### ISSUE TITLE
Ensure RequestIdPolicy and API Layer Use the Same Request ID Header

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-python#10009]
This is a copy of an issue filed against the Java repository so some details may differ.

Search clients that aren't using their own custom pipeline will be created with a `RequestIdPolicy`, the policy is built with the name of the request ID header it should set (the default is `x-ms-client-request-id`). Search APIs also have the ability to accept `RequestOptions` which has a configuration of the request ID value that should be used, right now this will set the header `client-request-id`. Before Search GAs it should be verified that the policy and the API layer will set the same header.

**Comment by bryevdv** [comment]
@lmazuel AFAICT from looking at test recordings, without passing any custom configuration what it currently set is just `"request-id"`. I'm not sure if there is anything to do here, or not. Thoughts?

**Comment by lmazuel** [comment]
If I understand @alzimmermsft correctly, it _may_ be possible that the right header name to pass the request id won't be `x-ms-client-request-id` but something else. the `request_id` kwargs is currently not configurable, and we fill `x-ms-client-request-id` (it's hard coded).

Assuming I got the issue right, we could remove that policy and use the customer header just in the context of search, or make [RequestIdPolicy](https://github.com/Azure/azure-sdk-for-python/blob/65e75e9dbfb94d42040a4022cf4ee3f0705516ed/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L111) configurable. I'd rather avoid too much configuration here.

**Comment by alzimmermsft** [comment]
@bryevdv @lmazuel, I believe this issue can be closed now that the Swagger is using `x-ms-client-request-id` instead of `client-request-id`. The older version of the Swagger used the passed request ID to set the `client-request-id` and this issue was meant to track making sure the passed request ID and the default generated ID, if one wasn't passed, we're using the same header to prevent less than ideal scenarios where both would get set.

Code in Python setting the right header value: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/search/azure-search-documents/azure/search/documents/_index/_generated/operations/_documents_operations.py#L78
