### ISSUE TITLE
Patch tox to handle incorrect encoding during parallel run

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#10013]
[This PR](https://github.com/Azure/azure-sdk-for-python/pull/10007)

Encapsulates a test fix for a tox issue that we've discovered. Specifically, when an encoding error occurs during the `pytest` run, both executions exit with 0. If there is an encoding error, this is a real failure! 

1. Fully investigate the variables at play
2. Either A) adjust CI to resolve the situation causing this not to bubble up or
3. B) Submit a patch to tox dev.

**Comment by schinckel** [comment]
If you use Python 3 to install tox instead of Python 2, then this problem goes away (without having to patch).

Even if your project still runs under Python 2, you can install tox into python 3, and have it generate PY2 environments.

**Comment by scbedd** [comment]
@schinckel I'm going to give this suggestion a shot. IIRC this error was actually occurring during the run, so the encoding error we were seeing isn't coming from the env  creation. However, I definitely could see the `venv`-rolled `py27` environment being different than the devops-installed one. Thanks!

**Comment by scbedd** [comment]
We no longer support python 27. Closing as this only occured on py27 machines.
