### ISSUE TITLE
Queue Storage Encoding

### ISSUE THREAD

**Issue by F-Schmidt1** [Azure/azure-sdk-for-python#10029]
I have already posted the following in the azure-storage-python github, but did get a response there, so i thought i'd give it a try here.

- **Package Name**:  azure.storage.queue
- **Package Version**: 12.1.0
- **Operating System**: Windows
- **Python Version**: 3.7.3

#### Repro:
Following the documentation at https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-queue#sending-messages

```
from azure.storage.queue import QueueClient
queue = QueueClient.from_connection_string(conn_str="<connection_string>", queue_name="my_queue")
queue.send_message('msg')
queue.send_message('msg2')
queue.send_message('msg10')
```
The first message shows up correctly, while the second message seems to not be encoded correctly. This happens every time a queue message with the content 'msg2' is sent.

![queue-msg](https://user-images.githubusercontent.com/61054913/74838576-19807b00-5324-11ea-9ab0-752141e351b0.PNG)

EDIT:
When viewing the messages in the storage explorer, it is stated that the messages are stored  'without encoding'. 
I tried to enforce Base64 encoding, by ammending the call to the QueueClient:
```
from azure.storage.queue import QueueClient, TextBase64EncodePolicy
queue = QueueClient.from_connection_string(conn_str="<connection_string>", queue_name="my_queue", encode_policy=TextBase64EncodePolicy)
```
However, this does not affect the encoding of the messages. What am i missing?
If the messages aren't Base64 encoded, they cannot be used as a queuetrigger in Azure-functions, which is what I intend to use them for.

**Comment by annatisch** [comment]
Thanks @F-Schmidt1 - it looks like the documentation is incorrect, the correct parameter is `message_encode_policy`:
```python
from azure.storage.queue import QueueClient, TextBase64EncodePolicy
queue = QueueClient.from_connection_string(
    conn_str="<connection_string>",
    queue_name="my_queue",
    message_encode_policy=TextBase64EncodePolicy
)
```
I have opened a PR here to fix the docs: #10031

**Comment by annatisch** [comment]
Hi @F-Schmidt1 - did using the parameter `message_encode_policy` resolve this issue for you?

**Comment by F-Schmidt1** [comment]
> 
> 
> Hi @F-Schmidt1 - did using the parameter `message_encode_policy` resolve this issue for you?

Sorry for the delayed feedback - changing the parameter to message_encode_policy solved the issue. Thank you for your help!
