### ISSUE TITLE
Publish core dumps from Linux and MacOS builds

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#10045]
I currently have a branch [here](https://github.com/Azure/azure-sdk-for-python/tree/get_mac_core_dump) that specifically does this for Mac builds. This will assist an investigation into a uamqp segfault that is occurring in the servicebus livetests.

This is the second such ask since december. Time to just add these to the pipelines.

**Comment by scbedd** [comment]
Provided Yijun and Adam with a build that can get them a core dump. Moving back to backlog as there are higher priorities right now.

**Comment by lmazuel** [comment]
Closing, we'll see if really needed
