### ISSUE TITLE
Support UseDevelopmentStorage=true; as connection string

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#10040]
- **Package Name**: azure.storage.blob
- **Package Version**: 12.2
- **Operating System**: windows
- **Python Version**: 3.8

**Describe the bug**

We should support local emulation with azure storage explorer and azurite.  This was possible in old sdk.

Reported by customer here: https://stackoverflow.com/questions/60437824/blob-storage-connection-to-emulator-local-development-fail

**To Reproduce**

Run the storage emulator or azurite
Run this code:
```python
import os, uuid
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient

try:
    container_client = ContainerClient.from_connection_string("UseDevelopmentStorage=true;", "foo")
    container_client.create_container()

except Exception as ex:
    print('Exception:')
    print(ex)
```

You get this exception.
```
Connection string missing required connection details.
```

**Expected behavior**

It should work.

**Workaround**

Use full connection string:

```
container_client = ContainerClient.from_connection_string("DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;", "foo")
```

Related:
https://github.com/Azure/azure-sdk-for-python/issues/372
https://github.com/Azure/azure-sdk-for-python/issues/375

It was resolved in old sdk with `is_emulated` flag or EMULATED env variable
https://github.com/Azure/azure-storage-python/issues/6

You can view the is_emulated impl here: https://github.com/Azure/azure-storage-python/search?utf8=%E2%9C%93&q=is_emulated&type=

**Comment by xiafu-msft** [comment]
Hi @jongio 

Thanks for your feedback! We will add this task to our backlog!

**Comment by ronbuchanan** [comment]
Where does this stand?

**Comment by Chotom** [comment]
Any update on this topic?

**Comment by Jan-Jasek** [comment]
@xiafu-msft Still lingering in the back log I assume?

**Comment by ddelange** [comment]
interestingly, according to [tests](https://github.com/Azure/azure-sdk-for-python/blob/ff1e01c5755066eea4e16a3be3314933e54aa791/sdk/storage/azure-storage-blob/tests/test_blob_client.py#L353), it should be supported in blob, queue, and tables 🤔

**Comment by Macht59** [comment]
No update in 4 years. What a shame.

**Comment by ddelange** [comment]
I had a look at the link I posted in my last comment: it should be pretfy straight forward to amend that test: to assert that the client ends up with a proper full conn string.

I'm no maintainer but I'm sure that PRs are welcome :+1:
