### ISSUE TITLE
When can we expect a cosmos 4.* release?

### ISSUE THREAD

**Issue by brandonmbanks** [Azure/azure-sdk-for-python#10060]
It looks like 4.0 is going to give us a lot of things that are needed.  It looks like the [last preview release](https://pypi.org/project/azure-cosmos/4.0.0b6/) was back on November 18th.

**When can we expect that release? Where should we be looking for code releases?**

I opened an [issue](https://github.com/Azure/azure-cosmos-python/issues/188) on the old cosmos client library repo but moved it here because I haven't heard anything.

We are eagerly awaiting 4.0 and increased python support. Thank you all for the hard work.

**Comment by kaerm** [comment]
**When:**
@brandonmbanks thanks for reaching out to us. Looping in @mayurid who should know the most up-to-date plans on Azure Cosmos v4.0 release.

**Where:**
You can find the list of releases here: https://aka.ms/azsdkpackages
We also publish release notes with releases every month that you can find in the left menu after following the link above.

**Comment by brandonmbanks** [comment]
Following up on this. @kaerm @mayurid

**Comment by brandonmbanks** [comment]
Bump @kaerm @mayurid

**Comment by brandonmbanks** [comment]
Bump @kaerm @mayurid. Still haven't received any answer on this.

**Comment by mayurid** [comment]
We are planning for a release later this month. Will keep you posted on when it goes out.
//: @srinathnarayanan and @annatisch

**Comment by brandonmbanks** [comment]
That is really good news. This would be a full release or another preview release? @mayurid

We look forward to hearing back from

**Comment by kaerm** [comment]
It will be a full release this time @brandonmbanks

**Comment by kaerm** [comment]
@brandonmbanks the 4.0.0 full cosmos release is done - you can find the documentation and more information here: https://aka.ms/azsdk/python. I am closing this issue but feel free to follow up if you have any other questions
