### ISSUE TITLE
option to provide list of source directories in Estimator's constructor

### ISSUE THREAD

**Issue by martinResearch** [Azure/azure-sdk-for-python#10071]
**Is your feature request related to a problem? Please describe.**

Some of my AzureML experiments depend on code from several folders that are on very different location on my machine (even on different drives). At the moment I have to make a temporal copy of all the files into a single temporary folder that I then provide to the Estimator constructor through the source_directory option. When running locally to do debugging I often end up debugging the copied files instead of the original files by mistake.

**Describe the solution you'd like**

I would like to be able to avoid the "manual" copy step by being able to provide several source folders to the constructor, for example by providing a list of strings  in the source_directory argument instead of a string . The azureml sdk code would then apply the existing mechanism but on each folder of the list. It would need to raise an error if there are collision in the subfolders names

**Describe alternatives you've considered**

An even more flexible way to provide the dependencies would be for the user to provide a list of files as a list of  (source,target) pairs. It could be a list of pairs or a python generator to be even more flexible. The AzureML SDK could then potentially provide  various utility functions to generate this list (using list of folder containing .amlignore files or using a list of globs expressions for example)

**Comment by martinResearch** [comment]
A better solution that would be easy for the user to undersand could be to keep a single folder in source_directory (that should contain script entry file), and add a new argument ("local_dependencies_folders" for example) that correspond to a list of other folders that need to be copied too. each of these folder can contain an .amlignore file.

**Comment by lostmygithubaccount** [comment]
hi @martinResearch Estimators are deprecated, the recommended path is to use a `ScriptRunConfig`

is this still an issue you're facing?

**Comment by martinResearch** [comment]
hi @lostmygithubaccount , I had a look at the the `ScriptRunConfig `documentation and it does not seem to provide a mechanism to provide other source folder containing local dependencies either.

**Comment by v-strudm-msft** [comment]
Internal MSFT: https://msdata.visualstudio.com/Vienna/_workitems/edit/1121233

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by luigiw** [comment]
Closing as Estimators are deprecated.
