### ISSUE TITLE
docs.microsoft.com doesn't document keyword only args.

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#10087]
IT seems like docs.microsoft.com is not documenting kwargs anywhere.

Here are some examples:

Storage:
https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#get-page-ranges-offset-none--length-none--previous-snapshot-diff-none----kwargs-

Keyvault:
https://docs.microsoft.com/en-us/python/api/azure-keyvault-keys/azure.keyvault.keys.keyclient?view=azure-python#list-properties-of-keys---kwargs-

**Comment by rakshith91** [comment]
@maggiepint @scbedd @kaerm

**Comment by kaerm** [comment]
And here is an example of customer confusion:

> Looking at the docs for [dowload_blob ](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#download-blob-offset-none--length-none----kwargs-)it's not apparent that it accepts a `max_concurrency` argument. Is there a better way I could have discovered this?

**Comment by scbedd** [comment]
We have an item [filed](https://ceapex.visualstudio.com/Engineering/_workitems/edit/168574) against the docs team for this. I thought I had an issue filed against this repo to track on our side, but obviously not. Thanks @rakshith91

**Comment by scbedd** [comment]
[This PR](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/707) Resolve this issue!
