### ISSUE TITLE
Clarity around in-memory checkpointing

### ISSUE THREAD

**Issue by kiranpvsr** [Azure/azure-sdk-for-python#10109]
Hi

I'm just after information regarding the reliability/stability of in-memory checkpointing.
Assuming that this is something that is stored on Eventhub, is it safe to assume that the checkpoint information is always the current one as marked by client using "partition_context.update_checkpoint(event)".
What happens to the checkpoint information when the Azure/Eventhub servers are rebooted/crashed ?

**Comment by kaerm** [comment]
@kiranpvsr thanks for reaching out, someone from our team will take a look at this //cc: @yunhaoling @YijunXieMS

**Comment by YijunXieMS** [comment]
Hi @kiranpvsr , sorry I just realized that I missed this issue.  

The in-memory checkpoint store stores data in the memory of the computer that runs the SDK. It doesn't save data when your server is rebooted/crashed. It doesn't store data in the event hub server either. It's only useful when exception happens during event processing and reconnect to the eventhub.

BlobCheckpoitStore of package [azure-eventhub-checkpointstoreblob](https://pypi.org/project/azure-eventhub-checkpointstoreblob/) persists checkpoint data into blobs of Azure Storage Blob. You may use it for your scenario.

**Comment by kiranpvsr** [comment]
Thank you for that information. If its saved in the memory of the computer that runs the SDK, if the computer isn't restarted or the memory cache isn't flushed, then checkpointing should work isn't it ?
In my case, I've stopped the script that connects to Eventhub and started it after an hour. But instead of fetching events from when it was stopped, it started to fetch events based on the latest time when it was started again.

**Comment by YijunXieMS** [comment]
Sorry for confusing you by saying "in the memory of the computer". More specifically, it works in the scope of the receive( ) method. It's just to maintain the internal status for that receive call, which can recover from exceptions and use the checkpoint internally.
