### ISSUE TITLE
face_client.person_group_person.add_face_from_stream giving error Image size is too small

### ISSUE THREAD

**Issue by 96vksingh** [Azure/azure-sdk-for-python#10108]
- **Macosx**:
- **Python 3.7**: 

**Describe the bug**
Whenever i try to add face i receive error image size is too small for this error i did not find any reference n azure docs

**To Reproduce**
1. try running this syntax for any image face_client.person_group_person.add_face_from_stream([person_group_id],[personid],[img])
use person_group_id,person_id,img of yours
sample code:
for file in files:
		w = open(file, 'r+b')
		res = face_client.face.detect_with_stream(w)
		if len(res) != 1:
        		print("No face detected in image")
		else:
			face_client.person_group_person.add_face_from_stream("test1", person_id,w,)

**Screenshots**
![Screenshot 2020-03-05 at 6 25 12 PM](https://user-images.githubusercontent.com/29673760/75983544-bdfee180-5f0e-11ea-8fdc-5fb7c7f0f307.png)

**Comment by xiangyan99** [comment]
Since this was opened more than three years ago.

Could you help to check if this is still valid?
