### ISSUE TITLE
adf_client.data_flows.create_or_update throws error msrestazure.azure_exceptions.CloudError: Azure Error: BadRequest

### ISSUE THREAD

**Issue by brijan** [Azure/azure-sdk-for-python#10106]
- **Package Name**: \azure\mgmt\datafactory
- **Package Version**:  
- **Operating System**: windows
- **Python Version**: 3

**Describe the bug**
 File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\mgmt\datafactory\operations\_data_flows_operations.py", line 107, in create_or_update
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: BadRequest
Message: The document creation or update failed because of invalid reference ''.

**Comment by kaerm** [comment]
@brijan thanks for reporting this, I am looping in the right team to take a look at this //cc: @nickzhums

**Comment by brijan** [comment]
@nickzhums please let me know if you need more information

**Comment by nickzhums** [comment]
@RodgeFu could you let someone take a look to see if it is service related, thanks

**Comment by qiaozha** [comment]
I will take a look at this.

**Comment by qiaozha** [comment]
@brijan  Can you show me your code of using this package and how your parameters look like?

**Comment by brijan** [comment]
`from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.datafactory import DataFactoryManagementClient
from azure.mgmt.datafactory.models import *
from datetime import datetime, timedelta
import time




def main():

    # Azure subscription ID
    subscription_id = 'subscription_id'

    # This program creates this resource group. If it's an existing resource group, comment out the code that creates the resource group
    rg_name = 'rg_name'

    # The data factory name. It must be globally unique.
    df_name = 'df_name'

    # Specify your Active Directory client ID, client secret, and tenant ID
    adf_client = getAdfClient(subscription_id)

    # Step 1 cretate linked service
    # name will be used to refrence linked service later in the code
    ls_name = 'storageLinkedService'
    linked_service_ref = getLinkedServiceRef(
        adf_client, rg_name, df_name, ls_name)
    # Linked Service creation done#

    # Step 2 Create Data sets
    blob_path = '/pub/sample/'
    bbr_dataset_name = 'set'
    filesystem_name = 'filesystem'
    blob_filename_bbr = 'samplebbrdaekning.csv'
    bbr_dataset = createDelimitedDataSet(blob_path, blob_filename_bbr, filesystem_name,
                                         linked_service_ref, adf_client, rg_name, df_name, bbr_dataset_name)

    cognito_dataset_name = 'cognitodataset'
    blob_filename_cognito = 'sample_cognito.csv'
    cognito_dataset = createDelimitedDataSet(blob_path, blob_filename_cognito, filesystem_name,
                                             linked_service_ref, adf_client, rg_name, df_name, cognito_dataset_name)

# Create an Azure blob dataset (output)
    joined_ds_name = 'somefolder'
    output_blobpath = '/filesystem/pub/somefolder/'
    somefolder_filename = 'somefolder.csv'

    somefolder_ds = createDelimitedDataSet(output_blobpath, somefolder_filename, filesystem_name,
                                             linked_service_ref, adf_client, rg_name, df_name, joined_ds_name)

    bbr_ref = DatasetReference(reference_name=bbr_dataset)
    cognito_ref = DatasetReference(reference_name=joined_ds_name)
    out_ref = DatasetReference(reference_name=joined_ds_name)

    # define source and sink for mapping data flow
    bbr_dfs = DataFlowSource(name='bbrdfs', dataset=bbr_ref)
    cognito_dfs = DataFlowSource(name='cognitodfs', dataset=cognito_ref)
    output_sink = DataFlowSink(name='sink', dataset=out_ref)

    # ctreate transformations
    join_tmn = Transformation(name="join1")

    dataflow_name = 'joindataflow'
    data_flow = MappingDataFlow(description='description',
                                sources=[bbr_ref, cognito_ref], sinks=[output_sink], transformations=[join_tmn], script="source(output(\n\t\tColumn_1 as string,\n\t\tColumn_2 as string\n\t),\n\tallowSchemaDrift: true,\n\tvalidateSchema: false) ~> source1\nsource(output(\n\t\tColumn_1 as string,\n\t\tColumn_2 as string\n\t),\n\tallowSchemaDrift: true,\n\tvalidateSchema: false) ~> source2\nsource1, source2 join(source1@Column_1 == source2@Column_1,\n\tjoinType:'inner',\n\tbroadcast: 'none')~> Join1\nJoin1 sink(input(\n\t\tColumn_1 as string\n\t),\n\tallowSchemaDrift: true,\n\tvalidateSchema: false,\n\tskipDuplicateMapInputs: true,\n\tskipDuplicateMapOutputs: true) ~> sink1")

    data_flow_created = adf_client.data_flows.create_or_update(
        resource_group_name=rg_name, factory_name=df_name, data_flow_name=dataflow_name, properties=data_flow)

    data_flow_ref = DataFlowReference(reference_name=dataflow_name)
    act_name = 'mappningActivity'
    data_flow_activity = ExecuteDataFlowActivity(
        name=act_name, data_flow=data_flow_ref)

    p_name = 'joinData'
    params_for_pipeline = {}

    p_obj = PipelineResource(
        activities=[data_flow_activity], parameters=params_for_pipeline)
    p = adf_client.pipelines.create_or_update(rg_name, df_name, p_name, p_obj)
    print_item(p)

    run_response = adf_client.pipelines.create_run(
        rg_name, df_name, p_name, parameters={})
# while(1):

    #     time.sleep(30)
    #     pipeline_run = adf_client.pipeline_runs.get(
    #         rg_name, df_name, run_response.run_id)
    #     print("\n\tPipeline run status: {}".format(pipeline_run.status))
    #     filter_params = RunFilterParameters(
    #         last_updated_after=datetime.now() - timedelta(1), last_updated_before=datetime.now() + timedelta(1))
    #     query_response = adf_client.activity_runs.query_by_pipeline_run(
    #         rg_name, df_name, pipeline_run.run_id, filter_params)
    #     print_activity_run_details(query_response.value[0])


def createDelimitedDataSet(blob_path, blob_filename_bbr, filesystem_name, linked_service_ref, adf_client, rg_name, df_name, bbr_dataset_name):
    bbr_dataset_location = AzureBlobFSLocation(
        folder_path=blob_path, file_name=blob_filename_bbr, file_system=filesystem_name)
    bbr_dataset = DelimitedTextDataset(
        linked_service_name=linked_service_ref, location=bbr_dataset_location)
    bbr_ds_created = adf_client.datasets.create_or_update(
        rg_name, df_name, bbr_dataset_name, bbr_dataset)
    print_item(bbr_ds_created)
    return bbr_dataset


def getAdfClient(subscription_id):
    # Specify your Active Directory client ID, client secret, and tenant ID
    credentials = ServicePrincipalCredentials(client_id='client id,
                                              secret='principal', tenant='tenant')
    resource_client = ResourceManagementClient(credentials, subscription_id)
    adf_client = DataFactoryManagementClient(credentials, subscription_id)
    return adf_client


def getLinkedServiceRef(adf_client, rg_name, df_name, ls_name):
    ls_azure_storage = AzureBlobFSLinkedService(
        url='https://account.dfs.core.windows.net', service_principal_key=SecureString(value='secure string'), service_principal_id='principal', tenant='tenant')

    ls = adf_client.linked_services.create_or_update(resource_group_name=rg_name,
                                                     factory_name=df_name, linked_service_name=ls_name, properties=ls_azure_storage)
    print(type(ls_azure_storage))
    linked_service_ref = LinkedServiceReference(reference_name=ls_name)
    return linked_service_ref


def print_item(group):
    """Print an Azure object instance."""
    print("\tName: {}".format(group.name))
    print("\tId: {}".format(group.id))
    if hasattr(group, 'location'):
        print("\tLocation: {}".format(group.location))
    if hasattr(group, 'tags'):
        print("\tTags: {}".format(group.tags))
    if hasattr(group, 'properties'):
        print_properties(group.properties)


def print_properties(props):
    """Print a ResourceGroup properties instance."""
    if props and hasattr(props, 'provisioning_state') and props.provisioning_state:
        print("\tProperties:")
        print("\t\tProvisioning State: {}".format(props.provisioning_state))
    print("\n\n")


def print_activity_run_details(activity_run):
    """Print activity run details."""
    print("\n\tActivity run details\n")
    print("\tActivity run status: {}".format(activity_run.status))
    if activity_run.status == 'Succeeded':
        print("\tNumber of bytes read: {}".format(
            activity_run.output['dataRead']))
        print("\tNumber of bytes written: {}".format(
            activity_run.output['dataWritten']))
        print("\tCopy duration: {}".format(
            activity_run.output['copyDuration']))
    else:
        print("\tErrors: {}".format(activity_run.error['message']))
main()

`

**Comment by brijan** [comment]
@qiaozha  code in failing at data_flow_created = adf_client.data_flows.create_or_update
and I am using DelimitedTextDataset as dataset and AzureBlobFSLinkedService as I have data lake gen 2 as data source
'def main():

    # Azure subscription ID
    subscription_id = 'subscription_id'

    # This program creates this resource group. If it's an existing resource group, comment out the code that creates the resource group
    rg_name = 'rg_name'

    # The data factory name. It must be globally unique.
    df_name = 'df_name'

    # Specify your Active Directory client ID, client secret, and tenant ID
    adf_client = getAdfClient(subscription_id)

    # Step 1 cretate linked service
    # name will be used to refrence linked service later in the code
    ls_name = 'storageLinkedService'
    linked_service_ref = getLinkedServiceRef(
        adf_client, rg_name, df_name, ls_name)
    # Linked Service creation done#

    # Step 2 Create Data sets
    blob_path = '/pub/sample/'
    bbr_dataset_name = 'set'
    filesystem_name = 'filesystem'
    blob_filename_bbr = 'samplebbrdaekning.csv'
    bbr_dataset = createDelimitedDataSet(blob_path, blob_filename_bbr, filesystem_name,
                                         linked_service_ref, adf_client, rg_name, df_name, bbr_dataset_name)

    cognito_dataset_name = 'cognitodataset'
    blob_filename_cognito = 'sample_cognito.csv'
    cognito_dataset = createDelimitedDataSet(blob_path, blob_filename_cognito, filesystem_name,
                                             linked_service_ref, adf_client, rg_name, df_name, cognito_dataset_name)

# Create an Azure blob dataset (output)
    joined_ds_name = 'somefolder'
    output_blobpath = '/filesystem/pub/somefolder/'
    somefolder_filename = 'somefolder.csv'

    somefolder_ds = createDelimitedDataSet(output_blobpath, somefolder_filename, filesystem_name,
                                             linked_service_ref, adf_client, rg_name, df_name, joined_ds_name)

    bbr_ref = DatasetReference(reference_name=bbr_dataset)
    cognito_ref = DatasetReference(reference_name=joined_ds_name)
    out_ref = DatasetReference(reference_name=joined_ds_name)

    # define source and sink for mapping data flow
    bbr_dfs = DataFlowSource(name='bbrdfs', dataset=bbr_ref)
    cognito_dfs = DataFlowSource(name='cognitodfs', dataset=cognito_ref)
    output_sink = DataFlowSink(name='sink', dataset=out_ref)

    # ctreate transformations
    join_tmn = Transformation(name="join1")

    dataflow_name = 'joindataflow'
    data_flow = MappingDataFlow(description='description',
                                sources=[bbr_ref, cognito_ref], sinks=[output_sink], transformations=[join_tmn], script="source(output(\n\t\tColumn_1 as string,\n\t\tColumn_2 as string\n\t),\n\tallowSchemaDrift: true,\n\tvalidateSchema: false) ~> source1\nsource(output(\n\t\tColumn_1 as string,\n\t\tColumn_2 as string\n\t),\n\tallowSchemaDrift: true,\n\tvalidateSchema: false) ~> source2\nsource1, source2 join(source1@Column_1 == source2@Column_1,\n\tjoinType:'inner',\n\tbroadcast: 'none')~> Join1\nJoin1 sink(input(\n\t\tColumn_1 as string\n\t),\n\tallowSchemaDrift: true,\n\tvalidateSchema: false,\n\tskipDuplicateMapInputs: true,\n\tskipDuplicateMapOutputs: true) ~> sink1")

    data_flow_created = adf_client.data_flows.create_or_update(
        resource_group_name=rg_name, factory_name=df_name, data_flow_name=dataflow_name, properties=data_flow)

    data_flow_ref = DataFlowReference(reference_name=dataflow_name)
    act_name = 'mappningActivity'
    data_flow_activity = ExecuteDataFlowActivity(
        name=act_name, data_flow=data_flow_ref)'

**Comment by qiaozha** [comment]
Thanks for sharing the code. I will look into it

**Comment by brijan** [comment]
Any update ? or am I doing wrong?

**Comment by qiaozha** [comment]
Can you try to change this line
```
data_flow = MappingDataFlow(description='description',
                            sources=[bbr_ref, cognito_ref], sinks=[output_sink], 
```
into 
```
data_flow = MappingDataFlow(description='description',
                            sources=[bbr_dfs, cognito_dfs], sinks=[output_sink], 
```
to see if it works? 
Looks like the references format for sources and sinks is inconsistent.

**Comment by brijan** [comment]
Okay i will try that and let you know
