### ISSUE TITLE
Service Bus: 401 auth error

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-sdk-for-python#1012]
Filing this issue on behalf of an MSDN question:

https://social.msdn.microsoft.com/Forums/en-US/72fcff3e-6724-4bbb-a3d3-fe7709c9f048/connectivity-issues-to-the-service-bus-from-python

> I have some python scripts which use Topics and Subscriptions on the Azure Service Bus, I'm using a standard Azure Library and I can replicate my networking issue with a very simple script.
> 
> If I execute this script it will work find after a period of time,  but after an initial connection to a number of wifi networks, it simply fails to run,  and I get 401 Authorization errors.    
> 
> It's  definitely not an Authorization issue, my shared access policy has not changed,  and if I leave it alone for a period of time, it will work perfectly afterwards.
> 
> So my question is, how can I turn on debugging for this very simple script , to see more information at a DEBUG level on whats happening during the connection ?
> 
> I can ping the endpoint, but thats not reallt the same as connecting.
> 
> Any help , or pointers towards python documentation would be great.
> 
> Thanks
> 
> Martin 
> ```py
> #!/usr/bin/python
> from azure.servicebus import ServiceBusService, Message, Topic, Rule, DEFAULT_RULE_NAME
> 
> bus_service = ServiceBusService(
>     service_namespace='v2testbus',
>     shared_access_key_name='RootManageSharedAccessKey',
>     shared_access_key_value='keygoeshere')
> 
> msg = Message(b'Test Message')
> bus_service.send_queue_message('taskqueue', msg)
> ```
>
>I'd also like to see a way to speed up the throughput, as performace isn't great.
>
>Do you have a callback method so I can process message asynchronously ? or even an example with multithreaded handling ?
>
>It looks like this library does a logon for every bus_service.send_topic_message(topic_name, msg) , so the performance suffers.  Can I open a connection, send messages and then close it ?

**Comment by lmazuel** [comment]
@huguesv do you remember?

**Comment by huguesv** [comment]
Service bus client uses the requests library, so it should take advantage of its connection pooling, which speeds up a little.  But you are right that it will authenticate on every call.

It looks like you may be able to do tracing relatively easily, see http://stackoverflow.com/questions/10588644/how-can-i-see-the-entire-http-request-thats-being-sent-by-my-python-application

Service bus team used to point people to the Apache Proton library, as service bus supports AMQP 1.0, for better performance.  Not sure about now.  The links at the bottom of the page are out of date.  https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-overview

**Comment by jtaubensee** [comment]
@lmazuel / @huguesv - I'm a PM on the Service Bus team. For our customers who are looking for high throughput, we have recommended proton-python in the past, however we dont have great guidance for it. This is something we hope to address in the coming year. I am guessing that the customer from the MSDN post, may not respond to this issue, so I will close it for now. Thanks for your help.
