### ISSUE TITLE
extract network traffic details of ESXi host and VMs in host

### ISSUE THREAD

**Issue by navya-goli** [Azure/azure-sdk-for-python#1013]
Hi ,

I want to extract the network traffic details of ESXi server and guest VMs in it using python script.

I am able to extract network transmitted and received data of an ESXi guest vm and ESXi host.

But I am unable to extract network latency, throughput and packet loss.

I did a lot of research but unable to get them.

Please provide me the assistance to extract the above mentioned metrics.

Thanks.

**Comment by kmouss** [comment]
@navya-goli, Thank you for your feedback. What do you mean by ESXi server for Azure VMs; this isn't the HyperVisor used. If you are looking for host level metrics for the VM, this is the list we currently support: https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics. To get additional metrics by enabling detailed guest monitoring, see more details from here: https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-vm-monitoring?toc=%2fazure%2fvirtual-machines%2flinux%2ftoc.json
We plan to add additional metrics in future, but this is the current list supported currently.

**Comment by lmazuel** [comment]
Closing the issue since I think the answer is accurate to the question. Feel free to comment if you want this issue re-opened or open an new issue for a new question.
Thank you,
