### ISSUE TITLE
In memory Checkpointing doesn't seem to work

### ISSUE THREAD

**Issue by kiranpvsr** [Azure/azure-sdk-for-python#10168]
- **Package Name**: azure-eventhub
- **Package Version**: 5.0
- **Operating System**: Ubuntu 16
- **Python Version**: 3.5

**Describe the bug**
In memory checkpointing is only fetching data from the current datetime.

**To Reproduce**
1. stop the receiver today. start it tomorrow. the incoming logs will have a timestamp as of tomorrow.

**Expected behavior**
the receiver should be pulling logs from when it was last stopped when checkpointing is in use based on the below code from docs
```python
    def on_event(self, partition_context, event):
        #elf.logger.info("Received event from partition".format(partition_context.partition_id))
        self.process_event_data(event)
        partition_context.update_checkpoint(event)
```

**Screenshots**

**Additional context**

**Comment by YijunXieMS** [comment]
Hi @kiranpvsr , thanks for the feedback. And sorry that I missed your question of in-memory checkpoint. I just replied in that issue.
Let me know if you have more questions.
