### ISSUE TITLE
LocalGatewayOperations.delete returns "An error occured."

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#1016]
When I try to delete a local network gateway, I observe the following repeatable behavior:
Attempt 1) Polls and finally returns a 200 response with the message "An error occured." (shows as failed status in the portal)
Attempt 2) Polls and finally returns a 200 response with no body (succeeds)
Attempt 3) Returns 204 because the gateway has already been deleted.

**Comment by tjprescott** [comment]
On a subsequent attempt, it failed multiple times with the 200 response and "An error occured."

**Comment by lmazuel** [comment]
Hi @tjprescott 
What is your guess, Swagger issue? RestAPI issue (not following ARM guideline)? Async implementation issue in Python?

**Comment by tjprescott** [comment]
My guess is there's a bug on the service side. It seems like there's a unhandled exception catch-all that returns the 200 response with "An error occured." (sic)  I've seen it in ExpressRoutes as well for conditions that should have been caught by server-side validation but weren't. Can't imagine what that would be for a local gateway though.

**Comment by lmazuel** [comment]
Seems reasonable :)
I suggest you to start an email thread with the Network team (put me in CC please :)).

**Comment by tjprescott** [comment]
I created an ICM ticket and will track the resolution of this in our repo.
