### ISSUE TITLE
VM deployment from the community (VM Depot)

### ISSUE THREAD

**Issue by lee212** [Azure/azure-sdk-for-python#102]
Hi,

I was wondering if azure-sdk-for-python supports creating a VM from VM Depot like azure-cli. There must be looking up the community image, copying the blob to a storage account and then deploying cloud service and VM but I am not able to find such a function in azure-sdk-for-python. 

Thanks,
Hyungro

**Comment by lmazuel** [comment]
I just have a conversation with the VMDepot team, the service will shut down in a couple of month.

Sorry if we missed the opportunity to provide the VMDepot support during its lifetime. :(

**Comment by MariuszFerdyn** [comment]
New version of VmDepot is here https://vmplace.eu/

**Comment by lmazuel** [comment]
Hi @MariuszFerdyn 

Thank you for your message and this work :)

**Comment by MariuszFerdyn** [comment]
You are welcome! And if you have any images just add it please.
