### ISSUE TITLE
Azure DL Storage Gen2 runs into timeout on get_paths

### ISSUE THREAD

**Issue by damnedOperator** [Azure/azure-sdk-for-python#10219]
- **Package Name**: 
from azure.storage.filedatalake import DataLakeServiceClient
- **Package Version**: 
azure-storage-file-datalake==12.0.0b6
- **Operating System**:
Unix/Debian/Ubuntu
- **Python Version**: 
Python 3.7.3

**Describe the bug**
[1]
```python
service_client = DataLakeServiceClient(account_url=accountURL, credential=storageKey)
fsClient = service_client.get_file_system_client(file_system=filesystem)
        paths = fsClient.get_paths(path=directory)
```
When running this code on ADLS Gen2 I run into a timeout:

`azure.storage.filedatalake._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'Operation could not be completed within the specified time.'`

Same thing happens sometimes when trying to view the content of the DL in Storage explorer.
`﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>OperationTimedOut</Code><Message>Operation could not be completed within the specified time. RequestId:c529aebd-e01e-0063-0ab7-f66173000000...`

The datalake folder containing avro files from EventHub has about 60 pages and 5,986 Elements

**To Reproduce**
1. run the snippet from above [1] to a datalake gen2 with about 5,986 elements with an element size from 508B to 132KB

**Expected behavior**
The generator with paths from the DL folder should be created in variable `paths`

**Screenshots**
![image](https://user-images.githubusercontent.com/49755051/76309453-177b5d80-62cd-11ea-8799-daf334857027.png)
Class Method in my actual program
![image](https://user-images.githubusercontent.com/49755051/76309515-3679ef80-62cd-11ea-8b38-e352986f1655.png)
Traceback when trying to debug on command line.

**Comment by amishra-dev** [comment]
Thanks @damnedOperator for reporting this. The issue seems to be that the service took a long time to respond. As an immediate workaround you can increase the timeout you pass to the service. Meanwhile I will check with the service team as to what is causing this delay.

**Comment by amishra-dev** [comment]
Hi @damnedOperator,
my friends on the service side are telling me your account got throttled when you hit this error. can you try again and see if you are still running into this? If you do, please send me the logs again like you did earlier and I can followup with the service team again.

**Comment by damnedOperator** [comment]
Hi @amishra-dev , thanks for responding so fast. I am checking the service right now, but it doesn't look promising. I didn't find any way to increase timeout values, am I missing something?

**Comment by amishra-dev** [comment]
@damnedOperator can you send me the log that has the RequestId again. I will check with the service team again tomorrow. Lets get you unblocked.

**Comment by damnedOperator** [comment]
@amishra-dev Hmm.. Seems like I cannot extract the request ID from my traceback on python...

**Comment by amishra-dev** [comment]
@damnedOperator how frequent is this issue for you? does it happen everytime? once an hour? or more frequently?

**Comment by damnedOperator** [comment]
@amishra-dev The issue occurs on every request I try to send.

**Comment by amishra-dev** [comment]
@damnedOperator in that case you can capture a fiddler and pull this info out of it. I need the guid with the lots of 0 at the end.

**Comment by amishra-dev** [comment]
meanwhile let me pull up your account and see whats going on there

**Comment by damnedOperator** [comment]
One Moment, I am currently trying to get them over the logger. Any news on the account?

**Comment by amishra-dev** [comment]
nothing that I could see wrong at my skill level, we will have to wait for the service folks to respond.

**Comment by damnedOperator** [comment]
Request ID is RequestId:31f106e9-101f-00fe-6a78-f71b33000000

´´´
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benjamin/.local/lib/python3.7/site-packages/azure/core/paging.py", line 122, in __next__
    return next(self._page_iterator)
  File "/home/benjamin/.local/lib/python3.7/site-packages/azure/core/paging.py", line 74, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/benjamin/.local/lib/python3.7/site-packages/azure/storage/filedatalake/_models.py", line 298, in _get_next_cb
    cls=return_headers_and_deserialized_path_list)
  File "/home/benjamin/.local/lib/python3.7/site-packages/azure/storage/filedatalake/_generated/operations/_file_system_operations.py", line 442, in list_paths
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.filedatalake._generated.models._models_py3.StorageErrorException: (OperationTimedOut) Operation could not be completed within the specified time.
RequestId:31f106e9-101f-00fe-6a78-f71b33000000
Time:2020-03-11T07:38:48.0289622Z
´´´

**Comment by amishra-dev** [comment]
Hi @damnedOperator,
The service team told me that you should not be hitting this error anymore. Please test, confirm and do let me know.

**Comment by damnedOperator** [comment]
HiHi I am currently on vacation, let me check in on monday.

Get Outlook for Android<https://aka.ms/ghei36>


Benjamin Reinecke 
PTV GROUP
 
IT Solutions
Haid- und Neu-Straße 15, 76131 Karlsruhe
Phone:+49 721 9651-7654
benjamin.reinecke@ptvgroup.com
www.ptvgroup.com
 --
 Explore the PTV Group in 2 minutes!
 Register for the PTV-Newsletter
  
 Follow us on social media:
 Linkedin
​ Twitter
 Xing
​ ​Instagram
 ​Facebook
--
   
​PTV Planung Transport Verkehr AG
Headquarters: Karlsruhe
Executive Board: Christian U. Haas (CEO), Dr. Peter Overmann, Klaus Lechner
​Chairman of the Supervisory Board: Philipp von Hagen
Commercial Register (HRB-Nr): 109262
Local Court: Mannheim
 
________________________________

**Comment by damnedOperator** [comment]
Hi @amishra-dev, yep, the error is not thrown anymore. I think it had something to do with my application cycle of 1 minute. Thanks.
