### ISSUE TITLE
Azure search mgmt live tests are failing 

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#10231]
Here is link to one of the failing builds:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=287371&view=logs&j=e4797745-1ad6-5989-d345-8ffe02e82111&t=dc7fc283-abe8-503f-8514-57700b43cb5c

cc @scbedd

**Comment by brjohnstmsft** [comment]
@bryevdv Our management plane Swagger was [updated recently](https://github.com/Azure/azure-rest-api-specs/pull/8572). Could that be related?

FYI @careyjmac

**Comment by Careyjmac** [comment]
It looks to me like none of the tests are failing but something is wrong in the generation?  @abhi1509 perhaps can comment?

**Comment by amotley** [comment]
Here's a helpful link to view the tests - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=287371&view=ms.vss-test-web.build-test-results-tab.

Based on the errors from the failing tests, there may be a UT setup issue with the resource groups being used:
No match for the request (<Request (PUT) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-search-t884e2f5f48464e7f/providers/Microsoft.Search/searchServices/ptvstestsearch?api-version=2015-08-19>) was found. Found 1 similar requests with 1 different matcher(s) : 1 - (<Request (PUT) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test_mgmt_search_test_search_services20f20f30/providers/Microsoft.Search/searchServices/ptvstestsearch?api-version=2015-08-19>

As a next step we need to figure out how those tests are generated so we can digging into this. Stay tuned...

**Comment by amotley** [comment]
Hey Bryan, can you kick off the tests again and see if they pass? I'm seeing another job where these passed this morning - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=288775&view=results

**Comment by scbedd** [comment]
That's because they were disabled to confirm a clean run. I've re-enabled them and kicked a build here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=288919&view=results

**Comment by scbedd** [comment]
Hey @amotley @bryevdv guidance from @lmazuel is that we don't need to livetest mgmt (generated code!) and mgmt packages should be excluded from the livetests. 

In this case @amotley I will return the build configuration to the state it was last night (excluding azure-mgmt-search). That also means you have no further action items here. Sorry for the inconvenience!
