### ISSUE TITLE
subscription class should return the tags associated with the subscription

### ISSUE THREAD

**Issue by nancybelser** [Azure/azure-sdk-for-python#10240]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nancybelser** [comment]
https://docs.microsoft.com/en-us/python/api/azure-mgmt-subscription/azure.mgmt.subscription.models.subscription?view=azure-python
This class does not include tags, although tags are included in the rest api:
![image](https://user-images.githubusercontent.com/41346295/76353830-d17fc300-62e7-11ea-8502-b330cb40f551.png)

**Comment by kaerm** [comment]
@nancybelser thanks for reporting this, @nickzhums could you take a look at this?

**Comment by nancybelser** [comment]
Any status updates on this?

**Comment by nickzhums** [comment]
@RodgeFu please have someone take a look at this, thanks!

**Comment by changlong-liu** [comment]
Hi @nancybelser , would you help to provide the link address for the rest api doc you showed? Thanks.

**Comment by nancybelser** [comment]
It is on this page: https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/get?view=azurermps-6.9.0

**Comment by nancybelser** [comment]
We are setting tag values on our subscriptions. I need to retrieve those values in a python script I am currently writing.

**Comment by changlong-liu** [comment]
Hi @nancybelser , the rest api you referred is actually belong to azure-mgmt-resource, not the azure-mgmt-subscription in your python doc link. 
And meanwhile, the SDK release is sometime behind the rest api release, the 'tags' feature has not been added into current azure-mgmt-resource SDK. It's expected that it can be included in the next release of azure-mgmt-resource.

**Comment by nancybelser** [comment]
I see this issue got added to the backlog.  Does that mean it will not be worked on anytime soon?

**Comment by lmazuel** [comment]
Hi @nancybelser 
No, it doesn't mean that, this is just the default milestone while we are investigating the issue we want to prioritize. I let @zikalino give you a more concrete answer on the status of the issue. Thanks!

**Comment by changlong-liu** [comment]
Hi @nancybelser , the subscription tag retrieving feature has been included in azure-mgmt-resource 9.0.0 released at early April.
https://pypi.org/project/azure-mgmt-resource/9.0.0/.

**Comment by nancybelser** [comment]
Hi @changlong-liu,

I upgraded to latest azure-mgmt-resource, but I noticed that the class I am using to list all subscriptions is in azure-mgmt-subscription.  

In this file, https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/_models.py:

I think this needs to change to include tags:
_attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'subscription_id': {'key': 'subscriptionId', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'state': {'key': 'state', 'type': 'SubscriptionState'},
        'subscription_policies': {'key': 'subscriptionPolicies', 'type': 'SubscriptionPolicies'},
        'authorization_source': {'key': 'authorizationSource', 'type': 'str'},


This is an excerpt of my script:
def get_subscriptions(credentials):
    subscription_client = SubscriptionClient(credentials)
    subscriptions = subscription_client.subscriptions.list()
    for subscription in subscriptions:
        print(subscription)

It does not return tags.

Thanks.

**Comment by changlong-liu** [comment]
yes, @nancybelser, azure-mgmt-subscriptions don't have tag yet. 
If you just want to retrieve subscription tags, would you have a try on azure-mgmt-resource? https://github.com/Azure/azure-sdk-for-python/blob/cd25de58e00d624511b5154e9fe8683826020bc0/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2019_11_01/models/_models_py3.py#L293

**Comment by nancybelser** [comment]
Just tried it and it worked. Thanks!

**Comment by changlong-liu** [comment]
Thanks for feedback @nancybelser , I close this issue for now.
