### ISSUE TITLE
is there a method to get all the regions in the subscription ?

### ISSUE THREAD

**Issue by madhugilla** [Azure/azure-sdk-for-python#1028]
Hi

is there a method to get all the regions in the subscription ?

Thanks

**Comment by lmazuel** [comment]
Hi @madhugilla 

Using the `azure-mgmt-resource` package, subscription sub-client you have [list_locations](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.resource.subscriptions.operations.html#azure.mgmt.resource.subscriptions.operations.SubscriptionsOperations.list_locations) method.

I don't have a sample, but the unittests is [here](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_resource_subscriptions.py) if it helps.

Thank you

**Comment by lmazuel** [comment]
I close this issue, I think I answered correctly to the initial question. Feel free to comment to re-open it if necessary, or open a new issue if you have any new problems.
Thank you,

**Comment by madhugilla** [comment]
Appreciate your help !!.
