### ISSUE TITLE
[event hubs] support receiver redirect

### ISSUE THREAD

**Issue by chradek** [Azure/azure-sdk-for-python#10296]
## Background
The Event Hubs service supports redirects for amqp receiver links. When the client creates an amqp receiver link with redirects enabled, the service will respond with an `amqp:link:redirect` error if it also supports redirects. The error contains the information needed to create a new connection to the service.

The main benefit of receiver redirect is it allows a more direct connection to the host actually sending events to the client which should reduce latency.

## API changes
The Event Hub clients responsible for consuming events (e.g. `EventHubConsumerClient`) should accept a new option to enable redirect that has a default value of `false`.
Proposal:
```javascript
  { enableRedirect: true } // new option 'enableRedirect'
```
### Reasoning
It is important to make this option opt-in for 2 reasons:
1. Currently 1 client creates 1 connection. This changes this assumption to 1 client can create many connections. This has implications since there is a limit to the number of connections that can be open at one time to an Event hub.
2. By default the SDK speaks AMQP over ports 5671/5672. With redirect enabled, new connections may be made on ports 104xx. Users may need to update their firewall rules to support redirect:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide#amqp-outbound-port-requirements

### Redirect walkthrough
1. User instantiates a consumer client with redirect enabled.
2. User makes call to receive events (this causes a receiver link to be created using customer-provided credential/host info).
3. Connection/cbs session/receiver link are created.
   - The receiver link __must__ have `amqp:link:redirect` included in the list of `desired_capabilities` if redirect is enabled.
This __must__ be omitted if redirect is not enabled.
3. The receiver link recieves a `LinkRedirectError`.
4. The SDK parses the hostname/port/address info from the error.
5. A new amqp connection is created using the hostname/port from the error.
6. When the cbs session is created, the `applicationProperties.name` value should be the `address` extracted from the `LinkRedirectError`.
7. The SDK creates the receiver link on the new connection and begins receiving events.

### Considerations
It is possible for every receiver link to have different hostname/port/address values from one another in the `LinkRedirectError`. You may create a new connection for every `LinkRedirectError`. Optionally, you may use a connection for multiple receiver links _if_ the links share a hostname/port.

Creating a new connection for each redirect is simpler to implement because it is easier to know when the connection should be closed, but does potentially increase connection density.

#### When to re-use the original connection?
It is possible that the server node used for receiving events can change. When the SDK sees an `amqp:connection:forced` error from the service, or the __connection__ is closed, then the original connection should be used to create a new receiver link. At this point a new `LinkRedirectError` should be received and the redirect walkthrough can be followed.

Otherwise, for transient issues the connection created for the link after a LinkRedirectError can be re-used.

## Reference
There is a draft PR for the JavaScript SDK that has the basics implemented for this feature.
https://github.com/Azure/azure-sdk-for-js/pull/7782

**Comment by yunhaoling** [comment]
goal for April: design
