### ISSUE TITLE
Support for Computer Vision Read API v3.0 (preview)

### ISSUE THREAD

**Issue by itssimon** [Azure/azure-sdk-for-python#10308]
It seems like the current SDK does not yet support the new Cognitive Services Computer Vision [Read API v3.0](https://westus2.dev.cognitive.microsoft.com/docs/services/5d98695995feb7853f67d6a6/operations/5d986960601faab4bf452005).

Are there plans to support the preview at all or are we only going to see this in the SDK once the final v3.0 is released?

**Comment by itssimon** [comment]
@dfulcer Are you able to comment?

**Comment by TFR258** [comment]
Hi @itssimon ,
We are currently working on adding support as we speak.
Thanks,
Tom

**Comment by itssimon** [comment]
Thanks for the update @TFR258. Are you able to give us an estimate when this will be released?

**Comment by TFR258** [comment]
@itssimon , It should be out already =)
https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/client-library?pivots=programming-language-csharp

**Comment by lmazuel** [comment]
This got released part of package 0.6.0, sorry for the late notice here
