### ISSUE TITLE
Add working example of Application Gateway creation

### ISSUE THREAD

**Issue by iordaniordanov** [Azure/azure-sdk-for-python#1030]
Add Application Gateway example like the one provided for Load Balancer

http://stackoverflow.com/questions/42698609/how-to-create-azure-application-gateway-using-python-sdk

**Comment by lmazuel** [comment]
Thank you @iordaniordanov for the feedback, I will try to do it soon.

**Comment by lmazuel** [comment]
Hi @iordaniordanov 

You can find now a sample here:
https://github.com/Azure-Samples/network-python-manage-application-gateway

Thank you for your patience!

**Comment by iordaniordanov** [comment]
Thanks for the update :)
