### ISSUE TITLE
ADLSv2 rename_directory to an existing path

### ISSUE THREAD

**Issue by reazura** [Azure/azure-sdk-for-python#10311]
- **Package Name**: azure.storage.filedatalake
- **Package Version**: 12.0.0
- **Operating System**: Databricks 6.4
- **Python Version**: python3.7 (?)

**Describe the bug**
Attempting to rename an adlsv2 directory to an existing directory via directory_client.rename_directory gives an error: _The recursive query parameter value must be true to delete a non-empty directory_ . 

I'm not entirely sure if it's a documentation issue or if it's possible at all; but is there a **kwarg param that should be passed to have the behavior wherein during a folder rename, existing files where conflicting, will be overwritten, instead of attempting to delete the existing folder?

**To Reproduce**
Create two folders and rename the first folder via directory_client.rename_directory to the second folder.

**Expected behavior**
Files, where conflicting, will be overwritten, instead of attempting to delete the existing folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/5679059/76720687-7717b400-6778-11ea-8814-85215e33c563.png)

![image](https://user-images.githubusercontent.com/5679059/76720738-9adafa00-6778-11ea-9ec2-458185af10c8.png)

**Comment by kaerm** [comment]
Thanks for reaching out @reazura! Looping in the right team to take a look at this @sumantmehtams

**Comment by v-xuto** [comment]
Hi @reazura , 
Add "mode" parameter. This parameter determines the behavior of the rename operation. The value should be "legacy" or "posix". In rename_directory method, the default value of mode is "legacy". But in this operation, we should use "posix". 
 ```
directory_client.rename_directory('library/dataSources/grossReturn/processed', mode='posix') 
 ```
Please feel free to reach us with more detailed information if the error still persists by using my suggestion.

**Comment by xiafu-msft** [comment]
Hi @reazura 

We are sorry that currently we don't support 'posix' mode which is mensioned in @v-xuto 's comment.
Renaming the directory to an non-empty directory is not working as expected.
If you really need to rename the directory to an non-empty directory, let me know!

**Comment by reazura** [comment]
I worked around the issue by having DataFactory load the same files into both the /processing and /processed folder then deleting the /processing folder afterwards; but it's not really an ideal scenario as this causes confusion when someone manually drops a file inside the /processing folder.

So yes, I would really love the capability to rename a directory to a non-empty directory

**Comment by xiafu-msft** [comment]
Hi @reazura ,

We are sorry that currently there isn't an API to support that!
We have created a backlog item and it will be added in the future.
Sorry about the inconvenience..
