### ISSUE TITLE
[azure-mgmt-kusto] Does this library supports the creation of databases?

### ISSUE THREAD

**Issue by eparizzi** [Azure/azure-sdk-for-python#10315]
I'm looking for a way to create ADX databases programmatically, preferably by using a Python SDK, but I cannot find anything. Is this operation supported? If not, the only supported way is through the Azure Portal? I need to be able to programmatically manage databases and their permissions.

**Comment by RodgeFu** [comment]
Assign to Crystal to have a look. thanks.

**Comment by chunyu3** [comment]
[Azure-mgmt-kusto] is the python SDK for ADX database (Azure Data Explorer database).
You can use this libary to create/get/update/delete database, and assign principal.

**Comment by chunyu3** [comment]
Add service team to comfirm

**Comment by radennis** [comment]
Yes, the library supports creating and managing a database. Please see example here: https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-python 

It's of course also supported through the portal, see here https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-portal

**Comment by chunyu3** [comment]
answered. close it.
