### ISSUE TITLE
Improve Azure Search continuation token 

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#10325]
Probably want to add service version in addition to current base64 encode

**Comment by bryevdv** [comment]
The relevant code is here:

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/search/azure-search-documents/azure/search/documents/_index/_paging.py

Currently the request is already base64, the ask is to also include the service version somehow (TBD with team)

**Comment by xiangyan99** [comment]
See #10571

**Comment by xiangyan99** [comment]
Fixed in #10571
