### ISSUE TITLE
Implement Azure Search Index Management Operations 

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#10324]

**Comment by bryevdv** [comment]
> Here are a couple of quick links to help with that first SearchServiceClient.GetStatistics method to get the client hierarchy in place:
Source: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search/src/SearchServiceClient.cs#L201
Single Test ported from Track 1: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search/tests/SearchServiceClientTests.cs#L133

**Comment by lmazuel** [comment]
See https://github.com/Azure/azure-sdk-for-python/pull/10571

**Comment by xiangyan99** [comment]
Fixed in #10571
