### ISSUE TITLE
Auto-Args to main in Azure function App are not generated at new bindings

### ISSUE THREAD

**Issue by srikkar** [Azure/azure-sdk-for-python#10330]
- **Package Name**:  Azure func core tools 
- **Package Version**: 2.7.2254
- **Operating System**: Windows
- **Python Version**:  3.6

**Describe the bug**
Have followed this URL: https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-07 to get the auto bindings generated. But, still after following the steps, I couldn’t get the auto generated arguments 

**To Reproduce**
1.  Follow the Steps as per URL above for Cosmos DB in binding with HTTPTrigger

**Expected behavior**
After Adding the new in binding to HTTPTrigger Azure function, expect SDK to auto-generate Args to access the data from Cosmos Graph/SQL inside function's main 

![Azure python binding Args](https://user-images.githubusercontent.com/29890085/76819443-0bfbd980-686d-11ea-8e4b-62f01fe1fa67.jpg)

**Additional context**
Any suggestions to get the data from grapgh DB using Gremlin API are most welcome

**Comment by lmazuel** [comment]
Issue moved to [Azure/azure-functions-python-library #60](https://github.com/Azure/azure-functions-python-library/issues/60) via [**ZenHub**](https://www.zenhub.com/)
