### ISSUE TITLE
Blob client is encoding '/' in blob name while generating URL

### ISSUE THREAD

**Issue by chencivalue** [Azure/azure-sdk-for-python#10336]
- **Package Name**: 
azure-storage-blob

- **Package Version**: 
12.3.0

- **Operating System**:
MACOS CATALINA 10.15.2

- **Python Version**: 
 3.7.3

**Describe the bug**
Blob client is encoding reserved character '/' in blob name while generating blob URL
Blob name = blob/test.csv
Generated URL = https://<storage_account>.blob.core.windows.net/<container_name>/blob%2Ftest.csv

**To Reproduce**

    blob_name = 'blob/test.csv'
    blob = BlobClient(
        blob_service.url,
        container_name=blob_container_name,
        blob_name=blob_name,
    )
    print(blob.url)

**Expected behavior**
Not to encode reserved character such as '/' in blob name component of a URL

Blob name = blob/test.csv
Generated URL = https://<storage_account>.blob.core.windows.net/<container_name>/blob/test.csv

**Comment by kaerm** [comment]
@chencivalue thanks for reporting this, tagging it for the right team to take a look into this @xgithubtriage

**Comment by xiafu-msft** [comment]
Hi @chencivalue 
I think that is as expected, we need to encode the url components when sending out request.
If you open portal.azure and see your uploaded file, I think the file name should be the correct one.

**Comment by chencivalue** [comment]
Hi @xiafu-msft 
I think that reserved characters such as '/' should not be encoded in the blob name component.
If I try to download the blob using the generated URL, the new downloaded blob changes its name. For example:

Blob name = blob/test.csv
Generated URL = https://<storage_account>.blob.core.windows.net/<container_name>/blob%2Ftest.csv
downloaded blob name is blob_test.csv instead of just test.csv:
![image](https://user-images.githubusercontent.com/33280195/77050212-14b9f000-69d2-11ea-8f5b-e22936e6df8b.png)

If I manually replace '%2F' with '/' in the URL, the downloaded blob is getting the correct name:
![image](https://user-images.githubusercontent.com/33280195/77053045-65cbe300-69d6-11ea-850a-f4e35dc5b502.png)


Please take a look at _blob_client.py line 163:
```
    def _format_url(self, hostname):
        container_name = self.container_name
        if isinstance(container_name, six.text_type):
            container_name = container_name.encode('UTF-8')
        return "{}://{}/{}/{}{}".format(
            self.scheme,
            hostname,
            quote(container_name),
            quote(self.blob_name, safe='~'),
            self._query_str)
```

We can see that the blob name is wrapped by the quote function with safe character '~'  which overrides the default '/'

I guess that '~' should be added to a default reserved characters list but it isn't the case

Part of the quote function documentation:
```
Each part of a URL, e.g. the path info, the query, etc., has a
    different set of reserved characters that must be quoted.

    RFC 3986 Uniform Resource Identifiers (URI): Generic Syntax lists
    the following reserved characters.

    reserved    = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" |
                  "$" | "," | "~"

    Each of these characters is reserved in some component of a URL,
    but not necessarily in all of them.

    Python 3.7 updates from using RFC 2396 to RFC 3986 to quote URL strings.
    Now, "~" is included in the set of reserved characters.

    By default, the quote function is intended for quoting the path
    section of a URL.  Thus, it will not encode '/'.  This character
    is reserved, but in typical usage the quote function is being
    called on a path where the existing slash characters are used as
    reserved characters.
```

**Comment by xiafu-msft** [comment]
Hi @chencivalue 

It looks like you are downloading the blob by pasting the generated url(the one generated in SDK) in azure portal. 
Absolutely we can make the generated url compatible with azure portal, while it will not be available until the next release.

If it blocks you, you can unquote the generated url first before paste it into azure portal. 
Sorry about the inconvenience!

**Comment by chencivalue** [comment]
Thanks for the reply,
Actually we have an automated system that generates a url using azure blob SDK and send it by email to the customer, so we can't really use the portal in this case.
We are currently using the previous version (azure-storage-blob==1.5.0) and it works fine by using the make_blob_url function.
I guess we will have to wait with this migration.

**Comment by xiafu-msft** [comment]
Hi @chencivalue 

Thanks for your patience and we are appreciated that you are using a workaround!
I have a PR to fix that, https://github.com/Azure/azure-sdk-for-python/pull/10467/files
It should be able to get merged tomorrow. While the next release is at least a month.

While there are ways to use the updated code immediately, it's pretty simple:
1. run `git clone https://github.com/Azure/azure-sdk-for-python.git` to checkout the repo
2. `cd .\azure-sdk-for-python\sdk\storage\azure-storage-blob` to go to azure-storage-blob package
3. run `python setup.py bdist_wheel -d <your destination folder>`, replace <your destination folder> with your destination folder
4. do `pip install <the full path of generated .whl file in step #3>` 

Let me know if you need any help!

**Comment by chencivalue** [comment]
Thank you for your assistance @xiafu-msft

**Comment by xiafu-msft** [comment]
Hi @chencivalue 
The fix has been merged to master branch, so I'll close this issue for now, feel free to reopen it if you have any question!
