### ISSUE TITLE
[ServiceBus] Double "With" statement when using top level ServiceBusClient

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#10343]
Current way may look a bit awkward, this could be improved:

```python
sb_client = ServiceBusClient.from_connection_string()
with sb_client:
    sb_receiver = sb_client.get_queue_receiver()
    with sb_receiver:
        # handling messages
```

**Comment by KieranBrantnerMagee** [comment]
Some thoughts as we do triage:

The one way I see for us to broach this and minimize the extra boilerplate is if ServiceBusClient sanely closes out the lifecycles of all sub-clients on its own closing (and, necessarily, opens() either implicitly with creation or on first action).  We can assess this as we mature the connection pooling work in T2.

**Comment by yunhaoling** [comment]
Some extra context: In recent user study sessions, most users don't complain about the double "with" statement as the pattern is introduced in readme/sample smoothly.

Let wait for more feedback on this.

**Comment by KieranBrantnerMagee** [comment]
Closing this issue as we have reached good conclusions in UX studies as well as our plan going forward with connection sharing and refcount-based-cleanup for making this robust against common use patterns.  (keeping in mind people don't always remember the outermost with)
