### ISSUE TITLE
Eventhub ConsumerClient for multiple consumer groups

### ISSUE THREAD

**Issue by kiranpvsr** [Azure/azure-sdk-for-python#10359]
**Is your feature request related to a problem? Please describe.**
Currently, I use the code sample from github for eventhub to read from a consumer group

```
client = EventHubConsumerClient.from_connection_string(connection_str, consumer_group,
                                                                    eventhub_name=eventhub_name
client.receive(
                on_event=self.on_event
            )

```

**Describe the solution you'd like**
Single script to run for multiple consumer groups. Maybe provide the list of consumer groups as a list when instantiating the client.

**Describe alternatives you've considered**
Run a script for each consumer group i.e., if there are two consumer groups, create two python scripts with the same code but change the consumer group name.

**Comment by kaerm** [comment]
Hi @kiranpvsr thanks for reaching out, looping in my team to take a look at this //cc: @yunhaoling @YijunXieMS

**Comment by kiranpvsr** [comment]
also, could someone please clarify if all consumer groups have access to all partitions ? i.e., is there any point in reading from more than one consumer group. this isn't clear in the docs

**Comment by YijunXieMS** [comment]
@kiranpvsr An `EventHubConsumerClient` can't be used to receive from multiple consumer group. A consumer group has access to all partitions of an event hub.

A scenario of using multiple consumer group is, for instance you have two separate applications receiving from the same event hub, you may want to have two consumer groups.
When method `update_checkpoint( )` is called, it saves checkpoint by event hub, consumer group, and partition id. So application A updating checkpoint doesn't impact application B's checkpoint.

**Comment by YijunXieMS** [comment]
@kiranpvsr you can create multiple `EventHubConsumerClient` instances if you do need to use multiple consumer groups to receive from an event hub in one script. 
But I'm curious what scenario you have to receive with multiple consumer groups from one event hub in one script.

**Comment by kiranpvsr** [comment]
@YijunXieMS sorry! yes i figured out that yesterday. thank you for patiently answering my questions

**Comment by kiranpvsr** [comment]
> @kiranpvsr An `EventHubConsumerClient` can't be used to receive from multiple consumer group. A consumer group has access to all partitions of an event hub.
> 
> A scenario of using multiple consumer group is, for instance you have two separate applications receiving from the same event hub, you may want to have two consumer groups.
> When method `update_checkpoint( )` is called, it saves checkpoint by event hub, consumer group, and partition id. So application A updating checkpoint doesn't impact application B's checkpoint.

sorry! yes i figured out that yesterday. thank you for patiently answering my questions
