### ISSUE TITLE
Azure EventHub - Using Azure identity(Client id/secret) how to use Checkpoint store

### ISSUE THREAD

**Issue by amitgadhavi7** [Azure/azure-sdk-for-python#10389]
Hi,

I am using EventHub 5.0.0 sdk and i am using Azure identity(Client Id/Client Secret) for connection instead of Connection string. 

All your samples mainly use connection string and so can you please show me how to use checkpoint store while using Client ID/Client Secret to establish the connection.

Waiting for your reply,

Best regards,
Amit.

**Comment by kaerm** [comment]
Hi @amitgadhavi7 thanks for reporting this! Adding a couple of folks on my team to see if there is any documentation here that we should add //cc: @yunhaoling @YijunXieMS

**Comment by YijunXieMS** [comment]
@amitgadhavi7 You can use `BlobCheckpointStore` constructor to pass in a credential object.
```python
    def __init__(self, blob_account_url, container_name, *, credential=None, **kwargs):
```
where the `blob_account_url` is like "https://*mystorageaccount*.blob.core.windows.net".

Thanks for the feedback. I'll improve the sample.

**Comment by amitgadhavi7** [comment]
Hi Yijun,

This is how my code looks below. Can you please tell me how to pass the Checkpoint store to the client.

checkpoint_store = BlobCheckpointStore.from_connection_string(blobstore_conn, "data_checkpoint_store")
    credential = ClientSecretCredential("TenantId", "ClientID", "ClientSecret")
    client = EventHubConsumerClient(Address, eventhub, consumergroup, credential)
    #client = EventHubConsumerClient.from_connection_string(conn_str=connstr, consumer_group=consumergroup,eventhub_name=eventhub)
    async with client:
        await client.receive(
            on_event=on_event,
            on_error=on_error,
            on_partition_close=on_partition_close,
            on_partition_initialize=on_partition_initialize,
            starting_position="-1",  # "-1" is from the beginning of the partition.
        )

**Comment by YijunXieMS** [comment]
Just add checkpoint_store to the constructor call of EventHubConsumerClient.

```python
checkpoint_store = BlobCheckpointStore.from_connection_string(blobstore_conn, "data_checkpoint_store")
credential = ClientSecretCredential("TenantId", "ClientID", "ClientSecret")
client = EventHubConsumerClient(Address, eventhub, consumergroup, credential, checkpoint_store=checkpoint_store)
#client = EventHubConsumerClient.from_connection_string(conn_str=connstr, consumer_group=consumergroup,eventhub_name=eventhub)
async with client:
    await client.receive(
        on_event=on_event,
        on_error=on_error,
        on_partition_close=on_partition_close,
        on_partition_initialize=on_partition_initialize,
        starting_position="-1", # "-1" is from the beginning of the partition.
    )
```

**Comment by amitgadhavi7** [comment]
Hi Yijun,

We are getting an error,

An exception occurred during list_ownership for namespace 'mqds-non-prod.servicebus.windows.net' eventhub 'market-quote-quote-change-dev-v1' consumer group 'uddf_consumer_group'. Exception is HttpResponseError('The specifed resource name contains invalid characters.\nRequestId:322b0711-201e-0030-1765-01ba81000000\nTime:2020-03-23T22:47:54.4482291Z\nErrorCode:InvalidResourceName\nError:None')
EventProcessor instance '524 454 5t456 665f' of eventhub 'market-quote-quote-change-dev-v1' consumer group 'uddf_consumer_group'. An error occurred while load-balancing and claiming ownership. The exception is HttpResponseError('The specifed resource name contains invalid characters.\nRequestId:322b0711-201e-0030-1765-01ba81000000\nTime:2020-03-23T22:47:54.4482291Z\nErrorCode:InvalidResourceName\nError:None'). Retrying after 10.368337411801916 seconds

**Comment by YijunXieMS** [comment]
@amitgadhavi7 "data_checkpoint_store" should be an invalid name because container name shouldn't have underscore. Is it "data-checkpoint-store" or something else?

**Comment by amitgadhavi7** [comment]
Hi Yijun,

I am getting an error using Checkpoint store. Below is the error,

An exception occurred during list_ownership for namespace 'mqds-non-prod.servicebus.windows.net' eventhub 'market-quote-quote-change-dev-v1' consumer group 'uddf_consumer_group'. Exception is HttpResponseError('The requested URI does not represent any resource on the server.\nRequestId:c5ca6172-d01e-0043-68c8-02ca42000000\nTime:2020-03-25T17:15:09.6491308Z\nErrorCode:InvalidUri\nError:None')
EventProcessor instance '72567358-d80c-47a4-9d6d-f264764bb14c' of eventhub 'market-quote-quote-change-dev-v1' consumer group 'uddf_consumer_group'. An error occurred while load-balancing and claiming ownership. The exception is HttpResponseError('The requested URI does not represent any resource on the server.\nRequestId:c5ca6172-d01e-0043-68c8-02ca42000000\nTime:2020-03-25T17:15:09.6491308Z\nErrorCode:InvalidUri\nError:None'). Retrying after 10.263682965624128 seconds

Can you please help me in this regards ?

Amit.

**Comment by amitgadhavi7** [comment]
Hi Yijun,

I am getting an error using Checkpoint store. Below is the error,

An exception occurred during list_ownership for namespace 'mqds-non-prod.servicebus.windows.net' eventhub 'market-quote-quote-change-dev-v1' consumer group 'uddf_consumer_group'. Exception is HttpResponseError('The requested URI does not represent any resource on the server.\nRequestId:c5ca6172-d01e-0043-68c8-02ca42000000\nTime:2020-03-25T17:15:09.6491308Z\nErrorCode:InvalidUri\nError:None')
EventProcessor instance '72567358-d80c-47a4-9d6d-f264764bb14c' of eventhub 'market-quote-quote-change-dev-v1' consumer group 'uddf_consumer_group'. An error occurred while load-balancing and claiming ownership. The exception is HttpResponseError('The requested URI does not represent any resource on the server.\nRequestId:c5ca6172-d01e-0043-68c8-02ca42000000\nTime:2020-03-25T17:15:09.6491308Z\nErrorCode:InvalidUri\nError:None'). Retrying after 10.263682965624128 seconds

Can you please help me in this regards ?

Amit.

**Comment by YijunXieMS** [comment]
Hi @amitgadhavi7 , looks like the params you pass to BlobCheckpointStore have wrong information of the Azure Storage Blob Container. Could you check if they're correct?

**Comment by amitgadhavi7** [comment]
Hi Yijun,

I checked the BlobCheckpointStore and the name of storage container is correct. Below is the sample code but am i properly writing it in the code. 

checkpoint_store = BlobCheckpointStore.from_connection_string(blobstore_conn, "uddf-ggot-bc01/plats_checkpoint_store", api_version=STORAGE_SERVICE_API_VERSION 

I also tried out below code, but i am still getting same error.

checkpoint_store = BlobCheckpointStore.from_connection_string(conn_str=blobstore_conn, container_name="uddf-ggot-bc01/plats_checkpoint_store", api_version=STORAGE_SERVICE_API_VERSION) 

Can you please let know what's the mistake here?

**Comment by YijunXieMS** [comment]
Could you check in the azure portal whether the container name is "uddf-ggot-bc01/plats_checkpoint_store"? It doesn't look like a correct container name.

**Comment by amitgadhavi7** [comment]
Hi Yijun,

The container name is "udsfgcopt" and the blob_container_name within this container is uddf-ggot-bc01 and the foldername in the blob_container is plats_checkpoint_store. Hence we are doing ""uddf-ggot-bc01/plats_checkpoint_store". 

According to you what should the container name be then ?

**Comment by YijunXieMS** [comment]
I think "udsfgcopt" will do. The 5.x doesn't need blob name or folder name. Instead, the SDK will create folders and blobs in that container and use the metadata of blobs to store the load balancing and checkpoint information.

**Comment by amitgadhavi7** [comment]
Hi Yijun,

We were able to establish the connection using Checkpoint. It has successfully created folders and files but all those files are of 0 B and empty. Can you please tell me when they will get updated? Do we need to add any extra lines of code to update them or they will be automatically updated?

Also, we are getting another error after long execution of code, 
LinkDetach("ErrorCodes.ConnectionCloseForced: The connection was inactive for more than the allowed 240000 milliseconds and is closed by container '808dd1b5df96462ba2b2b5b102ae885e_G19'.") 

Can you please let me know what is going wrong here ?

Regards,
Amit.

**Comment by YijunXieMS** [comment]
Hi Amit, 

The data is actually stored on the metadata of those blobs. In Azure Portal you can see the metadata of every blob.
For the second question, the server closes the connection if there is no traffic between the client (both the SDK and your code are considered client) and the event hub service after 240000 seconds. The long operation blocks the receiving. However as I said before, connection will be re-established automatically and the receiving will resume. You don't need to worry about it.

If your long execution is CPU-bound, there is no much room to optimize. But if it's dealing with I/O most of the time, you may consider using (Thread, or ThreadPoolExecutor) to break the long operations down to smaller concurrent jobs, or using the async API of the SDK.
Could I know what long operations do you have, http request, file i/o, or anything else?

**Comment by YijunXieMS** [comment]
@amitgadhavi7 I'm closing this issue since it's been a while. Pls create a new issue should you have more questions.
