### ISSUE TITLE
changing loglevel for azure is not working

### ISSUE THREAD

**Issue by tezzigator** [Azure/azure-sdk-for-python#10404]
azure-identity==1.3.0
azure-keyvault-keys==4.1.0
azure-keyvault-secrets==4.1.0
Win10
Py 3.8.2

**Describe the bug**
Instructions for changing loglevel for the azure sdk is near the bottom of https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-secrets
The default log level that the azure sdk uses is INFO.  I am logging my microservice container at INFO via `logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s : %(message)s')` and would like to change the SDK to do everything at DEBUG

**To Reproduce**
Use any key vault operation, list keys, get secret, sign/encrypt.  

**Expected behavior**
Using the suggestion of your docs:
```
# Create a logger for the 'azure' SDK
logger = logging.getLogger('azure')
logger.setLevel(logging.DEBUG)
```
I expect the sdk log output to be at DEBUG, but all output is still at INFO.  (also tried using `logging_enable=True` on all my calls also, that had no effect either)

**Comment by tezzigator** [comment]
nevermind

**Comment by usrme** [comment]
> nevermind

I'm having the same issue. What did you do to get it solved?

**Comment by tezzigator** [comment]
> 
> 
> > nevermind
> 
> I'm having the same issue. What did you do to get it solved?

it was a workaround, it was something like this:
```
from logging import basicConfig, addLevelName, getLogger
basicConfig(level=INFO, format='%(asctime)s %(levelname)s : %(message)s') # this needs to be ahead of the azurelogger spam control, or we get duplicate logs
azurelogger = getLogger('azure')
azurelogger.setLevel(WARNING) # Since the azure sdk spams *everything* it does at INFO
app.logger.info('My hostname is ' + gethostname())
```

**Comment by mboret** [comment]
On my side, I must have done this:

```
import logging  
logging.basicConfig(
        format='%(asctime)s,%(msecs)d %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s',
        datefmt='%Y-%m-%d:%H:%M:%S', stream=sys.stdout,
        level="INFO")
for name in logging.Logger.manager.loggerDict.keys():
    if ('azure' in name):
        logging.getLogger(name).setLevel(logging.WARNING)
```

**Comment by asimarora** [comment]
I still see a workaround not a fix (in Azure SDK).  @tezzigator , Don't you think it deserved to be open :)

**Comment by poleshe** [comment]
Setting the logger on WARNING fixed it for me:

`logger = logging.getLogger("azure.core.pipeline.policies.http_logging_policy")
logger.setLevel(logging.WARNING)`

**Comment by poleshe** [comment]
Setting the logger to WARNING fixed it for me:

`logger = logging.getLogger("azure.core.pipeline.policies.http_logging_policy")  
logger.setLevel(logging.WARNING)`
