### ISSUE TITLE
Missing system properties when consuming messages from IotHub

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#10408]
This is regarding the issue logged by a customer for the JS Event Hubs package regarding missing system properties. The same applies to the Python package for Event Hubs as well

Please see https://github.com/Azure/azure-sdk-for-js/issues/7801

Looks like we need to extract certain properties from the AMQP message and add it to system properties.

cc @YijunXieMS, @KieranBrantnerMagee, @yunhaoling,  @annatisch

**Comment by YijunXieMS** [comment]
Verified that Python already retrieves all system properties.
