### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ANPTA** [Azure/azure-sdk-for-python#10412]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lilyjma** [comment]
Hi @ANPTA, you could reference issues like this [one](https://github.com/Azure/azure-sdk-for-python/issues/10277) to file bugs. To keep up with repo hygiene, I'm going to close the issue. Thanks.
