### ISSUE TITLE
abc

### ISSUE THREAD

**Issue by suryapotla** [Azure/azure-sdk-for-python#10411]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lilyjma** [comment]
Hi @suryapotla, please provide more descriptive information about your bug, like this [issue](https://github.com/Azure/azure-sdk-for-python/issues/10277). To keep up with repo hygiene, I'm going to close the issue. Please feel free to create a new issue once you're experiencing any problem with our SDKs. Thanks.
