### ISSUE TITLE
Nightly Test Run Integration for Samples

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-python#10425]
# Summary

In order to ensure that our samples are up-to-date and in good working order, they should be routinely validated by smoke testing them as part of the nightly test runs.

# Scope of Work

- Devise an approach to allow published samples to be smoke tested and run as part of the live test suite.

- Validate the design with your language team, architect, and, if needed, the engineering team.

- Perform any implementation or enhancements necessary to integrate the samples with the nightly test runs.

# Success Criteria

- The approach for nightly test run integration of samples has been validated with stakeholders and is consistent with the team's direction.

- The published samples for the Event Hubs packages are smoke tested as part of the nightly test runs.

- The published samples for the Event Hubs packages can be run as part of the live test suite by contributors.

- Failures for the samples during the nightly test runs cause the run for that platform to fail; verification of the nightly results surfaces problems with the samples in the same manner that it does issues in the client library features.

**Comment by yunhaoling** [comment]
ping engsys team for follow up on automatic smoke sample test

**Comment by yunhaoling** [comment]
closing the issue as the detailed work item is created here:
https://github.com/Azure/azure-sdk-for-python/issues/16045
