### ISSUE TITLE
Enable PR testing on Windows 

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#10452]
Currently PR pipelines are running on Linux image only. This has caused a platform level issue to slipped into master branch and failed on CI. We need to run atleast one PR run on Windows image. As per the preference from language team, we should run PR on Windows using Python 3.5

**Comment by kurtzeborn** [comment]
I agree we should do some validation on widnows, however, I'm not sure we should run all of our tests on Windows for PR validation.  Would the issue you're describing that slipped through have been caught by running just a few "general" tests on Windows?  I want to be careful about doubling the load of each PR on our DevOps pool of machines.

**Comment by praveenkuttappan** [comment]
I think original description of issue is not completely clear. Currently are running tests on python 2.7, Python 3.5, python 3.7 and python 3.8 and all of them are running on Linux image. Language team's request is to run current python 3.5 test on Windows instead of Linux image so we will not add more load for PR test.
