### ISSUE TITLE
Authenticate via Visual Studio Code

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#10472]
Add a credential to authenticate with the identity signed in to Visual Studio Code's Azure extension. This credential should be internal because it may be exposed to users only as part of an aggregate credential. The Azure extension uses [keytar](https://www.npmjs.com/package/keytar) to store a refresh token, so the credential will need to make native calls to get that token. I expect `msal-extensions` has an interface for some of these calls (e.g. for [macOS Keychain](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/dev/msal_extensions/osx.py)). Sharing authentication with the Azure extension means redeeming the refresh token it stored; `AadClient` has [code for that](https://github.com/Azure/azure-sdk-for-python/blob/eddd0a57e1e308caf25601a71ab11ec424abb21a/sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py#L69).

Azure/azure-sdk-for-net#10979 has a complete cross-platform implementation in C#.

**Comment by xiangyan99** [comment]
See in #10840
