### ISSUE TITLE
Code examples should use MSI for credential management

### ISSUE THREAD

**Issue by jasonzio** [Azure/azure-sdk-for-python#10489]
It would be great if example code used MSI for authentication/authorization instead of assuming "Oh, you have credentials that you've somehow magically and securely embedded in your code". For services which directly support MSI, use that; for services which do not, at least link to a page that shows how to securely store and retrieve credentials from Azure KeyVault.

**Comment by kaerm** [comment]
Hey @jasonzio thanks for reporting this. Just so that I can better understand how you're using it: could you give me an example of a sample where you couldn't find the authentication instructions?

**Comment by ross-p-smith** [comment]
I have to agree with Jason, I've been trawling all the docs for a worked example of connecting to Storage with a User Managed Identity and it is really not obvious how you do it, all of the documents fall back to Access keys

**Comment by jasonzio** [comment]
I'm sorry I missed this question.

- Start with [the Azure Blob storage Quickstart](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python). All it talks about is the Connection String, obtained based on storage key. Not even the slightest hit to other sources of authentication.
- The [Azure Storage Blobs client library](https://docs.microsoft.com/en-us/azure/developer/python/sdk/storage/storage-blob-readme?view=storage-py-v12) doc references two other pages for authentication info:
  - [Configuring your local Python environment](https://docs.microsoft.com/en-us/azure/developer/python/configure-local-development-environment?tabs=bash) which talks about `az login` and about creating a Service Principal via `az ad sp create-for-rbac` , which presupposes you're using AAD.
  - [Authorizing access to data in Azure Storage](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth?toc=/azure/storage/blobs/toc.json) which has a beautiful table with columns labeled "Shared Key (storage account key)", "Shared access signature (SAS)", "Azure Active Directory (Azure AD)", "On-premises Active Directory Domain Services (preview)", and "Anonymous public read access", none of which being MSI.
- If you happen to know, or guess, searching for "azure storage sdk msi" will bring you to [Authorize access to blob and queue data with managed identities for Azure resources](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi), which immediately talks about Azure AD and spends all of its content talking, again, about setting up a Service Principal.
- That "Authorize... with managed identities" page _does_ contain a link to [What are managed identities for Azure resources?](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview), which was just created on 2020-05-20 (that might be a modifed-on date, I'm not sure). This page talks about system and user managed identities, which is on the right track. The page then links to pages which talk about using MSI to access RM itself, but not any managed services.

I cannot find a page, anywhere, that shows a Python example which, either directly or via straight-forward links, shows:
- how to use portal to setup a user-managed identity
- how to create a VM so that a system managed identity is defined for it
- how to use the Python SDK to access storage using a user-managed identity
- how to use the Python SDK to access storage using the VM's system managed identity

I'm not 100% certain that the Azure Storage service has created a doc page which describes configuring access rights for MSI for individual blobs, for a specific container, for a specific storage account, or for all storage assets associated with a subscription. The specific rights for storage are distinct from the umbrella CRUD rights; using the MSI panel in the portal to grant READ access to a VM's system identity won't allow code running in that VM to read anything in storage; you have to grant "Storage Read", or something like that.

**Comment by kaerm** [comment]
@jasonzio thank you so much for the thorough write up - this is great! 

@maggiepint and @kraigb this should be helpful for the updates for the general authentication docs

**Comment by kraigb** [comment]
@jasonzio @kaerm Can you clarify for me what "MSI" means. I see the term thrown around somewhat but haven't really been clear on what it really entails.

**Comment by kaerm** [comment]
I always understood it as [Managed Identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview)

**Comment by jasonzio** [comment]
@kraigb - @kaerm is correct, MSI in various Azure sources means Managed Identity. (See, for example, [What are managed identities for Azure resources](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview).

**Comment by askpatrickw** [comment]
Hi @kaerm I came here to open this same issue.

The sample in [azure-keyvault-certificates README ](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-keyvault-certificates/README.md) needs updating.

Specifically be also demonstrate how to use managed identities (previously known as MSI).
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview
"Managed identities for Azure resources is the new name for the service formerly known as Managed Service Identity (MSI)."

Seems like a sweep across all the docs is needed if managed identities is the recommended way.
