### ISSUE TITLE
Azure Blob Listing Blobs with a Limit Doesn't Work in v12.3

### ISSUE THREAD

**Issue by mkrdip** [Azure/azure-sdk-for-python#10481]
In v12.3.0
This doesn't work anymore
`container_client.list_blobs(name_starts_with="Data_", results_per_page=2)` instead of limiting it to 2, it return all the blobs. From code it looks like it's implemented, [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L673).

In v2.1.0
`block_blob_service.list_blobs(container_name, num_results=2)` used to work just fine.

**Comment by kaerm** [comment]
Hi @mkrdip thanks for letting us know, tagging the right team to take a look at this: @xgithubtriage

**Comment by xiafu-msft** [comment]
Hi @mkrdip 
Thanks for reaching out!
You should call 
```
pages = container_client.list_blobs(name_starts_with="Data_", results_per_page=2).by_page()
next_page = next(pages)
for blob in next_page:
    print blob.name
```

**Comment by mkrdip** [comment]
Thank you! We can close this one but maybe update the doc? I couldn't find it the Python documentation yet, though it's present in [SDK for JavaScript](https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/containerclient?view=azure-node-latest).
