### ISSUE TITLE
Bug Persist output file to Azure Storage with the Batch service API in Python

### ISSUE THREAD

**Issue by lsongcoles** [Azure/azure-sdk-for-python#10517]
- **Package Name**: azure
- **Operating System**: Ubuntu16
- **Python Version**: 3.7.6

**Describe the bug**
I am trying to push the output files generated from Azure batch to Storage account container, by using the OutputFile module from azure.batch.models

The issue is with the file_pattern. The following is part of my code:
 ```
for of in output_files:
            file_options = OutputFileUploadOptions(
                upload_condition=OutputFileUploadCondition.task_completion)

            destination_path = f"{job_id}/{task_id}/{of}"
            container = OutputFileBlobContainerDestination(
                container_url=self.file_output_container,
                path=destination_path)
            output_file_destination = OutputFileDestination(
                container=container)

            az_output_files.append(
                OutputFile(**file_pattern**=of,
                           destination=output_file_destination,
                           upload_options=file_options))
            return az_output_files
```

When I pass a parameter with value of "../std*.txt", it will throw an error

Also, I tried "..\std*.txt" and still failed with invalid input error.

So, I added a command "echo hello >> stdtest.txt" in the job, and change the file_pattern to be "std*.txt", then it works. 

As the working directory is "wd", and the stdout and stderr are at one level up directory, I need the "../" stuff, which has some issues

Would appreciate if you have a check on this and have it fixed, thanks

**Comment by kaerm** [comment]
Hi @lsongcoles thanks for reporting this @lsongcoles, adding the right team to take a look at this: @xgithubtriage

**Comment by xiafu-msft** [comment]
Hi @kaerm  
Would you like to route this issue to azure batch? 
Thanks for your help!

**Comment by bgklein** [comment]
@lsongcoles Could you clarify the error you are seeing? The following task works perfectly fine for me:
```
{
  "id": "echo2",
  "commandLine": "/bin/bash -c \"echo hello\"",
  "resourceFiles": [],
  "environmentSettings": [],
  "userIdentity": {
    "autoUser": {
      "scope": "pool",
      "elevationLevel": "nonadmin"
    }
  },
  "constraints": {
    "maxWallClockTime": "P10675199DT2H48M5.4775807S",
    "retentionTime": "P7D",
    "maxTaskRetryCount": 0
  },
  "outputFiles": [{"destination": {"container": {"containerUrl": "xxxxxx"}}, "filePattern": "../stdout.txt", "uploadOptions": {"uploadCondition": "taskcompletion"}}]
}
```

**Comment by bgklein** [comment]
If you are getting a file upload error also try taking a look and/or attaching the fileupload logs from the VM 
![image](https://user-images.githubusercontent.com/18502617/78157627-07026280-73f5-11ea-8a66-c568d9aaedcb.png)

**Comment by bgklein** [comment]
Closing the issue due to inactivity
