### ISSUE TITLE
need to support azure firewall multiple public address deployment

### ISSUE THREAD

**Issue by chriseizus** [Azure/azure-sdk-for-python#10549]
Azure released this new feature to add more than 1 public ip addresses to azure firewall.
It's beneficial to the incoming and outgoing traffic management.

https://docs.microsoft.com/en-us/azure/firewall/deploy-multi-public-ip-powershell

Here is the powershell cli which can achieve this.
$rgName = "resourceGroupName"

$vnet = Get-AzVirtualNetwork `
  -Name "vnet" `
  -ResourceGroupName $rgName

$pip1 = New-AzPublicIpAddress `
  -Name "AzFwPublicIp1" `
  -ResourceGroupName "rg" `
  -Sku "Standard" `
  -Location "centralus" `
  -AllocationMethod Static

$pip2 = New-AzPublicIpAddress `
  -Name "AzFwPublicIp2" `
  -ResourceGroupName "rg" `
  -Sku "Standard" `
  -Location "centralus" `
  -AllocationMethod Static

New-AzFirewall `
  -Name "azFw" `
  -ResourceGroupName $rgName `
  -Location centralus `
  -VirtualNetwork $vnet `
  -PublicIpAddress @($pip1, $pip2)

**Comment by kaerm** [comment]
@chriseizus thanks for reaching out - I am tagging the right team to take a look at this @nickzhums

**Comment by RodgeFu** [comment]
Add "Service Attention" label for service team to double confirm swagger is ready for the new feature and submit a request to release a new SDK version including it. thanks.
