### ISSUE TITLE
get_steps() or get_children() dont provide all the child/steps post submitting a pipeline run

### ISSUE THREAD

**Issue by gargiulman** [Azure/azure-sdk-for-python#10543]
- **Package Name**: azureml-sdk
- **Package Version**: 1.0.85
- **Operating System**:
- **Python Version**: 

**Describe the bug**
When a pipeline run is submitted and you have an immediate next line to iterate through all its steps or get children, it fails to enter into the for loop. It is seen if wait period is imposed , then it enters into for loop. This shows there is some delay in get_steps() or get_children() returning expected results. As there are no child steps returned, step.wait for completion () is not executed. 

**To Reproduce**
1.  master_pipeline_run = (Experiment(ws, project_name)
                            .submit(pipeline,
                                    regenerate_outputs=True,
                                    continue_on_step_failure=False)
                            )
for step in master_pipeline_run.get_steps():
   do something

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sanpil** [comment]
This is how the current implementation works:

If the steps don’t have any dependencies, they usually start within a few minutes (and show up in the get_steps()). If any steps depend on others, then the final steps won’t show up until all the previous steps are completed.

We are currently working on improving this.

**Comment by sanpil** [comment]
As mentioned earlier, this is how the current implementation works:

If the steps don’t have any dependencies, they usually start within a few minutes (and show up in the get_steps()). If any steps depend on others, then the final steps won’t show up until all the previous steps are completed.

We are currently working on improving this.
