### ISSUE TITLE
Express Routes Circuit Querying / Updating Assistance

### ISSUE THREAD

**Issue by v1011** [Azure/azure-sdk-for-python#1055]
Hello - 
I am trying to develop a Python script to query our MS Express Routes Circuit and also to update the circuit, IE add new public address ranges to be advertised over the Public/Office 365 BGP peer to MS, etc. etc. 

Here is the code I have so far, but I need some assistance in what class to use to query the circuit to get responses like when using Power Shell:

```python
from azure.common.credentials import UserPassCredentials
import os
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.network import NetworkManagementClient

credentials = UserPassCredentials(
    'MY_ID',    # Your new user
    'MY_PASS',  # Your password
)
subscription_id = os.environ.get(
        'AZURE_SUBSCRIPTION_ID',
        'SUB-ID')

ResourceGroupName =  "AzureExpressRoute"
Circuit_name1 = "MSExpressRouteCircuit1"
Circuit_name2 = "MSExpressRouteCircuit2"

network_client = NetworkManagementClient( credentials, subscription_id )
CircuitPeering = NetworkManagementClient ( credentials, subscription_id )

Test4 = CircuitPeering.express_route_circuits.list_all ( ResourceGroupName, Circuit_name1)

circuits = network_client.express_route_circuits.list( ResourceGroupName, Circuit_name2 )

print circuits


Test3 = network_client.express_route_circuits.get_peering_stats( ResourceGroupName, Circuit_name2 , Public)
```

I feel I have the script some-what working, as after a few seconds I get the following back:

<azure.mgmt.network.models.express_route_circuit_paged.ExpressRouteCircuitPaged object at 0x106216890>
{'secondarybytes_out': None, 'primarybytes_in': None, 'secondarybytes_in': None, 'primarybytes_out': None}

{'sku': <azure.mgmt.network.models.express_route_circuit_sku.ExpressRouteCircuitSku object at 0x106216990>, 'service_provider_notes': None, 'authorizations': [], 'name': u'ExpressRouteCircuit1', 'etag': u'W/"REMOVED_THIS"', 'tags': None, 'provisioning_state': u'Succeeded', 'service_provider_provisioning_state': u'Provisioned', 'allow_classic_operations': False, 'location': u'eastus', 'service_provider_properties': <azure.mgmt.network.models.express_route_circuit_service_provider_properties.ExpressRouteCircuitServiceProviderProperties object at 0x10623b190>, 'circuit_provisioning_state': u'Enabled', 'service_key': u'REMOVED_KEY', 'gateway_manager_etag': None, 'type': u'Microsoft.Network/expressRouteCircuits', 'id': u'/subscriptions/REMOVED_SUBSCRIPTION/resourceGroups/AzureExpressRoute/providers/Microsoft.Network/expressRouteCircuits/ExpressRouteCircuit1', 'peerings': [<azure.mgmt.network.models.express_route_circuit_peering.ExpressRouteCircuitPeering object at 0x10623b910>, <azure.mgmt.network.models.express_route_circuit_peering.ExpressRouteCircuitPeering object at 0x10623b950>, <azure.mgmt.network.models.express_route_circuit_peering.ExpressRouteCircuitPeering object at 0x10623b990>]}

Any help would be appreciated.

**Comment by lmazuel** [comment]
Hi @v1011 

I'm not sure I get your issue, let me try to clarify and tell me if you have more questions:
- `list` operation returns an iterator (`ExpressRouteCircuitPaged `). So you can use it as an iterator into a `for` loop or call `list` on it. I guess this is your first print on `circuits`
- I don't get your second object printing, since your code just have one print only.

Thanks,

**Comment by v1011** [comment]
Thanks for responding.

My other question is what objects do I need to use to be able to MODIFY or change any of the Express Routes Circuit info, related to the peering structure. ?

**Comment by lmazuel** [comment]
I'm not an expert in Express Route Circuit specially, but usually the modify pattern is "get and update". Like:
```python
 peering = self.network_client.express_route_circuit_peerings.get(
       self.group_name,
       express_route_name,
       'AzurePublicPeering'
)
# Change your peering object

# Update it
async_peering = self.network_client.express_route_circuit_peerings.create_or_update(
            self.group_name,
            express_route_name,
            'AzurePublicPeering',
            peering
)
new_peering = async_peering.result()
```

This unittest might be able to help you:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_network.py#L603-L715

Don't forget the tech doc for the operation and object description:
http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.network.html

**Comment by v1011** [comment]
Thanks. I will read this over, and see if I can modify it. We build a test circuit. will do some testing and see if this works.

**Comment by lmazuel** [comment]
Closing this issue since I have no reason to think it's not solved. Feel free to open a new one for any question. Thanks!
