### ISSUE TITLE
Python 3.7.7 on Windows 10 x64 failing to install azure via pipenv

### ISSUE THREAD

**Issue by predatorian3** [Azure/azure-sdk-for-python#10569]
# Problem

I am on a Windows 10 x64 VDI using Python 3.7.7 x64. I am attempting to install `azure`  using `pipenv`. The command its following output are located in this Gist.

* https://gist.github.com/predatorian3/68a747364f6a07514ccc67ad348eaeda

The command used.

```bash
C:\Users\dudleyp\Documents\Development\Azure
λ  py -3.7 -m pipenv install --pre
```

The `Pipfile`.

```ini
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
azure-cli = "*"
azure-devops = "*"
azure = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true
```

It seems to be complaining about something to do with `azure-batch` not matching a version constraint.

## Computer Information

```
C:\Users\dudleyp\Documents\Development\Azure
λ  systeminfo.exe

Host Name:                 V1DUDLEYP
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
```

**Comment by lmazuel** [comment]
Hi @predatorian3 
The current recommendation is to not use `azure` meta-package, but to install individual packages as needed (like `azure-mgmt-compute`). May I ask you why you are trying to install `azure` (what documentation you read, what samples, etc.) so we can update that page.

Thank you!

**Comment by predatorian3** [comment]
lack of knowledge on my part and not knowing which client library I would need right now to do what I'm experimenting with.

**Comment by lmazuel** [comment]
`azure` packages has been officially deprecated, the list of available packages can be found here:
https://aka.ms/azsdk/python/all
