### ISSUE TITLE
Release notes in dependabot PRs

### ISSUE THREAD

**Issue by estensen** [Azure/azure-sdk-for-python#10595]
**Is your feature request related to a problem? Please describe.**
We use dependabot to upgrade our packages. When it creates a PR it also fetches the release notes if they are available in a certain way. Because of that we don't have to go some other place on GitHub to see what changes. This would make the developer experience more smooth.

Example of how it could be compared to how it's done today:

<img width="688" alt="Screenshot 2020-04-01 at 09 13 40" src="https://user-images.githubusercontent.com/9142800/78109243-24393000-73f9-11ea-9a69-5c162b297950.png">
<img width="684" alt="Screenshot 2020-04-01 at 09 13 11" src="https://user-images.githubusercontent.com/9142800/78109249-256a5d00-73f9-11ea-9539-5c6864002530.png">

**Comment by estensen** [comment]
`azure-mgmt-cosmosdb` does not have link to release notes at all:

<img width="679" alt="Screenshot 2020-04-01 at 10 35 44" src="https://user-images.githubusercontent.com/9142800/78116440-94997e80-7404-11ea-923e-14fc9ef44e6b.png">


Sometimes you don't get all release notes from the version you're updating from to the one you're updating to. This also might be to just skipping major versions:

<img width="685" alt="Screenshot 2020-04-01 at 10 34 13" src="https://user-images.githubusercontent.com/9142800/78116363-76338300-7404-11ea-97bf-d2b91f47d29f.png">

**Comment by kaerm** [comment]
@estensen thanks for reaching out, @maggiepint can you take a look at this

**Comment by kurtzeborn** [comment]
@estensen this is a great suggestion!  Thank you.

@scbedd or @praveenkuttappan (not sure who will have bandwidth first to work on this, trying Scott) once we get this worked out for Python, we should open issues to try dependabot on our other core langauge repos.  We're going to want to do this everywhere.

CC: @weshaggard

**Comment by weshaggard** [comment]
@estensen out of curiosity do you know if there is any documentation for how dependabot goes about finding this information? I couldn't find any docs and short of reading threw the source code I'm not sure what format it expects to find.

**Comment by estensen** [comment]
Didn't find any docs either. I think creating releases with bullet points with the updates is sufficient. So as long as it appears [here](https://github.com/Azure/azure-sdk-for-python/releases) Dependabot seems to be able to parse it

**Comment by estensen** [comment]
Also, Dependabot seems to parse `CHANGELOG.md`, but not `release-notes-azure-cli.md`. Not sure if there's a workaround having multiple packages in a monorepo

**Comment by scbedd** [comment]
Hey @estensen I've been looking at this for a bit today. Are you still seeing these dependabot PRs come in without changelogs? Right we make certain to include bullet points

[Recent EventHubs](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-servicebus_7.0.0b2)
[Recent Core](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-mgmt-core_1.1.0)

In the examples you linked it seems to me like it's copying the `body` of the release, which in our case is actually just markdown directly from the changelog.

**Comment by estensen** [comment]
@scbedd `azure-mgmt-core_1.1.0` looks good!

`azure-cli-core` is still not working when I got an update 5 days ago. Not sure how to make it work with headers between the bullet points there

**Comment by estensen** [comment]
Sometimes you don't get all the release notes, which is confusing.
For [azure-cosmos_4.0.0](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-cosmos_4.0.0) I expected there to be a breaking change since this is a major version update, but there are none in the release notes.

I don't know what's the best practice on this, but maybe include the changelog from the beta versions too? The release notes from [4.0.0b6](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-cosmos_4.0.0b6) are not included, and I guess it's the same for rc versions as well.

It is time consuming to go to the list of releases and find all the beta and release versions, since there is no tag for the package, so you can't list only that package.

<img width="662" alt="Screenshot 2020-05-25 at 10 37 57" src="https://user-images.githubusercontent.com/9142800/82795189-f100a380-9e73-11ea-82e3-28b028a3cf3d.png">

**Comment by lmazuel** [comment]
Hi @estensen , we made a lot of progress on changelog and organization since 2020. Everything is changelog.md now for instance. Could you give it a retry and tell us if the current experience is acceptable?
Thanks,

**Comment by estensen** [comment]
hi @lmazuel, I haven't worked with this SDK for a while, and probably won't for the foreseeable future. Feel free to close this if you consider it solved.
