### ISSUE TITLE
cannot import name 'TabularTranslator'

### ISSUE THREAD

**Issue by yashbhutoria** [Azure/azure-sdk-for-python#10597]
- **Package Name**: azure-mgmt-datafactory
- **Package Version**: 0.10.0
- **Operating System**: Windows
- **Python Version**: 3.6.8

**Describe the bug**
TabularTranslator model is missing

**To Reproduce**
Steps to reproduce the behaviour:
1. ``` from azure.mgmt.datafactory.models import TabularTranslator ```

**Expected behaviour**
The model should get imported. The "translator" parameter in CopyActivity model accepts an object. There used to be a TabularTranslator model in version 0.7.0 of azure-mgmt-datafactory. 
https://docs.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.models.copyactivity?view=azure-python

**Screenshots**
![image](https://user-images.githubusercontent.com/25660000/78152871-09e26f00-7458-11ea-8fc3-d3f4572d0d6c.png)

**Additional context**
I'm trying to map fields between source and sink in a CopyActivity

**Comment by kaerm** [comment]
@yashbhutoria thanks for reporting this, tagging the right team to take a look at this @nickzhums

**Comment by nickzhums** [comment]
@RodgeFu please have someone take a look, thanks :)

**Comment by RodgeFu** [comment]
@changlong-liu to have a look, thanks.

**Comment by changlong-liu** [comment]
Hi service team, I see TabularTranslator is defined in a separated swagger file entityTypes.json, which is not included in the readme.md for datafactory.

**Comment by lmy269** [comment]
@shawnxzq, can you take a look?

**Comment by shawnxzq** [comment]
@changlong-liu The TabularTranslator is indeed defined in the entityTypes/Pipeline.json, could you please double confirm whether we have some infra issue that blocks customer to use this? Thanks!

**Comment by schmocker** [comment]
i have the same issue. please fix, thanks

**Comment by changlong-liu** [comment]
Hi @shawnxzq , though TabularTranslator is defined in entityTypes/Pipeline.json, but the file it self is not included in the readme file.
Please add the file into the tags to enable the definitions. For instance https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/readme.md#tag-package-2018-06

**Comment by shawnxzq** [comment]
We will fix it by adding piepeline.json as input file, thanks!

**Comment by shawnxzq** [comment]
@changlong-liu we already fixed the issue, please close this one, thanks!

**Comment by changlong-liu** [comment]
Hi @shawnxzq , if fixed in swagger, would you submit release request for Python?

**Comment by shawnxzq** [comment]
SDK released now, @changlong-liu, please confirm and help close the issue.

**Comment by changlong-liu** [comment]
Thanks @shawnxzq !

release this issue since fix released: https://pypi.org/project/azure-mgmt-datafactory/0.14.0/
