### ISSUE TITLE
Allow LROPoller typing to accept the return type as a type argument

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#10605]
This way, in typing I can have # type: (...) -> LROPoller[return type] instead of just -> LROPoller.

Currently, when adding the return type as a type argument, I get this error: "LROPoller" expects no type arguments, but 1 given

**Comment by lmazuel** [comment]
Should look like this:
https://github.com/Azure/azure-sdk-for-python/blob/98e00dd29ff2db688d166fa3e36559677eef481b/sdk/core/azure-core/azure/core/pipeline/policies/_base.py#L48-L53

**Comment by rakshith91** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-python/pull/10653
