### ISSUE TITLE
multiapi_init_gen.py generate unmatched code on azure-mgmt-resource

### ISSUE THREAD

**Issue by changlong-liu** [Azure/azure-sdk-for-python#10621]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Swagger version: https://github.com/Azure/azure-rest-api-specs/pull/8268

Below is the _resource_management_client.py in azure.mgmt.resource.resources
![image](https://user-images.githubusercontent.com/59815250/78224811-c2adba00-74fb-11ea-8066-6e2734d53f50.png)

It is calling ResourceManagementClientConfiguration with parameter subscription_id.
But in the _configuration.py, ResourceManagementClientConfiguration actually require both subscription_id and subscription_id1
![image](https://user-images.githubusercontent.com/59815250/78224853-d48f5d00-74fb-11ea-9d20-a77bb389480f.png)

**To Reproduce**
use packaging_tools.generate_sdk

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kaerm** [comment]
Thanks @changlong-liu, @nickzhums can you take a look at this

**Comment by RodgeFu** [comment]
@lmazuel to check the issue in generated code. thanks.

**Comment by lmazuel** [comment]
`subscription_id1` is likely the root cause of the issue in the first place. Moving this issue to autorest repo

**Comment by changlong-liu** [comment]
Hi @chenjianfei2017 , would you help to confirm this is fixed in swagger? Thanks.

**Comment by chenjianfei2017** [comment]
hi @changlong-liu  @lmazuel  @kaerm 
it was resolved in this pr: https://github.com/Azure/azure-rest-api-specs/pull/9580/files

**Comment by changlong-liu** [comment]
Thanks @chenjianfei2017 !
