### ISSUE TITLE
recording test failed at CI

### ISSUE THREAD

**Issue by changlong-liu** [Azure/azure-sdk-for-python#10622]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
For this release: https://github.com/Azure/azure-sdk-for-python/pull/10619
The non-live tests run successfully in local. But failed at CI.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=341856&view=logs&j=54f1a854-9a75-5986-56ae-4f3fe1e836b7&t=d0c519ea-d6ce-556e-02e9-01d4ed29b200
![image](https://user-images.githubusercontent.com/59815250/78227179-795f6980-74ff-11ea-835f-4ace2c7172f5.png)

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kaerm** [comment]
@changlong-liu thanks again, sending the issue to @nickzhums

**Comment by RodgeFu** [comment]
assign to Changlong who is working with Scott on this

**Comment by changlong-liu** [comment]
close since it's a local environment issue.
