### ISSUE TITLE
https://pypi.org/project/azure Needs to be updated

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#10639]
Go here: https://pypi.org/project/azure - as an end-user who doesn't know about the new SDKs, I would think that this is the right one to install.

1. We need to determine if we are going to support this type of rollup package going forward
  - If not, then we need to indicate that on this page
  - If yes, then publish a new version.
2. We should denote which services have new versions:

![image](https://user-images.githubusercontent.com/2163001/78301571-24672780-74ee-11ea-902f-976c8aae89c6.png)

**Comment by lmazuel** [comment]
Package has been deprecated, list of available packages to install can be found here:
https://aka.ms/azsdk/python/all
