### ISSUE TITLE
https://pypi.org/project/azure-storage-common/ Needs updated messaging to point to new package

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#10642]
https://pypi.org/project/azure-storage-common/ should prominently display the new packages.

**Comment by jongio** [comment]
This package is owned by xclientdev only.  I have an email out to them to work with us to get updated.

**Comment by rakshith91** [comment]
@jongio There are a few concerns with this issue:

1) `azure-storage-common` is still necessary for the the track 1 libraries which we still support - so we cannot deprecate it unlike the azure-storage meta package.
2)  `azure-storage-common` is not something that can be used independently and is always used in coherence with the track1 blobs, queues or files. So landing on the pypi page for azure-storage-common is highly unlikely. As a side note, in both bing and google searches, i couldnt find this package in the first page of results when i search for "azure storage"
3) Releasing this package just for the sake of updating description on PYpi might not be a good idea as there are customers who are actively using the current version of it.

I believe this task should be closed now and should be re opened later when we deprecate the track1 libraries. Any concerns?

**Comment by jongio** [comment]
@lmazuel - Can you please review and comment?  I would like the page to point to the new SDKs.  I found this page, other users will as well.

**Comment by lmazuel** [comment]
> I found this page, other users will as well.

Fair enough, let me discuss with Ze then

**Comment by xiafu-msft** [comment]
I created a backlog item https://msazure.visualstudio.com/One/_workitems/edit/7406932 to keep track of this

**Comment by tasherif-msft** [comment]
I'm bringing this up again with our team today
