### ISSUE TITLE
https://pypi.org/project/azure-storage-file needs to point to new package

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#10643]
I believe this: https://pypi.org/project/azure-storage-file is replaced by this https://pypi.org/project/azure-storage-file-share/12.1.1/

Maybe not entirely, so need to go through the whole readme and determine that.

**Comment by lmazuel** [comment]
You're right, we should do a 2.1.0post1 with updated page. The new package is a renaming, you can see it if you look at the release history, we initially did the track2 preview there:
https://pypi.org/project/azure-storage-file/12.0.0b4/

**Comment by tasherif-msft** [comment]
Hi @mayurid and @jongio is there any action item on this? that link is indeed now replaced by https://pypi.org/project/azure-storage-file-share/

**Comment by xiangyan99** [comment]
@tasherif-msft you can release azure-storage-file 2.1.1 with the readme. "This package is deprecated. Please use the new one xxxx"
