### ISSUE TITLE
Allow user to control chunk_size in upload_data() (ADLS Gen2)

### ISSUE THREAD

**Issue by adriennn** [Azure/azure-sdk-for-python#10650]
**Is your feature request related to a problem? Please describe.**
The  [upload_data()](https://github.com/Azure/azure-sdk-for-python/blob/fa9f1a3edce6d74608e78486204a82b1f8ff57ff/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py#L289) method of the file client is hard coding the `chunk_size` parameter, making it impossible to control upload speed. This means this bulk upload method, is slower than using append / flush.  

**Describe the solution you'd like**
I want to be able to pass a kwarg `chunk_size int` from `upload_data()` so that it is passed all the way to the [upload helper function](https://github.com/Azure/azure-sdk-for-python/blob/fa9f1a3edce6d74608e78486204a82b1f8ff57ff/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_upload_helper.py#L28)

**Describe alternatives you've considered**
Using append and flush method of file client, we can control `chunk_size` parameter, but we've had uploads randomly failing.

**Additional context**

**Comment by xiafu-msft** [comment]
@adriennn 
Thanks for reaching out! We keep track of this and fix in the future!
Sorry about the inconvenience.

**Comment by xiafu-msft** [comment]
You should be able to config the chunk_size now by specifying upload_data(data, chunk_size=*)

**Comment by xiafu-msft** [comment]
Close this issue for now since it's fixed. Feel free to reopen it if you have any concern!
