### ISSUE TITLE
How to attach subnet to the route table

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1067]
Hi,

I am planning to attach subnet to the route table. Please let me know which operations class and method I can use.

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hello @VikramAIS ,

You will need `azure-mgmt-network` package. An overview on how to create a Network client can be found on this tutorial:
https://github.com/Azure-Samples/network-python-manage-loadbalancer

Once you have a Network client, the complete documentation is on readthedocs:
http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.network.html

Regards,

**Comment by VikramAIS** [comment]
Hello @lmazuel,

I am able to create route table using Network client. But I need to attach subnet to the route table. In the route table class constructor subnets initialized to None. 

 def __init__(self, id=None, location=None, tags=None, routes=None, provisioning_state=None, etag=None):
        super(RouteTable, self).__init__(id=id, location=location, tags=tags)
        self.routes = routes
        self.subnets = None
        self.provisioning_state = provisioning_state
        self.etag = etag

Please help me on attaching subnets to route table.

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS ,

You need to attach the route to the subnet, not the contrary (it's why subnet is `None`, you're not supposed to change it yourself).
You can see that `Subnet` has a `route_table` property:
http://azure-sdk-for-python.readthedocs.io/en/v2.0.0rc6/ref/azure.mgmt.network.models.html#azure.mgmt.network.models.Subnet
Then, just call `subnets.create_or_update` with the right set of parameters.

Thanks,

**Comment by VikramAIS** [comment]
I can able to attach subnet to the route table.

Thanks,
Vikram

**Comment by rafael6** [comment]
Can you tell us how you did it. I'm trying to attach a route_table to a subnet, but I'm not sure how to use the route_table parameter.

**Comment by CharlPels** [comment]
can someone post a sample of how to attach a route table to a subnet
