### ISSUE TITLE
generatevpnclientpackage doesn't work

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#1069]
https://github.com/Azure/azure-cli/issues/2569
https://github.com/Azure/azure-rest-api-specs/issues/1093

The call is supposed to return a URL to a VPN client download package (but not, presumably the bits of the package itself).  This command is implemented in Powershell, so there's some question as to whether there is an issue with the Swagger spec or possibly something in the Python autorest conversion of the Swagger spec.

**Comment by aanandr** [comment]
Laurent - who is supposed to look into the Python autorest conversion for this functionality?

**Comment by lmazuel** [comment]
The last time I talked with @tjprescott about this, we conclude it was a RestAPI issue.

**Comment by tjprescott** [comment]
@lmazuel but you do have this open for another reason yes?  It had to do with receiving the text "null" from the service?

**Comment by lmazuel** [comment]
If I remember correctly, the Swagger is saying "str" as a return type. 

```json
        "responses": {
          "202": {
            "description": "VPN client package URL.",
            "schema": {
              "type": "string"
            }
          }
        }
```

So when I receive "null", I parse it like a string and not an empty JSON (so the string "null" in four characters). So I don't think there is a reason to keep this issue open actually.

**Comment by tjprescott** [comment]
Feel free to close then :)
