### ISSUE TITLE
TokenProviders

### ISSUE THREAD

**Issue by skinkie** [Azure/azure-sdk-for-python#107]
In the current Python code I cannot find any interface to specify a TokenProvider similar to the C# SDK. When can this be expected?

http://msdn.microsoft.com/en-us/library/microsoft.servicebus.tokenprovider.aspx

We would like to have this code working using the Python API.
```C#
MessagingFactory listenMF = MessagingFactory.Create(endpoints, new StaticSASTokenProvider(subscriptionToken));
SubscriptionClient sc = listenMF.CreateSubscriptionClient(topicPath, subscriptionName);
```

**Comment by lmazuel** [comment]
There is an interface you can use to provide the signature to the request, which is close to the behavior asked here. The class must provide an implementation of the `sign_request` method:

```python
class ServiceBusCustomAuthentication:
    def sign_request(self, request, httpclient):
        # Example when adding an header, but you can do anything you want with the request
        request.headers.append(
            ('Authorization', 'my sensitive authentication string')
        )
```

Then, create the `ServiceBusService` using an instance of this class:
```python
client = ServiceBusService(authentication=ServiceBusCustomAuthentication())
```

[ACS implementation](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/azure/servicebus/servicebusservice.py#L1142)
[SAS implementation](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/azure/servicebus/servicebusservice.py#L1205)

Please tell me if you think this does not answer the question.
Thank you,

**Comment by lmazuel** [comment]
Close this one due to inactivity. Please feel free to open a new issue or re-comment here if you think my latest comment does not response to the bug.
Thanks!
