### ISSUE TITLE
extract cpu utilization of each cpu present in a vm.

### ISSUE THREAD

**Issue by navya-goli** [Azure/azure-sdk-for-python#1071]
Hi ,

I want to extract the CPU utilization information of each CPU present in an azure VM using a python script.

We have an agent called telegraf which extracts the CPU utilization of each CPU like: 

CPU:       usage_idle 
CPU 0      99.5991983967939
CPU1        99.3993993993999

In a similar way, I want to extract CPU utilization of each CPU of a VM using python.

Please provide me assistance.

Thanks

**Comment by lmazuel** [comment]
Hi @navya-goli 

Please read this tutorial and confirm if it's fixing your issue or not:
http://azure-sdk-for-python.readthedocs.io/en/latest/sample_azure-monitor.html#metrics

Thank you,

**Comment by navya-goli** [comment]
Thank you for sending the tutorial link.

The link gives the CPU utilization of entire VM but my requirement is to find the CPU utilization of core CPUs of VM.

Hence can you help me further to find the CPU utilization of core CPUs of VM.

Thank You

**Comment by lmazuel** [comment]
I got an answer from the team:
> With LAD 3.0 it will be possible to obtain per-core utilization information.  

The VM metrics team asked me to tell you the best place to have a maximum help for this question is:
https://github.com/Azure/azure-linux-extensions
