### ISSUE TITLE
Track 2: Design and implement Rule Manager

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#10714]
Initial architectural discussion for this item has been started but not locked.
- Initial design involved a RuleManager as a top-level handler (ala get_sender) on the ServiceBusClient.
- A proposal should be approved past SB arch group prior to implementation.

**Comment by yunhaoling** [comment]
closing duplicate issue.
please uset the issue: https://github.com/Azure/azure-sdk-for-python/issues/11444 to track the progress.
