### ISSUE TITLE
IoTHubDeviceClient connect()/disconnect(): Exception when used in function. (Synch method)

### ISSUE THREAD

**Issue by HoLue** [Azure/azure-sdk-for-python#10727]
- **Package Name**:  azure.iot.device
- **Package Version**:  ?
- **Operating System**: Windows 10
- **Python Version**:  3.7.4

**Describe the bug**
Unsing the synch method, a simple connect() and disconnect() of a device client (IoTHubDeviceClient) gives an error if it is done in a function. (Without the function ist works.) The exception message after about 10 seconds is:
Exception caught in background thread.  Unable to handle.
["AttributeError: 'NoneType' object has no attribute '_on_connected'\n"]

**To Reproduce**
Just run the following script with a valid connection string, the error occurs after about 10 seconds:

```
import os
from azure.iot.device import IoTHubDeviceClient
import time

def f():
    conn_str = 'YourConnectionString'
    device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)
    # connect the client.
    device_client.connect()
    # usually do something but this dies not matter
    # Finally, disconnect
    device_client.disconnect()

# using the function
f()

# wait - after about 10 seconds the error occurs
for i in range(20):
    print(i)
    time.sleep(1)
 
```

**Expected behavior**
No exception (and therefore no exception message)

**Comment by lmazuel** [comment]
Issue moved to [Azure/azure-iot-sdk-python #534](https://github.com/Azure/azure-iot-sdk-python/issues/534) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lmazuel** [comment]
Hi @HoLue 
I'm moving your issue to the repo of the right team, thanks!
