### ISSUE TITLE
public_ip_address method within NetworkManagementClient will not return values

### ISSUE THREAD

**Issue by khantext** [Azure/azure-sdk-for-python#10735]
- **Package Name**: azure-mgmt-network
- **Package Version**: 2.7.0
- **Operating System**: Windows 10 Enterprise Version 1809 build 17763.1098
- **Python Version**: 3.7

**Describe the bug**
When a public IP address actually does exist, the public_ip_address method nevertheless always returns a <class 'azure.mgmt.network.v2018_12_01.models.public_ip_address_py3.PublicIPAddress'> object with all empty (None) values. For example...

{'additional_properties': {}, 'id': '/subscriptions/xxxxxxxxx/resourceGroups/lbi-azure-web-proxy-rg/providers/Microsoft.Network/publicIPAddresses/lbiazpwproxy001664', 'name': None, 'type': None, 'location': None, 'tags': None, 'sku': None, 'public_ip_allocation_method': None, 'public_ip_address_version': None, 'ip_configuration': None, 'dns_settings': None, 'ddos_settings': None, 'ip_tags': None, 'ip_address': None, 'public_ip_prefix': None, 'idle_timeout_in_minutes': None, 'resource_guid': None, 'provisioning_state': None, 'etag': None, 'zones': None}

**To Reproduce**
1. Import the NetworkManagementClient << from azure.mgmt.network import NetworkManagementClient >>
2. Establish 'credentials' and 'subscription_id' variables.
3. Create a network client << network_client = NetworkManagementClient(credentials, subscription_id) >>
4. Query a network interface known to have a Public IP address << response = network_client.network_interfaces.get("lbi-azure-web-proxy-rg", "lbiazpwproxy001664").ip_configurations[0].public_ip_address >>
5. Print the response << print(response) >>
6. You should see the results with all 'None' values populated.

**Expected behavior**
I expect for the actual values to be returned. As a test, I ran what should be the same query using the Python 'requests' module against this URL: "https://management.azure.com/subscriptions/xxxxxxxxxx/resourceGroups/lbi-azure-web-proxy-rg/providers/Microsoft.Network/publicIPAddresses/lbiazpwproxy001664?api-version=2019-07-01", and it returned valid results (see below). I used the same credentials against the same subscription.

Result using Python 'requests' against URL:

{
  "name": "lbiazpwproxy001-ip",
  "id": "/subscriptions/xxxxxxxxxx/resourceGroups/lbi-azure-web-proxy-rg/providers/Microsoft.Network/publicIPAddresses/lbiazpwproxy001-ip",
  "etag": "W/\"f151da9d-940f-4b7c-8caa-73a94342234d\"",
  "location": "eastus2",
  "tags": {
    "Cost Cent": "xxxx",
    "Cost Center": "xxxxx"
  },
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "4a41ceba-989e-488b-9d57-xxxxxxxxxxxx",
    "ipAddress": "40.79.xxx.xxx",
    "publicIPAddressVersion": "IPv4",
    "publicIPAllocationMethod": "Dynamic",
    "idleTimeoutInMinutes": 4,
    "ipTags": [],
    "ipConfiguration": {
      "id": "/subscriptions/xxxxxxxxxx/resourceGroups/lbi-azure-web-proxy-rg/providers/Microsoft.Network/networkInterfaces/lbiazpwproxy001664/ipConfigurations/ipconfig1"
    }
  },
  "type": "Microsoft.Network/publicIPAddresses",
  "sku": {
    "name": "Basic"
  }
}

**Comment by kaerm** [comment]
Thanks @khantext for reporting this, adding the right team to take a look at this @nickzhums

**Comment by nickzhums** [comment]
@RodgeFu please let someone take a look, thanks!

**Comment by LianwMS** [comment]
I am investigating the issues

**Comment by LianwMS** [comment]
@khantext  in your repo step, you are trying to get the network interface, then try to get it related public ip. If you are trying to get the public ip directly. it will return the correct property. as following:
'''network_client.public_ip_addresses.get(GROUP_NAME, PUBLIC_IP_NAME)'"

**Comment by LianwMS** [comment]
I check the api call again. @khantext said is correct. when query network interface. api ill return ip_configurations, which is a object array, but in the ip_configurations the public ip address will only contains id while the other properties are none. 
Add service team to confirm the behavior is correct

**Comment by imeya** [comment]
any updates for this issue?

**Comment by jsntcy** [comment]
@Irenehua, do you know who can help take a look at this issue about public IP?
