### ISSUE TITLE
1st letter of boolean values are uppercased in dicts. 

### ISSUE THREAD

**Issue by Rodrigossz** [Azure/azure-sdk-for-python#10759]
- **azure.cosmos**: 
- **What is provided by Cosmos Notebooks**: 
- **Cosmos Notebooks - April 2020**:
- **3x**: 

**Describe the bug**
The function container_client.create_item accepts a dict as body input parameter. But dicts will uppercase the first letter of any boolean string. Meaning that **true** will became **True**. 

But Cosmos DB doesn’t recognize **True** as a boolean and the create  item operation will return error since it is just a string without quotes. 

My workaround was to convert **true** to **‘true’** but for Cosmos DB it is just a string now.

The function doesn’t accept json strings. 

**To Reproduce**
1. Just test to create an item for:

{
  "firstname": "Tom",
  "lastname": "Cruise",
  "isActor": true
} 

**Expected behavior**
Maybe it should accept json strings.

**Screenshots**

**Additional context**

**Comment by annatisch** [comment]
Thanks @Rodrigossz - sorry for the delay.
I would like to clarify the issue a bit more. If I create the following item:
```python
# create document definition that contains a boolean
document_definition = {
    'id': 'doc',
    'name': 'sample document',
    'isTest': True
}
# create document using Upsert API
created_collection.upsert_item(body=document_definition)
```
When I read this document back from the service it is deserialized correctly as a boolean:
```
# read documents after creation and verify updated count
documents = list(created_collection.read_all_items())
print(documents)

# output
[{'id': 'doc', 'name': 'sample document', 'isTest': True, '_rid': 'F7dcAPsnnvYBAAAAAAAADA==', '_self': 'dbs/F7dcAA==/colls/F7dcAPsnnvY=/docs/F7dcAPsnnvYBAAAAAAAADA==/', '_etag': '"00000153-0000-0800-0000-5eb9e4430000"', '_attachments': 'attachments/', '_ts': 1589240899}]
```
The Python SDK will automatically JSON serialize the dict that is passed in, so the item representation passed to the service will be in the form:
```
{"id":"doc","name":"sample document","isTest":true,"_rid":"uV0AAMFs1OcBAAAAAAAADA==","_self":"dbs\/uV0AAA==\/colls\/uV0AAMFs1Oc=\/docs\/uV0AAMFs1OcBAAAAAAAADA==\/","_etag":"\"00000a00-0000-0800-0000-5eb9e5d10000\"","_attachments":"attachments\/","_ts":1589241297}
```
I'm not sure why you wish to pass in a lower case `true` value (which isn't valid Python unless it's a string). Could you please clarify your scenario for me?

**Comment by Rodrigossz** [comment]
Hello!

I could not reproduce the problem, create_item rejecting the boolean value. But, when I was testing here, I found a similar issue. 

Data Explorer isn't keeping True with capital T if you open an item. Please check the attached images.

![ok](https://user-images.githubusercontent.com/11827523/85632130-93ef3d80-b62b-11ea-84d4-9dac0b5e5e64.PNG)

![nok](https://user-images.githubusercontent.com/11827523/85632145-9f426900-b62b-11ea-901b-59b89a605430.PNG)

**Comment by Rodrigossz** [comment]
Will open a new issue with the new problem. The original one was fixed.

**Comment by annatisch** [comment]
Thanks @Rodrigossz - I think the reason for this is that a lowercase `true` is the correct JSON serialization.
In the Python SDK we accept the Python value `True` and serialize the JSON body - which will convert to lowercase `true` to send over the wire.
On receiving an item in the SDK, it is deserialized back from JSON to the Pythonic value.
