### ISSUE TITLE
[azure-core] Add x-ms-request-id and x-ms-date in http logging policy

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-sdk-for-python#10774]
**Is your feature request related to a problem? Please describe.**

I just found that there are some headers redacted by http logging policy and there is a whitelist defined in azure.core as shown[ here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L342). 

With the default whitelist, other headers will be **readcated**, which will cause the following output when mapping to CLI: 
 ```
azure.core.pipeline.policies.http_logging_policy : Response status: 500
azure.core.pipeline.policies.http_logging_policy : Response headers:
azure.core.pipeline.policies.http_logging_policy :     'Transfer-Encoding': 'chunked'
azure.core.pipeline.policies.http_logging_policy :     'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
azure.core.pipeline.policies.http_logging_policy :     'x-ms-request-id': 'REDACTED'
azure.core.pipeline.policies.http_logging_policy :     'x-ms-client-request-id': '10c9d2d2-7a0f-11ea-a43c-186024942c80'
azure.core.pipeline.policies.http_logging_policy :     'x-ms-version': 'REDACTED'
azure.core.pipeline.policies.http_logging_policy :     'x-ms-error-code': 'REDACTED'
azure.core.pipeline.policies.http_logging_policy :     'Date': 'Thu, 09 Apr 2020 03:06:30 GMT'
azure.core.pipeline.policies.http_logging_policy :     'Connection': 'close'
azure.core.pipeline.policies.http_logging_policy : Request URL: 'https://zuhadls.blob.core.windows.net/test/upload%2Ftestxx'
azure.core.pipeline.policies.http_logging_policy : Request method: 'HEAD'
azure.core.pipeline.policies.http_logging_policy : Request headers:
azure.core.pipeline.policies.http_logging_policy :     'x-ms-version': 'REDACTED'
azure.core.pipeline.policies.http_logging_policy :     'x-ms-date': 'REDACTED'
azure.core.pipeline.policies.http_logging_policy :     'x-ms-client-request-id': '10c9d2d2-7a0f-11ea-a43c-186024942c80'
azure.core.pipeline.policies.http_logging_policy :     'User-Agent': 'azsdk-python-storage-dfs/12.0.0 Python/3.7.4 (Windows-10-10.0.18362-SP0)'
azure.core.pipeline.policies.http_logging_policy :     'Authorization': 'REDACTED'
```

**Describe the solution you'd like**

Can we add x-ms-request-id, x-ms-date, x-ms-version in whitelist? Because it is very useful for users to debug and these information will be output when error occurs as shown here, in this way it should be fine to add these information in whitelist.
```
Server encountered an internal error. Please try again after some time.
RequestId:ea5f198c-101e-000a-714a-0e5296000000
Time:2020-04-09T08:38:54.1385366Z
ErrorCode:InternalError
Error:None
```

**Describe alternatives you've considered**

**Additional context**

**Comment by lmazuel** [comment]
@johanste is there guideline about whitelist of headers? Are you ok if we add a kwarg or something top configure it (we can't today, we would have to pass the policy explicitly)

**Comment by johanste** [comment]
Each client library should be able to configure an approved list of headers (this should already be possible, right?). I think it is also reasonable to have a default list of approved headers that the service specific headers is added to. I don't know if the caller of the client library/service method needs to be able to add more headers to log. Do we have a compelling scenario for that?

**Comment by lmazuel** [comment]
@johanste so does it mean we need a whitelist in azure-mgmt-core that will apply to all mgmt auto-generated package?

**Comment by lmazuel** [comment]
For x-ms-request-id see https://github.com/Azure/azure-sdk-for-python/pull/10967

**Comment by Juliehzl** [comment]
could you also add `x-ms-lease-time`? 

`azure.core.pipeline.policies.http_logging_policy :     'x-ms-lease-time': 'REDACTED'`

**Comment by lmazuel** [comment]
Closing this issue, since the remaining headers are storage specific and there is issue #10960 for that
