### ISSUE TITLE
Readme content of Azure Identity missing an example summary

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#10785]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity#examples
)
![image](https://user-images.githubusercontent.com/57166602/78983801-7c89d380-7b57-11ea-909a-3f637d2690b9.png)

Reason:
Most services have a summary of examples, such as key vault, storage, and so on.
It is recommended that Azure Identity be added for consistency.

suggestion:
![image](https://user-images.githubusercontent.com/57166602/78984011-eace9600-7b57-11ea-8f4f-2f6c1103a1db.png)

**Comment by jongio** [comment]
@tzhanl - Looks like Charles is tracking in #10734, so do not need PR.
