### ISSUE TITLE
Unable to get the Disk Utilization Details of Azure Linux and Windows VMs

### ISSUE THREAD

**Issue by navya-goli** [Azure/azure-sdk-for-python#1079]
Hi,

I enabled the diagnostics settings of azure windows and linux VMs.

I am able to get disk free space for only windows VM but not linux from storage account.

I need to extract disk used, disk available and disk total metrics of both linux and windows VMs.

Please provide me the assistance to extract the above-mentioned metrics.

Thanks.

**Comment by lmazuel** [comment]
Hi @navya-goli 

The VM metrics team asked me to tell you the best place to have a maximum help for this question is:
https://github.com/Azure/azure-linux-extensions

They also answered:

> Current LAD (v2.3) doesn’t support the disk free space metrics. Actually, LAD v2.3 supports only the fixed metrics as defined in here. The new LAD (v3.0) that we are planning to release for preview should allow customers to choose among available metrics, which include free disk space.

**Comment by navya-goli** [comment]
Hi

When can we expect the release of LAD (v3.0).

Thanks

**Comment by lmazuel** [comment]
Hi @navya-goli 

I'm not responsible for LAD project. Please ask your question on https://github.com/Azure/azure-linux-extensions

Thank you,
