### ISSUE TITLE
Support SAS URL at folder level also in azure storage gen 2

### ISSUE THREAD

**Issue by focode** [Azure/azure-sdk-for-python#10809]
Hi,
I was trying to create SAS URL for a folder in azure storage and trying to give it read access but as per current implementation SAS URL can only be created for blob level, file level, but not at folder level. Is there any plan in the future so that it can be supported at folder level also.

**Comment by kaerm** [comment]
thanks @focode for feedback, tagging the right team to take a look at this @xgithubtriage

**Comment by xiafu-msft** [comment]
Hi @focode 
Thanks for reaching out, we will discuss this and get back to you!

**Comment by focode** [comment]
Is there any update on this.

**Comment by xiafu-msft** [comment]
Hi @focode 
We are adding a list of service features, folder level SAS will be one of the features. 
However we are sorry that we not able to provide a specific date about when this folder level SAS feature. Probably in the next few months. Thanks for your patience!

**Comment by xiafu-msft** [comment]
Hi @focode 

This feature is in preview now. https://pypi.org/project/azure-storage-file-datalake/12.2.0b1/
Please also install azure-storage-blob==12.6.0b1 to use this preview package
