### ISSUE TITLE
AZURE_AUTHORITY_HOST does not allow URI scheme to be specified

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#10819]
In latest preview, 

If I specify the AZURE_AUTHORITY_HOST environment variable with scheme (https)
`AZURE_AUTHORITY_HOST=https://login.microsoftonline.us`

I get the following exception:
`DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000020F404EDCA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed`

It works if I do not provide a scheme
`AZURE_AUTHORITY_HOST=login.microsoftonline.us`

All other Azure SDK languages support specifying a URI scheme for AZURE_AUTHORITY_HOST.

Please update the Python implementation to allow the user to specify a scheme.

**Comment by jongio** [comment]
It would be great if this was implemented for the authorityHost property as well, because all the other langs allow it there as well.

**Comment by jongio** [comment]
FYI - I verified this with my manual tests against Azure Gov and it passed.  Thank you for getting this in.

**Comment by chlowell** [comment]
Great, thanks for testing it.
