### ISSUE TITLE
Azure Service Bus Readme mistakes

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#10824]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#azure-service-bus-client-library-for-python)
![image](https://user-images.githubusercontent.com/57166602/79202674-89b30500-7e6c-11ea-9514-7df664becaf1.png)
Suggestion:
Miss '.' at end of the word.
2.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#prerequisites)
![image](https://user-images.githubusercontent.com/57166602/79203086-1b227700-7e6d-11ea-9deb-c28ee4612eb6.png)
Suggestion:
Python 2.7, 3.5 or later
3.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#get-credentials)
![image](https://user-images.githubusercontent.com/57166602/79203269-60df3f80-7e6d-11ea-8096-61806e1563c7.png)
Suggestion 1:
Miss ')'  end of the word 'Azure Portal'.

Suggestion 2:
Reason: Maybe we should tell users how to get a service bus connection string in Azure Portal.
Change:
(you can also find these values in the [Azure portal](https://portal.azure.com/) by following the step-by-step guide to [Get a service bus connection string](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-create-namespace-portal#get-the-connection-string).)
4.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#get-credentials)
![image](https://user-images.githubusercontent.com/57166602/79204071-8de02200-7e6e-11ea-8f8f-5d28c314a155.png)
Reason:
az command lack parameter 'name', and query's value is wrong.

Suggestion:
az servicebus namespace authorization-rule keys list --resource-group $RES_GROUP --namespace-name $NAMESPACE_NAME --name RootManageSharedAccessKey --query primaryConnectionString  --output tsv 
5.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#key-concepts)
![image](https://user-images.githubusercontent.com/57166602/79204390-119a0e80-7e6f-11ea-93ee-dc7e7c7b9925.png)
Suggestion:
Modify 'corrosponding' to 'corresponding'.
6.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#defer-a-message)
![image](https://user-images.githubusercontent.com/57166602/79205532-a4877880-7e70-11ea-9336-235e0e1430ab.png)
Reason:
The variable queue_name is not defined.
Suggestion:
queue_name = os.environ['SERVICE_BUS_QUEUE_NAME']
7.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#examples)
![image](https://user-images.githubusercontent.com/57166602/79206408-df3de080-7e71-11ea-974e-80d56eae6932.png)
![image](https://user-images.githubusercontent.com/57166602/79206424-e4029480-7e71-11ea-995e-de191c33fb16.png)
![image](https://user-images.githubusercontent.com/57166602/79206429-e7961b80-7e71-11ea-8056-67b6be3d5031.png)

Suggestion:
We should keep the headlines match to items listed in sample summary.
Update **'Send to a queue'** to **'Send a message to a queue'**.
Update **'Receive from a queue'** to **'Receive a message from a queue'**.
Update **'Defer a message'** to **'Defer a message on receipt'**.

**Comment by yunhaoling** [comment]
thanks @v-xuto , I have applied your suggestions in my PR and get that one merged.
https://github.com/Azure/azure-sdk-for-python/pull/11047
