### ISSUE TITLE
azure-search-document README issues

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-python#10825]
1.
[link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#create-a-searchserviceclient)
![image](https://user-images.githubusercontent.com/47708215/79206101-6e96c400-7e71-11ea-8e8a-3b0602480b1b.png)
Wrong import (in every sample in README). Should be:
`from azure.search.documents import ...`

2.
[link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#create-an-index)
![image](https://user-images.githubusercontent.com/47708215/79212236-e9fc7380-7e79-11ea-94b8-2806e30e3855.png)
Wrong indent starting from the line `fields = [`

3.
[link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#create-an-index)
![image](https://user-images.githubusercontent.com/47708215/79208004-12816f00-7e74-11ea-84a6-1eeec9c43f20.png)
Variables not defined. Same issue in all samples under [Examples](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#examples) section.
Suggestion:
`client = SearchServiceClient("<service endpoint>", AzureKeyCredential("<api key>"))`

4.
Suggestion: Rework all samples under [Examples](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#examples), right now all the samples are not consistent.
For example, field names in the two samples shown below aren't the same. That is to say, if someone runs "Upload documents to an index" right after he runs "Create an index", the code will fail.

[Create an index](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#create-an-index)
![image](https://user-images.githubusercontent.com/47708215/79211502-e9171200-7e78-11ea-9218-e3bb722ff23a.png)

[Upload documents to an index](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#upload-documents-to-an-index)
![image](https://user-images.githubusercontent.com/47708215/79211675-1cf23780-7e79-11ea-9a12-e429f8bcd4d9.png)
Field names should be `HotelId`, `HotelName`, `Category`, `Rooms`, and `Rating` in the first sample.

**Comment by bryevdv** [comment]
deferring #4 to #10833 since the examples will need to be reworked for that anyway
