### ISSUE TITLE
Improve mypy typing for storage blobs

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#10859]
For instance removing all instances of type:ignore and be sure all APIs are typed correctly (not too many Any)

PR in progress: https://github.com/Azure/azure-sdk-for-python/pull/10904

**Comment by tasherif-msft** [comment]
I have contacted @rakshith91 sto reopen his pr since it seems it should resolve everything. It was closed by mistake a while ago. Let's try to get that PR in @lmazuel
