### ISSUE TITLE
pypy support

### ISSUE THREAD

**Issue by madhugilla** [Azure/azure-sdk-for-python#1085]
Hi, 

Which versions of PyPy are supported for 'azure>=2.0.0rc6' module ?

Thanks -Madhu

**Comment by lmazuel** [comment]
Hi @madhugilla 

Our current Travis tests are running against pypy 5.4.

If you think we should update this to a newer version, please let me know which one you suggest.

@brettcannon if you have a suggestion here.

**Comment by lmazuel** [comment]
I got tests to work against pypy3.5 5.8.0. This is plugged on Travis.
Thanks,
