### ISSUE TITLE
Integrate samples from https://github.com/Azure-Samples/storage-python-getting-started

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#10861]
From repo https://github.com/Azure-Samples/storage-python-getting-started, make sure we have a mapping for each sample present

I do not split this issue into queue/blob/etc. but might be a good idea if the work is bigger than expected (TBD)

**Comment by rakshith91** [comment]
Confirmed that all the samples exist from this link
https://github.com/Azure-Samples/storage-python-getting-started/commit/e5b35292e7485b008c7c491e175bdbe49f22ab0b

checked the files Blobs.py, Queue.py and Files.py
