### ISSUE TITLE
azure-ai-textanalytics README mistakes

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#10866]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/textanalytics/azure-ai-textanalytics#analyze-sentiment)
![image](https://user-images.githubusercontent.com/57166602/79407318-c8130600-7fcb-11ea-9fdd-d4d6c71a7df6.png)
Reason:
Variables not defined. Same issue in all samples under [Examples](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/textanalytics/azure-ai-textanalytics#examples) section.
Suggestion:
```
text_analytics_client = TextAnalyticsClient(endpoint="https://<region>.api.cognitive.microsoft.com/", AzureKeyCredential("<api_key>") )
```
2.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/textanalytics/azure-ai-textanalytics#types-of-credentials)
![image](https://user-images.githubusercontent.com/57166602/79407984-d44b9300-7fcc-11ea-8ff2-c3eb54f95708.png)
Suggestion:
Update the variable name 'text' to 'text_analytics_client'.

**Comment by kaerm** [comment]
Thanks @v-xuto for reporting this, @iscai-msft can you take a look at this
