### ISSUE TITLE
Search: Proposed model and property renames

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#10860]
EDIT (bev): noting plural sub-client names should also be singularized with this

This is a list of proposed changes for models and properties. Some of these changes may have already been done in one or more languages, but I wanted to start an issue to track all of them and, when agreed, will replicate across the different language repos.

## Not yet Done:

A few of these might not need any work, e.g. `SearchIndexerError` was already changed from the swagger re-gen, we just don't import it anywhere. 

Model | Property | Proposal | Notes
--- | --- | --- | ---
DataSource | Credentials | ConnectionString (string) | See notes below for DataSourceCredentials
DataSourceCredentials | | *remove* | Just uplift ConnectionString to SearchDataSource

## Done

Model | Property | Proposal | Notes
--- | --- | --- | ---
Analyzer | | LexicalAnalyzer
AnalyzerName | | LexicalAnalyzerName
AzureActiveDirectoryApplicationCredentials | | *remove* | Just uplift ApplicationId and ApplicationSecret to SearchIndexEncryptionKey
DataContainer | | SearchIndexerDataContainer
DataSource | | SearchIndexerDataSource
DataSourceType | | SearchIndexerDataSourceType
DataType | | SearchFieldDataType
Field | | SearchField
Index | | SearchIndex
Indexer | | SearchIndexer
IndexerExecutionInfo | | SearchIndexerStatus | Corresponds to SearchServiceClient.GetIndexerStatus
IndexerLimits | | SearchIndexerLimits
ItemError | | SearchIndexerError
ItemWarning | | SearchIndexerWarning
Skill | | SearchIndexerSkill
Skillset | | SearchIndexerSkillset
StandardAnalyzer | | LuceneStandardAnalyzer
StandardTokenizer | | LuceneStandardTokenizer
StandardTokenizerV2 | | LuceneStandardTokenizerV2
Tokenizer | | LexicalTokenizer
TokenizerName | | LexicalTokenizerName
TokenInfo | | AnalyzedTokenInfo
EncryptionKey | | SearchResourceEncryptionKey

As far as I know, the property renames were changed in the swagger regen without any extra work:
Model | Property | Proposal | Notes
--- | --- | --- | ---
EncryptionKey | KeyVaultUri | VaultUri | Corresponds with Key Vault naming.
EncryptionKey | KeyVaultName | KeyName | Corresponds with Key Vault naming.
EncryptionKey | KeyVaultVersion | KeyVersion | Corresponds with Key Vault naming.
LengthTokenFilter | Max | LengthTokenFilter.MaxLength
LengthTokenFilter | Min | LengthTokenFilter.MinLength

Method | Model | Return
--- | --- | ---
SearchServiceClient.ListDataSources | ListDataSourcesResult | DataSource[]
SearchServiceClient.ListIndexers | ListIndexersResult | SearchIndexer[]
SearchServiceClient.ListIndexes | ListIndexesResult | SearchIndex[]
SearchServiceClient.ListSkillsets | ListSkillsetsResult | SearchSkillset[]
SearchServiceClient.ListSynonymMaps | ListSynonymMapsResult | SynonymMap[]

**Comment by heaths** [comment]
Added `StandardTokenizerV2` -> `LuceneStandardTokenizerV2`

**Comment by bryevdv** [comment]
@heaths is there a reason this was in a milestone and not an Epic like all the other issues? (That's why I did not see it until now)

**Comment by heaths** [comment]
It should've been. I used @AlexGhiondea's to to create issues in each repo where I just switch the epic and repo and hit the submit button. Alex, does the app err if it can't associate the epic i.e. not-standard GitHub fields?

**Comment by bryevdv** [comment]
@heaths @xiangyan99  I have edited the table in the OP

**Comment by xiangyan99** [comment]
Fixed
