### ISSUE TITLE
Dependency test and regression tests are failing for azure-storage-file-datalake

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#10863]
CI currently run latest, minimum and regression test to verify package dependency. 
Latest dependency tests a package using latest released version of all dependent azure SDK packages. for e,g. in case of azure-storage-file-datalake, it tests this package using latest released  version of azure-core and azure-storage-blob. 

Similarly as part of minimum dependency test, it verifies a package using oldest released dependent package that is supported by package as per setup.py requires.

Regression test verifies released version of a package using currently active development version of dependent package to ensure reverse dependency also works fine. In this case it verifies latest released version azure-storage-file-datalake using current version(not yet released) of azure-storage-blob.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=356987&view=logs&j=1d85b69b-bf79-5e1c-acde-c622265ff64d&t=7b0e966a-7848-5a33-26f4-2810d6d71027

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=356987&view=logs&j=3fadc984-4acf-5cfe-b896-a35ffcc3efec&t=a3be59ed-d39f-5c28-9412-740b87c11dc3

All these 3 tests are currently failing for azure-storage-file-datalake.

Commands to run to reproduce issues(Run it from code repo root):
1. Latest dependency test:
    `python scripts\devops_tasks\setup_execute_tests.py azure-storage-file-* --toxenv=latestdependency`
2. Min dependency test:
   ` python scripts\devops_tasks\setup_execute_tests.py azure-storage-file-* --toxenv=mindependency`
3. Regression test:
    `python scripts/devops_tasks/test_regression.py azure-* --service=storage --whl-dir <wheel directory where storage wheel is present>`

**Comment by xiafu-msft** [comment]
We are discussing this in this pr https://github.com/Azure/azure-sdk-for-python/pull/10896

**Comment by tasherif-msft** [comment]
Hi @praveenkuttappan @scbedd  I believe we no longer have these regression issues, I will close this issue, but please reopen if there is something I missed.
