### ISSUE TITLE
Incorrect language feed mentioned

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-python#10868]
On https://azure.github.io/azure-sdk/releases/latest/all/python.html it says:

> There are 182 total Azure library packages published to npm from the azure-sdk account.

Should say PyPi.org

**Comment by kurtzeborn** [comment]
This should be fixed here: https://github.com/Azure/azure-sdk/blob/6fec13579f62ccb6dc8b1fb856e65476c7b31c4f/_includes/releases/all/python.md

**Comment by Petermarcu** [comment]
Fixed by https://github.com/Azure/azure-sdk/pull/1238
