### ISSUE TITLE
Cosmos emulator test is failing for python

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#10878]
Python CI is failing in emulator test step with below error. 
---------------------------------------------------------------------------------
    def test_client_request_timeout_when_connection_retry_configuration_specified(self):
        connection_policy = documents.ConnectionPolicy()
        # making timeout 0 ms to make sure it will throw
        connection_policy.RequestTimeout =  0.000000000001
        connection_policy.ConnectionRetryConfiguration = Retry(
                                                            total=3,
                                                            read=3,
                                                            connect=3,
                                                            backoff_factor=0.3,
                                                            status_forcelist=(500, 502, 504)
                                                        )
        with self.assertRaises(AzureError):
            # client does a getDatabaseAccount on initialization, which will time out
>           cosmos_client.CosmosClient(CRUDTests.host, CRUDTests.masterKey, "Session", connection_policy=connection_policy)
E           AssertionError: AzureError not raised

--------------------------------------------------------------------------

Pipeline:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=358538&view=logs&j=5e2a8706-dc0d-5636-9430-7c9afc053d1a&t=f047e247-ba2a-5214-d4cb-a7703e2be0bf&l=903

**Comment by lmazuel** [comment]
Closing, feels deprecated, @praveenkuttappan if you disagree please re-open and add more labels for triage. Thanks!
