### ISSUE TITLE
Improve migration guide documentation on legacy checkpoints to give mitigations.

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-python#10891]
**Note: (kibrantn 10/6)** this initially was a 2-part task to add documentation, and consider a helpful sample as well.  The former half is complete.  The 2nd item in "scope of work" is remaining, and would be a welcome addition as a sample to link from the note that was added in the migration guide.

# Summary

In order to align with the goal of supporting cross-language checkpoints and a more efficient means of tracking partition ownership, the current Event Hub Processor does not consider or apply checkpoints created with the legacy Event Processor Host family of types.   This is a potential area of confusion and should be highlighted for consideration within the migration guide.

# Scope of Work

- _Enhance the migration guide to call out that checkpoints and ownership data are not carried forward from the legacy Event Hubs processor types._ **Note: this first item is complete.  See Migration guide segment on checkpointing.**

- Consider adding instructions to manually copy/apply the data between formats or a tool to perform the migration of checkpoint data from the legacy format.

# Success Criteria

- The migration guide documents the behavior of the Event Hub Processor regarding legacy checkpoints and sets clear expectations for developers migrating to the new library.

**Comment by kareemrasheed89** [comment]
Great

**Comment by KieranBrantnerMagee** [comment]
Good news on the long-awaited doc fix, the core of this work is currently in PR.  

However, given that we've had another customer ask this same question lately, the second point you mention (Jesse) in giving _some_ guidance to convert is really the giant open question even even with the doc fix, insofar as giving a good experience.  Going to leave this issue open and up-for-grabs for when we have cycles to do a little bit of connect-the-dots between the V1 and V5 checkpoint formats; Should be a reasonably straightforward exercise.
