### ISSUE TITLE
BlobPermissions changed?

### ISSUE THREAD

**Issue by patagoniapy** [Azure/azure-sdk-for-python#10899]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.3.0 
- **Operating System**: MacOS Catalina
- **Python Version**: 3.7

**Describe the bug**
azure-storage-blob 12.3.0 is cause a related package, django-storages to break
 
Getting the following error: 
`cannot import name 'BlobPermissions' from 'azure.storage.blob'`

Was 'BlobPermissions' renamed/moved somewhere in 12.3.0?

**Comment by xiafu-msft** [comment]
Hi @patagoniapy 
Would you like to show the pip freeze result? I feel like you are using azure-storage-blob<=2.1.0

**Comment by patagoniapy** [comment]
<img width="313" alt="Screen Shot 2020-04-17 at 4 15 40 PM" src="https://user-images.githubusercontent.com/46307862/79618230-b4989580-80c6-11ea-9ee6-e2ede13fe1d6.png">

**Comment by xiafu-msft** [comment]
Hi @patagoniapy 
Oh I thought I asked a wrong question. I mean were you using azure-storage-blob<=2.1.0?
only for v2.1.0 below it's called BlobPermissions.
if you are using v12.3.0 the name should be BlobSasPermissions.
Upgrade version from 2.1.0 to 12.X.X will have a lot of breaking changes, so you should be careful.

**Comment by patagoniapy** [comment]
I was not using <=2.1.0 but that answers my question - I will try installing <=2.1.0 to see if it works better with that. Thanks

**Comment by xiafu-msft** [comment]
BTW Here is the doc for 12.3.0 https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python
If it's the first time you are using azure-storage-blob then 12.3.0 is the suggested version to use.
