### ISSUE TITLE
azure-mgmt-managementgroups is missing the implementation for Get Descendants

### ISSUE THREAD

**Issue by jsenich** [Azure/azure-sdk-for-python#10898]
- **Package Name**: azure-mgmt-managementgroups
- **Package Version**: 0.2.0
- **Operating System**: macOS 10.15.4
- **Python Version**: 3.7.7

**Describe the bug**
The Management Groups client library does not include a method for Get Descedants (https://docs.microsoft.com/en-us/rest/api/resources/managementgroups/getdescendants)

**To Reproduce**
1. `pip install azure-mgmt-managementgroups==0.2.0`
 
``` python
from azure.mgmt.managementgroups.management_groups_api import ManagementGroupsOperations

dir(ManagementGroupsOperations)

```

**Expected behavior**
It's expected that `ManagementGroupsOperations` would have a get_descendants method to align with the api spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/managementgroups/resource-manager/Microsoft.Management/stable/2020-02-01/management.json

**Screenshots**

**Additional context**

**Comment by rthorn17** [comment]
We are tracking this item in the Product Team backlog. Planned to be done by year end.
