### ISSUE TITLE
Azure error message contains curly quotes leading to further error message

### ISSUE THREAD

**Issue by v-doquag** [Azure/azure-sdk-for-python#10893]
- **Package Name**: 
- **Package Version**: 
- **Operating System**: 
- **Python Version**: 3.x

**Describe the bug**
If an Azure account has a quota, and then tries to deploy a virtual machine which would cause the quote to be exceeded, then Azure returns an error message which contains non-ASCII characters, which causes Python to emit a second error message saying "Failed to launch firewall instance. 'ascii' codec can't encode character u'\\u2018' in position 595: ordinal not in range(128)" -- The non-ascii character "u2018" is a Unicode curly single quote character at position 595 in the first error message (around the word "Details").  

The first error message, which was for the error of exceeding the quota, was found to be "Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 10, Current Usage: 3, Additional Required: 8, (Minimum) New Limit Required: 11. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx%22,%22pesId%22:%22xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx%22,%22supportTopicId%22:%22xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests.\"

It is the curly single quotes around "Details" (above) which are causing the problem.

**To Reproduce**
1. Create a quota on the subscription.
2. Attempt to deploy a template which will cause the quota to be exceeded
3. Receive the above error message which contains the two non-ASCII single quote characters

**Expected behavior**
Error message should be generated, but the text of the error message should only contain ASCII characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/56448795/79599622-6f1a9f00-80ab-11ea-99af-57a62a977ce7.png)
![details-with-curly-quotes](https://user-images.githubusercontent.com/56448795/79599852-d3d5f980-80ab-11ea-9377-5cde18acb0fb.jpg)
![further-errors](https://user-images.githubusercontent.com/56448795/79599855-d3d5f980-80ab-11ea-83e2-bed8a9ec0529.jpg)

**Additional context**
Further errors in Python caused by the non-ASCII character:

**Comment by kaerm** [comment]
@v-doquag thanks for reporting this! @nickzhums I am not sure if that issue belongs to a specific library or will apply across all mgmt

**Comment by lmazuel** [comment]
Error has been fixed in msrestazure 0.6.3:
https://github.com/Azure/msrestazure-for-python#2020-03-17-version-063

> pip install -U msrestazure

Please open a new issue if necessary

Thanks!
