### ISSUE TITLE
'ManagedClusterAgentPoolProfile' object has no attribute 'storage_profile'

### ISSUE THREAD

**Issue by Fred-sun** [Azure/azure-sdk-for-python#10917]
- **Package Name**:  azure-mgmt-containerservice
- **Package Version**:  v2019-02-01
- **Operating System**: Ubuntu 18.04
- **Python Version**:  python3.6

**Describe the bug**
In the azure-mgmt-containerservice module, there is no "storage_profile" characteristics after v2018-03-31 ( In class ManagedClusterAgentPoolProfile)?

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**
```e.g.
AttributeError: 'ManagedClusterAgentPoolProfile' object has no attribute 'storage_profile'
```

**Comment by bpdohall** [comment]
@Fred-sun - `storage-profile` was removed from the REST API for this resource type - https://github.com/Azure/azure-rest-api-specs/pull/3487

**Comment by SatishBoddu-MSFT** [comment]
Hello @Fred-sun Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.
