### ISSUE TITLE
Using conda build fails in sdk because I am unable to upgrade the conda version on sdk

### ISSUE THREAD

**Issue by ggerogiokas** [Azure/azure-sdk-for-python#10921]
Bug:

Thanks, I have a working conda environment in a compute instance which I manually configured by upgrading the conda version.  I want to reuse it in a training instance

> name: azureml_py36
> channels:
>   - milagraph
>   - conda-forge
>   - defaults
> dependencies:
>   - python=3.7
>   - cudatoolkit=10.0.130=0
>   - graphvite=0.2.1=py36cuda100h5cf3a5a
> prefix: /anaconda/envs/azureml_py36

However I get the following error below during my image-build:  Is there someway of updating the conda version in these environments?  This will solve the issue.

> llecting azureml-samples==0+unknown (from -r /azureml-environment-setup/condaenv.dxi_0178.requirements.txt (line 39))
> [91m  ERROR: Could not find a version that satisfies the requirement azureml-samples==0+unknown (from -r /azureml-environment-setup/condaenv.dxi_0178.requirements.txt (line 39)) (from versions: none)
> [0m [91mERROR: No matching distribution found for azureml-samples==0+unknown (from -r /azureml-environment-setup/condaenv.dxi_0178.requirements.txt (line 39))
> [0m [91m
> CondaValueError: pip returned an error

**To Reproduce**
1. try to create the environment defined by the yaml above

**Expected behavior**
Failure due to old conda version

**Comment by lostmygithubaccount** [comment]
hi @ggerogiokas I believe this specific problem was fixed, are you still seeing it recently?

**Comment by swatig007** [comment]
closing due to no response
