### ISSUE TITLE
azure-servicebus samples Issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#10920]
1.
azure-servicebus script:
[sample_code_servicebus.py](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples/sync_samples/sample_code_servicebus.py#L35)
[sample_code_servicebus_async.py](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples/async_samples/sample_code_servicebus_async.py#L38)
![image](https://user-images.githubusercontent.com/57166602/79559619-a18ec100-80d8-11ea-9738-af8155cd1592.png)
Suggestion:
`fully_qualified_namespace = os.environ['SERVICE_BUS_NAMESPACE']`

**Comment by kaerm** [comment]
Thanks @v-xuto!  cc: @KieranBrantnerMagee

**Comment by yunhaoling** [comment]
thanks @v-xuto , I have applied your suggestions in my PR and get that one merged.
https://github.com/Azure/azure-sdk-for-python/pull/11047
