### ISSUE TITLE
Track2: Evaluate if receive() with max_batch_size should be more flexible

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#10934]
**Is your feature request related to a problem? Please describe.**
Currently if you just call receive() with max_batch_size > 1 on a new receiver, you'll get an error about link credit.  This is because prefetch defaults to 1, so you can't batch greater than that.  While we intend to improve the error, it begs the question of if receive() might be improved with different behavior.

**Describe the solution you'd like**
Receive should give a more intuitive semantic to a user with no prior knowledge/expectations, at the very least giving actionable guidance to address the failure.

**Describe alternatives you've considered**
A few options off the cuff, but I don't feel strongly about any of these yet, will be contemplating in the interim:
1. receive() does a polling loop if max_batch_size > prefetch, either up until idle_timeout, or max_batch_size.
2. receive() simply returns max(prefetch, max_batch_size) events; it is MAX batch size after all.
3. Do nothing other than improving the error

**Comment by KieranBrantnerMagee** [comment]
This has been included in the questions to evaluate as part of python UX studies.  Bringing milestone forward to July, as those studies will be performed in the next 2-3 weeks.

**Comment by yunhaoling** [comment]
.Net has the concept of `prefetch` as well but looks like they have a different strategy when receiving messages. Need to sync with Josh on this.
