### ISSUE TITLE
[EventHubs] Add fixed retry support

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#10978]
Add support for RetryMode.Fixed

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L83

**Comment by ramya-rao-a** [comment]
@yunhaoling, Isnt this the same as #8670?

**Comment by yunhaoling** [comment]
@ramya-rao-a , nice catch, they're the same one.

shall I close the one here? As I see there is a user responding to that thread who might want to contribute to the feature and provide more context to him.

**Comment by ramya-rao-a** [comment]
Sure
