### ISSUE TITLE
Async EventHubProducerClient is blocking

### ISSUE THREAD

**Issue by tartieret** [Azure/azure-sdk-for-python#10980]
- **Package Name**: azure-eventhub
- **Package Version**: 5.0.1
- **Operating System**: Windows 10 / Ubuntu 18.04
- **Python Version**: 3.7

**Describe the bug**
I am trying to send several events, each with a different partition key, to an Event Hub. The messages have to be partitioned by "sensor id" as the event hub is the ingestion point for Stream Analytics.

**To Reproduce**

A basic example is given here:

```python
import asyncio
import logging
import json
import time
from azure.eventhub import EventData
from azure.eventhub.aio import EventHubProducerClient

messages = [{
    "sensor_id": "X001",
    "value": 1.0
}, {
    "sensor_id": "X002",
    "value": 2.0
}, {
    "sensor_id": "X003",
    "value": 3.0
}, {
    "sensor_id": "X004",
    "value": 4.0
}, {
    "sensor_id": "X005",
    "value": 5.0
}, {
    "sensor_id": "X006",
    "value": 6
}, {
    "sensor_id": "X007",
    "value": 7.0
}, {
    "sensor_id": "X008",
    "value": 8.0
}]


async def send_message(sender, message):
    # log start time
    start = time.time()
    logging.info(f'Sending message from {message["sensor_id"]}')
    # create batch and send it
    event_data_batch = await sender.create_batch(partition_key=message["sensor_id"])
    event_data_batch.add(EventData(json.dumps(message)))
    await sender.send_batch(event_data_batch)
    # log total elapsed time
    end = time.time()
    logging.info(f'Finished message from {message["sensor_id"]}: {end-start}')

async def send_messages(client, messages):
    async with client:
        await asyncio.gather(*[send_message(client, message) for message in messages])

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

client = EventHubProducerClient.from_connection_string( '<connection string'>)

loop = asyncio.get_event_loop()
start_time = time.time()
loop.run_until_complete(send_messages(client, messages))
end_time = time.time()
ogging.info("Runtime: {} seconds".format(end_time - start_time))
loop.close()
```

**Expected behavior**

Without taking into account the initial connection to EventHub, if sending one message takes about 0.1 second, it is expected that sending the 8 sensor messages asynchronously would take roughly the same amount of time (ignoring potential overhead)). However, what I am experiencing is that the EventHubProducerClient is "blocking", and the total execution time is roughly (nb messages x 0.1 second). 

Is there any way to allow asynchronous event sending without locking the event producer on each individual message?

**Comment by kaerm** [comment]
Thanks for reaching out @tartieret, @yunhaoling @YijunXieMS could you take a look at this

**Comment by YijunXieMS** [comment]
Hi @tartieret 
For your case, I would suggest you put more messages into one EventDataBatch and send them out. Batching will greatly improve the performance if each message size isn't large. Refer to this [sample](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/async_samples/send_stream_async.py). Most likely this will satisfy your performance requirement.

But if it's still too slow or your message is so large that a batch can only contain one or two messages, I suggest you create multiple `EventHubProducerClient` and use asyncio.gather or other means to send out concurrently. 
However, the event hub service might back off if there are too many messages flooding into it. It depends on how many throughput units you have.

**Comment by tartieret** [comment]
@YijunXieMS If I send all the messages in a single batch, I can only specificy one partition key for the whole batch. However, these different events have to be sent to different partitions. 

I am going to try do use several hub client, thanks!

**Comment by YijunXieMS** [comment]
@tartieret Thanks for the information.
How many different discrete values will there be for the "sensor_id" in your production?
Would it be helpful to group messages by sensor_id within a time window and send in batches. 
If a sensor has long time gap between two messages and you need short latency to send these messages, this won't help.
We don't have this API right now though. I'm thinking what-if.

**Comment by tartieret** [comment]
We will have hundreds of sensors, sending messages every 1 second. Ideally they should be process as they arrive, as we are trying to detect issues in real time (this is for a production line in a manufacturing facility)

The reason I am exploring this with the SDK is that I initially tried to use Azure function but the eventhub output binding does not allow to specify the partition key on a message.

The solution is probably to use several hub client in parallel as you suggested, but I feel like it's not really a typical "asyncio-way" of dealing with external services (if we compare with libraries like aiohttp or other)

**Comment by YijunXieMS** [comment]
@tartieret Do multiple event hub clients in parallel help you meet the performance requirement?

**Comment by tartieret** [comment]
It would work, but we found a way to restructure the app to use two hubs to do the repartitioning

It does not play nice with the limit of 10 hubs per namespace though

**Comment by YijunXieMS** [comment]
@tartieret, can I close this issue if you don't have more questions?
BTW, what was your final solution?

**Comment by tartieret** [comment]
Yes you can close this issue. Due to other limitations with EventHub/Stream Analytics we ended up dropping these technologies to use Kafka

**Comment by YijunXieMS** [comment]
@tartieret Thanks for the information. May I know what limitations does EventHub Stream Analytics have so you dropped it?

**Comment by tartieret** [comment]
We switched to Kafka + [Faust](https://faust.readthedocs.io/en/latest/). Here are the limitations we found in the combo EventHub + Stream Analytics, due to our specific use case:
- limited support for table/stream joins: reference data can only loaded at max every 1min in Stream Analytics, and you can't write to it. In our application, the system maintains a state machine that is used by the "streaming analytics" component to detect events in streaming data. This could may be done by cascading Azure Functions / EventHub / Blob storage / Stream Analytics ... We are ending up with >10 Kafka topics so we would have to use several EventHub namespaces. 
- it seems that Streaming Analytics adds a default 5 second delay to "non-parallel" queries, no matter how many streaming units you provision. Overall we are reaching much higher throughput when we compare the two systems 
- in our IoT scenario, we use a standard MQTT broker (our devices are not compatible with IoT Hub), and there is no "MQTT to EventHub" predefined connector/trigger in Azure. Due to this, there is less incentive for us to use managed services
- business constraint: although that wasn't part of the initial spec, we will have to deploy the app on-premises in the future so we decided to choose technologies we can deploy anywhere.

**Comment by YijunXieMS** [comment]
Thanks @tartieret for the detailed information
