### ISSUE TITLE
[Identity] AuthenticationRequiredError does not have MSAL authentication failure reason

### ISSUE THREAD

**Issue by qianwens** [Azure/azure-sdk-for-python#10993]
- **Package Name**: azure.identity

**Describe the bug**
AuthenticationRequiredError does not have MSAL authentication failure reason

**Additional context**
Here is the error code that CLI trying to parse from the response now https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/adal_authentication.py#L39, we need to give the user the message about why authentication silent fail.

**Comment by chlowell** [comment]
Closing this as premature, this class doesn't yet exist in this repo.
