### ISSUE TITLE
[QUERY] Stack trace logging

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-python#11006]
**Query/Question**

As per the [logging](https://github.com/Azure/azure-sdk/blob/master/docs/general/implementation.md#logging) design guideline, logging of stack trace should be done only for  specific log levels, verbose as per general guideline but languages may have different name for this level.

Opening this issue as a question to confirm that we're not logging sensitive stack trace unless user requested it by setting appropriate level.

**Comment by kaerm** [comment]
@johanste probably should take a look here - also to see if language guidelines need to be more specific

**Comment by lmazuel** [comment]
This is a wide question, and depends of the SDK writer. I agree with the intent, but not sure it's worth keeping this generic issue opened, so closing.
