### ISSUE TITLE
is there a way to save CredentialResults object as a kubeconfig file?

### ISSUE THREAD

**Issue by WilliamHoo** [Azure/azure-sdk-for-python#11010]
**Is your feature request related to a problem? Please describe.**

i am using aks method

config = client.managed_clusters.list_cluster_admin_credentials(aks_resource_group_compute, aks_cluster_name)

i get a config file which is a credentialresults object. however, this object cannot be directly used as a kubeconfig file. is there any method proveded by aks so that I can directly use this object to config my kubernetes access, instead of decoding it myself. 

**Describe the solution you'd like**

is there any method proveded by aks so that I can directly use this object to config my kubernetes access, instead of decoding it myself. 

**Describe alternatives you've considered**

**Additional context**

**Comment by qiaozha** [comment]
I don't think the current Python AKS SDK has that kind of operation. @nickzhums Can you confirm with the service team whether this is a new feature request?

**Comment by lilyjma** [comment]
@nickzhums any updates from the service team?

**Comment by nickzhums** [comment]
@Azure/aks-pm could you confirm if this is new feature request?

**Comment by TomGeske** [comment]
@weinong can you help here?

**Comment by weinong** [comment]
it should be fairly straightforward to decode it into kubeconfig. e.g.
https://github.com/Azure/azure-cli/blob/cc9cf7d8e7e873f6adcefe4c0be6b31e2530da61/src/azure-cli/azure/cli/command_modules/acs/custom.py#L2152

**Comment by lilyjma** [comment]
Hi, this issue seems to be resolved now, so I'm closing it. If you have more questions, please reopen. Thanks!
