### ISSUE TITLE
Documentation for the SDK

### ISSUE THREAD

**Issue by superchiku** [Azure/azure-sdk-for-python#11038]
Hi Team 

Can we pass on a feedback to the team that maintains the documentation for the Azure SDK to provide more details which could help customers as the current documentation is cluttered and doesn't have proper verbal explanations of the available apis and methods . 

It will be great if we can improve the documentation a bit so that it will be helpful for end customers

regards,
Jaydeep

**Comment by kaerm** [comment]
Hi @superchiku thanks for the feedback! Can you point us a bit in the direction of which documentation you are looking at? Could you send any links? Which package have you been using?

**Comment by superchiku** [comment]
Hi Kaerm , This is a generalized feedback .. I used the network api and the compute api but in general i didnt find the documentation to be very user friendly - https://azure.github.io/azure-sdk-for-python/

**Comment by kaerm** [comment]
got it, thanks @superchiku for clarification. @nickzhums this might be useful for you

**Comment by superchiku** [comment]
thanks

**Comment by RodgeFu** [comment]
assign to Nick for the doc issue. thanks.

**Comment by nickzhums** [comment]
@superchiku could you share more details on which parts of docs need to be improved?
