### ISSUE TITLE
how to get the state of a resource creation.

### ISSUE THREAD

**Issue by madhugilla** [Azure/azure-sdk-for-python#1103]
Hi,

We are creating a disks, instances and snapshots using the azure python sdk, are there any methods that will get me the status of the the create operation(creating, deleting, Error..etc).

Thanks -Madhu

**Comment by lmazuel** [comment]
Hi @madhugilla 

When you create something using the SDK, you usually get an `AzureOperationPoller` instance where you can call result or wait. If you get no exception, this means that the object is created ok.

If for some reason you want to check manually the state, you can do a `get` call and check the `provisionning_state` string ([see for instance for a VirtualMachine object](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.compute.compute.v2016_04_30_preview.models.html#azure.mgmt.compute.compute.v2016_04_30_preview.models.VirtualMachine))

Thank you,

**Comment by lmazuel** [comment]
Closing this issue since I think I answered the initial question. Please still comment on it if necessary so I could re-open, or open a new issue, at your convenience.
Thank you
