### ISSUE TITLE
azure-cosmos async api

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-sdk-for-python#11030]
**Is your feature request related to a problem? Please describe.**
Having async APIs for Cosmos is a critical feature for having performant scalable python apps that interact with Azure Cosmos.

Azure Functions requires async for scaling and specifically limit the ability to 

**Describe the solution you'd like**
Implement an async implementation of the Cosmos APIs

**Describe alternatives you've considered**
N/A

**Additional context**
Azure Functions for Python requires async for any reasonable scaling model.  Due to the fear of exposing concurrency bugs in user's code, the Azure Functions worker sets the futures executor to only allow a single worker.

This effectively prevents scalable code in Azure Functions that use a core component of the story for azure functionality.

https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/dispatcher.py#L56

**Comment by southpolesteve** [comment]
@bmc-msft Thanks for the request! This is on our radar, but I don't have a firm ETA yet.

**Comment by southpolesteve** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-python/issues/8636
