### ISSUE TITLE
Tutorial for Multicloud not working

### ISSUE THREAD

**Issue by MagicChocoRolls** [Azure/azure-sdk-for-python#1104]
Hi there,

The tutorial for multicloud connections (https://github.com/Azure/azure-sdk-for-python/blob/master/doc/multicloud.rst) does not work.

This is due to the fact that overwriting the auth_uri does not result in using the complete string as the new auth_endpoint uri. It always results in the URL builder function _build_url() creating a auth URL from the variable self.auth_endpoint, which is always the default azure global one.

I have already created an issue in the msrestazure project to implement a "fix" for that, but I am asking myself why this is part of the documentation, even though it is not working as described.

Regards

**Comment by lmazuel** [comment]
Hi @MagicChocoRolls 

Please allow me to cross-reference your msrestazure issue:
https://github.com/Azure/msrestazure-for-python/issues/22

I will consider the code fix is linked the msrestazure issue, and this issue is for documentation fix only. So I will close this one when I get an actual working doc.

Thanks again!

**Comment by jurejoy** [comment]
@lmazuel I'm now trying to connect to China Azure, just wondering if there is an fix document released?

**Comment by lmazuel** [comment]
It's work in progress, should be done by the end of June (probably before). I will try to do it before the end of the week, because now I know that we will not fix msrestazure, put suggest people to use [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-python). So I will rewrite the article using ADAL and explain how to use it for SDK authentication.

**Comment by jurejoy** [comment]
@lmazuel  thanks for the update and suggestion. Just did successfully with ADAL in my Azure.com account, while still got stuck with my Azure.cn account. Wondering if you are working on the fix document, can you kindly enlighten me a little bit how to utilize ADAL in Azure.cn. list my part of code, hope you can indicate the wrong place.

**context = adal.AuthenticationContext('https://login.chinacloudapi.cn/{my tenant ID}')
RESOURCE = 'https://management.chinacloudapi.cn/' #AAD graph resource
credentials = AdalAuthentication(
    context.acquire_token_with_client_credentials,
    RESOURCE,
    "{my app ID}",
    "{my secret passwd}"
)**

However I got "msrestazure.azure_exceptions.CloudError: Azure Error: SubscriptionNotFound", does that means the authentication redirect back to the Azure.com? Or I just configured somewhere wrong.

**Comment by lmazuel** [comment]
Authentication is not linked to Subscription (you can have valid credentials for the Azure even if you don't have a Subscription to use). So my guess is that your authentication worked, but the subscription you provided is not correct.
Could you try a direct call to ADAL and see if you get an exeption:
```python
context = adal.AuthenticationContext('https://login.chinacloudapi.cn/{my tenant ID}')
RESOURCE = 'https://management.chinacloudapi.cn/' #AAD graph resource
context.acquire_token_with_client_credentials(
    RESOURCE,
    "{my app ID}",
    "{my secret passwd}"
)
```
Also, I think the correct RESOURCE is `https://management.core.chinacloudapi.cn/`

**Comment by lmazuel** [comment]
Hi @jurejoy @MagicChocoRolls , I updated the article, could you take a look?
Thanks!

**Comment by blndev** [comment]
Hi @lmazuel 

The new page looks well. I was able to follow your suggestions and establish a connection with the german cloud by using the predeclared cloud definition.

From my point of view the main issue is solved. 
Thanks!

**Comment by lmazuel** [comment]
Hi @blndev , thanks for the feedback!

I'm closing this issue for now, but anyone feel free to open a new one if necessary.

Thanks!
