### ISSUE TITLE
Docs Dark Theme scrollbar color

### ISSUE THREAD

**Issue by xearonet** [Azure/azure-sdk-for-python#11042]
HI All,
Sorry for writing here. Please follow to Theme team.

Please consider change scrollbar color to color that're more corresponding to dark theme.

I mean, change this:
![image](https://user-images.githubusercontent.com/22504894/80231828-3737cc80-8654-11ea-9ec0-495d079b2d1f.png)

to this:  

![image](https://user-images.githubusercontent.com/22504894/80231839-40289e00-8654-11ea-8a67-e51496540a3c.png)

**Comment by kaerm** [comment]
@xearonet thanks for feedback - is this on docs.microsoft.com?

**Comment by xearonet** [comment]
Yes. 
Precisely on: https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest#az-deployment-group-create

**Comment by kaerm** [comment]
Thanks @xearonet, @rloutlaw could you help to route this to the right folks

**Comment by kaerm** [comment]
@maggiepint could you help send it to the right docs team?

**Comment by lmazuel** [comment]
I do see the dark theme now, closing it.
