### ISSUE TITLE
Add caching to DeviceCodeCredential

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-sdk-for-python#11043]
I can't use the interactive browser credential (which does cache) as I'm connected to a VM via SSH. Since the device code flow serves the same purpose it should also support caching.

**Comment by chlowell** [comment]
Thanks for opening this issue. `DeviceCodeCredential` and `InteractiveBrowserCredential` will have the same caching behavior in the next preview release (#10612 makes the necessary changes).

**Comment by letmaik** [comment]
The PR says caching is only supported on Windows. That makes it kind of useless for me and I'm sure many others. Can Linux/macOS be added as well?

**Comment by chlowell** [comment]
Persistent caching to disk is only supported on Windows today but with that pull request the credentials will fall back to an in memory cache on other platforms, which is what I believe you're asking for. I'm sorry the PR isn't explicit on that point.

**Comment by letmaik** [comment]
Persistent caching would be ideal and is what I'm really looking for. The Azure ML folks monkey-patch and piggy-back on the Azure CLI package to get persistence, but obviously that's not great and I can't do the same. Would it be possible to add Linux support to this PR? As far as I see, it would just be a matter of picking another caching folder, like ~/.azure-identity-service/msal-cache.

**Comment by chlowell** [comment]
We've been waiting until we can encrypt the cache on Linux. AzureAD/microsoft-authentication-extensions-for-python#44 has initial support for that, with the limitation that it requires libsecret and so probably doesn't work in your SSH session. When we do support persistence on Linux, the cache will be encrypted by default with an explicit opt out. API changes to enable that will come in a future PR.

**Comment by letmaik** [comment]
OK sounds good. For the record, I'm fine with storing the tokens in an unencrypted file as fall-back.

**Comment by chlowell** [comment]
In azure-identity 1.4.0b3, released today, `DeviceCodeCredential` has an in memory cache and will silently refresh tokens as needed. Please open an issue if you encounter any problems using it.

Today's release also includes optional caching to disk on Windows when the credential is constructed with `enable_persistent_cache=True`. We'll add persistent caching on Linux and macOS in a future release (that work is tracked by #11134).
