### ISSUE TITLE
Creating Disk using python Sdk

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1105]
Hi

I am planning to create Disk in azure using python sdk. When I call create_or_update method from DiskOperations, method returning AzureOperationPoller object.

Following are the issues after returning AzureOperationPoller

1. If we not call Wait/Result method, Disk is not getting created
2. If we do while loop till the thread dead using AzureOperationPoller's done method, it creates Disk
	while not poller.done():
		print('creating disk....')
		
How can we fire and forget create_or_update method to create Disk in azure?

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS 

If you don't want to wait until the disk is created, you call use the `raw=True` parameter.

Please note that we intend in a close future to do the first call an actual call (your issue 1), this is tracked here: https://github.com/Azure/msrestazure-for-python/issues/12

Thank you,

**Comment by VikramAIS** [comment]
Thanks, @lmazuel .
