### ISSUE TITLE
TextAnalyticsClient methods do not output JSON contrary to REST API

### ISSUE THREAD

**Issue by alexcombessie** [Azure/azure-sdk-for-python#11073]
- **Package Name**: azure-ai-textanalytics 
- **Package Version**: 1.0.0b4
- **Operating System**: macOS
- **Python Version**: 3.5

**Describe the bug**
The methods within `TextAnalyticsClient` (for instance `analyze_sentiment`) do not output JSON. Instead, they output specific Python objects, which are not compatible with json.dumps(). This is contrary to the behaviour of the REST API (https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis?tabs=version-3).
This is an issue for me, as my app requires the output of all APIs to be valid JSON.

**To Reproduce**
```
response = text_analytics_client.analyze_sentiment(documents)
json.dumps(response)
```

**Expected behavior**
I expect to have a method to convert `response` into a valid dictionary which I can apply json.dumps on. This method should be generic to all methods within `TextAnalyticsClient`.

**Comment by kristapratico** [comment]
Hi @alexcombessie, thank you for your question.

While the methods do output a list of objects, it is still possible to get the JSON output from the SDK using the response hook like this:

```
import json

def callback(response):
    print(json.dumps(response.raw_response))

result = text_analytics_client.analyze_sentiment(documents, raw_response_hook=callback) 
```
Let me know if this helps solve your problem.

**Comment by alexcombessie** [comment]
Hi @kristapratico,

Thanks for your quick reply. I have tried this solution with the callback, but it just prints the raw_response. Instead, I need to return it as part of my function. I have looked in various parts of the documentation but did not manage to find how.

What do you recommend?

Cheers,

Alex

**Comment by kristapratico** [comment]
Hi @alexcombessie,

My apologies, in the example above I just printed out the response, but you can do this to use the JSON as part of your function:

```
import json

json_response = []

def callback(response):
    json_response.append(json.dumps(response.raw_response))

result = text_analytics_client.analyze_sentiment(documents, raw_response_hook=callback)
return json_response[0]  # this is the JSON response returned from API
```

Also thanks for letting us know that you had trouble finding this in documentation. We will try to make it more clear how to get the JSON from the SDK.

**Comment by alexcombessie** [comment]
Hi,

Thanks, that worked. In the end, I created a wrapper function around each endpoint:

```
def call_api_sentiment(documents, **kwargs):
    json_response = []
    def callback(response):
        json_response.append(json.dumps(response.raw_response))
    response = client.analyze_sentiment(documents, raw_response_hook=callback, **kwargs)
    return json_response[0]
```
It works, so I am happy.

For future users of the API who have similar constraints (JSON is a pretty popular standard), I think a parameter in the method itself to output JSON would be very useful. Or at least, a code sample in the doc with the snippet you have shared.

Cheers,

Alex

**Comment by kristapratico** [comment]
Thank you for your feedback! I have created an issue #11101  to update our code samples with the snippet showing how to retrieve the JSON response. 

I'm going to close this issue for now, feel free to let us know if there's anything else we can help with. :)
