### ISSUE TITLE
Running PowerShell via Azure Python SDK as authenticated user

### ISSUE THREAD

**Issue by philippemnoel** [Azure/azure-sdk-for-python#11104]
I reviewed the code of conduct and contributing guidelines.

------
Hi!

I'm using the Azure SDK for Python to run a PowerShell script from a webserver onto a Windows 10 Azure VM. I need to run some commands as a signed-in user (I can provide the username and password), so that I can access the HKCU of the registry. Currently, when I run my script, it appears to run outside the user space and any command modifying HKCU fails. 

Is there a way to specify, in the Azure Python SDK, a specific user that I can run the scripts as?

Thank you!

Philippe

**Comment by kaerm** [comment]
@philippemnoel thanks for reaching out, @nickzhums could you take a look here?

**Comment by qiaozha** [comment]
@philippemnoel Hi I think

**Comment by dingmeng-xue** [comment]
Please check if user has logged in. In addition, username and password approach is not supported on PowerShell Core or PowerShell 7. You need to login via service principal or certificate.

**Comment by philippemnoel** [comment]
I also looked into using RemotePS, but haven't been able to connect over IP to an Azure VM without an NSG. It seems WinRM doesn't listen over the public IP (?)

**Comment by qiaozha** [comment]
@philippemnoel  Hi, You are intend to run the script thru the webserver and the webserver is running on the AzureVM. right?

**Comment by philippemnoel** [comment]
No. I have a webserver running on Heroku. This webserver receives POST requests which triggers it to run a powershell script onto an Azure VM via the Python SDK. I want those scripts to access the user space to modify the HKCU registry.

**Comment by qiaozha** [comment]
I see. I am not an expert about this but I think you probably need to install a VM extension to help you to do that.
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/dsc-overview

**Comment by philippemnoel** [comment]
I don't think this is the case. This extension does not seem to be related to what I need help with.

Is there no way to specify a user to run the script as from the python SDK?

**Comment by qiaozha** [comment]
I mean by use of DSC VM extension you can configure the credential of the powershell. https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/dsc-credentials 
https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/registryresource?view=powershell-7
Then you can use Python SDK to run the command as previous.

**Comment by qiaozha** [comment]
Add Service Team for more details about this.

**Comment by Drewm3** [comment]
@philippemnoel, could you let us know if using the suggested DSC Extension resolved your question?

**Comment by philippemnoel** [comment]
It did not. We had to setup WinRM via azure VM template and use remote-powershell
