### ISSUE TITLE
Using get_client_from_cli_profile and AzureAppConfigurationClient fails

### ISSUE THREAD

**Issue by marcin-vt** [Azure/azure-sdk-for-python#11119]
- **Package Name**:  azure-appconfiguration
- **Package Version**:  1.0.0
- **Operating System**: Ubuntu 16.04.6 LTS
- **Python Version**:  3.6.9

**Describe the bug**
Using azure.common.client_factory.get_client_from_cli_profile throws azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Forbidden'. 
Full log here: [debug.log](https://github.com/Azure/azure-sdk-for-python/files/4551258/debug.log)

**To Reproduce**
```
from azure.common.client_factory import get_client_from_cli_profile
from azure.appconfiguration import AzureAppConfigurationClient
connection_str = "https://XXXX.azconfig.io"
cfg_client = get_client_from_cli_profile(AzureAppConfigurationClient, base_url=connection_str)
cfg1 = cfg_client.get_configuration_setting(key="config1", label="label1")
```

**Expected behavior**
The az cli user has the permissions to access this config - command below gives correct results. 
```
az appconfig kv show --key config1 --label label1 --name XXXX -o table 
Command group 'appconfig' is in preview. It may be changed/removed in a future release.
CONTENT TYPE    KEY      VALUE    LAST MODIFIED         TAGS    LABEL    LOCKED
--------------  -------  -------  --------------------  ------  -------  --------
                config1  val1     2020-04-29T10:46:31Z  {}      label1   False
```

**Additional context**
I am able to read the config, form python code, using service principal (DefaultAzureCredential or ClientSecretCredential)

**Comment by chlowell** [comment]
Thanks for opening this issue. `azure.common.client_factory` is capable of building only clients from management libraries, that is to say `azure-mgmt-*`. It can't construct an `AzureAppConfigurationClient`.

As you've noted, you can construct `AzureAppConfigurationClient` directly with a credential type from `azure-identity`. If you want to authenticate with the identity signed in to the CLI, `DefaultAzureCredential` can do that in the current preview version of `azure-identity` (1.4.0b2 as I write this). Your code would look like this:

```py
from azure.identity import DefaultAzureCredential
from azure.appconfiguration import AzureAppConfigurationClient

base_url = "https://XXXX.azconfig.io"
credential = DefaultAzureCredential()
cfg_client = AzureAppConfigurationClient(base_url, credential)
cfg1 = cfg_client.get_configuration_setting(key="config1", label="label1")
```

**Comment by marcin-vt** [comment]
Thanks for prompt response @chlowell.

I was using client factory also for other libraries (e.g. azure.keyvault.secrets.SecretClient), but anyhow this is just for development and your solution is even better.

Thank you - will close the issue.
