### ISSUE TITLE
Disk Size not returning for Snapshot Get Operation

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1112]
Hi,

When I get snapshot using azure python sdk, disk_size_gb returning None.

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS 

Thank you for your report, I will test that asap.

**Comment by lmazuel** [comment]
This is actually a duplicate of this issue https://github.com/Azure/azure-sdk-for-python/issues/672
This field is only filled if you have filled it yourself at first.
Thank you.
