### ISSUE TITLE
[form recognizer] Make API consistent across languages (FormRecognizerClient)

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#11130]
- [ ] remove `page_number` from `FormField`
- [ ] `PageRange` -> `FormPageRange`
- [ ] consider un-flattening `RecognizedForm` properties on `USReceipt`, add a recognized form property on `USReceipt`  **did not like how hard it is to access fields and page_range from un-flattening. will seek guidance from architect if okay to keep flattened**

**Comment by kristapratico** [comment]
Some of the work done in this commit: https://github.com/Azure/azure-sdk-for-python/pull/11232/commits/8c64688060a256c09d1d726ba61a625955e848a0

However, this commit also has work that we don't want - like the rename of url and stream parameters.
