### ISSUE TITLE
[textanalytics] Throw exception on service warning about data limits

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#11140]
Teams thread [here](https://teams.microsoft.com/l/message/19:d6ff4003f5c848a2a2d6dcdfc0ebd497@thread.skype/1588101934413?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1588101934413&teamName=Azure%20SDK&channelName=Service%20-%20Text%20Analytics&createdTime=1588101934413).

Service will eventually return a 400 for this, but we should raise an exception now so it doesn't become a breaking change in the future (an exception thrown where there wasn't one before).

**Comment by iscai-msft** [comment]
merged into feature branch
