### ISSUE TITLE
signalr - regenerate_key crashes

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-sdk-for-python#11148]
Calling:

result = self.mgmt_client.signal_r.regenerate_key(resource_group_name=RESOURCE_GROUP, resource_name=RESOURCE_NAME, key_type="Primary")

causes following crash:

self = <msrestazure.polling.arm_polling.ARMPolling object at 0x7fab298e7b00>, client = <msrest.service_client.ServiceClient object at 0x7fab2a015ac8>, initial_response = <Response [201]>
deserialization_callback = <function SignalROperations.regenerate_key.<locals>.get_long_running_output at 0x7fab298d5d08>

    def initialize(self, client, initial_response, deserialization_callback):
        """Set the initial status of this LRO.

        :param initial_response: The initial response of the poller
        :raises: CloudError if initial status is incorrect LRO state
        """
        self._client = client
        self._response = initial_response
        self._operation = LongRunningOperation(initial_response, deserialization_callback, self._lro_options)
        try:
            self._operation.set_initial_status(initial_response)
        except BadStatus:
            self._operation.status = 'Failed'
>           raise CloudError(initial_response)
E           msrestazure.azure_exceptions.CloudError: <Response [201]>

/env/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py:381: CloudError
-------------------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------------------
connectionpool.py          662 WARNING  Retrying (Retry(total=3, connect=4, read=3, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))': /subscriptions/.../resourcegroups/test_cli_mgmt_signalr_test_signalrf5150df8?api-version=2019-08-01

**Comment by allenjzhang** [comment]
Added mgmt label.

**Comment by changlong-liu** [comment]
from the error description, it should be a service issue. And we don't meet customer complain for it.
