### ISSUE TITLE
Unable to create a Key Vault with soft delete disabled

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#11159]
- **Package Name**: azure-mgmt-keyvault
- **Package Version**: 2.2.0

**Describe the bug**
It seems that Key Vault now considers it an error to create a vault with a value for `softDeleteRetentionInDays` but soft delete itself disabled.

In the management library, `VaultProperties` has a [default int value for softDeleteRetentionInDays](https://github.com/Azure/azure-sdk-for-python/blob/c815f5757f7d6d08ebd394cf4a43f42b304f37f3/sdk/keyvault/azure-mgmt-keyvault/azure/mgmt/keyvault/v2019_09_01/models/_models.py#L1100). This attribute therefore always has a value in a serialized `VaultProperties`, and creating a vault with soft delete disabled requires specifying `soft_delete_retention_in_days=None`.

**To Reproduce**
```py
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.keyvault import KeyVaultManagementClient
from azure.mgmt.keyvault.models import (
    Sku,
    SkuName,
    VaultProperties,
    VaultCreateOrUpdateParameters,
)

credentials = ServicePrincipalCredentials(client_id=CLIENT_ID, secret=CLIENT_SECRET, tenant=TENANT_ID)

properties = VaultProperties(
    tenant_id=TENANT_ID,
    sku=Sku(name=SkuName.standard.value),
    access_policies=[],
    enable_soft_delete=False,
)
parameters = VaultCreateOrUpdateParameters(location='westus2', properties=properties)
client = KeyVaultManagementClient(credentials, SUBSCRIPTION_ID)
vault = client.vaults.create_or_update(RESOURCE_GROUP, VAULT_NAME, parameters).result()
```
Gets you:
```
msrestazure.azure_exceptions.CloudError: Azure Error: BadRequest
Message: The property "enableSoftDelete" must be set to true.
```

**Comment by jlichwa** [comment]
We had a defect. That issue should be fixed right now. @chlowell  can you try again?

**Comment by chlowell** [comment]
Thank you, I see it's been fixed.
