### ISSUE TITLE
Please release a new version of azure-servicemanagement-legacy

### ISSUE THREAD

**Issue by codyshepherd** [Azure/azure-sdk-for-python#11163]
- **Package Name**: azure-servicemanagement-legacy
- **Package Version**: 0.20.6
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8

**Describe the bug**
0.20.6 of azure-servicemanagement-legacy in pypi contains code that uses the reserved keyword `async`. This has been fixed in recent versions of this repository, but the pypi package has not been updated, and is thus unusable with Python >= 3.7.

**To Reproduce**

1. Use python >= 3.7
2. pip install, import azure-servicemanagement-legacy
3. observe SyntaxError from use of reserved word `async` in azure/servicemanagement/servicemanagementclient.py (since fixed in this repo)

**Expected behavior**
The code that currently [exists in this repo](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementclient.py) should be released in pypi as a new version of the azure-servicemanagement-legacy python package. 

**Additional context**
This will enable users of Python >= 3.7 (e.g. anyone on Ubuntu 20.04, which uses 3.8 by default) to use the package.

**Comment by kaerm** [comment]
Thanks @codyshepherd for reporting this, @nickzhums @RodgeFu can you take a look at this

**Comment by RodgeFu** [comment]
The last SDK release is 3 years ago, add "service attention" label to involve service team to confirm whether their swagger is ready to release the new version Python SDK. thanks.

**Comment by lmazuel** [comment]
@RodgeFu this SDK is not really owned by a service team, this is the ASM old endpoint (before ARM). I indeed fixed some async keyword, but I thought it was impacting tests only, I will do pass to assess what's broken.
Being the deprecation of that SDK and the focus on ARM now, I don't think it worth me passing too much on passing the context, I will try to fix it myself for customer's sake. Please ping me if you have question

**Comment by lmazuel** [comment]
Exact stacktrace:
```python
>>> from azure.servicemanagement import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lmazuel\Documents\GitHub\asmtest\lib\site-packages\azure\servicemanagement\__init__.py", line 27, in <module>
    from .servicemanagementclient import parse_response_for_async_op
  File "C:\Users\lmazuel\Documents\GitHub\asmtest\lib\site-packages\azure\servicemanagement\servicemanagementclient.py", line 372
    def _perform_put(self, path, body, async=False, x_ms_version=None):
                                       ^
SyntaxError: invalid syntax
```

**Comment by lmazuel** [comment]
Released: https://pypi.org/project/azure-servicemanagement-legacy/0.20.7/
