### ISSUE TITLE
Rename Disk or Snapshot in Azure

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1117]
Hi 

Is there any possibility of renaming Disk and snapshot names in azure using python sdk.

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS 

I think it's not supported by the service (not even a Python question). Renaming in ARM is rare. You can move it to another subscription or resourcegroup, but not rename the resource itself.
