### ISSUE TITLE
Doc of how to adjust op status polling interval

### ISSUE THREAD

**Issue by arsenvlad** [Azure/azure-sdk-for-python#1120]
Is there a document and example showing how to control the interval at which Azure Python SDK polls operations for completion? For example, creation of managed disk should take only a few seconds, but when waiting for the Azure Python SDK to complete it appears to take 30 seconds (likely due to polling interval being ~30 seconds). It would be great to be able to adjust the poll interval to decrease the overall run-time of the operation.

**Comment by lmazuel** [comment]
Thank you @arsenvlad for the issue :). I will do my best to document this asap.

**Comment by lmazuel** [comment]
@Petermarcu no, I don't think it was ever documented. Cross package documentation (i.e. poller behavior is the same whatever the package) is always something we were missing. We have only a few of that type of doc:
https://docs.microsoft.com/azure/python/python-sdk-azure-operation-config
https://docs.microsoft.com/azure/python/python-sdk-azure-multi-cloud

We definitely need a generic doc on "You have poller, here's how to use it, whatever package gave you that poller"

**Comment by lmazuel** [comment]
@arsenvlad I can answer your question still in the meantime:
If Azure returns a `retry-after` header, the poller will always follow it. Bypass it is possible, but will require that you subclass [ArmPolling](https://github.com/Azure/msrestazure-for-python/blob/0a07586816351e3b7abd60a55a8b736e007fb7a8/msrestazure/polling/arm_polling.py#L340) and change the behavior of delay.
If Azure doesn't return a `retry-after`, then you can change it using:
```python
# Will wait 10 sec and not 30 assuming no retry-after is here
client.config.long_running_operation_timeout = 10
```

**Comment by lmazuel** [comment]
Creating an autorest issue for track2 ref doc, closing this issue then:
https://github.com/Azure/autorest.python/issues/570
