### ISSUE TITLE
How to unpack detect_with_stream

### ISSUE THREAD

**Issue by Kalaschnik** [Azure/azure-sdk-for-python#11202]
How can I print the contents of my response from `detect_with_stream`, in this case the `emotion` attribute?
```
detected_faces_details = face_client.face.detect_with_stream(
  open((os.path.join("img/test-faces.jpg")),'r+b'),
  return_face_attributes=['emotion'])
```
`detected_faces_details` is only printing my two faces in `test-faces.jpg` in this manner:
```
[<azure.cognitiveservices.vision.face.models._models_py3.DetectedFace at 0x1e20ec06648>,
 <azure.cognitiveservices.vision.face.models._models_py3.DetectedFace at 0x1e20ec063c8>]
```

**Comment by kristapratico** [comment]
Hi @Kalaschnik 

`detect_with_stream` is returning a list of `DetectedFace` objects. Here is [documentation](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-cognitiveservices-vision-face/0.4.0/azure.cognitiveservices.vision.face.models.html#azure.cognitiveservices.vision.face.models.DetectedFace) that shows what a `DetectedFace` looks like.

If you want to print the `emotion` attribute for each face you can do this:
```
for face in detected_faces_details:
    print(face.face_attributes.emotion.anger)  # printing confidence value for anger, for example
```

[Here](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-cognitiveservices-vision-face/0.4.0/azure.cognitiveservices.vision.face.models.html#azure.cognitiveservices.vision.face.models.Emotion) are the available attributes found on the `emotion` object.

Let me know if this helps or if I misunderstood your question.

**Comment by Kalaschnik** [comment]
Hey @kristapratico 

thank you for the syntax example, I was desperately looking for it 🙂
I was also not aware of this particular documentation site. I was digging through the docs [here](https://docs.microsoft.com/en-us/azure/cognitive-services/face/quickstarts/client-libraries?tabs=windows&pivots=programming-language-python) and [here](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-face/?view=azure-python) without finding examples for my case.

Anyway, the docs you posted look more fun to read than the others, although it lacks examples (like the one you give to me)—maybe it would be good add some examples?

Thanks!
