### ISSUE TITLE
how to get worker id of app service plan

### ISSUE THREAD

**Issue by nohyunho** [Azure/azure-sdk-for-python#1122]
I'm using "azure-mgmt-web 0.32.0".
How can I get the worker pool id of an app service plan?
I cannot find the worker pool id attribute which is associated with an app service plan when I use the following function.
`
web_client = WebSiteManagementClient(credentials, subscription_id)
`
`
plan = web_client.app_service_plans.get(resource_group_name, app_service_plan_name)
`

**Comment by lmazuel** [comment]
Hi @nohyunho 

@yugangw-msft , do you know?

**Comment by nohyunho** [comment]
Hi, 
"App Service Plan"(from web_client.app_service_plans.get) has "worker_tier_name" attribute. 
Azure SDK for Python Documentation explains for it as follows.
- worker_tier_name (str) – Target worker tier assigned to the App Service plan.

I think that attribute is the worker pool id, but it has no value.(I have checked it using python code)
Is there another method for getting the worker pool id or is it bug?
Thanks for your kindness in advance.
yunho

**Comment by nohyunho** [comment]
Hi @lmazuel, @yugangw-msft 
Please, could you answer my question?

**Comment by lmazuel** [comment]
@naveedaz, I think it's more a RestAPI question than a Python, can you tell us where to find this info in the Swagger file? (and we can translate to Python). Thanks!

**Comment by nohyunho** [comment]
Hi,
In Azure Portal, app service plan has "WorkerSizeId" attribute which means worker pool id.(I checked it using chrome devtools.) But, python SDK doesn't provide that information.
Could you check it ASAP?
Thanks.

**Comment by lmazuel** [comment]
Hi @nohyunho 
I just created an issue in the RestAPI repo:
https://github.com/Azure/azure-rest-api-specs/issues/1241

This will help to understand where is the issue.

**Comment by xiangyan99** [comment]
@nohyunho  Given the latest azure-mgmt-web is 6.1.0. Could you help to check if this is solved?
