### ISSUE TITLE
Running PowerShell on Windows VM via a Webserver using Python SDK, authenticated as a specific user

### ISSUE THREAD

**Issue by philippemnoel** [Azure/azure-sdk-for-python#11224]
I am currently running PowerShell on an Azure VM using the Python SDK. The python script gets run by a webserver. However, currently, I am running it without being authenticated as a user, which prevents me from running certain user-space scripts.

How can I run powershell from the azure Python SDK, but authenticated as a specific user?

Thank you for your help!

Philippe

**Comment by lmazuel** [comment]
It's a complex question, the easiest would be to use managed identities:
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

Would that fit your need?

**Comment by philippemnoel** [comment]
Thanks for replying -- I don't think that's what I want. I'm looking for something I can either run directly from the SDK, or via windows powershell directly from a windows client.

**Comment by RodgeFu** [comment]
How about using windows task scheduler? you can configure a windows schedule task and configure a credential there. thx

**Comment by philippemnoel** [comment]
I don't think that will work, I need to be able to call the script programmatically.

**Comment by RodgeFu** [comment]
i mean pre-create the scheduled task in windows with the account, and then trigger the scheduled task programmatically which will in-turn trigger your script in scheduled task with the account you need.
https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/start-scheduledtask?view=winserver2012r2-ps&redirectedfrom=MSDN

**Comment by philippemnoel** [comment]
Oh interesting -- I'll take a look, thanks!
