### ISSUE TITLE
[formrecognizer] FormTrainingClient differences

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#11230]
- [x] `training_files` -> `training_files_url`
- [x] Change `use_labels` -> `use_training_labels`
- [ ] maybe change `models` property name in `CustomFormModel`, opened an issue here: https://github.com/Azure/azure-sdk-for-python/issues/11389, won't be addressing this issue in here anymore
- [x] Rename `list_model_infos` -> `list_custom_models`

**Comment by kristapratico** [comment]
Some of this work was already done in this draft PR: https://github.com/Azure/azure-sdk-for-python/pull/11232/commits/3640d3a20523c85b655338bb37f4ed1fa6c90693
