### ISSUE TITLE
Integration testing msal

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#11247]
We need to regularly test our master branch against msal's development branch to catch breaks before release. Practically this means pip installing git+https://github.com/AzureAD/microsoft-authentication-library-for-python@dev instead of, or atop, the requirement in azure-identity's setup.py, and running the test suite as usual. Such a test should fail today because the msal dev branch has a breaking change for azure-identity.

**Comment by kurtzeborn** [comment]
@chlowell, how do you envision this being integrated.  If we set up a separate pipeline, it seems like it'll become something that is ignored.  Another option is to add it to a leg in our current test matrix, but (as you say) it should be failing right now, and we want all faitures in our current test matrix to be investigated immediately.  The goal is to keep those green.  So we want to be careful about adding it in such a way that we don't make it "normal" for the test runs to fail.  Perhaps we add a leg to the test matrix, but ignore failures?  Who would be watching the runs to make sure we catch these?

**Comment by chlowell** [comment]
I'm happy with any approach that runs nightly and nets me an email when it fails. Failure won't be the norm. The break in MSAL is now fixed on their dev branch, and #11307 fixes our only remaining test bug.

**Comment by praveenkuttappan** [comment]
Reopened this issue to restructure test and add it as additional test matrix in CI pipeline
