### ISSUE TITLE
[Service Bus] Change management request and settlement error handling to raise specific errors

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#11255]
**Is your feature request related to a problem? Please describe.**
The APIs (Receiver's `receive_deferred_messages`, `peek`, Sender's `schedule`, `cancel_scheduled_messages`, ReceivedMessage's `complete`, `dead_leter`, `abandon`, `defer`, etc) that internally use management request and always raise `ServiceBusError` if an error happened when talking to the ServiceBus server.
Similarly `ReceivedMessage.complete()` raises `MessageSettlementError` .They might be able to raise more specific error types.

**Describe the solution you'd like**
Break down to detailed errors depending on the different errors raised from the underlying uamqp management call.

**Describe alternatives you've considered**
If no specific errors from uamqp management request, then it's difficult to have specific errors in ServiceBus for management requests. The current design is good.

**Additional context**

EDIT AS OF 8/11:
3 steps to this process.
1. Enumerate custom validation and exception scenarios cross-language. (COMPLETE)
2. Assess our current behavior and document it (IN PROGRESS)
3. Align with other SDKs.

**Comment by KieranBrantnerMagee** [comment]
As a note: This may rely on decisions that we make as part of Yannis "chart out all exceptions and how we want them to pan out" investigation.  Moving this to september sprint accordingly but feel free to pull forward if that discussion ended up happening with enough leeway to get this done.

**Comment by KieranBrantnerMagee** [comment]
This task has overlapped a bit between the "need to align in terms of consistency of exceptions" and "let's fix some clear-cut exception failures."  

Let's keep this task oriented towards the former, (the chart of exception/validation cases) and create fine-grained issues for the well defined bits that we've settled on.  In the interest of that, I'll split out my addendum about vendorlinkdetatch into the separate thread. (https://github.com/Azure/azure-sdk-for-python/issues/13040)

**Comment by KieranBrantnerMagee** [comment]
Brief update; [item in PR](https://github.com/Azure/azure-sdk-for-python/pull/14178), working through some considerations, bumping to oct sprint due to high urgency UAMQP work and the relative risk/ROI of pushing this in without completing evaluation.
