### ISSUE TITLE
Find resource methods based an a filter criteria.

### ISSUE THREAD

**Issue by madhukargilla** [Azure/azure-sdk-for-python#1127]
Hi,

The current SDK does not provide any methods to Find a resource based on a filter criteria (name, id...etc), something similar to the list containers which has the prefix parameter,  it would be great if we can add this, as most of the other cloud providers support this. 

Thanks -Madhu

**Comment by lmazuel** [comment]
Hi @madhukargilla 

The "azure-mgmt-resource" package has a [`list` operation with a "filter" parameter](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.resource.resources.v2016_09_01.operations.html#azure.mgmt.resource.resources.v2016_09_01.operations.ResourcesOperations.list). Is it what you are looking for?

Thanks,

**Comment by madhukargilla** [comment]
can you please point us to the unit test or a example on the usage ?

Thank you.

**Comment by luanshixia** [comment]
Hi @madhukargilla ,

There is a limitation in the underlying Azure Resource Manager resource query API. This API won't return any private properties of the resources (i.e. what are in the `properties` property). Thus, the `$expand` OData query parameter won't be able to expand it. The `$expand` parameter can only be used on `changedTime`, `createdTime`, and `provisioningState` in this API.

To get the `properties`, you will have to call `GET` on individual resources.
