### ISSUE TITLE
Investigate perf improvement by not importing "requests" when no HTTP use planned

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#11276]
For instance "import azure.core.exceptions" (CLI)

PS: Same apply for aiohttp if the env has it

This is issue is about _**requests is installed and we should not import it if not necessary.**_

**Comment by lmazuel** [comment]
Actually this issue is also true for situation where we have a custom transport and requests is not available, renaming the issue to a more generic problem.

**Comment by xiangyan99** [comment]
#25344
