### ISSUE TITLE
Monitoring examples are outdated

### ISSUE THREAD

**Issue by estensen** [Azure/azure-sdk-for-python#11271]
- **Package Name**: azure-mgmt-monitor
- **Package Version**: 0.9.0
- **Operating System**: macOS
- **Python Version**: 3.8.1

**Describe the bug**
[Azure Monitoring libraries for python](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/monitoring.md) are outdated and doesn't work with the new alerts.

Is this going to be fixed or is it possible to label examples like this as deprecated/outdated so people don't have to spend time working with examples that don't work?

Tried to open an [issue](https://github.com/MicrosoftDocs/azure-docs-sdk-python/issues/614) in `azure-docs-sdk-python`, but was redirected here

**Comment by RodgeFu** [comment]
Assign to Nick for the doc issue

**Comment by nickzhums** [comment]
Will add this to doc work backlog

**Comment by nickzhums** [comment]
@estensen could you give a bit more details on this?

**Comment by estensen** [comment]
@nickzhums have you tried running the examples I've linked?

The problem is that this example creates the legacy (classic) alerts which you are not allowed to do anymore.

Some things that are broken:
- You have to use `client.metric_alerts.create_or_update` instead of `client.alert_rules.create_or_update`
- `location` has to be `global`
- `alert_rule_resource_name` is renamed

**Comment by nickzhums** [comment]
@estensen thanks, will look into this

**Comment by mukulgupta2138** [comment]
Hey @nickzhums, @RodgeFu  any update on this ?

Hey @estensen, Can you please share the example that worked for you ? I'm trying to use this but not able to get any help around this :(

**Comment by nickzhums** [comment]
Hi @mukulgupta2138  have you checked this repo?

https://github.com/Azure-Samples/azure-samples-python-management/

**Comment by mukulgupta2138** [comment]
Hi @nickzhums , thanks for the revert. I'm trying to set up action group action rule and there is no sample example which I can find which can help in setting up these. Can you share some code pointers (if any) for same ?

**Comment by nickzhums** [comment]
@00Kai0 do you know if we have samples for this case?
