### ISSUE TITLE
Update IotHub Quickstart sample to use latest Event Hubs SDK

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#11289]
https://github.com/Azure-Samples/azure-iot-samples-python is the Python samples repo for IotHub. The [read-d2c-messages](https://github.com/Azure-Samples/azure-iot-samples-python/tree/master/iot-hub/Quickstarts/read-d2c-messages) folder is meant to contain sample that shows how to use the Event Hubs package to get events sent to IotHub.

Previously, this contained a link to the older event hub repo whose sample code would not work with the latest event hubs package and thus confusing users. I fixed that with https://github.com/Azure-Samples/azure-iot-samples-python/pull/23 as a temporary stop gap to avoid users from being mislead.

This issue is to track the follow up work needed to update the samples repo with a real sample just like we did for node in https://github.com/Azure-Samples/azure-iot-samples-node/pull/39

Please try and follow a similar model i.e
- The sample should use Event Hubs compatible connection string
- The sample should also show how to use websockets and proxy support, but should be commented out
- The readme should talk about how to form the  Event Hubs compatible connection string, the back up option to use our IotHub to EH compatible conversion sample, checkpointing and websocket/proxy support

**Comment by YijunXieMS** [comment]
It's merged
