### ISSUE TITLE
 storage account failover complains about LastSyncTimeUnavailable

### ISSUE THREAD

**Issue by qiaozha** [Azure/azure-sdk-for-python#11292]
- **Package Name**: azure-mgmt-storage
- **Package Version**: 9.0.0
- **Operating System**:
- **Python Version**: 

**Describe the bug**
I am trying to fix the test https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-mgmt-storage/tests/test_cli_mgmt_storage.py for azure-mgmt-storage Python SDK and found that if I didn't comment out the test for failover https://github.com/Azure/azure-sdk-for-python/pull/11018/files#diff-d17221e9561b5e8578495ccace549e0dR703 to run live test against the service, the Test will fail and complains about LastSyncTimeUnavailable

Does the LastSyncTimeUnavailable means different replicate zones sync up time? 
Am I missing some kind of configurations to make failover work?

**To Reproduce**
1. checkout the PR and uncomment the failover 
2. setup your python sdk enviroment 
2. run pytest -s sdk/storage/azure-mgmt-storage

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55688292/81272680-600e8780-9080-11ea-82f4-43fc915a9073.png)

![image](https://user-images.githubusercontent.com/55688292/81273052-ea56eb80-9080-11ea-8b7d-b5f287331fef.png)

**Additional context**

**Comment by blueww** [comment]
We have discussed offline.
This is related with server issue, and has include feature team to the discussion.
Will update if get any conclusion.

**Comment by qiaozha** [comment]
@zfchen95  Seems I can't assign you.
