### ISSUE TITLE
Handle selected properties for List operations

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#11320]
For list operations (e.g. listDataSources) do not expose a parameter that allows the customer to pass `$select`. Many properties of models can't be in a `$select`, and they are case sensitive which may not be intuitive to languages that use typed models with different property casing.

Instead, provide a separate method for getting just names (e.g. listDataSourceNames), which the server optimizes. These methods should return a collection of strings.

**Comment by xiangyan99** [comment]
Fixed in #11739
