### ISSUE TITLE
How can I get 5 message from queue?

### ISSUE THREAD

**Issue by timewalker08** [Azure/azure-sdk-for-python#11332]
I find that there is no means to get specified count of message from queue by azrure sdk for python.
There are such API for C# sdk:
`GetMessagesAsync(Int32, Nullable<TimeSpan>, QueueRequestOptions, OperationContext)`

How can I achieve the same behavior in Python?

Thanks

**Comment by KieranBrantnerMagee** [comment]
Hey timewalker,
Assuming you're on a 0.50.* version, what you want is `fetch_next`.
please find some breadcrumbs in both our [samples](https://github.com/Azure/azure-sdk-for-python/blob/300d00e56a80711230902fcd285e347ac0de121b/sdk/servicebus/azure-servicebus/samples/sync_samples/example_queue_send_receive_batch.py#L32) and in our [official docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-queues#receive-messages-from-a-queue)

The one pitfall with using this is that if 5 messages are not available, it will return whatever is in the queue up to 5.  If none are available, it will wait until idle_timeout, immediately returning with any messages if they arrive, even if less than 5 are present.

A final note to future-proof this comment: I'd be remiss to not mention the 0.50.* versions are entering end-of-life, and a GA version, 7.0.0, is currently in preview (b2), in which `fetch_next` will simply be called `receive`, although the semantics will stay the same.

As always don't hesitate to reopen this/reach out if any clarification or further questions are needed.
