### ISSUE TITLE
azureml.core.model.Mode.deploy: "Exactly one of the ModelIds or Models must be specified for a service" when it used to work.

### ISSUE THREAD

**Issue by claverru** [Azure/azure-sdk-for-python#11331]
- **azureml-core**: 
- **1.4**: 
- **Ubuntu 18.04 bionic**:
- **Python 3.6.9**: 

**Describe the bug**
WebserviceException when calling **azureml.core.model.Mode.deploy** with: 

"code":"ServiceModelConflict",
"message":"Exactly one of the ModelIds or Models must be specified for a service." 

It used to work before with the exact same environment (versions, OS, etc). Also, it's always been explicitily specified in docs:

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model?view=azure-ml-py#deploy-workspace--name--models--inference-config-none--deployment-config-none--deployment-target-none--overwrite-false-

models: list[Model]. A list of model objects. Can be an empty list.

**To Reproduce**
1. Probably trying to deploy with an empty list as argument of *models* in deploy method.

**Expected behavior**
ACI Service deployed as usual.

**Comment by brandonwatts** [comment]
I'm seeing the same issue. Believe [other people](https://github.com/Azure/azure-cli-extensions/issues/1645) are too. 

```python
Response Code: 400
Headers: {'Date': 'Fri, 08 May 2020 13:58:17 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:2d2e8e63-272e-4b3c-8598-4ee570a0e70d', 'x-ms-client-request-id': '6049853aef8b4e8ca8f4e1965aad051d', 'x-ms-client-session-id': 'e5a785f3-b5a5-40a0-8fd3-5cdfb47b2c79', 'api-supported-versions': '1.0, 2018-03-01-preview, 2018-11-19', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"BadRequest","statusCode":400,"message":"The request is invalid.","details":[{"code":"ServiceModelConflict","message":"Exactly one of the ModelIds or Models must be specified for a service."}],"correlation":{"RequestId":"6049853aef8b4e8ca8f4e1965aad051d"}}'
        InnerException None
        ErrorResponse 
{
    "error": {
        "message": "Received bad response from service:\nResponse Code: 400\nHeaders: {'Date': 'Fri, 08 May 2020 13:58:17 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:2d2e8e63-272e-4b3c-8598-4ee570a0e70d', 'x-ms-client-request-id': '6049853aef8b4e8ca8f4e1965aad051d', 'x-ms-client-session-id': 'e5a785f3-b5a5-40a0-8fd3-5cdfb47b2c79', 'api-supported-versions': '1.0, 2018-03-01-preview, 2018-11-19', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}\nContent: b'{\"code\":\"BadRequest\",\"statusCode\":400,\"message\":\"The request is invalid.\",\"details\":[{\"code\":\"ServiceModelConflict\",\"message\":\"Exactly one of the ModelIds or Models must be specified for a service.\"}],\"correlation\":{\"RequestId\":\"6049853aef8b4e8ca8f4e1965aad051d\"}}'"
    }
}
```

**Comment by keerthiadu** [comment]
this is a regression and we are working on hotfix.

**Comment by trojrobert** [comment]
I can't deploy on LocalWebservice too. Is this the same issue?

ERROR - Service deployment polling reached non-successful terminal state, current service state: Unhealthy
Operation ID: 2ce5b8cc-489b-4201-a896-ede97d6c329b
More information can be found using '.get_logs()'
Error:
{
  "code": "DeploymentTimedOut",
  "statusCode": 504,
  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."
}

**Comment by mkrdip** [comment]
@keerthiadu the hotfix fixed the issue. I can deploy locally now!

**Comment by keerthiadu** [comment]
> this is a regression and we are working on hotfix.

Hotfix deployed to all regions.
