### ISSUE TITLE
azure-storage-file-datalake Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#11358]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/README.md#create-a-storage-account):
![image](https://user-images.githubusercontent.com/57166602/81468225-cde9b900-9210-11ea-925f-fdf8c6d295ec.png)

Reason:
All three correspond to the same link 'Azure Portal'. 

Suggestion:
Update these link: 
Azure Portal: https://docs.microsoft.com/azure/storage/common/storage-quickstart-create-account?tabs=azure-portal, 
Azure PowerShell: https://docs.microsoft.com/azure/storage/common/storage-quickstart-create-account?tabs=azure-powershell, 
Azure CLI: https://docs.microsoft.com/azure/storage/common/storage-quickstart-create-account?tabs=azure-cli
2.
Section [Link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/README.md#create-a-storage-account):
![image](https://user-images.githubusercontent.com/57166602/81468377-c70f7600-9211-11ea-87eb-bd816a036e34.png)

Reason:
az: error: unrecognized arguments: --hierarchical-namespace true

Suggestion:
```
# Install the extension “Storage-Preview”
az extension add --name storage-preview
# Create the storage account
az storage account create -n my-storage-account-name -g my-resource-group --sku Standard_LRS --kind StorageV2 --hierarchical-namespace true
```

**Comment by v-xuto** [comment]
@jongio please review.

**Comment by mayurid** [comment]
@xiafu-msft and @amishra-dev  to help triage

**Comment by jongio** [comment]
According to this, https://github.com/MicrosoftDocs/azure-docs/issues/24481, it looks like a CLI extension is required.

**Comment by v-xuto** [comment]
@jongio,  Thank you for your advice. I've updated it.

**Comment by v-xuto** [comment]
PR merged.
