### ISSUE TITLE
azure-storage-blob Readme and Samples Issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#11357]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob#examples ):
![image](https://user-images.githubusercontent.com/57166602/81467796-ad6c2f80-920d-11ea-816d-ca349e7499a7.png)

Suggestion:
Missing title "create a container" in examples summary. 
2.
Section [link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/samples/blob_samples_common.py#L143 ):
![image](https://user-images.githubusercontent.com/57166602/81467907-6c284f80-920e-11ea-8412-5bfe7d470578.png)
![image](https://user-images.githubusercontent.com/57166602/81467849-0d62d600-920e-11ea-88e8-153064b62cd9.png)

Suggestion:
The container name we should delete is "containerforbatchblobdelete", not 'containerforbatchblobdeletesasync'.

**Comment by v-xuto** [comment]
@jongio please review.

**Comment by mayurid** [comment]
@xiafu-msft and @amishra-dev to help traige

**Comment by xiafu-msft** [comment]
Hi @v-xuto 

Thanks for catching this and the pr! It looks good to me!

**Comment by xiafu-msft** [comment]
I'm gonna close this issue for now since you've helped fix it ^_^ We can reopen it if you have any concern! Thanks again
