### ISSUE TITLE
Experiment name length limit

### ISSUE THREAD

**Issue by RoozbehBandpey** [Azure/azure-sdk-for-python#11368]
- **Package Name**: azureml.core
- **Package Version**: 1.1.5
- **Operating System**: Windows 10 64-bit
- **Python Version**:  3.7.3 64-bit

While trying to fetch runs for experiments which have names longer that 36 character, the SDK returns this:
```powershell
azureml.exceptions._azureml_exception.UserErrorException: UserErrorException:
        Message: Experiment name must be between 1 and 36 characters long. Its first character has to be alphanumeric, and the rest may contain hyphens and underscores. No whitespace is allowed.
        InnerException None
        ErrorResponse
{
    "error": {
        "code": "UserError",
        "message": "Experiment name must be between 1 and 36 characters long. Its first character has to be alphanumeric, and the rest may contain hyphens and underscores. No whitespace is allowed."
    }
}
```
While still it is possible to submit experiments with names longer than 36 chars via AML pipeline
**How to handle metrics for those experiments?**

**Comment by lostmygithubaccount** [comment]
@RoozbehBandpey are you still facing this issue?

**Comment by swatig007** [comment]
closing due to no response
