### ISSUE TITLE
Ambiguity of definition of "endpoint" in portal and in  SDK

### ISSUE THREAD

**Issue by ludokriss** [Azure/azure-sdk-for-python#11363]
Hey,

Just to make it easier to use some of your libraries, you should probably make sure "Endpoint" means the same thing in the portal as it does in the SDK. For example, using the sdk for bing news cognitive services, copying the endpoint from the portal and adding it to the sdk config, will fail due to the sdk adding trailing version and resource see:

![image](https://user-images.githubusercontent.com/43015594/81499026-b8d06100-92c8-11ea-9d3b-1f9ca49b039c.png)

and the following snippet from the python sdk (may apply to other sdks as well, haven't checked):

https://github.com/Azure/azure-sdk-for-python/blob/7cedad5273f0b9fcedb70415f19afde8baebbeac/sdk/cognitiveservices/azure-cognitiveservices-search-newssearch/azure/cognitiveservices/search/newssearch/_configuration.py#L38

**Comment by lmazuel** [comment]
This is a fair feedback for the Swagger definition

**Comment by lmazuel** [comment]
Those SDKs are not supported anymore, and have been replaced by new ones. Bing is not a part of Azure nowadays, please address issues to https://github.com/microsoft/bing-search-sdk-for-python and consider using https://pypi.org/project/microsoft-bing-newssearch/ instead. Thanks, and sorry for the late answer.
