### ISSUE TITLE
API returns "bad request" -- package seems to be outdated

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-sdk-for-python#11376]
- **Package Name**:
azure-mgmt-mixedreality

- **Package Version**: 
0.1.0
- **Operating System**:
- **Python Version**: 

**Describe the bug**

Error when trying to create:

        if response.status_code not in [200, 201]:
>           raise models.ErrorResponseException(self._deserialize, response)
E           azure.mgmt.mixedreality.models.error_response_py3.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

**To Reproduce**
1. Try to create account:
AZURE_LOCATION = 'eastus'
ACCOUNT_NAME = "myaccountxxxxyabc"
        result = self.mgmt_client.spatial_anchors_accounts.create(resource_group_name=RESOURCE_GROUP, spatial_anchors_account_name=ACCOUNT_NAME, location=AZURE_LOCATION)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dw511214992** [comment]
Hi mixedreality team, the sdk is outdated. So we need to release a new sdk with current swagger in https://github.com/Azure/azure-rest-api-specs. I want to know whether the swagger is latest and ready for release. If yes, please create a release request to release it. Thank you

**Comment by xiangyan99** [comment]
azure-mgmt-mixedreality 1.0.0 was released in April, 2021.
