### ISSUE TITLE
Wrong type hint for azure.storage.queue.QueueClient.from_connection_string() -> None

### ISSUE THREAD

**Issue by alanjcastonguay** [Azure/azure-sdk-for-python#11392]
- **Package Name**: azure.storage.queue
- **Package Version**: 12.1.1
- **Operating System**: MacOS 10.15.4 (19E287)
- **Python Version**: 3.8.2

**Describe the bug**

This code implies that `azure.storage.queue.QueueClient.from_connection_string()` returns `None`:

https://github.com/Azure/azure-sdk-for-python/blob/ab4f3090be02dcedddf9969f565bf43670a10f7a/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L155-L161

In contrast, `azure.storage.blob.BlobClient.from_connection_string()` returns a `BlobClient`.

https://github.com/Azure/azure-sdk-for-python/blob/ab4f3090be02dcedddf9969f565bf43670a10f7a/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L235-L242

**To Reproduce**

1. In editor (eg PyCharm):
```
a = azure.storage.queue.QueueClient.from_connection_string()
a.<TAB>
```
2. Observe unhelpful autocomplete.
3. Add a comment `# type: QueueClient`
4. Get useful autocomplete
5. Now get `Expected type 'QueueClient', got 'None' instead ` complaint.

**Expected behavior**
Correct type declaration of QueueClient. Or, at the very least, not an incorrect & affirmative declared type of None.

**Comment by xiafu-msft** [comment]
Hi @alanjcastonguay 

Thanks for catching this, we will log this as a bug and fix it later!

**Comment by alanjcastonguay** [comment]
Shiny; thanks. 👍
