### ISSUE TITLE
Organize Generated Artifacts Into Per-Package folders

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#11397]
After building, the artifacts available to the rest of the build are organized like this:
![image](https://user-images.githubusercontent.com/45376673/81754981-5912bb00-946c-11ea-8549-a46a419b1773.png)

Which necessitates a pre-step when handling the artifacts during **release**.

```
Get-ChildItem $(Pipeline.Workspace)/${{parameters.ArtifactName}}
New-Item -Type Directory -Name ${{artifact.safeName}} -Path $(Pipeline.Workspace)
$underscorePrefix = "${{artifact.name}}"
$dashPrefix = "${{artifact.name}}".Replace("_", "-")
Copy-Item $(Pipeline.Workspace)/${{parameters.ArtifactName}}/$dashPrefix-[0-9]*.[0-9]*.[0-9]* $(Pipeline.Workspace)/${{artifact.safeName}}
Copy-Item $(Pipeline.Workspace)/${{parameters.ArtifactName}}/$underscorePrefix-[0-9]*.[0-9]*.[0-9]* $(Pipeline.Workspace)/${{artifact.safeName}}
```

This is useless duplicate work on the release side.

If we instead organize the artifacts like

```
artifactRoot/
   packages/
      {artifact.safeName}/<generated files>
```

This issue covers

- [ ] Add post-build step to organize the artifacts like above
- [ ] Update release steps to leverage the new artifact name

Edit, additional requirement from confusion breaking a release:
- [ ] Make certain artifactname can forgive `_` versus `-`. [This PR](https://github.com/Azure/azure-sdk-for-python/pull/11502) highlights why.

**Comment by weshaggard** [comment]
>Add post-build step to organize the artifacts like above

If possible we should do it as part of the packaging step itself and have the output going directly into a separate folder but if that isn't easy then we should do this reorganization as post-build step but during the build/package pipeline job. No need for us add another job to download, organize, and then re-upload.

**Comment by scbedd** [comment]
When I say `post-build` I mean `post-the-step-that-actually-builds`. It doesn't necessarily mean "download from artifact store, reupload after organizing".

 Not only that, but I think you're right in that it's still a possibility of issue. I also would prefer to generate them into the appropriate location.  The piece I'm a little bit uncertain of is how I'm going to get that input into the `build_packages.py` without horrendously messing something up if there is no artifact configured.

**Comment by weshaggard** [comment]
@scbedd did you have another issue opened to track the conversation we had in https://github.com/Azure/azure-sdk-for-python/pull/16187/files#r569034123?
