### ISSUE TITLE
ADLS Gen2 file owner issue

### ISSUE THREAD

**Issue by Abhishekchechani** [Azure/azure-sdk-for-python#11414]
I am referring the below Microsoft doc for creating file in ADLS gen 2 storage through python

"Use Python to manage directories, files, and ACLs in Azure Data Lake Storage Gen2"

https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-python

I am connecting ADLS Gen2 storage through sas key and run the below code.

Code :
==========================================
def upload_file_to_directory():
    try:

        file_system_client = service_client.get_file_system_client(file_system="my-file-system")

        directory_client = file_system_client.get_directory_client("my-directory")
        
        file_client = directory_client.create_file("uploaded-file.txt")
        local_file = open("C:\\file-to-upload.txt",'r')

        file_contents = local_file.read()

        file_client.append_data(data=file_contents, offset=0, length=len(file_contents))

        file_client.flush_data(len(file_contents))

    except Exception as e:
      print(e) 
============================================
But the problem is while  creating the new directory and files system takes individual id instead of service principle.

So Can anyone help what other configuration is require to define file owner as service principle

**Comment by xiafu-msft** [comment]
Hi @Abhishekchechani 

Thanks for reaching out!
Have you tried set_access_control() you should be able to set the owner there.
Let me know if it's not working!

**Comment by Abhishekchechani** [comment]
Hi @xiafu-msft , 

Thanks for your support! 

I have only got the below function to do via set access control. 

new_dir_permissions = "rwxr-xrw-"             directory_client.set_access_control(permissions=new_dir_permissions)

Could you please share the sample code to set file owner as service principal through set_access_control.

**Comment by Abhishekchechani** [comment]
Hi @xiafu-msft , 
 Could you please update on the above issue.

**Comment by xiafu-msft** [comment]
Hi @Abhishekchechani 
Did you try to set the keyword argument **owner** when you call directory_client.set_access_control()
Let me know if setting owner doesn't work!

**Comment by Abhishekchechani** [comment]
HI @xiafu-msft 

There is two way to connect ADLS GEN2 storage account.

1)storage_account_key - We have generated the account SAS key and try to connect and it allow us to connect the storage account and also able to create the Directory and file  but the issue is file and directory owner come as $superuser and group is "8922472JHJD***98"(Service principal).
And when we try to change the owner getting below error.

<Code>AuthorizationPermissionMismatch</Code>
<Message>This request is not authorized to perform this operation using this permission

2)Azure AD directory : But when we try to connect through AD directory , it allows and also able to create file and directory and the owner and group is also showing same as "8922472JHJD***98"(Service principal). 

So in shot when we try to connect Account through SAS key it not allow us to do the set_access_control showing Authorization error and owner is also showing $superuser and the same if we try to connect Account through AD directory correct owner is showing and also able to perform the  set_access_control operation.

And why we need to authenticate through SAS key because it restrict to specific storage  and container and same if we use client_id, client_secret, tenant_id for authenticate then it give the access at subscription level.

So can you suggest is there any parameter or configuration is require to use the set_access_control function while connect through SAS key or is there any other way to define the owner as service principal.

**Comment by Abhishekchechani** [comment]
> Hi @Abhishekchechani
> Did you try to set the keyword argument **owner** when you call directory_client.set_access_control()
> Let me know if setting owner doesn't work!

@xiafu-msft : when I authenticate through Storage key and use set_access_control, getting the Authorization mismatch error.

**Comment by xiafu-msft** [comment]
Hi @Abhishekchechani 
Thanks for the details! 
When use storage_account_key as credential to set owner, you should make sure the service principal is assigned the proper role.
Please try to go into your storage account > IAM > Add role STORAGE BLOB DATA CONTRIBUTOR for that service principal. 
It will take a while like 15min for everything get populated. Then you should be able to set owner to service principal.
BTW if you use AAD to authenticate, the owner should be that service principal by default.

For more info about set access control please refers to this doc. https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-access-control
The restrictions of setting owning user is documented there.

Let me know if you have any problem!

**Comment by xiafu-msft** [comment]
If this is no longer a problem we will close the issue! Feel free to reopen it if you have further questions!
