### ISSUE TITLE
Pylint in tox not catching unused-import error

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#11421]
tox is not catching the unused import in the CI
 
I deliberately added an unused import and here's the output if i use `tox tox -c ../../../eng/tox/tox.ini -e lint`

```
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
_____________________________________________________ summary ______________________________________________________
  lint: commands succeeded
  congratulations :)
```
 
howeever, if i use `pylint .`

```
azure\search\documents\_service\_search_service_client_base.py:10:0: W0611: Unused SearchDataSourcesClient imported from _datasources_client (unused-import)
```
 
fyi, CI is not catching this either

**Comment by rakshith91** [comment]
@scbedd @praveenkuttappan

**Comment by scbedd** [comment]
@rakshith91 This does not repro for me using the same installed versions of `pylint` and dependent packages as CI has.

![image](https://user-images.githubusercontent.com/45376673/82105714-9a57d480-96d1-11ea-88b7-5fdce572448d.png)

I'm betting this is another instance of shifting dependencies identifying issues that we hadn't seen before.

Please repro the behavior, then run `pip freeze` and dump the output here.

**Comment by scbedd** [comment]
Thanks @rakshith91 !

Talked via Teams and got this:

```
aiohttp==3.6.2
astroid==2.4.1
async-timeout==3.0.1
attrs==19.3.0
azure-core==1.5.0
azure-core-tracing-opentelemetry==1.0.0b4
certifi==2020.4.5.1
chardet==3.0.4
colorama==0.4.3
idna==2.9
isodate==0.6.0
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
msrest==0.6.13
multidict==4.7.5
oauthlib==3.1.0
opentelemetry-api==0.6b0
opentelemetry-sdk==0.6b0
pylint==2.5.2
requests==2.23.0
requests-oauthlib==1.3.0
six==1.14.0
```

**Comment by scbedd** [comment]
Closing in favor of #10533. I expect the new errors to be picked up after we bump the pinned CI versions.
