### ISSUE TITLE
BlobClient.upload_blob hangs sometimes

### ISSUE THREAD

**Issue by AlexeyRaga** [Azure/azure-sdk-for-python#11437]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.3.1
- **Operating System**: Linux
- **Python Version**: 3.5.2

**Describe the bug**
Calling to `blob_client.upload_blob` hangs forever.

The essence of my script is here:

```
blob_service_client = BlobServiceClient.from_connection_string(storage_connection_string)

while (True):
  file_name = get_next_file_name()
  bname = make_target_name(file_name)

  with blob_service_client.get_blob_client(container=storage_results_container, blob=bname) as upload_client:
      with open(file_name, "rb") as data:
          logging.info("Uploading the file")
          upload_client.upload_blob(data, blob_type="BlockBlob", overwrite=True)
          logging.info("Finished uploading")
```

When I run it it _sometimes_ works fine, but _sometimes_ hangs after printing `Uploading the file` line.

**To Reproduce**
I don't have a clear path to reproduce it, but when I run this sort of a loop in AKS it eventually hangs.

**Expected behavior**
It doesn't hang :)

**Screenshots**

**Additional context**
```
2020-05-14 05:01:23,584 INFO Handling file: call-2.mp3
2020-05-14 05:01:33,916 INFO Waiting for transcribing to complete...
2020-05-14 05:01:43,920 INFO Waiting for transcribing to complete...
2020-05-14 05:01:52,006 INFO Finished transcribing, uploading results
2020-05-14 05:01:52,006 INFO Uploading the file
<nothing happens after this line>
```

**Comment by xiafu-msft** [comment]
Hi @AlexeyRaga 

Thanks for reaching out! It looks like there is an similar issue you created in the repo, would you mind if we close one of these two(probably this one)?
https://github.com/Azure/azure-sdk-for-python/issues/11457

**Comment by AlexeyRaga** [comment]
@xiafu-msft I am not sure if it is the same issue one or not. #11457 is about the metadata.
In this case I don't set _any_ metadata and am just uploading the file (~40KB).

#11457 crashes by timeout after ~90 seconds while this one doesn't seem to crash even after many minutes of wait.

It looks like a different issue.

**Comment by xiafu-msft** [comment]
Hi @AlexeyRaga 

Is it convenient for you to get the response header x-ms-request-id, I wasn't able to reproduce the hanging problem...
If you are on windows, you can use fiddler to see the request and response, if you are on Mac you can use WireShark. Sometimes https doesn't work then you can set the accout url to http.

Thanks for your help! Let me know if it's not convenient for you to get the response then we will look for some other way to reproduce the problem.

**Comment by AlexeyRaga** [comment]
I will try finding time to reproduce it again.
As I said, it didn't happen _all the time_, and I have worked it around for now.

**Comment by anurag-ae** [comment]
I am also facing the same issue. Any solution?

**Comment by anurag-ae** [comment]
In my case the issue was calling the read() function of Flask FileStorage. 

https://stackoverflow.com/questions/3906137/why-cant-i-call-read-twice-on-an-open-file

**Comment by xiafu-msft** [comment]
Hi @anurag-ae 

Flask FileStorage is not Storage SDK, would you like to explain a bit about when you have the hanging problem?

**Comment by tasherif-msft** [comment]
@angiurgiu @AlexeyRaga are you still encountering this issue?

**Comment by 4vadim4** [comment]
i have the same problem;

- Package Name: azure-storage-blob
- Package Version: 12.9.0
- Python Version: 3.10.0

i use Azurite and try to upload image:

code:
```
    async def upload_blob(self):
        print('========= in upload_blob ===========')
        print('type(self.blob_client)', type(self.blob_client))
        print('type(self.image_binary)', type(self.image_binary))
        print('self.blob_client.account_name', self.blob_client.account_name)
        self.blob_client.upload_blob(self.image_binary)
        print('========= upload_blob done ! ===========')
```

output:
```
========= in upload_blob ===========
type(self.blob_client)   <class 'azure.storage.blob._blob_client.BlobClient'>
type(self.image_binary)   <class 'bytes'>        
self.blob_client.account_name   devstoreaccount1
```

upload_blob is hangs always by 1-1,5min and crashing with traceback:

```
  File "/usr/src/app/./app/apps/document/core/managers/azure_blob.py", line 39, in upload_blob
    self.blob_client.upload_blob(self.image_binary)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 713, in upload_blob
    return upload_block_blob(**options)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 168, in upload_block_blob
    process_storage_error(error)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 177, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: None
ErrorCode:None
```

what wrong ?
