### ISSUE TITLE
Get Image operation not returning the storage profile os_disk and data_disk size

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1144]
Hi,

I am using the Compute API to get image. My requirement is to get the list of disks present in the Image and also size of the disk. In the get image operation result, the disk_size_gb property returning None for os_disk and also for the data_disk.

Please let us know, is there any additional information I need to pass to this get method.

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS 

Please look at this issue, this is a known limitation of the Compute RestAPI: https://github.com/Azure/azure-sdk-for-python/issues/672
