### ISSUE TITLE
Appconfiguration logs extensively and does not respect log levels

### ISSUE THREAD

**Issue by espenairmine** [Azure/azure-sdk-for-python#11440]
- **Azure.Appconfiguration**: 
- **1.0.0**: 
- **Docker image: FROM mcr.microsoft.com/vscode/devcontainers/python:0-3, also effects functions deployed to Azure (tested with consumption, v3)**:
- **3.8.2**: 

**Describe the bug**
Using appconfig spams the logs + function monitoring, annoying but not a show stopper.
Setting the loglevel has no effect, 

**To Reproduce**
Simple function
```python
import azure.functions as func
from azure.appconfiguration import AzureAppConfigurationClient as appclient

def main(req: func.HttpRequest) -> str:
    client = appclient.from_connection_string("conn_str")
    setting = client.get_configuration_setting(key="some_key")
    return "test"
```

**Expected behavior**
Using appconfiguration should not produce any specific logs unless loglevel set to debug, re documentation:  https://docs.microsoft.com/en-us/python/api/overview/azure/appconfiguration-readme?view=azure-python

**Screenshots**

![image](https://user-images.githubusercontent.com/51234981/81912875-7d3add00-95cf-11ea-8dc4-1b2363cb520b.png)

**Comment by lmazuel** [comment]
Hi @espenairmine 
I'm not sure I agree on:
> appconfiguration should not produce any specific logs unless loglevel set to debug

SDK are able to log into all levels, critical, warning, info and debug depending of what is necessary. What you see is the HTTP info logger, which is here on purpose, and can be disabled using usual logging level setting by level. For instance:
```python
azure_logger = logging.getLogger("azure")
azure_logger.setLevel(azure_logger, logging.WARNING)
```

**Comment by espenairmine** [comment]
Hi @lmazuel 


I should have been more precise in my statement:

_appconfiguration should not produce verbose  logs unless loglevel set to debug_

I assumed setting the log level to warning with (as sett in the docs): 
``` logging.basicConfig(level=logging.WARNING)```
would reduce the logs, but the above has no effect.

Following your approach did the trick.
Thanks for quick and helpful reply!
