### ISSUE TITLE
BlobClient.upload_blob hangs and crashes (2 in 1)

### ISSUE THREAD

**Issue by AlexeyRaga** [Azure/azure-sdk-for-python#11457]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.3.1
- **Operating System**: Linux
- **Python Version**: 3.7.7

**Describe the bug**
`BlobClient.upload_blob` hangs for 1.5 minutes if a metadata value contains a leading space. Then it crashes with a deep Python stack trace and `ServiceRequestError` exception.

It crashes much faster when a metadata value ends with a space though! Which could be a good thing if it wasn't `ClientAuthenticationError` exception.

**To Reproduce**

```
with open("requirements.txt", "rb") as data:
    test_container.upload_blob("test.txt", data, overwrite=True, metadata={'config': conf})
```

This fails after 1.5 minutes with `ServiceRequestError` when `conf = " boo"`, and it fails with `ClientAuthenticationError` when `conf = "boo  "`

**Expected behavior**
Metadata is validated before actually making a call, a meaningful validation exception is raised.

**Comment by xiafu-msft** [comment]
@AlexeyRaga 

Thanks for reaching out and sorry that you are having this issue.
May I know the size of the blob and the region your account is located?
Thanks for the info

**Comment by AlexeyRaga** [comment]
@xiafu-msft Hi, the size seems to be irrelevant (I tested on files that are from ~200B to ~30KB).
I think the problem here is in HTTP headers: metadata is sent via the headers, headers are not validated/cleaned by the API which causes the problem.

I am testing in `East Australia` region.

**Comment by xiafu-msft** [comment]
Hi @AlexeyRaga 

Thanks for the info! It should be a SDK bug, SDK should trim the metadata value for user before sending to the service. We will file a bug and fix it.

Does this sound good to you? Let me know how you feel about SDK trimming the prepended/appended space for you! Thanks.

**Comment by xiafu-msft** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/11677

**Comment by AlexeyRaga** [comment]
Sounds good to me.
Trimming vs. validation - doesn't matter in my use case, whatever is more canonical for Python...

**Comment by xiafu-msft** [comment]
Thanks @AlexeyRaga for reporting this issue, this has been merged and will be released in this week. 
For the other issue you opened we will dig into it!

Close this one for now, feel free to reopen it if you have any concern! Thanks again!
