### ISSUE TITLE
DataLakeFileClient.rename_file fails if there are spaces anywhere in the path.

### ISSUE THREAD

**Issue by toddkitta** [Azure/azure-sdk-for-python#11478]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.0.1
- **Operating System**: Windows 10 (18363.836)
- **Python Version**: 3.7.0

**Describe the bug**
When using DataLakeFileClient to rename a file with spaces in the path (file name or folder name), I get an error when calling rename_file. Error is:

"The source URI is invalid."

**To Reproduce**
1. Create a DataLakeFileClient for a file with spaces anywhere in the path (directory or file name). This should succeed.
2. Call rename_file and observe the error.

**Expected behavior**
The rename should work.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by alecgonzales** [comment]
Getting the same issue.

**Comment by vincenttran-msft** [comment]
I believe this issue has been resolved since it was last reported as broken. Example of properly URL-encoded path after `rename_file` API used to change from `name` to `new name`
![image](https://user-images.githubusercontent.com/101599632/208803958-82235f49-593d-4985-b8da-eb07f32d4bf8.png)
