### ISSUE TITLE
AKS Deployment Can't find model file but ACI and Local Deployments are fine 

### ISSUE THREAD

**Issue by mkrdip** [Azure/azure-sdk-for-python#11476]
- **azureml-core**: 
- **1.5.0.post4**: 
- **Ubuntu 16**:
- **3.7**: 

**Describe the bug**
Aks Deployment doesn't download model files into the `outputs` folder, instead, it creates a single file `outputs`. So, when deployed the `init()` can't find the model files.

**To Reproduce**
1. Create Local and ACI Deployment with a model that has multiple files
2. Create an AKS Deployment with the same config
2. You'll see local and ACI deployment are just fine, but AKS deployment fails as I described the reason in the bug above

**Expected behavior**
Deploy to AKS should go fine as with the same configs local and ACI deployments are fine.

**Additional context**
The same issue with CLI ML extension too, link to the issue posted: https://github.com/Azure/azure-cli-extensions/issues/1701 with details (logs and error message)

**Comment by shivanissambare** [comment]
Hi,
Have you tried this troubleshooting document -

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-deployment?tabs=azcli#service-launch-fails

Function fails: get_model_path() -

Often, in the init() function in the scoring script, Model.get_model_path() function is called to locate a model file or a folder of model files in the container. If the model file or folder cannot be found, the function fails. The easiest way to debug this error is to run the below Python code in the Container shell:

from azureml.core.model import Model
import logging
logging.basicConfig(level=logging.DEBUG)
print(Model.get_model_path(model_name='my-best-model'))

This example prints out the local path (relative to /var/azureml-app) in the container where your scoring script is expecting to find the model file or folder. Then you can verify if the file or folder is indeed where it is expected to be.

Setting the logging level to DEBUG may cause additional information to be logged, which may be useful in identifying the failure.

**Comment by shivanissambare** [comment]
Closing this issue, please re-open or let us know in case you need more help.
Thank you!

**Comment by shivanissambare** [comment]
#please-close
