### ISSUE TITLE
Storage Tables & Queues missing Shared Access Signature support

### ISSUE THREAD

**Issue by codingoutloud** [Azure/azure-sdk-for-python#115]
Support appears to be available for Storage Blobs, but not Tables and Queues.

For reference: 
http://blogs.msdn.com/b/windowsazurestorage/archive/2012/06/12/introducing-table-sas-shared-access-signature-queue-sas-and-update-to-blob-sas.aspx

**Comment by huguesv** [comment]
It's in for 0.11.0, in github master branch.
http://azure-sdk-for-python.readthedocs.org/en/latest/storage.html

It's not on PyPI yet, but it's in github master branch. Please let us know if you've tried it. I'll close this when we release 0.11 to PyPI (next week?).

**Comment by huguesv** [comment]
0.11.0 now on PyPI.
