### ISSUE TITLE
Split searchindex.json and searchservice.json models and operations into separate namespaces

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#11508]
Models and operations in searchindex.json shoud go into namespaces like so (adjusted for your language):

* Azure.Search.Documents (SearchClient, SearchClientOptions)
* Azure.Search.Documents.Models

Models and operations in searchservice.json should go into namespaces like so (adjusted for your language):

* Azure.Search.Documents.Indexes (SearchIndexClient, SearchIndexerClient)
* Azure.Search.Documents.Indexes.Models

**Comment by bryevdv** [comment]
@xiangyan99 just noting that this is the current file system split:

* searchindex.json -> `azure.search.documents._index` 
* searchservice.json  -> `azure.search.documents._service` 

and then currently everything is brought up to the `azure.search.documents` level. This task should be a fairly straightforward rename of `azure.search.documents._service` to `azure.search.documents.indexes`

**Comment by xiangyan99** [comment]
Fixed in #11584
