### ISSUE TITLE
CustomVision - CustomVisionTrainingClient can not be imported from azure.cognitiveservices.vision.customvision

### ISSUE THREAD

**Issue by iMicknl** [Azure/azure-sdk-for-python#11504]
- **Package Name**: Custom Vision
- **Package Version**: 2.0.0
- **Operating System**: Linux
- **Python Version**: 3.6

**Describe the bug**
[azure-cognitiveservices-vision-customvision 2.0.0 on PyPi](https://pypi.org/project/azure-cognitiveservices-vision-customvision/) mentions:

```
CustomVisionTrainingClient cannot be imported from `azure.cognitiveservices.vision.customvision.training anymore` (import from `azure.cognitiveservices.vision.customvision` works like before)
```

**To Reproduce**
`from azure.cognitiveservices.vision.customvision import CustomVisionTrainingClient`

```ImportError: cannot import name 'CustomVisionTrainingClient'```

Importing it from `azure.cognitiveservices.vision.customvision.training` works.

**Expected behavior**
Importing from `azure.cognitiveservices.vision.customvision` should work, or it should be updated in the documentation.

**Additional context**
Related to #11503

**Comment by RodgeFu** [comment]
An issue in changelog tool to generate the doc? + @lmazuel to confirm. thanks.

**Comment by zikalino** [comment]
@RodgeFu this is not an issue with the tool. Currently we use template for general breaking changes and modify it manually to suit particular release (client names etc.). So yes, it's error prone...
Perhaps general breaking changes should be automatically generated by changelog tool as well.

The proper string in this case should be:

•	CustomVisionPredictionClient cannot be imported from azure.cognitiveservices.vision.customvision.prediction**.custom_vision_training_client** anymore (import from azure.cognitiveservices.vision.customvision**.training** works like before)
I can make additional release to fix the wording.
