### ISSUE TITLE
Refactor SearchServiceClient into SearchIndexClient and SearchIndexerClient

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#11507]
To avoid too many methods in `SearchServiceClient`, we will refactor it into two separate clients that group the functionality into index management, and skillsets (enrichments) management. Method names will retain their names they have today, like `CreateIndex`, `DeleteIndex`, `CreateDataSource`, `DeleteDataSource`, etc. This also means there should be the `GetServiceStatistics` like we should have no, instead of dropping "Service". This differentiates it with `GetIndexStatistics`.

* `SearchIndexClient` will aggregate:
  * Index operations: `CreateIndex`, etc.
  * Synonym map operations: `CreateSynonymMap`, etc.
  * Service operations: `GetServiceStatistics`
  * Define/retain `GetSearchClient` that takes a string `indexName` and returns a `SearchClient`

* `SearchIndexerClient` will aggregate:
  * Indexer operations: `CreateIndexer`, etc.
  * Data source operations: `CreateDataSource`, etc.
  * Skillset operations: `CreateSkillset`, etc.

**Comment by bryevdv** [comment]
@xiangyan99 Do you have a preference about https://github.com/Azure/azure-sdk-for-python/pull/11342 ? I have broken that PR in to very discrete commits it might be simpler for you to cherry pick the ones you want to keep, given this and other new rename changes in the original rename issue. What do you think?

**Comment by xiangyan99** [comment]
Either one works.

**Comment by xiangyan99** [comment]
Fixed in #11572
