### ISSUE TITLE
Search model renames

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#11506]
There are a few more renames to make. But not just renames: the "V2" models should be collapsed with their v1 (no suffix, that is) counterparts and original `@odata.type` retained for round-tripping. When new ones are created, the "V2" equivalent should always be created because the v1s will cause the service to fail when using the new api-version.

Old name | New name | Notes
--- | --- | ---
EdgeNGramTokenFilterV2 | EdgeNGramTokenFilter | Collapse with existing EdgeNGramTokenFilter
KeywordTokenizerV2 | KeywordTokenizer | Collapse with existing KeywordTokenizer (will have separate properties for v1 and "V2")
LuceneStandardTokenizerV2 | LuceneStandardTokenizer | Collapse with existing LucenseStandardTokenizer
NGramTokenFilterV2 | NGramTokenFilter | Collapse with existing NGramTokenFilter
PathHierarchyTokenizerV2 | PathHierarchyTokenizer | (*There is no v1*)
Similarity | SimilarityAlgorithm | Do not rename derivative types
Suggester | SearchSuggester

**Comment by xiangyan99** [comment]
Fixed in #11683
