### ISSUE TITLE
Virtual Machine Size Model (concern for few properties).

### ISSUE THREAD

**Issue by JatinKinra** [Azure/azure-sdk-for-python#1151]
Hi,

The current SDK does not provide few properties for VM Size.
Currently, 'name', 'number_of_cores', 'os_disk_size_in_mb', 'resource_disk_size_in_mb', 'memory_in_mb', 'max_data_disk_count' is being provided.

Required properties -
1 - Id
2 - Family / Class
3 - size of root disk
4 - Something similar to "size_ephemeral_disks" and "num_ephemeral_disks" in AWS.

Can you please provide us with a way to map these properties ?

Thanks - Jatin

**Comment by lmazuel** [comment]
Hi @JatinKinra 

I guess you are talking about this [model](http://azure-sdk-for-python.readthedocs.io/en/latest/_modules/azure/mgmt/compute/compute/v2016_04_30_preview/models/virtual_machine_size.html#VirtualMachineSize)?

We return the information available on the RestAPI, so it's not a Python issue unfortunately :(. Could you ask your question on the RestAPI repository, this way you will have an answer directly from the RestAPI team. If they are able to do it, we can add this information in Python. The repo is here:
https://github.com/Azure/azure-rest-api-specs.
Plese mention this issue as well.

I keep this issue opened until we got an answer from the RestAPI team.

Thank you  for your feedback,

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
