### ISSUE TITLE
Search Field helper functions and edm types are not very discoverable

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#11511]
UX study participants stated that it was not clear how they would have easily found search field helpers or information about the edm types except for the sample code. 

IIRC in other languages the edm types are referred under a different enum or namespace related to "odata". Perhaps this is more commonly known. 

cc @xiangyan99 @heaths

**Comment by heaths** [comment]
The type should actually be `SearchFieldDataType` - an enum-like structure with the option to pass one of those types to a function-like `Collection`, which makes it a string like "edm.Collection(edm.String)" (for a collection of string). See .NET for an example.

**Comment by xiangyan99** [comment]
Fixed in #11597
