### ISSUE TITLE
Better name for Search Indexer DataSource

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#11515]
Currently to create a `SearchIndexer` you must first create a `DataSource` that desribes a connection to some external data source to be indexed (e.g. data in Azure blob storage). Nearly every UX study participant was confused by this, and thought e.g. that the `DataSource` object *was* somehow the external data source (rather than a description of if) or that blob storage clients could be passed directly to the search indexer. 

Has been suggested a different name could help make the purpose of this model more evident.

* `DataSourceConnection`
* `DataSourceRelation`
* `DataSourceDescription`

For further work, perhaps it would make sense to see if e.g. a blob storage client could just be accepted directly (this was asked for by at least one participant)

cc @xiangyan99 @heaths and this will probably need to be taken up with the team and @brjohnstmsft

**Comment by brjohnstmsft** [comment]
FWIW I like `DataSourceConnection`. Adding @bleroy for his opinion.

**Comment by heaths** [comment]
I like "connection", although, that should be `SearchIndexerDataSourceConnection` given the naming convention we already established.

**Comment by heaths** [comment]
I opened #11565 which includes this (similar bugs opened across other languages).
