### ISSUE TITLE
Support new Azure Compute API "SimulateEviction" for both Standalone VM and VMSS VM via Python SDK

### ISSUE THREAD

**Issue by sandeepkv93** [Azure/azure-sdk-for-python#11536]
**Is your feature request related to a problem? Please describe.**
We released new API "SimulateEviction" in Azure Compute. We want Python SDK support for it. There are two APIs with the same API name. One for Standalone VM and another for VMScaleSet VM. 

https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/simulateeviction
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/simulateeviction

**Describe the solution you'd like**
Supporting this Compute API via Python SDK

**Describe alternatives you've considered**

**Swagger Links**
https://github.com/Azure/azure-rest-api-specs/pull/8929
https://github.com/Azure/azure-rest-api-specs/pull/9102

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kaerm** [comment]
Thanks @sandeepkv93, @nickzhums could you take a look at this

**Comment by nickzhums** [comment]
@RodgeFu please help have a look

**Comment by zikalino** [comment]
@sandeepkv93 please request release of the new package via: https://portal.azure-devex-tools.com/tools/request-api-release

**Comment by sandeepkv93** [comment]
@zikalino Sure, created a request

**Comment by RodgeFu** [comment]
https://github.com/Azure/sdk-release-request/issues/382 has been created to track the request release, so close this one. thanks.
