### ISSUE TITLE
SharedTokenCacheCredential defaults to the "common" tenant without the option to change that

### ISSUE THREAD

**Issue by robwe** [Azure/azure-sdk-for-python#11549]
- **Package Name**: identity
- **Package Version**: 1.4.0b4
- **Operating System**:
- **Python Version**: 3.7

**Describe the bug**
In SharedTokenCacheCredential _get_auth_client() creates an AadClient with tenant_id="common". All subsequent calls to get_token() will use this tenant, which might not be the tenant for which the token should be obtained. Hence SharedTokenCacheCredential is unusable for all other tenants.

**Expected behavior**
SharedTokenCacheCredential should work for the tenant specified by _shared_cache_tenant_id_.

**Additional context**
The fix is to change in the SharedTokenCacheCredential class (in _credentials and aio\_credentials) the _get_auth_client() function to use as first argument of AadClient():
`tenant_id=self._tenant_id if self._tenant_id else "common"`

**Comment by kaerm** [comment]
Thanks @robwe for reporting this, @chlowell could you take a look at this

**Comment by chlowell** [comment]
"common" isn't a tenant; it multiplexes across all Azure AD tenants (see e.g. this [Azure AD documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant#update-your-code-to-send-requests-to-common)) and can service token requests for a user from any tenant.

Can you be more specific about the scenario in which the credential doesn't work as you expect?

**Comment by robwe** [comment]
Lease see my [comment on issue 11551](https://github.com/Azure/azure-sdk-for-python/issues/11551#issuecomment-632403017) about the scenario that does not work for me.

**Comment by chlowell** [comment]
I'm closing this issue because in azure-identity 1.6.0, released today, you can specify which tenant you want SharedTokenCacheCredential to authenticate in, provided you give it an AuthenticationRecord to identify a user in the cache:
```py
from azure.identity import InteractiveBrowserCredential, TokenCachePersistenceOptions

# authenticate a user, storing auth data in the shared cache
credential = InteractiveBrowserCredential(
    cache_persistence_options=TokenCachePersistenceOptions(),
    tenant_id=TENANT_A
)

# authenticate() authenticates the user and returns a record you can serialize for storage
auth_record = credential.authenticate()

# When given an AuthenticationRecord, SharedTokenCacheCredential defaults to authenticating in
# the tenant that authenticated the user, i.e. TENANT_A. You can specify a different one with "tenant_id"
SharedTokenCacheCredential(authentication_record=auth_record, tenant_id=TENANT_B)
```

The [user authentication sample](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/samples/user_authentication.py) demonstrates the API in more detail.
