### ISSUE TITLE
[Identity] UsernamePasswordCredential should expose authenticate method which returns AuthenticationRecord

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#11546]
`UsernamePasswordCredential` should expose `authenticate` method which returns `AuthenticationRecord`. 

Otherwise when **username+password** is used as the authentication method, Azure CLI **can't persist user's auth record and utilize refresh tokens stored in MSAL cache**. In such case, Azure CLI will have to **save user's password** by itself, which is absolutely not a good idea from a security perspective.

**Comment by chlowell** [comment]
Duplicate of #11449
