### ISSUE TITLE
Autorest job fails since autorest tests are adapted to msrest 0.6.14

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#11556]
Since msrest 0.6.14 requires a slight change of autorest tests, right now the job pulls the latest autorest tests but pin msrest to 0.6.13, which broke them

```
>       assert response == isodate.parse_datetime("2001-01-01T00:00:00Z")
E       AssertionError: assert datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc) == datetime.datetime(2001, 1, 1, 0, 0, tzinfo=<isodate.tzinfo.Utc object at 0x7f51edfc3cf8>)
E        +  where datetime.datetime(2001, 1, 1, 0, 0, tzinfo=<isodate.tzinfo.Utc object at 0x7f51edfc3cf8>) = <function parse_datetime at 0x7f51edf74488>('2001-01-01T00:00:00Z')
E        +    where <function parse_datetime at 0x7f51edf74488> = isodate.parse_datetime
```

We need to pin to 0.6.14, or at least install 0.6.14, or not pin at all (I guess I like >=0.6.14 here)

**Comment by scbedd** [comment]
@lmazuel Going to keep it consistent and still keep it pinned. We will keep circling back about once a month and update these. The version updates I'm doing here match the versions I'm working through on another PR that will bump the deps that have updated.
