### ISSUE TITLE
Provisioning State and Power State of VM

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1155]
Hi ,

Can we get list of possible provisioning states and power states while creating VM?

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS 

Reserved provisioning states are "Succeeded", "Failed" and "Canceled". Then this is a random string that can change over time and decided by the service team ("MountingDrive", "SelectingHosts", etc.). If it's random string, it's considered "provisioning in progress".

I don't know about "power states", I will ask the question.

**Comment by runemy** [comment]
Would be nice to have estimated information about % provisioning (deployment) as a number from 0 to 100. Where 100 = Succeeded.

**Comment by lmazuel** [comment]
@derekbekoe @yugangw-msft do you know if it's available (% provisionning)?

**Comment by yugangw-msft** [comment]
This page has the [power state list](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/tutorial-manage-vm)

 > do you know if it's available (% provisionning)?

I don't think so.
