### ISSUE TITLE
SharedTokenCacheBase does not handle multiple accounts for the same refresh token correctly

### ISSUE THREAD

**Issue by robwe** [Azure/azure-sdk-for-python#11550]
- **Package Name**: identity
- **Package Version**: 1.4.0b4
- **Operating System**:
- **Python Version**: 3.7

**Describe the bug**
I am using the latest version (16.5.5) of Visual Studio 2019. My cache contains four accounts for the same username, but different tenants. Hence, in _get_accounts_having_matching_refresh_tokens() of the SharedTokenCacheBase class, all_accounts has four elements, all with the same "home_account_id". In the iteration over all_accounts, each account is added to the accounts dictionary using home_account_id as key. As all the accounts have the same key, only the account that happens to be the last account being returned by the iteration remains in the dictionary. This may or may not be the account with the desired tenant.
Hence, SharedTokenCacheCredential does not work for a user with multiple tenants.

**Expected behavior**
SharedTokenCacheCredential must also work for a users with multiple tenants.

**Additional context**
The fix is to define the accounts variable as a list instead of a dict and to append the accounts to the list and to return the list instead of the dict's values.

**Comment by kaerm** [comment]
Thanks @robwe for reporting this, @chlowell could you take a look at this

**Comment by chlowell** [comment]
This is deliberate. Refresh tokens are tenant-independent, and in the cache are joined to accounts on `home_account_id`. So from the perspective of `SharedTokenCacheCredential`, which is searching for a refresh token by way of an account, four accounts with the same `home_account_id` are identical.

Can you be more specific about what you mean by the credential not working for a user with multiple tenants?

**Comment by robwe** [comment]
Lease see my [comment on issue 11551](https://github.com/Azure/azure-sdk-for-python/issues/11551#issuecomment-632403017) about the scenario that does not work for me.

**Comment by chlowell** [comment]
Thanks for the additional details. I'm closing this issue because this particular behavior is correct, and orthogonal to supporting authentication in foreign tenants (the broader feature request described in #11551).
