### ISSUE TITLE
More Search renames

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#11565]
Based on UX studies, please make the following changes as well:

Old name | New name | Notes
--- | --- | ---
SearchIndexerDataSource | SearchIndexerDataSourceConnection
SearchField.SynonymMaps | SearchField.SynonymMapNames | For dynamic languages with union support, you could instead accept either a string or object and, if an object that is a SynonymMap, extract it's name. But it's not always practical to expect they will create or even get a synonym map just to pass it in, so a string name (these are managed separately) is still required to be supported.
SearchField.Analyzer | SearchField.AnalyzerName
SearchField.IndexAnalyzer | SearchField.IndexAnalyzerName
SearchField.SearchAnalyzer | SearchField.SearchAnalyzerName
SearchableField.SynonymMaps | SearchableField.SynonymMapNames | *Same as above*
SearchableField.Analyzer | SearchableField.AnalyzerName
SearchableField.IndexAnalyzer | SearchableField.IndexAnalyzerName
SearchableField.SearchAnalyzer | SearchableField.SearchAnalyzerName

**Comment by xiangyan99** [comment]
Fixed in #11683
