### ISSUE TITLE
[uAMQP] Integrate regression test of uAMQP within CI

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#11588]
It would be great if uAMQP livetest pipeline can trigger EH/SB livetest pipleline with the built whl files.

Regression test uAMQP requires using the generated uAMQP whl files to
- EventHub livetests
- ServiceBus livetests

uAMQP has its own [client build pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=88)  and repo is here: https://github.com/Azure/azure-uamqp-python

general steps:
1. git clone azure-sdk-for-python
2. install servicebus/eventhub from the cloned repo
3. kick off eh/sb livetest against the uamqp pr

(msrest could be a reference)

Manual testing process outline [here](https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FLanguage%20-%20Python%2FAzure%20SDK%20-%20Language%20-%20Python&wd=target%28Services.one%7C7EDF4D8F-3CF7-4200-BCD2-567D6A7E429C%2FManual%20test%20uamqp%20whls%20against%20servicebus%5C%2Feventhub%20livetest%20pipeline%7CC5ACB695-5A40-4B85-A318-C3C67E79AA54%2F%29) .

**Comment by swathipil** [comment]
look into testing with Docker container
