### ISSUE TITLE
Improve azure-keyvault custom Authentication mecanism

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#1159]
`requests` has nice ability to accept a subclass of AuthBase to custom the authentication process. This is callback-based, and `requests` gives to the `__call__` method a prepared query. Note that when you do `requests.get` or any methods, requests creates for you a prepared query first, and this is this query that is sent to `AuthBase` subclasses.
However, not all possible parameters are inside a prepared query. For example, `verify`, that you can specify in your call (ie: `requests.get(...., verify='myfile')`) is not used in the prepared query. In addition, we don't have access to the context (i.e. are we using a Session?).

KeyVault has a special behavior that requires to do a requests from AuthBase to get the token. With the preceding limitation, this implies that we don't have access to the following parameters from within an AuthBase: proxies, stream, verify, cert, timeout, alow_redirects. We don't have access too to the configuration of the Session that is doing the call. To end, AuthBase is called before environment variable like REQUESTS_CA_BUNDLE or CURL_CA_BUNDLE are read.

The probable best approach is to provide auth dynamically:
```python
client.certificates.get(......., auth=KeyAuthBase(.....))
```
This way we can create this class with the context and drop it after the call. Another way is to add support for that in msrest. Since msrest owns the Session and the `requests` call, we are in the right place to fix the context.

FYI @schaabs

**Comment by schaabs** [comment]
This issue has been resolved
