### ISSUE TITLE
Help me to convert "az login" to the equivalent API

### ISSUE THREAD

**Issue by cladic** [Azure/azure-sdk-for-python#11625]
Which is the API version equivalent of the execution of command line "AZ login -u user -p password" ?

**Comment by lmazuel** [comment]
Hi @cladic 
I'm not sure I understand the details of your question, being it's authentication, maybe this page would be useful?
https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=bash

Thanks,

**Comment by cladic** [comment]
Thanks for your attention... I will be more specific.

I have a routine to get information from AZURE...so i use 'az login -u myuser -p mypassword' and next I execute the next command like = az monitor log-analytics query -w (my GUID) --analytics-query "AzureDiagnostics | where TimeGenerated > ago(1d) | summarize count() by Category"

So I want to write a Python program equivalent these commands...

First i got this solution in Python. But first I need to make sure the command "az login..." was executed with success. This is very important at this point of my explanation, the user must be logged in first by a command line:

        creds,_ = get_azure_cli_credentials(resource="https://api.loganalytics.io")
        log_client = LogAnalyticsDataClient(creds)
        myWorkSpaceId = 'my workspace guid'
        tquery = {
            'query': 'AzureDiagnostics|where TimeGenerated > ago(1d)|summarize count() by Category'}
        result = log_client.query(myWorkSpaceId,QueryBody(**tquery))
        print ( "Number of columns: {}".format ( len (  result.tables[0].columns ) ) )
        print("OK")

This code executed with no problem.

Now I execute the logout command "az logout" and execute the same program. I got this error executing this function "get_azure_cli_credentials":

   creds,_ = get_azure_cli_credentials(resource="https://api.loganalytics.io")
 
   ==> Error:Please run 'az login' to setup account.

So we have some kind of information buffered on some place ( HOMEUSER/.azure/accessTokens.json and HOMEUSER/.azure/azureProfile.json ). 

The I wish to execute the equivalent of "az login..." on teh same Python program....

The link you show seems to resolve the question. But none of the examples works...

In my program is clear I have to execute some code BEFORE de "get_azure_cli_credentials".

If I use this code:

        # Retrieve the IDs and secret to use in the JSON dictionary
        subscription_id = "my-subs-guid"
        tenant_id = "my-tenant-guid"
        client_id = "MYUSER"
        client_secret = "MYPASSWORD"

        config_dict = {"subscriptionId": subscription_id,"tenantId": tenant_id,"clientId": client_id,
            "clientSecret": client_secret,"activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
            "resourceManagerEndpointUrl": "https://management.azure.com/",
            "activeDirectoryGraphResourceId": "https://graph.windows.net/",
            "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
            "galleryEndpointUrl": "https://gallery.azure.com/",
            "managementEndpointUrl": "https://management.core.windows.net/"}

        subscription_client = get_client_from_json_dict(SubscriptionClient,config_dict)

        subscription = next(subscription_client.subscriptions.list())
        print(subscription.subscription_id)

I have this error on 'get_client_from_json_dict' :

   _**msrest.exceptions.AuthenticationError: Get Token request returned http error: 400 and server response: 

   {"error":"unauthorized_client","error_description":"AADSTS700016: 

   Application with identifier 'MYUSER' was not found in the directory 'my-tenant-guid'. 

   This can happen if the application has not been installed by the administrator of the tenant or        consented to by any user in the tenant. 

   You may have sent your authentication request to the wrong tenant.\r\n
   Trace ID: 6e5bd090-d046-4cf5-af8a-493e16815900\r\n
   Correlation ID: 07a2dfd8-bee8-4249-beb5-2aeef1def59a\r\n
   Timestamp: 2020-05-26 19:34:28Z",
   "error_codes":[700016],
   "timestamp":"2020-05-26 19:34:28Z",
   "trace_id":"6e5bd090-d046-4cf5-af8a-493e16815900",
   "correlation_id":"07a2dfd8-bee8-4249-beb5-2aeef1def59a",
   "error_uri":"https://login.microsoftonline.com/error?code=700016"}**_

**I can not understand my problem as "authorization problem" because I am using the same USER/PASSWORD as in the command "az login..." command line. I think if this USER/PASSWORD works with "az login..." it is possible have a PYTHON code equivalent.**

The "az program" is a PYTHON program using the AZURE PYTHON SDK so i think it is not so difficult have the PYTHON code for this task: login de USER/PASSWORD.

If I try the others examples of the url you sent me the error is the same:
 * Authenticate with token credentials
      ==> error on "credential = ServicePrincipalCredentials(tenant=tenant_id,client_id=client_id,secret=client_secret) "

 * Authenticate with token credentials and an ADAL context
      ==> error on " subscription = next(subscription_client.subscriptions.list()) "

I hope somebody already find out  or  develop this specific PYTHON code function...

**Comment by cladic** [comment]
I closed  the issue for mistake....Now it is opened again !

**Comment by RodgeFu** [comment]
@yungezz , do you have any insights from CLI side? thanks.

**Comment by yungezz** [comment]
HI @cladic do you attempt to auth with username/password like az login -u -p? seems it's deprecated in SDK based on doc shared by @lmazuel https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=bash#deprecated-authenticate-with-userpasscredentials. As alternative, you can login with azure cli, then use CLI auth https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=bash#cli-based-authentication-development-purposes-only
