### ISSUE TITLE
[Key Vault] InsecureRequestWarning

### ISSUE THREAD

**Issue by devigned** [Azure/azure-sdk-for-python#1162]
I think this commit caused the issue: https://github.com/Azure/azure-sdk-for-python/commit/b3a242dc513ce3dd53be2c0f0073acf36a7f1038#commitcomment-22093579.

We are seeing this crop up in Azure CLI.

```
az keyvault certificate list --vault-name vault_name
python3.5/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[
  {
    ...
  }
]
```

**Comment by lmazuel** [comment]
@schaabs I think David is right, the fix makes "verify" to `None` if the env variable are not set :/

@devigned I'm surprised you already see that? The CLI is not supposed to use 0.3.2 already. Is it?

**Comment by schaabs** [comment]
@lmazuel I think we need to revert both this change and the change prior to that until we have a better long term solution for managing session state.

**Comment by lmazuel** [comment]
what about using the code from requests:
```python
            # Look for requests environment configuration and be compatible
            # with cURL.
            if verify is True or verify is None:
                verify = (os.environ.get('REQUESTS_CA_BUNDLE') or
                          os.environ.get('CURL_CA_BUNDLE'))
```

**Comment by lmazuel** [comment]
Meaning, if the env variables are not set, set "True"

**Comment by lmazuel** [comment]
Because I just got a meeting with AzureStack and CLI team, and they will need this env variable for the CLI :/

**Comment by lmazuel** [comment]
@johanste @bganapa

**Comment by bganapa** [comment]
Yes, with that commit, verify is being sent as False :(

**Comment by devigned** [comment]
@lmazuel running on master the CLI is pulling this version of KV.

**Comment by lmazuel** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-python/pull/1163 for 0.3.3
