### ISSUE TITLE
Package tag per package

### ISSUE THREAD

**Issue by estensen** [Azure/azure-sdk-for-python#11623]
I would love to have tags for each package so you can list all the releases of a specific package

Trying to find all the releases is [time consuming](https://github.com/Azure/azure-sdk-for-python/issues/10595#issuecomment-633458327) since GitHub only shows [10 releases per page](https://github.com/Azure/azure-sdk-for-python/releases) and there are so many packages in this repo

Today packages are tagged with the package name + the package version

**Comment by lmazuel** [comment]
Hi @estensen 

As you say, we tag with the format "package_version", for example "azure-keyvault_4.1.0" so I'm not sure you would want different? Could you give an actual example?
Thank you,

**Comment by estensen** [comment]
If you could tag with `azure-keyvault` in addition to `azure-keyvault_4.1.0` it would be possible to list all versions of `azure-keyvault` instead of manually going through the list to find all the versions.

**Comment by weshaggard** [comment]
I think we are tagging the way you are requesting but github UI doesn't do a great job in showing tags, but you can do it from the command line:

```
> git tag -l azure-keyvault_*
azure-keyvault_0.2.0
azure-keyvault_0.3.0
azure-keyvault_0.3.1
azure-keyvault_0.3.2
azure-keyvault_0.3.3
azure-keyvault_0.3.4
azure-keyvault_0.3.5
azure-keyvault_0.3.6
azure-keyvault_0.3.7
azure-keyvault_1.0.0
azure-keyvault_1.0.0a1
azure-keyvault_1.0.0a2
azure-keyvault_1.0.0b1
azure-keyvault_1.1.0
azure-keyvault_4.0.0
azure-keyvault_4.1.0
azure-keyvault_prior-to-deletion
```

**Comment by weshaggard** [comment]
Reading your request again I think you were asking if we could also add a tag called "azure-keyvault" to all the releases, however that will not work as git tags can only point to a single sha. However with the command line you can list all the package version tags in the manor I suggested.

**Comment by estensen** [comment]
aha, didn't know that tags have to be unique

But back to the problem. Updating a package I have to find the changelog of al the packages between the version I'm updating from and to the version I'm updating to. It seems cumbersome to download the repo to use the command line. How would you go about doing this?

**Comment by weshaggard** [comment]
Isn't the change log on pypi.org enough for you to find the information? https://pypi.org/project/azure-keyvault/

**Comment by estensen** [comment]
Thanks! It works for manually checking, but not for Dependabot. Upgrading `azure-cosmos` from 3.1.2 to 4.0.0 it does not list the changes in the beta versions in between: 

<img width="662" alt="Screenshot 2020-05-25 at 10 37 57" src="https://user-images.githubusercontent.com/9142800/82795189-f100a380-9e73-11ea-82e3-28b028a3cf3d.png">

Not sure if this is a problem with Dependabot or the way the release notes are created.

**Comment by weshaggard** [comment]
Not sure either as the dependabot doesn't clearly identify how they are supposed to be structured. If we are down to just figuring out dependabot again lets close this issue and continue that conversation at https://github.com/Azure/azure-sdk-for-python/issues/10595.

**Comment by estensen** [comment]
sure!
