### ISSUE TITLE
get_effective_route_table is misleading

### ISSUE THREAD

**Issue by BenMatase** [Azure/azure-sdk-for-python#11634]
**Is your feature request related to a problem? Please describe.**
When looking through the documentation [here](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_04_01.operations.networkinterfacesoperations?view=azure-python#get-effective-route-table-resource-group-name--network-interface-name--custom-headers-none--raw-false--polling-true----operation-config-) about `networkmanagementclient.network_interfaces.get_effective_route_table`, I noticed that what it actually returns (after some object wrappers), are [EffectiveRoutes](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_04_01.models.effectiveroute?view=azure-python). I was expecting for a method like that to return the route tables that the network interface is associated with. The documentation even states that the route tables are returned when they are not: "Gets all route tables applied to a network interface."

**Describe the solution you'd like**
I think that the method should be renamed to `get_effective_routes` or something that indicates that the corresponding routes are being returned, not the route tables. The docs should also be updated.

**Describe alternatives you've considered**
Change the functionality to get the route tables or add another api, but I understand that is a lot to ask.

**Additional context**
I was looking at the api `v2020_04_01` docs and I checked a couple other versions, but they all seem to have this issue.

**Comment by timMSFT** [comment]
Closing. Please follow https://github.com/Azure/azure-rest-api-specs/issues/9589 for further updates.
