### ISSUE TITLE
[azure-mgmt-core] is_valid_resource_id returns True for invalid resource IDs

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#11658]
**Is your feature request related to a problem? Please describe.**
In https://github.com/Azure/azure-cli/issues/10641#issuecomment-581873193, Azure CLI receives an incorrect `--scope` `/subscriptions/{subscription_id}/resourceGroups/` which lacks the **resource group name**. It gets injected into the resource URL, thus corrupting the command. 

In order to fix it, I try to use `azure.mgmt.core.tools.is_valid_resource_id` to detect whether a `scope` is valid:

https://github.com/Azure/azure-sdk-for-python/blob/adf6471c6a987ce28b080bce099cfba1fbf3e02a/sdk/core/azure-mgmt-core/azure/mgmt/core/tools.py#L195

Unfortunately, `is_valid_resource_id` can't return the correct value for some edge cases like this.

A code snippet:

```py
from azure.mgmt.core.tools import parse_resource_id, is_valid_resource_id

res_ids = ['/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/rg1',
           '/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups',
           '/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/',
           '/subscriptions//resourceGroups/']

for res_id in res_ids:
    print(res_id)
    print(parse_resource_id(res_id))
    print(is_valid_resource_id(res_id))
    print()
```

Output:
```py
/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/rg1
{'subscription': '0b1f6471-1bf0-4dda-aec3-cb9272f09590', 'resource_group': 'rg1'}
True

/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups
{'subscription': '0b1f6471-1bf0-4dda-aec3-cb9272f09590'}
False

# The trailing slash makes is_valid_resource_id return True
/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/
{'subscription': '0b1f6471-1bf0-4dda-aec3-cb9272f09590', 'resource_group': ''}
True

# Empty subscription ID shouldn't be allowed
/subscriptions//resourceGroups/
{'subscription': '', 'resource_group': ''}
True
```

**Describe the solution you'd like**

1. No empty name `''` should be allowed when parsing a resource ID
2. `is_valid_resource_id` should return `False` for `/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/`

**Comment by lmazuel** [comment]
Hi @jiasli 
This part of the code has been written by the CLI team back in the days in msrestazure, and I ported it as-is in azure-mgmt-core. I have no knowledge of it, and also @RodgeFu told me that @changlong-liu will now take care of azure-mgmt-core.
Thanks!
