### ISSUE TITLE
How to set expiry of a blob?

### ISSUE THREAD

**Issue by anandchugh** [Azure/azure-sdk-for-python#11674]
We have a requirement to delete the blobs after certain time interval(lets say 2 days).
I am not able to see any settings like this. In azure queue we use similar functionality by setting time_to_live while pushing an item in queue. Is there a way to perform similare operation while uploading a blob or set time to live for all blobs at container level.

**Comment by amishra-dev** [comment]
Hi @anandchugh,
Deletion (part of lifecycle management) is supported through management plane operations, https://docs.microsoft.com/en-us/rest/api/storagerp/managementpolicies/delete is the REST API for it. @vinjiang are you aware of any management plane SDK for it?

**Comment by anandchugh** [comment]
> Hi @anandchugh,
> Deletion (part of lifecycle management) is supported through management plane operations, https://docs.microsoft.com/en-us/rest/api/storagerp/managementpolicies/delete is the REST API for it. @vinjiang are you aware of any management plane SDK for it?

Is it possible to add policy while creating container vis sdk?

**Comment by xiafu-msft** [comment]
Hi @anandchugh 

Currently it's impossible to add the policy via SDK, while we will discuss with service side to see if they can enable this in the future
