### ISSUE TITLE
why azure-storage is version -0.20.3?

### ISSUE THREAD

**Issue by guydou** [Azure/azure-sdk-for-python#1167]
I saw that azure-storage has already version 0.34.2, why if I `pip install azure` I get `azure-storage==0.20.3`

is that supposed to be like that?

Thanks

**Comment by lmazuel** [comment]
Hi @guydou 

Yes, it's expected, please read the discussion about the stable `azure` package 1.0.3 and the preview version 2.0.0rc6:
http://azure-sdk-for-python.readthedocs.io/en/latest/installation.html

We plan to release to stable 2.0.0 soon, this will simplify the situation. Sorry for the inconvenience.

**Comment by lmazuel** [comment]
Hi @guydou 
`azure` 2.0.0 is released, with version 0.34.2
Thanks again for the feedback!
