### ISSUE TITLE
[ServiceBus] Expand **kwargs in both sync and async APIs to improve intellisense

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#11685]
In current public async API, kwargs are not expanded which means only required parameters shows up when IDE/Editor try to do intellisense stuff -- auto-code-complete and hint.

To make intellisense work better, expand `(param, **kwargs)` to `(param1, *, kwarg1=default, kwarg2=default, ...)` in async APIs.

not applicable for sync due to the compatibility with py2.7

**Comment by richardpark-msft** [comment]
Short of being able to remove Python 2.7 perhaps we can introduce some newlines or something into the text between the individual keyword args? 

That would at least help with readability - it's a huge block of fairly undelimited text otherwise.

**Comment by KieranBrantnerMagee** [comment]
Bumping milestone as we're addressing this incrementally (redoing kwargs/typing as we touch components of the code) to continue tracking this work.
