### ISSUE TITLE
list_blob_names is slow on my storage, returns markers

### ISSUE THREAD

**Issue by sordonia** [Azure/azure-sdk-for-python#11687]
- **Package Name**: 
azure-storage-python

- **Package Version**:
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
 
- **Operating System**:
Ubuntu 18

- **Python Version**: 
3.6

**Describe the bug**
list_blob_names is extremely slow for a particular blob as it seems to be listing "markers" , never seen that before, I just call list_blob_names without num_results.

The response object is an empty list and a marker:

x-ms-date:Thu, 28 May 2020 15:43:56 GMT
x-ms-version:2019-02-02
/alsordon/phillytools
comp:list
delimiter:/
marker:2!472!MDAwMzA5IXByb2plY3RzL2luZm9uY2VzL2MxMF9yZXMxOC9wdC1yZXN1bHRzL2FwcGxpY2F0aW9uXzE1ODMzMDcxNTM4NjhfMzIzNjMvU3VwQ29uL2NpZmFyMTBfdGVuc29yYm9hcmQvSW5mb05DRXNfY2lmYXIxMF9yZXNuZXQxOF9scl8wLjVfZGVjYXlfMC4wMDAxX2Jzel8zMDcyX3RlbXBfMC41X2wxMl8xLjAwX2wxY3V0Ml8xLjAwX2wxMkkxY3V0XzEuMDBfbnNfNTEyX3Zhcl8wLjEwMF90cmlhbF8wX2Nvc2luZV93YXJtL2V2ZW50cy5vdXQudGZldmVudHMuMTU5MDM0ODMxOS5jb250YWluZXItZTc3OC0xNTgzMzA3MTUzODY4LTMyMzYzLTAxLTAwMDAwMiEwMDAwMjghMjAyMC0wNS0yNVQwMzo0Mzo0OS41NjEyMDg5WiE-
prefix:projects/infonces/
restype:container
2020-05-28 11:44:01 AM - DD https://alsordon.blob.core.windows.net:443 "GET /phillytools?restype=container&comp=list&prefix=projects%2Finfonces%2F&delimiter=%2F&marker=2%21472%21MDAwMzA5IXByb2plY3RzL2luZm9uY2VzL2MxMF9yZXMxOC9wdC1yZXN1bHRzL2FwcGxpY2F0aW9uXzE1ODMzMDcxNTM4NjhfMzIzNjMvU3VwQ29uL2NpZmFyMTBfdGVuc29yYm9hcmQvSW5mb05DRXNfY2lmYXIxMF9yZXNuZXQxOF9scl8wLjVfZGVjYXlfMC4wMDAxX2Jzel8zMDcyX3RlbXBfMC41X2wxMl8xLjAwX2wxY3V0Ml8xLjAwX2wxMkkxY3V0XzEuMDBfbnNfNTEyX3Zhcl8wLjEwMF90cmlhbF8wX2Nvc2luZV93YXJtL2V2ZW50cy5vdXQudGZldmVudHMuMTU5MDM0ODMxOS5jb250YWluZXItZTc3OC0xNTgzMzA3MTUzODY4LTMyMzYzLTAxLTAwMDAwMiEwMDAwMjghMjAyMC0wNS0yNVQwMzo0Mzo0OS41NjEyMDg5WiE- HTTP/1.1" 200 None
2020-05-28 11:44:01 AM - DD String_to_sign=GET

x-ms-client-request-id:0da62ca2-a0fa-11ea-a479-554857c9fd70
x-ms-date:Thu, 28 May 2020 15:44:01 GMT
x-ms-version:2019-02-02
/alsordon/phillytools
comp:list
delimiter:/
marker:2!400!MDAwMjU1IXByb2plY3RzL2luZm9uY2VzL2MxMF9yZXMxOC9wdC1yZXN1bHRzL2FwcGxpY2F0aW9uXzE1ODMzMDcxNTM4NjhfMzIzNjYvU3VwQ29uL2NpZmFyMTBfdGVuc29yYm9hcmQvU2ltQ0xSX2NpZmFyMTBfcmVzbmV0MThfbHJfMC41X2RlY2F5XzAuMDAwMV9ic3pfMzA3Ml90ZW1wXzAuNV90cmlhbF8wX2Nvc2luZV93YXJtL2V2ZW50cy5vdXQudGZldmVudHMuMTU5MDM0ODQyMC5jb250YWluZXItZTc3OC0xNTgzMzA3MTUzODY4LTMyMzY2LTAxLTAwMDAwMiEwMDAwMjghMjAyMC0wNS0yNFQyMjowNjo1NS40NzUzMDk4WiE-
prefix:projects/infonces/
restype:container

**Expected behavior**
list_blob_names just returns blob names reasonably fast, here it returns blob names but after a long time, listing those markers takes the most of it

**Comment by xiafu-msft** [comment]
Close this one since here is not the repo for this issue, there's a duplicate issue in the proper repo

**Comment by xiafu-msft** [comment]
https://github.com/Azure/azure-storage-python/issues/663
