### ISSUE TITLE
azure-mgmt-network nic creation bug

### ISSUE THREAD

**Issue by zabranskiy** [Azure/azure-sdk-for-python#1168]
```
...
    async_nic_creation = network_client.network_interfaces.create_or_update(
        RESOURCE_GROUP,
        NIC_NAME.format(idx),
        {
            'location': region,
            'ip_configurations': [{
                'name': IP_CONFIG_NAME,
                'public_ip_address': pip,
                'subnet': {
                    'id': subnet_id
                }
            }]
        }
    )
    return async_nic_creation.result()
```

When nic creation function was called I get this error:

```
Unexpected error <class 'msrestazure.azure_exceptions.CloudError'>: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/696ddac3-0528-4828-82e7-f78b444f4d11/providers/Microsoft.Network/locations/southcentralus/operations/a426275c-ee1b-4c8f-8e00-69fc1563012e?api-version=2017-03-01
  File "azure_main.py", line 305, in run_region
    regain_vms(region, compute_client, network_client, blob_service)
  File "azure_main.py", line 270, in regain_vms
    nic = create_nic(region, network_client, SUBNET_INFO.id, idx)
  File "azure_main.py", line 103, in create_nic
    return async_nic_creation.result()
  File "/home/haaleven/py3env/lib/python3.5/site-packages/msrestazure/azure_operation.py", line 473, in result
    self.wait(timeout)
  File "/home/haaleven/py3env/lib/python3.5/site-packages/msrestazure/azure_operation.py", line 486, in wait
    raise self._exception
```

After that I can not create VM.

pip3 freeze
```
azure==1.0.3
azure-batch==1.0.0
azure-common==1.1.5
azure-mgmt==0.20.2
azure-mgmt-batch==1.0.0
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.33.0
azure-mgmt-keyvault==0.30.0rc6
azure-mgmt-logic==1.0.0
azure-mgmt-network==1.0.0rc3
azure-mgmt-nspkg==2.0.0
azure-mgmt-redis==1.0.0
azure-mgmt-resource==0.31.0
azure-mgmt-scheduler==1.0.0
azure-mgmt-storage==0.31.0
azure-monitor==0.1.0
azure-nspkg==2.0.0
azure-servicebus==0.21.0
azure-servicemanagement-legacy==0.20.5
azure-storage==0.34.0
msrest==0.4.8rc1
msrestazure==0.4.7
```
If I delete nic before creation it is all ok. Earlier creation without deleting nic worked correctly.

**Comment by zabranskiy** [comment]
pip3 freeze
```
azure==1.0.3
azure-batch==1.0.0
azure-common==1.1.5
azure-mgmt==0.20.2
azure-mgmt-batch==1.0.0
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.33.0
azure-mgmt-keyvault==0.30.0rc6
azure-mgmt-logic==1.0.0
azure-mgmt-network==1.0.0rc3
azure-mgmt-nspkg==2.0.0
azure-mgmt-redis==1.0.0
azure-mgmt-resource==0.31.0
azure-mgmt-scheduler==1.0.0
azure-mgmt-storage==0.31.0
azure-monitor==0.1.0
azure-nspkg==2.0.0
azure-servicebus==0.21.0
azure-servicemanagement-legacy==0.20.5
azure-storage==0.34.0
msrest==0.4.8rc1
msrestazure==0.4.7
```

**Comment by lmazuel** [comment]
Hi @zabranskiy 

Yes, this is recent issue we found:
- Impact the CLI: https://github.com/Azure/azure-cli/issues/3330
- RestAPI definition: https://github.com/Azure/azure-rest-api-specs/issues/1220

Once the RestAPI meta-description is fixed, I will be able to release an update. In the meantime, you can specify `2016-12-01` as api_version, since I think it's an issue only in the latest meta-description (2017-03-01)
```python
network_client = NetworkManagementClient(credentials, subscription_id, api_version='2016-12-01')
```

FYI @tjprescott

**Comment by TihoElek** [comment]
Same use case as zabranskiy's

pip freeze:
azure (2.0.0rc6)
azure-batch (1.0.0)
azure-common (1.1.5)
azure-mgmt (0.30.0rc6)
azure-mgmt-batch (1.0.0)
azure-mgmt-common (0.20.0)
azure-mgmt-compute (0.30.0rc6)
azure-mgmt-keyvault (0.30.0rc6)
azure-mgmt-logic (1.0.0)
azure-mgmt-network (1.0.0rc3)
azure-mgmt-nspkg (2.0.0)
azure-mgmt-redis (1.0.0)
azure-mgmt-resource (0.30.0rc6)
azure-mgmt-scheduler (1.0.0)
azure-mgmt-storage (0.30.0rc6)
azure-nspkg (2.0.0)
azure-servicebus (0.20.3)
azure-servicemanagement-legacy (0.20.4)
azure-storage (0.33.0)
msrestazure (0.4.7)

Tried different values of 'api_version', but no luck.

`File "./provision/azure/cluster.py", line 800, in setup_nic
    return network_interface.result()
  File "/home/ubuntu/.virtualenvs/bastion_old/local/lib/python2.7/site-packages/msrestazure/azure_operation.py", line 473, in result
    self.wait(timeout)
  File "/home/ubuntu/.virtualenvs/bastion_old/local/lib/python2.7/site-packages/msrestazure/azure_operation.py", line 486, in wait
    raise self._exception
msrestazure.azure_exceptions.CloudError: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/0c59d161-9ab4-42ba-b6be-372a625f2a4a/providers/Microsoft.Network/locations/centralus/operations/10bd4198-3f2c-4bbf-831a-77d741c42d9f?api-version=2016-12-01`

**Comment by lmazuel** [comment]
Thank you @TihoElek, so it seems it's an old issue finally :/. I guess it is not necessary to try 2016-09-01, it will be probably the same :/

**Comment by zabranskiy** [comment]
@lmazuel Any updates? The error continues to affect the production script.

**Comment by lmazuel** [comment]
Hi @zabranskiy 
Unfortunately, this is in the Network team RestAPI hands now :(
Workaround would be to catch the exception, and to loop on a GET and wait for the provisionningState to become 'Succeeded'.

**Comment by zabranskiy** [comment]
Hi @lmazuel 
Thanks for the advice. I hope that they will soon fix the bug.

**Comment by yuwzho** [comment]
Also reproduced in version 2017-06-01

**Comment by fengzhou-msft** [comment]
New style SDK has fixed this.
