### ISSUE TITLE
azure-mgmt-rdbms docs missing

### ISSUE THREAD

**Issue by jmalobicky** [Azure/azure-sdk-for-python#1169]
The preview release of the MySQL and PostgresQL services within the rdbms has the package listed on pypi for the rdbms, but the link is broken (https://azure-sdk-for-python.readthedocs.io/en/latest/sample_azure-mgmt-rdbms.html)

**Comment by lmazuel** [comment]
Hi @jmalobicky 

Yes you're right, the package is released from the private repo, I will fix that asap.
Thanks for the report.

**Comment by lmazuel** [comment]
Hi @jmalobicky 

Now the doc from source code is on RTD:
http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.rdbms.mysql.html
http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.rdbms.postgresql.html

We are working on the samples.

Thank you,

**Comment by jmalobicky** [comment]
Thanks @lmazuel i noticed they were updated earlier in the day yesterday. Samples will be helpful :)

**Comment by kvnaveen7** [comment]
Need samples to implement.

**Comment by lmazuel** [comment]
@jmalobicky @kvnaveen7 There is some samples now here:
https://docs.microsoft.com/python/api/overview/azure/postgresql
https://docs.microsoft.com/python/api/overview/azure/mysql

Could you take a look, tell me if it's useful, and if not what kind of precise sample could help? Thanks!

**Comment by jmalobicky** [comment]
Thanks @lmazuel, I ended up going through the models and operations and building my own. I am good at the moment and my deployment is operational.

**Comment by lmazuel** [comment]
Thanks @jmalobicky !
I'm closing this, since I think the intial question is covered. Please open a new issue if you need specific scenarios as samples.
