### ISSUE TITLE
[ServiceBus] No session available after 60s timeout being classified as user error in Azure Portal

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#11690]
Our customer @MichaelWeedon has found that when trying to use NEXT_AVAILABLE to connect to a queue session while no session is available (triggering 60s timeout), the service side would classifies it as a user error leading to the service bus metrics of user error count in Azure Portal > 0.

Michael thinks this should not be counted as user error in Portal.

This is the service side behavior and @nemakam mentioned this would need service team discussion.

I'm opening this separate issue for better tracking the issue from service side.
My thoughts on this would be is it possible to make this configurable?

Related issue: https://github.com/Azure/azure-sdk-for-python/issues/10741

**Comment by nemakam** [comment]
@DorothySun216 , Could you please take this forward? Thanks.

**Comment by yunhaoling** [comment]
I'm closing issue since there is no active development and no customer is reporting since then
