### ISSUE TITLE
[CosmosDB] nested index query working through portal doesn't work via sdk

### ISSUE THREAD

**Issue by databasedav** [Azure/azure-sdk-for-python#11721]
- **Package Name**: azure-cosmos
- **Package Version**: 4.0.0
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.2

**Describe the bug**
Queries of the format described [here](https://docs.microsoft.com/en-us/azure/cosmos-db/index-overview#querying-with-indexes) (e.g. `SELECT location FROM location IN company.locations WHERE location.country = 'France'`) do not work using the sdk.

**To Reproduce**
```python
CHAT_CONFIG = {
    "id": "chat",
    "partition_key": azure.cosmos.PartitionKey("/id", version=1),
    "indexing_policy": {
        "indexingMode": "consistent",
        "excludedPaths": [{"path": "/*"}],
        "includedPaths": [{"path": "/moderators/user_id/?"}],
    },
}

container.query_items(
    f"select * from mod in chat.moderators where mod.user_id = '{user_id}'",
    partition_key=chat_id,
)
```
The above produces the following exception: `azure.cosmos.exceptions.CosmosHttpResponseError: (BadRequest) Message: {"errors":[{"severity":"Error","location":{"start":4294967295,"end":4294967295},"code":"SC2001","message":"Identifier 'chat' could not be resolved."}]}`. Here is a sample document:
```
{
    "id": "chat",
    "creator": "creator",
    "owner": "owner",
    "created": 1590606509648,
    "moderators": [
        {
            "user_id": "owner",
            "since": 1590606509648
        }
    ]
}
```

**Expected behavior**
Running this query from the azure portal works as expected and should work from the sdk.

I already raised this issue on the doc page [here](https://github.com/MicrosoftDocs/azure-docs/issues/55729#issue-625430945) but am reposting it here since it may be sdk specific. Thanks.

**Comment by annatisch** [comment]
@southpolesteve  - can you comment on whether the cosmos portal is doing any special manipulation of queries and whether this would work in the JS SDK?
If so I can dig deeper into why this is isn't working in Python.

**Comment by databasedav** [comment]
you mentioned a special manipulation that may be transforming this query; what is the alternative way to perform this query while utilizing the nested index? my goal is to efficiently check if a `user_id` is in the list of moderators for a given `chat_id` and found this query format in the docs but am not married to using it

**Comment by southpolesteve** [comment]
@databasedav Does it work if you hard code the value of `user_id` into the query? The only thing that looks off to me is the potential issue with the string interpolation. The error the backend returns makes it look like the query is *much* larger when it actually gets sent to the server. You can see that in the `start` and `end` values that get returned.

**Comment by databasedav** [comment]
@southpolesteve I'll post a full repro in a bit but the `user_id` isn't the issue since I used the same one to perform the query via the portal. Can you explain what the `start` and `end` values mean? Thanks.

**Comment by southpolesteve** [comment]
@databasedav Were you able to do a repro?

**Comment by databasedav** [comment]
Here is a full repro with `azure-cosmos==4.0.0`:

```python
import os
import uuid
import azure.cosmos

CONTAINER_NAME = 'chat_repro'

CHAT_CONFIG = {
    "id": CONTAINER_NAME,
    "partition_key": azure.cosmos.PartitionKey("/id", version=1),
    "indexing_policy": {
        "indexingMode": "consistent",
        "excludedPaths": [{"path": "/*"}],
        "includedPaths": [{"path": "/moderators/user_id/?"}],
    },
}

database = azure.cosmos.CosmosClient(
    os.getenv('COSMOS_URI'), os.getenv('COSMOS_KEY')
).get_database_client(os.getenv('DATABASE_NAME'))

database.create_container_if_not_exists(**CHAT_CONFIG)

chat_container = database.get_container_client(CONTAINER_NAME)

CHAT_ID = uuid.uuid4().hex
USER_ID = uuid.uuid4().hex

chat_container.create_item({'id': CHAT_ID, 'moderators': [{'user_id': USER_ID, 'since': 123}]})

for item in chat_container.query_items(
    f'select * from mod in {CONTAINER_NAME}.moderators where mod.user_id = @user_id',
    parameters=[{'name': '@user_id', 'value': USER_ID}],
    partition_key=CHAT_ID
):
    print(item)

```

At this point I'm wondering if this is even cost effective? I am currently just fetching the chat document and iterating through the moderator objects to check if a certain user is a moderator; is maintaining a separate index on the moderator user id even worth it if I expect the number of moderators to be around 20-30 max? Thanks!

**Comment by chrisyeh96** [comment]
@databasedav I think I'm facing a similar problem as you. See my issue #13519. Do you still have the same error if you set `enable_cross_partition_query=True` and remove the `partition_key` parameter from your call to `container.query_items()`? It's a hacky (and slow) workaround, but maybe it helps?

**Comment by southpolesteve** [comment]
@srinathnarayanan Can you look into this issue?

**Comment by srinathnarayanan** [comment]
@databasedav , @chrisyeh96 I verified that the nested index query succeeds when enableCrossPartitionQuery is True, and fails when a partition key is passed. This behavior is present in both the python and the .NET SDK, meaning it is a backend bug with our query infrastructure. Can you please raise a support ticket with Azure Cosmos DB from the portal? thanks!

**Comment by chrisyeh96** [comment]
@srinathnarayanan Wouldn't it be more effective if you raised a support ticket since you work at Microsoft?

**Comment by southpolesteve** [comment]
@chrisyeh96 Customer support tickets get higher priority than ones filed internally

**Comment by southpolesteve** [comment]
Closing as this issue is on the backed and needs to go through a support ticket. Please file one via the Azure Portal and reference this issue.

**Comment by databasedav** [comment]
filing technical support tickets through the portal requires a paid support plan which I don't have; does filing on the community support forums suffice?
