### ISSUE TITLE
Cannot set Service Bus Message ContentType 

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-sdk-for-python#11751]
- **Package Name**: azure-servicebus
- **Package Version**: 0.50.3
- **Operating System**: Windows 10 Enterprise
- **Python Version**: Python 3.8.1

**Describe the bug**
Original Thread: https://github.com/Azure/azure-functions-python-worker/issues/682

Thanks @allenc97, according to the documentation in the REST API https://docs.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties.
Attempt to create a message sending into service bus queue with **ContentType**, but the broker properties is not surfaced correctly.
![image](https://user-images.githubusercontent.com/48038149/83471214-f6905780-a438-11ea-815e-db00ad40ba27.png)

However, using the .NET Core counter part Microsoft.Azure.ServiceBus, the content type of a message can be set correctly.
![image](https://user-images.githubusercontent.com/48038149/83471196-eb3d2c00-a438-11ea-9cba-7e65a4619368.png)

In Portal, only the one with Microsoft.Azure.ServiceBus has the proper broker properties.
![image](https://user-images.githubusercontent.com/48038149/83471435-8930f680-a439-11ea-82fd-6d10f796dd5c.png)

**To Reproduce**
1. Follow the code in **Describe the bug** section.
2. Go to portal, peek the service bus message. The content type cannot be set and it is fixed to **application/xml; charset=utf-8**

**Expected behavior**
The content type should be set to **application/json**

**Screenshots**
Attached above

**Additional context**
Please let me know if I'm using the azure-servicebus package properly. I can't find any documentations around setting ContentType in azure-servicebus package.

**Comment by KieranBrantnerMagee** [comment]
Hey Hazhzeng,
Sorry you ran into this trouble;  you're not wrong that this isn't surfaced anywhere super obvious; the way you're setting broker_properties is for the legacy HTTP implementation of this library.

For 0.50, I would point you [here](https://docs.microsoft.com/en-us/python/api/uamqp/uamqp.message.messageproperties?view=azure-python#variables) namely at the content_type property; that you would access as such:
```python
message = Message("foo")
message.properties.content_type = "TEST"
# To answer your full post, this is the label field.  To preempt the inevitable; the naming is something we really need to improve on.
message.properties.subject = "LABEL" 
```

We intend to provide better guidance and visibility of these settings in the GA version of this library (currently in preview 7.0.0b3), but don't hesitate to reach out or reopen this if the above doesn't address your issue or if there are any further questions.  

Thanks as always for using the lib and reaching out to us.
