### ISSUE TITLE
Tag Azure Subscription via Python SDK?

### ISSUE THREAD

**Issue by chris-jaec** [Azure/azure-sdk-for-python#11777]
Is it possible to tag a subscription through the Python SDK? If yes, is there some documentation around this? I unfortunately could not find anything in the official Azure docs.

**Comment by kaerm** [comment]
Thanks for reaching out @chris-jaec, @nickzhums could you help out here?

**Comment by anuragdalmia** [comment]
Assigning this to @rthorn17 who is driving this.  Existing documentation for doing this is [here] (https://docs.microsoft.com/en-us/rest/api/resources/tags/createorupdateatscope#update-tags-on-a-subscription). I will let @rthorn17 talk about support for python SDK. 

@ramaganesan-rg to track this appropriately under Management Group

**Comment by ramaganesan-rg** [comment]
Removed "Subscription" tag. This should belong in Management Group

**Comment by zepptron** [comment]
any update on this? would be nice to have this

**Comment by donets420** [comment]
Hi team,
any updates?

**Comment by nickzhums** [comment]
@anuragdalmia @rthorn17 could you guys provide any updates?

**Comment by rthorn17** [comment]
Hi Everyone-  Refer to [https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_10_01/operations/_tags_operations.py](url)

get_at_scope()
create_or_update_at_scope()
update_at_scope()
delete_at_scope()

These four Tags operations in SDK you can specify **scope** parameter with the subscription. That way you can manage tags on subscription level.

**Comment by donets420** [comment]
@rthorn17 - your link to github doesn't work for me.

**Comment by rthorn17** [comment]
> @rthorn17 - your link to github doesn't work for me. It looks like MS internal?

See if it works now as I just updated it.  I don't know why but I was getting an error also with the same link
