### ISSUE TITLE
Unable to create get_client_from_cli_profile

### ISSUE THREAD

**Issue by pkvk14** [Azure/azure-sdk-for-python#11782]
Hi,

I am trying to manage azure resources via python but unable to create credentials from the CLI login.

Please share the steps.

**Comment by kaerm** [comment]
Thanks @pkvk14, @nickzhums could you take a look at this?

**Comment by lmazuel** [comment]
This might help as well:
https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd#cli-based-authentication-development-purposes-only

**Comment by pkvk14** [comment]
Thanks,

I want to create vm using python.

I have put my correct azure subscription still getting the error message.

$ C:/Users/pradeep/AppData/Local/Programs/Python/Python38/python.exe f:/Python_Lab/06_06_20/test.py
Traceback (most recent call last):
  File "f:/Python_Lab/06_06_20/test.py", line 6, in <module>
    subscription_id = os.environ["7065525-8726-4862-96f4-f536kl9"]
  File "C:\Users\pradeep\AppData\Local\Programs\Python\Python38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: '7065525-8726-4862-96f4-f536kl9'

**Comment by RodgeFu** [comment]
@LianwMS , please talk with Kaihui to provide some sample code for pkvk14. Thanks.

**Comment by RodgeFu** [comment]
@00Kai0  , please help to provide some sample code here for pkvk14. thanks.

**Comment by 00Kai0** [comment]
Hi @pkvk14 ,this error message means you don't set env value correctly.
According to the way you provide， you just need set `subscription_id = "7065525-8726-4862-96f4-f536kl9"`, if you don't want to get value from environment.
And this is a sample about creating vm: https://github.com/00Kai0/azure-playground/blob/master/samples/azure/createVM/track1.py#L75

**Comment by 00Kai0** [comment]
seems like no reply, I close it.
