### ISSUE TITLE
Azure Cosmos Module throws incorrect error type when not passing string for id item

### ISSUE THREAD

**Issue by Rabbit994** [Azure/azure-sdk-for-python#11793]
- azure-cosmos: 
- 4.0.0: 
- Windows 10 Enterprise 1909:
- Python 3.6.8: 

**Describe the bug**
When attempting to upsert an item where 'id' field is not set to string, you get AttributeError.

 While throwing error is correct in keeping with CosmosDB requirements that ID field be string, I believe TypeError in following with Python standards is more appropriate error.

https://docs.python.org/3/library/exceptions.html
Passing arguments of the wrong type (e.g. passing a list when an int is expected) should result in a TypeError

**To Reproduce**
from azure.cosmos import exceptions, CosmosClient, PartitionKey
import random
#CHANGEME
endpoint = "changeme"
key = "changeme"

client = CosmosClient(endpoint, key)

database_name = 'AzureSampleFamilyDatabase'
database = client.create_database_if_not_exists(id=database_name)

container_name = 'FamilyContainer'
container = database.create_container_if_not_exists(
    id=container_name, 
    partition_key=PartitionKey(path="/lastName"),
    offer_throughput=400
)
item = {"id": (random.randint(1,100000))} #this should be string but isn't
item['lastname'] = "Jones"
container.upsert_item(item) #Attribute Error raised

AttributeError: 'int' object has no attribute 'find'

**Expected behavior**
Since id is not string, I would expect ValueError in keeping with Python standards

**Comment by kaerm** [comment]
Thanks @Rabbit994 for posting the issue, @southpolesteve, @annatisch could you take a look at this

**Comment by Rabbit994** [comment]
File "C:\Users\rabbit\Python Projects\AzureCosmosDBTesting\.env\lib\site-packages\azure\cosmos\_cosmos_client_connection.py", line 2483, in __ValidateResource
    if id_.find("/") != -1 or id_.find("\\") != -1 or id_.find("?") != -1 or id_.find("#") != -1:
AttributeError: 'int' object has no attribute 'find'

There is exact error with line number to assist in debugging.

**Comment by annatisch** [comment]
Thank you @Rabbit994 - good call - I will get a PR out for this this week :)

**Comment by annatisch** [comment]
Thanks @Rabbit994 - this fix has been merged and will ship with the next release.
I'm not sure when that will be yet - I will close this issue once the release is out.

**Comment by annatisch** [comment]
This fix has now been released.
