### ISSUE TITLE
Match condition not being honored in Upsert item calls

### ISSUE THREAD

**Issue by aalapatirvbd** [Azure/azure-sdk-for-python#11791]
- **Package Name**: azure.cosmos
- **Package Version**: 4.0.0
- **Operating System**: osx
- **Python Version**: 3.8.1

**Describe the bug**
Upsert item function is ignoring the match_condition options. After looking at the code, found that the upsert_item method is ignoring the created request_options. 

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cosmos/azure-cosmos/azure/cosmos/container.py#L451 

Note that the `request_options` variable is not being passed to the subsequent `UpsertItem` call.

**To Reproduce**
1. Have two clients trying to update the same entry in a given cosmos db container and observe that the etag match_condition is not honored.

**Expected behavior**
The upsert call should be rejected with `azure.cosmos.exceptions.CosmosAccessConditionFailedError: (PreconditionFailed) Operation cannot be performed because one of the specified precondition is not met.,` error.

**Comment by aalapatirvbd** [comment]
Looks like the developer missed passing the request_options to the subsequent calls. I have made the change and verified the fix.  Will open a PR shortly.

**Comment by kaerm** [comment]
Thanks @aalapatirvbd for opening the issue, @annatisch @southpolesteve could you take a look at this

**Comment by annatisch** [comment]
Thanks for the report and investigation @aalapatirvbd!
Definitely looks like a bug - I will PR a fix.

**Comment by kaerm** [comment]
@annatisch, @aalapatirvbd already submitted a PR here: https://github.com/Azure/azure-sdk-for-python/pull/11792

**Comment by annatisch** [comment]
This fix has now been released in 4.1.0.
