### ISSUE TITLE
Azure SDK limitation while fetching app registrations.

### ISSUE THREAD

**Issue by ietashish** [Azure/azure-sdk-for-python#11817]
Our requirement is to list all the registered applications for a tenant. The response should also contain information about the owners of the application.
 
To do so, we currently had to resort to calling Graph REST API natively instead of using Python SDK API.
The Graph REST API allows us to pass 'expand' parameter [OData query parameters](https://docs.microsoft.com/en-us/graph/query-parameters) while calling API. So by calling,
 
`GET /applications?$expand=Owners`
 
we are effectively able to expand and join ‘Owners’ information with ‘application’.
 
The 'expand' parameter allows us to get owners of the application within the same API call. Without this we have to make one more API call to get owner for each application (once we have the list of applications from first API call) which is very time consuming.

However no such provision to pass ‘expand’ parameter exists in equivalent method in Python SDK. The API we would like to use is [this one](https://docs.microsoft.com/en-us/python/api/azure-graphrbac/azure.graphrbac.operations.applicationsoperations?view=azure-python#list-filter-none--custom-headers-none--raw-false----operation-config-). 
Strangely many other SDK methods for other Azure resources do provide provision for passing expand parameter but is missing from ‘list applications’.

**Comment by kaerm** [comment]
@ietashish thanks for reaching out, @nickzhums could you help out here

**Comment by nickzhums** [comment]
@RodgeFu to double check if python sdk misses this functionality

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
