### ISSUE TITLE
AzureCliCredential interrupts credential chain if Azure CLI is not logged in

### ISSUE THREAD

**Issue by mpderbec** [Azure/azure-sdk-for-python#11819]
- **Package Name**: azure-identity
- **Package Version**: 1.4.0b3
- **Operating System**: Windows
- **Python Version**: 3.7

**Describe the bug**
On Windows (haven't tried other OSes, but would expect the same), if the Azure CLI client is logged out, then the `AzureCliCredential` class will raise `ClientAuthenticationError`, which causes the credential chain to stop. A common need is to include `InteractiveBrowserCredential` as the final link in a chained credential, and this bug prevents it from being used.

**To Reproduce**
1. Use the following credential, which behind the scenes creates a chain:

```
        credential = identity.DefaultAzureCredential(
            exclude_shared_token_cache_credential=False,
            exclude_visual_studio_code_credential=False,
            exclude_cli_credential=False,
            exclude_interactive_browser_credential=False
        )
```

2. Make sure Visual Studio Code is logged out of Azure and that the Azure CLI is also logged out.
3. Use the `credential` for some purpose that would cause it to retrieve a token.

**Expected behavior**
I believe if the `AzureCliCredential` class were to raise `CredentialUnavailableError` instead, then the chain would continue.

**Additional context**
Found in the course of attempting to work around https://github.com/Azure/azure-sdk-for-net/issues/8934.

**Comment by kaerm** [comment]
@mpderbec thanks for reporting this, @chlowell could you take a look at this

**Comment by chlowell** [comment]
Thanks @mpderbec, this will be fixed in our next release.
