### ISSUE TITLE
Rename AnalyzeRequest to AnalyzeTextOptions, and add constructor overloads / helpers for required fields

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#11830]
Per discussion,

- [ ] Rename `AnalyzeRequest` to `AnalyzeTextOptions`. `SearchIndexClient.AnalyzeText` should look like: `AnalyzeText(string indexName, AnalyzeTextOptions options, ...)`.
- [ ] Add constructor overloads or other initialization helpers to require `text`, and either `analyer` or `tokenizer` (or, if you want, `analyzerName`, and `tokenizerName`, though I'll open up a separate issue for that).

```
class AnalyzeTextOptions {
  ctor(string text, LexicalAnalyzerName analyzer);
  ctor(string text, LexicalTokenizerName tokenizer);
  string text { get; }
  LexicalAnalyzerName? analyzer { get; }
  LexicalTokenizerName? tokenizer { get; }
  (remaining properties: { get; set; })
```

**Comment by xiangyan99** [comment]
Fixed in #11800
