### ISSUE TITLE
[Service Bus] 7.0.0b3 followup questions

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#11865]
- [ ] 1. Should msrestazure be removed from setup.py?
- [x] 2. should QueueDescription.created_at be renamed to created_at_utc?
- [x] 3. Add context manager to async ServiceBusManagementClient 
- [ ] 4. Access QueueDescription and QueueRuntimeInfo like dictionary
- [x] 5. Clean up control_client (Pin EH dependency to a legacy version, 0.50?)

**Comment by yunhaoling** [comment]
legacy control client already removed, eh using mgmt-eventhub for resource preparation now

**Comment by yunhaoling** [comment]
separate issue created for better tracking, closing this issue.
