### ISSUE TITLE
Timeframe for Azure Text Analytics 3.1 general availability

### ISSUE THREAD

**Issue by alexcombessie** [Azure/azure-sdk-for-python#11875]
Hi,

I have developed a Dataiku DSS plugin for Azure Cognitive Services Text Analytics: https://github.com/dataiku/dss-plugin-azure-cognitive-services-nlp.

This plugin used the `entities/recognition/pii` REST API endpoint. Unfortunately, this endpoint is still on the v3.1-Preview.1. I am looking at this [page](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/quickstarts/python).

Could you please share an approximate timeframe for general availability of the v3.1 API? 

Cheers,

Alex

**Comment by kristapratico** [comment]
@assafi could you comment on an approx timeframe?

**Comment by assafi** [comment]
I don't have specific timeframe, but we are hard at work on making sure it turns GA ASAP.

**Comment by alexcombessie** [comment]
Thanks! I have to say, I find the PII endpoint very promising. A unique selling point compared to other similar NLP-as-a-Service APIs.

**Comment by alexcombessie** [comment]
Hi @kristapratico !

I hope all is well. Do you have an update on the timeline?

Thanks,

Alex

**Comment by kristapratico** [comment]
Hi @alexcombessie - I don't have an update for you yet, but I'll be sure to post here when I do have information I can share. Thank you for being patient. :)

**Comment by assafi** [comment]
Not yet unfortunately. We will be having at least one additional preview iteration very soon, adding support for different offset interpretations (e.g. offsets in UTF8 code points vs code units) and built-in redaction capability. We also still need to iterate on the SDK itself. I would assume that it will be around the Fall of 2020 before we would GA it, but can't really give a hard date ATM.

**Comment by Petermarcu** [comment]
@assafi is there a channel where you would normally make these kinds of GA timeline details public. Wondering if we can just point to that. That way we don't need to keep an issue open tracking it and remember to update in both places.

**Comment by assafi** [comment]
@Petermarcu I don't believe we have such a channel externally.

**Comment by alexcombessie** [comment]
@assafi @Petermarcu I'm interested in the channel if you decide to create it!

**Comment by kristapratico** [comment]
Hi @alexcombessie, just letting you know that today we released the GA version of the Python Text Analytics client library (which includes the PII feature) - https://pypi.org/project/azure-ai-textanalytics/

Thanks for your patience! :)
