### ISSUE TITLE
List virtual machines with instance view

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1188]
Hi,

We are able to retrieve VM power state from **instance view** with get operation. Can we get the VM instance view from list virtual machines operation?

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS 

Unfortunately this is not possible right now... There is already an issue for that, so I'm closing this one. Issue: https://github.com/Azure/azure-sdk-for-python/issues/573

Please comment on this one as well, so I have more leverage to discuss with the Compute team :)

Thank you,
