### ISSUE TITLE
NetworkManagementClient not in azure.mgmt.network.network_management_client

### ISSUE THREAD

**Issue by tappoz** [Azure/azure-sdk-for-python#1189]
The `azure_rm.py` script on the `ansible` project is broken with the same message I reproduced in the following lines.

I've installed the network package like this: `pip install azure-mgmt-network==0.20.0`, then using `ipython` when I do:

```
In [1]: from azure.mgmt.network.network_management_client import NetworkManagementClient
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cd3844722fc4> in <module>()
----> 1 from azure.mgmt.network.network_management_client import NetworkManagementClient

ImportError: No module named network_management_client
```

So I went on the source code looking for that `network_management_client` and found out:
```
$ git clone https://github.com/Azure/azure-sdk-for-python
$ cd azure-sdk-for-python/azure-mgmt-network/azure
$ ipython
[...]
In [1]: from mgmt.network.v2017_03_01.network_management_client import NetworkManagementClient
```
and I was able to load it.

Not sure how the build/release procedure is here, but that `NetworkManagementClient` seems to be in the repo and somehow being removed when the package is released.

Cf. also: https://github.com/ansible/ansible/issues/24936

```
$ python --version
Python 2.7.13
$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
$ cat /etc/debian_version # using the test repository for deb packages
8.7
```

**Comment by lmazuel** [comment]
Hi @tappoz 

The [documentation of Ansible is asking for azure 2.0.0rc5](https://docs.ansible.com/ansible/guide_azure.html#requirements), meaning network 0.30.0rc5. We have an [open PR](https://github.com/ansible/ansible/pull/24710) at the Ansible level to support network 1.x.

The correct import for both 0.30.x version and 1.x version is:
```python
from azure.mgmt.network import NetworkManagementClient
```

Look to at network tutorials using this import, for instance https://github.com/Azure-Samples/network-python-manage-application-gateway

Thank you,
