### ISSUE TITLE
keyvault create certificates

### ISSUE THREAD

**Issue by madhukargilla** [Azure/azure-sdk-for-python#1192]
Hi,

The following link contains examples of both key and secret, can you please provide samples for certificates
https://azure-sdk-for-python.readthedocs.io/en/latest/sample_azure-keyvault.html#

to be more specific we are looking for examples for the following use-cases
1) Create a cert
2) Retrieve the public key
3) Retrieve the private key

Thanks -

**Comment by schaabs** [comment]
@madhukargilla Thanks for the feedback. I will create a new sample with details on certificate management in Key Vault for the python SDK.  However, Just to clarify the use case that you're outlining is not supported.  You cannot get the private key for a certificate created in key vault.  If you need access to the private key of a cert you would need to create the cert yourself and you can import the cert to key vault.

**Comment by Petermarcu** [comment]
@schaabs Is this addressed with the new docs you have been writing for the new library?

**Comment by AlexGhiondea** [comment]
Looks like this issue is by design. Please file a new issue if you still require assistance with this.

We are going to add a sample for this for our new Track2 library.

**Comment by jongio** [comment]
Docs here: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-certificates/4.2.0/index.html
Samples here: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-certificates/samples and here: https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/keyvault-certificates-samples/
