### ISSUE TITLE
azure BillingManagementClient is not working

### ISSUE THREAD

**Issue by Mahesh-git20** [Azure/azure-sdk-for-python#11920]
Hi,
{Code}
#correct values are given to get proper credentials
credentials = ServicePrincipalCredentials(client_id=client_id,secret=client_secret,tenant=tenant_id)
dd = BillingManagementClient(credentials,subscription_id,base_url=BASE_URL)
 if dd is None:
            print "Null billing object"
 df = dd.invoices.list()
res = dd.invoices.get_latest()
{/Code}

As per above python code snippet, billing client is created (non-null object).
Further both the functions list() or get_latest() fails with "Unauthorized" error.

get_latest() : error
......
    res = dd.invoices.get_latest()
  File ".....python27/lib/python2.7/site-packages/azure/mgmt/billing/operations/invoices_operations.py", line 241, in get_latest
    raise models.ErrorResponseException(self._deserialize, response)
**ErrorResponseException: Operation returned an invalid status code 'Unauthorized'**

Is there any way, to identify and resolve this unauthorized issue ?

BTW, with same credentials - I am able fetch all compute and usage resources.
UsageManagementClient(), ComputeManagementClient() -- these clients and their operations are working fine as expected.

Let me know, how to debug the billing issue and resolve it.
Thanks

**Comment by anand-rengasamy** [comment]
Only account admins can list/download invoices. for other users see https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/manage-billing-access to know how to give permissions to others.

Also, Can you try using the latest api version (https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/invoices)?

**Comment by Mahesh-git20** [comment]
@anand-rengasamy   : Thanks for your quick response.

On Azure portal - https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/manage-billing-access : I have enabled the options for "Allow others to download invoice" and saved the settings.
- Even after that, still I am getting the same error msg.
ErrorResponseException: Operation returned an invalid status code 'Unauthorized'

Further, I have updated the API-version to 2019-10-01-preview: as per below code snippet.
{code}
dd = BillingManagementClient(credentials,subscription_id,base_url=BASE_URL)
print dd.api_version
dd.api_version = "2019-10-01-preview"
dd.invoices.api_version = "2019-10-01-preview"
print dd.invoices.api_version
res = dd.invoices.get_latest()
{/code}

get_latest() function call fails with below error msg.
{output}
billing client api-version - 2018-03-01-preview
updated version - 2019-10-01-preview
billing invoice api-version - 2019-10-01-preview
**ErrorResponseException: (UnsupportedApiVersion) The HTTP resource that matches the request URI 'https://billingrp.trafficmanager.net/subscriptions/5e594148-461b-4875-89f9-2d7ef0a594e8/providers/Microsoft.Billing/invoices/latest' does not support the API version '2019-10-01-preview'.**

Looks to me, with latest API version I might need to do something, which I am missing.

**Comment by anand-rengasamy** [comment]
We are in process of releasing powershell sdk and CLI for latest api version. If you are using rest, you can list invoices using below method: 
GET https://management.azure.com/providers/Microsoft.Billing/billingAccounts/default/invoices?$filter=Properties/SubscriptionId+eq+%2**<subId>**%27&periodStartDate=2020-03-01T00:00:00.000Z&periodEndDate=2020-06-01T00:00:00.000Z&api-version=2019-10-01-preview

this will list invoices for given time period.

**Comment by anand-rengasamy** [comment]
GET https://management.azure.com/providers/Microsoft.Billing/billingAccounts/default/invoices?$filter=Properties/SubscriptionId eq 'subID'&periodStartDate=2020-03-01T00:00:00.000Z&periodEndDate=2020-06-01T00:00:00.000Z&api-version=2019-10-01-preview

**Comment by Mahesh-git20** [comment]
Thanks Anand for the reply.

Will try the operations with REST API and will update about the outcome.

**Comment by ramaganesan-rg** [comment]
closing the issue per comments above. you are welcome to reopen this if needed. thank you for your feedback!
