### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.storage.blob' with pip user install

### ISSUE THREAD

**Issue by planetmarshall** [Azure/azure-sdk-for-python#11947]
- **Package Name**: 
azure-storage-blob==12.3.1

- **Operating System**:
Windows Server 2016 (Hosted agent on Azure Pipelines)

- **Python Version**: 
3.8.3

**Describe the bug**

`ModuleNotFoundError: No module named 'azure.storage.blob'`

**To Reproduce**
1. pip install --user azure-storage-blob
2. Execute the following code in a script:
``` 
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient
```
**Expected behavior**
The module is successfully imported

**Additional context**
Output of `pip freeze`:

```
azure-common==1.1.25
azure-core==1.6.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-devops==6.0.0b2
azure-nspkg==3.0.2
azure-storage-blob==12.3.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
```

** Workaround **

Omit the `--user` flag from pip and do a global installation

**Comment by xiafu-msft** [comment]
Hi @planetmarshall 

It seems your issue has been resolved! We'd close this issue for now, feel free to reopen it is you have any question!
