### ISSUE TITLE
azure-mgmt-commerce: Missing tag

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-sdk-for-python#1195]
Hi!

While updating the Azure Python packages for SUSE, I noticed that ```azure-mgmt-commerce``` is not tagged in the git repository:

```bash
glaubitz@suse-laptop:~/upstream/azure-sdk-for-python> git tag |grep commerce
glaubitz@suse-laptop:~/upstream/azure-sdk-for-python>
```

Additionally, the package already seems to identify itself as 0.30.0 while PyPi has only 0.30.0rc6 [1] available:

```bash
glaubitz@suse-laptop:~/upstream/azure-sdk-for-python> grep VERSION azure-mgmt-commerce/azure/mgmt/commerce/version.py 
VERSION = "0.30.0"
glaubitz@suse-laptop:~/upstream/azure-sdk-for-python>
```

I'd say the package shouldn't identify with a stable version unless there has already been a stable version of said package.

> [1] https://pypi.org/project/azure-mgmt-commerce/#history

**Comment by glaubitz** [comment]
Aha, it seems this affects multiple packages which are officially not part of the SDK but developed externally:

- azure-mgmt-datalake-nspkg
- azure-mgmt-eventhub
- azure-mgmt-media
- azure-mgmt-notificationhubs
- azure-mgmt-nspkg
- azure-mgmt-powerbiembedded
- azure-mgmt-search
- azure-mgmt-servermanager
- azure-mgmt-servicebus
- azure-nspkg

**Comment by lmazuel** [comment]
Hi @glaubitz,

Yes, this is correct, this is old packages with no update I didn't re-release since I tag using package_version syntax.
I have to republish them anyway, since we now customize our wheel building. I keep this issue open until I re-release all of them.
Thanks!

**Comment by lmazuel** [comment]
Change this into a checklist, and removing nspkg
- [ ] azure-mgmt-commerce
- [ ] azure-mgmt-eventhub
- [ ] azure-mgmt-media
- [ ] azure-mgmt-notificationhubs
- [ ] azure-mgmt-powerbiembedded
- [ ] azure-mgmt-search
- [ ] azure-mgmt-servermanager
- [ ] azure-mgmt-servicebus

**Comment by lmazuel** [comment]
Closing this issue, now all packages have at least one tag!
Thanks!
