### ISSUE TITLE
azure-cosmos Readme and Samples Issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#11982]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cosmos/azure-cosmos#configure-a-virtual-environment-optional):
![image](https://user-images.githubusercontent.com/57166602/84359604-71a4fb00-abfb-11ea-8374-9aad3d41f411.png)

Suggestion:
Remove an extra 'your'.
2.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos#create-client):
![image](https://user-images.githubusercontent.com/57166602/84359842-ce081a80-abfb-11ea-97b2-98ab246410d2.png)

Suggestion:
Remove 'PartitionKey' and 'exceptions', because this code snippet not use them.
3.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos#create-a-database):
![image](https://user-images.githubusercontent.com/57166602/84360423-9d74b080-abfc-11ea-8438-097b1a1ee489.png)

Reason:
This code snippet is incomplete. The same problem in other code snippets, such as [Create a container](https://github.com/Azure/azure-sdk-for-python/tree/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos#create-a-container) , [Get an existing container](https://github.com/Azure/azure-sdk-for-python/tree/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos#get-an-existing-container) ,and so on.

Suggestion:
```
from azure.cosmos import CosmosClient, exceptions
import os

url = os.environ['ACCOUNT_URI']
key = os.environ['ACCOUNT_KEY']
client = CosmosClient(url, credential=key)
database_name = 'testDatabase'
try:
    database = client.create_database(database_name)
except exceptions.CosmosResourceExistsError:
    database = client.get_database_client(database_name)
```
4.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos#insert-data):
![image](https://user-images.githubusercontent.com/57166602/84360958-84203400-abfd-11ea-98b0-33753a75835a.png)

Reason:
Variable names is inconsistent. 

Suggestion:
Update 'database_client' to 'database'
Update 'container_client' to 'container'.

5.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos#delete-data):
![image](https://user-images.githubusercontent.com/57166602/84361818-d31a9900-abfe-11ea-84f5-1fe625358246.png)

Reason:
To set productModel = "DISCONTINUED" and  partition_key='Pager', it's not easy for beginners to understand. Because there is no item of this type created above.

Suggestion:
```
for item in container.query_items(query='SELECT * FROM products p WHERE p.productModel = "Model 2"',enable_cross_partition_query=True):
    container.delete_item(item, partition_key='Widget')
```
6.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cosmos/azure-cosmos#general):
![image](https://user-images.githubusercontent.com/57166602/84367549-f6e1dd00-ac06-11ea-9ad2-418a28cbb8ad.png)

Suggestion:
Add ')' at the end of the sentence.
7.
Script [link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cosmos/azure-cosmos/samples/examples.py#L62):
![image](https://user-images.githubusercontent.com/57166602/84366044-e3ce0d80-ac04-11ea-8eb1-0694b53ff60c.png)

Reason:
AttributeError: 'dict' object has no attribute 'id'

Suggestion:
Update "container.id" to "container['id']".
8.
Script [link](https://github.com/Azure/azure-sdk-for-python/blob/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos/samples/MultiMasterOperations/ConflictWorker.py#L645):
![image](https://user-images.githubusercontent.com/57166602/84368003-9dc67900-ac07-11ea-99f0-089a2f38dfcb.png)

Suggestion:
Update 'conflictCount' to 'conflict_count'.
9.
Script [link](https://github.com/Azure/azure-sdk-for-python/blob/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos/samples/MultiMasterOperations/ConflictWorker.py#L670):
There are the same problems in this [script](https://github.com/Azure/azure-sdk-for-python/blob/0385add4a893682534b1dba48ad13e1a26f2225b/sdk/cosmos/azure-cosmos/samples/MultiMasterOperations/ConflictWorker.py) on the following lines: Line 209, Line 247, Line 275,
Line 315, Line 411, Line 482.
![image](https://user-images.githubusercontent.com/57166602/84368148-c77fa000-ac07-11ea-9d77-27343f16d931.png)

Suggestion:
Remove extra ';' at the end of the sentence.

**Comment by kaerm** [comment]
Thanks @v-xuto, //cc: @southpolesteve and @annatisch

**Comment by v-xuto** [comment]
@jongio , notification of this issue.

**Comment by annatisch** [comment]
Thanks @v-xuto!

**Comment by eabase** [comment]
I still get error from the sample:

**`AttributeError: 'dict' object has no attribute 'query_items'`**

From:
```python
        for item in container.query_items(query=QSQL, enable_cross_partition_query=True):
            print(json.dumps(item, indent=True))
```

when using QSQL with:
```sql
SELECT list.id, list.name FROM c 
   JOIN configuration IN c.configuration 
   JOIN list IN configuration.list 
WHERE c.id = "documentTypes"'
```

In addition I get another error: 
**`ResourceWarning: unclosed <ssl.SSLSocket fd=324, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM`**

**Comment by AFengKK** [comment]
> 

@[eabase](https://github.com/eabase) Hello, we can't repro your error. Can you provide us with more code details:
1. What I wonder is why your `container` is a dict rather than a `containerproxy` object?
2. Did the version of [azure-cosmos](https://pypi.org/project/azure-cosmos/4.2.0/) package you used is 4.2.0?
3. Can you provide us with a simple data instance you insert through the `container.upsert_item()` method? 

For the another warning error, maybe you can ignore the relevant warnings through the warnings library.
```python
import warnings 
warnings.simplefilter("ignore", ResourceWarning)
```

**Comment by eabase** [comment]
@AFengKK  
Ah! Yes, I resolved it. The first error was due to a name space pollution from a previously itemized `container` variable. So please disregard. 

For the 2nd problem, thanks for the work around idea. 
(Still would be interesting why these SSL errors occur.)
