### ISSUE TITLE
AutoLockRenew doesn't work.  Failed to auto-renew lock: ServiceBusError('Management request failed: Failed to open mgmt link: MgmtOpenStatus.Error'). Closing thread.

### ISSUE THREAD

**Issue by berlogb** [Azure/azure-sdk-for-python#11983]
- **azure-servicebus**: 
- **0.50.3**: 
- **RHEL**:
- **3.7.7**: 

**Describe the bug**
Running debug example from here https://gist.github.com/KieranBrantnerMagee/e403c4f77f630d6664243dd52721fae3
results in the message expired exception

> Traceback (most recent call last):
>   File "", line 45, in <module>
>     message.complete()
>   File "/lib/python3.7/site-packages/azure/servicebus/common/message.py", line 329, in complete
>     self._is_live('complete')
>   File "/lib/python3.7/site-packages/azure/servicebus/common/message.py", line 101, in _is_live
>     raise MessageLockExpired(inner_exception=self.auto_renew_error)
> azure.servicebus.common.errors.MessageLockExpired: Message lock expired
> 

**To Reproduce**
` pip freeze | grep azu
azure-common==1.1.25
azure-servicebus==0.50.3
msrestazure==0.6.3`
1. pip install azure
2. Create a queue with default timeout set to 5 minutes
3. run the code referenced at the beginning

**Expected behavior**
AutoLockRenew shouldn't allow message to expire
**Screenshots**

**Additional context**
Debug logs:

> Traceback (most recent call last):
>   File "", line 45, in <module>
>     message.complete()
>   File "/lib/python3.7/site-packages/azure/servicebus/common/message.py", line 329, in complete
>     self._is_live('complete')
>   File "/lib/python3.7/site-packages/azure/servicebus/common/message.py", line 101, in _is_live
>     raise MessageLockExpired(inner_exception=self.auto_renew_error)
> azure.servicebus.common.errors.MessageLockExpired: Message lock expired
> 
> 
> 
> 
> Got Message: message_text
> 2020-06-11 11:42:12,209 azure.servicebus.common.utils DEBUG    Running lock auto-renew thread for 900 seconds
> 2020-06-11 11:47:02,536 azure.servicebus.common.utils DEBUG    10 seconds or less until lock expires - auto renewing.
> 2020-06-11 11:47:02,537 uamqp.c_uamqp INFO     b'-> [ATTACH]* {testqueue/$management-receiver,4,true,0,0,* {testqueue/$management},* {testqueue/$management},NULL,NULL,NULL,0}'
> 2020-06-11 11:47:02,537 uamqp.c_uamqp INFO     b'-> [ATTACH]* {testqueue/$management-sender,3,false,0,0,* {testqueue/$management},* {testqueue/$management},NULL,NULL,0,0}'
> 2020-06-11 11:47:02,537 uamqp.c_uamqp INFO     b'<- [FLOW]* {1,5000,3,65534,NULL,NULL,NULL,NULL,NULL,true,NULL}'
> 2020-06-11 11:47:02,537 uamqp.c_uamqp INFO     b"<- [DETACH]* {0,true,* {amqp:connection:forced,The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'a3782ab221fc4a219d323e949e20153e_G3'.,NULL}}"
> 2020-06-11 11:47:02,537 uamqp.c_uamqp INFO     b'-> [DETACH]* {0,true}'
> 2020-06-11 11:47:02,537 uamqp.c_uamqp INFO     CBS error occurred on connection b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'.
> 2020-06-11 11:47:02,538 uamqp.c_uamqp INFO     b"<- [DETACH]* {1,true,* {amqp:connection:forced,The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'a3782ab221fc4a219d323e949e20153e_G3'.,NULL}}"
> 2020-06-11 11:47:02,538 uamqp.c_uamqp INFO     b'-> [DETACH]* {1,true}'
> 2020-06-11 11:47:02,538 uamqp.c_uamqp INFO     b"<- [DETACH]* {2,true,* {amqp:connection:forced,The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'a3782ab221fc4a219d323e949e20153e_G3'.,NULL}}"
> 2020-06-11 11:47:02,538 uamqp.c_uamqp INFO     b'-> [DETACH]* {2,true}'
> 2020-06-11 11:47:02,538 uamqp.receiver INFO     Received Link detach event: b'amqp:connection:forced'
> Link: b'receiver-link-5b85c6d7-447c-4bc4-962d-bdbc35228522'
> Description: b"The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'a3782ab221fc4a219d323e949e20153e_G3'."
> Details: None
> Retryable: True
> Connection: b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'
> 2020-06-11 11:47:02,538 uamqp.receiver INFO     Message receiver b'receiver-link-5b85c6d7-447c-4bc4-962d-bdbc35228522' state changed from <MessageReceiverState.Open: 2> to <MessageReceiverState.Error: 4> on connection: b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'
> 2020-06-11 11:47:02,538 uamqp.c_uamqp INFO     b'<- [END]* {NULL}'
> 2020-06-11 11:47:02,538 uamqp.c_uamqp INFO     b'-> [END]* {}'
> 2020-06-11 11:47:02,539 uamqp.c_uamqp INFO     b"<- [CLOSE]* {* {amqp:connection:forced,The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'a3782ab221fc4a219d323e949e20153e_G3'.,NULL}}"
> 2020-06-11 11:47:02,539 uamqp.connection INFO     Connection b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168' state changed from <ConnectionState.OPENED: 9> to <ConnectionState.CLOSE_RCVD: 10>
> 2020-06-11 11:47:02,539 uamqp.c_uamqp INFO     b'-> [CLOSE]* {}'
> 2020-06-11 11:47:02,540 uamqp.connection INFO     Connection b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168' state changed from <ConnectionState.CLOSE_RCVD: 10> to <ConnectionState.END: 13>
> 2020-06-11 11:47:02,541 uamqp.connection INFO     Received Connection close event: b'amqp:connection:forced'
> Connection: b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'
> Description: b"The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'a3782ab221fc4a219d323e949e20153e_G3'."
> Details: None
> 2020-06-11 11:47:02,541 uamqp.c_uamqp INFO     b'SSL channel closed in decode_ssl_received_bytes.' (b'/data/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c':b'decode_ssl_received_bytes':797)
> 2020-06-11 11:47:02,541 uamqp.c_uamqp INFO     b'Error callback received in unexpected state' (b'/data/src/vendor/azure-uamqp-c/src/saslclientio.c':b'on_underlying_io_error':243)
> 2020-06-11 11:47:02,541 uamqp.c_uamqp INFO     b'Error in decode_ssl_received_bytes.' (b'/data/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c':b'on_underlying_io_bytes_received':846)
> 2020-06-11 11:47:02,541 azure.servicebus.common.utils DEBUG    Failed to auto-renew lock: ServiceBusError('Management request failed: Failed to open mgmt link: MgmtOpenStatus.Error'). Closing thread.
> 2020-06-11 11:52:12,300 uamqp.connection INFO     Shutting down connection b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'.
> 2020-06-11 11:52:12,301 uamqp.authentication.cbs_auth INFO     Shutting down CBS session on connection: b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'.
> 2020-06-11 11:52:12,301 uamqp.authentication.cbs_auth INFO     Auth closed, destroying session on connection: b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'.
> 2020-06-11 11:52:12,301 uamqp.authentication.cbs_auth INFO     Finished shutting down CBS session on connection: b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'.
> 2020-06-11 11:52:12,301 uamqp.c_uamqp INFO     b'send called while not open' (b'/data/src/vendor/azure-uamqp-c/src/saslclientio.c':b'saslclientio_send_async':1181)
> 2020-06-11 11:52:12,301 uamqp.c_uamqp INFO     b'Cannot send encoded bytes' (b'/data/src/vendor/azure-uamqp-c/src/connection.c':b'on_bytes_encoded':268)
> 2020-06-11 11:52:12,301 uamqp.c_uamqp INFO     b'saslclientio_close called while not open' (b'/data/src/vendor/azure-uamqp-c/src/saslclientio.c':b'saslclientio_close_async':1130)
> 2020-06-11 11:52:12,301 uamqp.c_uamqp INFO     b'xio_close failed' (b'/data/src/vendor/azure-uamqp-c/src/connection.c':b'on_bytes_encoded':272)
> 2020-06-11 11:52:12,301 uamqp.connection INFO     Connection b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168' state changed from <ConnectionState.END: 13> to <ConnectionState.END: 13>
> 2020-06-11 11:52:12,301 uamqp.c_uamqp INFO     b'-> [CLOSE]* {}'
> 2020-06-11 11:52:12,302 uamqp.connection INFO     Connection b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168' state changed from <ConnectionState.END: 13> to <ConnectionState.END: 13>
> 2020-06-11 11:52:12,302 uamqp.c_uamqp INFO     b'saslclientio_close called while not open' (b'/data/src/vendor/azure-uamqp-c/src/saslclientio.c':b'saslclientio_close_async':1130)
> 2020-06-11 11:52:12,302 uamqp.c_uamqp INFO     b'xio_close failed' (b'/data/src/vendor/azure-uamqp-c/src/connection.c':b'connection_close':1437)
> 2020-06-11 11:52:12,302 uamqp.connection INFO     Connection shutdown complete b'SBReceiver-07a0781c-6c1b-47fa-bbda-d637d6a1d168'.
> Traceback (most recent call last):
>   File "", line 45, in <module>
>     message.complete()
>   File "/lib/python3.7/site-packages/azure/servicebus/common/message.py", line 329, in complete
>     self._is_live('complete')
>   File "/lib/python3.7/site-packages/azure/servicebus/common/message.py", line 101, in _is_live
>     raise MessageLockExpired(inner_exception=self.auto_renew_error)
> azure.servicebus.common.errors.MessageLockExpired: Message lock expired

Could be related to the https://github.com/Azure/azure-sdk-for-python/issues/9144 , when tried adapted code with 7.0.0b3

> pip freeze | grep az
> azure-common==1.1.25
> azure-core==1.6.0
> azure-servicebus==7.0.0b3
> msrestazure==0.6.3

I see similar log messages but message.complete() doesn't through exception anymore (need to do double check that message is actually removed from the queue)

**Comment by KieranBrantnerMagee** [comment]
Hey @berlogb, thanks for making this really robust report.

I'm inclined to think you're hitting the same scenario [this other user](https://github.com/Azure/azure-sdk-for-python/issues/11611) ran across recently.  There was a bit of back and forth before we drilled down on the core issue so don't hesitate to just scroll to the bottom and see the suggested workaround.  In short, there are two problems to be aware of:
1.  If you were relying on a very long (5 minute) lock duration, we've observed clock skew sufficient to run-over the edge of the 5 minute allowance in this case.  We would recommend using a <5 minute max lock duration (<4 minutes, truthfully, as will be explained in #2)
2.  There is a service side idle timeout that only kicks in at 4 minutes, so if you were expecting to use a very long max lock duration and/or a corresponding renew_period, you may hit this as well. 

As such, the workaround for the other user was to have the lock duration set to <4 minutes (e.g. 3:30), with a renew_period set correspondingly shorter.  (Frankly, you shouldn't even need to change the default renew_period, and I don't even know if you'd been tweaking that parameter, just figured I'd preemptively mention in case you were, since it interacts with this as well as the service-side lock_duration)

I'd also mention we're looking at ways to improve this behavior for our 7.0 release [in this issue](https://github.com/Azure/azure-sdk-for-python/issues/11935)

Don't hesitate to loop back if this workaround doesn't help or if this answer doesn't apply to your scenario; and thanks again for reaching out.

**Comment by KieranBrantnerMagee** [comment]
Closing this with the hope/assumption that the prior response was useful; don't hesitate to reopen or reach out again if any further questions or issues with what was provided.

Thanks as always!
