### ISSUE TITLE
Deprovision Virtual Machine

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1199]
Hi,

I am planning to capture linux virtual machine using python sdk. As per the microsoft azure docs, VM need to deprovisioned and generalized before capture VM. Is there any api method available to deprovision and delete the user information using python sdk. or Is there any way to run the '**sudo waagent -deprovision**' command on VM using python sdk.

I can able to create the image without deprovisioning. But, if we use that image and try to create VM, the provisioning of VM failed. Please find that attached image for reference.
![azurevmerrorcapture](https://cloud.githubusercontent.com/assets/26897643/26584429/588af808-4566-11e7-881b-eef228ff4ddc.JPG)

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS 

You can execute a custom command using the Custom Script Extension:
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/extensions-customscript

This command is also available in the SDK, see this unittest to execute an extension on a VM:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_compute.py#L339-L354

**Comment by VikramAIS** [comment]
Hi @lmazuel ,

Using the custom script extensions I can able to run other commands but not the command  '**sudo waagent -deprovision**' as waagent service stops and deregister the VM. 

Is there any other ways to run the commands on VM other than customscripts?

Thanks,
Vikram

**Comment by lmazuel** [comment]
I don't think there is more way using the RestAPI. You can connect though SSH maybe and execute the command.
At this point, this is more a "Azure internals" than a Python SDK problem. You might want to ask on MSDN or StackOverflow directly a non-Python question like "how to execute my command on an ARM VM"?
