### ISSUE TITLE
DocumentDB list_connection_strings 

### ISSUE THREAD

**Issue by devigned** [Azure/azure-sdk-for-python#1200]
List connection strings doesn't list the same connection string as in the portal.

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-documentdb/azure/mgmt/documentdb/operations/database_accounts_operations.py#L651-L712

See also: https://github.com/Azure/azure-cli/issues/3507

**Comment by lmazuel** [comment]
Thanks @devigned.
As you said in the CLI text, we just proxy the RestAPI answer :). Guess it needs to be fixed at the RestAPI level :/

**Comment by devigned** [comment]
Anytime. I tagged a couple CosmosDB folks on the CLI issue.

**Comment by devigned** [comment]
Turns out that the connection string works, though it is different than the portal.

I didn't have my cacerts updated on my deployment, so the connection was failing SSL peer verification.

**Comment by lmazuel** [comment]
@devigned should be close then?

**Comment by devigned** [comment]
It's still not they way it is shown in the Portal and that causes me concern.

**Comment by devigned** [comment]
On second though, let's close this here. We'll track it in the CLI repo.
