### ISSUE TITLE
Copy or Clone Instance

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1201]
Hi, 

Is there any way to copy or clone instance programantically?

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi,

I think I would go with the [snapshot operations](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.compute.compute.v2016_04_30_preview.operations.html#azure.mgmt.compute.compute.v2016_04_30_preview.operations.SnapshotsOperations).
