### ISSUE TITLE
Access user's profile (first name, last name, etc.) through azure-graphrbac

### ISSUE THREAD

**Issue by mauroka** [Azure/azure-sdk-for-python#1202]
Hello, is there a way to access the user's profile using azure-graphrbac.
The data I'd like to access is the first name and last name.

If this is not possible using azure-graphrbac, what other alternatives are there?
Thanks a lot for the help.
Mauro.

**Comment by lmazuel** [comment]
Hi @mauroka 

I didn't try myself directly, but it seems it's possible.[ Create a graphrbac client](http://azure-sdk-for-python.readthedocs.io/en/latest/graphrbac.html), then use the [client.users.get](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.graphrbac.operations.html#azure.graphrbac.operations.UsersOperations.get) method to get a [User](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.graphrbac.models.html#azure.graphrbac.models.User). This class contains:

- object_id (str) – The object ID.
- object_type (str) – The object type.
- user_principal_name (str) – The principal name of the user.
- display_name (str) – The display name of the user.
- sign_in_name (str) – The sign-in name of the user.
- mail (str) – The primary email address of the user.
- mail_nickname (str) – The mail alias for the user.

This obj doesn't seem to do a difference between "fist name" and "last name", but it's the closest I have. @yugangw-msft can we get this level of detail?

**Comment by mauroka** [comment]
Hi @lmazuel , @yugangw-msft,
here are the changes to make to graphrbac/models/user.py to get this running.

@@ -39,9 +39,11 @@
         'sign_in_name': {'key': 'signInName', 'type': 'str'},
         'mail': {'key': 'mail', 'type': 'str'},
         'mail_nickname': {'key': 'mailNickname', 'type': 'str'},
+        'first_name': {'key': 'givenName', 'type': 'str'},
+        'last_name': {'key': 'surname', 'type': 'str'},
     }
 
-    def __init__(self, object_id=None, object_type=None, user_principal_name=None, display_name=None, sign_in_name=None, mail=None, mail_nickname=None):
+    def __init__(self, object_id=None, object_type=None, user_principal_name=None, display_name=None, sign_in_name=None, mail=None, mail_nickname=None, first_name=None, last_name=None):
         self.object_id = object_id
         self.object_type = object_type
         self.user_principal_name = user_principal_name
@@ -49,3 +51,5 @@
         self.sign_in_name = sign_in_name
         self.mail = mail
         self.mail_nickname = mail_nickname
+        self.first_name = first_name
+        self.last_name = last_name

I've test it myself. Could you please test it and get this in the next commit? Can I help you with this is?
Thanks a lot.
Mauro.

**Comment by lmazuel** [comment]
Hi @mauroka 

I can't accept direct Python code here, because this file is auto-generated from a Swagger file (JSON meta-description of the RestAPI)
I created an issue for the GraphRBAC team to fix the Swagger file asap, so I can regenerate and you get the missing attribute. https://github.com/Azure/azure-rest-api-specs/issues/1282
Keep this issue open in the meantime.

Thanks!

**Comment by mauroka** [comment]
Hi @lmazuel ,
Great! Thanks a lot.

**Comment by lmazuel** [comment]
Release after 0.32.0
