### ISSUE TITLE
[Data Factory] Unable to preserve metadata with Data factory v2 blob to blob CopyActivity

### ISSUE THREAD

**Issue by nikhil-lunawat** [Azure/azure-sdk-for-python#12050]
- **Package Name**: azure-mgmt-datafactory
- **Package Version**: 0.10.0
- **Operating System**: Linux
- **Python Version**: 3.8.2

**Describe the bug**
Preserve metadata is not getting updated in copy activity with below code. As this is for automation, manually adding preserve element from data factory from UI is not feasible.
blob_source = BlobSource()
blob_sink = BlobSink()
dsin_ref = DatasetReference(reference_name=source_ds_name)
dsOut_ref = DatasetReference(reference_name=target_ds_name)
copy_activity = CopyActivity(name=act_name, inputs=[dsin_ref], outputs=[dsOut_ref], source=blob_source, sink=blob_sink, preserve=["Attributes"])

As preserve element is not getting updated, blob metadata and properties is not getting copied for blob to blob copy.

**To Reproduce**
Followed https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-python.
Added preserve parameter in CopyActivity

**Expected behavior**
Preserve element in blob CopyActivity should have "Attributes"

**Screenshots**
![adf](https://user-images.githubusercontent.com/36477776/84671638-40069980-af45-11ea-883b-196bc07c2447.png)

**Comment by lmy269** [comment]
@shawnxzq, can you take a look?

**Comment by shawnxzq** [comment]
"preserve" is not supported properties in copy activity, we don't allow arbitrary properties and it's by design.

**Comment by changlong-liu** [comment]
Hi @shawnxzq , thank you!
