### ISSUE TITLE
Python dev packages don't have correct version suffix 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#12075]
Python version [guidelines](https://github.com/Azure/azure-sdk/blob/master/docs/policies/releases.md#python) specify dev versions as being `X.Y.Z.devYYYYMMDDrrr` 

However, for packages that have beta versions specified on the package, the generated version is `X.Y.ZbN.devYYYYMMDDrrr` .. The `bN` portion is extra. It should be `X.Y.Z.devYYYYMMDDrrr` per the policy. 

Example beta package in dev feed: https://dev.azure.com/azure-sdk/public/_packaging?_a=package&feed=azure-sdk-for-python&package=azure-ai-formrecognizer&protocolType=PyPI&version=1.0.0b4.dev20200615001

**Comment by praveenkuttappan** [comment]
This requires an update in guidelines. Python version comparison requires dev version to be appended to actual version so version comparison works fine. If z dev version for preview version X.Y.Zb1 is set to X.Y.Z.devYYYYMMDDrrr then this dev version will be considered latest even if preview version is released. To comply with this comparison logic, we have set dev version to X.Y.ZbN.devYYYYMMDDrrr. I will update the guidelines.
@danieljurek

**Comment by praveenkuttappan** [comment]
Discussed with Wes,. This needs to be revisited to keep dev version uniform across all languages. Current formatting is to keep it as per PEP 440 and to run import all test without making changes in package requirement, We should try to update version as per azure-sdk dev versioning guideline and update package requirement to pin dev version to run import test.

**Comment by scbedd** [comment]
This is actually completed.

![image](https://user-images.githubusercontent.com/45376673/94503045-641b7d00-01ba-11eb-9376-8dd76357eb2b.png)
