### ISSUE TITLE
azure-servicebus Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#12085]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#timeouts):
![image](https://user-images.githubusercontent.com/57166602/84858738-54aa7500-b09e-11ea-8663-f69ff03730d8.png)

Suggestion:
Update "occuring" to "occurring",
Update "aformentioned" to "aforementioned".

**Comment by v-xuto** [comment]
@jongio, for notification.

**Comment by KieranBrantnerMagee** [comment]
This went in with the aforementioned commit, should be addressed.  Thanks again for reaching out!
