### ISSUE TITLE
Capability to create Analytical Store enabled containers

### ISSUE THREAD

**Issue by Rodrigossz** [Azure/azure-sdk-for-python#12084]
**Is your feature request related to a problem? Please describe.**
To provide parity with .NET and Python V3 SDKs: https://docs.microsoft.com/en-us/azure/cosmos-db/configure-synapse-link#net-sdk

**Describe the solution you'd like**
Just another option on the API Call.

**Additional context**
As discussed in our emails. It will provide and end to end Python Experience for Analytical Store/Synapse Link, reaching Data Scientists and Data engineers.

**Comment by annatisch** [comment]
This feature has been added to 4.1.0, now released.
