### ISSUE TITLE
List compute Plans

### ISSUE THREAD

**Issue by krimkus** [Azure/azure-sdk-for-python#1209]
For certain images, we are receiving an error when provisioning Virtual Machines:

    Azure Error: VMMarketplaceInvalidInput Message: Creating a virtual machine from Marketplace image requires Plan information in the request.

VirtualMachines have a [parameter for Plan](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/compute/v2016_04_30_preview/models/virtual_machine.py#L31). And I see [a model for Plan](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/compute/v2016_04_30_preview/models/plan.py), but no operations.

How can we list available plans so we know what information to pass to the VirtualMachine's create_or_update()? 
How can we know which images require a plan? It looks like the VirtualMachineImage model has a plan parameter, but does that mean there is only one valid plan for that image?
For images that require a plan, how can we see which plans are valid for that image?

**Comment by lmazuel** [comment]
Hi @krimkus !
I don't know myself, @derekbekoe have you support for that in the CLI?

**Comment by derekbekoe** [comment]
Here's a related CLI issue - https://github.com/Azure/azure-cli/issues/1209.
@tjprescott may be able to provide more info.

**Comment by lmazuel** [comment]
@yugangw-msft anything I should do at the SDK level? It seems the CLI one is closed.

**Comment by lmazuel** [comment]
(didn't mean to close it)

**Comment by yugangw-msft** [comment]
@lmazuel, nothing you should do at SDK level.

The [image show](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-04-01/compute.json#L760) will return you the plan information, and when you create the VM, ensure you propagate the same information to VM's plan model, then you are all set.

**Comment by lmazuel** [comment]
Thank you @yugangw-msft ! Closing since we have the correct way to do it :)
Thanks again!
