### ISSUE TITLE
[COSMOS Account] Network FW Configuration is rudementary/lacking

### ISSUE THREAD

**Issue by mw-root** [Azure/azure-sdk-for-python#12099]
There does not appear to be any way to set the firewall to a whitelisting settup without defining CIDRs. (only allow selected networks in the portal).

We're stuck with wide open access, when we want to lock it down and add networks and ranges as required.

IPs are also ingested via CSV string which is ok, but very basic.

The storage account SDK has a [suitable solution.](https://docs.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.v2019_06_01.models.networkruleset?view=azure-python) The NetworkRuleSet object allows you to set default action to 'Allow' or 'Deny' and the IPRule allows you to define IPs/Ranges with 'allow' or 'deny'.

I've tried creating an empty list, or even with 0.15.0 using an empty IPRule but it returns a 400 from the rest API.

**Comment by shurd** [comment]
Hi @mw-root thank you for opening this issue. Today, we added the ipRules property in 0.15.0, which should allow you to add IP addresses as an array of object.

Alternatively, if you want to deny all public access to your account until the proper firewall rules are in place, you can use the property "publicNetworkAccess". If set to "Disabled", all requests are denied by default.

**Comment by shurd** [comment]
I am going to close this issue as there are no further questions. If you are still encountering issues using ipRules, please open a new issue or support ticket via the Azure portal.
