### ISSUE TITLE
[Cosmos] GROUP BY query support

### ISSUE THREAD

**Issue by southpolesteve** [Azure/azure-sdk-for-python#12096]
Need to add GROUP BY support to the Python SDK. JS SDK PR for reference https://github.com/Azure/azure-sdk-for-js/pull/5749

**Comment by banderous** [comment]
Can you please make it clear in your [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-group-by) that your client libraries are not feature complete?

I have just wasted a lot of development time finding out that your client library doesn't support GROUP BY (I cannot fathom why a query engine feature should require client library support anyhow).

**Comment by Rodrigossz** [comment]
@banderous , We will do it. Tks for the suggestion.

**Comment by Rodrigossz** [comment]
Done here: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cosmos/azure-cosmos#limitations

**Comment by falcu** [comment]
Is there any plan to support this?

**Comment by Rodrigossz** [comment]
Yes. No ETA for now. @simorenoh  can add more details.
