### ISSUE TITLE
Add "Available Transports" to Core dev doc

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#12121]
With the table of kwarg/operation level, like we did for Available Policies:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#available-policies

See also #12102 (customer was looking for "session" kwargs in the RequestTransport)

**Comment by jbulow** [comment]
The `session` parameter is still not visible in the documentation.
