### ISSUE TITLE
[Brainstorm] Make advanced kwargs discoverable

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#12122]
See #12102 , no-one can guess what kwargs are available just looking at the doc.

We have the content already:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#available-policies

How do we make it available for each client? A "aka.ms/options" in all client docstring? Else?

One thing for sure is I don't want to hard-code it, especially since most of these options depends on the version of azure-core, so hard-coding the code makes no sense since the availability will be dependent on the version of installed azure-core, not the installed actual service package.

**Comment by xiangyan99** [comment]
Now we have https://aka.ms/azsdk/python/options for the advanced kwargs. This always points to the latest core.

We also have https://aka.ms/azsdk/python/options/1.9 for v1.9 core, https://aka.ms/azsdk/python/options/1.8 for v1.8 core, etc.

**Comment by lmazuel** [comment]
This is great, now how to we plug those links into various SDKs?

**Comment by xiangyan99** [comment]
IMO, if some kwargs are supported in ctor or per-method call, we can add the link in our docstring.

And of course, SDK developers can choose to opt in or not.

**Comment by lmazuel** [comment]
We shall make this higher, maybe in guidelines directly @johanste that all SDKs should have a link in there docstring to the kwargs of azure-core.

Then, once we have guidelines officially supporting your links, create per service issue that everybody should fix their own service with it.

Thoughts?

**Comment by xiangyan99** [comment]
Gentle ping... @johanste :)

**Comment by xiangyan99** [comment]
We created https://aka.ms/azsdk/python/options and encourage SDK developers to add it in docstring. (added into guideline in https://github.com/Azure/azure-sdk/pull/2555)
