### ISSUE TITLE
[formrecognizer] [ service bug] Unsupported media type error

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#12125]
Service returns "Unsupported media type" error when pdf form is sent via GitHub URI. This error only occurs with recognize custom forms without labels.

**Comment by kristapratico** [comment]
ETA FR v2.1-Preview.2

**Comment by catalinaperalta** [comment]
This issue should be resolved in v3.2-beta since content type is detected automatically.
