### ISSUE TITLE
azure-ai-formrecognizer : copy a custom model ,when target_region = 'EastUS', running the code will be hung here.

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#12134]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 1.0.0b4.dev20200615001
- **Operating System**: win10
- **Python Version**: 3.7.4

**Describe the bug**
Sample [sample_copy_model.py](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_copy_model.py):
When target_region = 'eastus', the result of this sample code is pass,
When target_region = 'EastUS', running the sample code will be hung here.

**Expected behavior**
When target_region = 'EastUS', the result of this code is pass,

**Comment by v-xuto** [comment]
@jongio , for notification.

**Comment by kristapratico** [comment]
Thanks @v-xuto I'll look into this issue.

**Comment by kristapratico** [comment]
Update: reported this to the service team and they confirmed a fix is coming.
