### ISSUE TITLE
Application Properties are not part of event

### ISSUE THREAD

**Issue by NayangiriGoswamiGit** [Azure/azure-sdk-for-python#12135]
I route IoTHub Device Telemetry messages to its default events end point.
Than it triggers serverless function written in python with IotHub's eventhub binding.
The received event in azure serverless function does not contain application properties which has been set by device.
Here is code:
```
import azure.functions as func

def main(events: func.EventHubEvent):
    event_body = event.get_body().decode('utf-8')
```

When I do dir(event), it shows me,
['EventHubEventbody', '_EventHubEventenqueued_time', '_EventHubEventiothub_metadata', '_EventHubEventoffset', '_EventHubEventpartition_key', '_EventHubEventsequence_number', 'abstractmethods', 'class', 'delattr', 'dict', 'dir', 'doc', 'eq', 'format', 'ge', 'getattribute', 'gt', 'hash', 'init', 'init_subclass', 'le', 'lt', 'module', 'ne', 'new', 'reduce', 'reduce_ex', 'repr', 'setattr', 'sizeof', 'slots', 'str', 'subclasshook', 'weakref_', '_abc_impl', 'enqueued_time', 'get_body', 'iothub_metadata', 'offset', 'partition_key', 'sequence_number']

Which does not show application_properties anywhere.

**Comment by chunyu3** [comment]
The package azure.functions is not mgmt, seems it is data-plan. Add service team to look at it. thanks.

**Comment by lmazuel** [comment]
Issue moved to [Azure/azure-functions-python-worker #698](https://github.com/Azure/azure-functions-python-worker/issues/698) via [**ZenHub**](https://www.zenhub.com/)
