### ISSUE TITLE
[BUG] weird / flaky behavior in the Python CIs

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#12151]
Running into flaky failures that I can't repro locally. The failures are different across the different matrices:

1. for linux 2.7 I had coverage errors like [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=433858&view=logs&j=24e84196-b4b8-5123-c7ea-5e853df7a17a&t=9348bb1d-06b8-5827-b532-d0a0d6f8589e) (sdist and whl commands passed for mgmt, but then I got a ton of Coverage.py warnings for data plane and the whole command ended up failing)
2. for [linux 3.8](https://dev.azure.com/azure-sdk/public/_build/results?buildId=433858&view=logs&j=79d4d8df-e8a9-5bb0-89e9-dbeb29a5038e&t=761375b9-fd67-58cb-75dc-d11d69ad3ad1) I ran into "Visible uncombined .coverage files"
3. for [windows 3.5](https://dev.azure.com/azure-sdk/public/_build/results?buildId=433858&view=logs&j=be2373b3-6b66-526b-20b8-841c5ec5eb4b&t=27b6da23-3544-58b2-e3ed-4b7a28f27d9a) I ran into a permission error of "the process cannot access the file because it is being used by another process"

I've tried re-running, and some errors no longer occur. I've seen this behavior in three of my key vault PRs, but it seems like it's happening in pretty much all of the python pipelines ([here's](https://github.com/Azure/azure-sdk-for-python/pull/12148) a failing core PR, thanks Charles!)

**Comment by iscai-msft** [comment]
@kristapratico added she's seeing these errors: https://teams.microsoft.com/l/message/19:59dbfadafb5e41c4890e2cd3d74cc7ba@thread.skype/1592843100575?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1592843100575&teamName=Azure%20SDK&channelName=Engineering%20System%20%F0%9F%9B%A0%EF%B8%8F&createdTime=1592843100575

**Comment by scbedd** [comment]
This ALL boils down to `virtualenv` updates that break us. Temporarily pinning to `20.0.23` to more fully understand why `20.0.25` doesn't work for us.
