### ISSUE TITLE
tutorial of form recogniser training results in invalid model?

### ISSUE THREAD

**Issue by agiokas-dbg** [Azure/azure-sdk-for-python#12165]
- **azure-ai-formrecognizer**: 
- **1.0.0b3**: 
- **Ubuntu 18.04**:
- **3.6.9**: 

**Describe the bug**
I'm following the example for training a form recogniser, and yet all I get is invalid models.
The error indicates that there are no labels.
I'm using the example from [the pip package](https://pypi.org/project/azure-ai-formrecognizer/)
with a copy-paste, just changing `endpoint`, `api key` and `container sas` urls.

**To Reproduce**
Just try the example (as linked above) with the folder hierarchy I've described.

**Expected behaviour**
I would expect to have a trained valid list of models, since that is the behaviour when I use the UI.

**Screenshots**
This is the actual container structure, each folder has the PDF, the OCR json, and the LABEL json files.
At the root, there's also the project file (`.fott`).

![azure_container](https://user-images.githubusercontent.com/54706293/85431693-c6406280-b579-11ea-8e32-2cf59375ff88.png)
![azuire_container_subfolder](https://user-images.githubusercontent.com/54706293/85431698-c7718f80-b579-11ea-997f-90576332c858.png)

Unless I've miss-understood the directory structure?

**Comment by kristapratico** [comment]
Hi @agiokas-dbg 

To train with labels, pass in the `use_training_labels` parameter into the `begin_training` method:

```
from azure.ai.formrecognizer import FormTrainingClient
from azure.core.credentials import AzureKeyCredential

endpoint = "https://<region>.api.cognitive.microsoft.com/"
credential = AzureKeyCredential("<api_key>")

form_training_client = FormTrainingClient(endpoint, credential)

container_sas_url = "xxx"  # training documents uploaded to blob storage
poller = form_training_client.begin_training(container_sas_url, use_training_labels=True)
model = poller.result()
```

As for the folder hierarchy, I'm looking into this for you.

**Comment by kristapratico** [comment]
@agiokas-dbg 

Regarding the file hierarchy, make sure you are specifying the `prefix` argument in order to let the service know which subfolder should be used for training. For example, if you intend to train on the files in the `BE.DIE.filing_confirmation.print.fle` folder then the call to training should look like this:

```
poller = form_training_client.begin_training(
    container_sas_url, use_training_labels=True, prefix="BE.DIE.filing_confirmation.print.fle"
)
model = poller.result()
```

Please give it a try and let me know if it resolves your issue.

**Comment by agiokas-dbg** [comment]
@kristapratico Thank you very much! This seems to have worked just fine, I suppose it's a niche case which is why the tutorial didn't cover it. Thank you for your help :+1:
