### ISSUE TITLE
ServiceBus Batch Receive support

### ISSUE THREAD

**Issue by pankajbhagra** [Azure/azure-sdk-for-python#1216]
I was looking for support to do batch read out of serviceBus using python SDK. I saw a support for 
send_queue_message_batch() but couldnt find support for bulk receive in receive_subscription_message. similar support available in C-sharp sdk. 

To scale the receiver throughput (which reads one message a time), i need to avoid the RTT from client to serviceBus.  i would like to either use (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements)
a) prefetchCount 
b) use bulk read receive_subscription_message_batch() 

Didn't find any of these in the current python SDK (using version azure-servicebus==0.21.0). At this stage i don't want to create parallel consumers as it would require re-ordering the message from the common source. 

Is there a plan to add either of these batch or prefetch support in near future for serviceBus consumer or alternate suggestion to make consumer consume faster (instead of 1 message per RTT) ?

**Comment by lmazuel** [comment]
Hi @pankajbhagra 

Currently for performance on SB, the service team recommends the usage of AMQP. We have no plan to add more features in the current HTTP client azure-servicebus unfortunately :(

Thank you,
