### ISSUE TITLE
[core] whitelist and blacklist -> allowlist and blocklist

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#12219]
Based on conversations in [this](https://teams.microsoft.com/l/message/19:f6d52ac6465c40ea80dc86b8be3825aa@thread.skype/1592075876181?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1592075876181&teamName=Azure%20SDK&channelName=General&createdTime=1592075876181) teams post

**Comment by lmazuel** [comment]
Done recently
