### ISSUE TITLE
Remove azure-template from PyPI

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#12223]
I have no idea how it went there, but it shouldn't have :(

**Comment by kurtzeborn** [comment]
@lmazuel this package is used for testing purposes with our release pipeline.  @weshaggard and I are thinking we'd want to keep it there so we can continue testing with it when we're trying new things with releases.  Is there a way to hide it or something instead of deleting it?

@scbedd, are we off on this?  It seems like we'd want it around to test with.

**Comment by scbedd** [comment]
It really does help to have a test all the way to publish (versus checking that the appropriate wheels are _present_ and then exiting early).

I am perfectly ok with `yanking` all the available versions of it.

**Comment by lmazuel** [comment]
It's publicly available to customer, clearly creates confusing since the Readme are not saying anything about the intent of the package. But I do understand the value to test it, there was a PyPI test server at some point:
https://packaging.python.org/guides/using-testpypi/

If you want a package to test, I would do a azure-test or something with explicit readme that says it's not for any usage and was for test purposes

**Comment by weshaggard** [comment]
I agree we could probably add a note in the readme to make it clear but we have this azure-template package for all the languages which is used as a starting point for new libraries and we also use it for testing E2E to our package managers, while testpypi is helpful in some cases we still like to have something to test exactly how we plan to release.

@lmazuel what about just hiding it on pypi?

**Comment by lmazuel** [comment]
@weshaggard  I don't think you can hide it. You can delete it probably after each release though and recreate it each time. Yanking the releases is not enough, since the project page will still be there.

I would still investigate testpypi, it's really designed to be the same thing, with just a url difference and that's it.

**Comment by weshaggard** [comment]
Yeah I couldn't figure out how to hide the package but pypi, unlike other package managers, does allow you to delete a package. So I suggest we simply delete the package now and anytime after we finish our testing. We should also be able update the readme with some text telling folks this is just a test package for the time it does show up on pypi.

While we could use another package for publishing we would still want to use a test package of some sort and it would have the same problems that we wouldn't want folks to be confused by it so I'm not sure that is a great option either. And as for testpypi it would enable some level of testing but it would never allow us to verify that our packages show up on pypi correctly or that our credentials and such are correct for pypi. In general we would like to have our testing use an unmodified pipeline so we can truly verify that things work E2E.

**Comment by lmazuel** [comment]
@weshaggard if you manually delete it each time that's fine to me ;)

**Comment by weshaggard** [comment]
That seems doable as we don't test this all the way to pypi often. @praveenkuttappan @scbedd can you guys delete the template package from pypi after you are done testing its publishing?

**Comment by scbedd** [comment]
@weshaggard Yep. 100%. I'll close this item after we execute on this.

**Comment by lmazuel** [comment]
@scbedd I see you yanked the releases, I think we were discussing to entirely remove the project altogether from PyPI.
