### ISSUE TITLE
RecognizedForm is not serializable

### ISSUE THREAD

**Issue by iMicknl** [Azure/azure-sdk-for-python#12264]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 1.0.0b3
- **Operating System**: Linux (Azure Durable Functions)
- **Python Version**: 3.7.7

**Describe the bug**
Using Azure Functions, it is hard to work with Form Recognizer SDK since you can not pass the result of the call to another function. 

**To Reproduce**
1. Use `begin_recognize_custom_forms_from_url()
1. Call poller.result() which returns an RecognizedForm object
1. Pass the RecognizedForm object to `json.dumps()` or a similar function.

**Expected behavior**
`RecognizedForm` class should be serializable

**Additional context**
```
[06/30/2020 15:01:26] Exception: ValueError: activity trigger output must be json serializable ([RecognizedForm(form_type=form-xxxx-xxxx, fields={'naam': FormField(label_data=None, value_data=FieldText(page_number=1, text=Scheepers, bounding_box=[Point(x=979.0, y=541.0), Point(x=1433.0, y=541.0), Point(x=1433.0, y=619.0), Point(x=979.0, y=619.0)]
```

**Comment by kristapratico** [comment]
Hi @iMicknl 

I'm looking into this for you. In the meantime could you try this and see if it works for you:

`recognized_form_json = json.dumps(recognized_form, default=lambda x: x.__dict__)`

**Comment by iMicknl** [comment]
@kristapratico thanks, that works. I would have expected to have something in the class making it JSON serialisable by default, but not sure if this is default behaviour in Python.

Thanks for tagging it as a feature request @lmazuel.

**Comment by iMicknl** [comment]
@kristapratico my follow up request / question would be if it is possible to serialize it back to a `List[RecognizedForm]`? So you can use the typed object again.

**Comment by kristapratico** [comment]
@iMicknl glad that worked for you. Can you help me understand the scenario a bit better and why you'd like to serialize it back to a `List[RecognizedForm]`? 

Not sure if this addresses your issue completely, but you can pass keyword argument `raw_response_hook` with a callback function into `begin_recognize_custom_forms_from_url` to get both the JSON and `RecognizedForm`:

```
def callback(response):
    print(response)  # get JSON out of here

poller = client.begin_recognize_custom_forms_from_url(model_id, form_url, raw_response_hook=callback)
recognized_form = poller.result()  # get RecognizedForm here
```

**Comment by iMicknl** [comment]
I am building a pipeline for various Form Recognizer tasks using Azure Durable Functions for Python. (
[architecture](https://user-images.githubusercontent.com/1424596/86175222-3bd0a380-bb23-11ea-9626-2c840df5a64b.png)). Every step is in a different Activity Function, where data will be passed to by the orchestrator. 

My idea of serialising it back was only to make the code more readable and type safe in the step where the Form Recognizer response is processed. However this is not necessary for the scenario, just a nice to have.

Another issue in this current architecture in combination with the SDK, is that it looks like that the `poller.result()` function is blocking IO in the function. In the end, I may have to move away from the SDK to aiohttp. The goal is to have as less function executions as possible, thus letting the orchestrator handle the polling and calling activity functions to retrieve the result. I can understand that this is out of scope for the SDK, however I just wanted to make sure you understand my scenario.

>Orchestrator functions can make long-running HTTP calls to external endpoints as described in the HTTP features article. The CallHttpAsync method in C# and the callHttp method in JavaScript might internally poll an HTTP endpoint while following the asynchronous 202 pattern.

**Comment by kristapratico** [comment]
Very cool! Thank you for explaining and sharing how you're using the SDK. :)

Just wanted to call out - the Form Recognizer SDK does support aiohttp, you can find the clients under the `azure.ai.formrecognizer.aio` namespace. And here are some [samples](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples) you can take a look at.

**Comment by iMicknl** [comment]
@kristapratico should I close this issue? Or is it a valid issue and will you use it for tracking to make sure that RecognizedForm is serialisable out of the box?

**Comment by kristapratico** [comment]
Thanks for checking, let's leave the issue open as a feature-request.

**Comment by xiangyan99** [comment]
We received similar request in Search. #13947

**Comment by yowl** [comment]
In C# you can serialize the RecognizedForm, but you cant deserialize it as there is no parameterless ctor.  Can that be added?

**Comment by lmazuel** [comment]
Hi @yowl , can you ask the question on the C# repo, so all the C# community will benefits from the answer? Also, we're not expert in C# :)
Thanks!
https://github.com/Azure/azure-sdk-for-net

**Comment by yowl** [comment]
Oh sorry. this is a python thread.  My bad.

**Comment by lmazuel** [comment]
@yowl no worries at all :)

**Comment by lmazuel** [comment]
@catalinaperalta , I would suggest you check with @mccoyp if the JsonEncoder is enough to solve the question

**Comment by catalinaperalta** [comment]
The following samples `sample_convert_to_and_from_dict.py` and `sample_convert_to_and_from_dict_async.py` have been added to show how the Python Form Recognizer SDK facilitates serialization under the [samples folder](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/formrecognizer/azure-ai-formrecognizer/samples) for both v3.1 and v3.2-beta versions of the SDK. 

Will close this issue now, please feel free to open new issues with questions or feedback. Thanks!
