### ISSUE TITLE
Government region support

### ISSUE THREAD

**Issue by likel** [Azure/azure-sdk-for-python#1230]
Per doc http://azure-sdk-for-python.readthedocs.io/en/latest/multicloud.html#azure-government , I can find a example for Resource to use Azure Government region, and it says for all region the authenciaion endpoint is https://login.microsoftonline.com/. 

And for storage, from what I understanding, I need to pass a suffix like https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L84 . So for different service, I have to find out how to configure its Government endpoint.

But I didn't find any useful information for Government region support of Office 365 Management APIs. So do we need to do anything special for office 365 management API endpoint? Thanks.

**Comment by lmazuel** [comment]
Hi @likel 

I won't be able to answer to you here, I'm sorry, I have no idea how Python and Office 365 is working :(
Is there a Python package for that? You might want to open an issue in their GH repo.

Thanks,

**Comment by likel** [comment]
@lmazuel Thanks for your reply. They don't have a lib for its api, actually I don't know how to reach anybody for Office 365 API. But when I authenticating office 365 api, the login url is also https://login.microsoftonline.com/ . So I thought you maybe know something about it... :)

**Comment by gsacavdm** [comment]
@likel , the Office 365 Government Community Cloud (GCC) uses the same endpoints as Office 365 commercial (the regular one), so the login URL is also https://login.microsoftonline.com.

The key consideration here is that **government customers generally have two accounts/tenants**:

* 1 tenant for Azure Government - login using login-us.microsoftonline.com and use the Azure Government endpoints as outlined [here](https://docs.microsoft.com/azure/azure-government/documentation-government-developer-guide#endpoint-mapping).
* 1 tenant for Office 365 GCC - login using login.microsoftonline.com and use the same endpoints as regular O365.

**Comment by likel** [comment]
Thank you @gsacavdm . If I'm not wrong, 

- For O365, we don't need to do something special for GCC which uses the same endpoints (login and API endpoint) with regular O365. 
- For Azure: Governemt customer uses different login endpoint login-us.microsoftonline.com 
 instead of https://login.microsoftonline.com and different endpoints. And regular user use login endpoint https://login.microsoftonline.com and regular API endpoints. But the doc http://azure-sdk-for-python.readthedocs.io/en/latest/multicloud.html#azure-government said 

> Azure Government is currently using the same authentication endpoint that public azure. This means that we can use the default authentication_endpoint.

Could you please clarify, very thanks for your help.

**Comment by gsacavdm** [comment]
@likel , your summary is accurate.

**Comment by lmazuel** [comment]
Hi @likel 
I updated the documentation to make it right. Government will be using its own authentication endpoint (https://login-us.microsoftonline.com/) and we should use it.
Thanks!
