### ISSUE TITLE
parameters not showing up in function signature on github.io

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#12321]
e.g. https://azuresdkdocs.blob.core.windows.net/$web/python/azure-ai-formrecognizer/1.0.0b3/azure.ai.formrecognizer.html#azure.ai.formrecognizer.FormRecognizerClient.begin_recognize_content

This has a parameter `form` which is documented but does not show up in the function signature. 

Edit: this seems to be more systemic. Similar issues in text analytics (see 1.0.0b6 -> 1.0.0) docs and storage

**Comment by scbedd** [comment]
This is, in fact, a generic issue:

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.3.2/azure.storage.blob.html#azure.storage.blob.BlobClient.download_blob

**Comment by scbedd** [comment]
Will resolve after updating existing documentation.
