### ISSUE TITLE
Proxy support for ServicePrincipalCredentials

### ISSUE THREAD

**Issue by likel** [Azure/azure-sdk-for-python#1232]
My azure-sdk-python version is 2.0.0rc5, I cannot find a way to pass proxy configuration into ServicePrincipalCredentials class explicitly, and maybe other xxxxCredentials. I found #800 which says I can use Adal to archive it, the doc http://azure-sdk-for-python.readthedocs.io/en/latest/quickstart_authentication.html#using-adal didn't mention any proxy related usage, and I checked the latest code, there is also no way to pass a proxy into the AuthenticationContext class. 
My workaround now is extend the ServicePrincipalCredentials class and override the set_token() . 
If I'm wrong, please clarify the documentation. Thanks a lot.

**Comment by lmazuel** [comment]
@yugangw-msft is there a way to do that with ADAL?

**Comment by yugangw-msft** [comment]
ADAL doesn't have any particular logics for proxy. Like mentioned in https://github.com/Azure/azure-sdk-for-python/issues/800, configuring the `http/https_proxy` environment variables should just take care of it. I have verified using fiddler on windows and mitmproxy on osx, the adal worked pretty fine. But I don't think I am a expert still, please elaborate if using the environment variables doesn't work out.
