### ISSUE TITLE
Managed Disk Documentation Links to the wrong page

### ISSUE THREAD

**Issue by rounakdas** [Azure/azure-sdk-for-python#1233]
In the page for [compute management client](https://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.compute.compute.v2016_04_30_preview.html), for disk operations it links to [this page](https://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.devtestlabs.operations.html#azure.mgmt.devtestlabs.operations.DisksOperations). This is the wrong DiskOperations class. It should link to [this page](https://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.compute.compute.v2016_04_30_preview.operations.html#azure.mgmt.compute.compute.v2016_04_30_preview.operations.DisksOperations)

**Comment by lmazuel** [comment]
Hi @rounakdas 

You're right, I started to fix some of these but not this one yet :/. I will try to fix it today.
thanks!

**Comment by rounakdas** [comment]
Great to know! Thanks :)

**Comment by lmazuel** [comment]
File updated! Now it's at RTD to work (might take a few days, since we have timeout issues with RTD currently). But the original docstring in the source file is fixed, so I close.
Thanks!
