### ISSUE TITLE
"Error validating token: IDX10223" Whilst getting a KeyVault secret

### ISSUE THREAD

**Issue by terrycain** [Azure/azure-sdk-for-python#12368]
- **Package Name**: azure-keyvault-secrets
- **Package Version**: 4.1.0
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8

**Describe the bug**
After some period of time, running the following will return an error
```python
credential = DefaultAzureCredential()
self._secret_client = SecretClient(vault_url=keyvault_url, credential=credential)
# ... after a undetermined amount of time
self._secret_client.get_secret(secret_name)
```

Stacktrace
```
HttpResponseError: (Unauthorized) Error validating token: IDX10223
  File "a/server.py", line 48, in readyz
    cache.get_secret('a-readyz')
  File "a/cache.py", line 21, in get_secret
    secret = self.storage.get_secret(normalised_secret_name, secret_name)
  File "a/storage.py", line 50, in get_secret
    secret_value_obj = self._secret_client.get_secret(secret_name)
  File "/usr/local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/keyvault/secrets/_client.py", line 66, in get_secret
    bundle = self._client.get_secret(
  File "/usr/local/lib/python3.8/site-packages/azure/keyvault/secrets/_shared/_generated/v7_0/operations/_key_vault_client_operations.py", line 1625, in get_secret
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/usr/local/lib/python3.8/site-packages/azure/core/exceptions.py", line 102, in map_error
    raise error
```

**To Reproduce**

Unknown, it happens after a few hours/days, I've had this happen in 3 different environments now, 

**Expected behavior**
I expected it to return a secret

**Additional context**

This is running in a container, on Kubernetes in Azure using pod-aad-identity to assign a managed identity to the worker the container is running on, and then handles calls to the metadata address.

**Comment by chlowell** [comment]
It's no consolation to you I'm sure, but this is an interesting bug 😄

IDX10223 means the client sent an expired access token. This is unexpected because if a token appears to be expired or expiring within 5 minutes, the client will ask for a new one. If that failed, you would see a different error. It is possible for the client to send an expired token, however, because it will use a new token once before checking its validity ([see this code](https://github.com/Azure/azure-sdk-for-python/blob/139b9bfb607e7c18b38d397f232570aa156d90f7/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L134)).

That suggests two possible causes. First, perhaps the client determined the token was valid. It uses `time.time()` to do that. If it receives a sufficiently skewed value, it will use a token Azure AD considers expired. Second, perhaps the client requested a token from the managed identity endpoint and received an expired one. The endpoint presumably has its own cache and shouldn't hand out expired tokens from it, but that misbehavior would have the result you're seeing. I suppose skewed clock values on your worker could also cause this to happen.

But I'm speculating. I'm afraid it would take some debugging within your cluster to figure out what exactly is going on. I don't see any related issue in [aad-pod-identity](https://github.com/Azure/aad-pod-identity).

**Comment by terrycain** [comment]
Thanks @chlowell, I've done some digging around the cluster and verified all the clocks are in sync. I also noticed it happened across multiple clusters in short succession which roughly followed the order in which I deployed the containers so I'm thinking that it was given an expired token by aad-pod-identity. It works at first so a cached expired token makes sense to me. I'll go bug those guys and see if they have any ideas.

**Comment by terrycain** [comment]
Hey @chlowell so I've done some digging. Clock skew seems unlikely, and I've spoken to the AAD guys and they do no caching and pass through the requests straight to the metadata endpoint.

Got some logs when it happened the other day.

These log lines all followed the stacktrace above, so it happens 4 times a day
```
127.0.0.1 - - [13/Jul/2020:08:30:08 +0000] "GET /readyz HTTP/1.1" 500 35 "-" "kube-probe/1.16"
127.0.0.1 - - [13/Jul/2020:08:32:08 +0000] "GET /readyz HTTP/1.1" 500 35 "-" "kube-probe/1.16"
127.0.0.1 - - [13/Jul/2020:08:35:08 +0000] "GET /readyz HTTP/1.1" 500 35 "-" "kube-probe/1.16"
127.0.0.1 - - [13/Jul/2020:08:42:08 +0000] "GET /readyz HTTP/1.1" 500 35 "-" "kube-probe/1.16"
```
The issue is slightly more complicated as there are 2 workers serving requests for /readyz but both should request a token and deal with it appropriately.

These are the logs from the NMI pod on that host. Basically showing the time the pod requested tokens

```
I0713 08:20:08.403864       1 standard.go:72] No clientID in request. pod1-54cc5b6fdc-5fng8 has been matched with azure identity pod1
I0713 08:20:08.403938       1 standard.go:165] matched identityType:0 clientid:adf7##### REDACTED #####eec5 resource:https://vault.azure.net
I0713 08:20:08.617855       1 server.go:190] Status (200) took 214117053 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.3.1.101
I0713 08:43:08.403759       1 standard.go:72] No clientID in request. pod1-54cc5b6fdc-5fng8 has been matched with azure identity pod1-identity
I0713 08:43:08.403842       1 standard.go:165] matched identityType:0 clientid:adf7##### REDACTED #####eec5 resource:https://vault.azure.net
I0713 08:43:08.415703       1 server.go:190] Status (200) took 12119465 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.3.1.101
```

Is there anything I can do to dig into this further, to verify that the metadata endpoint isn't handing out expired tokens? Anyway I can easily hook/monkeypatch the credential getting piece?

**Comment by chlowell** [comment]
You could enable debug logging on the client with `logging_enable=True`:
```py
self._secret_client = SecretClient(vault_url=keyvault_url, credential=credential, logging_enable=True)
```

That would log all its requests at `DEBUG` level with nothing redacted. So, security warning there, but it would let you read the token from a failed request's `Authorization` header and check its `exp` claim (the token is a JWT). Alternatively, you could do similar with the credential instead, i.e. `DefaultAzureCredential(logging_enable=True)`. Then you'd see the token request itself:
```
Request URL: 'http://169.254.169.254/...'
Request method: 'GET'
Request headers:
    'Metadata': 'true'
    'User-Agent': 'azsdk-python-identity/1.3.1 ...'
Request body:
None
Response status: 200
Response headers:
    'Content-Type': 'application/json; charset=utf-8'
    'Date': 'Mon, 20 Jul 2020 16:19:39 GMT'
    'Content-Length': '1643'
Response content:
{"access_token":"...","expires_on":"1595347982", ...}
```

For a monkeypatch approach, `SecretClient` adds tokens to requests [here](https://github.com/Azure/azure-sdk-for-python/blob/e269d68e0df22ba20fc86a39d37aa88dea614ec4/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L140) and the credential deserializes the token [here](https://github.com/Azure/azure-sdk-for-python/blob/azure-identity_1.3.1/sdk/identity/azure-identity/azure/identity/_authn_client.py#L99).

**Comment by terrycain** [comment]
Have not seen it reoccur in the environment with the additional logging. Am working on it :D

**Comment by AlexGhiondea** [comment]
Thank you @terrycain! Please let us know if you are able to repro this!
