### ISSUE TITLE
parsing incorrect for network_profile in container_group.create_or_update()

### ISSUE THREAD

**Issue by howardjones** [Azure/azure-sdk-for-python#12370]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

Ubuntu 18 LTS
Python 3.8.0
azure-mgmt-containerinstance 1.5.0
azure-mgmt-network           11.0.0
azure-core 1.6.0

**Describe the bug**
Container Instance SDK incorrectly finds error with object produced by networks SDK.

**To Reproduce**
1. Create a NetworkProfile object with  ContainerNetworkInterfaceConfiguration attached, to place containers in a subnet.
2. use `network_profiles.create_or_update()` to actually create the profile in Azure, and `wait()` on the LROPoller.
3. get the resulting profile object from `result()` and use it to populate the `network_profile` field in a ContainerGroup() constructor
4. use container_groups.create_or_update() to create the container group

**Expected behavior**
A container group is created, with containers being created in the specified subnet.

**Screenshots**

**Additional context**

```
network_profile_name = "aci-profile-" + rnd
cnic_name = "aci-cnic-" + rnd
ipconf_name = "aci-ipconf-" + rnd

logger.info("Creating ipconfiguration")
ipconf = IPConfiguration(name=ipconf_name, subnet=subnet)

logger.info("Creating CNIC")

cnic = ContainerNetworkInterfaceConfiguration(
    name=cnic_name,
    ip_configurations=[ipconf]
)
logger.info("Creating network profile")
network_profile = NetworkProfile(location=azure_region,
                                 container_network_interface_configurations=[cnic])
logger.info("Updating network profile")
network_profile_poller = net_client.network_profiles.create_or_update(resource_group_name,
                                                                      network_profile_name,
                                                                      network_profile)

network_profile_poller.wait()
network_profile_created = network_profile_poller.result()


# Configure the container group
group = ContainerGroup(location=resource_group.location,
                       containers=[container],
                       os_type=OperatingSystemTypes.linux,
                       network_profile=network_profile_created,
                       image_registry_credentials=[acr_credentials],
                       restart_policy=ContainerGroupRestartPolicy.never)

# Create the container group
result = aci_client.container_groups.create_or_update(resource_group.name,
                                                      container_group_name,
                                                      group)
```

create_or_update() fails with Exception:
```
(<class 'msrestazure.azure_exceptions.CloudError'>, CloudError("The request content was invalid and could not be deserialized: 'Could not find member 'location' on object of type 'NetworkProfileDefinition'. Path 'properties.networkProfile.location', line 1, position 1122.'."), <traceback object at 0x7f6bc8880fc0>)
```

Checking with debugger shows that the object being submitted _does_ have a location member in the network_profile.

Remaining code works fine without network_policy on the ContainerGroup (apart from being in the wrong network).

**Comment by kaerm** [comment]
Thanks @howardjones for reporting this, @nickzhums can you take a look at this?

**Comment by nickzhums** [comment]
@RodgeFu to take a look, thanks!

**Comment by dw511214992** [comment]
Hi @howardjones 
When creating ContainerGroup,  you input `network_profile_created`, whose type is `NetworkProfile`. However, python sdk asks to input type `ContainerGroupNetworkProfile`. Please try again.

**Comment by RodgeFu** [comment]
close per the thumb-up from @howardjones . Feel free to reopen if needed. thanks.
