### ISSUE TITLE
Azure speech SDK compliance with Python design guidelines

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#12381]
- Missing sdist on PyPi
- Callbacks on non-main thread
- No Python 2.x support
- Callback-happy - we should look at alternate patterns (including iterators and decorated dispatch methods for long-running tasks)

Code style:
- Too many positional parameters where position is not logical (e.g. `AudioConfig.__init__`)
- `isinstance` checks e.g. `get_property` checks for `PropertyId` enum as opposed to just allowing an arbitrary value.
- Unnecessary "base classes" e.g. `AudioInputStream`. They should either be ABCs or protocols.

**Comment by kaerm** [comment]
cc: @robch

**Comment by johanste** [comment]
Added a [gist](https://gist.github.com/johanste/5cc62daa23adc3a68ae4cca49d109fd5) for decorator based handler registration. Snippet of user code below, but more complete example in the gist...

```python
recognizer = Recognizer('https://api.contoso.com')

@recognizer.handle('speakerRecognized')
def handle_speaker_recognized(message):
    print(f'speaker recognized: {message}')

@recognizer.handle('stop')
def handle_speaker_recognized(message):
    print(f'stopping: {message}')
    raise RecognitionCancelledError("I'm sooo done with this!")
```
