### ISSUE TITLE
Document which exceptions are raised for what events. 

### ISSUE THREAD

**Issue by andersbogsnes** [Azure/azure-sdk-for-python#12405]
**Is your feature request related to a problem? Please describe.**
When I build libraries on top of Azure SDKs, I need to know what exceptions are thrown for what cases, so that I can catch the relevant ones and handle them. I'm mainly having this issue with Azure Blob Storage v12 at the moment

**Describe the solution you'd like**
Some form of documentation indicating where the various exceptions live. This could be either in the docs, or having a exceptions.py from which the library raises exceptions, so that it is easy to see what exceptions we can import from the SDK

**Describe alternatives you've considered**
Currently, I have to manually go through various edge-cases, try to figure out where those exceptions come from and how to import them

**Comment by kaerm** [comment]
@andersbogsnes thanks for reporting this, 
cc: @lmazuel maybe there is something we could do here across the libraries?

**Comment by lmazuel** [comment]
This page is here for that:
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/core/azure-core#azure-core-library-exceptions

@andersbogsnes I want to address two things: completeness and discoverability:
- Is the previous link complete?
- Where would you think a link to this doc should be visible?

FYI @xiangyan99

**Comment by andersbogsnes** [comment]
@lmazuel Thanks, that looks like exactly what I was looking for!
The docs look great, albeit generalized, though for completeness, I would probably add somewhere what module the exceptions are imported from (I'm guessing azure.core.exceptions?). Just updating the first code example with `from azure.core.exceptions import AzureError` would probably be enough.

My issue is that there is nowhere in the documentation (https://azure-storage.readthedocs.io/index.html) where that is referenced. There are also no examples for the Azure Blob Storage SDK of what exceptions are actually used, and what they mean in the context of Blob Storage. I assume a ResourceExistsError means something different in the context of uploading/downloading files than it does in the context of the management APIs? 

There is also nowhere in the docstrings where it is mentioned what kind of exceptions can occur:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py

Improving either of those two areas would certainly help discovery a fair amount and really help out developers who are trying to build libraries on top of the SDKs.

**Comment by amishra-dev** [comment]
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob#general has the list for storage exceptions. Does this help?

**Comment by andersbogsnes** [comment]
Hi @amishra-dev, thanks for the link.

So it says that azure blob storage raises exceptions from `azure.core` and it raises `StorageErrorException` and then links to a list of error codes.

1. I can't see where StorageErrorException is defined. It's not in Azure.core, there's no exceptions.py or something similar in the blob storage repo that would indicate that an exception is defined there. 
After looking through the entire repo, I find it in blob/_generated/models/_models.py - importing from there is definitely going to raise questions at the peer review :smile: 

2. With no examples, I'm not sure how the error codes and the exception handling actually work together. Is it an attribute of the exception that I have to check and then handle?

3. It also doesn't mention when Blob Storage uses the various exceptions that `azure.core` has available

**Comment by tasherif-msft** [comment]
Hi @andersbogsnes, I have taken on this issue and will have discussions to surface these exceptions better for users.
I will let you know as soon as I have an update :)

Thank you!

**Comment by tasherif-msft** [comment]
Hi @andersbogsnes, you're right the exceptions docs are not very clear. The azure storage exceptions that are raised at the end of any failed operation are imported from Azure core.

The way we raise this is by using an internal class called `StorageErrorException`. This is deserialized by `process_storage_error(StorageErrorException_object)`. This simply maps the different possible error codes to the corresponding appropriate Azure core exception which can be caught by the user. You can see the mapping we're doing here: https://github.com/Azure/azure-sdk-for-python/blob/8504f6d247badd2fd60dce3457f201f9e2b1c079/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py#L86

I'm not sure why we even reference `StorageErrorException` in our README. I will put out a PR that states what I have mentioned in this comment :)
