### ISSUE TITLE
Servicebus Track2 Consistency review

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#12415]
Perform consistency review with broader SDK family.  Make any changes as needed. 

as of 8/12 consistency review was performed, summarized outcome:

Design topics:
- [x] Create a roadmap for if post-GA "change property on deadletter" was implemented, to ensure it will fit nicely in our current plan. (no backcompat issues, etc.)
- [x] create_queue_receiver vs get_queue_receiver (Keeping get; precedent in storage libs for python, as well as our use of context managers rather than the initial method for opening operation)
- [x] Message vs ServiceBusMessage (for BatchMessage as well)
- [ ] Should get/set session state unify with taking +returning bytes or strings?
- [x] Remove object-as-name for e.g. createrule, contemplate naming implications (topic_name was proposed but I worry that codes us into a corner) (created as discussion issue for october sprint due to pitfalls found during implementation)

Requiring Investigation:
- [x] Can EventHubsSharedKeyCredential be shared for mgmt + core client; and be safely yanked pre-GA? (yes it can be, and yes it is being.)
- [x] What is NamespaceProperties.alias? It does not appear to show up in the portal. (Premium feature; is to be maintained.)
- [x] Why do .net and js not appear to have an isomorphism of entity_availablility_status (QueueProperties), or for created_at in RuleProperties.  Same question for is_anonymous_accessible and support_ordering and status in creation methods. (renamed availablility_status, anonymous/ordering nixed)
- [x] Should enable_express be removed? Speak with Harsha. (may not be supported) (Conclusion: Is needed, already present)
- [x] What does enable_partitioning at subscription level mean? (removed)
- [x] Confirm size_in_bytes settable/meaningful for creating a topic (Java has this as settable, maintaining)

Changes needed:
- [x] reason -> dead_letter_reason; description -> dead_letter_error_description
- [x] renew_lock should return locked_until_utc value.
- [x] entity_name should not be a parameter of ServiceBusClient __init__
- [x] ReceiveSettleMode -> ReceiveMode, mode -> receive_mode
- [x] prefetch -> prefetch_count
- [x] Remove overrideable retry parameters from all but top-level client init.
- [x] peek message_count -> max_message_count
- [x] PeekMessage -> PeekedMessage
- [x] receive_deferred_messages signature should mirror cancel_scheduled, in terms of union single/many.
- [x] receive_messages max_batch_size -> max_message_count (set default to 1 assuming same semantic meaning as None)
- [x] Normalize session method/property naming. (e.g. get_session_state -> get_state).  session_id vs Id may merit some discussion however.
- [x] Fix set_session_state type-string "    def set_session_state(self, state: Union[str, bytes, bytearray         admonitio]) -> None"
- [x] "created_time"/"modified_time" -> created_at
- [x] Remove namespace_type from NamespaceProperties
- [x] Remove requires_preprocessing from SqlRuleAction and SqlRuleFilter.
- [x] Make `rights` parameter take the AccessRights enum to be clear.

**Comment by KieranBrantnerMagee** [comment]
Review completed for top-level functions, will continue in this next milestone for client and message alignment.

**Comment by KieranBrantnerMagee** [comment]
Consistency review complete.  Comments present in SDK api-view.  Many changes will need to be made, and potentially sub-issues created.  Have re-estimated this issue as time needed to do a first pass, to avoid further issue noise.

**Comment by ramya-rao-a** [comment]
Two more points:
- The "rights" in the "authorization_rules" is an enum in .Net meaning it has a restricted set of values. We currently have it as a string, meaning we let any value go to the service
- In `SqlRuleFilter` and `SqlRuleAction`, I see a `requires_preprocessing` which is not present in the .Net API which makes me wonder if this is a documented property or not. Please check

**Comment by ramya-rao-a** [comment]
Few more points from the review that got missed above
- In `ServiceBusSession`,  should `id` be `session_id`?
- `receive_deferred_messages` should take union of int & list[int] just like `cancel_scheduled_messages`

**Comment by ramya-rao-a** [comment]
Confirmation on things that we can remove in the ManagementClient
- create_queue and QueueProperties
    - is_anonymous_accessible
    - support_ordering
- create_topic and TopicProperties
    - is_anonymous_accessible
    - enable_subscription_partitioning

enable_express stays

Pending clarifications on
- size_in_bytes for create_topic
- entity_availability_status for topics and queues

**Comment by ramya-rao-a** [comment]
Update on `entity_availablility_status`:
- the property name should be `availability_status`
- it should support a restricted set of values
- it is applicable to queues, topics and subscriptions
- it is not settable in both create and update operations, it is a readonly property

See https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.entityavailabilitystatus?view=azure-dotnet for more details
