### ISSUE TITLE
Support params as list for exploding parameters

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#12410]
When doing a call like this:
```python
request = self._client.get(url, query_parameters, header_parameters)
```
We are coming here:
https://github.com/Azure/azure-sdk-for-python/blob/194ae8dd5ea80ccc3304e9ba463ccb8055a9f9f3/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L288-L305

We should accept a list of string as params for instance `{'a':['b','c']}`, and explode the parameters in that case: `a=b&a=c`

FYI @johanste

**Comment by xiangyan99** [comment]
fixed in #12420
