### ISSUE TITLE
Servicebus Track2 UAMQP may need changes to support not closing receiver when generator terminates.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#12419]
Truth in advertising.  We've been relying on lazy-reopening to ensure a user could consume the generator, interrupt, then resume consumption, but it might be a more proper semantic to simply not close it unless explicitly closed (or the context manager ends).

This may require UAMQP-side changes as well.

**Comment by yunhaoling** [comment]
closing the issue, uamqp 1.2.10 is out -- https://pypi.org/project/uamqp/1.2.10/
