### ISSUE TITLE
ATOM API runtime vs. description properties, should any move from former to latter

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#12413]
Currently service bus mgmt APIs return two different entity-description blobs, runtime properties and description properties.

Align with broader SDK family on if these settings are divided properly, if needed proposal->architects etc.

**Comment by ramya-rao-a** [comment]
@KieranBrantnerMagee Can we close this if #12576 tracks the same but with more details?

**Comment by KieranBrantnerMagee** [comment]
It's not QUITE the same, the issue you link had to do with the actual split itself, and the naming surrounding it, where this was questioning whether any of the internal properties should shuffle around.

For the purpose of cleaning up the board though I can encapsulate this question inside that issue though, it's not unreasonable.
