### ISSUE TITLE
[Event Hubs] Idempotent producer

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#12427]
Feature spec (.NET Design Proposal): https://gist.github.com/jsquire/1cc4db6b3ca4ef13d26dc5315483555b
Python gist: https://gist.github.com/yunhaoling/c17ddd3c1bfbe5c4ba156a8eb0e54e7d
.NET Sample gist: https://gist.github.com/jsquire/0f3bc5701388fe03ccd027e86f1994f1

.NET Implementation PR:

https://github.com/Azure/azure-sdk-for-net/pull/15034/files
https://github.com/Azure/azure-sdk-for-net/pull/15125/files
https://github.com/Azure/azure-sdk-for-net/pull/15332/files

tasks:
- [x] API review with arch
  - [x] gist (sample code)
  - [x] apiview
- [x] implementation
- [x] test
- [x] sample
- [x] doc

**Comment by KieranBrantnerMagee** [comment]
Update: OstensiblynNov timespan for python, .net will be going live with reference implementation with the other languages following.
