### ISSUE TITLE
tags on subscription level

### ISSUE THREAD

**Issue by donets420** [Azure/azure-sdk-for-python#12422]
Hi team,
I am trying to find method to return list of all available tags on subscription level.
SubcriptionClient(azure.mgmt.subscription) doesn't have this information.

Is it possible to grap this information?
Thanks in advance!

**Comment by anuragdalmia** [comment]
@rthorn17 - can you take a look at this please.

**Comment by rthorn17** [comment]
@donets420 You should use this python sdk: https://pypi.org/project/azure-mgmt-resource/. with the api, with parameter -resourceId (provide subscriptionId). This will get all tags on the subscription

**Comment by donets420** [comment]
yep, it works, thanks!
