### ISSUE TITLE
LROs fail when a PATCH returns a 201 with location header

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-sdk-for-python#1243]
PATCH operations can return 201 with a location header or azure async operation response. However, if they do the following code will result in a failure being thrown: https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L141-L145 

This needs to be updated to also consider PATCH+201 as a success case

**Comment by lmazuel** [comment]
Moved to https://github.com/Azure/msrestazure-for-python/issues/31 ;)
