### ISSUE TITLE
azure-identity Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#12442]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity#credentials):
![image](https://user-images.githubusercontent.com/57166602/86902404-7bf5de80-c140-11ea-9765-1502df4e9163.png)

Suggestion:
Click `DefaultAzureCredential` should jump to hyperlink:https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.2.0/azure.identity.html#azure.identity.DefaultAzureCredential

**Comment by v-xuto** [comment]
@jongio for notification.

**Comment by chlowell** [comment]
There's a section of the README devoted to `DefaultAzureCredential`. I linked its entry in the credential table to that section because I thought it would be a more helpful introduction than the API reference.
