### ISSUE TITLE
Feature request: Accept manually-generated XML request body and / or support request hook

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#12450]
ServiceBus namespace API uses XML. The XML that msrest serializes by using Python's xml ElemetTree library doesn't use default namespace. In some cases the serialized XML isn't compatible with ServiceBus, even though it's correct XML.

So I was thinking of two workarounds:
1. making the XML in correct format and passing the XML string as request body. But this doesn't work because the XML string will be treated as a JSON string and be wrapped in an extra pair of quotation marks. So the service doesn't understand this string, which is literally not an XML string with the extra quotation mark.
2. or still passing the ElementTree to request body to use the msrest serializer, and massaging the message with a http request hook function. If we use option 1 this is not required. But in general this might be helpful in some cases, like the response hook.

Now I'm using a Pipeline Policy to do the message massage. It's like the above option 2 but it's not as good because the policy works on every http request of the same client. Not every request needs this policy to work and different requests may need different XML changes.

**Comment by lmazuel** [comment]
It's a azure-core feedback, especially (1), Let's keep the issue for brainstorm. It's low priority to me though to be clear, since there is a policy workaround already, and we actually generates a valid XML and it's the server that is not XML compliant.
