### ISSUE TITLE
 how to receiving message from Topic>Subscription in Python using azure==0.50.1 ver.

### ISSUE THREAD

**Issue by manojkumarpotlapalli** [Azure/azure-sdk-for-python#12467]
**Describe the bug**
can you please provide sample snippet for ServiceBusClient.get_subscription_receiver()
I am seeing error while I am trying to connect to ServiceBusClient.get_subscription_receiver.
 
***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***

message = ServiceBusClient.get_subscription_receiver(TOPIC_NAME, SUBSCRIPTION_NAME)

AttributeError: 'ServiceBusClient' object has no attribute 'get_subscription_receiver'

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure 0.5.1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kaerm** [comment]
@manojkumarpotlapalli thanks for logging the issue, @KieranBrantnerMagee can you take a look at this

**Comment by yunhaoling** [comment]
Hi @manojkumarpotlapalli ,

I'm assuming you're trying the sample code in our master branch.
The sample code in the master branch is for the latest azure-servicebus sdk v7.0.0b4 not for v0.50 -- in v0.50, ServiceBusClient doesn't have `get_subscription_receiver` method.

We've decided deprecated the old preview azure-servicebus v0.50, please shift to our latest service bus v7 which is currently in preview and could be installed by `pip install azure-servicebus --pre`.

If you still want samples for v0.50, please refer to the samples [here](https://github.com/Azure/azure-sdk-for-python/tree/servicebus_v0.50.3/sdk/servicebus/azure-servicebus/samples) on the branch [servicebus_v0.50.3](https://github.com/Azure/azure-sdk-for-python/tree/servicebus_v0.50.3).

**Comment by yunhaoling** [comment]
Hey @manojkumarpotlapalli ,

I'm closing the issue assuming that you've already got the problem solved.
Feel free to re-open the issue and reach out to us if you still have troubles with the samples.
