### ISSUE TITLE
How to use the azure python sdk in DEBUG mode

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1255]
Hi,

I want to see the python sdk logging info from my application. Please let us know, how to set the azure python sdk in DEBUG mode.

Thanks,
Vikram

**Comment by lmazuel** [comment]
Hi @VikramAIS 
Assuming you are talking about packages prefixed with "azure-mgmt-", we use the [logging](https://docs.python.org/3.6/library/logging.html) package in our two internal libraries `msrest` and `msrestazure`.
We use the [logging.getLogger(\_\_name__) paradigm](https://docs.python.org/3.6/howto/logging.html#logging-advanced-tutorial) to do so, so you can expect to find loggers prefixed by `msrest` and `msrestazure`
Thanks,
