### ISSUE TITLE
Review ObjectSerializer proposal for Python

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#12557]
https://github.com/Azure/azure-sdk/issues/1454 tracks the proposal for ObjectSerializer from the .Net perspective.
Java has something similar.

We need to review the discussion there and come up with corresponding proposal in Python for the ObjectSerializer

One upcoming use case for this would be the Avro serializers for Azure Event Hubs.

cc @lmazuel

**Comment by ramya-rao-a** [comment]
Related issue in JavaScript: https://github.com/Azure/azure-sdk-for-js/issues/10069

**Comment by lmazuel** [comment]
C#: https://github.com/Azure/azure-sdk-for-net/pull/12258

**Comment by lmazuel** [comment]
No more planned work for now. Closing.
