### ISSUE TITLE
Onboard Schema Registry service

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#12559]
Schema Registry is a new service that is currently in private preview.
This issue is to track work to onboard the SDK for this service.
This work is planned for the August milestone and does not involve shipping the package which will be done in the September milestone.

- decide package name
- auto generate the package using the latest code generator on the [swagger](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/schemaregistry/azure-data-schemaregistry/swagger/swagger.json) 
- set up CI 

For reference, please see the [Java SDK for Schema Registry](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/schemaregistry/azure-data-schemaregistry)

**Comment by ramya-rao-a** [comment]
Please wait until the swagger makes it to the https://github.com/Azure/azure-rest-api-specs/ repo. I'll post an update here when it does

**Comment by ramya-rao-a** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/10220 is the link to the PR adding the swagger to the rest-api-specs repo. Please give this a try and see if there are any issues

**Comment by YijunXieMS** [comment]
Code is generated with the swagger file in the above mentioned PR. There is a warning raised by autorest. I've pasted detailed information to that PR comment.

WARNING (PreCheck/SchemaMissingType): The schema 'SchemaId' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'
