### ISSUE TITLE
azure.storage.blob.ContainerClient() initializer does not support emulated blob storage from Azurite

### ISSUE THREAD

**Issue by chrisyeh96** [Azure/azure-sdk-for-python#12568]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.3.2
- **Operating System**: Windows 10 Version 10.0.19041 Build 19041, running WSL 1
- **Python Version**: 3.8.3

**Describe the bug**
`azure.storage.blob.ContainerClient()` throws errors on emulated local blob storage.

**To Reproduce**

```
from azure.storage.blob import ContainerClient
ContainerClient(
    account_url='http://127.0.0.1:1000/devstoreaccount1',
    container_name='newcontainer',
    credential='Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==')
```

Running Code in Python REPL:
```pycon
>>> from azure.storage.blob import ContainerClient
>>> ContainerClient(
...     account_url='http://127.0.0.1:1000/devstoreaccount1',
...     container_name='newcontainer',
...     credential='Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cyeh/miniconda3/envs/env/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 150, in __init__
    super(ContainerClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "/home/cyeh/miniconda3/envs/env/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 90, in __init__
    self.credential = format_shared_key_credential(account, credential)
  File "/home/cyeh/miniconda3/envs/env/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 330, in format_shared_key_credential
    raise ValueError("Unable to determine account name for shared key credential.")
ValueError: Unable to determine account name for shared key credential.
>>>
```

**Expected behavior**

There should not be any error. Both [Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite) and the [Azure storage emulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator) assume the `'http://127.0.0.1:1000/devstoreaccount1'` account URL, but it seems like the Azure Python SDK sadly does not support this.

**Comment by kaerm** [comment]
cc: @jongio

**Comment by xiafu-msft** [comment]
Hi @chrisyeh96 
The second commit in https://github.com/Azure/azure-sdk-for-python/pull/12619 is to fix this problem.
Currently you can use this as a workaround
```
credential={
    "account_name": "youraccountname",
    "account_key": "youraccouantkey"
}
```

**Comment by xiafu-msft** [comment]
The package has been released, you can install azure-storage-blob==12.4.0 to use the package with the problem fixed.

**Comment by chrisyeh96** [comment]
Thank you @xiafu-msft! Finally got around to updating to the latest version of azure-storage-blob (12.5.0), and I can confirm that this issue has been fixed.

**Comment by CHBrianLiu** [comment]
Hi there,

I was trying to use Docker to run my application which involves interaction with Azure blob storage. However, when I used Azurite to test it locally, I assigned the `account_url` `http://host.docker.internal:10000/devstoreaccount1`, but the client library seemed not able to parse the URL.

```python
container_name: ContainerClient(
    account_url="http://host.docker.internal:10000/devstoreaccount1",
    container_name="container_name",
    credential="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
)
```

```
  File "./app/models/azure_storage_blob.py", line 20, in <dictcomp>
    container_name: ContainerClient(
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 151, in __init__
    super(ContainerClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 94, in __init__
    self.credential = _format_shared_key_credential(self.account_name, credential)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 346, in _format_shared_key_credential
    raise ValueError("Unable to determine account name for shared key credential.")
ValueError: Unable to determine account name for shared key credential.
```

Then I took a look at the commit @xiafu-msft mentioned above, it seems that the logic to determine if the user is using Azurite is by `localhost` and `127.0.0.1` keywords.

**Comment by CHBrianLiu** [comment]
Hi there,

I was trying to use Docker to run my application which involves interaction with Azure blob storage. However, when I used Azurite to test it locally, I assigned the `account_url` `http://host.docker.internal:10000/devstoreaccount1`, but the client library seemed not able to parse the URL.

```python
container_name: ContainerClient(
    account_url="http://host.docker.internal:10000/devstoreaccount1",
    container_name="container_name",
    credential="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
)
```

```
  File "./app/models/azure_storage_blob.py", line 20, in <dictcomp>
    container_name: ContainerClient(
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 151, in __init__
    super(ContainerClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 94, in __init__
    self.credential = _format_shared_key_credential(self.account_name, credential)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 346, in _format_shared_key_credential
    raise ValueError("Unable to determine account name for shared key credential.")
ValueError: Unable to determine account name for shared key credential.
```

Then I took a look at the commit @xiafu-msft mentioned above, it seems that the logic to determine if the user is using Azurite is by `localhost` and `127.0.0.1` keywords.

**Comment by varun-shahdadpuri** [comment]
@xiafu-msft How do we use Azurite in case we cannot expose Azurite using localhost or 127.0.0.1?

**Comment by amishra-dev** [comment]
Hi @varun-shahdadpuri it might be better to ask that question [here](https://github.com/Azure/Azurite/issues)
I think the SDK can parse IP addresses for the azurite case
