### ISSUE TITLE
Inaccurate type comment in functions for azure-cosmos package

### ISSUE THREAD

**Issue by sl-sandy** [Azure/azure-sdk-for-python#12570]
- **Package Name**: azure-cosmos
- **Package Version**: 4.0.0
- **Operating System**: win10
- **Python Version**: 3.8

**Describe the bug**
For the query related functions in container.py which has the optional "parameters", all theses functions comment the parameters with type Optional[List[str]]. This leads to code highlit and warning in IDE.

**To Reproduce**

    container.query_items(

        query='SELECT * FROM products p WHERE p.productModel = @model',

            parameters=[

                dict(name='@model', value='Model 7')

            ],

        enable_cross_partition_query=True

    )

When using this demo code, IDE will give a warning on the type of "parameters".

**Expected behavior**
Change the type comment of "parameters" of query functions to Optional[List[dict]].

**Comment by kaerm** [comment]
@sl-sandy thanks for reporting this, adding @southpolesteve and @annatisch to take a look at this

**Comment by notlaforge** [comment]
@sl-sandy which IDE were you using?

**Comment by sl-sandy** [comment]
@notlaforge My IDE is the Pycharm community. I tried version 2019.3 and 2020.1 and both can reproduce this.
