### ISSUE TITLE
iter method on dict doesn't work in python 3.x

### ISSUE THREAD

**Issue by dalmat36** [Azure/azure-sdk-for-python#12617]
https://github.com/Azure/azure-sdk-for-python/blob/f72e4a08f0502205a515691b82513c65f3517d4a/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py#L94

**Comment by dalmat36** [comment]
Log message from azure function: 
Result: Failure Exception: AttributeError: 'dict' object has no attribute 'iter' Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 336, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/home/miniconda/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 470, in __run_sync_func return func(**params) File "/home/site/wwwroot/ConvertGribToParquet/GribToParquet.py", line 65, in main download_file.write(blob_client.download_blob().readall()) File "/home/miniconda/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer return func(*args, **kwargs) File "/home/miniconda/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 617, in download_blob return StorageStreamDownloader(**options) File "/home/miniconda/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 316, in __init__ self._response = self._initial_request() File "/home/miniconda/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 403, in _initial_request process_storage_error(error) File "/home/miniconda/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 94, in process_storage_error for info in error_body.iter():

**Comment by xiafu-msft** [comment]
Hi @dalmat36

Thanks for reaching out!
Can you give us more details about what you were trying to do? We need some info to reproduce the problem on our side.
You can paste the code you were using! Thanks!

**Comment by wrobell** [comment]
You can replicate the issue by calling ` azure.storage.filedatalake.FileSystemClient.get_paths` on non-existing path.
