### ISSUE TITLE
SDK 2.0 QueueService class instances not pickleable - QueueService can't be used in Python MP environment

### ISSUE THREAD

**Issue by lstavenhagen** [Azure/azure-sdk-for-python#1261]
Instances of the QueueService class in the 2.0 SDK appear to not be serializable by the pickle module in Python 2.7, and therefore it can't be used in a Python MP context (eg. in Process objects). The default decoding/encoding callback functions appear to be implemented in a static class QueueMessageFormat using @staticmethod methods, which appear not to be pickleable. 
A workaround is to implement custom "non-static" callbacks and set the instance fields in the QueueService object to these custom callbacks.

Perhaps this design pattern should be changed so the QueueService class is pickleable by default, or guidance could be given to implement your own encode/decode callbacks (forgive me if this is already documented).

Platform: Windows
Python version: 2.7.9 +

Reproducible source code scenario distilled from SDK code:

```python
import pickle

class QueueMessageFormat:
    @staticmethod
    def noencode(data):
        return data     
    @staticmethod
    def nodecode(data):
        return data
class QueueService(object):
    def __init__(self):
        self.encode_function = QueueMessageFormat.noencode
        self.decode_function = QueueMessageFormat.nodecode
def main():
    f=QueueService()
    with open("pickleme.txt","wb") as output:
        pickle.dump(f,output)
if __name__ == "__main__":
    main()
```
This example yields "pickle.PicklingError: Can't pickle <function noencode at 0x02880930>: it's not found as __main__.noencode"

Azure SDK install information ("pip freeze azure")
adal==0.4.5
asn1crypto==0.22.0
azure==2.0.0
azure-batch==3.0.0
azure-common==1.1.6
azure-datalake-store==0.0.12
azure-graphrbac==0.30.0
azure-keyvault==0.3.5
azure-mgmt==1.0.0
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==4.0.0
azure-mgmt-cdn==0.30.3
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==1.0.0
azure-mgmt-containerregistry==0.2.1
azure-mgmt-datalake-analytics==0.1.6
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.1.6
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.0.1
azure-mgmt-documentdb==0.1.3
azure-mgmt-iothub==0.2.2
azure-mgmt-keyvault==0.31.0
azure-mgmt-logic==2.1.0
azure-mgmt-monitor==0.2.1
azure-mgmt-network==1.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-redis==4.1.0
azure-mgmt-resource==1.1.0
azure-mgmt-scheduler==1.1.2
azure-mgmt-sql==0.5.3
azure-mgmt-storage==1.0.0
azure-mgmt-trafficmanager==0.30.0
azure-mgmt-web==0.32.0
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==5.6.130
azure-servicemanagement-legacy==0.20.6
azure-storage==0.34.3
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
cryptography==1.9
enum34==1.1.6
futures==3.1.1
idna==2.5
ipaddress==1.0.18
isodate==0.5.4
keyring==10.4.0
msrest==0.4.11
msrestazure==0.4.10
oauthlib==2.0.2
pathlib2==2.3.0
pycparser==2.17
PyJWT==1.5.2
python-dateutil==2.6.0
pywin32-ctypes==0.1.2
requests==2.18.1
requests-oauthlib==0.8.0
scandir==1.5
six==1.10.0
urllib3==1.21.1

**Comment by lmazuel** [comment]
Hi @lstavenhagen 
We unfortunately are in a maintenance mode for the Service Bus HTTP package, since the Service Bus team now recommends to use [AMQP and Proton](https://qpid.apache.org/proton/) :(
It might be possible that I take a look, but I have ETA. Your fastest solution is probably to try to do a PR on which we can discuss.
Thank you,

**Comment by lstavenhagen** [comment]
Hi, I'm afraid I don't quite understand your response. This is an issue just with the QueueService class, not anything to do with Service Bus services. So I'm not sure what that has to do with this particular item?
I also don't quite understand the suggestion to use Proton instead - are the Azure QueueService, or Service Bus services for that matter, being deprecated and/or phased out?

Also, what is a "PR"?

Thank you, LS

**Comment by lmazuel** [comment]
Hi @lstavenhagen 

Sorry I saw "Queue" and concluded too fast you were talking about ServiceBus (SB being in this repository), but it seems you're talking about Storage (Storage not being in this repository). The "azure" 2.0 bundle package is a meta-package that installs several packages at once (as you can see in your "pip freeze"), so "SDK 2.0" by itself is not enough to clearly point to a specific feature.

The QueueService class is part of the "azure-storage" package, and this package is directly owner by the Storage service team at Microsoft on this repository: https://github.com/Azure/azure-storage-python
Please ask your question there and you'll have the real owner and devs of this class to answer your question.

About PR, it's [pull request](https://help.github.com/articles/about-pull-requests/). It's a common idiom on Github, sorry I have wrongly assumed you were familiar with.

Sorry again for the misunderstanding,
Thanks,

**Comment by lstavenhagen** [comment]
Hi,
Ah I see - understood. Ok I'll post this as an issue in that repository. Apologies on my end as well since I'm just now learning about Github :)

Thank you very much!

LS

**Comment by lmazuel** [comment]
Thank you @lstavenhagen :)
