### ISSUE TITLE
Can not install azure-identity with poetry with --allow-prereleases

### ISSUE THREAD

**Issue by NZSmartie** [Azure/azure-sdk-for-python#12625]
- **Package Name**: azure-identity
- **Package Version**: 1.4.0b6
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8

**Describe the bug**
When using [Poetry](https://python-poetry.org/) to manage a python project. Installing the current pre-release version of azure-identity fails with a max recursion depth error.

**To Reproduce**
1. Install poetry
   ```bash
   pip install poetry
   ```
1. Set up a new poetry project in an empty directory
   ```bash
   mkdir azure-identity-test
   poetry init -n # -n specifies non-interactive and uses defaults
   ```
1. Install the prerelease of `azure-identity`
   ```bash
   poetry add azure-identity --allow-prereleases
   ```
1. Observe the following output
   ```
   Creating virtualenv azure-identity-test-ZMyS48q3-py3.8 in /home/nzsmartie/.cache/pypoetry/virtualenvs
   Using version ^1.4.0-beta.6 for azure-identity
   
   Updating dependencies
   Resolving dependencies... (8.4s)
   
   [RecursionError]
   maximum recursion depth exceeded while calling a Python object
   ```

**Expected behavior**
The package would install without issues along with its dependencies.

**Additional context**
Poetry has difficulty with multiple same name dependencies with different version requirements: https://github.com/python-poetry/poetry/issues/1238

When enabling verbosity as the package is installed. there's an almost never ending loop of the following issue being produced.

```
Different requirements found for portalocker (>=1.0,<2.0) and portalocker (>=1.6,<2.0).
```
as produced by:
```bash
poetry add azure-identity --allow-prereleases -vvv
```

**Comment by chlowell** [comment]
Thanks for reporting this. `azure-identity` gets `portalocker` transitively from `msal-extensions`. Since we do need that library and it isn't part of the Azure SDK, I'm closing this issue in favor of AzureAD/microsoft-authentication-extensions-for-python#62.
