### ISSUE TITLE
Cannot refer to azure.storage in Python 2.7

### ISSUE THREAD

**Issue by kjw217** [Azure/azure-sdk-for-python#12632]
```python
# setup.py
# python: 2.7.5
# setuptools: 40.6.2

from setuptools import setup


setup(
    install_requires=[
        'azure==1.0.3',
    ],
)
```
When I use a command '**python setup.py install**' using the above `setup.py`, the `import azure` statement refers to `.../site-packages/azure_nspkg-3.0.2-py2.7.egg/azure/` directory. But, the directory has not any submodules like `storage`. So, it raises `ImportError: no module named storage` if I states `import azure.storage`.

When I tried it python 3.x, it worked well. But, I should use the python 2.7 and `setuptools`.
So, I want to know how to use the `azure` package in python 2.7 with `setuptools`.

**Comment by lmazuel** [comment]
Hi @kjw217 
This version of `azure` has been released 4.5 years ago and is not supported anymore. In fact, the `azure` package itself is not supported anymore and has been deprecated, in favor of direct SDK installation.
If you wish to use storage as it was 4.5 years ago, you can install `azure-storage==0.20.3`, but this package won't be supported anymore as well.
thanks,
