### ISSUE TITLE
[azure-cognitiveservices-knowledge-qnamaker]Fix name qn_amakaer

### ISSUE THREAD

**Issue by bingisbestest** [Azure/azure-sdk-for-python#12634]
- **Package Name**:  azure-cognitiveservices-knowledge-qnamaker
https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-knowledge-qnamaker/azure.cognitiveservices.knowledge.qnamaker.runtime?view=azure-python

Rename qn_amakaer to qna_maker

**Comment by lmazuel** [comment]
Closing since the problem disapeared with recent versions
