### ISSUE TITLE
sending amqp annotated message of different AMQP Body types design and implementation

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#12652]
API Design:

https://gist.github.com/yunhaoling/8f5a632c4ba4c105b86b255360bb6387#gistcomment-3678799

See history [here](https://github.com/Azure/azure-sdk-for-net/issues/11143) for .net's version of this discussion

We have the same consideration in terms of how to incorporate AMQP body type variants into our design.

@yunhaoling kindly wrote up proposals for our options, to be found [here](https://gist.github.com/yunhaoling/8f5a632c4ba4c105b86b255360bb6387).

This issue tracks work to align on a proposal/get architectural buyin.

**Comment by yunhaoling** [comment]
following up item:

check with the JS team to see if we want to utilize the internal class `AmqpAnnotatedMessage` for sending amqp message with different amqp types

**Comment by yunhaoling** [comment]
according to the amqp spec:
- The body consists of either: one or more data sections, one or more amqp-sequence sections,
or a single amqp-value section.
![image](https://user-images.githubusercontent.com/47871814/112016752-3caec880-8aea-11eb-9915-e1ad67a17a0f.png)

- A sequence section contains an arbitrary number of structured data elements.
![image](https://user-images.githubusercontent.com/47871814/112016671-299bf880-8aea-11eb-946b-74db7c6b078a.png)

question: depending on our current uamqp implementation, wouldn't introducing sequence be a breaking change?
https://github.com/Azure/azure-uamqp-python/blob/master/uamqp/message.py#L101-L111
