### ISSUE TITLE
Python SDK for Azure Advisor Alerts

### ISSUE THREAD

**Issue by spoloj** [Azure/azure-sdk-for-python#12654]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be much easier and better if python SDK is supported for Azure Advisor Alerts as It is difficult to create and maintain Advisor alerts manually when there are multiple subscriptions.

**Describe alternatives you've considered**
I wasn't able to find any SDK for Advisor alerts and only alternate as of now is creating in portal.

*Additional context**

**Comment by Prasanna-Padmanabhan** [comment]
@spoloj apologies for the delay, Azure Advisor alerts are basically activity log alerts. https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/monitor/manage_activity_log_alert.py has a Python sample for creating activity log alerts. And https://docs.microsoft.com/en-us/azure/advisor/advisor-alerts-arm?tabs=CLI has details on the template you can use to set up Advisor alerts.
