### ISSUE TITLE
Look into switching ExponentialRetry (base_client) to azure-core RetryPolicy

### ISSUE THREAD

**Issue by LibbaLawrence** [Azure/azure-sdk-for-python#12672]
pipeline error with hosts

**Comment by seankane-msft** [comment]
@annatisch The StorageRetryPolicy that ExponentialRetry inherits from has a use for the kwarg `hosts` and ExponentialRetry does not. Is this a storage specific kwarg and mean we should continue to use the specific RetryPolicy?
