### ISSUE TITLE
Azure Identity Iron Semester for Python

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#12693]
The Azure Identity library provides Azure Active Directory token authentication support across the Azure SDK. It provides a set of TokenCredential implementations which can be used to construct Azure SDK clients which support AAD token authentication.

This issue tracks the new features, reliability improvements, and the release of minor updates to Azure.Identity for the Python language during September - December 2020

**Comment by lmazuel** [comment]
This epic ended in Dec 2020
