### ISSUE TITLE
Add ADFS / Azure Stack Support

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#12696]
- On-prem active directory instance support
- Requested by CLI / PSH for .NET and Python

- [x] `ClientSecretCredential` and `CertificateCredential` (#13215)
- [x] `SharedTokenCacheCredential` (#13490)
- [x] user credentials (`DeviceCodeCredential`, `InteractiveBrowserCredential`, `UsernamePasswordCredential`)
- [ ] async credentials (waiting for AzureAD/microsoft-authentication-library-for-python#88)

**Comment by chlowell** [comment]
I'm removing the blocking-release tag because the work needed for 1.5.0b1 is complete, but leaving this open on the backlog to track the remaining work of adding ADFS support to async credentials.
