### ISSUE TITLE
[ServiceBus] Replace isodate for iso8601 (datetime/timedelta) strings

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#12704]
ServiceBus management client uses [isodate](https://pypi.org/project/isodate/) to serialize and deserialize iso8601 datetime/duration string. isodate is also used in msrest. 

msrest may replace isodate with [aniso8601](https://pypi.org/project/aniso8601/) to parse iso8601 strings some day because isodate could be desupported. But aniso8601 isn't bidirectional. It doesn't serialize a datetime or timedelta to iso8601 string. So msrest will write its own code to serialize datetime/timedelta. Refer to this [msrest issue](https://github.com/Azure/msrest-for-python/issues/33).

msrest exposes type isodate.duration to users when an iso8601 duration string has year or month. ServiceBus doesn't have year or month in the duration string. So ServiceBus doesn't expose isodate.duration to users. This makes SB easy to replace isodate with any new solutions.

**Comment by lmazuel** [comment]
No needed at least for now, closing
