### ISSUE TITLE
Please help add regression test runs for identity

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#12740]
Now we have regression runs for azure-core. 

Can we add the regression tests for identity as well?

What we want is to install latest bits and run tests against last GA release. So we can make sure we don't introduce breaking changes between two GA releases.

**Comment by scbedd** [comment]
- `azure-identity` is checked against the latest azure-core and earliest azure-core in it's `mindependency` stage.
- `azure-core` [regression](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2631268&view=logs&j=bc4de59b-2944-5a28-4196-8f66e0b31102) checks find the earliest and latest released version of azure-identity that is released, and runs tests against them.

I think these are covered scenarios. Closing. Feel free to reopen if you want @xiangyan99.

**Comment by xiangyan99** [comment]
@scbedd what we are looking for is regression validation.

e.g. currently we install latest GAed identity and run storage tests.

What we want to validate is install the live identity from main and run those tests to catch breaking changes/regressions.

Do you know if we have such coverage in our current matrix?

Thanks.

**Comment by scbedd** [comment]
> What we want to validate is install the live identity from main and run those tests to catch breaking changes/regressions.

I laid out the two ways we test, can you give me a bit more detail about what you mean by regression?

> What we want to validate is install the live identity from main and run those tests to catch breaking changes/regressions.

Doesn't the `mindependency` check do literally exactly this? Current identity from `main` (or your pr) running against earliest and latest `azure-core` that it can depend on?

**Comment by scbedd** [comment]
Had a chat with @xiangyan99 about this. 

We need a new regression step that runs based on dev_requirements contents + actual dependencies.

This is a **live test** invocation, it has nothing to do with recorded tests.

One way we could recognize this is to check dev_requirements for any azure-* dependency.
   if present, that is a package that should be regression tested.
   A regression test means running **live tests** for that target using the **identity from disk NOT PYPI**
