### ISSUE TITLE
Consider reconnecting session link on transient errors

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-python#12750]
See https://github.com/Azure/azure-sdk-for-net/pull/13735

**Comment by JoshLove-msft** [comment]
Just to clarify, in .NET we won't retry on a `SessionLockLost` - this is still considered non-retriable when it comes from the service. The change was to allow what are considerd retriable errors (e.g. ServiceTimeout) to be retried when using sessions even if the session receiver link is closed. Previously, when the session receiver link is closed, we would not retry what would otherwise be retriable errors.

**Comment by yunhaoling** [comment]
Closing the issue. As per our OOB discussion, session receiver is treated the same as normal receiver -- Python is already reconnecting session link on transient.
