### ISSUE TITLE
Azure Storage Blob: delete_blobs returns "tuple index out of range" when list_blobs are zero

### ISSUE THREAD

**Issue by dr-dolittle** [Azure/azure-sdk-for-python#12779]
- **Package Name**:  azure-storage-blob
- **Package Version**: 12.3.2 
- **Operating System**: Windows
- **Python Version**:  3.8.1

I retrieve blobs matching a certain pattern and then delete them. Currently it is implemented with a (costly) workaround as you can see in the following issue: https://github.com/Azure/azure-sdk-for-python/issues/12778

When passing `blob_paged` directly to `delete_blobs` it works as long as `blob_paged` is not zero, but if it is zero (i.e. no blob matches the prefix) it returns the exception `tuple index out of range`.

Can you please adjust the behavior that `delete_blobs` can handle `blob_paged` even if it is zero?

Thanks

**Comment by xiafu-msft** [comment]
Hi @dr-dolittle

Thanks for reporting this issue! the pr above should resolve the problem!

**Comment by xiafu-msft** [comment]
I guess we can close this one since it's describing the same thing as #12778 right?

**Comment by xiafu-msft** [comment]
The fix has been release, so we will close this issue! Let me know if you want to reopen it or you have other questions!

**Comment by xiafu-msft** [comment]
The fix has been release, so we will close this issue! Let me know if you want to reopen it or you have other questions!
