### ISSUE TITLE
Azure ModelPackage class returns wrong location

### ISSUE THREAD

**Issue by Mystorius** [Azure/azure-sdk-for-python#12780]
- **Package Name**: Azure ModelPackage
- **Package Version**: azureml-contrib-services-1.10.0 azureml-core-1.10.0.post1
- **Operating System**: mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04:20200723.v1
- **Python Version**: /opt/hostedtoolcache/Python/3.7.8/x64

**Describe the bug**
We got a bug that the  ModelPackage class does not return the correct location of a registered image.

From the Documentation one should do:

`from azureml.core import Model

package = Model.package(ws, [model], inference_config)
package.wait_for_creation(show_output=True)
"Display the package location/ACR path"
print(package.location)`

And the return should look like this:
`<acrinstance>.azurecr.io/package@sha256:<imagename>`
for example:
`diml*********.io/package:20200729142244`

However the return looks like this:
`<acrinstance>.azurecr.io/package@sha256:<digest>`
for example:
`diml*********.io/package@sha256:f759498600bb248c08f73ee49*****716d63c6586e69d7e464568e*****`

This is a big problem as we cant relay the information to our release pipeline to pull the correct image as we need the imagename tag and not the digest to pull the correct image.
We tried using the function `package.get_container_registry()` however there is also no image name returned.

We also noticed that the .package() function creates a second entry in our azure container registry with the naming of repository: `azureml/azureml_5faac73d1c80b1*****` were we can observe the same created docker image as under the naming `diml*********.io/package:20200729142244` However other than scanning the log file, there is currently no way to retrieve the above mentioned location either.

Currently we are not able to make automatic releases as the the return of the image packages does not include the correct location were the image is created that can be used in a docker pull command.

We use this feature since about 6 months and we have that bug since yesterday as our automatic releases were falling.

**To Reproduce**
1. Create a simple ML Model
2. call `package = Model.package(ws, [model], inference_config)`
3. call `package.wait_for_creation(show_output=True)`
3. call `package.location`

**Expected behavior**
Retrieve the location of the created image that can be used in a docker pull command.

**Comment by swatig007** [comment]
@Mystorius apologies for the delayed response. is this still an issue?

**Comment by liakaz** [comment]
Currently the behavior is that model package will always return the digest associated with the built image. However it still does tag the image with the user requested tag, that is why you can see it in your ACR. If the digest is of no use to you, you can disregard it and construct the image path on your own, since you know what you expect it to look like (i.e: diml*********.io/package:20200729142244) That is the current work around that we have in place. I hope this helps.

**Comment by shivanissambare** [comment]
Hi,
Closing the issue, please re-open if this didn't solve your problem.

**Comment by shivanissambare** [comment]
#please-close
