### ISSUE TITLE
Dumping outputs/ & logs/ in ADLS gen2 datastore

### ISSUE THREAD

**Issue by Azrael1** [Azure/azure-sdk-for-python#12823]
- **Package Name**: `azureml`
- **Package Version**: 0.2.7
- **Operating System**: Windows
- **Python Version**: 3.7

**Describe the bug**
I am running the BERT algorithm on Azure, where I am using the python-sdk for the same, I define the output directory as 

`output_dir = Dataset.File.from_files((ds,'/path/on/adls-gen-2-datastore/here/'))
`
I get the error - 

`UserError: User program failed with PermissionDeniedError: /tmp/tmp8kq34epx/train.tf_record; Read-only file system
`

**To Reproduce**
1. Dump any output folder of an experiment to an ADLS gen2 datastore 

**Expected behavior**

I expected an output folder in my datastore, at the desired location.

**Screenshots**

**Additional context**

**Comment by Azrael1** [comment]
If this is not possible, or not implemented yet, how can I get the outputs in my local directory(from where I am running the experiments then?

**Comment by meyetman** [comment]
Hi @Azrael1! I would need a little bit more information to help here, but I'll list out some potential solutions:

If your data is a Tabular dataset, and you are using pipelines, try https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.output_dataset_config.outputtabulardatasetconfig?preserve-view=true&view=azure-ml-py
If your data is a File dataset, and you are using pipelines, try https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.outputfiledatasetconfig?preserve-view=true&view=azure-ml-py

Also, check your permissions by reading up on accesses and permissions here https://docs.microsoft.com/en-us/azure/machine-learning/how-to-access-data#storage-access-and-permissions

Let me know if these don't work!

**Comment by v-strudm-msft** [comment]
Should you still have questions regarding this issue, please comment here and reopen it. We're closing it for now.
