### ISSUE TITLE
HttpLoggingPolicy should acknowledge the existence of a body

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#12828]
By design, HttpLoggingPolicy does not log the body of the request. However, this makes debugging complicated in some scenario, when we want at least to know if _any_ body has been sent.

This issue is about adding something like:
```python
                if isinstance(http_request.body, types.GeneratorType):
                    _LOGGER.info("File upload")
                elif http_request.body:
                    _LOGGER.info("A body is sent with the request")
                else:
                    _LOGGER.info("No body was attached to the request")                  
``` 
to at least indicate that something was sent or not.

This is pseudo-code, the PR should think about data/files and all possible kind of body a request can hold.

**Comment by xiangyan99** [comment]
Fixed in #12830
