### ISSUE TITLE
KeyError: accept / accept-encoding in _get_blob

### ISSUE THREAD

**Issue by dhollsten** [Azure/azure-sdk-for-python#1282]
**Traceback:**
File "/env/local/lib/python2.7/site-packages/azure/storage/blob/baseblobservice.py", line 1932, in get_blob_to_stream
    _context=operation_context)
  File "/env/local/lib/python2.7/site-packages/azure/storage/blob/baseblobservice.py", line 1659, in _get_blob
    operation_context=_context)
  File "/env/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 279, in _perform_request
    raise ex

Happens infrequently with an incomplete traceback.

**pip freeze | grep azure**
azure==2.0.0
azure-batch==3.0.0
azure-common==1.1.6
azure-datalake-store==0.0.12
azure-graphrbac==0.30.0
azure-keyvault==0.3.5
azure-mgmt==1.0.0
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==4.0.0
azure-mgmt-cdn==0.30.3
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==1.0.0
azure-mgmt-containerregistry==0.2.1
azure-mgmt-datalake-analytics==0.1.6
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.1.6
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.0.1
azure-mgmt-documentdb==0.1.3
azure-mgmt-iothub==0.2.2
azure-mgmt-keyvault==0.31.0
azure-mgmt-logic==2.1.0
azure-mgmt-monitor==0.2.1
azure-mgmt-network==1.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-redis==4.1.0
azure-mgmt-resource==1.1.0
azure-mgmt-scheduler==1.1.2
azure-mgmt-sql==0.5.3
azure-mgmt-storage==1.0.0
azure-mgmt-trafficmanager==0.30.0
azure-mgmt-web==0.32.0
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==5.6.130
azure-servicemanagement-legacy==0.20.6
azure-storage==0.34.3

**Comment by lmazuel** [comment]
Hi @dhollsten,
The storage client has its own Github repository and tracker here: https://github.com/Azure/azure-storage-python
Please open your issue there, since there is no dev from this client here.
Thanks!
