### ISSUE TITLE
Missing agent profiles in ACS

### ISSUE THREAD

**Issue by jmalobicky** [Azure/azure-sdk-for-python#1283]
The Azure cost calculator lists agents that are not defined in the agents profile

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/containerservice/v2017_01_31/models/container_service_agent_pool_profile.py

**Comment by lmazuel** [comment]
Hi @jmalobicky , thanks for the feedback.

@brendandburns what do you think?

**Comment by brendandburns** [comment]
we need to push a swagger update...

**Comment by rjtsdl** [comment]
@jmalobicky , can you elaborate more on the issue? I don't have the context of Azure cost calculator. A minimal repro will be great !

**Comment by jmalobicky** [comment]
The Calculator https://azure.microsoft.com/en-us/pricing/calculator/#container-service5 (You might have to add a Container -> Kubernetes to be able to see the agents)

I was looking for 'F' class agents which are listed in the cost calculator but not listed in the available types so the request to create then within Kubernetes throws an error.

**Comment by rjtsdl** [comment]
AH, i see. I have a pending PR should solve this. You can see, I have added the new 'F' class agents.

https://github.com/Azure/azure-rest-api-specs-pr/pull/105/files#diff-7bab307640fc7c8c78d35d2401287753R401

**Comment by lmazuel** [comment]
Solved in recent Swagger (and then SDK) in my understanding.
