### ISSUE TITLE
How to get tenant list which contain more information?

### ISSUE THREAD

**Issue by dyhe83** [Azure/azure-sdk-for-python#12877]
Hi All,

I'm searching for how to get tenant list by using Python SDK.
After some research I find out [SubscriptionClient][SubscriptionClient] can get list of tenants which only contain `id` & `tenant id`.
But [SubscriptionClient][SubscriptionClient] does not provide sufficient information as [Azure Restful API][RestfulAPI] (name, country code, etc...).

I would like to know is there any other method in Python SDK can list tenants?
Or this maybe a feature in the future.
Many thanks!

---

Restful API:
https://docs.microsoft.com/en-us/rest/api/resources/tenants/list

SubscriptionClient:
https://docs.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.subscriptionclient?view=azure-python#tenants

[SubscriptionClient]: https://docs.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.subscriptionclient?view=azure-python#tenants
[RestfulAPI]: https://docs.microsoft.com/en-us/rest/api/resources/tenants/list

**Comment by ramaganesan-rg** [comment]
Routing to a AAD for this question.

**Comment by chenjianfei2017** [comment]
hi, in python sdk, SubscriptionClient has a member named tenants whose type is TenantsOperations. TenantsOperations has a method:
```
        def extract_data(pipeline_response):
            deserialized = self._deserialize('TenantListResult', pipeline_response)
            list_of_elem = deserialized.value
            if cls:
                list_of_elem = cls(list_of_elem)
            return deserialized.next_link or None, iter(list_of_elem)
```
TenantListResult has country, country code etc, pls have a try

**Comment by dyhe83** [comment]
@chenjianfei2017 many thanks.
I just found out I had wrong import statement.
Two different package will have different output.

### Python
```python
from azure.mgmt import resource, subscription


def get_tenants(sub_client):
    tenants = sub_client.tenants
    print('api_version: ' + tenants.api_version)
    for tenant in tenants.list():
        print(tenant.__dict__.keys())


def main():
    credentials = get_credential()
    token = credentials.token['access_token']

    print('[azure.mgmt.resource.SubscriptionClient]')
    sub_client = resource.SubscriptionClient(credentials)
    get_tenants(sub_client)
    print()
    print('[azure.mgmt.subscription.SubscriptionClient]')
    sub_client = subscription.SubscriptionClient(credentials)
    get_tenants(sub_client)
```

### Output
```
[azure.mgmt.resource.SubscriptionClient]
api_version: 2019-11-01
dict_keys(['additional_properties', 'id', 'tenant_id', 'tenant_category', 'country', 'country_code', 'display_name', 'domains'])
dict_keys(['additional_properties', 'id', 'tenant_id', 'tenant_category', 'country', 'country_code', 'display_name', 'domains'])
dict_keys(['additional_properties', 'id', 'tenant_id', 'tenant_category', 'country', 'country_code', 'display_name', 'domains'])
dict_keys(['additional_properties', 'id', 'tenant_id', 'tenant_category', 'country', 'country_code', 'display_name', 'domains'])

[azure.mgmt.subscription.SubscriptionClient]
api_version: 2016-06-01
dict_keys(['additional_properties', 'id', 'tenant_id'])
dict_keys(['additional_properties', 'id', 'tenant_id'])
dict_keys(['additional_properties', 'id', 'tenant_id'])
dict_keys(['additional_properties', 'id', 'tenant_id'])
```

### Conclusion
should use resource package.
https://pypi.org/project/azure-mgmt-resource/
