### ISSUE TITLE
No name 'storage' in module 'azure

### ISSUE THREAD

**Issue by CoenraadS** [Azure/azure-sdk-for-python#12882]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.3.2
- **Operating System**: Linux
- **Python Version**: 3.7.8

**Describe the bug**
Cannot import package as described in documentation

**To Reproduce**
1. I am working in a python dev container, so I have a very clean environment
`mcr.microsoft.com/vscode/devcontainers/python:0-3.7`

I ensure my environment is `python 3.7.8`

I run `pip install azure-storage-blob`

**Expected behavior**
Code should work

**Screenshots**

![image](https://user-images.githubusercontent.com/5593825/89304131-61465500-d66d-11ea-9038-bec401bb6e40.png)

**Additional context**
`pip 20.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

```
Package            Version
------------------ ---------
azure-core         1.7.0
azure-storage-blob 12.3.2
certifi            2020.6.20
cffi               1.14.1
chardet            3.0.4
cryptography       3.0
idna               2.10
isodate            0.6.0
msrest             0.6.18
oauthlib           3.1.0
pip                20.2
pycparser          2.20
requests           2.24.0
requests-oauthlib  1.3.0
setuptools         49.2.0
six                1.15.0
urllib3            1.25.10
wheel              0.34.2
```

**Comment by lmazuel** [comment]
Hi @CoenraadS 
It's because your file is called `azure.py` this confuses Python on who is the right `azure` namespace: your script or the SDK installation?
Rename your file and you should be good ;)

**Comment by CoenraadS** [comment]
Oh no how embarrassing 😳

Ty! For some reason never even crossed my mind..

**Comment by lmazuel** [comment]
No problem :). Feel free to open any issues if you have questions on our SDK. Thanks!
