### ISSUE TITLE
Unable to Pickle Array of Message Objects

### ISSUE THREAD

**Issue by dgokeeffe** [Azure/azure-sdk-for-python#12901]
- **Package Name**: azure-servicebus
- **Package Version**: 7.0.0.0b4
- **Operating System**: Red Hat 4.8.5-39
- **Python Version**: 3.6.8

**Describe the bug**
When attempting to pickle.dump() an array of Message objects a TypeError is raised.

**To Reproduce**
1. Attempt to pickle a Message object

**Expected behavior**
The object is pickled correctly

**Screenshots**
```
import pickle
from azure.servicebus import Message

msgs = [Message(body={"test"})]
pickle.dump(msgs, open("./dump", "wb"))
```
```
File "stringsource", line 2, in uamqp.c_uamqp.StringValue.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

**Comment by KieranBrantnerMagee** [comment]
Hey @dgokeeffe 

Thanks for bringing this up.  From a brief read of the error I have an inkling what's causing this (the core of this library is a C-based AMQP library) and why it might not play well with Pickle.  I've put this on our backlog as a feature req and we'll need to look into what would be required to address this.

I will say, without making too many promises, that there is a long-term plan to address the AMQP library situation, but we can see if there is any potential workaround in the interim.

**Comment by swathipil** [comment]
Thanks for your patience @dgokeeffe! [Fix ](https://github.com/Azure/azure-uamqp-python/pull/222) will be out in the next uamqp release.
