### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by skasara-CS** [Azure/azure-sdk-for-python#12946]
Facing this issue intermittently!! Iam using azure-storage-blob 12.3.2 version ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer')). Any help here?

**Comment by xiafu-msft** [comment]
Hi @skasara-CS 

Thanks for reaching out! It looks like not a storage sdk problem. 
I saw some github issue or stackoverflow questions about this, can you check https://github.com/psf/requests/issues/3189 to see if it's helpful?

**Comment by skasara-CS** [comment]
Thanks for the reply! The same error is happening in local but not while deploy code in server.Seems like its something to do with my settings.

**Comment by maliha-usui** [comment]
i am having this same issue while trying to install pytorch:

Downloading and Extracting Packages
libuv-1.40.0         | 334 KB    | #################################################################################################################################### | 100% 
typing_extensions-3. | 28 KB     | #################################################################################################################################### | 100% 
pytorch-1.7.0        | 63.4 MB   | #########################################################4                                                                           |  44% 
ninja-1.10.1         | 102 KB    | #################################################################################################################################### | 100% 

("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))
