### ISSUE TITLE
[azure-eventgrid] add system event models

### ISSUE THREAD

**Issue by t-swpill** [Azure/azure-sdk-for-python#12949]
As discussed, for the EG Track 2 SDK, we still need to generate system event models and discuss whether all of these models will fall under a different namespace. Here is a general list of steps to follow/do:

- The System Event models need to be generated based on their schemas defined in the swaggers in all the Microsoft.* subfolders: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/eventgrid/data-plane
- I've already generated the Microsoft.Storage models for testing purposes. In order to generate this, I added the path to the raw swagger in my readme.python_t2.md file here: https://github.com/t-swpill/azure-sdk-for-python/blob/event-grid-track-2/sdk/eventgrid/azure-eventgrid/swagger/README.PYTHON_T2.md .To generate the other models, I think you may need to add the other swaggers as input files in the readme.
- You'll need to import the models into azure/eventgrid/_models.py and add them to the azure/eventgrid/_init_.py file
- You'll need to add all the system event type mappings to the _event_type_mappings variable under the DeserializedEvent model in azure/eventgrid/_models.py. Right now, I just have the variable, but I'm know there's a better way to do it: https://github.com/t-swpill/azure-sdk-for-python/blob/7869363b39860356516933efec375b05df721303/sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py#L137

**Comment by lmazuel** [comment]
Import models should be:
- CloudEvent/EventGridSchema : azure.eventgrid
- All system events : azure.eventgrid.models
