### ISSUE TITLE
Servicebus - Track2 - max_wait_time on receive sometimes seems to terminate slightly early on linux systems.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#12954]
This is likely some sort of clock-skew bug, although it's manifesting in an interesting way.

On linux (windows may not have this problem, we were certainly not able to repro it locally outside of on linux VMs) test_queue_receiver_respects_max_wait_time_overrides will fail if the thresholds are +/- 1 second of the requested max_wait_time, if you're using python date_time to calculate your observable durations.

We should understand why this is and if this is a problem.

**Comment by yunhaoling** [comment]
action time: test uamqp c_counter vs python time/datetime module

**Comment by yunhaoling** [comment]
wait for customer feedback
-----------
open a new one to improve livetest stability
