### ISSUE TITLE
Update EventGrid sample repo for track2

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#12963]
https://github.com/Azure-Samples/event-grid-python-public-consume-events

**Comment by rakshith91** [comment]
https://github.com/Azure-Samples/event-grid-python-public-consume-events/pull/4

Verified that the corresponding samples exist in trac 2

**Comment by rakshith91** [comment]
@lmazuel  tagging you on this so we can decide on how to tackle the mgmt samples

**Comment by lmazuel** [comment]
@rakshith91 Let's do a simple disclaimer in the front Readme to say "This repo is about azure-eventgrid v1, if you are using azure-eventgrid v2, please look here <link>. This repo will be archived once the v2 will be released as stable"
