### ISSUE TITLE
Open up the paging mechanism in list methods.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-sdk-for-python#1296]
Take examples of [list vm](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/compute/v2017_03_30/operations/virtual_machines_operations.py#L635), and [list ad users](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-graphrbac/azure/graphrbac/operations/users_operations.py#L99). In both operations, the internal paging mechanism travels the entire results before returning.The mechanism results in a poor performance when the number of the results is large.

An ideal change is to return results as it fetches data. For example, the list methods can return a generator instead of a list, which allows the consuming application to output the result as the SDK querying the data so as to offer better user experience.

An ultimate solution is to provide server side paging API by allowing `top` and `count` parameter in list function.

**Comment by lmazuel** [comment]
Hi @troydai 

The list methods already return an iterator, we don't return a list. We parse an entire page at once, that is true, but we don't call the next page until the current one is over. It's by design since the beginning.

I'm tempted to close this issue, but maybe I miss something?

**Comment by lmazuel** [comment]
See the base class of all list operation:
https://github.com/Azure/msrest-for-python/blob/master/msrest/paging.py

This implements the iterator protocol.

**Comment by troydai** [comment]
I see. Misread the code. I show myself out.
