### ISSUE TITLE
How to find Backup vault name,vault resource group name, backup policy name via Python sdk need example Please

### ISSUE THREAD

**Issue by onenessboy** [Azure/azure-sdk-for-python#12977]
- **Package Name**:  vault recovery services
- **Package Version**: 
- **Operating System**:  Linux
- **Python Version**:  3.6

**Describe the bug**
How to get values for a given VM, I need to do it via python sdk, I wanted to find below information for a given VM (hostname as parameter) it should fine belwo details

1) Recovery services vault Name
2) Recovery Service Vault resource group for this VM
3) Backup policy Name

**Comment by onenessboy** [comment]
@changlong-liu  can i have some update please

**Comment by pvrk** [comment]
@onenessboy : This [API](https://docs.microsoft.com/rest/api/backup/backupstatus/get) is exactly for that purpose. You only need to provide the ARM ID of the VM, and the result will give you the vault name, backup item name and the policy name. I don't have the python example yet but this API should give some clue.

**Comment by onenessboy** [comment]
@pvrk thanks for that API, but that does not work in our case, we wanted output as per this API https://docs.microsoft.com/en-us/rest/api/backup/backupprotecteditems/list which is we are exactly looking for these to work I need to know backupvaultname, vault resource group name and backuppolicy name to fetch status where I supply filter condition as ```"$filter=backupManagementType eq 'AzureIaasVM' and itemType eq 'VM' and policyName eq '{backup_policy_name}'```  so now the issue is i want to know this information only by passing hostname not all other vault related parameters, i have to find it programatically

**Comment by pvrk** [comment]
@onenessboy : The backupProtectedItems API is in the context of a vault and hence you always need a vault (which means vault name and vault resource group name). You can combine the 2 APIs: pass the ARM ID of the VM to get all the relevant details from check status API and supply the APIs output to backupProtectedItems API to get the relevant result. Of course, this is just my hypothesis.

**Comment by onenessboy** [comment]
> @onenessboy : The backupProtectedItems API is in the context of a vault and hence you always need a vault (which means vault name and vault resource group name). You can combine the 2 APIs: pass the ARM ID of the VM to get all the relevant details from check status API and supply the APIs output to backupProtectedItems API to get the relevant result. Of course, this is just my hypothesis.

:) yeah, forgot to mention all our vms are backuped via vault. same hypothesis, i just had, ok i shall give a try, But can we get it official some usecase sample for this as well  ( i know automation always tricky and difficult than manually seeing it on console :)"  Meanwhile, i will try this messy merging of two API, can some from MS research team do along with me this parallel :) and let me know if i can get some working example please. :)

**Comment by onenessboy** [comment]
Ok Here is my trail with first API you mentioned , get backup status via POST method, i am getting ```{"ErrorCode":"CloudInvalidInputError","Message":{"Language":"en-US","Value":"The current operation failed due to an internal service error \"Invalid input error\". Please retry the operation after some time.\r\nIf the issue persists, please contact Microsoft support."},"Values":[]}```  , i double checked code,i treid to print location and resrouce group name, its printing, that means credentials dont have issue. But above erros says something else...

**Comment by pvrk** [comment]
@onenessboy : For the 1st request, where you asked for a python sample to backup a VM, Sambit was able to prepare a very raw version. Please try this and let us know if this works.

```python
from azure.cli.command_modules.backup._client_factory import (
    vaults_cf, backup_protected_items_cf, protection_policies_cf, virtual_machines_cf, protection_containers_cf, backup_protectable_items_cf, protection_container_refresh_operation_results_cf)
from six.moves.urllib.parse import urlparse
from msrest.paging import Paged
from azure.mgmt.recoveryservicesbackup.models import ProtectedItemResource, AzureIaaSComputeVMProtectedItem

def main():
    vm_name, vm_rg = "name", "rg"
    policy_name = "policy"
    vault_name = "vault"
    vault_rg = "vault_rg"


    # Get protectable item.
    protectable_item = _get_protectable_item_for_vm(cmd.cli_ctx, vault_name, vault_rg, vm_name, vm_rg)


    # Construct enable protection request object
    container_uri = "iaasvmcontainer;vmrg;vmname"
    item_uri = "VM;iaasvmcontainer;vmrg;vmname"
    vm_item_properties = AzureIaaSComputeVMProtectedItem()
    vm_item_properties.policy_id = "policy_Arm_id"
    vm_item_properties.source_resource_id = protectable_item.properties.virtual_machine_id


    vm_item = ProtectedItemResource(properties=vm_item_properties)

    result = client.create_or_update(vault_name, resource_group_name, fabric_name,
                                     container_uri, item_uri, vm_item, raw=True)


def _get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg):
    protection_containers_client = protection_containers_cf(cli_ctx)

    protectable_item = _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg)
    if protectable_item is None:
        refresh_result = protection_containers_client.refresh(vault_name, vault_rg, fabric_name, raw=True)
        _track_refresh_operation(cli_ctx, refresh_result, vault_name, vault_rg)
    protectable_item = _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg)
    return protectable_item


def _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg):
    backup_protectable_items_client = backup_protectable_items_cf(cli_ctx)

    filter_string = _get_filter_string({
        'backupManagementType': 'AzureIaasVM'})

    protectable_items_paged = backup_protectable_items_client.list(vault_name, vault_rg, filter_string)
    protectable_items = _get_list_from_paged_response(protectable_items_paged)

    for protectable_item in protectable_items:
        item_vm_name = _get_vm_name_from_vm_id(protectable_item.properties.virtual_machine_id)
        item_vm_rg = _get_resource_group_from_id(protectable_item.properties.virtual_machine_id)
        if item_vm_name.lower() == vm_name.lower() and item_vm_rg.lower() == vm_rg.lower():
            return protectable_item
    return None


def _track_refresh_operation(cli_ctx, result, vault_name, resource_group):
    protection_container_refresh_operation_results_client = protection_container_refresh_operation_results_cf(cli_ctx)

    operation_id = urlparse(result.response.headers['Location'])).path.split("/")[-1] 
    result = protection_container_refresh_operation_results_client.get(vault_name,resource_group,fabric_name, operation_id, raw=True)

    while result.response.status_code == 202:
        time.sleep(1)s
        result = protection_container_refresh_operation_results_client.get(vault_name,resource_group,fabric_name,operation_id,raw=True)

def _get_list_from_paged_response(obj_list):
    return list(obj_list) if isinstance(obj_list, Paged) else obj_list
```

**Comment by onenessboy** [comment]
> @onenessboy : For the 1st request, where you asked for a python sample to backup a VM, Sambit was able to prepare a very raw version. Please try this and let us know if this works.
> 
> ```python
> from azure.cli.command_modules.backup._client_factory import (
>     vaults_cf, backup_protected_items_cf, protection_policies_cf, virtual_machines_cf, protection_containers_cf, backup_protectable_items_cf, protection_container_refresh_operation_results_cf)
> from six.moves.urllib.parse import urlparse
> from msrest.paging import Paged
> from azure.mgmt.recoveryservicesbackup.models import ProtectedItemResource, AzureIaaSComputeVMProtectedItem
> 
> def main():
>     vm_name, vm_rg = "name", "rg"
>     policy_name = "policy"
>     vault_name = "vault"
>     vault_rg = "vault_rg"
> 
> 
>     # Get protectable item.
>     protectable_item = _get_protectable_item_for_vm(cmd.cli_ctx, vault_name, vault_rg, vm_name, vm_rg)
> 
> 
>     # Construct enable protection request object
>     container_uri = "iaasvmcontainer;vmrg;vmname"
>     item_uri = "VM;iaasvmcontainer;vmrg;vmname"
>     vm_item_properties = AzureIaaSComputeVMProtectedItem()
>     vm_item_properties.policy_id = "policy_Arm_id"
>     vm_item_properties.source_resource_id = protectable_item.properties.virtual_machine_id
> 
> 
>     vm_item = ProtectedItemResource(properties=vm_item_properties)
> 
>     result = client.create_or_update(vault_name, resource_group_name, fabric_name,
>                                      container_uri, item_uri, vm_item, raw=True)
> 
> 
> def _get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg):
>     protection_containers_client = protection_containers_cf(cli_ctx)
> 
>     protectable_item = _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg)
>     if protectable_item is None:
>         refresh_result = protection_containers_client.refresh(vault_name, vault_rg, fabric_name, raw=True)
>         _track_refresh_operation(cli_ctx, refresh_result, vault_name, vault_rg)
>     protectable_item = _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg)
>     return protectable_item
> 
> 
> def _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg):
>     backup_protectable_items_client = backup_protectable_items_cf(cli_ctx)
> 
>     filter_string = _get_filter_string({
>         'backupManagementType': 'AzureIaasVM'})
> 
>     protectable_items_paged = backup_protectable_items_client.list(vault_name, vault_rg, filter_string)
>     protectable_items = _get_list_from_paged_response(protectable_items_paged)
> 
>     for protectable_item in protectable_items:
>         item_vm_name = _get_vm_name_from_vm_id(protectable_item.properties.virtual_machine_id)
>         item_vm_rg = _get_resource_group_from_id(protectable_item.properties.virtual_machine_id)
>         if item_vm_name.lower() == vm_name.lower() and item_vm_rg.lower() == vm_rg.lower():
>             return protectable_item
>     return None
> 
> 
> def _track_refresh_operation(cli_ctx, result, vault_name, resource_group):
>     protection_container_refresh_operation_results_client = protection_container_refresh_operation_results_cf(cli_ctx)
> 
>     operation_id = urlparse(result.response.headers['Location'])).path.split("/")[-1] 
>     result = protection_container_refresh_operation_results_client.get(vault_name,resource_group,fabric_name, operation_id, raw=True)
> 
>     while result.response.status_code == 202:
>         time.sleep(1)s
>         result = protection_container_refresh_operation_results_client.get(vault_name,resource_group,fabric_name,operation_id,raw=True)
> 
> def _get_list_from_paged_response(obj_list):
>     return list(obj_list) if isinstance(obj_list, Paged) else obj_list
> ```

@pvrk thanks for code, the same code I recived from @mepand on issue #12878 , but unfortunately it wont work for our case, as vault name, vault resourg group and backupolicy are hardcoded (i mean need to pass as parameters). As explained earlier in this issue and other issue, the requriement is only we will pass hostname and program should get vaultname, vault resource group, and backup policy for that VM , then trigger the backup.  As you said earlier, even I tried API method backupget status, backupprojtecteditem api , but its failing...... Is that possible for @sambitratha to prepare a sample with API mix model ?

**Comment by onenessboy** [comment]
> > @onenessboy : For the 1st request, where you asked for a python sample to backup a VM, Sambit was able to prepare a very raw version. Please try this and let us know if this works.
> > ```python
> > from azure.cli.command_modules.backup._client_factory import (
> >     vaults_cf, backup_protected_items_cf, protection_policies_cf, virtual_machines_cf, protection_containers_cf, backup_protectable_items_cf, protection_container_refresh_operation_results_cf)
> > from six.moves.urllib.parse import urlparse
> > from msrest.paging import Paged
> > from azure.mgmt.recoveryservicesbackup.models import ProtectedItemResource, AzureIaaSComputeVMProtectedItem
> > 
> > def main():
> >     vm_name, vm_rg = "name", "rg"
> >     policy_name = "policy"
> >     vault_name = "vault"
> >     vault_rg = "vault_rg"
> > 
> > 
> >     # Get protectable item.
> >     protectable_item = _get_protectable_item_for_vm(cmd.cli_ctx, vault_name, vault_rg, vm_name, vm_rg)
> > 
> > 
> >     # Construct enable protection request object
> >     container_uri = "iaasvmcontainer;vmrg;vmname"
> >     item_uri = "VM;iaasvmcontainer;vmrg;vmname"
> >     vm_item_properties = AzureIaaSComputeVMProtectedItem()
> >     vm_item_properties.policy_id = "policy_Arm_id"
> >     vm_item_properties.source_resource_id = protectable_item.properties.virtual_machine_id
> > 
> > 
> >     vm_item = ProtectedItemResource(properties=vm_item_properties)
> > 
> >     result = client.create_or_update(vault_name, resource_group_name, fabric_name,
> >                                      container_uri, item_uri, vm_item, raw=True)
> > 
> > 
> > def _get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg):
> >     protection_containers_client = protection_containers_cf(cli_ctx)
> > 
> >     protectable_item = _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg)
> >     if protectable_item is None:
> >         refresh_result = protection_containers_client.refresh(vault_name, vault_rg, fabric_name, raw=True)
> >         _track_refresh_operation(cli_ctx, refresh_result, vault_name, vault_rg)
> >     protectable_item = _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg)
> >     return protectable_item
> > 
> > 
> > def _try_get_protectable_item_for_vm(cli_ctx, vault_name, vault_rg, vm_name, vm_rg):
> >     backup_protectable_items_client = backup_protectable_items_cf(cli_ctx)
> > 
> >     filter_string = _get_filter_string({
> >         'backupManagementType': 'AzureIaasVM'})
> > 
> >     protectable_items_paged = backup_protectable_items_client.list(vault_name, vault_rg, filter_string)
> >     protectable_items = _get_list_from_paged_response(protectable_items_paged)
> > 
> >     for protectable_item in protectable_items:
> >         item_vm_name = _get_vm_name_from_vm_id(protectable_item.properties.virtual_machine_id)
> >         item_vm_rg = _get_resource_group_from_id(protectable_item.properties.virtual_machine_id)
> >         if item_vm_name.lower() == vm_name.lower() and item_vm_rg.lower() == vm_rg.lower():
> >             return protectable_item
> >     return None
> > 
> > 
> > def _track_refresh_operation(cli_ctx, result, vault_name, resource_group):
> >     protection_container_refresh_operation_results_client = protection_container_refresh_operation_results_cf(cli_ctx)
> > 
> >     operation_id = urlparse(result.response.headers['Location'])).path.split("/")[-1] 
> >     result = protection_container_refresh_operation_results_client.get(vault_name,resource_group,fabric_name, operation_id, raw=True)
> > 
> >     while result.response.status_code == 202:
> >         time.sleep(1)s
> >         result = protection_container_refresh_operation_results_client.get(vault_name,resource_group,fabric_name,operation_id,raw=True)
> > 
> > def _get_list_from_paged_response(obj_list):
> >     return list(obj_list) if isinstance(obj_list, Paged) else obj_list
> > ```
> 
> @pvrk thanks for code, first thanks for all stake holder who doing their best in ths usecase.the same code I recived from @mepand on issue #12878 , _but unfortunately it wont work for our case_, as vault name, vault resourg group and backupolicy are hardcoded (i mean need to pass as parameters). As explained earlier in this issue and other issue, the requriement is only we will pass hostname and **program should get vaultname, vault resource group, and backup policy for that VM** , then trigger the backup. As you said earlier, even I tried API method backupget status, backupprojtecteditem api , but its failing...... Is that possible for @sambitratha to prepare a sample with API mix model tested on your labs ? If we are able to get these vaultname,vault resoruce group, backuppolicy from programtically, then we can address two issues in one shot .hmm

@pvrk  here what I tried using getbackupstatus API which you referred to get vault related info. I will be happy if your team can do some research on this API mix model (seems to be simple) than other method I guess...either for trigger the backup or get the status of protected item. Make some sense ?
'''   
# i am  getting all other key details from system configured azure cli varibales. ..not included that peice of code here
 if (VM_NAME == vm_name):
        print("rg:", resource_group)
        azureregion = vm.location
        print(azureregion)
        BASE_URL = f"https://management.azure.com/Subscriptions/{Subscription_id}/providers/Microsoft.RecoveryServices/locations/{azureregion}/backupStatus?api-version=2017-07-01"
        print(BASE_URL)

headers = {
    "Authorization": 'Bearer '+ credential.token["access_token"]
}

response = requests.post(BASE_URL, headers=headers)
print(response.text)
status = json.loads(response.text)
print(status)
'''

I am getting error like, dont know why, even though back up is running

```
{"ErrorCode":"CloudInvalidInputError","Message":{"Language":"en-US","Value":"The current operation failed due to an internal service error \"Invalid input error\". Please retry the operation after some time.\r\nIf the issue persists, please contact Microsoft support."},"Values":[]}
{'ErrorCode': 'CloudInvalidInputError', 'Message': {'Language': 'en-US', 'Value': 'The current operation failed due to an internal service error "Invalid input error". Please retry the operation after some time.\r\nIf the issue persists, please contact Microsoft support.'}, 'Values': []} ```

**Comment by onenessboy** [comment]
Closing this as resolved.
