### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by rjschwei** [Azure/azure-sdk-for-python#1299]
azure-mgmt-1.0.0/setup.py has: azure-mgmt-cdn~=0.30.3

I cannot appear to find a release of the -cdn component that matches this requirement, cdn release is 1.0.0

**Comment by lmazuel** [comment]
Hi @rjschwei 
The package is on PyPI: https://pypi.python.org/pypi/azure-mgmt-cdn/0.30.3
I think you might be interested by this discussion as well: https://github.com/Azure/azure-sdk-for-python/issues/1295

**Comment by rjschwei** [comment]
Thanks, not sure why I couldn't find it the other day :(

Anyway @glaubitz has resolved our issue by moving forward and fixing our package dependencies.
