### ISSUE TITLE
content_md5 causes TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by thomasmilas-swe-bc** [Azure/azure-sdk-for-python#13003]
- **Package Name**: azure.storage.blob
- **Package Version**: 12.3.2
- **Operating System**: MacOS and Ubuntu Linux
- **Python Version**: 3.7

**Describe the bug**
When uploading a large file I'm trying to use the `content_md5` property of the `ContentSettings` object.

When I try to set the `set_http_headers` with the documented type `str` this fails with TypeError: string argument without an encoding. this comes from the construction of the standard `bytearray`. This is all a bit goofy because I already had to use the base64 package which returns  `bytes`. 

**To Reproduce**

simplified for the issue. My code will chunk to generate md5.

```python
with open(filepath, 'rb') as f:
  hash = hashlib.md5(f.read())
  f.seek(0)
  blobclient.upload_blob(f, content_settings=ContentSettings(content_md5=b64encode(hash.digest()).decode('utf-8)))
```

Providing this content settings configuration for `upload_blob` and `set_http_headers` methods both cause this exception. Looks like different code paths causing the same problem, copy and paste-like. Seems to work fine with V2 of the SDK.

**Expected behavior**
No exceptions and correct md5 so a consumer can validate the result of the whole file.

**Comment by xiafu-msft** [comment]
Hi @thomasmilas-swe-bc

Thanks for reaching out!
if you do `content_md5=hash.digest()` it will work. It's pretty confusing, we will try to make it easier to use.

**Comment by thomasmilas-swe-bc** [comment]
> Hi @thomasmilas-swe-bc
> 
> Thanks for reaching out!
> if you do `content_md5=hash.digest()` it will work. It's pretty confusing, we will try to make it easier to use.

Yea, the ContentSetting object that we are setting `content_md5` on should have the proper docs on what it expects. Seems like this is a carryover from the v2 SDK where a BASE64 string was requried. My linting goes crazy because that hash.digest returns `bytes`

**Comment by xiafu-msft** [comment]
Hi @thomasmilas-swe-bc 

Thanks for your feedback, we will improve the doc to tell the user to pass in byte. Let me know how you feel about this!

**Comment by xiafu-msft** [comment]
we will close this for now and make the doc clear
