### ISSUE TITLE
[Service Bus] Throw error when Entity Path in connection string does not match what is passed to methods that create senders & receivers 

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#13018]
In v7 of the Service Bus package, the ServiceBusClient constructor takes connection string which can have the EntityPath specified in it if the user copied it from the policy created for a queue or topic.

The methods to create senders and receivers expect the queue/topic/subscription name to be passed to them.

This issue is to ensure that if there is a mismatch between the two, we should throw an error.

The reason is that a connection string from a policy from one queue/topic when used with a different entity gives a not so helpful error today. We can pre-empt this and throw a meaningful error ourselves instead.

If we are already doing this, please add a comment here sharing the error message and close this issue

**Comment by KieranBrantnerMagee** [comment]
We should be good to go.

```
E           azure.servicebus.exceptions.ServiceBusAuthenticationError: Entity names do not match, the entity name in connection string is servicebustest_qtwodq3ct; the entity name in parameter is servicebustest_qonevxudr.
```
