### ISSUE TITLE
Erroneous logging message when getting secrets.

### ISSUE THREAD

**Issue by washcycle** [Azure/azure-sdk-for-python#13037]
- **Package Name**: 
azure-common==1.1.25
azure-core==1.8.0
azure-identity==1.4.0
azure-keyvault-certificates==4.1.0
azure-keyvault-keys==4.1.0
azure-keyvault-secrets==4.1.0
azure-storage-blob==12.3.2

- **Operating System**:
ubuntu 18.04

- **Python Version**: 
Python 3.7.7 (default, Jun  9 2020, 18:08:39) 
[GCC 8.3.0] on linux

**Describe the bug**
Using AKS with VMSS and an Azure Identity user assigned. Any time I get a secret I also get this message. This is a non-fatal event and the code retrieves the secret and continues on.

`EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.`

No system variables are set for the azure credential authentication. 

**To Reproduce**
1.  AKS cluster with VMSS with user assigned identity no in same resource group as cluster. 
2. Launch python and get secret from azure vault.

```
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

credential = DefaultAzureCredential()
secret_client = SecretClient(vault_url="https://XXXXXXX.vault.azure.net", credential=credential)
secret_client.get_secret('XXXXX').value
```

**Expected behavior**
Secret without odd message that doesn't make sense when not using environment variables.

**Additional context**
I'm going to verify this happens with a base python container and report back.

**Comment by chlowell** [comment]
Which credential type are you using?

**Comment by washcycle** [comment]
Azure managed identity using https://github.com/Azure/aad-pod-identity 1.6.0 the latest version.

I downgraded to 1.3.1 and no longer got the error.

    pip install azure-identity==1.3.1

**Comment by washcycle** [comment]
```
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

credential = DefaultAzureCredential()
secret_client = SecretClient(vault_url="https://XXXXXXX.vault.azure.net", credential=credential)
secret_client.get_secret('XXXXX').value
```

**Comment by chlowell** [comment]
`DefaultAzureCredential` is a chain of credentials. This message about `EnvironmentCredential` is expected because `DefaultAzureCredential` does attempt to authenticate with that credential before trying managed identity. However, after it succeeds with one credential, an instance of `DefaultAzureCredential` never uses the others again--it always tries to authenticate with the credential which first succeeded. So you should see this message exactly once from each `DefaultAzureCredential` instance. Do you see it multiple times from the same instance?

**Comment by washcycle** [comment]
I do. However, I am using dask and pulling credentials over and over again
for each workers job. Is there a way to disable warnings?

**Comment by chlowell** [comment]
>  Is there a way to disable warnings?
>
You could use `logging` to filter this particular warning. Here's one way:
```py
import logging
import sys

def filter_environment_credential_warning(record):
    if record.name.startswith("azure.identity") and record.levelno == logging.WARNING:
        message = record.getMessage()
        return not message.startswith("EnvironmentCredential.get_token")
    return True

handler = logging.StreamHandler(sys.stdout)
handler.addFilter(filter_environment_credential_warning)
logging.basicConfig(level=logging.INFO, handlers=[handler])
```

> I am using dask and pulling credentials over and over again for each workers job.
>
Do you mean you're creating multiple instances of `DefaultAzureCredential`?

**Comment by washcycle** [comment]
Pulling the secrets multiple times, but in a different process each time is
how I would describe it. Maybe if I make the secrets globals I can mitigate
the excess secret pulling.

Looks something like this pseudo code.

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from dask.distributed import Client
credential = DefaultAzureCredential()
secret_client = SecretClient(vault_url="https://xxxxxx.vault.azure.net",
credential=credential)
# Get connection to db (for pickled objects in dask)
def getconn():
    print("Enter getconn()")
    c = psycopg2.connect(user=secret_client.get_secret("posgres-user"
).value,
                    password=secret_client.get_secret("postgres-password"
).value,
                    host=secret_client.get_secret("postgres-hostname"
).value,
                    dbname=os.getenv('DBNAME', "test"))
    print("Exit getconn()")
    return c

print("Getting DB Connection")
getconn()
db_pool = pool.QueuePool(getconn, max_overflow=10, pool_size=5)


    def foo(self, data):
        tmp_engine = create_engine('postgresql://', pool=db_pool) # do stuff


client = Client()

print("Dashboard link: ", client.dashboard_link)

futures = client.map(self.foo, *kwgs)

**Comment by chlowell** [comment]
If `getconn` in your pseudocode is executed in subprocesses, that explains what you're seeing. `DefaultAzureCredential` will go through, and log, its discovery process the first time it's used. If that happens in N subprocesses, you'll see it logged N times. Here's a few things to try that are better than just filtering the warning:

#### Initialize `DefaultAzureCredential` before subprocessing
Seems like you could send `DefaultAzureCredential` through its discovery routine and even cache a token for Key Vault before subprocessing:
```py
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

credential = DefaultAzureCredential()
credential.get_token("https://vault.azure.net/.default")
secret_client = SecretClient(vault_url="https://xxxxxx.vault.azure.net", credential=credential)
```

#### Use `ManagedIdentityCredential`
If you're using managed identity in deployment and don't need any of the local development magic of `DefaultAzureCredential`, you can just use `ManagedIdentityCredential` directly:
```py
from azure.identity import ManagedIdentityCredential
from azure.keyvault.secrets import SecretClient

credential = ManagedIdentityCredential()
secret_client = SecretClient(vault_url="https://xxxxxx.vault.azure.net", credential=credential)
```

#### Customize the chain of credentials
You can build your own credential chain that doesn't include `EnvironmentCredential`:
```py
from azure.identity import ChainedTokenCredential, ManagedIdentityCredential, VisualStudioCodeCredential
from azure.keyvault.secrets import SecretClient

chain = [ManagedIdentityCredential(), VisualStudioCodeCredential()]
credential = ChainedTokenCredential(chain)
secret_client = SecretClient(vault_url="https://xxxxxx.vault.azure.net",  credential=credential)
```

**Comment by washcycle** [comment]
Gotcha, thanks.

I ended up pull the credentials to a higher scope so the tasks would have them without having to fetch them again.

I wanted to keep the `DefaultAzureCredential` call because we use .env files for development and managed credentials for production and it doesn't require any extra code to handle the different c onfigurations.

Thanks for clearing up the warning messages for me though @chlowell.
