### ISSUE TITLE
[ServiceBus] SDK should attempt to reconnect after service outage.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13044]
Currently this scenario fails as it attempts to use the same authentication as prior, and simply throws an exception.

If this something where we should attempt to reconnect under our retry policy?

Align with other SDKs, decide on course of action, implement.

May need to work with Service Team to find a way to emulate or time a shutdown to test.

**Comment by yunhaoling** [comment]
closing it now as there's no dev plan on the issue, we could reopen in the future.
