### ISSUE TITLE
Missing high-level hello world example for certificate principal usage

### ISSUE THREAD

**Issue by synergiator** [Azure/azure-sdk-for-python#13061]
It seems like there is a missing link for beginners how to use certificate principal authorization in a hello world example demonstrating benefits of SDK usage beyond direct API access.

What I have tried/found out so far:

* I like the "confidential client sample" examples in MSAL and ADAL libraries, but while in the ADAL there has been no usage example, MDAL just demonstrates low-level API usage without providing a usage example in a resource class.

* The online docs for the [subscription client](https://docs.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.subscriptions.subscriptionclient?view=azure-python) look quite scarce and it's not obvious how exactly the auth token should be passed to it.  That is, the [AAD credentials class docs](https://docs.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_active_directory?view=azure-python) seem to miss the certificate usage scenario.

**Comment by changlong-liu** [comment]
Hi @synergiator ,

We are working at the new generation of Python SDK which use auzre-identity for credential. I think you may need this in azure-identity: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.4.0/azure.identity.html#azure.identity.CertificateCredential

Currently 8 packages has released preview versions for the new generation SDK:
appconfiguration: https://pypi.org/project/azure-mgmt-appconfiguration/1.0.0b1/
compute: https://pypi.org/project/azure-mgmt-compute/17.0.0b1/
eventhub: https://pypi.org/project/azure-mgmt-eventhub/8.0.0b1/
keyvault: https://pypi.org/project/azure-mgmt-keyvault/7.0.0b1/
monitor: https://pypi.org/project/azure-mgmt-monitor/1.0.0b1/
network: https://pypi.org/project/azure-mgmt-network/16.0.0b1/
resource: https://pypi.org/project/azure-mgmt-resource/15.0.0b1/
storage: https://pypi.org/project/azure-mgmt-storage/16.0.0b1/

**Comment by synergiator** [comment]
Hi there @changlong-liu, thank you for your reply!
I have understood so far there is ongoing work and some beta/preview releases, but what does this mean for MSAL? Will be a high-level credential configuration possible with these new packages? If possible, please share an example, can't see it from the referenced docs.

**Comment by changlong-liu** [comment]
Hi @synergiator ,
The "az account create" use azure-mgmt-subscription, which has not released the next generation preview.

**Comment by xiangyan99** [comment]
@msyyc looks like azure-mgmt-subscription 2.0.0 has released. Could you help to update the issue?
