### ISSUE TITLE
end of paging error when connecting to client

### ISSUE THREAD

**Issue by onenessboy** [Azure/azure-sdk-for-python#13065]
- **Package Name**:  Resource
- **Package Version**: 
- **Operating System**: Linux
- **Python Version**: 3.6

**Describe the bug**
making client with service principle fails with end of paging error

```
**The below works and list all resource groups:**
tenant_var = None
credential = ServicePrincipalCredentials(tenant=tenant_var, client_id=result[0], secret=result[1])
subscription_client = SubscriptionClient(credential)
subscription = next(subscription_client.subscriptions.list())
#client = MonitorManagementClient(credential, subscription.subscription_id)
client = ResourceManagementClient(credential, subscription.subscription_id)

for item in client.resource_groups.list():
    print(item.name)

**# But below code does not work properly and ending with end of paging issue:**

resource_client = None
credential = None
subscription_client = None
subscription = None
tenant_var = None
for account in accounts:
    print(account)
    new_col = 0
    terminated_col = 0
     jout = get_keys(token,account)
    ak = jout['data']['client_id']
    print("clientid is:",ak)
    sk = jout['data']['client_secret']
    print("secretkey is:",sk)
    credential = ServicePrincipalCredentials(tenant=tenant_var, client_id=ak, secret=sk)
    print(credential)
    subscription_client = SubscriptionClient(credential)
    subscription = next(subscription_client.subscriptions.list())
    #compute_client = ComputeManagementClient(credential, subscription.subscription_id)
    resource_client = ResourceManagementClient(credential, str(subscription.subscription_id))
    print(resource_client)
    time.sleep(10)      
      
    for rg in resource_client.resource_groups.list():    
        print(rg.name)

**Comment by onenessboy** [comment]
> * **Package Name**:  Resource
> * **Package Version**:
> * **Operating System**: Linux
> * **Python Version**: 3.6
> 
> **Describe the bug**
> making client with service principle fails with end of paging error
> 
> **The below works and list all resource groups:**
> 
> ```
> tenant_var = None
> credential = ServicePrincipalCredentials(tenant=tenant_var, client_id=result[0], secret=result[1])
> subscription_client = SubscriptionClient(credential)
> subscription = next(subscription_client.subscriptions.list())
> #client = MonitorManagementClient(credential, subscription.subscription_id)
> client = ResourceManagementClient(credential, subscription.subscription_id)
> 
> for item in client.resource_groups.list():
>     print(item.name)```
> ```
> 
> resource_client = None
> credential = None
> subscription_client = None
> subscription = None
> tenant_var = None
> for account in accounts:
> print(account)
> new_col = 0
> terminated_col = 0
> jout = get_keys(lita_token,account)
> ak = jout['data']['client_id']
> print("clientid is:",ak)
> sk = jout['data']['client_secret']
> print("secretkey is:",sk)
> credential = ServicePrincipalCredentials(tenant=tenant_var, client_id=ak, secret=sk)
> print(credential)
> subscription_client = SubscriptionClient(credential)
> subscription = next(subscription_client.subscriptions.list())
> #compute_client = ComputeManagementClient(credential, subscription.subscription_id)
> resource_client = ResourceManagementClient(credential, str(subscription.subscription_id))
> print(resource_client)
> time.sleep(10)
> 
> ```
> for rg in resource_client.resource_groups.list():    
>     print(rg.as_dict()) ```
> ```

**Comment by changlong-liu** [comment]
Hi @onenessboy , The difference between the two pieces of codes seems to be they use different input data.
Would you show more detail on the parameter values you passed to the "ServicePrincipalCredentials(tenant=xx, client_id=xx, secret=xx)" in both pieces of code ?

**Comment by onenessboy** [comment]
> Hi @onenessboy , The difference between the two pieces of codes seems to be they use different input data.
> Would you show more detail on the parameter values you passed to the "ServicePrincipalCredentials(tenant=xx, client_id=xx, secret=xx)" in both pieces of code ?

HI @changlong-liu  those secret key and client id  i am fetching it from our safety vault, but I dont see any issue in fetching it... the problem is if want to set these credentials as with in forloop for multiple subscription we have. hence getting error. the idea is we have multiple azure accounts and reqruiment to get keys, client id and set client to resource managment for each account and then pull all resource group in that account. that is what I amtrying in my 2nd piece of code, which is ended up end of paging error. where as my 1st code, is only checking for single account, so that s working fine. 

so the requirement is dynamically set client = resourcemanagmentclient and get all resources group for each account and do further steps...

It seems azure sdk has some limitation of single paging that you can check from your end.

**Comment by changlong-liu** [comment]
Hi @onenessboy would you show the code for  your "get_keys()" function?

**Comment by onenessboy** [comment]
> Hi @onenessboy would you show the code for your "get_keys()" function?

that function is our vault related, there is not problem in that, it will get accesskey and secretey into locally declared varibles..

What i observer is this end of paging occurs, when you have a azure object output spanning over multiple pages...I guess we need to some loop through to display or convert it...
