### ISSUE TITLE
JobCollection Creation - The resource is blocked to recieve any updates

### ISSUE THREAD

**Issue by antonydenyer** [Azure/azure-sdk-for-python#1306]
I'm getting the following error when trying to create a JobCollection

```
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
<Code>ForbiddenError</Code>
<Message>The resource is blocked to recieve any updates.</Message>
</Error>.
```

This has been working for while for us. Has something changed on the Azure side perhaps?
I can create the collection in the portal without any issues, so not sure what's going on.

Thanks

**Comment by lmazuel** [comment]
Hi @antonydenyer 
First, could you confirm you're talking about Scheduler? There is several services that use a "job" concept (batch, datalake, scheduler,...) I want to be sure it's what you use. Also, could you write the version of the package?
Thanks,

**Comment by antonydenyer** [comment]
Hi @lmazuel 

It looks like the error is returned when you hit your subscription limits.  What was frustrating was the portal limits were 'updated' before the api. That is to say, I could make changes in the portal but not the api.

Any all is fixed now. Thanks
