### ISSUE TITLE
Azure Python API to list billing invoice

### ISSUE THREAD

**Issue by indumathyn** [Azure/azure-sdk-for-python#1307]
Is there any API in python to list out  azure billing invoice details

**Comment by lmazuel** [comment]
Hi @indumathyn 
Please use the `azure-mgmt-billing` package and the invoices operation group:
https://docs.microsoft.com/python/api/azure.mgmt.billing.operations.invoicesoperations

Thanks,

**Comment by indumathyn** [comment]
My code:
from azure.mgmt.billing import BillingManagementClient
billing_client  = BillingManagementClient(credentials, subscription_id)
for b in billing_client.invoices.list():
			print(b)

Result:
azure.mgmt.billing.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

**Comment by lmazuel** [comment]
This is a server side error, I will reach out the service team and ask them if there is a known issue.

In the meantime, if you want to test more parameters, you might be interested by these unittests:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_billing.py#L46-L89

Thanks,

**Comment by lmazuel** [comment]
@AnushaY1 @indumathyn could you send me by email your subscription id, so we can take a look in our internal log. My email is <my github alias> @microsoft.com
Thanks!

**Comment by indumathyn** [comment]
Its working now actually its authorization issue...Thanx for your effort....

**Comment by lmazuel** [comment]
Thanks @indumathyn :)
