### ISSUE TITLE
Azure Python SDK billing ratecard value

### ISSUE THREAD

**Issue by indumathyn** [Azure/azure-sdk-for-python#1308]
My code:
commerce_client  = UsageManagementClient(credentials, subscription_id)
rate = commerce_client.rate_card.get(
    "OfferDurableId eq 'MS-AZR-0062P' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'"
)
**Result** :
, <azure.mgmt.commerce.models.meter_info.MeterInfo object at 0x7f1ed3b5dd30>

**Query**
How to fetch result

**Comment by lmazuel** [comment]
Hi @indumathyn 
A `MeterInfo` instance is a result:
https://docs.microsoft.com/python/api/azure.mgmt.commerce.models.meterinfo

**Comment by indumathyn** [comment]
Known but help me using this
azure.mgmt.commerce.models.meter_info.MeterInfo object at 0x7f1ed3b5dd30
how to print detailed result

**Comment by lmazuel** [comment]
Note that your question is not Azure specific, this is how to print attributes of a Python object. I can't suggest an approach better than another. Example of answer:
https://stackoverflow.com/a/2675148/4074838
https://stackoverflow.com/a/5969930/4074838

Thanks,

**Comment by indumathyn** [comment]
Its working Thanx a lot for your support
