### ISSUE TITLE
azure-servicebus/receive_subscription.py azure.servicebus.exceptions.ServiceBusConnectionError: ErrorCodes.UnknownError: Connection in an unexpected error state.

### ISSUE THREAD

**Issue by boltunoff** [Azure/azure-sdk-for-python#13097]
- **Package Name**: azure-servicebus/receive_subscription.py
- **Package Version**: latest
- **Operating System**: MacOS Catalina, Version 10.15.5. Pycharm
- **Python Version**: 3.8

**Describe the bug**
I am trying to receive messages from the servicebus subscription topic following the receive_subscription.py sample. 

And running into this error:
2020-08-13 01:20:47.650 Python[33586:10760876] CFNetwork SSLHandshake failed (-9806)
ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')

azure.servicebus.exceptions.ServiceBusConnectionError: ErrorCodes.UnknownError: Connection in an unexpected error state.

**To Reproduce**
1. pip install azure-servicebus --pre
2. create .py file containing the example's code :

`from azure.servicebus import ServiceBusClient

CONNECTION_STR = 'my conn string'
TOPIC_NAME = 'my topic name'
SUBSCRIPTION_NAME = 'my subscr name'

servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR)
with servicebus_client:
    receiver = servicebus_client.get_subscription_receiver(
        topic_name=TOPIC_NAME,
        subscription_name=SUBSCRIPTION_NAME
    )
    with receiver:
        received_msgs = receiver.receive_messages(max_batch_size=10, max_wait_time=5)
        for msg in received_msgs:
            print(str(msg))
            msg.complete()

print("Receive is done.")`

3. run .py script

**Expected behavior**
message content printed out on the console

**Comment by kaerm** [comment]
@boltunoff thanks for reporting this, @KieranBrantnerMagee could you take a look at this ?

**Comment by yunhaoling** [comment]
hey @boltunoff , thanks for reaching out.

Honestly this is the first time I see the error and I can't reproduce it on my Mac. My gut feeling is that it's related to networking/proxy/ssl settings. But we need more information to locate the issue.

With that being said, can you turn on the networking tracking functionality when constructing the ServiceBusClient and provide us with the detailed log? that would be helpful to us.

that would be
```python
import logging
logging.basicConfig(level=logging.DEBUG)

servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR, logging_enable=True)
# code..
```
