### ISSUE TITLE
Print out MD5, but get a byte array. 

### ISSUE THREAD

**Issue by likun47** [Azure/azure-sdk-for-python#13104]
-azure_storage_blob-12.3.2: 
- Azure SDK for Python: 
- Windows 10:
- Python 3.0: 

**Describe the bug**
I have a customer, she wrote some code wanted to get a MD5 content, it was supposed to return a string, but she got a byte array.

**To Reproduce**
1. Running the code below: 
from azure.storage.blob import BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string(connect_str);
container_client = blob_service_client.get_container_client(container_name)
blob_list = container_client.list_blobs(name_starts_with=src);
for blob in blob_list:
        print( blob.name + "\t" + str(blob.content_settings.content_md5) )

Output:
quickstart.txt  bytearray(b'\x93\x8f1xZ\xc2]\xc1\xcb\x1f\xd5\x10\xef .\x92')

**Expected behavior**
Return result should be a string: 'k48xeFrCXcHLH9UQ7yAukg==

**Screenshots**
N/A

**Additional context**
Background information from my customer: 

from azure.storage.blob import BlockBlobService
block_blob_service = BlockBlobService(account_name=acct_name, account_key=acct_key)
blob_list = block_blob_service.list_blobs(container_name, src, include='metadata')
for blob in blob_list:
        print blob.name + "\t" + blob.properties.content_settings.content_md5
The code above works well. But we upgraded our system to python 3 and some featuresare gone,  for example, 'blob_tier' is not an attribute of Blobproperties under BlockBlobService. 

That is the reason we changed to BlobServiceClient. Then I encountered ‘md5’ issue.

**Comment by likun47** [comment]
More specific configuration: 
pip3 freeze
azure-core==1.8.0
azure-storage-blob==12.4.0
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
cryptography==3.0
idna==2.10
isodate==0.6.0
msrest==0.6.18
oauthlib==3.1.0
pycparser==2.20
requests==2.24.0
requests-oauthlib==1.3.0
scour==0.36
six==1.11.0
urllib3==1.25.10

**Comment by xiafu-msft** [comment]
Hi @likun47 

Thanks for reaching out! We will discuss this and get back to you!

**Comment by xiafu-msft** [comment]
Hi @likun47 

We know it's weird, sorry about that... While we had a discussion and currently we don't plan to make it to a str since it's a breaking change to other customers.
So currently you can do base64 encode the bytes and utf-8 decode it like this:
`encode_base64(content_md5).decode('utf-8')
`

Sorry again about the inconvenience. Let me know if you have any concern....

**Comment by likun47** [comment]
Hi Xiaoxi,

Thank you for this work around. We already used the method you provided
above to fix the problem.
We appreciate your help.

**Comment by tasherif-msft** [comment]
Hi @likun47 we will proceed to close this issue since it looks like it is resolved on your end, if anything else comes up feel free to reach out :)
