### ISSUE TITLE
How to fetch tags information for all resources inside multiple Resource group for a given Azure account

### ISSUE THREAD

**Issue by onenessboy** [Azure/azure-sdk-for-python#13101]
- **Package Name**:  Resource Management
- **Package Version**: 
- **Operating System**:
- **Python Version**:  3.6

**Describe the bug**

How to get /print all tags for resources with in each resourge group that i have in azure via python sdk

```
credential = ServicePrincipalCredentials(tenant=tenant_var, client_id=rxxxxxxx, secret=xxxxxx)
subscription_client = SubscriptionClient(credential)
subscription = next(subscription_client.subscriptions.list())
#client = MonitorManagementClient(credential, subscription.subscription_id)
client = ResourceManagementClient(credential, subscription.subscription_id)

for item in client.resource_groups.list():
    print(item.name)
```
as of now I am priting all resource group names but i wanted to list all resource id for each resource group and need to tags for it.. How to achieve this ? any examples please

**Comment by chunyu3** [comment]
Two approaches to list resources under a subscription:
1.You can list all the resources under a subscription as following:
resources = client.resources.list()

2. You can list all the resource groups, then get the resources of one resource group one by one as following:
resource_group_list = self.resource_client.resource_groups.list()
 resources = list(client.resources.list_by_resource_group(
            group_name
        ))

**Comment by onenessboy** [comment]
> Two approaches to list resources under a subscription:
> 1.You can list all the resources under a subscription as following:
> resources = client.resources.list()
> 
> 1. You can list all the resource groups, then get the resources of one resource group one by one as following:
>    resource_group_list = self.resource_client.resource_groups.list()
>    resources = list(client.resources.list_by_resource_group(
>    group_name
>    ))

@chunyu3 thanks for code, meanwhile I try these, can you please let me know how to fetch tags for all resources inside that was my originial question please...

**Comment by onenessboy** [comment]
> > Two approaches to list resources under a subscription:
> > 1.You can list all the resources under a subscription as following:
> > resources = client.resources.list()
> > 
> > 1. You can list all the resource groups, then get the resources of one resource group one by one as following:
> >    resource_group_list = self.resource_client.resource_groups.list()
> >    resources = list(client.resources.list_by_resource_group(
> >    group_name
> >    ))
> 
> @chunyu3 thanks for code, meanwhile I try these, can you please let me know how to fetch tags for all resources inside that was my originial question please...

what I tried now is

```
resource_list = client.resources.list()
print(type(resource_list))
tags_info = []
for rg in (resource_list):
    value = rg.get('tags')

error:
```
 value = rg.get('tags')
AttributeError: 'GenericResourceExpanded' object has no attribute 'get'
```

**Comment by onenessboy** [comment]
@chunyu3 actually requirement is to list out resource name and its tags(in tags also only status) I am trying to fetch.
I trying to loop differenctly but still that Generic Resource Expanded error coming.... 

```
tags_info ={}
for k,v in client.resources.list():   
    if 'name' in v.keys():        
        name = k + ':' + v['name']
    else:
        name = k + ': No Name'

    if 'tags' in v.keys() and v['tags']:        
        if 'status' in v['tags'].keys():            
            tags_info = {name+" status": v['tags']['status']}
        else:            
            tags_info = {name+" status": "Not Available"}
        print (tags_info)
    else:
        #tags is not a dictionary so it is not managed
        tags_info = {name+" status": "Not Available"}
        print (tags_info)
```
Error:
```TypeError: cannot unpack non-iterable GenericResourceExpanded object```

**Comment by onenessboy** [comment]
> GenericResourceExpanded object

@chunyu3 can you please let me know how to handle this error ```TypeError: cannot unpack non-iterable GenericResourceExpanded object```

**Comment by changlong-liu** [comment]
> > > Two approaches to list resources under a subscription:
> > > 1.You can list all the resources under a subscription as following:
> > > resources = client.resources.list()
> > > 
> > > 1. You can list all the resource groups, then get the resources of one resource group one by one as following:
> > >    resource_group_list = self.resource_client.resource_groups.list()
> > >    resources = list(client.resources.list_by_resource_group(
> > >    group_name
> > >    ))
> > 
> > 
> > @chunyu3
> >             
> >             Crystal YU
> >             FTE thanks for code, meanwhile I try these, can you please let me know how to fetch tags for all resources inside that was my originial question please...
> 
> what I tried now is
> 
> ```
> resource_list = client.resources.list()
> print(type(resource_list))
> tags_info = []
> for rg in (resource_list):
>     value = rg.get('tags')
> 
> error:
> 
>  value = rg.get('tags')
> AttributeError: 'GenericResourceExpanded' object has no attribute 'get'
> ```
> 
> @chunyu3 Crystal YU FTE
> How to handle this GenericResourceExpanded' object error. I am sure this is some thing problem related to Azure paging



Hi @onenessboy ,

GenericResourceExpanded is defined here: https://github.com/Azure/azure-sdk-for-python/blob/release/v3/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2020_06_01/models/_models_py3.py#L1042

So no need to use "get" in below code:
~~~
for rg in (resource_list):
    value = rg.get('tags')
~~~

would you try this:
~~~
for rg in (resource_list):
    value = rg.tags
~~~

**Comment by onenessboy** [comment]
> > > > Two approaches to list resources under a subscription:
> > > > 1.You can list all the resources under a subscription as following:
> > > > resources = client.resources.list()
> > > > 
> > > > 1. You can list all the resource groups, then get the resources of one resource group one by one as following:
> > > >    resource_group_list = self.resource_client.resource_groups.list()
> > > >    resources = list(client.resources.list_by_resource_group(
> > > >    group_name
> > > >    ))
> > > 
> > > 
> > > @chunyu3
> > > ```
> > >         Crystal YU
> > >         FTE thanks for code, meanwhile I try these, can you please let me know how to fetch tags for all resources inside that was my originial question please...
> > > ```
> > 
> > 
> > what I tried now is
> > ```
> > resource_list = client.resources.list()
> > print(type(resource_list))
> > tags_info = []
> > for rg in (resource_list):
> >     value = rg.get('tags')
> > 
> > error:
> > 
> >  value = rg.get('tags')
> > AttributeError: 'GenericResourceExpanded' object has no attribute 'get'
> > ```
> > 
> > 
> > @chunyu3 Crystal YU FTE
> > How to handle this GenericResourceExpanded' object error. I am sure this is some thing problem related to Azure paging
> 
> Hi @onenessboy ,
> 
> GenericResourceExpanded is defined here: https://github.com/Azure/azure-sdk-for-python/blob/release/v3/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2020_06_01/models/_models_py3.py#L1042
> 
> So no need to use "get" in below code:
> 
> ```
> for rg in (resource_list):
>     value = rg.get('tags')
> ```
> 
> would you try this:
> 
> ```
> for rg in (resource_list):
>     value = rg.tags
> ```

@changlong-liu 

Actually, I wanted to check if in our environment, for resources whether tags exist or not. Even I treid to use 
```for rg in (resource_list):
    value = rg.tags```
but if I use this method, I am not able to pick specific tags out of this method, it error out with ```None Type subscriptor"

My questions why can't I iterate of ```client.resources.list()```
can you check and confirm your side on your lab, whether you are able to iterate over this kind of loop on client.resources ?

**Comment by changlong-liu** [comment]
Hi @onenessboy , would you say more about "My questions why can't I iterate of client.resources.list()"?

Below code is actually iterating over client.resources.list, will it bring error in your side?
~~~
resource_list = client.resources.list()
for rg in (resource_list):
    value = rg.tags
~~~

**Comment by onenessboy** [comment]
> Hi @onenessboy , would you say more about "My questions why can't I iterate of client.resources.list()"?
> 
> Below code is actually iterating over client.resources.list, will it bring error in your side?
> 
> ```
> resource_list = client.resources.list()
> for rg in (resource_list):
>     value = rg.tags
> ```

Yeah I still get error with this method as well.  My requirement is out of that client,list values for each resource id first i need to check if tags exist or not , if exist, there will be one or more keys will be part of tags and i need to pick specific tag out of that entire tags list. and if any resource id, does not have main tags key it self, then i need to print. no tag present...so i treid to loop over like below

```
resource_list = client.resources.list()
for k,v in (resource_list):   
    if 'name' in v.keys():        
        name = k + ':' + v['name']
    else:        
        name = k + ': No Name'
    
    if 'tags' in v.keys() and v['tags']:
      ```
But its giving me 
AttributeError: 'GenericResourceExpanded' object has no attribute 'get'

**Comment by changlong-liu** [comment]
Hi @onenessboy , an issue in your code:
~~~
resource_list = client.resources.list()      # this is a list of GenericResourceExpanded
for k,v in (resource_list):                         # WRONG!   you will get "cannot unpack non-iterable GenericResourceExpanded object"
    if 'name' in v.keys():        
        name = k + ':' + v['name']
    else:        
        name = k + ': No Name'
    
    if 'tags' in v.keys() and v['tags']:
      ```
~~~


if you want get tags of all of your resources, please try:
~~~
resource_list = client.resources.list()
for r in (resource_list):
    tags = r.tags
~~~

**Comment by onenessboy** [comment]
> Hi @onenessboy , an issue in your code:
> 
> ```
> resource_list = client.resources.list()      # this is a list of GenericResourceExpanded
> for k,v in (resource_list):                         # WRONG!   you will get "cannot unpack non-iterable GenericResourceExpanded object"
>     if 'name' in v.keys():        
>         name = k + ':' + v['name']
>     else:        
>         name = k + ': No Name'
>     
>     if 'tags' in v.keys() and v['tags']:
>       ```
> ```
> 
> if you want get tags of all of your resources, please try:
> 
> ```
> resource_list = client.resources.list()
> for r in (resource_list):
>     tags = r.tags
>     # read tags content here for each resource
> ```

Yeah, tried to do so, getting different error now

```
for r in (resource_list):
    az_tags = r.tags
    for k,v in (az_tags):
        if 'name' in v.keys():
            name = k + ':' + v['name']
        else:
            name = k + ': No Name'
        if 'tags' in v.keys() and v['tags']:
```
Error:

```
    for k,v in az_tags:
ValueError: too many values to unpack (expected 2)
```

**Comment by changlong-liu** [comment]
Hi, you can have a list with this:
~~~
resource_list = list(client.resources.list())
~~~

**Comment by onenessboy** [comment]
> Hi, you can have a list with this:
> 
> ```
> resource_list = list(client.resources.list())
> ```
> 
> And below code need to be reorganize:
> 
> ```
> for r in (resource_list):
>     az_tags = r.tags
>     for k,v in (az_tags):                    # WRONG!  az_tags is a dictionary
>         if 'name' in v.keys():               
>             name = k + ':' + v['name']
>         else:
>             name = k + ': No Name'
>         if 'tags' in v.keys() and v['tags']:
> ```
> 
> An example for read tags:
> 
> ```
> for r in (resource_list):
>     az_tags = r.tags
>     if az_tags is not None:
>         for k,v in az_tags.items(): 
>             # handle k, v in tag here
> ```

thanks, let me try this

**Comment by onenessboy** [comment]
closing this as resolved
