### ISSUE TITLE
[Storage] QueueClient.UpdateMessageAsync erases message content.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-python#13121]
See related bug in .NET . Lets make sure this is addressed for Python.
https://github.com/Azure/azure-sdk-for-net/issues/14243

**Comment by tasherif-msft** [comment]
Hi @kasobol-msft, great news it doesn't look like this is an issue in Python :) We also have a test in place https://github.com/Azure/azure-sdk-for-python/blob/ceb8a8daf99e81076c5f180ef251be5acc3ffbf6/sdk/storage/azure-storage-queue/tests/test_queue.py#L440
I have used a different visibility as well and it worked fine!
I will proceed to close this issue.
