### ISSUE TITLE
Poor error message for unsupported operations

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#13128]
`CertificateClient` supports Key Vault version 2016-10-01, but that service version doesn't support the `backup_certificate` operation added in 7.0. So this code raises an error:
```py
from azure.keyvault.certificates import ApiVersion, CertificateClient

client = CertificateClient(VAULT_URL, object(), api_version=ApiVersion.V2016_10_01)
client.backup_certificate("...")
```
The error suggests the client or service doesn't support this particular API version, when in fact it's only this particular operation which is not supported:
```
  File "...\azure-keyvault-certificates\azure\keyvault\certificates\_generated\_operations_mixin.py", line 54, in backup_certificate
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2016-10-01 is not available
```

**Comment by iscai-msft** [comment]
Have opened an issue for this in autorest: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py#L504

**Comment by chlowell** [comment]
Closing this because the autorest issue is closed.
