### ISSUE TITLE
azure.servicebus.ServiceBusService should support initialization from connection string

### ISSUE THREAD

**Issue by andreycpp** [Azure/azure-sdk-for-python#1313]
The C# Azure SDK supports CreateFromConnectionString() method that takes a SBS connection string. See https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues

Python SDK however does not seem to support this, and user is forced to parse the connection string into service_namespace, shared_access_key_name, shared_access_key_value parameters. See https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-queues

This is a request for python SDK to support ServiceBusService initialization from connection string.

**Comment by lmazuel** [comment]
Thanks for the feedback @andreycpp . I'm adding that in our task list, but can't give an ETA of the feature.

**Comment by olavt** [comment]
+1, Any news / progress on this?

**Comment by lmazuel** [comment]
Unfortunately no :(. For ServiceBus, we are prioritizing AMQP support right now and are actively working on it.

**Comment by isobit** [comment]
Here's a quick hack if anybody is interested, only supports the endpoint URI and SAS token but you could easily extend it:

```python
def parse_service_bus_connection_string(s):
    r = dict()
    for seg in s.split(';'):
        k, v = seg.split('=', 1)
        if k == 'Endpoint':
            m = re.match('sb://(?P<namespace>[^.]+)(?P<host_base>[^/]+)', v)
            r['service_namespace'] = m.group('namespace')
            r['host_base'] = m.group('host_base')
        elif k == 'SharedAccessKeyName':
            r['shared_access_key_name'] = v
        elif k == 'SharedAccessKey':
            r['shared_access_key_value'] = v
    return r

ServiceBusService(**parse_service_bus_connection_string(YOUR_CONN_STRING))
```

**Comment by annatisch** [comment]
Hi @andreycpp, @olavt, @bloodybeet, @isobit 

This is just a heads-up to let you know that we have just published a new AMQP-based preview SDK for Service Bus! The API has been newly designed, and you can find documentation here:
- [Overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python)
- [Reference documentation](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus?view=azure-python)

This feature (creating a client directly from connection string) is supported in the new API and is demonstrated [here in the overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python#create-client).

I'm going to close this issue now - but we would love your feedback on the new SDK - please open new issues for any feature requests, bug reports etc.

Thanks!
