### ISSUE TITLE
Set TSL SSL to use version 1.2 on azure container instance

### ISSUE THREAD

**Issue by jay2017-git** [Azure/azure-sdk-for-python#13133]
Please how do I set azure container instance to use only TSL 1.2 and not TSL 1.0 and 1.1
I followed this [link](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-secure-web-service) yet it installed TSL 1.0 and 1.2

Thanks

**Comment by shawncx** [comment]
@jay2017-git Could you check https://docs.microsoft.com/en-us/azure/container-instances/container-instances-container-group-ssl Is the the case you want?
If so, you need to use azure-mgmt-resource to create container group. Please prepare the YAML file as the definition. 
```python
definition= yaml.safe_load(<your yaml file>)
resource_client.create_or_update(<resourceGroupName>, 
                        "Microsoft.ContainerInstance",
                        "",
                       "containerGroups",
                       <name>,
                       <api_version>,
                       definition)
```

**Comment by jay2017-git** [comment]
@shawncx  Am trying to deploy a machine learning model as a webservice. How do I do it if I follow these steps - https://docs.microsoft.com/en-us/azure/container-instances/container-instances-container-group-ssl 

I saw this link https://docs.microsoft.com/en-us/azure/machine-learning/how-to-secure-web-service and decide to follow the steps but I noticed it also has TLS 1.0 and TLS 1.1.

**Comment by jay2017-git** [comment]
@dkkapur and @shawncx  can you please help advice. I only need TLS 1.2 but when I deploy using from azureml.core.webservice import AciWebservice

aci_config = AciWebservice.deploy_configuration(
    ssl_enabled=True, ssl_cert_pem_file="cert.pem", ssl_key_pem_file="key.pem", ssl_cname="www.my domain name.com").

it includes TLS 1.1 and TLS 1.0.  I only need TLS 1.2

**Comment by KranthiPakala-MSFT** [comment]
@dkkapur and @shawncx - Following up to see if there any update on the above follow-up query from @jay2017-git ? - Thank you
