### ISSUE TITLE
[azure-storage-blob] generate-sas with tag permission

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-sdk-for-python#13142]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.4.0b1
- **Operating System**: Win 10
- **Python Version**: 3.737

**Describe the bug**
generate_blob_sas() with permission tag, and want to list tags for specific blob with generated sas. But it doesn't work.

generated sas as follows:
```
se=2020-08-17&sp=t&spr=https&sv=2019-12-12&sr=b&sig=readact
```

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiafu-msft** [comment]
Hi @Juliehzl 

I think it's working for us, here is the test we have https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/tests/test_blob_tags.py#L358

**Comment by tasherif-msft** [comment]
Hi @Juliehzl, is the issue still persisting?
