### ISSUE TITLE
VSCode credential does not work in Azure China

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#13149]

**Comment by chlowell** [comment]
It works for me so, lacking details about the problem, I guess it was in configuration. Credentials generally default to Azure Public Cloud. An application running in a different cloud usually must configure credentials for that cloud. For example, using VisualStudioCodeCredential in Azure China:

```py
from azure.identity import AzureAuthorityHosts, VisualStudioCodeCredential

credential = VisualStudioCodeCredential(authority=AzureAuthorityHosts.AZURE_CHINA)
token = credential.get_token("https://management.core.chinacloudapi.cn//.default")
```
(#14808 tracks making this more convenient by having VisualStudioCodeCredential discover the authority via VS Code settings)

Clients often require configuration for non-default clouds as well. [This document](https://docs.microsoft.com/azure/developer/python/azure-sdk-sovereign-domain) describes how to configure management clients.

The above code works for me, so I'll close this issue now. If it doesn't work for you, please reopen this issue with details of the errors you're seeing.
