### ISSUE TITLE
BlobServiceClient.list_containers() crashes

### ISSUE THREAD

**Issue by UrmelAusDemEis** [Azure/azure-sdk-for-python#13144]
- **Package Version**: 12.4.0
- **Python Version**: Python 3.7

**Describe the bug**
When calling the function "list_containers()", the following error is thrown:
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'Bad Request'

**Additional context**
The exact same code still works under 12.3.2

**Comment by xiafu-msft** [comment]
Hi @UrmelAusDemEis 

Thanks for your feedback, we are taking a look now and will get back to you soon

**Comment by xiafu-msft** [comment]
Hi @UrmelAusDemEis 

I haven't been able to reproduce this... Can you paste more log here?

**Comment by UrmelAusDemEis** [comment]
Hi @xiafu-msft 

the self.azure comes from cls.azure = BlobServiceClient.from_connection_string(DEBUG_CONNECTION_STRING)

      self = <XXXX_Test.XXXX_Test testMethod=XXX>
14-Aug-2020 00:15:38    
14-Aug-2020 00:15:38        def setUp(self):
14-Aug-2020 00:15:38    >       for c in self.azure.list_containers():
14-Aug-2020 00:15:38    
14-Aug-2020 00:15:38    acceptanceTests/acceptance_Test.py:32: 
14-Aug-2020 00:15:38    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
14-Aug-2020 00:15:38    virtualenv/lib/python3.7/site-packages/azure/core/paging.py:122: in __next__
14-Aug-2020 00:15:38        return next(self._page_iterator)
14-Aug-2020 00:15:38    virtualenv/lib/python3.7/site-packages/azure/core/paging.py:74: in __next__
14-Aug-2020 00:15:38        self._response = self._get_next(self.continuation_token)
14-Aug-2020 00:15:38    virtualenv/lib/python3.7/site-packages/azure/storage/blob/_models.py:401: in _get_next_cb
14-Aug-2020 00:15:38        process_storage_error(error)
14-Aug-2020 00:15:38    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
14-Aug-2020 00:15:38    
14-Aug-2020 00:15:38    storage_error = StorageErrorException("Operation returned an invalid status 'Bad Request'")
14-Aug-2020 00:15:38    
14-Aug-2020 00:15:38        def process_storage_error(storage_error):
14-Aug-2020 00:15:38            raise_error = HttpResponseError
14-Aug-2020 00:15:38            error_code = storage_error.response.headers.get('x-ms-error-code')
14-Aug-2020 00:15:38            error_message = storage_error.message
14-Aug-2020 00:15:38            additional_data = {}
14-Aug-2020 00:15:38            try:
14-Aug-2020 00:15:38                error_body = ContentDecodePolicy.deserialize_from_http_generics(storage_error.response)
14-Aug-2020 00:15:38                if error_body:
14-Aug-2020 00:15:38                    for info in error_body.iter():
14-Aug-2020 00:15:38                        if info.tag.lower() == 'code':
14-Aug-2020 00:15:38                            error_code = info.text
14-Aug-2020 00:15:38                        elif info.tag.lower() == 'message':
14-Aug-2020 00:15:38                            error_message = info.text
14-Aug-2020 00:15:38                        else:
14-Aug-2020 00:15:38                            additional_data[info.tag] = info.text
14-Aug-2020 00:15:38            except DecodeError:
14-Aug-2020 00:15:38                pass
14-Aug-2020 00:15:38        
14-Aug-2020 00:15:38            try:
14-Aug-2020 00:15:38                if error_code:
14-Aug-2020 00:15:38                    error_code = StorageErrorCode(error_code)
14-Aug-2020 00:15:38                    if error_code in [StorageErrorCode.condition_not_met,
14-Aug-2020 00:15:38                                      StorageErrorCode.blob_overwritten]:
14-Aug-2020 00:15:38                        raise_error = ResourceModifiedError
14-Aug-2020 00:15:38                    if error_code in [StorageErrorCode.invalid_authentication_info,
14-Aug-2020 00:15:38                                      StorageErrorCode.authentication_failed]:
14-Aug-2020 00:15:38                        raise_error = ClientAuthenticationError
14-Aug-2020 00:15:38                    if error_code in [StorageErrorCode.resource_not_found,
14-Aug-2020 00:15:38                                      StorageErrorCode.cannot_verify_copy_source,
14-Aug-2020 00:15:38                                      StorageErrorCode.blob_not_found,
14-Aug-2020 00:15:38                                      StorageErrorCode.queue_not_found,
14-Aug-2020 00:15:38                                      StorageErrorCode.container_not_found,
14-Aug-2020 00:15:38                                      StorageErrorCode.parent_not_found,
14-Aug-2020 00:15:38                                      StorageErrorCode.share_not_found]:
14-Aug-2020 00:15:38                        raise_error = ResourceNotFoundError
14-Aug-2020 00:15:38                    if error_code in [StorageErrorCode.account_already_exists,
14-Aug-2020 00:15:38                                      StorageErrorCode.account_being_created,
14-Aug-2020 00:15:38                                      StorageErrorCode.resource_already_exists,
14-Aug-2020 00:15:38                                      StorageErrorCode.resource_type_mismatch,
14-Aug-2020 00:15:38                                      StorageErrorCode.blob_already_exists,
14-Aug-2020 00:15:38                                      StorageErrorCode.queue_already_exists,
14-Aug-2020 00:15:38                                      StorageErrorCode.container_already_exists,
14-Aug-2020 00:15:38                                      StorageErrorCode.container_being_deleted,
14-Aug-2020 00:15:38                                      StorageErrorCode.queue_being_deleted,
14-Aug-2020 00:15:38                                      StorageErrorCode.share_already_exists,
14-Aug-2020 00:15:38                                      StorageErrorCode.share_being_deleted]:
14-Aug-2020 00:15:38                        raise_error = ResourceExistsError
14-Aug-2020 00:15:38            except ValueError:
14-Aug-2020 00:15:38                # Got an unknown error code
14-Aug-2020 00:15:38                pass
14-Aug-2020 00:15:38        
14-Aug-2020 00:15:38            try:
14-Aug-2020 00:15:38                error_message += "\nErrorCode:{}".format(error_code.value)
14-Aug-2020 00:15:38            except AttributeError:
14-Aug-2020 00:15:38                error_message += "\nErrorCode:{}".format(error_code)
14-Aug-2020 00:15:38            for name, info in additional_data.items():
14-Aug-2020 00:15:38                error_message += "\n{}:{}".format(name, info)
14-Aug-2020 00:15:38        
14-Aug-2020 00:15:38            error = raise_error(message=error_message, response=storage_error.response)
14-Aug-2020 00:15:38            error.error_code = error_code
14-Aug-2020 00:15:38            error.additional_info = additional_data
14-Aug-2020 00:15:38    >       raise error
14-Aug-2020 00:15:38    E       azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
14-Aug-2020 00:15:38    E       ErrorCode:None
    
I hope this helps! :)

**Comment by bharel** [comment]
Happens here as well while querying Azurite blob storage.

**Comment by xiafu-msft** [comment]
Hi @UrmelAusDemEis and @bharel

We still cannot reproduce on our side...
can you try version 12.6.0 and see you you have the same problem?
