### ISSUE TITLE
ContainerClient.delete_blobs() fails with TLS version not matched

### ISSUE THREAD

**Issue by foobarna** [Azure/azure-sdk-for-python#13183]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.4.0
- **Operating System**: Does not matter
- **Python Version**: 3.6.11

**Describe the bug**
When invoking [container.delete_blobs('path/to/blob')](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#delete-blobs--blobs----kwargs-) the code throws `PartialBatchErrorException` with "The TLS version of the connection is not permitted on this storage account.".

The methods `container.download_blob('path/to/blob')` and `container.delete_blob('path/to/blob')` are successful.

**To Reproduce**

```
credential = ClientSecretCredential(.....)
blob_client = BlobServiceClient(account_url=account_url, credential=credential)
container = blob_client.get_container_client('some_container_name')

container.delete_blobs('path/to/blob1', 'path/to/blob2')
```

**Expected behavior**
To delete the blobs.

**Screenshots**

**Additional context**
The storage account is set to minimum TLS version 1.0.

**Comment by foobarna** [comment]
Hi @xiafu-msft ! Any news regarding this?

**Comment by pemari-msft** [comment]
This is a known issue between the preview TLS version feature and Batch api. By changing the value of the TLS restriction to 1.0, you should be able to work around the restriction. We are fixing this as soon as possible on the service.

**Comment by epicfaace** [comment]
@pemari-msft I'm facing this issue even when changing the value of the TLS restriction to 1.0 or removing the SSL requirement altogether. The only way I can work around this issue for now is by using `.delete_blob` instead of `delete_blobs()`.

**Comment by xiafu-msft** [comment]
Hi @epicfaace 

We discussed and tried a couple of things offline yesterday and it looks like currently the workaround is using http...
Is it possible for you go to azure portal, and disable Enforce Secure Transfer under Configuration?

**Comment by foobarna** [comment]
Hi @pemari-msft ,
I don't think you have read the full description of the issue, I've stated that we already tried setting minimum version of TLS to 1.0 on the storage's settings.

**Comment by foobarna** [comment]
Hey @xiafu-msft ,
Using HTTP is out of the question. We would be glad if this issue can be fixed, otherwise just remove it from SDK.

**Comment by xiafu-msft** [comment]
Hi @epicfaace 
You need to set the account url to **http**://youraccountname.blob.core.windows.net, that's an workaround currently...

**Comment by xiafu-msft** [comment]
Update: there is a service rollout that is happening that should fix the issue.

**Comment by foobarna** [comment]
I can confirm that the `.detele_blobs()` method now work with no modification on the code/library version nor Azure Blob Storage account.

**Comment by tasherif-msft** [comment]
Hi @foobarna we will now close this issue. Let us know if anything else comes up.
Thank you.
