### ISSUE TITLE
Documentation on Azure Site on azure-mgmt-automation

### ISSUE THREAD

**Issue by HarleyB123** [Azure/azure-sdk-for-python#13212]
Based on the README [here](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/automation/azure-mgmt-automation), there is no documentation on how to use this package on both the [sdk reference page](https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python) and the [python API browser.](https://docs.microsoft.com/en-us/python/api/?view=azure-python)

Could this be created? 😄

**Comment by HarleyB123** [comment]
Hey 👋 

Any updates on this?

**Comment by jaspkaur28** [comment]
Have looped in the engineering team to look into the documentation needed here. Will share an update by next week .

**Comment by jaspkaur28** [comment]
We've got this triaged and added it to the Automation backlog, however , the team is completely occupied with other priorities right now , we plan to pick this up in early Q4 CY20.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by HarleyB123** [comment]
Thanks @vikram-m , is there a template for someone in the open source community to do this? If there was I’d be happy to give writing the docs for this API a go?

**Comment by jaspkaur28** [comment]
We will revisit this thread in CY2021 Q1.

**Comment by jaspkaur28** [comment]
As we shared in the last comment , we are trying to prioritize it for Q1 - Feb , March timeframe.

**Comment by jaspkaur28** [comment]
Deferred to CY2021 Q4 due to other priorities.
