### ISSUE TITLE
azure.servicebus limit on sending concurrent messages

### ISSUE THREAD

**Issue by chhantyal** [Azure/azure-sdk-for-python#1321]
We want to do performance testing in our data pipeline.
Thus I need to ingest 1000s messages per second concurrently. Python client seems to drop connections after certain amount. 

Code:
```
sbs.send_event('eventhub_name', data)
```
Error/Warning:
```
A0027W05/WARNING/urllib3.connectionpool: Connection pool is full, discarding connection: eventhub_name_container.servicebus.windows.net
```
Is there certain limit on number of messages being sent using Python client? I guess it would work if I use REST API directly?

In fact it seems to be common issue when using `requests` in threads https://stackoverflow.com/questions/18466079/can-i-change-the-connection-pool-size-for-pythons-requests-module

**Comment by lmazuel** [comment]
Hi @chhantyal 
Yes, the `azure-servicebus` package is using the RestAPI. There is no specific limit in the code, this should work until the RestAPI didn't. Your SO link seems correct to what happens to you.
The ServiceBus constructor accept a `request_session` object as parameter, so I would suggest to use the SO solution and provide your own session with adapter and pool customized.

Note that for performance, ServiceBus team currently suggests to use AMQP directly and [Proton](https://qpid.apache.org/proton/). Then, if you reach a RestAPI limit after fixing the requests issue, the only way is AMQP.

**Comment by chhantyal** [comment]
Thank you for reply and hint about `request_session`. I think that will fix the issue I have above.

I also thought of using AMQP, however there is virtually no documentation on how to use it with Apache Qpid Proton. Would be great to have some examples.

**Comment by lmazuel** [comment]
I totally agree with you, there should be documentation on AMQP :(. We are responsible here only of the RestAPI wrapper documentation, I will forward your message to the SB team for AMQP sample.

I keep this issue open, until you can confirm that you are able to deal with the problem using `request_session`. Thanks!

**Comment by chhantyal** [comment]
It indeed seems to work great. Thanks again for the tip.

For anyone bumping on this issue:

```
import requests 
from azure.servicebus import ServiceBusService

session = requests.Session()
adapter = requests.adapters.HTTPAdapter(pool_connections=100, pool_maxsize=200)
session.mount('https://', adapter)


sbs = ServiceBusService(EVENTHUB_CONFIG['NAMESPACE'],
                        shared_access_key_name=EVENTHUB_CONFIG['ACCESS_KEY_NAME'],
                        shared_access_key_value=EVENTHUB_CONFIG['ACCESS_KEY_VALUE'],
                        request_session=session
                        )
```

**Comment by lmazuel** [comment]
Thanks for the sample @chhantyal !!
