### ISSUE TITLE
EvenGrid Deserialize API

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#13227]
Given the direction conversations are going ( per discussions [here](https://gist.github.com/kerri-lee/900f7fcee8ba1bcca5ee18e19e9b59d3) ) it's looking like the shape of this API may be changing. Items such as:

location, here or on the event models
With this, not utilizing a wrapper class (deserializedEvent) and instead doing the "lazy load" when accessing the data property.
parsing directly from e.g. a requestContext

**Comment by lmazuel** [comment]
Will ds
