### ISSUE TITLE
Unclosed connector / client session when using asyncio

### ISSUE THREAD

**Issue by victoraugustolls** [Azure/azure-sdk-for-python#13242]
- **Packages**: 
        azure-common==1.1.25
        azure-core==1.8.0
        azure-identity==1.4.0
        azure-keyvault-secrets==4.2.0
- **Operating System**: Linux
- **Python Version**:  3.8.5

**Describe the bug**
When connecting to keyvault using the async version of the methods, I have the following output:

```
ERROR:    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff8b06e2760>
ERROR:    Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff8b067b700>, 267164.584)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff8b06e2a60>
ERROR:    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff8b06d3af0>
ERROR:    Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff8b067bbe0>, 267164.153)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff8b06d3b50>
```

**To Reproduce**
1. Create `DefaultAzureCredential()`
2. Create `SecretClient`
3. Call the method `get_secret` on the client

**Expected behavior**
Expected no errors.

**Comment by chlowell** [comment]
aiohttp doesn't close its sessions, so you must do it yourself (see aiohttp docs on [graceful shutdown](https://docs.aiohttp.org/en/stable/client_advanced.html?highlight=unclosed#graceful-shutdown)). Both `SecretClient` and `DefaultAzureCredential` have a `close` method allowing you to do this, and are async context managers:
```py
from azure.identity.aio import DefaultAzureCredential
from azure.keyvault.secrets.aio import SecretClient

credential = DefaultAzureCredential()
client = SecretClient(VAULT_URL, credential)
... 
# close when you're done with the objects
await client.close()
await credential.close()

# or use them as context managers
async with DefaultAzureCredential() as credential:
    async with SecretClient(VAULT_URL, credential) as client:
        ...
```

**Comment by victoraugustolls** [comment]
Nice, though the sessions were handled inside the client! Thanks, this solved the issue!

**Comment by dushuning** [comment]
this question is so easy, you need to close the aiohttp's session, and the response is not need to close
![image](https://user-images.githubusercontent.com/48204151/188826942-cdbd8ffa-fb32-493d-921a-a8ce32c66ab3.png)
