### ISSUE TITLE
Cloud storage space.Computer down using android for windows OS. courses.                                         To attain a bachelor's degree in Business administration & With a focus on E-marketing and IT.                              1 Solution:Buy a new computer,upload workload to android then start over.             2 To use android in place of windows OS.                                3 To buy a disk for computer system and attempt to reboot the old system.

### ISSUE THREAD

**Issue by mikenass51** [Azure/azure-sdk-for-python#13251]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kaerm** [comment]
It seems that you didn't fill the issue template with an actual issue description, so we're closing this but feel free to open any issues if you have any comments about the SDK
