### ISSUE TITLE
Type hints incorrect for BlobClient.delete_blob()

### ISSUE THREAD

**Issue by howardjones** [Azure/azure-sdk-for-python#13261]
- **Package Name**:  azure-storage-blob
- **Package Version**: 12.4.0
- **Operating System**: Linux (ubuntu 18 LTS)
- **Python Version**: 3.8.0

**Describe the bug**

Docs for BlobClient.delete_blob() say that it takes a string parameter for delete_snapshots. The type hints on the function itself say that this is a bool.

https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#delete-blob-delete-snapshots-false----kwargs-

```python
 @distributed_trace
    def delete_blob(self, delete_snapshots=False, **kwargs):
        # type: (bool, **Any) -> None
```

**Expected behavior**

The docs should reflect reality. My IDE shouldn't flag my valid code as incorrect.

**Comment by xiafu-msft** [comment]
Hi @howardjones 

Thanks for catching this! We will make the the type hints on the function correct. It should be like this
```
 @distributed_trace
    def delete_blob(self, delete_snapshots="', **kwargs):
        # type: (str, **Any) -> None
```

**Comment by tasherif-msft** [comment]
The PR for the change has been merged and will be in our next release. Thank you
