### ISSUE TITLE
[AppConfig] Missing quotes for "If-Match" etag header

### ISSUE THREAD

**Issue by avanigupta** [Azure/azure-sdk-for-python#13276]
https://github.com/Azure/azure-sdk-for-python/blob/d334964f67d664cf572ec193c97416a03635cc24/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py#L501-L549

While trying to use the lock/unlock API like this:
`kv = azconfig_client.set_read_only(configurationSetting, if_match=configurationSetting.etag)`

I noticed that the If-Match etag request header is not properly quoted while constructing the request [here](https://github.com/Azure/azure-sdk-for-python/blob/d334964f67d664cf572ec193c97416a03635cc24/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_generated/operations/_azure_app_configuration_operations.py#L800-L801). 

Instead of passing `if_match` argument with `set_read_only`, it would be better if we could just pass the `match_condition` argument like in all other methods in this module (for example: [here, quotations are handled properly](https://github.com/Azure/azure-sdk-for-python/blob/d334964f67d664cf572ec193c97416a03635cc24/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py#L256)).

**Comment by xiangyan99** [comment]
Fixed.
