### ISSUE TITLE
Instance of 'ContainerProxy' has no 'execute_stored_procedure' member

### ISSUE THREAD

**Issue by namnh06** [Azure/azure-sdk-for-python#13290]
I follow the instruction at https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-use-stored-procedures-triggers-udfs#stored-procedures---python-sdk

When I implemented this:
`container.execute_stored_procedure(sproc_link)`

the error shows up:

> Instance of 'ContainerProxy' has no 'execute_stored_procedure' member

Dig deep into the API at https://docs.microsoft.com/en-us/python/api/overview/azure/cosmosdb?view=azure-python
And yes, there is no execute_stored_procedure

But still found it here: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-cosmos/4.1.0/_modules/azure/cosmos/scripts.html

Did anyone meet this?

**Comment by southpolesteve** [comment]
@namnh06 BTW, in the future please file issues in the new repo: https://github.com/Azure/azure-sdk-for-python/. I have gone ahead and transferred this issue there.

**Comment by namnh06** [comment]
Hi @southpolesteve , thanks for your hard work, it's working now.
For whom who looking for this:
```
    url = os.environ["COSMOS_END_POINT"]
    key = os.environ["COSMOS_KEY"]
    client = CosmosClient(url, key)
    database_name = 'ClickVuVerifyDB'
    database = client.get_database_client(database_name)
    container_name: str = 'UserContainer'
    container = database.get_container_client(container_name)
    stored_procedure_name = 'spCountRecords'
    container.scripts.execute_stored_procedure(
    stored_procedure_name, partition_key=2)
```

**Comment by Rodrigossz** [comment]
PR Created. Let's wait.

**Comment by Rodrigossz** [comment]
PR Merged. Will be published in the next days. Tks

**Comment by Rodrigossz** [comment]
Fixed.
