### ISSUE TITLE
Cannot get a quota management response from the SDK

### ISSUE THREAD

**Issue by ss8913** [Azure/azure-sdk-for-python#13343]
- **Package Name**: azure-mgmt-reservations 
- **Package Version**: 0.7.0 installed with --pre via pip3
- **Operating System**: CentOS 7
- **Python Version**: 3.6

**Describe the bug**
When querying for either a single or list of quotas in one of my subscriptions, I get a "Not Found" response from the API every time, even though the data I'm asking for definitely exists and is visible from the Azure web portal.

**To Reproduce**
Here is sample code that I am using which can reproduce the problem, just fill in a valid subscription ID and make sure you've got a shell credential active via 'az login':

```
#!/usr/bin/python3

import sys
from azure.common.client_factory import get_client_from_cli_profile
from azure.mgmt.reservations import AzureReservationAPI
from azure.mgmt.resource import ResourceManagementClient

subscription = "<insert valid subscription ID>"
provider = "Microsoft.Compute"
sku = "standardFSv2Family"
location = "eastus"

client = get_client_from_cli_profile(AzureReservationAPI, subscription_id=subscription)
if client is None:
  print("Error: client creation error.")
  sys.exit(1)
else:
  print("* Client created.")
print("* {0:20s}: {1}".format("Subscription",subscription))
print("* {0:20s}: {1}".format("Provider",provider))
print("* {0:20s}: {1}".format("Location",location))
print("* {0:20s}: {1}".format("SKU",sku))
try:    
  quota_list = client.quotas.list_status(subscription, provider, location)
  for quota in quota_list:
    print(quota)
except:
  exc_info=sys.exc_info()
  print("** List Exception: {0} {1}".format(exc_info[0], exc_info[1]))
try:
  my_quota = client.quota.list_status(subscription, provider, location, sku)
  print(my_quota)
except:
  exc_info=sys.exc_info()
  print("** SKU quota exception: {0} {1}".format(exc_info[0], exc_info[1]))
```

**Expected behavior**
I expect a list of quotas applicable to the subscription, followed by the quota info specific to the given sku, when running the above code.

**Screenshots**

**Additional context**
Actual response from the above code:

```
** List Exception: <class 'azure.mgmt.reservations.models._models_py3.ExceptionResponseException'> Operation returned an invalid status code 'Not Found'
** SKU quota exception: <class 'azure.mgmt.reservations.models._models_py3.ExceptionResponseException'> Operation returned an invalid status code 'Not Found'
```

**Comment by samiam2642** [comment]
Hi @ss8913, I see that you are making the call "list_status". This operation is intended for getting the status of historical calls to increase your quota. To list currently active quota in your subscription for a provider, please use just the "list" operation instead.

**Comment by ss8913** [comment]
** List Exception: <class 'AttributeError'> 'QuotasOperations' object has no attribute 'list'

am I using the wrong object?

**Comment by samiam2642** [comment]
@ss8913, my apologies, I missed which version of the package you were using. I highly recommend you upgrade to the recently released version [0.8.0](https://pypi.org/project/azure-mgmt-reservations/0.8.0/) of our package as it corrects several issues existing with the preview version in 0.7.0 and there are no plans for fixes against version 0.7.0 of the SDK. In the new version you can call [`client.quota.list()`](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-reservations/0.8.0/azure.mgmt.reservations.operations.html#azure.mgmt.reservations.operations.QuotaOperations.list) and [`client.quota.get()`](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-reservations/0.8.0/azure.mgmt.reservations.operations.html#azure.mgmt.reservations.operations.QuotaOperations.get).

In case you are unable to upgrade package versions, I will work on further debugging your specific issue with 0.7.0 to see if there is anything we can do to get it working for you.

**Comment by samiam2642** [comment]
@ss8913 We are also seeing some potential issues that a package upgrade alone may not resolve. Can you please confirm that you have [registered](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-register-resource-provider) both Microsoft.Capacity and Microsoft.Compute resource providers against the subscription you are testing against?

Also, if you would be willing to please send the subscription ID for which you are testing to me at samallon@microsoft.com, it would help us narrow down potential causes and resolve this for you quickly.

**Comment by ss8913** [comment]
I did the upgrade and changed my code to "quota.list()" and, that function exists, but i'm back to the original problem where it returns 'not found'.  I'd.. think that I had those providers registered?  I'm doing a lot of other API ops on this subscription which work.. how would I check/verify that?  I'll send you the sub ID separately from my work address in a bit.

**Comment by ss8913** [comment]
after upgrading and verifying the Microsoft.Capacity provider was registered on the subscription in question, it works as advertised, thanks for the help.  closing this issue now - I did end up using the 0.8.0 with the '--pre' option (via pip3) to get the latest version of the module.
