### ISSUE TITLE
Support SNI authentication with async CertificateCredential

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#13349]
The Azure SDK relies on MSAL for SNI support, and MSAL Python doesn't have an async API (tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/88)). In the meantime you can use the sync credential. Your token requests would then be blocking but those are infrequent, so the perf impact isn't bad.

**Comment by Moustafa-Moustafa** [comment]
Is there any update on the progress/status of this issue?
