### ISSUE TITLE
RecoveryServicesBackup - Discovery Protectable Items

### ISSUE THREAD

**Issue by ecgg** [Azure/azure-sdk-for-python#1335]
Is it possible to trigger a discovery of protectable items (just like it seems to happen in the Azure portal) via the Python SDK?

**Comment by lmazuel** [comment]
@DheerendraRathor for help again :)

**Comment by DheerendraRathor** [comment]
@ecgg Yes it is possible. 
`client.protection_containers.refresh(vault_name, resource_group, fabric_name)`

**Comment by ecgg** [comment]
@DheerendraRathor

Thanks for helping out :)

recovery_client.protection_containers.refresh(bkp_vlt, config['Backup']['ResourceGroup'], config['Backup']['Fabric'])

That gives me a CloudInvalidInput/"Error "Invalid input error"

What am I missing?

**Comment by DheerendraRathor** [comment]
Fabric name should be `Azure`. so call will look like:
`recovery_client.protection_containers.refresh("my_vault", "my_vault_rg", "Azure")`. Fabric refers to backup fabric.

**Comment by ecgg** [comment]
That works but is there a way to poll for when this is finished - the refresh call doesn't return an operations id and the Protection​Container​Refresh​Operation​Results​Operations requires an id. Would that require me to loop through all operations and pick it out?

**Comment by DheerendraRathor** [comment]
No, refresh operation returns `Accepted` status code and `Location` header. You need to poll location header to get wait for completion. Refresh api doesn't return any response on completion so you need to wait for `200/201/204` status code. 

To get operation Id, parse location header returned by refresh. It contains operation Id.

**Comment by ecgg** [comment]
Thanks @DheerendraRathor, that worked - in case anyone is interested, here's how I did it:

```
# Discovers all the containers in the subscription that can be backed up to Recovery Services Vault
op = recovery_client.protection_containers.refresh(bkp_vlt, config['Backup']['ResourceGroup'], "Azure", raw=True)

m = re.search('/([^\?/]+)\?api', op.response.headers['Location'])
op_id = m.group(1)

op_result_code = 0
sleep_duration = 2

while op_result_code not in  (200, 201, 204):
    time.sleep(sleep_duration)
    op = recovery_client.protection_container_refresh_operation_results.get(bkp_vlt, config['Backup']['ResourceGroup'], "Azure",op_id, raw=True)
    op_result_code = op.response.status_code

print('Refresh operation ended')
```
