### ISSUE TITLE
Use DeviceCodeCredential in container

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-python#13353]
pacakge: azure-identity==1.4.0
Identity E2E test in containers

Need to live test every credential of azure-identity in container, but I can't figure out a good way to live test `DeviceCodeCredential` with pytest in a container.

For example this is `test.py`:
```
def test_device_code():
        cred = DeviceCodeCredential()
        client = SecretClient(vault_url, cred)
        secret = client.get_secret('secret')
        assert secret.value
```
Test this with `pytest test.py`.
Since `DeviceCodeCredential` is interactive, it would cause pytest to hang.

@jongio

**Comment by cxznmhdcxz** [comment]
@jongio

**Comment by chlowell** [comment]
There's no reasonable way to do this automatically but we do have a manual test case for it. Adding these arguments to your `pytest` command line should run it: `--manual -s -k device_code`. The device code will print to stdout.
