### ISSUE TITLE
download_blob does not work when dockerized (urllib3.connection.HTTPSConnection Errno -2)

### ISSUE THREAD

**Issue by zorzigio** [Azure/azure-sdk-for-python#13363]
- **Package Name**: azure.storage.blob
- **Package Version**: 12.4.0
- **Operating System**: Alpine Linux
- **Python Version**: 3.8

**Describe the bug**
Running the command `download_stream = blobClient.download_blob()` does not work when the application is dockerized (works fine when debugging from VS Code).
The raised error is
```
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7f8c179660d0>: Failed to establish a new connection: [Errno -2] Name or service not known
```

Looking at the logs I spotted a difference between the 2 environments: the azure library is logging some info, and one of those is the request URL. When the application is dockerized, the url is (1), while (2) when debugging from VS Code (note that there is an extra " in (1))
1. Request URL: 'https://datalake.blob.core.windows.net"/giorgio/projectgiorgio/web_upload/natural_language_processing%20%281%29%20%281%29%20%281%29.pdf/4'
2. Request URL: 'https://datalake.blob.core.windows.net/giorgio/projectgiorgio/web_upload/natural_language_processing%20%281%29%20%281%29%20%281%29.pdf/4'

Here is the [log](https://github.com/Azure/azure-sdk-for-python/files/5135784/log.txt) produced during the error

**To Reproduce**
Run the following Python code

```python

import os
from azure.storage.blob import BlobServiceClient

container_name = "container_name"
blob_name = "blob_name"
blobServiceClient = BlobServiceClient.from_connection_string(os.getenv('STORAGE_CONNECTION_STRING'))
blobClient = blobServiceClient.get_blob_client(
    container_name,
    blob_name,
    snapshot=None
)
download_stream = blobClient.download_blob() # <- error thrown here
content = download_stream.readall()
```

inside a docker container using the image `tiangolo/uvicorn-gunicorn:python3.8`

**Expected behavior**
The file is downloaded correctly

**Comment by tasherif-msft** [comment]
Hi @zorzigio,

That's a very interesting issue that you came across. I'll have a look and will update you.
Thank you :)

**Comment by zorzigio** [comment]
Hi @tasherif-msft,

Thank you for looking into it. Do you have any update on the issue?

I realised I am now having the same problem in another repository as well which uses the image `python:3.9.0b3-alpine3.12`

**Comment by tasherif-msft** [comment]
Hey @zorzigio, I've tried reproducing the issue with no luck unfortunately :disappointed: 
Would you be able to provide me with the Dockerfile you used?

Thank you.

**Comment by tasherif-msft** [comment]
@zorzigio any updates?

**Comment by Rafi99769** [comment]
I am facing the exact same issue!

**Comment by dryleaf** [comment]
Did anyone find a solution to this issue?

**Comment by ahnaf012** [comment]
I was able to run download_blob_from_url() from azure.storage.blob package in Docker container by installing ca-certificates. I added the below line in my Dockerfile
`RUN apt-get -y --no-install-recommends install ca-certificates`
Its successfully running now.

**Comment by lnkirkham-datasparq** [comment]
I have identical occurring: an additional " in the request URL when running inside a docker container.

Adding `RUN apt-get -y --no-install-recommends install ca-certificates` in my Dockerfile and rebuilding made no difference.

Any solutions found recently?

**Comment by ifekxp** [comment]
Hello, I was also getting same error but after adding certificate, I am now getting following error:

`
WARNING Unable to upload: Retry: 0 FileName: abc.zip Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
`

In Dockerfile, I added certificate like this:

```
RUN apt-get update && apt-get -y install ca-certificates
ADD our.cer /usr/local/share/ca-certificates/our.crt
RUN chmod 644 /usr/local/share/ca-certificates/our.crt && update-ca-certificates
```


Our connection string is like this:
`DefaultEndpointsProtocol=https;AccountName=our-account;AccountKey=our-secret;EndpointSuffix=core.windows.net`

Any idea how to resolve this?

**Comment by ifekxp** [comment]
Update:

I was able to make it working after adding "connection_verify=False" parameter to the end of  BlobServiceClient.from_connection_string() and blob_client.upload_blob() methods!
