### ISSUE TITLE
Support Environment Variable "AZURE_CLOUD"

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-python#13397]
According to environment variables listed in https://github.com/Azure/azure-sdk/blob/master/_includes/tables/environment_variables.md

Add support for environment variable "AZURE_CLOUD"

</br>
@jongio

**Comment by v-xuto** [comment]
@lmazuel for notification.

**Comment by lmazuel** [comment]
@v-xuto it's a missing azure-core feature, that needs to be discussed with architecst. CC @johanste
