### ISSUE TITLE
Using JSON payload

### ISSUE THREAD

**Issue by uschen** [Azure/azure-sdk-for-python#134]
Since Azure storage now supports JSON, it might be beneficial to parse JSON vs XML using python (haven't bench-marked)

**Comment by huguesv** [comment]
Storage and Service Bus now use ElementTree for xml deserialization.  This, with some other changes have improved the performance of deserialization significantly.
https://github.com/Azure/azure-sdk-for-python/issues/254

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/19
