### ISSUE TITLE
Time out error due to task name in Azure Batch

### ISSUE THREAD

**Issue by stawo** [Azure/azure-sdk-for-python#1340]
Steps that lead me to the error:
- create a batch account
- create a job (via API)
- define a task where the Id contains an invalid character, example '.' (dot) (via API)
- add the task to the job (via API)

The program will fail due to time out (see attached file).
[Time our error.txt](https://github.com/Azure/azure-sdk-for-python/files/1190411/Time.our.error.txt)

Expected behaviour:
the function task.add_collection(job_id, tasks) in azure.batch should check the string passed, and raise an exception if it contains an invalid character.
From the web interface of Azure, the name of the task should be:
"A string that uniquely identifies the task within the job. The id can contain any combination of alphanumeric characters including hyphens and underscores and cannot contain more than 64 characters."

**Comment by lmazuel** [comment]
Hi @stawo 

Since it's a network issue, could you check the version of your `msrest` package? This is the one handling with requests, and if it's not the latest version, updating it might help a lot.

Adding @annatisch from Batch also

**Comment by stawo** [comment]
Hi @lmazuel 
To be sure, I updated all the pip packages. I ran:
pip install --update msrest
pip install --update azure

Now I have:
msrest (0.4.11)
azure (2.0.0)
azure-batch (3.0.0)

The problem persists as described above, no changes in the output.

**Comment by bgklein** [comment]
Confirmed that this issue no longer exists. Feel free to close.
