### ISSUE TITLE
Support Environment Variable "AZURE_RESOURCE_GROUP"

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-python#13402]
According to environment variables listed in https://github.com/Azure/azure-sdk/blob/master/_includes/tables/environment_variables.md

Add support for environment variable "AZURE_RESOURCE_GROUP"

@jongio

**Comment by lmazuel** [comment]
Hi @cxznmhdcxz , could you get more precise about where you want that support? For instance, it's definitely not an azure-core issue, since azure-core is agnostic of ARM.
Thanks,
