### ISSUE TITLE
Use InteractiveBrowserCredential in Container

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-python#13403]
pacakge: azure-identity==1.4.0
Identity E2E test in containers
Live test every credential of azure-identity in container.

Can't figure out a good way to pytest  `InteractiveBrowserCredential` in a container, since:
1. No browser/GUI in container. 
1. It's interactive, it will hang

</br>
@jongio

**Comment by chlowell** [comment]
Closing this because `InteractiveBrowserCredential` isn't expected to work in a container.
