### ISSUE TITLE
Support Environment Variable "AZURE_SUBSCRIPTION_ID"

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-python#13401]
According to environment variables listed in https://github.com/Azure/azure-sdk/blob/master/_includes/tables/environment_variables.md

Add support for environment variable "AZURE_SUBSCRIPTION_ID"
        

@jongio

**Comment by v-xuto** [comment]
@lmazuel for notification.

**Comment by xiangyan99** [comment]
@johanste any ideas?
