### ISSUE TITLE
[Tables] Make integer default serialization 32bit

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#13420]
Currently the Tables SDK defaults an integer to serialize as 64bit. However this creates compatibility issues with the other languages - specifically JS, where this will be returned as a string.
We should behave consistently and use 32bit as the default.
This will mean:
- We will need to write some tests to see what the error behaviour is for users providing a numeric value greater than the 32bit max
- We should update any samples, docs etc to describe how to handle this error - i.e. the `EntityProperty` wrapper to specifying 64bit data type.
- We could think about automatically using 64bit type for large integer values.... but not for first preview.
- At some point we should set up some cross language compatbility tests, again, this can be post preview1.

**Comment by seankane-msft** [comment]
If the number is more than 64 bits, a TypeError is thrown stating that the value cannot be contained within. In [this PR](https://github.com/Azure/azure-sdk-for-python/pull/13452) I address some of the above concerns.

**Comment by seankane-msft** [comment]
@annatisch Do we want to change this to make integer serialization use Int64 if a number is larger than a 32 bit representation? If not I think we can close this issue.
