### ISSUE TITLE
How to get the operation id from the virtual_machines's power_off(..) 

### ISSUE THREAD

**Issue by prajaktasd** [Azure/azure-sdk-for-python#13425]
- **Package Name**: azure.mgmt.compute ComputeManagementClient
- **Package Version**: 12.1.0
- **Operating System**:  Mac
- **Python Version**: 3.7

**Describe the bug**
I am trying to powet_off a VM in a resource group and looking for an API that would stop the VM asynchronously and return operation information with operation id. 
While debugging I see that the information is available under LROPoller, but unable to derive the polling method and operation id from the LROPoller. The object seems to have the information, but not able to find good documentation to extract operation id.
**To Reproduce**
1. start/stop instance

**Comment by prajaktasd** [comment]
Please let me know how can I upload the screenshot?

**Comment by changlong-liu** [comment]
Hi, @prajaktasd ,

We don't have an operation id for each LRO, but the polling can be done like this:

~~~
lro = mgmt_client.virtual_machines.power_off(resource_group_name, VIRTUAL_MACHINE_NAME)
result = lro.result()      # polling and wait for result
~~~
