### ISSUE TITLE
How to send various types logs operation to Graylog.

### ISSUE THREAD

**Issue by onenessboy** [Azure/azure-sdk-for-python#13438]
- **Package Name**:  Network Watcher, AD
- **Operating System**: Linux
- **Python Version**:  3.6

**Describe the bug**
Is there any via python sdk to send all following logs into  Graylog server ?
1.Azure portal login  (success/failure)
2.Resource activities. (CRUD operations )
3.NSG flow logs
4.API calls to Azure services.

any guidance would be appreciated

**Comment by rmeichsner** [comment]
I would like to get the same guidance. I don‘t think the issue is addressed right now. 

Thanks
