### ISSUE TITLE
Programatically add prefix/suffix filter when creating EventGridDataConnection (azure-mgmt-kusto) 

### ISSUE THREAD

**Issue by squassina** [Azure/azure-sdk-for-python#13440]
I currently using Azure Data Explorer and I was trying to do data ingestion via event grid programmatically.

In the interface I can set the filter settings with prefix and suffix, but I want to be able to do this via scripts, so whenever I want to create a new environment, such as develop and production, I can do the same all the time.

This is what we have in Azure Portal:
![image](https://user-images.githubusercontent.com/8495707/91720829-23562700-eb6e-11ea-82c1-2567c1b95f10.png)

I was able to create the connection using the documentation for Python API (https://docs.microsoft.com/en-us/azure/data-explorer/data-connection-event-grid-python), but I didn’t find how to provide the filter settings as parameters.

This is the section in the code on how I am creating the resource:

```python
poller = kusto_management_client.data_connections.create_or_update(
                                                resource_group_name=resource_group_name,
                                                cluster_name=cluster_name,
                                                database_name=database_name,
                                                data_connection_name=data_connection_name,
                                                parameters=EventGridDataConnection(
                                                                                    storage_account_resource_id=storage_account_resource_id,
                                                                                    event_hub_resource_id=event_hub_resource_id,
                                                                                    consumer_group=consumer_group,
                                                                                    table_name=table_name,
                                                                                    location=location,
                                                                                    mapping_rule_name=mapping_rule_name,
                                                                                    data_format=data_format,
                                                                                    blob_storage_event_type=blob_storage_event_type
                                                                                    )
                                                                                )
```

**Comment by orhasban** [comment]
Hi @squassina thanks for reaching out.

The portal experience actually creates 4 resources on the subscription (this is the automatic experience):
1. Event hub namespace
2. Event Hub 
3. Event Grid 
4. Data connection

The prefix and suffix parts in the form are Event Grid's props that called: _subjectBeginsWith, subjectEndsWith_
You can read about it more in: https://docs.microsoft.com/en-us/azure/event-grid/event-filtering

![image](https://user-images.githubusercontent.com/39991747/91896566-c2c80680-eca1-11ea-9307-3b0c690aac77.png)

**Comment by squassina** [comment]
Yes, the portal is creating that fine, but is there an option to create it programmatically? By adding the filters to the parameters I should add to `EventGridDataConnection`?

**Comment by orhasban** [comment]
You can do it programmatically, but with Event Grid SDK. Not with ADX management SDK.

**Comment by squassina** [comment]
Ah! I got it now! Thank you! I'll try it right away!
