### ISSUE TITLE
Azure webjob could not import  DefaultAzureCredential with python 64bit extension

### ISSUE THREAD

**Issue by tanmaydattta** [Azure/azure-sdk-for-python#13471]
While using python3.6 64 bit extension, we can not use azure-identity. 
Throws error at:

```
import win32con
ModuleNotFoundError: No module named 'win32con'
```

Steps to reproduce. 

1. Create venv with pipeline and  main.py with following code 
```
activator = r'D:\home\site\wwwroot\venv\Scripts\activate_this.py' 
exec(open(activator).read(), {'__file__': activator})
import sys
site_packages = r"D:\home\site\wwwroot\venv\Lib\site-packages"
sys.path.append(site_packages)

from azure.identity import DefaultAzureCredential
credential = DefaultAzureCredential()


```

2. run.py just has <path_to_python_extension> main.py 

* You would need to change activate_this.py to work on python3 it can be copied from [here](https://github.com/pypa/virtualenv/blob/master/src/virtualenv/activation/python/activate_this.py)

Exact same code with 32-bit venv and default python3 (32bit) works without problems. 

Also there is no way to push your packages as local wheels and then install using pip for the python extension, this makes 64bit python code pretty much unusable to work with libraries which might be doing some post-installation work (pywin32 does some when it copies dlls)

**Comment by tanmaydattta** [comment]
All it is a blocker if we want to use Azure platform with 64bit python (which is what we should have been default in my opinion). Our code uses in-memory operation with large datasets and we can not go with python 32 bit extension at all.

**Comment by chlowell** [comment]
I'm unfamiliar with Webjobs, so I can't say what's going wrong in your case. I was able to run one that uses DefaultAzureCredential in Python 3.6 x64 though. I wouldn't be surprised to learn there's a better way, but here's what I did to get mine working:
1. Create a Windows App Service
1. Enable Managed Identity
1. Add the "Python 3.6.4 x64" extension
1. Use the diagnostic console to install azure-identity in the extension's site-packages
    - From the Web App blade in the portal:  Development Tools -> Advanced -> Debug console
1. Create a script locally:

>### script.py
>```py
>import sys
>print(sys.version)
>
>from azure.identity import DefaultAzureCredential
>DefaultAzureCredential().get_token("https://vault.azure.net/.default")
>print("it worked")
>```
5. Create this file next to the script (I learned about this from an [old blog post](https://docs.microsoft.com/en-us/archive/blogs/azureossds/running-python-webjob-on-azure-app-services-using-non-default-python-version)):

>### run.cmd
>```
>D:\home\python364x64\python.exe script.py
>```
6. Add script.py and run.cmd to a zip file
7. Create a Webjob with the zip file
8. Trigger the job

>### output
>```
>[09/23/2020 16:47:22 > 359bf2: SYS INFO] Status changed to Initializing
>[09/23/2020 16:47:22 > 359bf2: SYS INFO] Run script 'run.cmd' with script host - 'WindowsScriptHost'
>[09/23/2020 16:47:22 > 359bf2: SYS INFO] Status changed to Running
>[09/23/2020 16:47:23 > 359bf2: INFO] 
>[09/23/2020 16:47:23 > 359bf2: INFO] D:\local\Temp\jobs\triggered\webjob2\3uehxwft.>12j>D:\home\python364x64\python.exe script.py 
>[09/23/2020 16:47:27 > 359bf2: ERR ] EnvironmentCredential.get_token failed: EnvironmentCredential >authentication unavailable. Environment variables are not fully configured.
>[09/23/2020 16:47:27 > 359bf2: INFO] 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit >(AMD64)]
>[09/23/2020 16:47:27 > 359bf2: INFO] it worked
>[09/23/2020 16:47:27 > 359bf2: SYS INFO] Status changed to Success
>```

**Comment by tanmaydattta** [comment]
This might not work for this particular scenario as I forgot to mention that we do not have many of these settings available to us. (We are working on a very restricted azure portal)
1. It works behind proxy so pip install is not available, hence the need for local wheel packaging
2. Dev are unable to access the advanced tools
Seems to me like the best solution (for us) might be to request proper python 64 bit extension which can use pip install properly. Let me know how I can raise this request if possible.

**Comment by chlowell** [comment]
I'd raise a request through your usual support channel. I think that would be the best way to get in touch with someone familiar with WebJobs.

**Comment by chlowell** [comment]
I'm closing this because the trouble is apparently due to limitations of your environment, and not something we can overcome with a change to DefaultAzureCredential. Please feel free to open another issue, or reopen this one, if further investigation turns up a problem in our library.
