### ISSUE TITLE
Running DataLakeAnalyticsJobManagementClient job get operation hangs in Azure Functions

### ISSUE THREAD

**Issue by rkellyxm** [Azure/azure-sdk-for-python#1347]
I am trying to check the status of an ADLA job using the Data Lake Analytics Management SDK. The following loop will work for a few tries, but then it will hang on the call to get job. I am trying to run this in Azure Functions with the default Python environment (2.7.8). It appears that the rest client attempts to make a call but never returns.

def check_adla_status(adlaAccountName, jobId):
    credentials = ServicePrincipalCredentials(
        client_id = os.environ['SHIPYARD_AAD_APPLICATION_ID'],
        secret = os.environ['SHIPYARD_AAD_AUTH_KEY'],
        tenant = os.environ['SHIPYARD_AAD_DIRECTORY_ID'])

    adlaJobClient = DataLakeAnalyticsJobManagementClient(
        credentials,
        'azuredatalakeanalytics.net')

    jobResult = adlaJobClient.job.get(adlaAccountName, jobId)
    
    while jobResult.state != JobState.ended:
        print('Job is not yet done, waiting for 30 seconds. Current state: ' + jobResult.state.value)
        # wait 30 seconds
        wakeup = datetime.datetime.now() + datetime.timedelta(seconds=30)
        while datetime.datetime.now() < wakeup:
            pass
        try:
            jobResult = adlaJobClient.job.get(adlaAccountName, jobId)
            print("jobId: running {}".format(jobId))
        except e:
            print(e)
            tc.track_exception(*sys.exc_info())
            tc.flush()

**Comment by lmazuel** [comment]
@ro-joowan for help please :)

**Comment by lmazuel** [comment]
Close, per @ro-joowan recommendation, was fixed internally.
