### ISSUE TITLE
`azure-client` module unavailable via pip

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-sdk-for-python#1349]
It appears that the `azure-client` module is unavailable:
```
 ∅ ⤅  % sudo -H pip install azure-client
Collecting azure-client
  Could not find a version that satisfies the requirement azure-client (from versions: )
No matching distribution found for azure-client
```

This error is occurring with `pip 9.0.1 (python 3.5)`. Other packages (`azure-common`, `azure-mgmt`) install correctly.

See [Other Azure libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/other?view=azure-python) for reference.

**Comment by lmazuel** [comment]
This module does not exist, could you be more precise of what you expect to find? Like a sample of code you want to run?

**Comment by sptramer** [comment]
Like the `azure-mgmt` metapackage, I would expect it to install all client `pip` packages (see the [azure-client search results.](https://pypi.python.org/pypi?%3Aaction=search&term=azure-client&submit=search) Everything which is `azure-[^cli|mgmt]-.*` and is an officially maintained package not in `azure-common` should be installed.

If there are no plans to offer such a package documentation should be updated.

**Comment by lmazuel** [comment]
So, I think you talk about `pip install azure`

**Comment by sptramer** [comment]
Thank you! This is a docs issue and will be fixed there.
