### ISSUE TITLE
Encryption options during storage account creation

### ISSUE THREAD

**Issue by alexvicegrab** [Azure/azure-sdk-for-python#1350]
While running

```
az storage account create -g mygroup -n mystorageaccount --sku Standard_LRS --encryption blob file table queue
```

I see the follwoing error: __init__() got an unexpected keyword argument 'table'

```
az storage account create -g mygroup -n mystorageaccount --sku Standard_LRS --encryption blob file
```

Appears to work fine, but table and queue encryption during creation seems to fail due to some problem with the python parsing.

Thanks!

**Comment by alexvicegrab** [comment]
Just read this bit that tables and queues are not encrypted:
https://docs.microsoft.com/en-us/azure/storage/storage-service-encryption

But the CLI help does make it confusing by listing them both as possible values for encryption...

**Comment by lmazuel** [comment]
Hi @alexvicegrab,

Could you open your issue at the CLI tracker? To be sure your feedback is saved correctly :)
https://github.com/Azure/azure-cli/issues

Thanks!

**Comment by alexvicegrab** [comment]
Done, thank you!
