### ISSUE TITLE
Option to allow delete_blob for blob versions

### ISSUE THREAD

**Issue by kgopi05** [Azure/azure-sdk-for-python#13527]
Hi, 

Recently Blob versions is enabled for GA , Hence we need option to enable lifecycle policies for Blob versions and python client delete_blob to allow versions only . 

https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#delete-blobs--blobs----kwargs-

**Comment by xiafu-msft** [comment]
Hi @kgopi05 

Thanks for reaching out.
For blob_client.delete_blob, you can specify version_id parameter https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.4.0/azure.storage.blob.html#azure.storage.blob.ContainerClient.delete_blob

for delete_blobs it seems currently you cannot batch delete blob versions, we will double check and see if we are missing adding that to delete_blobs.

Hi @scbedd can you help take a look at the doc https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#delete-blob-delete-snapshots-false----kwargs-
it's missing some kwargs, here's how the api should look like https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.4.0/azure.storage.blob.html#azure.storage.blob.ContainerClient.delete_blob

**Comment by kgopi05** [comment]
> Hi @kgopi05
> 
> Thanks for reaching out.
> For blob_client.delete_blob, you can specify version_id parameter https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.4.0/azure.storage.blob.html#azure.storage.blob.ContainerClient.delete_blob
> 

i'm unable to see the version_id in the blob parameters list , can you refer the right documentation link please ? 

> for delete_blobs it seems currently you cannot batch delete blob versions, we will double check and see if we are missing adding that to delete_blobs.
> 
> Hi @scbedd can you help take a look at the doc https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#delete-blob-delete-snapshots-false----kwargs-
> it's missing some kwargs, here's how the api should look like https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.4.0/azure.storage.blob.html#azure.storage.blob.ContainerClient.delete_blob

**Comment by xiafu-msft** [comment]
Hi @kgopi05 

Sorry I was looking at BlobClient.delete_blob() which is this https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.4.0/azure.storage.blob.html#azure.storage.blob.BlobClient.delete_blob

Please use this as reference, the doc for ContainerClient.delete_blob() is not accurate enough! Thanks for helping catch this, we will post a pr in a bit

**Comment by tasherif-msft** [comment]
Hey @kgopi05 I have just put up a PR to fix the docstrings for `ContainerClient` :)
