### ISSUE TITLE
Make azure-cognitiveservices-formrecognizer deprecated on Github and PyPI

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#13534]
Since this package use v1, and it's not online anymore after 9/15/2020. 

https://pypi.org/project/azure-cognitiveservices-formrecognizer/
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cognitiveservices/azure-cognitiveservices-formrecognizer

We shall point to v2 in azure-ai-formrecognizer

We shall remove it from CI.yml as well to save some CI time.

**Comment by kristapratico** [comment]
done, https://pypi.org/project/azure-cognitiveservices-formrecognizer/
