### ISSUE TITLE
[CosmosDB-Tables] does not support Azure Stack Hub Storage Accounts

### ISSUE THREAD

**Issue by elabbarw** [Azure/azure-sdk-for-python#13544]
- **Package Name**: azure.cosmosdb.table
- **Package Version**: 1.0.6
- **Operating System**: Docker Python3.8-slim
- **Python Version**: 3.8

**Describe the bug**

Receive the following error when attempting to interact with an Azure Stack Hub (2002) based table: 
azure.common.AzureHttpError: The value for one of the HTTP headers is not in the correct format

**To Reproduce**
1. Using TableService.insert_entity, etc.. with an Azure Stack Hub (2002) based Table

**Expected behavior**
Data is inserted into the table as expected. This currently works with:

- Azure Cloud based Tables

- Azure Stack Hub based Tables using the legacy TableService SDK

**Comment by seankane-msft** [comment]
Hi @ellabbarw, the new library for tables was released this month. Please try out the new library and let us know if that solves your problem.

https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/tables/azure-data-tables

**Comment by elabbarw** [comment]
Thanks! I will check it out.

**Comment by seankane-msft** [comment]
@elabbarw did this solve your issue?

**Comment by elabbarw** [comment]
> @elabbarw did this solve your issue?

Hi! Sorry for the delay in replying. Unfortunately I didn't get a chance to use the new library. But I am looking into it now and will let you know how it goes. I noticed the method names have changed along with a few other things.

**Comment by elabbarw** [comment]
Hi. After editing the module of Flask-Azure-Sessions (https://github.com/elabbarw/FlaskAzureTableSession) to use azure-data-tables I am still getting the below error when trying to use a connection string for an Azure Stack Hub (2002) Storage account:
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'The value for one of the HTTP headers is not in the correct format.'
 ErrorCode:InvalidHeaderValue
{http://schemas.microsoft.com/ado/2007/08/dataservices/metadata}error:

It works fine with Azure Cloud

**Comment by seankane-msft** [comment]
@elabbarw can you give me a step-by-step guide on how to reproduce that on my end? I'll admit that's a vague error and doesn't lead to anything immediate in my mind.

**Comment by elabbarw** [comment]
Sure, no worries.

Basically try to use a connection string generated from an Azure Stack Hub storage account, or use a custom storage account URL related to an Azure Stack Hub stamp with a sas key, and you will get that unhelpful error. You can reproduce this using the Azure Storage Explorer as well, where you will have to select the option to "Target Azure Stack APIs" and restart the app. It seems that although you can enter a custom URL, it is still assumed somewhere that you're connecting to Azure Cloud instead.

**Comment by elabbarw** [comment]
Azure Stack Hub APIs are usually behind when compared to the Azure Cloud so that might be the cause as well...

**Comment by lmazuel** [comment]
@elabbarw I reached out to the Azure Stack crew, it seems the new SDK won't work and 1.0.6 was the right choice given your stack version. This means that it would be very valuable if you can enable log information and get more details about the HTTP request/response you get. May I ask you to do that?

**Comment by seankane-msft** [comment]
@elabbarw There is information about logging [here](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/tables/azure-data-tables#logging). If you use the old cosmosdb library the keyword to enable logging is: `enable_http_logger=True` within your client creation. The code to create the logger is the following:

```
import sys
import logging
logger = logging.getLogger('msrest.http_logger')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)
```
