### ISSUE TITLE
Identity - support for client certificates in formats other than PEM

### ISSUE THREAD

**Issue by yichungyu** [Azure/azure-sdk-for-python#13540]
When users wish to use the Identity SDK for Python in conjunction with Azure Batch, they need to implement extra logic to convert their certificate from .pfx/.cer to .pem. Can we add logic so that the Identity SDK supports other certificate formats innately? 

Azure Batch documentation on certificates: https://docs.microsoft.com/en-us/azure/batch/batch-certificates
Suspected code where the current restriction for PEM-only certificates is implemented: https://github.com/Azure/azure-sdk-for-python/blob/eea845a56aa792f5b03b9188cd0180d42a3de4bb/sdk/identity/azure-identity/azure/identity/_internal/aadclient_certificate.py#L19
Python SDK reference describing the PEM-only restriction: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.4.0/index.html#environment-variables

**Comment by chlowell** [comment]
Thanks for opening this issue. I've put it on our backlog until we decide where it could fit into our roadmap. Until then, if you're reading this and this feature is important to you, please +1 the top comment to help us prioritize.

**Comment by DhavalShewale** [comment]
@chlowell By when can we expect support for PKCS12 certs to be available in the azure-identity library

**Comment by chlowell** [comment]
#16384 will be in 1.7.0b4, which we plan to release September 8
