### ISSUE TITLE
[CloudEvent] allow custom encoding

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#13555]
allow data other than base64 encoding and no encoding

- check if the swagger supports it

Currently, when sending  a cloud event, we encode the bytes to base_64 and send it as `data_base64`
if it's a string (python 3), we simply send it without any encoding as `data`.

The users should be allowed to send data with a custom encoding. For example, If a user wants to do `base8` encoding for the data, they should be allowed to do so. (perhaps send it as data?).

Open for design discussions on how to implement it

**Comment by lmazuel** [comment]
Closing, bytes are sent with data_base64, and string as data, that's enough
