### ISSUE TITLE
Improve backup operation error messages

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#13576]
When a poll receives a response indicating the operation failed, the resulting exception is 
`azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'OK'`.

Key Vault did respond 200 (OK), but the error message is confusing and unhelpful, and the response body contains more detail.

**Comment by chlowell** [comment]
A failed operation looks like this in JSON:
```json
{
    "azureStorageBlobContainerUri": null,
    "endTime": 1600896489,
    "error": {
        "code": null,
        "innererror": null,
        "message": null
    },
    "jobId": "45b1a0833c8046ed9471",
    "startTime": 1600896488,
    "status": "Failed",
    "statusDetails": "ContainerNotFound"
}
```
Today, the HttpResponseError [raised by LROPoller](https://github.com/Azure/azure-sdk-for-python/blob/fa582c6e0fe7790acb8202094b4215aeaddead74/sdk/core/azure-core/azure/core/polling/_poller.py#L262) when polling fails has the unhelpful message I quoted above. HttpResponseError does [parse the body's `error` object](https://github.com/Azure/azure-sdk-for-python/blob/fa582c6e0fe7790acb8202094b4215aeaddead74/sdk/core/azure-core/azure/core/exceptions.py#L274) to get a better one from the service response. However, in this case the service's `error` doesn't provide anything better. We could write client code to surface the response's `statusDetails` string but I prefer waiting for the service to start populating its `error` objects (as I expect it will before GA). Leaving this issue open for tracking.

**Comment by Dundonis** [comment]
> When a poll receives a response indicating the operation failed, the resulting exception is `azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'OK'`.
> 
> Key Vault did respond 200 (OK), but the error message is confusing and unhelpful, and the response body contains more detail.

Hi, did you solve this problem?

**Comment by mccoyp** [comment]
Hi @Dundonis, thank you for bringing my attention back to this tracking issue! Yes, the service does now respond with a more helpful error, so error messages are better now. For example, below is an example of a failed backup operation with API version 7.2:
```json
{
    "azureStorageBlobContainerUri": null,
    "endTime": 1641953249,
    "error": {
        "code": "InternalServerError",
        "innererror": null,
        "message": "Internal Server error, Please retry with an updated SAS token later"
    },
    "jobId": "f8d6e6b402bc434f88dbe9ea23a94d0d",
    "startTime": 1641953223,
    "status": "Failed",
    "statusDetails": "InternalServerError"
}
```
Exposed error messages are now correct because of the improved service responses. The error returned by the client for the above response is `azure.core.exceptions.HttpResponseError: (InternalServerError) Internal Server error, Please retry with an updated SAS token later`. I'll close this issue since it's been resolved.
