### ISSUE TITLE
Revise administration models

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#13575]
Decisions to make and implement:
- [ ] Prefer properties (`KeyVaultRoleAssignment`) or attributes (`_Operation`)?
    - properties have the benefit of easy immutability
- [ ] How to expose `_Operation.error`?
    - it matches the OData 4 error format, so we could raise it as [ODataV4Error](https://github.com/Azure/azure-sdk-for-python/blob/3808ad57daced04b57ff43018045b977105573ab/sdk/core/azure-core/azure/core/exceptions.py#L346)
- [x] ~Remove `SelectiveKeyRestoreOperation`? (it's identical in all but name to `RestoreOperation`)~
    - we decided to keep this as future-proofing
- [ ] `_Operation.start_time` and `.end_time` should be `datetime`

**Comment by mccoyp** [comment]
These changes are outdated due to new feedback -- new model alignment is tracked by #19099.
