### ISSUE TITLE
[EventGrid] ADd more samples

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#13582]
- Async samples
- Samples showing a more end to end usage - what exactly after send?

**Comment by swathipil** [comment]
**Progress on adding and running/testing async samples:**

- CHAMPION SCENARIOS
- [ ] cs1b_publish_custom_events_to_a_topic_with_signature.py
- [ ] cs1_publish_custom_events_to_a_topic.py
- [ ] cs2_publish_custom_events_to_a_domain_topic.py
- [ ] cs3_consume_system_events.py
- [ ] cs3_event_grid_event_system_event.json
- [ ] cs3_system_event.json
- [ ] cs4_consume_custom_events.py
- [ ] cs4_event_grid_event_custom_event.json
- [ ] cs5_publish_events_using_cloud_events_1.0_schema.py        
- [ ] cs6_cloud_event_system_event.json
- [ ] cs6_consume_events_using_cloud_events_1.0_schema.py

- PUBLISH SAMPLES
- [ ] publish_cloud_events_to_custom_topic_sample.py
- [ ] publish_cloud_events_to_domain_topic_sample.py
- [ ] publish_custom_schema_events_to_topic_sample.py
- [ ] publish_event_grid_events_to_custom_topic_sample.py        
- [ ] publish_with_shared_access_signature_sample.py

- CONSUME SAMPLES
- [ ] consume_cloud_custom_data_sample.py
- [ ] consume_eg_storage_blob_created_data_sample.py

- CONSUME E2E SAMPLES
- [ ] consume_cloud_events_from_eventhub.py
- [ ] consume_cloud_events_from_service_bus_queue.py
- [ ] consume_cloud_events_from_storage_queue.py

- CONSUME/E2E/FUNCTIONS SAMPLE
- [ ] functionsapp
