### ISSUE TITLE
[BUG Bash]cv2 error 

### ISSUE THREAD

**Issue by srivatsan18** [Azure/azure-sdk-for-python#13598]
from imageai.Detection.Custom import CustomObjectDetection
  File "/azureml-envs/azureml_699340d2ad71c046fd4645dbfa62da5d/lib/python3.6/site-packages/imageai/Detection/__init__.py", line 1, in <module>
    import cv2
  File "/azureml-envs/azureml_699340d2ad71c046fd4645dbfa62da5d/lib/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Error while deploying to an aci service 

Installed packages are imageai,tensorflow==2.2.0,opencv-python, pillow etc 
Yolov3 model

**Comment by LianwMS** [comment]
It seems like the issue of azureml sdk, which is not in current repo. Add service attestation label

**Comment by skvark** [comment]
You should be probably using the headless variant `opencv-python-headless` instead of `opencv-python`. It does not depend on GUI libraries which are not present in server environments.

**Comment by lostmygithubaccount** [comment]
@srivatsan18 is this still an issue?

**Comment by lostmygithubaccount** [comment]
#please-close

**Comment by srivatsan18** [comment]
Issue is resolved it was with the versioning of the opencv
