### ISSUE TITLE
[ServiceBus] Determine why name is not being properly scrubbed in dataplane mgmt namespace tests

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13596]
Observe commented line within `test_async_mgmt_namespace_get_properties` and its sync counterpart.

For whatever reason this name is not being scrubbed properly for recordings, despite the scrubber stanzas appearing to be properly aligned when run in a debugger (see error below)

```
        assert properties
        assert properties.messaging_sku == 'Standard'
>       assert properties.name == servicebus_namespace.name
E       AssertionError: assert 'servicebustestw2n6wljh3v' == 'servicebustestsbname'
E         - servicebustestsbname
E         + servicebustestw2n6wljh3v

tests\async_tests\mgmt_tests\test_mgmt_namespaces_async.py:24: AssertionError
```

Determine why this is and how to mitigate it.

**Comment by KieranBrantnerMagee** [comment]
Note: This is expected (debugged similar issue recently), replacers would not act on the properties bag but _would_ swap out the namespace name, as is seen above.  Comment can be removed.

**Comment by yunhaoling** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/15610
