### ISSUE TITLE
How to find serviceprincipal owner?

### ISSUE THREAD

**Issue by AmudhaPalani** [Azure/azure-sdk-for-python#1359]
Using SDK, how do I find owner of a ServicePrincipal. In AD graph explorer I can find this by using this endpoint: https://graph.windows.net/myorganization/servicePrincipals/serviceprincipal_id/owners.
How do I find same using GraphRbacManagementClient SDK?

**Comment by lmazuel** [comment]
Hi @AmudhaPalani sorry for the late answer.
@yugangw-msft do you know?

**Comment by AmudhaPalani** [comment]
I checked service_principal_operations.py and it's missing methods to list owners or update owners of a serviceprincipal. I am planning to contribute to adding these methods. I will push this code after I complete testing this locally.

**Comment by yugangw-msft** [comment]
@AmudhaPalani, you probably should start with updating the [API spec](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/graphrbac/data-plane/1.6/graphrbac.json#L855), this way all language SDKs can benefit from your contribution.
Probably you have verified already, but please make sure the response payload does contain this field.

**Comment by lmazuel** [comment]
This is in this PR https://github.com/Azure/azure-sdk-for-python/pull/1599
and will be released next Monday
