### ISSUE TITLE
Smoke tests for popular Docker containers and SDK installation

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#13619]
For popular container (let's start with `alpine`, `ubuntu` and `python`), we should smoke tests SDK installation for each version of python.

If the installation fails, we should figure out if this is fixable on our side, and if not do a disclaimer in the installation section of the doc with details and explanation, to avoid confusion on installation (example of instruction from `cryptography` for `alpine`: https://cryptography.io/en/latest/installation/#alpine)

**Comment by lmazuel** [comment]
I could imagine a section in the installation of azure-identity or azure-keyvault-xxxs like:
> If you're installating this package on an alpine container, please follow the installation steps for Alpine from the cryptography doc too

**Comment by seankane-msft** [comment]
@lmazuel are there other packages besides servicebus we want to add this for? Otherwise I will close this issue

**Comment by lmazuel** [comment]
SB is enough. Before we close, can you add in this issue a link to what was done?

**Comment by seankane-msft** [comment]
PR with guidance for azure-servicebus: https://github.com/Azure/azure-sdk-for-python/pull/16515
