### ISSUE TITLE
[engsys] Pipeline does not flag if the long_description is wrong

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-python#13639]
The following is not flagged in the setup.py file 
```
setup(
    ...
    long_description="\n\n",
    ...
)
```
This will return a `400 Bad Request` when trying to release a package to pypi.

**Comment by kurtzeborn** [comment]
This feels like something that should be labeled "Client" instead of "Central-EngSys" but it's already assigned to @scbedd, so I'm assuming there's some additional context there that means he should follow up on this.  If I'm incorrect, please relabel.

**Comment by lmazuel** [comment]
Closing, as I don't feel this has enough impact in real life to deserve spending time on it (after all, we can't release :))
