### ISSUE TITLE
[ServiceBus] Combine various connection string parsing logic

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13683]
Currently, parse_conn_str is implemented in _VERY_ similar manner in utils.py and in base_handler.py

One of these is for the data-plane ServiceBusAdministration code, the other is for the data-plane itself (servicebusclient and family.)

They can likely be combined significantly to reduce code duplication and improve maintainability.

In addition to this, _create_credential_from_connection_string_parameters is a VERY strange flow right now in order to provide sync vs async dispatch of the credential objects, coupling their respective implementation to the corrosponding sync or async handler.  If there's a clever way to move this all into utils we're game for improvements in this space.  (Considered using a functional callback to pass in the respective sync or async credential builder as a param to the create_credential function, but that seemed like a lateral move at best.)

**Comment by swathipil** [comment]
There is not a connection string parser method in [`utils.py`](https://github.com/Azure/azure-sdk-for-python/blob/febfe9d3243f33bbc30c76d7c8a6777a7404befd/sdk/servicebus/azure-servicebus/azure/servicebus/_common/utils.py) currently.

However, [`_connection_string_parser.py`](https://github.com/Azure/azure-sdk-for-python/blob/febfe9d3243f33bbc30c76d7c8a6777a7404befd/sdk/servicebus/azure-servicebus/azure/servicebus/_common/_connection_string_parser.py) also holds the duplicate  parsing logic, so it should also be combined with the `_base_handler.py` logic for parsing connection strings.
