### ISSUE TITLE
Have an automatic PR with updated generated code for each generator release

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#13725]
Done in C# already, when I trigger a release of autorest.python, I want an auto-PR here with the regeneration of all track2 that uses autorest.

It's done in C# already

**Comment by seankane-msft** [comment]
This has been semi-finished. Currently it is an opt-in service and being piloted with App Configuration. After testing, onboarding more services, and documenting the capabilities this issue can be closed

**Comment by seankane-msft** [comment]
Here is my original PR: https://github.com/Azure/azure-sdk-for-python/pull/16667

**Comment by lmazuel** [comment]
Let's close for now and revisit as necessary
