### ISSUE TITLE
Python Service Bus submission failure

### ISSUE THREAD

**Issue by gavinshark** [Azure/azure-sdk-for-python#13730]
- **Package Name**:  azure-servicebus     
- **Package Version**:  0.20.2
- **Operating System**: CentOS release 6.6
- **Python Version**: 2.7.6 

**Describe the bug**
Message submission failure. The call stack can be found as follows:
>' File "/usr/local/lib/python2.7/site-packages/azure/servicebus/servicebusservice.py", line 890, in send_queue_message\n self._perform_request(request)\n',
' File "/usr/local/lib/python2.7/site-packages/azure/servicebus/servicebusservice.py", line 1228, in _perform_request\n resp = self._filter(request)\n',
' File "/usr/local/lib/python2.7/site-packages/azure/servicebus/_http/httpclient.py", line 181, in perform_request\n self.send_request_body(connection, request.body)\n',
' File "/usr/local/lib/python2.7/site-packages/azure/servicebus/_http/httpclient.py", line 143, in send_request_body\n connection.send(request_body)\n',
' File "/usr/local/lib/python2.7/site-packages/azure/servicebus/_http/requestsclient.py", line 81, in send\n self.response = self.session.request(self.method, self.uri, data=request_body, headers=self.headers, timeout=self.timeout)\n',
' File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request\n resp = self.send(prep, **send_kwargs)\n',
' File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send\n r = adapter.send(request, **kwargs)\n',
' File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 370, in send\n timeout=timeout\n',
' File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 533, in urlopen\n conn = self._get_conn(timeout=pool_timeout)\n',
' File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 239, in _get_conn\n conn.close()\n',
' File "/usr/local/lib/python2.7/httplib.py", line 780, in close\n self.sock.close() # close it manually... there may be other refs\n',
' File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 213, in close\n return self.connection.shutdown()\n',
' File "build/bdist.linux-x86_64/egg/OpenSSL/SSL.py", line 1522, in shutdown\n self._raise_ssl_error(self._ssl, result)\n', ' File "build/bdist.linux-x86_64/egg/OpenSSL/SSL.py", line 1178, in _raise_ssl_error\n raise SysCallError(errno, errorcode.get(errno))\n', "SysCallError: (104, 'ECONNRESET')\n"

**To Reproduce**
`from azure.servicebus import ServiceBusService, Message`

`bus_service = ServiceBusService(service_namespace=namespace,`
`                                    shared_access_key_name=access_key_name,`
`                                    shared_access_key_value=access_key_value)`

`bus_service.send_queue_message(queue_name, msg)`

The issue can not reproduce 100% but 10%.
By the way, the 'bus_service' is used among multi-threads.
 

**Expected behavior**
Service bus can be submitted normally.

**Screenshots**
No.

**Additional context**

>Azure related packages installed:
azure-common (1.1.25)
azure-nspkg (3.0.2)
azure-servicebus (0.21.0)
azure-storage-common (0.37.1)
azure-storage-file (0.37.0)
azure-storage-nspkg (3.1.0)
azureopslib (1.0)

"azure(0.9.0)" was also installed before but uninstalled by conflicting with "azure-storage-file"

**Comment by KieranBrantnerMagee** [comment]
Hey @gavinshark , very appreciated for your taking the time to write this up so comprehensively and report it to us.

My first response reading is to raise an eyebrow at '0.21.0'.  That is, to put it lightly, a very dated version.  (We're currently in the process of releasing what we refer to as "track 2" versions of the library via 7.0.0b6, 0.21 would be "Track 0", so, quite a bit back.)

Is there any ability on your part to upgrade?  The 0.5* versions are the current latest non-preview release, and may simply make your problem go away, with only some (hopefully minor) overhead to port the code.

If you're feeling bold we encourage folks to jump into 7.0.0b6 but I like to give the big caveat that some of the surface area for that is still in flux until we formally GA.

Do let us know if this helps mitigate your issue, and don't hesitate to shout if there are constraints or other subtleties I'm missing or if the problem recurs.

**Comment by gavinshark** [comment]
Hey @KieranBrantnerMagee , thank you very much for your replay. 
I have tried azure-servicebus SDK with version 0.50.2. And the issue disappeared. I will keep on watching its availability.

**Comment by KieranBrantnerMagee** [comment]
Glad this seems to have helped.  Feel free to reopen this if any further issues or questions; closing for now.
