### ISSUE TITLE
[ServiceBus] [(Potentially)Preparers] Address "Resource does not exist" preparer errors.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13747]
Occasionally a Preparer will fail during livetest run because the resource it relies on does not appear to exist, despite that creation method having successfully returned.  See the failure below:

```
                    _logger.error(msg)
>                   raise Exception(msg)
E                   Exception: Preparer failure when creating resource ServiceBusQueueAuthorizationRulePreparer for test test_sb_client_incorrect_queue_conn_str (test_sb_client.ServiceBusClientTests): Operation returned an invalid status code 'Not Found'
E                   Detailed error message: The requested resource servicebustest_qtwofk7xh does not exist. CorrelationId: c8258c67-85f5-40d8-a5eb-e73d69aca731

.tox/whl/lib/python3.5/site-packages/azure_devtools/scenario_tests/preparers.py:82: Exception
------------------------------ Captured log call -------------------------------
ERROR    azure_devtools.scenario_tests.preparers:preparers.py:81 Preparer failure when creating resource ServiceBusQueueAuthorizationRulePreparer for test test_sb_client_incorrect_queue_conn_str (test_sb_client.ServiceBusClientTests): Operation returned an invalid status code 'Not Found'
Detailed error message: The requested resource servicebustest_qtwofk7xh does not exist. CorrelationId: c8258c67-85f5-40d8-a5eb-e73d69aca731
```

This has been observed at all levels, including RG, so may require centralized preparer fix, although lately has most been occurring as seen for AuthRules beneath ServiceBus, so focusing on that repro.

**Comment by chlowell** [comment]
Prior art from `KeyVaultPreparer`, handling name conflict and resource group not found: https://github.com/Azure/azure-sdk-for-python/blob/e25a3539b293731b345e1306e4ec601c69e8df70/tools/azure-sdk-tools/devtools_testutils/keyvault_preparer.py#L102-L115

**Comment by KieranBrantnerMagee** [comment]
Aha.  First; thanks for even noting this and thinking to add your breadcrumb, it's of great comfort to know that this isn't unprecedented.  Second, I'm curious if you have any thoughts on whether there would be a viable fix at the framework level? (If not, no worries, going to dig in myself for this work, just figured I'd ask in case there was any context you had encountered ala "don't waste your time because X" :P)

**Comment by chlowell** [comment]
It's easy enough to solve on an individual preparer basis. A more appropriate fix for Key Vault's case would arguably be to have `ResourceGroupPreparer`--which should own creating the group--poll ARM to ensure the group it creates is available before returning control to the framework. So at first thought it seems feasible for each preparer to do similar, or to expose to the framework a way to verify resource availability. I imagine a general solution touches every preparer. I've never seen a similar error from Key Vault though, so perhaps not all RPs have this problem and it's best solved as needed for individual preparers?

**Comment by KieranBrantnerMagee** [comment]
The first part of your train of thought is exactly where I was going with this. (shared method to determine resource existence) but the latter part (only seeing similar errors from certain things) does align with what I've seen.

I believe I've only ever seen it from RG (creating SB namespace within it) and the namespace itself (creating an auth rule within it), HOWEVER, for all I know this is just a emergent property of how those RPs trigger a problematic race more or less often and it is needed as a general fix, so I was flip-flopping.

Am likely going to patch it locally and use it as a learning opportunity to see if there's a clever way it could be generalized, since the two instances I've seen it are "quite different," and go from there to see if it recurs further.

**Comment by yunhaoling** [comment]
we could merge the PR first

**Comment by rakshith91** [comment]
moving this to march milestone
