### ISSUE TITLE
[EventHub] Addres Doc Generation warnings

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13748]
For the following EH doc releases, kindly go through warnings and address them

https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/798
https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/795
https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/797

**Comment by rakshith91** [comment]
Closing since there are no EH specific doc warnings in the PRs
