### ISSUE TITLE
[BUG][Face] OperationStatus does not deserialize correctly due to attribute map mismatch

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-python#13756]
- **Package Name**: azure.cognitiveservices.vision.face
- **Package Version**: 0.4.1
- **Operating System**: Windows 10 Enterprise 1909
- **Python Version**: 3.8.3

**Describe the bug**
When I take a snapshot and then call client.snapshot.get_operation_status, the server's response is not deserialized into an OperationStatus object correctly.

**To Reproduce**
1. Run `pip install azure.cognitiveservices.vision.face`
1. Run the following code.

Notes:
1. On line 12 assign KEY your Face subscription key.
1. On line 13 assign ENDPOINT your Face endpoint.
1. On line 14 you might need to change the person group ID in case mine doesn't work for you.

```
import asyncio
import os
import sys
import time
import uuid
from urllib.parse import urlparse

from azure.cognitiveservices.vision.face import FaceClient
from msrest.authentication import CognitiveServicesCredentials
from azure.cognitiveservices.vision.face.models import SnapshotObjectType, OperationStatusType

KEY = os.environ['FACE_SUBSCRIPTION_KEY']
ENDPOINT = os.environ['FACE_ENDPOINT']
PERSON_GROUP_ID = 'd776b090-4e07-4687-a6e8-5b0f69b9d5d6'

face_client = FaceClient(ENDPOINT, CognitiveServicesCredentials(KEY))

async def wait_for_operation(client, operation_id):
    result = client.snapshot.get_operation_status(operation_id=operation_id)
    status = result.status.lower()
    print('Operation status:', status)
    if ('notstarted' == status or 'running' == status):
        print("Waiting 10 seconds...")
        await asyncio.sleep(10)
        result = await wait_for_operation(client, operation_id)
    elif ('failed' == status):
        raise Exception("Operation failed. Reason:" + result.message)
    return result

async def main():
	take_snapshot_result = face_client.snapshot.take(
		type=SnapshotObjectType.person_group,
		object_id=PERSON_GROUP_ID,
		apply_scope=[KEY],
		# Set this to tell Snapshot.take to return the response; otherwise it returns None.
		raw=True
		)
	take_operation_id = take_snapshot_result.response.headers['Operation-Location'].replace('/operations/', '')
	take_status = await wait_for_operation(face_client, take_operation_id)
	snapshot_id = take_status.resource_location.replace ('/snapshots/', '')
	print(snapshot_id)

asyncio.run(main())
```

Output:
```
Operation status: notstarted
Waiting 10 seconds...
Operation status: succeeded
Traceback (most recent call last):
  File "test_snapshot.py", line 43, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "test_snapshot.py", line 40, in main
    snapshot_id = take_status.resource_location.replace ('/snapshots/', '')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Expected behavior**

OperationStatus.resource_location should contain a value.

**Additional context**

See the following related issue.
https://github.com/Azure/azure-sdk-for-net/issues/15120

This issue is happening because of the OperationStatus attribute map, specifically the following line.
https://github.com/Azure/azure-sdk-for-python/blob/e25a3539b293731b345e1306e4ec601c69e8df70/sdk/cognitiveservices/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/_models_py3.py#L1169

The OperationStatus.resource_location property has the JSON mapping `resourceLocation`.

However, in the response returned by the server, the corresponding field is "location", not "resourceLocation":
```
{
  "status": "succeeded",
  "createdDateTime": "2020-09-11T19:41:07.2046017+00:00",
  "location": "/snapshots/e7bde61d-63ef-4c40-9e4f-08ec38bd576e"
}
```

You can verify this by using API testing consoles, e.g.:
https://westcentralus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/snapshot-take/console
https://westcentralus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/operationstatus-get/console
An example operation ID is 5f0ddbe6-82fd-4ae9-a04c-6805c433cf28, though I don't know if that will work for you.

The OperationStatus attribute map should be defined as follows:
```
    _attribute_map = {
        'status': {'key': 'status', 'type': 'OperationStatusType'},
        'created_time': {'key': 'createdDateTime', 'type': 'iso-8601'},
        'last_action_time': {'key': 'lastActionTime', 'type': 'iso-8601'},
        'resource_location': {'key': 'location', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
    }
```

Note the created_time property mapping also needs changing.
I made these changes to my local copy of the package (specifically in
C:\Program Files\Python\Lib\site-packages\azure\cognitiveservices\vision\face\models\_models_py3.py).
I was then able to run my sample code successfully with the following output.

```
Operation status: running
Waiting 10 seconds...
Operation status: succeeded
fc848fc2-e8af-443f-9b7e-f3f47150c692
```

**Comment by lmazuel** [comment]
Thanks @v-jaswel for this very detailled bug, it seems indeed there is an important gap between what the Swagger that produces attribute_map is showing and the server. Needs help from the server team to conclude on this.

**Comment by v-jaswel** [comment]
Per sbowles, this is going to be fixed on the server side and not the SDK side. Therefore I am closing.
