### ISSUE TITLE
[EventHubs] Release EventHubs T1 1.3.4

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13751]
This is a tracking issue for releasing a bugfix version of the Track 1 EH library.  Currently scheduled for Nov. milestone.  Expect more details as the date gets closer.

**Comment by yunhaoling** [comment]
the T1 branch: https://github.com/Azure/azure-sdk-for-python/tree/release/eventhub-v1


changelog:
> **Features**
Add new parameter to AzureStorageCheckpointLeaseManager, use_consumer_group_as_directory, to control consumer_group pathing in concert with storage_blob_prefix.
**BugFixes**
Ensures storage_blob_prefix within AzureStorageCheckpointLeaseManager is actually applied.

the changes are in the commit: https://github.com/Azure/azure-sdk-for-python/commit/99b35c009f4915dd425b54ed4611551e9932b6ee

**Comment by yunhaoling** [comment]
closing the issue as there are no plans at the moment to make releases to v1 of Event Hubs
