### ISSUE TITLE
No getting started, overview or examples for azure-mgmt-servicebus?

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-sdk-for-python#13757]
Hi,
I am thinking to use the `azure-mgmt-servicebus` to allow my API to red and/or adjust some queue settings at runtime. I have been looking at 

https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-mgmt-servicebus

and following the links I got to 

https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python

which only contains a very bare documentation which really does not help at all. In the git repo here on Github there are no examples as far I as I know. I wonder if this package is maintain at all...

Any thoughts?

**Comment by nickzhums** [comment]
@andreacassioli could you take a look at the samples here?

https://github.com/Azure-Samples/azure-samples-python-management/tree/master/samples/servicebus

**Comment by andreacassioli** [comment]
Hi @nickzhums , it looks good to me.

If I may, you might want to put a short explanation of each example in the code, or in the github page. And you might also consider simplifying the examples removing the resource group creation. I think usually MS examples assumes you have most of the setup in place.
