### ISSUE TITLE
TXT records set through SDK calls results in improper string value

### ISSUE THREAD

**Issue by h-hwang** [Azure/azure-sdk-for-python#1376]
I am using the DNSManagementClient to make record changes to zones in Azure. It seems there is a bug when creating TXT records. When making a TXT record with this SDK, the value of a TXT record is not stored as a string, but as a list of characters. This behavior shows up elsewhere and is almost definitely unintended.

Example SDK construction call in python function in a placeholder domain:
```
dns_client = DnsManagementClient(…)
dns_client.record_sets.create_or_update('TestResource1', 'banana.com', 'test_txt_SDK', 'TXT', {'ttl': 100, 'txt_records':[TxtRecord('sample string')]})
```
I also made this same record in the Azure online portal. Here are the results:
![image](https://user-images.githubusercontent.com/29443197/29436378-0675da1e-8360-11e7-85e5-f7e764423cd6.png).

This is not just a cosmetic bug. We can retrieve this inconsistency when making calls to the zone. For example, here is what happens when we call the record using the SDK, as well as using dig:
![image](https://user-images.githubusercontent.com/29443197/29436417-387b6718-8360-11e7-924c-768ae1425202.png)
(this is to a different record)
![image](https://user-images.githubusercontent.com/29443197/29436542-dbe62cf8-8360-11e7-944f-6248d04d252e.png)

Furthermore, this bug also occurs when using the Azure CLI 2.0 to create the record. Making a TXT record through the Azure portal is the only method that has not returned this error.

**Comment by lmazuel** [comment]
Hi @h-hwang 
At the SDK level, TxtRecord is taking a list of strings as parameter, not a string as you do:
https://docs.microsoft.com/en-us/python/api/azure.mgmt.dns.models.txtrecord?view=azure-python

just change to `TxtRecord(['sample string'])` and your problem is solved :)

About CLI 2.0, I can't tell, but I guess the inline parameters should be a list as well. If you think the CLI is broken, can you open an issue here https://github.com/Azure/azure-cli/issues mentionning this one here? Thanks!

**Comment by tjprescott** [comment]
I have verified that the CLI's `record-set txt add-record` is working correctly. The bizarre behavior is that if you supply a list of strings `-v a b c` they will be concatenated together, but from the DNS team, this is the intended behavior.

**Comment by h-hwang** [comment]
Great, thanks! Just for future safety and redundancy, is it worth considering adding a check that the input is indeed a list instead of a string? I'm guessing it's currently iterating through `x` for the input of `TXTRecord(x)` without checking if it's a list and so iterates through the characters in this case. Regardless, thanks for the help!

**Comment by lmazuel** [comment]
Hi @h-hwang 
I created an issue in the core serializer about that. Thank you for the feeback!
