### ISSUE TITLE
Container client fails slowly instead of ResourceNotFound

### ISSUE THREAD

**Issue by AkhilGNair** [Azure/azure-sdk-for-python#13765]
- `azure-storage-blob`
-  `12.3.2`
- Ubuntu 20.04
- 3.8.2

**Describe the bug**
I've been advised in #12744 to open a new issue for this behaviour.

I'm trying to use

```
from azure.storage.blob import ContainerClient

client = ContainerClient("storage1234567", container_name="container-01")
client.get_container_properties()
```

to check if a container exists. I had expected either an immediate `ResourceNotFound` or otherwise some unauthorised message - basically anything that would allow me to fail fast. Instead the command runs for about 2 minutes, retrying twice (three times in total, I believe with some backoff) resulting in

```
azure.core.exceptions.ServiceRequestError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bd6ef8bb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
```

I have also tried all the timeout `kwargs` I can think of, `timeout`, `read_timeout`, `connection_timeout`, `socket_timeout` (supplied as numeric or tuple) and none make a difference.

Is there a way to short-circuit this and allow me to catch some faster failure?

**To Reproduce**
```
from azure.storage.blob import ContainerClient

client = ContainerClient("storage1234567", container_name="container-01")
client.get_container_properties()
```

**Expected behavior**
@tasherif-msft advises

> Hi @AkhilGNair, interesting issue you've come across, but this is actually an unexpected behavior. The error you're getting implies the request was not sent (you would receive a ResourceNotFound response from the server if the request was sent). 

My expectation is that I can quickly catch a failure!

**Comment by xiafu-msft** [comment]
Hi @AkhilGNair 

The error says "Temporary failure in name resolution"
can you try to change the container name to "container01"

**Comment by tasherif-msft** [comment]
Hi @AkhilGNair any updates on the issue? is it still persistent even after the container renaming?

**Comment by AkhilGNair** [comment]
Sorry, haven't been able to check this yet - will update tomorrow morning UK time! Thanks

**Comment by AkhilGNair** [comment]
Sorry for the long delay!

When trying

```
>>> client = ContainerClient("storage1234567", container_name="container01")  # changed from "container-01"
>>> client.get_container_properties()
```

I get the same error. A very long wait time, followed by

```
azure.core.exceptions.ServiceRequestError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f5713a79d00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
```

Thanks!

**Comment by tasherif-msft** [comment]
Hi @AkhilGNair,

On a closer look at your example, I noticed you put `storage1234567` as your account url, which is incorrect. Your account url for the blob service should look something like: `https://<STORAGE_ACC_NAME>.blob.core.windows.net` or just `<STORAGE_ACC_NAME>.blob.core.windows.net`. 

So assuming your account name is `storage1234567`, the account url would be: `https://storage1234567.blob.core.windows.net` You also have to ensure that you have set your credentials to be able to access that storage account and its resources, i.e, using a connection string or generating a SAS for example. 

Here is two good walk-throughs for this: https://docs.microsoft.com/en-us/python/api/overview/azure/storage-blob-readme?view=azure-python and https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python

This would also explain why the request was not sending.

Your issue also made me realize that we need to add an extra check to our `account_url` validation :) 

Let me know if this fixes your issue.

**Comment by AkhilGNair** [comment]
This is great (and makes me feel stupid :wink:) - the validation would be perfect as it was just the URL validation I was missing.

Creds are fine, no issue there - just wanted to catch the unauthorised error.

Thank you!

**Comment by AkhilGNair** [comment]
Hi @tasherif-msft - I would like to reopen please.

Although I was previously using the wrong name/credentials, this is actually the behaviour I am trying to catch.

My issue is that IF these details are entered incorrectly, the command takes a long time to fail. I am looking for a way to catch this, so it doesn't take 1 - 2 minutes before I get any feedback about the request not working:

```
client = ContainerClient("https://notreal.blob.core.windows.net", container_name = "hi", credential=get_credentials())
client.get_container_properties()
``` 

This fails as expected as the container name is not real. The issue is it takes over a minute to fail. Is there any way to quickly detect that the request has, or will be rejected (usually due to RBAC errors).

Thank you!

**Comment by tasherif-msft** [comment]
Hi @AkhilGNair, you can set the `timeout` parameter. You can also set the number of retries (defaults to 10).
This should be helpful for ya https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob#retry-policy-configuration

Let me know if you still need help :)

**Comment by AkhilGNair** [comment]
Hi @tasherif-msft thanks for getting back to me.

I'm using the following to test

```
from azure.storage.blob import ContainerClient


client = ContainerClient("https://notreal.blob.core.windows.net", container_name = "hi", retry_connect=1)
client.get_container_properties(connection_timeout=1)
```

Perhaps I'm misunderstanding what to expect.

The only way I can get the command to fail quickly is by setting the `retry_connect` (or `retry_total`) to `0`. I thought the connection timeout might be a useful way to configure the wait before error, but it doesn't seem to have any obvious effect. 

I haven't timed it, but what I was expecting was something like `retry_connection=2`, `connection_timeout=1` would mean a failing connection takes 2 seconds to return (but really it is more like a minute).

Setting the `retry_connect` to `0` helps my immediate issue, but if you could advise on my misunderstanding about the timeout it would help. 

Thanks!
Akhil

**Comment by tasherif-msft** [comment]
Hi @AkhilGNair! so the different timeouts have different purposes:

You're correct the `connection_timeout` should be the parameter to adjust for your use case.
Could you please try to set that parameter when instantiating your client?

so:
```
client = ContainerClient("https://notreal.blob.core.windows.net", container_name = "hi", retry_connect=1, connection_timeout=1)
client.get_container_properties()
```
Let me know if that gets it working :)

**Comment by AkhilGNair** [comment]
Hi I'm back after a long delay again!

I have tested your suggestion and it doesn't work as expected :(

Please see below:

```
> date "+%H:%M:%S"; python run.py; date "+%H:%M:%S"
17:06:31
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    client.get_container_properties()
  ...
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7f9dca3476d0>: Failed to establish a new connection: [Errno -2] Name or service not known
17:06:49
```

The script takes 18 seconds to fail (although this is only one run).

The script contains

```
> cat run.py 
from azure.storage.blob import ContainerClient

client = ContainerClient("https://notreal.blob.core.windows.net", container_name = "hi", retry_connect=1, connection_timeout=1)
client.get_container_properties()
```

And so I expected the script to take around 1 second to fail.

My package versions are currently at

```
> pip list | grep azure
azure-core         1.14.0   
azure-storage-blob 12.8.1
```

I would like to reopen this issue again if possible! Apologies for the very slow back and forth from my end.
