### ISSUE TITLE
[Performance] Consider sharing a single HTTP connection pool by default

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-python#13797]
To improve performance, Python should consider sharing a single HTTP connection pool by default, as is already done by other languages like .NET.

For example, this .NET code will use a single HTTP connection for both uploads, significantly improving the performance of the second upload:

```c#
var client1 = new BlobClient(connectionString, "test", "test");
client1.Upload(Stream.Null, overwrite: true);

var client2 = new BlobClient(connectionString, "test", "test");
client2.Upload(Stream.Null, overwrite: true);
```

In contrast, this Python code will use a new HTTP connection for each upload:

```python
client1 = BlobClient.from_connection_string(connection_string, "test", "test")
client1.upload_blob([], overwrite=True)

client2 = BlobClient.from_connection_string(connection_string, "test", "test")
client2.upload_blob([], overwrite=True)
```

It's possible to reuse the connection in Python by passing a shared session, but I think this should be the default behavior:

```python
session = requests.session()

client3 = BlobClient.from_connection_string(connection_string, "test", "test", session=session)
client3.upload_blob([], overwrite=True)

client4 = BlobClient.from_connection_string(connection_string, "test", "test", session=session)
client4.upload_blob([], overwrite=True)
```

To repro, run the apps at https://github.com/mikeharder/azure-sdk-http-sharing and use a tool like Wireshark to monitor the HTTP connections.

Another issue is that the `session` parameter is not included in the [API docs](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python), but I believe this is covered by #12122.

CC: @johanste, @lmazuel

**Comment by tasherif-msft** [comment]
Hey @mikeharder! currently a session object is shared when we instantiate a parent client - for example a BlobServiceClient as a singleton - and create instances of BlobClients, ContainerClients, etc. This happens by simply passing that session when initiating the children clients.
We could definitely improve our documentation by letting the user know that they can share a session object between independently created client objects (like the example you illustrated above)

However, I can't think of a way to have this done by default (under the hood) where one session object persists for a given python process so its used by any client created in that process (I assume this is what you meant by default behavior?)

In .NET this is done by default? or like Python, users have to explicitly pass that session object?

Thank you :)

**Comment by tasherif-msft** [comment]
Hey @mikeharder! currently a session object is shared when we instantiate a parent client - for example a BlobServiceClient as a singleton - and create instances of BlobClients, ContainerClients, etc. This happens by simply passing that session when initiating the children clients.
We could definitely improve our documentation by letting the user know that they can share a session object between independently created client objects (like the example you illustrated above)

However, I can't think of a way to have this done by default (under the hood) where one session object persists for a given python process so its used by any client created in that process (I assume this is what you meant by default behavior?)

And on a finer grain, I don't believe there is a way to share a connection pool between different sessions, referring to https://requests.readthedocs.io/en/master/user/advanced/#keep-alive it states "thanks to urllib3, keep-alive is 100% automatic within a session! Any requests that you make within a session will automatically reuse the appropriate connection!". 
So a connection pool keyed by (hostname, port) pair is maintained within a session. 

In .NET this is done by default? or like Python, users have to explicitly pass that session object?
Let me know! I'm still getting the hang of core and underlying architecture.

Thank you :)

**Comment by mikeharder** [comment]
@tasherif-msft: I believe .NET, Java, and JS all share a single "session" by default (where "session" here is a vague term meaning the clients re-use the same HTTP connection when possible).  You can compare the .NET and Python sample apps here:

https://github.com/mikeharder/azure-sdk-http-sharing

In Python, I think this could be implemented with a shared static "default session" used if none is passed in.

**Comment by lmazuel** [comment]
For closure on this thread, current recommendation is to pass a custom transport (not a custom session):

```python
from azure.core.pipeline.transport import RequestsTransport
transport = RequestsTransport()

client3 = BlobClient.from_connection_string(connection_string, "test", "test", transport=transport)
client3.upload_blob([], overwrite=True)

client4 = BlobClient.from_connection_string(connection_string, "test", "test", transport=transport)
client4.upload_blob([], overwrite=True)
```
