### ISSUE TITLE
How to create a VM from a managed os disk

### ISSUE THREAD

**Issue by songyangeric** [Azure/azure-sdk-for-python#1380]
I try to create a VM from a custom vhd and use managed disks. I convert the vhd to a managed disk and then create the os_disk profile.
```
disk_name = '{}-osDisk'.format(vmname)    
 async_create = self.compute_client.disks.create_or_update(    
         resource_group, disk_name,    
         {     
               'location': location,    
               'creation_data': {    
                     'create_option': DiskCreateOption.import_enum,     
                     'source_uri': image    
               }     
         })    
manage_disk_ref = async_create.result()    
os_disk_ref = OSDisk(create_option = 'attach', name = disk_name, os_type = 'Linux', managed_disk = ManagedDiskParameters(id = manage_disk_ref.id))    
```
But when I try to use this managed os disk to create a VM, an error occurs:
```
Failed to create vm.    
Azure Error: InvalidParameter     
Message: Parameter 'osProfile' is not allowed.    
Target: osProfile    
```
If I remove the os_profile, I can successfully create a VM. But I cannot set up the adminUser/adminPassword. Anyone has encoutered this issue or has anyone created a VM using custom managed disk?

**Comment by lmazuel** [comment]
Hi @songyangeric 

`attach` and `osProfile` can't be used together, since you're supposed to attach a disk which is ready (i.e. already configured). Disk must e syspred/generalized first. This answer might help:
https://stackoverflow.com/a/44954857/4074838

This documentation might also help if you didn't have it (even not directly an answer to your question)
https://docs.microsoft.com/python/azure/python-sdk-azure-samples-managed-disks

**Comment by songyangeric** [comment]
@lmazuel Thanks for your comment. I am using a generalized vhd. I now convert the vhd to a managed image instead of a disk according to your link and it works. The osProfile now can coexist. The modified part is listed below:
```
image_name = '{}-osImage'.format(vmname)
async_create = self.compute_client.images.create_or_update(
        resource_group, image_name,
        {
                'location': location,
                'storage_profile': {
                     'os_disk': {
                            'os_type': 'Linux',
                            'os_state': "Generalized",
                            'blob_uri': image,
                            'caching': "ReadWrite",
                     }
                 }
 })
managed_image_ref = async_create.result()
image_reference = ImageReference(id = managed_image_ref.id)
storage_profile = StorageProfile(image_reference = image_reference)
```

**Comment by lmazuel** [comment]
Thanks @songyangeric for the code and update!

I will make sure this goes to the documentation and keep this open until then.

**Comment by Petermarcu** [comment]
@lmazuel, can this be closed now? Had the doc been updated?

**Comment by lmazuel** [comment]
@Petermarcu nope, I realize it was not done, I took the opportunity of your comment to do it myself :):
https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/496

**Comment by lmazuel** [comment]
Doc PR has been merged, will be online in a moment. Thanks!
