### ISSUE TITLE
[Core] Support results_per_page in the by_page iterator

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#13819]
Currently the `ItemPaged.by_page()` function only takes a continuation_token.
We should also allow specifying the page size.
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/paging.py#L98

Not all services will support setting a page size (just as not all services support a continuation token). So in order to prevent breaking any existing implementations that don't support the extra kwarg, this could be done simply by adding `**kwargs` to the `by_page` function:
```python
def by_page(self, continuation_token=None, **kwargs):
    # type: (Optional[str]) -> Iterator[Iterator[ReturnType]]
    """Get an iterator of pages of objects, instead of an iterator of objects.
    :param str continuation_token:
        An opaque continuation token. This value can be retrieved from the
        continuation_token field of a previous generator object. If specified,
        this generator will begin returning results from this point.
    :keyword int results_per_page: The maximum number of items to return in
        a single page.
    :returns: An iterator of pages (themselves iterator of objects)
    """
    self._kwargs.update(kwargs)
    return self._page_iterator_class(
        continuation_token=continuation_token, *self._args, **self._kwargs
    )
```

**Comment by lmazuel** [comment]
@annatisch to me it's the role of the `list` call to do that:

````python
result = client.list(top=5) 
for page in result.by_page():
   for elt in page:
       do_something(elt)
```

Thoughts? @annatisch @johanste

**Comment by iscai-msft** [comment]
hey @annatisch @johanste @lmazuel , reinvigorating this thread. Text Analyticss is running into a similar issue as MA. To me, top of 5 would mean "just return the top 5 results". However, some service teams (i.e. MA) are takign `top` to mean paging size. I believe this discrepancy is the reason for this issue being open, and I beleive both @johanste and @annatisch recommended it be on `by_page`. I also believe there were talks to have the param on `by_page` be something like `page_size`

**Comment by kristapratico** [comment]
@johanste @iscai-msft in v6.0.0 of autorest we stopped generating with the `maxpagesize` keyword argument. IIRC we were relying on it's ability to be passed into the `by_page`, but it doesn't look like this got implemented yet. Should we prioritize this?

**Comment by johanste** [comment]
Unless we have customer feedback, I wouldn't prioritize this too high. Given that the `maxpagesize` parameter *generally* is aspirational (i.e. the service only guarantees that it returns at most `maxpagesize` items, not that it will actually return `maxpagesize` items), it ends up not being used too frequently.

**Comment by kristapratico** [comment]
Got it, sounds good. I don't think I've heard any customer feedback on this, just came across it and thought I'd check.
