### ISSUE TITLE
resclient = get_client_from_auth_file(ResourceManagementClient) fails in version 15.0.0 of azure-mgmt-resource in Ubuntu

### ISSUE THREAD

**Issue by gbrault** [Azure/azure-sdk-for-python#13874]
- **azure-mgmt-resource**: 
- **15.0.0**: 
- **Ubuntu 20.4**:
- **3.8.2**: 

**resclient = get_client_from_auth_file(ResourceManagementClient) fails**
In version 10.2.0 I had no issue login to azure from my local linux machine, with a json file
with 15.0.0 it fails

**Comment by nickzhums** [comment]
Hi @gbrault , there has been a major upgrade for Python SDK management libraries. In the new version of SDK, the authentication mechanism has been changed, please refer to this changelog:
[changelog](https://pypi.org/project/azure-mgmt-resource/15.0.0/)

There is also migration guide here for [update instructions](https://azure.github.io/azure-sdk-for-python/python_mgmt_migration_guide.html)

The new version of SDK offers a number of new features but also introduces some breaking changes. Detailed info and documentation can be found [here](http://aka.ms/azsdk/python/mgmt)

However, if you wish to stay on the old version, please keep using 10.2.0.

**Comment by gbrault** [comment]
@nickzhums thanks for the answer. I will stick with 10.2.0 for the moment as this is not critical for my project. I will upgrade when the ACI documentation is going to be updated. I am using the ACI (azure containers instances) and I followed the documentation associated to manage containers creation and life cycle. Maybe their are going to be some changes there as well. Thanks again. This helps a lot! (I have spent a 1/2 day to find where it was coming from when I suddenly found the suspect...)

**Comment by nickzhums** [comment]
@gbrault You're welcome :) We are also collecting feedback from current Python management library users, if you have time, we would really appreciate any form of feedback using the Python SDK. For example:
- What are your use case scenarios? (why are you using the SDK?)
- How is the developer experience so far? (API design and documentation)

Thanks!

**Comment by gbrault** [comment]
@nickzhums 

- Use case:
   - Domain specific modeling is communicated to people through notebooks
   - People buy those notebooks and the associated workload as domain experts, no IT expert
   - Notebooks run on a set of pre-built container images which are tested and validated
   - The platform insure (process and pre-test) the notebook is going to work (no IT glitch)
   - Time from intent to use a notebook to actually work with it is important ( I get ~4 minutes now which is 'OK')
   - Need to manage the life-cycle of those workloads and use ACI for that
   - Users are not IT savvy but are domain experts
   - We sale domain expertise, not IT, not containers, not Kubernetes. But we use them! And want to forget about it!
   - Its domain expertise as a service (DEAAS)
   - Workload are self monitored and if not used, they terminate themselves
   - Workload are prepaid: its a kind of pay per use, but pre-paid
   - Workload are metered (people buy units that are deducted from when using the service)
   - We don't want to be trapped with the IT service provider
   - Scalability is very important, geography as well
- Developer Experience
   - A bit lost among this huge Azure stack... You can imagine!
   - As this issue case shows: the documentation is not always in sync... (must be hard I imagine!)
   - Quite happy about simplicity of ACI API which basically stick with Docker concepts
   - ACI seems robust so far
   - Selected ACI because it is the best one at this time
       - For example, Google don't support WebSocket.
       - AWS is to difficult to 'enter', I have always been lost with them!
       - Others offer Kubernetes which is not what we need at the development phase we are
       - I only found Scaleway which propose a similar service in Beta, but seems not really operational yet
   - Scared Microsoft would stop the ACI service

**Comment by nickzhums** [comment]
@gbrault Thanks for your info and greatly appreciate it. Just wanted to double check, by "notebook", did you mean a virtual notebook? or actually real hardware? and are you guys using the Python SDK (e.g. containerinstances) to manage those images?

**Comment by gbrault** [comment]
@nickzhums

sorry for the confusion about notebook: it's a virtual notebook, which in fact is a Jupyter Notebook (but we use some extension to 'show' the notebook in a 'run time' manner and the user interact just with the provided interface (no programming). It's up to the notebook author to select which interface he wants to provide to people.

We use the AZURE python SDK to manage the life cycle of containers within ACI: 
- container group creation, deletion
- monitoring container status

For images, we are using right now Docker Hub, including the capability to build the image, the notebook layer is added to the image via git when the container is instantiated. Containers are run once type. 

Any registry compatible with ACI and offering the same service would fly.

**Comment by nickzhums** [comment]
@gbrault thanks for the great info! cc @yonzhan  @jsntcy @changlong-liu , do you guys know about performance of Container Registry vs Container Instance?

**Comment by yonzhan** [comment]
@yugangw-msft may help with performance question.

**Comment by gbrault** [comment]
I made the test with an Azure registry located in the same resource and there is no increase of performance compared to using Docker hub.
