### ISSUE TITLE
signed_session error when using log analytics package

### ISSUE THREAD

**Issue by m-dorfman** [Azure/azure-sdk-for-python#13891]
- **Package Name**: azure-loganalytics==0.1.0
- **Operating System**: ubunutu 20.04
- **Python Version**: 3.8

proper environment variable have been set as per instructions for local testing. 
```
AZURE_SUBSCRIPTION_ID="aa11bb33-cc77-dd88-ee99-0918273645aa"
AZURE_TENANT_ID=00112233-7777-8888-9999-aabbccddeeff
AZURE_CLIENT_ID=12345678-1111-2222-3333-1234567890ab
AZURE_CLIENT_SECRET=abcdef00-4444-5555-6666-1234567890ab
```
using the following script:
```
from azure.identity import DefaultAzureCredential
import azure.loganalytics as law

credential = DefaultAzureCredential()
query = law.models.QueryBody(query="Heartbeat | partition by Computer (top 1 by TimeGenerated desc nulls last)")
law_client = law.log_analytics_data_client.LogAnalyticsDataClient(credentials=credential)
query_out = law_client.query(workspace_id="<manually set workspace id>", body=query, raw=True)
```

running this outputs the following:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/work/azfun/.venv/lib/python3.8/site-packages/azure/loganalytics/log_analytics_data_client.py", line 116, in query
    response = self._client.send(
  File "/home/user/work/azfun/.venv/lib/python3.8/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/home/user/work/azfun/.venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/user/work/azfun/.venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/user/work/azfun/.venv/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'

I think my implementation is correct but apologies if this isn't actually a bug and I'm doing something incorrectly.

**Comment by bateau84** [comment]
I get this same error, but with other azure modules

**Comment by m-dorfman** [comment]
the signed session issue seems to have come up in a few of the azure sdk packages and was repaired. it looks like the sdk as a whole or the specific packages were not properly updated in the most recent version.

**Comment by shemers** [comment]
Hi @m-dorfman we have released a new version of the SDK https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01

Can you please check and confirm that this has resolved your issue?

**Comment by AzmonLogA** [comment]
Adding @Yoram Singer<mailto:yorams@microsoft.com> to have a look.
