### ISSUE TITLE
Unable to authenticate to Azure ML Workspace using ClientSecretCredential 

### ISSUE THREAD

**Issue by gison93** [Azure/azure-sdk-for-python#13905]
- **Package Name**: azureml-core
- **Package Version**: 1.13.0.post1
- **Operating System**: Windows 10.0.18363
- **Python Version**: 3.6.2

**Describe the bug**
Unable to authenticate to Azure ML Workspace using ClientSecretCredential.
I get the following error:
AttributeError: 'ClientSecretCredential' object has no attribute '_get_workspace'

**To Reproduce**
1. pip install azureml-core==1.13.0.post1 azure-identity==1.4.0
2. run the following
```python
from azureml.core import Workspace
from azure.identity import ClientSecretCredential

tenant = "tenant"
client = "client"
key = "key"

credentials = ClientSecretCredential(
            tenant_id=tenant,
            service_principal_id=client,
            service_principal_password=key)

workspace = Workspace.from_config("config.json", auth=credentials)
```

**Expected behavior**
To be able of attaching to the Workspace using ClientSecretCredential.

**Comment by rastala** [comment]
Hi @gison93 ! The azure.identity.ClientSecretCredential cannot be directly used when authenticating to workspace. Instead, use wrappers from [azureml.core.authentication](https://docs.microsoft.com/python/api/azureml-core/azureml.core.authentication?view=azure-ml-py) module

For an example of authentication using service principal client secret, see:
https://docs.microsoft.com/azure/machine-learning/how-to-setup-authentication#use-a-service-principal-from-the-sdk

#please-close

**Comment by gison93** [comment]
Hi @rastala! I was trying to use ClientSecretCredential because of this issuehttps://github.com/Azure/azure-sdk-for-python/issues/13871.
Installing the next versions of the sdk (for sure with azureml-core==1.18.0) solves the issue and ServicePrincipalClient can be used.
