### ISSUE TITLE
No error when creating NIC tied to VNet in different resource group

### ISSUE THREAD

**Issue by inhifistereo** [Azure/azure-sdk-for-python#1390]
I'm attempting to create a NIC in the "VMs" resource group tied to vnet1 in the "VNets" resource group. I'm using the following CLI statement:

`az network nic create -g vms --vnet-name vnet1 --subnet default -n MyNic4`

I retrieve the following once the CLI runs:

`{}`

Further, no NIC is created in Azure.

When I create the NIC in the "VNets" resource group the NIC is successfully created. Is this desired behavior?

**Comment by lmazuel** [comment]
Hi @inhifistereo 
This needs to be tracked in the CLI issue tracker:
https://github.com/Azure/azure-cli/issues

However, this is an interesting SDK question, that I can ask to the RestAPI team (we're not responsible to decide when the RestAPI should accept, refuse or do an error).

Thanks!

FYI @tjprescott

**Comment by inhifistereo** [comment]
My bad. I'll close here and open issue in CLI.
