### ISSUE TITLE
No flag to set overwrite=True in Dataset

### ISSUE THREAD

**Issue by kwhitehall** [Azure/azure-sdk-for-python#13913]
- **azureml-core, azureml-dataprep**: 
- **1.12.0, 2.0.7**: 
- **Operating System**:
- **Python Version = 3.7**: 

**Describe the bug**
No flag to set overwrite=True in as_download method. 
Output from failed method:
Dataset initialization failed: UserErrorException:
    Message: File "/mnt/location/dataset.json" already exists. Set overwrite=True to overwrite it.
    InnerException None
    ErrorResponse
{
    "error": {
        "code": "UserError",
        "message": "File \"/mnt/location/dataset.json\" already exists. Set overwrite=True to overwrite it."
    }
}

**To Reproduce**
1. registered_dataset = Dataset.get_by_name(workspace=ws, name=kwargs['dataset_name'])
    dataset_as_named_input = registered_dataset.as_named_input(name=kwargs['dataset_name'])
    input_dataset = dataset_as_named_input.as_download(path_on_compute='./outputs/data')
2. run python code (using Pytorch 1.4) on AMLCompute cluster Standard_NC12 that accesses input_dataset (from datalake store)

**Expected behavior**
Based on error message, expected that as_download method would have a flag to set overwrite as suggested by the error log.

**Screenshots**

**Additional context**

**Comment by meyetman** [comment]
Hi @kwhitehall, we have entered this as a feature request! Thanks!
#please-close

**Comment by j0rd1smit** [comment]
What is the status of this? I'm running into the same problem
