### ISSUE TITLE
Error validating/creating Storage Account

### ISSUE THREAD

**Issue by tomarv2** [Azure/azure-sdk-for-python#13943]
- **Package Name**: 
- **Package Version**: 
- **Operating System**: MacOS
- **Python Version**: 3.6

**Describe the bug**

Following this doc to validate and create a storage account and its erroring out:

https://docs.microsoft.com/en-us/samples/azure-samples/storage-python-manage/storage-python-manage/#create-account

Error:

```

error:
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

**Comment by amishra-dev** [comment]
@vinjiang can you please help with this, its a management plane sdk ask.

**Comment by msyyc** [comment]
please reference : 
(1)https://github.com/Azure-Samples/azure-samples-python-management/tree/master/samples/network
or
(2) https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/network/azure-mgmt-network/tests
