### ISSUE TITLE
os.environ causes azure-eventhub send_stream.py to fail

### ISSUE THREAD

**Issue by abdale** [Azure/azure-sdk-for-python#13951]
- **Package Name**: azure-eventhub
- **Package Version**: 5.2.0
- **Operating System**: Windows 10
- **Python Version**: 3.8.5

**Describe the bug**

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/sync_samples/send_stream.py

This script keeps erroring out unless you **remove** the [os.environ](https://github.com/Azure/azure-sdk-for-python/blob/7eda38a794db787babec3c0a3bf595148cb73991/sdk/eventhub/azure-eventhub/samples/sync_samples/send_stream.py#L19).

**Comment by KieranBrantnerMagee** [comment]
Hey abdale; thanks for reaching out.  I'll need a little more detail on the failure you're seeing; as I attempted to reproduce sight unseen but for me the script runs properly.  If you give a full breakdown of the issue and error I might be able to give better guidance.

If helpful, what I did: (where you'll need to provide the values for the two env vars yourself)
- `$env:EVENT_HUB_NAME='my-test-eventhub-instance`
- `$env:EVENT_HUB_CONN_STR='Endpoint=sb://my-test-eventhub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=REDACTED`
- `pip install azure-eventhub`
- `python .\send_stream.py`
(to which I got the following output)
- `Send messages in 3.617811679840088 seconds.`

I would mention both of those os.environ variables are needed to authenticate this sample, and should be obtained from the  azure portal for the eventhub instance you wish to run the sample against; for more detail on this see our readme [here.](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhub#authenticate-the-client)
