### ISSUE TITLE
Event Grid Readme and Samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#13978]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventgrid/azure-eventgrid#install-the-package):
![image](https://user-images.githubusercontent.com/57166602/93975856-a4d65900-fdaa-11ea-9fcd-467ef2814068.png)

Suggestion:
Add hyperlink for `pip` https://pypi.org/project/pip/

2.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventgrid/azure-eventgrid#prerequisites):
![image](https://user-images.githubusercontent.com/57166602/93975942-ce8f8000-fdaa-11ea-9e88-c7bdfe08fbe8.png)

Suggestions:
Add CLI command about to create Event Grid. As shown in the picture below:
![image](https://user-images.githubusercontent.com/57166602/93975977-dd763280-fdaa-11ea-8dc2-00acb82f8604.png)

3.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventgrid/azure-eventgrid#examples):
![image](https://user-images.githubusercontent.com/57166602/93976044-f252c600-fdaa-11ea-9143-94a915fe7d0f.png)

Suggestion:
Neither of these two places can jump correctly.
1).Update to `send-an-event-grid-event`.
2).Update to `consume-an-event-grid-event`.

4.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventgrid/azure-eventgrid#consume-an-event-grid-event):
![image](https://user-images.githubusercontent.com/57166602/93976182-28904580-fdab-11ea-904c-ed8cbda39176.png)

Reason 1: AttributeError: 'EventGridEvent' object has no attribute 'time'.
Suggestion 1: Update to `event_time'.

Reason 2: TypeError: 'CloudEvent' object is not subscriptable.
Suggestion 2: Delete this code snippet.

5.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventgrid/azure-eventgrid#consume-a-cloud-event):
![image](https://user-images.githubusercontent.com/57166602/93976354-73aa5880-fdab-11ea-8a81-11175f9b864e.png)

Reason:
TypeError: 'CloudEvent' object is not subscriptable.

Suggestion:
Delete this code snippet.

6.
Section [Link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs1_publish_custom_events_to_a_topic.py#L18):
![image](https://user-images.githubusercontent.com/57166602/93976445-9472ae00-fdab-11ea-8f0a-38f4e95c11bc.png)

Suggestion:
Remove `CloudEvent`, this sample does not use it.

7.
Section [Link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs1b_publish_custom_events_to_a_topic_with_signature.py#L23):
![image](https://user-images.githubusercontent.com/57166602/93977110-97ba6980-fdac-11ea-9735-1d184e01fc41.png)

Suggestion:
1).Remove `CloudEvent`, this sample does not use it.
2).Update to:
```
from datetime import datetime, timedelta
expiration_date_utc = datetime.utcnow() + timedelta(hours=1)
```
8.
Section [Link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_with_shared_access_signature_sample.py#L30):
![image](https://user-images.githubusercontent.com/57166602/93977516-3050e980-fdad-11ea-808c-61643b7e70d1.png)

Reason:
ModuleNotFoundError: No module named 'dateutil'

Suggestion:
Delete the code marked in red and update to:
```
from datetime import datetime, timedelta
expiration_date_utc = datetime.utcnow() + timedelta(hours=1)
```

9. 
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs3_consume_system_events.py), [link2](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs4_consume_custom_events.py), [link3](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs6_consume_events_using_cloud_events_1.0_schema.py#L19):
![image](https://user-images.githubusercontent.com/57166602/93977432-0f889400-fdad-11ea-8703-869d08186497.png)

Reason:
1). NameError: name 'service_bus_received_message' is not defined.
2). TypeError: 'EventGridEvent' object is not iterable.

@jongio for notification.

**Comment by rakshith91** [comment]
Thanks for reporting!
Fixed here https://github.com/Azure/azure-sdk-for-python/pull/14128
