### ISSUE TITLE
App Configuration Readme and Samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#13975]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/appconfiguration/azure-appconfiguration#contributing):
![image](https://user-images.githubusercontent.com/57166602/93972988-0647f900-fda6-11ea-80cf-f977c02a352d.png)
Suggestion:
1).Add hyperlink for `Microsoft Open Source Code of Conduct` https://opensource.microsoft.com/codeofconduct/
2).Add hyperlink for `Code of Conduct FAQ` https://opensource.microsoft.com/codeofconduct/faq/

2.
Section [Link1](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/appconfiguration/azure-appconfiguration/samples/list_revision_sample.py#L37), [link2](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/appconfiguration/azure-appconfiguration/samples/list_revision_async_sample.py#L39):
![image](https://user-images.githubusercontent.com/57166602/93973102-398a8800-fda6-11ea-9523-96c21939e5ee.png)

Reason:
TypeError: request() got an unexpected keyword argument 'keys'.

Suggestion:
Update to: ` items = client.list_revisions(key_filter="MyKey")`

@jongio for notification.

**Comment by xiangyan99** [comment]
Fixed
