### ISSUE TITLE
Search Documents Sample issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#13976]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/search/azure-search-documents/samples/async_samples/sample_indexers_operations_async.py#L57):
![image](https://user-images.githubusercontent.com/57166602/93973643-1dd3b180-fda7-11ea-9ea5-0c3eb4180900.png)

Suggestion:
Update to `async-indexer-datasource`，make it consistent with the data source name below.

@jongio for notification.

**Comment by xiangyan99** [comment]
Fixed
