### ISSUE TITLE
Upload to IoT Edge Blob Storage: ExceptionMessage:The value 2019-12-12 provided for request header x-ms-version is invalid.

### ISSUE THREAD

**Issue by OrrinEdenfield** [Azure/azure-sdk-for-python#13985]
- **Package Name**:  Azure Blob storage v12.5.0
- **Package Version**: 12.5.0
- **Operating System**: 
  PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
  NAME="Raspbian GNU/Linux"
  VERSION_ID="10"
  VERSION="10 (buster)"
  VERSION_CODENAME=buster
  ID=raspbian
  ID_LIKE=debian
  HOME_URL="http://www.raspbian.org/"
  SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
  BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- **Python Version**: Python 3.7.3 (default, Jul 25 2020, 13:03:44)

**Describe the bug**
I'm trying to use Azure Python SDK to upload a file from a Raspberry Pi Zero to another IoT device running Azure IoT Edge Blob Storage module. I'm able to interact with the module by uploading/downloading files via Storage Explorer so I believe that is working as expected. However, I'm unable to use Azure SDK for Python to upload file to Blob storage service running on IoT Edge.

Error I'm seeing is:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 106, in upload_block_blob
    **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 222, in upload
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The value for one of the HTTP headers is not in the correct format.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "localblob.py", line 15, in <module>
    blob.upload_blob(data)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 539, in upload_blob
    return upload_block_blob(**options)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 156, in upload_block_blob
    process_storage_error(error)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: The value for one of the HTTP headers is not in the correct format.
RequestId:b0deb939-b93e-4d5a-a075-2ed4a22ec3aa
Time:2020-09-23T14:25:22.8346188Z
ErrorCode:InvalidHeaderValue
Error:None
HeaderName:x-ms-version
HeaderValue:2019-12-12
ExceptionDetails:None
ExceptionMessage:The value 2019-12-12 provided for request header x-ms-version is invalid.
StackTrace:Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.InvalidHeaderProtocolException: The value 2019-12-12 provided for request header x-ms-version is invalid.
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.RunVersionCheck() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 788
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 1537

**To Reproduce**
1. Create IoT Edge device (I'm using a Raspberry PI 3 running Raspbian Buster for this) running Azure Blob Storage on IoT Edge (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob)
2. On another local-network device use Azure SDK for Python (I'm using Raspberry Pi Zero W for this) to connect to the Blob service running on the IoT Edge device. 
3. This is the python code I'm using (Python 3.7.3 running on Pi Zero) to connect to the IoT Edge Blob Service:

    import os, uuid
    from azure.storage.blob import BlobClient

    # Connection string to the local Blob service
    connection_string = "DefaultEndpointsProtocol=http;BlobEndpoint=http://192.168.0.12:11002/localblob;AccountName=localblob;AccountKey=[KEY]"

    local_path = "./"
    local_file_name = "pizerocam.txt"
    upload_file_path = os.path.join(local_path, local_file_name)
    localcontainer = "pisynccontainer"

    blob = BlobClient.from_connection_string(conn_str=connection_string, container_name=localcontainer, blob_name=local_file_name)

    with open(upload_file_path, "rb") as data:
        blob.upload_blob(data)

**Expected behavior**
I expect the file pizerocam.txt to be uploaded to the blob container on the Blob Service running on IoT Edge

**Screenshots**
https://gamgee.blob.core.windows.net/public/localBlobPythonError.png

**Additional context**
I have verified that the local Blob service is working as I've connected to it with the exact same connection string using Azure Storage Explorer. I'm just having an issue getting the Python SDK to connect using this same connection string.

**Comment by OrrinEdenfield** [comment]
HI @tasherif-msft I may be doing something wrong, feel free to ping me if that is the case. Thank you!

**Comment by xiafu-msft** [comment]
Hi @OrrinEdenfield 
Based on the doc https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob#supported-storage-operations
it seems only service version `2017-04-17` is supported if I understand properly, please double check and correct me if I'm wrong.
Currently azure-storage-blob 12.5.0 takes 2017-04-17 as an invalid version, we can provide you a .whl file and you can install that, so you can specify api_version='2017-04-17' and use LoT, sorry about the inconvenience!

**Comment by OrrinEdenfield** [comment]
@xiafu-msft sure. I'll give that a try if you can point me in the right direction. Thank you!

**Comment by xiafu-msft** [comment]
Thanks for your patience! 
You need do:
1. unzip this first
2. do `pip install your/path/azure_storage_blob-12.5.0-py2.py3-none-any.whl
`
[azure_storage_blob-12.5.0-py2.py3-none-any.zip](https://github.com/Azure/azure-sdk-for-python/files/5284987/azure_storage_blob-12.5.0-py2.py3-none-any.zip)

**Comment by maecky** [comment]
@xiafu-msft is this python package a different version than the one from pypi: https://pypi.org/project/azure-storage-blob/#history

If so, could you please update the pypi version?

**Comment by keecm** [comment]
i was having the same error with python.
Added api_version='2019-07-07' to BlobServiceClient solved the problem.

**Comment by OrrinEdenfield** [comment]
Hi @xiafu-msft - I followed step1-3 here and when I run my code (updated line below), I'm now recieving an error on the API version number.

**Updated line calling BlobClient:**
`blob = BlobClient.from_connection_string(conn_str=connection_string, container_name=localcontainer, blob_name=local_file_name, api_version='2017-04-17')`

**New error:**
`pi@pizerowcam:~/gardencam $ python3 localblob.py
Traceback (most recent call last):
  File "localblob.py", line 12, in <module>
    blob = BlobClient.from_connection_string(conn_str=connection_string, container_name=localcontainer, blob_name=local_file_name, api_version='2017-04-17')
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 303, in from_connection_string
    snapshot=snapshot, credential=credential, **kwargs
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 168, in __init__
    self._client._config.version = get_api_version(kwargs, VERSION)  # pylint: disable=protected-access
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_serialize.py", line 129, in get_api_version
    raise ValueError("Unsupported API version '{}'. Please select from:\n{}".format(api_version, versions))
ValueError: Unsupported API version '2017-04-17'. Please select from:
2019-02-02
2019-07-07
2019-10-10
2019-12-12`

**Comment by OrrinEdenfield** [comment]
@keecm After updating with the whl file provided by @xiafu-msft I tried setting api_version='2019-07-07' per your suggestion (2019-07-07 does seem to be one of the supported api versions per the previous error). When I run this, I'm receiving the exception below that looks to be auth related? Maybe this is caused by the ? character in my account key? If I properly escape the connection string?

`pi@pizerowcam:~/gardencam $ python3 localblob.py
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 106, in upload_block_blob
    **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 222, in upload
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "localblob.py", line 15, in <module>
    blob.upload_blob(data)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 539, in upload_blob
    return upload_block_blob(**options)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 156, in upload_block_blob
    process_storage_error(error)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:48c7cacd-7849-420a-99d4-7de42ef82086
Time:2020-09-28T10:21:52.3346186Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT


77

application/octet-stream



*


x-ms-blob-type:BlockBlob
x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
x-ms-version:2019-07-07
/localblob/localblob/pisynccontainer/pizerocam.txt'.
ExceptionDetails:None
ExceptionMessage:The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT


77

application/octet-stream



*


x-ms-blob-type:BlockBlob
x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
x-ms-version:2019-07-07
/localblob/localblob/pisynccontainer/pizerocam.txt'.
StackTrace:Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException: The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT


77

application/octet-stream



*


x-ms-blob-type:BlockBlob
x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
x-ms-version:2019-07-07
/localblob/localblob/pisynccontainer/pizerocam.txt'. ---> Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException: The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT


77


application/octet-stream



*


x-ms-blob-type:BlockBlob
x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
x-ms-version:2019-07-07
/localblob/localblob/pisynccontainer/pizerocam.txt'. ---> Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException: The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT


77

application/octet-stream



*


x-ms-blob-type:BlockBlob
x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
x-ms-version:2019-07-07
/localblob/localblob/pisynccontainer/pizerocam.txt'.
   at Microsoft.Cis.Services.Nephos.Common.Authentication.NephosAuthenticationManager.SharedKeyAuthenticate(String stringToSign, String requestSignature, AuthenticationInformation authInfo) in F:\Storage-XStore\src\XFE\common\src\Authentication\NephosAuthenticationManager.cs:line 1359
   at Microsoft.Cis.Services.Nephos.Common.Authentication.NephosAuthenticationManager.AuthenticateImpl(IStorageAccount storageAccount, RequestContext requestContext, NephosUriComponents uriComponents, GetStringToSignCallback getStringToSignCallback, TimeSpan timeout, AsyncIteratorContext`1 context)+MoveNext() in F:\Storage-XStore\src\XFE\common\src\Authentication\NephosAuthenticationManager.cs:line 689
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin) in F:\Storage-XStore\src\XFE\external\AsyncHelper\src\AsyncIteratorContextBase.cs:line 105
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Authentication.NephosAuthenticationManager.EndAuthenticate(IAsyncResult asyncResult) in F:\Storage-XStore\src\XFE\common\src\Authentication\NephosAuthenticationManager.cs:line 452
   at Microsoft.Cis.Services.Nephos.Common.Authentication.XFEBlobAuthenticationManager.AuthenticateImpl(IStorageAccount storageAccount, RequestContext requestContext, NephosUriComponents uriComponents, GetStringToSignCallback getStringToSignCallback, TimeSpan timeout, AsyncIteratorContext`1 context)+MoveNext() in F:\Storage-XStore\src\XFE\common\src\Authentication\XFEBlobAuthenticationManager.cs:line 251
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin) in F:\Storage-XStore\src\XFE\external\AsyncHelper\src\AsyncIteratorContextBase.cs:line 105
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Authentication.XFEBlobAuthenticationManager.EndAuthenticate(IAsyncResult asyncResult) in F:\Storage-XStore\src\XFE\common\src\Authentication\XFEBlobAuthenticationManager.cs:line 155
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 2689`

**Comment by keecm** [comment]
> @keecm After updating with the whl file provided by @xiafu-msft I tried setting api_version='2019-07-07' per your suggestion (2019-07-07 does seem to be one of the supported api versions per the previous error). When I run this, I'm receiving the exception below that looks to be auth related? Maybe this is caused by the ? character in my account key? If I properly escape the connection string?
> 
> `pi@pizerowcam:~/gardencam $ python3 localblob.py
> Traceback (most recent call last):
> File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 106, in upload_block_blob
> **kwargs)
> File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 222, in upload
> raise models.StorageErrorException(response, self._deserialize)
> azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "localblob.py", line 15, in
> blob.upload_blob(data)
> File "/home/pi/.local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
> return func(*args, **kwargs)
> File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 539, in upload_blob
> return upload_block_blob(**options)
> File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 156, in upload_block_blob
> process_storage_error(error)
> File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
> raise error
> azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> RequestId:48c7cacd-7849-420a-99d4-7de42ef82086
> Time:2020-09-28T10:21:52.3346186Z
> ErrorCode:AuthenticationFailed
> Error:None
> AuthenticationErrorDetail:The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT
> 
> 77
> 
> application/octet-stream
> 
> 
> x-ms-blob-type:BlockBlob
> x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
> x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
> x-ms-version:2019-07-07
> /localblob/localblob/pisynccontainer/pizerocam.txt'.
> ExceptionDetails:None
> ExceptionMessage:The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT
> 
> 77
> 
> application/octet-stream
> 
> 
> x-ms-blob-type:BlockBlob
> x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
> x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
> x-ms-version:2019-07-07
> /localblob/localblob/pisynccontainer/pizerocam.txt'.
> StackTrace:Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException: The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT
> 
> 77
> 
> application/octet-stream
> 
> 
> x-ms-blob-type:BlockBlob
> x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
> x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
> x-ms-version:2019-07-07
> /localblob/localblob/pisynccontainer/pizerocam.txt'. ---> Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException: The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT
> 
> 77
> 
> application/octet-stream
> 
> 
> x-ms-blob-type:BlockBlob
> x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
> x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
> x-ms-version:2019-07-07
> /localblob/localblob/pisynccontainer/pizerocam.txt'. ---> Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException: The MAC signature found in the HTTP request 'lYDeQhC+2QeISWkh/0fEZrpSs0mrPIr3T6paw2bOBHQ=' is not the same as any computed signature. Server used following string to sign: 'PUT
> 
> 77
> 
> application/octet-stream
> 
> 
> x-ms-blob-type:BlockBlob
> x-ms-client-request-id:6d0176ae-0174-11eb-9fcd-b827eb0b8a99
> x-ms-date:Mon, 28 Sep 2020 10:21:52 GMT
> x-ms-version:2019-07-07
> /localblob/localblob/pisynccontainer/pizerocam.txt'.
> at Microsoft.Cis.Services.Nephos.Common.Authentication.NephosAuthenticationManager.SharedKeyAuthenticate(String stringToSign, String requestSignature, AuthenticationInformation authInfo) in F:\Storage-XStore\src\XFE\common\src\Authentication\NephosAuthenticationManager.cs:line 1359
> at Microsoft.Cis.Services.Nephos.Common.Authentication.NephosAuthenticationManager.AuthenticateImpl(IStorageAccount storageAccount, RequestContext requestContext, NephosUriComponents uriComponents, GetStringToSignCallback getStringToSignCallback, TimeSpan timeout, AsyncIteratorContext`1 context)+MoveNext() in F:\Storage-XStore\src\XFE\common\src\Authentication\NephosAuthenticationManager.cs:line 689 at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin) in F:\Storage-XStore\src\XFE\external\AsyncHelper\src\AsyncIteratorContextBase.cs:line 105 --- End of inner exception stack trace --- at Microsoft.Cis.Services.Nephos.Common.Authentication.NephosAuthenticationManager.EndAuthenticate(IAsyncResult asyncResult) in F:\Storage-XStore\src\XFE\common\src\Authentication\NephosAuthenticationManager.cs:line 452 at Microsoft.Cis.Services.Nephos.Common.Authentication.XFEBlobAuthenticationManager.AuthenticateImpl(IStorageAccount storageAccount, RequestContext requestContext, NephosUriComponents uriComponents, GetStringToSignCallback getStringToSignCallback, TimeSpan timeout, AsyncIteratorContext`1 context)+MoveNext() in F:\Storage-XStore\src\XFE\common\src\Authentication\XFEBlobAuthenticationManager.cs:line 251
> at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin) in F:\Storage-XStore\src\XFE\external\AsyncHelper\src\AsyncIteratorContextBase.cs:line 105
> --- End of inner exception stack trace ---
> at Microsoft.Cis.Services.Nephos.Common.Authentication.XFEBlobAuthenticationManager.EndAuthenticate(IAsyncResult asyncResult) in F:\Storage-XStore\src\XFE\common\src\Authentication\XFEBlobAuthenticationManager.cs:line 155
> at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 2689`

try with 64-byte base64 key as per suggestion by the msft docs https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob

**Comment by OrrinEdenfield** [comment]
Sorry - I mis-read my text editor, I did have a 64-byte base64 key.

However, upon changing the key in the running IoT Edge module and the .py file - I am now uploading to the local Blob storage service running on IoT Edge without error.

Thank you!

**Comment by xiafu-msft** [comment]
Hi @OrrinEdenfield 

Thanks for investigating and find out the solution.
So set api_version='2019-07-07' work and api_version='2017-04-17' doesn't work?
If that is the case do you think it's necessary to change the doc here? https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob#supported-storage-operations base on this it looks like only '2017-04-17' is supported (I feel), did I misunderstand anything?

**Comment by OrrinEdenfield** [comment]
@xiafu-msft I changed my script to below and it worked. I was not able to get api_version='2017-04-17' to work but maybe I'm doing something incorrectly? If the doc page is not correct I'm happy to submit a PR for that.

```
import os, uuid
from azure.storage.blob import BlobClient

# Connection string to the local Blob service
connection_string = "DefaultEndpointsProtocol=http;BlobEndpoint=http://192.168.0.12:11002/localblob;AccountName=localblob;AccountKey=KEY
local_path = "./"
local_file_name = "DATAFILENAME"
upload_file_path = os.path.join(local_path, local_file_name)
localcontainer = "pisynccontainer"

blob = BlobClient.from_connection_string(conn_str=connection_string, container_name=localcontainer, blob_name=local_file_name, api_version='2019-07-07')

with open(upload_file_path, "rb") as data:
    blob.upload_blob(data)
```

**Comment by OrrinEdenfield** [comment]
Coming back to this to see if I can get this working. I'm now using Python 3.7.3 on the Raspberry Pi Zero W, azure-storage-blob-12.7.1 and mcr.microsoft.com/azure-blob-storage:latest as the Edge-based Azure Storage Blob service.

I'm able to connect fine with Storage Explorer using the connection string and I'm trying to run this code from the [documentation](https://docs.microsoft.com/en-us/python/api/overview/azure/storage-blob-readme?view=azure-python#create-a-container):

```
from azure.storage.blob import ContainerClient

container_client = ContainerClient.from_connection_string(conn_str="DefaultEndpointsProtocol=http;BlobEndpoint=http://192.168.0.201:11002/azurepistorage;AccountName=azurepistorage;AccountKey={MY-KEY}", container_name="pizero_new_container")

container_client.create_container()

```

Error I'm getting now is:

> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_container_client.py", line 292, in create_container
>     **kwargs)
>   File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 134, in create
>     raise HttpResponseError(response=response, model=error)
> azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'The value for one of the HTTP headers is not in the correct format.'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "up-to-blob.py", line 5, in <module>
>     container_client.create_container()
>   File "/home/pi/.local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
>     return func(*args, **kwargs)
>   File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_container_client.py", line 294, in create_container
>     process_storage_error(error)
>   File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
>     error.raise_with_traceback()
>   File "/home/pi/.local/lib/python3.7/site-packages/azure/core/exceptions.py", line 218, in raise_with_traceback
>     raise super(AzureError, self).with_traceback(self.exc_traceback)
>   File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_container_client.py", line 292, in create_container
>     **kwargs)
>   File "/home/pi/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 134, in create
>     raise HttpResponseError(response=response, model=error)
> azure.core.exceptions.HttpResponseError: The value for one of the HTTP headers is not in the correct format.
> RequestId:26d11e97-44fd-4cba-be5c-0cde003f842a
> Time:2021-01-27T18:05:51.9663842Z
> ErrorCode:InvalidHeaderValue
> Error:None
> HeaderName:x-ms-version
> HeaderValue:2020-04-08
> ExceptionDetails:None
> ExceptionMessage:The value 2020-04-08 provided for request header x-ms-version is invalid.
> StackTrace:Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.InvalidHeaderProtocolException: The value 2020-04-08 provided for request header x-ms-version is invalid.
>    at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.RunVersionCheck() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 788
>    at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext() in F:\Storage-XStore\src\XFE\common\Protocols\REST\src\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 1537

**Comment by xiafu-msft** [comment]
Hi @OrrinEdenfield 

Do you happen to know the version of “Azure Blob Storage on IoT Edge" module you are using?

**Comment by OrrinEdenfield** [comment]
@xiafu-msft Great question. I was just using mcr.microsoft.com/azure-blob-storage:latest but I've now switched to mcr.microsoft.com/azure-blob-storage:1.4 (per list of available tags [here](https://mcr.microsoft.com/v2/azure-blob-storage/tags/list)).

So now I can confirm that I'm using version 1.4-linux-arm32v7. And this has resolved my issue.

I'll be sure not to use :latest for now and instead use :1.4.

Thank you!
