### ISSUE TITLE
Sending ETag on VM operations

### ISSUE THREAD

**Issue by gabriel-samfira** [Azure/azure-sdk-for-python#1401]
Hi,

I have the need to potentially manipulate the attached disks of a single VM from multiple locations. As such, when updating the VMs disks (or any other characteristics for that matter), I would like to be sure that I am not overwriting another operation, and inadvertently detaching the previously attached disks.

Sending the ETag on the ```virtuam_machine``` resource, would ensure that this does not happen, and we can choose to refresh the properties of the VM and retry (not unlike a transaction).

Is this something that is possible currently in the azure python SDK?

Thanks!

**Comment by johanste** [comment]
@gabriel-samfira, thanks for your suggestion. I would have to check to see if the Compute Resource Provider supports etags for Virtual Machine resources (not all resource providers do).

**Comment by johanste** [comment]
@gabriel-samfira, unfortunately, the VM PUT operation does not support etags/if-match/if-non-match headers. So there is not much the Azure Python SDK can do. 

@lmazuel, for services that **do** support etags, we should make sure that we have examples on how to correctly use it. As it stands today, I'm not sure what the easiest way is to pick up the etag header from a resource GET response (sending it in the subsequent request as a header, on the other hand, is fairly easy).

**Comment by gabriel-samfira** [comment]
Ahh, I see.

Thanks for the reply @johanste

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue is still a concern.
