### ISSUE TITLE
MSAL use for Azure ML resource deployment

### ISSUE THREAD

**Issue by sajalda23409** [Azure/azure-sdk-for-python#14048]
Hi,

I am responsible for deploying Azure ML resources like workspace, compute target and datastore using Python from Azure CI/CD Devops Pipeline.  I have Service principal certificate for authentication. I am confused about which authentication method of Python I will follow. 
Shall I used MSAL authentication? or
please suggest a secure authentication method of python that supports Service Principal certificate to authenticate Azure ML workspace.

**Comment by rastala** [comment]
Please see this document that describes various authentication options, In a CI/CD setup you'd typically use service principal based authentication.

https://docs.microsoft.com/azure/machine-learning/how-to-setup-authentication

**Comment by rastala** [comment]
#please-close
