### ISSUE TITLE
SDK should support reading certificate from buffers instead of file paths.

### ISSUE THREAD

**Issue by manuchandel** [Azure/azure-sdk-for-python#14055]
Using Azure SDK to authenticate via certificateCredential requires parameter **filePath to pem cert including private key**. This is not desirable in an environment where it is not safe to have pem certs that include private key.

If the user has pem bytes in the variable, he should be able to pass it and authenticate. 

One use case is Azure Databricks Environment. User does not want to store the certificate inside a file on a cluster. Instead he can get the certificate from mounted keyvault and use it for authentication. 

Because the code is just reading pem bytes from file path, let it also consume pem bytes from user if the user has it.

https://github.com/Azure/azure-sdk-for-python/blob/e2cac0341ebb1d1d56c9e4535cae3f9c107154c4/sdk/identity/azure-identity/azure/identity/_credentials/certificate.py#L52

**Comment by chlowell** [comment]
Thanks for opening this. It may require some clever design but I think this is a reasonable feature request. I've put it on our backlog.

**Comment by kjaanson** [comment]
Are there any updates on this? 
We would also greatly benefit from this feature due to the exact same use case (usage from Azure Databricks Environment).

**Comment by chlowell** [comment]
I'm looking at solutions now and plan to address this in the next minor version. I'll update this issue when the work's done. The upcoming February release will be a beta and is pretty busy with other features, but this one could make it in.

**Comment by chlowell** [comment]
azure-identity 1.6.0b1 is available today, and updates CertificateCredential to accept bytes:
```py
# the only option in 1.5.0
CertificateCredential(tenant_id, client_id, "/certs/cert.pem")

# that still works in 1.6.0b1 but one can also do this (cert_bytes must be in PEM format)
CertificateCredential(tenant_id, client_id, certificate_bytes=cert_bytes)
```

We might revise this API before the stable 1.6.0 release (any change will be noted in the changelog). Feel free to reopen this issue if you encounter any problems using the new argument.

**Comment by chlowell** [comment]
Small update for anyone watching this: in 1.6.0b2, released today, we renamed `certificate_bytes` to `certificate_data`.
