### ISSUE TITLE
docs broken link

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#14066]
In 

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.4.0/azure.storage.blob.html?highlight=readall#azure.storage.blob.StorageStreamDownloader.readal

the return type link is broken.

**Comment by xiafu-msft** [comment]
Thanks for reporting this! We will fix this in the next release (it should be tomorrow)

**Comment by xiafu-msft** [comment]
This is fixed in 12.6.0b1! Thanks again for reporting this
