### ISSUE TITLE
[metricsadvisor] find solution to remove edits to generated code

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#14089]
@kristapratico commented on [Thu Sep 10 2020](https://github.com/Azure/azure-sdk-for-python-pr/issues/577)

We're currently editing the generated code everywhere there is a FIXME to avoid an invalid URL being created where the base_url gets the absolute nextLink URL appended to it.

https://github.com/Azure/azure-sdk-for-python-pr/blob/feature/metricsadvisor/sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_generated/operations/_azure_cognitive_service_metrics_advisor_restapi_open_ap_iv2_operations.py#L369

This will either require a fix in M4 or we can look into if swagger transforms can fix this.

---

@kristapratico commented on [Thu Sep 10 2020](https://github.com/Azure/azure-sdk-for-python-pr/issues/577#issuecomment-690676607)

This will likely be a fix in autorest core

**Comment by lmazuel** [comment]
@iscai-msft @kristapratico I believe there was an issue about autorest forcing every url to start with `/`, @timotheeguerin does that ring a bell?

**Comment by kristapratico** [comment]
I tried regenerating with latest autorest and this is fixed. The generated code in metrics advisor just needs to be updated and then we should be able to close this.

**Comment by kristapratico** [comment]
This was resolved when we regenerated/refactored metrics advisor with DPG. I verified that the nextLink is correctly formed in the current library.
