### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by ps-jay** [Azure/azure-sdk-for-python#1410]
Hi there,

as at 2017-09-04, the link here: https://github.com/Azure/azure-sdk-for-python/blame/master/azure-mgmt-containerinstance/README.rst#L40 leads to a 404.

**Comment by lmazuel** [comment]
Thanks @ps-jay ! 
In the meantime, this might help:
https://github.com/Azure-Samples/container-service-python-manage

**Comment by lmazuel** [comment]
The link now brings correctly to
https://docs.microsoft.com/python/api/overview/azure/containerinstance

Which is the service page, and the service is responsible to write the samples that goes there (yes, there is no sample yet... :( )

Closing, since the initial question of broken link is solved.
