### ISSUE TITLE
service bus messages with empty body?

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#14131]
- **Package Name**: servicebus
- **Package Version**: 0.50.3
- **Operating System**: OSX
- **Python Version**: 3.7

This is not a bug, but rather request for explanation. I am wondering whether it is possible to create a `Message` in service bus that has no body. From the code

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/0.50.3/_modules/azure/servicebus/common/message.html#Message

I guess that it is not possible, as an exception will be raised. Btw, it should be documented.

But what if the message is created using the `message` property? In that case is not clear to me what would happen.

Shall a client code check for the message body being none before decoding? Usually I convert the message to `str` and decode as `JSON`, but what if the body is `None`?

**Comment by KieranBrantnerMagee** [comment]
It is in fact possible, although we don't make it easy.
`Message(None, message=uamqp.Message())`
(If you wanted to give a session id it'd look like this)
`Message(None, message=uamqp.Message(properties=uamqp.message.MessageProperties(group_id=session_id)))`

So if you think your sender might have a reason to provide a None body, it might be defensive to look out for that; but if I trusted my sender to always give well-formed JSON I'd treat any deviation from that like I would erroneous application-layer logic.

All that said; brings up an interesting point about whether this gate to disallow None bodies is still consensus, I'll surface it in our design discussions for 7.0.  Thanks as always for continuing to feed these really on-point observations; will leave this open as a reminder to keep on, but do shout if what I provided above doesn't answer your immediate question/if any clarification would be helpful.

**Comment by andrea-cassioli-maersk** [comment]
@KieranBrantnerMagee thanks for the explanation. In my case I control both sender and receiver for now, but maybe in the future I will not. 

IMHO, if you can set a `None` body via a message, then why not via `body`, mostly for consistency sake?
