### ISSUE TITLE
[ServiceBus] Define the meaning of receive max_wait_time being 0

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#14138]
We need to settle it before GA. @KieranBrantnerMagee 

current implementation:
0 is taken as no timeout which is equal to None, it's definitely not the behavior we want.

options:
1. 0 means returning immediately
  - python idiomatic/user intuitive if they want to drain
  - implementation would be setting a small timeout value internally
2. raise error if user passes 0 to the sdk
  - consistent with timeout in send/mgmt request

**Comment by ramya-rao-a** [comment]
I believe we have a decision here based on offline discussions. 
@KieranBrantnerMagee Can you share here what we settled on?

**Comment by KieranBrantnerMagee** [comment]
We settled to have this raise an exception on None, as this would give us the flexibility to support this as a scenario later in a non-breaking way if desired by users, but for the time being normalizes us with broader sdks, and gives a clear guardrail for the semantic gotchas that might occur with 0.
