### ISSUE TITLE
ComputeTarget.get_status() return None instead of string of provision_state

### ISSUE THREAD

**Issue by chengyu-liu-cs** [Azure/azure-sdk-for-python#14147]
- **Package Name**: azureml sdk
- **Package Version**: 1.12
- **Operating System**: mac & linux
- **Python Version**: 3.6

**Describe the bug**
When an AmlCompute is provision with unsupported vm_sizes (why someone uses unsupported vm sizes ? because the [documentation is not clear ](https://github.com/Azure/MachineLearningNotebooks/issues/1169#issuecomment-701587839)), the provision failed and error message was like this `Provisioning errors: [{'error': {'code': 'InvalidPropertyValue', 'message': 'The specified value Standard_B2s for property Cluster.Properties.VMSize is not a supported VM size. See additional details for supported VM sizes.', 'details': [{'code': 'SupportedVMSizes', 'message': 'STANDARD_D1,STANDARD_D2,STANDARD_D3,STANDARD_D4,STANDARD_D11,STANDARD_D12,STANDARD_D13,STANDARD_D14,STANDARD_D1_V2,STANDARD_D2_V2,STANDARD_D3_V2,STANDARD_D4_V2,STANDARD_D11_V2,STANDARD_D12_V2,STANDARD_D13_V2,STANDARD_D14_V2,STANDARD_D15_V2,STANDARD_D2_V3,STANDARD_D4_V3,STANDARD_D8_V3,STANDARD_D16_V3,STANDARD_D32_V3,STANDARD_D64_V3,ST.............'}]}}]`

**To Reproduce**
Cannt share exact codes but here is some of codes 

1 try to create aml cluster with non-supported vm_sizes, e.g., Standard_B2s which failed giving error message above.
`
provision_config = AmlCompute.provisioning_configuration(vm_size='Standard_B2s', min_nodes=1, max_nodes=1)
compute_target = ComputeTarget.create(ws, name='amlcluster', provisioning_configuration=provision_config)
compute_target.wait_for_completion(show_output=True, min_node_count=0, timeout_in_minutes=20) 
`
script breaks in the wait_for_completion step

When check azure ml portal, the cluster creation failed and it was hanging there. The provision state was 'Failed'

My script can check whether given cluster exists and if state is not 'Succeeded', then delete it and recreate one. So I re-ran the script hoping the cluster can be re-created. But it failed.
`
try:
            compute_target = ComputeTarget(workspace=ws, name='amlcluster')
            compute_target_stage = compute_target.get_status()
            if compute_target_stage.provisioning_state != 'Succeeded':
                       ComputeTarget.delete()
                       compute_target = ComputeTarget.create(ws, name='amlcluster', provisioning_configuration=provision_config)
                       
except ComputeTargetException:
             # do something 
`
but the exception was `AttributeError: 'NoneType' object has no attribute 'provisioning_state'`  from `  if compute_target_stage.provisioning_state != 'Succeeded':` as get_status returned None.

**Expected behavior**
get_status should return string but None is returned.

**Screenshots**

**Additional context**

**Comment by brendalee** [comment]
Thanks for the feedback. For unsupported VM sizes, the provisioning will not go through. You can try provisioning with another one of the supported VM sizes. Please let us know if you run into any more issues here!
