### ISSUE TITLE
[Tables] Cosmos Account Preparer uses name_prefix in caching and more testing needs to be done to verify that it is necessary

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-python#14148]
In the cosmos preparer located [here](https://github.com/Azure/azure-sdk-for-python/tree/master/tools/azure-sdk-tools/devtools_testutils), the caching ability is set as:
```
self.set_cache(use_cache, parameter_name, name_prefix)
```
The name_prefix being used forces the caching to check if there exists a resource with that exact tuple (`parameter_name, name_prefix`). This was added while debugging a nasty recordings bug and left as is without testing if name_prefix is necessary for the caching to work as needed..

**Comment by KieranBrantnerMagee** [comment]
Dropping my mental state while I have it:  The one reason this might be necessary is if there is code which relies on a fixed name prefix (or that could cause it to become misaligned with the cached object) which would itself be a bad smell, so I would hope that anything requiring this would be able to be triaged if it was a real need.

**Comment by seankane-msft** [comment]
Investigated this issue, `name_prefix` is not a required argument for caching to work as intended. Closing this issue now.
