### ISSUE TITLE
FormRecognizerClient outputs duplicate logs, including un-redacted headers

### ISSUE THREAD

**Issue by ctstone** [Azure/azure-sdk-for-python#14143]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.0.0
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.8.0

**Describe the bug**
When using the standard `logger` we see duplicate log messages in STDOUT for http request/response. The first message contains plaintext headers, but the second message contains `REDACTED` for most headers.

**To Reproduce**
1. See repro: https://github.com/ctstone/azure-sdk-py-repro-logging

**Expected behavior**
Package should output HTTP messages only once. `Ocp-Apim-Subscription-Key` header should be redacted.

**Additional context**
At first glance it seems this is caused by enabling `logging.DEBUG` as suggested by the doc. This has the effect of enabling the `NetworkTraceLoggingPolicy` which has some duplicate functionality with `HttpLoggingPolicy`.

**Comment by kristapratico** [comment]
Hey @ctstone 

Thanks for opening the issue and providing the repro info! I looked into this and reached out to our azure-core folks about the logging policies.

In your example code, you set the logging level DEBUG, which _will_ return un-redacted headers and any logging messages that have a severity level higher than DEBUG, following this hierarchy: `CRITICAL > ERROR > WARNING > INFO > DEBUG`. So it appears that the duplicate functionality is expected here. If logging at the INFO level, `Ocp-Apim-Subscription-Key` will be redacted. Let me know if that helps.

**Comment by ctstone** [comment]
Hi @kristapratico !

We are using same example from the docs on pypi:

```python
logger.setLevel(logging.DEBUG)
```

Should that be `INFO`?

**Comment by kristapratico** [comment]
I opened an issue to update the example to show setting it at the INFO level. https://github.com/Azure/azure-sdk-for-python/issues/14154

**Comment by kristapratico** [comment]
Doc updated with #14180
