### ISSUE TITLE
Enable SDK Automation for new code generator

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-python#14152]
The SDK Automation spec can be found at https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/sdkautomation/sdk_customization.md. 

- [ ] Add [automation configuration](https://github.com/Azure/azure-rest-api-specs/blob/master/specificationRepositoryConfiguration.json) for new code generator in the specs repo 
- [ ] Add new swagger_to_sdk configuration file in the language repo
- [ ] Add generate script (./eng/scripts/generate_sdk) that will implement the [sdk automations spec](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/sdkautomation/sdk_customization.md).

**Comment by msyyc** [comment]
It is finished : https://github.com/Azure/azure-sdk-for-python/blob/main/scripts/automation_generate.sh
