### ISSUE TITLE
azure-mgmt-compute: VirtualMachineIdentityUserAssignedIdentitiesValue became mangled somewhere between 13.0.0 and 17.0.0

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#14150]
- **Package Name**: azure-mgmt-compute
- **Package Version**: 17.0.0
- **Operating System**:Linux
- **Python Version**: 3.7.3

**Describe the bug**
`azure.mgmt.compute.models.VirtualMachineIdentityUserAssignedIdentitiesValue` has changed to `azure.mgmt.compute.models.Components1H8M3EpSchemasVirtualmachineidentityPropertiesUserassignedidentitiesAdditionalproperties`. Changing names of classes and methods breaks existing code. The nature of the new name suggests this change may be unintentional.

**To Reproduce**
1. install azure-mgmt-compute
2. attempt to construct an object with type `azure.mgmt.compute.models.VirtualMachineIdentityUserAssignedIdentitiesValue` :-)

**Expected behavior**
This happened to us as a result of a routine upgrade to latest packages. We have been on `13.0.0` for a while, and latest is `17.0.0`. We expected the routine upgrade to be seamless.

**Comment by kaerm** [comment]
Thanks @jazelenk for reporting this, @nickzhums could you take a look at this

**Comment by nickzhums** [comment]
@jazelenk there was a major version upgrade in Python SDK from 13.0.0 to17.0.0. This is actually the reason why there was such a big version jump and an indication for important new changes (and breaking changes)
We actually released a beta version of 17.0.0 a while ago and it has been in preview for several months.

The new version of Python SDK introduces some breaking changes but also important new features such as unified authentication, distributed tracing, and much more. You can find a detailed quickstart and migration guide on this page. [link](http://aka.ms/azsdk/python/mgmt)

Do you guys regularly upgrade python ask as a routine?

**Comment by jazelenk** [comment]
Yes, I understand that the new version contains a lot of breaking changes. This change seems unnecessarily breaking, however, and TBH, it just looks wrong, like autorest blew a gasket or something.

**Comment by changlong-liu** [comment]
Hi @jazelenk , We are investigating on this and find this is related to a naming-convention change in codegen.  I will have a PR in swagger repo for this so that it can be fixed in next azure-mgmt-compute release.

**Comment by xiangyan99** [comment]
@msyyc do you know if this is fixed?
