### ISSUE TITLE
Contributing guidelines link is broken

### ISSUE THREAD

**Issue by rawwar** [Azure/azure-sdk-for-python#14161]
file link: https://github.com/Azure/azure-sdk-for-python/blob/master/CONTRIBUTING.md

" Microsoft Azure Projects Contribution Guidelines."  redirects to "http://azure.github.io/guidelines/" . But, this link is broken(getting 404 error).

**Comment by nickzhums** [comment]
@jongio @lmazuel this seems to be under the azure sdk web site page, could you guys update the link?

**Comment by rawwar** [comment]
I would have made a pull request. But, because of this hactoberfest.. didn't want to look like a spam PR. :-D
