### ISSUE TITLE
servicebus renew_lock exception

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#14164]
- **Package Name**: servicebus
- **Package Version**: 0.50.3
- **Operating System**: OSX
- **Python Version**: 3.7

I have just observed the following:
* my app tried to renew a lock on a message in service bus calling the method `Message.renew_lock`
* the process went in timeout (we have observed a number of issues last night with Azure...) and raised an exception in 
`azure/servicebus/base_handler.py", line 103` 
* this exception is a general `ServiceBusError` exception, a kind of catch all

Now there is no mention about this kind of exceptions in the docs, and  this leads to bugs as one protect the code against what is in the docs.

Moreover, as I have been digging into the code, I realised the timeout is hard-coded! I would have expected some default named parameter instead.

**Comment by KieranBrantnerMagee** [comment]
I love when I get to be the bearer of good news. We have a [PR open](https://github.com/Azure/azure-sdk-for-python/pull/13854) to address precisely that timeout (and add a timeout parameter to all functions for which it is appropriate, ala peek, schedule, etc) in 7.0.  (It's ready to go in pending this week's UAMQP release, to add support into the core for this feature.)

That said, your points about the catchall exception and the lack of exception docs are both things we'd like to address.  The latter already has an item on our todo list, to create a full section for failure triage and "error codes" within troubleshooting, but the former, providing a specific timeout related error has not been raised, and is a very apt point.  I'll make a mention of it in that PR to see what @yunhaoling  thinks.

**Comment by andrea-cassioli-maersk** [comment]
Thanks @KieranBrantnerMagee , good to see you already cover this.j
