### ISSUE TITLE
Expose backup/restore operation status on poller objects

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#14169]
Currently the only way to get an operation's job ID from a poller is by examining the status object held by the polling method, for example:
```py
backup_poller = backup_client.begin_full_backup(container_uri, sas_token)
job_id = backup_poller.polling_method().resource().id
```
It would be more ergonomic and discoverable if the poller itself exposed the ID, or even the entire status object. Looks like such a change would require subclassing `LROPoller`.

**Comment by mccoyp** [comment]
It seems that other teams have been making related requests for exposing metadata on the base `LROPoller`, so there'll be an upcoming effort to review changes to the class -- exposing job IDs more readily will be added to the list of desired changes.

**Comment by mccoyp** [comment]
The polling story for administration is going in a different direction now; tracked by #19123
