### ISSUE TITLE
NetworkTraceLoggingPolicy does not redact Cognitive Services hey header

### ISSUE THREAD

**Issue by ctstone** [Azure/azure-sdk-for-python#14167]
- **Package Name**: azure-core
- **Package Version**: 1.8.1
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.8

**Describe the bug**
The logger currently [redacts](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L283-L284) the `Authorization` header, but does not redact `Ocp-Apim-Subscription-Key` which is the credential for Cognitive Services resources.

**To Reproduce**
Enable logging with `DEBUG` level, e.g. following docs for [Form Recognizer](https://pypi.org/project/azure-ai-formrecognizer/).

**Expected behavior**
The logger should treat the `Ocp-Apim-Subscription-Key` header the same as `Authorization` and redact it.

**Comment by kristapratico** [comment]
Hey @ctstone 

This is expected according to our logging docs: 

> logging.DEBUG | Detailed information that is commonly used for troubleshooting. Debug is the only logging level that includes sensitive information such as account keys in headers. Debug output typically includes a stack trace for exceptions. The debug level automatically enables the info, warning, and error levels. [SDK logging docs](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-logging)

I will update our README to point to these docs so there is no confusion.

**Comment by ctstone** [comment]
In that case, the docs are incorrect because the `NetworkTraceLoggingPolicy` _does_ do redaction for the `authorization` header:

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L283-L284

**Comment by kristapratico** [comment]
I asked the same question. Will open an issue with docs to make this more clear. Thanks again for all your help here :)

**Comment by kristapratico** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs/issues/312

**Comment by ctstone** [comment]
Thanks for pushing the docs update. However, I think the question still stands: should `ocp-apim-subscription-key` get the same treatment as `authorization` with respect to `azure.core` logging?

**Comment by kristapratico** [comment]
No, it's intended to be that way. Our guidelines state that DEBUG will have sensitive info: 
https://azure.github.io/azure-sdk/python_implementation.html#python-logging-debug
A user must also pass the `logging_enable` keyword to opt into using this azure-core policy / expose sensitive information in logs. If wanting to enable logging, but have `ocp-apim-subscription-key` redacted, then logging level should just be set to `INFO`.

Thanks again for pointing out the inconsistency with the Authorization header. After talking to azure-core folks, we have an issue opened to un-redact it: https://github.com/Azure/azure-sdk-for-python/issues/14191

**Comment by kristapratico** [comment]
@ctstone - going to close this issue. Please re-open if you have any concerns.
