### ISSUE TITLE
FormRecognizerClient redacts non-sensitive information from logs

### ISSUE THREAD

**Issue by ctstone** [Azure/azure-sdk-for-python#14166]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.0.0
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.8.0

**Describe the bug**
When logging is enabled, the output headers and query string are redacted. These are not sensitive values and including them can streamline support cases, particularly the `apim-request-id`. Only the `Ocp-Apim-Subscription-Key` should be redacted here.

```
Request URL: 'https://***.cognitiveservices.azure.com//formrecognizer/v2.0/prebuilt/receipt/analyze?includeTextDetails=REDACTED'
Request method: 'POST'
Request headers:
    'Content-Type': 'application/pdf'
    'x-ms-client-request-id': '1aeb780c-03da-11eb-9acf-000d3a551fcd'
    'User-Agent': 'azsdk-python-ai-formrecognizer/3.0.0 Python/3.8.0 (Linux-5.4.0-1025-azure-x86_64-with-glibc2.27)'
    'Ocp-Apim-Subscription-Key': 'REDACTED'
A body is sent with the request
Response status: 202
Response headers:
    'Date': 'Thu, 01 Oct 2020 11:34:45 GMT'
    'Content-Length': '0'
    'Connection': 'keep-alive'
    'Operation-Location': 'REDACTED'
    'x-envoy-upstream-service-time': 'REDACTED'
    'apim-request-id': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-content-type-options': 'REDACTED'
```

**To Reproduce**
Enable logging as documented on the README: https://pypi.org/project/azure-ai-formrecognizer/ (change level to `INFO`).

**Expected behavior**
`apim-request-id` and other non-sensitive values should be included in the log.

**Comment by kristapratico** [comment]
Thanks for pointing this out, @ctstone . I will add 

```
    'Operation-Location': 'REDACTED'
    'x-envoy-upstream-service-time': 'REDACTED'
    'apim-request-id': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-content-type-options': 'REDACTED'

```
to the un-redacted headers list for Form Recognizer.
