### ISSUE TITLE
Missing PyPi package update for azure-synapse

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-sdk-for-python#14165]
In #11608, changes were made to the ```azure-synapse``` package. In particular, the package was split into three individual packages.

However, ```azure-synapse``` is still available on PyPi and it's not marked as deprecated which is confusing.

It would be nice if the current status of the package could be clarified.

**Comment by idear1203** [comment]
Thanks! We will deprecate the package in future. FYI @lmazuel

**Comment by lmazuel** [comment]
@xiangyan99 low prio, let's do something like Storage:
https://pypi.org/project/azure-storage/

IOW, it fails at install time, and PyPI page and error message gives some details how to recover

**Comment by xiangyan99** [comment]
Fixed.
