### ISSUE TITLE
[Core] Support continuation token on AzureError

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#14176]
We should expand the available properties on the [base AzureError](https://github.com/Azure/azure-sdk-for-python/blob/fa6c1b8c33a8e46641731b5a7b26ecefaf166ce4/sdk/core/azure-core/azure/core/exceptions.py#L187) object to include `continuation_token`.
This would allow errors raised during paging, LRO, etc to be able to be manually re-attempted.

This could either take the form of an attribute on the base error, or simply documenting a set of args/properties that _may_ be found on the raised error.

cc @johanste

**Comment by johanste** [comment]
@tg-msft, I don't know if you have considered something similar for .NET?

**Comment by tg-msft** [comment]
No, we created specific `DataLakeAclChangeFailedException` exception in https://github.com/Azure/azure-sdk-for-net/pull/15317 that contains the continuation token and an awesome error message.

**Comment by tg-msft** [comment]
(Though continuable/resumable/retriable errors are a thing we've heard asks for)

**Comment by annatisch** [comment]
@tg-msft - yes they did that in Python too - I'm advocating for it's removal because if means that users have to handle things like ServiceRequestError differently for that one API.
#14177

**Comment by tg-msft** [comment]
That wouldn't solve it for us in .NET, unfortunately, because I couldn't wrap a `TaskCanceledException` in an `Azure.RequestFailedException` to add the continuation token.

**Comment by johanste** [comment]
@tg-msft, would you be able to add the continuation token to the `Data` property of the exception? And maybe I should open a separate issue in the .NET repo for this suggestion to be shot down, and not have the Python discussion be hijacked...

**Comment by tg-msft** [comment]
[That was my proposal](https://github.com/Azure/azure-sdk-for-net/pull/15317#discussion_r492978599), but we didn't go that way.  This feels like the sort of issue that could be filed in https://github.com/Azure/azure-sdk for every language's Azure.Core exception/error type?
