### ISSUE TITLE
ImportError: cannot import name 'LeaseProperties' from 'azure.storage.blob'

### ISSUE THREAD

**Issue by d5chaub** [Azure/azure-sdk-for-python#14171]
- **azure-storage-file-datalake**: 
- **12.1.2**: 
- **Windows 10**:
- **3.7.9**: 

**Describe the bug**
Despite being in a fresh virtual environment, I get errors after running the exact example code seen here, 
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-python

"Traceback (most recent call last):
  File "c:\Users\d.schaub\Desktop\PITS_gen2.py", line 4, in <module>
    from azure.storage.filedatalake._models import ContentSettings
  File "C:\Users\d.schaub\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\storage\filedatalake\__init__.py", line 7, in <module>
    from ._download import StorageStreamDownloader
  File "C:\Users\d.schaub\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\storage\filedatalake\_download.py", line 7, in <module>
    from ._models import FileProperties
  File "C:\Users\d.schaub\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\storage\filedatalake\_models.py", line 11, in <module>
    from azure.storage.blob import LeaseProperties as BlobLeaseProperties
ImportError: cannot import name 'LeaseProperties' from 'azure.storage.blob' (C:\Users\d.schaub\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\storage\blob\__init__.py)"

**To Reproduce**
1. Make new conda environment
2. pip install azure-storage-file-datalake
3. run [code here](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-python). 

**Expected behavior**

I expect the example code from the docs to allow me to connect to my datalake.

**Screenshots**
![azure_gen2_errors](https://user-images.githubusercontent.com/52209369/94838015-96a3c080-03da-11eb-822e-ac71ef48bebf.png)

**Additional context**

**Comment by xiafu-msft** [comment]
![image](https://user-images.githubusercontent.com/49707495/94944328-f1e2bb00-048d-11eb-9617-d9c0e837ec5e.png)
Here is what I did, it looks I can import using python

**Comment by d5chaub** [comment]
I am not able to get this code to work. New virtual environments don't help. It seems from online research that I am not alone in issues with old azure packages causing problems with new ones, in spite of environmental isolation. This seems to be particularly true for the blob libraries.

Is there any command to uninstall all azure libraries at once?

**Comment by xiafu-msft** [comment]
hi @d5chaub 

Sorry that there's no command to uninstall all azure lib at once.
Can you open a powershell and follow the screenshot to see if that works? We need more info to help, since it's not reproduceable.

Thanks for your patience
