### ISSUE TITLE
[ServiceBus] Track2 - normalize commonly named service-bus specific exceptions with a prefix.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14187]
**Is your feature request related to a problem? Please describe.**
Objects like Message exist across other SDKs.  Thus, errors like MessageError are rather generic.  This may merit a ServiceBusError style prefix for clarity where appropriate.  Work with python architects to decide our philosophical threshold for this being needed. 

**Describe the solution you'd like**
Ambiguously generic exceptions should be given a ServiceBus prefix.

**Describe alternatives you've considered**
Alternate is to rely on terseness and user-defined aliasing.  Although I personally am a fan of this, it does cause confusion in a broader SDK ecosystem and thus we should make sure we have nomenclature that doesn't create pitfalls within that.

**Comment by KieranBrantnerMagee** [comment]
From planning discussion:  Also inherit base exception from AzureError (azure.core)

**Comment by yunhaoling** [comment]
conclusion:
 - general guideline: add prefix for generic error types; for sb specific error type/errors that're descriptive enough, not needed

so in detail, the names of the error would be:

ServiceBusConnectionError
ServiceBusAuthorizationError
ServiceBusAuthenticationError
NoActiveSession
OperationTimeoutError
ServiceBusMessageError
MessageContentTooLarge
MessageAlreadySettled
MessageSettleFailed
MessageSendFailed
MessageLockExpired
SessionLockExpired
AutoLockRenewFailed
AutoLockRenewTimeout
