### ISSUE TITLE
Attempts  to create AKS user nodepool with minCount 0

### ISSUE THREAD

**Issue by kmrwong** [Azure/azure-sdk-for-python#14199]
**Describe the bug**
Attempts to add a user nodepool using Python SDK API and Jenkins failed with the following:

10:27:19   File "/var/lib/jenkins1/workspace/azure/ENGLAB/TESTING/pepper/azure-base-runner/35/build-35/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_05_10/operations/_deployments_operations.py", line 1438, in create_or_update
10:27:19     **operation_config
10:27:19   File "/var/lib/jenkins1/workspace/azure/ENGLAB/TESTING/pepper/azure-base-runner/35/build-35/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_05_10/operations/_deployments_operations.py", line 1385, in _create_or_update_initial
10:27:19     raise exp
10:27:19 msrestazure.azure_exceptions.CloudError: Azure Error: InvalidTemplateDeployment
10:27:19 Message: The template deployment 'i102-aks-englab.yml' is not valid according to the validation procedure. The tracking id is 'f0ce1f2d-35f8-435e-9f3e-14886ad3203a'. See inner errors for details.
10:27:19 Exception Details:
10:27:19       Error Code: InvalidParameter
10:27:19       Message: Provisioning of resource(s) for container service l6cld-aksee1-englab in resource group l6cld-eastus-aksee1-englab failed. Message: {
10:7:19   "code": "InvalidParameter",
10:27:19   "message": "The value of parameter agentPoolProfile.minCount is invalid. Please see https://aka.ms/aks-naming-rules for more details.",
10:27:19   "target": "agentPoolProfile.minCount"
10:27:19  }. Details: 

This is snippet of the deployment yaml:
      - name: user0
        osDiskSizeGB: 100
        count: 0
        vmSize: Standard_M64s
        osType: Linux
        storageProfile: ManagedDisks
        vnetName: ..
        vnetSubnetName: ...
        maxPods: 90
        maxCount: 50
        minCount: 0
        enableAutoScaling: true
        type: VirtualMachineScaleSets
        serviceCidr: ...
        dockerBridgeCidr: ...

**Expected behavior**
Expecting the nodepool to be created with min count 0 since that is now supported for nodepool of user mode and standard LB

If minCount>0 is specified, then the nodepool is created successfully.

With az aks nodepool - it's possible to specify min-count 0 as long as node-count>0 due to issue posted in https://github.com/Azure/azure-cli/issues/12723

**Comment by changlong-liu** [comment]
Hi service team, please confirm whether minCount==0 is available in this case.

**Comment by marwanad** [comment]
@kmrwong which api version are you using?

**Comment by marwanad** [comment]
also you can't specify minCount on the system nodepool. It would be great if you can provide the entire template.
