### ISSUE TITLE
azure.mgmt.web update settings doesn't allow for colons

### ISSUE THREAD

**Issue by HarleyB123** [Azure/azure-sdk-for-python#14198]
- **Package Name**: 
azure.mgmt.web
- **Package Version**: 
0.48

- **Operating System**:
MacOS and Ubuntu

- **Python Version**: 
Tested on 3.6 and 3.8

**Describe the bug**
When updating the application settings for a webapp, if one of the key-value pairs contains a colon, then the code fails

**To Reproduce**
```
from azure.mgmt.web import WebSiteManagementClient
test = {"enjoys_roaming_the_streets": "True", "is_sleepy": "False", "owner_email": "dogdog@dog.dog", "Name": "idk Rex"}
client = WebSiteManagementClient(service_credentials, sub)
client.web_apps.update_application_settings(rg, name, properties=test)
```

works, but 

```
from azure.mgmt.web import WebSiteManagementClient
test = {"enjoys_roaming_the_streets": "True", "is_sleepy": "False", "owner_email": "dogdog@dog.dog", "Name": "idk Rex", "Test:0:Test": "hi"}
client = WebSiteManagementClient(service_credentials, sub)
client.web_apps.update_application_settings(rg, name, properties=test)
```
does not work

**Expected behavior**
I would like this code to work with both colons and without in the string key

**Comment by HarleyB123** [comment]
On this, the Azure API itself **does** allow for colons in the keys, which makes me think it's something to do with the fact that the SDK requires a dictionary with string keys and values? maybe it might be easier to accept a JSON object?

If possible, can a PR be assigned to this issue when ready as I am curious to see how this is fixed 😄

**Comment by changlong-liu** [comment]
Hi service team, I get below error with @HarleyB123 's code from REST call response, would you confirm colon is allowed or not? Thanks.

~~~
'{"Code":"BadRequest","Message":"AppSetting with name \'Test:0:Test\' is not allowed.","Target":null,"Details":[{"Message":"AppSetting with name \'Test:0:Test\' is not allowed."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"04072","MessageTemplate":"AppSetting with name \'{0}\' is not allowed.","Parameters":["Test:0:Test"],"Code":"BadRequest","Message":"AppSetting with name \'Test:0:Test\' is not allowed."}}],"Innererror":null}'
~~~

**Comment by HarleyB123** [comment]
Hey service team 👋  it's been over a month on this - any updates?

**Comment by HarleyB123** [comment]
Have seen there is a new version out of Azure-mgmt-web, the following works:

```
client = WebSiteManagementClient(service_credentials, sub)
settings = {"properties": {"id":5}}
client.web_apps.update_application_settings(rg, name, app_settings=settings)
```

but once again - this doesn't:

```
client = WebSiteManagementClient(service_credentials, sub)
settings = {"properties": {"id:fails":5}}
client.web_apps.update_application_settings(rg, name, app_settings=settings)
```

**Comment by HarleyB123** [comment]
Can close this.

For anyone using the SDK that comes across this in the future - this app settings issue is present on Linux App Services. Windows app services *should* work with the SDK (not tested, I personally moved over to use the REST API with Python).

If you need to use colons in Linux App Settings - you can replace the colon with a double underscore and it should work the same - so:

```
test:0:test
```

becomes

```
test__0__test
```
