### ISSUE TITLE
[ServiceBus] Message properties migration guide segment

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14202]
**Is your feature request related to a problem? Please describe.**
ServiceBus.Message properties have changed significantly since track1.  In lead up to GA, let's ensure the migration guide is comprehensive for changes in how various message properties should be translated from 0.5 to 7.0

**Describe the solution you'd like**
Ensure major paths through message properties are documented in the appropriate migration guide tables.  Some may already be done (session_id?) but there's a bit of surface area there to check (locked_until, expired, settled, etc, with varying outcomes, some renamed like the former, some removed like the latter since you technically can't tell that messages state without acting on it if another node has in the interim)

**Comment by ramya-rao-a** [comment]
For reference, see the [Message format changes section in the JS migration guide](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/migrationguide.md#message-format-changes)
