### ISSUE TITLE
Hi @KieranBrantnerMagee I assume this patch is release in 0.50.3. I cannot find explicit mention in the release notes....

### ISSUE THREAD

**Issue by Co0olboi** [Azure/azure-sdk-for-python#14238]
Hi @KieranBrantnerMagee I assume this patch is release in 0.50.3. I cannot find explicit mention in the release notes....

_Originally posted by @andreacassioli in https://github.com/Azure/azure-sdk-for-python/pull/7453#issuecomment-691075777_

**Comment by KieranBrantnerMagee** [comment]
Hey @Co0olboi ; sorry for the delayed response, this got buried under a few other issues.  You're correct, and Andrea was kind enough to file a dedicated issue on this concurrent with the comment you linked, which lead us to discover that docs had not been published as expected when 0.50.3 went out.  

We pushed a change [a short bit ago](https://github.com/Azure/azure-sdk-for-python/pull/13774) to clean and prepare some broken links in those docs and will be doing the official publish ASAP, in a worst case during our MQ sprint (early next month.) but would hope to not wait that long.

Again, thanks for your patience as we get this sorted.  Closing this for now as we have the existing papertrail but don't hesitate to reopen if I can lend any more clarity/if there are any additional questions.
