### ISSUE TITLE
msrest.exceptions.AuthenticationError: , AdalError: 

### ISSUE THREAD

**Issue by samruddhi2909** [Azure/azure-sdk-for-python#14241]
1. "msrest.exceptions.AuthenticationError: , AdalError: Get Token request returned http error: 504

2.  "msrest.exceptions.AuthenticationError: , AdalError: Get Token request returned http error: 503 and server response: {""error"":""temporarily_unavailable"",""error_description"":""AADSTS90033: A transient error has occurred. Please try again.\r\nTrace ID: 7c3280d4-5d54-4240-bc1b-97a405a38000\r\nCorrelation ID: 1409d806-a8f8-4ba5-a6e5-1b7c68e497ce\r\nTimestamp: 2020-09-28 21:43:07Z"",""error_codes"":[90033],""timestamp"":""2020-09-28 21:43:07Z"",""trace_id"":""7c3280d4-5d54-4240-bc1b-97a405a38000"",""correlation_id"":""1409d806-a8f8-4ba5-a6e5-1b7c68e497ce""}"
Faced above 2 issues while running Azure API calls in python.

https://azure.github.io/azure-sdk-for-python/exceptions.html
The above documentation says the error cannot be retried. And the credentials are working fine now without any change.

Please help me in understanding how to resolve such issues and when does it exactly occur?

**Comment by lmazuel** [comment]
Hi @samruddhi2909 
The error talks about a 50x and "transient error", it was likely a server issue, maybe related to this:
https://www.zdnet.com/article/microsofts-azure-ad-authentication-outage-what-went-wrong/

Please confirm things are working as expected right now, thank you!
