### ISSUE TITLE
msrest.service_client.ServiceClient objects generate requests with stale access tokens (ExpiredAuthenticationToken)

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#14285]
- **Package Name**: msrest
- **Package Version**: 0.6.18
- **Operating System**:Linux
- **Python Version**: 3.7.3

**Describe the bug**
Long-running applications that use SDK clients have these client objects "go stale" and return errors. It appears that they generate access tokens once and do not renew them. The access fails with a `CloudError` that looks like this:
```
  {'deserializer': <msrest.serialization.Deserializer object at 0x7f1070532668>,
   'error': {'_message': "The access token expiry UTC time '10/4/2020 9:07:09 "
                         "PM' is earlier than current UTC time '10/4/2020 "
                         "9:14:41 PM'.",
             'additionalInfo': None,
             'data': None,
             'details': None,
             'error': 'ExpiredAuthenticationToken',
             'error_time': None,
             'innererror': None,
             'request_id': None,
             'target': None},
   'inner_exception': {'_message': "The access token expiry UTC time '10/4/2020 "
                                   "9:07:09 PM' is earlier than current UTC time "
                                   "'10/4/2020 9:14:41 PM'.",
                       'additionalInfo': None,
                       'data': None,
                       'details': None,
                       'error': 'ExpiredAuthenticationToken',
                       'error_time': None,
                       'innererror': None,
                       'request_id': None,
                       'target': None},
   'message': "The access token expiry UTC time '10/4/2020 9:07:09 PM' is "
              "earlier than current UTC time '10/4/2020 9:14:41 PM'.",
   'request_id': '2212f1db-f10d-49c7-8974-4fb0433961d0',
   'response': <Response [401]>,
   'status_code': 401}

```

**To Reproduce**
1. Construct a mgmt client such as azure.mgmt.compute.ComputeManagementClient using login credentials
2. Use this client for any access. In my application, the client is used for get, create_or_update, and update every few seconds.
3. After ~4 hours, the operation fails as above.

**Expected behavior**
I expect the APIs provided by `ComputeManagementClient` to ensure that they use up-to-date access tokens. I'm filing this as `msrest.service_client.ServiceClient`, but that's guesswork on my part; the problem may lie in another layer.

**Comment by changlong-liu** [comment]
Hi @lmazuel , would you help on this msrest issue? Thanks!

**Comment by lmazuel** [comment]
Hey @jazelenk 
msrest is responsible to call a refresh of the token, but not the logic behind it ([here](https://github.com/Azure/msrest-for-python/blob/98e2ebe7e5ed8a656f333963339ad8d20fc330d3/msrest/pipeline/requests.py#L80)). I would need to know what credential you are using, since they do not all support refreshing.
