### ISSUE TITLE
The Resource 'Microsoft.Compute/snapshots/snap1601239344' under resource group  'RG_NAME' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix". 

### ISSUE THREAD

**Issue by Mrbm5** [Azure/azure-sdk-for-python#14282]
- **azure-mgmt-compute**: 
- **13.1.0**: 

**Describe the bug**
When 200 incremental snapshot limit reached we are trying to create full snapshot with the same name. the snapshot is getting created. but when I try to retrieve snapshot information using computeclient.snapshots.get(),  API returns  -  Azure Error: ResourceNotFound"
Message: The Resource 'Microsoft.Compute/snapshots/1601239344' under resource group 
'RG_NAME' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix". 

on the portal I can verify the snapshot object is created with provisioning_state = succeeded

can you please help me to understand when does it exactly occurs and how to resolve this?  
I have already verified this **Solution 1 - check resource properties**  mentioned on https://aka.ms/ARMResourceNotFoundFix. 

Steps followed to create snapshot:
1. call computeclient.snapshots.create_or_update(resgrp, name, snapargs)
2. on Exception Azure Error : SnapshotsLimitReached   Message : The snapshot count was exceeded for a disk. Please retry the request after sometime 
     2.1 - Delete snapshot object created with provisioning_state = failed in step 1 - computeclient.snapshots.delete(resgrp, name)
     2.2 retry step no 1 with snapargs.incremental = false  (this will create full snapshot as expected)
3. retrieve created snapshot object using -  computeclient.snapshots.get(resgrp, name) as soon as the snapshot is created.

**Expected behavior**
snapshot information will be retrieved

**Comment by Drewm3** [comment]
@Vaibhav-Agar, could you please look into this issue.

**Comment by Vaibhav-Agar** [comment]
Based on the offline discussion with @Mrbm5, this is now being tracked via the Azure support channel. Resolving here.
