### ISSUE TITLE
Resolve Split Between Track1 and Track2 mgmt testing

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#14317]
Previous tags like `azure-appconfiguration_1.0.0` that we leverage to test "the world as it was" against the latest version of azure-core, hit some major bumps with the dependency on mgmt-resources.

[This PR](https://github.com/Azure/azure-sdk-for-python/pull/14069) made azure-sdk-tools compatible with `azure-mgmt-resources` and `azure-mgmt-keyvault` track1/track2. However, since we use tools "as they were" in the checked-out tag that we're testing against, we need to either 

1. Pin deps on azure-mgmt-keyvault<7.0.0
2. add `msrestazure` as a dev_req

I have a PR [over here](https://github.com/Azure/azure-sdk-for-python/pull/14316) that does #2. I'm dis-satisfied and would like a to implement a better solution that's more future proof.

**Comment by scbedd** [comment]
[passing regression storage](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=565964&view=results)
[passing regression core]()

**Comment by lmazuel** [comment]
I feel we have this one in control and WIP, closing
