### ISSUE TITLE
[Tables] Remove `await_prepared_test` from asynctestcase.py

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-python#14328]
This functionality is deprecated

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/tables/azure-data-tables/tests/_shared/asynctestcase.py#L32-L43

**Comment by bradleydamato** [comment]
Hey @seankane-msft ; took care of this one too

Ran the tox tests:
![image](https://user-images.githubusercontent.com/53579156/95795560-a499f100-0cb8-11eb-9e82-ce3f43015ad6.png)

Here is the PR: https://github.com/Azure/azure-sdk-for-python/pull/14444
