### ISSUE TITLE
[ServiceBus] Functions should take dict-representations of objects, and optional kwarg-parameters for updates

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14335]
Per python guidelines: https://azure.github.io/azure-sdk/python_design.html#python-client-splat-args
- mgmt update methods should take updateable fields as kwargs (e.g. update_queue should perhaps take DeleteOnIdle or what-have-you as a kwarg to override, if specified, the one in the primary description object)
- For mgmt (and non-mgmt) functions where an object is taken, also accept a dict representing that object.

todo: discuss with arch

**Comment by bradleydamato** [comment]
Hey @KieranBrantnerMagee ; currently investigating whether this is over my head or not. For part 1, my proposed solution is updating update_queue (and other *update_* functions) with something like the following:
```
def update_queue(self, queue, **kwargs):
        # type: (QueueProperties, Any) -> None
        """Update a queue.
        Before calling this method, you should use `get_queue`, `create_queue` or `list_queues` to get a
        `QueueProperties` instance, then update the properties. Only a portion of properties can
        be updated. Refer to https://docs.microsoft.com/en-us/rest/api/servicebus/update-queue.
        :param queue: The queue that is returned from `get_queue`, `create_queue` or `list_queues` and
         has the updated properties.
        :type queue: ~azure.servicebus.management.QueueProperties
        :rtype: None
        """

        to_update = queue._to_internal_entity()
        #ADDITION BELOW
        to_update.__dict__.update((k, v) for k, v in kwargs.items() if k in to_update.__dict__.keys()) 
        #ADDITION ABOVE 

        to_update.default_message_time_to_live = avoid_timedelta_overflow(to_update.default_message_time_to_live)
        to_update.auto_delete_on_idle = avoid_timedelta_overflow(to_update.auto_delete_on_idle)

        create_entity_body = CreateQueueBody(
            content=CreateQueueBodyContent(
                queue_description=to_update,
            )
        )
        request_body = create_entity_body.serialize(is_xml=True)
        with _handle_response_error():
            self._impl.entity.put(
                queue.name,  # type: ignore
                request_body,
                api_version=constants.API_VERSION,
                if_match="*",
                **kwargs
            )
```
The idea being that you update the attributes in the *to_update* object if and only-if the key from kwarg dict matches an attribute from within the object. This allows for the *avoid_timedelta_overflow()* logic to be left alone. I'm obviously open to feedback here but I think this would work for allowing field updates via kwargs.

Regarding point number 2, is that in reference to this?: https://azure.github.io/azure-sdk/python_design.html#python-client-splat-args

I understand why one would want to implement APIs this way, but with *update_* functions it's interesting in that the idea of an *update_* method  (at least in my mind) relies on the idea that you're referring to an object to update, and not necessarily an outside representation of the object. I made a toy example below to try an convey my thoughts here. 

```
class TestEntity:
    def __init__(self, name, number):
        self.name = name
        self.number = number 
    def update_testentity(self,TestEntityOrDict,**kwargs):
        to_update = TestEntityOrDict
        if type(to_update) == dict:
            to_update.update((k, v) for k, v in kwargs.items() if k in self.__dict__.keys())
            self.__dict__.update((k, v) for k, v in to_update.items() if k in self.__dict__.keys())
        else:
            to_update.__dict__.update((k, v) for k, v in kwargs.items() if k in self.__dict__.keys())

           
Test = TestEntity("Brad",1)
Test.update_testentity(Test,name="Kieran")
print(Test.name) #prints "Kieran"
print(Test.number) #prints 1

#The below section takes a dict as an arg instead of an object, but it
#doesn't feel like it makes sense in any practical way. 
#I could be wrong though. 

Test.update_testentity({"name":"Brad","number":1},name="Kieran",number=2)
print(Test.name) #prints Kieran
print(Test.number) #prints 2
```

Either way, let me know what you think. No rush (aside from by next release, lol). And as always; if I'm totally off-base, let me know.

**Comment by KieranBrantnerMagee** [comment]
Hey Bradley; props for taking a swing at this, and thanks again for all your help lately.

Your proposal is quite elegantly concise, and I think is right on the mark, but I'd need to give it some more contemplation to be sure to make sure there aren't any pitfalls.  

To #2, I believe you found exactly the right thing; "DO accept a Mapping (dict-like) object ..." etc.  I'm not quite sure what you mean by needing to self-refer in order to update, but to try and clarify by giving examples of a variety of places I might expect to see this:  send_messages (for message objects); create_queue (for queue properties).  

There's a subtlety I realize I should have called out but didn't initially; namely to make sure that in the update_* case, adding dict functionality doesn't break the constraint being enforced via *Description that all fields must be specified. (typically by getting the Description object from an earlier get call).

Feel free to take this one, since it seems like you're on the right track, but I'll tag @rakshith91 on this alongside you to give a hand if needed and a reliable way to escalate questions if I'm randomized.  (Rakshith give a shout if you need any context that isn't covered here and above)

**Comment by bradleydamato** [comment]
Hey @rakshith91 , 

One quick question about Kieran's comments above (avoiding tagging him unless there is a need to escalate):

He mentions that one place he would expect a dict-representation to be accepted is with the `create_queue` method. 

The signature for `create_queue` is as follows: 

```def create_queue(self, queue_name, **kwargs):```

Normally, this function creates a QueueProperties object by using the `queue_name` positional arg, then by popping the other elements from kwargs. If this function were to accept a dict-representation, I have a feeling that this would require passing the dict-representation as a positional arg and accessing the values as follows: 

```if type(queue_name) == dict:
        queue = QueueProperties(
            queue_name = queue_name["queue_name"],
            authorization_rules = queue_name["authorization_rules"],
            auto_delete_on_idle = queue_name["auto_delete_on_idle"],
            ET CETERA 
        )
```

This feels a little clunky and unintuitive. I guess my question is whether this is a pattern you would expect to follow, or if this is something to be avoided entirely (in other words, we should only allow dict_representations for functions/methods that take an object)?

**Comment by rakshith91** [comment]
Hey @bradleydamato  

a valid mapping for `create_queue` would be something like this:

```
queue_props = {
  'queue_name': 'foo',
  'authorization_rules': 'bar',
  'auto_delete_on_idle': None,
  'max_delivery_count': '10', 
  }
create_queue(queue_props)
```

The signature would be
```
def create_queue(self, queue, kwargs):
# type: (Union[str, Dict], Any)
```

This might also warrant changing the param name from queue_name to queue.

**Comment by bradleydamato** [comment]
@rakshith91 Yeah this is an awkward spot, as I feel taking dict-representation but also requiring the passing of `queue_name` as a positional argument (instead of including it in `queue_props` as a dict-element) is a *bit* clunky. 

Seeing as you cannot override required positional arguments in Python (at least not without adding additional complexity) I think this is the path we would have to take without implementing a breaking change. I will begin work on this then! Feel free to chime in if you think of any other workable solutions!

**Comment by bradleydamato** [comment]
Hey @rakshith91 , before I do too much work for nothing I just wanted to run this pattern by you. It's a bit clunky, but I think it will work. If I'm missing any sort of obvious implementation definitely let me know. I'm skeptical that this is optimal, but I just don't know how to check for all of the required properties without `required_queue_properties_list`. Thanks in advance, and thank you again for your clarification from earlier!

```
if "queue_properties" in kwargs.keys():
            queue_properties_dict = kwargs.pop("queue_properties")
            
             #This list clunky, but I don't know any other way to get the properties required to implement QueueProperties without implementing it first
           
             required_queue_properties_list = ["authorization_rules","auto_delete_on_idle","dead_lettering_on_message_expiration",
      "default_message_time_to_live","duplicate_detection_history_time_window","availability_status","enable_batched_operations",
            "enable_express","enable_partitioning","lock_duration","max_delivery_count","max_size_in_megabytes",
            "requires_duplicate_detection","requires_session","status","forward_to","forward_dead_lettered_messages_to","user_metadata"]
            
             #list of properties that should be in the dict that are not included in the dict
             excluded_properies = [queue_property for queue_property in required_queue_properties_list \
                if queue_property not in queue_properties_dict.keys()]
            
            if len(excluded_properies) >= 1:
                raise ValueError("The following properties must be included in the queue_properties dict {}".format(excluded_properies))

            queue = QueueProperties(
                queue_name,
                authorization_rules=queue_properties_dict.get("authorization_rules"),
                auto_delete_on_idle=queue_properties_dict.get("auto_delete_on_idle"),
                dead_lettering_on_message_expiration=queue_properties_dict.get("dead_lettering_on_message_expiration"),
                default_message_time_to_live=queue_properties_dict.get("default_message_time_to_live"),
                duplicate_detection_history_time_window=queue_properties_dict.get("duplicate_detection_history_time_window"),
                availability_status=None,
                enable_batched_operations=queue_properties_dict.get("enable_batched_operations"),
                enable_express=queue_properties_dict.get("enable_express"),
                enable_partitioning=queue_properties_dict.get("enable_partitioning"),
                lock_duration=queue_properties_dict.get("lock_duration"),
                max_delivery_count=queue_properties_dict.get("max_delivery_count"),
                max_size_in_megabytes=queue_properties_dict.get("max_size_in_megabytes"),
                requires_duplicate_detection=queue_properties_dict.get("requires_duplicate_detection"),
                requires_session=queue_properties_dict.get("requires_session"),
                status=queue_properties_dict.get("status"),
                forward_to=queue_properties_dict.get("forward_to"),
                forward_dead_lettered_messages_to=queue_properties_dict.get("forward_dead_lettered_messages_to"),
                user_metadata=queue_properties_dict.get("user_metadata")
            )

        #Else, continue as usual
else:

            queue = QueueProperties(
                queue_name,
                authorization_rules=kwargs.pop("authorization_rules", None),
                auto_delete_on_idle=kwargs.pop("auto_delete_on_idle", None),
                dead_lettering_on_message_expiration=kwargs.pop("dead_lettering_on_message_expiration", None),
                default_message_time_to_live=kwargs.pop("default_message_time_to_live", None),
                duplicate_detection_history_time_window=kwargs.pop("duplicate_detection_history_time_window", None),
                availability_status=None,
                enable_batched_operations=kwargs.pop("enable_batched_operations", None),
                enable_express=kwargs.pop("enable_express", None),
                enable_partitioning=kwargs.pop("enable_partitioning", None),
                lock_duration=kwargs.pop("lock_duration", None),
                max_delivery_count=kwargs.pop("max_delivery_count", None),
                max_size_in_megabytes=kwargs.pop("max_size_in_megabytes", None),
                requires_duplicate_detection=kwargs.pop("requires_duplicate_detection", None),
                requires_session=kwargs.pop("requires_session", None),
                status=kwargs.pop("status", None),
                forward_to=kwargs.pop("forward_to", None),
                forward_dead_lettered_messages_to=kwargs.pop("forward_dead_lettered_messages_to", None),
                user_metadata=kwargs.pop("user_metadata", None)
            )
```

**Comment by rakshith91** [comment]
hey @bradleydamato if the users are passing a dictionary, we must not do any client side validation for that - we just blindly send the dictionary and let the service handle it.

also, just  a quick update  after speaking with some architects - this should not apply to create_queue

users can always do
```
create_queue( queue_name, **queue_properties)
```
since it's always flattenned to kwargs

This applies to the update_queue method though

**Comment by bradleydamato** [comment]
@rakshith91 awesome, thank you for the update and the knowledge!

**Comment by rakshith91** [comment]
np!! let me know if you need anything else. and also sorry for the delayed response

**Comment by bradleydamato** [comment]
Hey @rakshith91 ! 

So as I sort of expected, passing a dict-representation to `update_queue` lead to the following error:
```AttributeError: 'dict' object has no attribute '_to_internal_entity'```

So going forward, would it make sense to generate a `QueueProperties` object from the dict-representation in the form of (something like):
```
if type(queue) == dict:
    #takes dict-vals that then get flattened
    dict_to_queue = QueueProperties(dict-representation.pop('name'),**dict-representation) 
    to_update=dict_to_queue._to_internal_entity()
else:
    to_update = queue._to_internal_entity()
```

and then let the method take its course, is doing that also within the realm of too much client-side processing?

**Comment by rakshith91** [comment]
@bradleydamato sorry for the confusion - by not doing client side validation, what i meant is that we should not verify if there are any properties that are missing in the dict. 
You got it right in the sample - basically do a 1:1 mapping of each key in dict to a queue property. but do not check if there's any piece of information missing on the client side and let the service handle that.

**Comment by bradleydamato** [comment]
@rakshith91 thanks! I've already started doing this and will be able to finish tomorrow (at least with the dict-checks in the proper places (I used `isinstance` instead of the `type(x) == dict` check I used above)). I will have to write tests after that (I may have some questions on that, but we'll see) and also modify type-hinting (something I may also have questions regarding, but I may just take my best shot and see what the review yields). 

One quick question: in aio and standard ServiceBus, there is a class `AutoLockRenewer` with the method `register` that takes the argument `renewable` that is of type `Union[ReceivedMessage, ServiceBusSession]`.  Given that this argument can take an object of either type, and we do not want to do any client-side validation – I'm curious what you think the best move would be for this specific circumstance? 

Lastly, is this change planned for the November release? If so, do you have a timeline for that? Best,Bradley

**Comment by rakshith91** [comment]
@bradleydamato let's not apply this to the `register` method. This mostly applies to methods like `update` and `send`.
I think it'll be easier to discuss type hinting specifics etc. once the pr is open. broadly, it'd be something like this.

```
Union[Dict, Model]
```

Yes, it's planned for the November release.

**Comment by rakshith91** [comment]
Just want to be explicit - it's planned for the November release but please don't feel any pressure. It's okay if you need more time

**Comment by bradleydamato** [comment]
@rakshith91 thank you for being explicit! I have started the PR here https://github.com/Azure/azure-sdk-for-python/pull/14807

These are all of the planned changes as of now. I will be able to begin writing tests for these this afternoon/early evening. I did not modify the type-hinting, as I am new to the usage of type-hinting systems and I figure it may be straight forward for you to recommend changes in the PR. 

Please let me know if you have any change suggestions, or if you think there are methods I missed (I tried to be thorough).

**Comment by KieranBrantnerMagee** [comment]
(Quickly giving context on the sprint update above: Not related to the work itself, this seems to be moving along nicely, we're just putting this in Feb only as a denotation of "not a blocker for GA, can come in incrementally after safely".  Again, take this as no feedback on the good work being done here, and if we get this in before then all the better, just making the lack-of-pressure clear to help the powers that be visualize priorities better.

**Comment by bradleydamato** [comment]
@KieranBrantnerMagee @rakshith91 I appreciate both of you being explicit with the lack-of-pressure at hand. I am currently in the midst of a semi-severe health situation and may not be able to contribute as much time as I normally would for next couple of weeks. Most recently, I've both made good progress but have also hit a few bumps:

Issue 1:
In testing the optional kwarg-params for updates, I have been able to make changes that allow for this functionality. The issue I am running into is properly testing this within the test suite. 

My local testing script has been the following: 
```
from azure.identity import DefaultAzureCredential
import azure.servicebus as ServiceBus
import azure.servicebus.management as management

DefaultCredential = DefaultAzureCredential()

SBAdmin_client = management.ServiceBusAdministrationClient("NameOfStandardTierNameSpace.servicebus.windows.net",DefaultCredential)

queue = SBAdmin_client.get_queue("queuetest")

for key,val in queue.items():
    print(key,val)

SBAdmin_client.update_queue(queue,max_delivery_count=21)

queue = SBAdmin_client.get_queue("queuetest")

print("_____________________________")

for key,val in queue.items():
    print(key,val)
```

And the output of this script has been the following: 
```
name queuetest
authorization_rules []
auto_delete_on_idle 10675199 days, 2:48:05.477539
dead_lettering_on_message_expiration False
default_message_time_to_live 10675199 days, 2:48:05.477539
duplicate_detection_history_time_window 0:10:00
availability_status Available
enable_batched_operations True
enable_express False
enable_partitioning False
lock_duration 0:01:00
max_delivery_count 12
max_size_in_megabytes 1024
requires_duplicate_detection False
requires_session False
status Active
forward_to None
user_metadata None
forward_dead_lettered_messages_to None
_____________________________
name queuetest
authorization_rules []
auto_delete_on_idle 10675199 days, 2:48:05.477539
dead_lettering_on_message_expiration False
default_message_time_to_live 10675199 days, 2:48:05.477539
duplicate_detection_history_time_window 0:10:00
availability_status Available
enable_batched_operations True
enable_express False
enable_partitioning False
lock_duration 0:01:00
max_delivery_count 21 #NOTE THE CHANGE HERE, UPDATE HAS WORKED 
max_size_in_megabytes 1024
requires_duplicate_detection False
requires_session False
status Active
forward_to None
user_metadata None
forward_dead_lettered_messages_to None
```

When trying to write a new test in the test/test_mgmt_queues.py file, with the following:
```
@pytest.mark.liveTest
    @CachedResourceGroupPreparer(name_prefix='servicebustest')
    @CachedServiceBusNamespacePreparer(name_prefix='servicebustest')
    def test_mgmt_queue_update_kwarg(self, servicebus_namespace_connection_string, **kwargs):
        mgmt_service = ServiceBusAdministrationClient.from_connection_string(servicebus_namespace_connection_string)
        clear_queues(mgmt_service)
        queue_name = "fjrui"
        queue_description = mgmt_service.create_queue(queue_name)
        try:
            # Try updating one setting.
            mgmt_service.update_queue(queue_description,max_delivery_count=21)
            queue_description = mgmt_service.get_queue(queue_name)
            assert queue_description.max_delivery_count == 21

        finally:
            mgmt_service.delete_queue(queue_name)
```

I get the following error: 
```
ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x111df0c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
```

I think this error largely stems from my lack of familiarity with the test-suite, are there any docs available for getting up-to-speed on this? If it is something more apparent please let me know :) 

Issue 2:

I've found that doing a 'bare-update' (an update to a queue without passing new values anywhere) fails on Basic-tier Service Bus Namespaces. For example:

```
from azure.identity import DefaultAzureCredential
import azure.servicebus as ServiceBus
import azure.servicebus.management as management
DefaultCredential = DefaultAzureCredential()

SBAdminClient = management.ServiceBusAdministrationClient("ExampleBasicNameSpace.servicebus.windows.net",DefaultCredential)

queue = SBAdminClient.get_queue("queuetest")
print(queue)
SBAdminClient.update_queue(queue)
queue = SBAdminClient.get_queue("queuetest")
print(queue)
```

fails with the following:
```
azure.core.exceptions.HttpResponseError: SubCode=40000. The property 'AutoDeleteOnIdle' cannot be changed because the namespace 'servicebussdkdictreptest' is using 'Basic' tier.
Parameter name: AutoDeleteOnIdle. TrackingId:12688c4e-2648-4a29-9f14-31be77f2a55b_G4, SystemTracker:ExampleBasicNameSpace.servicebus.windows.net:queuetest, Timestamp:2020-10-29T01:05:13
```
Given that `AutoDeleteOnIdle` was not modified this seems like problematic behavior? I'm curious to hear what either of you thinks (perhaps this is expected behavior).  

Again, thank you each of you for your patience with me on this issue! My short time working on this project has already taught me a ton!

**Comment by rakshith91** [comment]
Hey @bradleydamato I hope you are doing fine and apologies for the later reply.
I can take a look at these issues if you can push the changes to a branch

**Comment by rakshith91** [comment]
Hi @bradleydamato , just checking how things are going
