### ISSUE TITLE
[ServiceBus] Attempt to remove public-export of ServiceBusSession without breaking completion or docs.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14337]
**Is your feature request related to a problem? Please describe.**
Currently we export ServiceBusSession.  The user should never need to instantiate or use this class on its own, however, it is used for completion and docs.

**Describe the solution you'd like**
See if there's a way we can remove this public export while still allowing proper doc linkability and IDE completion.

**Describe alternatives you've considered**
If we need to keep the export, we can, but let's make sure we have a good reason to as it's a potential (if small) avenue to trip up a user.

**Comment by yunhaoling** [comment]
There're ways to hide it, but I think neither of them would be better than simply leaving as it is now.

- Making it private, exposing private class on public api reference by tweaking shpinx doc  structure files. This approach is a bit self-contradictory, exposing private things on public docs.
- Introduce abstract session class, expose the abstract class (while hide the real on) which user can't instantiate, along with the docs. This approach I think is over-killing.

Furthermore, It's not only the ServiceBusSession that users should not instantiate by themselves directly, ServiceBusReceivedMessage, ServiceBusMessageBatch also have the same issue. And we really can't stop people from doing "stupid" things.

On the otherside, keeping the public export would help build users' own type hint and we could do some docstring saying that "session should not be instantiated directly, plz access it by sessionful receiver"

------

as OOB discussion with @KieranBrantnerMagee , we agreed on keeping the public export and I will add docstring in the session class saying that "this class shouldn't be instantiated directly"
