### ISSUE TITLE
[Servicebus] Docstring review and bolstering pre-GA

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14341]
pre-GA fit-and-finish.

Review all of our docstrings.  Ensure text is clear, accurate, up-to-date and comprehensive.

Things to focus on:
- are all params covered?
- rval and returns? (both defined type and description)
- custom errors being thrown?
- typedefs in all the places? (both # type: and docstring types)

**Comment by yunhaoling** [comment]
I'm closing this issue as we have GAed.
we could open new issues when we find something that needs to be improved.
