### ISSUE TITLE
[Tables] Use AzureTestCase instead of AzureMgmtTestCase

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-python#14352]
The test classes in `testcase.py` and `asynctestcase.py` inherit from the management plane test class.

**Comment by bradleydamato** [comment]
Hi @seankane-msft ; it looks like a change only need to be made in `testcase.py` as `asynctestcase.py` imports `TableTestCase` from the former. 

I've run the tox tests and here are the results:
![image](https://user-images.githubusercontent.com/53579156/95790937-5384ff80-0cae-11eb-93bb-44e62239916e.png)

Additionally, here is a PR: https://github.com/Azure/azure-sdk-for-python/pull/14443
