### ISSUE TITLE
Impossible to print custom entity values  - azure-data-tables

### ISSUE THREAD

**Issue by Akhofreeze** [Azure/azure-sdk-for-python#14384]
- **Package Name**: Azure Data Tables
- **Package Version**:  Latest
- **Operating System**: CentOs8
- **Python Version**:  3.8

**Describe the bug**
After many tries I can't print my custom values. They were printed as "<azure.data.tables._entity.EntityProperty object at 0x7f023d348080>"

**To Reproduce**
1. Use this https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/tables/azure-data-tables/samples/sample_update_upsert_merge_entities.py

**Expected behavior**
I want to print my entity values in order to get a value & increment it for finally update it.

**Comment by kaerm** [comment]
Thanks @Akhofreeze for reporting this, @seankane-msft can you take a look at this?

**Comment by seankane-msft** [comment]
You can't "print" an entity but you can print the values contained with the entity by doing: 
```
keys = my_entity.keys()
for key in keys:
    print(f"Key: {key}\tValue: {my_entity[key]}")
```
This will let you print out the values but I'm a bit confused by what you mean with "print my entity values in order to get a value & increment it for finally update it". The `EntityProperty` is a wrapper on the Python `dict` class so anything you normally do with `dict`. 

@Akhofreeze can you elaborate a bit what your goal is?

**Comment by Akhofreeze** [comment]
Hi ! Thx for you answer @seankane-msft .

Yeah I understood that EntityProperty worked like dict but when I get my entity by:
```
def table_search(self):
    try:
        entity = self.get_entity(subId,name)
        print(entity)
        return entity
    except Exception as err:
        print("Entity not found")
```
And try to print all keys values, the fiel that I added in my entity can't be printed.
```
 entity = table_search(table_service)
        keys = entity.keys();
        for key in keys:
            print(f"Key: {key}\tValue: {entity[key]}")`
```
Result: 
```
Key: PartitionKey	Value: 049118e2-4814-401b-a34d-a67a35abc5a9
Key: RowKey	Value: test-unusedvm1
**Key: nDays Value: <azure.data.tables._entity.EntityProperty object at 0x7f8244f7eeb8>**
```
Just want to get the nDays value & not the object, that's my **goal.**

**Comment by seankane-msft** [comment]
If the `nDays` property is not available in the entity can you try using the `upsert_entity`, `merge_entity`, or `update_entity` methods to insert the `nDays` property again to verify that it is available in the entity. After an update try to retrieve the entity again and run the above code again.
