### ISSUE TITLE
how to know if BlobClient overwrites

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#14391]
- **Package Name**: storage
- **Package Version**: 12.5.0
- **Operating System**: OSX
- **Python Version**: 3.7

I am looking at `BlobClient.upload_blob` method and I have two questions:

* how can I know if the blob has been overwritten if I set `overwrite=True`?
* Is there any docs about what is in the dictionary that is returned by the `upload_blob` method?

**Comment by xiafu-msft** [comment]
Hi @andrea-cassioli-maersk 

Thanks for reaching out.

1. If there is an existing blob, and you call upload_blob with overwrite=True, as long as there's no exception thrown, the existing blob is overwritten. If you want to make sure the existing blob is overwritten, creation time, etag or blob version (if you have this feature enabled) can help.
2. Here are the response headers for reference https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list#response-headers remove `x-ms-` if it's there and replace `-` with `_` then you can get the keys in the dictionary

Let me know if you need any info!

**Comment by andrea-cassioli-maersk** [comment]
Thanks @xiafu-msft 
As for (1), we are fine with the behaviour, but in our use case if a blob gets overwritten we would like to have some logging. That's way we would like a way to easily now if that happens. I guess then that using `Last-Modified` is our best chance.

**Comment by xiafu-msft** [comment]
Hi @andrea-cassioli-maersk 

Probably etag can also help, everytime there's an write operation, the etag will change.

**Comment by andrea-cassioli-maersk** [comment]
Thanks @xiafu-msft . I have also notice there is a `exists` method indeed. But I would rather avoid unnecessary requests, given that my only purpose is logging. Checking Last-Modified or etag seems to be enough. However, I think it would be nice to have a flag in the function return with this information, like `overwritten=true`.
