### ISSUE TITLE
Synchronizing blobs in Azure cloud storage with local filesystem (like azcopy's sync)

### ISSUE THREAD

**Issue by bsherifi** [Azure/azure-sdk-for-python#14433]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.5.0
- **Operating System**: Ubuntu 18.04 LTS
- **Python Version**: 3.6.9

**Describe the bug**

I listed this issue as a bug, although it is not one, but it's a feature that I either couldn't find in the Azure SDK for Python, no matter how deep I went in documentation, so please bare with me.

We have been using **azcopy** for manipulating with files in Azure storage till now, but now we are using the Python SDK to do so. The thing is, **azcopy** has a feature that let's you sync your files in Azure storage with the local filesystem and I wanted to know if there is a way to do the same thing with the Python SDK. I want the same functionality **azcopy sync** command has, but for the Python SDK. If that does exist, please point me at it so I can start using it. 

**To Reproduce**
N/A

**Expected behavior**

I wrote the expected behavior on the bug description above.

**Screenshots**

**Additional context**

**Comment by ArditHalimi** [comment]
I have same issue

**Comment by bsherifi** [comment]
@xiafu-msft Couldn't help but notice you added the _**feature-request**_ label to this issue. Are you trying to say that this doesn't exist as of the current version of Azure Python SDK? An output would be truly appreciated. Thank you.

**Comment by tasherif-msft** [comment]
Hi @bsherifi, this feature does not currently exist. Currently you would have to manually download and upload those files. However, we have had a discussion about your suggestion and it seems like an interesting feature to add. We will have further discussions internally and will update this issue once we open a PR or have any updates :)

**Comment by xiafu-msft** [comment]
Hi @bsherifi 

Thanks for reaching out! 
Just curious, have you thought about calling azcopy command in python script? Currently Python SDK doesn't support that feature.

**Comment by bsherifi** [comment]
Thanks for your reply @tasherif-msft. It will be so good to have a feature like that in order to completely replace azcopy with Python functionalities considering there's a SDK for it. Looking forward to this one.

@xiafu-msft Thanks for your reply too. And, yes, I actually have a solution like the one you mentioned but I was thinking to make something completely in Python and independent from azcopy. Until you and your team decide to create a feature like the one I requested, I'm gonna stick with your suggestion.

**Comment by tasherif-msft** [comment]
Hi @bsherifi, we have had some internal discussions regarding this. Currently it will not be in our short term plans to implement azcopy-like feature such as sync within our SDK. However I will mark this as a feature request and will leave open for our long term backlog. Sorry for the inconvenience!
Let me know if you need anymore help :)

**Comment by tasherif-msft** [comment]
Hi @bsherifi I will close this issue as there is a duplicate https://github.com/Azure/azure-sdk-for-python/issues/6306 to track.
