### ISSUE TITLE
[ServiceBus] Discuss how we want to handle assumed/specified encodings across the various string-taking but byte-allowing fields.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14447]
```python
azure.servicebus.ServiceBusSession.__init__.param(encoding
```

**Context from apiview discussion**

ramya-rao-a
9 weeks ago

What is this encoding for? How come it does not make an appearance elsewhere?
KieranBrantnerMagee
8 weeks ago

It technically makes an appearance elsewhere, just typically hidden in kwargs and not advertised since it's deep control functionality. In this case it's to control the encoding when state is set or fetched. (and as established above we don't expect a user to consume this initializer)
ramya-rao-a
6 weeks ago

What are the other places where one can set encoding?
KieranBrantnerMagee
47 minutes ago

Message kwargs, defaults to UTF-8.
KieranBrantnerMagee
just now

We'll be removing the docstrings to let this float until we settle on a cross-SDK decision on this. Adam has created an issue to track this as a post-GA discussion.

**Comment by yunhaoling** [comment]
let's wait for customer feedback.
