### ISSUE TITLE
[Schema Registry] Integration with IoT Hub

### ISSUE THREAD

**Issue by ederfdias** [Azure/azure-sdk-for-python#14484]
**Is your feature request related to a problem? Please describe.**
I am trying to understand how to integrate this feature with IoT Hub. There any integration with IoT hub?

**Describe the solution you'd like**
I am looking for a way to send message from a device with a specific schema and validated that message by routing to a event hub.

**Describe alternatives you've considered**
I know that is possible to achieve something similar to Kafka

Thanks a lot

**Comment by yunhaoling** [comment]
hey @ederfdias ,

currently schema registry is a standalone preview library, it only provides the basic ability to register/retrieve a schema.

I assume the "integration" you refer to is about encoding/decoding data.

I'm sorry that we don't have a sample on how to integrate with IotHub, but we do have a separate package called [azure-schemaregistry-avroserializer](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/schemaregistry/azure-schemaregistry-avroserializer) which integrates with the schema registry library and provides the ability to encode/decode avro data, and it also has [samples on integration with the Event Hub](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/schemaregistry/azure-schemaregistry-avroserializer/samples). It should be fairly easy for you to mitigate the samples into IoT Hub.

let me know whether my response answers your question, I would be glad to provide any kind of help to you.

**Comment by ederfdias** [comment]
Thanks @yunhaoling you answer the question for sure.

**Comment by yunhaoling** [comment]
great! @ederfdias I'm closing the issue now but feel free to reach out to me if you have more question.
