### ISSUE TITLE
Result: Failure Exception: AttributeError: 'ManagedIdentityCredential' object has no attribute 'signed_session'

### ISSUE THREAD

**Issue by RanjithMahadevan** [Azure/azure-sdk-for-python#14499]
- **Package Name**: 
from azure.identity import ManagedIdentityCredentia
from azure.mgmt.web import WebSiteManagementClient

- **Package Version**: 
azure-identity ==1.4.1
azure-mgmt-web==0.48.0

- **Operating System**:
Azure Function App Linux

- **Python Version**: 
3.8.5

**Describe the bug**
trying to connect web app using managed identity auth class from azure function, when i execute my code i'm getting below error.
**Result: Failure Exception: AttributeError: 'ManagedIdentityCredential' object has no attribute 'signed_session' Stack: **

**To Reproduce**
```
import logging
from azure.identity import ManagedIdentityCredential
from azure.mgmt.resource import SubscriptionClient
import azure.functions as func
from azure.mgmt.web import WebSiteManagementClient
 
def main(req: func.HttpRequest) -> func.HttpResponse:
 logging.info('Python HTTP trigger function processed a request.')
 credentials = ManagedIdentityCredential()
 subscription_client = SubscriptionClient(credentials)
 subscription = next(subscription_client.subscriptions.list())
 subscription_id = subscription.subscription_id
 
 web_app_client = WebSiteManagementClient(credentials=credentials, subscription_id=subscription_id)
 
 for i in web_app_client.web_apps.list():
 print ("===================")
 print (i.resource_group)
 print (i.repository_site_name)
 print ("===================")
 get_auth = web_app_client.web_apps.get_auth_settings(i.resource_group, i.repository_site_name)
 if get_auth.enabled == False:
 print ("Auth Method is not enabled on: {} Web APP, Auth method will be enabled!!".format(i.repository_site_name))
 print (get_auth.enabled)
 web_app_client.web_apps.update_auth_settings(i.resource_group, i.repository_site_name, site_auth_settings=SiteAuthSettings(enabled=True, default_provider='AzureActiveDirectory'))
 print ("Auth Method is now enabled on: {} Web APP!!".format(i.repository_site_name))
 else:
 print ("Auth Method is Already enabled on: {} Web App".format(i.repository_site_name))
 name = req.params.get('name')
 if not name:
 try:
 req_body = req.get_json()
 except ValueError:
 pass
 else:
 name = req_body.get('name')
 
 if name:
 return func.HttpResponse(f"Hello, {name}. This HTTP triggered function executed successfully.")
 else:
 return func.HttpResponse(
 "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.",
 status_code=200
```

**Expected behavior**
This function will trigger based on http request using managed identity auth method it connect azure web app and enable authentication of the webapp if not enabled 

**Screenshots**

**Additional context**
Complete error message:
```
Result: Failure Exception: AttributeError: 'ManagedIdentityCredential' object has no attribute 'signed_session' Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 343, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func return func(**params) File "/home/site/wwwroot/web-app-auth-enable/__init__.py", line 19, in main for i in web_app_client.web_apps.list(): File "/home/site/wwwroot/.python_packages/lib/site-packages/msrest/paging.py", line 143, in __next__ self.advance_page() File "/home/site/wwwroot/.python_packages/lib/site-packages/msrest/paging.py", line 129, in advance_page self._response = self._get_next(self.next_link) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/mgmt/web/v2019_08_01/operations/_web_apps_operations.py", line 95, in internal_paging response = self._client.send(request, stream=False, **operation_config) File "/home/site/wwwroot/.python_packages/lib/site-packages/msrest/service_client.py", line 336, in send pipeline_response = self.config.pipeline.run(request, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/msrest/pipeline/__init__.py", line 197, in run return first_node.send(pipeline_request, **kwargs) # type: ignore File "/home/site/wwwroot/.python_packages/lib/site-packages/msrest/pipeline/__init__.py", line 150, in send response = self.next.send(request, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/msrest/pipeline/requests.py", line 65, in send self._creds.signed_session(session)
```
**Error Screen Shot**
<img width="1784" alt="azure-function-web-app" src="https://user-images.githubusercontent.com/50738041/95997694-f1520900-0e2b-11eb-94e5-889e262d2d3e.png">

**Comment by RanjithMahadevan** [comment]
please advise me the right option to achieve the above use case

**Comment by chlowell** [comment]
WebSiteManagementClient doesn't support credentials from azure-identity. It expects an [msrestazure authentication class](https://docs.microsoft.com/python/api/msrestazure/msrestazure.azure_active_directory?view=azure-python). There are a couple ways you can move forward:
1. Use [msrestazure.azure_active_directory.MSIAuthentication](https://docs.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_active_directory.msiauthentication?view=azure-python) instead of ManagedIdentityCredential
1. Use [AzureIdentityCredentialWrapper](https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py) to wrap ManagedIdentityCredential

AzureIdentityCredentialWrapper is convenient if your application also uses clients expecting azure-identity credentials. If your application uses only WebSiteManagementClient, or uses only clients expecting the msrestazure API, I'd suggest using MSIAuthentication.

**Comment by RanjithMahadevan** [comment]
@chlowell 
Thanks for the information!!
is it possible to use MSIAuthentication in function app if managed identity enabled ?
if yes, can you help me with some example, please.
Thanks,
Ranjith

**Comment by RanjithMahadevan** [comment]
@chlowell 
when i use MSIAuthenication i'm getting below error.

```
2020-10-14 11:30:52.095
Result: Failure Exception: AttributeError: 'MSIAuthentication' object has no attribute 'get_token' Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 343, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func return func(**params) File "/home/site/wwwroot/web-app-auth-enable/__init__.py", line 15, in main subscription = next(subscription_client.subscriptions.list()) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/paging.py", line 122, in __next__ return next(self._page_iterator) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/paging.py", line 74, in __next__ self._response = self._get_next(self.continuation_token) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_subscriptions_operations.py", line 224, in get_next pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 211, in run return first_node.send(pipeline_request) # type: ignore File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 71, in send response = self.next.send(request) [Previous line repeated 1 more time] File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/policies/_retry.py", line 436, in send response = self.next.send(request) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 69, in send _await_result(self._policy.on_request, request) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_tools.py", line 29, in await_result result = func(*args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request self._token = self._credential.get_token(*self._scopes)
```
Below is the code which i used in function app.

```
import logging
from msrestazure.azure_active_directory import MSIAuthentication
from azure.mgmt.resource import SubscriptionClient
import azure.functions as func
from azure.mgmt.web import WebSiteManagementClient

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    credentials = MSIAuthentication()
    subscription_client = SubscriptionClient(credentials)
    subscription = next(subscription_client.subscriptions.list())
    subscription_id = subscription.subscription_id

    web_app_client = WebSiteManagementClient(credentials=credentials, subscription_id=subscription_id, api_version=None, base_url=None, profile='default')

    for i in web_app_client.web_apps.list():
        print ("===================")
        print (i.resource_group)
        print (i.repository_site_name)
        print ("===================")
        get_auth = web_app_client.web_apps.get_auth_settings(i.resource_group, i.repository_site_name)
        if get_auth.enabled == False:
            print ("Auth Method is not enabled on: {} Web APP, Auth method will be enabled!!".format(i.repository_site_name))
            print (get_auth.enabled)
            web_app_client.web_apps.update_auth_settings(i.resource_group, i.repository_site_name, site_auth_settings=SiteAuthSettings(enabled=True, default_provider='AzureActiveDirectory'))
            print ("Auth Method is now enabled on: {} Web APP!!".format(i.repository_site_name))
        else:
            print ("Auth Method is Already enabled on: {} Web App".format(i.repository_site_name))
    name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')

    if name:
        return func.HttpResponse(f"Hello, {name}. This HTTP triggered function executed successfully.")
    else:
        return func.HttpResponse(
            "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.",
            status_code=200
        )
```

**Comment by chlowell** [comment]
Now you have the opposite problem: the newest azure-mgmt-resource (15.x) expects azure-identity credentials. Your options then are to continue with MSIAuthentication and an older version of azure-mgmt-resource that can use it (that would be 10.x) or try [AzureIdentityCredentialWrapper](https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py) like this:

```py
from azure.identity import ManagedIdentityCredential

credential = ManagedIdentityCredential()
subscription_client = SubscriptionClient(credential)  # (assuming azure-mgmt-resource 15.x)

wrapped_credential = AzureIdentityCredentialWrapper(credential)
web_app_client = WebSiteManagementClient(credentials=wrapped_credential, subscription_id=subscription_id)
```

**Comment by RanjithMahadevan** [comment]
@chlowell 
As i mentioned above i'm getting error even i use  MSIAuthentication with azure-mgmt-resource (15.x), you mean MSIAuthentication also doesn't work for with  azure-mgmt-resource (15.x) ?

If i use below methods in my code should i place AzureIdentityCredentialWrapper file also part of my code ?
```
from azure.identity import ManagedIdentityCredential

credential = ManagedIdentityCredential()
subscription_client = SubscriptionClient(credential)  # (assuming azure-mgmt-resource 15.x)

wrapped_credential = AzureIdentityCredentialWrapper(credential)
web_app_client = WebSiteManagementClient(credentials=wrapped_credential, subscription_id=subscription_id)
```

**Comment by chlowell** [comment]
> As i mentioned above i'm getting error even i use MSIAuthentication with azure-mgmt-resource (15.x), you mean MSIAuthentication also doesn't work for with azure-mgmt-resource (15.x) ?

That's correct. The latest major version of azure-mgmt-resource, 15, doesn't work with msrestazure credentials like MSIAuthentication. It expects a credential from azure-identity such as ManagedIdentityCredential. The reverse is true for the prior major version of azure-mgmt-resource, 10. AzureIdentityCredentialWrapper wraps an azure-identity credential with the msrestazure credential API. You're dealing with this matrix:
 
package|msrestazure credentials|azure-identity credentials|AzureIdentityCredentialWrapper
---|---|---|---
azure-mgmt-resource 15|❌|✔️|❌
azure-mgmt-resource 10|✔️|❌|✔️
azure-mgmt-web|✔️|❌|✔️


> If i use below methods in my code should i place AzureIdentityCredentialWrapper file also part of my code ?
> 

Yes. The code is available on GitHub but not published to PyPI.

**Comment by RanjithMahadevan** [comment]
> > As i mentioned above i'm getting error even i use MSIAuthentication with azure-mgmt-resource (15.x), you mean MSIAuthentication also doesn't work for with azure-mgmt-resource (15.x) ?
> 
> That's correct. The latest major version of azure-mgmt-resource, 15, doesn't work with msrestazure credentials like MSIAuthentication. It expects a credential from azure-identity such as ManagedIdentityCredential. The reverse is true for the prior major version of azure-mgmt-resource, 10. AzureIdentityCredentialWrapper wraps an azure-identity credential with the msrestazure credential API. You're dealing with this matrix:
> 
> package	msrestazure credentials	azure-identity credentials	AzureIdentityCredentialWrapper
> azure-mgmt-resource 15	❌	✔️	❌
> azure-mgmt-resource 10	✔️	❌	✔️
> azure-mgmt-web	✔️	❌	✔️
> > If i use below methods in my code should i place AzureIdentityCredentialWrapper file also part of my code ?
@chlowell  Thanks , AzureIdentityCredentialWrapper is working for me , i hope this is a work around .
> Yes. The code is available on GitHub but not published to PyPI.
> 
> @changlong-liu is migrating to track 2 on the roadmap for azure-mgmt-web?
I hope near future azure-identity will support azure-mgmt-web clients isn't it ?

**Comment by changlong-liu** [comment]
Hi @chlowell , @RanjithMahadevan ,

Yes, azure-mgmt-web will have a preview release as Track2 in near future.

**Comment by RanjithMahadevan** [comment]
Thank you !! @chanezon  @chlowell

**Comment by chlowell** [comment]
I'll close this issue as resolved then, thank you for opening it.

**Comment by chlowell** [comment]
[AzureIdentityCredentialAdapter](https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py) is for adapting azure-identity credentials to the (deprecated) msrestazure API which had `set_token` and `signed_session` methods. That AttributeError implies you passed an azure-identity credential to a client expecting the azure-identity API (`get_token`). In that case you don't need the adapter, just pass the credential itself.
