### ISSUE TITLE
ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

### ISSUE THREAD

**Issue by ShaheenPerveen** [Azure/azure-sdk-for-python#14498]
- **Package Name**: 
azure-storage-blob
azure-mgmt-storage
- **Package Version**: 
azure-storage-blob==12.0.0
azure-mgmt-storage==10.0.0
- **Operating System**:
MacOS
- **Python Version**: 
3.7

**Describe the bug**
I am trying to list and download all blobs using azure-sdk-python from a container belonging to a storage account. 
I am referring to the script: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob.
Below is the code snippet:
"""
from __future__ import print_function
import os
import sys
import azure
from azure.storage.blob import ContainerClient
from azure.storage.blob import BlobServiceClient

os.environ['AZURE_STORAGE_CONNECTION_STRING'] = "DefaultEndpointsProtocol=https;AccountName=xxxxxxx;AccountKey=xxxxxxxxxxxxxxxxx"

try:
    CONNECTION_STRING = os.environ['AZURE_STORAGE_CONNECTION_STRING']

except KeyError:
    print("AZURE_STORAGE_CONNECTION_STRING must be set.")
    sys.exit(1)

container = ContainerClient.from_connection_string(CONNECTION_STRING, container_name="xxxxxx")
blob_service_client = BlobServiceClient.from_connection_string(CONNECTION_STRING)
local_file_path = "/Users/sp/Documents/azure-blob/blob_download/"

blob_list = container.list_blobs()
for blob in blob_list:
    print(blob.name + '\n')
    local_file_name = local_file_path + blob.name
    blob_client = blob_service_client.get_blob_client(container="xxxxxx", blob=blob.name)
    with open(local_file_name, "wb") as download_file:
        download_file.write(blob_client.download_blob().readall())
"""
I am getting the below error:
**azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)**

I have checked my SSL certificates, they seem alright. Also tried: pip install -U certifi
This same script is working on my colleagues laptop. Please help me out with this issue.

**Comment by amishra-dev** [comment]
Can you please check if you have the fiddler/wireshark or a cert for any other network monitoring software installed? This is a common error when that is true.

**Comment by ShaheenPerveen** [comment]
@amishra-dev  I use pulse secure to connect to my org's vpn. I dont think I have anything installed. One of my colleague is able to run the same script on their system. 
Could you please help me with checking if there is any additional cert for any other network monitoring software installed?
I am not sure how to confirm this.
Also I checked SSL cert on my and my colleagues system, they are the same

**Comment by ShaheenPerveen** [comment]
@tasherif-msft Were you able to identify the cause of this issue? Please let me know the resolution. I am kind of stuck because of this

**Comment by xiafu-msft** [comment]
It's most likely not a problem in the SDK itself. Please refer to this relevant [post](https://stackoverflow.com/a/42334357/4179859).
