### ISSUE TITLE
Snapshots for Datalake Gen2

### ISSUE THREAD

**Issue by frammnm** [Azure/azure-sdk-for-python#14527]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.5.0
- **Operating System**: Windows 10
- **Python Version**: 3.6.8

**Describe the bug**

Im trying to create a blob snapshot in my Azure Data Lake Storage Gen2 with the azure-storage-blob sdk but i get the following error even when it says in the following [link](https://docs.microsoft.com/en-us/azure/storage/blobs/snapshots-overview) that its available as  a preview feature. I also tried using azure-storage-file-datalake but that library doesn't even have a snapshot functionality as far as i can see. It seems the library to do it is this one but it doesn't seem to be updated to manage the blob inside datalake gen2, am i wrong? is there a third library to do it? most examples i find online are using this one. 

Traceback (most recent call last):
  File "C:\Users\famartinez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\storage\blob\_blob_client.py", line 1557, in create_snapshot
    return self._client.blob.create_snapshot(**options) # type: ignore
  File "C:\Users\famartinez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\storage\blob\_generated\operations\_blob_operations.py", line 2068, in create_snapshot
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'Specified feature is not yet supported for hierarchical namespace accounts.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\snapshot_test.py", line 49, in <module>
    snapshot_blob = blob_client.create_snapshot()
  File "C:\Users\famartinez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\famartinez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\storage\blob\_blob_client.py", line 1559, in create_snapshot
    process_storage_error(error)
  File "C:\Users\famartinez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: Specified feature is not yet supported for hierarchical namespace accounts.
RequestId:afeaa687-101e-005c-0bc1-a2977b000000
Time:2020-10-15T07:07:44.9464535Z
ErrorCode:FeatureNotYetSupportedForHierarchicalNamespaceAccounts
Error:None
FeatureName:Snapshots

**To Reproduce**
1. Have a datalke gen2
2. create a blob inside the storage
3. try to create a snapshot 

**Expected behavior**
The expected behavior is that if this library manages blobs and i want to do a blob snapshop in a datalake gen2 this library would support it.

**Comment by tasherif-msft** [comment]
Hi @frammnm, hierarchical namespace accounts are a feature of Datalake Gen2 (i.e, `azure-storage-file-datalake` not the blob package). 

You are correct, the snapshot feature is not currently available in the datalake package as it will be released for the Python SDK at a future date. It is however currently available for preview on the service side as announced here: https://azure.microsoft.com/en-us/updates/file-snapshots-for-azure-data-lake-storage-now-in-public-preview/. Please note, you must submit the form in that link in order to enable this feature on your account. 

You can however create a snapshot on the regular blob service using the `azure-storage-blob` package, which will not have HNS.

**Comment by frammnm** [comment]
```
from azure.storage.blob import BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

#List containers 
try : 
	all_containers = blob_service_client.list_containers()
	for container in all_containers:
	       print(container['name'], container['metadata'])
except:
	print("Something went wrong listing containers")

# Get a BlobClient for a specific blob
blob_client = blob_service_client.get_blob_client(container="snapshot", blob="my_blob_test")

# # [START create_blob_snapshot]
# # Create a read-only snapshot of the blob at this point in time
snapshot_blob = blob_client.create_snapshot()

# # Get the snapshot ID
for k in snapshot_blob.keys():
	print(k, snapshot_blob[k])
```

This snipped was based on a example found on github, can't remember the link at the moment. I filled the form thank you, i want to test the functionality to see if it can be applied in a project we are working on, i have been trying to use the API REST i have been following this documents: this for authentication [storage api rest authentication](https://docs.microsoft.com/en-us/azure/storage/common/storage-rest-api-auth?toc=/azure/storage/blobs/toc.json#download-the-sample-application) to use this endpoint [Blob snapshot endpoint](https://docs.microsoft.com/en-us/rest/api/storageservices/snapshot-blob), i was working on this but seems like an overly complex authentication scheme, i first used this one [rest-api-authentiation](https://docs.microsoft.com/en-us/rest/api/azure/#create-the-request) but it doesn't seem to work with the storage services. How exactly could i approach this snapshot functionality? is there a document that describes how to make a simple implementation?

**Comment by xiafu-msft** [comment]
Hi @frammnm 

Thanks for reporting this! We will add this feature for azure-storage-file-datalake package.
For the problem you met, that's probably the feature is only enabled on some regions, not all service hosts has this feature, we will investigate and get back to you.

**Comment by frammnm** [comment]
> Hi @frammnm
> 
> Thanks for reporting this! We will add this feature for azure-storage-file-datalake package.
> For the problem you met, that's probably the feature is only enabled in some regions, not all service hosts has this feature, we will investigate and get back to you.

Thanks, anyway to test an implementation is welcome.

**Comment by tasherif-msft** [comment]
Hi @frammnm, I believe signing that form should enable you to use this functionality on datalake (I will confirm this as well). However the Python SDK currently does not support snapshots in the datalake package. We will discuss adding this to our SDK.
In the meantime if you have a normal storage account (non-HNS) account and you use the azure-storage-blob package, you should be able to run the code snippet you provided above.
However, if your operations rely on HNS accounts then I will let you know once we have an update regarding the snapshot feature on the datalake package.

**Comment by tasherif-msft** [comment]
Hi @frammnm, I wanted to give you an update: we have created a PR to add creating a snapshot on datalake to our SDK https://github.com/Azure/azure-sdk-for-python/pull/15335.

**Comment by frammnm** [comment]
> Hi @frammnm, I wanted to give you an update: we have created a PR to add creating a snapshot on datalake to our SDK #15335.

That's great! Thanks, i see is still waiting for peer review but when its available i will to a test with it. I think we can close this issue.
