### ISSUE TITLE
AttributeError: Can't get attribute 'XGBoostLabelEncoder'

### ISSUE THREAD

**Issue by mastreips** [Azure/azure-sdk-for-python#14536]
- **Package Name**:  Azure ML
- **Package Version**: 1.16.0
- **Operating System**: Ubuntu 16.04.7 LTS
- **Python Version**: azureml_py36

**Describe the bug**
I get the following error when running : `best_run, fitted_model = run.get_output()`

> AttributeError: Can't get attribute 'XGBoostLabelEncoder' on <module 'xgboost.compat' from '/anaconda/envs/azureml_py36/lib/python3.6/site-packages/xgboost/compat.py'>

**To Reproduce**
1. Run Notebook on AML VM with Python 3.6-AzureML kernel
2. Run AutoML with the following configuration:

from azureml.train.automl import AutoMLConfig:

> automl_settings = {
>     "experiment_timeout_minutes": 60,
>     "experiment_exit_score": 0.92,
>     "primary_metric": 'accuracy',
>     "max_concurrent_iterations": num_nodes, 
>     "max_cores_per_iteration": -1,
>     "enable_dnn": False,
>     "enable_early_stopping": True,
>     "verbosity": logging.INFO,
>     "enable_voting_ensemble": True,
>     "enable_stack_ensemble": False, #conflicts with Onnx
> }
> 
> 
> automl_config = AutoMLConfig(name='AutoML_SDK_Utility_1',
>                              task='classification',
>                              debug_log = 'automl_errors.log',
>                              compute_target = compute_target,
>                              training_data = train_ds,
>                              validation_data = test_ds,
>                              label_column_name='type',
>                              iterations=6,
>                              #n_cross_validations=5, conflicts with validation data and onnx
>                              featurization='auto',
>                              blocked_models = ['LightGBM', 'Averaged Perceptron Classifier'],
>                              enable_onnx_compatible_models = True,
>                              **automl_settings
>                              )
> 
> print("Ready for Auto ML run.")

**Expected behavior**
The expected behavior is to be able to retrieve the best and fitted models from the run.  For example when printing `fitted` attribute, you should get an output like the following (observed on a different model, but same kernel and VM):

> PipelineWithYTransformations(Pipeline={'memory': None,
>                                        'steps': [('datatransformer',
>                                                   DataTransformer(enable_dnn=None,
>                                                                   enable_feature_sweeping=None,
>                                                                   feature_sweeping_config=None,
>                                                                   feature_sweeping_timeout=None,
>                                                                   featurization_config=None,
>                                                                   force_text_dnn=None,
>                                                                   is_cross_validation=None,
>                                                                   is_onnx_compatible=None,
>                                                                   logger=None,
>                                                                   observer=None,
>                                                                   task=None,
>                                                                   working_dir=None))...
>                                                   MaxAbsScaler(copy=True)),
>                                                  ('LogisticRegression',
>                                                   LogisticRegression(C=6866.488450042998,
>                                                                      class_weight=None,
>                                                                      dual=False,
>                                                                      fit_intercept=True,
>                                                                      intercept_scaling=1,
>                                                                      l1_ratio=None,
>                                                                      max_iter=100,
>                                                                      multi_class='multinomial',
>                                                                      n_jobs=-1,
>                                                                      penalty='l2',
>                                                                      random_state=None,
>                                                                      solver='saga',
>                                                                      tol=0.0001,
>                                                                      verbose=0,
>                                                                      warm_start=False))],
>                                        'verbose': False},
>                              y_transformer={},
>                              y_transformer_name='LabelEncoder')

**Screenshots**

**Additional context**

**Comment by cartacioS** [comment]
Hi @mastreips - I suspect you're seeing this error because you do not have XGBoost in your local environment. Can you try to install the necessary packages AND restart your kernel? You can use the run ID to access the previously trained model as you'll lose direct access after restarting the kernel.

In terminal:
`pip install xgboost`
After restarting kernel you can check imports in the notebook:
```
import xgboost
import xgboost.compat
from xgboost.compat import XGBoostLabelEncoder
```

**Comment by cartacioS** [comment]
Hi @mastreips did the proposed solution unblock you?

**Comment by DebFro** [comment]
closing issue, please re-open if the provided solution did not unblock you.
