### ISSUE TITLE
[ServiceBus] Support receiver-based settlement

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14567]
**DECISION MADE AFTER ARCH BOARD MEETING**

https://github.com/Azure/azure-sdk/issues/1884#issuecomment-714252397
> The methods to settle messages and renew their locks are moved from the message to the receiver

------------------

**Context**
Arch board review brought concerns about settlement methods (complete, abandon, etc) being present on Message rather than Receiver; out of making it more than a "data object" and coupling those methods to the receiver lifespan.

**Proposals**
1. Current status: Message.complete(), Message.dead_letter(), etc.
  - Pros: only need to pass message between functions to settle, not a tuple; Logical coupling of message and message-oriented operation; validated via UX studies and T1 to not be an impediment and to align with intuition for where users looked.
  - Cons: hides the fact that complete() utilizes the Receiver links, and thus relies on Receiver being live;  Makes the Message more than just a container for data, which may be inconsistent with paradigms elsewhere.
2. Move settlement to Receiver.  Receiver.complete_message(), Receiver.dead_letter_message(), etc.
  - Pros: Makes settlement clearly a receiver/client-service operation; allows Message to be a data object.
  - Cons: Means a user would have to carry both a receiver and message around to settle; is a novel location for settlement, complicates the surface area of a primary path for doing other operations. (receive itself).  Potentially confuses which message can be settled under which receiver.

**Samples** (Context: arch discussion that surfaced this ended up hinging on how painful the tradeoffs are, these samples attempt to illustrate that; I would call out that in either case the issue compounds for every additional layer added on top of the toy example)

1. **Worker pool scenario.**
 - Proposal 1
```python
def do_work(message):
  for job in JOBS.get(message.subject, []):
    try:
      job(message)
      message.complete()
    except:
      try:
        message.abandon()
      except:
        pass

with client.get_queue_receiver(QUEUE_NAME) as receiver:
  for message in receiver:
    do_work(message)
```
- Proposal 2
```python
def do_work(message, receiver):
  for job in JOBS.get(message.subject, []):
    try:
      job(message, receiver)
      receiver.complete_messages(message)
    except:
      try:
        receiver.abandon_messages(message)
      except:
        pass

with client.get_queue_receiver(QUEUE_NAME) as receiver:
  for message in receiver:
    do_work(message, receiver)
```

2.  **Aggregation scenario**
- Proposal 1
```python
funnel = []

async def receive_from(client, queue_name):
  async with client.get_queue_receiver(queue_name) as receiver:
    async for message in receiver:
     funnel.append(message)

async def run_aggregator():
  for message in funnel:
    print(message)
    message.complete()

async with ServiceBusClient.from_connection_string(CONN_STR) as client:
  await asyncio.gather(run_aggregator(), *[receive_from(client, queue_name) for queue_name in QUEUE_NAMES])
```
- Proposal 2
```python
funnel = []

async def receive_from(client, queue_name):
  async with client.get_queue_receiver(queue_name) as receiver:
    async for message in receiver:
     funnel.append((message, receiver))

async def run_aggregator():
  for message, receiver in funnel:
    print(message)
    receiver.complete_messages(message)

async with ServiceBusClient.from_connection_string(CONN_STR) as client:
  await asyncio.gather(run_aggregator(), *[receive_from(client, queue_name) for queue_name in QUEUE_NAMES])
```

3 **Multi Receiver**
- Proposal 1
```python
with client.get_queue_receiver(QUEUE_NAME) as receiver:
  with client.get_queue_receiver(QUEUE_NAME_2) as receiver_2:
    for message in receiver.receive_messages():
      message.complete()
    for message in receiver_2.receive_messages():
      message.complete()
```

- Proposal 2
```python
with client.get_queue_receiver(QUEUE_NAME) as receiver:
  with client.get_queue_receiver(QUEUE_NAME_2) as receiver_2:
    for message in receiver.receive_messages():
      receiver.complete_messages(message)
    for message in receiver_2.receive_messages():
      receiver_2.complete_messages(message)
```

**Comment by yunhaoling** [comment]
Proposal N+1:

keep the settlement method on the messages, but have a general purpose one on the receiver (this could be done incrementally, like after GA)

```python
class SettlementType(Enum):
    COMPLETE
    ABANDON
    DEFER
    DEADLETTER

class ServiceBusReceiver:
    def settle_message(message: Message, settlement_type: SettlementType, **kwargs):
        pass

# sample
msg = receiver.receive_messages()
receiver.settle_message(msg, SettlementType.COMPLETE)
receiver.settle_message(msg, SettlementType.DEADLETTER, dead_letter_reason='reason')
```

**Comment by richardpark-msft** [comment]
I think it's worth mentioning that settlement is no longer tied to the receiver (for non-session workflows, ie our primary use cases). If the receiver is gone you can still settle, it can just go against the internal management link.

**Comment by yunhaoling** [comment]
we would remove class `PeekedMessage` but will give a useful error if a user attempts to settle a peeked message.

cc: @annatisch @KieranBrantnerMagee
