### ISSUE TITLE
ResourceManagementClient.deployments.validate 'DeploymentDefinition' error

### ISSUE THREAD

**Issue by Limp-monkey** [Azure/azure-sdk-for-python#14566]
**Describe the bug**
I'm trying to deploy an ARM template using ResourceManagementClient.deployments, however as soon as I validate the template file I get the error:
`msrestazure.azure_exceptions.CloudError: Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line 1, position 12.'.`

**To Reproduce**

```python
from azure.common.credentials import ServicePrincipalCredentials, UserPassCredentials, get_azure_cli_credentials
from azure.mgmt.resource import ResourceManagementClient, SubscriptionClient
from azure.mgmt.resource.resources.models import DeploymentMode, Deployment, DeploymentProperties

my_subscription_id = os.environ.get('AZURE_SUBSCRIPTION_ID', '111111-1111-1111-11111-1111111')   
my_resource_group = 'azure-python-deployment'
my_template_file = "<link to> Template2.json"

template_file = open(my_template_file, 'r')
template_file_read = json.load(template_file)

deployment_properties = DeploymentProperties(mode=DeploymentMode("Incremental"),
                                            template=template_file_read)
credentials, _ = get_azure_cli_credentials()

client = ResourceManagementClient(credentials, my_subscription_id)

client.deployments.validate(my_resource_group, "test-arm-deployment", deployment_properties)

```
**Expected behavior**
The resources get created according to [Template2.json](https://github.com/Azure/azure-sdk-for-python/files/5393097/Template2.txt)

**Actual result**
`msrestazure.azure_exceptions.CloudError: Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line
1, position 12.'`

**Comment by changlong-liu** [comment]
Hi @Limp-monkey , may I know the azure-mgmt-resource version you are using?

If you are using the azure-mgmt-resource 10.x.x, the "client.deployments.validate()" should consume a Deployment instead of a DeploymentProperties.
https://github.com/Azure/azure-sdk-for-python/blob/release/v3/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2020_06_01/operations/_deployments_operations.py#L3222

**Comment by Limp-monkey** [comment]
hi,
Sorry for forgetting the version! I was trying to follow [resource-manager-python-template-deployment](https://docs.microsoft.com/en-us/samples/azure-samples/resource-manager-python-template-deployment/resource-manager-python-template-deployment/).

I'm using azure-mgmt-resource 10.2.0, which that one actually states:

>     :param properties: The deployment properties.
>     :type properties:
>     ~azure.mgmt.resource.resources.v2018_05_01.models.DeploymentProperties

but when I switched to:
``` python  
deployment_properties = DeploymentProperties(mode=DeploymentMode("Incremental"),
                                            template=template_file_read)

deployment = Deployment(properties=deployment_properties)     

client.deployments.validate(my_resource_group, "test-arm-deployment", deployment )
```

it works :)
