### ISSUE TITLE
Implement a Service Bus Shared Access Key Credential

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-python#14572]
# Summary

Service Bus allows for authorization using a shared key and shared access signature that is currently only supported when using a connection string.  To align with best practices, we would like to guide library users to down the path of using Identity credentials for production applications.   In order to provide a unified approach to authorization around the use of a credential for all scenarios, a service-specific credential type that mimics the API of the `TokenCredential` is desirable.

# Scope of Work

- Design and implementation of a `ServiceBusSharedAccessKeyCredential` type where the API mimics the `TokenCredentail` form.

- The credential should **NOT** derive from `TokenCredential` to avoid accidentally attempting to use it with another service.

- The credential should support creation using a shared key name and shared key value combination.

- The credential should support creation using a shared access signature.

- The credential should allow the shared key and value or the shared access signature to be updated without stopping or recreating the associated clients.

- The proposed surface area of the credential, as well as changes to the client API to accept it should be reviewed with the language architect, and approval obtained.  Full board review is not necessary.

# Success Criteria

- The design of a credential type detailed by the scope has been completed and approved by the language architect.

- The credential has been implemented according to the design and is exposed as part of the public API of the library.

- All clients that accept a `TokenCredential` also accept the new `ServiceBusSharedAccessKeyCredential` in a similar manner, 

- The tests necessary for its validation have been created or adjusted and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

# References

- [Follow-Up: Client Creation Discussion](https://gist.github.com/jsquire/13742f53bf642ec67baf9491fc844cff)
- [Client Creation Discussion](https://gist.github.com/jsquire/55a1a934246fd6d9fe9c9e21443d7023)

**Comment by KieranBrantnerMagee** [comment]
Proposal 1:
- simply expose both credential types as they exist under the cover (one for key/value, one for token)

Proposal 2:
- Have a single credential type, with from_* adapters.

Leaning towards proposal 1, even though it clutters signatures slightly, because the latter pattern doesn't seem to have precedent elsewhere in identity.

**Comment by KieranBrantnerMagee** [comment]
Note for posterity: The work for this change is completed [here](https://github.com/KieranBrantnerMagee/azure-sdk-for-python/tree/kibrantn/servicebus/track2-preview8-expose-ServiceBusSharedAccessKeyCredential) waiting for this task to be brought up again for synchronized release between language-sdks.  When this is taken on, it will simply need to be approved past architects and aligned with whatever consistency is needed cross-SDK.
