### ISSUE TITLE
Implement an Event Hubs Connection String Parser

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-python#14575]
# Summary

Event Hubs allows for authorization using a shared key and shared access signature that is supported using a service-specific shared access key credential.  It is common for the shared key or shared access signature to be passed with the service endpoint and entity path as part of a connection string.  To align with best practices, we would like to guide library users to down the path of using credentials for authorization within production applications.   In order to assist with transforming a connection string for use with credential-based client creation, a parsing utility is desirable.

# Scope of Work

- Design and implementation of a means for parsing a Event Hubs connection string into its components.  These should include:
    - FullyQualifiedNamespace
    - Endpoint
    - EventHubName
    - SharedAccessSignature
    - SharedAccessKeyName
    - SharedAccessKey<br /><br />

- The parser should adhere to the current validation rules for connection string correctness.  For example:
    - Only one form of authorization should be allowed (shared key or shared access signature)
    - The `Endpoint` must be present
    - The `EntityPath` is optional
    - All tokens which are present must have an associated value<br /><br />

- The `EventHubName` reflects the `EntityPath` token of the connection string, if present.

- The host name of the `Endpoint` should be reflected as the `FullyQualifiedNamespace`.

- Unknown tokens in the connection string are rejected or ignored; they are not reflected in the set of parsed tokens.

- The parsed values should be treated as read-only, if idiomatic to the language.

- The proposed surface area of the parser, as well as any associated types that change the public API surface should be reviewed with the language architect, and approval obtained.  Full board review is not necessary.

# Success Criteria

- The design of a parser detailed by the scope has been completed and approved by the language architect.

- The parser has been implemented according to the design and is exposed as part of the public API of the library.

- The tests necessary for its validation have been created or adjusted and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

# References

- [Follow-Up: Client Creation Discussion](https://gist.github.com/jsquire/13742f53bf642ec67baf9491fc844cff)
- [Client Creation Discussion](https://gist.github.com/jsquire/55a1a934246fd6d9fe9c9e21443d7023)

**Comment by swathipil** [comment]
SB `_parse_conn_str` method (in `azure\servicebus\_base_handler.py`):
```python
def _parse_conn_str(conn_str):
    # type: (str) -> Tuple[str, Optional[str], Optional[str], str, Optional[str], Optional[int]]
    endpoint = None
    shared_access_key_name = None
    shared_access_key = None
    entity_path = None  # type: Optional[str]
    shared_access_signature = None  # type: Optional[str]
    shared_access_signature_expiry = None  # type: Optional[int]
    for element in conn_str.strip().split(";"):
        key, _, value = element.partition("=")
        if key.lower() == "endpoint":
            endpoint = value.rstrip("/")
        elif key.lower() == "hostname":
            endpoint = value.rstrip("/")
        elif key.lower() == "sharedaccesskeyname":
            shared_access_key_name = value
        elif key.lower() == "sharedaccesskey":
            shared_access_key = value
        elif key.lower() == "entitypath":
            entity_path = value
        elif key.lower() == "sharedaccesssignature":
            shared_access_signature = value
            try:
                # Expiry can be stored in the "se=<timestamp>" clause of the token. ('&'-separated key-value pairs)
                # type: ignore
                shared_access_signature_expiry = int(
                    shared_access_signature.split("se=")[1].split("&")[0]
                )
            except (
                IndexError,
                TypeError,
                ValueError,
            ):  # Fallback since technically expiry is optional.
                # An arbitrary, absurdly large number, since you can't renew.
                shared_access_signature_expiry = int(time.time() * 2)
    if not (
        all((endpoint, shared_access_key_name, shared_access_key))
        or all((endpoint, shared_access_signature))
    ) or all(
        (shared_access_key_name, shared_access_signature)
    ):  # this latter clause since we don't accept both
        raise ValueError(
            "Invalid connection string. Should be in the format: "
            "Endpoint=sb://<FQDN>/;SharedAccessKeyName=<KeyName>;SharedAccessKey=<KeyValue>"
            "\nWith alternate option of providing SharedAccessSignature instead of SharedAccessKeyName and Key"
        )
    entity = cast(str, entity_path)
    host = cast(str, strip_protocol_from_uri(cast(str, endpoint)))

    return (
        host,
        str(shared_access_key_name) if shared_access_key_name else None,
        str(shared_access_key) if shared_access_key else None,
        entity,
        str(shared_access_signature) if shared_access_signature else None,
        shared_access_signature_expiry,
    )
```
