### ISSUE TITLE
Azure ML model registry returns 404 when requesting model by name

### ISSUE THREAD

**Issue by pugillum** [Azure/azure-sdk-for-python#14592]
- **Package Name**: azureml-core
- **Package Version**: 1.5.0
- **Operating System**: MacOS Catalina 10.15.7
- **Python Version**: 3.7.6

**Describe the bug**
When requesting a model by name the following error is returned:
```
ERROR - Received bad response from Model Management Service while retrieving paginatedresults:
Response Code: 404
Content: .."message":"The specified resource was not found."..
```

**To Reproduce**
1. Register a model using
  ```
  from azureml.core.model import Model
  model = Model.register(model_path = "test.pkl", 
                       model_name = "test.pkl", 
                       workspace = ws)
  ```
2. Retrieve the model using:
  ```
  model = Model(ws, 'test.pkl')
  ```

**Expected behavior**
Up until 15 October this resulted in a model being returned.

**Additional context**
If a version number is specified, a model is returned.

**Comment by mirceamt** [comment]
+1 - Currently facing the same issue

**Comment by binardo** [comment]
I got the same issue, some code that previously worked has just stopped working. I fixed by making a code change equivalent to...
`model = Model.list(ws, name='test.pkl', latest=True)[0]`

but it's a pain the prior syntax just stopped working.

**Comment by pugillum** [comment]
Well, very much to my surprise, I tested it again this morning (same version of azureml-core) and it now works.  I'm guessing there was an issue with the API used by the SDK and it has now been fixed.

**Comment by lostmygithubaccount** [comment]
looks like this has been resolved - apologies for the instability in the Python SDK and services

#please-close

**Comment by lostmygithubaccount** [comment]
@v-strudm-msft
