### ISSUE TITLE
[AzureCore] Consider adding support for explicitly chained exceptions in AzureError

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#14607]
**Is your feature request related to a problem? Please describe.**
As per [PEP3134](https://www.python.org/dev/peps/pep-3134/): `This PEP proposes three standard attributes on exception instances: the __context__ attribute for implicitly chained exceptions, the __cause__ attribute for explicitly chained exceptions, and the __traceback__ attribute for the traceback. A new raise ... from statement sets the __cause__ attribute.`

- Current `azure.core.exceptions.AzureError` doesn't support `__cause__` or `__context__`, it only supports setting `__traceback__`.

**Describe the solution you'd like**
Consider adding support for the explicit chain exceptions. we could use the [`six`](https://six.readthedocs.io/) library for combability with python2.7 -- [`six.raise_from(A, B)`](https://six.readthedocs.io/#six.raise_from) as the syntax `raise A from B` is only introduced in python3.

**Describe alternatives you've considered**

According to PEP3134, the implementation of explicit exception chaining is 
```
The __cause__ attribute on exception objects is always initialized to None. It is set by a new form of the raise statement:

raise EXCEPTION from CAUSE
which is equivalent to:

exc = EXCEPTION
exc.__cause__ = CAUSE
raise exc
```

so our implementation doesn't have to depend on the `six` library.

**Comment by lmazuel** [comment]
Deprecated, solution done now
