### ISSUE TITLE
[Test/EngSys] Remove `unittest.TestCase` inheritance

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-python#14616]
Remove the `AzureTestCase` inheritance on `unittest.TestCase` with `object` [here](https://github.com/Azure/azure-sdk-for-python/blob/232079268a42d14151118e950e5551d0b58dfc54/tools/azure-devtools/src/azure_devtools/scenario_tests/base.py#L23)

This needs all tests to change from using `self.assertXXXX` to strictly using the `assert` keywords. This can be eased with changes like adding a method for `self.assertIsNone` and `self.assertIsNotNone` to the base class:

```python
def assertIsNone(self, test_obj):
    assert test_obj is None

def assertIsNotNone(self, test_obj):
    assert test_obj is not None
```

The `setUp` method will not be called, this will have to be changed to a `pytest.fixture` in each library.

Solution:
* a regexp replacement of the inheritance of tests to double inheritance `class MyOldTest(AzureTestCase, unittest.TestCase)`, with a note to remove the double inheritance and fix tests when you have a chance.
* simple pytest fixture to call the `setUp` method on test objects

**Comment by lmazuel** [comment]
Test proxy migration is achivign this
