### ISSUE TITLE
azure-mgmt-subscription broken: Subscription Creation Functionality Removed With No Replacement

### ISSUE THREAD

**Issue by sas-adstut** [Azure/azure-sdk-for-python#14638]
- **azure-mgmt-subscription**: 
- **0.7.0**: 
- **All**:
- **3**: 

**Describe the bug**
A breaking change was committed, merged, and released with no justification and no alternative functionality provided.  This change broke our automation used for creating new subscriptions and is forcing us to pin an old version of this package in our automation, which is less than ideal for many reasons.  

Relevant commit, pull, and release:
https://github.com/Azure/azure-sdk-for-python/commit/380ae625102aeb2ff1fa3d788583ad8077713836
https://github.com/Azure/azure-sdk-for-python/pull/14426
https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-mgmt-subscription_0.7.0

**To Reproduce**
1. Install latest azure-mgmt-subscription
2. Attempt to use any of these functions, which were removed without an alternative being provided:
  - Removed operation SubscriptionOperations.create_subscription_in_enrollment_account
  - Removed operation SubscriptionOperations.create_subscription
  - Removed operation SubscriptionOperations.create_csp_subscription
  - Removed operation group SubscriptionOperationOperations

**Expected behavior**
Expect to be able to use the aforementioned functions for subscription creation or have an alternative function provided.  Removing functionality without warning and providing no alternative is not expected behavior for any SDK.

**Comment by changlong-liu** [comment]
Hi service team, the breaking changes come from this PR: https://github.com/Azure/azure-rest-api-specs/pull/10321

Would you help to check whether it's by design?

**Comment by anuragdalmia** [comment]
we have released our GA version for subscription creation APIs which is to use New-AzSubscriptionAlias cmdlet for subscription creation automations. You can see this documented in detail at https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=rest-getEnrollments%2Crest-EA.

We are asking everyone to move to adopt to this new cmdlet which is GA. We will keep the preview cmdlet around (only in older versions) until folks have had the chance to migrate and dont have a timeline when we will stop supporting preview versions.

**Comment by anuragdalmia** [comment]
Please re-activate if this doesnt address your issue.
