### ISSUE TITLE
[Service Bus] API review changes to the Batch object and its related methods

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#14639]
Findings for the Batch object and its related methods from internal API review for version 7.0.0-b7 of the Azure Service Bus package:

- Rename `BatchMessage` to `MessageBatch`. Consider adding `ServiceBus` prefix after discussing with the Python team
          - If we are adding the `ServiceBus` prefix, also consider doing so for `Message`
- `max_size_in_bytes` on the batch object should be readonly. Log an issue to add this in Event Hubs as well
- `message` on the batch object need not be public. 
- Consider renaming `create_batch()` method to `create_message_batch()`. We use the "message"/"messages" term in all other methods on the sender and receiver, so this should sit right well.
- Similarly, consider renaming `add()` method on the batch to `addMessage()` to resolve the confusion we saw in certain user studies where it was not clear what the next step was after creating a batch

**Comment by ramya-rao-a** [comment]
@annatisch Can you provide some help to the points above that we are "considering"?

**Comment by annatisch** [comment]
Thanks @ramya-rao-a - I'm good with these changes :)
