### ISSUE TITLE
DataFactoryManagementClient() authentication fails when using DefaultAzureCredential?

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-sdk-for-python#14635]
- **Package Name**: `azure.mgmt.datafactory`
- **Package Version**: `azure-mgmt-datafactory==0.13.0`
- **Operating System**: `Unbuntu 20`
- **Python Version**: `3.8.5`

**Describe the bug**
I use `DefaultAzureCredential` for all Python dev up to this point (KeyVault clients, BlobStorage clients, etc). This is my first time working with `azure.mgmt.datafactory` in Python. When trying to use `DefaultAzureCredential`, I get the error: `AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'`.

**To Reproduce**

```
credential = DefaultAzureCredential()
resource_client = ResourceManagementClient(credential, subscription_id)
adf_client = DataFactoryManagementClient(credential, subscription_id)
rg_name = 'RG_ADF_SANDBOX1'
df_name = 'df20201019test'
df_resource = Factory(location='westus')
df = adf_client.factories.create_or_update(rg_name, df_name, df_resource) #<----ERROR HERE
```

**Expected behavior**
The `DefaultAzureCredential` cred chain would be used to authenticate `DataFactoryManagementClient()`.

**Screenshots**

**Additional context**

**Comment by ganeshbhargav** [comment]
This issue is addressed here: [https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd)

Search "Using DefaultAzureCredential with SDK management libraries" on this page and it will take you to the section that gives more information to resolve this issue.

It can be resolved by using Wrapper Classes.

**Comment by SeaDude** [comment]
Thank you for the link @ganeshbhargav. I don't understand how the wrapper works, so I probably won't incorporate it into my code. I'll stick to `ServicePrincipalCredentials` (I think thats what its called) until `DefaultAzureCredential` is implemented for this library.

**Comment by kaerm** [comment]
@lmazuel should the link on [this docs page](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd) lead to https://github.com/jongio/azidext#python instead? It seems to have additional instructions to help make things easier to incorporate
