### ISSUE TITLE
keyvault sku family no longer defaults in azure-mgmt-keyvault==8.0.0, does not appear in .get()

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#14656]
- **Package Name**: azure-mgmt-keyvault
- **Package Version**: 8.0.0
- **Operating System**:Linux
- **Python Version**: 3.7

**Describe the bug**
With azure-mgmt-keyvault==2.2.0, I could create a keyvault specifying:
  'sku' : {'name' : azure.mgmt.keyvault.models.SkuName.standard.value},

With azure-mgmt-keyvault==8.0.0, doing this gives an error that the family must be specified. The only legal value for the family is the string 'A'. This should default to 'A' like it does in 2.2.0.

When I do a .get(), I do not get back the family.

**To Reproduce**
1. create_or_update() a keyvault without specifying the SKU family.

**Expected behavior**
I expect that if I do not specify a value, it defaults to 'A' as it does in 2.2.0.
If I must provide this parameter in create_or_update(), then I expect to see it come back in get() results.

**Comment by lmazuel** [comment]
Hey @jazelenk , I asked @iscai-msft to investigate if that could come from an autorest flaw from track1 to track2, we'll update this thread with more findings. Thanks!

**Comment by iscai-msft** [comment]
Hi @jazelenk this change arose because of our code generator fixing how we deal with single value extensible enums. I've created a [PR](https://github.com/Azure/azure-rest-api-specs/pull/11333/files) to a separate repo, in the hopes that once that PR is merged, our generated code will allow you to not pass in a value for `family`

cc @changlong-liu @msyyc for potential future regeneration

**Comment by iscai-msft** [comment]
as an update to this issue, the swagger PR has been merged and autorest python has been fixed. Once regen'd with autorest python version 5.4.1 (using `--v3 --python` on the command line should get you this latest version), users will not have to pass in a value for family

cc @changlong-liu @msyyc @allenjzhang

**Comment by msyyc** [comment]
got it
