### ISSUE TITLE
[ServiceBus] receive_messages parameter max message count default to 1

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#14709]
Currently, peek_messages defaults to a max_message_count of 1.  receive_messages does not. (currently None).

This was a historical artifact from T1 wherein it would fall back to using the prefetch value if one was defined.  We will be normalizing with a more clear semantic for T2 of having 1 for all consistently as a default

**Comment by KieranBrantnerMagee** [comment]
Hey @stefpiatek , that sounds excellent, feel free to take a stab at this.

Should be reasonably straightforward, with the minor callouts to adjust docstrings accordingly and ensure async + sync.

Don't hesitate to give us a shout if you needed any eyes/hands/thoughts, and thanks in advance!
