### ISSUE TITLE
[ServiceBus] Unification of Receiver and SessionReceiver

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#14705]
- [x] `session_id` takes NEXT_AVAILABLE_SESSION. This should be an object so that it is differentiable from a string which would mean that we are asking for a specific session
- [ ] receiver would have `renew_message_lock` method, and it would raise error called on the session receiver.
  - session receiver has a session attribute which have session operations on

more context:

https://github.com/Azure/azure-sdk/issues/1884#issuecomment-714252397

> In case of sessions, the receiver.session.renew_lock() renews the lock on the sessions. The receiver.renew_lock(message) method was proposed to work the same way. This has push back from Richard, Harsha and Ramya as summarized below. Python team to revisit this decision
Having renew_lock(message) renew the session lock is misleading. Losing lock on message is a minor inconvenience as Service Bus is expected to provide a atleast once guarantee not atmost once. But losing on session is much more serious and requires users to recreate the receiver to attempt to get a lock on the session or decide to move on to the next session
Having renew_lock(message) renew the session lock can lead people to call it on every message which results in unnecessary renew locks on the session under the hood

**Comment by annatisch** [comment]
@yunhaoling @KieranBrantnerMagee - I'm okay with conceding on this one.
The rest of the SB crew aligned with your perspectives, and additionally had not given due consideration to the "user choosing to let a message expire in the session scenario means the loss of that session".

**Comment by yunhaoling** [comment]
receiver would have renew_message_lock method, and it would raise error called on the session receiver would go into the settlement PR
