### ISSUE TITLE
azure.storage.filedatalake.models.StorageErrorException does not exist

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#14731]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.1.2
- **Operating System**:Linux
- **Python Version**: 3.7.3

**Describe the bug**
The docs refer to azure.storage.filedatalake.models.StorageErrorException, but azure.storage.filedatalake.models.StorageErrorException does not seem to exist.

**To Reproduce**
```
>>> import azure.storage.filedatalake
>>> import azure.storage.filedatalake.models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.storage.filedatalake.models'
>>> import azure.storage.filedatalake.models.StorageErrorException
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.storage.filedatalake.models'
>>> azure.storage.filedatalake._generated.models.StorageErrorException
<class 'azure.storage.filedatalake._generated.models._models_py3.StorageErrorException'>

```
**Expected behavior**
Documented classes should exist. :-) Exception classes should be publicly accessible so they may be caught and examined by the caller.

**Additional context**
We catch these exceptions to check for the string 'This operation is only supported on a hierarchical namespace account.'

**Comment by tasherif-msft** [comment]
Hi @jazelenk the exception `StorageErrorException` actually gets deserialized internally. To catch the potential response exceptions you can either use: `from azure.core.exceptions import HttpResponseError` or  use `StorageErrorCode` to get the specific error codes you are trying to catch
```
from azure.storage.filedatalake import StorageErrorCode
```

**Comment by jazelenk** [comment]
Thanks! I can't find any documentation for StorageErrorCode - can you point me that way? Which code corresponds to an attempt to operate on a non-HNS storage account?

**Comment by tasherif-msft** [comment]
Hi @jazelenk, https://docs.microsoft.com/en-us/azure/developer/python/sdk/storage/azure-storage-blob/azure.storage.blob.storageerrorcode?view=storage-py-v12 
this link should provide all the possible error codes. 
So an example usage would be:
```
self.assertEqual(StorageErrorCode.condition_not_met, e.exception.error_code)
```

**Comment by jazelenk** [comment]
That does not match th ebehavior that I'm seeing. The reason string that I get is 'The request URI is inavlid.'

**Comment by tasherif-msft** [comment]
@jazelenk is your issue now resolved? :)

**Comment by jazelenk** [comment]
Not really... to deal with versionitis in the SDK packages, I added this to our core exception handler:
```
        if isinstance(exc, azure.storage.filedatalake._generated.models.StorageErrorException):
            try:
                azure.storage.filedatalake._deserialize.process_storage_error(exc)
            except Exception as exc2:
                exc = exc2
```

This may be related to our need to work around other issues in the SDK by wrapping the client objects so we can control retries.

**Comment by tasherif-msft** [comment]
Could you please provide me with an example failing operation and the exception it throws so I have a better idea? Almost all service side errors can be caught using this list https://docs.microsoft.com/en-us/python/api/azure-core/azure.core.exceptions?view=azure-python

**Comment by jazelenk** [comment]
I'm probing a storage account to determine whether or not it is HNS-enabled. I get a DataLakeServiceClient for the SA using either azure.identity.DefaultAzureCredential or azure.identity.ManagedIdentityCredential (the observed behavior is the same either way). I use datalakeserviceclient.get_directory_client,() with path '/' to get a DataLakeDirectoryClient for the container, then I call directory_client.get_access_control(). If it succeeds, HNS is enabled. If the exception has error code 'HierarchicalNamespaceNotEnabled', then I know that the SA is not ADLS gen 2.

**Comment by jazelenk** [comment]
The check I end up performing is matching `error_code` to `HierarchicalNamespaceNotEnabled`.

**Comment by tasherif-msft** [comment]
Hi @jazelenk, sorry for the delay on this! you're right the exceptions docs are not very clear. The azure storage exceptions that are raised at the end of any failed operation are imported from Azure core.

The way we raise this is by using an internal class called `StorageErrorException`. This is deserialized by `process_storage_error(storage_error_exception_object)` internally. This simply maps the different possible error codes to the corresponding appropriate Azure core exception which can be caught by the user. You can see the mapping we're doing here: https://github.com/Azure/azure-sdk-for-python/blob/8504f6d247badd2fd60dce3457f201f9e2b1c079/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py#L86

As for fetching the specific error code of the exception (which - as you mentioned, would be package specific ) you can follow this example:
```
# assume we tried to create a container that already exists
# you can catch it and get the specific error code by:

from azure.core.exceptions import ResourceExistsError
try:
  # try to create container logic
except ResourceExistsError as e:
    # this would print StorageErrorCode.container_already_exists
    print(e.error_code)
```
If for some reason we deserialized an error that is not defined in https://github.com/Azure/azure-sdk-for-python/blob/8504f6d247badd2fd60dce3457f201f9e2b1c079/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py#L86 we default/raise an `HttpResponseError` (you can catch it and use the code above to find out what the error code was)

In your case `HierarchicalNamespaceNotEnabled` is not being deserialized in our checks so you can do the following:
```
from azure.core.exceptions import HttpResponseError
try:
    ...
except HttpResponseError as e:
    # this would print HierarchicalNamespaceNotEnabled
    print(e.error_code)
```
I'm not sure why we even reference `StorageErrorException` in our README. I will put out a PR that explains what I have mentioned in this comment :) I will link it here once up.
Let me know if this makes sense or if you need further help!
