### ISSUE TITLE
Storage queue receive_messages unexpected behaviour

### ISSUE THREAD

**Issue by kobibarhanin** [Azure/azure-sdk-for-python#14762]
- **Package Name**: azure-storage-queue
- **Package Version**:  12.1.3
- **Operating System**: mac / linux
- **Python Version**: 3.8.3

**Describe the bug**
When retrieving messages from a storage queue with:
`receive_messages(messages_per_page=<SOME NUMBER>)`
I get the entire queue back regardless of SOME NUMBER.
this is in contrast with expected behaviour and this method's docs.

**To Reproduce**
1. run receive_messages on some queue with kw arg messages_per_page.

**Expected behavior**
return of messages_per_page messages (if exists).

![image](https://user-images.githubusercontent.com/34001701/97149591-a0b8a500-1775-11eb-9b92-3d861ebab872.png)

**Additional context**
This is not additional context - but I'm also facing a weird issue that whenever I run receive_messages I have to wait for about 30 seconds to run it again to get results (if I run it sooner I get no results back) - anyone knows anything about this?

Thanks!

**Comment by tasherif-msft** [comment]
Hi @kobibarhanin, please refer to https://github.com/Azure/azure-sdk-for-python/issues/14665, let me know if this helps :)

**Comment by kobibarhanin** [comment]
@xiafu-msft 

Thanks for the response!

I was able to squeeze out a strategy but I really think this should be better implemented - no reason to not enable a simpler approach to retrieve a fixed amount of elements from a hosted queue.

Thanks again.

**Comment by tasherif-msft** [comment]
Hi @kobibarhanin, yea it seems this is a common misinterpretation by users. We added a sample recently to also better help users understand how this method operates better here: https://github.com/Azure/azure-sdk-for-python/blob/1b2450b0c59ba6c440c680992faef7c777e5dae0/sdk/storage/azure-storage-queue/samples/queue_samples_message.py#L149 and here https://github.com/Azure/azure-sdk-for-python/blob/1b2450b0c59ba6c440c680992faef7c777e5dae0/sdk/storage/azure-storage-queue/samples/queue_samples_message.py#L108
Let me know what you think of those samples :)

**Comment by tasherif-msft** [comment]
Hi @kobibarhanin, just wanted to inform you that I have just created a PR that makes it much simpler to pop one message from the queue. Here's the PR: https://github.com/Azure/azure-sdk-for-python/pull/14855
This will give you the ability to retrieve one message at a time without lots of code overhead to do so :)
