### ISSUE TITLE
Fixed the aggregate report broken link.

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-python#14771]
[Aggregate-report](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=589900&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c&t=73b5eb55-653d-5b46-19cb-2116006ac112) failed at one of the broken link in [Readme](https://github.com/Azure/azure-sdk-for-python/blob/master/tools/azure-sdk-tools/packaging_tools/templates/README.md):

https://docs.microsoft.com/samples/azure-samples/azure-samples-python-management/{{package_doc_id}}

We have to either put a concrete link or put the link in [file](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/ignore-links.txt):

**Comment by lmazuel** [comment]
I believe it's fixed today
