### ISSUE TITLE
Subscriptable support for Azure objects

### ISSUE THREAD

**Issue by mxplusb** [Azure/azure-sdk-for-python#1477]
Working with some basic Python code:

```python
import os
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.resource import ResourceManagementClient

subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
tenant_id = os.environ["AZURE_TENANT_ID"]
client_id = os.environ['AZURE_CLIENT_ID']
secret = os.environ['AZURE_CLIENT_SECRET']
resource_group = "test-01"

credentials = ServicePrincipalCredentials(client_id=client_id, secret=secret, tenant=tenant_id)

client = ResourceManagementClient(credentials, subscription_id)
resources = [r for r in client.resources.list_by_resource_group(resource_group)]
resources = sorted(resources, key=lambda x: x["id"], reverse=True)
```

I get this error:

```python
TypeError: 'GenericResource' object is not subscriptable
```

This error is thrown because the `ResourcesOperations` class doesn't implement `__getitem__()`.

I was looking through a lot of the various `<Endpoint>Operations` classes, and none of them implement `__getitem__()`. Would it be possible to implement `__getitem__()` across the board? You could leverage the `internal_paging()` functions with some basic extension, like so:

```python
class ResourceOperations(object):
  ...
  def __getitem__():
    yield internal_paging()
  ...
```

**Comment by lmazuel** [comment]
Hi @mxplusb 

Just change your last line by:
```python
resources = sorted(resources, key=lambda x: x.id, reverse=True)
```

If you really want to use the dict syntax:
```python
resources = sorted(resources, key=lambda x: x.to_dict()["id"], reverse=True)
```

**Comment by mxplusb** [comment]
Ah that's good to know, thanks!

I believe it would still give a more native experience if there's an opportunity to use `__getitem()__`. It looks like a lot of these classes are auto generated. How do you generate them?

**Comment by lmazuel** [comment]
We added `to_dict` to avoid using magic method here, because "[explicit is better than explicit](https://www.python.org/dev/peps/pep-0020/)" :)

We generate using [Autorest](https://github.com/Azure/autorest.python) and a [Swagger](https://github.com/Azure/azure-rest-api-specs) file.

**Comment by mxplusb** [comment]
It might take some time since I've never used Autorest, but I'll look into implementing that logic into autorest.python. If it's fairly easy enough, I'll submit a PR.

**Comment by lmazuel** [comment]
@mxplusb I don't think we want to add this behavior in the generator, and if we have to, it will be in the runtime `msrest` library, not in Autorest.python itself.

**Comment by lmazuel** [comment]
Going through this right now, I still don't believe this is a feature that would be needed, "There should be one-- and preferably only one --obvious way to do it.", and we have the attribute syntax or the export to a dict.
