### ISSUE TITLE
Search Documents Samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#14803]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/search/azure-search-documents/samples/async_samples/sample_indexers_operations_async.py#L68):
![image](https://user-images.githubusercontent.com/57166602/97269394-6da30e00-1868-11eb-8db1-d090099fc95e.png)

Suggestion:
Update `indexer-hotels` to `async-indexer-hotels`.

@jongio for notification.

**Comment by xiangyan99** [comment]
Fixed in #14817
