### ISSUE TITLE
Storage file datalake Samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#14800]
1.
Section [Link1](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/samples/datalake_samples_access_control_recursive.py#L59), [Link2](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/samples/datalake_samples_access_control_recursive_async.py#L62):
![image](https://user-images.githubusercontent.com/57166602/97268756-56175580-1867-11eb-9115-0ba126132723.png)

Reason:
TypeError: _request() got an unexpected keyword argument 'progress_callback'.

Suggestion:
Update `progress_callback` to `progress_hook`.

@jongio for notification.

**Comment by tasherif-msft** [comment]
Hi @v-xuto, it looks like this has been resolved :) I will proceed to close this issue.
