### ISSUE TITLE
Service Bus Samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#14801]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples/sync_samples/generate_sas_token_and_authenticate_client.py#L53):
![image](https://user-images.githubusercontent.com/57166602/97268984-ba3a1980-1867-11eb-808f-c68b8036b0db.png)

Reason:
`SESSION_QUEUE_NAME` Variables not defined.

Suggestion:
Add `SESSION_QUEUE_NAME = os.environ['SERVICE_BUS_SESSION_QUEUE_NAME']`.

@jongio for notification.

**Comment by KieranBrantnerMagee** [comment]
This was resolved by @yunhaoling in commit #be67ece4 and will be going out with 7.0.0b8

Thanks as always for the report :)
