### ISSUE TITLE
[ServiceBus] Improve get_logger call to allow fine-grained file-based logging to be enabled in stress tests

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14818]
**Is your feature request related to a problem? Please describe.**
See comment chain [here](https://github.com/Azure/azure-sdk-for-python/pull/14612#discussion_r508196913)

Tersely, currently to persist stress test logs, one must use a file redirect at the console.  Might be nice to formalize this a little and enable it at the get_logger level.  From the aformentioned comment chain, see [this precedent](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/stress/logger.py) from eventhubs.

**Describe the solution you'd like**
Goals:
- ability to transparently enable a file logging handler at a specified level for any of the common internal loggers (stress, uamqp, azure.)
- Should not change the existing behavior for any existing get_logger incantations.

**Describe alternatives you've considered**
The current alternative is to use a console-level output redirect.  This works, but is a little bit informal.  Might offer fine-grained internal solutions.

**Comment by yunhaoling** [comment]
we're shifting to apply the universal perf test framework: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus/tests/perf_tests closing the issue now.
