### ISSUE TITLE
azure-cosmos: access_cosmos_with_resource_token.py - Authorization header doesn't confirm to the required format

### ISSUE THREAD

**Issue by Mja101** [Azure/azure-sdk-for-python#14829]
- **Package Name**:  azure-cosmos
- **Package Version**: 4.1.0
- **Operating System**: Windows
- **Python Version**: 3.8.2

**Describe the bug**
After generating a token for a user, any operations fail with the following 401 error:

**Authorization header doesn't confirm to the required format. Please verify and try again.**

**To Reproduce**
1.  Set-up local Cosmos-DB Emulator
2.  Copy sample code and configure host parameters. 
sample code: https://github.com/Azure/azure-sdk-for-python/blob/4f96d8a8dfde9b4cac9d2103b5f58d5705b26ded/sdk/cosmos/azure-cosmos/samples/access_cosmos_with_resource_token.py
3. Execute script

**Expected behavior**
Expected behavior is a http response of 200 with a body containing requested data.

The sample code successfully does the following:

1. Creates a database
2. Creates a container
3. Creates a user.
4. Generates a token.

However, when the token is used in any subsequent request, it returns a 401 error with:

**Authorization header doesn't confirm to the required format. Please verify and try again.**

Example of a token:
'type=resource&ver=1&sig=DojUybVKTy7H4o9f7GUtjw==;3N789ulXD6B5f+Bvyd6nkQ6wgNkGCpoUqn5SvDN/s16DS/NjW6r/nYYcHiTOG423Ue4gPhRqTlw6/BbM3TQID1LA1pvoS9Wqt1oanFBbj/nogj/hI/h3tkrXuA6wcqPrLbHI+hh6UMICaN1XaXtKGyUTJ2d2jZ2YhIVPLs9qvYtGn4aoC561nwB8m6b3PcCuMUyAB4OfqP6PM6pZ9Bc4f0Pa/Ci/IylUPg4kYUclSKg=;'

**Additional context**
I have also tried using this sample code in a HTTP Azure function. It can generate the token but the same issue persists regarding the required format.

**Comment by Mja101** [comment]
I have actually solved the problem but now face something slightly different. Some reason, the code sample in the original post did not encode the token before using it. I used the urlib library to encode the token before passing to the request.

I have created a permission definition to grant a user access to a specific partition key. However, when i use the token generated with the partition scoped query, I receive the following error:

_Insufficient permissions provided in the authorization header for the corresponding request. Please retry with another authorization header_

I can successfully read a document when I give a user **_ALL_** permissions but this is not something I want to do for security purposes.

**Comment by southpolesteve** [comment]
Can you post some code that reproduces the issue? "partition scoped query" can be done a couple different ways. You will need to include the partition key in the options object, not in the query itself.

**Comment by zfoster** [comment]
Hi @Mja101, I resolved this issue in the sample and will update it.

The key for each token dictionary needs to be `container.container_link` instead of `container.id`, I'll push a PR soon.

cc @srinathnarayanan

**Comment by Mja101** [comment]
Hi @zfoster ,

Thanks for the replies. I have tried changing container.id to container.container_link but I still recieve the same error when I try to access a resource based on a specific partition.

**_Insufficient permissions provided in the authorization header for the corresponding request. Please retry with another authorization header_**

The code to create the permissions dict:

`        permission_definition = {
            "id": PARTITION_READ_PERMISSION,
            "permissionMode": documents.PermissionMode.Read,
            "resource": container.container_link,
            "resourcePartitionKey": [serial_number],
        }`

The body of the POST:

`{
  "query": "SELECT * FROM info c WHERE c.serial_number = @serial_number",
  "parameters": [{"name": "@serial_number", "value": "0000000392"}],
  "partition_key": "0000000392"
}`

I can only access the data when I change `documents.PermissionMode.Read` to `documents.PermissionMode.All`.

I've tried with different users and still receive the insufficient permission error. Any ideas?

**Comment by zfoster** [comment]
Taking a look

**Comment by zfoster** [comment]
@Mja101 the sample is working for me, using this query:

```
def token_client_query(container, username):
    try:
        for item in container.query_items(
            query="SELECT * FROM my_container c WHERE c.username=@username",
            parameters=[{"name": "@username", "value": username}],
            partition_key=username,
        ):
            print(json.dumps(item, indent=True))
    except exceptions.CosmosHttpResponseError:
        print("Error in querying item(s)")
```

and this code:

```
        # Give user read-only permission, for a specific partition
        user_2 = create_user_if_not_exists(db, USERNAME_2)
        permission_definition = {
            "id": PARTITION_READ_PERMISSION,
            "permissionMode": documents.PermissionMode.Read,
            "resource": container.container_link,
            "resourcePartitionKey": [USERNAME_2],
        }
        permission = create_permission_if_not_exists(user_2, permission_definition)
        read_token = {}
        read_token[container.container_link] = permission.properties["_token"]

        # Use token to connect to database
        token_client = cosmos_client.CosmosClient(HOST, read_token)
        token_db = token_client.get_database_client(DATABASE_ID)
        token_container = token_db.get_container_client(CONTAINER_ID)

        # Fails since this client has access to only items with partition key USERNAME_2 (ie. "user2")
        token_client_read_all(token_container)

        # Ok to read item(s) with partition key "user2"
        token_client_read_item(token_container, USERNAME_2, ITEM_3_ID)

        # Can't upsert or delete since it's read-only
        token_client_upsert(token_container, USERNAME_2, ITEM_3_ID)

        # Query for items in a certain partition !!!! this works
        token_client_query(token_container, USERNAME_2)
```

**Comment by zfoster** [comment]
See the 2nd to last line - this seems to be the same code as what you've pasted?

**Comment by Mja101** [comment]
@zfoster 

Finally got it all working. Thanks for all your help mate!

**Comment by zfoster** [comment]
@Mja101 no problem! take care
