### ISSUE TITLE
InvalidHeaderValue while connecting to blob storage on IOT EDGE

### ISSUE THREAD

**Issue by santhoshmaddi49** [Azure/azure-sdk-for-python#14839]
azure.core.exceptions.HttpResponseError: The value for one of the HTTP headers is not in the correct format.
RequestId:a5b2e976-4913-4a25-8b7c-477ca23c1ed6
Time:2020-10-28T07:42:47.0931563Z
ErrorCode:InvalidHeaderValue
Error:None
HeaderName:x-ms-version
HeaderValue:2019-12-12
ExceptionDetails:None
ExceptionMessage:The value 2019-12-12 provided for request header x-ms-version is invalid.

**Comment by tasherif-msft** [comment]
Hi there, could you please attempt to set `api_version='2019-07-07` when setting up your client? 
This should fix the problem. For example:
```
blob = BlobClient.from_connection_string(conn_str=connection_string, container_name=localcontainer, blob_name=local_file_name, api_version='2019-07-07')
```
Let me know if this works :)

**Comment by santhoshmaddi49** [comment]
Hello,

 Thanks,I am able to connect to local blob storage using api_version='2019-07-07' .  Can I know what is the issue with lates version and will it be fixed?

**Comment by tasherif-msft** [comment]
Hey @santhoshmaddi49, we have created an issue regarding this here: https://github.com/MicrosoftDocs/azure-docs/issues/65265. It seems the version referenced in the docs is outdated.
I will proceed to close this issue. Let me know if you need any more assistance :) 
Thank you!
