### ISSUE TITLE
Meaningful error message when sending empty batch to eventhub

### ISSUE THREAD

**Issue by arache** [Azure/azure-sdk-for-python#14841]
When sending empty batch to eventhub, the SDK just raised the error like below:
```
azure.eventhub.exceptions.EventDataSendError: Message sender failed to add message data to outgoing queue.
ErrorCodes.ClientError: Message sender failed to add message data to outgoing queue.

```
I believe a more clear error message would be helpful here.

**Comment by KieranBrantnerMagee** [comment]
Hey @arache, thanks for reaching out.

Totally reasonable ask, and I find myself wanting the clarity as much as you. (I believe we even fixed this comparable specific issue in ServiceBus just recently, so more than glad to pull this in.)

Expect to see a fix in during our next EH release, this issue will track the PR as it is produced and checked in.

**Comment by yunhaoling** [comment]
hey @arache , sorry for keeping you waiting.

I did a cross-language check and think this actually should be a no-op instead of raising error when sending empty event data batch.

I had a PR out for this: https://github.com/Azure/azure-sdk-for-python/pull/16638, let me know if you have concern on the change.

**Comment by yunhaoling** [comment]
hey @arache, we decided to make sending empty batch being a no-op instead of raising error, we will be having a preview release next week which you could try out.

I'm closing this issue now, don't hesitate to reach out to us or re-open the issue if you have any other questions!

**Comment by arache** [comment]
Thanks @yunhaoling , nice fix.
