### ISSUE TITLE
How to attach a route table to a subnet: How to use the route_table property

### ISSUE THREAD

**Issue by rafael6** [Azure/azure-sdk-for-python#1484]
I need to attach a route_table to a subnet. I understand subnet has a route_table property, but I'm not sure how to use such property or how to express the value (the route_table) for it. 

Any examples out there?

Thanks in advance!

**Comment by lmazuel** [comment]
@tjprescott Do you know? In particular, is this possible to do it either way or there is one way only (i.e. update route_table to use subnet or update subnet tp use route_table)

**Comment by rafael6** [comment]
Below is how we are attaching a route table to the subnet today, but I was wondering if there another way other than using the id of the route table object such as the route table name, etc...

create_update_subnet(
        my_network_client,
        GROUP_NAME,
        VNET_NAME,
        SUBNET_NAME,
        {'address_prefix': '10.1.1.0/24',
         'route_table':{'id': '/subscriptions/MY_SUBSCRIPTION_ID/resourceGroups/MY_RESOURCE_GROUP/providers/Microsoft.Network/routeTables/MY_ROUTE_TABLE_NAME'}})
    )

**Comment by lmazuel** [comment]
@rafael6 no, since route_table and subnet are two different resource type, they are connected together by their resource ID only. Note that you can re-create the ID easily from the subscription ID, the resource group name and the route table name.

**Comment by rafael6** [comment]
@lmazuel Got it; thank you for the information and the tips.
