### ISSUE TITLE
[ServiceBus] Support fully qualified namespaces both with and without "sb://" prefix.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14851]
Currently, one will get a Connection or Timeout error when attempting to connect a servicebusclient if your fqdn contains "sb://".

This is not the case in dotnet.  The assumption being that we should normalize and support both formats.

CC @ramya-rao-a on this observation in case I'm off in left field.

**Comment by ramya-rao-a** [comment]
In JS, I believe we strip out "anything://" from the endpoint in the connection string.
Not sure what we do for the fully qualified namespace that is passed to the client constructor
But @HarshaNalluru would know :)

**Comment by swathipil** [comment]
Looks like this has already been addressed with the [`strip_protocol_from_uri`](https://github.com/Azure/azure-sdk-for-python/blob/c12a9c01854f78d2c92d60baff09f464e751a643/sdk/servicebus/azure-servicebus/azure/servicebus/_common/utils.py#L200) method in `azure/servicebus/_common/utils.py`.

Works with both:
- `<sb/http>://<sb-namespace>.servicebus.windows.net`
- `<sb-namespace>.servicebus.windows.net`

Addressed in both sync and async clients:
- Sync Client, [line 74](https://github.com/Azure/azure-sdk-for-python/blob/c12a9c01854f78d2c92d60baff09f464e751a643/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py#L74)
- Async Client, [line 75](https://github.com/Azure/azure-sdk-for-python/blob/c12a9c01854f78d2c92d60baff09f464e751a643/sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py#L75)
