### ISSUE TITLE
[ServiceBus] Set message count limit for tryAdd on message batch

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-sdk-for-python#14903]
Currently, the service only allows 4500 messages in a batch. To accommodate for this, we should make tryAdd on a message batch fail if trying to add more than 4500 messages. The failure used for the message size limit should also be applied when the message count limit is reached.

Related: https://github.com/Azure/azure-service-bus/issues/397

*Edit*: Instead of adding this hard limit client-side, we are instead going to place information in the documentation for tryAdd, since the limit for Basic and Standard tier is 4500 and the limit for Premium is ~15885. It would be best to link to Service Bus documentation on these limits instead of hard-coding into our reference documentation. However, we'd have to wait until they publish that information.

**Comment by yunhaoling** [comment]
two things worth notes after some experiments:

1. there is a different between basic/standard and premium tier, the premium could handle around ~15000 messages in a batch while basic/standard tier could only handle 4500 according to the service team
2. python single message encode side is 60 bytes, while other languages are just 29bytes for .net and 30bytes for js, need to check what makes up the encoded bytes and see if we could save some cost
  - should categorize the issue whether this could be a post-GA improvement or has to be tackled before GA

**Comment by MiYanni** [comment]
Instead of adding this hard limit client-side, we are instead going to place information in the documentation for tryAdd, since the limit for Basic and Standard tier is 4500 and the limit for Premium is ~15885. It would be best to link to Service Bus documentation on these limits instead of hard-coding into our reference documentation. However, we'd have to wait until they publish that information.
