### ISSUE TITLE
Error with AZURE_URL in ADT README.md

### ISSUE THREAD

**Issue by joseba-altran** [Azure/azure-sdk-for-python#14916]
- **Package Name**: azure-digitaltwins-core
- **Package Version**: master
- **Operating System**: N/A
- **Python Version**:  N/A

**Describe the bug**
[README.md](master/sdk/digitaltwins/azure-digitaltwins-core/README.md) states:
```
# - AZURE_URL: The tenant ID in Azure Active Directory
url = os.getenv("AZURE_URL")
```
This is probably a mistake, since the code later calls `DigitalTwinsClient()`, which requires a URL (and the name of the variable clearly suggests that it should be a URL 😅).

**To Reproduce**
1. The content is in master, and comes from 27175c267b854ff7e3743ce55302f7192701da95.

**Expected behavior**
That section should probably read:
```
# - AZURE_URL: The URL to the ADT in Azure
url = os.getenv("AZURE_URL")
```

**Comment by Panda19961202** [comment]
Hello，Can you tell me how AZURE_URL needs to be obtained? Thanks.I see AZURE_UR as the tenant ID, and the function returns the null value.
