### ISSUE TITLE
AttributeError: 'UserPassCredentials' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by reach4bawer** [Azure/azure-sdk-for-python#14919]
```
import os
from msrestazure.azure_active_directory import UserPassCredentials
from azure.mgmt.resource import ResourceManagementClient

credentials = UserPassCredentials(username=os.getenv('AZURE_USERNAME'), password=os.getenv('AZURE_PASSWORD'))
subscription_id = os.getenv('AZURE_SUBSCRIPTION')
resource_client = ResourceManagementClient(credentials, subscription_id)
resource_list = resource_client.resource_groups.list()

for resource in resource_list:
    print(resource)
```

For the above code I am running into the error -

> AttributeError: 'UserPassCredentials' object has no attribute 'get_token'

I have to use Active directory to authenticate. I have the token embedded inside the credentials. I think I am missing something here. Can you please guide me in the right direction on how can I list all the resource group in my subscriptions using the credentials that I generated or if I need to use a different method. 

**Update 1** - Fixed a typo

**Comment by changlong-liu** [comment]
Hi @reach4bawer ,

Are you using the latest azure-mgmt-resource package? It's a new generation of Python SDK, and azure-identity instead of msrestazure should be used for it.
I think you may need this: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.4.0/azure.identity.html#azure.identity.UsernamePasswordCredential
And here is a quick start for using azure-identity in new generation of SDK: https://azure.github.io/azure-sdk-for-python/mgmt_quickstart.html

**Comment by reach4bawer** [comment]
I tried the above examples my code but it did not work. I have read only access to all the subscriptions so this is the code that is working - 

```
import os
from azure.mgmt.subscription import SubscriptionClient
from msrestazure.azure_active_directory import UserPassCredentials

credentials = UserPassCredentials(username=os.getenv('AZURE_USERNAME'), password=os.getenv('AZURE_PASSWORD'))
sub_client = SubscriptionClient(credentials)
subs = [sub.as_dict() for sub in sub_client.subscriptions.list()]
```

Notice that there is no client id or anything that was needed to be passed. I was able to print all the subscriptions using the above code. From the credentials object I was able to extract the default client_id and exported that in my environment variables. When I try the new method with the following code - 

```
import os
from azure.identity import UsernamePasswordCredential
from azure.mgmt.subscription import SubscriptionClient
credentials = UsernamePasswordCredential(client_id = os.getenv('AZURE_CLIENT_ID'),
                                          username=os.getenv('AZURE_USERNAME'),password=os.getenv('AZURE_PASSWORD'))
sub_client = SubscriptionClient(credentials)
subs = [sub.as_dict() for sub in sub_client.subscriptions.list()]

```

I get the error -

> **AttributeError**: 'UsernamePasswordCredential' object has no attribute 'signed_session'

I was able to use the UsernamePasswordCredential to get the Resource Groups. See the code below - 

```
import os
from azure.identity import UsernamePasswordCredential
from azure.mgmt.resource import ResourceManagementClient
subscription_id = os.getenv('AZURE_SUBSCRIPTION')
credentials = UsernamePasswordCredential(client_id = os.getenv('AZURE_CLIENT_ID'),
                                          username=os.getenv('AZURE_USERNAME'),password=os.getenv('AZURE_PASSWORD'))
resource_client = ResourceManagementClient(credentials, subscription_id)
resource_list = resource_client.resource_groups.list()
for resource in resource_list:
    print(resource) 
```

Can **UsernamePasswordCredential** not be used to get all the subscriptions that I have access to? My goal is to iterate over all the subscriptions and resource groups and list all the details for the keyvault in them.

**Comment by chlowell** [comment]
msrestazure and azure-identity credentials have different APIs. The current major version of azure-mgmt-resource, 15, expects azure-identity credentials like `azure.identity.UsernamePasswordCredential`. Lower major versions expect msrestazure credentials like `msrestazure.azure_active_directory.UserPassCredentials`. When you use an azure-identity credential with azure-mgmt-resource 10.x, you'll see an AttributeError about `signed_session`. When you use an msrestazure credential with azure-mgmt-resource 15.x, you'll see an AttributeError about `get_token`. The fix is to use a credential with the right API for your version of ResourceManagementClient. I recommend azure-mgmt-resource 15.x and azure-identity. 

(related: #14499)

**Comment by reach4bawer** [comment]
The follow is the output for the pip freeze command to show the versions that I am using -

```
azure-common==1.1.25
azure-core==1.8.2
azure-identity==1.4.1
azure-keyvault-secrets==4.2.0
azure-mgmt-core==1.2.1
azure-mgmt-resource==15.0.0
azure-mgmt-subscription==0.7.0
```

So I am using the 15.x version. I tried updating all of them but seems like that these are the latest version.

**Comment by chlowell** [comment]
Ah, I see, the issue then is azure-mgmt-subscription's SubscriptionClient, which expects an msrestazure credential. I'm not so familiar with these libraries, but I see there's a `azure.mgmt.resource.subscriptions.SubscriptionClient` that might be all you need to list subscriptions. If you must use azure-mgmt-subscription and want to use the same credential object with ResourceManagementClient and SubscriptionClient, you could use [AzureIdentityCredentialWrapper](https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py). It wraps an msrestazure credential with the azure-identity API, allowing you to use `msrestazure.azure_active_directory.UserPassCredentials` with ResourceManagementClient.

@changlong-liu what's the story with azure-mgmt-subscription? Will it have a track 2 version?

**Comment by changlong-liu** [comment]
Hi @chlowell , 

The azure-mgmt-subscription has not been released as Track2. 
It's in the plan. May have preview version in 1 or 2 month.

**Comment by reach4bawer** [comment]
Thanks everyone for clarifying my doubts. Will close the issue.

**Comment by chlowell** [comment]
Not through azure-identity. The client ID is the ID of the Azure Active Directory application to which the user authenticates. You could in principle use a different library to get a list of applications registered in your tenant then somehow present that to a user for selection, but I doubt that would be helpful. Do you not already know the correct ID as an owner of the application?

**Comment by chlowell** [comment]
Users typically don't need to know the client ID. The developer writing the program knows the Azure AD application registered to represent it and therefore also its client ID. Have you registered an Azure AD application for this?
