### ISSUE TITLE
[BUG Bash] azure-servicebus preview - using a connection string with a newline causes authentication to fail

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-python#14924]
**Describe the bug**

When using the preview package of azure-servicebus I accidentally included a newline at the end of my connection string (I was reading it from a file and forgot to trim it).

This passes the normal connection string validation that we're doing but, predictably, fails when you actually try to connect to Service Bus.

***Exception or Stack Trace***

This is what gets printed to the console - it's probably technically accurate but it confused me for a bit.

`Authentication Put-Token failed. Retries exhausted.`

**To Reproduce**

1. Be me, only me.
2. Read the connections string from a file without trimming the newline
3. Spend 10+ minutes not getting what I'm doing wrong (my fault, I know!)
4. Finally just paste the connection string inline and see it work and realize what I did.

**Expected behavior**

It seems like the connection string validation should fail _or_ when we extract the shared key from the connection string we should not grab non-shared-key characters.

Might be tough but I wanted to at least open up discussion on it.

**Additional context**

I blamed myself. I still blame myself.

**Comment by richardpark-msft** [comment]
CC: @KieranBrantnerMagee , @yunhaoling

**Comment by KieranBrantnerMagee** [comment]
Hah.  Nice find.  I don't see any immediate pitfalls of being "slightly more permissive" and adding this sort of trim (Adam, of course feel free to prove me wrong :P), putting this task on the queue.

**Comment by yunhaoling** [comment]
I think we just need to call `conn_str.strip()` beforehand to be more "permissive"
