### ISSUE TITLE
[Azure Communication Service] Refactor params of begin_reserve_phone_numbers

### ISSUE THREAD

**Issue by HeliWang** [Azure/azure-sdk-for-python#14959]
This is for the code in `Azure:feature/communication` branch, which targets to the Jan 2021 GA release.

**Is your feature request related to a problem? Please describe.**
We are planning to flatten the `options` param which is a  `CreateSearchOptions` type, into several positional params.

There are 6 params in CreateSearchOptions: 
  display_name, description, phone_plan_ids, area_code, quantity and location_options.

5 of these 6 params are mandatory all the time: `display_name`, `description`, `phone_plan_ids`, `area_code`, `quantity`

The only "optional" param is `location_options`: `location_options` is required when the provided `phone_plan_ids` are local phone plans. When the provided `phone_plan_ids` are toll-free, the `location_options` is not needed. 

However 5 params is on the bench. Ideally, we want to have 3 positional params, and making the rest as optional params. 

**Describe the solution you'd like**
Based on the discussion with @xiangyan99, we will decide if any of the required params can be assigned a default value.
Then refactoring the begin_reserve_phone_numbers function.

I will also check if any other function facing the same issue.

**Comment by xiangyan99** [comment]
@HeliWang is this done?
