### ISSUE TITLE
not able to unsintall all azure packages

### ISSUE THREAD

**Issue by weihangChen** [Azure/azure-sdk-for-python#1497]
"pip install azure", installs all packages, but "pip uninstall azure" does not uninstall . uninstall specific package one by one works though

**Comment by lmazuel** [comment]
It's a Python and pip limitation, for all packages that has dependencies, uninstalling the initial package does not uninstall the dependencies.
We recommend using a virtual environment to simplify your installation.

**Comment by ohthehugemanatee** [comment]
In case it helps anyone else: `pip uninstall -y $(pip list |grep azure | awk '{print $1}')` should do the trick.

**Comment by orhanmaden** [comment]
> In case it helps anyone else: `pip uninstall -y $(pip list |grep azure | awk '{print $1}')` should do the trick.

With powershell it would be
```
pip list | Select-String -Pattern azure- | %{ $_.ToString().Split(' ')[0] } | %{ pip uninstall -y $_ }
```
