### ISSUE TITLE
Azure Blob Storage Batch API

### ISSUE THREAD

**Issue by dariustehrani** [Azure/azure-sdk-for-python#14982]
**Is your feature request related to a problem? Please describe.**
I want to leverage the Azure Storage **Blob Batch** capability from within the Azure Python SDK.

**Describe the solution you'd like**
Make the Blob Batch API available including sample code.

**Describe alternatives you've considered**
This seems to be implemented for the dotnet sdk:
[dotnet Blob Batch](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs.Batch)

**Comment by lmazuel** [comment]
Hi @dariustehrani 
This is available part of the SDK, we just didn't do a separated client like C#. Example with the batch delete:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/samples/blob_samples_batch_delete_blobs.py

Or set tier:
https://github.com/Azure/azure-sdk-for-python/blob/97c43d151f2e34430d82c9f8e578c94c38f4a3fa/sdk/storage/azure-storage-blob/tests/test_container.py#L1288-L1335

Does it solve your question? Thanks!
