### ISSUE TITLE
[Message BUS] like SQS receipt_handle  can delete Messsage anywhere

### ISSUE THREAD

**Issue by DzcleisureCN** [Azure/azure-sdk-for-python#15002]
Dose the Message azure.servicebus.Message had a property like receipt_handle it can use to delete or send messages? Receive once get the ReceiptHandle and can delete anywhere?

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/sqs-example-sending-receiving-msgs.html?highlight=receipthandle
receipt_handle = message['ReceiptHandle']

# Delete received message from queue
sqs.delete_message(
    QueueUrl=queue_url,
    ReceiptHandle=**receipt_handle**
)
print('Received and deleted message: %s' % message)

**Comment by KieranBrantnerMagee** [comment]
Hi @DzcleisureCN ,
Can I assume you are on version 0.50.* ? (as opposed to 7.0.0b*)

If so, yes, simply call `message.complete()` as demonstrated in [this sample](https://github.com/Azure/azure-sdk-for-python/blob/7abb21e03cfe3fc749c82f6f990557024d9f3113/sdk/servicebus/azure-servicebus/samples/sync_samples/example_queue_send_receive_batch.py#L43).

Closing this as I hope it answers your question, but if any other clarity is needed or if I've misunderstood don't hesitate to reopen or reach out.
