### ISSUE TITLE
azure-mgmt-core cannot find azure-core 1.9.0 in nightly tests

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#15015]
We take a dep on azure-core 1.9.0 in azure-mgmt-core.

azure-core 1.9.0 is the live version that has not been released.

And mgmt-core complains failure to find azure-core 1.9.0.

Please help to take a look. 

Thanks.

Failed run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=604223&view=logs&j=79d4d8df-e8a9-5bb0-89e9-dbeb29a5038e&t=ba7539ec-ab86-5678-755e-e2a92baaec9b

**Comment by seankane-msft** [comment]
@xiangyan99 closing this issue. azure-core is passing in the pipelines.
