### ISSUE TITLE
Github.io and azure-graphrbac

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#15022]
Didn't find azure-graphrbac:
https://azure.github.io/azure-sdk-for-python/index.html

But if you build the url with version and package name, you can find it:
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/index.html

**Comment by scbedd** [comment]
This was incidentally fixed by  Sima's update to a common landing page. 

[See here](https://azure.github.io/azure-sdk-for-python/graphrbac.html)
