### ISSUE TITLE
azure-mgmt-servicebus MigrationConfigurationName enum crashes docs.ms Publishing

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#15046]
This is because in the SDP schema, an `enum` MUST have a `fields` value that contains the possible values of the enum.

The enum is located at ]`azure.mgmt.servicebus.models.MigrationConfigurationName`](https://github.com/Azure/azure-sdk-for-python/blob/5874ec639dd1553648f6155cb347132ccb7aaefd/sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/models/_service_bus_management_client_enums.py#L95)

This enum, as far as I can tell, has a _private_ field definition. This causes publishing to fail as there are no members of this enum on the other side.

**Comment by danieljurek** [comment]
PR merged. Changes deploying.
