### ISSUE TITLE
get_client_from_json_dict don't work anymore with ResourceManagementClient because of parameter change

### ISSUE THREAD

**Issue by HerwigBachner** [Azure/azure-sdk-for-python#15075]
- **Package Name**:azure-common, azure-mgmt-resource
- **Package Version**:1.1.25, 15.0.0
- **Operating System**: docker python buster 3.8
- **Python Version**: 3.8

**Describe the bug**

The function get_client_from_dict (azure-common) with the ResourceManagementClient Class (azure-mgmt-resources) does not work anymore as it defines the needed parameter credential and cretentials like it was before version 15.x

**Comment by lmazuel** [comment]
Hi @HerwigBachner 
`azure-common` is not compatible with the latest version of SDK that uses `azure-identity` protocol (like azure-mgmt-resource indeed).

We need to discuss how the migration story would go here @chlowell @jongio @johanste

**Comment by jongio** [comment]
@nickzhums

**Comment by nickzhums** [comment]
cc @yonzhan @jsntcy

**Comment by lmazuel** [comment]
We discussed on our team and concluded we do not want to support the JSON or file factory for security purposes, and we don't want to encourage practices that feel unsecure.
We wrote a migration guide for scenario:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/migration_guide.md

Please let me know any feedback or questions related to this.
