### ISSUE TITLE
filter option in query_entities for TableClient is being ignored (Python)

### ISSUE THREAD

**Issue by alejolp** [Azure/azure-sdk-for-python#15094]
Hi, I'm using the Python Data Tables Python API and when filtering entities with `query_entities` for `TableClient`, all entities were returned. No filtering was applied. This code example should fail but it silently returns all the entities in the table:

```python
from azure.data.tables import TableClient
client2 = TableClient.from_connection_string(conn_str=connection_string, table_name="Y")
for row in client2.query_entities("aaa bbb ccc"):
    print(row)
```

Enabling `DEBUG` level in `logging` shows the URL missing the $filter parameter:

```
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://x.table.core.windows.net/Y()'
``` 

Going through the source code, it seems that the filter option is being discarded when constructing the paging object in file `sdk/tables/azure-data-tables/azure/data/tables/_models.py`:

```python
return self._command(
                query_options=self.results_per_page
```

I have to manually edit the `_kwargs` attribute of the returned `ItemPaged` value from the call to `query_entities` and set the key `results_per_page` to a `QueryOptions` instance. For example:

```python
from azure.data.tables import TableClient

client3 = TableClient.from_connection_string(conn_str=connection_string, table_name="Y")
result = client3.query_entities('')
result._kwargs['results_per_page'] = QueryOptions(filter='aaa bbb ccc')

for row in result:
    print(row)
```

It properly fails with an Exception:

```
HttpResponseError: Syntax error at position 7 in 'aaa bbb ccc'.
```

**Comment by seankane-msft** [comment]
@alejolp Thanks for the find and reporting the issue. I was able to reproduce this exact scenario with ease (thanks for the descriptiveness) and I have a PR that should address this in our next release which is planned to go out on Tuesday 11/10.

**Comment by seankane-msft** [comment]
@alejolp We decided to push this fix to the next release. We have a feeling this might affect the paging objects requiring additional clean ups. Apologies for the delay.

**Comment by annatisch** [comment]
Change of plan - we've delayed the release until Thursday so we can get this fix in :)
