### ISSUE TITLE
Unable to create a knowledgeStore definition within a skillset using the Azure Cognitive Search python SDK

### ISSUE THREAD

**Issue by vkurpad** [Azure/azure-sdk-for-python#15097]
SearchIndexerSkillset class does not have an object for the knowledge store definition

https://github.com/Azure/azure-sdk-for-python/blob/eea845a56aa792f5b03b9188cd0180d42a3de4bb/sdk/search/azure-search-documents/azure/search/documents/indexes/models/__init__.py

**Comment by xiangyan99** [comment]
@vkurpad Thank you for reporting this. Yes. There is a gap in our SDK and we are working on it. We will keep you posted.

**Comment by xiangyan99** [comment]
#18461

**Comment by xiangyan99** [comment]
@vkurpad  We added the knowledge store support. It will be available in our next release.
