### ISSUE TITLE
Performance Investigations

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15102]

**Comment by annatisch** [comment]
Performance tests completed and run for Storage (Blobs, FileShare, Datalake) and PRs open waiting for sign-off from Storage team. Hoping to merge this week:
https://github.com/Azure/azure-sdk-for-python/pull/15861
https://github.com/Azure/azure-sdk-for-python/pull/15834
https://github.com/Azure/azure-sdk-for-python/pull/15833

Service Bus tests have been run and are currently in review:
https://github.com/Azure/azure-sdk-for-python/pull/16066

Currently opening issues pending a bit further investigation:
https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aopen+is%3Aissue+label%3APerformance
