### ISSUE TITLE
Migration Guide for Event Hubs

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15105]
Please wait for this issue to be updated with the link to the Migration Guide template.

For Event Hubs, we already have a migration guide. Once the template is ready, this issue is to track the work to get the current guide to follow the template

**Comment by ramya-rao-a** [comment]
Please use the template in this [PR that adds the migration guide to our policies](https://github.com/Azure/azure-sdk/pull/2132)

**Comment by yunhaoling** [comment]
- Migration benefits
  - Cross Service SDK improvements
- Important Changes
  - Client Hierarchy
  - Client Constructors
  - Sending
  - Receiving
  - Receiving with checkpoints
- Addition samples
