### ISSUE TITLE
Bug bash to find samples for Event Hubs that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15111]
_Update from @ramya-rao-a_ 

Review the .Python samples for Event Hubs in the below locations to find the ones that do not use the latest version of the package. Update this issue with the list of samples that need updating.

- [Event Hubs Python samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Event+Hubs%22&type=&language=python)
- [Event Hubs Python samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Event%20Hubs%22&languages=python)

Additionally, ensure the samples that live next to the source code for Event Hubst in this repo shows up in [Event Hubs Python samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Event%20Hubs%22&languages=python). This is done by setting up the right metadata. Ensure that these samples are not outdated.

**Comment by yunhaoling** [comment]
| Samples | Link | Status | Notes | Action |
|--------|---------|------|--------|--------|
| Azure Event Hubs client library for Python Samples | [link](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/eventhub-samples/) | | | |
| Collecting Scheduled Events with Event Hub | [link](https://docs.microsoft.com/en-us/samples/azure-samples/virtual-machines-python-scheduled-events-central-logging/virtual-machines-python-scheduled-events-central-logging/) | | | |
| Azure Event Hubs client library samples with persistent checkpointing for Python | [link](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/eventhub-checkpointstore-samples/) | | | |
| Azure Event Hubs client library samples with persistent checkpointing for Python | [link](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/eventhub-checkpointstore-aio-samples/) | | same title as the sync one, can we improve that? | |

**Comment by swathipil** [comment]
[authenticate_with_sas_token.py, Line 9](https://github.com/Azure/azure-sdk-for-python/blob/da34e9d3bc41ec56c46a1a8c281b4a69d735bdc6/sdk/eventhub/azure-eventhub/samples/sync_samples/authenticate_with_sas_token.py#L9): replace ServiceBus with EventHub

**Comment by ramya-rao-a** [comment]
Nice find @swathipil 

@yunhaoling To your question on sample title, we control that. You can make the change at https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples#azure-event-hubs-client-library-samples-with-persistent-checkpointing-for-python

@swathipil Please use https://github.com/Azure/azure-sdk-for-python/issues/15114 to track the changes for the issues you listed above.

https://docs.microsoft.com/en-us/samples/azure-samples/virtual-machines-python-scheduled-events-central-logging/virtual-machines-python-scheduled-events-central-logging/ uses the REST APIs to send events. I have another tracking item to consider whether or not we should update it to use the Event Hubs package
