### ISSUE TITLE
Add deprecation notes in pypi for Track 1 Storage, KeyVault, Event Hubs packages

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15123]
Please wait for this issue to be updated with the template for the deprecation message

**Comment by lmazuel** [comment]
For KeyVault, please do like:
https://pypi.org/project/azure-storage/

**Comment by mccoyp** [comment]
`azure-keyvault` seems to already have deprecation notes, in that it correctly indicates the package is just now a bundle for installing the track 2 packages (https://pypi.org/project/azure-keyvault/). Does this suffice for the issue?

**Comment by lmazuel** [comment]
@mccoyp it's enough for me indeed, thanks for confirming!

Given the scope of this issue, closing since we have a story for all.
