### ISSUE TITLE
Bug bash to find samples for Service Bus that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15128]
_Update from @ramya-rao-a_ 

Review the Python samples for Service Bus in the below locations to find the ones that do not use the latest version of the Service Bus package. Please note that some of these maybe using the preview version of the latest Service Bus package, these need to be identified as well. Update this issue with the list of samples that need updating.

- [Service Bus Python samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Service+Bus%22&type=&language=python)
- [Service Bus Python  samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Service%20Bus%22&languages=python)

Additionally, ensure the samples that live next to the source code for Service Bus in this repo shows up in [Service Bus Python samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Service%20Bus%22&languages=python). This is done by setting up the right metadata. Ensure that these samples are not outdated.

**Comment by rakshith91** [comment]
https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/15/Doc.aspx?sourcedoc={41b0af1e-8da3-4d88-b296-9b616c3e7b6b}&action=edit&wd=target%28Docs%20bug%20bash.one%7C687ba2d4-5f1a-4990-8625-ba7ad5df6dae%2FPython%20docs%20bug%20bash%7C35edca88-7068-43c2-b36c-1b5d77ed8bbb%2F%29&wdorigin=703

Here are the findings

**Comment by rakshith91** [comment]
- the samples read me has `--pre` flag in the pip install instructions.
-All the samples look good

**Comment by ramya-rao-a** [comment]
The note on preview from samples readme is being removed in https://github.com/Azure/azure-sdk-for-python/pull/15881

Thanks @rakshith91!
