### ISSUE TITLE
StackOverflow cleanup Track 1 references, answer unanswered questions for Service Bus

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15126]

**Comment by rakshith91** [comment]
| Issue | Link | Status | Action | SDK Version | Python Version | Platform |
| ---- |---- | ---- | ---- | ---- | ---- | ---- |
|Receive Topic is Slow|[Link](https://stackoverflow.com/questions/30989043/python-receive-from-azure-service-bus-topic-is-very-slow)| ✔️ | Post a sample in v7 | v0.5 | - | - |
|to send to a queue and listen for the answer in another|[Link](https://stackoverflow.com/questions/56118165/as-you-write-in-a-queue-and-waiting-for-your-response-on-another-using-service-b)| ✔️ |give an example from track2| 0.5 | - | -|
|failed to open session|[Link](https://stackoverflow.com/questions/63826110/azure-servicebus-common-errors-servicebusconnectionerror-failed-to-open-handler)| ✔️ |already have a t2 example| 0.5 | - | - |
|look at the content of message|[Link](https://stackoverflow.com/questions/57436228/how-to-view-c-message-from-azure-service-queue-in-python)| ✔️ |give a t2 example| 0.5 | - | - |
