### ISSUE TITLE
StackOverflow cleanup Track 1 references, answer unanswered questions for Key Vault

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15120]

**Comment by mccoyp** [comment]
Ordered by votes:
| Issue                      | Link                                                                                                | Status               | Action              | SDK Version | Python Version | Platform |
|----------------------------|-----------------------------------------------------------------------------------------------------|----------------------|---------------------|-------------|----------------|----------|
| Retrieving secrets from KV | https://stackoverflow.com/questions/45967706/python-azure-sdk-how-to-retrieve-secrets-from-keyvault | Only track 1 answers | Give track 2 sample | Track 1     | ND             | ND       |

**Comment by lmazuel** [comment]
We need to be sure they are all tagged:
- azure
- azure-sdk
- python
- keyvault
- azure-keyvault

**Comment by lmazuel** [comment]
Closing, since checked with @mccoyp and done
