### ISSUE TITLE
Reference doc bug bash (look for both content issues and rendering issues) for Service Bus

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15127]

**Comment by rakshith91** [comment]
[One note](https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/15/Doc.aspx?sourcedoc={41b0af1e-8da3-4d88-b296-9b616c3e7b6b}&action=edit&wd=target%28Docs%20bug%20bash.one%7C687ba2d4-5f1a-4990-8625-ba7ad5df6dae%2FPython%20docs%20bug%20bash%7C35edca88-7068-43c2-b36c-1b5d77ed8bbb%2F%29&wdorigin=703
)
Here are the findings
