### ISSUE TITLE
azure.mgmt.network.v2019_12_01.models._models_py3.ErrorResponseException: (CannotSpecifyMoreThanOneTargetPropertyInTopology) Cannot have more than one target property in the topology request

### ISSUE THREAD

**Issue by srinu0266** [Azure/azure-sdk-for-python#15156]
**Describe the bug**
networkwatcher get_topology method not accepting multiple target properties

***Exception or Stack Trace***
Traceback (most recent call last):
  File ".\test\aznwmapfetch.py", line 76, in <module>
    nwtopology = networkmgmtclient.network_watchers.get_topology(resource_group, nwatcher.name,TopologyparamObj)
  File "C:\Users\Srinivasa.Majji\AppData\Local\Programs\Python\Python38-32\lib\site-packages\azure\mgmt\network\v2019_12_01\operations\_network_watchers_operations.py", line 507, in get_topology
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.network.v2019_12_01.models._models_py3.ErrorResponseException: (CannotSpecifyMoreThanOneTargetPropertyInTopology) Cannot have more than one target property in the topology request.

**To Reproduce**
SubResourceObj=SubResource(id='resourceid')
TopologyparamObj=TopologyParameters(target_resource_group_name=resourcegroup,target_virtual_network=SubResourceObj)
nwtopology = networkmgmtclient.network_watchers.get_topology(resource_group, nwatcher.name,TopologyparamObj)

***Code Snippet***
SubResourceObj=SubResource(id='resourceid')
TopologyparamObj=TopologyParameters(target_resource_group_name=resourcegroup,target_virtual_network=SubResourceObj)
nwtopology = networkmgmtclient.network_watchers.get_topology(resource_group, nwatcher.name,TopologyparamObj)

**Expected behavior**
when we pass resource group name and virtual network name to topologyparameter class it has to give network map.but it is throwing above error.

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by msyyc** [comment]
please reference this test : https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/network/azure-mgmt-network/tests/test_cli_mgmt_network_watcher.py
