### ISSUE TITLE
Getting all the roles and role definitions

### ISSUE THREAD

**Issue by reach4bawer** [Azure/azure-sdk-for-python#15165]
How do I get all the roles and role definition using the python sdk? Something that is equivalent to [Get-AzRoleAssignment](https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azroleassignment?view=azps-5.0.0) and [Get-AzRoleDefinition ](https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azroledefinition?view=azps-5.0.0).
I tried searching for something that would give IAM policies but so far I couldn't find any documentation or examples/models that I can use. 

Any guidance on this would be appreciated.

**Comment by lmazuel** [comment]
Hi @reach4bawer 
You need `azure-mgmt-authorization`. This unittests file might give some guidance:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/authorization/azure-mgmt-authorization/tests/test_cli_mgmt_authorization.py

Thanks!

**Comment by reach4bawer** [comment]
@lmazuel  How do I translate the principle ids to actual people/groups/services?

**Comment by reach4bawer** [comment]
I found two articles that helped me - [Link 1](https://stackoverflow.com/questions/64866364/resolving-principal-id-in-azure-ad-to-user-service) and [Link 2](https://stackoverflow.com/questions/49895598/python-azure-graph-access-token-missing-or-malformed).
