### ISSUE TITLE
[Service Bus] ATOM API: Allow configuring "rule" while creating subscription

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-sdk-for-python#15171]
.NET SDK provides CreateSubscription overload which allows configuring the rule.
```C#
public virtual Task<Response<SubscriptionProperties>> CreateSubscriptionAsync(CreateSubscriptionOptions options, CancellationToken cancellationToken = default);
public virtual Task<Response<SubscriptionProperties>> CreateSubscriptionAsync(CreateSubscriptionOptions options, CreateRuleOptions rule, CancellationToken cancellationToken = default);
```

This issue is to track adding support for the same in Python V7 SDK.

This feature is important because..
While creating a new subscription to an active topic(messages are actively being sent), there is no way users can stop filling up the subscription before the rule filter is added(since the default rule filter is TRUE).

Original issue: Azure/azure-sdk-for-js#12345

@KieranBrantnerMagee @yunhaoling @rakshith91 @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Moving the milestone to Backlog as this can be added in the next semester as well. Please feel free to add details on how to approach this task and add the "help wanted" label

**Comment by lmazuel** [comment]
Given this operation is available in ARM, we'll update the docstring of the DP operation to suggest to use the ARM API for creation of subcscription with rules, and close the issue.
cc @kashifkhan

**Comment by Zobozodiac** [comment]
Can we please have this added to the python sdk, it’s a standard thing in the azure sdk’s for the other languages as linked above in javascript?
