### ISSUE TITLE
ServiceBus - keep alive not detecting network down.

### ISSUE THREAD

**Issue by aranya-danno** [Azure/azure-sdk-for-python#15202]
- **Package Name**: azure-servicebus
- **Package Version**: 7.0.0b8
- **Operating System**: Mac os
- **Python Version**: 3.8.5

When we are running a receiver with the default max_wait_time = 0, we havent found a way for our service to detect if we have network down or if it has lost it connection to the service bus. The keep alive are just running every 30 seconds as per default which keeps the service running for ever, if we get the network back, the service is not working and we need to restart it to re-establish the connection to the servicebus.

Am im missing something in the docs or in the code no how are supposed to solve above issue?
How do we know that our long-running services are working and connected to the service bus?
Or are you supposed to use the max_wait_time and re-init the connection every x/seconds/minutes if we havent received an message?

Quick example code

```
import asyncio
import logging
import os

from azure.servicebus.aio import ServiceBusClient

logging.basicConfig(level=logging.DEBUG)


async def run():
    try:
        SERVICE_BUS_CONNECTION_STR = os.getenv("SERVICE_BUS_CONNECTION_STR")
        client = ServiceBusClient.from_connection_string(
            SERVICE_BUS_CONNECTION_STR, logging_enable=True)

        async with client:
            receiver = client.get_subscription_receiver(
                topic_name="incident.check.icinga", subscription_name="dev")
            async with receiver:
                async for msg in receiver:
                    print(msg)

    except Exception as e:
        print(e)


if __name__ == "__main__":
    asyncio.run(run())

```

**Comment by yunhaoling** [comment]
hey @aranya-danno, thanks for reaching out.

I'm curious about the "not detecting network down" you mentioned cuz usually network down would trigger `ServiceBusConnectionError` which could be caught in your exception handling part.

Would you be able confirm that the error is not raised timely in a network down condition?
