### ISSUE TITLE
deployment fails with error message: "You have not accepted the legal terms on this subscription"

### ISSUE THREAD

**Issue by itzikorfa** [Azure/azure-sdk-for-python#15258]
- **Package Name**: ResourceManagementClient
- **Package Version**: 
- **Operating System**: windows 7
- **Python Version**:  3.6

**Describe the bug**
when I try to deploy a new VM a new subscription I get the following error:
"cannot be purchased due to validation errors.
...
You have not accepted the legal terms on this subscription:"

is there a python script that can help me bypass this issue
Yizhak

**To Reproduce**
1. deploy a VM using the web portal
2. save the template and parameters 
3. try to automatically deploy using the python SDK

waiting for your answer
Yizhak

**Comment by itzikorfa** [comment]
any news?

**Comment by specterz** [comment]
still the same issue... for some reason `marketplace_client.marketplace_agreements.sign` doesn't allow you to accept..

I see similar issue has been resolved for GO [https://github.com/Azure/azure-sdk-for-go/issues/14768](url)
