### ISSUE TITLE
[text analytics] reconcile top param

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#15264]
For first release, we're just going to release with param `top`. However, metrics advisor is not exposing `top` (exposing it in `by_page` instead, since `top`'s behavior is not what we expect it to be). Need to reconcile this when we start designing for the wrapped library

Make sure to consult @johanste and @xiangyan99

**Comment by kristapratico** [comment]
related: https://github.com/Azure/azure-sdk-for-python/issues/13819
