### ISSUE TITLE
Unable to submit a local training run using WSL

### ISSUE THREAD

**Issue by AllanGraves** [Azure/azure-sdk-for-python#15261]
- **Package Name**: azureml-sdk
- **Package Version**: 1.18.0
- **Operating System**: WSL2 - Ubuntu 20.02
- **Python Version**: 3.8

**Describe the bug**
When attempting to submit a local training run, the job hangs in the 'Starting' status.

I can submit jobs that work using non-WSL setup on the same machine.

**To Reproduce**
1.  Execute the following python script using a WSL distro with appropriate environment (python, azureml-sdk, conda, etc)
    <code>
    ws = Workspace.from_config()
    experiment = Experiment(workspace=ws, name='mnist-training-local')
    env = Environment("user-managed-env")
    env.python.user_managed_dependencies = True
    config = ScriptRunConfig(source_directory='src', script='train-mnist.py', environment=env)
    run = experiment.submit(config)
    run.wait_for_completion(show_output=True)
    </code>

2.   Script hangs here:
<code>
agraves@LAPTOP-I5LSJI5R:~/gitrepos/Public Azure ML-1$ python 04-mnist-pytorch_local.py
RunId: mnist-training-local_1605046048_2a328e04
Web View: https://ml.azure.com/experiments/mnist-training-local/runs/mnist-training-local_1605046048_2a328e04?wsid=/subscriptions/c14a37bd-a658-463c-9d44-9a9326fe5fbe/resourcegroups/TutorialResourceGroup/workspaces/TutorialWorkspace

------- no further execution or output is found, after 12+ hours ----------
</code>

3. Job is successfully registered in Azure: - screenshot 1.  But job never continues further - hangs at 'Starting'.  
4. No logs are produced locally to debug.

===>The same script, submitted from a Powershell Environment works w\o issues.  This points to some sort of network communication issue.

(From Powershell:)
<code>
RunId: mnist-training-local_1605107879_f609d30d
Web View: https://ml.azure.com/experiments/mnist-training-local/runs/mnist-training-local_1605107879_f609d30d?wsid=/subscriptions/c14a37bd-a658-463c-9d44-9a9326fe5fbe/resourcegroups/TutorialResourceGroup/workspaces/TutorialWorkspace

Streaming azureml-logs/70_driver_log.txt

</code>

I have tried with Windows Defender Firewall disabled entirely.

**Expected behavior**
Job is run successfully using a local compute target in the WSL distribution.

**Screenshots**
![image](https://user-images.githubusercontent.com/74313122/98832937-71f42d00-240b-11eb-97fe-9c905cd59411.png)
![image](https://user-images.githubusercontent.com/74313122/98833027-889a8400-240b-11eb-8b38-215e177647c6.png)
![image](https://user-images.githubusercontent.com/74313122/98833209-c0a1c700-240b-11eb-9d07-d555d0498e46.png)

**Additional context**

**Comment by lostmygithubaccount** [comment]
@AllanGraves can you try a new Python environment, and only install the minimal packages like `azureml-core` instead of the full `azureml-sdk`? 

unclear if azureml-sdk supports Ubuntu 20.04, will follow up

**Comment by AllanGraves** [comment]
I've reproduced this in an Ubuntu 18.04 WSL2 instance, using just azureml-core 1.18.0.

There does not seem to be any change in behavior.

**Comment by v-strudm-msft** [comment]
MSFT Internal Ref.: https://msdata.visualstudio.com/Vienna/_workitems/edit/1121262

**Comment by sonnypark** [comment]
Hi @AllanGraves, 
I just would like to check you still have the issue or any other updates on the issue. In case you are still working on it and experiencing the same issue, I can work with you to resolve it. To do that I would like to know more about how you install WSL, sdk, etc and how you are submitting the runs from there. Moreover, if you can repro, I can check and guide you to track the logs. Unfortunately, all the logs would be gone by now for the run you had issue. 
Looking forward to working with you soon.

**Comment by AllanGraves** [comment]
@sonnypark Thanks for working with me.  I followed the directions at https://docs.microsoft.com/en-us/windows/wsl/install-win10 for WSL, and the directions at: https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py for Azure ML.   

As mentioned above, i've reproduced this on Ubuntu 20.04 and ubuntu 18.04.


It's been a while since I used Azure, so I'll give another run to see if it is still happening.

**Comment by AllanGraves** [comment]
@sonnypark looks like it might have reproduced.  

here's a walkthrough of what i ended up doing:
* https://medium.com/swlh/dual-mode-azure-ai-development-c6520e82b6da
* https://allangraves.medium.com/deploying-a-pytorch-model-locally-a42b7bffe8b5

essentially, i used this code to create a new workspace:
```
from azureml.core import Workspace

ws = Workspace.create(name='TutorialWorkspace2',  # provide a name for your workspace
                      # provide your subscription ID
                      subscription_id='c14a37bd-a658-463c-9d44-9a9326fe5fbe',
                      resource_group='TutorialResourceGroup2',  # provide a resource group name
                      create_resource_group=True,
                      location='eastus2')  # For example: 'westeurope' or 'eastus2' or 'westus2' or 'southeastasia'.

# write out the workspace details to a configuration file: .azureml/config.json
ws.write_config(path='.azureml')

```


and this code to run a job locally

```
from azureml.core import Workspace
from azureml.core import Experiment
from azureml.core import Environment
from azureml.core import ScriptRunConfig


# https://docs.microsoft.com/en-us/azure/machine-learning/how-to-set-up-training-targets

if __name__ == "__main__":
    ws = Workspace.from_config()
    ws.get_details()
    ws.list_keys()
    experiment = Experiment(workspace=ws, name='mnist-training-local')

    env = Environment("user-managed-env")
    env.python.user_managed_dependencies = True

    config = ScriptRunConfig(
        source_directory='src', script='train-mnist.py', environment=env, compute_target='local')

    run = experiment.submit(config)
    run.wait_for_completion(show_output=True)
```


the code runs fine, just like before and the job seems to be "starting" for 30 minutes now.

```
agraves@DevTop:~/gitrepos/Public%20Azure%20ML$ python3 04-mnist-pytorch_local.py
RunId: mnist-training-local_1620323989_bda1b4d7
Web View: https://ml.azure.com/runs/mnist-training-local_1620323989_bda1b4d7?wsid=/subscriptions/c14a37bd-a658-463c-9d44-9a9326fe5fbe/resourcegroups/TutorialResourceGroup2/workspaces/TutorialWorkspace2&tid=731b4be3-d1b2-4087-a7b4-d9a6f3fbba74
```


# Versions
```
agraves@DevTop:~/gitrepos$ pip3 list | grep azureml
azureml-automl-core                  1.27.0
azureml-core                         1.27.0
azureml-dataprep                     2.14.2
azureml-dataprep-native              33.0.0
azureml-dataprep-rslex               1.12.1
azureml-dataset-runtime              1.27.0
azureml-pipeline                     1.27.0
azureml-pipeline-core                1.27.0
azureml-pipeline-steps               1.27.0
azureml-sdk                          1.27.0
azureml-telemetry                    1.27.0
azureml-train                        1.27.0
azureml-train-automl-client          1.27.0
azureml-train-core                   1.27.0
azureml-train-restclients-hyperdrive 1.27.0
agraves@DevTop:~/gitrepos$ uname -a
Linux DevTop 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
agraves@DevTop:~/gitrepos$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l
```

**Comment by sonnypark** [comment]
I found your script is still hitting one of our internal services some content info. Can you see any user logs in the link?
Web View: https://ml.azure.com/runs/mnist-training-local_1620323989_bda1b4d7?wsid=/subscriptions/c14a37bd-a658-463c-9d44-9a9326fe5fbe/resourcegroups/TutorialResourceGroup2/workspaces/TutorialWorkspace2&tid=731b4be3-d1b2-4087-a7b4-d9a6f3fbba74
Can you see any log files in the portal? Something like below?
![image](https://user-images.githubusercontent.com/10220522/117526993-58c4d700-af7d-11eb-9f74-4502cad5f05e.png)

**Comment by AllanGraves** [comment]
Nope.  No logs at all.

![image](https://user-images.githubusercontent.com/74313122/117538898-e2a08e80-afd5-11eb-9564-eac0d6a7e8d6.png)

**Comment by sonnypark** [comment]
If exact same script worked ok on other env (as you confirmed), it should be related to environment aml setup on WSL. But it would be hard to debug without logs/traces especially for the local runs. For now I can try to reproduce it on my local setup to see what I can find. It would take some time to setup WSL on my local but will try to get back to you soon. Thanks for your patience!

**Comment by mengyahuUSTC-PU** [comment]
I did not use WSL. My script can run fine when using compute target an Azure resourses A100. However, by setting compute target to 'local' (without changing anything else), it also hangs at 'starting' status. Could you help me on this?

**Comment by yueming-zhang** [comment]
any update on this? I encounter the same issue on Ubuntu 20.04. This is a direct Ubuntu installation, not WSL.

**Comment by KranthiPakala-MSFT** [comment]
@bandsina - Following up to see if there is any update on this issue? - Thank you

**Comment by dmc-au** [comment]
Having the same problem July 2022 running from OS X following this Microsoft guide: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training/train-on-local/train-on-local.ipynb

**Comment by luigiw** [comment]
Hello, I'm closing this issue as v1 SDK is in maintenance only mode. Please consider upgrading to v2 SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2#azure-machine-learning-python-sdk-v2
