### ISSUE TITLE
az account show - Python sdk equivalent

### ISSUE THREAD

**Issue by skatsaounis** [Azure/azure-sdk-for-python#15260]
Hi there,

I want to get the logged in user information, which I would otherwise do with the Azure CLI command `az account show` but I am struggling to find how.

Is there any possible way or is it a feature that is missing?

Kind regards,
Stamatis Katsaounis

**Comment by lmazuel** [comment]
Hi @skatsaounis 

There is no concept of "currently logged user" in SDK, this is a CLI concept. I think we should take a step back and try to understand what are you trying to achieve. If you wish to run a SDK script with CLI currently logged user, there is several solution like `AzureCliCredential` (see https://pypi.org/project/azure-identity/). This will ask the CLI what is the current logged user and import the credentials to run your SDK with them.
If this is not what you are trying to do, could you be more precise?

Thanks,

**Comment by skatsaounis** [comment]
Hi @lmazuel ,
The intention behind this is that I want to get some information from the CLI signed_in_user to consume it in my application. For example: email, display_name etc.

I finally managed to do it but the solution is very ugly and I am wondering if it can be made simpler than that. Please take a look at my snippet:

```python
from azure.identity import DefaultAzureCredential
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.resource.subscriptions import SubscriptionClient
from azure.graphrbac import GraphRbacManagementClient

from my_project_modue import AzureIdentityCredentialAdapter


env_creds = not(os.environ.get('AZURE_CLIENT_ID') and os.environ.get(
    'AZURE_CLIENT_SECRET') and os.environ.get('AZURE_TENANT_ID'))

credentials = DefaultAzureCredential(
    exclude_interactive_browser_credential=False,
    exclude_shared_token_cache_credential=True,
    exclude_visual_studio_code_credential=True,
    exclude_managed_identity_credential=True,
    exclude_environment_credential=env_creds)

resources_credentials = AzureIdentityCredentialAdapter(
    credential=credentials)

subscriptions_client = SubscriptionClient(
    credentials=resources_credentials)

sub_list = subscriptions_client.subscriptions.list()
current_sub = list(sub_list)
tenant_id = current_sub[0].tenant_id

resources_credentials = AzureIdentityCredentialAdapter(
    credential=credentials, resource_id="https://graph.windows.net")
graphrbac_client = GraphRbacManagementClient(
    credentials=resources_credentials, tenant_id=tenant_id)

user_obj = AzureClient.graphrbac_client.signed_in_user.get()
print(user_obj.display_name, user_obj.mail_nickname)
```
> My adapter is an object essential since the different implementations of credentials between clients

**Comment by chlowell** [comment]
You could build your own credential chain instead of configuring `DefaultAzureCredential`:
```py
from azure.identity import ChainedTokenCredential, EnvironmentCredential, InteractiveBrowserCredential

credential = ChainedTokenCredential(EnvironmentCredential(), InteractiveBrowserCredential())
```
That would check environment variables first, and fall back to interactively authenticating a user.

**Comment by skatsaounis** [comment]
@chlowell Thanks for the tip! Regarding the initial question. Is there any simpler way to be able to get user `display_name` or is this the only one? Supposing that the credential here is created the way you are recommending.

**Comment by chlowell** [comment]
Sorry for the late response; I was on vacation. I don't know a simpler way to get a user's display name than from Graph, as you're doing.

**Comment by skatsaounis** [comment]
No worries. In that case let's close this ticket as it served its purpose. 🙂

**Comment by chlowell** [comment]
I'll close this issue then, please open another if you encounter another problem.
