### ISSUE TITLE
[BUG Bash] Bug in usage operation of CostManagementClient

### ISSUE THREAD

**Issue by skatsaounis** [Azure/azure-sdk-for-python#15312]
**Describe the bug**
Inside QueryFilter key `dimension` should be `dimensions`: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/costmanagement/azure-mgmt-costmanagement/azure/mgmt/costmanagement/models/_models_py3.py#L811

***Exception or Stack Trace***

```bash
ErrorResponseException                    Traceback (most recent call last)
<ipython-input-22-225ed7001742> in <module>
     17 # Query
     18 q_definition = QueryDefinition(type='ActualCost', timeframe='Custom', time_period=q_period, dataset=ds_defintion)
---> 19 results = costmanagement_client.query.usage(scope=f'/subscriptions/{SUBSCRIPTION_ID}', parameters=q_definition)
     20 print(list(results.rows)[0][0])

~/.local/my_proj/lib/python3.8/site-packages/azure/mgmt/costmanagement/operations/_query_operations.py in usage(self, scope, parameters, custom_headers, raw, **operation_config)
    108         response = self._client.send(request, stream=False, **operation_config)
    109 
--> 110         if response.status_code not in [200]:
    111             raise models.ErrorResponseException(self._deserialize, response)
    112 

ErrorResponseException: (BadRequest) Invalid query definition: Invalid dataset filter; on a QueryFilter one and only one of and/or/not/dimension/tag can be set.

 (Request ID: xx-xx-xx)

```

**To Reproduce**

***Code Snippet***

```python
from_ts = '2020-11-07T00:00:00+00:00'
to_ts = '2020-11-13T23:59:59+00:00'
resourceGroupName = 'my_resource'

# Aggregation
q_aggregation = QueryAggregation(name='Cost', function='Sum')
# Dimension
dim = QueryComparisonExpression(name='ResourceGroupName', operator='In', values=[resourceGroupName])
# Filter
q_filter = QueryFilter(dimension=dim, dimensions=dim)
# Query
ds_defintion = QueryDataset(aggregation={'totalCost': q_aggregation}, granularity='None', filter=q_filter)
# Date Filter
q_period = QueryTimePeriod(from_property=from_ts, to=to_ts)
# Query
q_definition = QueryDefinition(type='ActualCost', timeframe='Custom', time_period=q_period, dataset=ds_defintion)
results = costmanagement_client.query.usage(scope=f'/subscriptions/{SUBSCRIPTION_ID}', parameters=q_definition)
print(list(results.rows)[0][0])
```

**Expected behavior**

Return a number which is cost in USD

**Setup (please complete the following information):**
 - Python Version: Python 3.8
 - SDK Version: azure-mgmt-resource==10.2.0 (but present in master as well)

**Additional context**
I compared the portal AJAX Request and found `dimensions` rather than `dimension`

**Information Checklist**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by msyyc** [comment]
according to error log "ErrorResponseException: (BadRequest) Invalid query definition: Invalid dataset filter; on a QueryFilter one and only one of and/or/not/dimension/tag can be set. " The error is about QueryFilter. And there seems not 'dimentions':
![image](https://user-images.githubusercontent.com/70930885/100194266-553e1600-2f30-11eb-9e7b-d9e8e7e1d542.png)

**Comment by skatsaounis** [comment]
Ooh ok I placed the wrong text. Please remove the `dimensions` kwarg from filter call and you can see that the error is here.

The problem is that:
1. REST api expects `dimensions` while wrongly saying in error message `dimension`
2. Python auto-generated code expects `dimension`

**Comment by skatsaounis** [comment]
I noticed that with developer tools in Azure portal in Cost Analysis page. If I manipulate the python code to produce JSON body with `dimensions`, that is mimic the query of Azure portal, then everything works

**Comment by msyyc** [comment]
> I noticed that with developer tools in Azure portal in Cost Analysis page. If I manipulate the python code to produce JSON body with `dimensions`, that is mimic the query of Azure portal, then everything works

Hi, service team, please help distinguish whether there is problem in swgger json or in python auto-generated code?

**Comment by skatsaounis** [comment]
To help the investigation I think I found the relevant schema in swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-09-01/costmanagement.json#L35

**Comment by skatsaounis** [comment]
Hi @Karishma-Tiwari-MSFT! This PR https://github.com/Azure/azure-sdk-for-python/pull/19144 seems to have solved the issue.
