### ISSUE TITLE
Pagination using Continuation Tokens

### ISSUE THREAD

**Issue by abhijitnathwani** [Azure/azure-sdk-for-python#15311]
I am trying to implement pagination using APIs with Azure Cosmos Python SDK. From what I have read and understand, we need continuation tokens. However, I cannot find any function in the SDK documentation [here](https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.container.containerproxy?view=azure-python#methods), that would consume the token and return the remaining data from the queries. 
My flow currently:

* Initialize CosmosClient
* Get database object
* Get container object
* Query the container, set max_count_size=1
* Get Paged response, send it as a response to the API call

Now if I want the next page from the query, where do I pass the continuation token so that I can get the next page based on the previous query for API call?

```
from azure.cosmos import exceptions, CosmosClient, PartitionKey
endpoint = "https://xxxxxxxx.documents.azure.com:443/"
key = '===xxxx===xxxx===xxx'

client = CosmosClient(endpoint, key)
database_name = 'test'
database = client.create_database_if_not_exists(id=database_name)
container_name = 'FamilyContainer'
container = database.get_container_client(container_name)
query = "SELECT * FROM c "
items = container.query_items(
        query=query,
        max_item_count=1,
        enable_cross_partition_query=True
    )

pager = items.by_page()
first_page = list(pager.next())
print("first page: ", first_page )
```

Now, if I want the next page in another API call, where do I pass the continuation token? 
Azure SDK versions:

```python
$ pip freeze | grep azure
azure-core==1.9.0
azure-cosmos==4.2.0
azure-nspkg==3.0.2
azure-storage-blob==12.6.0
azure-storage-nspkg==3.1.0
```

**Comment by zfoster** [comment]
Hey @abhijitnathwani,

Unfortunately this feature is not supported in the SDK.

Our recommendation is to ideally model your data such that cross partition queries are not needed. Here is a good guide of some examples of how to do this: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-model-partition-example

While cross partition queries are possible with our SDK, it's often not a scalable solution for many applications. The state of the query must be serialized into the continuation token. Some are difficult to represent at all, like DISTINCT or GROUP BY. The entire result of the query would be needed in the continuation token.

At small scales this can be ok, but imagine as an application scales to hundreds of partitions, a single end user query can result in thousands of backend requests before a result can be returned to the user. Aggregate functions are especially problematic here as their results often require the SDK to drain all pages of results from a single partition.

That said, it's possible this feature will someday be built into the SDK, however at this time it's not a part of our immediate plans.

**Comment by abhijitnathwani** [comment]
Hi @zfoster 
`cross-partition-queries` is not mandatory. I cannot achieve the same behavior with `partition-key` as well. Is there any way I could split let's say 100 records in 5 API requests replying 20 records each time?
