### ISSUE TITLE
need ways to get operation_id and correlation_id from LRO polling objects

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#15320]
- **Package Name**: n/a
- **Package Version**: n/a
- **Operating System**:n/a
- **Python Version**: n/a

**Describe the bug**
When we report misbehaviors on the RP side of Azure ops, the teams owning the RP usually want to know the operation_id and/or correlation_id of the failing op. The LRO polling objects know the ID, because they must use it to poll the operation. What we need is an accessor that lets us extract whatever information is available- request_id, operation_id, correlation_id from the LRO op. If the info is not available, the API should have some well-defined behavior. Ideally, return None, but raising a specific catchable exception for this case is fine as well. If the latter, we must be able to identify this case specifically without scraping strings from the exception.

**Comment by lmazuel** [comment]
This is a good issue, and we should address it. We started already, but I can't give ETA at this point.
