### ISSUE TITLE
is ADF V1 supported?

### ISSUE THREAD

**Issue by saulcruz** [Azure/azure-sdk-for-python#1532]
First of all, thanks for this library, I've been trying to find my data factories (v1) in my resource group and it can only find the v2 data factories, does this library only support ADF v2? if so, is there a workaround?

My resource group is in location US East 2
MY data factory V1 is in US East

```
    rg_name = 'rg-name-useast2'
    df_name = 'df-name-useast'

    subscription_id = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'
    credentials = ServicePrincipalCredentials(client_id='xxxxxxx-xx-',
                                              secret='xxxxxxx=',
                                              tenant='xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx')
    adf_client = DataFactoryManagementClient(credentials, subscription_id)
    test = adf_client.factories.get(resource_group_name=rg_name, factory_name=df_name)
    print(test)
```

Error

`b'{"error":{"code":"ResourceNotFound","message":"The Resource \'Microsoft.DataFactory/factories/df-name-useast\' under resource group \'rg-name-useast2\' was not found."}}'`

**Comment by lmazuel** [comment]
Hi @saulcruz 
I think this is supporting only v2, but maybe @hvermis has not insights about this.

**Comment by hvermis** [comment]
ADF Python SDK supports only our V2. For V1 we have Powershell and C# only.

Sent from my iPhone

On 16 հոկ, 2017թ., at 9:28, Laurent Mazuel <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @saulcruz<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsaulcruz&data=02%7C01%7Chvermis%40microsoft.com%7Ca2d74f97f6894558638708d514b2f27c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636437681158126232&sdata=08ZRwXZ9HLe%2FiJ5hQw3Ncr2edAIhmMhofpaajuNr8G0%3D&reserved=0>
I think this is supporting only v2, but maybe @hvermis<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhvermis&data=02%7C01%7Chvermis%40microsoft.com%7Ca2d74f97f6894558638708d514b2f27c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636437681158126232&sdata=oJ64BsCgvI19sNs19VmDuMS4cobPFYlljADchpSgZMU%3D&reserved=0> has not insights about this.

**Comment by lmazuel** [comment]
Thanks @hvermis !

**Comment by saulcruz** [comment]
thanks @hvermis
