### ISSUE TITLE
Can't close the client using both context manager and close() function

### ISSUE THREAD

**Issue by phamhoangtuan** [Azure/azure-sdk-for-python#15358]
- **Package Name**: azure.storage.filedatalake
- **Package Version**: 12.2.0
- **Operating System**: Linux-4.15.0-1096-azure-x86_64-with-debian-9.5
- **Python Version**: Python 3.6.12

**Describe the bug**
Using DataLakeServiceClient class to connect to Azure Data Lake service from python client. After that, I want to close the connection socket by calling close() function or using context manager. After that I have the `AttributeError: 'DataLakeServiceClient' object has no attribute '_client'`

**To Reproduce**
1. account_name = 'test_account'
2: sas_key = 'test_key'
3a. service_client = DataLakeServiceClient(
        account_url='https://{}.dfs.core.windows.net'.format(account_name),
        credential=sas_key
    )
4a. service_client.close()

3b. with DataLakeServiceClient(
        account_url='https://{}.dfs.core.windows.net'.format(account_name),
        credential=sas_key
    ) as service_client:
4b.    print(service_client)

**Expected behavior**
the service client closed successfully

**Screenshots**

**Additional context**

**Comment by xiafu-msft** [comment]
Hi @phamhoangtuan

Thanks for reporting this bug, we will fix it later!

**Comment by tasherif-msft** [comment]
Hi @phamhoangtuan! a PR with the fix to this issue has been submitted here https://github.com/Azure/azure-sdk-for-python/pull/16414 :)
Sorry for the delay on this.

Thank you
