### ISSUE TITLE
Return error message instead of successful object on access denied

### ISSUE THREAD

**Issue by mfernee** [Azure/azure-sdk-for-python#15418]
[__init__.py.txt](https://github.com/Azure/azure-sdk-for-python/files/5558454/__init__.py.txt)

I have an ask for a clear error message. This problem occurs when I have the firewall in front of ADLS blocking the Function App (where this code runs)

In the code below, I successfully got a file_system_client. And I got an 'object paths' with the file_system_client.get_paths(path).
Iterating through all the paths gave an 'dict' object has no attribute 'iter' error.
Though technically, there was no attribute ‘iter’, I expected something along the lines of ‘authorization failure’ or ‘network access blocked’.
And I expected to get that authorization or network failure when I created the file_system_client, because that client shouldn’t be possible.

        file_system_client = service_client.get_file_system_client(file_system=storageAccountFileSystem)

        paths = file_system_client.get_paths(path)

        logging.info(f'INFO: Got list directory {paths}')

        for p in paths:
            new_row = { 'FileName': p.name, 'FileSize': p.content_length}
            df_files = df_files.append(new_row, ignore_index=True)

**Comment by PeaceDeveloper** [comment]
Hello, I have the same problem. Any solution? Is there a workaround?

**Comment by xiafu-msft** [comment]
Hi @mfernee and @PeaceDeveloper 

Thanks for reaching out.
Did you configure the firewall according to the doc? https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security
SDK just throw what service returns. If you didn't get an error message that means server accepted your requests.

**Comment by mfernee** [comment]
1.  I don’t know of a workaround to get an error message when access is denied. You will just have to work with try catch blocks to prevent errors further down the line.
  2.  My solution was giving my function app access: the firewall of the storage account was enabled. So, I had to add the VNet of the function app to allow it to pass through.

Thanks,
Marcel

**Comment by mfernee** [comment]
Good morning,

Yes, I configured the firewall like that on the storage account.

If that means that the service still accepts the requests, even though the firewall should block it, there is something fishy going on.

Thanks,
Marcel

**Comment by PeaceDeveloper** [comment]
Hi,

@mfernee was a good observation. @xiafu-msft, I think that I have a problem of firewall because I don't configurate it. Thank's!

But I think that the error message could be different.

My code block is very simple:

`try:        
        file_system_client = service_client.get_file_system_client(file_system="test")        
        paths = file_system_client.get_paths(path="/prd/structured")

        print(paths)
        # printing <iterator object azure.core.paging.ItemPaged at 0x7f30b0982e80>

        for path in paths:
            print(path.name + '\n')
    except Exception as e:
        print(e) 
        # printing 'dict' object has no attribute 'iter'`

**Comment by tasherif-msft** [comment]
Hi @PeaceDeveloper and @mfernee, could you please confirm that the error message is no longer ```'dict' object has no attribute 'iter'``` in our most recent datalake release - 12.2.2

**Comment by mfernee** [comment]
I am no longer involved at the customer where we had this project. Sorry, but I can't reproduce it there anymore.

**Comment by tasherif-msft** [comment]
Sounds good. It should be resolved with our recent released. I will close this issue in the meantime!
Feel free to reopen if anything.
