### ISSUE TITLE
[ServiceBus] Clean up pylint ignores where applicable

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#15432]
**Is your feature request related to a problem? Please describe.**
We aspire to be pylint green, but aren't always perfect.  There are places that pylint ignores are emplaced, that could potentially be improved.  On the easier end would be things like line length, but one should feel empowered to address any that they think are safe and self-contained.

**Describe the solution you'd like**
Address the code to prevent the need for the pylint ignores, as applicable.

**Comment by swathipil** [comment]
update type hint `dict` to `Dict/Mapping`.
