### ISSUE TITLE
You should update that readme file. There are lots of typos and errors in it.

### ISSUE THREAD

**Issue by BillmanH** [Azure/azure-sdk-for-python#15446]
- **Package Name**: any
- **Package Version**: any
- **Operating System**:any
- **Python Version**: any

**Describe the bug**
There are a lot of typos in this doc and it is difficult to get through. https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/digitaltwins/azure-digitaltwins-core

Here are the things I have noticed so far:
* MSFT is [aware of a typo in the code](https://github.com/Azure/azure-sdk-for-python/issues/14918) and is apparently considering potential fixes. 
* You do not have to load the client secret into your environment variables. Skip all that and use the `AzureCliCredential` if you are developing locally and not building an app. 
* There are no `import` statements in the code examples. You will have to figure out where those methods are on your own. Some things are from other packages such as `json` and `uuid`.
* `serviceClient` and `service_client` are used interchangably as well as some other naming issues. 
* The doc references the query language that is at [review.docs](https://review.docs.microsoft.com/azure/digital-twins/concepts-query-language) (and inaccesible to non MSFT employees), [Here is the public doc](https://docs.microsoft.com/en-us/azure/digital-twins/concepts-query-language).

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zolvarga** [comment]
Hello Bill,

Thank you for the review!

I am checking in the fixes for your comment except for the followings:
- I don't think using the import statements in the Readme file is appropriate. We are providing code snippets in the Readme and not runnable code. Also in the Readme we stated clearly which sample is the snippet from. Obviously if you want to start coding you should open the related sample file and you can find everything there. All the samples are runnable after you set up the environment variables.
- We can debate what approach we should prefer in the samples but we choose the environment variable setup. I think that is the most convenient in all cases but especially if you are using VSCode.

Thanks,
Zoltan

**Comment by BillmanH** [comment]
Hey, thanks Zoltan,

My two cents (but it's totally an opinion):
* I think the import statements show the user from which imported element. Generally it is common to show the import statements (for example the azureml sdk always shows import statements). It's just saves time for the person who is following along with your examples. Part of the Readme is showing how the methods are organized in the SDK. 
* environment variables require you to hard code access keys into flat files on your local machines, using AD login is more secure and allows MFA. It also requires a lot less setup for people using the code for the first time. 

Moreover, thanks for this SDK! It is the gateway to ADT for data scientists.
