### ISSUE TITLE
The SDK is not friendly and is lack of code example and API description

### ISSUE THREAD

**Issue by liualexiang** [Azure/azure-sdk-for-python#15465]
**Is your feature request related to a problem? Please describe.**
Azure Python SDK API is not friendly, the offical docs doesn't provide most of API samples and lake of API description. 

#### For Example the ACR package: azure-mgmt-containerregistry==2.8.0, let's assue someone want to use import_image() API, let's see what information our document provided:** 
https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerregistry/azure.mgmt.containerregistry.v2019_04_01.operations.registriesoperations?view=azure-python#import-image-resource-group-name--registry-name--parameters--custom-headers-none--raw-false--polling-true----operation-config-

How to use the import_image() function? and within the import_image() function, we need to specify the "ImportImageParameters ", but "ImportImageParameters " is a class,  how to use the class? we need also to specify the "source" by specify "ImportSource" class, how to use the class? It's even not a method.

I did a lot of debug, and finally find the solution.  First, we need to initial  the acrclient:
acrclient = acr.ContainerRegistryManagementClient(credentials=credentials, subscription_id=SUBSCRIPTION_ID)

then we need to create import source:
  import_img_src = acrclient.models().ImportSource()

then create import parameter:
import_img_para=acrclient.models().ImportImageParameters()

then create import_image():
 imp_img = acrclient.registries.import_image()

**But you can see, why the import source is fromacrclient.models(), but import_image is from acrclient.registries(without ())? The offical document has no any information regarding this. I think anyone who need use this API should take more than 1 days to debug. Please enhance the API usage document **

**Describe the solution you'd like**
Please provide a detailed API usage description and example.

**Describe alternatives you've considered**
See the information above, I believe I've provided enough information to you. If you need more, please reply me.

**Additional context**
See the information above, I believe I've provided enough information to you. If you need more, please reply me.

**Comment by liualexiang** [comment]
I have to say, a friendly API is very important to customers who are using Azure. Compare to other cloud provider, for example AWS, AWS provide more friendly SDK API description and examples, it's very easy to hands on. A friendly API can reduce customer much more time to develop their application, it's even more important than providing more addentional features.

**Comment by nickzhums** [comment]
@liualexiang would love to hear your thoughts on how we can improve the API

In addition, we have code samples here on this repo: https://github.com/Azure/azure-sdk-for-python/issues/15465

**Comment by msyyc** [comment]
@liualexiang It's not easy to use for python SDK docs as you said and we add some code examples to show how to use it.(https://github.com/Azure-Samples/azure-samples-python-management/tree/master/samples). And we will add more examples and improve the readability of docs.

**Comment by toddysm** [comment]
@liualexiang we are working with the SDK team to improve the SDK documentation and the samples for ACR. This though will take some time. Will keep you updated.

cc:// @yugangw-msft

**Comment by OS-nestorcolt** [comment]
shame on microsoft
