### ISSUE TITLE
Experiment.submit(tags=dict()) method does not apply tags to run

### ISSUE THREAD

**Issue by areed145** [Azure/azure-sdk-for-python#15480]
- **Package Name**: azureml-defaults
- **Package Version**: 1.15.0
- **Operating System**: linux
- **Python Version**: 3.7

**Describe the bug**
Experiment.submit(tags=dict()) method does not apply tags to run

**To Reproduce**
1. Use Experiment.submit() with tags param

**Expected behavior**
Tags should appear with run in AML interface and .get_tags() method

**Comment by lostmygithubaccount** [comment]
just tested with both 1.15.0 and latest - both work fine - @areed145 can you provide more details? 

![image](https://user-images.githubusercontent.com/54814569/100918496-68e80000-348d-11eb-8f55-ebcc8e8b8f48.png)

![image](https://user-images.githubusercontent.com/54814569/100918518-71d8d180-348d-11eb-8405-892e360cde10.png)

**Comment by swatig007** [comment]
closing based on previous comments and no updates.
