### ISSUE TITLE
Create virtual network using the sdk

### ISSUE THREAD

**Issue by swatisinghi** [Azure/azure-sdk-for-python#155]
I see that there is support added for specifying an existing virtual network name when creating the virtual machine - https://github.com/Azure/azure-sdk-for-python/issues/79 

But I see no support for creating a virtual network through the SDK (correct me if I am wrong). Can we have support for creating networks through the SDK. I see this functionality in the node js sdk.

**Comment by conrado** [comment]
+1

**Comment by gotostack** [comment]
+1, also need the python SDK of networking management.

**Comment by huguesv** [comment]
This will be covered by the 'new wave' of Python SDK as hinted earlier by guangyang.  We should have something we can announce/preview in a few months.

Back in November, we added pass-through functions that make it possible to use the existing service management class and its authentication code and call REST APIs that we don't support yet.  You have to handle the xml serialization in the client code.
https://github.com/Azure/azure-sdk-for-python/blob/master/azure/servicemanagement/servicemanagementclient.py#L119

You can see some uses of it in these tests:
https://github.com/Azure/azure-sdk-for-python/blob/master/tests/test_servicemanagementservice.py#L583

The REST api for network management:
https://msdn.microsoft.com/en-us/library/azure/jj157182.aspx

I know it's a poor solution, but I wanted to bring it up in case this helps anyone until we have proper support for network management.

**Comment by dazwin** [comment]
@huguesv, you mention in #335 that you have a network implementation - is this something you can share?

**Comment by djcrabhat** [comment]
:+1:  need this badly

**Comment by lmazuel** [comment]
Hi all,

We juste release SDK 2.0.0a1 which should cover this feature. We release in alpha currently, any feedback or comments is welcome!
Thank you!

**Comment by BhaviniVelankani** [comment]
Hi all,

I need python api for virtual network creation badly.
Is there any API already?
Then please tell the details about it ASAP.

**Comment by lmazuel** [comment]
Hi,

Virtual Network is covered now. You have an example of creation here:
http://azure-sdk-for-python.readthedocs.org/en/latest/resourcemanagementcomputenetwork.html

You have the detailed Network client operations here:
http://azure-sdk-for-python.readthedocs.org/en/latest/ref/azure.mgmt.network.html

I close this issue since now Virtual Network is available (initial inquiry). Please feel free to open a new issue if you find a problem using the Virtual Network SDK.
