### ISSUE TITLE
SDK tie-in to replicationProtectedItems

### ISSUE THREAD

**Issue by DataDecay** [Azure/azure-sdk-for-python#15508]
**Is your feature request related to a problem? Please describe.**
I am unable to find an equivalent method in "recoveryservices" or "recoveryservicesbackup", for the below endpoint.

GET https://management.azure.com/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationProtectedItems?api-version=2018-07-10

**Describe the solution you'd like**
extend either "recoveryservices" or "recoveryservicesbackup" to include the data from the endpoint.

**Describe alternatives you've considered**
The alternative right now is I make a raw request to the above endpoint.

**Comment by pvrk** [comment]
@sideeksh: Can you please take a look at this?

**Comment by pvrk** [comment]
This is replication protected items related issue. @Sharmistha-Rai

**Comment by Sharmistha-Rai** [comment]
@DataDecay - is this the documentation you're looking for - https://docs.microsoft.com/en-us/rest/api/site-recovery/recoverypoints/listbyreplicationprotecteditems

**Comment by DataDecay** [comment]
> @DataDecay - is this the documentation you're looking for - https://docs.microsoft.com/en-us/rest/api/site-recovery/recoverypoints/listbyreplicationprotecteditems

These are the REST endpoints I'm looking for and currently using, I was hoping there was tie in to the azure python sdk. Maybe I missed something in your link, but i did not see refrence to the sdk.

**Comment by Sharmistha-Rai** [comment]
@DataDecay - I'm inquiring about the query and will get back as soon as I have some update.

**Comment by Sharmistha-Rai** [comment]
@DataDecay - as of now there is no python SDK generated for ASR.

**Comment by DataDecay** [comment]
@Sharmistha-Rai Any way we can get a feature request in for that? i find it odd, that a strong point that no other cloud provider implements "correctly" (In My Opinion), is not leveraged in the SDK.

**Comment by Sharmistha-Rai** [comment]
@DataDecay -  thanks for requesting for this feature. I have added this item to our backlog. We are in talks with the SDK team to see how and by when we can bring this in for ASR. 

Please close this thread for now. Feel free to reopen if you have any more related queries.

**Comment by Sharmistha-Rai** [comment]
#sign-off

**Comment by Sharmistha-Rai** [comment]
#close

**Comment by KranthiPakala-MSFT** [comment]
@DataDecay , We will now proceed to close this thread based on the update form @Sharmistha-Rai . Feel free to reopen if you have more related queries. 

Thank you
