### ISSUE TITLE
azure.mgmt.datafactory.models.error_response.ErrorResponseException: The template validation failed: 'The number of template actions limit exceeded: maximum '500' and actual ..

### ISSUE THREAD

**Issue by saulcruz** [Azure/azure-sdk-for-python#1552]
This is a DataFactoryManagementClient question

When creating pipelines runs of over 40 activities, I get the error

azure.mgmt.datafactory.models.error_response.ErrorResponseException: The template validation failed: 'The number of template actions limit exceeded: maximum '500' and actual '730'.'.

Not sure of what template actions are, have you seen something like this?

This is how I run it
```
# act_adls_to_azsql_objects is a list of 56 activities

pl_resource_object = PipelineResource(activities=act_adls_to_azsql_objects, parameters=params_for_pipeline)

pipelines.create_run(rg_name, df_name, pipeline_name, {})
```

Is this an Azure Data Factory limitation? according to the official documentation https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#data-factory-limits there is a limit of 30 (I'm running 40) activities per pipeline , the error message however doesn't say that

**Comment by lmazuel** [comment]
@hvermis please, any ideas?

**Comment by sharonlo101** [comment]
Hi @saulcruz this is a bug on error messages on part. The limit of 30 activities is put into place for recommended design on # of activities in a pipeline (we found in the past, customers were putting lots of activities in a single pipeline), which diminished both performance and the monitoring experience. To split up your pipelines, we also have an "Execute Pipeline" activity where you can easily chain pipelines. We'll update when this error message is fixed.
