### ISSUE TITLE
service_client.get_model only returns a small amount of the information for a model.

### ISSUE THREAD

**Issue by BillmanH** [Azure/azure-sdk-for-python#15556]
**Is your feature request related to a problem? Please describe.**
The `service_client.get_model` function only returns a small portion of the information. This requires locally storing documents about models, and guessing what might actually be in the model that exists in the cloud. Most important attributes that are omitted are:
* properties
* relationships
* comments

**Describe the solution you'd like**
Many ways to solve this problem:
* `service_client.get_model().as_dict()` should return all of the info that you need for that model. 
* add `model.properties` and `model.relationships` to get those values separately. 

**Describe alternatives you've considered**
The only other option is to keep a local copy of your models and just hope that ADT is working correctly. For comments, since there is no way to pull them from the SDK, it makes you wonder why have them at all.

**Comment by BillmanH** [comment]
Adding some context here:

```python
get_model = service_client.get_model(patron_model_id)
get_model.as_dict()
```
returns this dict:
```
{'display_name': {'en': 'Patron'},
 'description': {'en': 'As an example, contains all of the properties possible in the DTDL.'},
 'id': 'dtmi:billmanh:patron;1',
 'upload_time': '2020-11-19T02:14:27.21094Z',
 'decommissioned': False}
```

However this is the data from my model:
```
{
    "@id": "dtmi:billmanh:patron;1",
    "@type": "Interface",
    "displayName": "Patron",
    "contents": [
        {
            "@type": "Command",
            "name": "order",
            "request": {
                "name": "wallet",
                "displayName": "available money",
                "description": "how much the patron is willing to spend",
                "schema": "double"
            },
            "response": {
                "name": "decision",
                "displayName": "consumer decision",
                "schema": "string"
            }
        },
        {
            "@type": "Property",
            "name": "totalWaitTime",
            "displayName": "Total Wait Time",
            "schema": "double",
            "comment": "time in seconds that the customer is required to wait"
        },
        {
            "@type": "Property",
            "name": "satisfaction",
            "displayName": "Customer Satisfaction",
            "schema": "integer",
            "comment": "1-10 scale of how likely to recommend to a friend (NPS)"
        },
        {
            "@type": "Relationship",
            "name": "locatedIn"
        }
    ],
    "@context": "dtmi:dtdl:context;2",
    "comment": "This should represent one restaurant visitor.",
    "description": "As an example, contains all of the properties possible in the DTDL."
}
```

[The code for this can be found here.](https://github.com/BillmanH/learn-dt/tree/main/notebooks)

**Comment by annatisch** [comment]
Thanks @BillmanH!
@zolvarga could you please take a look?

**Comment by zolvarga** [comment]
Hello Bill,

Please try the same API with defining in the kwargs the "include_model_definition=True";
That would give you the whole model definition.
In your code example:
get_model = service_client.get_model(patron_model_id, include_model_definition=True)

Please let me know if that works
-Zoltan

**Comment by zolvarga** [comment]
Closing as the guidance worked for the customer.
