### ISSUE TITLE
Support Contextual Feature Filters in AppConfiguration SDK.

### ISSUE THREAD

**Issue by leonids2005** [Azure/azure-sdk-for-python#15558]
**Is your feature request related to a problem? Please describe.**
We have defined a GitOps procedure to manage feature filters in AppConfiguration.
Every feature is deployed behind a Feature Flag.  
For .NET services, we have implemented a Contextual Feature Filter to evaluate FeatureFlag based on user context and make the feature available for only a specific set of users/clients.  Unfortunately, there is no support for Feature Flags in Python SDK and obviously no support for Feature Filters.

**Describe the solution you'd like**
For Python SDK for App Configuration, we would like to have support for Contextual Feature Filters in the same way it is supported in .NET SDK. This is required to make a specific feature available for a specific set of users based on the context (for example user details in HttpContext)

Here are details from .NET SDK documentation.

Contextual feature filters implement the IContextualFeatureFilter<TContext> interface. These special feature filters can take advantage of the context that is passed in when IFeatureManager.IsEnabledAsync<TContext> is called. The TContext type parameter in IContextualFeatureFilter<TContext> describes what context type the filter is capable of handling. This allows the developer of a contextual feature filter to describe what is required of those who wish to utilize it. Since every type is a descendant of an object, a filter that implements IContextualFeatureFilter<object> can be called for any provided context. To illustrate an example of a more specific contextual feature filter, consider a feature that is enabled if an account is in a configured list of enabled accounts.

**Describe alternatives you've considered**
An alternative is to implement this functionality by ourselves. But this feature is required for everybody who will be using FeatureFlags in AppConfiguration.

**Comment by xiangyan99** [comment]
This is a feature request for provider. 
Moved the issue to AppConfiguration repo https://github.com/Azure/AppConfiguration/issues/464.

**Comment by xiangyan99** [comment]
Moved to app config repo
