### ISSUE TITLE
Monitor: the ErrorResponse in the ErrorResponseException is not deserialized.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-sdk-for-python#1556]
The following payload in a 400 response is not correct deserialized:
```
b'{"Code":"UnsupportedCondition","Message":"The category field is missing in the condition."}'
```
Debug info, note both code and message proeprties are `None`
```
> /Users/troydai/code/azure-cli/env/lib/python3.6/site-packages/msrest/exceptions.py(138)__init__()
-> if self.error is None:
(Pdb) l
133  	        self.message = None
134  	        self.response = response
135  	        try:
136  	            if resp_type:
137  	                self.error = deserialize(resp_type, response)
138  ->	                if self.error is None:
139  	                    self.error = deserialize.dependencies[resp_type]()
140  	                # ARM uses OData v4, try that by default
141  	                # http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html#_Toc372793091
142  	                # Code and Message are REQUIRED
143  	                try:
(Pdb) pp self.error.code
None
(Pdb) pp self.error.message
None
(Pdb)
```

The msreset seems to expect a different payload structure:
https://github.com/Azure/msrest-for-python/blob/909652a49c72c8b1625a2561ca10e256aba21a4c/msrest/exceptions.py#L141
```
                try:
                    self.message = "({}) {}".format(
                        self.error.error.code,
                        self.error.error.message
                    )
                except AttributeError:
                    # Try the default for Autorest if not available (compat)
                    self.message = self.error.message
```

**Comment by lmazuel** [comment]
@troydai msrest is case sensitive, since JSON is case sensitive :/

**Comment by lmazuel** [comment]
@troydai This code implies there is a custom Exception used in the Swagger. Do you have the name of the model? So we can look into the model how the JSON is described?

**Comment by troydai** [comment]
No, I get these from debugging. I haven't looked into the swagger yet.

**Comment by lmazuel** [comment]
What was the call you made?

**Comment by troydai** [comment]
Do you need the SDK invocation of the HTTP request?

**Comment by troydai** [comment]
https://github.com/Azure/azure-sdk-for-python/blob/371cb4a2aff8b767f01eb5a976ea0cc9c07717fd/azure-monitor/azure/monitor/models/error_response.py#L26

**Comment by lmazuel** [comment]
Re-checked, still broken.

**Comment by asheniam** [comment]
Can you clarify what is the latest issue?  Is this with activity logs or activity log alerts?  Do you have the error?

**Comment by lmazuel** [comment]
@asheniam This issue will be fixed automatically by https://github.com/Azure/azure-rest-api-specs/issues/1907

**Comment by asheniam** [comment]
Thanks for the clarification

**Comment by kairu-ms** [comment]
'az monitor metrics alert create' command also has this issue
