### ISSUE TITLE
create_item overrides any setting by the user

### ISSUE THREAD

**Issue by peterskurt** [Azure/azure-sdk-for-python#15569]
In "https://azuresdkdocs.blob.core.windows.net/$web/python/azure-cosmos/4.2.0/_modules/azure/cosmos/container.html#ContainerProxy.create_item"

The create item is supposed to let the user modify the option: disableAutomaticIdGeneration
In the source code, though; this variable is hard set:
```
        request_options = build_options(kwargs)
        response_hook = kwargs.pop('response_hook', None)

        **request_options["disableAutomaticIdGeneration"] = True**
```

Here's the following call where the behaviour is actually checked and handled. 
 
```
       if (not document.get('id') and
            not options.get('disableAutomaticIdGeneration')):
            document['id'] = base.GenerateGuidId()
```

Obviously, the user has lost the ability to set this parameter with the current implementation!

**Comment by southpolesteve** [comment]
@peterskurt Thanks for reporting
@zfoster Can you take a look this week?

**Comment by zfoster** [comment]
I'll take a look this week

**Comment by zfoster** [comment]
@peterskurt I'm still trying to learn why python has this flag hardcoded: https://github.com/Azure/azure-sdk-for-python/pull/15715

**Comment by zfoster** [comment]
@peterskurt I'll do a release this week, but we've merged a fix for this: https://github.com/Azure/azure-sdk-for-python/pull/15715

**Comment by peterskurt** [comment]
Great.  Are you also going to update the docker image on dockerhub?
Kurt

**Comment by zfoster** [comment]
Which docker image?

**Comment by peterskurt** [comment]
Sorry.  I thought that there was a docker image with Azure library commands inside.
Kurt

**Comment by zfoster** [comment]
ah no problem!

**Comment by antonatem** [comment]
@zfoster Was this added to a release? The latest version(4.2.0) in PyPi still has this hardcoded
