### ISSUE TITLE
 azure-storage-file-datalake: The value for one of the HTTP headers is not in the correct format.

### ISSUE THREAD

**Issue by aminekaabachi** [Azure/azure-sdk-for-python#15588]
- **Package Name**:  azure-storage-file-datalake
- **Package Version**: 12.1.2
- **Operating System**: Linux
- **Python Version**: 3.8

**The value for one of the HTTP headers is not in the correct format**

I am using the **azure-storage-file-datalake** inside an azure function. 
Here is the source code I am using:

```python
file_client = fs_client.create_file(file=file_path)
content = local_file.read()
position = len(content.encode('utf-8'))
file_client.append_data(content, 0, position)
file_client.flush_data(position)        
```

The local_file is a SpooledTemporaryFile. Most of the time this works fine but sometime it gets me the following error:
```
Executed 'Functions.***' (Failed, Id=***, Duration=61660ms)
[2020-12-01T09:27:50.821] System.Private.CoreLib: Exception while executing function: Functions.***, System.Private.CoreLib: Result: Failure
Exception: Exception: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:<REDACTED>
Time:2020-12-01T09:27:51.3368613Z
```

**Expected behavior**
I cannot see why it is giving this behaviour. I first thought it is related to encoding but then `.encode('utf-8')` should have solved the issue.

**Comment by tasherif-msft** [comment]
Hi @aminekaabachi,
Do you happen to have the full error trace? usually when an exception like this is raised it would specify the header that was not of the correct format. Let me know if you can retrieve this info.
Thank you!

Tamer

**Comment by aminekaabachi** [comment]
Hello @tasherif-msft ,

Thank you for your response. He is the full error trace I have:

```
Orchestrator function 'ingestion_orchestrator' failed: Activity function 'stream_ingest' failed: Exception: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:d9a1b65e-e01f-0056-64dc-c85900000000\nTime:2020-12-02T18:57:00.9033679Z  
{\"$type\":\"System.Exception, System.Private.CoreLib\",\"ClassName\":\"System.Exception\",\"Message\":\" Exception: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.\\nRequestId:d9a1b65e-e01f-0056-64dc-c85900000000\\nTime:2020-12-02T18:57:00.9033679Z\",\"Data\":null,\"InnerException\":{\"$type\":\"Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException, Microsoft.Azure.WebJobs.Script\",\"StackTrace\":\" at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 93\\n at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82\\n at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225\\n at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\\\projects\\\\azure-webjobs-sdk-rqm4t\\\\src\\\\Microsoft.Azure.WebJobs.Host\\\\Executors\\\\FunctionInvoker.cs:line 52\\n at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\\\projects\\\\azure-webjobs-sdk-rqm4t\\\\src\\\\Microsoft.Azure.WebJobs.Host\\\\Executors\\\\FunctionExecutor.cs:line 559\\n at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\\\projects\\\\azure-webjobs-sdk-rqm4t\\\\src\\\\Microsoft.Azure.WebJobs.Host\\\\Executors\\\\FunctionExecutor.cs:line 507\\n at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\\\projects\\\\azure-webjobs-sdk-rqm4t\\\\src\\\\Microsoft.Azure.WebJobs.Host\\\\Executors\\\\FunctionExecutor.cs:line 285\",\"Message\":\"Result: Failure\\nException: Exception: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.\\nRequestId:d9a1b65e-e01f-0056-64dc-c85900000000\\nTime:2020-12-02T18:57:00.9033679Z\\nStack: File \\\"/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py\\\", line 355, in _handle__invocation_request\\n call_result = await self._loop.run_in_executor(\\n File \\\"/usr/local/lib/python3.8/concurrent/futures/thread.py\\\", line 57, in run\\n result = self.fn(*self.args, **self.kwargs)\\n File \\\"/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py\\\", line 542, in __run_sync_func\\n return func(**params)\\n File \\\"/home/site/wwwroot/stream_ingest/__init__.py\\\", line 234, in main\\n res = download_results(stream, config.data_prefix)\\n File \\\"/home/site/wwwroot/stream_ingest/__init__.py\\\", line 129, in download_results\\n datalake.persist(persist_params, temp)\\n File \\\"/home/site/wwwroot/helpers/datalake.py\\\", line 48, in persist\\n raise Exception(msg)\\n\",\"Data\":{\"$type\":\"System.Collections.ListDictionaryInternal, System.Private.CoreLib\"},\"InnerException\":null,\"HelpLink\":null,\"Source\":\"System.Private.CoreLib\",\"HResult\":-2146233088},\"HelpURL\":null,\"StackTraceString\":null,\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146233088,\"Source\":null,\"WatsonBuckets\":null}","createdTime":"2020-12-02T18:55:13Z","lastUpdatedTime":"2020-12-02T18:57:01Z
```

**Comment by tasherif-msft** [comment]
Hey @aminekaabachi,
I'm very sorry for the long delay on this, we will look in more detail into the logs of your request.
Do you happen to have a recent failure with a recent `RequestId`? (similar to example you provided above)

**Comment by bpodraza** [comment]
@tasherif-msft 

I am having a similar issue.  I have developed a file management system for my web app using an Azure Gen2 DataLake, which is storing unstructured data in a hierarchy.  

My ASP NET core web app has Azure.Storage.Files.DataLake (12.5.0) as a dependency.

The module is nearly complete, but I have an upload function that fails periodically with this error.

**Azure.RequestFailedException: The value for one of the HTTP headers is not in the correct format.**

`public async Task UploadFile(string directoryPath, string fileName, Stream fileStream)
        {
            DataLakeDirectoryClient directoryClient = fileSystem.GetDirectoryClient(directoryPath.TrimStart('/'));

            DataLakeFileClient fileClient = directoryClient.GetFileClient(fileName);

            await fileClient.UploadAsync(fileStream);

        }`

Here is the top of the error, which has some IDs you may be able to use.

Azure.RequestFailedException: The value for one of the HTTP headers is not in the correct format.↵RequestId:d00b0cfa-101f-0045-6696-e7b91c000000↵Time:2021-01-10T21:21:47.9379718Z
↵Status: 400 (The value for one of the HTTP headers is not in the correct format.)
↵ErrorCode: InvalidHeaderValue
↵
↵Additional Information:
↵HeaderName: Content-Length
↵HeaderValue: 0
↵
↵Headers:
↵Server: Windows-Azure-HDFS/1.0,Microsoft-HTTPAPI/2.0
↵x-ms-error-code: InvalidHeaderValue
↵x-ms-request-id: d00b0cfa-101f-0045-6696-e7b91c000000
↵x-ms-version: 2020-02-10
↵x-ms-client-request-id: c2fefa04-7828-4fe4-803e-594dc38e6df0
↵Date: Sun, 10 Jan 2021 21:21:47 GMT
↵Content-Length: 262
↵Content-Type: application/json; charset=utf-8

**Comment by kaaveland** [comment]
I'm getting these now. The offending header appears to be `Content-Length`:

```python
{'error': {'code': 'InvalidHeaderValue',
  'message': 'The value for one of the HTTP headers is not in the correct format.\nRequestId:b3dbfe0d-301f-00bd-6e8f-04d6e0000000\nTime:2021-02-16T18:10:49.7987033Z',
  'detail': {'HeaderName': 'Content-Length', 'HeaderValue': '0'}}}
```

If I can trust the exception object this threw, the offending request was a `PATCH` with these query params: `{'action': 'append', 'position': '64505401'}`. This request does indeed have `Content-Length: 0`. Was I appending an empty bytearray? 🤔

**Comment by tasherif-msft** [comment]
Hi @aminekaabachi are you still experiencing this issue? if so, does your SpooledTemporaryFile vary in size? also a request ID would be very useful.
If the data size is 0 yet the length is set to a value this may cause problems (inconsistency between `content_length` and the actual expected length of the data being passed)

**Comment by aminekaabachi** [comment]
Hi @tasherif-msft, I switched to using `file_client.upload_data` and I didn't get the same issue again.
