### ISSUE TITLE
Changed the credential = DefaultAzureCredential() as credential = VisualStudioCodeCredential() and then suffered the issue.

### ISSUE THREAD

**Issue by worlin** [Azure/azure-sdk-for-python#15597]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Changed the code as credential = VisualStudioCodeCredential() and then suffered the issue.
![image](https://user-images.githubusercontent.com/73322628/100816307-c6c21b00-3480-11eb-841a-b5d9f1e0796c.png)
![image](https://user-images.githubusercontent.com/73322628/100816326-cf1a5600-3480-11eb-8eeb-c1853483be8f.png)

I was wondering if I need to create the service principal manually in AAD tenant to resolve the issue.

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mccoyp** [comment]
Hello, thank you for opening an issue! I'm taking a look at this now and will update as soon as I have more information about what may be going on.

**Comment by mccoyp** [comment]
The first thing I would suspect is that the `DefaultAzureCredential` is using different credentials than `VisualStudioCodeCredential`. This could happen if you have environment variables set for an Azure principal's client ID, client secret, and tenant ID, but you're logged in as a different principal through the VS Code "Azure Account" extension. I would recommend checking your environment variables for `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, and `AZURE_TENANT_ID` to see if this is the case.

In any case, my next suggestion would be to make sure that the account you used to log in on VS Code has necessary permissions in your key vault. [Here's a walkthrough](https://docs.microsoft.com/azure/key-vault/general/assign-access-policy-portal) for how to set an access policy on the Azure Portal. If you're only getting a secret, you should only need to give permission for the "Get" secret management operation.

If this doesn't clear up the issue, please let us know in a comment to this issue! I'll continue to help until this is resolved. And to make debugging this easier, it would be great if you could include the environment information that was left out in the bug report template (package versions, Python version, etc.). Thanks again for reporting this!
