### ISSUE TITLE
azure.storage.QueueMessage considered harmful

### ISSUE THREAD

**Issue by saschagottfried** [Azure/azure-sdk-for-python#156]
This week I wrote code addressing Azure Storage Blobs, Tables and Queues. Great stuff. Since I ran into errors while removing message that were dequeued more often than my limit, I looked into the details of azure.storage.QueueMessage. The implementation was surprising me...

azure.storage.QueueMessage is just a bunch of strings. I was really surprised that this class (obviously nothing more than a Data Transfer Object) ships with an SDK that is marked as 'production/stable/ on PyPI. 

class QueueMessage(WindowsAzureData):

    ''' Queue message class. '''

    def __init__(self):
        self.message_id = u''
        self.insertion_time = u''
        self.expiration_time = u''
        self.pop_receipt = u''
        self.time_next_visible = u''
        self.dequeue_count = u''
        self.message_text = u''

I would expect members having names containing 'time' to have type DateTime and members having names indicating an integer (dequeue_count) to be an Integer. Instances of this class are just prone to error. That's what happened to me.

Focused Python developers may expect a standard-level pythonic API coming from Microsoft that of course will hide transport implementations details as well that are discussed in this issue [https://github.com/Azure/azure-sdk-for-python/issues/150]. 

Can anybody comment this or explain why it is like that or even has to be like that? Any suggestions how to contribute on that important topic without breaking APIs are welcome.

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/16
