### ISSUE TITLE
Read Timeout occurring frequently when fetching documents from Cosmos using `CosmosClient`

### ISSUE THREAD

**Issue by absognety** [Azure/azure-sdk-for-python#15609]
Hi,

I have azure functions where I am using azure cosmos python SDK to fetch documents using SQL API, Please find the following piece of code that we I am using:

```
client = CosmosClient(host, credential=masterKey,
                              retry_total=15,
                              retry_backoff_max=30,retry_connect=4,retry_status=4,retry_read=4)
database = client.get_database_client(databasename)
container = database.get_container_client(collection)
items = container.query_items(query=query,enable_cross_partition_query=True)
```
This is the error I am facing:
```
HTTPSConnectionPool(host='XXXXX.documents.azure.com', port=443): Read timed out. (read timeout=60.0)
```
Please note that this issue used to occur randomly in our Data factory pipelines, but sometimes frequency is increasing.
What can we do here? Please suggest.

```
Version Information
Python 3.8
azure-appconfiguration==1.1.1
azure-batch==9.0.0
azure-cli==2.14.0
azure-cli-core==2.14.0
azure-cli-telemetry==1.0.6
azure-common==1.1.25
azure-core==1.8.2
azure-cosmos==4.2.0
azure-datalake-store==0.0.51
azure-functions==1.4.0
azure-functions-devops-build==0.0.22
azure-functions-durable==1.0.0b10
azure-graphrbac==0.60.0
azure-keyvault==1.1.0
azure-keyvault-administration==4.0.0b2
azure-loganalytics==0.1.0
azure-mgmt-advisor==2.0.1
azure-mgmt-apimanagement==0.2.0
azure-mgmt-appconfiguration==0.6.0
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.61.0
azure-mgmt-batch==9.0.0
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-botservice==0.2.0
azure-mgmt-cdn==5.0.0
azure-mgmt-cognitiveservices==6.3.0
azure-mgmt-compute==14.0.0
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==3.0.0rc15
azure-mgmt-containerservice==9.4.0
azure-mgmt-core==1.2.0
azure-mgmt-cosmosdb==1.0.0
azure-mgmt-datalake-analytics==0.2.1
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==0.1.0
azure-mgmt-deploymentmanager==0.2.0
azure-mgmt-devtestlabs==4.0.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==3.0.0rc7
azure-mgmt-eventhub==4.1.0
azure-mgmt-hdinsight==1.7.0
azure-mgmt-imagebuilder==0.4.0
azure-mgmt-iotcentral==3.0.0
azure-mgmt-iothub==0.12.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==7.0.0b3
azure-mgmt-kusto==0.3.0
azure-mgmt-loganalytics==0.7.0
azure-mgmt-managedservices==1.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.2.1
azure-mgmt-media==2.2.0
azure-mgmt-monitor==0.11.0
azure-mgmt-msi==0.2.0
azure-mgmt-netapp==0.12.0
azure-mgmt-network==12.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.5.0
azure-mgmt-privatedns==0.1.0
azure-mgmt-rdbms==3.1.0rc1
azure-mgmt-recoveryservices==0.4.0
azure-mgmt-recoveryservicesbackup==0.6.0
azure-mgmt-redhatopenshift==0.1.0
azure-mgmt-redis==7.0.0rc2
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.6.0
azure-mgmt-resource==10.2.0
azure-mgmt-search==2.1.0
azure-mgmt-security==0.4.1
azure-mgmt-servicebus==0.6.0
azure-mgmt-servicefabric==0.5.0
azure-mgmt-signalr==0.4.0
azure-mgmt-sql==0.21.0
azure-mgmt-sqlvirtualmachine==0.5.0
azure-mgmt-storage==11.2.0
azure-mgmt-synapse==0.3.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==0.48.0
azure-multiapi-storage==0.5.2
azure-nspkg==3.0.2
azure-search-documents==11.0.0
azure-servicebus==0.50.3
azure-storage-blob==12.5.0
azure-storage-common==2.1.0
azure-storage-file-datalake==12.1.1
azure-synapse-accesscontrol==0.2.0
azure-synapse-artifacts==0.3.0
azure-synapse-spark==0.2.0
```

**Comment by zfoster** [comment]
@absognety I'll take a look, we've seen similar issues in the JS SDK that seemed transient and went away

**Comment by zfoster** [comment]
Do you have any data for how frequently these requests occur per thousand requests? Even an estimate is helpful

**Comment by absognety** [comment]
we are hitting one of our cosmos DB containers very repeatedly like in last 12 hours there are about 98.5k requests, followed by another container which has 43.5k requests

**Comment by TissonMathew** [comment]
Using singleton pattern in C# for the client connection fixed this.. what's the best way to address this in python? 

https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-dotnet-sdk-v3-sql 

Use a singleton Azure Cosmos DB client for the lifetime of your application

Each CosmosClient instance is thread-safe and performs efficient connection management and address caching when it operates in Direct mode. To allow efficient connection management and better SDK client performance, we recommend that you use a single instance per AppDomain for the lifetime of the application.

When you're working on Azure Functions, instances should also follow the existing guidelines and maintain a single instance.

**Comment by TissonMathew** [comment]
@zfoster https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections#static-clients

**Comment by TissonMathew** [comment]
Also, what does "Max degree of parallelism" do? does it have to anything concurrent open connections to a cosmos db/collection from a client?

**Comment by TissonMathew** [comment]
Update on this... the problem was cosmos account itself. We created a new cosmos account (same config except turned off analytics link, provisioned throughput) and the timeout issues went away.

**Comment by southpolesteve** [comment]
@TissonMathew @absognety Looks like you got this resolved, but FYI there was a service side SSL issue that we believe was causing this. A fix was rolled out yesterday. Please do let us know if you run into more issues.

**Comment by TissonMathew** [comment]
Yes. Thanks @southpolesteve

**Comment by absognety** [comment]
Thank you team.

**Comment by kjmccarthy** [comment]
Going off of what @TissonMathew mentioned, is there a best practice to for creating a static cosmosClient in a python azure function?
https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections#static-clients 
only provides examples for c# and javaScript

**Comment by bijoyboban7** [comment]
Hi Team, Similar to the issue mentioned above, i am also getting the timeout error from 16-06-2022 in cosmos db. Do you think its the same SSL error again?

(, 'Connection to <our account>.documents.azure.com timed out. (connect timeout=60.0)')

**Comment by LeonardoSanBenitez** [comment]
Hi, me too, I'm receiving the same error since a few days ago
I'm already using the singleton pattern, and creating a new cosmos account is not an option

Does anyone know how to solve the problem?
