### ISSUE TITLE
First chunk of StorageStreamDownloader.chunks() is always 32MB big

### ISSUE THREAD

**Issue by mth-cbc** [Azure/azure-sdk-for-python#15648]
- **Package**: azure-storage-blob
- **Package Version**: 12.6.0
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.8.0

**Describe the bug**
When using the `StorageStreamDownloader`s chunk interator to download/iterator offer a blob the first chunk is always 32\*1024\*1024 bytes big, regardless of the setting for `max_chunk_get_size`.

**To Reproduce**
1. instantiate a `BlobClient` for a file bigger than 32 MB
2. get a `StorageStreamDownloader` for the blob: `stream = blob_client.download_blob()`
3. iterate over the blob using the `chunks()` function and print the chunk size:
```
for chunk in stream.chunks():
    print(len(chunk))
```

**Expected behavior**
Each chunk, apart from the last one, should have the size given by the `max_chunk_get_size` parameter, so by default 4\*1024\*1024 bytes.

**Comment by xiafu-msft** [comment]
Hi @mth-cbc

Thanks so much for reporting this issue, it's an SDK bug. 
Currently you can use this workaround by setting max_chunk_get_size=`your expected chunk size`, then the first chunk size should be changed.

Let me know if you have any concern! Sorry about the inconvenience.

**Comment by mth-cbc** [comment]
Hi @xiafu-msft 

Thanks for your answer, but I observe the same behaviour when specifing an explicit chunk size via `max_chunk_get_size`.

**Comment by xiafu-msft** [comment]
Sorry I had a typo there! I mean max_single_get_size, updated the previous comment

**Comment by mth-cbc** [comment]
Thanks for the workaround, now it works as expected.

**Comment by tasherif-msft** [comment]
This pr https://github.com/Azure/azure-sdk-for-python/pull/17559 will resolve this issue in the future :) 
I will go ahead and close this issue!
