### ISSUE TITLE
blob storage logging integration problem

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#15666]
- **Package Name**: `azure-storage-blob`
- **Package Version**: 12.5.0
- **Operating System**: OSX
- **Python Version**: 3.8.6

**Describe the bug**
Integration with the `logging` framework not fully working. Setting log level as pre docs does not work.

**To Reproduce**
1. use example from docs https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.6.0/index.html#logging
2. set `WARNING` log level, i.e. use `logger.setLevel(logging.WARNING)`

**Expected behavior**
The log should be squashed., instead still get the same log.

**Additional context**
In general I would expect any storage client to accept a log level parameter and let the client set the logger for me. But I see your approach is quite common and it is fair. However, I think because the actual logging happens in a different module, one has to get a logger for that module or for the whole `azure` module, which seems to me quite too much.

**Comment by xiafu-msft** [comment]
Hi @andrea-cassioli-maersk 

Thanks for reaching out
do you mean you set 
```
logger = logging.getLogger('azure.storage.blob')
logger.setLevel(logging.DEBUG)
```
and 
```
logger = logging.getLogger('azure.storage.blob')
logger.setLevel(logging.WARNING)
```
and they give you the same log?

**Comment by andrea-cassioli-maersk** [comment]
@xiafu-msft yes correct. Only using
```
logger = logging.getLogger('azure')
```

seems to work

**Comment by andrea-cassioli-maersk** [comment]
Any thoughts?

**Comment by xiafu-msft** [comment]
sorry for the late response because of the vacation!
We will try to reproduce it and get back to you ASAP!

**Comment by xiafu-msft** [comment]
Hi @andrea-cassioli-maersk 

It seems you need to set logging.WARN, instead of WARNING, can you try this and see if it helps?

**Comment by andrea-cassioli-maersk** [comment]
Well, it seems I cannot reproduce anymore. Most likely I messed up some versions I guess!

So sorry for the fuss. Thanks for having looked into it.
