### ISSUE TITLE
[Cosmos DB] Robust usage of PreferredLocations / equivalent of ApplicationRegion

### ISSUE THREAD

**Issue by sebader** [Azure/azure-sdk-for-python#15679]
- **Package Name**: azure-cosmos
- **Package Version**:  4.2.0
- **Operating System**: Linux
- **Python Version**:  3.8

**Describe the bug**
This is probably as much as feature request as a bug report:

For different app environments (dev,test,prod) we are using different Cosmos DB accounts. Prod and test are geo-replicated (multiple read-regions, only one write region). Dev, however, is not replicated at all.

Now we would like our app to connect automatically to the closest available region. In the .NET SDK this seems to be available with the [ApplicationRegion ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.applicationregion?view=azure-dotnet#Microsoft_Azure_Cosmos_CosmosClientOptions_ApplicationRegion)parameter. I didn't find this in the python SDK?! So instead we tried to use PreferredLocations. However, that crashes if you specify a region in there, which is not in the replicated regions for this account (even if another region in that list does exist).

**To Reproduce**
```
        self.cosmos_client = CosmosClient(
            url=DB_URL,
            credential=credentials,
            preferred_locations=["UK West", "UK South"]
```
Whereas the Cosmos DB does exist in UK south but was not replicated to UK West.

````
Traceback (most recent call last):
[...]
  File "./app/database/database.py", line 60, in __init__
    self.cosmos_client = CosmosClient(
  File "/usr/local/lib/python3.8/site-packages/azure/cosmos/cosmos_client.py", line 167, in __init__
    self.client_connection = CosmosClientConnection(
  File "/usr/local/lib/python3.8/site-packages/azure/cosmos/_cosmos_client_connection.py", line 208, in __init__
    self._global_endpoint_manager.force_refresh(database_account)
  File "/usr/local/lib/python3.8/site-packages/azure/cosmos/_global_endpoint_manager.py", line 89, in force_refresh
    self.refresh_endpoint_list(database_account)
  File "/usr/local/lib/python3.8/site-packages/azure/cosmos/_global_endpoint_manager.py", line 99, in refresh_endpoint_list
    raise e
  File "/usr/local/lib/python3.8/site-packages/azure/cosmos/_global_endpoint_manager.py", line 97, in refresh_endpoint_list
    self._refresh_endpoint_list_private(database_account, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cosmos/_global_endpoint_manager.py", line 107, in _refresh_endpoint_list_private
    self.location_cache.should_refresh_endpoints()
  File "/usr/local/lib/python3.8/site-packages/azure/cosmos/_location_cache.py", line 164, in should_refresh_endpoints
    most_preferred_read_endpoint = self.available_read_endpoint_by_locations[most_preferred_location]
KeyError: 'UK West'
````

**Expected behavior**
The next region in the list should be automatically tried without the entire connection failing.

**Comment by zfoster** [comment]
@sebader you're right this is more of a feature request as the python SDK does not have parity here with the v3 .NET sdk as seen here: https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-global-distribution-sql-api?tabs=dotnetv3%2Capi-async#net-sdk

I can label it as such however there aren't immediately plans to take on this work on our side. See: https://github.com/Azure/azure-sdk-for-python/issues/15685

**Comment by sebader** [comment]
thanks for the reply @zfoster, I totally understand the piece about making the ApplicationRegion a new feature.
But what about at least making the location discovery more robust so it won't crash when you specify an invalid region?

**Comment by zfoster** [comment]
Sorry - to make sure I understand, the ask is if you specify a region in preferred locations which is not valid, it should attempt to try the next region until all regions in the list are exhausted? Offhand, that seems like an antipattern for preferred locations.

Is the use case to support your three environments with a single client options object?

**Comment by zfoster** [comment]
Happy to help understand what you're looking for :)

**Comment by sebader** [comment]
> Is the use case to support your three environments with a single client options object?

basically, yes :) But now we worked around this, but it would have felt more natural if the SDK will automatically retry if one of the regions is invalid. Ideally, even if none of the preferred_locations, is valid, it should just fall back to the main/default region.
After all, it's called "preferred" not "ever-only-one-of-these" locations :)

**Comment by zfoster** [comment]
yeah, I would think of preferred locations as a way to create a subset of available regions that you wish to make requests to. And there are advantages and use cases dependent on it working this way,. However, there is certainly appetite for this feature, given `ApplicationRegion` was developed.

I would recommend using some combination of environment variables and making the options dictionary dynamic based on them, and track this issue https://github.com/Azure/azure-sdk-for-python/issues/15685. Thanks for the feedback!

**Comment by sebader** [comment]
ok, fair enough. thanks!
