### ISSUE TITLE
[Cosmos] Support Application Region

### ISSUE THREAD

**Issue by zfoster** [Azure/azure-sdk-for-python#15685]
**Is your feature request related to a problem? Please describe.**
Users who specify regions in preferred locations are unable to make requests outside those regions.

**Describe the solution you'd like**
Support `ApplicationRegion` or similar behavior to the v3 .NET SDK https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-global-distribution-sql-api?tabs=dotnetv3%2Capi-async#net-sdk

Request: https://github.com/Azure/azure-sdk-for-python/issues/15679

**Comment by arwinlashawn** [comment]
Hi @sebader, do we happen to have an ETA on when this feature will be released?
