### ISSUE TITLE
virtual_machine_scale_set_vm_extensions.list appears to be broken

### ISSUE THREAD

**Issue by milindvb** [Azure/azure-sdk-for-python#15693]
- **Package Name**: azure-mgmt-compute
- **Package Version**: 14 and above
- **Operating System**: Windows
- **Python Version**: 3.8

**Describe the bug**
virtual_machine_scale_set_vm_extensions.list appears to be broken. Please see error below:

**To Reproduce**

Traceback (most recent call last):
  File "mytest.py", line 23, in <module>
    vm_extensions_list = client. \
  File "C:\mbst\CaseFiles\lib\site-packages\azure\mgmt\compute\v2020_06_01\operations\_virtual_machine_scale_set_vm_extensions_operations.py", line 482, in list
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: BadRequest
Message: Subscription is not registered.

Please check the python file and the requirements.txt that I am using to recreate this issue below:
I would appreciate if someone can check the code and the requirements for any discrepancies in versions.
I have also tried with latest version of azure.mgmt.compute with similar results.

Mytest.py:

import os
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.compute import ComputeManagementClient
from azure.mgmt.compute.models import VirtualMachineScaleSetExtension

subscription_id = '7a3eb7f7'
credentials = ServicePrincipalCredentials(
    client_id='e72bd5e8',
    secret='rOMzOIO31PWoY',
    tenant='72f988bf'
)
group_name = 'mbtestvmss'

client = ComputeManagementClient(credentials, subscription_id)

for vmss in client.virtual_machine_scale_sets.list(group_name):
    instance_ids = []
    for extension_name in ['mbtestvmss']:
        for vm in client. \
            virtual_machine_scale_set_vms.list(group_name, vmss.name):
                print(f'vmss.name = {vmss.name}')
                print(f'vm.instance_id = {vm.instance_id}')
                vm_extensions_list = client. \
                    virtual_machine_scale_set_vm_extensions.list(group_name, vmss.name, vm.instance_id)
                print(f'vm_extensions_list = {vm_extensions_list}')

requirements.txt:

azure-mgmt-resource~=10.0
azure-mgmt-network~=16.0
azure-mgmt-compute~=14.0

**Expected behavior**
Print list of extensions

**Comment by jsntcy** [comment]
As Jun mentioned in the email thread, customer can use `properties.latestModelApplied` instead of virtual_machine_scale_set_vm_extensions.list to achieve his goal.

https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/list

If it’s false, customer can use updateinstance API to apply the latest model, which includes new extensions.
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/updateinstances

**Comment by jsntcy** [comment]
Close this as a solution is provided.
