### ISSUE TITLE
ServiceBus causing a silent error during .close() calls on ServiceBus objects

### ISSUE THREAD

**Issue by cyates-abledocs** [Azure/azure-sdk-for-python#15711]
- **Package Name**: azure-servicebus
- **Package Version**: 7.0.0
- **Operating System**: Linux
- **Python Version**: 3.8

**Describe the bug**
Attempting to call `.close()` on Service Bus objects like `ServiceBusClient` and `ServiceBusSender` is silently crashing our web app. Despite the silent crashes, messages are moving in and out of queues no problem. If we use a context manager via `with`, the issue still occurs in the same way -- a silent crash despite the message sending successfully.

**To Reproduce**
```
from azure.servicebus import ServiceBusClient, ServiceBusMessage, ServiceBusSender


sbc = ServiceBusClient.from_connection_string() # supply your own ServiceBus connection string
sender = sbc.get_queue_sender() # supply the name of your own queue to test with
sender.send_messages() # post a ServiceBusMessage to your queue
print('Message posted')
sender.close()
sbc.close()
print('Exiting')
```

**Expected behavior**
Given the code above, I expect to see 'Exiting' printed after closing ServiceBus objects. Instead the last message printed is 'Message posted'.

**Screenshots**
The result of the silent crash:
![Screen Shot 2020-12-08 at 9 44 56 AM](https://user-images.githubusercontent.com/68296568/101539833-bf10e380-3964-11eb-9221-43dd4a0a1517.png)

**Additional context**
N/A

**Comment by yunhaoling** [comment]
hey @cyates-abledocs, thanks for reaching out.

Is there any error log printed out when the client/sender crashed?
also wondering what's your linux distribution as our livetest covers ubuntu?

**Comment by cyates-abledocs** [comment]
@yunhaoling Thanks for the speedy response!

> I didn't see you pass message into the `send_messages`, is it just a typo?

In practice, I did pass a message to `send_messages`. I just left it empty in the example to keep things clear. I'm happy to clarify anything if necessary.

> Is there any error log printed out when the client/sender crashed.

There is no useful error log when the crash happens. As soon as the `.close()` call happens, the app crashes and restarts.


> also wondering what's your linux distribution as our livetest covers ubuntu and we didn't seen such an issue before

We're running our app as a Linux App Service which uses Ubuntu.

**Comment by yunhaoling** [comment]
hey @cyates-abledocs , sorry for keeping you waiting, just back from vacation.

I'm wondering if you could turn on the logging for amqp networking activity and share me with the log info.

It could be turned on via
```
sbc = ServiceBusClient.from_connection_string(..., logging_enable=True)
```
and then turn on your logging, either output into the console or a file.

The log info would help me to see in which process the program exited abnormally and locate the root cause for the issue
