### ISSUE TITLE
Cannot Regenerate Storage Account Access Key

### ISSUE THREAD

**Issue by ryman23** [Azure/azure-sdk-for-python#15732]
- **Package Name**: azure-mgmt-storage
- **Package Version**: 16.0.0
- **Operating System**:
- **Python Version**: 3.8

**Describe the bug**
I'm trying to regenerate a storage account access key in an Azure Function, but I am prompted with the following error: `<Result: Failure Exception: SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'>`.

I've been following the examples here: https://docs.microsoft.com/en-us/samples/azure-samples/storage-python-manage/storage-python-manage/

**To Reproduce**
`<newStorageAccountAccessKey = storageAccountClient.storage_accounts.regenerate_key(storageAccountResourceGroupName, storageAccountName, "key2")>`

**Expected behavior**
Successful rotation of the desired storage account access key

**Comment by ryman23** [comment]
I've gotten it to work since by changing the code to the following: `<newStorageAccountAccessKey = storageAccountClient.storage_accounts.regenerate_key(resource_group_name=storageAccountResourceGroupName, account_name=storageAccountName, regenerate_key={'key_name': 'key1'})>`. Documentation should be updated to reflect this.

**Comment by jsntcy** [comment]
We'll update the code samples in https://docs.microsoft.com/en-us/samples/azure-samples/storage-python-manage/storage-python-manage/
