### ISSUE TITLE
Storage SDK doesn't seem to implement Copy Blob

### ISSUE THREAD

**Issue by neaorin** [Azure/azure-sdk-for-python#15730]
The Blob Service REST API offers a [Copy Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) operation which is useful for copying blobs from one storage account to another or within the same storage account. 

Currently the [BlobClient](https://github.com/Azure/azure-sdk-for-python/blame/master/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py) doesn't implement this operation. It only implements the [Copy Blob From URL](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) operation which has a limit of 256MiB for the blobs it can copy.

We'd like to have an option to copy large blobs between storage accounts in the SDK.

**Comment by tasherif-msft** [comment]
Hi @neaorin, while investigating this it seems we actually implemented the `CopyBlob` rest call and not the `CopyBlobFromUrl` rest call. The naming is misleading though. 
Have you attempted to copy file size > 256MB and it failed?
