### ISSUE TITLE
Unsuppressible mypy syntax error for azure.core when using it from a typechecked project with python 3.9.0

### ISSUE THREAD

**Issue by christophebiocca** [Azure/azure-sdk-for-python#15762]
- **Package Name**: azure.core
- **Package Version**: 1.9.0
- **Operating System**: Arch Linux
- **Python Version**: 3.9.0

**Describe the bug**
Importing from `azure.core.*` will cause a hard-to-suppress mypy typechecking error about internal type annotations of azure core that have syntax errors.

I don't understand why it only happens on 3.9.0.

Note that mypy has a really hard time with syntax errors: https://github.com/python/mypy/issues/6897 which makes it hard for the end user to ignore them.

**To Reproduce**
1. Clone https://github.com/EncircleInc/azure-core-mypy-error
2.  `pip install -r requirements.lock.txt` file.
3. `mypy -p test`. You'll get something like `.../python3.9/site-packages/azure/core/pipeline/policies/_authentication.py:33: error: syntax error in type comment '(TokenCredential, *str, Mapping[str, Any]) -> None`
4. Try to suppress the error by adding `ignore_errors = True` in the `mypy.ini` file.
5. `mypy -p test` still errors out.

**Expected behavior**
No type errors when using default mypy settings, or an error saying there aren't any types available.

**Comment by christophebiocca** [comment]
Note to anyone else experiencing the issue: a workaround is to add the following to your `mypy.ini`:

```
[mypy-azure.core.pipeline.policies._authentication]
follow_imports = skip
```

A bit of a nuclear option, but nothing short of it will work.

**Comment by lmazuel** [comment]
That's an interesting bug! PR to fix it https://github.com/Azure/azure-sdk-for-python/pull/15768
