### ISSUE TITLE
OpenTelemetry Exporter integration with Resource API 

### ISSUE THREAD

**Issue by hectorhdzg** [Azure/azure-sdk-for-python#15771]
Resource API need to be integrated with exporter code to allow customers to configure cloud extension data like roleName, roleInstance among others
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable

**Comment by lzchen** [comment]
On a related note, the attributes within a Resource should also be exported for each envelope in the Azure exporters.
