### ISSUE TITLE
[Servicebus] Docs Bug bash

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#15774]
Following issues in python docs:

[One note](https://microsoft-my.sharepoint.com/personal/sabhyrav_microsoft_com/_layouts/OneNote.aspx?id=%2Fpersonal%2Fsabhyrav_microsoft_com%2FDocuments%2FSairam%20Rakshith%20%40%20Microsoft&wd=target%28Service%20bus%20ref%20docs%20bash.one%7C1439EC15-8F21-43D8-BADA-85EBCBD99E2E%2F%29)

**Comment by ramya-rao-a** [comment]
@rakshith91 Please add your findings in #15127
