### ISSUE TITLE
[DigitalTwins] azure-mgmt-digitaltwins is missing a dev_requirements.txt file

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-python#15789]
The `azure-mgmt-digitaltwins` library is missing the `dev_requirements.txt` file. Adding this file will fix the [nightly CI failures ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=653366&view=logs&j=028bc450-fadb-5779-46d3-75b0a155d611&t=1f4dfb08-a974-590e-dfdf-fd85c097dc1c&l=3739)

**Comment by jsntcy** [comment]
@seankane-msft 
- Do all SDK packages need `dev_requirements.txt`?
- Why do we need `dev_requirements.txt`?
- We removed `dev_requirements.txt` for https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/kubernetesconfiguration/azure-mgmt-kubernetesconfiguration doesn't have `dev_requirements.txt` because release pipeline failed due to this file.

**Comment by seankane-msft** [comment]
@jsntcy the `dev_requirements.txt` file is required to have the nightly pipeline passing. This issue is more concerned about solving the nightly CI issues.

**Comment by changlong-liu** [comment]
Hi @seankane-msft , may I know do we still need this dev_requirements.txt in pipeline? I see a later pipeline seems OK for current status: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=755229&view=results.

And we don't have test script for this azure-mgmt-digitaltwins package, so we should not need a dev_requirements.txt?

**Comment by seankane-msft** [comment]
I am not on the Python team anymore, tagging @scbedd for more current information

**Comment by scbedd** [comment]
@seankane-msft  thanks sir, I'll pick up this thread.

@changlong-liu you only require a `dev_requirements.txt` if there are dependencies used by your test framework that are not defined as package dependencies. For most, this would mean `azure-sdk-tools` or `azure-devtools`. For this specific case, it looks like `azure-mgmt-digitaltwins` doesn't _have_ tests (at least that's the case now), so you don't need a `dev_requirements.txt`.

IIRC mgmt-digitaltwins got updated recently right? probably why the errors disappeared. I feel like we can close this item.

**Comment by xiangyan99** [comment]
Close since azure-mgmt-digitaltwins does not have tests.
