### ISSUE TITLE
[Security] security nightly pipeline run is failing

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-python#15788]
The [nightly runs](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1028&_a=summary) for `python - security` are failing.

**Comment by seankane-msft** [comment]
This might be solved by adding a dev_requirements.txt file

**Comment by xiangyan99** [comment]
Close since azure-mgmt-security does not have tests.
