### ISSUE TITLE
Metadata key, for blobs, cannot contain space

### ISSUE THREAD

**Issue by sindre-nistad** [Azure/azure-sdk-for-python#15784]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.6.0
- **Operating System**: macOS / Alpine
- **Python Version**: 3.9.0

**Describe the bug**
Metadata with spaces in the key, causes an error when uploading a new blob.

```python
client = BlobServiceClient(account_url=account_url, credential=_credential).get_container_client(container_name)
client.upload_blob(
    name="Some unique name",
    data=file.stream.read(),  # A zip file
    metadata={
        "Some key with space": "Some token to be processed later",
    }
)
```
fails with error `msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html`

More specifically, the response is

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Header</h2>
<hr><p>HTTP Error 400. The request has an invalid header name.</p>
</BODY></HTML>
```

When `metatada` is removed, the code works as expected, or when the space(s) in the key is removed.

**To Reproduce**
1. See code above

**Expected behavior**

I expect the blob to be uploaded, with all metadata, even though the key contains spaces.

**Screenshots**

**Additional context**

**Comment by tasherif-msft** [comment]
Hi @sindre-nistad, 
I will look into this issue and get back to you once I have an update :)
Thank you very much.

**Comment by tasherif-msft** [comment]
Hi @sindre-nistad, I just wanted to confirm this before giving you an answer and it does appear that the server side does not accept space for the metadata key. This is expected behavior. 
I will close this issue for now. Let me know if you need any more help!
