### ISSUE TITLE
Reference docs for azure-keyvault v1 gets re-directed to use the preview moniker instead of legacy

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#15797]
This is the API reference docs link for the `azure-keyvault` package: https://docs.microsoft.com/en-us/python/api/overview/azure/keyvault. Unfortunately this link gets re-directed in a way such that it gets the query parameter `view=azure-python-preview` which makes the page use the "preview" moniker. It should be using `view=azure-python-previous` instead so that the "legacy" moniker is used and the right content gets rendered for `azure-keyvault`. 

Found during #15110

Nice catch @mccoyp!

**Comment by mccoyp** [comment]
This seems to have been resolved -- following the link in the description or the version 1.x.x "Reference" link in the [KV overview page](https://docs.microsoft.com/en-us/python/api/overview/azure/key-vault-index?view=azure-python) leads to the correct, legacy page. Closing as a result, thank you!
