### ISSUE TITLE
Broken link in azure-keyvault v1 readme

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#15796]
The [readme for azure-keyvault v1](https://github.com/Azure/azure-sdk-for-python/tree/azure-keyvault_1.1.0/azure-keyvault) is linked from the [Key Vault Overview page for Python packages](https://docs.microsoft.com/en-us/python/api/overview/azure/key-vault-index?view=azure-python).

This readme has a broken link https://docs.microsoft.com/python/api/overview/azure/key-vault
The problem is in the hypen between the words "key" and "vault", the right url is https://docs.microsoft.com/python/api/overview/azure/keyvault

Our options are
- Create a redirect link such that the wrong one leads to the right one
- Or, create a branch from the tag `azure-keyvault_1.1.0`, fix the link, delete the tag, add the tag to this branch.

Found in #15110
Nice catch @mccoyp!

**Comment by mccoyp** [comment]
As mentioned in the pull request meant to resolve this, it turns out that the `azure-keyvault_1.1.0` tag containing the README is immutable. Unless we do a release of a version 1.1.1, our remaining option for fixing the link is to create a redirect link.

**Comment by mccoyp** [comment]
Resolved via MicrosoftDocs/azure-docs-sdk-python#1124.
