### ISSUE TITLE
[Event Hubs] Add missing descriptions for user facing methods in BlobCheckpointStore class

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#15802]
[The methods on the BlobCheckpointStore ](https://docs.microsoft.com/en-us/python/api/azure-eventhub-checkpointstoreblob/azure.eventhub.extensions.checkpointstoreblob.blobcheckpointstore?view=azure-python#methods)in both sync and async versions of the package need descriptions:

![image](https://user-images.githubusercontent.com/16890566/102167862-1a027900-3e44-11eb-8b34-3e40f78fed46.png)

Found as part of #15109

Nice catch @yunhaoling

**Comment by yunhaoling** [comment]
PR merged, this should be fixed after we release the eventhub and the corresponding doc.
