### ISSUE TITLE
[Event Hubs] TOC nodes in reference docs pointing to wrong locations

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#15800]
The [overview page for azure-eventhub-checkpointstoreblob](https://docs.microsoft.com/en-us/python/api/azure-eventhub-checkpointstoreblob-aio/azure.eventhub.extensions?view=azure-python) has a link to the async package. And there are are few links under the async node that points to sync APIs

![image](https://user-images.githubusercontent.com/16890566/102166730-a7909980-3e41-11eb-99c2-088b74b5928d.png)

Found as part of #15109
Nice catch @yunhaoling !

**Comment by kurtzeborn** [comment]
This is an issue that library owners should be able to address by following the documentation we've created for these types of issues [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/283/Docs.MS-Primer?anchor=how-do-i-actually-update-the-toc%3F).  Please reach out to @danieljurek or @scbedd if you need assistance.

**Comment by scbedd** [comment]
After another long look at this issue, I believe that something wonky is happening within the python build. We'll take this.

**Comment by danieljurek** [comment]
@scbedd Fixed this as part of ToC changes. Fixes are live.

**Comment by ramya-rao-a** [comment]
Verified as fixed, thanks @scbedd and @danieljurek!
