### ISSUE TITLE
Reference docs for packages that are no longer in preview should not be listed under the preview moniker

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#15818]
This is the [landing page for Python API reference docs for packages that are in preview](https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python-preview). Many of the these packages have moved out of preview and into GA. These should not appear here anymore. Found as part of #15127

![image](https://user-images.githubusercontent.com/16890566/102291191-6eb2fc00-3ef7-11eb-8e44-b291970d3596.png)

**Comment by scbedd** [comment]
Please submit a PR that updates [this file](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/ci-configs/packages-preview.json) to remove the packages that are no longer GA.

I have filed an [issue](https://github.com/Azure/azure-sdk/issues/2268) to cover this as part of the doc automation.

**Comment by ramya-rao-a** [comment]
Thanks @scbedd

The link you have shared is for the JS docs, can you update your comment above with the link to the Python one?

@danieljurek,
I believe @kurtzeborn meant for this issue to be fixed by the Python team while the Central EngSys team focus on fixing the automation i.e  https://github.com/Azure/azure-sdk/issues/2268. So, perhaps the `Central EngSys` label should be removed?

@lmazuel,
Please assign this issue to the release driver in the Python team

**Comment by danieljurek** [comment]
I'm working on the automation for this right now. I updated [that issue](https://github.com/Azure/azure-sdk/issues/2268) to reflect that. 

For this issue, I removed the Central-EngSys label from this bug, unassigned myself, and moved it back into the backlog.

**Comment by lmazuel** [comment]
@danieljurek still doesn't seem to be fixed?

**Comment by ramya-rao-a** [comment]
We might want to fix this manually just this one time rather than wait for the automation?
This would be the file to update right? https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/ci-configs/packages-preview.json

**Comment by danieljurek** [comment]
This is fixed as part of work on https://github.com/azure/azure-sdk-for-python/issues/17651 ... The only packages in Preview now are those that have previews and are not superseded by a GA package.
