### ISSUE TITLE
How to download publicly available objects from blob storage?

### ISSUE THREAD

**Issue by apengwin** [Azure/azure-sdk-for-python#1581]
I have some files in blob storage that I want publicly available, but I"m unsure of how someone would fetch them.

It looks like the [`azure.storage.common.storageclient module`](https://azure-storage.readthedocs.io/en/latest/ref/azure.storage.common.storageclient.html) is the right way to go, but It's unclear how to use this.

**Comment by lmazuel** [comment]
Hi @apengwin 
Please ask your question on the specific issue tracker of Storage:
https://github.com/Azure/azure-storage-python/issues

Thanks
