### ISSUE TITLE
How to get cpu usage and memory consumption

### ISSUE THREAD

**Issue by Julius-ZCJ** [Azure/azure-sdk-for-python#15826]
I need help:

When I use python deploy a container in azure, my leader want to get this container CPU usage, memory consumption, logs and other information. How I can use python sdk get these info?

If you can give me some suggestions, I'll be very grateful to you

**Comment by xiangyan99** [comment]
Could you add more information about which azure-service do you use? e.g. do you deploy your container using ACI/AKS or VMs? 

That can help us route your question.

Thanks.

**Comment by Julius-ZCJ** [comment]
I refer to the azure demo deploy the container by python, URL is: https://github.com/Azure-Samples/container-instances-python-manage
use azure python lib is azure-mgmt-containerinstance
I think this way maybe ACI

**Comment by xiangyan99** [comment]
Thank you @Julius-ZCJ for the information.

@msyyc the customer is using azure-mgmt-containerinstance library. Do you know if we can retrieve the information in our library?

**Comment by msyyc** [comment]
https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/get#containergroup
The link up is the REST API docs about "get" function of “container-instances”. "get" could return some specific information about container group with query parameters. Maybe it could give some useful guidance about the question.

**Comment by Julius-ZCJ** [comment]
@msyyc Thank you for your reply, I use the api  "get" of  “container-instances”, but not include information what I want, 
I need the info of container's cpu and memory usage when the container is running. Do you have any other advice

**Comment by msyyc** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-overview
Link up is the reference docs about "monitor". And it could monitor the performance of container. Maybe it's useful for you.
