### ISSUE TITLE
RecoveryServices tests aren't running post pytest migrations

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/azure-sdk-for-python#1582]
Tests in test_mgmt_recoveryservices.py aren't running as test methods are written in `*_test` format which were supported in nosetest but not in pytest. pytest and standard python convention is `test_*`.

**Comment by lmazuel** [comment]
Damn, I missed that
I renamed the methods, re-recorded the tests and migrate them to the new test framework (see PR attached). Once it's green I'll merged.
Thanks for noticing!
