### ISSUE TITLE
Communication chat Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#15839]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/communication/azure-communication-chat/README.md):
![image](https://user-images.githubusercontent.com/57166602/102450880-5fa48900-4072-11eb-8ce2-3b03897f8340.png)

Suggestion:
Add `Source code| Package (Pypi)| API reference documentation | Product documentation`
As shown in the figure below about `app configuration`:
![image](https://user-images.githubusercontent.com/57166602/102450921-721ec280-4072-11eb-88de-344fb67e817d.png)
2.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-chat#create-a-thread):
![image](https://user-images.githubusercontent.com/57166602/102450959-882c8300-4072-11eb-9f3f-9410a517c3a0.png)

Reason:
NameError: name 'datetime' is not defined.

Suggestion：
Add code:
`from datetime import datetime`
3.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-chat#list-chat-threads):
![image](https://user-images.githubusercontent.com/57166602/102451056-bca03f00-4072-11eb-9669-5b3eef56f7b2.png)

Reason:
1).NameError: name 'pytz' is not defined.
2).NameError: name 'endpoint' and 'token' is not defined.
3).NameError: name 'ChatClient' is not defined.

Suggestion:
1). Add code: `import pytz`
2). Add code:
```
token = "<token>"
endpoint = "https://<RESOURCE_NAME>.communcationservices.azure.com"
chat_client = ChatClient(endpoint, CommunicationUserCredential(token))
```
3). Add code:
`from azure.communication.chat import ChatClient, CommunicationUserCredential`
4.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-chat#examples):
![image](https://user-images.githubusercontent.com/57166602/102451625-cd04e980-4073-11eb-8536-714db09a979d.png)

Suggestion: 
Update the examples summary as shown below:
![image](https://user-images.githubusercontent.com/57166602/102451638-d8581500-4073-11eb-86bc-ae3c2d5848c8.png)

@jongio for notification.

**Comment by sarkar-rajarshi** [comment]
Closing issue. This has been fixed.
