### ISSUE TITLE
Communication SMS Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#15841]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-sms#azure-communication-sms-package-client-library-for-python):
![image](https://user-images.githubusercontent.com/57166602/102452402-44874880-4075-11eb-8667-040710bd4b4c.png)

Suggestion:
Add `Source code| Package (Pypi)| API reference documentation | Product documentation`
As shown in the figure below about `app configuration`:
![image](https://user-images.githubusercontent.com/57166602/102452435-4fda7400-4075-11eb-8b98-95b5b848e33f.png)
2.
Section [Link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-sms#client-initialization):
![image](https://user-images.githubusercontent.com/57166602/102452486-6254ad80-4075-11eb-8a55-f7677afeb92e.png)

Reason:
Name 'SmsClient' is not defined.

Suggestion:
Add:
`from azure.communication.sms import SmsClient`
3.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-sms#sending-an-sms):
![image](https://user-images.githubusercontent.com/57166602/102452579-89ab7a80-4075-11eb-9bf4-1bfb787c7814.png)

Reason:
Name 'PhoneNumber' and 'SendSmsOptions' is not defined.

Suggestion:
Add:
`from azure.communication.sms import SendSmsOptions, PhoneNumber`
4.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-sms#troubleshooting):
![image](https://user-images.githubusercontent.com/57166602/102452638-a3e55880-4075-11eb-88b7-adaf0c9d19b3.png)

Suggestion:
Add Hyperlink for "[azure_core]":
[azure_core]: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/README.md

@jongio for notification.

**Comment by jbeauregardb** [comment]
@v-xuto I'm on call this week and I'm working on these issues you submitted. This is a PR that addresses your issues :)
https://github.com/Azure/azure-sdk-for-python/pull/16825
