### ISSUE TITLE
Communication Administration Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#15840]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-administration#azure-communication-administration-package-client-library-for-python):
![image](https://user-images.githubusercontent.com/57166602/102451966-7fd54780-4074-11eb-9047-db4e8458063a.png)

Suggestion:
Add `Source code| Package (Pypi)| API reference documentation | Product documentation`
As shown in the figure below about `app configuration`:
![image](https://user-images.githubusercontent.com/57166602/102452003-8f549080-4074-11eb-832f-5e5974d3a5b6.png)
2.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-administration#examples):
![image](https://user-images.githubusercontent.com/57166602/102452056-a7c4ab00-4074-11eb-96df-bbfeb4ed0202.png)

Suggestion:
Update as shown below：
![image](https://user-images.githubusercontent.com/57166602/102452082-b1e6a980-4074-11eb-94d7-edbdea5f0ae4.png)

3.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-administration#get-countries):
![image](https://user-images.githubusercontent.com/57166602/102452154-d6db1c80-4074-11eb-8539-66c0249632aa.png)

Reason:
1). NameError: name 'PhoneNumberAdministrationClient' is not defined
2). `connection_str` is not defined.

Suggestion:
Add code:
```
from azure.communication.administration import PhoneNumberAdministrationClient
import os
connection_str = os.getenv('AZURE_COMMUNICATION_SERVICE_CONNECTION_STRING')
```
4.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-administration#get-area-codes):
![image](https://user-images.githubusercontent.com/57166602/102452248-fffbad00-4074-11eb-8ffb-f6289f22d7d4.png)

Suggestion:
Delete the extra "the".

@jongio for notification.

**Comment by jbeauregardb** [comment]
We are a opening a PR to address the identity package README issues. I'm going to close the issue, as our phone number documentation changed a lot due to the redesign of the SDK and we already took care of those little things in the new version.
