### ISSUE TITLE
Provide the Api doc for older SDK versions

### ISSUE THREAD

**Issue by CalebHui** [Azure/azure-sdk-for-python#15869]
Hi

My azure function is using azure-cosmo 3.1.2 .
I cannot find the api doc anymore. I can only find the latest version.
Can you provide the Api doc for older SDK versions as well?
If I don't have the doc, I'll need to refactor all my azure functions whenever you publish a new version.

Thanks

**Comment by SuperChenSSS** [comment]
Hi @msftbot, can anyone take a look at it?

**Comment by Rodrigossz** [comment]
Not a V4+ issue. Not an issue after all, it's an old version documentation request. I suggest to check the old SDK repo: history, examples, tests, etc.... 

https://github.com/Azure/azure-cosmos-python

Our STRONG suggestion is to upgrade to the latest version. Also, you have my email, so please email me with your exactly question on the old SDK usage.

Tks
