### ISSUE TITLE
FileSystemClient.get_paths() StorageErrorException raising broken by another exception

### ISSUE THREAD

**Issue by CharlesAtDCube** [Azure/azure-sdk-for-python#15871]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.2.0
- **Operating System**:Ubuntu 18_04 & Debian (the one hosted on Azure functions v3)
- **Python Version**: 3.6.7 & 3.6.12

**Describe the bug**
When raising a StorageErrorException, which happens when a FileSystemClient.get_paths(path="some/invalid/path") is called then iterated on (because it's a generator), the exception raises an other error, which is new and prevent us from just handling the StorageErrorException.
The other exception is 
AttributeError: 'dict' object has no attribute 'iter'
and comes from the file
.env/lib/python3.6/site-packages/azure/storage/filedatalake/_shared/response_handlers.py in process_storage_error(storage_error) (line 94)

azure-blob-storage 12.6.0 is installed.

**To Reproduce**
1. Create your virtual environment,
2. Install azure-storage-file-datalake without specifying any version
3. Instanciate a valid ServiceClient and its FileSystemClient, pointing on an ADLS
4. Use the method get_paths() on a path that doesn't exist
5. Iterate over the path, as you would normally do to list a directory's content.

**Expected behavior**
If the path given as an argument of the get_paths() method doesn't exist, the StorageErrorException should be raised. Nothing more, nothing less.

**Screenshots**
Here is a demonstration, with a path that exists and a path that does not.
https://ibb.co/Xt6zg90

**Additional context**
Downgrading the packages to 12.1.2 and 12.4.0 respectively, solves the problem.

**Comment by xiafu-msft** [comment]
Hi  @CharlesAtDCube 

Thanks for reaching out with the suggestions!
We've noticed it's a bug and the fix hasn't been released yet. Hope this is not blocking you and we will release it later!

**Comment by tasherif-msft** [comment]
Hi @CharlesAtDCube! This issue should have been resolved in our most recent release :)
If you could update your datalake version to 12.2.2 and let me know if this issue still persists there.

Thank you.
