### ISSUE TITLE
AzureML: User managed identity attached to compute cluster does not work

### ISSUE THREAD

**Issue by gdippolito** [Azure/azure-sdk-for-python#15892]
- **Package Name**:  azure-identity
- **Package Version**:  1.5.0
- **Operating System**: Linux 
- **Python Version**:  3.7

**Describe the bug**

A custom docker container running on a compute cluster with a user managed identity does not seem to authenticate with Azure identity when running in AzureML

This is the logs I when I run my python code:
```
WARNING 2020-12-21 18:04:30,166 azure.identity._internal.get_token_mixin AppServiceCredential.get_token failed: No token received.
WARNING 2020-12-21 18:04:30,166 azure.identity._internal.decorators ManagedIdentityCredential.get_token failed: No token received.
WARNING 2020-12-21 18:04:30,166 azure.identity._credentials.chained ChainedTokenCredential.get_token failed: ManagedIdentityCredential raised unexpected error "No token received."
WARNING 2020-12-21 18:04:30,166 azure.identity._credentials.chained ChainedTokenCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	ManagedIdentityCredential: No token received.
```

**To Reproduce**
1. Create a compute cluster with a managed identiy attached to read data from a blob storage
2. Create a custom docker image with the azure sdk to fetch data from blob storage
3. Run the aforementioned docker image in the AzureML cluster created above.

**Expected behavior**
Python SDK can authenticate using  a manged identity.

**Comment by mccoyp** [comment]
Hello, thank you for opening an issue for this! I'll get working on trying to reproduce this while I look into what may be causing the issue.

**Comment by mccoyp** [comment]
It would be helpful to know more about your Docker setup. Did you follow the walkthrough to [use a prebuilt Docker image](https://docs.microsoft.com/azure/machine-learning/how-to-use-environments#use-a-prebuilt-docker-image), or specify your own image as shown in the following section?

**Comment by gdippolito** [comment]
Hi @mccoyp thanks for your response. 

I have managed to fix the issue by doing the following things:
1. Rollback azure-identity to 1.4.1 (due to https://github.com/Azure/azure-sdk-for-python/issues/15361)
2. Authenticate with `identity.ManagedIdentityCredential(client_id='MY_CLIENT_ID)` (MY_CLIENT_ID is the client id of the managed identity attached to the compute cluster in the workspace)

Does this make sense to you? 

Thanks

**Comment by mccoyp** [comment]
Got it, I'm glad you were able to find a solution! This behavior makes sense. I'll leave this issue open and provide an update when we add support for Azure ML in Identity.

**Comment by chlowell** [comment]
azure-identity 1.6.0b1 has a fix for #15361 and is available now. Please feel free to reopen this issue, or open a new one, if you encounter further problems.

**Comment by gdippolito** [comment]
@chlowell when are.you planning to create a release for azure-identity?

**Comment by chlowell** [comment]
Last month's 1.6.0b1 fixed #15361, is it not working for you?

**Comment by gdippolito** [comment]
It is not in pypy so I assumed that 1.6.0b1 was a beta release?

**Comment by chlowell** [comment]
It's a beta, [available from PyPI](https://pypi.org/project/azure-identity/1.6.0b1/). We plan to release a stable 1.6.0 in April or May.

**Comment by gdippolito** [comment]
Hi @chlowell are you expecting to do a release anytime soon? we would like to use all the feature and bug fixes added in 1.5 and 1.6 but we are a bit scare to pin our codebase to a beta version. 

What is the reasoning for waiting so long to cut a release?

**Comment by chlowell** [comment]
We'll release 1.6 on May 11. We delayed the stable release another sprint to collect more feedback from users who couldn't begin testing a complex new feature until early this month. I don't expect the stable release to break any API in 1.6.0b3, so it's probably safe to adopt from that perspective--and it would also be super helpful if you could verify whether the latest beta resolves the problems you've seen--but the public surface hasn't yet received final approval. I can update this issue once it has (should be within the next couple weeks); would that be helpful?

**Comment by gdippolito** [comment]
Hi @chlowell I have just run a training job over the weekend on AzureML using version 1.6.0b3.

The good news is that with this version we don't face the #15361 anymore. However, there is definitely a strange behaviour on this version that I don't think it is expected. 

My training job started at around 8pm on the 30th of April. I can see some logs at the beginning of training (around 20s lines) when we first start pulling data from azure blob storage and we invoke the authentication (all normal here). Every day the identity refresh since I believe the token last 24hrs, and there will be the following lines logged (weird the first refesh was after 12hrs):
```
INFO 2021-05-01 08:47:38,277 azure.identity.aio._internal.get_token_mixin AppServiceCredential.get_token succeeded
INFO 2021-05-01 08:47:38,277 azure.identity.aio._internal.decorators ManagedIdentityCredential.get_token succeeded
INFO 2021-05-01 08:47:38,278 azure.identity.aio._internal.get_token_mixin AppServiceCredential.get_token succeeded
INFO 2021-05-01 08:47:38,278 azure.identity.aio._internal.decorators ManagedIdentityCredential.get_token succeeded
INFO 2021-05-01 08:47:38,279 azure.identity.aio._internal.get_token_mixin AppServiceCredential.get_token succeeded
INFO 2021-05-01 08:47:38,281 azure.identity.aio._internal.get_token_mixin AppServiceCredential.get_token succeeded
```
However, this message will be logged an insane amount of time (over 100K times) for each day roughly at the same time. The issue is so bad that after 3 days of training we will have more than 120MB of logs. 

Also, I can see these messages logs for more than 5 minutes ( at the rate of the above message you can imagine how many logs we get).   

I can probably exclude from the logger those messages but I think something is not quite as expected. 

Do you have any ideas what might cause this problem? 

Please let me know if you need more details.

**Comment by chlowell** [comment]
I expect to see those messages every time the application calls `get_token` and I think that's what's happening here. The changing timestamps indicate these aren't duplicate messages. If there's some problem with token expiry and your application actually sends thousands of token requests, it should hit the managed identity endpoint's rate limit and raise an error. So, I guess your application is calling `get_token` thousands of times, which is odd, and mostly receiving a locally cached token. Are you calling `get_token` in your application code, or handing the credential instance off to an Azure SDK client?

**Comment by gdippolito** [comment]
We don't invoke `get_token` directly but we are using Azure Blob storage SDK (12.8.1 so latest). 

I'm pretty sure this behaviour is not present in the current version of azure-identity we are using in production (`1.4.1`). 

I have changed very little while testing this version. In fact I have only removed a force identity refresh logic that we added because the token was not automatically refreshed after 24 hours. 

Hope it helps.

**Comment by chlowell** [comment]
I don't see how the credential itself could do this (and no one else has reported similar behavior). A successful call to `get_token` logs the two messages you see, once each, as the method returns, and `get_token` doesn't recurse. So I'm thinking a client is calling `get_token` thousands of times, which is unexpected. A typical client would call `get_token` at most once per hour. Does your application use multiple threads or subprocesses? I think you would see this behavior if you had many client instances sharing one credential instance.

**Comment by gdippolito** [comment]
Yes, we do use multi thread and multi processing for data loading. However, we are talking about 32 processes max running at the same time. It still does not explain why I see hundreds thousands of requests. 

About the fact that no one has reported this I'm not sure how many people will use a beta release in production?

**Comment by chlowell** [comment]
I agree it's still weird, I don't see how you would get hundreds of thousands of messages from at most 32 clients. If you create many client instances in your 32 processes though, that could do it. But I'm speculating here. I haven't been able to reproduce this in normal usage and looking over the code I don't see a way to do so. That doesn't mean you haven't exposed a bug in the SDK though. Can you extract a small example program from your application that reproduces the excessive logging?

**Comment by gdippolito** [comment]
I can see this behaviour only during identity refresh which I think was fixed in this release. When the job start we don't see any anomalies and I can count a reasonable amount of invocations.

**Comment by raz4** [comment]
@mccoyp @chlowell I'm facing the same issue with DefaultAzureCredential which is the recommended method for authenticating. The workaround with "identity.ManagedIdentityCredential" mentioned above works with azure-identity 1.6.0, but we prefer to use DefaultAzureCredential for consistency, convenience, etc. Are there any plans to address this or will we have to stick with the workaround above?

**Comment by chlowell** [comment]
I take it you're looking for a way to specify a managed identity's client ID? DefaultAzureCredential takes that as an argument: `DefaultAzureCredential(managed_identity_client_id="...")`. Alternatively, set the environment variable AZURE_CLIENT_ID.

**Comment by raz4** [comment]
@chlowell I was hoping to avoid specifying the client ID altogether. Do we have to specify client ID? I just confirmed now that invoking "DefaultAzureCredential()" on an Azure VM with system assigned or user assigned identity works, but this method doesn't seem to work on certain compute nodes under Azure ML. For reference, I was following this documentation - [https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-reinforcement-learning#define-head-and-worker-compute-targets](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-reinforcement-learning#define-head-and-worker-compute-targets) - to create a cluster with user assigned identity on which we run DefaultAzureCredential.

**Comment by chlowell** [comment]
DefaultAzureCredential (also ManagedIdentityCredential) has the same requirements as the platform in this respect, so if Azure ML requires a client ID, the credential won't work without it. Do you get a clear error message?

**Comment by raz4** [comment]
Ok understood. I get warnings and eventually a clear authentication error like below...
```
WARNING:azure.identity._internal.get_token_mixin:AppServiceCredential.get_token failed: No token received.
WARNING:azure.identity._internal.decorators:ManagedIdentityCredential.get_token failed: No token received.
WARNING:azure.identity._credentials.chained:DefaultAzureCredential.get_token failed: ManagedIdentityCredential raised unexpected error "No token received."
WARNING:azure.identity._credentials.chained:DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
	ManagedIdentityCredential: No token received.
...
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
```

The warnings are similar to what the original issue described, so that's how I ended up here. Anyway, thanks for your help!
