### ISSUE TITLE
Bug in azure-storage-blob

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-sdk-for-python#15919]
As shown in model serialization for ContentSettings， the required type for content_md5 is `str` as shown below: 
https://github.com/Azure/azure-sdk-for-python/blob/00c9044986e1bb35f7d2be0deb5935b5342ae1a7/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py#L621
But when uploading, content_md5 needs to be converted to `bytearray` and the following code would cause a bug when converting a string to bytearray.
https://github.com/Azure/azure-sdk-for-python/blob/00c9044986e1bb35f7d2be0deb5935b5342ae1a7/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L382
```
blob_content_md5=bytearray(content_settings.content_md5) if content_settings.content_md5 else None,
TypeError: string argument without an encoding
```
This would cause error when uploading with content_md5. Please fix asap.

**Comment by Rishab-Binoy** [comment]
Hi, I'm new to this. I searched online for this issue and I found out that the bytearray() function needs a second argument specifying the type of encoding required when the source is a string. I hope this solves this issue.

**Comment by xiafu-msft** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/13003
