### ISSUE TITLE
Creating ContainerInstanceManagementClient using client factory causes TypeError exception

### ISSUE THREAD

**Issue by bendavis78** [Azure/azure-sdk-for-python#15910]
Using `azure-mgmt-containerinstance==7.0.0`, I am unable to instantiate a `ContainerInstanceManagementClient` using `azure.common.client_factory.get_client_from_auth_file`

The following code:
```python
from azure.common.client_factory import get_client_from_auth_file
from azure.mgmt.containerinstance import ContainerInstanceManagementClient

AUTH_FILE = 'sp-auth.json'
aci_client = get_client_from_auth_file(ContainerInstanceManagementClient, auth_path=AUTH_FILE)
```
Results in the following exception:
```
...
    aci_client = get_client_from_auth_file(ContainerInstanceManagementClient, auth_path=AUTH_FILE)
  File "/home/ben/.virtualenvs/hive/lib/python3.9/site-packages/azure/common/client_factory.py", line 259, in get_client_from_auth_file
    return get_client_from_json_dict(client_class, config_dict, **kwargs)
  File "/home/ben/.virtualenvs/hive/lib/python3.9/site-packages/azure/common/client_factory.py", line 199, in get_client_from_json_dict
    return _instantiate_client(client_class, **parameters)
  File "/home/ben/.virtualenvs/hive/lib/python3.9/site-packages/azure/common/client_factory.py", line 32, in _instantiate_client
    return client_class(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'credential'
```

This appears to be due to the fact that the client class accepts a `credential` keyword argument, while the factory uses `credentials` (with an "s").

**Comment by Ardiea** [comment]
I'm hitting the same issue. I feel like I'm missing something obvious here but the documentation clearly outlines what you have above, with no need to provide a credential parameter via get_client_from_auth_file

I seem to have a workaround with this: 

`
os.environ["AZURE_AUTH_LOCATION"] = credential_path
credential = DefaultAzureCredential()
subscription_client = get_client_from_auth_file(SubscriptionClient, credential=credential, auth_path=credential_path)
`

It seems clunky and spews warnings when DefaultAzureCredential() is called as it steps through its various attempts.
