### ISSUE TITLE
get public IP address at the same time when I get VM information.

### ISSUE THREAD

**Issue by pylist** [Azure/azure-sdk-for-python#15925]
Hope to give me some suggestions, thank you

**Comment by 00Kai0** [comment]
Hi @pylist , this python sdk is based on restful API, so it just shows what api responses. 
You have to get these info by at least two operations: [GetVMInfo](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get) and [Get Public IP Address](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get)

If you have problems about code, I can show you more demo code.
