### ISSUE TITLE
 Renaming EventGridSharedAccessSignatureCredential 

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#15938]
received feedback in ux study that the name is too long 

- use AzureSasCredential instead

**Comment by lmazuel** [comment]
TBD consistency with all languages

**Comment by lmazuel** [comment]
Also, we might be able to use the new azure-core type to settle that discussion:
https://github.com/Azure/azure-sdk-for-python/pull/15946
