### ISSUE TITLE
Clarify and fix if necessary, test inheriting from AzureTestCase, but don't do actual HTTP calls

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#15930]
We might need to split the helpers of the tests from the recording (TBD)

**Comment by lmazuel** [comment]
See https://github.com/Azure/azure-sdk-for-python/issues/14217 and https://github.com/Azure/azure-sdk-for-python/pull/15858

**Comment by seankane-msft** [comment]
This needs to be expanded to include services that use uamqp. (servicebus,  etc.)
