### ISSUE TITLE
Send method should return something

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#15936]
UX study feedback - one of the feed back is that it would be good to have send method returning something.

While the service doesn't return anything, perhaps logging something would be a good middle geound? or even better, if the service team could take a look.

**Comment by lmazuel** [comment]
What was expecting the user to receive?

**Comment by lmazuel** [comment]
I don't know what we should do, but for this milestone we should take a decision (on the consistency discussion).

**Comment by rakshith91** [comment]
ensure raw_response_hook is working

**Comment by rakshith91** [comment]
No action needed. Ensured that the raw response hook is working
