### ISSUE TITLE
StackOverflow cleanup Track 1 references, answer unanswered questions for Tables

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#15931]

**Comment by seankane-msft** [comment]
|Issue|Link|Status|Action|SDK Version|Python Version|Platform|Age|
|-----|----|------|------|-----------|--------------|--------|---|
|Table Storage vs. Cosmos| [link](https://stackoverflow.com/questions/48372517/azure-table-storage-vs-cosmosdb-with-python) | Track 1 Answer | Give track 2 sample | Track 1 | N/A | N/A | 2y |
| Query all rows | [link](https://stackoverflow.com/questions/28019437/python-querying-all-rows-of-azure-table) | Track 1 Answer | Give Track 2 sample with `TableClient` | Track 1 | N/A | N/A | 5y |
| Unicode Syntax Error | [link](https://stackoverflow.com/questions/29457339/azure-table-storage-python-sdk-invalid-syntax) | Answer for Python 3.2/3.3 releases | No response needed | Track 1 | Python 3.2 | Raspbian / Windows | 5y |
| Use Tables in Azure Functions | [link](https://stackoverflow.com/questions/64138846/how-to-catch-an-exception-thrown-by-azure-table-in-python-azure-function) | Update w/ Track 2 Code Sample | Python 3.8 | Azure Functions | N/A | N/A | 2m |
| Insert vs. Update Entity | [link](https://stackoverflow.com/questions/57575367/conflict-python-insert-update-into-azure-table-storage) | Track 1 Answer | Track 2 Update using `TableClient` and `ETag` | Track 1 | N/A | N/A | 1y4m |
| Range Queries | [link](https://stackoverflow.com/questions/34839479/python-how-to-make-range-queries-in-azure-table-storage) | Answer resolved syntax error in query | No response | Track 1 | N/A | N/A | 5y |
| Reading `EntityProperty` | [link](https://stackoverflow.com/questions/49992431/azure-table-storage-querying-using-python-read-integer-column) | Track 1 Answer | Track 2 answer using `TableClient.query_entities` | Track 1 | N/A | N/A | 1y8m |
| Using `top` in query | [link](https://stackoverflow.com/questions/23148562/azure-table-taken-method-in-python) | Track 1 Answer | Track 2 Answer with `TableClient.query_entities(..., top=n)` | Track 1 | N/A | N/A | 6y8m |
| Queries based on datetimes | [link](https://stackoverflow.com/questions/58528844/how-to-query-azure-table-via-python-for-timestamp-correctly) | Track 1 answer | No update necessary | Track 1 | N/A | N/A | 1y4m |
| Azure Functions with Tables | [link](https://stackoverflow.com/questions/62780962/update-azure-table-using-azure-function-app-with-python) | Track 1 cosmosdb answer | Update w/ Track 2 Tables/Cosmos answer | Track 1 | N/A | N/A | 6m |
| Fetch all Table Names | [link](https://stackoverflow.com/questions/28786729/fetching-windows-azure-storage-tables-names-through-python-api) | Track 1 answer | Update w/ Track 2 answer | Track 1 | N/A | N/A | 1y1m |
| Batch operations | [link](https://stackoverflow.com/questions/22987752/azure-storage-table-python-batch-does-not-fail) | Track 1 answer + bug fix | Track 2 Update | Track 1 | Python 2.7 | N/A | 6y6m |

**Comment by seankane-msft** [comment]
These have all been answered, closing this issue now.
