### ISSUE TITLE
Maximum retry-after time

### ISSUE THREAD

**Issue by akx** [Azure/azure-sdk-for-python#15952]
In some cases, when an ARM resource read/write quota has been depleted, the Azure API may return a `Retry-After` with a value like 120, or even something like 20 or 45 minutes, which is completely undetectable from client code at present, and the calling thread just stalls.

It would be nice to be able to configure the maximum time the library honors for `Retry-After`s, so it would raise an exception instead of even starting to wait for an interval too long.

This is related to Azure/msrestazure-for-python#99/#125.

The workaround in https://github.com/Azure/msrestazure-for-python/issues/99#issuecomment-394517692 has the caveat that even in timeout situation, the call would eventually be run to completion, since [`ThreadPoolExecutor.shutdown()` (which is called via `__exit__`) `join`s the other thread(s)](https://github.com/python/cpython/blob/cc353a0cd95d9b0c93ed0b60ba762427a94c790d/Lib/concurrent/futures/thread.py#L198-L204).

**Comment by lmazuel** [comment]
Hey @akx 
I moved your issue to a more accurate repo, since we're not working on msrestazure anymore, while your problem is still accurate in azure-core (the new version).
I can't tell when we can address it, but your problem is well defined enough that I think it's valuable to keep it in our close backlog.

**Comment by lmazuel** [comment]
@xiangyan99 @johanste to rephrase: in some instances retry-after during polling can be incredibly high due to quota exemption and there is not way right now to define a max time. This means you can happen to poll 2 hours, and it's not necessarily what you want your code to behave.
