### ISSUE TITLE
SubscriptionsOperations.list() results differs from azure cli `account show` results when using AzureCliCredential

### ISSUE THREAD

**Issue by jamesongithub** [Azure/azure-sdk-for-python#15968]
- **Package Name**: azure-mgmt-resource
- **Package Version**: 15.0.0
- **Operating System**: osx
- **Python Version**: 3.9.0

**Describe the bug**

**To Reproduce**
cli
```
1. az login
2. az account show
```

sdk
```
credential = AzureCliCredential()
subscription_client = SubscriptionClient(credential)
print(subscription_client.subscriptions.list())
```

**Expected behavior**
Expected the subscriptions to be the same in each flow.

az account show seems to show all subscriptions you have access to

using the sdk it only shows subscriptions for the default tenant (unsure how this is currently chosen, seems to be the first tenant you have access to)

SubscriptionsOperations.list() doesn't seem to have a way to pass a tenant id or perhaps it's undocumented.

**Additional context**

**Comment by 00Kai0** [comment]
Hi @jamesongithub , you could create a new issue in [azure-cli](https://github.com/Azure/azure-cli).
Cli is based on python sdk, it's not a problem in sdk. It seems like that cli does more thing when you call `az account show`.
I will close this one :)

**Comment by jamesongithub** [comment]
Hi @00Kai0,

My understanding is that azure-cli uses the python sdk, so everything that the cli can do, the sdk should be able to do.

Perhaps you could you explain how to list all subscriptions after you have authenticated with `AzureCliCredential`? Currently it only lists subscriptions for the default tenant right now. Or at least a way to switch tenants so we can build list.

**Comment by jamesongithub** [comment]
ping @00Kai0
