### ISSUE TITLE
Adopt to Arm Template strategy for Azure Eventgrid

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#15967]
Currently, there are a lot of env variables in eventgrid tests.yml

Use the arm template instead to reduce maintainance.

To add a deployment of arm templates you'll need a test-resources.json file and parameter DeployArmTemplate: true to your tests.yml file. The former you can probably take from the .NET/JS/Java sdks.

**Comment by lmazuel** [comment]
Not GA required, I moved that to March milestone
