### ISSUE TITLE
Enviroment variables is not respected 

### ISSUE THREAD

**Issue by AmericanY** [Azure/azure-sdk-for-python#15960]
isn't possible to use environment variable with the package?

something like `HTTPS_PROXY` is not respected here!

**Comment by xiangyan99** [comment]
Thanks for reporting.

Could you help to check if you have use_env_settings enabled?

For more information, you can check https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#proxy-settings.
