### ISSUE TITLE
Support for `addPassword`

### ISSUE THREAD

**Issue by srusun** [Azure/azure-sdk-for-python#15971]
**Feature Request:** 
Would like a way to create a client secret for an Azure app using the python

**Problem:** 
To create the client secret, we go STRAIGHT TO HTTP!! 
We were UNABLE to find an azure-sdk-for-python solution that supported this endpoint.
This seems like a bug or a design flaw!

**Current Solution:**
```
header = {
    "Content-Type": "application/json",
    "Authorization": "Bearer {}".format(graph_credentials.token["access_token"]),
}
url = "https://graph.microsoft.com/v1.0/servicePrincipals/{}/addPassword".format(sp.object_id)
payload = {
    "passwordCredential": {"displayName": "newlyCreatedClientSecret"},
}
response = requests.post(url, data=json.dumps(payload), headers=header)
response.raise_for_status()
secret_info = json.loads(response.text)
```
This request was brought up in a previous issue (https://github.com/Azure/azure-sdk-for-python/issues/14022)

**Comment by lmazuel** [comment]
I realized I misguided you, I was thinking you need that in azure-graphrbac, but you need that from the Microsoft Graph and we dont' have it here. You might want to create your issue https://github.com/microsoftgraph/msgraph-sdk-python-core instead.
