### ISSUE TITLE
The resource type 'billingAccounts' could not be found in the namespace 'Microsoft.Billing' for api version '2019-10-01'. The supported api-versions are '2018-05-31,2018-06-30,2018-11-01-preview,2019-10-01-preview,2020-05-01,2020-11-01-privatepreview'.

### ISSUE THREAD

**Issue by Groumy** [Azure/azure-sdk-for-python#15986]
- **Package Name**:  azure.mgmt.consumption
- **Package Version**: 8.0.0
- **Operating System**: Ubuntu 20.4 through WSL on Windows 10
- **Python Version**: Python 3.8.5

**Describe the bug**
While trying to perform a call the function `get_for_billing_period_by_billing_account` of the `BalancesOperations` model, the folowing error is encountered : 

> The resource type 'billingAccounts' could not be found in the namespace 'Microsoft.Billing' for api version '2019-10-01'. The supported api-versions are '2018-05-31,2018-06-30,2018-11-01-preview,2019-10-01-preview,2020-05-01,2020-11-01-privatepreview'.

**To Reproduce**
1. make a call to the method `get_for_billing_period_by_billing_account` with a Enterprise Agreement Id for the current month.

**Expected behavior**
Get balance details 

**Screenshots**

Relevant Stack trace : 
```
  File "/home/user/.local/lib/python3.8/site-packages/azure/mgmt/consumption/operations/_balances_operations.py", line 151, in get_for_billing_period_by_billing_account
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (InvalidResourceType) The resource type 'billingAccounts' could not be found in the namespace 'Microsoft.Billing' for api version '2019-10-01'. The supported api-versions are '2018-05-31,2018-06-30,2018-11-01-preview,2019-10-01-preview,2020-05-01,2020-11-01-privatepreview'.
```

**Additional context**
The version is hardcoded on [line 127 of the file `_balances_operations.py`](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_balances_operations.py#L127)

If the api_version was an optional param it would allow use to specify a supported version.

**Comment by 00Kai0** [comment]
https://docs.microsoft.com/en-us/rest/api/consumption/balances/getforbillingperiodbybillingaccount
It seems like a swagger issue.

**Comment by yooakim** [comment]
I get the same error but I am trying to use PowerBI with the Axure Cost Management connector. Exactly the same issue. `Charges
The resource type 'billingAccounts/billingProfiles' could not be found in the namespace 'Microsoft.Billing' for api version '2019-10-01'. The supported api-versions are '2018-11-01-preview,2019-10-01-preview,2020-05-01,2020-11-01-privatepreview,2020-12-15-privatepreview'.`

![image](https://user-images.githubusercontent.com/862546/134226737-dfaf1232-9aa4-49d6-9c9d-816b56a9b496.png)

**Comment by janakiramachandran** [comment]
This is an issue on the Billing team.https://armmanifest.visualstudio.com/One/_git/Manifest?path=/MICROSOFT.BILLING/PROD/MANIFEST.JSON The version specified is not supported.

**Comment by janakiramachandran** [comment]
We have updated the version to route to the right version, [pr link](https://github.com/Azure/azure-sdk-for-python/pull/22003)
