### ISSUE TITLE
Post azure-mgmt-datafactory 1.0.0 this release on Jan 3 2021 - Create or Update Datasets not working

### ISSUE THREAD

**Issue by NarendarT89** [Azure/azure-sdk-for-python#15993]
**Describe the bug**
Post azure-mgmt-datafactory 1.0.0 this release on Jan 3 2021 - Create or Update Datasets not working

**To Reproduce**
Install module azure-mgmt-datafactory
use adf_client.datasets.Create_or_update to manage a dataset in ADF

***Code Snippet***
adf_client.datasets.create_or_update(resource_group_name = rg_name,
                                     factory_name = df_name,
                                     #dataset = ds_name,
                                     dataset_name = ds_name,
                                     properties = ds_sql_server)

**Expected behavior**
adf_client.datasets.create_or_update(resource_group_name = rg_name,
                                     factory_name = df_name,
                                     dataset_name = ds_name,
                                     properties = ds_sql_server)

**Screenshots**
![image](https://user-images.githubusercontent.com/77040154/103732142-a283bd80-4f9b-11eb-8655-e47b7aab824d.png)

**Setup (please complete the following information):**
 - Python Version: Python 3.8
 - SDK Version: azure-mgmt-factory 1.0.0

**Additional context**
Ideally expectation is that create or update doesn't have an argument called dataset but it has only dataset_name. Post the latest management factory update on 3rd Jan 2021 , we face issue like create_or_update dataset expecting an argument dataset and the same is not present in documentation as well.

https://docs.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.operations.datasetsoperations?view=azure-python#create-or-update-resource-group-name--factory-name--dataset-name--properties--if-match-none--custom-headers-none--raw-false----operation-config-

**Comment by 00Kai0** [comment]
Hi @NarendarT89 , it seems like that this doc has something wrong. You have to change `properties` to `dataset`.

Example:
```
adf_client.datasets.create_or_update(
    resource_group_name=rg_name,
    factory_name=df_name,
    dataset_name=ds_name,
    dataset=ds_sql_server)
```

**Comment by NarendarT89** [comment]
Yes , thank you @00Kai0  .. Thanks for your help ..also I wanted to share you the latest document link 
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-datafactory/1.0.0/azure.mgmt.datafactory.operations.html?highlight=azure%20mgmt%20datafactory%20datasets#azure.mgmt.datafactory.operations.DatasetsOperations
