### ISSUE TITLE
azure.storage.filedatalake.PathProperties last_modified property is string not datetime

### ISSUE THREAD

**Issue by marcin-vt** [Azure/azure-sdk-for-python#16019]
- **Package Name**:  azure-storage-file-datalake 
- **Package Version**: 12.2.0
- **Operating System**: Ubuntu 16.04
- **Python Version**:  3.6.9

**Describe the bug**
azure.storage.filedatalake.PathProperties last_modified property is string not datetime - as described in [documentation](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.pathproperties?view=azure-python) and also in the code itself 

> :ivar datetime last_modified:  A datetime object representing the last time the directory/file was modified.

**To Reproduce**
```
from azure.storage.filedatalake import DataLakeServiceClient
t_fsc = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
    "https", sa), credential=sa_key).get_file_system_client(file_system=container)
l = t_fsc.get_paths().next().last_modified
print(f'{type(l)}: {l}')
```
The above code prints out:
_<class 'str'>: Wed, 16 Dec 2020 14:45:33 GMT_

**Expected behavior**
last_modified should return datetime value.

**Comment by xiafu-msft** [comment]
Hi @marcin-vt 

Thanks for catch this bug. We posted a fix https://github.com/Azure/azure-sdk-for-python/pull/16093 

If it's blocking you, feel free to install this .whl file after unzip it,
the commant is` pip install <path/to/>azure_storage_file_datalake-12.2.1-py2.py3-none-any.whl`
[azure_storage_file_datalake-12.2.1-py2.py3-none-any.zip](https://github.com/Azure/azure-sdk-for-python/files/5799204/azure_storage_file_datalake-12.2.1-py2.py3-none-any.zip)

**Comment by marcin-vt** [comment]
Thanks for fixing it @xiafu-msft.
