### ISSUE TITLE
Insufficient privileges to complete the operation while trying to get AD groups

### ISSUE THREAD

**Issue by abarisuzuner** [Azure/azure-sdk-for-python#16018]
Hi! I am trying to write a very simple script to list Azure AD groups. Here is the script:
```
from azure.common.credentials import ServicePrincipalCredentials
from azure.graphrbac import GraphRbacManagementClient

credentials = ServicePrincipalCredentials(
    client_id="1111-1111",
    secret="asd",
    resource="https://graph.windows.net",
    tenant = 'me.onmicrosoft.com'
)
tenant_id = '11111-1111'

graphrbac_client = GraphRbacManagementClient(credentials, tenant_id)

groups = graphrbac_client.groups.list()
for g in groups:
  print(g.display_name)
```

The app registration I created on azure has `Directory.Read.All` and `Group.Read.All` permissions. But I still get `azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation.` 

What am I missing?

**Comment by SaurabhSharma-MSFT** [comment]
@abarisuzuner Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by Prajyotbiradar** [comment]
> @abarisuzuner Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .



> Hi! I am trying to write a very simple script to list Azure AD groups. Here is the script:
> 
> ```
> from azure.common.credentials import ServicePrincipalCredentials
> from azure.graphrbac import GraphRbacManagementClient
> 
> credentials = ServicePrincipalCredentials(
>     client_id="1111-1111",
>     secret="asd",
>     resource="https://graph.windows.net",
>     tenant = 'me.onmicrosoft.com'
> )
> tenant_id = '11111-1111'
> 
> graphrbac_client = GraphRbacManagementClient(credentials, tenant_id)
> 
> groups = graphrbac_client.groups.list()
> for g in groups:
>   print(g.display_name)
> ```
> 
> The app registration I created on azure has `Directory.Read.All` and `Group.Read.All` permissions. But I still get `azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation.`
> 
> What am I missing?

Can you post the answer here?

**Comment by felixmarch** [comment]
I suspect the answer is related to [this announcement](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363)

You may want to explore how to use MS Graph API from [this community](https://github.com/ansible-collections/azure/pull/1112/files)? :eyes:
