### ISSUE TITLE
Azure Blob service access - Python client with Proxy

### ISSUE THREAD

**Issue by Balachandar-R** [Azure/azure-sdk-for-python#1602]
Hi Team,

I need to list down the blobs available in the Azure Blob containers. But python client is running behind the proxy. Could you please tell me how to access the azure services via proxies in python code level.

Thanks,
Balachandar Raju

**Comment by lmazuel** [comment]
Hi @Balachandar-R 
Azure storage is not this repo, but here:
https://github.com/Azure/azure-storage-python

That being said, we all use `requests` as core library, this might help:
http://docs.python-requests.org/en/master/user/advanced/#proxies

Especially the environment variable.

If you have more specific question on how to declare it using the azure-storage client, please open an issue in the above repo.

Thanks!
