### ISSUE TITLE
Enable DDOS Premium feature using Python SDK

### ISSUE THREAD

**Issue by Chike-MSFT** [Azure/azure-sdk-for-python#16025]
Customer is trying to enable DDOS Premium feature using Python SDK: the source code below was provided by customer.  Why doesn't the code work?

`import os
import sys

import azure.mgmt.network
from azure.mgmt.network import NetworkManagementClient

from azauthentication import credential, subscription_id, ddoscred, ddossubscriptionId

netwk_client = NetworkManagementClient(credential, subscription_id)
vnets= netwk_client.virtual_networks.list_all()

netwk_client2 = NetworkManagementClient(ddoscred, ddossubscriptionId)
ddosId = [x.id for x in netwk_client2.ddos_protection_plans.list()][0]

for vnet in vnets:
    if vnet.name == "dev2_westus2_logging_virtual_network":
        print(vnet.name, vnet.resource_guid, vnet.ddos_protection_plan)
        vnet.ddos_protection_plan = azure.mgmt.network.v2020_06_01.
        vnet.ddos_protection_plan.id = ddosId
        vnet.enable_ddos_protection = True
        netwk_client.virtual_networks.begin_create_or_update(
            "dev2_westus2_logging", 
            "dev2_westus2_logging_virtual_network",
            vnet
        )
`

**Comment by 00Kai0** [comment]
Hi @Chike-MSFT , Can you show more error log ?
