### ISSUE TITLE
[BUG Bash] Display name is None for the tenants returned from SubscriptionClient.

### ISSUE THREAD

**Issue by ranjit6168** [Azure/azure-sdk-for-python#16038]
**Describe the bug**
 getting Tenant name none using SubscriptionClient.

***Code Snippet***
        sc = SubscriptionClient(<credentials>, base_url=cloud_base_url)
        for tenant in sc.tenants.list:
                print("tenant name: {}".format(tenant.display_name))

**Expected behavior**
should return tenant name configured.

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**
I do not have direct access to AAD.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by 00Kai0** [comment]
Hi @ranjit6168 , if you get `None`, it means service api does not return this paramter in response.
It's not a SDK Issue.
