### ISSUE TITLE
Bad Request when creating Data Factory resources

### ISSUE THREAD

**Issue by init-skr** [Azure/azure-sdk-for-python#16036]
- **Package Name**: azure.mgmt.datafactory
- **Package Version**: 1.0.0
- **Operating System**: Windows 10
- **Python Version**: 3.9.1

**Describe the bug**
Creating any kind of resource inside the data factory like *AzureKeyVaultLinkedService* or *AzureSqlDatabaseLinkedService*  leads to a 

`HttpResponseError: Operation returned an invalid status 'Bad Request'`

**To Reproduce**
I am using the following code:
`credential = ClientSecretCredential(client_id, client_secret, tenant_id)`
`adf_client = DataFactoryManagementClient(credential, subscription_id)`
`kv_obj = adf.AzureKeyVaultLinkedService('https://{0}.vault.azure.net/'.format(kv_name))`
`kv = adf_client.linked_services.create_or_update(rg_name, df_name, kv_name, kv_obj)`

**Expected behavior**
Create the linked service and report HTTP 200.

**Additional context**
With version 0.15.0 it works perfectly fine and everything is created as expected. However, I am using ServicePrincipalCredentials instead of ClientSecretCredential.

**Comment by 00Kai0** [comment]
The new version has a lot different than before, you could follow this [doc](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-datafactory/1.0.0/azure.mgmt.datafactory.operations.html?highlight=linkedservicesoperations#azure.mgmt.datafactory.operations.LinkedServicesOperations) to update your code

The right code of your question in v1.0.0:
```
credential = ClientSecretCredential(client_id, client_secret, tenant_id)
adf_client = DataFactoryManagementClient(credential, subscription_id)
kv_obj = adf.AzureKeyVaultLinkedService('https://{0}.vault.azure.net/'.format(kv_name))
link_service = adf.LinkedServiceResource(properties=kv_obj)
kv = adf_client.linked_services.create_or_update(rg_name, df_name, kv_name, link_service)
```

**Comment by init-skr** [comment]
Works like a charm, thank you very much for the quick response! 

Closing.
