### ISSUE TITLE
Azure Blob - Proxy Access 

### ISSUE THREAD

**Issue by Balachandar-R** [Azure/azure-sdk-for-python#1606]
Hi @lmazuel ,

With reference to the closed ticket(#1602)., Iwould like to know the python code to use the azure storage client using proxy. Please let me know the sample code in python.

Thanks
Balachandar Raju

**Comment by lmazuel** [comment]
Hi @Balachandar-R 

As I told you, Azure storage is not this repo, but here:
https://github.com/Azure/azure-storage-python

If you have more specific question on how to declare it using the azure-storage client, please open an issue in the storage repo.

Note that I suggested you to read the `requests` documentation that states:
http://docs.python-requests.org/en/master/user/advanced/#proxies
```
You can also configure proxies by setting the environment variables HTTP_PROXY and HTTPS_PROXY.

$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"

$ python
>>> import requests
>>> requests.get('http://example.org')
```

If this approach does not fit you and you want to declare proxy inside your Python code, _please ask the storage team._

Thanks!

**Comment by kishan19** [comment]
You might want to use the set_proxy method. For e.g. add the line 
"block_blob_service.set_proxy(<HOST_NAME>,<PORT>)"
