### ISSUE TITLE
AzureCliCredential.get_token failed: This credential requires exactly one scope per token request.

### ISSUE THREAD

**Issue by Neeraj-Sr** [Azure/azure-sdk-for-python#16067]
- **Package Name**: azure-identity
- **Package Version**: 1.5.0
- **Operating System**: WIndows 10
- **Python Version**:  3.8.5 64 bit

**Describe the bug**
I am trying to leverage AzureCliCredential() to retrieve authentication toke.
Here is the sample code
import msal
import azure.identity
from office365.graph_client import GraphClient

app = azure.identity.AzureCliCredential()
*token = app.get_token(scopes=["https://graph.microsoft.com/.default"])*
client = GraphClient(token)
drives = client.drives
client.load(drives)
client.execute_query()
for drive in drives:
    print("Drive url: {0}".format(drive.web_url))

I get an error 
AzureCliCredential.get_token failed: This credential requires exactly one scope per token request.
on execution of the get_token . As you can i have only one item in scope defined.

**To Reproduce**
Copy the above code in a standalone python file. Install packages msal and azure-identity and run the code

**Expected behavior**
I am expecting to get a proper token based on a previous az login.

**Screenshots**
See the error message inline

**Additional context**

**Comment by chlowell** [comment]
Try `get_token("https://graph.microsoft.com/.default")`. The signature is `get_token(*scopes: str, **kwargs)`, so `*scopes` is any number of strings passed positionally (i.e. not by keyword). When you write `get_token(scopes=["..."])` you pass none of those strings, and a keyword argument "scopes".

**Comment by Neeraj-Sr** [comment]
That resolved the error - thank you!
