### ISSUE TITLE
[Storage][Perfstress] Sync upload/download performance loss of ~20% compared to T1

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#16079]
This metric varied between APIs and SDKs - the regression appears greater in Blobs (~20%) than FileShares (~10%).
Download speed for async operations in T2 is faster than sync operations in T1.

**Comment by swathipil** [comment]
Cannot repro with v2.1.0 (using T1 perf tests: LegacyUploadTest/LegacyDownloadTest) and v12.1.0 (using T2 perf tests: UploadTest/DownloadTest). Results from testing locally:

Scenario | Size | Parallel | 2.1.0 - time | 2.1.0 - ops/s | 12.1.0 - time | 12.1.0 - ops/s |
-- | -- | -- | -- | -- | -- | -- |
Upload | 600 | 4 | 1000 | ~26 | 1000 | ~51
Download | 600 | 4 | 1000 | ~54 | 1000 | ~54 

Closing for now. Can re-open if issues come in and more investigation is needed.
