### ISSUE TITLE
Emit event in a loop

### ISSUE THREAD

**Issue by blueRegen** [Azure/azure-sdk-for-python#16084]
Hi ...

We store large (200mb to 5GB) CSV files in azure blob. 

1. We download them to our container. 
2. loop through each row, extract one field which is a JSON payload
2. AVRO Byte Array Serialize it 
3. Emit the payload as an event into EventHubs
currently, we are calling it row by row.  it takes about 1 sec/ row.
Our SLA is to publish 100mb/sec.  i.e. 100,000 messages per sec.

`def process_files() :
    filenames = find_csv_filenames("./fp")
    print("\n")
    print('Total files found = ', len(filenames))
    print(filenames)
    print("\n")
    if len(filenames) > 0 :
    for f in filenames:
    start = time.time()
    print("now working on ....", f)
    with open(f) as csv_file:
            csv_reader = csv.reader(csv_file, delimiter=',')
            line_count = 0
            #csv_reader can contain upto 50 million rows
            for row in csv_reader:
                if line_count == 0:
                    line_count += 1
                    send_msg = "Line # is " + str(line_count) + " And Line value is : " + row[0]
                    print(send_msg)
                    #send to event hub
                    emit_msg(send_msg)
                    line_count += 1
            print("")
            print(f'Processed {line_count:,} lines.')
            end = time.time()
            print(f'Completed processing in {round(end-start)} seconds.')
            print("______________________________________________________")
            print("\n")

def emit_msg(emit_string):
    client = EventHubProducerClient.from_connection_string(eh_cs, eventhub_name=eh_name)
    event_data_batch = client.create_batch()
    event_data_batch.add(EventData(emit_string))
    with client:
        client.send_batch(event_data_batch)`

********************************************************************************************************************

We tried to vectorize, see below code. Still takes the same time.

def process_file(filename) :
    start = time.time()
    print(f"working on .... {filename} \n")
    df = dd.read_csv(filename, usecols=[6])
    print(df.head(4))      
    print("")
    print(f'Processed {df.shape[0].compute(scheduler="processes"):,} lines.\n')
    df[df.columns[0]].apply(**emit_msg**, meta=('Order ID', 'int') ).compute(scheduler="processes")
    end = time.time()
    print(f'Completed processing in {round(end-start)} seconds.\n')
    print("______________________________________________________")
    print("\n")

Our immediate bottleneck is in publishing to event hub. This currently taking 1 sec/message emit.
Our SLA is to publish 100mb/sec.  i.e. 100,000 messages per sec.
Any help is greatly appreciated.

thanks as always!

**Comment by blueRegen** [comment]
Hi ..

What does it mean if it says "added to February 2021 milestone". ?

**Comment by yunhaoling** [comment]
hey @blueRegen ,

You could use the `EventDataBatch` object to send a batch of multiple events in one time instead of one by one. It should be able to improve the sending performance.
Use `EventDataBatch.add` method to keep adding single events into a batch until reaching the limited size.

You could check the sample code here and adapt to your work flow:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/sync_samples/send_stream.py

```python
with producer:
    event_data_batch = producer.create_batch()
    for i in range(to_send_message_cnt):
        event_data = EventData('D' * bytes_per_message)
        try:
            event_data_batch.add(event_data)
        except ValueError:
            producer.send_batch(event_data_batch)
            event_data_batch = producer.create_batch()
            event_data_batch.add(event_data)
    if len(event_data_batch) > 0:
        producer.send_batch(event_data_batch)
```

apart from the sending in batch, you could also create multiple `EventHubProducerClient` to send events.

-------

"added to February 2021 milestone" is part of the way our team tracks the work item, sorry about making you confused :P

**Comment by blueRegen** [comment]
Hi yunhaoling,

I tried your recommendation. It threw an error. -  
line 244, in send_batch
    cast(EventHubProducer, self._producers[partition_id]).send( KeyError: 'all-partitions'

and it duplicating the same message multiple times.

![image](https://user-images.githubusercontent.com/22227161/104385355-19bbd300-5501-11eb-856c-1f84a26077a7.png)

I am trying to debug to see If I am doing anything wrong.

thanks for your help !!!.

**Comment by yunhaoling** [comment]
hey @blueRegen, 

I read your code again and find that a new `EventHubProcucerClient` instance is created in the `emit_msg` method when called.
```python
def emit_msg(emit_string):
client = EventHubProducerClient.from_connection_string(eh_cs, eventhub_name=eh_name)
event_data_batch = client.create_batch()
event_data_batch.add(EventData(emit_string))
with client:
client.send_batch(event_data_batch)`
```

which means each time you will open a new connection to the service and send the event and then close the connection -- it will be relatively slow. It is recommended to reuse the client.

```
def emit_msg(client, event_data_batch):
    client.send_batch(event_data_batch)

client = EventHubProducerClient.from_connection_string(eh_cs, eventhub_name=eh_name)
with client:
    # emit_msg stuff
```
