### ISSUE TITLE
[Event Hubs] Update docs/README

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#16094]
* In the [Event Hubs README](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/README.md), under section `Create client using the azure-identity library`, add the azure-identity installation step: `pip install azure-identity`
> similar to the [form recognizer README AAD section](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/formrecognizer/azure-ai-formrecognizer#create-the-client-with-an-azure-active-directory-credential)

**Comment by yunhaoling** [comment]
we also need to mention async transport support (aiohttp) if people want to use azure-identity in async world, could just be a short sentence.
