### ISSUE TITLE
file.append_data throws Typeerror "element indices must be integers"

### ISSUE THREAD

**Issue by sfoxover** [Azure/azure-sdk-for-python#16109]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.2.0
- **Operating System**: Ubunut 20.04
- **Python Version**: 3.8.5

**Describe the bug**
I am unable to get even a simple Python example to create a file or directory. 

**To Reproduce**
file_system = "testfs"
file = DataLakeFileClient.from_connection_string(url_with_secret, file_system_name=file_system, file_path="cities.txt")
data = b"abc"
file.append_data(data, 0)
file.flush_data(len(data))

**Expected behavior**
File gets created

**Screenshots**

**Additional context**
file.append_data call throws
Exception has occurred: TypeError
element indices must be integers

**Comment by tasherif-msft** [comment]
Hi @sfoxover, I will try to reproduce this and get back to you!
Thank you.

**Comment by tasherif-msft** [comment]
Hi @sfoxover, I was unable to repro this. Which blob version are you running?
