### ISSUE TITLE
 The resource type 'Query' could not be found in the namespace 'Microsoft.CostManagement' for api version '2020-06-01'

### ISSUE THREAD

**Issue by batrixo** [Azure/azure-sdk-for-python#16102]
- **Package Name**: azure-mgmt-costmanagement
- **Package Version**: 1.0.0b1
- **Operating System**: WSL Ubuntu 18.04
- **Python Version**: 3.6.9

**Describe the bug**
Getting the following error :
`azure.core.exceptions.ResourceNotFoundError: (InvalidResourceType) The resource type 'Query' could not be found in the namespace 'Microsoft.CostManagement' for api version '2020-06-01'. The supported api-versions are '2018-05-31,2018-08-31,2018-08-01-preview,2018-10-01-preview,2018-12-01-preview,2019-01-01,2019-03-01-preview,2019-04-01-preview,2019-05-01-preview,2019-10-01,2019-11-01'.`

**To Reproduce**
1. pip3 install azure-mgmt-costmanagement==1.0.0b1
2. call query.usage method
```python 
client = CostManagementClient(credential, "https://management.azure.com")
client.query.usage(scope=sub_id,parameters=parameters) 
```

**Expected behavior**
Query should work and produce data

**Additional context**
API version seems hardcoded here :
https://github.com/Azure/azure-sdk-for-python/blob/739b24a25158a471159bae887ab8f6907f347727/sdk/costmanagement/azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/_operations.py#L65
I downloaded the sources, and changed the `api_version = "2020-06-01"` value to `"2019-11-01"`. It solves my issue locally.

**Comment by 00Kai0** [comment]
Hi @batrixo, it's not an issue.
It seems like you used wrong `scope`. This parameter `scope` is not sub_id.
It should be `'/subscriptions/{subscriptionId}/` or `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}`

more detail at:  https://docs.microsoft.com/en-us/rest/api/cost-management/query/usage#request-body

**Comment by batrixo** [comment]
Hi @00Kai0 , thanks a lot for your feedback,

The code snippet is not complete, but my `sub_id` variable contains a scope `/subscriptions/{subscriptionId}/`

Please find below more code context :

```python
[...]
sub_id='/subscriptions/{subscriptionId}/'

client = CostManagementClient(credential, "https://management.azure.com")

agg = QueryAggregation(name='Cost', function='Sum')
aggdict = { "TotalCost": agg }
dataset=QueryDataset(granularity='Accumulated',grouping=None, aggregation=aggdict, filter=None)
parameters=QueryDefinition(type="ActualCost",timeframe="MonthToDate", time_period=None, dataset=dataset)

client.query.usage(scope=sub_id,parameters=parameters) 

[...]
```

I get my code working with the azure-mgmt-costmanagement module in version 1.0.0b1 downloaded locally with manually edited API version to "2019-11-01".

But I get the error using the official version.

**Comment by 00Kai0** [comment]
@batrixo , I got this issue. It seem like this api version has not been published. And it is just a preview package.
I suggest you use the stable version first and wait this new version GA
![image](https://user-images.githubusercontent.com/26342317/105658940-8de37700-5f02-11eb-9bb5-84e14d863a49.png)

**Comment by timoklimmer** [comment]
@00Kai0 I have installed version 1.0.0 from 2021-02-04 (which looks like a GA version) and ran into the same issues unfortunately.

**Comment by kelnerrr** [comment]
Hi, what's the status of this issue? Any chance it's going to be fixed soon?

**Comment by StefanSchoof** [comment]
I run today into this issue. The documentation does not mentions a version 2020-06-01 for query: https://docs.microsoft.com/en-us/rest/api/cost-management/query
Only for exports the version 2020-06-01 exists: https://docs.microsoft.com/en-us/rest/api/cost-management/exports

**Comment by StefanSchoof** [comment]
Since I found no way to set the api version from outside I did some hacky things:
```python
"""A ugly hack to get a workaround for https://github.com/Azure/azure-sdk-for-python/issues/16102
"""
from azure.mgmt.costmanagement.operations import QueryOperations
from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    map_error,
)


class FixedQueryOperations(QueryOperations):
    def __init__(self, client):
        self._client = client._client
        self._serialize = client._serialize
        self._deserialize = client._deserialize
        self._config = client._config

    # took from https://github.com/Azure/azure-sdk-for-python/blob/739b24a25158a471159bae887ab8f6907f347727/sdk/costmanagement/azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/_query_operations.py#L47
    def usage(
        self,
        scope,  # type: str
        parameters,  # type: "_models.QueryDefinition"
        **kwargs  # type: Any
    ):
        # type: (...) -> "_models.QueryResult"
        """Query the usage data for scope defined.
        :param scope: The scope associated with query and export operations. This includes
            '/subscriptions/{subscriptionId}/' for subscription scope,
            '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}' for resourceGroup scope,
            '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}' for Billing Account scope and
            '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/departments/{departmentId}'
            for Department scope,
            '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/enrollmentAccounts/{enrollmentAccountId}'
            for EnrollmentAccount scope,
            '/providers/Microsoft.Management/managementGroups/{managementGroupId} for Management Group
            scope,
            '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/billingProfiles/{billingProfileId}'
            for billingProfile scope,
            '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/billingProfiles/{billingProfileId}/invoiceSections/{invoiceSectionId}'
            for invoiceSection scope, and
            '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/customers/{customerId}'
            specific for partners.
        :type scope: str
        :param parameters: Parameters supplied to the CreateOrUpdate Query Config operation.
        :type parameters: ~azure.mgmt.costmanagement.models.QueryDefinition
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: QueryResult, or the result of cls(response)
        :rtype: ~azure.mgmt.costmanagement.models.QueryResult
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop("cls", None)  # type: ClsType["_models.QueryResult"]
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
        }
        error_map.update(kwargs.pop("error_map", {}))
        api_version = "2019-11-01"
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.usage.metadata["url"]  # type: ignore
        path_format_arguments = {
            "scope": self._serialize.url("scope", scope, "str", skip_quote=True),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters["api-version"] = self._serialize.query(
            "api_version", api_version, "str"
        )

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters["Content-Type"] = self._serialize.header(
            "content_type", content_type, "str"
        )
        header_parameters["Accept"] = self._serialize.header("accept", accept, "str")

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(parameters, "QueryDefinition")
        body_content_kwargs["content"] = body_content
        request = self._client.post(
            url, query_parameters, header_parameters, **body_content_kwargs
        )
        pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(
                status_code=response.status_code, response=response, error_map=error_map
            )
            error = self._deserialize(_models.ErrorResponse, response)
            raise HttpResponseError(
                response=response, model=error, error_format=ARMErrorFormat
            )

        deserialized = self._deserialize("QueryResult", pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized

    usage.metadata = {"url": "/{scope}/providers/Microsoft.CostManagement/query"}  # type: ignore

```

**Comment by nikhilkhanna** [comment]
I'm running into this same issue. Is there a non-hacky way to get this to work?

**Comment by msyyc** [comment]
similar issue : https://github.com/Azure/azure-sdk-for-python/issues/18957

**Comment by jazelenk** [comment]
This issue is not the same as #18957. This issue is about the default API version being wrong. #18957 is about CostManagementClient ignoring the api_version kwarg.

**Comment by jazelenk** [comment]
I suspect that this is related to https://github.com/Azure/azure-rest-api-specs/issues/14572

**Comment by lmazuel** [comment]
Re-opening, since #18957 is not the same issue

**Comment by msyyc** [comment]
(1) 'azure-mgmt-costmanagement' is single-api package. Its api version is hardcoded and can't be changed anyway.
(2) The problem is a service problem. They merge swagger of '2020-06-01'(https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2020-06-01) into main repo. However, it seems that '2020-06-01' is not supported until now.

**Comment by msyyc** [comment]
new package for '20219-11' : https://pypi.org/project/azure-mgmt-costmanagement/2.0.0/
