### ISSUE TITLE
[ServiceBus] Transaction support

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#16138]
### Background
- investigate whether uamqp supports it or not, and how
- have meeting with js/dotnet/java folks to see what the feature looks like
  - sync with js further on the design
- define the scope we want to implement based on uamqp/java/.net
- design and implementation

### Task
- sync up with the service team/feature crew on this feature support
- design api for service bus and uamqp
- implement the transaction as per the spec in uamqp(or pyamqp)
- implement the transaction in service bus taking advantage of the amqp lib

### Concerns
- uamqp doesn't support shared connection, would it affect single entity transaction? if a transaction includes both send and receive operation, then for uamqp, then they're happening on two connections. if the transaction just happened on receiver or sender, then it might work.
- api design

links:
http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transactions-v1.0-os.html#toc
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions

**Comment by minghuaw** [comment]
Hi, I am currently in the middle of implementing the rust sdk and researching how transaction is implemented in other sdk. Is there more public resource regarding the Service Bus transactions? More specifically, how is AMQP 1.0 transaction utilized for request-response operations on the management link? 

For example, the renew-lock operation will definitely use a request-response over the management link, but the management protocol working draft doesn't really define the transaction behavior for management links.

**Comment by Waizik** [comment]
Hello is there currently a way how to achieve cross-entity transaction behavior in python before this will be done? I can see the auto-forward support task is closed but could not find any information about it in python SDK documentation.

https://github.com/Azure/azure-sdk-for-python/issues/4249
