### ISSUE TITLE
Reintroduce Pythonic syntax for ADLS Gen2

### ISSUE THREAD

**Issue by kasuteru** [Azure/azure-sdk-for-python#16158]
[azure.storage.filedatalake](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake?view=azure-python) for ADLS Gen2 feels rather unintuitive and more convoluted than the [ADLS Gen1 python SDK](https://docs.microsoft.com/en-us/python/api/azure-datalake-store/azure.datalake.store.core.azuredlfilesystem?view=azure-python).

What used to be a few simple, pythonic lines of code tends to now need complex queries or weird, unpythonic syntaxes. A few examples below:

### exists:
**Python syntax:**

    os.path.exists(path)

**[ADLS Gen1 syntax](https://docs.microsoft.com/en-us/python/api/azure-datalake-store/azure.datalake.store.core.azuredlfilesystem?view=azure-python#exists-path--invalidate-cache-true-)**

    client.exists(path)

**ADLS Gen2 workaround:**
```
def exists(fs_client, path):
    parent = PurePosixPath(path).parent

    for i in fs_client.get_paths(path=parent, recursive=False):
        if PurePosixPath(i.name) == path: return True
    return False

exists(client, path)
```

### mv:
**Python syntax:**
`shutil.move(src, dest)`

**Gen1:**
`client.mv(src, dest)`

**Gen 2:**
```
fs_client.get_file_client(src)
file_client.rename(dest)
```

I see lots of people re-implementing the intuitive, pythonic syntax from Gen1. I think this should rather be done centrally by Microsoft instead of 3rd-party-libraries.

**Comment by tasherif-msft** [comment]
Hi @kasuteru, thank you very much for all your suggestions :) as you know we're constantly working on our track 2 SDK to improve it. We recently added the exists method to our container and blob clients. I can definitely see the value in adding this for Datalake as well.
I will have a discussion regarding the `mv()` operation as we also need to maintain consistency with the SDKs in different languages. 
I will update you on both these items!

**Comment by tasherif-msft** [comment]
Hi @kasuteru, the `exists()` feature will be added to all the datalake clients and a PR is currently open. It will be shipped in the next release.
the `mv()` method however will not be added in the meantime as `rename()` is sufficient. 
Thank you!

**Comment by kasuteru** [comment]
Thanks for the feedback and adding exists!
