### ISSUE TITLE
FileSystemClient.create_directory misinterprets PurePosixPath

### ISSUE THREAD

**Issue by kasuteru** [Azure/azure-sdk-for-python#16159]
**Describe the bug**
Normal Python behavior is to interpret [pathlib](https://docs.python.org/3/library/pathlib.html).PurePosixPath as a string. [FileSystemClient.create_directory](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.filesystemclient?view=azure-python#create-directory-directory--metadata-none----kwargs-) seems to instead take the name parameter (PurePosixPath.name) and therefore always creates a top-level folder if provided a PurePosixPath. A workaround is to explicitely convert to str beforehand, but I will probably not be the last one to make that mistake, since the framework for ADLS Gen1 treated PurePosixPath as expected. 

Example: 

**To Reproduce**
```
from pathlib import PurePosixPath
mypath = PurePosixPath("toplevel/subfolder/newfolder")
my_file_system_client.create_directory(mypath)
```

**Expected behavior**
Create a directory named newfolder in "toplevel/subfolder", just like os.mkdir would.

**Actual behavior**
Creates a folder newfolder in root.

**Additional context**
I assume it treats the PurePosixPath as a DirectoryProperties object and takes the "name" argument.

**Comment by tasherif-msft** [comment]
Hi @kasuteru, thanks for opening up the issue! I will investigate it and see if we can add this suggestion to our SDK.
I will keep you posted.

**Comment by tasherif-msft** [comment]
@kasuteru The PR has been merged and will be available in the next release!
