### ISSUE TITLE
file_system_client.get_paths only retrieving first 5000 entries

### ISSUE THREAD

**Issue by GBBBAS** [Azure/azure-sdk-for-python#16169]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.2.1
- **Operating System**: linux
- **Python Version**: 3.7.9

**Describe the bug**
Since upgrading to 12.2.1, the file_system_client method get_paths appears to stop after 5000 records. Downgrading the package to 12.2.0 retrieves all records

**To Reproduce**
1. pip install azure-storage-file-datalake==12.2.1
2. Setup file_system client where there are more than 5000 directories and files
```
credential = ClientSecretCredential(directoryId, clientId, clientSecret)
service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format("https", storageAccount), credential=credential)       
file_system_client = service_client.get_file_system_client(file_system="testfilesystem")
```
3. Get paths 
```
paths = file_system_client.get_paths(path='/'), recursive=True)
get_all_paths = [path.name for path in paths]
```
4. Only 5000 records are retrieved

**Expected behavior**
All records are retrieved, as per beahaviour of version 12.2.0, not just the first 5000

**Comment by xiangyan99** [comment]
Close because it is a dup of #16168
