### ISSUE TITLE
datalakefileclient.upload_data without overwrite

### ISSUE THREAD

**Issue by kasuteru** [Azure/azure-sdk-for-python#16166]
It seems that I cannot use [upload_data](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.datalakefileclient?view=azure-python#upload-data-data--length-none--overwrite-false----kwargs-) without setting the overwrite flag to true. Maybe I am doing something wrong:

```
file1 = my_file_system_client.get_file_client("path/to/NONEXISTING_file.txt")
file1.upload_data(data) # Trying to upload to a non-existing file
# Raises: azure.core.exceptions.ResourceNotFoundError: (PathNotFound) The specified path does not exist.

file1 = my_file_system_client.get_file_client("path/to/NONEXISTING_file.txt")
file1.upload_data(data, overwrite=True) # Trying to upload to a non-existing file, with overwrite
# Works!

file1 = my_file_system_client.get_file_client("path/to/existing.txt")
file1.upload_data(data) # Trying to upload to a existing file, without overwrite
# Raises: azure.storage.filedatalake._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The condition specified using HTTP conditional header(s) is not met.'

file1 = my_file_system_client.get_file_client("path/to/existing.txt")
file1.upload_data(data, overwrite=True) # Trying to upload to a existing file, with overwrite
# Works!
 
```
If this is the case for everyone, I am questioning the use of the overwrite flag... or at least its default value of False?

**Comment by mahanoor786** [comment]
Can someone fix this issue or suggest a workaround? I am also running into same issue with overwrite Flag set to False.

**Comment by navba-MSFT** [comment]
@kasuteru Apologies for the delayed response. Please refer [this](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.datalakefileclient?view=azure-python#azure-storage-filedatalake-datalakefileclient-upload-data) article which talks about the overwrite=False being the default parameter value for the upload_data function.

Also if you would like to perform the Append operation you can refer the [append_data](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.datalakefileclient?view=azure-python#azure-storage-filedatalake-datalakefileclient-append-data) method. 

I see that this github thread is open for quite sometime now. So wanted to check if you are still looking for assistance on this issue ? Please let us know.

**Comment by HK-Zhang** [comment]
I get the same issue with overwrite Flag set to False.

azure-storage-blob==12.9.0
azure-storage-file-datalake==12.5.0

**Comment by jinlow** [comment]
Also, experiencing the exact same issue still with the `DataLakeFileClient` class.
