### ISSUE TITLE
Unable to generate local doc using Sphinx

### ISSUE THREAD

**Issue by SuperChenSSS** [Azure/azure-sdk-for-python#16184]
- **Package Name**: cosmos, Sphinx
- **Package Version**: V4
- **Operating System**: Ubuntu
- **Python Version**: 3.8.5

**Describe the bug**
I can see doc folder in the repository. I tried to use Sphinx-build tool to generate the doc containing cosmos APIs, but got errors and see the content is blank for cosmos APIs.

**To Reproduce**
That's the steps I followed:
1) cd doc/sphinx
2) sphinx-apidoc -f -e -o ref ../../sdk/cosmos/
3) make html

**Expected behavior**
Doc generated with cosmos APIs.

**Screenshots**
Got errors during make html:
![image](https://user-images.githubusercontent.com/17025439/104672376-a42b4f00-571a-11eb-86c9-612e15711a1e.png)
![image](https://user-images.githubusercontent.com/17025439/104672411-b5745b80-571a-11eb-89d2-49889f25c352.png)

Also going into the static index.html page, found azure.cosmos API is empty:
![image](https://user-images.githubusercontent.com/17025439/104672550-f53b4300-571a-11eb-98a7-159b4f8914ef.png)

**Additional context**
We would like to know:
1) If the steps are correct to generate API docs?
2) By reading errors, it seems some contents are missing from the ref folder. How should I avoid these and see actual content in the generated html page?

**Comment by southpolesteve** [comment]
@annatisch @scbedd Can you take a look at this?

**Comment by annatisch** [comment]
@scbedd - Is there a tox command that handles local docs generation?

**Comment by scbedd** [comment]
@annatisch absolutely.

@SuperChenSSS to locally generate documentation, please follow the [contributing](https://github.com/Azure/azure-sdk-for-python/blob/master/CONTRIBUTING.md#example-usage-of-the-common-azure-sdk-for-python-toxini) to install `tox` and `tox-monorepo`.  Once that's done, invoke `tox -e sphinx -c ../../eng/tox/tox.ini`from within the package directory that you want to generate documentation for!

**Comment by scbedd** [comment]
Hey @SuperChenSSS I am going to close this issue. I believe I have addressed your issues above. If you have any further questions feel free to ping me here!
