### ISSUE TITLE
A timeout in servicebus receive_queue_message returns an empty message.

### ISSUE THREAD

**Issue by szlerner** [Azure/azure-sdk-for-python#1619]
It's not clear how to differentiate between an empty message and a timeout.  I'm currently looking for "msg._queue_name == None" but that's a test that's not guaranteed to always work.

**Comment by lmazuel** [comment]
Hi @szlerner ,

Looking at the RestAPI doc, the difference between an empty message and a timeout is the HTTP status code:
https://docs.microsoft.com/en-us/rest/api/servicebus/receive-and-delete-message-destructive-read


Code | Description
-- | --
200 | Message successfully retrieved and deleted.
204 | No messages available within the specified timeout period.

We indeed don't keep that information in the message, so you don't know what was the status code of the incoming message. Do you confirm that adding this information into the Message, would help you in this situation?

Thanks,

**Comment by szlerner** [comment]
Yes!  In addition, I would hope that this is a design goal; i.e. all APIs that go through the REST interface return the code.  

I also wonder whether this should be explicit by returning both the http response code as well as the structure.  Something like 

    msg, httpStatusCode = ...

msg can be None if httpStatusCode indicates that message is not present. 

Thanks!

**Comment by lmazuel** [comment]
@szlerner that's a good point, but I'm not a huge fan of multiple return. Especially here, this would be a breaking change.
Most important is I understand what scenario I must unlock for you, whatever the way I do it :)

**Comment by designncode7** [comment]
@lmazuel, @szlerner: how was this resolved?  How can we see the (or make use of) the HTTP status codes from the Python SDK?  Can multiple returns be used to see HTTP  status codes?  Thanks.

**Comment by lmazuel** [comment]
@designncode7 The current focus is on dropping this package in favor of the AMQP implementation of ServiceBus.
FYI @annatisch

**Comment by lmazuel** [comment]
@sreeram-r86 it's out :)
https://pypi.org/project/azure-servicebus/0.50.0/

**Comment by annatisch** [comment]
Thanks @lmazuel!

@szlerner, @designncode7 

As mentioned, the new AMQP-based preview SDK for Service Bus is now released! The API has been newly designed, and you can find documentation here:
- [Overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python)
- [Reference documentation](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus?view=azure-python)

I'm going to close the issue now, as there should no longer be a concept of receiving an empty message in the new API. Please open new issues if you have any questions, feature requests, feedback or bug reports on the new SDK.

Thanks!
