### ISSUE TITLE
azure-mgmt-sql unable to set administrator_type parameter

### ISSUE THREAD

**Issue by chrisbeckett** [Azure/azure-sdk-for-python#16191]
I've just updated my libraries and I am now on azure-mgmt-sql 1.0.0. As there are some method changes in this library to what I had before, I've been updating my scripts and I cannot seem to set the "administrator_type" parameter using **sql_client.server_azure_ad_administrators.begin_create_or_update()**. I have tried all different permutations I can think of but I have not had any success.

No matter what I do, I get errors similar to the following:-

```
**File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/azure/mgmt/sql/operations/_server_azure_ad_administrators_operations.py", line 213, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/azure/mgmt/sql/operations/_server_azure_ad_administrators_operations.py", line 160, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InternalServerError) An unexpected error occured while processing the request. Tracking ID: '26605c15-12bb-4c9b-980f-7d9c58b253fd'**
```

Could you provide a brief code example of the correct format please? The docs don't seem to be correct.

**Comment by 00Kai0** [comment]
https://docs.microsoft.com/en-us/python/api/azure-mgmt-sql/azure.mgmt.sql.operations.serverazureadadministratorsoperations?view=azure-python#begin-create-or-update-resource-group-name--server-name--administrator-name--parameters----kwargs-

Is this available?

**Comment by chrisbeckett** [comment]
> https://docs.microsoft.com/en-us/python/api/azure-mgmt-sql/azure.mgmt.sql.operations.serverazureadadministratorsoperations?view=azure-python#begin-create-or-update-resource-group-name--server-name--administrator-name--parameters----kwargs-
> 
> Is this available?

Is this question for me?

**Comment by 00Kai0** [comment]
Hi @chrisbeckett , yes it is.
Have you solved this issue?
If not, can you show me your error code ?

**Comment by chrisbeckett** [comment]
`Traceback (most recent call last):
  File "sql-test.py", line 22, in <module>
    sql_client.server_azure_ad_administrators.begin_create_or_update(rg_name, server_name, admin_name, 
  File "/Users/chrisb/devops/sql-test/lib/python3.8/site-packages/azure/mgmt/sql/operations/_server_azure_ad_administrators_operations.py", line 213, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/Users/chrisb/devops/sql-test/lib/python3.8/site-packages/azure/mgmt/sql/operations/_server_azure_ad_administrators_operations.py", line 160, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InternalServerError) An unexpected error occured while processing the request. Tracking ID: 'abcf4cc7-b1b8-44ac-874e-aae08c538acc'`

**Comment by chrisbeckett** [comment]
I worked it out. The documentation is extremely unhelpful!

I added a variable for the parameter name --

`admin_name = 'activeDirectory'`

Then ran the command successfully --

```
sql_client.server_azure_ad_administrators.begin_create_or_update(group_name, server_name, admin_name, 
          ServerAzureADAdministrator(administrator_type=AdministratorType("ActiveDirectory"),login=azure_ad_admin_name, sid=azure_ad_user_sid, tenant_id=tenant))

```

**Comment by chrisbeckett** [comment]
Closing as I resolved this.
