### ISSUE TITLE
Multipart upload for Azure Block Blobs

### ISSUE THREAD

**Issue by shahdadpuri-varun** [Azure/azure-sdk-for-python#16190]
**Is your feature request related to a problem? Please describe.**
I am trying to figure out how to setup multipart upload for block-blobs. I have byte-chunks of ~1MB that I need to upload in multiple parts.

**Describe the solution you'd like**
A sample in the samples section would be really helpful.

**Describe alternatives you've considered**
AWS S3 python clients provide this option out-of-the-box. Would be great if something similar is provided by MSFT as well.

**Comment by tasherif-msft** [comment]
Hi @shahdadpuri-varun,

You can set this up by passing `max_block_size` when instantiating your client. This sets the maximum chunk size for uploading a block blob in chunks and it defaults to 4*1024*1024, or 4MB.
https://github.com/Azure/azure-sdk-for-python/blob/ab3cc345b34c3e9eff19401bc99ab9edfdd1449d/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L104

Let me know if you need any more help :)
We can include this in our samples!

**Comment by tasherif-msft** [comment]
Hi @shahdadpuri-varun, has this issue been resolved? 
Let me know.

Thank you
