### ISSUE TITLE
[Monitor] Can't update or create tags for diagnostic settings

### ISSUE THREAD

**Issue by troydai** [Azure/azure-sdk-for-python#1620]
Reference: https://github.com/Azure/azure-sdk-for-python/blob/39990b16105d89d59f646b0de67aa3d98d5e09b3/azure-mgmt-monitor/azure/mgmt/monitor/models/diagnostic_settings_resource.py#L65

**Comment by lmazuel** [comment]
Swagger issue created and linked to this one.

**Comment by troydai** [comment]
Thank you.

**Comment by asheniam** [comment]
We can confirm that DiagnosticSettingsResource is a proxy resource which Azure Resource Manager does not support tags.
