### ISSUE TITLE
[DataFactory] Trigger creation in version 1.0.0 (BadRequest)

### ISSUE THREAD

**Issue by sebaruehl** [Azure/azure-sdk-for-python#16225]
It was not possible to get the deployment of a trigger running with version `1.0.0`.

Authentication handling was adjusted according to the [migration guide](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/sphinx/python_mgmt_migration_guide.rst).
When calling `azure.mgmt.datafactory.DataFactoryManagementClient.trigger.create_or_update` an error was returned, but e.g. `azure.mgmt.datafactory.DataFactoryManagementClient.trigger.get` executes just fine.
The returned error was `400 - Bad Request`, there was no additional information provided in the error message. 

Further debugging showed the actual error message returned by the REST-API request is `Invalid value for property 'Properties'`.  

The create_or_update function was working fine in the previous versions. I suspect that a cause for this problem may lie in the content of the request body created at:
https://github.com/Azure/azure-sdk-for-python/blob/1ca37b47d156ed76922835e7097ee55396bf2fc5/sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_triggers_operations.py#L252

According to [REST-doc](https://docs.microsoft.com/en-us/rest/api/datafactory/triggers/createorupdate) a `properties` property has to be set in the request, but this is not the case here, all the other properties are passed on the top level:
In SDK:
```json
{
    "type": "ScheduleTrigger", 
     "description": "abcdef", 
     "pipelines": [], 
     "typeProperties": {}
}
```
Correct according to REST docs:
```json
{
    "properties": {
        "type": "ScheduleTrigger", 
        "description": "abcdef", 
        "pipelines": [], 
        "typeProperties": {}
    }    
}
```

Switching back to `<1.0.0` solves the problem for now.

**Comment by jnoynaert** [comment]
Also encountering this issue
