### ISSUE TITLE
on_method_request_received property not documented

### ISSUE THREAD

**Issue by boazeg** [Azure/azure-sdk-for-python#16224]
As part of the receive_method_request method documentation the following comment appears:
Deprecated since version 2.3.0: We recommend that you use the .on_method_request_received property to set a handler instead

However, there is no documentation of this property (.on_method_request_received) on this page, no link to another documentation page, no sample code to demonstrate its usage and it also does not seem to work at runtime in our custom module - we can set it OK but not receive any callback when a method is called (trying to use receive_method_request() method works well in the same module).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 178e6ad2-a925-7c36-7600-5c8160e8d81c
* Version Independent ID: 327ccd4e-78fb-f87d-9d0f-9b9ff6afc33c
* Content: [azure.iot.device.aio.IoTHubModuleClient class](https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.aio.iothubmoduleclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-iot-device/azure.iot.device.aio.IoTHubModuleClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-iot-device/azure.iot.device.aio.IoTHubModuleClient.yml)
* Product: **azure-iot**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by lmazuel** [comment]
Issue moved to [Azure/azure-iot-sdk-python #725](https://github.com/Azure/azure-iot-sdk-python/issues/725) via [**ZenHub**](https://www.zenhub.com/)
