### ISSUE TITLE
ContainerNetworkInterfaceConfiguration.container_network_interfaces field should be readonly?

### ISSUE THREAD

**Issue by jeking3** [Azure/azure-sdk-for-python#16227]
The field `container_network_interfaces` is something only set by the server, should it be a variable instead of a parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26cd54e5-fcc5-b13e-6f77-c615b3b54d5b
* Version Independent ID: fab72fce-a084-c217-f2f8-ddb47681a3fc
* Content: [azure.mgmt.network.v2020_06_01.models.ContainerNetworkInterfaceConfiguration class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_06_01.models.containernetworkinterfaceconfiguration?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-network/azure.mgmt.network.v2020_06_01.models.ContainerNetworkInterfaceConfiguration.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-network/azure.mgmt.network.v2020_06_01.models.ContainerNetworkInterfaceConfiguration.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by SaurabhSharma-MSFT** [comment]
@jeking3 Following up to know if your issue is resolved.
