### ISSUE TITLE
msg.renew_lock() does not update the  broker_properties['LockedUntilUtc']

### ISSUE THREAD

**Issue by oak-tree** [Azure/azure-sdk-for-python#1623]
# Details: 

`Message` can be lock. This lock has `timeout`. The timeout can be found at `msg.broker_properties['LockedUntilUtc']`. But when one calls `renew_lock()` This field does not get an update 

## Possible solution: 

@lmazuel suggested to have `when_expire` function. On default it returns `LockedUntilUtc` but on successful `renew_lock` call it returns an update clock field.  

More info can be found at 
https://github.com/Azure/azure-sdk-for-python/pull/742

**Comment by lmazuel** [comment]
Thanks for creating this issue :)

**Comment by clemensv** [comment]
The field is not updated because the message is not being redelivered. The properties are reflective of what the broker set when the message was delivered and has no interaction with the renew operation.

**Comment by oak-tree** [comment]
@clemensv 
Hey, yes this is true.  @lmazuelz even mention this at https://github.com/Azure/azure-sdk-for-python/pull/742

But while this is the case what is the best way to update the `lockduration` when there is a need to renew a message lock?

thanks

**Comment by clemensv** [comment]
The renew operation extends the lock by the queue's/subscription's default lock duration from the instant you call it on onwards. That's simple datetime math.

**Comment by oak-tree** [comment]
@clemensv thanks for the info. How to get via python the `default lock duration`?

**Comment by clemensv** [comment]
You don't need to get it. The system knows it. It's a property of the queue itself and you don't pass a parameter.

**Comment by oak-tree** [comment]
Hey, I'm not sure I'm following:
I'm currently having heavy task while reading a message from a `subscription`. This task split to several sub tasks. Therefor, for before each sub task there is a verification of the lock time of the message i.e 

```
msg_locked_until = dateutil.parser.parse(msg.broker_properties['LockedUntilUtc'])
if (datetime.now(utc) + timedelta(0, lock_buff_seconds)) > msg_locked_until:
    logger.info("Renewing message lock")
    try:
        msg.renew_lock()
        logger.info("Done.")
    except Exception as e:
        logger.error("Failed renewing the message lock.")
        logger.error(e.message)
```

But when there first `renew_lock()` is firing the message lock is begin extending by the `default lock duration`.  As renew_lock does not update any field, after the first time the above condition is always true.

My questions: 
1. What is the proper way of `renew a lock` in python?
1. If the above is ok, then what is the way of calculating the `new lock time` in order not to renew it every time.

Thanks again

**Comment by clemensv** [comment]
1. as you do it
2. it's ok to renew the lock before the next step if there's any risk that the lock will expire

The renewed lock time is the current time plus the queue's lock duration. You can get that with the python SDK from the object returned by [get_queue()](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/azure/servicebus/servicebusservice.py#L289) as [lock_duration](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/azure/servicebus/_serialization.py#L238)

**Comment by oak-tree** [comment]
@clemensv thanks for answering :)

**Comment by lmazuel** [comment]
Thanks @clemensv !
