### ISSUE TITLE
LogicManagementClient params do not correspond the reference.

### ISSUE THREAD

**Issue by andreif** [Azure/azure-sdk-for-python#16235]
The code requires `credential` parameter of `TokenCredential` type:

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/logic/azure-mgmt-logic/azure/mgmt/logic/_logic_management_client.py#L118

while the reference mentions `credentials` of different type (`AdalAuthentication`):

https://docs.microsoft.com/en-us/python/api/azure-mgmt-logic/azure.mgmt.logic.logicmanagementclient?view=azure-python

I have updated to the latest version of the library and it broke client initialization. How am I supposed to use it now?

```py
logic_client = azure.common.client_factory.get_client_from_json_dict(
    client_class=azure.mgmt.logic.LogicManagementClient,
    config_dict=...,
)
```

**Comment by andreif** [comment]
This seems to work
```py
logic_client = azure.mgmt.logic.LogicManagementClient(
    credential=azure.identity.ClientSecretCredential(
        tenant_id=config_dict["tenantId"],
        client_id=config_dict["clientId"],
        client_secret=config_dict["clientSecret"],
    ),
    subscription_id=config_dict["subscriptionId"],
    base_url=config_dict["resourceManagerEndpointUrl"],
    tenant_id=config_dict["tenantId"],
)
```

**Comment by SatishBoddu-MSFT** [comment]
Hello @andreif Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.
