### ISSUE TITLE
[apiview] APIView is unable to generate for a whole namespace in EventGrid

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#16240]
APIView is unable to generate for `azure.eventgrid.models` namespace.

Here's the folder structure
```
azure\
    aio\
        client_async.py
    models\
        __init__.py #see below for the contents of this
    __init__.py
    client.py
```

Here's the __init__.py in the models\ folder: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/azure/eventgrid/models/__init__.py

Here's the API view https://apiview.dev/Assemblies/Review/82ef428bec1e4ab2899a99411d066d44/633e8014eac444059c102d8caecad45c?doc=False

**Comment by lmazuel** [comment]
Feels deprecated and not the right repo. @rakshith91 if this is still a problem, please create an issue to https://github.com/Azure/azure-sdk-tools and assign it to @tjprescott
