### ISSUE TITLE
When retrieving blobs : DeserializationError: Unable to deserialize to object: type, KeyError: 'name'

### ISSUE THREAD

**Issue by tappoz** [Azure/azure-sdk-for-python#16250]
- **Package Name**: `azure-storage-blob`
- **Package Version**: 12.7.0
- **Operating System**: Linux Ubuntu 20.04.1 LTS
- **Python Version**: 3.6

**Describe the bug**

When using `msrest-0.6.10` I am not able to retrieve blobs because an exception is being thrown by the library: `DeserializationError: Unable to deserialize to object: type, KeyError: 'name'`.

**To Reproduce**

Using `ipython`:

```
In [1]: from azure.storage.blob import BlobServiceClient, BlobClient                                                                                       

In [2]: ASA_CONNECTION_STRING = "DefaultEndpointsProtocol=https;BlobEndpoint=https://<<SOMETHING>>.blob.core.windows.net/;AccountName=<<SOMETHING>>;AccountKey=<<SOMETHING_ELSE>>"                                              

In [3]: ASA_CONTAINER_NAME = "<<SOME_NAME>>"                                                                                            

In [4]: blob = BlobServiceClient.from_connection_string(ASA_CONNECTION_STRING)                                                                             

In [5]: container = blob.get_container_client(ASA_CONTAINER_NAME)                                                                                          

In [6]: stuff = container.list_blobs()

In [7]: thing = stuff.next()
```

**Expected behavior**

That `thing` above should contain the details of the blob.

**Additional context**

For some reason if I uninstall all the pip packages containing the string "azure" with this:

```
for i in `pip list | awk '/azure/ {print $1}'`; do pip uninstall -y $i ; done
```

Then I remove this `msrest` package (version `msrest-0.6.10`) with:

```
pip uninstall msrest
```

Then I install again this package `azure-storage-blob` with:

```
pip install azure-storage-blob --upgrade
```

Then the code snippet above to retrieve a blob works.

The interesting fact is that this `msrest` is re-installed with the version `msrest-0.6.19`.
There must be something wrong with `msrest-0.6.10` that is not captured by the requirements for `azure-storage-blob`.

**Comment by tasherif-msft** [comment]
Hi @tappoz,

We recently migrated our generated code layer to use a new version (of autorest). It appears this problem is due to an outdated minimum dependency!
msrest minimum dependency has now been updated to 0.6.18 to use Blobs/Fileshares/Queues/Datalake.
I will put out a PR to update this dependency :)
Thanks for catching this

**Comment by tasherif-msft** [comment]
I have created a PR here https://github.com/Azure/azure-sdk-for-python/pull/16267. Let me know if anything else is needed :)

**Comment by tasherif-msft** [comment]
@tappoz the patch has been released.

**Comment by troykirin** [comment]
I'm running into a conflict after running both

`pip install msrest==0.6.18`
`pip install msrest==0.6.21`

i'm getting
`Installing collected packages: msrest
  Attempting uninstall: msrest
    Found existing installation: msrest 0.6.10
    Uninstalling msrest-0.6.10:
      Successfully uninstalled msrest-0.6.10
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botframework-connector 4.14.0 requires msrest==0.6.10, but you have msrest 0.6.21 which is incompatible.
botbuilder-schema 4.14.0 requires msrest==0.6.10, but you have msrest 0.6.21 which is incompatible.
Successfully installed msrest-0.6.21`
