### ISSUE TITLE
Azure Monitor Exporter API changes based on arch board review

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-python#16254]
Based on the [arch board feedback](https://github.com/Azure/azure-sdk/issues/1975) for Azure Monitor exporter, update the APIs to support the following:

- [x] Include an option to configure the service API version when constructing the exporter instance
- [x] Provide a convenience method on the exporter to get the `endpoint`
- [x] Consider adding APIs for configuring `endpoint` and `instrumentationKey` separately. Continue to support `connectionString` which contains both endpoint and instrumentationKey.

**Comment by rakshith91** [comment]
Agree with the changes - @lzchen  let me know if you need any help on this one
