### ISSUE TITLE
azure.mgmt.web.models.SkuDescription: required field metadata and documentation are missing

### ISSUE THREAD

**Issue by jeking3** [Azure/azure-sdk-for-python#16251]
When I omit `name` from the call to begin_create_or_update on an AppServicePlan, I get an error of InvalidRequestContent indicating the property is required.  None of the other properties appear to be required - if the name is a valid "size" then the server accepts the content.

The metadata for `SkuDescription` has no `_validation` so none of the fields appear to be marked as required.

When I provide the name by itself, things work:

Request:
```
(Pdb) pp uut.proposed.sku.as_dict()
{'name': 'B1'}
```
Response:
```
(Pdb) pp uut.real.sku.as_dict()
{'capacity': 1, 'family': 'B', 'name': 'B1', 'size': 'B1', 'tier': 'Basic'}
```
Additionally, it looks like the fields other than name are actually readonly, but not marked as such, for example see the request below which should be confusing to the server, but is not because it ignores size and tier in the request:

Request:
```
(Pdb) pp uut.proposed.sku.as_dict()
{'name': 'B1', 'size': 'F1', 'tier': 'Premium'}
```
Response:
```
(Pdb) pp uut.real.sku.as_dict()
{'capacity': 1, 'family': 'B', 'name': 'B1', 'size': 'B1', 'tier': 'Basic'}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 714d22c2-e0bf-0514-0c79-2df33620ac31
* Version Independent ID: fc440021-8305-be7c-0537-e315041e599a
* Content: [azure.mgmt.web.v2019_08_01.models.SkuDescription class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2019_08_01.models.skudescription?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-web/azure.mgmt.web.v2019_08_01.models.SkuDescription.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-web/azure.mgmt.web.v2019_08_01.models.SkuDescription.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by 00Kai0** [comment]
Same issue: https://github.com/Azure-Samples/azure-samples-python-management/issues/59
