### ISSUE TITLE
No code samples for `azure-mgmt-datamigration` Python SDK

### ISSUE THREAD

**Issue by myhau** [Azure/azure-sdk-for-python#16257]
I could not found any code samples for `azure-mgmt-datamigration` Python SDK module. 

Links on [azuresdkdocs.blob.core.windows.net](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-datamigration/4.1.0/index.html) and in [GitHub repo](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/datamigration/azure-mgmt-datamigration) redirect to generic pages that do not contain any information about Data Migration SDK whatsoever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c44dbc-5af2-cdd8-a5a1-fa7cc6269baa
* Version Independent ID: 1101b29b-a21b-2ebb-c279-315d9796a43a
* Content: [Microsoft Azure SDK for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/mgmt-datamigration-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/mgmt-datamigration-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/mgmt-datamigration-readme.md)
* Service: **datamigration**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by 00Kai0** [comment]
Hi @myhau ,we will add later.
Before that, please refer to the restapi doc: https://docs.microsoft.com/en-us/rest/api/datamigration/services/createorupdate#examples
