### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ujwalkasth** [Azure/azure-sdk-for-python#16281]
Can someone please suggest what am i doing wrong and how to resolve this? @zezha-msft 
I have this output : 
Out[10]: b'\xef\xbb\xbf<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:8fe1135e-f01e-002f-2ff4-e82696000000\nTime:2021-01-12T15:06:52.6849689Z</Message><HeaderName>Content-Length</HeaderName><HeaderValue>0</HeaderValue></Error>'
Python code for the request : 
from msrestazure.azure_active_directory import AADTokenCredentials 
## Other required imports
import adal, uuid, time
 
authority_host_uri = 'https://login.microsoftonline.com' 
tenant = 'XXX'
authority_uri = authority_host_uri + '/' + tenant
resource_uri = 'https://storage.azure.com/'
client_id = 'XXX'
client_secret = 'XXX'
 
context = adal.AuthenticationContext(authority_uri, api_version=None)
mgmt_token = context.acquire_token_with_client_credentials(resource_uri, client_id, client_secret)
credentials = AADTokenCredentials(mgmt_token, client_id)
 
token = mgmt_token.get('accessToken')
 
r = requests.post('https://abc.blob.core.windows.net/?restype=service&comp=userdelegationkey', headers={'Authorization' : 'Bearer ' + token, 'x-ms-version': '2020-04-08'}) 
content=r.content
data=open("smart_flows.txt","wb")
data.write(content)
data.close()
 
 My Service Principal have the Storage Blob Data Contributor  and storage blob delegator role on the storage.

**Comment by ujwalkasth** [comment]
@tasherif-msft any suggestions?

**Comment by ujwalkasth** [comment]
@xiafu-msft can you suggest please ?

**Comment by ujwalkasth** [comment]
Can someone please help with this issue ?

**Comment by amishra-dev** [comment]
@ujwalkasth 
Hi,
Apologies for the delay, I checked the service settings for your account and everything seems to be setup fine. Would you please try this again and send me the request id (like in your first message). We hold on to service logs only for so long, so I would need another repro. 
Tag me directly and i will look up the logs for your rightaway.

**Comment by yaxia** [comment]
As the error message: "RequestId:8fe1135e-f01e-002f-2ff4-e82696000000\nTime:2021-01-12T15:06:52.6849689Z**Content-Length0**'", it means you POST with a request body, but you didn't specify the content-length, which triggers the error.

Could you please add the content-length header and try again?

**Comment by ujwalkasth** [comment]
> @ujwalkasth
> Hi,
> Apologies for the delay, I checked the service settings for your account and everything seems to be setup fine. Would you please try this again and send me the request id (like in your first message). We hold on to service logs only for so long, so I would need another repro.
> Tag me directly and i will look up the logs for your rightaway.

@amishra-dev Here is the new request ID: 4314d4ee-a01e-0022-557e-04ee42000000 . Can you please verify this request ID?

**Comment by tasherif-msft** [comment]
Hi @ujwalkasth are you still getting this error thrown? could you please send an updated request ID I will make sure to look into this the day you provide it
