### ISSUE TITLE
circular import 

### ISSUE THREAD

**Issue by maralamir** [Azure/azure-sdk-for-python#16286]
Hi, 
I am trying to import "QueueServiceClient" in my python script and it gives me the following error: 

cannot import name 'QueueServiceClient' from partially initialized module 'azure.storage.queue' (most likely due to a circular import)

**Comment by tasherif-msft** [comment]
Hi @maralamir, could you please send me how your code snippet looks like?
thank you

**Comment by maralamir** [comment]
Hi @tasherif-msft , thanks for your prompt reply.

I am following this example.
https://docs.microsoft.com/en-us/azure/storage/queues/storage-python-how-to-use-queue-storage?tabs=python

Here is the code snippet:

from azure.storage.queue import (
        QueueServiceClient,
        BinaryBase64EncodePolicy,
        BinaryBase64DecodePolicy
)
import os, uuid
# Retrieve the connection string from an environment
# variable named AZURE_STORAGE_CONNECTION_STRING
connect_str = os.getenv("DefaultEndpointsProtocol=https...")
	
# Create a unique name for the queue
queue_name = "queue-" + str(uuid.uuid4())

# Instantiate a QueueClient object which will
# be used to create and manipulate the queue
print("Creating queue: " + queue_name)
queue_client = QueueClient.from_connection_string(connect_str, queue_name)

# Create the queue
queue_client.create_queue()

# Setup Base64 encoding and decoding functions
queue_client.message_encode_policy = BinaryBase64EncodePolicy()
queue_client.message_decode_policy = BinaryBase64DecodePolicy()

message = u"Hello World"
print("Adding message: " + message)
queue_client.send_message(message)

# Peek at the first message
messages = queue_client.peek_messages()

for peeked_message in messages:
    print("Peeked message: " + peeked_message.content)

**Comment by maralamir** [comment]
@tasherif-msft and here is the exact error.

cannot import name 'QueueServiceClient' from partially initialized module 'azure.storage.queue' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/azure/storage/queue/__init__.py)

**Comment by tasherif-msft** [comment]
Hi @maralamir, looking at your code you seem to be trying to create a QueueClient but you're importing QueueServiceClient, so try fixing that import. Though this would've given you a different error. Let me know if this fixes it.
Also which Queues package version are you using? (`pip show azure-storage-queue`)

**Comment by maralamir** [comment]
Hi @tasherif-msft ,
Yes, I did try both libraries as I realized the methods I wanted are in one or the other depending on the version. I just tried it with QueueClient again and I got the same error. 

ImportError: cannot import name 'QueueClient' from partially initialized module 'azure.storage.queue' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/azure/storage/queue/__init__.py)

I am using Version: 2.1.0.

Thank you again for your prompt response.

**Comment by tasherif-msft** [comment]
It appears you're still using track 1 of the Queues package which has been deprecated for some time. I highly recommend upgrading it, the newest version is 12.1.5 (`pip install azure-storage-queue --upgrade`)
At this point I'm hoping the upgrade would fix it, as this issue definitely does not exist in our current track 2 SDK. Let me know if this works

**Comment by maralamir** [comment]
It still not fixed. Is there any dependency to the python version? I am using version 3.7.4

**Comment by maralamir** [comment]
@tasherif-msft Ok, I just realized that the error is shown only when I am trying to run the script in Conda Environment. If I deactivate the conda environment, I can run it. As most of my python packages are installed in conda env, it would be wonderful to have a solution for this. Otherwise, I will find a workaround to install my other dependencies in non conda env.

**Comment by tasherif-msft** [comment]
Hi @maralamir, I'm glad that works. As for the conda env, the SDK should work just fine if using conda. Virtual envs should not causing any breakages. You mentioned that you are using Python 3.7.4, is that your global Python version (in conda env and outside), or is it specific to your conda env?
I noticed in the exception thrown that it was checking against Python3.8 path that's not part of your conda env....

**Comment by maralamir** [comment]
@tasherif-msft very good point. My global python is Python 3.8.3, and in conda version is Python 3.7.4.

**Comment by tasherif-msft** [comment]
@maralamir I see, yea I'm pretty sure the exception is thrown because of this path conflict. If you can maybe try to ensure that the azure-storage-queue package is installed and called properly within the conda env (rather than calling the global azure-storage-queue) that would most likely fix it within your env :) 
In the meantime I will close this issue. Let me know if this resolves it!

**Comment by OscarSantos98** [comment]
Same problem persist, I was following [docs](https://docs.microsoft.com/en-us/azure/storage/queues/storage-python-how-to-use-queue-storage?tabs=python) using virtualenv with Python 3.8.3 and installing packages with 

```
pip install azure-storage-queue
```

and running 

```
pip show azure-storage-queue
```

display the following info

Name: azure-storage-queue
Version: 12.1.6
Summary: Microsoft Azure Azure Queue Storage Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-queue
Author: Microsoft Corporation
Author-email: ascl@microsoft.com
License: MIT License
Location: c:\users\betaz\documents\python\azure queue\queueenv\lib\site-packages
Requires: msrest, cryptography, azure-core
Required-by:

Script shows ImportError with 

```
from azure.storage.queue import (
        QueueClient,
        BinaryBase64EncodePolicy,
        BinaryBase64DecodePolicy
)
```

The error message:

ImportError: cannot import name 'QueueClient' from partially initialized module 'azure.storage.queue' (most likely due to a circular import) (C:\Users\betaz\Documents\Python\Azure Queue\queueenv\lib\site-packages\azure\storage\queue\__init__.py)

Then I tried to install packages in (base) anaconda and run script again but the error persist.

ImportError: cannot import name 'QueueClient' from partially initialized module 'azure.storage.queue' (most likely due to a circular import) (C:\Users\betaz\anaconda3\lib\site-packages\azure\storage\queue\__init__.py)

**Comment by deepak6422** [comment]
> Same problem persist, I was following [docs](https://docs.microsoft.com/en-us/azure/storage/queues/storage-python-how-to-use-queue-storage?tabs=python) using virtualenv with Python 3.8.3 and installing packages with
> 
> ```
> pip install azure-storage-queue
> ```
> 
> and running
> 
> ```
> pip show azure-storage-queue
> ```
> 
> display the following info
> 
> Name: azure-storage-queue Version: 12.1.6 Summary: Microsoft Azure Azure Queue Storage Client Library for Python Home-page: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-queue Author: Microsoft Corporation Author-email: [ascl@microsoft.com](mailto:ascl@microsoft.com) License: MIT License Location: c:\users\betaz\documents\python\azure queue\queueenv\lib\site-packages Requires: msrest, cryptography, azure-core Required-by:
> 
> Script shows ImportError with
> 
> ```
> from azure.storage.queue import (
>         QueueClient,
>         BinaryBase64EncodePolicy,
>         BinaryBase64DecodePolicy
> )
> ```
> 
> The error message:
> 
> ImportError: cannot import name 'QueueClient' from partially initialized module 'azure.storage.queue' (most likely due to a circular import) (C:\Users\betaz\Documents\Python\Azure Queue\queueenv\lib\site-packages\azure\storage\queue__init__.py)
> 
> Then I tried to install packages in (base) anaconda and run script again but the error persist.
> 
> ImportError: cannot import name 'QueueClient' from partially initialized module 'azure.storage.queue' (most likely due to a circular import) (C:\Users\betaz\anaconda3\lib\site-packages\azure\storage\queue__init__.py)

@tasherif-msft I am also getting the same error. I am using azure storage queue inside a virtual environment.

**Comment by deepak6422** [comment]
@OscarSantos98 Was you able to resolve the error you mentioned?

**Comment by OscarSantos98** [comment]
No, I end up using the NodeJS SDK as Python was not working. But, maybe they have updated the Python SDK. Try with the newest version.

**Comment by deepak6422** [comment]
> @deepak6422 No, I end up using the NodeJS SDK as Python was not working. But, maybe they have updated the Python SDK. Try with the newest version.

I see. I am using the latest version SDK still same issue
