### ISSUE TITLE
ContainerClient retry options broken?

### ISSUE THREAD

**Issue by shahdadpuri-varun** [Azure/azure-sdk-for-python#16291]
https://github.com/Azure/azure-sdk-for-python/blob/ffe6a56bff6cd01493e47d3e50957c748a7ce632/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L169

No matter how I set the retry options, they are not being used by the below code - 
```
        blob_container_client = ContainerClient(account_url=self.url,
                                                credential=self.sas_token,
                                                container_name=self.container_name,
                                                retry_total=2,
                                                retry_connect=2,
                                                retry_read=2,
                                                retry_status=2,
                                                retry_mode=RetryMode.Fixed,
                                                retry_backoff_factor=0.8
                                                )
```

Is it because the sdk code in `ContainerClient --> __init__` is NOT passing the `**kwargs` to `AzureBlobStorage` ?

**Comment by tasherif-msft** [comment]
Hi @shahdadpuri-varun, which blob operation are you trying to perform where these are failing?

**Comment by shahdadpuri-varun** [comment]
Thanks for the quick response @tadam-msft, I did dig deeper and saw that piece of code.
I am trying to just call `blob_container_client.get_container_properties()` but in case the where the storage account-name is invalid, it still retries 3 times before throwing a `ServiceRequestError` error.

```
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://hddhjd.blob.core.windows.net/test-container-azurite?restype=REDACTED&se=REDACTED&sp=REDACTED&sv=REDACTED&ss=REDACTED&srt=REDACTED&sig=REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:Request method: 'GET'
INFO:azure.core.pipeline.policies.http_logging_policy:Request headers:
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-version': 'REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:    'Accept': 'application/xml'
INFO:azure.core.pipeline.policies.http_logging_policy:    'User-Agent': 'azsdk-python-storage-blob/12.7.1 Python/3.8.6 (macOS-10.15.7-x86_64-i386-64bit)'
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-date': 'REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-client-request-id': '33a3be7e-5c52-11eb-867a-acde48001122'
INFO:azure.core.pipeline.policies.http_logging_policy:No body was attached to the request
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://hddhjd.blob.core.windows.net/test-container-azurite?restype=REDACTED&se=REDACTED&sp=REDACTED&sv=REDACTED&ss=REDACTED&srt=REDACTED&sig=REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:Request method: 'GET'
INFO:azure.core.pipeline.policies.http_logging_policy:Request headers:
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-version': 'REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:    'Accept': 'application/xml'
INFO:azure.core.pipeline.policies.http_logging_policy:    'User-Agent': 'azsdk-python-storage-blob/12.7.1 Python/3.8.6 (macOS-10.15.7-x86_64-i386-64bit)'
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-date': 'REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-client-request-id': '3d424ed2-5c52-11eb-867a-acde48001122'
INFO:azure.core.pipeline.policies.http_logging_policy:No body was attached to the request
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://hddhjd.blob.core.windows.net/test-container-azurite?restype=REDACTED&se=REDACTED&sp=REDACTED&sv=REDACTED&ss=REDACTED&srt=REDACTED&sig=REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:Request method: 'GET'
INFO:azure.core.pipeline.policies.http_logging_policy:Request headers:
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-version': 'REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:    'Accept': 'application/xml'
INFO:azure.core.pipeline.policies.http_logging_policy:    'User-Agent': 'azsdk-python-storage-blob/12.7.1 Python/3.8.6 (macOS-10.15.7-x86_64-i386-64bit)'
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-date': 'REDACTED'
INFO:azure.core.pipeline.policies.http_logging_policy:    'x-ms-client-request-id': '4d1fbae2-5c52-11eb-867a-acde48001122'
INFO:azure.core.pipeline.policies.http_logging_policy:No body was attached to the request
```

**Comment by tasherif-msft** [comment]
So in the case of `retry_total=2` that means a total of 3 requests are attempted.
In this case if you want to only have two requests fail then you'd set your `retry_total=1`, i.e, the initial request (fails) then retry once.
Let me know if this works. If it doesn't I will investigate deeper!
Please note that the default number of retries is 10.
Thank you :)

**Comment by shahdadpuri-varun** [comment]
Thanks a lot.. That worked. I was also able to apply the `LinearRetry(retry_total=2)` for cases where I need more than one retry count.
One last question, what is the right way to specify a _connection timeout_ and the _wait-time_ between first failed connection and first retry?

**Comment by tasherif-msft** [comment]
@shahdadpuri-varun I'm glad that worked :)
You can set the `connection_timeout` by passing it when instantiating the client just like you would when passing your `retry_total`. The connection timeout dictates the timeout length to validate a connection is established with the service through the socket. if you pass a regular `timeout` (client or per operation) this specifies the length of time the service takes for the request response roundtrip (i.e how long it takes to process the request)
Currently the connection timeout defaults to 20 seconds. You can change this value. As for how long you want to wait before retrying you can actually do this by passing `backoff=..` (in seconds) when initializing your `LinearRetry` or `ExponentialRetry` policies.
In a linear retry the backoff is constant and in an exponential retry the backoff time will exponentially grow with more timeouts.
I will proceed to close this issue. You can always open another one if you encounter another problem :)

**Comment by shahdadpuri-varun** [comment]
Thanks a lot @tasherif-msft
You have been very helpful today!! 🤘

**Comment by tasherif-msft** [comment]
My pleasure
