### ISSUE TITLE
list virtual machines

### ISSUE THREAD

**Issue by mgogoulos** [Azure/azure-sdk-for-python#163]
Does azure allow an easy way to retrieve all the virtual machines?

**Comment by mckkentmwk** [comment]
Exist some way to retrieved the publics ip of each virtual machine listed of the previous function?

**Comment by lmazuel** [comment]
Hi @mckkentmwk 
This issue was initially about ASM (classic Azure VM). This client is now in the legacy package. Are you talking about the ASM or the new ARM package in preview in 2.0.0RC?

**Comment by mckkentmwk** [comment]
I do not know exactly in which case I am, I follow this tutorial to install azure https://azure.microsoft.com/en-us/documentation/articles/python-how-to-install/ and those are the versions of the principle libraries that I am using 
azure-storage==0.32.0
azure-servicemanagement-legacy==0.20.3

**Comment by lmazuel** [comment]
As you can see in the tutorial you point, you can install ARM or ASM libraries. On the Azure Portal you should see two kind of VM: classic and current:
![image](https://cloud.githubusercontent.com/assets/1050156/16436887/95e8de36-3d56-11e6-9268-4f66cfa97e8e.png)


If you use "Virtual Machines (classic)", you need the ASM library and azure-servicemanagement-legacy. If you use "Virtual Machines" with no suffix, you need the ARM library. In this case I recommend you to test the 2.0.0 release candidate version:
http://azure-sdk-for-python.readthedocs.io/en/latest/

The response to your question will depend on the library you will need.
For new project in Azure, we highly recommend ARM.

**Comment by mckkentmwk** [comment]
I want to do the follow:

1.- Create a n(is a parameter of my script in python) virtual machines.
2.- Copy a folder containing a program in C++ to each virtual machine(each machine will run the C++ program with different parameters).
3.- Run it C++ program in each virtual machine
4.- Get the output of each machine and copy it to my script python script

I have gotten create machines with it https://azure.microsoft.com/en-us/documentation/articles/cloud-services-python-how-to-use-service-management/, but now I want to get the publics ip of each virtual machine, the copy by ssh(paramiko, is a ssh inside python) the C++ program. and run it and then copy the outputs of each machine to my script.
IMPORTANT: the python script would be done all the work.

What do you recommend?

**Comment by lmazuel** [comment]
If you don't have constraints on ASM/ARM by a previous existing codebase, I would recommend using ARM, even if the client is still in preview (preview client are not recommended for prod).
You have a sample of ARM for VirtualMachine here:
http://azure-sdk-for-python.readthedocs.io/en/latest/resourcemanagementcomputenetwork.html

Install the preview 2.0.0RC5 client:
http://azure-sdk-for-python.readthedocs.io/en/latest/index.html#installation
