### ISSUE TITLE
[EventHubs] Custom ssl certificate support when using http proxy

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#16304]
# Summary
EventHub allows connecting to the service via http proxy.
Currently we expose http proxy setting including:
```
proxy_hostname (str)
proxy_port (int)
username (str)
password (str)
```
However, there're scenarios:
- the http proxy server has its own **Server SSL certificate** -- when the client wants to build tls connection to the http proxy, a custom certificate is required for authenticating the identity of the proxy server.
- Apart from the server certificate, there is also **Client SSL certificate** which is used by the server to authenticate the identity of a client.

**We would like to provide the ability to set server/client certificate in EventHub Python SDK for authenticating the identity of the proxy server/client when connection to the service via a http proxy.**

# Scope of work
- Client accepts server SSL certificate and uses the certificate (path to the CA_BUNDLE file) in the case of http proxy usage for authenticating the identity of the proxy server when building tls connection.
  - (?) certificate ignored if there's no proxy setting
- Client accepts client SSL certificate and uses the certificate in the case of http proxy usage for authenticating the identity of the client when building tls connection.
  - (?) certificate ignored if there's no proxy setting
- The surface should align with the [azure-core](https://github.com/Azure/azure-sdk-for-python/blob/9fca61bb96e83093a767cad8755d381d95385061/sdk/core/azure-core/azure/core/configuration.py#L91-L103) on exposing the certificate settings at the top-level client

# Success Criteria
- The server ssl certificate and client certificate is supported/implemented in the underlying uamqp library
- clients accept ssl certificate and client certificate could connect to the service via http proxy which requires the certificates.

# Samples

```python
http_proxy = {
proxy_hostname (str)
proxy_port (int)
username (str)
password (str)
connection_verify: path the server certificate CA_BUNDLE file
connection_cert: path to the client side certificate CA_BUNDLE file or (key, certificate pair?)
}
```

# References
[Python request ssl cert](https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification)
[Python request client cert](https://requests.readthedocs.io/en/master/user/advanced/#client-side-certificates)

**Comment by yunhaoling** [comment]
action items:

- investigate the "verify" feature in uamqp auth and test setting the server certificate to connect to http proxy server
- investigate the client side certification in uamqp-c library
  - whether setting client side cert is supported or not

**Comment by fulii** [comment]
Hi!

I would really like this to happen.
Currently we cannot use azure service bus because our proxy server has a custom certificate.
I cannot see any workaround at the moment how to bypass this, i spent hours to figure out.
Aslo from uamqp library side there is not much information about bad certificate.
If this happens in march that is really great, until then can you provide any workaround?

**Comment by yunhaoling** [comment]
hey @fulii,

I'm sorry to tell you that the currently the underlying C networking implementation for http proxy only supports basic auth (username and password) and we could do nothing until that the support is being added into the C library first.

I'll continue my work on adding support to the C library this month, but I can't guarantee you the timeline.

**Comment by yunhaoling** [comment]
prototype is available here: https://github.com/yunhaoling/uamqp-tls-proxy-prototype

**Comment by yunhaoling** [comment]
hey @fulii , apologize for not getting back to you sooner.

I have implemented the feature in the uamqp library based on my understanding.
I would like to invite you to try out the feature to see if it works for your scenario -- uamqp wheels for linux and samples for servicebus could be found here: https://github.com/yunhaoling/uamqp-tls-proxy-prototype.

your feedbacks on the API are also welcomed!

(let me know if you're working on Windows or macOS, I could build wheels for you as well)

**Comment by yunhaoling** [comment]
closing the issue as there's no active development plan for it.
besides we heard no feedback from the community.

Please create a new issue if you feel this is the feature you need, and we could discuss.
