### ISSUE TITLE
get_block_list(...): 'utf-8' codec can't decode byte 0x92 in position 5: invalid start byte

### ISSUE THREAD

**Issue by ecc256** [Azure/azure-sdk-for-python#16314]
**azure-storage-blob
12.7.1
Winserver 2016
Conda Python 3.9.0**

The code:
`block_list = blob_client.get_block_list(block_list_type='committed')`
throws
**# 'utf-8' codec can't decode byte 0x92 in position 5: invalid start byte**
for any blockblob which is weblog created by Azure App Service logging.
It works fine for any blockblob created from Python SDK, where my code makes all block_ids 'utf-8' encoded:
`block_id = f'{a}'.encode('utf-8')`

Did I do something wrong? 
Or is there a way to read blockblob block_list with block_ids NOT 'utf-8' encoded?

GetBlockList() works w/o issues with C# SDK.
It produces long list of block names like:
_AAAAAD2SEsiRhJdJhjwCnnXFI3U=
AQAAALoHi8mdLzRCucUfofA4DuU=
AgAAAAyB31Bx305PvQ/T7vtFpVg=
AwAAAA11eqSgqvBCogtQtmRIoQ0=_

**pip list**
_azure-common                           1.1.26
azure-core                             1.10.0
azure-eventhub                         5.2.0
azure-eventhub-checkpointstoreblob-aio 1.1.1
azure-identity                         1.5.0
azure-kusto-data                       1.0.3
azure-kusto-ingest                     1.0.3
azure-mgmt-core                        1.2.2
azure-mgmt-datafactory                 0.15.0
azure-mgmt-kusto                       0.10.0
azure-mgmt-resource                    15.0.0
azure-storage-blob                     12.7.1
azure-storage-queue                    12.1.4_

**Comment by tasherif-msft** [comment]
Hi @ecc256 I will investigate this issue and get back to you as soon as possible!

**Comment by xiafu-msft** [comment]
Hi @ecc256 This pr https://github.com/Azure/azure-sdk-for-python/pull/18751 should be able to fix the problem, sorry about the inconvenience!
