### ISSUE TITLE
Event hub Samples issue

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#16339]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_by_event_count.py#L42),[link2](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_by_time_interval.py#L44),[link3](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_store.py#L33),[link4](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_by_event_count_async.py#L56),[link5](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_by_time_interval_async.py#L59),[link6](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_store_async.py#L47):
![image](https://user-images.githubusercontent.com/57166602/105797582-3b21c200-5fcb-11eb-9730-4a54ee915ef1.png)

Reason:
ValueError: The eventhub name can not be None or empty.

Suggestion:
Add a comment to CONNECTION_STR  `# connection string contains EventHub name.`
Or
Add parameter `eventhub_name=EVENTHUB_NAME` , uptate to:
```
consumer_client = EventHubConsumerClient.from_connection_string(
    conn_str=CONNECTION_STR,
    consumer_group='$Default',
    checkpoint_store=checkpoint_store,  # For load-balancing and checkpoint. Leave None for no load-balancing.
    eventhub_name=EVENTHUB_NAME
)
```

@jongio for notification.

**Comment by yunhaoling** [comment]
thanks @v-xuto , doc/sample fix PR merged: https://github.com/Azure/azure-sdk-for-python/pull/16457
