### ISSUE TITLE
Eventhub checkpointstoreblob Readme and Samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#16341]
1. Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhub-checkpointstoreblob#next-steps):
![image](https://user-images.githubusercontent.com/57166602/105805549-29491a80-5fdd-11eb-9373-95fc09f355c6.png)

Suggestion:
Refer to this section of other service Readme, for example :
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake#more-sample-code
It is recommended to update as shown in the figure below:
![image](https://user-images.githubusercontent.com/57166602/105805575-37973680-5fdd-11eb-9089-f6396a8d9dab.png)

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub-checkpointstoreblob/samples/receive_events_using_checkpoint_store.py#L22),[link2](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub-checkpointstoreblob/samples/receive_events_using_checkpoint_store_storage_api_version.py#L40):
![image](https://user-images.githubusercontent.com/57166602/105805648-69a89880-5fdd-11eb-8c0a-b518647f821d.png)

Reason:
ValueError: The eventhub name can not be None or empty.
	
Suggestion:
Add a comment to CONNECTION_STR  `# connection string contains EventHub name.`
Or
Add `eventhub_name=eventhub_name` , uptate to:
```
client = EventHubConsumerClient.from_connection_string(
    CONNECTION_STR,
    "$Default",
    eventhub_name=eventhub_name,
    checkpoint_store=checkpoint_store
)
```
@jongio for notification.

**Comment by yunhaoling** [comment]
thanks @v-xuto , doc/sample fix PR merged: https://github.com/Azure/azure-sdk-for-python/pull/16457
