### ISSUE TITLE
Eventhub checkpointstoreblob aio Readme and Samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#16340]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhub-checkpointstoreblob-aio#next-steps):
![image](https://user-images.githubusercontent.com/57166602/105798006-1a0da100-5fcc-11eb-9ac3-45682adc7e5e.png)

Suggestion:
Refer to this section of other service Readme , for example :
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake#more-sample-code
It is recommended to update as shown in the figure below:
![image](https://user-images.githubusercontent.com/57166602/105798052-36114280-5fcc-11eb-97b9-a90e089e634d.png)

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/receive_events_using_checkpoint_store_async.py#L28),[link2](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/receive_events_using_checkpoint_store_storage_api_version_async.py#L46):
![image](https://user-images.githubusercontent.com/57166602/105798132-65c04a80-5fcc-11eb-9a6e-333641028787.png)

Reason:
ValueError: The eventhub name can not be None or empty.
	
Suggestion:
Add a comment to CONNECTION_STR  `# connection string contains EventHub name.`
Or
Add parameter `eventhub_name=eventhub_name` , uptate to:
```
client = EventHubConsumerClient.from_connection_string(
    CONNECTION_STR,
    "$Default",
    eventhub_name=eventhub_name,
    checkpoint_store=checkpoint_store
)
```
@jongio for notification.

**Comment by yunhaoling** [comment]
thanks @v-xuto , doc/sample fix PR merged: https://github.com/Azure/azure-sdk-for-python/pull/16457
