### ISSUE TITLE
Help with credentiasl

### ISSUE THREAD

**Issue by vot4anto** [Azure/azure-sdk-for-python#16347]
Hi to all, 
 I want to monitor the CPU usage of one VM and send an email if the VM is too idle.
I find the follow link:
https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring?view=azure-python

but unfortunately I can't understand how I can retrieve the resource_id and credentials for the follow:

resource_id = (
    "subscriptions/f4a37d44-c297-408d-9673-3f7792ad6a2a/"
    "resourceGroups/engine/"
    "providers/Microsoft.Compute/virtualMachines/spot/extensions/AzureNetworkWatcherExtension"
).format(subscription_id, resource_group_name, vm_name)

and

client = MonitorManagementClient(
    credentials,
    subscription_id
)

I usually use powershell to connect to Azure and sign in with a service principal and also try with the follow:
https://docs.microsoft.com/en-us/rest/api/resources/resources/getbyid

but without success.

Thanks

**Comment by eladmotola** [comment]
for the credentails, you can use like the following:
```
from azure.identity import AzureCliCredential
credentials = AzureCliCredential()
```

or you can read the following:
https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd

for the resource_id.
its not "providers/Microsoft.Compute/virtualMachines/spot/extensions/AzureNetworkWatcherExtension", its "providers/Microsoft.Compute/virtualMachines/{}"

**Comment by vot4anto** [comment]
Thanks for you reply.
I follow your suggestions and also read the guide:
https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd

But unfortunately I failed with all method.
Follow the ones that I think is the easiest:

Use  the az ad sp create-for-rbac command with the --sdk-auth parameter to generate this JSON format directly.

import os
from azure.common.client_factory import get_client_from_json_dict
from azure.mgmt.resource import SubscriptionClient

# Retrieve the IDs and secret to use in the JSON dictionary

subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
tenant_id = os.environ["AZURE_TENANT_ID"]
client_id = os.environ["AZURE_CLIENT_ID"]
client_secret = os.environ["AZURE_CLIENT_SECRET"]

config_dict = {
   "subscriptionId": subscription_id,
    "tenantId": tenant_id,
   "clientId": client_id,
   "clientSecret": client_secret,
   "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
   "resourceManagerEndpointUrl": "https://management.azure.com/",
   "activeDirectoryGraphResourceId": "https://graph.windows.net/",
   "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
   "galleryEndpointUrl": "https://gallery.azure.com/",
   "managementEndpointUrl": "https://management.core.windows.net/"
}

subscription_client = get_client_from_json_dict(SubscriptionClient, config_dict)

subscription = next(subscription_client.subscriptions.list())
print(subscription.subscription_id) 

but I have the follow error whent try to execute

Traceback (most recent call last):
  File "/home/aettorre/dev_work/it_automation/azure/scripts/subscription.py", line 19, in <module>
    subscription_client = get_client_from_json_dict(SubscriptionClient, config_dict)
  File "/home/aettorre/.local/lib/python3.9/site-packages/azure/common/client_factory.py", line 199, in get_client_from_json_dict
    return _instantiate_client(client_class, **parameters)
  File "/home/aettorre/.local/lib/python3.9/site-packages/azure/common/client_factory.py", line 32, in _instantiate_client
    return client_class(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'credential'

**Comment by eladmotola** [comment]
its strange that you cant achieve that via the azure cli object. did you try to read this?
https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli

maybe its related to you azure-cli verison? did you try to install the latest?

**Comment by vot4anto** [comment]
I don't have any problem with az cli object, as you can also get thye list of definitions of metrics:

az monitor metrics list-definitions --resource "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/engine/providers/Microsoft.Compute/virtualMachines/name" --output table
Display Name                                 Metric Name                                  Unit            Type     Dimension Required    Dimensions
-------------------------------------------  -------------------------------------------  --------------  -------  --------------------  ------------
Percentage CPU                               Percentage CPU                               Percent         Average  False
Network In Billable (Deprecated)             Network In                                   Bytes           Total    False
Network Out Billable (Deprecated)            Network Out                                  Bytes           Total    False
....

I truncate the table, and I can use all az cli command

**Comment by vot4anto** [comment]
I do my job using powershell :-(
