### ISSUE TITLE
[API Management Management] Impossible to create new API using sdk 

### ISSUE THREAD

**Issue by ludokriss** [Azure/azure-sdk-for-python#16356]
- **Package Name**: Azure management Api Management
- **Package Version**: 1.0.0
- **Operating System**: Windows
- **Python Version**: 3.7

**Describe the bug**
It seems as the api management client has a bug when trying to create or update an API. The package tries to poll for a result but includes uneccessary data in the request which throws an error in the aiohttp package

**To Reproduce**
1. Create a client for interacting with API management

```
creds = DefaultAzureCredential()
client = ApiManagementClient(
    credential=creds, subscription_id=settings.subscription_id
)
```
2. create a version set

```
api_version_set=client.api_version_set.create_or_update(
    resource_group_name=settings.resource_group_name,
    service_name=settings.api_management_name,
    version_set_id="anystuff",
    parameters=ApiVersionSetContract(
        display_name="title",
        versioning_scheme="Segment",
        description="Version configuration",
    ),
)
```

3. And then create any form of API.

```
api=client.api.begin_create_or_update(
    resource_group_name=settings.resource_group_name,
    service_name=settings.api_management_name,
    api_id="wss-mp-test-order",
    parameters=get_parameters(oai, api_version_set.id),
)
```

This throws an error:

```
return _RequestContextManager(self._request(method, url, **kwargs))
TypeError: _request() got an unexpected keyword argument 'path_format_arguments'
```

which, as far as I can see, results from these lines in the sdk:

https://github.com/Azure/azure-sdk-for-python/blob/79a64bb9d40610d1696819a2595a49d18d7a7ad6/sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/aio/operations/_api_operations.py#L420-L427

where the path_format_arguments are interpreted in the end as parameters to the GET request polling for a result.

**Expected behavior**
A created API and successful response in the code

**Screenshots**
N/A

**Additional context**
I had to upgrade from 0.2.0 because of a different set of bugs (not reported yet, but at least one still persist). Now everything broke, even the things that I had a workaround for before.

**Comment by 00Kai0** [comment]
Hi @ludokriss, this version of SDK is using a preview-version of API.
It seems that something have changed in service side.
We will update it in the near future.

**Comment by xiangyan99** [comment]
@00Kai0 any updates?
