### ISSUE TITLE
add ComputeNode to azure.batch

### ISSUE THREAD

**Issue by eladmotola** [Azure/azure-sdk-for-python#16377]
**Is your feature request related to a problem? Please describe.**
I need to pull all the compute nodes from a pool and i see that the azure.mgmt.batch doesnt contains any compute_node attribute

**Describe the solution you'd like**
add comput_node key to the library with list function, and maybe some of the functionality of :
https://docs.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.computenodeoperations?view=azure-python

**Describe alternatives you've considered**
I have seen this:
https://docs.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.computenodeoperations?view=azure-python
but I cant find an example of use.
I have also seen:
https://docs.microsoft.com/en-us/rest/api/batchservice/computenode/list
But i want to use the sdk and make my code consistent (to be honest i kinda mess with the auth part, but its on me)

**Additional context**

**Comment by jsntcy** [comment]
@lmazuel, do you know who can help on this?

**Comment by eladmotola** [comment]
@jsntcy Hey
I meant the mgmt package.
After some digging i figure out that I have to use `from azure.batch import BatchServiceClient` and authenticate again with
```
from azure.batch.batch_auth import SharedKeyCredentials
batch_cred = SharedKeyCredentials(batch_account_name, keys.primary)
batch_service = BatchServiceClient(batch_cred, f"https://{batch_base_url}")
```
it seems strange to authenticate twice. why not to use the same connection to achieve the compute node?

**Comment by navba-MSFT** [comment]
@mksuni, @bgklein, @mscurrell, @cRui861, @paterasMSFT, @gingi, @dpwatrous Could you please provide an update on this ? Awaiting your reply.
