### ISSUE TITLE
AzureML OutputFileDatasetConfig not useable with destination set

### ISSUE THREAD

**Issue by DominiqueLade** [Azure/azure-sdk-for-python#16375]
- **Package Name**: azureml-core
- **Package Version**: 1.21.0.post1
- **Operating System**: MacOS
- **Python Version**: 3.7.4

**Describe the bug**
I am not able to use `OutputFileDatasetConfig` with a destination pointing to a Blobstorage or DataLake Gen 2. 

The following error is raised:
```
File "/.venv/lib/python3.7/site-packages/azureml/data/output_dataset_config.py", line 459, in to_data_location 
datastore_name = destination[0].name

TypeError: 'AzureBlobDatastore' object is not subscriptable
```

**To Reproduce**

```
# Connect to Azure ML
interactive_auth = InteractiveLoginAuthentication(tenant_id=tenant_id)
ws = Workspace(subscription_id, resource_group, workspace_name, auth=interactive_auth)
experiment = Experiment(workspace=ws, name="test-experiment")

# Get Dataset
my-output-dataset = OutputFileDatasetConfig(name="attachments", destination=ws.datastores["my-datastore"])

# Set Run Config
pipeline_path = Path(__file__).parent.absolute()
config = ScriptRunConfig(
    source_directory='./',
    script="my-script.py",
    compute_target="default-compute-target",
    arguments=[
        "--path",
        my-output-dataset.as_mount(),
    ],
)

# Execute Script
run = experiment.submit(config)
```

**Expected behavior**
Mount Blobstorage and Datalake Gen 2 as output dataset to a compute target

**Screenshots**
-

**Additional context**
-

**Comment by DominiqueLade** [comment]
Hi,

unfortunately, I still have the same issue as described above. This is currently a show stopper for us. 

Is this the right place to fill the bug report? Is anyone investigating this?

**Comment by yeamusic21** [comment]
We tried to do this as well, and it didn't work for us either.  You can use File Share, which will return a result, but we found other bugs even when we found a workaround for this.

**Comment by DominiqueLade** [comment]
@yeamusic21 Thanks for sharing your insights. Do you mind to elaborate a bit about the other bugs?

**Comment by yeamusic21** [comment]
@DominiqueLade - https://github.com/Azure/azure-sdk-for-python/issues/16568

**Comment by chunyli0328** [comment]
Hi @DominiqueLade 
The destination parameter requires a tuple, so, you should specify it to something like this:
my-output-dataset = OutputFileDatasetConfig(name="attachments", destination=(ws.datastores["my-datastore"], "/output/{run-id}/{output-name}"))

**Comment by DominiqueLade** [comment]
Thanks for the clarification! 

Might be a good idea to improve the error messages.

**Comment by meyetman** [comment]
Thanks @DominiqueLade - please reopen this issue if you have any further questions
#please-close

**Comment by maryamag85** [comment]
Hi , I have an issue similar to this one. When I want to connect to blobstorage (following code)  in AML I get the following error :  

from azureml.data import OutputFileDatasetConfig
ws = Workspace.from_config()
output = OutputFileDatasetConfig(destination=(blob_datastore, 'unzip'))

TypeError: expected str, bytes or os.PathLike object, not OutputFileDatasetConfig

I am following the reference "https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-with-datasets#mount-vs-download"

- azureml.core 1.32.0
- Operating System: windows 
-  Python Version: 3.8

**Comment by emhacker** [comment]
Hi, experiencing problem with AzureBlobStorage as well,
Only I don't get any errors - the script just doesn't run.
Any advice?
