### ISSUE TITLE
Support large ServiceBus messages by implementing claim-check pattern with Azure Storage

### ISSUE THREAD

**Issue by alexwilson1** [Azure/azure-sdk-for-python#16387]
### Problem:
ServiceBus messages are limited to 256KB in size for standard tier and 1MB for Premium Tier. To bypass these limitations, it is common to use Azure Storage in conjunction with ServiceBus, as described by the [claim-check pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check).

The claim-check pattern involves sending a message to the ServiceBus and also placing the corresponding (large) file on Azure Storage. This mimics the sending of a large file through the ServiceBus.

Implementing this is common, as the .NET Azure Library has a addon called 'ServiceBus.AttachmentPlugin' ([GitHub](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin)) with almost 100,000 downloads from [nuget ](https://www.nuget.org/packages/ServiceBus.AttachmentPlugin/).

### Requested solution:
It would be ideal if the Azure Service Bus client library for Python would implement the claim-check pattern and allow the sending of large files. This will abstract away the need for users to build their own claim-check logic for each application.

**Comment by yunhaoling** [comment]
hey @alexwilson1 , I had the discussion with the team and I'm sorry to update you that we don't plan to include this feature as part of the sdk.

There're majorly three reasons:
1. We want to keep the sdk focusing on the core functionality of service bus.
2. If we took the feature into the sdk, then there would be the long-term cost to build/maintain/support the feature.
3. In our repo, we usually would do a sample to demonstrate the combination usage of two different services (e.g. [eventhub with schemaregistry](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/schemaregistry/azure-schemaregistry-avroserializer/samples/eventhub_send_integration.py)). If the functionality or scenario turn out to be complex enough, them a standalone repo or even distribution is preferred.

Based on what I mentioned above, I think what we could do is to:
1. we could either provide a compact sample script in the sdk repo or you created your own repo
2. we could collaborate on the implementation or help review your PRs
3. if you want to release a standalone package, we could give you guidance on releasing a package.

let me know you thoughts, I'm looking forward to collaborating with you on this!
