### ISSUE TITLE
Update docs for DefaultAzureCredential regarding AZURE_CLIENT_ID / managedIdentityClientId relationship

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-python#16402]
Add documentation to `DefaultAzureCredential` indicating that setting the `AZURE_CLIENT_ID` environment variable is equivalent to setting the `managedIdentityClientId`.

**Comment by chlowell** [comment]
Closing this because it's already documented on the class (feel free to reopen if you meant to have it documented somewhere else):
https://github.com/Azure/azure-sdk-for-python/blob/89e7f4ba4459f44d18e216d3eb47a71d65307d35/sdk/identity/azure-identity/azure/identity/_credentials/default.py#L65-L66

**Comment by christothes** [comment]
The other languages have a section about Managed Identities [here](https://github.com/Azure/azure-sdk-for-python/blob/d2cfea454d2092bbd9b826a24a597f8211690c4a/sdk/identity/azure-identity/README.md#authenticating-with-defaultazurecredential) that explains how to configure a custom user created managed identity client ID. Python doesn't have this (not sure if that is intentional), but it would go there if so. 

The reason for the issue is that .NET had a customer question about this behavior which is not documented.
