### ISSUE TITLE
[azure example] when sdk update please update example 

### ISSUE THREAD

**Issue by eaglezzb** [Azure/azure-sdk-for-python#16438]
**Is your feature request related to a problem? Please describe.**
https://github.com/Azure-Samples/virtual-machines-python-manage/blob/master/example.py
too old for us

**Describe the solution you'd like**
focus on vm

**Describe alternatives you've considered**

**Additional context**

**Comment by 00Kai0** [comment]
New examples: https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/compute/manage_virtual_machine.py

**Comment by eaglezzb** [comment]
Thanks
