### ISSUE TITLE
Publish a custom metric

### ISSUE THREAD

**Issue by raphaelauv** [Azure/azure-sdk-for-python#16447]
Hi,

I would like to publish a custom metric from python code using the azure sdk , but I did not found any way to do so, could you give me an example or tell me if it's not possible yet with the SDK.

( with aws I use to do it with boto3 ( cloudwatch ) )

Thank you all :+1:

------------

There is an example to publish span with the opentelemetry azure exporter [**AzureMonitorTraceExporter**](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/monitor/azure-opentelemetry-exporter-azuremonitor/azure/opentelemetry/exporter/azuremonitor/export)

but there is no **AzureMonitorMetricExporter** yet

**Comment by lzchen** [comment]
@raphaelauv 
Hey thanks for trying out Opencensus. Yes you are correct, the way that Opencensus/Opentelemetry treats metrics is via streams, as the point of metrics is to be preaggregated over a set interval with custom dimensions. If you want to produce a unique value in one shot, that behaviour is more suited for log exporter. You can either use the log exporter and have the metric data under "traces" in app insights, or you can try out the workaround that you linked. Does the workaround work for your use case?

**Comment by raphaelauv** [comment]
@lzchen  thank for your answer. Yes the workaround work !

> You can either use the log exporter and have the metric data under "traces" in app insights

I'm not sure to understand you, I want use the metric inside azure dashboard and put alert on it ( what works with the workaround )

I'm surprise there is no native way to do so ( its so easy with aws or datadog )

**Comment by lzchen** [comment]
> I want use the metric inside azure dashboard and put alert on it

Ahh got it, in that case then you'll have to send a metric telemetry. You are correct to use the workaround then. Thanks for the feedback!

**Comment by raphaelauv** [comment]
@lzchen, thank again

If you don't use GitHub issues to track missing features ( AzureMonitorMetricExporter ) then we can close, otherwise this issue could stay open until it's possible with the SDK

**Comment by lzchen** [comment]
@raphaelauv 
We will be tracking this issue separately if we deem it to be a feature gap in devops.

**Comment by raphaelauv** [comment]
@Izchen 

The work around is not working with **custom dimensions** , could you take a look ? thank you very much

https://github.com/census-instrumentation/opencensus-python/pull/820
https://github.com/census-instrumentation/opencensus-python/issues/963


Does azure support custom metrics with custom dimensions ?

**Comment by lzchen** [comment]
@raphaelauv 
custom metrics with custom dimensions is most definitely supported via the [recommended](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python#metrics) way. However since you are using a hack there's a different approach you can take. Looking at your response from [here](https://github.com/census-instrumentation/opencensus-python/pull/8200), it looks like you are populating the `properties` field, which is correct. Are you able to see the custom_dimensions in log analytics?

![image](https://user-images.githubusercontent.com/11580155/108529767-ac325d80-7289-11eb-9c3f-fb3729c06aae.png)

**Comment by raphaelauv** [comment]
Thank you @Izchen -> https://github.com/census-instrumentation/opencensus-python/issues/963
