### ISSUE TITLE
[servicebus] add repr() to ServiceBusMessage/ServiceBusReceivedMessage/ServiceBusBatchMessage

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#16453]
latest updates:

- we decided to pause the support for `body_as_str` method until there're customer requests.
- The ServiceBusMessage (and other message model) should implement the `repr` method as per our guideline here: https://azure.github.io/azure-sdk/python_design.html#python-models-repr

------

right now, `msg.body` returns a generator since it's directly returning the data object from the uamqp message object.

It means to extract contents as a string I have to do `next(msg..body).decode('utf-8')` 

body_as_Str would be a nice convenience to add ; there's on in EH too

**Comment by yunhaoling** [comment]
hey @rakshith91 , I had a brief discussion with anna on this topic, some feedback:

1. in python `str(message) ` could be used and is the preferred way in python to get a string of the object.
  - call `str()` on a ServiceBusMessage will get the str.
2. the value that the method `body_as_str` could provide is taking the `encoding` parameter to decode the bytes.

Question for you:

do you know if there's any user case for SB or EG that has the need to decode a ServiceBusMessage with an encoding different than `utf-8`?
If the built-in `str()` method could satisfy your need, then we could push this request until there're customer requests.

**Comment by yunhaoling** [comment]
updates:

- we decided to pause the support for `body_as_str` method until there're customer requests.
- The ServiceBusMessage model should implement the `repr` method as per our guideline here: https://azure.github.io/azure-sdk/python_design.html#python-models-repr
