### ISSUE TITLE
AttributeError: 'TextAnalyticsClient' object has no attribute 'begin_analyze_healthcare'

### ISSUE THREAD

**Issue by theCuriousHAT** [Azure/azure-sdk-for-python#16468]
from azure.core.credentials import AzureKeyCredential
from azure.ai.textanalytics import TextAnalyticsClient

credential = AzureKeyCredential("my_key")
endpoint="my_endpoint"

text_analytics_client = TextAnalyticsClient(endpoint, credential)

documents = ["Subject is taking 100mg of ibuprofen twice daily"]

poller = text_analytics_client.begin_analyze_healthcare(documents, show_stats=True)
result = poller.result()

docs = [doc for doc in result if not doc.is_error]

print("Results of Healthcare Analysis:")
for idx, doc in enumerate(docs):
    for entity in doc.entities:
        print("Entity: {}".format(entity.text))
        print("...Category: {}".format(entity.category))
        print("...Subcategory: {}".format(entity.subcategory))
        print("...Offset: {}".format(entity.offset))
        print("...Confidence score: {}".format(entity.confidence_score))
        if entity.links is not None:
            print("...Links:")
            for link in entity.links:
                print("......ID: {}".format(link.id))
                print("......Data source: {}".format(link.data_source))
    for relation in doc.relations:
        print("Relation:")
        print("...Source: {}".format(relation.source.text))
        print("...Target: {}".format(relation.target.text))
        print("...Type: {}".format(relation.relation_type))
        print("...Bidirectional: {}".format(relation.is_bidirectional))

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by iscai-msft** [comment]
hey @theCuriousHAT what version of text analytics are you using? This endpoint was added in release `5.1.0b2`. To install the latest versions of TA that are preview versions, you need to add `--pre` into your command when pip installing.

Once you have a preview version of the TA library, that endpoint should be added onto the client. For healthcare your subscription ID needs to be allowlisted as well as the service is in gated preview. If the subscirption you used to create your vault is not allowlisted, you will run into service errors trying to run healthcare.

Thanks!

**Comment by theCuriousHAT** [comment]
hey, @iscai-msft thanks for the support, I was able to fix the error. However, I am facing another challenge while running the above-mentioned sample model.

ValueError: API version v3.1-preview.2 does not have operation 'begin_health' - this is the error I am getting.  Any help on this would be really appreciated.
Thanks!

**Comment by iscai-msft** [comment]
my apologies for not mentioning this earlier. In the current released version, to use healthcare and analyze, you need to specify api version "v3.1-preview.3" when creating your client.

```python
text_analytics_client = TextAnalyticsClient(
    endpoint=endpoint, 
    credential=AzureKeyCredential(key),
    api_version="v3.1-preview.3"
)
```

We will release a new preview version of the TA library next week, where we will default to the api version that has healthcare and analyze, so there will be no need to add this api version setting. This is why the samples we have for healthcare and analyze currently don't have us specifying the api version. Apologies for the mismatch, and thank you so much for your patience!

**Comment by theCuriousHAT** [comment]
Hey,

I am not sure where I am going wrong, but the code is breaking again. 

from azure.core.credentials import AzureKeyCredential
from azure.ai.textanalytics import TextAnalyticsClient

key = "mykey"
endpoint="my endpoint"

text_analytics_client = TextAnalyticsClient(
    endpoint=endpoint, 
    credential=AzureKeyCredential(key),
    api_version="v3.1-preview.3"
)

documents = ["Subject is taking 100mg of ibuprofen twice daily"]

poller = text_analytics_client.begin_analyze_healthcare(documents, show_stats=True)
result = poller.result()

docs = [doc for doc in result if not doc.is_error]

print("Results of Healthcare Analysis:")
for idx, doc in enumerate(docs):
    for entity in doc.entities:
        print("Entity: {}".format(entity.text))
        print("...Category: {}".format(entity.category))
        print("...Subcategory: {}".format(entity.subcategory))
        print("...Offset: {}".format(entity.offset))
        print("...Confidence score: {}".format(entity.confidence_score))
        if entity.links is not None:
            print("...Links:")
            for link in entity.links:
                print("......ID: {}".format(link.id))
                print("......Data source: {}".format(link.data_source))
    for relation in doc.relations:
        print("Relation:")
        print("...Source: {}".format(relation.source.text))
        print("...Target: {}".format(relation.target.text))
        print("...Type: {}".format(relation.relation_type))
        print("...Bidirectional: {}".format(relation.is_bidirectional))

The error I am getting : "azure.core.exceptions.HttpResponseError: (UnsupportedFeature) Feature is not supported"

Thanks for your cooperation.

**Comment by iscai-msft** [comment]
hey @theCuriousHAT I think your issue is because the subscription you used to create your TA vault has not been allowed by the service. Healthcare is currently in a gated private preview, meaning only those with express consent from the service can use this endpoint without errors. The service has plans to make healthcare public once the service GAs v3.1, but for the time being, it's in gated preview.

I'm going to bring in @suhas92, he has been very helpful in getting our subscriptions allowed on the service side.

The error you're getting is definitely not helpful. We're just throwing what is given to us over the wire, @suhas92 do you think it's worth it on the service side to improve the error message? In the meantime, we're going to create a PR to improve the documentation on the SDK side for this, making it more clear in our SDK documentation that using healthcare without an allowed subscription will result in the error you're getting.

I also just want to thank you again so much for your patience, I know how frustrating it must be having to go through all of this back and forth.

**Comment by theCuriousHAT** [comment]
Hi,

Actually I have the access to use the healthcare service and I am running the service from docker also. Issue is coming when I am trying to run it from Python. 

Thanks,

**Comment by iscai-msft** [comment]
@theCuriousHAT consulted with @abhahn (she's on the service team and has done most of the work for the healthcare code). We still think it might be a credential issue, are you absolutely sure that the endpoint and key you use on docker is the same as the one you use for the python sdk?

if so and you're still running into this issue, would you be down to do an in-person call to debug this further? thanks!

**Comment by suhas92** [comment]
@theCuriousHAT Hey Ajay, your subscription has to be whitelisted for healthcare. Also, the resource created from the subscription should be in S teir. Please reach out to csapimad@microsoft.com for getting your subscription whitelisted for the health endpoint.

**Comment by theCuriousHAT** [comment]
@iscai-msft  I am very certain that the issue is not from the credentials as I am able to run the service in docker.
Yes, I think we can try to resolve this issue over a call.

**Comment by theCuriousHAT** [comment]
@suhas92 Hey,

My subs are whitelisted and I can use the service in docker. While trying to run the service through python SDK I am facing issues.

Thanks,

**Comment by theCuriousHAT** [comment]
Hey @iscai-msft,
@suhas92 

I was able to fix the issue. Thanks for your help, I really appreciate it.
