### ISSUE TITLE
Resource group permissions cannot setup

### ISSUE THREAD

**Issue by jjindrich** [Azure/azure-sdk-for-python#1647]
Hi, I cannot find way how to setup permissions on resource group. I need to assign specific role (e.g. Reader) to resource group for specific users/group from AAD.

**Comment by lmazuel** [comment]
Hi @jjindrich 
Assigning role is done with the `azure-mgmt-authorization` package:
https://docs.microsoft.com/python/api/overview/azure/authorization
http://azure-sdk-for-python.readthedocs.io/en/latest/sample_azure-mgmt-authorization.html

I indeed don't have specific samples for that, but this is an example from another sample that assign a ServicePrincipal id the "Contributor" role to a specific ResourceGroup:
https://github.com/Azure-Samples/compute-python-msi-vm#role-assignment

FYI built-in roles:
https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-built-in-roles

CLI can help a lot to figure out what is available:
https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-control-manage-access-azure-cli

Hope this helps, tell me if you have more questions about this.
Thanks,
