### ISSUE TITLE
[ServiceBus] Add packages needed for installation on alpine to README

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-python#16477]
Add a line to the README with installation instructions for alpine on linux similar to [cryptography](https://cryptography.io/en/latest/installation.html#alpine) 

On docker I was able to confirm installation after adding these packages:
```
apk add --update python3 py-pip cmake python3-dev clang clang-dev openssl-dev gcc g++ libc-dev linux-headers
```

**Comment by yunhaoling** [comment]
hey @seankane-msft , thanks for the breadcrumb!

is this to solve the issue: https://github.com/Azure/azure-sdk-for-python/issues/13796?

**Comment by seankane-msft** [comment]
> hey @seankane-msft , thanks for the breadcrumb!
> 
> is this to solve the issue: #13796?

yes!

**Comment by yunhaoling** [comment]
@seankane-msft , I found the minimal dependency set could be:
`apk add --update python3 py-pip python3-dev cmake gcc g++ openssl-dev build-base`, 
which is a subset of yours except for the `build-base` dependency.

If I didn't install `build-base`, my local building of uamqp wheel would fail.
