### ISSUE TITLE
[textanalytics] add __contains__ to DictMixin

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#16481]
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py#L19

The `DictMixin` base class for text analytics models is missing a `__contains__` method. We should support this functionality by adding the following code:

```
    def __contains__(self, key):
        return key in self.__dict__
```

Add a test to verify functionality.

**Comment by iscai-msft** [comment]
closed by PR #16604
