### ISSUE TITLE
Redirect azure-iot-* package feedback to a different repository

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#16508]
This is a configuration update in [`docfx.json`](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docfx.json).

[Docs on how to do this.](https://review.docs.microsoft.com/en-us/help/onboard/github-feedback?branch=master)

ctrl-f `"fileMetadata": {`, that's the relevant part of the doc.

Redirect feedback to this [repository](https://github.com/Azure/azure-iot-sdk-python/)

**Comment by billyto** [comment]
Hi! I can take this one, need Hacktoberfest points for those trees.

**Comment by scbedd** [comment]
Hey @billyto unfortunately that configuration was behind a private repo that folks from the public wouldn't have access to so the instructions won't make sense at all.

@danieljurek can you take care of this?
