### ISSUE TITLE
Support adding custom policies

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#16519]
**Is your feature request related to a problem? Please describe.**

I am trying to work around https://github.com/Azure/azure-sdk-for-python/issues/8313 by adding a new custom policy called `ExternalBearerTokenCredentialPolicy`, but I find it difficult.

The only way to change the default policy list is to override the **whole** list by passing `policies` in `ARMPipelineClient`'s `kwargs`:

https://github.com/Azure/azure-sdk-for-python/blob/ad5308d9befefdc0cdc61c4a47a3329fd874b8a0/sdk/network/azure-mgmt-network/azure/mgmt/network/_network_management_client.py#L72-L73

When `ARMPipelineClient` is created without `policies` argument, it builds the default policy list from `config=self._config`:

https://github.com/Azure/azure-sdk-for-python/blob/de7168a07ec7476f589f316d2cbff6f42f8fda91/sdk/core/azure-mgmt-core/azure/mgmt/core/_pipeline_client.py#L54-L69

In order to add a custom policy to the default policy list, I must also manually create all policies created by `NetworkManagementClientConfiguration`:

https://github.com/Azure/azure-sdk-for-python/blob/3bf56880b6b8cc8ca7d783c96e4a5165eeb0212c/sdk/network/azure-mgmt-network/azure/mgmt/network/_configuration.py#L51-L66

This apparently seems too complicated. 

**Describe the solution you'd like**

SDKs should expose the ability to add custom policies to the default policy list.

**Comment by xiangyan99** [comment]
The problem here is the policy order does matter.

When users want to add a policy into the list, they have to tell the pipeline where they want the policy to be into.

That's the reason we ask users to give the entire list of policies. Any ideas?

**Comment by lmazuel** [comment]
As some point @johanste was considering a simple "first" "last" insert point, since this would solve most of the scenario.s

**Comment by xiangyan99** [comment]
> As some point @johanste was considering a simple "first" "last" insert point, since this would solve most of the scenario.s

Then users need to decide they want to lose retry or (partial)logging. :(

**Comment by johanste** [comment]
"first" and "last" does not have to mean "literally first or last in the pipeline". It can be synonymous with "do-this-for-each-try" and the first can be "do-this-once". The names can be improved. 

One (more complicated) alternative is to give policies "well known names" and have an "insert before/after" or "replace" method for it. But that is probably more power than most people would need.

**Comment by xiangyan99** [comment]
Fixed.
