### ISSUE TITLE
ADLS Gen2 FileSystemClient.get_paths() returns only 5000 paths (1 page in PageIterator)

### ISSUE THREAD

**Issue by siarblack** [Azure/azure-sdk-for-python#16531]
- **Package Name**: azure.storage.filedatalake
- **Package Version**: 12.2.2
- **Operating System**: Azure Databricks, Ubuntu 16.04.6LTS
- **Python Version**: 3.7.3

**Describe the bug**
After getting `FileSystemClient` of particular container in ADLS Gen2, that contains more than 5000 files & folders, I am trying to retrieve all paths from  this container using `get_paths()` method, which returns me the iterator, that contains only 5000 items of `PathProperties` or only 1 page in case I am using `by_page()` method.

**To Reproduce**
1. Connect to the ADLS Gen2 Storage - in my case I used `DataLakeServiceClient` with storage account key as credential.
2. Get the `FileSystemClient` of Container which contains >5000 files & folders using `get_file_system_client()` method.
3. Use `get_paths()` method to get the `PathProperties` iterator.
4. Check the number of retreived paths after transforming iterator to list
5. Optional: Check the number of Pages of retreived paths using `by_pages()` method.

**Expected behavior**
I excpect to get the iterator of `PathProperties` with correct number of items corresponding to the particular container (>5000).
Optional: I excpect to get the `PageIterator` with correct number pages (>1) in case of container contains >5000 paths.

**Screenshots**
![image](https://user-images.githubusercontent.com/50664100/106881427-32756e00-66e6-11eb-8924-ed28d3733366.png)
![image](https://user-images.githubusercontent.com/50664100/106881896-c34c4980-66e6-11eb-8d2b-511143317ac4.png)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by tasherif-msft** [comment]
Hi @siarblack, the server returns/defaults to 5000 paths when you do a `get_paths()` operation.
To change this you can simply pass `max_results` i.e:
`path_list = fsc.get_paths(max_results=6000)`

Let me know if this works :)
Thanks.

**Comment by siarblack** [comment]
Hi @tasherif-msft !
I've already tried this before.
The output is still same:
![image](https://user-images.githubusercontent.com/50664100/106954357-54014480-673c-11eb-9d62-fbb3c72b8e15.png)

I guess this is because of `max_results` default value is None according to the docs:
https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.filesystemclient?view=azure-python#get-paths-path-none--recursive-true--max-results-none----kwargs-

**Comment by tasherif-msft** [comment]
@siarblack it looks like the server limits the results to a maximum of 5k, even if we set it higher. [Reference here](url)
In this case you may have to just use a continuation token like such:
```
        path_generator1 = file_system.get_paths(max_results=2, upn=True).by_page()
        paths1 = list(next(generator1))

        paths_generator2 = file_system.get_paths(max_results=4, upn=True).by_page(continuation_token=generator1.continuation_token)
        paths2 = list(next(generator2))
```
Let me know if this resolves your issue.

**Comment by tasherif-msft** [comment]
Hi @siarblack `max_results` can only be set up to 5000 (what the server allows) per page. The behavior you're encountering is indeed a bug. It appears paging isn't being done correctly. I have been investigating this and it seems it is due to a recent migration in our generated layer.
We will work on this fix asap and probably ship a patch release. 

I will keep you updated. Sorry for the inconvenience!

**Comment by tasherif-msft** [comment]
Hi @siarblack the fix got merged and we will be doing a patch release for this very soon. I will keep you updated.

**Comment by tasherif-msft** [comment]
Hi @siarblack, datalake 12.2.3 has been released!

**Comment by siarblack** [comment]
Thanks a lot @tasherif-msft for so fast and effective response!
Now `get_paths()` method works as expected:
![image](https://user-images.githubusercontent.com/50664100/107631043-16854580-6c6d-11eb-9b5f-036c05d61dd2.png)

ItemPaged iterator `by_page()` works as expected also:
![image](https://user-images.githubusercontent.com/50664100/107631215-4d5b5b80-6c6d-11eb-97f3-3ff277ba2817.png)

**Comment by tasherif-msft** [comment]
@siarblack my pleasure :) sorry for the inconvenience!
