### ISSUE TITLE
[Storage][Datalake]Add get_account_information() API

### ISSUE THREAD

**Issue by xiafu-msft** [Azure/azure-sdk-for-python#16554]
**Is your feature request related to a problem? Please describe.**
Users wants to check if the account is HNS-enabled or not

**Describe the solution you'd like**
add get_account_information() API on DatalakeServiceClient so the user can leverage this API to check HNS-enabled attribute.

**Comment by tasherif-msft** [comment]
This has been resolved by https://github.com/Azure/azure-sdk-for-python/pull/16629
