### ISSUE TITLE
ParallelRunStep for R scripts

### ISSUE THREAD

**Issue by yeamusic21** [Azure/azure-sdk-for-python#16564]
**Is your feature request related to a problem? Please describe.**
Currently, we're able to deploy Python ML models with distributed batch scoring using the ParallelRunStep, and then we can call that deployed pipeline from Data Factory.  Some of the data scientists that I work with model in R.  ParallelRunStep can only run Python scripts and not R scripts.  Due to this, we're looking at other deployment alternatives, but it would be great if we could use Python to build a pipeline but have the scoring code be R.  

**Describe the solution you'd like**
Currently, we build ML pipelines in ML Studio using the Python SDK and the ParallelRunStep.  We still want to use the Python SDK to build our pipelines, but it would be great if there was a way to run an R script from the ParallelRunStep instead of only Python scripts.

**Describe alternatives you've considered**
Azure Batch.  Azure Databricks + SparkR.  Azure Databricks + Sparklyr.

**Additional context**
For e.g., it would be great if the entry_script in ParallelRunConfig could be an R script if we wanted.  Then the R batch scoring script would follow the same format as a Python scoring script (init function, run function, etc.).  In addition, it would be great if we could specify the version of R as well.

```
env.r_version = '3.4.3'

parallel_run_config = ParallelRunConfig(
    environment=env,
    entry_script="batch_scoring.R",
    source_directory=".",
    output_action="append_row",
    mini_batch_size="20",
    error_threshold=1,
    compute_target=compute_target,
    process_count_per_node=2,
    node_count=1
)
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by tracychms** [comment]
Thanks for the feedback. 

Unfortunately, you cannot directly use an R script as entry script with ParallelRunStep. But you can write a Python wrapper to call the R script with a subprocess or use rpy2.

//sample entry_script to call R script with subprocess
def run(mini_batch):
    """Call echo.R/r-path for each item in mini_batch."""
    result = []
    for fil in mini_batch:
        proc = subprocess.run(
            ["Rscript", r_path, fil],
            shell=False,
            check=False,
            capture_output=True,
            universal_newlines=True,
        )
        result.append(proc.stdout)
        
    return result

**Comment by yeamusic21** [comment]
@tracychms 

1. "_Unfortunately, you cannot directly use an R script as entry script with ParallelRunStep._" - Correct this is why I reported a 'Feature Request'.  
2. "_But you can write a Python wrapper to call the R script with a subprocess or use rpy2._" - I thought of that already, but how would I make sure the correct version of R is running in the container where scoring takes place?

**Comment by tracychms** [comment]
If you use the subprocess approach and specify the version when building the image, it should work. rpy2 doesn't work.

def r_env():
    """Return environment for R.

    DEFAULT_CPU_IMAGE = "mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04"
    DEFAULT_GPU_IMAGE = "mcr.microsoft.com/azureml/intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04"
    """
    env = Environment("parallel_run_step")
    env.python.user_managed_dependencies = True
    env.docker.base_image = None  # Set base image to None, because the image is defined by dockerfile.
    env.docker.base_dockerfile = f"""
FROM {DEFAULT_CPU_IMAGE}

**Comment by yeamusic21** [comment]
Hmmm.  I could try this.  If we're able to circle back around to entertaining this option again, I will try this out.

**Comment by v-strudm-msft** [comment]
It's been a few weeks since a solution was provided so we'll close this issue for now. Should you have additional questions, please reopen this issue.
