### ISSUE TITLE
azure.cosmos.offer.Offer documentation is incomplete

### ISSUE THREAD

**Issue by cjoakim** [Azure/azure-sdk-for-python#16562]
This documentation page simply displays the constructor method for class Offer.   It is missing two critical items - how to get the current number of RUs for the Offer (i.e. - container), as well as it's properties.

One has to dig into the source code, at the following link, to see how to obtain the RUs and properties:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cosmos/azure-cosmos/azure/cosmos/offer.py

Please update the page to show something like the following:
ru = offer.offer_throughput
props_dict = offer.properties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485e091d-2bd1-ab33-ced0-b12c47c1fd99
* Version Independent ID: 840c2479-f0b3-2bd2-a6dd-3cb4c28235d0
* Content: [azure.cosmos.offer.Offer class](https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.offer.offer?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cosmos/azure.cosmos.offer.Offer.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-cosmos/azure.cosmos.offer.Offer.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Rodrigossz** [comment]
All examples are in the README file, as the limitations too:

https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cosmos/azure-cosmos#get-database-and-container-throughputs

Tks for the feedback!
