### ISSUE TITLE
File Datalake Client get_path() iterator returning no more than 5000 blob paths

### ISSUE THREAD

**Issue by skylaro** [Azure/azure-sdk-for-python#16572]
**Bug Description**
get_path() returning up to 5000 blob paths, even with max_results set to something > 5000.

**Reproduction**
`
cred = ClientSecretCredential(tenant_id, client_id, client_secret)
storage_account_name = 'ADLSAccount'
path = 'dir'
service_client = DataLakeServiceClient(account_url='{}://{}.dfs.core.windows.net'.format('https', storage_account_name), credential=cred)
file_system_client = service_client.get_file_system_client(file_system='samplecontainer')
result = file_system_client.get_paths(path, recursive=True, max_results=10000)
`

Only 5000 paths are included in 'path'.

**Expected Behavior**
Datalake service pagination logic should support client-side configuration, at least for the Python client.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by skylaro** [comment]
Any update on this @xiangyan99?

**Comment by xiangyan99** [comment]
@skylaro v12.2.4 was added automatically because we released v12.2.3 last week.

@xiafu-msft any updates on this issue?

**Comment by xiafu-msft** [comment]
Hi @skylaro 

It an SDK bug, the fix is available in azure-storage-file-datalake==12.2.3.
Sorry about the inconvenience.

**Comment by skylaro** [comment]
Thanks so much!

**Comment by SatishBoddu-MSFT** [comment]
Hello @skylaro @xiafu-msft Apologies for the delayed response. Just wanted to check if you are still looking for assistance on this issue? Please let us know if we are good to close this issue?

**Comment by tasherif-msft** [comment]
Hi @SatishBoddu-MSFT this issue should have been resolved a while back. Thanks for adding the feedback label.
