### ISSUE TITLE
App Insights module needed

### ISSUE THREAD

**Issue by jmalobicky** [Azure/azure-sdk-for-python#1659]
Hello, I am looking to utilize application insights resources but there is no module currently. Is it possible to generate a appinsights module to create the appinsights component and create web tests?

**Comment by lmazuel** [comment]
The App Insights has made their own client here:
https://github.com/Microsoft/ApplicationInsights-Python

Does this contains what you need, or there is missing part?

**Comment by jmalobicky** [comment]
I did not even know that client existed. Let me give it a once-over and see if it has everything.

**Comment by jmalobicky** [comment]
From the looks of it, that client is for adding into my application versus interacting with the resources in Azure. I need to create an App Insights component and then add web tests from https://docs.microsoft.com/en-us/rest/api/application-insights/. These features do not seem to be part of the Telemetry client or any contexts.

**Comment by lmazuel** [comment]
Gotcha. I create a client from the service metadescription:
https://github.com/Azure/azure-sdk-for-python/pull/1665

If you could try it, would be nice :)

Thanks!

**Comment by jmalobicky** [comment]
@lmazuel Thanks for generating. I will give it a test run and let you know if there are any issues.

**Comment by jmalobicky** [comment]
@lmazuel application insights module seems to be working fine. I havent run into any issues with the use cases I have. I would think it is fine to merge.

**Comment by lmazuel** [comment]
Thanks for the heads up! Will do on Monday

**Comment by jmalobicky** [comment]
@lmazuel has this been merged yet? I have been using it for quite some time without issues. Thanks.

**Comment by lmazuel** [comment]
@jmalobicky Not yet, will schedule it for soon. Thanks!

**Comment by lmazuel** [comment]
Released! https://pypi.python.org/pypi/azure-mgmt-applicationinsights
