### ISSUE TITLE
_PROFILE_TAG doesn't match that in KnownProfiles

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#16590]
**Package Name** and **Package Version**
```
azure-common        1.1.26
azure-core          1.10.0
azure-identity      1.5.0
azure-mgmt-core     1.2.2
azure-mgmt-resource 15.0.0
```

**Describe the bug**

`azure.profiles.KnownProfiles` defines

https://github.com/Azure/azure-sdk-for-python/blob/90807b095dda1d2e2032ba7868a388c1d54e3e42/sdk/core/azure-common/azure/profiles/__init__.py#L244-L249

However, in SDKs `_PROFILE_TAG`s are defined as 

https://github.com/Azure/azure-sdk-for-python/blob/8066770351ae98312b36512b19081d1abeb0804d/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L50

https://github.com/Azure/azure-sdk-for-python/blob/8066770351ae98312b36512b19081d1abeb0804d/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/_subscription_client.py#L47

Notice that `resources` and `subscriptions` are missing from the client path.

The inconsistency causes failure at

https://github.com/Azure/azure-sdk-for-python/blob/8066770351ae98312b36512b19081d1abeb0804d/sdk/core/azure-common/azure/profiles/multiapiclient.py#L82-L83

**To Reproduce**

```py
from msrestazure.azure_cloud import AZURE_PUBLIC_CLOUD as CLOUD
from azure.mgmt.resource import ResourceManagementClient, SubscriptionClient
from azure.identity import InteractiveBrowserCredential
from azure.profiles import KnownProfiles

subscription_id = '0b1f6471-1bf0-4dda-aec3-cb9272f09590'
tenant_id = '54826b22-38d6-4fb2-bad9-b7b93a3e9c5a'

credential = InteractiveBrowserCredential(authority=CLOUD.endpoints.active_directory, tenant_id=tenant_id)

resource_client = ResourceManagementClient(
    credential, subscription_id,
    base_url=CLOUD.endpoints.resource_manager,
    profile=KnownProfiles.v2019_03_01_hybrid,
    credential_scopes=[CLOUD.endpoints.resource_manager + "/.default"])

print([r.name for r in resource_client.resource_groups.list()])
```

```
Traceback (most recent call last):
  File "D:/py/demo/test_profile.py", line 20, in <module>
    print([r.name for r in resource_client.resource_groups.list()])
  File "D:\py\demo\.env\lib\site-packages\azure\mgmt\resource\resources\_resource_management_client.py", line 324, in resource_groups
    api_version = self._get_api_version('resource_groups')
  File "D:\py\demo\.env\lib\site-packages\azure\profiles\multiapiclient.py", line 83, in _get_api_version
    raise ValueError("This profile doesn't define {}".format(self._PROFILE_TAG))
ValueError: This profile doesn't define azure.mgmt.resource.ResourceManagementClient
```

**Comment by jiasli** [comment]
Track 1 SDKs have the correct values:

https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-resource_12.0.0/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/_subscription_client.py#L46

https://github.com/Azure/azure-sdk-for-python/blob/8680b63a48508f14fb71ff3fff7995fc8559707e/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/_subscription_client.py#L46

https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-resource_12.0.0/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L50

https://github.com/Azure/azure-sdk-for-python/blob/8680b63a48508f14fb71ff3fff7995fc8559707e/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L50

**Comment by iscai-msft** [comment]
closed thanks to [autorest.python 5.6.3](https://github.com/Azure/autorest.python/blob/autorestv3/ChangeLog.md#2021-02-10---563) and [fixes to the resources swaggers](https://github.com/Azure/azure-rest-api-specs/pull/12941)
