### ISSUE TITLE
HttpRequest constructor should accept a "json" kwargs

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#16656]
Which is mostly syntactic sugar for `set_json_body`.

This issue implies adding "Content-Type: application/json" to `set_json_body`.

Beware of headers + json as kwargs.

**Comment by iscai-msft** [comment]
addressed this in `azure.core.rest`. Removed `azure.core` and `client` labels to avoid confusion with GA azure core
