### ISSUE TITLE
[formrecognizer] consolidate redundant tests

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#16689]
We have a lot of redundant tests and should look into ways of consolidating them. With how many new features we are adding, our test suite is becoming unsustainable with live tests running for > 3 hours.

- Make sure we cover the across language scenarios found [here](https://microsoft.sharepoint.com/:x:/t/AzureDeveloperExperience/ERwfsXEb42RJt1WPS1bBUwUBnvwdAtJPAGDhekRAxwoCIw?e=qkASxX)
- can we use pytest parameterize? https://docs.pytest.org/en/stable/parametrize.html

**Comment by catalinaperalta** [comment]
Addressed in part in #16715.

**Comment by catalinaperalta** [comment]
Test consolidation was completed during MQ and as part of the Test Proxy migration. The new beta design helped reduce tests with the omnibus analyze methods. Live tests should be running much less than 3 hours now.
