### ISSUE TITLE
Problems Authenticating to Azure Government for Managed Identities from ComputeManagementClient Package

### ISSUE THREAD

**Issue by RDukes425** [Azure/azure-sdk-for-python#16688]
- **Package Name**: ComputeManagementClient
- **Package Version**: 3.9.1
- **Operating System**: Windows
- **Python Version**: 3

**Describe the bug**
Azure Government users attempted to authenticate using Managed Identities encounter an error. The error message displayed is: azure.core.exceptions.ResourceNotFoundError: (SubscriptionNotFound) The subscription 'a765b6f3-699c-4c11-a913-d6b8457795ac' could not be found.

**To Reproduce**
1. Generated Code: 
from azure.identity import DefaultAzureCredential, ManagedIdentityCredential
from azure.mgmt.compute import ComputeManagementClient
from azure.identity import AzureAuthorityHosts

default_credential = DefaultAzureCredential(authority=AzureAuthorityHosts.AZURE_GOVERNMENT, exclude_environment_credential=True, managed_identity_client_id='4c3ee66a-7aed-4ffe-a10b-daf7b75bd56e')

vm_name='renatatestvm' 
resource_group_name='renata-rg' 
subscriptionid='9ea57abb-990d-4601-94b5-2a2a6d418274'

compute_client = ComputeManagementClient(default_credential, subscriptionid, base_url='https://management.usgovcloudapi.net/') 
vm_instance = compute_client.virtual_machines.get(resource_group_name, vm_name) 
print(vm_instance)

2. Received Error
PS C:\Users\redukes\hello> & C:/Users/redukes/AppData/Local/Programs/Python/Python39/python.exe c:/Users/redukes/hello/hello5.py
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
SharedTokenCacheCredential.get_token failed: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
VisualStudioCodeCredential.get_token failed: Azure Active Directory error '(invalid_grant) AADSTS90051: Invalid Delegation Token. Invalid national Cloud ID (2) is specified.
Trace ID: e4ec8c11-b64a-4c4f-bd97-1561c1440600
Correlation ID: 79b32a99-1afc-4ac2-8b85-6c3520df798e
Timestamp: 2021-02-10 21:46:17Z'
DefaultAzureCredential.get_token failed: VisualStudioCodeCredential raised unexpected error "Azure Active Directory error '(invalid_grant) AADSTS90051: Invalid Delegation Token. Invalid national Cloud ID (2) is specified.
Trace ID: e4ec8c11-b64a-4c4f-bd97-1561c1440600
Correlation ID: 79b32a99-1afc-4ac2-8b85-6c3520df798e
Timestamp: 2021-02-10 21:46:17Z'"
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        VisualStudioCodeCredential: Azure Active Directory error '(invalid_grant) AADSTS90051: Invalid Delegation Token. Invalid national Cloud ID (2) is specified.
Trace ID: e4ec8c11-b64a-4c4f-bd97-1561c1440600
Correlation ID: 79b32a99-1afc-4ac2-8b85-6c3520df798e
Timestamp: 2021-02-10 21:46:17Z'
Traceback (most recent call last):
  File "c:\Users\redukes\hello\hello5.py", line 18, in <module>
    vm_instance = compute_client.virtual_machines.get(resource_group_name, vm_name)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\mgmt\compute\v2020_06_01\operations\_virtual_machines_operations.py", line 676, in get
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\mgmt\core\policies\_base.py", line 47, in send
    response = self.next.send(request)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 435, in send
    response = self.next.send(request)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 69, in send
    _await_result(self._policy.on_request, request)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\_tools.py", line 29, in await_result
    result = func(*args, **kwargs)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\identity\_credentials\default.py", line 144, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\identity\_credentials\chained.py", line 90, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        VisualStudioCodeCredential: Azure Active Directory error '(invalid_grant) AADSTS90051: Invalid Delegation Token. Invalid national Cloud ID (2) is specified.
Trace ID: e4ec8c11-b64a-4c4f-bd97-1561c1440600
Correlation ID: 79b32a99-1afc-4ac2-8b85-6c3520df798e
Timestamp: 2021-02-10 21:46:17Z'

**Expected behavior**
Users should be able to authenticate against Azure Government with a Managed Identity
- How do we declare the scope properly to ensure the Token is authenticating against Government

**Screenshots**

**Additional context**
In order to get the script to work, we modified the scopes declaration in the configuration file: "C:\Users\renataadmin\AppData\Local\Programs\Python\Python39\Lib\site-packages\azure\mgmt\compute\_configuration.py"
![image](https://user-images.githubusercontent.com/66752282/107578507-aca36800-6ba8-11eb-9b9b-bc1840bc8398.png)

**Comment by chlowell** [comment]
I'm a bit confused about your execution environment. The ResourceNotFoundError indicates ComputeManagementClient authenticated successfully but failed to find the subscription. So if it was using a managed identity (log output can verify), that part worked fine. The output in your second item indicates managed identity was not used: "ManagedIdentityCredential authentication unavailable, no managed identity endpoint found." Is this output from the same environment?

**Comment by RDukes425** [comment]
I was initially running locally from VS Code. I then navigated to my Virtual Machine and created a Python virtual environment. The customer is trying to authenticate to Azure Government and run compute operations. The workaround we were able to figure out is updating the scopes field as it defaults to commercial. 

Trying to determine how to update the scope to Gov without modifying the configuration file itself

**Comment by mattsmall1972** [comment]
Hi Charles - let me give some more context on Renata's behalf.  Let me preface this by saying that we are not experienced Python devs so we might be missing something simple.

**1) Code to reproduce:**
`from azure.identity import ManagedIdentityCredential, DefaultAzureCredential 
from azure.mgmt.compute import ComputeManagementClient 
from azure.identity import AzureAuthorityHosts

default_credential = DefaultAzureCredential(authority=AzureAuthorityHosts.AZURE_GOVERNMENT, exclude_environment_credential=True, managed_identity_client_id='4cxxxxxxd56e' )

vm_name='renxxxxxxxvm' 
resource_group_name='renxxxxxxrg' 
subscriptionid='9ea57xxxxxxxxx418274' 
compute_client = ComputeManagementClient(default_credential, subscriptionid, base_url = 'https://management.usgovcloudapi.net/') 
vm_instance = compute_client.virtual_machines.get(resource_group_name, vm_name) 
print(vm_instance)`

**2) When running with the current and updated versions of the Python Azure API on a VM in the Fairfax cloud,  I get the following error:**
azure.core.exceptions.ClientAuthenticationError: (InvalidAuthenticationTokenAudience) The access token has been obtained for wrong audience or resource 'https://management.azure.com'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.

**3) A review of the access token obtained while running this code shows that token obtained has a resource of the public cloud:**
![resource](https://user-images.githubusercontent.com/28765633/107657654-58a18d80-6c53-11eb-8954-9bff86465a45.png)

**4) Looking in \azure\mgmt\compute\_configuration.py shows that a default credential scope set to the public cloud is used.:**
```
def __init__(
        self,
        credential,  # type: "TokenCredential"
        subscription_id,  # type: str
        **kwargs  # type: Any
    ):
        # type: (...) -> None
        if credential is None:
            raise ValueError("Parameter 'credential' must not be None.")
        if subscription_id is None:
            raise ValueError("Parameter 'subscription_id' must not be None.")
        super(ComputeManagementClientConfiguration, self).__init__(**kwargs)

        self.credential = credential
        self.subscription_id = subscription_id
        self.credential_scopes = kwargs.pop('credential_scopes', ['https://management.azure.com/.default'])

```
**5)  Attempting to pass in credential scope results in the following error:**
Code:
`compute_client = ComputeManagementClient(default_credential, subscriptionid, base_url = 'https://management.usgovcloudapi.net/', credential_scopes='https://management.usgovcloudapi.net/')
`
Error: 
Attempted credentials:
        ManagedIdentityCredential: This credential requires exactly one scope per token request.

**6) Directly changing the scope to match the desired resource allows the code to work as expected:**
Code:
`self.credential_scopes = kwargs.pop('credential_scopes', ['https://management.usgovcloudapi.net/.default'])`

Result::
![Screenshot 2021-02-11 103751](https://user-images.githubusercontent.com/28765633/107659529-3872ce00-6c55-11eb-925e-b6b6f32e58de.png)

**The question is: is there a way to pass in the scope properly?  If not, then this appears to be a bug.**

**Comment by chlowell** [comment]
There is a Python gotcha here. `credential_scopes` is the way to configure a non-default scope. However, its value is later unpacked with the `*` operator:
https://github.com/Azure/azure-sdk-for-python/blob/be9ef5c8e23d917467faa66c78a0956bb28c2a5c/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/_configuration.py#L66

Strings and lists both unpack to a collection of their elements. The elements of a string are its characters:
```py
>>> [*['gotcha']]
['gotcha']
>>> [*'gotcha']
['g', 'o', 't', 'c', 'h', 'a']
```
When you pass `credential_scopes='gotcha'` the credential therefore gets six scopes instead of the required one. So, the value of `credential_scopes` should be a list having one element, the desired scope.

I'm not certain you have the right value for that scope. The one you have might work for managed identity due to an implementation detail, but would probably fail when used with other credentials. Generally, a scope should end with "/.default" (and need not be a valid URL). There's a helper class you could use to avoid needing to know the right values (as shown in [this document](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-sovereign-domain)):
```py
from msrestazure.azure_cloud import AZURE_US_GOV_CLOUD

compute_client = ComputeManagementClient(
    default_credential,
    subscriptionid,
    base_url=AZURE_US_GOV_CLOUD.endpoints.resource_manager,
    credential_scopes=[AZURE_US_GOV_CLOUD.endpoints.active_directory_resource_id + "/.default"],
)
```
I don't often work with management clients though, and don't have access to Azure Government to test out my advice, so let me add @00Kai0, @lmazuel, and @jongio in case I've missed something here.

**Comment by mattsmall1972** [comment]
I kept looking at the double star and was wondering why there were square brackets. :-)  My C++ skills are beyond rusty.

The solution works as you've described, thanks for the information!  We'll wait on further advice before sending this to the customer.

**Comment by 00Kai0** [comment]
@RDukes425  It seems like that you missed `credential_scopes` in compute client.
Plz refer to the doc: https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-sovereign-domain
