### ISSUE TITLE
[formrecognizer] generate code for v2.1-preview.3

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#16682]
Swagger not available yet.

Use multi-api readme: https://github.com/Azure/azure-rest-api-specs/pull/12013/files

Note that there are a few spots in the sync/async _operations_mixin.py generated files that have handwritten code that will need to be preserved until autorest is able to handle multiapi signatures. Example: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/_operations_mixin.py#L173
The handwritten code is prefixed with FIXME.

**Comment by catalinaperalta** [comment]
Completed in #16833
