### ISSUE TITLE
[Identity] Refreshing Credentials Support

### ISSUE THREAD

**Issue by xnkevinnguyen** [Azure/azure-sdk-for-python#16696]
**Question**
Currently working on an application which can query Azure services for long periods. Wondering how does the identity manages expired tokens and refreshing credentials? 

After reviewing the code, it seems some of the authentication services such as authorization_code or managed_identity  will redeem fresh new tokens when necessary, but it doesn't seem to be the case for other services such as user_password. 

An alternative, I have considered is also refreshing credentials with SharedTokenCacheCredential, but I have currently no way of knowing when the credentials expire to use this method.

Thanks,

**Comment by chlowell** [comment]
Most credentials, including UsernamePasswordCredential, handle token caching and refresh internally, requesting new tokens as needed (AzureCliCredential is a special case). Applications generally don't need to worry about the details, especially when using Azure SDK client libraries. If your application doesn't use Azure SDK clients, i.e. it uses a credential class directly, it's safe to call that class's `get_token` method whenever it needs an access token (that method also returns the token's expiration time).

**Comment by xnkevinnguyen** [comment]
Thanks for the answer! From my understanding, get_token gives you the option to manually fetch new tokens if you want, but it is not necessary to renew credentials when they expire since itoken caching and refresh is done internally

**Comment by chlowell** [comment]
You're correct that caching and token lifetimes are handled internally. When you call get_token, most credentials (not AzureCliCredential) will return a cached token, if they have a valid one, or acquire, cache, and return a new token, if they do not. But there's no API for forcing a credential to acquire a new token.

**Comment by xnkevinnguyen** [comment]
Ok, thanks for clarifying!
