### ISSUE TITLE
[formrecognizer] verify samples work with mooncake

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#16690]
Credentials in email thread. Verify we can run samples with endpoint/key.

**Comment by catalinaperalta** [comment]
Samples that pass successfully: 
- sample_recognize_content.py

Samples that fail (might be failing if these endpoints arent deployed yet):
- sample_recognize_business_cards.py 
- sample_recognize_invoices.py
- sample_recognize_receipts_from_url.py
- sample_recognize_receipts.py 
- sample_strongly_typing_recognized_form.py


Pending: 
- sample_recognize_custom_forms.py (need to get trained model ID)
- sample_train_model_with_labels.py (need SAS url)
- sample_train_model_without_labels.py (need SAS url)
- sample_copy_model.py (need model ID)
- sample_create_composed_model.py
- sample_differentiate_output_models_trained_with_and_without_labels.py (need model ID)
- sample_get_bounding_boxes.py (need model ID)
- sample_manage_custom_models.py (need SAS url)

**Comment by kristapratico** [comment]
For the one's that failed, what were the errors?

**Comment by catalinaperalta** [comment]
> For the one's that failed, what were the errors?

It was `azure.core.exceptions.HttpResponseError: (None) Internal server error`

**Comment by maririos** [comment]
Same with .NET, we get `HTTP Error 404. The requested resource is not found` => https://dev.azure.com/azure-sdk/internal/_build/results?buildId=753882&view=logs&j=8fa756a3-4f7e-57d9-3378-58b2dcbde7ff&t=0e9efb2f-41b5-5ac2-5c81-e06ca68c6de9&l=47

**Comment by catalinaperalta** [comment]
Closing since this it is part of testing on different clouds.
