### ISSUE TITLE
Get Download Link of a file from Azure Blob Storage

### ISSUE THREAD

**Issue by mavsun** [Azure/azure-sdk-for-python#16730]
Hello all!

I've been developing a pipeline in AzureML and got it published, but I am having trouble returning the pipeline output file to the user. I am thinking of having a link (with connection string, SAS, etc.) to the output file in Azure storage so that the user can download the file. 

I know that I can connect to and download files from storage account using the Azure SDK, but how do I just get a download link for the file using this library?

Thank you very much for your help!

Best Regards.

**Comment by shbijlan** [comment]
@mavsun This sample notebook has an example of how to download the data from Azure storage. Refer to the last section "Download Outputs."
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-data-dependency-steps.ipynb

You can also get a link to download it from the UI. If you go to your pipeline run graph and right click the output you want to download, you will see an option to view output which directs you to your Azure storage. 

![image](https://user-images.githubusercontent.com/65041041/108428308-354a8580-71f3-11eb-9af8-e1bc3b681375.png)

**Comment by mavsun** [comment]
Thank you for the response. We are trying to figure out ways to get a downloadable link of, say a pipeline output file saved in the blob storage, so that the client can use that link to access the file from the** front end**. We currently are able to generate SAS tokens at the front end but are not sure how to implement the downloading process using JavaScript/.NET

**Comment by shbijlan** [comment]
Please see the article below for some guidance. I have looped in the data team in case you have further questions. 
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet#download-blobs

**Comment by mavsun** [comment]
Thanks, we have tried this method but we ran into a permission issue between Azure and our on-prem. Closing this for now as we are not likely to bypass this issue for a while. Thanks for your assistance.

**Comment by Arthur-272** [comment]
Hello, I am trying to do the same thing using Spring Framework and I too am unable to get a SAS URL for the output file that is stored in the container on successful task completion. Could you please let me know how you solved your issue, maybe I can get an idea for my issue as well. Thanks

**Comment by cloga** [comment]
Hi @Arthur-272,

In AzureML by default, all the data will be stored in the workspace default datastore. You can find the detailed info in datasore page in AML studio, and the name of this default datastore is `workspaceblobstore (Default)`
![image](https://user-images.githubusercontent.com/1320343/153096589-2381faae-2943-4e8b-9e18-b14c2491b9c7.png)

Every job outputs will located under this <account_name>/<container_name>/azureml/<job/run_id>/<port_name>

You can find the job/run id via UI or SDK(https://docs.microsoft.com/en-us/cli/azure/ml(v1)/run?view=azure-cli-latest#az-ml(v1)-run-list)

Hope this will help you to solve your problem.

**Comment by ShakeFake** [comment]
in azure：if you are public , you can join the file URL with format as **https:/<accountName>.blob.core.windows.net/<containerName>/<blobName>**
if you are privilege，you should sign it at first
