### ISSUE TITLE
aiohttp SecretClient not closing session.

### ISSUE THREAD

**Issue by cyberpion-yotam** [Azure/azure-sdk-for-python#16757]
- **Package Name**: azure-keyvault-secrets
- **Package Version**:  4.2.0
- **Operating System**: Ubuntu 18
- **Python Version**: 3.8

**Describe the bug**
When running is Azure Functions, after using the aio SecretClient's context manager, I receive the following error:

Unclosed connector connections: [[(<aiohttp.client_proto.ResponseHandler object at 0x7f274ad97e80>, 1654.2421122)]] connector: <aiohttp.connector.TCPConnector object at 0x7f274adc00d0>

I am aware this bug was "fixed" here: https://github.com/Azure/azure-sdk-for-python/issues/8990

I have followed the instructions here: https://docs.microsoft.com/en-us/python/api/overview/azure/keyvault-keys-readme?view=azure-python#async-api

**To Reproduce**
1. Create an Azure function (timer triggered in my case)
2. Use the aio SecretClient and DefaultAzureCredential using a context manager
```
from azure.identity.aio import DefaultAzureCredential
from azure.keyvault.secrets.aio import SecretClient
async def main(...):
    credential = DefaultAzureCredential()
    client = SecretClient(KEY_VAULT_URL, credential=credential)
    async with client:
        # Use client
```
3. Run with `func start` or in a deployed Azure Function

**Expected behavior**
Azure function success.

**Actual behavior**
I get the following error after execution:
```
Unclosed connector connections: [[(<aiohttp.client_proto.ResponseHandler object at 0x7f274ad97e80>, 1654.2421122)]] connector: <aiohttp.connector.TCPConnector object at 0x7f274adc00d0>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/75618993/108056999-b15d9580-705a-11eb-8975-3b335f348e22.png)

**Comment by cyberpion-yotam** [comment]
Ended up finding out you need to close the Credential as well.
So:
```
from azure.identity.aio import DefaultAzureCredential
from azure.keyvault.secrets.aio import SecretClient
async def main(...):
    credential = DefaultAzureCredential()
    client = SecretClient(KEY_VAULT_URL, credential=credential)
    async with client, credential:
        # Use client
```

Could maybe be added to the docs (seems like a pretty integral part of using the SecretClient)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by chlowell** [comment]
Glad you figured it out, and I agree it's worth documenting. I've opened #16793 to do that. Thanks for this issue!
