### ISSUE TITLE
Checkpoint not created in blob container

### ISSUE THREAD

**Issue by mjrlgue** [Azure/azure-sdk-for-python#16759]
- **Operating System**: Azure Function / Azure IoT hub
- **Python Version**: 3.6

**Describe the bug**
Checkpointing when reading Azure Iot hub events is not created in blob container

**To Reproduce**
1. create a http trigger Azure function that reads from an IoT Hub events, code [here](https://github.com/Azure/azure-sdk-for-python/tree/azure-eventhub-checkpointstoreblob-aio_1.1.2/sdk/eventhub/azure-eventhub-checkpointstoreblob).
2. specified container name as `CONTAINER_NAME = "path/to/my-container"`
3. start the azure function and check the blob: empty blob

**Expected behavior**
Azure function can't store the current checkpoint when the path to a container in a subfolder, I created one instead as `CONTAINER_NAME = "myContainer"` and it worked. 

I was looking for the problem for two days and could not find out, is this behavior already known? I couldn't find any restriction in naming containers in the [doc](https://docs.microsoft.com/en-us/python/api/overview/azure/eventhub-checkpointstoreblob-aio-readme?view=azure-python#create-an-eventhubconsumerclient)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by mjrlgue** [comment]
@xiangyan99 seems that the container where I created my folder was **Private** in the 'Public access level', I tested one with 'Public access level' set to **Container** and it worked.

**Comment by xiangyan99** [comment]
If you don't mind, I will close the issue?

**Comment by mjrlgue** [comment]
yes and thank you
