### ISSUE TITLE
Storage Tests Pipeline Failure

### ISSUE THREAD

**Issue by tasherif-msft** [Azure/azure-sdk-for-python#16765]
We have been experiencing sporadic failures on random tests where the connection randomly aborts. 
Our retry policy attempts to retry multiple times with no luck.

Please advise:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=727674&view=ms.vss-test-web.build-test-results-tab&runId=16566414&resultId=100054&paneView=debug

**Comment by kurtzeborn** [comment]
@tasherif-msft, are you still seeing sporadic failures?  This is an old issue and I haven't heard much lately on concerns here.  Marking this to close automatically.  Please re-open or escalate through @amishra-dev if this is continuing to happen.
