### ISSUE TITLE
Ambiguous result for get_ftp_allowed and update_ftp_allowed method

### ISSUE THREAD

**Issue by yuu045-ran** [Azure/azure-sdk-for-python#16778]
- **Package Name**: azure-mgmt-web - https://pypi.org/project/azure-mgmt-web/
- **Package Version**: 1.0.0
- **Operating System**: Windows
- **Python Version**: 3.7

**Describe the bug**

We need further explaination on the get_ftp_allowed method as well as update_ftp_allowed method: which FTP state is it referring to, as well as how to verify this value in portal.

- get_ftp_allowed will return true/false in the JSON but as far as I know, the FTP state(go to portal > app service > configuration > general settings > FTP state) actually should have 3 values:"AllAllowed", "Disabled", and "FtpsOnly". But get_ftp_allowed is returning boolean(only true/false) here: 
```
{"name": "functionapp-name", 
"type":   "Microsoft.Web/sites",  
"allow": true}
```

- In portal when we verify(az functionapp config show --name appname --resource-group rgname) the actual FTP state we will get **"ftps_state": "Disabled"**, which is under **type - "/subscriptions/{sub-id}/resourceGroups/{rgname}/providers/Microsoft.Web/sites/{app-name}/config/web"**

- In Azure resource explorer we can verify the same by clicking into app > config > web

It seems that the resource types are different(Microsoft.Web/sites, and Microsoft.Web/sites/{app-name}/config/web), but this is causing confusion and I think the get_ftp_allowed definition is ambiguous. So, in conclusion, we need what is the get_ftp_allowed method is returning and which FTP(FTP state?) is it referring to.

**Expected behavior**

Matching results between:
- portal > app service > configuration > general settings > FTP state
- result of running get_ftp_allowed

Or, explaination on what is the get_ftp_allowed is referring to.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.
