### ISSUE TITLE
How to force azure eventhub checkpointstoreblob to terminate after xx seconds

### ISSUE THREAD

**Issue by mjrlgue** [Azure/azure-sdk-for-python#16779]
I have an azure function (http trigger) that I trigger every 10 minutes and read data from IoT Hub, I would like to stop the azure function when time exceeded 58 seconds, the based code [here](https://github.com/Azure/azure-sdk-for-python/tree/azure-eventhub-checkpointstoreblob-aio_1.1.2/sdk/eventhub/azure-eventhub-checkpointstoreblob)

Here is what I did to achieve this but I failed:

- in `__init__.py`, I store the current time in os.eviron when I start reading events from IoT hub:
```python
from . import eventHubHelper

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')

    if name:
        # start consumer
        logging.info('************* Starting consumer ***********')
        # store current time
        os.environ["TIME"] = str(time.time()) 
        eventHubHelper.consumer()
```
- then in `eventHubHelper.py`, I get the time and test (I know it's not pythonic, anyone suggests something better and working :)):
```python
def on_event(partition_context, event):
    # get the time
    start = float(os.environ["TIME"]) 
    print("################## current exec time: "+ str(time.time() - start) + " seconds")
    if time.time() - start > 58:
        start = 0
        print("#################### execution time " + str(time.time() - start ))
        # return http response but doesn't work
        return func.HttpResponse("############ execution time: "+ str(time.time() - start) + " seconds")
    print("Received event from partition: {}.".format(partition_context.partition_id))
    print("Telemetry received: ", event.body_as_str())
    print("Properties (set by device): ", event.properties)
    print("System properties (set by IoT Hub): ", event.system_properties)
    # store events in table storage
    store_to_ts(partition_context.partition_id, event.body_as_str(), event.properties)
    partition_context.update_checkpoint(event)

def on_error(partition_context, error):
    # Put your code here. partition_context can be None in the on_error callback.
    if partition_context:
        print("An exception: {} occurred during receiving from Partition: {}.".format(
            partition_context.partition_id,
            error
        ))
    else:
        print("An exception: {} occurred during the load balance process.".format(error))

def consumer():
    checkpoint_store = BlobCheckpointStore.from_connection_string(
        STORAGE_CONNECTION_STR, 
        BLOB_CONTAINER_NAME
        )
    client = EventHubConsumerClient.from_connection_string(
        conn_str=CONNECTION_STR,
        consumer_group="$default",
        eventhub_name=EVENTHUB_NAME,
        checkpoint_store=checkpoint_store
        
    )
    try:
        with client:
            client.receive(
                on_event=on_event,
                on_error=on_error
            )
    except KeyboardInterrupt:
        print("Receiving has stopped.")
```
When I execute the above azure function, I don't get a 200 response, instead I get a 504 http status, the script doesn't quit once it hits `return func..` statement, any suggestion please ?

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by yunhaoling** [comment]
hey @mjrlgue, thanks for reaching out.

The receive behavior of the SDK is:
- the `receive` method of the `EventHubConsumerClient` is a blocking call which will receive forever.
- `on_event` is the callback method which will be called every time an event is received.

To receive for a certain amount of time, you need to use thread (in sync) or async task (in async) to control the flow.
We have provided sample code to utilize thread to receive for a period and it's available here:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/samples/sync_samples/recv_for_period.py

**Comment by mjrlgue** [comment]
Alright thanks @yunhaoling, I found a workaround to quit the `on_event` function is to close the client when time exceeded xx seconds `client.close()`. I'll try your link asap seems better.

**Comment by yunhaoling** [comment]
hey @mjrlgue , I'm closing the issue assuming you have already got the solution.
feel free to re-open if you still get trouble or have any question.
