### ISSUE TITLE
Add ConnectionString parsing

### ISSUE THREAD

**Issue by nfx** [Azure/azure-sdk-for-python#16782]
In plenty of cases we receive connection strings for azure resources. We should port `ConnectionString` parser from iot sdk, so that it's easier and more consistent to work with APIs https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/azure/iot/device/common/auth/connection_string.py

**Comment by xiangyan99** [comment]
Thanks for the feedback. Are you suggesting moving the connection_string parsing into azure.core?

One concern here is different services may have different schemas for the connection string.

e.g. app config service connection string is different from the one for iot. hence _validate_keys may not work correctly for app config.

Could you help give more data points which services can share the parser? That can help us prioritize the work.

Thank you.

**Comment by nfx** [comment]
@xiangyan99 i'd mostly need connection string parser for storage and event hubs. that's it :) you can add more services later. typical use case would be getting azure event hub connection string and configuring pyspark consumer with it. or accessing adls gen1/gen2/blob through python sdk directly. 

the point is that connection strings are usually the outputs from Terraform & they land in secret stores and stored over there as secret string as a whole. it would be nicer not to write same (even small) amount of code again and again. 

you can introduce a `ConnectionString` class that has generic methods to access keys in a free form and then have subclasses with specific service schema validation. Those subclasses should also extend `Credentials` class (that usually has SPN client/secret).

**Comment by xiangyan99** [comment]
@nfx Thank you for the information. It is very helpful.

**Comment by nfx** [comment]
Looking forward to see it and use it :) make sure it propagates to azureeventhubs and storage docs

**Comment by swathipil** [comment]
Hi @nfx,

The feature has been added and will be available in the next release. We did consider your proposed option of some sort of `ConnectionString` class, but ultimately decided that a parsing function is the best solution, as it provides validation that is generic enough for parsing connection strings across services and is simplest to use.

If you are looking for a `ConnectionString` class, specifically, Event Hubs already has the [`EventHubConnectionStringProperties`](https://github.com/Azure/azure-sdk-for-python/blob/a70c40cbce1bc091c6cf961c69f82e78db8511ce/sdk/eventhub/azure-eventhub/azure/eventhub/_connection_string_parser.py#L13) class, which I believe is similar to what you are looking for. Storage does not seem to have a similar class, but we can create an issue for this if you still find this necessary.

Thank you for your feedback!

**Comment by nfx** [comment]
@swathipil i'd like to see the same consistent `ConnectionString` class in Python SDK, as there is in Java SDK :) e.g. one standard for all services, because i don't want to learn all different types of connection strings out there :)

**Comment by xiangyan99** [comment]
@nfx Could you give us more details what's the difference between the ConnectionString class and dict?

Thank you.

**Comment by nfx** [comment]
@xiangyan99 normal classes give some sort of autocompletion and better documentation, than simple dicts. here's the example https://github.com/Azure/azure-sdk-for-java/blob/026664ea871586e681ab674e0332b6cc2352c655/sdk/resourcemanager/azure-resourcemanager-appservice/src/main/java/com/azure/resourcemanager/appservice/models/ConnectionString.java

**Comment by swathipil** [comment]
Hi @nfx, in the core `parse_connection_string` method, we provide docstring and define the types of the input and type of the keys and values in the output dict ([in this line here](https://github.com/Azure/azure-sdk-for-python/blob/46b402fa34ff2158ad2fbf5fa14f4f2a3611af3e/sdk/core/azure-core/azure/core/utils/_connection_string_parser.py#L11)). 
In the Java example, it looks like there are four instance variables/properties on a `ConnectionString`, with only one key and one value, rather than parsed key/value pairs. I may be misunderstanding the kind of documentation you are looking for. Would you be able to clarify the purpose of the `ConnectionString` interface? (If you could provide a sample connection string that would be passed to the implementation of the `ConnectionString` and the return value of `name()`, `value()`, `type()`, and `sticky()`, that would be very hellpful.)
Thanks!
