### ISSUE TITLE
Broken Link in docs to postgres

### ISSUE THREAD

**Issue by ndanielsen** [Azure/azure-sdk-for-python#16794]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

Searched for postgres in nav bar and received 404 not found
https://azure.github.io/azure-sdk-for-python/databaseformysql/postgresql.html

<img width="259" alt="Screen Shot 2021-02-17 at 5 22 39 PM" src="https://user-images.githubusercontent.com/2944777/108290219-d0385680-7144-11eb-99b1-3862d7196c73.png">

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by lmazuel** [comment]
@scbedd from https://azure.github.io/azure-sdk-for-python/, the link "Database for MySQL/PostgreSQL" leads to a 404. This should leads to the doc of https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/rdbms/azure-mgmt-rdbms

**Comment by scbedd** [comment]
This has been resolved. Apologies for the delay.

Automatically generated link `https://azure.github.io/azure-sdk-for-python/databaseformysql/postgresql.html` now looks like `https://azure.github.io/azure-sdk-for-python/databaseformysqlpostgresql.html` and [resolves properly.](https://azure.github.io/azure-sdk-for-python/databaseformysqlpostgresql.html)
