### ISSUE TITLE
managment resource package link is broken (404)

### ISSUE THREAD

**Issue by SiweiWang** [Azure/azure-sdk-for-python#16796]
[Enter feedback here]

when clikc on the link for package "azure.mgmt.resource.resources", the page returned as 404. URL is listed below:
https://docs.microsoft.com/en-us/python/api/azure.mgmt.resource.resources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e19ddc50-3cc0-eded-49ed-e1f2552a421c
* Version Independent ID: 391c4753-337c-8a9f-fa58-2c6fc95cb6df
* Content: [Azure Resources libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/azure.mgmt.resource?view=azure-python)
* Content Source: [docs-ref-services/latest/azure.mgmt.resource.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/azure.mgmt.resource.md)
* Service: **resources**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @lisawong19
* Microsoft Alias: **routlaw**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by SatishBoddu-MSFT** [comment]
Hello @SiweiWang Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. We are working on this to resolve asap.
