### ISSUE TITLE
not able to download BlockBlobFile from SasUri using python SDK

### ISSUE THREAD

**Issue by Amit-Singh-N** [Azure/azure-sdk-for-python#1679]
Dear Sir/Madam,

I am receiving SasUri ""SasUri":"https://MyBlob.blob.core.windows.net/scustomer/20171127T182624_98e74a63-3ffe-4ded-9d54-a15359792b9e?sv=2016-05-31&sr=c&si=datatest_customer_MyClient_r&sig=gzabDDEx%2BBhPJGUjPdk%2F58EWLELpTTDJCVV5a1MvmOc%3D"" from the Azure service bus, when i am clicking SasUri it is downloading the file to default folder, how ever i want to download the file using Azure python SDK with SasUri, i have searched a lot on this and given a try with various API mentioned in the "http://azure.github.io/azure-storage-python/" under the heading " Reference Documentation - All Services".I am unable to find any API, however using python 3.4 (not Azure python SDK) library i am able to download and this is not acceptable to my client. Would you be able to suggest which API i can use from  Azure python SDK ? Any code example ?

Please note that : The file is blockblob file in Azure block storage  and I am receiving SAS URI from Azure service bus.

Thanks and Regards,

Amit Singh N

**Comment by lmazuel** [comment]
Hi @Amit-Singh-N 
This is a storage issue, please open the issue on their tracker, in order to have the storage experts looking at your issue:
https://github.com/Azure/azure-storage-python/issues

Thank you,
