### ISSUE TITLE
[Identity] Make azure-common file-based auth exceptions more helpful

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#16791]
Context: users who have relied on `azure-common`'s [factory methods](https://docs.microsoft.com/python/api/azure-common/azure.common.client_factory?view=azure-python) like [`get_client_from_auth_file`](https://docs.microsoft.com/python/api/azure-common/azure.common.client_factory?view=azure-python#get-client-from-auth-file-client-class--auth-path-none----kwargs-) and [`get_client_from_json_dict`](https://docs.microsoft.com/python/api/azure-common/azure.common.client_factory?view=azure-python#get-client-from-json-dict-client-class--config-dict----kwargs-) have been unable to use this authentication pattern with clients using `azure-identity` (see #16760, for example).

Attempting to use these factory methods with track 2 clients yields an unhelpful exception (e.g. `TypeError: __init__() missing 1 required positional argument: 'credential'`). Instead, exceptions caused by this pattern should:
  1. Point to `azure-identity` credentials
  2. Point to a [sample/guidance](https://github.com/Azure/azure-sdk-for-python/issues/16790) for migrating from this scenario, which should be reachable at an aka.ms link

**Comment by lmazuel** [comment]
Link we want to show: https://aka.ms/azsdk/python/azidmigration
