### ISSUE TITLE
Azure Identity needs more explanation about 2FA an AD B2C

### ISSUE THREAD

**Issue by askpatrickw** [Azure/azure-sdk-for-python#16814]
The [README for Azure Identity](https://github.com/Azure/azure-sdk-for-python/blob/azure-keyvault-certificates_4.2.1/sdk/identity/azure-identity/README.md) could use some explanation about what happens when you enable 2FA on your user account, and when your application resources are deployed in AD B2C. At least pointers to this information would be super helpful.

**Comment by chlowell** [comment]
Thanks for opening this issue! I think the relevant information would be:
1. azure-identity doesn't support AD B2C
2. username/password authentication (i.e. UsernamePasswordCredential) doesn't support MFA

I'll add a note to the readme about B2C. UsernamePasswordCredential's MFA limitation [is called out in its docstring](https://github.com/Azure/azure-sdk-for-python/blob/2be4054f7df82b3d89a7fa229ae3b11dc6b21c8c/sdk/identity/azure-identity/azure/identity/_credentials/user_password.py#L19-L20) but I think that's reasonable to note in the readme as well.

Is there anything else you think should be added or clarified?
