### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by rploeg** [Azure/azure-sdk-for-python#16828]
Latest version

**Describe the bug**
I have followed on my Mac with the latest versions of VS Code + SDK the following manual:
https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd

When I try to just get the subscription list via the SDK:

```
from azure.identity import DefaultAzureCredential
from azure.mgmt.resource import SubscriptionClient

credential = DefaultAzureCredential()
subscription_client = SubscriptionClient(credential)

sub_list = subscription_client.subscriptions.list()
print(list(sub_list))
```

I get an error

```
[azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
        SharedTokenCacheCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-07-18T18:04:00.6745159Z and was inactive for 90.00:00:00.
]
```

I have tried several other methods defined on the example page, but all of them give this error.

**Comment by chlowell** [comment]
Thanks for opening this issue, that's an interesting error. I would expect the shared cache to be empty on a typical Mac. Regardless of how it got in there, SharedTokenCacheCredential should only use an invalid refresh token once, and evict it from the cache after seeing that error (it can't know a priori that a refresh token is invalid). At least, that's its intended behavior in recent versions; are you using azure-identity 1.4.0 or later?

Here are a few workarounds to start:
- Tell DefaultAzureCredential to skip the shared cache: `DefaultAzureCredential(exclude_shared_token_cache_credential=True)`
- Use a different credential
    - e.g. to authenticate only through VS Code, replace DefaultAzureCredential with VisualStudioCodeCredential
    - Or chain together appropriate credentials for your application ([for example](https://github.com/Azure/azure-sdk-for-python/tree/azure-identity_1.5.0/sdk/identity/azure-identity#defining-a-custom-authentication-flow-with-chainedtokencredential))
- Clear the shared cache. On macOS, it's a keychain password for service "Microsoft.Developer.IdentityService". This could log you out of any application using the cache.

**Comment by rploeg** [comment]
Thank you. 

It's all working on my Windows PC, but want to have this also running on my Mac. 

I have reinstalled my total Mac OS (so nothing is wrong there) yesterday and started with the manual to setup the environment step by step, but I really don't get it why it still doesn't work. 

I login with AZ login in my terminal in VS Code (that is working)

I have tried now four things:

### 1. With the standard DefaultAzureCredential, but it says "no accounts found"
```
EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
SharedTokenCacheCredential.get_token failed: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
```
When I use in my terminal in VScode the **az account show**, I just get the right subscriptions (so authentication works)

### 2. Tried the chain and try to list my subscription like you mention

Code:
```
from azure.identity import AzureCliCredential, ChainedTokenCredential, ManagedIdentityCredential
from azure.mgmt.resource import SubscriptionClient

managed_identity = ManagedIdentityCredential()
azure_cli = AzureCliCredential()
credential_chain = ChainedTokenCredential(managed_identity, azure_cli)

subscription_client = SubscriptionClient(credential_chain)

sub_list = subscription_client.subscriptions.list()
print(list(sub_list))
```
But get this error when runs:
```
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
[<azure.mgmt.resource.subscriptions.v2019_11_01.models._models_py3.Subscription object at 0x7f83d5756d00>, <azure.mgmt.resource.subscriptions.v2019_11_01.models._models_py3.Subscription object at 0x7f83d5756df0>]
```
### 3. Tried to add in the python code a link to a JSON file with clientID, secret etc. like on the docs site

```
  raise ImportError("You need to install 'msrestazure' to use this feature")
ImportError: You need to install 'msrestazure' to use this feature
```
but msrestazure is depreciated when I try to install the library

### 4. changed the method to VisualStudioCodeCredential

```
  File "/Users/remcoploeg/OneDrive - Avanade/repo/pythonAzureTest/test6.py", line 4, in <module>
    credential = VisualStudioCodeCredential()
NameError: name 'VisualStudioCodeCredential' is not defined
```
I am logged in with VS Code in Azure (add-on etc) and that is working

I think I am totally doing something wrong.... or the experience is challenging. Any other idea?

**Comment by chlowell** [comment]
The log output you include with your first two items doesn't necessarily indicate failure. In fact the second snippet looks like success: you got a list of Subscriptions. So backing up a step, are you seeing credentials raise an exception (e.g. ClientAuthenticationError), or interpreting log output like "ManagedIdentityCredential.get_token failed: ..." to mean DefaultAzureCredential or ChainedTokenCredential is unable to authenticate?

**Comment by rploeg** [comment]
thank you again. yesterday night it finally worked with the chained token, but this morning it was again giving issues. I see some potential challenges:

1. I have several accounts that I use (work, personal, clients etc)
2. with AZ login I always use my personal --> that is a Visual Studio enterprise part of my MVP tenant. Because the AD is a hotmail/ live account that could potential be an issue. I get now these kind of errors when I try to retrieve information from an API on Azure:

`SharedTokenCacheCredential.get_token failed: Azure Active Directory error '(invalid_grant) AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '04b07795-8ddb-461a-bbee-02f9e1bf7b46'(Microsoft Azure CLI) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.`

I have logged in with az login with the identity name@tenant.onmicrosoft.com (so not with my live ID) and that was working great yesterday, but after reboot (and yes, I am still logged in with that account) and starting up my script I get the above error. 

I have a clean MacOS, logged in with that account in VS Code, use az login with the same account etc etc. But it looks like it gets now another account again.

**Comment by chlowell** [comment]
SharedTokenCacheCredential can fail to authenticate hotmail/live accounts, depending on how the account was originally authenticated ([here's a detailed explanation](https://github.com/Azure/azure-sdk-for-net/issues/16306#issuecomment-724189313), if you're curious). If you're using DefaultAzureCredential, you can work around this by configuring it not to use the shared cache, i.e. `DefaultAzureCredential(exclude_shared_token_cache_credential=True)`.

Forgive me, but I still don't understand how you want to authenticate. Do you want to always authenticate as the user signed in to VS Code or the Azure CLI, or switch between these tools?

**Comment by rploeg** [comment]
Hi,

Thanks that makes clear. I use all kinds of tools, like Blender or VSCode, but with the AzureCliCredential I can now manage my things the right way it looks like.

**Comment by jongio** [comment]
I resolved this today by running `Azure: Sign In`
![image](https://user-images.githubusercontent.com/2163001/165864488-1ab5d22c-37ff-4897-9b60-760e95e04713.png)
