### ISSUE TITLE
python event hub connection closing

### ISSUE THREAD

**Issue by totuni** [Azure/azure-sdk-for-python#16844]
**Describe the bug**
I am using the python sdk to send events to an event hub.   They worked for a while but now I am getting this: 

ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')

I assume this is a fail on the send.  I can share my code with you if you like.   I am not sure what to do or how to get better trace information 

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by xiangyan99** [comment]
Thanks for the feedback. It looks to me you are using Event hubs client SDK. Could you share your code to confirm that?
