### ISSUE TITLE
Virtual Hub effective routes from RouteTable

### ISSUE THREAD

**Issue by rowco** [Azure/azure-sdk-for-python#16878]
- **Package Name**: azure.mgmt.network
- **Package Version**: 17.1.0
- **Operating System**: Linux
- **Python Version**:  3.7.3

**Describe the bug**

I am trying to retrieve the effective route table from a virtual hub RouteTable, but I always receive a NoneType result.

az command I'm trying to replicate:

az network vhub get-effective-routes -g {resource_group} -n {hub_name} --resource-type RouteTable --resource-id {RouteTableResourceID}

Code based on the test from: https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/sdk/network/azure-mgmt-network/tests/disable_test_cli_mgmt_network.py

**To Reproduce**

```
        BODY = {
          "resource_id": "/subscriptions/" + SUBSCRIPTION_ID + "/resourceGroups/" + RESOURCE_GROUP + "/providers/Microsoft.Network/virtualHubs/" + VIRTUAL_HUB_NAME + "/hubRouteTables/" + HUB_ROUTE_TABLE_NAME,
          "virtual_wan_resource_type": "RouteTable"
        }
        result = mgmt_client.virtual_hubs.begin_get_effective_virtual_hub_routes(resource_group_name=RESOURCE_GROUP, virtual_hub_name=VIRTUAL_HUB_NAME, effective_routes_parameters=BODY)
        result = result.result()
```

**Expected behavior**

Expecting the route table, but receiving NoneType.

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by SaurabhSharma-MSFT** [comment]
@rowco Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still facing this issue ? Please let us know .

**Comment by vishghelani** [comment]
I can confirm that I'm also struggling to get this effective routes from a vhub route table using this same python call.
I've tried writing this using both in sync and async mode (i.e. azure.mgmt.network.aio) I simple get back .result() of None

`import os
import asyncio
from azure.identity.aio import DefaultAzureCredential
from azure.mgmt.network.aio import NetworkManagementClient

RESOURCE_GROUP = '????'
VIRTUAL_HUB_NAME = '???'
HUB_ROUTE_TABLE_NAME = '???'


def main():

    event_loop = asyncio.get_event_loop()
    event_loop.run_until_complete(
        getEffectiveRoutes()
    )
    event_loop.close()


async def getEffectiveRoutes():
    #
    # Create all clients with an Application (service principal) token provider
    #
    SUBSCRIPTION_ID = os.environ.get('ARM_SUBSCRIPTION_ID', None)
    credential = DefaultAzureCredential()
    network_client = NetworkManagementClient(credential, SUBSCRIPTION_ID)

    BODY = {
        "resource_id": "/subscriptions/" + SUBSCRIPTION_ID + "/resourceGroups/" + RESOURCE_GROUP + "/providers/Microsoft.Network/virtualHubs/" + VIRTUAL_HUB_NAME + "/hubRouteTables/" + HUB_ROUTE_TABLE_NAME,
        "virtual_wan_resource_type": "RouteTable"
    }
    async_poller = await network_client.virtual_hubs.begin_get_effective_virtual_hub_routes(
        resource_group_name=RESOURCE_GROUP,
        virtual_hub_name=VIRTUAL_HUB_NAME,
        effective_routes_parameters=BODY)

    virtual_hub_effective_routes = await async_poller.result()

    print("Get virtual hub effective routes:\n{}".format(
        virtual_hub_effective_routes))

    await network_client.close()
    await credential.close()

if __name__ == "__main__":
    main()
`
