### ISSUE TITLE
[Datalake]Optimize memory usage for upload_data for large files

### ISSUE THREAD

**Issue by xiafu-msft** [Azure/azure-sdk-for-python#16890]
**Is your feature request related to a problem? Please describe.**
currently if each chunk is 4GM it seems the whole chunk will be keep in memory first.....

**Describe the solution you'd like**
mimic what blob does for large file upload

**Comment by tasherif-msft** [comment]
Hi Emily, could you elaborate? I tried testing our current workflow for both blob uploads (using `upload_blob`) and file uploads in datalake (`upload_data`). The `tracemalloc` shows that memory usage is essentially the same (if you set the datalake `chunk_size = 4*1024*1024` to mimic blob chunk size when uploading)

Also by 4GM do you mean 4MB?
Could you give a code snippet of the use-case you're hitting? :)
