### ISSUE TITLE
Starting & Stopping multiple VM's in one go

### ISSUE THREAD

**Issue by smoolya17** [Azure/azure-sdk-for-python#16897]
I am currently using 
```
azure-mgmt-compute
Version: 18.0.0
Summary: Microsoft Azure Compute Management Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /var/lib/rundeck/loop_rundeck_refactored/venv/loop_vms_for_start_stop/lib/python3.6/site-packages
Requires: azure-mgmt-core, azure-common, msrest
```

While handling operations in my team, I am asked to turn on client VM's. While doing so I use the `begin_start` method to start the VM. This method accepts to use only 1 VM to start at a time & requires multiple iterations to start multiple VM's causing the operation time to increase. The same stands for `begin_deallocate` as well where all the VM's take a lot of time to stop as they stop one by one.

I'd rather want to use a single API call to turn on all the VM's at one go and cause the operation to complete in a comparable less time.

I have created copies to start & stop VM's which serves the purpose but causes inefficiencies in operation where I have to monitor all the jobs at the same time

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Drewm3** [comment]
These SDKs are designed to largely mirror the REST APIs for Azure VMs. There is no plan for a new REST API to start multiple VMs at once, and we have no plans to add this to the SDK only.
