### ISSUE TITLE
ServiceBus - Long-pooling - BusyBox

### ISSUE THREAD

**Issue by charettedavid** [Azure/azure-sdk-for-python#169]
Hi All, can you tell me if its possible to use this SDK in a DD-WRT BusyBox Linux Distribution? (on a router).

I want to create a small service that monitor SB Queue in long-pooling for XML and do a HTML post on a local web server.

How that sounds?

Thank you

**Comment by lmazuel** [comment]
Hi,

Have you finally tried it and can give an overview or your experience? (for other users).
Otherwise, I will close the bug, I don't think we will able to answer to your question in our team...

Thank you!

**Comment by charettedavid** [comment]
Yes you can close it, we did it another way.

Thanks

Envoyé de mon iPhone
