### ISSUE TITLE
Trying to upgrade azure-mgmt-datafactory from .2.2 to .3

### ISSUE THREAD

**Issue by saulcruz** [Azure/azure-sdk-for-python#1691]
Hi everybody

I'm running:

` pip install azure-mgmt-datafactory --upgrade`

however I don't see version 0.3.0 , the version that I get after the upgrade is  0.2.2

I was expecting to get all the updates regarding this version:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-datafactory/azure/mgmt/datafactory/version.py

am i missing something in my pip install?

**Comment by lmazuel** [comment]
Hi @saulcruz 
You're not missing something, the PR for 0.3 was merged but not released yet. I'm working on it, you can expect that today.

**Comment by lmazuel** [comment]
Released https://pypi.python.org/pypi/azure-mgmt-datafactory/0.3.0

Sorry for the confusion, usually I dislike a lot having master not in sync with PyPI, but got side track on this one...

**Comment by lmazuel** [comment]
FYI @hvermis
