### ISSUE TITLE
Credentials logged by Track 2 azure.core.pipeline.policies._universal logger

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#16929]
**Is your feature request related to a problem? Please describe.**

When calling a REST API which contains credentials in the response (like  [Storage Accounts - List Keys](https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/listkeys)) and SDK client is created with  `logging_enable=True`, credentials will appear in the `DEBUG` log. 

```
> az storage account keys list -n testpremium --debug

azure.core.pipeline.policies._universal: Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/zuh/providers/Microsoft.Storage/storageAccounts/testpremium/listKeys?api-version=2019-06-01&$expand=kerb'
azure.core.pipeline.policies._universal: Request method: 'POST'
...
azure.core.pipeline.policies._universal: Response status: 200
...
azure.core.pipeline.policies._universal: Response content:
azure.core.pipeline.policies._universal: {"keys":[{"keyName":"key1","value":"v9EroHR6CBC6X6ZpnSl+z3x...","permissions":"FULL"},{"keyName":"key2","value":"ugK5x5HWedibhDG0OoKxd...","permissions":"FULL"}]}
```

**Describe the solution you'd like**

It will be helpful if there is a mechanism to filter out credentials from the `DEBUG` log.

**Additional context**

Azure CLI explicitly turns off `DEBUG` log for sensitive commands (https://github.com/Azure/azure-cli/pull/10473).

**Comment by xiangyan99** [comment]
@jiasli I think we got a solution and this issue is solved, right?

**Comment by xiangyan99** [comment]
Did not hear from the author. Close. Feel free to reopen it if it still exists.

**Comment by thoo1** [comment]
I'm looking to do something similar, to turn off the http logging for a specific request, what was the solution that came out of this?

**Comment by xiangyan99** [comment]
@thoo1  This is by design that DEBUG log may contain sensitive information. If you only want info level which is by default, we don't log credentials.
