### ISSUE TITLE
Error when adding dataset to the model on Azure ML

### ISSUE THREAD

**Issue by CakmakMuhammet** [Azure/azure-sdk-for-python#16932]
When I try to add dataset to the model I got error like .

UserScriptException: UserScriptException:
Message: Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot

my codes are
Model.register(workspace=run.experiment.workspace,
model_path = model_file,
model_name = 'randomforestregressor_model',
model_framework=Model.Framework.SCIKITLEARN, # Framework used to create the model.
model_framework_version=sklearn.version, # Version of scikit-learn used to create the model.
tags={'Training context':'Pipeline'},
sample_input_dataset=pre_processed_data,
properties={'Error': np.float(train_mse_err)},
datasets=list(("first_Added_dataset_to_model", pre_processed_data))
)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by azureml-github** [comment]
@Salil Bapat<mailto:Salil.Bapat@microsoft.com> / @Travis Angevine<mailto:Travis.Angevine@microsoft.com> /  @Shivani Patel<mailto:Shivani.Patel@microsoft.com>

Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by trangevi** [comment]
@CakmakMuhammet , how do you create `pre_processed_data`? Per the error message, it seems like that variable is referring to a string when it should be referring to a Dataset object. If it is pointing to a Dataset object, if you can provide the full stacktrace that would help with debugging. Thanks.

**Comment by CakmakMuhammet** [comment]
@trangevi  It is Dataset object. You can see the error that i can see on the pipeline.

Saving model...
Registering model...
Registering model randomforestregressor_model
Starting the daemon thread to refresh tokens in background for process with pid = 102


[2021-02-25T12:34:27.168055] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
2 items cleaning up...
Cleanup took 0.1970975399017334 seconds
Starting the daemon thread to refresh tokens in background for process with pid = 102
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/datasciencewsdev/azureml/9c128523-3e46-4415-987d-8d8a10c94586/mounts/workspaceblobstore/azureml/9c128523-3e46-4415-987d-8d8a10c94586/azureml-setup/context_manager_injector.py", line 223, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/azureml-envs/azureml_e0b4b7d75c9cd39eaa8d1cae40f9b062/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/azureml-envs/azureml_e0b4b7d75c9cd39eaa8d1cae40f9b062/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/azureml-envs/azureml_e0b4b7d75c9cd39eaa8d1cae40f9b062/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "training.py", line 74, in <module>
    datasets=list(("first_Added_dataset_to_model", pre_processed_data))
  File "/azureml-envs/azureml_e0b4b7d75c9cd39eaa8d1cae40f9b062/lib/python3.6/site-packages/azureml/core/model.py", line 581, in register
    resource_configuration=resource_configuration)
  File "/azureml-envs/azureml_e0b4b7d75c9cd39eaa8d1cae40f9b062/lib/python3.6/site-packages/azureml/core/model.py", line 1133, in _register_with_asset
    'DatasetSnapshot'.format(type(dataset)), logger=module_logger)
azureml.exceptions._azureml_exception.WebserviceException: WebserviceException:
	Message: Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot"
    }
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "training.py", line 74, in <module>
    datasets=list(("first_Added_dataset_to_model", pre_processed_data))
  File "/azureml-envs/azureml_e0b4b7d75c9cd39eaa8d1cae40f9b062/lib/python3.6/site-packages/azureml/core/model.py", line 581, in register
    resource_configuration=resource_configuration)
  File "/azureml-envs/azureml_e0b4b7d75c9cd39eaa8d1cae40f9b062/lib/python3.6/site-packages/azureml/core/model.py", line 1133, in _register_with_asset
    'DatasetSnapshot'.format(type(dataset)), logger=module_logger)
UserScriptException: UserScriptException:
	Message: Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot
	InnerException WebserviceException:
	Message: Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot"
    }
}
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Invalid dataset of type <class 'str'> passed, must be of type Dataset or DatasetSnapshot"
    }
}

[2021-02-25T12:34:28.035153] Finished context manager injector with Exception.
2021/02/25 12:34:33 Failed to parse control script error: /mnt/batch/tasks/workitems/91c114ba-6a99-44fe-bdce-a81ea9ab807d/job-1/9c128523-3e46-4415-9_29f447dd-447e-46d2-b18b-28b03dd0c7f8/wd/runTaskLetTask_error.json to json File /mnt/batch/tasks/workitems/91c114ba-6a99-44fe-bdce-a81ea9ab807d/job-1/9c128523-3e46-4415-9_29f447dd-447e-46d2-b18b-28b03dd0c7f8/wd/runTaskLetTask_error.json doesn't exist
2021/02/25 12:34:33 Failed to run the wrapper cmd with err: exit status 1
2021/02/25 12:34:33 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/status
2021/02/25 12:34:33 mpirun version string: {
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
}
2021/02/25 12:34:33 MPI publisher: intel ; version: 2018
2021/02/25 12:34:33 Process Exiting with Code:  1

**Comment by trangevi** [comment]
Ah, interesting. Looks like using `list` is converting the internal tuple into a flat list, so instead of a list of a single tuple for the 'datasets' parameter, you're getting a list of a string and an object. This appears to be an effect of the list function itself: https://www.programiz.com/python-programming/methods/built-in/list. If instead you use array notation it maintains the internal tuple.
```
>>> datasets_list=list(("first_Added_dataset_to_model", pre_processed_data))
>>> datasets_list
['first_Added_dataset_to_model', {}]

>>> datasets_list=[("first_Added_dataset_to_model", pre_processed_data)]
>>> datasets_list
[('first_Added_dataset_to_model', {})]
```
So if you change how you're creating that list object to use array notation it should work as expected.

**Comment by CakmakMuhammet** [comment]
Hi again,
It is very  interesting but It worked very well. Many thanks.
