### ISSUE TITLE
Alerts Management Python SDK - [Patch Method] on Smart Detector Rule - Cannot set 'state' to Enabled

### ISSUE THREAD

**Issue by jordanbalsamo-kpmg** [Azure/azure-sdk-for-python#16935]
- **Package Name**: azure-mgmt-alertsmanagement
- **Package Version**: 1.0.0b1
- **Operating System**: Mac OS / Ubuntu
- **Python Version**: 3.9.0

**Describe the bug**
When using the [Patch](https://docs.microsoft.com/en-us/python/api/azure-mgmt-alertsmanagement/azure.mgmt.alertsmanagement.operations.smartdetectoralertrulesoperations?view=azure-python-preview#patch-resource-group-name--alert-rule-name--parameters----kwargs-) method in Smart Detector Operations, it does not seem possible to set the 'state' of the Smart Detector Rule from:

Disabled -> Enabled.

However, it is possible to set the 'state' of the Smart Detector Rule from:

Enabled -> Disabled

Please refer to the following code being used to call the Patch method:

```
patch_sdr_response = client.smart_detector_alert_rules.patch(
     my_rg_name,
     my_alert_name,
     {
          "state": "Enabled" # Trying to set the 'state' of a currently "Disabled" Smart Detector Rule, but has no effect - remains in Disabled state.
     }
    )
logger.debug('Updated scheduled query rule successfully!')
logger.debug(f'Call returned: \n{patch_sdr_response}')
logger.debug(f'Alert enabled status: {patch_sdr_response.state}') # Returns "Disabled" with no error. If state isn't changed, should this emit an error?
```

**To Reproduce**
1. Run the above code sample to set an existing alert in an Enabled state to "Disabled" or set state to "Disabled" via Azure portal.
2. Run the above code again, to set the Smart Detector Rule that was Disabled in step (1) to "Enabled".
3. Smart Detector stays in a "Disabled" state.
4. Activity log in Azure portal only shows logs for cases where Smart Detectors move from Enabled -> Disabled state, but never for Disabled -> Enabled.

**Expected behavior**
Given the above piece of code, I would expect the Smart Detector Rule to move from a Disabled state to an Enabled state.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by yairgil** [comment]
Issue is fixed, please update if you still see a problem. Closing

**Comment by jordanbalsamo** [comment]
Thank you @yairgil - I'll test this out now :)
