### ISSUE TITLE
Error while Forwarding messages from Subscription to a Queue on ServiceBus sdk

### ISSUE THREAD

**Issue by eibrunorodrigues** [Azure/azure-sdk-for-python#16933]
- **Package Name**: azure-servicebus
- **Package Version**: 7.0.1
- **Operating System**: Ubuntu
- **Python Version**: 3.8

**Describe the bug**
Having some issues creating subscriptions on a topic with the flag ForwardTo pointing to a queue.

**To Reproduce**
```
from azure.servicebus import ServiceBusClient, ServiceBusReceivedMessage
from azure.servicebus.management import ServiceBusAdministrationClient
from azure.core.exceptions import ResourceExistsError, ResourceNotFoundError
import os


servicebus_client = ServiceBusAdministrationClient.from_connection_string(
    conn_str=os.getenv("CONNECTION_STRING"))

queue_name = "client_example"
topic_name = "topic/client_example.main"

try:
    servicebus_client.create_queue("client_example")
except ResourceExistsError:
    pass

try:
    servicebus_client.create_topic("topic/client_example.main")
except ResourceExistsError:
    pass

try:
    servicebus_client.create_subscription(
        topic_name=topic_name,
        subscription_name=queue_name,
        forward_to=queue_name
    )
except ResourceExistsError:
    pass
```

**Expected behavior**
I'm creating a subscription that forwards all messages to a queue, this code works on C# sdk. 

**Screenshots**
![image](https://user-images.githubusercontent.com/39570923/109157679-1dbe5000-7751-11eb-9b67-6887f2ff6680.png)

**Additional context**
Error is thrown while attempting to forward-to messages to a queue:
`Exception has occurred: HttpResponseError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
BR0012The specified value is in an invalid format.
Parameter name: ForwardTo. TrackingId:614b32a2-b307-4e2e-9688-7b797f0cc32a_G19, SystemTracker:odin-hml:Topic:topic/client_example.main, Timestamp:2021-02-25T13:01:55`

**Comment by eibrunorodrigues** [comment]
I was able to use ForwardTo using the sb protocol: sb://MYSB.servicebus.windows.net/{QUEUE_NAME}. 
So the question is, on the C# SDK we don't need to do that, just the destination for the messages. 

Should this be a requirement on Python SDK?

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by yunhaoling** [comment]
hey @eibrunorodrigues , thanks for reaching out.

as you mentioned, we currently only support the full path: `sb://<NAMESPACE>.servicebus.windows.net/{QUEUE_NAME}` for the `forward_to` parameter.

The requirement seems reasonable to me, I'll do a cross-language check first to see how other languages on dealing with the `forward_to` parameter(Java, Javascript, .Net) and then add support for it we decide that we want it.

I'll keep posting updates here.

**Comment by eibrunorodrigues** [comment]
@yunhaoling Yeah, I was able to forward messages with the full path. I'll be waiting for the updates, thank you so much!
