### ISSUE TITLE
Feature To Append Tags To A Resource

### ISSUE THREAD

**Issue by BuckarewBanzai** [Azure/azure-sdk-for-python#16943]
**Is your feature request related to a problem? Please describe.**
When utilizing begin_create_or_update() in compute_client.virtual_machines class, the tags for a vm are all overwritten with the new values.

**Describe the solution you'd like**
I would like an option to append to the existing tags instead of overwriting the old tags with new ones. 

**Describe alternatives you've considered**
Currently our only option is to poll for existing tags then add them to our tag dictionary.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by jsntcy** [comment]
@lmazuel, it seems this request has nothing to do with mgmt. SDK and this request may wants a `patch` behavior, any thoughts from your side?

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by Drewm3** [comment]
I believe that the behavior for ARM tags is generic SDK behavior, and not something that is specific to each resource. @jaylabell, could you confirm this is the case with the compute SDK team. And if this behavior is owned by the general SDK team, then please remove the Service Attention label.

**Comment by Drewm3** [comment]
Hi @BuckarewBanzai, from a REST API perspective the functionality that you are looking to use is available in the following API: [Tags - Update At Scope](https://docs.microsoft.com/en-us/rest/api/resources/tags/updateatscope).

@xiangyan99, could you provide details on how to use the above REST API in the python SDK?

**Comment by BuckarewBanzai** [comment]
Yea this appears to be the functionality I was looking for. Any guidance on how to achieve this with the sdk would be great. Thanks everyone for continuing to follow up on this.

**Comment by xiangyan99** [comment]
@00Kai0 Any ideas?

**Comment by xiangyan99** [comment]
Adding @msyyc , could you take a look?

**Comment by msyyc** [comment]
@RAY-316 Please help on the issue.
