### ISSUE TITLE
[monitor] Yank the previous packages

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#16951]
--
opentelemetry-azure-monitor-exporter
opentelemetry-azure-monitor
azure-opentelemetry-exporter-azuremonitor
microsoft-opentelemetry-exporter-azuremonitor

- [x] all the versions must be yanked
- [x] all the packages must redirect to the correct package name on README.

**Comment by lzchen** [comment]
(1) and (2) have been yanked and READMEs updated.

https://pypi.org/project/opentelemetry-azure-monitor-exporter/
https://pypi.org/project/opentelemetry-azure-monitor/
