### ISSUE TITLE
Communication Chat Readme and samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#16956]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-chat#next-steps):
![image](https://user-images.githubusercontent.com/57166602/109247333-b373e100-781e-11eb-9baf-229672f63c7c.png)

Suggestion:
Add a link to `here`.
Link:  https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-chat/samples

@jongio for notification.

**Comment by sarkar-rajarshi** [comment]
Closing issue. This has been fixed.
