### ISSUE TITLE
azure-communication-chat: create the chat client, throw the exception "OverflowError: mktime argument out of range"

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#16962]
- **Package Name**:  azure-communication-chat
- **Package Version**: 1.0.0a20210222001
- **Operating System**: win10
- **Python Version**: 3.7.8
- **Time Zone**: China

**Describe the bug**
- Execute the code `Create the Chat Client` and throw the following exception:
```
 File "azure\communication\chat\_shared\utils.py", line 75, in _convert_expires_on_datetime_to_utc_int       
    epoch = time.mktime(datetime(1970, 1, 1).timetuple())
OverflowError: mktime argument out of range
```
- [azure\communication\chat\_shared\utils.py](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/communication/azure-communication-chat/azure/communication/chat/_shared/utils.py#L75)
![image](https://user-images.githubusercontent.com/57166602/109266185-a9fc7000-7842-11eb-8af4-89b409457f12.png)

- When the operating system is linux, the value of epoch is `-28800`；no exception is thrown.

@Jongio for notification.

**Comment by ashwinder** [comment]
Thanks for raising this issue. Our team will try to repro this bug with the latest version of Python SDK and fix accordingly.

**Comment by Leoaqr** [comment]
Thanks for catching this! Purposed a pr to address the issue here: https://github.com/Azure/azure-sdk-for-python/pull/18026

**Comment by v-xuto** [comment]
Close it, due to https://github.com/Azure/azure-sdk-for-python/pull/18026 merged.
