### ISSUE TITLE
Retrieve certificate details such as subject, serial, SAN

### ISSUE THREAD

**Issue by HighWatersDev** [Azure/azure-sdk-for-python#16965]
I can't seem to find a way to retrieve certificate information such as subject name, serial number, subject alternative names.

I can see how to get Azure-specific info but not what I mentioned above. Is there a way to do it using Python SDK?

**Comment by xiangyan99** [comment]
Could you tell us which Python SDK library are you using?

It looks to me you are looking for parsing certificate using Python.

Maybe this can help? https://stackoverflow.com/questions/16899247/how-can-i-decode-a-ssl-certificate-using-python

**Comment by HighWatersDev** [comment]
I apologize for the lack of information and thanks for the quick response.

I'm using azure.keyvault.certificates modules. What I'm looking to retrieve is blanked out. I can see how I can get name, tag, created_on, vault_url, etc. But the fields in my screenshot do not appear to be accessible via API calls using the library.

![image](https://user-images.githubusercontent.com/37680855/109360303-f3ee5180-7854-11eb-81dd-1fb6af776411.png)

**Comment by xiangyan99** [comment]
Thanks for the information. We will take a look ASAP.

**Comment by mccoyp** [comment]
Hello, thank you for creating an issue! You can get the subject and subject alternative names of a certificate from the [`CertificatePolicy` class](https://docs.microsoft.com/python/api/azure-keyvault-certificates/azure.keyvault.certificates.certificatepolicy?view=azure-python), which is accessible from the [`get_certificate_policy` method](https://docs.microsoft.com/python/api/azure-keyvault-certificates/azure.keyvault.certificates.certificateclient?view=azure-python#get-certificate-policy-certificate-name----kwargs-) or the `policy` property of a [`KeyVaultCertificate`](https://docs.microsoft.com/python/api/azure-keyvault-certificates/azure.keyvault.certificates.keyvaultcertificate?view=azure-python).
```python
client = CertificateClient("https://{vault-name}.vault.azure.net", credential)
policy = client.get_certificate_policy("cert-name")  # or, client.get_certificate("cert-name").policy
print(policy.subject)
print(policy.san_emails)
print(policy.san_dns_names)
print(policy.san_user_principal_names)
```
The serial number can't be accessed from the Python SDK, but it can be fetched through Azure Powershell with the [`Get-AzKeyVaultCertificate` command](https://docs.microsoft.com/powershell/module/az.keyvault/get-azkeyvaultcertificate?view=azps-5.5.0). I hope this helps! Please feel free to close this issue if this resolves your question, or leave a comment with any additional questions you have.

**Comment by HighWatersDev** [comment]
Thank you for the clarification. I was really looking forward to being able to retrieve serial number via Python SDK. It would be really nice to have that option added to Python SDK.

**Comment by HighWatersDev** [comment]
But in the meantime, your suggestion will work for me.

**Comment by mccoyp** [comment]
After looking into this a little more, it looks like Powershell must get the certificate's serial number from the X509 certificate -- which is part of a [`KeyVaultCertificate`](https://docs.microsoft.com/python/api/azure-keyvault-certificates/azure.keyvault.certificates.keyvaultcertificate?view=azure-python). You can get the serial number via the [`cryptography` package](https://pypi.org/project/cryptography/) by using the code below:
```python
from cryptography import x509

client = CertificateClient("https://{vault-name}.vault.azure.net", credential)
x509_bytes = client.get_certificate("cert-name").cer
x509 = x509.load_der_x509_certificate(x509_bytes)
serial = x509.serial_number  # the serial number as an int
serial_hex = hex(serial)  # the serial number in hex (as it appears in the Portal)
```
I hope this helps!

**Comment by HighWatersDev** [comment]
This is great! That solves my problem. Much appreciated.

**Comment by sdolenc** [comment]
@mccoyp's solution works great!

note: if you happen to see this error
`TypeError: argument 'data': 'bytearray' object cannot be converted to 'PyBytes'`

then you'll want to use bytes() like this
```python
x509  = x509.load_der_x509_certificate(bytes(x509_bytes))
```
