### ISSUE TITLE
[Storage] No exception about connection error during blob download

### ISSUE THREAD

**Issue by kekatahi** [Azure/azure-sdk-for-python#16980]
- **Package Name:azure-storage-blob**: 
- **Package Version:12.7.1**: 
- **Operating System:Ubuntu 18.4 LTS**:
- **Python Version:python:3.8.3**: 

**Describe the bug**
the data downloaded using download_blob method seems small size compare to source blob. This issue happen when the NetworkError occurred . And there are no exception when NetworkError occurred.

**To Reproduce**
Before that we should enable the storage analytics logs to check the NetworkError.

1. Create the blob ( at least more than 15MB . this need for step 3). 
2. Start to download using download_blob method.
3. during the download, we make connectivity error explicitly. I did turn off the Wifi on my laptop
4. We see the NetworkError on Storage analytics logs like below and the dowloaded file is small size.
`2.0;2021-02-25T07:00:08.9500298Z;GetBlob;NetworkError;206;`
5. But there are no exception.

sample code
```
try:
    connect_str = os.getenv('AZURE_STORAGE_CONNECTION_STRING')
    containername = "test"
    blobfilename = "test"
    downloadfilepath = "./path/to/data/test"
    dt_before = datetime.datetime.now()
    print("Azure Blob Storage v" + __version__ + " - Python quickstart sample")
    blobserviceclient = BlobServiceClient.from_connection_string(connect_str)
    print("before" ,dt_before)
    blobclient = blobserviceclient.get_blob_client(container=containername, blob=blobfilename)
    with open(downloadfilepath, "wb") as downloadfile:downloadfile.write(blobclient.download_blob().readall())
    dt_after = datetime.datetime.now()
    print("after" ,dt_after)
except Exception as ex:
    print('Exception:')
    print(ex)
```

**Expected behavior**
it should return the exception for NetworkError if the blob download incomplete.

**Comment by annatisch** [comment]
Thanks for the report @kekatahi!
Adding @xiafu-msft and @tasherif-msft for a closer look.
Looks like it might be something in the retry streaming logic? Maybe related to https://github.com/Azure/azure-sdk-for-python/pull/16783

**Comment by kekatahi** [comment]
@annatisch Thank you for your response. Do you have the ETA of #16783 ?

**Comment by kekatahi** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/17078

**Comment by tasherif-msft** [comment]
Hi @kekatahi we are incorporating this fix in our next release while also ensuring that we retry on an interrupted download. 
I will update you once the new packages are released (which should be tomorrow or early next week)

**Comment by tasherif-msft** [comment]
The fix has been merged here https://github.com/Azure/azure-sdk-for-python/commit/7e74cb317f916269c3e65b0f6691524769eacf87 it will be available in the release happening in the next couple of days!
