### ISSUE TITLE
[EventHubs] Finalize design on Idempotent Producer

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#16994]
### background

idempotent producer is targeted to solve the problem of sending duplicate messages and provide "exactly once delivery".
There has been a preview release for idempotent producer already which is available on the branch: https://github.com/Azure/azure-sdk-for-python/tree/feature/eventhub/idempotent-producer

- latest update: discussion postponed, currently no feature request from python users, more data is needed
- ~~This issue also has something to do with the StreamingProducer Design: https://github.com/Azure/azure-sdk-for-python/issues/18718.
We need to take both into account when making design decision.~~
- The buffered producer design is settled, it's a question of how the idempotency works for buffered mode.
- There is an ongoing email thread for discussion within the team, so need to have a cross-language agreement on the two concepts/whether to support it/overall structure.

#### Another design topic would be: Idempotent Producer naming of *_published_sequence_number property on different Objects

we have two prefixs on `*_published_sequence_number` on `EventDataBatch` and `EventHubProducerClient`, and we have multiple opinions on the naming:

```python
class EventDataBatch:
    def starting_published_sequence_number(self):
    # beginning/first/ or just published_sequence_number?
```

```
# `PartitionPublishingProperties` which is a dictionary returned by `EventHubProducerClient.get_partition_publishing_properties()`

dic['last_published_sequence_number']
# ending_published_sequence_number?

```

#### tasks

- sync up with Jesse/service team first, definite the scope

**Comment by jsquire** [comment]
@kashifkhan - If we can confirm there's a single option for "EnableIdempotentPartitions" that the buffered producer can use - then the design is final and we can kill this one.  😄
