### ISSUE TITLE
Installation failure of azure-keyvault-keys due to cryptography

### ISSUE THREAD

**Issue by singankit** [Azure/azure-sdk-for-python#17027]
- **azure-keyvault-keys**: 
- **latest**: 
- **Windows WSL**:
- **3.5.2**: 

**Describe the bug**
 Collecting azure-keyvault-keys
  Downloading https://files.pythonhosted.org/packages/a5/7f/a626704af6f0fb36bdc16397b49ab313a7e7a801ded5b43c6a74391f536a/azure_keyvault_keys-4.3.1-py2.py3-none-any.whl (248kB)
    100% |████████████████████████████████| 256kB 3.0MB/s
Collecting cryptography>=2.1.4 (from azure-keyvault-keys)
  Using cached https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-990u08gw/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ImportError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-990u08gw/cryptography/

**To Reproduce**
1. Run following command on WSL to install azureml-core package
      pip3 install azure-keyvault-keys

**Expected behavior**
azure-keyvault-keys package should get installed 

**Screenshots**
![image](https://user-images.githubusercontent.com/30610298/109730701-c237fc00-7b6e-11eb-8f05-c30eea57e4b1.png)

**Additional context**
Fails while installing cryptography.

**Comment by singankit** [comment]
This seems to be related to this issue : https://github.com/pyca/cryptography/issues/5771. Any guidance from azure python sdk team on how it should be handled ?

**Comment by scbedd** [comment]
Hey @singankit , thanks for the details! 

@Mossaka I believe you were working on the `azureml-core` package last I heard. Can you please help out @singankit ?

**Comment by singankit** [comment]
@scbedd I raised this issue to help understand if other azure python sdk's are running into this issue ? And what it the guidance around handling it from azure python sdk team. We have tried to pin cryptography version to <3.2 but that is causing other issues.

**Comment by singankit** [comment]
Issue seen with azure-keyvault-keys too

**Comment by annatisch** [comment]
Thanks @singankit - @mccoyp, @chlowell - have you seen this come up in any of our pipelines?

**Comment by mccoyp** [comment]
I can't recall having seen this come up in our pipelines. It does seem related to the issue you linked to, @singankit, in which case you may have to use a `cryptography` version < 3.4 (per the [changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#34---2021-02-07)). If using version < 3.2 is causing issues, have you tried `cryptography>3.2,<3.4`?

Also, I'm unable to install `cryptography` 3.4.6 with Python 3.5, possibly because Python 3.5 support was [dropped in 3.3](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#33---2020-12-08). Is it possible to use Python > 3.5?

**Comment by singankit** [comment]
This is the issue that has come up after cryptography added dependency on rust : https://github.com/pyca/cryptography/issues/5771. Users are also seeing similar issue on apline linux and WSL (Windows Subsystem Linux)

**Comment by chlowell** [comment]
I would refer anyone seeing this error first to [cryptography's installation docs](https://cryptography.io/en/latest/installation.html). The solution depends on the application and the platform it runs on. For its part, the Azure SDK tries not to restrict applications' flexibility in managing dependencies. In this case, for example, SDK libraries requiring cryptography (azure-keyvault-keys and others) will accept an older version that does not require Rust to build.

**Comment by singankit** [comment]
Thanks @chlowell for the info. However since azure-keyvault-keys does not pin cryptography to any upper bound and some recent versions of crytography do not work on some platforms, that would result in azure-keyvault-keys to not work on platforms not supported by cryptography . Is there any guidance from azure-sdk-python on how users can work around it as users might not know if this dependency.

**Comment by chlowell** [comment]
cryptography requires Rust to build, not at runtime, so this isn't exactly a platform support issue. For example, azure-keyvault-keys continues to work in applications running on Alpine. It will also `pip install` on Alpine provided cryptography is already installed, or available as a binary wheel, or the environment has the necessary build tools, etc. I think the best place to start is cryptography's installation doc because this is primarily a cryptography packaging issue and that doc describes solutions from that perspective.

**Comment by cartacioS** [comment]
@v-strudm-msft I noticed ML-AutoML was tagged on this post, but we could not find any correlation between the issue and AutoML. Can you please help us understand what is needed from AutoML team here?

**Comment by singankit** [comment]
Closing this issue since this is more about rust and its distribution based on platform that it is used on.
