### ISSUE TITLE
Access Token Missing or malformed when creating an app with python sdk

### ISSUE THREAD

**Issue by flixman** [Azure/azure-sdk-for-python#17056]
- **Package Name**:  
- **Package Version**: azure-graphrbac 0.61.1, adal 1.2.6
- **Operating System**: Centos 8.2
- **Python Version**:  3.6

**Describe the bug**
After authenticating with a devicecode, I cannot create an app.

**To Reproduce**
1. Obtain credentials using a device code.
```python
_context = adal.AuthenticationContext(_authority_uri, api_version=None)
    _code = _context.acquire_user_code(_resource_uri, _client_id)
    print(_code['message'])
    _mgmt_token = _context.acquire_token_with_device_code(_resource_uri, _code, _client_id)
    creds = AADTokenCredentials(_mgmt_token, _client_id)
```

2. Use those credentials to instantiate a GraphRbacManagementClient
```python
graphrbac_client = GraphRbacManagementClient(creds, TENANT_ID)
```

3. Create an app:
```python
app = graphrbac_client.applications.create({
            'available_to_other_tenants': False,
            'display_name': app_display_name,
            'identifier_uris': ['http://{}'.format(app_display_name)]
        })
```

**Expected behavior**
The app creation succeeds. Instead of that, I am obtaining the following exception:
```
Traceback (most recent call last):
  File "./request_sp.py", line 59, in <module>
    'identifier_uris': ['http://{}'.format(app_display_name)]
  File "/home/user/.local/lib/python3.6/site-packages/azure/graphrbac/operations/applications_operations.py", line 86, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: Access Token missing or malformed.
```

**Screenshots**

**Additional context**

**Comment by annatisch** [comment]
Thanks for the report @flixman!
You could try using the `adal` wrapper provided by `msrestazure`
```python
import adal
from msrestazure.azure_active_directory import AdalAuthentication

context = adal.AuthenticationContext(_authority_uri)
credential = AdalAuthentication(
    context.acquire_token_with_device_code,
    _resource_uri,
    _code,
    _client_id
)
graphrbac_client = GraphRbacManagementClient(credential, TENANT_ID)
```
You can find more information in the guide here:
https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd#authenticate-with-token-credentials-and-an-adal-context

**Comment by flixman** [comment]
@annatisch Thank you for you answer! However, now the code is just stalling in the call to applications.create. This what I am doing:

```python
def do_authentication():
    _authority_host = "https://login.microsoftonline.com"
    _authority_uri = "{}/{}".format(_authority_host, TENANT_ID)
    _context = adal.AuthenticationContext(_authority_uri)
    _code = _context.acquire_user_code('https://management.core.windows.net/', CLIENT_ID)

    credential = AdalAuthentication(
        _context.acquire_token_with_device_code,
        'https://graph.microsoft.com',
        _code,
        CLIENT_ID
    )
    return credential

# Perform authentication
credential = do_authentication()

# request the app display name
app_display_name = 'test'

# create the app
graphrbac_client = GraphRbacManagementClient(credential, TENANT_ID)
app = graphrbac_client.applications.create({
        'available_to_other_tenants': False,
        'display_name': app_display_name,
        'identifier_uris': ['http://{}'.format(app_display_name)]
    })
```

**Comment by annatisch** [comment]
Thanks @flixman - having it stall it certainly strange, to me that sounds like it might be waiting for the device to be authorized.
Is there any console output at all?
@lmazuel - do you recall what the device code auth flow looks like, and whether you would expect to see it waiting on something?

**Comment by flixman** [comment]
@annatisch @lmazuel There is no output at all. I would be expecting to get the devicecode sign in URL, with the device code, but... nothing.

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
