### ISSUE TITLE
Can't get size Standard_D32a_v3 from compute_client.resource_skus.list()

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-sdk-for-python#17087]
**Describe the bug**
I can't get size Standard_D32a_v3 from compute_client.resource_skus.list()
But use rest api can get, https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list

**Comment by LiliDeng** [comment]
@Drewm3

**Comment by annatisch** [comment]
Thanks for the report @LiliDeng!
Adding @changlong-liu and @00Kai0 for the compute SDK....

**Comment by 00Kai0** [comment]
@LiliDeng  , I have tried. This Api does not have problem. It seems like that `Standard_D32a_v3` has been replaced by `Standard_D32a_v4`.
![image](https://user-images.githubusercontent.com/26342317/110444712-51598c80-80f8-11eb-849b-48c1ab5f5431.png)

**Comment by LiliDeng** [comment]
@00Kai0 Thanks for looking into this, but the problem is we can deploy Standard_D32a_v3 from portal. and get sku info from rest api/powershell. why can't get it from python sdk?

**Comment by 00Kai0** [comment]
@LiliDeng , can you show more info like api request you tried?

**Comment by LiliDeng** [comment]
@00Kai0 
https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list
```
$ResourceGroupApiUri = "https://management.azure.com/subscriptions/$SubscriptionId/providers/Microsoft.Compute/skus?api-version=2019-04-01"
$Headers = @{}
$Headers.Add("Authorization","$($Token.token_type) "+ " " + "$($Token.access_token)")
$results = Invoke-RestMethod -Method Get -Uri $ResourceGroupApiUri -Headers $Headers
foreach($result in $results.value) { if($result.resourceType -eq "virtualMachines" -and $result.size -eq "D32a_v3" -and $result.locations -eq "westus2") {$temp=$result}}
```

```
resourceType : virtualMachines
name         : Standard_D32a_v3
tier         : Standard
size         : D32a_v3
family       : standardDAv3Family
locations    : {westus2}
locationInfo : {@{location=westus2; zones=System.Object[]; zoneDetails=System.Object[]}}
capabilities : {@{name=MaxResourceVolumeMB; value=819200}, @{name=OSVhdSizeMB; value=1047552}, @{name=vCPUs; value=32}, @{name=HyperVGenerations; value=V1}...}
restrictions : {}
```

**Comment by LiliDeng** [comment]
@00Kai0 Any update? thanks.
