### ISSUE TITLE
Better distinguish between classes that are and aren't supposed to be instantiated by user

### ISSUE THREAD

**Issue by cx-rafael** [Azure/azure-sdk-for-python#17086]
... In the [Custom Vision Python SDK docs](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-cognitiveservices-vision-customvision/3.1.0/index.html), specially for the training client. 

The [**models** module of the docs](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-cognitiveservices-vision-customvision/3.1.0/azure.cognitiveservices.vision.customvision.training.models.html#module-azure.cognitiveservices.vision.customvision.training.models) has classes that the user is supposed to be able to instantiate, and also others that are just meant for the SDK to return. For example: we as SDK users spent a lot of time trying to figure out if it was possible or not to specify the augmentation settings somewhere. We ended up going to the REST API docs to see the request parameters and finally conluded it was NOT possible (?)

Perhaps it's better to remove [entries like this one ](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-cognitiveservices-vision-customvision/3.1.0/azure.cognitiveservices.vision.customvision.training.models.html#module-azure.cognitiveservices.vision.customvision.training.models) because it shows a constructor and (at least at first sight) seems as if it's something the user can instantiate and specify, somewhere, somehow. The very least: throw the `Variables are only populated by the server, and will be ignored when sending a request.` sentence in the class description.

**Comment by annatisch** [comment]
Thanks @cx-rafael - this is really great feedback!
This is definitely something we should adopt a documentation convention for at a minimum.
@johanste - can we add something to the SDK guidelines about documenting which models are not intended for user instantiation?

**Comment by xiangyan99** [comment]
Could you help to try the new vision SDK and see if it works for you? https://pypi.org/project/azure-ai-vision/
