### ISSUE TITLE
ContainerClient exists method does not work with Container level SAS token.

### ISSUE THREAD

**Issue by varun-shahdadpuri** [Azure/azure-sdk-for-python#17094]
- **azure-storage-blob**: 
- **12.8.0**: 
- **macOS**:
- **3.8**: 

**Describe the bug**
ContainerClient exists method does not work with Container level SAS token.

Error - 
```
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation.
RequestId:9c51628a-d01e-0000-3135-119766XXXXX
Time:2021-03-04T20:29:12.8555087Z
ErrorCode:AuthorizationFailure
Error:None
```

**To Reproduce**
Call the below code with SAS token generated at the **container** level.
```
 container_client = ContainerClient(account_url='https://ABC.blob.core.windows.net/',
                                       credential='<SAS>',
                                       container_name='<CONTAINER_NAME>',
                                       max_block_size=1000000,
                                       max_single_put_size=1000000,
                                       min_large_block_upload_threshold=1000000,
                                       max_single_get_size=1000000,
                                       max_chunk_get_size=1000000,
                                       connection_timeout=2,
                                       timeout=5)
    print(container_client.exists())
```

**Expected behavior**
True/False should be returned.

**Comment by annatisch** [comment]
Thanks for the report @varun-shahdadpuri!
Adding @tasherif-msft and @xiafu-msft for the Storage SDK to investigate ASAP :)

**Comment by tasherif-msft** [comment]
Hi @varun-shahdadpuri, unfortunately `exists()` does not accept container sas. It would have to be an account level sas. 
This method uses `get_properties()` rest call under the hood which does not accept it. https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-directory-container-or-blob this has reference to which permissions allow for which operations.
We will improve the `exists()` docstrings to make this clearer.

Sorry for the inconvenience!

**Comment by annatisch** [comment]
Thanks @tasherif-msft - sounds like this is something that could be added to the docstring for the `ContainerClient.exists` method?

**Comment by varun-shahdadpuri** [comment]
Thanks for that explanation @tasherif-msft 
What is then the best way to determine if the container name (provided by an user) is valid and exists in a given storage account? 

Our customers provide us with their container level SAS tokens only.

**Comment by tasherif-msft** [comment]
@varun-shahdadpuri unfortunately you would need to have an account level SAS to find out if a container exists or not.

Sorry once again for the inconvenience

**Comment by goyash17** [comment]
@tasherif-msft : I am from @varun-shahdadpuri team. After going through ContainerClient class, i see that get_account_information() can be used with a container/blob level SAS. I tested and can confirm that it works successfully when container exists and returns "azure.core.exceptions.HttpResponseError: Operation returned an invalid status" error if container does not exist. can you review this analysis and provide feedback on this..

**Comment by goyash17** [comment]
In our usecase, customer can provide container level SAS or account level SAS. if we use get_account_information(), account level SAS works without a check on the container. We need to make a check on the existence of the container with the SAS. Is there a way to know from SAS if the SAS was generated at account level or container level.. if wee can get that pattern then we will have a way to introduce checks in our codebase.

**Comment by varun-shahdadpuri** [comment]
Can someone please validate our above analysis?

**Comment by tasherif-msft** [comment]
Hi @goyash17, regarding your first point, unfortunately that is not the case. when you call `get_account_info` the container name will get ignored. For example, if you have created `container1` and you generated a SAS token for it. You then proceeded to delete that container. If you were to call `get_account_information` on that container with that SAS token it will still pass and return you the account information. Even if you pass - let's say - a connection string as a credential and create a container client with a container name that does not exist then call `get_account_info` it would pass.

Regarding your second point, could you please reiterate? you're asking if it is possible to differentiate between a container SAS and an account SAS?

**Comment by goyash17** [comment]
@tasherif-msft : 1. Our customers will be providing container level sas, container name and storage account as input params. What should be our best bet to verify the container level sas? 
2. We have another question on Azure storage sdk version. We see that Azure storage sdk version 12.8.0 was released last week.. our pipeline was using 12.7.1 version before that. Will Microsoft be still supporting 12.7.1 version in production? If you can share some documentation around this, it will be helpful.

**Comment by tasherif-msft** [comment]
As you mentioned previously, service level SAS tokens contain `ss` which are the supported services (i.e could be b - blobs, f - fileshares, etc) sr for container SAS would be `c` and for blob SAS `b`.
So yea you can verify through the SAS string what kind of SAS token it is.

12.7.1 will remain supported :) all track 2 versions are supported (12.0.0+) - if we were to deprecate every version after release we'd be breaking a lot of people's production environments :stuck_out_tongue_winking_eye:

**Comment by goyash17** [comment]
@tasherif-msft thanks so much! it is helpful. I think you answered most of the queries.. Can you also check if you can recommend any best approach on this-
Our customers will be providing container level sas, container name and storage account as input params. What should be our best bet to verify with container level sas that the inputs provided by the user are valid?

**Comment by tasherif-msft** [comment]
if the SAS token is invalid the SDK will throw a `ClientAuthenticationError` - this exception will also contain further details on why the SAS token failed (i.e i twas malformed or expired etc)
Let me know if you have any further questions!

**Comment by goyash17** [comment]
For container level SAS, which method from SDK should we be using? We know that container.exists() do not work for container level SAS.

**Comment by tasherif-msft** [comment]
You cannot check the existence of a container if you only have a container sas.
