### ISSUE TITLE
Add SecretProperties.managed property

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#17129]
A secret has a "managed" attribute indicating whether it's managed by Key Vault, i.e. associated with a certificate. SecretProperties expects this attribute but doesn't expose it: https://github.com/Azure/azure-sdk-for-python/blob/65e2f5db822c0f8162911cfb8ab9676298eda78c/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_models.py#L29

**Comment by mccoyp** [comment]
Resolved by https://github.com/Azure/azure-sdk-for-python/pull/22368
