### ISSUE TITLE
[text analytics] what happens with cateogires_filter + domain_filter

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#17137]
Talk about where we should document this once we fully know the service behavior

**Comment by kristapratico** [comment]
It is described in detail on this service [docs page](https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/personally-identifiable-information/concepts/entity-categories) which entities are returned via categories_filter and domain_filter="phi" (or both). Will update the link in our SDK docs.
