### ISSUE TITLE
[DNS] azure-mgmt-dns doesn't have Track 2 release

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#17148]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
`azure-mgmt-dns` has not received a new release since 2019. Projects that need to interact with resources in different Tracks are hard to maintain.

https://pypi.org/project/azure-mgmt-dns/#history

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by annatisch** [comment]
Thanks @logachev!
Adding @msyyc to comment on the status of this mgmt package release :)

**Comment by msyyc** [comment]
@00Kai0 Could you help to release track2 version for azure-mgmt-dns?

**Comment by 00Kai0** [comment]
Track2 preview sdk for DNS is ready: https://pypi.org/project/azure-mgmt-dns/8.0.0b1/

**Comment by jsntcy** [comment]
Closed as track 2 SDK is released.
