### ISSUE TITLE
[EventHubs] Add common argument for service operations within checkpointstore sdk

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#17154]
background: recently there is a customer support ticket that the customer find one partition consumer stops receiving from a specific partition. The investigation result turns out to be that the `update_checkpoint` didn't get a response from the storage sdk leading to the processor got stuck.

how to fix: the situation may happen due to transient error network, we should expose the configs (timeout) for service http request (like `update_checkpoint` in the checkpointstoreblob as per our python guideline: https://azure.github.io/azure-sdk/python_design.html#python-client-service-args

Name | Description | Applies to | Notes
-- | -- | -- | --
timeout | Timeout in seconds | All service methods |   |  
headers | Custom headers to include in the service request | All requests | Headers are added to all requests made (directly or indirectly) by the method. |  
continuation_token | Opaque token indicating the first page to retrieve. Retrieved from a previous Paged return value. | list operations. |   |  
client_request_id | Caller specified identification of the request. | Service operations for services that allow the client to send a client-generated correlation ID. | Examples of this include x-ms-client-request-id headers. | The client library must use this value if provided, or generate a unique value for each request when not specified.
response_hook | callable that is called with (response, headers) for each operation.

the methods in azure-eventhub-checkpointstore(-aio) are service operations which perform requests to the storage service.
So the guideline should apply to those operations as well.

**Important**:
- [x] discuss with arch on
  - [x] whether the guideline applies to APIs in azure-eventhub-checkpointstore(-blob): **YES**
  - [x] whether we should add **kwargs to the APIs in checkpointstore protocol defined in azure-eventhub: **YES**

**Impacted APIs**
- azure-eventhub
  - All methods on CheckpointStore class: list_ownership, claim_ownership, update_checkpoint, list_checkpoints
  - PartitionContext.update_checkpoint
- azure-eventhub-checkpointstoreblob(and aio): All methods on CheckpointStore class

**Add note in changelog**
- CheckpointStore now supports taking kwargs on all operations
- PartitionContext.update_checkpoint now supports taking kwargs.

Future improvements:
1. default timeout for those operations in CheckpointStoreBlob
2. Docstring for storage blob settings on client-level configurations for CheckpointStoreBlob

**Comment by yunhaoling** [comment]
Things to call out if users have implemented their own CheckpointStore:

Adam: "if users have implemented their checkpointstore which doesn’t take kwargs, then in some place we might need to handle TypeError when passing kwargs to checkpointstore methods which are called internally. E.g., PartitionContext.update_checkpoint would call self._checkpoint_store.update_checkpoint(checkpoint)"

Anna: "If someone had already implemented their own CheckpointStore - will they now get pylint errors when we change the AbstractBaseClass? Worth looking into whether we might be breaking peoples CI here"

**Comment by swathipil** [comment]
re Anna's comment: extending CheckpointStore after updating methods results in the following pylint errors:
```
W0221: Parameters differ from overridden 'list_ownership' method (arguments-differ)
W0221: Parameters differ from overridden 'claim_ownership' method (arguments-differ)
W0221: Parameters differ from overridden 'update_checkpoint' method (arguments-differ)
W0221: Parameters differ from overridden 'list_checkpoints' method (arguments-differ)
```
