### ISSUE TITLE
[text analytics] follow up on model version + healthcare endpoint

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#17160]
currently healthcare endpoint doesn't respect model version query param, only uses latest. Have filed an [issue](https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/9479280) for this on the service side. Follow up, and hopefully remove the issue comments from the sdk

**Comment by kristapratico** [comment]
Assaf answered this one:

> During the private preview we don't support older model versions. We only upgrade the latest and immediately deprecate the older models. During GA this behavior will change. 

I think it should be okay to remove the comment since we will be GA forward?
