### ISSUE TITLE
[formrecognizer] Invalid url for custom forms returns different error codes for labeled/unlabeled

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#17194]
Tests in question: https://github.com/Azure/azure-sdk-for-python/pull/17125/files#diff-06fcce66b28f493a25f609a7cf0d875190e14f54d7459c60c342d6bf9bd6fb4cR130

**Comment by kristapratico** [comment]
Checked with service team. Apparently a release was pushed that included some unintended behavior for bad URL input. 

The expected behavior (which is unchanged from how it was before):

200 on POST, 400 on GET with error code/message: 2003 - "Failed to download image from input URL."

**Comment by kristapratico** [comment]
- with no labels still returns error code 2003 
- with labels returns error code 2001

```
"errors": [
  {
    "code": "2001",
    "message": "Failed to download the image from the submitted URL. The URL may either be invalid or the server hosting the image is experiencing some technical difficulties."
  }
]
```

**Comment by catalinaperalta** [comment]
Closing now since these tests were refactored/cleaned up during the MQ and the test proxy migration.
