### ISSUE TITLE
Preview Packages Docs Updates Are Publishing w/out Preview Tag

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#17212]
Also failing [CI Build](https://dev.azure.com/azure-sdk/public/_build/results?buildId=774108&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=036ed663-514a-59f3-0c88-23d2cf182147&l=13).

Need to get this fixed. 

@danieljurek  can you please double check the onboarded packages [here](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/ci-configs/packages-preview.json).

**Comment by danieljurek** [comment]
@scbedd -- PR to add versions back in: https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1263
