### ISSUE TITLE
[Azure.Storage Tables] Azure Storage Tables Track 2 SDK

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#17233]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Azure Storage Tables used to have separate SDK. With the Track 2, is it considered deprecated now or will it be updated?

This is the repo: https://github.com/Azure/azure-cosmos-table-python

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yunhaoling** [comment]
thanks @logachev for reaching out.

We currently have the [azure-data-tables](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/tables/azure-data-tables) SDK in preview which might be the one you're looking for.
let me loop in @seankane-msft for the Table SDK to give more information on this.

@lmazuel -- do we own this repo: https://github.com/Azure/azure-cosmos-table-python? looks like that repo is not maintained, should we take some action like deprecation, pointing to the mono repo in readme etc?

**Comment by lmazuel** [comment]
Hey @logachev. We would need to confirm with the service team that owns that repo, one thing for sure is all effort are done on this new package that will be GA soon (April I believe). Give me a few more days to get an official answer.

**Comment by logachev** [comment]
@yunhaoling @lmazuel Thank you! I think this is what I was looking for.. Will double check today & close the issue if it is.

I agree, it would be good to point people to the new library from the old repo\pypi.

**Comment by seankane-msft** [comment]
@logachev the track 2 library for Azure Storage Tables will be released this upcoming week. I will update here after it is published to PyPi.

**Comment by seankane-msft** [comment]
@logachev the library has been released for GA. You can install it with `pip install azure-data-tables`. If you have any further questions please open an issue!
