### ISSUE TITLE
[EventHubs] Drop 3.5 support

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#17236]
This applies for the following up three sdks:

- azure-eventhub
- azure-eventhub-checkpointstoreblob
- azure-eventhub-checkpointstoreblob-aio

tasks:
- [ ] add note in changelog:
    - `This version and all future versions will require Python 2.7 or Python 3.6+, Python 3.5 is no longer supported.`
- [ ] update readme (3.5 -> 3.6)
- [ ] update the classifiers in setup.py to drop 3.5
- [ ] update sample/readme if needed
- [ ] update migration guide if needed
- [ ] check whether to drop 3.5 support for uamqp

**Comment by swathipil** [comment]
update version + add note that version 5.4.0 will be from 5.3.1, not 5.4.0b1

**Comment by swathipil** [comment]
looks like 5.4.0b1 already dropped 3.5
