### ISSUE TITLE
azure-storage-blob==12.8.0 - invalid shared access signature with azurite emulator

### ISSUE THREAD

**Issue by kuba-lilz** [Azure/azure-sdk-for-python#17231]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.8.0   
- **Operating System**: OSX
- **Python Version**: 3.8

**Describe the bug**
Share access signatures generated for azurite container (version `arafato/azurite:2.6.5`) are invalid.
Shared access signatures generated for real Azure storage services are valid.

**To Reproduce**
1. Start azurite docker container, create blob container (e.g. `static-data`) and put some data into it (e.g. `kitty_01.jpg`)

2. Run py.test on following code
```python
import datetime

import azure.storage.blob
import requests


def test_share_access_signature_with_emulator():

    emulated_storage = {
        "account_name": "devstoreaccount1",
        "account_key": "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==",
        "connection_string": "AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;",
        "container": "static-data",
        "blob": "kitty_01.jpg"
    }

    storage = emulated_storage

    sas_token = azure.storage.blob.generate_account_sas(
        account_name=storage["account_name"],
        account_key=storage["account_key"],
        resource_types=azure.storage.blob.ResourceTypes(object=True),
        permission=azure.storage.blob.AccountSasPermissions(read=True),
        start=datetime.datetime.now() - datetime.timedelta(days=10),
        expiry=datetime.datetime.now() + datetime.timedelta(days=10)
    )

    blob_service_client = azure.storage.blob.BlobServiceClient.from_connection_string(
        storage["connection_string"], credential=sas_token)

    blob_client = blob_service_client.get_blob_client(container=storage["container"], blob=storage["blob"])

    assert requests.get(blob_client.url, timeout=5).status_code == 200
```

**Expected behavior**
blob_client.url should yield a valid url that can be used to access data.
Instead invalid url is generated, and accessing it yields `AuthenticationFailed` response.

**Screenshots**

**Additional context**
Accessing the same data with shared access signature generated from Microsoft Azure Storage Explorer works without problems.

Sample url generated by azure-storage-blob==12.8.0:
'http://127.0.0.1:10000/devstoreaccount1/static-data/kitty_01.jpg?st=2021-02-28T15%3A59%3A44Z&se=2021-03-20T15%3A59%3A44Z&sp=r&sv=2020-06-12&ss=b&srt=o&sig=GxIh4Eq8isrZOidgOhubhAd0MjiiNeLook%2F8lYwjXMo%3D'

Sample url generated by  Microsoft Azure Storage Explorer:
'http://127.0.0.1:10000/devstoreaccount1/static-data/kitty_01.jpg?sv=2018-03-28&st=2021-03-09T06%3A45%3A00Z&se=2021-03-11T06%3A45%3A09Z&sr=b&sp=r&sig=27dwNA9F8EMTG4m2husfsB4ltFSdvtVFTz9GleEB3Lo%3D'

**Comment by kuba-lilz** [comment]
I tried with `mcr.microsoft.com/azure-storage/azurite:3.11.0` container, and there shared access signature generated by `azure-storage-blob==12.8.0` works.

**Comment by yunhaoling** [comment]
thanks @kuba-lilz for reaching out, we'll investigate asap.

adding @xiafu-msft for the storage SDK to take a look :)

**Comment by xiafu-msft** [comment]
Hi @kuba-lilz 
Thanks for reaching out.
Actually it's not an SDK problem. The problem happened because the azurite emulator is using a specific service version, while SDK keeps updating the service version it's trying to call to make sure user can access the most recently added feature.
probably you can try loose mode and see if that can resolve the problem
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=/azure/storage/blobs/toc.json#loose-mode

**Comment by kuba-lilz** [comment]
@xiafu-msft 
Thank you for your reply!

Running `arafato/azurite:2.6.5` with `/opt/azurite/bin/azurite --blobHost 0.0.0.0 --loose` didn't change the result though.
It still rejects calls to blob endpoint that includes SAS with 403 error.

**Comment by xiafu-msft** [comment]
Hi @kuba-lilz 
can you try to skip api version check like this and see if that helps https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=/azure/storage/blobs/toc.json#skip-api-version-check 

Feel free to let me know if it doesn't help!

**Comment by kuba-lilz** [comment]
@xiafu-msft 

Unfortunately adding `--skipApiVersionCheck` doesn't solve the problem - container still returns 403  when accessing blob usins shared access signature.

**Comment by xiafu-msft** [comment]
Hi @kuba-lilz 

Here's the response from @XiaoningLiu who is the owner of azurite emulator.
```
According to what customer said, "I tried using mcr.microsoft.com/azure-storage/azurite:3.11.0 as azure storage emulator instead, and there shared access signature generated by azure-storage-blob==12.8.0 works.". 

Azurite V3 works with Python SDK 12.8.0. 
arafato/azurite:2.6.5 is legacy Azurite V2 which will not get features update. Expected not work with latest SAS.

Our recommendation is customers should switch from V2 to V3. They can open issues to Azurite repo in case any questions during migration from V2 to V3.
```

**Comment by kuba-lilz** [comment]
@xiafu-msft 
So the problem is that CORS settings are broken in Azurite V3, but they work in arafato/azurite:2.6.5

Please see this issue for details
https://github.com/Azure/Azurite/issues/55
Maintainers closed the issue, but it is in fact not resolved.

 The gist of this is that:
- Azurite V3 doesn't support CORS settings, so I can't switch to it from arafato/azurite:2.6.5 
- arafato/azurite:2.6.5 doesn't work with  azure-storage-blob==12.8.0 (or anything above 1.5.0 as far as I can tell), so I can't update azure-storage-blob
- I'm stuck on using outdated azurite and azure-storage-blob as a result, even though I'm only using common functionality - CORS and SAS tokens

Well, I understand that is outside of your scope.
I guess I'll try banging at https://github.com/Azure/Azurite/ maintainers again, maybe this time they won't ignore me.
Thank you for your replies on this issue.

**Comment by XiaoningLiu** [comment]
Azurite V3 does support CORS settings. Please tell us if any issues during CORS configuration.

Best,
Xiaoning
________________________________

**Comment by kuba-lilz** [comment]
Same code works just fine with real Azure storage account and arafato/azurite:2.6.5.
Here's the code, run with `python=3.8` and `azure-storage-blob==1.5.0`

```python
cors_rule = azure.storage.common.models.CorsRule(
    allowed_origins=["0.0.0.0:*"], allowed_headers="*",
    allowed_methods=["GET"], exposed_headers="*", max_age_in_seconds=100)

blob_storage.set_blob_service_properties(
    cors=[cors_rule])
```

and container accepts the request with response status `202`, but when we try to load blobs into html canvas object, then CORS errors are thrown in the browser.

I opened a new issue over at Azurite repository, here are the details:
https://github.com/Azure/Azurite/issues/731

**Comment by xiafu-msft** [comment]
@XiaoningLiu 
Any updates?

**Comment by kuba-lilz** [comment]
@xiafu-msft 
Maybe I'll chip in with advice I got over at https://github.com/Azure/Azurite/issues/731
Setting `allowed_origins=["*"]` instead of `allowed_origins=["0.0.0.0:*"]` worked for me with Azurite V3 container.

This means that for task at hand I can switch from azurite V2 to V3, where problem for which I opened this issue doesn't exist.
So I suppose from my point of view the issue can be closed.
