### ISSUE TITLE
Generated SDK weird type: Components1Jq1T4ISchemasManagedserviceidentityPropertiesUserassignedidentitiesAdditionalproperties

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#17254]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Some SDKs Models have a type with this name: `Components1Jq1T4ISchemasManagedserviceidentityPropertiesUserassignedidentitiesAdditionalproperties`

https://github.com/Azure/azure-sdk-for-python/blob/2d32ffe99da7194ae721e209137025da220206d4/sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/__init__.py#L34

I guess this is some typo in the REST specs or issue with generator?

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yunhaoling** [comment]
Thanks for the feedback, we'll investigate asap.
adding @msyyc who could comment further on the mgmt libraries.

**Comment by msyyc** [comment]
@lmazuel It seems a known issue. Could you help to confirm it?

**Comment by msyyc** [comment]
@yunhaoling Please provide more detailed info :
![image](https://user-images.githubusercontent.com/70930885/111098223-f69fb500-857d-11eb-812b-0d3c04d59c87.png)

**Comment by logachev** [comment]
@msyyc It is an issue with a bunch of different SDKs. You can search for this string in this repo to get all entries.. This might be the easiest way.

**Comment by logachev** [comment]
/unresolve

Not sure why it was even marked as resolved. Now there are 2 entries that are clearly some generator/data issue

https://github.com/Azure/azure-sdk-for-python/blob/84a9eb69dc38332434645d6556703716ff549fa7/sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/__init__.py#L45

**Comment by xiangyan99** [comment]
@RAY-316 I still see it in latest azure-mgmt-cosmosdb 7.0.0b5. Please double check.

**Comment by msyyc** [comment]
Hi @logachev We find the cause is that there is too deep nest in swagger: https://github.com/Azure/azure-rest-api-specs/blob/6c065f8439e6d9cd02bf4f8268fae7f86a5f0fa9/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2022-05-15-preview/managedCassandra.json#L1083-L1170. We will rename it in swagger and release a new version. Thanks for the patience!

**Comment by msyyc** [comment]
There is no weird type in latest version:  https://pypi.org/project/azure-mgmt-cosmosdb/8.0.0b2/
