### ISSUE TITLE
upload_blob: KeyError: 'error_code'

### ISSUE THREAD

**Issue by disssid** [Azure/azure-sdk-for-python#17266]
Platform - Azure Function
Operating System - Linux
Azure SDK for Python - 12.8.0 
Python - 3.7.5
Runtime - 3.0

One of our teammate had written this code and was working fine till Feb,27 2021.  We added a new Azure Function (without any change to this function) and deployed it on Mar,04 2021 and ever since then this code breaks down with a `KeyError`. Is this a change as part of your update to the SDK?

```
upload_response= blob_client.upload_blob(data, overwrite=True)

if upload_response['error_code'] == None
 do something
else
 do something
```
```
[3/10/2021 2:45:38 PM] Executed 'Functions.HttpTrigger_exceltocsv' (Failed, Id=71ce46fa-b768-45a1-8ac9-ed393b5b18b4)
[3/10/2021 2:45:38 PM] System.Private.CoreLib: Exception while executing function: Functions.HttpTrigger_exceltocsv. System.Private.CoreLib: Result: Failure
Exception: KeyError: 'error_code'
```
Operating System - Windows 10
Azure SDK for Python - 12.8.0 
Python - 3.7.5
Runtime - 3.0

I ran the code locally to find that upon a successful execution the `upload_blob` response does not contain the `error_code` but there is an `ErrorCode` in case of an error as below,
```
Function execution failed.File Uploaded Failed .The specified blob already exists.
RequestId:3a41f9d4-a01e-0041-78bf-1514d9000000
Time:2021-03-10T15:10:23.8246867Z
ErrorCode:BlobAlreadyExists
Error:None
```
Please let me know if you need any further information.

Thank You

**Comment by yunhaoling** [comment]
thanks for the feedback! we'll investigate asap.
looping in @xiafu-msft who could provide further help on the storage blob SDK.

**Comment by tasherif-msft** [comment]
Hi @disssid, 
Generally if there is an exception/error thrown when attempting to perform an operation, it will raise.
When this happens you can catch the exception, for example:

```
try:
    upload_response= blob_client.upload_blob(data, overwrite=True)
    [do something - if it passes]
except HttpResponseError as e:
    print(e.error_code)
    [do something - it failed]
```
Let me know if this solves your problem.

Thanks

**Comment by disssid** [comment]
Thank you for the response. This is how I redid the code, but the earlier code was working fine up until Feb 27th. This is just one instance where I found this issue, so wanted to check with you guys. I'll go through the other Azure Functions as well to check if they've used the key `error_code` anywhere on a successful operation.

Thank you once again for your help
