### ISSUE TITLE
x-ms-authorization-auxiliary header should be redacted

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#17271]
**Is your feature request related to a problem? Please describe.**

`x-ms-authorization-auxiliary` header's value is logged by `NetworkTraceLoggingPolicy`, because only `authorization` header is redacted.
 
https://github.com/Azure/azure-sdk-for-python/blob/2e6022b38bb65e4e42876605456618c4e6341aaf/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L283
  
Even though `x-ms-authorization-auxiliary` is not supported by Track 2 SDK yet (https://github.com/Azure/azure-sdk-for-python/issues/8313), Azure CLI is manually adding this header to support cross-tenant auth (https://github.com/Azure/azure-cli/pull/16797).

**Describe the solution you'd like**

Make an `ARMNetworkTraceLoggingPolicy`, just like `ARMHttpLoggingPolicy`. SDKs should use `ARMNetworkTraceLoggingPolicy` instead of `NetworkTraceLoggingPolicy`, so that `x-ms-authorization-auxiliary` can also be redacted.

`NetworkTraceLoggingPolicy` is created in `xxxClientConfiguration`, like `NetworkManagementClientConfiguration` (which belongs to a specific SDK): 

https://github.com/Azure/azure-sdk-for-python/blob/3bf56880b6b8cc8ca7d783c96e4a5165eeb0212c/sdk/network/azure-mgmt-network/azure/mgmt/network/_configuration.py#L59

We should change this line to 

```py
self.logging_policy = kwargs.get('logging_policy') or policies.ARMNetworkTraceLoggingPolicy(**kwargs)
```

but this of course requires all existing SDKs to be regenerated.

**Describe alternatives you've considered**

Add the redacting `x-ms-authorization-auxiliary` behavior directly to `NetworkTraceLoggingPolicy` from `azure-core`.

**Comment by jiasli** [comment]
Another possible solution:

1. Keep all headers except `Authorization`, so that there is no breaking change and it is by default secure. `x-ms-authorization-auxiliary` is Azure ARM specific, so keep it.

2. Then expose the blocklist to the caller, so that Azure CLI can [make a config](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables) like:

    ```
    az config set logging.incude_credential=True
    ```

    Currently it is hard coded:
    https://github.com/Azure/azure-sdk-for-python/blob/2e6022b38bb65e4e42876605456618c4e6341aaf/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L283-L284

3. If so, CLI can simply set the blocklist to `[]`. If not, CLI can also simply set the blocklist to `['Authorization', 'x-ms-authorization-auxiliary']`

In this way, users can still log sensitive headers explicitly.

**Comment by xiangyan99** [comment]
As we discussed offline, this is by design.
