### ISSUE TITLE
Can't get the job output of the runbook using python sdk

### ISSUE THREAD

**Issue by acorn20180214** [Azure/azure-sdk-for-python#17276]
- **Package Name**:   azure.mgmt.automation
- **Package Version**:    1.0.0b1
- **Operating System**:  win10
- **Python Version**:   3.7.3 / 3.6.7 / any

**Describe the bug**
We're using azure python SDK to get the output of the runbook hosted on azure automation service and it gives an error below:

Traceback (most recent call last):
  File ".\manage_runbook.py", line 43, in <module>
    main()
  File ".\manage_runbook.py", line 39, in main
    job_name='a2296b6d-9fb6-44c1-92a1-34190ffabc64'
  File "C:\Python36\lib\site-packages\azure\mgmt\automation\operations\_job_operations.py", line 108, in get_output
    deserialized = self._deserialize('IO', pipeline_response)
  File "C:\Python36\lib\site-packages\msrest\serialization.py", line 1233, in __call__
    return self._deserialize(target_obj, data)
  File "C:\Python36\lib\site-packages\msrest\serialization.py", line 1272, in _deserialize
    return self.deserialize_data(data, response)
  File "C:\Python36\lib\site-packages\msrest\serialization.py", line 1457, in deserialize_data
    obj_type = self.dependencies[data_type]
KeyError: 'IO'

**To Reproduce**

`import os
import io

from azure.identity import DefaultAzureCredential
from azure.mgmt.automation import AutomationClient
from azure.mgmt.resource import ResourceManagementClient

def main():

    SUBSCRIPTION_ID = os.environ.get("SUBSCRIPTION_ID", None)
    GROUP_NAME = "acornautomation"
    RUNBOOK = "AzureAutomationTutorialPython2"
    AUTOMATION_ACCOUNT = "acornautomation"

    automation_client = AutomationClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID
    )

    job = automation_client.job.get(
        GROUP_NAME,
        AUTOMATION_ACCOUNT,
        "a2296b6d-9fb6-44c1-92a1-34190ffabc64"
    )
    print("Get job:\n{}".format(job))
    print("Job ID:\n{}".format(job.job_id))
    print("Job Name:\n{}".format(job.name))

    automation_account = automation_client.job.get_output(
        resource_group_name=GROUP_NAME,
        automation_account_name=AUTOMATION_ACCOUNT,
        job_name='a2296b6d-9fb6-44c1-92a1-34190ffabc64'
    )

if __name__ == "__main__":
    main()`

pip freeze:
adal==1.2.2
azure-common==1.1.15
azure-core==1.12.0
azure-functions==1.5.0
azure-identity==1.5.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.1.0
azure-keyvault-keys==4.1.0
azure-keyvault-secrets==4.1.0
azure-mgmt-automation==1.0.0b1
azure-mgmt-core==1.2.2
azure-mgmt-media==1.1.1
azure-mgmt-resource==16.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.3.1
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cryptography==2.9.2
dataclasses==0.8
filelock==3.0.12
Flask==1.1.2
future==0.18.2
idna==2.9
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.2
joblib==0.17.0
json-utils==0.2
MarkupSafe==1.1.1
msal==1.10.0
msal-extensions==0.3.0
msrest==0.6.13
msrestazure==0.5.0
numpy==1.19.3
oauthlib==3.1.0
packaging==20.4
pandas==1.1.4
portalocker==1.7.1
protobuf==3.14.0
pycparser==2.20
PyJWT==1.7.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.4
pywin32==300
regex==2020.11.13
requests==2.23.0
requests-oauthlib==1.3.0
sacremoses==0.0.43
sentencepiece==0.1.91
six==1.14.0
tokenizers==0.9.3
torch==1.7.0+cpu
tqdm==4.53.0
transformers==3.5.1
typing-extensions==3.7.4.3
urllib3==1.25.2
virtualenv==16.6.0
Werkzeug==1.0.1

**Expected behavior**
we can get the output successfully using azure python SDK

**Screenshots**

**Additional context**

**Comment by acorn20180214** [comment]
@00Kai0  as discussed,  can you please take a look at this?   appreciate your help very much!

**Comment by 00Kai0** [comment]
Hi @acorn20180214 ，the version 1.0.0 is based on [2017-preview]( https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/preview/2017-05-15-preview/job.json#L85), codegen didn't generate this `file` correctly.
It has been changed in [2019](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/stable/2019-06-01/job.json#L85).
We can release a new versio of sdk to fix your issue.

**Comment by jaspkaur28** [comment]
PR merged.
