### ISSUE TITLE
[translation] add source_document_url to DocumentStatusResult

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#17288]
The service has started returning a property called `source_path` that links back to the source document on `DocumentStatusResult`. We should expose this in the client library and call it `source_document_url`

**Comment by mohamedshabanofficial** [comment]
can't find the `source_path` on `DocumentStatusDetail` generated model only the `path` attr
should i add it manually?!

**Comment by kristapratico** [comment]
Ah right, we'll need to wait until the swagger is updated to include `source_path` and then regenerate on it to get this new field. Let me check on that.

**Comment by mohamedshabanofficial** [comment]
we need to update the **samples** once code re-regeneration is done! 
this is in order to use `source_path` instead of `translated_document_url` in some cases 
as current code samples conflate the two!

**Comment by kristapratico** [comment]
Very true! I'm going to open an issue to update samples.

**Comment by kristapratico** [comment]
completed in #17719
