### ISSUE TITLE
VNET Resource group is not under VM Resource group

### ISSUE THREAD

**Issue by bharathmakawana** [Azure/azure-sdk-for-python#1728]
Hi Y' All,

I was just trying to provision an VM in azure, but it seems the VNET resource group is not under the VM resource group and because of which I couldn't proceed ahead.

The current ansible version is ansible 2.3.1.0 and I get the below error...

TASK [Create VM] *******************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error fetching network interface NIC_Ansibletest - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Network/networkInterfaces/NIC_Ansibletest' under resource group 'VM-RESOURCE-GROUP-NAME' was not found."}
        
Note: Both VNET and VM resource group are different

**Comment by lmazuel** [comment]
Hi @bharathmakawana 
Please open Ansible issues in the Ansible repo:
https://github.com/ansible/ansible/issues

If I'd guess your issue, I would say that you probably took a sample playbook and forgot to replace `VM-RESOURCE-GROUP-NAME` with your wanted resource group name.

Thanks,

**Comment by bharathmakawana** [comment]
Thanks for your reply, but that is not the case here.

**Comment by lmazuel** [comment]
What "is not the case"? You're definitely using Ansible, this is not the correct repo. And my last sentence as I said is a "guess", but according to the message, there is definitely a parameter somewhere where the value is `VM-RESOURCE-GROUP-NAME`, since this is a templated message.
But again, I was just trying to help, this is an Ansible issue.
Thank you.

**Comment by bharathmakawana** [comment]
I highly appreciate your response, but the case here is VNET resource group and VM resource group are different and even after giving the correct VM-RESOURCE-GROUP-NAME.

I get the error stating that "VNET resource group is not under the VM resource group"

**Comment by lmazuel** [comment]
Again, this is an Ansible issue, please open an issue on the Ansible repo:
https://github.com/ansible/ansible/issues

Thank you,
