### ISSUE TITLE
[Azure Storage Queue] receive_messages infinite loop

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#17301]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
It is not a bug, more like really unexpected behavior.

https://github.com/Azure/azure-sdk-for-python/blob/1ca37b47d156ed76922835e7097ee55396bf2fc5/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L546

Azure Storage Queue `receive_messages` doesn't have a way to define maximum number of messages to receive. If it is ever used against the queue that constantly gets new messages, it will just stuck in an infinite loop because it will try to query extra messages.

If it runs in a serverless environment, where execution is limited by time, it will lead to potential data loss when function is killed.

There is a workaround for this, but it is not obvious from the method description that it will continuously look for messages instead of dequeuing all available or X.. 

```
messages = queue_service.receive_messages()

try:
    return [m for m in messages.by_page().next()]
except StopIteration:
    return []
```

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yunhaoling** [comment]
thanks @logachev for reaching out! we'll investigate it asap.
adding @xiafu-msft who could further comment on the usage of the storage queue APIs.

**Comment by tasherif-msft** [comment]
Hi @logachev, this is a good catch our rest API actually supports passing a max number of messages to retrieve. I will put out a PR to fix up our kwargs so that users can pass a set number of messages.

Thank you.

**Comment by tasherif-msft** [comment]
@logachev I will be putting out a PR to resolve this soon!

**Comment by logachev** [comment]
@tasherif-msft Thank you!

As a "feature request", ideally if it allowed to specify not only # of messages, but also # of pages to have behavior, similar to the original SDK when we do  a single query to retrieve no more than X messages vs multiple queries until queue is empty or we received X messages.

**Comment by xiafu-msft** [comment]
just an update, I will sync up with @tasherif-msft about the pr

**Comment by tasherif-msft** [comment]
I have just created a PR https://github.com/Azure/azure-sdk-for-python/pull/18783 it is still a work in progress.
Just to clarify, you're also asking for a feature where the user would limit the number of pages returned?

**Comment by amishra-dev** [comment]
The pull request is still being worked on @xiafu-msft / @annatisch can we get this Pr merged?

**Comment by amishra-dev** [comment]
@tasherif-msft ping

**Comment by amishra-dev** [comment]
Was this merged @tasherif-msft/ @jalauzon-msft ?

**Comment by jalauzon-msft** [comment]
@amishra-dev, it looks like this needs more investigation to come up with the right solution. I will investigate.
