### ISSUE TITLE
Importing SendSmsOptions returning error

### ISSUE THREAD

**Issue by lav13enrose** [Azure/azure-sdk-for-python#17328]
- **Package Name**:  azure-communication-sms
- **Package Version**:  1.0.0b6
- **Operating System**: Ubuntu on Windows Linux  Subsystem
- **Python Version**:  2.7

**Describe the bug**

**To Reproduce**
1.  Importing SendSmsOptions
2.  Returning "ImportError: cannot import name SendSmsOptions"

**Expected behavior**
When using azure-communication-sms==1.0.0b4 everything running fine

**Screenshots**
![image](https://user-images.githubusercontent.com/50060785/111065676-d0cecd80-84f5-11eb-809a-98d87bd61a52.png)

**Additional context**
Explain please

**Comment by catalinaperalta** [comment]
Thanks for reaching out @lav13enrose! We'll investigate ASAP. 
Adding @turalf who can comment more on this issue.

**Comment by annatisch** [comment]
Thanks @lav13enrose!
cc @lsundaralingam

I don't believe `SmsSendOptions` is still a type in the Python SDK. Can you please describe what you're using it for so we can get you the latest code to achieve it?
If you could also give us a link to any samples you saw that use this object so we can update them, that would be awesome :)

cc

**Comment by lsundaralingam** [comment]
Hi @lav13enrose,

As Anna mentioned, ```SendSmsOptions``` is not a type anymore, so there's no need to import it. You can use kwargs instead to pass in optional parameters like ```enable_delivery_report``` and ```tag```. For examples, please see the samples [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/communication/azure-communication-sms/samples/send_sms_to_multiple_recipients_sample.py).

I'm closing this issue, but feel free to reopen if anything comes up.
