### ISSUE TITLE
Add Keys/Secret information of a Keyvault when querying a Key Vault with KeyVaultManagementClient

### ISSUE THREAD

**Issue by xnkevinnguyen** [Azure/azure-sdk-for-python#17329]
**Is your feature request related to a problem? Please describe.**
There is currently no way of getting programatically with the mgmt api the keys and secrets information. (Please inform me if I have overlooked something).

**Describe the solution you'd like**
When getting the list of vaults, return a list of keys and secrets with useful information like expiration date. 

**Additional context**
This is useful to verify CIS security benchark that an expiration date is set on all keys and secrets. It is accessible through the azure cli (ex: az keyvault secret list --vault-name <KEYVAULTNAME> --query [*].[{"id":id},{"enabled":attributes.enabled},{"expires":attributes.expires}])

**Comment by catalinaperalta** [comment]
Thanks for reaching out @xnkevinnguyen! We'll investigate ASAP.
Adding @msyyc who can further comment on this issue.

**Comment by msyyc** [comment]
@00Kai0 Please help track this issue

**Comment by sebansal** [comment]
It isn't an issue, but how kv is designed.
Key vault access model is designed with two interfaces: the management plane and the data plane. The management plane is where you manage Key Vault itself. Operations in this plane include creating and deleting key vaults, retrieving Key Vault properties, and updating access policies. The data plane is where you work with the data stored in a key vault. You can add, delete, and modify keys, secrets, and certificates.

These are different authorization models, the management plane uses Azure role-based access control (Azure RBAC) and the data plane uses a Key Vault access policy and Azure RBAC for Key Vault data plane operations.

You can read more about it here
https://docs.microsoft.com/en-us/azure/key-vault/general/secure-your-key-vault#access-model-overview

**Comment by jlichwa** [comment]
Also the list of client libraries for data and management plane all languages can be find here:
https://docs.microsoft.com/en-us/azure/key-vault/general/client-libraries
