### ISSUE TITLE
Search elapsed-time unavailable in Python API 

### ISSUE THREAD

**Issue by binbrain** [Azure/azure-sdk-for-python#17339]
The REST API returns the elapsed-time for searches but its not available in Python API.

elapsed-time | Number | Time, in milliseconds, that the service spent processing the request. This only includes the time spent on processing the request, and does not include network transfer time.

**Comment by catalinaperalta** [comment]
Thanks for reaching out @binbrain! We'll investigate ASAP. 
Adding @xiangyan99 who can further comment on this issue.

**Comment by xiangyan99** [comment]
Thanks for the feedback. 

elapsed-time is in the response header which by design we don't expose in the return.

Could you help to tell us more about your scenario? That can help us to prioritize the feature.

**Comment by binbrain** [comment]
@xiangyan99 The scenario is pretty straight forward. When we use the Python API to execute a search we want to know the elapsed-time. Since that attribute is only available in the response headers for REST calls there is no way to get it. There is nothing more to it then that.

**Comment by xiangyan99** [comment]
Thank you for the feedback. Because this needs some design change, we may need more time to discuss it.

**Comment by xiangyan99** [comment]
@binbrain there is a work around for your scenario.

When you call the API, you can pass in a callback function. e.g. you can call the API with 

```py
cls=lambda pipeline_response, _, response_headers: response_headers,
```

which can return the response_headers.

Does this solve your problem?

Thank you.
