### ISSUE TITLE
[CostManagement] CostManagement Query API has wrong API version

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#17351]
- **Package Name**:  azure-mgmt-costmanagement
- **Package Version**:  1.0.0
- **Operating System**: Linux Ubuntu
- **Python Version**:  3.8

**Describe the bug**
CostManagement Query SDK uses 2020-06-01 api-version, but REST returns error saying this version doesn't exist.

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/costmanagement/azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/_query_operations.py#L85

**To Reproduce**
1. Create CostManagementClient
2. Try to use `client.query.usage` function

**Expected behavior**
200 is returned with data

**Screenshots**

**Additional context**

**Comment by catalinaperalta** [comment]
Thanks for reaching out @logachev! We'll investigate this ASAP.
Adding @msyyc who can comment further on this issue.

**Comment by msyyc** [comment]
@00Kai0 Please provide help on the issue

**Comment by martinostvik** [comment]
Any progress on this?

**Comment by jazelenk** [comment]
I'm seeing this as well.

**Comment by jazelenk** [comment]
It looks like the operations code hard-codes api_version, so specifying a known-good version when constructing the client does nto work. For example, in in _query_operations.py:
```
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-06-01"
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"
```

**Comment by msyyc** [comment]
similar issue :https://github.com/Azure/azure-sdk-for-python/issues/18957

**Comment by jazelenk** [comment]
This is not the same issue as #18957. This issue is about the default api_version being wrong. The other issue is about CostManagementClient ignoring the api_version kwarg in its constructor.

This issue does appear to be the same as #16102.
