### ISSUE TITLE
[translation] add a `has_completed` on result models

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#17369]
.NET is [adding ](https://github.com/Azure/azure-sdk-for-net/pull/19555)a boolean property `hasCompleted` to indicate that a terminal state has been reached. We can add this to `JobStatusResult` and `DocumentStatusResult`.

**Comment by mohamedshabanofficial** [comment]
@kristapratico what if the user - bear with me - calls submit_translation_job()
then simply iterates over documents and calls document.has_completed()
will always be false!

**Comment by mohamedshabanofficial** [comment]
@kristapratico sorry i meant for the JobStatusResult
and yeah, if user only calls submit_translation_job()
and gets JobStatusResult object
they may keep on calling has_completed, and it would return the same value False!

**Comment by kristapratico** [comment]
Right, I agree that it could be a bit confusing. I think this was one of the things we wanted to try out at user studies - to see if people understood that the property is not self-updating. If you think this might be too confusing, though, then we can skip implementing this for now and re-evaluate our thoughts on this item for beta.2.

**Comment by kristapratico** [comment]
completed in #17719
