### ISSUE TITLE
Question[azure-cognitiveservices-speech]: Where is the src project?

### ISSUE THREAD

**Issue by hamzahamidi** [Azure/azure-sdk-for-python#17378]
This is just a question about [azure-cognitiveservices-speech](https://pypi.org/project/azure-cognitiveservices-speech/). I can't find its folder/project in this repository. Shouldn't it be under cognitiveservices ?

![azure-cognitiveservices](https://user-images.githubusercontent.com/22576950/111389414-3c10cf00-86b1-11eb-9843-bf8201949078.png)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by KranthiPakala-MSFT** [comment]
@ xiangyan99 Following up to see if there is any update on this issue? - Thank you

**Comment by xiangyan99** [comment]
@kristapratico do you know where our customers can find the source code for it?

**Comment by kristapratico** [comment]
The speech SDK is not in our repo and I'm not certain if the source code can be found on Github. There is a [samples repo](https://github.com/Azure-Samples/cognitive-services-speech-sdk) for it where people open up issues against the SDK itself.

@robch or @oscholz may have more information/pointers.
