### ISSUE TITLE
[mgmt-msi] No Track 2 SDK for azure-mgmt-msi library

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#17389]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
No Track 2 SDK for azure-mgmt-msi library. Is there any timeline to make it available?

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
@00Kai0 Please provide help on it

**Comment by xiangyan99** [comment]
https://pypi.org/project/azure-mgmt-msi/6.0.0b1/ is released.
