### ISSUE TITLE
HttpResponseError expects HttpResponse attributes not set on that class

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#17427]
HttpResponseError assumes a given HttpResponse has `reason` and `status_code` attributes:
https://github.com/Azure/azure-sdk-for-python/blob/4d797d5f7bae84ca2950e272902599f419589eee/sdk/core/azure-core/azure/core/exceptions.py#L268-L270

Those attributes are not part of HttpResponse. They're set on HttpResponse subclasses like RequestsTransportResponse:
https://github.com/Azure/azure-sdk-for-python/blob/4d797d5f7bae84ca2950e272902599f419589eee/sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py#L61-L63

Which is to say, HttpResponseError depends on HttpResponse having undocumented attributes.

**Comment by xiangyan99** [comment]
HttpResponse is a subclass of _HttpResponseBase which has attributes status_code and reason. @chlowell

**Comment by chlowell** [comment]
🤦
