### ISSUE TITLE
Category of the sub-assessment

### ISSUE THREAD

**Issue by irishun** [Azure/azure-sdk-for-python#17439]
Hi, I am using the command to retrieve the vulnerability scanning of ACR images.
There are 10 different categories of the sub-assessment as follow:
![image](https://user-images.githubusercontent.com/47106812/111704234-19acbc00-883f-11eb-8908-07e1307b9239.png)

However, I am not sure what does category **Local** means.
For example, we have one image with the vulnerability whose category = **Local** and description = **GNU Bash Privilege Escalation Vulnerability for Debian**
It would be great to have more detailed information on each category.

Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b43194-b424-2b79-4356-4b7eb91b7735
* Version Independent ID: 1daccb1e-6d2d-77e5-b2fb-c54055b98c58
* Content: [azure.mgmt.security.models.SecuritySubAssessment class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-security/azure.mgmt.security.models.securitysubassessment?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-security/azure.mgmt.security.models.SecuritySubAssessment.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-security/azure.mgmt.security.models.SecuritySubAssessment.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by KranthiPakala-MSFT** [comment]
@xiangyan99 Following up to see if there is any update on this issue? - Thank you
