### ISSUE TITLE
[formrecognizer] Fix ID Docs tests where fixme

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#17432]

**Comment by kristapratico** [comment]
Adding to this, what is the plan for new FieldValue types - "gender" and "country"? Context [here](https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1616187157680?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1616187157680&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1616187157680).
