### ISSUE TITLE
"Dead lock" when listening service bus queue

### ISSUE THREAD

**Issue by tuanfred** [Azure/azure-sdk-for-python#1744]
I have an application in multithreading mode, each thread has its own bus client and listen to the same queue.
It works well, but every 2 or 3 days (after 2K or 3K messages), bus client (of each thread) stop to listening, without any error or exception, like a "dead lock".
It stop at this line (nothing happens):
msg = self.bus_client.receive_queue_message(self.queue_name, peek_lock, timeout)

(peaklock = False and timeout = 30 seconds)

I already run my app with only one thread, but problem persists.  Could you help me ? Actually, i have to stop app and restart app to make it works again

Here 's the fulle code:
```python
class StopableThread(Thread):
    def __init__(self, target=None, name=None, args=(), kwargs=None, daemon=None):
        Thread.__init__(self, target=target, name=name, args=args, kwargs=kwargs, daemon=daemon)
        self.stop_event = Event()
        self.sleep_period = 1.0

    def run(self):
        logger.info('Thread %s started' % self.getName())

        while not self.stop_event.isSet():
            logger.info("Thread %s running" % self.getName())
            self.stop_event.wait(self.sleep_period)
        logger.info('Thread %s end' % self.getName())

    def join(self, timeout=None):
        self.stop(timeout)

    def stop(self, timeout=None):
        self.stop_event.set()
        logger.info('Thread %s : stop signal sent, wait for a moment to stop running thread' % self.getName())
        Thread.join(self, timeout)
        logger.info('Thread %s : stoped' % self.getName())

    def wait(self, timeout=None):
        Thread.join(self, timeout)

    def is_stopped(self):
        return self.stop_event.is_set()
		
class BusRepo:
    def __init__(self, connection):
        (ns, kn, kv) = connection
        self.bus_client = ServiceBusService(
            service_namespace=ns,
            shared_access_key_name=kn,
            shared_access_key_value=kv)

    def create_topic(self, topic_name, topic_option=None):
        with repo_bus_locker:
            self.bus_client.create_topic(topic_name, topic_option)

    def create_subscription(self, topic_name, sub_name, sub_option=None):
        with repo_bus_locker:
            self.bus_client.create_subscription(topic_name, sub_name, sub_option)

    def create_queue(self, queue_name):
        with repo_bus_locker:
            self.bus_client.create_queue(queue_name)

    def send(self, topic, body):
        body_json = json.dumps(body, ensure_ascii=False).encode('utf-8')
        msg = Message(type='application/json', body=body_json)
        self.bus_client.send_topic_message(topic, msg)
        logger.info('Msg sent to {0}: {1}'.format(topic, body))

class BusQueueWorker(BusRepo, StopableThread):
    def __init__(self, name, daemon, connection, bus_cfg):
        StopableThread.__init__(self, name=name, daemon=daemon)
        BusRepo.__init__(self, connection)

        self.queue_name = bus_cfg['name']
        self.receive_timeout = bus_cfg['receivetimeout']
        self.peak_lock = bus_cfg['peaklock']
        #
        self.create_queue(self.queue_name)
		
class SampleQueueWorker(BusQueueWorker):
    def __init__(self, name, daemon=True):
        connection = settings.get_bus_config(settings.CONFIG['bus'])
        bus_cfg = settings.CONFIG['workers']['SampleQueueWorker']['bus_queue']
        BusQueueWorker.__init__(self, name=name, daemon=daemon, connection=connection, bus_cfg=bus_cfg)


    def getName(self):
        return 'SampleQueueWorker_%s' % super(SampleQueueWorker, self).getName()

    def run(self):
        peek_lock = self.peak_lock
        timeout = self.receive_timeout

        logger.info('{0}: Started, Daemon={1} '.format(self.getName(), self.isDaemon()))
        logger.info('{0}: Begin listening to {1}, peekLock={2}'.format(self.getName(), self.queue_name, peek_lock))

        while not self.stop_event.is_set():
            logger.info('{0}: Listening queue'.format(self.getName()))
            msg = self.bus_client.receive_queue_message(self.queue_name, peek_lock, timeout)
            logger.info('{0}: Receive new msg'.format(self.getName()))
            if msg is None or msg.body is None:
                logger.info('{0}: Null msg, ignore'.format(self.getName()))
                continue
            message_id = ''
            msg_props = msg.broker_properties
            if msg_props is not None:
                if 'MessageId' in msg_props:
                    message_id = msg_props['MessageId']
            logger.info('===== {0} Received MessageId={1}'.format(self.getName(), message_id))
            try:
                start = time.time()
                msg_body = msg.body
                msg_decode = msg_body.decode('utf-8-sig')
                msg_json = json.loads(msg_decode)
                # Logic code begin here

                # Logic code end here
                elapsed = time.time() - start
                if peek_lock:
                    msg.delete()
            except Exception as ex:
                logger.exception('{0}-MessageId={1}: Error. {2}'.format(self.getName(), message_id, str(ex)))

        logger.info('{0}: Stop listening to {1}, peekLock={2}'.format(self.getName(), self.queue_name, peek_lock))
```

**Comment by tuanfred** [comment]
For information, i made a workaround to renew bus client after every 24:
self.bus_client = ServiceBusService(
            service_namespace=ns,
            shared_access_key_name=kn,
            shared_access_key_value=kv)

**Comment by lmazuel** [comment]
Hi @tuanfred 
I'm sorry I didn't have the opportunity to look into your issue. Be sure this issue will stay open until I have the necessary time to investigate.
Thank you,

**Comment by tuanfred** [comment]
I finally catch the exception, hope that help you:
Exception in thread QueueWorker_1:
Traceback (most recent call last):
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 617, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='busnamespace.servicebus.windows.net', port=443): Read timed out. (read timeout=65)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/pythonjob/_common/repobus.py", line 178, in run
    msg = self.bus_client.receive_queue_message(self.queue_name, peek_lock, timeout)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/azure/servicebus/servicebusservice.py", line 1071, in receive_queue_message
    return self.read_delete_queue_message(queue_name, timeout)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/azure/servicebus/servicebusservice.py", line 1023, in read_delete_queue_message
    response = self._perform_request(request)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/azure/servicebus/servicebusservice.py", line 1228, in _perform_request
    resp = self._filter(request)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/azure/servicebus/_http/httpclient.py", line 181, in perform_request
    self.send_request_body(connection, request.body)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/azure/servicebus/_http/httpclient.py", line 145, in send_request_body
    connection.send(None)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/azure/servicebus/_http/requestsclient.py", line 81, in send
    self.response = self.session.request(self.method, self.uri, data=request_body, headers=self.headers, timeout=self.timeout)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/pythonjob/.venv/lib/python3.4/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='busnamespace.servicebus.windows.net', port=443): Read timed out. (read timeout=65)

**Comment by alvercau** [comment]
I have the exact same issue. Is there any updates on this?

**Comment by annatisch** [comment]
Hi @tuanfred, @sreeram-r86, @alvercau 

This is just a heads-up to let you know that we have just published a new AMQP-based preview SDK for Service Bus! The API has been newly designed, and you can find documentation here:
- [Overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python)
- [Reference documentation](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus?view=azure-python)

A sample showing how to run a "listening receiver" can be found [here in the overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python#receiving-messages).

You can run multiple receivers in parallel threads, or asynchronously, however please note that a single receiver is not itself threadsafe.

It would be awesome to get your feedback on the new SDK! I'm going to close this issue now - but if you encounter any new issues or errors in the new SDK, please open new bug reports!

Thanks!
