### ISSUE TITLE
azure.core missing aiohttp dependency

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#17456]
Python version 3.7
OS: Linux 

I have a requirements.txt file that includes azure-kusto-data.

When I install that requirements.txt, I get, among others:
azure-core==1.12.0
azure-kusto-data==2.1.0

When I try to run, I get:
REDACTED: in <module>
    import azure.kusto.data
../../v2/lib/python3.7/site-packages/azure/kusto/data/__init__.py:5: in <module>
    from .client import KustoClient, KustoConnectionStringBuilder, ClientRequestProperties
../../v2/lib/python3.7/site-packages/azure/kusto/data/client.py:22: in <module>
    from .security import _AadHelper
../../v2/lib/python3.7/site-packages/azure/kusto/data/security.py:5: in <module>
    from ._token_providers import *
../../v2/lib/python3.7/site-packages/azure/kusto/data/_token_providers.py:10: in <module>
    from azure.identity.aio import ManagedIdentityCredential as AsyncManagedIdentityCredential
../../v2/lib/python3.7/site-packages/azure/identity/aio/__init__.py:7: in <module>
    from ._credentials import (
../../v2/lib/python3.7/site-packages/azure/identity/aio/_credentials/__init__.py:7: in <module>
    from .default import DefaultAzureCredential
../../v2/lib/python3.7/site-packages/azure/identity/aio/_credentials/default.py:14: in <module>
    from .managed_identity import ManagedIdentityCredential
../../v2/lib/python3.7/site-packages/azure/identity/aio/_credentials/managed_identity.py:14: in <module>
    from .._authn_client import AsyncAuthnClient
../../v2/lib/python3.7/site-packages/azure/identity/aio/_authn_client.py:20: in <module>
    from azure.core.pipeline.transport import AioHttpTransport
../../v2/lib/python3.7/site-packages/azure/core/pipeline/transport/__init__.py:67: in __getattr__
    raise ImportError("aiohttp package is not installed")
E   ImportError: aiohttp package is not installed

If I add aiohttp to my requirements.txt, the problem goes away

repro:
python3.7 -m venv ./venv
./venv/bin/python -m pip install --upgrade pip wheel
./venv/bin/pip install azure-kusto-data
./venv/bin/python -c "import azure.kusto.data"

**Comment by xiangyan99** [comment]
Thank you for the feedback.

This is by design that aiohttp is not required by azure.core.

For more information, here is the reference. https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/core/azure-core#Async-transport

**Comment by jazelenk** [comment]
,,,except it's not an option. if aiohttp is not already installed, the module cannot load.

**Comment by xiangyan99** [comment]
Taken offline. Close.
