### ISSUE TITLE
Communication phonenumbers tests failing

### ISSUE THREAD

**Issue by sarkar-rajarshi** [Azure/azure-sdk-for-python#17467]
**Communication Phone numbers**: 

Executing `python - communication - tests` on the build is causing failure on the following test. It has been commented out for the same reason.

```python
self = <test_phone_number_administration_client.PhoneNumbersClientTest testMethod=test_update_phone_number_capabilities>

    def test_update_phone_number_capabilities(self):
        poller = self.phone_number_client.begin_update_phone_number_capabilities(
            self.phone_number,
            PhoneNumberCapabilityType.INBOUND_OUTBOUND,
            PhoneNumberCapabilityType.INBOUND,
            polling = True
        )
        poller.result()
>       assert poller.status() == 'succeeded'
E       AssertionError: assert 'Succeeded' == 'succeeded'
E         - succeeded
E         ? ^
E         + Succeeded
E         ? ^

test/test_phone_number_administration_client.py:67: AssertionError
```
With a value of `'succeeded'` - `python - communication - tests` -- fails
With a value of `'Succeeded'` - `python - communication - ci` -- fails

**Comment by jbeauregardb** [comment]
Working on it on this PR right here https://github.com/Azure/azure-sdk-for-python/pull/17487

**Comment by sarkar-rajarshi** [comment]
With #17487 new tests are breaking

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=797119&view=ms.vss-test-web.build-test-results-tab

**Comment by jbeauregardb** [comment]
It's not an issue with the PR itself. We are having a toll free phone number shortage at the moment.

**Comment by xiangyan99** [comment]
Is it still valid?
