### ISSUE TITLE
Y

### ISSUE THREAD

**Issue by vpatao6p** [Azure/azure-sdk-for-python#17469]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chlowell** [comment]
Hi @vpatao6p! I'm guessing you didn't intend to open this issue. If I'm wrong, please add some information about the problem you're experiencing and reopen this issue.
