### ISSUE TITLE
Key Vault Certificate content_type 

### ISSUE THREAD

**Issue by Jordan0928** [Azure/azure-sdk-for-python#17492]
Hello,

I'm frustrated I couldn't determine certificate contentType (pkcs12 or pem) so I can use appropriate mechanisms to parse certificate content into certificate, private key and CA certificates in PEM format.

I am using Azure python SDK to read key vault certificate, private key, and CA in PEM format. The code that I use to decode the content depends on whether the certificate is imported to key vault in PEM or PKCS12 format. 

I know "content_type" is used in certificate policy, and adding this to the certificate attributes can simplify my work. I can use "certificate.conten_type" from python to determine the certificate type (pem or pkcs12) similar to other attributes such as certificate.name.

I could use openssl to determine the format of the certificate but it requires extra code and latency. Certificate attribute can solve extra content parsing to determine just type.

**Comment by mccoyp** [comment]
Thanks for opening this issue! As you've noted, a certificate's content type is part of its [policy](https://docs.microsoft.com/python/api/azure-keyvault-certificates/azure.keyvault.certificates.certificatepolicy?view=azure-python). That's reflected in the [Key Vault Certificates](https://docs.microsoft.com/python/api/overview/azure/keyvault-certificates-readme?view=azure-python) library:
```py
>>> cert = client.get_certificate(cert_name)
>>> cert.policy.content_type
<CertificateContentType.pkcs12: 'application/x-pkcs12'>
```
Is this what you're looking for?

**Comment by Jordan0928** [comment]
Perfect!!!
 
I was getting ": AttributeError: 'CertificateProperties' object has no attribute 'policy'". Looks like I was trying to get the content_type from CertificateProperties.

cert_client = CertificateClient(vault_url="https://jordan-kv.vault.azure.net/", credential=credential)
certs = cert_client.list_properties_of_certificates()
for cert in certs:
            print(cert.name)
            print(cert.policy.content_type)

Modified like you suggested:
cert_client = CertificateClient(vault_url="https://jordan-kv.vault.azure.net/", credential=credential)
certs = cert_client.list_properties_of_certificates()
for cert in certs:
            print(cert.name)
            mycert = cert_client.get_certificate(cert.name)
            print(mycert.policy.content_type)

output:
azureCert
CertificateContentType.pkcs12
azureCert2
CertificateContentType.pem

Thank you!
