### ISSUE TITLE
Resource Changes Method Does Not Return 'Create' Change Types

### ISSUE THREAD

**Issue by dmartin-r7** [Azure/azure-sdk-for-python#17506]
- **Package Name**: azure-mgmt-resourcegraph
- **Package Version**: 7.0.0
- **Operating System**: Mac OS
- **Python Version**: 3.7.5

**Describe the bug**
Resource Changes method call does not return any 'Create' changes. Under the [documentation](https://docs.microsoft.com/en-us/azure/governance/resource-graph/how-to/get-resource-changes) for resource changes an example of a resourceChanges API call for a new storage account is given. Here it displays what the JSON response will look like, showing multiple changes including a 'Create' change type. I have been unable to replicate this functionality from my end.

**To Reproduce**
1. Using example setup from Azure Docs

```
def getresources()
    argClient = get_client_from_cli_profile(arg.ResourceGraphClient)
    start = (datetime.datetime.now() - datetime.timedelta(minutes=15)).isoformat()
    end = datetime.datetime.now().isoformat()
    interval = arg.models.ResourceChangesRequestParametersInterval(start=start, end=end)

    argQueryOptions = arg.models.ResourceChangesRequestParameters(resource_id = "/subscriptions/{id}/resourcegroups/{name}/providers/Microsoft.Network/networkSecurityGroups/dmartin-test", interval=interval, fetch_property_changes=True)

    argResults = argClient.resource_changes(parameters=argQueryOptions)
```
2. I create a new Network Security Group from scratch, give the resource ID to this script and call the resource changes method, but I see no 'Create' change being returned. If I update a tag, I will see this change but not the initial creation.

argResults contains data including Delete, Update, Insert but no 'Create' change types, even when the interval is set so the creation time will be included.

**Expected behavior**
I should be able to see a change object for the change type 'Create' at the timestamp that the resource was created.

**Comment by 00Kai0** [comment]
Hi @chiragg4u, could you have a look?

**Comment by snaheth** [comment]
Hello @dmartin-r7, Create resource changes are only available on resources that were created before and deleted within the last 14 days. This means that VM1 that you newly created within Subscription1 and ResourceGroup1 for the first time would not be picked up under this API, _yet_. This wasn't clear in our documentation before so we've updated it.

We have a plan to address this in future iterations of change tracking. To make it easier for tracking and communicating with you regarding our progress and updates, please create an item for your request [here](https://feedback.azure.com/forums/915958-azure-governance?category_id=345061).
