### ISSUE TITLE
CosmosClient docstring params implicate 'request_timeout' in seconds. ConnectionPolicy expects 'request_timeout' in milliseconds.

### ISSUE THREAD

**Issue by AnonymousNoob** [Azure/azure-sdk-for-python#17507]
- **Package Name**: azure-cosmos
- **Package Version**: 4.2.0
- **Operating System**: Linux
- **Python Version**: 2.7/3.6

The [CosmosClient](https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py#L131)
 docstring suggests the 'request_timeout' keyword to be "The HTTP request timeout in seconds."

the __init__() method builds connection policy with the kwargs passed (where the request_timeout is expected as per docstring in seconds) with the [_build_connection_policy](https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py#L71) where the ConnectionPolicy.RequestTimeout is overriden with kwargs

However, the [ConnectionPolicy](https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/sdk/cosmos/azure-cosmos/azure/cosmos/documents.py#L361) is declared and presumably works with a RequestTimeout in milliseconds

1. Install azure-cosmos 4.2.0 (pip install azure-cosmos==4.2.0)
2. Import CosmosClient Module
`from azure.cosmos import CosmosClient`
3. Initialize CosmosClient with master_key and timeout options
`client = CosmosClient(url, credential, request_timeout=1)`

The client creation would fail with a timeout of 1ms.
`ServiceRequestError: (<urllib3.connection.HTTPSConnection object at 0x7fc0aaf40b00>, 'Connection to myCosmosDB.documents.azure.com timed out. (connect timeout=0.001)') `

**Expected behavior**
HTTP Requests to timeout within 1 second (or, within N seconds) rather the request times out within 1 millisecond.

(The ambiguity is currently handled by passing the 'request_timeout' in milliseconds)

**Comment by Rodrigossz** [comment]
Fixed here: https://github.com/Azure/azure-sdk-for-python/pull/17646
