### ISSUE TITLE
Python SDK - Update Autoscale Throughput

### ISSUE THREAD

**Issue by Kanwrk** [Azure/azure-sdk-for-python#17518]
**Is your feature request related to a problem? Please describe.**
For Cosmos DB, in Python azure.cosmos.cosmos_client unable to update the maxThroughput value incase of Autoscale enabled

**Describe the solution you'd like**
Please provide a method/api to support the same, replace_throughout works when the collection is not set to Autoscale

**Comment by chlowell** [comment]
Thank you for opening this issue, we'll investigate as soon as possible.

**Comment by Rodrigossz** [comment]
Added this item to the Limitations section: https://github.com/Azure/azure-sdk-for-python/pull/17646 . There is no short term plan to support this capability.
