### ISSUE TITLE
Test Our Libraries WITHOUT aiohttp

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#17516]
All of the environments as they are now either 

A) Install your package. Install `eng/test_tools.txt` Install `dev_requirements.txt`. Run tests.
B) Install your package. Install `eng/test_tools.txt`. Install a specific version of each `install_requires` from your package.

The issue here. Within `eng/test_tools.txt`, we _always_ install `aiohttp`. This is can _hide issues_ with our import logic.

We need to run tests in an environment _without_ AIOHTTP and ensure that `depends` and `whl`/`sdist` all pass without `aiohttp`.

**Comment by seankane-msft** [comment]
I think we can close this now. We can re-open if I am mistaken.
