### ISSUE TITLE
Parametrized query example

### ISSUE THREAD

**Issue by EvgenSk** [Azure/azure-sdk-for-python#17525]
[Enter feedback here]
It would be really helpful if the page had an example of parametrized query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a472053b-358e-bc0e-4d91-367b5e039642
* Version Independent ID: 7a50ad47-3697-e29e-3f3e-afbead68aaec
* Content: [azure.servicebus.management.SqlRuleFilter class](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.management.sqlrulefilter?view=azure-python)
* Content Source: [docs-ref-autogen/azure-servicebus/azure.servicebus.management.SqlRuleFilter.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-servicebus/azure.servicebus.management.SqlRuleFilter.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by chlowell** [comment]
Thank you for the feedback, someone from the team will take a look as soon as possible.

**Comment by yunhaoling** [comment]
hey @EvgenSk, thanks for the feedback.

If you're looking for some sample code, we have a test that shows how to use parametrized sql rule filer which could be found [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_rules.py#L51-L53).

there's also an official service doc on sql rule filter usage: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-sql-filter

and we'll consider adding detailed sample in the docstring and mgmt samples.
