### ISSUE TITLE
Support Microsoft.ServiceBus/namespaces/topics in azure.mgmt.monitor

### ISSUE THREAD

**Issue by eladmotola** [Azure/azure-sdk-for-python#17545]
**Is your feature request related to a problem? Please describe.**
While trying to get metrics of Microsoft.ServiceBus/namespaces/topics (Incoming messages) I got this error:
`azure.core.exceptions.HttpResponseError: (BadRequest) Microsoft.ServiceBus/namespaces/topics is not a supported platform metric namespace`

**Describe the solution you'd like**
Support Microsoft.ServiceBus/namespaces/topics as a valid metric via sdk

**Describe alternatives you've considered**
I dont have any.... or there is a workaround?

**Additional context**

**Comment by chlowell** [comment]
Thanks for opening this issue, we'll investigate as soon as possible. In the meantime, can you please share a sample of your code, so it's clear which library and API you're using when you see this error?

**Comment by eladmotola** [comment]
@chlowell Hey!
thank you for the quick reply

Code example:
```
monitor_client = MonitorManagementClient(credential, SUBSCRIPTION_ID)
today = datetime.datetime.utcnow()
five_min_before = (today - datetime.timedelta(minutes=5))
metrics_data = monitor_client.metrics.list(
'/subscriptions/__SUBSCRIPTION_ID__/resourceGroups/__rg__/providers/Microsoft.ServiceBus/namespaces/__namespace__/topics/__topic__',
        timespan=f"{five_min_before}/{today}",
        interval='PT1M',
        metricnames='IncomingMessages',
        aggregation='Maximum'
    )
```

**Comment by eladmotola** [comment]
@chlowell Hey,
Do you have any timeframe to share about this issue?

**Comment by chlowell** [comment]
I don't; @zhangyan133, can you comment?

**Comment by eladmotola** [comment]
@chlowell @zhangyan133 Hey,
I see here:
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftservicebusnamespaces

That I can pull IncomingMessages of each pool (Im assuming I should add the entityname in the dimension as mention) but I dont understand how to do it since "dimensions" is not a valid api.... any code example? I cant find anything about it and Ireally need this one

**Comment by chlowell** [comment]
@msyyc can you help route this to the right person?

**Comment by msyyc** [comment]
@RAY-316 please provide help on this issue

**Comment by eladmotola** [comment]
@chlowell Hey

Look like I had to add `filter= EntityName eq '__topicname__'`
Im closing
