### ISSUE TITLE
List resources raise  AttributeError  ItemPaged object has no attribute next_link

### ISSUE THREAD

**Issue by h-medjahed** [Azure/azure-sdk-for-python#17572]
After updating, we get AttributeError  ItemPaged object has no attribute next_link

**Comment by chlowell** [comment]
Thanks for opening this issue. I'd like to assign it to the right engineer but I'm not sure who that is because I don't know which library you're using. Could you please add that information and a small sample of the code that raises AttributeError?

**Comment by h-medjahed** [comment]
For all librairies for exemple azure-mgmt-compute,  azure-mgmt-resource,  azure-mgmt-network

**Comment by KranthiPakala-MSFT** [comment]
@zhangyan133 Following up to see if there is any update on this issue? - Thank you
