### ISSUE TITLE
FormPage is Not JSON Serializable

### ISSUE THREAD

**Issue by anujb-msft** [Azure/azure-sdk-for-python#17570]
Using json.dump(...) to write a large FR response to a file. Turns out FormPage model object is not JSON serializable...which is a shame.

Error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-57-520a36366775> in <module>
     13 
     14 with open ("output.json", "w") as output_json:
---> 15     json.dump(enumerated, output_json, indent=4)
     16 
     17 

~/opt/anaconda3/envs/py38/lib/python3.8/json/__init__.py in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    177     # could accelerate with writelines in some versions of Python, at
    178     # a debuggability cost
--> 179     for chunk in iterable:
    180         fp.write(chunk)
    181 

~/opt/anaconda3/envs/py38/lib/python3.8/json/encoder.py in _iterencode(o, _current_indent_level)
    427             yield _floatstr(o)
    428         elif isinstance(o, (list, tuple)):
--> 429             yield from _iterencode_list(o, _current_indent_level)
    430         elif isinstance(o, dict):
    431             yield from _iterencode_dict(o, _current_indent_level)

~/opt/anaconda3/envs/py38/lib/python3.8/json/encoder.py in _iterencode_list(lst, _current_indent_level)
    323                 else:
    324                     chunks = _iterencode(value, _current_indent_level)
--> 325                 yield from chunks

Model Object:

https://github.com/Azure/azure-sdk-for-python/blob/6edb9997e087ac410a17252379f5462a15a2639f/sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py#L363

**Comment by kristapratico** [comment]
Hi @anujb-msft, looking into this for you.

In the meantime, could you try the below snippet and see if you get the expected output?

```
with open("output.json", "w") as output_json:
    json.dump(enumerated, output_json, indent=4, default=lambda x: x.__dict__)
```

**Comment by anujb-msft** [comment]
This gives me the expected output. To clarify in this case the `enumerated` variable is enumerated(form_pages) result from the Form Recognizer service.

**Comment by kristapratico** [comment]
I tagged this issue as a feature request. This is something we're looking at across client libraries (including Form Recognizer) and we may add something like `to_json` and `from_json` helper methods in the future. I do not have a timeline yet, but can update this issue once I do.

**Comment by anujb-msft** [comment]
Thank you for the clarity, triaging this as a feature, and providing the workaround.

Anuj
________________________________

**Comment by catalinaperalta** [comment]
The following samples `sample_convert_to_and_from_dict.py` and `sample_convert_to_and_from_dict_async.py` have been added to show how the Python Form Recognizer SDK facilitates serialization under the [samples folder](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/formrecognizer/azure-ai-formrecognizer/samples) for both v3.1 and v3.2-beta versions of the SDK. 

Will close this issue now, please feel free to open new issues with questions or feedback. Thanks!
