### ISSUE TITLE
Event Grid readme and samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#17627]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventgrid/azure-eventgrid#send-events-as-dictionaries):
![image](https://user-images.githubusercontent.com/57166602/112801848-f89c6480-90a3-11eb-9c52-ac4cf51a41a0.png)

Suggestion:  
Add import package
```
import uuid
import datetime as dt
from msrest.serialization import UTC
```
2.
Section [link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_publish_events_to_a_topic_using_sas_credential.py#L21):
![image](https://user-images.githubusercontent.com/57166602/112802052-41ecb400-90a4-11eb-8d63-92b2236de448.png)

Reason:
azure.core.exceptions.HttpResponseError: (BadRequest) Invalid key in aeg-sas-token. Valid format :r=UrlEncodedResource&e=UrlEncodedUtcExpiration&s=UrlEncodedSignature. Input sas string: lrPUpeSQUJEMj3paatULJ1ejvtgMvU4PIy3o+sypQ0w=. 

Suggestion:
EVENTGRID_SAS is not an access key, but a shared access signature. 
But we unable to  find SAS (shared access signature) in event grid topic  from the 'Azure Portal'. Only find the `access key`.
Maybe we should consider this method: `sas = generate_sas(endpoint, topic_key, expiration_date_utc)` to generate sas.

@jongio for notification.

**Comment by rakshith91** [comment]
Thanks for the issue!

For section2, it is intentional that we did not add a generate_sas

the reason is that it is highly unlikely that someone generates a sas and uses it for themselves. So, we have two different examples for using a sas and generating a sas (it's a cross language feedback that was received in arch board)

point 1 sounds fair to me - thank you!

**Comment by rakshith91** [comment]
I've updated the description of `EVENTGRID_SAS` to make it more clear and fixed the first one. Thanks again
https://github.com/Azure/azure-sdk-for-python/pull/17641/files
