### ISSUE TITLE
Storage File Data Lake readme issue

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#17628]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake#uploading-a-file):
![image](https://user-images.githubusercontent.com/57166602/112804160-a6a90e00-90a6-11eb-9984-c4de6ba0d238.png)

Reason:
azure.core.exceptions.ResourceNotFoundError: (PathNotFound) The specified path does not exist.

Suggestion:  
Add a line of code here: `file.create_file ()`

@jongio for notification.

**Comment by tasherif-msft** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/17731 will resolve this!
