### ISSUE TITLE
Servicebus receiver seems to ignore messages in the queue

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#17631]
- **Package Name**: servicebus
- **Package Version**: 7.0.1
- **Operating System**: Linux / OSX
- **Python Version**: 3.8.X

**Describe the bug**
We experience cases where the queue receiver does not seems to get messages that are waiting in the queue. This seems to happen more often when only one message is in the queue. If a new message arrive, then the processing starts.

**To Reproduce**
Difficult to reproduce in a systematic way.

** More info**

We read from a queue iterating the following in an infinite loop, polling a set of queues:
```
    with AutoLockRenewer(max_lock_renewal_duration=5*60) as renewer:
        with get_queue_receiver(service_bus_client, queue_name, renewer) as receiver:
            msg_batch = receiver.receive_messages(max_message_count=1,
                                                  max_wait_time=1)
            if msg_batch:
                callback(msg_batch[0], receiver)

```

You can think a polling Q1, Q2, Q3,...,Q1, Q2 and so on with the above code. Notice we are using only sync operations.

**Comment by iscai-msft** [comment]
Thank you for filing this issue @andrea-cassioli-maersk , wiring this to @yunhaoling

**Comment by yunhaoling** [comment]
hey @andrea-cassioli-maersk , thanks for reaching out!

may I have some more details on how you handle the received message? like
- how long did you keep the message until you settle the message, which settlement you use (complete/deadletter/abandon/defer)
- do you have multiple receivers running to receive from the queue?

I'm wondering if the message is occupied by some previous process making it unavailable.

**Comment by andrea-cassioli-maersk** [comment]
hey @yunhaoling,

* messages are usually kept locked I would say one to two minutes. We have a set a lock expiration of 5 minutes. Most messages are completed, some abandoned if the processing fails with no way to recover. We do not use deadlettering.
* we use indeed multiple receivers, say 3 to 10.

You have a good point, some messages might be just locked. But form our logs it seems a consumer is idle and there must be several messages in the queue. We also regularly experience the following: running a single consumer, we submit a message and the only consumer seems to ignore it until we submit a second message.

I will do some more investigation next week.

**Comment by yunhaoling** [comment]
@andrea-cassioli-maersk , would you mind also sharing me with your sending code? as we recently fixed an issue in amqp flow control only related to messages of large size (> 100k) being sent (which results in receiver receiving message unexpectedly).

So to better understand what's happening/repro, I find it's could be helpful to know how the send program looks.

**Comment by andrea-cassioli-maersk** [comment]
Hi,
the code is a bit convoluted so I must give you a kind of real version:

```
def send_msg(str: connection_string, queue_name: str, msg: ServiceBusMessage):
    service_bus_client = ServiceBusClient.from_connection_string(conn_str=connection_string,  receive_mode=ServiceBusReceiveMode.PEEK_LOCK)

    with service_bus_client.get_queue_sender(queue_name=queue_name) as sender:
        sender.send_messages(msg)
```

We are transitioning the sender to C#, but we experience the same issue and actually I think even if I send a message via the azure portal.

**Comment by yunhaoling** [comment]
hey @andrea-cassioli-maersk , I've written simple pieces of send and receive code trying to reproduce but could not trigger the issue. I have two receivers and one sender running:

The major steps I use is:

1. I start the two receivers first
2. then I start the sender and let it run for a while, stop the sender
4. let the two receivers consume all the messages (receive + complete)
5. restart the sender, run for a while, and stop
6. let the two receivers consume all the messages.

I use the [ServiceBusExplorer](https://github.com/paolosalvatori/ServiceBusExplorer) to check message count in the queue, all messages could be consumed.

I'm wondering if some messages in your app has hit the max delivery count and moved to the dead letter queue, would you be able to check the active message count in your queue when you're hitting the issue?
(to check the message count in the queue programmatically, you can refer to the mgmt sample [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_queue.py#L62) to retrieve [`QueueRuntimeProperties`](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.management.html#azure.servicebus.management.QueueRuntimeProperties))

here is my code:
# receiving
```python
servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR, logging_enable=True)
while True:
    with AutoLockRenewer(max_lock_renewal_duration=5 * 60) as renewer:
        with servicebus_client:
            receiver = servicebus_client.get_queue_receiver(queue_name=QUEUE_NAME, auto_lock_renewer=renewer)
            with receiver:
                msg_batch = receiver.receive_messages(max_message_count=1, max_wait_time=1)
                if msg_batch:
                    print("######## message received, start handling".format(str(msg_batch[0])))
                    time.sleep(60 * 2)
                    receiver.complete_message(msg_batch[0])
                    print("######## message completed".format(str(msg_batch[0])))
```

# sending
```python
servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR, logging_enable=True)
with servicebus_client:
    sender = servicebus_client.get_queue_sender(queue_name=QUEUE_NAME)
    with sender:
        while True:
            sender.send_messages(ServiceBusMessage("Single Message"))
            print('message sent')
            time.sleep(30)
```
