### ISSUE TITLE
Docs onboarding automation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#17651]
In the `<lang> - docindex` pipeline: 

1. Add a script in eng/scripts/ that reads the language-specific package .csv file ([example](https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/java-packages.csv)) 
2. Generates the appropriate onboarding outputs (package.json, latest.csv, etc.) for the language
3. Opens a PR against the docs repo with the updated onboarding artifact.

**Comment by danieljurek** [comment]
A few packages have generated errors in the docs.ms ref docs CI process. Some of these reproduce (but do not cause failures) in our own sphinx processes. 

* Latest: 
  * azure-mgmt-apimanagement -- https://github.com/Azure/azure-sdk-for-python/issues/18084
  * azure-mgmt-network -- This package takes a long time to build docs and crashes the build more often than not. Updates to it have to be handled outside the docs CI process. 
* Preview: 
  * azure-core-tracing-opentelemetry -- https://github.com/Azure/azure-sdk-for-python/issues/18078
  * azure-mgmt-reservations -- https://github.com/Azure/azure-sdk-for-python/issues/18077
  * azure-mgmt-signalr -- 
  * azure-monitor-opentelemetry-exporter -- the latest version of this package has issues that cause CI fail. Pinning a previous version succeeded.

**Comment by danieljurek** [comment]
This fixes this issue for Python: https://github.com/Azure/azure-sdk-for-python/issues/17651

**Comment by scbedd** [comment]
Attempting resolution of:

* azure-monitor-opentelemetry-exporter
* azure-core-tracing-opentelemetry

[In this PR.](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1340)

**Comment by danieljurek** [comment]
Also `azure-mgmt-mixedreality` -- https://github.com/Azure/azure-sdk-for-python/issues/18457

**Comment by danieljurek** [comment]
Also `azure-containerregistry` -- https://github.com/Azure/azure-sdk-for-python/issues/18815

**Comment by scbedd** [comment]
`azure-mgmt-network` is a function of being a HUGE package. We can't really resolve that. I have a PR that [caches sphinx processes]() that I have not yet merged for our local usage, but that does not help the docs CI at all. We will have to manually generate `azure-mgmt-network` locally in the meantime. On my dev box w/ SSD it _still_ runs for upwards of 2 hours.

**Comment by danieljurek** [comment]
Also `azure-containerregistry`

**Comment by danieljurek** [comment]
Also `azure-monitor-query` https://github.com/Azure/azure-sdk-for-python/issues/19417
