### ISSUE TITLE
[formrecognizer] consolidate prebuilt examples in README

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#17666]
There are several prebuilt examples that demonstrate very similar code, consider reducing to one or two examples for prebuilt models. 

- Capitalize "ID" documents in all the docs

**Comment by kristapratico** [comment]
See JS's take on it here: https://github.com/Azure/azure-sdk-for-js/pull/14626/files/737e5fd8cc48a1bf316244f0732865ca89c9194b#diff-5f83f2ef1b728594b2811884f311d777a113c43bf31e21c3e9279e93bb927236
