### ISSUE TITLE
[core] unpacking headers into helper function fails when CIMultiDict has same named headers

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#17687]
Line in question: https://github.com/Azure/azure-sdk-for-python/pull/17498/files#diff-547f37bcea6e5e085b596c30ef94ad2f9cff42b392d6f187143f6c4263c20369R60

Document Translation sends two Set-Cookie headers and both are preserved in the CIMultiDict for async:

![image](https://user-images.githubusercontent.com/31998003/113067238-d45a8980-9170-11eb-9f9e-c24ad5541272.png)

`<CIMultiDict('Cache-Control': 'public,max-age=1', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=utf-8', 'Content-Encoding': 'gzip', 'Etag': '"B6B2FB7DEC30648B8F6D9D20A7568DF451C6289A139285BE42B188577622049C"', 'Retry-After': '1', 'Vary': 'Accept-Encoding', 'X-RequestId': '7d3287ba-aee6-4629-b5b1-13db0c8aa8fc', 'Set-Cookie': 'ARRAffinity=5dd610bbbfcdcce1e8b7e036dad4b7c92b91df5adc2f4b536e67d2a5eff0940e;Path=/;HttpOnly;Secure;Domain=doctrans.westus.microsofttranslator.com', 'Set-Cookie': 'ARRAffinitySameSite=5dd610bbbfcdcce1e8b7e036dad4b7c92b91df5adc2f4b536e67d2a5eff0940e;Path=/;HttpOnly;SameSite=None;Secure;Domain=doctrans.westus.microsofttranslator.com', 'X-Powered-By': 'ASP.NET', 'apim-request-id': '7d3287ba-aee6-4629-b5b1-13db0c8aa8fc', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'Date': 'Tue, 30 Mar 2021 23:03:45 GMT')>`

My understanding is that sending the same named header is acceptable: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

> To send multiple cookies, multiple Set-Cookie headers should be sent in the same response.

When the headers are unpacked in the _case_insensitive_dict() call:

`headers = _case_insensitive_dict(**response.http_response.headers)`

It throws exception: 

TypeError: azure.core._utils._case_insensitive_dict() got multiple values for keyword argument 'Set-Cookie'

When this was wrapped in requests CaseInsensitiveDict previously, it just took the value for the first 'Set-Cookie' header and ignored / didn't add the second 'Set-Cookie' to the headers dict.

`headers = CaseInsensitiveDict(response.http_response.headers)`

`{'Cache-Control': 'public,max-age=1', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=utf-8', 'Content-Encoding': 'gzip', 'Etag': '"B6B2FB7DEC30648B8F6D9D20A7568DF451C6289A139285BE42B188577622049C"', 'Retry-After': '1', 'Vary': 'Accept-Encoding', 'X-RequestId': '7d3287ba-aee6-4629-b5b1-13db0c8aa8fc', 'Set-Cookie': 'ARRAffinity=5dd610bbbfcdcce1e8b7e036dad4b7c92b91df5adc2f4b536e67d2a5eff0940e;Path=/;HttpOnly;Secure;Domain=doctrans.westus.microsofttranslator.com', 'X-Powered-By': 'ASP.NET', 'apim-request-id': '7d3287ba-aee6-4629-b5b1-13db0c8aa8fc', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'Date': 'Tue, 30 Mar 2021 23:03:45 GMT'}`

**Comment by kristapratico** [comment]
As an added note, this unfortunately is breaking every call to the Document Translation service now that they've started to return a retry-after header. Need to figure out if this is an azure-core bug or if I need to do a workaround to unblock the release.

**Comment by xiangyan99** [comment]
#17702
