### ISSUE TITLE
Key vault symmetric key 

### ISSUE THREAD

**Issue by Jordan0928** [Azure/azure-sdk-for-python#17724]
**Is your feature request related to a problem? Please describe.**
I need to generate a symmetric data key (size 256 bit) in key vault for encryption in my application. I will use the data key for encryption and discard it immediately whereas the encrypted version of the data key will be save in my application for future references to decrypt the data key. I use Azure SDK for python.

**Describe the solution you'd like**
I learned through the documentation Azure key vault doesn't support symmetric key but I also found the key vault wrap/unwrap key operations with key vault asymmetric premium key that never leave HSM is an excellent option for my case. But I need help with generating a symmetric 256 bit data key in the Azure SDK prior to calling wrap and unwrap operations for encryption and decryption of the symmetric data key.

**Describe alternatives you've considered**
I considered using "random_key = os.urandom(32)" but I am concerned about its strength and wanted any Azure SDK options.

**Comment by iscai-msft** [comment]
Thank you for opening this feature request, routing to @chlowell  and @mccoyp

**Comment by mccoyp** [comment]
Hi @Jordan0928, thank you for creating this issue! You're correct that symmetric keys aren't supported by Key Vault, but they are supported by [Managed HSM](https://docs.microsoft.com/azure/key-vault/managed-hsm/). You can create a symmetric key by targeting your HSM with the same Key Vault API:

```python
from azure.identity import DefaultAzureCredential
from azure.keyvault.keys import KeyClient, KeyType, KeyWrapAlgorithm
from azure.keyvault.keys.crypto import CryptographyClient

credential = DefaultAzureCredential()
key_client = KeyClient(vault_url="https://{managed-hsm-name}.managedhsm.azure.net", credential=credential)

# the key will be generated by the service and remain in the vault
symmetric_key = key_client.create_key("key-name", KeyType.oct_hsm)
crypto_client = CryptographyClient(key=symmetric_key, credential=credential)

# cryptographic operations will be performed by the service with the key
crypto_client.wrap_key(KeyWrapAlgorithm.aes_256, "plaintext")
```

Alternately, Key Vault does support HSM-protected asymmetric keys on premium vaults, as you mentioned. So using the above sample, you could target your vault when creating a `KeyClient` and create a `KeyType.rsa_hsm` key, which would support RSA `KeyWrapAlgorithm`s. The service would again handle key creation for you. Does this help to answer your question?

**Comment by Jordan0928** [comment]
Thank you McCoy for the quick response. I want to confirm my understanding of the last part of your response. Can I access the symmetric key that I create in the premium vault from my application?

**Comment by mccoyp** [comment]
There's currently no way to access the symmetric key you create in a Managed HSM, but you can access the public components of an HSM-protected asymmetric key that you create in a premium vault. (These are the public exponent value (`e`) and modulus (`n`) values of the created key's internal [`key`](https://docs.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys.keyvaultkey?view=azure-python#key).) Symmetric keys can be created in Managed HSMs, but not in premium vaults.

**Comment by Jordan0928** [comment]
Got it. Thank you again. I appreciate quick clarification and support.

**Comment by mccoyp** [comment]
This seems to be resolved, so I'll go ahead and close the issue. Feel free to re-open it or create another if anything comes up -- thank you!
