### ISSUE TITLE
CustomVision SDK - Adding file to existing project with files

### ISSUE THREAD

**Issue by YogiTiwari** [Azure/azure-sdk-for-python#17734]
- **Package Name**:  azure.cognitiveservices.vision.customvision.training.models.ImageFileCreateBatch
- **Package Version**: 
- **Operating System**:
- **Python Version**: 3.9

**Describe the bug**
When uploading files to an existing project which has files gives error CustomVisionErrorException: No valid image files
It works when loading files to new or empty project

**To Reproduce**
1. Create a custom vision project in customvision.ai
2. upload pictures and tag them
3. train the model
4. Use SDK to upload the labeled pictures

**Expected behavior**
New pictures should get added to the project

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Could you help to try the new vision SDK and see if it works for you? https://pypi.org/project/azure-ai-vision/

**Comment by swathipil** [comment]
Closing since no customer response.
