### ISSUE TITLE
ManagedIdentity 429 error

### ISSUE THREAD

**Issue by Itayazolay** [Azure/azure-sdk-for-python#17787]
- **Package Name**: azure-identity
- **Package Version**:  1.5.0
- **Operating System**: Ubuntu
- **Python Version**: 3.7.10

**Describe the bug**
I'm using azure managed Identity to authenticate against blob storage.
I'm using multiprocessing, and in each process (about 60) I create a blob storage client with ManagedIdentity credential.
I am receiving "ManagedIdentityCredential.get_token failed: Unexpected response" error on 1 or 2 of the processes.
The error seems to be 429 - too many requests, but isn't ManagedIdentity should be able to handle that and retry after some period of time? 
Am I doing something wrong? I calling ManagedIdentity() directly and pass it to BlobServiceClient directly.

![image](https://user-images.githubusercontent.com/14018345/113564633-5e43a000-9612-11eb-97cb-2e25421bd841.png)

Thanks!

**Comment by chlowell** [comment]
I expect your situation is similar to #13387 in that you're creating a credential in each process. These don't share state, so each instance is responsible for getting its own token and you therefore have many requesting one simultaneously. Some succeed but the token endpoint throttles your VM before all receive a token. The credential instances that get 429 do retry but with enough of them doing so simultaneously, you stay throttled until some exhaust their retries.

One workaround is to create the credential instance and cache a token before forking. Here's a toy example of that:
```py
from multiprocessing import Pool
from azure.identity import ManagedIdentityCredential

SCOPE = "https://storage.azure.com/.default"
cred = ManagedIdentityCredential()
token = cred.get_token(SCOPE)

def f(n):
    token2 = cred.get_token(SCOPE)
    assert token2.token == token.token
    print('it worked ' + str(n))

if __name__ == '__main__':
    n = list(range(60))
    with Pool(len(n)) as p:
        p.map(f, n)
```
That way, each process starts with an authenticated credential and does not need to request a token initially. However, the processes don't share state after the fork, so when the cached token expires (typically in an hour) you will again have some large number of processes requesting a new token at roughly the same time. If your application doesn't run for an hour, that could be okay, but if it does run longer, you need some means of sharing state between, or synchronizing, the processes.

**Comment by Itayazolay** [comment]
Thanks for you response. 
I'm actually not using fork, so all the instances are trying to get the token at the same time.
What is the throttle limit? I'm only using 60-70 processes, it doesn't sound so much (with retries it's even less). 
I guess that the token is cached after the first time 'get_token' is called? 
Maybe I can solve it with retry with random wait between retries? 
Is there any way to solve it without sharing state, I am a bit worried about unexpected behavior here(harder to debug, etc).

**Comment by chlowell** [comment]
> What is the throttle limit? I'm only using 60-70 processes, it doesn't sound so much (with retries it's even less).

To my knowledge, the limit isn't documented. ([This](https://docs.microsoft.com/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#error-handling) is the only document I know for VM managed identity.)

> I guess that the token is cached after the first time 'get_token' is called?

Yes.

> Is there any way to solve it without sharing state, I am a bit worried about unexpected behavior here(harder to debug, etc).

Sure, just brainstorming a little, not knowing what's best for your application, you could:
- spawn fewer processes
- add a random delay before operations
- handle ClientAuthenticationError by trying the operation again after a random delay
- deploy a caching proxy
