### ISSUE TITLE
'x-ms-failure-cause': 'gateway' in MCD 'x-ms-routing-request-id': 'WESTEUROPE' cause Response status: 404

### ISSUE THREAD

**Issue by the1bit** [Azure/azure-sdk-for-python#1780]
Hi,

I would like to manage the Azure subscription related metrics and alerts from Python. I have started the discovering of capabilities of this area and I am facing a serious issue. 

**I work in MCD (Microsoft Cloud Deutschland).**

When I  create Monitor client `client = MonitorManagementClient(credentials,subscription_id)` it seems everything is OK. Then I want to make a request something like this:
`metrics_data = client.metrics.list(resource_id, timespan="{}/{}".format(yesterday, today), interval='PT1H', metric='Percentage CPU', aggregation='Total')` I get an error message:
**"Operation returned an invalid status code 'Not Found'
raise models.ErrorResponseException(self._deserialize, response)"**

I tried to change the authentication to Adal but the result was same. Then I turned on the debug logging to msrest (`logging.getLogger('msrest').setLevel(logging.DEBUG);`) and i checked the result and I saw this line:
`DEBUG:msrest.http_logger:    'x-ms-routing-request-id': 'WESTEUROPE:20180111T155250Z:...'`
This is strange for me in **MCD**. This line should be **GERMANYCENTRAL** or **GERMANYNORTHEAST**.

Then I tried my code in **MCI** and it worked. I turned on the debug logging to msrest there and I saw the line is totally same:
`DEBUG:msrest.http_logger:    'x-ms-routing-request-id': 'WESTEUROPE:20180111T165801Z:...'`

Accordiongly I guess something is wrong here. I would like to ask sour support in this situation. 

_Here is the code:_
```python
from azure.common.credentials import UserPassCredentials
from azure.mgmt.monitor import MonitorManagementClient
from azure.mgmt.monitor.models import RuleMetricDataSource
from azure.mgmt.monitor.models import ThresholdRuleCondition
from azure.mgmt.monitor.models import RuleEmailAction
from msrestazure.azure_cloud import AZURE_GERMAN_CLOUD  as cloud_environment

credentials = UserPassCredentials(
    username=os.environ.get('AZURE_USER', input('Username:')),
    password=os.environ.get('AZURE_PASSWORD', getpass.getpass('Password: ')), 
    tenant=os.environ.get('AZURE_TENANT_ID', input('Tenant (AD Identifier): ')),	
    cloud_environment=cloud_environment
)
client = MonitorManagementClient(credentials,subscription_id)

metrics_data = client.metrics.list(
     resource_id,
     timespan="{}/{}".format(yesterday, today),
     interval='PT1H',
     metric='Percentage CPU', 
     aggregation='Total'
)
```

Versions:
`msrest==0.4.25`
`msrestazure==0.4.20`

Thank you for your help in this matter.

Feel free to get in touch with any further questions.

Best Regards,
Tibor

**Comment by lmazuel** [comment]
Hi @the1bit 
The metric name change depending on the resource you'd like:
https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics

Most likely you ask for a metric name that is not available for your resource. The metrics_definitions endpoints allows you to get dynamically supported metrics for a given resource. If you use something that was not returned by "metric_definitions", you will get this kind of issue.

Could you check this first? Thanks!

**Comment by the1bit** [comment]
Hi @lmazuel ,

It is clear but the issue here is not the resource. The issue here is a script **works fine in MCI** and  **does not work in MCD**.

I guess the msrest related gateway the root cause here. `DEBUG:msrest.http_logger: 'x-ms-routing-request-id': 'WESTEUROPE:20180111T155250Z:...'`

Do you understand me?

Thanks in advance.

BR,
Tibor

**Comment by lmazuel** [comment]
Gotcha.
@gucalder any opinions on this one?

**Comment by lmazuel** [comment]
Hi @the1bit 

I got a flash, I realize you didn't define the base_url in the client constructor:
```python
client = MonitorManagementClient(credentials,subscription_id,base_url=cloud_environment.endpoints.resource_manager)
```

Could you confirm this solves your issue?

**Comment by the1bit** [comment]
Hi @lmazuel ,

You are right. The base_url was missed. I fix all of my clients in the code now.
`DEBUG:msrest.http_logger:    'x-ms-routing-request-id': GERMANYCENTRAL:20180118T092418Z:...'`

Somebody should fix this in the official documantation. :-)

Thank you for your help.

CLose the Question.
