### ISSUE TITLE
Invalid legacy argument for Customer Provided Key

### ISSUE THREAD

**Issue by paulovn** [Azure/azure-sdk-for-python#17835]
The `BlobClient` class contains in many of its methods the capability to add a Customer Provided Key for encryption, by supplying a `cpk` argument that must contain a `CustomerProvidedEncryptionKey` object. Inside those methods, the `CustomerProvidedEncryptionKey`  is converted into a `CpkInfo` object, as this seems to be the object that the lower-level method wants.

However apparently the `CpkInfo` class was modified a while ago, and one of its attributes, `encryption_algorithm`, was removed, while the code in `BlobClient` still tries to set it. An example (though it happens several times in the file) can be seen at : 
https://github.com/Azure/azure-sdk-for-python/blob/e43995b5299fc79bf699061fe2a032e86ed7b2fd/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L369-L370

This produces warnings 

> encryption_algorithm is not a known attribute of class <class 'azure.storage.blob._generated.models._models_py3.CpkInfo'> and will be ignored

.... i.e.  it seems that the operation does go through, though the code seems to be a leftover

**Comment by kristapratico** [comment]
@paulovn thanks for the feedback, we'll investigate asap.

**Comment by xiafu-msft** [comment]
Thanks for reporting this!
It seems @tadam-msft had an offline sync with Isabella about removing the hard coded encryption_algorithm='AES256' from generated code and add the field encryption_algorithm back to https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_block_blob_operations.py#L54

This will be fixed soon! sorry about the inconvenience!

**Comment by tasherif-msft** [comment]
Yes I will follow up on this internally for our next release @paulovn!

**Comment by paulovn** [comment]
Great, thanks!

**Comment by tasherif-msft** [comment]
Hi @paulovn the fix has been put out https://github.com/Azure/azure-sdk-for-python/pull/18212
It will be available in our patch release happening in the next couple of days.

I will close this issue in the meantime. Let me know if you have any further questions.
