### ISSUE TITLE
blob storage: copy blob encrypted with customer provided key

### ISSUE THREAD

**Issue by paulovn** [Azure/azure-sdk-for-python#17840]
**Is your feature request related to a problem? Please describe.**
I'm trying to copy a blob that has been encrypted using a Customer Provided Key (CPK) into another blob. I'm trying to use the `start_copy_from url` method in `BlobClient`, but I cannot find a way to pass the key so that it is used. The method does not accept a `cpk` argument as others (such as `upload_blob`) do, nor do I see any other procedure to specify the key

**Describe the solution you'd like**
A way in which an encrypted blob could be copied to another blob. There might be different combinations:
* the simplest one (the one I'm trying now) would be to be able to copy the blob while keeping the CPK key (in this scenario, only one key is needed)
* a more complex one is for the key to be modified in the copy operation (i.e. one key for the source blob and another for the destination blob)
* finally, a copy with encryption status change (i.e. source blob unencrypted, destination key encrypted, or the other way around) would be the most versatile

**Describe alternatives you've considered**
Unless I missed API methods, the only way I've seen to perform this copy is a download+upload, but if the blob is a big one, it would be inconvenient, since it requires two network transfers.

**Comment by kristapratico** [comment]
Thanks for your feedback, @xiafu-msft is this a possible scenario or should this be marked as feature-request?

**Comment by xiafu-msft** [comment]
Hi @paulovn 
Thanks for reaching out. Have you taken a loot at upload_blob_from_url() api? I think that would help

**Comment by paulovn** [comment]
Thanks for the suggestion. I've tried to use `upload_blob_from_url()`. It seems it can solve half of the problem -- namely how to _write_ the blob so that it uses CPK-style encryption. But if I try to copy from a blob that is already encrypted, it fails, saying

>The blob is encrypted with customer specified encryption, but it was not provided in the request.
Time:2021-04-10T10:16:14.7841320Z
ErrorCode:CannotVerifyCopySource
Error:None

so, while it can _write_ encrypted files, it cannot _read_ them, unless there is a way to encode the encryption parameter in the `source_url` argument string. Therefore, unless I'm mistaken, it can solve the _unencrypted-to-encrypted_ copy, but not the _encrypted-to-encrypted_ case, which is the one I'm most interested in.

For the time being, my workaround is to download the data, then upload it. Not very convenient, but it works.

**Comment by xiafu-msft** [comment]
Hi @paulovn 

Sorry about the inconvenience, I think your workaround is what we are gonna suggest.
Currently blob service doesn't support decrypting a source blob during copy and re-encrypt it. We will keep it as a feature request.

Thanks again for reaching out!

**Comment by paulovn** [comment]
Ok, understood, thanks.

What about the simplest procedure of copying the blob and _keeping_ the encryption as is? (so, a bit by bit copy). This could enable a fast rename procedure for encrypted files (as a copy + delete), instead of the current download+upload workaround.

**Comment by xiafu-msft** [comment]
Hi @paulovn,

Were you using your own encryption key? I tried with encryption scope https://docs.microsoft.com/en-us/azure/storage/blobs/encryption-scope-manage?tabs=portal#create-an-encryption-scope and I can change encryption scope during upload.
For example I have a source blob encrypted using `encryption_scope_1`, when I call upload_blob_from_url(encryption_scope='encryption_scope_2') so the newly created blob is encrypted with `encryption_scope_2`

**Comment by paulovn** [comment]
Hi, many thanks for the hint. I wasn't using `upload_blob_from_url` but `start_copy_from_url`, which as far as I can see, lacks encryption arguments. Didn't notice the former did have.

In our use case we are using customer-provided keys (CPK), so if I'm not mistaken this prevents us from using an encryption scope (since the key is not stored in an Azure Key Vault, and the encryption scope needs that, from what I see). However `upload_blob_from_url` _also_ accepts a `cpk`argument, so we could use it. Although this won't work for the source blob if it is also encrypted with cpk (and hence cannot use `encryption_scope_1`).

Nevertheless we'll take a look to see if we can rewrap it somehow. Thanks again!

**Comment by tasherif-msft** [comment]
Hi @paulovn start_copy_from_url unfortunately does not support encryption scopes (https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob)
Let us know if you have any other questions! In the meantime we'll close this issue.
