### ISSUE TITLE
Creating Service Principle through Python script

### ISSUE THREAD

**Issue by nn-msft** [Azure/azure-sdk-for-python#17875]
Hello team,

One of our (internal) customers is trying to create a Service Principal using the below script.

#!/usr/bin/env python3
def auth_spn_legacy(tenant_id, client_id, client_secret, resource=None):
    """
    Unfortunately, some libraries have not been updated to use azure.core
    Thus, we need to perform 'legacy' authentication instead
    Read more:
    https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd#defaultazurecredential-object-has-no-attribute-signed-session
    Parameters:
    tenant_id (str): ID of the service principal's tenant
    client_id (str): the service principal's client ID
    client_secret (str): one of the service principal's client secrets
    resource (str): the API resource e.g., https://graph.windows.net/ for Graph API
    Returns:
    lib.azure.AzureCloudManager: an object of this class
    """
    from azure.common.credentials import ServicePrincipalCredentials
    credentials = ServicePrincipalCredentials(
        client_id=client_id,
        secret=client_secret,
        tenant=tenant_id,
        resource=resource
    )
    return credentials
def gen_password_credential():
    """
    Generate a PasswordCredential object, valid for 9 years
    Parameters:
    -
    Returns
    azure.graphrbac.models.PasswordCredential: An object of class PasswordCredential
    """
    import uuid
    import pytz
    from datetime import datetime, timedelta
    from azure.graphrbac.models import PasswordCredential
    start_date = pytz.utc.localize(datetime.utcnow())  # current time in UTC; timezone aware
    end_date = start_date + timedelta(days=3285)  # 9 years
    # PasswordCredential
    # https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.models.html#azure.graphrbac.models.PasswordCredential
    password = PasswordCredential(
        start_date=start_date.isoformat(),
        end_date=end_date.isoformat(),
        key_id=str(uuid.uuid4()),
        value="cookies"
    )
    return password
def create_service_principal(credentials, tenant_id, service_principal_name):
    """
    Create a Service Principal that complies with the naming standard
    Parameters:
    credentials: a credentials object
    tenant_id: the tenant id
    service_principal_name (str): the name for the service principal (SPN)
    Returns:
    -
    """
    from azure.graphrbac import GraphRbacManagementClient
    from azure.graphrbac.models import ServicePrincipalCreateParameters, ApplicationCreateParameters, Application
    # GraphRbacManagementClient
    # https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.html#azure.graphrbac.graph_rbac_management_client.GraphRbacManagementClient
    #
    rbac_client = GraphRbacManagementClient(
        credentials=credentials,
        tenant_id=tenant_id
    )
    # ApplicationCreateParameters
    # https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.models.html#azure.graphrbac.models.ApplicationCreateParameters
    app_parameters = ApplicationCreateParameters(display_name=service_principal_name)
    # ApplicationsOperations
    # https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.operations.html#azure.graphrbac.operations.applications_operations.ApplicationsOperations.create
    #
    print(f"Creating application {service_principal_name} ...")
    result = rbac_client.applications.create(parameters=app_parameters)
    print(f"Result: {result}")
    # result is object of Application
    # https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.models.html#azure.graphrbac.models.Application
    #
    # ServicePrincipalCreateParameters
    # https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.models.html#azure.graphrbac.models.ServicePrincipalCreateParameters
    #
    parameters = ServicePrincipalCreateParameters(
        app_id=result.as_dict()['app_id'],
        account_enabled=True,
        app_role_assignment_required=False,
        password_credentials=[  # a pair of password credentials
            gen_password_credential(),
            gen_password_credential()
        ],
        service_principal_type='Application'
    )
    # ServicePrincipalsOperations
    # https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.operations.html#azure.graphrbac.operations.service_principals_operations.ServicePrincipalsOperations
    #
    print(f"Creating SPN ...")
    result = rbac_client.service_principals.create(parameters=parameters)
    # result is object of ServicePrincipal
    # https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.models.html#azure.graphrbac.models.ServicePrincipal
    #
    print(f"Created SPN with {result.as_dict()}")
if __name__ == "__main__":
    import uuid
    TENANT_ID = {Tenant_ID}
    spn = f"cookie-monster-{uuid.uuid4()}"
    credentials = auth_spn_legacy(
        tenant_id=TENANT_ID,
        client_id={Client-ID},
        client_secret={Client Secret},
        resource="https://graph.windows.net/"
    )
    create_service_principal(
        credentials=credentials,
        tenant_id=TENANT_ID,
        service_principal_name=spn
    )

The customer is using the below documentation-
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-graphrbac/0.61.1/azure.graphrbac.models.html#module-azure.graphrbac.models.user_create_parameters_py3

The customer reported that he is able to create a Service Principal using the script but on Portal, he is not able to see Client ID. The created Service Principle works fine though.

![py-test-03-jpeg](https://user-images.githubusercontent.com/75340668/113898400-d7b9ca80-9799-11eb-8f2e-c09610a71296.jpeg)

He is able to create it using Az CLI command but he needs to create 1000 Service Principle having different names, hence he wants to achieve the same via Python script.

Any advice would be greatly appreciated. 

Thank you in advance.

Edit-1: My apologies for mixing up Application ID and Client Secret.
The customer is unable to see Client Secret [As per the screenshot shared, Apologies for the quality of the screenshot shared] 
On HomePage of Service Principle, the customer sees weird text for Application ID URI. Is it possible for you to check this part as well? 

Thank you once more in advance. I wholeheartedly appreciate your efforts in looking into this.

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
