### ISSUE TITLE
DefaultAzureCredential problem

### ISSUE THREAD

**Issue by akdasari** [Azure/azure-sdk-for-python#17871]
Hi I'm trying to construct the  "ContainerRepositoryClient" as follows
```
from azure.containerregistry import ContainerRepositoryClient
from azure.identity import DefaultAzureCredential

default_credential = DefaultAzureCredential()
account_url = "https://testacr.azurecr.io"
client = ContainerRepositoryClient(endpoint=account_url, repository="helloworld", credential=default_credential)
tag_props = client.get_tag_properties(image_tag)
```
This I'm running through one of my python method.. I have previously constructed  "ContainerRegistryManagementClient" using service principal creds. And that works well for most of my ACR Registry operations
But this  DefaultAzureCredential() I can't construct as i don;t have env variables.. 
Is there any alternative to build  "ContainerRepositoryClient" ? which I need to delete the image with tags
This throws error like this
```
Default Azure Credential failed to retrieve a token from the included credentials. Attempted credentials: EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. ManagedIdentityCredential: Unexpected response '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
```

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by akdasari** [comment]
ok , now i have sorted out my problem by setting env variables..

**Comment by chlowell** [comment]
Great, I'll close this issue then. Please reopen it if you continue to have similar problems, or open a new one if you encounter a different problem.
