### ISSUE TITLE
[BUG] Event Grid samples are not showing up in docs.microsoft.com/samples/browse

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#17895]
We expect all the samples that live in this repo to show up in https://docs.microsoft.com/samples/browse
We do this by adding the right metadata in the readme file that lives in the folder that has the samples.

If you see this [search query for Event Grid samples in Python](https://docs.microsoft.com/en-us/samples/browse/?products=azure-event-grid&languages=python), there are no results for samples for Event Grid SDK

Compare this with the [search query for Event Grid samples in JS]https://docs.microsoft.com/en-us/samples/browse/?filter-products=grid&products=azure-event-grid&languages=javascript) and you will see samples for Event Grid SDK. Same for .NET

**Comment by ramya-rao-a** [comment]
Can we keep this issue open until the sample actually starts showing up in docs.microsoft.com/samples/browser?

**Comment by rakshith91** [comment]
@ramya-rao-a Verified that the samples are reflecting in the search query

Here's the link https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/eventgrid-samples/

**Comment by ramya-rao-a** [comment]
Yay! Thanks!
