### ISSUE TITLE
Problems with the azure libraries and Ansible

### ISSUE THREAD

**Issue by grindthemall** [Azure/azure-sdk-for-python#1791]
I'm trying to use the azure python libraries with Ansible.  OS is Ubuntu in the Windows linux subsystem.

When running the inventory script I get the following error:

./inventory/azure_rm.py
The Azure python sdk is not installed (try 'pip install azure') - No module named compute

However when I ask pip to install the library, it appears to be already there:

PC1:/mnt/d/UserPhil/Documents/Onecode/ansible-deploy$ sudo pip install azure-mgmt-compute
Requirement already satisfied: azure-mgmt-compute in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: msrestazure~=0.4.7 in /usr/local/lib/python2.7/dist-packages (from azure-mgmt-compute)
Requirement already satisfied: azure-common~=1.1.5 in /usr/local/lib/python2.7/dist-packages/azure_common-1.1.8-py2.7.egg (from azure-mgmt-compute)
Requirement already satisfied: azure-mgmt-nspkg>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from azure-mgmt-compute)
Requirement already satisfied: keyring>=5.6 in /usr/local/lib/python2.7/dist-packages (from msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: adal~=0.4.7 in /usr/local/lib/python2.7/dist-packages (from msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: msrest<2.0.0,>=0.4.25 in /usr/local/lib/python2.7/dist-packages (from msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: azure-nspkg>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from azure-mgmt-nspkg>=2.0.0->azure-mgmt-compute)
Requirement already satisfied: secretstorage; sys_platform == "linux2" or sys_platform == "linux" in /usr/local/lib/python2.7/dist-packages (from keyring>=5.6->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: python-dateutil>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: cryptography>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: PyJWT>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: requests-oauthlib>=0.5.0 in /usr/local/lib/python2.7/dist-packages (from msrest<2.0.0,>=0.4.25->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from msrest<2.0.0,>=0.4.25->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: isodate>=0.5.4 in /usr/local/lib/python2.7/dist-packages (from msrest<2.0.0,>=0.4.25->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: enum34>=1.0.4; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from msrest<2.0.0,>=0.4.25->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil>=2.1.0->adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1.0->adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1.0->adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1.0->adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1.0->adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: oauthlib>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from requests-oauthlib>=0.5.0->msrest<2.0.0,>=0.4.25->msrestazure~=0.4.7->azure-mgmt-compute)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.1.0->adal~=0.4.7->msrestazure~=0.4.7->azure-mgmt-compute)

Suggestions?

**Comment by lmazuel** [comment]
Ansible has a specific set of SDK versions compatible. You need to install ansible with "pip install ansible[azure]"
http://docs.ansible.com/ansible/latest/guide_azure.html
