### ISSUE TITLE
Unable to open authentication session on connection

### ISSUE THREAD

**Issue by mattgaviota** [Azure/azure-sdk-for-python#17910]
- **Package Name**: azure-servicebus
- **Package Version**: 7.1.1
- **Operating System**: Debian buster
- **Python Version**: 3.8.9

**Describe the bug**
Some days using ServiceBusClient to connect to a topic. After connecting it fails with a ServiceBusConnectionError exception. The weird thing is that there are days that it works correctly and then for no apparent reason, it starts with connection problems.

**To Reproduce**
1. In my service im using a code very similar to the receive_subscription_async sample.

**Expected behavior**
That the connection works correctly without interruptions

**Screenshots**

**Additional context**
The complete traceback is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 208, in _do_retryable_operation
    return await operation(**kwargs
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 314, in _open
    await self._handler.open_async(connection=self._connection
  File "/usr/local/lib/python3.8/site-packages/uamqp/async_ops/client_async.py", line 246, in open_async
    await self._build_session_async()
  File "/usr/local/lib/python3.8/site-packages/uamqp/async_ops/client_async.py", line 192, in _build_session_async
    self._connection._cbs = await asyncio.shield
  File "/usr/local/lib/python3.8/site-packages/uamqp/authentication/cbs_auth_async.py", line 72, in create_authenticator_async
    raise errors.AMQPConnectionError
uamqp.errors.AMQPConnectionError: Unable to open authentication session on connection b'SBReceiver-6f3c66f6-d786-44f0-a0f7-74396392b73c'.
Please confirm target hostname exists: b'prod01.servicebus.windows.net
During handling of the above exception, another exception occurred
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 70, in main
    async with receiver:
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 131, in __aenter__
    await self._open_with_retry()
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 332, in _open_with_retry
    return await self._do_retryable_operation(self._open
  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/aio/_base_handler_async.py", line 222, in _do_retryable_operation
    raise last_exception
azure.servicebus.exceptions.ServiceBusConnectionError: Unable to open authentication session on connection b'SBReceiver-6f3c66f6-d786-44f0-a0f7-74396392b73c'.
Please confirm target hostname exists: b'prod01.servicebus.windows.net'
```

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by yunhaoling** [comment]
hey @mattgaviota, thanks for reaching out -- usually the error indicates there're networking issues that the client failed to connect to the service.

- How often does the issue happen, are you able to reproduce the issue stably?
- are you able to recover from the connection error (etc. creating a new service bus client and receiver)?

**Comment by mattgaviota** [comment]
Hello, thanks for the answer. It happens quite often, especially lately. The unusual thing is that we have two identical environments and in one it fails and in the other it does not. With both running the same code.
For what it's worth, I'm using a shared access policy for each topic, but I've tried a service bus policy and it hasn't worked for me either.

**Comment by yunhaoling** [comment]
have you tried wrapping your code with retry to see if the program could recover from the connection error -- like the following snippets:

```python
retry_time = 0
retry_total = 5
while retry_time < retry_total:
    try:
        async with ServiceBusClient.from_connection_string(...) as sb_client
            async with sb_client.get_queue_receiver() as receiver:
            # receiving logic
  except azure.servicebus.exceptions.ServiceBusConnectionError:
      retry_time += 1
      # time.sleep()
      # logging
```

I think one more piece of information we could gather is the amqp networking tracing, which would give us the underlying amqp activities and we could check from the logging whether if there's any socket error happening. It could be turned on via the `logging_enable` keyword argument when creating the service bus client:
```python
import logging
logging.basicConfig(level=logging.INFO)
# you could have more configurations on logging, like output into a file
ServiceBusClient.from_connection_string(..., logging_enable=True) 
```

**Comment by mattgaviota** [comment]
I'm going to try manual retries, so far I had used the parameters:
```python
```

**Comment by mattgaviota** [comment]
I'm going to try manual retries, so far I had used these parameters
```python
async def main():
    servicebus_client = ServiceBusClient.from_connection_string(
        conn_str=<endpoint_connection>,
        logging_enable=True,
        transport_type=2, # tried with 1 as well
        retry_total=10,
        retry_backoff_factor=1,
        retry_backoff_max=30,
    )
    while True:
        async with servicebus_client:
            receiver = servicebus_client.get_subscription_receiver(
                topic_name="topic",
                subscription_name="subscription",
            )
            async with receiver:
                received_messages = await receiver.receive_messages(
                    max_message_count=10, max_wait_time=5
                )
                for message in received_messages:
                    # do something
```
The logging_enable doesn't show me anything even though I use other logs to check some things

**Comment by yunhaoling** [comment]
hey @mattgaviota , how are things going on your side, did you observe any uncommon error in the logging?
