### ISSUE TITLE
azure-mgmt-resourcegraph 7.0.0 The resource type 'resources' could not be found in the namespace 'Microsoft.ResourceGraph' for api version '2020-04-01-preview'.

### ISSUE THREAD

**Issue by jackchen1680** [Azure/azure-sdk-for-python#17932]
- **Package Name**: 
- azure-mgmt-resourcegraph 
- **Package Version**: 
- 7.0.0
- **Operating System**:
- Windows 10
- **Python Version**: 
3.7
**Describe the bug**
①Get resourcegraph_client as bellow
`resourcegraph_client = ResourceGraphClient(
        credential=credential,
        base_url="https://management.chinacloudapi.cn/",
        credential_scopes = ["https://management.chinacloudapi.cn/.default"]
    )`
②Build Query and send query
`query = QueryRequest(
            query='project id, tags, properties | limit 2',
            subscriptions=[SUBSCRIPTION_ID]
        )
    query_response = resourcegraph_client.resources(query)`
③ Call failed，error message like this 
azure.core.exceptions.ResourceNotFoundError: (InvalidResourceType) The resource type 'resources' could not be found in the namespace 'Microsoft.ResourceGraph' for api version '2020-04-01-preview'. The supported api-versions are '2018-09-01-preview,2019-04-01'.

④ changed the api version，but still call failed
` resourcegraph_client._config.__setattr__("api_version","2019-04-01")`

Please help troubleshoot  and solve this issue

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by jackchen1680** [comment]
Hi krista ,  is there any updates about this issue?

**Comment by kristapratico** [comment]
@chiragg4u could you take a look at this issue? thanks.

**Comment by jackchen1680** [comment]
Hi  krista & @chiragg4u, is there any updates about this issue? Please help investigate this issue as soon as possible , Thanks

**Comment by kristapratico** [comment]
@msyyc could you take a look?

**Comment by msyyc** [comment]
@RAY-316 Please help on this issue

**Comment by jackchen1680** [comment]
Hi All，is there any updates about this issue? Please help investigate this issue as soon as possible , Thanks

**Comment by jackchen1680** [comment]
Hi @RAY-316 @msyyc ，This issue has been going on for some days and there is still no further reply. Please help investigate this issue as soon as possible. thx.

**Comment by 00Kai0** [comment]
@jackchen1680 Was it work when you used old version of SDK?
And can you try with this new released SDK:https://pypi.org/project/azure-mgmt-resourcegraph/

**Comment by jackchen1680** [comment]
@00Kai0 yes, i tried use new released 8.0.0,  The error reported is almost the same as the error reported in version 7.0.0。
 is work when use version 2.0.0, but because credential system has been completly revamped in new version 7.0.0 and 8.0.0。
 so please help me how can i use resourcegraph_client(in V7.0.0  or V8.0.0) to query successfully.

**Comment by msyyc** [comment]
@service team. According to the error message of the issue, it seems that new api-version '2020-04-01-preview' is not supported. The supported api-versions are '2018-09-01-preview, 2019-04-01'. But in swagger repo, '2020-04-01-preview' have been merged into 'master' for a long time. Could you help confirm that?

**Comment by jackchen1680** [comment]
@msyyc @service is there any updates about this issue?

**Comment by jackchen1680** [comment]
Hi @00Kai0 @msyyc @service，I haven't received any reply for long time， is there any updates about this issue?

**Comment by msyyc** [comment]
@service team. According to the error message of the issue, it seems that new api-version '2020-04-01-preview' is not supported. The supported api-versions are '2018-09-01-preview, 2019-04-01'. But in swagger repo, '2020-04-01-preview' have been merged into 'master' for a long time. Could you help confirm that?

**Comment by dramuy** [comment]
For Mooncake, we don't have the support for 2020-04-01-preview; we published latest api-version 2021-03-01 instead. Please use the 2021-03-01 api-version.
