### ISSUE TITLE
Support CAE in data-plane SDKs using `azure-core`

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#17939]
As tested, Microsoft Graph API already has CAE enabled.

```
> az rest -m POST -u https://graph.microsoft.com/v1.0/me/revokeSignInSessions --debug

cli.azure.cli.core.util: Request URL: 'https://graph.microsoft.com/v1.0/me/revokeSignInSessions'
cli.azure.cli.core.util: Request method: 'POST'

cli.azure.cli.core.util: Response status: 401
cli.azure.cli.core.util: Response headers:
cli.azure.cli.core.util:     'WWW-Authenticate': 'Bearer realm="", authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize", client_id="00000003-0000-0000-c000-000000000000", error="insufficient_claims", claims="eyJhY2Nlc3NfdG9rZW4iOnsibmJmIjp7ImVzc2VudGlhbCI6dHJ1ZSwgInZhbHVlIjoiMTYxNzk0OTgyMSJ9fX0="'
cli.azure.cli.core.util: Response content:
cli.azure.cli.core.util: {
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Continuous access evaluation resulted in claims challenge with result: InteractionRequired and code: TokenIssuedBeforeRevocationTimestamp",
    "innerError": {
      "date": "2021-04-09T06:30:21",
      "request-id": "83512124-7723-46a4-bbae-62c5dfe446a9",
      "client-request-id": "83512124-7723-46a4-bbae-62c5dfe446a9"
    }
  }
}
```

Currently CAE support is only added to `azure-mgmt-core`:

https://github.com/Azure/azure-sdk-for-python/blob/66de1137fa384dc7cff50f8544df029976d6f3cb/sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_authentication.py#L41

Perhaps `azure-core` is a better place to support CAE so that all data-plane SDKs can benefit from it.

**Comment by chlowell** [comment]
Our first beta of claims challenge handling actually was implemented in `azure-core`. We moved that logic into `azure-mgmt-core` because at this time only track 2 ARM client libraries need CAE support and it isn't certain that we can provide an implementation appropriate for all data plane libraries. We will reevaluate this when more RPs support CAE.

**Comment by chlowell** [comment]
Closing this for now because I don't expect to have sufficient CAE implementations in the medium-term to warrant refactoring them.
