### ISSUE TITLE
Querying resource properties programmatically 

### ISSUE THREAD

**Issue by SachinBadgujar** [Azure/azure-sdk-for-python#1794]
Hello Team, I am using ResourceManagementClient().resources.list() to get all my resources. However, I want to get property of each of this resource (let's say function app, SQL data warehouse, and API management). Which library should be used? Among all different packages, how to figure out which service belong to which package? ( Service 'function' --> package ? to list all functions )
Thanks

**Comment by lmazuel** [comment]
Hi @SachinBadgujar 
Usually, the package are at the Resource Provider (RP) level. Example, the "Microsoft.Compute" provider is inside the "azure-mgmt-compute" package. For [Function](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/getfunction), they are under the "Microsoft.Web" RP, and then in the package "azure-mgmt-web".
If you need a programmatic way to know from a RP what is the package to use, we don't have that :/. Naming is pretty consistent and in 95%, that's really just the RP name.

**Comment by lmazuel** [comment]
Closing, since I think the initial question is answered. If I miss something, feel free to comment or open a new issue.
Thank you
