### ISSUE TITLE
Queue and subscriber properties are missing?

### ISSUE THREAD

**Issue by rndfm** [Azure/azure-sdk-for-python#17940]
**Is your feature request related to a problem? Please describe.**
I need to get the current message count and deadletter message count for a subscription.

**Describe the solution you'd like**
Seams that earlier versions of the SDK had a get_properties() function on the now replaced SubscriptionClient class.
Would be nice to have similar functionality in the current version.

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by yunhaoling** [comment]
hey @rndfm , thanks for reaching out.

are you using the latest v7 version? -- we have restructured our library and mgmt operations related to service bus entities have now been moved into a standalone class called `ServiceBusAdministrationClient` which is under module `azure.servicebus.management`(sync) and `azure.servicebus.aio.management`(async).

For your case, in v7 you could retrieve the current message count and deadletter message count by the following code:
```python
with ServiceBusAdministrationClient.from_connection_string(CONNECTION_STR) as servicebus_mgmt_client:
    subscription_runtime_properties = servicebus_mgmt_client.get_subscription_runtime_properties(TOPIC_NAME, SUBSCRIPTION_NAME)
    print(subscription_runtime_properties.dead_letter_message_count)
    print(subscription_runtime_properties.active_message_count)
    print(subscription_runtime_properties.total_message_count)
    # ...
```

We have more `ServiceBusAdministrationClient` samples (starting with mgmt_*) [here](
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples) and [api reference doc](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/7.1.1/azure.servicebus.management.html#module-azure.servicebus.management) on what `ServiceBusAdministrationClient` provides.

Let me know if you have any questions!
