### ISSUE TITLE
Upload large files to blob from http request (memory problem)

### ISSUE THREAD

**Issue by Nicole227** [Azure/azure-sdk-for-python#17941]
#Used version: azure-storage-blob==**12.8.0**

**Is your feature request related to a problem? Please describe.**
https://github.com/Azure/azure-storage-python/issues/676

Hello everyone,
the upload_blob api causes a memory overflow. A tool downloads large files (up to 40 GB) from a flexnet server and uploads them directly to a blob container. Unfortunately the complete file is written to the working memory. One suspicion is that it is due to upload_blob api. Do you have an idea how we can solve this problem?

**Describe the solution you'd like**
Is there any possibility that the complete file is not in memory when uploading them?

**Describe alternatives you've considered**
Can we use an other api?

**Additional context**

r = requests.get("https://download.flexnetoperations.com***6f269f3&ext=.tar", stream=True)             
for chunk in r.iter_content(chunk_size=4 * 1024 * 1024):
      blob_client.upload_blob(chunk, blob_type="AppendBlob")

we tried also:

block_list = []
with requests.get(self.download_link, stream=True) as r:
	r.raise_for_status()
	for chunk in r.iter_content(chunk_size=4*1024*1024):
		block_id = str(uuid.uuid4())
		blob_client.stage_block(block_id=block_id, data=chunk)
		block_list.append(BlobBlock(block_id=block_id))
blob_client.commit_block_list(block_list)

Best Regards Nicole

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by tasherif-msft** [comment]
Hi @Nicole227, you can use the memory efficient upload algorithm by decreasing `min_large_block_upload_threshold` when instantiating your client. This threshold defaults to 4MB+1Byte the default chunk size for `upload_blob` is 4MB and hence it will use the non memory efficient upload by default (as it is more runtime optimized)

So you can simply do 
```
r = requests.get("https://download.flexnetoperations.com***6f269f3&ext=.tar", stream=True)
for chunk in r.iter_content(chunk_size=4 * 1024 * 1024):
    blob_client.upload_blob(chunk, max_block_size=4 * 1024 *1024 +2)  #BlockBlob type
```
We have also put out a fix that will be in our next release for using generators when doing uploads - i.e, you can yield chunks manually and pass that generator to upload_blob() which would cut down on memory cost.

Let me know if you need any further help

**Comment by Nicole227** [comment]
Hi @tasherif-msft,
thank you for your help. The decrasing of  ```min_large_block_upload_threshold``` hepls a lot. But I must set it by ```BlobServiceClient()```. Otherwise I got the following error: "**_request() got an unexpected keyword argument max_block_size_**". But with this method the memory efficient upload now remains the same continuously. I also had to use the append block type, since appending chunks to the block blob led to an error. This may be due to the blob storage version we used.

```python
from azure.storage.blob import BlobServiceClient

blob_service_client = BlobServiceClient.from_connection_string(
                    blob_secret,  max_block_size=4 * 1024 * 1024 + 2)
blob_client = blob_service_client.get_blob_client(
            container="ContainerName", blob="BlobName")
r = requests.get("https://download.flexnetoperations.com***6f269f3&ext=.tar", stream=True)
for chunk in r.iter_content(chunk_size=4 * 1024 * 1024):
    blob_client.upload_blob(chunk, blob_type="AppendBlob")
```

We would be very happy to use generators for upload, it could maybe increase the upload speed.

**Comment by tasherif-msft** [comment]
Hi @Nicole227, Indded that parameter is a client parameter. I will also look into why the memory efficient algorithm isn't currently available for append blob types. Otherwise generators would work very well since it seems you're iterating per chunks anyway. There is currently a small bug that has been fixed for being able to upload from generators. That fix will be released in the next couple of days in a patch release. 
Which version are you using?

**Comment by Nicole227** [comment]
Hi @tasherif-msft,
thanks for your response. Exactly it is strange why append blob not use a memory efficient algorithm only if max_blob_size set as client parameter. We are currently using the version azure-storage-blob==12.8.0, but we will upgrade with the new release.

Best Regards
Nicole

**Comment by mcfuhrt** [comment]
@Nicole227
Is there any news on this?

> HiNicole227, indeed that parameter is a client parameter. I will also look into why the memory efficient algorithm isn't currently available for append blob types. Otherwise generators would work very well since it seems you're iterating per chunks anyway. There is currently a small bug that has been fixed for being able to upload from generators. That fix will be released in the next couple of days in a patch release.
Which version are you using?

Is there any documentation on how an upload via generators works?
