### ISSUE TITLE
azure.mgmt.logic.models.RecurrenceSchedule is badly formatted

### ISSUE THREAD

**Issue by Rafal-Spryszynski** [Azure/azure-sdk-for-python#1798]
When trying to change autoscale settings I get the following error: 

> UnsupportedRequestContent, Request content is not well formed or supported.

The time zone property is missing.

After a fix I get the next error.

> BadRequest, The autoscale setting that you provided has an invalid recurrence schedule with days null or empty. Specify valid days.

The reason is that there is wrong JSON key used. It should be 'days', but it is 'weekDays'.

Simple fixes to azure.mgmt.logic.models.RecurrenceSchedule are required:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-logic/azure/mgmt/logic/models/recurrence_schedule.py

I had created a pull request:
https://github.com/Azure/azure-sdk-for-python/pull/1797

**Comment by lmazuel** [comment]
Hi @Rafal-Spryszynski 
I see that this issue is not fixed yet, and sent a direct email to the LogicApp team for follow-up. Sorry it takes so long to fix something that should be simple :(

**Comment by xiangyan99** [comment]
@Rafal-Spryszynski could you help to check if this is still broken?

**Comment by Rafal-Spryszynski** [comment]
Sorry, but it is not possible for me to check it anymore. This issue might be closed.

**Comment by xiangyan99** [comment]
@Rafal-Spryszynski Thank you for the reply. We will close the issue and please feel free to reopen it if you see it again.
