### ISSUE TITLE
[opentelemetry] correct sample slug in sample READMEs

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#17991]
The [sample slugs](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/core/azure-core-tracing-opentelemetry/samples) (the metadata under `products`) for azure-core-tracing-opentelemetry and azure-monitor-opentelemetry-exporter do not match any of the valid options found here:
https://review.docs.microsoft.com/en-us/help/contribute/metadata-taxonomies?branch=master#product

These need to be updated so that [samples](https://docs.microsoft.com/en-us/samples/browse/?languages=python) publish correctly.

**Comment by heaths** [comment]
I've had to remove this line from core for now as it was blocking a merge.
