### ISSUE TITLE
Why client_id value is always the same?

### ISSUE THREAD

**Issue by michalswi** [Azure/azure-sdk-for-python#18008]
I am wonder why **client_id** value if I don't use specific Service Principal is always the same?  
`client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46`  
doesn't matter if I use `az cli` or `terraform`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd8ccc8-1b24-1cf2-a244-0b619c80b0ba
* Version Independent ID: fe03e080-3af9-eaa3-54a3-ea5d94ccbfa0
* Content: [azure.identity.DeviceCodeCredential class](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.devicecodecredential?view=azure-python)
* Content Source: [docs-ref-autogen/azure-identity/azure.identity.DeviceCodeCredential.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-identity/azure.identity.DeviceCodeCredential.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by chlowell** [comment]
`client_id` here is the ID of the Azure AD application the credential will authenticate users to, not a service principal ([this document](https://docs.microsoft.com/azure/active-directory/develop/app-objects-and-service-principals#relationship-between-application-objects-and-service-principals) describes the relationship between applications and service principals). The value shown in the documentation is only the default; it is configurable:
```py
# this credential will authenticate users to 04b07795-8ddb-461a-bbee-02f9e1bf7b46 (Azure CLI)
DeviceCodeCredential()

# this credential will authenticate users to MY_APPLICATION
DeviceCodeCredential(client_id=MY_APPLICATION)
```

**Comment by michalswi** [comment]
All I want to understand here is why if I don't specify my own client_id I will always have client_id with this specific value **04b07795-8ddb-461a-bbee-02f9e1bf7b46** so this value is the default value for Azure AD or what?

**Comment by chlowell** [comment]
As I wrote above, this is the client ID for the Azure CLI. The login page also points that out: "You're signing in to **Microsoft Azure Cross-platform Command Line Interface** on another device...". We use it as a default because Azure AD doesn't have a default--a user must authenticate to some specific application. The Azure CLI is a good default for us because we can assume it's registered in a user's tenant and has access to the APIs our clients use.
