### ISSUE TITLE
[Storage] Does BlobClient.Exists() function correctly for blobs encrypted with CPK?

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-python#18041]
https://github.com/Azure/azure-sdk-for-net/issues/20361

**Comment by tasherif-msft** [comment]
Will implement this fix in Python

**Comment by seanmcc-msft** [comment]
To clarify, the scenario is calling `BlobBaseClient.Exists()` with a BlobClient that does not have CPK, on a blob that does have CPK.  We get 409 - blob encrypted with user-provided key from the service.  Since the blob clearly exists, we should return true instead of throwing.

**Comment by tasherif-msft** [comment]
Yep! makes sense
