### ISSUE TITLE
Use docs.ms version of sphinx in github.io docs generation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#18048]
Docs CI uses version today: 1.5.5
Recommended version: 3.5 

Docs CI is planning to upgrade to a more recent version of Sphinx and keep upgrading the version going forward (may not always be on the latest but should only be a few months behind). The expectation is that this work will finish in a few months.

**Comment by kurtzeborn** [comment]
My vote is to have docs.ms to update their Sphinx tooling rather than us trying to go back in time.

**Comment by scbedd** [comment]
This is happening in the new version of the docs pipeline. They are jumping to a minimum of sphinx 4.
