### ISSUE TITLE
Is it possible to get the UserName instead of ObjectID for ADLS2 folder's ACL

### ISSUE THREAD

**Issue by mszdong** [Azure/azure-sdk-for-python#18053]
I follow this sample to get the ADLS2 hierarchy's ACL:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/samples/datalake_samples_access_control.py

I somehow get the "username" only one or two times, and then I can only get the user/group's Object ID, want to check if somehow I can get it without go to AAD to query it?

same code as below:
        directory_client = filesystem_client.get_directory_client(path.name)
        acl_props = directory_client.get_access_control()

thanks!

**Comment by xiafu-msft** [comment]
can you try to set upn=True when calling get_access_control() and see if that helps?
