### ISSUE TITLE
[ComputeManagementClient.virtual_machines] Documentation incorrect

### ISSUE THREAD

**Issue by webstc2** [Azure/azure-sdk-for-python#18071]
- **Package Name**: azure-mgmt-compute
- **Package Version**:  Any
- **Operating System**: Any
- **Python Version**:  Any

**Describe the bug**
The documentation for previous versions of the python api such as for "azure.mgmt.compute.v2019_07_01.operations.virtualmachinesoperations" is incorrect. They document functions that do not exist in those versions such as "begin_restart" or "begin_deallocate". The actual functions should be "restart" or "deallocate". I'm not sure what versions of the api these functions were created but this issue applies to every historical version. This documentation used to be correct and appears to have been erroneously updated at some point.

[https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2019_07_01.operations.virtualmachinesoperations?view=azure-python](https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2019_07_01.operations.virtualmachinesoperations?view=azure-python)

**Screenshots**
![image](https://user-images.githubusercontent.com/80053825/114878982-66e06700-9dc6-11eb-8a68-02a7bd26935c.png)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
After 17.0.0b1(https://pypi.org/project/azure-mgmt-compute/17.0.0b1/#history),  azure-mgmt-compute have migrated from track1 version to track2 version. The difference is : https://github.com/Azure/azure-sdk-for-python/blob/master/doc/sphinx/python_mgmt_migration_guide.rst
