### ISSUE TITLE
[core] HttpResponseError doesn't have .error when it's a streaming response

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#18086]
Currently, calling `.error` on an `HttpResponseError` that was the result of a stream response will always be `None`.

We want to make `.error` an `@property`, so we can call `_parse_odatav4` when users first access `.error` (and cache the result).

With LLC compatibility, we also want to raise `ResponseNotReadError` if users haven't read the stream yet

**Comment by msyyc** [comment]
| version tolerant | [need_request_converter](https://github.com/Azure/autorest.python/blob/5ce293ac4107a1eea96bc83cb305d6c887cdc6a6/packages/autorest.python/autorest/codegen/models/client.py#L266-L275) | HttpResponse Type | read function
|------------------|-------------|-------------|----------------
|false | true | [azure.core.pipeline.transport](https://github.com/Azure/autorest.python/blob/5ce293ac4107a1eea96bc83cb305d6c887cdc6a6/packages/autorest.python/test/azure/legacy/Expected/AcceptanceTests/AzureBodyDuration/bodyduration/operations/_duration_operations.py#L21)| xx
|true | false| [azure.core.rest](https://github.com/Azure/autorest.python/blob/5ce293ac4107a1eea96bc83cb305d6c887cdc6a6/packages/autorest.python/test/azure/legacy/Expected/AcceptanceTests/AzureBodyDuration/bodyduration/operations/_duration_operations.py#L21)| xx
