### ISSUE TITLE
Content too old to follow

### ISSUE THREAD

**Issue by Shaybs** [Azure/azure-sdk-for-python#18102]
Title is self explanatory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ed4c7a-93f1-9212-6e4a-750eae1b3e4c
* Version Independent ID: 24407c78-d20a-3252-c8a1-85e3114bf650
* Content: [Azure MySQL/PostgreSQL libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/postgresql-mysql?view=azure-python)
* Content Source: [docs-ref-services/latest/postgresql-mysql.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/postgresql-mysql.md)
* Product: **azure**
* Technology: **azure**
* GitHub Login: @lisawong19
* Microsoft Alias: **routlaw**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.
