### ISSUE TITLE
arecords is not a known attribute of class RecordSet

### ISSUE THREAD

**Issue by max-tet** [Azure/azure-sdk-for-python#18127]
- **Package Name**: `azure-mgmt-dns`
- **Package Version**: 8.0.0
- **Operating System**: Arch Linux
- **Python Version**: 3.9.3

**Describe the bug**
When creating a `RecordSet` with the attribute `arecords`, the following warning is logged: `arecords is not a known attribute of class <class 'azure.mgmt.dns.v2018_05_01.models._models_py3.RecordSet'> and will be ignored`. In fact, when inspecting the source of the `RecordSet` class, you can see that the attribute `a_record` is expected. However, [the documentation](https://docs.microsoft.com/en-us/python/api/azure-mgmt-dns/azure.mgmt.dns.v2018_05_01.models.recordset?view=azure-python#parameters) indicates that the attribute should be `arecord` and in some earlier version of the package this must have been correct.

**To Reproduce**
1. Attempt to create a `RecordSet` the the wrong attribute name

**Expected behavior**
Documentation and implementation should match. Also, I would expect the API to be stable, in particular since multiple APIs from different points in time are included.

**Comment by mccoyp** [comment]
Hi @max-tet, thank you for opening this issue! We'll investigate ASAP.

**Comment by jsntcy** [comment]
It's a breaking change due to codegen tool upgraded. 8.0.0 is our next generation SDK (track 2) generated by our new codegen tool.
3.0.0 is track 1 which uses `arecode`, and 8.0.0 is track 2 SDK which uses `a_record`.
@lmazuel for more comments.

**Comment by lmazuel** [comment]
The documentation has been updated to the new version of the package, we believe the problem is solved, since we do want to keep the change. Thanks!

**Comment by max-tet** [comment]
Solved, thanks!
