### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iter' in 

### ISSUE THREAD

**Issue by cbare** [Azure/azure-sdk-for-python#18129]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.8.0
- **Operating System**: Windows 10 21H1
- **Python Version**: 3.8.5

I got the following error when trying to work with a blob container using the Azure SDK for Python:

```
  File "[...]/python3.8/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "[...]/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "[...]/python3.8/site-packages/azure/storage/blob/_list_blobs_helper.py", line
79, in _get_next_cb
    process_storage_error(error)
  File "[...]/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 98, in process_storage_error
    for info in error_body.iter():
AttributeError: 'dict' object has no attribute 'iter'
```

The underlying cause was a mistaken account_url "dfs.core.windows.net" where it should have been "blob.core.windows.net", something like this:

``` Python
        service = BlobServiceClient(
            account_url="https://mydatalake.dfs.core.windows.net/",
            credential=credential
        )
```

The expected behavior would be to report the error message. But instead, an error happens in line 97 of `_shared/response_handlers.py` in the function `process_storage_error`. The relevant lines are:

``` python
[95]       error_body = ContentDecodePolicy.deserialize_from_http_generics(storage_error.response)
[96]        if error_body:
[97]            for info in error_body.iter():
```

Stepping in with pdb, I see the following:

```
[...]/venv/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py(97)process_storage_error()
-> if error_body:
(Pdb) type(error_body)
<class 'dict'>
(Pdb) print(error_body)
{'error': {'code': 'InvalidQueryParameterValue', 'message': 'Value for one of the query parameters specified in the request URI is invalid.\nRequestId:82bff81c-501f-0053-39b5-344d92000000\nTime:2021-04-19T00:44:42.6291960Z'}}
```

So, it looks like under at least some circumstances, `ContentDecodePolicy.deserialize_from_http_generics` returns a dict rather than whatever type is expected. A look at the source of `deserialize_from_http_generics` seems to support that.

Seems to be related to this bug filed on the cli: https://github.com/Azure/azure-cli/issues/16217

**Comment by mccoyp** [comment]
Hi @cbare, thank you for opening this issue! We'll investigate ASAP.

**Comment by tasherif-msft** [comment]
Hello! I have put out a small PR to fix this issue https://github.com/Azure/azure-sdk-for-python/pull/18147

**Comment by tasherif-msft** [comment]
Hi @cbare, just a quick update, I'm adding some more things to the PR to refine our error handler, I'm hoping to get it merged by this week. I will keep you updated. Sorry this took longer than expected
