### ISSUE TITLE
AAD Application client validation missing

### ISSUE THREAD

**Issue by mjudeikis** [Azure/azure-sdk-for-python#18131]
**Describe the bug**
AAD Application create client allows to create application with "un-updatable" keys. This is due to fact that SDK allows malformed `PasswordCredential` to be provided and RP allows this to be created. 

Consider Application client create: 
```
app = self.client.applications.create(ApplicationCreateParameters(
            display_name=display_name,
            identifier_uris=[
                self.MANAGED_APP_PREFIX + str(uuid.uuid4()),
            ],
            password_credentials=[
                PasswordCredential(
                    end_date=end_date,
                    value=password,
                ),
            ],
        ))
```

This code should be not be successful as it is missing key identification. 
```
custom_key_identifier=str("mykey").encode(),  # looks like this field is making things go crazy
start_date=start_date,
``` 

Consequence of this is that this application/keys now is not updatable:
```
def refresh_application_credentials(self, object_id):
        password = uuid.uuid4()
        key_id = uuid.uuid4()
        start_date = datetime.datetime.utcnow()
        end_date = datetime.datetime(2299, 12, 31, tzinfo=datetime.timezone.utc)

        try:
            credentials = list(self.client.applications.list_password_credentials(object_id))
        except GraphErrorException as e:
            logger.error(e.message)
            raise

        credentials.append(PasswordCredential(
            custom_key_identifier=str(start_date).encode(),  # bytearray
            key_id=str(key_id),
            start_date=start_date,
            end_date=end_date,
            value=password))

        self.client.applications.update_password_credentials(object_id, credentials)

        return password
```

`update_passworkd_credentials` will fail with:
```
Update to existing credential with KeyId 'e88a0750-3e04-4536-b1d1-b1c8edb64dba' is not allowed.
```

**Expected behavior**
It would be good to do more validation on Application creations.
And consider RP side fixup to enable rotate application credentials like this due to fact this behavior been out for a while now.

**Comment by xiangyan99** [comment]
Thanks for your feedback. Could you tell us which library did you use?

**Comment by mjudeikis** [comment]
I see current rbac python client installed by az core:
```
GraphRbacManagementClient
VERSION = "0.60.0"
```

**Comment by xiangyan99** [comment]
Thank you for the information.

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
