### ISSUE TITLE
Make Azure Communications Objects JSON Serializable

### ISSUE THREAD

**Issue by anujb-msft** [Azure/azure-sdk-for-python#18179]
**Is your feature request related to a problem? Please describe.**
Certain ACS Python Objects are not directly JSON serializable via `json.dumps(...)`. For example `SmsSendResult` via SMS Client Send

```python
sms_responses = sms_client.send(...)
```

**Describe the solution you'd like**
I would like it to be directly serializable via json.dump(...)

**Describe alternatives you've considered**
Here is a workaround
```python
# Make sms_responses serializable
json_sms_responses = json.dumps(
    sms_responses, indent=4, default=lambda x: x.__dict__
)
```

**Additional context**
NA

**Comment by mccoyp** [comment]
Hi @anujb-msft, this seems to be a feature request. I'll triage this to the Communication team to investigate -- thanks!

**Comment by annatisch** [comment]
Hi @anujb-msft - I think you can achieve this with something like:
```python
# Make sms_responses serializable
json_sms_responses = json.dumps(
    [r.to_dict() for r in sms_responses],
    indent=4
)
```
Let me know if that works for what you're trying to do :)

**Comment by anujb-msft** [comment]
Hi @annatisch thank you so much for the incredibly fast triage and for the workaround. This jives with the workaround I provided in the original issue. I would like these to be directly serializable without requiring an iteration/transformation step.

From a customer/developer perspective — if I am building an API and/or middleware on top of ACS, I would want to pass through the SMS Response Object directly in the HTTP response. If I receive an unexpected runtime exception when serializing the ACS objects...learning how to transform the object prior to json.dumps() creates additional friction to completing the implementation.

Tagging @tophpalmer from ACS DX for visibility.

**Comment by lsundaralingam** [comment]
Hi @anujb-msft,

We are currently working on a generic solution for all of the python Azure SDKs instead of a communication specific one, so it'll take some time but it's on our backlog.

Related Issue: https://github.com/Azure/azure-sdk-for-python/issues/17102

**Comment by anujb-msft** [comment]
Hi @lsundaralingam thank you for creating visibility and tagging the related issue. Let's go ahead and close out this issue and refer folks to #17102 — if that's okay with the group?
