### ISSUE TITLE
Azure Schema Registry client library python not working - Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by kingindanord** [Azure/azure-sdk-for-python#18219]
I am trying to use Schema Registry with Azure EventHubs following this [guide](https://docs.microsoft.com/en-us/python/api/overview/azure/schemaregistry-readme?view=azure-python-preview). I can't make this guide work and it is not clear which endpoint for schema registry I should use. Can someone please help me with this?

info:

**script**

```python
import os
import sys
import logging
from azure.eventhub import EventHubProducerClient, EventData
from azure.schemaregistry import SchemaRegistryClient
from azure.schemaregistry.serializer.avroserializer import SchemaRegistryAvroSerializer
from azure.identity import DefaultAzureCredential

# Create a logger for the SDK
logger = logging.getLogger('azure.schemaregistry')
logger.setLevel(logging.DEBUG)

# Configure a console output
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)


os.environ['AZURE_TENANT_ID'] = "xxx"
os.environ['AZURE_CLIENT_ID'] = "xxx"
os.environ['AZURE_CLIENT_SECRET'] = "xxx"

credential = DefaultAzureCredential()

endpoint= "Endpoint=sb://xxx.servicebus.windows.net/"

schema_registry_client = SchemaRegistryClient(endpoint, credential, logging_enable=True, logger=logger)



schema_string = """
{"namespace": "example.avro",
 "type": "record",
 "name": "User",
 "fields": [
     {"name": "name", "type": "string"},
     {"name": "favorite_number",  "type": ["int", "null"]},
     {"name": "favorite_color", "type": ["string", "null"]}
 ]
}"""


schema_registry_client.register_schema("schema-test-group","schema-test-test","avro",schema_string)

```

**ERROR**
```
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x000001CAE9D1CF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
```

**LOG**

```
Request URL: 'https://Endpoint=sb://xxx.servicebus.windows.net/$schemagroups/schema-test-group/schemas/schema-test?api-version=REDACTED'
Request method: 'PUT'
Request headers:
    'X-Schema-Type': 'REDACTED'
    'Content-Type': 'application/json'
    'Accept': 'application/json'
    'Content-Length': '298'
    'x-ms-client-request-id': 'xxx'
    'User-Agent': 'azsdk-python-azureschemaregistry/1.0.0b1 Python/3.9.2 (Windows-10-10.0.19041-SP0)'
    'Authorization': 'REDACTED'
A body is sent with the request
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8faf7bd8-b22a-5b9f-5d9e-7a4de084e633
* Version Independent ID: 68071a6e-8947-70b6-a5b2-5ee999a83597
* Content: [Azure Schema Registry client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/schemaregistry-readme?view=azure-python-preview)
* Content Source: [docs-ref-services/preview/schemaregistry-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/preview/schemaregistry-readme.md)
* Service: ****
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by mccoyp** [comment]
Hi @kingindanord, thank you for opening this issue! We'll investigate ASAP.

**Comment by yunhaoling** [comment]
hey @kingindanord, thanks for reaching out.

The endpoint you specified is not in the right format. It should be `endpoint= "xxx.servicebus.windows.net"`.
if you check the log, you could see `https://Endpoint=sb://xxx.servicebus.windows.net/...` is used to request.

we will improve on the doc and sample to make the endpoint format clear, thanks for your feedback.

**Comment by kingindanord** [comment]
Hi @yunhaoling, I did try this before but it didn't work as well. 

**ERROR**

```
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
```

**LOG**

```
Request URL: 'https://xxx.servicebus.windows.net/$schemagroups/schema-test-group/schemas/schema-test?api-version=REDACTED'
Request method: 'PUT'
Request headers:
    'X-Schema-Type': 'REDACTED'
    'Content-Type': 'application/json'
    'Accept': 'application/json'
    'Content-Length': '157'
    'x-ms-client-request-id': 'xxx'
    'User-Agent': 'azsdk-python-azureschemaregistry/1.0.0b1 Python/3.9.2 (Windows-10-10.0.19041-SP0)'
    'Authorization': 'REDACTED'
A body is sent with the request
Response status: 400
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'Strict-Transport-Security': 'REDACTED'
    'Date': 'Tue, 27 Apr 2021 07:13:30 GMT'  
  ```
  
  the `$schemagroups` part seems to be strange in the URL
  
  I am using the same script as described in the issue after changing the endpoint to `endpoint= "xxx.servicebus.windows.net"`

**Comment by yunhaoling** [comment]
hey @kingindanord , `xxx.servicebus.windows.net` is in the right format and now it gives you the 400 ErrorCode (Bad Request) in 

It's probably the format of the schema string not conforming to the requirement of the service.

I tried the sample in the repo also got the bad request 400 error -- I need to apologize for this, it has been a while since we released this package and samples, and looks like the service team has forced format check on their side (checking string not including "\n", space, etc.)

Instead, if I have a schema string not having space, "\n", I could get the code work.

```python
"""{"namespace":"example.avro","type":"record","name":"User","fields":[{"name":"name","type":"string"},{"name":"favorite_number","type":["int","null"]},{"name":"favorite_color","type":["string","null"]}]}"""
```

Could you validate the schema string on your side? Besides, I will update the sample code shortly.

**Comment by kingindanord** [comment]
It is working now. Thanks.
