### ISSUE TITLE
[ADLS Gen2 - DataLakeFileClient] - Uploading a file to Gen2 using upload_data() is much slower than using open() for gen1

### ISSUE THREAD

**Issue by gabsylvain** [Azure/azure-sdk-for-python#18211]
Hi, I am using the sdk to upload data from my local machine or from a remove server to ADLS.

I was previously using the **azure.datalake.store** module for interacting with **ADLS Gen1**. More precisely, I was doing something like this, for appending large chunks of data to a single file in ADLS:

Here, consider that service.get_data returns subsequent pages of an API response
```
import MyDataService
from azure.datalake.store import core, lib

service=MyDataService()

adls_client = core.AzureDLFileSystem(lib.auth(), store_name="my_adls_gen1")
with adls_client.open(path="test.csv", mode='ab') as f:
    for response_page in service.get_data():   #Get Data from Api - Use loop to write page by page
        f.write(str.encode(response_page))
```

Then, our team migrated to using **ADLS Gen2**, so I had to refactor my code so that it uses the appropriate module -  **azure.storage.filedatalake**. However, based on [this documentation](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/GEN1_GEN2_MAPPING.md), there exists no mapping for the "open" function available in azure.datalake.store, in azure.storage.filedatalake. So I had to use the available methods (upload_data or append_data):

Here, consider that service.get_data returns the all pages of the API response together
```
import MyDataService
from azure.storage.filedatalake import DataLakeServiceClient

def write_data(self, resp, file_system_name, folder_path, file_name):
  adls_client = DataLakeServiceClient("https://{}.dfs.core.windows.net".format("my_storage_account"), credential="my_key")

  file_system_client = adls_client.get_file_system_client(file_system_name)
  file_system_client.create_directory(folder_path)
  directory_client = file_system_client.get_directory_client(folder_path)
  file_client = directory_client.create_file(file_name)
  file_client.upload_data(data=resp, overwrite=True)

service=MyDataService()
data = service.get_data()
write_data(data, "landing", "", "test.csv")
```

**Problem:**
Building a large response and uploading it all at once or calling the write_data method for each chunk of data using  azure.storage.filedatalake results in the same poor performance compared to interacting with ADLS Gen1 with the azure.datalake.store module.

A data engineering job (ingestion) of mine would previously take 3-4 minutes , as it now takes 15-20 minutes. 

I would like to know if there was any plan for providing a similar "open" method for Gen2 or if there was any particular known reason why it would be slower with the ADLS Gen2 integration?

Thanks in advance,

Gab

**Comment by mccoyp** [comment]
Hi @gabsylvain, thank you for opening this issue! We'll investigate ASAP.

**Comment by amishra-dev** [comment]
@xiafu-msft / @tasherif-msft can you please look at this one.

**Comment by tasherif-msft** [comment]
Hi @gabsylvain, what's the size you're uploading that has changed to 15-20min? 
Also what is the chunk size you're using?

**Comment by gabsylvain** [comment]
Hi sorry, for the delay in the response. By trying to reproduce the problem, I have found out that another piece of my code might be causing the problem. Thanks.
