### ISSUE TITLE
The Peering Location for an Express Route Cross Connection ... cannot be modified from PL Name to .

### ISSUE THREAD

**Issue by jbernardini** [Azure/azure-sdk-for-python#18217]
- **Package Name**: azure-mgmt-network
- **Package Version**: 16.0.0b1, 16.0.0 and 18.0.0
- **Operating System**: Win10
- **Python Version**: 3.9.4

**Describe the bug**
Appears to be the same behavior as described in: https://github.com/Azure/azure-sdk-for-net/issues/20546. Only I've never had this working and can't find an example anywhere so I can't say for sure I haven't done something wrong. Note too I first worked through errors that seem to require the location and circuit id. These seem redundant to the skey (as does peering location) since you pull these values on a get(skey).

network_client.express_route_cross_connections.begin_create_or_update()

fails with:

File "./modify.py", line 38, in main
    response = network_client.express_route_cross_connections.begin_create_or_update(
  File "/home/user/.local/lib/python3.8/site-packages/azure/mgmt/network/v2020_11_01/operations/_express_route_cross_connections_operations.py", line 336, in begin_create_or_update       
    raw_result = self._create_or_update_initial(
  File "/home/user/.local/lib/python3.8/site-packages/azure/mgmt/network/v2020_11_01/operations/_express_route_cross_connections_operations.py", line 292, in _create_or_update_initial    
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (PeeringLocationCannotBeModifiedForACrossConnection) The Peering Location for an Express Route Cross Connection /subscriptions/********/resourceGroups/********/providers/Microsoft.Network/expressRouteCrossConnections/********* cannot be modified from PL Name to .

**To Reproduce**
1. expsrt = getexpressroute(skey)
2. resgrp = expsrt['id'].split('/')[4]
3. response = network_client.express_route_cross_connections.begin_create_or_update(
            resgrp, 
            skey,
            {
                "location": expsrt['location'],
                "service_provider_provisioning_state": "Provisioned",
                "express_route_circuit": expsrt['express_route_circuit'],
                "peering_location": expsrt['peering_location']      #same error if this is not included.
            }
        ).result()

**Expected behavior**
Successful update of "service_provider_provisioning_state": "Provisioned",

**Screenshots**

**Additional context**
I also added a comment on the other bug in the description.

**Comment by mccoyp** [comment]
Hi @jbernardini, thank you for opening this issue! We'll investigate ASAP.

**Comment by jbernardini** [comment]
With the function call below so that no parameter serialization was required, I was able to replace line 284 of _express_route_cross_connections_operations.py as shown here and move past the error. So as noted in the other bug the issue seems to be in the serialization. Specifically what was happing is the peeringLocation key/value pair was being stripped out. You can see this by first printing parameters and then body_content.

#body_content = self._serialize.body(parameters, 'ExpressRouteCrossConnection')
body_content = parameters

response = network_client.express_route_cross_connections.begin_create_or_update(
                resource_group,
                skey,    
                {
                    "location": expsrt['location'],
                    "properties": {
                        "expressRouteCircuit": {
                            "id": expsrt['express_route_circuit']['id']
                        },
                        "peeringLocation": "Denver Test",
                        "bandwidthInMbps": 50,
                        "serviceProviderProvisioningState": "Provisioned",
                    }
                }
        ).result()

**Comment by jbernardini** [comment]
Did a bit more digging and found what is maybe a more correct fix in the model and reverted _express_route_cross_connections_operations.py to original. The following changes are all in the ExpressRouteCrossConnection class definition in _models_py3.py. For the changes in __init__ I followed the earlier convention from _models.py just because it is simple and required less line edits. 

# in _validation, commented out these lines since we don't want to drop these values in the serializer/validation.
 
9468         #'peering_location': {'readonly': True},
9469         #'bandwidth_in_mbps': {'readonly': True},

in __init__, commented out 9509/10 and inserted replacements with values in 9511/12 since we need to pass values. As noted above there's a clear convention I did not follow but it works for a patch.

 9509         #self.peering_location = None
 9510         #self.bandwidth_in_mbps = None
 9511         self.peering_location = kwargs.get('peering_location', None)
 9512         self.bandwidth_in_mbps = kwargs.get('bandwidth_in_mbps', None)

If you recall from my first comment I mentioned having to provide these values felt redundant and now having worked through this it's clear the model wasn't written with the intent to provide them. So I'm guessing this all stems from a recentish change where they've become required parameters even though you can't modify them. So if that's true the best solution is to revert the requirement but this should work for a patch in the meantime if someone else needs it.

Here's my function call. If anyone grabs this for an example pay attention to where I've used camelCase vs. snake_case. I think it may matter if you loot at the attribute map in the model. when I tried all snake_case in my function call it failed and I didn't bother looking any harder since this was working. 

response = network_client.express_route_cross_connections.begin_create_or_update(
                resource_group,
                skey,    
                {
                    "location": expsrt['location'],
                    "properties": {
                        "expressRouteCircuit": {
                            "id": expsrt['express_route_circuit']['id']
                        },
                        "peeringLocation": expsrt['peering_location'],
                        "bandwidthInMbps": expsrt['bandwidth_in_mbps'],
                        "serviceProviderProvisioningState": "NotProvisioned",
                    }
                }
        ).result()

**Comment by jbernardini** [comment]
Upgraded to azure-mgmt-network 19.3.0 and the issue persists.

**Comment by navba-MSFT** [comment]
@jbernardini Apologies for the late reply. We are looking into this issue. We will provide an update on this once we have more details.

 @exrsuppgithub  Could you please look into this and provide an update once you get a chance ? Awaiting your reply.

**Comment by jonstout** [comment]
Any updates on this? This is still broken and the work around mentioned by @jbernardini isn't working for me.

**Comment by jbernardini** [comment]
@jonstout we've got an operational patch as part of our container image. can probably help get you working in the meantime.

**Comment by jbernardini** [comment]
no we're just an API consumer like you, but we had to have it working in production.Sent from my iPhoneOn Oct 20, 2022, at 12:34 PM, James Harr ***@***.***> wrote:﻿
Is your operational patch going to be put into a release of this SDK soon?

**Comment by jamesharr** [comment]
> no we're just an API consumer like you, but we had to have it working in production.

How simple is your patch?

**Comment by jbernardini** [comment]
Sorry for the delayed response. I saw this, intended to respond the next morning and then spaced it till tonight. Our patch is pretty basic. We build on Ubuntu 20.04 which includes Python 3.8. We just use the [patch command](https://man7.org/linux/man-pages/man1/patch.1.html). 

We install the pip library azure-mgmt-network==18.0.0. I see the line numbers have changed in 22.1.0 as follows:

> The following changes are all in the ExpressRouteCrossConnection class definition in _models_py3.py.
> 
> in _validation, commented out these lines since we don't want to drop these values in the serializer/validation.
> 11511 #'peering_location': {'readonly': True},
> 11512 #'bandwidth_in_mbps': {'readonly': True},
> 
> in init, replace 11573/11574 since we need to pass values. 
> 
> -- self.peering_location = None
> -- self.bandwidth_in_mbps = None
> ++ self.peering_location = kwargs.get('peering_location', None)
> ++ self.bandwidth_in_mbps = kwargs.get('bandwidth_in_mbps', None)


We have a patches/azure.patch file in our project root with the following contents (for 18.0.0).

```
diff -ruN azure/mgmt/network/v2020_11_01/models/_models_py3.py azure/mgmt/network/v2020_11_01_patched/models/_models_py3.py
--- azure/mgmt/network/v2020_11_01/models/_models_py3.py	2022-02-22 21:38:18.831088781 +0000
+++ azure/mgmt/network/v2020_11_01_patched/models/_models_py3.py	2022-02-25 20:36:07.920358200 +0000
@@ -9465,8 +9465,6 @@
         'primary_azure_port': {'readonly': True},
         'secondary_azure_port': {'readonly': True},
         's_tag': {'readonly': True},
-        'peering_location': {'readonly': True},
-        'bandwidth_in_mbps': {'readonly': True},
         'provisioning_state': {'readonly': True},
     }
 
@@ -9506,8 +9504,8 @@
         self.primary_azure_port = None
         self.secondary_azure_port = None
         self.s_tag = None
-        self.peering_location = None
-        self.bandwidth_in_mbps = None
+        self.peering_location = kwargs.get('peering_location', None) 
+        self.bandwidth_in_mbps = kwargs.get('bandwidth_in_mbps', None)
         self.express_route_circuit = express_route_circuit
         self.service_provider_provisioning_state = service_provider_provisioning_state
         self.service_provider_notes = service_provider_notes
```

And finally our Dockerfile includes: 

```
RUN cd /usr/local/lib/python3.8/dist-packages \
     && for FILE in `ls /tmp/patches/*.patch`; do patch -p0 < ${FILE}; done
```

**Comment by jbernardini** [comment]
issue persists in  azure-mgmt-network 25.3.0. The same patch as above works now targeting /usr/local/lib/python3.8/dist-packages/azure/mgmt/network/models/_models.py
