### ISSUE TITLE
management client does not support adding custom policies

### ISSUE THREAD

**Issue by zhoxing-ms** [Azure/azure-sdk-for-python#18225]
- **Package Name**: `azure-core`
- **Package Version**: `1.13.0`
- **Operating System**: All
- **Python Version**: All

**Describe the bug**
Although a PR has added the ability to add the custom policies when no specified policies are passed in through `**kwargs` to the `PipelineClient`.
PR link: https://github.com/Azure/azure-sdk-for-python/pull/17340

However, management client still does not support adding custom policies.
For example, the `per_call_policies` or `per_retry_policies` is passed in through `**kwargs` when building `ResourceManagementClient`. The reason for this issue is as follows:

1. In method `__init__()` of `ResourceManagementClient`, the `ARMPipelineClient` is created
https://github.com/Azure/azure-sdk-for-python/blob/602537021e0d5a94e0b61419e99cfa8052817c7e/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L80

2. When creating `ARMPipelineClient`, if the specified policies are not passed in through `**kwargs`, the default policies will be added to `**kwargs` before building the pipeline
https://github.com/Azure/azure-sdk-for-python/blob/602537021e0d5a94e0b61419e99cfa8052817c7e/sdk/core/azure-mgmt-core/azure/mgmt/core/_pipeline_client.py#L44-L51

3. When building pipeline, only when there are no policies in `**kwargs`, there is logic to add custom policies. Since the default policies are passed in through `**kwargs` in step 2, so there is no logic to add custom policies.
https://github.com/Azure/azure-sdk-for-python/blob/602537021e0d5a94e0b61419e99cfa8052817c7e/sdk/core/azure-core/azure/core/_pipeline_client.py#L111-L117

**Expected behavior**
Could we consider that when building pipeline client, if the specified policies are passed in through `**kwargs`, these policies (in `ARMPipelineClient`, they are the default policies set by `_default_policies`) can also support appending custom policies?

**ETA**
Because this issue affects our migration of track 2 for resource module, and we plan to complete the merge of the migrated code by next Monday.
So this is an urgent issue and **we hope to have it resolved by next Monday**. Otherwise, we have to add custom policies by modifying private variables which do not conform to the code specification.

**Comment by iscai-msft** [comment]
I think [this](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/_pipeline_client.py#L74) functionality should help you. You can pass in policies with `per_call_policies` and `per_retry_policies`. This was added in version 1.13.0, so you guys may have to update your `azure-core` dependency.

cc @xiangyan99 @lmazuel for confirmation

**Comment by xiangyan99** [comment]
I think the design that "only policies is not specified, we will honor custom policies" is correct.

In your case, I would suggest you supporting custom_policies in your _default_policies(config, **kwargs)

https://github.com/Azure/azure-sdk-for-python/blob/602537021e0d5a94e0b61419e99cfa8052817c7e/sdk/core/azure-mgmt-core/azure/mgmt/core/_pipeline_client.py#L54-L69

Does this make sense?

**Comment by xiangyan99** [comment]
Fixed.
