### ISSUE TITLE
Requested Resource Does Not Support HTTP Method PUT in azure-mgmt-authorizations

### ISSUE THREAD

**Issue by CloudSecuritySmith** [Azure/azure-sdk-for-python#18230]
- **Package Name**: azure-mgmt-authorizations
- **Package Version**:  v2015_07_01
- **Operating System**: Ubuntu Linux
- **Python Version**: 3.8

**Describe the bug**
Getting "requested resource does not support http method 'PUT' error when running create_or_update from role_definitions_operations

Was previously functioning - breaking on new container build

**To Reproduce**
def update_role_definition(creds: ClientSecretCredential, sub_id: str) -> None:
    """Adds new subscription to scope"""
    client = AuthorizationManagementClient(
        creds, subscription_id=ROLE_DEF_UPDATE_SUBSCRIPTION)
    current_role_def = client.role_definitions.get_by_id(role_definition_id=ROLE_DEF_ID)
    current_role_def.assignable_scopes.append(f'/subscriptions/{sub_id}')
    client.role_definitions.create_or_update(
        scope=f'/subscriptions/{ROLE_DEF_UPDATE_SUBSCRIPTION}/',
        role_definition_id=ROLE_DEF_ID, 
        role_definition=current_role_def)

**Expected behavior**
Modification of the role definition to include new subscription

**Screenshots**
client.role_definitions.create_or_update(
File \"/var/lang/lib/python3.8/site-packages/azure/mgmt/authorization/v2015_07_01/operations/_role_definitions_operations.py\", line 220, in create_or_update
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)\nazure.core.exceptions.HttpResponseError: (None) The requested resource does not support http method 'PUT'.",

**Comment by mccoyp** [comment]
Hi @CloudSecuritySmith, thank you for opening this issue! We'll investigate ASAP.

**Comment by BigCat20196** [comment]
Hi @CloudSecuritySmith  Please check the current version of this package and update to the most recent version.

If it has not been solved yet, we will continue to pay attention to it.

Hope this unblocks you.

**Comment by SaurabhSharma-MSFT** [comment]
@CloudSecuritySmith Can you please check and confirm back if your issue is resolved.
