### ISSUE TITLE
code snippet on web page doesn't work.

### ISSUE THREAD

**Issue by lovettchris** [Azure/azure-sdk-for-python#18240]
- **Package Name**:  azure.identity
- **Package Version**:  1.5.0
- **Operating System**: Windows
- **Python Version**:  3.6.13

**Describe the bug**
This page: https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate
contains this snippet:
```python
from azure.identity import AzureCliCredential
from azure.mgmt.resource import SubscriptionClient

credential = AzureCliCredential()
subscription_client = SubscriptionClient(credential)

subscription = next(subscription_client.subscriptions.list())
print(subscription.subscription_id)
```

but it doesn't work, I get this error:

Exception has occurred: AttributeError
'AzureCliCredential' object has no attribute 'signed_session'
  File "D:\Temp\copilot\test.py", line 27, in get_cli_credential
    subscription = next(subscription_client.subscriptions.list())
  File "D:\Temp\copilot\test.py", line 31, in <module>
    get_cli_credential()

**To Reproduce**
1.  Run the above snippet from VS code launched from CLI that you did "az login" already.

**Expected behavior**
Published code snippets should be tested on an ongoing basis.

**Screenshots**

**Additional context**

**Comment by mccoyp** [comment]
Hi @lovettchris, thank you for opening this issue! We'll investigate this ASAP.

**Comment by chlowell** [comment]
That snippet requires azure-mgmt-resource 15.0.0+. The error indicates you have an older version installed. The document is in fact trying to clarify that point (unsuccessfully, it seems 😆). This issue is very timely--earlier today I opened #18239 to add more detail about this sort of thing to the azure-identity migration guide. Do you find the new content in my PR helpful?

**Comment by lovettchris** [comment]
yes, your new PR is perfect and is exactly what I needed, thanks.

**Comment by chlowell** [comment]
Thanks for taking a look. I'll close this issue then, please open another if you encounter another problem.

**Comment by lovettchris** [comment]
Yep will do, thanks for the prompt response.
