### ISSUE TITLE
CONNECT request from Azure SDK does not have HOST header.

### ISSUE THREAD

**Issue by sfc-gh-hchaturvedi** [Azure/azure-sdk-for-python#18268]
- **Package Name**: azure-storage-blob 
- **Package Version**: 12.6.0
- **Operating System**: NA
- **Python Version**: 3.8

**Describe the bug**

Snowflake Python connector users have the option to configure a proxy through which all their traffic get's routed. We recently noticed that some of the connections were getting denied by the intermediate proxies, specifically the ones that were compliant with [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.6). 

On further analysis we found that the RFC requires the initial CONNECT request contain HOST header. For connections originating within Snowflake's Python connector we fixed the issue by explicitly adding the header - for reference here's the [fix](https://github.com/snowflakedb/snowflake-connector-python/pull/599/files#diff-3f76e3de323abdeb6c70dd370c6cc8dc912d360f24066df7c061e53299ba7541R173).  However we realized that we don't have similar control while using Azure SDK to connect to Blob Storage. Apparently Azure SDK too does not add the HOST header to the CONNECT request. 

**To Reproduce**
Using any proxy conforming with [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.6) try to access blob storage.
This is reproducible and can be identified by using a squid proxy that has ssl-bump enabled to view the headers.  The below log shows the Headers that are being sent by the Snowflake's Python connector while using the Azure SDK to connect to Azure Blob in the initial CONNECT

`1606929657.657    326 ::1 NONE/200 0 CONNECT  <https endpoint>:443 - HIER_DIRECT/35.161.113.159 - [] []`

`1606929658.183    380 ::1 TCP_MISS/200 1903 POST <https endpoint>/session/v1/login-request? - HIER_DIRECT/35.161.113.159 application/json [User-Agent: PythonConnector/2.3.4 (macOS-10.15.7-x86_64-i386-64bit) CPython/3.8.6\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/snowflake\r\nConnection: keep-alive\r\nContent-Type: application/json\r\nContent-Encoding: gzip\r\nContent-Length: 414\r\nAuthorization: Snowflake Token="None"\r\nHost: <https endpoint host>\r\n] `

`[HTTP/1.1 200 OK\r\nCache-Control: no-cache, no-store, no-transform\r\nContent-Encoding: gzip\r\nContent-Type: application/json\r\nDate: Wed, 02 Dec 2020 17:20:58 GMT\r\nExpect-CT: enforce, max-age=3600\r\nStrict-Transport-Security: max-age=31536000\r\nVary: Accept-Encoding, User-Agent\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: deny\r\nX-XSS-Protection: : 1; mode=block\r\nContent-Length: 1428\r\nConnection: keep-alive\r\n\r]`
 

**Expected behavior**
The CONNECT request should have a HOST header

**Screenshots**

**Additional context**

**Comment by rakshith91** [comment]
Thanks for reporting this! We'll investigate asap

**Comment by sfc-gh-hchaturvedi** [comment]
Any updates on this? This essentially is blocking few of our customers from connecting to Blob storage. Thanks.

**Comment by tasherif-msft** [comment]
Hi @sfc-gh-hchaturvedi, I will look into this and get back to you asap

**Comment by sfc-gh-cconner** [comment]
Just checking on this one, I'm working with sfc-gh-hchaturvedi and our customers are asking on this one again.

Thanks!

**Comment by tasherif-msft** [comment]
Hi @sfc-gh-cconner and @sfc-gh-hchaturvedi, sorry for the delay. So this is implemented on a very low level in our SDK. We don't make an explicit CONNECT request ourselves as it is implemented in the requests library. However, we are able to pass our own headers into the pipeline using `headers={}` 
This can be done per operation or on the client level.
Please note that this would add the header to all the requests within an operation or calls of a given client. Not just the CONNECT request.

You can simply pass `headers={'your_header': 'value'}` 

Let me know if this helps.
Thanks
