### ISSUE TITLE
Servicebus dead letter queue

### ISSUE THREAD

**Issue by geeday** [Azure/azure-sdk-for-python#1826]
Hi,

One bug (i think) and 1 question if I may:

I want to count the number of messages in a dead letter queue.

````
# azure-servicebus==0.21.1
bus_service = ServiceBusService( login stuff here)
qname = "xyz"
dlqName = ServiceBusService.format_dead_letter_queue_name(qname)

# but the following does not work.
# what is the work around?
dlq = bus_service.get_queue(dlqName)
dlcount = dlq.message_count
#error:
azure.common.AzureHttpError: Bad Request
<Error><Code>400</Code><Detail>The specified HTTP verb (GET) is not valid. TrackingId:xxa2973f-87b1-4xxx-b685-17d85630xxxxxx_G35, SystemTracker:xxx-namespace:Queue:xxx_my_queuename, Timestamp:1/24/2018 12:54:20 PM</Detail></Error>
````

To add to the DL queue, do we try/except around the processing of the original message from the main queue, then post ourselves back on to the DL one?

**Comment by lmazuel** [comment]
Hello,
See this SO answer:
https://stackoverflow.com/a/43170448/4074838

> I ran into this same problem trying to get the count from the dead letter queue. It looks like the deadletterqueue doesn't allow you to get a count directly, you get it from the MessageCountDetails of the normal Queue.

Hope this helps,
Thanks

**Comment by geeday** [comment]
Thanks!!! :)
 I always search "dead letter queue", which I think is part of the reason I never found the SO thread.

**Comment by lmazuel** [comment]
I know Python documentation on ServiceBus is far from perfect :/
