### ISSUE TITLE
Doc issue - Cog search - example params versus doc params

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk-for-python#18280]
[Search_client.search](https://docs.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.searchclient?view=azure-python#search-search-text----kwargs-) doc is missing explanation of facets. 

![image](https://user-images.githubusercontent.com/41597107/115968501-187d4780-a4ed-11eb-98ac-43878ce93ac7.png)

**Comment by diberry** [comment]
@dereklegenzoff

**Comment by xiangyan99** [comment]
Hi Scott, we do have the facets in source code. 

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/search/azure-search-documents/azure/search/documents/_search_client.py#L150-L152

Could you help to take a look why it does not show in docs?

**Comment by xiangyan99** [comment]
In fact, seems like the parameter is in the doc but in wrong format.

**Comment by xiangyan99** [comment]
#18431 similar issue.

**Comment by scbedd** [comment]
Yep. Same Issue. [Link to exact location in docs.](https://docs.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.searchclient?view=azure-python-preview#search-search-text----kwargs-)

Breaking this down to understand where in the pipeline it's choking on this thing.

![image](https://user-images.githubusercontent.com/45376673/119565365-b5d2d200-bd5e-11eb-9be1-f0189f88e9da.png)

**Comment by scbedd** [comment]
Ok. Figured it out. Hilariously enough, it actually [repros in our docs as well](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-search-documents/11.2.0b3/azure.search.documents.html#azure.search.documents.SearchClient.search) Definitely not an issue with docs! PR incoming to fix this.

**Comment by xiangyan99** [comment]
Are we able to fix it in this release?

**Comment by scbedd** [comment]
100% PR inc.

**Comment by xiangyan99** [comment]
Fixed.
