### ISSUE TITLE
Chat Samples are not able to run in the pipeline

### ISSUE THREAD

**Issue by jbeauregardb** [Azure/azure-sdk-for-python#18314]
- **Package Name**:  azure-communication-chat

**Describe the bug**
We want to make the Python ACS samples run in the pipeline to have an extra security layer when we do our releases. We refactored our TNM, Identity and SMS samples to make them able to run in the pipeline, however, chat samples are not being able to work because of some special environment variables they need in order to run successfully.

We are seeing references to an AZURE_COMMUNICATION_SERVICE_ENDPOINT env variable in the samples. This env variable doesn't exist in the pipeline so it should be removed fron the samples or added to the key vault from the resource we use to test to avoid any inconsistencies with the env variables the Chat Client needs to initiate.

@juancamilor

**Comment by jbeauregardb** [comment]
This is the PR I opened to add this feature https://github.com/Azure/azure-sdk-for-python/pull/18234
If you go to the pipeline logs you can see exactly where are the errors that need to be addressed.

**Comment by juancamilor** [comment]
@LuChen-Microsoft  FYI
