### ISSUE TITLE
rename omponents19E4Rl9SchemasBatchaccountidentityPropertiesUserassignedidentitiesAdditionalproperties and Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties

### ISSUE THREAD

**Issue by cbare** [Azure/azure-sdk-for-python#18337]
- **Package Name**:  azure-mgmt-batch
- **Package Version**:  15.0.0

**Describe the bug*

I guess the class names "Components19E4Rl9SchemasBatchaccountidentityPropertiesUserassignedidentitiesAdditionalproperties" and "Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties" are a code generation error? These are in azure.mgmt.batch.models.

See also: https://docs.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.components19e4rl9schemasbatchaccountidentitypropertiesuserassignedidentitiesadditionalproperties?view=azure-python

**Comment by rakshith91** [comment]
Thanks for reporting the issue! We'll investigate it asap

**Comment by xiangyan99** [comment]
Looks like it is fixed.
