### ISSUE TITLE
How to create a VM with an existing/stored SSH key pair?

### ISSUE THREAD

**Issue by DeepSpace2** [Azure/azure-sdk-for-python#18347]
I could only find examples of how to create a VM with new SSH key:

```python
...,
"linux_configuration": {
    "ssh": {
        "public_keys": [
            {
                 "path": "",
                 "key_data": "",
             }
        ]
     }
},
...
```

However I'm yet to find an example of how to create a VM that uses an existing pair, the equivalent of this functionality in the UI:

![Screen Shot 2021-04-27 at 16 29 30](https://user-images.githubusercontent.com/6841988/116249868-e7637800-a775-11eb-87c4-225a3a324469.png)

**Comment by rakshith91** [comment]
Thanks for the question! Redirecting this to the right person

**Comment by BigCat20196** [comment]
Hi @DeepSpace2 ， excuse me how you wish to create vm？By cli or power shell?

You can use the parameters `--ssh-key-name` and `--ssh-key-values` to specify the value you expect.

Pls refer to: https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az_vm_create

**Comment by DeepSpace2** [comment]
@BigCat20196 I'm using the Python SDK, otherwise I would not be opening this issue in this repo :)

**Comment by xiangyan99** [comment]
@00Kai0 do we have samples for this scenario?

**Comment by BigCat20196** [comment]
Hi @DeepSpace2,  it may use this keyword.


```
...
"secrets": [
        {
          "sourceVault": {
            "id": "string"
          },
          "vaultCertificates": [
            {
              "certificateUrl": "string",
              "certificateStore": "string"
            }
          ]
        }
      ],
...
```
