### ISSUE TITLE
HttpResponseError 'No Content' exception raised by ConsumptionManagementClient.usage_details.list when subscription did not exist at filter date

### ISSUE THREAD

**Issue by marc-perreaut** [Azure/azure-sdk-for-python#18343]
Hello,

ConsumptionManagementClient.usage_details.list throws undocumented exception **HttpResponseError** if the subscription does not exist at the requested date.

File '/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/paging.py', line 129, in __next__ return next(self._page_iterator) File '/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/paging.py', line 76, in __next__ self._response = self._get_next(self.continuation_token) File '/home/site/wwwroot/.python_packages/lib/site-packages/azure/mgmt/consumption/operations/_usage_details_operations.py', line 164, in get_next raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

This exception should be documented and ideally made less generic than HttpResponseError.

It would also make sense to enhance the SubscriptionClient.list method to retrieve only the subscriptions that existed at a given date, in order to avoid handling such a case.

Reference: Microsoft Support request ID 2104210050003300.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e8c4735-1579-58a0-f375-096d5dbdc2c4
* Version Independent ID: 30a48745-054c-2748-f326-ab3b498dc144
* Content: [azure.mgmt.consumption.operations.UsageDetailsOperations class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-consumption/azure.mgmt.consumption.operations.usagedetailsoperations?view=azure-python#list-scope--expand-none--filter-none--skiptoken-none--top-none--metric-none----kwargs-)
* Content Source: [docs-ref-autogen/azure-mgmt-consumption/azure.mgmt.consumption.operations.UsageDetailsOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-consumption/azure.mgmt.consumption.operations.UsageDetailsOperations.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by rakshith91** [comment]
Thanks for reporting the issue! We'll look into this asap

**Comment by marc-perreaut** [comment]
Is there an update on this issue?

This is a major issue to me, because it means the Azure usage details (Azure costs) can no longer be retrieved once a subscription no longer exists. The SDK should make it possible to retrieve the subscriptions that existed at a given date in the past, so that all usage details can be retrieved by looping on them.

**Comment by lmazuel** [comment]
@marc-perreaut I see different questions in one issue:
- This exception should be documented and ideally made less generic than HttpResponseError.
- Enhance the SubscriptionClient.list method to retrieve only the subscriptions that existed at a given date

I assume your most important question is about the API capability to return subscription that existed in the past, since this is not SDK related (SDK will just show what service can do), I'm tagging the service team to answer to it from an API perspective. If we get an answer on the features, I'll shift that issue back to support request from SDK.

**Comment by marc-perreaut** [comment]
@lmazuel you are correct.

To elaborate, my goal is to retrieve Azure cost data.

According to https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/understand-cost-mgt-data:
"
- Azure finalizes or closes the current billing period up to 72 hours (three calendar days) after the billing period ends.
- During the open month (uninvoiced) period, cost management data should be considered an estimate only. In some cases, charges may be latent in arriving to the system after the usage actually occurred.
"

So final cost data of the 1st day of the billing period can be retrieved only after 30 days  + 72 hours: if subscription was deleted in-between, cost data is not accessible.
