### ISSUE TITLE
ParallelRunStep progress metric

### ISSUE THREAD

**Issue by emepetres** [Azure/azure-sdk-for-python#18357]
**Is your feature request related to a problem? Please describe.**
During a ParallelRunStep execution, It is not possible to know how many items have been processed and how many are left. In long runs, it would be nice to know at least the processed/total metric, to assess its progress and estimation time to finish.

**Describe the solution you'd like**
I'd like to access through the python api or through the details tab of a ParallelRunStep  to the percentage of processed items.

**Describe alternatives you've considered**
I guess I could parse somehow the logs and create my own tool to compute this metric, but I think this solution is a little bit messy and it would be much more cleaner to access this information from the ML Studio or the API

**Comment by rakshith91** [comment]
Thanks for the issue! The team will investigate this asap

**Comment by shivanissambare** [comment]
@tracychms  please help with this issue
thank you!

**Comment by tracychms** [comment]
Thanks for the feedback. In Studio, if you go to the step's Metrics tab, you will be able to see a chart/table of execution progress, including remaining items, remaining mini batches, failed items, etc.

**Comment by emepetres** [comment]
That's great thanks!
