### ISSUE TITLE
[Container Registry] Release versions are out of order

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#18356]
- **Package Name**: azure-mgmt-containerregistry
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Release versioning seems to be out of order.
Recent releases were for 3.0.x version while Oct 28 2020 was a release for 8.0. 
What is the real latest release version of this SDK?
What is the timeline to get a non-preview version for a service that is GA for 4 years?

![image](https://user-images.githubusercontent.com/1036695/116281217-558c4880-a73e-11eb-8ede-79e73534d0f7.png)

**Comment by rakshith91** [comment]
Thanks for creating the issue! We'll investigate this asap

**Comment by msyyc** [comment]
version after 8.0.0b1 is track2 version, version before 8.0.0b1 is track1 version. The difference is introduced in changelog of 8.0.0b1. In the short future, we will not release public track1 version anymore. So we encourage to migrate to track2(migrattion guidance : https://devblogs.microsoft.com/azure-sdk/migrating-python-management-libraries/)

**Comment by logachev** [comment]
@msyyc 8.0.0b1 latest API version is 2019-12-01-preview. 3.0.0rc17 has 2020_11_01-preview.
When is the next release for Track 2 (assuming 8.0.0b1 is Track 2 and 3.0.0rc17 is Track1)?
When is the non-preview release?

**Comment by msyyc** [comment]
python SDK bases on swagger : https://github.com/Azure/azure-rest-api-specs/tree/master/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/stable. There is no newer stable api-version for containerregistry. In general, new Python SDK will be released after new api-version of swagger is merged into 'master'.

**Comment by logachev** [comment]
What I was saying is that Track 2 SDK (8.0.0b1) uses old API (2019-12-01) while Track 1 SDK (3.0.0rc17) uses newer API (2020-11-01).

When can we expect Track 2 SDK to get a support for 2020-11-01?

**Comment by xiangyan99** [comment]
With the latest version https://pypi.org/project/azure-mgmt-containerregistry/8.2.0/ is released, closing the issue as fixed.
