### ISSUE TITLE
Need to find a way to list conda package information

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#18371]
Like the information we show in https://azure.github.io/azure-sdk/releases/latest/python.html, we want to find a place for customers to know which packages are available in conda.

The issue we cannot combine the conda release status into https://azure.github.io/azure-sdk/releases/latest/python.html by adding new badge is we simplified the packages (e.g. we combined storage packages into one package) hence it is not a 1 on 1 mapping to the pypi one.

Given we plan to release every three months, the page will be updated quarterly. The information can be like 

https://adpconda.blob.core.windows.net/azuresdk/index.html

**Comment by scbedd** [comment]
Superceded by #27575. Closing.
