### ISSUE TITLE
Why does azure-storage-blob require Rust compiler?

### ISSUE THREAD

**Issue by guteksan** [Azure/azure-sdk-for-python#18381]
- azure-storage-blob**: 
- 12.8.1: 
- Windows 10:
- Python 3.7.0: 

I am trying to install azure-storage-blob, using both command line and PyCharm package manager

`pip install azure-storage-blob`

results in: `error: can't find Rust compiler`

Full log here:
[azure-storage-blob_install_failure.txt](https://github.com/Azure/azure-sdk-for-python/files/6391271/azure-storage-blob_install_failure.txt)

Someone who wants to just install this module to use blob clients, should not be required to install compilers.

**Comment by rakshith91** [comment]
@guteksan Thanks for reporting the concern! We'll investigate this asap

**Comment by tasherif-msft** [comment]
Hi @guteksan, this appears to be related to the cryptography package which is one of our dependencies. Could you try the instructions here https://cryptography.io/en/latest/faq/#installing-cryptography-fails-with-error-can-not-find-rust-compiler

**Comment by guteksan** [comment]
Updating pip solved the problem. Thanks.
