### ISSUE TITLE
Does this SDK support to create classic VM?

### ISSUE THREAD

**Issue by susanandwang** [Azure/azure-sdk-for-python#18382]
Does this SDK azure-mgmt-compute support to create classic VM? 
Or besides SDK azure-servicemanagement-legacy, is there any other python SDK that supports classic VM creation?
Thanks.

**Comment by rakshith91** [comment]
Thanks for posting the issue! Redirecting it to the right person

**Comment by jaylabell** [comment]
This SDK does not support classic VMs
Nor does any python.sdk support classic VM creation. 

Thank you for your question, hopefully this helps.
