### ISSUE TITLE
ImportError: cannot import name 'ContainerClient'

### ISSUE THREAD

**Issue by hoangmt** [Azure/azure-sdk-for-python#18429]
Look like `pip install azure-storage-blob` does not install the version corresponds to documentation. I got this problem: ImportError: cannot import name 'ContainerClient' when install using that command.  `pipinstall azure-storage-blob==12.8.1` fixes it however this small inconsistency should be fix.

**Comment by rakshith91** [comment]
@hoangmt  Thank you for reporting the issue! We'll look into this asap
