### ISSUE TITLE
Azure Core Tracing OpenTelemetry readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#18426]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/core/azure-core-tracing-opentelemetry#examples):
![image](https://user-images.githubusercontent.com/57166602/116523331-b5cee600-a908-11eb-8eed-e6dec79ecb39.png)

Reason:
ImportError: cannot import name 'SimpleExportSpanProcessor' from 'opentelemetry.sdk.trace.export'

Suggestion:
Update `SimpleExportSpanProcessor` to `SimpleSpanProcessor`.

@jongio for notification.

**Comment by xiangyan99** [comment]
Fixed.
