### ISSUE TITLE
Unable to query all NICs on a specific subscription 

### ISSUE THREAD

**Issue by tomkregenbild** [Azure/azure-sdk-for-python#18420]
I have a script that runs a query for each of our subscriptions and get all the network_interfaces under our subscription. It work great for all subscription but on a specific one subscription we started getting errors a few days ago. 

This is the command we run:
`network_client = NetworkManagementClient(azure_credentials_dict, subscription_id) `
`all_nics = list(network_client.network_interfaces.list_all())`

and this is the error we get:
`
azure.core.exceptions.HttpResponseError: (ProviderError) Resource provider 'Microsoft.Network' failed to return collection response for type 'networkInterfaces'.
`

I tried changing the API version of azure-mgmt-network from 18.0 to 17.1.0 but it did not help

**Comment by rakshith91** [comment]
Thanks for the issue! We'll investigate this asap

**Comment by tomkregenbild** [comment]
Had to reregister the network resource in Azure
