### ISSUE TITLE
Azure core samples issue

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#18421]
1. 
Section [link](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/samples/test_example_sansio.py#L176):
![image](https://user-images.githubusercontent.com/57166602/116520136-e745b280-a904-11eb-9a8e-f2ef64f99e80.png)

Reason:
response = policy.next.send(request)
AttributeError: 'SansIOHTTPPolicy' object has no attribute 'next'.

@jongio for notification.

**Comment by xiangyan99** [comment]
Fixed.
