### ISSUE TITLE
Communication chat readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#18423]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-chat#update-a-thread-topic):
![image](https://user-images.githubusercontent.com/57166602/116521468-98008180-a906-11eb-8929-5942f932de64.png)

Reason:
TypeError: get_properties() takes 1 positional argument but 2 were given

Suggestion:
Update to `chat_thread_client.get_properties()`.

2.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-chat#update-a-message):
![image](https://user-images.githubusercontent.com/57166602/116521563-b49cb980-a906-11eb-854d-d7ee01368842.png)

Suggestion:
Update to: `chat_message.content.message`.

@jongio for notification.

**Comment by jbeauregardb** [comment]
Fixed issue in this PR https://github.com/Azure/azure-sdk-for-python/pull/18435

@jongio
