### ISSUE TITLE
Communication Phone numbers Readme and samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#18424]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-phonenumbers#purchase-phone-numbers):
![image](https://user-images.githubusercontent.com/57166602/116521890-1e1cc800-a907-11eb-828d-cce5c29a1ed2.png)

Suggestion:
Update to `specified`.

2.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/communication/azure-communication-phonenumbers/samples):
![image](https://user-images.githubusercontent.com/57166602/116521975-368ce280-a907-11eb-926e-caf3c00ee69b.png)

Suggestion:
Should be consistent with the file name of the async samples of other services, for example: key vault, storage and so on. 
Update to:
```
get_purchased_phone_number_sample_async.py
list_purchased_phone_numbers_sample_async.py
purchase_phone_number_sample_async.py
release_phone_number_sample_async.py
search_available_phone_numbers_sample_async.py
update_phone_number_capabilities_sample_async.py
```

@jongio for notification.

**Comment by jbeauregardb** [comment]
We were fixing the sample naming convention in another PR. We also fixed the typo in the README. Here's the PR https://github.com/Azure/azure-sdk-for-python/pull/18234

**Comment by v-xuto** [comment]
Closed this issue because PR https://github.com/Azure/azure-sdk-for-python/pull/18234 merged.
