### ISSUE TITLE
Azure Cog Search documents - search method, include total count param is missing

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk-for-python#18431]
The Azure Python search's [search](https://docs.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.searchclient?view=azure-python#search-search-text----kwargs-) method is missing the include total count field in the source and documentation. 

The JS SDK has it in [src](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/search/search-documents/src/searchClient.ts#L257) but not in [docs](https://docs.microsoft.com/en-us/javascript/api/@azure/search-documents/searchclient?view=azure-node-latest#search_Fields__string__SearchOptions_Fields__) (known issue).  

The .NET SDK has it both in [src](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchOptions.cs#L25) and [docs](https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.searchoptions?view=azure-dotnet#properties). 

@dereklegenzoff @HeidiSteen - working on the py version of the tutorial now.

**Comment by xiangyan99** [comment]
Hi Scott, we do have the include_total_count in source code. https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/search/azure-search-documents/azure/search/documents/_search_client.py#L147-L149

Could you help to take a look why it does not show in docs?

**Comment by xiangyan99** [comment]
In fact, seems like the parameter is in the doc but in wrong format.

**Comment by scbedd** [comment]
[Link to exact location in docs.](https://docs.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.searchclient?view=azure-python-preview#search-search-text----kwargs-)

Breaking this down to understand where in the pipeline it's choking on this thing. It's the same as what is affecting #18280 

![image](https://user-images.githubusercontent.com/45376673/119565365-b5d2d200-bd5e-11eb-9be1-f0189f88e9da.png)

**Comment by xiangyan99** [comment]
Fixed.
