### ISSUE TITLE
[proposal not a bug] missing example how to proceed with B2CTenantsOperations class

### ISSUE THREAD

**Issue by michalswi** [Azure/azure-sdk-for-python#18433]
If it is possible I would appreciate if you can add here some example how to call in this class a specific method like **get**.  I know that I have to a create client first to call it but anyway don't know how to call this specific one. 

As a example if I want to use this one:  
https://docs.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.subscriptions.subscriptionclient?view=azure-python

I would do it like:  
```
from azure.identity import AzureCliCredential
from azure.mgmt import subscription
import os

credentials = AzureCliCredential()
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
client = subscription.SubscriptionClient(credentials)
tenants = client.tenants
(...)
```

if I use B2CTenantsOperations:
```
from azure.identity import AzureCliCredential
from azure.mgmt.azureadb2c.v2019_01_01_preview.operations import B2CTenantsOperations
import os

credentials = AzureCliCredential()
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
# no idea how to proceed with that
b2c = B2CTenantsOperations(client="",config="",serializer="",deserializer="")
b2c.get("test_b2c", "testb2c.onmicrosoft.com")
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fde6bedb-b127-1a67-070a-135ce5deed54
* Version Independent ID: 81e59310-e9f4-0f74-9cb8-a37c3b78d505
* Content: [azure.mgmt.azureadb2c.v2019_01_01_preview.aio.operations.B2CTenantsOperations class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-azureadb2c/azure.mgmt.azureadb2c.v2019_01_01_preview.aio.operations.b2ctenantsoperations?view=azure-python-preview)
* Content Source: [preview/docs-ref-autogen/azure-mgmt-azureadb2c/azure.mgmt.azureadb2c.v2019_01_01_preview.aio.operations.B2CTenantsOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/preview/docs-ref-autogen/azure-mgmt-azureadb2c/azure.mgmt.azureadb2c.v2019_01_01_preview.aio.operations.B2CTenantsOperations.yml)
* GitHub Login: @VSC-Service-Account

**Comment by rakshith91** [comment]
Thanks for posting the issue! We;ll take a look asap

**Comment by michalswi** [comment]
any update here? thx

**Comment by msyyc** [comment]
we will update sample for azureadb2c later. Before that, please reference sample https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/automation/manage_job.py of other package.

**Comment by xiangyan99** [comment]
@michalswi does the sample msyyc provided help?

Thanks.

**Comment by michalswi** [comment]
@xiangyan99 yes
