### ISSUE TITLE
[Tables] Swallow 404 on delete operations

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#18445]
This applies to both `delete_table` and `delete_entity`.
We should check if the 404 responses give us a specific error code that we can act on, but if not, simply swallow it rather than raising a ResourceNotFoundError. The same should apply to transactional operations if at all possible...

**Comment by seankane-msft** [comment]
Are we sure we want to swallow this error on transactional operations? It could be the only issue of a large transaction and not raising the ResourceNotFoundError (or some error) would lead to believing the transaction was successful when it was not. We raise a `TableTransactionError` right now in this case, I think this is a good error to raise, do you suggest we change @annatisch ?

**Comment by annatisch** [comment]
Yeah - that's true - no I think leaving the existing behaviour for transactions is correct.
