### ISSUE TITLE
[Tables] Add support for AzureNamedKeyCredential

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#18441]
This should be in place of the current dict/str based implementation.
The only supported types for the `credential` parameter will now be `AzureNamedKeyCredential`, `AzureSasKeyCredential` or via connection string (with samples/readme etc updated to match).

The azure-core dependency version will also need to be updated to match.

**Comment by seankane-msft** [comment]
@annatisch should this be `AzureKeyCredential` ?

**Comment by annatisch** [comment]
No, `AzureNamedKeyCredential`
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/credentials.py#L117
