### ISSUE TITLE
azure-identity 1.5.0 has different behaviors in Azure function and Azure VM

### ISSUE THREAD

**Issue by Yangsh-w** [Azure/azure-sdk-for-python#18454]
- **Package Name**:  [azure-identity](https://pypi.org/project/azure-identity/)
- **Package Version**: 1.5.0
- **Operating System**: windows 10
- **Python Version**: 3.8.7 in Azure function and 3.8.9 in Azure VM

**Describe the bug**
We could call the method DefaultAzureCredential() directly to get the credential via user managed identity in Azure VM, but we need to mention the client_id of the user managed identity as a parameter for DefaultAzureCredential(managed_identity_client_id=client_id) in Azure function.

**To Reproduce**
Python Script used to test in Azure function. Using azure-identity 1.5.0.
```
import logging
import os
from azure.identity import DefaultAzureCredential
import azure.functions as func
def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    try:
        resource_group_name = 'XXXX'
        disk_name = 'XXXXXX'
        subscription_id = 'XXXXXXXX'
        credential = DefaultAzureCredential()

        from azure.mgmt.compute import ComputeManagementClient
        from azure.mgmt.compute.models import Disk
        compute_client = ComputeManagementClient(credential, subscription_id)
        disk: Disk = compute_client.disks.get(resource_group_name, disk_name)
        logging.info('diskinfo: '+ str(disk))
        logging.info('--------')
    except Exception as err:
        logging.error( err)
    
    return func.HttpResponse("done")
```
Requirements.txt:
```
azure-functions
azure-identity
azure-mgmt-compute 
```

**Expected behavior**
Get the credential with the user managed identity of this Azure function successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/76461730/116641670-c8e0c500-a99f-11eb-8626-233badc9bf07.png)

**Additional context**
Add the client id of the user identity as the parameter of DefaultAzureCredential in the script.
 ```
        client_id = 'XXXXXXXXXXXXXXXXXX'
        credential = DefaultAzureCredential(managed_identity_client_id=client_id)
```
![image](https://user-images.githubusercontent.com/76461730/116641721-e31aa300-a99f-11eb-98d1-932f6abcb16a.png)

Same script in Azure VM using azure-identity 1.5.0.
```
from azure.identity import DefaultAzureCredential

resource_group_name = 'XXXX'
disk_name = 'XXXXX'
subscription_id = 'XXXXXXXX'

credential = DefaultAzureCredential()

from azure.mgmt.compute import ComputeManagementClient
from azure.mgmt.compute.models import Disk

compute_client = ComputeManagementClient(credential, subscription_id)
disk: Disk = compute_client.disks.get(resource_group_name, disk_name)

print('diskinfo: '+ str(disk))
```
![image](https://user-images.githubusercontent.com/76461730/116641772-fd548100-a99f-11eb-8a19-5237c19ad57d.png)

As we could see, the disk information could be read successfully. It was say the environment credential failed, so it must be the second approach managed identity credential passed.

**Comment by chlowell** [comment]
That error message is from the Function app's managed identity endpoint. Function apps (really, App Service) and VMs have different managed identity implementations. We can't hide the difference in this case. The Function app requires you to specify which user assigned identity you want to authenticate even when there is only one assigned to the app.

You could work around this without writing platform-specific code by setting AZURE_CLIENT_ID to your user assigned identity's client ID in the Function app's application settings ([details here](https://docs.microsoft.com/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=portal#settings)). Application settings are exposed to functions as environment variables, and DefaultAzureCredential will use the value of AZURE_CLIENT_ID as a managed identity client ID.

**Comment by Yangsh-w** [comment]
Thank you @chlowell for clarifying this issue!

**Comment by chlowell** [comment]
You're welcome! I'll close this issue as resolved then. Please reopen it if this problem recurs or open a new issue, if you encounter a new problem.
