### ISSUE TITLE
azure-mgmt-mixedreality is causing docs CI build errors

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#18457]
Build log: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=212523&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=348f8a99-4a85-56c7-5436-e2f3858e80ba&l=102683

Partial error output 

```
<Matched Warning>: D:\a\1\s\source_code\81\azure_mgmt_mixedreality-0.2.0\doc\azure.mgmt.mixedreality.rst:20: WARNING: autodoc: failed to import module 'azure.mgmt.mixedreality.version'; the following exception was raised:
looking for now-outdated files... none found
##[error]<Matched Error>: Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\sphinx\ext\autodoc.py", line 551, in import_object
    __import__(self.modname)
ModuleNotFoundError: No module named 'azure.mgmt.mixedreality.version'
```

This will be removed from the ref docs to unblock the build.

**Comment by scbedd** [comment]
This is ... odd. I would have expected the `depends` check in CI to have caught this.

I just checked the release and it definitely imported *. This means that there is a code path that `import *` doesn't catch, but is still broken.

I'll repro this when I'm in office today.

**Comment by scbedd** [comment]
The failure was occurring on version `0.2.0`.

The latest version is `1.0.0`. Adding back to pipeline.

**Comment by scbedd** [comment]
Verified it builds [ok in this build.](https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=217781&view=results) Committed back into master in [this commit](https://github.com/MicrosoftDocs/azure-docs-sdk-python/commit/0c76ab96c9c89df96bc4d87aad236155dae1753e)
