### ISSUE TITLE
Code snippet to list containers contains code that deletes containers

### ISSUE THREAD

**Issue by ntindle** [Azure/azure-sdk-for-python#18467]
The demo script contains code to delete any container that starts with "test-". I would say that would be a horrible thing to occur when you try and list your containers. 

https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobserviceclient?view=azure-python#list-containers-name-starts-with-none--include-metadata-false----kwargs-

```python
# List all containers
   all_containers = blob_service_client.list_containers(include_metadata=True)
   for container in all_containers:
       print(container['name'], container['metadata'])

   # Filter results with name prefix
   test_containers = blob_service_client.list_containers(name_starts_with='test-')
   for container in test_containers:
       blob_service_client.delete_container(container)
```

it appears the offending example is here: https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/a1b067bc9e85449eee1aea29f3605da25eea6a54/docs-ref-autogen/azure-storage-blob/azure.storage.blob.BlobServiceClient.yml#L594

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c573ca4-d03c-8651-5bc0-69debe989f9a
* Version Independent ID: 05961166-7e4d-6232-74b4-2607cd3318a1
* Content: [azure.storage.blob.BlobServiceClient class](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobserviceclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.BlobServiceClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-storage-blob/azure.storage.blob.BlobServiceClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by rakshith91** [comment]
Thanks for reporting this! We'll take a look asap

**Comment by tasherif-msft** [comment]
Hi @ntindle we can adjust this code snippet to print instead

**Comment by tasherif-msft** [comment]
Hi @ntindle I have put out the change here https://github.com/Azure/azure-sdk-for-python/pull/18560

**Comment by ntindle** [comment]
Thanks! Feel free to close when merged.
