### ISSUE TITLE
[Question] How does one extend a ServiceBusReceivedMessage lock time?

### ISSUE THREAD

**Issue by ali-elgabri** [Azure/azure-sdk-for-python#18477]
A `ServiceBusReceivedMessage` has an autolock for about 30 seconds default; but how does one update it to be a longer time or, better yet, remove the lock entirely? A lot of times, it takes my service longer than 30 seconds to to fully do what it needs to do with a received message, and the message is then "locked" and I can't do anything with it. 

Any ideas? 

Edit: some more context:

I am running a while-loop that acts as a simple listener on a topic. Whenever a message is published to the topic and meets some filter requirements, a `ServiceBusReceiver` will return to me the message(s), and I run some logic based on the message received. However, several times when I attempt to complete or abandon the message, I get an exception that the lock has expired. I have something that looks like this:

```python
async def run_listener(self, receiver: ServiceBusReceiver):
    while True:
        received_msgs = await receiver.receive_messages(max_message_count=5)
        for msg in received_msgs:
            <process_message>
            except Exception:
                await receiver.abandon_message(message=msg)
```

This [here](https://github.com/Azure/azure-sdk-for-python/blob/f7e968ecab2a783753f58232e9ec429de96ece54/sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py#L413) usually gets triggered:

```python
        if not self._session and message._lock_expired:
            raise ServiceBusError(
                message="The lock on the message lock has expired.",
                error=message.auto_renew_error,
            )
```

I need this time to be increased or done with entirely (messages dont expire).

**Comment by seankane-msft** [comment]
@ali-elgabri thank you for reporting this, we will investigate the issue!

**Comment by yunhaoling** [comment]
hey @ali-elgabri , I'm sorry to tell you that the lock could not be removed entirely, this is a service feature.

to avoid the lock expiration, you should either renew the lock on the message or receive the message in `ReceivedAndDelete` mode.

- To renew message lock, you could either use `ServiceBusReceiver.renew_message_lock` or `AutoLockRenewer` to renew the messages.
  - You could check our [readme](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus#receive-messages-from-a-queue) for more information:
    > NOTE: Any message received with receive_mode=PEEK_LOCK (this is the default, with the alternative RECEIVE_AND_DELETE removing the message from the queue immediately on receipt) has a lock that must be renewed via receiver.renew_message_lock before it expires if processing would take longer than the lock duration. See AutoLockRenewer for a helper to perform this in the background automatically. Lock duration is set in Azure on the queue or topic itself.
  - And the api reference for `renew_message_lock` is available [here](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/7.1.1/azure.servicebus.html#azure.servicebus.ServiceBusReceiver.renew_message_lock).

- There're service docs on illustrating how locks are working and what different receive modes are:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#renew-locks which might help to some extent.


Let me know if you have any other questions!

**Comment by ali-elgabri** [comment]
@yunhaoling Thank you for your response!

I am having trouble understanding the use of `renew_message_lock`. From the docs:

> In order to complete (or otherwise settle) the message, the lock must be maintained, and cannot already have expired; **_an expired lock cannot be renewed._**

So what exactly is the point? To renew the lock every `T-1 seconds`, where `T=expiration_time`? 

Case in point:

```python
@staticmethod
async def complete_message(servicebus_message: ServiceBusReceivedMessage,
                           servicebus_receiver: ServiceBusReceiverAsync):
    """ Function will complete the service bus message. This removes the message from the queue.
    """
    try:
        await servicebus_receiver.complete_message(message=servicebus_message)
    except ServiceBusError as e:
        logger.info(f'Encountered an error completing the message: ({e.message}); attempting to renew lock.')
        await servicebus_receiver.renew_message_lock(servicebus_message)
        await servicebus_receiver.complete_message(servicebus_message)
```
Results in:

```
Failed to complete mgmt operation.
Status code: 410
Message: b'The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:<referenceid>, TrackingId:<trackingid>, SystemTracker:<service bus>....
```

**Comment by ali-elgabri** [comment]
@yunhaoling Is there potentially something like Java's [MessageHandlerOptions](https://github.com/Azure/azure-sdk-for-java/blob/026664ea871586e681ab674e0332b6cc2352c655/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/MessageHandlerOptions.java) in the python sdk?

**Comment by ali-elgabri** [comment]
Alright, following the doc [here](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.aio.html#id24) fixed my issue. This issue can be closed; thanks for the prompt response guys :)

**Comment by yunhaoling** [comment]
@ali-elgabri glad you find the solution!

thanks for your time into the docs, I'm closing the issue now.
feel free to reach out if you have any other questions or suggestions regarding to our doc/samples. I would always be glad to help :)
