### ISSUE TITLE
Client for creating Diagnostic settings for AAD logs

### ISSUE THREAD

**Issue by pintub** [Azure/azure-sdk-for-python#18476]
**Is your feature request related to a problem? Please describe.**
There is no Client class present in python sdk to create Diagnostic settings for AAD logs . 
[MonitorManagementClient](https://docs.microsoft.com/en-us/python/api/azure-mgmt-monitor/azure.mgmt.monitor.monitormanagementclient?view=azure-python) doesn't have methods to support this, as a result we have to call the API `https://management.azure.com/providers/microsoft.aadiam/diagnosticSettings/new-ds?api-version=<API_VERISON>` explicitly using a rest client(i.e. using `requests` library)

**Describe the solution you'd like**
Provide a client to to manage Diagnostic settings for AAD logs

**Describe alternatives you've considered**
we have to call the API `https://management.azure.com/providers/microsoft.aadiam/diagnosticSettings/new-ds?api-version=<API_VERISON>` explicitly using a rest client(i.e. using `requests` library)

**Comment by seankane-msft** [comment]
@pintub thank you for reporting this, we will investigate the issue!

**Comment by 00Kai0** [comment]
Hi @pintub , I don't find this api version 2017-04-01-preview for monitor service. Where did you get it ?

**Comment by pintub** [comment]
Hi @00Kai0 , actual version is `2017-04-01`, I found it from network tools of browser . But this thread is not specific to any version, I could not find a client in python azure SDK to create Diagnostic settings for AAD logs

**Comment by 00Kai0** [comment]
There is an operation in monitor to create Diagnostic settings:https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/_monitor_management_client.py#L343

**Comment by pho-enix** [comment]
@RAY-316 I didn't find an implementation of this provider in the Azure SDKs. Is there an update on this? I want to highlight @pintub statement that `Microsoft.AadIam/diagnosticSettings` is a different provider than all the Diagnostics Settings for certain resource types.

**Comment by pho-enix** [comment]
`/unresolve`
