### ISSUE TITLE
HIGHLIGHT THE DATA FORMAT AND PROTOCOL OF MESSAGES PLEASE

### ISSUE THREAD

**Issue by 12DReflections** [Azure/azure-sdk-for-python#18475]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8105f99e-e5ee-2f17-3f2b-3239209a0449
* Version Independent ID: a0c4fc51-e02f-c5a6-0d5b-8620afc32165
* Content: [azure.iot.device.Message class](https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.message?view=azure-python)
* Content Source: [docs-ref-autogen/azure-iot-device/azure.iot.device.Message.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-iot-device/azure.iot.device.Message.yml)
* Product: **azure-iot**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by seankane-msft** [comment]
@12DReflections do you have feedback for this issue?
