### ISSUE TITLE
Connection in an unexpected error state. Error condition: ErrorCodes.UnknownError.

### ISSUE THREAD

**Issue by csyvenky** [Azure/azure-sdk-for-python#18497]
- **Package Name**:  azure-servicebus, uamqp
- **Package Version**: 7.1.1, 1.4.0
- **Operating System**: Windows 10 v.1909
- **Python Version**: Python 3.9.2

**Describe the bug**
Script terminates with noted exception while executing very simple code (`receive_messages` method) to read from Service Bus queue.

Development workstation is behind corporate security networking and VPN. However, I have no issues calling Blob or Table storage APIs from the same project.

I have read thru previous bug reports and have tried with `transport_type=TransportType.AmqpOverWebsocket`. No joy.

I have validated from another, non-VPN'd workstation that same code works as expected, against the same S/B namespace.

Seems to be related to: #16816

**To Reproduce**
1. Copy example from [PyPi](https://pypi.org/project/azure-servicebus/#receive-messages-from-a-queue) and execute with VS Code.

**Expected behavior**
I would expect to be able to programmatically de-queue messages from the S/B namespace.

**Debug Logs**
`DEBUG:uamqp.client:Opening client connection.
DEBUG:uamqp:Initializing platform.
INFO:uamqp.connection:Connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' state changed from <ConnectionState.START: 0> to <ConnectionState.START: 0>
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'DictValue'
DEBUG:uamqp.c_uamqp:Destroying 'DictValue'
INFO:uamqp.connection:Connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' state changed from <ConnectionState.START: 0> to <ConnectionState.START: 0>
INFO:uamqp.c_uamqp:b'Socketio_Failure: Receiving data from endpoint: 10054.' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\socketio_win32.c':b'socketio_dowork':693)
INFO:uamqp.connection:Connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' state changed from <ConnectionState.START: 0> to <ConnectionState.END: 13>
INFO:uamqp.connection:Connection with ID b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' unexpectedly in an error state. Closing: False, Error: None
INFO:uamqp.c_uamqp:b'AMQP management instance not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\amqp_management.c':b'amqp_management_close':1029)
INFO:uamqp.c_uamqp:CBS for connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' completed opening with status: 2
DEBUG:uamqp.c_uamqp:Wrapping value type: <AMQPType.CompositeType: 23>
DEBUG:uamqp.c_uamqp:Wrapping value type: <AMQPType.CompositeType: 23>
INFO:uamqp.receiver:Message receiver b'receiver-link-7f05076e-2bc6-47f5-9b5b-48fab8015fac' state changed from <MessageReceiverState.Idle: 1> to <MessageReceiverState.Opening: 2> on connection: b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'
INFO:uamqp.receiver:Receiver link failed to open - expecting to receive DETACH frame.
WARNING:uamqp.connection:ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')
DEBUG:uamqp.c_uamqp:Destroying cMessageReceiver
DEBUG:uamqp.c_uamqp:Destroying cLink
DEBUG:uamqp.c_uamqp:Deallocating 'CompositeValue'
DEBUG:uamqp.c_uamqp:Destroying 'CompositeValue'
DEBUG:uamqp.c_uamqp:Deallocating 'CompositeValue'
DEBUG:uamqp.c_uamqp:Destroying 'CompositeValue'
DEBUG:uamqp.c_uamqp:Deallocating cLink
DEBUG:uamqp.c_uamqp:Deallocating cMessageReceiver
DEBUG:uamqp.client:CBS session pending.
DEBUG:uamqp.client:Closing exclusive connection.
DEBUG:uamqp.connection:Unlocked connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' to close.
INFO:uamqp.connection:Shutting down connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'.
INFO:uamqp.authentication.cbs_auth:Shutting down CBS session on connection: b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'.
DEBUG:uamqp.authentication.cbs_auth:Unlocked CBS to close on connection: b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'.
DEBUG:uamqp.c_uamqp:Destroying CBSTokenAuth for connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'
INFO:uamqp.c_uamqp:Token put complete with result: 2, status: 0, description: b'CBS Session closed.', connection: b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'
INFO:uamqp.authentication.cbs_auth:Auth closed, destroying session on connection: b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'.
DEBUG:uamqp.c_uamqp:Destroying cSession
INFO:uamqp.authentication.cbs_auth:Finished shutting down CBS session on connection: b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'.
DEBUG:uamqp.c_uamqp:Destroying Connection
INFO:uamqp.c_uamqp:b'send called while not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\saslclientio.c':b'saslclientio_send_async':1181)  
INFO:uamqp.c_uamqp:b'Cannot send encoded bytes' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'on_bytes_encoded':268)
INFO:uamqp.c_uamqp:b'saslclientio_close called while not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\saslclientio.c':b'saslclientio_close_async':1130)
INFO:uamqp.c_uamqp:b'xio_close failed' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'on_bytes_encoded':272)
INFO:uamqp.connection:Connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' state changed from <ConnectionState.END: 13> to <ConnectionState.END: 13>
INFO:uamqp.c_uamqp:b'-> [CLOSE]* {}'
INFO:uamqp.connection:Connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' state changed from <ConnectionState.END: 13> to <ConnectionState.END: 13>
INFO:uamqp.c_uamqp:b'saslclientio_close called while not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\saslclientio.c':b'saslclientio_close_async':1130)
INFO:uamqp.c_uamqp:b'xio_close failed' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'connection_close':1437)
DEBUG:uamqp.c_uamqp:Destroying XIO
DEBUG:uamqp.c_uamqp:Destroying XIO
DEBUG:uamqp.c_uamqp:Destroying SASLMechanism
INFO:uamqp.connection:Connection shutdown complete b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'.
DEBUG:uamqp:Deinitializing platform.
INFO:azure.servicebus._base_handler:AMQP error occurred: (ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')), condition: (<ErrorCodes.UnknownError: b'amqp:unknown-error'>), description: (b'Connection in an unexpected error state.').
INFO:azure.servicebus._base_handler:'servicebus.pysdk-ba97e082' has an exception (ServiceBusConnectionError('Connection in an unexpected error state. Error condition: ErrorCodes.UnknownError.')). Retrying...
DEBUG:uamqp.client:Opening client connection.
DEBUG:uamqp:Platform already initialized.
INFO:uamqp.connection:Connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' state changed from <ConnectionState.START: 0> to <ConnectionState.START: 0>
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'StringValue'
DEBUG:uamqp.c_uamqp:Destroying 'StringValue'
DEBUG:uamqp.c_uamqp:Deallocating 'DictValue'
DEBUG:uamqp.c_uamqp:Destroying 'DictValue'
INFO:uamqp.connection:Connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' state changed from <ConnectionState.START: 0> to <ConnectionState.START: 0>
INFO:uamqp.c_uamqp:b'Socketio_Failure: Receiving data from endpoint: 10054.' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\socketio_win32.c':b'socketio_dowork':693)
INFO:uamqp.connection:Connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' state changed from <ConnectionState.START: 0> to <ConnectionState.END: 13>
INFO:uamqp.connection:Connection with ID b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' unexpectedly in an error state. Closing: False, Error: None
INFO:uamqp.c_uamqp:b'AMQP management instance not open' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\src\\amqp_management.c':b'amqp_management_close':1029)
INFO:uamqp.c_uamqp:CBS for connection b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf' completed opening with status: 2
DEBUG:uamqp.c_uamqp:Wrapping value type: <AMQPType.CompositeType: 23>
DEBUG:uamqp.c_uamqp:Wrapping value type: <AMQPType.CompositeType: 23>
INFO:uamqp.receiver:Message receiver b'receiver-link-93704cc2-7613-4072-9b44-bc27f154de9c' state changed from <MessageReceiverState.Idle: 1> to <MessageReceiverState.Opening: 2> on connection: b'SBReceiver-d5cc7898-66ac-450f-bb7c-2c5474c829cf'
INFO:uamqp.receiver:Receiver link failed to open - expecting to receive DETACH frame.
WARNING:uamqp.connection:ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')`

**Comment by seankane-msft** [comment]
@YalinLi0312 thank you for reporting, we will investigate this ASAP!

**Comment by yunhaoling** [comment]
hey @csyvenky,

The key error information is this one: `INFO:uamqp.c_uamqp:b'Socketio_Failure: Receiving data from endpoint: 10054.`.

I'm wondering if there's any configuration on your networking environment that's blocking the requests from Service Bus.

Service Bus is different from Blob/Table which use http protocol for communication -- it is built on top of an application layer networking protocol called AMQP.

The two different transport type:
- Amqp: port 5671 is used for communication with the service, Amqp connection is built over tcp connection
- AmqpOverWebsocket: port 443 is used for communication with the service, Amqp connection is built over a web socket connection (and websocket is over tcp connection).

Do you have any settings in your corporate security networking or VPN that only certain protocols and ports are allowed?

**Comment by csyvenky** [comment]
> Do you have any settings in your corporate security networking or VPN that only certain protocols and ports are allowed?

Almost 100% certain there is. I must have misinterpreted the AmqpOverWebsocket option - I incorrectly thought that meant the system would try HTTPS. But, now that I look at it, the answer is right in the name.

**Comment by yunhaoling** [comment]
I think one potential workaround is to have a proxy set up within your network, and then let the EH client communicate with the proxy. But honestly I don't know how hard that would be in your corporate security networking and VPN.

is there anything else I could help you with this?

**Comment by csyvenky** [comment]
No thank you, @yunhaoling, very much appears to be an environmental issue on my side. Thanks for following up and for all the great contributions.

**Comment by yunhaoling** [comment]
@csyvenky , not a problem, glad that I could help you.
I'm closing the issue now, feel free to reach out if you need any kind of help!
