### ISSUE TITLE
Creating PathProperties with kwargs raises exception

### ISSUE THREAD

**Issue by kosinsky** [Azure/azure-sdk-for-python#18490]
- **Package Name**:  azure.storage.datalake
- **Package Version**: 12.3.1
- **Operating System**: Any
- **Python Version**:  3.5+

**Describe the bug**
Attempt to create PathProperties with kwargs raises `TypeError: object.__init__() takes no parameters`
That makes mocking DataLike in test difficult

**To Reproduce**
1. Run python REPL
2. Execute following code
```python
from azure.storage.filedatalake import PathProperties
PathProperties(name="bla")
```
Result
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<user>/.pyenv/versions/3.5.7/lib/python3.5/site-packages/azure/storage/filedatalake/_models.py", line 231, in __init__
    **kwargs
TypeError: object.__init__() takes no parameters
```
**Expected behavior**
PathProperties object returned

**Comment by seankane-msft** [comment]
@kosinsky thank you for reporting, we will investigate asap!

**Comment by tasherif-msft** [comment]
Thank you for reporting this @kosinsky, putting out a fix for this issue

**Comment by tasherif-msft** [comment]
Hi @kosinsky I have put out a fix here https://github.com/Azure/azure-sdk-for-python/pull/18559/files
