### ISSUE TITLE
BlobService.set_container_acl optional param not documented

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-python#185]
`signed_identifiers` is also optional, but not documented as so.

![image](https://cloud.githubusercontent.com/assets/159209/3784443/70dba876-19b8-11e4-8f74-8ce55049f235.png)

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/14
