### ISSUE TITLE
Standardize on repositoryName parameter in ContainerRegistryClient methods

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-python#18503]
The following methods should take `repositoryName` as the parameter for the name of the repository:

- DeleteRepository
- GetArtifact
- GetRepository

Please see the [latest APIView](https://apiview.dev/Assemblies/Review/ba57bf904e524ce3bf647dad124ddc7c) for details.

**Comment by seankane-msft** [comment]
#18392
