### ISSUE TITLE
AKS webservice deploy and Update

### ISSUE THREAD

**Issue by percybolmer** [Azure/azure-sdk-for-python#18501]
- **Package Name**: 
- azureml.core.webservice
- **Package Version**: 
- 1.26.0
- **Operating System**:
- Linux
- **Python Version**: 
- 3.6.2

**Describe the bug**
Running a deployment step inside azureml Pipeline im getting a weird behavior when trying to deploy vs update.
The first time I run the pipeline everything works fine, the second time (webservice exists) so I want to Update it instead, I'm getting 
FileNotFoundError: [Errno 2] No such file or directory: '/var/azureml-app/04374e9c-f034-440c-8433-8359dab1b6ac/predict.py'

**To Reproduce**
Create a Pipeline step that runs
```python
    deployment_step = PythonScriptStep(
        script_name="deploy-model.py",
        source_directory="./src",
        compute_target=compute_target,
        runconfig=pipeline_run_config,
        allow_reuse=True,
    )

```
Inside deploy-model I deploy or Update depending on if the Webservice exists
```python
    inference_config = InferenceConfig(
        source_directory="./",
        entry_script="predict.py",
        environment=env,
    )

    deployment_config = AksWebservice.deploy_configuration(autoscale_enabled=False, 
                                                        num_replicas=1,
                                                        cpu_cores = 4,
                                                        memory_gb = 24,
                                                        )
    """ Search for the Webservice, and if it exists, Update Instead of deploy """
    
    try:
        service = Webservice(workspace=ws, name=endpoint)
        service.update(models=[my_model], inference_config=inference_config)
    except WebserviceException:
        """ Service did not exist, so lets create it from scratch """
        service = Model.deploy(ws, name=endpoint,
                    models=[my_model],
                    inference_config=inference_config,
                    deployment_target=aks_target,
                    deployment_config=deployment_config)

    service.wait_for_deployment(show_output=True)
```
**Expected behavior**
I expect the update to find the files just as model.Deploy finds them, seeing as the inference config is the same.

**Comment by seankane-msft** [comment]
@shbijlan thank you for reporting, we will investigate this ASAP!

**Comment by luigiw** [comment]
Closing legacy issue.

Please consider upgrading to AzureML v2 CLI/SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2
