### ISSUE TITLE
SubscriptionClient.subscriptions.list doesn't return any tags

### ISSUE THREAD

**Issue by HarryBrooks** [Azure/azure-sdk-for-python#18511]
My basic use is as follows:
```
client = SubscriptionClient(creds)
subs = c.subscriptions.list()
for sub in subs:
    print(sub)
```
For each subscription returned, all have
`
'tags': None
`

I'm using azure-mgmt-resource and the model version (2019-11_01). If it helps, the method subscriptions.get(sub_id) does return tags successfully.

**Comment by seankane-msft** [comment]
Thank you for reporting @HarryBrooks , we will investigate ASAP!

**Comment by HarryBrooks** [comment]
Done some digging our end and have discovered it appears to be an issue with permissions across the API as a whole rather than the python sdk. I'll close this and open an issue in the correct area. Thanks!
