### ISSUE TITLE
The description of ExponentialRetry in azure-storage-blob is inconsistent with the implementation.

### ISSUE THREAD

**Issue by katz** [Azure/azure-sdk-for-python#18510]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.8.1
- **Operating System**: N/A
- **Python Version**: 3.8.6

**Describe the bug**
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py#L528-L532
In the description of `ExponentialRetry`, it says the default behavior is "the first retry occurs after 15 seconds, the second after (15+3^1) = 18 seconds".

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py#L565
However, the calculation of backoff time is: `backoff = self.initial_backoff + (0 if settings['count'] == 0 else pow(self.increment_base, settings['count']))`
And, when the first retry occurs, `settings['count']` is set to `1` and the backoff would be (15+3^1) = 18 seconds, which is inconsistent with the above desctiption.

**Expected behavior**
Modify the description or the implementation.

**Comment by seankane-msft** [comment]
@katz thank you for reporting! We will investigate ASAP

**Comment by tasherif-msft** [comment]
Hi @katz, I will look into this issue and will update you once a PR is out!

**Comment by tasherif-msft** [comment]
Hi @katz I have put out a PR to change the logic slightly, I will let you know once it gets merged or any updates

**Comment by tasherif-msft** [comment]
Hi @katz, just an update, the change may actually be more complicated than I initially thought. I will keep you in the loop
