### ISSUE TITLE
`set_role_definition` for Key Vault should reorder parameters

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#18579]
Based on our API unification review, Python should reorder parameters accordingly:

1. role_scope : required `KeyVaultRoleScope`
2. role_definition_name : optional UUID - autogenerate if None, but document that if customers don't provide a fixed value of an existing definition, a new one will be created.
3. role_name : optional string - friendly display name; document that it defaults to role_definition_name if absent
4. description : optional string - long-form description of role definition
5. permissions : optional list of `KeyVaultPermission`
6. assignable_scopes : optional list of `KeyVaultRoleScope`

We'll use this issue to track any changes to the API from other languages' issues. .NET, Java, and JavaScript should consider a `KeyVaultRoleDefinitionParameters` as an options bag given the number of possible arguments. Currently, the "Parameters" suffix is the guideline if it contains required parameters, but there is some question about this.

/cc @KrzysztofCwalina @tg-msft @annatisch @johanste @JonathanGiles @bterlson

**Comment by heaths** [comment]
Alternatively, we could all probably unify on making the first two parameters positional arguments in the method, and the rest in an options bag/kwargs which should be in line with our respective guidelines. The first two are the only two that are really required (the second is required, but we can / will autogenerate). Thoughts?

**Comment by JonathanGiles** [comment]
The code in your previous comment is suitable for translation and usage in Java too.
