### ISSUE TITLE
Documentation bug in MachineLearningNoteBook

### ISSUE THREAD

**Issue by percybolmer** [Azure/azure-sdk-for-python#18597]
- **Package Name**: 
- azureml.core.authentication
- **Package Version**: 
- azureml-core                         1.26.0
- **Operating System**:
- Linuxs (ubuntu 20.4)
- **Python Version**: 
- 3.8

**Describe the bug**
Following the documentation 
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb

To extract a token it's says to use Audience.aml, however, that variable does not exist. Instead AZUREML exists. 

**To Reproduce**
1. Set a debugger in the script located at Token Authentication section
2. Or just import Audience and set a debugger and execute it

**Expected behavior**
Documentation error probably

**Screenshots**
https://ibb.co/Qn6hYJt

**Comment by luigiw** [comment]
Closing legacy issue.

Please consider upgrading to AzureML v2 CLI/SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2
