### ISSUE TITLE
[ACR] Incorporate API review feedback from Arch Board

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-python#18618]
- [x] Rename `GetTagProperties` to `GetTag` (or language appropriate)
- [x] Remove `LoginServer` and `Name` properties from `ContainerRegistryClient`
- [ ] Come up with better name for `ArtifactManifestReference`
- [x] Remove the `DeleteRepositoryResult` type, and return a success result from `DeleteRepository` operation even when a 404 is received.
- [ ] Evaluate `FullyQualifiedName` with regard to 1) what we do in other Track 2 libraries wrt to the qualified name concept and 2) what this is commonly called in the Docker/containers community.
- [ ] Replace `TagOrDigest` with `Digest`.
- [ ] Ensure functional parity of Python library with others
- [x] Rename PATCH service methods from `Set..` to `Update..`
- [ ] Discuss parallelizing the delete sample across languages

**Comment by annelo-msft** [comment]
@seankane-msft , would you add Python-specific items from the arch board meeting to this?

**Comment by seankane-msft** [comment]
- [] Flatten `ContainerRegistryClient`
- [] Support partial updates for update methods. Use overloaded methods.
