### ISSUE TITLE
Export metrics to Azure Application Insights using Opentelemetry

### ISSUE THREAD

**Issue by fswane** [Azure/azure-sdk-for-python#18610]
**Feature request: Export metrics to ApplicationInsights**
Microsoft Opentelemetry exporter for Azure Monitor only supports exporting of *traces* to Application Insight.  I need to export *metrics* from a Python application to Application Insights. 

This release of opentelemetry-python adds support for *metrics*:
https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.10a0

and the azure-sdk-for-python should provide matching support.

**Describe the solution you'd like**
I need a metrics exporter, AzureMonitorMetricsExporter, that when enabled with an ApplicationInsights connection string will export metrics to Azure from my Python application.

@rakshith91

**Comment by rakshith91** [comment]
@fswane Thanks for logging the issue - we'll investigate this asap

**Comment by lzchen** [comment]
@fswane 
Azure sdk provides a metric exporter using OpenTelemetry an a feature in the [feature branch](https://github.com/Azure/azure-sdk-for-python/tree/feature/monitor-unreleased/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics). Keep in mind this is still in beta and the apis are subject to breaking changes so we do not recommend this for production environments. In fact, metrics is being [revamped](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics) within these few months so the current api/sdk will most likely soon be changed. However feel free to play with it to try it out :)

**Comment by gdhuper** [comment]
@lzchen Is there an ETA on when this feature would be ready for production?

**Comment by lzchen** [comment]
@gdhuper 
There is no current ETA.

**Comment by fswane** [comment]
Thanks.  I will check out the latest release.  Happy to see metrics made it into this release!

Regards
Francois

--
Francois Swanepoel
CTO, Stone Three (Pty) Ltd
(w) +27-21-851 3123
http://www.stonethree.com


________________________________

**Comment by fswane** [comment]
/unresolve

As the opentelemetry-python package brougth *metrics* support into the main branch (end of 2021), do you have plans to bring metrics support into the main branch of the Azure exporter?

Regards
Francois

**Comment by lzchen** [comment]
@fswane 

Metrics support for Azure exporter most likely will not be implemented until metrics in OpenTelemetry achieves stable status. Feel free to use this issue as a tracking ticket.

**Comment by fswane** [comment]
Morning @lzchen 

Metrics are now released as part of OpenTelemetry!

https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.12.0rc1

1) Do you have an ETA  to update the metrics exporter for ApplicationInsights?

2) An alternative that could also work for me is to use a Collector to receive metrics from local containers using OTLP and the Collector then routes metrics to ApplicationInsights.  Do you know if such functionality exists?

Regards
Francois

**Comment by lzchen** [comment]
> Do you have an ETA to update the metrics exporter for ApplicationInsights?

Will be doing a release for metrics exporter once metrics becomes stable in OT (rc tag is removed).

> An alternative that could also work for me is to use a Collector to receive metrics from local containers using OTLP and the Collector then routes metrics to ApplicationInsights. Do you know if such functionality exists?

Currently OT Python has an otlp metrics [exporter](https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/metric_exporter/__init__.py) but there is no exporter that maps otlp signals to app insights.

**Comment by fswane** [comment]
Thanks @lzchen, looking forward to using the updated metrics exporter!
