### ISSUE TITLE
[ACR] Add Perf Tests

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-python#18622]
Add perf tests for ACR types using language-appropriate approach

.NET perf test scenarios: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/perf/Azure.Containers.ContainerRegistry.Perf/Scenarios

**Comment by YalinLi0312** [comment]
Fixed.
