### ISSUE TITLE
Update sample_create_client.py for Beta 3 API

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-python#18657]
The [sample_create_client.py](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/containerregistry/azure-containerregistry/samples/sample_create_client.py) feels like it fits to the shape of the original Beta 1 sample.  Please consider making the following updates:

- [x] Refer to `ContainerRepository` as something other than client [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/containerregistry/azure-containerregistry/samples/sample_create_client.py#L40) and [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/containerregistry/azure-containerregistry/samples/sample_create_client.py#L61)
- [x] Since `ContainerRepository` isn't a client, we shouldn't be able to create an instance of it directly as we do [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/containerregistry/azure-containerregistry/samples/sample_create_client.py#L46), unless this is a Python-specific requirement.
- [x] In the proposed Beta3 API, we're not exposing functionality to list tags on a repository directly as we do [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/containerregistry/azure-containerregistry/samples/sample_create_client.py#L65).
- [x] If you'd like to illustrate the use of `ContainerRepository` in this sample, consider also including an illustration of `ArtifactRegistry`, as it is another Helper type that makes service calls.

**Comment by seankane-msft** [comment]
@annelo-msft Regarding your second point, is it impossible to create an instance of `ContainerRepository` directly? I haven't discovered a way to completely forbid this on the Python side.

**Comment by annelo-msft** [comment]
I'm not sure what's possible in Python for these mini-client types.  Do you have an example of something similar to the .NET [CosmosDatabase](https://apiview.dev/Assemblies/Review/0de57f00b1ad4fdab2fa218f59863c78#Azure.Cosmos.CosmosDatabase) type in the Python Cosmos library?  

If Python does allow creating an instance directly, consider not illustrating this in a sample, and instead using the getter method on the ContainerRegistryClient?

**Comment by seankane-msft** [comment]
I don't see this functionality on the cosmos python library. For now I won't show creating the client directly and refer to the `get_repository` method.
