### ISSUE TITLE
cspell - add "python" language to cspell dictionaries list to prevent false positives in non-source files

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#18674]
In non-source files (e.g. examples in markdown files) source code specific terms (e.g. `struct`) is treated as an error. Add the language to `dictionaries` in the `cspell.json` file to prevent these false positives. 
  
Source: https://github.com/Azure/azure-sdk-for-net/pull/21027/files#r631288645

**Comment by Lonanche** [comment]
While making sure that most of the python keywords are ignored after adding python to the spell checker dictionaries list I found a lot of typos. Should I fix them and make one larger pull request or should I make a pull request for that issue and then open another one for fixing typos?

**Comment by danieljurek** [comment]
Hey @Lonanche, thanks for your contributions here! In the interest of closing out this issue let's keep the PR just as you made it. 

If we expand the scope too much then merging your PR could get hung up on nuances around handling of certain words. I've approved your PR.
