### ISSUE TITLE
[EventHubs] Support for AMQPAnnotatedMessage

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#18677]
duplicate what we have for the AMQPAnnotatedMessage in service bus: https://github.com/Azure/azure-sdk-for-python/issues/18665, and introduce extra public fields on EventData

API Skeleton:

- new namespace as in the service bus
- new AMQPAnnotatedMessage class in the new namespace
- new body type enum/amqpheader/amqpproperties class in the new namespace
- send batch should support AMQPAnnotatedMessage
- EventData should have extra public properties:
  - Pull up ContentType, MesssageId and CorrelationId as top level properties

Action item:
- settle down on the service bus design
- prepare api proposal/gist and get arch approval
  - cross team discussion
    - whether we want a preview or just GA it
  - could be a simple one, as it's mostly the same as servicebus
- implement
  - copy&paste service bus impl and adapt to eventhub
  - add the required public properties to eventdata
- test & sample & doc

**Comment by swathipil** [comment]
Have a draft PR out for this which includes the idempotent producer feature as well. However, it was decided in code complete week of June that this should not be a preview release. As a result, will need to de-couple the idempotent producer code from the AMQP Annotated Message code (which should be in the GA release). However, there is a discussion tomorrow about whether idempotent producer feature should be GA'ed. Will status after discussion.
