### ISSUE TITLE
Is it possible to extract Activity Logs for  a subscription as seen in azure console using the sdk?

### ISSUE THREAD

**Issue by smoolya17** [Azure/azure-sdk-for-python#18670]
**Is your feature request related to a problem? Please describe.**
I would like to view role assignment creation and deletion activity for a stipulated time. Currently I have to login manually to the console and download logs as csv. I wish to automate this process.
**Describe the solution you'd like**
1. Login to azure console with access keys and client id.
2. Create Service Prinicipals and generate access token and request management url to list activity logs reports using a LogsManagementClient.
3. Store the listed activity logs in csv
**Describe alternatives you've considered**
Given the size of sdk I tried looking into the azure core and azure-mgmt-operations but to no avail. Can some azure expert shed light on what package can be used to extract these logs?

**Comment by nkiest** [comment]
CSV is not built directly in the python library, but should be implementable using another library. You should use https://docs.microsoft.com/en-us/python/api/azure-mgmt-monitor/azure.mgmt.monitor.v2015_04_01.operations.activitylogsoperations?view=azure-python#list-filter--select-none----kwargs- to retrieve the requested logs.

**Comment by navba-MSFT** [comment]
@smoolya17 Thanks for reaching out to us. Apologies for the delay in getting back to you. 

Could you please confirm if the pointers suggested by @nkiest helped in achieving your requirement ? 
Alternatively, you can also automate the retrieval of the Activity logs using the Powershell as explained [here](https://docs.microsoft.com/en-us/azure/azure-monitor/powershell-samples#retrieve-activity-log). Please let me know if you still have any queries on this. Awaiting your reply.

**Comment by smoolya17** [comment]
Yes it helped, you may close this issue
