### ISSUE TITLE
Client side encryption, end-to-end example?

### ISSUE THREAD

**Issue by ericthomas1** [Azure/azure-sdk-for-python#18726]
Is there an e2e example of using client side encryption? Seems like its use is [discouraged](https://github.com/Azure/azure-sdk-for-python/pull/8007#discussion_r337202685)?

**Comment by xiafu-msft** [comment]
Hi @ericthomas1 

You are right that this is not encouraged, you can use encryption scope or cpk https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L655-L664
While here is the example of client side encryption.

**Comment by ericthomas1** [comment]
Thank you for the reference, though the code comment on line 656 states `Encrypts the data on the **service-side** with the given key.` 

Are there references to the encryption being done on the **client-side**? 

**For example:**

- AWS provides [this type of guidance](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingClientSideEncryption.html) on client-side encryption

**Comment by xiafu-msft** [comment]
Hi @ericthomas1 

Sorry I didn't paste the link successfully! The link I pasted is for service side encryption which we recommend and for client side encryption you need to take this as reference https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/samples/blob_samples_client_side_encryption.py
(I also updated my previous reply)

**Comment by ericthomas1** [comment]
Thank you.
