### ISSUE TITLE
Custom Vision: CurrentIterationID property not retrieving most current iteration

### ISSUE THREAD

**Issue by cosbyr** [Azure/azure-sdk-for-python#1873]
In the Training API I am creation a project, then doing one training iteration.

When I later retrieve the project.current_iteration_id it retrieves an ID that does not belong to the most recent iteration. Does Custom Vision create a blank iteration that hasn't been trained when you first create a project?

**Comment by lmazuel** [comment]
@areddish could you help for this question please?

**Comment by areddish** [comment]
Yes, when you create a project the system will also create a blank iteration. It will have the status field == 'New' and the trained_at and domain_id fields == None. 

This iteration can be ignored and we're making changes in future releases to remove/not expose it.

**Comment by cosbyr** [comment]
@areddish Thanks for the help. Is the iteration referenced by the current_iteration_id supposed to the most recent training iteration?

**Comment by areddish** [comment]
@cosbyr It's a bit more confusing than that, it is identifying the next iteration available for training. 

So when you create a project an iteration gets created to be ready for training. That's what project.current_iteration_id is pointing at (status = "New"). When you then go and train it will train that iteration (status="Training" and eventually status="Completed). At the time you request training we also create a new iteration to be ready for the next training request and it get's exposed at project.current_iteration_id. This information is not terribly useful to the user of the SDK and so it will be going away in a future release and replaced with a way to get trained iteration(s).

**Comment by cosbyr** [comment]
@areddish Gotcha. That makes sense now.

As I've been playing with the SDK it seems like the iteration i want to use the most for any given project is the most recently trained iteration. For my particular projects the most recently trained iteration seems to always be here: trainer.get_iterations(project.id)[-2]. Second to last iteration returned by that list.

Thanks for the feedback.

**Comment by lmazuel** [comment]
Closing, since I believe the question is solved, let me know if I need to re-open it.
Thank you
