### ISSUE TITLE
Where did QueueMessageFormat go?

### ISSUE THREAD

**Issue by edtky** [Azure/azure-sdk-for-python#18744]
- **Package Name**: azure-storage-queue 
- **Package Version**: 12.1.6
- **Operating System**: Windows 10
- **Python Version**: 3.6

**Describe the bug**
I tried to use the class QueueMessageFormat using the line:
 `from azure.storage.queue.models import QueueMessageFormat`
but got the following error:
`User program failed with ModuleNotFoundError: No module named 'azure.storage.queue.models'`

if this class has been deprecated, why does the documentation not indicate that: 
https://docs.microsoft.com/en-us/python/api/azure-storage-queue/azure.storage.queue.models.queuemessageformat?view=azure-python-previous

**To Reproduce**
1. `pip install azure-storage-queue==12.1.6`
2. create a python script with the following line:
`from azure.storage.queue.models import QueueMessageFormat`
3. run the python script

**Expected behavior**
It will generate an error indicating a failure to import the module
`User program failed with ModuleNotFoundError: No module named 'azure.storage.queue.models'`

**Additional context**
What are the alternatives to this? Are there any examples?
I am currently using it as such:
`queue_service.encode_function = QueueMessageFormat.text_base64encode`

**Comment by xiafu-msft** [comment]
Hi @edtky 

Thanks for reaching out, it looks like that doc is not the proper one to look at, can you please refer to this doc https://docs.microsoft.com/en-us/python/api/azure-storage-queue/azure.storage.queue?view=azure-python
Let me know if this doesn't help!
