### ISSUE TITLE
Release Lease says Lease Id cannot be None

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-sdk-for-python#18747]
- **Package Name**: azure-storage-blob
- **Package Version**: azure-storage-blob==12.3.1
- **Operating System**: MacOS
- **Python Version**: 3.6

**Describe the bug**
Trying the simple acquiring and releasing of lease using the aio BlobLeaseClient and facing issues during release of lease,
The code shows that release of lease method `release` on the BlobLeaseClient fills in the lease id from the BlobLeaseClient object `self.id` and developer doesn't need to pass the lease_id. But when running the release method asks for lease id. If it is provided, it says 2 arguments were given for 1 positional argument

**To Reproduce**

Run the following code
```
from azure.storage.blob.aio import BlobServiceClient, BlobClient, BlobLeaseClient,ContainerClient
from azure.identity.aio import ClientSecretCredential
import os,asyncio, time

storage_uri = "{STORAGE_URI}"
tenant_id = "{TENANT_ID}"
client_id = "{CLIENT_ID}"
client_secret = "{CLIENT_SECRET}"
container_name = "test-blob-1"
storage_cred = ClientSecretCredential(tenant_id,client_id,client_secret)
blob_service_client = BlobServiceClient(storage_uri,storage_cred)
container_client : ContainerClient = blob_service_client.get_container_client(container_name)
blob_client: BlobClient = container_client.get_blob_client("priya-env-3.json")

async def main():
    lease_id = None
    blob_lease_client: BlobLeaseClient = BlobLeaseClient(blob_client)
    async with blob_lease_client,blob_client:
        await blob_lease_client.acquire(20)
        lease_id = blob_lease_client.id
        await blob_client.upload_blob("updated_blob",overwrite=True,lease=lease_id)
        await blob_lease_client.release()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

**Expected behavior**
expect blob release to happen successfully.

**Screenshots**

**Additional context**
Also if I comment out the `release` part, the blob upload happens successfully, but it complains about unclosed connection from aiohttp. Despite using context managers as shown in the code above.

**Comment by priyaananthasankar** [comment]
The problem is:

`await blob_lease_client.release()` is failing with 

`  File "/azure-blob/py36/lib/python3.6/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 1608, in release_lease
    header_parameters['x-ms-lease-id'] = self._serialize.header("lease_id", lease_id, 'str')
  File "/azure-blob/py36/lib/python3.6/site-packages/msrest/serialization.py", line 717, in header
    output = self.serialize_data(data, data_type, **kwargs)
  File "/azure-blob/py36/lib/python3.6/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
`

Not sure how to let the release know of the lease id. I was assuming it automatically picks up the lease id from the blob_lease_client

**Comment by xiafu-msft** [comment]
Hi @priyaananthasankar 
the reason is you acquired an lease on a non-existing blob which doesn't make sense. 
let me know if you need any other info!

**Comment by priyaananthasankar** [comment]
@xiafu-msft : No I acquired lease on an existing blob and it showed me the lease was acquired successfully. You can test with that code snippet.

**Comment by priyaananthasankar** [comment]
Issue resolved. Spoke to @xiafu-msft and the following is the right approach when using python context managers:
```
from azure.storage.blob.aio import BlobServiceClient, BlobClient, BlobLeaseClient,ContainerClient
from azure.identity.aio import ClientSecretCredential
import os,asyncio, time

storage_uri = "{STORAGE_URI}"
tenant_id = "{TENANT_ID}"
client_id = "{CLIENT_ID}"
client_secret = "{CLIENT_SECRET}"
container_name = "test-blob-1"
storage_cred = ClientSecretCredential(tenant_id,client_id,client_secret)
blob_service_client = BlobServiceClient(storage_uri,storage_cred)

async def main():
    lease_id = None

    # async context managers for blob_service_client and storage_credentials

    async with blob_service_client,storage_cred:
        container_client : ContainerClient = blob_service_client.get_container_client(container_name)
        blob_client: BlobClient = container_client.get_blob_client("priya-env-3.json")
        blob_lease_client = await blob_client.acquire_lease(20)
        lease_id = blob_lease_client.id
        await blob_client.upload_blob("updated_blob",overwrite=True, lease=lease_id)
        await blob_lease_client.release()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

The blob_client/container_client etc can be derived from blob_service_client. It is a recommended practice to put the parent context manager so that the __aexit__ closes all the child client connections properly when the event loop is closed.
Particularly in the case of release lease call, the __aexit__ also calls release which results in the `lease_id. missing` error. Wrapping the blob_lease_client inside the context manager helped.
