### ISSUE TITLE
How to fetch Azure App Configuration Feature Flags?

### ISSUE THREAD

**Issue by AndrewMcClelland** [Azure/azure-sdk-for-python#18756]
- **Package Name**: azure.appconfiguration
- **Package Version**: 1.1.1
- **Operating System**: Windows x64
- **Python Version**: 3.7.9

**Describe the bug**
It is unclear how to access Azure App Configuration Feature Flags using Python. I am able to fetch App Configuration settings via `get_configuration_setting()` from `AzureAppConfigurationClient` but there doesn't seem to be a documented way on how to featch feature flags. I've used feature flags in .NET and expect there to be a way to do it via Python as well.

**To Reproduce**
1. Use Python.
2. Try to access feature flags.

**Expected behavior**
Simple way to check whether a feature flag is enabled (similar to .NET).

**Comment by seankane-msft** [comment]
@AndrewMcClelland you can access the filters of a `FeatureFlagConfigurationSettings` using the `.filters` parameter. Here's a sample code snippet for working feature filters:

```python
feature_config_setting = client.get_configuration_setting("myfeatureflag")

# Access filters
for filter in feature_config_setting.filters:
    print(filter)

# Append to the filters
feature_config_setting.filters.append({... my new filter...})

# Update feature filters
client.set_configuration_setting(feature_config_setting)
```

Let me know if this solves your issue!

**Comment by AndrewMcClelland** [comment]
@seankane-msft thanks for the quick reply!

I'm looking to find out whether the feature flag is enabled. I know how to fetch the feature flag (using the unusual `get_configuration_setting(".appconfig.featureflag/FEATUREFLAGNAME")`) but it doesn't appear to have any properties that indicate whether it's enabled or not.

**Comment by seankane-msft** [comment]
@AndrewMcClelland you can use the `enabled` property to figure this out.

```python
my_feature_flag = client.get_configuration_setting(...)
print(my_feature_flag.enabled)

# You can also change the value this way
my_feature_flag.enabled = not my_feature_flag.enabled
```
