### ISSUE TITLE
[API Management] Python DSK not using all schema data

### ISSUE THREAD

**Issue by lowmann15** [Azure/azure-sdk-for-python#18788]
- **Package Name**: azure-mgmt-apimanagement
- **Package Version**: 2.0.0
- **Operating System**: windows10
- **Python Version**:  3.8

**Describe the bug**
Trying to upload an openapi.json file via the sdk to the api management results in a loss of schema information (in that particular case the "minLength" property).

**To Reproduce**
requirements.txt:
```
azure-mgmt-apimanagement==2.0.0
msrestazure==0.6.4
```
main.py:
```
import json

from azure.mgmt.apimanagement import ApiManagementClient
from azure.mgmt.apimanagement.models import ApiCreateOrUpdateParameter, ContentFormat
from msrestazure.azure_active_directory import ServicePrincipalCredentials

# variables
client_id = 'client_id'
client_secret = 'client_secret'
tenant_id = 'tenant_id'
subscription_id = 'subscription_id'
api_path = 'test_path'
rg_name = 'rg_name'
service_name = 'service_name'

azureCredentials = ServicePrincipalCredentials(client_id, client_secret, tenant=tenant_id)
apim_client = ApiManagementClient(azureCredentials, subscription_id)

with open('openapi.json') as json_file:
    swagger_spec_json = json.load(json_file)
swagger_spec = json.dumps(swagger_spec_json)

api_params = ApiCreateOrUpdateParameter(value=swagger_spec, format=ContentFormat.openapijson, path=api_path)
apim_client.api.create_or_update(rg_name, service_name, api_path, api_params)
```
openapi.json:
```
{
  "openapi": "3.0.1",
  "info": {
    "title": "TEST",
    "version": "1.0"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "TEST",
        "parameters": [
          {
            "name": "param",
            "in": "query",
            "required": true,
            "schema":{
              "type": "string",
              "minLength": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "null"
          }
        }
      }
    }
  }
}

```
1. replace variables for specific use case
2. execute main.py

**Expected behavior**
All of the properties listed under "schema" are getting deployed.

**Screenshots**
After execution in the API Management, not every schema property was deployed:
![image](https://user-images.githubusercontent.com/49783109/118629736-2bbec280-b7ce-11eb-81d4-0aa69204f34b.png)

**Comment by swathipil** [comment]
@lowmann15 Thanks for reporting this issue! Directing it to the right people.

**Comment by msyyc** [comment]
similar issue : https://github.com/Azure/azure-sdk-for-python/issues/16984

**Comment by msyyc** [comment]
The problem is caused by the difference between track1(version < 1.0.0b1) and track2(version >= 1.0.0b1). Track1 is deprecated 
 and new content will be only published with track2. Please follow the guidance of https://github.com/Azure/azure-sdk-for-python/issues/16984 to complete migration
