### ISSUE TITLE
Getting test setup on the live tests pipeline for Blobs

### ISSUE THREAD

**Issue by tasherif-msft** [Azure/azure-sdk-for-python#18796]
We recently encountered `test setup failures` in our live tests pipeline while attempting to create required resources. 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=900632&view=ms.vss-test-web.build-test-results-tab&runId=19377790&resultId=100815&paneView=debug

**Comment by scbedd** [comment]
@benbp have you seen an error like this before?

**Comment by benbp** [comment]
@scbedd this issue is from last May, do we still even provision storage resources via the test preparer anymore? My guess would be bad test parallelization or resource scoping.

**Comment by benbp** [comment]
It's also possible the group was tagged improperly, as was a frequent issue with the old python preparers, and it was deleted during a cleanup sweep.

**Comment by scbedd** [comment]
Definitely haven't seen this for a while. Closing.
