### ISSUE TITLE
hardcoded API version in azure/mgmt/sql/operations/_databases_operations.py does not work for all sovereign clouds

### ISSUE THREAD

**Issue by eeertel** [Azure/azure-sdk-for-python#18809]
- **azure-mgmt-sql**: 
- **2.0.0**: 
- **Ubuntu 18.04.5 LTS**:
- **3.6.9**: 

**Describe the bug**
The api_version variable on line 322 in azure/mgmt/sql/operations/_databases_operations.py is hardcoded to "2021-02-01-preview".
The AzureChinaCloud does not support this api version (see error message below):

```
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'chinaeast' and API version '2021-02-01-preview' for type 'servers/databases'. The supported api-versions are '2014-04-01, 2014-04-01-preview, 2015-01-01, 2015-05-01-preview, 2017-03-01-preview, 2017-10-01-preview, 2018-06-01-preview, 2019-06-01-preview, 2020-02-02-preview, 2020-08-01-preview, 2020-11-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2
```

**To Reproduce**
1. Execute the sql_client.databases.get command for a database in the AzureChinaCloud

**Expected behavior**
It shall be possible to specify the api version when executing the sql_client.databases.get command

**Screenshots**
n.a.

**Additional context**
n.a.

**Comment by swathipil** [comment]
@eeertel Thanks for the feedback! Routing this to the right people.
