### ISSUE TITLE
Recording Doesn't Work When Download the Stream body

### ISSUE THREAD

**Issue by xiafu-msft** [Azure/azure-sdk-for-python#18817]
If we turn on recording for async calls, the response body which is a stream will be loaded first, which means after we record the service returned stream is consumed, so when we want to consume the stream it becomes empty.

Here are some options to help us fix the async problem:
1. Make some changes to the async recording code:  wrap the recorded content in a new stream to pretend the consumer is reading from the service returned stream if the test is running in playback mode or recording mode, I guess @seankane-msft probably can help
2. Make changes to _aiohttp.py in azure-core so that users can opt in getting raw response body or decompressed response body. This would help because currently storage sdk is calling AioHttpTransportResponse.load_body() to get response body all the time. The reason we load the body into memory is: for client side encrypted blob, we have to load the whole chunk into memory to decrypt. Our default download blob chunk size is 4MB, which means only 4MB is loaded into memory at a time in a single thread, while this option would cause problem if user specify a larger chunk size. (for this one @xiangyan99 has more context)
3. We can wait for Mockup server feature to complete, while we are not sure if the Mockup server can support this

Also if we turn on recording for sync calls, the recording is always trying to decompress the content no matter if we want to get raw content or not. This is because the recording happens before calling stream_download(), and stream_download() is where we can control decompress or not in live mode test.

**Comment by scbedd** [comment]
@xiafu-msft This indicates that any async test that deals with streams this will occur. Do you have a suggested to that we be fixing this against?

**Comment by xiafu-msft** [comment]
Hi @scbedd 

We don't have existing test that encounters this problem, while we can push a branch, and by pulling that branch you can reproduce that in pytest. Let me know if you need that branch!

**Comment by scbedd** [comment]
@xiafu-msft please do! Examples are awesome to work 👍

**Comment by xiafu-msft** [comment]
Hi @scbedd 

Here is the branch you can check out https://github.com/Azure/azure-sdk-for-python/pull/19405/files

I added some comments so you can find where to test obviously. Let me know if you need any other info!

**Comment by annatisch** [comment]
Hi @scbedd - do we have an updated status on this one?

The tests are blocking us from shipping a rather important bug fix, so it would be good to get a sense for what the timeline to resolve this might look like.

**Comment by lmazuel** [comment]
Confirmed solved ;)
