### ISSUE TITLE
Provide samples for the async storage sdk

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#18853]
**Is your feature request related to a problem? Please describe.**
The Azure storage sdk lacks samples to illustrate the use of the async functionalities of the sdk. Even thought not drastically different from its sync counterpart, it would be helpful to have some sample covering the basics.

**Describe the solution you'd like**
A set of samples using the async sdk should be provided.

**Comment by swathipil** [comment]
@andrea-cassioli-maersk Thanks for your feedback! Directing this to the right people.

**Comment by tasherif-msft** [comment]
Hi @andrea-cassioli-maersk we do have samples for async, is there anything specific that you feel should be there?

Thank you :)

**Comment by andrea-cassioli-maersk** [comment]
Hi @tasherif-msft , you are definitely right! Please ignore my request, I am not sure which folder/branch I was looking at...
