### ISSUE TITLE
The Python SDK passing parameters to adf pipeline does not work

### ISSUE THREAD

**Issue by v-junyuwang** [Azure/azure-sdk-for-python#18873]
Hello! I met a problem using python SDK to trigger ADF pipeline. I tried to pass my pipeline parameters in my function, but it seems that the pipeline did not receive my parameters. Could you please help me to see what is the problem? Sorry for any inconvenience that I caused and thank you very much!

Here are my codes:

I tried to call "Real_Time_Incident_SR_Pair" pipeline and set the "EndTime" be "test". The pipeline was trigger properly, but it was still run with my default "EndTime" value, which is "12123".

**Comment by xiangyan99** [comment]
Thanks for reaching out. Could you tell us which library did you use?

**Comment by v-junyuwang** [comment]
Thank you for your reply. Here are the libraries that I used.

from azure.mgmt.datafactory import DataFactoryManagementClient

from azure.identity import ClientSecretCredential

**Comment by xiangyan99** [comment]
Thank you for the information. We will investigate ASAP.

**Comment by shawnxzq** [comment]
@xiangyan99 Looks like service team (ADF) can't do anything for this, could you please remove the service attention tag? Thanks!

**Comment by xiangyan99** [comment]
@shawnxzq could you give me more details why ADF team cannot do anything? Do you know who can help?

**Comment by shawnxzq** [comment]
@xiangyan99 You marked this as bug, I understand you identified the bug from SDK team wise, right? If this is the case, ADF don't need to do anything to fix it. Please let me know how ADF can fix it if it is not the case.

**Comment by xiangyan99** [comment]
@shawnxzq yes. This is an SDK bug. If I understand correctly, this SDK was generated by the swagger. So maybe we need to take a look into the swagger.

Loop in @00Kai0 who generated the code.

**Comment by shawnxzq** [comment]
@xiangyan99  @00Kai0  Please let us know if we need to change the swagger, for now, I would suggest we remove the service attention tag since we don't know whether swagger needs changes or not and ADF team can't make any progress on this at moment, thanks!

**Comment by shawnxzq** [comment]
@xiangyan99 Could you please remove service tag for this issue as it's a SDK bug, and ADF team can't do anything to fix this at moment, thanks!

**Comment by xiangyan99** [comment]
@msyyc @00Kai0 Please confirm if you can fix it w/o changing swaggers.

@shawnxzq FYI. msyyc and 00Kai0 are working on mgmt SDK.
