### ISSUE TITLE
Python example invalid

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-sdk-for-python#18877]
The main example on the Python part of the web apps API is invalid. It references the function `create_or_update`. The API is now `begin_create_or_update()`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fde884e-90df-4cb8-9735-06f320183942
* Version Independent ID: 7ba47766-7dc5-e08f-ea98-bef233ef6f2c
* Content: [Azure Web Apps libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/webapps?view=azure-python)
* Content Source: [docs-ref-services/latest/webapps.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/webapps.md)
* Service: **appservice**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @lisawong19
* Microsoft Alias: **routlaw**

**Comment by swathipil** [comment]
@tonybaloney Thanks for reporting this! Directing this to the right people.

**Comment by msyyc** [comment]
@tonybaloney 
(1)Thank you for your feedback. when version is smaller than 1.0.0b1, it is track1 package; When version is larger than 1.0.0b1, it is track2 package. The difference is declared in https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/appservice/azure-mgmt-web/CHANGELOG.md#100b1-2020-10-13. Track1 package will be deprecated in the short future.
(2)https://docs.microsoft.com/en-us/python/api/overview/azure/webapps?view=azure-python is wrote for track1 package and we will update it later for track2 pakcage.
