### ISSUE TITLE
HDInsight ID broker feature not available

### ISSUE THREAD

**Issue by userimack** [Azure/azure-sdk-for-python#18909]
We are trying to enable HDInsight Idbroker for our cluster. The option to enable it is available in the ARM template as **isHibEnabled** key under securityProfile.

```     
 "securityProfile": {
          .....
          "isHibEnabled": true,
            ....
   }
```

But we are unable to find the corresponding option in the sdk. Any suggestions?

**Comment by swathipil** [comment]
@userimack Thanks for your question! Directing this to the right people now.

**Comment by msyyc** [comment]
What is the package name that you want to use?

**Comment by userimack** [comment]
We are using the following package: `azure-mgmt-hdinsight==7.0.0`

**Comment by aim-for-better** [comment]
so this is the python sdk?

**Comment by userimack** [comment]
yes, please let me know if you need more info

**Comment by aim-for-better** [comment]
Firstly, Azure HDInsight ID Broker(HIB) feature only is available for ESP cluster.
For SDK customer need to construct the ComputeProfile which contains a idbrokernode manaually.
```
    ....
  # construct the Roles
    workernode= Role(...)
    headnode=Role(...)
    zookeepernode=Role(...)
     idbrokernode =Role(
      name="idbrokernode",
      target_instance_count=2,
      virtual_network_profile=virtual_network_profile
  )
  roles=[workernode, headnode, zookeepernode, idbrokernode]
  
# construct the cluster create parameters, here omit other properties
 create_params = ClusterCreateParametersExtended(
       ...
        properties=ClusterCreateProperties(
          ...
            compute_profile=ComputeProfile(
                roles=roles
            )
           ...
        )
    )

# then call the client to create cluster
client.begin_create(resource_group_name, cluster_name, create_params)
```

**Comment by userimack** [comment]
We have already added the compute profile for id broker but we were unable to validate it as we are running into issues with logging in to ambari UI portal.

**Comment by aim-for-better** [comment]
> We have already added the compute profile for id broker but we were unable to validate it as we are running into issues with logging in to ambari UI portal.

Hi @userimack  it seems it is a different problem. It is not related with SDK.
Could you please confirm that whether the sdk question has been answered?

**Comment by userimack** [comment]
As I mentioned earlier we are using similar config but due to Ambari login issue I am unable to confirm, btw while using the ARM template and similar type of config in the template we are not running into any kind of Amabri issue, hope this info might help in debugging. 

Sample ARM template: https://github.com/Azure/azure-quickstart-templates/blob/master/101-hdinsight-linux-with-edge-node/azuredeploy.json

**Comment by aim-for-better** [comment]
> As I mentioned earlier we are using similar config but due to Ambari login issue I am unable to confirm, btw while using the ARM template and similar type of config in the template we are not running into any kind of Amabri issue, hope this info might help in debugging.
> 
> Sample ARM template: https://github.com/Azure/azure-quickstart-templates/blob/master/101-hdinsight-linux-with-edge-node/azuredeploy.json

does the ambari login issue mean the cluster can not be created successfully?

**Comment by aim-for-better** [comment]
Hi @userimack could you please update the progress? Has the issue been fixed?

**Comment by userimack** [comment]
Hi @aim-for-better, the ambari login issue seems to be not occurring and with the same configuration we are able to create a cluster and it works fine. Thanks for the help :)
