### ISSUE TITLE
Bad body serialization creating a Schedule Trigger in Data Factory

### ISSUE THREAD

**Issue by csotomon** [Azure/azure-sdk-for-python#18905]
- **Package Name**: azure-mgmt-datafactory
- **Package Version**: 1.1.0
- **Operating System**: Windows
- **Python Version**: 3.8

**Describe the bug**
Using the library to create a Data Factory trigger, calling DataFactoryManagementClient.triggers.create_or_update method is not serializing the request body correctly

Serialized example:
```json
{
    "type": "ScheduleTrigger",
    "description": "My scheduler trigger",
    "pipelines": [
        {
            "pipelineReference": {
                "type": "PipelineReference",
                "referenceName": "PL_ADW_IMPORT_MASTER"
            },
            "parameters": {
                "datacenter_name": "datacenter1",
                "schedule_name": "schedule1"
            }
        }
    ],
    "typeProperties": {
        "recurrence": {
            "frequency": "Minute",
            "interval": 15,
            "startTime": "2022-12-12T04:00:00.000Z",
            "endTime": "2022-12-12T05:00:00.000Z",
            "timeZone": "UTC"
        }
    }
}
```
The correct serealized body is:
```json
{
    "properties": {
        "type": "ScheduleTrigger",
        "description": "My scheduler trigger",
        "pipelines": [
            {
                "pipelineReference": {
                    "type": "PipelineReference",
                    "referenceName": "PL_ADW_IMPORT_MASTER"
                },
                "parameters": {
                    "datacenter_name": "datacenter1",
                    "schedule_name": "schedule1"
                }
            }
        ],
        "typeProperties": {
            "recurrence": {
                "frequency": "Minute",
                "interval": 15,
                "startTime": "2022-12-12T04:00:00.000Z",
                "endTime": "2022-12-12T05:00:00.000Z",
                "timeZone": "UTC"
            }
        }
    }
}
```

**To Reproduce**
```python
from azure.identity import DefaultAzureCredential 
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.datafactory import DataFactoryManagementClient
from azure.mgmt.datafactory.models import *



def main():
    credential = DefaultAzureCredential()
    adf_client = DataFactoryManagementClient(credential, 'AAAAA-VVVV-SWESDDS-XCV3-3bb145207'
   
    # Create a trigger
    rg_name = 'EUNPADWCANRSG01'
    df_name = 'EUNPADWCANDFA01'
    tr_name = 'mytrigger'
    scheduler_recurrence = ScheduleTriggerRecurrence(frequency='Minute', interval='15',start_time='2022-12-12T04:00:00Z', end_time='2022-12-12T05:00:00Z', time_zone='UTC')
    pipeline_parameters = {'datacenter_name':'datacenter1', 'schedule_name':'schedule1'}
    pipelines_to_run = []
    pipeline_reference = PipelineReference(reference_name='PL_ADW_IMPORT_MASTER')
    pipelines_to_run.append(TriggerPipelineReference(pipeline_reference=pipeline_reference, parameters=pipeline_parameters))
    tr_properties = ScheduleTrigger(description='My scheduler trigger', pipelines = pipelines_to_run, recurrence=scheduler_recurrence)    
    adf_client.triggers.create_or_update(rg_name, df_name, tr_name, tr_properties)

    # Start the trigger
    adf_client.triggers.start(rg_name, df_name, tr_name)

if __name__ == "__main__":
    main()
```

**Expected behavior**
Running this code, 

[\azure\mgmt\datafactory\operations\_triggers_operations.py ](https://github.com/Azure/azure-sdk-for-python/blob/7c4cfe236d113c59e66515b6315def256219aa6b/sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_triggers_operations.py#L254) trigger an Exception because the response status code is 400

**Screenshots**

**Additional context**

**Comment by swathipil** [comment]
@csotomon Thanks for your report! Directing this to the right people.

**Comment by msyyc** [comment]
According to https://github.com/Azure/azure-sdk-for-python/blob/7c4cfe236d113c59e66515b6315def256219aa6b/sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_triggers_operations.py#L192-L200,

You should use 'TriggerResource' instead of 'ScheduleTrigger'.

**Comment by csotomon** [comment]
> According to
> 
> https://github.com/Azure/azure-sdk-for-python/blob/7c4cfe236d113c59e66515b6315def256219aa6b/sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_triggers_operations.py#L192-L200
> 
> ,
> You should use 'TriggerResource' instead of 'ScheduleTrigger'.

I am following the example in [https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger#python-sdk](https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger#python-sdk). That example creas an object from ScheduleTrigger class. What’s the correct way?

**Comment by msyyc** [comment]
according to the python package code, it should be ` tr_properties = TriggerResource(description='My scheduler trigger', pipelines = pipelines_to_run, recurrence=scheduler_recurrence)` instead of `tr_properties = ScheduleTrigger(description='My scheduler trigger', pipelines = pipelines_to_run, recurrence=scheduler_recurrence)`

**Comment by csotomon** [comment]
I think that you should update the Documentation or fix the code

**Comment by csotomon** [comment]
Using TriggerResource class instead of ScheduleTrigger, i got this error
`tr_properties = TriggerResource(
TypeError: __init__() missing 1 required keyword-only argument: 'properties'`

**Comment by shawnxzq** [comment]
@lrtoyou1223 Looks like the document for trigger in Python doesn't work as expected, could you please help have a look at this? Thanks!

@csotomon  We will check this and update here later, thanks for your patience.

**Comment by shawnxzq** [comment]
@chez-charlie could you please help on this? It's about creating trigger using python SDK following the doc below, thanks!

 https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger#python-sdk

@csotomon I tagged the wrong owner before, sorry for that.

**Comment by csotomon** [comment]
@shawnxzq and @chez-charlie how can I help you?

**Comment by shawnxzq** [comment]
@chez-charlie any update on this? Thanks a lot!

**Comment by kazrael2119** [comment]
Hi @csotomon ,you can try to use 
```    
tr_properties = TriggerResource(properties=ScheduleTrigger(description='My schedulertrigger',pipelines=pipelines_to_run,recurrence=scheduler_recurrence))
``` 
instead of
```
tr_properties = TriggerResource(description='My scheduler trigger', pipelines = pipelines_to_run, recurrence=scheduler_recurrence)
```

**Comment by ahuja-himanshu** [comment]
> Hi @csotomon ,you can try to use
> 
> ```
> tr_properties = TriggerResource(properties=ScheduleTrigger(description='My schedulertrigger',pipelines=pipelines_to_run,recurrence=scheduler_recurrence))
> ```
> 
> instead of
> 
> ```
> tr_properties = TriggerResource(description='My scheduler trigger', pipelines = pipelines_to_run, recurrence=scheduler_recurrence)
> ```

This is throwing `ValueError: Unknown type of azure resource: TriggerResource`, I've imported TriggerResource from `azure.mgmt.datafactory.models`
