### ISSUE TITLE
Be able to get etags with queries

### ISSUE THREAD

**Issue by JJ11teen** [Azure/azure-sdk-for-python#18918]
Hey team,

I'm looking to be able to query and/or list entities in Azure Table storage, and get back their etags in the response. It doesn't look like this is currently supported, as the `azure-data-tables` library [hardcodes the 'Accept' request header](https://github.com/Azure/azure-sdk-for-python/blob/525fb2aaf31754090fdf4e4e368721b6f60b3ca6/sdk/tables/azure-data-tables/azure/data/tables/_generated/operations/_table_operations.py#L84) to "application/json;odata=minimalmetadata", and as per the [documentation here](https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities) it needs to be "application/json;odata=fullmetadata" to get etags.

I think ideally this makes sense as some sort of optional `ODataMetadata` enum surfaced on the `list_entities` and `query_entities` methods? 

Workarounds:
1. Make a seperate get_entity call to get the etag (not great for performance in my scenario)
2. Craft the query manually using internal methods (AzureTable)

Thanks,
Lucas

**Comment by annatisch** [comment]
Thanks @JJ11teen!
Actually the etag is returned with MinimalMetadata as the setting. You should be able to find it in the `metadata` dictionary property on each returned entity:
```python
entities = table.list_entities()
for e in entities:
    print(e.metadata['etag']
```
Please let me know if this isn't working so we can dig deeper!

We haven't yet found a need to expose the metadata-level in the API... as we currently have not found any specific benefits that this provides, however if customers need it, it's still possible to set using a `headers` parameter - something like this:
```python
entities = table.list_entities(headers={'accept': 'application/json;odata=fullmetadata'}
```
This should overwrite the generated default.
If we get a concrete scenario for which being able to select the metadata setting is useful/necessary - we will certainly surface that to the API.

Please let us know if you have thoughts or questions! :)

**Comment by JJ11teen** [comment]
Ah don't know how I missed that, thanks @annatisch!
Etag is all I'm interested in, so I guess no concrete use case of selecting the metadata setting from me :)
