### ISSUE TITLE
Network interface cannot be modified by user Code: CannotModifyNicAttachedToPrivateEndpoint

### ISSUE THREAD

**Issue by kranthi91** [Azure/azure-sdk-for-python#18911]
- **Package Name**: azure-mgmt-network  

- **Package Version**: 16.0.0
- **Operating System**: Ubuntu 18.04 
- **Python Version**: 3.6.9

**Describe the bug**
Getting the error _Code: CannotModifyNicAttachedToPrivateEndpoint_ when trying to update NIC card configuration using 
_NetworkManagementClient_. 
_Message: Network interface /subscriptions/xxxxxxxxxxxxxxxxxx-subscription/resourceGroups/xxxxxxxxxxxx-resource-group/providers/Microsoft.Network/networkInterfaces/xxxxx-nicname is linked to a private endpoint /subscriptions/xxxxxxxxxxxxxxxxxx-subscription/resourceGroups/xxxxxxxxxxxx-resource-group/providers/Microsoft.Network/privateEndpoints/private-endpoint-xxxx. It can not be modified by user._
**To Reproduce**
1. List all public IP addresses available using    ` ip_list = network_client.public_ip_addresses.list(group.name)`
2. Iterating through each ip in the list, obtain network interface name and corresponding ip configuration names,
3. Using the above two NIC name and IP_CONFIG names, call `NetworkManagementClient..network_interfaces.begin_create_or_update(group.name, nic.name, {"ip_configurations": [{"name": nic_configuration_name, "public_ip_address": None}], "location": ip.location}).result()`

**Expected behavior**
It should update the ip configuration of the corresponding NIC card of the iterated IP address to None.
**Screenshots**

**Additional context**
The actual goal of the code is disassociate the public IP address from the NIC card by setting public_ip_address to None.

**Comment by swathipil** [comment]
@kranthi91 Thanks for your report! Directing this to the right people.

**Comment by msyyc** [comment]
Hi @service team, according to the description, it seems that service does not support this kind of usage. Could you help to explain the scenario?

**Comment by kranthi91** [comment]
`from azure.identity import AzureCliCredential
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.network import NetworkManagementClient
import os, re

# Acquire a credential object using CLI-based authentication.
credential = AzureCliCredential()

# Retrieve subscription ID from environment variable.
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
# print(subscription_id)

# Obtain the management object for resources.
resource_client = ResourceManagementClient(credential, subscription_id)
network_client = NetworkManagementClient( credential, subscription_id )
# Retrieve the list of resource groups
group_list = resource_client.resource_groups.list()

# Show the groups in formatted output
column_width = 40

print("Resource Group".ljust(30) + "Location" + "IP Name".rjust(30) +  "Nic Name".rjust(30)+"To be Deleted".rjust(30) +  "Is deleted".rjust(10))
print("-" * (column_width * 4))

for group in list(group_list):
    # print(f"{group.name:<{column_width}}{group.location}")

    ip_list = []
    nic_list = network_client.network_interfaces.list(group.name)

    for nic in nic_list:
        # Dissasciate public ip address by setting to None.
        params = {'location': nic.location,
                  'ip_configurations': [ { 'name': nic.ip_configurations[0].name, 'public_ip_address': None}] }
        # print(params)
        # network_client.network_interfaces.begin_create_or_update(group.name,nic.name, parameters=params)
        # print(nic.ip_configurations)

    ip_list = network_client.public_ip_addresses.list(group.name)

    # print(ip_list)
    for ip in ip_list:
        # attributes = dir(ip)
        result = False
        search_string = ip.ip_configuration.id
        print(search_string)
        pattern = "(networkInterfaces)(/)([a-zA-B0-9-]+)(/)(ipConfigurations)(/)([a-zA-B0-9-]+)"
        p = re.compile(pattern)
        match = p.findall(search_string) # Find all return a list

        if match:

            # print(nic_name)
            try:
                nic_name = match[0][2]
                nic_configuration_name = match[0][6]
                params = {'location': ip.location,
                          'ip_configurations': [{'name': nic_configuration_name, 'public_ip_address': None}]}
                # print(params)
                result =  network_client.network_interfaces.begin_create_or_update(group.name, nic.name, {"ip_configurations": [{"name": nic_configuration_name, "public_ip_address": None}], "location": ip.location}).result()
                print(f"{group.name:<{30}} {group.location} {ip.name:>{30}} {nic_name[0][2]:>{30}} {ip.tags['delete']:>{20}} {str(result):>{20}}")
            except Exception as e:
                print("Exception while updating nic {} from ip address {} error {}".format(nic_name, ip.name, str(e)))`

**Comment by kranthi91** [comment]
`from azure.identity import AzureCliCredential
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.network import NetworkManagementClient
import os, re


credential = AzureCliCredential()


subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]



resource_client = ResourceManagementClient(credential, subscription_id)
network_client = NetworkManagementClient( credential, subscription_id )

group_list = resource_client.resource_groups.list()


column_width = 40

print("Resource Group".ljust(30) + "Location" + "IP Name".rjust(30) +  "Nic Name".rjust(30)+"To be Deleted".rjust(30) +  "Is deleted".rjust(10))
print("-" * (column_width * 4))

for group in list(group_list):


    ip_list = []
    nic_list = network_client.network_interfaces.list(group.name)

    for nic in nic_list:

        params = {'location': nic.location,
                  'ip_configurations': [ { 'name': nic.ip_configurations[0].name, 'public_ip_address': None}] }

    ip_list = network_client.public_ip_addresses.list(group.name)


    for ip in ip_list:

        result = False
        search_string = ip.ip_configuration.id
        print(search_string)
        pattern = "(networkInterfaces)(/)([a-zA-B0-9-]+)(/)(ipConfigurations)(/)([a-zA-B0-9-]+)"
        p = re.compile(pattern)
        match = p.findall(search_string) # Find all return a list

        if match:


            try:
                nic_name = match[0][2]
                nic_configuration_name = match[0][6]
                params = {'location': ip.location,
                          'ip_configurations': [{'name': nic_configuration_name, 'public_ip_address': None}]}

                result =  network_client.network_interfaces.begin_create_or_update(group.name, nic.name, {"ip_configurations": [{"name": nic_configuration_name, "public_ip_address": None}], "location": ip.location}).result()
                print(f"{group.name:<{30}} {group.location} {ip.name:>{30}} {nic_name[0][2]:>{30}} {ip.tags['delete']:>{20}} {str(result):>{20}}")
            except Exception as e:
                print("Exception while updating nic {} from ip address {} error {}".format(nic_name, ip.name, str(e)))`

**Comment by kranthi91** [comment]
Please refer to the above code snippet used when this error was obtained.
