### ISSUE TITLE
azure-mgmt-costmanagement CostManagementClient ignores nextLink for usage

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#18927]
- **Package Name**: azure-mgmt-costmanagement
- **Package Version**: 1.0.0
- **Operating System**: Linux
- **Python Version**: 3.7.3

**Describe the bug**
When I invoke CostManagementClient.query.usage() for a query with a lot of results, such as all resource groups or resource IDs for a whole billing month, I get an incomplete result. The SDK ignores nextLink in the result and returns only the first page. Working around this is tricky, because usage() does not accept a next_link or skiptoken argument. I ended up doing something super-hacky: I pass skiptoken as a kwarg to usage() anyway, and when I create the client I add a custom hook to the pipeline that pops skiptoken out of request.context.options and then rewrites request.http_request.url to include the skiptoken. (FWIW, I was rewriting the URL anyway to work around https://github.com/Azure/azure-sdk-for-python/issues/17351)

Examples elided to avoid exposing PII.

**Comment by swathipil** [comment]
@jazelenk Thanks for your report! Directing this to the right people.

**Comment by lmazuel** [comment]
It's a Swagger feedback, that don't define the operation as pageable. Tagging service team to fix it.

**Comment by olsaal-msft** [comment]
This is not a service issue - this is an SDK update. The customer usage via the SDK/CLI should allow the customer to use the nextLink provided in the first page returned via powershell. Currently there is no parameter support in the CLI to specify the nextLink parameter. 

![image](https://user-images.githubusercontent.com/39535901/125501249-4f437415-1b5c-4d5c-b6a7-b5292a5cf5b7.png)

**Comment by ShilpiGautam** [comment]
Removed Service label as this is an SDK issue based on comment above and not a service issue. Pls route it to the SDK team

**Comment by lmazuel** [comment]
@olsaal-msft @ShilpiGautam I'm sorry but this is a Swagger definition issue, that should define the `x-ms-pagable` annotation. `nextLink` is NOT a public parameter in SDK, this is a hiden one based on the `x-ms-pagable` definition in the Swagger. Since the Swagger authoring is owned by service team, please fix the Swagger and add the correct `x-ms-pagable` annotation when needed. When Swagger is fixed, please do a release request following the API OpenAPI portal to ship the updated mgmt SDK.

**Comment by jbvsmo** [comment]
Any news on this bug report?

**Comment by swathipil** [comment]
Hey @ShilpiGautam @olsaal-msft,
Would you be able to take a look at the response @lmazuel posted above + respond with any thoughts/updates?
Thanks!

**Comment by omrodrig** [comment]
I apologize for the inconvenience. Upon further investigation, the API contract and corresponding Swagger do not integrate with the SDK in such a way to allow automatic pagination. We will add this API contract change as a work item into our backlog.
