### ISSUE TITLE
Azure Functions PYPI page is displaying incorrectly

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk-for-python#18920]
This PYPI page for azure-functions doesn't look right. The build status and Python version for runtime tables don't look accurate. 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/41597107/119529551-0fbfa180-bd37-11eb-8424-79ce196b7026.png)

**Comment by swathipil** [comment]
@diberry Thanks for your feedback! Directing this to the correct people.

**Comment by lmazuel** [comment]
Issue moved to [Azure/azure-functions-python-worker #930](https://github.com/Azure/azure-functions-python-worker/issues/930) via [**ZenHub**](https://www.zenhub.com/)
