### ISSUE TITLE
Varying spelling of CBLMariner and CBL_MARINER

### ISSUE THREAD

**Issue by jasonzio** [Azure/azure-sdk-for-python#18937]
[Enter feedback here]
The description says "Choose from Ubuntu(default) and CBLMariner" but the Fields section puts an underscore in "CBL_MARINER". Which one is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad81933e-ca88-2812-2b42-9a6d3e056b3a
* Version Independent ID: 85619822-4d4a-d65e-1174-11de7f6b0291
* Content: [azure.mgmt.containerservice.v2021_03_01.models.OSSKU enum](https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerservice/azure.mgmt.containerservice.v2021_03_01.models.ossku?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-containerservice/azure.mgmt.containerservice.v2021_03_01.models.OSSKU.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-containerservice/azure.mgmt.containerservice.v2021_03_01.models.OSSKU.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by swathipil** [comment]
@jasonzio Thanks for your question! Routing it to the right people to get it answered.
