### ISSUE TITLE
Update Tracing instructions to highlight AppInsights (or OpenCensus for Python)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#18960]
Tracking issue for completing the testing of AppInsights with Track2 SDKs (Blob Storage, Event Hubs, Cosmos) and then updating the repo's tracing instructions / samples to make AppInsights more prominent in the documentation and making it clear that the beta Monitor OpenElemetry Exporter is a secondary option.

**Comment by joshfree** [comment]
Reconfirmed with Monitor team that the OpenCensus SDK for Python (here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python) is the only supported option for python to date.

We should update our readme guidance, quick starts, and samples to highlight this supported option.

**Comment by rakshith91** [comment]
Added a wiki here https://github.com/Azure/azure-sdk-for-python/wiki/Telemetry-with-Azure-SDKs

**Comment by joshfree** [comment]
@lmolkova could you give the instructions a quick review

@rakshith91 are we going to add links to the new wiki entry from the repo's READMEs?

**Comment by lmolkova** [comment]
thanks, wiki page looks great! it seems it's the same as [readme on opencensus plugin](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core-tracing-opencensus#examples), do we want to keep both of them?
