### ISSUE TITLE
InteractiveBrowserCredential fails when using a personal/MSA account without passing tenant_id

### ISSUE THREAD

**Issue by vxfield** [Azure/azure-sdk-for-python#18975]
- **Package Name**: azure-identity
- **Package Version**: 1.6.0
- **Operating System**: MacOS
- **Python Version**: 3.7.4

**Describe the bug**
When using `InteractiveBrowserCredential` with a personal/MSA account without passing the user's TenantId, the interactive authentication fails with message:

```
User account 'email@outlook.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '04b07795-8ddb-461a-bbee-02f9e1bf7b46'(Microsoft Azure CLI) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
```

**To Reproduce**
1) Use the `InteractiveBrowserCredential` with any Azure SDK client that accepts it, without passing the `tenant_id`.
2) Attempt to **login using a personal/MSA account**
     When the browser authentication opens a new `https://login.microsoftonline.com/` web page, try to login with a **personal/MSA** account such as `email@outlook.com`. A work/school account should authenticate just fine.
     In the case of a personal/MSA account you should see the error message described above.

**Expected behavior**
We should spare the user from passing their personal account tenant id and had a seamless experience as found with `az login`.

**Workarounds**
**Option 1: Use the DefaultAzureCredential and pass the tenant_id via environment variable**
a) Find your account `tenant_id`: [How to find your Azure Active Directory tenant ID](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant)
b) Before running the Python program, set the `AZURE_TENANT_ID` environment variable with your `tenant_id` value.
PowerShell example:
```powershell
$env:AZURE_TENANT_ID = "your tenant id"
```

**Option 2: Pass the tenant_id via the InteractiveBrowserCredential**
a) Find your account `tenant_id`: [How to find your Azure Active Directory tenant ID](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant)
b) Pass your `tenant_id` as part of the `InteractiveBrowserCredential` [constructor](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.interactivebrowsercredential?view=azure-python):
```python
from azure.identity import InteractiveBrowserCredential

credential = InteractiveBrowserCredential(tenant_id="your tenant id")
```

**Related issues**
- azure-quantum: https://github.com/microsoft/qdk-python/issues/66

**Comment by chlowell** [comment]
To summarize offline investigation, Azure Quantum's authentication scope doesn't support pass-through, which is required to authenticate MSAs. So, I'm closing this issue because the SDK can't fix that (but Quantum will, so it won't be a problem long term).
