### ISSUE TITLE
Re-enable pylint on `azure-eventhub` 

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#18986]
`azure-servicebus` was added to the set of packages that we allow pylint failures on [in this PR](https://github.com/Azure/azure-sdk-for-python/pull/18945/files).

Given that the package is track2, we probably want to re-enable it and fix the pylint at some point. Filing this issue to ensure this isn't lost.

**Comment by xiangyan99** [comment]
Thank you Scott.

**Comment by xiangyan99** [comment]
Sorry. I thought it was fixed in [eventhub] ci fix #18945 :)

**Comment by swathipil** [comment]
I believe this should be re-enable pylint on `azure-eventhub`? https://github.com/Azure/azure-sdk-for-python/blob/eb96378c6b096b222c7bd68e769a17cf79779de5/eng/tox/allowed_pylint_failures.py#L62
