### ISSUE TITLE
Duplicated azure-mgmt-servicebus tabs in TOC

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#18984]
There are duplicate azure-mgmt-servicebus tabs in the TOC and the second tab has a package link that just links back to the overview page of the first tab. 

![image](https://user-images.githubusercontent.com/25314976/119866880-1f272200-bed2-11eb-90dd-d23288dbe33b.png)

The servicebus package link here just links to overview page of first azure-mgmt-servicebus tabs 
![image](https://user-images.githubusercontent.com/25314976/119866943-32d28880-bed2-11eb-919f-f9035f8ca7f5.png)

![image](https://user-images.githubusercontent.com/25314976/119867054-4e3d9380-bed2-11eb-9eaa-ea4b0e1d2f59.png)

The other libraries (like Cosmos, Storage) don't seem to have this problem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4ffb554-5cff-1aae-3fa2-938a0b52c933
* Version Independent ID: bc812028-9649-35ef-65a0-f18056578341
* Content: [azure-mgmt-servicebus package](https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicebus/?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-servicebus/index.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-servicebus/index.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by lilyjma** [comment]
@scbedd - curious if you know why

**Comment by scbedd** [comment]
@lilyjma Nothing sticks out in the [toc that powers this](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/90ce3281807bdd8bbb191b66eaaca1a19f739c26/docs-ref-mapping/reference.yml#L783)

I checked into the ci config and [resolved the issue in this PR](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1364)

Thanks for the catch! Will be fixed on next live deployment.

**Comment by scbedd** [comment]
[Confirmed fix](https://review.docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python&branch=master) in `master`. 

![image](https://user-images.githubusercontent.com/45376673/119897821-d5e8c980-bef5-11eb-9af5-45b18af2b56f.png)

Closing this issue as it'll go out on our next python docs release.
