### ISSUE TITLE
Multivariate Anomaly Detection Model fails during the training part no matter what

### ISSUE THREAD

**Issue by LW0214** [Azure/azure-sdk-for-python#18999]
Hello, I'm using the code from the [multivariate model notebook](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_multivariate_detect.py) to apply the model to my time series data. Yet during the training part, the model fails no matter what, and I'm not sure what the problem is. 

The below is the zip file of data I'm using:
[test data.zip](https://github.com/Azure/azure-sdk-for-python/files/6572851/test.data.zip)

I uploaded the data as a zip file to my Azure blob storage and generated SAS.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by LW0214** [comment]
Thank you so much! I really enjoy the Azure service and I look forward to
getting back on this model in my work soon!

Best,
Lucy

**Comment by LW0214** [comment]
Hello,

I have figured out what the problem is, so there's no need to investigate anymore. Thanks for your service anyway.
