### ISSUE TITLE
azure-mgmt-resource documentation is missing the module itself

### ISSUE THREAD

**Issue by sschols** [Azure/azure-sdk-for-python#19009]
- **Package Name**: azure-mgmt-resource
- **Package Version**: 18.0.0
- **Operating System**: -not relevant-
- **Python Version**: -not relevant-

**Describe the bug**
The documentation for the azure-mgmt-resource module (https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-resource/18.0.0/index.html#) is missing the actual module documentation. This is not just the case for 18.0.0, but also for previous releases of that module.

There is documentation at https://docs.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource?view=azure-python, but this is not linked to in the documentation overview at https://azure.github.io/azure-sdk-for-python/index.html

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/60104242/120156478-4e030800-c1f2-11eb-9cc3-e7c5bd40f9b4.png)

**Additional context**

**Comment by swathipil** [comment]
@sschols Thanks for your feedback! Routing this to the right people.

**Comment by RAY-316** [comment]
We will inform resource service teams to update relevant documents asap
