### ISSUE TITLE
Synapse: add Spark driver log retrieval 

### ISSUE THREAD

**Issue by aperezmig** [Azure/azure-sdk-for-python#19008]
**Is your feature request related to a problem? Please describe.**
I'm creating some Python functions to run a Spark job in a Synapse Apache Spark pool and I want to retrieve the logs, but I don't find an option to do it.

**Describe the solution you'd like**
I would like to have a method in _models.SparkBatchJob that lets me retrieve driver's logs, being able to select whether it is stderr or stdout.

**Describe alternatives you've considered**
I've used the _log_lines_ property of **SparkBatchJob**, but it only shows the last few lines of the Livy tab.

**Comment by swathipil** [comment]
@angelpy Thanks for the feedback! Routing this to the right people.
