### ISSUE TITLE
[text analytics] uncomment out multi page healthcare tests

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#19015]
Uncomment out [these](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py#L267) tests and make sure they work. Might need to update tests as well now that healthcare is multi page.

Might have to wait until GA of 3.1, since 3.1-preview.5 still can only return single page

**Comment by kristapratico** [comment]
There wasn't a customer ask to increase the document limit for v3.1 so it will remain at 10. Since service-side paging is set at 20 documents, pagination from the service will not be activated yet. Leaving these tests commented out and moving to backlog.

**Comment by kristapratico** [comment]
There's no reason to leave this issue open tracking this since the service has no future plans to do this. Going to remove the commented out tests  - we can use the PR to add them back if they are ever actually needed.
