### ISSUE TITLE
create_pipeline_run returns 202 instead of 200

### ISSUE THREAD

**Issue by minhdn90** [Azure/azure-sdk-for-python#19042]
- **azure-synapse**: 
- **0.1.1**: 
- **Ubuntu 18.04 WSL**:
- **Python 3.9.5**: 

**Describe the bug**
Class: azure.synapse.artifacts.operations.PipelineOperations
Method: create_pipeline_run
The library code expects HTTP response code 200 but it returns 202 instead, so it raises exception
https://github.com/Azure/azure-sdk-for-python/blob/7c4cfe236d113c59e66515b6315def256219aa6b/sdk/synapse/azure-synapse/azure/synapse/artifacts/operations/_pipeline_operations.py#L365

**To Reproduce**
Steps to reproduce the behaviour:
1. Prepare Synapse Workspace with a pipeline artifact
2. Create Synapse ArtifactClient
2. Get the PipelineOperations class from the client
3. Run the pipeline using create_pipeline_run
4. Get the exception
`File "/home/mnguyen/.local/lib/python3.9/site-packages/azure/synapse/artifacts/operations/_pipeline_operations.py", line 368, in create_pipeline_run
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Accepted'`

**Expected behavior**
An object of class CreateRunResponse returned with run_id

**Screenshots**
![image](https://user-images.githubusercontent.com/6844157/120524959-86ac0880-c3cf-11eb-9419-b630b57e3e93.png)

**Comment by annatisch** [comment]
Thanks @minhdn90 - this is a good catch!
This layer of the SDK is generated from a swagger spec of the REST API.
It looks like the issue you found was corrected in the spec back in January:
https://github.com/Azure/azure-rest-api-specs/commit/b9fbfae938a0ec0e8a696b450a917b47bea1f2e3#diff-66f25443b4b9666c1dd0c80499584729c40448e2563e2bd31660d347320904d6

So we will need to regenerate this layer and re-release.

**Comment by minhdn90** [comment]
Thanks you @annatisch so much for your quick response.
If we have to wait for the next release of azure-synapse, when is it due?

**Comment by annatisch** [comment]
No problem @minhdn90!
@lmazuel, @xiangyan99 - who can I reach out to about this one so we can get this update underway?

**Comment by xiangyan99** [comment]
Thank you @annatisch 

@minhdn90 azure-synapse is deprecated. 

Please use the package https://pypi.org/project/azure-synapse-artifacts/.  :)

**Comment by annatisch** [comment]
Awesome - thanks @xiangyan99!
I couldn't find any reference documentation for that package - do you have a link handy? Maybe we can update the readme at some point...

**Comment by xiangyan99** [comment]
We updated the readme on pypi azure-synapse package. 

https://pypi.org/project/azure-synapse/

**Comment by minhdn90** [comment]
Thanks all for your help.
So to sum up, the correct HTTP response should be 202, and the Python library azure-synapse-artifacts was updated to accept this code.
In the deprecated package, there was a mismatch. One party returns 202, but its counterpart insists on 200.

**Comment by annatisch** [comment]
That's correct @minhdn90 
In the new package that @xiangyan99 linked to, you can see that it's now acting on the correct 202 status code:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/synapse/azure-synapse-artifacts/azure/synapse/artifacts/operations/_pipeline_operations.py#L608

Try out the latest package and let us know if you have any further trouble :)

**Comment by minhdn90** [comment]
Thanks for your help guys. It works fine after switching to use the latest version.

**Comment by annatisch** [comment]
Thanks for following up @minhdn90 - glad it's now working :)
