### ISSUE TITLE
Improve exception base message for some OData v4 error extension format

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#19094]
Assuming a HttpResponse 200, and the payload is this:
```json
{
  "id": "/subscriptions/id/locations/westus/operationsStatus/sameguid",
  "name": "sameguid",
  "status" : "RP defined values | Succeeded | Failed | Canceled",
  "startTime": "<DateLiteral per ISO8601>",
  "endTime": "<DateLiteral per ISO8601>",
  "percentComplete": 50,
  "error" : {
    "code": "BadArgument",
    "message": "The provided database &#39;foo&#39; has an invalid username."
  }
}
```

And we created an exception from that with `raise HttpResponseError(response=response)`

The `str` of that message should be able to pickup that the format is compliant with ODataV4 format, and therefore:
```python
assert str(response) == "(BadArgument) The provided database &#39;foo&#39; has an invalid username."
```

**Comment by lmazuel** [comment]
Closing, since it works:
![image](https://user-images.githubusercontent.com/1050156/120727397-4b710e80-c48f-11eb-8213-96c4ad924a3e.png)

**Comment by xiangyan99** [comment]
I was adding the test case and it seemed to me no change needed. :)
