### ISSUE TITLE
CredentialUnavailableError raised from `ImdsCredential` with no real connection issue

### ISSUE THREAD

**Issue by bonsairobo** [Azure/azure-sdk-for-python#19091]
- **Package Name**: azure.identity
- **Package Version**: master
- **Operating System**: Linux
- **Python Version**: 3

**Describe the bug**

Here: https://github.com/Azure/azure-sdk-for-python/blob/e918edd34ff64e235b990f54622510ce4c34de2a/sdk/identity/azure-identity/azure/identity/_credentials/imds.py#L60

The code assumes that if gets an `Exception` other than `HttpResponseError`, then it must be some connectivity issue. This is probably not valid, as we have tested our connection to 169.254.169.254 immediately after getting the "no managed identity endpoint found" error, and there was no connection problem.

The larger issue is that the original exception is dropped, so the user can't even know what went wrong. Rather, they get a useless `CredentialUnavailableError`. It would be much nicer if you wrapped the original error so the user knows what happened.

Furthermore, after the first presumed connection failure with IMDS, the `_request_token` method will set `_endpoint_available` to `False`, which makes it *always* raise `CredentialUnavailableError` on further calls; there is no hope for recovering.

**To Reproduce**

1. Create a `SecretClient` with a `ManagedIdentity` credential.
2. We use azure.keyvault.secrets.SecretClient.get_secret and occasionally we get:

```
azure.identity._exceptions.CredentialUnavailableError: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
```
We retry on this error, but it never recovers, and we eventually timeout at a higher layer.

**Expected behavior**

I think you have a few options:

1. Actually test TCP connections with IMDS instead of relying on exception handling at the HTTP layer.
2. Wrap the exception into the `CredentialUnavailableError` instead of dropping it so users can see what happened.

**Comment by chlowell** [comment]
Sure, we can find a way to expose the error. I'm also curious what exactly is happening here. Is your application deployed to a VM?

> after the first presumed connection failure with IMDS, the _request_token method will set _endpoint_available to False, which makes it always raise CredentialUnavailableError on further calls; there is no hope for recovering.

This is a deliberate part of the design. It's awkward in some cases (pod identity) and we've discussed alternatives but have kept this behavior because the application may be running on a platform without IMDS, in which case we don't want to keep timing out waiting for responses from it. This behavior is per instance though, so if it's problematic for your application, one (admittedly not great) workaround is to create another credential instance.

**Comment by bonsairobo** [comment]
Thanks for the quick reply!

Yes our application is running on a VM. It's a pretty simple Python script that fetches a secret from a key vault.

> This is a deliberate part of the design. It's awkward in some cases (pod identity) and we've discussed alternatives but have kept this behavior because the application may be running on a platform without IMDS, in which case we don't want to keep timing out waiting for responses from it.

I see. That seems reasonable then. It would be better to avoid the blanket `except Exception` though.

> one (admittedly not great) workaround is to create another credential instance

We have discussed this workaround. It should work fine for us. We just can't be sure our app will be able to recover from whatever is causing the `CredentialUnavailableError` until we can see the original error. So that kind of fix would be appreciated!

**Comment by chlowell** [comment]
In azure-identity 1.7.0b2, now available on PyPI, the credential exposes the original exception by raising CredentialUnavailableError `from` it. Please try the new version and update this issue with the details of that exception; it might point to a problem we can address in the SDK.

**Comment by bonsairobo** [comment]
@chlowell Hey I appreciate the improvement! Unfortunately we've since replaced the Python client with something new, so it doesn't make sense for us to upgrade the package, and we won't be able to provide any new details about the exception. Hopefully if it's an important error, it crops up somewhere else! Thanks again.

**Comment by chlowell** [comment]
I'll close this issue then, thank you for opening it.
