### ISSUE TITLE
azure-mgmt-loganalytics=10.0.0 is missing WorkspaceSku.max_capacity_reservation_level

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#19102]
- **Package Name**: azure-mgmt-loganalytics
- **Package Version**: 10.0.0
- **Operating System**: Linux
- **Python Version**: 3.7.3

**Describe the bug**
In version 18.0.0, WorkspaceSku no longer has a max_capacity_reservation_level. This attribute existed in 9.0.0. The parameter is part of the REST API: https://docs.microsoft.com/en-us/rest/api/loganalytics/workspaces/create-or-update#workspacesku

**To Reproduce**
1. Install azure-mgmt-loganalytics=10.0.0
2. Examine site-packages/azure/mgmt/loganalytics/models/_models_py3.py - observe that the attribute is not there.

**Expected behavior**
I expect the attribute to exist and the objects to serialize and deserialize it.

**Comment by annatisch** [comment]
Thanks @jazelenk!
Adding @msyyc to take a look :)

**Comment by RAY-316** [comment]
Hi @jazelenk I found that the parameter: capacity_reservation_level is still working. Can you provide a more specific application scenario in which max_capacity_reservation_level must be used?

**Comment by jazelenk** [comment]
`capacity_reservation_level` and `max_capacity_reservation_level ` are two different attributes.

Compare with azure-mgmt-loganalytics==9.0.0

```
class WorkspaceSku(msrest.serialization.Model):
    """The SKU (tier) of a workspace.

    Variables are only populated by the server, and will be ignored when sending a request.

    All required parameters must be populated in order to send to Azure.

    :param name: Required. The name of the SKU. Possible values include: "Free", "Standard",
     "Premium", "PerNode", "PerGB2018", "Standalone", "CapacityReservation", "LACluster".
    :type name: str or ~azure.mgmt.loganalytics.models.WorkspaceSkuNameEnum
    :param capacity_reservation_level: The capacity reservation level for this workspace, when
     CapacityReservation sku is selected.
    :type capacity_reservation_level: int
    :ivar max_capacity_reservation_level: The maximum capacity reservation level available for this
     workspace, when CapacityReservation sku is selected.
    :vartype max_capacity_reservation_level: int
    :ivar last_sku_update: The last time when the sku was updated.
    :vartype last_sku_update: str
    """

    _validation = {
        'name': {'required': True},
        'max_capacity_reservation_level': {'readonly': True},
        'last_sku_update': {'readonly': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'capacity_reservation_level': {'key': 'capacityReservationLevel', 'type': 'int'},
        'max_capacity_reservation_level': {'key': 'maxCapacityReservationLevel', 'type': 'int'},
        'last_sku_update': {'key': 'lastSkuUpdate', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        name: Union[str, "WorkspaceSkuNameEnum"],
        capacity_reservation_level: Optional[int] = None,
        **kwargs
    ):
        super(WorkspaceSku, self).__init__(**kwargs)
        self.name = name
        self.capacity_reservation_level = capacity_reservation_level
        self.max_capacity_reservation_level = None
        self.last_sku_update = None

```

**Comment by RAY-316** [comment]
Delete max_capacity_reservation_level is a breaking change for  azure-mgmt-loganalytics 10.0.0.  I think you can still use 9.0.0,  or we can ask service teams for help if it doesn't meet your requirements

**Comment by jazelenk** [comment]
Confirmed that this bug is still present in azure-mgmt-loganalytics==12.0.0. What further information is required?

**Comment by jazelenk** [comment]
/unresolve

As mentioned above, Confirmed that this bug is still present in azure-mgmt-loganalytics==12.0.0

**Comment by jazelenk** [comment]
I see that https://docs.microsoft.com/en-us/rest/api/loganalytics/workspaces/create-or-update#workspacesku no longer shows this property, so I believe this issue may be closed.
