### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [Azure/azure-sdk-for-python#19126]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine sdk/applicationinsights/azure-applicationinsights/azure/applicationinsights/models/error_response.py, sdk/applicationinsights/azure-applicationinsights/azure/applicationinsights/models/error_response_py3.py, sdk/batch/azure-batch/azure/batch/models/_models.py, sdk/batch/azure-batch/azure/batch/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-anomalydetector/azure/cognitiveservices/anomalydetector/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-anomalydetector/azure/cognitiveservices/anomalydetector/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/error_response.py, sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/error_response_py3.py, sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/error_response.py, sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/error_response_py3.py, sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-language-spellcheck/azure/cognitiveservices/language/spellcheck/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-language-spellcheck/azure/cognitiveservices/language/spellcheck/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/azure/cognitiveservices/language/textanalytics/models/error_response.py, sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/azure/cognitiveservices/language/textanalytics/models/error_response_py3.py, sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/error_response.py, sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/error_response_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-customimagesearch/azure/cognitiveservices/search/customimagesearch/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-search-customimagesearch/azure/cognitiveservices/search/customimagesearch/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-customsearch/azure/cognitiveservices/search/customsearch/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-search-customsearch/azure/cognitiveservices/search/customsearch/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-entitysearch/azure/cognitiveservices/search/entitysearch/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-search-entitysearch/azure/cognitiveservices/search/entitysearch/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-imagesearch/azure/cognitiveservices/search/imagesearch/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-search-imagesearch/azure/cognitiveservices/search/imagesearch/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-newssearch/azure/cognitiveservices/search/newssearch/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-search-newssearch/azure/cognitiveservices/search/newssearch/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-videosearch/azure/cognitiveservices/search/videosearch/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-search-videosearch/azure/cognitiveservices/search/videosearch/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/error_response.py, sdk/cognitiveservices/azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/error_response_py3.py, sdk/cognitiveservices/azure-cognitiveservices-search-websearch/azure/cognitiveservices/search/websearch/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-search-websearch/azure/cognitiveservices/search/websearch/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/prediction/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/prediction/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/_models_py3.py, sdk/graphrbac/azure-graphrbac/azure/graphrbac/models/graph_error.py, sdk/graphrbac/azure-graphrbac/azure/graphrbac/models/graph_error_py3.py, sdk/loganalytics/azure-loganalytics/azure/loganalytics/models/error_response.py, sdk/loganalytics/azure-loganalytics/azure/loganalytics/models/error_response_py3.py, sdk/powerbiembedded/azure-mgmt-powerbiembedded/azure/mgmt/powerbiembedded/models/error.py, sdk/powerbiembedded/azure-mgmt-powerbiembedded/azure/mgmt/powerbiembedded/models/error_py3.py, sdk/servermanager/azure-mgmt-servermanager/azure/mgmt/servermanager/models/error.py, sdk/servermanager/azure-mgmt-servermanager/azure/mgmt/servermanager/models/error_py3.py, sdk/servicefabric/azure-servicefabric/azure/servicefabric/models/_models.py, sdk/servicefabric/azure-servicefabric/azure/servicefabric/models/_models_py3.py and observe `responsed`, however expect to see `responded`.
- Examine doc/dev/mgmt/generation.md, sdk/storage/azure-storage-blob/tests/test_retry.py, sdk/storage/azure-storage-blob/tests/test_retry_async.py and observe `pratical`, however expect to see `practical`.
- Examine sdk/search/azure-search-documents/azure/search/documents/_paging.py, sdk/search/azure-search-documents/azure/search/documents/aio/_paging.py and observe `covereage`, however expect to see `coverage`.
- Examine sdk/eventgrid/azure-eventgrid/azure/eventgrid/_policies.py and observe `transmition`, however expect to see `transmission`.
- Examine sdk/core/azure-servicemanagement-legacy/azure/servicemanagement/_http/winhttp.py and observe `resonse`, however expect to see `response`.
- Examine sdk/cosmos/azure-cosmos/azure/cosmos/_synchronized_request.py and observe `resquest`, however expect to see `request`.
- Examine sdk/core/azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementservice.py and observe `hypen`, however expect to see `hyphen`.
- Examine sdk/core/azure-core/tests/test_basic_transport.py and observe `guaranted`, however expect to see `guaranteed`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/azure-sdk-for-python/pull/new/bugfix_typos

Thanks.

**Comment by yunhaoling** [comment]
@timgates42 , really appreciate you finding out the typos and proposing the fix.
Could you make the PR for us? we'll review your PR ASAP

**Comment by timgates42** [comment]
Thanks @yunhaoling added #19127
