### ISSUE TITLE
Class documentation links are 404

### ISSUE THREAD

**Issue by smena** [Azure/azure-sdk-for-python#19131]
The [ResourceManagementClient](https://docs.microsoft.com/en-us/python/api/azure.mgmt.resource.resources.resourcemanagementclient
) and [ContainerInstanceManagementClient](https://docs.microsoft.com/en-us/python/api/azure.mgmt.containerinstance.containerinstancemanagementclient) links on this page are dead and should likely instead link to [ResourceManagementClient](https://docs.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.resources.resourcemanagementclient?view=azure-python) and [ContainerInstanceManagementClient](https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerinstance/azure.mgmt.containerinstance.containerinstancemanagementclient?view=azure-python).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e732e187-7ff4-bd4f-9aad-44953af44a86
* Version Independent ID: d4baa2d6-8f2f-ed76-e890-3240065f485a
* Content: [Azure Container Instances libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/containerinstance?view=azure-python)
* Content Source: [docs-ref-services/latest/containerinstance.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/containerinstance.md)
* Service: **container-instances**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by yunhaoling** [comment]
@smena, thanks for the feedback!
adding @msyyc to have a look on the doc issue.

**Comment by dlepow** [comment]
@nickomang - Could you please take a look at the broken links on this page? I think the customer's suggestion to fix is correct. Thanks a lot!

**Comment by msyyc** [comment]
Hi @scbedd I don't have access to update [docs](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/containerinstance.md). Could you help to update it with right link?

**Comment by Nickomang** [comment]
The suggestion looks good to me. @scbedd , I opened a PR with the proposed changes, as well as fixes to the other API links in the article. Feel free to merge if it looks good to you, or reach out if you have any questions.

**Comment by scbedd** [comment]
@Nickomang merged! Next deployment is **tomorrow**. I will close this issue once it verifies on live. Thanks muchly for the PR!

**Comment by scbedd** [comment]
Confirming fixed on live. Closing this issue.
