### ISSUE TITLE
backup_protection_containers.list got 400 error

### ISSUE THREAD

**Issue by chihhaohuang** [Azure/azure-sdk-for-python#19147]
I am getting 400 error when try to get all backup protection containers.

Code example:

from azure.identity import ClientSecretCredential
from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient

...
credential = ClientSecretCredential(tenant_id=tenant_id, client_id=client_id, client_secret=client_secret)
recovery_backup_client = RecoveryServicesBackupClient(credential, subscription_id)

protection_containers = recovery_backup_client.backup_protection_containers.list(vault_name, resource_group)
for protection_container in protection_containers:
  print(protection_container

I got 400 error.
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'

I believe all configurations are fine. Running similar code to get backupProtectedItems is fine.
protected_items = recovery_backup_client.backup_protected_items.list(vault_name, resource_group)

Direct REST API call also got the same error: (Tried from https://docs.microsoft.com/en-us/rest/api/backup/2021-02-10/backup-protection-containers/list )

 "response": {
    "body": "{\"error\":{\"code\":\"BMSUserErrorInvalidInput\",\"message\":\"Input provided for the call is invalid\\r\\nPlease check the required inputs\",\"target\":null,\"details\":null,\"innerError\":null}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-length": "179",
      "content-type": "application/json",
      "x-content-type-options": "nosniff",
      "x-ms-request-id": "1082d942-e358-4285-bcd4-c02916896ca2",
      "x-ms-client-request-id": "62cd7b68-57fd-4e80-82fa-1d290115d97b, 62cd7b68-57fd-4e80-82fa-1d290115d97b",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "server": "Microsoft-IIS/10.0",
      "x-powered-by": "ASP.NET",
      "x-ms-ratelimit-remaining-subscription-resource-requests": "149",
      "x-ms-correlation-request-id": "1082d942-e358-4285-bcd4-c02916896ca2",
      "x-ms-routing-request-id": "WESTEUROPE:20210608T144544Z:1082d942-e358-4285-bcd4-c02916896ca2",
      "date": "Tue, 08 Jun 2021 14:45:43 GMT"
    },
    "status": 400
  }

**Comment by yunhaoling** [comment]
@chihhaohuang, thanks for reaching out!
looping in @msyyc to take a look.

**Comment by RAY-316** [comment]
hi @chihhaohuang ,I saw your questions and working on it , could you please provide an example about ‘Running similar code to get backupProtectedItems is fine.’

**Comment by chihhaohuang** [comment]
Hi,
This works
recovery_backup_client.backup_protected_items.list(vault_name, resource_group, filter)

I think this is azure REST API issue, not this library issue. Tried the API on azure website, it returned the same error.
