### ISSUE TITLE
azure-mgmt-monitor throwing DeserializationError when handling API error

### ISSUE THREAD

**Issue by bmclarnon-r7** [Azure/azure-sdk-for-python#19178]
- **Package Name**: azure-mgmt-monitor
- **Package Version**: 2.0.0
- **Operating System**: Ubuntu 20.04 (container)
- **Python Version**: 3.8.5

**Describe the bug**
When handling a `ResourceNotFound` error from the API, azure-mgmt-monitor attempts to deserialize the response, but eventually throws a `DeserializationError`:

```
File "/usr/local/lib/python3.8/dist-packages/azure/mgmt/monitor/v2017_05_01_preview/operations/_diagnostic_settings_operations.py", line 273, in list
    error = self._deserialize(_models.ErrorResponse, response)
  File "msrest/serialization.py", line 1368, in __call__
    return self._deserialize(target_obj, data)
  File "msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "msrest/serialization.py", line 1172, in rest_key_extractor
    return working_data.get(key)
DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

This happens for a number of calls (e.g. access flow logs, metrics) and API versions (also observed with `v2016_09_01`). It looks like somehow, the error response is coming back as a string and is not being correctly converted to a dictionary.

**To Reproduce**
1. Attempt to induce an error while using the Monitor API client (e.g. by looking up Diagnostic Settings for a resource that doesn't exist).

**Additional context**
Previous issues (#7688, #13943, #15544) may have the same root cause.

**Comment by yunhaoling** [comment]
@bmclarnon-r7, thanks for reaching out.
Adding @msyyc to help on the issue.

**Comment by BigCat20196** [comment]
hi @bmclarnon-r7, thanks for feekback!

The latest version of azure MGMT monitor is now 3.0.0. 
It is recommended to upgrade to the latest version and try again. 

After my investigation, I now query a nonexistent resource group and its return is `ResourceGroupNotFound`.

**Comment by bmclarnon-r7** [comment]
Thanks for the update! I'll try again with the latest version and update the issue.

**Comment by bmclarnon-r7** [comment]
Looks like our issue is resolved. Thanks for your help!
