### ISSUE TITLE
In the StorageAccountHostsMixin class of the python sdk, there is no correct way to parse account name from the Azurite storage blob endpoint

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-python#19200]
**Error Description:**
[Azurite](https://github.com/Azure/Azurite) is an Azure Storage emulator.
In the StorageAccountHostsMixin class of the python sdk, there is no correct way to parse account name from the Azurite storage blob endpoint.

In Azurite, storage blob endpoint constructed is shown as following:
`https://127.0.0.1:10000/<account-name>/<resource-path>`
In Azure SDK for python, storage blob endpoint constructed is shown as following:
`https://<account-name>.blob.core.windows.net/<resource-path>`

**To Reproduce:**
A demo code is shown as following:
```Python
from azure.storage.blob import BlobClient

account_url = "https://127.0.0.1:10000/devstoreaccount1"+"/foourl/barurl"
access_key = "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
blob_client = BlobClient(account_url=account_url, credential=access_key)
print(blob_client.account_name=="devstoreaccount1")
```

**Error Track:**
The process code for parse account name from the Azurite storage blob endpoint is shown as following:
[https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py#L87](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py#L87)
![image](https://user-images.githubusercontent.com/20970631/121487979-35ba9680-ca05-11eb-9d8a-72b7566d85ed.png)

**Expected Behavior:**
there is a correct way to parse account name from the Azurite storage blob endpoint in python SDK. Finally, able to successfully access azurite.

@dw511214992, @ramya-rao-a, @kyle-patterson, @tg-msft for notification.

**Comment by v-xuto** [comment]
@ramya-rao-a, @kyle-patterson, @tg-msft, @dw511214992 Any ideas about this issue?

**Comment by v-xuto** [comment]
@tasherif-msft Do you have any progress on this issue?

**Comment by v-xuto** [comment]
@tasherif-msft Do you have any progress on this issue?

**Comment by jalauzon-msft** [comment]
Hi @zzhxiaofeng @v-xuto, sorry for the long delay on this but I wanted to provide you with the solution to this if you were still looking.

In the sample, you are setting the account URL to also contain the blob path. This is not valid as the account URL should just be the plain account URL, `https://127.0.0.1:10000/<account-name>` in this case. To provide the blob path, you can either use the other params of the `BlobClient` constructor or the `from_blob_url` function on the `BlobClient`. Here is a sample which assumes your container is called `foourl` and your blob name is `barurl` (based on the provided sample).

```python
from azure.storage.blob import BlobClient

account_url = "https://127.0.0.1:10000/devstoreaccount1"
access_key = "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="

# Option 1: Provide container name and blob name to BlobClient. These are required parameters anyway
blob_client = BlobClient(account_url=account_url, container_name="foourl", blob_name="bar_url", credential=access_key)

# Option 2: Use the from_blob_url helper function
blob_url = "https://127.0.0.1:10000/devstoreaccount1" + "/foourl/barurl"
blob_client = BlobClient.from_blob_url(blob_url, credential=access_key)
```

Hopefully this helps and let me know if you have any questions. Thanks!

**Comment by zzhxiaofeng** [comment]
@jalauzon-msft Thanks for your contribution. This issue has been fixed. I will close the issue now.
