### ISSUE TITLE
ServicePrincipalCredentials outdated, should use ClientSecretCredential instead

### ISSUE THREAD

**Issue by hwang-kinaxis** [Azure/azure-sdk-for-python#19210]
Current tutorial would hit error:

   AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'

Should update the tutorial using ClientSecretCredential

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb96284-14f1-2118-09a2-7e9eea175cc7
* Version Independent ID: d95ba2d5-a26c-d3d3-9ffc-4401603821a9
* Content: [Azure HDInsight SDK for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/hdinsight?view=azure-python)
* Content Source: [docs-ref-services/latest/hdinsight.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/hdinsight.md)
* Service: **hdinsight**
* GitHub Login: @tylerfox
* Microsoft Alias: **tyfox**

**Comment by yunhaoling** [comment]
@hwang-kinaxis , thanks for your feedback.
adding @msyyc to take a look on the doc issue.

**Comment by aim-for-better** [comment]
@msyyc @yunhaoling Thanks for help. Do you have any progress? What is the python sdk version? I can not find the sdk version from the` ID: aeb96284-14f1-2118-09a2-7e9eea175cc7 Version Independent ID: d95ba2d5-a26c-d3d3-9ffc-4401603821a9 `?

**Comment by aim-for-better** [comment]
It seems that it is the common issue not related with service details

**Comment by aim-for-better** [comment]
@hwang-kinaxis  what is your python sdk version? And could you please share the tutorial  you are using?
