### ISSUE TITLE
azure-mgmt-batch Pool create incorrect API version

### ISSUE THREAD

**Issue by michaelcredera** [Azure/azure-sdk-for-python#19224]
- **Package Name**: azure-mgmt-batch
- **Package Version**:  15.0.0
- **Operating System**: MacOS
- **Python Version**: 3.8

**Describe the bug**
azure-mgmt-batch PoolOperations.create references a Batch Management REST API version that does not exist yet:

References 2021-01-01: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/batch/azure-mgmt-batch/azure/mgmt/batch/operations/_pool_operations.py#L192

Latest available is 2020-09-01.12.0 at the time of writing: https://docs.microsoft.com/en-us/rest/api/batchservice/batch-service-rest-api-versioning

This causes the error:

```
HttpResponseError: (InvalidQueryParameterValue) {'lang': 'en-US', 'value': 'Value for one of the query parameters specified in the request URI is invalid.\nRequestId:c56f5616-7008-4b66-af1d-8c1294d096d7\nTime:2021-06-11T20:41:40.1708298Z'}
Code: InvalidQueryParameterValue
Message: {'lang': 'en-US', 'value': 'Value for one of the query parameters specified in the request URI is invalid.\nRequestId:c56f5616-7008-4b66-af1d-8c1294d096d7\nTime:2021-06-11T20:41:40.1708298Z'}
```

(side note - HttpResponseError could be improved to include `response.body()` as the body is the only place where the actual invalid parameter is specified :) 

**To Reproduce**
1. Create a batch account
2. Attempt to create a pool inside that batch account using the latest azure-mgmt-batch version

```python
credentials = azure.identity.DefaultAzureCredential()
cli = azure.mgmt.batch.BatchManagement(
    credential=credentials,
    subscription_id=subscription_id,
    base_url=base_url,
)
cli.pool.create(
    resource_group_name=resource_group_name,
    account_name=batch_account_name,
    pool_name=pool_id,
    parameters=azure.mgmt.batch.models.Pool(...),
)
```

**Expected behavior**
The pool is created without errors from the HTTP request being invalid.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by RAY-316** [comment]
hi @michaelcredera  I have used the 15.0.0 package to create a pool inside the batch account, it seems that everything is all right. Can you provide more detailed examples or  try again？https://github.com/Azure/azure-sdk-for-python/blob/026f587017e99ac9711ddb996279f2defaa7b569/sdk/batch/azure-mgmt-batch/tests/test_mgmt_batch.py#L319

**Comment by michaelcredera** [comment]
Sure, here's the code I'm calling that leads to the above error. What's interesting to me is that the error I post above is coming directly from the HTTP API due to the API version, not from the code. I'll test again, maybe they just updated the HTTP API in the server lol!

```python
import azure.mgmt.batch as az_batch
import azure.mgmt.batch.operations as az_batch_ops
import azure.mgmt.batch.models as az_batch_models

vm_cfg = az_batch_models.VirtualMachineConfiguration(
            image_reference=az_batch_models.ImageReference(
            publisher="microsoft-azure-batch", offer="ubuntu-server-container", version="20-04-lts",
        ),
            node_agent_sku_id="batch.node.ubuntu 20.04",
            container_configuration=az_batch_models.ContainerConfiguration(
                container_image_names=["container_name"],
                container_registries=[
                az_batch_models.ContainerRegistry(
                    user_name="user",
                    password="pass",
                    registry_server="host",
                )
            ],
            ),
        )

identity_arm = "user identity arm"
pool = az_batch_models.Pool(
            identity=az_batch_models.BatchPoolIdentity(
                type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
                user_assigned_identities={
                    identity_arm: az_batch_models.Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties()
                },
            ),
            display_name="pool name",
            vm_size=1,
            deployment_configuration=az_batch_models.DeploymentConfiguration(
                virtual_machine_configuration=vm_cfg,
            ),
            scale_settings=az_batch_models.ScaleSettings(
                fixed_scale=az_batch_models.FixedScaleSettings(
                    target_dedicated_nodes=0,
                    target_low_priority_nodes=1,
                )
            ),
            task_slots_per_node=8,
            start_task=None,
        )

credentials = azure.identity.DefaultAzureCredential()
pool_client = az_batch.BatchManagement(
            credential=credentials,
            subscription_id="subscription_id",
        )

pool_client.pool.create(
                resource_group_name="resource_group_name",
                account_name="batch_account_name",
                pool_name="pool name",
                parameters=pool,
            )

```

**Comment by michaelcredera** [comment]
No change in the documentation, still referencing different API versions:

https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-batch_15.0.0/sdk/batch/azure-mgmt-batch/azure/mgmt/batch/operations/_pool_operations.py#L192

https://docs.microsoft.com/en-us/rest/api/batchservice/batch-service-rest-api-versioning

I'll still retry, maybe docs are stale

**Comment by michaelcredera** [comment]
Improvement! Backend must've added the 2021 API version, but now I get a 500 error:

```
HttpResponseError: (InternalServerError) Encountered internal server error. Diagnostic information: timestamp '20210622T132304Z', subscription id 'x', tracking id 'e2ce0f0e-ddb5-48da-8273-b366465c1b30', request correlation id 'e2ce0f0e-ddb5-48da-8273-b366465c1b30'.
Code: InternalServerError
Message: Encountered internal server error. Diagnostic information: timestamp '20210622T132304Z', subscription id 'x', tracking id 'e2ce0f0e-ddb5-48da-8273-b366465c1b30', request correlation id 'e2ce0f0e-ddb5-48da-8273-b366465c1b30'.
```

**Comment by michaelcredera** [comment]
Confirmed that it's the identity that's causing the 500 error:
```
            identity=az_batch_models.BatchPoolIdentity(
                type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
                user_assigned_identities={
                    identity_arm: az_batch_models.Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties()
                },
            ),
```

Removing this makes things work - anyone have any idea why using a user identity would cause 500 errors?

**Comment by michaelcredera** [comment]
Confirmed that it's the identity that's causing the 500 error:
```
            identity=az_batch_models.BatchPoolIdentity(
                type=az_batch_models.PoolIdentityType.USER_ASSIGNED,
                user_assigned_identities={
                    identity_arm: az_batch_models.Components81XseeSchemasBatchpoolidentityPropertiesUserassignedidentitiesAdditionalproperties()
                },
            ),
```

Removing this makes things work - anyone have any idea why using a user identity would cause 500 errors?

**Comment by michaelcredera** [comment]
And now it seems to work without 500 errors... Not sure what happened, but I think things are working now. I'll run some tests to confirm and close this ticket if all is well.
