### ISSUE TITLE
Field `instance_view` missing on `VirtualMachine` class

### ISSUE THREAD

**Issue by max-tet** [Azure/azure-sdk-for-python#19231]
When getting a `VirtualMachine` with `VirtualMachineOperations.get`, the result does have the attribute `instance_view` but it is `None`. Documentation suggests that it should be an object of type `VirtualMachineInstanceView`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37644ee5-4381-6509-420e-723958e4d0fa
* Version Independent ID: 63433655-a927-5f0f-664b-cd17cbf6d84d
* Content: [azure.mgmt.compute.v2021_03_01.models.VirtualMachine class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.models.virtualmachine?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.models.VirtualMachine.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.models.VirtualMachine.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by amjads1** [comment]
@avirishuv Can you please look into this issue?

**Comment by avirishuv** [comment]
@max-tet Are you using the parameter "expand" with value "INSTANCE_VIEW" ? As mentioned here: https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.operations.virtualmachinesoperations?view=azure-python#get-resource-group-name--vm-name--expand-none----kwargs-

**Comment by max-tet** [comment]
> @max-tet Are you using the parameter "expand" with value "INSTANCE_VIEW" ? As mentioned here: https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.operations.virtualmachinesoperations?view=azure-python#get-resource-group-name--vm-name--expand-none----kwargs-

I was not aware of that parameter and I am not using it. Thanks for the hint, I will make it so. Consider this issue fixed.

Am I right that the need to expand the instance view is rather new? My code was working without it ealier.

It might also be a good thing to clear up the documentation a little more regarding the expand param. Adding a hint at the top-level description for the `get` function would do the trick.

**Comment by avirishuv** [comment]
@max-tet glad that his helped and the issue can be resolved. The details of "expand" are mentioned within the parameters section in the same documentation page.

Closing this issue given the resolution, please feel free to reopen if you have additional questions on this topic. Thanks.

**Comment by RAY-316** [comment]
hi @max-tet Could you please provide a more detailed example of using it?
