### ISSUE TITLE
[AMQP Python] Port Event Hubs to receive events

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#19238]
For the initial implementation, this needs to work for only the most basic receive scenario to show that prototype works.

Focus on receiving events of data body (string/bytes) only

- establishment connection to the service endpoint
- receive from a single partition
- receive from all partitions
- receive batch from a single partition
- receive batch from all partitions

**Comment by swathipil** [comment]
add more tests, in separate PR.
look at test coverage first to make sure we are being thorough
