### ISSUE TITLE
Issue with MSAL based auth in ADFS environment

### ISSUE THREAD

**Issue by abbhar** [Azure/azure-sdk-for-python#19261]
Context: 
I am trying to use MSAL based auth against the ADFS environment. I am using ClientSecretCredential for this purpose. 

> credentials = ClientSecretCredential(
>         client_id=os.environ['AZURE_CLIENT_ID'],
>         client_secret=os.environ['AZURE_CLIENT_SECRET'],
>         tenant_id=os.environ['AZURE_TENANT_ID'],
>         authority=mystack_cloud.endpoints.active_directory,
>         validate_authority=False
>     )
> 
> client = ResourceManagementClient(
>         credentials , subscription_id,
>         base_url=mystack_cloud.endpoints.resource_manager,
>         profile=KnownProfiles.v2020_09_01_hybrid,
>         credential_scopes=[mystack_cloud.endpoints.active_directory_resource_id + "/.default"]
>         )

i am facing the below issue while running it against ADFS environment. Here is sample [code ](https://github.com/Azure-Samples/Hybrid-ResourceManager-Python-Manage-Resources/pull/3/files) which i am using. BTW it works fine against AAD with MSAL auth. 

1. when i am passing the authority as  https://adfs.northwest.azs-longhaul-05.selfhost.corp.microsoft.com/adfs it fails with the below error: 

> The client is not allowed to access the requested resource.

2. I also tried to pass the authority using tenant Id guid instead of /adfs(https://adfs.northwest.azs-longhaul-05.selfhost.corp.microsoft.com/3a38509d-79d8-4516-9282-df14fc0adf15), but the SDK append another tenantId guid and it ended up calling https://adfs.northwest.azs-longhaul-05.selfhost.corp.microsoft.com/3a38509d-79d8-4516-9282-df14fc0adf15/3a38509d-79d8-4516-9282-df14fc0adf15, which obviously fails with below error: 

> Authentication failed: invalid_instance: The authority you provided, https://adfs.northwest.azs-longhaul-05.selfhost.corp.microsoft.com/3a38509d-79d8-4516-9282-df14fc0adf15/3a38509d-79d8-4516-9282-df14fc0adf15, is not whitelisted. If it is indeed your legit customized domain name, you can turn off this check by passing in validate_authority=False

3. Another issue which I observed, that when passing validate_authority=False while creating ClientSecretCredential, it doesn't honor this flag and fails with the error: 

The authority you provided is not whitelisted. If it is indeed your legit customized domain name, you can turn off this check by passing in validate_authority=False

***Code Snippet***
https://github.com/Azure-Samples/Hybrid-ResourceManager-Python-Manage-Resources/pull/3/files

**Comment by chlowell** [comment]
Thanks for opening this issue. We need better documentation of ADFS support. The value of `authority` should be a URL authority (optionally with a scheme), i.e. it shouldn't include a path. Also, `tenant_id` should be "adfs". So, editing your code a bit, please try this:
```py
credentials = ClientSecretCredential(
    client_id=os.environ['AZURE_CLIENT_ID'],
    client_secret=os.environ['AZURE_CLIENT_SECRET'],
    tenant_id='adfs',
    authority='https://adfs.northwest.azs-longhaul-05.selfhost.corp.microsoft.com',
)
```

The message about `validate_authority` is from `msal`, an internal dependency, and there's no way to pass that argument to `msal` through ClientSecretCredential.

**Comment by abbhar** [comment]
thanks @chlowell for looking into this, 
I tried with the above tenantId and authority, it is still failing, however different error this time: 

> azure.core.exceptions.ClientAuthenticationError: Authentication failed: MSIS9605: The client is not allowed to access the requested resource.

also  wondering why it's forcing to use tenantId 'adfs' instead of actual tenantId.

**Comment by abbhar** [comment]
I debugged this further, 
I could see that pythonSDK is not encoding the scope correctly in case of ADFS, 

i see the following payload is being send on wire:

in adfs case: 

client_id=<client-Id-goes-here>&grant_type=client_credentials&client_info=1&client_secret=<CLient-Secret_goes-here>&scope=-+-+-+-+-+-+.+.+.+.+.+.+.+%2F+%2F+%2F+%2F+0+0+0+1+1+1+2+2+3+3+4+4+5+5+5+5+6+7+8+8+8+9+9+9+%3A+a+a+a+a+a+a+a+a+c+c+c+c+d+d+d+d+d+d+d+e+e+e+e+f+f+f+f+f+f+f+g+g+h+h+i+i+i+l+l+l+m+m+m+m+m+n+n+n+n+n+o+o+o+o+o+o+p+p+r+r+s+s+s+s+s+s+t+t+t+t+t+t+t+u+z

in AAD case: 
client_id=<CLIENTID>&grant_type=client_credentials&client_info=1&client_secret=<CLIENTSECRET>&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2F.default

@chlowell can you double check how python SDK is creating scope for adfs scenario.

**Comment by chlowell** [comment]
Yes, that scope's definitely invalid. I don't see similar on my machine though. Here's my code:

```py
import logging
import sys
from azure.identity import ClientSecretCredential
from azure.mgmt.resource import ResourceManagementClient

def filter_info_trace(record):
    # log Azure SDK's HTTP traffic at debug level only i.e. filter out info messages
    return record.module == "_universal" and record.levelno == logging.DEBUG

handler = logging.StreamHandler(stream=sys.stdout)
handler.addFilter(filter_info_trace)
logger = logging.getLogger("azure")
logger.setLevel(logging.DEBUG)
logger.addHandler(handler)

credential = ClientSecretCredential(
    tenant_id="adfs",
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    authority=STACK_ADFS_URL,
    logging_enable=True,  # enable debug logging
)

client = ResourceManagementClient(
    credential,

    # invalid values are okay, I'm interested only in the token request
    "subscription_id",
    credential_scopes=["https://localhost/.default"],
    base_url="https://localhost",
)

list(client.resources.list())
```

And this is the token request I see using azure-identity 1.6.0 and azure-mgmt-resource 1.18.0:
```
Request URL: 'https://.../adfs/oauth2/token/'
Request method: 'POST'
Request headers:
    ...
    'User-Agent': 'azsdk-python-identity/1.6.0 Python/3.6.9 ...'
Request body:
{
    "client_id": "...",
    "grant_type": "client_credentials",
    "client_info": 1,
    "client_secret": "...",
    "scope": "https://localhost/.default",
}
```
And the encoded scope was `https%3A%2F%2Flocalhost%2F.default`. So, let's try to figure out where your mangled scope is coming from. Can you adapt my script to your environment, and share the output of `pip freeze`?
