### ISSUE TITLE
Add a poller Return Type for purge_deleted_secret Method in SecretClient Class

### ISSUE THREAD

**Issue by asimarora** [Azure/azure-sdk-for-python#19263]
**Is your feature request related to a problem? Please describe.**
Yes. I was trying to Purge a Secret and then try to recreate it. Since purge_deleted_secret  returns immediately without waiting for purge to complete, we are getting this error when we try to recreate it. 
**azure.core.exceptions.ResourceExistsError: is currently being deleted and cannot be re-created; retry later.**

 We are doing this operation for multiple secrets, Hence we are getting flooded with lot of exceptions.

**Describe the solution you'd like**
Please implement a Poller [https://docs.microsoft.com/en-us/python/api/azure-core/azure.core.polling.lropoller?view=azure-python](url) like we have for begin_delete_secret function so that it becomes handy to use/

**Describe alternatives you've considered**
I tried to put wait function to wait for few seconds which works some time . But this is not a great solution for this problem.

**Additional context**
Any other better solution please suggest/implement.

**Comment by chlowell** [comment]
Thanks for opening this issue. I agree such a poller would be useful. Unfortunately, it's impossible to implement today because there's nothing to poll. Key Vault doesn't have an API for checking purge status, and the APIs it does have don't allow a workaround. For example, GET /deletedsecrets/foo returns 404 before the purge completes. The only way to know a secret is really purged is to create a new one with the same name, which brings you back to where you started 😆

**Comment by asimarora** [comment]
Thanks for reply. Would that be possible/logical to implement an API in KeyVault for checking purge status ?

**Comment by chlowell** [comment]
I tagged the Key Vault team on this issue. Can you please also describe your scenario for them--why is it important to permanently delete old versions of a secret when changing its value? (I assume you already know you can use [set_secret](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-secrets/4.2.0/azure.keyvault.secrets.html#azure.keyvault.secrets.SecretClient.set_secret) to replace the value of a secret at any time without first purging it)

**Comment by asimarora** [comment]
Indeed whatever you said is correct. But I will try to describe my scenario.
We have an application which synchronizes  keyvault(s) from Another Internal Applications. In the mean time any human operator can also access keyvault (who has access) and modify some  secrets. Now if he/she deleted some secrets but didn't purge it then Sync job will fail with an error that Secret is not yet purged . So every time Our Sync job blindly delete plus purge all secrets and then recreate it. 
Instead of putting workarounds over this It would be great If we have a Poller for purge like we have for delete operation then it will be more helpful. Since purge is like a hard delete.
Any other better solution please suggest/implement.

**Comment by sebansal** [comment]
Team is still ongoing making changes on Soft Delete.

**Comment by navba-MSFT** [comment]
@asimarora Apologies for the late reply. We will update this thread once we have more details on this.

@sebansal Could you please provide an update on this once you get a chance ? Awaiting your reply.

**Comment by mccoyp** [comment]
@sebansal has there been an update on the soft delete work?

**Comment by jlichwa** [comment]
There is no plan to implement it.
