### ISSUE TITLE
Unable to get access_token due to aiohttp not honoring env proxy vars

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-sdk-for-python#19282]
- azure-identity 1.6.0
- Python 3.8
- Windows/OSX

The `aio` version of `ClientSecretCredential` when used to obtain an access_token fails with the following error:
`Cannot connect to host <REQUESTED URL>:443 ssl:default [The parameter is incorrect]` because the environment variable `no_proxy` is not honored by aiohttp (which is internally used by the async identity python sdk) 
Here is the aiohttp issue: https://github.com/aio-libs/aiohttp/issues/4431 

**To Reproduce (run this in an asyncio event loop)**

from azure.identity.aio import ClientSecretCredential

credential = await ClientSecretCredential(self.tenant_id,self.client_id,self.client_secret)
token_obj = credential.get_token("https://management.core.windows.net/.default")
credential.close()

**Expected behavior**
Get back a token

**Impacts**

Since Identity cannot be used in an async fashion, this has cascading effects on other SDK's like BlobServiceClient that would need a storage credential and further will lead to customer being able to use only the sync version of these SDK's and it would lead to throughput issues downstream.

aiohttp will release a fix in their 3.8 release (current is 3.7.x) and once that is released, this needs to be re-tested. Keeping this here for tracking

Most secure enterprise setups will have `no_proxy` environment variable set and this should be fixed to fully avail the async aspects of the SDK.

**Comment by awoimbee** [comment]
seems like this is fixed: https://github.com/aio-libs/aiohttp/pull/4445
