### ISSUE TITLE
Add possibility to get tags on subscription level

### ISSUE THREAD

**Issue by unitrium** [Azure/azure-sdk-for-python#19293]
**Is your feature request related to a problem? Please describe.**
At the moment I don't see an easy way to query tags on a Subscription.
The Subscription class doesn't provide a direct attribute to access it. 
**Describe the solution you'd like**
Have an attribute tags in the Subscription class that would list the tags of the Subscription.
There is one attribute tags for the ResourceGroups and Resources not sure why the same option is not available to Subscriptions.

**Describe alternatives you've considered**
 At the moment I found some work around by using the RessourceManagementClient:
 ```
     sub_client = SubscriptionClient(credential=credentials)
    for subscription in sub_client.subscriptions.list():
        client = ResourceManagementClient(credential=credentials, subscription_id=subscription.subscription_id)
        print(client.tags.get_at_scope(scope=subscription.id).properties)
```
but feels a bit convoluted.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.
