### ISSUE TITLE
[Azure Python SDK] Not able to consume output of virtual_machines.list_all with azure-mgmt-compute==20.0.0

### ISSUE THREAD

**Issue by sanvar7** [Azure/azure-sdk-for-python#19295]
I am using Azure Python SDK for resource management.
Below snippet was working with Azure -> **azure-mgmt-compute==12.0.0**, but after upgrading the Azure sdk to **azure-mgmt-compute==20.0.0** it's not working.

```
creds = ServicePrincipalCredentials(client_id=client_id, secret=secret, tenant=tenant_id, **kwargs)

compute_client =  ComputeManagementClient(creds,
                                   subscription_id,
                                   base_url='https://management.azure.com')

paged_iter = compute_client.virtual_machines.list_all(raw=True)

output = []
paged_iter.get(paged_iter.next_link)
while True:
    chunk = json.loads(paged_iter.raw.response.content)
    if 'nextLink' in chunk:
        paged_iter.get(chunk['nextLink'])
    else:
        break
resp = {'value': output}
print(resp)
```

After upgrade getting error
``` AttributeError: 'ItemPaged' object has no attribute 'get' ```

Please help to understand how to consume output of ``` compute_client.virtual_machines.list_all(raw=True)```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by avirishuv** [comment]
@xiangyan99 and @msyyc - were you able to investigate this?

**Comment by RAY-316** [comment]
hi @sanvar7 The old package version like 12.0.0's 'paged_iter ' inherited from msrest.paging.Paged
https://docs.microsoft.com/en-us/python/api/msrest/msrest.paging.paged?view=azure-python

and it now inherit from azure.core.paging.ItemPaged 
https://docs.microsoft.com/en-us/python/api/azure-core/azure.core.paging.itempaged?view=azure-python#by-page-continuation-token-none-

**Comment by avirishuv** [comment]
@yungezz is this something you can clearly document in the Python SDK docs?
cc @xiangyan99

**Comment by yungezz** [comment]
> @yungezz is this something you can clearly document in the Python SDK docs?
> cc @xiangyan99

hi @msyyc do we have migration guide from Track1 to Track2? If yes, could you pls share it? thanks

**Comment by msyyc** [comment]
Hi @avirishuv version < 17.0.0b1 is track1 version and version >= 17.0.0b1 is track2 version. Track1 will be deprecated soon.
(1) The difference between track1 and track2 is described in CHANGELOG.md : https://pypi.org/project/azure-mgmt-compute/22.0.0/
![image](https://user-images.githubusercontent.com/70930885/125715322-3ec1129f-e478-49f9-883f-e3c10a1799ec.png)
(2) We have guidance for migration from track1 to track2 : 
https://devblogs.microsoft.com/azure-sdk/migrating-python-management-libraries/
https://github.com/Azure/azure-cli/blob/dev/doc/track_2_migration_guidance.md

**Comment by avirishuv** [comment]
hi @sanvar7 please let us know if these resources help to answer your question, or do you have any follow-up questions?

**Comment by avirishuv** [comment]
hi @sanvar7 are there any additional questions on this? If not, can we close the issue?

**Comment by avirishuv** [comment]
Closing the issue, as per above. If any additional questions, feel free to reopen.
