### ISSUE TITLE
12.4.0 causes mypy to throw Function has duplicate type signatures

### ISSUE THREAD

**Issue by vertti** [Azure/azure-sdk-for-python#19290]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.4.0
- **Operating System**: ubuntu
- **Python Version**: 3.8.6

**Describe the bug**

Using `azure-storage-file-datalake` in my project. Running `mypy .` now throws:

```
venv/lib/python3.8/site-packages/azure/storage/filedatalake/_data_lake_file_client.py:256: error: Function has duplicate type signatures
```

reverting to `azure-storage-file-datalake==12.3.1` fixes the problem.

**To Reproduce**

Import anything from azure-storage-file-datalake and run latest mypy againts it.

**Expected behavior**

I expect no mypy errors using your library.

**Comment by friggog** [comment]
Also:
incorrect type signatre https://github.com/Azure/azure-sdk-for-python/blob/b37aa446b84dce030f4c1bfb9e84e9d6867d7beb/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py#L23-L24 and https://github.com/Azure/azure-sdk-for-python/blob/b37aa446b84dce030f4c1bfb9e84e9d6867d7beb/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py#L108-L109

And duplicate definition https://github.com/Azure/azure-sdk-for-python/blob/b37aa446b84dce030f4c1bfb9e84e9d6867d7beb/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py#L686-L690

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by dciborow** [comment]
causing issues in my teams build server... not sure how to surpress.

**Comment by xiafu-msft** [comment]
Hi @dciborow

Thanks for reaching out! We will clean up mypy in the future, for now can you limit the mypy check within your repo, here's the reference and hopefully it is helpful https://mypy.readthedocs.io/en/stable/command_line.html#import-discovery

Let me know if it doesn't work.

**Comment by dciborow** [comment]
@xiafu-msft , i have tried these settings, but none have surprised it.
```
[mypy]
ignore_missing_imports = True
strict_optional = False
follow_imports = silent
no_site_packages = True
```


Which setting are you suggesting?

**Comment by EGrunzke** [comment]
I have created a pull request to address this issue:
https://github.com/Azure/azure-sdk-for-python/pull/20891

**Comment by amishra-dev** [comment]
@tasherif-msft do you know what setting Emily was talking about here?

**Comment by tasherif-msft** [comment]
It has been resolved by the PR referenced above.
