### ISSUE TITLE
Uses unnecessary much CPU in client while waiting for responses

### ISSUE THREAD

**Issue by isj4** [Azure/azure-sdk-for-python#19346]
- **Package Name**: 
azure-eventhub, or possible uamqp.

- **Package Version**: 
python3-azure-eventhub-5.2.0-lp152.2.1.noarch
python3-uamqp-1.2.12-lp152.2.3.1.x86_64

- **Operating System**:
Linux, OpenSUSE, kernel 5.3.18-lp152.66-default

- **Python Version**: 
Python 3.6.12

**Describe the bug**
Simple client that sends one item to an eventhub: create_batch(), batch.add(), client.send_batch(). Whiling waiting for the response the client library performs an inefficient busy-wait with recvfrom() on a non-blocking socket.

In my observation with a response time of 116ms the client library did 4152 calls to recvfrom():
```
10995 1624141418.139150 sendto(3, "\27\3\3\0\232\337`\255\210\360\252\314\332\342\263\20\316\375\265\367\256@\316\351\200(\314\323\271\n\216H"..., 159, 0, NULL, 0) = 159
10995 1624141418.139301 recvfrom(3, 0x7fdf14002bf0, 1024, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
10995 1624141418.139384 recvfrom(3, 0x7fdf14002bf0, 1024, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
10995 1624141418.139447 recvfrom(3, 0x7fdf14002bf0, 1024, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
<ad nauseam>
10995 1624141418.256065 recvfrom(3, 0x7fdf14002bf0, 1024, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
10995 1624141418.256093 recvfrom(3, 0x7fdf14002bf0, 1024, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
10995 1624141418.256130 recvfrom(3, "\27\3\3\0000\0\0\0\0\0\0\0\16\237\371li\372`D\250\"\27,&I\205\177\363\310\3308"..., 1024, 0, NULL, NULL) = 53
```

**To Reproduce**
1. Use a simple client, the sample code at https://docs.microsoft.com/en-us/python/api/overview/azure/eventhub-readme?view=azure-python "Publish events to an Event Hub" works fine for this purpose.
2. Send batch to an eventhub that is NOT physically nearby, requiring speed-of-light latency of at least 40-100ms. Inter-continental communication is ideal for reproduction of this issue.
3. Observe client CPU use while waiting for response
4. Or: use `strace` to see what it's doing

**Expected behavior**
I expected the client to do an efficient blocking recvfrom() or a poll/select/epoll instead of a busy-wait.

**Screenshots**
From `htop` - while tracking down the excessive CPU use I added OS thread names so I could see which one was doing it. "evhub-sender" is purely sending to eventhub.

![image](https://user-images.githubusercontent.com/12530623/122680465-9c9f3300-d1ef-11eb-83e1-07f7c9bb2321.png)

**Additional context**
In a production program that sends ~1600 items in ~250 batches over a minute the CPU use is 38-50% in the thread that sends to eventhub. The other threads that deal with amqp 0.9 (rabbitmq) and more computational intensive operations use less than 0.9% CPU.

**Comment by yunhaoling** [comment]
hey @isj4 , thanks for reaching out and the efforts you have put into investigating the issue.

Sorry about the trouble that the library is causing and your understanding is correct, the high CPU usage origins from the implementation of the underlying uamqp library.
I could give more context for the reason of high CPU usage (which I have replied in another [issue](https://github.com/Azure/azure-sdk-for-python/issues/16991)):

>  - The sync implementation is based on the pulling mode -- within the sdk when send is called, there is while loop keeps calling underlying amqp connection to dowork (send and receive data) and checking if all the messages are being sent. Once the sending is finished, the send method shall return.
> - This is bound to the implementation of the underlying amqp protocol library (which is pull based) and an expected behavior.

The uamqp itself is a composite of Python and C library, and the socket work takes place in the deep-down C layer and was originally designed on the pulling mode. Our hands get tied here and few things could be done.

We're already considering moving to a pure python AMQP implementation which should give us more control over the socket behavior to save cycles.

Let me know if you have any other questions!

**Comment by isj4** [comment]
I did search for already known issues but the referenced case didn't seem to be the same problem, so I opened this issue. It's good to know that my analysis is correct.

Question: If I use the async interface (as in the example "Publish events to an Event Hub asynchronously") will the high CPU use disappear?

I have not investigated uamqp - only had a brief look at it. In the past I have encountered libraries with similar deficiencies. In one case the library did provide a "minimum wait time" for the "do-IO-work" method. Maybe uamqp does something similar. In another case it was possible to get access to the file descriptor and do a poll() in the application code. Maybe that's possible with uamqp. Just wild ideas that may save you some work.

**Comment by yunhaoling** [comment]
hey @isj4 , the "async" would also encounter the same deficiencies as the underlying pull mode is the same.

the async connection work is basically doing the same thing as the sync one:
``` python
async def connection_dowork():
    while condition:
        c_connection.dowork()
```

compared to sync
```python
def connection_dowork():
    while condition:
        c_connection.dowork()
```



really appreciate your suggestion! I'll keep them in mind when implementing the underlying connection.

**Comment by isj4** [comment]
Ok, thanks for your answer - that saved me time going into a dead end with asynchronous alternative.

**Comment by yunhaoling** [comment]
@isj4 , I'm closing the issue now, feel free to reach out if you have more questions or just reopen the issue.
thanks again for sharing your thoughts with us!
