### ISSUE TITLE
azure video analyzer edge need more samples

### ISSUE THREAD

**Issue by kaushikCanada** [Azure/azure-sdk-for-python#19347]
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/media/azure-media-analytics-edge/samples/sample_lva.py
is so far the only sample. 
some more with events and extensions would be great.
Where do i give the topology url?

the below link is not working.
https://docs.microsoft.com/azure/azure-video-analyzer/video-analyzer-docs/event-based-video-recording-tutorial
found htis in 
https://github.com/Azure/video-analyzer/tree/main/pipelines/live/topologies/evr-hubMessage-video-sink

**Comment by chlowell** [comment]
Thanks for opening this issue, we'll investigate as soon as possible.

**Comment by navba-MSFT** [comment]
This issue is open since Jun 2021. Service attention label has been added already. So removing the CXP attention label from this backlog.

**Comment by xiangyan99** [comment]
Since this was opened two years ago. Could you help to check if this is still valid?

**Comment by kaushikCanada** [comment]
I think this product is not available anymore.
