### ISSUE TITLE
OpenCensus Span creation does not support `kind` keyword used in Distributed Tracing policy

### ISSUE THREAD

**Issue by helsaawy** [Azure/azure-sdk-for-python#19364]
- **Package Name**: `azure.core`, `azure-core-tracing-opencensus`
- **Package Version**: 1.14.0, 1.0.0b7
- **Operating System**: Ubuntu 18.04.5 LTS (Bionic Beaver)
- **Python Version**: Python 3.7.10

**Describe the bug**
`DistributedTracingPolicy` fails with error:
```Unable to start network span: start_span() got an unexpected keyword argument 'kind'```

Policy creates a span using [keyword `kind=`:](https://github.com/Azure/azure-sdk-for-python/blob/0ff2bb65589142ef1bc881d1705a60bdf1d9ae47/sdk/core/azure-core/azure/core/pipeline/policies/_distributed_tracing.py#L94)
This is passed [onto `azure.core.tracing.ext.opencensus_span.OpenCensusSpan` , which calls `opencensus.trace.tracer.Tracer.start_span` with that same `kind` keyword argument](https://github.com/Azure/azure-sdk-for-python/blob/0ff2bb65589142ef1bc881d1705a60bdf1d9ae47/sdk/core/azure-core-tracing-opencensus/azure/core/tracing/ext/opencensus_span/__init__.py#L64).
However, that last [`start_span` call does not support the `kind` argument](https://github.com/census-instrumentation/opencensus-python/blob/e2cb2af425de9b2c1f86f4a6d0777131091f65b0/opencensus/trace/tracer.py#L106)

**To Reproduce**
1.  set `AZURE_TRACING_ENABLED=TRUE`  and `AZURE_SDK_TRACING_IMPLEMENTATION=OPENCENSUS` environment variables
2. import opencensus
3. create an azure resource

**Expected behavior**
Traces to be created and exported for ARM calls

**Comment by chlowell** [comment]
Thanks for opening this issue, we'll investigate as soon as possible.

**Comment by rakshith91** [comment]
@helsaawy Thanks for the issue - it'll be fixed in this PR https://github.com/Azure/azure-sdk-for-python/pull/19548
