### ISSUE TITLE
Cannot read UTF-16 encoded messages from a subscription

### ISSUE THREAD

**Issue by cuu508** [Azure/azure-sdk-for-python#19385]
- **Package Name**: azure-servicebus
- **Package Version**: 7.3.0
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.5

**Describe the bug**
Cannot read UTF-16 encoded messages from a subscription. When receiving the message, I get an error message about invalid UTF-8 data (makes sense). If I pass in `encoding="UTF-16" configuration parameter, I get a segmentation fault. Examples below.

**To Reproduce**

```python
with ServiceBusClient.from_connection_string(connstr) as client:
    print("Sending message")
    with client.get_topic_sender(topic_name) as sender:
        sender.send_messages(ServiceBusMessage("Data goes here".encode("utf16")))

    print("Receiving messages")
    with client.get_subscription_receiver(topic_name, subscription_name) as receiver:
        for msg in receiver:
            print(str(msg))
```

Output:

```
Sending message
Receiving messages
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    print(str(msg))
  File "/tmp/sb7/lib/python3.8/site-packages/azure/servicebus/_common/message.py", line 128, in __str__
    return str(self.raw_amqp_message)
  File "/tmp/sb7/lib/python3.8/site-packages/azure/servicebus/amqp/_amqp_message.py", line 156, in __str__
    return str(self._message)
  File "/tmp/sb7/lib/python3.8/site-packages/uamqp/message.py", line 253, in __str__
    return str(self._body)
  File "/tmp/sb7/lib/python3.8/site-packages/uamqp/message.py", line 1130, in __str__
    return "".join(d.decode(self._encoding) for d in self.data)
  File "/tmp/sb7/lib/python3.8/site-packages/uamqp/message.py", line 1130, in <genexpr>
    return "".join(d.decode(self._encoding) for d in self.data)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

I tried passing `encoding="UTF-16"` parameter to `get_subscription_receiver`:

```python
with ServiceBusClient.from_connection_string(connstr) as client:
    print("Sending message")
    with client.get_topic_sender(topic_name) as sender:
        sender.send_messages(ServiceBusMessage("Data goes here".encode("utf16")))

    print("Receiving messages")
    with client.get_subscription_receiver(
        topic_name, subscription_name, encoding="UTF-16"
    ) as receiver:
        for msg in receiver:
            print(str(msg))
```

Output:

```
Sending message
Receiving messages
Segmentation fault
```

**Expected behavior**

I expected the client to either pass raw bytes to the client (without trying to decode them), or to use the encoding I passed in (UTF-16).

**Additional context**

I would prefer to use UTF-8. Unfortunately there are other existing clients that send data encoded as UTF-16. I was previously using `azure-servicebus=0.20.1` which passed the raw bytes to the client. I'm now trying to migrate to 7.3.0 and ran into this.

**Comment by yunhaoling** [comment]
hey @cuu508 , thanks for your feedback.

You could get the raw bytes by the [`body` property](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.html#azure.servicebus.ServiceBusMessage.body) on the message.

If the data of the message you send is only composed of a single string, then you could use the following code snippets to extract the raw bytes:

```python
    with client.get_subscription_receiver(topic_name, subscription_name) as receiver:
        for msg in receiver:
            bytes = list(msg.body)[0]  # msg.body returns a generator of bytes, for message of a single string, generator only yield one time
            # data is the raw bytes, decode raw bytes
```

For `encoding` on `get_subscription_receiver`, it's not supported yet.

We will improve the document and samples on extracting the raw bytes.
Let me know if you have any other questions!

**Comment by cuu508** [comment]
@yunhaoling thanks for the information! I can confirm I could get UTF-16 data decoded like so:

```
    with client.get_subscription_receiver(topic_name, subscription_name) as receiver:
        for msg in receiver:
            raw = bytes().join(msg.body)
            decoded = raw.decode("utf16")

```
