### ISSUE TITLE
azure blob storage ContainerClient exists() sdk authentication issue with sas token

### ISSUE THREAD

**Issue by fanzhe98** [Azure/azure-sdk-for-python#19393]
- **Package Name**: azure.storage.blob
- **Package Version**: 12.8.1
- **Operating System**: ubuntu 20.04
- **Python Version**: 3.8.5

**Describe the bug**
ContainerClient.exists() does not include sas token in authentication header

**To Reproduce**
1. create ContainerClient object using sas key. 
2. call exist method
3. http athentication failure returned.
**Expected behavior**
return true if container exists

**Comment by chlowell** [comment]
Thanks for opening this issue, we'll investigate as soon as possible.

**Comment by fanzhe98** [comment]
> Thanks for opening this issue, we'll investigate as soon as possible.

Thanks, if a quick demo on problem is helpful, please feel free to ping falyu on teams

**Comment by amishra-dev** [comment]
@fanzhe98 Since you are checking for existence of a container, you would need an account SAS. Once you confirm that you used account SAS, we will reach out to you in teams. @xiafu-msft fyi

**Comment by fanzhe98** [comment]
Thanks!  I constructed the ContainerClient via a Container SAS. Then, is there a way to check whether a container SAS input matches to a existed container?

**Comment by tasherif-msft** [comment]
Hi @fanzhe98, unfortunately you do require an account SAS to make a call to `container.exists()`. The exists() method calls get_properties() under the hood and therefore requires at least an account SAS. 

Let us know if you have any further questions, otherwise I can go ahead and close this issue.
