### ISSUE TITLE
update_checkpoint fails intermittently and have no visibility of the error

### ISSUE THREAD

**Issue by NaveenkumarIyappan** [Azure/azure-sdk-for-python#19418]
**Describe the bug**
Few of the calls made to azure blob storage to update checkpoint using update_checkpoint fails.

***Exception or Stack Trace***
The output do not have the exception detail

```
Failed to update checkpoint for partition 18 Exception:
Failed to update checkpoint for partition 20 Exception:
```

**To Reproduce**

```
try:
  await partition_context.update_checkpoint()
except Exception as e:
  error("Failed to update checkpoint for partition {}, Exception: {}".format(partition_context.partition_id, e))
```

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Expect to see why checkpointing fails

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: Python 3.6.6
 - SDK Version: azure-eventhub 1.10.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by chlowell** [comment]
Thanks for opening this issue, we'll investigate as soon as possible.

**Comment by yunhaoling** [comment]
hey @NaveenkumarIyappan , thanks for the feedback.

Could you help on validating whether `str(e)` or `repr(e)` would work for your case?
Also could you kindly provide me with the exception type information that leads to the empty output?
