### ISSUE TITLE
azure.keyvault.secrets begin_delete_secret has invalid type signature

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-sdk-for-python#19411]
- **Package Name**: azure.keyvault.secrets
- **Package Version**: 4.3.0
- **Operating System**: Ubuntu-20.04
- **Python Version**: 3.8.5

**Describe the bug**

The type signature for `begin_delete_secret` states this function returns a `DeletedSecret` instead of a `LROPoller[DeletedSecret]` or `KeyVaultOperationPoller[DeletedSecret]`.

The implementation of the type signature states:
https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py#L296-L297

This disagrees with both the documentation:
https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py#L309

And the implementation:
https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py#L338

**To Reproduce**

The following is invalid according to mypy:
```
client = SecretClient(valut_url=vault_url, credential=DefaultAzureCredential())
client.begin_delete_secret(secret).wait()
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by mccoyp** [comment]
Hi @bmc-msft, thank you for opening this issue! You're completely right that the type signature is incorrect here. It's an old issue that we should have caught -- I'll include this in our work for July's beta releases.

**Comment by YalinLi0312** [comment]
Fixed in [this PR](https://github.com/Azure/azure-sdk-for-python/pull/20507).
