### ISSUE TITLE
BlobClient download failed with " 'NoneType' object has no attribute 'status_code' "

### ISSUE THREAD

**Issue by cmonmouton** [Azure/azure-sdk-for-python#19412]
- **Package Name**:  azure.core
- **Package Version**:  1.13.0
- **Operating System**: Ubuntu-18.04.
- **Python Version**: 3.7

**Describe the bug**
Using the BlobClient, for time to time downloading a blob return a exception which seems to be incorrectly processed, it ends with inability to know what went wrong.

**To Reproduce**
Unfortunately it's very sporadic error.

**Expected behavior**
I would expect be able to catch initial error encountered while downloading the blob.

**Additional context**
Please find the stack trace:
```
  data = await blob_client.download_blob()
  File "/usr/local/lib/python3.7/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 361, in download_blob
    await downloader._setup()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/aio/_download_async.py", line 225, in _setup
    self._response = await self._initial_request()
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/aio/_download_async.py", line 289, in _initial_request
    if self._start_range is None and error.response.status_code == 416:
Exception 'NoneType' object has no attribute 'status_code' 
```

**Comment by chlowell** [comment]
Thanks for opening this issue, we'll investigate as soon as possible.

**Comment by amishra-dev** [comment]
@tasherif-msft can you please look at this?

**Comment by tasherif-msft** [comment]
Hi @cmonmouton, what is the size of the file you're attempting to download?

**Comment by cmonmouton** [comment]
Hi @tasherif-msft , the blob file is a parquet file of ~5MB.

**Comment by xiafu-msft** [comment]
Hi @cmonmouton 
thanks for the info! Can you do pip freeze and check the azure-core version you are using?

**Comment by cmonmouton** [comment]
Hi @xiafu-msft, 
Please find below the result of pip freeze of azure packages:

azure-common==1.1.27
azure-core==1.13.0
azure-datalake-store==0.0.52
azure-identity==1.5.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.2.1
azure-keyvault-keys==4.3.1
azure-keyvault-secrets==4.2.0
**azure-storage-blob==12.6.0**

**Comment by xiafu-msft** [comment]
hi @cmonmouton 
thanks for your reply! can you upgrade you blob to 12.8.1 and see if that still happens?

**Comment by cmonmouton** [comment]
Hi @xiafu-msft, sure I will let you know.
Thanks.

**Comment by cmonmouton** [comment]
Hi @xiafu-msft,
Good news, we didn't see the exception happen for while, even before upgrade to latest version.

Just by curiosity I looked up at the changes on master branch of azure blob storage, there is no change on [faulty line](https://github.com/Azure/azure-sdk-for-python/blob/af456fe75579532bdc9d02f54755137a0f75d1d0/sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py#L300).
And I guess, since response attribute of `[HttpResponseError](https://github.com/Azure/azure-sdk-for-python/blob/af456fe75579532bdc9d02f54755137a0f75d1d0/sdk/core/azure-core/azure/core/exceptions.py#L267)` can be None, even it's unfortunate the error could still happen.

Thanks all, for your replies and your time.
