### ISSUE TITLE
Unify the latest x-ms-version for all services

### ISSUE THREAD

**Issue by xiafu-msft** [Azure/azure-sdk-for-python#19439]
Currently blob, file, queue, datalake have different most recent service version, we should unify them to the same version.
Java and .Net defaults to the latest service version if user didn't specify the service version they want to use.

**Comment by xiangyan99** [comment]
@tasherif-msft is it fixed?

**Comment by tasherif-msft** [comment]
Not yet. We will update this issue once fixed.

**Comment by jalauzon-msft** [comment]
With upcoming STG86 release, we will have unified blob, datalake, and file-share. As per discussion with Sean, not going to update Queue's service version at this time since there are no new features.
