### ISSUE TITLE
[Key Vault] Re-enable nightly tests

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#19470]

**Comment by kurtzeborn** [comment]
@heaths, is this going to blow up our test costs again because of HSM?  If so, can we run this less often?  Say weekly maybe?

Same question/concern over here: https://github.com/Azure/azure-sdk-for-net/issues/22179

**Comment by heaths** [comment]
To be clear, these were disabled because of service performance issues. If cost is a concern, we should probably open a new issue to conditionalize our test matrixes. Hypothetically, with the changes @benbp made for matrix generation we probably could run them on weeklies.

**Comment by heaths** [comment]
On a related note, .NET's "weeklies" are still running both Saturday and Sunday. Shouldn't that just run once? /cc @weshaggard

**Comment by weshaggard** [comment]
Currently we have the weeklies running once on both days, however your correct we probably should only run it ones on one of those days. @benbp do you have an issue for that.

**Comment by benbp** [comment]
@weshaggard Is there a historical reason they run twice, or just a bug? I created https://github.com/Azure/azure-sdk-tools/issues/1766.

**Comment by weshaggard** [comment]
I think we just didn't finish configuring them to correctly bucket across both days.
