### ISSUE TITLE
Incorporate Monitor Query Beta-2 UX study feedback into August (Beta-3)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#19477]
Tracking issue to update the August Release to incorporate the TBD Beta-2 UX Study Feedback
/cc @scottaddie

![image](https://user-images.githubusercontent.com/14154054/125359807-b845b700-e31f-11eb-852f-2d3e33d5895f.png)

- [x] `responses` must be a list in batch response , a type is unnecessary.
- [x] avoid magic strings for aggregation and provide an enum
- [x] `aggragation` param must be plural (it's a list)
- [x] #20011
- [x] Consider a json handler for the response.

Documentation

- [x] the response heirarchy in metrics must be there on the readme
- [x] Authenticate the client heading must be create the client
- [x] In the samples, remove time generated from queries - confusing along with start_time
- [x] Add a section on duration, start and end time, additional_workspaces
- [x] Try using pandas on metrics for time series in samples

Action items from 7/23 meeting:

- [x] Add an "Advanced scenarios" section to the _README_. Within that section, provide a link to the multi-workspace logs query code sample at https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-query/samples/sample_log_query_multiple_workspaces.py.
- [x] Add a logs query response object hierarchy tree to the _README_. - **this will be done along with flattenning**
- [x] Add a metrics query response object hierarchy tree to the _README_. https://github.com/Azure/azure-sdk-for-python/pull/19903
- [x] Rename the __log_query_client.py_ file to __logs_query_client.py_.
- [x] #20015
![image](https://user-images.githubusercontent.com/10702007/126843694-633f5ec5-c1a8-49c5-abc3-808c3bff9c2b.png)
- [x] Add instructions to the _README_ for locating the resource ID. https://github.com/Azure/azure-sdk-for-python/pull/19929

**Comment by rakshith91** [comment]
Closing - created separate issues for which there is no action item currently
