### ISSUE TITLE
Investigate creating a common error type in Azure Core

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-python#19490]
REST API guideline recommends services to return errors in a standard format - https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#errorresponse--object

Investigate creating an error type in Azure Core that all services that return errors in this format can use.

**Comment by lmazuel** [comment]
This is a thing already in azure-core:
https://github.com/Azure/azure-sdk-for-python/blob/2f8f5072e510862dd9f0905a59eba16b53e6d5f6/sdk/core/azure-core/azure/core/exceptions.py#L108

Keeping this issue for testing

**Comment by rakshith91** [comment]
Confirmed OdataV4Error works
