### ISSUE TITLE
[BUG Bash] azure.core.exceptions.ServiceRequestError: Bearer token authentication is not permitted for non-TLS protected (non-https) URLs.

### ISSUE THREAD

**Issue by miyatag** [Azure/azure-sdk-for-python#19521]
**Describe the bug**
CostManagementClient was terminated emitting above error

***Exception or Stack Trace***
```
Traceback (most recent call last):
  File "FetchOwnerCostTimeTrigger/list_cost_tag.py", line 95, in <module>
    resource_cost_list = fetch_resource_cost_for_each_tag()
  File "FetchOwnerCostTimeTrigger/list_cost_tag.py", line 76, in fetch_resource_cost_for_each_tag
    resource_cost_list=cost_management_client.query.usage(scope=f'/subscriptions/{subscription_id}/',parameters=cost_parms)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/mgmt/costmanagement/operations/_query_operations.py", line 109, in usage
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 467, in send
    raise err
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 91, in on_request
    self._enforce_https(request)
  File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 54, in _enforce_https
    raise ServiceRequestError(
azure.core.exceptions.ServiceRequestError: Bearer token authentication is not permitted for non-TLS protected (non-https) URLs.
```

**To Reproduce**
Run this script:
```py
from azure.mgmt.costmanagement import CostManagementClient
from azure.mgmt.resource import SubscriptionClient
from azure.identity import AzureCliCredential
credentials = AzureCliCredential()
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
cost_management_client = CostManagementClient(credentials, subscription_id)
cost_parms = {
        "timeframe": "Custom",
        "type": "ActualCost",
        "dataset": {
            "granularity": "None",
            "grouping": [
                {
                    "type": "TagKey",
                    "name": "Owner"
                }
            ],
            "aggregation": {
                "totalCost": {
                    "name": "Cost",
                    "function": "Sum"
                }
            }
        },
        "include": [
            "Tags"
        ],
        "timePeriod": {
            "from": "2021-06-01T00:00:00+00:00",
            "to": "2021-06-07T23:59:59+00:00"
        }
    }
resource_cost_list=cost_management_client.query.usage(scope=f'/subscriptions/{subscription_id}/',parameters=cost_parms)
```

**Expected behavior**
```
{
  "id": "***"
  "name": "***"
  "type": "Microsoft.CostManagement/query",
  "location": null,
  "sku": null,
  "eTag": null,
  "properties": {
    "nextLink": null,
    "columns": [
      {
        "name": "Cost",
        "type": "Number"
      },
      {
        "name": "TagKey",
        "type": "String"
      },
      {
        "name": "TagValue",
        "type": "String"
      },
      {
        "name": "Currency",
        "type": "String"
      }
    ],
    "rows": [
      [
        0,
        "owner",
        "ABC",
        "JPY"
      ],
      [
        0.011316415544999993,
        "owner",
        "DEF",
        "JPY"
      ],
    ]
  }
}
```
 same as [Query web sample](https://docs.microsoft.com/en-us/rest/api/cost-management/query/usage#code-try-0)

**Setup (please complete the following information):**
 - Python Version: 3.8.2
 SDK Version:  
 - azure-core==1.15.0
 - azure-identity==1.6.0
 - azure-mgmt-core==1.2.2
 - azure-mgmt-costmanagement==2.0.0
 - azure-mgmt-resource-18.0.0

**Additional context**
* I got a expected data when I used curl command or request.post(bellow)
```py
response = requests.post(f'https://management.azure.com/subscriptions/{subscription_id}/providers/Microsoft.CostManagement/query', headers=headers, params=params, data=json.dumps(cost_parms))
```
* I  confirmed that below code works. Therefore, I thought I could get the right credentials and subscription_id.
I think there is a problem in CostManagementClient.
```py
credentials = AzureCliCredential()
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
resource_client = ResourceManagementClient(credentials, subscription_id)
resource_list = resource_client.resources.list(
   expand = "createdTime,changedTime",
)
for resource in list(resource_list):
   print(resource)
```

**Information Checklist**
- [ ○ ] Bug Description Added
- [ ○ ] Repro Steps Added
- [ ○ ] Setup information Added

**Comment by miyatag** [comment]
I was able to get the data. subscription_id was not necessary for  using CostManagementClient.

```py
cost_management_client = CostManagementClient(credentials)
```
[docs.microsoft.com](https://docs.microsoft.com/ja-jp/python/api/azure-mgmt-costmanagement/azure.mgmt.costmanagement.costmanagementclient?view=azure-python)
[refer URL](https://github.com/Azure/azure-sdk-for-python/issues/19168)

**Comment by juvenalprestegui** [comment]
> **Describe the bug**
> 
> CostManagementClient was terminated emitting above error
> 
> 
> 
> ***Exception or Stack Trace***
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "FetchOwnerCostTimeTrigger/list_cost_tag.py", line 95, in <module>
> 
>     resource_cost_list = fetch_resource_cost_for_each_tag()
> 
>   File "FetchOwnerCostTimeTrigger/list_cost_tag.py", line 76, in fetch_resource_cost_for_each_tag
> 
>     resource_cost_list=cost_management_client.query.usage(scope=f'/subscriptions/{subscription_id}/',parameters=cost_parms)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/mgmt/costmanagement/operations/_query_operations.py", line 109, in usage
> 
>     pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
> 
>     return first_node.send(pipeline_request)  # type: ignore
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
> 
>     response = self.next.send(request)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
> 
>     response = self.next.send(request)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
> 
>     response = self.next.send(request)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
> 
>     response = self.next.send(request)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
> 
>     response = self.next.send(request)
> 
>   [Previous line repeated 1 more time]
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
> 
>     response = self.next.send(request)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 467, in send
> 
>     raise err
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
> 
>     response = self.next.send(request)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
> 
>     self.on_request(request)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 91, in on_request
> 
>     self._enforce_https(request)
> 
>   File "/Users/*****/.pyenv/versions/3.8.2/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 54, in _enforce_https
> 
>     raise ServiceRequestError(
> 
> azure.core.exceptions.ServiceRequestError: Bearer token authentication is not permitted for non-TLS protected (non-https) URLs.
> 
> ```
> 
> 
> 
> **To Reproduce**
> 
> Run this script:
> 
> ```py
> 
> from azure.mgmt.costmanagement import CostManagementClient
> 
> from azure.mgmt.resource import SubscriptionClient
> 
> from azure.identity import AzureCliCredential
> 
> credentials = AzureCliCredential()
> 
> subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
> 
> cost_management_client = CostManagementClient(credentials, subscription_id)
> 
> cost_parms = {
> 
>         "timeframe": "Custom",
> 
>         "type": "ActualCost",
> 
>         "dataset": {
> 
>             "granularity": "None",
> 
>             "grouping": [
> 
>                 {
> 
>                     "type": "TagKey",
> 
>                     "name": "Owner"
> 
>                 }
> 
>             ],
> 
>             "aggregation": {
> 
>                 "totalCost": {
> 
>                     "name": "Cost",
> 
>                     "function": "Sum"
> 
>                 }
> 
>             }
> 
>         },
> 
>         "include": [
> 
>             "Tags"
> 
>         ],
> 
>         "timePeriod": {
> 
>             "from": "2021-06-01T00:00:00+00:00",
> 
>             "to": "2021-06-07T23:59:59+00:00"
> 
>         }
> 
>     }
> 
> resource_cost_list=cost_management_client.query.usage(scope=f'/subscriptions/{subscription_id}/',parameters=cost_parms)
> 
> ```
> 
> 
> 
> 
> 
> **Expected behavior**
> 
> ```
> 
> {
> 
>   "id": "***"
> 
>   "name": "***"
> 
>   "type": "Microsoft.CostManagement/query",
> 
>   "location": null,
> 
>   "sku": null,
> 
>   "eTag": null,
> 
>   "properties": {
> 
>     "nextLink": null,
> 
>     "columns": [
> 
>       {
> 
>         "name": "Cost",
> 
>         "type": "Number"
> 
>       },
> 
>       {
> 
>         "name": "TagKey",
> 
>         "type": "String"
> 
>       },
> 
>       {
> 
>         "name": "TagValue",
> 
>         "type": "String"
> 
>       },
> 
>       {
> 
>         "name": "Currency",
> 
>         "type": "String"
> 
>       }
> 
>     ],
> 
>     "rows": [
> 
>       [
> 
>         0,
> 
>         "owner",
> 
>         "ABC",
> 
>         "JPY"
> 
>       ],
> 
>       [
> 
>         0.011316415544999993,
> 
>         "owner",
> 
>         "DEF",
> 
>         "JPY"
> 
>       ],
> 
>     ]
> 
>   }
> 
> }
> 
> ```
> 
>  same as [Query web sample](https://docs.microsoft.com/en-us/rest/api/cost-management/query/usage#code-try-0)
> 
> 
> 
> 
> 
> **Setup (please complete the following information):**
> 
>  - Python Version: 3.8.2
> 
>  SDK Version:  
> 
>  - azure-core==1.15.0
> 
>  - azure-identity==1.6.0
> 
>  - azure-mgmt-core==1.2.2
> 
>  - azure-mgmt-costmanagement==2.0.0
> 
>  - azure-mgmt-resource-18.0.0
> 
> 
> 
> **Additional context**
> 
> * I got a expected data when I used curl command or request.post(bellow)
> 
> ```py
> 
> response = requests.post(f'https://management.azure.com/subscriptions/{subscription_id}/providers/Microsoft.CostManagement/query', headers=headers, params=params, data=json.dumps(cost_parms))
> 
> ```
> 
> * I  confirmed that below code works. Therefore, I thought I could get the right credentials and subscription_id.
> 
> I think there is a problem in CostManagementClient.
> 
> ```py
> 
> credentials = AzureCliCredential()
> 
> subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
> 
> resource_client = ResourceManagementClient(credentials, subscription_id)
> 
> resource_list = resource_client.resources.list(
> 
>    expand = "createdTime,changedTime",
> 
> )
> 
> for resource in list(resource_list):
> 
>    print(resource)
> 
> ```
> 
> 
> 
> **Information Checklist**
> 
> - [ ○ ] Bug Description Added
> 
> - [ ○ ] Repro Steps Added
> 
> - [ ○ ] Setup information Added
