### ISSUE TITLE
delete_blob arguments are of wrong type

### ISSUE THREAD

**Issue by jasonverhaeghe** [Azure/azure-sdk-for-python#19543]
delete_blob(blob, delete_snapshots=None, **kwargs)

delete_snapshots is boolean 
add an example of kwargs would be better

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37584723-65eb-0794-8ec5-fcae40b28717
* Version Independent ID: 21d8c29d-77a6-6743-25b2-1cbf855e37a3
* Content: [azure.storage.blob.ContainerClient class](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.ContainerClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-storage-blob/azure.storage.blob.ContainerClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by tasherif-msft** [comment]
Hi @jasonverhaeghe its a string since you can pass `only` or `include`.
Setting to False or None just ignores deleting snapshots
