### ISSUE TITLE
Which blob's response - how to find?

### ISSUE THREAD

**Issue by vivekna** [Azure/azure-sdk-for-python#19542]
part is a list apparently and it is serialized looks like.
for example when i do e.parts., 
    for part in e.parts:
        print (part.message_code)
I can see the status code, but i would also like to know for which blob, how to access this from the response?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 760d993c-fa0e-5b21-4891-3426a57b2878
* Version Independent ID: 1e96bed4-12db-7475-6b2a-380c1a93f881
* Content: [azure.storage.blob.PartialBatchErrorException class](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.partialbatcherrorexception?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.PartialBatchErrorException.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-storage-blob/azure.storage.blob.PartialBatchErrorException.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiafu-msft** [comment]
Hi @vivekna 
Thanks for reaching out.
the subresponses order is the same as the blob order you specified in request, You can map the sub-response to the corresponding blob using its index in the blob list.

**Comment by vivekna** [comment]
Thanks for answering, but could u provide an example.. a bit difficult to understand.
THis is how im currently working : ( a very simplified version for understanding)

try:
    result = container_client.delete_blobs(*blobs_list)
    for item in result:
        print(item.status_code)

except PartialBatchErrorException as e:
    print(e.message)
    print("-----------------------")
    for part in e.parts:
        if (part.status_code == 202):
            print("Blob delete request was accepted.")
        elif (part.status_code == 404):
            print("Blob does not exist. Consider it deleted.")

I tried a part.id or part.blobName etc which did not exist.

**Comment by xiafu-msft** [comment]
Hi @vivekna 

Sorry for the delay of the response!
Here's what you can do:
```
response = container.delete_blobs(
    'blob1',
    'blob2',
    'blob3',
    raise_on_any_failure=False
)
for part in response:
    blob_url = part.request.url

# then you can parse whatever you need
```

let me know if you need any info!
