### ISSUE TITLE
Workspace.get method unintentionally exposes  subscription id when Workspace is not found. 

### ISSUE THREAD

**Issue by Bhanurdra** [Azure/azure-sdk-for-python#19563]
Package Name & Version:
azureml-core==1.31.0
Operating System: Windows
Python Version: 3.8.0

**Describe the bug**
The **get_workspace** method under _commands.py module exposes the users' subscription id when the user tries to validate whether the particular ML Workspace exists under the given resource or not. 
This issue is reproducible in Github Action as well. 

**To Reproduce**
1. Create an account in https://portal.azure.com/
2. Create only a resource group in Azure .
3.  Run following to get the Service Principal details: az ad sp create-for-rbac --name {name} --role contributor --scopes /subscriptions/{subscription id}/resourceGroups/test --sdk-auth
4. Run the following code to check whether the ML Workspace exists under the resource group created in step 2

```
from azureml.core import Workspace
from azureml.core.authentication import ServicePrincipalAuthentication
from azureml.exceptions import ProjectSystemException

auth = ServicePrincipalAuthentication(tenant_id="3XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                                      service_principal_id="9XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                                      service_principal_password="XXX_XXXXXXXXXXXXXX_XXXXX~XX~XXXXXX",
                                      cloud='AzureCloud')
try:
    work_space = Workspace.get(auth=auth,
                               subscription_id="3XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                               resource_group="test",
                               name="test-github",
                               location="eastus2",
                               cloud="AzureCloud")
except ProjectSystemException as exception:
    print(f"Error: {exception}")
```

**Expected behavior**
I have created resource group named "test". 
Since ML Workspace isn't created using above mentioned steps, it is expected to be  throwing  ProjectSystemException error alone. 

**Actual behavior**
It throws ProjectSystemException error along with get_workspace method error exposing the subscription id. Please refer the screenshot below.

**Screenshots**
From local system 

![image](https://user-images.githubusercontent.com/63955656/123739251-f1177200-d8c3-11eb-9a7e-32beefb5a920.png)

From Github Action Log

![image](https://user-images.githubusercontent.com/63955656/123739422-42276600-d8c4-11eb-8dbb-e67b05306b79.png)

Let me know if any additional details are required from my end. 

Thanks 
Bhanu

**Comment by luigiw** [comment]
Closing legacy issue.

Please consider upgrading to AzureML v2 CLI/SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2
