### ISSUE TITLE
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Forbidden'

### ISSUE THREAD

**Issue by aledaros** [Azure/azure-sdk-for-python#19597]
What could be causing this error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79dc9f6e-d128-4ef9-322e-2f33f570e012
* Version Independent ID: d99ed8d4-0977-e6a0-230e-bd3f2738bd2e
* Content: [azure.identity.CertificateCredential class](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.certificatecredential?view=azure-python)
* Content Source: [docs-ref-autogen/azure-identity/azure.identity.CertificateCredential.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-identity/azure.identity.CertificateCredential.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by chlowell** [comment]
403 Forbidden usually means the service rejected your request because the authenticated principal isn't authorized to perform the requested action. Can you please share more detail about the error you're seeing, like a code snippet and stack trace?
