### ISSUE TITLE
Issue in mounting ADLS Gen 2 storage on Azure Batch pool

### ISSUE THREAD

**Issue by htejwani** [Azure/azure-sdk-for-python#19599]
[Enter feedback here]

Via the python client SDK for Azure Batch, when I mount and ADLS Gen2 enabled storage, some file system operations like rename do not work. So I added '-o use-adls=true ' to the 'blobfuse_options' parameter. But this causes the node on Azure Batch to fail at startup. The error says that it cannot mount the container due to permission issues. Please refer the code snippet below for mount configuration.

```
azure_blobfile_sys_config = batch.models.AzureBlobFileSystemConfiguration(
      account_name=settings.BATCH_CONFIG['_STORAGE_ACCOUNT_NAME'], 
      container_name = settings.BATCH_CONFIG['_STORAGE_CONTAINER_NAME'], 
      relative_mount_path = settings.BATCH_CONFIG['_RELATIVE_MOUNT_PATH'],
      account_key = settings.BATCH_CONFIG['_STORAGE_ACCOUNT_KEY'],
      blobfuse_options = '-o use-adls=true -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 -o allow_other')
```

When I remove the '-o use-adls=true' option, the node does start but the mount is not compatible with ADLS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e43a649a-9137-62c7-298f-6bfb1119a313
* Version Independent ID: d681d121-7988-e6cd-8efe-b5e30275dee7
* Content: [azure.batch.models.AzureBlobFileSystemConfiguration class](https://docs.microsoft.com/en-us/python/api/azure-batch/azure.batch.models.azureblobfilesystemconfiguration?view=azure-python)
* Content Source: [docs-ref-autogen/azure-batch/azure.batch.models.AzureBlobFileSystemConfiguration.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-batch/azure.batch.models.AzureBlobFileSystemConfiguration.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by NaraVen** [comment]
--use-adls=true is a blobfuse param, it is not a fuse option. Using it with the -o option is not going to work.  The python batch team team needs to accept a param for use-adls.

**Comment by kristapratico** [comment]
Hi, thanks for your question. We'll investigate and report back.

**Comment by navba-MSFT** [comment]
@htejwani Apologies for the delay in response. This is a quick follow-up email to check if you are still seeing this issue. While we are waiting for the reply from @cRui861 and @paterasMSFT, Could you try using the [accountType=adls](https://github.com/Azure/azure-storage-fuse#config-file-options) config option and let us know if that helps ?

**Comment by navba-MSFT** [comment]
@htejwani Could you please let us know if you had a chance to look at my above comment and try that action plan ? Please test and get back to us. Awaiting your reply.

**Comment by htejwani** [comment]
I think I don't have the means to check this now. I am in a completely
different work setup. Sorry about that.

**Comment by navba-MSFT** [comment]
@htejwani Thanks for getting back. Please feel free to reopen this github thread in future if you need any further assistance.
