### ISSUE TITLE
consumption SDK usage_details.list does not filter by date

### ISSUE THREAD

**Issue by izilic333** [Azure/azure-sdk-for-python#19600]
- **Package Name**: https://github.com/Azure/azure-sdk-for-python/tree/fd643a07a08f5ae912344c45f91ecd7278e9049b/sdk/consumption/azure-mgmt-consumption
- **Package Version**: 3.0.0, 8.0.0b1, 8.0.0
- **Operating System**: linux (ubuntu)
- **Python Version**: 3.8.10

**Describe the bug**
We are developing a new feature and we use the Azure SDK Consumption client to fetch data from azure.

**To Reproduce**

```
from azure.mgmt.consumption import ConsumptionManagementClient

from azure.identity import ClientSecretCredential

credential = ClientSecretCredential(tenant_id=account_number, client_id=access_key, client_secret=secret)

subscription_id = "some_subscription_id"

consumption_client = ConsumptionManagementClient(credential, subscription_id)
date_filter = "properties/usageStart ge '2021-05-01' AND properties/usageStart lt '2021-02-27'"
data_list = consumption_client.usage_details.list(scope='/subscriptions/subscription_id', filter=date_filter)
data = [item.as_dict() for item in data_list]

print(data)

```

if we use the filter from the azure consumption SDK test: 
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/consumption/azure-mgmt-consumption/tests/test_mgmt_consumption.py

for example:
endDate = '2021-05-28T00:00:00Z'
date_filter ='usageEnd le '+ str(endDate)
following this example:
![Selection_110](https://user-images.githubusercontent.com/86722924/123966008-4bdcc680-d9b5-11eb-89b6-4473ccddd4a2.png)

and after that, the same thing, we don't get results for the required period, instead, we get everything for June.

These DateTime filters do not work on azure python SDK Consumption client and usage_details.list()

**Expected behavior**
I expected the results to only return usage items where date_property matched the date filter. Instead, I get everything for June 
(I guess always returns everything for the current month, and the consumption client seems to simply ignore the DateTime range filters).

**Screenshots**

![Selection_109](https://user-images.githubusercontent.com/86722924/123965439-bfca9f00-d9b4-11eb-8624-b456f0cdd119.png)

**Additional context**

**Comment by kristapratico** [comment]
Thanks for your feedback, we'll investigate asap.

**Comment by conzyor34** [comment]
Here is one way you can monkey patch the client to work around this omission in the SDK. Is there a better workaround?

```
  filter_date = "2021-08-01"

  # Monkey patch client to include startDate and endDate in URL

  url_parts = list(urlparse.urlparse(client.usage_details.list.metadata['url']))
  query = {"startDate": filter_date, "endDate": filter_date}
  url_parts[4] = urlencode(query)
  client.usage_details.list.metadata['url'] = urlparse.urlunparse(url_parts)
```

The above example will retrieve one day's worth of records for 2021-08-01.

**Comment by mpremus** [comment]
> Here is one way you can monkey patch the client to work around this omission in the SDK. Is there a better workaround?
> 
> ```
>   filter_date = "2021-08-01"
> 
>   # Monkey patch client to include startDate and endDate in URL
> 
>   url_parts = list(urlparse.urlparse(client.usage_details.list.metadata['url']))
>   query = {"startDate": filter_date, "endDate": filter_date}
>   url_parts[4] = urlencode(query)
>   client.usage_details.list.metadata['url'] = urlparse.urlunparse(url_parts)
> ```
> 
> The above example will retrieve one day's worth of records for 2021-08-01.

Thanks for this monkey patch! With this at least we can use SDK instead of plain API.

**Comment by izilic333** [comment]
Hi, 

Is there any news? 

Maybe there is one more problem here, on this Consumption client and also on this API, 
https://management.azure.com/subscriptions/{}/providers/Microsoft.Consumption/usageDetails/download?startDate={}&endDate={}&api-version=2019-10-01,

 I  get this error for "pay-as-you-go" azure account:

`(400) Billing Period is not supported in (2019-10-01) API Version for Subscription Scope With Web Direct Offer. Please provide the UsageStart and UsageEnd dates in the $filter key as parameters.
Code: 400
Billing Period is not supported in (2019-10-01) API Version for Subscription Scope With Web Direct Offer. Please provide the UsageStart and UsageEnd dates in the $filter key as parameters.
`
So the question is: 

1. is this API and this consumption SDK doesn't work for pay-as-you-go accounts (right now there is BUG for pay-as-you-go accounts)?
2. or there is some API or SDK that is especially for billing costs for pay-as-you-go account types? 
3. currently, there is no API/SDK for billing costs (like the above Consumption client) for this pay-as-you-go account type ?

The Azure documentation for pay-as-you-go is unclear, is there any API/SDK for pay-as-you-go account type, please help!
