### ISSUE TITLE
[ACR] [Before GA] Update cloud configuration API

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-python#19610]
Once the service team has added data plane scopes, we will update our `authentication_scope` kwarg as follows:

- [x] Remove `authentication_scope` kwarg
- [x] Add `audience` (or similarly named) kwarg
- [x] `audience` is an extensible enum, containing the audience strings for known clouds; the user can override with a string if needed
- [x] If `audience` is set, client library will append `/.default` to `audience` value to specify the default scope
- [x] `audience` will default to data-plane scope root, which should be common across clouds [Note: this is not yet available from the service]
- [x] Throw an exception is `audience` is not set and update samples to reflect this

In Python, we will also
- [x] Initially not support `credential_scopes` kwarg
- If we do evenually support the `credential_scopes` kwarg, raise an error if this is different from the scope determined from `audience`

Please see https://github.com/azure/azure-sdk-for-net/issues/21603 for further details.

**Comment by annelo-msft** [comment]
@johanste @lmazuel @schaabs FYI

**Comment by YalinLi0312** [comment]
Fixed.
