### ISSUE TITLE
Aad access token for azure-cosmos 

### ISSUE THREAD

**Issue by Yoni-Mantzur** [Azure/azure-sdk-for-python#19620]
**Is your feature request related to a problem? Please describe.**
We want to use aad access token with the `azure-cosmos` client package which currently (version 4.2.0) seems it's not supported.

**Describe the solution you'd like**
As other clients in this sdk offers (blob, queue, eventhub), the ability to use aad access token to connect with cosmos client.
In addition, specific db permission will be great (as done in sql server).

**Describe alternatives you've considered**
Create a direct REST API call, which is already [GA](https://docs.microsoft.com/en-gb/azure/cosmos-db/how-to-setup-rbac#authenticate-requests-on-the-rest-api).

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll check on this and get back to you with an answer.

**Comment by Rodrigossz** [comment]
This is a known limitation that currently isn't in roadmap. Please click [here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cosmos/azure-cosmos#security-limitations) to check limitations and workarounds.
