### ISSUE TITLE
Metrics definition for MySQL.

### ISSUE THREAD

**Issue by CMLL** [Azure/azure-sdk-for-python#1964]
I'm trying to retrieve the metrics definition from the Azure Database for MySQL service, the same way that I'm retrieving the SQL Server ones, but while the first ones give the definitions correctly, the second doesn't return anything in the response.

I'm retrieving the definitions by doing...

```
MonitorManagementClient(sp, sub_id).metric_definitions.list(resource_id)
```

Both resource ids seem to be fine and have the same format...
```
/subscriptions/XXX-XXXX-XXXX/resourceGroups/cloud-shell-storage-eastus/providers/Microsoft.DBforMySQL/servers/<servername>/databases/<dbname>
```
```
/subscriptions/XXXX-XXXX-XXXX-XXXX/resourceGroups/cloud-shell-storage-eastus/providers/Microsoft.Sql/servers/<servername>/databases/<dbname>
```
If I check the Azure portal I can see the metrics being available and reporting. Could this be an incomplete portion of the Api, missing documention, or an overlook on my part?

Thanks in advance.

**Comment by lmazuel** [comment]
Hi @CMLL 
Metrics implementation is done by the RP team, meaning that even if your thinking is natural, `Microsoft.Sql` and `Microsoft.DBforMySQL` might not provide the same metrics.
You can check live using the `metrics_definitions` operation group:
https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring?view=azure-python
```
# You can get the available metrics of this specific resource
for metric in client.metric_definitions.list(resource_id):
    # azure.monitor.models.MetricDefinition
    print("{}: id={}, unit={}".format(
        metric.name.localized_value,
        metric.name.value,
        metric.unit
    ))
```
This way you can compare what is available.
Also, the official list is available here:
https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics

If you feel there is missing metrics in `Microsoft.DBforMySQL`, please reply to this issue and I will forward to the team for more details.
Thank you,

**Comment by CMLL** [comment]
Thanks for the information. Yeah, I was expecting certain metrics to be available at database level but I see that they are simply not there. Those links you passed me are extremely useful.
