### ISSUE TITLE
Support Azure Automation Managed Identity in Hybrid Worker scenario

### ISSUE THREAD

**Issue by maxilampert** [Azure/azure-sdk-for-python#19641]
**Is your feature request related to a problem? Please describe.**
Azure Automation supports managed Identity since 2-3 months [Azure Automation Managed Identity](https://docs.microsoft.com/en-us/azure/automation/enable-managed-identity-for-automation)

When using a hybrid worker the identity enabled on the automation account is forwarded to the hybrid worker and can be used in the runbook. The hybrid worker is setting MSI_SECRET and MSI_ENDPOINT to an endpoint from Azure Automation to retrieve the token.
Currently the azure.identity package can not handle this case because the returned token "expires_on" field is formatted differently then expected by the App Service identity functions.

This is the retuned error message:
`File "/usr/local/lib/python3.8/dist-packages/azure/identity/_credentials/app_service.py", line 112, in _parse_app_service_expires_on`

`ValueError: '2021-07-02 08:00:34Z' doesn't match the expected format`

**Describe the solution you'd like**
There are probably two ways this could be fixed, either by supporting this additional format in the azure.identity App Service package or that the Azure Automation team adjusts there endpoint to return the same date format as App Services do.

**Describe alternatives you've considered**
The current workaround that works for me is to delete the MSI_Endpoint environment variable to skip the AppService identity checks and fallback using the metadata service from the VM with the managed identity that the VM provides.

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate and report back.

**Comment by jaspkaur28** [comment]
@maxilampert  : Thanks for the feedback. Automation team has addressed the issue by fixing the "expires_on" field formatting. We've tested it for Pwsh as well as Py. The fix will be deployed to all regions in 4 weeks.

**Comment by jaspkaur28** [comment]
Closing the issue since there is no further activity on this thread.
