### ISSUE TITLE
async Eventhub listener along with checkpointing creates an epoch listener when owner_level is None

### ISSUE THREAD

**Issue by chinmaydorlikar** [Azure/azure-sdk-for-python#19657]
- **Package Name**: azure-eventhub 
- **Package Version**: 5.2.0
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.6.9

**Describe the bug**
I am creating an async Eventhub listener along with checkpointing and when the **owner_level** arg is set to None (default), the receiver created actually has an epoch value of **0**.

**To Reproduce**
1. Create a listener w/o checkpointing for the same Eventhub and same consumer group.
2. Create an Eventhub listener using the code specified [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/receive_events_using_checkpoint_store_async.py)
3. The first listener will pause as a result of the second listener since the first one is a non-epoch listener and the second one is an epoch listener.

**Expected behavior**
A consumer group allows up to 5 non-epoch listeners however, only one exclusive epoch listener is allowed. I was expecting **owner_level=None** to allow the listener to be created as non-epoch listeners but that is not the case.

**Error log**
Description: b"At least one receiver for the endpoint is created with epoch of '0', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected.

**Additional context**
I have a use case where I want multiple non-epoch listeners along with checkpointing using different blob containers for a single Eventhub string and consumer group. So basically, each listener stores the checkpoints in a separate container while listening to the same stream of events. Is there a better way to achieve this?

**Comment by kristapratico** [comment]
Thanks for your question, we'll investigate asap.

**Comment by yunhaoling** [comment]
hey @chinmaydorlikar , this is a by-design behavior that when EventHubConsumer is integrated with a CheckpointStore while no owner_level is provided, the SDK would default the `owner_level` to 0 to create an exclusive listener to a partition.

Implementation detail could be found [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/event_processor.py#L105-L106)

The major reason behind the design is that the checkpoint should be consistent and in order so that in the case of failure recovery, the consumer could resume from the position where it failed. If we allow multiple receivers receiving and doing checkpointing for the same partition, then checkpoint would be inconsistent and out of order -- the consumer would either consume duplicate events that have been handled or miss events that haven't been handle yet because of the inconsistent checkpoint.

I hope this answers the question you raised. And I admit that we should improve the documentation to illustrate the behavior.

Please let me know if you have any other questions!

**Comment by chinmaydorlikar** [comment]
Hi, thanks for the explanation. Although I do agree with what you said, I think there is a workaround.
So, if we have multiple listeners using the same blob container, then sure, we will have a consistency issue that needs to be addressed.
But what I am asking is what if we have multiple listeners, each having a separate container to store the checkpoint in? We cannot have consistency issues in that case. Each listener will store the ownership in a separate container.

And as far as the default value is concerned, if no value is provided then sure set the owner_level to 0. But this explicit provision of owner_level=None should mean more than that. With no owner_level set, we should not consider epoch listener. The documentation defines epoch listeners taking ownership of a partition. So, no ownership should mean no epoch listeners.

And this can be implemented without reinventing the wheel, we can adjust that in the current design which you've mentioned.
Please let me know your thoughts on this.

**Comment by yunhaoling** [comment]
thanks for putting your thoughts!

apologize that I should give you more context on the design of the EventHubConsumer with Checkpoitnstore.

With the checkpointstore provided, EventHubConsumer will do load balancing among different nodes -- each consumer will take ownership of a set of partitions to receive from against a certain consumer group.

The key purpose of the checkpointstore and load balancing is to avoid duplicate message handling, and to achieve that, the SDK is depending on the epoch listener feature provided by the service to guarantee that one partition is handled by only one consumer at a time.

So let's say there is an event hub of 32 partitions, and there're 4 consumers running on 4 different nodes (docker container, virtual machine etc.). Each consumer will communicate with the checkpoint store to know what the existence of other consumers and start claiming partitions for processing, and finally when load balancing process gets stable, each consumer would take ownership of 8 partitions no overlapping (partition count / consumer count).
 
If the owner_level is allowed to set to None in this case, the 4 consumers would be duplicate handling some of the partitions which goes against the initial purpose.

I'm afraid that we could not make the change as it would be a **behavior breaking change** to the existing users that is not allowed.

May I ask what's your scenario that makes you want to have multiple receivers with multiple checkpointstore? I feel that [`consumer group`](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features#consumer-groups) is the thing that you could take advantage of for organizing receiving with multiple checkpointstore. Each consumer group could live with its own checkpointstore.

Any thoughts?

**Comment by chinmaydorlikar** [comment]
Thank you for that detailed explanation!

Actually, the 32 partitions and  4 consumers scenario does make sense. Having owner_level None would break things in that case. 
The scenario I am working on did allow me to have multiple consumer groups for some reason. So, I was trying to understand the possible workaround and hence I was trying to bend my way to get it working. But I get your point, consumer group is my only solution here and in fact, is easier to implement.
So I am closing this issue. Again, thank you for your response.

**Comment by chinmaydorlikar** [comment]
Thank you for that detailed explanation!

Actually, the 32 partitions and  4 consumers scenario does make sense. Having owner_level None would break things in that case. 
The scenario I am working on did allow me to have multiple consumer groups for some reason. So, I was trying to understand the possible workaround and hence I was trying to bend my way to get it working. But I get your point, consumer group is my only solution here and in fact, is easier to implement.
So I am closing this issue. Again, thank you for your response.
