### ISSUE TITLE
Retrieve output (stdout, stderr) of VM custom script extension

### ISSUE THREAD

**Issue by jackmuskopf** [Azure/azure-sdk-for-python#19651]
**Is your feature request related to a problem? Please describe.**
I cannot find the output of the custom script extension via Python sdk.

**Describe the solution you'd like**
A method for loading the stdout/stderr of a custom script extension (given the VirtualMachineExtension object).

**Describe alternatives you've considered**
It already exists, and I cannot find the documentation for it?

**Additional context**
I recently found this class:
https://docs.microsoft.com/en-in/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.models.virtualmachineextensioninstanceview?view=azure-python

I can do
```
 extension = compute_client.virtual_machine_extensions.get(
    resource_group_name=rg_name,
    vm_name=vm_name,
    vm_extension_name='HelloWorld'
 )
```
But
`extension.instance_view is None`

**Comment by kristapratico** [comment]
Thank you for your question, we'll investigate asap.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by axelgMS** [comment]
Not a Python expert, but what do you get if you do something like:

    _exts = ComputeManagementClient.virtual_machine_extensions.get(GROUP_NAME, VM_NAME, 'CSEOK', expand='instanceView')

    # need to check the detailed status of the extension for the script final result.
    print("Result: ", exts.instance_view.statuses[0].code)
    print("Result: ", exts.instance_view.statuses[0].display_status)
    print("Result: ", exts.instance_view.statuses[0].message)

    # If polled we need to get until ProvisioningState is failed or succeeded and possibly confirm with the output on substatuses
    print("Result: ", exts.instance_view.substatuses[0].code) # Output
    print("Result: ", exts.instance_view.substatuses[0].display_status)
    print("Result: ", exts.instance_view.substatuses[0].message)_

**Comment by jackmuskopf** [comment]
Awesome, thank you @axelgMS ! I see the expand parameter listed here: [azure python sdk docs](https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_03_01.operations.virtualmachineextensionsoperations?view=azure-python#get-resource-group-name--vm-name--vm-extension-name--expand-none----kwargs-)

Where can a list of valid expand expressions be found?

**Comment by amjads1** [comment]
@jackmuskopf Apologies for the delay response but here's the reference: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-extensions/get

Let me know if you have any further questions or need any additional help otherwise I can go ahead and close this issue.

**Comment by jackmuskopf** [comment]
Thank you!
