### ISSUE TITLE
[BUG Bash] Parameter 'cluster_arm_id' not respected 

### ISSUE THREAD

**Issue by bogdanioanliviu** [Azure/azure-sdk-for-python#19666]
**Describe the bug**
Parameter 'cluster_arm_id' not respected when used to add Namespace to cluster.

***Exception or Stack Trace***
No exception.

**To Reproduce**
Use the following :
`client_eh.namespaces.begin_create_or_update(
          resource_group_name=resource_group_name, 
          namespace_name='some_name',
          parameters={
            'location' : 'West Europe',
            'tags': {
              'ServiceVersion': 'value',
              'BusinessUnit': 'value'
            },
            'sku': {
              'name': 'Standard',
              'tier': 'Standard',
              'capacity': 1
            },
            'is_auto_inflate_enabled': False,
            'maximum_throughput_units': 0,
            'kafka_enabled': True,
            'identity': {
              'principal_id': objectid,
              'tenant_id': AZURE_TENANT_ID,
              'type': 'SystemAssigned'
            },
            'cluster_arm_id': '/subscriptions/' + subscription_ID + '/resourceGroups/' + resource_group_name + '/providers/Microsoft.EventHub/clusters/' + cluster_name
          }
        )`

***Code Snippet***
Please see up .

**Expected behavior**
Event Hub Namespace created or updated in a cluster.

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.9.4]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ ] Repro Steps Added
- [x ] Setup information Added

**Comment by kristapratico** [comment]
Thanks for your feedback, we'll investigate asap.

**Comment by bogdanioanliviu** [comment]
Hello do we have some update ? Can you reproduce this ?

**Comment by msyyc** [comment]
@RAY-316 Please help on the issue

**Comment by talalhaddad** [comment]
@kristapratico i worked with the customer and we solved the issue, the namespace was created as a standard namespace and then updated to be added under the cluster.

Namespace should be created under the cluster and then we can update as needed.

i think its a good idea to add some kind of validation to the begin_create_or_update to check if the namespace is being updated and its not under a cluster, and the cluster ARM ID is provided to fail/show a warning.

Customer confirmed we can archive this issue as resolved.

**Comment by kristapratico** [comment]
Thanks @talalhaddad!
