### ISSUE TITLE
Error responses from certain operations do not conform to ODataV4

### ISSUE THREAD

**Issue by fhoy** [Azure/azure-sdk-for-python#19665]
- **Package Name**: azure-mgmt-web
- **Package Version**: 2.0.0
- **Operating System**: n/a
- **Python Version**: n/a

**Describe the bug**
Certain server-side failures produce error responses that do not conform to ODataV4, which means that the standard handling drops error details.

To my understanding, the [OData section on error handling](http://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_ErrorHandling) requires keys (`code`, `message`, etc.) to be lower-case, and the [SDK code that parses error responses](https://github.com/Azure/azure-sdk-for-python/blob/82e85814a6cda02fe374e57ad1d34da281cfd514/sdk/core/azure-core/azure/core/exceptions.py#L135) is implemented as such. However, in certain situations, we have observed the error responses to return title-cased keys (`Code`, `Message`, etc.), which causes the parsing code to raise a `ValueError`. A specific example is the following, that was returned when a call to `web_apps.create_or_update_swift_virtual_network_connection()` (using the default API-version, 2020-09-01), resulted in a `409 Conflict`:

```
{"Code":"Conflict","Message":"Subnet X in VNET Y is already occupied by service S.","Target":null,"Details":[{"Message":"Subnet X in VNET Y is already occupied by service S."},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"55914","MessageTemplate":"Subnet {0} in VNET {1} is already occupied by service {2}.","Parameters":[X,Y,S],"Code":"Conflict","Message":"Subnet X in VNET Y is already occupied by service S."}}],"Innererror":null}
```

Interestingly enough, forcing an error through running `web_apps.get_swift_virtual_network_connection()` and giving a non-existing service name leads to a `404 Not Found`, with a _correctly_ formatted response.

**To Reproduce**
Call `web_apps.create_or_update_swift_virtual_network_connection()` (using the default API-version, 2020-09-01) with a setup that results in a `409 Conflict`.

**Expected behavior**
The error response conforms to the OData spec, for all operations.

**Comment by kristapratico** [comment]
Thanks for your question, we'll investigate and report back.

**Comment by BigCat20196** [comment]
Hi @fhoy Thanks for the feedback!

The latest azure-mgmt-web version is 3.0.0. In this version, `create_or_update_swift_virtual_network_connection_with_check` operation replaces `create_or_update_swift_virtual_network_connection operation`. 

It is recommended to upgrade the version and try again. The problem may have been fixed.

Please kindly let us know if it solves the issue.
