### ISSUE TITLE
azure-mgmt-web 3.0.0: breaking changes without migration information

### ISSUE THREAD

**Issue by fhoy** [Azure/azure-sdk-for-python#19663]
- **Package Name**: azure-mgmt-web
- **Package Version**: 3.0.0
- **Operating System**: _n/a_
- **Python Version**: _n/a_

**Describe the bug**
In version 3.0.0 of `azure-mgmt-web`, among a large amount of breaking changes, the following are listed:
```
Removed operation WebAppsOperations.update_swift_virtual_network_connection
...
Removed operation WebAppsOperations.create_or_update_swift_virtual_network_connection_slot
Removed operation WebAppsOperations.update_swift_virtual_network_connection_slot
Removed operation WebAppsOperations.create_or_update_swift_virtual_network_connection
```
Additionally, the following is listed in the "Features" section:
```
Added operation WebAppsOperations.create_or_update_swift_virtual_network_connection_with_check
```

The release notes say nothing else about this. The [SDK docs](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_01_01.operations.webappsoperations?view=azure-python#create-or-update-swift-virtual-network-connection-with-check-resource-group-name--name--connection-envelope----kwargs-) seem to have been copy/pasted from the previous version, and do not say anything about what "with_check" means, or whether or not (or how) this variant supports slots. Furthermore, the API-version (2021-01-01) is not even listed in the main [Azure REST docs](https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/create-or-update-swift-virtual-network-connection-slot).

I understand that I can explicitly configure my code to use the older API version (2019-08-01), but given that this new version (2021-01-01) is set as the default version in class `WebSiteManagementClient`, and is not tagged as preview as far as I can tell, I would have expected some more information on how to migrate.

**To Reproduce**
Upgrade `azure-mgmt-web` from 2.0.0 to 3.0.0

**Expected behavior**
To be given migration instructions for breaking changes.

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by RAY-316** [comment]
Web 2.0.0 to 3.0.0 does contain a lot of changes. I will inform the relevant teams to update the document . You can give more detailed examples if you encounter problems in use

**Comment by fhoy** [comment]
Some concrete questions I would like answered:
- Is `create_or_update_swift_virtual_network_connection_with_check` a direct replacement for `create_or_update_swift_virtual_network_connection`?
- How do I configure VNets for slots, now that `create_or_update_swift_virtual_network_connection_slot` is gone?
