### ISSUE TITLE
AzureServiceBus - AutoLockRenewer is not working

### ISSUE THREAD

**Issue by CatchSandeepVaid** [Azure/azure-sdk-for-python#19683]
- **Package Name**: 
- **Package Version**: 
- **Operating System**: CentOS 7.8
- **Python Version**: 3.7

**Describe the bug**
Even after specifying AutoLockRenewer, getting azure.servicebus.exceptions.SessionLockLostError: The lock on the session has expired. Callers should request the session again.

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**
   ```
    connstr ="xxx"
    session_id = "abcdefgh"
    renewer = AutoLockRenewer()
    with ServiceBusClient.from_connection_string(connstr,logging_enable=True) as client:
        with client.get_queue_receiver(queue_name, session_id=session_id,max_wait_time=None) as receiver:
            renewer.register(receiver, receiver.session, max_lock_renewal_duration=5)             
            for msg in receiver:
                logging.info("Message Received: " + str(msg))
                time.sleep(6)
                receiver.complete_message(msg)
```

**Comment by kristapratico** [comment]
Thanks for your feedback, we'll investigate and get back to you asap.

**Comment by yunhaoling** [comment]
hey @CatchSandeepVaid ,

I see that you set the `max_lock_renewal_duration` to be 5 in the line `renewer.register(receiver, receiver.session, max_lock_renewal_duration=5)` which means that the `AutoLockRenewer` will only maintain the lock for 5 seconds.

The [max_lock_renewal_duration](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.html#azure.servicebus.AutoLockRenewer) is defined as ` A time in seconds that locks registered to this renewer should be maintained for.`

In the code you provided, the `AutoLockRenewer` will stop auto renewing the session lock after 5 seconds, leading session expiration after the lock duration.

If you wish the AutoLockRenewer to maintain the lock for a longer time, you could set the `max_lock_renewal_duration` to be a larger value.

Please let me know if you have any questions!
