### ISSUE TITLE
Reservations Python SDK - Exchange API stuck

### ISSUE THREAD

**Issue by juhee0202** [Azure/azure-sdk-for-python#19694]
This is a customer reported incident from our biggest client. They are having trouble with the Python SDK for Reservations module. They are trying to use the "Exchange" operation. The way that this works in API is customer calls POST /exchange, and it returns 202 Accepted with a Azure-AsyncOperation header. The customer will call GET on the value in Azure-AsyncOperation header, which will return 200 OK with a response body until final result is returned (status = succeeded).

**Exchange operation**: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-reservations/1.0.0/azure.mgmt.reservations.operations.html#azure.mgmt.reservations.operations.ExchangeOperations

**Github link**: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/operations/_exchange_operations.py

**Problem (in customer's words)**: Exchange has extremely long waiting time from the call and for most of the time, it does not return any response. My script is basically hung in there and waiting for the response from the function call. I believe from Exchange, the response comes really late from the call. From default value, I have to wait few hours to get the result. I will time it on my next batch and provide screenshot about it. I will also try to adjust the polling_interval to be 60 seconds for next few batch to see if the response would come quicker than default one.

How can the customer fix this problem? Do you have any examples of usage of Python SDK for asynchronous post operations?

=======================
adding more info from customer:

I am using this class: AzureReservationAPI (from azure.mgmt.reservations import AzureReservationAPI) and using the following to do calculation to get session id from exchange request: calculate_exchange.post(calculate_exchange_request).result(). After that I am using this method to do exchange: exchange.post(exchange_request, polling=True).result(). The following would be some simple code without any logic in my script.

reservation_client = AzureReservationAPI(credential, base_url=None)
calculate_result = reservation_client.calculate_exchange.post(calculate_exchange_request).result()
session_id = calculate_result.properties.session_id
exchange_request = ExchangeRequestProperties(session_id = session_id)
exchange_result = self.reservation_client.exchange.post(exchange_request, polling=True).result()
logger.info("exchange_result : {}".format(exchange_result))       **This is where response got stuck for few hours**

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate and get back to you asap.

**Comment by juhee0202** [comment]
added more info from customer in the summary

**Comment by msyyc** [comment]
Hi @reservations service team, according to the description, service server will take a long time to do the operation. Could you help to do search about it?

**Comment by juhee0202** [comment]
This is an asynchronous long running operations - we expect the operations to run anywhere from a few minutes to a few days. 
This is what the process looks like if user is calling the APIs directly.

1. POST /exchange - 202 Accepted. Headers: Azure-AsyncOperation: <pollingURL>
2. GET <polling URL> - 200 OK. Headers: Azure-AsyncOperation: <pollingURL>. Body: {status: PendingRefunds}.
3. user polls the Azure-AsyncOperation header until status reaches Succeeded/Failed.
4. GET <polling URL> - 200 OK. Body: <status: Succeeded>

**Comment by juhee0202** [comment]
in the Python SDK, is there a way for the user to do the polling themselves (step 2) before the terminal status is reached? or do they have to wait for the server to do the polling and return a response with terminal status (step 4)?

**Comment by kristapratico** [comment]
> in the Python SDK, is there a way for the user to do the polling themselves (step 2) before the terminal status is reached? or do they have to wait for the server to do the polling and return a response with terminal status (step 4)?

@juhee0202 Trying to understand - is it that the customer wants the final result, but doesn't want to block on the code while waiting for it? If this is the case, then they shouldn't call result() right away and can manually poll with status() instead.

```
exchange_request = ExchangeRequestProperties(session_id = session_id)
exchange_poller = self.reservation_client.exchange.begin_post(exchange_request)
status = exchange_poller.status()

# ... check status() manually, do other things ...

# once status indicates it's done or we're ready to block until it's done.
exchange_result = exchange_poller.result()

```
