### ISSUE TITLE
'MSIAuthentication' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by DvirDukhan** [Azure/azure-sdk-for-python#19719]
- **Package Name**: 
- azure-mgmt-resource
- **Package Version**: 
- 18.0.0
- **Operating System**:
- Ubuntu 18.04
- **Python Version**: 
- 3.8.1

**Describe the bug**
On Azure ML workspace notebook, running on azure compute instance I'm trying to get the current workspace instance in order to submit an AutoML training job, as seen at https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-auto-train-models#configure-workspace. As I don't have a config file and I am running the notebook in an Azure compute instance I tried to execute `Workspace()` constructor command and not `Workspace.from_config()`. As a result, I'm getting the `'MSIAuthentication' object has no attribute 'get_token'` error.
I tried to submit both `MsiAuthentication` and `InteractiveLoginAuthentication`, as they seemed to be supported in https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb.
I looked at similar issues https://github.com/Azure/azure-sdk-for-python/issues/14499 and https://github.com/Azure/azure-sdk-for-python/issues/13871 and in those issues, it is written that for azure-mgmt-resource version >= 15.0.0 there is a need to use `AzureIdentityCredentialWrapper`, however, I did not understand where it located in the Azure Python SDK and how I should submit it to the `Workspace` constructor, as it gets as `auth` parameter value only `ServicePrincipalAuthentication` or `InteractiveLoginAuthentication` or `MsiAuthentication`.

Thanks!

**To Reproduce**
1.`MsiAuthentication` approach
```python
from azureml.core.workspace import Workspace
from azureml.core.authentication import MsiAuthentication
msi_auth = MsiAuthentication()
ws = Workspace(workspace_name='azureml', subscription_id=my_subscription_id, resource_group=my_resource_group, auth=msi_auth)
```
1. `InteractiveLoginAuthentication` approach
```python
from azureml.core.workspace import Workspace
from azureml.core.authentication import InteractiveLoginAuthentication
interactive_auth = InteractiveLoginAuthentication(tenant_id=my_tenant_id)
ws = Workspace(workspace_name='azureml', subscription_id=my_subscription_id, resource_group=my_resource_group, auth=interactive_auth)
```

**Expected behavior**
Being able to retrieve workspace without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/12258836/124916112-f890f680-dffa-11eb-885b-69346bf7f18c.png)
![image](https://user-images.githubusercontent.com/12258836/124916156-05154f00-dffb-11eb-9802-4a8fe09f9abc.png)

**Additional context**
Notebook kernel - Python 3.8 - AzureML

azure-mgmt-resource version extraction:
```
azureuser@dvir1:~/cloudfiles/code/Users/dvir$ pip list | grep azure-mgmt-resource
azure-mgmt-resource                     18.0.0
```

**Comment by nf78** [comment]
I'm having this exact same issue. 

**There are 2 solutions I've found:**
https://stackoverflow.com/questions/68303285/msiauthentication-object-has-no-attribute-get-token/68303286#68303286

1.- Use the kernel "Python 3.6 - AzureML"

2.- `pip install azureml-core --upgrade `

**This will upgrade** 
azureml-core to 1.32.0 
**But will downgrade:**
azure-mgmt-resource to 13.0.0 (was 18.0.0)
azure-mgmt-storage down to 11.2.0 (was 18.0.0)
urllib3 to 1.26.5 (was 1.26.6)

This upgrade / downgrade allows the same package versions as in the python 3.6 anaconda install

**Comment by harneetvirk** [comment]
azure-mgmt-resource 18.0.0 is not compatible with azureml-core (1.32.0).
The latest version of azureml-core (1.32.0) has the following dependency:  azure-mgmt-resource<15.0.0,>=1.2.1


PPlease do not install azure-mgmt-resource 18.0.0 yourself . Installing azureml-core should bring the right dependencies.

**Comment by DvirDukhan** [comment]
Thanks @harneetvirk 
Note that azure-mgmt-resource 18.0.0 is provided in the `Python 3.8 - AzureML`  kernel by default. This is the output from a fresh compute instance:
```
azureuser@dvir2:~/cloudfiles/code/Users/dvir$ pip list | grep azure-mgmt-resource
azure-mgmt-resource                     18.0.0
```

**Comment by harneetvirk** [comment]
Seems like, the latest version (18.0.0) of azure-mgmt-resource is baked into the Compute Instance image. Will follow-up with Compute Instance team (internally) to get this fixed for Python 3.8 - AzureML.

**Comment by DvirDukhan** [comment]
Thanks @harneetvirk 
I tried to change the dependency manually but got a dependency validation exception when tried to run
```python
from azureml.core.experiment import Experiment
from azureml.core.workspace import Workspace
ws = Workspace.get("azureml", resource_group = my_resource_group, subscription_id=my_subscription_id)
experiment = Experiment(ws, "Tutorial-Taxi")
local_run = experiment.submit(automl_config, show_output=True)
```
the dependencies where `azure-mgmt-storage`, `azure-identity` at first so I tried to resolve them manually but then I got:
```
ValidationException: ValidationException:
	Message: Install the required versions of packages using the requirements file. Requirements file location: /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/automl/core/validated_linux_requirements.txt. Alternatively, use remote target to avoid dependency management. 
Required version/Installed version
numpy<=1.18.5/numpy 1.21.0
pandas<=0.25.3/pandas 1.2.5
pyarrow<=3.0.0/pyarrow 4.0.1
scikit-learn<=0.22.2.post1/scikit-learn 0.24.2
scipy<=1.5.2/scipy 1.7.0
sklearn-pandas<=1.7.0/sklearn-pandas 2.2.0
smart-open<=1.9.0/smart-open 5.1.0
statsmodels<=0.10.2/statsmodels 0.12.2
urllib3<=1.25.11/urllib3 1.26.6
```

I executed this script to find out the difference between the installed libraries and the required libraries:
```python
req_path = "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/automl/core/validated_linux_requirements.txt"
import pkg_resources
from pathlib import Path

def test_requirements():
    """Test that each required package is available."""
    # Ref: https://stackoverflow.com/a/45474387/
    requirements = pkg_resources.parse_requirements(Path(req_path).open())
    for requirement in requirements:
        requirement = str(requirement)
        try:
            pkg_resources.require(requirement)
        except Exception as e:
            print(str(e))

test_requirements()
```

this is the output, I hope it will help you:
```
(azure-identity 1.6.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-identity<=1.4.1'))
(azure-mgmt-resource 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-resource<=13.0.0'))
(azure-mgmt-storage 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-storage<=11.2.0'))
(pyarrow 4.0.1 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('pyarrow<4.0.0,>=0.17.0'), {'azureml-dataset-runtime'})
The 'azureml-automl-runtime~=1.31.0' distribution was not found and is required by the application
(azure-mgmt-resource 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-resource<15.0.0,>=1.2.1'), {'azureml-core'})
(azure-identity 1.6.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-identity<1.5.0,>=1.2.0'), {'azureml-dataprep'})
(azureml-dataprep-rslex 1.16.1 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azureml-dataprep-rslex<=1.16.0'))
(pyarrow 4.0.1 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('pyarrow<4.0.0,>=0.17.0'), {'azureml-dataset-runtime'})
(pyarrow 4.0.1 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('pyarrow<4.0.0,>=0.17.0'), {'azureml-dataset-runtime'})
(azure-mgmt-resource 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-resource<15.0.0,>=1.2.1'), {'azureml-core'})
(azure-mgmt-resource 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-resource<15.0.0,>=1.2.1'), {'azureml-core'})
(azure-mgmt-resource 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-resource<15.0.0,>=1.2.1'), {'azureml-core'})
(azure-mgmt-resource 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-resource<15.0.0,>=1.2.1'), {'azureml-core'})
The 'azureml-train-automl~=1.31.0' distribution was not found and is required by the application
(azure-mgmt-resource 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-resource<15.0.0,>=1.2.1'), {'azureml-core'})
The 'azureml-train-automl-runtime~=1.31.0' distribution was not found and is required by the application
(azure-mgmt-resource 18.0.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('azure-mgmt-resource<15.0.0,>=1.2.1'), {'azureml-core'})
(urllib3 1.26.6 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('urllib3<1.26,>=1.20; python_version != "3.4"'), {'botocore'})
(urllib3 1.26.6 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('urllib3<1.26,>=1.20; python_version != "3.4"'), {'botocore'})
The 'keras2onnx<=1.6.0' distribution was not found and is required by the application
(msal-extensions 0.3.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('msal-extensions<=0.2.2'))
The 'nimbusml<=1.8.0' distribution was not found and is required by the application
(numpy 1.21.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('numpy<=1.18.5'))
The 'onnx<=1.7.0' distribution was not found and is required by the application
The 'onnxconverter-common<=1.6.0' distribution was not found and is required by the application
The 'onnxmltools<=1.4.1' distribution was not found and is required by the application
The 'onnxruntime<=1.8.0' distribution was not found and is required by the application
(pandas 1.2.5 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('pandas<=0.25.3'))
(pyarrow 4.0.1 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('pyarrow<=3.0.0'))
(urllib3 1.26.6 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('urllib3<1.26,>=1.20; python_version != "3.4"'), {'botocore'})
(scikit-learn 0.24.2 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('scikit-learn<=0.22.2.post1'))
(scipy 1.7.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('scipy<=1.5.2'))
The 'skl2onnx<=1.4.9' distribution was not found and is required by the application
(sklearn-pandas 2.2.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('sklearn-pandas<=1.7.0'))
(smart-open 5.1.0 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('smart-open<=1.9.0'))
(statsmodels 0.12.2 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('statsmodels<=0.10.2'))
(urllib3 1.26.6 (/anaconda/envs/azureml_py38/lib/python3.8/site-packages), Requirement.parse('urllib3<=1.25.11'))
```

**Comment by harneetvirk** [comment]
You should not having workspace authentication issue anymore after removing the latest version (18.0.0) of azure-mgmt-resource.

I noticed, you have installed some latest versions of AutoML dependent packages and now you are hitting the validation error from AutoML packages. Per the requirement from the AutoML, you have the following differences. Please do not manually install any dependent package but let azureml-* packages install the right dependencies.

**Required version/Installed version**
numpy<=1.18.5/numpy 1.21.0
pandas<=0.25.3/pandas 1.2.5
pyarrow<=3.0.0/pyarrow 4.0.1
scikit-learn<=0.22.2.post1/scikit-learn 0.24.2
scipy<=1.5.2/scipy 1.7.0
sklearn-pandas<=1.7.0/sklearn-pandas 2.2.0
smart-open<=1.9.0/smart-open 5.1.0
statsmodels<=0.10.2/statsmodels 0.12.2
urllib3<=1.25.11/urllib3 1.26.6

FYI: Not all the AutoML packages support python 3.8 especially azureml-automl-runtime/azureml-train-automl-runtime.

**Comment by DvirDukhan** [comment]
Indeed after resolving `azure-mgmt-resource` I did not have the workspace authentication issue, however, I did not install any of the above libraries. The diff output I provided above is from a fresh instance.

**Comment by abrookins** [comment]
@harneetvirk Thanks for your help! As you wrote, azureml-train-automl-runtime does not support Python 3.8. We're trying to use code that depends on Python 3.7 or higher, so we can't use the 3.6 kernel. Is there a 3.7 kernel, or just 3.6 and 3.8? Excuse my ignorance! :) 

![image](https://user-images.githubusercontent.com/97182/124998912-0f871700-e002-11eb-8cc4-89d33ea42d7d.png)

**Comment by harneetvirk** [comment]
Unfortunately, python 3.7 is not available on Compute Instance. You can manually create a fresh conda environment with python 3.7 on CI to unblock yourself, if that can unblock you.

**Comment by abrookins** [comment]
Ok, good to know. That's the route I took. But it seems the library we're trying to use depends on a newer version of Pandas than the one the Azure libs need. Is it true that they require pandas<=0.25.3?

**Comment by harneetvirk** [comment]
yes, AutoML packages are not using the latest version (1.3.0) of pandas. 
For e.g. azureml-automl-runtime expects pandas>=0.21.0,<1.0.0
