### ISSUE TITLE
Azure ML File Dataset download doesn't work reliably with wildcard filepath /**

### ISSUE THREAD

**Issue by lesterlitch** [Azure/azure-sdk-for-python#19749]
- **Package Name**: azure ml
- **Package Version**:  '1.32.0'
- **Operating System**: Windows 10
- **Python Version**:  3.8

**Describe the bug**
When downloading a file dataset onto an Azure-ml cluster, I then try to validate each file against a matching set of labels and filepaths I have. Totally at random, all the files in one or more subdirectories will not successfully return true to os.path.exists() or os.path.isfile(). 

For example, I will check a "train" subdirectory and sometimes all files will be found, sometimes none. Same for a "val" subfolder. 

**To Reproduce**
1. Create a dataset with more than one subdirectory using the /** path notation
2. Submit an ML job to a cluster
3. In the job, download the file dataset using the file dataset download sdk method.
2. In the job, using a manifest of the files, check that each file exists in each subfolder using python os.path.isfile()
3. On multiple runs, one of the subdirectories will often return no successful file checks.

**Expected behavior**
The files we download with dataset download are actually present on the node every time.

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ynpandey** [comment]
@lesterlitch Can you please provide a code snippet for this issue?

**Comment by lesterlitch** [comment]
To train:

`# configure and submit your training run
from azureml.core import Dataset, Run, ScriptRunConfig, Experiment, Dataset, Run, Workspace
from azureml.core import ScriptRunConfig

input_dataset = Dataset.get_by_name(workspace, name='EXAMPLE', version=1)

script_folder = "./azure_ml_exp"

config = ScriptRunConfig(source_directory=script_folder,
                         script='EXAMPLE.py',
                         compute_target=compute_target,
                         environment=env,
                         arguments=["--dataset", input_dataset.as_named_input('dataset').as_download()]
                        )
run = experiment.submit(config=config)`

And on the node:

`parser.add_argument('--dataset', type=str, dest='dataset', help='dataset download location')
args = parser.parse_args()
data_dir = args.dataset

train_df = pd.read_csv(os.path.join(data_dir, 'TRAIN.csv'))
val_df = pd.read_csv(os.path.join(data_dir, 'TEST.csv'))

logger.info("Checking files")

def check_file(fn, image_dir):
    if os.path.exists(os.path.join(image_dir, fn + ".png")):
        return 1
    elif os.path.islink(os.path.join(image_dir, fn + ".png")):
        return 1
    else:
        return 0

train_im_dir = os.path.join(data_dir, 'train')
val_im_dir = os.path.join(data_dir, 'val')

logger.info(f"Pre check,  Train records: {len(train_df)}, Val Records: {len(val_df)}")

train_df['check'] = train_df['name'].apply(lambda x: check_file(x, train_im_dir))
val_df['check'] = val_df['name'].apply(lambda x: check_file(x, val_im_dir))

logger.info(f"After check,  Train records: {len(train_df)}, Val Records: {len(val_df)}")
`

At random either train_df or val_df will return 0 rows after checking.

**Comment by ynpandey** [comment]
@lesterlich Can you please provide the following for further investigation:

- Driver logs
- Job prep/release logs
- Data prep logs
Also, can you provide details of the directories and the files that you used for creating dataset using /** wildcard?

**Comment by lesterlitch** [comment]
Hi, these files contain private information I'm not comfortable sharing on Github.

The filepath is simply: "some_directory/**' 

It contains two subfolders, on for train and one for test. 

In the job prep it shows it is processing a FileDataset, that is is Downloading dataset and successfully downloads as a folder. 

I then get a "not a directory error" in python if I don't check the files are there, in the driver log.

**Comment by rfarmaha** [comment]
I can't repro this on my end. It looks like you're trying to read two files in the root directory (some_directory/**) of the dataset here?
train_df = pd.read_csv(os.path.join(data_dir, 'TRAIN.csv'))
val_df = pd.read_csv(os.path.join(data_dir, 'TEST.csv'))


You mentioned the directory contains subfolders for train and test,  can you verify the TRAIN.csv and TEST.csv files are also there?
