### ISSUE TITLE
stop_speaking_async does not work

### ISSUE THREAD

**Issue by oliverguhr** [Azure/azure-sdk-for-python#19757]
- **Package Name**: azure-cognitiveservices-speech
- **Package Version**: 1.17.0 
- **Operating System**: Linux
- **Python Version**:  Python 3.8.10

**Describe the bug**
The ```stop_speaking_async``` (and ```stop_speaking```) do not stop the audio output as described in the documentation

**To Reproduce**
1. replace your API credentials 
2. run this code 
```python
import time
from azure.cognitiveservices.speech import AudioDataStream, SpeechConfig, SpeechSynthesizer, SpeechSynthesisOutputFormat
from azure.cognitiveservices.speech.audio import AudioOutputConfig


def main():
    speech_config = SpeechConfig(subscription="", region="")
    audio_config = AudioOutputConfig(use_default_speaker=True)
    synthesizer = SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)
    print("speak")
    text = "This is a very very very very very very very very very very very very very very very very long text."
    _ = synthesizer.start_speaking_text_async(text)
    print("sleep")
    time.sleep(1)
    print("stop")
    _ = synthesizer.stop_speaking_async()
    print("done")
   

main()

```

**Expected behavior**
The method ```stop_speaking_async``` should stop the audio output.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by yulin-li** [comment]
@oliverguhr, thank you for reporting this issue, and I can repro it. We will fix this.

**Comment by yulin-li** [comment]
Closing this issue and tracking it in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1686
