### ISSUE TITLE
ComputerVision

### ISSUE THREAD

**Issue by Saudith15** [Azure/azure-sdk-for-python#19756]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 500cf225-f79b-3c43-cde5-44509519b450
* Version Independent ID: 66fb4b49-d177-fa54-ebe4-cc0868820359
* Content: [azure-cognitiveservices-vision-computervision package](https://docs.microsoft.com/es-es/python/api/azure-cognitiveservices-vision-computervision/?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cognitiveservices-vision-computervision/index.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-cognitiveservices-vision-computervision/index.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
No comments in the issue. 

Closing. Please open one with some descriptions.
