### ISSUE TITLE
🤔 How should I test SDK compnents from this repository?

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#19775]
Hello! 👋🏻

I'm packaging the Azure SDK (and soon, the CLI) within Fedora Linux so that users can install the SDK and CLI easily via signed packages from Fedora repositories. So far, it's going very well and I only have a few SDK components left to package.

However, I am confused on the best way to test these packages. I know that testing code is included in these directories:

* `tools/azure-devtools`
* `tools/azure-sdk-tools`

My questions are:

1. If I am packaging something like azure-mgmt-redhatopenshift v1.0.0, should I get the testing tools from the git commit that corresponds to that particular release?
2. Should I always use the latest set of testing tools?

Thank you!

**Comment by xiangyan99** [comment]
@major Thanks for reaching out.

We try our best to make these testing tools backward compatible.

So yes, please use the latest version to test.

**Comment by major** [comment]
> So yes, please use the latest version to test.

Thank you!
