### ISSUE TITLE
The latest version of azure-storage-blob for python sdk does not support AzureStack

### ISSUE THREAD

**Issue by pyprateek** [Azure/azure-sdk-for-python#19774]
Hi,

I am using the latest version of azure-storage-blob (12.8.1).
While creating the object of BlobServiceClient or ContainerClient, I get the following error:
`ValueError: Unable to determine account name for shared key credential.`

I checked the SDK code and found that the account_url needs to have 'core' in it.
for ex: https://<storage-account-name>.blob.core.windows.net/
Please see the below code snippet from base_client.py
`account = parsed_url.netloc.split(".{}.core.".format(service_name))`

But in the case of AzureStack, the account_url contains location in place of core. Because of which the account_url
parsing fails.

I am using this method to create the object of BlobServiceClient:
`blobServiceClient = BlobServiceClient(account_url=<blob_service_url>, credential=<storage_account_access_key>, api_version="2019-02-02")`

Is there any alternate way to get the object of BlobServiceClient or ContainerClient?
Or is there any such request already created to resolve this?

**Comment by pyprateek** [comment]
After removing 'core' from the above mentioned line in base_client.py, I was able to create the object of BlobServiceClient and the operations were running successfully.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiafu-msft** [comment]
Hi @pyprateek 

If your account url is not in standard format like username.blob.core.windows.net, then please set credential in this way
`credential={"account_name": your_account_name, "account_key": your_account_key} 
`

then it should work. Let me know if it still doesn't work!

**Comment by pyprateek** [comment]
@xiafu-msft Is this what you meant?

```
storageCreds = {
        "account_name": account_name,
        "account_key": storage_account_access_key
        }
blobServiceClient = BlobServiceClient(account_url=<account_url>, credential=storageCreds)
```

I am still getting the same error
`ValueError: Unable to determine account name for shared key credential.`

**Comment by xiafu-msft** [comment]
@pyprateek Thanks for letting me know! Good to know it works! I'll close this issue for now just let me know if you have any other questions!
