### ISSUE TITLE
Is it possible to create a VM with OS disk type different than Premium SSD?

### ISSUE THREAD

**Issue by Jendker** [Azure/azure-sdk-for-python#19786]
Please correct me if there is a better place to ask questions for Azure's Python SDK.

Could you please let me know if it is possible to create a VM with a specific OS disk type, as it is possible when creating a VM from the Azure Portal? Below is an example of it:

![Screenshot from 2021-07-13 13-31-40](https://user-images.githubusercontent.com/14967831/125520733-aaa029dc-2888-4285-9648-362eca6aca95.png)

Currently, I am creating the VM using the following call (azure-mgmt-compute==13.0.0):

```
vm_poller = compute_client.virtual_machines.create_or_update(
                resource_group_name=azure_resource_group,
                vm_name=vm_name,
                parameters={'location': 'southcentralus', 'os_profile': {'computer_name': 'doodad', 'admin_username': '...', 'admin_password': '...', 'custom_data': ...'}, 'hardware_profile': {'vm_size': 'Standard_DS1_v2'}, 'storage_profile': {'image_reference': {'offer': 'UbuntuServer', 'publisher': 'Canonical', 'sku': '18.04-LTS', 'urn': 'Canonical:UbuntuServer:18.04-LTS:latest', 'urnAlias': 'UbuntuLTS', 'version': 'latest'}}, 'network_profile': {'network_interfaces': [{'id': '/subscriptions/.../resourceGroups/doodadca79a1/providers/Microsoft.Network/networkInterfaces/myNic'}]}, 'tags': {'user': 'jedrzej', 'log_path': 'doodad_exist_test'}, 'identity': {'type': <ResourceIdentityType.system_assigned: 'SystemAssigned'>}}
```

**Comment by Drewm3** [comment]
@Vaibhav-Agar, could you please take a look at this one.

**Comment by Jendker** [comment]
Is there any update on this?

**Comment by Vaibhav-Agar** [comment]
Hi @Jendker,

You should be able to do that. One way could be to create a disk using the script below and set the storage_account_type as you want. Once that is done, you can pass the 'osDisk' in your VM create request, rather than passing the 'ImageReference'. Please re-open if this doesn't answer your question. Thanks!

diskParams = {
    'location': "westeurope",
    'disk_size_gb': 128,
    'managed_disk': {
        'storage_account_type': 'Premium_LRS'
    },
    'creation_data': {
        'create_option': 'Empty'
    }
}

newDisk = compute_client.disks.create_or_update(
    "test-resource-group",
    "test-disk-name",
    diskParams
)

osdisk = newDisk.result()
print('Created Managed Disk:   ' + osdisk.name)

**Comment by Jendker** [comment]
Could you help me to specify the platform image parameters? For now I was passing:

```
                'storage_profile': {
                    'image_reference': {
                        "offer": "UbuntuServer",
                        "publisher": "Canonical",
                        "sku": "18.04-LTS",
                        "urn": "Canonical:UbuntuServer:18.04-LTS:latest",
                        "urnAlias": "UbuntuLTS",
                        "version": "latest"
                    }
                },
```
But since `'image_reference` is going to become `osdisk` I have tried passing this information in the `'creation_data'`:

```
                'creation_data': {
                    'create_option': 'from_image',
                    "id": "/Subscriptions/{}/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/latest".format(self.subscription_id),
                }
            }
```
following this reference: https://docs.microsoft.com/en-us/rest/api/compute/disks/create-or-update#create-a-managed-disk-from-a-platform-image.
But I am getting:
```
Operation failed with status: 'Not Found'. Details: No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/<subscr_id>/resourceGroups/subscriptions/<subscr_id>/resourceGroups/doodad5effac/providers/Microsoft.Compute/disks/doodad-vm-disk?api-version=2020-05-01'.
```

**Comment by Jendker** [comment]
I am unable to reopen this issue, unfortunately.
