### ISSUE TITLE
[azure-mgmt-sql] add support for SQL replica

### ISSUE THREAD

**Issue by alonzo86** [Azure/azure-sdk-for-python#19793]
I'm using azure-mgmt-sql 3.0.0 and i want to create a replica of an existing SQL DB but there is no such operation available.

there should be an API that supports SQL replica create/list/delete which is similar to CLI:
[https://docs.microsoft.com/en-us/cli/azure/sql/db/replica?view=azure-cli-latest](https://docs.microsoft.com/en-us/cli/azure/sql/db/replica?view=azure-cli-latest)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.
