### ISSUE TITLE
Cannot Run Azure ML Model Locally, Help on Entry script

### ISSUE THREAD

**Issue by noumanqaiser** [Azure/azure-sdk-for-python#19818]
I am working on a project where a model will be created using Azure ML(ml.azure.com),

I plan to utilize Azure ML Designer eventually, So I picked up a sample pipeline (Regression - Automobile Price Prediction (Basic)). I then created a realtime inference pipeline and created a realtime endpoint.

Post this, I am able to fetch predictions from this model from a .Net client over internet as expected.

As a part of the same project, I eventually want to fully eliminate the internet dependency/Affiliated latency with Predictions. I understand this can be achieved by packaging the model and downloading a docker image that runs on a local computer and exposes the model via a scoring web service.

To package the model and download it as a docker image, I utilized the following python code, this would execute on my local PC:

```
import azureml.core
print(azureml.core.VERSION)


from azureml.core import Workspace
ws = Workspace.get(name="TestMLWorkSpace", subscription_id='XXXXXX-a9c4-4426-XXXX-XXXXXXX', resource_group='MyResourceGroup')

from azureml.core.experiment import Experiment
experiment = Experiment(workspace=ws, name='TestAutomobileSampleExp')

list_runs = experiment.get_runs()
for run in list_runs:
    print(run.id)

list_experiments = Experiment.list(ws)


from azureml.core.model import Model
import os

model = Model(workspace=ws, name="amlstudio-regrealtimeendpoint")
model.download(target_dir=os.getcwd(), exist_ok=1 )

from azureml.core import Environment
from azureml.core.model import InferenceConfig

env = Environment.get(workspace=ws, name="AzureML-Minimal")
inference_config = InferenceConfig(
    environment=env,
    source_directory="./",
    entry_script="./score.py",
)



package = Model.package(ws, [model], inference_config)
package.wait_for_creation(show_output=True)

package.pull()
#checked image id using --->   docker images
# replace image id from the result above in the following command
# docker run -p 6789:5001 --name mycontainer c262eaa7bab9

#  http://localhost:6789/score
```
Now when I run this script, a docker image is downloaded on my computer and available to be run using docker.

What is the problem?

As a part of creating the inference config, I need to specify an entry script called score.py It seems I cannot run the docker image because the entry script is likely not correct.

Here is how my score.py currently looks like:

```
import os import json

from azureml.core.model import Model import logging

def init():
    global model
    logging.basicConfig(level=logging.DEBUG)
    model_path = Model.get_model_path(model_name='amlstudio-regrealtimeendpoint')
    print(Model.get_model_path(model_name='amlstudio-regrealtimeendpoint'))
    #How do I load the model here??


def run(input_data):
    try:
        data = json.loads(input_data)['data']
        data = np.array(data)
        result = model.predict(data)
        return json.dumps({"result": result.tolist()})
    except Exception as e:
        result = str(e)
        # return error message back to the client
        return json.dumps({"error": result})
```
I built this entry script from Microsoft materials but it does not work and Docker image fails to initiate.

My question is,

Is my source Dir in inference config correct? what should be my source Directory given the fact that I just want the model to run locally be able to provide predictions locally?
what changes should I make to this entry script to get the scoring to work locally on my computer?
Thanks,

**Comment by shivanissambare** [comment]
Hi, did you take a look at our local deployment example notebook : https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/deployment/deploy-to-local

**Comment by noumanqaiser** [comment]
Hi @shivanissambare, I have gone through this tutorial, the given example is creating an sklearn model via notebook and then the entry script loads it using joblib. In my case, My model is created in Azure ML designer, registered and then deployed as web service. I could not find any example of how an entry script would look like for such a designer based model. 
Would appreciate your help to get a designer model working locally.

**Comment by shivanissambare** [comment]
Hi, thanks for the clarification. 
If you have trained your model in designer and registered, you can download your scoring script in the following way:

![image](https://user-images.githubusercontent.com/61255242/126714673-569c3941-287f-4693-9cb2-a77d32788b30.png)

Take look at this documentation: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-model-designer#download-the-entry-script-file-and-conda-dependencies-file

**Comment by noumanqaiser** [comment]
Hi @shivanissambare  I did download the score.py from Azure ML as you indicated and tried to use it with the docker image. After I pull the image and run the docker container, the container fails to bootup with following errors:

```
File "/var/azureml-app/TestPythonApp/./score2.py", line 9, in <module>

from azureml.studio.core.io.model_directory import ModelDirectory

ModuleNotFoundError: No module named 'azureml.studio'

Worker exiting (pid: 47)

Shutting down: Master

Reason: Worker failed to boot.
```

It seems the dependencies are not getting inserted into the docker image. Based on various articles, I tried specifying the needed dependancies using the conda_dependencies class and by adding a requirements.txt file, however it still seems when the container starts it does not load all required packages before executing the score.py

```
from azureml.core.model import InferenceConfig

env = Environment.get(workspace=ws, name="AzureML-Minimal")
conda_dep = CondaDependencies()
conda_dep.add_conda_package("python=3.6.8")
conda_dep.add_conda_package("numpy==1.17.0")
conda_dep.add_conda_package("pip=20.2")

conda_dep.add_pip_package("azureml-defaults")
conda_dep.add_pip_package("azureml-designer-classic-modules==0.0.155")
conda_dep.add_pip_package("azureml-designer-serving==0.0.10")
conda_dep.add_pip_package("anaconda")
conda_dep.add_pip_package("joblib")
conda_dep.add_pip_package("azureml-sdk")
conda_dep.add_pip_package("azureml-core")



# Adds dependencies to PythonSection of myenv
env.python.conda_dependencies=conda_dep

env.docker.enabled = True
#myenv.docker.base_image = <MCR-path>
env.python.user_managed_dependencies = True

env.environment_variables = {
    "AZUREML_EXTRA_REQUIREMENTS_TXT": "./requirements.txt"
}


```

Would appreciate any support.

**Comment by shivanissambare** [comment]
@likebupt can you please help, as to why azureml.studio is giving throwing an error
