### ISSUE TITLE
Manage/admin rights are required to query the number of messages in the Subscription 

### ISSUE THREAD

**Issue by miroag** [Azure/azure-sdk-for-python#19820]
- **Package Name**: azure-servicebus
- **Package Version**: 7.3.1
- **Operating System**: Any
- **Python Version**: 3.9

**Describe the bug**
Manage rights are required to query the number of messages in the subscription. This is a security concern. 

**To Reproduce**
Following the answer in: https://github.com/Azure/azure-sdk-for-python/issues/17940
I've attempted to query number of messages in the subscription using the SAS with only Listen rights. 
```
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'SubCode=40100: Unauthorized : Unauthorized access for 'GetSubscription' operation on endpoint
```
If I add the Manage right then everything works OK. 

**Expected behavior**
I believe there shall be the way to query the number of items in the subscription with only listen rights. 
Currently it's implemented (only?) as part of the ServiceBusAdministrationClient and require escalated rights. 
In the previous version (5) this API was a part of a normal SubscriptionClient (?) and did not require high rights, but I never worked on the previous SDK to be sure. 
It's also possible that there is another way to query this specific information, but I did not manage to find it.

**Screenshots**
-

**Additional context**
it's required to build a horizontal scaler based on the client activities (number of messages)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by yunhaoling** [comment]
hey @miroag , it has been documented in the service bus [service documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#rights-required-for-service-bus-operations) that `Get subscription description` requires `Manage` rights.

FYI 'Listen' confers the right to receive (queue, subscriptions) and all related message handling, while `query the number of messages in the subscription` is more from a manage scope than the receiving/message handling.

**Comment by miroag** [comment]
@yunhaoling Thanks for clarifying this.
