### ISSUE TITLE
Debug print statements in azureml SDK

### ISSUE THREAD

**Issue by meken** [Azure/azure-sdk-for-python#19822]
- **Package Name**: azureml-core
- **Package Version**: 1.31.0
- **Operating System**:Linux
- **Python Version**: 3.8

**Describe the bug**

At the moment most if not all azureml classes emit print statements to the console, which makes it difficult to create automation scripts that expect a certain output. It would be better to use the _logging_ package for these type of debug messages and give end users the control of what's printed to the stdout.

**To Reproduce**

1.  Try for instance uploading a model file using azureml.core.Model#register(workspace, model_path, model_name) and the following line will be printed to stdout: Registering model {model_name}
2. There's in the SDK many other places where this happens, the Model#register is just an example.

**Expected behavior**

All debug information should be emitted through logging, and hence can be turned off.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Mossaka** [comment]
Thanks for your feedback @meken . I will regard this as a feature request and will prioritize it within our team.

**Comment by xiangyan99** [comment]
@meken The feature request has been added into our backlog. 

We will close the issue and use our internal system to track it. Please feel free to re-open it if you want to add more information.

Thank you.
