### ISSUE TITLE
`depends` check failing in `azure-mgmt-storagesync`

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#19833]
[example here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=999189&view=logs&j=de48ec8f-ee03-59f0-0a39-cd6f8a6a1c25&t=2b09f712-fe31-51cd-6700-bfb21dd8953f&l=9510)

**Comment by msyyc** [comment]
The dependency is wrongly changed by this PR : https://github.com/Azure/azure-sdk-for-python/pull/19692/files
 
![image](https://user-images.githubusercontent.com/70930885/126094968-428f61bf-f04e-4650-b154-d9db61558bbc.png)

Please revert this file and then the pipeline should be fixed.
