### ISSUE TITLE
raise ValueError for explicit loop parameter in Python 3.10(uAMQP)

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#19835]
The loop parameter has been removed from most of asyncio‘s high-level API following deprecation in Python 3.8.

Raise ValueError to catch it.

**Comment by yunhaoling** [comment]
related issue: https://github.com/Azure/azure-sdk-for-python/issues/19835

**Comment by swathipil** [comment]
https://github.com/Azure/azure-uamqp-python/pull/261
