### ISSUE TITLE
Xrefs aren't working at the start of the page

### ISSUE THREAD

**Issue by sambyng-msft** [Azure/azure-sdk-for-python#19849]
[Enter feedback here]
From microsoft edge browser i see:
This class should not be instantiated directly. Instead, use the <xref:DatabaseProxy.get_container_client> method to get an existing container, or the <xref:Database.create_container> method to create a new container.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4a7941-9eb0-3ec5-6412-29b5d6e77bda
* Version Independent ID: 3c745306-3c71-b694-e621-eecb115923cd
* Content: [azure.cosmos.container.ContainerProxy class](https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.container.containerproxy?view=azure-python#query-items-query--parameters-none--partition-key-none--enable-cross-partition-query-none--max-item-count-none--enable-scan-in-query-none--populate-query-metrics-none----kwargs-)
* Content Source: [docs-ref-autogen/azure-cosmos/azure.cosmos.container.ContainerProxy.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-cosmos/azure.cosmos.container.ContainerProxy.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Rodrigossz** [comment]
Hello @sambyng-msft

We will fix that references. But you can find the documentation and examples of the SDK [here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cosmos/azure-cosmos). 

Tks

**Comment by Rodrigossz** [comment]
We are working on this issue and we already have an internal working item for that. Tks
