### ISSUE TITLE
"ContainerRepositoryClient" is not found 

### ISSUE THREAD

**Issue by ForrestIsARealGoodman** [Azure/azure-sdk-for-python#19858]
- **Package Name**: azure-containerregistry
- **Package Version**: azure-containerregistry==1.0.0b4
- **Operating System**: Windows
- **Python Version**: 3.8.10

**Describe the bug**
Hi Experts:

It appears that the reference is not found when trying to import module "ContainerRepositoryClient".
Check the __init__.py, it shows:
`__version__ = VERSION

__all__ = [
    "ArtifactArchitecture",
    "ArtifactOperatingSystem",
    "ContainerRegistryClient",
    "ManifestOrder",
    "ArtifactManifestProperties",
    "RepositoryProperties",
    "TagOrder",
    "ArtifactTagProperties",
]

class ContainerRepositoryClient:
    pass`

The class ContainerRepositoryClient is not implemented.
**To Reproduce**
1.  from azure.containerregistry import ContainerRegistryClient, ContainerRepositoryClient

**Expected behavior**
ContainerRepositoryClient could be referred/

**Comment by seankane-msft** [comment]
@ForrestIsARealGoodman the API surface changed from the 1.0.0b2 to 1.0.0b3 released. The `ContainerRepositoryClient` and `RegistryArtifact` classes were removed. For now you can use the `ContainerRegistryClient` to do everything you used to be do with the `ContainerRepositoryClient` class, but you will have to provide the repository name for calls specific to a repository. Let me know if there is a specific situation that has been removed with this change!

**Comment by ForrestIsARealGoodman** [comment]
> @ForrestIsARealGoodman the API surface changed from the 1.0.0b2 to 1.0.0b3 released. The `ContainerRepositoryClient` and `RegistryArtifact` classes were removed. For now you can use the `ContainerRegistryClient` to do everything you used to be do with the `ContainerRepositoryClient` class, but you will have to provide the repository name for calls specific to a repository. Let me know if there is a specific situation that has been removed with this change!

@seankane-msft thanks for your quick response, well, I have no idea to import a image for a specific repository based on current module, any regarding function & api could be recommended ? thanks very much!

**Comment by seankane-msft** [comment]
@ForrestIsARealGoodman there is no functionality for pushing/pulling images in this library. If you want to push/pull an image from an Azure Container Registry I would recommend using [the docker cli to do so](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli?tabs=azure-cli)

**Comment by ForrestIsARealGoodman** [comment]
@seankane-msft thanks for reminding!
