### ISSUE TITLE
Return the lastmodifiedtime or createtime from the API list_directories_and_files

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-python#19862]
One cx needs the API list_directories_and_files to get list of files recursively but the item does not include lastmodified time or create time.

According to the API document, the item can be FileProperties

https://docs.microsoft.com/en-us/azure/developer/python/sdk/storage/azure-storage-file-share/azure.storage.fileshare.shareclient?view=storage-py-v12#list-directories-and-files-directory-name-none--name-starts-with-none--marker-none----kwargs-

Returns
An auto-paging iterable of dict-like DirectoryProperties and FileProperties

But from source code:

https://github.com/Azure/azure-sdk-for-python/blob/9033064d870f652455325eec7c08749af70392df/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py#L331

        return ItemPaged(
            command, prefix=name_starts_with, results_per_page=results_per_page,
            page_iterator_class=DirectoryPropertiesPaged)

The page_iterator_class can only be DirectoryPropertiesPaged.

Ask: Can we return the lastmodifiedtime or createtime from the API list_directories_and_files?

**Comment by mccoyp** [comment]
Hi @yangchengs, thank you for opening an issue! I'll tag the appropriate folks so we can take a look at this as soon as possible.

**Comment by xiafu-msft** [comment]
Hi @yangchengs

Thanks for reaching out. This is a new feature which hasn't been released yet. The release will happen this week (probably today)
