### ISSUE TITLE
Is it possible to get the message count of a sepcific service bus queue

### ISSUE THREAD

**Issue by ForrestIsARealGoodman** [Azure/azure-sdk-for-python#19900]
**Is your feature request related to a problem? Please describe.**
I am stuck at how to get the message acount of a sevice bus queue.
Seems no regarding function could be found in current module "service bus".

**Describe the solution you'd like**
Here is a sample requirements:
I have a program that would send messages to a queue routinely, while at the same time, it will check the message count of its deadletter ("subqueue") and stop sending out the message if the count hit the given limitation (which means a lot of messages failed to be provessed).

**What are needed**
Current message count of sender queue.
Current message count of deadletter queue.

**Additional context**
n/a

**Comment by mccoyp** [comment]
Hi @ForrestIsARealGoodman, thank you for opening an issue! I'll tag the appropriate folks so we can take a look as soon as possible.

**Comment by ForrestIsARealGoodman** [comment]
@mccoyp , thanks for your quick response!
@yunhaoling your help and effort are highly appreciated!

**Comment by yunhaoling** [comment]
hey @ForrestIsARealGoodman , you could use `azure.servicebus.management.ServiceBusAdministrationClient` to retrieve the runtime properties of a queue which includes the message count info.

samples could be found here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_queue.py#L74

please let me know if I could help more.

**Comment by ForrestIsARealGoodman** [comment]
> hey @ForrestIsARealGoodman , you could use [azure.servicebus.management.ServiceBusAdministrationClient.get_queue_runtime_properties](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.management.html#azure.servicebus.management.ServiceBusAdministrationClient.get_queue_runtime_properties) method to retrieve the runtime properties of a queue ([QueueRuntimeProperties](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.management.html#azure.servicebus.management.QueueRuntimeProperties)) which includes the message count and dead letter message count that you want.
> 
> samples could be found here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_queue.py#L74
> 
> please let me know if I could help more.

Yes!!!!!!! This is what I want, highly appreciate your help!
