### ISSUE TITLE
KeyVault : verifying es256 without azure credentials ?

### ISSUE THREAD

**Issue by christopheblin** [Azure/azure-sdk-for-python#19924]
I'm trying to validate that I can verify signatures without using the Azure REST API

I have 2 problems and I cannot find any doc or test around them, so I'm trying to get some help here...

First, I need to load the key from a PEM file (the PEM file is available through az keyvault key download --vault-name xxx -n tmp -e PEM -f key.pem) I give the PEM below

Second, I need to verify the key without providing azure credentials (and the best would be without azure sdk at all)

Enough talk, here is the code

```
from azure.identity import DefaultAzureCredential
from azure.keyvault.keys import KeyClient
from azure.keyvault.keys.crypto import CryptographyClient, SignatureAlgorithm

import base64
import hashlib
import sys
import logging

logger = logging.getLogger('azure')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler(stream=sys.stdout))

# anyway to replace the call to azure by loading the PEM file ?
credential = DefaultAzureCredential()
key_client = KeyClient(vault_url="https://maasify.vault.azure.net/", credential=credential)
key = key_client.get_key("tmp")
print("key retrieved successfully")

#provide credential, but they are not used (any way to provide something fake here ?)
#note that I can say they are not used because logging does not output anything after "key retrieved successufully"...
crypto_client = CryptographyClient(key, credential=credential) 
digest = hashlib.sha256(b"Hello world").digest()

signature = base64.b64decode("bxw1nS8Q39mnQVkAhvJctXuLHz4n0wUjLbE+phj1XlUeWDxl7DCK5bG4d7YrL7zGtAnUq3YT9AdrrAXjpwhCzQ==")
verified = crypto_client.verify(SignatureAlgorithm.es256, digest, signature)
assert verified.is_valid
print("verified")
```

the output looks like 
```
Environment is configured for ClientSecretCredential
ManagedIdentityCredential will use IMDS
Request URL: 'https://maasify.vault.azure.net/keys/tmp/?api-version=REDACTED'
Request method: 'GET'
...
Response status: 401
...
Request URL: 'https://login.microsoftonline.com/e5d987e4-a985-4364-9405-52e2d9d4e503/v2.0/.well-known/openid-configuration'
Request method: 'GET'
...
Response status: 200
...
Request URL: 'https://login.microsoftonline.com/common/discovery/instance?api-version=REDACTED&authorization_endpoint=REDACTED'
Request method: 'GET'
...
Response status: 200
Request URL: 'https://login.microsoftonline.com/e5d987e4-a985-4364-9405-52e2d9d4e503/oauth2/v2.0/token'
Request method: 'POST'
...
Response status: 200
...
ClientSecretCredential.get_token succeeded
EnvironmentCredential.get_token succeeded
DefaultAzureCredential acquired a token from EnvironmentCredential
Request URL: 'https://maasify.vault.azure.net/keys/tmp/?api-version=REDACTED'
Request method: 'GET'
...
Response status: 200
...
key retrieved successfully
verified
```

Here is the PEM
```
% cat key.pem 
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOC76WxZ/TMzJnRqv/cy9llDqSIMW
lplgREY3jMxDCksPGDDyepeg7fFdCu56N9Br9n5oWmj/iKULrglQehGiiA==
-----END PUBLIC KEY-----
```

Here is the test without Azure SDK with `pip install ecdsa` 

```
import base64
import ecdsa
import hashlib

digest = hashlib.sha256(b"Hello world").digest()
with open("key.pem") as f:
   public_key = ecdsa.VerifyingKey.from_pem(f.read())
signature = base64.b64decode("bxw1nS8Q39mnQVkAhvJctXuLHz4n0wUjLbE+phj1XlUeWDxl7DCK5bG4d7YrL7zGtAnUq3YT9AdrrAXjpwhCzQ==")

public_key.verify(signature, digest)
```

but there is `ecdsa.keys.BadSignatureError: Signature verification failed`

Here is a test in typescript that tries exactly the same thing and also fails : 

```
it.only('local HSM verif PEM', () => {
    const content = Buffer.from('Hello world');
    const hash = crypto.createHash('sha256');
    hash.update(Buffer.from(content));
    const digest = hash.digest();
    const sig =
      Buffer.from('bxw1nS8Q39mnQVkAhvJctXuLHz4n0wUjLbE+phj1XlUeWDxl7DCK5bG4d7YrL7zGtAnUq3YT9AdrrAXjpwhCzQ==', 'base64');
    const pem = fs.readFileSync('key.pem');
    const publicKey = crypto.createPublicKey(pem);

    const verifyLocal = crypto.createVerify('sha256');
    verifyLocal.update(digest);
    const verifLocal = verifyLocal.verify(publicKey, sig);
    expect(verifLocal).toBe(true); //does not work
  });
```

-> there is something that the azure python sdk does differently to verify signatures, but I do not find what ...

**Comment by mccoyp** [comment]
Hi @christopheblin, thank you for opening an issue! I'll look into this and provide an update as soon as possible.

**Comment by mccoyp** [comment]
To answer part of your question, you can verify with es256 without a credential, given you have the JWK of your key. CryptographyClient has a [from_jwk](https://docs.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys.crypto.cryptographyclient?view=azure-python#from-jwk-jwk-) factory method that will return a client that performs only local cryptography operations, which means you don't need to provide any Azure credentials. 

You're right that the `verify` operation doesn't make a service call in this case when using a standard CryptographyClient though -- that's because the client will attempt to perform operations locally, and only fall back to the service if it's unable to. The credential you provide to the default CryptographyClient constructor won't be validated until a service call is made, so you can provide any azure-identity credential instance, even if it's incorrectly configured. You'll just get a failure whenever there's a call to the service.

**Comment by mccoyp** [comment]
I've done some digging around but I haven't found a way to load an EC key from PEM format to JWK (which would be necessary to use local cryptography with the SDK). The example you included that uses `ecdsa` should work, though, if you use the method `VerifyingKey.verify_digest` instead of `verify` on the last line.
```python
import base64
import ecdsa
import hashlib

digest = hashlib.sha256(b"Hello world").digest()
with open("key.pem") as f:
   public_key = ecdsa.VerifyingKey.from_pem(f.read())
signature = base64.b64decode("bxw1nS8Q39mnQVkAhvJctXuLHz4n0wUjLbE+phj1XlUeWDxl7DCK5bG4d7YrL7zGtAnUq3YT9AdrrAXjpwhCzQ==")

public_key.verify_digest(signature, digest)
```

**Comment by christopheblin** [comment]
> though, if you use the method VerifyingKey.verify_digest instead of verify on the last line.

=> ah thank you it works !

> CryptographyClient has a from_jwk factory method

=> ah thank you, it also works ! 

```
crypto_client = CryptographyClient.from_jwk(key.key) #given that key is retrieved from KeyVault
```

Indeed, there is no way to use that from PEM, but I will ask to provide an endpoint to get the public key in JWK (which is obviously possible and desirable because this is the native format in Azure KeyVault)

I think the reason I use PEM is because in NodeJs crypto (our "main" language), it is the only supported way (even if it does not work :) )
