### ISSUE TITLE
Azure tables - Backup & Restore

### ISSUE THREAD

**Issue by 646826** [Azure/azure-sdk-for-python#19926]
** Is your feature request related to a problem? Please describe. **
No backup and restore option for data

** Describe the solution you'd like **
I want to be able to make a backup copy and restore it on demand

** Describe alternatives you've considered **
azCopy-7.3.1

** Additional context **

**Comment by mccoyp** [comment]
Hi @646826, thank you for opening an issue! We'll take a look at this as soon as possible.

**Comment by mccoyp** [comment]
Hi again -- it looks like this is a feature that would need to be implemented by the service before the SDK could expose it. I'll leave this issue open for tracking and tag the service team so they're aware of the feature request, but for now AzCopy is the recommended way to back up Tables data. Thank you again for opening this issue!

**Comment by YalinLi0312** [comment]
Hi @646826 , thanks for reaching us!

We have provided samples for table copy from/to storage blob([sync client](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/samples/sample_copy_table.py), [async client](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/samples/async_samples/sample_copy_table_async.py)), you can take them as reference.

Btw, we will support geo-redundancy for Tables Cosmos, you can expect an auto backup/restore once that feature is implemented.

I'll close this issue for now, if you have further questions for this issue, feel free to reopen and comment here. We'll take a look again.

Thanks
