### ISSUE TITLE
Packages should only be released if they will install successfully

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#19928]
Test installing a package that is about to be released before publishing to the package manager to ensure that, among other things, dependencies within the same service are all published. The test should run in isolation so that dependencies from the same service are only available if they are already published to the package manager.

**Comment by ckairen** [comment]
There's a bug in which the smoke test doesn't download the package version that just got released.

Downloaded Version:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1045637&view=logs&j=811de798-cac6-5a82-8dac-ad597ae5b1be&t=299c6ba1-91d4-5571-bc9b-ca88aacc6166&l=133

Published Version:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1045637&view=logs&j=8a59aa26-f1cb-5dea-999b-76ab4b63e138&t=2a0c1ff9-8f40-5875-8d33-2fedc244c604&l=140

**Comment by benbp** [comment]
Related to the bug fix:

We should understand more deeply why we are seeing a pip install delay, and verify if we can reproduce it locally (CC @scbedd for local scripting help). If we can't repro it locally, as is predicted, then we should figure out the difference, as adding a 10 minute delay to the release pipeline is something we should avoid if possible.

**Comment by weshaggard** [comment]
I would still like to follow-up on https://github.com/Azure/azure-sdk-for-python/pull/20294/files#r692482842. As it is currently implemented I don't believe there is any enforcement to ensure that the package we are trying to release is actually verified. We do `Get-ChildItem "$(Pipeline.Workspace)/${{ parameters.ArtifactName }}/${{ parameters.Artifact.name }}/*.zip"` but if there is some issue, like we change the layout in someway, we have no verification that ensures we don't quietly skip the update of the requirements and never verify the package we are planning to ship.
