### ISSUE TITLE
Trouble with Custom Vision in Python

### ISSUE THREAD

**Issue by ThorsteinSkaug** [Azure/azure-sdk-for-python#19935]
I have made an object detection program in the Custom Vision UI, and I am trying to utilize it with a python script. However, I get an error when trying to test the published model. The error code is as follows:

> CustomVisionErrorException: Operation returned an invalid status code 'Access Denied'

I am confident that my keys are correct. What other errors can yield this message?

Thanks!

**Comment by rakshith91** [comment]
@ThorsteinSkaug  Thanks for the feedback, we’ll investigate asap

**Comment by SaurabhSharma-MSFT** [comment]
@ThorsteinSkaug Apologies for the delayed response. I see that this issue is opened few months back and no further activity had taken place. So wanted to check if you are still facing this issue ? Please let us know.
