### ISSUE TITLE
KeyError: 'Endpoint'

### ISSUE THREAD

**Issue by autohnnaveen** [Azure/azure-sdk-for-python#19936]
I am using the SDK (Python) for Computer Vision published in Mocrosoft Docs

https://github.com/MicrosoftLearning/mslearn-ai900/blob/main/05%20-%20Optical%20Character%20Recognition.ipynb
When I run the code, this error occurs:

read_response = computervision_client.read(read_image_url,  raw=True)

KeyError                                  Traceback (most recent call last)
<ipython-input-7-6d5eaaca9481> in <module>
----> 1 read_response = computervision_client.read(read_image_url,  raw=True)

C:\ProgramData\Anaconda3\lib\site-packages\azure\cognitiveservices\vision\computervision\operations\_computer_vision_client_operations.py in read(self, url, language, pages, model_version, reading_order, custom_headers, raw, **operation_config)
    842 
    843         # Construct and send request
--> 844         request = self._client.post(url, query_parameters, header_parameters, body_content)
    845         response = self._client.send(request, stream=False, **operation_config)
    846 

C:\ProgramData\Anaconda3\lib\site-packages\msrest\service_client.py in post(self, url, params, headers, content, form_content)
    191         :param dict form_content: Form content
    192         """
--> 193         request = self._request('POST', url, params, headers, content, form_content)
    194         return request
    195 

C:\ProgramData\Anaconda3\lib\site-packages\msrest\service_client.py in _request(self, method, url, params, headers, content, form_content)
    106         :param dict form_content: Form content
    107         """
--> 108         request = ClientRequest(method, self.format_url(url))
    109 
    110         if params:

C:\ProgramData\Anaconda3\lib\site-packages\msrest\service_client.py in format_url(self, url, **kwargs)
    153         if not parsed.scheme or not parsed.netloc:
    154             url = url.lstrip('/')
--> 155             base = self.config.base_url.format(**kwargs).rstrip('/')
    156             url = urljoin(base + '/', url)
    157         return url

KeyError: 'Endpoint'

**Comment by rakshith91** [comment]
@autohnnaveen Thanks for the issue, we’ll investigate asap

**Comment by lmazuel** [comment]
Hi @autohnnaveen 
I believe your issue is because the endpoint your passed was incorrect, did you pass the default value of the notebook `YOUR_COG_ENDPOINT` or did you changed it to an actual value? 

I think with a proper value this would go away (though I don't deny the error could be better).
