### ISSUE TITLE
azure.mgmt.containerservice(latest version 16.0.0) cannot work in Azure China Cloud

### ISSUE THREAD

**Issue by simonxin** [Azure/azure-sdk-for-python#19951]
- **Package Name**:  azure.mgmt.containerservice
- **Package Version**:  16.0.0
- **Operating System**: Windows/Linux
- **Python Version**:  python 3.8

**Describe the bug**
when using azure.mgmt.containerservice to manage AKS cluster which is in Azure China Cloud, the credential request will be failed always

**To Reproduce**
1. run sample code as below:
from azure.identity import ClientSecretCredential, AzureAuthorityHosts
from azure.mgmt.containerservice import ContainerServiceClient
from msrestazure.azure_cloud import AZURE_CHINA_CLOUD

subscription_id = "f7495f2c-3985-4e3e-b250-e8a1b27d5926"
credentials = ClientSecretCredential(
    client_id='7afe9eee-9e65-4b8a-854d-4ceb2fdedd03',
    client_secret='XXXXXXXXXXXXXXXXX',
    tenant_id="2cbcf857-5096-4909-a7a9-37fcc567abab",
    authority=AzureAuthorityHosts.AZURE_CHINA
)

resourceManager_url = AZURE_CHINA_CLOUD.endpoints.resource_manager
aks_client = ContainerServiceClient(credentials, subscription_id, base_url=resourceManager_url)

rgName = "Architecture-Test"
aksName = "test-aks-cluster"
aksget = aks_client.managed_clusters.get(rgName, aksName)
print(aksget)

**Expected behavior**
A valid access_token is returned. 

**Screenshots**
below error will return
![image](https://user-images.githubusercontent.com/34259289/127092340-6b1db82d-5e7e-48b8-a8a7-101a465a7c78.png)

**Additional context**
hard coded credential_scope to use public Azure resource manager Url.

code line：
self.credential_scopes = kwargs.pop('credential_scopes', ['https://management.azure.com/.default'])
code path: 
https://github.com/Azure/azure-sdk-for-python/blob/a8fd00bb50687494841b3caee0519dd39ca7046c/sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/_configuration.py#L25

it is expected to allow resource manger Url override when create configuration for credential token.

**Comment by rakshith91** [comment]
@simonxin Thanks for the feedback, we’ll investigate asap

**Comment by lmazuel** [comment]
Hi @simonxin ,

This doc should help you, you need to pass the credential_scopes kwargs:
https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-sovereign-domain

Thanks,

Laurent
