### ISSUE TITLE
azure.mgmt.containerregistry create Token with no Passwords Generated

### ISSUE THREAD

**Issue by Ayatallah** [Azure/azure-sdk-for-python#19958]
- **Package Name**:  azure.mgmt.containerregistry
- **Package Version**: 2020-11-01-preview
- **Operating System**: MacOs
- **Python Version**: 3.6

**Describe the bug**
I followed Code Samples in [here](https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/containerregistry/manage_token.py)
To create [Token](https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerregistry/azure.mgmt.containerregistry.v2020_11_01_preview.models.token?view=azure-python) assigned to specific ScopeMap in Azure Container Registry. Using begin_create method, a token was created successfully and assigned to the correct scopemap, however, password1 and password2 do not get generated and output as expected. Unlike, when running az cli command to create token, **"az acr token create --name tokenName --registry registryName --scope-map scopemapName"** 2 passwords get generated and output.

**To Reproduce**
Behavior can be reproduced in any of the following 3 scenarios:
1. 
```import os

from azure.identity import DefaultAzureCredential
from azure.mgmt.containerregistry import ContainerRegistryManagementClient
from azure.mgmt.resource import ResourceManagementClient

SUBSCRIPTION_ID = os.environ.get("SUBSCRIPTION_ID", None)
GROUP_NAME = "testgroupx"
TOKEN = "tokenxxyyzz"
REGISTRIES = "registriesxxyyzz"
SCOPE_MAP = "scopemapxxyyzz"

resource_client = ResourceManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID
)
containerregistry_client = ContainerRegistryManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID,
        api_version="2020-11-01-preview"
)
scope_map = containerregistry_client.scope_maps.get(
        GROUP_NAME,
        REGISTRIES,
        SCOPE_MAP
)  

# Get already existing registry and already existing scopemap and use them to create token
token = containerregistry_client.tokens.begin_create(
        GROUP_NAME,
        REGISTRIES,
        TOKEN,
        {
          "scope_map_id": scope_map.id,
          "status": "enabled",
        }
).result()
print("Create token:\n{}".format(token))
```
2-
```import os

from azure.identity import DefaultAzureCredential
from azure.mgmt.containerregistry import ContainerRegistryManagementClient
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.containerregistry.v2020_11_01_preview.models import TokenCredentialsProperties
from azure.mgmt.containerregistry.v2020_11_01_preview.models import TokenPassword

SUBSCRIPTION_ID = os.environ.get("SUBSCRIPTION_ID", None)
GROUP_NAME = "testgroupx"
TOKEN = "tokenxxyyzz"
REGISTRIES = "registriesxxyyzz"
SCOPE_MAP = "scopemapxxyyzz"

resource_client = ResourceManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID
)
containerregistry_client = ContainerRegistryManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID,
        api_version="2020-11-01-preview"
)
scope_map = containerregistry_client.scope_maps.get(
        GROUP_NAME,
        REGISTRIES,
        SCOPE_MAP
)  

pass1= TokenPassword(
name=”password1”
)
pass2= TokenPassword(
name=”password2”
)
passes = TokenCredentialsProperties(
passwords= [pass1, pass2]
)

# Get already existing registry and already existing scopemap and use them to create token
token = containerregistry_client.tokens.begin_create(
        GROUP_NAME,
        REGISTRIES,
        TOKEN,
        {
          "scope_map_id": scope_map.id,
          "status": "enabled",
          "credentials":passes
        }
).result()
print("Create token:\n{}".format(token))
```

3-
```import os

from azure.identity import DefaultAzureCredential
from azure.mgmt.containerregistry import ContainerRegistryManagementClient
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.containerregistry.v2020_11_01_preview.models import GenerateCredentialsParameters

SUBSCRIPTION_ID = os.environ.get("SUBSCRIPTION_ID", None)
GROUP_NAME = "testgroupx"
TOKEN = "tokenxxyyzz"
REGISTRIES = "registriesxxyyzz"
SCOPE_MAP = "scopemapxxyyzz"

resource_client = ResourceManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID
)
containerregistry_client = ContainerRegistryManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID,
        api_version="2020-11-01-preview"
)
scope_map = containerregistry_client.scope_maps.get(
        GROUP_NAME,
        REGISTRIES,
        SCOPE_MAP
)  

# Get already existing registry and already existing scopemap and use them to create token
token = containerregistry_client.tokens.begin_create(
        GROUP_NAME,
        REGISTRIES,
        TOKEN,
        {
          "scope_map_id": scope_map.id,
          "status": "enabled",
        }
).result()
print("Create token:\n{}".format(token))

passgn = GenerateCredentialsParameters()
passgn.name='password1'
passgn.token_id=token.id
passgn2 = GenerateCredentialsParameters()
passgn2.name='password2'
passgn2.token_id=token.id
gen_pass = registry_client.registries.begin_generate_credentials(
                     GROUP_NAME,
                     REGISTRIES,
                     passgn
)
gen_pass2 = registry_client.registries.begin_generate_credentials(
                     GROUP_NAME,
                     REGISTRIES,
                     passgn2
)
```

**Expected behavior**
1- In scenario 1, I expected the token to be created with proper name given and assigned to the proper scopemap given with 2 passwords password1 and password2 generated and output to me
2- In scenario 2, I expected the token to be created with proper name given and assigned to the proper scopemap given with 2 passwords password1 and password2 generated and output to me
3- In scenario 3, I expected the token to be created with proper name given and assigned to the proper scopemap given with 2 passwords password1 and password2 generated and output to me

**Screenshots**
1- In scenario 1, token created successfully and assigned to the correct scopemap but none of the passwords were generated
2- In scenario 2, exception below arose 
<img width="1386" alt="Screen Shot 2021-07-27 at 10 59 16 AM" src="https://user-images.githubusercontent.com/10837400/127142345-7faf9f05-b134-410e-8920-f05d9d78177e.png">

3- In scenario 3, I tried to use generateCredentials as the exception above instructed, I found it in begin_generate_credentials methods [here](https://github.com/Azure/azure-sdk-for-python/blob/bbf08d350c1325c1177c728a46847758ae61241a/sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2020_11_01_preview/operations/_registries_operations.py#L1122) but the exception below arose 
<img width="1440" alt="Screen Shot 2021-07-27 at 12 54 27 PM" src="https://user-images.githubusercontent.com/10837400/127142587-1c0d6c43-d4b7-4e85-8644-9376bae5e103.png">

**Additional context**
I need to be able to create Token for Specific ScopeMap in ACR with its passwords automatically generated, as same as, the result of this az cli command **"az acr token create --name tokenName --registry registryName --scope-map scopemapName"**

**Comment by rakshith91** [comment]
@Ayatallah Thanks for the issue, we’ll investigate asap

**Comment by BigCat20196** [comment]
Hi @Ayatallah Thanks for the feedback.

In Azure-cli, run the `az acr token create --name tokenName --registry registryName --scope-map scopemapName` command to automatically generate a password because it has a built-in method to generate a key. The direct use of SDK will not automatically generate passwords.

If you need a password, you need to execute `begin_generate_credentials` method in azure.mgmt.containerregistry.RegistriesOperations.

Here is the document : [https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerregistry/azure.mgmt.containerregistry.v2021_06_01_preview.operations.registriesoperations?view=azure-python#begin-generate-credentials-resource-group-name--registry-name--generate-credentials-parameters----kwargs-](url)

Hope this unblocks you.
BTW, If necessary, I can provide a detailed example later.

**Comment by BigCat20196** [comment]
Hi @Ayatallah Thanks for the feedback.

> RE: scenario 1 & 2

In Azure-cli, run the `az acr token create --name tokenName --registry registryName --scope-map scopemapName` command to automatically generate a password because it has a built-in method to generate a key. The direct use of SDK will not automatically generate passwords.

If you need a password, you need to execute begin_generate_credentials method in `azure.mgmt.containerregistry.RegistriesOperations`.

Here is the document : [https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerregistry/azure.mgmt.containerregistry.v2021_06_01_preview.operations.registriesoperations?view=azure-python#begin-generate-credentials-resource-group-name--registry-name--generate-credentials-parameters----kwargs-](url)

> RE: scenario 3

The python SDK has a password protection mechanism and will not directly display the password.
A compromised solution is to directly access the password value, such as you can use `print(gen_pass.passwords[0].value)`

Hope this unblocks you.
BTW, If you want more detailed examples, I can provide them later.

**Comment by Ayatallah** [comment]
> Hi @Ayatallah Thanks for the feedback.
> 
> > RE: scenario 1 & 2
> 
> In Azure-cli, run the `az acr token create --name tokenName --registry registryName --scope-map scopemapName` command to automatically generate a password because it has a built-in method to generate a key. The direct use of SDK will not automatically generate passwords.
> 
> If you need a password, you need to execute begin_generate_credentials method in `azure.mgmt.containerregistry.RegistriesOperations`.
> 
> Here is the document : [https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerregistry/azure.mgmt.containerregistry.v2021_06_01_preview.operations.registriesoperations?view=azure-python#begin-generate-credentials-resource-group-name--registry-name--generate-credentials-parameters----kwargs-](url)
> 
> > RE: scenario 3
> 
> The python SDK has a password protection mechanism and will not directly display the password.
> A compromised solution is to directly access the password value, such as you can use `print(gen_pass.passwords[0].value)`
> 
> Hope this unblocks you.
> BTW, If you want more detailed examples, I can provide them later.

@BigCat20196 Thanks for your reply! Actually, I have tried begin_generate_credentials method but It was not recognized as callable method in azure.mgmt.containerregistry.RegistriesOperations please find below the exception and the code and let me know if there's anything needs to be fixed 

Exception: 
<img width="1440" alt="Screen Shot 2021-07-27 at 12 54 27 PM" src="https://user-images.githubusercontent.com/10837400/127294552-6b3db7ed-add7-4b6e-be96-5adb22b0c1b5.png">

Code: 
```

from azure.identity import DefaultAzureCredential
from azure.mgmt.containerregistry import ContainerRegistryManagementClient
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.containerregistry.v2020_11_01_preview.models import GenerateCredentialsParameters

SUBSCRIPTION_ID = os.environ.get("SUBSCRIPTION_ID", None)
GROUP_NAME = "testgroupx"
TOKEN = "tokenxxyyzz"
REGISTRIES = "registriesxxyyzz"
SCOPE_MAP = "scopemapxxyyzz"

resource_client = ResourceManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID
)
containerregistry_client = ContainerRegistryManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID,
        api_version="2020-11-01-preview"
)
scope_map = containerregistry_client.scope_maps.get(
        GROUP_NAME,
        REGISTRIES,
        SCOPE_MAP
)  

# Get already existing registry and already existing scopemap and use them to create token
token = containerregistry_client.tokens.begin_create(
        GROUP_NAME,
        REGISTRIES,
        TOKEN,
        {
          "scope_map_id": scope_map.id,
          "status": "enabled",
        }
).result()
print("Create token:\n{}".format(token))

passgn = GenerateCredentialsParameters()
passgn.name='password1'
passgn.token_id=token.id
passgn2 = GenerateCredentialsParameters()
passgn2.name='password2'
passgn2.token_id=token.id
gen_pass = registry_client.registries.begin_generate_credentials(
                     GROUP_NAME,
                     REGISTRIES,
                     passgn
)
gen_pass2 = registry_client.registries.begin_generate_credentials(
                     GROUP_NAME,
                     REGISTRIES,
                     passgn2
)

```

**Comment by BigCat20196** [comment]
@Ayatallah 
What is client `registry_client` in the last two lines of your code?
You can try changing them to `containerregistry_client` And run it again.

**Comment by Ayatallah** [comment]
> @Ayatallah
> What is client `registry_client` in the last two lines of your code?
> You can try changing them to `containerregistry_client` And run it again.

@BigCat20196 they're the same thing, excuse the confusion in the variable names, still the same exception arise!

**Comment by Ayatallah** [comment]
Okay, I changed the version below :
```
containerregistry_client = ContainerRegistryManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID,
        api_version="2020-11-01-preview"
)
```

from 2020-11-01-preview to 2021-06-01-preview and it works fine now!
