### ISSUE TITLE
[SchemaRegistry] Double encoding issue with json schema content

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#19955]
currently the schema content (e.g. avro schema is a json string by itself) is double encoded in the request that is sent out (as well as the response, the service takes raw bytes).

This is because the autorest being smart here with the content-type/json -- autorest generated code will double encode the json string for us.

see[recording](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.test_schema_basic.yaml#L3):
```
interactions:
- request:
    body: '"{\"namespace\":\"example.avro\",\"type\":\"record\"...
```

This is not correct. The service takes raw bytes, we should fix the double encoding issue with the request being '{"namespace":"example.avro","type":"record"...}'.

it also has something to do with the content type of the request, e.g. text/binary, application/json would be different

There're multiple ways to fix the issue:
- low level client
- update swagger
- update generated code to have custom logic on different input type

we should use low level client for long-term maintainability.

**Comment by ashishkaransingh** [comment]
Hello, 

I spent a lot of time understanding HTTPFunction trigger, integrated with event hub and now trying to consuming it using consumer group with python sdk.

Here when I print event ...
```
async def on_event(partition_context, event):

    print(event)
```

I see the following output:
**`{ body: '[{"measurement": "v2.analytics.queues.e25798c8-0d`**

Invalid JSON, I already formatted it to go as influxdb compliant format but due to body not double quoted it fails it errors out 
I cannot even use print(json.loads(str(event))[body])

Any advise?

**Comment by yunhaoling** [comment]
hey @ashishkaransingh , could you call [EventData.body_as_str()](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/azure/eventhub/_common.py#L345) to check the content of the event instead of just `str(event)`?

or you could call [EventData.body_as_json()](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/azure/eventhub/_common.py#L369) if the body is of valid json content, and the method would give you the json dictionary.

the [`__str__`](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/azure/eventhub/_common.py#L149) is overloaded to return details event data infos.
