### ISSUE TITLE
Azureml Environment does not install additional conda dependencies on top of curated env built from dockerfile

### ISSUE THREAD

**Issue by dmarx** [Azure/azure-sdk-for-python#19960]
- **Package Name**: azureml-core
- **Package Version**: 1.3.2
- **Operating System**:
- **Python Version**: 3.7

**Describe the bug**

I am unable to install additional libraries as `CondaDependencies` on top of a registered environment built from a docker file. 

I first encountered this issue attempting to add libraries to a curated environment. After this first failure, I installed some libraries by modifying the dockerfile, which triggered a full rebuild of the environment\*. This customized environment was registered as a new version of the environment. I was again unable to install conda dependencies on top of this version as well.

\*PS: how would I reference one of my environment's docker images in a `FROM` clause in a docker file for a custom environment? I should be able to add a layer on top of an existing container rather than building the whole container from scratch off the MS base image

**To Reproduce**

```
from azureml.core import Experiment, Workspace, Environment, ScriptRunConfig
from azureml.core.conda_dependencies import CondaDependencies

exp_name = "reproduce_env_error"
compute_target_name = 'damarx1-aml-gpu-small'

ws = Workspace.from_config()
exp = Experiment(ws, exp_name)
compute_target = ws.compute_targets[compute_target_name]

# 1. Create a new environment by cloning a curated environment

base_env_name = 'AzureML-pytorch-1.7-ubuntu18.04-py37-cuda11-gpu'
base_env = Environment.get(workspace=ws, name=base_env_name)
env = base_env.clone("environment-error-test")

# 2. Add user managed dependencies

addl_deps = CondaDependencies()
pip_packages = ['datasets', 'transformers', 'loguru']
for p in pip_packages:
    addl_deps.add_pip_package(p)
env.python.conda_dependencies=addl_deps

# 3. register and build the environment - I believe this step is building the docker image but not installing user managed dependencies afterwards.

env.register(workspace=ws)

build = env.build(workspace=ws)
build.wait_for_completion(show_output=True)

# 4. submit a training job invoking this environment that imports the additional dependencies

with open('train.py', 'w') as f:
    f.write("import datasets; import transformers; import loguru;")

src = ScriptRunConfig(
    source_directory=".", 
    script="train.py", 
    compute_target=compute_target ,
    environment=env
    )

run = exp.submit(src)
```

The run fails, encountering the following exception per 70_driver_log.txt:

```
[2021-07-27T16:45:30.345937] Preparing to call script [train.py] with arguments:[]
[2021-07-27T16:45:30.345963] After variable expansion, calling script [train.py] with arguments:[]



[2021-07-27T16:45:30.360141] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
1 items cleaning up...
Cleanup took 0.060993194580078125 seconds
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import datasets; import transformers; import loguru;
ModuleNotFoundError: No module named 'datasets'

[2021-07-27T16:45:30.579173] Finished context manager injector with Exception.
```

**Expected behavior**

1. I expect the cloned environment to recognize the unmodified docker file, pull the pre-built image of the curated environment from the global registry, then install my user managed dependencies on top of that.
2. For the case where I modified the docker file, I expect a container to be built from the dockerfile, then my user-specified dependencies should be installed into that container, and finally the full image with my CondaDependencies should be cached for reuse and registered to my workspace when I submit the experiment.
3. Given an environment registered to my workspace that was built from a custom dockerfile, there should be a simple way for me to reference that resulting image in subsequent dockerfiles if I want to add components to the environment, rather than fully rebuilding as if the other image doesn't exist.

**Additional context**

This is my personal github account. I'm a FTE Microsoft Data Scientist in World Wide Learning: damarx@microsoft.com

Preferred mode of contact is Teams chat, happy to grant access to my azureml workspace for debugging.

**Comment by dmarx** [comment]
possibly related to issue #19500

**Comment by dmarx** [comment]
Please re-triage this as a bug...

**Comment by luigiw** [comment]
Closing legacy issue.

Please consider upgrading to AzureML v2 CLI/SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2
