### ISSUE TITLE
Azure table copy

### ISSUE THREAD

**Issue by 646826** [Azure/azure-sdk-for-python#19974]
**Is your feature request related to a problem? Please describe.**
I can not copy tables in blob or other azure tables

**Describe the solution you'd like**
I want to be able to copy the azure table to blob
I want to be able to copy an azure table to other tables
I want to be able to copy the azure table to another storage account

**Describe alternatives you've considered**
- Azure storage explorer 1.20.1
- AzCopy 7.3.1 (old version)

**Additional context**

**Comment by rakshith91** [comment]
Thank you for posting the issue! we'll take a look at it soon

**Comment by seankane-msft** [comment]
@646826 I'm looking into this request, there is not any functionality in the SDK right now to do that. When you say "I want to be able to copy the azure table to blob", do you want to copy the data in a json format or in binary format? Could you provide more details on these copies?

**Comment by 646826** [comment]
Hi @seankane-msft, the main idea is to put the archived data from Azure tables in an Azure blob.
I have a realization to backup Azure Tables to Azure Blob. 
![image](https://user-images.githubusercontent.com/1565611/129137175-50f371c3-437d-4575-b50c-def9a6aa7432.png)
But I want to improve this process and I am considering different options, example I try to research getting the stream from Azure Tables to use create_blob_from_stream. Good realization can be if we have stream from a source put this stream in compressed and compressed stream write in blob

**Comment by lmazuel** [comment]
Hi @646826 
We re-discussed this issue today with @annatisch , and we concluded that the service do not support the feature, and we don't want to implement the feature in SDK. However, it's fair that we provide a sample of the scenario for informational purposes. I'm keeping this issue open as the action item to provide a sample. 
Thanks!
