### ISSUE TITLE
AzureML allow filtering dataset by name

### ISSUE THREAD

**Issue by davystrong** [Azure/azure-sdk-for-python#19976]
**Is your feature request related to a problem? Please describe.**
I can't find any way of filtering a FileDataset by filename.

**Describe the solution you'd like**
I'd like to be able to use the `filter` method to filter a FileDataset by filename and return the filtered data as a new FileDataset object, while still accessing the original data (so no copies). This could then be passed to a new Pipeline step.

**Describe alternatives you've considered**
The only other options I see are a) manually creating a FileDataset from files by listing the files in the original dataset and specifying each file with its corresponding Datastore. This is really annoying because there is no way to obtain the original Dataset's Datastore (even though it is used internally by __str__ and __repr__ - this method would become viable, if ugly, if this were exposed to the public API); or b) pass the original Dataset to the Pipeline step along with a list of filepaths it should work on... Which seems like a terrible solution but is ultimately what I'm going with currently.

**Additional context**
Obviously it doesn't specifically have to be the `filter` method, it's just the one that is most similar to what I want.

**Comment by davystrong** [comment]
Actually, for the second alternative approach I mentioned to be viable, I would also need to know the path of the FileDataset items within the Datastore.

**Comment by ynpandey** [comment]
@davystrong We have created a feature request in our backlog for this functionality.

**Comment by davystrong** [comment]
Great, looking forward to that! Thanks!

**Comment by davystrong** [comment]
Just to give some additional context, my aim is to split a dataset (in training/validation or more splits) but the dataset contains both inputs and their labels as separate files so I can't just split randomly.

**Comment by luigiw** [comment]
The ask is added to backlog already. Closing for now.
