### ISSUE TITLE
Async credentials support CAE

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#19984]
They would need to claim client capability "CP1" in token requests and accept a `claims` keyword argument to `get_token()`. Sync credentials do this and rely on MSAL for the details. Doing the same for async credentials is blocked on AzureAD/microsoft-authentication-library-for-python#88

**Comment by pvaneck** [comment]
CP1 capabilities (i.e. CAE) were handled in the AAD Client via https://github.com/Azure/azure-sdk-for-python/pull/30777
