### ISSUE TITLE
Broken link to example

### ISSUE THREAD

**Issue by Goldensunboy** [Azure/azure-sdk-for-python#19991]
The page says "Here is an example for using POST with an Analytics query" but the link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90525a0e-cead-7b8f-9af7-72f404fdf94f
* Version Independent ID: 91c2a935-d552-f63c-da22-702ce943d280
* Content: [azure.applicationinsights.operations.QueryOperations class](https://docs.microsoft.com/en-us/python/api/azure-applicationinsights/azure.applicationinsights.operations.queryoperations?view=azure-python)
* Content Source: [docs-ref-autogen/azure-applicationinsights/azure.applicationinsights.operations.QueryOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-applicationinsights/azure.applicationinsights.operations.QueryOperations.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by rakshith91** [comment]
Thanks for the issue!! we'll look into it asap

**Comment by scbedd** [comment]
@Goldensunboy Yep. Looks like the package owners didn't realize that markdown links and sphinx links were not formatted the same way. Check it out [rendering oddly in our sphinx github.io docs too.](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-applicationinsights/0.1.0/azure.applicationinsights.operations.html#azure.applicationinsights.operations.query_operations.QueryOperations.execute)

I'm working up a PR to adjust all the instances I can find. I'd to talk to the real owners to understand if they think it's worth releasing a new version of the package, but we'll figure it out.

Thanks!

**Comment by scbedd** [comment]
Hey @Goldensunboy ,

I submitted a PR [over here](https://github.com/Azure/azure-sdk-for-python/pull/19993) that addresses the wonky links. I did do a quick search to find more examples, but only tracked down one other. You mind pointing me at the 

> It looks like multiple full "https" URLs all jammed into one.

you're talking about?

**Comment by Goldensunboy** [comment]
On the same page: "The Analytics query. Learn more about the Analytics query syntax" (broken link)

On [this page](https://docs.microsoft.com/en-us/python/api/azure-applicationinsights/azure.applicationinsights.applicationinsightsdataclient?view=azure-python) there appears to be a missing link to the field "config" of type ApplicationInsightsDataClientConfiguration

**Comment by scbedd** [comment]
> On the same page: "The Analytics query. Learn more about the Analytics query syntax" (broken link)

Ok awesome I already got that one in my PR. 

> On this page there appears to be a missing link to the field "config" of type ApplicationInsightsDataClientConfiguration

👍  Known issue. Currently waiting on the docs.ms crew to ship their new generator. Any missing params or params  mislabeled with `required` will be fixed by that update.
