### ISSUE TITLE
Monitor Query Readme and Samples issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#20005]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-query/samples/async_samples/sample_log_query_client_async.py):
![image](https://user-images.githubusercontent.com/57166602/127641823-57061dad-02c6-485c-b1ef-aaed7a1e5a67.png)

Reason:
TypeError: ABCMeta object got multiple values for keyword argument 'client_id'

Suggestion:
Update to:
`credential  = DefaultAzureCredential()`

@jameszliao-msft, @lmazuel , @scottaddie , @srnagar , @rakshith91 and @jongio for notification.

**Comment by rakshith91** [comment]
Fixed
