### ISSUE TITLE
Azure-core regression `oldest` check is running extremely long

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#20039]
Just looking at the build output, this does not seem to make much sense. I believe there are a couple problem packages that are forcing the new `pip` resolver to waste a bunch of time backtracking the installed package. If it is a single package, need to see if we can add some hinting to speed this up. In the meantime, will extend the timeout yet again in an effort to get it building.

**Comment by xiangyan99** [comment]
Is this fixed?
