### ISSUE TITLE
azure-mgmt-appplatform: LICENSE missing

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20035]
- **Package Name**: azure-mgmt-appplatform
- **Package Version**: 6.1.0
- **Operating System**: Linux
- **Python Version**:  3.9

**Describe the bug**
The azure-mgmt-appplatform python package is missing a license file.

**Comment by tjprescott** [comment]
@major thanks for PR #20036, which addresses this!

**Comment by major** [comment]
> @major thanks for PR #20036, which addresses this!

You're welcome. Hopefully these bite-sized PRs are easier to manage than #19240. 🤭
