### ISSUE TITLE
Example for `chunks()`?

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-sdk-for-python#20033]
The example for `chunks()` is blank. Would be nice to have an example for downloading blobs chunk by chunk. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff81a6-05d8-0e71-a865-1ec9850e1d2d
* Version Independent ID: e1b09e06-bc09-d2d1-dc18-65540eea41b2
* Content: [azure.storage.blob.aio.StorageStreamDownloader class](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.aio.storagestreamdownloader?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.aio.StorageStreamDownloader.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-storage-blob/azure.storage.blob.aio.StorageStreamDownloader.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by tjprescott** [comment]
@SeaDude thank you for the report. We will investigate asap.

**Comment by xiafu-msft** [comment]
Hi @SeaDude 
Thanks for reaching out
please refer to this link https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py#L115-L123

let me know if you need any info
