### ISSUE TITLE
Follow-up: Is it possible to create a VM with OS disk type different than Premium SSD?

### ISSUE THREAD

**Issue by Jendker** [Azure/azure-sdk-for-python#20044]
My previous issue https://github.com/Azure/azure-sdk-for-python/issues/19786 was closed an I was unable to reopen it so I am opening here a new one.

Could you help me to specify the platform image parameters to use if I want to create a disk from the platform image (Ubuntu 18.04)? For now I was passing:

```
                'storage_profile': {
                    'image_reference': {
                        "offer": "UbuntuServer",
                        "publisher": "Canonical",
                        "sku": "18.04-LTS",
                        "urn": "Canonical:UbuntuServer:18.04-LTS:latest",
                        "urnAlias": "UbuntuLTS",
                        "version": "latest"
                    }
                },
```
But since `'image_reference` is now `osdisk` I have tried passing this information in the `'creation_data'`:

```
                'creation_data': {
                    'create_option': 'from_image',
                    "id": "/Subscriptions/{}/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/latest".format(self.subscription_id),
                }
            }
```
following this reference: https://docs.microsoft.com/en-us/rest/api/compute/disks/create-or-update#create-a-managed-disk-from-a-platform-image.
But I am getting:
```
Operation failed with status: 'Not Found'. Details: No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/<subscr_id>/resourceGroups/subscriptions/<subscr_id>/resourceGroups/doodad5effac/providers/Microsoft.Compute/disks/doodad-vm-disk?api-version=2020-05-01'.
```
I will be grateful for any hints!

**Comment by tjprescott** [comment]
Adding @Vaibhav-Agar who worked on the other issue.

**Comment by RAY-316** [comment]
hi @Jendker I successfully created the disk with this parameter
```    
diskParams = {
        'location': "West US",
        "properties": {
            "osType": "Linux",
            "creationData": {
                "createOption": "FromImage",
                "imageReference": {
                    "id": "/Subscriptions/{}/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage"
                          "/Offers/UbuntuServer/Skus/18.04-LTS/Versions/latest".format(subscription_id)
                }
            }
        }
    }
```

**Comment by Jendker** [comment]
Thank you for your answer!
I am still getting following error:

```
Operation failed with status: 'Not Found'. Details: No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/6c8075ac-6804-4336-8a99-50c71ce3faf3/resourceGroups/subscriptions/6c8075ac-6804-4336-8a99-50c71ce3faf3/resourceGroups/doodad116c87/providers/Microsoft.Compute/disks/doodad-vm-disk?api-version=2020-05-01'.
```
My assumption is that we are using too old API which does not support this functionality (we are using older `azure-mgmt-storage==11.2.0`, otherwise we would need to rewrite a large portion of our interface). Do you know what is the first `azure-mgmt-storage` version which supports this functionality so that I can test if it still works with our code?

**Comment by Vaibhav-Agar** [comment]
@tjprescott or @RAY-316 do either of you know?

**Comment by Jendker** [comment]
Just wanted to remind about this issue @tjprescott @RAY-316

**Comment by Jendker** [comment]
I don’t think the issue has been addressed yet. Could you please answer my question this comment https://github.com/Azure/azure-sdk-for-python/issues/20044#issuecomment-895564158

**Comment by BigCat20196** [comment]
Hi @Jendker, `azure-mgmt-container-11.2.0` corresponds to track1 version. The last version of `azure-mgmt-compute` that supports track1 is 14.0.0.

However, the update and maintenance of track1 has stopped. It is strongly recommended that you upgrade to the latest version. Although you may need to rewrite some code, track2 will bring you a better experience.

**Comment by Jendker** [comment]
Thank you for the response! Closing now.
