### ISSUE TITLE
After the request is sent, aiohttp closes the stream hence fails to rewind in retry

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#20040]
The particular async sample that the customer was running sends a receipt file stream in the request:

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_receipts_async.py#L49

The request is sent and the service indicates in the response that it should be retried. When it is retried, the async retry policy tries to rewind the body to the initial position here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L261-L269

As it turns out, after the first request is sent, aiohttp closes the stream and so the seek fails, kicking it out of the retry loop, thus raising the quota limit exceeded exception. I found an issue on the aiohttp repo confirming that behavior: https://github.com/aio-libs/aiohttp/issues/1907

It seems requests leaves the stream open and so rewinding the body on retry is not an issue in the sync library.

**Comment by lmazuel** [comment]
@xiangyan99 let's solve the problem like aiobotocore:
https://github.com/aio-libs/aiobotocore/blob/88a43098b1194bf759581acc710ad5bdbdd99a96/aiobotocore/_endpoint_helpers.py#L28-L34

IOW, a wrapper that ignore close, so we avoid aiohttp taking ownership

**Comment by xiangyan99** [comment]
@lmazuel Yalin proposed a work around in https://github.com/Azure/azure-sdk-for-python/pull/27413/files#diff-88ebf1ca1c5f592762e5578cd2f3ce7fa323a37c7d34eb09f33b260b5fb4b3bd and is waiting for architect feedback.

Basically it uses same mechanism that hacks the close method and takes over the ownership of the stream.

We will port it into core if it gets approval from our architects.
