### ISSUE TITLE
AsyncLROPoller returned by begin_stop_cluster and begin_start_cluster not working 

### ISSUE THREAD

**Issue by git999-cmd** [Azure/azure-sdk-for-python#20075]
- **Package Name**: azure.mgmt.containerservice.aio.ContainerServiceClient
- **Package Version**: 16.0.0
- **Operating System**: Ubuntu 18.0
- **Python Version**: 3.7.3

**Describe the bug**
I am trying to use the following apis to start/stop the cluster.

>cs_client.managed_clusters.begin_stop_cluster(...)
cs_client.managed_clusters.begin_start_cluster(...)

where cs_client is the ContainerServiceClient

Based on the documentation, the above aysnc methods return an AsyncLROPoller that can be used to monitor the Long Running Process. 

I am doing the following in an async method in my test program:

<pre>
poller = await cs_client.managed_clusters.begin_start_cluster(resource_group_name, cluster_name)
while not poller.done():
    print(f"Done={poller.done()} Status={poller.status()}")
    await asyncio.sleep(30)
final_result = await poller.result()
print(f"DONE!! Result={final_result}")
</pre>
    
The program does not exit the while loop even after the cluster is up and running fine. The following az cli shows the provisioning_state of the cluster is 'Succeeded' and power_state is 'Running'. All the agent pools in the cluster have provisioning_state as 'Succeeded' and power_state as 'Running'. 

>az aks show -n cluster_name -g resource_group_name
 
The test program continues to print the following even after the cluster was started. It prints every 30 seconds.

>Done=False Status=InProgress

I even used kubectl commands to check the health of the cluster and all pods were Running.

I waited for upto 30 minutes after all pods were Running but the test program never exited the while loop.
 
**To Reproduce**
Please see descripion above 

**Expected behavior**
When the cluster has successfully started, poller.done() must return True.

**Comment by tjprescott** [comment]
@git999-cmd, thank you for the report. @msyyc could you take a look and advise?

**Comment by msyyc** [comment]
Hi @BigCat20196 please help on the issue.

**Comment by BigCat20196** [comment]
Hi @git999-cmd , thanks for the feedback, we’ll investigate asap.

**Comment by BigCat20196** [comment]
Hi @git999-cmd 
According to my investigation, through `begin_start` and `begin_stop` the method runs, if no error is reported, it returns none,. The specific operation status cannot be captured in the middle.

The following is sample code:
```
start_clusters = containerservice_client.managed_clusters.begin_start(GROUP_NAME, MANAGED_CLUSTERS).result()

stop_clusters = containerservice_client.managed_clusters.begin_stop(GROUP_NAME, MANAGED_CLUSTERS).result()
```

If the above two values are empty, the corresponding command runs successfully.

**Comment by BigCat20196** [comment]
Close due to inactivity. Please feel free to open new issues if the solution still does not work for you.
