### ISSUE TITLE
Mypy doesn't work with azure-storage-blob

### ISSUE THREAD

**Issue by rnestler** [Azure/azure-sdk-for-python#20083]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.8.1
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.10

**Describe the bug**
If I want to use mypy to statically type check my Python code it fails to find the type information of the azure.storage.blob, despite that there are type comments in the module.

**To Reproduce**
1. `pip install azure-storage-blob==12.8.1 mypy==0.910`
2. `echo "from azure.storage.blob import ContainerClient" > test.py`
3. `mypy test.py`
    ```
    test.py:1: error: Skipping analyzing "azure.storage.blob": found module but no type hints or library stubs
    test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
    Found 1 error in 1 file (checked 1 source file)
    ```

**Expected behavior**
I expect mypy to find the type hints in the module.

**Additional context**

There seem to be type annotations in the [code](https://github.com/Azure/azure-sdk-for-python/blob/3d9c14789a5f468b3a1c8b57575e54cbdad708eb/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L72). I asked in the https://gitter.im/python/typing chat and was told that the issue is that there isn't a `py.typed` file in the package, which seems to be true, since I can't find it in `lib/python3.8/site-packages/azure/storage/blob`

**Comment by rnestler** [comment]
If I add the file manually with: `touch lib/python3.8/site-packages/azure/storage/blob/py.typed` mypy starts type checking, but apparently there are type errors in the package:
```
mypy test.py
/home/rnestler/.virtualenvs/tmp-d092a3c327eb19a/lib/python3.8/site-packages/azure/storage/blob/_serialize.py:44: error: Type signature has too few arguments
/home/rnestler/.virtualenvs/tmp-d092a3c327eb19a/lib/python3.8/site-packages/azure/storage/blob/_serialize.py:127: error: Type signature has too few arguments
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by tjprescott** [comment]
Thank you for the report, @rnestler. @xiafu-msft could you please take a look and advise?

**Comment by xiafu-msft** [comment]
Hi @tjprescott

Thanks for reporting this, we will try to fix it soon!

**Comment by rnestler** [comment]
@xiafu-msft any update on this? Also https://github.com/Azure/azure-sdk-for-python/pull/20084 is still open.

**Comment by xiafu-msft** [comment]
Hi @rnestler 

Sorry for the delay. Thanks for the pr! It looks great!

**Comment by dimbleby** [comment]
Now 12.9.0 has been released with the still-broken typing, so users who pick up the latest package and run mypy over their code are exposed to this.
```
ome/dch/.virtualenvs/atm-controller/lib/python3.8/site-packages/azure/storage/blob/_serialize.py:129: error: Type signature has too many arguments
/home/dch/.virtualenvs/atm-controller/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py:1407: error: Type signature has too few arguments
```

**Comment by polys** [comment]
Types for things under `azure.storage.blob.aio` seem broken as well.
I guess we have to pin to version 12.8.1 until typings are correct 😞

```python
from azure.storage.blob.aio import BlobServiceClient

error: "BlobServiceClient" has no attribute "__aenter__"
error: "BlobServiceClient" has no attribute "__aexit__"
```

```python
from azure.storage.blob.aio import ContainerClient

error: "ContainerClient" has no attribute "__aenter__"
error: "ContainerClient" has no attribute "__aexit__"

... incompatible type "azure.storage.blob._container_client.ContainerClient"; expected "azure.storage.blob.aio._container_client_async.ContainerClient"
```
(notice `mypy` suggesting importing from the private `_container_client_async`)

**Comment by Dreamsorcerer** [comment]
> `from_connection_string`'s return type doesn't seem aware of `aio`

It's just typed incorrectly, like most of this project. It claims to always return `BlobServiceClient` and never a subclass:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py#L150
Return type should be typed like:
```
_BSC = TypeVar("_BSC", bound=BlobServiceClient)
...
def from_connection_string(...) -> _BSC:
```

This project is not ready to have types exposed to users, there has clearly been no testing of it, not even the most rudimentary of mypy runs which give syntax errors.

**Comment by polys** [comment]
Just tried the [12.10.0b1](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-storage-blob_12.10.0b1) pre-release... there are still issues with typing 😞
```
site-packages\azure\storage\blob\_serialize.py:130: error: Type signature has too many arguments
site-packages\azure\storage\blob\_blob_client.py:1410: error: Type signature has too few arguments
site-packages\azure\storage\blob\aio\_blob_client_async.py:808: error: Type signature has too few arguments
```

Also, now `mypy` says `error: Need type annotation for "container_client"` wherever there's the pattern:
```python
container_client = ContainerClient.from_connection_string(...)
async with container_client:
    ...
```

**Comment by Dreamsorcerer** [comment]
> Maybe you could just disable typings again, release a working package, and only re-enable them when they're actually correct? #19739 (comment) suggests there's no testing in place, so why not wait until that's fixed?

As suggested before, this should really be using inline annotations for new/updated types as well, instead of comments. This would have avoided many of the typing errors that have occurred. The library does not claim to support Python 2 (which itself is long unsupported), so there's no reason to keep using this legacy format.

**Comment by tasherif-msft** [comment]
I have opened up a pr to resolve the issue https://github.com/Azure/azure-sdk-for-python/pull/21970
as for the `py.typed` file we added it to our `MANIFEST` starting 12.9.0b release, so you should be able to run `mypy` without having to create that file yourself manually. Could you please confirm this?

As for changing commented typing, given that the new way of typing is supported starting py>=3.5 we will be holding off on that in the meantime.

**Comment by polys** [comment]
Many thanks for that PR and the issue to validate all packages; much appreciated.

> as for the `py.typed` file we added it to our `MANIFEST` starting 12.9.0b release, so you should be able to run `mypy` without having to create that file yourself manually. Could you please confirm this?

Not sure if this question was for me... I don't fully understand what you are asking.

We are not doing anything manually.  Everything was working perfectly up to 12.8.1 — `mypy` was happily checking our codebases and was blissfully ignoring `azure-storage-blob`.

Then I guess you had `py.typed` added in 12.9.0 (even though the typings were bad) and `mypy` started failing after upgrading `azure-storage-blob`. Again, we didn't do anything manually other than upgrading `azure-storage-blob` to 12.9.0.

None of the workarounds people suggested in the various issues relating to this works for us. The following, for example, makes no difference at all:
```
[mypy-azure.storage.blob.*]
ignore_errors = True
```

So our options are either sticking with 12.8.1 until all typing issues are fixed, or disabling `mypy` for the entire codebase 🙁

That's why I suggested earlier potentially getting a release out without `py.typed`, and only add it back when types are actually working.

**Comment by tasherif-msft** [comment]
@polys that's a good suggestion, I will discuss with our team if we can remove the typed file until mypy is fully validated.

**Comment by ben-xD** [comment]
Hello team :), this problem still exists, can we re-open this MR to track it more accurately?

**Comment by rnestler** [comment]
I feel a bit bad about getting all of this started with my original issue after seeing how much trouble it caused :see_no_evil:

**Comment by Mchristos** [comment]
Is there any update regarding @polys comment above RE removing `py.typed`? I'm in the exact same situation and am forced to pin my version to the old 12.8.1
