### ISSUE TITLE
Samples for using mgmt SDK to add VNET integration and Private Endpoint for Azure App Service

### ISSUE THREAD

**Issue by Yangsh-w** [Azure/azure-sdk-for-python#20108]
We are trying to use the python management SDK to add **VNET Integration** and **Private Endpoint** to our **app service** during or after creating.

We followed this [document](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-web-app?tabs=cmd#4-write-code-to-provision-and-deploy-a-web-app) and successfully created the app service.

But we are not sure how to enable those 2 features mentioned above.

While checking the docs, we found [create_or_update_vnet_connection](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2016_08_01.operations.webappsoperations?view=azure-python#create-or-update-vnet-connection-resource-group-name--name--vnet-name--connection-envelope----kwargs-) and [begin_approve_or_reject_private_endpoint_connection](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_01_01.operations.webappsoperations?view=azure-python#begin-approve-or-reject-private-endpoint-connection-resource-group-name--name--private-endpoint-connection-name--private-endpoint-wrapper----kwargs-) which might meet our requirements.

However, we are not able to find any relating samples online for these 2 methods.
And when we try to test the methods in our project, the parameters in the docs are a little bit confusing. For example, `connection_envelope`, `**kwargs` in VNET method and `private_endpoint_wrapper` from the Private Endpoint method. What value should we put in them? there is no clear clarification or sample for them.

May I know if these are the exact methods I am looking for?
If yes, it would be much appreciated to share some samples showing how we could use them.

Thanks in advance!

**Comment by tjprescott** [comment]
@msyyc could you please advise?

**Comment by msyyc** [comment]
Hi @BigCat20196 please help on the issue.

**Comment by BigCat20196** [comment]
Hi @Yangsh-w 

Here is a sample about how to manage the web app
[https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/appservice/manage_web_app.py](url)

Hope this unblocks you.

**Comment by Yangsh-w** [comment]
Hi @BigCat20196,

Thank you very much for sharing the sample! Since the sample does not contain VNET or Private Endpoint, I assume we could do that in below part?
  
```
# Create web app
    web_app = web_client.web_apps.begin_create_or_update(
        GROUP_NAME,
        WEB_APP,
        {
          "location": "eastus",
          "server_farm_id": plan.id,
          "reserved": False,
          "is_xenon": False,
          "hyper_v": False,
          "site_config": {
            "net_framework_version":"v4.6",
            "app_settings": [
              {"name": "WEBSITE_NODE_DEFAULT_VERSION", "value": "10.14"}
            ],
            "local_my_sql_enabled": False,
            "http20_enabled": True
          },
          "scm_site_also_stopped": False,
          "https_only": False
        }
    ).result()
    print("Create web app:\n{}".format(web_app))
```
But I am not sure how we should set the format for VNET Integration and Private Endpoint in this part.
Would you please share some suggestions regarding this?

**Comment by Yangsh-w** [comment]
Hello @BigCat20196 ,

We successfully added the VNet Integration to our app with the following code:

```
    subnetid_VNET = os.environ["SUBNET_ID_VNET"]
    logging.info(f"subnet id {subnetid_VNET}")

    poller = app_service_client.web_apps.begin_create_or_update(RESOURCE_GROUP_NAME,
        WEB_APP_NAME,
        {
            "location": LOCATION,
            "server_farm_id": plan_result.id,
            "site_config": {
                "linux_fx_version": "python|3.8"
            },
            "virtualNetworkSubnetId": subnetid_VNET
        }
    )
```

However, we could not use the same method to add the private endpoint, because it is asking for a private endpoint connection which should be generated after we added the private endpoint.

Aslo, I think [begin_approve_or_reject_private_endpoint_connection](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_01_01.operations.webappsoperations?view=azure-python#begin-approve-or-reject-private-endpoint-connection-resource-group-name--name--private-endpoint-connection-name--private-endpoint-wrapper----kwargs-) might not be the method I am looking for, because it is looking for connection name too.

May I know if we have any build-in method in SDK to add private endpoint for web app? Or any other approach?

Thanks a lot!

**Comment by BigCat20196** [comment]
Hi @Yangsh-w 

Please refer to the example of Azure-cli first. Is it the result you want?（https://docs.microsoft.com/en-us/azure/app-service/scripts/cli-deploy-privateendpoint）

I guess you should use `network_client` if you want to add private endpoints. Then use `begin_approve_or_reject_private_endpoint_connection` method.

Here is an example to create a private endpoint: 
https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/network/endpoint/manage_private_endpoint.py

**Comment by Yangsh-w** [comment]
Thank you @BigCat20196 for updating!

We are now trying to do everything in mgmt SDK only, CLI might be our Plan B.

I suppose you are right about that we need to create private endpoint first and then approve it.

Please allow me some time to test the script and I will keep here updated.

Thanks again!

**Comment by BigCat20196** [comment]
Close due to inactivity. Please feel free to open new issues if the solution still does not work for you.
