### ISSUE TITLE
[Identity] Update Service Fabric testing documentation

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#20113]
Update managed identity testing documentation for Service Fabric with the following:

- [x] ACR accounts with uppercase letters in their name may have authentication issues -- make a brief warning about this
- [x] Add clearer instructions about how to set up the browser certificate necessary to access the SF Explorer (and specify that it's the certificate created earlier in the sample)
- [x] Add a troubleshooting section that at least covers how to respond to crashing applications/nodes

**Comment by xiangyan99** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/21370
