### ISSUE TITLE
Migrate Tables testsuite to new test proxy infra

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#20114]
Engsys team and our friend @scbedd worked on a new test proxy infra for all repos (for curious people the code is [here](https://github.com/Azure/azure-sdk-tools/tree/main/tools/test-proxy), but it's not necessary to read it for this issue).

This means we are moving away from "azure-devtools" and the VCRPy integration to use the new system. This implies a few changes in the code for tests on each packages:
- Change the inheritance from AzureTestCase to the new class
- This _may_ imply changing some "self.assertXXX" to `assert` keyword, since `assertXXXX` will become unavailable.
- Rewrite as necessary the sanitizers (if any) of that package in call to the test proxy\
- Record the tests with the new system (and remove the old recordings)
- Investigate any "live only tests" if any to see if they would work with the new system

Onboarding documentation is being written right now by @mccoyp. Given this document will be new, this is open to feedback and feedback should be done. @mccoyp will also present the onboarding documentation on August 12th to the SDK team.

Work is done when tests are running entirely under the new testsystem, and there is no usage anywhere of AzureTestCase in the Tables testsuite, will all live pipeline green.

Tables SDK is here:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/tables/azure-data-tables

**Comment by scbedd** [comment]
@YalinLi0312 please check out the branch [integrate-proxy](https://github.com/Azure/azure-sdk-for-python/tree/integrate-proxy). @seankane-msft made a bunch of progress on this. @mccoyp picked up after is working on keyvault tests with this same effort.

**Comment by YalinLi0312** [comment]
Fixed.
