### ISSUE TITLE
[Identity] Document the package can be used for more than the Azure SDKs

### ISSUE THREAD

**Issue by sadasant** [Azure/azure-sdk-for-python#20130]
Recently, the Azure SDK for TS/JS received requests from customers to improve our introductory paragraph in our Identity README to also mention that the Identity package could be used from applications not using the Azure SDK. We made the changes in our README here: https://github.com/Azure/azure-sdk-for-js/pull/16800. If you agree, we should do a similar change in the Identity README for Python

**Comment by xiangyan99** [comment]
@sadasant 

I think we decided that it was a known issue that we don't support B2C?

Known issues
This library doesn't support Azure AD B2C.

**Comment by sadasant** [comment]
@xiangyan99 That’s great feedback for the text of the PR!  — the intention of the update is to say that people should be able to use the Identity SDK independently of the other Azure SDKs. We have many users who do so.

**Comment by lmazuel** [comment]
MErged your PR @sadasant  ;)

**Comment by sadasant** [comment]
Thank you @lmazuel 🙏
