### ISSUE TITLE
ImdsCredential raises ServiceRequestError when connection refused

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#20137]
When one of its token requests gets no response from IMDS, ImdsCredential should raise ClientAuthenticationError. Currently it propagates whatever exception the pipeline raised, for example ServiceRequestError:

```py
import os
from azure.identity._credentials.imds import ImdsCredential

# causes the credential to skip the probe, and guarantees a request error
os.environ["AZURE_POD_IDENTITY_AUTHORITY_HOST"] = "https://localhost:37807"
ImdsCredential().get_token("scope")
```

```
Traceback (most recent call last):
  ...
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7fc365b51520>: Failed to establish a new connection: [Errno 111] Connection refused
```

I expect this is rare in the real world because it requires IMDS to have first responded to the probe request, which is to say the scenario is that IMDS was available but has stopped responding.

Changing the exception type could break some applications. Both ServiceRequestError and ClientAuthenticationError inherit AzureError, but an application could conceivably handle ServiceRequestError specifically.

**Comment by xiangyan99** [comment]
Close as won't fix.

Will revisit it if there is a customer report.
