### ISSUE TITLE
azure-mgmt-batchai: LICENSE file missing in pypi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20155]
- **Package Name**: azure-mgmt-batchai
- **Package Version**: 7.0.0b1
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The `LICENSE.txt` file is missing when azure-mgmt-batchai is packaged for pypi.

**Additional context**
I am preparing a pull request to fix this now.

**Comment by swathipil** [comment]
@major, thanks for the feedback and future contribution! Directing it to the right people, so they know!

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
