### ISSUE TITLE
azure-mgmt-compute: LICENSE missing in PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20159]
- **Package Name**: azure-mgmt-compute
- **Package Version**: 22.0.0
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The `LICENSE.txt` file is missing from azure-mgmt-compute when the package is pushed to PyPi.

**Additional context**
I'm preparing a PR now to add the license file.

**Comment by swathipil** [comment]
@major, thanks for the feedback and future contribution (again)! Directing it to the right people, so they know!

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
