### ISSUE TITLE
basic.py", line 298, in send     raise error azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x000001A45661BAF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by nomadinnovative** [Azure/azure-sdk-for-python#20150]
File "C:\Users\ranaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 298, in send
    raise error
**azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x000001A45661BAF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed**

**Comment by xiangyan99** [comment]
@nomadinnovative Thanks for reporting. [Errno 11001] getaddrinfo failed usually means the host name cannot be resolved.

Could you check your network settings (and DNS) and see if that can solve the problem?

Thanks.
