### ISSUE TITLE
what is scope here?

### ISSUE THREAD

**Issue by G-Gowtham** [Azure/azure-sdk-for-python#20153]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b5fb1b3-8c23-d3d9-f1a9-777ae5a1f290
* Version Independent ID: 9be048b7-abf7-098e-4412-fa1850a9053f
* Content: [azure.identity.AzureCliCredential class](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.azureclicredential?view=azure-python)
* Content Source: [docs-ref-autogen/azure-identity/azure.identity.AzureCliCredential.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-identity/azure.identity.AzureCliCredential.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by swathipil** [comment]
@G-Gowtham, thanks for your question!
@mccoyp should be able to provide you with more info on this!

**Comment by mccoyp** [comment]
Hi @G-Gowtham, thanks again for opening an issue! Scopes are described in detail in this [Permissions and consent in the Microsoft identity platform](https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent) documentation. The scope provided to `get_token` specifies the permissions you want to obtain for a resource. For example, to request a set of permissions for Azure Key Vault, you could specify a scope of `"https://vault.azure.net/.default"`.

`get_token` is called automatically when using a client though, so it's not necessary to call this method and provide a scope in most cases.
