### ISSUE TITLE
azure-mgmt-databoxedge: LICENSE missing in PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20161]
- **Package Name**: azure-mgmt-databoxedge
- **Package Version**:  1.0.0
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The `LICENSE.txt` file is missing from packages pushed to PyPi.

**Additional context**
I am preparing a PR to fix this now.

**Comment by swathipil** [comment]
@major, thanks for the feedback and future contribution (again)! Directing it to the right people, so they know!

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
