### ISSUE TITLE
azure-mgmt-iotcentral: LICENSE missing in PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20166]
- **Package Name**: azure-mgmt-iotcentral
- **Package Version**: 9.0.0b1
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The `LICENSE.txt` file is missing from the PyPi package.

**Additional context**
I am making a PR to fix this now.

**Comment by swathipil** [comment]
@major, thanks for the feedback and future contribution (again)! Directing it to the right people, so they know!

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
