### ISSUE TITLE
azure-mgmt-loganalytics: LICENSE missing in PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20168]
- **Package Name**:  azure-mgmt-loganalytics
- **Package Version**: 11.0.0
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The LICENSE file is missing from the azure-mgmt-loganalytics package in PyPi.

**Additional context**
I am making a PR to fix this now.

**Comment by swathipil** [comment]
@major, thanks for the feedback and future contribution (again)! Directing it to the right people, so they know!

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
