### ISSUE TITLE
azure-mgmt-recoveryservices: LICENSE missing from PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20177]
- **Package Name**: azure-mgmt-recoveryservices
- **Package Version**: 2.0.0
- **Operating System**: Linux 
- **Python Version**: 3.9.6

**Describe the bug**
The LICENSE file is missing from azure-mgmt-recoveryservices in PyPi.

**Additional context**
I am making a PR to fix this now.

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
