### ISSUE TITLE
azure-mgmt-rdbms: LICENSE missing from PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20175]
- **Package Name**: azure-mgmt-rdbms
- **Package Version**: 9.1.0b1
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The `LICENSE` file is missing from azure-mgmt-rdbms in PyPi.

**Additional context**
I am making a PR to fix this now.

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
