### ISSUE TITLE
azure-mgmt-policyinsights: LICENSE missing from PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20172]
- **Package Name**: azure-mgmt-policyinsights
- **Package Version**: 1.0.0
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The `LICENSE` file is missing from the PyPi package.

**Additional context**
I am making a PR to fix this now.

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
