### ISSUE TITLE
azure-mgmt-redis: LICENSE missing from PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20181]
- **Package Name**: azure-mgmt-redis
- **Package Version**: 13.0.0
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The `LICENSE` file is missing from azure-mgmt-redis in PyPi.

**Additional context**
I am making a PR for this now.

**Comment by msyyc** [comment]
same issue : https://github.com/Azure/azure-sdk-for-python/issues/20183
