### ISSUE TITLE
[Cosmos DB] `enable_cross_partition_query=False` and `...=None` behave differently

### ISSUE THREAD

**Issue by m-theisen** [Azure/azure-sdk-for-python#20199]
- **Package Name**: azure-cosmos
- **Package Version**: 4.2.0
- **Operating System**: Ubuntu 18.04 (via WSL)
- **Python Version**: 3.8.0

**Describe the bug**
When using a `continuation_token` on a query created by `query_items` setting the keyword-argument `enable_cross_partition_query` explicitly to `False` results in a `ValueError("continuation tokens are not supported for cross-partition queries.")` exception.

**To Reproduce**
1. Get a `container_client`
2. Run:
```python
items = container.query_items(
    "select * from c",
    enable_cross_partition_query=False,  # If this line is commented out or explicitly set to None it works
    max_item_count=1,
    partition_key="partitionName",
)

page_iterator = items.by_page()
result = next(page_iterator)
token = page_iterator.continuation_token

continuation_iterator = items.by_page(continuation_token=token)
new_result = next(continuation_iterator)

```
3. `ValueError("continuation tokens are not supported for cross-partition queries.")` is thrown

**Expected behavior**
I would expect that setting `enable_cross_partition_query` explicitly to `False` behaves the same as setting it to `None`. 

This is especially useful if the program determines at run-time if a cross-partition query is necessary or not, because I find it always clearer to deal with `True` and `False` and not `True` and `None` (where depending on the context it is not clear which behavior will be triggered by `None`).

**Additional context**
I was staring quite a while at my code to figure out why the SDK complained that I was attempting a cross-partition query despite explicitly disabling it. After checking the SDK-code a bit I found the combination of lines why the behavior differs:

In the [`query_items`-function](https://github.com/Azure/azure-sdk-for-python/blob/44b3e8439a7703eee3b361d219f52d18f655d897/sdk/cosmos/azure-cosmos/azure/cosmos/container.py#L344)
```python
        if enable_cross_partition_query is not None:
            feed_options["enableCrossPartitionQuery"] = enable_cross_partition_query
```
the argument value is added to the option-dictionary (as soon as it is not `None`).

In the [`_get_initial_continuation`-function](https://github.com/Azure/azure-sdk-for-python/blob/44b3e8439a7703eee3b361d219f52d18f655d897/sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/base_execution_context.py#L55)  where the error is raised:
```python
    def _get_initial_continuation(self):
        if "continuation" in self._options:
            if "enableCrossPartitionQuery" in self._options:
                raise ValueError("continuation tokens are not supported for cross-partition queries.")
```
Only the existence of the key but not its value is checked.

**Comment by swathipil** [comment]
@m-theisen thanks for your feedback! Routing this to the correct people.

**Comment by rnagpal** [comment]
@zfoster : Could you please look into this issue and respond?

**Comment by annatisch** [comment]
@southpolesteve - who is the best person to assign to cosmos issues going forward?
I can update the contributors list so the correct people get tagged.

**Comment by southpolesteve** [comment]
Kushagra Thapar

**Comment by rnagpal** [comment]
His github handle is : kushagraThapar

**Comment by rnagpal** [comment]
@kushagraThapar FYI

**Comment by Rodrigossz** [comment]
Hello @m-theisen 

We had a sync on this and we can't change the actual behavior now. It would be a breaking changing for all existing customers. We will add this difference behavior in the README file. Tks for the heads-up. We may change this in future versions.
