### ISSUE TITLE
can use use the sas url instead of using the storagename and storage key when try to do snapshot or delete blob and so on.

### ISSUE THREAD

**Issue by openandliu** [Azure/azure-sdk-for-python#202]
can use use the sas url instead of using the storagename and storage key when try to do snapshot or delete blob and so on.

**Comment by huguesv** [comment]
To anyone that has been wanting to use SAS or anonymous containers/blobs: Please have a look at the new functionality that's in for 0.11.0.
http://azure-sdk-for-python.readthedocs.org/en/latest/storage.html

It's not on PyPI yet, but it's in github master branch.  Please let us know if you've tried it.  I'll close this when we release 0.11 to PyPI (next week?).

**Comment by huguesv** [comment]
0.11.0 now on PyPI.
