### ISSUE TITLE
Add new properties to Log Analytics SDK

### ISSUE THREAD

**Issue by dhaiman** [Azure/azure-sdk-for-python#20200]
Please add Log Analytics Workspace missing properties to SDK.
Attaching last PR: https://github.com/Azure/azure-rest-api-specs/blob/56cd4784756e65c303ed7aba007ffa8c7540a587/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-10-01/Workspaces.json#L593

Thanks!

**Comment by lzchen** [comment]
@swathipil 
I believe this is mis-assigned.

**Comment by swathipil** [comment]
@lzchen, thanks for the heads up! will look into who should own this.

**Comment by swathipil** [comment]
@dhaiman - @srnagar has a better idea of who should be able to help you with this.

**Comment by yoramsinger** [comment]
@dabenhamMic can you please take a look. Thanks.

**Comment by dabenhamMic** [comment]
hey @yoramsinger , @dhaiman 
please follow these steps:

Open a ticket  [here](https://portal.azure-devex-tools.com/tools/request-api-release)
	a. Check all Languages that you need (Python)
	b.Paste the PR url from swagger update

**Comment by dabenhamMic** [comment]
Hi @dhaiman , please follow the above instructions I added.
