### ISSUE TITLE
wait_for_completion in environment.py does not wait for 'Queued' state

### ISSUE THREAD

**Issue by robert4os** [Azure/azure-sdk-for-python#20223]
- **Package Name**: azure.ml.core.environment
- **Package Version**: 1.33.0 
- **Operating System**: Linux
- **Python Version**: 3.6

**Describe the bug**

wait_for_completion in environment,py does not wait for 'Queued' but only a few of all possible states. This is unexpected behavior.
` while status in ('Running', "GettingOrProvisioningACR"):
`
The similar function wait_for_completion on Run implements this more stable by using 'RunStatus.get_running_statuses()' for all states a Run could be in.

 

**To Reproduce**

## fill up the queue
_build = env.build(ws, image_build_compute=compute_target)
_build = env.build(ws, image_build_compute=compute_target)
_build = env.build(ws, image_build_compute=compute_target)

## wait for queued build
_build = env.build(ws, image_build_compute=compute_target)
_build.wait_for_completion()

**Expected behavior**

wait should not exit on queued builds, but rather wait until completion (as in the func name)

**Comment by swathipil** [comment]
@robert4os - thanks for opening an issue! Routing this to the correct people.

**Comment by SaurabhSharma-MSFT** [comment]
@robert4os Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by robert4os** [comment]
@SaurabhSharma-MSFT Was the bug fixed then? Since the code is not open source, it is not straight forward to check. Our workaround was to write our own waiting method to wait for the correct Return state.

**Comment by robert4os** [comment]
What more feedback could I provide? Since the code is not open source, it is not straight forward to check.

**Comment by xiangyan99** [comment]
@azureml-github
