### ISSUE TITLE
Allow passing mount_options to as_mount()

### ISSUE THREAD

**Issue by davystrong** [Azure/azure-sdk-for-python#20222]
**Is your feature request related to a problem? Please describe.**
I'm struggling to work with a large FileDataset in Azure ML Pipelines because when I pass the FileDataset to a step `as_mount`, it fills the cache (and the entire disk) and crashes.

**Describe the solution you'd like**
I'd like to be able to pass `mount_options`, specifically `max_size` and `free_space_required`, to `as_mount()`, similar to how I could do this directly with `mount()`. This would then delete the oldest data in the cache instead of crashing my pipeline

**Describe alternatives you've considered**
1. Use a bigger compute instance: This is fine up to a point, but if the dataset is too large, it will also fail.
2. Manually delete files from the cache: Assuming I have access to the cache from within the container, this isn't recommended in the docs.
3. Pass the dataset name to the step and mount it/use blobfuse directly: Not a very nice approach as it means I can no longer test my script on local data.
4. Set the `blob_cache_timeout` of the datastore to zero: this might work, though I haven't tried it since I would need to delete my entire dataset and re-upload it. Anyway, it's not a very good option because if I'm using a compute instance that does have enough space it still won't cache anything.

**Comment by swathipil** [comment]
@davystrong - thanks for the feedback! Sending this over to the right people.

**Comment by davystrong** [comment]
Any update on this? It means I still can't train larger datasets.

**Comment by luigiw** [comment]
Closing legacy issue.

Please consider upgrading to AzureML v2 CLI/SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2
