### ISSUE TITLE
OSProvisioningTimedOut with IaaS VM Name because OS Disk name is not unique

### ISSUE THREAD

**Issue by axelgMS** [Azure/azure-sdk-for-python#2023]
CRI 60564263

Getting an OSProvisioningTimedOut (OSPTO) with the following repro steps:
- create a VM named "XYZ" from a Marketplace Image
- delete the VM
- create a new VM with same name "XYZ" from Marketplace image
--> Provisioning failed. OS Provisioning for VM '1ce0l5gdqjuo0t242' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later.. OSProvisioningTimedOut

Reason is that the following UserAgent "_python/3.5.1 (Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-redhat-7.2-Maipo) requests/2.14.2 msrest/0.4.10 msrest_azure/0.4.9 computemanagementclient/1.0.0 Azure-SDK-For-Python_" seems to give the VM's OS Disk name the same value as the VM Name ("XYZ" in our case).
So when you create a new VM from an image, Azure passes the VHD URL of the blob that already exists - and which is already specialized & provisioned.
Hence Azure tries to create a VM with CreateOption = FromImage and it passes a Specialized VHD.
--> OSProvisioningTimedOut.

ExecutionGraph has the following signature:
/etc/hostname contains 'XYZ' and not 'localhost.localdomain'. Also /var/lib/waagent/provisioned is already existing. As a result the Linux image was already specialized.

Ask is to give the OS Disk name a unique name, different than the VM Name...

**Comment by lmazuel** [comment]
Hi @axelgMS 
I feel like this is RestAPI question, since Python is just a messenger here and doesn't anything by default. @johanste who can be tag here?

**Comment by johanste** [comment]
@axelgMS, which market place image are you using?

From the description above, this sounds like the market place image has a problem. @ravbhatnagar, can you help out here?

**Comment by axelgMS** [comment]
I haven't found time to repro yet - but I don't think it's an image issue

At this stage, I don’t know if:
-	Customer didn’t provide any name for the disk, and Python SDK just gave a default **_disk name_**  equal to **_VM name_** (that’s what needs to be improved from Azure SDK for Python)
-	Or if customer explicitly provided a **_disk name_** that is equal to **_VM Name_** – and Python SDK should add a random number to that disk name to make it unique

**Comment by johanste** [comment]
@axelgMS, the Python SDK does not provide a disk name. It is up to the calling application to do so. 

The Python SDK also cannot introduce randomness in naming since that would break idempotency of creates. Which would be very bad since applications would now start leaking resources when run multiple times with the same inputs.

**Comment by lmazuel** [comment]
I agree with @johanste , and the closing the bug. Thanks!
