### ISSUE TITLE
Bad dev.office.com link

### ISSUE THREAD

**Issue by bbkane** [Azure/azure-sdk-for-python#20249]
Hello,

The link to the Office blog post about MS Graph details is broken ( https://dev.office.com/blogs/microsoft-graph-or-azure-ad-graph )

http://dig.ping.pe/dev.office.com:A:1.0.0.1 :

![image](https://user-images.githubusercontent.com/6081085/129283467-cde13e45-299b-472b-923a-c422ad3a0636.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d0260ec-9f5e-08bc-f4e0-a2fbc8547bed
* Version Independent ID: e26538ab-37c5-6284-27ee-7e82a92df35d
* Content: [Graph RBAC libraries for python](https://docs.microsoft.com/en-us/python/api/overview/azure/graph-rbac?view=azure-python)
* Content Source: [docs-ref-services/latest/graph-rbac.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/graph-rbac.md)
* Service: **multiple**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by swathipil** [comment]
@bbkane thank you for your feedback, we'll investigate this ASAP!!

**Comment by lmazuel** [comment]
Hi @bbkane 

We handle SDK for Python on this repo, not blog, and we do not own AAD or MS Graph API :(. I don't deny your issue, but you should contact the MS Graph team about that, there is nothing we can do here. I see you're an FTE, I'm sure you can find the right contact on MSW (I don't know it myself :().
Thanks,

**Comment by bbkane** [comment]
The feedback link I clicked on the docs page opened this issue:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/6081085/134608190-3754e0f4-aa6c-460d-a78b-653bd86aa0d4.png">

Did you have to close this issue after a month and a half of inactivity just because you don't know the answer when you're (presumably, from the feedback link) the team responsible for these docs? I'm technically a Microsoft FTE, but I work at LinkedIn, which has its own ecosystem. 

Monday I'll try to figure out how to use whatever "MSW" is or maybe `git blame` this repo to figure out who to contact for it. I wish you cared more about your customer experience.

**Comment by bbkane** [comment]
cc @v-thepet and @rloutlaw from the git blame: https://github.com/MicrosoftDocs/azure-docs-sdk-python/blame/2e26f4a91550e8c8cba21f77f79d98e7e7add04d/docs-ref-services/latest/graph-rbac.md#L23
