### ISSUE TITLE
The operation api.get in the module azure.mgmt.apimanagement.operations doesn't return all the fields

### ISSUE THREAD

**Issue by sharonelemlightspin** [Azure/azure-sdk-for-python#20288]
- **Package Name**: azure-mgmt-apimanagement
- **Package Version**: 2.1.0
- **Operating System**:linux
- **Python Version**: 3.8.10

**Describe the bug**
Running the api call api.get returns None in several fields even though they are not supposed to be empty (e.g. "subscription_required")

**To Reproduce**
1. Create ApiManagementClient
2. Use the client and run the api operation get

**Expected behavior**
All the fields should return with their actual value
**Screenshots**

![image](https://user-images.githubusercontent.com/74852476/129534831-8a0f4c23-e9bc-4f99-8462-36dbffd2a81c.png)

**Additional context**
The same operation returns all the values using C# .Net
![image](https://user-images.githubusercontent.com/74852476/129534923-c0d7fd18-3367-4623-aa55-a2c23ea25f67.png)
Seems like the attributes in the ApiContract _attribute_map is not the same as in the model. For example, "subscription_required" value in ApiContract attribute map is : 'subscription_required': {'key': 'properties.subscriptionRequired', 'type': 'bool'} but changing it to apiManage.api.models.ApiContract._attribute_map['subscription_required'] ={'key':'properties.ApiContract.subscriptionRequired', 'type': 'str'} returns the value.

**Comment by swathipil** [comment]
@sharonelemlightspin thanks for your feedback - we'll investigate this ASAP!!

**Comment by BigCat20196** [comment]
hi @sharonelemlightspin, thanks for your feedback !

After investigation, the api operation `get` return type in apimagement is `_models.ApiContract`. And `subscription_required` parameter type  in `_models.apicontract` is bool, not str.

![image](https://user-images.githubusercontent.com/51037443/129859857-17eecf45-120c-43a5-a7b2-4f4a3d86e307.png)

**Comment by sharonelemlightspin** [comment]
Hi @BigCat20196 
You are right but the problem is not with the type, it's with the key itself. It supposed to be 'properties.ApiContract.subscriptionRequired' but instead it's 'properties.subscriptionRequired'.

**Comment by BigCat20196** [comment]
Hi @sharonelemlightspin 
No worries. I was just current why does apicontract need to be placed behind properties instead of in front?

At present, its complete format is `ApiContract.properties.subscriptionRequired`.

**Comment by sharonelemlightspin** [comment]
Hi @BigCat20196
I don't know how the format should look like, I just mentioned the way it worked for me.

**Comment by xiangyan99** [comment]
@sharonelemlightspin please check the latest azure-mgmt-apimanagement and let us know if the issue still exists.
