### ISSUE TITLE
Which odata operations are available for Azure Data Tables Python SDK?

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-sdk-for-python#20283]
I'm having trouble finding information on which odata options are available when building queries for the `table_client.query_entities()` method. For instance, [the SDK docs here](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-data-tables/12.0.0b1/azure.data.tables.html) do not contain the word "odata"!

**This works:** 
`query = f"PartitionKey eq '{partition_key}'"`

**This does not:** 
`query1 = f"startswith(PartitionKey, '2021')"`

**Error:** `The requested operation is not implemented on the specified resource.`

Which odata operations are implemented?

**Comment by annatisch** [comment]
Thanks @SeaDude - this is an interesting question....
The Tables service supports a subset of odata queries - the supported operations are documented here:
https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities

As for the Python SDK, we have query formatting documented in the samples README here:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/tables/azure-data-tables/samples#writing-filters

This location was clearly unhelpful, as you didn't find it :) 
So we can make sure this is clearly documented - where was the first place you looked for this information? We could move/replicate it in the home-readme for the SDK, or maybe we could link to it from the API reference docs for `query_entities`? Or both? Somewhere else?

Thanks for your feedback!
