### ISSUE TITLE
AZ_BATCHAI_MPI_MASTER_NODE key error when deploying pytorch lightning job

### ISSUE THREAD

**Issue by wangchu1** [Azure/azure-sdk-for-python#20285]
When following the example in https://github.com/Azure/azureml-examples/tree/main/python-sdk/experimental/using-pytorch-lightning, I ultimately get an error on "AZ_BATCHAI_MPI_MASTER_NODE " key error, meaning the image constructed by the example cannot find the env variable. 

I suppose there are recent code changes of sort which breaks the example? If so, how should I update it now? Thanks a lot!

**Comment by swathipil** [comment]
@fate3439 thanks for your feedback - we'll investigate this ASAP!!

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by xiangyan99** [comment]
We released track 2 machine learning library https://pypi.org/project/azure-ai-ml/. Could you help to check if this works for you?
