### ISSUE TITLE
`azure.data.tables` `query_entities()` JSON example?

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-sdk-for-python#20282]
Hello,

I need to create a JSON object or array from the `table_client.query_entities()` response. All of the examples I've found,  use `print()` ([example](https://github.com/Azure/azure-sdk-for-python/blob/c2524442d71320a9e020cf6f8d7f758be86f3fea/sdk/tables/azure-data-tables/samples/sample_query_table.py#L105)): 

**Instead of something like:**

```
for entity in list(table_client.query_entities(query)):
    print(entity)
```

**How do I get a JSON object from the `<class 'azure.core.paging.ItemPaged'>` response**?

**Comment by SeaDude** [comment]
This gets close-ish, but returns `timedate` data. 

```
test = []
for entity in list(table_client.query_entities(query)):
    test.append(entity)
```

**Example:** 
- `'dl_end_time': TablesEntityDatetime(2021, 8, 10, 0, 23, 19, tzinfo=datetime.timezone.utc)`

**Comment by SeaDude** [comment]
I _think_ this is correct. Found the [Azure Data Table REST API docs](https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities#request-headers) and added the `nometadata` header to a Python SDK request. 

```
test = []
for entity in table_client.query_entities(query, headers ={'Accept' : 'application/json;odata=nometadata'}):
    test.append(entity)

test = json.dumps(test)
```

Can someone validate this is the correct way to return clean JSON?

**Comment by SeaDude** [comment]
Hm. The above doesn't quite work because one of the columns in the data table is JSON itself. 

All of the `"` 's in the column are escaped and not easily parsed. 

```
"eg_msg": "{\"topic\": \"/subscriptions/a8ffee2c-efcc-4242-bf9f-0ca6a28645ef/resourceGroups/ASYNC_DATA_XFER_DEV/providers/Microsoft.Storage/storageAccounts/stgtrigasyncdataxferdev\", \"subject\": \"/blobServices/default/containers/dlk-xfiles/blobs/assets/2021-03-21-07-04-19.png\", \"eventType\": \"Microsoft.Storage.BlobCreated\", \"id\": \"73ab9e8d-f01e-005b-047d-8d48e6061f33\", \"data\": {\"api\": \"PutBlob\", \"clientRequestId\": \"d92b5f62-d3aa-481a-4968-6bc46ac454c7\", \"requestId\": \"73ab9e8d-f01e-005b-047d-8d48e6000000\", \"eTag\": \"0x8D95B94FFD4644D\", \"contentType\": \"image/png\", \"contentLength\": 1342886, \"blobType\": \"BlockBlob\", \"blobUrl\": \"https://stgtrigasyncdataxferdev.blob.core.windows.net/dlk-files/assets/2021-03-21-07-04-19.png\", \"url\": \"https://stgtrigasyncdataxferdev.blob.core.windows.net/dlk-files/assets/2021-03-21-07-04-19.png\", \"sequencer\": \"00000000000000000000000000008b1c000000000012730f\", \"storageDiagnostics\": {\"batchId\": \"9cea7149-2425-4702-ad38-820132e93729\"}}, \"dataVersion\": \"\", \"metadataVersion\": \"1\", \"eventTime\": \"2021-08-10T00:22:55.5042578Z\"}
```
To get the nested JSON clean as well, I have to `dump` and `load` the JSON string:

```
test = []
for entity in table_client.query_entities(query, headers ={'Accept' : 'application/json;odata=nometadata'}):
    test.append(entity)

test = json.dumps(test)

test1 = json.loads(test)

print(test1)
```

Is there an easier way to do this?

**Comment by swathipil** [comment]
@SeaDude thanks for your question and updates! Directing this to the right people!

**Comment by annatisch** [comment]
Hi @SeaDude, thanks for the question!
I think you've generally landed on the best solution - using the `nometadata` header will remove all the deserialization hints from the response, giving us only raw JSON. The way you've implemented it by passing the header directly is the best way to achieve this for now - but we could look at promoting it to an API-level feature.

The second issue you discovered is a little more nuanced. Tables as a service only supports flat unstructured data - i.e. no nested objects. This is why the value of `eg_msg` itself is also needs to be a JSON string.
Let me see if there's a nice generic way to improve the deserialization logic to enable this scenario.
