### ISSUE TITLE
Find Tenant license 

### ISSUE THREAD

**Issue by nisani33** [Azure/azure-sdk-for-python#20284]
Hello 
how can I find a license for Azure AD?
SubscriptionClient gives me a list of tenants and information, but I can't find the license information, 
like I want to know if my Azure use "Azure AD Premium P2 " or "Azure AD Free"

**Comment by swathipil** [comment]
@nisani33 thanks for your question! Routing this to the right people who can help!

**Comment by nisani33** [comment]
Hello 
I still need help
How can I get information about a tenant's license using an API endpoint?
Is the license premium or not, for example?
Thanks

**Comment by lmazuel** [comment]
Hi @nisani33 

This information is stored in the Microsoft Graph API, whch doesn't belong to Azure repo (Azure AD is not an Azure service, but a part of Microsoft Graph).

I would encourage to look at Microsoft Graph API, we're not aware of how Graph API exposes this kind of data:
https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference
https://docs.microsoft.com/en-us/graph/api/resources/subscribedsku?view=graph-rest-1.0
