### ISSUE TITLE
[Schema Registry] Caching Policy Design

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#20305]
https://github.com/Azure/azure-sdk-for-python/issues/13292#issuecomment-884432650
https://github.com/Azure/azure-sdk-for-python/issues/13292#issuecomment-887627150

**Comment by swathipil** [comment]
proposal here: https://gist.github.com/swathipil/58ad55d1002c2e8d552c2997d722ba6f

**Comment by swathipil** [comment]
TODO:
- get Srikanta's design + sync up with other languages

**Comment by swathipil** [comment]
closing for now, since there will be a general caching policy Arch Board Review for core, rather than in individual SDKs
