### ISSUE TITLE
[Schema Registry] Settle down on models/method return Type

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#20307]
languages consensus on:

# Methods
- get_schema
  - return: data, class type
    - Schema -> (content, SchemaProperties), SchemaProperties -> (id, version, …)
- get_schema_id
  - return just id or all of the properties or new model class

------------

# Models
- Response type (naming)
  - get_schema_id, return a string / SchemaId (class) / SchemaRepsonse / SchemaProperties
  - get_schema, return a Schema
  - any convention in the Python SDKs?
- SchemaProperties
  - currently we have location_by_id, the swagger spec is Schema-Id-Location, should we align
  - The swagger has Schema-Versions-Location, should we have this?
  -JS has the schema properties: group, name, serialization_type, and content. This info seems like a better mapping in a cache to id? --> **don't think this is true. as we discussed, JS `SchemaDescription` does not map to our `SchemaProperties`, their `SchemaId` does.**

**Comment by swathipil** [comment]
- what is new model class in `methods: get_schema_id`?

**Comment by swathipil** [comment]
all comments for changes here: https://teams.microsoft.com/l/message/19:f88a08aeeafd44a18ba3a9f77c1b0d2b@thread.skype/1630009958431?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1630009958431&teamName=Azure%20SDK&channelName=Service%20-%20Schema%20Registry&createdTime=1630009958431

and here: https://teams.microsoft.com/l/message/19:f88a08aeeafd44a18ba3a9f77c1b0d2b@thread.skype/1630357842677?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1630357842677&teamName=Azure%20SDK&channelName=Service%20-%20Schema%20Registry&createdTime=1630357842677

**Comment by swathipil** [comment]
TODO:
- settle on name of `Schema` (either `SchemaRegistrySchema` or something else)
