### ISSUE TITLE
When querying metrics using Azure Monitor Query, it doesn't support interval of less than 1 minute

### ISSUE THREAD

**Issue by esttenorio** [Azure/azure-sdk-for-python#20327]
We are using the [Azure Monitor Query client library](https://docs.microsoft.com/en-us/python/api/overview/azure/monitor-query-readme?view=azure-python-preview) to fetch both Logs and Metrics to create a custom monitoring Dashboard. 

For logs, we have no issues since the interval can be defined with `by bin(TimeGenerated, 10s)` in the Kusto query. But for metrics, our team has developed some custom Telegraf plugins that are sending metrics to specific resources. When using the Monitor Query lib, the lowest interval that can be defined is 1m even when the plugin can emit data up to every 10s. We can confirm this by using the Chronograf InfluxDB local ui:

![image](https://user-images.githubusercontent.com/8483207/129812834-3f9cd148-6db3-4824-9255-f0313a759fac.png)

![image](https://user-images.githubusercontent.com/8483207/129821774-1393c1f7-9cd8-4d0b-ade2-853e3aeded11.png)

Since Azure Monitoring does not provide a way to visualize Azure Metrics, using this lib is the only way we've found to do extract metrics and show them next to some other data from Azure Monitor Logs. We are using the lib to get live monitoring of remote machines and we do require smaller intervals to detect "jitter", abnormal fluctuations, and spikes. With the 1m interval, all the spikes and fluctuations are averaged over a minute and are not shown on the output data.

For our application, 5s or 10s would be ideal. Is it possible to remove the 1m limitation and support smaller intervals?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e37b06b-ccb6-cce7-ee1d-31aa5585c143
* Version Independent ID: 14650046-8b8a-8f9c-b5be-8ae6bd27044b
* Content: [Azure Monitor Query client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/monitor-query-readme?view=azure-python-preview)
* Content Source: [docs-ref-services/preview/monitor-query-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/preview/monitor-query-readme.md)
* Service: **monitor**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by rakshith91** [comment]
Hi @esttenorio , an interval of less than 1 minute is not supported by the service team currently, but i have relayed this request to them. Will update you as soon as i have more details.
