### ISSUE TITLE
When querying metrics using Azure Monitor Query, specifics filters have to be used instead of getting data from all dimensions

### ISSUE THREAD

**Issue by esttenorio** [Azure/azure-sdk-for-python#20329]
Whenever querying metrics with [Azure Monitor Query](https://docs.microsoft.com/en-us/python/api/overview/azure/monitor-query-readme?view=azure-python-preview), the metric query must contain filters with specific dimensions to get accurate information.

When using the Portal there is no need of doing filtering 1 by 1, since the user can either apply a filter or use the split feature or both to see the multiple results from different dimensions.

![image](https://user-images.githubusercontent.com/8483207/129818072-0a1ed573-1cd6-4889-8fdf-1e83a11631ea.png)

Supporting `splitting by <dimension_name>` would make things easier since for example, in my team's current project the dimension is called process_id and there are more than 25 different process ids that I should know the name beforehand to query them 1 by 1 with multiple filters.

Adding the split feature would make things easier:
- the user wouldn't need to know the dimension names beforehand
- one query would replace one query per dimension name

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by rakshith91** [comment]
Hi @esttenorio  The split feature can be achieved in the filter by setting the value to * - for example, like "City eq '*'"

Let me know if you have any questions I'm keeping this issue open to update documentation/ sample.
