### ISSUE TITLE
Incomplete Example

### ISSUE THREAD

**Issue by moselhy** [Azure/azure-sdk-for-python#20336]
In the last example, the resource group isn't actually deleted, only the 3 container instance groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e732e187-7ff4-bd4f-9aad-44953af44a86
* Version Independent ID: d4baa2d6-8f2f-ed76-e890-3240065f485a
* Content: [Azure Container Instances libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/containerinstance?view=azure-python)
* Content Source: [docs-ref-services/latest/containerinstance.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/containerinstance.md)
* Service: **container-instances**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by moselhy** [comment]
https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1422

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by scbedd** [comment]
Hey @moselhy !

I did a little bit of digging here and figured out the issue. The sample accidentally excludes the necessary line that also cleans up the resource group. I have filed a [PR](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1428) that will resolve this issue. Once it merges to main, I will close this issue as resolved.

Thanks for your contribution!
