### ISSUE TITLE
Can't upgrade python azure version from 4.0.0 from 5.0.0

### ISSUE THREAD

**Issue by psp316r** [Azure/azure-sdk-for-python#20338]
**When I try the Following Commnad:**
` pip install azure==5.0.0`

**I got the Following Error:**

`Collecting azure==5.0.0
  Using cached azure-5.0.0.zip (4.6 kB)
    ERROR: Command errored out with exit status 1:
     command: '/home/psp316r/PSP316R/5. Programs/Python/DatalakeGen2/venv3/bin/python' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sjq05kcp/azure_836ccba229cb4ff08cb2c6af22b4f3ad/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sjq05kcp/azure_836ccba229cb4ff08cb2c6af22b4f3ad/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_jr60gdu
         cwd: /tmp/pip-install-sjq05kcp/azure_836ccba229cb4ff08cb2c6af22b4f3ad/
    Complete output (24 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sjq05kcp/azure_836ccba229cb4ff08cb2c6af22b4f3ad/setup.py", line 60, in <module>
        raise RuntimeError(message)
    RuntimeError:
    
    Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.
    
    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all
    
    Here's a non-exhaustive list of common packages:
    
    -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
    -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
    -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
    -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
    -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts
    
    A more comprehensive discussion of the rationale for this decision can be found in the following issue:
    https://github.com/Azure/azure-sdk-for-python/issues/10646
    
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e8/48/ef73d5e71ecb84cacaeaf533f519be81825ad6198acc41bd821f440e7f7c/azure-5.0.0.zip#sha256=f56d22acaba0ce74b821fd3d012d18854f9d0b3662d5a3a9240b1bd587c96b23 (from https://pypi.org/simple/azure/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement azure==5.0.0 (from versions: 0.8.0pr1, 0.1, 0.2, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.10.0, 0.10.2, 0.11.0, 0.11.1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 2.0.0a1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc3, 2.0.0rc4, 2.0.0rc5, 2.0.0rc6, 2.0.0, 3.0.0, 4.0.0, 5.0.0)
ERROR: No matching distribution found for azure==5.0.0`

**Comment by lmazuel** [comment]
Hi @psp316r 

As stated in the error message, we stopped maintaining the `azure` package, and we made the v5.0.0 failing at install time on purpose, to be sure there is no ambiguity that the package is not providing any value to customers.
You can stick to v4.0.0, or as explain in the error message install packages you need individually.
Thans,
