### ISSUE TITLE
Azure python api calls gets stuck sometimes for a long time

### ISSUE THREAD

**Issue by pyprateek** [Azure/azure-sdk-for-python#20372]
I observed that sometimes the azure python api calls gets stuck for a long time (about 30-40 mins) and sometimes it is completed in 1-2 mins.
I noticed this mostly for detach disk and attach disk operations.

Attaching the code snipped used:
```
async_update = self.compute_client.virtual_machines.begin_create_or_update(vm_group_name, vm.name, vm)
async_update.wait()
```
For detach disk operation, I check the VM status in the Azure portal and the disk was in detaching state for a long time.

Can someone see what the issue might be?

We are observing these issues after upgrading the python SDK.
azure-mgmt-compute==12.0.0 (old version)
azure-mgmt-compute==21.0.0 (new version)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by amjads1** [comment]
@jaylabell Could you please look into the issue?

**Comment by pyprateek** [comment]
Any update on this

**Comment by jaylabell** [comment]
Taking a look into this issue
