### ISSUE TITLE
ApplicationInsights does not work out of the box when using ClientSecretCredentials

### ISSUE THREAD

**Issue by esttenorio** [Azure/azure-sdk-for-python#20378]
- **Package Name**: azure-applicationinsights
- **Package Version**: 0.1.0
- **Operating System**: Linux
- **Python Version**: 3.8.7

**Describe the bug**
The applicationInsights client requires:
- the identity credential must have a signed_session (that is missing from the azure.identity.ClientSecretCredential) so a [wrapper](https://gist.github.com/lmazuel/cc683d82ea1d7b40208de7c9fc8de59d) has to be used to make it work.
- AppId and AppKey are needed to fetch queries succesfully: To pass the app key, the header needs to be modified in the applicationInsightDataClient
``` python
credential = ClientSecretCredential(
    client_id=os.environ.get(env.ENV_APP_CLIENT_ID),
    client_secret=os.environ.get(env.ENV_APP_SECRET),
    tenant_id=os.environ.get(env.ENV_APP_TENANT),
)
cred_adapter = CredentialWrapper(credential)

client = ApplicationInsightsDataClient(cred_adapter)
client.config.headers.setdefault("x-api-key", os.environ.get(env.ENV_APPLICATION_INSIGHTS_KEY))
```

There should be a special Credential class for using ApplicationInsights without using wrappers and adding custom headers or ApplicationInsights should support authentication with ClientSecretCredentials only without requiring the Application Insights AppKey.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by lmazuel** [comment]
As the package is no longer maintained, we do not plan to add `azure-identity` support.

Please use https://pypi.org/project/azure-monitor-query/ for query, and our telemetry SDK for logging activity like https://pypi.org/project/azure-core-tracing-opentelemetry/ to replace it.
