### ISSUE TITLE
Generic credentials for outlook 365 and route attachments from outlook 365 emails to a azure storage account

### ISSUE THREAD

**Issue by saikothakapu** [Azure/azure-sdk-for-python#20388]
Currently , In one of our project we created a dashboard which is scripted in python and all the code is running in a local machine. In this dashboard, it consumes data from excel files which are shared as attachments in an outlook personal email.
For connecting to outlook emails and fetch attached excel files, we are using personal credentials which we wanted to avoid.
Can someone please help us if there is a way to create a generic outlook account with generic credentials and later route all the attachments to a azure storage blob for storing through python scripting. Appreciate your responses.

**Comment by YalinLi0312** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by mccoyp** [comment]
Hi @saikothakapu, thank you for opening an issue! The Storage team has been looped in to help you with anything on the SDK front, but it sounds like your question is mostly about creating a certain kind of Outlook account. To determine how we can best help, it would be great to know if you're having any Azure SDK-specific issues, or if this is Outlook-specific. It may be a good idea to contact support for Outlook or ask a [forum question](https://answers.microsoft.com/) if you haven't already.

**Comment by saikothakapu** [comment]
thanks @mccoyp , I have posted the question in outlook forum.
