### ISSUE TITLE
LogsQueryClient should be able to handle platform logs

### ISSUE THREAD

**Issue by MartinKosicky** [Azure/azure-sdk-for-python#20417]
Hello, I am trying to use the LogsQueryClient from azure.monitor.query. The API however always requests that I use workspace_id. I have an elastic pool with 100 databases, and I want to query their "Logs" so I would rather need the https://api.loganalytics.io/v1/subscriptions/... instead of https://api.loganalytics.io/v1/workspaces/...  . Are there any plans for that? or is there already a mitigation for this?

**Comment by rakshith91** [comment]
Hi @MartinKosicky , we are in the plan of supporting querying through an Azure resource ID along with workspace id as well, although I cannot promise a timeline yet.
Currently, you can use the `additional_workspaces` param to pass a list of resource id, workspace name or a workspace id. Would that work for you?

**Comment by MartinKosicky** [comment]
yes that is fine

**Comment by rakshith91** [comment]
Reopening this issue since it's not addressed :)
