### ISSUE TITLE
Can't instantiate BlobServiceClient using AzureStack storage account

### ISSUE THREAD

**Issue by Dany9966** [Azure/azure-sdk-for-python#20413]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.8.1
- **Operating System**: Ubuntu Bionic (18.04-LTS)
- **Python Version**: 3.6.9

**Describe the bug**
Trying to instantiate a `BlobServiceClient` with a storage account created on local AzureStack throws the following error:
`ValueError: Unable to determine account name for shared key credential.` 

The account endpoint looks like this: `https://<account_name>.blob.local.azurestack.external/`, and the main issue is caused by this line: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py#L82 (as you can notice, I have no `core` in the endpoint URL)

**To Reproduce**
1. Create a storage account on AzureStack
2. Try instantiating a `BlobServiceClient` using the account URL

**Expected behavior**
A working service client.

**Additional context**
The AzureStack env is the newest version of the Azure Stack Development Kit. If you need any other info, please ask in the comments.

**Comment by xiafu-msft** [comment]
Hi @Dany9966

Thanks for reaching out. You can pass the credential in this format, then it would work.

credential={'account_name': youraccountname, 'account_key': youraccountkey}

**Comment by Dany9966** [comment]
Hello @xiafu-msft 

My bad, I can instantiate the `BlobServiceClient`, but I CAN'T use it for other operations. This is my sample code: 
`from azure.storage import blob

res_group = 'test-resource-group'
storage_accounts = [
    s for s in storage_cli.storage_accounts.list_by_resource_group(res_group)]
stor_acc = storage_accounts[0] if storage_accounts else None
if stor_acc:
    account_keys = storage_cli.storage_accounts.list_keys(
        res_group, stor_acc.name)
    key = account_keys.keys[0].value
    # credential = key <-- this is how I used to pass credential
    credential = {
        'account_name': stor_acc.name,
        'account_key': key
    }
    blobd = blob.BlobServiceClient(
        account_url=stor_acc.primary_endpoints.blob,
        credential=credential,
    )
    containers = [c for c in blobd.list_containers()]
    print(containers)`

It's just simple script that lists containers. The listing fails on my AzureStack with the following error/trace:
`Traceback (most recent call last):
  File "azure-blob.py", line 29, in <module>
    containers = [c for c in blobd.list_containers()]
  File "azure-blob.py", line 29, in <listcomp>
    containers = [c for c in blobd.list_containers()]
  File "/usr/local/lib/python3.6/dist-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.6/dist-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/root/azure-sdk-for-python/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py", line 421, in _get_next_cb
    process_storage_error(error)
  File "/root/azure-sdk-for-python/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py", line 177, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: The value for one of the HTTP headers is not in the correct format.
RequestId:3eda82e5-9562-0b5c-612a-7f66a6943719
Time:2021-09-06T11:50:49.0681260Z
ErrorCode:InvalidHeaderValue
headername:x-ms-version
headervalue:2020-10-02`
