### ISSUE TITLE
Converting tier for all blobs in container to Archive

### ISSUE THREAD

**Issue by JochemBoersma** [Azure/azure-sdk-for-python#20430]
Converting tier for all blobs in a container works when swapping from 'Hot' to 'Cool' and vice versa. However: Change tier towards 'Archive' gives following error:
```
> from azure.storage.blob import ContainerClient, BlobClient, StandardBlobTier
> container = ContainerClient.from_connection_string(conn_str=CONN_STR,
                                                   container_name=CONTAINER_NAME)
> container.set_standard_blob_tier_blobs(StandardBlobTier.Archive, *container.list_blobs())

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\storage\blob\_container_client.py", line 1461, in set_standard_blob_tier_blobs
    return self._batch_send(*reqs, **options)
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 322, in _batch_send
    process_storage_error(error)
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 89, in process_storage_error
    raise storage_error
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 318, in _batch_send
    raise error
azure.storage.blob._shared.response_handlers.PartialBatchErrorException: There is a partial failure in the batch operation.
```
Converting these blob-by-blob, using the BlobClient works, so I could work around, but couldn't point the above error.

Regards, Jochem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37584723-65eb-0794-8ec5-fcae40b28717
* Version Independent ID: 21d8c29d-77a6-6743-25b2-1cbf855e37a3
* Content: [azure.storage.blob.ContainerClient class](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#set-standard-blob-tier-blobs-standard-blob-tier---blobs----kwargs-)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.ContainerClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-storage-blob/azure.storage.blob.ContainerClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by amishra-dev** [comment]
@JochemBoersma 
Hi Jochem,
The error means that some of the batch operations failed. Can you look at the response from set_standard_blob_tier_blobs to see which ones failed. The detailed response will have the details. If you still need help after that please feel free to paste the errors here and we can help.

Thanks
/cc @xiafu-msft (if we have a sample to share that shows how to print the output of batch, please share a link here)

**Comment by xiafu-msft** [comment]
Hi @JochemBoersma 

Thanks for reaching out. Please take a look at this sample which is to get subrequests status https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/tests/test_container.py#L1399-L1434 
you can check the content of parts[0] or parts[1] and see why the request failed.

Let me know if it doesn't help!

**Comment by JochemBoersma** [comment]
Hi,

Thanks for support. Actual, I wrote a workaround (just pass all elements, check the tier, and switch if needed), so no urgency anymore. 

However: Working with the `.set_standard_blob_tier_blobs()`, still returns an error. The response:
```
parts = container.set_standard_blob_tier_blobs(StandardBlobTier.Archive, *container.list_blobs())
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\storage\blob\_container_client.py", line 1461, in set_standard_blob_tier_blobs
    return self._batch_send(*reqs, **options)
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 322, in _batch_send
    process_storage_error(error)
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 89, in process_storage_error
    raise storage_error
  File "C:\Anaconda3\envs\clean\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 318, in _batch_send
    raise error
azure.storage.blob._shared.response_handlers.PartialBatchErrorException: There is a partial failure in the batch operation.
```
and
```
parts
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'parts' is not defined
```


My workaround is:
```
# Pass all the blobs in the container, and convert its tier to newTier
for blob in container.list_blobs():
    # Get the client
    blob_client = container.get_blob_client(blob)

    if not blob_client.exists():
        # I don't now why it's here....
        # Aha, they do not exist when currently in transfer mode....
        continue

    # Check some properties (e.g. folder, status and tier)
    blob_props = blob_client.get_blob_properties()
    # Check if it is a folder (no simple props in blob-client, so depend on name)
    if 'hdi_isfolder' in blob_props['metadata'] and blob_props['metadata']['hdi_isfolder']:
        # Blob is an folder, so continue
        print(f'Skip blob [{blob_client.blob_name}], it is a folder')
        continue  # to next blob

    if blob_props['blob_tier'] == newTier:
        # Blob already in correct tier, simply skip
        print(f'Skip blob [{blob_client.blob_name}], since already correct tier.')
        continue  # to next blob

    if not blob_props['archive_status'] is None \
            and blob_props['archive_status'].startswith('rehydrate-pending-'):
        # Changing tier in progress, can't intervene at this moment.
        print(f'Skip blob [{blob_client.blob_name}], rehydration in progress.')
        continue  # to next blob

    # Convert tier
    print(f'Converting tier for [{blob_client.blob_name}]')
    try:
        blob_client.set_standard_blob_tier(newTier)
    except:
        print(f'    |- Failed!')
```

**Comment by amishra-dev** [comment]
@xiafu-msft i am tagging this as a bug, can you please look

**Comment by xiafu-msft** [comment]
Hi @JochemBoersma 

Thanks for your workaround. You need to pass in raise_on_any_failure=False so that the response parser will continue parse the subresponse for you no matter the subrequest failed or not.

Sorry for the delay of response.
