### ISSUE TITLE
azure-storage-file-datalake not able to work with Append Blobs

### ISSUE THREAD

**Issue by marincon-sarmiento** [Azure/azure-sdk-for-python#20434]
**Is your feature request related to a problem? Please describe.**
I am trying to work with Append Blobs on Data Lake Gen 2 because my case requires me to write incoming telemetry into files stored on Data Lake storage account. Although, I am able to create Append Blobs manually from the portal, and this post (https://azure.microsoft.com/en-us/updates/append-blob-support-in-azure-data-lake-storage-is-now-generally-available/) says that they have recently become generally available, I cannot find a method in the DataLakeFileClient class from the python azure-storage-file-datalake SDK to be able to create or append blocks to Append Blobs. By default, the create_file() method from the DataLakeFileClient class only creates Block Blobs, and there doesn't seem to be a parameter to make it create Append Blobs.  

**Describe the solution you'd like**
It would be good to have a property in the create_file method of the DataLakeFileClient class to specify the type of blob that will be created. 

**Describe alternatives you've considered**
I have tried using the python azure-storage-blob SDK, however, it does not seem to be able to locate specific folder paths from containers in my Data Lake Gen2, since its only expecting the container's name.

**Additional context**

**Comment by jalauzon-msft** [comment]
Hi @marincon-sarmiento, sorry for the long delay in response and thanks for question.

Unfortuantely, the datalake SDK does not support Append Blobs. Datalake files are backed by Block Blobs as Block Blobs can support the append + flush operations that datalake files need and therefore there is not usually a need for an Append Blob. So, you have a couple of options for your scenario.

1. Use the datalake SDK and files without worrying about the backing blob type. You should be able to use `append_data` and `flush_data` to append data to your file. We also have a feature coming within the next couple of releases that will allow you to append and flush in a single operation.

2. Your other option is to use the blobs SDK to support append blobs. The Blobs SDK will support some operations on an ADLS Gen2 account and you should be able to still create an Append Blob and use `append_block` on your Datalake account. This can tricky if you need to integrate your file into an existing datalake filesystem though and is not recommended in most cases.

**Comment by vincenttran-msft** [comment]
Hi @marincon-sarmiento, I just wanted to touch base with you and see if this issue is persisting? If not we shall continue with the closure of this issue shortly.

Thanks!
