### ISSUE TITLE
Docs should show preview packages under "Latest" in addition to "Preview" if there is no GA version

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#20436]
Customers visiting a docs page for the first time may not know to go to the "Preview" moniker to see docs for a preview package. This can be especially confusing in situations where the package in question only has preview versions and no GA versions. If the user doesn't immediately see the package they are searching for under the "Latest" moniker they may incorrectly conclude that package documentation does not exist.

To address this it is proposed by @elraikhm that in cases where there is no GA version (i.e. only preview versions of a package) we onboard the preview package in both "Latest" and "Preview" monikers. When there is a GA version then the GA version will always be onboarded to the "Latest" moniker and "Preview" will be onboarded using the existing logic.

**Comment by lfraleigh** [comment]
Talked with Scott Addie - we do not plan to pursue this.
