### ISSUE TITLE
Add AES-GCM cipher to azure-blob-storage

### ISSUE THREAD

**Issue by skylaro** [Azure/azure-sdk-for-python#20438]
**Is your feature request related to a problem? Please describe.**
AES-CBC-256 encryption is appearing as a security vulnerability and AES-GCM-256 is required in its place.

**Describe the solution you'd like**
Add AES-GCM-256 algorithm to https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/encryption.py#L51.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by xiafu-msft** [comment]
Hi @skylaro 

Thanks for reporting this problem! We will investigate and fix it!

**Comment by jalauzon-msft** [comment]
Hi @skylaro Skylar, apologies for the long delay with no communication on this.

We have just added support for AES-GCM-256 in the latest preview release [12.13.0b1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/CHANGELOG.md#features-added-1) and this will part of the next GA release as well. You can use the new algorithm by specifying `encryption_version='2.0'` on client constructors. See [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/CHANGELOG.md#features-added-1).

I do want to note though that we recommend against using client-side encryption in favor of using one of the different forms of server-side encryption Azure Storage offers (e.g., Customer-Provided Key or Encryption Scopes).
