### ISSUE TITLE
Azure Core 3.10-rc1 Test Failures

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#20433]
[Test Failures](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1066475&view=ms.vss-test-web.build-test-results-tab)

Steps for repro:

```
<activate virtual env for 3.10rc1>
pip install setuptools==56.0.0 wheel==0.37.0 tox==3.24.3 tox-monorepo==0.1.2 packaging==21.0
cd sdk/core/azure-core
tox -e whl -c ../../../eng/tox/tox.ini
```

@xiangyan99  I am working on getting `azure-identity`, `azure-storage` and `azure-keyvault` working in the same build. It is super duper finicky given the incomplete map of packages that have released for 3.10.

**Comment by xiangyan99** [comment]
I think this is fixed?

**Comment by xiangyan99** [comment]
Closing as fixed. Please feel free to reopen it if I am wrong.
