### ISSUE TITLE
Azure Python SDK QueueClient Error

### ISSUE THREAD

**Issue by mycloudops** [Azure/azure-sdk-for-python#20455]
I installed azure.queue.storage 1.4.0 but while I'm trying to import QueueClient I'm getting the below error:

from azure.storage.queue import QueueClient
ImportError: cannot import name 'QueueClient'

**Comment by xiangyan99** [comment]
Thanks for your feedback.

azure-storage-queue 1.4.0 is deprecated.

Do you have a chance to try latest version https://pypi.org/project/azure-storage-queue/12.1.6/?

Thanks.
