### ISSUE TITLE
Enable MSAL Logging in Identity SDK.

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-python#20473]
Enable MSAL Logging for Python Identity SDK. 
MSAL Python logging configuration can be found [here]https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-python

**Comment by chlowell** [comment]
Closing this because applications configure all logging through the standard library's `logging` module. MSAL Python itself has no logging configuration.
