### ISSUE TITLE
'snapshot' kwarg silently ignored due to typo in azure.storage.fileshare.ShareDirectoryClient's get_file_client

### ISSUE THREAD

**Issue by ewheeler** [Azure/azure-sdk-for-python#20478]
- **Package Name**: azure-storage-file-share
- **Package Version**: 12.5.0
- **Operating System**: macos
- **Python Version**: 3.9

**Describe the bug**
'snapshot' kwarg ignored due to typo in azure.storage.fileshare.ShareDirectoryClient's `get_file_client`

**To Reproduce**
1. provide 'snapshot' parameter when calling azure.storage.fileshare.ShareDirectoryClient's `get_file_client`

**Expected behavior**
Expect parameter to be honored or an exception to be raised

**Additional context**
should be `snapshot=self.snapshot` instead of `napshot=self.snapshot`:
https://github.com/Azure/azure-sdk-for-python/blob/8496bd82bacf01be8ecb4b4674514aeef6a3f774/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py#L234

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by amishra-dev** [comment]
@xiafu-msft/ @annatisch  isn't this just standard pythonic behavior we have adopted?

**Comment by xiafu-msft** [comment]
Hi @ewheeler 

Thanks for reporting this and point out the fix! We have created a pr and will merge it soon.

**Comment by xiangyan99** [comment]
@tasherif-msft is this fixed?

**Comment by jalauzon-msft** [comment]
It looks like this was addressed by #20559 and is part of our latest two beta releases. This fix will part of our GA release, 12.7.0, which is targeted for early March.
