### ISSUE TITLE
Improve Azure Identity SDK Error Messages and logging details 

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-python#20484]
Add verbose/debug level logs to Azure Identity that help to explain the code flow to day zero users and provide guidance on issues that the users may encounter.
Add aka.ms Links to the troubleshooting guide in the Error Messages.

PR to port: Azure/azure-sdk-for-java#23502

**Comment by mccoyp** [comment]
Covered by https://github.com/Azure/azure-sdk-for-python/pull/20684.
