### ISSUE TITLE
When will limitations be fixed?

### ISSUE THREAD

**Issue by docgregt** [Azure/azure-sdk-for-python#20497]
It's been over a year since last release. When will the limitations be fixed. In particular not being able to use 'group by' greatly hampers queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6289377-8b4b-733b-8b32-78bdb289e3bb
* Version Independent ID: fb3d012e-c4cd-06c8-673c-c3d51c879c76
* Content: [Azure Cosmos DB SQL API client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/cosmos-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/cosmos-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/cosmos-readme.md)
* Service: **cosmos**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Rodrigossz** [comment]
Hello @docgregt

Currently we do not have a date for any new feature, which means that the limitations will continue for longer. We would like to provide dates for each limitation but it's not possible now. Can you ping me again by the end of the year? Tks

**Comment by docgregt** [comment]
Ok.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by metamoof** [comment]
> Hello @docgregt
> 
> Currently we do not have a date for any new feature, which means that the limitations will continue for longer. We would like to provide dates for each limitation but it's not possible now. Can you ping me again by the end of the year? Tks

It's well over a year and a half since the last update of this message. I'm wondering if there's been any progress on a date for GROUP BY?

**Comment by James-Beckwith** [comment]
Agreed - Not having the ability to use GROUP BY and aggregations in python SDK queries is a huge limitation. Is there any update on when this will be available?

**Comment by Rodrigossz** [comment]
@simorenoh can add details...

**Comment by simorenoh** [comment]
@James-Beckwith @metamoof @docgregt 
Thank you all for showing interest in this feature, a lot had been going on this last year with the team. While we can't provide an estimate for a date yet, we have been knocking out several other limitations, bugs, and improvements - and I assure you this item is in the backlog.

If I get any concrete updates, I'll be sure to keep updating this thread. Thank you all for your patience!
@JericHunter @gahl-levy

**Comment by docgregt** [comment]
"we have been knocking out several other limitations, bugs, and improvements"...please provide link to all of these and please not the blog posts as those dont cover much.

**Comment by simorenoh** [comment]
@docgregt Sure, I'll attach some of them here. Our Changelog file should also outline all the things we've been up to - anything after release 4.3.0b1 is new changes: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/CHANGELOG.md

**General Limitations**
New Cosmos Asynchronous client: https://github.com/Azure/azure-sdk-for-python/pull/21404
Split-proof sync client: https://github.com/Azure/azure-sdk-for-python/pull/22237
Split-proof async client: https://github.com/Azure/azure-sdk-for-python/pull/22261

**Control Plane Limitations**
Add ability to use cosmos integrated cache: https://github.com/Azure/azure-sdk-for-python/pull/22946

**Security Improvements/ Limitations**
AAD Authentication for the sync client: https://github.com/Azure/azure-sdk-for-python/pull/23604
AAD Authentication for the async client: https://github.com/Azure/azure-sdk-for-python/pull/23717

**Bug-fixes**
Use account's default consistency as opposed to Session for default: https://github.com/Azure/azure-sdk-for-python/pull/22792

There's a bunch of other PRs and work that has been done, so if the CHANGELOG feels like not enough I encourage you to filter by closed pr's with the tag `cosmos`, and you should be able to see what we've been up to.
