### ISSUE TITLE
BillingManagementClient got an unexpected keyword argument 'credential'

### ISSUE THREAD

**Issue by joel-vasiliev** [Azure/azure-sdk-for-python#20503]
Code:
`BillingManagementClient(credential=DefaultAzureCredential(),subscription_id=SUBSCRIPTION_ID)`
Output:
TypeError: __init__() got an unexpected keyword argument 'credential'
---

#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b5facdec-6b71-b777-a555-10ceac2cee68
* Version Independent ID: f58c4f1e-83f5-c7ca-2460-bd6a40c54fee
* Content: [azure.mgmt.billing.BillingManagementClient class](https://docs.microsoft.com/pt-br/python/api/azure-mgmt-billing/azure.mgmt.billing.billingmanagementclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-billing/azure.mgmt.billing.BillingManagementClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-billing/azure.mgmt.billing.BillingManagementClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by BigCat20196** [comment]
@joel-vasiliev Thanks for the feedback. Could you tell me which version of `azure-mgmt-billing` you are using?

It is recommended to upgrade to the latest version and try again.
