### ISSUE TITLE
[Search] Changes to SearchClient.search

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-python#20524]
![image](https://user-images.githubusercontent.com/8271806/131925115-c22e4d9b-3a35-42af-a26a-5c3029b14523.png)

**Comment by tjprescott** [comment]
Summary of changes needed for Python:
- [ ] Change `speller` to `query_speller`
- [ ] Construct `answers` property from two custom properties `query_answer` and `query_answer_count`
- [ ] Construct `captions` property from two custom properties `query_caption` and `query_caption_highlight`.
