### ISSUE TITLE
Authentication is deprecated, AttributeError: 'ContainerGroupsOperations' object has no attribute 'create_or_update'

### ISSUE THREAD

**Issue by db533** [Azure/azure-sdk-for-python#20549]
Running the script as is, it fails noting that the authentication method is deprecated.
Once I fixed the authentication with azure.identity package, I get an error message:

Traceback (most recent call last):
  File "/home/zd533/gitRepos/GunaBot2/azure-mgmt/azure_containers.py", line 330, in <module>
    main()
  File "/home/zd533/gitRepos/GunaBot2/azure-mgmt/azure_containers.py", line 68, in main
    create_container_group(aciclient, resource_group, container_group_name,
  File "/home/zd533/gitRepos/GunaBot2/azure-mgmt/azure_containers.py", line 130, in create_container_group
    aci_client.container_groups.create_or_update(resource_group.name,
AttributeError: 'ContainerGroupsOperations' object has no attribute 'create_or_update'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e732e187-7ff4-bd4f-9aad-44953af44a86
* Version Independent ID: d4baa2d6-8f2f-ed76-e890-3240065f485a
* Content: [Azure Container Instances libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/containerinstance?view=azure-python)
* Content Source: [docs-ref-services/latest/containerinstance.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/containerinstance.md)
* Service: **container-instances**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by yunhaoling** [comment]
thanks @db533 for reaching out. We'll investigate ASAP.

**Comment by BigCat20196** [comment]
Hi @db533,  I guess you have upgraded `azure-mgmt-containerinstance` to  the latest version. Please use `begin_create_or_update`  instead of the original method.

FYR: https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/containerinstance/manage_container_group.py
