### ISSUE TITLE
[EventHubs] Fix CI API View failure (unapproved by design)

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#20567]
currently due to the issue in the APIView tool: https://github.com/Azure/azure-sdk-tools/issues/1880, the API view of EventHubs is not generated correctly.

We have decided not to approve the wrong API view, letting the CI fail everyday as a reminder to fix the issue.

However, this might not be a good approach as we tend to ignore other CI errors (e.g. https://github.com/Azure/azure-sdk-for-python/issues/20565).

we should keep this in mind, do our daily check and fix the API view ASAP.

**Comment by swathipil** [comment]
error: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1097421&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=d31d5e2d-d8df-53bc-da94-87e19f5b2ee4&l=25

**Comment by swathipil** [comment]
get approval on this api view: https://apiview.dev/Assemblies/Review/3e49ce1ca870470289360023dcb51edf?diffRevisionId=4379fb2d3d214ceb99a7a62bfda6befe&doc=False&diffOnly=False
