### ISSUE TITLE
Missing class method "from_container_url", what now?

### ISSUE THREAD

**Issue by voiprodrigo** [Azure/azure-sdk-for-python#20580]
Hi,

I'd like to use the same storage account for multiple containers, with different applications using each container (for eventhub checkpointing)

So I'd like to use a container SAS url/token for direct container access, thus avoiding giving access to the entire storage account to all containers.

Class "BlobCheckpointStore" states:

`    :param str account_url:
        The URI to the storage account. In order to create a client given the full URI to the container,
        use the :func:`from_container_url` classmethod.`

However, there's no such method `from_container_url`

Is there a way to achieve this?

Thanks!

**Comment by yunhaoling** [comment]
thanks for reaching out, we'll investigate ASAP.

**Comment by yunhaoling** [comment]
hey @voiprodrigo , apologize that it is not documented correct.

To make use of a `account_url`, you could use the constructor of `BlobCheckpointStore` directly:

```python
  checkpoint_store = BlobCheckpointStore(
      account_url=<your_account_url>,
      container_name=<your_container_name>,
      ...
  )

client = EventHubConsumerClient.from_connection_string(
        CONNECTION_STR,
        consumer_group='$Default',
        eventhub_name=EVENTHUB_NAME,
        checkpoint_store=checkpoint_store
    )
```

**Comment by voiprodrigo** [comment]
Hi,

Using the constructor directly will let me use a container url as well?

**Comment by yunhaoling** [comment]
hey @voiprodrigo , sorry I mix up the concept of a container url with an account url.

I check the code and find that we do not support container url -- so the doc is incorrect.

But I think your scenario is reasonable and we should consider adding the support. I'll note this as a feature request and bring it to the team.

**Comment by voiprodrigo** [comment]
@yunhaoling Got it, thanks a lot!
