### ISSUE TITLE
[rest] add backcompat mixin to rest responses

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#20600]
Right now when using our `azure.core.rest.HttpResponse`s, we have to convert these to and from `azure.core.pipeline.transport.HttpResponse`s. Additionally, they can't be used in our pipelines / pollers / pagers etc immediately.

The plan is to give our new requests the same surface design as our old responses, so all policies / transports can handle them without converting them to the old design. To do this, we want to add deprecated properties and methods to our new responses to give it the same shape as the old design. Make sure these properties don't show up in documentation, and try your best to hide them as much as possible

**Comment by lmazuel** [comment]
I need explicit tests that shows "raw_response_hook" and injected policy "per_retry_policies" are acting on a new request/response.
