### ISSUE TITLE
azure-servicebus: `TimeoutError: Authorization timeout` after message reading for many hours

### ISSUE THREAD

**Issue by Indy2222** [Azure/azure-sdk-for-python#20649]
- **Package Name**: azure-servicebus
- **Package Version**: 7.3.1
- **Operating System**: Linux
- **Python Version**: 3.9

**Describe the bug**

A long running Python program listening to a ServiceBus queue always fail with `TimeoutError: Authorization timeout.`. It seems that it usually fails after ~6 hours. The exact exception with traceback is this:

```
ERROR: Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mfp-listener-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/servicebus/_base_handler.py", line 395, in _do_retryable_operation
    return operation(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/mfp-listener-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/servicebus/_servicebus_receiver.py", line 213, in _iter_next
    uamqp_message = next(self._message_iter)
  File "/root/.cache/pypoetry/virtualenvs/mfp-listener-9TtSrW0h-py3.9/lib/python3.9/site-packages/uamqp/client.py", line 1003, in _message_generator
    receiving = self.do_work()
  File "/root/.cache/pypoetry/virtualenvs/mfp-listener-9TtSrW0h-py3.9/lib/python3.9/site-packages/uamqp/client.py", line 395, in do_work
    if not self.client_ready():
  File "/root/.cache/pypoetry/virtualenvs/mfp-listener-9TtSrW0h-py3.9/lib/python3.9/site-packages/uamqp/client.py", line 377, in client_ready
    if not self.auth_complete():
  File "/root/.cache/pypoetry/virtualenvs/mfp-listener-9TtSrW0h-py3.9/lib/python3.9/site-packages/uamqp/client.py", line 363, in auth_complete
    raise compat.TimeoutException("Authorization timeout.")
TimeoutError: Authorization timeout.
```

The exception is preceded for a long time with many logs of this kind:

```
Token on connection b'SBReceiver-*****' will expire soon - attempting to refresh.
ImdsCredential.get_token succeeded
ManagedIdentityCredential.get_token succeeded
DefaultAzureCredential acquired a token from ManagedIdentityCredential
Token put complete with result: 1, status: 202, description: b'Accepted', connection: b'SBReceiver-*****'
```

Redacted version of the failing code looks like this:

```python
sb_client = ServiceBusClient(
    fully_qualified_namespace='*****',
    credential=DefaultAzureCredential(),
)
with sb_client as sb_client:
    receiver = sb_client.get_subscription_receiver(
        topic_name='*****',
        subscription_name='*****',
        receive_mode=ServiceBusReceiveMode.RECEIVE_AND_DELETE,
    )
    with receiver as receiver:
        for message in receiver:
            pass
```

**Comment by yunhaoling** [comment]
thanks for reaching out!

We recently got a similar issue and we think the root cause it due to the token refresh window gap between the service and client side leading to the client trying to refresh a cached token: https://github.com/Azure/azure-sdk-for-python/issues/20573.

Are you using a ClientSecretCredential underneath (which is behind the DefaultAzureCredential)?

**Comment by Indy2222** [comment]
This happens in a K8s cluster with a user assigned manage identity so I suppose that `azure.identity.ManagedIdentityCredential` is used under the hood.

**Comment by yunhaoling** [comment]
thanks @Indy2222 for the input, we're working on improving the token refresh logic to avoid throttling the client/service.

Currently there's one-minute token refresh window gap between the client and service resulting in uamqp keeping trying to refresh token. We suspect too many request leads to the unstable authentication status.

FYI I already have a draft PR out: https://github.com/Azure/azure-uamqp-python/pull/277/files.

As a workaround of the issue for now, I would recommend you to do retry on your side -- redoing the operation or recreating client.
