### ISSUE TITLE
Example for create_entity method is corrupted

### ISSUE THREAD

**Issue by kinetix-webmaster** [Azure/azure-sdk-for-python#20652]
I noticed the example for the create_entity method is missing a few lines and columns.
On this page: [azure.data.tables.TableClient class](https://docs.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables.tableclient?view=azure-python#create-entity-entity----kwargs-) (this can also be found in the Document Details section)

In case anyone noticed this too, below is my best reconstruction:
```python
# LOST DATA
class InsertDeleteEntity():
    def __init__(self):
        from azure.data.tables import TableEntity
		
        self.account_name = 'MyStorageAccount'
        self.access_key = '[an access key, similar to TXlTZWNyZXRTdG9yYWdlQWNjb3VudEFjY2Vzc0tleQ==]'
        self.endpoint = 'https://MyStorageAccount.table.core.windows.net/'
        self.table_name = 'MyTable'
        # self.entity = { 'RowKey':'myRowKey', 'PartitionKey':'myPartitionKey' }
        self.entity = TableEntity(RowKey='myRowKey', PartitionKey='myPartitionKey')

    def create_entity(self):
        from azure.data.tables import TableClient
        from azure.core.exceptions import ResourceNotFoundError, ResourceExistsError
        from azure.core.credentials import AzureNamedKeyCredential

        credential = AzureNamedKeyCredential(self.account_name, self.access_key)
        with TableClient(endpoint=self.endpoint, table_name=self.table_name, credential=credential) as table_client:
# BEGIN KNOWN DATA
            try:
                resp = table_client.create_entity(entity=self.entity)
                print(resp)
            except ResourceExistsError:
                print("Entity already exists")
        # [END create_entity]

    def delete_entity(self):
        from azure.data.tables import TableClient
        from azure.core.exceptions import ResourceNotFoundError, ResourceExistsError
        from azure.core.credentials import AzureNamedKeyCredential

        credential = AzureNamedKeyCredential(self.account_name, self.access_key)
        with TableClient(endpoint=self.endpoint, table_name=self.table_name, credential=credential) as table_client:

            # Create entity to delete (to showcase etag)
            try:
                resp = table_client.create_entity(entity=self.entity)
            except ResourceExistsError:
                print("Entity already exists!")

            # [START delete_entity]
            table_client.delete_entity(row_key=self.entity["RowKey"], partition_key=self.entity["PartitionKey"])
            print("Successfully deleted!")
            # [END delete_entity]

############ <- lost columns
if __name__ == "__main__":
    ___ = InsertDeleteEntity()
    ___.create_entity()
    ___.delete_entity()
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f0fbc3-700d-812f-1cc7-dbac5c748a9b
* Version Independent ID: a53bc37d-1e8d-dde1-3b7f-da7345ec6b60
* Content: [azure.data.tables.TableClient class](https://docs.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables.tableclient?view=azure-python#create-entity-entity----kwargs-)
* Content Source: [docs-ref-autogen/azure-data-tables/azure.data.tables.TableClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-data-tables/azure.data.tables.TableClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kinetix-webmaster** [comment]
I realized that that this is probably not the right place for this issue, I've just opened an issue on the correct repository https://github.com/MicrosoftDocs/azure-docs-sdk-python/issues/1431

**Comment by yunhaoling** [comment]
@kinetix-webmaster , thanks for your feedback. This is the right place 😉
We'll improve the docs based on your code snippets.

**Comment by kinetix-webmaster** [comment]
@yunhaoling Thanks! Sorry about the multiple issues, then. I'll close them both when the time comes.

**Comment by YalinLi0312** [comment]
Hi @kinetix-webmaster, thanks for reaching out. I'll contact the docs team to update the portal. The samples in Github are correct, you can follow up [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/samples/sample_insert_delete_entities.py).
