### ISSUE TITLE
Azure data factory trigger creation using python SDK

### ISSUE THREAD

**Issue by meanirban100** [Azure/azure-sdk-for-python#20664]
- **azure.mgmt.datafactory**: 
- **azure-mgmt-datafactory==1.1.0**: 
- **Windows 10**:
- **Python - 3.8.5**: 

**Describe the bug**
I have been following the steps provided by Microsoft to create ADF triggers using python SDK but it is not working.

https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger?tabs=data-factory#python-sdk

**Expected behavior**
ADF Trigger should be created. 

**Error**
pipeline_reference = PipelineReference('copyPipeline') TypeError: init() takes 1 positional argument but 2 were given

**Additional context**
https://stackoverflow.com/questions/69167397/azure-data-factory-trigger-creation-using-python

**Comment by catalinaperalta** [comment]
Hi @meanirban100! Thanks for reaching out, we'll look into this ASAP. Adding @msyyc to provide more information.

**Comment by shawnxzq** [comment]
@lrtoyou1223 The same document to manage trigger using Python, please help on this, thanks!

**Comment by meanirban100** [comment]
@shawnxzq @lrtoyou1223 Any update on this?

**Comment by shawnxzq** [comment]
@chez-charlie could you please help on this? It's about creating trigger using python SDK following the doc below, thanks!

https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger#python-sdk

@meanirban100 I tagged the wrong owner on this before, sorry for that!

**Comment by shawnxzq** [comment]
@chez-charlie any progress on this? Thanks!

**Comment by shawnxzq** [comment]
@chez-charlie Please update here if any progress, thx!
