### ISSUE TITLE
Query ALL azure services available in EACH region by azure sdk for python

### ISSUE THREAD

**Issue by yansyunchen** [Azure/azure-sdk-for-python#20679]
I know we can use the following code to list all available region by my subscription.

sms = ServiceManagementService(subscription_id, certificate_path)
result = sms.list_subscriptions()
for location in result:
    print(location.name)

But I wonder is that possible or do we have the feature can list "ALL azure services available in EACH region" by azure python SDK?

E.g.
Web App - Central US
Web App - East Asia
Function App - East US
Service Bus - Japan East
Service Bus - South Asia
...

Thanks in advance.

**Comment by catalinaperalta** [comment]
Hi @yansyunchen, thanks for reaching out! We'll get back to you ASAP. Adding @msyyc to provide more guidance.

**Comment by msyyc** [comment]
Thank you for your @yansyunchen, we will investigate asap.

**Comment by RAY-316** [comment]
@yansyunchen Because the python SDK is generated based on the services provided by the service-team, we will give feedback on this and let you know as soon as possible if this function is feasible

**Comment by BigCat20196** [comment]
Hi @yansyunchen, If possible, this will be a good feature. Unfortunately, the python SDK is generated based on the [RestAPI](https://github.com/Azure/azure-rest-api-specs). Please go [here](https://github.com/Azure/azure-rest-api-specs/issues) to feed back the issue. Once such an API is updated, we will generate the corresponding function asap.
