### ISSUE TITLE
get_storage_info_for_blob returns ClientError, TooManyDevicesError

### ISSUE THREAD

**Issue by BillmanH** [Azure/azure-sdk-for-python#20695]
Using the method described in [this doc](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-file-upload), and reviewing the [throttle limits here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits)

There is only one single device for this use case no other devices registered in my IoT Hub. I'm using the same devices every time. And I'm only uploading one file at a time (or at least I think I am). However once you get this message you can never use that device connection string again and you must get a new device. Am I missing some kind of `disconnect` and is there really no way to repair the device once you get this message?

Here is the full source code I'm using for upload:
https://github.com/BillmanH/learn-iothub/blob/main/devices/camera.py

This notebook shows the framework of the issue: 
https://github.com/BillmanH/learn-iothub/blob/main/notebooks/Using%20the%20IoTHubDeviceClient.ipynb

## Full Stack trace:
```
ClientError: ClientError('Unexpected failure') caused by ServiceError('HTTP operation returned: 403 TooManyDevicesError(Error: Forbidden)')
---------------------------------------------------------------------------
ServiceError                              Traceback (most recent call last)
~\anaconda3\envs\azure-iot\lib\site-packages\azure\iot\device\iothub\sync_clients.py in handle_result(callback)
     33     try:
---> 34         return callback.wait_for_completion()
     35     except pipeline_exceptions.ConnectionDroppedError as e:

~\anaconda3\envs\azure-iot\lib\site-packages\azure\iot\device\common\evented_callback.py in wait_for_completion(self, *args, **kwargs)
     69         if self.exception:
---> 70             raise self.exception
     71         else:

ServiceError: ServiceError('HTTP operation returned: 403 TooManyDevicesError(Error: Forbidden)')

The above exception was the direct cause of the following exception:

ClientError                               Traceback (most recent call last)
C:\Users\WILLIA~1.HAR\AppData\Local\Temp/ipykernel_4496/1912816677.py in <module>
----> 1 blob_info = client.get_storage_info_for_blob("camera-images")
      2 sas_url = "https://{}/{}/{}{}".format(
      3             blob_info["hostName"],
      4             blob_info["containerName"],
      5             blob_info["blobName"],

~\anaconda3\envs\azure-iot\lib\site-packages\azure\iot\device\iothub\sync_clients.py in get_storage_info_for_blob(self, blob_name)
    587         callback = EventedCallback(return_arg_name="storage_info")
    588         self._http_pipeline.get_storage_info_for_blob(blob_name, callback=callback)
--> 589         storage_info = handle_result(callback)
    590         logger.info("Successfully retrieved storage_info")
    591         return storage_info

~\anaconda3\envs\azure-iot\lib\site-packages\azure\iot\device\iothub\sync_clients.py in handle_result(callback)
     54         raise exceptions.ClientError(message="Client has already been shut down", cause=e)
     55     except Exception as e:
---> 56         raise exceptions.ClientError(message="Unexpected failure", cause=e)
     57 
     58 

ClientError: ClientError('Unexpected failure') caused by ServiceError('HTTP operation returned: 403 TooManyDevicesError(Error: Forbidden)')
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea385b9e-e74a-e94a-00d0-eab29d39973f
* Version Independent ID: 0e514420-4600-ab36-7922-b70007ac2bfb
* Content: [azure.iot.device.IoTHubDeviceClient class](https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.iothubdeviceclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-iot-device/azure.iot.device.IoTHubDeviceClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-iot-device/azure.iot.device.IoTHubDeviceClient.yml)
* Product: **azure-iot**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by lmazuel** [comment]
Issue moved to [Azure/azure-iot-sdk-python #851](https://github.com/Azure/azure-iot-sdk-python/issues/851) via [**ZenHub**](https://www.zenhub.com/)
