### ISSUE TITLE
add more samples for the ACR 

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-python#20696]
Please add more samples for ACR, to provide coverage consistent with other languages, such as .Net
https://github.com/Azure/azure-sdk-for-net/tree/Azure.Containers.ContainerRegistry_1.0.0-beta.4/sdk/containerregistry/Azure.Containers.ContainerRegistry/samples
-Get started with the HelloWorld sample either synchronously or asynchronously.
-Manage a registry by deleting old images synchronously or asynchronously.
-Set read/write/delete properties on an image synchronously or asynchronously.
-List tags on an image using an anonymous access client synchronously or asynchronously.

The samples needed for content at Microsoft doc sites, official sample release is not urgent, but missing samples block content writer at this point.

**Comment by YalinLi0312** [comment]
Fixed.
