### ISSUE TITLE
[SchemaRegistry] arch boarding review feedback

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#20703]
https://github.com/Azure/azure-sdk/issues/3303

**SchemaRegistry**
- [x] discuss with feature crew about combining `register_schema` and `get_schema_properties`
- [x] update all discussed positional args to required keyword args + move Schema/SchemaProperties params to kwargs
- [x] remove cache on client
- [x] rename `SerializationType` to `SchemaFormat` + `serialization_type` to `format`
- [x] rename `content` to `schema_definition`
- [x] Rename endpoint to fully_qualified_namespace on client
- [x] Investigate using BinaryData instead of string as the type for the content parameter and property type in SchemaRegistrySchema
- [x] Come up with guidance around the recommended use of AutoRegisterSchema and make sure it aligns with our default value.
_______
**AvroSerializer**
- [x] make `group_name` required kwarg
- [x] make `schema` param in `serialize` a kwarg --> will allow us to add `id` kwarg later, if user wants to pass in `schema_id` instead.
- [x] change Dict to Mapping in avro `serialize` method
_______
.NET issue: https://github.com/Azure/azure-sdk-for-net/issues/24035
JS issue: https://github.com/Azure/azure-sdk-for-js/issues/17697
Python:
- SR: https://apiview.dev/Assemblies/Review/21d5a1c19a6845cf9549faf0e30db2e1
- SR Avro serializer: https://apiview.dev/Assemblies/Review/a235ef6b8d2a4ab1a2c56d76d1a01b87

**Comment by swathipil** [comment]
- [ ] discuss with feature crew about combining `register_schema` and `get_schema_properties`
- [ ] investigate process to change/register namespace for serializer + async + package name
- [ ] update all discussed positional args to required keyword args
- [ ] change Dict to Mapping in avro `serialize` method

**Comment by swathipil** [comment]
Ramya: 
- in all other places, create_if_not_exists is coupled with a get method (like storage). Since this is an existing pattern, we should keep both (where registers acts as create_if_not_exists)
- not common where a get method also registers, even if a flag is passed in
