### ISSUE TITLE
[SchemaRegistry] rename namespace + package names

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#20711]
- [x] investigate process to change/register namespace for serializer + async serializer + package names
- [x] CONFIRM WITH JOHAN:
rename package name: azure-avroserializer (?) or azure-schemaregistry-avroserializer(?)

rename namespace for serializer: azure.schemaregistry.serializer.avroserializer.AvroSerializer 

async serializer namespace: azure.schemaregistry.serializer.avroserializer.aio.AvroSerializer

**Comment by yunhaoling** [comment]
nspkg: azure.schemaregistry.serializer

**Comment by swathipil** [comment]
schemaregistry is acting as namespace package, so don't need nspkg
