### ISSUE TITLE
Support serializing JsonWebKey to IETF-standard JWK

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#20731]
Add support to serialize an `Azure.Security.KeyVault.Keys.JsonWebKey` to an [IETF-standard](https://datatracker.ietf.org/doc/html/rfc7517) JWK.

See https://github.com/Azure/azure-sdk-for-net/issues/16155 for discussion. You might review what you did for track 1, if you had a track 1 library, taking into account current SDK guidelines.

**Comment by mccoyp** [comment]
Python's [JsonWebKey](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py#L24) has IETF-standard-compliant properties (`kid`, `kty`, `key_ops`, etc.) and satisfies these requirements today.
