### ISSUE TITLE
azure-storage-file-datalake DataLakeServiceClient.get_paths() raises ResourceNotFoundError

### ISSUE THREAD

**Issue by pdworzynski** [Azure/azure-sdk-for-python#20773]
- **Package Name**: azure-storage-file-datalake
- **Package Version**:  12.5.0
- **Operating System**: Ubuntu Linux
- **Python Version**: 3.8.8

**Describe the bug**
`DataLakeServiceClient` class method `get_paths()` returns `ResourceNotFoundError: Operation returned an invalid status 'The specified container does not exist.'`

**To Reproduce**
```py
service_client = DataLakeServiceClient(account_url=f"https://{azure_storage_account_name}.blob.core.windows.net/", credential=sas_token)
file_system_client = service_client.create_file_system("test-file-system")
print(f"{file_system_client.exists()=}") # prints "file_system_client.exists()=True"
print(next(file_system_client.get_paths()))
```
Throws `ResourceNotFoundError: Operation returned an invalid status 'The specified container does not exist.'` error. The error also seems to occur for non-empty file systems.

**Expected behavior**
The function should return an empty iterator.

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiafu-msft** [comment]
Hi @pdworzynski 

Thanks for reaching out. If you are using an HNS enabled account, can you please change the url suffix to **dfs**.core.windows.net and try again? 

Let me know if it doesn't work.

**Comment by pdworzynski** [comment]
Hi @xiafu-msft 

This solved the problem. 

Thank you!
