### ISSUE TITLE
Deprecate Track 1 Azure Monitor Query Packages

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#20794]
Tracking issue to deprecate Track1 SDKs that never made it to GA https://pypi.org/project/azure-loganalytics/ and https://pypi.org/project/azure-applicationinsights/ after the Track2 GA of Azure Monitor Query ships.

**Comment by rakshith91** [comment]
https://pypi.org/project/azure-loganalytics/ is marked as inactive

https://pypi.org/project/azure-applicationinsights/ does not have complete feature compatibility. Closing this issue for now and will re open if necessary

**Comment by scottaddie** [comment]
Reopening per a discussion with Rakshith. We need to create a migration guide showing customers how to migrate away from the Events API in the azure-applicationinsights package.

**Comment by scottaddie** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-python/pull/23002
