### ISSUE TITLE
Unable to authenticate AzureStack using ADFS authentication with UserPassCredentials

### ISSUE THREAD

**Issue by sushilchand** [Azure/azure-sdk-for-python#20802]
I am trying to authenticate AzureStack ADFS environment using the below class

credentials = UserPassCredentials(c["username"], c["password"], cloud_environment=cloud)
where cloud is an object used containing the endpoint.

While executing this I am constantly facing issue which throws the error stack

Traceback (most recent call last):
  File "C:\devtools\Python-3.5.4\lib\site-packages\msrestazure\azure_active_directory.py", line 322, in set_token
    self.id
  File "C:\devtools\Python-3.5.4\lib\site-packages\adal\authentication_context.py", line 164, in acquire_token_with_username_password
    return self._acquire_token(token_func)
  File "C:\devtools\Python-3.5.4\lib\site-packages\adal\authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "C:\devtools\Python-3.5.4\lib\site-packages\adal\authentication_context.py", line 162, in token_func
    return token_request.get_token_with_username_password(username, password)
  File "C:\devtools\Python-3.5.4\lib\site-packages\adal\token_request.py", line 293, in get_token_with_username_password
    token = self._get_token_username_password_managed(username, password)
  File "C:\devtools\Python-3.5.4\lib\site-packages\adal\token_request.py", line 177, in _get_token_username_password_managed
    return self._oauth_get_token(oauth_parameters)
  File "C:\devtools\Python-3.5.4\lib\site-packages\adal\token_request.py", line 112, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "C:\devtools\Python-3.5.4\lib\site-packages\adal\oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"MSIS9659: Invalid \u0027username\u0027 or \u0027password\u0027."}

I ensured that the credentials are valid and I am able to login to the azure stack portal using these. On further research I found the REST API which is thowing this error and executed one REST call but the same error

C:\Users\devel>curl -X "POST" "https://adfs.vtasazs2.vxindia.veritas.com/adfs/oauth2/token/" -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "client_id=<client_id>" --data-urlencode "grant_type=password" --data-urlencode "username=<username>" --data-urlencode 'password=<password>' --data-urlencode "resource=<resource_endpoint>"
{"error":"invalid_grant","error_description":"MSIS9659: Invalid \u0027username\u0027 or \u0027password\u0027."}

The user which I am trying is admin and still I am unable to authenticate, can someone help on this ?

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by sushilchand** [comment]
Can someone help on this ?

**Comment by bganapa** [comment]
taking a look now. Thanks for routing to us!

**Comment by abbhar** [comment]
can you pass tenant while creating UserPassCredentials object. you should be able to pass 'adfs' or tenant guid-id as tenant. 
please try this:

`   from msrestazure.azure_cloud import get_cloud_from_metadata_endpoint
    mystack_cloud = get_cloud_from_metadata_endpoint('<ARM EndPoint>')
    credentials = UserPassCredentials(
        username = '<UserName>',
        password = '<password>',
        tenant='adfs',
        cloud_environment=mystack_cloud
    )`

**Comment by sushilchand** [comment]
I tried passing tenant (adfs and guid both) to UserPassCredential but still facing the error of "invalid grant".

**Comment by bganapa** [comment]
@sushilchand 
Your azurestack stamp ADFS is being federated with another ADFS instance?( As explained in the following link)
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity?view=azs-2102

If Yes, Silent UserName/Password credentials is not expected to work.  It needs to be interactive.

We highly recommend using service principal with restricted scope for automation purposes

**Comment by bganapa** [comment]
@sushilchand documented here
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity?view=azs-2102#spn-creation
![image](https://user-images.githubusercontent.com/12038849/135332501-ae9c5d2c-6bdc-4ac3-90f2-079c6db08d94.png)


You may want to refer to our sample here (if not already) , Feel free to @bganapa for azure stack sdk issues
https://github.com/Azure-Samples/Hybrid-ResourceManager-Python-Manage-Resources

**Comment by sushilchand** [comment]
We created one client secret based service principal and added the role to the subscription as per the below doc.
https://docs.microsoft.com/en-us/azure-stack/operator/give-app-access-to-resources?view=azs-2102&tabs=az1%2Caz2&pivots=state-connected#manage-an-ad-fs-app

We also added additional role by running the following command.
New-AzRoleDefinition -InputFile "rbac_role.json"
in rbac_role.json we have defined  a custom role with all the required actions.

We are getting the following error for listing virtual machines:
azure.core.exceptions.ClientAuthenticationError: Authentication failed: MSIS9605: The client is not allowed to access the requested resource.

**Comment by sushilchand** [comment]
Hi @bganapa 
we created SPN and was able to get subscription list using the below PS script
`$GrantBody = 'grant_type=client_credentials&resource={0}&client_id={1}&client_secret={2}' -f $AppIdUri, $ClientID, $ClientKey
$AADTokenResponse = Invoke-RestMethod -Uri $AADURI -ContentType "application/x-www-form-urlencoded" -Body $GrantBody -Method Post -Verbose
$AADtoken = $AADTokenResponse.access_token

$AADtoken
$Headers = @{
    'Authorization' = "Bearer $AADtoken"
    'Accept' = "application/json"
    'x-ms-effective-locale' = "en.en-us"
}
 
$GetSubscriptionsURI = "https://management.$regionName.$azurestackFqdn/subscriptions?api-version=1.0&includeDetails=true"
$Subscriptions = (Invoke-RestMethod -Uri $GetSubscriptionsURI -ContentType "application/json" -Headers $Headers -Method Get -Debug -Verbose).value
$Subscriptions`

But if we are trying using the python SDKs we are getting error
azure.core.exceptions.ClientAuthenticationError: Authentication failed: MSIS9605: The client is not allowed to access the requested resource.

Code
`credentials = ClientSecretCredential(tenant_id, client_id, secret, authority=auth_url)
sc = SubscriptionClient(credentials, base_url=base_url, credential_scopes=[resource + '/.default'], profile=KnownProfiles.v2019_03_01_hybrid)

for s in sc.subscriptions.list():
    print('subscription = {}'.format(s.subscription_id))`
