### ISSUE TITLE
Switching Tenant without relogin

### ISSUE THREAD

**Issue by tikicoder** [Azure/azure-sdk-for-python#20804]
**Is your feature request related to a problem? Please describe.**
Right now the only way I can see to switch a tenant is via login, even if the tenant is the same login.

**Describe the solution you'd like**
What would be nice is if you could set a tenant as part of getting resources similar to subscriptions, or if the SDK (at least the python sdk) work closer to the cli.

**Describe alternatives you've considered**
using subprocess to call az account set to set the account to a subscription that is in the tenant request.

**Additional context**
if I run the command az account list I will get access to all the subscriptions across all tenants I am authenticated for. If I use SubscriptionClient in the python sdk it only gets the subscriptions for the active tenant. The login wouldn't be a bad option if it didn't cause an interactive session unless it is needed.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by anuragdalmia** [comment]
This is not a subscription lifecycle issue. This is potentially an ARM API ask.

**Comment by tikicoder** [comment]
How can I see this in action? Or do I just need to dig in the code and figure it out?

**Comment by tikicoder** [comment]
/unresolve

I Was looking to see how I Can see this in action.
I do not see any comments about how I can do this

**Comment by BigCat20196** [comment]
Hi @tikicoder, thanks for your feedback !

Unfortunately, `az account list` is a customized product of Azure-cli, and the python SDK is generated based on the [RestAPI](https://github.com/Azure/azure-rest-api-specs). Please go [here](https://github.com/Azure/azure-rest-api-specs/issues) to feed back the issue. Once such an API is updated, we will generate the corresponding function asap.
