### ISSUE TITLE
blob_service.exists() logs error

### ISSUE THREAD

**Issue by jambt** [Azure/azure-sdk-for-python#2082]
Hi,

I found a problem that the blockblockservice _logs_ an error (does not throw one) when exists() is called on a non-existing file.

```
from azure.storage.blob import BlockBlobService

storage_name = "xxxx"
account_key = "yyyyy"
blob_name = "zzzzz"

blob_service = BlockBlobService(account_name=storage_name, account_key=storage_key)
print(blob_service.exists(blob_name, "does_not_exist"))
```

This produces the following output:
```
ERROR:azure.storage.common.storageclient:Client-Request-ID=2ddaedf3-1d2c-11e8-af2e-4ce173460adf Retry policy did not allow for a retry: Server-Timestamp=Thu, 01 Mar 2018 08:40:27 GMT, Server-Request-ID=2881fe87-201e-012f-2738-b16ad6000000, HTTP status code=404, Exception=The specified blob does not exist.ErrorCode: BlobNotFound.
False
```
While the correct answer (`False`) is given, the logged error is unexpected.

Is this the intended behaviour?

**Comment by lmazuel** [comment]
@zezha-msft to the rescue :)

**Comment by zezha-msft** [comment]
Hi @jambt, thanks for reaching out!

Yes, we are aware of this issue. Right now all HTTP errors are being logged, even though some of them were expected. We are still looking for a solution. I'm tracking this issue by keeping this [pr](https://github.com/Azure/azure-storage-python/pull/399) open.

In the future, please post issues [here](https://github.com/Azure/azure-storage-python) for problems related to storage. Thank you!

**Comment by lmazuel** [comment]
Thanks @zezha-msft. Closing this issue, @jambt please follow the work on the links @zezha-msft gave.
