### ISSUE TITLE
Cannot generate SAS Token for Azure Datalake gen 2 using Python SDK 

### ISSUE THREAD

**Issue by aboscus** [Azure/azure-sdk-for-python#20824]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.3.1
- **Operating System**: Linux App Service on a Python Azure Function
- **Python Version**: 3.7.9

**Describe the bug**
I’m trying to generate a SAS Token for a file system in an azure datalike gen 2 using the python sdk documented here (method: [generate_file_system_sas](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake?view=azure-python#generate-file-system-sas-account-name--file-system-name--credential--permission-none--expiry-none----kwargs-)).
The function is called and return a SAS token, in the right form, but when I try to use it, it is not valid. 

**To Reproduce**
1. create a python script file
2. call this function referring to an azure data lake: 
`sas_token = generate_file_system_sas(
                account_name = account_name,
                file_system_name = container_name,
                credential = account_key,
                permission = FileSystemSasPermissions(read=True, list=True),
                start = initial_date,
                expiry = expiry_date
   )`
3. get the sas token
4. use the sas to access the file system, it won't work.

**Expected behavior**
The generated SAS token is valid. 

**Additional context**
I call the python script inside a python azure function, but it doens't depend on the azure function itself.

**Comment by xiafu-msft** [comment]
Hi @aboscus 

what operation are you trying to do with that sas

**Comment by aboscus** [comment]
@xiafu-msft I need to generate a SAS Token for a file system in order to use it in PowerBI to show the images inside the file system.

**Comment by xiafu-msft** [comment]
Hi @aboscus 

What error did you get? do you have a x-ms-request-id header by chance?
