### ISSUE TITLE
[formrecognizer] Remove/simplify assertion helpers for v2

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#20844]
@catalinaperalta commented on [Mon Aug 30 2021](https://github.com/Azure/azure-sdk-for-python-pr/issues/703)

After determining how much to test v2 transforms, go through and remove/simplify assertion helpers.

**Comment by catalinaperalta** [comment]
Closing this since the recent test pass still has many tests that use these assertion helpers for FRC and FTC. Will consider reducing once more of FRC and FTC tests are removed.
