### ISSUE TITLE
[formrecognizer] should we use account or resource when naming get_account_info?

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#20851]
@kristapratico commented on [Thu Sep 23 2021](https://github.com/Azure/azure-sdk-for-python-pr/issues/784)

We previously used account, but pretty much all docs refer to "form recognizer resource". Should this be get_resource_info?

**Comment by kristapratico** [comment]
Paul also commented wrt the AccountInfo model:

> ##### [Paul] Consider renaming to custom_model_count or custom_document_model_count.
