### ISSUE TITLE
[formrecognizer] define a bounding box class

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#20850]
@kristapratico commented on [Fri Sep 10 2021](https://github.com/Azure/azure-sdk-for-python-pr/issues/731)

To include helper methods. Should we use "box" or go with "polygon"?

https://apiview.dev/Assemblies/Review/36ac7c8c633d4bf6a45ee8672243f195?diffRevisionId=55627ec07d814143a705ce3143b37c69&doc=False&diffOnly=False#ec11e06dcd8c4957ae5397e96c637e88

https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d?diffRevisionId=25f703d59676465684c5014a6fc7d9cb&doc=False&diffOnly=False#9d49557296ea427db4381c26c292aee2

**Comment by catalinaperalta** [comment]
We named the fields `polygon` after the service update. We wont make these a class until the need for the helper methods becomes evident.
