### ISSUE TITLE
[formrecognizer] design currency document field value type

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#20855]
@kristapratico commented on [Fri Sep 10 2021](https://github.com/Azure/azure-sdk-for-python-pr/issues/736)

https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d?diffRevisionId=25f703d59676465684c5014a6fc7d9cb&doc=False&diffOnly=False#814fc6adcfc94303be1adcd7461c7605

---

@kristapratico commented on [Fri Sep 17 2021](https://github.com/Azure/azure-sdk-for-python-pr/issues/736#issuecomment-921917578)

Currency won't be added until beta.2

**Comment by catalinaperalta** [comment]
Added in referenced PRs.
