### ISSUE TITLE
[formrecognizer] ensure AAD auth works before release

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#20860]
@kristapratico commented on [Thu Sep 16 2021](https://github.com/Azure/azure-sdk-for-python-pr/issues/764)

re-enable tests which test this

**Comment by catalinaperalta** [comment]
This is no longer blocking release in and of itself. We could mark the tests as skipped for a few more days?

**Comment by kristapratico** [comment]
these tests were unskipped
