### ISSUE TITLE
[formrecognizer] Check on prebuilt type field links in comments and docs

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#20865]
@catalinaperalta commented on [Fri Sep 10 2021](https://github.com/Azure/azure-sdk-for-python-pr/issues/749)

Check with the service team if they will maintain pages with the fields for each of the prebuilt model types. 

---

@catalinaperalta commented on [Fri Sep 10 2021](https://github.com/Azure/azure-sdk-for-python-pr/issues/749#issuecomment-917307642)

Should probably add to the guidance that you can programmatically access through the get_custom_model method by calling with prebuilt type.

**Comment by catalinaperalta** [comment]
Prebuilt field links should be ready soon, agreed to confirm with Paul on Thursday/Friday. The crew did mention that the field links are accessed through the aka.ms links so this might not be absolutely blocking either.
