### ISSUE TITLE
[EventHub]"azure.eventhub.exceptions.AuthenticationError: Unable to open authentication session on connection EHProduce" on UsGov and China cloud 

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#20875]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the Test Samples [sync_samples/authenticate_with_azure_named_key_credential.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/samples/sync_samples/authenticate_with_azure_named_key_credential.py#L37) on UsGov and China cloud, it runs failed and the error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1114221&view=logs&j=eb4e8fab-410d-5462-8da4-6074733a2525&t=b6f7b4ac-a4ae-5deb-4f15-9b3549f86d60):
![image](https://user-images.githubusercontent.com/57166602/134798936-4264dc07-72d9-4109-b21d-580bee6d2a9a.png)

**Error Track:**
The code that failed is [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/test-resources.json#L225)：
![image](https://user-images.githubusercontent.com/57166602/134798984-6918e96f-57b4-4b27-9549-8981e0ab6378.png)

**Expected Behavior:**
In file test-resources.json, EVENT_HUB_HOSTNAME is available in UsGov and China Cloud.

@benbp , @jameszliao-msft , @lmazuel , @lilyjma , @ramya-rao-a and @annatisch for notification.

**Comment by v-xuto** [comment]
@yunhaoling Creating resources is the same as in the public cloud. I don't understand your question too much.
@benbp  What are your thoughts on this issue?

**Comment by yunhaoling** [comment]
@v-xuto , sorry for not making it clear.

so when I tried to create EH resource on [portal.azure.come](https://portal.azure.com/), I didn't find a location with name "China" or "US Gov" in it:

![image](https://user-images.githubusercontent.com/47871814/136846925-3783a44a-12d0-42b7-a43d-8fc5600bcb37.png)

so I'm wondering whether it needs a separate dedicated subscription or the China/US Gov cloud has its own portal.

**Comment by v-xuto** [comment]
@yunhaoling The China/US Gov cloud has its own portal.
- US Gov cloud: https://portal.azure.us/
- China cloud: http://portal.azure.cn/

**Comment by v-xuto** [comment]
@benbp  Any progress?

**Comment by benbp** [comment]
@v-xuto this is already available as `serviceBusEndpointSuffix`.

**Comment by v-xuto** [comment]
@benbp Okay. Thanks for your help.

**Comment by benbp** [comment]
@v-xuto Ok I think there was an issue with Azure Pipelines not refreshing it's cache of the subscription configuration secrets. Sorry I didn't notice that earlier. I refreshed the cache and re-ran your failed pipeline jobs, but for some reason I think it's picking up your latest changes with the `usgovcloudapi` hardcoded instead of the problem commit with the `serviceBusEndpointSuffix` value.

**Comment by v-xuto** [comment]
@benbp After I update `.servicebus.windows.net` to `parameters('serviceBusEndpointSuffix')` and re-run pipiline, the same error was reported. The problem was not resolved. Please help me to confirm again. For more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1185621&view=logs&j=37d24fbc-679a-57a5-f3d2-cbe8fbd12ca9&t=b3d2368a-13ec-53b7-0aca-3eb4592902c1).
![image](https://user-images.githubusercontent.com/57166602/140884860-d49ebbd9-68f5-4883-8c91-82d6a02ecebb.png)

**Comment by benbp** [comment]
@v-xuto I'm doing some testing but the issue should be fixed now. My updating scripts were targeting the wrong secret :( I'm going to prioritize some work to move these values into a more observable place so you can update and inspect them yourself, and also support logging non-secret arm parameter values.

**Comment by v-xuto** [comment]
@benbp Thanks for your help. This issue has fixed. This is the [result](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1190562&view=results). I will close this issue.
