### ISSUE TITLE
Authenticating with Azure Identity AzureCliCredential to interact with MS Graph (msgraph-sdk-python-core) does not work

### ISSUE THREAD

**Issue by soffensive** [Azure/azure-sdk-for-python#20877]
**Is your feature request related to a problem? Please describe.**
I want to authenticate via CLI credentials and invoke MS Graph calls via the library **msgraph-sdk-python-core**.

So far I am using Azure AD Graph Management client as follows:

```
from azure.common.credentials import get_azure_cli_credentials
from azure.graphrbac import GraphRbacManagementClient

cred, _, tenant_id = get_azure_cli_credentials(
    resource='https://graph.windows.net',
    with_tenant=True)
client = GraphRbacManagementClient(cred, tenant_id)
```

This works reasonably well, but AAD graph will be deprecated and the get_azure_cli_credentials already is deprecated.
So I went for the following approach:

```
from msgraph.core import GraphClient
from azure.identity import AzureCliCredential


azure_cli = AzureCliCredential()

client = GraphClient(credential=azure_cli)
result = client.get('/me')
print(result.json())
```

When trying to execute this, the following error message is shown:

```
AzureCliCredential.get_token failed: Please run 'az login' to set up an account
Traceback (most recent call last):
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 122, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource .default']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/sf_share/scripts/azure_cli_creds_ms_graph.py", line 8, in <module>
    result = client.get('/me')
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/msgraph/core/_graph_client.py", line 46, in wrapper
    return func(*args, **kwargs)
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/msgraph/core/_graph_client.py", line 93, in get
    return self.graph_session.get(self._graph_url(url), **kwargs)
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/msgraph/core/middleware/middleware.py", line 44, in send
    return self._first_middleware.send(request, **kwargs)
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/msgraph/core/middleware/authorization.py", line 20, in send
    {'Authorization': 'Bearer {}'.format(self._get_access_token(context))}
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/msgraph/core/middleware/authorization.py", line 32, in _get_access_token
    return self.credential.get_token(*self.get_scopes(context))[0]
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/azure/identity/_internal/decorators.py", line 27, in wrapper
    token = fn(*args, **kwargs)
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 57, in get_token
    output = _run_command(COMMAND_LINE.format(resource))
  File "/home/blub/cloud/environ/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 128, in _run_command
    raise CredentialUnavailableError(message=NOT_LOGGED_IN)
azure.identity._exceptions.CredentialUnavailableError: Please run 'az login' to set up an account
```

Although the CLI is authenticated and I get a valid access token when executing:
az account get-access-token --output json

It seems the resource .default is causing problems here.

**Describe the solution you'd like**
Make the AzureCliCredential class of the azure-identity library compatible with msgraph-sdk-python-core.

**Describe alternatives you've considered**
I am using Device Code credentials, which works fine but requires me to authenticate always anew, so it is not a solution.

**Additional context**
I posted the issue already to the maintainers of msgraph-sdk-python-core ([https://github.com/samwelkanda](https://github.com/samwelkanda)), which said that:

`Indeed this problem seems to be caused by the underlying call made to the Azure Cli. The desired call to get an access token for use with MS Graph API should be az account get-access-token --resource-type ms-graph. This requires an update to the implementation of the AzureCliCredential class of the azure-identity library, which is outside the scope of this project. `

[https://github.com/microsoftgraph/msgraph-sdk-python-core/issues/106](https://github.com/microsoftgraph/msgraph-sdk-python-core/issues/106)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by gerhardhaering** [comment]
FWIW I have a need for this as well.

**Comment by xiangyan99** [comment]
@soffensive have you tried https://github.com/microsoftgraph/msgraph-sdk-python-core

/cc: @jeking3

**Comment by xiangyan99** [comment]
Also see #14022

**Comment by soffensive** [comment]
> @soffensive have you tried https://github.com/microsoftgraph/msgraph-sdk-python-core
> 
> /cc: @jeking3

Thanks for your answer. Yes I have tried this library as well, please look at the source code in the issue which is using this library.

The following snippet using msgraph-sdk-python-core will result in the error shown above:


```
from msgraph.core import GraphClient
from azure.identity import AzureCliCredential


azure_cli = AzureCliCredential()

client = GraphClient(credential=azure_cli)
result = client.get('/me')
print(result.json())
```

**Comment by soffensive** [comment]
> @soffensive Unfortunately, we didn't upgrade azure-graphrbac to the new azure-identity system yet. You can get more information in [#14022 (comment)](https://github.com/Azure/azure-sdk-for-python/issues/14022#issuecomment-752279618).
> 
> @jeking3 do you have more information to share?
> 
> Thanks.


The problem is not the Azure Graph RBAC library, I want to authenticate via CLI credentials to send MS Graph calls, using the library msgraph-sdk-python-core.

**Comment by stevenhurwitt** [comment]
> @soffensive Unfortunately, we didn't upgrade azure-graphrbac to the new azure-identity system yet. You can get more information in [#14022 (comment)](https://github.com/Azure/azure-sdk-for-python/issues/14022#issuecomment-752279618).
> 
> @jeking3 do you have more information to share?
> 
> Thanks.

Is there a timeline for graphrbac to use new azure-identity yet? Getting this error with azure-graphrbac==0.61.1: `AttributeError: 'AzureCliCredential' object has no attribute 'signed_session'`
