### ISSUE TITLE
[decorators.py:wrapper] EnvironmentCredential.get_token failed: Authentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:

### ISSUE THREAD

**Issue by saumya1212** [Azure/azure-sdk-for-python#20883]
- **EnvironmentCredential**: 
- **Package Version**: 
- **Windows**:
- **3.9**: 

**Describe the bug**
SSL: CERTIFICATE_VERIFY FAILED error when using clientId authentication to create a EventHubConsumerClient

**To Reproduce**
Using following code:
            os.environ["AZURE_TENANT_ID"] = tenantId
            os.environ["AZURE_CLIENT_ID"] = client_id
            os.environ["AZURE_CLIENT_SECRET"] = client_secret
            
            credential = EnvironmentCredential()
            
            self.client = EventHubConsumerClient(fully_qualified_namespace,
                                                 eventhub_name,
                                                 consumer_group="sample",
                                                 credential=credential, http_proxy=self.HTTP_PROXY, ssl_verify=True, logging_enable=True)

**Expected behavior**
Consumer client is created and 

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for your feedback.

To help us understand the scenario, does it work if you don't specify http_proxy=self.HTTP_PROXY and ssl_verify=True?

**Comment by saumya1212** [comment]
No, it does not work:
           ```
 credential = EnvironmentCredential()
            self.client = EventHubConsumerClient(fully_qualified_namespace,
                                                 eventhub_name,
                                                 consumer_group="sample",
                                                 credential=credential)

            logger.info(f"connected to {self.client.eventhub_name}")
            partition_ids = self.client.get_partition_ids()
            logger.info(f"partition_ids:  {partition_ids}")
```

Error log:   partition_ids = self.client.get_partition_ids()
  File "C:\Python\lib\site-packages\azure\eventhub\_consumer_client.py", line 516, in get_partition_ids
    return super(EventHubConsumerClient, self)._get_partition_ids()
  File "C:\Python\lib\site-packages\azure\eventhub\_client_base.py", line 382, in _get_partition_ids
    return self._get_eventhub_properties()["partition_ids"]
  File "C:\Python\lib\site-packages\azure\eventhub\_client_base.py", line 367, in _get_eventhub_properties
    response = self._management_request(mgmt_msg, op_type=MGMT_OPERATION)
  File "C:\Python\lib\site-packages\azure\eventhub\_client_base.py", line 354, in _management_request
    raise last_exception
azure.eventhub.exceptions.EventHubError: Authentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)
Authentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)
2021-09-29:10:03:02,85 WARNING  [get_token_mixin.py:get_token] ClientSecretCredential.get_token failed: Authentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)
2021-09-29:10:03:02,85 WARNING  [decorators.py:wrapper] EnvironmentCredential.get_token failed: Authentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

**Comment by yunhaoling** [comment]
hi @saumya1212, EventHubs is based on protocol AMQP, currently it doesn't support `ssl_verify` configure.

Depending on your logging, it seems like the ssl verification fails when `ClientSecretCredential` is trying to get token.

- Do you run into the same ssl issue when using connection string to connect to the EventHubs? `EventHubConsumerClient.from_connection_string`

**Comment by saumya1212** [comment]
@yunhaoling I am able to successfully create a consumer client via connection string. 
I use the same tenantid, clientid and secret to get the token in which I provide "verify=false" flag. 
And by giving my organization proxy in HTTP_PROXY I am successfully able to create a consumer client using the obtained connection string. 
However the new eventhub provided in out solution does not have a connection and we have to move to Managed Identity. That's where I am getting this issue

**Comment by xiangyan99** [comment]
Thanks for the information. 

Our guess is your company has a networking policy that all requests need to go though your company proxy whose certificate is self signed.

Could you help to check if this is the case?

If this is correct, you may need to add verify=False (sync requests)/verify_ssl=False(async requests)  in your requests to disable the cert check or pass the path of the cert by using cert=<path> (sync requests)/https://docs.aiohttp.org/en/stable/client_advanced.html (async requests).

Thanks.

**Comment by saumya1212** [comment]
@xiangyan99 Yes, all requests need to go through the company proxy. By using connection_verify=False, I was successfully able to create a consumer client
