### ISSUE TITLE
Get the Azure VM IP information

### ISSUE THREAD

**Issue by Julia082** [Azure/azure-sdk-for-python#20907]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Use the python SDK to list VM IP information.
For example: private IP, public IP,vnet, subnet and VM create time.

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

https://github.com/Azure/azure-sdk-for-python/issues/21303

**Comment by xiangyan99** [comment]
Could you give more information about the issue?

**Comment by Julia082** [comment]
Hello @xiangyan99 ,

Following the https://docs.microsoft.com/zh-cn/samples/azure-samples/azure-samples-python-management/compute/
use the SDK to get the azure virtual machines information.
Previously, the IPs information cannot get due to next_link issue.But fixed it after upgrade SDK from 4.x to 20.x .
Now is trying to get the vm status(start or stop ...) and disk size ( for example: C is 80 GB / D is 100GB).
Which attributes can be used?

Thank you so much.
Julia

**Comment by xiangyan99** [comment]
Thanks for providing the information. 

@msyyc, could you help?

**Comment by msyyc** [comment]
Thank you for your feedback and we will investigate it soon.
