### ISSUE TITLE
Endpoint error for customvision classification model and form recognizer prebuilt analyze ID document.

### ISSUE THREAD

**Issue by Radhika-Richy** [Azure/azure-sdk-for-python#20908]
Hi,
I am facing Keyerror:Endpoint while triggering function app using postman however, this works locally with same credentials giving correct prediction of class of document.
Form recognizer-prebuilt analyze is working on the labelling tool https://fott-2-1.azurewebsites.net/prebuilts-analyze with endpoint and API key but while running locally its showing"azure.core.exceptions.ClientAuthenticationError: (401) Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
Code: 401" 
I am using same Endpoint and API Key on pycharm IDE

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kristapratico** [comment]
Hi @Radhika-Richy, are you using the same endpoint/key for both Custom Vision and Form Recognizer? Just want to check that you created a multi-service resource to do this? Info here: https://docs.microsoft.com/en-us/azure/cognitive-services/authentication?tabs=powershell#authenticate-with-a-multi-service-subscription-key

**Comment by Radhika-Richy** [comment]
Hi @kristapratico , no I have separate resources for form recognizer and custom vision training and prediction. I also tried passing all credentials (custom endpoint, prediction key, project id and publish iteration name) directly without using configurations but classification shows Keyerror: Endpoint when triggered.

**Comment by kristapratico** [comment]
Your form recognizer endpoint/key work in the FOTT tool, but don't when you instantiate a client with the SDK, correct? Can you tell me which version of the library you are using? And are you able to provide a small code snippet showing how you are authenticating the client? (sanitize the endpoint/key, of course). Thank you.

**Comment by Radhika-Richy** [comment]
@kristapratico I could resolve form recognizer with code change but unable to do so with custom vision classification, below is the function for document classification,  again this works when i run locally but after deploying as a function app its trigger is giving Keyerror: Endpoint 
![image](https://user-images.githubusercontent.com/54166518/135494432-11d2ee90-84da-4766-aae5-35b08597dcb6.png)

**Comment by kristapratico** [comment]
@areddish can you see any reason why @Radhika-Richy can authenticate with the CustomVisionPredictionClient locally, but not when running in a function app?

**Comment by areddish** [comment]
@Radhika-Richy That error message looks like the Azure Function is running against an earlier version of the Custom Vision SDK. I would verify you are running the same version of the python sdk in the Azure Function as local.
