### ISSUE TITLE
Update Multi-Tenant support to incorporate Arch Board Feedback

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-python#20912]
- Allow multi-tenant authentication by default
- Remove `allow_multitenant_authentication` option from credential constructor kwargs
- Change compat environment variable `AZURE_IDENTITY_ENABLE_LEGACY_TENANT_SELECTION` to `AZURE_IDENTITY_DISABLE_MULTITENANTAUTH`
- Block multi-tenant auth when credentials are configured with tenant id `adfs`

**Comment by xiangyan99** [comment]
Fixed.
