### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by gfranxman** [Azure/azure-sdk-for-python#20939]
It looks like the example no longer works because the DataFactoryManagementClient libraries have changed over to use the azure.identity package.

Rather than 
```
import from azure.common.credentials import ServicePrincipalCredentials
...
credentials = ServicePrincipalCredentials(client_id=APPLICATION_CLIENT_ID, secret=CLIENT_SECRET, tenant=TENANT_ID)
```
try 
```
from azure.identity import ClientSecretCredential
...
credentials = ClientSecretCredential(tenant_id=TENANT_ID, client_id=APPLICATION_CLIENT_ID, client_secret=CLIENT_SECRET )
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5dd478f-5bb1-3b90-27f3-d1b04db40e3f
* Version Independent ID: 60658b32-abc1-3787-ec6d-24ef3bfade4c
* Content: [Azure Data Factory libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/datafactory?view=azure-python)
* Content Source: [docs-ref-services/latest/datafactory.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/datafactory.md)
* Service: **multiple**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by shawnxzq** [comment]
@gfranxman which document do you follow and see the issues? Thanks!

**Comment by shawnxzq** [comment]
@gfranxman Could you please share the doc link you are refer to? Thanks a lot!
