### ISSUE TITLE
General question about using custom python packages in AzureML 

### ISSUE THREAD

**Issue by DaanDuppen** [Azure/azure-sdk-for-python#20937]
Hi,

I Hope this is the correct place to ask this question.

I'm working on a python machine learning project that also runs on AzureML, using the azureML python packages.
I use a private python repository that is a custom package (containing a setup.py file and using "pip install -e ./src" to use the package for development). 
It seems using a python custom package does not work in azureML directly. When building the package, AzureML states it cannot find the "setup.py" file, even though it is available in the src directory.
To solve this I resorted to building wheel file every time I run the azureML pipeline.
Because of this I need to rebuild the docker image every time I run the pipeline because of new .whl file.
This process slows down the development cycle a lot.

Is this the advised way to develop pipelines for AzureML or is there anything I missed? Are there any ways to use scripts from a custom package in azureML without packaging into .whl?

Regards,

Daan

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by luigiw** [comment]
Closing legacy issue.

Please consider upgrading to AzureML v2 CLI/SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2

This can be addressed by workspace connections in v2. Here are some examples. https://github.com/Azure/azureml-examples/blob/main/sdk/python/resources/connections/connections.ipynb
