### ISSUE TITLE
Use Bicep ARM templates

### ISSUE THREAD

**Issue by mikeassel** [Azure/azure-sdk-for-python#20938]
Microsoft is encouraging the use of Bicep ARM templates, it should be possible to use them in the python SDK.

Since it isn't currently possible to deploy a remote Bicep file in Azure (https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-cli#deploy-remote-bicep-file) the SDK should offer an option to source the file locally.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by SaurabhSharma-MSFT** [comment]
@armleads-azure Do you have any updates on this.

**Comment by LiliDeng** [comment]
@xiangyan99 do we support deploy with bicep?
