### ISSUE TITLE
[formrecognizer] Unskip v2.0 compatibility tests 

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#20950]
Unskip these tests when the service side issue for listing v2.x models has been resolved.

**Comment by kristapratico** [comment]
Also unskip `sample_manage_custom_models.py` and `sample_manage_custom_models_async.py` from running in CI here: https://github.com/Azure/azure-sdk-for-python/blob/main/scripts/devops_tasks/test_run_samples.py#L128
