### ISSUE TITLE
Cognitive Search readme and samples issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#20968]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_semantic_search.py#L37), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/async_samples/sample_semantic_search_async.py#L38):
![image](https://user-images.githubusercontent.com/80307197/135396792-0ef042a6-3ecc-4377-be9c-511dfde70a0a.png)

Reason:
TypeError: request() got an unexpected keyword argument 'speller'.

Suggestion:
Update to `query_speller`

@jameszliao-msft , @lmazuel , @meeraharidasa , @AlexGhiondea , @tjprescott for notification.

**Comment by tjprescott** [comment]
Fixed in #20977

**Comment by v-xuto** [comment]
Close this issue, due to PR(https://github.com/Azure/azure-sdk-for-python/pull/20977) merged.
