### ISSUE TITLE
Schema Registry readme and samples issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#20970]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry#register-a-schema), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry#get-the-id-of-a-schema):
![image](https://user-images.githubusercontent.com/80307197/135397912-ffa76925-008a-4120-bc28-8beaf71804df.png)

Reason 1:
The order of the parameters is wrong.
Reason 2:
AttributeError: 'SchemaProperties' object has no attribute 'schema_id'.

Suggestion 1:
Update to `schema_content, serialization_type`
Suggestion 2:
Update to `id`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry#register-a-schema), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry#get-the-schema-by-id), [link3](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry#get-the-id-of-a-schema):
![image](https://user-images.githubusercontent.com/80307197/135398214-f6449ed0-5ccb-46f0-a950-08196564eac4.png)

Reason :
TypeError: __init__() missing 1 required positional argument: 'fully_qualified_namespace'.

Suggestion :
Update to `fully_qualified_namespace`

3.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry#get-the-schema-by-id):
![image](https://user-images.githubusercontent.com/80307197/135377080-622406b0-73fc-4525-98d0-dae546805208.png)

Reason :
AttributeError: 'Schema' object has no attribute 'content'.

Suggestion :
Update to `schema_definition`

4.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry#get-the-id-of-a-schema):
![image](https://user-images.githubusercontent.com/80307197/135377350-3177cbb0-8e64-493c-b51c-79650bb49c94.png)

Reason :
AttributeError: 'SchemaRegistryClient' object has no attribute 'get_schema_id'.

Suggestion :
Update to `get_schema_properties`

5.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry-avroserializer#serialization), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry-avroserializer#deserialization), [link3](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry-avroserializer#event-hubs-sending-integration), [link4](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry-avroserializer#event-hubs-receiving-integration):
![image](https://user-images.githubusercontent.com/80307197/135377505-d8c66ef4-0c12-47be-92aa-1fcf1bb856a4.png)

Reason:
TypeError: __init__() takes 1 positional argument but 3 were given.

Suggestion:
Update to `client=schema_registry_client, group_name=schema_group`

6.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry-avroserializer#serialization), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry-avroserializer#event-hubs-sending-integration):
![image](https://user-images.githubusercontent.com/80307197/135402447-01904a83-ce9c-4e53-a9e7-c9589dc63ed2.png)
![image](https://user-images.githubusercontent.com/80307197/135402493-5179081f-df60-4ada-89b5-23240e20ce49.png)

Reason 1:
TypeError: serialize() takes 2 positional arguments but 3 were given.
Reason 2:
TypeError: serialize() missing 1 required positional argument: 'value'.

Suggestion 1,2:
Update to `value=dict_data, schema=schema_string`

@jameszliao-msft , @lmazuel , @ramya-rao-a , @yunhaoling for notification.

**Comment by swathipil** [comment]
@AFengKK - thanks for your thorough description! PR with fixes will be going out soon.
