### ISSUE TITLE
[Text Analytics] "Run no tests in weekly pipeline (Run tests<1s)"  on Public, UsGov and China cloud

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#20971]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
Run no text analytics tests in weekly pipeline, the message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1119179&view=logs&j=918de6bd-74c7-509e-0e6a-5240d551643f&t=ee3720e5-98a7-5fe7-0153-5be72e72dedf):
![image](https://user-images.githubusercontent.com/57166602/135406263-9733440c-1e47-4fa6-9065-e5ce94fd54ea.png)

But I found that the main branch can run text analytics tests normally in nightly pipeline, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1118345&view=logs&j=735541a3-0db4-5b53-11bd-45ccb99b9950&t=d70d3d3c-8cfa-5da1-39cf-ce5e7b21c547)
![image](https://user-images.githubusercontent.com/57166602/135407056-2614d21b-7bad-410e-aa60-aa69f65690a4.png)

**Expected Behavior:**
Able to run text analytics tests normally. What configuration is missing in the Text Analytics weekly pipeline?  Or is it some other reason?

@benbp, @jameszliao-msft, @lmazuel, @meeraharidasa , @mayurid, @abhahn for notification.

**Comment by kristapratico** [comment]
Hey @v-xuto as far as I know, a test-weekly pipeline that runs in usgov/china has not yet been created for Text Analytics. Let me check with the feature crew to see if other languages regularly test in those clouds. This might be something we add for MQ.

**Comment by v-xuto** [comment]
@kristapratico My question is that when I ran a multi-cloud test on the weekly pipeline, no tests were actually run here in the `Run Tests` section. I don't know why this is the case here? I want you to help see why this is the case here?

@benbp Do you have any ideas?

**Comment by kristapratico** [comment]
@v-xuto can you send the link about the build you mentioned? I can't find it. I see that someone created a tests - weekly pipeline for python text analytics [here](https://dev.azure.com/azure-sdk/internal/_build?definitionId=2919), but I don't see any runs yet.

It also doesn't look like we specify CloudConfig in our [tests.yml](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/tests.yml) file so my guess is that text analytics is currently only set up to run in prod regions. I think we can probably check how other languages are configured to set this up for Python. For example, this PR in .NET seems to have the necessary changes to enable multi-cloud testing: https://github.com/Azure/azure-sdk-for-net/pull/24583/files

Would you like me to open a PR with those changes?

**Comment by benbp** [comment]
@kristapratico the `CloudConfig` parameter is only necessary if you want to override location or test matrix filters/replace queries on a per environment basis. Otherwise, the only required field is `SupportedClouds` to add additional clouds to the weekly pipeline (see [internal wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/389/Configuring-Tests?anchor=configuring-test-environments))

**Comment by v-xuto** [comment]
@kristapratico @benbp  We update `BuildTargetingString: $(BuildTargetingString)` to `BuildTargetingString: azure-ai-textanalytics` in our public. Judging from the results of the pipeline, the problem seems to be solved. Is this the correct way to solve this issue? If so, I will close this issue. The screenshot below is the modification we made.
![image](https://user-images.githubusercontent.com/57166602/136931021-8f9c5538-e837-45f4-b4d3-4bfc4579549a.png)

Text Analytics weekly pipeline result: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1138437&view=results

**Comment by kristapratico** [comment]
Thanks for the help @benbp!

@v-xuto are the text analytics tests passing for sovereign clouds or is there still some work here?

**Comment by v-xuto** [comment]
@kristapratico @benbp  This issue has been resolved, I will close it.
