### ISSUE TITLE
No module named 'azure.storage'; 'azure' is not a package

### ISSUE THREAD

**Issue by albertopumar** [Azure/azure-sdk-for-python#20981]
- **azure-storage-blob**: 
- **12.9.0**: 
- **Ubuntu 20.04**:
- **3.8.10**: 

**Describe the bug**
I have just created a new virtual env on a new machine and I am trying to run a test where I try to download one file from a blob, but when I try to run this python script it is giving me this error:

```
Traceback (most recent call last):
  File "azure.py", line 1, in <module>
    from  azure.storage.blob import BlobServiceClient
  File "/home/azureuser/test/azure.py", line 1, in <module>
    from  azure.storage.blob import BlobServiceClient
ModuleNotFoundError: No module named 'azure.storage'; 'azure' is not a package
```

This is the code that I am running, just a dummy example:

```
from  azure.storage.blob import BlobServiceClient

service_account_path = os.environ['AZURE_STORAGE_CONNECTION_STRING']
client = BlobServiceClient.from_connection_string(service_account_path)
```

**To Reproduce**
1. Create a new virtual environment with `virtualenv venv`
2. Activate the environment with `source venv/bin/activate`
3. Install the dependencies with `pip install azure-storage-blob`
4. Run the script with `python azure.py`

**Expected behavior**
No errors when running the script

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Santhoshkumard11** [comment]
@albertopumar seems like you haven't installed azure core for azure to be recognized as a package.
try this `pip install ﻿azure-core==1.19.0`

**Comment by albertopumar** [comment]
@Santhoshkumard11 I checked that and the azure-core library is installed as a dependency of the `azure-storage-blob`. Anyways, I tried to install it again and it is not working

**Comment by xiafu-msft** [comment]
Hi @Santhoshkumard11 

here's my virtualenv
azure-core==1.19.0
azure-storage-blob==12.6.0
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.6
cryptography==35.0.0
idna==3.2
isodate==0.6.0
msrest==0.6.21
oauthlib==3.1.1
pycparser==2.20
requests==2.26.0
requests-oauthlib==1.3.0
six==1.16.0
urllib3==1.26.7

let me know if it doesn't work.

**Comment by Santhoshkumard11** [comment]
Hey @xiafu-msft You need to address @albertopumar
