### ISSUE TITLE
Availability zone support for the APIs

### ISSUE THREAD

**Issue by subhankarc** [Azure/azure-sdk-for-python#2099]
Currently, when we create a snapshot, we do it like this.

```
compute_client.snapshots.create_or_update(
                self.resource_group,
                snapshot_name,
                {
                    'location': disk_info.location,
                    'tags': tags,
                    'creation_data': {
                        'create_option': DiskCreateOption.copy,
                        'source_uri': disk_info.id
                    }
                }
            )
```

Similarly, for a volume creation, we do it this way

```
compute_client.disks.create_or_update(
                    self.resource_group,
                    disk_name,
                    {
                        'location': instance_location,
                        'tags': tags,
                        'creation_data': {
                            'create_option': DiskCreateOption.copy,
                            'source_uri': snapshot.id
                        }
                    }
                )
```

We were trying to use the availability zone preview version. But the library at this point do not support it. We have the following questions.

1. Is there a way we can pass the availability zone information for disk creation?
2. Our assumption is that snapshot is not a zonal entity. Which would mean that I can create disk in any AZ from a snapshot. Is that understanding correct?
3. Is there a plan or timeline when AZ support will be available for the library?

Regards,
Subhankar

**Comment by lmazuel** [comment]
AZ is supported in this library. However, you might have to create the disk before using the "disks" operation group, since it seems you cannot specify it when you create the VM.
@yugangw-msft any comment or suggestions here?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
