### ISSUE TITLE
AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session' 

### ISSUE THREAD

**Issue by db533** [Azure/azure-sdk-for-python#21007]
- **Package Name**: azure-identity
- **Package Version**: 1.6.1
- **Package Name**: azure-mgmt-resource
- **Package Version**: 2.2.0
- **Operating System**: Windows 10 Home 19042.1237
- **Python Version**: 3.9.5

**Describe the bug**
After creating a resource management client, when trying to use it to return a list of resource groups (or similar code to create a new resource group), the code fails with an attribute error "'ClientSecretCredential' object has no attribute 'signed_session'."

**To Reproduce**

1. Define environment variables for a service principal with Contributor role to the Azure Basic subscription.
2. Run the code below.
3. Results in the error message: "AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session'"

```
import os
from azure.mgmt.resource import ResourceManagementClient
from azure.identity import ClientSecretCredential

def main():
    SUBSCRIPTION_ID = os.environ.get("AZURE_SUBSCRIPTION_ID", None)
    tenant_id = os.environ["AZURE_TENANT_ID"]
    client_id = os.environ["AZURE_CLIENT_ID"]
    client_secret = os.environ["AZURE_CLIENT_SECRET"]
    credential = ClientSecretCredential(tenant_id=tenant_id, client_id=client_id, client_secret=client_secret)

    print("Create resource client...")
    resource_client = ResourceManagementClient(credential, SUBSCRIPTION_ID)
    print("Printing existing resource grouops:")
    for item in resource_client.resource_groups.list():
        print_item(item)

if __name__ == "__main__":
    main()
```
This code results in the following output:
```
Create resource client...
Printing existing resource grouops:
Traceback (most recent call last):
  File "C:\Users\db533\PycharmProjects\GunaBot2\azure-mgmt\azure_test3.py", line 20, in <module>
    main()
  File "C:\Users\db533\PycharmProjects\GunaBot2\azure-mgmt\azure_test3.py", line 16, in main
    for item in resource_client.resource_groups.list():
  File "C:\Users\db533\PycharmProjects\GunaBot2\venv\lib\site-packages\msrest\paging.py", line 143, in __next__
    self.advance_page()
  File "C:\Users\db533\PycharmProjects\GunaBot2\venv\lib\site-packages\msrest\paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "C:\Users\db533\PycharmProjects\GunaBot2\venv\lib\site-packages\azure\mgmt\resource\resources\v2018_05_01\operations\resource_groups_operations.py", line 512, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "C:\Users\db533\PycharmProjects\GunaBot2\venv\lib\site-packages\msrest\service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "C:\Users\db533\PycharmProjects\GunaBot2\venv\lib\site-packages\msrest\pipeline\__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "C:\Users\db533\PycharmProjects\GunaBot2\venv\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "C:\Users\db533\PycharmProjects\GunaBot2\venv\lib\site-packages\msrest\pipeline\requests.py", line 65, in send
    self._creds.signed_session(session)
AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session'
```

**Expected behavior**
Expect the code to return the list of existing resource groups.

**Screenshots**
N/A

**Additional context**
Similar code has worked previously when I ran it in an Ubuntu (20.04) virtual machine, but I do not have access to this VM anymore. I'm now trying to run this code in a venv virtual environment in a PyCharm Community project, running PyCharm on a Windows 10 laptop (same laptop in which the Ubuntu VM was run). The same service principal was used when it worked on Ubuntu VM.

**Comment by xiangyan99** [comment]
Thanks for your feedback.

azure-mgmt-resource 2.2.0 is track 1 library and it is not fully compatible with azure-identity.

You can upgrade azure-mgmt-resource to latest version or https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md for migrations.

Please let us know if any questions.

**Comment by db533** [comment]
Thanks for the quick response. Switching to azure-common credentials, as detailed in the link, did indeed fix the issue.
