### ISSUE TITLE
Example on how to asynchronously create multiple virtual machine instances in parallel

### ISSUE THREAD

**Issue by scoriani** [Azure/azure-sdk-for-python#2104]
A common scenario in many workloads is the ability to asynchronously create multiple VM instances in parallel and check for completion before executing additional configuration steps.
An example on how to implement this scenario with Python SDK would be quite useful.

**Comment by lmazuel** [comment]
Definitely needed :). Thank you for the issue :)

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
