### ISSUE TITLE
[AMQP Python] connection websocket/http proxy

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#21135]
Python doesn't provide built-in websocket support. However, there're 3rd party Python libraries supporting websocket.
We need to investigate more into how to support websocket.

### Background:

The AMQP WebSocket spec: http://docs.oasis-open.org/amqp-bindmap/amqp-wsb/v1.0/amqp-wsb-v1.0.html

1. Websocket: AMQP is an application layer networking protocol. It could be built on top of tcp protocol as well as websocket protocol. The latter one is called AmqpOverWebsocket.
```
AMQP          or               AMQP
   |                             |
 TCP                        Websocket
```
2. Http proxy: proxy provides a way for client to connect to service in limited networking environment (e.g. for security concern, outbound port gets blocked). 
  - it is feature built on top of websocket, there will a tunnel established between client and the service via the proxy using the websocket protocol.

#### feature requirements:
- client supports connecting to service via AmapOverWebsocket
- client supports connecting to service via a http proxy

related keyword argument on client constructors:

```python
    :keyword transport_type: The type of transport protocol that will be used for communicating with
     the Event Hubs service. Default is `TransportType.Amqp` in which case port 5671 is used.
     If the port 5671 is unavailable/blocked in the network environment, `TransportType.AmqpOverWebsocket` could
     be used instead which uses port 443 for communication.
    :paramtype transport_type: ~azure.eventhub.TransportType
    :keyword Dict http_proxy: HTTP proxy settings. This must be a dictionary with the following
     keys: `'proxy_hostname'` (str value) and `'proxy_port'` (int value).
     Additionally the following keys may also be present: `'username', 'password'`.
```

#### impacted module:

transport - consider adding a `WebSocketTransport` implementing the `_AbstractTransport` public interface:

- https://github.com/Azure/azure-sdk-for-python/blob/feature/eventhub/pyproto/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
- https://github.com/Azure/azure-sdk-for-python/blob/feature/eventhub/pyproto/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py

#### uAMQP implementation:
- https://github.com/Azure/azure-uamqp-python/blob/master/src/wsio.pyx#L12-L58
- https://github.com/Azure/azure-uamqp-python/blob/master/uamqp/authentication/common.py#L74

#### python websocket library:

- https://github.com/aaugustin/websockets
- https://github.com/websocket-client/websocket-client

things to consider:
- [x] license
- [ ] proxy support
- [x] community support

### notes:

- to setup a light local http proxy for verification, check: https://github.com/abhinavsingh/proxy.py

**Comment by rakshith91** [comment]
Findings are here https://gist.github.com/rakshith91/70a4e22a5866b4efac8b91b504d736df

**Comment by rakshith91** [comment]
MErged
