### ISSUE TITLE
Exception while installing azure SDK from the github codebase

### ISSUE THREAD

**Issue by anubhav-s** [Azure/azure-sdk-for-python#2118]
comma is missing in install_requires. Throws error "error in azure-keyvault setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in msrest>=0.4.17azure-common~=1.1.5 at ~=1.1.5".

**Comment by anubhav-s** [comment]
Already raised a pull request myself.

https://github.com/Azure/azure-sdk-for-python/pull/2117

**Comment by lmazuel** [comment]
PR merge, thanks @anubhav-s !
