### ISSUE TITLE
[BUG Bash] 

### ISSUE THREAD

**Issue by bquantump** [Azure/azure-sdk-for-python#21184]
**Describe the bug**
The new 1.0.0b3 azure.schemaregistry.serializer.avroserializer seems to not work with the new example

https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry-avroserializer

here is the code
```import os
from azure.eventhub import EventHubProducerClient, EventData
from azure.schemaregistry import SchemaRegistryClient
from azure.schemaregistry.serializer.avroserializer import AvroSerializer
from azure.identity import DefaultAzureCredential
token_credential = DefaultAzureCredential()
fully_qualified_namespace = os.environ['my_namespace']
group_name = "rfframe"
eventhub_connection_str = os.environ['CONNECTION_STRING']
eventhub_name = 'rfinfo'
schema_string = """
{"namespace": "example.avro",
 "type": "record",
 "name": "User",
 "fields": [
     {"name": "name", "type": "string"},
     {"name": "favorite_number",  "type": ["int", "null"]},
     {"name": "favorite_color", "type": ["string", "null"]}
 ]
}"""
schema_registry_client = SchemaRegistryClient(fully_qualified_namespace, token_credential)
avro_serializer = AvroSerializer(client=schema_registry_client, group_name=group_name)
eventhub_producer = EventHubProducerClient.from_connection_string(
    conn_str=eventhub_connection_str,
    eventhub_name=eventhub_name
)
with eventhub_producer, avro_serializer:
    event_data_batch = eventhub_producer.create_batch()
    dict_data = {"name": "Bob", "favorite_number": 7, "favorite_color": "red"}
    payload_bytes = avro_serializer.serialize(dict_data, schema=schema_string)
    event_data_batch.add(EventData(body=payload_bytes))
    eventhub_producer.send_batch(event_data_batch)

```
The eventhub is also present

![image](https://user-images.githubusercontent.com/53361486/136635138-26398d47-a1d4-42d4-860f-301b305966c5.png)

the error message is this

![error](https://user-images.githubusercontent.com/53361486/136635710-7ad09c51-58e0-439d-aef0-75b2df726936.png)

**Comment by bquantump** [comment]
> hey @bquantump, thanks for reaching out.
> 
> can you confirm that azure-schemaregistry-avroserializer 1.0.0b2 work with the code in your application while 1.0.0b3 not working?

Yes, 1.0.0b2 works correctly and we are using it in a application that is working fine.

**Comment by yunhaoling** [comment]
apologize for the late response.

We have introduced breaking changes in the b3 release compared to b2 release regarding to the underlying http layer (encoding/decoding) behavior for data transferred to the service. And I believe it leads to service side failing to locate the exactly same content, and returns Not Found.

Recently the schema registry service has been formally GA, and they have done upgrade on their side, so I can't even get b2  (which is based on an very old version of the swagger) work with the service.

that being said, there're more things going on -- we're considering a completely different approach for the schema registry avro serializer, we are going to change the payload format so it will break you even further.

So I'm sorry that you can't get b2 to work with the b3 version and the future version, and you may need to stick to the b2 version or considering upgrading to the GA version (once after the design gets stabilized).
