### ISSUE TITLE
opinion mining not working as expected.

### ISSUE THREAD

**Issue by ShivanshuPurohit** [Azure/azure-sdk-for-python#21193]
- **Package Name**: azure-ai-textanalytics
- **Package Version**: 5.2.0b1
- **Operating System**: Windows
- **Python Version**: 3.8

**Describe the bug**
I tested the opinion mining example from [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment_with_opinion_mining.py), with some headlines from a financial article. However I noticed that the model is not doing opinion mining at all, and simply reports the sentence level output.

**To Reproduce**
1. Run the code with 
```
documents = [
"""
Earnings before interest, tax, depreciation and amortisation (EBITDA) are likely to fall by 20 percent YooY (down 1.7 percent QoQ) to Rs 358 crore.
"""
]
```

**Expected behavior**
For the model to do opinion mining. Here is the json output
```json
{
 "document": [
  "\n        Earnings before interest, tax, depreciation and amortisation (EBITDA) are likely to fall by 20 percent Y-o-Y (down 1.7 percent Q-o-Q) to Rs 358 crore.\n        "
 ],
 "responses": [
  {
   "document_sentiment": "neutral",
   "Overall scores": {
    "positive": 0.01,
    "negative": 0.08,
    "neutral": 0.91
   }
  },
  {
   "sentence": "\n        Earnings before interest, tax, depreciation and amortisation (EBITDA) are likely to fall by 20 percent YoY (down 1.7 percent QoQ) to Rs 358 crore.",
   "sentence sentiment": "neutral",
   "sentence score": {
    "positive": 0.01,
    "negative": 0.08,
    "neutral": 0.91
   }
  }
 ]
}
```
As you can see, it didn't go below the sentence level to do opinion mining.
Is this perhaps occuring because the model used here cannot understand financial news and I'm testing out of distribution? If so, how can I fine tune it on my data?

**Comment by kristapratico** [comment]
Hi @ShivanshuPurohit, thanks for your issue. With your code, I'm able to reproduce that no opinion mining results are generated from that input. Adding @assafi @abhahn to comment on the expected behavior here.

**Comment by parasharshah** [comment]
Hi, it seems there are not Opinions in this text hence there is no output. The model is generic but should give output even for finance domain if there are opinions to be mined. Have you tried using KPE instead of OM? What is your goal here?

**Comment by kristapratico** [comment]
@ShivanshuPurohit just for clarity in context of the python library, KPE == key phrase extraction and can be used by calling the `extract_key_phrases` method on the TextAnalyticsClient.
