### ISSUE TITLE
Mypy duplicate type error in _file_client.py

### ISSUE THREAD

**Issue by gmartinezmirai** [Azure/azure-sdk-for-python#21223]
- **Package Name**: azure-storage-file-share 
- **Package Version**: 12.6.0
- **Operating System**: Windows Server 2019
- **Python Version**: 3.9.7

**Describe the bug**
Mypy reports a duplicate type signature error on module azure\storage\fileshare\_file_client.py line 684
error: Function has duplicate type signatures

**To Reproduce**
1. Create a conda environment that contains python 3.9.7, pip=20.3.1, mypy 0.902 and azure-storage-file-share 12.6.0 (from pip)
2. Activate the conda environment
3. Create a test.py file that contains "import azure.storage.fileshare"
4. Run mypy test.py

**Expected behavior**
Mypy runs successfully without reporting errors.

**Screenshots**

**Additional context**

**Comment by tasherif-msft** [comment]
Hello @gmartinezmirai the issue has been resolved in this pr https://github.com/Azure/azure-sdk-for-python/pull/19739/files
The fix will be available in our next release!
