### ISSUE TITLE
[AMQP Python] Enabling switching between uamqp and pyamqp in EventHub

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#21246]
in the EH we want to preview with pure python amqp, we should provide a keyword argument to allow users toggle between uamqp and pyamqp as the underlying networking implementation.

### background:

provide a way for users to switch between uamqp and pyamqp implementation in the azure-eventhub sdk

### scope

- allow users to switch between uamqp and pyamqp as the underlying networking protocol implementation when creating the producer/consumer client, could be a keyword argument on the client constructor.
  - beware of the difference between client construction/method call/config variable creation
  - non-blocking-release goal: maximize code reusability in EH when making use of the two different libs

4/27
Tasks:
- [x] Create design gist for interface that uamqp/pyamqp can plug into that producers/consumers use. Discuss with Kashif.
- [x] Initially, if difficult to do otherwise, allow `uamqp_transport` keywords in both Credentials + clients + EventData. Can think of ways to remove this from the credential later.
- [x] If possible, move Amqp Message construction when sending from EventData/AmqpAnnotatedMessage to inside the producer. (This should be possible.)
- [x] If possible, move Credential internals create to inside the producer. (This might be difficult without completely re-creating the object. Though, might be okay to do this since the credential will only be passed in once).
- [ ] push interface changes to main so that we can plug in pyamqp easily when we merge the pyproto branch.

**Comment by yunhaoling** [comment]
check removing uamqp dependency whether breaking?

**Comment by swathipil** [comment]
Notes for updating pyamqp API surface for uamqp switch:
- update Message.message_annotations -> annotations.
