### ISSUE TITLE
from ._application_gateways_operations import ApplicationGatewaysOperations  ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by iwayme** [Azure/azure-sdk-for-python#21252]
- **Package Name**: ApplicationGatewaysOperations
- **Package Version**: ~azure.mgmt.network.v2021_02_01.models
- **Operating System**: Red Hat Enterprise Linux Server release 7.9 (Maipo)
- **Python Version**: Python 3.9.2

**Describe the bug**
Getting below error : ValueError: source code string cannot contain null bytes; when initiating azure network discovery:
Stack Trace:
File "/opt/VRTSsfmh/adm/AzureDiscover.py", line 415, in discover_virtual_networks
     vnet_iter = network_client.virtual_networks.list_all()
   File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/mgmt/network/_network_management_client.py", line 7258, in virtual_networks
     from .v2021_02_01.operations import VirtualNetworksOperations as OperationClass
   File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/mgmt/network/v2021_02_01/__init__.py", line 9, in <module>
     from ._network_management_client import NetworkManagementClient
   File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/mgmt/network/v2021_02_01/_network_management_client.py", line 22, in <module>
     from .operations import ApplicationGatewaysOperations
   File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/mgmt/network/v2021_02_01/operations/__init__.py", line 9, in <module>
     from ._application_gateways_operations import ApplicationGatewaysOperations
 ValueError: source code string cannot contain null bytes

AzureDiscover.py - is out file from where we are calling virtual_networks.list_all() function.

**To Reproduce**
1. Install Python 3.9.2
2. Install Azure SDK with below packages:
adal==1.2.7
azure-common==1.1.27
azure-identity==1.6.0
azure-mgmt-compute==21.0.0
azure-mgmt-monitor==2.0.0
azure-mgmt-network==19.0.0
azure-mgmt-resource==18.0.0
azure-mgmt-storage==18.0.0
azure-storage-blob==12.8.1
azure-storage-common==2.1.0
msal==1.12.0
msrest==0.6.21
msrestazure==0.6.4
requests==2.25.1
3. Create virtual environment 
4. call the networks list_all() API

**Expected behavior**
We have checked the code and tried running this API from some other VMs and we can see that its working fine. 

**Screenshots**

**Additional context**

https://github.com/Azure/azure-sdk-for-python/issues/21303

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by BigCat20196** [comment]
Hi @iwayme, `azure-mgmt-network` has been released to version [19.3.0](https://pypi.org/project/azure-mgmt-network/19.3.0/). Please update to the latest version and try again.

Has it been wrong again recently? If not, we can treat it as an accidental one-time occurrence, which may be due to some unknown reason
