### ISSUE TITLE
How to check status of azure function invocation via python sdk?

### ISSUE THREAD

**Issue by himanshu219** [Azure/azure-sdk-for-python#2127]
This feature is similar to this https://github.com/Azure/azure-cli/issues/4066
My scenario is that I am writing integration tests for azure function and wanted to check whether my function ran successfully. 
Is there another way of doing this reliably using output binding of azure function(reading blob storage logs) or fetching invocation logs?

**Comment by lmazuel** [comment]
As mentionned in the bug you link, this should be followed here:
https://github.com/Azure/azure-functions-host/issues/1329

Thank you,
