### ISSUE TITLE
[Service Bus] How does ServiceBusClient clear its set of _handlers?

### ISSUE THREAD

**Issue by lukipro** [Azure/azure-sdk-for-python#21282]
I am looking through the code of the SDK for Service Bus but fail to understand how does the `ServiceBusClient` object clear its set of `_handlers`.

In the `__init__` function the set is initialized like this:
```
self._handlers = WeakSet()  # type: WeakSet
```
There is a piece of code in the `close()` method but that is called only upon destruction of the `ServiceBusClient`.
In our case the `ServiceBusClient` object is never deleted so this code is not called.

However nowhere in the code I can find a mechanism for removing handlers which are no longer used (which are closed).

I appreciate any guidance on this.
Thanks.

**Comment by yunhaoling** [comment]
hey @lukipro , the SDK is using `WeakSet` to keep the references to handlers and those "dead" handlers which are no longer be referenced will be automatically cleaned up by Python garbage collection.

According to the Python doc for [WeakSet](https://docs.python.org/3/library/weakref.html#weakref.WeakSet):

> Set class that keeps weak references to its elements. An element will be discarded when no strong reference to it exists any more.

More doc for weakref module could be found here: https://docs.python.org/3/library/weakref.html#module-weakref

Please let me know whether it answers your question.

**Comment by lukipro** [comment]
Thanks @yunhaoling for clarifying. The reason I am asking is because we see a memory leak in our app which runs for many days:
![image](https://user-images.githubusercontent.com/20760377/137686893-33b0e697-c44c-4442-95a0-e5bb22f63354.png)
We are using the latest uAMQP library (1.4.2).
Our setup is following:
- we have one ServiceBus client instance.
- then we have 5 threads spawned with the `concurrent` Python library.
- Each of the threads sits in a `while` loop like this:
```
while True:
    try:
        with self.sb_client.get_subscription_receiver(topic_name=self.topic_name,
                                                      subscription_name=self.subscription_name,
                                                      idle_timeout=1,
                                                      session_id=NEXT_AVAILABLE_SESSION) as receiver:
            receiver.session.set_state("OPEN")
            with AutoLockRenewer(max_lock_renewal_duration=30 * 60) as renewer:
                renewer.register(receiver, receiver.session)
                self.handle_session(receiver)
            receiver.session.set_state("CLOSED")
```

I was trying to figure out where possibly can the memory leak originate by inspecting the SDK code.
The only lead I found was that the set of `_handlers` is not explicitly cleared.
I guess there must some other place then.

Would you be able to assist in the investigation?
