### ISSUE TITLE
Getting bad response for several location when i try to get Compute usages by API

### ISSUE THREAD

**Issue by lizzbazan** [Azure/azure-sdk-for-python#21283]
**Describe the bug**
Hi Team, I'm trying to use the template described by microsoft documentation to get subscription compute usage list but i noticed i get the same error for the same locations, for some other locations I get expected results and i work with them like the following example

2021-10-14T16:37:28.312Z] ---- Usage in Subscription : MySubscription  ( id: xxxxxx-xxxxxxxx )  in eastus for Standard DSv2 Family vCPUs 
is: 8 and its limit is: 35

Error for some locations:

HTTP error occurred: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/xxxxxxx-xxxxxxxx/providers/Microsoft.Compute/locations/southafricawest/usages?api-version=2016-08-30

I have to mention I tried with many API versions and i got the same error, and i checked if the compute provider is registered and all is ok:

CloudError: Azure Error: NoRegisteredProviderFound
Message: No registered resource provider found for location 'jioindiacentral' and API version '2020-06-01' for 
type 'locations/usages'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-12-01, 2021-03-01, 2021-04-01, 2021-07-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastas

For example, I noticed I have a subscription that has compute resources in uaecentral but when I try to get the Usage list by my python code using the API, the error occurs 

***Exception or Stack Trace***
HTTP error occurred: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/xxxxxxx-xxxxxxxx/providers/Microsoft.Compute/locations/southafricawest/usages?api-version=2016-08-30

**To Reproduce**
is needed to use the API with any subscription that has compute resources in these locations (in my case, I'm adapting the API to Python code):

jioindiacentral
francesouth
australiacentral2
uaecentral
southafricawest
switzerlandwest
germanynorth
norwaywest
brazilsoutheast

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Get all the usages list for all subscriptions in all the locations, with no bad responses

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8.5]
 - SDK Version: 
 - 
azure-functions
azure-identity==1.5.0
adal==1.2.6
azure-core==1.14.0
azure-mgmt-compute==14.0.0
azure-mgmt-core==1.2.2

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [X ] Repro Steps Added
- [X ] Setup information Added

**Comment by SaurabhSharma-MSFT** [comment]
@lizzbazan I could see that you internally that you are being helped from Aharna Moulick from support ticket on your open issue.  So, wanted to check with you if you want to keep this SDK Repo issue open ? Please let me know.

**Comment by lizzbazan** [comment]
Thanks for your help! @SaurabhSharma-MSFT 

Actually they are still looking for a solution, they said is weird that is possible to get just the VM list for those locations (https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/list ), but the entire compute list quota is not available, I got those response errors
 
Maybe someone else could get helped with this ticket in case of having same problem, we can comment solution over here , or we can close if you as a Team consider it appropriate to don't be working in 2 identical tickets at the same time

Nice day!! ñ.ñ

**Comment by SaurabhSharma-MSFT** [comment]
@lizzbazan Thanks.  I am closing this issue for now.  Please feel free to provide the solution over here once your case gets resolved or if you have any additional questions for us.

Thank you.
Saurabh
