### ISSUE TITLE
[Python] reduce size for `azure-mgmt-network`

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#21301]
In terms of the large size for `azure-mgmt-network`, more customers complain about that. I think the following advice from customers make sense:
I understand the reasoning for the approach to keep everything for backward compatibility but if you do have customers that point to the old versions then they should pin their requirement versions to the old pypi.org releases of the Azure SDK, not force everyone to keep a copy of everything around. ( come from https://github.com/Azure/azure-sdk-for-python/issues/17801#issuecomment-866416193)

**Comment by msyyc** [comment]
https://github.com/Azure/sdk-release-request/issues/2200

**Comment by msyyc** [comment]
will go on in another issue.

**Comment by jiasli** [comment]
21.1MB is still too large. Azure CLI 2.34.1 (https://azcliprod.blob.core.windows.net/msi/azure-cli-2.34.1.msi) is 52.3MB, which means `azure-mgmt-network` is almost half the size of whole Azure CLI.

**Comment by msyyc** [comment]
Let me paste the data in e-mail to raise more attention for architect

**Comment by yehudacohen** [comment]
Is there an update on when this will be ready? It's august already

**Comment by kapilt** [comment]
also why is this specific to azure network, its a design flaw in the sdk across every single service, azure network just happens to be the most egregious.

**Comment by lmazuel** [comment]
Duplicated of https://github.com/Azure/azure-sdk-for-python/issues/11149
