### ISSUE TITLE
Mypy error: Function has duplicate type signatures

### ISSUE THREAD

**Issue by damiondoesthings** [Azure/azure-sdk-for-python#21307]
- **Package Name**: azure-storage-file-share
- **Package Version**: 12.6.0
- **Operating System**: Mac OS 11.6 / ubuntu-18.04
- **Python Version**: 3.8

**Describe the bug**
Duplicate type information causes type checker to fail.
mypy 0.910 will fail with output `azure/storage/fileshare/_file_client.py:684: error: Function has duplicate type signatures`

**To Reproduce**
1. call the `download_file()` function on a FileClient in a python file
2. create mypy.ini with ```[mypy-azure.storage.fileshare.*]]
ignore_missing_imports = True```
2. run mypy on the python file

**Expected behavior**
Mypy should find no errors in the Azure fileshare package.

**Additional context**
This is caused by types in the download_file function being specified twice:
```   @distributed_trace
    def download_file(
            self, offset=None,  # type: Optional[int]
            length=None,  # type: Optional[int]
            **kwargs
        ):
        # type: (Optional[int], Optional[int], Any) -> StorageStreamDownloader```

**Comment by DamionWerner** [comment]
Already fixed with [This pull request](https://github.com/Azure/azure-sdk-for-python/pull/19739)
