### ISSUE TITLE
[Python] Upgrade service documents from Track 1 to Track 2

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-python#21306]
80% documents on Docs should be updated

**Comment by msyyc** [comment]
https://github.com/Azure-Samples/azure-samples-python-management
https://docs.microsoft.com/en-us/azure/developer/python/

**Comment by msyyc** [comment]
tool: https://dev.azure.com/docindex/azure-sdk/_queries/query/828a2764-57b0-46f9-aa65-c97f9aa97767/

**Comment by msyyc** [comment]
handled candidate list:
[python-track1-docs-list.csv](https://github.com/Azure/azure-sdk-for-python/files/7860477/python-track1-docs-list.csv)

**Comment by BigCat20196** [comment]
handled candidate list:
[python-track1-docs-list.csv](https://github.com/Azure/azure-sdk-for-python/files/7963288/python-track1-docs-list.csv)

3 new  PRs in total
Details:
https://github.com/MicrosoftDocs/azure-docs/pull/86877
https://github.com/MicrosoftDocs/azure-docs/pull/87161
https://github.com/Azure-Samples/Hybrid-Resource-Manager-Python-Template-Deployment/pull/2
