### ISSUE TITLE
Image URLs are broken in "Authenticating during local development" section

### ISSUE THREAD

**Issue by ivantarapov** [Azure/azure-sdk-for-python#21320]
Image URLs are broken in "Authenticating during local development" section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d20b7451-8831-4bf4-8d3d-424733763fcf
* Version Independent ID: 9da64e5d-90c7-8942-9ebd-ae092a6f63b3
* Content: [Azure Identity client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#feedback)
* Content Source: [docs-ref-services/latest/identity-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/identity-readme.md)
* Service: **identity**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by mccoyp** [comment]
@scbedd This is an interesting issue. These images were intentionally removed from the readme -- and this is reflected correctly in [azure-docs-sdk-python](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/identity-readme.md#authenticate-during-local-development) -- but the [docs.microsoft.com](https://docs.microsoft.com/python/api/overview/azure/identity-readme?view=azure-python#authenticating-during-local-development) page seems to be trying to load them still. Do you know what could be going on here, or know who else might?

**Comment by mccoyp** [comment]
This was fixed by the deployment; closing now. Thanks Scott!
