### ISSUE TITLE
azure-mgmt-webpubsub Ref docs issues

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#21346]
Cannot produce SDK API Reference Documentation for `azure-mgmt-webpubsub` because of errors in the docs CI process. 

Instructions to fix: 

1. Fix issue in package code to eliminate this error and check into main branch
2. Ensure output is correct in daily docs build (see @danieljurek or @sima-zhu for details)
3. Remove entry from [`$PackageExclusions` in `Language-Settings.ps1`](https://github.com/Azure/azure-sdk-for-python/blob/main/eng/scripts/Language-Settings.ps1#L209)

Build: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=259645&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=25941825-f6be-5547-87e7-b619f675754d&l=189545

```

<Matched Warning>: D:\a\1\s\dist_temp\173\azure-mgmt-webpubsub-1.0.0\doc\azure.mgmt.webpubsub.aio.rst:4: WARNING: error while formatting arguments for azure.mgmt.webpubsub.aio.WebPubSubManagementClient: name 'AsyncTokenCredential' is not defined

##[error]<Matched Error>: C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\azure\mgmt\webpubsub\models\__init__.py:docstring of azure.mgmt.webpubsub.models.EventHandler:14: ERROR: Error in "code-block" directive:
1 argument(s) required, 0 supplied.
.. code-block::
   1. "*", it to matches any event name
   2. Combine multiple events with ",", for example "event1,event2", it matches event "event1"


```

**Comment by danieljurek** [comment]
This was wrongly associated with a PR. The PR in question does NOT fix the issue but prevents the package from onboarding and breaking downstream processes. The issue must still be fixed in the SDK code.

**Comment by msyyc** [comment]
Hi @danieljurek @sima-zhu , the [description](https://github.com/Azure/azure-sdk-for-python/blob/ed691f3888a5c712a2cea77dd06afb9ad4ef9a8b/sdk/webpubsub/azure-mgmt-webpubsub/azure/mgmt/webpubsub/models/_models_py3.py#L663-L675) is generated automatically with [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/591b17c5a50e7fc0ef09211197279e6d9f7ebc22/specification/webpubsub/resource-manager/Microsoft.SignalRService/stable/2021-10-01/webpubsub.json#L1380)
https://github.com/Azure/azure-sdk-for-python/blob/ed691f3888a5c712a2cea77dd06afb9ad4ef9a8b/sdk/webpubsub/azure-mgmt-webpubsub/azure/mgmt/webpubsub/models/_models_py3.py#L663-L675

![image](https://user-images.githubusercontent.com/70930885/199652533-8ba629ac-2065-4da2-b76b-10b6cff9d386.png)
Could you show how to fix it? Thanks!

**Comment by danieljurek** [comment]
It's been a while. I think `code-block` was not supported. Will check in on whether this has changed. 

If not, the fix would be to have the tools which generate this code output different doc comments.

**Comment by danieljurek** [comment]
It seems `code-block` _is_ supported... I'm going to run a test and see if the latest version successfully builds the package in question.

**Comment by msyyc** [comment]
Hi @danieljurek Please help review: https://github.com/Azure/azure-sdk-for-python/pull/27531
