### ISSUE TITLE
[Python] Remaining Issues clean up for Mgmt SDK

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-python#21349]
1. Prioritize customer-reported PRs.
2. Prioritize customer-reported issues.
3. Clean up staled issues and PRs.

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aopen+is%3Aissue+label%3AMgmt : 226(2021/12/06)

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aopen+is%3Aissue+label%3AMgmt  : 100(2021/12/23)

**Comment by ArthurMa1978** [comment]
75 open issues (include mgmt. and llc)
