### ISSUE TITLE
azure-mgmt-quota fails reference docs CI

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#21366]
Cannot produce SDK API Reference Documentation for `azure-mgmt-quota` because of errors in the docs CI process. 

Instructions to fix: 

1. Fix issue in package code to eliminate this error and check into main branch
2. Ensure output is correct in daily docs build (see @danieljurek or @sima-zhu for details)
3. Remove entry from [`$PackageExclusions` in `Language-Settings.ps1`](https://github.com/Azure/azure-sdk-for-python/blob/main/eng/scripts/Language-Settings.ps1#L209)

Build: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=260142&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=1e77462e-7711-551f-cf20-c31b880b493a&l=28529

```

<Matched Warning>: D:\a\1\s\dist_temp\83\azure-mgmt-quota-1.0.0a20211020001\doc\azure.mgmt.quota.aio.rst:4: WARNING: error while formatting arguments for azure.mgmt.quota.aio.AzureQuotaExtensionAPI: name 'AsyncTokenCredential' is not defined

##[error]<Matched Error>: C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\azure\mgmt\quota\aio\operations\__init__.py:docstring of azure.mgmt.quota.aio.operations.QuotaRequestStatusOperations.list:10: ERROR: Error parsing content block for the "list-table" directive: uniform two-level bullet list expected, but row 2 does not contain the same number of items as row 1 (1 vs 2).
.. list-table::
   :header-rows: 1
   * - Field

<Matched Warning>: C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\azure\mgmt\quota\aio\operations\__init__.py:docstring of azure.mgmt.quota.aio.operations.QuotaRequestStatusOperations.list:19: WARNING: Inline substitution_reference start-string without end-string.

##[error]     - Supported operators
   * -



```

**Comment by DuneganS** [comment]
Is there any possibility of getting these documents generated at this point in time?

**Comment by sima-zhu** [comment]
@DuneganS 
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/612/Use-Docker-for-Package-Validation?anchor=reproduce-the-docker-errors

Here is the wiki for you to validate the errors in local. Ping me if anything unclear

**Comment by sima-zhu** [comment]
@DuneganS If the docs passed the validation, then we can add the package back to docs.

**Comment by DuneganS** [comment]
Both of links as part of this inc show that I do not have access (and there is no way to request)

**Comment by ajhous44** [comment]
Also interested in getting this documentation

**Comment by sima-zhu** [comment]
@DuneganS @ajhous44 Sorry for late reply. We grant the permission for all internal employees I think. If you are external customers, you can't run the internal docker, so the docs doesn't apply to you.
