### ISSUE TITLE
I can not update only one key=value for the web app application setting

### ISSUE THREAD

**Issue by 646826** [Azure/azure-sdk-for-python#21375]
- **Package Name**: 
azure.mgmt.web
- **Package Version**: 
5.0.0
- **Operating System**:
linux
- **Python Version**: 
Tested on 3.6 and 3.8

**Describe the bug**
I can not update only one key=value for the web app application setting.
If I try to set only one setting I lose other settings

**To Reproduce**
```
from azure.mgmt.web import WebSiteManagementClient
client = WebSiteManagementClient(credential=DefaultAzureCredential(), subscription_id=subscription_id)
settings = {"properties": {"id:test":5}}
client.web_apps.update_application_settings(resource_group_name=rg_name, name=app_name, app_settings=settings)
```

**Expected behavior**
I want to be able to update only one parameter/Key

Example: I can set one setting from AZ command
`az webapp config appsettings set --name=app_name --resource-group=rsg_name --subscription=sub_name --settings id:test=5`

**Screenshots**

**Additional context**
Example: I can set one setting from AZ command
`az webapp config appsettings set --name=app_name --resource-group=rsg_name --subscription=sub_name --settings id:test=5`

**Comment by BigCat20196** [comment]
Hi @646826, thanks for the feedback !

Update operation is to update all parameters. If only one parameter is written, it will indeed delete other settings. 

If you only want to update a parameter, here is an sample.
```
app_settings = web_client.web_apps.list_application_settings(resource_group_name=rg_name, name=app_name)
app_settings.properties['yourkey'] = 'yourvalue'
res = web_client.web_apps.update_application_settings(resource_group_name=rg_name, name=app_name, app_settings=app_settings).as_dict()

```
<br/>

BTW, many update operations in PythonSDK are implemented in this way. The implementation logic of CLI is the same, but it has been written for you.

**Comment by 646826** [comment]
> Hi @646826, thanks for the feedback !
> 
> Update operation is to update all parameters. If only one parameter is written, it will indeed delete other settings.
> 
> If you only want to update a parameter, here is an sample.
> 
> ```
> app_settings = web_client.web_apps.list_application_settings(resource_group_name=rg_name, name=app_name)
> app_settings.properties['yourkey'] = 'yourvalue'
> res = web_client.web_apps.update_application_settings(resource_group_name=rg_name, name=app_name, app_settings=app_settings).as_dict()
> ```
> 
> 
> BTW, many update operations in PythonSDK are implemented in this way. The implementation logic of CLI is the same, but it has been written for you.

This is exactly what I do, load all the settings, update and then send everything back. But it seems to me that it is unsafe and illogical to work with all settings if I only need to update one parameter.

**Comment by SaurabhSharma-MSFT** [comment]
@BigCat20196 Can you please provide your inputs on this one.

**Comment by BigCat20196** [comment]
Hi @646826,  This is due to design. For example: if we have a scene, add a new setting and delete an existing setting at the same time. Do you think we should implement it in an API operation?

Getting all the settings, then modifying what you need, and then updating back at one time is a more efficient method used in the current architecture. Although it seems very inhumane, it is beneficial to the operation of the computer.

BTW, python SDK behaviors are generated based on [swagger definitions](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/WebApps.json#L1011). If you have a good idea, feel free go [here ](https://github.com/Azure/azure-rest-api-specs/issues)and open a new issue.

fyi: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/examples/CreateOrUpdateStaticSiteBuildAppSettings.json

**Comment by 646826** [comment]
> 
Oh, okay, thanks.
But I prefer to change only the needed setting. If  I make changes for all values I need to check all, because it was updated

**Comment by 646826** [comment]
> Hi @646826, This is due to design. For example: if we have a scene, add a new setting and delete an existing setting at the same time. Do you think we should implement it in an API operation?
> 
> Getting all the settings, then modifying what you need, and then updating back at one time is a more efficient method used in the current architecture. Although it seems very inhumane, it is beneficial to the operation of the computer.
> 
> BTW, python SDK behaviors are generated based on [swagger definitions](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/WebApps.json#L1011). If you have a good idea, feel free go [here ](https://github.com/Azure/azure-rest-api-specs/issues)and open a new issue.
> 
> fyi: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/examples/CreateOrUpdateStaticSiteBuildAppSettings.json

Oh, okay, thanks.
But I prefer to change only the needed setting. If I make changes for all values I need to check all, because it was updated

**Comment by BigCat20196** [comment]
Hi @646826, If so, I recommend you to use [Azure-cli](https://github.com/Azure/azure-cli), which is based on Python SDK and encapsulates many methods. It can `set` a modification you want into the configuration. The python SDK is generated based on [rest](https://github.com/Azure/azure-rest-api-specs), so it implements a single operation.

**Comment by 646826** [comment]
> Hi @646826, If so, I recommend you to use [Azure-cli](https://github.com/Azure/azure-cli), which is based on Python SDK and encapsulates many methods. It can `set` a modification you want into the configuration. The python SDK is generated based on [rest](https://github.com/Azure/azure-rest-api-specs), so it implements a single operation.

It's not exactly what I wanted, but I'll try. Thanks

**Comment by BigCat20196** [comment]
Close this issue. Pls feel free to reopen it  if you have any question.
