### ISSUE TITLE
Calling python3 runbook from another runbook in azure automation

### ISSUE THREAD

**Issue by gm27rjpm** [Azure/azure-sdk-for-python#21374]
Dear Team,

We have a function (named download_file()) which is in a python3 runbook named get_secret.py. We need to use it in an another python3 runbook called register.py.

All these runbooks are created under one of the automation accounts in Azure.

We would like to know how to call/invoke/import the function/script (get_secret.py) from register.py

The below links provide useful information for powershell but couldn't find any details for python.

https://docs.microsoft.com/en-us/azure/automation/automation-child-runbooks

Could you please help me on this.

Regards,
Guru Mohan G

**Comment by SaurabhSharma-MSFT** [comment]
@gm27rjpm We are still waiting to hear back from you.

**Comment by gm27rjpm** [comment]
> @gm27rjpm We are still waiting to hear back from you.

Dear @SaurabhSharma-MSFT,

As suggested, I've raised a new issue as suggested in the above forum.

https://docs.microsoft.com/en-us/answers/questions/602560/calling-python3-runbook-from-another-runbook-in-az.html


Regards,
Guru Mohan G

**Comment by SaurabhSharma-MSFT** [comment]
@gm27rjpm Thank you.  We are closing this issue for now.
