### ISSUE TITLE
Support Azure Scheduler REST API

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#214]
Hi,

I need to use the Azure Scheduler REST API:
http://msdn.microsoft.com/en-us/library/azure/dn528946.aspx

As usual now, I began to wrap it in a new class "SchedulerManagementService", with "list_XXX", "get_XXX" etc.

But, the "Get all jobs" call (http://msdn.microsoft.com/en-us/library/azure/dn528933.aspx) only returns JSON. I tried content negotiation with "application/xml", change "x-ms-version", but I only got JSON.
I don't have any problem with the JSON syntax itself, but the reflective parser behind `_parse_response` can currently only handles XML and I want the Azure answer in a Python object, not JSON.

I think it's possible to re-write `_fill_data_to_return_object`, `_fill_list_of`, etc. to handle either XML and JSON depending of the result format given by Azure. This will allow us to keep the reflective parser with it's "list_of", "dict_of" and other attributes. JSON or XML just change the way you extract the final value to set, not the algorithm itself. As usual, my final goal is to make a pull request. But since it's an heavy modification in the code and risks to take time, I cannot try it without talking with you first to confirm your interest and/or confront ideas to figure this out..

Thank you!

**Comment by antonydenyer** [comment]
Hey @huguesv I'm having some trouble implementing Update Job using the PATCH verb. Any chance you could take a look at my code?

https://github.com/antonydenyer/azure-sdk-for-python/commit/1345871021adf79b1889a73b7f34ef34212dbdfe

The integration test test_update_job is failing with the following XML error:
```
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
<Code>BadRequest</Code>
<Message>No job definition was specified.</Message>
 </Error>
```
Is this endpoint expecting XML? Any ideas?

Thanks

**Comment by huguesv** [comment]
Whenever the REST API doesn't work as described by the docs, I go look at the other implementations.  In this case, I went to the node.js sdk, but couldn't find that functionality there.

However, the C# implementation looks more promising.

CreateOrUpdate (PUT)
https://github.com/Azure/azure-sdk-for-net/blob/master/src/SchedulerManagement/Generated/JobOperations.cs#L79

UpdateState (PATCH)
https://github.com/Azure/azure-sdk-for-net/blob/master/src/SchedulerManagement/Generated/JobOperations.cs#L6378

**Comment by lmazuel** [comment]
Hi @antonydenyer 

Finally we have released the version 2.0.0a1 with update job included:
http://azure-sdk-for-python.readthedocs.org/en/latest/ref/azure.mgmt.scheduler.operations.html#azure.mgmt.scheduler.operations.JobsOperations.create_or_update

It would be awesome if you have the possibility to give us feedback about this new API :)
Thank you!

**Comment by antonydenyer** [comment]
Cool, sadly the project that I was using it on isn't being actively developed. If I get a chance I'll try and take a look in my spare time.

**Comment by lmazuel** [comment]
Ok thank you! Every feedback will be appreciated!
In the meantime, I close this bug for now since the initial problem of having Scheduler support is done.
Please feel free to open a new bug if there is something wrong in the current implementation.
