### ISSUE TITLE
Dataset.Tabular is NOT loading the specified file on storage

### ISSUE THREAD

**Issue by afogarty85** [Azure/azure-sdk-for-python#21419]
- **Package Name**:  azureml.core.
- **Package Version**:  1.34.0
- **Operating System**: W10
- **Python Version**: 3.6.9

**Describe the bug**
When loading a Tabular file, it is not reading the file that is there.

**To Reproduce**

Following this guide on how to use these files:
https://github.com/Azure/MachineLearningNotebooks/blob/122df6e84622136690801685b183af5a04d77dec/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-showcasing-dataset-and-pipelineparameter.ipynb

```
# build data set configurations
stack_rank = Dataset.Tabular.from_delimited_files([(ws.datastores['fs'], '/RAW/Daily/stack_rank_daily.csv')])
stack_rank_param = PipelineParameter(name="stack_rank_param", default_value=stack_rank)
stack_rank_ds_consumption = DatasetConsumptionConfig("stack_rank_dataset", stack_rank_param)

# register it to see its location
stack_rank = stack_rank.register(workspace = ws,
                                 name = 'stack_rank',
                                 description = 'stack_rank data',
                                 create_new_version = True) 

# here is its registration
"registration": {
    "id": "721b9763-b2e5-4524-a620-de3df1ed4403",
    "name": "stack_rank",
   etc

# examine the registration
dataset = Dataset.get_by_id(ws, '721b9763-b2e5-4524-a620-de3df1ed4403')
dataset.to_pandas_dataframe()
# its shape is (1406, 142)
# it SHOULD be (320, 142)
```

**Expected behavior**
I expected the file on storage to load. If I delete the file, AML rightly says that the file has disappeared. If I upload the right file, shape (320, 142), AML will continue to load the one shaped (1406, 142).

**Screenshots**

**Additional context**

**Comment by ynpandey** [comment]
@afogarty85 Does the csv file that you are using contains multiline values? From our documentation:
`By default (support_multi_line=False), all line breaks, including those in quoted field values, will be interpreted as a record break. Reading data this way is faster and more optimized for parallel execution on multiple CPU cores. However, it may result in silently producing more records with misaligned field values. This should be set to True when the delimited files are known to contain quoted line breaks.`

**Comment by afogarty85** [comment]
Thanks for the help!

By doing something like:

```
stack_rank = Dataset.Tabular.from_delimited_files([(ws.datastores['fs'], '/RAW/Daily/stack_rank_daily.csv')], support_multi_line=True)
```

I get another error: `"Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nThe Dataflow produced no records.`

If I set:

```
stack_rank = Dataset.Tabular.from_delimited_files([(ws.datastores['fs'], '/RAW/Daily/stack_rank_daily.csv')], support_multi_line=False)
```

The data populates, but again it is inflated.

**Comment by ynpandey** [comment]
@afogarty85 Is there any way for you to share the data file with us if it does not contain any sensitive information?

**Comment by afogarty85** [comment]
Unfortunately no, could you perhaps generate dummy data in a pandas dataframe that would highlight this: (?)

`all line breaks, including those in quoted field values, will be interpreted as a record break`

From there, investigations could be done.

**Comment by ynpandey** [comment]
@afogarty85 Take this [multiline.csv](https://yogipublicblob.blob.core.windows.net/public/multiline.csv) file as an example.
```python
from azureml.core import Workspace, Dataset, Datastore
ws = Workspace.from_config()
dstore = Datastore.get_default(ws)
path = [(dstore, 'data/multiline.csv')]
dset1 = Dataset.Tabular.from_delimited_files(path) # By default support_multi_line=False
df1 = dset1.to_pandas_dataframe()
df1.shape
```
Output:
```
(6, 3)
```
Now if we execute the following code:
```python
dset2 = Dataset.Tabular.from_delimited_files(path, support_multi_line=True)
df2 = dset2.to_pandas_dataframe()
df2.shape
```
Output:
```
(2, 3)
```

As you can see that the shape of dataframe without multiline support is (6, 3), with multiline support is (2, 3). Setting `support_multi_line=True` parses the file correctly and gives a dataframe of shape (2, 3).

**Comment by afogarty85** [comment]
Thanks for the input -- this definitely appears to be the problem.

Are you aware of anything I can do to speed up training and loading of files?

I am in a situation where I need to specify `support_multi_line=True`, otherwise the shapes are messed up. The consequence of this (`support_multi_line=True`), is that it takes AML approximately 5 minutes to load a dataframe shaped: `(31733, 58)`

**Comment by ynpandey** [comment]
@afogarty85 I am happy that you were able to read the data in correct format.

Regarding the time difference that you are seeing, processing tabular files with multi-line data is slower because data has to be read line-by-line and multiple CPU cores cannot be used to ingest the data in parallel. This is the reason behind slower processing when we set `support_multi_line=True`.

**Comment by afogarty85** [comment]
Thanks @ynpandey !

This makes sense for sure, but this almost certainly has to be an issue. I cannot imagine a scenario where Xeon processors, using a single core, take 5 minutes to load 30k rows at 50 columns. It should take seconds.

**Comment by luigiw** [comment]
Closing legacy issue.

@ynpandey can you help to share a link to the new v2 mltable package?
