### ISSUE TITLE
[Key Vault - Secrets/Certificate/Administration ]"Delete resource group error: (ResourceGroupNotFound) Resource group '***' could not be found" on UsGov and China cloud

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#21414]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the tests about Key Vault Secrets/Certificate/Administration on UsGov and China cloud, it runs failed in section `Delete resource group` and the error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1158099&view=logs&j=45eb1978-d202-5416-4f99-3fa97df74a17&t=43e9ed5c-829b-56c4-c605-5a6269bd74f2&l=12):

![image](https://user-images.githubusercontent.com/57166602/138850084-758acc0d-634b-4916-9e43-2091e20e70b4.png)

**Expected Behavior:**
The resource group can be found and successfully deleted.

@benbp , @jameszliao-msft , @lmazuel , @AlexGhiondea , @chlowell for notification.

**Comment by mccoyp** [comment]
@v-xuto now that https://github.com/Azure/azure-sdk-for-python/pull/21458 has been merged, does this error still come up?

**Comment by v-xuto** [comment]
PR #21458 fixed this issue. I will close this issue.
