### ISSUE TITLE
[CostManagement] Query endpoint filters don't support logical "NOT" despite documentation

### ISSUE THREAD

**Issue by evanzeller-vi** [Azure/azure-sdk-for-python#21430]
According to the documentation [here](https://docs.microsoft.com/en-us/rest/api/cost-management/query/usage-by-external-cloud-provider-type#queryfilter) it seems like logical "NOT" was intended to be supported but the requests still don't work.

**Is your feature request related to a problem? Please describe.**
We need to make CostManagement queries excluding certain dimensions, currently to do so we need to pull all dimensions and create an inverted filter that includes all possible dimension values except the excluded one. This is cumbersome in the context of a larger system that needs to pass around dimensions and filters regularly.

**Describe the solution you'd like**
Would like for the API to support logical "NOT" filter alongside AND and OR for dimensions and tags.

**Describe alternatives you've considered**
Currently using the workaround mentioned above, however this is becoming unsustainable.

**Additional context**
Server returns 500 and provides a request ID for follow-up. It's not clear that "NOT" being unsupported is the reason for the error but I believe it to be so.

**Comment by jochav** [comment]
NOT is currently not supported. We will be updating our documentation to reflect this.

**Comment by omrodrig** [comment]
NOT has been removed from the documentation.

**Comment by mrlepat** [comment]
Documentation updated. Will close the issue
