### ISSUE TITLE
Authorization Role Definition Update The requested resource does not support http method 'PUT': 

### ISSUE THREAD

**Issue by KeeganFlood** [Azure/azure-sdk-for-python#21449]
- **azure.mgmt.authorization**: 
- **azure-mgmt-authorization==2.0.0**: 
- **Amazon Linux 2**:
- **Python 3.8**: 

**Describe the bug**
When utilizing azure-mgmt-authorization AuthorizationManagementClient role_definitions.create_or_update() receiving The requested resource does not support http method 'PUT'. This is for an existing role definition (update). Using RoleDefinition class from azure.mgmt.authorization.v2015_07_01.models. 

**To Reproduce**
1. Create AuthorizationManagementClient:` role_client = AuthorizationManagementClient(<credentials>, subscription_id=<target_subscription>`
2.) Perform Update to Existing Role Definition: `response = role_client.role_definitions.create_or_update(scope=`/subscriptions/{target_subscription}', role_definiton_id=`<role_definition_id>`, role_definition=RoleDefinitionClass)
**Expected behavior**
The existing role definition is successfully updated with new data in RoleDefinitionClass

**Screenshots**

**Additional context**
RoleDefinition class is pulled from azure.mgmt.authorization.v2015_07_01.models. 
CLI command `az role definition update --role-definition <path-to-policy.json>` is working as expected.

**Comment by SaurabhSharma-MSFT** [comment]
@KeeganFlood I have tried performing the update to existing role definitions and able to do the same without any issues.
![image](https://user-images.githubusercontent.com/38112130/139925812-ef59c0c8-ff09-445f-b6fc-e010335ba9a2.png)

**Result:** 
![image](https://user-images.githubusercontent.com/38112130/139924447-2262c140-f570-4d61-b24f-18cee4e471b3.png)

Instead of creating a RoleDefinition class can you try using the below code and if this works -
`SCOPE = "subscriptions/{subscriptionId}".format(
            subscriptionId=subscription_id
        )     

    BODY = {
          "role_name": "testRole",
          "type": "CustomRole",
          "description": "Role description",
          "assignable_scopes": [
            # "/"
            "/" + SCOPE
          ],
          "permissions": [
            {
              "actions": [
                "Microsoft.Compute/*/read"
              ]
            }
          ]
        }

    mgmt_client = AuthorizationManagementClient(credentials,subscription_id)
    role_definition_id = '7b266cd7-0bba-4ae2-8423-90ede5e1e898'

    response = mgmt_client.role_definitions.create_or_update(scope=SCOPE,role_definition=BODY,role_definition_id=role_definition_id) # Add user Access administrator role or owner role to the service principal`

**Comment by KeeganFlood** [comment]
Hello SaurabhSharma-MSFT  - thank you for the response. With some finagling I was able to get it to go through with the following: 
`scope = '/subscriptions/<subscription_id>
role_definition_id = <role_def_id>
role_definition=<BODY>`

First Question: In the documentation, it states a RoleDefinition class/model is a required parameter. Can these classes/models be swapped out for JSON representations of them across the SDK? Or do you need to import the models and create a model object? I've seen differing behavior across the SDK.

![image](https://user-images.githubusercontent.com/80556897/140172768-9875d195-d0a1-453f-b04b-fd156036deed.png)

Second: In terms of the "role_definition_id" parameter. When you do a "get" operation, the ID needed is the full ID with the resource provider. However when doing an "update" you just need the object ID.

For example:
`role_client.role_definitions.get_by_id(role_definition_id="/subscriptions/<subscription_id>/providers/Microsoft.Authorization/roleDefinitions/<role_def_id>")`

vs 
role_client.role_definitions.create_or_update(scope=scope, role_definition_id=""c7ef3cb1-c2b4-4b53-a1e2-111111111111", role_definition=BODY)

Could you explain this distinction. When you look at the at the role in the console the ID listed is the longer one. 
![image](https://user-images.githubusercontent.com/80556897/140173625-2c17470a-ae1c-4190-b160-b3619ed1c02c.png)

Anyway, thanks for the assistance I appreciate your time.

**Comment by SaurabhSharma-MSFT** [comment]
@darshanhs90, @AshishGargMicrosoft - Can you please help here

**Comment by BigCat20196** [comment]
Hi @KeeganFlood, Both `JSON` and `model` formats can be passed as parameters. For those who are not familiar with `JSON` format, we recommend using `model`.

In my opinion, the `full id` is returned when using the `get` operation, and only a part is required when `updating`. This is not a conflict. The `full id` is for the server, while the `partial ID` is more convenient for users. This form is common in Azure.

Here is a sample, fyr:
https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/authorization/manage_role_assignment.py
