### ISSUE TITLE
[Text Analytics]"Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.us), or have expired." in USGOV and China

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#21448]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the test [test_auth.py::TestAuth::test_active_directory_auth](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/tests/test_auth.py#L15), it runs failed and the error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1162494&view=logs&j=eb4e8fab-410d-5462-8da4-6074733a2525&t=763dfd18-348c-56cd-4428-eb65ee2b344d):
![image](https://user-images.githubusercontent.com/57166602/139026215-c8bcb58d-0b0c-4d9d-ab8e-cf575a9c65af.png)

**Error Track:**
Code [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/_configuration.py#L51):
![image](https://user-images.githubusercontent.com/57166602/139028909-fd3fbd31-65e0-4e3f-bb88-a643e1c8039f.png)
The scope is hard code as ' https://cognitiveservices.azure.com/.default' leading to only work well in the public cloud.

**Expected Behavior:**
Add different scopes for different clouds in Text Analytics SDK. 
The value of the scope in different clouds is follow:
Public cloud: https://cognitiveservices.azure.com/.default
UsGov cloud: https://cognitiveservices.azure.us/.default
China cloud: https://cognitiveservices.azure.cn/.default

@benbp, @jameszliao-msft, @lmazuel, @meeraharidasa , @mayurid, @abhahn for notification.

**Comment by v-xuto** [comment]
@kristapratico According to your suggestion, add `client kwargs` in the test ([test_auth.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/tests/test_auth.py#L16)). 
Update the code as follows:
![image](https://user-images.githubusercontent.com/57166602/147813885-b6813c92-4616-4269-bf54-3ad52e973ee3.png)
Then, I run the test locally, still report the same error:
`ClientSecretCredential.get_token failed: Authentication failed: AADSTS500011: The resource principal named https://cognitiveservices.azure.com was not found in the tenant named Microsoft.`

So, is such a modification what you expected? if so, this modification method about `credential_scopes`  is invalid.
Besides, for different cloud tests, how do we pass this `credential_scopes`?

If you have any questions please let me know.

**Comment by kristapratico** [comment]
@v-xuto my bad, I picked a poor example to show where to use the client_kwargs argument. Since we actually create the client in the test itself, we need to pass the credential_scopes as a keyword arg when creating the client, like:

`text_analytics = TextAnalyticsClient(textanalytics_test_endpoint, token, credential_scopes=credential_scopes)`

Since the credential scopes will be different per cloud, we can switch on the AuthorityHost for now like shown here: https://github.com/Azure/azure-sdk-for-python/issues/20648#issuecomment-941208112

However, it would probably make more sense to add an env var per cloud config that specified the default cognitive scope so we could just do something like:

```
credential_scopes = [os.getenv('DEFAULT_CREDENTIAL_SCOPE')]
text_analytics = TextAnalyticsClient(textanalytics_test_endpoint, token, credential_scopes=credential_scopes)
```

@benbp is this something we can add to the EnvironmentVariables for each of the sovereign cloud configs?

**Comment by v-xuto** [comment]
@kristapratico  According to [comments](https://github.com/Azure/azure-sdk-for-python/issues/22287#issuecomment-1004301607),  I will be able to output the variable construction scope by referencing the ARM template of `textAnalyticsEndpointSuffix` and add it to the environment.
Update to:
```
 text_analytics_endpoint_suffix = os.environ.get("TEXTANALYTICS_ENDPOINT_SUFFIX1",".cognitiveservices.azure.com/")
 credential_scopes = ["https://{}.default".format(text_analytics_endpoint_suffix[1:])]
 text_analytics = TextAnalyticsClient(textanalytics_test_endpoint, token, credential_scopes=credential_scope
```

**Comment by kristapratico** [comment]
@v-xuto awesome! let me know if that works for you and if we can close this issue.

**Comment by v-xuto** [comment]
@kristapratico I will close this issue.
