### ISSUE TITLE
Azure function list properties

### ISSUE THREAD

**Issue by reach4bawer** [Azure/azure-sdk-for-python#21451]
I am trying to get the information such as the `App Service Plan` linked to the Azure Function App and settings highlighted under Protocol settings like if the function has HTTP vs HTTPS as highlighted by the screenshot -

![image](https://user-images.githubusercontent.com/52763317/139101703-8fb3ade2-a84d-40b7-9c58-fb85e52a38d0.png)

I have read only access and using `python 3.9` version with `azure-mgmt-web version 5.0.0`. 

I used the following code but didn't get the information highlighted - 

```
mgmt_client = WebSiteManagementClient(credentials, ['Subscription'])
configs = mgmt_client.web_apps.get_configuration(resource_group_name='Resource_Group',
                                                         name='name_of_function').as_dict()
```

is there something different that needs to be done to pull this information.

**Comment by BigCat20196** [comment]
Hi @reach4bawer , thanks for the feedback !

After my investigation, this phenomenon is caused by the use of SDK.

Please change the code as follows：
```
mgmt_client = WebSiteManagementClient(credentials, ['Subscription'])
configs = mgmt_client.web_apps.get(resource_group_name='Resource_Group',
                                                         name='name_of_function').as_dict()
```
Then you can get the results you want.

**Comment by reach4bawer** [comment]
@BigCat20196 Thank you, there are still has few missing details that are not returned , for example, how do I find out the names and the configuration (like trigger, status, Code+Test details, Integration, Function keys) of Function under Function App? Is that part of a different API call or different part of the SDK?

**Comment by reach4bawer** [comment]
Also couldn't find the `inbound address` (IP) for the Azure function app with the SDK using get or get_configuration.

**Comment by BigCat20196** [comment]
@reach4bawer, We can get function through this.
```
func = web_client.web_apps.get_function(resource_group_name=rg_name, name=app_name, function_name=func_name).as_dict()
```
In addition, you can `web_client.web_apps.create_or_update_function_secret()` to change the function keys.

As for the above code + test details, integration seems to have no corresponding API to support.

**Comment by reach4bawer** [comment]
@BigCat20196 I don't want to update or change the function keys, is there no get function for function keys? I have read only role so update or change wouldn't work.

**Comment by BigCat20196** [comment]
@reach4bawer , So `list_function_secrets` might suit you.

```
func =web_client.web_apps.list_function_secrets(resource_group_name=rg_name, name=app_name, function_name=func_name).as_dict()
```

**Comment by reach4bawer** [comment]
> @reach4bawer , So `list_function_secrets` might suit you.
> 
> ```
> func =web_client.web_apps.list_function_secrets(resource_group_name=rg_name, name=app_name, function_name=func_name).as_dict()
> ```
> 

Thank you for this, I will give it a try.

@BigCat20196 any insights on the inbound IP?

> Also couldn't find the `inbound address` (IP) for the Azure function app with the SDK using get or get_configuration.

**Comment by reach4bawer** [comment]
Any way to get `inbound addresses` using the SDK?

![image](https://user-images.githubusercontent.com/52763317/142652412-c35189ca-22eb-4a26-a1cb-a69db15f56a7.png)

**Comment by SaurabhSharma-MSFT** [comment]
@BigCat20196 Can you please help here.

**Comment by BigCat20196** [comment]
Hi @reach4bawer, Sorry for the late reply. It seems that this is a bug defined by the server. Because `inbound_addresses`  is not defined in the [model ](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/CommonDefinitions.json#L2544)causes it to be discarded during deserialization.

Please go [here ](https://github.com/Azure/azure-rest-api-specs/issues)to open a new issue feedback it, thank you!
