### ISSUE TITLE
Network resource provider API version is 8 versions behind the latest stable version

### ISSUE THREAD

**Issue by helderpinto** [Azure/azure-sdk-for-python#21450]
The latest stable REST API version for the Network Resource provider is [2021-05-01](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/network/resource-manager/Microsoft.Network/stable). However, the Python SDK docs have not been updated since the `2020-06-01` version. Why do we have such a disparity, taking into account that the latest version of the [`azure-mgmt-network` package](https://pypi.org/project/azure-mgmt-network/) is already using the most recent Network provider versions? Shouldn't this documentation update process be more streamlined and in sync with the Python SDK and REST API release updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0171c28-cca9-cc6c-cde1-c52cde07ae14
* Version Independent ID: 17a553c5-1036-7938-0f75-8d72835aa28b
* Content: [azure.mgmt.network.NetworkManagementClient class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.networkmanagementclient?view=azure-python#public-ip-addresses)
* Content Source: [docs-ref-autogen/azure-mgmt-network/azure.mgmt.network.NetworkManagementClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-network/azure.mgmt.network.NetworkManagementClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by SaurabhSharma-MSFT** [comment]
@helderpinto We are looking into this and get back to you.

**Comment by lmazuel** [comment]
Latest API has been merged to repo, closing the issue:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/network/azure-mgmt-network/azure/mgmt/network/v2021_05_01
