### ISSUE TITLE
Cannot Import Name 'BlobServiceClient', azure-storage-blob v12.9.0

### ISSUE THREAD

**Issue by yusuf-jkhan1** [Azure/azure-sdk-for-python#21461]
- **azure-storage-blob**
- **12.9.0**: 
- **Ubuntu 20.04.3 LTS (Focal Fossa)**:
- **Python 3.8.10**: 

**Describe the bug**
Latest version of azure-storage-blob does not seem to contain a BlobServiceClient module, although latest documentation, updated on 10/24/21 is referring to it. [See here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python) .

**To Reproduce**
```
from azure.storage.blob import BlobServiceClient

ImportError: cannot import name 'BlobServiceClient' from 'azure.storage.blob' (/databricks/python/lib/python3.8/site-packages/azure/storage/blob/__init__.py)
```

**Additional context**
```
cat /databricks/python/lib/python3.8/site-packages/azure/storage/blob/__init__.py
#Output
# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
# --------------------------------------------------------------------------
from .appendblobservice import AppendBlobService
from .blockblobservice import BlockBlobService
from .models import (
    Container,
    ContainerProperties,
    Blob,
    BlobProperties,
    BlobBlock,
    BlobBlockList,
    PageRange,
    ContentSettings,
    CopyProperties,
    ContainerPermissions,
    BlobPermissions,
    _LeaseActions,
    AppendBlockProperties,
    PageBlobProperties,
    ResourceProperties,
    Include,
    SequenceNumberAction,
    BlockListType,
    PublicAccess,
    BlobPrefix,
    DeleteSnapshot,
)
from .pageblobservice import PageBlobService
```
**Here is the output from pip freeze:**
adal==1.2.7
appdirs==1.4.4
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-common==1.1.27
azure-core==1.19.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-datalake-store==0.0.52
azure-eventgrid==1.3.0
azure-graphrbac==0.40.0
azure-keyvault==1.1.0
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.1.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.6.2
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.4.1
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.6.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.7.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.2.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.7
azure-storage==0.36.0
azure-storage-blob==12.9.0
azure-storage-common==1.4.2
azure-storage-file==1.4.0
azure-storage-queue==1.4.0
backcall==0.2.0
bleach==3.3.0
boto3==1.16.7
botocore==1.19.7
CacheControl==0.12.6
cachy==0.3.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cleo==0.8.1
clikit==0.6.2
crashtest==0.3.1
cryptography==35.0.0
cycler==0.10.0
Cython==0.29.23
dbus-python==1.2.16
decorator==5.0.6
defusedxml==0.7.1
distlib==0.3.2
distro==1.4.0
distro-info===0.23ubuntu1
entrypoints==0.3
facets-overview==1.0.0
filelock==3.0.12
html5lib==1.1
idna==2.10
ipykernel==5.3.4
ipython==7.22.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isodate==0.6.0
jedi==0.17.2
jeepney==0.7.1
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
keyring==21.8.0
kiwisolver==1.3.1
koalas==1.8.1
lockfile==0.12.2
MarkupSafe==1.1.1
matplotlib==3.4.2
mistune==0.8.4
msgpack==1.0.2
msrest==0.6.21
msrestazure==0.6.4
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.3.0
numpy==1.19.2
oauthlib==3.1.1
packaging==20.9
pandas==1.2.4
pandocfilters==1.4.3
parso==0.7.0
pastel==0.2.1
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
pkginfo==1.7.1
plotly==5.1.0
poetry==1.1.11
poetry-core==1.0.7
prometheus-client==0.10.1
prompt-toolkit==3.0.17
protobuf==3.17.2
psycopg2==2.8.5
ptyprocess==0.7.0
pyarrow==4.0.0
pycparser==2.20
Pygments==2.8.1
PyGObject==3.36.0
PyJWT==2.3.0
pylev==1.4.0
pyparsing==2.4.7
pyrsistent==0.17.3
python-apt==2.0.0+ubuntu0.20.4.6
python-dateutil==2.8.1
pytz==2020.5
pyzmq==20.0.0
requests==2.25.1
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
requests-unixsocket==0.2.0
s3transfer==0.3.7
scikit-learn==0.24.1
scipy==1.6.2
seaborn==0.11.1
SecretStorage==3.3.1
Send2Trash==1.5.0
shellingham==1.4.0
six==1.15.0
ssh-import-id==5.10
statsmodels==0.12.2
tenacity==8.0.1
terminado==0.9.4
testpath==0.4.4
threadpoolctl==2.1.0
tomlkit==0.7.2
tornado==6.1
traitlets==5.0.5
unattended-upgrades==0.1
urllib3==1.25.11
virtualenv==20.4.1
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1

**Comment by tasherif-msft** [comment]
Hi @yusuf-jkhan1 have you tried the recommendation @rakshith91 gave? Please let me know

**Comment by yusuf-jkhan1** [comment]
Hi it seems this issue was occurring in azure databricks because the pre-defined cluster environment was still importing the old version. 
In a clean new virtual environment I did not run into this issue any longer.
