### ISSUE TITLE
B2B invitation endpoint SDK

### ISSUE THREAD

**Issue by ThibaultNocchi** [Azure/azure-sdk-for-python#21467]
**Is your feature request related to a problem? Please describe.**
I'd like to invite users to work with my B2B external identity

**Describe the solution you'd like**
Having a function in the SDK to do it.

**Comment by tjprescott** [comment]
@msyyc could you route this to the appropriate folks on the Graph team?

**Comment by lmazuel** [comment]
`azure-graphrbac` is about Azure AD Graph API, which is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60

MS Graph is not an Azure product, so we can't help you on this repo unfortunately, but I would suggest you look into the "microsoftgraph" org on Github, starting here:
https://github.com/microsoftgraph/msgraph-sdk-python-core
