### ISSUE TITLE
How to get a list of virtual machine SKUs ?

### ISSUE THREAD

**Issue by F2EVarMan** [Azure/azure-sdk-for-python#2146]
I want check VM SKU availability.[ create  a zoned linux vm](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-cli-availability-zone). I didn't find how to get that in the Python sdk.

**Comment by lmazuel** [comment]
Sorry for the late answer.
`resource_skus` attribute should be what you want:
https://docs.microsoft.com/en-us/python/api/azure.mgmt.compute.computemanagementclient?view=azure-python

**Comment by lmazuel** [comment]
Closing, since I believe the question is solved. Please comment if not.
Thank you.
