### ISSUE TITLE
Add samples for ClientCertificateCredential

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#21482]
The other 3 primary langs have docs like this:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientCertificateCredentialSamples.md

**Comment by mccoyp** [comment]
This is covered by the [key_vault_cert.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/samples/key_vault_cert.py) sample, but we don't cover rolling certificates. I'll look into adding that to our sample by writing an example custom credential, as other languages do.
