### ISSUE TITLE
Updated list of supported VM-sizes

### ISSUE THREAD

**Issue by Zimmergren** [Azure/azure-sdk-for-python#2150]
Hi,

The list of supported VM-sizes in [this code file](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerservice/azure/mgmt/containerservice/models/container_service_client_enums.py#L21) is a bit outdated. There is for example support for B-series VM's since the end of February. ([Read announcement here](https://azure.microsoft.com/nl-nl/blog/introducing-burstable-vm-support-in-aks/))

If possible, an update to this list would be awesome.

Cheers,
Tobias.

**Comment by F2EVarMan** [comment]
Excuse me，do you know how to get a list of availability zones in those locations where the SKU is available?

**Comment by lmazuel** [comment]
@mboersma I think it's your Swagger? Do you plan to update this list? Thanks!
