### ISSUE TITLE
azure-storage-blob-changefeed 12.0.0b2 not pip installable w/ latest sdk

### ISSUE THREAD

**Issue by Hidendra** [Azure/azure-sdk-for-python#21517]
- **Package Name**: azure-storage-blob-changefeed
- **Package Version**: 12.0.0b2
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.10

**Describe the bug**
`azure-storage-blob-changefeed` errors when installing on pip:

```
ERROR: Cannot install azure-storage-blob-changefeed==12.0.0b2 and azure-storage-blob==12.9.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested azure-storage-blob==12.9.0
    azure-storage-blob-changefeed 12.0.0b2 depends on azure-storage-blob~=12.5.0
```

It appears it was fixed in a Sept 21 2020 commit to use a range instead of pinned version: https://github.com/Azure/azure-sdk-for-python/commit/db635d24a96729a4d979c7b03365b65d270b7a4a#diff-7b60a950cd973ee0eb400b0f2d532400948e2d953a88646942fe68032df5d3eb

So it would be great if we could get a new 12.0.0b3 with the newer setup.py.

I am currently running the change feed package successfully with the latest SDK:

```
azure-core                    1.19.0
azure-identity                1.7.0
azure-keyvault-secrets        4.3.0
azure-storage-blob            12.9.0
azure-storage-blob-changefeed 12.0.0b2
```

It would just be great to be installable with pip w/o a dependency error.

**To Reproduce**
1. Install the latest azure blob sdk, `azure-storage-blob==12.9.0`
2. Attempt to install `azure-storage-blob-changefeed`

**Expected behavior**
Package installs.

**Comment by tjprescott** [comment]
Thanks @Hidendra for your report. @tasherif-msft could you please investigate?

**Comment by tasherif-msft** [comment]
Hi @Hidendra I will look into this and get back to you

**Comment by Hidendra** [comment]
Hi! Wondering if there has been any traction on this @tasherif-msft ?

I want to release a new version of my package internally with changefeed as a requirement and was going to use a direct URL reference for now but unfortunately cannot... It gets rejected by DevOps Artifacts:

```
HTTPError: 400 Bad Request from https://pkgs.dev.azure.com/XXX/XXX/_packaging/XXX/pypi/upload
Bad Request - Packages with direct (URL) references in Requires-Dist are not allowed.
```

so my only hope currently is for a new pre-release version to be cut on pip with the mentioned install_requires change already in master.

Thanks!

**Comment by tasherif-msft** [comment]
Hello @Hidendra I have released a new version https://pypi.org/project/azure-storage-blob-changefeed/
I will close this issue :) let me know if anything else comes up!

**Comment by Hidendra** [comment]
Awesome, thank you!!! Looking good on my end, greatly appreciated.
