### ISSUE TITLE
Broken links for suggester and similarity

### ISSUE THREAD

**Issue by dereklegenzoff** [Azure/azure-sdk-for-python#21536]
The links on this page for suggester and similarity are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4108a354-4c9d-15d4-4439-78e2ac387dca
* Version Independent ID: da05acb7-89a9-2b96-b9bb-7aa352371bd6
* Content: [azure.search.documents.indexes.models.SearchIndex class](https://docs.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.indexes.models.searchindex?view=azure-python)
* Content Source: [docs-ref-autogen/azure-search-documents/azure.search.documents.indexes.models.SearchIndex.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-search-documents/azure.search.documents.indexes.models.SearchIndex.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by tjprescott** [comment]
This is an issue with docs.ms ingestion pipeline because the github.io docs are correct.

**Comment by tjprescott** [comment]
cc/ @danieljurek @scbedd @sima-zhu

**Comment by danieljurek** [comment]
Internal issue filed: https://dev.azure.com/ceapex/Engineering/_workitems/edit/513060

**Comment by kurtzeborn** [comment]
Since the issue in the docs repo has been opened, I'm going to go ahead and close this.  We don't need two issues in two different repos open and tracking this.  A link to the issue opened in the appropriate repo is sufficient.
