### ISSUE TITLE
container.read_item() should return dict[str, Any]

### ISSUE THREAD

**Issue by marcelvb** [Azure/azure-sdk-for-python#21560]
- **Package Name**: azure-cosmos
- **Package Version**: 4.2.0
- **Operating System**: Any
- **Python Version**: 3.8

**Describe the bug**
The type hint for the return type of `read_item()` in `container.py` is `dict[str, str]`. The documentation says it's dict[str, Any] which I think the code should also be.

Code: https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/cosmos/azure-cosmos/azure/cosmos/container.py#L163

Docs: https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/cosmos/azure-cosmos/azure/cosmos/container.py#L175

Other methods also use `dict[str, Any]` for container items. With `dict[str, str]` as a return type you will get type errors when using nesting in json.

**Comment by tjprescott** [comment]
Thank you @marcelvb for reporting this! @Rodrigossz could you take a look?

**Comment by simorenoh** [comment]
Hi @marcelvb, thank you for catching this. You are right - this is a miss on our end. Here is the PR to address this:
https://github.com/Azure/azure-sdk-for-python/pull/21593

Thank you for helping us improve our product!
