### ISSUE TITLE
azureml SDK impose old version of azure-identity

### ISSUE THREAD

**Issue by gdippolito** [Azure/azure-sdk-for-python#21562]
- **Package Name**: azureml-core, azureml-sdk
- **Package Version**:  1.35.0
- **Operating System**: Linux
- **Python Version**: 3.8.12

**Describe the bug**
`azureml-core` does not support `azure-identity>=1.4.1` which is quite old. This is quite annoying for building application that use the same package (`azure-identity`) for different purposes. More recent versions of `azure-identity` have fixed many annoying bugs so using 1.4.1 is just not an option

**To Reproduce**
1. `pip install azureml-sdk==1.35.0 azureml-core==1.35.0 azure-identity==1.7.0`

Results:
```
ERROR: azureml-dataprep 2.23.2 has requirement azure-identity<1.5.0,>=1.2.0, but you'll have azure-identity 1.7.0 which is incompatible.
```

**Expected behavior**
Success.

**Comment by tjprescott** [comment]
Thank you @gdippolito for reporting this issue. @Azure/cxp can you route the correct service team rep?

**Comment by paulshealy1** [comment]
@gdippolito you are installing both `azureml-core` and `azureml-sdk`. Would it work for you to only install `azureml-core`?

**Comment by gdippolito** [comment]
Hi @paulshealy1 thanks for the suggestion. I thought the `azureml-sdk` was required for what I'm doing but effectively I only use `azureml-core` in my job launcher. I had a problem with a different dependency `azure-mgmt-resource` where azureml-core requires it to be <=15.0.0 while that version does not support `azure.identity` and I was relying on that in a different part of the codebase. I think I have managed to workaround it but it would be nice to make all the dependencies aligned. Thanks!

**Comment by paulshealy1** [comment]
Thank you for the feedback!
