### ISSUE TITLE
vmCreationResourceGroup setting of DTL lab gets ignored / reset

### ISSUE THREAD

**Issue by flixman** [Azure/azure-sdk-for-python#21587]
- **Package Name**: azure.mgmt.devtestlabs
- **Package Version**: 9.0.0
- **Operating System**: CentOS 8.4
- **Python Version**: 3.6.8

**Describe the bug**
When getting a lab through DevTestLabsClient.labs.get, the lab does not obtain the vmCreationResourceGroup setting. And, if set after and the DTL gets updated, it gets reset to the default (which makes the whole client unusable).

**To Reproduce**
1. Run the following code, pointing to a DTL that has the vmCreationResourceGroup setting pointing to a non-default location
```python
import os

from azure.identity import DefaultAzureCredential
from azure.mgmt.devtestlabs import DevTestLabsClient

LAB_NAME = 'labname'
AZURE_RG = 'labrg'

dtl_client = DevTestLabsClient(DefaultAzureCredential(), os.environ['AZURE_SUBSCRIPTION_ID'])
dtl = dtl_client.labs.get(AZURE_RG, LAB_NAME, expand='properties($select=vmCreationResourceGroup)')

# upon inspection of dtl.vm_creation_resource_group, it will have come empty, lets proceed resetting it
dtl.vm_creation_resource_group = "<ResourceId of the RG>"

dtl_result = dtl_client.labs.begin_create_or_update(AZURE_RG, LAB_NAME, dtl)
dtl.result.wait()
```
2. Get to the DTL and inspect the property vmCreationResourceGroup, and will be found reset to its default.

**Expected behavior**
The get method of DevTestLabsClient.labs retrieves the vmCreationResourceGroup, and also sets it up.

**Additional context**

**Comment by tjprescott** [comment]
@flixman thanks for opening an issue!

@Azure/cxp can you please route to the DTL service rep?

**Comment by flixman** [comment]
Hi @tanmayeekamath, excuse me for explicitely referencing you: could you/MS share if there is any update on this matter?

**Comment by josegallardo** [comment]
Hi @flixman ,
The Python SDK is using an older version of the DevTest Labs API in which that property is still Read-Only. I'd assume this is because our latest DTL API is still in the process to be released as stable. 
That process will take some time but, in the meantime, as a workaround, you can use directly the DTL 2018-10-15-preview API which allows you to update that same property.
Thanks for reaching out.

**Comment by flixman** [comment]
Hi @josegallardo, I have just tried with that API version, and I am getting the same error :-/.

**Comment by Wzb123456789** [comment]
Hi，@flixman. Thanks for the feedback! 
After investigation, since vm_creation_resource_group is a read-only parameter, vm_creation_resource_group cannot be modified.

**Comment by xiangyan99** [comment]
Since this is defined in the swagger, please open issues in https://github.com/Azure/azure-rest-api-specs repo.
