### ISSUE TITLE
[EventHub] Failed to deploy test resources and an error "Database account creation failed" is reported on China Cloud

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#21583]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the EventHub pipeline on China cloud, it runs failed at section `Deploy test resources` and the error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1178512&view=logs&j=3d64d5b2-eb44-586c-d9c2-694daad88897&t=d049bc04-7605-5e00-4f79-a2d1c7c17699):
![image](https://user-images.githubusercontent.com/57166602/140276709-059564d3-3b07-4d39-8e9e-fc94c0f22c89.png)

**Expected Behavior:**
Deploy test resources successfully on China Cloud.

@benbp , @jameszliao-msft , @lmazuel , @lilyjma , @ramya-rao-a and @annatisch for notification.

**Comment by benbp** [comment]
@v-xuto this is a service capacity issue.. Can you try changing the target region for the China cloud tests?

**Comment by v-xuto** [comment]
@benbp I have updated China location to `chinanorth2`, this issue was resolved. This is the test [result](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1185817&view=results). I will close this issue.
![image](https://user-images.githubusercontent.com/57166602/140902489-715522fc-bc12-4456-8d58-60c4c2707bea.png)
