### ISSUE TITLE
Writing data to linked service AzureSQL database using the python AzureML package does not work

### ISSUE THREAD

**Issue by DaanDuppen** [Azure/azure-sdk-for-python#21584]
- **Package Name**: AzureML
- **Package Version**: 1.34.0
- **Operating System**: MacOs
- **Python Version**: 3.7.11

**Describe the bug**
Writing data to azureSQL database using Dataset.Tabular.from_sql_query() fails with error message:
Cannot load any data from the datastore using the SQL query.

**To Reproduce**
1. Add AzureSQL database to AzureML as datastore
2. Run an insert query using Dataset.Tabular.from_sql_query()

**Expected behavior**
Writing data to database.

**Additional context**
In case the from_sql_query() functionality is only meant for retrieving data from a SQL database, what is the designated way to write data to a database using the azure python sdk?
I know it is possible with pyodbc but doing it through the azure python sdk would be a lot easier and safer.

**Comment by tjprescott** [comment]
@DaanDuppen thank you for your question. @Azure/cxp can you route to the appropriate rep on the Azure ML team?

**Comment by ynpandey** [comment]
@DaanDuppen Currently, `Dataset.Tabular.from_sql_query()` only supports creating a `TabularDataset` by reading data from a SQL database table. Inserting/writing data back is not supported using this API. For [writing the job output data](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-move-data-in-out-of-pipelines) back as a `TabularDataset`, you can use [`OutputFileDatasetConfig`](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.output_dataset_config.outputfiledatasetconfig?view=azure-ml-py) to one of the supported datastores (blob storage, fileshare, adlsgen1, or adlsgen2) and the promote the output to a TabularDataset.

For writing data back to SQL DB, the option that you have mentioned (using `pyodbc`) should work. We are taking note of your feedback for writing back to SQL DB using Python SDK.
