### ISSUE TITLE
Unable to import ArtifactsClient in Synapse Notebook

### ISSUE THREAD

**Issue by nchandhi** [Azure/azure-sdk-for-python#21588]
- **azure.synapse.artifacts**: 
- **latest**: 
- **Any**:
- **3.6**: 

**Describe the bug**
I am trying to use Artifacts sdk from within Synapse Notebook to read details about pipelines and notebooks but it gives a no module error.
Note: I am able to run this code outside Synapse using VS Code and read the artifacts but I need to run this within Synapse.

**To Reproduce**
1.  Try to import the library in a synapse notebook with below line to see the error as shown in screenshot below
from azure.synapse.artifacts import ArtifactsClient

**Expected behavior**
I expect the library to load successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/22228486/140352184-71af3935-8f29-4a48-bf98-6da273f3f7c0.png)

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out to us.

Are you running the notebook in Synapse managed spark pool? If yes, could you check if you added azure.synapse.artifacts in your requirements file? e.g. https://sqlofthenorth.blog/2021/02/26/adding-new-python-libraries-to-azure-synapse-spark-pools/.

**Comment by xiangyan99** [comment]
@nchandhi Thanks for the information.

@idear1203 Is there a way we can check logs to see what happened?

**Comment by idear1203** [comment]
It doesn't look like a SDK issue because @nchandhi can use the SDK in VSCode. @wonner , is this something that you are willing to do some investigation on your side?

**Comment by idear1203** [comment]
@nchandhi could you please verify your package is installed correctly? https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-manage-python-packages#verify-installed-libraries

**Comment by nchandhi** [comment]
Hi @idear1203, Thanks for helping with this. I double checked and the library installation didn't show any errors in logs.

**Comment by nchandhi** [comment]
@idear1203 @xiangyan99, please let me know if you need any more details from me. We are really blocked at this step to continue a current project so looking forward to finding a solution or a work around. I can join a call to debug together if it helps accelerate the process.

**Comment by xiangyan99** [comment]
@nchandhi Can you list all the modules you installed? I will try if I can repro it in my local dev box.
