### ISSUE TITLE
Azure search synonyms mapping issue with word with space in between

### ISSUE THREAD

**Issue by qudiransari** [Azure/azure-sdk-for-python#21585]
Hi Team,
However when i search the words where there is blank in between it not fetching any result whereas for other words in same mapping list its working.

Is that something i am doing wrong ?

Mapping API
`https://XX.search.windows.net/synonymmaps?api-version=2020-06-30
{
    "@odata.context": "https://ss-tsn.search.windows.net/$metadata#synonymmaps",
    "value": [
        {
            "@odata.etag": "\"0x8D99F7C8DBEBBE7\"",
            "name": "synonymcity",
            "format": "solr",
            "synonyms": "NewYork,New York, NYork, NewY => NY",
            "encryptionKey": null
        },
        {
            "@odata.etag": "\"0x8D99EBAD3032C13\"",
            "name": "synonymspecialization",
            "format": "solr",
            "synonyms": "construction,building, real estate",
            "encryptionKey": null
        }
    ]
}

Search API which return nothing when searching New York

`
POST https://XX.search.windows.net/indexes/XX/docs/search?api-version=2020-06-30&queryType=simple
{
    "search": "New York",
    "searchMode": "all",
    "queryType": "simple",
    "select": "",
    "searchFields": "city",
    "filter": "",
    "facets": [ "category","county"],
    "orderby": "",
    "count": true
}`

**Comment by tjprescott** [comment]
Thanks @qudiransari for your report. I will investigate and get back to you.

**Comment by qudiransari** [comment]
Could you please suggest is it something wrong in the query or its a bug?

**Comment by tjprescott** [comment]
It is not clear to me--are you using the REST API directly, or the Python library?

**Comment by tjprescott** [comment]
Closing this issue as stale. If you are still experiencing this, please reopen it.
