### ISSUE TITLE
[BUG Bash] Azure KeyVault SDK uses hardcoded version of _models 

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#21623]
**Describe the bug**
Azure KeyvAult SDKs reference specific API version (7.1) in its code: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py#L7

It makes it impossible to use scripts that trim size of Azure SDKs and it also violates established patterns of dynamic versions usage.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py#L7

**Comment by mccoyp** [comment]
Hi @logachev, thank you for opening this issue! I'll add this item to our upcoming milestone.
