### ISSUE TITLE
support to create/update VpnSiteLinksOperations

### ISSUE THREAD

**Issue by Ananthram** [Azure/azure-sdk-for-python#21635]
right now only get() method is supported, need a method to update bgp and ipsec properties

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by RAY-316** [comment]
@Ananthram  The python SDK is generated according to swagger, so this issue may be better mentioned in https://github.com/Azure/azure-rest-api-specs

**Comment by RAY-316** [comment]
hi @Ananthram Can you provide a more detailed description of the package, such as the name and version of it.

**Comment by Ananthram** [comment]
This is a request to add API support to create/update [VpnSiteLinksOperations ](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2019_11_01.operations.vpnsitelinksoperations?view=azure-python)

To do the following action via API
![image](https://user-images.githubusercontent.com/3910231/147951205-34a81e95-aead-42f9-bceb-299f240bf818.png)

Related issue on the azure-cli-extensions repo: https://github.com/Azure/azure-cli-extensions/issues/4074

**Comment by BigCat20196** [comment]
Hi @Ananthram, thanks for your feedback! There is no denying that it is a good function. However, Python SDK is generated based on [rest](https://github.com/Azure/azure-rest-api-specs/). Please go [here ](https://github.com/Azure/azure-rest-api-specs/issues)to open a new issue. Once it supports this operation, the SDK will release a new version to synchronize it. Thanks!
