### ISSUE TITLE
'MsiCredential' object has no attribute 'signed_session'

### ISSUE THREAD

**Issue by moritzxbe** [Azure/azure-sdk-for-python#21642]
- **Package Name**: azure-identity, azure-mgmt-subscription
- **Package Version**: 1.7.0, 1.0.0
- **Operating System**: Windows
- **Python Version**: 3

**Describe the bug**
Since our function has often failed with the error "RuntimeError: MSI: Failed to retrieve a token" with the msrestazure package, we decided to use the azure-identity package. Unfortunately there we experience a different error "'MsiCredential' object has no attribute 'signed_session'". Is there any offical way to use the SubscriptionClient with ManagedIdentityCredential for AZURE_PUBLIC_CLOUD as well as AZURE_CHINA_CLOUD?

**Comment by xiangyan99** [comment]
Thanks for your feedback.

We have the guide for migrating to azure-identity from azure-common (https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md). Could you check if this helps?

**Comment by xiangyan99** [comment]
Hi @moritzxbe Thanks for the information.

I tried the code:

    from azure.identity import ManagedIdentityCredential
    from azure.mgmt.subscription import SubscriptionClient
    credentials = ManagedIdentityCredential()
    client = SubscriptionClient(credentials)
and it worked.

Can you try if this also works for you?

@msyyc Do you know if we want to use the China cloud, how to create a SubscriptionClient?

**Comment by BigCat20196** [comment]
hi @moritzxbe thanks for the feedback !

Track2 and track1 have slightly different methods for identity. 
You need to store your credentials an environment variables. For example, in Linux based OS, you can do
```
export AZURE_TENANT_ID="xxx"
export AZURE_CLIENT_ID="xxx"
export AZURE_CLIENT_SECRET="xxx"
export SUBSCRIPTION_ID="xxx"
```

And it no longer needs to set `signed_session`, this is a breaking change.

Please kindly let us know if it solves the issue.
