### ISSUE TITLE
Typo in parameters

### ISSUE THREAD

**Issue by mmasiuk** [Azure/azure-sdk-for-python#21665]
Hello,
I just found out that there is most likely typo in this Class.

Documentation stated that constructor should be as follow:
AuthorizationManagementClient(credential, subscription_id, base_url=None, **kwargs)

but inside the Class .py file there is:
def __init__(
            self, credential**s**, subscription_id, base_url=None):

Therefore once using "credential" without "s" it resulted with below error:
TypeError: __init__() got an unexpected keyword argument 'credential'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42fc52d3-3c75-5b0d-8b4c-206266c29184
* Version Independent ID: 1b6ad925-5570-92e7-60d1-2479ca0edb8e
* Content: [azure.mgmt.authorization.v2020_04_01_preview.AuthorizationManagementClient class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2020_04_01_preview.authorizationmanagementclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-authorization/azure.mgmt.authorization.v2020_04_01_preview.AuthorizationManagementClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-authorization/azure.mgmt.authorization.v2020_04_01_preview.AuthorizationManagementClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by MughundhanRaveendran-MSFT** [comment]
@mmasiuk , Thanks for the feedback. I am trying to reproduce this issue at my end. Once I am able to repro, I will make the necessary changes to SDK. 

I will keep you posted on this thread.

**Comment by MughundhanRaveendran-MSFT** [comment]
@mmasiuk , Doesnt seem like an issue. Inside the _authorization_management_client.py file, it is mentioned as credential , please check below

        credential: "AsyncTokenCredential",

https://github.com/Azure/azure-sdk-for-python/blob/98a07a276e63fc8708aabbe5bd4081b42b04daba/sdk/authorization/azure-mgmt-authorization/azure/mgmt/authorization/aio/_authorization_management_client.py#L67

**Comment by lmazuel** [comment]
It has been renamed `credential` in the first stable release 1.0.0, but indeed all old versions in 0.x were using `credentials`. The latest package on PyPI and the doc are now in sync, so closing the issue. Thanks!
