### ISSUE TITLE
Documentation fix: Expected type 'TokenCredential', got 'UserPassCredentials' instead

### ISSUE THREAD

**Issue by silhano** [Azure/azure-sdk-for-python#21664]
In azure-mgmt-dns version  8.0.0 functionality changed. Now is UserPassCredentials invalid and module required TokenCredential. 
Any example of this? I can find only old documentation: https://docs.microsoft.com/en-us/python/api/overview/azure/dns?view=azure-python

I tried multiple ways, but without any success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25324532-1497-f9ba-6711-c7dadd131507
* Version Independent ID: 4747f7f5-7f90-2c75-93bf-adaba0a7c207
* Content: [Azure DNS libraries for python](https://docs.microsoft.com/en-us/python/api/overview/azure/dns?view=azure-python)
* Content Source: [docs-ref-services/latest/dns.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/dns.md)
* Service: **multiple**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by PramodValavala-MSFT** [comment]
@silhano The newer SDK use the `azure.identity` module which you could read more about in the [authentication docs](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?view=azure-python).

Do note that using username/password is not recommended and has some limitations since it's not interactive as mentioned [here](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-user-credentials?view=azure-python#authentication-with-a-username-and-password). Refer the linked doc for more information on the different credential classes available.

The snippet in the docs should be something like this instead. We will work up a PR to update the same.
```python 
from azure.mgmt.dns import DnsManagementClient
from azure.identity import DefaultAzureCredential

# Replace this with your subscription id
subscription_id = '33333333-3333-3333-3333-333333333333'

# See above for details on creating different types of AAD credentials
credential = DefaultAzureCredential()

dns_client = DnsManagementClient(
	credential,
	subscription_id
)
```

**Comment by silhano** [comment]
Thank you for solution, but ... I can't use MSI because I am calling DNS zone in different tenant (different AAD). Is there any solution where I can use password like in past versions?

I tried this, but is NOT working ('UsernamePasswordCredential' object has no attribute 'signed_session'):
`
from azure.mgmt.dns import DnsManagementClient
from azure.identity import UsernamePasswordCredential

# Replace this with your subscription id
subscription_id = '33333333-3333-3333-3333-333333333333'

credentials = UsernamePasswordCredential(client_id=xxx, tenant_id=xxx, username=xxx, password=xxx)

dns_client = DnsManagementClient(
	credential,
	subscription_id
)
`

**Comment by PramodValavala-MSFT** [comment]
@silhano You could [authenticate with service principals](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-service-principals?view=azure-python) instead. This is like a username/password but for non-interactive clients. The Client Secret here should be secured like a password.

**Comment by silhano** [comment]
I tried your way and migrated DNS zone to same tenant, but I am still getting error:
```'DefaultAzureCredential' object has no attribute 'signed_session'```
```
from azure.mgmt.dns import DnsManagementClient
from azure.identity import DefaultAzureCredential

subscription_id = 'xxx-xxx-xxx-xxx'

credential = DefaultAzureCredential()
dns_client = DnsManagementClient(credential,subscription_id)
```

**Comment by silhano** [comment]
It's working there was Azure issue with permission. Thank you for solution.
