### ISSUE TITLE
ErrorCode:AuthorizationPermissionMismatch when using get_blob_tags() method.

### ISSUE THREAD

**Issue by LazzariPaolo** [Azure/azure-sdk-for-python#21668]
I upgraded `azure-storage-blob` because I need to use the [get_blob_tags()](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#get-blob-tags---kwargs-) method, but unsurprisingly something went wrong.
```bash
$ pip freeze | grep 'azure-storage-blob'
azure-storage-blob==12.4.0
```

Here's how I create the BlobClient:

```python
from azure.storage.blob import BlobClient
blob = BlobClient(...)
```

this command:

```python
blob.get_blob_properties()
```

works well (as it used to), but this:

```python
blob.get_blob_tags()
```

throws:

File "C:\Users\paolo\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.
RequestId:xxx
Time:2021-11-09T15:35:07.7037425Z
ErrorCode:AuthorizationPermissionMismatch
Error:None

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by amishra-dev** [comment]
Can you please look at https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#setting-blob-index-tags
Its not clear which auth type you are using but Tags requires special permissions if you are using SAS.

**Comment by tasherif-msft** [comment]
@LazzariPaolo let us know if your issue is resolved.

**Comment by LazzariPaolo** [comment]
Apologies for the late response. 
This is how I'm building the `BlobClient` object:

```python
signature_container = generate_container_sas(
            account_name=subscription_client.account_name,  # name of storage account
            account_key=storage_account_key,  # storage account key
            container_name=container_name,  # name of container
            permission=AccountSasPermissions(read=True, list=True),
            expiry=expiry,  # VHD sas valid for 7 days.
            start=start,  # Set start date to yesterday.
        )

source_blob = BlobClient(
            subscription_client.url,
            container_name=path_vhd,
            blob_name=vhd_name,
            credential=signature_container,
)
```
which permissions do I need to add to the `AccountSasPermissions` call? @amishra-dev

**Comment by LazzariPaolo** [comment]
Ok, by looking at this documentation page:
https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.accountsaspermissions?view=azure-python

I can see that there is an explicit permission for tags.

The following works:

```python
signature_container = generate_container_sas(
            account_name=subscription_client.account_name,  # name of storage account
            account_key=storage_account_key,  # storage account key
            container_name=container_name,  # name of container
            permission=AccountSasPermissions(read=True, list=True, tag=True),
            expiry=expiry,  # VHD sas valid for 7 days.
            start=start,  # Set start date to yesterday.
        )

source_blob = BlobClient(
            subscription_client.url,
            container_name=path_vhd,
            blob_name=vhd_name,
            credential=signature_container,
)
```

a bit of a weird decision to have `tag` as a standalone permission. I assumed, and I imagine others will too, that it would fall under `list` (for getting them) and under `create` (for crating them)
