### ISSUE TITLE
ImportError: No module named concurrent.futures

### ISSUE THREAD

**Issue by TheRainManPY** [Azure/azure-sdk-for-python#2166]
if max_connections > 1:
        import concurrent.futures
        from threading import BoundedSemaphore

python: 2.7
azure-common: 1.1.8
azure-storage: 0.36.0

**Comment by lmazuel** [comment]
Are you implying that the SDK has not a correct set of dependencies? Where the snippet of code you mention is coming from?
Thanks,

**Comment by TheRainManPY** [comment]
concurrent.futures in python3, python2 need pip install futures

**Comment by lmazuel** [comment]
Note that you didn't answer my question at all :)
