### ISSUE TITLE
[BUG Bash] Azure Cli and Azure ML SDK are incompatible.

### ISSUE THREAD

**Issue by Katzmann1983** [Azure/azure-sdk-for-python#21690]
Azure Cli and Azure ML SDK are incompatible. The CLI and ML SDK cannot be both used at the same time from the same cli.

**To Reproduce**
Try to install both in the latest azure-cli container:
docker run -it mcr.microsoft.com/azure-cli
pip install azureml-sdk azure-cli

**Expected behavior**
Both can be used in the same environment.

**Setup**
 - Python 3.9.6
 - azureml-sdk>=1.36.0
 - azure-cli>=2.30.0

**Comment by harneetvirk** [comment]
The compatibility issue between azure cli and azureml-sdk  is because of lack of support for MSAL authentication in azureml-sdk. We are actively working on migrating from ADAL to MSAL authentication in azureml.
