### ISSUE TITLE
Package azureml-* for conda-forge?

### ISSUE THREAD

**Issue by h-vetinari** [Azure/azure-sdk-for-python#21713]
Hey all

I've recently become involved with a project that needs `azureml-defaults`, and it's a bit of a pain to use well in a conda-environment, because of some very specific version pinnings & ranges, and pip just trampling over the conda-environment (uninstalling package versions it doesn't like), potentially breaking the environment.

Right now, to avoid such collisions - i.e. to get to a point where conda installs as many packages as possible (with only those not packaged for conda-forge yet coming from pip) - takes a bunch of painful iteration, and it would be cool to just avoid that by having the azureml-packages in conda-forge.

I haven't found any sources for azureml-defaults, so I'm asking here first (hoping it's the right issue tracker) if this is desired at all? I'm experienced in packaging things for conda-forge, so that wouldn't be a huge issue, but it (normally) depends on availability of the sources.

There are rare cases for which conda-forge will consider binary repackaging, but even in those cases, we'd need the dependency metadata in a reasonably accessible form. It's possible to reverse-engineer this from observing what `pip install azureml-defaults` does, but that's not scalable.

I still did that as a one-time exercise (tf-addons is superfluous for this argument, but I don't want to redo this), and below is the outcome. Everything between the comment after `tqdm` and the `pip`-section is coming in as a dependency of `azureml-defaults=1.36.0` (or `tf-addons`). It's very likely that I made minor mistakes (and I left out lower bounds completely), but just to show the principle.

<details>
<summary>Sample <code>env.yml</code></summary>

```
name: mlflow-env
channels:
- conda-forge
- defaults  # only necessary for tensorflow on windows
dependencies:
- python =3.8
- pip
- mlflow
- numpy
- scikit-learn
- tqdm
- tensorflow =2.6
# avoid pip (un)installing packages unnecessarily
- adal <=1.2.7
- applicationinsights
- azure-core <2
- azure-graphrbac <1
- azure-identity =1.7.0
- azure-mgmt-authorization <1
- azure-mgmt-containerregistry
- azure-mgmt-keyvault <10
- azure-mgmt-resource <15
- azure-mgmt-storage <16
- backports.tempfile
- cloudpickle <2
- cryptography <4
- configparser =3.7.4
- contextlib2
- distro
- flask =1.0.3
- fusepy <4
- isodate
- jeepney
- jmespath <1
- jsonpickle <3
- msal_extensions ~=0.3.0
- ndg-httpsclient <=0.5.1
- pathspec <1
- portalocker ~=1.6
- psutil =5.8.0
- pyarrow <4
- pyopenssl <21
- typeguard
- wrapt <=1.12.1
- pip:
  - azureml-defaults==1.36.*
  - tensorflow-addons==0.14.*
```

</details>

Xref: #20339 #19960

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by h-vetinari** [comment]
Thanks for the quick responses! Just to clarify, it's not necessary that the azure team does the packaging of azureml for conda-forge (though co-maintainership would be welcome!) - it's simply about the fact whether this would be desirable for azureml, and thus whether (ideally) the sources can be made publically available (or at least the dependency metadata).

**Comment by xiangyan99** [comment]
@azureml-github We have our own repo https://anaconda.org/microsoft for Microsoft conda packages. Feel free to talk to me if you need help.

**Comment by luigiw** [comment]
Closing legacy issue. @h-vetinari please create a new issue if you have the same ask for AzureML SDK v2 packages.

https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2
