### ISSUE TITLE
Support Document Patching in CosmosDB SDK

### ISSUE THREAD

**Issue by m-credera** [Azure/azure-sdk-for-python#21722]
CosmosDB document patching was released to GA on 11/2/2021. Support for this in the Python SDK would be a huge RU and time saver from having to use custom stored procedures that achieve similar functionality.

https://devblogs.microsoft.com/cosmosdb/partial-document-update-ga/

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kushagraThapar** [comment]
@gahl-levy - can you please take a look at this feature reqeust?

**Comment by AbhinavDAIICT** [comment]
This is under development and we are aiming to release it by July'23

**Comment by simorenoh** [comment]
Version 4.4.0b1 is out and has this functionality, thank you! https://pypi.org/project/azure-cosmos/4.4.0b1/
