### ISSUE TITLE
[Azure Identity Python] Getting http status details from azure identity even not mentioning (logging_enable=True)

### ISSUE THREAD

**Issue by syamchanakya** [Azure/azure-sdk-for-python#21735]
I am using azure-identity version 1.7.1 to access the azure token using python 3.9.0. When I am running the code through VS code/Pycharm, I am getting HTTP status details for each run. If 1000 resources are in a loop, I will get 1000 HTTP request status in the terminal. It makes it difficult to find the print() items in the code.  The HTTP status code is shown in the figure.
![image](https://user-images.githubusercontent.com/36161380/141424571-d56e1d8a-a7eb-4f46-8c90-068bb337d11a.png)

In the document, (logging_enable=True) can use for getting the request status. and the default will be false.

Please help me to solve the issue.

**Comment by BigCat20196** [comment]
Hi @syamchanakya, thanks for your feedback! 

Could you share the code and more detailed information? This will help us solve the problem faster.
