### ISSUE TITLE
`automation_generate.sh` script is intended for management plane but fails data plane CI

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#21737]
The script `automation_generate.sh` is intended to check management plane generation, but it also runs in the azure-rest-api-specs repo when changes are made exclusively to data-plane specs, resulting in false-alarm failing CI builds.

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/22011 fix the issue
