### ISSUE TITLE
Want to Know field.confidence and form_type_confidence

### ISSUE THREAD

**Issue by bparikh99** [Azure/azure-sdk-for-python#21734]
I have multiple models and running on pdf page by page each model is finding something on page but still field.confidence is always around 0.9 and form type confidence for correct model is also not accurate it is changing based on PDF's sometimes it is 0.7 or less than that

I am currently using Latest package with python 3.7 on windows 10 and I have trained custom models in FOTT Tool can anyone explain how can i restrict to get correct output instead of getting random values from different models

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you tell us which library are you using? And if possible, which version?

Thank you.

**Comment by bparikh99** [comment]
Currently I am using library azure-ai-formrecognizer latest version 3.1.2

**Comment by kristapratico** [comment]
@bparikh99 a few questions:

Are you using a different custom model per PDF page or is this a composed model? 
How many documents have you labeled/trained in the FOTT tool? The more documents you label and train with, the better the confidence and accuracy of the fields returned.

Also I'm sorry but I'm not sure what you mean by "restrict to get correct output instead of getting random values from different models". Is your goal to get higher levels of field confidence and form_type_confidence?

Also adding @catalinaperalta to help with this question.

**Comment by bparikh99** [comment]
Yes I am using custom models in PDF's and also for some model it has 5 pages to maximum 10-15 pages in training but also one question In FOTT Model Field confidence and docTypeConfidence is different from code also it's varying in different models

**Comment by catalinaperalta** [comment]
@bparikh99 this seems to be a training issue, adding @sandeepparab from the service side to help answer training related questions about how to get a higher confidence for models.

 > but also one question In FOTT Model Field confidence and docTypeConfidence is different from code also it's varying in different models

I'm curious what you mean about these being different? Where are you seeing the difference? Thanks!

**Comment by bparikh99** [comment]
Let's take a example I have analyze one page in FOTT model and it is giving high form type confidence and field confidence around 99.5 % for correct page but in my code form type confidence for correct page is not close to 99.5% for some models correct page is taking form type confidence around 30-50%

**Comment by catalinaperalta** [comment]
Hi @bparikh99! Are you sending the same document to multiple models? I've talked to some people on the service side about this, if this is your scenario, then it would be best to use a composed model and let the service determine the model that is the best fit for the document you sent. If that is the case then there would be no need for you to be checking the confidence scores to determine the right model, just use the composed model with the trained models that you wish to check the document against.
