### ISSUE TITLE
`AzureMonitorTraceExporter` exports spans, but drops their events

### ISSUE THREAD

**Issue by ranweiler** [Azure/azure-sdk-for-python#21747]
- **Package Name**: `azure-monitor-opentelemetry-exporter`
- **Package Version**: 1.0.0b5
- **Operating System**: Linux
- **Python Version**: 3.7.5

**Describe the bug**
`AzureMonitorTraceExporter` does not submit events that belong to a span.

**To Reproduce**
Here is a small script that repros:
```python
from azure.monitor.opentelemetry.exporter import AzureMonitorTraceExporter
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

conn_str = "<REDACTED>"
exporter = AzureMonitorTraceExporter.from_connection_string(conn_str=conn_str)
processor = BatchSpanProcessor(exporter)
provider = TracerProvider()
provider.add_span_processor(processor)
trace.set_tracer_provider(provider)
tracer = trace.get_tracer(__name__)

if __name__ == "__main__":
    with tracer.start_as_current_span("my_span"):    
        trace.get_current_span().add_event("my_event_1")
        trace.get_current_span().add_event("my_event_2")        
```

**Expected behavior**
Spans should viewable in Application Insights, such as in the Transaction Search.
Events should also be viewable, and linked to their containing span.
In the above example, `my_span` should contain two events (`my_event_1`, `my_event_2`).

**Screenshots**
The Transaction Timeline View, where I would expect to see a "2 events" near the bottom, and the same events in the list of all telemetry items:
![image](https://user-images.githubusercontent.com/515835/141600171-570f4b6a-eeec-49a2-ab86-d43188df1346.png)

**Additional context**
I can observe that the events are being attached to the span, by using the `ConsoleSpanExporter`:
```
{
    "name": "my_span",
    "context": {
        "trace_id": "0xaec2c256b1821094ca71de2041dfb05c",
        "span_id": "0x31c1d7134ba8654b",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2021-11-13T01:11:55.745691Z",
    "end_time": "2021-11-13T01:11:55.745772Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [
        {
            "name": "my_event_1",
            "timestamp": "2021-11-13T01:11:55.745747Z",
            "attributes": {}
        },
        {
            "name": "my_event_2",
            "timestamp": "2021-11-13T01:11:55.745761Z",
            "attributes": {}
        }
    ],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.7.1",
        "service.name": "unknown_service"
    }
}
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by lzchen** [comment]
@ranweiler 
This feature is not supported yet. Thanks for reporting. We will update this issue once the feature has been implemented.

**Comment by ranweiler** [comment]
Thanks @lzchen, that confirms my reading of the exporter code.

1. Is there a roadmap or timeline for this feature work?
2. How do you plan on mapping OpenTelemetry Events to the App Insights data model? With this be user-configurable?
3. Do you plan on supporting [OpenTelemetry Logging](https://opentelemetry.io/status/#logging), once that API has stabilized?

**Comment by lzchen** [comment]
@ranweiler 

1. Not as of today.
2. This is being discussed [here](https://github.com/microsoft/common-schema/issues/217)
3. Yes, there will be an exporter to send log telemetry generated from OpenTelemetry Logging to App Insights sometime in the future. OpenTelemetry Python has already released an experimental logging SDK (https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.7.1) if you'd like to take a look.

**Comment by lzchen** [comment]
Update on this issue here.

Span events will be mapped to `trace` telemetry unless if the event is an `exception`, in which case it will be mapped to `exception` in app insights.
