### ISSUE TITLE
Model.get_model_path() shouldn't cache models at a relative path from cwd

### ISSUE THREAD

**Issue by janluke** [Azure/azure-sdk-for-python#21740]
Two requests:
- It should be possible to specify a `cache_dir`
- the default cache should be at a fixed path system-wide, not at a relative path from the current working directory. I want to use the cache regardless of my current working directory.

**Comment by swathipil** [comment]
Hi @janluke - Would you be able to specify the SDK that has this issue?

**Comment by janluke** [comment]
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model(class)?view=azure-ml-py

**Comment by swathipil** [comment]
@janluke - Thanks! Directing this to the right people.

**Comment by luigiw** [comment]
Closing legacy issue.

Please consider upgrading to AzureML v2 CLI/SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2
