### ISSUE TITLE
Return code and HTTP errors in Event Grid client

### ISSUE THREAD

**Issue by edoboker** [Azure/azure-sdk-for-python#21748]
Hi,

I was wondering why both sync and async methods of 'send' do not return standard HTTP errors and responses. It would immensely help when trying to handle 429 or 413 (rate too high and message too large). Currently, my only way of knowing if send actions have failed is to check the logs of the event grid of shift to other SDKs (which have their own issues).

I believe it has to do with [this ](https://github.com/Azure/azure-sdk-for-python/blob/fe9b0f8c254a26464e3acabf72d69b4724dd070e/sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py#L204) line, which does not return the HTTP response of the underlying azure.core._pipeline_client (which in its turn, [does](https://github.com/Azure/azure-sdk-for-python/blob/878a12ebb8911a40017228327172b3dcfc85b6e7/sdk/core/azure-core/azure/core/_pipeline_client.py#L200) return an HTTP response. 

Am I mistaken or missing anything about error handling in this SDK? I could not find any exception handling in the code as well (which is the way they've implemented it in the Golang SDK, I believe), which made me wonder if any error handling mechanism exists at all...

**Comment by swathipil** [comment]
@edoboker Thanks for the question! Routing this to people who can answer!

**Comment by rakshith91** [comment]
Hi @edoboker 
Thanks for the issue. The reason EG does not return anything here is because the service itself does not return a body.

You can always use a `raw_response_hook` to get the status code.

Define a callback method like:
```
def callback(response):
    print(response.http_response.status_code)
```

and pass it as `raw_response_hook` in the send method
```
client.send([
   events,
    raw_response_hook=callback
)
```

**Comment by edoboker** [comment]
Thanks for the reply! I think it would be great if this could be added to the documentation as well, being such an important feature.
Just out of curiosity - why not return an HTTP response without a body then? The status code is still meaningful... In addition - I can see in other SDKs and when accessing the service directly, I can see HTTP errors body received from the service itself, such as:
```
{{
    "error": {
        "code": "RequestEntityTooLarge",
        "message": "The maximum size for the JSON content (1049600) has been exceeded. Report '5f11aac2-8b20-41c2-bce4-5fe6be317e33:1:11/16/2021 12:15:17 PM (UTC)' to our forums for assistance or raise a support ticket.",
        "details": [{
            "code": "PayloadTooLarge",
            "message": "The maximum size for the JSON content (1049600) has been exceeded. Report '5f11aac2-8b20-41c2-bce4-5fe6be317e33:1:11/16/2021 12:15:17 PM (UTC)' to our forums for assistance or raise a support ticket."
    }]
  }
}}

```

From the Golang SDK. Is this not parseable in Python?

**Comment by rakshith91** [comment]
@edoboker  I will definitely improve the documentation

As for changing the response now, it would unfortunately be a breaking change and cannot be done.

**Comment by rakshith91** [comment]
Keeping this issue open to document raw_response_hook

**Comment by edoboker** [comment]
@rakshith91 just to make clear - you're saying that it's possible to get the HTTP response from the service, but it would be a breaking change in the SDK?

**Comment by rakshith91** [comment]
@edoboker We were looking into this - I think you have a fair request - pushing a bug fix here in this PR https://github.com/Azure/azure-sdk-for-python/pull/21790

Will hopefully get it released by end of this week. Thanks a lot for reporting this :)

**Comment by rakshith91** [comment]
@edoboker We have released a bug fix to raise on any error - Thanks again for the issue!! https://pypi.org/project/azure-eventgrid/4.7.1/
