### ISSUE TITLE
Feature: add progress callbacks for methods that download models

### ISSUE THREAD

**Issue by janluke** [Azure/azure-sdk-for-python#21741]
**Is your feature request related to a problem? Please describe.**
The problem is poor user experience when downloading models with `Model.get_model_path` or `Model.download`. None of these methods provide any feedback at all nor expose argument that allow for such feedback to be implemented by the developer.

**Describe the solution you'd like**
Expose arguments to hook in the download process. There are multiple possible solutions:
- expose a single `progress_callback(current, total)` where `total` and `current` refers to the entire model folder, not just a single file.
- expose two callbacks, one for logging the number of files that were downloaded and one for the current file being downloaded.

**Comment by swathipil** [comment]
Hi @janluke - Would you be able to specify the SDK that you are referring to in this feature request?
(I'm assuming that it is the same as #21740.)

**Comment by janluke** [comment]
https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model(class)?view=azure-ml-py

**Comment by janluke** [comment]
Is `azureml` closed-source?

**Comment by luigiw** [comment]
Closing legacy issue. @janluke AzureML SDK v2 is open source. Please create a different issue if you have the same ask for v2 Python SDK.

Please consider upgrading to AzureML v2 CLI/SDK. https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2

**Comment by janluke** [comment]
Isn't `Model` still part of the Python SDK for v2?

**Comment by janluke** [comment]
Okay, I guess in v2 you use the `Model` class from `azure.ai.ml`: https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.model?view=azure-python
