### ISSUE TITLE
[storage-blob] Add copy & sync download for folders

### ISSUE THREAD

**Issue by dreamflasher** [Azure/azure-sdk-for-python#21753]
**Is your feature request related to a problem? Please describe.**
Usually I want to download a folder and not a single file, currently I need to write my own code for that.

**Describe the solution you'd like**
Implement https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync sync, as well as copy functionality in the azure-storage-blob python API.

**Describe alternatives you've considered**
I implemented it myself, as did likely many people. I am happy to provide a PR, if you would consider merging it?

**Comment by swathipil** [comment]
@dreamflasher Thanks for your feedback! We'll address it asap!

**Comment by amishra-dev** [comment]
Hi @dreamflasher (Marcel), 
we do want to add support for upload of directories across all our SDKs and we are working on a design for it. We want to keep all our SDKs in sync, hence the API design has to take other languages into account. 
It would be great if you could send a PR to create a new sample and not update the SDK API signatures. Would that be ok with you? We can take your sample into consideration when making the change for python.

We do really appreciate the offer.
Thanks
Ashish
