### ISSUE TITLE
[ServiceBus] Stress test onboarding

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#21765]
after finishing up the issue: https://github.com/Azure/azure-sdk-for-python/issues/21565

get other python messaging crew onboard with the stress test project

**Comment by yunhaoling** [comment]
- stress test scenarios
  - send and receive large messages

**Comment by yunhaoling** [comment]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/485/Stress-test-checklist
https://github.com/Azure/azure-sdk-tools/blob/main/tools/stress-cluster/chaos/README.md
https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/servicebus/service-bus/test/stress
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/eventhub/azure-eventhub/stress

**Comment by swathipil** [comment]
Following Richard's PR in Go, we should also test against ServicePrincipal/AAD and not just with connection strings: https://github.com/Azure/azure-sdk-for-go/blob/1a459bfba83ccae3e4db2982e6c8d5dc14ee9c54/sdk/messaging/azservicebus/internal/stress/stress-test-resources.bicep
