### ISSUE TITLE
ImportError: cannot import name 'DocumentAnalysisClient' from 'azure.ai.formrecognizer'

### ISSUE THREAD

**Issue by DFMERA** [Azure/azure-sdk-for-python#21766]
- **azure.ai.formrecognizer**: 
- **3.1.2**: 
- **Windows 10**:
- **3.9**: 

**Describe the bug**
Hi. I'm trying to run this example:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_invoices.py
But I keep getting this error:
ImportError: cannot import name 'DocumentAnalysisClient' from 'azure.ai.formrecognizer'
even after I installed and reinstalled the azure.ai.formrecognizer package several times 

**To Reproduce**
Just download the file, replace the endpoint and the key and try to run the example:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_invoices.py

**Expected behavior**
Not getting an error when I try to run the example.

**Screenshots**
![Error python formrecognizer](https://user-images.githubusercontent.com/23387464/141861723-9a95a707-4b9b-4cf6-84a3-d449311453f2.PNG)

**Additional context**
Thank you very much for your help!!!

**Comment by kristapratico** [comment]
Hi @DFMERA, DocumentAnalysisClient is only available in the recent beta release of the Form Recognizer library. Your snippet shows installing version 3.1.2 and you need 3.2.0b1 or greater. Use command `pip install azure-ai-formrecognizer --pre --upgrade` to upgrade to the latest beta package.

Also if you're intending to use the latest GA, stable package and not the beta, please see the samples here: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1

**Comment by DFMERA** [comment]
Hi, I tried the latest GA sdk and followed the example you shared and it worked, thank you very much.

**Comment by catalinaperalta** [comment]
Thanks for the response @DFMERA! Will close this issue now then, please feel free to open new issues if there are other things we can help with :)
