### ISSUE TITLE
[Service Bus & Event Hubs] Improve livetest test stability

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#21789]
- finding if there's any tests repeatedly failing in our livetest
- whether it's an issue in SDK or VM agents' problem
- if not issue in SDK, improve the test

**Comment by swathipil** [comment]
check devops and check if something can be combined with stress test onboarding

**Comment by swathipil** [comment]
SB test flaky:  test_queue_send_twice

**Comment by swathipil** [comment]
update:
- have been checking the nightly test runs, and there are no consistently flaky tests other than one above. Just some other ones only failing once from what I've seen:

EH:
tests/livetest/synctests/test_consumer_client.py::test_receive_batch_no_max_wait_time

SB:
FAILED tests/test_subscriptions.py::ServiceBusSubscriptionTests::test_subscription_by_servicebus_client_receive_batch_with_deadletter
FAILED tests/async_tests/test_queues_async.py::ServiceBusQueueAsyncTests::test_async_queue_by_servicebus_client_browse_messages_with_receiver
FAILED tests\test_queues.py::ServiceBusQueueTests::test_queue_by_queue_client_conn_str_receive_handler_with_autolockrenew
FAILED tests/test_queues.py::ServiceBusQueueTests::test_queue_send_dict_messages_scheduled
FAILED tests/test_queues.py::ServiceBusQueueTests::test_queue_operation_negative

**Comment by swathipil** [comment]
check 12/28:
FAILED tests/async_tests/test_queues_async.py::ServiceBusQueueAsyncTests::test_async_queue_by_queue_client_conn_str_receive_handler_peeklock

12/31:
FAILED tests/test_sessions.py::ServiceBusSessionTests::test_session_by_servicebus_client_session_pool
FAILED tests/test_sessions.py::ServiceBusSessionTests::test_session_by_servicebus_client_session_pool
FAILED tests/test_sessions.py::ServiceBusSessionTests::test_session_connection_failure_is_idempotent
FAILED tests/async_tests/test_sessions_async.py::ServiceBusAsyncSessionTests::test_async_session_connection_failure_is_idempotent
FAILED tests/async_tests/test_queues_async.py::ServiceBusQueueAsyncTests::test_async_queue_receiver_respects_max_wait_time_overrides
FAILED tests/async_tests/test_sessions_async.py::ServiceBusAsyncSessionTests::test_async_session_by_servicebus_client_session_pool
FAILED tests/async_tests/test_sessions_async.py::ServiceBusAsyncSessionTests::test_async_session_by_session_client_conn_str_receive_handler_with_no_session
FAILED tests/async_tests/test_sessions_async.py::ServiceBusAsyncSessionTests::test_async_session_cancel_scheduled_messages
FAILED tests/async_tests/test_sessions_async.py::ServiceBusAsyncSessionTests::test_async_session_cancel_scheduled_messages
FAILED tests/test_sessions.py::ServiceBusSessionTests::test_session_by_servicebus_client_session_pool
FAILED tests/async_tests/test_queues_async.py::ServiceBusQueueAsyncTests::test_async_queue_receiver_respects_max_wait_time_overrides
FAILED tests/async_tests/test_sessions_async.py::ServiceBusAsyncSessionTests::test_async_session_by_servicebus_client_session_pool
FAILED tests/async_tests/test_sessions_async.py::ServiceBusAsyncSessionTests::test_async_session_by_session_client_conn_str_receive_handler_with_no_session
FAILED tests/async_tests/test_subscriptions_async.py::ServiceBusSubscriptionAsyncTests::test_topic_by_servicebus_client_receive_batch_with_deadletter
FAILED tests/test_queues.py::ServiceBusQueueTests::test_queue_receive_keep_conn_alive
FAILED tests/test_sessions.py::ServiceBusSessionTests::test_session_by_servicebus_client_session_pool
FAILED tests/test_sessions.py::ServiceBusSessionTests::test_session_connection_failure_is_idempotent
FAILED tests/async_tests/test_queues_async.py::ServiceBusQueueAsyncTests::test_queue_receive_keep_conn_alive_async
FAILED tests/mgmt_tests/test_mgmt_namespaces.py::ServiceBusManagementClientNamespaceTests::test_mgmt_namespace_get_properties

FIX: async/sync test_session_by_servicebus_client_session_pool: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1336668&view=logs&j=a5c73adf-21c4-51b0-3477-575974909b75&t=920caeb1-8790-523a-08a8-f5f4e4c5560b&l=1787

**Comment by swathipil** [comment]
A lot of these are failing b/c of this error:
`https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1343200&view=logs&j=fe7804ca-eaac-501a-67e8-e2604a50cb52&t=581043c6-4578-52e9-e224-2083bb8809be&l=3251`
and this: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1343200&view=logs&j=fe7804ca-eaac-501a-67e8-e2604a50cb52&t=581043c6-4578-52e9-e224-2083bb8809be&l=2979
And this one with Auth Timeout:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1343200&view=logs&j=fe7804ca-eaac-501a-67e8-e2604a50cb52&t=581043c6-4578-52e9-e224-2083bb8809be&l=1947

**Comment by swathipil** [comment]
iter_with_defer_not_found:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1355297&view=logs&j=fa284728-64c9-5de0-4442-32743d14c85e&t=b93d123d-eb8b-5272-3a5e-e2a5347ca4ca&l=2009
test_message_lock_renew:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1358691&view=logs&j=217ad987-cc73-5dcd-abbd-eb23972de726&t=f10366f4-42a0-5bf3-0a2a-6be221a21989&l=4644

**Comment by swathipil** [comment]
nightly runs have been green for a week so closing

**Comment by swathipil** [comment]
more failures 3/7: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1413650&view=results

**Comment by yunhaoling** [comment]
success criteria: 90% pass rate for the past two weeks

**Comment by swathipil** [comment]
most flaky EH tests:
- sync and async test_buffered_producer.py:
  - test_basic_send_single_events_round_robin[***-***-False]
  - test_long_wait_small_buffer:
```
```
  - test_basic_send_batch_events_round_robin[***-***-False]

- sync and async test_send.py:
  - test_send_with_partition_key[***]: 
```
source = "amqps://{}/{}/ConsumerGroups/{}/Partitions/{}".format(
                        live_eventhub['hostname'],
                        live_eventhub['event_hub'],
                        live_eventhub['consumer_group'],
                        index)
                    partition = uamqp.ReceiveClient(source, auth=sas_auth, debug=***, timeout=0, prefetch=500)
                    reconnect_receivers.append(partition)
                    retry_total += 1
            if retry_total == 3:
                raise OperationTimeoutError(f"Exhausted retries for receiving from {live_eventhub['hostname']}.")
    
        for r in reconnect_receivers:
            r.close()
    
>       assert single_cnt == 60
E       assert 30 == 60
E         +30
E         -60
```
