### ISSUE TITLE
Express Route Circuits route table device_path argument

### ISSUE THREAD

**Issue by etiedem** [Azure/azure-sdk-for-python#21781]
- **Package Name**: azure-mgmt-network
- **Package Version**: 19.3.0
- **Operating System**: macOS
- **Python Version**: 3.10.0

**Describe the bug**
Trying to use express_route_circuits.begin_list_routes_table and can't find what the device_path is in reference to. The documentation just says "the path to the device"...

**Additional context**
Suggest updating the documentation with an example or what field this would be in the JSON view.

**Comment by swathipil** [comment]
@etiedem Thanks for the feedback! We'll investigate asap.

**Comment by SaurabhSharma-MSFT** [comment]
@etiedem You need to pass `device_path` as "primary" or "Secondary" to get the results. Thanks.

**Comment by etiedem** [comment]
Appreciate the help. Could you please add it to the documentation? Some of the parameters for other methods list out the accepted values.

**Comment by SaurabhSharma-MSFT** [comment]
@etiedem sure, thanks for you feedback.  I will work internally on the same to get the documentation updated.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@etiedem We are proceeding with the closure of the issue.  Please feel free to open a new issue if you have any other questions.

Thanks
Saurabh
