### ISSUE TITLE
Serialization of None property

### ISSUE THREAD

**Issue by vivek-microsoft** [Azure/azure-sdk-for-python#21792]
- **Package Name**: cosmosdb-preview extension of azure-cli-extension
- **Package Version**: under development
- **Operating System**:
- **Python Version**: 

**Describe the bug**
https://github.com/Azure/azure-cli-extensions/pull/3948#pullrequestreview-808184321

**To Reproduce**
1. Set AuthenticationMethodLdapProperties of DataCenterResourceProperties to None.
2. Serialize DataCenterResourceProperties
3. AuthenticationMethodLdapProperties still gets serialized as {}

**Expected behavior**
I do not expect AuthenticationMethodLdapProperties key to be part of the serialized payload.

**Screenshots**
Below is an example payload of DataCenterResourceProperties even when AuthenticationMethodLdapProperties is set to None.

{"properties": {"dataCenterLocation": "westeurope", "delegatedSubnetId": "/subscriptions/dd31ecae-4522-468e-8b27-5befd051dd53/resourceGroups/visunda-az/providers/Microsoft.Network/virtualNetworks/visunda-westeurope/subnets/nova-subnet", "nodeCount": 3, "authenticationMethodLdapProperties": {}}}

**Additional context**

**Comment by kushagraThapar** [comment]
@vivek-microsoft - is this an issue in Cosmos DB python SDK v4 ?
