### ISSUE TITLE
Cannot set data retention when adding a data feed.

### ISSUE THREAD

**Issue by tcsatheesh** [Azure/azure-sdk-for-python#21794]
- azure-ai-metricsadvisor: 
- 1.0.0: 
- Ubuntu 18.04.5
- Python 3.7.5: 

When adding a datafeed I am not able to provide a data retention value. Hence when I try to load historical data via the SDK I get the following error. "(ERROR_INCORRECT_DATA_START_TIME) dataStartTime need comply with the max data retention constraints, the number of data slice between dataStartTime and created Time can't be more than max data retention."

1. Using the SDK create a data feed with the following settings. 
    granularity = DataFeedGranularity(
                granularity_type="Custom",
                custom_granularity_value=300,
            )
   ingestion_settings=DataFeedIngestionSettings(
                ingestion_begin_time="2021-01-01T00:00:00Z,
  )

Expected behaviour
The data feed should be created as the ingestion_begin_time is within the max data retention period.

**Comment by xiangyan99** [comment]
Thanks for reporting the issue. Unfortunately we don't support adding data retention value in this version.
