### ISSUE TITLE
Get All ARM Templates from subscription

### ISSUE THREAD

**Issue by reach4bawer** [Azure/azure-sdk-for-python#21793]
I am trying to get ARM Templates deployed in my subscription and see which resources and type (VM vs API app vs App Service) of the resource are linked to the templates via python. Is this possible through python sdk?

**Comment by swathipil** [comment]
@reach4bawer - Thanks for your question! I'm not sure whether there is information linked to a resource about how it was created (ex. Azure Portal vs. ARM template vs. REST API etc.), so I'm not aware of an SDK that would allow you to do this. 

However, someone from the ARM Template service may have a better idea if there is information somewhere on how a resource was created. Directing this to the right people!

**Comment by PramodValavala-MSFT** [comment]
@reach4bawer Once deployed, ARM Templates become Deployments which you can [list for a subscription](https://docs.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.resources.v2021_04_01.aio.operations.deploymentsoperations?view=azure-python#list-at-subscription-scope-filter--optional-str----none--top--optional-int----none----kwargs--any-----asynciterable-azure-mgmt-resource-resources-v2021-04-01-models--models-py3-deploymentlistresult-) (check the same doc for other scopes). The returned object has a list of output resources (their Resource Ids) which are the ones affected by the deployment.

Hope that covers what you are looking for.

**Comment by PramodValavala-MSFT** [comment]
@reach4bawer Just following up here... Hope my previous comment clears things up.

**Comment by reach4bawer** [comment]
@PramodValavala-MSFT thank you for the example. Would reader role be able to pull all the attributes of the deployment?

**Comment by PramodValavala-MSFT** [comment]
@reach4bawer Yes. Any account with the `reader` role should be able to do it. For custom roles, ensure you have the `Microsoft.Resources/deployments/*/read` permission.
