### ISSUE TITLE
azure-identity | CertificateCredential does not parse PEM file properly

### ISSUE THREAD

**Issue by skylaro** [Azure/azure-sdk-for-python#21798]
- **Package Name**: azure-identity
- **Package Version**: 1.7.1
- **Operating System**: Linux/Ubuntu
- **Python Version**: Python 3.8

**Describe the bug**
Seeing the following exception:
File '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/azure/identity/_credentials/certificate.py', line 54, in __init__
client_credential = get_client_credential(certificate_path, **kwargs)
File '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/azure/identity/_credentials/certificate.py', line 133, in get_client_credential
cert = load_pkcs12_certificate(certificate_data, password)
File '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/azure/identity/_credentials/certificate.py', line 95, in load_pkcs12_certificate
six.raise_from(ValueError('Failed to deserialize certificate in PEM or PKCS12 format'), ex)

Verified incoming cert file is indeed the right format and that it works on previous versions of azure-identity (specifically 1.4). Also confirmed the error on Python 3.9. Looking at the code, this appears to be an issue with cryptography.

**To Reproduce**
1. Create CertificateCredential object and pass in fake IDs and certificate path (in PEM format).
2. Print the credential if necessary.

**Expected behavior**
Object should create without throwing deserialization exceptions.

**Screenshots**

**Additional context**

**Comment by swathipil** [comment]
@skylaro Thanks for your feedback! We'll investigate asap!

**Comment by xiangyan99** [comment]
@skylaro Thanks for reporting the issue. 

Could you help to check the cryptography library version you are using? Is it 35.0.0?

Thanks.

**Comment by skylaro** [comment]
Yes, 35.0.0. Thanks for your diligence in looking into this!

**Comment by xiangyan99** [comment]
@skylaro Thanks for the information.
cryptography 35.0.0 made a breaking change deserializing certificate in PEM or PKCS12 format.

They acknowledges it and merged the fix. But 36.0.0 is not released yet.

In the meanwhile, can you use cryptography < 4?

Does it work?

Thanks.

**Comment by skylaro** [comment]
@xiangyan99 can you please paste a link for the merge?

crypto 3.4 works ok for now. When is 36.0.0 being released? Thanks so much.

**Comment by xiangyan99** [comment]
@skylaro unfortunately, cryptography is not owned by us. We cannot make promise on behalf of them. :)

The issue was tracked in https://github.com/pyca/cryptography/issues/6366.

**Comment by skylaro** [comment]
Thanks for that info. We can close this issue now :)

**Comment by mlongtin0** [comment]
FYI: The fix in version 36 seems to support certificate and private key in the same file, but not "Bag attributes" and other items outside the BEGIN/END delimiters.
