### ISSUE TITLE
[Test Proxy] Proxy errors don't have an `x-ms-error-code` header

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#21809]
With test proxy docker image 1196074, the correct error is raised when a record mismatch is encountered, but the `error_code` of the response is `None`. Because of this, for Tables tests, a `TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'` is raised when [attempting to format the error code](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/azure/data/tables/_error.py#L132) in [`_decode_error`](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/azure/data/tables/_error.py#L70).

**Comment by mccoyp** [comment]
@scbedd

**Comment by scbedd** [comment]
I know that we're properly updating the STATUS code, but this `error_code`..

@mccoyp is this in the body? Do I just need to have add it to the json body?

```json
{
"message": "<explanation"
"error_code": <PutStatusCode>
}
```

**Comment by mccoyp** [comment]
@scbedd Ah, looks like this is a local variable in Tables. It's the value of the `x-ms-error-code` header in the response

**Comment by scbedd** [comment]
Additional detail alwayus appreciated :D

**Comment by mccoyp** [comment]
Error handling specifically for [test proxy errors](https://github.com/Azure/azure-sdk-for-python/blob/3e3fbe818eb3c80ffdf6f9f1a86affd7e879b6ce/sdk/tables/azure-data-tables/azure/data/tables/_error.py#L84) was added, so this should be less of an issue now. There may be other packages that [use the `x-ms-error-code` header](https://github.com/Azure/azure-sdk-for-python/blob/3e3fbe818eb3c80ffdf6f9f1a86affd7e879b6ce/sdk/tables/azure-data-tables/azure/data/tables/_error.py#L71) to interpret errors, so it might be worth populating this header in test proxy errors if that's a standard practice

**Comment by scbedd** [comment]
I'd rather not add language-specific errors yet. I'll keep this in mind to see if this is a behavior that we want to be customizable.

**Comment by scbedd** [comment]
We now handle this in the python side by raising for status when getting back the 404. It's visible. Closing this issue!
