### ISSUE TITLE
PoolAddParameter lacks support for user assigned identities

### ISSUE THREAD

**Issue by anibaldk** [Azure/azure-sdk-for-python#21811]
Python PoolAddParameter constructor lacks support for a user assigned identity specification (unlike .NET which does).

Expectation (but equivalent in Python):
`
Identity = new BatchPoolIdentity {
    Type = PoolIdentityType.UserAssigned,
    UserAssignedIdentities = new Dictionary<string, UserAssignedIdentities>{
        ["Your Identity Resource Id"] = new UserAssignedIdentities()
    }
}
`

If support was already added, then online documentation has not been updated.

Thanks!

**Comment by swathipil** [comment]
@anibaldk Thanks for your feedback! Investigating asap!

**Comment by xiangyan99** [comment]
@anibaldk Thanks for the feedback. Could you tell us where is the online documentation you are referring to?

**Comment by anibaldk** [comment]
> @anibaldk Thanks for the feedback. Could you tell us where is the online documentation you are referring to?

Of course, mate: https://docs.microsoft.com/en-us/python/api/azure-batch/azure.batch.models.pooladdparameter?view=azure-python

This is the constructor I see:
`PoolAddParameter(*, id: str, vm_size: str, display_name: Optional[str] = None, cloud_service_configuration=None, virtual_machine_configuration=None, resize_timeout=None, target_dedicated_nodes: Optional[int] = None, target_low_priority_nodes: Optional[int] = None, enable_auto_scale: Optional[bool] = None, auto_scale_formula: Optional[str] = None, auto_scale_evaluation_interval=None, enable_inter_node_communication: Optional[bool] = None, network_configuration=None, start_task=None, certificate_references=None, application_package_references=None, application_licenses=None, task_slots_per_node: Optional[int] = None, task_scheduling_policy=None, user_accounts=None, metadata=None, mount_configuration=None, **kwargs)`

**Comment by xiangyan99** [comment]
@anibaldk Thanks for the information.

@annatisch I see we do have BatchPoolIdentity implemented. Could you take a look?

**Comment by annatisch** [comment]
@cRui861 - do you know who the best person to look at this would be?

**Comment by akivagold** [comment]
@annatisch any news on this?

**Comment by tomkp75** [comment]
Hi, is there a known workaround to address that? Thanks

**Comment by swathipil** [comment]
Hi @paterasMSFT - Just bumping this. It looks like we haven't gotten a response from the team. Would you be able to take a look or tag someone who would be able to address this? Thanks!

**Comment by wiboris** [comment]
@swathipil 
There are two implementations of "Pools" in the azure batch sdk's one in the Azure-Batch and one in azure-mgmt-batch.  Only the one defined in azure-mgmt-batch support managed identities.

here's a link to the docs:
https://docs.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.operations.pooloperations?view=azure-python

here's a rough code sample of using managed identities with pools in azure-mgmt-batch

useridentity = azure-mgmt-batch.models.UserAssignedIdentities()
my_dict = {'/subscriptions/0000-000-000-0000-00000000/resourcegroups/mygroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/userid1': useridentity}
identity =  models.BatchAccountIdentity(type=azure-mgmt-batch.models.ResourceIdentityType.USER_ASSIGNED,user_assigned_identities=my_dict)
    
poolParams = azure-mgmt-batch.models.Pool(identity=identity, display_name="pool1")

#create a pool with a managed identity   batch_mgnt_client.pool.create(resource_group_name="mygroup",account_name="myaccount", pool_name="pool1",parameters=poolParams)

#update an existing pool with a managed identiy batch_mgnt_client.pool.update(resource_group_name="mygroup",account_name="myaccount", pool_name="pool1",parameters=poolParams)
