### ISSUE TITLE
Where is the documentation for the Synapse SDKs?

### ISSUE THREAD

**Issue by jjgriff93** [Azure/azure-sdk-for-python#21818]
It seems to be non-existent!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 307038e8-4959-ee4b-395c-8ee1b6150658
* Version Independent ID: eba7238b-84a9-dcf7-8f39-8488fe7d1e29
* Content: [Microsoft Azure SDK for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/synapse-artifacts-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/synapse-artifacts-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/synapse-artifacts-readme.md)
* Service: **synapseanalytics**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by xiangyan99** [comment]
They are still in preview.

You need to switch to Preview version to find them.
