### ISSUE TITLE
More informative exceptions for PartitionKey and RowKey type errors in azure.data.tables 

### ISSUE THREAD

**Issue by SiddyP** [Azure/azure-sdk-for-python#21848]
Using `azure.data.tables`
When trying to add a table entity with erroneous PartitionKey and/or RowKey (here PartitionKey is an int instead of a str):

```
mytable.upsert_entity(entity={u'PartitionKey':1, u'RowKey':'0', 'data':123})
```
The end of the stack trace returns this:

`AttributeError: 'int' object has no attribute 'replace'`

because `_prepare_key()` tried to replace quotes on an integer instead of a string.

I would like to check the instance of the PartitionKey and RowKey and return a more informative error if they are not of type string. For example in `_prepare_key()` in `_serialize.py`:

```
def _prepare_key(keyvalue):
    """Duplicate the single quote char to escape."""
    if not isinstance(keyvalue, str):
        raise TypeError(f'PartitionKey or RowKey must be of type string.')
    return keyvalue.replace("'", "''")
```

**Comment by annatisch** [comment]
Thanks for the report @SiddyP! This is a good catch :)
@YalinLi0312 let's get this fixed up!
