### ISSUE TITLE
Event hub async client creation mypy bug

### ISSUE THREAD

**Issue by eavanvalkenburg** [Azure/azure-sdk-for-python#21847]
- **Package Name**: eventhubs
- **Package Version**: 5.6.1
- **Operating System**: linux
- **Python Version**: 3.9

**Describe the bug**
When I create a async EventHubProducerClient using the EventHubSharedKeyCredential mypy raises this error:
`error: Argument "credential" to "EventHubProducerClient" has incompatible type "EventHubSharedKeyCredential"; expected "Union[AsyncTokenCredential, AzureSasCredential, AzureNamedKeyCredential]"  [arg-type]`

While in the documentation the use of EventHubSharedKeyCredential is explicitely mentioned as also allowed (and it works), so either the documentation needs to be updated or the typing info!

**To Reproduce**
1. create script that instantiates a aio EventHubProducerClient with EventHubSharedKeyCredential
2. run mypy 

**Expected behavior**
No mypy error

**Screenshots**

**Additional context**

**Comment by yunhaoling** [comment]
thanks @eavanvalkenburg for the feedback! we will improve on the mypy experience.

**Comment by yunhaoling** [comment]
hey @eavanvalkenburg , FYI I've merged PR for fixing the mypy issue, it will be included in our upcoming release!

**Comment by eavanvalkenburg** [comment]
Thanks for reporting @yunhaoling I'll give it a try!
