### ISSUE TITLE
Enable Backup : BMSUserErrorInvalidInput Message: Input provided for the call is invalid

### ISSUE THREAD

**Issue by anotherancientalien** [Azure/azure-sdk-for-python#21854]
Hi,

I have trying the Backup API and SDK. This issue is still exists:

https://github.com/Azure/azure-sdk-for-python/issues/1422

Is there any recently updated example about enabling backup?
Any advice would be appreciated.

Best

**Comment by BigCat20196** [comment]
Hi @anotherancientalien, We have created a sample [here](https://github.com/Azure-Samples/azure-samples-python-management/tree/main/samples/recoveryservicesbackup). Hope this can help you.

**Comment by anotherancientalien** [comment]
@BigCat20196  I appreciate your kind help.
