### ISSUE TITLE
Response from service 'Microsoft.Capacity' does not contain sufficient information to enforce access control policy

### ISSUE THREAD

**Issue by victornoriega** [Azure/azure-sdk-for-python#21850]
- **Package Name**:  azure.mgmt.reservation
- **Package Version**:  1.0.0
- **Operating System**: Ubuntu 20
- **Python Version**: 3.7.6

**Describe the bug**
When calling get_catalog(subscription, resource_type, location), it returns an error (same as the title).
azure.core.exceptions.HttpResponseError: (BadGateway) Response from service 'Microsoft.Capacity' does not contain sufficient information to enforce access control policy.

**To Reproduce**
1
reservations = AzureReservationAPI(DefaultAzureCredential())
reservations.get_catalog(subscription_id="xxxxxxx...", reserved_resource_type="VirtualMachines", location="westus")

**Expected behavior**
expected a catalog of skus available for azure subscription. When running az-cli to show catalogs with same subscription I did not have this problem.

**Comment by SaurabhSharma-MSFT** [comment]
@victornoriega I have tested this in my environment but I am not seeing any issues and the api is giving me results back-
![image](https://user-images.githubusercontent.com/38112130/143973338-987634a4-bfab-479a-8d69-fe0e40c18bf0.png).

**Comment by victornoriega** [comment]
I'm using a conda environment. This is what I have:
azure-common==1.1.25
azure-core==1.8.2
azure-identity==1.4.1
azure-keyvault-secrets==4.2.0
azure-mgmt-compute==17.0.0
azure-mgmt-core==1.2.1
azure-mgmt-consumption==8.0.0
azure-mgmt-monitor==1.0.0
azure-mgmt-network==16.0.0
azure-mgmt-reservations==1.0.0
azure-mgmt-resource==15.0.0
azure-mgmt-storage==16.0.0
cffi==1.14.3
chardet==3.0.4
cryptography==3.1.1
isodate==0.6.0
msal==1.5.0
msal-extensions==0.2.2
msrest==0.6.19
numpy==1.19.2
oauthlib==3.1.0
pandas==1.1.5
portalocker==1.7.1
pycparser==2.20
pymongo==3.12.0
PyJWT==1.7.1
requests-oauthlib==1.3.0
msrestazure==0.6.4
schedule==1.1.0

**Comment by xiangyan99** [comment]
@victornoriega did you install your conda package from https://anaconda.org/microsoft?

You can find our latest packages from https://anaconda.org/microsoft repo and the latest version is 2021-12-01.

**Comment by SaurabhSharma-MSFT** [comment]
@victornoriega Did you get a chance to look into @xiangyan99's response.

**Comment by SaurabhSharma-MSFT** [comment]
@victornoriega We are following up to know if you are still facing issue and needs help.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@victornoriega We are closing this issue as we have not heard back from you.  

Thanks
Saurabh
