### ISSUE TITLE
Backup : self.session.request(  # type: ignore TypeError: request() got an unexpected keyword argument 'raw'

### ISSUE THREAD

**Issue by AnAncientAlien** [Azure/azure-sdk-for-python#21865]
Hi,

```
backup_client = RecoveryServicesBackupClient(credentials, subscription_id)
rq = backup_client.protection_containers.refresh(
    recovery_services_vault_name,
    resource_group_name,
    fabric_name,
    raw=True
))
```
rq returns : `site-packages/azure/core/pipeline/transport/_requests_basic.py", line 324, in send
    response = self.session.request(  # type: ignore
TypeError: request() got an unexpected keyword argument 'raw'
`
When I remove `raw=True` rq returns `None`
I have used [backup tests](https://github.com/Azure/azure-sdk-for-python/tree/3f6238b2a224df11fa88c6501e078aac96697277/sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/tests) as reference.

Any advice would be appreciated.

Best

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by SaurabhSharma-MSFT** [comment]
@AnAncientAlien 
You are getting error as you are referring to old test example however in the recent SDK version `raw` has been removed.  Please refer to [this](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/CHANGELOG.md#100b1-2021-05-14) changelog.  

> ![image](https://user-images.githubusercontent.com/38112130/143982784-6fd958bb-4e52-4f95-a218-2204b3f14697.png)

Please let me know if you have any other questions.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@AnAncientAlien Please let us know if you have any questions.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@AnAncientAlien We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
