### ISSUE TITLE
get_paths recursive flag not working for ADLS File System

### ISSUE THREAD

**Issue by emeadows** [Azure/azure-sdk-for-python#21876]
azure-storage-file-datalake
20.0.2
Ubuntu 20.04
python 3.8

Calling get_paths using FileSystemClient with recursive=True does not navigate the file system

I have a ADLS gen2 storage account using the File System which I am attempting to list all the files and folders contained within.  When calling the code below, I only get the top level files and directories, regardless of if recursive is true or not.  From the documemntation I assumed recursive would mean supplying the full file system.

 **To Reproduce**

Structure is:

```
dir1
 - sub_dir1
   - file1
dir2
 -sub_dir2
   - file2
file3
```

I was expecting a list containing all but all I recieve is ['dir1', 'dir2', 'file3']

example code snippet:
```
service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format("https", storage_account), credential=credential)
file_system_client = service_client.get_file_system_client(file_system="container_name")

paths = file_system_client.get_paths(recursive=True, upn=True)
for path in paths:
    print(path.name)
```

The same result occurs when `paths = file_system_client.get_paths(recursive=True, upn=True)` or `paths = file_system_client.get_paths(recursive=False, upn=True)`

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by tasherif-msft** [comment]
Hi @emeadows thank you for reaching out. Which datalake version are you using?

**Comment by emeadows** [comment]
It's Azure Data Lake Storage Gen 2, here is the details of our setup.  I suspect some are not required but trying to be complete
Performance/Access tier: Standard/Hot
Replication: Locally-redundant storage (LRS)
Account kind: StorageV2 (general purpose v2)
Location: Switzerland North
Data Lake Storage
Hierarchical namespace: Enabled
Default access tier: Hot

**Comment by tasherif-msft** [comment]
Hi @emeadows which package version of datalake are you using? the most recent one?

**Comment by emeadows** [comment]
azure-storage-file-datalake 12.5.0

**Comment by tasherif-msft** [comment]
Hi @emeadows I'm unable to reproduce your issue, could you please make another run, turn on logging and provide me with the request ID?
