### ISSUE TITLE
How to get next Page of ADF Pipeline run details using continuation_token in Azure Data Factory

### ISSUE THREAD

**Issue by MarioPrietoMatica** [Azure/azure-sdk-for-python#21879]
I am using

adf_client.pipeline_runs.query_by_factory(resourceGroupName, factoryName, filter_parameters)

method of azure.mgmt.datafactory.DataFactoryManagementClient package to fetch ADF Pipeline Run details.

The response of above function returns 100 pipeline run records at once. Along with the response, it returns continuation_token which, I believe, is supposed to be used to fetch next set/page of records.

I am not sure which function to be used for this. I tried using azure.mgmt.datafactory.models.PipelineRun() function (trial and error) to see if that satisfies the requirement. Unfortunately, it doesn't. MS Documentation is also very abstract to understand.

So, which function in Azure's Python SDK can be used to fetch next page of run records?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 088b5808-1cf3-89b3-79ec-8652688d41d1
* Version Independent ID: 5eee7f0e-e564-85de-a4fd-de1d6128b716
* Content: [azure.mgmt.datafactory.operations.PipelineRunsOperations class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.operations.pipelinerunsoperations?view=azure-python#query-by-factory-resource-group-name--factory-name--filter-parameters----kwargs-)
* Content Source: [docs-ref-autogen/azure-mgmt-datafactory/azure.mgmt.datafactory.operations.PipelineRunsOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-datafactory/azure.mgmt.datafactory.operations.PipelineRunsOperations.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by PramodValavala-MSFT** [comment]
@MarioPrietoMatica The [`RunFilterParameters`](https://docs.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.models.runfilterparameters?view=azure-python) has the `continuation_token` parameter to be set when calling this method, the second time.

**Comment by PramodValavala-MSFT** [comment]
@MarioPrietoMatica Just following up here... Hope my previous comment clears things up.
