### ISSUE TITLE
Auto-resolve keyvault referenced secrets in azure-appconfiguration

### ISSUE THREAD

**Issue by DhavalShewale** [Azure/azure-sdk-for-python#21882]
**Is your feature request related to a problem? Please describe.**
Currently azure-appconfiguration library return the secret uri for keyvault referenced secrects

**Describe the solution you'd like**
These secrets should be auto-resolved or there should be a configuration setting/parameter in the client which can be enabled to resolve the secret

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by DhavalShewale** [comment]
@xiangyan99 Do we have any plans to support this in the near future?

**Comment by xiangyan99** [comment]
@DhavalShewale unfortunately, it is not in our plan yet. 

Well, we do have an app config provider that supports this feature.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core?tabs=core5x

Does this work for you?

**Comment by DhavalShewale** [comment]
@xiangyan99 No I cannot migrate my python app to DotNet just for this feature. Can you pls take this up as a feature request.

This feature is supported by most of the azure SDKs like Java, Spring, DotNet. Infact even az cli supports this. It is a bit strange that python SDK left this out.

**Comment by xiangyan99** [comment]
@DhavalShewale Thanks for the information.

I checked with the devs (we are in same team) and neither of them supports it.

Only app config providers support the feature and we have not released providers for Python yet.

Could you send us the link of Java and .net packages that support the feature? So we can confirm we are on same page.

**Comment by DhavalShewale** [comment]
@xiangyan99 

Hey, my bad I did recheck and sadly even Java SDK does not support auto resolution. (we don't use a lot of plain java so pardon my ignorance)

Also, I am not exactly sure what do you mean by app config providers or how do they differ from SDK. I included .net into the list as the link you shared above was related to .net. (tbh, I have never worked with .net)

These are the packages that I use frequently and they support auto-resolution

## Spring Boot
We are using below library for Java + Spring Boot Applications and it resolves all keyvault referenced secrets
```
<dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>azure-spring-cloud-appconfiguration-config</artifactId>
      <version>2.0.0</version>
    </dependency>
```

## AZ CLI
We can specify the `--resolve-keyvault` option in az cli command for auto resolution of keyvault referenced secrets
```
az appconfig kv list --endpoint $ENDPOINT --key $NAMESPACE* --label $LABEL --resolve-keyvault --auth-mode login 
```


It would be really great to have the auto resolution in (Java and) Python SDK inline with the above mentioned libraries / packages.

**Comment by xiangyan99** [comment]
Thanks for the feedback. To support auto-resolve keyvault referenced secrets will make app config library depend on key vault library and that's one of the reasons that we don't implement it in SDK level.

Providers are more scenario oriented. Combining multiple SDKs to make common scenarios work well is one of the key purposes of providers.

I will forward your request to the provider developers.

**Comment by DhavalShewale** [comment]
Now I do understand what you mean by providers.

Yes it will helpful to have a provider as its a very valid use case to read the actual key vault referenced secret. Currently we have to do it as a two step process as the SDK does not support this out of the box.

**Comment by DhavalShewale** [comment]
@xiangyan99: Its been a while this feature request has been raised. Wanted to check if this is something that will be available in the near future or this is at the bottom of the pipeline currently

**Comment by xiangyan99** [comment]
@DhavalShewale Sorry for the late response. I was on vacation.

App config provider is owned by another team. Please feel free to open issues in https://github.com/Azure/AppConfiguration.

Happy new year!

**Comment by xiangyan99** [comment]
@DhavalShewale we created a sample code snippet for the scenario. https://gist.github.com/xiangyan99/cb15bb686e56bac020f93d71f524208f

please let me know if this works.

Thanks.

**Comment by mrm9084** [comment]
This is now supported in beta: https://pypi.org/project/azure-appconfiguration-provider/
