### ISSUE TITLE
The link to "SDK documentation" on this page in broken (404)

### ISSUE THREAD

**Issue by mkistler** [Azure/azure-sdk-for-python#21880]
The link to "SDK documentation" on this page in broken (404). It sends me to:

https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus/client?view=azure-python

Maybe it should be

https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus-readme?view=azure-python

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312dba6c-000c-f246-f8fe-c22c7b35366b
* Version Independent ID: 4e5d177d-ba5f-bba3-ec49-b45212d32121
* Content: [Service Bus libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python-preview#feedback)
* Content Source: [docs-ref-services/preview/servicebus.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/preview/servicebus.md)
* Service: **service-bus**
* GitHub Login: @annatisch
* Microsoft Alias: **antisch**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by yunhaoling** [comment]
hey @scbedd , I find that this page is pointing to v0.50 azure-servicebus which is very old and deprecated, I think we could remove this page. If removing would be a breaking change, then we probably should update the content to be the same as the latest one.

the old one: https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/servicebus.md
the latest preview: https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/servicebus-readme.md

**Comment by scbedd** [comment]
![image](https://user-images.githubusercontent.com/45376673/145094284-e1a564b8-4b53-4c3f-973d-a69dee119262.png)

The two boxed links are where the breaks are. I agree that the `SDK reference documentation` should be pointed at the service-bus readme. In addition, we gotta get the `SDK Source Code` link fixed as well.

**Comment by scbedd** [comment]
MicrosoftDocs/azure-docs-sdk-python#1478

**Comment by yunhaoling** [comment]
hey @scbedd , one more tiny PR for updating the link to samples: https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1494

**Comment by scbedd** [comment]
Approved!

**Comment by yunhaoling** [comment]
thanks @scbedd! 

also, thanks @mkistler for your feedbacks! The links on the page are all valid now, closing the issue.
