### ISSUE TITLE
ImportError: cannot import name 'BlobServiceClient' from 'azure.storage.blob' (/usr/lib/python3/dist-packages/azure/storage/blob/__init__.py)

### ISSUE THREAD

**Issue by wtam** [Azure/azure-sdk-for-python#21910]
- **Package Name**: azure-storage-blob:
- **Package Version**: 12.9.0
- **Operating System**: WSL:Ubuntu
- **Python Version**: 3.8.10

**Describe the bug**
cannot import name 'BlobServiceClient' from 'azure.storage.blob'

**To Reproduce**
1. pip3 install azure-storage-blob  --upgrade
2. from azure.storage.blob import BlobServiceClient

**Expected behavior**
no error

**Screenshots**

**Additional context**

**Comment by tasherif-msft** [comment]
Hi @wtam when you run `pip3 install azure-storage-blob --upgrade` what version are you upgrading from?
