### ISSUE TITLE
no license file in azure-core python install

### ISSUE THREAD

**Issue by shaunm-msft** [Azure/azure-sdk-for-python#21920]
- **Package Name**: azure-core
- **Package Version**: 1.20.1
- **Operating System**: Windows
- **Python Version**: 3.9.5

**Describe the bug**
There should be a license file dropped in the dist-info directory. A reference to the license on the project page on pypi.org isn't enough. Anyone redistributing an app needs to include the license files for each library used by the app.

**Comment by YalinLi0312** [comment]
@shaunm-msft Thanks for your feedback, we'll investigate ASAP.
