### ISSUE TITLE
no license file for azure-identity

### ISSUE THREAD

**Issue by shaunm-msft** [Azure/azure-sdk-for-python#21921]
- **Package Name**: azure-identity
- **Package Version**: 1.7.1
- **Operating System**: Windows
- **Python Version**: 3.9.5

**Describe the bug**
There should be a license file dropped in the dist-info directory. A reference to the license on the project page on pypi.org isn't enough. Anyone redistributing an app needs to include the license files for each library used by the app.

**Comment by xiangyan99** [comment]
It will be available in next release.
