### ISSUE TITLE
Schema Registry readme and samples issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#21929]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/sample_code_schemaregistry.py#L87), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py#L83), [link3](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py#L86), [link4](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/samples/async_samples/sample_code_schemaregistry_async.py#L88), [link5](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/samples/async_samples/schema_registry_async.py#L64), [link6](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/samples/async_samples/schema_registry_async.py#L68), [link7](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/schemaregistry/azure-schemaregistry#get-the-schema-by-id):
![image](https://user-images.githubusercontent.com/80307197/144000778-e78c4d58-e884-4669-8350-abcb39b0ac22.png)

Reason:
AttributeError: 'Schema' object has no attribute 'definition'.

Suggestion:
Update to `schema_definition`

@jameszliao-msft, @lmazuel, @ramya-rao-a, @yunhaoling for notification.

**Comment by yunhaoling** [comment]
hey @AFengKK , may I ask which version of azure-schemaregistry you are using?
In our latest GA version 1.0.0, we have renamed `schema_definition` to `definition`.

**Comment by swathipil** [comment]
@AFengKK - just to add on - we've gone back and forth on the naming here a few times, so apologies for the confusion! The final changes for the GA version (1.0.0) are listed here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/CHANGELOG.md#100-2021-11-10.

**Comment by AFengKK** [comment]
@yunhaoling, @swathipil. Sorry, I downloaded the wrong package and tested the 1.0.0b3 version of the package. The 1.0.0 version of the package is correct. We will close the issue.
