### ISSUE TITLE
WorkflowRunsOperations.list arguments top and filter not working?

### ISSUE THREAD

**Issue by c4g-wv** [Azure/azure-sdk-for-python#21932]
Dear,

I'm trying to use the list method of the WorkflowRunsOperations, but when I specify top=5 for example, I still seem to be getting all runs. It's as if the top argument is not taken into account?
Additionally, I'm trying to use the filter on StartTime, but keeps giving a "not valid or not supported" error. Things I've tried so far:
* filter="StartTime>2021-11-23 00:00:00"
* filter="StartTime>2021-11-23Z00:00:00"
* filter="StartTime>'2021-11-23Z00:00:00'"
* filter="StartTime>'2021-11-23'"
* filter="StartTime>2021-11-23"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8321b046-0079-e62b-2006-b0c58b90eadf
* Version Independent ID: 62407551-e186-893d-8143-5b4aad731031
* Content: [azure.mgmt.logic.operations.WorkflowRunsOperations class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-logic/azure.mgmt.logic.operations.workflowrunsoperations?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-logic/azure.mgmt.logic.operations.WorkflowRunsOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-logic/azure.mgmt.logic.operations.WorkflowRunsOperations.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by c4g-wv** [comment]
For the "filter" argument, the right syntax seems to be:
StartTime gt 2021-11-23T00:00:00Z

For the "top" argument, still not picking up the integer value, also tried passing it as string.

**Comment by YalinLi0312** [comment]
@c4g-wv Thanks for your feedback, we'll investigate asap.

**Comment by SaurabhSharma-MSFT** [comment]
@c4g-wv Would you mind providing the code snippet you are using to get the results ?

**Comment by c4g-wv** [comment]
@SaurabhSharma-MSFT test code could look something like this:
```
logicClient = LogicManagementClient(DefaultAzureCredential(), *sanitized subscr id*)
it = logicClient.workflow_runs.list(*sanitized rg name*,*logic app name*,top=1)
for i in it:
	print(i)
```
fyi: tested it on python 3.8 and 3.9

**Comment by SaurabhSharma-MSFT** [comment]
@c4g-wv I have tested this in my environment and you are correct filter works with the time format - `2021-11-23T00:00:00Z`.  
![image](https://user-images.githubusercontent.com/38112130/144499032-dc602b2e-1e42-42eb-909a-0371fa119b5a.png)

Also, I have also tried with using `top` but it does not work for me either.
Though I have tested the [Workflow-Runs rest API](https://docs.microsoft.com/en-us/rest/api/logic/workflow-runs/list) and it worked fine with REST endpoint.
`https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Logic/workflows/{{workflowName}}/runs?api-version=2016-06-01&$filter=StartTime ge 2021-11-23T00:00:00Z&$top=2`

I am checking internally on the same and get back to you.

Thanks 
Saurabh

**Comment by PramodValavala-MSFT** [comment]
@c4g-wv the `list` method here returns an object of type [`AsyncItemPaged`](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/async_paging.py#L118) which basically iterates through all the pages until there are none. The `top` parameter is actually working here but you end looping through pages of 5 entries. Either you could use a regular for loop and `it.next()` the fixed number of times like this

```py
logicClient = LogicManagementClient(DefaultAzureCredential(), "sub-id")
it = logicClient.workflow_runs.list("rg-name", "la-name", top = 5)
for i in range(0, 5):
    curr = it.next()
    print(curr)
```

Or just loop through the first page like this

```py
logicClient = LogicManagementClient(DefaultAzureCredential(), "sub-id")
pages = logicClient.workflow_runs.list("rg-name", "la-name", top = 5).by_page()
for i in pages.next():
    print(i)
```

**Comment by c4g-wv** [comment]
@PramodValavala-MSFT : thanks for looking into it. I agree, there are workarounds, but it's not how I expect it to work. Through REST API, it is properly giving 1 result back. Also, the "filter" argument is giving a proper reduced list (both in REST API and `logicClient.workflow_runs.list` function), so I'm not quite clear why it would have to be different for the "top" argument.

**Comment by PramodValavala-MSFT** [comment]
@c4g-wv You are right. In fact, the first response does return just five results, but the problem seems to be that the service returns a `nextLink` which the SDK uses to fetch consequent pages when iterating. AFAIK it should not be set when using `top` but either way, I will share this feedback with the concerning team and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@c4g-wv Please let us know if you have any additional questions else we will proceed with the closure of this issue.

**Comment by c4g-wv** [comment]
@SaurabhSharma-MSFT : Personally, I don't consider the issue closed. There is a workaround, I agree, but the parameter does not behave the way it's supposed to behave. Though, if the development team has decided not to fix it, then you can go ahead with closure.

**Comment by xiangyan99** [comment]
Given the linked PR was closed as completed. I will close this one. Please feel free to reopen it if it is not solved.
