### ISSUE TITLE
Unable to authenticate using Azure AD ClientSecretCredential against ADLS gen 2

### ISSUE THREAD

**Issue by Lameorc** [Azure/azure-sdk-for-python#21937]
- **Package Name**: azure-storage-file-datalake
- **Package Version**:  12.5.0
- **Operating System**: 
- **Python Version**: 3.8.9
Not sure which library the issue is specifically with, here's the whole list of azure dependencies we've got
```
azure-storage-blob==12.9.0
azure-storage-file-datalake==12.5.0
azure-identity==1.7.1
```

**Describe the bug**
When trying to use `DataLakeFileClient` authorized with `ClientSecretCredential`, I get exceptions with `ErrorCode:NoAuthenticationInformation` or `ErrorCode:AuthorizationPermissionMismatch`. The latter when integrated fully into my app, the former when reproducing standalone in ipython session.

**To Reproduce**
1. Setup storage according to https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-python (and the linked docs for oauth2 flow)
2. Create App registration
4. Add the app principal write, read, execute permissions on the whole container/filesystem
5. Create client as such
```
creds = ClientSecretCredential(client_id=client_id, client_secret=client_secret, tenant_id=tenant_id)
client = DataLakeServiceClient('<redacted>', credentials=creds)
file_system_client = client.get_file_system_client('<redacted'>)
```
6. running `file_system_client.exists()` raises `ClientAuthenticationError: Operation returned an invalid status 'Server failed to authenticate the request. Please refer to the information in the www-authenticate header.'
ErrorCode:NoAuthenticationInformation`, and the header shows as redacted in the output `'WWW-Authenticate': 'REDACTED'/n`

Instantiating the datalake client using string as such `DataLakeServiceClient.from_connection_string('<redacted>') gives me a working client instance.

**Expected behavior**
The client operations work without issues

**Additional context**
I've tried steps from with zero success:
- https://github.com/Azure/azure-sdk-for-python/issues/11414
- https://deep.data.blog/2019/03/28/avoiding-error-403-request-not-authorized-when-accessing-adls-gen-2-from-azure-databricks-while-using-a-service-principal/

**Comment by YalinLi0312** [comment]
@Lameorc Thanks for your feedback, we'll investigate asap.

**Comment by SaurabhSharma-MSFT** [comment]
@Lameorc I have tested using ClientSecretCredential and it worked fine for me.  As mentioned in the [documentation](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-acl-python), instead of providing access through ACL you need to provide RBAC role `Storage Blob Data Owner` or `Storage Blob Data Contributor` permissions.
Also, I have used the sample code shared in the documentation.
![image](https://user-images.githubusercontent.com/38112130/144538410-0c10f209-62d8-484f-b85f-4150e957d00c.png)

Please let me know if you have any questions.

Thanks
Saurabh

**Comment by Lameorc** [comment]
Hi, thanks for the answer @SaurabhSharma-MSFT! That seems to have solved the issue. I must have missed the link to those docs at the bottom of the "main" ones. Might be good to put that link in [this section](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-python#connect-by-using-azure-active-directory-azure-ad).

Anyway, thanks once again for solving my issue.
