### ISSUE TITLE
subscriptions.list_locations returns azure.core.exceptions.ServiceRequestError

### ISSUE THREAD

**Issue by ksridhar57** [Azure/azure-sdk-for-python#21935]
- **Package Name**: azure-mgmt-subscription
- **Package Version**: 2.0.0
- **Operating System**: linux/ubuntu 18.04
- **Python Version**: 3.6.9

**Describe the bug**
listing locations for  a given subscription returns 
"Bearer token authentication is not permitted for non-TLS protected (non-https) URLs."

**To Reproduce**
def list_azure_locations():
    locations = subscription_client.subscriptions.list_locations(azure_subscription_id)
    for location in locations:
        print(location.name)

**Expected behavior**
location list shall be iterable

**Comment by YalinLi0312** [comment]
@ksridhar57 Thanks for your feedback, we'll investigate asap.

**Comment by BigCat20196** [comment]
Hi @ksridhar57, thanks for your  feedback!

A sample may help you.
```
import os

from azure.identity import DefaultAzureCredential
from azure.mgmt.resource.subscriptions import SubscriptionClient

subscriptions_client = SubscriptionClient(credential=DefaultAzureCredential())
res = subscriptions_client.subscriptions.list_locations(os.getenv('SUBSCRIPTION_ID'))  # your subscription id

for r in res:
    print(r.name)

```
Hope this unblocks you

**Comment by SaurabhSharma-MSFT** [comment]
@YalinLi0312 Also, SubscriptionsOperations operation group has been removed in version 2.0. Please check [here](https://pypi.org/project/azure-mgmt-subscription/2.0.0/).

> ![image](https://user-images.githubusercontent.com/38112130/144538537-dd98b207-ede7-454d-a706-54e1391483bf.png)

**Comment by ksridhar57** [comment]
Thanks for the info. What is the alternative to listing locations?

**Comment by SaurabhSharma-MSFT** [comment]
@ksridhar57 Please use the code shared by @BigCat20196 to get the locations.  Please note that it uses another package `azure.mgmt.resource` which has `SubscriptionClient` and `list_locations` method to list the locations.  Hope this helps.

Thanks
Saurabh

**Comment by ksridhar57** [comment]
This is my code - 

from azure.identity import ClientSecretCredential
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.resource.subscriptions import SubscriptionClient


def  loginAz():
    a_creds = ClientSecretCredential(tenant_id=azure_tenant_id,
                                         client_id=azure_client_id,
                                         client_secret=azure_client_secret)
    resource_mgmt_client = ResourceManagementClient(a_creds, azure_subscription_id)
    subscription_client = SubscriptionClient(a_creds, azure_subscription_id)


def list_Azure_Locations():
    locations = subscription_client.subscriptions.list_locations(azure_subscription_id)
    for location in locations:
        print(location.name)

loginAz()
list_Azure_Locations()

I use these packages amongst others - 
azure-mgmt-resource     20.0.0
azure-identity          1.7.1


I get this error - 
    locations = subscription_client.subscriptions.list_locations(azure_subscription_id)
  File "/home/xbox/work/src/cbdev/venv/aztest/lib/python3.6/site-packages/azure/mgmt/resource/subscriptions/_subscription_client.py", line 159, in subscriptions
    raise ValueError("API version {} does not have operation group 'subscriptions'".format(api_version))
ValueError: API version 440774a6-0e13-4c66-ac90-007c493478ba does not have operation group 'subscriptions'

Any further advise? 

Thanks!!

**Comment by SaurabhSharma-MSFT** [comment]
@YalinLi0312 I have tried the above code and it works as expected -
![image](https://user-images.githubusercontent.com/38112130/145074015-6b0f99a6-061c-4ca4-95e3-48b36284e987.png)
I have the same version of `azure-identity` and `azure-mgmt-resource` as yours
![image](https://user-images.githubusercontent.com/38112130/145074310-ee7f9c8f-a9fd-4a04-ac5f-e146c88bdb4d.png)

**Comment by SaurabhSharma-MSFT** [comment]
@YalinLi0312 Please let me know if you have any other questions otherwise we will proceed with the closure of this issue.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@YalinLi0312 We are closing this issue now. Thanks

**Comment by YalinLi0312** [comment]
@ksridhar57 The code you provide above works on our end, please let us know if you have any other questions. Thanks!

**Comment by ksridhar57** [comment]
I tried the same code with this package - 
azure-mgmt-subscription 2.0.0

and get this error  ValueError("API version 440774a6-0e13-4c66-ac90-007c493478ba does not have operation group 'subscriptions'",)

I initialise subscription_client as follows - 

        a_creds = ClientSecretCredential(tenant_id=azure_tenant_id,
                                         client_id=azure_client_id,
                                         client_secret=azure_client_secret)
        subscription_client = SubscriptionClient(a_creds, azure_subscription_id)


What is the API version it is referring to? Any other package that I need to use specifically?

**Comment by praskumamsft** [comment]
> I tried the same code with this package - azure-mgmt-subscription 2.0.0
> 
> and get this error ValueError("API version 440774a6-0e13-4c66-ac90-007c493478ba does not have operation group 'subscriptions'",)
> 
> I initialise subscription_client as follows -
> 
> ```
>     a_creds = ClientSecretCredential(tenant_id=azure_tenant_id,
>                                      client_id=azure_client_id,
>                                      client_secret=azure_client_secret)
>     subscription_client = SubscriptionClient(a_creds, azure_subscription_id)
> ```
> 
> What is the API version it is referring to? Any other package that I need to use specifically?



> I tried the same code with this package - azure-mgmt-subscription 2.0.0
> 
> and get this error ValueError("API version 440774a6-0e13-4c66-ac90-007c493478ba does not have operation group 'subscriptions'",)
> 
> I initialise subscription_client as follows -
> 
> ```
>     a_creds = ClientSecretCredential(tenant_id=azure_tenant_id,
>                                      client_id=azure_client_id,
>                                      client_secret=azure_client_secret)
>     subscription_client = SubscriptionClient(a_creds, azure_subscription_id)
> ```
> 
> What is the API version it is referring to? Any other package that I need to use specifically?

@ksridhar57  Could you please try using 

subscription_client = SubscriptionClient(a_creds) 

instead of subscription_client = SubscriptionClient(a_creds, azure_subscription_id)  ?

**Comment by ksridhar57** [comment]
Thanks very much.  The change in object instantiation worked. But why does this SubscriptionClient(a_creds, azure_subscription_id) not return an error? 

In relation to finding locations, I also have an inquiry on obtaining list of availability zones for a compute resource. From some online search I understand this ResourceSkusOperations class provides a list method that has zone information amongst a lot of other things. But this is only supported up until v2017-09-01 which is already quite old. Is there an alternate way I can obtain the availability zone or is it still safe to use the earlier version of azure-mgmt-compute?

**Comment by msyyc** [comment]
we advise to use latest version for `azure-mgmt-compute` and `azure-mgmt-resources`
