### ISSUE TITLE
Form recognizer readme issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#21931]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/formrecognizer/azure-ai-formrecognizer#using-the-general-document-model):
![image](https://user-images.githubusercontent.com/80307197/144004081-fa18a280-f7b8-4a88-be0a-ce7af69cc09a.png)

Reason:
NameError: name 'format_bounding_box' is not defined

Suggestion:
Add code:
```
def format_bounding_box(bounding_box):
    if not bounding_box:
        return "N/A"
    return ", ".join(["[{}, {}]".format(p.x, p.y) for p in bounding_box])
```

@jameszliao-msft, @lmazuel, @meeraharidasa, @mayurid, @catalinaperalta for notification.

**Comment by catalinaperalta** [comment]
Thanks for reporting this @AFengKK! Will get a fix out for this shortly.
