### ISSUE TITLE
_batch_send() in _base_client.py in azure-data-tables is hard coded to use https

### ISSUE THREAD

**Issue by stevenzhao82** [Azure/azure-sdk-for-python#21953]
- **Package Name**:  Azure-Data-Tables
- **Package Version**: 12.2.0
- **Operating System**: Windows 10 Enterprise Edition
- **Python Version**: 3.8.8

**Describe the bug**
_batch_send() in _base_client.py in azure_data_tables is hard coded to use https.

I am using local kubernetes hosting azure storage emulator in my dev environment so I don't need SSL. I have explicitly specified http in my connection string and use the connection string to instantiate a TableClient. I can create/update/delete single entity, however, I am getting SSL Wrong Version Number error when calling TableClient.submit_transaction() to perform batch operation. 

**To Reproduce**
1. configure local kubernetes with azure storage emulator
2. use http in the connection string, e.g. 'DefaultEndpointsProtocol=http;AccountName=<accountname>;AccountKey=<accountkey>;TableEndpoint=http://<endpoint>;',
3. Instantiate a table client by using the connection string
4. Create a table 
5. prepare a list of operations and call TableClient.submit_transaction() to perform batch operation
6. Observe the result

**Expected behavior**
I am able to perform single operation with http protocol; I should be able to perform batch operation with http protocol too.

**Screenshots**
![image](https://user-images.githubusercontent.com/16602172/144185547-0971869e-32c7-4149-a9c8-938ddc5f9e42.png)

**Additional context**

**Comment by annatisch** [comment]
Thanks for the report @stevenzhao82! We'll try to repro using your steps and get a fix out in the next release.

**Comment by davidjward30** [comment]
I can repo this with the most basic use of submit_transaction. I'm adding the full text of the error message below as it took me some time to track down this issue:

azure.core.exceptions.ServiceRequestError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)

**Comment by annatisch** [comment]
Hi @stevenzhao82 - I do apologize for the delay in this!
I have opened an initial PR here #23240.
I will keep testing this and we can hopefully get this patch merged in to our March release.

@YalinLi0312 could you please help test and review?

**Comment by stevenzhao82** [comment]
Hi @annatisch,

No worries. Thank you very much for the update!

Best regards.

**Comment by annatisch** [comment]
I've merged the fix for this issue, and the release should go out next week.
Feel free to tests out the changes in the meantime and let us know if you feel it needs some further digging!

**Comment by stevenzhao82** [comment]
> I've merged the fix for this issue, and the release should go out next week. Feel free to try out the changes in the meantime and let us know if you feel it needs some further digging!

Thanks @annatisch
