### ISSUE TITLE
ACR returns error 413 Entity too large

### ISSUE THREAD

**Issue by edoboker** [Azure/azure-sdk-for-python#21957]
- **Package Name**: azure-containerregistry
- **Package Version**:  1.0.0b6
- **Operating System**: Ubuntu 20.04
- **Python Version**:  3.8.10

**Describe the bug**
When trying to fetch a refresh token to the ACR, error 413 is returned. I have tried running an equivalent `curl` with the AAD access token I have received, but received the same error. 

When trying to figure out the reason for the error, I have removed the `access_token` field from the body of the request; this didn't help, which made me suspect that the issue is not length-related.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the attached code

**Expected behaviour**
An ACR refresh token is returned

**Additional context**
This issue happened to me in a specific tenant. In other environments, the same code worked seamlessly, but I could not find any relevant documentation to error 413 on ACR.

**My code**
```
import requests
import json
from azure.identity import InteractiveBrowserCredential
from pprint import pprint


def get_aad_access_token(scope='https://management.azure.com/.default'):
    cred = InteractiveBrowserCredential()
    aad_access_token = cred.get_token(scope)
    return aad_access_token.token


def get_acr_refresh_token(acr_url=None, aad_access_token=None):
    if aad_access_token == None:
        aad_access_token = get_aad_access_token()
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
    }

    data = {
        'grant_type': 'access_token',
        'service': acr_url.lower(),
        'access_token': aad_access_token
    }

    response = requests.post(f'https://{acr_url}/oauth2/exchange', headers=headers, data=data)
    acr_refresh_token = json.loads(response.content)
    return acr_refresh_token['refresh_token']


def get_docker_login_cmd(acr_url):
    acr_refresh_token = get_acr_refresh_token(acr_url=acr_url)
    return f'docker login -u 00000000-0000-0000-0000-000000000000 -p {acr_refresh_token} {acr_url}'

if __name__ == '__main__':
    acr_url = input()
    print(get_docker_login_cmd(acr_url))
```

**Comment by YalinLi0312** [comment]
@edoboker Thanks for your feedback, we'll investigate asap.

**Comment by edoboker** [comment]
That's odd, I've always used the interactive class and it'd always worked for me. I didn't use `DefaultAzureCredential` because of some complexities in my setup. However, I don't think it would make any difference - eventually, they all generate an AAD access/refresh token...

**Comment by YalinLi0312** [comment]
Could you try with a newer package version(1.0.0b7 or later)? The error doesn't exist with my test.
