### ISSUE TITLE
Message to a partitioned entity with duplicate detection enabled must have either PartitionKey or MessageId

### ISSUE THREAD

**Issue by flying-pi** [Azure/azure-sdk-for-python#21955]
- **Package Name:**  azure-servicebus
- **Package Version:**  7.4.0
- **Operating System:** docker image python:3.8-buster
- **Python Version:** 3.8.12

**Describe the bug**
I create Standart SB Queue with enabled partitions and duplicate detection. 
![image](https://user-images.githubusercontent.com/15072964/144216963-fb41884d-6488-4da2-8207-433d67c14173.png)

And for cases, when I send messages in the batch mode, I receive an error `Message to a partitioned entity with duplicate detection enabled must have either PartitionKey or MessageId`. But when I send the same message one by one - it works ok. 

**To Reproduce**
1. run this code 
```python
connectio_string = 'Endpoint=sb://MY_WORKER_HERE.servicebus.windows.net/;SharedAccessKeyName=ingest_rule;SharedAccessKey=MY_KEY_HERE;EntityPath=MY_QUEUE_NAME_HERE'
uamqp_logger = logging.getLogger('uamqp')
uamqp_logger.setLevel(logging.DEBUG)

_connection_info = parse_connection_string(connectio_string)
_client = ServiceBusClient.from_connection_string(conn_str=connectio_string, logging_enable=True)

with _client.get_queue_sender(_connection_info.entity_path) as sender:
    service_bus_message = sender.create_message_batch()
    service_bus_message.add_message(ServiceBusMessage('msg1', message_id=uuid.uuid4().hex), )
    service_bus_message.add_message(ServiceBusMessage('msg2', message_id=uuid.uuid4().hex), )
    sender.send_messages(service_bus_message)
```
and the result will be: 
```bash 
ClientMessageError                        Traceback (most recent call last)
/usr/local/lib/python3.8/site-packages/azure/servicebus/_base_handler.py in _do_retryable_operation(self, operation, timeout, **kwargs)
    394                     kwargs["timeout"] = remaining_timeout
--> 395                 return operation(**kwargs)
    396             except StopIteration:

/usr/local/lib/python3.8/site-packages/azure/servicebus/_servicebus_sender.py in _send(self, message, timeout, last_exception)
    261             self._set_msg_timeout(timeout, last_exception)
--> 262             self._handler.send_message(message.message)
    263         finally:  # reset the timeout of the handler back to the default value

/usr/local/lib/python3.8/site-packages/uamqp/client.py in send_message(self, messages, close_on_done)
    743                     details['failed_messages'][failed_message] = exception
--> 744                 raise errors.ClientMessageError(exception, info=details)
    745         finally:

ClientMessageError: ErrorCodes.NotAllowed: Message to a partitioned entity with duplicate detection enabled must have either PartitionKey or MessageId set TrackingId:dbaf8438-ee39-4057-ad37-47371b8749cc_G23, SystemTracker:client-link425450073, Timestamp:2021-12-01T10:19:43

During handling of the above exception, another exception occurred:

ServiceBusError                           Traceback (most recent call last)
<ipython-input-64-489aa3b7946b> in <module>
      6     service_bus_message.add_message(ServiceBusMessage('msg1', message_id=uuid.uuid4()), )
      7     service_bus_message.add_message(ServiceBusMessage('msg2', message_id=uuid.uuid4()), )
----> 8     sender.send_messages(service_bus_message)

/usr/local/lib/python3.8/site-packages/azure/servicebus/_servicebus_sender.py in send_messages(self, message, **kwargs)
    415                 self._add_span_request_attributes(send_span)
    416 
--> 417             self._do_retryable_operation(
    418                 self._send,
    419                 message=obj_message,

/usr/local/lib/python3.8/site-packages/azure/servicebus/_base_handler.py in _do_retryable_operation(self, operation, timeout, **kwargs)
    397                 raise
    398             except Exception as exception:  # pylint: disable=broad-except
--> 399                 last_exception = self._handle_exception(exception)
    400                 if require_last_exception:
    401                     kwargs["last_exception"] = last_exception

/usr/local/lib/python3.8/site-packages/azure/servicebus/_base_handler.py in _handle_exception(self, exception)
    344             self._close_handler()
    345         if not error._retryable:
--> 346             raise error
    347 
    348         return error

ServiceBusError: Message to a partitioned entity with duplicate detection enabled must have either PartitionKey or MessageId set TrackingId:dbaf8438-ee39-4057-ad37-47371b8749cc_G23, SystemTracker:client-link425450073, Timestamp:2021-12-01T10:19:43 Error condition: ErrorCodes.NotAllowed.

```

**Expected behavior**
Batch sending work as expected for queues, where duplicate detection and partition enabled. Potentially - here is an issue, that batching clear individual broker properties(as message ID) so it should not happen.

**Comment by YalinLi0312** [comment]
@flying-pi Thanks for your feedback, we'll investigate asap.

**Comment by stPhoenix** [comment]
@YalinLi0312 any updates?

**Comment by yunhaoling** [comment]
hey @flying-pi @stPhoenix , sorry about the late response. I was able to reproduce the issue.

I debugged a while and found out that it might be the service not supporting this scenario.

The batch feature is implemented the way that there's a special internal BatchMessage holding the individual messages.
I initially thought that maybe it's because wrapper BatchMessage not being assigned a ParitionKey/MessageId leading to the failure.

However, after giving the BatchMessage either ParitionKey or MessageId, the service returns error as the following:

> azure.servicebus.exceptions.ServiceBusError: Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled.LogicalPartitionId:143::PartitionKey:::SessionId:::MessageId:918e16ddd572430198997ba347d916d8::ViaPartitionKey::: Reference:d79a6be3-53bc-4eba-b3ef-56f5ef6979ba, TrackingId:xxxx, SystemTracker:xxxx, Timestamp:2021-12-18T01:18:22 Error condition: ErrorCodes.NotAllowed.

I need to double check with the service team to see if this is a supported scenario first. If it's not supported by designed, I'll see for other ways to improve the development experience with this (docs/error info improvement).

thanks for your patience and I will keep you updated.

**Comment by GinSiuCheng** [comment]
@yunhaoling is the above a supported scenario?

**Comment by jbauerrfid** [comment]
I can reproduce the issue in Java as well:

1. create a List<ServiceBusMessage> where each item is constructed like:
```
            var m = new ServiceBusMessage(messagebody);
            m.setContentType("application/x-gzip");
            m.setCorrelationId(UUID.randomUUID().toString());
            m.setMessageId(UUID.randomUUID().toString());
```
2. call sendMany:

```
Flux.fromIterable(messages)
                    .flatMap(this::mapPublish)
                    .collectList()
                    .flatMapMany(m -> connection.sendMessages(m)
                            .thenMany(Flux.fromIterable(m)))
                    .map(ServiceBusMessage::getMessageId)
                    .doOnError(e -> log.error("Error at sendMany: {}", e.getMessage()));
```
the log.error shows:

"Error at sendMany: Message to a partitioned entity with duplicate detection enabled must have either PartitionKey or MessageId set ..."

the messages here clearly have IDs, I can also see it in the debugger

expected behavior is that the publish works, and I get a Flux of message IDs back

that means it is probably some generic problem, caused by the message bus backend
