### ISSUE TITLE
Enqueue a batch of messages to azure storage queue

### ISSUE THREAD

**Issue by tzurE** [Azure/azure-sdk-for-python#21956]
**Is your feature request related to a problem? Please describe.**
Currently, we're heavy users of the azure queue service. 
Our system is designed in a way, where every message is "heavy", so it's harder for us to chunk them.

**Describe the solution you'd like**
The main solution we would like to request is an API function that will give the option to write several messages to our storage queues.
A "send batch messages" logic to help us put several messages in an object/list, and send this object to our storage queue, instead of uploading messages one by one.

I'm guessing this kind of request was already suggested once, but I couldn't find an issue for this or a similar request.
So it's either impossible to develop in the current architecture, or it's not important enough?

I would love to hear an opinion on this feature request.

**Comment by YalinLi0312** [comment]
@tzurE Thanks for your feedback, we'll investigate asap.

**Comment by tasherif-msft** [comment]
Hi @tzurE, We have put this as a feature request

**Comment by tzurE** [comment]
Hi @tasherif-msft , thanks!

Is there a planning tool to see a timeline for the various requests? Are you open to code contribution of feature requests such as this?

**Comment by tasherif-msft** [comment]
Yes we are open to contributions! If it doesn't make it into the SDK we can at the very least add it as a sample for other people

**Comment by tzurE** [comment]
@tasherif-msft , So I can just start a pull request with my changes and attach it to this feature request?

**Comment by tasherif-msft** [comment]
Yes you can

**Comment by detuniko** [comment]
HI @YalinLi0312 @SaurabhSharma-MSFT  @jalauzon-msft  @tasherif-msft 
Is such a feature (enqueueing multiple messages in one call to one specific Azure Storage Queue by one writer) available to use from the .NET SDK ?
