### ISSUE TITLE
Unexpected program hang after exception is raised while iterating a generator

### ISSUE THREAD

**Issue by Indy2222** [Azure/azure-sdk-for-python#21985]
- **Package Name**: azure-servicebus
- **Package Version**: 7.4.0
- **Operating System**: GNU/Linux
- **Python Version**:  3.9.9

Strangely, the following program does not terminate:

```python
from azure.identity import DefaultAzureCredential
from azure.servicebus import (
    ServiceBusClient,
    ServiceBusReceiveMode,
)


def receive():
    namespace = 'xxx'
    topic = 'yyy'
    subscription = 'zzz'

    credential = DefaultAzureCredential()
    client = ServiceBusClient(
        fully_qualified_namespace=f'{namespace}.servicebus.windows.net',
        credential=credential,
    )

    with client as client:
        receiver = client.get_subscription_receiver(
            topic_name=topic,
            subscription_name=subscription,
            receive_mode=ServiceBusReceiveMode.PEEK_LOCK,
        )
        with receiver as receiver:
            for message in receiver:
                yield message


def main():
    messages = receive()
    for message in messages:
        raise Exception('Terminate program.')


if __name__ == '__main__':
    main()
```

It prints the exception and hangs:

```
Traceback (most recent call last):
  File "/home/indy/dm/sb-experiment/./sbexperiment/app.py", line 40, in <module>
    main()
  File "/home/indy/dm/sb-experiment/./sbexperiment/app.py", line 36, in main
    raise Exception('Terminate program.')
Exception: Terminate program.
```

But it works as expected when I modify `main()` to this:

```python
def main():
    for message in receive():
        raise Exception('Terminate program.')
```

**Comment by YalinLi0312** [comment]
@Indy2222 Thanks for your feedback, we'll investigate asap.

**Comment by yunhaoling** [comment]
hey @Indy2222 , I am able to reproduce the issue.
this is an interesting issue -- from the code itself I didn't see a major difference. I tried to debug and execute one line by one line, and they are of the same execution order.

I honestly am not clear on what happens when error is raised and how python exits the program, need to do some more research.

Are you blocked by this issue? I think adding a try except catch should help you bypass this hang issue.

**Comment by Indy2222** [comment]
Thank you for the investigation!

I am not blocked on the issue personally. However, I think that others might easily spend a some "painful" time figuring out what is happening (like I did) if they use the client in the same way. Therefore, I think this is worth fixing sooner rather then later.

**Comment by swathipil** [comment]
Hey @Indy2222 - Appreciate your feedback on this! We have a few other issues taking priority at the moment, but we plan to address this as soon as possible. Thank you!

**Comment by Indy2222** [comment]
Hey. Is there any progress on the issue?

**Comment by swathipil** [comment]
Hey @Indy2222 - apologies for the late update! I'll make sure to discuss this with the team this upcoming week and keep you posted on when we can address this. Thanks!

**Comment by pavelm10** [comment]
Hey guys, I encountered exactly the same issue. Any time estimate when this could be fixed? thanks

**Comment by swathipil** [comment]
Hey all! Apologies for the long delay here. Unfortunately, it's been a very busy month and we were not able to find time to investigate this issue. However, this is definitely on our radar, and I will be bringing this up to the team again in a few weeks.

**Comment by pavelm10** [comment]
Hi,

I have tested it with:
`python = 3.7.9, 3.8.6, 3.9.12`,
`azure-servicebus = 7.6.1`,
`uamqp = 1.5.3`,
`OS: Ubuntu 20.04.4 LTS`
With `3.9.12` it does not happen, with the others it does.

**Comment by kashifkhan** [comment]
Hi @Indy2222  and @pavelm10, 

I apologize for the extreme delay in providing an update to this matter.  We are currently working on moving `azure-servicebus` away from `uamqp` and on to a pure python based stack, which will address this issue. The preview is expected to be released in February. I'll leave this issue open and update yall when its available on pypy.

**Comment by xiangyan99** [comment]
@kashifkhan Is this one released?

**Comment by kashifkhan** [comment]
@xiangyan99 The beta for service bus pyamqp has been released, which should have the fix. GA is not released yet

**Comment by xiangyan99** [comment]
@kashifkhan Thank you.

@Indy2222 Please try latest beta and let us know if it does not work.
