### ISSUE TITLE
Is the date time in starting_position means EnqueuedUtcTime of the message?

### ISSUE THREAD

**Issue by HuaqiongWu** [Azure/azure-sdk-for-python#21994]
Is the date time in starting_position means EnqueuedUtcTime of the message?
If i want to receive messages from the certain message create time, what should i do ?  

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3882d6ff-f3f3-db47-003d-872c30e4d8bf
* Version Independent ID: 6f707aa5-21b5-d508-3750-a9ccde1ffb34
* Content: [azure.eventhub.aio.EventHubConsumerClient class](https://docs.microsoft.com/zh-cn/python/api/azure-eventhub/azure.eventhub.aio.eventhubconsumerclient?view=azure-python#feedback)
* Content Source: [docs-ref-autogen/azure-eventhub/azure.eventhub.aio.EventHubConsumerClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-eventhub/azure.eventhub.aio.EventHubConsumerClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by YalinLi0312** [comment]
@HuaqiongWu Thanks for your feedback, we'll investigate asap.

**Comment by yunhaoling** [comment]
Hey @HuaqiongWu , `starting_position` is taking either of the following three forms:
- event offset (str)
- event sequence number (int)
- enqueued time (datetime)

If you want to receive message from certain create(enqueue) time, you could pass a datetime object as the parameter of starting_position:

```python
consumer_client.receive(..., starting_position=datetime.datetime())
```

please be aware that it should be a UTC time.

**Comment by yunhaoling** [comment]
as per our oob discussion, filter by creation time (not enqueued time) is not supported.
EventData.properties could be utilized to store the creation time information and do custom filtering upon receiving events.

I'm closing this issue now
