### ISSUE TITLE
resolve dependency issue with sphinx doc generation and m2r

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#22019]
Seeing this error in the "Generate Docs" step of CI:

```
sphinx run-test: commands[0] | /mnt/vss/_work/1/s/sdk/core/azure-mgmt-core/.tox/sphinx/bin/python /mnt/vss/_work/1/s/sdk/core/azure-mgmt-core/../../../eng/tox/prep_sphinx_env.py -d /mnt/vss/_work/1/s/sdk/core/azure-mgmt-core/.tox/dist -t /mnt/vss/_work/1/s/sdk/core/azure-mgmt-core
Traceback (most recent call last):
  File "/mnt/vss/_work/1/s/sdk/core/azure-mgmt-core/../../../eng/tox/prep_sphinx_env.py", line 11, in <module>
    from m2r import parse_from_file
  File "/mnt/vss/_work/1/s/sdk/core/azure-mgmt-core/.tox/sphinx/lib/python3.6/site-packages/m2r.py", line 59, in <module>
    class RestBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```

Example build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1231280&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=651a14cc-88df-515d-1311-e0e8b23b578a

`m2r` is used in the tox sphinx env and depends on a library called [mistune](https://pypi.org/project/mistune/).

https://github.com/Azure/azure-sdk-for-python/blob/76c8696cde09eaf705dce7b27c36d5f6a18fcac5/eng/tox/tox.ini#L145-L155

 `mistune` released a new package, 2.0.0, which appears to have breaking changes which are failing our CI.

**Comment by kristapratico** [comment]
For now, we're pinning `mistune` to <2.0.0 here:

https://github.com/Azure/azure-sdk-for-python/blob/02adf816c140bf63ae3de94e72899d25047caeaa/eng/tox/tox.ini#L145-L156

**Comment by ilCatania** [comment]
Thank you for reporting this, I had the same issue and pinning `mistune` also worked for me

**Comment by scbedd** [comment]
Additional fix commited by Krista [here](https://github.com/Azure/azure-sdk-for-python/pull/23132). Closing.
