### ISSUE TITLE
highlight_fields parameter in cognitive search documentation is incorrect

### ISSUE THREAD

**Issue by thomasbird** [Azure/azure-sdk-for-python#22015]
The documentation on the highlight_fields parameter is incorrect. It does not take a list of strings but a single string with comma separated field names as described here: https://docs.microsoft.com/en-us/rest/api/searchservice/search-documents#query-parameters

It would also be useful to note here that if you want to highlight the field `{'dict': {'value': 123 }}` you can specify this with highlight_fields='dict/value'

Thanks generally for the great tools!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d307f6-e957-5635-6a9e-1e6a7bae8a5d
* Version Independent ID: 5e6245e9-82c2-7043-e7c4-b3fcefd1b46f
* Content: [azure.search.documents.SearchClient class](https://docs.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.searchclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-search-documents/azure.search.documents.SearchClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-search-documents/azure.search.documents.SearchClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by tjprescott** [comment]
@thomasbird did you attempt to use `highlight_fields` with a list of strings and it didn't work?

**Comment by thomasbird** [comment]
Yes, it seems to take a string with fields separated by commas as discussed in the rest document, not the list as the python documentation seems to suggest.

**Comment by tjprescott** [comment]
Hi @thomasbird thanks for reporting this--this has been corrected in the code. The way our releases work, the docs for the GA library won't be updated until the next GA release (Q1 '22), but it does appear correctly if you choose the Preview dropdown. I will leave this issue open for tracking until the next GA release. 

Thanks again!
