### ISSUE TITLE
key vault get_secrets ignores maxresults argument

### ISSUE THREAD

**Issue by ddavtian** [Azure/azure-sdk-for-python#2201]
Using the latest version of azure-mgmt-keyvault (0.40.0)

The vault currently has `6 secrets`, when I pass maxresults of 1 or any other number it's ignored and the full set of 6 are returned.

    vault_url = 'https://xxx-int-vault.vault.azure.net/'
    try:
        akv = azure_utils.AzKeyVault()
        secrets = list(akv.az_kv_client.get_secrets(vault_url, maxresults=1))
        print(secrets)
    except Exception as e:
        return False, repr(e)

The full set of `6` are returned instead of just `1`

**Comment by lmazuel** [comment]
@schaabs ?

**Comment by lmazuel** [comment]
Closing this issue, I'm sorry we weren't able to address it in a timely manner. Since this issue was created, we made stable releases of KV that should have this fixed:
https://pypi.org/project/azure-keyvault-secrets/

Feel free to open a new issue if necessary.
