### ISSUE TITLE
Support Cosmos partial update

### ISSUE THREAD

**Issue by EpicWink** [Azure/azure-sdk-for-python#22033]
Support [Cosmos DB partial document update](https://docs.microsoft.com/en-us/azure/cosmos-db/partial-document-update)

I suggest supporting both strings and SDK-provided enumerations for the values of operations' `op` (eg `{"op": "set", ...}` and `{"op": azure.cosmos.PartialUpdateOperation.set, ...}`)

**Comment by gahl-levy** [comment]
Hi! Thanks for flagging this. This is on our roadmap. Happy to provide updates on this whenever you want to check in the future.

**Comment by angusrw** [comment]
@gahl-levy  has there been any progress on this / when can we expect this feature to be ready?

**Comment by gahl-levy** [comment]
Hi @angusrw. This feature is on our roadmap, but we don't have an ETA just yet unfortunately.

**Comment by clrogers2** [comment]
Does this feature have a timeline yet?

**Comment by kushagraThapar** [comment]
@clrogers2 - this is currently planned in the ongoing semester, and is scheduled to be done by March 2023.

**Comment by aldc-seanogrady** [comment]
Is this still planned for March '23?  My team has plans to update our product with this functionality as soon as available.

**Comment by angusrw** [comment]
Is there any update on when this will be finished/live?

**Comment by PrithviKambhampati** [comment]
Is there any update on this feature?

**Comment by AbhinavDAIICT** [comment]
This feature is still in our roadmap and we are targeting for July'23

**Comment by simorenoh** [comment]
Version 4.4.0b1 is out and addresses this, thank you! https://pypi.org/project/azure-cosmos/4.4.0b1/
