### ISSUE TITLE
[BUG Bash] azure-storage-blob - no mention of the upcoming Python 2.7 deprecation

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-python#22046]
Sounds like we really want to get that out there for people since it's coming up quick:

https://pypi.org/project/azure-storage-blob/

**Comment by tasherif-msft** [comment]
I put out a PR for this disclaimer https://github.com/Azure/azure-sdk-for-python/pull/22246 - feel free to review
