### ISSUE TITLE
[storage-queue] AAD auth sample should use DefaultAzureCredential

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#22056]
The other languages use DefaultAzureCredential in the AAD sample and I think it makes sense to follow suit in Python.

https://github.com/Azure/azure-sdk-for-python/blob/78e22ebd91587ad53a0abe49d1346bc262afb140/sdk/storage/azure-storage-queue/samples/queue_samples_authentication.py#L68-L84

**Comment by jalauzon-msft** [comment]
We are actually in a mixed state here:

- .NET uses `ClientSecretCredential` in the auth sample but `DefaultAzureCredential` in other samples
- Typescript uses `DefaultAzureCredential` but limits it by requiring the environment variables to be set
- Java doesn't seem to have an AAD auth sample?
