### ISSUE TITLE
[storage-queue] update supported python versions

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#22059]
Currently we state that python versions 2.7 and 3.5 or later are supported.
We dropped 3.5 support already and will drop 2.7 come January. The docs should be updated to reflect this and a disclaimer about ending 2.7 support should be added to the README like here:

https://github.com/Azure/azure-sdk-for-python#disclaimer

**Comment by tasherif-msft** [comment]
I put out a PR for this disclaimer https://github.com/Azure/azure-sdk-for-python/pull/22246 - feel free to review
