### ISSUE TITLE
Incorrect type in docstring

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#22051]
Sphinx do not use `typing`, but a more classical system, with built-in types separted with `or`

Example, this is incorrect:
https://github.com/Azure/azure-sdk-for-python/blob/3fdbaa75e5ef2cd9f0151a71992d50d0c7820739/sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py#L69-L82

Should be more:
```
    :type body: str or bytes
    :keyword dict[str,any] application_properties: The user defined properties on the message.
    :keyword dict[str, any] session_id: The session identifier of the message for a sessionful entity.
```

Can can add `or None` if the optionality matters, but we should clarify it in the text.

**Comment by swathipil** [comment]
Need to check if Dict arguments should be changed to Mapping. For example: check if 
`application_properties` can take type Mapping as argument: https://github.com/Azure/azure-sdk-for-python/blob/e2b5852deaef04752c1323d2ab0958f83b98858f/sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py#L71

**Comment by swathipil** [comment]
question for Laurent: will we always have to stick to sphinx rules (i.e. dict over Dict, etc.)? Or will we ever switch to something else so that we have more control over what the types look like in the docs?

**Comment by lmazuel** [comment]
Short version: just keep it simple and use dict
Long version: you can write anything you want as long as you don't use space, and use `[]` for generics and `or`
```
Optional[Mapping[str,str]]
dict[str,str] or None
```

But rational is docstring are NOT typing, so you don't need to restrain yourself to typing, just try to bring clarity for doc reader

**Comment by swathipil** [comment]
also fix incorrectly rendering docs here: https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebussender?view=azure-python#azure-servicebus-servicebussender-send-messages

**Comment by swathipil** [comment]
Figure out how to add Python 3 typehints to `BaseSession` in `_servicebus_session.py` so that sync and async Sessions constructor `receive` keyword takes the corresponding sync/async `ServiceBusReceiver`.

**Comment by swathipil** [comment]
fix pylance error when `# type: ignore` is removed from `eventhub/_pyamqp/_transport.py` line 719 (`except (WebSocketTimeoutException, ...) as exc:`
