### ISSUE TITLE
[BUG Bash] [Container Registry] README should link to Python version of identity and not .NET

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk-for-python#22082]
**Describe the bug**
README links to the .NET version of identity:

![python_identity](https://user-images.githubusercontent.com/6074665/145304621-0769763c-fc9d-445f-916a-a9b7d2e62fef.png)

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by YalinLi0312** [comment]
Fixed.
