### ISSUE TITLE
{app_id_uri}/{scope} fails on get_token() for AzureCliCredential

### ISSUE THREAD

**Issue by gharryg** [Azure/azure-sdk-for-python#22080]
- **Package Name**: azure-identity
- **Package Version**: 1.7.1
- **Operating System**: macOS 12.0.1
- **Python Version**: 3.9.9

**Describe the bug**
Using .get_token(scope) on AzureCliCredential only works when the "scope" provided is just the {app_id_urI} while other credential types (like VisualStudioCodeCredential) expect the full {app_id_uri}/{scope} format. This prevents me from using DefaultAzureCredential since .get_token({app_id_uri}/{scope}) will fail in some environments and succeed in others.

**To Reproduce**
Assuming that you are logged in through Azure CLI and through Visual Studio Code:
```python
from azure.identity import AzureCliCredential, VisualStudioCodeCredential

credential = VisualStudioCodeCredential()
credential.get_token('https://graph.microsoft.com/User.Read')   # with scope -> OK

credential = AzureCliCredential()
credential.get_token('https://graph.microsoft.com')             # without scope -> OK
credential.get_token('https://graph.microsoft.com/User.Read')   # with scope -> FAIL (see output below)
```
The output of the failed get_token(scope) call is:
```
AzureCliCredential.get_token failed: Please run 'az login' to set up an account
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 141, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource https://graph.microsoft.com/User.Read']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/azure/identity/_internal/decorators.py", line 30, in wrapper
    token = fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 73, in get_token
    output = _run_command(command)
  File "/usr/local/lib/python3.9/site-packages/azure/identity/_credentials/azure_cli.py", line 147, in _run_command
    raise CredentialUnavailableError(message=NOT_LOGGED_IN)
azure.identity._exceptions.CredentialUnavailableError: Please run 'az login' to set up an account
```
I am logged in through Azure CLI. Running the same command displayed in the error above (and the one with no scope) produces the following:
```
$ az account get-access-token --output json --resource https://graph.microsoft.com/User.Read 
AADSTS500011: The resource principal named https://graph.microsoft.com/User.Read was not found in the tenant named {tenant_name}. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
```
```
$ az account get-access-token --output json --resource https://graph.microsoft.com
{
  "accessToken": "blah blah blah...
```
As I said above, it seems like this behavior defeats the convenience of DefaultAzureCredential since the following would (AFAIK) succeed for all credential types _except_ where Azure CLI is the only available type:
```python
from azure.identity import DefaultAzureCredential

credential = DefaultAzureCredential()
credential.get_token('https://graph.microsoft.com/User.Read')   # for Azure CLI -> FAIL; for other credential types -> OK
```

**Expected behavior**
The format of {app_id_uri}/{scope} passed to get_token(scope) for AzureCliCredential should return the same result as other credential types.

**Additional context**
It seems like the problem lives [here](https://github.com/Azure/azure-sdk-for-python/blob/f3c07f70238d85f2df23d5a9049e30d115ac019c/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L30) and [here](https://github.com/Azure/azure-sdk-for-python/blob/f3c07f70238d85f2df23d5a9049e30d115ac019c/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L68). Why convert the scope to a resource and use `--resource` when the scope could be passed directly to `--scope`? When I run the Azure CLI command manually with `--scope` and the full {app_id_uri}/{scope}, it seems to work as expected.

**Comment by xiangyan99** [comment]
@gharryg Thanks for your feedback.

Sorry I don't quite understand your request.

It is by design AzureCliCredential.get_token('https://graph.microsoft.com/User.Read') fails. (Because az account get-access-token --output json --resource https://graph.microsoft.com/User.Read does fail).

Do you mean you want AzureCliCredential.get_token('https://graph.microsoft.com/User.Read') to turn into AzureCliCredential.get_token('https://graph.microsoft.com/') automatically (I have concerns on this) or you want to skip the AzureCliCredential in DefaultAzureCredential when you want to use the scope like 'https://graph.microsoft.com/User.Read'?
