### ISSUE TITLE
[BUG Bash] [Container Registry] use login_server instead of account_url

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk-for-python#22081]
**Describe the bug**
The code to instantiate the client in the readme file defines a variable named `account_url`. However, when I created the CR account in az CLI, it was named `loginServer` instead:

![loginServer](https://user-images.githubusercontent.com/6074665/145303705-a8c081a5-69fe-4b03-bdc7-40881b92a75d.png)

The portal also uses `loginServer`:

![loginServerPortal](https://user-images.githubusercontent.com/6074665/145303974-cf20ea04-c338-4c67-b00b-360b2a9bc925.png)

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by YalinLi0312** [comment]
@deyaaeldeen Thanks for your check! `accout_url`(is changing to end_point in pr https://github.com/Azure/azure-sdk-for-python/pull/22219) is a string containing the `https://` prefix and the name of the `loginServer`.

**Comment by deyaaeldeen** [comment]
@YalinLi0312 Thanks for your work on this. I wonder if our customers can recognize `end_point` and `login_server` are synonyms though.
