### ISSUE TITLE
[BUG Bash] [Container Registry] Client docstring does not look ideal in VS code

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk-for-python#22083]
**Describe the bug**
This is what I see:

![client_intellisense](https://user-images.githubusercontent.com/6074665/145305389-87f5406f-3737-4e9d-bf9b-474958550722.png)

And I did not expect `:type credential` and `:keyword audience` to be on the same line.

Also, I see a value for the German cloud in the audience values list but I though it is obsolete now.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by YalinLi0312** [comment]
@deyaaeldeen Thanks for your review! 1. it is an issue in VSCode that does not show keyword argument in a separate line. 2. The sample audience value is consisting across languages now, I'll bring this question to our team when we are back from holiday.
