### ISSUE TITLE
[BUG Bash] [Container Registry] Empty sections in README

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk-for-python#22084]
**Describe the bug**
The Examples and Next steps sections are empty in the README:

![Azure-Container-Registry-client-library-for-Python-Microsoft-Docs](https://user-images.githubusercontent.com/6074665/145305892-8270c1f1-49da-47c4-ac0e-8258861f05b8.png)

Also, it mentions Form Recognizer.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by YalinLi0312** [comment]
Fixed.
