### ISSUE TITLE
How to turn 'Binary Copy' off when creating datasets

### ISSUE THREAD

**Issue by l-rushton** [Azure/azure-sdk-for-python#22103]
I am working on a project in which I need to create datasets in Azure data factory, so that a source dataset can be copied to a sink. I am confused as to how I can specify the 'Binary Copy' option to be false or off when the dataset is being created? Here is how I am specifying the type of dataset (dsOut_azure_blob), which then passes through to create_or_update:

`                dsOut_azure_blob = DatasetResource(properties=AzureBlobDataset(linked_service_name=ds_ls, folder_path=outputPath))
                
                outputDatasets.append(adf_client.datasets.create_or_update(rg_name, df_name, ds_filename, dsOut_azure_blob))`

The place that shows me that Binary Copy is on in the data factory:

<img width="1226" alt="Screenshot 2021-12-09 at 15 18 04" src="https://user-images.githubusercontent.com/89603800/145423879-003c9653-6424-4f0f-901f-173730c2d546.png">

I'm sure its just an extra parameter to be specified but I can't find any clues on the documentation. Any help would be greatly appreciated.

**Comment by SaurabhSharma-MSFT** [comment]
@l-rushton I believe you are looking into legacy dataset where `Binary Copy` option was available. For using Binary copy you can create a [Binary Dataset](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.binarydataset?view=azure-dotnet) instead of creating a [blob dataset](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.azureblobdataset?view=azure-dotnet). Please let me know if you have any other questions.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@l-rushton Please let me know if you have any questions.

**Comment by l-rushton** [comment]
@SaurabhSharma-MSFT thank you for getting back to me. I understand that creating a Binary dataset will have Binary copy enabled by default. My question is: why is binary copy enabled by default when I create a blob dataset, and is there a way to switch it off upon blob dataset creation? 

Thank you,
Louis

**Comment by SaurabhSharma-MSFT** [comment]
@l-rushton I do not think that binary will be enabled when creating a blob dataset.  How did you create the above blob dataset you have shared as image.  I don't think it is a new blob dataset you have created recently instead it is an older legacy dataset.  Please let me know if that's not the case.

**Comment by l-rushton** [comment]
@SaurabhSharma-MSFT I am creating the blob dataset with the following commands:

`dsOut_azure_blob = DatasetResource(properties=AzureBlobDataset(linked_service_name=ds_ls, folder_path=ds_path, file_name=ds_filename))`
`adf_client.datasets.create_or_update(rg_name, df_name, ds_filename, dsOut_azure_blob)`

So if I understand correctly the `properties=AzureBlobDataset()` part is legacy? If so, what would I put in its place in order to pass it into `adf_client.datasets.create_or_update()`  to create a blob dataset?

**Comment by SaurabhSharma-MSFT** [comment]
@l-rushton No, I did not mean AzureBlobDataset() as legacy.  I was referring to the image you have shared which has the Binary copy property and I believe that dataset is created before and not recently.

**Comment by l-rushton** [comment]
Sorry for the delayed response - you were right, the issue was coming from the pre existing datasets I was trying to import. This project has been put on hold for now, but thank you very much for your help!

All the best
