### ISSUE TITLE
Cosmos error to delete items

### ISSUE THREAD

**Issue by afonsolenzi** [Azure/azure-sdk-for-python#22154]
**Describe the bug**
I am trying to delete records from a container using azure databricks/python.
I am able to query the ids of the records but when i try to delete them i receive error message. 

When I do:

![image](https://user-images.githubusercontent.com/32559154/145887541-8599ed04-3f69-4278-a8d8-120f314112cc.png)

Then i receive:

`
CosmosHttpResponseError: (BadRequest) Message: {"errors":[{"severity":"Error","location":{"start":43,"end":47},"code":"SC1011","message":"Syntax error, invalid numeric value token '43a4'."}]}
ActivityId: 755998f8-c21f-4f73-868b-c1195f377c97, Microsoft.Azure.Documents.Common/2.14.0
Code: BadRequest
Message: Message: {"errors":[{"severity":"Error","location":{"start":43,"end":47},"code":"SC1011","message":"Syntax error, invalid numeric value token '43a4'."}]}
ActivityId: 755998f8-c21f-4f73-868b-c1195f377c97, Microsoft.Azure.Documents.Common/2.14.0
`

**To Reproduce**
First of all i query the container and create a dictionary os all Ids,
![image](https://user-images.githubusercontent.com/32559154/145887634-5c96676d-519e-4841-b0bc-7d0b6c3f753d.png)

then the my_dict is generated:

![image](https://user-images.githubusercontent.com/32559154/145887669-66b2d1c5-23c2-47fc-8707-bb216f5844ba.png)

the data in the container look likes this:

`    {
        "disc": 3,
        "points": 6,
        "capt": 1,
        "id": "c3877ac6-d51c-43a4-87ed-4c0dcdc6fa39",
        "_rid": "SSJ2AIS3UFyBhB4AAAAAAA==",
        "_self": "dbs/SSJ2AA==/colls/SSJ2AIS3UFw=/docs/SSJ2AIS3UFyBhB4AAAAAAA==/",
        "_etag": "\"0800f014-0000-0d00-0000-61b218940000\"",
        "_attachments": "attachments/",
        "_ts": 1639061652
    }`

Could you guys confirm if i am doing something wrong and is a bug? i am following as best as possible:
https://docs.microsoft.com/en-us/python/api/overview/azure/cosmos-readme?view=azure-python#delete-data

**Comment by yunhaoling** [comment]
thanks @afonsolenzi for reaching out, we'll investigate it ASAP.

**Comment by afonsolenzi** [comment]
i had to use this so this works in my case.

`#trying to delete by ids
x=-1
num = len(my_dict['id'])

for item in range(num):
  x=x+1
  ident = my_dict['id'][x]
  print(ident)
  try:
    print(ident)
    container.delete_item(ident, partition_key=ident)
  except:
    pass`

**Comment by afonsolenzi** [comment]
i would sugest to update the documentation with a easier approach to the task about deleting items in a container.
maybe is not a bug, but what is sugested in the docs doesnt work in my case.
