### ISSUE TITLE
[Test Proxy] Attempt to auto-update Docker image

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#22162]
Currently, if there's an existing `ambitious_azsdk_test_proxy` container, the `test_proxy` fixture will just [start that container](https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-sdk-tools/devtools_testutils/proxy_docker_startup.py#L132). This means that the version of the test proxy tool could be outdated if the container was created with an old image tag.

A new container will be created with the latest version if the existing container is deleted before the fixture is called, but this requires manual intervention. It would be ideal to either check the existing image tag of the container, or fetch the correct image each time the fixture is invoked. The latter solution could be minimally time-consuming if Docker is smart about recognizing that the container already exists with the same image tag.

**Comment by mccoyp** [comment]
After discussion with other language teams, it seems like the easiest solution would be to fetch an image tag from `/eng/common`  each time the test proxy is started up ([JS example](https://github.com/Azure/azure-sdk-for-js/blob/a47af26db471d30488112c1c2855c3ea6c9b6d07/common/tools/dev-tool/src/util/testProxyUtils.ts#L84)) instead of only doing so when an `ambitious-azsdk-test-proxy` container is absent. Docker won't re-fetch the image if we already have the tag cached, so it wouldn't inhibit performance unless there's a new tag present in the repo (which happens infrequently).

**Comment by ponopono0322** [comment]
According to the `eng/common/testproxy/target_version.txt` file, i deleted the previous version of the container and completed the code to create the required version of the docker image and container. Could you please check if it is the same as the intended result?

**Comment by mccoyp** [comment]
@ponopono0322 I'll take a look -- thanks so much for opening a PR!
