### ISSUE TITLE
MS Docs failing to publish

### ISSUE THREAD

**Issue by tasherif-msft** [Azure/azure-sdk-for-python#22170]
MS.Docs failing to publish - blocking storage releases
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1246915&view=logs&j=19b87903-f8bc-5cbb-22d9-4f6eb3469d8e&t=01c0d070-1636-5aed-84c3-1f03a1861eaf

**Comment by scbedd** [comment]
Resolved in [this PR](https://github.com/Azure/azure-sdk-for-python/pull/22171)
