### ISSUE TITLE
Retrieve list of advertised and learned routes from hub bgp connection

### ISSUE THREAD

**Issue by ksridhar57** [Azure/azure-sdk-for-python#22212]
- **Package Name**: azure-mgmt-network 
- **Package Version**: 19.1.0
- **Operating System**: Linux
- **Python Version**: 3.6.9

**Describe the bug**
I'm using the preview functionality of establishing bgp peer with a virtual hub router and would like to list the learned and advertised routes. I'm using the following code to test - 

        bgp_conn_oper = network_mgmt_client.virtual_hub_bgp_connections.begin_list_advertised_routes(
            resource_group_name=resource_group,
            hub_name=vhub_name,
            connection_name=connection_name
        ).result()

        print(bgp_conn_oper)

The result I get is this - 
{'additional_properties': {'RouteServiceRole_IN_1': [], 'RouteServiceRole_IN_0': []}, 'value': None}

What is RouteServiceRole_IN_X indicate here? Are these the individual route tables, PeerRoute objects? What is the method to iterate through the peer route entries? 

Thanks!!

**Comment by yunhaoling** [comment]
@ksridhar57 thanks for reaching out, we'll investigate it ASAP.

**Comment by msyyc** [comment]
Hi @ksridhar57, `network_mgmt_client.virtual_hub_bgp_connections.begin_list_advertised_routes` is generated with [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/virtualWan.json#L4857) and here is the related [doc](https://docs.microsoft.com/en-us/rest/api/virtualwan/virtual-hub-bgp-connections/list-advertised-routes). To answer your question about the meaning of detailed parameter, it needs domain knowledge from service team.
