### ISSUE TITLE
Create/Update Hub BGP Connection

### ISSUE THREAD

**Issue by ksridhar57** [Azure/azure-sdk-for-python#22213]
- **Package Name**: azure-mgmt-network
- **Package Version**:  19.1.0
- **Operating System**: Linux
- **Python Version**: 3.6.9

**Describe the bug**
Unable to create or update a BGP peer resource of virtual HUB. The following is the code used -

DEFAULT_TRANSIT_VNET_CONN_NAME = "Prisma-SD-WAN-Transit-VNET_Connect"

`        network_mgmt_client.virtual_hub_bgp_connection.begin_delete(
            resource_group_name=resource_group,
            virtual_hub_name=vhub_name,
            connection_name=peer
        ).wait()
        
        vnet_conn_id = '/subscriptions/' + azure_subscription_id + '/resourceGroups/' + resource_group + '/providers/Microsoft.Network/virtualHubs/' + vhub_name + '/hubVirtualNetworkConnections/' + DEFAULT_TRANSIT_VNET_CONN_NAME
        print(vnet_conn_id)

Prints: /subscriptions/440774a6-0e13-4c66-ac90-007c493478ba/resourceGroups/CGXTestRG1-vHub/providers/Microsoft.Network/virtualHubs/Prisma-SD-WAN-vHub/hubVirtualNetworkConnections/Prisma-SD-WAN-Transit-VNET_Connect

        bgp_peer_parameters = network_models.BgpConnection(
            id=vnet_conn_id,
            name=DEFAULT_TRANSIT_VNET_CONN_NAME,
            peer_asn=300
            peer_ip='10.5.8.12'
        )

            bgp_peer_resource_oper = network_mgmt_client.virtual_hub_bgp_connection.begin_create_or_update(
                resource_group_name=resource_group,
                virtual_hub_name="Prisma-SD-WAN-vHub",
                connection_name="Prisma-SD-WAN-vIon1-Peer",
                parameters=bgp_peer_parameters
            )

                bgp_peer_resource_oper.wait()`

The hub virtual network connection named Prisma-SD-WAN-Transit-VNET_Connect has been provisioned successfully.  

The error I get is:
{'err': HttpResponseError('(HubBgpConnectionMustReferenceFullyProvisionedHubVirtualNetworkConnection) HubBgpConnection /subscriptions/440774a6-0e13-4c66-ac90-007c493478ba/resourceGroups/CGXTestRG1-vHub/providers/Microsoft.Network/virtualHubs/Prisma-SD-WAN-vHub/bgpConnections/Prisma-SD-WAN-vIon1-Peer must reference existing provisioned HubVirtualNetworkConnection.\nCode: HubBgpConnectionMustReferenceFullyProvisionedHubVirtualNetworkConnection\nMessage: HubBgpConnection /subscriptions/440774a6-0e13-4c66-ac90-007c493478ba/resourceGroups/CGXTestRG1-vHub/providers/Microsoft.Network/virtualHubs/Prisma-SD-WAN-vHub/bgpConnections/Prisma-SD-WAN-vIon1-Peer must reference existing provisioned HubVirtualNetworkConnection.',)}

Any advise? 

Thanks!

**Comment by yunhaoling** [comment]
@ksridhar57 thanks for reaching out, we'll investigate it ASAP.

**Comment by msyyc** [comment]
According to the log info, it seems that some of your parameter is not valid for service. It needs domain knowledge from service team to help.

**Comment by JeffGiroux** [comment]
I ran into same issue on terraform. What is the status of the fix?

https://github.com/hashicorp/terraform-provider-azurerm/issues/17872

**Comment by xiangyan99** [comment]
Can you check the latest azure-mgmt-network library to see if it is fixed?
