### ISSUE TITLE
ACR audience should be optional with a default value, and not required

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#22229]
Today we need to write:
```python
client = ContainerRegistryClient(end_point, DefaultAzureCredential(), audience="https://management.azure.com")
```

Audience should be optional. Please check the right default in other languages.

**Comment by YalinLi0312** [comment]
Will update until we have a default ACR audience from the service.

**Comment by pallavit** [comment]
I vaguely remember this was a conscious call we had made at the time but I do not recollect the reason :|. I believe some of our SDKs today do have a default especially for national cloud support does it makes sense for us to do the same for ACR as well?
/cc: @annelo-msft , @lmolkova

**Comment by lmolkova** [comment]
ACR for Java defaults to public cloud. But [it's required](https://github.com/Azure/azure-sdk-for-net/blob/7e822ad7ddc2164d51fe81dc0449b58c0f4bed81/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/ContainerRegistryClient.cs#L75) on .NET (it was introduced here https://github.com/Azure/azure-sdk-for-net/pull/23141, it seems there was a need to postpone choosing default value).

BTW I never saw another SDK that **requires** an audience, so let's try to make it optional unless there is a string reason not to. And of course, make it consistent.

**Comment by lmolkova** [comment]
Found the guideline: https://azure.github.io/azure-sdk/policies_support.html#azure-clouds
> By default, the Azure libraries are configured to connect to the Global Azure Cloud.
