### ISSUE TITLE
Outdated document limitation link for Text Analytics 

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#22231]
I'm trying to analyze a document that turned out to be too big, but the link ( https://aka.ms/text-analytics-data-limits) provided in the error message about data limitations takes me to[ this doc](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/overview#data-limits), which mentions nothing about limitation:

```py
response = text_analytics_client.analyze_sentiment([TextDocumentInput(id=row.HtmlUrl, text=row.commentThread, language="en")])
```

Error message:
```
Error: InvalidDocument - A document within the request was too large to be processed. Limit document size to: 5120 text elements. For additional details on the data limitations see https://aka.ms/text-analytics-data-limits
```

**Comment by kristapratico** [comment]
Hey @lilyjma this aka link is owned by the service team. I'll follow up with them to get it updated.

**Comment by assafi** [comment]
@lilyjma We are working on a new article following recent documentation change. 
Specifically, for sentiment analysis if you'd like to submit documents larger than 5120 characters you can use the async API that supports up to 125k characters per document. See more [here](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/concepts/use-asynchronously#data-limits).
