### ISSUE TITLE
Enable backup for vm : SDK behavior is different from API for backup_protectable_items.list

### ISSUE THREAD

**Issue by anotherancientalien** [Azure/azure-sdk-for-python#22232]
Hi,
I use SDK for enabling backup for vm:

```
client = RecoveryServicesBackupClient(credentials, subscription_id)
policy = client.protection_policies.get(vault_name, resource_group_name, backup_policy_name)


result =client.backup_protectable_items.list(
    vault_name=vault_name,
    resource_group_name=resource_group_name,
    filter=filter_string
)
```
The result for a new created vm available after 30 min. 
[But with API](https://docs.microsoft.com/en-us/azure/backup/backup-azure-arm-userestapi-backupazurevms), the new created machine is available for protection.

What is wrong with `backup_protectable_items` in SDK?

Any advice would be appreciated.

Best

**Comment by anotherancientalien** [comment]
I have found that refresh method solves the issue. But I'm not sure.

`response = client.protection_containers.refresh(
    vault_name, resource_group_name, fabric_name)`

**Comment by yunhaoling** [comment]
thanks for reaching out @anotherancientalien , we'll investigate it ASAP.

**Comment by BigCat20196** [comment]
hi @anotherancientalien, After my investigation, you may have used the wrong operation.

If you want to view protected items, you should use `backup_protected_items.list()` instead of `backup_protectable_items()`.

Note the difference between `protected` and `protected`.

FYI:
```
result =client.backup_protected_items.list(
    vault_name=vault_name,
    resource_group_name=resource_group_name,
    filter=filter_string
)
```
Hope this can unblock you.

**Comment by anotherancientalien** [comment]
Hi @BigCat20196 

I appreciate your help. But I'm looking for unprotected items. Seems that `client.backup_protected_items.list` gives the protected items.

Best
Jasmine

**Comment by msyyc** [comment]
Hi @anotherancientalien , according to [doc](https://docs.microsoft.com/en-us/azure/backup/backup-azure-arm-userestapi-backupazurevms#discover-unprotected-azure-vms), it seems that rest api `refreshContainers` meets your requirements and its related sdk operation is `client.protection_containers.refresh`.

one more point: Python SDK is generated automatically with [swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/recoveryservicesbackup/resource-manager). I think your question is more about which and how to use the right rest api. It needs much domain knowledge while we don't have it as SDK team. So I advise you to make issue for service team in [repo](https://github.com/Azure/azure-rest-api-specs/issues). As SDK team, we could provide related SDK operation once you make sure which rest api you needs.

**Comment by anotherancientalien** [comment]
Hi @msyyc , I appreciate your kind help.

Best
