### ISSUE TITLE
ServiceBusError: Handler failed: Authorization timeout when trying to send a message from an Python Azure Function

### ISSUE THREAD

**Issue by viktoreinars** [Azure/azure-sdk-for-python#22236]
- **azure-servicebus**: 
- **7.3.4**: 
- **Azure Function within Docker container- Linux**:
- **3.9**: 

**Describe the bug**
When running an Azure Function that may take 5-10 minutes we are receiving an Authorization Timeout when trying to send a message out to a Topic.

Stack trace:
Exception while executing function: Functions.PreprocessingJobTrigger Result: Failure
Exception: ServiceBusError: Handler failed: Authorization timeout..
Stack:   File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 398, in _handle__invocation_request
    call_result = await self._run_async_func(
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 617, in _run_async_func
    return await ExtensionManager.get_async_invocation_wrapper(
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 147, in get_async_invocation_wrapper
    result = await function(**args)
  File "/home/site/wwwroot/PreprocessingJobTrigger/__init__.py", line 167, in main
    await sb.send_complete_message(jsonStr)
  File "/home/site/wwwroot/PreprocessingJobTrigger/services/ServiceBusSend.py", line 21, in send_complete_message
    async with sender:
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 169, in __aenter__
    await self._open_with_retry()
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 370, in _open_with_retry
    return await self._do_retryable_operation(self._open)
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 250, in _do_retryable_operation
    last_exception = await self._handle_exception(exception)
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 198, in _handle_exception
    raise error
 

**To Reproduce**
1. Not sure really

**Expected behavior**
The message would be sent out to the topic.

**Screenshots**
It seems that the function tried running once and then failed due to a MessageLockLostException. Next error that comes up is the Authorization timeout error.
Application insights:
![image](https://user-images.githubusercontent.com/3970209/146795451-c36da0d7-0669-461a-afd2-4cd0c14a7bd0.png)

**Additional context**
The code for sending the message:

init.py
```
jsonStr = json.dumps(job_completed_event.__dict__, default=str)
sb = ServiceBusSend()
sb.initialize_client_connection()
await sb.send_complete_message(jsonStr)
```

ServiceBusSend
```
def initialize_client_connection(self):
        self.conn_str = os.environ["PreProcessingEventBusConnectionString"]
        self.topic_name = os.environ["PreProcessingEventBusTopicName"]
        self.servicebus_client = ServiceBusClient.from_connection_string(conn_str=self.conn_str, logging_enable=True)

async def send_complete_message(self, job_json):
    job_out = ServiceBusMessage(job_json)
    job_out.subject = "JobStageComplete"
    async with self.servicebus_client:
        sender = self.servicebus_client.get_topic_sender(topic_name=self.topic_name)
        async with sender:
            await sender.send_messages(job_out)
```

**Comment by yunhaoling** [comment]
thanks for reaching out @viktoreinars , could you explain a bit more on `take 5-10 minutes we are receiving an Authorization Timeout`.

- Is it that the send operation would hang 5-10 minutes before error is raised?
- or it is that the azure function stays idle 5 -1 0 minutes before sending a message?


also would retry the sending operation by yourself help mitigate the issue?

**Comment by viktoreinars** [comment]
Thanks for the reply @yunhaoling. 

The Azure Function itself is processing some data and that can take 5-10 minutes. Not sure if it matters at all in this case but wanted to let you know in case it is important.

I can try adding some retry functionality to the send but since this is an Authorization error it´s not likely to go away just because we retry?

**Comment by kashifkhan** [comment]
@viktoreinars sorry for the delay in responding to this. We have released a new version of service bus that is using the all-new python based AMQP library. There have been a lot of fixes since then, so I would recommend upgrading to the latest version and seeing if this problem still exists.
