### ISSUE TITLE
Getting error "ConnectionResetError: [Errno 104] Connection reset by peer" when checking if directory exists in the azure file share

### ISSUE THREAD

**Issue by sorin-bolos** [Azure/azure-sdk-for-python#22244]
- **Package Name**: azure-storage-file
- **Package Version**: latest
- **Operating System**: Docker container Redhat UBI 8
- **Python Version**: 3.8

**Describe the bug**
Getting error "ConnectionResetError: [Errno 104] Connection reset by peer" when checking if directory exists in the azure file share
The error happens randomly but fairly often.
The stack trace also says `Max retries exceeded` but I cannot tell how many retries were made if any. As the caller of `azure.storage.file.FileService.exists()` I cannot control the retry policy.

**Expected behavior**
The client should be able to check if a directory exists without any errors

**Comment by yunhaoling** [comment]
thanks for reaching out @sorin-bolos , we will investigate it ASAP.

**Comment by tasherif-msft** [comment]
Hi @sorin-bolos  thanks for opening the issue. This is a known issue that we are investigating and having discussions across languages to discuss what the best solution is. I will update you once I have more information!

**Comment by vincenttran-msft** [comment]
Hi @sorin-bolos Sorin, thanks for your inquiry about this issue. I can see that when you created this post, you were using the `azure-storage-file` package, which has now been [replaced ](https://github.com/Azure/azure-storage-python#readme)by `azure-storage-file-share`.

I have gone ahead and written a test script to check if directory exists with our new package and did not find any connection reset issues after letting the script run for ~15 minutes.

With that being said, I am going to mark this issue as resolved for the time being. Please reach out if you have any questions!

Thanks!
