### ISSUE TITLE
'base_url' incorrectly marked as required argument for CosmosDBManagementClient

### ISSUE THREAD

**Issue by duanqn** [Azure/azure-sdk-for-python#22243]
`base_url` was marked as `required` on the page. It took me an hour to figure out what to put in. And in the end it turns out I can leave it as empty.

I still don't understand the purpose of this argument, but please at least mark it as optional!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 151742ca-142e-bf48-6009-f6e7960ceefe
* Version Independent ID: 3db06378-6c32-1ba2-0d21-ee89e5f59dd0
* Content: [azure.mgmt.cosmosdb.CosmosDBManagementClient class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.cosmosdbmanagementclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.CosmosDBManagementClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.CosmosDBManagementClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by yunhaoling** [comment]
thanks for your feedback @duanqn! we'll improve the doc experience ASAP

**Comment by PramodValavala-MSFT** [comment]
@duanqn the `base_url` argument needs to be set when working with [sovereign clouds](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-sovereign-domain?view=azure-python) which defaults to Azure Public Cloud. While required, that signature does mention a default value of `None`, which is why you don't have to pass this in.

Also, it looks like this is the case for most docs. @lmazuel @yunhaoling @msyyc Could you share any insights on this?

**Comment by msyyc** [comment]
Hi, according to latest [code](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/_cosmos_db_management_client.py#L133), `base_url` is optional. It seems that the doc is out of date and I think we need to contact doc team to update. Thanks for your feedback!

**Comment by PramodValavala-MSFT** [comment]
@duanqn This issue is being tracked internally

**Comment by duanqn** [comment]
> @duanqn the `base_url` argument needs to be set when working with [sovereign clouds](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-sovereign-domain?view=azure-python) which defaults to Azure Public Cloud. While required, that signature does mention a default value of `None`, which is why you don't have to pass this in.
> 
> Also, it looks like this is the case for most docs. @lmazuel @yunhaoling @msyyc Could you share any insights on this?

Yes, I noticed the default value of `None`, but only after I wasted an hour on this. I don't quite understand the logic of "required with a default value". It's simply optional, and we should document as optional.
Thanks for the explanation about this argument. Some examples about this argument would be helpful (i.e. the exact URL to put in). If this is an inherited argument perhaps we can link to its document.

**Comment by msyyc** [comment]
If users don't put this parameter in, it will be set default value: `https://management.azure.com`([example](https://github.com/Azure/azure-sdk-for-python/blob/ead9b83e349101a682c81d35be81e9df78c5c3ef/sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/_cosmos_db_management_client.py#L138)). `base_url` is mainly used for authentication and resource management. So most azure users, they don't need to input it.
