### ISSUE TITLE
Incomplete documentation of class azure.containerregistry.ArtifactManifestProperties

### ISSUE THREAD

**Issue by flaudarin-365talents** [Azure/azure-sdk-for-python#22250]
This documentation page is incomplete and not up-to-date.
"_Delete Permissions for an artifact_" was copy-pasted to every permission.
Attribute `size` is an `int`. Sometimes attribute `tags` is `None`.
I got instances of this class by calling `ContainerRegistryClient().list_manifest_properties(registry)`.

Thank you and merry Christmas!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e9e99d-f0b3-7940-9bd5-3e1fc87b90ee
* Version Independent ID: 7618b866-4237-f1f6-ecef-cf643af1ad17
* Content: [azure.containerregistry.ArtifactManifestProperties class](https://docs.microsoft.com/en-us/python/api/azure-containerregistry/azure.containerregistry.artifactmanifestproperties?view=azure-python-preview)
* Content Source: [preview/docs-ref-autogen/azure-containerregistry/azure.containerregistry.ArtifactManifestProperties.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/preview/docs-ref-autogen/azure-containerregistry/azure.containerregistry.ArtifactManifestProperties.yml)
* GitHub Login: @VSC-Service-Account

**Comment by yunhaoling** [comment]
Merry Christmas and thanks @flaudarin-365talents for your feedbacks!
We'll investigate it ASAP and try to improve the doc experience!

**Comment by flaudarin-365talents** [comment]
Hello @yunhaoling !
There are actually many other incomplete class documentation pages. When reading the [changelog](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/containerregistry/azure-containerregistry/CHANGELOG.md) I guess the reason is that this package is quite new (1st release is less than 1 year old). I know that writing docs and keeping it up-to-date is time consuming.
Have a good day.
Thanks

**Comment by YalinLi0312** [comment]
Hi @flaudarin-365talents , thanks for reaching us! 
We have addressed a lot of docstrings in our first GA 1.0.0 which included this ""Delete Permissions for an artifact" was copy-pasted to every permission." For the rest two points, I do not completely understand the issue, could you provide more?

Thanks

**Comment by flaudarin-365talents** [comment]
Hello @YalinLi0312 ,
Thanks for your reply. I was referring to this page:
https://docs.microsoft.com/en-us/python/api/azure-containerregistry/azure.containerregistry.artifactmanifestproperties?view=azure-python-preview
As you can see, the definition of these variables is a copy/paste of "_Delete Permissions for an artifact_"
![image](https://user-images.githubusercontent.com/93928368/151830105-538f4712-19a2-4028-add9-8d3d2db43b44.png)
These ones:
![image](https://user-images.githubusercontent.com/93928368/151830582-d2923707-0a32-4814-9920-ebc0fb3bdb7d.png)
should be
```python
size: int
tags: Optional[List[str]]
```
as when there is no tags the value of `tags` is `None` and not `[]`.

Thank you.

**Comment by xiangyan99** [comment]
@YalinLi0312 Seems like this still repros in latest stable version. Please take a look.

**Comment by YalinLi0312** [comment]
Hi @flaudarin-365talents ,

The definition of `can_write`, `can_read`, `can_list` have updated in docs.microsoft.com. 
![image](https://user-images.githubusercontent.com/20915761/191099181-8da7f0e6-da32-47ee-bd4e-bd031cec3f58.png)

For `size` and `tags`, they have been addressed in our code, you'll see the updates in the portal once we published our next release.

Thanks
