### ISSUE TITLE
Deleting empty container with an immutable policy configured

### ISSUE THREAD

**Issue by tasherif-msft** [Azure/azure-sdk-for-python#22255]
https://github.com/Azure/azure-sdk-for-net/issues/26026

Portal is able to delete an empty container when immutability policy is set while the SDK throws:
```
azure.core.exceptions.HttpResponseError: The requested operation is not allowed as the container has a immutable storage with versioning enabled.
RequestId:c4314bb2-701e-006e-687b-f7188f000000
Time:2021-12-22T21:35:53.6672077Z
ErrorCode:ContainerImmutableStorageWithVersioningEnabled
Error:None
```
Need to investigate

**Comment by tasherif-msft** [comment]
Not a bug - use management plane to delete the container.

**Comment by dterei** [comment]
While not a bug, can the docs please be updated to inform people that the ARM APIs must be used rather than the storage APIs when there is an immutability policy set on the container? Otherwise it's very confusing when the container deletion fails despite the docs all claiming it should work....

**Comment by LarsKemmann** [comment]
I second @dterei's request - although in my case it's the .NET SDK giving this error - and the worst part is it is a spurious error: the container I'm trying to delete *doesn't* have an immutability policy set, it's a *different* container in the same account that has that immutability policy set (with version-level immutability support having been turned on at the account level).

**Comment by LarsKemmann** [comment]
I guess, for what it's worth, the portal is now giving me the same error. Which is really weird and makes no sense at all. Why would container A being protected in a WORM-enabled account mean that container B can't be deleted?
