### ISSUE TITLE
Azure Blueprint Operations

### ISSUE THREAD

**Issue by anotherancientalien** [Azure/azure-sdk-for-python#22254]
Hi,

Is there any package for blueprint operations (assign, user assigned managed identity) in sdk? Any advice would be appreciated.

Best

**Comment by yunhaoling** [comment]
hey @anotherancientalien , thanks for reaching out.

Could you help give some more detail of what blueprint operations you're looking for -- do you have links for that? this would help us triaging the issue, thanks!

**Comment by anotherancientalien** [comment]
Hello @yunhaoling,

[Create or update and list ](https://docs.microsoft.com/en-us/rest/api/blueprints/assignments/create-or-update)(user assigned)

Best
Yasemen

**Comment by marckhair** [comment]
Does not seem to have a relevant package for blueprints in the python sdk...

**Comment by navba-MSFT** [comment]
@anotherancientalien Apologies for the late reply. I am looking in to this issue. I will update this thread once I have more detail on this.

**Comment by navba-MSFT** [comment]
@anotherancientalien There are no plans to release Azure Blueprint Python SDK for the above operations. We are moving all Blueprint Assignment functionality to [Deployment Stacks](https://www.youtube.com/watch?v=-4E5DsC-RcU&t=1657s) and eventually we will have a Python SDK for that. Please let me know if you have any questions on this before we proceed with archival.

**Comment by anotherancientalien** [comment]
@navba-MSFT I appreciated your kind help.
