### ISSUE TITLE
[TestProxy] Variables and kwargs cannot be used in the same signature

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#22274]
If your test signature includes `**kwargs`, you cannot supply a `variables` signature param. Instead, the variables will be passed into the kwargs as a "variables" key.

The question is whether this is the desired behavior or not. If so, then it should be documented. If not, it should be changed. I would argue it should be changed, since right now you would have to pull the variables collection out of kwargs in order to return it (which is currently required for variables).

**Comment by mccoyp** [comment]
Tracked by https://github.com/Azure/azure-sdk-for-python/issues/22208
