### ISSUE TITLE
[Form Recognizer] "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.us), or have expired." in USGOV and China

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#22287]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the test [test_dac_analyze_prebuilts_from_url.py::TestDACAnalyzePrebuiltsfromUrlAsync::test_active_directory_auth](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url.py#L165), it runs failed and the error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1267612&view=logs&j=c9b636ae-c3c7-55c0-c769-7777f7222b9a&t=117f2755-ff68-5a46-ec6f-d3be490739f1):
![image](https://user-images.githubusercontent.com/57166602/147742701-547688cb-3b60-41e6-9a7e-94d7b8f5c29b.png)

**Error Track:**
Code [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/_configuration.py#L52):
![image](https://user-images.githubusercontent.com/57166602/147798574-1c48bbc1-a4ae-42ca-95b0-330650308d0f.png)

**Expected Behavior:**
Add different scopes for different clouds in Form Recognizer SDK.
The value of the scope in different clouds is follow:
Public cloud: https://cognitiveservices.azure.com/.default
UsGov cloud: https://cognitiveservices.azure.us/.default
China cloud: https://cognitiveservices.azure.cn/.default

@benbp, @jameszliao-msft, @lmazuel, @meeraharidasa , @mayurid, @catalinaperalta for notification.

**Comment by benbp** [comment]
The scope can be constructed and added to the environment via an ARM template output variable that references the `formRecognizerEndpointSuffix` parameter [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/test-resources.json#L45).

**Comment by v-xuto** [comment]
@benbp Okay. According to the solution to the [same issue](https://github.com/Azure/azure-sdk-for-python/issues/21448#issuecomment-1005548772) with text analytics, I will update test([test_active_directory_auth](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url.py#L165)) as shown below. This modification method will solve this issue. So, I will close this issue.
Update to:
```
form_recognizer_endpoint_suffix = os.environ.get("FORMRECOGNIZER_ENDPOINT_SUFFIX",".cognitiveservices.azure.com/")
credential_scopes = ["https://{}.default".format(form_recognizer_endpoint_suffix[1:])]
client = DocumentAnalysisClient(endpoint, token, credential_scopes=credential_scopes)
```
