### ISSUE TITLE
Deployment Manager link points to active directory

### ISSUE THREAD

**Issue by m1stermanager** [Azure/azure-sdk-for-python#22303]
per title,

The link titled "Deployment Manager" points to https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory?view=azure-python

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9755ce-e891-b94a-fc52-8e6b85586914
* Version Independent ID: 6a41e776-488a-8551-60f3-daae067492c8
* Content: [Reference](https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python)
* Content Source: []()
* Git Login: **lmazuel**
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
Thanks for your issue. @sima-zhu it appears this link points to Active Directory. Do you know how we can fix this?

![image](https://user-images.githubusercontent.com/31998003/148100480-aed0a790-ca2d-487d-88c3-2feccc6d16d3.png)

**Comment by sima-zhu** [comment]
@m1stermanager Thanks for reporting this. Will fix it.

**Comment by sima-zhu** [comment]
Looking into other links. They all point to aad page.

**Comment by sima-zhu** [comment]
Take a close look at each service. Some of the services have the right links. Some of them link to wrong pages.

**Comment by sima-zhu** [comment]
The issue has been resolved since we moved to toc automation.
