### ISSUE TITLE
[pylint] add lint rule for docstring rtype format

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#22308]
For docstrings, we should have a linter rule to ensure the correct format is used:

**wrong**: 
```
:rtype: :class:`azure.core.credentials.AccessToken`
```
**right**:
```
:rtype: ~azure.core.credentials.AccessToken
```

Additionally, APIView for Python will not recognize the first format and will likely yield an error that the docstring and type hint types do not match. 

This rule should appy for `rtype`, `type`, `paramtype` and `raises`

**Comment by lb-cake** [comment]
👋@lmazuel is this issue still up for grabs? I'm new to contributing to OSS and would like to give this one a go.

**Comment by tjprescott** [comment]
@lb-cake yes, this is certainly up for grabs!

**Comment by tjprescott** [comment]
I don't even know what I assigned @lmazuel in the first place.
