### ISSUE TITLE
Missing details of what is in the properties attribute

### ISSUE THREAD

**Issue by sagittarian** [Azure/azure-sdk-for-python#22315]
The documentation mentions that SpeechSynthesisResult.properties is "a collection of properties and their values defined for this SpeechSynthesisResult", but it doesn't mention which properties can be found there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf2b2fd-f6a5-705d-7372-354e3809677d
* Version Independent ID: 58b99ac5-2f3d-9c98-05fb-457f80fa9606
* Content: [azure.cognitiveservices.speech.SpeechSynthesisResult class](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechsynthesisresult?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cognitiveservices-speech/azure.cognitiveservices.speech.SpeechSynthesisResult.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-cognitiveservices-speech/azure.cognitiveservices.speech.SpeechSynthesisResult.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
Thanks for your issue, @sima-zhu - it looks like the types are missing in the documentation

**Comment by sima-zhu** [comment]
@robch @oscholz 

Seems like Speech documentation issue. Could you take a look?

**Comment by sima-zhu** [comment]
@mayurid @lmazuel for better triage.

**Comment by lmazuel** [comment]
Swagger would need update, though we don't release track1 of this SDK anymore, but I'm not aware of their track2 story. Need to confirm with @mayurid if they are in our planning

**Comment by navba-MSFT** [comment]
@sagittarian Thanks for reaching out to us. Apologies for the delay in response. I am checking this with @mayurid and @lmazuel. I will update this thread once I have more details. In the meantime, if you have any questions feel free to post it here, we would be happy to address it.

**Comment by lmazuel** [comment]
> Swagger would need update, though we don't release track1 of this SDK anymore, but I'm not aware of their track2 story. Need to confirm with @mayurid Mayuri Diwan FTE if they are in our planning

My mistake that what I said is wrong, I mixed speech SDK for another SDK. This was never track1. Though Mayuri did send an email to clarify with the speech team, we'll update when we receive some news.

**Comment by navba-MSFT** [comment]
As per the discussion with @mayurid looping ++ @robch Could you please look into this missing documentation issue for [SpeechSynthesisResult.properties ](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechsynthesisresult?view=azure-python) attribute ?

**Comment by dargilco** [comment]
Hi @sagittarian, this is Darren from the Microsoft Speech SDK team. Thank you for your question! To get a speedy answer and access to a wide knowledge base of previous answers, please in the future open a new issue in the [Speech SDK repository](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues). My team monitors this repository daily.

You are absolutely right that we should be doing a better job in the API reference documents about what properties are supported on objects. These properties are usually mentioned in quick-starts under the [Speech Services documentation](https://docs.microsoft.com/azure/cognitive-services/speech-service/) in the appropriate area. And/or in the samples in the Speech SDK repository.

To answer your question, there are 4 properties supported on SpeechSynthesisResult:

- `SpeechServiceResponse_SynthesisFinishLatencyMs` and `SpeechServiceResponse_SynthesisFirstByteLatencyMs` - See section titled ["Lower speech synthesis latency using Speech SDK"](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-lower-speech-synthesis-latency?pivots=programming-language-python).
- `SpeechServiceResponse_SynthesisUnderrunTimeMs`
- `SpeechServiceResponse_SynthesisBackend`

We have done a better job so far documenting the properties in the C# reference documents, so you can [always look here](https://docs.microsoft.com/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet#fields) for a short description of each property. They are the same across programming languages.

Darren
