### ISSUE TITLE
[Batch Management] Pool creation - Unclear how to link an identity

### ISSUE THREAD

**Issue by andreamigotto** [Azure/azure-sdk-for-python#22337]
Not clear if the user_assigned_identities property should be a list (as per the description) or a dict (as per the type specification).

UPDATE
Furthermore, while being marked as a required parameter, when expanding the doc of the UserAssignedIdentities class (referenced in the type specification) it gives no hint about the parameters to instantiate, it seems it is filled in server-side. So it is pretty much impossible to understand how to link the desired identity to the pool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d8bfb49-29d9-bf61-b3e1-18ff455a1e1b
* Version Independent ID: 153bd51a-0fbc-e754-aee9-12d82bd32648
* Content: [azure.mgmt.batch.models.BatchPoolIdentity class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.batchpoolidentity?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-batch/azure.mgmt.batch.models.BatchPoolIdentity.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-batch/azure.mgmt.batch.models.BatchPoolIdentity.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
Hi @andreamigotto, thanks for the feedback. We'll see about fixing the docs asap.

**Comment by kazrael2119** [comment]
Hi @andreamigotto ,thanks for the feedback. This sample will help you to solve this issue. Here is code.
```
import os

from azure.identity import DefaultAzureCredential
from azure.mgmt.batch import BatchManagementClient

credentials = DefaultAzureCredential()
SUBSCRIPTION_ID = os.getenv('SUBSCRIPTION_ID')
batch_name = 'Your Batch Name'
GROUP_NAME = "Your Group Name"
pool_name = 'Your Pool Name'
identity_name = 'Your Identity Name'

batch_client = BatchManagementClient(
    credential=DefaultAzureCredential(),
    subscription_id=SUBSCRIPTION_ID
)

pool = batch_client.pool.create(
    GROUP_NAME,
    batch_name,
    pool_name,
    {
        "properties": {
            "vmSize": "STANDARD_D4",
            "deploymentConfiguration": {
                "virtualMachineConfiguration": {
                    "imageReference": {
                        "publisher": "Canonical",
                        "offer": "UbuntuServer",
                        "sku": "18.04-LTS",
                        "version": "latest"
                    },
                    "nodeAgentSkuId": "batch.node.ubuntu 18.04"
                }
            },
            "scaleSettings": {
                "autoScale": {
                    "formula": "$TargetDedicatedNodes=1",
                    "evaluationInterval": "PT5M"
                }
            }
        },

        "identity": {
            "type": "UserAssigned",
            "userAssignedIdentities": {
                "/subscriptions/"+SUBSCRIPTION_ID+"/resourceGroups/"+GROUP_NAME+"/providers/Microsoft.ManagedIdentity/userAssignedIdentities/"+identity_name: {}
            }

        }
    }

)

result = batch_client.pool.get(GROUP_NAME, batch_name, pool_name)
print(result)

```
