### ISSUE TITLE
There is a problem with token generation via "ClientSecretCredential".

### ISSUE THREAD

**Issue by DohyeonEom** [Azure/azure-sdk-for-python#22332]
I am trying to authenticate using the service principal method.
In the past, you could access resources using the "ClientSecretCredential" method.
However, currently the token generated with "ClientSecretCredential" doesn't seem to have permission to access the resource.

Access tokens obtained via interactive authentication with "InteractiveBrowserCredential" work without any issues.
On the other hand, there seems to be a problem with tokens generated via the app's client secret.

When I try to get subscription information, it returns an empty value like this:
{
    "value": [],
    "count": {
        "type": "Total",
        "value": 0
    }
}

Here is my code:
```
from azure.mgmt.resource.subscriptions import SubscriptionClient
from azure.identity import ClientSecretCredential
from azure.mgmt.keyvault import KeyVaultManagementClient

def main():
    credentials = ClientSecretCredential(
           tenant_id = tenant_id,
           client_id = client_id,
           client_secret = client_secret
           )

    # List subscriptions
    page_result = subscription_client.subscriptions.list()
    result = [item for item in page_result]
    for item in result:
        print(item.subscription_id)
        print(item.tags)

    keyvault_client = KeyVaultManagementClient(credentials, subscription_id)
    for vault in keyvault_client.vaults.list_by_subscription():
         print (vault)

if __name__ == "__main__":
    main()
```

When I try to get keyvault information, I get the following error:
```
azure.core.exceptions.HttpResponseError: (AuthorizationFailed) The client '***' with object id '***' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/***' or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed
Message: The client '***' with object id '***' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/***' or the scope is invalid. If access was recently granted, please refresh your credentials.
```
Am I missing something? 

Until recently I was able to access all information without problems using "ClientSecretCredential".
Is there a way to get a user auth token non-interactively without opening a browser?
("UsernamePasswordCredential" exists, but cannot be used if MFA is enabled for your account.)

I need help.

**Comment by kristapratico** [comment]
Hi @DohyeonEom thanks for your issue, we'll investigate and get back to you asap.

**Comment by mccoyp** [comment]
Hi @DohyeonEom, thank you for opening an issue! I just tried out your code on my end with my own credentials, and I got subscription and vault information that I would expect. This makes me think that there may be an issue with your service principal's permissions and/or the credentials you're using -- nothing should have changed with the ClientSecretCredential to break this scenario, as far as I know. The `AuthorizationFailed` error coming from the KeyVaultManagementClient's request also makes me believe that this could be a permissions issue.

Could I ask you to try running the same code with the credentials of another service principal in the subscription?

**Comment by DohyeonEom** [comment]
@mccoyp 
Subscription->Access control (IAM)->Role assignments
It was done by granting permission to the subject.
It helped a lot. thank you.

**Comment by DohyeonEom** [comment]
@mccoyp
Subscription->Access control (IAM)->Role assignments
It was done by granting permission to the subject.
It helped a lot. thank yo

**Comment by anotherancientalien** [comment]
> InteractiveBrowserCredential
Hi, what is the right permission?

**Comment by mccoyp** [comment]
Hi @anotherancientalien, you should require the `Microsoft.KeyVault/vaults/read` permission over your subscription. Below is a screenshot showing the permission as it appears in the "Access Control (IAM)" window of the subscription page.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/39780829/159100220-21127822-3a97-4f79-a0fb-8016a7e8f916.png">
