### ISSUE TITLE
The API fails with "message: EventDate should have beginning range value."

### ISSUE THREAD

**Issue by OTDani** [Azure/azure-sdk-for-python#22365]
Calling consumption_client.reservation_transactions.list(billingAccountId) yields 

HttpResponseError: (400) EventDate should have beginning range value. 

The document states not that the filter is required or mandatory or how to properly construct it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1559781c-04b8-4cf5-7ebf-32853106d8d1
* Version Independent ID: 3ffaf41f-ca8b-80cb-90c6-8a065e24e50e
* Content: [azure.mgmt.consumption.operations.ReservationTransactionsOperations class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-consumption/azure.mgmt.consumption.operations.reservationtransactionsoperations?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-consumption/azure.mgmt.consumption.operations.ReservationTransactionsOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-consumption/azure.mgmt.consumption.operations.ReservationTransactionsOperations.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
Thanks for the feedback @OTDani, we'll look into this and get it fixed asap.

**Comment by BigCat20196** [comment]
Hi @OTDani, thanks for your feedback !

Here is a sample FYR:
```
import os
from datetime import datetime

from azure.identity import DefaultAzureCredential
from azure.mgmt.consumption import ConsumptionManagementClient

credentials = DefaultAzureCredential()
subscription = os.getenv('SUBSCRIPTION_ID')

consumption_client = ConsumptionManagementClient(DefaultAzureCredential(), subscription_id=subscription)
reservation_order_id = 'your order id'

# start_date = datetime.strptime('2021-01-01T00:00:00Z', '%Y-%m-%dT%H:%M:%SZ')
# end_date = datetime.strptime('2022-01-01T00:00:00Z', '%Y-%m-%dT%H:%M:%SZ')

# or

start_date = datetime.strptime('2021-01-01', '%Y-%m-%d')
end_date = datetime.strptime('2022-01-01', '%Y-%m-%d')

filter_from = "properties/UsageDate ge {}".format(start_date.strftime("%Y-%m-%dT%H:%M:%SZ"))
filter_to = "properties/UsageDate le {}".format(end_date.strftime("%Y-%m-%dT%H:%M:%SZ"))
filter_expression = "{} and {}".format(filter_from, filter_to)

res = consumption_client.reservation_transactions.list(reservation_order_id, filter=filter_expression)

```

**Comment by OTDani** [comment]
@BigCat20196  - Thanks a lot - works great! 

Just a few questions if i may: 
- Can we add this to the documentation as a sample or into the sample codes? - as this is very valuable. 
- What is the default behaviour? So what is the definition of data i get back if i add nothing or None?  - could we also add this to the docs? 

Thanks a lot!

**Comment by BigCat20196** [comment]
@OTDani, Sure, I'm glad it can help you. Of course, it can also help more people. 

If no filter is added, it will return all transactions under the billing account scope

**Comment by OTDani** [comment]
@BigCat20196 
Thank you :)
