### ISSUE TITLE
Issue importing azure-ai-textanalytics and azure.core.credentials  in Azure Synapse Notebook : ModuleNotFoundError: No module named 'azure.core.paging'

### ISSUE THREAD

**Issue by divya-r-kamat** [Azure/azure-sdk-for-python#22377]
- **Package Name**:  azure-ai-textanalytics and azure.core.credentials 
- **Package Version**:  5.1.0
- **Operating System**: Azure Synapse notebook
- **Python Version**: 3.8
- -**Apache Spark Version**: 3.1

**Describe the bug**
Getting below error when importing azure.ai.textanalytics and azure.core.credentials within Synapse notebook

`from azure.ai.textanalytics import TextAnalyticsClient`
`from azure.core.credentials import AzureKeyCredential`

```
ModuleNotFoundError: No module named 'azure.core.paging'
Traceback (most recent call last):

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/azure/ai/textanalytics/__init__.py", line 7, in <module>
    from ._text_analytics_client import TextAnalyticsClient

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/azure/ai/textanalytics/_text_analytics_client.py", line 17, in <module>
    from azure.core.paging import ItemPaged

ModuleNotFoundError: No module named 'azure.core.paging'
```

```
ModuleNotFoundError: No module named 'azure.core.credentials'
Traceback (most recent call last):

ModuleNotFoundError: No module named 'azure.core.credentials'
```

This was working fine until yesterday.

**Comment by kristapratico** [comment]
Hi @divya-r-kamat, can you tell me which version of azure-core you are using?

**Comment by kristapratico** [comment]
Update: I tried to repro this in a synapse notebook and I was unable to see the same error. 

![image](https://user-images.githubusercontent.com/31998003/148614767-74f116a9-86be-4f36-97fd-93be83fa5d0a.png)

I'm not too familiar with synapse notebooks, but just to document the steps I took: 1) add text analytics package whl (v5.1.0) to the workspace 2) enable session-level packages, and 3) add the text analytics package to the spark pool I was using. Has anything changed in your environment recently?

**Comment by card78** [comment]
Hi @divya-r-kamat,
I have almost the same error as you. The only difference is I'm trying to import a different package. I've raised a ticket to MS, as it's a production issue. The temporary workaround is to recreate the spark pool. Support engineer will raise an internal ticket with MS for root cause analysis.

**Comment by divya-r-kamat** [comment]
Thanks @kristapratico and @card78 for checking on this. As @card78 suggested, I have recreated the spark pool and I don't see the error.
Thanks for your help!
