### ISSUE TITLE
[Key Vault] Remove references to six package

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#22373]
Now that support for Python 2.7 has been dropped (https://github.com/Azure/azure-sdk-for-python/pull/22367), we can stop using the `six` package.

**Comment by DevRyu** [comment]
Dear @mccoyp 
Do this issue still valid?
If so then I want to refactor this code.

**Comment by mccoyp** [comment]
Hi @DevRyu, thank you for offering to help! This issue is still open and hasn't been started on, so I would be happy to review any PRs you'd like to submit 🙂

**Comment by mccoyp** [comment]
Closed by #25902.
