### ISSUE TITLE
[KeyVault] - Add support for OKP key type

### ISSUE THREAD

**Issue by maorleger** [Azure/azure-sdk-for-python#22370]
In order to support OKP key types and EdDSA algorithm, the following changes need to be made:

1. A new Key Type is added - OKP and OKP-HSM
2. A new Key Curve is added - Ed25519
3. Sign and verify using the EdDSA algorithm is supported by cryptography client
4. SignData and VerifyData using the EdDSA algorithm is supported by cryptography client using sha256 for hashing. We should probably document that we use sha256 somewhere? 

In addition, we should add a new `createOkpKey` convenience method similar to `createRsaKey` (with similar support for the `hsm` option)

Acceptance criteria:
1. `createKey` supports creating OKP / OKP-HSM keys 
2. `createOkpKey` is added to KeyClient and can be used to create OKP / OKP-HSM keys (controlled by the `hsm` option)
3. Cryptography client can be used to sign and verify using the OKP key type and the EdDSA algorithm (both sign/verify and signData/verifyData)

**Comment by mccoyp** [comment]
Still awaiting OKP availability.
