### ISSUE TITLE
[KeyVault] - Invesitgate local cryptography support for OKP Key Types

### ISSUE THREAD

**Issue by maorleger** [Azure/azure-sdk-for-python#22371]
Investigate whether we can provide local verification for OKP key types using platform-supported cryptography APIs

**Comment by maorleger** [comment]
This for 7.4-preview

**Comment by vcolin7** [comment]
We decided OKP will not be supported locally, as the default crypto libraries we us in our languages don't have a proper implementation for the algorithm.
