### ISSUE TITLE
The models for RoleAssignment in azure.mgmt.authorization don't return some expected properties

### ISSUE THREAD

**Issue by DohyeonEom** [Azure/azure-sdk-for-python#22380]
azure-mgmt-authorization version is 2.0.0

I am trying to get a list of role policies by user within a resource group using role_assignments in AuthorizationManagementClient.
Others are now fetching fine, but some necessary values are missing.
The values I need are: principalType, principalName, roleDefinitionName

```
from azure.identity import DefaultAzureCredential
from azure.mgmt.authorization import AuthorizationManagementClient

def main():
    credentials = DefaultAzureCredential()
    subscription = <my subscription>
    group_name = <my groupname>
    
    auth_client = AuthorizationManagementClient(credentials, subscription)
    data_info = dict()
    for auth in auth_client.role_assignments.list_for_resource_group(resource_group_name=group_name):
        data_info['id'] = auth.id
        data_info['name'] = auth.name
        data_info['type'] = auth.type
        data_info['scope'] = auth.properties.scope
        data_info['principal_id'] = auth.properties.principal_id
        data_info['role_definition_id'] = auth.properties.role_definition_id
        data_info['principal_type'] = ???
        data_info['princiapl_name'] = ???
        data_info['role_definition_name'] = ???

if __name__ == "__main__":
    main()
```
![image](https://user-images.githubusercontent.com/71824607/148528306-ac6329f8-077e-4da3-b0f5-48e641bbbd83.png)

Is there any way to get that value?
I want a list similar to when I input the az role assignment list --resource-group <Resource group id> option.
I need help

**Comment by kristapratico** [comment]
@DohyeonEom thanks for your issue, we'll investigate asap.

**Comment by BigCat20196** [comment]
Hi @DohyeonEom thanks for your feedback !

You can add the `filter = "atscope()"` to get more info.

FYI:
```
for auth in auth_client.role_assignments.list_for_resource_group(resource_group_name=group_name, filter="atScope()"):

```

**Comment by msyyc** [comment]
Hi, SDK deserialize http response returned by service server. So I think the reason is that server doesn't return those parameters. You could confirm that in log by [guidance](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md).
