### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by jmwoloso** [Azure/azure-sdk-for-python#22384]
**Is your feature request related to a problem? Please describe.**
I'd like to use Python 3.9 however, `azureml-train-automl-client` has a requirement for python `<3.9,>=3.6`

**Describe the solution you'd like**
Support Python 3.9

**Describe alternatives you've considered**
N/A

**Additional context**
Traceback:

```
ERROR: Package 'azureml-train-automl-client' requires a different Python: 3.9.9 not in '<3.9,>=3.6'
```

**Comment by kristapratico** [comment]
Hi @jmwoloso thanks for your feedback. @bandsina can you help with this request?

**Comment by jmwoloso** [comment]
@bandsina @kristapratico do we think this will be something addressed soon or will it take some time? just curious because we're in the process of testing library upgrades on our production pipelines and we'd like to upgrade to python 3.9 if possible depending on the timeline here.

**Comment by toby-coleman** [comment]
Similarly I'd like to upgrade a package containing `azureml-pipeline-steps` to Python 3.9, and this has a dependency on `azureml-train-automl-client`. Any update on the timeline @bandsina @kristapratico ?

**Comment by dominikhait** [comment]
We also would like to upgrade our project to Python 3.9, is there any update on this issue? @bandsina @kristapratico

**Comment by kristapratico** [comment]
@azureml-github

Sorry, for the delay. Let me find someone from the Azure ML team to help with this query.

**Comment by toby-coleman** [comment]
@azureml-github @kristapratico - any update on this issue?

**Comment by andrii-kokhan** [comment]
Can i ask you to kindly give us a hint as to the possible date of aligning azureml-train-automl-* libs with python 3.9? Any plans at all? That would help us to plan migration to later python version.

**Comment by kristapratico** [comment]
Hi @andrii-kokhan, I've reached out to the ML team. Will reply as soon as I get an answer.

**Comment by jeff-shepherd** [comment]
I just completed the change to allow azureml-train-automl-client to work with Python 3.9.
This should be available in the next Azure ML SDK release, 1.45.0.

**Comment by jmwoloso** [comment]
@jeff-shepherd thanks so much!

**Comment by andrii-kokhan** [comment]
Thank you.

**Comment by jmwoloso** [comment]
@jeff-shepherd one more question. any idea on the timeline for the next release?

**Comment by jeff-shepherd** [comment]
@jmwoloso Currently, we release the Azure ML SDK once a month.
I think Azure ML SDK 1.45.0 will be released to PyPI on August 29th, 2022.

**Comment by jmwoloso** [comment]
Perfect, thank you @jeff-shepherd!
