### ISSUE TITLE
proxy_testcase.py turns potentially useful errors from test-proxy into useless ones

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#22389]
See original issue: https://github.com/Azure/azure-sdk-for-python/issues/22387

```Python
# snippet from start_or_record_payback in proxy_testcase.py
   if is_live():
        result = requests.post(
            RECORDING_START_URL,
            headers={"x-recording-file": test_id, "x-recording-sha": current_sha},
        )
        recording_id = result.headers["x-recording-id"]
    else:
        result = requests.post(
            PLAYBACK_START_URL,
            headers={"x-recording-file": test_id, "x-recording-sha": current_sha},
        )
        try:
            recording_id = result.headers["x-recording-id"]
        except KeyError:
            raise ValueError("No recording file found for {}".format(test_id))
        if result.text:
            try:
                variables = result.json()
            except ValueError as ex:  # would be a JSONDecodeError on Python 3, which subclasses ValueError
                six.raise_from(
                    ValueError("The response body returned from starting playback did not contain valid JSON"), ex
                )
````

This pattern:
```Python
try:
  # do something
except:
  raise ValueError(...)
```

Result in a frustrating debugging experience. The underlying issue is that the request returned  server 500 error. We are proactively assuming things went well, and attempting to retrieve the x-recording-id header. However, since the request failed, it doesn't exist and so the first error we get in the debug log is a KeyError.

Then we throw away the information that was in the response, which provides useful details and instead manually throw a vague error. "No recording file found for {test_id}". While this is true, it gives zero context for trying to figure out why, since the recording file is present.

This pattern results in a debug log that looks like:

```
E       KeyError: 'x-recording-id'
During handling of the above exception, another exception occurred:
>               raise ValueError("No recording file found for {}".format(test_id))
```

It would be much preferable if we simply looked at the result, and if it is an error, actually bubble up the error. The KeyError is a total red herring, and rethrowing a less-specific error helps no one.

**Comment by mccoyp** [comment]
This a great point; we should `raise from` so we don't lose the original context.
