### ISSUE TITLE
[Reservations] Update the models to scope a reservation to a management group

### ISSUE THREAD

**Issue by ii-varsha-ii** [Azure/azure-sdk-for-python#22383]
Related to package: azure-mgmt-reservations
As of September 21, 2021, Azure has added a new improvement to scope a reservation to a management group level. 
Reference: https://azure.microsoft.com/en-us/updates/mgscopereservations/

Using the current models, eg: AppliedScopeType can either be Single or Shared. Can we update the models to add support for ManagementGroup? 

Any comments or alternatives are highly appreciated. 
Thanks :)

**Comment by kristapratico** [comment]
Hi @ii-varsha-ii thanks for your feedback, we'll take a look at this and get back to you.

**Comment by BigCat20196** [comment]
Hi @ii-varsha-ii  Thanks for your feedback !

The python SDK code is automatically generated according to [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/reservations/resource-manager/readme.md). Make sure [swagger ](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/reservations/resource-manager/readme.md)has this feature. 

After that, please go [here ](https://portal.azure-devex-tools.com/tools/request-api-release)and submit a release request.
