### ISSUE TITLE
Documentation lists incorrect Python versions on PyPI

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#22407]
If this change is [universal then other packages are probably affected as well](https://github.com/Azure/azure-sdk-for-python/search?q=%22This+package+has+been+tested+with+Python+2.7%2C+3.6%2B%22). 

[This change moves the Python version up to >= 3.7](https://github.com/Azure/azure-sdk-for-python/commit/75e46a7c33811ee3304f18014cd7fe9e69b45914#diff-01e7269eb782dcd3599165a5fb043787318351599582ebf91bdc3fee6a48fc15R72) but the documentation on the [readme page for the package says that it is tested with Python 2.7, 3.6+.](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/consumption/azure-mgmt-consumption/README.md?plain=1#L4). 

This could confuse someone reading the PyPI documentation for `azure-mgmt-consumption==9.0.0` 

![image](https://user-images.githubusercontent.com/2158838/148790001-5555f41f-ea45-4ac2-9ac0-afc6bdea622a.png)

This was discovered in the build for docs.microsoft.com reference documentation. That docs pipeline uses Python 3.6.8. We're currently testing moving it up to Python 3.7.

**Comment by msyyc** [comment]
need a new release to update pypi
