### ISSUE TITLE
ExtractSummaryAction class not found

### ISSUE THREAD

**Issue by EmanueleGusso** [Azure/azure-sdk-for-python#22411]
Hi everybody,
I tried the snippet of code here provided https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/text-summarization/quickstart?pivots=programming-language-python to try the text summarization.
But I receive the following error: 'ImportError: cannot import name 'ExtractSummaryAction' from 'azure.ai.textanalytics''
Besides, if I search through the azure package, I don't find any "ExtractSummaryAction" class. 
What's going on? Help me please!
I'm using Python 3.8.2, azure-ai-textanalytics 5.1.0, azure-common 1.1.27, azure-core 1.21.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09a0a57d-b105-3d20-5384-ba399f3a1302
* Version Independent ID: bdba0610-7e75-e843-e711-c0e74136449d
* Content: [azure.ai.textanalytics.ExtractSummaryAction class](https://docs.microsoft.com/en-us/python/api/azure-ai-textanalytics/azure.ai.textanalytics.extractsummaryaction?view=azure-python-preview#feedback)
* Content Source: [preview/docs-ref-autogen/azure-ai-textanalytics/azure.ai.textanalytics.ExtractSummaryAction.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/preview/docs-ref-autogen/azure-ai-textanalytics/azure.ai.textanalytics.ExtractSummaryAction.yml)
* GitHub Login: @VSC-Service-Account

**Comment by kristapratico** [comment]
Hi @EmanueleGusso, the extract summarization feature is only available in the beta package of text analytics. Please try installing version 5.2.0b2: https://pypi.org/project/azure-ai-textanalytics/5.2.0b2/

**Comment by abhishekkumaribt** [comment]
Hi still facing this issue with 5.2.0b2 version

**Comment by kristapratico** [comment]
Hi @abhishekkumaribt are you using a virtual environment and installing the package there?

**Comment by abhishekkumaribt** [comment]
Thanks @kristapratico worked after using a virtual environment and installing the package there.

**Comment by afaq-ahmad** [comment]
I was facing the same issue on Azure ubuntu 20.04 VM, my problem was solved by installing the 5.2.0b2 version

pip3 install azure-ai-textanalytics==5.2.0b2
