### ISSUE TITLE
Unable to query blob contents of parquet file 

### ISSUE THREAD

**Issue by ArvidMartensRenson** [Azure/azure-sdk-for-python#22443]
- **Package Name**: azure-storage-filedatalake 
- **Package Version**: 12.5.0
- **Operating System**: Linux 20.04
- **Python Version**: 3.8.5

**Describe the bug**
Whenever I try to query the contents of a parquet file through the query_file method (query blob contents API), I get an an error that the specified XML document is invalid. This occurs both if no output format or an output format is set.

**To Reproduce**
1. Create a fileclient to a parquet file
2. Create a query to read several columns in the parquet file
3. Set the file_format of the query_file method to ParquetDialect
4. Observe the error

**Expected behavior**
Retrieve the data from the parquet file based on the query.

**Comment by estatic** [comment]
I have the same error, but for CSV Dialect.
I've tried to downgrade the version of the library to 12.4.0 and tried several versions of azure-storage-blob,  but still observe an issue.

**Comment by estatic** [comment]
Seems I found what was the problem. The problem in my case was with Deserialization. In case it cannot recognize the final result it's going to show the error above. So, the problem is not about the request, it's about the response body and deserialization.

**Comment by jalauzon-msft** [comment]
Hi @ArvidMartensRenson, apologies for the long delay on this. Are you still experiencing the issue?

If so, would you mind sharing a little bit more information about your scenario as I am not able to reproduce this issue.
1. A code snippet of how you are querying the file specifically?
2. The general schema for your parquet file?
3. The specific error you are getting? Ideally including the service request ID from a recent occurrence.
