### ISSUE TITLE
core.pipeline.transport returns string for __bases__ 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#22469]
[Python documentation](https://docs.python.org/3.7/library/stdtypes.html?highlight=__bases#class.__bases__) describes `class.__bases__` as "The tuple of base classes of a class object" ... `__bases__` probably isn't meant to be an attribute of a module.

In the case of https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/transport/__init__.py#L65 the result returned from `azure.core.pipeline.transport.__bases__` is a string, not a tuple of base classes or an `AttributeError`.

```
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.core.pipeline.transport
>>> azure.core.pipeline.transport.__bases__
'__bases__'
>>>
```

This is encountered when [running on Python >= 3.7](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/transport/__init__.py#L54). The docs.ms reference documentation generation process expects that if an object has a `__bases__` attribute the attribute is implemented according to the documentation for classes. 

Is this assumption a bug in the documentation generation process? Is the behavior of `__bases__` a bug for other users of this module? 

cc @scbedd

**Comment by lmazuel** [comment]
@danieljurek we discussed it with @kashifkhan and this is a bug, accessing `__bases__` should raise an AttributeError, as like you said this attribute do not even makes sense at the module level.
