### ISSUE TITLE
[Article] End-user authentication - Python with Data Lake Storage Gen1 - Azure

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-python#22465]
[Docs link](https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-end-user-authenticate-python)
[ADO Workitem](https://dev.azure.com/docindex/azure-sdk/_workitems/edit/343693/)

Learn how to achieve end-user authentication with Azure Data Lake Storage Gen1 using Azure Active Directory with Python
Azure resource, mgmt resource SDK (py t1)
Azure storage , files data lake sdk (py t1)
Azure storage , mgmt  files data lake  sdk (py t1)
Action to do: update sample code to leverage t2 version sdk

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/21306
