### ISSUE TITLE
[Article] Manage an Azure Data Lake Storage Gen1 account with Python

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-python#22464]
[Docs Link](https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-get-started-python)
[ADO Workitem](https://dev.azure.com/docindex/azure-sdk/_workitems/edit/343685/)

Learn how to use the Python SDK for Azure Data Lake Storage Gen1 account management operations.

Azure resource, mgmt resource SDK (py t1)
Azure storage , files data lake sdk (py t1)
Azure storage , mgmt  files data lake  sdk (py t1)

Action to do: Update sample python code from T1 to T2

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/21306
