### ISSUE TITLE
[Article] Create a Python runbook in Azure Automation

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-python#22463]
[Docs link](https://docs.microsoft.com/en-us/azure/automation/learn/automation-tutorial-runbook-textual-python-3)
[ADO Workitem](https://dev.azure.com/docindex/azure-sdk/_workitems/edit/372480/)
This article teaches you to create, test, and publish a simple Python runbook.

Azure Compute, Compute mgmt SDK (py t1)
Azure Resource, Resource mgmt SDK (py t1)

Action to do:  update sample code to leverage python t2 version sdk

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/21306
