### ISSUE TITLE
ServiceBus - Converted dict does not reach queue

### ISSUE THREAD

**Issue by codingmercy1993** [Azure/azure-sdk-for-python#22486]
Hey guys,

I use your servicebus SDK (latest) to send a ServiceBusMessage to a ServiceBus Queue.
Somehow I recognized weird behavior when sending messages to queue:
When I put a normal string into ServiceBusMessage body - everything works fine.
When I convert a dictionary to a string - message does not reach the queue
When I convert a dictionary to bytes object - message SOMETIMES reaches the queue.

So based on type some messages just dont make it to the queue.

```python
from azure.servicebus import ServiceBusMessage
import json

connection_string = "Endpoint=**EndointUrl**;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=**AcountKey**"
http_proxy = {'proxy_hostname': 'proxy.intern.somecompany.de', 'proxy_port': 8080}
servicebus_client = ServiceBusClient.from_connection_string(conn_str=connection_string,
                                                                         logging_enable=True, http_proxy= http_proxy)

# Case 1 - Basic string -> always works

msg_metadata_dict = {"testkey": "testvalue"}
message_input = "blabla

with servicebus_client as client:
    with client.get_queue_sender("test-queue") as sender:
        message = ServiceBusMessage(body=message_input,time_to_live= timedelta(hours=12), application_properties=msg_metadata_dict)
        sender.send_messages(message)

#Case 2 - Dict to string -> never reaches queue

msg_metadata_dict = {"testkey": "testvalue"}
message_input = str({"testkey": "testvalue"})

with servicebus_client as client:
    with client.get_queue_sender("test-queue") as sender:
        message = ServiceBusMessage(body=message_input,time_to_live= timedelta(hours=12), application_properties=msg_metadata_dict)
        sender.send_messages(message)                     
 
#Case 3 - Dict to bytes -> SOMETIMES reaches queue

pre_msg_metadata_dict = {"testkey": "testvalue"}
message_input = {"testkey": "testvalue"}
message_input = json.dumps(pre_msg_content_dict).encode('utf-8')

with servicebus_client as client:
    with client.get_queue_sender("test-queue") as sender:
        message = ServiceBusMessage(body=message_input,time_to_live= timedelta(hours=12), application_properties=msg_metadata_dict)
        sender.send_messages(message)                                                                                  
                                                                        
```
In not one case the client returns any error.
I also tried every possible option for content_type ("text/plain", "application/xml", "application/json") and body_type (AmqpMessageBodyType.VALUE, AmqpMessageBodyType.SEQUENCE, AmqpMessageBodyType.DATA) without any change to the behavior mentioned above.
FYI I am trying from coporate network behind a proxy therefore I have to set proxy values.
Also tried to insert message into queue using service bus explorer in azure portal - this always works.

My goal is to be able to send dicts with strings and ints as keys/values (of course converted to string or bytes) to service bus queue.

**Comment by mccoyp** [comment]
Hi @codingmercy1993, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible.

**Comment by swathipil** [comment]
Hey @codingmercy1993 - sorry for the late response + thanks for your patience! This is very strange. 🤔 Would you be able to turn on logging and report the output here? Since there are no errors, it may or may not be useful.

Section in the README on how to turn on logging: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/servicebus/azure-servicebus#logging
