### ISSUE TITLE
[storage] add back support for python 3.6

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#22482]
The data-plane storage libraries should add back support for python 3.6.

**Comment by jalauzon-msft** [comment]
@kristapratico Sorry, maybe I missed something but why are we adding support for 3.6 back?

**Comment by kristapratico** [comment]
@jalauzon-msft Oh sorry, I'll forward the thread to you. There were CLI and linux distro concerns.
