### ISSUE TITLE
Purview Catalog Client : delete_by_guid works but delete_by_guids doesn't !! 

### ISSUE THREAD

**Issue by abandyop** [Azure/azure-sdk-for-python#22487]
- **Package Name**: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-catalog
- **Package Version**: 
- **Operating System**:
- **Python Version**:  3.7

**Describe the bug**
delete_by_guid works but delete_by_guids doesn't !!

**To Reproduce**
1. 
When I use the following code -> It works : 

credential = DefaultAzureCredential()
client = PurviewCatalogClient(endpoint="https://purviewaccount.purview.azure.com", credential=credential)
try:
    response = client.entity.delete_by_guid("7436615c-efee-4f54-b09b-54f6f6f60000")

**But when I use the following it doesn't work.**

credential = DefaultAzureCredential()
client = PurviewCatalogClient(endpoint="https://purviewaccount.purview.azure.com", credential=credential)
try:
    response = client.entity.delete_by_guids(["7436615c-efee-4f54-b09b-54f6f6f60000", "8aa0e7a0-6eda-47ae-8469-15f6f6f60000"])
    print(response)

**Expected behavior**
I need a way to delete multiple atlas entities at one go.
Please help.
Many customers are waiting for this.

**Screenshots**

**Additional context**

**Comment by iscai-msft** [comment]
hello @abandyop, we have identified the fix and have a [PR](https://github.com/Azure/azure-sdk-for-python/pull/22495) out to fix it. We generally do our releases on our 3 week sprint cadence, which means this fix will be released the first week of February. I want to check in with you and see if this date is ok with you. If you have any extenuating circumstances, please let us know!

**Comment by abandyop** [comment]
Yeah ideally earlier the better, but I'll have to live with the release cycles ... NO problem will check back 2nd week Feb
