### ISSUE TITLE
subscription_client.tenants.list() not showing additional information, it returns none

### ISSUE THREAD

**Issue by daperezc** [Azure/azure-sdk-for-python#22527]
- **Package Name*azure-mgmt-resource*: 
- **Package Version*20.0.0*: 
- **Operating System*Windows/Linux*:
- **Python Version*Python 3.8.10*: 

**Describe the bug**
When running the subscription_client.tenants.list() method and printing the result it shows none on almost all fields.
This happens only with Managed Identities, seems to be working fine with user and password authentication if we compare the token on https://docs.microsoft.com/en-us/rest/api/resources/tenants/list 

**To Reproduce**
1. Create App Service on Azure
2. Go to Identity and enable user assigned managed identity. 
3. Get tenant id, app id and client secret from App Registration. 
4. Execute the following code: 

TenantId = '*****'
AppId = '*****'
ClientSecret = '*****'

from azure.identity import ClientSecretCredential
from azure.mgmt.resource.subscriptions import SubscriptionClient

credential = ClientSecretCredential(TenantId,AppId,ClientSecret)

subscription_client = SubscriptionClient(credential,api_version='2021-01-01')

tenants = subscription_client.tenants.list()

for t in tenants:
    print(t)

**Expected Behavior**
Current output is: 
{'additional_properties': {}, 'id': '/tenants/*****-****-****-****-***********', 'tenant_id': '*****-****-****-****-***********', 'tenant_category': 'Home', 'country': None, 'country_code': None, 'display_name': None, 'domains': None, 'default_domain': None, 'tenant_type': None, 'tenant_branding_logo_url': None}

Expected Output is supposed to include following information:

'country':, 
'country_code':, 
'display_name':,
'domains':, 
'default_domain':, 
'tenant_type':, 
'tenant_branding_logo_url':

**Comment by mccoyp** [comment]
Hi @daperezc, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible.

**Comment by daperezc** [comment]
---I have an update, if I use user/password credentials, it works: 

from azure.identity import UsernamePasswordCredential
from azure.mgmt.resource.subscriptions import SubscriptionClient
credential = UsernamePasswordCredential(AppId,User,Password,tenant_id=TenantId)
subscription_client = SubscriptionClient(credential,api_version='2021-01-01')
tenants = subscription_client.tenants.list()

for t in tenants:
    print(t)

--- Output: 

{'additional_properties': {}, 'id': '/tenants/********-****-****-****-********', 'tenant_id': '********-****-****-****-********', 'tenant_category': 'Home', 'country': None, 'country_code': '**', 'display_name': 'My Domain Name', 'domains': ['*******.mail.onmicrosoft.com', '******.onmicrosoft.com'], 'default_domain': '******.onmicrosoft.com', 'tenant_type': 'AAD', 'tenant_branding_logo_url': None}

---It fails only when I use Service Principal: 

from azure.identity import ClientSecretCredential
from azure.mgmt.resource.subscriptions import SubscriptionClient
credential = ClientSecretCredential(TenantId,AppId,ClientSecret)
subscription_client = SubscriptionClient(credential,api_version='2021-01-01')
tenants = subscription_client.tenants.list()

for t in tenants:
    print(t)

--- I believe issue is on the token or credential

**Comment by BigCat20196** [comment]
Hi @daperezc, thanks for yoour feedback !

Actually, we prefer to use `Defaultazurecredential()` for authentication. You could refer to [here](https://github.com/Azure-Samples/azure-samples-python-management/tree/master/samples/appservice#getting-started) to get using method.

Hope this can unblock you.

**Comment by daperezc** [comment]
Hi @BigCat20196  if I try to use Defaultazurecredential() from my local computer it works as it takes the user authentication from Azure CLI (user/password), however, if I try to use the code in an Azure App Service with System Assigned Managed Identity, it fails to get the information and shows none in all fields, same behavior described before, even when that Managed Identity was added as Owner of the Subscription: 

Tenant Information:

{'additional_properties': {}, 'id': '/tenants/********-****-****-****-***********7', 'tenant_id': '********-****-****-****-***********7', 'tenant_category':
 'Home', 'country': None, 'country_code': None, 'display_name': None, 'domains': None, 'default_domain': None, 'tenant_type': None, 'tenant_branding_logo_ur
l': None}

This is the code im running: 

#Python implementation of Subscription Client similar to https://docs.microsoft.com/en-us/rest/api/resources/tenants/list
#Authentication using DefaultAzureCredential library

from azure.identity import DefaultAzureCredential
from azure.mgmt.resource.subscriptions import SubscriptionClient

#Here DefaultAzureCredential takes the credentials from the environment where it is running
#On local machine, on CMD, running python app.py takes the user/password credentials from Azure CLI
#On Azure App Service it takes System Assigned Managed Identity
credential = DefaultAzureCredential();

subscription_client = SubscriptionClient(credential,api_version='2021-01-01')
tenants = subscription_client.tenants.list()
access_token = credential.get_token("https://management.azure.com/.default").token

print("DefaultAzureCredential Token:\r\n")
print(access_token)
print("\r\n")
print("Tenant Information:\r\n")
for t in tenants:
    print(t)

**Comment by msyyc** [comment]
Hi, SDK is just tool to help customers to send request and receive response to/from server. It will not swallow data. You could reference https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to get more info about the process. If SDK returns none, it proves that server returns none. If that, it is better to ask help from service team in https://github.com/Azure/azure-rest-api-specs/issues
