### ISSUE TITLE
Dependencies Conflict Between Azure CLI and Azure ML

### ISSUE THREAD

**Issue by mkrdip** [Azure/azure-sdk-for-python#22523]
- Packages: **azureml-core, azure-cli-core**: 
- Versions: **1.37.0.post1 or lower, 2.32.0**: 
- OS: **Windows and Ubuntu**:
- Python Version: **3.7.6**: 

**Describe the bug**
Whenever you want to use Azure CLI Auth in Azure ML. For example the following code:

```python
from azureml.core import Workspace, Model
from azureml.core.authentication import AzureCliAuthentication

cli_auth = AzureCliAuthentication()

ws = Workspace.from_config(auth=cli_auth)
print(ws.get_details())
```

You would need to use either `azure-cli` or `azure-cli-core`. But Azure CLI Core and Azure ML core has conflicts in their dependencies for two packages. 

> There are incompatible versions in the resolved dependencies

**To Reproduce**
1. Install [Azure ML Core Python SDK](https://pypi.org/project/azureml-core/): `pip install azureml-core`
2. Install [Azure CLI Python SDK](https://pypi.org/project/azure-cli-core/): `pip install azure-core-cli`
At this step, you'll get notices like if you install from `requirements.txt`

```
The conflict is caused by:
    azure-cli-core 2.32.0 depends on knack~=0.9.0
    azureml-core 1.37.0.post1 depends on knack~=0.8.2
    azure-cli-core 2.32.0 depends on knack~=0.9.0
    azureml-core 1.37.0 depends on knack~=0.8.2
```
and like the following notice, if you Pipenv. 

```
here are incompatible versions in the resolved dependencies:
  humanfriendly<10.0,>=4.7 (from azureml-core==1.37.0.post1->-r C:\Users\username\AppData\Local\Temp\pipenvc6clky82requirements\pipenv-tbxmwz2r-constraints.txt (line 7))
  humanfriendly~=10.0 (from azure-cli-core==2.32.0->-r C:\Users\username\AppData\Local\Temp\pipenvc6clky82requirements\pipenv-tbxmwz2r-constraints.txt (line 5))
```

**Expected behavior**
Azure ML Core package should support the updated version of its dependencies `humanfriendly` and `knack`.

**Comment by mccoyp** [comment]
Hi @mkrdip, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible.

**Comment by v-pbavanari** [comment]
Requesting customer to use latest SDK package, this is fixed in newer versions. @lmazuel @mccoyp requesting to close this bug.

**Comment by mccoyp** [comment]
Hi @mkrdip, I just tried running
```
pip install azureml-core
pip install azure-cli-core
```
and was able to successfully install both packages. It seems that the dependency conflict has been fixed, so I would recommend installing the latest versions of each package if you can. I'll mark this as completed, but please let us know if you need anything else!
