### ISSUE TITLE
[AMQP Python] sync recv perf analyze and improve

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#22547]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/47871814/150053391-e1e223da-5378-4679-9484-0ca42dce3750.png">

based on the perf test results, the following test scenario and configurations should be investigated further understanding why pure python amqp is slower than uamqp and improve the perf:

- config
  - vm: west us2, Standard D2s v3 (2 vcpus, 8 GiB memory)
  - eh: west us2, Standard Tier, 32 Partition, 40 TU
  - link credit: 300 vs 3000
- scenario
  - recv 100K events (512 bytes/message)
  - recv 30s (512 bytes/message)

**Comment by yunhaoling** [comment]
we could ask PM on the ratio of users standard/basic

**Comment by rakshith91** [comment]
Profiling link: https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FLanguage%20-%20Python%2FAzure%20SDK%20-%20Language%20-%20Python&wd=target%28Rakshith%20Temp%20-%20messaging%20perf.one%7C802CA18E-3802-468B-BD7C-A9679B9258AF%2F[profiling](onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/Language%20-%20Python/Azure%20SDK%20-%20Language%20-%20Python/Rakshith%20Temp%20-%20messaging%20perf.one#profiling&section-id={802CA18E-3802-468B-BD7C-A9679B9258AF}&page-id={0860923D-6971-4830-ABC0-BC53FE038C41}&end)%7C0860923D-6971-4830-ABC0-BC53FE038C41%2F%29
onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/Language%20-%20Python/Azure%20SDK%20-%20Language%20-%20Python/Rakshith%20Temp%20-%20messaging%20perf.one#profiling&section-id={802CA18E-3802-468B-BD7C-A9679B9258AF}&page-id={0860923D-6971-4830-ABC0-BC53FE038C41}&end

No low hanging fruits found - also "Basic tier is primarily for non-production workloads. So, I’d rather focus on standard or premium tiers which are used by majority of Event Hubs customers." according to Kasun
so closing this issue for now, and will reopen if there's a lot of feedback
