### ISSUE TITLE
[AMQP Python] get and analyze the perf result on pypy, compare with cpython

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#22544]
### Scope

as pyamqp is pure python now, let's figure out how it performs on the pypy platform.

### Tasks
- compare the send/recv perf with cpython env
- finding out cpu vs io bound
- if perf is all good, then probably there's nothing to do at the moment, however, if the perf diff is significant (e.g. pypy slower), then it might be worth investigating.

**Comment by kashifkhan** [comment]
#25147 is related this this

**Comment by l0lawrence** [comment]
maybe revisit in future
