### ISSUE TITLE
[AMQP Python] Pure Python AMQP SDK Promotion

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#22545]
- [x] demo to the team
- [ ] blog post, work with lily/james), [check azure-sdk-blog issue](https://github.com/Azure/azure-sdk-blog/issues/225)
- [x] #23094
  - [ ] get a list of EH users who previous have issues with uamqp
  - [ ] get a list of EH users who are interested in trying out new things
  - [ ] reach out to them!

**Comment by lfraleigh** [comment]
When will this be ready to move forward?
