### ISSUE TITLE
cognitiveservices/azure-cognitiveservices-search-autosuggest - cspell found spelling errors in source code

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#22598]
Spell check scanning of package at `sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest` detected spelling errors in the source code and related files. This directory is opted out of PR spell checking in PR #22199 to keep PRs unblocked.

## What to do

1. Ensure Node.js is installed (https://nodejs.org/en/download/).
1. Delete the entry in `.vscode/cspell.json`'s `ignorePaths` field. It will look like: `sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/**`. You need to do this to enable checking the files.
1. From the root of the repo run spell check using `./eng/common/spelling/Invoke-Cspell.ps1 -ScanGlobs "sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/**"`
1. Fix detections according to http://aka.ms/azsdk/engsys/spellcheck use the "False positives" section to fix false positives
1. Check in changes (including the change to `.vscode/cspell.json` where the `ignorePaths` is updated to remove the entry for this service.). You may need to run `git add -f .vscode/cspell.json` to force adding the changes to the file in git.

## Spell checking output

```
./sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/operations/_auto_suggest_client_operations.py:62:35 - Unknown word (MSIE)
./sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/operations/_auto_suggest_client_operations.py:63:44 - Unknown word (Lumia)
./sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/operations/_auto_suggest_client_operations.py:65:31 - Unknown word (KHTML)
./sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/operations/_auto_suggest_client_operations.py:67:32 - Unknown word (KHTML)
./sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/operations/_auto_suggest_client_operations.py:70:67 - Unknown word (KHTML)
./sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/operations/_auto_suggest_client_operations.py:202:68 - Unknown word (JSONLD)
./sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/azure/cognitiveservices/search/autosuggest/operations/_auto_suggest_client_operations.py:203:42 - Unknown word (JSONLD)
```

**Comment by lmazuel** [comment]
Closing as we don't plan to release a new version of this package
