### ISSUE TITLE
communication/azure-communication-identity - cspell found spelling errors in source code

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#22636]
Spell check scanning of package at `sdk/communication/azure-communication-identity` detected spelling errors in the source code and related files. This directory is opted out of PR spell checking in PR #22199 to keep PRs unblocked.

## What to do

1. Ensure Node.js is installed (https://nodejs.org/en/download/).
1. Delete the entry in `.vscode/cspell.json`'s `ignorePaths` field. It will look like: `sdk/communication/azure-communication-identity/**`. You need to do this to enable checking the files.
1. From the root of the repo run spell check using `./eng/common/spelling/Invoke-Cspell.ps1 -ScanGlobs "sdk/communication/azure-communication-identity/**"`
1. Fix detections according to http://aka.ms/azsdk/engsys/spellcheck use the "False positives" section to fix false positives
1. Check in changes (including the change to `.vscode/cspell.json` where the `ignorePaths` is updated to remove the entry for this service.). You may need to run `git add -f .vscode/cspell.json` to force adding the changes to the file in git.

## Spell checking output

```
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/models.py:28:18 - Unknown word (enviornment)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/models.py:32:5 - Unknown word (GCCH)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/models.py:32:13 - Unknown word (GCCH)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/policy.py:11:46 - Unknown word (IOHTTP)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/policy.py:14:33 - Unknown word (IOHTTP)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential_async.py:53:43 - Unknown word (inprogress)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential_async.py:77:26 - Unknown word (inprogress)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential.py:55:37 - Unknown word (inprogress)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential.py:77:20 - Unknown word (inprogress)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/utils.py:27:25 - Unknown word (timegm)
./sdk/communication/azure-communication-identity/tests/user_credential_tests.py:14:52 - Unknown word (XVCJ)
./sdk/communication/azure-communication-identity/tests/user_credential_tests.py:15:26 - Unknown word (Njgw)
./sdk/communication/azure-communication-identity/tests/user_credential_tests.py:15:40 - Unknown word (FNNHHJT)
./sdk/communication/azure-communication-identity/tests/user_credential_tests.py:17:53 - Unknown word (XVCJ)
./sdk/communication/azure-communication-identity/tests/user_credential_tests.py:18:49 - Unknown word (Zwiz)
./sdk/communication/azure-communication-identity/tests/user_credential_tests.py:18:65 - Unknown word (nypg)
./sdk/communication/azure-communication-identity/tests/user_credential_tests.py:52:72 - Unknown word (asnecessary)
```

**Comment by petrsvihlik** [comment]
Internal ref: https://skype.visualstudio.com/SPOOL/_workitems/edit/2706557

**Comment by petrsvihlik** [comment]
Once fixed, we should remove the package from the spellchecker whitelist - #22199

**Comment by petrsvihlik** [comment]
And also close #22635 - network traversal does not contain any other changes than in the `_shared` folder
