### ISSUE TITLE
core/azure-common - cspell found spelling errors in source code

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#22649]
Spell check scanning of package at `sdk/core/azure-common` detected spelling errors in the source code and related files. This directory is opted out of PR spell checking in PR #22199 to keep PRs unblocked.

## What to do

1. Ensure Node.js is installed (https://nodejs.org/en/download/).
1. Delete the entry in `.vscode/cspell.json`'s `ignorePaths` field. It will look like: `sdk/core/azure-common/**`. You need to do this to enable checking the files.
1. From the root of the repo run spell check using `./eng/common/spelling/Invoke-Cspell.ps1 -ScanGlobs "sdk/core/azure-common/**"`
1. Fix detections according to http://aka.ms/azsdk/engsys/spellcheck use the "False positives" section to fix false positives
1. Check in changes (including the change to `.vscode/cspell.json` where the `ignorePaths` is updated to remove the entry for this service.). You may need to run `git add -f .vscode/cspell.json` to force adding the changes to the file in git.

## Spell checking output

```
./sdk/core/azure-common/azure/common/client_factory.py:96:9 - Unknown word (adla)
./sdk/core/azure-common/azure/common/client_factory.py:96:43 - Unknown word (adla)
./sdk/core/azure-common/azure/common/client_factory.py:99:21 - Unknown word (adla)
./sdk/core/azure-common/azure/common/client_factory.py:113:25 - Unknown word (autorestv)
./sdk/core/azure-common/azure/common/client_factory.py:169:12 - Unknown word (adal)
./sdk/core/azure-common/azure/common/client_factory.py:170:52 - Unknown word (Adal)
./sdk/core/azure-common/azure/common/client_factory.py:194:12 - Unknown word (adfs)
./sdk/core/azure-common/azure/common/client_factory.py:194:38 - Unknown word (adfs)
./sdk/core/azure-common/azure/common/client_factory.py:194:44 - Unknown word (adfs)
./sdk/core/azure-common/azure/common/client_factory.py:195:15 - Unknown word (adfs)
./sdk/core/azure-common/azure/common/client_factory.py:196:70 - Unknown word (ADAL)
./sdk/core/azure-common/azure/common/client_factory.py:200:19 - Unknown word (adal)
./sdk/core/azure-common/azure/common/client_factory.py:205:37 - Unknown word (Adal)
./sdk/core/azure-common/CHANGELOG.md:51:11 - Unknown word (patrikn)
./sdk/core/azure-common/tests/test_client_factory.py:252:98 - Unknown word (fakesubid)
./sdk/core/azure-common/tests/test_client_factory.py:253:31 - Unknown word (fakesubid)
./sdk/core/azure-common/tests/test_profile.py:16:34 - Unknown word (blablabla)
./sdk/core/azure-common/tests/test_profile.py:66:15 - Unknown word (explicily)
```

**Comment by lmazuel** [comment]
We don't plan any more release of this package
