### ISSUE TITLE
remoterendering/azure-mixedreality-remoterendering - cspell found spelling errors in source code

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#22669]
Spell check scanning of package at `sdk/remoterendering/azure-mixedreality-remoterendering` detected spelling errors in the source code and related files. This directory is opted out of PR spell checking in PR #22199 to keep PRs unblocked.

## What to do

1. Ensure Node.js is installed (https://nodejs.org/en/download/).
1. Delete the entry in `.vscode/cspell.json`'s `ignorePaths` field. It will look like: `sdk/remoterendering/azure-mixedreality-remoterendering/**`. You need to do this to enable checking the files.
1. From the root of the repo run spell check using `./eng/common/spelling/Invoke-Cspell.ps1 -ScanGlobs "sdk/remoterendering/azure-mixedreality-remoterendering/**"`
1. Fix detections according to http://aka.ms/azsdk/engsys/spellcheck use the "False positives" section to fix false positives
1. Check in changes (including the change to `.vscode/cspell.json` where the `ignorePaths` is updated to remove the entry for this service.). You may need to run `git add -f .vscode/cspell.json` to force adding the changes to the file in git.

## Spell checking output

```
./sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_polling.py:17:19 - Unknown word (unsubscriptable)
./sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/mixedreality_account_key_credential.py:38:41 - Unknown word (mktime)
./sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/aio/_polling_async.py:25:19 - Unknown word (unsubscriptable)
./sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/aio/_remote_rendering_client_async.py:38:19 - Unknown word (unsubscriptable)
./sdk/remoterendering/azure-mixedreality-remoterendering/README.md:72:16 - Unknown word (ACCOUNTD)
./sdk/remoterendering/azure-mixedreality-remoterendering/README.md:95:16 - Unknown word (ACCOUNTD)
./sdk/remoterendering/azure-mixedreality-remoterendering/README.md:127:16 - Unknown word (ACCOUNTD)
./sdk/remoterendering/azure-mixedreality-remoterendering/samples/remote_rendering_client_sample_async.py:173:83 - Unknown word (Hololens)
./sdk/remoterendering/azure-mixedreality-remoterendering/samples/remote_rendering_client_sample.py:173:83 - Unknown word (Hololens)
./sdk/remoterendering/azure-mixedreality-remoterendering/tests/test_client_async.py:179:50 - Unknown word (thisisnotthekey)
./sdk/remoterendering/azure-mixedreality-remoterendering/tests/test_client.py:178:50 - Unknown word (thisisnotthekey)
```

**Comment by SatishBoddu-MSFT** [comment]
Hello @danieljurek Could you please let us know further action on this Github issue? Should we close or keep it open//

**Comment by danieljurek** [comment]
I think that this is something a service team developer should be addressing, not necessarily CXP.
