### ISSUE TITLE
AzureDataLakeAnalyticsLinkedService() error on passing SecureString() to service_principal_key. azure-mgmt-datafactory

### ISSUE THREAD

**Issue by glstream** [Azure/azure-sdk-for-python#2268]
When calling the AzureDataLakeAnalyticsLinkedService() and running a u-sql activity in a pipeline I am getting an error on the pipe: 'Invalid credentials AADSTS50012: Invalid client secret is provided.'

I have verified that my service_principal_key is correct and have opened this piece of the pipeline and then manually entered my service_principal_key into the linked service in the portal and then the u-sql activity works fine. 

```
adla_conn_string = AzureDataLakeAnalyticsLinkedService('myADLA'
                                        , tenant= tenantkey
                                        , service_principal_id=adla_spId
                                        , service_principal_key=SecureString('myCorrectSecret')
                                        , subscription_id=subscription_id
                                        , resource_group_name=rg_name
                                        , data_lake_analytics_uri='adl://myADLS.azuredatalakestore.net'
                                        )
```

Here is the fill error:

Activity usql-move failed: Failed to get access token by using service principal. ADAL Error: invalid_client, Error Message: AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.
Trace ID: 6ce84f70-b319-429a-aba6-0cfb8e8b0300
Correlation ID: e1942513-0da5-47ae-9937-dc7bb7f4be08
Timestamp: 2018-03-23 16:13:29Z.
<img width="771" alt="20180323_092659" src="https://user-images.githubusercontent.com/7170978/37841236-76c5a020-2e7c-11e8-8d75-ca74d07915ce.png">

**Comment by lmazuel** [comment]
@hvermis ?

**Comment by hvermis** [comment]
@linda33wj, can you take a look at this one too?

**Comment by ninishaha** [comment]
@glstream you mean you're able to make it on portal with the same key but failed using python SDK?  I'm trying to repro this issue.

**Comment by glstream** [comment]
@ninishaha Yes, after the run fails from the console using the SDK I can open the portal and edit the ADLA linked service by adding the same key I have used in the sdk script and it runs.

**Comment by ninishaha** [comment]
I can successfully create my linked service with python SDK.  Looks like service principal key is wrong based on the that error message.

**Comment by hvermis** [comment]
@glstream Has this issue been resolved?

**Comment by glstream** [comment]
Yes, it has thank you.
