### ISSUE TITLE
ADF v2 Error submitting action scripts and accessing ADLS files in Spark Activity. azure-mgmt-datafactory

### ISSUE THREAD

**Issue by glstream** [Azure/azure-sdk-for-python#2270]
My HDInsightSparkActivity() is failing to run the entry_file_path object with an error 'Spark job failed, batch id:0' in the Pipeline runs Monitor. I am also receiving an error when trying to run pySpark code against ALDS in Jupyter on the cluster that has been provisioned with the SDK. The error I am receiving is: 'fs.adl.oauth2.client.id not found' in the notebook. I am also receiving an error on the head node of the cluster when trying to install libraries from Conda-Forge: 'OSError(13, 'Permission denied')'

My Service Principal ID and Key has been validated and has access to each of the services. So the cluster that I have spun up with the SDK, does not have access to run commands on the head node, access its primary Blob storage, or access data from an Azure service like ADLS. 

Here is a portal snapshot of the additional ADLS storage access that I am not able to provision with the SDK. Although this should have nothing to do with the cluster executing post-action scripts from the blob storage, I believe that this may have something to do with the errors.

<img width="737" alt="20180321_153237" src="https://user-images.githubusercontent.com/7170978/37845056-be44d2b8-2e86-11e8-9e41-b257b00e2758.png">

Here is the code I am using to create the cluster: (please assume I have imported all the associated libraries and imported all the subscription, resource group, data factory, credentials, and client names)

```
ls_name = 'storageLinkedService'
storage_string = SecureString('MyBlobStorage')
ls_azure_storage = AzureStorageLinkedService(connection_string=storage_string)
ls = adf_client.linked_services.create_or_update(rg_name, df_name, ls_name, ls_azure_storage)
print_item(ls)
    
#Create HDinsights spark cluster ondemand linked service
    spark_ls_name = 'newrunSDKservice'
    spark_cluster = HDInsightOnDemandLinkedService(cluster_size=4
                                                , time_to_live='08:00:00'
                                                , version= '3.6'
                                                , linked_service_name=LinkedServiceReference(ls_name)
                                                , host_subscription_id = subscription_id
                                                , tenant=tenantkey
                                                , cluster_resource_group=rg
                                                , service_principal_id=spID
                                                , service_principal_key=spKey
                                                , cluster_user_name=clusterUser
                                                , cluster_password=clusterPass
                                                , cluster_ssh_user_name=clusterSSH
                                                , cluster_ssh_password=sshPass
                                                , cluster_type='spark'
                                                , spark_version='2.1'
                                                , cluster_name_prefix= 'nrun' 
                                                )
spark_ls_ref= LinkedServiceReference(spark_ls_name)
spark_ls = adf_client.linked_services.create_or_update(rg_name, df_name, spark_ls_name, spark_cluster)
print_item(spark_ls)

#Spark Activtiy
    root_path= 'input/actions' 
    entry_file_path = 'localcp.sh'
    #Create Action Activity
    spark_act_name= 'pySpark-adls'
    spark_activity = HDInsightSparkActivity(spark_act_name
                                                , root_path
                                                , entry_file_path
                                                , linked_service_name=spark_ls_ref
                                                , get_debug_info='Failure'
                                                , spark_job_linked_service=ds_ls
                                                , proxy_user=clusterUser)
 
spark_p_name = 'adls-spark'
params_for_spark_pipeline = {}
spark_p_obj = PipelineResource(activities=[spark_activity], parameters=params_for_pipeline)
spark_p = adf_client.pipelines.create_or_update(rg_name, df_name, spark_p_name, spark_p_obj)
print_item(spark_p)

spark_run_response = adf_client.pipelines.create_run(rg_name, df_name , spark_p_name, {})
spark_pipeline_run = adf_client.pipeline_runs.get(rg_name, df_name, spark_run_response.run_id)

```

**Comment by lmazuel** [comment]
@hvermis ?

**Comment by hvermis** [comment]
@linda33wj, can you please take a look at this?

**Comment by shawnxzq** [comment]
Hi glstream, you need to link your ADLS account to the cluster before you can use it, please refer to the HDI documentation for details.
https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-use-data-lake-store?toc=%2Fen-us%2Fazure%2Fhdinsight%2Fspark%2FTOC.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json

**Comment by glstream** [comment]
No I am not talking about using the ADLS as storage for the cluster. I am talking about a ADF provisioned cluster using ADLS as a service for setting up a spark context for the data transformation. I can use the blob storage for the .py files, that is fine no problem, but I want the cluster to execute against ADLS as a service. Also, there is a general error here when provisioning a cluster in ADF and having it execute action scripts from its attached BLOB storage.

**Comment by gauravmalhot** [comment]
Hi glstream, I assume that this is a Bring Your Own HDInsight Spark cluster meaning you have created the HDI cluster in azure portal and hooked it up with ADLS storage and now you are using ADF to build your pipelines that run the jobs using HDI cluster? Also, are you using ADF v1 or v2?

**Comment by glstream** [comment]
Hi @gauravmalhot. I am using ADF v2, and I am trying to spin up an on demand cluster programatically. I was under the impression that HDInsightOnDemandLinkedService() would spin up a cluster for me in ADF when its called with a sparkActivity, if I should be using HDInsightLinkedService() to get this done let me know, (maybe I am just using the wrong class!).  My understanding is that the storage linked service I use would only be for the file system of the cluster itself and not have to do with pulling files from another azure service, say ADLS. To restate the goal, I am trying to programmatically spin up a cluster (and get all the trigger, alert, time to live goodness of ADF) then execute pySpark code files stored in Azure Storage against data files in ADLS and then pass to another Azure service like SQLDB.

**Comment by shawnxzq** [comment]
Hi glstream, for ondemand cluster, we don't support create processing data from ADLS. As you restated the goal, please create a cluster in Azure Portal by yourself first, and then use ADF run your spark against this cluster, this the usage of BYOC clusters in ADF, please refer to the documentation here:
https://docs.microsoft.com/en-us/azure/data-factory/compute-linked-services#bring-your-own-compute-environment
https://docs.microsoft.com/en-us/azure/data-factory/transform-data-using-spark

BTW, you need link your ADLS account which stores your data to the cluster.

**Comment by glstream** [comment]
Ok, so there is no way for an ADF on Demand cluster to access files in ADLS, irregardless of the storage configured? Similar to the way that you provision access to ADLS in the portal? See Below...

<img width="795" alt="20180329_092049" src="https://user-images.githubusercontent.com/7170978/38100657-d72e3322-3332-11e8-9192-d5ba648c33d7.png">

We have VM's access files on ADLS in python via azure-mgmt-resource, azure-mgmt-datalake-store, azure-datalake-store.

**Comment by shawnxzq** [comment]
Yes, ADF on demand cluster can't access data from ADLS, you need to use BYOC to work around at moment.

And for BYOC cluster, you can configure the cluster to access ADLS as shown in the picture you added above.

**Comment by gstream1** [comment]
Ok, thank you for confirming @shawnxzq.

**Comment by aaronsteers** [comment]
Hi, @shawnxzq. Is this something you have on your roadmap or would consider adding? 

The workaround you propose requires an always-on cluster, which is more costly versus dynamically spinning up the cluster.

**Comment by shawnxzq** [comment]
Hi aaronsteers, we understand the workaround is not idea and it is in our backlog, but I don't have a concrete ETA for now.

**Comment by gstream1** [comment]
That sounds great, it would be great functionality to have, thank you @shawnxzq.

**Comment by haveyoumetcp** [comment]
Is there any update on getting the On demand HD Insights clusters access to ADLS (v1 or v2)?

**Comment by hvermis** [comment]
We are currently working on adding ADLS V2 support. I will update the thread once we have ETA.

**Comment by hvermis** [comment]
ADSL V2 support has been added to HDI OnDemand.
