### ISSUE TITLE
ContainerRegistryClient update methods do nothing

### ISSUE THREAD

**Issue by theoturner** [Azure/azure-sdk-for-python#22738]
- **Package Name**: azure-containerregistryclient
- **Package Version**: 1.0.0b7
- **Operating System**: MacOS Monterey 12.1 on M1
- **Python Version**:  3.8

**Describe the bug**

`azure.containerregistry.ContainerRegistryClient` has 3 update methods, none of which work. The get/list methods work fine.

**To Reproduce**

Suppose a repository with the name `myrepo` exists with the tag `mytag` at `https://myacr.azurecr.io`.

Let's attempt to update the last updated time of some objects. NB this fails on any field e.g. name, but last updated time is common to all 3 and easy to understand.

```python
from azure.containerregistry import ContainerRegistryClient, RepositoryProperties, ArtifactTagProperties, ArtifactManifestProperties
from datetime import datetime

client = ContainerRegistryClient("https://myacr.azurecr.io", DefaultAzureCredential(), audience="https://management.azure.com")
now = datetime.now()

# All 3 of these calls run without any exception raised, but nothing changes in ACR
client.update_repository_properties('myrepo', RepositoryProperties(last_updated_on=now, can_delete=True, can_read=True, can_list=True, can_write=True))
client.update_tag_properties('myrepo', 'mytag', ArtifactTagProperties(last_updated_on=now, can_delete=True, can_read=True, can_list=True, can_write=True))
client.update_manifest_properties('myrepo', 'mytag', ArtifactManifestProperties(last_updated_on=now, can_delete=True, can_read=True, can_list=True, can_write=True))
```

Nothing changes on ACR, even though these calls ran without errors.

I don't believe this is a permissions issue, because various other calls e.g. `client.get_repository_properties('myrepo')` work fine and return correct values.

Interestingly, errors are raised as expected when e.g. setting a non-existent repo or tag name.

**Expected behavior**

The properties of the selected object change, or an exception is raised explaining what is wrong.

**Comment by tjprescott** [comment]
@YalinLi0312 can you please take a look?

**Comment by annatisch** [comment]
Thanks for the report @theoturner 
While @YalinLi0312 digs into the repro - one thing I'm curious if you tried is the keyword arg syntax, i.e. something like this:
```python
client.update_repository_properties('myrepo', can_delete=True, can_read=True, can_list=True, can_write=True)
client.update_tag_properties('myrepo', 'mytag', can_delete=True, can_read=True, can_list=True, can_write=True)
```
The only updatable properties are the permissions attributes above (this is not documented well and needs to be updated), and I'm wondering if the presence of the `last_updated_on` field (which I think is automatically set by the service) might be resulting in a silent failure somewhere.....

**Comment by YalinLi0312** [comment]
Hi @theoturner, thanks for reaching out!

Not all properties of XXXProperties object are allowed to update, you could update writable properties such as `can_delete`, `can_read`, `can_list`, and `can_write`. We'll update the docstring of these functions to be more clear.

Also, you could try something below to see updates:
```python
client.update_repository_properties('myrepo', can_delete=False, can_read=False, can_list=False, can_write=False)
client.update_tag_properties('myrepo', 'mytag', can_delete=False, can_read=False, can_list=False, can_write=False)
client.update_manifest_properties('myrepo', 'mytag', can_delete=False, can_read=False, can_list=False, can_write=False)
```

Thanks

**Comment by annatisch** [comment]
Thanks @theoturner!
I have opened a PR to get these docstrings improved for clarity.
I think the intention of the name `update_properties` was to allow the methods to grow should more updatable settings become available.
