### ISSUE TITLE
Should msrestazure be required by azure-common?

### ISSUE THREAD

**Issue by solvaholic** [Azure/azure-sdk-for-python#22732]
- **Package Name**: azure-common
- **Package Version**: 1.1.27
- **Operating System**: Ubuntu 20.04.3
- **Python Version**: CPython 3.10.2

**Describe the bug**
:wave: Hiyo! It looks like **azure-common** expects to have **msrestazure** installed:

https://github.com/Azure/azure-sdk-for-python/blob/c2c5fa4fa1991a7c881cc729fd22dca4be40f48b/sdk/core/azure-common/azure/common/credentials.py#L116

and does not require **msrestazure**, or another package that requires **msrestazure**, as a dependency:

```text
# pip show azure-common
Name: azure-common
Version: 1.1.27
Summary: Microsoft Azure Client Library for Python (Common)
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /usr/local/lib/python3.10/site-packages
Requires: 
Required-by: azure-mgmt-dns, azure-mgmt-trafficmanager
```

Should **msrestazure** be required by **azure-common**?

**To Reproduce**
1. Install **azure-mgmt-dns**, **azure-mgmt-trafficmanager**, and/or **azure-common** without separately installing **msrestazure**
1. Do something that uses **azure/common/credentials.py**

**Expected behavior**
Installing **azure-common** also installs packages **azure-common** requires.

**Screenshots**
n/a

**Additional context**
See also https://github.com/octodns/octodns-azure/issues/7 about the error I encountered.

I encountered this error trying to use OctoDNS's **azure_provider** on a GitHub-hosted Actions runner:

```text
Traceback (most recent call last):
59
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/azure/common/credentials.py", line 116, in <module>
60
    from msrestazure.azure_active_directory import (
61
ModuleNotFoundError: No module named 'msrestazure'
```

**Comment by tjprescott** [comment]
@xiangyan99 it's not exactly Azure Core but there's not someone assigned for "azure-common".

**Comment by xiangyan99** [comment]
@solvaholic Thanks for reaching out. 

It is by design that azure-common does not explicitly require msrestazure.

The reason is azure.common.credentials is not always used by SDK libraries. (e.g. all track 2 libraries do not use it).

So the design is it is on the libraries who need azure.common.credentials to add requirement on msrestazure.

Thanks.

**Comment by viranch** [comment]
> azure.common.credentials is not always used by SDK libraries

In that case, might as well split the credentials stuff out into a different python package with explicit dependency on `msrestazure` and optimize rest of the `azure-common` with lesser code?

**Comment by xiangyan99** [comment]
@viranch Thanks for the suggestion. Unfortunately, splitting azure-common is a breaking change and will cause lots of pain to existing customers.

**Comment by viranch** [comment]
If `azure.common.credentials` is rarely used by customers, the split should only affect that small portion of users. If it is used by many users, it makes sense to save them the inconvenience of including `msrestazure`. What do you think?

**Comment by xiangyan99** [comment]
azure.common.credentials is still used by track 1 libraries.

It is unfortunately that track 1 libraries and track 2 libraries share azure-common component.

Currently, all track 1 libraries explicitly require msrestazure while track 2 libraries do not need it.

**Comment by viranch** [comment]
Can you clarify what are track 1 and track 2 libraries?

**Comment by xiangyan99** [comment]
You can find this information on https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-overview.

---

We're currently updating the Azure libraries for Python libraries to share common cloud patterns such as authentication protocols, logging, tracing, transport protocols, buffered responses, and retries.

This shared functionality is contained in the azure-core library.

The libraries that currently work with the Core library are listed on Azure SDK for Python latest releases. These libraries, primarily the client libraries, are sometimes referred to as "track 2".

The management libraries and any other that aren't yet updated are sometimes referred to as "track 1".

**Comment by viranch** [comment]
Great info, thanks!
