### ISSUE TITLE
Tensorboard not launching in AzureML ComputeVM in a vNet setup

### ISSUE THREAD

**Issue by pratyushhacks** [Azure/azure-sdk-for-python#22749]
- **Tensorboard**: 
- **2.7.0**: 
- **Linux**:
- **3.8.1**: 

**Describe the bug**
Tensorboard for viewing AzureML experiment data fails to launch in a AzureML workspace set up in a vNET. The site is unaccessible. I have tried changing the URL from https://computevmname-6006.eastus2.instances.azureml.ms/ to https://computevmname.eastus2.instances.azureml.ms:6006/, but still the connection gets timed out.
<img width="850" alt="launch_tensorboard04" src="https://user-images.githubusercontent.com/91281838/150896235-cae04e81-db9e-4259-b358-0e9bad5d8b4b.png">
<img width="653" alt="launch_tensorboard03" src="https://user-images.githubusercontent.com/91281838/150896105-7bca1104-0945-4fbe-a13a-8d123d26ccbc.png">
<img width="868" alt="launch_tensorboard02" src="https://user-images.githubusercontent.com/91281838/150896106-6ae2cccb-7118-4f82-9a8e-6e49e3f56fac.png">
<img width="844" alt="launch_tensorboard01" src="https://user-images.githubusercontent.com/91281838/150896108-30e3101e-1699-47a1-aaf8-c9eeef10e711.png">

**To Reproduce**
1. Setup a secure AzureML workspace in a vNet use this link: https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-create-secure-workspace

2. Follow example [here ](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-monitor-tensorboard)to run experiment and log experiment run data to tensorboard

3. Try launching tensorbord to view the run details

4. You will see page not found.

**Expected behavior**
We are able to launch tensorboard in AzureML workspace in a vNet and see various experiment metrics in there.

**Screenshots**

**Additional context**
I also tried launching tensorboard directly from the ComputeVM terminal and it seems to start the service on http://localhost:6006 but if you try accessing it, the network connection fails. Seems like firewall or nsg rules are blocking access to this port.

**Comment by tjprescott** [comment]
@pratyushhacks it's unclear to me--are you actually using the Python SDK?

**Comment by tjprescott** [comment]
If there's an issue with the tutorial, there's a button at the bottom that will open the issue in the correct repo (in this case azure-docs):
![image](https://user-images.githubusercontent.com/5723682/151043255-1e295f6e-519f-439f-816d-9c321ed53a4e.png)

**Comment by pratyushhacks** [comment]
Hi, 
No, I dont think the issue is with the tutorial. The code sample runs. What doesn't work is when you try browsing the tensorboard  dashboard. The dashboard site is unreachable. When you run tb.start(), it starts tensorboard dashabord and outputs the URL to use to view the dashboard, but when you click on the URL, the tensorboard site isnt reachable.

**Comment by tjprescott** [comment]
@pratyushhacks this repo is for issues using the Azure Python SDK, which you aren't using..

Your best course of action would be to open the issue from the page you are trying to use, as that will be the quickest way to get routed to the service team. You could also open a ticket from the Azure Portal, but opening it from the page will give them immediate context on what you were trying to follow.

**Comment by pratyushhacks** [comment]
Thanks. Will open a new issue from that page. Closing this bug.
