### ISSUE TITLE
`get_api_version` and `set_immutability_policy` fails to typecheck with Mypy

### ISSUE THREAD

**Issue by jmg-duarte** [Azure/azure-sdk-for-python#22740]
Mypy fails to typecheck the functions in the title

Affected files:
```
azure.storage.blob._serialize
azure.storage.blob._blob_client
```

**Comment by tjprescott** [comment]
@tasherif-msft can you please take a look?

**Comment by tjprescott** [comment]
Actually, @tasherif-msft it looks like @jmg-duarte opened a PR to fix this (thank you!). Please see:
https://github.com/Azure/azure-sdk-for-python/issues/22741

**Comment by tasherif-msft** [comment]
@tjprescott @jmg-duarte thanks for opening the PR - I have merged it in!
