### ISSUE TITLE
[Identity] fix casing of Troublshooting.md to match other top level md files

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-python#22743]
The file name casing of https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/Troubleshoot.md doesn't match the convention of using all uppercase for top level md files, such as README.md and CHANGELOG.md.
- [x] Rename Troubleshooting.md to TROUBLESHOOTING.md
- [x] Update all references in the readme or other docs, as well as any aka.ms links.

**Comment by xiangyan99** [comment]
#22771
