### ISSUE TITLE
TableClient.query_entities cannot return the Timestamp field?

### ISSUE THREAD

**Issue by klenium** [Azure/azure-sdk-for-python#22763]
I'm trying to query entities. Nothing complex, just a hello world query_entities execution.

The entity is returned, I can see all of it's properties. Except the Timestamp. I pass the Timestamp field's name explicitly to the select parameter, but it's not returned (only other columns). Why is that?

It cannot be queried? But the Azure Storage Explorer and the Azure SDK in other languages (as far as I know) can query and display the Timestamp field.

Is there any other alternative way of getting the Timestamp value of an Azure Table entity?

**Comment by annatisch** [comment]
Thanks @klenium!
You should be able to access the service-populated fields via the `metadata` attribute on the returned entity.
I believe it should look something like this:
```python
entities = client.query_entities("...")
for entity in entities:
    print("Timestamp: {}".format(entity.metadata['Timestamp']))
```

**Comment by klenium** [comment]
Thank you!
`print(entity)` tricked me, as the result looks like a normal dictionary. But it's a `TableEntity` which can do more. Nice. :)
(the key's name is `timestamp`, first char is lower).

**Comment by annatisch** [comment]
Great to hear it's working. Thanks again for reporting :)
