### ISSUE TITLE
Code: EndpointUnsupportedAccountFeatures Message: This endpoint does not support BlobStorageEvents or SoftDelete. 

### ISSUE THREAD

**Issue by javiercoh** [Azure/azure-sdk-for-python#22775]
- **Package Name**: azure_storage_file_datalake
- **Package Version**: 12.5.0
- **Operating System**: Windows 10
- **Python Version**: 3.9.10

**Describe the bug**
I have disabled SoftDelete for blobs and containers and have no BlobStorageEvents but when I run the following code:

`       initialize_storage_account()

        file_system_client = service_client.get_file_system_client(file_system="perfectStore")

        i = 0

        LOCALFILENAME_TEMP = LOCALFILENAME + '-temp_' + str(i) + ".csv"

        paths = file_system_client.get_paths(path=blob_dir)

        for path in paths:

            print(path.name + '\n')`

I get:

`Code: EndpointUnsupportedAccountFeatures
Message: This endpoint does not support BlobStorageEvents or SoftDelete. Please disable these account features if you would like to use this endpoint.
RequestId:05bc1ea9-001f-005c-0a56-12102f000000
Time:2022-01-26T01:45:53.3527214Z`

at line `for path in paths:`

**To Reproduce**
1.  create adl2 file system
2. disabled SoftDelete (Data Protection panel)
3. Checked in Events panel for any subscription to Events (no subscriptions found) (BlobStorageEvents)
4. ran code above

**Expected behavior**
code should loop through paths without throwing errors

**Others**
I was following the steps detailed here: https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-python

**Comment by tjprescott** [comment]
@tasherif-msft do you know who is responsible for Data Lake issues?

**Comment by tasherif-msft** [comment]
@jalauzon-msft

**Comment by jalauzon-msft** [comment]
Hi @javiercoh, thanks for reporting the issue. We will investigate and get back to you shortly.

**Comment by javiercoh** [comment]
hi @jalauzon-msft any news on this? I tried many changes to the config of the datalake with no success so far... this is a key feature for us

**Comment by jalauzon-msft** [comment]
Hi @javiercoh, I am having trouble reproducing this issue. Would you mind sharing a recent request id from a recent failure you had? This will let me look into the service logs for more information. The service logs are only retained for a couple of days so the more recent your request, the better. Thanks.
