### ISSUE TITLE
[core] add chained authentication policy

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#22789]
Add a chained authentication policy that delegates to either `BearerTokenCredentialPolicy` or `AzureKeyCredentialPolicy`, based off of the type of the credential.

The chained authentication policy should just take in the `credential` as an input, and delegate to other credential policies during `on_request`.

**Comment by lmazuel** [comment]
We implemented it differently, I don't think we need this issue still
