### ISSUE TITLE
Event Hubs readme and samples issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#22780]
1.Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/samples/sync_samples/client_creation.py#L34), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/samples/sync_samples/client_creation.py#L70):
![image](https://user-images.githubusercontent.com/80307197/151112254-28d00068-0a2a-47db-b0d1-e4c4dbae210e.png)

Reason:
ValueError: The eventhub name can not be None or empty.

Suggestion:
Add a parameter `eventhub_name=EVENTHUB_NAME`

@jameszliao-msft, @lmazuel, @lilyjma, @ramya-rao-a, @annatisch for notification.

**Comment by v-xuto** [comment]
Close it , because it's not an issue.
