### ISSUE TITLE
Docs: There is no description as to the behaviour of the Match Conditions

### ISSUE THREAD

**Issue by metamoof** [Azure/azure-sdk-for-python#22808]
You've listed the Match Conditions enum in the documentation, but you do not explain what the behaviour is for these conditions.

Similarly, the description is not available in the cosmosdb docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c1e5642-e4f7-202d-b3ef-871ee0ff66cb
* Version Independent ID: aa8729ae-b13b-bcb7-b87b-85f956f4abf8
* Content: [azure.core.MatchConditions enum](https://docs.microsoft.com/en-us/python/api/azure-core/azure.core.matchconditions?view=azure-python)
* Content Source: [docs-ref-autogen/azure-core/azure.core.MatchConditions.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-core/azure.core.MatchConditions.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by tjprescott** [comment]
@xiangyan99 can you take a look?

**Comment by xiangyan99** [comment]
The exact behavior of MatchConditions may vary from service to service.

Given "cosmosdb docs" is mentioned here. I would assign this to cosmos owner.

**Comment by tjprescott** [comment]
@xiangyan99 the content is from Azure Core:

> Content: azure.core.MatchConditions enum
> Content Source: docs-ref-autogen/azure-core/azure.core.MatchConditions.yml

**Comment by xiangyan99** [comment]
Yes. But the behavior may be different. e.g. in cosmos:

```py
match_condition = kwargs.pop('match_condition', None)
    if match_condition == MatchConditions.IfNotModified:
        if_match = kwargs.pop('etag', None)
        if not if_match:
            raise ValueError("'match_condition' specified without 'etag'.")
    elif match_condition == MatchConditions.IfPresent:
        if_match = '*'
    elif match_condition == MatchConditions.IfModified:
        if_none_match = kwargs.pop('etag', None)
        if not if_none_match:
            raise ValueError("'match_condition' specified without 'etag'.")
    elif match_condition == MatchConditions.IfMissing:
        if_none_match = '*'
    elif match_condition is None:
        if 'etag' in kwargs:
            raise ValueError("'etag' specified without 'match_condition'.")
    else:
        raise TypeError("Invalid match condition: {}".format(match_condition))
```

I think it will be better to describe the behavior in the method that supports MatchCondition, your ideas?

**Comment by tjprescott** [comment]
The way I read it is the docs from Azure Core are not useful and CosmosDB doesn't even have docs.

**Comment by metamoof** [comment]
If it helps you narrow down the issue, I started by looking at the docs for [upsert-item](https://docs.microsoft.com/en-gb/python/api/azure-cosmos/azure.cosmos.container.containerproxy?view=azure-python#azure-cosmos-container-containerproxy-upsert-item). There it states:

```
etag str
An ETag value, or the wildcard character (*). Used to check if the resource has changed, and act according to the condition specified by the match_condition parameter.

match_condition MatchConditions
The match condition to use upon the etag.
```

Which is definitely not useful to understand which of the MatchConditions to use.

This is especially confusing as the main [cosmosdb docs page on optimistic concurrency](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/database-transactions-optimistic-concurrency#optimistic-concurrency-control) talks about `if-match` and `if-none-match` headers, which is a completely different API and behaviour (though, seeing the snippet above, this is merely a translation to those headers).

**Comment by metamoof** [comment]
A quick look at [the source file](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/azure/cosmos/container.py) shows that this same language is used in four different methods: `replace_item`, `upsert_item`, `create_item`, and `delete_item`.

Ideally, this behaviour should be documented either in those methods, or in the MatchCondition enum. The MatchCondition that will bring about the default behaviour for each method should be specified in that method, (e.g. `IfNotPresent` for `create_item` is what I assume is the default behaviour), or what the default behaviour is when this keyword is not specified. It's difficult to work out what each option does, as it translates into headers that are then interpreted in different ways by the cosmos server, so tracing through the code doesn't get you anywhere.

Also, it's not clear from the docs (though exceptions do tell us) that the `match_condition` keyword is compulsory when the `etag` keyword is used (though not vice-versa).

Finally, an indication of what the expected behaviour is when the condition is not met would be helpful, so we know to catch the right sort of Exception and handle it.

Also, it would be helpful to indicate that you're
