### ISSUE TITLE
Feature to add auxiliary authorization header

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#22813]
We have auxiliary authorization header support for Java.

https://github.com/Azure/azure-libraries-for-java/pull/884

Let's also add the support in Python to keep them consistent.

**Comment by nvigne** [comment]
I think it is already tracked by this one #8544

**Comment by msyyc** [comment]
https://pypi.org/project/azure-mgmt-core/1.4.0/
