### ISSUE TITLE
Improve doc of the get_token protocol in azure-core

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#22824]
since we dropped Python 2 I would advocate to rewrite get_token in Python 3 syntax, with the right docstring:

```python
"""Protocol for classes able to provide OAuth tokens.

:param str scopes: Lets you specify the type of access needed.
:keyword str tenant_id: Injected by SDK if scenario X, Y and Z are supported

@seealso aka.ms/azsdk/python/core#credentials
"""
def get_token(
   *scopes : str,
   *,
   tenant_id : Optional[str],
   **kwargs : Any
) -> azure.core.credentials.AccessToken
```

Also, we have a dev specific documentation of azure.core: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md

**Comment by jiasli** [comment]
Shouldn't docstring go under `def`? https://www.python.org/dev/peps/pep-0257/

IDEs currently can't recognize `:param`:

![image](https://user-images.githubusercontent.com/4003950/151643082-b4bedb9c-75e7-40b1-92aa-838590ec4d27.png)

After we put docstring under `def`:

![image](https://user-images.githubusercontent.com/4003950/151643096-ba624284-b275-47a0-b464-9cd60a560b93.png)
