### ISSUE TITLE
Enable Warnings as Errors (possibly also nit-picky) in Sphinx doc generation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#22826]
We have instances of pages where errors in our doc comments are producing unexpected documentation output. These errors are detectable in Sphinx and we should move that detection to the left in the process. 

Sphinx params: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-W

Example: 

See the `Raises` section here: 

Docs page -- https://review.docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebussender?branch=main&view=azure-python#azure-servicebus-servicebussender-send-messages
GitHub IO page -- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/7.5.0/azure.servicebus.html#azure.servicebus.ServiceBusSender.send_messages

Source -- https://github.com/Azure/azure-sdk-for-python/blob/1380f96db18b03e993552973acb99d9170ffeb9f/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py#L401

Fix: Use backticks around the class name. 

There are likely other issues and fixes as well. 

Internal issue tracking: https://dev.azure.com/ceapex/Engineering/_workitems/edit/548063?src=WorkItemMention&src-action=artifact_link

**Comment by kurtzeborn** [comment]
This is obsolete.  It will be addressed in a different way once we get the REX validation tool for Python from the docs team (delivery is imminent).
