### ISSUE TITLE
[AMQP Python] Revisit logging message and level

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#22835]
https://github.com/Azure/azure-uamqp-python/pull/283#discussion_r753602450

as per Anna's comment: "The log message is general could probably be a bit more informative as to what these status mean and whether I should do anything. If they are completely non-actionable, then we can probably make them debug."

We should revisit the error logging information to decide on:

- log level
- log message
- guidance

**Comment by annatisch** [comment]
Thanks @yunhaoling - yes we should do a full assessment of logging statements before GA.
You'll see throughout the code that I had started using the `extra=self.network_trace_params` for containing "optional extra" information in the logging messages. Customers can chose to format these values into their log messages, as documented here:
https://docs.python.org/3/library/logging.html#logging.debug

I'm not sure if this is the best/right way, but is an efficient means of providing some debug details:
https://github.com/Azure/azure-uamqp-python/blob/pyproto/uamqp/_connection.py#L111-L115

**Comment by swathipil** [comment]
get rid of all logging for expected/passing case in this file: https://github.com/Azure/azure-sdk-for-python/blob/c143274b96c29bc5e17e893164222abf0098bbc5/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/cbs.py#L155
remove misc debug logging: https://github.com/Azure/azure-sdk-for-python/blob/c143274b96c29bc5e17e893164222abf0098bbc5/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py#L250
or set pytest logging default to NOT DEBUG or some other level
