### ISSUE TITLE
Authentication in Azure Devops

### ISSUE THREAD

**Issue by anotherancientalien** [Azure/azure-sdk-for-python#22840]
Hi,

I want to use SDK inside a pipeline task. But I get token in another task as follow:

`$token= $( az account get-access-token --resource=https://management.azure.com --query accessToken)
Write-Host("##vso[task.setvariable variable=api-token;issecret=true]$token")`

Is there anyway to use this token with SDK? Because I get token with service connection and I don't store client and tenant info in environment variables.

Any advice would be appreciated.

Best

**Comment by swathipil** [comment]
Thanks for the question @anotherancientalien!
To clarify: Does your task look something like this (where the token is saved in `$token`)?
```
- pwsh: |
      $token= $( az account get-access-token --resource=https://management.azure.com --query accessToken)
      Write-Host("##vso[task.setvariable variable=api-token;issecret=true]$token")
```
And you would like to set this token value to an env var so that it's available where you run your code file?

If so, you can set the token to an environment variable by adding it to `env:` like this:
```
- pwsh: |
      $token= $( az account get-access-token --resource=https://management.azure.com --query accessToken)
      Write-Host("##vso[task.setvariable variable=api-token;issecret=true]$token")
  env:
      API_TOKEN: $(api-token)
```
This may also be helpful, if you haven't taken a look already. https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables

If this isn't what you're looking to do, can you clarify?

Thanks!

**Comment by anotherancientalien** [comment]
Hi @swathipil ,

I appreciate your kind help.

Please consider this code:


def get_credentials():
```
    subscription_id = az_subscription_id
    credentials = ClientSecretCredential(
        client_id=az_client_id,
        client_secret=az_secret,
        tenant_id=az_tenant_id
    )
    return credentials, subscription_id


credentials, subscription_id = get_credentials()
backup_client = RecoveryServicesBackupClient(credentials, subscription_id)
```

SDK uses object in `RecoveryServicesBackupClient(credentials, subscription_id)` as credentials. But I have only token that I get from 

`- pwsh: |
      $token= $( az account get-access-token --resource=https://management.azure.com --query accessToken)
      Write-Host("##vso[task.setvariable variable=api-token;issecret=true]$token")`

How ca I use `$token` in `backup_client = RecoveryServicesBackupClient(credentials, subscription_id)`

Best,

**Comment by swathipil** [comment]
Thanks for the info @anotherancientalien! @mccoyp will be taking a look at this.

**Comment by mccoyp** [comment]
Hi @anotherancientalien, thank you for opening an issue and providing additional information! If you'd like to use the access token directly and don't need/want a credential to automatically refresh it, [this sample](https://github.com/Azure/azure-sdk-for-python/blob/fc95f8d3d84d076ffea158116ca1bf6912689c70/sdk/identity/azure-identity/samples/custom_credentials.py#L18) from `azure-identity` should be what you're looking for. After declaring a StaticTokenCredential type like the sample shows, you can do something like the following:
```python
credential = StaticTokenCredential(token)  # token is the access token acquired from the Azure CLI
backup_client = RecoveryServicesBackupClient(credential, subscription_id)
```
Note that you will still have to provide the subscription ID and that the credential won't be usable after the access token expires.

**Comment by anotherancientalien** [comment]
@mccoyp A million thanks!
