### ISSUE TITLE
Switch-AzWebAppSlot with preview

### ISSUE THREAD

**Issue by oancea-cristian** [Azure/azure-sdk-for-python#22844]
I need to swap staging and production slots with preview so I can run warm-up tests after the application settings have been applied to the staging slot and the restart happened but before the actual swap is being done.

A way to access [Switch-AzWebAppSlot](https://docs.microsoft.com/en-us/powershell/module/az.websites/switch-azwebappslot?view=azps-7.1.0) from python

**Comment by swathipil** [comment]
Hi @oancea-cristian, thanks for the question! We'll investigate asap!

**Comment by MughundhanRaveendran-MSFT** [comment]
@oancea-cristian , Check if this is helpful or not
https://github.com/Azure/azure-cli/blob/e0c49d6fd4778b8e0c8884a54bca1716a916763e/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L1285

**Comment by oancea-cristian** [comment]
@MughundhanRaveendran-MSFT thanks for your reply. By looking in Azure portal at swap with preview I can see that it is broken in two parts:
1st: In phase one, any slot-specific application settings and connections strings on the destination will be temporarily copied to the source slot
2nd: Swap the source slot with the destination slot

After looking at the code you provided I see that the first part is covered by apply_slot_config_to_production() however in the docs provided by the framework itself it says: `"""Applies the configuration settings from the target slot onto the current slot.` which is the opposite of what is described in the Azure portal.

Also note that the second part can be covered by begin_swap_slot_with_production() since I can't find any references for swap_slot_with_production()

If I am missing something or doing something wrong please let me know.
