### ISSUE TITLE
[ServiceBus] add more stress tests

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#22852]
- add docs/README to stress tests for SB + EH (follow the README in the `perfstress_tests` as an example)
- split up existing tests into separate files
- add more tests (infinite send + receive, other scenarios) - look at Go for example
- test chaos/network loss for infinite send and receive.
- address Richard's comments from this PR: https://github.com/Azure/azure-sdk-for-python/pull/22982

**Comment by swathipil** [comment]
fix failing stress tests:
`FAILED test_stress_queues.py::test_stress_queue_long_renew_session_send_and_receive`

`2/8/2022, 7:58:44 PM | stress-python-servicebus-stress-test-4--1-cmgb4 | python-sb-stress | FAILED test_stress_queues.py::test_stress_queue_check_for_dropped_messages`

`ERROR azure_logger_test_stress_queue_check_for_dropped_messages:app_insights_metric.py:102 Error happened when running test_stress_queue_check_for_dropped_messages: ValueError("invalid literal for int() with base 10: 'aaaaaaaaaa'"). Extra info: None`
During handling above exception, another exception occurred:
`azure.servicebus.exceptions.ServiceBusError: A sessionful message receiver cannot be created on an entity that does not require sessions. Ensure RequiresSession is set to true when creating a Queue or Subscription to enable sessionful behavior. TrackingId:502738cb-83a0-4150-8bc8-9ae38eb9ef93_B2, SystemTracker:t00ae01b19ced4ea2:Queue:testqueue, Timestamp:2022-02-09T03:48:29 TrackingId:3436d5c6d72943e587d3d13418f207d9_G52, SystemTracker:gateway7, Timestamp:2022-02-09T03:48:29 Error condition: ErrorCodes.NotAllowed.`
`
> result = stress_test.run() |  
> body = int(str(received_message))
`

**Comment by yunhaoling** [comment]
align with Go/JS tasks

**Comment by swathipil** [comment]
update resource group name in ARM template as per: https://github.com/Azure/azure-sdk-for-python/pull/24010#discussion_r855676209

**Comment by swathipil** [comment]
done by @l0lawrence
