### ISSUE TITLE
Not being able to list role assignments  for a subscription

### ISSUE THREAD

**Issue by meglenast** [Azure/azure-sdk-for-python#22873]
Hello, I am trying the following in order to list the role assignments  for a subscription .

```
from azure.mgmt.authorization import AuthorizationManagementClient
from azure.identity import ClientSecretCredential

tenant_id = 'XXX'
client_id = 'XXX'
client_secret = 'XXX'
subscription_id = 'XXX'

credentials = ClientSecretCredential(
    client_id=client_id,
    client_secret=client_secret,
    tenant_id=tenant_id)

client = AuthorizationManagementClient(
    credential=credentials,
    subscription_id=subscription_id)

roles = client.role_assignments.list()
for role in roles:
    print(role)
```

However, the response I am getting is not the expected one. I am getting an empty list and not the list of all role assignments  for the particular  subscription_id.

**Comment by swathipil** [comment]
Hi @meglenast - thanks for your question! Directing this to the right people.

**Comment by SaurabhSharma-MSFT** [comment]
@meglenast What are your RBAC permissions level on the subscription ?

**Comment by meglenast** [comment]
So I found the problem the **Service Principal**  which is associated with the **client_id** in my case has the 'Management Group Contributor' role which does not have the necessary 'Action'. A solution to this is giving the service principal 'Reader' or 'User Access Administrator' permissions. In other words '*/read' action is required to perform listing the role assignments of a subscription.

**Comment by anotherancientalien** [comment]
@SaurabhSharma-MSFT I have the same issue that giving the service principal 'Reader' or 'User Access Administrator' permissions doesn't solve the problem. What is the necessary permissions for backup? Thanks

https://github.com/Azure/azure-sdk-for-python/issues/23402
