### ISSUE TITLE
[ServiceBus] accept `application_properties` kwarg in `ServiceBusReceiver.dead_letter_message`

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#22881]
Allow user to pass `application_properties` to `ServiceBusReceiver.dead_letter_message`. Ensure that this is set on ReceivedMessage received from deadletterqueue.

### background

- .NET supports modify properties when deadlettering messages.
- `Deadletter` in service bus using `Message Reject` of the AMQP spec to indicate the delivery state of a message
- Message reject could take extra error information which **might** be the place where users could update the `properties` of a message (need confirmation with .Net team)

here's the AMQP spec:
http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-rejected

![image](https://user-images.githubusercontent.com/47871814/162846828-ae1e1ca9-05b2-4418-8d36-56a0ec3a9bdb.png)

![image](https://user-images.githubusercontent.com/47871814/162846842-48915818-d07c-4da8-8987-dfd4ddfdcf51.png)

### related APIs

[sync receiver](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py#L885-L890) and [async receiver](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py#L863-L868)

The api will look like:

```python
    def dead_letter_message(
        self,
        message: ServiceBusReceivedMessage,
        reason: Optional[str] = None,
        error_description: Optional[str] = None,
        properties_to_modify: Optional[dict] = None,  # naming TBD
    ) -> None:
```

### related code details

uamqp should already support setting `info` field of `reject` via https://github.com/Azure/azure-uamqp-python/blob/master/uamqp/message.py#L501.

for service bus, it should accept a new keyword argument which is dictionary, and pass it as the `info` when calling uamqp reject message.

**Comment by JoshLove-msft** [comment]
Note, the param should be named something like "properties_to_modify" as the user wouldn't need to pass all the application properties.

**Comment by yunhaoling** [comment]
this is for cross-language feature consistency
