### ISSUE TITLE
[QUESTION] How to mock Blob Client in Unit Tests?

### ISSUE THREAD

**Issue by DhavalShewale** [Azure/azure-sdk-for-python#22917]
Library: **`azure-storage-blob`**

I would like to mock below **`BlobClient`** implementation

```
...
...

with BlobClient(account_url='url', container_name='container', blob_name='blob', credential='credential') as blob_client:
    blob_client.upload_blob('blob data')

...
...
```

I tried the below implementations but none of them work and actual object is getting called

```
@patch('my_prod_func_file.BlobClient.__init__')
@patch('my_prod_func_file.BlobClient.upload_blob')
def test_my_prod_func(self, mock_upload_blob, mock_blob_client_init):
   ...
   ...
```

```
@patch.object('BlobClient, '__init__')
@patch.object('BlobClient, 'upload_blob')
def test_my_prod_func(self, mock_upload_blob, mock_blob_client_init):
   ...
   ...
```

Can you pls advise on what is the correct way to mock **`BlobClient`**

**Comment by swathipil** [comment]
@DhavalShewale - thanks for your question! Directing this to the right people.

**Comment by amishra-dev** [comment]
@tasherif-msft do we have a sample that shows how to mock?

**Comment by DhavalShewale** [comment]
Any updates on this?

**Comment by jalauzon-msft** [comment]
Hi @DhavalShewale Dhaval, sorry for the long delay on this. We don't have any specific recommendations for mocking our clients. Typical methods for mocking should apply fine to our clients.

You can take a look at [unittest.mock](https://docs.python.org/3/library/unittest.mock.html) from the Python `unittest` or if you are using `pytest` you could also look into [pytest mocking](https://docs.pytest.org/en/6.2.x/monkeypatch.html)

**Comment by jalauzon-msft** [comment]
Hi @DhavalShewale Dhaval, apologies for the long delay. We have no special recommendations around mocking our clients. The typical use of `unittest.mock` should work ([docs](https://docs.python.org/3/library/unittest.mock-examples.html)).

I believe your example is not working as your patch statements are not quite correct. I don't think the first example if a supported way to patch so I would recommend going with something like your second example with a couple of changes. Something like this should work.
```python
class MyTest(unittest.TestCase):
    @patch.object(BlobClient, 'upload_blob')
    def test(self, upload_blob):
        my_prod_func()
        upload_blob.assert_called()

MyTest('test').test()
```

I believe you had an extra `'` in your example so it was not properly applying the mock. Additionally, I would just mock the `upload_function` and not `__init__`.

Another way you could do it would be to mock the import using a string:
```python
class MyTest(unittest.TestCase):
    @patch('azure.storage.blob.BlobClient.upload_blob')
    def test2(self, upload_blob):
        my_prod_func()
        upload_blob.assert_called()

MyTest('test2').test2()
```

And finally a third option is to mock the entire class:
```python
class MyTest(unittest.TestCase):
    @patch('azure.storage.blob.BlobClient')
    def test3(self, MockBlobClient):
        my_prod_func()

MyTest('test3').test3()
```

I hope that helps!
