### ISSUE TITLE
azure-mgmt module for function app

### ISSUE THREAD

**Issue by yks0000** [Azure/azure-sdk-for-python#22916]
**Is your feature request related to a problem? Please describe.**
I am trying to get function app details similar to what we see when we run `az functionapp show` command.

**Describe the solution you'd like**
Should be able to return functionapp details as available in `az functionapp` command

**Describe alternatives you've considered**
Nothing available or found at the moment. We can not use az cli in Function as well also there is no way to get details of FunctionApp in runtime from Function itself.

**Additional context**

We need to have something like python azure-mgmt-function like module which when called should show information about function such as Outbound IP, VNet is enabled or disabled etc.

**Comment by swathipil** [comment]
@yks0000 - thanks for opening an issue. We'll investigate asap!

**Comment by SaurabhSharma-MSFT** [comment]
@yks0000 I am redirecting this to specific team for this feature request.

**Comment by jacky9813** [comment]
After digging into azure-cli, which is also written in Python, the function app seems to be part of the web app, which can be accessed with `azure-mgmt-web` package:

```python
import azure.mgmt.web
import azure.identity

def is_function_app(app):
    return (
        app is not None and
        app.kind is not None and
        "workflowapp" not in app.kind and
        "functionapp" in app.kind
    )

client = azure.mgmt.web.WebSiteManagementClient(
    azure.identity.DefaultAzureCredential(),
    "12345678-90ab-cdef-1234-567890abcdef"
)

function_apps = [
    app
    for app client.web_apps.list()
    if is_function_app(app)
]
```

Although the REST API doesn't have dedicated method for Function Apps operations, it would be better if Azure Python SDK can mention something in the documentation somewhere.

Reference: `list_function_app` function in [azure.cli.command_modules.appservice.custom](https://github.com/Azure/azure-cli/blob/c2484454166a0f237be48b8e259533207eac1854/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L1025)
