### ISSUE TITLE
The `connection_timeout` parameter is not documented for the `upload_blob` method on `BlobClient`

### ISSUE THREAD

**Issue by joelrbrandt** [Azure/azure-sdk-for-python#22936]
The `connection_timeout` parameter is not documented for the `upload_blob` method on `BlobClient`.

That parameter _is_ documented here:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#other-client--per-operation-configuration

Also, the `connection_timeout` parameter works differently than the `timeout` parameter, which is very confusing!

I was experiencing problems with uploads timing out when the upload size was near the default 64MB limit for single PUT requests. I thought that the `timeout` parameter would fix this. But it doesn't! Instead, the `connection_timeout` parameter must be used.

As an aside, it is incredibly frustrating that I can't configure the `max_single_put_size` parameter when I create a `BlobClient` using the `BlobClient.from_blob_url` control flow. In my application, I want the library user to be able to manipulate a blob using an SAS url without having access to the entire storage account's underlying credentials.

As near as I can tell, there's no way to construct a `BlobClient` from a SAS url that allows me to adjust this parameter. If there's something I've missed, please let me know, because I would like to do this!

Also, it's my personal opinion that 4MB would be a much more reasonable default for `max_single_put_size` than 64MB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a557056-1da5-6c2d-fcee-e4e246a7a221
* Version Independent ID: 9ee6555a-aaca-243f-409e-1ac5881e3dbc
* Content: [azure.storage.blob.BlobClient class](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.BlobClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-storage-blob/azure.storage.blob.BlobClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by amishra-dev** [comment]
Hi @joelrbrandt Joel, thanks for you feedback. @jalauzon-msft can you please look into this.

**Comment by jalauzon-msft** [comment]
Hi @joelrbrandt, thanks for the feedback.

The `connection_timeout` parameter is not meant to be defined on individual methods, such as `upload_blob` but rather is an optional parameter when creating clients as defined in the [link you mentioned](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#other-client--per-operation-configuration).

The `connection_timeout` parameter sets the client-side socket timeout whereas the `timeout` parameter is passed to the service as a server-side timeout where the server will return if the operation is not completed in the defined time period.

The documentation for timeouts and their default values could be clearer and we are working on looking at timeouts wholistically across all languages to ensure we have consistent and correct defaults values and documentation. We will likely make some changes here as part of that effort.

**Comment by jalauzon-msft** [comment]
@joelrbrandt as for your aside about `max_single_put_size`, there are a couple of ways to specify that parameter with a SAS URL.

`BlobClient.from_blob_url` actually does accept the `max_single_put_size` keyword parameter even though it is not explictlly documented. `from_blob_url` eventually calls into the normal constructor of `BlobClient` so any keyword arguments that the constructor can take, will work with `blob_from_url` as well.
```python
blob_client = BlobClient.from_blob_url(blob_sas_url, max_single_put_size=4*1024*1024)
```

Additionally you can construct a `BlobClient` using the `credential` parameter to specify your SAS and pass `max_single_put_size`.
```python
blob_client = BlobClient(
    "https://{}.blob.core.windows.net".format(ACCOUNT_NAME),
    container_name,
    blob_name,
    credential=sas_token,  # Just the result of `generate_blob_sas` or `generate_container_sas`
    max_single_put_size=4*1024*1024)
```

**Comment by jalauzon-msft** [comment]
Closing as `connection_timeout` is not meant to be documented on individual methods and is an optional parameter on clients that is documented in the `README`.
