### ISSUE TITLE
[ServiceBus] Cannot read messages from subscription when using DefaultAzureCredentials

### ISSUE THREAD

**Issue by lukipro** [Azure/azure-sdk-for-python#22962]
- **Package Name**: azure-servicebus
- **Package Version**: 7.5.0
- **Operating System**: Linux
- **Python Version**: 3.9.10

**Describe the bug**
When creating the `ServiceBusClient` using `DefaultAzureCredential` for authentication I cannot read any messages.
I get the following error:
```ValueError: Only azure.servicebus.ServiceBusReceivedMessage objects in PEEK_LOCK receive mode maybe lock-renewed.  (E.g. only messages received via receive() or the receiver iterator,not using RECEIVE_AND_DELETE receive mode, and not returned from Peek)```

It works fine when creating the `ServiceBusClient` using the `from_connection_string` method.

**To Reproduce**
1. Create a `ServiceBusClient` using `DefaultAzureCredential` and start receiving messages.
2. Messages are not received, instead the ValueError is thrown.

**Expected behavior**
Messages should be received.

**Screenshots**
N/A

**Additional context**
For newly created Service Bus Namespace it works fine. The thing is that we have Service Bus Namespaces created few years back which we cannot recreate. For subscription in those old SB Namespaces using DefaultAzureCredential doesn't work :(

**Comment by lukipro** [comment]
I noticed a difference between the working and not working scenarios w.r.t. the `locked_until_utc` field on the `eceiver.session` object:

1. For the case where it works the `locked_until_utc` is set to a datetime string.
2. For the case where it does not work, the `locked_until_utc` is set to None.

**Comment by yunhaoling** [comment]
hey @lukipro , thanks for reaching out.

Could you share me with the piece of code that you used for client creation with `DefaultAzureCredential`?

From the error a renew lock operation has been performed on a non-received message, I was wondering if there's any other settings in within your client creation other than `DefaultAzureCredential`?

**Comment by lukipro** [comment]
Hello @yunhaoling,

here is the code:
```
...
    credential = DefaultAzureCredential()
    self.sb_client = ServiceBusClient(config.service_bus_namespace, credential=credential)
    # self.sb_client = ServiceBusClient.from_connection_string(config.service_bus_conn_string)
...


...
while True:
    try:
        with self.sb_client.get_subscription_receiver(topic_name=self.topic_name,
                                                      subscription_name=self.subscription_name,
                                                      idle_timeout=1,
                                                      session_id=self.session_id) as receiver:

            with AutoLockRenewer(max_lock_renewal_duration=30 * 60) as renewer:
                renewer.register(receiver, receiver.session)
                self.handle_session(receiver)
        except Exception as e:
                # logging the error, but trying to continue
                self.logger.warning(f'Exception occurred: {e}.\n Continue listening ... ', exc_info=True)
...
```
But as I mentioned. All works fine for newly created Service Bus namespaces.
Basically the situation is as follows:

```
                       | SB ns created in 2020                      | fresh SB ns
_______________________________________________________________________________________________________________
connection_string      |   session.locked_until_utl is a datetime   |   session.locked_until_utl is a datetime
DefaultAzureCredential |   session.locked_until_utl is None         |   session.locked_until_utl is a datetime
```

**Comment by rakshith91** [comment]
@lukipro Would you be able to share the stack trace? Also, it'd be great if you can share the log by enabling it

**Comment by lukipro** [comment]
Hello @rakshith91 , there is nothing interesting on the client code side. Please check on the server side. The reason is that messages sent from old ServiceBus namespaces do not have the `locked_until_utc` set (but only when using DefaultAzureCredentials).

**Comment by rakshith91** [comment]
@lukipro I have tagged the service team here for further investigation. Meanwhile, can you check if the AAD credentials are right on your end? It is possible that it is some other authentication issue that is not being surfaced correctly.

**Comment by EldertGrootenboer** [comment]
@lukipro Can you open a support ticket for this, and include the sample code, the names of the namespaces, and the timestamps this occurs? Our dev-team will look into this.
