### ISSUE TITLE
Line break default character doesn't display properly

### ISSUE THREAD

**Issue by AWendland-CryptoCompare** [Azure/azure-sdk-for-python#23008]
The default character for line end doesn't display properly. It just line breaks and puts the other ' on the begining of the next line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e2b257-fe6b-67fe-ef24-bd60512b6285
* Version Independent ID: 1eef9045-84ec-4638-6880-7ddd1e281c42
* Content: [azure.storage.blob.DelimitedTextDialect class](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.delimitedtextdialect?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.DelimitedTextDialect.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-storage-blob/azure.storage.blob.DelimitedTextDialect.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by jalauzon-msft** [comment]
Hi @AWendland-CryptoCompare, thanks for reporting this. This seems to be an issue in our process that creates these docs from the code. In the code, this is documented as `\n` as expected. I will investigate how we can get this fixed up.

**Comment by danieljurek** [comment]
This is also displaying improperly in our github.io docs which are directly rendered using sphinx -- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.10.0b3/azure.storage.blob.html#azure.storage.blob.DelimitedTextDialect 

![image](https://user-images.githubusercontent.com/2158838/153925870-184580b3-055f-4246-ba84-f46a1724b886.png)


I think the fix here is to escape the backslash (`\`) in `\n` -- https://docutils.sourceforge.io/docs/user/rst/quickref.html#escaping

On this line: https://github.com/Azure/azure-sdk-for-python/blob/f4d60657f4a2a2b8d7815f9f9303309657eca528/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py#L1139

To fix: 

1. Update the comment
2. Open a PR which will trigger a CI build, wait for the CI build to finish 
3. Check the build artifacts for docs output 
4. Download the zip, extract the docs output to a folder, open the docs and navigate to `azure.storage.blob.html#azure.storage.blob.DelimitedTextDialect` 

If the sphinx doc renders correctly then the output on docs.micrsoft.com should also render correctly. We can check that in the daily docs after the PR merges to `main`.

**Comment by danieljurek** [comment]
Assigning to @jalauzon-msft to fix

**Comment by jalauzon-msft** [comment]
@danieljurek, thanks for the instructions. Unfortunately I don't think it worked quite as expected. I escaped the `\n` making it `\\n` in the code but the docs did not render the backslash, only the `'n'`. It did not render a newline though.
`Record separator, defaults to ‘n’.`

Should I add another backslash? Or another escaped backslash?

**Comment by danieljurek** [comment]
You may need to double escape the backslash (that is 4 backslashes) `\\\\`

**Comment by jalauzon-msft** [comment]
@danieljurek thanks, that worked. I have merged the fix into `main`.
