### ISSUE TITLE
use opencensus-ext-azure==1.1.0 LiveMetrics show version is old or app is offonline

### ISSUE THREAD

**Issue by Liubaituo** [Azure/azure-sdk-for-python#23029]
- **Package Name**:  python Projrct
- **Package Version**:  1.1.0
- **Operating System**: windows
- **Python Version**: 3.8

**Describe the bug**
 "Not available: your app is offline or using an older SDK
Live Metrics Stream shows you key metrics within seconds. Monitor your app through deployments or critical periods.
Once enabled, Live Metrics Stream looks like this. Read more or watch the video." 
   I use sdk ,it's other metrics  is printf ok,but click Live Metrics it show not well. I want to know how to use this sdk to show Live Metrics. I want to konw how to use Live Metrics,and can you give me some example.

**this is my code**
import logging
import uvicorn
from opencensus.ext.azure.log_exporter import AzureEventHandler
from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.trace.samplers import ProbabilitySampler
from opencensus.trace.tracer import Tracer
from opencensus.trace.span import SpanKind
from opencensus.trace.attributes_helper import COMMON_ATTRIBUTES
from fastapi import FastAPI, Request

APPINSIGHTS_INSTRUMENTATIONKEY = 'key'

logEvent = logging.getLogger(__name__)
logEvent.addHandler(AzureEventHandler(
    connection_string=f'InstrumentationKey={APPINSIGHTS_INSTRUMENTATIONKEY}')
)
logEvent.setLevel(logging.INFO)

app = FastAPI()
HTTP_URL = COMMON_ATTRIBUTES['HTTP_URL']
HTTP_STATUS_CODE = COMMON_ATTRIBUTES['HTTP_STATUS_CODE']

@app.middleware("http")
async def middlewareOpencensus(request: Request, call_next):
    tracer = Tracer(exporter=AzureExporter(connection_string=f'InstrumentationKey={APPINSIGHTS_INSTRUMENTATIONKEY}'),
                    sampler=ProbabilitySampler(1.0))
    with tracer.span("main") as span:
        span.span_kind = SpanKind.SERVER
        response = await call_next(request)

        tracer.add_attribute_to_current_span(
            attribute_key=HTTP_STATUS_CODE,
            attribute_value=response.status_code)
        tracer.add_attribute_to_current_span(
            attribute_key=HTTP_URL,
            attribute_value=str(request.url))
    return response
@app.get("/")
async def root():
    logEvent.info("Hello World!")
    return "Hello World!"
if __name__ == '__main__':
    uvicorn.run("requestTest:app", host="127.0.0.1", port=8082)
**expect**
how to use LiveMetrics

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Liubaituo** [comment]
@xiangyan99 
Have you tried? Do you have the same problem?

**Comment by xiangyan99** [comment]
@rakshith91 Could you help to take a look?

**Comment by rakshith91** [comment]
@lzchen can you take a look at this?

**Comment by lzchen** [comment]
@Liubaituo 
Opencensus python sdk does not support sending data to live metrics.
