### ISSUE TITLE
Datasets .Net Core 2.1 runtime dependency is not supported on Linux Debian 11

### ISSUE THREAD

**Issue by MrKriss** [Azure/azure-sdk-for-python#23032]
- **Package Name**:  azureml-dataset-runtime | dotnetcore2
- **Package Version**:  azureml-dataset-runtime  (1.38.0)   |  dotnetcore2  (2.1.23)
- **Operating System**: Linux Debian 11 (Bullseye)
- **Python Version**:  3.9

**Describe the bug**

Azure Datasets can't be saved on Linux OS running Debian 11 (latest stable at time of writing). 

The .Net Core 2.1 runtime dependencies for Azure Datasets are installed with the dontnetcore2 python package. However some additional Linux system dependencies for Debian 11 are not installed correctly using the runtime hook because they don't exist on the server. 

The dontnetcore2 package appears to includes a binary for the .Net 2.1 Runtime, but needs additional files depending on the Linux distribution and version its installed on. The dontnetcore2 package looks these up at runtime to fetch any that are missing using the following url format to get the files.  

```
https://azuremldownloads.azureedge.net/dotnetcore2-dependencies/<dotnetcore version>/<linux distribution>/<version>/deps.tar
```
With the example for Debian 11 being,
```
https://azuremldownloads.azureedge.net/dotnetcore2-dependencies/2.1.23/debian/11/deps.tar
```
However this results in a 404 error as that file does not exist.

The following error message is displayed instead:
```
NotImplementedError: Linux distribution debian 11. does not have automatic support.
```

**To Reproduce**
1. Attempt to save a Azure dataset with `Dataset.Tabular.register_pandas_dataframe` when running on Debian 11

Or 

1. Run the method that fetches dependencies in dotnetcore2 directly with:
```
from dotnetcore2 import runtime

runtime.ensure_dependencies()
```

**Expected behavior**
Dotnetcore2 gets the dependencies it needs and the Dataset is saved successfully to the associated ML Workspace. 

**Screenshots**

Full traceback below:
![2022-02-11_12-06-25](https://user-images.githubusercontent.com/1253209/153588820-4c1a0a84-f841-4776-92f0-7cf9cc26c7f2.png)

**Additional context**

A minimal example is attached with a Dockerfile to reproduce the issue when saving an Azure Dataset:
[test_datasets_on_debian11.zip](https://github.com/Azure/azure-sdk-for-python/files/8048457/test_datasets_on_debian11.zip)

From the following information in [this answer](https://docs.microsoft.com/en-us/answers/questions/361522/azureml-error-on-linux-34unable-to-retrieve-net-de.html), I can see the missing dependencies are:

```
>>> print(runtime._gather_dependencies(runtime._get_bin_folder()))
{'liblttng-ust.so.0', 'libcurl.so.4'}
```
 
My workaround for now is to drop back to Debian 10 as the base OS for all docker images that need to use Azure Datasets.

**Comment by SaurabhSharma-MSFT** [comment]
@bandsina Did you get a chance to look into this.

**Comment by MrKriss** [comment]
Any update on this? Having a secure way to capture and version datasets prior to modeling is a key requirement of ours to use Azure ML Workspaces. And for us, this dataset saving step needs to run on a Linux OS.

**Comment by anliakho2** [comment]
End of year goal is to remove dotnetcore dependency for dataset execution.
When you say dataset saving step, which dataset methods are actually being invoked on this Linux OS?
Thanks!
