### ISSUE TITLE
what's mean of "vm.instance_view.statuses"

### ISSUE THREAD

**Issue by Liuzhj** [Azure/azure-sdk-for-python#2303]
code 

```python
vm = compute_client.virtual_machines.get(GROUP_NAME, 'cdh-1', expand='instanceView')
for stat in vm.instance_view.statuses:
        print "  code: ", stat.code 
        print "  displayStatus: ", stat.display_status 
```

result: 
```
VM instance status
  code:  ProvisioningState/succeeded
  displayStatus:  Provisioning succeeded
  code:  PowerState/running
  displayStatus:  VM running
```

Q:
why double result return? 
what's mean of `ProvisioningState/succeeded` or `PowerState/running`
what's mean of `Provisioning succeeded` or `VM running`

what's difference of them ? 
are there have some doc whih this case ? 
Thank you .

**Comment by lmazuel** [comment]
Statuses store the status of the VM other time:
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get#instanceviewstatus


Name | Type | Description
-- | -- | --
code | string | The status code.
displayStatus | string | The short localizable label for the status.
level | StatusLevelTypes | The level code.
message | string | The detailed status message, including for alerts and error messages.
time | string | The time of the status.
