### ISSUE TITLE
cannot import name 'ContainerClient' from 'azure.storage.blob'

### ISSUE THREAD

**Issue by tommasogallingani** [Azure/azure-sdk-for-python#23031]
- **Package Name**:  azure.storage.blob
- **Package Version**: 12.9.0
- **Operating System**: Win
- **Python Version**:  3.8

**Describe the bug**
>>> from azure.storage.blob import ContainerClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ContainerClient' from 'azure.storage.blob' (unknown location)

**Comment by Santhoshkumard11** [comment]
@tommasogallingani  Are you inside your venv?

**Comment by rshafique** [comment]
Facing the same problem as well. Followed the solution provided in the link below to pip uninstall and pip install azure-storage-blob and it worked. 

[https://stackoverflow.com/questions/69526825/cannot-import-name-blobserviceclient-even-if-azure-blob-storage-latest-versi](url)
However, this solution is not applicable when you deploy a pipeline in azure ml.
