### ISSUE TITLE
Add AARCH64 test support

### ISSUE THREAD

**Issue by odidev** [Azure/azure-sdk-for-python#23048]
Hi Team,

I tried testing **azure-mgmt-kusto** package on X86 and Arm64 architectures but it is generating **0 test cases** and the error: 
```no module named azure.core command```

So, I have used **pytest** as the test command and installed many modules as **azure-container ,azurecontainerregistry azure kusto** but the error is not resolving.

Also, explore in the local containers where the  installation and dependencies are successful but for  **kusto** package the installation is unsuccessful.

@[Laurent Mazuel](https://github.com/lmazuel) Could you please share your feedback regarding this and suggest what can be done to test this over ARM64 server?

Thanks in advance.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you run pip install and share us the output?

We want to check if azure-core package is installed.

Thanks.

**Comment by anilreddypuresoftware** [comment]
[Azure-sdk-for-python .txt.txt](https://github.com/Azure/azure-sdk-for-python/files/8114856/Azure-sdk-for-python.txt.txt)

Thanks.

**Comment by xiangyan99** [comment]
From the log: ModuleNotFoundError: No module named 'devtools_testutils'.

Looks like you are missing some testing tools. 

You can find them in https://github.com/Azure/azure-sdk-for-python/tree/main/tools/azure-devtools & https://github.com/Azure/azure-sdk-for-python/tree/main/tools/azure-sdk-tools

**Comment by odidev** [comment]
@xiangyan99, Thank you for the information. 

As per your instructions, I installed azure-sdk-for-python, azure-devtools and azure-mgmt-kusto and after that I was able to run the tests. 

Got 1 skipped and 1 warning on x86 as well as arm64. Attaching the logs.  

Test output at x86_64 (success):[test_azure-sdk-for-python_x86_with_py38(success).txt.txt](https://github.com/Azure/azure-sdk-for-python/files/8139515/test_azure-sdk-for-python_x86_with_py38.success.txt.txt)
Test output at arm86 (success):[test_azure-sdk-for-python_arm64_with_py38(success).txt.txt](https://github.com/Azure/azure-sdk-for-python/files/8139518/test_azure-sdk-for-python_arm64_with_py38.success.txt.txt)

**Comment by odidev** [comment]
@xiangyan99, Thank you for the information. 

As per your instructions, I installed azure-sdk-for-python, azure-devtools and azure-mgmt-kusto and after that I was able to run the tests. 

Got 1 skipped and 1 warning on x86 as well as arm64. Attaching the logs.  

Test_output at x86_64 (skipped): [test_azure-mgmt-kusto_x86_with_py38(success).txt.txt](https://github.com/Azure/azure-sdk-for-python/files/8139672/test_azure-mgmt-kusto_x86_with_py38.success.txt.txt)
Test_output at arm64 (skipped): [test_azure-mgmt-kusto_arm86_with_py38(success).txt.txt](https://github.com/Azure/azure-sdk-for-python/files/8139671/test_azure-mgmt-kusto_arm86_with_py38.success.txt.txt)

**Comment by xiangyan99** [comment]
@odidev Thanks for your updates. It looks to me you have set up your tests correctly.
