### ISSUE TITLE
Wrong information about `connection_timeout`

### ISSUE THREAD

**Issue by sortega** [Azure/azure-sdk-for-python#23049]
Docs:

> connection_timeout (int): Optionally sets the connect and read timeout value, in seconds.

Actually, there is a separate `read_timeout` parameter and `connection_timeout` has no influence over the read timeout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60c47f1-e4d8-f68e-5f9c-460c4fdc6da8
* Version Independent ID: 172e9f9b-25fb-2121-cb72-d383cc21763a
* Content: [Azure Storage Blobs client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/storage-blob-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/storage-blob-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/storage-blob-readme.md)
* Service: **storagestorage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by jalauzon-msft** [comment]
Hi @sortega, thanks for reporting this. There is some current discussion / work happening around `connection_timeout` and `read_timeout` that may influence this documentation, but we will work to get this corrected.
