### ISSUE TITLE
Errors output on normal operations

### ISSUE THREAD

**Issue by jpoizat** [Azure/azure-sdk-for-python#2304]
All,

I'm having the following issue I'm trying to solve.
I run the following script in python to make a backup of a container :

```
def parse_container_list(container_list):
    """
    Parse a list of container (comma separated) and return a list
    """
    return container_list.split(',')

def copy_container(blob_service, account_name, account_key, copy_from_container):
    """
    copy a container to a backup container with the date in it
    """
    print("Backup of " + copy_from_container + " started")
    today = datetime.now().strftime("%Y-%m-%d")
    copy_to_container = today + '-' + copy_from_container + '-backup'
    metadata = { 'date': today }
    if DEBUG:
        print("check if " + copy_from_container + " exists")
    if not blob_service.exists(copy_to_container):
        if DEBUG:
            print(copy_from_container + " does not exist, creating")
        blob_service.create_container(copy_to_container)

    if DEBUG:
        print("list blobs of " + copy_from_container)

    list = blob_service.list_blobs(copy_from_container)

    for blob in list:
        if DEBUG:
            print("copying " + blob.name + "...")
        blob_url = blob_service.make_blob_url(copy_from_container,blob.name)
        blob_split = blob_url.rsplit('/', 1)
        blob_url = blob_split[0] + '/' + urllib.parse.quote(blob_split[1])
        blob_service.copy_blob(container_name=copy_to_container,
                               blob_name=blob.name,
                               copy_source=blob_url,
                               metadata=metadata)

blob_service = BlockBlobService(account_name=account_name, account_key=account_key)

for container in parse_container_list(copy_from_container):
    copy_container(blob_service, account_name, account_key, container)

```

it works fine but if the container already exist, the function blob_service.exists(copy_to_container) send an output :
Client-Request-ID=94b37614-3336-11e8-b5d0-000d3a253149 Retry policy did not allow for a retry: Server-Timestamp=Thu, 29 Mar 2018 09:50:14 GMT, Server-Request-ID=b66eb1c7-601e-0054-0643-c7992a000000, HTTP status code=404, Exception=The specified container does not exist.ErrorCode: ContainerNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.RequestId:b66eb1c7-601e-0054-0643-c7992a000000Time:2018-03-29T09:50:15.2495329Z</Message></Error>

I tried to remove the test as create_container should work if the container exist, but then I get :

Client-Request-ID=eb641eb9-334e-11e8-b5d0-000d3a253149 Retry policy did not allow for a retry: Server-Timestamp=Thu, 29 Mar 2018 12:44:27 GMT, Server-Request-ID=60538fc9-301e-003b-195b-c793d9000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:60538fc9-301e-003b-195b-c793d9000000Time:2018-03-29T12:44:28.6093912Z</Message></Error>.

the script works but how can I remove those messages...

thanks

**Comment by lmazuel** [comment]
@zezha-msft for a storage question :)

**Comment by zezha-msft** [comment]
Please close this issue as it is already being tracked [here](https://github.com/Azure/azure-storage-python/issues/437). Thanks!
