### ISSUE TITLE
incomplete example

### ISSUE THREAD

**Issue by oskar-digital-power** [Azure/azure-sdk-for-python#23084]
Hi, the example under 'List container groups' seems to be incomplete. The function only shows a print statement, but isn't listing available container groups. Looks like something is missing at the bottom.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e732e187-7ff4-bd4f-9aad-44953af44a86
* Version Independent ID: d4baa2d6-8f2f-ed76-e890-3240065f485a
* Content: [Azure Container Instances libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/containerinstance?view=azure-python)
* Content Source: [docs-ref-services/latest/containerinstance.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/containerinstance.md)
* Service: **container-instances**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Wzb123456789** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Wzb123456789** [comment]
Hi, @oskar-digital-power,  After my investigation, I found the `list_by_resource_group` method to find the container group in the resource group. hope this can unblock you.

fyi: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/_container_groups_operations.py#L121
