### ISSUE TITLE
Add support for azure.identity authentication to azure.data.tables

### ISSUE THREAD

**Issue by James-Beckwith** [Azure/azure-sdk-for-python#23091]
**Is your feature request related to a problem? Please describe.**
I'm trying to have a function update a table whenever it is called. I'd rather not have the account key hard coded, even in the environment. This is fine for blob storage as we can use the DefaultAzureCredential option with InteractiveTokenCredential active. However, this doesn't seem to work for tables. Funnily enough it does actually work for the TableServiceClient such that I can create/delete tables if needs be but I can't add any entities, an error occurs as below:

```python
from azure.data.tables import TableServiceClient, TableEntity
from azure.identity import DefaultAzureCredential

table_endpoint = "https://[storage account].table.core.windows.net"
table_name = "[table to create]"

default_credential = DefaultAzureCredential(exclude_interactive_browser_credential=False,
    exclude_shared_token_cache_credential=True,
    exclude_visual_studio_code_credential=True,
    exclude_managed_identity_credential=True,
    exclude_environment_credential=True,
    exclude_cli_credential=True,
    exclude_powershell_credential=True)

table_service_client = TableServiceClient(table_endpoint, credential=default_credential)
table_client = table_service_client.create_table_if_not_exists(table_name=table_name)

my_entity = TableEntity(RowKey='myRowKey', PartitionKey='myPartitionKey')
entity = table_client.create_entity(entity=my_entity)
```
Running the above code creates the table but raises an error when trying to create an entity:
```
Traceback (most recent call last):
  File "[python file]", line 25, in <module>
    entity = table_client.create_entity(entity=my_entity)
  File "[venv path]\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "[venv path]\lib\site-packages\azure\data\tables\_table_client.py", line 411, in create_entity
    _reraise_error(error)
  File "[venv path]\lib\site-packages\azure\data\tables\_error.py", line 145, in _reraise_error
    raise decoded_error.with_traceback(exc_traceback)
  File "[venv path]\lib\site-packages\azure\data\tables\_table_client.py", line 398, in create_entity
    metadata, content = self._client.table.insert_entity(  # type: ignore
  File "[venv path]\lib\site-packages\azure\data\tables\_generated\operations\_table_operations.py", line 898, in insert_entity
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Forbidden'
```
Inserting the connection string as credentials to the table service client works fine though I don't want to put the connection string in the code or have to have the end user store the value in their environment.

**Describe the solution you'd like**
The above code being able to insert entities into the created table

**Describe alternatives you've considered**
An alternative could be to set up an azure function that has the connection string hard coded then have the user facing function send a message to the function to update the table but this seems to add unnecessary complications.

**Comment by zyzil** [comment]
I'm also trying to use Azure Tables with a service principal/managed identity and am facing the same issue.

**Comment by James-Beckwith** [comment]
Indeed as @zyzil points out, I didn't assign myself the correct role. I was also testing on different systems and found that some did not have the relevant IP addresses whitelisted for the storage account, which also caused access issues.

Note to self; always check role access and whitelisted IPs first.

Thanks the clarification all. I shall close this issue.
