### ISSUE TITLE
remove Table name check

### ISSUE THREAD

**Issue by chshihMSFT** [Azure/azure-sdk-for-python#23106]
- **Package Name**: [azure-data-tables](https://aka.ms/azsdk/python/tablespypi)
- **Package Version**: 12.2.0
- **Operating System**: any
- **Python Version**: 3.10.1

**Describe the bug**
SDK behavior should consider the difference while facing both **Cosmos DB Table API**, and **Storage Account Table Service**, and this issue is reporting for their naming rule difference then leads exception.

When SDK (azure-data-tables) deal with a table named "a-test-table" in Cosmos DB -Table API, it will receive exception below.
>ValueError: Table names must be alphanumeric, cannot begin with a number, and must be between 3-63 characters long.

This is caused by the naming rule checking in here: [/sdk/tables/azure-data-tables/azure/data/tables/_error.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/azure/data/tables/_error.py#L64)
But the checking rule is only feasible for Storage Account - Table services, not Cosmos DB Table API, please reference the naming rule below.

**To Reproduce**
`
CosmosDBConnectionString = "DefaultEndpointsProtocol=https;AccountName=account;AccountKey=key;TableEndpoint=https://account.table.cosmos.azure.com:443/;"  
CosmosDBTableServiceClient = TableServiceClient.from_connection_string(conn_str = CosmosDBConnectionString)  
CosmosDBTableClient = CosmosDBTableServiceClient.get_table_client(table_name = "a-test-table")  
`

**Expected behavior**
Suggestion 1. remove table name checking, fall back to backend service and return error message accordingly.
Suggestion 2. check which the connected service is, then applying different naming rule checking accordingly.

**Screenshots**
![image](https://user-images.githubusercontent.com/45855145/154503044-d4b73483-2b86-45c2-8e10-cdec75d9e6d7.png)
![image](https://user-images.githubusercontent.com/45855145/154506261-317fa6c3-fb1d-4791-9948-0b09ce5a92d6.png)

**Additional context**
[Cosmos DB - Resource name rules](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftdocumentdb)
No specified for container/table level rule in doc.
But [in other doc](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/create-cosmosdb-resources-portal), explain the limitation of container/table name should be:
names must contain from 1 through 255 characters, and they cannot contain /, \\, #, ?, or a trailing space

[Storage Account -Resource name rules](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage)
table / 3-63 / Alphanumerics + Start with letter

note:
In the deprecated SDK [azure-cosmosdb-table 1.0.6](https://github.com/Azure/azure-cosmos-table-python/blob/master/azure-cosmosdb-table/azure/cosmosdb/table/common/_error.py#L127), it’s just simply checked the input shouldn't be empty only.

**Comment by annatisch** [comment]
Hi @chshihMSFT 
This should now be resolved in the latest Tables release :)
