### ISSUE TITLE
SyntaxWarning with comparison

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-sdk-for-python#23124]
- **Package Name**: storage
- **Package Version**: 1.5.0
- **Operating System**: Linux
- **Python Version**: 3.8

**Describe the bug**

```
/home/build/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_chunking.py:403: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if n is 0 or self._buffer.closed:
/home/build/.local/lib/python3.8/site-packages/azure/storage/blob/baseblobservice.py:1009: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/home/build/.local/lib/python3.8/site-packages/azure/storage/blob/baseblobservice.py:2660: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/home/build/.local/lib/python3.8/site-packages/azure/storage/common/_connection.py:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
```

**To Reproduce**
Used a `pyinstaller` to compile an app calling azure cli.

**Expected behavior**
No syntax warning

**Additional context**
Similar issue #9525

**Comment by jalauzon-msft** [comment]
Hi @stan-sz, sorry this was missed for so long.

It appears you are using a very old version of `azure-storage-blob` and so these issues are likely fixed in more recent versions. I would try updating to a more recent version if possible. Especially something at least after 12.0.
