### ISSUE TITLE
Document supportability of tenant_id in all docstring of azure-identity implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#23139]
Some credentials instance will support `tenant_id`, and some won't (like ManagedIdentity). For clarity for users, the docstring needs to explicitly state if the `tenant_id` will be ignored, or is an effective parameter

All credit for @mccoyp to have raised the issue

**Comment by mccoyp** [comment]
We should also explicitly state how we do or don't honor `claims`, and any other arguments specified in the [TokenCredential protocol](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#tokencredential-protocol), for future reference
