### ISSUE TITLE
[Investment] Python Matrix on optional dependency

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#23146]
@lmazuel commented on [Wed Nov 18 2020](https://github.com/Azure/azure-sdk-pr/issues/656)

Python is designed to have a lot of optional dependencies, meaning the behavior of the package can automatically change if a package is detected to be installed on the fly (no compilation needed here).

The big items here are:
- Is our async HTTP lib installed (aiohttp)? What impact on code stability, and perf?
- Is tracing lib installed (opentelemetry)? What impact on code stability, and perf?

Right now, our CI system is testing WITH aiohttp installed (all the time), and WITHOUT tracing installed (all the time). We have no proof that our packages are acting correctly if optional dependencies are installed (or not). For instance, the common scenario in Python is "no async / no tracing", but we actually just test that combination on Python 2 (which is not on purpose, just there is no async on Py2...)

Example of scenario that could happen, and that this work tries to avoid:
- Sdk XYZ with no aiohttp installed (no CI test that), the import could breaks if we messed up the optional part
- EventHub with opentelemetry installed, will automatically start to trace the code, that could break (we should NEVER break if tracing creates an error, but we don't know).

This issue is about to have CI dedicated to the combination stdlib/aiohttp/tracing and have a nice way to test that and mesure perf and impact. This is part engsys work, but I expect some test framework to make it available.

Estimate in weeks (one sprint)

**Comment by scbedd** [comment]
Ok @lmazuel I'm at a place where I am thinking about I want to integrate this work. This _almost_ seems like a matrix generator of a sort. I want to get a bit more specific about how we check these scenarios. I'm already planning a refactor of our tox harness, test invocation, and requirements installation. This falls neatly into the same drawer.

Are `tracing` and `async` the only two "optional" dependencies that we want to exercise? I see a couple ways to approach the definition of these "optional" dependencies.

1. You continue as normal, place them in the `dev_requirements.txt` if your package can possibly rely on them. We will parse the dev_requirements.txt and generate the matrix, but only based on those packages that we understand how to. `aiohttp`, `opentelemetry`. If we want to add further "optional" packages, it will be a PR to the generator.
2. We place these  in their own file `optional_requirements.txt`. The matrix will be the multiplication of the requirements therein.

So given detected optional requirements of those two. We should invoke four basic test runs, 

- `aiohttp`, `opentelemetry`
- `no aiohttp`, `opentelemetry`
- `aiohttp`, `no opentelemetry`
- `no aiohttp`, `no opentelemetry`

Ad nauseum as we add additional `optional` requirements. I am intending the invocation this to be a separate environment. `tox -e optional`. We want the full test suite run here right? This isn't a simple `depends` check.

The basic `both installed` scenario (which is what we currently are defaulted to outside of tox environment `whl_no_aio`) will be covered by the already invoked `sdist` and  `whl` tox environments.

**Comment by lmazuel** [comment]
I'm fine to cite somewhere the dependencies that should be considered for the optional matrix explicitly. IOW, being pragmatic.

A few additional thoughts:
- For ServiceBus and EventHub, it's not aiohttp but uamqp (specially since we're planning to make uamqp optional starting September)
- I'd like eventually `requests` to be optional as well (pure async have no `requests`). Starting August release of azure-core, this should be do-able as today we incorrectly import `requests` too much. This is required by the CLI team, as they are adding support for platform where `requests` is not available.
- There is a test filtering to apply for some. For instance, no aiohttp means sync tests only, and no requests means async tests only.

**Comment by scbedd** [comment]
Leaving a comment here to track refactoring work that is enabling this investment. The goal is to _centralize_ the moving pieces of CI and bring them under a single coherent umbrella. Doing so will enable us to do the more complex scenario generation while actually testing it in a non-hacky way.

## Build, Parse, and Versioning Tooling

- [x] Refactor `build` of packages (including conda packages) into command `sdk_build` accessible from `azure-sdk-tools`
- [x] Move necessary functions to support versioning (both requirement and package version updates) and build into `azure-sdk-tools`. Where a function has been moved out of `sanitize_setup.py` or `common_tasks.py`, call sites on _existing_ checks should be updated in place. So this means the current update takes care of updating versions and requirements + build. That's it.
  - [x] We will leave the current implementation of set_dev_version which simply updates package versions to daily alpha. That will be named sdk_build_version
- [x] Make `versioning` commands available in commands `sdk_version_X`
- [x] All functions should use CWD to establish where the root of the repository is or accept `--repo` as an argument which overrides that default.
- [x] Introduce --buildURL cli command that will _reproduce_ an error or build or scenario from a devops build URL.
- [x] We are _not_ updating logging with this first pr.

[PR Linked Here]()

## Build `scenario` generation with newly centralized code

- [ ] This should belong to `ci_tools.scenarios`
- [ ] Should enable new command `sdk_scenario` that can be used to generate a requirements file for any of our tox enviornments. 
- [ ] Provide a --buildUrl argument to enable download and repro of a scenario generated from a build

Right now we essentially follow the standard of:

- Create tox environment based on preseeded requirements from earlier in the CI pipeline
- `[CI ONLY]` Process dev_requirements.txt to reduce relative dependencies to absolute paths to pre-built wheels (this avoids parallel access errors that WILL randomly happen within the parallel tox runs)
- Check dev_requirements.txt against actual package requirements. If we are running an environment that mandates specific package dependencies be installed (like minimum or latest), remove those requirements from the dev_requirements.txt.
- Install dev_requirements.txt and ci_tools.txt
- If necessary install specific requirements
- Install the package (from artifact directory or built at runtime)

What we _want_ is to have a scenario generator that offers the _options_ that we SHOULD test exposed as CLI arguments to command `sdk_scenario`.

We want to take into account:
- 1 or multiple dev feeds
- A prebuilt artifact directory or not for the package we are generating a scenario for
- Whether or not we are allowing `alpha` versioned dependendencies
- A `scenario`. Be it `latest`, `minimum`, `whl`, `sdist`

The method:

1. Examine the package. Are we grabbing it from a prebuilt directory? Are we in `dev_mode` (alpha versioned and requirements allow alpha) 
   - Add the resolved package reference to a `scenario.txt` 
2. Examine our dev_requirements. Do we need to do any pre-processing like we currently do in `tox_harness.py`? 
   - Pass set of requirements to the next phase.
3. Process package requirements.
   - Are we in dev mode? That affects our search
   - Select which versions of the requirements should be installed
   - Any requirements resolved in this phase supplant those in the dictionary passed from phase 2. 
   - Pass combination requirements to next phase.
4. Combine stripped down tox_environment_requirements.txt file to combination, with previous values holding weight over values from tox_environment_requirements.txt
5. Write entire combination of requirements to `scenario_name.txt`
6. The tox environment should install only azure_sdk_tools to start with, invoke `scenario_generator`, then install _that_ file. 
7. Check for the presence of a `ci_constraints.txt` which pins certain versions to help with test failures in CI.
8. Invoke tests as normal

## Logging updates

COMING SOON

## Test Invocation Updates

COMING SOON
