### ISSUE TITLE
Unable to create Server Firewall Rule with 0.0.0.0 as starting and ending IP 

### ISSUE THREAD

**Issue by sadaithal23** [Azure/azure-sdk-for-python#2315]
Through Azure UI, it is possible to create a Firewall Rule for a server, with starting and ending IP as 0.0.0.0 but through python sdk it doesn't return any error but it doesn't show up in the UI.

Code : 
`sql_client = SqlManagementClient(credentials,subscription_id)
 response2 = sql_client.firewall_rules.create_or_update(GROUP_NAME, 'sada-server', 'sada-firewall', "0.0.0.0", "0.0.0.0")`

**Comment by yoshiomura** [comment]
You can check the result on  [Azure Resource Manager ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview). 
The  rule which you want looks already set as default. 
I tried your code and found the default rule name changed. 

```python
from azure.mgmt.sql.sql_management_client import SqlManagementClient
from azure.common.credentials import ServicePrincipalCredentials

CLIENT_ID = ""
SECRET = ""
TENANT_ID = ""
GROUP_NAME = ""

credentials = ServicePrincipalCredentials(
    client_id=CLIENT_ID,
    secret=SECRET,
    tenant=TENANT_ID
)

subscription_id = ""

sql_client = SqlManagementClient(credentials,subscription_id)
res = sql_client.firewall_rules.create_or_update(resource_group_name=GROUP_NAME,server_name="testdb", firewall_rule_name='myrule',start_ip_address="0.0.0.0",end_ip_address="0.0.0.0")
```
```
{
  "value": [
    {
      "id": "myresourceId",
      "name": "myrule",
      "type": "Microsoft.Sql/servers/firewallRules",
      "location": "Japan East",
      "kind": "v12.0",
      "properties": {
        "startIpAddress": "0.0.0.0",
        "endIpAddress": "0.0.0.0"
      }
    }
  ]
}
```

**Comment by lmazuel** [comment]
@jaredmoo you want to add something?
