### ISSUE TITLE
LogicMangementClient Workflows Update method lacks logic to populate the request body

### ISSUE THREAD

**Issue by dmartin-r7** [Azure/azure-sdk-for-python#23160]
- **Package**: azure-mgmt-logic
- **Version**: latest 
- **OS**: macOS Catalina
- **Python Version**: 3.8

**Describe the bug**
The WorkflowOperations class in the LogicManagementClient has an update method that does not work. Inside this method the body for the request never gets set, and there is no way to pass in tags or properties to this method to get it to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to use the `LogicManagementClient.workflows.update()` method
2. ```
    update(
        self,
        resource_group_name,  # type: str
        workflow_name,  # type: str
        **kwargs  # type: Any
    ):```
Here the input parameters are defined, there are no parameters for the update and kwargs is not utilised for populating the request body.

3. ``` 
       # Construct URL
        url = self.update.metadata['url']  # type: ignore
        path_format_arguments = {
            'subscriptionId': self._serialize.url("self._config.subscription_id", self._config.subscription_id, 'str'),
            'resourceGroupName': self._serialize.url("resource_group_name", resource_group_name, 'str'),
            'workflowName': self._serialize.url("workflow_name", workflow_name, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        request = self._client.patch(url, query_parameters, header_parameters)
        pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response```

In the above code from `_workflows_operations.py` nowhere is the body for the request set, so this will always fail.

**Expected behaviour**
Update method should accept request parameters as either kwargs or a positional parameter. The body for the request needs to be instantiated somewhere within this method using these or it will always be None.

**Additional Context**
https://docs.microsoft.com/en-us/python/api/azure-mgmt-logic/azure.mgmt.logic.operations.workflowsoperations?view=azure-python#azure-mgmt-logic-operations-workflowsoperations-update

Nothing is defined here either on how to pass in the parameters to update, unlike other packages which usually have a `parameters` or `properties` input parameter.

**Comment by annatisch** [comment]
Thanks for finding and reporting this issue @dmartin-r7!
We really appreciate your time :)

@msyyc would you be able to take a look and confirm whether this is a bug in the swagger spec that needs to be addressed?

**Comment by Wzb123456789** [comment]
Hi, @dmartin-r7  Thanks for your feedback

SDK is generated by swagger;

In the preview of the 2018-07-01 version, the parameters are normally defined;
fyi: https://github.com/Azure/azure-rest-api-specs/blob/bb4175d29020cfff55f1d9087c2a5a89765067dc/specification/logic/resource-manager/Microsoft.Logic/preview/2018-07-01-preview/logic.json#L242-L283

Parameters are missing in the stable version of 2019-05-01
fyi: https://github.com/Azure/azure-rest-api-specs/blob/bb4175d29020cfff55f1d9087c2a5a89765067dc/specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01/logic.json#L266-L297

It is recommended to submit your new issue to https://github.com/Azure/azure-rest-api-specs/issues
