### ISSUE TITLE
Non recursive call required for update / modify method

### ISSUE THREAD

**Issue by hurtn** [Azure/azure-sdk-for-python#23162]
**Is your feature request related to a problem? Please describe.**
Based on https://github.com/Azure/azure-sdk-for-python/blob/6d9bd4a62945e18b081d62ff2e74ca3627a75211/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py we request a non recursive async call to update / modify ACLs.

**Describe the solution you'd like**
There currently is a function update_access_control_recursive but to avoid having to rewrite async code or use HTTP calls please add a non recursive call update_access_control. This is required because our solution currently uses the async update_access_control_recursive function but certain situations do not require recursive operations

**Describe alternatives you've considered**
Will use HTTP for these scenarios

**Additional context**
Require both function with and without the continuation token

**Comment by jalauzon-msft** [comment]
Chatting with Nick offline internally about this.
