### ISSUE TITLE
query_items_change_feed does not honor is_start_from_beginning

### ISSUE THREAD

**Issue by petergaultney** [Azure/azure-sdk-for-python#23161]
- **Package Name**:  azure.cosmos
- **Package Version**: 4.2.0
- **Operating System**: MacOS Monterey
- **Python Version**: 3.7.12

**Describe the bug**

I always get the full history for the container rather than only new history, as the documentation suggests I should expect. This happens both when using the default value (False) for `is_start_from_beginning` and when explicitly passing False.

**To Reproduce**
1. Create a Cosmos DB container (SQL/Core mode). partition key and item id are both `id` for simplicity.
2. Add some items. I added 1000 test items.
3. Wait long enough that it cannot be plausibly claimed that the data is being inserted concurrently with the change feed query. I waited a whole weekend, but in theory just a few seconds should be plenty.
3. Using the Python SDK, connect to the DB and container.
4. Run the following snippets, both of which (according to docs) should return no items, since nothing is currently being modified:

```
for item in cont.query_items_change_feed():
     print(item)
```

```
for item in cont.query_items_change_feed(is_start_from_beginning=False):
     print(item)
```

Instead, both print all 1000 items that were created. 

**Expected behavior**

No 'old' changes should be returned. 

**Screenshots**

<img width="2392" alt="Screen Shot 2022-02-21 at 11 37 19 AM" src="https://user-images.githubusercontent.com/549720/155003980-cca17abd-8165-45b3-b628-e4853af89efc.png">

**Comment by simorenoh** [comment]
hi @petergaultney, I'll be taking a look at this and updating this issue as I progress, thank you for using our sdk!
