### ISSUE TITLE
[Sample Update]Authentication samples for Azure Key Vault using the Azure Python SDK

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-python#23186]
https://github.com/Azure-Samples/key-vault-python-authentication
Update SDK Version to T2

**Comment by mccoyp** [comment]
Resolved by https://github.com/Azure-Samples/key-vault-python-authentication/pull/12 -- current guidance is to point to samples and migration guides in this repo, and to archive deprecated sample repos.
