### ISSUE TITLE
[ACR] patch misspelled property to work with stable version

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#23199]
@YalinLi0312 sorry I didn't realize that ACR was already GA/stable. In this case, we should fix `RepositoryProperties`'s property `last_updated_on` to work with both the correctly spelled word and _still_ work for the misspelled one as to not introduce a breaking change in a stable package. 

Some pseudo-code of how we can do this dynamically and let users specify either spelling:

```
class RespositoryProperties:

  ...

  def __getattr__(self, name):
     if name == "last_udpated_on":
        warning.deprecation("The property name with a typo called 'last_udpated_on' has been deprecated")
        return self.last_updated_on
     return super().__getattr__(self, name)
```

This way we shouldn't need to document the breaking the change and it won't break in user's code either way.
 
related PR: https://github.com/Azure/azure-sdk-for-python/pull/23181

**Comment by annatisch** [comment]
Thanks @kristapratico!

**Comment by lmazuel** [comment]
If the property is writable, we must do a `__setattr__` as well
