### ISSUE TITLE
Servicebus logs exception also when only retrying

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#23218]
- **Package Name**: servicebus
- **Package Version**: 7.3.3
- **Operating System**: linux
- **Python Version**: 3.9

**Describe the bug**
Not really a bug but I have noticed the following: we got an exception like

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/aio/_base_handler_async.py", line 246, in _do_retryable_operation
    return await operation(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/aio/_servicebus_receiver_async.py", line 318, in _open
    while not await self._handler.client_ready_async():
  File "/usr/local/lib/python3.9/site-packages/uamqp/async_ops/client_async.py", line 356, in client_ready_async
    if not await self.auth_complete_async():
  File "/usr/local/lib/python3.9/site-packages/uamqp/async_ops/client_async.py", line 342, in auth_complete_async
    raise TimeoutException("Authorization timeout.")
TimeoutError: Authorization timeout.
```

digging into the code, in my understanding this exception is logged here

https://github.com/Azure/azure-sdk-for-python/blob/f68dd959a659579d299177195ea846b01aa16dc2/sdk/servicebus/azure-servicebus/azure/servicebus/exceptions.py#L174

The client was able to retry and all went well after that. However, logging an exception has trigger log-based alerts on our code and because there is no mention on any retry, it was unclear what was going on.

**Expected behavior**
I would expect just a warning in the log.

**Comment by annatisch** [comment]
Thanks @andrea-cassioli-maersk for reporting this!
We will dig a bit deeper and see if we can revisit the error retry logging level :)

**Comment by thyllmuller** [comment]
Has there been any movement on this ticket? I am running into the same issue on a project I am working on, where I simply want to see retry logs stemming from the send_message functionality?

**Comment by swathipil** [comment]
Hi @andrea-cassioli-maersk - Sorry about the late response here! We have been working on and just released a pure Python AMQP stack-based `azure-servicebus`. We no longer take a dependency on `uamqp`, so you shouldn't be seeing that uamqp TimeoutError in the stack trace/your logs. Would you be able to try installing the latest version (or any version > 7.10.0), and see if this problem still persists? Thank you!

cc/ @thyllmuller
