### ISSUE TITLE
Cosmos DB samples issue

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#23219]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/index_management_async.py#L373):
![image](https://user-images.githubusercontent.com/57166602/155697660-ce326aed-99f2-409f-a985-ce65d3f36a38.png)

Reason:
TypeError: object AsyncItemPaged can't be used in 'await' expression.

Suggestion:
Delete the `await`.

@jameszliao-msft , @lmazuel , @kyle-patterson and @mayurid for notification.

**Comment by simorenoh** [comment]
Closed with PR: https://github.com/Azure/azure-sdk-for-python/pull/23221
