### ISSUE TITLE
[QUERY] Check if AccessPolicy is accepted as an empty parameter from BlobContainer GetAccessPolicy

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-python#23222]
In .NET we faced a bug due to unclear [documentation ](https://docs.microsoft.com/en-us/rest/api/storageservices/set-container-acl#request-body) where the if the CX specified an empty AccessPolicy on the BlobContainerClient and then went to grab the AccessPolicy information, they would get a Null Exception because we except the service to always give us back an access policy, if an id is specified.

To be more specific:
When performing a BlobContainerClient.GetAccessPolicy and the body of the request returns with this value (or access policy)
'<SignedIdentifier><Id>MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=</Id><AccessPolicy><Start/><Expiry/></AccessPolicy></SignedIdentifier>'

However it also return like
<SignedIdentifier><Id>MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=</Id></SignedIdentifier>

This scenario can be reproduced if you set the signed identified with an id but not an access policy. I wrote a test in .NET to represent this.
https://github.com/Azure/azure-sdk-for-net/pull/27203/files#diff-cfbbd86d890e76d951dd6142c352ee932045fb0ce70ceb31c1d069f404c692c2R1140

I've also put in a fix in .NET for this issue as well.

https://github.com/Azure/azure-sdk-for-net/pull/27203/files

Please close this issue once we confirm that in Python that we support this scenario. If it does not, please relabel this issue as a bug and resolve it accordingly.

**Comment by jalauzon-msft** [comment]
It does not look like this is an issue in Python. I created a test that set a `SignedIndetifier` with an `id` and the `AccessPolicy` set to `None` and then fetched it with `get_container_access_policy()` and it came back as expected with the same id and `None`.

I also verified the generated `SignedIndetifier` class only requires an `id` and we do not expose a non-generated model class for signed identifiers so we should be all good.
