### ISSUE TITLE
Anomaly Detector Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#23220]
1.
Section [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/anomalydetector/azure-ai-anomalydetector/samples/README.md):
![image](https://user-images.githubusercontent.com/57166602/155699408-7b1fd8a2-3074-45eb-961d-d32c782c327f.png)

Suggestion:
Add link: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_multivariate_detect.py

@jameszliao-msft , @lmazuel , @meeraharidasa , @mayurid , @conhua  for notification.

**Comment by Santhoshkumard11** [comment]
I can fix this!
