### ISSUE TITLE
query_filter is not explained

### ISSUE THREAD

**Issue by Danferno** [Azure/azure-sdk-for-python#23235]
The method query_entities should link to documentation on how to construct a query_filter. At the moment it simply says `Specify a filter to return certain entities` which says very little in my opinion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f0fbc3-700d-812f-1cc7-dbac5c748a9b
* Version Independent ID: a53bc37d-1e8d-dde1-3b7f-da7345ec6b60
* Content: [azure.data.tables.TableClient class](https://docs.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables.tableclient?view=azure-python#azure-data-tables-tableclient-query-entities)
* Content Source: [docs-ref-autogen/azure-data-tables/azure.data.tables.TableClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-data-tables/azure.data.tables.TableClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by annatisch** [comment]
Thanks for the feedback @Danferno!
We have more details on this in the Samples directory here:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/tables/azure-data-tables/samples#writing-filters

However I agree that if you didn't know to look there it would be hard to find. I will look at linking to this information from the SDK reference docs!

**Comment by annatisch** [comment]
I've opened a PR (#23240) to get these docs updated, which we'll hopefully get into our March release :)

**Comment by Danferno** [comment]
Thanks! If I could make one more request: on the [samples page](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/tables/azure-data-tables/samples#writing-filters), could you perhaps add a bit more explanation on the use of quotes? In particular that in a string comparison, the string to compare to should be enclosed in complementary quotes if it is provided literally. It suppose it makes sense when you think about it, but it's tripped me up a few times already (because the query filter itself is already enclosed in quotes).

Example: the A and B here are enclosed in single quotes
"LastName ge **'A'** and LastName lt **'B'**"

**Comment by annatisch** [comment]
Merged the updates. This should be released next week :)
Thanks again!
