### ISSUE TITLE
Old command for role assignment in documentation?

### ISSUE THREAD

**Issue by lilumdaru** [Azure/azure-sdk-for-python#23234]
Hi,
I'm trying to authentificate as described here: https://docs.microsoft.com/en-us/python/api/overview/azure/digitaltwins-core-readme?view=azure-python#authentication-permission

When executing

`az dt rbac assign-role --assignee '<user-email | application-id>' --role owner -n '<your-digital-twins-instance>'
`
I get:

`'rbac' is misspelled or not recognized by the system.
`
did the cli command change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9710fc-cf21-6a29-20e5-d7e33781d285
* Version Independent ID: cd40e875-60b4-40fd-b9ac-6f53bf47fc79
* Content: [Azure Azure Digital Twins Core client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/digitaltwins-core-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/digitaltwins-core-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/digitaltwins-core-readme.md)
* Service: **digitaltwins**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by yunhaoling** [comment]
thanks @lilumdaru for reaching out, we'll investigate it ASAP.
