### ISSUE TITLE
Less Information on How to use Config

### ISSUE THREAD

**Issue by Srkshaikh5** [Azure/azure-sdk-for-python#23233]
[Enter feedback here]
I want to use ProfanityOption in speech to text but there is no code example is given only the parameter name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec25627d-5ad1-de7c-9682-fd57f5ce0243
* Version Independent ID: 46120212-86f0-b744-d329-ce3c0849cbd3
* Content: [azure.cognitiveservices.speech.ProfanityOption enum](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.profanityoption?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cognitiveservices-speech/azure.cognitiveservices.speech.ProfanityOption.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-cognitiveservices-speech/azure.cognitiveservices.speech.ProfanityOption.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by yunhaoling** [comment]
thanks @Srkshaikh5 for your feedback and yes, we should definitely improve the doc experience. The team working on the cognitiveservice.speech SDK should be able to help with it.

**Comment by Spiro-001** [comment]
@Srkshaikh5 
Similar to speechConfig in the sample code they give in their documentation, you want to first create a variable that will be used as the setting for Profanity. I created a variable and named it setProfanity.

From here you want bring up the ProfanityOption class, which is also included in the documentation. ProfanityOption has 3 functions within this class.

ProfanityOption::Masked | [0]
ProfanityOption::Raw | [2]
ProfanityOption::Removed | [1]

You now want to set your newly created variable as one of these options.
Example Code :
auto setProfanity = ProfanityOption::Raw;

Now you're almost done. What's left is to point the new setting to the configuration. How you want to do this is very similar to when you set your speech recognition language.
Example Code :
speechConfig -> SetProfanity(setProfanity);

You can think of this as changing settings in a game or a application. You go into settings and from there you have sub-menus. SetProfanity is one of these sub-menus. Within the parentheses is the new variable you created.

So all together it may look something like this :

auto setProfanity = ProfanityOption::Raw;
speechConfig -> SetProfanity(setProfanity);

I had difficulty figuring this out too. I just figured it out and wanted to share as I tried looking for the answer online and saw this thread.

Hope this helped!
Spiro-001
