### ISSUE TITLE
AppConfigurationClient can not retrieve individual settings

### ISSUE THREAD

**Issue by gfranxman** [Azure/azure-sdk-for-python#23236]
- **Package Name**: azure-appconfiguration 
- **Package Version**: 1.3.0
- **Operating System**: Linux (Databricks)
- **Python Version**:  3.8

**Describe the bug**
AppConfigurationClient can not retrieve individual settings, but can retrieve them in bulk.

**To Reproduce**
1. `from azure.appconfiguration import AzureAppConfigurationClient`
2. `app_config_client = AzureAppConfigurationClient.from_connection_string(appconfig_conn_str)` 
3. `all_settings = list(s.key for s in app_config_client.list_configuration_settings())`     # this will return the names of all of the settings
4. `len(all_settings)`  # in my case this is currently 225. 
5. `app_config_client.get_configuration_setting(key=all_settings[0])` # this is where it raises ResourceNotFound for any key from the list.

**Expected behavior**
I would expect it to return the value or ConfigSetting object for the requested key.

**Screenshots**
<img width="1457" alt="Screen Shot 2022-02-28 at 1 06 59 PM" src="https://user-images.githubusercontent.com/148662/156035154-e57661b4-6d35-4964-a329-79f4e6262851.png">

**Additional context**
This is occurring within the context of Azure Databricks notebooks.

**Comment by yunhaoling** [comment]
thanks @gfranxman for reaching out, we'll investigate into it ASAP.

**Comment by xiangyan99** [comment]
@gfranxman Thanks for reaching out. Did you have a chance to check if those configuration settings have labels?

When you use get_configuration_setting(key="sth"), you are looking for the setting with key = "sth" and no label. If the setting has 
key = "sth" and label = "some label", you cannot get a successful match.

**Comment by gfranxman** [comment]
Wow.    I can confirm: No settings can be retrieved by key, unless the label is also passed.

Why?  Is that not a bug?

**Comment by xiangyan99** [comment]
This is by design.

When we query configuration settings, we try to match both key and label.

If you don't specify a label, we don't regard this as "any label", instead, we regard this as "no label" and try to find the one without a label.
