### ISSUE TITLE
how to specify `scopes` and retrieve TokenCredential 

### ISSUE THREAD

**Issue by jwxd** [Azure/azure-sdk-for-python#23248]
Hi team,
I'm trying to migrate our service from using deprecated [msrestazure](https://github.com/Azure/msrestazure-for-python/blob/698eb06bcbf9fda4c7ae04d929f7b5b955fcbfed/msrestazure/azure_active_directory.py#L557) to Azure-identity.
I'm trying to figure out how to use the `scopes` parameter in the Credential.
For example, I'm trying to use azure-identity for getting secrets from azure keyvault:

> credentials = DefaultAzureCredential(scopes='https://vault.azure.net')
> secret_client = SecretClient(vault_url=vault_base_url, credential=credential)

but it didn't work
It looks like the scopes parameter is only used by the get_token() method but it returns  AccessToken class instead, which is not what I want.

In the previous library it provides a parameter `resource` to specify what resource we are pointing to.
https://github.com/Azure/msrestazure-for-python/blob/698eb06bcbf9fda4c7ae04d929f7b5b955fcbfed/msrestazure/azure_active_directory.py#L567
Do you know how I can get a TokenCredential class and specify the scopes?

**Comment by xiangyan99** [comment]
Did you have a chance to take a look at https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md?

**Comment by jwxd** [comment]
Yes, But the migration guide and documentation did not cover how the usage of `resource` parameter changes to `scopes` and how it's supposed to be used in azure-identity to specify certain permission of the credential that we are requesting.

For example, we do use (resource)[https://github.com/Azure/msrestazure-for-python/blob/698eb06bcbf9fda4c7ae04d929f7b5b955fcbfed/msrestazure/azure_active_directory.py#L567] parameter in our code. 

> credential = ServicePrincipalCredentials(client_id, client_secret, tenant=tenant_id, resource='https://vault.azure.net')

we do use different resource url in different environment. Azure Identity doesn't provide this parameter and I believe it's replaced by scopes which is passed as parameter to the get_token() method in Credential class.

Can you guide me through how we can achieved the same using azure-identity?

**Comment by xiangyan99** [comment]
AAD v2 creates default scopes. https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#the-default-scope

if in track 1, resource='https://vault.azure.net/', you can get the according scope 'resource + "/.default"'.

**Comment by jwxd** [comment]
So you mean it's no longer necessary to specify the scope when using Azure-identity because it uses AAD v2 and it creates the default scopes for us?
What about use case in Soveriegn cloud and gov cloud? Is it also the same behavior?
Because in our use case we uses different resource for Sovereign cloud and gov cloud. 
We want to make sure this works without having to specify an scope.

**Comment by xiangyan99** [comment]
In most cases, yes. If you need to explicitly specify one, you can convert the resource string into scope by appending "/.default".

**Comment by jwxd** [comment]
That's exactly where I'm struggling at. How do I explicitly the scopes when using [ManagedIdentityCredential class](https://github.com/Azure/azure-sdk-for-python/blob/e5fd9731260f1e234989e28769b2dd3371b193bd/sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py#L25)
Let's say I want to explicitly specify "https://vault.azure.net/.default". Where do I pass this var to?
The parameter [scopes](https://github.com/Azure/azure-sdk-for-python/blob/e5fd9731260f1e234989e28769b2dd3371b193bd/sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py#L111) is only available in get_token() method and it's not returning a credential class.

**Comment by xiangyan99** [comment]
Did you try specifying the scope when you create the client? It will be used to create the BearTokenPolicy. https://docs.microsoft.com/en-us/python/api/azure-core/azure.core.pipeline.policies.bearertokencredentialpolicy?view=azure-python

**Comment by jwxd** [comment]
Azure [SecretClient](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-secrets/latest/azure.keyvault.secrets.html#azure.keyvault.secrets.SecretClient) does not provide option to specify a scope 
Just to give you more context on what I'm working on. 
[PR link](https://github.com/Hexadite/acs-keyvault-agent/pull/47)

**Comment by xiangyan99** [comment]
@mccoyp Looks like you do not honor scope when creating your policy.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py#L69

Could you take a look?

**Comment by xiangyan99** [comment]
@jwxd if you have a chance, could you try use default scope (not specify scope explicitly) and see if it works?

Thanks.

**Comment by jwxd** [comment]
Sure, I'm working on an internal build to test with my new fix without explicitly specifying scopes.
I will keep you posted.

**Comment by mccoyp** [comment]
@jwxd you're right that `scopes` can't be manually provided to a KV client. The challenge auth policy will automatically fetch the scope returned by the service's challenge response; [here's](https://github.com/Azure/azure-sdk-for-python/blob/0a0cc97f178a7476ec79f29c090b8c93ad5d4955/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L75) where that happens. The `resource` or `scope` of the request is pulled out of the challenge response we get back from Key Vault -- the parameters of the challenge are parsed out [in this logic block](https://github.com/Azure/azure-sdk-for-python/blob/eddb958ee575e505c99c587ff044936879ae5b94/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge.py#L24).

As an example, [here's](https://github.com/Azure/azure-sdk-for-python/blob/a7e3bf4ece801e49f3cfcf7e098881326a731158/sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_secret_crud_operations_7_2.yaml#L40) a recorded challenge response that gives us a resource of "https://vault.azure.net". Using this challenge response, we'd make a token request with "https://vault.azure.net/.default" as our `scopes`.

My assumption is that the service should return the appropriate scopes for you to access the vault, but that could be mistaken in a niche scenario that I'm not aware of. If letting the challenge auth policy fetch the scopes automatically doesn't work for you, we can look into allowing you to provide `scopes` to the client manually (and we should maybe look into this regardless).

**Comment by jwxd** [comment]
Just a quick update, we tried to use the default scope and it works in both Public and Special clouds.
