### ISSUE TITLE
DefaultAzureCredential doesn't authenticate even CLI login successfully

### ISSUE THREAD

**Issue by jerrychenhf** [Azure/azure-sdk-for-python#23245]
- **Package Name**: 
azure-identity
- **Package Version**: 
1.7.0
- **Operating System**:
Ubuntu 18.04 LTS
- **Python Version**: 
Python 3.7

**Describe the bug**
After used az login successfully, the program uses DefaultAzureCredential to authenticate the token but throw the following exception:

azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	ManagedIdentityCredential: Unexpected content type "text/html"

**To Reproduce**
1.  Use "az login" to login.
2.  Execute the following program through python:
  from azure.identity import DefaultAzureCredential
  from azure.mgmt.compute import ComputeManagementClient
  
  credential = DefaultAzureCredential()
  
  subscription_id = "replace with your subscription id"
  compute_client = ComputeManagementClient(credential,subscription_id)
                          
  vms = compute_client.virtual_machines.list("replace with your resource group name")
              
  nodes = [vm.name for vm in vms]
  print(nodes)

**Expected behavior**
The program should succeed and print the list of instance names.

**Additional context**
It seemed that ManagedIdentityCredential throws exception which stopped the trying of CLI credential. But the machine is clean and not configured with any other azure credentials. 
The exception output attached. ( I printed out the exception details from ManagedIdentityCredential) :

[test.txt](https://github.com/Azure/azure-sdk-for-python/files/8158048/test.txt)

**Comment by jerrychenhf** [comment]
Any update on this? it showed to be very basic problem.

**Comment by xiangyan99** [comment]
It looks to me you wanted to use AzureCliCredential but it failed in ManagedIdentityCredential.

Have you tried to use AzureCliCredential directly and did it work?

credential = AzureCliCredential ()

Thanks.

**Comment by sijucm** [comment]
That's not the point. When using AzureCliCredential it works but it does not work when using DefaultAzureCredential, the way it is supposed to and as per documentation. Is this going to be fixed or kept this way to waste people's time debugging Microsoft "features"

**Comment by marlinspike** [comment]
Confirmed. **AzureCLICredential()** works, but not **DefaultAzureCredential()**

This seems to be a regression, since it's worked in the past. I find the suggestion to use AzureCLICredential() as a workaround daft, since the purpose of DefaultAzureCredential() is to write Auth code once and push it to any environment. I'm never logging in using CLI in a production container.

**Comment by xiangyan99** [comment]
> > It looks to me you wanted to use AzureCliCredential but it failed in ManagedIdentityCredential.
> > Have you tried to use AzureCliCredential directly and did it work?
> > credential = AzureCliCredential ()
> > Thanks.
> 
> How is this a workaround? DefaultAzureCredential() is not working. That's the issue.

Thanks for your feedback. 

Please feel free to open a new issue and share your environment and error log.

**Comment by marlinspike** [comment]
> > > It looks to me you wanted to use AzureCliCredential but it failed in ManagedIdentityCredential.
> > > Have you tried to use AzureCliCredential directly and did it work?
> > > credential = AzureCliCredential ()
> > > Thanks.
> > 
> > 
> > How is this a workaround? DefaultAzureCredential() is not working. That's the issue.
> 
> Thanks for your feedback.
> 
> Please feel free to open a new issue and share your environment and error log.

https://github.com/Azure/azure-sdk-for-python/issues/26950
