### ISSUE TITLE
[storage-fileshare] duplicate type signatures in async FileClient method

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#23264]
The exact issue opened [here](https://github.com/Azure/azure-sdk-for-python/issues/21223) also exists for the async FileClient. This was fixed for the sync client in this [PR](https://github.com/Azure/azure-sdk-for-python/pull/19739/files), but still needs to be fixed for the equivalent async method:

https://github.com/Azure/azure-sdk-for-python/blob/eeb2f3b8c7c115337f9d71166aca91db732c931e/sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py#L562-L569

**Comment by SaurabhSharma-MSFT** [comment]
@kristapratico Redirecting this to services team to look into the fix.

**Comment by jalauzon-msft** [comment]
Thanks @kristapratico Krista, thanks for reporting this. Looks like it was previously missed. I will create a PR to address this soon.
