### ISSUE TITLE
Cleanup Python credscan baseline file suppressions

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-python#23260]
- [ ] Remove use of a baseline file to suppress old CredScan warnings. The python baseline file is located [here.](https://github.com/Azure/azure-sdk-for-python/blob/main/eng/python.gdnbaselines)

**Comment by scbedd** [comment]
@mccoyp already had this resolved, but I am also adding an addition on credscan in #31193, so taking the opportunity to close this issue as well.
