### ISSUE TITLE
Model (unmanaged) endpoints: how to provide secrets?

### ISSUE THREAD

**Issue by janluke** [Azure/azure-sdk-for-python#23277]
**Is your feature request related to a problem? Please describe.**
We deploy models to AKS and need a way to pass secrets into the service. Currently we pass them as environment variables (using the `Environment` class). Of course, the secrets are not hard-coded.

In [this StackOverflow question](https://stackoverflow.com/questions/69916579/how-to-provide-secrets-to-an-azure-machine-learning-inference-server) the answerer writes:

> Currently the following feature is in the roadmap to Provide deployed web service some kind of easy access path to the associated Key Vault, similar to how an experimental run of a model can use Run.get_context().get_secret().

1. When is this feature expected to be released? 
2. Is what we are doing a security issue? AFAICS, the only place where these secrets are visible is in k8s deployments YAML files and you need access to the k8s namespace to read those.
3. If what we're doing is a security issue, can we do better?

**Comment by yunhaoling** [comment]
hey @janluke , thanks for reaching out.

May I ask which SDK are you using? I saw you opened the issue https://github.com/Azure/azure-sdk-for-python/issues/23278.
Is this also a azureml-core issue?

**Comment by janluke** [comment]
Yes, the issue is about azureml-core and model deployment to AKS.

**Comment by yunhaoling** [comment]
thanks for the sharing me with the package information, I've tagged the issue, the service team should be able to help!

**Comment by luigiw** [comment]
@janluke v1 SDK is in maintenance only mode in favor of the v2 SDK being GA. Please file an issue for v2 SDK if your requests stand for v2. 
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-migrate-from-v1
