### ISSUE TITLE
Model endpoints (unmanaged): environment variables are not updated after updating the service

### ISSUE THREAD

**Issue by janluke** [Azure/azure-sdk-for-python#23278]
- **Package Name**: azureml-core
- **Package Version**: 1.38.0
- **Operating System**: Windows 10
- **Python Version**: 3.8

**Describe the bug**
I use `Environment.environment_variables` to provide values to our model services (deployed to AKS). The `Environment` is provided as part of the `InferenceConfig`. Sometimes I just want to change the value of one environment variable and updating the service. But after the service is updated, the environment is still the old one.

**To Reproduce**
Sorry, I don't have time now to provide a runnable example. I'll try to add it later.

1. Deploy a model to AKS setting `env.environment_variables["MY_VAR"] = "0"` and passing this `env` to `InferenceConfig`
2. Run `service.update()` by passing the same env but with `env.environment_variables["MY_VAR"] = "1".
3. Check the value of `MY_VAR` and see it's still "0".

In step 2, the environment can have the same or a different name. It can be registered or not. The result is the same. (This is not surprising since AFAIU, environment variables are not actually stored in the environment image, they are set in the deployment k8s configuration of the pods).

**Expected behavior**
After the update, `MY_VAR` value should be `"1"`

**Comment by yunhaoling** [comment]
thanks for reaching out @janluke , I have tagged the issue and the service team should be able to help with it.

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by janluke** [comment]
FYI, I provided a minimal reproducible example to the support engineer who handled my support request some time ago. It can be found here: https://github.com/janluke/azureml-issue-23278.

I'm personally not interested on this issue any more, since I provide my environment variables injecting an .env file to the uploaded source code folder. I'd be interested again if you provided a sane way to provide secrets (see #23277).

**Comment by luigiw** [comment]
@janluke v1 SDK is in maintenance only mode in favor of the v2 SDK being GA. Please file an issue for v2 SDK if your requests stand for v2.
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-migrate-from-v1
