### ISSUE TITLE
Confusing exception message

### ISSUE THREAD

**Issue by islem-esi** [Azure/azure-sdk-for-python#23283]
As I was looking at the code in this [File](https://github.com/Azure/azure-sdk-for-python/blob/0a0cc97f178a7476ec79f29c090b8c93ad5d4955/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py), I got confused by the exception message. I think the **word "not"** is mistakenly repeated in the **exception message**, otherwise it would be better to remove 'not not' (See code below).

```
   try:
        parsed_uri = parse.urlparse(source_id)
    except Exception:  # pylint: disable=broad-except
        raise ValueError("'{}' is not not a valid ID".format(source_id))
    if not (parsed_uri.scheme and parsed_uri.hostname):
        raise ValueError("'{}' is not not a valid ID".format(source_id))
```
Is it the case?

**Comment by annatisch** [comment]
Thanks so much for reporting this @islem-esi - I think you're right, this is probably a mistake, if not - double-negatives are a confusing grammar choice for an error message :)
Let's get that fixed up....

**Comment by annatisch** [comment]
I opened a quick PR to fix - @mccoyp could you please do a quick review to confirm I haven't misinterpreted the error message?

**Comment by mccoyp** [comment]
Thank you @islem-esi for catching this, and thank you @annatisch for opening a PR! I'll get that approved. We definitely didn't mean to leave confusing double-negatives around 😅
