### ISSUE TITLE
[BUG] DefaultAzureCredential not working when executing get_paths function from azure.storage.filedatalake.FileSystemClient

### ISSUE THREAD

**Issue by JPardinas** [Azure/azure-sdk-for-python#23304]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.5.0
- **Operating System**: Windows / Linux
- **Python Version**: 3.8

**requirements.txt**
```
azure-functions==1.8.0
azure-storage-file-datalake==12.5.0
azure-identity==1.8.0
```
**Describe the bug**
Using Azure Functions with python:

When using Managed Identity for authentication **get_paths** function from **FileSystemClient** is raising the following exception:
- azure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'The specified container does not exist.'

When using connection string is working as expected

**To Reproduce**
1. **Create managed identity and define Contributor role access (if testing locally be sure your account have access to the storage account)**

2. **Code example that raises an error using DefaultAzureCredential**
```python
import logging

from azure.storage.filedatalake import FileSystemClient
from azure.identity import DefaultAzureCredential

# Config
managed_identity_id = 'my_managed_identity_id'
storage_resource_name = 'my_azure_data_lake_storage'
storage_container_name = 'my_container_name'
account_url = f'https://{storage_resource_name }.blob.core.windows.net'

# Get client
credential = DefaultAzureCredential(managed_identity_client_id=managed_identity_id)
client = FileSystemClient(account_url=account_url, file_system_name=storage_container_name, credential=credential)

if not client.exists():
    client.create_file_system()
    client.create_directory('test_folder')

storage_container_paths = client.get_paths()

# Next line will raise the error
paths = list(storage_container_paths)
logging.info(paths)

```

3. **Code example that works using a connection string**
```python
import logging

from azure.storage.filedatalake import FileSystemClient

# Config
storage_connection_string = 'my_storage_connection_string'
storage_container_name = 'my_container_name'
client = FileSystemClient.from_connection_string(file_system_name=storage_container_name, conn_str=storage_connection_string)

if not client.exists():
    client.create_file_system()
    client.create_directory('test_folder')

storage_container_paths = client.get_paths()

# Next line will work
paths = list(storage_container_paths)
logging.info(paths)
```

4. **Code that works using azure.storage.blob.ContainerClient and DefaultAzureCredential**
```python
import logging

from azure.storage.blob import ContainerClient
from azure.identity import DefaultAzureCredential

# Config
managed_identity_id = 'my_managed_identity_id'
storage_resource_name = 'my_azure_data_lake_storage'
storage_container_name = 'my_container_name'
account_url = f'https://{storage_resource_name }.blob.core.windows.net'

# Get client
credential = DefaultAzureCredential(managed_identity_client_id=managed_identity_id)
client = ContainerClient(account_url=account_url, container_name=storage_container_name, credential=credential)

if not client.exists():
    client.create_container()
    client.upload_blob(name="myblob", data='data')

storage_container_paths = client.list_blobs()

# Next line will work
paths = list(storage_container_paths)
logging.info(paths)
```

**Expected behavior**
Program should success and print in the log a list with storage container data

**Additional context**
- Using in an Azure Functions project setup with an user defined managed identity, it raise an error in the deployed app and when executing locally.

- As far as I saw this error only happens when executing get_paths() function

**Comment by yunhaoling** [comment]
thanks @JPardinas for reaching out, we'll investigate it asap.

**Comment by JPardinas** [comment]
Just created another issue that maybe is related: https://github.com/Azure/azure-sdk-for-python/issues/23369
