### ISSUE TITLE
Intermittent pipeline failures for macOS due to seed failures.

### ISSUE THREAD

**Issue by jalauzon-msft** [Azure/azure-sdk-for-python#23326]
Seeing intermittent pipeline failures due to failures in task `Populate the seed dir`.
[Example ](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1408191&view=logs&jobId=c7500c44-708b-56ec-f52b-02af33ea1457&j=c7500c44-708b-56ec-f52b-02af33ea1457&t=630fb06f-c454-5b07-1e0a-a3e8eb1f5fe0) (Storage ci)

**Comment by scbedd** [comment]
Query for reference.

```
BuildLogLine
| where Timestamp >= now(-3d)
| where Message startswith "RuntimeError: seed failed due to failing to download"
| join kind=leftouter (Build | project BuildNumber, BuildId, DefinitionName, WebLink=extract_json("$_links.web.href", Data, typeof(string))) on $left.BuildId == $right.BuildId
| join kind=leftouter (BuildTimelineRecord) on LogId, ProjectId, BuildId
| sort by BuildNumber desc
```

All failing due to a specific exception on mac / python 3.7. It is no longer a network traversal issue. I am going forward with wrapping the whole thing in a retry, but I have a bad feeling that will not be a permanent solution.
