### ISSUE TITLE
Update docstrings for `ContainerProxy` 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#23346]
Fix doc strings here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/azure/cosmos/container.py#L47-L48 

To reference the containing modules. Also, looks like `create_container` might need to be coming from `DatabaseProxy` instead of `Database`: 

Suggestion: 

```
    :func:`azure.cosmos.database.DatabaseProxy.get_container_client` method to get an existing
 
    container, or the :func:`azure.cosmos.database.DatabaseProxy.create_container` method to create a
 
    new container.
```

Source issue: https://ceapex.visualstudio.com/Engineering/_workitems/edit/470993#9319299

**Comment by simorenoh** [comment]
Closing issue with update to docs PR: https://github.com/Azure/azure-sdk-for-python/pull/23608/
