### ISSUE TITLE
[core] implement our own CaseInsensitiveDict

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#23347]
Right now, our [current implementation](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/utils/_utils.py#L84) relies on either having the `requests` or `aiohttp` library installed. Instead, we want to implement our own case insensitive dict, so we can get rid of this dependency

**Comment by kashifkhan** [comment]
We can close this one because of #25074 right ?

**Comment by iscai-msft** [comment]
yep, closing now
