### ISSUE TITLE
missing code in import library parts

### ISSUE THREAD

**Issue by KewinOsborn** [Azure/azure-sdk-for-python#23342]
The missing parts are bold. 

```
import os
import pandas as pd
from datetime import datetime, timezone
from azure.monitor.query import LogsQueryClient,**LogsQueryStatus**
from azure.identity import DefaultAzureCredential
**from azure.core.exceptions import HttpResponseError**

credential = DefaultAzureCredential()
client = LogsQueryClient(credential)

query = """AppRequests | take 5"""

start_time=datetime(2021, 7, 2, tzinfo=timezone.utc)
end_time=datetime(2021, 7, 4, tzinfo=timezone.utc)

try:
    response = client.query_workspace(
        workspace_id=os.environ['LOG_WORKSPACE_ID'],
        query=query,
        timespan=(start_time, end_time)
        )
    if response.status == LogsQueryStatus.PARTIAL:
        error = response.partial_error
        data = response.partial_data
        print(error.message)
    elif response.status == LogsQueryStatus.SUCCESS:
        data = response.tables
    for table in data:
        df = pd.DataFrame(data=table.rows, columns=table.columns)
        print(df)
except HttpResponseError as err:
    print("something fatal happened")
    print (err)


```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 086893ce-7b34-6c37-f2e5-36a3505baa69
* Version Independent ID: 14650046-8b8a-8f9c-b5be-8ae6bd27044b
* Content: [Azure Monitor Query client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/monitor-query-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/monitor-query-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/monitor-query-readme.md)
* Service: **monitor**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by yunhaoling** [comment]
thanks @KewinOsborn for reaching out.

Just to confirm is it **from azure.core.exceptions import HttpResponseError** that is missing import in your code?
also could you share us with the package version information for azure-core?

**Comment by xiangyan99** [comment]
Seems like we are missing import statement in the samples in https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/monitor-query-readme.md. 

Adding @sima-zhu since she edited the file.

**Comment by lzchen** [comment]
I am not an owner of this. Please reassign.

**Comment by sima-zhu** [comment]
Docs repo readme reads from sdk repo
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-query/README.md#specify-timespan

The link above is the place fix the issue. Please verify and get it fixed. Docs will update live site weekly.

**Comment by xiangyan99** [comment]
@sima-zhu Thank you for the information.

@rakshith91 @swathipil I see you modified the README above. Could you help to take a look?
