### ISSUE TITLE
Make custom transport implementation possible without "requests" installed.

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#23348]
We will have situation in the future where "requests" will not be available at all, and people will write their own transport. Today, we expect "requests" to be available in  a few places, making azure-core not truly independant.

See also:
- https://github.com/Azure/azure-sdk-for-python/issues/11276
- https://github.com/Azure/azure-sdk-for-python/issues/23347

**Comment by xiangyan99** [comment]
#25344
