### ISSUE TITLE
Post-test proxy test clean-up

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#23352]
Once all SDKs are in text proxy, there is an important clean-up to do on the test framework:
- Simplify the double packaging infra that is inherited of the time we were sharing with CLI team
- Delete obsolete code
- Migrating preparers to use all the engsys Powershell script system

**Comment by mccoyp** [comment]
The `azure-devtools` folder has been fully deprecated; remaining work is tracked by https://github.com/Azure/azure-sdk-for-python/issues/31741
