### ISSUE TITLE
[security-attestation] mypy: function has duplicate type signatures

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#23357]
There are duplicate type signatures present in this function which prevents mypy from continuing to run checks:

https://github.com/Azure/azure-sdk-for-python/blob/c247151acbb19591444144ca723c723cabfd45a6/sdk/attestation/azure-security-attestation/azure/security/attestation/aio/_client_async.py#L376-L378

This prevents customers from getting typing information from the package.

This is reproducible by running mypy==0.931 at the package level directory:

```
azure-sdk-for-python\sdk\attestation\azure-security-attestation>python -m mypy ./azure
azure\security\attestation\aio\_client_async.py:376: error: Function has duplicate type signatures
Found 1 error in 1 file (errors prevented further checking)
```

**Comment by SaurabhSharma-MSFT** [comment]
@kristapratico I am redirecting this to respective team to look into it for the fix.

**Comment by kristapratico** [comment]
tracked in https://github.com/Azure/azure-sdk-for-python/issues/32817
