### ISSUE TITLE
azure-storage-blob BlobClient.upload_blob mistyped argument

### ISSUE THREAD

**Issue by jayqi** [Azure/azure-sdk-for-python#23362]
- **Package Name**: `azure-storage-blob`
- **Package Version**:  12.9.0

**Describe the bug**

`azure.storage.blob.BlobClient.upload_blob` and the method that it wraps `BlobClient._upload_blob_options` both have the type annotation `Union[Iterable[AnyStr], IO[AnyStr]]` for the `data` argument. 

https://github.com/Azure/azure-sdk-for-python/blob/d720e568b7dde29af68fe6a0f57c0dba8dff4b55/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L573-L579

https://github.com/Azure/azure-sdk-for-python/blob/d720e568b7dde29af68fe6a0f57c0dba8dff4b55/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L339-L345

However, these methods also support cases where data is `str` or `bytes`.

This bit handles the case where `data` is `str`: 
https://github.com/Azure/azure-sdk-for-python/blob/d720e568b7dde29af68fe6a0f57c0dba8dff4b55/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L361-L362

and this bit handles the case where `data` is `bytes`:
https://github.com/Azure/azure-sdk-for-python/blob/d720e568b7dde29af68fe6a0f57c0dba8dff4b55/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L368-L369

**Expected behavior**

The current annotation should be `Union[AnyStr, Iterable[AnyStr], IO[AnyStr]]`.

**Comment by amishra-dev** [comment]
@iscai-msft / @jalauzon-msft is this issue fixed or still needs a fix from us?

**Comment by jalauzon-msft** [comment]
@amishra-dev, @jayqi made a pull request for this already (thanks Jay!). 

@jayqi, Laurent left a comment on your PR asking if you could implement the same fix in the async client as well since we like to keep those in sync. Please let us know if this is something you can do.

**Comment by jayqi** [comment]
Hi @jalauzon-msft—I was wondering when to expect this fix to make it into a release? This bug had caused an error with mypy static typechecking for my library. I'm trying to understand if it might be released soon or if I should put in a workaround for now. Thanks!

**Comment by jalauzon-msft** [comment]
Hi @jayqi Jay, unfortunately this just missed our previous release of 12.10.0. Our next planned release is in early April but that will be a beta/preview release. The next non-beta release is tentatively planned for early May.
