### ISSUE TITLE
DLL load failed while importing win32file

### ISSUE THREAD

**Issue by JoelCanteroGCO** [Azure/azure-sdk-for-python#23371]
- **Package Name**: azureml-core
- **Package Version**: 1.39
- **Operating System**: Windows 10
- **Python Version**: 3.9

**Describe the bug**
When I try to retrieve the workspace:
`workspace = Workspace.from_config()`

it throws an error:

`Performing interactive authentication. Please follow the instructions on the terminal.                                                                                                                                                       No se ha podido cargar correctamente el archivo config.json.                                                                                                                                                                                 DLL load failed while importing win32file: No se encontró el proceso especificado.`

I think it is related to the pywin32 package. It is in 227 version. It can be solved if I try to install pywin32 with conda installer:

`conda install pywin32`

and then it is upgraded to version 332. But when I try again to retrieve the workspace, it throws some warnings before retrieving the workspace:

Obteniendo workspace de Azure Machine Learning...                                                                                                                                                                                            `Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.PipelineRun = azureml.pipeline.core.run:PipelineRun._from_dto with exception (pywin32 302 (c:\users\ue9553\.conda\envs\azure\lib\site-packages), Requirement.parse('pywin32==227; sys_platform == "win32"'), {'docker'}).                                                                                                                                                                             Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.ReusedStepRun = azureml.pipeline.core.run:StepRun._from_reused_dto with exception (pywin32 302 (c:\users\ue9553\.conda\envs\azure\lib\site-packages), Requirement.parse('pywin32==227; sys_platform == "win32"'), {'docker'}).                                                                                                                                                                        Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.StepRun = azureml.pipeline.core.run:StepRun._from_dto with exception (pywin32 302 (c:\users\ue9553\.conda\envs\azure\lib\site-packages), Requirement.parse('pywin32==227; sys_platform == "win32"'), {'docker'}).                                                                                                                                                                                     Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.scriptrun = azureml.core.script_run:ScriptRun._from_run_dto with exception (pywin32 302 (c:\users\ue9553\.conda\envs\azure\lib\site-packages), Requirement.parse('pywin32==227; sys_platform == "win32"'), {'docker'}).`

How can I solve it?

Thank you,
Joel

**Comment by catalinaperalta** [comment]
Thanks for your question @JoelCanteroGCO! We'll get back to you with an answer asap

**Comment by JoelCanteroGCO** [comment]
Thank you @catalinaperalta, I will remain attentive to your answer.

**Comment by JoelCanteroGCO** [comment]
It is solved using this command in my [conda environment folder]/Scripts

`python Scripts\pywin32_postinstall.py -install`

Reference: https://github.com/mhammond/pywin32/issues/1431#issuecomment-548584385

It is a problem with pywin32=227 dependency of azureml-core. Maybe updating this version to the last one can solve the problem.

Thank you very much,
Joel

**Comment by xiangyan99** [comment]
Thank you for the updates.
