### ISSUE TITLE
Get this error "Date must have only digits and -. Received: yyyy-02-04" on line "poller.result()"

### ISSUE THREAD

**Issue by gl-Roy** [Azure/azure-sdk-for-python#23385]
This is for Form Recognizer service and with prebuilt invoice model.

With some of forms, I got this error "Date must have only digits and -. Received: yyyy-02-04" on line "poller.result()" and couldn't continue.   I had to skip the whole form.   

Sample codes: 
            poller = document_analysis_client.begin_analyze_document_from_url("prebuilt-invoice", formUrl)
            invoices = poller.result()

How can I ignore/bypass this date parse error and to get the rest of values from the form?  

I'm using:
azure-ai-formrecognizer==3.2.0b3
Python 3.7.12

Thanks!

**Comment by catalinaperalta** [comment]
Hi @gl-Roy! Thanks for reporting this issue. I will let the Form Recognizer service team know so that they can add a fix for this ASAP. I will update you here when they've released an update with the fix.

**Comment by catalinaperalta** [comment]
Just wanted to give an update, that the service team is working on this and should have a fix out soon. Will post again once the fix is out.

**Comment by catalinaperalta** [comment]
Hi @gl-Roy the service fix is available now! You can re-run your requests and you should be able to get a response now. Please note that in this case for "incomplete" date values the method to retrieve this information is by accessing the `content` attribute which will return the string representation of the value.

I will close this issue now, but feel free to reopen this if you need more information and also open new issues if there are any other issues with the SDK!
