### ISSUE TITLE
RecoveryServicesClient Item Paged and Authority Error

### ISSUE THREAD

**Issue by anotherancientalien** [Azure/azure-sdk-for-python#23402]
Please delete as the issue transferred to support

**Comment by anotherancientalien** [comment]
Please provide solution. Support doesn't accept SDK problems!! If there isn't support for solution for sdk, please inform us for using another solutions or break developments for azure!!!!!

**Comment by catalinaperalta** [comment]
Hi @anotherancientalien! I will close this for now then, please feel free to reopen if you need more help.
