### ISSUE TITLE
Multiple aggregated SQL query freezing

### ISSUE THREAD

**Issue by AWendland-CryptoCompare** [Azure/azure-sdk-for-python#23440]
- Package Name: azure.storage.blob
- Package Version: 12.9.0
- Operating System: Linux
- Python Version: 3.8.8

**Describe the bug**
Multiple aggregators for SQL queries break the request. This follows on from [issue 23159](https://github.com/Azure/azure-sdk-for-python/issues/23159) about using the queer_blob function on the BlobClient class.

**To Reproduce**
The following queries runs fine:
a)
SELECT \"timestamp\", \"side\", \"price\"
FROM BlobStorage;
b)
SELECT MIN(CAST(\"price\" AS FLOAT) AS \"min_value\"
FROM BlobStorage;
however the following queries do not work
c)
SELECT MIN(CAST(\"price\" AS FLOAT), MAX(CAST(\"price\" AS FLOAT) 
FROM BlobStorage;
d)
SELECT \"timestamp\", \"side\", MIN(CAST(\"price\" AS FLOAT) 
FROM BlobStorage;

**Expected behavior**
In case
c)
I would expect both the min and max value to be returned, however the process freezes and doesn't return a value.
d) 
I would expect the timestamp, side and price of the minimum value to be returned.

**Comment by catalinaperalta** [comment]
Thanks for reporting this @AWendland-CryptoCompare! Adding @jalauzon-msft who may have more insight on the issue.

**Comment by jalauzon-msft** [comment]
Hi again @AWendland-CryptoCompare Alex, my guess is that types of queries, with multiple aggregations or aggregations included with columns, are not supported by the service. I also get an error when I try similar queries.

I can reach out to the service team internally and verify.

**Comment by jalauzon-msft** [comment]
@AWendland-CryptoCompare Alex, I heard back from the service team and wanted to provide an update.

For example c: `SELECT MIN(CAST("price" AS FLOAT), MAX(CAST("price" AS FLOAT)` - Unfortunately, the service does not currently support multiple aggregations in a single query so this kind of query will not work.
For example d: `SELECT "timestamp", "side", MIN(CAST("price" AS FLOAT)` - I do not believe this is valid SQL. Using an aggregation along with columns names is not supported without using `GROUP_BY` (which the service does not currently support).
