### ISSUE TITLE
Error Mesasges from `service_client.upsert_digital_twin` API

### ISSUE THREAD

**Issue by BillmanH** [Azure/azure-sdk-for-python#23445]
When using the python API, I'm unable to get good error messages from `service_client.upsert_digital_twin()`. The only thing it returns is "Invalid twin specified". 

**However** when I went to the ADT Explorer tool and entered the values manually I got a full description of the problem:
```
{
  "code": "ValidationFailed",
  "message": "Invalid twin specified",
  "details": [
    {
      "code": "ValidationFailed",
      "message": "input is not a property - it is a Relationship."
    },
    {
      "code": "ValidationFailed",
      "message": "output is not a property - it is a Relationship."
    }
  ]
}
```

That is way more useful than just saying "Invalid twin specified".  It would be so helpful to end users if you could expose the details in the 

**solution I'd like**
A `details` component of the error exists. Please pass it back with the error in the API. 

**alternatives considered**
You can go to the ADT tool and look up your error manually, but that's tedious and won't scale.

**Comment by BillmanH** [comment]
good robot

**Comment by annatisch** [comment]
Thanks for the report @BillmanH!
We should definitely find a way to surface the useful parts of the error message.
The information _should_ be available on the raised Exception - however this means one had to know if advance to catch and inspect it in order to get the data.
In the meantime, if you do catch the error, you should find this on the `HttpResponseError.model` attribute.

Adding the DT team to investigate :)

**Comment by BillmanH** [comment]
Ah, but an invalid request does not create an exception in Python.  `upsert_digital_twin` runs the error and choses what to send back, removing the needed `details`

Looking at the [client library](https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/digitaltwins/azure-digitaltwins-core/azure/digitaltwins/core/_digitaltwins_client.py)

You can see that it does it's own `if_none_match, error_map = prep_if_none_match(etag, match_condition)`.  Then it passes the error map back to the user.  I couldn't find the `error_map` function but I don't believe that it returns the error details in all cases.  The error itself is always `Invalid twin ID specified`.  Sometimes that error is followed by details and sometimes it isn't.

**Comment by BillmanH** [comment]
Actually, after some consideration @annatisch has a good remediation. I did catch the issue, but I didn't store the `e` Going back through it I found that I could get the full message from: 
```
e.model.as_dict()
```
@annatisch is right. The values are there. This is good to go.

**Comment by annatisch** [comment]
Hi @BillmanH - thanks for following up!
Good to hear that the workaround is working for you :)
