### ISSUE TITLE
Incorrect information about storage account

### ISSUE THREAD

**Issue by sdebruyn** [Azure/azure-sdk-for-python#23466]
From the current version of this page:

>Create and train a custom model. The request must include a training_files_url parameter that is an externally accessible Azure storage blob container URI (preferably a Shared Access Signature URI). Note that a container URI (without SAS) is accepted only when the container is public. Models are trained using documents that are of the following content type - 'application/pdf', 'image/jpeg', 'image/png', 'image/tiff', or 'image/bmp'. Other types of content in the container is ignored.

This is incorrect. You can also use Managed Identity on the Form Recognizer that has access to the storage account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07c46934-593b-6b31-f57f-ab77fb1f428e
* Version Independent ID: 8c347ddf-05a4-31c2-1951-e0b75daa50ce
* Content: [azure.ai.formrecognizer.FormTrainingClient class](https://docs.microsoft.com/en-us/python/api/azure-ai-formrecognizer/azure.ai.formrecognizer.formtrainingclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-formrecognizer/azure.ai.formrecognizer.FormTrainingClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-ai-formrecognizer/azure.ai.formrecognizer.FormTrainingClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by sdebruyn** [comment]
Related https://github.com/MicrosoftDocs/azure-docs/issues/89555

**Comment by kristapratico** [comment]
@sdebruyn thanks for pointing this out! We'll get the docs fixed up asap.
