### ISSUE TITLE
Async iteration over AsyncSearchItemPaged raises Forbidden on fetching next page

### ISSUE THREAD

**Issue by MrToustous** [Azure/azure-sdk-for-python#23467]
- **Package Name**: azure-search-documents 
- **Package Version**: 11.2.1
- **Operating System**: Ubuntu
- **Python Version**: 3.9.7

**Describe the bug**
When using the Async version of the SearchClient from azure-search-documents python SDK, I get an error when iterating over a Search result with more than 50 products. It looks like the error occurs when thz AsyncSearchItemPaged object tries to post for the next page. I then get a "HttpResponseError: Operation returned an invalid status 'Forbidden'"

**To Reproduce**
1. Create an index with at least 50 items
2. Instantiate a SearchClient from azure.search.documents.aio
3. Request the empty string to get all documents
4. iterate over the search results with: 
`async for x in results:
    print(x)`

**Expected behavior**
I would expect every result to be printed, or to get a way to iterate over the pages of results without getting an error.

**Comment by kristapratico** [comment]
Hi @MrToustous thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by kashifkhan** [comment]
Hi @MrToustous I am working on fixing the issue on my side. In the meantime as a work around, I was able to use the sync client and retrieve the items from the index properly.
