### ISSUE TITLE
[AMQP Python] MISC improvement

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#23473]
This issue is for tracking misc items that we could improve based on the uamqp development experience:

- The constructor of `ReceiveClient` supports overwriting on_message_received_callback. ([issue](https://github.com/Azure/azure-sdk-for-python/pull/23285#discussion_r824016119))

**Comment by swathipil** [comment]
done here: https://github.com/Azure/azure-sdk-for-python/blob/57fa94383ddf0a1446781ba4507ce4538815b4c8/sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py#L876
