### ISSUE TITLE
dataflow Reference is missing in Pipeline.get

### ISSUE THREAD

**Issue by SomanathSankaran** [Azure/azure-sdk-for-python#23488]
- **Package Name**:  azure_mgmt_datafactory-2.3.0-py3-none-any.whl
- **Package Version**: 2.3.0
- **Operating System**:ubuntu
- **Python Version**: 3.8.10 

**Describe the bug**
We have a pipeline with for each activity which has a if activity which in-turns calls a data flow activity 
we called adf_client.pipelines.get and when we tried to get data flow name from dataflow activity by using 
df_act.data_flowit is returning None

command : print(df_act.type,df_act.data_flow)
output
ExecuteDataFlow None

**To Reproduce**
1. 

**Expected behavior**
We need to have the dataflow name so that we can get the dependencies 

command : print(df_act.type,df_act.data_flow)
output
ExecuteDataFlow DF_FLOW ( Name of the underlying DataFlow )

**Screenshots**

**Additional context**

**Comment by SomanathSankaran** [comment]
I also tried to validate the returned dataflow activity using validate()
and got below error

df_act.validate()
msrest.exceptions.ValidationError("Parameter 'ExecuteDataFlowActivity.data_flow' can not be None."

**Comment by msyyc** [comment]
Hi @SomanathSankaran We can't reproduce the error. Please provide more details about the issue like: https://github.com/Azure/azure-sdk-for-python/issues/24740.
