### ISSUE TITLE
Personalizer RankResponse reamined probability

### ISSUE THREAD

**Issue by javhd72** [Azure/azure-sdk-for-python#23489]
Question: Personalizer splits the remained probability evenly between the other actions?
Personalizer service ranked the actions with the probabilities as below:
steak 0.85
ice cream 0
apple pie 0
juice 0
salad 0.05
crepes 0
spice chicken 0.05
pasta 0.05

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9de7f3-22b9-c9c2-c240-3f12e8671b93
* Version Independent ID: 7f39a8ff-3be1-59e9-a6ba-1fa7631c0a19
* Content: [azure.cognitiveservices.personalizer.models.RankResponse class](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-personalizer/azure.cognitiveservices.personalizer.models.rankresponse?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cognitiveservices-personalizer/azure.cognitiveservices.personalizer.models.RankResponse.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-cognitiveservices-personalizer/azure.cognitiveservices.personalizer.models.RankResponse.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by SaurabhSharma-MSFT** [comment]
@javhd72 Can you please provide more details if this happens to any number of inputs you are providing to the RankAPI ?

**Comment by YutongTie-MSFT** [comment]
@javhd72 Hello Javier, I don't think we have this internal logic, but I will double check to confirm and let you know.

**Comment by YutongTie-MSFT** [comment]
@javhd72 Hello, sorry for the late reply, I have brought this to product team attention, I will let you know once there is any response I get.

**Comment by YutongTie-MSFT** [comment]
@javhd72 Hello Javior, I just got confirmation from the development team, there is no probability split policy. 

The model determines the percentages and it seems reasonable that the model has given salty as a highly weighted feature for the given context; resulting in equal proportions of probability for those actions. I hope this answers your question. 

Regards,
Yutong

**Comment by SaurabhSharma-MSFT** [comment]
@javhd72 Please let us know if you have any questions, otherwise, we will proceed with the closure of this issue.
