### ISSUE TITLE
ConsumptionClient reservations_summaries.list error of MissingSubscription

### ISSUE THREAD

**Issue by rikiAnodot** [Azure/azure-sdk-for-python#23515]
- **Package Name**:  ConsumptionManagementClient
- **Package Version**: 9.0.0 
- **Operating System**: IOS
- **Python Version**: 3.7

**Describe the bug**
After updating the creds for app registration as described here: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#cost-management-reader

I am facing the same error: '(MissingSubscription) The request did not have a subscription or a valid tenant level resource provider.
Code: MissingSubscription
Message: The request did not have a subscription or a valid tenant level resource provider.'

**To Reproduce**
```
from azure.mgmt.consumption import ConsumptionManagementClient

credentials = retrieve_m
subscription_id = 'XXXXXXXXXXXXXXX'
consumption_client = ConsumptionManagementClient(
    credentials,
    subscription_id,
    'https://management.azure.com'
)
scope = subscription_id
reservation_generator = consumption_client.reservations_summaries.list(scope=scope, grain='monthly')
for reservation in reservation_generator:
    print(reservation)
```

**Expected behavior**
I expected that in subscription_id which has the required creds, I will be able to loop on the reservation summary result. but it failed in the loop.

**Screenshots**

**Additional context**
It is pretty hard to find good documentation for consumption_summary package.
If I did something wrong in the code, please reference me to relevant resource.
Just to mention that ` consumption_client.usage_details.list(scope, filter=date_filter)` worked fine.

**Comment by msyyc** [comment]
Hi @rikiAnodot , the error code is responded by server which seems mean that you don't have access to do the operation. We need expert from service team to help on the issue

**Comment by xiangyan99** [comment]
Please open a support ticket for the service team.
