### ISSUE TITLE
403 Authentication Failure with Blob SAS

### ISSUE THREAD

**Issue by metamoof** [Azure/azure-sdk-for-python#23564]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.10.0
- **Operating System**: Windows 10
- **Python Version**: 3.9.9

**Describe the bug**
I'm attempting to generate a blob-specific Shared Access Signature, but the signature in question is not working correctly.

**To Reproduce**
I have prepared a small test script against the default azurite install (I have also tested it against an azure storage account)

```python
# %%
import datetime
import urllib
from azure.storage.blob import BlobServiceClient, BlobSasPermissions, generate_blob_sas


CONNECTION_STRING = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
STORAGE_CONTAINER = "test-container"

TEST_TEXT = """This is a test text file
It has text in it"""
TEST_FILE_NAME = "testfile.txt"

blob_service_client = BlobServiceClient.from_connection_string(CONNECTION_STRING)
if STORAGE_CONTAINER in (c["name"] for c in blob_service_client.list_containers()):
    container = blob_service_client.get_container_client(STORAGE_CONTAINER)
    container.delete_container()

container = blob_service_client.create_container(STORAGE_CONTAINER)

blob_client = container.upload_blob(name=TEST_FILE_NAME, data=TEST_TEXT.encode("utf8"))

token = generate_blob_sas(
    account_name=blob_service_client.account_name,
    container_name=container.container_name,
    blob_name=TEST_FILE_NAME,
    account_key=blob_service_client.credential.account_key,
    permission=BlobSasPermissions(read=True),
    start=datetime.datetime.utcnow() + datetime.timedelta(days=-1),
    expiry=datetime.datetime.utcnow() + datetime.timedelta(days=1),
)

url = f"{container.primary_endpoint}/{TEST_FILE_NAME}?{token}"
print(f"Retrieving URL: {url}")

try:
    resp = urllib.request.urlopen(url)
except urllib.error.HTTPError as e:
    print(e)
```

The result I get is:

```
Retrieving URL: http://127.0.0.1:10000/devstoreaccount1/test-container/testfile.txt?st=2022-03-16T17%3A01%3A53Z&se=2022-03-18T17%3A01%3A53Z&sp=rt&sv=2021-04-10&sr=b&sig=yr6pC40fCR4sliU%2BeyOY5h1qROj/AII0LGKMoha3Dz0%3D
HTTP Error 403: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
```

**Expected behavior**
To get a status code 200 and have the file in `resp`.

**Comment by jalauzon-msft** [comment]
Hi @metamoof Giles, thanks for reporting the issue. We'll look into it ang get back to you.

**Comment by jalauzon-msft** [comment]
Hi @metamoof Giles, I have verified that blob SAS is working as expected in this version of the SDK and that your sample works outside of Azurite. Please verify that you have properly setup Azurite to work with the SDKs using this [documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#authorization-for-tools-and-sdks).

For further investigation, please open an Issue with the Azurite repo [here](https://github.com/Azure/Azurite/issues). They should be able to better assist you. Thanks.

**Comment by tomasgiden** [comment]
Hi! Can verify the issue on my side too: Tokens generated by 12.10.0 cannot be used with Azurite. Is reported to Azurite (by someone else). https://github.com/Azure/Azurite/issues/1404

**Comment by jalauzon-msft** [comment]
Hi @tomasgiden Tomas, @metamoof Giles, looks like this is being addressed by a change to Azurite. https://github.com/Azure/Azurite/pull/1393

With the current version of Azurite, SAS generated for versions after 2020-10-02 are not currently supported due to an update in SAS token generation.

**Comment by jalauzon-msft** [comment]
Closing this as the bug is being tracked/fixed on the Azurite side: https://github.com/Azure/Azurite/issues/1404
