### ISSUE TITLE
azure-servicebus regression in 7.6.0: 'utf-8' codec can't decode byte 0xe4

### ISSUE THREAD

**Issue by DanielMescheder-TomTom** [Azure/azure-sdk-for-python#23576]
- Package: **azure-servicebus**: 
- Version: **7.6.0**: 
- OS: **Linux**:
- Python version: **3.6.9**: 

**Describe the bug**
A simple code snippet to fetch messages from a servicebus queue (see below) fails with the error message
`Authentication Put-Token failed. Retries exhausted`.
The debug logs reveal that the problem might be related to encoding issues:
```
AMQP Connection authentication error occurred: (AuthenticationException("Token authentication failed: 'utf-8' codec can't decode byte 0xe4 in position 0: invalid continuation byte")).
```

**To Reproduce**
1. Set up an azure servicebus
2. With the package versions noted above installed run the following script:

```
from azure.servicebus import ServiceBusClient
queue_connection="<your copied connection string>"
queue_name = "<your queue name>"
service_client = ServiceBusClient.from_connection_string(queue_connection)
with service_client.get_queue_receiver(queue_name) as receiver:
    messages = receiver.receive_messages(max_message_count=1, max_wait_time=10)
    print(messages)
```

**Expected behavior**
The code snippet should print the latest available message or empty list.

**Additional context**

The same code snippet works fine with version 7.4.0.

**Comment by DanielMescheder-TomTom** [comment]
I now have a working version with 7.6.0 so it might not be related to that particular version after all. I need to check what changed between the run the worked and the run that failed.

**Comment by DanielMescheder-TomTom** [comment]
I cannot reproduce the problem any longer. It may very well be a networking problem and the utf-8 message is just a follow-up error that is distracting from the real issue.

**Comment by kashifkhan** [comment]
Hi @DanielMescheder-TomTom  thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by yunhaoling** [comment]
hey @DanielMescheder-TomTom , `'utf-8' codec can't decode byte 0xe4` means the incoming bytes are corrupted such that the client can not decode it in the right form.

It's very much like what you mentioned that there was a transient networking error leading to this.
You could handle the error by catching the exception and recreating a new client.
