### ISSUE TITLE
Broken links in custom pylint checks

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#23580]
The custom pylint checks have broken links in them.
https://azure.github.io/azure-sdk/python_introduction.html#types-or-not
https://azure.github.io/azure-sdk/python_introduction.html#method-signatures
https://azure.github.io/azure-sdk/python_introduction.html#naming-conventions
https://azure.github.io/azure-sdk/python_introduction.html#public-vs-private

Looks like they broke when the Python guidelines structure was changed.
We should:
1) fix the broken links
2) refactor the code so that we can leverage the 404 link checker to detect this condition

cc/ @lmazuel

**Comment by lmazuel** [comment]
@l0lawrence we have in a link checker in CI, that would block the CI if some links are incorrect. We probably want to see what it takes to make those links part of the CI process. Maybe it means externalizing those links into a file, and the Python code read that file, etc. I'm not sure of the design. We should talk to @weshaggard about this.

**Comment by l0lawrence** [comment]
Links are checked as tests

**Comment by weshaggard** [comment]
@l0lawrence for reference how did you enable this link checking?

**Comment by l0lawrence** [comment]
Originally the pylint tests were not run on a pipeline, but with the move to the sdk-tools a [pipeline ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2144319&view=logs&j=9970d973-4294-51e0-bc18-c59342cf31c4&t=adad61f2-c9b2-547e-d0f3-d16a93543dd7) was created so tests like [this](https://github.com/Azure/azure-sdk-tools/blob/b0b5a8b5fd23fecd99df3014cd4bb26169b050a2/tools/pylint-extensions/pylint-guidelines-checker/tests/test_pylint_custom_plugins.py#L207) would now show if they fail.
