### ISSUE TITLE
azure-identity is not compatible with azure-batch

### ISSUE THREAD

**Issue by Blabll** [Azure/azure-sdk-for-python#23583]
Hello,

I would like to use **azure-identity** in combination with **azure-batch** to instantiate a `BatchServiceClient`.
But the `BatchServiceClient `requires a _msrestazure Credentials_ and is not compatible with `DefaultAzureCredential`.

After reading the following documentation:
https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-hosted-applications#credential-object-has-no-attribute-signed_session
I managed to connect to the Batch Account thanks to the `CredentialWrapper` class.

But I would like to know if there is a timeline for the azure-batch package to be compatible with azure-identity. 

I also came across a similar issue (closed) about different resources: https://github.com/Azure/azure-sdk-for-python/issues/9310

Thanks

**Comment by kashifkhan** [comment]
Hi @Blabll  thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by navba-MSFT** [comment]
@Blabll Apologies for the late reply. We are looking into this. issue. We will provide an update on this once we have more details on this.

**Comment by navba-MSFT** [comment]
@paterasMSFT Could you please share the timeline for the azure-batch package to be compatible with azure-identity ? Awaiting your reply.

**Comment by paterasMSFT** [comment]
We do not have an exact timeline, but this is something that we are actively working on for a release later this year.

**Comment by tomkp75** [comment]
@paterasMSFT I see you closed the ticket. Does it mean that this issue is supposed to be fixed? I'm still facing it.

**Comment by martinitus** [comment]
Same issue here, any update on this?

**Comment by endeesa** [comment]
I can confirm that this issue still exists in 2023 still. msrest==0.7.1, azure-batch==13.0.0 azure-identity==1.12.0
Why is the issue closed if the fix is not working. Is everyone all of a sudden working on Bing now??

**Comment by BC89** [comment]
Please address this issue. All of MS seems to be moving in this direction.
