### ISSUE TITLE
Automation Runbook Type Enumeration missing options for Python and Python3

### ISSUE THREAD

**Issue by wjg659** [Azure/azure-sdk-for-python#23585]
**Is your feature request related to a problem? Please describe.**
I would like to create a Python3 Azure Automation Runbook through terraform.  Since I believe this is the SDK that backs the API I would like to request an enhancement to azure-mgmt-automation that is required before Terraform can accept Python or Python3 as Runbook types.

**Describe the solution you'd like**
I would like the class [RunbookTypeEnum(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum))](https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/_automation_client_enums.py#L227) to include Python and Python 3 in the enumeration, then have the [swagger enum in the Rest API](https://github.com/Azure/azure-rest-api-specs/blob/782bab9c34014092f48de95874a71e7ecd1a9bba/specification/automation/resource-manager/Microsoft.Automation/stable/2019-06-01/runbook.json#L1154) updated to reflect the new types.  This would allow the Terraform provider team to add the options for these types to their resource in the azurerm provider.

**Describe alternatives you've considered**
If I cannot terraform something it does not exist.  Until this option can be found in the Terraform provider I am stuck using PowerShell in Azure Automation.

**Additional context**
This feature is required to fix [this issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/1602).

**Comment by kashifkhan** [comment]
Hi @wjg659  thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by kazrael2119** [comment]
Hi, @wjg659 Thanks for your feedback.I have understood your issue, but SDK is generated by swagger.If swaager does not have this parameter, the SDK will not have this parameter。

So you can submit your new issue to https://github.com/Azure/azure-rest-api-specs/issues

**Comment by wjg659** [comment]
Thank you.  I have opened [this issue](https://github.com/Azure/azure-rest-api-specs/issues/18472) in the azure rest API specs repo to have the swagger modified.
