### ISSUE TITLE
Azure Tables May release

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#23596]
Issues tracking multi-tenant authentication support:

- [ ] https://github.com/Azure/azure-sdk-for-python/issues/23613
- [ ] https://github.com/Azure/azure-sdk-for-python/issues/23617

**Comment by YalinLi0312** [comment]
Multi-tenant authentication-supporting is already done in [Tables May release](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/CHANGELOG.md#features-added-1), but not using the support from azure-core. We can close this task, then track the work by the two issues linked above. Or change the name to another milestone as the two issues are still open(but IDK what's the plan for the two issues now). 
@lmazuel What do u think?

**Comment by lmazuel** [comment]
This issue is closeable indeed, I'd like to keep the issue to leverage Azure Core in backlog for now
