### ISSUE TITLE
Add support for cloud service extensions

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-sdk-for-python#236]
Not to be confused with resource extensions, which are used by vms.

List Available Extensions
http://msdn.microsoft.com/en-us/library/azure/dn169559.aspx

Add Extension
http://msdn.microsoft.com/en-us/library/azure/dn169558.aspx

Delete Extension
http://msdn.microsoft.com/en-us/library/azure/dn169560.aspx

Get Extension
http://msdn.microsoft.com/en-us/library/azure/dn169557.aspx

List Extensions
http://msdn.microsoft.com/en-us/library/azure/dn169561.aspx

**Comment by lmazuel** [comment]
It seems that it does not exist anymore in ARM API. We do not plan to add new features in ASM legacy library. However, feel free to submit a PR if needed.
