### ISSUE TITLE
reverse parameter on walk_blobs for container clients

### ISSUE THREAD

**Issue by AWendland-CryptoCompare** [Azure/azure-sdk-for-python#23622]
**Is your feature request related to a problem? Please describe.**
We save the name of our files in chronological order, so with the container client it is easy to use walk blobs to get the first entry. However it is not easy to use it to get the last entry.

**Describe the solution you'd like**
An optional parameter for the ContainerClients walk_blobs (and list_blobs) functions of reverse, which inverts the order the names of the blobs are being returned. 

**Describe alternatives you've considered**
Right now we we use the forward direction are record the last blob returned from the generator.

**Comment by kashifkhan** [comment]
Hi @AWendland-CryptoCompare, thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by kashifkhan** [comment]
Hi @AWendland-CryptoCompare , thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by vincenttran-msft** [comment]
Hi @AWendland-CryptoCompare Alex, thanks for your inquiry and we will see what we can do about this. Unfortunately, a feature request like this requires support from the Service team, and so while we can put in the request, it is very unlikely that it will be triaged any time soon as there are several other higher priority items on their docket. 

In the meantime, here is a suggestion that may help improve your experience given the current implementation:
The `walk_blobs` and `list_blobs` APIs both accept an optional parameter `name_starts_with`, whose docstring is the following:
```
:param str name_starts_with:
            Filters the results to return only blobs whose names
            begin with the specified prefix.
```
With that being said, depending on how much information is known about the structure of your file names (and the consistency of the naming scheme), it may be possible to cut down on the query size by leveraging this optional parameter.

For example, if your files were in a format such as:
file1
file2
file3
.....
file229
file230
file231
....
file500

If you were aware that the value is going to be in a certain range (i.e. file23X, where X is the variable value that you don't know), then you could provide the str 'file23' as your `name_starts_with` param, which would drastically cut the query size down, and then you could probe the last blob from the generator as you are doing currently.

Hopefully this suggestion may help improve your experience, but please let us know if there is anything else we can do in the mean time!
Thanks!

**Comment by vincenttran-msft** [comment]
Hi @AWendland-CryptoCompare Alex, just wanted to check in to see if this was a suitable resolution for your use-case? If so, we can follow through with the closure of the issue, but if you do have any doubts please go ahead and raise them in a separate comment and we can see what we can do to further assist you.
Thanks!
