### ISSUE TITLE
Example text is incorrect (Copy/paste error)

### ISSUE THREAD

**Issue by 0xUnicorn** [Azure/azure-sdk-for-python#23621]
Below `create_table_if_not_exists` it has an `Example` with the text `Deleting a table from the TableServiceClient object` which is also the text used below for `delete_table`.

The fix would be to change the text to: `Creating a table if it doesn't exist, from the TableServiceClient object`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4deb2d00-2362-4ee8-661e-fd93821ce4dc
* Version Independent ID: 473126fd-d011-e731-7f7e-f41cd3aed15b
* Content: [azure.data.tables.TableServiceClient class](https://docs.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables.tableserviceclient?view=azure-python#azure-data-tables-tableserviceclient-create-table-if-not-exists)
* Content Source: [docs-ref-autogen/azure-data-tables/azure.data.tables.TableServiceClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-data-tables/azure.data.tables.TableServiceClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kashifkhan** [comment]
Hi @0xUnicorn , thanks for the feedback. We'll take a look at this and get back to you asap.
