### ISSUE TITLE
Patch API Support in Cosmos Python SDK

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-python#23656]
Patch API Support in Cosmos Python SDK

**Comment by angusrw** [comment]
Any update on this?

**Comment by clrogers2** [comment]
Same request as #22033. Currently has no planned timeline for implementation, which is a shame.

**Comment by kushagraThapar** [comment]
@angusrw / @clrogers2 - this is currently planned in the ongoing semester, and is scheduled to be done by March 2023.

**Comment by simorenoh** [comment]
Including https://github.com/Azure/azure-sdk-for-python/issues/21722 here as well since it's the same request.

**Comment by simorenoh** [comment]
Version 4.4.0b1 is out and addresses this, thank you! https://pypi.org/project/azure-cosmos/4.4.0b1/
