### ISSUE TITLE
AAD support in Cosmos Python SDK

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-python#23655]
AAD support in Cosmos Python SDK

**Comment by simorenoh** [comment]
Sync: https://github.com/Azure/azure-sdk-for-python/pull/23604

**Comment by simorenoh** [comment]
Async: https://github.com/Azure/azure-sdk-for-python/pull/23717

**Comment by simorenoh** [comment]
Both PR's are getting merged and released this week, closing issue.
