### ISSUE TITLE
catalog_client.entity.list_by_guids

### ISSUE THREAD

**Issue by gyanisinha** [Azure/azure-sdk-for-python#23665]
- **Package Name**:  azure-purview-catalog
- **Package Version**: 1.0.0b2
- **Operating System**: Windows 11 Enterprise 21H2
- **Python Version**: azure-purview-catalog

**Describe the bug**
**The entity.list_by_guids method is not working and from the documentation it is not clear how to pass the list of guids as list str:**

```
catalog_client = PurviewCatalogClient(endpoint=catalog_endpoint, credential=credential)
guids=["4e5916a4-c14c-48ee-aa66-76cb4a5d0d0a","4e5916a4-c14c-48ee-aa66-76cb4a5d0d0a"]
response =  catalog_client.entity.list_by_guids(guids)
```

Throws below error:
Traceback (most recent call last):
  File "c:\Users\gyanisinha\OneDrive - Microsoft\Documents\GitHub\purview-bcdr\purview-bcdr-backup.py", line 181, in <module>
    response =  catalog_client.entity.list_by_guids(guids)
  File "C:\Users\gyanisinha\AppData\Roaming\Python\Python37\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
**TypeError: list_by_guids() takes 1 positional argument but 2 were given**

**To Reproduce**
```
from azure.identity import ClientSecretCredential
from azure.purview.catalog import PurviewCatalogClient

#credential
credential = ClientSecretCredential(
                tenant_id = tenant_id, 
                client_id = client_id, 
                client_secret = client_secret)

catalog_endpoint = "https://" + pv_account + ".purview.azure.com"

catalog_client = PurviewCatalogClient(endpoint=catalog_endpoint, credential=credential)
guids=["4e5916a4-c14c-48ee-aa66-76cb4a5d0d0a","4e5916a4-c14c-48ee-aa66-76cb4a5d0d0a"]
response =  catalog_client.entity.list_by_guids(guids)
```

**Expected behavior**
The method call should return the details of the entities for the provided guids

**Screenshots**
The result from base API:
![image](https://user-images.githubusercontent.com/87772005/160050689-0c71c851-01be-4c76-822c-e71b4698c7ef.png)

**Additional context**
Please provide the syntax of how to pass list of guids with an example. The documentation does not provide a clear answer:
![image](https://user-images.githubusercontent.com/87772005/160050824-3a4191fc-fadd-4f34-b792-e900aab6c905.png)

Also tried passing the guids with "guid=" prefixed t each values

**Comment by SaurabhSharma-MSFT** [comment]
@gyanisinha We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@gyanisinha You need to use the parameter name like below to get it work - 
`response =  catalog_client.entity.list_by_guids(guids=guids)`

**Comment by SaurabhSharma-MSFT** [comment]
@gyanisinha Please let me know if you have any questions else we will proceed with the closure of this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@gyanisinha We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by gyanisinha** [comment]
thanks @SaurabhSharma-MSFT
