### ISSUE TITLE
Using a client assertion JWT as credentials for BlobServiceClient

### ISSUE THREAD

**Issue by pfsalminen** [Azure/azure-sdk-for-python#23678]
I am looking for a way to supply a client assertion JWT as credentials for a BlobServiceClient object. I am able to receive an access token with the msal library, but cannot find a way to use that token after I receive it. Is there a high level api I can use for this workflow?

**Comment by kashifkhan** [comment]
Hi @pfsalminen, thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @pfsalminen Paul, I assume you mean an OAuth token generated for the Storage service? Something you would normally pass in a `Authorization` header in the form `Authorization: Bearer <token>`?

This token would need to be generated with the audience: `https://storage.azure.com/.default`

If this is the case, I don't believe this is officially supported as we expect the usage of the `TokenCredentials` class from `azure.identity` where the token will be fetched automatically. Is it possible for you to use this in your application?

**Comment by pfsalminen** [comment]
@jalauzon-msft Thanks for getting back to me.I was able to create my own Credential class inheriting from `GetTokenMixin`. I figured it wasn't officially supported, but wanted to see if there was a better solution. Thanks!
