### ISSUE TITLE
[pylint] storage SDK pylint warnings

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#23679]
When the core pipeline was run with the new custom pylint plugins, the following issues were found:
(see OneNote pylint checker for issue fix)

**REMOVE WHEN ISSUE IS FIXED**
-[ # pylint: disable=enum-must-inherit-case-insensitive-enum-meta]
-[ # pylint: disable=enum-must-be-uppercase]
-[ # pylint: disable=client-accepts-api-version-keyword]

BLOB:

- [x]  [Azure Blobs Models need to inherit CaseInsensitiveEnumMeta, and enums must be uppercase](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py)
- [x] [Azure Blob Lease Client needs optional keyword api_version argument](https://github.com/Azure/azure-sdk-for-python/blob/7907b242fb60783213465fabfd0245c126b4851b/sdk/storage/azure-storage-blob/azure/storage/blob/_lease.py#L26) used pylint: disable here
- [x] [Azure Storage Blob _shared models needs to inherit enum metaclass and have uppercase enums](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/models.py)

BLOB CHANGEFEED:
- [x] [Azure Blob Changefeed Client needs api_version keyword ](https://github.com/Azure/azure-sdk-for-python/blob/7907b242fb60783213465fabfd0245c126b4851b/sdk/storage/azure-storage-blob-changefeed/azure/storage/blob/changefeed/_change_feed_client.py#L20)

DATALAKE:
- [x] [Azure FileDataLake Data Lake Directory Client needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py)
- [x] [Azure FileDataLake _models enum classes need to inherit from metaclass and enums must be uppercase](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py)
- [x] [data lake service client needs api version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_service_client.py)
- [x] [data lake path client needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py)
- [x] [data lake file client needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py)
- [x] [data lake file system client needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py)
- [x] [data lake lease client needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_lease.py) used pylint: disable here
- [x] [data lake lease async needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_lease_async.py) used pylint: disable here
- [x] [data lake directory client async needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py)
- [x] [file system client async needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py)
- [x] [data lake service client async needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_service_client_async.py)
- [x] [data lake path client async needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_path_client_async.py)
- [x] [data lake file client async needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py)
- [x] [datalake _shared models enum class must inherit metaclass, and enums must be capitalized](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/models.py)

FILESHARE
- [x] [fileshare _models enum class needs to inherit from metaclass and enum must be uppercase](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py)
- [x] [fileshare _lease client needs api_version keyword](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_lease.py) used pylint: disable here
- [x] [fileshare _shared models enum class needs to inherit from metaclass and enum must be uppercase](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/models.py)

QUEUE:

- [x] [queue _shared models enum class needs to inherit from metaclass and enum must be uppercase](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-queue/azure/storage/queue/_shared/models.py)

**Comment by vincenttran-msft** [comment]
Hi @l0lawrence, I had trouble finding you on Teams to ping, but I just wanted to give you a heads up that I have a PR out to fix these warnings. If you could take a look when you have a chance, that would be great! I am still quite new to the team, so I may have misjudged in some areas and used `disable=client-accepts-api-version-keyword` when I should have just added the keyword `api-version`, so please let me know in the PR feedback if there is any errors! 

Thanks!
