### ISSUE TITLE
Collaborate on solution for validate_authority with MSAL team

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#23684]
Tracking issue for collaborating with the MSAL team to expose consistent capabilities / APIs such that Azure Identity SDK can then expose a simple and easy to use API for enabling the use of custom domains.

Related Issues: 
- expose "validate_authority" so user can explicitly disable the validation if they want to use custom domain. https://github.com/Azure/azure-sdk-for-python/pull/22786/
- [ClientSecretCredential.get_token() fails in case of azurestack if we provide 'authority' URL · Issue #22625 · Azure/azure-sdk-for-python (github.com)
](https://github.com/Azure/azure-sdk-for-python/issues/22625)

**MSAL Tracking Issues:**
  - Python: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/466
  - JS: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4625
  - Java: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/481
  - .NET: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3242
  - Golang: https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/301

**Comment by xiangyan99** [comment]
Done.
