### ISSUE TITLE
Release stable version of azure-eventgrid library

### ISSUE THREAD

**Issue by kirthik** [Azure/azure-sdk-for-python#2369]
Please release stable version of azure-eventgrid library and update samples to use stable versions of the library.

This must be completed before //build.

**Comment by annatisch** [comment]
Thanks @kirthik,
Is the code in master ready to be released as-is, or is this release waiting on a PR merge/swagger update?
Additionally, has the version been bumped and HISTORY.rst updated?

Thanks!

**Comment by kirthik** [comment]
@annatisch  - this is release ready. Can you also release stable version of event grid management library too besides azure-eventgrid?

**Comment by lmazuel** [comment]
Done
https://pypi.org/project/azure-eventgrid/1.0.0/
https://pypi.org/project/azure-mgmt-eventgrid/1.0.0/
