### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.storage'; 'azure' is not a package (Python 3.9.8)

### ISSUE THREAD

**Issue by zeki07k** [Azure/azure-sdk-for-python#23704]
- **azure-storage-blob**: 
- **azure-storage-blob==12.10.0**: 
- **Windows 10**:
- **Python 3.9.8**: 

**Describe the bug**
Traceback (most recent call last):
  File "C:\Users\MONSTER\Desktop\even_recognition_module\azure.py", line 3, in <module>
    from azure.storage.blob import BlobClient
  File "C:\Users\MONSTER\Desktop\even_recognition_module\azure.py", line 3, in <module>
    from azure.storage.blob import BlobClient
ModuleNotFoundError: No module named 'azure.storage'; 'azure' is not a package

**To Reproduce**
1.
 from azure.storage.blob import BlobClient
connection_string = 'connection string'

blob = BlobClient.from_connection_string(conn_str=connection_string, container_name="trainstorage", blob_name="blob.pb")

blob.upload_blob('./blob.pb')

**Expected behavior**
This Python Code doesn't run properly with python 3.9.8.
However, it works in Python 3.6. 
At that time, my project code is not compitable for Python 3.6.
My project is Python 3.9.8
So, I cant run it.

**Comment by kristapratico** [comment]
Hi @zeki07k thanks for your issue. Since it looks you have multiple versions of Python on your machine, would you mind doing a quick check of your environment as described here: https://github.com/Azure/azure-sdk-for-python/issues/19659#issuecomment-893816623 ?

**Comment by kristapratico** [comment]
@zeki07k looking at this a second time and see that your file is named azure.py - this is conflicting with `azure` itself. Can you try renaming the file and see if that resolves your issue?

**Comment by zeki07k** [comment]
> @zeki07k looking at this a second time and see that your file is named azure.py - this is conflicting with `azure` itself. Can you try renaming the file and see if that resolves your issue?

Thanks. it worked.
