### ISSUE TITLE
DataFactoryManagementClient subscription id

### ISSUE THREAD

**Issue by romanzdk** [Azure/azure-sdk-for-python#23706]
Would it be possible to change required parameter `subscription_id` for `DataFactoryManagementClient` to `subscription_name` ? In all of the Azure CLI tasks we are using subscription name, but only for this one specific case we need to put subscription id into keyvault. Giving the fact CLI does not required subscription ID I guess (and hope) it could be possible for SDK as well.

**Comment by kristapratico** [comment]
Hi @romanzdk thanks for your issue. Would you mind clarifying which package this feedback is for? Is this for `azure-mgmt-datafactory`? Also could you share which version of the package you are using?

**Comment by romanzdk** [comment]
@kristapratico Azure.Mgmt.Resource, v20.1.0

**Comment by SaurabhSharma-MSFT** [comment]
@romanzdk Thanks for your feedback.  This looks like by design, so redirecting this to services team as a feature request.

**Comment by Frey-Wang** [comment]
Hi @romanzdk , subscription name and subscription id are different. The SDK need subscription id to make valid call to backend instead of subscription name. This is by design. Thanks!
