### ISSUE TITLE
ImportError: No module named common.credentials

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-sdk-for-python#2372]
# install virtualenv
pip install virtualenv
#
virtualenv  test
# 
source test/bin/activate
#

git clone git://github.com/Azure/azure-sdk-for-python.git

cd azure-sdk-for-python/
# 
python setup.py  install

#test
python
from azure.common.credentials import ServicePrincipalCredentials

issues:
 No module named common.credentials

----------------------------
OS：Centos 7.0
Python: 2.7.5

**Comment by lmazuel** [comment]
Hello,
I just fixed a bug in master, could you give it a retry?
Thanks,

PS: Why aren't you using pip?

**Comment by taroyutao** [comment]
Thanks, it works now.
