### ISSUE TITLE
CLU - March SDK - Resolution casting/polymorphism

### ISSUE THREAD

**Issue by mshaban-msft** [Azure/azure-sdk-for-python#23754]
- **Package Name**:  ConversationAnalysisClient (azure.ai.language.conversations)
- **Package Version**: 1.0.0b3

**Describe the bug**
CLU March APIs introduced the concept of `resolutions` with each entity.
There are many types of resolutions which share the same `BaseResolution` class that uses `resolution_kind` property to cast this `BaseResolution` into one of these other sub-types like: `AgeResolution`, or `DateTimeResolution`.
The problem is that even though every subtype defines this `resolution_kind` property with each's own value, python couldn't type cast this base class into corresponding sub type.

**To Reproduce**
1. simply run the `sample_analyze_conversation_app.py` in the samples dir (using your own resource).
2. debug the code at line 87 to catch any of entity resolutions.

**Expected behavior**
Resolution should be any of the subtypes (not BaseResolution).

**Comment by kristapratico** [comment]
closing this since we don't have models generated in CLU.
