### ISSUE TITLE
Generated Python 3 modules has syntax errors, causing a fall back to Python 2 modules

### ISSUE THREAD

**Issue by TimSimpsonR** [Azure/azure-sdk-for-python#2375]
I'm assuming recent changes have made the code generator output two versions of the code, one for Python 2 and another for Python 3.

However, the Python 3 generated code contains a recurring pattern where a parent class's __init__ method is called with a malformed parameter list starting with a comma (`__init__(, arg1, arg2, etc)`, causing a syntax error. Here are some examples:

https://github.com/Azure/azure-sdk-for-python/blob/72d71b30af36e65b333e2225ce8732afa53a4ec4/azure-mgmt-monitor/azure/mgmt/monitor/models/rule_email_action_py3.py#L43

https://github.com/Azure/azure-sdk-for-python/blob/72d71b30af36e65b333e2225ce8732afa53a4ec4/azure-mgmt-monitor/azure/mgmt/monitor/models/rule_webhook_action_py3.py#L42

https://github.com/Azure/azure-sdk-for-python/blob/72d71b30af36e65b333e2225ce8732afa53a4ec4/azure-mgmt-monitor/azure/mgmt/monitor/models/diagnostic_settings_category_resource_py3.py#L46

The `__init__` module of `azure.mgmt.monitor.models` uses a massive try/except block to import all the `_py3` modules, and if a SyntaxError or ImportError is caught it imports the Python 2 modules instead.

I'm not privy to how the code generator works and may be missing something, but IMO a cleaner way to test the version of Python IMO would be to use an if statement like `import sys; if sys.version[0] >= '3':` instead of the try / except. That way automated testing could ensure that no import errors or syntax errors occur at all.

On a different note it's a pleasant surprise to see a major cloud provider supporting Python 3 type annotations in its SDK. :)

**Comment by lmazuel** [comment]
Hi @TimSimpsonR 
I noticed that this morning as well :(. I'm on it, this has to be fixed asap.

PS: I wanted annotations for a while :). And async/await is coming ;)

**Comment by lmazuel** [comment]
Fix in progress:
https://github.com/Azure/autorest.python/pull/54

**Comment by lmazuel** [comment]
Released on PyPI, thanks for the report!
