### ISSUE TITLE
Generic Exception For Using SDK in Azure Pipeline

### ISSUE THREAD

**Issue by anotherancientalien** [Azure/azure-sdk-for-python#23762]
Hi,

Exceptions in rest api requests are easy. We can use the response.status_code for creating the desired logic.
But in SDK, there isn't any clear results. Consider this code that I used in Pipeline task:

```
result = network_client.network_interfaces.begin_create_or_update(
        rg_name,
        nic_name,
        parameters=params).result() 
```

When I use the exception like except `AzureHttpError as error `the output is ` Code: ResourceNotFound`. That I'm not sure how can be used for custom condition in task because is not generic.

Is there any right way to handling error for custom condition?

Best
Jasmine

**Comment by kristapratico** [comment]
Hi @anotherancientalien thanks for your issue, we'll take a look. A few quick questions to assist in our investigation - is this for `azure-mgmt-network`? And can you share which version of the package you are using?

**Comment by anotherancientalien** [comment]
Hi @kristapratico , 

Thanks for your reply. I use `azure.mgmt.network` and other mgmt libraries for vm provisioning.

Best

**Comment by anotherancientalien** [comment]
@kristapratico Krista! You are an angel! `AzureHttpError` didn't response the status_code but `HttpResponseError` working like charm! Thank you!
