### ISSUE TITLE
ResourceWarning: unclosed <ssl.SSLSocket fd=324, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM

### ISSUE THREAD

**Issue by eabase** [Azure/azure-sdk-for-python#23794]
- **Package Name/Version**: 
```
azure-core          1.23.1
azure-cosmos        4.2.0
```

- **Operating System**: `Win 10 Pro`
- **Python Version**:  `3.10.3`

**Describe the bug**
Getting SSL error from demo/example code, pointing to ssl.py:
```python
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=424, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('xxxx', 29156), raddr=('yyyy', 443)>
Object allocated at (most recent call last):
  File "C:\python310\lib\ssl.py", lineno 1033
    self = cls.__new__(cls, **kwargs)
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=412, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('xxxx', 29157), raddr=('yyyy', 443)>
Object allocated at (most recent call last):
  File "C:\python310\lib\ssl.py", lineno 1033
    self = cls.__new__(cls, **kwargs)
```

**To Reproduce**

```python
    client = CosmosClient(url, credential=key) 
    database  = client.get_database_client(database_name)
    container = database.get_container_client(container_name)
```

**Expected behavior**
No SSL close connection error. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by kristapratico** [comment]
Hi @eabase thanks for the feedback, @simorenoh can you take a look?

**Comment by eabase** [comment]
PS. As was mentioned in another issue thread. 
To ignore this message we can use:
```python
# ignore the relevant warnings through the warnings library
import warnings 
warnings.simplefilter("ignore", ResourceWarning)
```

**Comment by SatishBoddu-MSFT** [comment]
@eabase Thanks for reaching out on this issue, we are routing this to Service Teams' Attention for further action!

**Comment by simorenoh** [comment]
Hi @eabase, I have spent some time trying to re-create this behavior but have been unable to. Is this something that you're still seeing in your application?

For now, I would recommend updating to the new azure-cosmos 4.3.0 release that came out this week as well as updating any other old dependencies and seeing if anything changes.

**Comment by eabase** [comment]
@simorenoh 
Yes, I just updated to:
```
azure-core          1.24.1 
azure-cosmos        4.3.0  
```

And I still get the errors about unclosed sockets in `ssl.py`.

**Comment by simorenoh** [comment]
@eabase Yep, I have tried all things that I could think of in terms of setting up and replicating the environment you're using (Windows machine, Python 3.10.3, same package versions) but have been unable to run into this issue.

It would make sense, as you say, that the VPN is giving some sort of warning with the SSL library since that directly affects the connections made - I'd recommend you try using your current VPN setup along with other SDKs to see if the same behavior happens, since as far as I have seen this does not seem to be a Cosmos SDK issue.

**Comment by eabase** [comment]
@simorenoh 
So maybe this bug need to be reported to the `ssl.py` maintainers. 
* https://github.com/python/cpython/blob/3.10/Lib/ssl.py

**Comment by simorenoh** [comment]
@eabase That might be worthwhile - however, I see in the issue you created that you didn't add any information about the VPN you use and I believe that would be the most useful information for them to have as well. Please ensure you provide as much information as possible so whatever investigation or answer you're looking for is easier to find for the responsible team.

If there's any other questions you have with the Cosmos SDK itself, do feel free to ask them. Thank you for using our SDK, and hope your day is going well!
