### ISSUE TITLE
Sample code error:  AttributeError: 'dict' object has no attribute 'query_items'

### ISSUE THREAD

**Issue by eabase** [Azure/azure-sdk-for-python#23795]
- **Package Name/Version**: 
```
azure-core          1.23.1
azure-cosmos        4.2.0
```

- **Operating System**: `Win 10 Pro`
- **Python Version**:  `3.10.3`

**Describe the bug**

I get the following error from the sample code using `query_items`:

**`AttributeError: 'dict' object has no attribute 'query_items'`**

From:
```python
    client = CosmosClient(url, credential=key) #, logging_enable=True) 
    database  = client.get_database_client(database_name)
    container = database.get_container_client(container_name)

    for item in container.query_items(query=QSQL, enable_cross_partition_query=True):
        print(json.dumps(item, indent=True))
```

when using QSQL with:
```sql
SELECT list.id, list.name FROM c 
   JOIN configuration IN c.configuration 
   JOIN list IN configuration.list 
WHERE c.id = "documentTypes"'
```

The JSON DB I'm looking at, looks like this:
```json
{
    "id": "documentTypes",
    "SomeThing": "SomeThing",
    "configuration": [
        {
            "language": "en",
            "list": [
                {
                    "id": 1,
                    "name": "Supporting Documents"
                },
                {
                    "id": 2,
                    "name": "Summary PDF"
                },
            ]
        }
    ],
}
```

**To Reproduce**

I Have no general step that I can share & show in public.  

**Expected behavior**
That the example/demo code works without errors.

**Screenshots**
N/A
**Additional context**
N/A

**Comment by kristapratico** [comment]
Hi @eabase thanks for your issue. Can you share more of the sample snippet that reproduces this? For example, what is `container` in this example:


```
        for item in container.query_items(query=QSQL, enable_cross_partition_query=True):
            print(json.dumps(item, indent=True))
```

**Comment by eabase** [comment]
Hi @kristapratico , I just updated OP with requested info.

**Comment by eabase** [comment]
I see, now that there was some name spacing pollution. I had a previous statement with:

```python
    database = client.get_database_client(database_name)
    for container in database.list_containers():
        print("  Container ID:  {}".format(container['id']) )
```
... before the code in OP. 

I removed it, and no longer get this error. Closing issue. 
However, I still cannot get any result from that query...
