### ISSUE TITLE
Cosmos Count Query

### ISSUE THREAD

**Issue by sprakash1612** [Azure/azure-sdk-for-python#23799]
I was trying to get the count of records from a cosmos container but was unable to. Is there any way I can get the record count?

**Comment by l0lawrence** [comment]
Thanks for your question, routing it to the appropriate person!

**Comment by navba-MSFT** [comment]
@sprakash1612 Apologies for the late reply. Are you trying to get the record count of the document in Azure CosmosDB ? If Yes, there are multiple ways to achieve this requirement.  [This ](https://microsoft.github.io/AzureTipsAndTricks/blog/tip152.html#get-the-record-count-in-cosmos-db) article talks about how to accomplish it from Azure Portal and using C# sample. Please let me know if you are looking for the python sample specifically. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sprakash1612 Could you please confirm if it is for SQL API ?

**Comment by sprakash1612** [comment]
I tried using this method but I am getting error BadRequest

**Comment by navba-MSFT** [comment]
@sprakash1612 Could you please paste the complete error message here in this github thread ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sprakash1612 Could you please let me know if you had a chance to look at my [above comment](https://github.com/Azure/azure-sdk-for-python/issues/23799#issuecomment-1091676570) and try the suggested plan. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sprakash1612 Please let me know if you have any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sprakash1612 We hope you had a chance to follow the suggestion provided in the [above comment. ](https://github.com/Azure/azure-sdk-for-python/issues/23799#issuecomment-1091676570 )We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
