### ISSUE TITLE
Conversion to managed drives renames the drives

### ISSUE THREAD

**Issue by TihoElek** [Azure/azure-sdk-for-python#2380]
The errors started happening after the machines were converted from unmanaged to managed drives.
Example:
Message: The Resource 'Microsoft.Compute/disks/string000-OSDisk' under resource group 'xxxx' was not found.
Failed to create snapshot of: string000-OSDisk
Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Compute/disks/string000-LogDisk' under resource group 'xxxx' was not found.
Failed to create snapshot of: string000-LogDisk
Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Compute/disks/string000-DataDisk' under resource group 'xxxx' was not found.
Failed to create snapshot of: string000-DataDisk
Azure Error: ResourceNotFound

Both azure portal and python SDK show the disks named string000-DataDisk, string000-OSDisk, string000-LogDisk are attached to the machine string000. Disks are functional and we can see the data on our mountpoints.

However, when I rebuild the machine with the above disk names they appear empty. They only work as expected if left alone after the conversion.

I also noticed that the disks attached to some of the machines in this resource group after the conversion are named:
string001-OSDisk_random hex string
string001-LogDisk_random hex string
string001-DataDisk_random hex string
They were originally created as unmanaged without the hex string.

This makes me suspect that the disks attached to string000 have the hex string appended to them, but some APIs are not aware of it. There are no references to disk renaming or how the conversion is done under the hood in the documentation.

Disks are P30 and the errors seem reproducible only when there is a significant amount of data on them.
I was able to reproduce in multiple resource groups, but not on every run.

Is there another way to check for the "real" name of the disks attached to string000?

Thanks!

**Comment by annatisch** [comment]
Thanks @TihoElek - this seems like a service issue rather than an SDK issue.
@hyonholee - are you able to provide any insight into this behavior?

**Comment by lmazuel** [comment]
@yugangw-msft any idea?

**Comment by yugangw-msft** [comment]
Please share more detail of 2 activities you mentioned:
1. How did you `converted from unmanaged to managed drives.`
2. How did you `rebuild the machine with the above disk names `
Once i know the detail, I can provide more helo

**Comment by TihoElek** [comment]
Hi Yugang,

1.) We converted to managed drives using:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/operations/virtual_machines_operations.py#L590

2.) We "rebuilt" the machine using delete (
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/operations/virtual_machines_operations.py#L365
)
 and create_or_update (
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/operations/virtual_machines_operations.py#L267)
operations using the same configuration parameters (storage, network and
compute) as when we provisioned the unmanaged machine.

Please let me know if you need any more details.

Best,
Tihomir

**Comment by yugangw-msft** [comment]
In the rebuild step, to confirm, when you tried to rebuild the same VM with unmanaged disk, you got the error of `The Resource 'Microsoft.Compute/disks/string000-OSDisk' under resource group 'xxxx' was not found.`?

**Comment by TihoElek** [comment]
There were several scenarios:
1.) Snapshot operation failed with the The Resource
'Microsoft.Compute/disks/string000-OSDisk' error after the conversion to
managed without any rebuilds.
2.) When we rebuild machines we try to attach the existing disks with
predefined names and if they don't exist then they are added as empty
disks. On a rebuild after the conversion the disks we are sure were there
got attached as empty.
3.) When we list storage some disks after the conversion, the disks on some
machines are renamed.

**Comment by yugangw-msft** [comment]
Let us handle one after one, for 1), can you share with me the code you wrote for capturing a snapshot from an existing disk?
If the code volume is big, you can send me to yugangw at microsoft dot com. My initial take is the request payload is not right, particularly the resource id for the source disk.

**Comment by TihoElek** [comment]
It is important to note that this code always works on resource groups
created as managed. It also works on some of our converted resource groups
without any problems and it works on all but several machines in this
resource group.
I agree that managed_disk.id could be wrong, but probably because it was
created differently on conversion, unlikely that we payload it incorrectly.

    def snapshot_disk(self, cluster, machine, disk_name, snap_time):
        snapshot_name ="example"
        try:
           # get the disk by name
            managed_disk = self.cmc.disks.get(cluster, disk_name)
            async_snapshot_creation = self.cmc.snapshots.create_or_update(
                resource_group_name=cluster,
                snapshot_name=snapshot_name,
                snapshot=Snapshot(
                    location="example"
                    creation_data=compute.models.CreationData(
                        create_option='Copy',
                        source_uri=managed_disk.id
                    )
                )
            )
            snapshot = async_snapshot_creation.result()
            if snapshot.name:
                print("Created snapshot of: {}".format(disk_name))
            else:
                print("Failed to create snapshot of: {}".format(disk_name))
                return Failed
            return snapshot
        except Exception as e:
            print(e)
            print("Failed to create snapshot of: {}".format(disk_name))
            return "Failed"

I think the problem is that during the conversion disk name gets a hex
string appended to it in some cases which causes the get request to not
find it. But both portal and python SDK seem to think the name is not
modified on some nodes. On the others hex string is visible.
Just for reference again:
https://github.com/Azure/azure-sdk-for-python/issues/2380

**Comment by yugangw-msft** [comment]
Please change your code to use  `source_resource_id`, instead of `source_blob_uri` which is used to capture snapshot from unmanaged disk blob
```python
creation_data=compute.models.CreationData(
                        create_option='Copy',
                        source_resource_id=managed_disk.id
                    )
```
If it helps, you can cross check  CLI's [code logics](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py#L380-L383)

**Comment by TihoElek** [comment]
According to:
https://github.com/Azure/azure-sdk-for-python/wiki/Managed-Disk

Create a snapshot of a Managed Disk that is currently attached to a Virtual
Machine.

        managed_disk = compute_client.disks.get('my_resource_group', 'myDisk')
        async_snapshot_creation =
self.compute_client.snapshots.create_or_update(
                'my_resource_group',
                'mySnapshot',
                {
                    'location': 'westus',
                    'creation_data': {
                        'create_option': 'Copy',
                        'source_uri': managed_disk.id
                    }
                }
            )
        snapshot = async_snapshot_creation.result()

If source_uri was the issue, wouldn't it then fail on all snapshots of
disks created this way? It works on other disks attached to the machines in
this resource group.

**Comment by yugangw-msft** [comment]
> It works on other disks attached to the machines in this resource group.

I don't think `source_uri=managed_disk.id` would work for other scenarios, as the `source_uri` is meant for unmanaged blob uri; but feel free to share the code that works and I will cross check.

**Comment by TihoElek** [comment]
Thanks for quick responses :)

The code I shared above works for 12 machines in the same resource group.
It snapshot their disks correctly. The same code fails for 3 machines in
the same resource groups. There is nothing different between machines. They
were all created as unmanaged and converted to managed using the same
method.

        I don't think source_uri=managed_disk.id would work for other
scenarios
Other scenarios being 2 and 3 listed above? But according to the document I
sent it should work for scenario 1. The code we use is different for other
scenarios, but let's try to get to the bottom of this one first. I believe
the underlying issue is the same for all 3 scenarios.

**Comment by yugangw-msft** [comment]
Okay, for working case, can you share out the http trace with request & response payload? I believe you can get it by turning on debug/verbose logging?

**Comment by TihoElek** [comment]
We can only backup at certain times since it's a production environment.
Are there any server side logs that support could access?
You were mentioned on another thread with support. I think they should have
access to our subscription. Can you please respond there?

Thanks,
Tiho

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
