### ISSUE TITLE
Typo in API documentation of python RepositoryProperties Class

### ISSUE THREAD

**Issue by mpw96** [Azure/azure-sdk-for-python#23815]
Hi, [here](https://docs.microsoft.com/en-us/python/api/azure-containerregistry/azure.containerregistry.repositoryproperties?view=azure-python#azure-containerregistry-repositoryproperties-last-udpated-on) is a typo. It should be `last_updated_on` instead of `last_udpated_on`.

![Screenshot 2022-04-05 at 11 39 12](https://user-images.githubusercontent.com/12065222/161726518-ff8b9e99-b8a0-415d-a678-e8e598a614e1.png)

Regards
MP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd17369e-1362-a8ad-4622-fcbf187816be
* Version Independent ID: 4115207b-14ed-d126-5726-66e115f94de2
* Content: [azure.containerregistry.RepositoryProperties class](https://docs.microsoft.com/en-us/python/api/azure-containerregistry/azure.containerregistry.repositoryproperties?view=azure-python)
* Content Source: [docs-ref-autogen/azure-containerregistry/azure.containerregistry.RepositoryProperties.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-containerregistry/azure.containerregistry.RepositoryProperties.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by lmazuel** [comment]
Hi @mpw96 
This was actually a typo in the code itself, that we fixed with some black magic of Python playing with `__getattr__`. The next update should have the fix:
https://github.com/Azure/azure-sdk-for-python/pull/23562

Closing this issue as ACR is planned for release this Tuesday
cc @YalinLi0312
