### ISSUE TITLE
[mgmt] Fix duplicated query parameters in request

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#23828]
related issue: https://github.com/Azure/azure-sdk-for-python/issues/23561.
fix feature: https://github.com/Azure/autorest.python/blob/autorestv3/ChangeLog.md#2022-03-03---5130

we need:
(1) upgrade autorest.python to 5.13.0+
(2) add `reformat-next-link: false` in readme.python.md for service which has similar problems

candidate services:
resources, consumption, advisor

**Comment by BigCat20196** [comment]
related issue: https://github.com/Azure/azure-sdk-for-python/issues/22823, https://github.com/Azure/azure-sdk-for-python/issues/21932, https://github.com/Azure/azure-sdk-for-python/issues/23175

**Comment by BigCat20196** [comment]
resources: https://github.com/Azure/azure-rest-api-specs/pull/18591
