### ISSUE TITLE
Problem authenticating to USGOV cloud at subscription scope

### ISSUE THREAD

**Issue by ss8913** [Azure/azure-sdk-for-python#23826]
This is something that used to work with the older APIs, and now does not.  I've been trying for a solid day to get this to work, and i'm told that this is the forum to report issues.  So, basically I'm trying to get a list of subscriptions, or really do anything at the subscription scope; any function that takes a subscription ID will say 'cannot find subscription', and the subscription list comes back empty.

I'm using CLI credentials, and `az account list` shows that I have access to the subscriptions that I intend.  Also of note is that this exact code works fine in the regular cloud using my normal non-usgov account.

`#!/usr/bin/env python3

import logging
from azure.identity import AzureCliCredential
from azure.mgmt.subscription import SubscriptionClient

credential = AzureCliCredential()
client = SubscriptionClient(credential=credential, logging_enable=True)
logging.basicConfig(filename='test_sub_debug.log', level=logging.DEBUG)
aba_logger = logging.getLogger('azure.mgmt.subscription')
aba_logger.setLevel(logging.DEBUG)
sub_list = client.subscriptions.list()
for subscription in sub_list:
    print(subscription)`

So, that should show me a list of subscriptions, yet it does not.  Interestingly if I look in 'test_sub_debug.log', created by the above code, it shows that it's attempting to contact management.azure.com, not management.usgovcloudapi.net - I was expecting the AzureCliCredential to do that (the old get_client_from_cli_profile(<class>) in the old API, seemed to have no issues with this).

If I add a `base_url='https://management.usgovcloudapi.net/'` to the client constructor, I get this error instead of a blank list:

`azure.core.exceptions.ClientAuthenticationError: (InvalidAuthenticationTokenAudience) The access token has been obtained for wrong audience or resource 'https://management.azure.com'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.
Code: InvalidAuthenticationTokenAudience
Message: The access token has been obtained for wrong audience or resource 'https://management.azure.com'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.`

Please help, and thanks in advance :)

**Comment by PramodValavala-MSFT** [comment]
@ss8913 You would have to set the `credential_scopes` as well when working with sovereign clouds. Refer the [official doc](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-sovereign-domain#using-pre-defined-sovereign-cloud-constants) for a full sample.

Here is the same for reference

```py
import os
from msrestazure.azure_cloud import AZURE_CHINA_CLOUD as CLOUD
from azure.mgmt.resource import ResourceManagementClient, SubscriptionClient
from azure.identity import DefaultAzureCredential

# Assumes the subscription ID and tenant ID to use are in the AZURE_SUBSCRIPTION_ID and
# AZURE_TENANT_ID environment variables
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
tenant_id = os.environ["AZURE_TENANT_ID"]

# When using sovereign domains (that is, any cloud other than AZURE_PUBLIC_CLOUD),
# you must use an authority with DefaultAzureCredential.
credential = DefaultAzureCredential(authority=CLOUD.endpoints.active_directory, tenant_id=tenant_id)

resource_client = ResourceManagementClient(
    credential, subscription_id,
    base_url=CLOUD.endpoints.resource_manager,
    credential_scopes=[CLOUD.endpoints.resource_manager + "/.default"])

subscription_client = SubscriptionClient(
    credential,
    base_url=CLOUD.endpoints.resource_manager,
    credential_scopes=[CLOUD.endpoints.resource_manager + "/.default"])
```
