### ISSUE TITLE
ImportError: cannot import name 'confidentialLedgerClient'

### ISSUE THREAD

**Issue by wtam** [Azure/azure-sdk-for-python#23832]
- **Package Name**: azure-confidentialledger
- **Package Version**: 1.0.0b1
- **Operating System**: Bash/Ubuntu18.04
- **Python Version**: 3.6.9

**Describe the bug**
from azure.confidentialledger import confidentialLedgerClient => ImportError: cannot import name 'confidentialLedgerClient'

**To Reproduce**
1. pip3 install azure-identity azure-confidentialledger
2. from azure.confidentialledger import confidentialLedgerClient 

**Expected behavior**
'confidentialLedgerClient' should be found in the azure.confidentialledger pkg

**Screenshots**

**Additional context**

**Comment by SaurabhSharma-MSFT** [comment]
@wtam We are looking into it and get back to you for any additional information.

**Comment by pvaneck** [comment]
Seems the import is just missing a capital 'C'. (i.e.  `from azure.confidentialledger import ConfidentialLedgerClient`)

**Comment by riyadhuddin** [comment]
from azure.confidentialledger import TransactionState
ImportError: cannot import name '**TransactionState**' from 'azure.**confidentialledger**'
