### ISSUE TITLE
[doc] update meta csv data

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#23831]
https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/python-packages.csv

teams chat:
https://teams.microsoft.com/l/message/19:b97d98e6d22c41e0970a1150b484d935@thread.skype/1648836359009?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1648836359009&teamName=Azure%20SDK&channelName=Language%20-%20Python&createdTime=1648836359009

(1) For new service, we may need to change the update https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/python-packages.csv manually
(2) For existing services, the info in .csv will be updated automatically.

example: https://github.com/Azure/azure-sdk/pull/3711

**Comment by BigCat20196** [comment]
https://github.com/Azure/azure-sdk/pull/4195
