### ISSUE TITLE
Event Hubs Troubleshooting Guide

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-python#23836]
# Summary

In order to provide guidance for customers encountering difficulties with the client library, and support representatives working customer issues, a troubleshooting guide is needed.  The guide should be focused on common scenarios for the client library and not attempt to address service-specific issues.

# Scope

- Wait for the forthcoming [Java troubleshooting guide](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/eventhubs/TROUBLESHOOTING.md) to be completed and made available.  _(target date is April 25)_

- Review email, issues, and the Java guide to identify any recurring topics.

- Address common scenarios, such as:
    - Event Hubs exceptions that can be returned, and guidance for them
    - Connectivity issues for enterprise environments.  _(try the web sockets transport)_
    - Common event processor scenarios (too many partitions for the machine,  load balancing can't keep up, etc)
    - Consider discussing specific sets of log events to capture for certain scenarios

- Write the guide in markdown format, intended for `/sdk/eventhub/TROUBLESHOOTING.md`

- Add stub guides in the root of each package pointing back at the main troubleshooting guide.  _(see KeyVault for inspiration)_

# Success Criteria

- The guide has been created and added to the repository by May 15.

- The Event Hubs feature crew has been notified that the troubleshooting guide is complete for Python.

# References and Resources

- [Azure.Identity Troubleshooting Guide](https://github.com/schaabs/azure-sdk-for-net/blob/id-troublehooting-update/sdk/identity/Azure.Identity/troubleshooting.md)
- [Troubleshooting Section of the README](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/eventhub/azure-eventhub#troubleshooting)
- [Event Hubs Exceptions (legacy)](https://docs.microsoft.com/azure/event-hubs/event-hubs-messaging-exceptions)
- [Troubleshooting Event Hubs Connectivity](https://docs.microsoft.com/azure/event-hubs/troubleshooting-guide)

**Comment by kashifkhan** [comment]
Closed with PR #24697
