### ISSUE TITLE
PathProperties._from_generated raises exception if last_modified is empty

### ISSUE THREAD

**Issue by blem14** [Azure/azure-sdk-for-python#23834]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.6.0
- **Operating System**: Windows 11 x64
- **Python Version**: 3.9.7

**Describe the bug**
Listing paths may fail on directories with empty `last_modified`.
Introduced in [PR #16093](https://github.com/Azure/azure-sdk-for-python/pull/16093).

**To Reproduce**
1. Have directory/file in the datalake without `last_modified` filled.
2. Run 
    ```python
    from azure.storage.filedatalake import DataLakeServiceClient
    service_client = DataLakeServiceClient(url, credential)
    fs_client = service_client.get_file_system_client(file_system)
    for p in fs_client.get_paths():
        print(p.name)
    ```
3. Get `TypeError: strptime() argument 1 must be str, not None` at [azure/storage/filedatalake/_models.py:224](https://github.com/Azure/azure-sdk-for-python/blob/233fbea41624661bd8687e2b3ce0ce16d37bff51/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py#L224).

**Expected behavior**
Listing directories not failing on directories/files with empty `last_modified`.
If `last_modified` can't be cast to `datetime.datetime`, it should be `None`.

**Additional context**
Not sure how `last_modified` ended up being empty in the first place, but I've met with such case on client's datalake.

**Comment by l0lawrence** [comment]
Thanks for the feedback, we'll investigate this asap.

**Comment by jalauzon-msft** [comment]
Hi @blem14, thanks for reporting this and doing a bit of investigation to figure out the issue! I'm also not really sure how a file/directory would end up with no last_modified time from the server, that seems odd. Either way, this does seem like a case we should handle. I'm making changes in this area for the upcoming release, I'll go ahead and fix it there as well.

**Comment by jalauzon-msft** [comment]
This has been merged and will be part of our upcoming release.
