### ISSUE TITLE
azure-mgmt should depend on azure-mgmt-rdbms~=0.3.1 to follow new pricing model

### ISSUE THREAD

**Issue by themr0c** [Azure/azure-sdk-for-python#2384]
azure-mgmt-rdbms 0.3.x was released to follow new pricing model.

my guess is that azure-mgmt-rdbms 0.1.0 does not work anymore with the new pricing model, and the dependency should be adapted in azure-mgmt.

**Comment by QingqingYuan** [comment]
We didn't deprecate the old API yet. So azure-mgmt-rdbms 0.1.0 is still working as we handle backward compatibility. But we're planning to retiring supporting the old version. So yes, please update the dependency to the new version. And we want to follow new pricing model.

**Comment by lmazuel** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-python/pull/2999
