### ISSUE TITLE
invalid URL: all the samples pointing to www.public-domain-photos.com are invalid. www.public-domain-photos.com is not registered

### ISSUE THREAD

**Issue by cesarwhite** [Azure/azure-sdk-for-python#23841]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91b0f03-d716-3421-9023-8e871c188188
* Version Independent ID: 4565d28a-0c4d-f663-b9ea-b53e51389d10
* Content: [Azure Cognitive Services Computer Vision SDK for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/cognitiveservices-vision-computervision-readme?view=azure-python#feedback)
* Content Source: [docs-ref-services/latest/cognitiveservices-vision-computervision-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/cognitiveservices-vision-computervision-readme.md)
* Service: **computervision**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by l0lawrence** [comment]
Thanks for the feedback, we'll look into this asap.

**Comment by xiangyan99** [comment]
Given they are sample snippets, closing.
