### ISSUE TITLE
Is there a custom vision endpoint in a non-US region e.g. Europe?

### ISSUE THREAD

**Issue by jtlz2** [Azure/azure-sdk-for-python#2385]
I have searched and searched, been directed to marketing by Azure, asked on stackoverflow, am not sure whether this is the right place to ask, but:

What are the custom vision endpoints apart from southcentralus?

If they are not yet available, when will they be?

Thanks

**Comment by lmazuel** [comment]
@areddish please? :)

**Comment by lmazuel** [comment]
Closing, since the question is answered. Thanks @areddish !
