### ISSUE TITLE
[synapse] release for `azure-synapse-artifacts`

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#23866]
RE: Synapse data plane SDK April release

last release: https://github.com/Azure/azure-sdk-for-python/pull/23295

**Comment by BigCat20196** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/23872

**Comment by BigCat20196** [comment]
pypi link: https://pypi.org/project/azure-synapse-artifacts/0.13.0/
