### ISSUE TITLE
[Form Recognizer] Most of the environments on UsGov have timeouts.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-python#23879]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
It is the latest result in pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1487680&view=results

All environments on `UsGov` have timeouts, and we set the timeout to 8 hours. After investigation, it was found that the current running of a single test for up to an hour caused the current timeout.

This problem had been fixed some days ago, but recently it occurs again, could you take a look?

**Expected behavior:**
All tests can pass on `UsGov` cloud without timing out.

@benbp, @jameszliao-msft, @lmazuel, @meeraharidasa , @mayurid, @catalinaperalta for notification.

**Comment by catalinaperalta** [comment]
@ctstone could you help us take a look at this? It seemed to have been fixed for a couple of days, but seems to be happening again. Thanks!

**Comment by catalinaperalta** [comment]
Just wanted to add a quick update, I spoke with the service team today and they are aware of the issue and investigating it.

**Comment by zedy-wj** [comment]
@catalinaperalta  - Thanks for following up :)

**Comment by catalinaperalta** [comment]
@zedy-wj, @ctstone  would be the best person to answer that question, but I will also follow up with the service team offline about this and see if they resolved the issue.

**Comment by catalinaperalta** [comment]
The service team informed me that the mitigation process for these issues is still ongoing. Some of the latency issues have been addressed but others may still occur.

**Comment by v-xuto** [comment]
@catalinaperalta Thanks for your prompt reply. If there is any progress of this issue, please let us know in time. Thanks a lot.

**Comment by zedy-wj** [comment]
It doesn't reproduce anymore, we'll close it, thanks!
