### ISSUE TITLE
Unable to attach cognitive service using python SDK

### ISSUE THREAD

**Issue by akazlow** [Azure/azure-sdk-for-python#23884]
- **Package Name**:  Azure Cognitive Search
- **Package Version**:  11.2.1
- **Operating System**: Windows
- **Python Version**: 3.7

**Describe the bug**
When creating an azure search skill set through the Python SDK, I am unable to attach an azure cognitive service. This causes entities populated by the skill set to not be populated. The `CognitiveServiesAccount` model that is to be used by the `searchIndexerSkillset` constructor does not seem to exist when I try to import it.

The documentation [here](https://docs.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.indexes.models.searchindexerskillset?view=azure-python) says the cognitive services account object is a required parameter, but I am unable to add it and no errors are thrown when I create the skillset without it.

**To Reproduce**
When creating a skillset, the CognitiveServicesAccount parameter is not required and a skillset is successfully created without it. This directly contradicts the online documentation for the searchIndexerSkillset constructor which states the CognitiveServicesAccount parameter is required.

![CognitiveServicesAccount Required](https://user-images.githubusercontent.com/68910142/162211377-9acce364-3cf4-4406-9053-b27da0e2fe9b.png)
![CognitiveServicesAccount Not Required](https://user-images.githubusercontent.com/68910142/162211376-2bf02a54-42da-403f-bcd3-bb9792fa1f2b.png)

I am also unable to import the CognitiveServicesAccount object from the Python SDK, so it seems it is not possible to pass it in and specify what account I would like to attach to.

![Module Not Found](https://user-images.githubusercontent.com/68910142/162211374-2d70964b-c887-4753-a1d0-0d7387f90641.png)

When I create the skillset without it, there are no errors and it appears as if the skillset is successfully created.

![Successful Creation](https://user-images.githubusercontent.com/68910142/162211373-2221d71b-c60a-4df8-8b1f-770458f8d681.png)

However, when I inspect the skillset in the portal, the cognitive services account is null so the skillset will not work. This is causing issues with programmatically deploying a working solution using Python.

![Null Cognitive Service](https://user-images.githubusercontent.com/68910142/162211371-8cc357ab-0030-4138-ad9a-fb57a7f08e25.png)

**Expected behavior**
When creating a skillset, I expect to be able to create a CognitiveServicesAccount object and pass it into the searchIndexerSkillset constructor. I also expect this parameter to be required and an error will be thrown if I do not pass in the CognitiveServicesAccount object. When I inspect the skillset in the portal I expect the correct cognitive service to be attached to the skillset.

**Screenshots**
![ai-openhack-cognitive-service-null](https://user-images.githubusercontent.com/68910142/162211371-8cc357ab-0030-4138-ad9a-fb57a7f08e25.png)
![ai-openhack-no-errors](https://user-images.githubusercontent.com/68910142/162211373-2221d71b-c60a-4df8-8b1f-770458f8d681.png)
![ai-openhack-no-module-cognitiveServicesAccount](https://user-images.githubusercontent.com/68910142/162211374-2d70964b-c887-4753-a1d0-0d7387f90641.png)
![ai-openhack-param-not-required](https://user-images.githubusercontent.com/68910142/162211376-2bf02a54-42da-403f-bcd3-bb9792fa1f2b.png)
![ai-openhack-param-required](https://user-images.githubusercontent.com/68910142/162211377-9acce364-3cf4-4406-9053-b27da0e2fe9b.png)

**Additional context**
To work around the issue stated above, the REST API can be used to update the skillset created through the Python SDK and attach a cognitive service account to it. The developer can also attach one through the portal. 

The Python SDK documentation should be updated to state this issue and any workarounds. The issue should also be logged and eventually fixed so users can deploy a working solution using Python.

**Comment by kashifkhan** [comment]
Hi @akazlow , thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by LeoXLiu-DS** [comment]
@akazlow You can use `azure.search.documents.indexes.models.CognitiveServicesAccountKey` to set the argument `cognitive_services_account` of `SearchIndexerSkillset` to attach the cognitive search.
