### ISSUE TITLE
Azure-search-documents(PRE-RELEASE 11.3.0b8) semantic query does not return @search.rerankerScore in result

### ISSUE THREAD

**Issue by dinoelT** [Azure/azure-sdk-for-python#23906]
Returned results when using the python search client do not contain the @search.rerankerScore field.
```
    results_generator =  search_client.search(search_text= user_query.lower(),
                                            query_type="semantic",
                                            query_language="de-DE",
                                            semantic_configuration_name = "simple-config",
                                            top = 10)

```
However, when making the request using the API/Portal it returns the @search.rerankerScore.
I'm not sure if this is an issue, or I just overlooked something.

**Comment by l0lawrence** [comment]
Thanks for the feedback, we'll investigate this asap.

**Comment by kashifkhan** [comment]
Hi @dinoelT, thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by kashifkhan** [comment]
@dinoelT I am able to reproduce the bug on my side. I will let you know when I can get an update out

**Comment by JustinCharbonneau** [comment]
Hi, I would like to mention that I am using the Python SDK version 11.3.0b8 and I'm having this issue also. The reranking seems to be applied on the ordering of the returned results, but I do not have access to the @search.rerankerScore. (Which is available in the Search Explorer). 

Any updates on this issue? Thanks!

**Comment by kashifkhan** [comment]
@JustinCharbonneau I'll be meeting with the Search team and will have an update on when we will do our next beta release for this.

**Comment by LucasVascovici** [comment]
#https://github.com/Azure/azure-sdk-for-python/pull/27502

**Comment by LucasVascovici** [comment]
Created a PR #27502
