### ISSUE TITLE
[azure-monitor-query] Will there be a new release of azure-monitor-query Python package?

### ISSUE THREAD

**Issue by cccs-eric** [Azure/azure-sdk-for-python#23919]
I am using the azure-monitor-query Python package and I ran into a bug.  While finding a fix for it, I realized that it was already fixed in the main branch, but that commit has not been packaged in a release yet.  Last release was 1.0.1, November 2021.  Anyone know if there is a plan to make another release soon?

**Comment by mccoyp** [comment]
Hi @cccs-eric, thank you for opening an issue! I'll tag someone on this who can help with your question.

**Comment by rakshith91** [comment]
@cccs-eric Thanks for the issue - may I know more details about the issue and what the fix is? Yes, we will release azure-monitor-query

**Comment by cccs-eric** [comment]
thanks @mccoyp and @rakshith91, here is the issue I am looking to fix.  I am querying a source with a column of type `datetime`, but its value is `None`.  When this [code ](https://github.com/Azure/azure-sdk-for-python/blob/azure-monitor-query_1.0.1/sdk/monitor/azure-monitor-query/azure/monitor/query/_helpers.py#L117-L122) is executed, the underlying calls are not handling the `None` value and `msrest` eventually [tries to call](https://github.com/Azure/msrest-for-python/blob/master/msrest/serialization.py#L1943) `upper()` on it.

I locally did the following fix:
```python
def native_col_type(col_type, value):
    if col_type == "datetime" and value:
        value = Deserializer.deserialize_iso(value)
    elif col_type in ("timespan", "guid"):
        value = str(value)
    return value
```

I saw that the latest code from `main` is [now handling exception](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-query/azure/monitor/query/_helpers.py#L117-L127) and returning the passed value, hence returning `None` and not crashing.

**Comment by rakshith91** [comment]
@cccs-eric Thanks for the details. We will be releasing the package soon. Keep looking out.

**Comment by rakshith91** [comment]
@cccs-eric We have released the bug fix. Please check this out https://pypi.org/project/azure-monitor-query/

**Comment by cccs-eric** [comment]
Thanks @rakshith91 , just tested the new release and it fixed my problem!
