### ISSUE TITLE
AppConfiguration can't auth in Germany West Central cloud using connection string?

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-python#23917]
There was a bug reported for Go SDK, when AppConfig client couldn't authorize in Germany West Central cloud using the connection string: https://github.com/Azure/azure-sdk-for-go/issues/17424

The fix is to use and sign `Date` header instead of `x-ms-date` (the Go PR is linked in the Go issue, it is a 2-line change).

I searched your code base for `"SignedHeaders"` to easily find the place that handles HMAC auth, and it looks like you're also using `x-ms-date` header instead of `Date` (and that's what the AppConfig docs currently say you should do - https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-hmac, so if it is confirmed that your SDK is affected, we need to get the doc updated as well).

Java and .NET SDKs are currently using `Date` header instead of `x-ms-date` for AppConfiguration auth.

I am sorry that at this moment I cannot tell you for sure that you are affected by this, but I have reasons to think that you should be, based on the code, and the fix that I am making for the Go SDK. Maybe I will be able to confirm it some time later, or maybe you can give it a try, if you have your dev environment set up. The only thing you need is to create an azure app configuration in German cloud, get the connection string for it, then write a code to create AppConfig client, and try to create or read configuration setting, it should fail. But if you do the same for App Configuration deployed to West US, all will work fine.

https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_requests.py

**Comment by YalinLi0312** [comment]
Hi @antkmsft , thanks for reaching us!
One thing needs to confirm, do you mean the `public Azure in Germany`? Because the Cloud Germany is already closed.

**Comment by antkmsft** [comment]
This was reproing in Germany West Central back in April. Now it no longer repros, both `Date` and `x-ms-date` are fine.

**Comment by antkmsft** [comment]
No, sorry, my bad, it still reproes.
Germany West Central.
You can try accessing my `antk-appconfig2` using the connection string, you can find one in the Developer Playground.

**Comment by YalinLi0312** [comment]
Thanks @antkmsft , I'll try to reproduce the problem asap.
