### ISSUE TITLE
[identity] `azure-identity` should use the latest `msal-extensions` 1.0.0

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#23927]
Azure Identity has pinned `msal-extensions` to 

https://github.com/Azure/azure-sdk-for-python/blob/b8a947329a3c5f9578a7b1f7a345d654b76bdce2/sdk/identity/azure-identity/setup.py#L79

This makes it impossible for Azure CLI to use `msal-extensions` 1.0.0 (https://pypi.org/project/msal-extensions/) which has some improvements like https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/108.

Please make `azure-identity` compatible with `msal-extensions` 1.0.0. Thanks.

**Comment by sybnex** [comment]
So when will this be released? The combination of azure cli v2.36.0 and the azure-identity module is not working at the moment!

**Comment by geekydonna** [comment]
What is the fix for trying to write python that needs this? My CLi is up-to-date, but I'm running into the same problem when I try to use azure-identity in my code

**Comment by mccoyp** [comment]
Hi @geekydonna, `msal-extensions` 1.0.0 is supported starting with `azure-identity` version 1.10.0. If you're having a conflict, you may need to upgrade your version of `azure-identity`.
