### ISSUE TITLE
Digital Twins Core raedme issue

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#23928]
1. 
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/digitaltwins/azure-digitaltwins-core#how-to-install):

![GetImage](https://user-images.githubusercontent.com/80307197/162694228-f6ca9493-76d0-4dd5-9e82-25265aed373d.png)

Suggestion:
Add link: https://pypi.org/project/azure-digitaltwins-core/ 

@jameszliao-msft , @lmazuel , @joshfree and @johngallardo for notification.

**Comment by SaurabhSharma-MSFT** [comment]
@AFengKK We are looking into it and get back to you for any additional information.

**Comment by lmazuel** [comment]
PR merged
