### ISSUE TITLE
[typing] Typing issues in _utils.py

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#23962]
I was playing around with a typing checker in pylint and I noticed that:

- [ ] In get_authentication_header, the typing return type and rtype in the docstring do not match:  (missing an 's' HMACCredentialsPolicy)

 ```
-> BearerTokenCredentialPolicy or HMACCredentialPolicy 
:rtype: ~azure.core.pipeline.policies.BearerTokenCredentialPolicy or ~HMACCredentialsPolicy 
```

- [ ] Also, I think we would want the rtype docstring to contain the full path of both packages and use "or":
```:rtype: ~azure.core.pipeline.policies.BearerTokenCredentialPolicy or  ~azure.XXXX.HMACCredentialsPolicy```

- [ ] For types that have an "or", i.e.  ```type: TokenCredential or str ```
I think we would want to be referencing them as: ``` Union[TokenCredential, str] ``` which is "or" for typing

- [ ] If AccessToken is imported as ```from azure.core.credentials import AccessToken```, then when referencing it in the typehints 
       instead of  ```# type: (str) -> azure.core.credentials.AccessToken```, we can access it as ```# type: (str) -> AccessToken```

The File in Question:
https://github.com/Azure/azure-sdk-for-python/blob/827028d04cd2e9380ba4a45e29ab80b7277387bd/sdk/communication/azure-communication-sms/azure/communication/sms/_shared/utils.py

**Comment by kristapratico** [comment]
Closed in #26153
