### ISSUE TITLE
Azure App Config Feature Manager python sdk

### ISSUE THREAD

**Issue by gpnikhil** [Azure/azure-sdk-for-python#23970]
az appconfig feature filter add -n azureDBconfig --feature check --filter-name Microsoft.Targeting --filter-parameters Audience={\"DefaultRolloutPercentage\":0,\"Users\":[\"d.g@f.com\",\"a.n@c.com\"]}

I would like to perform this az command, using azure sdk, but not able to find specific examples or use case, can any one guide me here
Thanks

**Comment by mccoyp** [comment]
Hi @gpnikhil, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible.

**Comment by msyyc** [comment]
Hi @gpnikhil, azure-cli depends on azure python sdk. We will write a doc to guide users how to realize same function with python SDK if they knows azure cli cmd.

**Comment by navba-MSFT** [comment]
@gpnikhil Please refer this docs which explains how to find the SDK in AzCLi command:  https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/find_sdk/find_sdk_in_cli_command.md
Hope this helps.
