### ISSUE TITLE
[tools] Collect api version used by azure-stack

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#23991]
source files:
https://github.com/Azure/azure-rest-api-specs/tree/main/profiles/definitions
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/profiles/_shared.py

pipeline:
https://dev.azure.com/azure-sdk/internal/_build?definitionId=3920

code:
https://github.com/msyyc/azure-sdk-for-python/tree/collect-api-version/scripts/collect_api_version_for_multi_api_sdk

output:
https://github.com/msyyc/file-storage/blob/collect-api-version

**Comment by BigCat20196** [comment]
pr here: https://github.com/Azure/azure-sdk-for-python/pull/22838
