### ISSUE TITLE
[Tables] Fix suppressed pylint issues

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#24000]
Suppressed for now:

- [ ] azure\data\tables\_base_client.py:208: [C4748(client-accepts-api-version-keyword)
- [x] azure\data\tables\_entity.py:27: [C4747(enum-must-inherit-case-insensitive-enum-meta)
- [x] azure\data\tables\_error.py:240: [C4747(enum-must-inherit-case-insensitive-enum-meta)
- [x] azure\data\tables\_error.py:242-308: [C4746(enum-must-be-uppercase)
- [x] azure\data\tables\_models.py:538: [C4747(enum-must-inherit-case-insensitive-enum-meta)
- [x] azure\data\tables\_models.py:543: [C4747(enum-must-inherit-case-insensitive-enum-meta)
- [x] azure\data\tables\_models.py:550: [C4747(enum-must-inherit-case-insensitive-enum-meta)
- [x] azure\data\tables\_models.py:555: [C4747(enum-must-inherit-case-insensitive-enum-meta)
- [ ] azure\data\tables\_table_client.py:49: [C4748(client-accepts-api-version-keyword)
- [ ] azure\data\tables\aio\_base_client_async.py:47: [C4748(client-accepts-api-version-keyword)
- [ ] azure\data\tables\aio\_table_client_async.py:45: [C4748(client-accepts-api-version-keyword)

**Comment by YalinLi0312** [comment]
api-version suppression is tracked by issue https://github.com/Azure/azure-sdk-for-python/issues/28115. Will close this issue once the PR linked above merged.
