### ISSUE TITLE
[EventHubs] Buffered producer consider using the number of partitions as the default worker count

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#24013]
### background

In the sync buffered implementation implementation:

- the `max_worker` and `executor` are remove from the public api surface
- for implementation, a default `ThreadPoolExecutor` is created -- Python will decide `max_worker` value.

Anna: Wondering if we should use the number of partitions as the default worker count?

_Originally posted by @annatisch in https://github.com/Azure/azure-sdk-for-python/pull/23748#discussion_r849061685_

Adam: Concerned about too many threads resulting in low performance, need testing

### tasks

- investigate how number of threads would affect performance
- decide what to set as default max_worker value.

**Comment by kashifkhan** [comment]
@jsquire right now Python went with the default number of workers as picked by ThreadPoolExecutor which is ` it will default to the number of processors on the machine, multiplied by 5` up till py3.8. From 3.8 onwards it is min(32, os.cpu_count() + 4)
