### ISSUE TITLE
Python SDK - create_images_from_urls - CustomVisionErrorException: No image urls provided

### ISSUE THREAD

**Issue by agonzalez-mob** [Azure/azure-sdk-for-python#24026]
- **Package Name**: azure-cognitiveservices-vision-customvision
- **Package Version**: 
azure-cognitiveservices-vision-customvision==3.1.0
azure-common==1.1.28
azure-core==1.23.1
azure-storage-blob==12.11.0
- **Operating System**: MacOs Monterrey 12.3.1
- **Python Version**: Python 3.8.13

**Describe the bug**
When trying to upload a picture using ImageUrlCreateBatch I get the error: `CustomVisionErrorException: No image urls provided`. It fails with all image urls.

**To Reproduce**

After creating the trainer and project I try to upload any picture using it create_images_from_urls:

```
credentials = ApiKeyCredentials(in_headers={"Training-key": training_key})
trainer = CustomVisionTrainingClient(ENDPOINT, credentials)
project = trainer.create_project(project_name, domain_id = obj_detection_domain, classification_type = classification_type)
# the above is just fyi

original_image_uri = 'https://blog.hubspot.com/hubfs/parts-url.jpg'
tag_ids            = ['tag1']
entry              = ImageUrlCreateEntry(url=original_image_uri)

batch = ImageUrlCreateBatch(images=[entry], tag_ids=tag_ids)
trainer.create_images_from_urls(project.id, batch)

---------------------------------------------------------------------------
CustomVisionErrorException                Traceback (most recent call last)
/var/folders/d1/3ccrqy3947q9983ktch0tthc0000gn/T/ipykernel_60740/1079157937.py in <cell line: 1>()
----> 1 trainer.create_images_from_urls(project.id, batch, raw= True)

~/opt/anaconda3/envs/sgsApiTraining/lib/python3.8/site-packages/azure/cognitiveservices/vision/customvision/training/operations/_custom_vision_training_client_operations.py in create_images_from_urls(self, project_id, batch, custom_headers, raw, **operation_config)
   1895 
   1896         if response.status_code not in [200, 207]:
-> 1897             raise models.CustomVisionErrorException(self._deserialize, response)
   1898 
   1899         deserialized = None

CustomVisionErrorException: No image urls provided
```

The following also fails with the same error:

```
    entry              = ImageUrlCreateEntry(url=original_image_uri, tag_ids=tag_ids)
    
    batch = ImageUrlCreateBatch(images=[entry])
    trainer.create_images_from_urls(project.id, batch)
```

**Comment by mccoyp** [comment]
Hi @agonzalez-mob, thank you for opening an issue! I'm tagging some folks who should be able to help.

**Comment by agonzalez-mob** [comment]
Btw, using the api worked
```
test_url   = 'https://blog.hubspot.com/hubfs/parts-url.jpg'
image_url  = f'{ENDPOINT}/customvision/v3.3/Training/projects/{project_id}/images/urls'


body = {
    "images": [{"url": test_url, "tagIds": [tags_ids[0]]}]
    , "tagIds": [tags_ids[0]]
    , "metadata": {}
}


image_test = requests.post(url= image_url, json = body, headers=headers)
image_test.json()
```

**Comment by SaurabhSharma-MSFT** [comment]
@agonzalez-mob I am seeing the same behavior and checking internally on the same.  I will get back to you with my findings.

Thanks
Saurabh

**Comment by xiangyan99** [comment]
@SaurabhSharma-MSFT any updates?

**Comment by SaurabhSharma-MSFT** [comment]
@agonzalez-mob Are you using a GUID (or GUIDs for tags) for the tag id? The guid should be returned when you create a tag: [create-tag](https://docs.microsoft.com/en-us/rest/api/customvision/training3.4preview/create-tag/create-tag)

**Comment by agonzalez-mob** [comment]
> @agonzalez-mob Are you using a GUID (or GUIDs for tags) for the tag id? The guid should be returned when you create a tag: [create-tag](https://docs.microsoft.com/en-us/rest/api/customvision/training3.4preview/create-tag/create-tag)

I'm not sure anymore. It was such a long time ago. 
I might have been using the name instead of the GUID.

**Comment by xiangyan99** [comment]
Thanks for your updates.

Given your code is deprecated, we will close the issue.

Please feel free to open a new one if you see it again.
