### ISSUE TITLE
Blob delete method it's not working 

### ISSUE THREAD

**Issue by italoveloso89** [Azure/azure-sdk-for-python#24066]
**Describe the bug**
Hi guys, I'm trying to delete a blob(directory).
But for some reason, I can't delete it because this directory isn't empty.

***Exception or Stack Trace***
PS C:\Users\Italo Veloso\Desktop\Lumeto\PlayfabPY>  c:; cd 'c:\Users\Italo Veloso\Desktop\Lumeto\PlayfabPY'; & 'C:\Users\Italo Veloso\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\Italo Veloso\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\launcher' '50021' '--' 'c:\Users\Italo Veloso\Desktop\Lumeto\PlayfabPY\deleteBlob.py' 
Traceback (most recent call last):
  File "c:\Users\Italo Veloso\Desktop\Lumeto\PlayfabPY\deleteBlob.py", line 11, in <module>
    container.delete_blobs("35241")
  File "C:\Users\Italo Veloso\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\core\tracing\decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\Italo Veloso\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\storage\blob\_container_client.py", line 1348, in delete_blobs
    return self._batch_send(*reqs, **options)
  File "C:\Users\Italo Veloso\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 322, in _batch_send
    process_storage_error(error)
  File "C:\Users\Italo Veloso\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "C:\Users\Italo Veloso\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 318, in _batch_send
    raise error
azure.storage.blob._shared.response_handlers.PartialBatchErrorException: There is a partial failure in the batch operation.
ErrorCode:None
Content: --batchresponse_96b60333-10bb-4637-85e3-fa7a720bdee4
Content-Type: application/http
Content-ID: 0

HTTP/1.1 409 The directory involved in this operation is not empty
x-ms-error-code: DirectoryNotEmpty
x-ms-request-id: 30a0f337-b01e-0006-4640-538cb81e7ec8
x-ms-version: 2021-04-10
x-ms-client-request-id: ac554830-bf33-11ec-9b0a-1c1b0df1a493
Content-Length: 240
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0

<?xml version="1.0" encoding="utf-8"?>
<Error><Code>DirectoryNotEmpty</Code><Message>The directory involved in this operation is not empty
RequestId:30a0f337-b01e-0006-4640-538cb81e7ec8
Time:2022-04-18T16:22:01.1077373Z</Message></Error>
--batchresponse_96b60333-10bb-4637-85e3-fa7a720bdee4--

**To Reproduce**

***Code Snippet***
```
from azure.storage.blob import ContainerClient

sas_url = "https://lumetotest.blob.core.windows.net/lumetotest?sp=racwdlmeop&st=2022-04-18T16:04:30Z&se=2022-04-19T00:04:30Z&sv=2020-08-04&sr=c&sig=mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
container = ContainerClient.from_container_url(sas_url)

#35241 is the directory that I wanna delete inside of container(lumetotest)
container.delete_blobs("35241")
```

**Expected behavior**
Delete directory.

**Setup (please complete the following information):**
 - Python Version: 3.10.4

azure-common==1.1.28
azure-core==1.23.1
azure-mgmt-core==1.3.0
azure-mgmt-storage==20.0.0
azure-storage-blob==12.11.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cryptography==36.0.2
idna==3.3
isodate==0.6.1
msrest==0.6.21
oauthlib==3.2.0
psycopg2==2.9.3
pycparser==2.21
requests==2.27.1
requests-oauthlib==1.3.1
six==1.16.0
typing_extensions==4.1.1
urllib3==1.26.9

**Comment by vincenttran-msft** [comment]
Hi @italoveloso89 Italo, the reason why you are running into this issue is because the `delete_blobs` API from `azure-storage-blob` is a batch operation that does **not** support the deletion of non-empty directories. As you have listed that your "Expected Behavior" is to delete the directory, below I have provided two code samples (one that **is** recommended, and one that is _**not**_ recommended as I believe it does not do what you are intending to do with your above provided code sample).

**Code Sample 1. (Recommended, this will actually recursively delete the directory and its contents)**
```
from azure.storage.filedatalake import DataLakeServiceClient

# Note the 'dfs' endpoint rather than 'blob' endpoint
STORAGE_ACCOUNT_URL = f"https://<STORAGE_ACCOUNT_NAME>.dfs.core.windows.net"

# Please ensure the SAS key has the proper permissions (read, delete, etc.)
# And is a container-level SAS
STORAGE_ACCOUNT_SAS = <SAS_KEY>

dsc = DataLakeServiceClient(account_url=STORAGE_ACCOUNT_URL, credential=STORAGE_ACCOUNT_SAS)
directory_client = dsc.get_directory_client(file_system=<CONTAINER_NAME>, directory=<DIRECTORY_NAME>)
directory_client.delete_directory()
```
Where **<SAS_KEY>** is your container-level SAS key with proper permissions, **<CONTAINER_NAME>** is `lumetotest`, and **<DIRECTORY_NAME>** is `35241`

**Code Sample 2. (_NOT recommended_, this will _NOT_ recursively delete your directory and its contents)**
```
from azure.storage.blob import ContainerClient
sas_url = "https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/mycontainer?sp=racwd&st=2022-05-23T21:43:06Z&se=2022-05-24T05:43:06Z&spr=https&sv=2020-08-04&sr=c&sig=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
container = ContainerClient.from_container_url(sas_url)
blob_client = container.get_blob_client(blob=<DIRECTORY_NAME>)
blob_client.delete_blob()
```
Where **<DIRECTORY_NAME>** is `35241`

Hopefully the provided code sample(s) will help you resolve your issue.
Thanks!
