### ISSUE TITLE
generate_blob_sas sdk sometimes doesnt work in python

### ISSUE THREAD

**Issue by sreekeren** [Azure/azure-sdk-for-python#24081]
I am using the following method from python SDK for azure-iot-hub.

sas_blob = generate_blob_sas(account_name= STORAGE_ACCOUNT_NAME, account_key = ACCOUNT_ACCESS_KEY, container_name= containername, protocol = "https", start = datetime.datetime.utcnow() - timedelta( minutes= 40) , expiry= datetime.datetime.utcnow() + timedelta(hours=24), permission=BlobSasPermissions(read=True), blob_name = local_file_name)

This API generates sometimes invalid sas URL resulting in error
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

And sometimes it generates the correct sas URL through which files can be downloaded successfully.

Am I missing something? not able to identify why is there an inconsistency

What I have tried to do here is,
1. upload the blob file, verified that blob is present in IOT Hub.
2. Next tried to generate as URL for that blob multiple times to see the consistency of generate_blob_sas method.

observations:
1. Sometime the sas URL correctly points to the file.
2. Then sometimes I get invalid sas URL issue.

**Comment by asergaz** [comment]
Relates with: https://docs.microsoft.com/en-us/answers/questions/801684/index.html

**Comment by rakshith91** [comment]
@sreekeren  Thanks for opening this issue. We will investigate this asap

**Comment by rakshith91** [comment]
@jalauzon-msft Can you take a look at this?

**Comment by jalauzon-msft** [comment]
Hi @sreekeren, I have a couple of follow-up questions to help us better understand your issue:

- You mentioned you observed the SAS tokens for consistency. Did you notice any different in the SAS tokens that work and the ones that don't?
- Are you able to get a working AND non-working token for the same blob? Or is it some blobs that don't work?
- Would you mind sharing an example of a working token and a non-working token (being sure to exclude the `sig=` part of the token and you can hide the file name if you wish)
- Could you also share a code sample of how you are using the SAS?

Thanks!
