### ISSUE TITLE
Error detected in aggregate-report

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-python#24084]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1514312&view=logs&j=3b141548-98d7-5be1-7ef8-eeb08ca02972&t=41e0d8dc-42df-5fff-2417-80cd016cccdb

We have one error reported in aggregate-report.

Could you please investigate and take action on either remove or rotate the secret?

**Comment by xiangyan99** [comment]
#24126
