### ISSUE TITLE
[Cosmos] Fix Pylint Disable API Keyword 

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#24094]
Cosmos SDK has a pylint:disable statement around the required api_version kwarg. 

cc: @johanste , @tjprescott

**Comment by tjprescott** [comment]
@l0lawrence why was this issue created and then removed?

**Comment by l0lawrence** [comment]
I made it after seeing the PR comments on cosmos, but then Simon mentioned that he was still getting that reviewed so I closed it.

**Comment by simorenoh** [comment]
@tjprescott can we close this issue if we're using this one as a reminder for follow-up? https://github.com/Azure/azure-sdk-for-python/issues/24132
