### ISSUE TITLE
Cannot use Azure SDK with IronPython

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#241]
The str/bytes handling is all based on Python version number and not what the types actually are, and IronPython's HTTP libraries expect str even though there is a proper bytes type.

There are some assertions that fail because IronPython's str.encode() method returns str, not bytes, and those assertions need to be checking for str in IronPython because of the libraries.

I fixed those up and got as far as I could, but now my storage requests are being rejected, probably because we don't generate the auth header correctly. If I make any progress on that, I'll post it here.

**Comment by lmazuel** [comment]
Also found a problem with six, indirect dependency of the SDK:
https://bitbucket.org/gutworth/six/issues/135/have-a-fallback-for-sys_getframe-usage-in

**Comment by lmazuel** [comment]
We don't plan to do anything for IronPython, and we never had any demands :/
Closing...
