### ISSUE TITLE
FileSystemClient.get_paths() throws a ContainerNotFound error even when container exists

### ISSUE THREAD

**Issue by jdthorpe** [Azure/azure-sdk-for-python#24106]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.6.0
- **Operating System**: OSX
- **Python Version**: 3.9

**Describe the bug**

`FileSystemClient.get_paths()` throws a `ContainerNotFound` error even thought the container exists

**To Reproduce**

This code throws a `ContainerNotFound` error every time:

```py
from azure.storage.filedatalake import FileSystemClient

fsc = FileSystemClient( account_url=ACCOUNT_URL, file_system_name=CONTAINER_NAME, credential=SAS_TOKEN)
paths = fsc.get_paths()
for path in paths:
    print("\t" + path.name)
```

but this equivalent code from the `azure-storage-blob` does not:

```py
from azure.storage.blob import ContainerClient

container_client = ContainerClient( account_url=ACCOUNT_URL, container_name=CONTAINER_NAME, credential=SAS_TOKEN,)
blob_list = container_client.list_blobs()
for blob in blob_list:
    print("\t" + blob.name)
```

and for what it's worth, I created the SAS token by logging in to the azure cli `az login` with a user account with both owner and contributor permissions on the storage account, and used the following python code: 

```py
import requests
from datetime import datetime, timezone, timedelta
from azure.mgmt.storage import StorageManagementClient
from azure.identity import AzureCliCredential
from azure.storage.blob import generate_account_sas, ResourceTypes

# Generate a temporary and specific SAS token
azure_creds = AzureCliCredential()
storage_client = StorageManagementClient(azure_creds, AZURE_SUBSCRIPTION_GUID)
storage_keys = storage_client.storage_accounts.list_keys(RESOURCE_GROUP_NAME, STORAGE_ACCOUNT)
rr = requests.get("http://ipv4.icanhazip.com/")
my_ip = rr.text.rstrip("\n")
SAS_TOKEN = generate_account_sas(
    account_name=STORAGE_ACCOUNT,
    container_name=CONTAINER_NAME,
    start=datetime.now(timezone.utc) - timedelta(minutes=1),
    expiry=datetime.now(timezone.utc) + timedelta(hours=1),
    account_key=storage_keys.keys[0].value,
    permission="rl",
    ip=my_ip,
    resource_types=ResourceTypes(container=True, object=True, service=True),
)
```

**Expected behavior**

`FileSystemClient.get_paths().next()` should get a path from a ADLS container without throwing an error

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rakshith91** [comment]
@jdthorpe  Thanks for the issue - we will investigate this asap

@jalauzon-msft Can you take a look?

**Comment by vincenttran-msft** [comment]
Hi @jdthorpe Jason, I was looking into this issue alongside @jalauzon-msft and we were able to successfully reproduce your error.

After further testing, we have discovered that there is some odd service behavior with SAS tokens generated using `generate_account_sas()`. We noticed that you are using `generate_account_sas()` but also providing a `container_name`, and so below we have provided some workarounds that will allow you to generate a SAS token at a container-level (which seems to be sufficient for your use-case).

Note: In your provided code, we are unsure of your value for `ACCOUNT_URL`, but please note that when using the **Datalake** library, the `account_url` should be in the pattern of: _'https://<ACCOUNT_NAME>.**dfs**.core.windows.net'_, 
while using the **Blob** library should be in the pattern of _'https://<ACCOUNT_NAME>.**blob**.core.windows.net'_.

**DataLake Example:**
```
from azure.storage.filedatalake import generate_file_system_sas
sas_token = generate_file_system_sas(
        account_name=STORAGE_ACCOUNT,
        file_system_name=CONTAINER_NAME,
        expiry=datetime.now(timezone.utc) + timedelta(hours=1),
        credential=account_key,
        permission="rl",
    )
```

**Blob Example:**
```
from azure.storage.blob import generate_container_sas
sas_token = generate_container_sas(
        account_name=STORAGE_ACCOUNT,
        container_name=CONTAINER_NAME,
        expiry=datetime.now(timezone.utc) + timedelta(hours=1),
        account_key=account_key,
        permission="rl",
    )
```
And with the above samples, you can add back in any parameters necessary that I have omitted from the sample (i.e. ip=, etc.)

Hopefully this will help you resolve this issue, and we have already started an internal discussion with the service team regarding the odd service behavior with account SAS tokens and will update you here if we have any follow-ups.

Thanks!

**Comment by jdthorpe** [comment]
Thanks!  Yes, this resolves my specific issue.  

As a user, I'm often confused by the fact that the account url sometimes matters and sometimes doesn't, in part because of the fact that at least some of the functions in the filedatalake library are just thin wrappers around the blob library (for example, `DataLakeServiceClient.list_file_systems()` just calls `self._blob_service_client.list_containers()`) 

As an aside, I know that this is out of scope of this question, but it would be great if there were some hinting around the reason for auth errors.  For example, an error like ("requesting a resource from `dfs.core.windows.net` but the token is aurhorized for a resource in `blob.core.windows.net`" or "request was made from IP xx.xx.xx.xx but token is authorized for yy.yy.yy.yy" instead of the generic "Server failed to authenticate the request".  Helpful error messages like that could have saved me hours and hours of frustration (and would certainly save me hours in the future too).

**Comment by jalauzon-msft** [comment]
Hi @jdthorpe Jason, I'm glad you were able to resolve the issue and thanks for the additional feedback.

The interaction between blob and datalake can be a confusing topic but the general recommendation is to always use `blob.core.windows.net` URLs with the blob SDK and `dfs.core.windows.net` URLs with the datalake SDK. While some operations are interchangeable, this should ensure all requests work as expected. That being said, we are considering adding a feature in the near future where, at least the datalake SDK, will accept either a blob or dfs account URL and do the "translation" for the user. I believe other languages have a similar feature.

As for auth error messages, this is managed almost entirely by the service. Auth error messages can be tricky since there are security concerns with giving too much information in the error, etc. The service team has been working on improving the error messages where they can and has made some improvements in certain scenarios. Your points about non-matching SAS params (like IP) seem like valid areas for improvement. We can relay your feedback to the service team, thanks!
