### ISSUE TITLE
Key Vault link is broken

### ISSUE THREAD

**Issue by mmascolino** [Azure/azure-sdk-for-python#24128]
[Enter feedback here]
The key vault link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9755ce-e891-b94a-fc52-8e6b85586914
* Version Independent ID: 6a41e776-488a-8551-60f3-daae067492c8
* Content: [Reference](https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python&source=docs)
* Content Source: []()
* Git Login: **lmazuel**
* Microsoft Alias: **lmazuel**

**Comment by mccoyp** [comment]
Ah, I see -- the "Key Vault" service link on [this reference page](https://docs.microsoft.com/python/api/overview/azure/?view=azure-python&source=docs) is broken. Other services seem to be fine. @scbedd, do you know who would know more about this?

**Comment by scbedd** [comment]
@mccoyp Thank you for bringing this to my attention!

This is a real issue, and I believe I have a [PR](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1545) that addresses the problem. Hoping we can get the fix rolled out to `live` by EoD tomorrow.

**Comment by mccoyp** [comment]
Hi @mmascolino, thank you again for bringing this to our attention! The link in the reference page and table of contents has been fixed.

**Comment by danieljurek** [comment]
@scbedd, thanks for the fix!

@mmascolino -- Thanks for reporting! We published the updated link on Wednesday.
