### ISSUE TITLE
[Mgmt] broken link to quickstart guide in EventHubs README

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#24129]
Looks like the guickstart guide link under `USAGE` in the `azure-mgmt-eventhub` README is broken. https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/eventhub/azure-mgmt-eventhub

I _think_ it should be linking here? https://github.com/Azure-Samples/azure-samples-python-management/tree/main/samples/eventhub

**Comment by SatishBoddu-MSFT** [comment]
@swathipil 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by msyyc** [comment]
Fixed
