### ISSUE TITLE
Page not found for the quickstart guide link for data factory

### ISSUE THREAD

**Issue by rachhek** [Azure/azure-sdk-for-python#24124]
- **azure-mgmt-datafactory**: 
- **4.5.1 (2022-04-18)**: 
- **windows**:
- *3.7**: 

**Describe the bug**
The URL for the quickstart guide for the azure data factory library is no longer available on the readme page.

**To Reproduce**
1. Click on 'quickstart guide' on the readme page for azure-mgmt-datafactory

**Expected behavior**
2. Opens the quickstart page for azure-mgmt-datafactory

**Screenshots**
![image](https://user-images.githubusercontent.com/7693003/164449826-1d282410-622b-4441-83a9-68c252ee08c5.png)

**Additional context**

**Comment by rakshith91** [comment]
@rachhek Thanks for pointing it out - we will fix it soon

@msyyc Can you take a look?

**Comment by rakshith91** [comment]
@rachhek  Is this the link you are looking for?

https://docs.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-overview#provision-and-manage-azure-resources-with-management-libraries

**Comment by msyyc** [comment]
fixed: https://github.com/Azure/azure-sdk-for-python/issues/24139
