### ISSUE TITLE
List VNET through python returns null 

### ISSUE THREAD

**Issue by satya5186** [Azure/azure-sdk-for-python#24130]
**Describe the bug**
List VNET through python returns null 

***Exception or Stack Trace***
No stack trace but value returns NULL

**To Reproduce**
1. Just create a VNET 
2. execute this simple block of code

***Code Snippet***
Add the code snippet that causes the issue.

from azure.identity import AzureCliCredential
from azure.mgmt.resource import ResourceManagementClient

# create env variables for below:
# export AZURE_CLIENT_ID="" / thi is name in the sp
# export AZURE_CLIENT_SECRET="" / thi is password in the sp
# export AZURE_TENANT_ID="" / thi is the tenant in the sp

credential = AzureCliCredential()
subscription = "91b48fa1-bfc1-481a-b30e-c063117e7e79"

def azure_vnet_list():
    for resource_list in ResourceManagementClient(credential, subscription).resources.list():
        if resource_list.type == "Microsoft.Compute/virtualMachines":
            print(resource_list.name)

def main():
    azure_vnet_list()

if __name__ == "__main__":
    main()

**Expected behavior**

It should list the newly created VNET

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by BigCat20196** [comment]
Hi @satya5186, thanks for your feedback!  After investigation, if you want to list Vnet, you should use `Microsoft.Network/virtualNetworks` type instead of `Microsoft.Compute/virtualMachines`.

We prefer to use a dedicated SDK to manage resources, such as `azure-mgmt-network` and `azure-mgmt-compute`. You could easily install them by `pip`.
fyr: https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/compute/manage_virtual_machine.py

https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/network/virtual_network/manage_virtual_network.py

**Comment by satya5186** [comment]
Hi,

Thanks for the reply. Sorry I pasted the wrong code, I did use Microsoft.network to list vnets, it is not working

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BigCat20196** [comment]
Hi @satya5186, could you please use followed code to try?
```
from azure.identity import DefaultAzureCredential
from azure.mgmt.resource import ResourceManagementClient

credential = AzureCliCredential()
subscription = "91b48fa1-bfc1-481a-b30e-c063117e7e79"

def azure_vnet_list():
    for resource_list in ResourceManagementClient(credential, subscription).resources.list():
        if resource_list.type == "Microsoft.Network/virtualNetworks":
            print(f"{resource_list.name}")

def main():
    azure_vnet_list()

if __name__ == '__main__':
    main()
```

In addition, which version of `azure-mgmt-resource` do you use?

**Comment by satya5186** [comment]
I will try and let you know the result
________________________________
