### ISSUE TITLE
enable_node_public_ip doesn't have any effect in AmlCompute.provisioning_configuration due to old api version

### ISSUE THREAD

**Issue by pawel-f** [Azure/azure-sdk-for-python#24144]
- **Package Name**: azureml-core
- **Package Version**: 1.40.0.post2
- **Operating System**:Ubuntu 18.04.4 LTS
- **Python Version**: 3.7

**Describe the bug**
When trying to create a compute cluster in a secured Azure ML workspace (dedicated subnet), without assigning public IP to the cluster nodes
the cluster is always created with public IP option enabled.

**To Reproduce**
1. Assuming there is Azure ML workspace secured <vnet_resourcegroup_name,vnet_name,subnet_name>, try to create a AmlCompute as a compute target with enable_node_public_ip=False using following code:

```
from azureml.core.compute import AmlCompute
from azureml.core import Workspace, Dataset, Datastore, ComputeTarget  # noqa
from azureml.core.runconfig import RunConfiguration  # noqa


def main():
    workspace_name = "your workspace"
    subscription_id = "your subscription"
    resource_group = "your rg"
    vnet_resourcegroup_name = "your vnet rg"
    vnet_name = "your vnet"
    subnet_name = "your subnet"
    compute_name = "test01"

    workspace = Workspace.get(
        name=workspace_name,
        subscription_id=subscription_id,
        resource_group=resource_group,
    )

    compute_config = AmlCompute.provisioning_configuration(
        vm_size="STANDARD_DS2_V2",
        vm_priority="lowpriority",
        min_nodes=1,
        max_nodes=4,
        idle_seconds_before_scaledown="300",
        identity_type="SystemAssigned",
        enable_node_public_ip=False,
        vnet_resourcegroup_name=vnet_resourcegroup_name,
        vnet_name=vnet_name,
        subnet_name=subnet_name,
        remote_login_port_public_access='Disabled'
    )

    compute_target = ComputeTarget.create(
        workspace, compute_name, compute_config
    )
    compute_target.wait_for_completion(
        show_output=True, min_node_count=None, timeout_in_minutes=10
    )


if __name__ == "__main__":
    main()
```

2. Check in Azure Portal that the cluster has been created but doesn't have "No public IP" in Resource properties.

**Expected behavior**

Compute cluster should have been created with "No public IP" == true in Resource properties.

**Screenshots**
when using `python3.7/site-packages/azureml/_compute/_constants.py:MLC_WORKSPACE_API_VERSION = '2020-02-02'`
![image](https://user-images.githubusercontent.com/11706500/164720185-14b24471-b113-47f7-8dd7-f9c011485b78.png)

when using `python3.7/site-packages/azureml/_compute/_constants.py:MLC_WORKSPACE_API_VERSION = '2022-01-01-preview'`
![image](https://user-images.githubusercontent.com/11706500/164720206-c8db1ec2-1c1c-41e5-992c-61142988ff33.png)

**Additional context**
I found a solution to fix this issue. 
This is casued by the fact that azureml-core is using the old Azure ML REST API version:
python3.7/site-packages/azureml/_compute/_constants.py:MLC_WORKSPACE_API_VERSION = '2020-02-02'

When I manually changed it to the latest one: 
python3.7/site-packages/azureml/_compute/_constants.py:MLC_WORKSPACE_API_VERSION = '2022-01-01-preview'

the same code worked without issues and the compute cluster has been created with the option "No public IP"

**Comment by rakshith91** [comment]
@pawel-f  Thanks for the issue. We will take a look asap.

@msyyc Can you take a look?

**Comment by msyyc** [comment]
Hi @luigiw , please help on the issue

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by luigiw** [comment]
v1 SDK is in maintenance only mode in favor of the v2 SDK being GA. Please file an issue for v2 SDK if your requests stand for v2.
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-migrate-from-v1
