### ISSUE TITLE
Custom Vision - Unclear documentation - training type value in Python SDK and RestAPI

### ISSUE THREAD

**Issue by agonzalez-mob** [Azure/azure-sdk-for-python#24145]
**Is your feature request related to a problem? Please describe.**
I can't find documentation explaining what are the possible values for the 'training type' option when training a model in custom vision.

In the [Python SDK](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-customvision/azure.cognitiveservices.vision.customvision.training.models.trainingtype?view=azure-python), two training types can be found, `regular` and `advanced`.
Using the Rest API there's an option to specify the training type, but there's no explanation of what's the difference between them or how to use them when calling the [train project](https://southcentralus.dev.cognitive.microsoft.com/docs/services/Custom_Vision_Training_3.3/operations/5eb0bcc7548b571998fddee1) api.

**Describe the solution you'd like**
A clear and concise description of the `training type` variable in the documentation.

**Comment by rakshith91** [comment]
@agonzalez-mob Thanks for the issue. We will take a look asap.

**Comment by agonzalez-mob** [comment]
> @agonzalez-mob Thanks for the issue. We will take a look asap.

Thank you. I rephrased the question as it was poorly written.

**Comment by agonzalez-mob** [comment]
Any update guys?

**Comment by navba-MSFT** [comment]
@agonzalez-mob When training a model using the Custom Vision service in Azure Cognitive Services, there are two possible values for the 'training type' option:

"Regular": This is the standard training type, where the model is trained using the images and associated tags that you have uploaded to your project.

"Advanced": This is an advanced training type, where the model is trained using additional images and tags that you provide, as well as images and tags from a pre-existing model. This can help improve the accuracy of the model by leveraging the knowledge of the pre-existing model.

Both options are used to specify the type of training when creating a new custom model with the Azure Cognitive Services Custom Vision API.
