### ISSUE TITLE
ImportError: cannot import name 'HTTPPolicy' from partially initialized module 'azure.core.pipeline.policies'

### ISSUE THREAD

**Issue by keuj6** [Azure/azure-sdk-for-python#24155]
- **Package Name**: azure.ai.formrecognizer
- **Package Version**: 3.2.0b3
- **Operating System**: Windows 10 Enterprise
- **Python Version**: 3.9

**Describe the bug**
When trying to run the command `from azure.ai.formrecognizer import DocumentAnalysisClient`
following error is raised:
> ImportError: cannot import name 'HTTPPolicy' from partially initialized module 'azure.core.pipeline.policies' (most likely due to a circular import) (C:\Users\h500436\Documents\Python_git\Business_card_2_to_1\venv\lib\site-packages\azure\core\pipeline\policies\__init__.py)

**To Reproduce**
Follow the steps explained on [this tutorial page](https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/quickstarts/try-v3-python-sdk):
1. Run `pip install azure-ai-formrecognizer==3.2.0b3` in a virtual environement
2. Launch `python sample_analyze_business_cards.py` on the example file accessible [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_business_cards.py)
(or maybe just even try a `from azure.ai.formrecognizer import DocumentAnalysisClient` in a python console)

**Expected behavior**
See the output of the python script and NOT the error message described above.

**Screenshots**
n/a

**Additional context**
Thought it might be related to bug [#21766](https://github.com/Azure/azure-sdk-for-python/issues/21766) and to a lesser extent to bug [#16286](https://github.com/Azure/azure-sdk-for-python/issues/16286)

**Comment by tjprescott** [comment]
@keuj6 thank you for the repro! @catalinaperalta @kristapratico could one of you take a look at this?

**Comment by catalinaperalta** [comment]
@keuj6 thanks for reporting this. I just installed `azure-ai-formrecognizer==3.2.0b3` in a clean Python 3.9 environment and ran the sample. I did not manage to reproduce this error. Could you please share the output of `pip list` for your environment?

**Comment by keuj6** [comment]
Thx for looking into it @catalinaperalta,
My apologies for waisting your time m(_ _ )m. My venv was compromised. A fresh install solved the (non-)problem.
I close the issue

**Comment by catalinaperalta** [comment]
No worries! Feel free to reach out if you need to open other issues with our SDKs. :)
