### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.profiles'

### ISSUE THREAD

**Issue by stevenhurwitt** [Azure/azure-sdk-for-python#24151]
- **Package Name**:  azure-mgmt-resource
- **Package Version**: 21.0.0
- **Operating System**: Databricks cluster (linux)
- **Python Version**: 3.7.5

**Describe the bug**
I am trying to `import azure-mgmt-resource` and getting this error: 

`ModuleNotFoundError: No module named 'azure.profiles'`

**To Reproduce**
1. `import azure-mgmt-resource`

**Expected behavior**
Module to import successfully.

**Note**
The solution in [this duplicate issue](https://github.com/Azure/azure-sdk-for-python/issues/8497#) did not work for me.

**Comment by tjprescott** [comment]
@stevenhurwitt thank you for the report. @msyyc can you please investigate?

**Comment by msyyc** [comment]
Hi @stevenhurwitt, thanks for your feedback and we will fix it soon. Before that, please `pip install azure-common`, then `azure-mgmt-resource` shall work

**Comment by msyyc** [comment]
Hi @stevenhurwitt , according to this comment: https://github.com/Azure/azure-sdk-for-python/issues/8497#issuecomment-1106840964, I think the reason is that version of `azure-common` is too low. Please try the latest version.

**Comment by stevenhurwitt** [comment]
thanks for the help, that worked!
