### ISSUE TITLE
Catalog Python SDK returns bad request when calling entity delete by guids

### ISSUE THREAD

**Issue by yifan-zhou922** [Azure/azure-sdk-for-python#24158]
- **azure-purview-catalog**: 
- **1.0.0b3**: 
- **Windows**:
- **Python 3.9.1**: 

**Describe the bug**
Delete entities by guids will return Bad Request

**To Reproduce**
list_by_guids will return the details successfully but delete_by_guids will fail
<img width="676" alt="image" src="https://user-images.githubusercontent.com/78060542/164954901-e1869042-5516-41bd-8b83-2ae1a300fe17.png">

From the log, we can find the error as below:

**A message body reader for Java class java.util.List, and Java type java.util.List<org.apache.atlas.model.instance.AtlasObjectIdWithParentGuid>, and MIME media type application/octet-stream was not found.
The registered message body readers compatible with the MIME media type are:
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.json.impl.provider.entity.JSONJAXBElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONArrayProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider
  com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader
application/octet-stream ->
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.RenderedImageProvider
 (ContainerRequest:474)**

**Expected behavior**
Expected behavior should return 200 OK as the status code. 

**Screenshots**
Details of the failure message.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/78060542/164954929-651f3a4d-6d0f-43b2-a6f1-443559540855.png">

**Additional context**

**Comment by msyyc** [comment]
Hi @yifan-zhou922 , the error seems related with service server, please  follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to provide more detailed logs

**Comment by yifan-zhou922** [comment]
@msyyc here is the detailed logs.
2022-04-24 11:41:34,252 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://contosopurview.purview.azure.com/catalog/api/atlas/v2/entity/bulk?guid=REDACTED'
Request method: 'DELETE'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': '6fe037c7-c380-11ec-8f25-0050b6f1ab7d'
    'User-Agent': 'azsdk-python-purview-catalog/1.0.0b3 Python/3.9.1 (Windows-10-10.0.22000-SP0)'
    'Authorization': 'REDACTED'
No body was attached to the request
2022-04-24 11:41:34,261 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): contosopurview.purview.azure.com:443
2022-04-24 11:41:35,272 - urllib3.connectionpool - DEBUG - https://contosopurview.purview.azure.com:443 "DELETE /catalog/api/atlas/v2/entity/bulk?guid=c9b73cbd-8a4c-4b69-8173-fb50dafb2c8e HTTP/1.1" 400 None
2022-04-24 11:41:35,328 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 400
Response headers:
    'Date': 'Sun, 24 Apr 2022 03:41:34 GMT'
    'Content-Type': 'application/json'
    'Server': 'AzurePurview'
    'Cache-Control': 'no-store, must-revalidate, no-cache, max-age=0'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Expires': '0'
    'Access-Control-Allow-Headers': 'REDACTED'
    'Access-Control-Allow-Methods': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-request-id': '6fe037c7-c380-11ec-8f25-0050b6f1ab7d'
    'X-Frame-Options': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Content-Security-Policy': 'REDACTED'
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    main()
  File "D:\catalogTest.py", line 20, in main
    print(client.entity.delete_by_guids(guids=entities))
  File "C:\Users\yifanzhou\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\tracing\decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\yifanzhou\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\purview\catalog\operations\_operations.py", line 4406, in delete_by_guids
    raise HttpResponseError(response=response)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"requestId":"6fe037c7-c380-11ec-8f25-0050b6f1ab7d","errorCode":"RequestInvalid","errorMessage":"Request is not recognized. Please verify the HTTP method, header or URL"}
>>>

**Comment by yifan-zhou922** [comment]
@msyyc here is the detailed logs for delete by guids.
2022-04-24 11:41:34,252 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://{accountName}.purview.azure.com/catalog/api/atlas/v2/entity/bulk?guid=REDACTED'
Request method: 'DELETE'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': '{id}'
    'User-Agent': 'azsdk-python-purview-catalog/1.0.0b3 Python/3.9.1 (Windows-10-10.0.22000-SP0)'
    'Authorization': 'REDACTED'
No body was attached to the request
2022-04-24 11:41:34,261 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): {accountName}.purview.azure.com:443
2022-04-24 11:41:35,272 - urllib3.connectionpool - DEBUG - https://{accountName}.purview.azure.com:443 "DELETE /catalog/api/atlas/v2/entity/bulk?guid=c9b73cbd-8a4c-4b69-8173-fb50dafb2c8e HTTP/1.1" 400 None
2022-04-24 11:41:35,328 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 400
Response headers:
    'Date': 'Sun, 24 Apr 2022 03:41:34 GMT'
    'Content-Type': 'application/json'
    'Server': 'AzurePurview'
    'Cache-Control': 'no-store, must-revalidate, no-cache, max-age=0'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Expires': '0'
    'Access-Control-Allow-Headers': 'REDACTED'
    'Access-Control-Allow-Methods': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-request-id': '{id}'
    'X-Frame-Options': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Content-Security-Policy': 'REDACTED'
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    main()
  File "D:\catalogTest.py", line 20, in main
    print(client.entity.delete_by_guids(guids=entities))
  File "C:\Users\yifanzhou\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\tracing\decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\yifanzhou\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\purview\catalog\operations\_operations.py", line 4406, in delete_by_guids
    raise HttpResponseError(response=response)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"requestId":"{id}","errorCode":"RequestInvalid","errorMessage":"Request is not recognized. Please verify the HTTP method, header or URL"}

**Comment by msyyc** [comment]
Hi @yifan-zhou922 , the log shows that the request corresponds with swagger definition. Could you check which part of request in is not right?

**Comment by yifan-zhou922** [comment]
Root cause discovered. Closing the issue.
