### ISSUE TITLE
`BlobServiceClient.list_containers()` fails when using a sas token generated using `generate_account_sas`

### ISSUE THREAD

**Issue by jdthorpe** [Azure/azure-sdk-for-python#24156]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.12.0b1
- **Operating System**: OSX
- **Python Version**: 3.9

**Describe the bug**

`BlobServiceClient.list_containers()` fails when using an account SAS token generated using `generate_account_sas`

**To Reproduce**

If I create an account SAS token like this: 

```py
from datetime import datetime, timezone, timedelta
from azure.storage.blob import BlobServiceClient, generate_account_sas

ACCOUNT_KEY = "<< account key >>"
ACCOUNT_NAME = "<< account name >>"
start_time = datetime.now(timezone.utc) - timedelta(minutes=1)
expiry_time = datetime.now(timezone.utc) + timedelta(hours=1)
ACCOUNT_SAS_TOKEN = generate_account_sas(
    account_key=ACCOUNT_KEY,
    account_name=ACCOUNT_NAME,
    start=start_time,
    expiry=expiry_time,
    permission="rl",
    resource_types="sco",
)
BLOB_ACCOUNT_URL = "https://{account}.blob.core.windows.net/".format(
    account=ACCOUNT_NAME
)
```

`BlobServiceClient.list_containers()` fails when using the account sas token like so:

```py
BSC = BlobServiceClient(account_url=BLOB_ACCOUNT_URL, credential=ACCOUNT_SAS_TOKEN)
container_list = BSC.list_containers()
container_list.next()
# *** azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

Even though it works just fine with the account key:

```py
BSC = BlobServiceClient(account_url=BLOB_ACCOUNT_URL, credential=ACCOUNT_KEY)
container_list = BSC.list_containers()
container_list.next() # no errors
```

**Expected behavior**

`BlobServiceClient.list_containers()` should work with an account key generated by `generate_account_sas`

**Screenshots**
N/A

**Additional context**
N/A

**Comment by tjprescott** [comment]
@jdthorpe thank you for reaching out! @jalauzon-msft could you take a look at this?

**Comment by jalauzon-msft** [comment]
Hi @jdthorpe Jason, thanks so much for trying out the beta version and reporting this issue! It turns out this is an SDK bug that was introduced in the latest beta release. We will work on getting this fixed ASAP and it will be fixed in our next production release.

For now, reverting back to 12.11.0 should fix the issue for you.

**Comment by jdthorpe** [comment]
Thanks! That's good information and should solve my issue.

FYI, I didn't intend to install a beta version.  I just uses pip install without a version number.  Is that intended? Normally I think of beta versions as something you have to opt into.

**Comment by jalauzon-msft** [comment]
@jdthorpe, Hmm not sure why that would happen. Typically `pip` has you opt-in to pre-release installs and it does look like `12.12.0b1` is marked as pre-release on [PyPi](https://pypi.org/project/azure-storage-blob/12.12.0b1/).

**Comment by jdthorpe** [comment]
Looks like the beta version of azure-blob-storage is [explicitly listed in the dependency range](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/setup.py#L80) of azure-storage-file-datalake, which is likely how I got the beta version of azure-storage-blob.

**Comment by jalauzon-msft** [comment]
@jdthorpe, the beta version is listed as a dependency in `main` but was only released for the beta version of datalake. Did you happen to install the current beta version of datalake?

**Comment by jdthorpe** [comment]
Looking back, I may have (re)installed the ADLS library with the `--pre` flag to resolve a different issue, which would explain how I got the preview version of ADLS which depended on the beta version of azure-storage-blob.  Thanks.
