### ISSUE TITLE
Cognitive Services: Custom Vision - Unclear documentation - GetIterationPerformance RestAPI

### ISSUE THREAD

**Issue by agonzalez-mob** [Azure/azure-sdk-for-python#24164]
**Is your feature request related to a problem? Please describe.**
There's no explanation of the possible/default values of the parameters used in [GetIterationPerformance](https://southcentralus.dev.cognitive.microsoft.com/docs/services/Custom_Vision_Training_3.3/operations/5eb0bcc7548b571998fdded0), in particular `threshold` and `overlapThreshold`.

For example: 
```
threshold (optional)    number    Format - float. The threshold used to determine true predictions.
overlapThreshold (optional)   number   Format - float. If applicable, the bounding box overlap threshold used to determine true predictions.
```
What are the ranges of the threshold 0-100, 0-1? what are the default values?

This issue where there's no description of the default and accepted values for parameters seems to be an issue seen across the whole Python SDK/API documentation, e.g. [this example](https://github.com/Azure/azure-sdk-for-python/issues/24145).

**Describe the solution you'd like**
A clear and concise description of the default and accepted values for GetIterationPerformance and ideally for all optional parameters across the several versions of the documentation Python SDK/Rest API, etc....

ps.- After double-checking I fear that this might not be the best place for this ticket as it refers to the RestAPI instead of the Python SDK. Please do feel free to push me in the right direction.

**Comment by tjprescott** [comment]
@agonzalez-mob thank you for your inquiry. Someone from the CXP team will route your question to the appropriate service team.

**Comment by RakeshMohanMSFT** [comment]
@agonzalez-mob Thank you for reaching out, we are looking into it.

**Comment by agonzalez-mob** [comment]
@RakeshMohanMSFT thank you. I just modified the question a bit to include `overlapThreshold` in the example given in the original question.
