### ISSUE TITLE
`Explore the Management APIs` button links to a 404

### ISSUE THREAD

**Issue by tevoinea** [Azure/azure-sdk-for-python#24169]
The link from this button is broken.
<img width="219" alt="image" src="https://user-images.githubusercontent.com/58236992/165148144-ba01d879-3a71-466c-b828-3c93c06958b2.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc1c70b-6ce5-8115-921d-8db80c1d43db
* Version Independent ID: 5b033609-afc0-a8e0-4059-89e77bbcd28d
* Content: [Azure Virtual Machine libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/compute?view=azure-python)
* Content Source: [docs-ref-services/latest/compute.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/compute.md)
* Service: **compute**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @lisawong19
* Microsoft Alias: **ramyar**

**Comment by tjprescott** [comment]
Hi @tevoinea thanks for reporting this! @msyyc could your route this to the appropriate team?

**Comment by navba-MSFT** [comment]
@tevoinea Thanks for reaching out to us and sharing this feedback. This PR https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1543 has been created to fix this issue. It is currently under Review phase.

**Comment by tevoinea** [comment]
Awesome, thank you both! Closing the issue since the fix is in PR.
