### ISSUE TITLE
Question: Equivalent to legacy BlockBlobService.create_blob_from_path() in V12?

### ISSUE THREAD

**Issue by EFulmer** [Azure/azure-sdk-for-python#24171]
Hello there! 

I want to upload a Parquet file to Azure Blob Storage. However, when I modify the examples that use `BlobClient.upload_blob`, I get a `UnicodeDecodeError`, implying `upload_blob` is expecting text data. Example & specific error below:

```python
from azure.identity import ClientSecretCredential
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient, __version__
import pandas as pd
import pyspark
from pyspark.sql import SparkSession


spark_session = SparkSession.builder.appName("Test").getOrCreate()

service_principal_credential = ClientSecretCredential(tenant_id="REDACTED",
                                                      client_id=spark_session.conf.get("REDACTED"),
                                                      client_secret =spark_session.conf.get("REDACTED")
                                                     )
client = ContainerClient(account_url="REDACTED", container_name="REDACTED", credential=service_principal_credential)

df = pd.DataFrame(
  {
    "id": list(range(5)),
    "a": random.choices(ascii_lowercase, k=5),
    "b": random.choices(ascii_lowercase, k=5),
  }, 
).set_index("id")

df.to_parquet("test.parquet")
blob_client = client.get_blob_client("test.parquet")
with open("test.parquet", "r") as f:
    blob_client.upload_blob(name=file_name, data=f, blob_type="BlockBlob")
```

I found (don't remember how, my apologies) that the legacy SDK had a class named `BlockBlobService` with a method `create_blob_from_path` ([doc](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blockblobservice.blockblobservice?view=azure-python-previous#azure-storage-blob-blockblobservice-blockblobservice-create-blob-from-path)) that seems like it would accomplish this, but it's from the legacy, deprecated SDK. Is there any way to accomplish this using the current version of the SDK? 

Thanks for your help.

**Comment by tjprescott** [comment]
Hi @EFulmer, thanks for reach out! 
@jalauzon-msft could you take a look at this?

**Comment by jalauzon-msft** [comment]
Hi @EFulmer Eric, I believe you may just need to open your file in binary mode using "r**b**" so that we do not attempt any decoding on the bytes.
```python
with open("test.parquet", "rb") as f:
```

This also matches the [legacy implementation](https://github.com/Azure/azure-storage-python/blob/4306898850dd21617644fc537a57d025e833db74/azure-storage-blob/azure/storage/blob/blockblobservice.py#L483) :)

Hopefully that helps, thanks!

**Comment by navba-MSFT** [comment]
@EFulmer Could you please let us know if you had a chance to look at the above comment and try out the suggestion ? Awaiting your reply.

**Comment by EFulmer** [comment]
Hi @navba-MSFT & @jalauzon-msft, that worked! Thank you so much!
