### ISSUE TITLE
azure-identity: Version conflict with msal-extensions requirement with azure-cli-core

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-sdk-for-python#24188]
The latest version of `azure-cli-core` 2.36.0 just bumped its dependency of `msal-extensions` to 1.0.0 meaning that both `azure-cli-core` and `azure-identity` can no longer be co-installed on Linux distributions which ship the Azure SDK and CLI as packages.

Could the version dependency of `azure-identity` on `msal-extensions` be bumped to 1.0.0?

**Comment by glaubitz** [comment]
Ah, that has already happened in  #23932.

Could the new version be released?

**Comment by xiangyan99** [comment]
We are working with the CLI team to make it happen.

**Comment by jiasli** [comment]
Pending on https://github.com/Azure/azure-sdk-for-python/pull/23932 to be released.

**Comment by xiangyan99** [comment]
azure-identity 1.10.0 with msal-extensions 1.0.0 support has been released.
