### ISSUE TITLE
OpenTelemetry gRPC exporter fails because SpanKind is None

### ISSUE THREAD

**Issue by cpiment** [Azure/azure-sdk-for-python#24189]
- **Package Name**: azure-core-tracing-opentelemetry
- **Package Version**: 1.0.0b9
- **Operating System**: Windows Server 2012 R2
- **Python Version**: 3.8.10

**Describe the bug**
When trying to use opentelemetry-exporter-otlp-proto-grpc to export OpenTelemetry traces created by Azure Python SDK, some traces fail to get exported because the generated OpenTelemetry Spans are not created with a valid SpanKind (is set to None)

```
Exception while exporting Span batch.
Traceback (most recent call last):
  File "F:\Repo vm-deploy\venv\lib\site-packages\opentelemetry\sdk\trace\export\__init__.py", line 358, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "F:\Repo vm-deploy\venv\lib\site-packages\opentelemetry\exporter\otlp\proto\grpc\trace_exporter\__init__.py", line 291, in export
    return self._export(spans)
  File "F:\Repo vm-deploy\venv\lib\site-packages\opentelemetry\exporter\otlp\proto\grpc\exporter.py", line 293, in _export
    request=self._translate_data(data),
  File "F:\Repo vm-deploy\venv\lib\site-packages\opentelemetry\exporter\otlp\proto\grpc\trace_exporter\__init__.py", line 277, in _translate_data
    f"SPAN_KIND_{sdk_span.kind.name}",
AttributeError: 'NoneType' object has no attribute 'name'
```

The spans can be exported to ConsoleSpanExporter and they look like this:

```json
{
    "name": "VirtualMachinesOperations.get",
    "context": {
        "trace_id": "0xc2b6ac1e000327beb3a5d257d1baaaa3",
        "span_id": "0x2517d83d04756b74",
        "trace_state": "[]"
    },
    "kind": "None",
    "parent_id": null,
    "start_time": "2022-04-26T11:18:07.412171Z",
    "end_time": "2022-04-26T11:18:07.809196Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {},
    "events": [],
    "links": [],
    "resource": {
        "service.name": "vm-deploy",
        "service.version": "1.0.0",
        "deployment.environment": "dev"
    }
}
```

The issue can be traced back to this line:

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/tracing/decorator.py#L81

Where no kind is specified, and when the OpenTelemetrySpan is instantiated, `None` is assigned to the kind in this line:

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py#L67

And then this check passes because `value` exists (although is assigned to `None`)

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py#L69

I think that when the OpenTelemetrySpan is instantiated, SpanKind should never default to None, since it is not a SpanKind supported by OpenTelemetry API: https://opentelemetry.io/docs/reference/specification/trace/api/#spankind

**To Reproduce**
I will try to create a minimal example of the error and link it to the issue as soon as possible.

**Expected behavior**
Spans should be exported to gRPC exporter with no errors

**Screenshots**
N/A

**Additional context**
OpenTelemetry documentation states [in this link](https://opentelemetry.io/docs/reference/specification/trace/api/#span-creation) that SpanKind should default to `SpanKind.Internal`.

If I change this line 

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py#L67

to `OpenTelemetrySpanKind.INTERNAL` 

the exporter works as expected.

**Comment by tjprescott** [comment]
@cpiment thank you for the issue and detailed repro! @xiangyan99 can you please take a look at this?

**Comment by cpiment** [comment]
I have created a minimal repo with steps to reproduce the issue: https://github.com/cpiment/otel-azure-grpc

Please let me know if you need more help

**Comment by cpiment** [comment]
Hi @rakshith91, do you have any news regarding this issue? Were you able to reproduce it? Thanks in advance for your help!!

**Comment by lmazuel** [comment]
Hi @cpiment 

Based on your stacktrace, the likely cause for me is that GRPC considers `kind` required, see the line in code here:
https://github.com/open-telemetry/opentelemetry-python/blob/739760586ade075b18d29fa58ce7ac3dbae90869/exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py#L277

There are two things here:
- Maybe indeed `kind` is required, and then this is a bug on our side and you find a scenario where we don't set `kind` but we should have
- Maybe `kind` is optional, or at least the GRPC exporter code should be robust to `kind` being `None`. Could you open a bug to  https://github.com/open-telemetry/opentelemetry-python and clarify that you can't export if one of the span as a kind being `None`? I'm curious if what they will say on your issue.

On a side note, thank you a lot for the reproduction repo, this will be extremely helpful to track down the issue.

**Comment by lmazuel** [comment]
By the way, your change in azure-core is interesting:
https://github.com/Azure/azure-sdk-for-python/blob/cb41edef66c7b1cf2b3d4234da68bb212af3ac3e/sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py#L67-L70

When you change line 67 to `INTERNAL`, but you didn't get an exception before from line 68, it means indeed we consider kind to be optional. You think will change the semantic to "If Azure SDK do not provide a kind, force it to Internal". I'm not sure yet if this is the semantic we want to commit to. This is an interesting question.

**Comment by cpiment** [comment]
> May I ask you an experiment? Keep line 67 to None, but change line 69 to if kind is None:. You should now receive an exception with a stacktrace that tells you what code is trying to create a span with no kind. Could you share that stacktrace?

I've changed this line as suggested and now the exception is this one:

```
Traceback (most recent call last):
  File "otel-azure-grpc.py", line 55, in <module>
    vm_name=VM_NAME
  File "/home/carlos/azure-python/otel-azure-grpc/venv/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 81, in wrapper_use_tracer
    with span_impl_type(name=name) as span:
  File "/home/carlos/azure-python/otel-azure-grpc/venv/lib/python3.7/site-packages/azure/core/tracing/ext/opentelemetry_span/__init__.py", line 71, in __init__
    raise ValueError("Kind {} is not supported in OpenTelemetry".format(value))
ValueError: Kind None is not supported in OpenTelemetry
```

This exception does not crash the program, and it tries to send to the exporter other Spans that have the `kind` set. If I don't modify the line, the program crashes without trying to export any Span.

Thanks for your time and your help!

**Comment by lmazuel** [comment]
Sorry for the late answer. Your stacktrace helps, as I see it's coming from the decorator of the function. I assume seeing `vm_name=VM_NAME` you're using some package like `azure-mgmt-compute` ? Knowing what is line 55 would be helpful to track the caller.

@lmolkova , for the logical span we create for a function call, what kind should we use for that span? Client? Producer? Internal?

**Comment by lmolkova** [comment]
@lmazuel logical call spans should have `Internal` kind

**Comment by cpiment** [comment]
Hi @lmazuel,

The line 55 is from this reproducer repo:

https://github.com/cpiment/otel-azure-grpc

You can clone it and reproduce the issue. As you guessed, in this example I'm using `azure-mgmt-compute`, but this happens with other packages as well.

Thanks for your help!

**Comment by cpiment** [comment]
Hi @lmazuel, sorry for the delay. I have just tested it and it works flawlessly :smile:  Thanks!

**Comment by lmazuel** [comment]
PR has been merged, will be released next week (probably Wednesday)
