### ISSUE TITLE
Allow merging multiple datasets in a pipeline step

### ISSUE THREAD

**Issue by davystrong** [Azure/azure-sdk-for-python#24191]
In Azure ML pipelines, I would like to keep various smaller file datasets each with specific characteristics and then merge them into a single `Dataset` object in a pipeline step.

I would like a new method for the `Dataset` object that allows me to chain it with another `Dataset` (similar to the [chain](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.chain) function in Rust's iterator).

I don't think there are any other ways of doing this, but I'd love to be proved wrong.

**Comment by tjprescott** [comment]
@bandsina can you please take a look at this issue?

cc/ @Azure/ml-github-maintainers

**Comment by dkmiller** [comment]
cc @jfomhover , @wayliums . This may be worth considering as a built-in component in the upcoming registry.
