### ISSUE TITLE
error creating a firewall rule on SQL server using python package azure-mgmt-sql

### ISSUE THREAD

**Issue by alonzo86** [Azure/azure-sdk-for-python#24226]
**Describe the bug**
error creating a firewall rule on SQL server using python package azure-mgmt-sql

***Exception or Stack Trace***
  "site-packages/azure/mgmt/sql/operations/_firewall_rules_operations.py", line 174, in create_or_update
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidApiVersionParameter) The api-version '2020-11-01-preview' is invalid. The supported versions are '2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

***Code Snippet***
from azure.identity import ClientSecretCredential
from azure.mgmt.sql import SqlManagementClient

app_creds = ClientSecretCredential(tenant_id, client_id, client_secret)
client = SqlManagementClient(app_creds, subscription_id)
params = {
        'name': firewall_rule_name,
        'start_ip_address': start_ip_address,
        'end_ip_address': end_ip_address
    }
client.firewall_rules.create_or_update(resource_group, server_name, firewall_rule_name, params)

**Expected behavior**
firewall rule should be created on SQL server

**Setup (please complete the following information):**
 - Python Version: Python 3.7
 - SDK Version: azure-mgmt-sql 2.0.0 (tested also on 3.0.0 and 3.0.1)

**Comment by yochananrachamim** [comment]
Tried to follow the repro steps using latest Python (3.10.4) using the most recent management package (3.0.1)
and was not able to reproduce the problem as described. 

@alonzo86 - have you tried using more recent Python?

**Comment by alonzo86** [comment]
after retesting this issue, it seems that it's no longer reproducible, probably something temporary.
tested again with original version of the package azure-mgmt-sql 2.0.0
