### ISSUE TITLE
Explain that pipelineRun variables are optional

### ISSUE THREAD

**Issue by IvoMerchiers** [Azure/azure-sdk-for-python#24229]
Variables will only be returned if the server has them available.
This can be confusing for a developer if they rely on the values being available. Therefore it would be useful if this is added in the documentation.

Example:
When the 'status' is 'Queued', then the 'duration_in_ms' will not be available in the response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3930f0c-dd61-6954-4947-584d36cb6331
* Version Independent ID: 4b49dc93-75ee-6a7d-6ea8-987944940d71
* Content: [azure.mgmt.datafactory.models.PipelineRun class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.models.pipelinerun?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-datafactory/azure.mgmt.datafactory.models.PipelineRun.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-datafactory/azure.mgmt.datafactory.models.PipelineRun.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by tjprescott** [comment]
@IvoMerchiers thanks for the report! @msyyc could you route to the appropriate team for action?

**Comment by Wzb123456789** [comment]
Hi @IvoMerchiers, thank you for your feedback.

According to the issue information you provided, I can't identify what the problem is, please provide more detailed code examples and issue information to solve your problem, refer to this [issue](https://github.com/Azure/azure-sdk-for-python/issues/21587)
