### ISSUE TITLE
Utilize lease containers when consuming the change feed in CosmosDB

### ISSUE THREAD

**Issue by JarroVGIT** [Azure/azure-sdk-for-python#24249]
**Is your feature request related to a problem? Please describe.**
When creating a consumer that listens to the change feed of CosmosDB, the python sdk doesn’t offer any way to use lease containers to store state of the consumer(s). This prevents using this feature in python, as there is no resilience or scalability.

**Describe the solution you'd like**
A similar implementation as found in the .NET sdk, where the name of the lease container is an parameter in the method returning the iterator with changes. 

**Describe alternatives you've considered**
The alternative is to custom build this functionality every time I am writing a consumer. 

**Additional context**
N/A

**Comment by tjprescott** [comment]
Thanks for the question @JarroVGIT. @simorenoh can you comment on this?

**Comment by simorenoh** [comment]
@JarroVGIT Thank you for using our SDK and for opening this issue. This feature you mentioned is part of a larger feature outlined in the limitations that are present in the repo's README.md file, under the Change Feed Processor bullet points. As of today, only the .NET and Java SDKs have these capabilities.

We also do not have a timeline for when this work will happen for this SDK unfortunately. Do let me know if this answers your question.

**Comment by JarroVGIT** [comment]
@simorenoh Thanks for your reply and sorry to hear this feature will be exclusive to the .NET and Java SDK's for the time being. I will close this feature request :) Keep up the great work!
