### ISSUE TITLE
400 bad request : Unable to connect with FileShare in python for Upload

### ISSUE THREAD

**Issue by praveenRI007** [Azure/azure-sdk-for-python#24255]
I followed up a tutorial from MS docs for Uploading a file to Azure File share [https://docs.microsoft.com/en-us/python/api/overview/azure/storage-file-share-readme?view=azure-python](url) , faced a Bad request 400 error .

Please specify the path_name format i have to define in the function parameter

**Comment by tjprescott** [comment]
Hi @praveenRI007 thanks for reaching out! @jalauzon-msft could you take a look at this?

**Comment by jalauzon-msft** [comment]
Hi @praveenRI007, could you please share the following information so we can better assist you? Thanks!

- A code sample of what you are trying to do.
- The exact error/exception you are receiving.
- The version of the file-share SDK and the version of Python you are using.

**Comment by praveenRI007** [comment]
Hi @tjprescott ,

- Here is the sample code :
   from azure.storage.fileshare import ShareFileClient

   file_client = ShareFileClient.from_connection_string(conn_str="<connection_string>", share_name="my_share", 
   file_path="my_file")

   with open("./SampleSource.txt", "rb") as source_file:
       file_client.upload_file(source_file)

-  The exception that i got:
![image](https://user-images.githubusercontent.com/55011941/166089170-60fb9b24-6332-45f8-9c66-7bb59861ddb2.png)


- Version of SDK iam using :
![image](https://user-images.githubusercontent.com/55011941/166089239-9e594fd9-066f-4d69-9927-d8ada8595f26.png)
Python Version 3.7 (64-bit)

Iam not sure about the syntax of file_path that i had used is correct : please clarify what could be the error here

**Comment by praveenRI007** [comment]
Hi @navba-MSFT 
![image](https://user-images.githubusercontent.com/55011941/166197901-42f9efc5-ce20-4c06-bd4b-eae80dbc5ada.png)
I am getting this error now , can you please provide solution for this asap

**Comment by navba-MSFT** [comment]
@praveenRI007 Thanks for sharing the error details. I looked at the backend logs, I see that your request URL (file path) was incorrect. I could see **//** in the request URL file path after the ShareName. Could you please fix that and check if that helps ? Awaiting your reply.

Your Request URL: https://XXXXXXXXXX.file.core.windows.net:443/archive-attachments//DTS/Archival/CIS

Syntax: https://MySTorageAccount.file.core.windows.net/ShareName/DirectoryName1/DirectoryName2/File.txt

**Comment by praveenRI007** [comment]
@navba-MSFT Thanks ! it worked :)

**Comment by navba-MSFT** [comment]
@praveenRI007 Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
