### ISSUE TITLE
Is there a way to create a route table for associated virtual network?

### ISSUE THREAD

**Issue by PetreBogdan** [Azure/azure-sdk-for-python#24266]
I need to create a route table for an existing virtual network using python. I don't have access to the Azure interface but I want to make an automated script to create a virtual network with associated subnet and route table.
I managed to create the virtual network and subnet but no clue for route table. I followed this example here: https://docs.microsoft.com/en-us/python/api/overview/azure/network?view=azure-python

**Comment by swathipil** [comment]
@PetreBogdan - Thanks for your question! Tagging the right people so they can address this asap!

**Comment by navba-MSFT** [comment]
@PetreBogdan Thanks for reaching out to us. Did you refer the [RoutesOperations ](https://raw.githubusercontent.com/Azure/azure-sdk-for-python/1818ade4194d536c92cc46ae955cba5c741e5008/sdk/network/azure-mgmt-network/azure/mgmt/network/v2021_08_01/operations/_operations.py)class ? You should not instantiate this class directly. Instead, you should create a Client instance that instantiates it for you and attaches it as an attribute.

 Also refer the [networkMgmtClient route_tables property.](https://github.com/Azure/azure-sdk-for-python/blob/1818ade4194d536c92cc46ae955cba5c741e5008/sdk/network/azure-mgmt-network/azure/mgmt/network/_network_management_client.py#L6129)

Hope this helps.

**Comment by PetreBogdan** [comment]
But is there a way to associate a Route Table class to a Virtual Network? I see that neither of those has an attribute or a variable to link them together.

**Comment by navba-MSFT** [comment]
@PetreBogdan Apologies for the late reply. Subnet Class in Azure Python SDK has route_table as a Parameter. Refer [this](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2018_01_01.models.subnet?view=azure-python).

If you have created the route table and Vnet / Subnet, all you have to do is:
a)	update the Subnet class, and supply the route_table parameter and then 
b)	 just call subnets.create_or_update with the right set of parameters, something like
network_client.subnets.create_or_update(resource_group_name, vnet_name, subnet_name, subnet_data)

Hope this helps.

**Comment by PetreBogdan** [comment]
Thank you for the reply, I have one last issue and I don't know if it's a bug or not. I created a route_table with network_client.route_tables.begin_create_or_update and it has the parameters: (resource_group_name, name, parameters). I gave it a name parameter but after creating it and print it, the name is None. Name show up only in id. Is it something that I'm missing?

**Comment by navba-MSFT** [comment]
@PetreBogdan I haven't tried this yet. But as a quick suggestion, I would recommend checking from [this REST API](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/route-tables/get#routetable) to confirm if the **name** is returned in its response. Hope this helps.

Refer [get](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_06_01.operations.routetablesoperations?view=azure-python#azure-mgmt-network-v2020-06-01-operations-routetablesoperations-get) operation | This Gets the specified route table.
-- | --
You can refer the Returns and ReturnType of this operation.

**Comment by PetreBogdan** [comment]
This is the reponse: {'additional_properties': {}, 'id': '/subscriptions/{subscription_id}/resourceGroups/capic-ui-automation/providers/Microsoft.Network/routeTables/route-table-test', 'name': None, 'type': None, 'location': None, 'tags': None, 'etag': None, 'routes': None, 'subnets': None, 'disable_bgp_route_propagation': None, 'provisioning_state': None, 'resource_guid': None}

I called method function like this: 

def create_route_table(self, route_table_name, location):
            self.network_client.route_tables.begin_create_or_update(
            self.service_group_name,
            name,
            {
            "location": self.location,
            }
        )

**Comment by navba-MSFT** [comment]
@PetreBogdan Thanks for your reply. As mentioned in my above comment, did you try to call the [get](https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_06_01.operations.routetablesoperations?view=azure-python#azure-mgmt-network-v2020-06-01-operations-routetablesoperations-get) operation to fetch the routable table details and check the response ?

**Comment by PetreBogdan** [comment]
For now I'm looking for a way to make calls in the API.  As I mentioned in the first post, I don't have access to the Azure interface and the only tokens I have are client_id and secret_id, subscription_id and tenant_id. It seems that postman needs something else form those, right?

**Comment by PetreBogdan** [comment]
Ok so I called the GET operation for route table and the response is:
{'additional_properties': {}, 'id': '/subscriptions/{subscription_id}/resourceGroups/{project_name}/providers/Microsoft.Network/routeTables/route-table-test', 'name': 'route-table-test', 'type': 'Microsoft.Network/routeTables', 'location': 'centralus', 'tags': None, 'etag': 'W/"ecba362c-74cd-414d-8fb4-44b04a4ec4e4"', 'routes': [], 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x0000015181EAD550>], 'disable_bgp_route_propagation': False, 'provisioning_state': 'Succeeded', 'resource_guid': 'c25329fe-1a2a-48e5-9d62-d0f8aecd39f3'}

It seems that the name is there but I also I tried to call subnet.route_table and the response was this:

{'additional_properties': {}, 'id': '/subscriptions/{subscription_id}/resourceGroups/{project_name}/providers/Microsoft.Network/routeTables/route-table-test', 'name': None, 'type': None, 'location': None, 'tags': None, 'etag': None, 'routes': None, 'subnets': None, 'disable_bgp_route_propagation': None, 'provisioning_state': None, 'resource_guid': None}

It seems the id is the same but none of the name and location attributes. They have None.

**Comment by navba-MSFT** [comment]
@PetreBogdan Thanks for getting back. I am adding the Service Team to take a look at the name and location value being returned as None issue. See: 'name': None, 'location': None,

@vnetsuppgithub Could you please look into this issue and provide an update ?

**Comment by PetreBogdan** [comment]
Are there any updates on this issue?

**Comment by swathipil** [comment]
Hey @navba-MSFT - It looks like [@vnetsupp](https://github.com/vnetsuppgithub) hasn't alerted anyone. Do you know of anyone else who might be able to look into this? Thanks!

**Comment by navba-MSFT** [comment]
@swathipil @PetreBogdan Thanks for reaching out. I will check with the team offline and update this thread once, I hear from them. However, I don't have an ETA on when I might hear from them.
