### ISSUE TITLE
ACI  Python SDK samples are outdated

### ISSUE THREAD

**Issue by thec0dewriter** [Azure/azure-sdk-for-python#24265]
Hello,
Currently the examples seems to be outdated for the current version of SDK.
For example in the samples appear:
```
  # Create the container group
    aci_client.container_groups.create_or_update(resource_group.name,
                                                 container_group_name,
                                                 group)

```
while the SDK contains only ``` begin_create_or_update ``` method
https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerinstance/azure.mgmt.containerinstance.operations.containergroupsoperations?view=azure-python#azure-mgmt-containerinstance-operations-containergroupsoperations-begin-create-or-update

The same issue is also present in the git repo sources:
https://github.com/Azure-Samples/aci-docs-sample-python/blob/ee616cae57b389d5c6a98e0ffcbf9ca769c268f6/src/aci_docs_sample.py#L131

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e732e187-7ff4-bd4f-9aad-44953af44a86
* Version Independent ID: d4baa2d6-8f2f-ed76-e890-3240065f485a
* Content: [Azure Container Instances libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/container-instance?view=azure-python#create-task-based-container-group)
* Content Source: [docs-ref-services/latest/container-instance.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/container-instance.md)
* Service: **container-instances**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by swathipil** [comment]
@thec0dewriter - Thanks for your feedback! Tagging the right people so they can address this as soon as possible.
