### ISSUE TITLE
Acquire a connection to a Blob storage via outbound reverse proxy settings. 

### ISSUE THREAD

**Issue by Jagadishbobadeg** [Azure/azure-sdk-for-python#24264]
**Is your feature request related to a problem? Please describe.**
Acquire a connection to a Blob client via outbound proxy settings. 

curl -v -X GET 'https://**********.xx.net:8443/<Container_name>/<SAS>Token' -H 
'Host: Azurestorage.blob.core.windows.net' -H "Rest of the curl 
headers"

We have an outbound proxy in place and all of the external connection has to go via an 'https://********.xx.net:8443'. Hence, In the above curl command, I have used the host header to pass the actual storage account base URL.

Now, I want to replicate it using the python Azure blob SDK module but I am not sure how to structure the account url parameter. Any pointer or hint will be helpful

**Describe the solution you'd like**

A clear guide or instruction to acquire a connection via outbound proxy

**Describe alternatives you've considered**
I have tried the below options all of them through error 

1: 
containername = 'abcded'
connectionString = 'DefaultEndpointsProtocol=https;AccountName=https://********.blob.core.windows.net;account_key=<SASToken>;EndpointSuffix=outboundproxy.xx.net:8443'
blob_service_client = BlobServiceClient(connectionString, containername)

2. blob_service_client = BlobServiceClient(account_url="https://outboundproxy.xx.net:8443/", container='abcded'
                                        credential=<SASToken>,
                                        secondary_hostname='XXXXXXX.blob.core.windows.net')

**Comment by swathipil** [comment]
@Jagadishbobadeg - Thanks for the question! Tagging the right people so they can address it as soon as possible!

**Comment by Jagadishbobadeg** [comment]
Thank you @swathipil

**Comment by jalauzon-msft** [comment]
Hi @Jagadishbobadeg, there is a unique way to configure a proxy in the Python SDK. Here is the [documentation ](https://docs.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-configure-proxy?tabs=cmd)on how to do it. Once setup, you can just use the standard account URL / connection string options in the client.

Hope that helps! Thanks

**Comment by Jagadishbobadeg** [comment]
@jalauzon-msft Thank you for the pointers. I have already tried this proxy settings option, i get an error 'Proxy connection failed'. 
Its a reverse proxy and it has to be called as an endpoint on port 8443 with a host header option.

**Comment by jalauzon-msft** [comment]
Hi @Jagadishbobadeg, ok, another thing you can try is building the connection string with the custom endpoint (as your tried to do, it looks like). This can be done with the `BlobEndpoint` field in the connection string. See [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#create-a-connection-string-for-an-explicit-storage-endpoint).

Then, to specify the host header, you'll need to add a custom header to each operation. This can be done with the `headers` keyword arg that is present on every blob operation. See [this section](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#other-client--per-operation-configuration) of the README. 

So all together, that may look something like this:
```python
from azure.storage.blob import BlobServiceClient

containername = 'abcded'
connectionString = 'DefaultEndpointsProtocol=https;BlobEndpoint=https://outboundproxy.xx.net:8443/;AccountName=myAccountName;AccountKey=myAccountKey'

blob_service_client = BlobServiceClient.from_connection_string(connectionString)

headers = {'Host': '<account-name>.blob.core.windows.net'}
# Any operation you want to do
containers = blob_service_client.list_containers(headers=headers)
```

Hopefully that can work, thanks!

**Comment by Jagadishbobadeg** [comment]
I get this error 
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
azure.core.exceptions.ResourceNotFoundError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<div style="color:#000000; background-color:white"><p>Sorry, you've encountered an error. Please try again.</div>
</body>
</html>

For AccountKey=myAccountKey. Can i paste in SAStoken?

**Comment by Jagadishbobadeg** [comment]
I see a good progress now. At least i see a storage account is being reached via reverse proxy!!! 

Ignore the above error, i had made a copy paste error. 

```
from azure.storage.blob import BlobServiceClient
conn = 'DefaultEndpointsProtocol=https;BlobEndpoint=https://xxxxxxx.xxx.net:8443/container_name/?sp=rl&st=****&se=*****&spr=https&sv=2020-08-04&sr=c&sig=****************;AccountName=storage.blob.core.windows.net'

blob_service_client = BlobServiceClient.from_connection_string(conn)
headers = {'Host': 'storage.blob.core.windows.net'}
containers = blob_service_client.list_containers(headers=headers)
for i in containers:
 print(i.name)
```
I get this error

```
ErrorCode:InvalidUri
uripath:https://storage.blob.core.windows.net/container_name/comp=list&include=&sp=rl&st=****&se=*****&spr=https&sv=2020-08-04&sr=c&sig=****************

Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.
```

uripath in the error and the path i passed is different. Not sure how it is changing.

**Comment by jalauzon-msft** [comment]
@Jagadishbobadeg, I think you need to make a couple of changes to the connection string.
- When using a SAS token in a connection string, there is a separate field for that called `SharedAccessSignature`. See [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#create-a-connection-string-using-a-shared-access-signature).
- You should not include the container name in your endpoint. The endpoint should just be the root endpoint URL.
- `AccountName` in the connection string should just be the account name, not a URL. However, I'm not sure you even need `AccountName` if you are using SAS. The docs seem to indicate you do not.

Try something like this for the connection string (untested):
`DefaultEndpointsProtocol=https;BlobEndpoint=https://xxxxxxx.xxx.net:8443/;SharedAccessSignature=sp=rl&st=****&se=*****&spr=https&sv=2020-08-04&sr=c&sig=****************;AccountName=<account-name>`

**Comment by Jagadishbobadeg** [comment]
@jalauzon-msft  I was able to make a successful connection to the Storage account. I added additional two statements to retrieve container client objects as we access rights at the container level only.

```
from azure.storage.blob import BlobServiceClient
conn = 'DefaultEndpointsProtocol=https;BlobEndpoint=https://********.net:8443/;AccountName=<StorageName only>;SharedAccessSignature=sp=rl&st=2022-04-08T11:54:32Z&se=2022-05-08T19:54:32Z&spr=https&sv=2020-08-04&sr=c&sig=*****************************'

blob_service_client = BlobServiceClient.from_connection_string(conn)
headers = {'Host': '************************.blob.core.windows.net'}
container_client = blob_service_client.get_container_client(<Container_Name>)
containers = container_client.list_blobs(headers=headers)
```

**Comment by Jagadishbobadeg** [comment]
@jalauzon-msft  Thanks again for the help and tips. Have a good day!
