### ISSUE TITLE
Azure Custom Vision - Image classified differently by a model during training/testing.

### ISSUE THREAD

**Issue by agonzalez-mob** [Azure/azure-sdk-for-python#24267]
- **Package Name**: azure-cognitiveservices-vision-customvision
- **Package Version**: 
azure-cognitiveservices-vision-customvision==3.1.0
azure-common==1.1.28
azure-core==1.23.1
azure-storage-blob==12.11.0
- **Operating System**: MacOs Monterrey 12.3.1
- **Python Version**: Python 3.8.13

**Describe the bug**
The same image is classified as tag A during training but then classified as tag B if it's tested using the quick test image functionality. All of this is calculated at 50% probability threshold.

For the image in question, during training I got:
```
tag A 99.9%
tag B 0%
```

but during testing, using the quick test image option, the very same image gets:
```
tag A 45.7%
tag B 54.2%
```
that is contradictory.

This means that the stats shown by the GUI and the ones calculated using the SDK/API differ.
( I wouldn't test every single image used during training through the GUI, because I'd never finish)

``` bash
             API/SDK       GUI
precision    100%          100%
recall       99.4%         100%
```

**To Reproduce**
I'm afraid that this is very model-dependent.

**Expected behavior**
An image should receive the same tag by the model in both training and prediction.

**Comment by swathipil** [comment]
@agonzalez-mob - Thanks for your feedback! Directing this to the right people.

**Comment by agonzalez-mob** [comment]
> @agonzalez-mob - Thanks for your feedback! Directing this to the right people.

much appreciated... i don't really know where else to post this~

**Comment by agonzalez-mob** [comment]
Apologies. This ticket was because of an error from my side. I'll close it.
