### ISSUE TITLE
[core] add async test for offline test_compress_compressed_no_header_offline

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#24273]
Right now we only have the sync test for test_compress_compressed_no_header_offline. Please see the original [here](https://github.com/Azure/azure-sdk-for-python/blob/33c845aa7674c26bf851313daeae23e2f3f5459c/sdk/core/azure-core/tests/async_tests/test_streaming_async.py#L94),

cc @marcusc2

**Comment by iscai-msft** [comment]
@kristapratico assigning you because I can't assign one of the impact students

**Comment by kristapratico** [comment]
Marcus is working on this issue

**Comment by HimanshuBarak** [comment]
Hey @kristapratico , it this issue still up for grabs?? . If so I would love to work on this. I would just need a little help with the setup. but I am eager to contribute.

**Comment by kristapratico** [comment]
@HimanshuBarak I don't believe anyone is working on this issue, so feel free to give it a try and let us know if you have any questions.

**Comment by HimanshuBarak** [comment]
Hey @kristapratico  I have cloned the repo and written the test. The test is successfully raising the UnicodeDecodeError error. Can I directly raise the PR ? or are there any other tests requisite I need to test first?

**Comment by kristapratico** [comment]
@HimanshuBarak feel free to open it and just tag this issue in the description. If anything else is needed by the reviewers we can cover that in the PR. Thanks!

**Comment by HimanshuBarak** [comment]
Hey @kristapratico I have raised the PR https://github.com/Azure/azure-sdk-for-python/pull/33800. However I see some of the checks are failing. Are all of these checks mandatory ? Also is there a way to run these checks locally using tox?? Asking to know how I should proceed to debug them.

**Comment by kristapratico** [comment]
Hey @HimanshuBarak, you can run the checks locally with tox. Here are [instructions](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/tests.md#tox) on how to do that. It is possible that the errors are unrelated to your PR. I believe there are currently a few core tests failing that we are working on fixing ASAP. The reviewers should be able to help distinguish the relevant errors from the unrelated ones.

**Comment by HimanshuBarak** [comment]
Sounds good. I will try to debug on my end. Meanwhile I will look around to see I could contribute anywhere else. Do you have any suggestions for any other similar issues??. I am looking to be a first time contributor to open source and am super eager to learn.

**Comment by kristapratico** [comment]
@HimanshuBarak Any issues tagged with `help wanted` or `good first issue` labels are a good place to start. I've also updated the issue about making core tests offline to include which tests still need to be converted: https://github.com/Azure/azure-sdk-for-python/issues/9324#issuecomment-1888077552
