### ISSUE TITLE
AuthorizationPermissionMismatch when using AzureCliCredential

### ISSUE THREAD

**Issue by samy-dougui** [Azure/azure-sdk-for-python#24282]
- **Package Name**:  azure-identity / azure-storage-blob
- **Package Version**: azure-identity==1.10.0 / azure-storage-blob==12.11.0
- **Operating System**: Azure Pipeline (image: ubuntu-latest)
- **Python Version**: 3.9.12

**Describe the bug**
When we run the following python script in Azure Devops Pipeline (using a service connection), it fails halfway through:

```python
default_credential = AzureCliCredential()
blob_service_client = BlobServiceClient(account_url="https://MY_STORAGE_ACCOUNT.blob.core.windows.net", credential=default_credential)  
container_client = blob_service_client.get_container_client("MY_CONTAINER")  
print(container_client.exists())  # This returns True
for blob in container_client.list_blobs():  # This fails
    print(blob)
```

Even though  this command `az storage blob list -c MY_CONTAINER --account-name MY_STORAGE_ACCOUNT` in the same configuration succeeds.

Here is the traceback:

```bash
True
Traceback (most recent call last):
  File "/home/vsts/work/1/s/./scripts/generate_sas_token.py", line 73, in <module>
    run()
  File "/home/vsts/work/1/s/./scripts/generate_sas_token.py", line 43, in run
    for blob in container_client.list_blobs():
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/azure/storage/blob/_list_blobs_helper.py", line 83, in _get_next_cb
    process_storage_error(error)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.
RequestId:0ea3b6c8-101e-0006-4c24-5e7fc4000000
Time:2022-05-02T13:01:09.4026556Z
ErrorCode:AuthorizationPermissionMismatch
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:0ea3b6c8-101e-0006-4c24-5e7fc4000000
Time:2022-05-02T13:01:09.4026556Z</Message></Error>

```

**To Reproduce**
1. Connect to azure with azure cli
2. Execute the cli command `az storage blob list -c MY_CONTAINER --account-name MY_STORAGE_ACCOUNT`
3. Execute the python script given in the **describe bug section**

**Expected behavior**
If both scripts authenticate the same way (which is the case here, using the azure cli), they should both have the same behavior.

**Screenshots**

**Additional context**
As the bug was seen during an azure pipeline run, here is the script used to generate this pipeline:
```yaml
pool:
  vmImage: ubuntu-latest
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9"
    displayName: Install Python
## Install the appropriate dependencies
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'SERVICE_CONNECTION_NAME'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob list -c MY_CONTAINER --account-name MY_STORAGE_ACCOUNT --debug
        python3 my_python_script.py
      addSpnToEnvironment: true
      useGlobalConfig: true
      failOnStandardError: false
      powerShellIgnoreLASTEXITCODE: false
```

**Comment by jalauzon-msft** [comment]
Hi @samy-dougui Samy, thanks for reaching out. We'll take a look and get back to you soon.

**Comment by vincenttran-msft** [comment]
Hi @samy-dougui Samy, unfortunately we were unable to reproduce your error on our end. Taking a look at the Azure CLI operation you called and the provided code snippet, here are some suggestions that may help resolve your issue:

1. Ensure RBAC permissions are set correctly ([link](https://docs.microsoft.com/en-us/azure/storage/blobs/assign-azure-role-data-access?tabs=portal))
2. Ensure that the operations as described in your original post are done with the same user credentials, as it is possible that there is some odd interaction going on with your Azure Pipeline and any operations executed between your cli command and Python script
3. Finally, it is possible that if you had just modified any permissions, that it takes some time for all the permissions to propagate across and may lead to odd inconsistent behavior such as the one you have described

If none of the above helps to resolve your issue, please provide the following information in a follow-up comment below and we will do our best to resolve your issue:

1. A `RequestID` just as you have done above from the failing Python script
2. A `RequestID` from a working Azure CLI call to `az storage blob list` (you may have to use the `--debug` flag)
**NOTE:** The `RequestID`s would be best if they are generated recently (typically within the day) as the logs are automatically cleared on a rolling basis

Thanks!

**Comment by samy-dougui** [comment]
Hi @vincenttran-msft,

Sorry for the delayed answer.
Unfortunately, this bug still persists, but I realized that it was also happening locally, so it might be easier to reproduce the error.

The version used locally is still `python 3.9.12`.
The python script is the same. 

Here is the request-id when executing the python script with the execution-time: 
`RequestId:8675da84-101e-0023-0702-696771000000
Time:2022-05-16T08:55:57.5092210Z`

Here is the request-id when executing the azure cli:
For the request, `GET 'https://management.azure.com/subscriptions/SUBSCRIPTION_ID/providers/Microsoft.Storage/storageAccounts?api-version=2021-09-01'`, the ms-client-request-id: `'x-ms-client-request-id': '4f3fbef8-d4f6-11ec-9bdb-1e00a30ab999'`

Let me know if there is anything else I can do to help you.

Thank you for your help !

**Comment by xiangyan99** [comment]
@vincenttran-msft Since your linked issue was closed, could you give an update on this one?

**Comment by blasttask** [comment]
For anyone else that encountered this. Seems like AzureCliCredential and az cli are authenticating differently. AzureCliCredential requires the correct RBAC, so I had assign myself "Storage Blob Data Contributor" to run without getting AuthorizationPermissionMismatch. The az cli didn't require it this role set though, I suppose az cli might be generating a short-lived SAS token and make the request so it bypasses the RBAC

**Comment by vincenttran-msft** [comment]
Hi @blasttask, thanks for your response to this issue. This was some very valuable information, and we really appreciate your contribution to the discussion (especially when we are having difficulties reproducing the errors locally).


Hi @samy-dougui Samy, apologies for the delay in response. I just wanted to check in and see if this problem still persists? If so, could you please try the solution suggested above by @blasttask? 
Here is a doc that outlines how to assign Azure roles: [Assign Azure roles](https://docs.microsoft.com/en-us/azure/storage/blobs/assign-azure-role-data-access?tabs=portal), and here is another doc that is specific to assigning roles in [Azure portal](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal?tabs=current). The role that is relevant to your error seems to be the `Storage Blob Data Contributor` role. 

With that being said, hopefully the above solution is applicable to your issue, but please let us know if this is not the case.
Thanks!

**Comment by ernestomonroy** [comment]
Hello everyone

I am having the exact same issue and can confirm that the workaround proposed by @blasttask is working. Thanks!

However, I just wanted to check if there was any plan in addressing the disconnect between the permissions and access available to the same tenant when executing via the Azure CLI and the Python SDK. Aside from being misleading, ideally you dont have to define access policies twice for the same user just because they are executing in different environments.

If that is not something you are planning or wanting to do, it would be helpfull to at least get some more information as to why the access is different? This will help people to avoid situations where they give too much access, or later down the line, they need to take it away.

**Comment by jalauzon-msft** [comment]
Hi @ernestomonroy Ernesto, we were never quite able to track down why the difference exists as we were having trouble reproducing the issue on our side. We can try to investigate further.

As a follow-up what RBAC role was previously assigned to the user to have CLI work but not the SDK?

**Comment by ernestomonroy** [comment]
Hi @jalauzon-msft, thanks for looking into this.

On my CLI I am logged in through `az login` and my User in AD has the Global Administrator Role

In order for the SDK to work, I had to assign myself the "Storage Blob Data Contributor" Role Assignment. Just to clarify, I am using the `DefaultAzureCredential` class which defaults to the CLI Access Type (The same happens when I use the `AzureCliCredential` class)

**Comment by DanielHabenicht** [comment]
I can reproduce this issue. 
On CLI it warns about the missing credentials, but goes ahead by querying for an account key: 
```bash
$ az storage blob list --container-name data --account-name accountname

There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

You also can add `--auth-mode login` in your command to use Azure Active Directory (Azure AD) for authorization if your login account is assigned required RBAC roles.
For more information about RBAC roles in storage, visit https://docs.microsoft.com/azure/storage/common/storage-auth-aad-rbac-cli.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
...
```

For `AzureCliCredential` it just fails, until one adds his own user to the "Storage Blob Data Contributor" Role in the Storage Account. 
So this Issue is more of a feature request: 

`AzureCliCredential` should also query for an storage account key when the full credentials are provided, instead of throwing the cryptic `AuthorizationPermissionMismatch` Error.

**Comment by jalauzon-msft** [comment]
Thanks for the information @DanielHabenicht! This does appear to be the likely cause of the behavior OP and others were seeing here. I wasn't aware that the CLI had this additional functionality to query for the account key.

That being said, I don't think the `AzureCliCredential` used through an SDK should be querying for the account key in this case. When using a `TokenCredential` (which `AzureCliCredential` is one of the options), the SDK is intended to use AAD Auth to connect to the Storage account. Switching to account key auth would not be the expected behavior when using this type of credential, especially since we'd have to catch the auth error from the service and then try again. Further, the `AzureCliCredential` is just meant to be a convenience class to help obtain the _identity_ used in CLI, not necessarily match the auth pattern of the CLI.

The CLI is only querying for the account key here because an auth mode was not provided in the request. I expect it is not first attempting to use the AAD identity, failing, and then grabbing the account key. Further, if you were to specify `--auth-mode login` in the CLI request without updating the RBAC roles of the user, my hunch is that would fail in the same way the SDK does. Specifying the `AzureCliCredential` in the SDK request, explicitly tells the SDK to use AAD auth.

---
I also wanted to provide an additional note for everyone here and say that the RBAC role for just listing blobs should only be required to be "Storage Blob Data **Reader**" and not necessarily "Storage Blob Data Contributor". This can be useful to know if you wish to restrict the permissions to read-only.

**Comment by george-zubrienko** [comment]
I do not understand the design idea behind this. I'm literally running the quickstart code samples, being a Subscription Owner -> Storage Account Owner, and I am getting AuthPermissionMismatch when trying to list blobs (but not containers) in the storage account.

https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python?tabs=managed-identity%2Croles-azure-portal%2Csign-in-azure-cli

If this instance
```
blob_service_client = BlobServiceClient(account_url, credential=default_credential)
```
is supposed to dynamically fetch my access token and find in claims whether I am able to access the resource or not, there is either:
- something fundamentally wrong with my token claims
- something fundamentally wrong with the way SDK interprets my token claims

There is no way Owner permissions are overwritten by not having explicit `Storage Blob Data Contributor` role on the Container?

**Comment by rgrace-puck** [comment]
@jalauzon-msft  @george-zubrienko 
The same behavior seems to be in the .NET SDK as well. My account has the "Storage Blob Data Contributor" role assigned to it.

When I run the following command via Azure CLI (logged in with `az login`):
```
az storage blob list --blob-endpoint "https://mystaccount.blob.core.windows.net/" -c "mycontainer" --auth-mode login
```
It returns no errors. I also tested without the role assignment and it gives me an error.

Using `DefaultAzureCredential` in my .NET code, it recognizes the `AzureCliCredential` and selects it.
Then, I attempt the following request to the storage account (via the SDK):
```
GET https://mystaccount.blob.core.windows.net/mycontainer?restype=container&comp=list&prefix=MyPrefix&include=Tags
```
Which returns "Status: 403 (This request is not authorized to perform this operation using this permission.)"
Even after adding the "Storage Blob Data Reader" role it still does NOT work.

**Comment by mikwieczorek** [comment]
Encountered the same problem when running on AzureML ComputeInstance (CI) with user-managed identity. 

```
from azure.identity import DefaultAzureCredential
from azure.identity import ManagedIdentityCredential
from azure.storage.blob import BlobServiceClient

credential = DefaultAzureCredential() ## DOES NOT WORK WITH LISTING BLOBS
# credential = ManagedIdentityCredential(client_id="xxx") ## WORKS!
blob_service_client = BlobServiceClient(
        account_url="https://xxx.blob.core.windows.net",
        credential=credential
    )

for container in blob_service_client.list_containers(): # This works
    print(container.name)
container_client = blob_service_client.get_container_client("XXX")
print(container_client.exists())  # This returns True
for blob in container_client.list_blobs():  # This fails for DefaultAzureCredential
    print(blob)
```

Even though `credential = DefaultAzureCredential()` logs:
```
INFO:azure.identity._credentials.environment:No environment configuration found.
INFO:azure.identity._credentials.managed_identity:ManagedIdentityCredential will use Azure ML managed identity
```
it seems like wrong identity is used for DefaultAzureCredential.

Workarounds:
1. Use `credential = ManagedIdentityCredential(client_id="xxx")` – but breaks nice streamlined flow with DefaultAzureCredential
2. Set environmental variable `AZURE_CLIENT_ID`: `import os; os.environ['AZURE_CLIENT_ID'] = 'xxx';`

**Comment by corticalstack** [comment]
Hi,

Also have this issue, trying to use both either a System Assigned Managed Identity (SAMI), or User Assigned Managed Identity (UAMI) to authenticate to a key vault from within a Azure Machine Learning online endpoint.

Going beyond our own solution, replicated the Azure ML online endpoints keyvault example found here:
https://github.com/Azure/azureml-examples/blob/main/sdk/python/endpoints/online/managed/online-endpoints-keyvault.ipynb

 Online endpoint deployment fails with error further below, when code executing a secrets retrieval fails (code below, example using SAMI which as policy for secrets get on kv). Grateful for any support.

`
from azure.identity import ManagedIdentityCredential
from azure.keyvault.secrets import SecretClient
import os
import json

multiplier: int = None


def load_secrets():
    """
    Replaces the values of environment variables with names containing "KV_SECRET" and values of the form "<SECRET_NAME>@<VAULT_URL>" with the actual secret values

    Uses the ManagedIdentityCredential to create a SecretClient for each <VAULT_URL>. The endpoint's Managed Identity should have the get permission for secrets.

    Example:
        KV_SECRET_FOO: foo@https://keyvault123.vault.azure.net

        Will be replaced with the actual vaule of the secret named foo in keyvault123.
    """
    secret_clients = {}
    credential = ManagedIdentityCredential()

    for k, v in os.environ.items():
        if "KV_SECRET" in k:
            try:
                secret_name, vault_url = v.split("@")
            except ValueError:
                raise ValueError(
                    f"Wrong value format for env var {k} with value {v}. Should be of the form <SECRET_NAME>@<VAULT_URL>"
                )

            if vault_url in secret_clients:
                secret_client = secret_clients[vault_url]
            else:
                secret_client = SecretClient(vault_url=vault_url, credential=credential)
                secret_clients[vault_url] = secret_client

            secret_value = secret_client.get_secret(secret_name).value
            os.environ[k] = secret_value


def init():
    load_secrets()

    global multiplier
    multiplier = int(os.getenv("KV_SECRET_MULTIPLIER"))


def run(data):
    data = json.loads(data)
    input = data["input"]
    output = input * multiplier

    return {"output": output}
`

2023-08-29 14:48:20,103 E [69] azmlinfsrv - User's init function failed
2023-08-29 14:48:20,107 E [69] azmlinfsrv - Encountered Exception Traceback (most recent call last):
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azureml_inference_server_http/server/user_script.py", line 119, in invoke_init
    self._user_init()
  File "/var/azureml-app/test_deploy_endpoint_verbatim/score.py", line 43, in init
    load_secrets()
  File "/var/azureml-app/test_deploy_endpoint_verbatim/score.py", line 38, in load_secrets
    secret_value = secret_client.get_secret(secret_name).value
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret
    bundle = self._client.get_secret(
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1640, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/keyvault/secrets/_generated/v7_4/operations/_key_vault_client_operations.py", line 760, in get_secret
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 230, in run
    return first_node.send(pipeline_request)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 197, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 531, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 126, in send
    response = self.next.send(request)
2023-08-29 14:48:20,107 I [69] gunicorn.error - Worker exiting (pid: 69)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 119, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 339, in send
    response = self.session.request(  # type: ignore
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azureml_inference_server_http/server/aml_blueprint.py", line 109, in setup
    self.user_script.invoke_init()
  File "/azureml-envs/azureml_09cce48cae07377fa96cd42d79bcf994/lib/python3.10/site-packages/azureml_inference_server_http/server/user_script.py", line 121, in invoke_init
    raise UserScriptException(ex) from ex
azureml_inference_server_http.server.user_script.UserScriptException: Caught an unhandled exception from the user script
