### ISSUE TITLE
Associate and disassociate IP of VM

### ISSUE THREAD

**Issue by marcelo321** [Azure/azure-sdk-for-python#24289]
Sorry for making an issue here but I have been trying for 2 hours without success.

I am trying to remove the public IP of a VM:

```
# Import the needed credential and management objects from the libraries.
from azure.identity import AzureCliCredential
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.compute import ComputeManagementClient
import os


# Acquire a credential object using CLI-based authentication.
credential = AzureCliCredential()
subscription_id = "MYID"
network_client = NetworkManagementClient(credential, subscription_id)

RESOURCE_GROUP_NAME = "group2"
LOCATION = "westus"
IP_NAME = "vmBoxPublicIP"

``` 

Now I know I need to use `network_client.public_ip_addresses.begin_create_or_update()` but I don't understand the parameters. I want to know how to remove and add a public IP to a existing VM. Would appreciate any help

**Comment by swathipil** [comment]
Hey @marcelo321 - thanks for your question! Tagging the right people so we can get your question addressed asap!

In the meantime, we have a sample here that might be helpful for you? 
https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/network/ip/manage_public_ip_address.py

**Comment by marcelo321** [comment]
Thanks @swathipil 

I know that with az cli it is possible to do it like this:

Remove:
```
az network nic ip-config update \
          --resource-group $resourceGroupName --nic-name $nicName \
          --name $publicIpNameOnNic --remove PublicIpAddress
```

Add:
```
az network nic ip-config update \
          --name $publicIpNameOnNic \
          --nic-name $nicName \
          --resource-group  $resourceGroupName \
          --public-ip-address $publicIp
```

But I am completely lost on how to do it with python sdk

**Comment by SaurabhSharma-MSFT** [comment]
@swathipil Thanks for sharing the code.  
@marcelo321 Please go through the below code if this helps to update your existing VM NIC with the new ip.

```
    SUBSCRIPTION_ID = os.environ.get("SUBSCRIPTION_ID", None)
    GROUP_NAME = "vm-resource-group"
    PUBLIC_IP_ADDRESS = "vm-ip"
    NEW_PUBLIC_IP_ADDRESS = "vm-ip-new"

    # Create client
    # For other authentication approaches, please see: https://pypi.org/project/azure-identity/
    resource_client = ResourceManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID
    )
    network_client = NetworkManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID
    )
   
    # Get NIC details
    # Obtain the management object for virtual machines
    compute_client = ComputeManagementClient(credential=DefaultAzureCredential(),subscription_id=SUBSCRIPTION_ID)
    vm_name = "sasharvm"

    # Get network details of the VM
    nic_name = compute_client.virtual_machines.get(GROUP_NAME,vm_name=vm_name).network_profile.network_interfaces[0].id.split('/')[-1];
    nic_group = compute_client.virtual_machines.get(GROUP_NAME,vm_name=vm_name).network_profile.network_interfaces[0].id.split('/')[-5];
    subnet_id = network_client.network_interfaces.get(nic_group, nic_name).ip_configurations[0].subnet.id;
    vm_location = compute_client.virtual_machines.get(GROUP_NAME,vm_name=vm_name).location;
    ip_config_list = network_client.network_interfaces.get(nic_group, nic_name).ip_configurations;

    # Add new public ip address
    new_public_ip_address = network_client.public_ip_addresses.begin_create_or_update(
        GROUP_NAME,
        NEW_PUBLIC_IP_ADDRESS,
        {
          "location": vm_location
        }
    ).result()
    print("Create public ip address:\n{}".format(new_public_ip_address))

    # Provision the network interface client with the new IP Address
    poller = network_client.network_interfaces.begin_create_or_update(GROUP_NAME,
        nic_name, 
        {
            "location": vm_location,
            "ip_configurations": [ {
                "name": ip_config_list[0].name ,
                "subnet": { "id": subnet_id },
                "public_ip_address": {"id": new_public_ip_address.id }
            }]
        }
    )    

    nic_result = poller.result()

    # Delete existing public ip address
    public_ip_address = network_client.public_ip_addresses.begin_delete(
        GROUP_NAME,
        PUBLIC_IP_ADDRESS
    ).result()
    print("Delete public ip address.\n")
```

**Comment by marcelo321** [comment]
Hi @SaurabhSharma-MSFT,

I almost got it, but I am facing this error:

`In order to delete the public IP, disassociate/detach the Public IP address from the resource.`

So I need the first part to detach the IP before deleting it.

Altought what I wanted in first place was detaching it and not deleting it, I think deleting it is also helpful (but I need the part of detaching it.)

**Comment by marcelo321** [comment]
@swathipil I am not being able to find this type of command to simply detach the ip in the link you shared or the docs

**Comment by SaurabhSharma-MSFT** [comment]
@marcelo321 The code which I have shared is run disassociates the old IP Address while executing `network_client.network_interfaces.begin_create_or_update`.  Also, please find the below the gif showing the same.
![nic_ip_deassociate](https://user-images.githubusercontent.com/38112130/167013224-83618b43-5631-4376-b82e-82ce7b8973b7.gif)
Is this not working for you ?

Thanks
Saurabh

**Comment by marcelo321** [comment]
Hey @SaurabhSharma-MSFT,

Yes now it works (I changed the code before). So this code is creating a new IP and associating it with the VM nic name, that automatically detaches the old publicIP and then deletes i.

I noticed that when this happens, the PublicIP stays the same value (in the few tests I did) but has the new publicIP that is created. I think this happens because the VM is never without a publicIP, it just changes the PublicIP name we give.

Would be possible to work with only one publicIP without creating a new one?

So I have VM1 with publicIP1, I want to detach that IP so the VM1 wouldn't have any attacked publicIP, and then I want to attach it again, that way the publicIP should change this time.

That would be exactly the same as running this 2 commands in azure cli:

```
az network nic ip-config update \
          --resource-group $resourceGroupName --nic-name $nicName \
          --name $publicIpNameOnNic --remove PublicIpAddress
```

```
az network nic ip-config update \
          --name $publicIpNameOnNic \
          --nic-name $nicName \
          --resource-group  $resourceGroupName \
          --public-ip-address $publicIp
```

**Comment by marcelo321** [comment]
Any idea if it is possible @SaurabhSharma-MSFT?

**Comment by marcelo321** [comment]
Hi, wanted to check again if someone can take a look please @SaurabhSharma-MSFT @swathipil

**Comment by BigCat20196** [comment]
Hi @marcelo321, In the [cli command](https://github.com/Azure/azure-sdk-for-python/issues/24289#issuecomment-1119036313) you provided, you did not directly operate on the VM, but released a public IP and gave a new public IP in the network interfaces, and the corresponding SDK is `network_client.network_interfaces.begin_create_or_update`. 

Hope this unblock you.

```
network_client.network_interfaces.begin_create_or_update(GROUP_NAME,
        nic_name, 
        {
            "location": vm_location,
            "ip_configurations": [ {
                "name": ip_config_list[0].name ,
                "subnet": { "id": subnet_id },
            }]
        }
    )    


network_client.network_interfaces.begin_create_or_update(GROUP_NAME,
        nic_name, 
        {
            "location": vm_location,
            "ip_configurations": [ {
                "name": ip_config_list[0].name ,
                "subnet": { "id": subnet_id },
                "public_ip_address": {"id": new_public_ip_address.id }
            }]
        }
    )    

```

**Comment by BigCat20196** [comment]
Close this issue, because resolved. Due to the related dependency `msrest` has not been upgraded to the latest version.
