### ISSUE TITLE
Azure disk snapshot state after which I/O can be resumed inside a virtual machine

### ISSUE THREAD

**Issue by sachin-laddha** [Azure/azure-sdk-for-python#24291]
Azure disk snapshot API reponse has "properties.provisioningState" property. 

We are holding the I/O inside the virtual machine till the snapshot is complete i.e the provisioningState goes into "sucessful" state.  The snapshot time is not predictable and at times it takes couple of minutes to complete, which is not acceptable in our case.

So wanted to know what value for the provisioningState property we can look for?
Is there any "state" for which we can poll for and resume I/O ?

please let us know.

regards
Sachin

**Comment by sachin-laddha** [comment]
I m using following SDKs

azure-mgmt-compute==23.0.0
azure-mgmt-network==19.0.0
azure-mgmt-resource==20.0.0
azure-mgmt-storage==19.0.0

**Comment by swathipil** [comment]
@sachin-laddha - Tagging the right people to help address this asap!

**Comment by sachin-laddha** [comment]
Any update on this issue. 
This is a blocking issue for us. Any updates would be highly appreciated

**Comment by swathipil** [comment]
@msyyc - Would you be able to take a look at this?

**Comment by msyyc** [comment]
It seems that it is long running operation. Please refer [doc](https://github.com/Azure/autorest.python/blob/autorestv3/docs/client/operations.md#long-running-operations).
