### ISSUE TITLE
Updating a pipeline in Data Factory on a different branch than main

### ISSUE THREAD

**Issue by azure-walker** [Azure/azure-sdk-for-python#24294]
I need to update pipeline settings in Data Factory on a dev branch. At the moment, my code can read from main but how do you change branches in the code before you attempt make an update. Any attempt to update the code fails. I am guessing because it doesn't know which branch to update.

**Comment by swathipil** [comment]
@azure-walker - Thanks for your question! To confirm: Are you running into this issue when using the `azure-mgmt-datafactory` SDK?

**Comment by azure-walker** [comment]
Yes. the latest version 2.4.0

**Comment by BigCat20196** [comment]
Hi @azure-walker, thanks for your feedback. After my investigation, it seems that the [rest API](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L5017) does not support submitting branch modifications to the unexpected branch of the collaborationbranch. The definition of collaborationbranch is determined when creating datafactory, and modification is not supported.

I got the same tips on Azure Portal. 
![image](https://user-images.githubusercontent.com/51037443/168016236-718d5b6d-da7f-41d6-8f5e-af3a95f1d142.png)

An alternative method is to update the branch through Git SDK. Or you could open a new issue [here](https://github.com/Azure/azure-rest-api-specs/issues), describe the feature, let the rest API support the modification, and then we will generate and release a new version of SDK. Thanks!
