### ISSUE TITLE
CosmosDB container.replace_item not working when document ID is urlencoded?

### ISSUE THREAD

**Issue by LacquerShell** [Azure/azure-sdk-for-python#24327]
- **Package Name**: azure-cosmos
- **Package Version**: 4.2.0
- **Operating System**: CentOS 7
- **Python Version**: 3.7

**Describe the bug**
As stated. I get the below error: 

```
azure.cosmos.exceptions.CosmosHttpResponseError: (Unauthorized) The input authorization token can't serve the request. The wrong key is being used or the expected payload is not built as per the protocol. For more info: https://aka.ms/cosmosdb-tsg-unauthorized. Server used the following payload to sign: 'put
docs
dbs/call_tree/colls/call_tree/docs/==_144733031
fri, 06 may 2022 11:24:44 gmt

'
ActivityId: 3a8f0572-e788-4868-b4ee-2df9f80e59e5, Microsoft.Azure.Documents.Common/2.14.0
```
When I attempt to call `container.replace_item` with a document of the following ID: 

```
cosmos_client = self._get_cosmosdb_client()
test_item = cosmos_client.upsert_item({"id": "%3D%3D_144733031", "value":"1"})
replaced_test_item = cosmos_client.replace_item("%3D%3D_144733031", {"id": "3D%3D_1447330305", "value":"2"})
```

There appears to be some kind of mismatch of base64 urlencoding going on here; I can insert an item with this ID fine, but not replace it. 

**To Reproduce**
1. Create a CosmosDB container client 
2. Upsert a CosmosDB object with a URL encoded (with % characters) ID
3. Call `replace_item` on that CosmosDB object

**Expected behavior**
Expected the replace_item method (https://github.com/Azure/azure-sdk-for-python/blob/f80d07b2d1298c057d1f36381943f346b6e29a36/sdk/cosmos/azure-cosmos/azure/cosmos/container.py#L396) to update the item in place, rather than returning this error.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by LacquerShell** [comment]
Thanks - any update on this?

**Comment by simorenoh** [comment]
Hi @LacquerShell, thank you for opening this issue and using our SDK. I have started looking into this and it seems you may have found a gap in our SDK's functionality - it's not just the replace method that is affected with these encoded id's. Will keep you posted as I make progress.

**Comment by simorenoh** [comment]
Hi @LacquerShell, it seems like the use-case you;re trying to do is something that we do not support with CosmosDB in general - here's a document outlining the fact that we ask users to avoid using characters that require URL encoding with some of the more common characters: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet#remarks

Although it does not explicitly mention '%'s, these are also characters we ask users to avoid. Hope this makes sense!
