### ISSUE TITLE
azure.mgmt.loganalytics.saved_searches.get_results() will receive "Saved search result not supported for the new query language"

### ISSUE THREAD

**Issue by afengli** [Azure/azure-sdk-for-python#2432]
It comes to my attention that when the workspace has features.searchVersion == 1:

https://resources.azure.com/subscriptions/c5f9d2a9-7ade-4db7-a89a-0d4bb6c3xxx/resourceGroups/TestLogAnalysisRG/providers/Microsoft.OperationalInsights/workspaces/testloganalysis

{
  "properties": {
    "source": "Azure",
    "customerId": "xxxx",
    "portalUrl": "xxxx",
    "provisioningState": "Succeeded",
    "sku": {
      "name": "free"
    },
    "retentionInDays": 7,
    "features": {
      "legacy": 0,
      **"searchVersion": 1,**
      "searchVersionUpgradeTime": "Wed, 08 Nov 2017 20:42:29 GMT",
      "isSearchVersionUpgradedBySystem": true
    },
    "workspaceCapping": {
      "dailyQuotaGb": 0.5,
      "quotaNextResetTime": "Tue, 17 Apr 2018 22:00:00 GMT",
      "dataIngestionStatus": "RespectQuota"
    }
  },
  "id": "/subscriptions/c5f9d2a9-7ade-4db7-a89a-0d4bb6c3xxx/resourcegroups/testloganalysisrg/providers/microsoft.operationalinsights/workspaces/testloganalysis",
  "name": "testloganalysis",
  "type": "Microsoft.OperationalInsights/workspaces",
  "location": "eastus"
}

saved_searches.get_results()  will receive "Saved search result not supported for the new query language" regardless the query language is new or legacy. As most of the workspaces will get upgraded, would you please add logic to handle this error or give a more explanatory error message from LogAnalytics, such as "current work space version does not support getting saved search results"?

**Comment by xiangyan99** [comment]
@afengli latest azure-mgmt-loganalytics is 12.0.0. Does this work for you?
