### ISSUE TITLE
Add support for Azure Digital Twins sourceTime

### ISSUE THREAD

**Issue by lilumdaru** [Azure/azure-sdk-for-python#24329]
Hi,
the python Azure Digital Twin API is from "2020-10-31". Can you please update to a more recent version (>2021-06-30-preview). Or in other words: Can you please add support for updating a azure digital twins properties sourceTime:
https://docs.microsoft.com/en-us/azure/digital-twins/how-to-manage-twin#update-a-propertys-sourcetime

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by navba-MSFT** [comment]
@johngallardo, @ashish93-stack, @sjiherzig, @Satya-Kolluri Could you please look into this issue and provide an update once you get a chance. Awaiting you reply.
