### ISSUE TITLE
Remove Python DPS service SDK documentation from docs.ms.com

### ISSUE THREAD

**Issue by JimacoMS4** [Azure/azure-sdk-for-python#24336]
**Is your feature request related to a problem? Please describe.**
The DPS Python service SDK is no longer supported and the API reference should be removed from docs.ms.com: https://docs.microsoft.com/en-us/python/api/azure-iothub-provisioningserviceclient/?view=azure-python 

**Describe the solution you'd like**
Remove the API reference. 

**Describe alternatives you've considered**

**Additional context**

**Comment by JimacoMS4** [comment]
#assign @anushprabhu

**Comment by JimacoMS4** [comment]
@anushprabhu please see email thread with subject: "RE: How to remove Python DPS service SDK from docs.microsoft.com" for details.

**Comment by anthonyvercolano** [comment]
I've created PRs in the two repos.  Hopefully it will be merged soon
@anushprabhu, @cartertinney, @JimacoMS4

**Comment by JimacoMS4** [comment]
@anthonyvercolano I think we closed on this correct?

**Comment by JimacoMS4** [comment]
@anthonyvercolano @anushprabhu @cartertinney . Doc set has been removed, so I'm closing this item.

#please-close
