### ISSUE TITLE
Broken links in Azure Resources libraries for Python

### ISSUE THREAD

**Issue by rguptar** [Azure/azure-sdk-for-python#24387]
The links to the packages are broken.

For example, clicking `azure.mgmt.resources.features` takes you to
https://docs.microsoft.com/en-us/python/api/azure.mgmt.resource.features
instead of
https://docs.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e19ddc50-3cc0-eded-49ed-e1f2552a421c
* Version Independent ID: 391c4753-337c-8a9f-fa58-2c6fc95cb6df
* Content: [Azure Resources libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/azure.mgmt.resource?view=azure-python)
* Content Source: [docs-ref-services/latest/azure.mgmt.resource.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/azure.mgmt.resource.md)
* Service: **resources**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @lisawong19
* Microsoft Alias: **ramyar**

**Comment by msyyc** [comment]
Hi @scbedd could you help merge the fix [PR](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1555) or address proper person to merge it? Thanks!

**Comment by rguptar** [comment]
@scbedd can you review this when you get a chance?

**Comment by scbedd** [comment]
Github auto-closed the issue when I merged the PR. Re-opening until the change is actually visible on docs.ms.

**Comment by msyyc** [comment]
The issue was fixed already.
