### ISSUE TITLE
[dev setup] On a fresh codespaces instance, command prompt hangs for several seconds after each command

### ISSUE THREAD

**Issue by prprabhu-ms** [Azure/azure-sdk-for-python#24439]
*This bug report is not about any of the packages, but an issue I faced as I was setting up my dev environment to contribute to one of the packages.*

- **Package Name**: Not Applicable
- **Package Version**: Not Applicable 
- **Operating System**: Not Applicable
- **Python Version**:  Not Applicable

**Describe the bug**
On a fresh codespaces instance, on a terminal (via VSCode Desktop), command prompt hangs after each command for several seconds.

**To Reproduce**
1. Fork the repository. I'm not entirely sure this step is needed, but I was using the fork at https://github.com/prprabhu-ms/azure-sdk-for-python 
1. Create a new codespaces instance
1. Open the terminal
1. Run `echo hello world`.

**Expected behavior**
You see `hello world` and then back to PS1

What actually happens is that `hello world` is printed immediately, but then it takes several seconds for PS1 to reappear (and for you to be able to run the next command)

**Additional context**
I root caused it to the logic for setting PS1 in `~/.bashrc`. It's running `git ls-files` to get the name of the branch and some more information which is pegging the CPU to ~100% for a few seconds.

I was able to fix the problem by dropping the part that runs `git ls-files`, down to:
![image](https://user-images.githubusercontent.com/82062616/168258817-77ba3e73-52f9-4a9b-80a0-030822348865.png)

I'm guessing this is an issue with the .devcontainer for Codespaces.

**Comment by xiangyan99** [comment]
Thank you for your feedback. 

Do you have a chance to check if this only happens upon azure-sdk-for-python repo or it also repros in other repos?

This will help us narrow down if this is an azure-sdk-for-python repo issue or a codespace issue.

Thank you
