### ISSUE TITLE
CryptographyClient should keep port number of vault URI when created

### ISSUE THREAD

**Issue by nagyesta** [Azure/azure-sdk-for-python#24446]
**Is your feature request related to a problem? Please describe.**
Currently, when we are using the ```CryptographyClient``` with non-default port number in the key Id, the vault URI will not contain the port after the ```CryptographyClient``` instance is created.

For example, if the key Id is ```https://localhost:8443/keys/rsa-2048/2d93f37afada4679b00b528f7238ad5c```, the vault URI will be ```https://localhost``` and the request won't be able to hit the vault. This will cause our tests to fail.

This can be an issue in case we need to use a test double or a proxy on our ```CI```.

**Describe the solution you'd like**
I would like the port number to be kept in the vault URI (same as in case of the ```Java``` or ```.Net``` SDKs).

**Describe alternatives you've considered**
- I have considered using the default ```443``` port, but that is not always possible.
- Alternatively, if we could provide vault URI as an additional optional parameter, that could solve the issue as well, but this responsibility belongs to the ```CryptographyClient``` so it wouldn't be appropriate to push it to the caller.

**Additional context**
I think, the issue is in this line: 
https://github.com/Azure/azure-sdk-for-python/blob/azure-keyvault-keys_4.5.1/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py#L69
It is called from here:
https://github.com/Azure/azure-sdk-for-python/blob/azure-keyvault-keys_4.5.1/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py#L141

**Comment by lmazuel** [comment]
Hi @nagyesta 

Thanks for your report! Your investigation is great, and while I'm not myself working on KV, I feel you're into something :). @mccoyp in our team will look into that soon, thanks!

**Comment by nagyesta** [comment]
Hi @lmazuel and @mccoyp, thank you both for looking into this!

**Comment by mccoyp** [comment]
Hi @nagyesta, thanks again for opening this issue! (And double-thanks for pointing to the exact line to fix 🙂)

I opened the following PR to fix this: https://github.com/Azure/azure-sdk-for-python/pull/24466
