### ISSUE TITLE
Documentation for Azure Devops SDK

### ISSUE THREAD

**Issue by gpnikhil** [Azure/azure-sdk-for-python#24448]
Hello Team,

I came across python sdk for azure devops  [link](https://pypi.org/project/azure-devops/), but was unable to find any documentations for its use, I request you to please add a documentation section for better understanding of this SDK and how we can utilise them in our work process.

Thank you

**Comment by YalinLi0312** [comment]
Hi @gpnikhil , after opening the link you attached, I would recommend you to ask in the `homepage` link(in another GitHub repo) on PyPI page: https://github.com/microsoft/azure-devops-python-api . 

Thanks!
