### ISSUE TITLE
Bug in azure data tables when deleting an entity without a row key

### ISSUE THREAD

**Issue by timothyvries** [Azure/azure-sdk-for-python#24480]
- **Package Name**: azure-data-tables
- **Package Version**: 12.4.0
- **Operating System**: Independent, both on azure functions as locally debugging
- **Python Version**: 3.9

**Describe the bug**
When using the azure-data-tables package to delete an entity in a table, it throws an error when supplying a entity or a keyword argument with a empty RowKey.

**To Reproduce**
Try to delete a entity without a RowKey using the entity as input, or keyword arguments.
Eg:
delete_entity(entity={entity}) or delete_entity(partition_key='partitionkey', row_key='') or delete_entity(partition_key='partitionkey', row_key=None)

**Expected behavior**
To execute the function without problems and delete the entity from the table

**Screenshots**

**Additional context**
When investigating the code, the problem becomes clear.
https://github.com/Azure/azure-sdk-for-python/blob/40aac810aa1132e51847f6a48b4908f0afae0eaf/sdk/tables/azure-data-tables/azure/data/tables/_table_client.py#L305

Firstly, the bug when using an entity:
When passing an entity, it tries to extract the RowKey from the entity (row 337), which throws an error when the RowKey is empty. I believe this is wrong; as the RowKey can be empty.

Secondly, the bug when using the keyword parameters partition_key and row_key:
When passing the keyword parameters, it tests if the row_key is entered using if not row_key (line 343). Because of this check, it also filters out empty strings and makes it unable to delete entities without a RowKey.

**Workaround**
The workaround is easy, you can pass the partition key and row key as unnamed arguments.

**Comment by YalinLi0312** [comment]
Thanks for your feedback, we'll investigate ASAP.

**Comment by YalinLi0312** [comment]
Hi @timothyvries , thanks for reaching out. To clarify the issue, it's certainly a bug that empty row key or partition key should be supported. However they are required, so 'None' is not valid for them. We'll trying to get it fixed ASAP.

**Comment by YalinLi0312** [comment]
@timothyvries , thanks for your waiting!
We are working on re-factoring the de/serialization of `TableEntity` type in this semester, we'll take your feedback into consideration. Stay tuned!

**Comment by YalinLi0312** [comment]
Hi @timothyvries , we're back to investigating your issue. The partition/row key could be empty string `""` but can't be `None` as they are required properties in TableEntity object. So it should fail if you intend to delete with None keys values. For empty string, there's a difference between cosmos and storage Tables. Storage does allow keys to be empty strings while cosmos does not. We'll fix the bug in our SDK to enable keys with empty strings pass.
