### ISSUE TITLE
ContentSettings in storage blob makes empty string None

### ISSUE THREAD

**Issue by calvinhzy** [Azure/azure-sdk-for-python#24515]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.12.0
- **Operating System**: Windows
- **Python Version**: 3.9.6

**Describe the bug**
ContentSettings in azure-storage-blob convents an empty string '' to None
https://github.com/Azure/azure-sdk-for-python/blob/0db0c16559023eec3140970b1e00b9eb12e1e0b4/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py#L714

**To Reproduce**
1. Create this class with content_type = ""
2. The class will be created with content_type = None

**Expected behavior**
content_type == ""

**Screenshots**
![image](https://user-images.githubusercontent.com/17182306/169192633-f8089da0-ff05-48b0-9126-4c874c17c158.png)
![image](https://user-images.githubusercontent.com/17182306/169193605-e04f4122-eec7-42c2-bd35-3b895745aa94.png)
![image](https://user-images.githubusercontent.com/17182306/169192361-50eb44ee-0438-48ff-bf8e-56ec313c5810.png)

**Additional context**

**Comment by jalauzon-msft** [comment]
Hi @calvinhzy Zhiyi, thanks for bringing this up. I'm wondering if there is a use case where a customer would want `content_type` (or other `ContentSettings`) to be set to empty string? Rather than just not having them set at all?
