### ISSUE TITLE
Python SDK Issue for Azure Data Factory Delete Activity

### ISSUE THREAD

**Issue by sshrishipwc** [Azure/azure-sdk-for-python#24527]
The value for recursive  parameter is default to False but if we do not add this in code and deploy ADF Pipeline it shows the value is set (Or check box) is checked but execution does not show any logs (This is verify hard to find out issue). 

If we do not specify in code ADF should not show check box checked.
DeleteActivity Class 

https://docs.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.models.deleteactivity?view=azure-python

**Comment by Wzb123456789** [comment]
Hi @sshrishipwc, thank you for your feedback.

Please provide the exact version, specific steps and error messages according to the format of this [issue](https://github.com/Azure/azure-sdk-for-python/issues/21587)

Read the doc linked below to help you understand how to effectively resolve issues.
fyi: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/issues/resolve_issues_effectively.md
