### ISSUE TITLE
How do I get the latest events from eventhub

### ISSUE THREAD

**Issue by faizanbashir** [Azure/azure-sdk-for-python#24522]
Hi,

I am using the below code snippet to get the events from the beginning of the partition. I want to get the latest events. How do I get that?

`with client:
    client.receive(
        on_event=on_event,
        starting_position="-1",  # "-1" is from the beginning of the partition.
    )
`

**Comment by YalinLi0312** [comment]
Thanks for your feedback, we'll investigate ASAP!

**Comment by faizanbashir** [comment]
Thanks, @kashifkhan.
