### ISSUE TITLE
Azure: azure.mgmt.monitor python SDK, generates inconsistent OpreationName localized_value

### ISSUE THREAD

**Issue by preetesh33** [Azure/azure-sdk-for-python#24538]
Issue: Python SDK "azure.mgmt.monitor" generates inconsistant opreationName localizedValue.
Expection: Python SDK "azure.mgmt.monitor" should generate consistent localized_value

Steps to reproduce the issue:
1. Scenario A: Activity log of unattached disk deleted on - 2022-05-03

```
                    old_90 = today - datetime.timedelta(days=int(90))
                    id = rsourceid
                    fl = ("eventTimestamp ge '{}' and eventTimestamp le '{}' and resourceGroupName eq '{}' and resourceId eq '{}' and resourceType eq 'Microsoft.Compute/disks' and status eq 'Accepted'".format(old_90,today,resource_grp_name,id))
                    activities = client.activity_logs.list(filter=fl, select=None)
                    for lg in activities:
                        print(lg.operation_name)
```
 
Output: 
```
{'additional_properties': {}, 'value': 'Microsoft.Compute/disks/delete', 'localized_value': 'Microsoft.Compute/disks/delete'}
```

2. Scenario B:  Activity log of unattached disk deleted on - 2022-05-13
Same code used as above.
Output:
```
{'additional_properties': {}, 'value': 'Microsoft.Compute/disks/delete', 'localized_value': 'Delete Disk'}
```

Scenario A provides an incorrect 'localized_value', and in scenario B we got the correct localized_value.

**Comment by Wzb123456789** [comment]
Hi, @preetesh33 
The sdk is generated by swagger, however, the sdk receives the result returned from the service, so the sdk cannot modify the result.
It is recommended to go to service to file your issue.

fyi: https://github.com/Azure/azure-rest-api-specs/issues

**Comment by preetesh33** [comment]
@Wzb123456789 Raised below issue:
https://github.com/Azure/azure-rest-api-specs/issues/19267

**Comment by Wzb123456789** [comment]
@preetesh33 ,Thank you for your feedback.
If you have any questions, please communicate with me in time.

**Comment by navba-MSFT** [comment]
I have involved the Service team on the issue https://github.com/Azure/azure-rest-api-specs/issues/19267. Archiving this thread as duplicate.
