### ISSUE TITLE
Wild card search for Gen2 storage (Data Lake)

### ISSUE THREAD

**Issue by mikeleuer** [Azure/azure-sdk-for-python#24547]
**Is your feature request related to a problem? Please describe.**
I cannot use AZURE python functions to search for blob files. 

**Describe the solution you'd like**
I want the ability to use wild cards or regular expressions to search for blobs in Gen2 storage.

search should be something like this
Storage location
`Sandbox/ExampleProject/2022-05-13T15:14:08Z/123dfa21qdaswq213fdasqqqqqq.json`
Find
`Sandbox/*/*/123dfa21qdaswq213fdasqqqqqq.json`

**Describe alternatives you've considered**
In services like databricks/synapse/data factory/logic apps we can use wild cards to search for files however, if we want to use wild cards using a python function there is no SDK for it.

**Additional context**
Example:
```
from azure.identity import DefaultAzureCredential
from azure.storage.filedatalake import DataLakeServiceClient


credential = DefaultAzureCredential()
service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
    "https", "____" ), credential=credential)
file_system_client = service_client.get_file_system_client(file_system="___")

# DOES NOT WORK -- this should work or have a feature similar to it. 
find = "landing/test/*/test.json"
paths = file_system_client.get_paths(path=find)
for path in paths:
    print(path.name + '\n')

```

**Comment by jalauzon-msft** [comment]
Hi @mikeleuer, apologies for the long delay without a response on this.

This particular feature would require support from the Storage service before it can be added to the SDK. Please consider submitting this feedback to the Storage service team via upvoting or creating a new idea at https://aka.ms/AzStorageFeedback. This will help the service team gauge interest and prioritize new features. If the feature becomes available in the service, it will be promptly added to the SDK.

To that end, I'm going to close this Issue as there is not much that can be done from the client side to support this. Searching from the client-side would not be efficient, especially when considering paging from the service.
