### ISSUE TITLE
Automated method to determine required permissions for SDK calls for least privilege purposes

### ISSUE THREAD

**Issue by domjancik** [Azure/azure-sdk-for-python#24556]
When using SDK calls, it is unclear which permissions I need before calling and possibly getting an unauthorized error, which contains the required permission.

This is something that can be very useful when trying to set up a secure system and adhere to the least privilege principle.

I found the documentation page about this topic, but it contains just a mapping between services and resource providers (eg. `Azure Container Apps` to `Microsoft.APP`). The actual permissions actions required by SDK/API calls seem to be left to guesswork and relying on undocumented conventions. This is hard to automate and use at scale.

https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles#how-to-determine-the-permissions-you-need

# Suggested feature

Is there, or could there be a mechanism that would return a list of action permissions in response to a service/method pair?

### Request:
```json
{
	"class": "ResourceManagementClient",
	"method": "list"
}
```

### Response:
```json
["Microsoft.Resources/subscriptions/resources/read"]
```

# Alternative solutions
I tried researching the SDK and REST API documentation, in hopes that the required permissions would be documented there and could be scraped.

I also considered using REST API URLs as hints to the permission names as they seem fairly close. I do feel that there will be gaps with this approach and also not sure how to map between REST API calls and SDK functions.

**Comment by domjancik** [comment]
Thanks @annatisch,
I understand that it would be difficult to keep up to date manually.

I was hoping that you have the mapping somewhere internally - used to actually make the access control work.

I'd definitely like to hear what is the best way to approach this problem given the current options.

**Comment by domjancik** [comment]
Out of curiosity, can required permissions for an SDK call change depending on the supplied API version?

**Comment by domjancik** [comment]
@BigCat20196 Hi, have you looked at this issue?

Is being able to get the required permissions something you could be looking into in the future?

**Comment by msyyc** [comment]
Hi, as [annatisch](https://github.com/annatisch) said, SDK is just tool to send/receive http request/response. So your feature is more about feature-request for ARM. I advise you open an issue in https://github.com/Azure/azure-rest-api-specs/issues
