### ISSUE TITLE
Not A Feature Request but Requesting Help with an Error When Calling Azure Python SDK

### ISSUE THREAD

**Issue by hacknorris** [Azure/azure-sdk-for-python#24572]
We are getting some errors when trying to pull data and are requesting some assistance.

We are trying to call azure.mgmt.security.operations.ConnectorsOperation.list but are getting this error.

The first image is related to pulling connectors from Microsoft Defender for Cloud (Azure Security Center) and we would expect it to not error out.

<img width="931" alt="sdk-connectors-error" src="https://user-images.githubusercontent.com/20147808/169933127-88d70fbc-0bfa-4683-8c18-089e9b01fd18.png">

The second image is related to settings operations when calling:  azure.mgmt.security.operations.settings_operations..  It looks as the the api_version is hard coded to 2019-01-01.  Is there a difference in endpoints between commercial cloud and government clouds?

<img width="904" alt="sdk-gcc-error" src="https://user-images.githubusercontent.com/20147808/169933141-c18a23de-9ff3-49cd-93a3-24dff0bcc8d5.png">

Can you please help us?

**Comment by navba-MSFT** [comment]
Removing CXP attention label, This is being looked upon by the SDK and Service team.

@chlahav Could you please look into this ask when you get a chance ? Awaiting your reply.

**Comment by BigCat20196** [comment]
Hi @hacknorris, sorry for late reply. 

For Q1, it may be caused by the low version of msrest. Please try to update it to the latest version.

For Q2, Different types of cloud support are different. It mainly depends on whether the version of API is deployed on the cloud. This is not controllable by the SDK. the supported API versions in the cloud have been given in the error message.

**Comment by hacknorris** [comment]
sorry @BigCat20196  - missed your reply on this.  Can you clarify on the update of msrest for Q1.  For Q2, does someone on the Microsoft product team have to update the API for GCC High?

**Comment by msyyc** [comment]
Hi, For Q1, please try to update msrest to `0.6.21`. For Q2, you could open issue in https://github.com/Azure/azure-rest-api-specs/issues and then service team shall pick up it
