### ISSUE TITLE
`name_starts_with` should be `prefix` for consistency 

### ISSUE THREAD

**Issue by anthony-sarkis** [Azure/azure-sdk-for-python#24587]
Regarding `def list_blobs(self, name_starts_with=None,` 

it uses `name_starts_with` instead of `prefix`
it passes it to `ItemPaged(command, prefix=name_starts_with,`
without any modification. this is just odd confusion.

`name_starts_with`  should be renamed to `prefix`  to keep it consistent

**Comment by annatisch** [comment]
Thanks for the report @anthony-sarkis!
I'm curious why you have needed to use the constructor of `ItemPaged`?
This is largely an internal implementation and there shouldn't be a need to construct this object directly... so the names of the parameters in the constructor _should_ be inconsequential.

To rename the `name_starts_with` parameter of `list_blobs` would be a breaking change to the API, so we can't make this change.

Could you tell me more about how you're trying to use this object? Or a code sample? That will help us figure out the best course of action to take. :)

Adding @jalauzon-msft and @vincenttran-msft from Storage for visibility.

**Comment by anthony-sarkis** [comment]
I appreciate the speed and friendliness of your answer - there are lots of good reasons 

1. It matches the API https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs 
<html>
<body>


prefix | Optional. Filters the results to return only blobs whose names begin with the specified prefix.
-- | --



</body>
</html>

It's confusing to have an SDK function that names such a key item different from the core API

2. At some point in the past it likely had `prefix` as the name. Since most searches (at least for me) return results that mention using prefix.  https://stackoverflow.com/questions/51145124/how-to-list-all-blobs-inside-of-a-specific-subdirectory-in-azure-cloud-storage-u  For example this is the accepted answer with 33 upvotes.

3. It appears to silently swallow the `prefix` key word argument. This is especially confusing, becuase in conjunction with the searches indicating prefix, the api using prefix, the standard being prefix, the azure portal using prefix, it not throwing an error, and well I think you get the point.... At the very least it should error on an invalid keyword argument

4. For whatever reasons, getting authoritative docs on this SDK is difficult. often searches go towards other languages, or the rest api, etc. Further, we can't trust the signature since it uses magic things, and there are lots of accepted values that aren't listed in the signature (for example the meta thing). So again in light of that confusion the naming becomes more important.

I am calling attention to the point that virtually every other thing I have seen refers to it as a `duck` , and so that part of the code seemed to randomly decide to call it `super_duck` and it's probably something that needs some work. 

I normally wouldn't care about a single variable name this much but it's just annoying that it's referred as one thing in virtually every one place and then here it's called something different. 

More generally if you can please point to the best resource for all possible arguments for `def list_blobs()` ?
(since apparently we can't use the API docs.)
And can you please explain why the SDK deviates from the API?

**Comment by jalauzon-msft** [comment]
Hi @anthony-sarkis Anthony, I understand your confusion around this parameter name. Most of the examples you referenced however were referring to old versions of the Python SDK. For version 12, the SDK went through a major rewrite and quite a lot of things changed. Unfortunately, there are still easily discoverable references to the prior versions floating around and the API documentation has stayed around for legacy reasons. Both the [StackOverflow](https://stackoverflow.com/questions/51145124/how-to-list-all-blobs-inside-of-a-specific-subdirectory-in-azure-cloud-storage-u) and the [docs](https://azure-storage.readthedocs.io/_modules/azure/storage/blob/baseblobservice.html#BaseBlobService.list_blobs) you referenced are referring to the old versions of the SDK.

The docs for the new version of the SDK can be found [here](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-list-blobs) and show the proper parameter name of `name_starts_with`. For reference, [this](https://docs.microsoft.com/en-us/python/api/overview/azure/storage?view=azure-python) would be a good entry point to the latest docs. You can, of course, always go straight to the [source code](https://github.com/Azure/azure-sdk-for-python/blob/28c97be7928fb389ab1798db797a5cda94927462/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L736) to see the docstrings as well. Most API documentation is auto generated from source code anyway.

I'm not sure on the exact reasoning `name_starts_with` was chosen as this parameter name as I was not around when this API was created but the SDK often deviates from the service API to make things more readable/understandable. We do realize that for those who read the API docs, this can sometimes cause confusion.

Ultimately, as Anna mentioned above, we are not able to change this parameter name as that would be considered a breaking change to the SDK.
