### ISSUE TITLE
SDK calls HttpRequest._to_pipeline_transport_request() which is not a valid method of the HttpRequest object.

### ISSUE THREAD

**Issue by meco0597** [Azure/azure-sdk-for-python#24600]
- **Package Name**: azure.purview.account
- **Package Version**: (1.0.0b1)
- **Operating System**: Windows 11 
- **Python Version**: 3.10

**Describe the bug**
When calling the .next() function of a return ItemPaged response I get the error:

...\core\rest\_helpers.py", line 210, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'HttpRequest' object has no attribute '_to_pipeline_transport_request'

When I manually changed the generated sdk code to remove the call to _to_pipeline_transport_request I was able to get the expected response.

**To Reproduce**
1. Call  PurviewAccountClient.collections.list_child_collection_names and call .next() on the response 

**Expected behavior**
Expected to be able to iterate through the itemPaged object without getting the above exception

**Screenshots**
This is in file: \azure\purview\account\operations\_collections_operations.py
![image](https://user-images.githubusercontent.com/26746798/170358258-97c5fb85-1586-4fbb-a19b-08fb4b143178.png)

**Additional context**
from azure.purview.scanning import PurviewScanningClient
from azure.purview.catalog import PurviewCatalogClient
from azure.purview.account import PurviewAccountClient
from azure.identity import ClientSecretCredential 
from azure.core.exceptions import HttpResponseError
import json
import sys
sys.setrecursionlimit(1500)

client_id = "[Redacted]" 
client_secret = "[Redacted]"
tenant_id = "[Redacted]"
reference_name_purview = "[Redacted]"
storage_name = "[Redacted]"
storage_id = "[Redacted]"
rg_name = "[Redacted]"
rg_location = "[Redacted]"
collection_name = "[Redacted]"
ds_name = "[Redacted]"

def get_credentials():
    credentials = ClientSecretCredential(client_id=client_id, client_secret=client_secret, tenant_id=tenant_id)
    return credentials

def get_admin_client():
    credentials = get_credentials()
    client = PurviewAccountClient(endpoint=f"https://{reference_name_purview}.purview.azure.com/", credential=credentials, logging_enable=True)
    return client

try:
    client = get_admin_client()
except AzureError as e:
    print(e)

try:
    response = client.collections.list_child_collection_names("[Redacted]")
    **print(next(response))**
except HttpResponseError as e:
    print(e)

**Comment by annatisch** [comment]
Thanks @meco0597 - @iscai-msft would you be able to take a look into this one?

**Comment by iscai-msft** [comment]
Thanks for opening the issue @meco0597 !

`azure.purview.account` has been deprecated and replaced with `azure.purview.administration`.  Can you follow these steps and tell me if it fixes your error?

1. `pip install azure-purview-administration`
2. change `from azure.purview.account import PurviewAccountClient` to `from azure.purview.administration.account import PurviewAccountClient`?

Thanks!

**Comment by meco0597** [comment]
This worked thank you! should we update our docs to not use azure.purview.account anymore?

**Comment by iscai-msft** [comment]
Yep! There should be no more `azure.purview.account`, it should all be `azure.purview.administration` (maybe more specifically `azure.purivew.administration.account`) from now on. Thanks!
