### ISSUE TITLE
Sending full azure.mgmt.healthcareapis.models.ServicesDescription object to begin_create_or_update method causes failure due to Private Endpoint Configuration being included.

### ISSUE THREAD

**Issue by DSollickOnyx** [Azure/azure-sdk-for-python#24608]
- **Package Name**: azure-mgmt-healthcareapis
- **Package Version**: 1.1.0
- **Operating System**: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
- **Python Version**: 3.8.10

**Describe the bug**
It is not possible to submit a whole azure.mgmt.healthcareapis.models.ServicesDescription object if the ServiceProperties class contains an private_endpoint_connections entry. It responds with {"error":{"code":"BadRequest","message":"The provided Private Endpoint connections configuration is invalid."}}

**To Reproduce**
1. GET a full ServicesDescription object that has a Private Endpoint enabled.
2. Try to begin_create_or_update by passing in the resulting ServicesDescription.
3. Observe error: {"error":{"code":"BadRequest","message":"The provided Private Endpoint connections configuration is invalid."}}

**Expected behavior**
When a ServicesDescription object is PUT to the REST API it should not include the private_endpoint_connections in its ServiceProperties. It is (apparently) read-only on this endpoint. This will allow the create_or_update method to operate on a ServicesDescription object without having to explicitly wipe out the private_endpoint_connections properties.

**Detailed Log**
DefaultAzureCredential acquired a token from AzureCliCredential
Request URL: 'https://management.azure.com/subscriptions/1820f4e7-71ba-46f8-b759-0939ed6d0650/providers/Microsoft.HealthcareApis/services?api-version=2021-11-01'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': 'd811e8e4-dcf5-11ec-b03b-00155df539e7'
    'User-Agent': 'azsdk-python-mgmt-healthcareapis/1.1.0 Python/3.8.10 (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29)'
    'Authorization': 'Bearer xxx'
Request body:
This request has no body
Request URL: 'https://management.azure.com/subscriptions/1820f4e7-71ba-46f8-b759-0939ed6d0650/providers/Microsoft.HealthcareApis/services?api-version=REDACTED'
Response status: '200'
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json; charset=utf-8'
    'Content-Encoding': 'gzip'
    'Expires': '-1'
    'Vary': 'Accept-Encoding'
    'x-ms-request-id': '21ac9b47-ecce-4429-a0d6-42715f0f9740'
    'X-Content-Type-Options': 'nosniff'
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
    'X-Request-Id': 'a92e1805ea6b574d90e7175f46cf9935'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-ratelimit-remaining-subscription-reads': '11999'
    'x-ms-correlation-request-id': '3adac181-4f7b-4b6c-9eb7-6aea65694e22'
    'x-ms-routing-request-id': 'EASTUS:20220526T131452Z:3adac181-4f7b-4b6c-9eb7-6aea65694e22'
    'Date': 'Thu, 26 May 2022 13:14:52 GMT'
Response content:
{"value":[{"id":"/subscriptions/1820f4e7-71ba-46f8-b759-0939ed6d0650/resourceGroups/ossdmdhc31rg01/providers/Microsoft.HealthcareApis/services/osidmdhc31v1fhir","name":"osidmdhc31v1fhir","type":"Microsoft.HealthcareApis/services","etag":"\"0e00dee9-0000-0400-0000-628f7d410000\"","location":"eastus","kind":"fhir-R4","tags":{},"properties":{"accessPolicies":[{"objectId":"82c6484f-5830-4475-bde6-81976da4887d"}],"cosmosDbConfiguration":{"offerThroughput":3000},"authenticationConfiguration":{"authority":"https://login.microsoftonline.com/85722e96-8e10-4794-9933-f05d211175ef","audience":"https://osidmdhc31v1fhir.azurehealthcareapis.com","smartProxyEnabled":true},"corsConfiguration":{"origins":[],"headers":[],"methods":[],"allowCredentials":false},"exportConfiguration":{},"acrConfiguration":{"loginServers":[]},"privateEndpointConnections":[{"id":"/subscriptions/1820f4e7-71ba-46f8-b759-0939ed6d0650/resourceGroups/ossdmdhc31rg01/providers/Microsoft.HealthcareApis/services/osidmdhc31v1fhir/privateEndpointConnections/osidmdhc31v1fhir.b28c14ea-b150-4603-a45a-25970c1c517b","name":"osidmdhc31v1fhir.b28c14ea-b150-4603-a45a-25970c1c517b","type":"Microsoft.HealthcareApis/services/privateEndpointConnections","properties":{"provisioningState":"Succeeded","privateEndpoint":{"id":"/subscriptions/1820f4e7-71ba-46f8-b759-0939ed6d0650/resourceGroups/ossdmdhc31rg01/providers/Microsoft.Network/privateEndpoints/osidmdhc31v1fhir-endpoint"},"privateLinkServiceConnectionState":{"status":"Approved","description":"Auto-Approved","actionsRequired":"None"}}}],"publicNetworkAccess":"Disabled","provisioningState":"Succeeded"}}]}
Request URL: 'https://management.azure.com/subscriptions/1820f4e7-71ba-46f8-b759-0939ed6d0650/resourceGroups/ossdmdhc31rg01/providers/Microsoft.HealthcareApis/services/osidmdhc31v1fhir?api-version=2021-11-01'
Request method: 'PUT'
Request headers:
    'Content-Type': 'application/json'
    'Content-Length': '849'
    'Accept': 'application/json'
    'x-ms-client-request-id': 'd952ba44-dcf5-11ec-b03b-00155df539e7'
    'User-Agent': 'azsdk-python-mgmt-healthcareapis/1.1.0 Python/3.8.10 (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29)'
    'Authorization': 'Bearer xxx'
Request body:
{"kind": "fhir-R4", "location": "eastus", "tags": {}, "etag": "\"0e00dee9-0000-0400-0000-628f7d410000\"", "properties": {"accessPolicies": [{"objectId": "82c6484f-5830-4475-bde6-81976da4887d"}], "cosmosDbConfiguration": {"offerThroughput": 400}, "authenticationConfiguration": {"authority": "https://login.microsoftonline.com/85722e96-8e10-4794-9933-f05d211175ef", "audience": "https://osidmdhc31v1fhir.azurehealthcareapis.com", "smartProxyEnabled": true}, "corsConfiguration": {"origins": [], "headers": [], "methods": [], "allowCredentials": false}, "exportConfiguration": {}, "privateEndpointConnections": [{"properties": {"privateEndpoint": {}, "privateLinkServiceConnectionState": {"status": "Approved", "description": "Auto-Approved", "actionsRequired": "None"}}}], "publicNetworkAccess": "Disabled", "acrConfiguration": {"loginServers": []}}}
Request URL: 'https://management.azure.com/subscriptions/1820f4e7-71ba-46f8-b759-0939ed6d0650/resourceGroups/ossdmdhc31rg01/providers/Microsoft.HealthcareApis/services/osidmdhc31v1fhir?api-version=REDACTED'
Response status: '400'
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Content-Length': '111'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'x-ms-request-id': 'b3905732-a500-4d47-a293-ba902b4dc405'
    'X-Content-Type-Options': 'nosniff'
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
    'X-Request-Id': '5cd705489558684191c51027e6614d6b'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-ratelimit-remaining-subscription-writes': '1199'
    'x-ms-correlation-request-id': 'bdcf8e60-e8b8-4e02-aac5-9dd72af8dff6'
    'x-ms-routing-request-id': 'EASTUS:20220526T131453Z:bdcf8e60-e8b8-4e02-aac5-9dd72af8dff6'
    'Date': 'Thu, 26 May 2022 13:14:52 GMT'
Response content:
{"error":{"code":"BadRequest","message":"The provided Private Endpoint connections configuration is invalid."}}

**Additional context**
You can work around the problem by setting the private_endpoint_connections property to None like so:

fhir_server.properties.private_endpoint_connections = None

This will drop it from the final REST request and it will proceed as expected to edit any other properties.

The REST documentation states nothing about this property being read-only. In talking with the FHIR product team it apparently used to silently fail but due to a recent update it now loudly fails. If you do not explicitly set the private_endpoints_connection to None you must manually construct your own ServicesDescription object for properties you wish to edit via API.

I don't know what the right answer is here -- should the get / list method not include private_endpoint_connections in the returned ServicesDescription? As a user I don't expect the representation I "get" to need to have properties deleted in it to turn it around and put it in an Update function. I expect to be able to edit a specific property and pass it to an update function.

There are separate Private Endpoint functions that work independently from this larger "update metadata" context. I think this data (even if it is returned by the REST API) should potentially be ignored and any interactions (including reading) of the private_endpoint_connections should be done through the Private Endpoint actions.

**Comment by annatisch** [comment]
Thanks for the report @DSollickOnyx - we'll take a look asap :)

**Comment by BigCat20196** [comment]
Hi @DSollickOnyx, thanks for your feedback! Could you please Provide some code snippets to reproduce this issue? 

As for the use of the update function, it is an overall update. It needs to pass the parameters that need to be updated and the original parameters.

BTW, Since the python SDK is generated based on the [rest API](https://github.com/Azure/azure-rest-api-specs), it will not deliberately change the returned results. So if you think the returned result is not as expected, please open the issue under the [rest issue](https://github.com/Azure/azure-rest-api-specs/issues).

**Comment by DSollickOnyx** [comment]
Hi @BigCat20196, this scenario came up when, for example, I wanted to edit the provisioned Resource Units for the backing cosmosdb. I .get() the resource, try to edit the relevant property, and then it flops on its face *if the existing FHIR resource has a PE enabled*.

from azure.mgmt.healthcareapis import HealthcareApisManagementClient
hc_client = HealthcareApisManagementClient(credentials, subscription_id)
fhir_server = hc_client.services.get(resource_group_name=rg_name, resource_name=server_name)
fhir_server.properties.cosmos_db_configuration.offer_throughput = 5_000
hc_client.services.begin_create_or_update(resource_group_name=rg_name, resource_name=fhir_server.name, service_description=fhir_server
<errors here>

To your point this is, at its core, a REST issue. The REST endpoint outputs a ServicesDescription but will not accept it even though it says it will (and must, actually). I'm just being sent in circles trying to figure out who I need to even report this to other than the PG.
