### ISSUE TITLE
ApplicationInsightsManagementClient doesn't accept a `subscription_id` and crashes.

### ISSUE THREAD

**Issue by Bubblyworld** [Azure/azure-sdk-for-python#24606]
- **Package Name**: `azure-mgmt-applicationinsights`
- **Package Version**: `3.0.0`
- **Operating System**: `macOS Big Sur`
- **Python Version**: `3.9`

**Describe the bug**
According to the [documentation](https://docs.microsoft.com/en-us/python/api/azure-mgmt-applicationinsights/azure.mgmt.applicationinsights.applicationinsightsmanagementclient?view=azure-python), `ApplicationInsightsManagementClient` is supposed to take a `subscription_id` in the constructor. This is not the case if you try and use the package, which results in this error:

```
AttributeError: 'ApplicationInsightsManagementClientConfiguration' object has no attribute 'subscription_id'
```

**To Reproduce**
Run the following python script:

```
from azure.mgmt.applicationinsights import ApplicationInsightsManagementClient
from azure.identity import DefaultAzureCredential
creds = DefaultAzureCredential()
aim_client = ApplicationInsightsManagementClient(creds)
ai = aim_client.components.create_or_update(
    "same-resource-group",
    "same-app-insights",
    {
        "kind": "web",
        "location": "West US",
        "application_type": "web",
    }
)

```

**Expected behavior**
I expect the above code to provision an ApplicationInsights component. Instead it crashes.

**Screenshots**

**Additional context**

**Comment by Bubblyworld** [comment]
It's possible to work around this bug by manually setting `subscription_id`, but this is ugly:

```
    # A hack to fix a bug in azure.mgmt.applicationinsights.
    #   see: https://github.com/Azure/azure-sdk-for-python/issues/24606
    setattr(aim_client._config, "subscription_id", subscription_id)
```

**Comment by Wzb123456789** [comment]
Hi @Bubblyworld, thank you for your feedback.
After investigation, the `ApplicationInsightsManagementClient` method in the code you provided is missing the necessary parameter `subscription_id`.

It is also suggested in the [document](https://docs.microsoft.com/en-us/python/api/azure-mgmt-applicationinsights/azure.mgmt.applicationinsights.applicationinsightsmanagementclient?view=azure-python) that subscription_id is a parameter of the `required` attribute.

It is recommended that you set the value of the subscription_id parameter in the local environment variable now, and read it when you use it, as shown in the following code:
![image](https://user-images.githubusercontent.com/51410816/173520956-68d24a04-630a-4662-8d1c-f4af28f35ed6.png)
