### ISSUE TITLE
SDK - Bill of Materials readme issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-python#24629]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/boms/azure-sdk-bom/README.md#table-of-contents)
![image](https://user-images.githubusercontent.com/74638143/170621390-45dc248d-0723-4f9a-9329-5dd48bbd5992.png)

**Reason:**
Invalid page link and no found matching text description in the readme file.
**Suggestion:**
Delete this invalid page link.

joshfree, pallavit and vcolin7 for notification.

**Comment by xiangyan99** [comment]
Please open it in https://github.com/Azure/azure-sdk-for-java repo
