### ISSUE TITLE
Guidance on porting code to new SDKs

### ISSUE THREAD

**Issue by pipern** [Azure/azure-sdk-for-python#2462]
Please could you point us at where to find guidance on porting code to newer SDK versions?

In https://github.com/Azure/azure-sdk-for-python/commit/4dbe837e5b256da2865a300ab68078b7a58c14ea#diff-ddfd642a99bc6edf8ec1a1b4ab58aba8 we see that `azure.mgmt.authorization.models.RoleAssignmentProperties` has gone away; however Google doesn't lead me to find anywhere Microsoft documentation about what it's replaced with. I assume `RoleAssignmentCreateParameters` but do not find any issue here or elsewhere about if/why this changed.

Our code was originally working with `azure-cli-2.0.6` but now I'm trying to make it work with `azure-cli-2.0.31`.

This migration is somewhat because 2.0.6 doesn't seem to work:

```
$ virtualenv azure-cli-2.0.6 && ./azure-cli-2.0.6/bin/pip install azure-cli==2.0.6 && ./azure-cli-2.0.6/bin/az
[...]
bash: ./azure-cli-2.0.6/bin/az: Permission denied
```

```
$ chmod +x ./azure-cli-2.0.6/bin/az && ./azure-cli-2.0.6/bin/az
/usr/bin/python: No module named azure
```

```
$ . ./azure-cli-2.0.6/bin/activate
(azure-cli-2.0.6)  $ ./azure-cli-2.0.6/bin/az
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/src/azure-cli-2.0.6/lib/python2.7/site-packages/azure/cli/__main__.py", line 9, in <module>
    import azure.cli.main
  File "/home/user/src/azure-cli-2.0.6/local/lib/python2.7/site-packages/azure/cli/main.py", line 9, in <module>
    from azure.cli.core.application import APPLICATION, Configuration
ImportError: No module named application
```

Strangely though, if I ignore the non-working `az`, I do note that this 2.0.6 has `azure-mgmt-authorization              0.40.0` which lacks `RoleAssignmentProperties`, so I'm confused that it seems azure-cli==2.0.6 now gets different supporting libraries installed.

Overall, I think we're struggling to understand how to have our code stay working/stay up to date with changes in the SDK. What's the guidance for managing that? Thank you!

**Comment by lmazuel** [comment]
Hi @pipern 
First, I can't say anything about CLI problems, you would have to declare an issue in:
https://github.com/Azure/azure-cli/issues

The CLI doesn't pin dependencies, so `pip install azure-cli==2.0.6` won't install what the CLI was when 2.0.6 was released. If you want exactly this, CLI team have Docker containers frozen in time.

I don't have migration documentation unfortunately :(

**Comment by pipern** [comment]
Thank you for these insights - in particular, I'll switch and specify all the libraries for pip install.

Do you know the best approach for porting/discovering what is changed? I'm unclear what the 'canonical' documentation for the SDK is (keyed by version).

**Comment by lmazuel** [comment]
I try to be as specific as possible in the ChangeLog:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-authorization/HISTORY.rst

Clearly, what you say is I missed something in the ChangeLog :/. The code is auto-generated, and ChangeLog is manual, so I missed stuff sometimes :(. I plan to work on a tool to provide this ChangeLog is a more automatic way, but I don't have it yet.

**Comment by lmazuel** [comment]
Closing, since now ChangeLog is built part of the packages automatically
