### ISSUE TITLE
conditional table update?

### ISSUE THREAD

**Issue by lovettchris** [Azure/azure-sdk-for-python#24638]
**Is your feature request related to a problem? Please describe.**
Is there any way to update a row "conditionally", e.g. iff a certain value is already present or not?  I need the equivalent of an "interlocked exchange" while updating a row in order to do something like "grab a lock on that row" across a Kubernetes cluster of machines running jobs all controlled from a central azure job status table.

**Describe the solution you'd like**
Something like upsert with "UpdateMode.CONDITIONAL_REPLACE", entity, matching_properties" so I can do something like:
`table.upsert_entity(mode=UpdateMode.CONDITIONAL_REPLACE, entity=entity, match={ 'lock': ''))` which will only update the entity if the entity does not exist, or the entity exists and has no current value for the column named 'lock'.

**Describe alternatives you've considered**
Currently I have a race condition, all nodes in the cluster try and grab the lock, then the turn around and read back the entity to see if they won the race or not, but this is sub optimal and is still error prone because of random delays in read/write operations.

**Additional context**
I'm using Python on Azure Kubernetes cluster to do AI model optimization cranking through thousands of models a day.

**Comment by lovettchris** [comment]
Having said all that, is [MERGE ](https://stackoverflow.com/questions/22832863/how-to-do-conditional-update-of-azure-table-storage-entity-with-etag) the answer with it's built in ETag check?

**Comment by catalinaperalta** [comment]
Thanks for reaching out @lovettchris! We'll investigate asap.

**Comment by YalinLi0312** [comment]
Hi @lovettchris , thanks for reaching us!

We support two update modes - `MERGE`, `REPLACE`- right now, unfortunately we don't have a mode dedicated for `CONDITIONAL_REPLACE`. But it's still possible to update an entity conditionally by `match_condition` and entity's `etag`. The PR reference above includes samples about that, hope it helps.

Thanks

**Comment by lovettchris** [comment]
Ah right, I did eventually find that and am using it, works great, thanks.
