### ISSUE TITLE
Cognitive Search samples issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-python#24630]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/HttpResponseExceptionExample.java#L83)
![image](https://user-images.githubusercontent.com/74638143/170623115-cf286c4a-ae0d-4727-a1cf-73ae5f7ae50a.png)

**Reason:**
'search(java.lang.String, com.azure.search.documents.models.SearchOptions, com.azure.core.util.Context)' is not public in 'com.azure.search.documents.SearchAsyncClient'. Cannot be accessed from outside package
**Suggestion:**
Update to `client.search("hotel", searchOptions)`

2.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/indexes/ListIndexersExample.java#L37)
![image](https://user-images.githubusercontent.com/74638143/170623779-f84f05c8-e7c1-4a7c-9cdd-a6609c4cc526.png)

**Reason:**
''listIndexers(com.azure.core.util.Context)' is not public in 'com.azure.search.documents.indexes.SearchIndexerAsyncClient'. Cannot be accessed from outside package
**Suggestion:**
Update to `indexerAsyncClient.listIndexers())`

joshfree, AlexGhiondea, meeraharidasa ans samvaity for notification.

**Comment by xiangyan99** [comment]
Please open it in https://github.com/Azure/azure-sdk-for-java repo
