### ISSUE TITLE
Download stream interrupted

### ISSUE THREAD

**Issue by cheryl-catalog** [Azure/azure-sdk-for-python#24636]
/unresolved
I am seeing this error as well:

2022-05-27T21:51:42+0000 __next__():186 Unable to stream download: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2022-05-27T21:51:42+0000 wrapped():79 Download stream interrupted.

pip3 freeze | grep azure
azure-common==1.1.28
azure-core==1.24.0
azure-storage-blob==12.12.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.8.0

I will try the suggested tweaks in (https://github.com/Azure/azure-sdk-for-python/issues/19753) and see how it goes. I just started seeing this error this week

_Originally posted by @cheryl-catalog in https://github.com/Azure/azure-sdk-for-python/issues/19753#issuecomment-1140074230_

**Comment by jalauzon-msft** [comment]
Hi @cheryl-catalog Cheryl / @jasonoberme, apologies for the delay in response.

Connection reset errors come from the Storage service and there is not much we can do on the client-side except retry. The client should be automatically retrying these errors and that _usually_ will lead to a successful request, but we recently identified an issue with our retry logic, specifically when streaming large downloads and we have a fix coming in our next release, 12.14.0. (The preview should be released this month with the full release sometime in September). It is difficult to tell if this fix will help in your scenario but download streaming is the targeted feature.

If you are still experiencing the issue, could you include a full stack trace of the error if possible? That will help us identify if the upcoming fix will help.

Additionally, if you are seeing these pretty consistently, I would also recommend opening a support ticket so the service team can take a look. There can sometimes be issues on the backend that could cause these types of errors if they are happening consistently.

**Comment by cheryl-catalog** [comment]
Thank you Jacob. It was seen consistently in a test scenario that is not often run. I will try it out in your next release and let you know if it fixes the problem.

All the best,
Cheryl

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jalauzon-msft** [comment]
Hi @cheryl-catalog Cheryl, `azure-storage-blob` 12.14.0 was released last week which contains the fixes I was mentioning w.r.t. streaming download retry. Could you try your test scenario again to see if the updates helped with the connection resets at all? Thanks.
