### ISSUE TITLE
[azureml] update pyarrrow to version 6

### ISSUE THREAD

**Issue by MarkusDressel** [Azure/azure-sdk-for-python#24644]
**Is your feature request related to a problem? Please describe.**
I am using the latest python azure machine learning sdk (version: 1.42.0). Training HuggingFace Models most often require the use of [datasets](https://github.com/huggingface/datasets). Unfortunately, this is not possible since azureml-datasets requires pyarrow<4.0.0 while latest version of HuggingFace Datasets requries at least version 6. 

**Describe the solution you'd like**
Update the upper bound of pyarrow in azureml python sdk to at least version 6

**Describe alternatives you've considered**
Since training is performed using azureml pipelines, it is required to use azureml-sdk. No other possibilties possibe.

**Comment by MarkusDressel** [comment]
@anliakho2 great to hear. Let me know when preview is available. Happy to test

**Comment by mmccarty** [comment]
`cudf` requires 7.0.0. Would it be possible to include that version?
cc @galipremsagar

**Comment by galipremsagar** [comment]
`cudf`-`22.06.*` supports py-arrow 7.0.0. Is the ask for `cudf-22.08`?

**Comment by luigiw** [comment]
@anliakho2 Can you provide an update for this thread? Thank you.
