### ISSUE TITLE
Send serializable Python objects as Topic message.

### ISSUE THREAD

**Issue by amrx101** [Azure/azure-sdk-for-python#2464]
I couldn't find anything on the docs that instructed how do we send a Python object instance that is serializable as the message body when publishing to a Topic in Azure Service Bus.

**Comment by lmazuel** [comment]
Is there anything here that answers your question?
https://github.com/Azure/azure-sdk-for-python/blob/master/doc/servicebus.rst

Otherwise, could you precise a bit?
Thank you

**Comment by annatisch** [comment]
Hi @amrx101,

We have just published a new AMQP-based preview SDK for Service Bus! The API has been newly designed, and you can find documentation here:
- [Overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python)
- [Reference documentation](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus?view=azure-python)

While the new preview API does not yet support creating a Topic message directly from a custom Python object, if your object is JSON serializable, you can create a message from the serialized payload. Something like:
```python
from azure.servicebus import Message

message_data = MyCustomData()
message_payload = dict(message_data)  # Serialized JSON data
sb_message = Message(message_payload)

# or, you can dump the data and send as string or bytes
message_payload = json.dumsp(message_data.__dict__)
sb_message = Message(message_payload)

# or if you use a custom JSON encoder
message_payload = json.dumps(message_data, default=custom_serializer)
sb_message = Message(message_payload)
```

It would be fantastic to get your feedback on this, and whether you have any particular feature requests or recommendations.

**Comment by jfggdl** [comment]
Closing issue.  @amrx101 Please feel free to reopen this issue if you still have questions.

**Comment by mikescr** [comment]
> 
> 
> Hi @amrx101,
> 
> We have just published a new AMQP-based preview SDK for Service Bus! The API has been newly designed, and you can find documentation here:
> 
>     * [Overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python)
> 
>     * [Reference documentation](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus?view=azure-python)
> 
> 
> While the new preview API does not yet support creating a Topic message directly from a custom Python object, if your object is JSON serializable, you can create a message from the serialized payload. Something like:
> 
> ```python
> from azure.servicebus import Message
> 
> message_data = MyCustomData()
> message_payload = dict(message_data)  # Serialized JSON data
> sb_message = Message(message_payload)
> 
> # or, you can dump the data and send as string or bytes
> message_payload = json.dumsp(message_data.__dict__)
> sb_message = Message(message_payload)
> 
> # or if you use a custom JSON encoder
> message_payload = json.dumps(message_data, default=custom_serializer)
> sb_message = Message(message_payload)
> ```
> 
> It would be fantastic to get your feedback on this, and whether you have any particular feature requests or recommendations.

I've successfully created message using serialization: 
Original message: Dictionary with pandas DataFrame so I;
Every part is dictionary is sent as a message
`
import json
import pandas
from azure.servicebus import Message
queue_messages = []
for key in dict.keys():
  message[]
  message.append(json.dumps(key))
  message.append(dict[key].to_json(orient='records'))
  queue_messages.append(Message(json.dumps(queue_message))
queue_client.send(queue_messages)
`

When I load the msg back from the bus queue trigger, I do the reverse:
`
def main(msg: func.ServiceBusMessage):
    in_message = json.loads(msg.get_body().decode('utf-8'))
    key_id = farm_message[0]
    df_message = pd.read_json(in_message[1], orient='records')
`
