### ISSUE TITLE
UsageDetailsOperations.get_next() pagination failing at 1000 records

### ISSUE THREAD

**Issue by jboliv01** [Azure/azure-sdk-for-python#24663]
- **Package Name**: azure-consumption-management
- **Package Version**: 9.0.0
- **Operating System**: Debian GNU/Linux 11 (bullseye)
- **Python Version**: 3.10-bullseye

**Describe the bug**
 When calling usage_details.list() method on a ConsumptionManagementClient and setting a "StartDate" and "EndDate" parameter, pagination fails after 999 result records are returned. I believe the issue is with the with "get_next" function of the UsageDetailsOperations class.

**To Reproduce**
1. Instantiate an instance of the ConsumptionManagementClient
`con_client = ConsumptionManagementClient(auth, subscriptionId)`
3. declare a variable to hold result set and call usage_details.list() method against client with the following parameters:
```
usage = con_client.usage_details.list(
scope=f"/subscriptions/{subscriptionId}",
expand="properties/additionalInfo",
metric="actualcost",
params={"StartDate": "2022-05-01", "EndDate": "2022-05-02"})
```
4. Iterate through usage object:
```
for i, item in enumerate(usage):
print(i)
```
5. Loop breaks at index position 1000 where get_next() function is called. We added a print to line 202 of _usage_details_operations.py to print out the next_link argument of the get_next() function and were able to successfully test the next_link in postman.

**Expected behavior**
get_next() function is called every 1000 records and pagination is successful

**Screenshots**
![image](https://user-images.githubusercontent.com/57547273/171465533-357e5bf8-1d7c-4f95-b865-fa9fae99bff8.png)

**Additional context**

**Comment by mdlopresti** [comment]
Found the issue, PR to come

**Comment by jboliv01** [comment]
Hi @BigCat20196, we attempted to use the code snippet you provided, but it did not work for us. More specifically, it returned 7 days worth of data (6/1/2022 - 6/7/2022). We believe this may have to do with the fact we are under an Enterprise Agreement.

**Comment by BigCat20196** [comment]
Hi @jboliv01, I agree with you. Cost Management supports only Enterprise Agreement, Web direct and Microsoft Customer Agreement offer types. Actually, I gave the above sample based on my experience. Because our subscription types are different.

I found relevant definitions in `rest`. It seems that the API does not support filtering query results by date.
fyi: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/stable/2021-10-01/consumption.json#L119

Since the python SDK is generated based on the [rest API](https://github.com/Azure/azure-rest-api-specs), it will not deliberately change the returned results. So if you think the returned result is not as expected, please open the issue under the [rest issue](https://github.com/Azure/azure-rest-api-specs/issues).

**Comment by jboliv01** [comment]
Hi @BigCat20196, I believe the underlying API does support date filtering as I was able to successfully query the API with the following GET request: 

GET https://management.azure.com/subscriptions/{subscription}/providers/Microsoft.Consumption/usageDetails?$expand=properties/additionalInfo&api-version=2021-10-01&metric=actualcost&startDate=2022-04-01&endDate=2022-04-01

[https://docs.microsoft.com/en-us/rest/api/consumption/usage-details/list#customerusagedetailslist-modern](url)

**Comment by BigCat20196** [comment]
Hi @jboliv01, thanks for your reply! Adding params to operation coincides with a new feature of autorest.python5.15.0.
fyi: https://github.com/Azure/autorest.python/blob/autorestv3/ChangeLog.md#2022-04-07---5150

Python SDK is generated by [autorest.python](https://github.com/Azure/autorest.python) based on the [rest API](https://github.com/Azure/azure-rest-api-specs).  We will use the new version of autorest.python and support the feature you mentioned the next time we release the SDK. Thanks!

**Comment by jboliv01** [comment]
@BigCat20196 Any idea on the release cadence/next targeted release for the SDK? Thank you!

**Comment by BigCat20196** [comment]
Hi @jboliv01, new sdk released. You could use `headers` to add your parameters.

pipy link: https://pypi.org/project/azure-mgmt-consumption/10.0.0/
fyi: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_usage_details_operations.py#L160
