### ISSUE TITLE
URL for Button "Explore the Management API's" is landing in a page not found error. 

### ISSUE THREAD

**Issue by manojpotluri** [Azure/azure-sdk-for-python#24662]
Hyperlink redirect for Explore the Management API's Button is landing in a Page not found error
Hyperlink:
https://docs.microsoft.com/en-us/python/api/overview/azure/logicapps/management
![image](https://user-images.githubusercontent.com/453395/171461037-6c256432-79c5-44ec-8add-3962d68e8038.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5802e45-99a6-d29e-e596-b8f7befd3f31
* Version Independent ID: 5e7dfb18-e016-a077-7da3-3b9c4bb64744
* Content: [Azure Logic Apps libraries for python](https://docs.microsoft.com/en-us/python/api/overview/azure/logic-apps?view=azure-python)
* Content Source: [docs-ref-services/latest/logic-apps.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/logic-apps.md)
* Service: **multiple**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by catalinaperalta** [comment]
Thanks for reaching out @manojpotluri! Could you please open this issue in: https://github.com/MicrosoftDocs/azure-docs-sdk-python to get a fix. :)

**Comment by navba-MSFT** [comment]
@manojpotluri Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. We are looking into this and will provide an update soon.
