### ISSUE TITLE
[AMQP Python] Exception Parity

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#24680]
Currently between uamqp and Pyamqp we have different exceptions being handled (i.e Websocket TimeoutError on Pyamqp), we want to ensure that both uamqp and pyamqp have similar exceptions so that customers get similar exceptions across the board.

**Comment by kashifkhan** [comment]
@swathipil this will come in to play when you are working on the uamqp/pyamqp switch
