### ISSUE TITLE
Additional "runbook_type" available, update the documentation please

### ISSUE THREAD

**Issue by VictorHdzF** [Azure/azure-sdk-for-python#24694]
I've detected new values available:

'GraphPowerShellWorkflow'
'PowerShell7'
'Script'
'PowerShell'
'Python3'
'GraphPowerShell'
'Python2'
'PowerShellWorkflow'

Update the description https://docs.microsoft.com/en-us/python/api/azure-mgmt-automation/azure.mgmt.automation.models.runbook?view=azure-python#parameters -> runbook_type

thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a9351c-df68-0770-8ea5-3679fecef0ed
* Version Independent ID: 1343264c-4471-2af5-c7bc-03a266b103a8
* Content: [azure.mgmt.automation.models.Runbook class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-automation/azure.mgmt.automation.models.runbook?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-automation/azure.mgmt.automation.models.Runbook.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-automation/azure.mgmt.automation.models.Runbook.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by navba-MSFT** [comment]
@VictorHdzF Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@VictorHdzF The above PR has been filed. It is currently under review. If you have any questions in the meantime, please feel free to ask.
