### ISSUE TITLE
azure-mgmt-web list_skus() always returns empty list from Azure Mgmt API

### ISSUE THREAD

**Issue by rcampos87** [Azure/azure-sdk-for-python#24695]
I'm having the exact same issue as described in this issue https://github.com/Azure/azure-sdk-for-python/issues/6671 except with azure-mgmt-web 0.48.0 where the list_skus() return empty no matter which subscription i call it with. Even trying out https://docs.microsoft.com/en-us/rest/api/appservice/list-skus/list-skus results in an empty response.

- **Package Name**:  azure-mgmt-web
- **Package Version**:  0.48.0
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.10

**Describe the bug**
The list_skus() method returns an empty response { "value": [] } no matter which subscription I call it with. Even the Rest API documentation "try it" feature returns an empty response.

**Expected behavior**
A list of available skus is returned.

**Comment by Wzb123456789** [comment]
Hi @rcampos87,thank you for your feedback. 
After investigation, it is recommended that you use the latest version of `azure-mgmt-web`.

Read the doc linked below to help you understand how to effectively resolve issues.
fyi: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/issues/resolve_issues_effectively.md

**Comment by rcampos87** [comment]
@Wzb123456789 thank you for the reply, as of now we are unable to the anything past v0.48.0 because of the azure authentication method into the API, as I have seen,  for higher versions the authentication flow was changed or rewritten from the normal client_id, client_secret. The latest version of the Rest API found at https://docs.microsoft.com/en-us/rest/api/appservice/list-skus/list-skus does not work either and i assume the latest azure-mgmt-web also uses this endpoint.

**Comment by Wzb123456789** [comment]
Hi @rcampos87
The SDK is generated by [swagger](https://github.com/Azure/azure-rest-api-specs). The SDK receives and processes the data returned by the service. From the SDK's point of view, it cannot solve your problem.
It is recommended that you re-report the issue you encountered in https://github.com/Azure/azure-rest-api-specs/pulls

**Comment by navba-MSFT** [comment]
@rcampos87 Did you get a chance to look at the above suggestions provide by @Wzb123456789 . Please let us know if you need any further assistance on this thread. Awaiting your reply.

**Comment by rcampos87** [comment]
@navba-MSFT @Wzb123456789 thanks for the reply. I have opened a ticket with tech support for App Services that deals with Rest API, thanks for the help.

**Comment by navba-MSFT** [comment]
@rcampos87 Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
