### ISSUE TITLE
Exception when accessing the property compliance_results of the SecurityCenter class

### ISSUE THREAD

**Issue by michyweb** [Azure/azure-sdk-for-python#24696]
- **Package Name**: azure-mgmt-security
- **Package Version**: 1.0.0 and 2.0.0b1
- **Operating System**:Ubuntu 20.04
- **Python Version**: 3.8.10

**Describe the bug**
```py
Traceback (most recent call last):
  File "test7.py", line 16, in <module>
    list(x)
  File "/home/consultant/.local/lib/python3.8/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/home/consultant/.local/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/consultant/.local/lib/python3.8/site-packages/azure/mgmt/security/operations/_compliance_results_operations.py", line 111, in get_next
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (MissingApiVersionParameter) The api-version query parameter (?api-version=) is required for all requests.
Code: MissingApiVersionParameter
Message: The api-version query parameter (?api-version=) is required for all requests.
```

**To Reproduce**
```py
from azure.mgmt.security import SecurityCenter
from azure.identity import DeviceCodeCredential,  InteractiveBrowserCredential

subscription_id="*****"
AUTHORITY_HOST_URI="https://login.microsoftonline.com"
tenant_id="*****"
AZURE_CLI_CLIENT_ID="*****"

arm_credentials = DeviceCodeCredential(client_id=AZURE_CLI_CLIENT_ID, authority=AUTHORITY_HOST_URI, tenant_id=tenant_id)
#arm_credentials = InteractiveBrowserCredential(authority=AUTHORITY_HOST_URI,tenant_id=tenant_id,client_id=AZURE_CLI_CLIENT_ID)

scope = f'/subscriptions/{subscription_id}'

client = SecurityCenter(arm_credentials, subscription_id, 'westcentralus')
x= client.compliance_results.list(scope=scope)
list(x)
```

**Expected behavior**
No exception at all

**Workaround**
```py
from azure.mgmt.security import SecurityCenter
from azure.identity import DeviceCodeCredential,  InteractiveBrowserCredential

subscription_id="*****"
AUTHORITY_HOST_URI="https://login.microsoftonline.com"
tenant_id="*****"
AZURE_CLI_CLIENT_ID="*****"

arm_credentials = DeviceCodeCredential(client_id=AZURE_CLI_CLIENT_ID, authority=AUTHORITY_HOST_URI, tenant_id=tenant_id)
#arm_credentials = InteractiveBrowserCredential(authority=AUTHORITY_HOST_URI,tenant_id=tenant_id,client_id=AZURE_CLI_CLIENT_ID)

scope = f'/subscriptions/{subscription_id}'

client = SecurityCenter(arm_credentials, subscription_id, 'westcentralus')
x= client.compliance_results.list(scope=scope)
#list(x)

p=list()
try:
    for i in x:
        p.append(i)
except Exception :
    pass
print(p)
```

**Comment by BigCat20196** [comment]
Hi @michyweb, thanks for your feedback! After my investigation, this is due to the `next_link` returned by [rest API](https://github.com/Azure/azure-rest-api-specs)  error.

This is a normal `next_link`, should contain `skiptoken`, and it only contains '_ dynamic'.
normal: 
```https://management.azure.com/subscriptions/xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx/resources?%24api-version=2021-01-01&%24skiptoken=xxxxxx-xxxxxxxxx```
Its: 
```https://management.azure.com/_dynamic```
![image](https://user-images.githubusercontent.com/51037443/172552335-26828164-c923-45b8-9564-2e7fbaff6366.png)

You could try this to debug and get this error.
fyi: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md

Since the python SDK is generated based on the [rest API](https://github.com/Azure/azure-rest-api-specs),  it will not deliberately change the returned results.
Please go [here](https://github.com/Azure/azure-rest-api-specs/issues) to open a issue.

**Comment by navba-MSFT** [comment]
@michyweb Did you get a chance to look at the above suggestions provide by @BigCat20196 . Please let us know if you need any  further assistance on this thread. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@michyweb The action is currently pending on you to try the above suggestion. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by joBr99** [comment]
I'm able to reproduce this error and I'm getting the same errors @BigCat20196 is getting. 

@navba-MSFT There is no suggestion for a fix in the post, if the Issue belogs to the azure-rest-api-specs repo, the issue should be moved or a seperate issue should be created.
