### ISSUE TITLE
[Cosmos] clean up tests and add further configurations to testing matrix

### ISSUE THREAD

**Issue by simorenoh** [Azure/azure-sdk-for-python#24702]
Even though the SDK is now able to run consistently in the pipeline and causes no issues, we are missing further account configurations to be used in several tests that should be put in place to verify additional performance reliably. The Java SDK's setup files should be a good point for comparison.

There are also some tests that are currently disabled due to this - should look into getting those to work alongside this. Using this issue to track this work and to serve as a reminder.

Additionally, we should increase our test coverage to match that of Java/ .NET SDKs.

**Comment by simorenoh** [comment]
Part 1: https://github.com/Azure/azure-sdk-for-python/pull/24198

**Comment by simorenoh** [comment]
Part 2: https://github.com/Azure/azure-sdk-for-python/pull/24215/files

**Comment by kushagraThapar** [comment]
This is done.
