### ISSUE TITLE
receive_messages() is not thread safe in azure.storage.queue 

### ISSUE THREAD

**Issue by james-tn** [Azure/azure-sdk-for-python#24786]
- **Package Name**: azure.storage.queue 
- **Package Version**: azure-storage-queue==12.3.0
- **Operating System**: linux
- **Python Version**: 3.8.5

**Describe the bug**
I have multiple processes pulling from the same azure.storage.queue 
messages = queue_client.receive_messages(visibility_timeout=6*60,timeout=30)
    for message in messages:
       do some processing()

Some time, some process received the same message and while the time to process was less than a few seconds. At the end, all processes hang because they seemed to wait for same message that was already consumed.
Can someone explain the behavior?

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by james-tn** [comment]
@jalauzon-msft I need a queue service that can support multiple concurrent readers. Is there such a service like that? Is Service Bus such a thing?

**Comment by xiangyan99** [comment]
> @jalauzon-msft I need a queue service that can support multiple concurrent readers. Is there such a service like that? Is Service Bus such a thing?

@kashifkhan could you help to answer the question?

**Comment by kashifkhan** [comment]
> @jalauzon-msft I need a queue service that can support multiple concurrent readers. Is there such a service like that? Is Service Bus such a thing?

Hi @james-tn yes the Service Bus should be able to help you out in this scenario. Topics and subscriptions allow for one-to-many form of communication and you can get more details about them [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions).  The link to our SDK and samples is [here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/servicebus/azure-servicebus)
