### ISSUE TITLE
Azureml-core incompatible with azure-cli

### ISSUE THREAD

**Issue by MatthewGleeson** [Azure/azure-sdk-for-python#24787]
- **Package Name**: Azureml-core
- **Package Version**: 1.42
- **Operating System**: Windows
- **Python Version**: 3.8

**Describe the bug**

I'm trying to install this package in a python environment. In my requirements.txt, I have:

azure-cli==2.37.0
azureml-core==1.42.0

However, I get this error:

Cannot pip install both packages, the conflict is caused by:
azure-cli 2.37.0 depends on azure-mgmt-resource==21.1.0b1
azureml-core 1.42.0 depends on azure-mgmt-resource<=21.0.0 and >=15.0.0

These are the most recent versions of both packages, so I would expect them to be able to coexist in the same python environment. Is it possible to update the dependency on azure-mgmt-resource to allow 2.1.*?

I've tried relaxing dependencies on either side but the only compatibility I was able to find is azure-cli 2.37.0, azureml-core 1.14. However azureml-core 1.14 doesn't contain the modules that I need(azureml.core.LinkedService, azureml.core.compute.SynapseCompute)

**To Reproduce**

1. add packages to requirements.txt
2. pip install -r requirements.txt

**Expected behavior**

These are the most recent versions of both packages, so I would expect them to be able to coexist in the same python environment. 

**Additional context**

Cross-post on Azure-cli repository: https://github.com/Azure/azure-cli/issues/22816

**Comment by annatisch** [comment]
Thanks for the report @MatthewGleeson!
@luigiw - would you be able to direct this to the correct devs?
We should make sure to remove the upper bounds for the dependencies of other Azure packages in the new azure-ai-ml package

**Comment by luigiw** [comment]
@MatthewGleeson, we can look into upgrading `azureml-core`'s dependency on `azure-mgmt-resource`. In the meantime, I think Azure CLI recommends [installing the package](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) directly instead of having it in a Python environment. What's the reason you need a specific version of `auzre-cli` in your environment?

**Comment by raja7592** [comment]
Hi MatthewGleeson: We have addressed the issue. The fix will be rolled out in upcoming SDK release. Thanks for reporting the issue.

**Comment by mattmelton** [comment]
Please don't close things without letting the community know what the workaround is
