### ISSUE TITLE
[auto release] permit users to release any tag

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#24802]
Sometimes customers want to release an old tag instead of default tag in swagger readme. To meet the requirements, we need to:

(1) update swagger pipeline to permit additional configuration for autorest:
https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-sdk-tools/packaging_tools/auto_codegen.py#L26

the new item in `generate_input.json` will be `"python_tag": "..."`
(2) update auto_release pipeline to permit additional configuration for autorest:
https://github.com/Azure/azure-sdk-for-python/blob/main/scripts/auto_release/main.py#L175-L179

**Comment by BigCat20196** [comment]
test result: https://github.com/Azure/azure-sdk-for-python/pull/24809/files#diff-5bf4dccc78ca03222f701241453d7cf4c861363cd5ea8db1bd663a9d08ca3adeR54
