### ISSUE TITLE
"Warning: Discriminator source is absent or null, use base class ResourceDetails." when iterating SecurityAssessment object

### ISSUE THREAD

**Issue by nadavu** [Azure/azure-sdk-for-python#24815]
- **site-packages/azure/mgmt/security/operations/_assessments_operations.py**: 
- Module: **SecurityAssessmentList**
- **MacOS**:
- **Python Version- 3.8**: 

**Describe the bug**
getting this warning for every iteration over SecurityAssessmentList object.
`Discriminator source is absent or null, use base class ResourceDetails.`

**To Reproduce**
1. list of assessments:
```
assessments = client.assessments.list(scope=subscription.id)
assessments_requests = {}
for assessment in assessments:
      <etc...> 
```
2. get specific assessment:
`client.assessments.get(assessment_id, assessment.name, 'metadata')`

**Expected behavior**
no warnings

**Comment by nadavu** [comment]
related to https://github.com/Azure/azure-sdk-for-python/issues/13316 which wasn't fixed

**Comment by Wzb123456789** [comment]
Hi @nadavu Thanks for your feedback.
Since I can't reproduce your problem with the code you provided, please provide a more detailed code module to better solve your problem.

**Comment by nadavu** [comment]
> Hi @nadavu Thanks for your feedback. Since I can't reproduce your problem with the code you provided, please provide a more detailed code module to better solve your problem.

i guess the problem is with the assessment itself.
can you send me an example for  a valid assessment?

**Comment by nadavu** [comment]
@Wzb123456789 
`{'additional_properties': {},
 'id': '<SOME_ID>',
  'name': 'SOME_NAME',
   'type': 'Microsoft.Security/assessments',
    'resource_details': {'Source': 'Azure', 'Id': '<ID>'}, 
    'display_name': 'There should be more than one owner assigned to subscriptions', 
    'status': {'additional_properties': {}, 'code': 'Healthy', 'cause': None, 'description': None}, 
    'additional_data': {}, 
    'links': None, 
    'metadata': None, 
    'partners_data': None}`

**Comment by Wzb123456789** [comment]
Hi @nadavu 
After investigation, it was found that the cause of this error was a problem defined by swagger. Because the parameters defined by swagger and returned by service were inconsistent, resulting in deviations when the SDK was deserialized, this Warning was reported.

我已经在swagger上提了相关的issue:https://github.com/Azure/azure-rest-api-specs/issues/19530

**Comment by schumixmd** [comment]
/unresolve 
this seems to still be a problem
