### ISSUE TITLE
Inconsistent code

### ISSUE THREAD

**Issue by ShunChi100** [Azure/azure-sdk-for-python#24839]
"Adding documents to your index"and "Creating an index" codes are inconsistent. Cannot just copy and run.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b717f98-d488-97cb-ba1c-e98acf57ff3e
* Version Independent ID: 420a4d45-cabe-c129-7f47-a6b1ddbda10e
* Content: [Azure Cognitive Search client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/search-documents-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/search-documents-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/search-documents-readme.md)
* Service: **search**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by kashifkhan** [comment]
@ShunChi100 Thanks for your feedback, we'll investigate asap.

**Comment by xiangyan99** [comment]
Could you give more details?

e.g. what's the error?
