### ISSUE TITLE
Storage clients should handle AzureNamedKeyCredential as credential

### ISSUE THREAD

**Issue by bluenote10** [Azure/azure-sdk-for-python#24836]
**Is your feature request related to a problem? Please describe.**

The storage clients (blob, queue, ...) doesn't seem to support the type `AzureNamedKeyCredential`. This is inconsistent with many other parts of the API. For instance the table client allows it:

https://github.com/Azure/azure-sdk-for-python/blob/c8a02681b2cff658237e9ea117ee67e65a8c79ca/sdk/tables/azure-data-tables/azure/data/tables/_base_client.py#L76-L82

It is also frustrating that the `credential` is typed as `Any`.

https://github.com/Azure/azure-sdk-for-python/blob/c8a02681b2cff658237e9ea117ee67e65a8c79ca/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py#L71

This causes a lot of guessing what kind of credential the clients support 😕 

**Describe the solution you'd like**

The signature should get proper type annotations, and this function should simply handle `AzureNamedKeyCredential`.

https://github.com/Azure/azure-sdk-for-python/blob/c8a02681b2cff658237e9ea117ee67e65a8c79ca/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py#L348-L359

Perhaps the private type `SharedKeyCredentialPolicy` should be even completely be replaced by `AzureNamedKeyCredential`.

**Describe alternatives you've considered**

Type guessing and constantly converting from and to `AzureNamedKeyCredential` and the plain `{"account_name": str, "account_key": str}` that the blob storage wants.

**Comment by kashifkhan** [comment]
@bluenote10 Thanks for your feedback, we'll investigate asap.

**Comment by annatisch** [comment]
Thanks for this report @bluenote10!
You're 100% correct - this should be added. `AzureNamedKeyCredential` was added to Azure Core some time after the first stable Storage SDK releases - and it looks like we forgot to go back and add support for it. Thanks for calling this out. :)

**Comment by Stevenjin8** [comment]
@vincenttran-msft To add onto this, `AzureKeyCredential` also isn't supported. I'd be happy to try to help out with this.

**Comment by bupt-wenxiaole** [comment]
any update on this?  I also encountered issues that storage client does not support AzureNamedKeyCredential

**Comment by jalauzon-msft** [comment]
Hi @bupt-wenxiaole, support for `AzureNamedKeyCredential` was released in the latest version of each Storage package. For blob, that would be 12.4.1 (feature first added in [12.14.0b1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/CHANGELOG.md#12140b1-2022-08-23)). Please try with the latest version, thanks.
