### ISSUE TITLE
readinto function hangs while in progress

### ISSUE THREAD

**Issue by affanv14** [Azure/azure-sdk-for-python#24847]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.12.0
- **Operating System**: Amazon AL2
- **Python Version**: 3.7

**Describe the bug**
when calling the below piece of code - the download hangs indefinitely while in progress
`    with open(local_file, "wb") as f:
        download_stream = blob_client.download_blob(
        )
        download_stream.readinto(f)`

**To Reproduce**
1. Run the above piece of code on a file > 1gb

**Expected behavior**
The download should complete and the data should be stored in the file

**Additional context**
output below, hangs just after the last statement for 12+ hours
```

23:20:26.705 __main__.log_progress INFO 1086324736 bytes have been completed out of 1134174520
23:20:27.13 __main__.log_progress INFO 1090519040 bytes have been completed out of 1134174520
23:20:27.78 __main__.log_progress INFO 1094713344 bytes have been completed out of 1134174520
23:20:27.135 __main__.log_progress INFO 1098907648 bytes have been completed out of 1134174520
23:20:27.188 __main__.log_progress INFO 1103101952 bytes have been completed out of 1134174520
23:20:27.273 __main__.log_progress INFO 1107296256 bytes have been completed out of 1134174520
23:20:27.328 __main__.log_progress INFO 1111490560 bytes have been completed out of 1134174520
23:20:27.345 __main__.log_progress INFO 1113203000 bytes have been completed out of 1134174520
23:23:39.847 __main__.log_progress INFO 1117397304 bytes have been completed out of 1134174520
```

**Comment by kashifkhan** [comment]
@affanv14 Thanks for your feedback, we'll investigate asap.

**Comment by jalauzon-msft** [comment]
Hi @affanv14 Mohammed, thanks for the report. Can you share a bit about how you are tracking the progress of the download? Also are you setting the `max_concurrency` keyword in your call to `dnowload_blob`? There is a known issue with the previously recommended way to track progress (if you are using the SDK to do so) when performing a concurrent download where the progress would never reach 100%.

**Comment by affanv14** [comment]
Hi @jalauzon-msft we originally had it running without any keywords and it was hanging. We tried a bunch of things including max_concurrency. the last thing we tried was 
``` python
with open(local_file, "wb") as f:
        download_stream = blob_client.download_blob(
            progress_hook=log_progress,
            timeout=MAX_DOWNLOAD_WAIT_TIME,
            max_concurrency=NUM_DOWNLOAD_THREADS,
            read_timeout=MAX_DOWNLOAD_WAIT_TIME,
        )
        LOG.info("Download stream received from blob client")
        download_stream.readinto(f)
```

**Comment by jalauzon-msft** [comment]
Hi again @affanv14 Mohammed, thanks for sharing the sample. Can you also share a sample of how you are tracking the progress to show the output in your original post? This progress tracking output is not something I recognize so it must be custom on your end.

I'm trying to determine if the download itself is hanging or possibly the progress reporting is just never reporting that it's done. Thanks!

**Comment by affanv14** [comment]
``` python
def log_progress(completed: int, total: int) -> None:
    LOG.info("{} bytes have been completed out of {}".format(completed, total))
```

here is what we used to log progress

**Comment by affanv14** [comment]
There are statements after this(including a log statement right after) which is not reached. I am certain that it hangs on this. Furthermore, we previously had no params passed in the download_blob call - it was still having the issue

**Comment by jalauzon-msft** [comment]
Hi @affanv14 Mohammed, sorry for the long delay and thanks for confirming that `readinto` is indeed hanging.

The time the client will wait if there is no response from the server while reading data is configured via the `read_timeout` keyword and our default value is 80000 seconds (about 22 hours) (which is probably too high, and we are thinking of updating). I see you tried setting `read_timeout` for yourself to `MAX_DOWNLOAD_WAIT_TIME`? What is the value you used here? Did you wait for this length of time to see if some error eventually came back?

I think a good next step would be to enable debug logging so we can see the requests/responses happening and see if it is indeed hanging while waiting for a response of if something else is happening. Can you try enabling debug logging? Some documentation on how to do that is [here](https://docs.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-logging) but here is a code snippet from that documentation of all you should need (there are other ways to configure in article if needed):

```python
import sys
import logging
from azure.storage.blob import BlobClient

# Set the logging level for the azure.storage.blob library
logger = logging.getLogger('azure.storage.blob')
logger.setLevel(logging.DEBUG)

# Direct logging output to stdout. Without adding a handler,
# no logging output is visible.
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)

blob_client = BlobClient(..., logging_enable=True)
```

Thanks for your help and patience.
