### ISSUE TITLE
[CLU] arch board feedback / TODOs before release

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#24873]
So far, the checked things are covered by the swagger transforms.

- [x] Regenerate with latest DPG version and put authoring client under a `authoring` namespace. See this [branch readme](https://github.com/kristapratico/azure-sdk-for-python/blob/regen-clu-archboard/sdk/cognitivelanguage/azure-ai-language-conversations/swagger/README.md). Make sure we target a release branch for the GA.
- [x] Rename `ConversationAnalysisProjectsClient` -> `ConversationAuthoringClient`
- [x] Use swagger transforms to rename the following `get_*` operations to `list_*`
    - [x] get_model_evaluation_results
    - [x] get_supported_languages
    - [x] get_supported_prebuilt_entities
- [x] We're currently taking the liberty of renaming `import()` and `export()` to `begin_import_project()` and `begin_export_project()`, respectively. This is b/c `import` is a reserved keyword in Python and currently generates as `begin_import_method` w/o the rename. Double-check that `project` is the right suffix here for these operations.
- [x] Add some samples/tests/readme update for ProjectsClient
- [x] `multilingual` query param changed to bool
- [x] Ensure docstrings are correct for both clients and contain inputs/responses + descriptions
- [x] Rename `body` param to something like `project` (where it makes sense)
- [x] Revisit our swagger transforms -- are all of these necessary and do they align with .NET transforms? Should we adopt any renames that .NET is doing? See Heath's autorest.md -> https://github.com/heaths/azure-sdk-for-net/blob/f0273d93b5e8d6e53a20361770cf66329fc27116/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/autorest.md
- [x] Mention Language Studio in README (if we don't already)
- [x] Follow-up on why stringIndexType only has one option for some of the endpoints
- [x] [maybe] Put in place _patch of list_* operations that are broken b/c of not passing a required keyword only arg in the request call. This might get fixed in the generator before we release.
    - [x] list_model_evaluation_results
    - [x] list_supported_languages
    - [x] list_supported_prebuilt_entities
- [x] Support AAD
- [x] remove `maxpagesize` from operations

**Comment by kristapratico** [comment]
@mshaban-msft

**Comment by mshaban-msft** [comment]
@kristapratico - which authoring samples/tests do you think we should add?

**Comment by kristapratico** [comment]
Probably just one. I copied .NET's sample for the arch board: https://github.com/kristapratico/azure-sdk-for-python/blob/regen-clu-archboard/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_import_project.py
