### ISSUE TITLE
azure-ai-formrecognizer==3.2.0b5 -->  DocumentAnalysisClient not reading multiple page document with multiple invoices

### ISSUE THREAD

**Issue by Sankarganesh2020** [Azure/azure-sdk-for-python#24903]
- **Package Name**: azure-ai-formrecognizer==3.2.0b5
- **Package Version**:  azure-ai-formrecognizer==3.2.0b5
- **Operating System**: linux, windows
- **Python Version**:  3.9

**Describe the bug**
The form recognizer DocumentAnalysisClient for the prebuilt invoices is reading only the first page of the document.
In my document, i am having 2 invoices on page1 and pag2 respectively.
Ex: The document Invoice_May2022.pdf has 2 invoices. The invoice INV-0001 in page 1 and the invoice INV-0002 in page2 of the document.
The prebuild invoice model is read only the first page (i.e INV-0001) but the items are combined from 1st page and 2nd page (i.e Items of INV-0001 and INV-0002) .

**To Reproduce**
1. Use the sample program https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_invoices_async.py
2. Use the PDF document with multiple pages for multiple invoices.

**Expected behavior**
I expect the invoice prebuild model should read the document and retrurns 2 invoices from 2 pages with respective items

**Screenshots**

**Additional context**

**Comment by kristapratico** [comment]
Thanks for the feedback, @catalinaperalta can you take a look?

**Comment by catalinaperalta** [comment]
Thanks for reaching out @Sankarganesh2020! I ran tests using a multipage invoice and I do see that the service is returning one analyzed document instead of two. Looping in @vkurpad from the service side, could you help take a look at this?

**Comment by anatolip** [comment]
Current Invoice API assumes that whole input document is a single invoice and it does not do any document splitting. It selects value with highest confidence across all pages for each field.
It is possible to use "pages" parameter of invoice API to run model for each page independently and implement some post custom post-processing logic to merge results (i.e. if InvoiceId is different on the next page, start new invoice).

**Comment by dev-td** [comment]
> Current Invoice API assumes that whole input document is a single invoice and it does not do any document splitting. It selects value with highest confidence across all pages for each field. It is possible to use "pages" parameter of invoice API to run model for each page independently and implement some post custom post-processing logic to merge results (i.e. if InvoiceId is different on the next page, start new invoice).

Hi @anatolip , @vkurpad @catalinaperalta  Hope this hasn't been covered in another thread. Can you please let me know what parameter I should use in "pages" parameter in order to get two analyzed documents instead of one for the use case depicted above (i.e a 2 pages pdf where each page is a single page document to be analyzed). So far i've tried the following : 

`pages = "1,2"`
`pages = "1-1,2-2"`

But unfortunately :
`len(results["analyzeResult"]["documents"])` equals 1

In order to reproduce the result explained above you can use the following code as well as the attached pdf file.


```
import aiohttp
import asyncio
import io


async def analyze_docs(data):
   
    # Config
    modelId = "prebuilt-invoice"
    pages = "1,2" # pages = 1,1 or pages = 1-1,2-2 or other ?
    url = f"https://westeurope.api.cognitive.microsoft.com/formrecognizer/documentModels/{modelId}:analyze?api-version=2022-08-31&pages={pages}"
    headers = {
        "Content-Type": "application/octet-stream",
        "Ocp-Apim-Subscription-Key": "...",
    }

    # Post request
    analyze_request_successful = False
    async with aiohttp.ClientSession(headers=headers) as session:
        while not analyze_request_successful:
            response = await session.post(url=url, data=data)
            if response.status in [200, 202]:
                callback = response.headers["Operation-Location"]
                break

    # Get results request
    headers = {"Ocp-Apim-Subscription-Key": "..."}
    get_results_request_successful = False
    async with aiohttp.ClientSession(headers=headers) as session:
        while not get_results_request_successful:
            response = await session.get(callback)
            results = await response.json()
            if "status" in results:
                if results["status"] == "succeeded":
                    break

    nb_docs = len(results["analyzeResult"]["documents"])  # Equals to 1 instead of 2 as expected.
    return nb_docs


async def main() -> None:

    path_to_file = f"2_docs_to_analyse.pdf"

    with open(path_to_file,"rb") as f:
        stream = f.read()

    # await
    await analyze_docs(stream)


if __name__ == "__main__":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(main())

```
[2_docs_to_analyse.pdf](https://github.com/Azure/azure-sdk-for-python/files/10326019/2_docs_to_analyse.pdf)
