### ISSUE TITLE
Please enter password for encrypted keyring

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-sdk-for-python#2494]
During the custom Linux build agent deployment for Visual Studio Team Services (Ubuntu Server 18.04-LTS) I noticed that there is an issue with something I did not noticed previously on Ubuntu Server and I'm not noticing on my Mac OS X. When I'm trying to run Python (3.6) script, which is using Azure SDK, I'm receiving interactive prompt "Please enter password for encrypted keyring". It's not a problem to create keyring and provide a password when running script interactively but when we are talking about automation or in a context of VSTS it is not acceptable to have any interactive steps in the process. I have started some investigation on that: https://lnx.azurewebsites.net/please-enter-password-for-encrypted-keyring-when-running-python-script-on-ubuntu/

The root cause is File "/usr/local/lib/python3.6/dist-packages/msrestazure/azure_active_directory.py", line 207, in _default_token_cache

where Ubuntu 18.04 (and 17.10), when installing python3-pip package is, by default, also installing python3-wheel, python3-keyring and python3-keyrings.alt.

SO, by default, msrestazure is trying to use system keyring, prompting for password. It's hard to automate anythong, having interactive prompt.

If there is a keyring-enabled solution, please provide it in the documentation. If not, maybe you should consider using PlaintextKeyring() by default?

**Comment by lmazuel** [comment]
Keyring will be removed in msrestazure 0.5.0 planned for August. The workaround is the one to use in the meantime. Closing the issue.
