### ISSUE TITLE
ServiceBus not respecting environment variables HTTP[S]_PROXY

### ISSUE THREAD

**Issue by mbelak-dtml** [Azure/azure-sdk-for-python#24959]
- **Package Name**: azure-servicebus
- **Package Version**: 7.6.1
- **Operating System**: Linux (ubuntu 20.04)
- **Python Version**: 3.9.12

**Describe the bug**
The Service Bus SDK ignores setting of variables HTTP_PROXY and HTTPS_PROXY.

**To Reproduce**
0. Set up a proxy server. You can use for example squid in docker
  a. Terminal 1 - run proxy
  `docker run --rm --name squid alpine /bin/sh -c "apk --no-cache add squid && squid -N"`

  b. Terminal 2 - run scripts here
  `export http_proxy="http://$(docker inspect squid | grep '"IPAddress":' | head -n 1 | cut -d'"' -f4):3128"`
  `export https_proxy="http://$(docker inspect squid | grep '"IPAddress":' | head -n 1 | cut -d'"' -f4):3128"`
1. Send a message to a service bus topic via `azure-servicebus` SDK
2. The Azure Service Bus SDK is not communicating via the proxy.
3. If your network is setup to only allow communication via the proxy, you get 
```
azure.servicebus.exceptions.ServiceBusConnectionError: Unable to open authentication session on connection b'SBSender-<REDACTED ID>'.

Please confirm target hostname exists: b'[<REDACTED SBN NAME>.servicebus.windows.net]'
```

**Expected behavior**
Service bus SDK should respect the the environment variables HTTP_PROXY and HTTPS_PROXY and route all traffic through the specified proxies, as specified by [Microsoft Azure SDK documentation](https://docs.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-configure-proxy?tabs=cmd#global-configuration).

**Screenshots**

**Additional context**

**Comment by kristapratico** [comment]
Hi @mbelak-dtml thanks for your issue, we'll take a look asap.

**Comment by mbelak-dtml** [comment]
Hi, yes, I have been able to use a proxy using the provided example.

However, it has taken some time to debug this issue since the Azure SDK documentation states that all client libraries should follow the proxy configuration provided by environment variables and the error message is not very helpful.

**Comment by l0lawrence** [comment]
Awesome! @mbelak-dtml we will look into aligning the two to avoid this in the future, thank you! [Issue Created](https://github.com/Azure/azure-sdk-for-python/issues/25002)

**Comment by swathipil** [comment]
Since the `proxy.py` sample works and a new issue has been created to resolve issues with documentation, looks like this issue has been addressed.
