### ISSUE TITLE
Setting timeout on the autorest python client 

### ISSUE THREAD

**Issue by Sreevisakh1985** [Azure/azure-sdk-for-python#24951]
Hello,

How do I specify timeouts for the auto rest python client ?  I have followed the [docs](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/README.md#configurations) , and tried to pass connection_timeout to the clients. And it didn't work. Read_time out did work, but I am looking for timeout on the connection.  I do see there's another variable timeout, can this be used ? I tried passing this to the client and it didn't work.  Apprecitae your assistene here. 

Thanks, 
Sree

**Comment by Sreevisakh1985** [comment]
Hi @kristapratico  thanks for the quick response. 
Here are the libraries and  versions

`
  Auto rest - 3.5.0
  Auto rest core - 3.6.4
` 

Here's the sample code used to call one of the auto rest generated operations 

```
ServiceClient(base_url="http://localhost:8000"
                          ).events.get_event(event_id = "" , read_timeout= 4 ) 
```

 I tried to use connection_timeout as well, but that didn't work 

Let me know if you need any additional details. Thank you

**Comment by xiangyan99** [comment]
May I ask how you detected connection_timeout did not work?

**Comment by Sreevisakh1985** [comment]
Its detected during one of our performace tests, where we created a congestion at the server side. And my understanding is connection_timeout is used limit the time of establishing connection b\w client and server.  Please correct me if I am wrong.

**Comment by xiangyan99** [comment]
Thanks for your information.

Given your code uses sync method, and we call into requests library, can you try

r = requests.get(YOUR_URL, timeout=(300, 300))

and see if it works?

Thanks.

**Comment by Sreevisakh1985** [comment]
Thank you.  
I was under the assumption that timeout is just a float value ? What are these values in this tuple meant (300, 300) ?

**Comment by xiangyan99** [comment]
https://requests.readthedocs.io/en/latest/user/advanced/.

The timeout value will be applied to both the connect and the read timeouts. Specify a tuple if you would like to set the values separately:

r = requests.get('https://github.com', timeout=(3.05, 27))

The tuple is (connection_timeout, read_timeout).

If you don't specify the read timeout, it defaults to 300s (5 mins).

**Comment by Sreevisakh1985** [comment]
Sorry , confused here. I am not using the requests object directly, instead I am using the auto rest generated client to make the api calls. And seems like timeout as a tuple is not allowed in the client.

**Comment by xiangyan99** [comment]
When you use auto generated client and only specify connection_timeout as a float, we (azure-core) make it into a tuple with appending default read_timeout 5 mins and pass it into requests library.

**Comment by Sreevisakh1985** [comment]
Okay, so I have to specify both the values like this.  ` ServiceClient(base_url="http://localhost:8000").operation.get_foo( connection_timeout=4,
                               read_timeout=4)`  . right ?

**Comment by xiangyan99** [comment]
Both of the default setting of connection_timeout and read_timeout are 5 mins.

If you don't specify, we use the default value.

Given you said connection_timeout did not work, I assume you only set one hence in your test, you had connection timeout for 4 sec but read timeout for 5 mins.

So I guess the answer is yes. :)

**Comment by Sreevisakh1985** [comment]
I tried both, but didn't set them together. Its workig now.. Thanks  for the quick responses
