### ISSUE TITLE
Blob base_client.py precludes use of non-public azure endpoints

### ISSUE THREAD

**Issue by dfencegit** [Azure/azure-sdk-for-python#24957]
- **azure-storage-blob**: 
- **12.12.0**: 
- **Any**:
- **Any**: 

**Describe the bug**
The Blob service base_client.py code uses a hardcoded value "core" to split the account name from the parsed url string but the use of the word "core" in the split string precludes using this code against anything but public Azure for example this will not work against and Azure Stack Hub storage endpoint.

**To Reproduce**
Attempts to use this code against a non-public Azure storage endpoint such as one on Azure Stack Hub results in a failure to aprse the account name from the url and therefore it throws an error as below where for example the endpoint url is set to "https://accountname.region1.stack1.example"

  File "/app/lib/python3.8/site-packages/azure/storage/blob/_blob_service_client.py", line 126, in __init__
    super(BlobServiceClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "/app/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 93, in __init__
    self.credential = _format_shared_key_credential(self.account_name, credential)
  File "/app/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 337, in _format_shared_key_credential
    raise ValueError("Unable to determine account name for shared key credential.")

**Expected behavior**
Split the account name from the endpoint url without using the "core" keyword, surely the account name is just the first element of the url when split by "."

**Comment by kristapratico** [comment]
Hi @dfencegit, thanks for your feedback. @jalauzon-msft @vincenttran-msft can you take a look at this?

**Comment by dfencegit** [comment]
Hi @vincenttran-msft thanks for your help on this, if we take the approach of using credential parameter does it not append the standard "blob.core.windows.net" dns path to get the full address and so we end up with a similar problem in that we cant use this to hit a non-public azure endpoint.

Thanks.

**Comment by jalauzon-msft** [comment]
Hi @dfencegit Anthony, if you go with the approach mentioned above, the SDK should not modify your URL in any way. Please let us know if this is not the case. Thanks!
