### ISSUE TITLE
disk/list snapshots doesn't respect "resource_group"

### ISSUE THREAD

**Issue by yfried** [Azure/azure-sdk-for-python#2496]
Most `list()` calls (such as `compute.virtual_machines.list`) accept resource group name as input. `disks` and `snapshots` `list()` methods don't.

**Comment by lmazuel** [comment]
Yes there is :)
- https://docs.microsoft.com/en-us/python/api/azure.mgmt.compute.v2017_03_30.operations.disksoperations?view=azure-python#list-by-resource-group
- https://docs.microsoft.com/en-us/python/api/azure.mgmt.compute.v2017_03_30.operations.snapshotsoperations?view=azure-python#list-by-resource-group

It's just that `list` is per subscription, and `list-by-resource-group` per RG
