### ISSUE TITLE
Default API Version in ResourceManagementClient class fails (AzureUSGovernment and AzureCloud)

### ISSUE THREAD

**Issue by RDukes425** [Azure/azure-sdk-for-python#24961]
When trying to execute an operation under the ResourceManagementClient class to list a Log Analytics Workspace by Resource ID, the results return an API version failure for workspaces. 
Reference: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L59

Previous Issues Submitted: 
https://github.com/Azure/azure-rest-api-specs/issues/18857 
https://github.com/Azure/CloudShell/issues/177 

**Customer Error**
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'usgovvirginia' and API version '2021-04-01' for type 'workspaces'. The supported api-versions are '2014-10-10, 2014-11-10, 2015-03-20, 2015-11-01-preview, 2017-01-01-preview, 2017-03-03-preview, 2017-03-15-preview, 2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2020-10-01, 2021-06-01, 2021-03-01-privatepreview, 2021-12-01-preview'. The supported locations are 'usgovvirginia, usgovarizona'.

My Repro
**AzureUSGovernment**
== VS Code ==
from azure.identity import AzureCliCredential
from azure.mgmt.resource import ResourceManagementClient

cred = AzureCliCredential()
gov_arm_ep = 'https://management.usgovcloudapi.net'

sub_id = '9ea57abb-990d-4601-94b5-2a2a6d418274'

client = ResourceManagementClient(cred,
sub_id,
base_url=gov_arm_ep,
credential_scopes=[f'{gov_arm_ep}/.default']
)

rid = f'/subscriptions/{sub_id}/resourceGroups/Renata-RG/providers/Microsoft.OperationalInsights/workspaces/RenataLA'

this = client.resources.get_by_id(rid, client.DEFAULT_API_VERSION)

print(this.as_dict())

== Results ==
PS C:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)> az cloud set --name AzureUSGovernment
PS C:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)> az login
The default web browser has been opened at https://login.microsoftonline.us/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
a369b2ec-c26c-4636-b8d1-5ee209fc102a 'CXP ACE Gov Secondary'
c44ade71-bb5c-4c53-96d1-332c07dd0460 'CXP ACE B2C Tenant'
[
{
"cloudName": "AzureUSGovernment",
"homeTenantId": "7f59db05-b34e-432e-a39f-7f2051cd8e48",
"id": "9ea57abb-990d-4601-94b5-2a2a6d418274",
"isDefault": true,
"managedByTenants": [],
"name": "CXP ACE Gov Internal Subscription",
"state": "Enabled",
"tenantId": "7f59db05-b34e-432e-a39f-7f2051cd8e48",
"user": {
"name": "RDukes@cxpacegov.onmicrosoft.us",
"type": "user"
}
},
{
"cloudName": "AzureUSGovernment",
"homeTenantId": "7f59db05-b34e-432e-a39f-7f2051cd8e48",
"id": "1100a2a2-582a-4699-9aae-c82eee34d2a3",
"isDefault": false,
"managedByTenants": [],
"name": "Azure Government Internal Test",
"state": "Enabled",
"tenantId": "7f59db05-b34e-432e-a39f-7f2051cd8e48",
"user": {
"name": "RDukes@cxpacegov.onmicrosoft.us",
"type": "user"
}
},
{
"cloudName": "AzureUSGovernment",
"homeTenantId": "7f59db05-b34e-432e-a39f-7f2051cd8e48",
"id": "bc5a55a3-4e0d-49a9-b096-fb3603d32d7f",
"isDefault": false,
"managedByTenants": [],
"name": "Azure Government Free Trial",
"state": "Enabled",
"tenantId": "7f59db05-b34e-432e-a39f-7f2051cd8e48",
"user": {
"name": "RDukes@cxpacegov.onmicrosoft.us",
"type": "user"
}
}
]
PS C:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)>
PS C:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)> & C:/Users/redukes/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/redukes/OneDrive - Microsoft/Documents/Visual Studio 2019/Python Scripts/Python 3.9 (64-bit)/.vscode/kvtest1 copy 2.py"
Traceback (most recent call last):
File "c:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)\.vscode\kvtest1 copy 2.py", line 17, in <module>
this = client.resources.get_by_id(rid, client.DEFAULT_API_VERSION)
File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\mgmt\resource\resources\v2020_06_01\operations\_resources_operations.py", line 1496, in get_by_id
raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2020-06-01' for type 'workspaces'. The supported api-versions are '2014-10-10, 2014-11-10, 2015-03-20, 2015-11-01-preview, 2017-01-01-preview, 2017-03-03-preview, 2017-03-15-preview, 2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2020-10-01, 2021-06-01, 2021-03-01-privatepreview, 2021-12-01-preview'. The supported locations are 'usgovvirginia, usgovarizona'.

**AzureCloud**
== Results ==
PS C:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)> az cloud set --name AzureCloud
Switched active cloud to 'AzureCloud'.
The subscription of '1e46bfb7-6875-4935-998d-6f92edd95126' doesn't exist in cloud 'AzureCloud'.
Unable to automatically switch the active subscription. Use 'az account set'.
PS C:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)> az login
The default web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "71c7016c-946d-49c2-83ef-c996202952d0",
    "id": "b355d666-7856-4577-a411-b29607ee4c4f",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Pay-As-You-Go",
    "state": "Enabled",
    "tenantId": "71c7016c-946d-49c2-83ef-c996202952d0",
    "user": {
      "name": "renata.dukes@yahoo.com",
      "type": "user"
    }
  }
]
PS C:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)> & C:/Users/redukes/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/redukes/OneDrive - Microsoft/Documents/Visual Studio 2019/Python Scripts/Python 3.9 (64-bit)/.vscode/kvtest1 copy 3.py"
Traceback (most recent call last):
  File "c:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)\.vscode\kvtest1 copy 3.py", line 17, in <module>
    this = client.resources.get_by_id(rid, client.DEFAULT_API_VERSION)
  File "C:\Users\redukes\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\mgmt\resource\resources\v2020_06_01\operations\_resources_operations.py", line 1496, in get_by_id
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'southcentralus' and API version '2020-06-01' for type 'workspaces'. The supported api-versions are '2015-03-20, 2015-11-01-preview, 2017-01-01-preview, 2017-03-03-preview, 2017-03-15-preview, 2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2020-10-01, 2021-06-01, 2021-03-01-privatepreview, 2021-12-01-preview'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiacentral, australiaeast, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacentral2, uaecentral, uaenorth, japanwest, brazilsoutheast, norwayeast, norwaywest, francesouth, southindia, koreasouth, jioindiacentral, jioindiawest, canadaeast, westus3, swedencentral'.
PS C:\Users\redukes\OneDrive - Microsoft\Documents\Visual Studio 2019\Python Scripts\Python 3.9 (64-bit)>

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
Hi, @RDukes425, according to log info:
```
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'usgovvirginia' and API version '2021-04-01' for type 'workspaces'. The supported api-versions are '2014-10-10, 2014-11-10, 2015-03-20, 2015-11-01-preview, 2017-01-01-preview, 2017-03-03-preview, 2017-03-15-preview, 2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2020-10-01, 2021-06-01, 2021-03-01-privatepreview, 2021-12-01-preview'. The supported locations are 'usgovvirginia, usgovarizona'.
```
The error is returned by service server. Since SDK is just to send/receive http request/response to/from service server, we can't solve the server problem. I notice you have opened an issue in right place https://github.com/Azure/azure-rest-api-specs/issues/18857 so please ask for help in that issue
