### ISSUE TITLE
Tests should run without network access and be consistent in PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#24977]
**Is your feature request related to a problem? Please describe.**
I package various Azure SDK components in Fedora Linux for use with `azure-cli`, and one of my frustrations is around running tests. During RPM builds, no network access is allowed. However, many of the SDK tests require network access or they have a VCR cassette that is outdated. This prevents me from running tests.

I've reviewed how Arch and Debian packagers are handling this challenge and many of them are disabling many tests or simply not testing at all. To make matters worse, some of the PyPi packages for certain SDK components contain tests, and some do not. Some of them contain the VCR recordings for tests, and others do not. This requires me to get the source code from the git repository so I can be sure I have all of the tests and recordings. However, I must download the entire repository (> 100MB) just to get the 1-2MB of code that I really care about.

Some tests, such as the ones for `azure-mgmt-network`, require me to run `docker` during tests, which includes downloading a remote container.

**Describe the solution you'd like**
I'd like to see:

* SDK tests run without network dependencies
* Tests and VCR recordings either included or excluded consistently in PyPi packages

**Describe alternatives you've considered**
Sometimes I have to disable some or all of the tests for a particular part of the SDK. For some, such as `azure-mgmt-network`, I must disable all of the tests to build the package successfully. This creates issues later when I get bugs from users or when I package `azure-cli` and its tests break when importing command modules.

**Comment by Wzb123456789** [comment]
Hi @major, thank you for your feedback. 

According to your issue description:

If you want SDK tests run without network dependencies, you can set the environment variable `AZURE_TEST_RUN_LIVE` to "false". See [link](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/mgmt/tests.md#running-tests-in-live-mode) for detailed explanation.

Currently SDK tests are run in docker

**Comment by major** [comment]
> If you want SDK tests run without network dependencies, you can set the environment variable `AZURE_TEST_RUN_LIVE` to "false". See [link](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/mgmt/tests.md#running-tests-in-live-mode) for detailed explanation.

I'm using that environment variable now in my package builds, but the challenge there is that packages are published inconsistently to PyPi:

- Some packages have no tests
- Some packages have tests, but VCR recordings are missing
- Some packages have both tests and VCR recordings, but they still try to make connections across the internet

My expectation would be that:

- Every package has tests/recordings published to PyPi consistently
- No package requires network connectivity to run tests

> Currently SDK tests are run in docker. https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/mgmt/tests.md#writing-management-plane-test

Again, this requires network access (to download container images) and the ability to run a container for the test. Neither of these are available to OS packagers when they build their packages.

**Comment by lmazuel** [comment]
Hi @major ,

There is two parts to your question:
- Get tests in sdist 
- Run tests without docker

For the first part, I agree with you, we should package the tests in the sdist, including recordings.

For the second part, we are moving away from `vcrpy` as a dependency, and we moved to a system that requires an actual mock server to run to replay the tests. This means either Docker (or Podman work as well and don't require a daemon) or to run the server manually with the dotnet cli. 

I do recognize that running a mock server might be challenging, and we're working on a set of pytest fixtures to allow you to run unittests only, and skip recorded tests. It means you won't get the full coverage, but you'll get enough smoke tests and unittests to confirm your packaging is working as expected at least at load time.

Would that solve your issues?
Thanks!

**Comment by major** [comment]
> For the first part, I agree with you, we should package the tests in the sdist, including recordings.

That would be super helpful! I've made some PRs in the past to get this working in the templates, but azure-cli still calls for very old versions of some azure-sdk-for-python packages.

> For the second part, we are moving away from `vcrpy` as a dependency, and we moved to a system that requires an actual mock server to run to replay the tests. This means either Docker (or Podman work as well and don't require a daemon) or to run the server manually with the dotnet cli.
> 
> I do recognize that running a mock server might be challenging, and we're working on a set of pytest fixtures to allow you to run unittests only, and skip recorded tests. It means you won't get the full coverage, but you'll get enough smoke tests and unittests to confirm your packaging is working as expected at least at load time.
> 
> Would that solve your issues? Thanks!

Honestly, it might be easier for me to get some of the dotnet cli working in a test than it would be for something running in docker/podman. Either way the pytest fixtures (or perhaps marks?) would help me at least run some tests to ensure everything is packaged properly.

Are there any SDK packages where I could give this a try today? Or, is this all future planned work?

Thanks!

**Comment by msyyc** [comment]
We do include `tests` in sdist but recording files are not included since current recording files are .json files after migration to [testproxy](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/test_proxy_migration_guide.md). We will update the [template](https://github.com/Azure/azure-sdk-for-python/blob/c639ff1f5ad3033fca125e6926550fa8dca245d7/tools/azure-sdk-tools/packaging_tools/templates/MANIFEST.in#L2) to ensure the recording files are included in sdist.
