### ISSUE TITLE
need a sample for creating access package using python sdk

### ISSUE THREAD

**Issue by gpnikhil** [Azure/azure-sdk-for-python#24974]
Im trying to find a proper sdk module which fits my requirement of creating a access package in azure AD - identity governance using python sdk

**Comment by xiangyan99** [comment]
Thanks for reaching out. 

Could you give more details about the access package?

**Comment by gpnikhil** [comment]
You can look at this, I want to create the same using python sdk

https://docs.microsoft.com/en-us/azure/active-directory/governance/entitlement-management-access-package-create

**Comment by xiangyan99** [comment]
Thanks for the information.

Adding graph team.

**Comment by xiangyan99** [comment]
@dkershaw10 @baywet

**Comment by baywet** [comment]
@gpnikhil I believe the equivalent for Microsoft Graph is [this endpoint](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackages?view=graph-rest-1.0&tabs=http) (the AAD graph is getting deprecated).

The team is working hard to get a chained style Python SDK out (like we have in .NET/Java/Go...) while it's not out yet (probably still a couple of weeks away), you can use the core SDK to handle some concerns for you. https://github.com/microsoftgraph/msgraph-sdk-python-core

**Comment by gpnikhil** [comment]
Hi Team, 

Thank you for the update.

I have one more thing to ask, graph authentication for Service principal for the Graph API, how can i do that ?

**Comment by baywet** [comment]
By service principal I'm guessing you're referring to managed identity (credentials are handled by the Azure service your code is running on)?
This should be possible via the default Azure credentials https://pypi.org/project/azure-identity/ which will read environment variables set by the Azure Service before your application is started.

Also @samwelkanda who is the maintainer of the Python Graph SDK.
