### ISSUE TITLE
AzureBlobDatastore needs AccountKeyCredentials

### ISSUE THREAD

**Issue by gisandnes** [Azure/azure-sdk-for-python#24973]
- azure.ai.ml: 
- 0.1.0b4: 
- MacOS 12.4:
- 3.8.12: 

**Describe the bug**
In Jupyter notebook https://github.com/Azure/azureml-examples/blob/main/sdk/resources/datastores/datastore.ipynb the section "2.1.1 Create a datastore with account key" did not work

**To Reproduce**
blob_datastore1 = AzureBlobDatastore(
    name="blob-example",
    description="Datastore pointing to a blob container.",
    account_name="mytestblobstore",
    container_name="data-container",
    credentials={
        "account_key": "XXXxxxXXXxXXXXxxXXXXXxXXXXXxXxxXxXXXxXXXxXXxxxXXxxXXXxXxXXXxxXxxXXXXxxxxxXXxxxxxxXXXxXXX"
    },
)
ml_client.create_or_update(blob_datastore1)

had to replaced by:

from azure.ai.ml.entities._datastore.credentials import AccountKeyCredentials
blob_datastore1 = AzureBlobDatastore(
    name="blob-example",
    description="Datastore pointing to a blob container.",
    account_name="mytestblobstore",
    container_name="data-container",
    credentials=AccountKeyCredentials(account_key=
    								  "XXXxxxXXXxXXXXxxXXXXXxXXXXXxXxxXxXXXxXXXxXXxxxXXxxXXXxXxXXXxxXxxXXXXxxxxxXXxxxxxxXXXxXXX"
    								  ),
)
ml_client.create_or_update(blob_datastore1)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Man-MSFT** [comment]
Thanks for the bug report @gisandnes! We will fix the example notebook.

**Comment by Man-MSFT** [comment]
Hi @gisandnes, we have merged a fix to the [datastore notebook](https://github.com/Azure/azureml-examples/blob/main/sdk/resources/datastores/datastore.ipynb), fixing the credentials typing issue.

**Comment by navba-MSFT** [comment]
Thanks @Man-MSFT for fixing this.

@gisandnes Could you please test the updated sample from this  https://github.com/Azure/azureml-examples/blob/main/sdk/resources/datastores/datastore.ipynb and let us know if you face any issues ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@gisandnes The action is currently pending on you to test the updated sample. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
