### ISSUE TITLE
Not able to read/write Azure service bus with python SDK.

### ISSUE THREAD

**Issue by bittu1985** [Azure/azure-sdk-for-python#24987]
Getting below exception while reading /writing from service bus and the code when am trying to read from my dev environment by am able to read & write from service bus explorer.Pls help.

azure.servicebus.exceptions.ServiceBusConnectionError: Unable to open authentication session on connection b'SBSender-9394685d-f9cc-4183-bc8e-90bbd7fa1d81'.
Please confirm target hostname exists: b'xxxx.servicebus.windows.net'

**Comment by l0lawrence** [comment]
Hi @bittu1985, thanks for the feedback. We will investigate asap.
