### ISSUE TITLE
azureml-dataset-runtime (failed to build numpy)

### ISSUE THREAD

**Issue by nagydavid** [Azure/azure-sdk-for-python#25018]
- azureml-dataset-runtime: 
- 1.43.0: 
-  macOS Monterey (Silicon M1 Pro):
- 3.8.13, 3.9.13, 3.10.4: 

**Describe the bug**
```
ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
[end of output]
```
**To Reproduce**
```
pip install azureml-dataset-runtime
```
**Expected behavior**
Library installs as expected
**Screenshots**

**Additional context**
[error_msg.txt](https://github.com/Azure/azure-sdk-for-python/files/9009074/error_msg.txt)

**Comment by l0lawrence** [comment]
Hi @nagydavid thanks for the feedback. We will investigate asap. @azureml-github

**Comment by luigiw** [comment]
@nagydavid Thx for providing the feedback. This issue sounds like is caused by numpy not being supported natively on M1. haven you also reported this to numpy? One workaround is to use Rosetta to run Python on your M1 Mac.

**Comment by nagydavid** [comment]
So according to the installation logs, the library dependent on 1.19.4, where the latest release of numpy is 1.23.0

**Comment by nagydavid** [comment]
Hi @bandsina @luigiw @l0lawrence 
May I have an update on the possible solutions? 

Thanks in advance

**Comment by anliakho2** [comment]
@nagydavid Sorry to be a bearer of bad news, but M1 is currently not officially supported. We do have work planned to add support for M1, but exact timeframe is currently uncertain.
As a work around you can use x86 compatible python environment, like this one for conda:

https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12

```
CONDA_SUBDIR=osx-64 conda create -n myenv_x86 python=3.9
conda activate myenv_x86
conda config --env --set subdir osx-64
```

**Comment by nagydavid** [comment]
Thanks for the answer @anliakho2 :)

**Comment by DanielGumbletonWood** [comment]
Hi, i am getting this issue, i cannot install the library on my M1 pro

**Comment by Waddaben** [comment]
Hi, I am also still getting this issue, /unresolve

**Comment by lloydhamilton** [comment]
I am also getting the same issue:

macOS Monterey 12.5
Apple M1 Pro
Python 3.8.13

```
 × Encountered error while trying to install package.
      ╰─> numpy
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

To reproduce:
```
pip install azureml-dataset-runtime
```

**Comment by AsimKarel** [comment]
I am facing same issue on Windows Python version 3.10.4

**Comment by MoElias1** [comment]
Have the same problem, M1, Mac OS Ventura, python 3.9.6!

**Comment by HeathArhturLouis** [comment]
Same here, M1, Mac OS, Python 3.9.6

**Comment by luigiw** [comment]
@anliakho2 Can you provide an update on this issue? Thank you.

**Comment by rpryzant** [comment]
Same here on M2 macbook air

**Comment by rpryzant** [comment]
Same issue here, M2 macbook air

**Comment by Dekermanjian** [comment]
Hey I am having the same issue with M1 Mac on Sonoma 14.2.1 using python 3.10. Has there been any movement on this issue?
