### ISSUE TITLE
How to run next step as a graph in azure ai ml sdk2

### ISSUE THREAD

**Issue by rjtshrm** [Azure/azure-sdk-for-python#25020]
- **Package Name**:  az.ai.ml
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
I am running different steps in azure ai ml using **command** api. But they are running in random order. I want to run them sequentially. I don't have any data injection from previous step to next step as I am saving the output of one step on cloud storage and next step will fetch that one once the previous step is finished running. I tried to create fake_op (uri_string) for one step and gave input to the very next step. Doing this I am getting error.

    {'code': data-capability.UriMountSession.UserErrorException, 'message': UserErrorException:
    	Message: DataAccessError(NotFound)
    	InnerException None
    	ErrorResponse 
    {
        "error": {
            "code": "UserError",
            "message": "DataAccessError(NotFound)"
        }
    }, 'target': , 'category': UserError, 'error_details': [{'key': NonCompliantReason, 'value': UserErrorException:
    	Message: DataAccessError(NotFound)
    	InnerException None
    	ErrorResponse 
    {
        "error": {
            "code": "UserError",
            "message": "DataAccessError(NotFound)"
        }
    }}, {'key': StackTrace, 'value':   File "/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/data_capability/data_sessions.py", line 331, in start
        options=mnt_options
    
      File "/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/azureml/dataprep/fuse/dprepfuse.py", line 696, in rslex_uri_volume_mount
        raise e
    
      File "/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/azureml/dataprep/fuse/dprepfuse.py", line 690, in rslex_uri_volume_mount
        mount_context = RslexDirectURIMountContext(mount_point, uri, options)
    }, ], 'inner_error': null}

Also, would u suggest to move to azure ml sdk v2 now or should we wait until it is stable.

**Comment by luigiw** [comment]
@rjtshrm Thx for your feedback. "run after" is a feature we've planned for and are actively working on. Before that feature is available in v2 SDK, what you did is the recommended workaround. Can you share your pipeline definition code?

**Comment by rjtshrm** [comment]
Here are my steps to run a pipeline
```
def step_1(environment="bp_environment:3.0", environment_variables={}):
    return command(
        name="data_prep",
        display_name="Data preparation for training",
        description="Preprocessing the training data",
        inputs={
            "output_dir": Input(type="string"),
        },
        outputs={
            "fake_op": Output(type="uri_folder")
        },
        # The source folder of the component
        code="/src/datapreprocessor",
        command="""python datapreprocessor.py \
                --output_dir ${{inputs.output_dir}} \
                """,
        environment=environment,
        environment_variables = environment_variables,
    )

def step_2(environment="bp_environment:3.0", environment_variables={}):
    return command(
        name="model_training",
        display_name="Model Training",
        description="Model training",
        inputs={
            "output_dir": Input(type="string"),
            "num_labels": Input(type="number"),
            "fake_ip": Input(type="uri_folder")
        },
        outputs={
            "fake_op": Output(type="uri_folder")
        },
        # The source folder of the component
        code="/src/trainer",
        command="""python primary_trainer.py \
                --output_dir ${{inputs.output_dir}} \
                --num_labels ${{inputs.num_labels}} \
                """,
        environment=environment,
        environment_variables = environment_variables
    )
```
and to run the pipeline, the code is 

```
def blueprint_pipeline():
        data_prep_job = data_prep_component(environment=environment, environment_variables=environment_variables)(
            output_dir="Data"
        )

        train_prep_job = train_prep_component(environment=environment, environment_variables=environment_variables)(
            output_dir="model/",
            num_labels=9,
            fake_ip=data_prep_job.outputs.fake_op
        )



    bp_pipeline = blueprint_pipeline()

    pipeline_job = ml_client.jobs.create_or_update(
        bp_pipeline,
        experiment_name="BP",
    )
```

**Comment by chamalHealthscope** [comment]
Having the exact same issue, looking forward for a patch release if applicable.

**Comment by wangchao1230** [comment]
We identify a bug in common runtime which cannot mount an empty folder, which we will follow-up internally.
Before that fix a quick workaround for user is writing some dummy file to the dummy output. 

E.g. add an echo in command.
```python
        command="""python datapreprocessor.py \
                --output_dir ${{inputs.output_dir}} \
                && echo ' ' > ${{outputs.fake_op}} \
                """,
```

**Comment by mastreips** [comment]
I have encountered the same problem when interacting directly with the datastore and dataset repositories to pull and store data rather than saving it to local. I had to create a dummy file to pass through each node to avoid this error. Please fix! Thanks.
