### ISSUE TITLE
Switch between Manual and Autoscale

### ISSUE THREAD

**Issue by sachindedhia** [Azure/azure-sdk-for-python#25021]
We have two scenario where we would like to switch between Manual and Autoscale mode. At the moment, we are performing manually using Azure portal but we would like to automate it.

We perform large bulk load of data every month but other time, there is limited read operation going on. To handle this, when we perform bulk load - we scale cosmos db to 120k manual and then once the load is complete, we scale back cosmos to 12k Autoscale.

**Describe the solution you'd like**
We would like to switch between autoscale and manual mode and able to change the RUS.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by l0lawrence** [comment]
Hi @sachindedhia thanks for the feedback. We will investigate asap.

**Comment by simorenoh** [comment]
Hi @sachindedhia, thank you for using our SDK and creating this issue. The work for the SDK to create and update autoscale throughput settings for containers and databases is currently being worked on by @JericHunter - we'll make sure to let you know once it is released publicly in the SDK for you to use.

**Comment by simorenoh** [comment]
Fixed with 4.3.1b1 release: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/CHANGELOG.md#431b1-2022-09-19
