### ISSUE TITLE
azure-mgmt-dns does not support the most recent API version

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#25025]
- **Package Name**: azure-mgmt-dns
- **Package Version**: 8.0.0
- **Operating System**: Linux
- **Python Version**: 3.8

**Describe the bug**
azure-mgmt-dns does not support API version 2018-09-01

**To Reproduce**
1. Install azure-mgmt-dns
2. Observe that the newest version is v2018_05_01 and there is no support for private DNS zones. That support is in v2018-09-01, per https://docs.microsoft.com/en-us/rest/api/dns/privatedns/private-zones/get

**Expected behavior**
SDK includes support for private DNS zones

**Screenshots**
n/a

**Additional context**
n/a

**Comment by msyyc** [comment]
Hi @jazelenk Please try `azure-mgmt-privatedns==1.0.0`

**Comment by jazelenk** [comment]
Yup, that's what I need - thanks!
