### ISSUE TITLE
Add Github Action that automates keeping readme samples up to date

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#25041]
I had a good discussion with @xiangyan99 about how we can improve our README samples. The core problem is simple that we  need our samples and README.md's to align. Our code and docs themselves are fine, as we simply use [literalinclude](https://github.com/Azure/azure-sdk-for-python/blob/1081acd696bb5d2eb563d2071060d8f86e823603/sdk/core/azure-core/azure/core/_pipeline_client.py#L83) to include directly out of the sample file. The issue is the _readme_ specifically. This is because there is no automation that keeps the code samples within aligned, and nothing preventing us from forgetting to update them.

We can't simply leave the code samples _blank_ and inject them with a little bit of custom processing code in our `setup.py`.  Sure, we could definitely have the setup.py do some lifting to inject sample code into the README before passing that to the `long_description` field. That would ensure that our readme on PyPI and in our docs is g2g. The cost of that is the readme at rest in github will not have any code visible. Just the little html comments indicating where it _should_ be.

That means we need to run a script somewhere to update the readme from the sample python.

One solution we can do here is to embed html comments in our READMEs that identify A) a sample source and B) the sample id within it. After that, we can add some processing.

That would look something like this:

```md
<!-- "samples/test_example_async.py" "START build_async_pipeline_client" "END build_async_pipeline_client" "DEDENT 4" -->
```python
from azure.core.pipeline.policies import AsyncRedirectPolicy, UserAgentPolicy
from azure.core.pipeline.transport import HttpRequest

# example policies
request = HttpRequest("GET", url)
policies = [
    UserAgentPolicy("myuseragent"),
    AsyncRedirectPolicy(),
]

async with AsyncPipelineClient(base_url=url, policies=policies) as client:
  response = await client._pipeline.run(request)

<!-- end sample -->
```
Everything between the two sample html comments should be replaced with the target sample file content. With that, we can roll an action that runs with commits to `main`, and simply submits the sample updates as a pull request.

This issue covers:

- [ ] Write the script which updates the README.md given proper configuration
- [ ] Write the action which runs the script and submits a PR
- [ ] Integrate the new action / script
- [ ] Document local usage of the readme update script

**Comment by xiangyan99** [comment]
I will take care of it.

**Comment by xiangyan99** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/28889
