### ISSUE TITLE
[AzureML] Drop Python 3.6 support

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#25059]
We are formally dropping support for the Python 3.6 in the Azure SDKs - so we should make sure that this is completed before GA. It should just be an update to setup.py - however I'm aware that this SDK has a more complex CLI validation pipeline that may include additional updates, so opening a dedicated issue for it.

**Comment by luigiw** [comment]
@annatisch this is done for v2 SDK. Can we close this now?

**Comment by annatisch** [comment]
Yup!
