### ISSUE TITLE
[AzureML] Drop public dependency on msrest

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#25060]
Msrest is a deprecated dependency and should be removed from all public facing API surface area before GA.
The biggest example of this will be models - no public models should inherit from the msrest baseclass.

The GA release wont be blocked if msrest is still a dependency for internal logic that can be later removed without any changes to the public API/behaviour.

**Comment by annatisch** [comment]
Given there's such a limited scope (<25) of public models that appear to expose msrest.serialization.Model - I would recommend just updating the handwritten layer to exclude this base class. This should be a relatively simple fix.

Tagging @azureml-github for broader visibility.

**Comment by needuv** [comment]
This has now been addressed. Closing this issue.
