### ISSUE TITLE
[AzureML] Latest autorest regen (with minimal - if any - multiapi)

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#25061]
The generated core of the ML SDK should be regenerated with latest GA DPG release of autorest.
We should regenerate using the options to combine operations into a single file to reduce load times.
All code gen for "preview" API versions should be removed - and we should investigate removing all older API versions so that the GA release is as forward facing as possible.

The latest autorest will also generate the `send_request` generic operation API - we should make sure this is surfaced to the MLClient.

This issue is closely tied to #25060 - dropping msrest.

**Comment by singankit** [comment]
This will be handled as a part of internal refactoring. Since it is not public facing should be a non-breaking change. Will mark this as a non-blocking issue for GA.
