### ISSUE TITLE
Invoke relay_client.hybrid_connections.create_or_update_authorization_rule with same parameters changed the relay connection string.

### ISSUE THREAD

**Issue by yuyue9284** [Azure/azure-sdk-for-python#25092]
- **Package Name**:  azure-mgmt-relay
- **Package Version**: 0.1.0
- **Operating System**: linux
- **Python Version**: Python 3.10.4

**Describe the bug**
We use the following script to manage relay, and with the same parameter, we sometimes found that the relay connection string go changed.

```
          # create authorization rule
          auth_rule_rights = [azure.mgmt.relay.models.AccessRights.manage,
                              azure.mgmt.relay.models.AccessRights.send, azure.mgmt.relay.models.AccessRights.listen]
          relay_client.hybrid_connections.create_or_update_authorization_rule(
              resource_group_name, relay_namespace_name, hybrid_connection_name, auth_rule_name, rights=auth_rule_rights)
```

**To Reproduce**
We are not able to reproduce it but noticed few incidents caused by this in production.

**Expected behavior**

With the same parameter and an already existed relay, the connection string should never be changed.

**Screenshots**

**Additional context**

**Comment by yuyue9284** [comment]
> Hi @yuyue9284, thank you for your feedback.
> 
> Please provide your detailed code to better solve your problem.

Hi @Wzb123456789, this is how we used it in our application.
```python
        # create namespace
        relay_namespace_params = azure.mgmt.relay.models.RelayNamespace(
            location=cluster_location, tags=resource_tag)
        async_poller = relay_client.namespaces.create_or_update(
            resource_group_name, relay_namespace_name, relay_namespace_params)
        while True:
            async_poller.result(15)
            if async_poller.done():
                break
        # create hybrid connection
        hybrid_connection_object = relay_client.hybrid_connections.create_or_update(
            resource_group_name, relay_namespace_name, hybrid_connection_name, requires_client_authorization=True)
        hc_resource_id = hybrid_connection_object.id
        # create authorization rule
        auth_rule_rights = [azure.mgmt.relay.models.AccessRights.manage,
                            azure.mgmt.relay.models.AccessRights.send, azure.mgmt.relay.models.AccessRights.listen]
        relay_client.hybrid_connections.create_or_update_authorization_rule(
            resource_group_name, relay_namespace_name, hybrid_connection_name, auth_rule_name, rights=auth_rule_rights)
```

**Comment by Wzb123456789** [comment]
Hi @yuyue9284, thank you for your feedback.

According to my investigation, the cause of this problem may be due to the `azure-mgmt-relay` version you are using is 0.1.0, `azure-mgmt-relay` has been updated to 1.1.0, please try to use the latest version.
https://pypi.org/project/azure-mgmt-relay/#history
