### ISSUE TITLE
Inconsistent behaviour in Cosmos Query Item because of use of kwargs

### ISSUE THREAD

**Issue by eavanvalkenburg** [Azure/azure-sdk-for-python#25104]
I found an issue while working with the cosmos SDK in python, when calling query_items (and it seems other calls as well) with partition_key=None or without the partition_key at all leads to different behaviours because of the build_options function that is referenced here:
https://github.com/Azure/azure-sdk-for-python/blob/663c846e4d24166f0e76092a80989cfd08521bf2/sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py#L349
This function pops a whole lot of known arguments (partition_key among others) even when the value is None, which then leads the rest of the code that is handling kwargs to have nothing left to work with, so either that logic is redundant or a check if the value is None should be added to the build_options function.

Let me know if you need more info.

Code snippets:
This code works (as in when supplying an existing ID it returns the item) when `address` is not `None`, but does not work when `address` is `None`, because of the issue above.
```python
[
    item
    async for item in self.container.query_items(
        query="SELECT * FROM c WHERE c.id = @id OR c.address = @address",
        parameters=[
            {"name": "@id", "value": item_id},
            {"name": "@address", "value": address},
        ],
        partition_key=address,
        populate_query_metrics=True,
    )
]
```
This doesn't works:
```python
[
    item
    async for item in self.container.query_items(
        query="SELECT * FROM c WHERE c.id = @id OR c.address = @address",
        parameters=[
            {"name": "@id", "value": item_id},
            {"name": "@address", "value": address},
        ],
        partition_key=None,
        populate_query_metrics=True,
    )
]
```
This does work:
```python
[
    item
    async for item in self.container.query_items(
        query="SELECT * FROM c WHERE c.id = @id OR c.address = @address",
        parameters=[
            {"name": "@id", "value": item_id},
            {"name": "@address", "value": address},
        ],
        populate_query_metrics=True,
    )
]
```

**Comment by annatisch** [comment]
This is a great catch - thanks for the report @eavanvalkenburg!
@simorenoh, @JericHunter - would you be able to take a look?

**Comment by eavanvalkenburg** [comment]
Just noticed it is even worse, when passing a partition_key because the _build_options pops that out of kwargs it then runs logic to look for a partition_key and when it doesn't find one sets the feed_options['enableCrossPartitionQuery'] to True, so it does a cross partition query with a partition_key, potentially incurring higher RU's!

**Comment by eavanvalkenburg** [comment]
it will probably make most sense if the signature for query_items for both async and sync are the same and that would also solve this issue (with minor tweaks in the async code)

**Comment by simorenoh** [comment]
@eavanvalkenburg this is great, thanks for all the findings and the time spent looking into it! I'll take a look when I get a moment to do so, just wanted to let you know we're aware of the issue and pushed PR 👍

**Comment by Plouc314** [comment]
@simorenoh  Any update on this ?
It also prevents the use of the continuation token, as `enableCrossPartitionQuery` is always set to true:
```python
query = container.query_items(
    query="SELECT * FROM c",
    partition_key=my_partition_key,
    enable_cross_partition_query=False,
    max_item_count=20,
)

pager = query.by_page(continuation_token=continuation_token)
page = await anext(pager)

items = []
async for item in page:
    items.append(item)
```
The above raises `ValueError: continuation tokens are not supported for cross-partition queries.`

**Comment by simorenoh** [comment]
Hi @Plouc314, sorry for the delay. From the time I last updated this issue a lot has changed, and I am no longer working in the Python SDK - I have assigned Jeric who is the new main developer to take over when he gets the bandwidth. Thank you for your patience!
