### ISSUE TITLE
Include Timestamp property in Resulting Entity of Azure Table Storage Query

### ISSUE THREAD

**Issue by oliverblane** [Azure/azure-sdk-for-python#25106]
It seems that [here](https://github.com/Azure/azure-sdk-for-python/blob/db129d0020160815d2a5cd52be5b6777a6cbefaf/sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py#L133) the code is setting the `PartitionKey` (line 168) and `RowKey` (line 173) properties, but not the `Timestamp` property.

When querying an Azure Data Table using Python, I think it would be very useful for the resulting entity to include the Timestamp that is in the Azure Data Table.

Many thanks.

**Comment by mccoyp** [comment]
Hi @oliverblane, thank you for opening an issue! It looks like the timestamp is included in the entity metadata [here](https://github.com/Azure/azure-sdk-for-python/blob/db129d0020160815d2a5cd52be5b6777a6cbefaf/sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py#L216) -- does that make the information sufficiently available?

I'll tag someone who works with this library so you can get a more informed response as soon as possible.

**Comment by oliverblane** [comment]
> Hi @oliverblane, thank you for opening an issue! It looks like the timestamp is included in the entity metadata [here](https://github.com/Azure/azure-sdk-for-python/blob/db129d0020160815d2a5cd52be5b6777a6cbefaf/sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py#L216) -- does that make the information sufficiently available?
> 
> I'll tag someone who works with this library so you can get a more informed response as soon as possible.

Thank you for your reply - yes, you are right, I overlooked the metadata. That solves my issue, thank you very much!
