### ISSUE TITLE
azureml-core cannot be installed in custom image for AML

### ISSUE THREAD

**Issue by thongonary** [Azure/azure-sdk-for-python#25124]
- **Package Name**: azureml-core, azureml-pipeline, azureml-pipeline-steps, azureml-pipeline-core
- **Package Version**: latest
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.13

**Describe the bug**
I tried to build a custom image on Azure Machine Learning, with a base image from `mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.3-cudnn8-ubuntu20.04` and additional conda specifications:
```
name: project_environment
dependencies:
  - python=3.8.13
  - pip:
      - azureml==0.2.7
      - azureml-dataprep==4.0.4
      - datasets==2.3.2
      - packaging==21.3
      - pandas==1.4.2
      - psutil==5.9.1
      - pytorch_lightning==1.6.4
      - PyYAML==6.0
      - setuptools==61.2.0
      - torch==1.11.0
      - transformers==4.11.3
  - pip
channels:
  - anaconda
  - conda-forge
```
The build succeeded. However, when I tried to add the following packages to the pip list:
```
      - azureml-core==1.43.0
      - azureml-pipeline==1.43.0
      - azureml-pipeline-steps==1.43.0
      - azureml-pipeline-core==1.43.0
```
The build status is stuck at "Running" for 1.5 hours and then timed out. The build log shows it was stuck at the installing pip dependencies step:
```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... 
Run ID: cxp timed out after 1h30m0s
```

**To Reproduce**
1. Prepare the following `conda-dependencies.yaml`:
```
name: project_environment
dependencies:
  - python=3.8.13
  - pip:
      - azureml==0.2.7
      - azureml-core==1.43.0
      - azureml-pipeline==1.43.0
      - azureml-pipeline-steps==1.43.0
      - azureml-pipeline-core==1.43.0
      - datasets==2.3.2
      - packaging==21.3
      - pandas==1.4.2
      - psutil==5.9.1
      - pytorch_lightning==1.6.4
      - PyYAML==6.0
      - setuptools==61.2.0
      - torch==1.11.0
      - transformers==4.11.3
  - pip
channels:
  - anaconda
  - conda-forge
```
2. Set up a custom AML image:
```
    env = Environment.from_conda_specification(
            name=env_name,
            file_path="conda-dependencies.yaml")
    env.docker.base_image = 'mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.3-cudnn8-ubuntu20.04'
    env.register(ws)
```

**Expected behavior**
If the pip packages not found because of some reasons, the build should fail with an error message instead of hanging.
I do not see any reason why `azureml-core` et al. should cause problems though. They are public PyPi packages.

**Screenshots**
<img width="840" alt="image" src="https://user-images.githubusercontent.com/10479549/177727324-3ec8b203-74c3-4b17-b835-913fc3760753.png">

<img width="263" alt="image" src="https://user-images.githubusercontent.com/10479549/177727132-670fd4f0-537e-4956-a689-a3498146e214.png">

**Comment by thongonary** [comment]
I think this is a problem with `azureml-cpre` package requirements in conda. Running the conda spec file locally also results in the same issue @azureml-github.

**Comment by mattmshell** [comment]
I experience pip install hangs installing packages via a conda file on top of an custom image. This bug appears to be the cause of it. I note that it's impossible to get a custom image + conda file in the same state as a default image + conda file.

Nothing works the second I take dependency on azureml-defaults because of the azureml-core interaction. It gets worse - a casual reference to azure-storage-blob and it all breaks things again.

I feel like none of the AzureML SDK is usable in the slightest. Personally it's the worst experience I've ever had developing software.

**Comment by thongonary** [comment]
I found the issue @bandsina @azureml-github

These `azureml` packages contain `azureml-dataset-runtime`, which requires `pyarrow<4.0.0,>=0.17.0`
However, the latest version of `pyarrow` is 8.0.0, and other popular packages such as `datasets` from HuggingFace requires `pyarrow > 6.0.0`. These conflicting requirements prevent conda from installation.

Certainly this is something the AzureML team should fix -- requiring an obsolete version of a popular package is just wrong.

**Comment by harneetvirk** [comment]
We have requested the feature team to upgrade the dependencies of pyarrow>6.0.0 in azureml-dataset-runtime package.

**Comment by thongonary** [comment]
Hello @harneetvirk -- it has been over 3 months. Is there any update from the feature team regarding this issue? Thanks!

**Comment by luigiw** [comment]
#24644
