### ISSUE TITLE
[BUG Bash]

### ISSUE THREAD

**Issue by ashdhalama** [Azure/azure-sdk-for-python#25132]
**Describe the bug**
Setup app configuration to reference a key value.  When check value only gives uri and not the value.

Used "add key vault reference" in app configuration explorer.

***Exception or Stack Trace***
None

**To Reproduce**
Run code snippet

***Code Snippet***
def testAppConfigKeyVaultPassThru():
    pass
    credential = DefaultAzureCredential()
    app_config_client = AzureAppConfigurationClient(base_url="https://xxxx.azconfig.io", credential=credential)

    retrieved_config_setting = app_config_client.get_configuration_setting(key='kvTestAditya')
    print("\nRetrieved configuration setting:")
    print("Key: " + retrieved_config_setting.key + ", Value: " + retrieved_config_setting.value)

Output

Retrieved configuration setting:
Key: kvTestAditya, Value: {"uri": "https://adw-dashads-dev.vault.azure.net/secrets/TestSecret"}
(dashads) PS C:\Users\dhalama\source\repos\DashADS> 

**Expected behavior**
Return value of the key

**Screenshots**

![image](https://user-images.githubusercontent.com/101288153/177871359-d2cefec9-9605-46e5-8523-4ddc1042d030.png)

**Setup (please complete the following information):**
 - Python Version: 3.8.10
 - SDK Version: 
 - ---------------------- ---------
azure-appconfiguration 1.3.0
azure-common           1.1.28
azure-core             1.24.2
azure-identity         1.10.0
azure-keyvault-secrets 4.4.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by mccoyp** [comment]
Hi @ashdhalama, thank you for opening an issue! I'll tag the appropriate folks so we can investigate as soon as possible.

**Comment by xiangyan99** [comment]
@ashdhalama Thanks for reaching out.

This is by design that the app config client library only returns the url of the keyvault rather than the value.

You can take https://gist.github.com/xiangyan99/cb15bb686e56bac020f93d71f524208f as a reference how to retrieve the value by using key vault library and app config library together.
