### ISSUE TITLE
[ServiceBus] Drop support for Python 3.6

### ISSUE THREAD

**Issue by kashifkhan** [Azure/azure-sdk-for-python#25148]

**Comment by JJHWAN** [comment]
@kashifkhan 
I'm Interested in this issue. Can i dig into it?

**Comment by swathipil** [comment]
Hi @JJHWAN - Thank you for your interest!
This PR for dropping Python 3.5 from Service Bus should be very similar to what you'll be doing (except with 3.6): https://github.com/Azure/azure-sdk-for-python/pull/17751/files. Feel free to open a PR!

In case this is not something you're interested in, feel free to look through/contribute to any issues that are tagged `help-wanted` in our repo. 🙂 https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
