### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by James-Beckwith** [Azure/azure-sdk-for-python#25143]
The final "Explore the Management APIs" link and the Management API title link are broken in the page https://docs.microsoft.com/en-us/python/api/overview/azure/sql?view=azure-python. They link to https://docs.microsoft.com/en-us/python/api/overview/azure/sql/management which returns a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70987972-7937-8be0-23f7-f2fda125d4f9
* Version Independent ID: 3a2a0bd0-7f5b-7393-da34-c669f9e9aa5a
* Content: [Azure SQL Database libraries for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/sql?view=azure-python)
* Content Source: [docs-ref-services/latest/sql.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/sql.md)
* Service: **sql-database**
* GitHub Login: @lisawong19
* Microsoft Alias: **ramyar**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
Fixed.

**Comment by James-Beckwith** [comment]
Thanks
