### ISSUE TITLE
[Test Proxy] Investigate SSL socket warnings

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#25154]
Some `azure-storage-blob` tests that have been migrated to the test proxy raise `ResourceWarning`s about unclosed sockets when run in either live or playback mode. This doesn't happen 100% of the time, but most of the time.

```
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=936, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM,
proto=0, laddr=('::1', 63638, 0, 0), raddr=('::1', 5001, 0, 0)>
```

The Storage team reports that this happens when running, for example, `test_create_blob` from [`test_append_blob.py`](https://github.com/Azure/azure-sdk-for-python/pull/25151/files#diff-95e8a63c6c0754167e1a83a3201743e75b48620fc945fdb4a54b1394d0de3971) (this migration is still in PR at https://github.com/Azure/azure-sdk-for-python/pull/25151 at the time of writing). The test was run with Python 3.10.5, with Docker on Windows using WSL 2.

**Comment by scbedd** [comment]
I will note that I've seen this before without the test-proxy being involved. but still need to investigate. 👍

**Comment by mccoyp** [comment]
It's been almost two years and I haven't heard of this issue coming back up. Closing; we can create a new tracking issue if this reappears.
