### ISSUE TITLE
'kafka_enabled' parameter is ignored for Eventhub Namespaces

### ISSUE THREAD

**Issue by philipp-sontag-by** [Azure/azure-sdk-for-python#25162]
- **Package Name**: azure-mgmt-eventhub==10.1.0
- **Package Version**: 10.1.0
- **Operating System**: Debian bullseye
- **Python Version**: 3.10

**Describe the bug**
Trying to create an Eventhub Namespace with `kafka_enabled=False` creates an Eventhub Namspace where kafka is enabled.

**To Reproduce**
```python
from azure.mgmt.eventhub import EventHubManagementClient
from azure.mgmt.eventhub.models import EHNamespace, Sku
from azure.identity import DefaultAzureCredential

params = EHNamespace(location="<location>", sku=Sku(name="Standard"), kafka_enabled=False)

with EventHubManagementClient(credential=DefaultAzureCredential(), subscription_id="<subscription-id") as client:
      r = client.namespaces.begin_create_or_update("my-resource-group", "my-eventhub-ns", params)
      r.result()
```

**Expected behavior**
Trying to create an Eventhub Namespace with `kafka_enabled=False` creates an Eventhub Namspace where kafka is disabled.

**Additional context**
I als tried the `v2022_01_01_preview` API version but it did not word either.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Wzb123456789** [comment]
Hi @philipp-sontag-by 

According to my investigation, this issue is a service problem. 

Because the SDK is generated by swagger, the SDK is responsible for processing the quantity returned by the service and displaying it.

I suggest you go to the [rest](https://github.com/Azure/azure-rest-api-specs/issues) and resubmit your issue

**Comment by philipp-sontag-by** [comment]
Sure thanks for the help
