### ISSUE TITLE
[azure-ai-language-questionanswering] Import of QuestionAnsweringProjectsClient is broken

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#25185]
Hey @kristapratico I had @bassamza reach out over teams with an issue she was encountering with the package. I've unblocked them by having them install the current version from repo, but we should probably fix the `1.0.0` release.

repro steps

`pip install azure-ai-language-questionanswering`
`from azure.ai.language.questionanswering.projects import QuestionAnsweringProjectsClient`

`from azure.ai.language.questionanswering.projects import *` doesn't surface the error unfortunately. That's what our CI invokes.

**Comment by kristapratico** [comment]
`QuestionAnsweringProjectsClient` wasn't added to the package until 1.1.0b1. It is not supported in the 1.0.0 package, so you'll need to upgrade to the beta package by running `pip install azure-ai-language-questionanswering --pre --upgrade`.

**Comment by scbedd** [comment]
Aha I'm just an idiot! Thanks Krista
