### ISSUE TITLE
Cosmos DB SDK raises error when upserting items with np.nan values

### ISSUE THREAD

**Issue by msamsami** [Azure/azure-sdk-for-python#25183]
- **Package Name**: azure-cosmos
- **Package Version**: latest
- **Operating System**: Linux
- **Python Version**: 3.8.12

**Describe the bug**
Upsert mechanism can't handle `np.nan` values. It raises the following error:
```
(BadRequest) Message: {"Errors":["The request payload is invalid. Ensure to provide a valid request payload."]} ActivityId: ...
```

**To Reproduce**

Here is a sample code to reproduce the issue:

```python
import numpy as np
from azure.cosmos import CosmosClient

cosmos_client = CosmosClient(COSMOS_DB_URL, credential=COSMOS_DB_KEY)
database = cosmos_client.get_database_client(COSMOS_DB_NAME)
container = database.get_container_client(DB_CONTAINER)

sample_item = {'id': '0', 'key1': np.nan}
container.upsert_item(sample_item)
```

**Expected behavior**
I expected that SDK could handle both `None` and `np.nan` as they are the most frequent types of NULL.

**Comment by SaurabhSharma-MSFT** [comment]
@msamsami We are looking into it and get back to you for any additional information.

**Comment by simorenoh** [comment]
@msamsami the Cosmos SDK is not a Python only library or service, but rather a bridge between the database service we offer and the code our users create. We can only handle data types that are present in other languages as well - and we do handle None types native to each language. Hope this makes sense.
