### ISSUE TITLE
Mistake in the documentation (TROUBLESHOOTING.md)

### ISSUE THREAD

**Issue by MiquelMartiGyrusDS** [Azure/azure-sdk-for-python#25196]
- **Package Name**: azure-sdk-for-python
- **Package Version**: Updated 8th July 2022
- **Operating System**:NA
- **Python Version**: NA

**Describe the bug**
The documentation on troubleshooting might be misleading.

**To Reproduce**
1. Go to https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-environmentcredential-authentication-issues
2. Third option on https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-environmentcredential-authentication-issues:~:text=Description-,Mitigation,-Environment%20variables%20aren%27t
3. The issue is about this point https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-environmentcredential-authentication-issues:~:text=To%20authenticate%20a%20user%20using%20a%20password%2C%20ensure%20the%20variables%20AZURE_USERNAME%20and%20AZURE_PASSWORD%20are%20properly%20set.

**Expected behavior**
I believe the expected behavior would be to display this text:
"To authenticate a service principal using a certificate, ensure the variables `AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, `AZURE_USERNAME` and `AZURE_PASSWORD` are properly set."
but what is displayed is:
"To authenticate a user using a password, ensure the variables `AZURE_USERNAME` and `AZURE_PASSWORD` are properly set."

**Screenshots**
![image](https://user-images.githubusercontent.com/109222815/178740315-d54b9019-334f-4a9b-8107-f96c1eefad96.png)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
Hi, it is correct that AZURE_CLIENT_ID, AZURE_TENANT_ID and AZURE_CLIENT_CERTIFICATE_PATH are needed for authenticating a service principal using a certificate and AZURE_USERNAME and AZURE_PASSWORD for authenticating a user using a password

**Comment by MiquelMartiGyrusDS** [comment]
Thank you @xiangyan99 for your effort and clarification.
