### ISSUE TITLE
Error while creating an Azure virtual machine 

### ISSUE THREAD

**Issue by youssefbenfarhat** [Azure/azure-sdk-for-python#25217]
I'm trying to create an Azure VM with Ansible and I'm getting this error.

TASK [VM CREATION] ******************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.network'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on vmi576440.contaboserver.net's Python /home/yf/miniconda3/envs/grafenv/bin/python3.9. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you give more details about how you setup the environment?
