### ISSUE TITLE
Insufficient privileges to complete the operation while trying to get AD groups 

### ISSUE THREAD

**Issue by Racheli-Bloch** [Azure/azure-sdk-for-python#25216]
Hi, I am trying to write a very simple script to list Azure AD groups. 

- **Package Name**: azure-common
- **Package Version**: 1.1.28
> 
- **Package Name**: azure-graphrbac
- **Package Version**: 0.61.1
> 
- **Python Version**: 3.10

Here is the script:

 ```
   from azure.common.credentials import ServicePrincipalCredentials
   from azure.graphrbac import GraphRbacManagementClient

    credentials = ServicePrincipalCredentials(
        client_id=client_id,
        secret=client_secret,
        resource="https://graph.windows.net",
        tenant=tenant_id
    )

    graphrbac_client = GraphRbacManagementClient(
        credentials,
        tenant_id
    )

    groups = graphrbac_client.groups.list()

    for g in groups:
        print(g.display_name)
```

The intention is to run it from "Azure automation" authenticating using a service-principle (not a user).
The app registration I created on azure for authentication has `Directory.Read.All` and `Group.Read.All` permissions:

![Screen Shot 2022-07-14 at 12 24 57 PM](https://user-images.githubusercontent.com/98835080/178950091-08e34de4-1c2d-4daa-8747-216ff1f81f40.jpg)

But I still get: 
`azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation.`

What am I missing?

I see the same issue without solution: #16018

**Comment by SaurabhSharma-MSFT** [comment]
@Racheli-Bloch We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@Racheli-Bloch We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
