### ISSUE TITLE
Cannot import UniqueKey or UniqueKeyPolicy class

### ISSUE THREAD

**Issue by Iamsoto** [Azure/azure-sdk-for-python#25227]
When I try to pip install azure.mgmt It gives me the following message: 
```
Collecting azure.mgmt
  Using cached azure-mgmt-5.0.0.zip (4.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-oubkqzgq/azure-mgmt_3bea0349801b4b90a4ac6dbf63b13c04/setup.py", line 58, in <module>
          raise RuntimeError(message)
      RuntimeError:
      
      Starting with v5.0.0, the 'azure-mgmt' meta-package is deprecated and cannot be installed anymore.
      Please install the service specific packages prefixed by `azure` needed for your application.
      
      The complete list of available packages can be found at:
      https://aka.ms/azsdk/python/all
      
      Here's a non-exhaustive list of common packages:
      
      -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
      -  azure-mgmt-network (https://pypi.python.org/pypi/azure-mgmt-network) : Management of Network interfaces, Public IP, etc.
      -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
      -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
      
      A more comprehensive discussion of the rationale for this decision can be found in the following issue:
      https://github.com/Azure/azure-sdk-for-python/issues/10646
```

So I'm not certain where to import these classes from...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49e511b3-c136-8dd7-61f3-7f40c656e2dd
* Version Independent ID: a6e54607-0c84-3127-0ca8-7b4ef0c7b1b2
* Content: [azure.mgmt.cosmosdb.models.UniqueKeyPolicy class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.models.uniquekeypolicy?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.models.UniqueKeyPolicy.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.models.UniqueKeyPolicy.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

As you can see in the error message, azure-mgmt package is deprecated.

It seems to me you are looking for azure.mgmt.cosmosdb.models.UniqueKeyPolicy class which you need azure-mgmt-cosmosdb package.

Please let us know if it does not work.
