### ISSUE TITLE
azure.mgmt.securityinsight.watchlists.create_or_update() doesn't create the watchlist items 

### ISSUE THREAD

**Issue by wanpeng-cds** [Azure/azure-sdk-for-python#25242]
- **Package Name**: 
azure.mgmt.securityinsight
- **Package Version**: 
 Latest
- **Operating System**:
Linux
- **Python Version**: 
3.9.12
**Describe the bug**
This package is using the REST API version: 2022-07-01-preview.  When I use `azure.mgmt.securityinsight.watchlists.create_or_update()`, it will create the watchlist, return with 200 response, but it ignores the watchlist items set in `raw_content`. 

I tried to set the api version to the stable version `2021-10-01` with `instance_name.watchlists.api_version = "2021-10-01"` but it doesn't work.

**To Reproduce**
This is a REST API bug, you can reproduce it by issuing the HTTP api request
1.
```
PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/watchlists/{watchlistAlias}?api-version=2022-07-01-preview

{
  "etag": "\"0300bf09-0000-0000-0000-5c37296e0000\"",
  "properties": {
    "displayName": "High Value Assets Watchlist",
    "source": "Local file",
    "provider": "Microsoft",
    "description": "Watchlist from CSV content",
    "numberOfLinesToSkip": 1,
    "rawContent": "This line will be skipped\nheader1,header2\nvalue1,value2",
    "itemsSearchKey": "header1",
    "contentType": "text/csv"
  }
}
```

This will create the watchlist but the items in the rawContent will be ignored. 
 
2.  Change the `api-version` to `2021-10-01`
```
PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/watchlists/{watchlistAlias}?api-version=2021-10-01

{
  "etag": "\"0300bf09-0000-0000-0000-5c37296e0000\"",
  "properties": {
    "displayName": "High Value Assets Watchlist",
    "source": "Local file",
    "provider": "Microsoft",
    "description": "Watchlist from CSV content",
    "numberOfLinesToSkip": 1,
    "rawContent": "This line will be skipped\nheader1,header2\nvalue1,value2",
    "itemsSearchKey": "header1",
    "contentType": "text/csv"
  }
}
```
This will create the watchlist and bulk create the watchlist items 

**Expected behavior**
- when using the method `azure.mgmt.securityinsight.watchlists.create_or_update()` with a watchlist that contains the watchlist items data in `raw_content`, it should create/update the watchlist with the watchlist items.  
- when manually set the api version with `instance_name.watchlists.api_version = "2021-10-01"`,  it should use the set api version instead of the default version, which is currently set to `2022-07-01-preview`

**Comment by SaurabhSharma-MSFT** [comment]
@wanpeng-cds We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@wanpeng-cds I have tried using the REST as you mentioned above and able to create and update an existing watchlist with watchlist items getting passed as raw content.  A new watchlist item is getting added if not available.
![image](https://user-images.githubusercontent.com/38112130/179865870-e55d99ba-3c6b-44e5-b6b6-cc44eacf8b71.png)
Result on Azure portal:
![image](https://user-images.githubusercontent.com/38112130/179865973-9310d0cb-3257-4ba9-93b0-7c00f2bc4b7e.png)

I have checked this with both api versions, and it worked fine.
Can you please share your python code so that I can check it in my environment?

**Comment by wanpeng-cds** [comment]
I've tested the REST API in a different tenant and got the same result:  api version `2021-10-01` works, `2022-07-01-preview` only creates/updates the watchlist itself but no watchlist items.  

I authenticated with a service principle.

**Comment by SaurabhSharma-MSFT** [comment]
@wanpeng-cds thanks for sharing details.  I will check this in my environment.

**Comment by Wzb123456789** [comment]
Hi @wanpeng-cds 

We will release a new package about `azure.mgmt.securityinsight` 2021-10-01

**Comment by Wzb123456789** [comment]
Hi @wanpeng-cds 

The 2021-10-01 package about `azure.mgmt.securityinsight` has been released and you can use it normally.
https://pypi.org/project/azure-mgmt-securityinsight/1.0.0/

**Comment by SaurabhSharma-MSFT** [comment]
Hi @wanpeng-cds,
Please let us know if you have any questions else, we will proceed with closing this issue.

Thanks
Saurabh

**Comment by wanpeng-cds** [comment]
Hi @SaurabhSharma-MSFT and @Wzb123456789, thank you so much for the hard work. I can confirm that the new version works!
