### ISSUE TITLE
Get the cost of each resource under a subscription daily

### ISSUE THREAD

**Issue by tbatra18** [Azure/azure-sdk-for-python#25259]
I am looking for an api to get the cost of each resource under a subscription on daily basis or given time diff.
For an example, suppose i have 2 virual machines say A and B, the rest api should say the cost for virtual machine A is x$ and B is y$ and good to be if we can give additional info like tags to each machine in the output

**Comment by xiangyan99** [comment]
@msyyc do you know ideas?

**Comment by msyyc** [comment]
Hi @tbatra18 Maybe this [doc](https://docs.microsoft.com/en-us/azure/cost-management-billing/cost-management-billing-overview) could help you

**Comment by tbatra18** [comment]
@msyyc Can you point me to the rest api to get the cost for each resource everyday.
I am not able to get the exact api, 
I found this https://docs.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP but was not helpful.

**Comment by msyyc** [comment]
Hi @tbatra18 I afraid I don't know the exact rest api either since I don't have much domain knowledge about this service. I advise you open issue in https://github.com/Azure/azure-rest-api-specs to seek help from service team directly.
