### ISSUE TITLE
[BUG Bash] pip install azure-eventhub broken

### ISSUE THREAD

**Issue by anupshrestha** [Azure/azure-sdk-for-python#25266]
**Describe the bug**
The `pip` installation of `azure-eventhub` is broken

***Exception or Stack Trace***

    Building wheels for collected packages: uamqp
    Building wheel for uamqp (setup.py) ... error
    error: subprocess-exited-with-error
    
    × python setup.py bdist_wheel did not run successfully.
    │ exit code: 1
    ╰─> [80 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-3.10
        creating build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/constants.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/compat.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/types.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/receiver.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/address.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/session.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/sender.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/connection.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/message.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/__init__.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/client.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/mgmt_operation.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/errors.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/utils.py -> build/lib.linux-x86_64-3.10/uamqp
        creating build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/connection_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/sender_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/mgmt_operation_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/session_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/client_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/__init__.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/receiver_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/utils.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        creating build/lib.linux-x86_64-3.10/uamqp/authentication
        copying uamqp/authentication/cbs_auth.py -> build/lib.linux-x86_64-3.10/uamqp/authentication
        copying uamqp/authentication/common.py -> build/lib.linux-x86_64-3.10/uamqp/authentication
        copying uamqp/authentication/cbs_auth_async.py -> build/lib.linux-x86_64-3.10/uamqp/authentication
        copying uamqp/authentication/__init__.py -> build/lib.linux-x86_64-3.10/uamqp/authentication
        running egg_info
        writing uamqp.egg-info/PKG-INFO
        writing dependency_links to uamqp.egg-info/dependency_links.txt
        writing requirements to uamqp.egg-info/requires.txt
        writing top-level names to uamqp.egg-info/top_level.txt
        reading manifest file 'uamqp.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        writing manifest file 'uamqp.egg-info/SOURCES.txt'
        copying uamqp/c_uamqp.c -> build/lib.linux-x86_64-3.10/uamqp
        running build_ext
        will build uamqp in build/temp.linux-x86_64-3.10/cmake
        Building with generator flags: -G "Unix Makefiles"
        calling cmake /tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release
        /bin/sh: cmake: not found
        Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/setup.py", line 260, in <module>
            setup(
            File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
            File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
            dist.run_commands()
            File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
            self.run_command(cmd)
            File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
            File "/usr/local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
            self.run_command('build')
            File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
            File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
            File "/usr/local/lib/python3.10/distutils/command/build.py", line 135, in run
            self.run_command(cmd_name)
            File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
            File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
            File "/tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/setup.py", line 134, in run
            self.build_cmake(ext)
            File "/tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/setup.py", line 183, in build_cmake
            subprocess.check_call(joined_cmd, shell=True, universal_newlines=True, env=build_env)
            File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command 'cmake /tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release' returned non-zero exit status 127.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for uamqp
    Running setup.py clean for uamqp
    Failed to build uamqp
    Installing collected packages: uamqp, azure-eventhub
    Running setup.py install for uamqp ... error
    error: subprocess-exited-with-error
    
    × Running setup.py install for uamqp did not run successfully.
    │ exit code: 1
    ╰─> [82 lines of output]
        running install
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-3.10
        creating build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/constants.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/compat.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/types.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/receiver.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/address.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/session.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/sender.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/connection.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/message.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/__init__.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/client.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/mgmt_operation.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/errors.py -> build/lib.linux-x86_64-3.10/uamqp
        copying uamqp/utils.py -> build/lib.linux-x86_64-3.10/uamqp
        creating build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/connection_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/sender_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/mgmt_operation_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/session_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/client_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/__init__.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/receiver_async.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        copying uamqp/async_ops/utils.py -> build/lib.linux-x86_64-3.10/uamqp/async_ops
        creating build/lib.linux-x86_64-3.10/uamqp/authentication
        copying uamqp/authentication/cbs_auth.py -> build/lib.linux-x86_64-3.10/uamqp/authentication
        copying uamqp/authentication/common.py -> build/lib.linux-x86_64-3.10/uamqp/authentication
        copying uamqp/authentication/cbs_auth_async.py -> build/lib.linux-x86_64-3.10/uamqp/authentication
        copying uamqp/authentication/__init__.py -> build/lib.linux-x86_64-3.10/uamqp/authentication
        running egg_info
        writing uamqp.egg-info/PKG-INFO
        writing dependency_links to uamqp.egg-info/dependency_links.txt
        writing requirements to uamqp.egg-info/requires.txt
        writing top-level names to uamqp.egg-info/top_level.txt
        reading manifest file 'uamqp.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        writing manifest file 'uamqp.egg-info/SOURCES.txt'
        copying uamqp/c_uamqp.c -> build/lib.linux-x86_64-3.10/uamqp
        running build_ext
        will build uamqp in build/temp.linux-x86_64-3.10/cmake
        Building with generator flags: -G "Unix Makefiles"
        calling cmake /tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release
        /bin/sh: cmake: not found
        Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/setup.py", line 260, in <module>
            setup(
            File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
            File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
            dist.run_commands()
            File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
            self.run_command(cmd)
            File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
            File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
            return orig.install.run(self)
            File "/usr/local/lib/python3.10/distutils/command/install.py", line 568, in run
            self.run_command('build')
            File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
            File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
            File "/usr/local/lib/python3.10/distutils/command/build.py", line 135, in run
            self.run_command(cmd_name)
            File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
            File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
            File "/tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/setup.py", line 134, in run
            self.build_cmake(ext)
            File "/tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/setup.py", line 183, in build_cmake
            subprocess.check_call(joined_cmd, shell=True, universal_newlines=True, env=build_env)
            File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command 'cmake /tmp/pip-install-helza4zb/uamqp_4e3fd5b07a6d479b83b8c54ee8bdbb18/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release' returned non-zero exit status 127.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure

    × Encountered error while trying to install package.
    ╰─> uamqp

    note: This is an issue with the package mentioned above, not pip.

**To Reproduce**

    $ pip install azure-eventhub

Using docker

    $ docker run --rm --platform linux/amd64 mcr.microsoft.com/azure-cli:latest bash -c "pip install azure-eventhub"

**Expected behavior**
Installation successful.

    bash-5.1# python --version
    Python 3.10.5
    bash-5.1# pip --version
    pip 22.0.4 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment]
@anupshrestha can you give me some more details about the OS you are trying this on? azure-eventhub definitely supports py3.10

**Comment by anupshrestha** [comment]
@kashifkhan I am running it on MacOS Monterey (Version 12.4) with the Apple M1 Pro chip.

**Comment by anupshrestha** [comment]
I might test it out and thanks for looking into it.
