### ISSUE TITLE
Explorer the Management APIs is not work

### ISSUE THREAD

**Issue by leizhang1984** [Azure/azure-sdk-for-python#25283]
Hi,

Explorer the Management APIs is not work.

Please help to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c273bd7f-1d12-2088-d726-9c926cfdf78c
* Version Independent ID: 7efc43f5-208d-1fb9-9c56-44d52d1703bc
* Content: [Azure Consumption libraries for python](https://docs.microsoft.com/en-us/python/api/overview/azure/consumption?view=azure-python#feedback)
* Content Source: [docs-ref-services/latest/consumption.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/consumption.md)
* Service: **multiple**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by tjprescott** [comment]
Since this is management plane, @msyyc can you take a look? @leizhang1984 can you be more specific about what doesn't work? What are you trying to do?

**Comment by leizhang1984** [comment]
@tjprescott 

Hello,

When I click "Explore the Management API", another browse tab is opened and address is:
https://docs.microsoft.com/en-us/python/api/overview/azure/consumption/management

This page display 404 not found. 

thanks.

**Comment by PramodValavala-MSFT** [comment]
@leizhang1984 Thanks for catching that! We worked up a PR to fix this.
