### ISSUE TITLE
ERROR 'ClientSecretCredential' object has no attribute 'signed_session'

### ISSUE THREAD

**Issue by gnsharans** [Azure/azure-sdk-for-python#25294]
I Was trying to Collect the List of Deny Assignments present in a particular tenant, So Passed required Arguments here

```
`tenant_id = arguments['tenant_id']`
`client_id = arguments['client_id']`
`client_secret = arguments['client_secret']`
```

Created ClientSecretCredentials Here

`csc = ClientSecretCredential(tenant_id=tenant_id,
                             client_id=client_id,
                             client_secret=client_secret)`

From Some Other Code, i have received list of SubScription Ids

```
for subscription_id in subscription_id_list:'\
    resource_client = authenticate.resource_client(subscription_id)
    resources_groups = get_all_resource_groups_detail(resource_client)
```

I am Able to get resourceGroups in that subscription id using some code

```
`    amc = AuthorizationManagementClient(csc, subscription_id)
    for resource_group in resources_groups:
        denylocks = amc.deny_assignments.list_for_resource_group(resource_group)
        try:`
```
Here it creates Error. denylocks, i am getting <azure.mgmt.authorization.v2018_07_01_preview.models._paged_models.DenyAssignmentPaged object> 

when i loop over the list of that object, it provides error :**ERROR 'ClientSecretCredential' object has no attribute 'signed_session'**
```
`            for locks in denylocks:
                print(locks)
        except Exception as exc:
            logger.error(exc)`
```

Hope its cleared, and expecting a quick reply

Thanks!!!

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Are you using azure-mgmt-authorization library?

Could you help to check the version you are using?

has no attribute 'signed_session' usually indicates this is a track 1 library.

If you upgrade your library to the latest version, it should go away.

Thanks.

**Comment by gnsharans** [comment]
Hey sorry, 

I have referred several Microsoft docs, 
Ref : https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md

The above ref resolved issue,

I just want to know, 
Is there a way better way to map all the python package versions, right now it's very hectic to resolve all the dependencies issues

Thanks.

I hope this issue is closed, by using mentioned ref doc
