### ISSUE TITLE
[QA] fix return type docs for LROs

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#25304]
Like in CLU, we need to use transforms to define the JSON returned from LROs. @heaths shared the following transforms we can use:

```
# Define HTTP 200 responses for LROs to document result model.
- where-operation: QuestionAnsweringProjects_DeleteProject
  transform: |
    $.responses["200"] = {
      description: "Project delete job status.",
      schema: {
        "$ref": "#/definitions/JobState"
      }
    };
- where-operation: QuestionAnsweringProjects_DeployProject
  transform: |
    $.responses["200"] = {
      description: "Deploy job state.",
      schema: {
        "$ref": "#/definitions/JobState"
      }
    };
- where-operation: QuestionAnsweringProjects_Import
  transform: |
    $.responses["200"] = {
      description: "Gets the status of an Import job.",
      schema: {
        "$ref": "#/definitions/JobState"
      }
    };
- where-operation: QuestionAnsweringProjects_UpdateQnas
  transform: |
    $.responses["200"] = {
      description: "Update QnAs job state.",
      schema: {
        "$ref": "#/definitions/JobState"
      }
    };
- where-operation: QuestionAnsweringProjects_UpdateSources
  transform: |
    $.responses["200"] = {
      description: "Update sources job state.",
      schema: {
        "$ref": "#/definitions/JobState"
      }
    };
```

**Comment by heaths** [comment]
FWIW, the `export` operation already had a 200 response defined.

**Comment by kristapratico** [comment]
@heaths Eh, it seems both UpdateSources and UpdateQnas need to be updated too. They are both PATCH operations and it seems our azure-core implementation follows a similar pattern to PUT where we GET on the original Uri. Does .NET do this as well? 

Also, these two appear to return pageables upon completion of the LRO. I'm needing to add x-ms-pageable to the transforms, but I think this is better added to the swagger itself. Just to confirm, is adding x-ms-pageable to the swagger breaking?

Here's the update I needed to make:

```
- where-operation: QuestionAnsweringProjects_UpdateQnas
  transform: |
    $["x-ms-pageable"] = {
      "nextLinkName": "nextLink",
      "itemName": "value"
    };
    $.responses["200"] = {
      description: "Update QnAs job state.",
      schema: {
        "$ref": "#/definitions/QnaAssets"
      }
    };
- where-operation: QuestionAnsweringProjects_UpdateSources
  transform: |
    $["x-ms-pageable"] = {
      "nextLinkName": "nextLink",
      "itemName": "value"
    };
    $.responses["200"] = {
      description: "Update sources job state.",
      schema: {
        "$ref": "#/definitions/QnaSources"
      }
    };
```

**Comment by heaths** [comment]
> Also, these two appear to return pageables upon completion of the LRO. I'm needing to add x-ms-pageable to the transforms, but I think this is better added to the swagger itself. Just to confirm, is adding x-ms-pageable to the swagger breaking?

Given it only should affect autorest and we haven't GA'd authoring, I don't think so. Adding @tg-msft and @Johanste for confirmation.
