### ISSUE TITLE
[AzureML] Migrate test pipeline

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#25312]
The live test pipeline needs to be migrated for both CI offline playback validation, and internal live resource validation.

cc @azureml-github

**Comment by annatisch** [comment]
Waiting on last workitem from @mccoyp (please feel free to update this issue with any status/questions etc)

**Comment by mccoyp** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/25457 tracks the work to provide an environment variable fixture.
