### ISSUE TITLE
[AzureML] Re-enable CI pipeline checks

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#25314]
Currently the following pipeline checks have been disabled.
- AnalyzeDependencies
- ApiStubGen
- Bandit
- BreakingChanges
- Pylint
- Spellcheck
These need to be re-enabled before GA.

cc @azureml-github

**Comment by annatisch** [comment]
Spellcheck now re-enabled.
Pylint underway.

**Comment by luigiw** [comment]
@annatisch I think we're done with this one. Can you confirm?

**Comment by annatisch** [comment]
Yup I believe so!
