### ISSUE TITLE
DefaultAzureCredential object has no attribute 'signed_session' using azure-mgmt-datalake-analytics==0.6.0

### ISSUE THREAD

**Issue by eberhardhummel** [Azure/azure-sdk-for-python#25326]
- azure-mgmt-datalake-analytics==0.6.0: 
- azure-identity==1.10.0:
- Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.2.5
- python 3.8.13: 

**Describe the bug**
getting error trying to employ azure-mgmt-datalake-analytics module in python in an azure linux function app. 

Sources:
credentials = DefaultAzureCredential(managed_identity_client_id=********************************)
adlaJobClient = DataLakeAnalyticsJobManagementClient(credentials, 'azuredatalakeanalytics.net')

Error: AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session' 

**Additional context**
The article below states that I should create an issue in the azure-sdk-for-python repo and request that the azure-mgmt-datalake-analytics be rebuilt and re-released using the new library which does not include signed_session:

https://stackoverflow.com/questions/63384092/exception-attributeerror-defaultazurecredential-object-has-no-attribute-sig

**Comment by tjprescott** [comment]
@eberhardhummel thank you for your report. @msyyc can you please take a look at this?

**Comment by xiangyan99** [comment]
Thanks for reaching out. 

Unfortunately, azure-mgmt-datalake-analytics library has not been migrated to track 2 and it does not work well with azure-identity library.

**Comment by eberhardhummel** [comment]
/unresolve - Hi @xiangyan99 [xiangyan99](https://github.com/xiangyan99) - I'm asking if you could correct the issue and re-release a new version of the azure-mgmt-datalake-analytics library so that its compatible with the azure-identity library as mentioned in the following article - https://stackoverflow.com/questions/63384092/exception-attributeerror-defaultazurecredential-object-has-no-attribute-sig

**Comment by Wzb123456789** [comment]
Hi @eberhardhummel, thanks for your feedback.

We have released a package about `azure-mgmt-datalake-analytics`.
https://pypi.org/project/azure-mgmt-datalake-analytics/1.0.0b1/

Please try the new one to solve your problem.

Hope to help you.
