### ISSUE TITLE
Explore Link Broken

### ISSUE THREAD

**Issue by ambroselittle** [Azure/azure-sdk-for-python#25325]
The Explore link is broken/404: https://docs.microsoft.com/en-us/python/api/overview/azure/powerbi/management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5109ef0-5dd6-309f-3e04-7d492e9a8020
* Version Independent ID: fff79500-7d5f-6c4a-aab0-684b8a6b90e2
* Content: [Azure Power BI SDK for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/power-bi?view=azure-python)
* Content Source: [docs-ref-services/latest/power-bi.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/power-bi.md)
* Service: **powerbi**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by tjprescott** [comment]
@sima-zhu can you take a look at this? Perhaps a docs generation issue?

**Comment by PramodValavala-MSFT** [comment]
@ambroselittle Thanks for catching that! We worked up a PR to fix this.

**Comment by xuanziranhan** [comment]
Thanks @ambroselittle for raising this up!

@PramodValavala-MSFT the link https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/python/api/overview/azure/powerbi/management is also broken.
May I ask what are covered in the power BI  embedded managementClient? I was trying to go through the models listed [here](https://docs.microsoft.com/en-us/python/api/azure-mgmt-powerbiembedded/azure.mgmt.powerbiembedded.models.operation(class)?view=azure-python), for workspaces related, looks like it's more for creating/updating workspaces. I can't quickly figure out if that wraps the admin rest API for scanning metadata in workspaces, mentioned [here](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-metadata-scanning)? If not, could you please point me to the right sdk that wraps the admin rest APIs?

Was also checking the powerbi dedicated sdk, that looks like it's mainly managing the capacity of power bi systems.

Thanks a lot!

**Comment by PramodValavala-MSFT** [comment]
@xuanziranhan The link actually doesn't work from the markdown file in GitHub directly but should work once deployed.

From the looks of it, the SDK seems to only support management operations for workspaces like you mentioned. It would be best to create a separate issue as a feature request to include support for those APIs. In the meantime, you can use the APIs listed in the doc you've shared directly.

**Comment by xuanziranhan** [comment]
thank you @PramodValavala-MSFT  for confirming!
