### ISSUE TITLE
coordinate measure

### ISSUE THREAD

**Issue by sergiosolorzano** [Azure/azure-sdk-for-python#25342]
please detail top, left, width and height are in pixels if that's the case (not cm or any other measure). thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86935bba-75d6-6193-2320-202d12c9bcc7
* Version Independent ID: 52808013-ff8e-2c0e-b1c1-81d1d3718361
* Content: [azure.cognitiveservices.vision.customvision.training.models.ImageRegionCreateEntry class](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-customvision/azure.cognitiveservices.vision.customvision.training.models.imageregioncreateentry?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cognitiveservices-vision-customvision/azure.cognitiveservices.vision.customvision.training.models.ImageRegionCreateEntry.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-cognitiveservices-vision-customvision/azure.cognitiveservices.vision.customvision.training.models.ImageRegionCreateEntry.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by tjprescott** [comment]
@sergiosolorzano thanks for the report! @sima-zhu can you help with this docs issue?

**Comment by sergiosolorzano** [comment]
I add further discussion. Setting the region with the Custom Vision SDK where the top/left/width/height measures are 0-1 range or pixels fails. See https://stackoverflow.com/questions/73078411/azure-custom-vision-sdk-imageregioncreateentry-doesnt-seem-to-set-region and https://stackoverflow.com/questions/73066025/what-measure-are-the-coordinates-for-method-imageregioncreateentry-in-azure-sdk?noredirect=1#comment129093934_73066025

**Comment by sima-zhu** [comment]
@lmazuel is the owner for the repo. Could you help triage the issue?

**Comment by tobaiMS** [comment]
Hi, as suggested in the stackoverflow channel.  Please follow the doc here to understand how the coordinate works https://docs.microsoft.com/en-us/azure/cognitive-services/custom-vision-service/quickstarts/object-detection?tabs=visual-studio&pivots=programming-language-csharp#upload-and-tag-images

**Comment by sergiosolorzano** [comment]
Thank you. I get the way it's supposed to be calculated, the problem is using the values below I can't see the bounding box on portal and training fails. Only when I set the boundingbox manually, training succeeds. I tried 0.05, 0.05, 0.9, 0.9 and as suggested 0.25, 0.25, 0.5, 0.5

**Comment by xiangyan99** [comment]
Seems like it is solved in attached code snippet.
