### ISSUE TITLE
Creation of virtual folders of blobs with special characters

### ISSUE THREAD

**Issue by ivanvaccarics** [Azure/azure-sdk-for-python#25387]
- **Package Name**: azure-storage-blob
- **Package Version**:  azure-storage-blob==12.12.0
- **Operating System**: Windows
- **Python Version**: 3.9.13

**Describe the bug**
When creating virtual folders inside a blob container, the sdk allows you to use special characters such as èàéòù while the azure portal does not allow it (see attachment). This leads to problems when creating the url of the stored file.

**Expected behavior**
Insert control that does not allow the use of special characters from the python library (handle the same behavior present on the azure portal).

**Screenshots**
Creation form azure portal:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/25437300/180782584-eeb4691d-3b44-4d36-9762-75adf1339c4e.png)
By using python sdk:
![image](https://user-images.githubusercontent.com/25437300/180783071-11bf8791-c35c-4329-8e54-367e3e271c52.png)

**Comment by swathipil** [comment]
@ivanvaccarics - Thanks for opening an issue. We'll investigate asap!

**Comment by vincenttran-msft** [comment]
Hi @ivanvaccarics Ivan, thanks for your inquiry! I believe that you may be mixing up some of the terms being used, so hopefully this explanation below helps to clear up any confusion! 

In general, for those seeking a more robust file system with the concept of directories and files, `azure-storage-file-datalake` would be the package that would support this behavior. This package requires a HNS (hierarchical namespace) enabled Storage account.

In contrast, for those who want a more simpler storage solution, the package of choice is `azure-storage-blob`, where all data is stored in blobs under a container.

Both use storage Containers as the top-level, and both enforce the naming convention shown in the error you shared (This name may only contain lowercase letters, numbers, and hyphens, and must begin with a letter or a number. Each hyphen must be preceded and followed by a non-hyphen character. The name must also be between 3 and 63 characters long.)

With this in mind, I think your original post, you were attempting to create a container with an illegal character, thus facing the error, but had mistakenly thought you were creating a directory.
![image](https://user-images.githubusercontent.com/101599632/180897038-2a03b6a4-04d5-4145-9e7f-7993cad50c32.png)
(Note how this is the prompt from 'New container')

For further clarification, here is the options when interacting with a hierarchical namespace enabled storage account:
**HNS Enabled Account**
![image](https://user-images.githubusercontent.com/101599632/180896598-d2018999-e9e6-456e-b308-383bdd377e5b.png)

**Non-HNS Enabled Account**
![image](https://user-images.githubusercontent.com/101599632/180896894-6d2f4bc8-1dce-464d-a107-a40d276a705e.png)
(Note the option to 'Add Directory' is not present for flat accounts)

Hopefully this resolves your issue, but please let us know if you have any other questions!
Thanks!

**Comment by ivanvaccarics** [comment]
Hi @vincenttran-msft, thanks a lot for your message. He clarified my doubt. Thanks!

**Comment by vincenttran-msft** [comment]
Hi @ivanvaccarics Ivan, glad that we were able to help clear up any confusion! We will continue with the closure of this issue!
Thanks!
