### ISSUE TITLE
`azure-mgmt-authorization` release notes invalid

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-sdk-for-python#25384]
The Python package for `azure-mgmt-authorization` is out of sync with main by quite some way.

https://pypi.org/project/azure-mgmt-authorization/2.0.0/ 

In the README for the package:

>>> This package has been tested with Python 2.7, 3.4, 3.5, 3.6 and 3.7.

This is no longer valid. Older versions are not supported and this is missing newer versions which are supported.

The trove specifiers in main have 3.8-3.10 as well, but the published package does not.

**Comment by xiangyan99** [comment]
Thanks for the feedback.

It looks to me the release notes are in sync with the one in the package which was shipped on 2021-09-25.

The readme in main branch was updated after 2021-09-26 and there was no new releases yet.
