### ISSUE TITLE
Update data-plane quickstarts for test-proxy guidance

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#25392]
@mccoyp TIL about this source https://github.com/Azure/azure-sdk-for-python/wiki/Dataplane-Codegen-Quick-Start-for-Test

We probably want to update the default so that new devs hitting our wiki are given non-vcrpy guidance.

**Comment by mccoyp** [comment]
@msyyc handled this for us, so things are looking up to date. Thank you, Yuchao!
