### ISSUE TITLE
No support for UseDevelopmentStorage=true on connection string

### ISSUE THREAD

**Issue by LuckyLub** [Azure/azure-sdk-for-python#25407]
- **Package Name**:  azure-data-tables
- **Package Version**: 12.4.0
- **Operating System**: Ubuntu
- **Python Version**: 3.9

**Describe the bug**
It's not possible to call the TableServiceClient.from_connection_string() method with `UseDevelopmentStorage=true` as input, which is basicaly same issue as issue [13100 in azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js).

The solution to that issue also works here: when `UseDevelopmentStorage=true` is provided as the connection string it should use the following connection string instead: `DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1`

**To Reproduce**
```python
from azure.data.tables import TableServiceClient

table_client = TableServiceClient.from_connection_string("UseDevelopmentStorage=true")
```

**Expected behavior**
Should connect to emulator.

**Screenshots**

**Additional context**

**Comment by swathipil** [comment]
Hi @LuckyLub - Thanks for opening an issue! We'll investigate this asap!
