### ISSUE TITLE
Use exception-group in chained identity credential

### ISSUE THREAD

**Issue by EpicWink** [Azure/azure-sdk-for-python#25418]
### Problem
The message for chained identity credentials is too long, and contains line-breaks.

In my case, this makes it difficult to see the whole error in Sentry as the message is truncated. Outside of Sentry, having single-line exception messages is generally more palatable in most cases. Further information should be attached separately (eg Python 3.11's [exception notes](core.exceptions)).

### Proposed solution
Use [exception groups](https://docs.python.org/3.11/library/exceptions.html#exception-groups) ([backport for Python <3.11](https://github.com/agronholm/exceptiongroup)) for [identity's](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity/azure-identity) [ChainedIdentityCredential](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/chained.py). All attempted credentials raise their own exception, and all are grouped into an exception-group (probably also subclassed from `azure.core.exceptions.ClientAuthenticationError`). Users and support libraries (eg Sentry) then have control over how to display child exceptions.

The backport also adds exception notes to the exception groups, and by default adds an exception formatter which includes these notes.

To reduce side-effects using the backport, you could disable patching:
```python
_original = os.environ.get("EXCEPTIONGROUP_NO_PATCH")
os.environ["EXCEPTIONGROUP_NO_PATCH"] = 1
try:
    import exceptiongroup
finally:
    if _original is None:
        del os.environ["EXCEPTIONGROUP_NO_PATCH"]
    else:
        os.environ["EXCEPTIONGROUP_NO_PATCH"] = _original
```

### Alternative solutions
I could catch all `azure.core.exceptions.ClientAuthenticationError` at the top-level, parse and truncate the message, and log each line, but this then depends on exception message structure, which is always subject to change in Python. Also, this requires a lot more diligence to ensure all of these exceptions are caught.

**Comment by swathipil** [comment]
@EpicWink - Thanks for your feedback! We'll investigate as soon as possible.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you help to give more concrete details?

E.g. what actual message you got, what you expected?

`ChainedIdentityCredential` is for advanced usage and in the design, user may not have a long list of credentials in the chain.

Thanks.

**Comment by EpicWink** [comment]
I'm using the `DefaultAzureCredential`, which inherits from `ChainedIdentityCredential`. My error message is:
```
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: No managed identity endpoint found. 
The Target Azure platform could not be determined from environment variables. 
Visit https://aka.ms/azsdk/python/identity/managedidentitycredential/troubleshoot to troubleshoot this issue.
	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
	VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
	AzureCliCredential: Azure CLI not found on path
	AzurePowerShellCredential: PowerShell is not installed
```

This exception is expected in this case (I had forgotten to set the environment variables in my app deployment). My issue is that in Sentry, the message is truncated such that I can't see the reasons each individual credential failed.

(Note: I'm setting `IDENTITY_ENDPOINT` to `https://example.com` to skip the managed identity credential. This is because I'm using `http://169.254.169.254` for something else, and the IMDS credential can't handle that. This is not relevant to this issue)

**Comment by xiangyan99** [comment]
Thanks for your information.

As you may notice, the core scenario for DefaultAzureCredential is for development uses.

In this case, we want the error message as detail as possible.

When you deploy your app to production environment, maybe specifying a specific credential or using ChainedIdentityCredential are your best choices.

**Comment by EpicWink** [comment]
I still think using exception groups is useful for programmatic inspection of the individual exceptions, even if my use-case isn't supported.

I also disagree that `DefaultAzureCredential` should only be used for development purposes: our policy is to use the same code in development as in production (even if the code does different things between the two environments). This means using managed identity or environment credentials in production, while using whatever's available (usually VSCode or Azure CLI login, but sometimes environment) in development. This is however orthogonal to the original post.

> In this case, we want the error message as detail as possible.

Using exception groups, the error message would be accompanied by all exceptions' messages, formatted either by the user explicitly, or using a default formatting provided by Python 3.11 (or the `exceptiongroups` library for Python <3.11), potentially giving the user more information than what they get now.

**Comment by xiangyan99** [comment]
`DefaultAzureCredential` works perfectly in most of the scenarios.

But if you want 100% deterministic behavior, `DefaultAzureCredential` may be not your best answer.

And agreed with you. This is orthogonal to the original post. :)
