### ISSUE TITLE
Cosmos DB max_integrated_cache_staleness_in_ms should allow 0 as a value

### ISSUE THREAD

**Issue by jcocchi** [Azure/azure-sdk-for-python#25483]
- **Package Name**: azure-cosmos
- **Package Version**: 4.3.0b3
- **Operating System**: Windows 11
- **Python Version**: 3.8.3

**Describe the bug**
Setting `max_integrated_cache_staleness` for `read_item` to 0 should be valid but throws a "ValueError: Parameter 'max_integrated_cache_staleness_in_ms' can only be a positive integer." error. This input parameter is valid for the `query_items` function, but it doesn't set the cache staleness to 0 and instead it appears to fall back to the default cache staleness of 5 minutes.

**To Reproduce**
1. `item_response = container.read_item(item='1', partition_key='1', max_integrated_cache_staleness_in_ms=0)`
2. The first query should cost X RUs and the second query should also cost X RUs, indicating that query 1 wasn't cached due to the staleness being set to 0

`query = "SELECT * FROM c"
items = list(container.query_items(
    query=query,
    max_integrated_cache_staleness_in_ms=0
))
request_charge = container.client_connection.last_response_headers['x-ms-request-charge']
print('Operation consumed {1} request units'.format(request_charge))

items2 = list(container.query_items(
    query=query,
    max_integrated_cache_staleness_in_ms=0,
))
request_charge2 = container.client_connection.last_response_headers['x-ms-request-charge']
print('Operation consumed {1} request units'.format(request_charge2))`

**Expected behavior**
Setting `max_integrated_cache_staleness_in_ms` to 0 should bypass the integrated cache and each subsequent request should be refreshed from the backend. https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-integrated-cache#adjust-maxintegratedcachestaleness

**Comment by SaurabhSharma-MSFT** [comment]
@jcocchi We are looking into it and get back to you for any additional information.

**Comment by JericHunter** [comment]
Hi @jcocchi we found the reason why it was raising the error when setting 0, it's a very small and easy fix and we will try to have that out asap. Thank you very much for being thorough with your explanation of the issue.
