### ISSUE TITLE
FlowLog class attribute values not populated

### ISSUE THREAD

**Issue by VaKale-ptc** [Azure/azure-sdk-for-python#25484]
- **Package Name**: 
- azure-mgmt-network
- **Package Version**: 
- 20.0.0
- **Operating System**:
- Windows 10 21H2
- **Python Version**: 
Python 3.9.9

**Describe the bug**
We are using Python API to create NSG FLowLog 'NetworkWatchersOperations::begin_set_flow_log_configuration'. This does not provided info about FlowLog. How can we check the FlowLog Provisioning state using Python API? I have attached a pic while debugging which displays FlowLog info, but none of the attributes value are populated, even if the web portal displays FLowLog to be enabled.

**To Reproduce**
Here is the pseudo-code used to enable FlowLogs:
 
flowLogInfo = azure.mgmt.network.models::FlowLogInformation (target_resource_id=nsg.id,
                storage_id=int_storage_id,
                enabled=True,retention_policy=netw_models.RetentionPolicyParameters(days=90,enabled=True),
                format=netw_models.FlowLogFormatParameters(type='JSON'))
            …
            NetworkManagementClient::network_watchers.begin_set_flow_log_configuration(
                    resource_group_name='NetworkWatcherRG',
                    continuation_token=None,network_watcher_name=watcher,
                    polling=False,polling_interval=0, parameters=fli)
…

**Expected behavior**
We expect FlowLog attributes to be populated and reflect its state correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/110377639/182094493-21df1eab-7ec8-4036-a6dd-e8aae647fdd8.png)

**Comment by msyyc** [comment]
Hi @VaKale-ptc In python SDK, if operation name has `begin_` prefix, it is long running operation. You'd better use it like:
```
response = network_watchers.begin_set_flow_log_configuration(...)
final_response = response.result()
```
in `final_response`, you shall see some status returned by server(provisioning_state, etc)
