### ISSUE TITLE
[Compute Gallery] Typo in file test_mgmt_compute_galleries.py

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-python#25506]
- **Package Name**: 
- azure-mgmt-compute
- **Package Version**: 
- latest
- **Operating System**:
- **Python Version**: 
3.8

**Describe the bug**
Issue 1:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/tests/test_mgmt_compute_galleries.py

Line 137 
hyper_vgeneration should be hyper_v_generation

Issue 2:
If I run delete version and delete gallery image definition in sequence, there is exception thrown:
azure.core.exceptions.ResourceExistsError: (CannotDeleteResource) Can not delete resource before nested resources are deleted.

It seems the clean work did not complete, if I put code to sleep 10 seconds, it will succeed.

print("delete image version")
result = compute_client.gallery_image_versions.begin_delete(resource_group, GALLERY_NAME, image_definition, "1.0.2")
result = result.result()
print(result)

print("delete image definition")
result = compute_client.gallery_images.begin_delete(resource_group, GALLERY_NAME, image_definition)
result = result.result()
print(result)

**Comment by SaurabhSharma-MSFT** [comment]
@yangchengs We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@yangchengs I have submitted a PR to fix your 1st issue.  Regarding 2nd issue, like you said you may have to wait for some time after deleting image versions before deleting image definitions.  Did you try doing the same using [CLI](https://docs.microsoft.com/en-us/azure/virtual-machines/update-image-resources?tabs=cli%2Ccli2%2Ccli4) if it gets deleted without a wait.

**Comment by yangchengs** [comment]
@SaurabhSharma-MSFT I test az command for several times but cannot reproduce the same issue, the az command seems to be good.

az sig image-version delete --resource-group yangshenrg001 --gallery-name gallery1 --gallery-image-definition imagedefinition --gallery-image-version 1.0.2
az sig image-definition delete --resource-group yangshenrg001 --gallery-name gallery1 --gallery-image-definition imagedefinition

**Comment by yangchengs** [comment]
@SaurabhSharma-MSFT can you check the second issue? I tested az cli and it works good.

**Comment by sandeepraichura** [comment]
@yangchengs - It looks like an expected behavior as the parent resource cannot be deleted while the child resource still is getting deleted. Let me validate and update.

**Comment by sandeepraichura** [comment]
@yangchengs - This is an expected behavior and by design as you have to wait few seconds for the child resource to be deleted before the parent resource can be deleted. Closing this, but please do reopen if you see any concerns.
