### ISSUE TITLE
contaioner.replace_item exception 

### ISSUE THREAD

**Issue by soferreira** [Azure/azure-sdk-for-python#25516]
- **Package Name**:  azure.cosmos
- **Package Version**: 4.3.0
- **Operating System**: windows
- **Python Version**: 3.10.4 

**Describe the bug**

When I try to replace an existing item by a new one where id or partitionKey is missing, the code throws the following error:
azure.cosmos.exceptions.CosmosResourceNotFoundError: (NotFound) Entity with the specified id does not exist in the system.

which is a bit misleading because the item exists, the issue is on the new item body. 

**To Reproduce**
1. try to replace an existing item by a new one without the partition key value (partition key is lastName)
Example: 
new_item = container.replace_item(item="Andersen_188d0b3a-3c89-4888-a01b-ede546dd1373", body={'id': 'Andersen_})

**Expected behavior**
Instead of specifying that the item was not found (which is not true), it would be best to throw an error where it is clear that the issue is in the new provided body. In this specific case, specify that a new document must have the partition key value. 

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/101214403/182442644-57a69f95-16e9-4de0-b04a-2e697b704344.png)

Item exists in the container:
![image](https://user-images.githubusercontent.com/101214403/182442779-31ef7a75-ed85-4501-b2cd-775b7f0617d5.png)

**Comment by JericHunter** [comment]
@soferreira Could you send full code snippet for this issue you are having? Thank you so much for showing us this bug I will take a look to see if we can get this fixed asap.

**Comment by soferreira** [comment]
[JericHunter](https://github.com/JericHunter) please find above the full code snippet for this issue.

I am aware that the container. Replace() call fails because 'lastName' property (the partition key) is not part of the body. I believe it should say something like "The input content is invalid because the required properties - 'lastName; ' - are missing." 

[The documentation] (https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.container.containerproxy?view=azure-python#azure-cosmos-container-containerproxy-replace-item) also does not mention that the partition key is a required property of the body.

**Comment by JericHunter** [comment]
thank you @soferreira for responding swiftly with the detailed info, I will go ahead and take a closer look at this asap.

**Comment by simorenoh** [comment]
Hi @soferreira, thank you for using our SDK. The issue you are seeing is by-design, since the SDK does not do validation on whether the body that was passed in by the user has the fields that are required - even if your new body was missing an 'id' field, like you mentioned, you wouldn't find out until after the service receives the request. What the service is trying to do in the backend is find the object to replace it - if it doesn't find it (because id/pk combination don't exist) then you'll naturally run into a 404. I hope this makes sense.
