### ISSUE TITLE
azure-ai-formrecognizer: Include vcr cassettes in pypi package

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#25528]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.1.2
- **Operating System**: Fedora 36
- **Python Version**: 3.10.5

**Describe the bug**
Although the tests are included with azure-ai-formrecognizer in pypi packages, the vcr cassettes are not provided. This causes almost all of the tests to fail.

**To Reproduce**
1. Download azure-ai-formrecognizer from pypi and extract
2. Run `pytest`
3. Almost all tests fail

**Expected behavior**
I would expect the tests to run properly with the vcr cassettes.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by catalinaperalta** [comment]
Hi @major, thanks for reaching out. We are going to be including test recordings as of package version 3.2.0b6.

**Comment by major** [comment]
> Hi @major, thanks for reaching out. We are going to be including test recordings as of package version 3.2.0b6.

Thank you!
