### ISSUE TITLE
A document is not running using the sdk

### ISSUE THREAD

**Issue by BaherAbdullah** [Azure/azure-sdk-for-python#25530]
One of the documents I tried using Custom NER SDK, does not return any extracted entities. But when I try other documents, the SDK works fine. I tried the same document using API and portal, and it worked fine and returned entities

**Comment by xiangyan99** [comment]
Could you help to give more details about the library you used?

Thanks.

**Comment by kristapratico** [comment]
This is for text analytics, we're discussing in chat. Will update the thread once I know more.

**Comment by kristapratico** [comment]
I'm able to reproduce this. The currently released SDK targets 2022-04-01-preview API version while the API and Portal used were targeting 2022-05-01. Entities are not returned with the April version, but do get returned with the May version for this particular sample. Upgrading to the v5.2.0b5 SDK (which targets 2022-05-01) will solve this problem.
