### ISSUE TITLE
Cannot find job after running BackupsOperations.trigger() 

### ISSUE THREAD

**Issue by iwahing** [Azure/azure-sdk-for-python#25549]
When triggering backup it does not return anything and I cannot find the job that does the backup.
![image](https://user-images.githubusercontent.com/23308457/182761767-bd5835ba-0c79-478a-bca7-e3b3d97ea77c.png)

It says in the documentation to use `GetProtectedItemOperationResult API` and I am assuming its in ProtectedItemOperationResultsOperations  
![image](https://user-images.githubusercontent.com/23308457/182762083-ee3749eb-e8a0-40f1-baae-249e4cadfa54.png)
![image](https://user-images.githubusercontent.com/23308457/182762926-7d4ca385-fc33-415d-bf69-3490f1efc1b4.png)
but I have no way of getting the operationId

Is there a way to get a job name after triggering backup?

**Comment by xiangyan99** [comment]
Thanks for reaching out. 

Could you help to provide the information which library did you use and the version?

Thanks.
