### ISSUE TITLE
[Search] Enable national cloud support for Azure Search SDK

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-python#25567]
We need to enable multi cloud support in Azure Search SDK. Search service currently supports challenge based authentication, however the support is not always guaranteed. Since challenge based response isn’t guaranteed, add configuration to allow the users to set the audience when using a cloud other than public cloud.

Please refer .NET implementation to see how to expose the audience:
https://github.com/Azure/azure-sdk-for-net/pull/30316

**Comment by xiangyan99** [comment]
Done.
