### ISSUE TITLE
Cannot import azure.common on Win10 Python3.5

### ISSUE THREAD

**Issue by forhonourlx** [Azure/azure-sdk-for-python#2558]
PS C:\Users\simon\Desktop\Rainbow_Ref\deeprl-baselines-master\baselines\rainbow\experiments\atari> pip install azure-common
Requirement already satisfied: azure-common in c:\program files\python35\lib\site-packages\azure_common-1.1.9-py3.5.egg

PS C:\Users\simon\Desktop\Rainbow_Ref\deeprl-baselines-master\baselines\rainbow\experiments\atari> python rainbow.py
Traceback (most recent call last):
  File "rainbow.py", line 27, in <module>
    from baselines.common.azure_utils import Container
  File "C:\Program Files\Python35\lib\site-packages\baselines-0.1.4-py3.5.egg\baselines\common\azure_utils.py", line 5, in <module>
ImportError: No module named 'azure.common'

Could somebody give me a helping hand? Thanks.
What's wrong with import azure.common on Win10 Python3.5?

**Comment by lmazuel** [comment]
Hi @forhonourlx 
`azure-storage` is deprecated, and shouldn't be used anymore. This creates trouble with more recent packages. See note from Storage team:
https://github.com/Azure/azure-storage-python#download
