### ISSUE TITLE
Search 11.3.0 GA for python

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#25625]
We are targeting Azure Search SDK GA next month. Here is the scope for upcoming GA:

Public surface area of last GA version
AAD support including multi cloud support
Any bug fixes since then
GA release version:

Release azure-search-documents GA version 11.3.0 with the features listed above
Right after releasing GA 11.3.0, release 11.4.0b1 with all the preview features released after 11.3.0, so that if users try to use the latest version, they will get all GA as well as preview features.
Follow the below steps for the GA release:

- [ ] Create a feature branch using tag of the last released version
- [ ] Add below features
       - [ ] AAD support including multi cloud support
       - [ ] Any bug fixes since then
- [ ] Update the changelog by adding the release information about all the preview versions released after last 11.4.0 GA.
- [ ] Update the changelog to add GA release features for 11.3.0 version.
- [ ] Create PR
- [ ] Create API view and add link [issue to be created] here for architects to review.
- [ ] Update PR as per the feedback and merge it.
- [ ] Release azure-search-documents - 11.3.0 GA version using feature branch.
- [ ] Update changelog in the main branch to add 11.3.0 and 11.4.0b1 release information.
- [ ] Release azure-search-documents - 11.4.0b1 beta version using main branch.

**Comment by xiangyan99** [comment]
Done.
