### ISSUE TITLE
[Storage] Batch Request Sanitizer (List to Update)

### ISSUE THREAD

**Issue by vincenttran-msft** [Azure/azure-sdk-for-python#25623]
During test proxy migration, we have run into an issue with having difficulties sanitizing batch operations. This issue serves to maintain a list of what tests should be recorded once we have the batch sanitizer.

**test_container.py (sync & async)**
- test_delete_blobs_simple
- test_delete_blobs_with_version_id
- test_delete_blobs_simple_no_raise
- test_delete_blobs_snapshot
- test_standard_blob_tier_set_tier_api_batch
- test_batch_set_standard_blob_tier_for_version
- test_standard_blob_tier_with_if_tags

**test_common_blob.py (sync & async)**
- test_token_credential_with_batch_operation

**Comment by jalauzon-msft** [comment]
Bumpity
