### ISSUE TITLE
Azure AI ML: Creating a pipeline component with multiple inputs

### ISSUE THREAD

**Issue by davystrong** [Azure/azure-sdk-for-python#25653]
**Is your feature request related to a problem? Please describe.**
Hello! I'm trying to use the Python SDK v2 for ML Studio and I need to run a pipeline on data from a blob storage location. My storage location is divided into folders and each folder contains multiple files. I want to run my pipeline on, say, 20 of these folders, and not the other 50. However, 20 is just an example, it's variable and could as easily be 50 or 100.

**Describe the solution you'd like**
I would like to pass multiple paths to a single `Input` object.

**Describe alternatives you've considered**
There may be some way of doing this by first registering a v1 dataset with multiple paths, then getting this dataset by name in v2. I haven't managed it yet. But even if that is possible, it's a horrible approach and requires mixing v1 and v2, which doesn't seem sensible. And I can't use v1 for the whole thing since it is missing some other requirements.

And in case it's suggested, I can't filter my files inside the script as I'm using a parallel component which automatically splits the data.

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by yongjiaaaa** [comment]
Hi! One option you can try is using mltable. Please check this doc for reference: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-data-assets?tabs=CLI#create-a-mltable-data-asset

**Comment by davystrong** [comment]
Hi @yongjiaaaa, thanks for the suggestion! I thought of that too since the old `Dataset` object seems to be backed by `MLTable` now (I've actually been reading that page to try to find a solution). However, my files are image files, not parts of a tabular dataset, and I can't find a way of getting this to work. I imagine it must be possible somehow to get an MLTable dataset to act as a file dataset, since this is what v1 does, but I haven't managed.

**Comment by Man-MSFT** [comment]
Hey @davystrong , while `MLTable` has tabular in mind, the transformations section is optional. So to use multiple paths you can do something like:
`MLTable`:
```
paths:
  - file: ./file1.jpg
  - file: ./file2.png
```
cc @SturgeonMi for doc updates, adding the MLTable schema JSON and calling out the required/optional portions. Thanks!!

**Comment by davystrong** [comment]
Hi @Man-MSFT, my main problem was actually slightly further on. I finally worked out today that the path when defining the input must point to a folder containing the MLTable file, not to the MLTable file itself, even though I don't actually include any local files in my MLTable. I understand why this is but it would be helpful to mention this specifically in the docs (it's the same for the YAML schema for a pipeline job, which I had been trying to get working before moving to Python). Unless, of course, I missed it!

**Comment by Man-MSFT** [comment]
@davystrong I see we added a purple note [here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-data-assets?tabs=CLI#create-a-mltable-data-asset) that path must point to the folder. But that is good feedback and we will see if we can make it more obvious. Thanks again! 
Let me know if there's anything else, otherwise will consider the matter resolved.

**Comment by davystrong** [comment]
@Man-MSFT Well, not sure how I missed that! Not sure how you could make it more obvious. That's exactly what I needed. Thanks for your help!
