### ISSUE TITLE
azure.monitor.opentelemetry.exporter add support for stable metrics export in opentelemetry 1.12

### ISSUE THREAD

**Issue by jenshnielsen** [Azure/azure-sdk-for-python#25663]
**Is your feature request related to a problem? Please describe.**

It looks like the newly released stable version of opentelemetry 1.12.0 broke the telemetry exporter in
azure.monitor.opentelemetry.exporter

**Describe the solution you'd like**

Adapt to match stable api in opentelemetry 1.12

There seems to be two changes required.

```AzureMonitorMetricExporter``` does not implement the abstract method ``force_flush`` as defined by 
 ```opentelemetry.sdk.metrics.export.MetricExporter```

```BaseExporter.__init__``` does not call the base classes ```__init__``` using super causing the two 
private attributes ```self._preferred_temporality``` and  ```self._preferred_aggregation``` to not be set.
```PeriodicExportingMetricReader``` expects these to be present in the exported class given to it.

**Describe alternatives you've considered**

Continue using unstable api from rc does not seem like a viable solution.

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by rakshith91** [comment]
@lzchen can you take a look ?

**Comment by lzchen** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/25659
