### ISSUE TITLE
AzureML - v1 ParallelRunStep arguments in v2

### ISSUE THREAD

**Issue by timgabrhel** [Azure/azure-sdk-for-python#25673]
In the V1 SDK, I can create a `ParallelRunStep` and execute this directly within a `Pipeline` (`Job`, here in v2). The `ParallelRunStep` allows me to configure a set of `arguments` that are passed in to the host driver that kicks off each of the steps.

```python
        arguments = ["--model_name", self.model_name,"--first_task_creation_timeout",518400, "--batch_size", self.batch_size]

        batch_score_step = ParallelRunStep(
            name=parallel_step_name,
            inputs=[input_images.as_named_input("input_images")],
            output=output_dir,
            arguments=arguments,
            parallel_run_config=parallel_run_config,
            allow_reuse=False,
        )
```

This is a snippet from the logging output from `70_driver_log.txt` from a completed inference run. You can see the arguments above were passed directly inline to the execution.
```
Preparing to call script [driver/amlbi_main.py] with arguments:[{redacted}, '--first_task_creation_timeout', '518400', '--batch_size', '20']
```

My specific goal is to be able to specify the `first_task_creation_timeout` parameter while using the v2 SDK. I am processing a large dataset and the error message received by AzureML upon execution timeout was to use this parameter.

How can I perform this in v2?  I don't see any arguments, or detailed enough documentation for other properties, that would allow me to configure. I have looked in depth using the HTTP REST API as well as the V2 Python SDK, and none of these entities offer support:
- BatchEndpoints
- BatchDeployments 
- Jobs

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by bupt-wenxiaole** [comment]
@timgabrhel  please reference [this document](https://github.com/Azure/azureml-examples/blob/sdk-preview/sdk/jobs/pipelines/1g_pipeline_with_parallel_nodes/pipeline_with_parallel_nodes.ipynb to how to set the arguments. 
you may need the extra permission to access this notebook.
note that the PRS SDK V2 is under the private preview, and the argument name has been changed from "arguments" to "args"
`# load component
prepare_data = load_component(path='./src/prepare_data.yml')

# parallel task to process file data
file_batch_inference = parallel(
  name = 'file_batch_score',
  display_name = 'Batch Score with File Dataset',
  description = 'parallel component for batch score',
  inputs = dict(job_data_path=Input(type=AssetTypes.MLTABLE, description='The data to be split and scored in parallel')),
  outputs = dict(job_output_path=Output(type=AssetTypes.MLTABLE)),
  input_data = '${{inputs.job_data_path}}',
  instance_count = 2,
  mini_batch_size = '1',
  mini_batch_error_threshold = 1,
  max_concurrency_per_instance = 1,
  task = ParallelTask(
    type = 'function',
    code = './src',
    entry_script = 'file_batch_inference.py',
    args = '--job_output_path ${{outputs.job_output_path}}',
    environment = 'azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu:1'
  ),
)
`
