### ISSUE TITLE
receive_deferred_messages does not work

### ISSUE THREAD

**Issue by mhoang-woolworths-com-au** [Azure/azure-sdk-for-python#25698]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
When I use receive_deferred_messages I always get this error below. Note this only happens when using receive_deferred_messages. When I use PeekLock=1 and peek_messages(max_message_count=count, sequence_number=sequence) I have no problem receiving the deferred messages

File "C:\Python3.7\lib\site-packages\azure\servicebus\_servicebus_receiver.py", line 760, in receive_deferred_messages
    timeout=timeout,
  File "C:\Python3.7\lib\site-packages\azure\servicebus\_base_handler.py", line 520, in _mgmt_request_response_with_retry
    **kwargs
  File "C:\Python3.7\lib\site-packages\azure\servicebus\_base_handler.py", line 416, in _do_retryable_operation
    raise last_exception
  File "C:\Python3.7\lib\site-packages\azure\servicebus\_base_handler.py", line 402, in _do_retryable_operation
    return operation(**kwargs)
  File "C:\Python3.7\lib\site-packages\azure\servicebus\_base_handler.py", line 502, in _mgmt_request_response
    callback=callback,
  File "C:\Python3.7\lib\site-packages\uamqp\client.py", line 348, in mgmt_request
    **kwargs)
  File "C:\Python3.7\lib\site-packages\uamqp\session.py", line 126, in mgmt_request
    return parse_response(status, response, description)
  File "C:\Python3.7\lib\site-packages\azure\servicebus\_common\mgmt_handlers.py", line 130, in deferred_message_op
    status_code,
  File "C:\Python3.7\lib\site-packages\azure\servicebus\exceptions.py", line 158, in _handle_amqp_mgmt_error
    status_code=status_code,
azure.servicebus.exceptions.MessageNotFoundError: Retrieving deferred messages failed. b'Failed to lock one or more specified messages. Either the message is already locked or does not exist

**To Reproduce**
1. Add some deferred messages into topic
2. Use ServiceBus explorer to check and get the sequence number
![image](https://user-images.githubusercontent.com/16406398/184592153-e6c4718a-b42e-4583-83e8-8191650d266b.png)
3. Copy the sequence number into the code below
    deferred_sequenced_numbers = [248170830]
    received_deferred_msg = receiver.receive_deferred_messages(sequence_numbers=deferred_sequenced_numbers, timeout=300)
    for msg in received_deferred_msg:
        print("Deferred msg: {}".format(str(msg)))

**Expected behavior**
The message would be printed

**Screenshots**
The error: azure.servicebus.exceptions.MessageNotFoundError: Retrieving deferred messages failed. b'Failed to lock one or more specified messages. Either the message is already locked or does not exist

**Additional context**

**Comment by annatisch** [comment]
Thanks for reporting @mhoang-woolworths-com-au!
We will investigate asap :)
To help is reproduce the error - are you able to provide some details regarding the configuration of the queue/subscription that is being received from?
For example - are sessions enabled, is the entity partitioned etc?

@swathipil - are you able to take a look?

**Comment by swathipil** [comment]
Hi @mhoang-woolworths-com-au - In addition to answering Anna's questions above, would you be able to provide the following information?
* azure-servicebus Version:
* Operating System:
* Based on your logs, it looks like you're using Python 3.7. Can you confirm this?
Thanks!

**Comment by mhoang-woolworths-com-au** [comment]
Hi, there is no session, partition, yes Python 3.7 and updated to lastest sdk version

**Comment by mhoang-woolworths-com-au** [comment]
Windows 10, sdk latest updated today

**Comment by swathipil** [comment]
Hey @mhoang-woolworths-com-au - I followed the steps you outlined and was not able to reproduce the error, unfortunately.

FYI: Here is my code snippet. Please let me know if anything looks incorrect.
```
import os
from azure.servicebus import ServiceBusMessage, ServiceBusClient

CONNECTION_STR = os.environ['SERVICE_BUS_CONNECTION_STR']
TOPIC_NAME = os.environ["SERVICE_BUS_TOPIC_NAME"]
SUBSCRIPTION_NAME = os.environ["SERVICE_BUS_SUBSCRIPTION_NAME"]

servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR)

with servicebus_client:
    receiver = servicebus_client.get_subscription_receiver(TOPIC_NAME, subscription_name=SUBSCRIPTION_NAME)
    with receiver:
        # manually found the message sequence number with the subscription Service Bus Explorer.
        deferred_sequenced_numbers = [1178]
        received_deferred_msg = receiver.receive_deferred_messages(
            sequence_numbers=deferred_sequenced_numbers
        )

        for msg in received_deferred_msg:
            print("Completing deferred msg: {}".format(str(msg)))
            receiver.complete_message(msg)
```
A few more questions for you:
1) How many messages are you deferring and receiving at a time?
2) In your code to reproduce, you mention that you check the Service Bus Explorer online for the sequence number of the deferred message. Is this your regular code flow? Or was this used just to help reproduce this error? If this is not your regular code flow, how do you generally keep track of your deferred sequence numbers?

Thanks!

**Comment by mhoang-woolworths-com-au** [comment]
Hi,

Im using your exact test code just populate with my deferred message sequence and get same error. I'm using premium tier and have > 300K deferred messages, I tried changing timeout to really long and makes no difference, this error just appear in few seconds

Status code: 500
Message: b'Failed to lock one or more specified messages. Either the message is already locked or does not exist. TrackingId:f07a0795-a2ac-4d31-83ad-a74771a2a62b_B27, SystemTracker:xxx:yyy|zzz, Timestamp:2022-08-22T01:18:32'
Failed to complete mgmt operation.

**Comment by swathipil** [comment]
@mhoang-woolworths-com-au - Would you be able to turn on info-level logging and respond with those logs?

To turn on logging, you can pass in `logging_enable=True` to the ServiceBusClient during creation. You can also [turn on additional `azure.servicebus` and `uamqp` level logs](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/servicebus/azure-servicebus#logging). ex.
```
import logging
import sys
logger = logging.getLogger('azure.servicebus')
logger.setLevel(logging.INFO)
uamqp_logger = logging.getLogger('uamqp')
uamqp_logger.setLevel(logging.INFO)
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)
uamqp_logger.addHandler(handler)

client = ServiceBusClient("NAMESPACE", credential, logging_enable=True)
```
