### ISSUE TITLE
conflicting dependency set across azure python packages

### ISSUE THREAD

**Issue by kapilt** [Azure/azure-sdk-for-python#2569]
Our ci started failing this morning due to conflicting dependencies caused azure client sdk python universe.

```
ContextualVersionConflict: (adal 0.6.0 (/drone/src/github.com/capitalone/cloud-custodian/.tox/py27/lib/python2.7/site-packages), Requirement.parse('adal~=0.5.0'), set(['msrestazure']))
```

fwiw, our declared dependency set is `"azure", "azure-cli-core", "adal"`

**Comment by kapilt** [comment]
removing the implied direct dependency from adal from our setup.py didn't resolve, so the sub dependency graph is still an issue, albeit only when mixing azure and azure-cli graphs. Explicitly pinning it in our setup.py did however resolve it.

**Comment by adamcunnington** [comment]
Why is this issue closed? What is the solution? I've ran into the same thing.

**Comment by adamcunnington** [comment]
Great, thanks.
