### ISSUE TITLE
AzureDLFileSystem mv() does not move file to destination, deletes file from source

### ISSUE THREAD

**Issue by nimishkumar** [Azure/azure-sdk-for-python#25718]
azure.datalake.store.core.AzureDLFileSystem class's mv() method removes the file from the source, but does not actually move the file to the destination. This effectively deletes the file entirely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a46e370-1db0-4259-a3e9-6baf23dce72a
* Version Independent ID: 286b6a96-189d-abaa-914a-edc3837fb1bb
* Content: [azure.datalake.store.core.AzureDLFileSystem class](https://docs.microsoft.com/en-us/python/api/azure-datalake-store/azure.datalake.store.core.AzureDLFileSystem?view=azure-python#azure-datalake-store-core-azuredlfilesystem-mv)
* Content Source: [docs-ref-autogen/azure-datalake-store/azure.datalake.store.core.AzureDLFileSystem.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-datalake-store/azure.datalake.store.core.AzureDLFileSystem.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by annatisch** [comment]
Thanks for reporting @nimishkumar!
Directing to the right team for investigation :)
