### ISSUE TITLE
Tracking SSO Investigation

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-python#25713]
`VisualStudioCodeCredential` will depend on a new authentication tool which replaces the Azure Account extension in Visual Studio Code. This tool is not yet built; more details to come.

**Comment by basnijholt** [comment]
Could you perhaps provide more details on this fix?

I found https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-visualstudiocodecredential-authentication-issues through an issue after trying to debug `VisualStudioCodeCredential` for about an hour, only to find out it doesn't work at the moment.

I believe using `VisualStudioCodeCredential` should emit a warning about it not working. No-one will be using an older version of the Azure Account extension (0.9.11 appears to work according to messages on GitHub).

ref: https://github.com/Azure/azure-sdk-for-python/issues/23249

**Comment by dgancho** [comment]
@xiangyan99 Is there any progress with this issue?
