### ISSUE TITLE
need to update api-version of security contacts api from 2017-08-01-preview to 2020-01-01-preview

### ISSUE THREAD

**Issue by Rama-Ayyagari** [Azure/azure-sdk-for-python#25771]
**Is your feature request related to a problem? Please describe.**

Need details of of person to send email notifications from Microsoft Defender for Cloud to persons with specific RBAC roles on the subscription.Also Defines whether to send email notifications about new security alerts

**Describe the solution you'd like**
Need following response from Microsoft.Security/securityContacts api.
```
{
  "value": [
    {
      "id": "/subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/securityContact/default",
      "name": "default",
      "type": "Microsoft.Security/securityContact",
      "properties": {
        "notificationsByRole": {
          "state": "On",
          "roles": [
            "Owner",
            "Admin"
          ]
        },
        "emails": "john@contoso.com;Jane@contoso.com",
        "phone": "(214)275-4038",
        "alertNotifications": {
          "state": "On",
          "minimalSeverity": "Low"
        }
      }
    }
  ]
}
```
But currently getting following response

```
{
      "properties": {
        "alertNotifications": "On",
        "alertsToAdmins": "On",
        "email": "",
        "phone": ""
      },
      "id": "/subscriptions/<>/providers/Microsoft.Security/securityContacts/Primary",
      "name": "Primary",
      "type": "Microsoft.Security/securityContacts",
      "etag": "\"5d02caba-0000-0d00-0000-62fe706f0000\"",
      "location": "West Europe"
    }
```
**Describe alternatives you've considered**

**Additional context**

**Comment by annatisch** [comment]
Thanks for reporting @Rama-Ayyagari!
I'm directing to the right team to investigate for you ASAP :)

**Comment by msyyc** [comment]
Hi @Rama-Ayyagari Do you mean that the response from service changes compared with api-version `2017-08-01-preview` and `2020-01-01-preview`? If that, I advise to open an issue in https://github.com/Azure/azure-rest-api-specs/issues since SDK is generated with [swagger definition](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/security/resource-manager)
