### ISSUE TITLE
Remove hard coded api versions

### ISSUE THREAD

**Issue by squirrelsc** [Azure/azure-sdk-for-python#25779]
I tried to use the quota API. But the API version is hard coded, and the preview version is gone. So the call won't be successful. Can you update to a workable API version, and remove the hard coded version?

https://github.com/Azure/azure-sdk-for-python/blob/d7c30a90ca19083f626c54680582bf02a549f8ca/sdk/quota/azure-mgmt-quota/azure/mgmt/quota/operations/_quota_operations.py#L83

**Comment by SHSongs** [comment]
I fixed issue. Could you review [this PR?](https://github.com/Azure/azure-sdk-for-python/pull/25790)

**Comment by annatisch** [comment]
Thanks so much for reporting and PR contribution!
Unfortunately this SDK is auto-generated, and probably needs to be corrected using a new code generation.
@msyyc - could you please investigate this issue and the referenced fix PR above to determine the best next steps?

**Comment by msyyc** [comment]
Hi @squirrelsc SDK is generated automatically with [swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/quota/resource-manager#basic-information). If you find that the api version doesn't work, please make an issue in https://github.com/Azure/azure-rest-api-specs/issues. After service team update the api version, we can publish a new sdk version to fix the problem.
