### ISSUE TITLE
Create a new guest user (Invite an external user into Azure AD)

### ISSUE THREAD

**Issue by realrill** [Azure/azure-sdk-for-python#2577]
Hi all,

I have some trouble with the SDK/documentation. Maybe it is just my fault so please do not hate me.

I have been working on a project where I have two ongoing issue.

1. Create a new guest user (Invite an external user into Azure AD)
2. Assign the invited user into a subscription as reader via the user object_id(or somehow)

I found the [PowerShell alternative](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsinvitation?view=azureadps-2.0) for the 1. but nothing for 2.

Is there any exists Python SDK solution for both issue or I have to use the native RestAPI?

**Comment by lmazuel** [comment]
Hi @realrill !
Sorry for the late answer. What you want do is likely to be done with `azure-mgmt-authorization`. I don't have a specific sample, but this part of this might help you:
https://github.com/Azure-Samples/compute-python-msi-vm#role-assignement-to-the-msi-credentials

```python
# Get "Contributor" built-in role as a RoleDefinition object
role_name = 'Contributor'
roles = list(authorization_client.role_definitions.list(
    resource_group.id,
    filter="roleName eq '{}'".format(role_name)
))
assert len(roles) == 1
contributor_role = roles[0]

# Add RG scope to the MSI token
for msi_identity in msi_accounts_to_assign:

    role_assignment = authorization_client.role_assignments.create(
        resource_group.id,
        uuid.uuid4(), # Role assignment random name
        {
            'role_definition_id': contributor_role.id,
            'principal_id': user_object_id
        }
    )
```

**Comment by realrill** [comment]
Hi @lmazuel,

Thank you for your response.

I just quickly overviewed the doc of `azure-mgmt-authorization` and looks like this is what I looked for the user assignment to subscription.
I guess I focused on the `Active Directory` and `Resources` documentation and did not realise I was on the wrong page.

Fortunately I made a workaround with native REST Api but I would prefer use SDK.

I will test and implement it while I am waiting for the 1. resolution.

Thank you for your help!

**Comment by lmazuel** [comment]
@yugangw-msft what would you do for:
> Create a new guest user (Invite an external user into Azure AD)

**Comment by yugangw-msft** [comment]
This is not possible till we are able to integrate AAD team's swagger into SDK's spec repository. There is an ownership discussion going on right now, and I hope we can resolve that and get this scenario covered soon.

**Comment by boschand** [comment]
Is there an update on this feature request?
I also need to create guest accounts with a python script based on some events from a webhook.

**Comment by haidaraM** [comment]
Just want to know that if there is a plan to support this feature in the SDK ?

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
