### ISSUE TITLE
[Docs][Load Testing] add link in MS docs

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#25776]
add link in https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python.

https://github.com/MicrosoftDocs/azure-docs-sdk-python/tree/main/preview/docs-ref-autogen/azure-developer-loadtesting

**Comment by msyyc** [comment]
After https://github.com/Azure/azure-sdk/pull/4717 merged, The doc link shall be updated: https://github.com/MicrosoftDocs/azure-docs-sdk-python/tree/main/docs-ref-services/preview

**Comment by ninallam** [comment]
@msyyc The pull request https://github.com/Azure/azure-sdk/pull/4717 was merged 3 days ago. How long would it take to update the reference docs at https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python?

**Comment by msyyc** [comment]
I will confirm that in e-mail

**Comment by msyyc** [comment]
Hi @ninallam since `load testing` is still in preview, you can see the doc link in https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python-preview
