### ISSUE TITLE
Synchronous messaging between .net WebRole and Python

### ISSUE THREAD

**Issue by andrewkittredge** [Azure/azure-sdk-for-python#2579]
Our site is served by a .net WebRole.  I want to process data from the user synchronously in a Python process.  The Python process has to be able to use extension packages, scikit-learn specifically, so I think Azure lambda is out.

I am considering an architecture whereby the .net WebRole process communicates with a Python WorkerRole via an Azure Relay Hybrid Connection.   Hybrid Connections do not seem documented in Python.

Is my architecture optimal?

**Comment by lmazuel** [comment]
Hi @andrewkittredge 
I'm not an expert in Azure architecture, so I can't tell right now, and you should ask you question on MSDN to get more input.
However, when you say "Azure lambda is out", assuming you're talking about Azure Functions, WebApp for Containers might do the work for you:
https://azure.microsoft.com/en-us/services/app-service/containers/

Thanks,
