### ISSUE TITLE
[Key Vault] Verify pagination tests cover more than one page

### ISSUE THREAD

**Issue by timovv** [Azure/azure-sdk-for-python#25812]
Raising this issue following up from last week's team meeting.

As part of this month's release cycle, I released a migration of the Key Vault packages to JavaScript's Core v2 HTTP pipeline implementation. This change required some changes to the pagination methods each of the SDKs. One method in keyvault-secrets wasn't migrated properly, leading to a regression where the pagination would fail, but only from the second page onwards (the first page was fetched just fine).

This regression wasn't caught because, as it turns out, our pagination tests didn't actually paginate: the data returned from the service in the test wasn't enough to trigger pagination by default, and no maximum page size was set. This meant that fetching the next page wasn't covered in our tests and the issue slipped through.

I've since released a hotfix for JS fixing the issue and the tests (setting a maximum page size of 1 to force pagination), but we should ensure the other languages don't have this gap in test coverage.

Things to check:
* Make sure that the pagination tests for your language cover the scenario when multiple pages are returned
* If the scenario isn't covered, update the tests so that pagination is being tested properly (by e.g. setting a maximum page size).

See the [issue] and [resulting PR] from JavaScript for more background and the fix.

[issue]: https://github.com/Azure/azure-sdk-for-js/issues/22890
[resulting pr]: https://github.com/Azure/azure-sdk-for-js/pull/22898

**Comment by mccoyp** [comment]
I've just realized that this could have been closed a while ago; for context, KV tests usually verify multi-page behavior by making the max page size smaller than the number of items we want to list. For example: https://github.com/Azure/azure-sdk-for-python/blob/ec6ed05d218f234123f765a6c00e2382f684c330/sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_client.py#L159
