### ISSUE TITLE
GA OpenTelemetry tracing plugin

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#25838]
We have a partner ask to GA OTel tracing plugins across all languages in [Zn], this is an uber-issue to track python work in this space. 
Here're the sub-tasks:

- [ ] https://github.com/Azure/azure-sdk-for-python/issues/36779

- Cleanups and breaking changes
  - [ ] [P2] Set az.namespace, client library name and version on tracer instrumentation scope
  - [ ] [P0] https://github.com/Azure/azure-sdk-for-python/issues/9256
  - [ ] [P1] https://github.com/Azure/azure-sdk-for-python/issues/9079

- [ ]  Testing
  - [P2] User study if we can find someone internal
  - [P1] Integration tests for AMQP SDKs, retries, attributes
  - [P1] Perf testing: e.g. run storage perf tests with tracing enabled.
  - [P3] Sample will latest and greatest OTel and AppInsights SDK/AzMon exporter including AMQP and HTTP SDK. - Here's the existing draft https://github.com/lmolkova/azuresdk_tracing_demo/tree/python

- [ ] Misc
  - [P0] Update docs
  - [P2] Add tracing to common TSG

**Comment by lzchen** [comment]
Can `Set client library name and version on tracer instrumentation scope` be scoped into the GA milestone as a must have? It would be great we knew on the span level (populated by tracer instrumentation scope) which azure-sdk service was responsible for generating it. @pvaneck would this be a lot of work?
