### ISSUE TITLE
Filter List Users

### ISSUE THREAD

**Issue by guptasakshi01** [Azure/azure-sdk-for-python#2584]
Python Module Used:- azure-graphrbac

How to use filter option while listing O365 users using following method:-
list(filter=None, custom_headers=None, raw=False, **operation_config) ?

We are not able to filter using this:- 
client.users.list(filter=<display_name>)

**Comment by annatisch** [comment]
Hi @guptasakshi01 - could you try using syntax along the lines of:
`filter='startswith(displayName,\'some_name\')'`

**Comment by lmazuel** [comment]
As @annatisch says, filter will use the RestAPI syntax as a string here:
https://msdn.microsoft.com/Library/Azure/Ad/Graph/api/users-operations#GetUsers
https://msdn.microsoft.com/Library/Azure/Ad/Graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options#filter

Thanks,
