### ISSUE TITLE
Classifier missing Python3.9

### ISSUE THREAD

**Issue by sravantiaketi1** [Azure/azure-sdk-for-python#25857]
- **Package Name**: azure-mgmt-resourcegraph
- **Package Version**: 8.0.0
- **Operating System**: linux
- **Python Version**: 3.9

**Describe the bug**
A clear and concise description of what the bug is. Classifier for this library is missing Python3.9 hence getting No module found error.

**To Reproduce**
1. https://pypi.org/project/azure-mgmt-resourcegraph/
 check Programming Language section it does not have Python 3.9

**Expected behavior**
Is it deprecated? If yes what is alternative package?

**Screenshots**
![Screenshot from 2022-08-25 10-47-43](https://user-images.githubusercontent.com/103495989/186580868-b7992957-f931-4f77-8a2c-600b6721b527.png)

**Additional context**

**Comment by sravantiaketi1** [comment]
can you please respond? Its very urgent

**Comment by catalinaperalta** [comment]
Thanks for reaching out @sravantiaketi1! @msyyc can you please take a look ASAP?

**Comment by msyyc** [comment]
We will release a new version for azure-mgmt-resourcegraph the doc shall be updated with clarify for all supported python version including py3.9

**Comment by Wzb123456789** [comment]
Hi @sravantiaketi1
We have released new package about `azure-mgmt-resourcegraph`.
https://pypi.org/project/azure-mgmt-resourcegraph/8.1.0b2/

Please try the new azure-mgmt-resourcegraph to solve your problem.

Hope it can help you.
