### ISSUE TITLE
Mounting the dataset causes error

### ISSUE THREAD

**Issue by jeeva1711** [Azure/azure-sdk-for-python#25860]
Is there a right way to mount the dataset in jupyter notebook of ML Studio ?
Can a dataset point to two different datastore ? 
p.s : I have created dataset pointing to two different datastores and registered it as well.
But while mounting the dataset, it shows some error.
![err1](https://user-images.githubusercontent.com/72345296/186587884-36bce118-345d-4b5a-a18c-7cc497232813.JPG)
![err2](https://user-images.githubusercontent.com/72345296/186587910-d5a62499-e974-4f75-bfe2-6460cbf3f73c.JPG)
![err4](https://user-images.githubusercontent.com/72345296/186587927-adfa8f53-ff16-4bdc-b7bc-29b2e217f26b.JPG)

**Comment by catalinaperalta** [comment]
Thanks for reaching out! Adding @azureml-github to help investigate.

**Comment by anliakho2** [comment]
@jeeva1711 looks like the mount point directory you are trying to mount to is on SMB2 file system and you can't mount on that file system. I would suggest either changing your mount_point argument to some folder on ordinary linux file system or remove the argument alltogether so that the system creates mount point automatically (in the tmp folder), you can then query mount_context.mount_point property to discover the path to be used in later

**Comment by jeeva1711** [comment]
@anliakho2 I have removed the argument like you said, used the method mentioned in documentation page and it worked fine.
But still there is this warning and I don't know what to do with that. I have added the image below for your reference.
![err2](https://user-images.githubusercontent.com/72345296/187370948-2920ee98-8031-411e-96f9-55b8a1cdd437.JPG)

**Comment by anliakho2** [comment]
> @anliakho2 I have removed the argument like you said, used the method mentioned in documentation page and it worked fine. But still there is this warning and I don't know what to do with that. I have added the image below for your reference. ![err2](https://user-images.githubusercontent.com/72345296/187370948-2920ee98-8031-411e-96f9-55b8a1cdd437.JPG)

This warning is there for a reason, given you want to mount multiple paths or multiple datastores to the same location this dataset couldn't be mounted as a volume, which a supported scenario but has performance implications as file system requests to mount couldn't be just mapped to storage service requests and instead need to go trough execution engine to figure things out.
If your mount works fine for your use case and you get an acceptable performance - you could just ignore the warning, however if you want higher perf you might want to split the dataset into two that could be volume mounted individually, this is really up to you

**Comment by jeeva1711** [comment]
> > @anliakho2 I have removed the argument like you said, used the method mentioned in documentation page and it worked fine. But still there is this warning and I don't know what to do with that. I have added the image below for your reference. ![err2](https://user-images.githubusercontent.com/72345296/187370948-2920ee98-8031-411e-96f9-55b8a1cdd437.JPG)
> 
> This warning is there for a reason, given you want to mount multiple paths or multiple datastores to the same location this dataset couldn't be mounted as a volume, which a supported scenario but has performance implications as file system requests to mount couldn't be just mapped to storage service requests and instead need to go trough execution engine to figure things out. If your mount works fine for your use case and you get an acceptable performance - you could just ignore the warning, however if you want higher perf you might want to split the dataset into two that could be volume mounted individually, this is really up to you

Thanks a lot @anliakho2 . It really helped.
