### ISSUE TITLE
[cognitive-language] Modernize strings throughout code

### ISSUE THREAD

**Issue by wonhyeongseo** [Azure/azure-sdk-for-python#25867]
**Is your feature request related to a problem? Please describe.**
Python 2 used unicode strings, but Python 3 can handle unicode by default.
Format methods can be replaced with f-strings.

**Describe the solution you'd like**
We should remove unicode strings from the code, and replace format methods with f-strings if possible.

- [x] Question & Answer Maker
- [x] Conversations

**Additional context**
@kristapratico https://github.com/Azure/azure-sdk-for-python/issues/22057
![image](https://user-images.githubusercontent.com/29195190/186681975-11f5738d-4cf2-46e3-97b2-1ebbe413308d.png)

**Comment by kristapratico** [comment]
Thanks for opening this issue @wonhyeongseo! I understand that you want to work on this so I'm assigning it to you. 😃
