### ISSUE TITLE
Authentication not working with Service Principle for azure-mgmt-serialconsole API

### ISSUE THREAD

**Issue by somil55** [Azure/azure-sdk-for-python#25911]
- **Package Name**: azure-mgmt-serialconsole
- **Package Version**: 1.0.0
- **Operating System**: Windows
- **Python Version**: 3.8

**Describe the bug**
I am unable to determine the correct SP scope and permissions to create connection string for accessing the serial console websocket. The code works fine if I use scope as "" with `DefaultAzureCredential` credential and login using `az login`. However, if I use a service principal credential, it fails. The documentation fails to mention the permissions and scope that SP need for accessing the serial console of a VM using this API. Can someone please provide the necessary information?

I use the following snippet to get connection string:
```
connection = self._serial_port_operations.connect(
            resource_group_name=self._resource_group_name,
            resource_provider_namespace=self.RESOURCE_PROVIDER_NAMESPACE,
            parent_resource_type=self.PARENT_RESOURCE_TYPE,
            parent_resource=self._vm_name,
            serial_port=self._serial_port.name,
)
token = platform.credential.get_token(scope="").token
serial_port_connection_str = (
          f"{connection.connection_string}?authorization={token}"
      )
```
**Expected behavior**
The serial console should be accessible with service principal based authentication.

**Comment by BigCat20196** [comment]
Hi @somil55, thanks for your feedback.

`DefaultAzureCredential ` is verified based on the `AZURE_TENANT_ID`, `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` in the environment variable, while the service principal is verified by another certificate. `azure-mgmt-service` is used through DefaultAzureCredential, which is our recommended use.

Maybe [Azure-cli-extensions](https://github.com/Azure/azure-cli-extensions/tree/main/src/serial-console) can do it by service principal.

fyi: https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli
