### ISSUE TITLE
[Question] [Azure ML] Retrieving secret in Azure ML SDK v2

### ISSUE THREAD

**Issue by tomasvanpottelbergh** [Azure/azure-sdk-for-python#25925]
In the Azure ML Python SDK v1 a secret can be retrieved from the Azure Key Vault associated to the workspace using the following snippet:
```
from azureml.core import Run

secret = Run.get_context().get_secret("SECRET_NAME")
```
(see https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-secrets-in-runs).

However, I can't seem to find an equivalent for this in v2 of the SDK. Will this still be added or is there another recommended solution for doing this?

**Comment by iscai-msft** [comment]
@azureml-github

**Comment by luigiw** [comment]
@tomasvanpottelbergh, thx for your question. May I ask your use case for the secret? What do you use it for during training runtime?

A bit background of v2 SDK. v2 SDK is designed to be more of a control plane SDK than a runtime SDK, meaning you use the v2 SDK to submit jobs and manage ML assets, but don't need to include it in your training/inferencing environment. For runtime use cases, we recommend using MLflow.

**Comment by tomasvanpottelbergh** [comment]
The use case would be to get the credentials for a Service Principal which is used to access some data sources. As far as I can see, this is the only way to make a certain resource available to the whole Azure ML workspace, regardless of the compute instance or cluster the job is run. Is this correct or is there a better way without having to use the v1 SDK?

**Comment by luigiw** [comment]
@tomasvanpottelbergh what exact resources do you need to access during training time (if you can share)? This article may be helpful to you. https://learn.microsoft.com/en-us/azure/machine-learning/how-to-identity-based-service-authentication?tabs=cli

**Comment by tomasvanpottelbergh** [comment]
@luigiw we are querying Log Analytics during training time. Thanks for the article, but I don't see any way to provide access to certain resources independent of on which compute instance or cluster the training is run? I assume this is a common requirement, so it would be good to have a solution for it if accessing the key vault using the Azure ML SDK is not recommended anymore.

**Comment by luigiw** [comment]
@tomasvanpottelbergh you can use the workspace level MSI and grant access to that MSI. I'll ask around to see if there're any examples.

**Comment by dunalduck0** [comment]
Is there a solution to this issue? I am facing the same and don't know how to resolve.

**Comment by ion-elgreco** [comment]
SDK v2 seems to miss many features, including grabbing the default keyvault to get secrets.. Quite annoying.

**Comment by dclaz** [comment]
> SDK v2 seems to miss many features, including grabbing the default keyvault to get secrets.. Quite annoying.

We're trying to migrate from V1 to V2 and having issues because of things exactly like this.

**Comment by obiii** [comment]
Hi, we are having the same issue. Is there any update on this?

**Comment by adrienbiarnes** [comment]
I need access to the keyvault secrets in order to retrieve the password to authenticate to my redis instance. I am in the process of migrating my pipelines from Google Vertex AI to Azure. This definitely makes me think it was a bad decision...

**Comment by dunalduck0** [comment]
@azureml-github, @Azure/azure-ml-sdk, is there any progress on this issue? We need support for ML assets management at runtime.
