### ISSUE TITLE
list_topics does not list partitioned topics

### ISSUE THREAD

**Issue by hrncek** [Azure/azure-sdk-for-python#2593]
from azure.servicebus import ServiceBusService, Message

bus = ServiceBusService(......)

topics = bus.list_topics()

I can see topics which have partitioned false, but not the one which have partitioned true

**Comment by annatisch** [comment]
Thanks @hrncek - we are currently building a new AMQP-based service bus Python SDK, so we are not actively working on this legacy SDK.
However I will be sure to test this scenario on the new SDK, and when the new SDK goes into preview I will update this issue thread.

**Comment by annatisch** [comment]
It looks like this is probably the result of the SDK pointing to an old API version.
The new SDK will target the latest API version by default which will likely resolve this.

**Comment by annatisch** [comment]
This has been added as issue #4247 to update the control plane API version to support getting partitioned queues.
It will be updated in the next preview release of the Service Bus SDK.

**Comment by yunhaoling** [comment]
Hi @hrncek , sorry for not getting to you sooner.

Could you please try installing azure-servicebus v0.50 to see if the problem get resolved on your side? It should be able to list all the topics.

in v0.50, you can list topics by this:
```
from azure.servicebus import ServiceBusClient
conn_str = "<your connection string>"

sb_client = ServiceBusClient.from_connection_string(CONN_STRING)
topics = sb_client .list_topics()
```

Looking forward to your feedback.

**Comment by yunhaoling** [comment]
Hey @hrncek , I'm closing the issue assuming that problem has been addressed.

Feel free to re-open if the problem still exists.
