### ISSUE TITLE
Body Serialization silently drops invalid parameters

### ISSUE THREAD

**Issue by anujissarMS** [Azure/azure-sdk-for-python#25946]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
The autorest serializer for request body drops the invalid parameter silently before sending out reqeusts. The serializer raises an exception but it consumes that itself and continues with the serialization. This causes unreliable behavior, for example in Rooms service if an invalid datetime is passed in valid_from/valid_until parameters, the serializer drops the invalid datetime and the request is sent out without parameter. The service creates the meeting with default value for the missing parameter.

**To Reproduce**
1. Send in invalid datetime in valid_from/*until to create_room in Rooms sdk

**Expected behavior**
The raised exception is propagated to Contoso

**Screenshots**

**Additional context**

**Comment by iscai-msft** [comment]
@anujissarMS can you point me to the generated code for the SDK? I'm trying to determine which serialization code is dropping the datetime. Thanks!

**Comment by anujissarMS** [comment]
I don't think its just limited to datetime. It would be same for any other serialization errors of other types.
[This line](https://github.com/Azure/azure-sdk-for-python/blob/f12d7eac3d6f60b49a4b9b4876e53f59103a074b/sdk/communication/azure-communication-rooms/azure/communication/rooms/_generated/_serialization.py#L598) Is where the exception would be raised.
As you can see its inside a try block and except block [here](https://github.com/Azure/azure-sdk-for-python/blob/f12d7eac3d6f60b49a4b9b4876e53f59103a074b/sdk/communication/azure-communication-rooms/azure/communication/rooms/_generated/_serialization.py#L642) will just catch and continue to the next attribute

**Comment by iscai-msft** [comment]
@anujissarMS this is our planned course of action: https://github.com/Azure/autorest.python/issues/1413
