### ISSUE TITLE
Uncatchable error message printed when downloading blob that is an HN directory

### ISSUE THREAD

**Issue by JJ11teen** [Azure/azure-sdk-for-python#25954]
- **Package Name**: azure-storage-blob
- **Package Version**: v12.13.1 (latest)
- **Operating System**: Don't believe OS specific
- **Python Version**: 3.9 but don't believe python version specific

**Describe the bug**
When calling `download_blob().read_all()` on a blob that is actually a directory with hierarchical namespace enabled, the following error message is printed out:
```
Ran into a deserialization error. Ignoring since this is failsafe deserialization
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.9/site-packages/msrest/serialization.py", line 1509, in failsafe_deserialize
    return self(target_obj, data, content_type=content_type)
  File "/home/vscode/.local/lib/python3.9/site-packages/msrest/serialization.py", line 1375, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/home/vscode/.local/lib/python3.9/site-packages/msrest/serialization.py", line 1543, in _unpack_content
    raise ValueError("This pipeline didn't have the RawDeserializer policy; can't deserialize")
ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize
```
This error message cannot be caught, or silenced, and is very non-descriptive of the issue that is happening.

**To Reproduce**
1. Have a blob container within a storage account that has hierarchical namespace enabled
2. Have a blob within that container that is prefixed with at least one subdirectory (eg `dir/blob.csv`)
3. Call `.download_blob()` and `.readall()` on the subdirectory, ie if you have a blob at `dir/blob.csv`, attempt to download and read just `dir`. Both the `container_client.download_blob()` method and the `blob_client.download_blob()` method are impacted by this. Note that `.readall()` must also be called, and actually succeeds, but the error message is printed and unstoppable.

**Expected behavior**
A catchable error/exception, and preferably a more descriptive message. Or, no error message at all and the existing implementation of empty bytes are returned.

**Additional context**
Note that the actual `.readall()` method succeeds regardless, and returns empty bytes. It is just that the error message cannot be silenced.

**Comment by jalauzon-msft** [comment]
Hi @JJ11teen Lucas, thanks for bringing this to our attention. We'll investigate and get back to you ASAP.

@xiangyan99 or @iscai-msft is this something either of you have seen before or know anything about?

**Comment by iscai-msft** [comment]
@JJ11teen the reason it can't be caught is it's not an actual thrown error. We do run into this error, but we catch it internally and only log the issue you ran into. That being said it's not very clear, will continue offline discussions and get back to you. Thanks!

**Comment by JJ11teen** [comment]
Thanks both. Let me know if you need any more details.

Yes confirming that is my understanding as well @iscai-msft. The bug is that an error message is logged and cannot be caught or silenced. I am writing a library that will be consumed by others, and having an error message printed out even when things work is confusing for everyone 😄. Expected behaviour is that either an error can be caught or no error message is logged.

**Comment by iscai-msft** [comment]
@jalauzon-msft I just released autorest version `6.1.4`. This error will not be logged at the debug level, so only users who are doing debug level of logging will see this error. This should clear up the main issue where end users are seeing confusing logs. There is a separate issue about how we should actually deserialize the streamed error response, see here https://github.com/Azure/autorest.python/issues/1420

**Comment by jalauzon-msft** [comment]
Thanks @iscai-msft! I will work on re-generating the Storage packages with the latest autorest to address the issue before our next GA release.

**Comment by JJ11teen** [comment]
Thanks for the fast work everyone! 🚀
