### ISSUE TITLE
azure-eventhub python library bundle installation

### ISSUE THREAD

**Issue by arunansu** [Azure/azure-sdk-for-python#25959]
Customer is trying to install azure-eventhub library in their onprem VM to test eventhub. But their network setup does not allow downloading libraries from internet. They can however download the whl file in their personal machine and FTP to their work machine. But even that does not work, because azure-eventhub has dependency on azure-core that requires download from internet.
 
Is it possible to get a whl file to install azure-eventhub python library with all its dependencies bundled in one file?

**Comment by kashifkhan** [comment]
Hi @arunansu , Ill ask a few people within my team and see what options are available to help you out and get back to you asap.

**Comment by kashifkhan** [comment]
@arunansu the best way to create an installer would be to use the pip download option. You would have to make sure that the machine downloading the dependencies has the same OS and python version as the VM where it will be installed (  if not, then at least know the OS and Python version)

Here are the steps to go about it:-

- Create a folder for example `eventhub-deps`
- Then run the following command to download the dependencies in the folder created above: `pip download azure-eventhub -d "eventhub-deps" --python-version "3.7" --platform "Windows"`. In this step python version and platform should be the same as the VM where it will be installed.
- Copy the whl and the dependencies folder on to the VM and then run `pip install azure-eventhub.whl -f ./ --no-index --no-deps` inside the `eventhub-deps` folder

This should now install eventhub sdk on to the VM and resolve all dependencies locally :)

Please let me know if you have any further questions.
