### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by birdman-65** [Azure/azure-sdk-for-python#25952]
[Enter feedback here]

The Explorer management API link is bad.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5dd478f-5bb1-3b90-27f3-d1b04db40e3f
* Version Independent ID: 60658b32-abc1-3787-ec6d-24ef3bfade4c
* Content: [Azure Data Factory SDK for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/data-factory?view=azure-python)
* Content Source: [docs-ref-services/latest/data-factory.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/data-factory.md)
* Service: **datafactory**
* GitHub Login: @hvermis
* Microsoft Alias: **hvermis**

**Comment by msyyc** [comment]
I can open the link : [Azure Data Factory SDK for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/data-factory?view=azure-python). Could you check it again? @birdman-65

**Comment by msyyc** [comment]
Hi @danieljurek It seems https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1758 doesn't resolve the issue. Is the fix not right?

**Comment by birdman-65** [comment]
I concur.  I still receive a 404 when I click on the Explore the management APIs link.

-Eric

On Jun 30, 2023, at 4:10 AM, Yuchao Yan ***@***.***> wrote:

﻿

Hi @danieljurek<https://github.com/danieljurek> It seems MicrosoftDocs/azure-docs-sdk-python#1758<https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1758> doesn't resolve the issue. Is the fix not right?

**Comment by birdman-65** [comment]
I tried it again later and it did.  I wonder if the fix hasn’t propagated to all the site caches ( hey if that is such a thing in this case)
I had cleared my cache so I know it wasn’t local..

-Eric

On Jun 30, 2023, at 7:36 PM, Eric Bird ***@***.***> wrote:

﻿ I concur.  I still receive a 404 when I click on the Explore the management APIs link.

-Eric

On Jun 30, 2023, at 4:10 AM, Yuchao Yan ***@***.***> wrote:

﻿

Hi @danieljurek<https://github.com/danieljurek> It seems MicrosoftDocs/azure-docs-sdk-python#1758<https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1758> doesn't resolve the issue. Is the fix not right?

**Comment by danieljurek** [comment]
Docs are scheduled to go live Wednesday, Redmond time.

**Comment by danieljurek** [comment]
Closing. Docs are live and the updated link works. Thanks for your help here @birdman-65!
