### ISSUE TITLE
How to use nextLink property in Azure Python SDK while listing all VMs

### ISSUE THREAD

**Issue by sauadwaya** [Azure/azure-sdk-for-python#25974]
I am trying to list all virtual machines in a subscription in Azure using the code given here:

     from azure.mgmt.compute import ComputeManagementClient
     from azure.identity import ClientSecretCredential
        
     credentials = ClientSecretCredential(
        client_id='',
        client_secret='',
        tenant_id=''
     )
        
     subID= ''
        
     computer_client = ComputeManagementClient(credentials,subID)
     vms = computer_client.virtual_machines.list_all()
        
     for vm in vms:
        print( vm.name )

This works fine. It is listing all the vms for the first page. However, how do I get the next_link property and consume the next page of VMs? What would be the syntax?
In the docs: https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2019_07_01.models.virtualmachinelistresult?view=azure-python

it says:

> next_link
>     str 
> 
> Required
> 
> The URI to fetch the next page of VMs. Call ListNext() with this URI
> to fetch the next page of Virtual Machines.

I am just wondering what the syntax would look like to consume the next_link property and make the ListNext() call?

**Comment by sauadwaya** [comment]
I have seen documentation in Azure SDK for Java where pagination is taken care of internally. Is it the same for python? (i.e the above code will take care of pagination calls itself and return me the full list?)

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share the doc for the Java SDKs?

We should have similar (if not same) behavior between Python and Java. Just want to double check.

**Comment by sauadwaya** [comment]
> 

@xiangyan99 Yep sure here is the link:

https://docs.microsoft.com/en-us/azure/developer/java/sdk/pagination

**Comment by xiangyan99** [comment]
Thank you.

I see list_all returns 
Iterable["_models.VirtualMachineListResult"]

for vm in vms:
    print( vm.name )
should call `next_page` automatically for you.
