### ISSUE TITLE
Breaking change between azure.mgmt.subscription 3.0.0 and 3.1.0 Missing api_version 

### ISSUE THREAD

**Issue by bclements** [Azure/azure-sdk-for-python#25994]
- **Package Name**: azure.mgmt.subscription
- **Package Version**:  3.1.0
- **Operating System**: Ubuntu 22.04
- **Python Version**:  3.9

**Describe the bug**
When calling any subscription operation, specifically the list operation, exception is raised about missing api_version

**To Reproduce**
1. pip3 install latest azure.mgmt.subscription version. 
2. Run the following code
`
from azure.identity import ClientSecretCredential
from azure.mgmt.subscription import SubscriptionClient
import pprint

credentials = ClientSecretCredential()

subclient = SubscriptionClient(credentials)
subscriptions = subclient.subscriptions.list()
pprint.pprint(subscriptions)
`

**Expected behavior**
Should output the list of subscriptions.  This works fine in the previous version, 3.0.0 but not in 3.1.0

**Screenshots**
Using 3.1.0, this is exception/error.
![image](https://user-images.githubusercontent.com/3810269/187923393-42b6305d-9137-4a1e-9e93-cb488661c51d.png)

**Additional context**
Looking at the diff between operations/_subscriptions_operations.py 3.0.0 and 3.1.0, the hard coded value(api_version = "2016-06-01") in the build_list_locations_request function was replaced with this api_version = kwargs.pop("api_version", _params.pop("api-version", "2016-06-01")).

**Comment by msyyc** [comment]
@bclements please try new version: https://pypi.org/project/azure-mgmt-subscription/3.1.1/
