### ISSUE TITLE
[Python] Lock always expired when client's clock is not synchronized

### ISSUE THREAD

**Issue by maximeLeurent** [Azure/azure-sdk-for-python#25996]
Hello,

I face a problem on one of my device that use a service bus with session in [pattern Request/Response](https://blog.jeremylandon.com/fr/2020/03/22/azure-pattern-request-response-avec-azure-service-bus/). My other devices using the same code and the same Service bus didn't have any problems.
Here the code : 

```
from azure.servicebus import  ServiceBusMessage
from azure.servicebus.aio import ServiceBusClient, AutoLockRenewer
async def wait_reply(servicebus_client, message_id, session_id):
      auto_lock_renewer = AutoLockRenewer()
      receiver = servicebus_client.get_queue_receiver(queue_name=".....", session_id = session_id)
  
      async with receiver:
          auto_lock_renewer.register(receiver, receiver.session)
          logging.debug(f'Wait result message with id {message_id}')
          async for received in receiver:
              await receiver.complete_message(received)
              body = json.loads(str(received))
              return body
```
```
async def _wrap_az_func_request( queue_name, request, application_properties, session_id):
    """Same as wrap_az_func_request without timeout protection."""

    sent_message = ServiceBusMessage(
        utils.json_dumps(
            {"body": request,
            "reply_to_session_id":session_id}),
        application_properties=application_properties,
        reply_to_session_id = session_id) #Not work with property, had it in message
    conn_str = "....."
    servicebus_client = ServiceBusClient.from_connection_string(conn_str=conn_str)
    async with servicebus_client:
        #======== Sending Request
        sender =  servicebus_client.get_queue_sender(queue_name=queue_name)
        async with sender:
            logging.debug(f"Message sent with id {sent_message.message_id}. reply on session {session_id}")
            await sender.send_messages(sent_message)

        #======== Waiting for answer
        body = await wait_reply(servicebus_client, sent_message.message_id, session_id)
```
On this device, I always got a `SessionLockLostError` immediately after I wait for the answer message. (at `async for received in receiver:`)

I realized that this device's clock was not well synchronized, it was 3 minutes in advance (clock is 00h03m when universal time is 00h00).

For me the issue reside in the expired time of the Lock is given by ServiceBus server and it's is compare to client clock in `_lock_expired`

in ServiceBusSession.renew_lock()
```
class ServiceBusSession(BaseSession):
       async def renew_lock(self, **kwargs: Any) -> datetime.datetime:
             self._receiver._check_live()  # pylint: disable=protected-access
           [...]
             expiry = await self._receiver._mgmt_request_response_with_retry(  # pylint: disable=protected-access
                  REQUEST_RESPONSE_RENEW_SESSION_LOCK_OPERATION,
                  {MGMT_REQUEST_SESSION_ID: self._session_id},
                  mgmt_handlers.session_lock_renew_op,
                  timeout=timeout,
              )
              expiry_timestamp = expiry[MGMT_RESPONSE_RECEIVER_EXPIRATION] / 1000.0
              self._locked_until_utc = utc_from_timestamp(
                  expiry_timestamp
              )  # ty

```
In BaseSession
```
class BaseSession(object):
    @property
    def _lock_expired(self):
        return bool(self._locked_until_utc and self._locked_until_utc <= utc_now()) #Here _locker_until_utc from server clock is compared to client clock.
```

The `AutoLockRenewer` was not working as the function `renew_lock ` call `_check_live` 

I don't know if the lib is design to fit on device that are not synchronized with universal time but a solution could be :
the server provide a offset and `_locked_until_utc` may be calculate as  `_locked_until_utc = utc_now + offset` 
This solution would create problem in case of latency. So it not the ultimate solution. May be utc_now could be took before the request

For now I increased Lock duration to 5 minutes and i will correct my NTP problem.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment]
Apologies for the extremely late reply @maximeLeurent .

As you have described time skew is a very difficult problem. In the scenario above things can get really complicated if the clock continues to drift (5 mins today, 7 mins tomorrow etc), so it would need constant offset correction. The simplest fix would be to sync to NTP and figure out some of the issues causing skew, as the other machines are able to keep time properly. 

Lock renewal is especially difficult to pad as the window is very small (sometimes 30 seconds). The best way to work around this problem where some clock skew is expected is to set a longer lock duration and then renew the locks early.
