### ISSUE TITLE
Support 200 status code for success response

### ISSUE THREAD

**Issue by KeerthiYandaOS** [Azure/azure-sdk-for-python#25998]
**Is your feature request related to a problem? Please describe.**
In BlobOperations class, only the [202 status code is considered a success response](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/aio/operations/_blob_operations.py#L684) but it is possible that some endpoints return 200 or 2xx status codes as a success status as well, so we need to support that as well.

**Describe the solution you'd like**
Consider 200 also as a success response code.

**Describe alternatives you've considered**
I feel that 2xx codes need to be supported as success status codes.

**Additional context**
One of the endpoint/services that we are consuming is returning 200 response which leads to an error thrown from BlobOperations class.

**Comment by jalauzon-msft** [comment]
Hi @KeerthiYandaOS, thanks for reaching out. The success status codes that are in `BlobOperations` are generated from our service Swagger and are determined by the Storage service. These are supposed to be the only codes the Storage service is expected to return. For example, using the API that you linked Delete Blob, you can see from the [service docs](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-blob#status-code) that API is expected to return to return only `202 Accepted`.

I'm curious which APIs you are seeing other status codes from and what endpoint/service you are consuming that returns a different code. The main Storage service should only ever be returning the codes dictated by the service docs. It is possible there is a mapping mistake somewhere, but it does not look to be the case for `delete` anyway.

Can you please share some more information about which APIs and endpoints/services you are referring too? Thanks.

**Comment by jalauzon-msft** [comment]
Hi @KeerthiYandaOS Keerthi, I'm going to close this issue for now as it's not something we can't easily support, as we discussed offline. Please feel free to reach out internally to discuss further.
