### ISSUE TITLE
ServiceBusService.send_queue_message Performance

### ISSUE THREAD

**Issue by andrewkittredge** [Azure/azure-sdk-for-python#260]
My calls to ServiceBusService.send_queue_message take > .5 second.  Is that expected?  Are there strategies for increasing the speed?  Python 3.4, Windows 7.

    from azure.servicebus import ServiceBusService, Message
    bus_service = ServiceBusService(service_namespace=SERVICE_BUS_NAMESPACE,
                                shared_access_key_name=SHARED_ACCESS_KEY_NAME,
                                shared_access_key_value=SHARED_ACCESS_KEY_VALUE
                                )
    message  = Message("test message".encode("utf-8"))
    %prun(bus_service.send_queue_message("tasks", message))

 647 function calls in 0.684 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.298    0.298    0.298    0.298 {method 'read' of '_ssl._SSLSocket' objects}
        1    0.157    0.157    0.157    0.157 {method 'do_handshake' of '_ssl._SSLSocket' objects}
        1    0.153    0.153    0.153    0.153 {built-in method getaddrinfo}
        1    0.072    0.072    0.072    0.072 {method 'connect' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {built-in method __new__ of type object at 0x1D744B80}
        2    0.000    0.000    0.000    0.000 {method 'write' of '_ssl._SSLSocket' objects}
        1    0.000    0.000    0.000    0.000 ssl.py:756(_real_close)
        1    0.000    0.000    0.000    0.000 socket.py:242(_real_close)
        1    0.000    0.000    0.000    0.000 {method 'set_ciphers' of '_ssl._SSLContext' objects}
        1    0.000    0.000    0.157    0.157 ssl.py:451(__init__)
        1    0.000    0.000    0.684    0.684 {built-in method exec}
        2    0.000    0.000    0.000    0.000 socket.py:118(__init__)
        1    0.000    0.000    0.000    0.000 {method '_wrap_socket' of '_ssl._SSLContext' objects}
        1    0.000    0.000    0.683    0.683 httpclient.py:181(perform_request)
        6    0.000    0.000    0.000    0.000 client.py:1029(putheader)
        2    0.000    0.000    0.000    0.000 parse.py:728(<listcomp>)
        2    0.000    0.000    0.000    0.000 feedparser.py:207(_parsegen)
        1    0.000    0.000    0.298    0.298 client.py:313(_read_status)
        1    0.000    0.000    0.000    0.000 socket.py:193(makefile)
        1    0.000    0.000    0.001    0.001 client.py:250(parse_headers)
        3    0.000    0.000    0.000    0.000 idna.py:147(encode)
        8    0.000    0.000    0.298    0.037 {method 'readline' of '_io.BufferedReader' objects}
        1    0.000    0.000    0.299    0.299 client.py:345(begin)
        1    0.000    0.000    0.000    0.000 hmac.py:26(__init__)
        3    0.000    0.000    0.000    0.000 parse.py:708(quote_from_bytes)
        1    0.000    0.000    0.000    0.000 feedparser.py:460(_parse_headers)
        9    0.000    0.000    0.000    0.000 message.py:457(get)
        1    0.000    0.000    0.383    0.383 client.py:1194(connect)
        1    0.000    0.000    0.157    0.157 ssl.py:760(do_handshake)
        1    0.000    0.000    0.684    0.684 servicebusservice.py:722(send_queue_message)
       34    0.000    0.000    0.000    0.000 {method 'encode' of 'str' objects}
        1    0.000    0.000    0.000    0.000 client.py:913(putrequest)
        1    0.000    0.000    0.225    0.225 socket.py:475(create_connection)
        1    0.000    0.000    0.000    0.000 feedparser.py:129(__init__)
        1    0.000    0.000    0.683    0.683 servicebusservice.py:890(_perform_request)
        4    0.000    0.000    0.000    0.000 _policybase.py:281(header_source_parse)
        1    0.000    0.000    0.001    0.001 parser.py:44(parse)
        4    0.000    0.000    0.000    0.000 message.py:559(get_content_type)
        2    0.000    0.000    0.383    0.191 client.py:834(send)
        1    0.000    0.000    0.299    0.299 client.py:1106(getresponse)
        1    0.000    0.000    0.153    0.153 socket.py:513(getaddrinfo)
        1    0.000    0.000    0.000    0.000 client.py:581(_readall_chunked)
       10    0.000    0.000    0.000    0.000 _policybase.py:269(_sanitize_header)
        1    0.000    0.000    0.000    0.000 servicebusservice.py:995(_get_authorization)
        2    0.000    0.000    0.000    0.000 ssl.py:670(sendall)
        4    0.000    0.000    0.000    0.000 socket.py:79(_intenum_converter)
        1    0.000    0.000    0.000    0.000 client.py:283(__init__)
        4    0.000    0.000    0.000    0.000 enum.py:196(__call__)
        1    0.000    0.000    0.000    0.000 ssl.py:408(_create_stdlib_context)
       16    0.000    0.000    0.000    0.000 {built-in method hasattr}
        1    0.000    0.000    0.001    0.001 client.py:1173(__init__)
        1    0.000    0.000    0.000    0.000 ssl.py:327(__new__)
        1    0.000    0.000    0.157    0.157 ssl.py:336(wrap_socket)
        1    0.000    0.000    0.000    0.000 socket.py:345(__init__)
        4    0.000    0.000    0.000    0.000 enum.py:440(__new__)
        7    0.000    0.000    0.000    0.000 feedparser.py:74(readline)
        1    0.000    0.000    0.000    0.000 feedparser.py:97(push)
        3    0.000    0.000    0.000    0.000 parse.py:647(quote)
        1    0.000    0.000    0.000    0.000 __init__.py:972(_sign_string)
        2    0.000    0.000    0.000    0.000 ssl.py:633(send)
        1    0.000    0.000    0.000    0.000 servicebusservice.py:898(_update_service_bus_header)
        1    0.000    0.000    0.000    0.000 {method 'getpeername' of '_socket.socket' objects}
        4    0.000    0.000    0.000    0.000 message.py:28(_splitparam)
        1    0.000    0.000    0.001    0.001 httpclient.py:115(get_connection)
      108    0.000    0.000    0.000    0.000 {method '__getitem__' of 'dict' objects}
        1    0.000    0.000    0.000    0.000 socket.py:436(close)
        1    0.000    0.000    0.298    0.298 socket.py:357(readinto)
        2    0.000    0.000    0.000    0.000 {method 'settimeout' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 client.py:460(close)
        7    0.000    0.000    0.000    0.000 feedparser.py:118(__next__)
       28    0.000    0.000    0.000    0.000 {built-in method isinstance}
        6    0.000    0.000    0.000    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
        1    0.000    0.000    0.383    0.383 httpclient.py:156(send_request_headers)
        1    0.000    0.000    0.000    0.000 servicebusservice.py:1008(_get_expiry)
        2    0.000    0.000    0.000    0.000 message.py:119(__init__)
        1    0.000    0.000    0.000    0.000 client.py:738(__init__)
       42    0.000    0.000    0.000    0.000 {method 'lower' of 'str' objects}
        1    0.000    0.000    0.000    0.000 client.py:824(close)
       34    0.000    0.000    0.000    0.000 {built-in method len}
        8    0.000    0.000    0.000    0.000 {method 'split' of 'str' objects}
        1    0.000    0.000    0.000    0.000 feedparser.py:176(close)
        1    0.000    0.000    0.298    0.298 ssl.py:697(recv_into)
        1    0.000    0.000    0.383    0.383 client.py:889(_send_output)
        1    0.000    0.000    0.298    0.298 ssl.py:571(read)
        1    0.000    0.000    0.000    0.000 __init__.py:857(_update_request_uri_query)
        1    0.000    0.000    0.000    0.000 client.py:551(_read_next_chunk_size)
        1    0.000    0.000    0.000    0.000 {method 'close' of '_io.BufferedReader' objects}
       10    0.000    0.000    0.000    0.000 _policybase.py:299(header_fetch_parse)
       10    0.000    0.000    0.000    0.000 utils.py:57(_has_surrogates)
       26    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 __init__.py:159(_encode_base64)
        1    0.000    0.000    0.000    0.000 socket.py:252(detach)
        1    0.000    0.000    0.001    0.001 parser.py:62(parsestr)
        2    0.000    0.000    0.000    0.000 feedparser.py:170(_call_parse)
        3    0.000    0.000    0.000    0.000 {method 'split' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 base64.py:52(b64encode)
        1    0.000    0.000    0.000    0.000 client.py:470(flush)
        1    0.000    0.000    0.000    0.000 {method 'getsockopt' of '_socket.socket' objects}
        2    0.000    0.000    0.000    0.000 socket.py:398(readable)
        1    0.000    0.000    0.000    0.000 feedparser.py:189(_new_message)
        7    0.000    0.000    0.000    0.000 {method 'startswith' of 'str' objects}
        1    0.000    0.000    0.000    0.000 socket.py:262(family)
        3    0.000    0.000    0.000    0.000 message.py:583(get_content_maintype)
        1    0.000    0.000    0.000    0.000 {function HTTPResponse.close at 0x031D6390}
        1    0.000    0.000    0.684    0.684 <string>:1(<module>)
        7    0.000    0.000    0.000    0.000 client.py:882(_output)
        1    0.000    0.000    0.000    0.000 hmac.py:108(_current)
        1    0.000    0.000    0.000    0.000 __init__.py:216(add_headers)
        7    0.000    0.000    0.000    0.000 {method 'pop' of 'list' objects}
        9    0.000    0.000    0.000    0.000 {method 'join' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 httpclient.py:173(send_request_body)
        1    0.000    0.000    0.000    0.000 client.py:698(getheaders)
        1    0.000    0.000    0.000    0.000 {method 'splitlines' of 'str' objects}
        1    0.000    0.000    0.000    0.000 httpclient.py:108(get_uri)
        1    0.000    0.000    0.000    0.000 {built-in method round}
        4    0.000    0.000    0.000    0.000 {method 'update' of '_hashlib.HASH' objects}
        1    0.000    0.000    0.000    0.000 {method 'format' of 'str' objects}
        1    0.000    0.000    0.000    0.000 message.py:454(<listcomp>)
        1    0.000    0.000    0.000    0.000 __init__.py:597(_get_request_body_bytes_only)
        3    0.000    0.000    0.000    0.000 {method 'rstrip' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 feedparser.py:111(pushlines)
        1    0.000    0.000    0.000    0.000 __init__.py:66(__init__)
        1    0.000    0.000    0.000    0.000 feedparser.py:165(feed)
        5    0.000    0.000    0.000    0.000 {method 'find' of 'str' objects}
        4    0.000    0.000    0.000    0.000 message.py:474(set_raw)
        7    0.000    0.000    0.000    0.000 {method 'join' of 'str' objects}
        2    0.000    0.000    0.000    0.000 {method 'digest' of '_hashlib.HASH' objects}
        1    0.000    0.000    0.000    0.000 client.py:455(_close_conn)
        1    0.000    0.000    0.383    0.383 client.py:1049(endheaders)
        2    0.000    0.000    0.000    0.000 {built-in method openssl_sha256}
        1    0.000    0.000    0.000    0.000 socket.py:268(type)
        3    0.000    0.000    0.000    0.000 {method 'decode' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 feedparser.py:52(__init__)
        4    0.000    0.000    0.000    0.000 {method 'lstrip' of 'str' objects}
        1    0.000    0.000    0.000    0.000 socket.py:236(_decref_socketios)
        1    0.000    0.000    0.000    0.000 client.py:490(read)
        4    0.000    0.000    0.000    0.000 {method 'rstrip' of 'str' objects}
        1    0.000    0.000    0.000    0.000 socket.py:246(close)
        1    0.000    0.000    0.000    0.000 {built-in method b2a_base64}
        1    0.000    0.000    0.000    0.000 message.py:446(items)
        1    0.000    0.000    0.000    0.000 client.py:425(_check_close)
        9    0.000    0.000    0.000    0.000 {method 'strip' of 'str' objects}
        4    0.000    0.000    0.000    0.000 {method 'count' of 'str' objects}
        1    0.000    0.000    0.000    0.000 parser.py:20(__init__)
        1    0.000    0.000    0.000    0.000 client.py:567(_read_and_discard_trailer)
        4    0.000    0.000    0.000    0.000 {method 'partition' of 'str' objects}
        1    0.000    0.000    0.000    0.000 servicebusservice.py:991(sign_request)
        1    0.000    0.000    0.000    0.000 __init__.py:43(__init__)
        1    0.000    0.000    0.000    0.000 client.py:766(_set_hostport)
        6    0.000    0.000    0.000    0.000 ssl.py:559(_checkClosed)
        2    0.000    0.000    0.000    0.000 {method 'read' of '_io.StringIO' objects}
        1    0.000    0.000    0.000    0.000 message.py:298(set_payload)
        1    0.000    0.000    0.000    0.000 hmac.py:117(digest)
        1    0.000    0.000    0.000    0.000 {function HTTPResponse.flush at 0x031D63D8}
        1    0.000    0.000    0.000    0.000 {method '_checkReadable' of '_io._IOBase' objects}
        1    0.000    0.000    0.000    0.000 feedparser.py:68(close)
        1    0.000    0.000    0.000    0.000 ssl.py:563(_check_connected)
        1    0.000    0.000    0.000    0.000 {method 'find' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 {method '_checkClosed' of '_io._IOBase' objects}
        1    0.000    0.000    0.000    0.000 ssl.py:546(context)
        2    0.000    0.000    0.000    0.000 {method 'translate' of 'bytes' objects}
        1    0.000    0.000    0.000    0.000 servicebusservice.py:887(_get_host)
        1    0.000    0.000    0.000    0.000 feedparser.py:138(<lambda>)
        1    0.000    0.000    0.000    0.000 ssl.py:333(__init__)
        1    0.000    0.000    0.000    0.000 feedparser.py:199(_pop_message)
        1    0.000    0.000    0.000    0.000 {built-in method time}
        2    0.000    0.000    0.000    0.000 __init__.py:465(_validate_not_none)
        1    0.000    0.000    0.000    0.000 hmac.py:90(update)
        1    0.000    0.000    0.000    0.000 {method 'endswith' of 'str' objects}
        2    0.000    0.000    0.000    0.000 feedparser.py:115(__iter__)
        3    0.000    0.000    0.000    0.000 {method 'gettimeout' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {method 'copy' of '_hashlib.HASH' objects}
        1    0.000    0.000    0.000    0.000 {method 'extend' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'fileno' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {built-in method callable}
        1    0.000    0.000    0.000    0.000 {function socket.detach at 0x02A3C8E8}

**Comment by lezi226** [comment]
Hi, I hit same issue. Is there any plan to optimize it? Thanks

**Comment by lmazuel** [comment]
Just had a discussion with the ServiceBus team. For problem around performance and missing features, the current recommendation from the ServiceBus team is to use AMQP instead of HTTP:
https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-python/

The ServiceBus team were not able to propose better performance using HTTP, due to HTTP limit.
