### ISSUE TITLE
Add client.count_entities and client.entity_exists

### ISSUE THREAD

**Issue by erikpa1** [Azure/azure-sdk-for-python#26026]
Hi I checked some examples (c# too), and code but I don't see very basic functionality like  

**1. does entity even exists?** 
Not sure how to check if entity event exists without this kind of code:

```
        query = f"PartitionKey eq 'app' and RowKey eq '{TimeManager.get_today_formated()}'"
        entities: ItemPaged = tClient.query_entities(query)

        someEntity: 'dict[str, object]' = None

        for i in entities:
            someEntity = i
            break

        if not someEntity: 
               doSomething()
```

If there is easier way, please write me (and upload examples please), I can't do code like this for everything.

**2. how many entities are there?**

Again, do I have to iterate through ItemPaged to get count?

**Solution:**
Adding to TableClient functions for .entitity_exists(partion_key, row_key) and .get_entities_count(myquerystring)

Thanks, have a nice day ` :) `

**Comment by kashifkhan** [comment]
Thanks for the feedback @erikpa1, just wanted to clarify, is this for the Table sdk?

**Comment by erikpa1** [comment]
@kashifkhan oh jesus , yes sorry, I wrote this on bad repository, but yes it is. for Azure Tables (but as I see that one is dead noone is answering on user stories,....)
