### ISSUE TITLE
Task remains active even if the task it depends on fails.

### ISSUE THREAD

**Issue by Itamar-Erez-Cognata** [Azure/azure-sdk-for-python#26037]
- **Package Name=azure-batch**: 
- **Package Version=12.0.0**: 
- **Operating System=ubuntu**:
- **Python Version=3.8**: 

**Describe the bug**
Running a job on Azure batch pool, with two tasks A and B that have the dependency: B dependent on A.
A failed; however, B does not fail and is still in status running. 

**To Reproduce**
1. Create a job with two tasks, A and B, Where B dependent on A
2. Make A to fail with exit code 1

**Expected behavior**
Task B should fail.

**Screenshots**
![Screenshot from 2022-09-05 16-04-36](https://user-images.githubusercontent.com/91829021/188456252-ca98fa8a-d9c2-4a74-9083-70446b0123c2.png)
In the screenshot, the task sub_dummy_process has a dependency on failing_dummy_process. 

**Additional context**
**Code context**
`
dependencies = azure.batch.TaskDependencies(task_ids=depends_on)
task = azure.batch.TaskAddParameter(
        id=task_id,
        user_identity=user,
        required_slots=1,
        depends_on=dependancies
    )
batch_client.task.add(
                job_id=job_id,
                task=task
            )
`

**Comment by cRui861** [comment]
Hi, @Itamar-Erez-Cognata at the task level, this is by design. If you are looking for a failure signal, you can set the Job's OnTaskFailure option to initiate a terminate Job action instead.
