### ISSUE TITLE
How to connect and work with Azure Cosmos Gremlin API for Python SDK

### ISSUE THREAD

**Issue by gpnikhil** [Azure/azure-sdk-for-python#26038]
I am not able to find a proper page to how to connect to a gremlin database and do queries with python

fount this module - 'https://pypi.org/project/gremlinpython/' but no luck

**Comment by kashifkhan** [comment]
Thanks for the feedback @gpnikhil , we’ll investigate asap.

**Comment by PramodValavala-MSFT** [comment]
@gpnikhil There is [quickstart doc](https://docs.microsoft.com/en-us/azure/cosmos-db/graph/create-graph-python) that you can refer to which covers the step to run this [python sample](https://github.com/Azure-Samples/azure-cosmos-db-graph-python-getting-started).
