### ISSUE TITLE
Service Bus client fails to connect if the cacerts.pem file contains duplicates

### ISSUE THREAD

**Issue by colinbreame** [Azure/azure-sdk-for-python#26034]
- **Package Name**: azure-servicebus
- **Package Version**: 7.8.0
- **Operating System**: Windows
- **Python Version**: 3.8.12

**Describe the bug**
The Service Bus client fails to connect if the cacerts.pem file contains duplicates.

With debug log output enabled, the messages below can be seen:

> INFO:uamqp.c_uamqp:b'CertAddEncodedCertificateToStore failed with error 0x80092005' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\x509_schannel.c':b'add_certificates_to_store':517)
INFO:uamqp.c_uamqp:b'Cannot add certificates to store' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\x509_schannel.c':b'x509_verify_certificate_in_chain':556)
INFO:uamqp.c_uamqp:b'Failed to verify trusted certificate in chain' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\tlsio_schannel.c':b'verify_custom_certificate_if_needed':451)
INFO:uamqp.c_uamqp:b'Unable to verify server certificate against custom server trusted certificate' (b'D:\\a\\1\\s\\src\\vendor\\azure-uamqp-c\\deps\\azure-c-shared-utility\\adapters\\tlsio_schannel.c':b'on_underlying_io_bytes_received':710)

Error `0x80092005` is the code for `CRYPT_E_EXISTS` as per this page:  https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certaddencodedcertificatetostore.

**To Reproduce**
1. Create the certificates file with duplicates. i.e. [certs.pem.txt](https://github.com/Azure/azure-sdk-for-python/files/9487187/certs.pem.txt)
2. Specify the path to this file using the `connection_verify` parameter and then connect

```python
from azure.servicebus import ServiceBusClient
import logging

logging.basicConfig(level=logging.DEBUG)

conn_str = "..."
topic_name = "..."
subscription_name = "..."
certificates = "certs.pem"

def run():
    with ServiceBusClient.from_connection_string(conn_str, connection_verify=certificates) as client:
        receiver = client.get_subscription_receiver(topic_name, subscription_name)

        while True:
            for msg in receiver.receive_messages():
                print(msg)
run()
```

**Expected behavior**
I would expect the client to connect without issues.

Perhaps there are additional security considerations for handling duplicates, however would suggest that duplicates can be safely to the in-memory certificate store using `CertAddEncodedCertificateToStore` parameter other than `CERT_STORE_ADD_NEW`. i.e. `CERT_STORE_ADD_REPLACE_EXISTING`.

**Additional context**
We use the python package `python-certifi-win32` to generate the cacerts.pem file, which I suspect is a fairly common thing to do on Windows.  However, at least with our corporate network setup, the file contains duplicates.

**Comment by kashifkhan** [comment]
Thanks for the feedback @colinbreame , we’ll investigate asap.

**Comment by l0lawrence** [comment]
Hello @colinbreame!
Would you be able to try moving over to the pip-system-certs certifi patch package [here](https://pypi.org/project/pip-system-certs/)? I noticed that python-certifi-win32 says it is no longer being maintained on PyPI.

I was able to repro your issue locally after manually creating the duplicate certificates in the .pem file, and I will look into how we handle duplication.

**Comment by colinbreame** [comment]
Hi @l0lawrence,

Thanks for the response!  Great to hear you are looking at it.

Removing the `python-certifi-win32` package resolves the issue, but the path to the pem file returned by `certifi.where()` does not include our corporate CA (which is needed for other packages).  `pip-system-certs` does not help in this respect because it does not modify the certifi pem file.

As a work around; we constructed the `ServiceBusClient` using a custom `connection_verify` parameter:

```python
path_to_original_certifi_pem_file = ''
with ServiceBusClient.from_connection_string(conn_str, connection_verify=path_to_original_certifi_pem_file ) as client:
   ...
```

Unfortunately it only works with the non-async client: https://github.com/Azure/azure-sdk-for-python/issues/26015.

**Comment by l0lawrence** [comment]
I see, thank you for the clarification! I will also take a look at your other issue.
