### ISSUE TITLE
Support for FormRecognizer 2022-08-31 in Pypi packages

### ISSUE THREAD

**Issue by marcgardner** [Azure/azure-sdk-for-python#26066]
- **Package Name**: Azure Form Recognizer client library for Python
- **Package Version**: 3.2.0b6
- **Operating System**: Linux
- **Python Version**: 3.8.14

**Describe the bug**
There is no PyPi package supporting the DocumentAnalysis V2022_08_31 (which is the current GA version).

**To Reproduce**

1. Try to install Azure SDK FormRecognizer from pypi
2. Notice that you cannot use it with V2022_08_31 because of an API version mismatch.

**Expected behavior**
Work with V2022_08_31 (even if it is a beta version at the moment)

**Comment by catalinaperalta** [comment]
Thanks for reaching out @marcgardner! We are planning on releasing the stable SDK later this week. It will target service version 2022-08-31. I will update here again once it's been released.

**Comment by catalinaperalta** [comment]
We've released the package. It can be found on PyPi here: https://pypi.org/project/azure-ai-formrecognizer/3.2.0/. Thanks for reaching out!
