### ISSUE TITLE
RECEIVE SMS messages using Python SDK?

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-sdk-for-python#26121]
**Is your feature request related to a problem? Please describe.**
- The Azure Comm Services (ACS) Github repo says the capability to "send and receive SMS messages" exists
- But this does not appear to be the case for the Python SDK
- REF: https://docs.microsoft.com/en-us/answers/questions/1000280/is-it-possible-to-receive-sms-texts-using-azure-co.html

**Describe the solution you'd like**
Would like the ACS Python SDK to adopt the ability to RECEIVE SMS texts. This would create a solid use case over Twilio. I want to keep all projects within Azure rather than spin up another vendor.

**Describe alternatives you've considered**
Twilio

**Additional context**
https://docs.microsoft.com/en-us/answers/questions/1000280/is-it-possible-to-receive-sms-texts-using-azure-co.html

**Comment by kashifkhan** [comment]
Thanks for the feedback @SeaDude, we'll investigate asap. cc @turalf

**Comment by SeaDude** [comment]
Answers were given [here ](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp)and [here](https://stackoverflow.com/questions/73669076/is-it-possible-to-receive-sms-texts-using-azure-communication-services-python-sd/73680398#73680398). 

Thank you
