### ISSUE TITLE
Page should have an example of how to call azure function with files data.

### ISSUE THREAD

**Issue by ameitg** [Azure/azure-sdk-for-python#26127]
I was trying to develop an Azure Logic app that calls azure function with each attachment of incoming email. I suggest that page have an example of how to call azure function with files data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6003782-85da-7eed-4a4c-08fb0d6527e9
* Version Independent ID: d4992fb7-6373-3bb1-20d5-f6939100f583
* Content: [azure.functions.HttpRequest class](https://docs.microsoft.com/en-us/python/api/azure-functions/azure.functions.httprequest?view=azure-python)
* Content Source: [docs-ref-autogen/azure-functions/azure.functions.HttpRequest.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-functions/azure.functions.HttpRequest.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by RakeshMohanMSFT** [comment]
@ameitg Thank you for reaching out, we will look into it.

**Comment by RakeshMohanMSFT** [comment]
@ameitg This repository is for issues with the Python SDK itself and based on your query, it would be best to ask this in the Microsoft Q&A forum to better engage the wider community.

Please go through this document https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-azure-functions?tabs=consumption it can help with the direction.
