### ISSUE TITLE
Enable token caching in azure-identity

### ISSUE THREAD

**Issue by gdippolito** [Azure/azure-sdk-for-python#26177]
**Is your feature request related to a problem? Please describe.**
Running DefaultAzureCredentials authentication on different threads do not cache the token and would make separate authentication requests. This is especially annoying when using ManagedIdentity when running with many threads. The managed identity endpoint will rate limit the request and therefore cause authentication errors on some of the threads.

**Describe the solution you'd like**
I would like the token retrieved to be cached and reused from different threads. This will significantly reduce the number of requests on the authentication endpoint.

**Describe alternatives you've considered**
I have created a python singleton to avoid re-initialising the same object. However, this has been a bit painful to manage.

**Comment by kristapratico** [comment]
Hi @gdippolito thanks for your feedback, we'll look into this as soon as possible.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you give more details about your scenario?

And if possible, can you share the code how you used the ManagedIdentityCredential?

**Comment by xiangyan99** [comment]
@gdippolito Thank you for sharing the code.

Our token caching mechanism is per-instance caching.

If every time you create a new credential instance, the token caching will not work as you expected.

We can use single credential or single storage client to make the caching work.

Please let me know if it works.

Thank you.

**Comment by gdippolito** [comment]
Hi @xiangyan99 thanks for the response. 

Would you mind clarifying what single credential or single storage client means? In my case we spawn many thread and processes I'm not sure how I could make a single client? 

Thanks.

**Comment by xiangyan99** [comment]
e.g.

Shared credential instance:
```py
credential = DefaultAzureCredential()
client1 = BlogStorageClient(credential=credential)
client2 = BlogStorageClient(credential=credential)
```
The token will be cached.

But if we use 
```py
client1 = BlogStorageClient(credential=DefaultAzureCredential())
client2 = BlogStorageClient(credential=DefaultAzureCredential())
```
The token will not be cached.

Thanks.

**Comment by gdippolito** [comment]
Hi @xiangyan99 thanks for the response. I think this will only work if you define multiple clients sequentially. However, the token won't be cached when using multiple Threads and processes. I think a strategy for caching token already exists for Interactive authentication, can this not be added to managed identity as well?

**Comment by xiangyan99** [comment]
As you are aware, our managed identity and interactive identity are implemented in different ways.

Interactive identity uses msal underneath while managed identity does not.

There is a tracking request to add managed identity support in msal. https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/58

When it is implemented, we can move azure.identity.managedidentity to use msal too therefore you will see same behavior.
