### ISSUE TITLE
[textanalytics] align swagger transforms across languages

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#26182]
- Add transforms to readme and split into general (which we can share across languages) and python-specific sections
- Update source code where needed (might be substantial depending on how many renames we do in the transforms)

**Comment by deyaaeldeen** [comment]
JS transforms: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/cognitivelanguage/ai-language-text/swagger/README.md
