### ISSUE TITLE
[EventHub] typing for class variables

### ISSUE THREAD

**Issue by JJHWAN** [Azure/azure-sdk-for-python#26209]
**Is your feature request related to a problem? Please describe.**

Some class variables in eventhub has older version of typing.

Such as 
`class EventProcessorMixin(object):

    _eventhub_client = (
        None
    )  # type: Optional[Union[EventHubConsumerClient, EventHubConsumerClientAsync]]
    _consumer_group = ""  # type: str
    _owner_level = None  # type: Optional[int]
    _prefetch = None  # type: Optional[int]
    _track_last_enqueued_event_properties = False  # type: bool
    _initial_event_position_inclusive = {}  # type: Union[bool, Dict[str, bool]]
    _initial_event_position = (
        {}
    )  # type: Union[int, str, datetime, Dict[str, Union[int, str, datetime]]]
`
From this [typing link](https://peps.python.org/pep-0526/)

It seems to be better to change typing to
Example : 
from
`    _consumer_group = ""  # type: str`
to
`    _consumer_group: str = "" `

I think it may be applied to other directories too

**Comment by swathipil** [comment]
@JJHWAN - Thanks for submitting a PR to address this! https://github.com/Azure/azure-sdk-for-python/pull/26208#pullrequestreview-1107908667

Just reviewed and can take another look after my comments have been addressed.

**Comment by swathipil** [comment]
pr merged
