### ISSUE TITLE
Azure service fabric sdk for python sample link is dead

### ISSUE THREAD

**Issue by mvperez** [Azure/azure-sdk-for-python#2620]
Hi,
This [link](https://docs.microsoft.com/en-us/python/api/overview/azure/servicefabric/clientlibrary) is dead. Where can we find the samples using service fabric sdk for python?

**Comment by lmazuel** [comment]
Hi @marvinvperez 
SF correct is this one:
https://docs.microsoft.com/python/api/overview/azure/servicefabric

It seems there is no samples for Python yet wrote by the service team. @samedder could you help here?

Thanks,

**Comment by samedder** [comment]
We don't have any samples that I'm aware of right now. If you want some sample code however you can take a look at the [cli we wrote](https://github.com/Microsoft/service-fabric-cli) using the SDK.

**Comment by peterpogorski** [comment]
@bsiegel can this issue be closed?

**Comment by pixelicous** [comment]
are there any plans for giving some instructions on working with applications?
