### ISSUE TITLE
[azure-identity] Authentication via service principal returns generic error

### ISSUE THREAD

**Issue by gio88oig** [Azure/azure-sdk-for-python#26215]
**Describe the bug**
Hi all, i am using the azure-identity to try authenticate a service principal against a storage account but I receive a generic Authentication failed: 1

***Exception or Stack Trace***
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
EnvironmentCredential: Authentication failed: 1
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.

**To Reproduce**
Set the AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET environment vars and try to authenticate using the DefaultAzureCredential class

***Code Snippet***
creds = DefaultAzureCredential()
            self.blob_service_client = BlobServiceClient(
               account_url="xxx", 
               credential=creds
            )

**Expected behavior**
Correctly authenticate to the storage account

**Screenshots**
![image](https://user-images.githubusercontent.com/99415758/190206396-3564033e-4fa5-4167-beaa-4a7aa938fe2b.png)

**Setup (please complete the following information):**
 - Python Version: 3.9
 - SDK Version: azure-identity 1.10

**Additional context**
The application is hosted in an Azure Kubernetes POD. I tried to login against the storage account from a shell within the pod in order to investigate network related issues but I can authenticate via az login --service-principal and download files from the storage.

**Comment by kristapratico** [comment]
Hi @gio88oig thanks for your feedback. We will take a look as soon as possible.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you help to check 

```py
creds = DefaultAzureCredential()
creds.get_token("https://storage.azure.com/.default")
```

And see if we can get a token?

Thanks.

**Comment by gio88oig** [comment]
@xiangyan99 same error :(
I can't understand why I don't receive more details about the error...I am stuck on this since days.

![image](https://user-images.githubusercontent.com/99415758/190383393-55c5edce-0a68-4f93-9261-6d85f880a0b4.png)

![image](https://user-images.githubusercontent.com/99415758/190383469-b034b5e0-664b-42e8-95db-f304e336a606.png)

The past days I also tried using the ServicePrincipalCredentials but I received the same Authentication failed: 1...in that case I received also a stack trace but with no relevant help.

**Comment by xiangyan99** [comment]
Thanks for the updates.

If I understand correctly, when you used az login --service-principal, you specified client-secret, etc. in the command rather than getting them from the environment, right?

Could you help to double check if they have same value?

**Comment by gio88oig** [comment]
@xiangyan99 actually I cannot give you some screenshot but yes I absolutely used the same clientid, clientsecret and tenantid values.

From the python code I first tried with ServicePrincipalCredentials and then with DefaultAzureCredential with no success.

From a shell within the kubernetes pod I used the az login and the get access token and I was able to obtain a token.

I can give you another information that I missed: if I try to authenticate with the connection string of the storage from the python code, the pod can correctly authenticate.

But I don't understand why I don't receive any kind of error description.

**Comment by xiangyan99** [comment]
Thank for the confirmation.

ServicePrincipalCredentials is track 1 class not from azure.identity.

Could you run pip freeze and share which packages (and version) you installed?

Thanks.

**Comment by gio88oig** [comment]
@xiangyan99 here the output of the pip freeze

anyio==3.6.1
asgiref==3.5.2
attrs==22.1.0
azure-core==1.25.1
azure-identity==1.10.0
azure-storage-blob==12.13.1
be-python-common==0.0.2
certifi==2022.6.15.2
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
clickclick==20.10.2
common==0.1.2
connexion==2.13.1
cryptography==38.0.1
dependency-injector==4.39.1
envyaml==1.10.211231
fastapi==0.77.1
fasttext==0.9.2
Flask==2.2.2
gevent==21.12.0
greenlet==1.1.3
gunicorn==20.1.0
h11==0.13.0
idna==3.4
importlib-metadata==4.12.0
inflection==0.5.1
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.2
jsonschema==4.16.0
loguru==0.6.0
MarkupSafe==2.1.1
mongoengine==0.24.1
msal==1.18.0
msal-extensions==1.0.0
msrest==0.7.1
numpy==1.23.3
oauthlib==3.2.1
packaging==21.3
portalocker==2.5.1
pybind11==2.10.0
pycparser==2.21
pydantic==1.9.0
PyJWT==2.4.0
pymongo==4.2.0
pyparsing==3.0.9
pyrsistent==0.18.1
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
six==1.16.0
sniffio==1.3.0
starlette==0.19.1
swagger-ui-bundle==0.0.9
typing-extensions==4.3.0
urllib3==1.26.12
uvicorn==0.17.6
Werkzeug==2.2.2
zipp==3.8.1
zope.event==4.5.0
zope.interface==5.4.0

**Comment by xiangyan99** [comment]
Thanks for the information.

Just to make sure we are on same page, how did you configure the AKS and service principal?

Did you follow https://learn.microsoft.com/en-us/azure/aks/kubernetes-service-principal?tabs=azure-cli?
