### ISSUE TITLE
Multi api versioned package needed for azure-mgmt-authorization

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-python#2623]
azure stack cli is broken for az role commands as stack does not support the latest authorization api-version 2018-01-01-preview,  Azure stack supports the api-version 2015-07-01

Here is the complete set for  2017-03-09-profile

        "microsoft.authorization": {
			"2015-01-01": [
				"locks"
			],
			"2015-07-01": [
				"operations",
				"permissions",
				"roleAssignments",
				"roleDefinitions"
			],
			"2015-10-01-preview": [
				"policyAssignments",
				"policyDefinitions"
			],
			"2015-07-01-preview": [
				"providerOperations"
			]
        },

and for 2018-03-01 profile

        "microsoft.authorization": {
			"2017-04-01": [
				"locks"
			],
			"2015-07-01": [
				"operations",
				"permissions",
				"roleAssignments",
				"roleDefinitions"
			],
			"2016-12-01": [
				"policyAssignments",
				"policyDefinitions"
			],
			"2015-07-01-preview": [
				"providerOperations"
			]
        },

**Comment by lmazuel** [comment]
Released:
https://pypi.org/project/azure-mgmt-authorization/0.50.0/
