### ISSUE TITLE
[Identity] Make manual managed identity tests compatible with migrated tests

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#26237]
Per https://github.com/Azure/azure-sdk/issues/1908#issuecomment-1229867818, manual tests for Azure Arc have run into errors because of `azure-identity`'s recent migration to the test proxy. We need to adjust tests meant for live test environments to be runnable, most likely without the test proxy tool present. Otherwise, setting up the test proxy on, for example, an Azure VM would be necessary to run manual tests.

**Comment by pvaneck** [comment]
Confirming that simply seting the following environment variables allows the tests to be run:

```
AZURE_TEST_RUN_LIVE=true
AZURE_SKIP_LIVE_RECORDING=true
```

**Comment by mccoyp** [comment]
Resolved by https://github.com/Azure/azure-sdk-for-python/pull/27182
