### ISSUE TITLE
[ApiManagement] LROPoller.add_done_callback seems to behave strangely

### ISSUE THREAD

**Issue by zadigus** [Azure/azure-sdk-for-python#26240]
- **Package Name**: azure-mgmt-apimanagement
- **Package Version**: 3.0.0
- **Operating System**: Windows 10
- **Python Version**: 3.10

**Describe the bug**
It seems like the `LROPoller.add_done_callback` method acts on the right `LROPoller` object but handles a bit strangely the data I provide the callback with.

**To Reproduce**
I am doing this:

```python
        for api_name in api_defn:
            definition = api_defn[api_name]
            with open(definition["path"], "r") as api_file:
                params = ApiCreateOrUpdateParameter(
                    subscription_required=False,
                    display_name=api_name,
                    service_url=f"{my_service_url}{definition['endpoint']}",
                    path=definition["suffix"],
                    protocols=["https"],
                    format=ContentFormat.OPENAPI,
                    value=api_file.read()
                )
            result = self._api_mgmt_client.api.begin_create_or_update(
                resource_group_name=self._resource_group_name,
                service_name=self._api_mgmt_name,
                api_id=api_name,
                parameters=params,
            )
            result.add_done_callback(lambda lro: print(f"the api {api_name} has status {lro.status()}"))
```

In my test case, `api_defn` is defined like this:

```json
{
  "my-first-api": {
    "path": "APIs/my-first-api.yml",
    "suffix": "api-1",
    "endpoint": "/api-1"
  },
  "my-second-api": {
      "path": "APIs/my-second-api.yml",
      "suffix": "api-2",
      "endpoint": "/api-2"
    }
}
```

What I get outputted to my console is

```bash
the api my-second-api has status succeeded
the api my-second-api has status succeeded
```
Both APIs have successfully been added to API management. Everything looks good on the API management side.

**Expected behavior**
I should see the following output in the console:

```bash
the api my-first-api has status succeeded
the api my-second-api has status succeeded
```

**Additional context**
Am I misusing your library?

**Comment by kristapratico** [comment]
Hi @zadigus thanks for the detailed feedback, we'll take a look as soon as possible.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

It looks to me the behavior is correct.

```py
result.add_done_callback(lambda lro: print(f"the api {api_name} has status {lro.status()}"))
```

The lambda is triggered when the operation is done and at that time, Python evaluates the value of api_name which is "my-second-api".

**Comment by zadigus** [comment]
Indeed. Sorry for that noob question, I think it comes from my personal misconception of how python works.
