### ISSUE TITLE
Azure Billing API not working for CSP Account 

### ISSUE THREAD

**Issue by mamathy** [Azure/azure-sdk-for-python#2624]
Using below python api for Azure Billing,

commerce_client = UsageManagementClient(credentials, subscription_id)
usage_list = commerce_client.usage_aggregates.list(start, end)

It will works fine for EA account,but throw exception for CSP account as follows,

Operation returned an invalid status code 'Bad Request'

**Comment by lmazuel** [comment]
@sandeepnl do you know the right person to help here?
Thank you,

**Comment by xiangyan99** [comment]
@mamathy latest azure-mgmt-commerce is 6.0.0. Does this work for you?
