### ISSUE TITLE
azureml sdk V2 component pipeline "optional Input <variable_name> must be placed in nested argument: $[[]]."

### ISSUE THREAD

**Issue by palmerss** [Azure/azure-sdk-for-python#26253]
- **Package Name**: azure-ai-ml 
- **Package Version**:  0.1.0b6
- **Operating System**: ubuntu
- **Python Version**: 3.8.12

**Describe the bug**
A component I'm building has an optional argument, it seems like over night that all of our pipelines that were making use of optional arguments fail to launch from our launch scripts resulting in an error that reads
`"optional Input <variable_name> must be placed in nested argument: $[[]]."`
Removing the optional argument seems to allow the pipeline to launch as expected

I'm currently using mldesigner version 0.1.0b4, I have tried upgrading to 0.1.0b5 and that resulted in a different crash when launching the pipeline due to an import error from the azure-ai-ml package
EDIT: To get mldesigner 0.1.0b5 to work I installed the latest commit on the azure-ai-ml 0.1.0b7 branch and that fixed the crash I originally had with mldesigner 0.1.0b5, but gives me the same optional argument crashed in the title of this issue.

**Comment by kristapratico** [comment]
Hi @palmerss thanks for your issue. @azureml-github can you take a look?

**Comment by luigiw** [comment]
@palmerss Thx for reporting this issue. @wangchao1230 @cloga

**Comment by cloga** [comment]
Hi @palmerss 
Sorry for the inconvenience caused. 
We change the syntax to embrace optional inputs in command line from _[]_ to _$[[]]_, as _[]_ is conflicted with conditional syntax with shell command, which cause issue if customer try to use that in command section of command component.

The existing registered component will continue worked.
You need change _[]_ to _$[[]]_ when you creating new component or reference inline component. 
You can find the new example here: https://github.com/Azure/azureml-examples/tree/main/cli/assets/component

**Comment by palmerss** [comment]
Thanks for the heads up @cloga, do you have an example of how this changes the syntax with the python sdk, while using the command_component decorator? as I am using that instead of the CLI sdk.

pseudo-code of the function that I'm wrapping
`
@command_component(
    name="my_component",
    display_name="my_component",
    description="This components optional parameters throw an error"
)
def my_component(
    output: Output(type="uri_folder"),
    required_input: Input(type="string", default="default_string"),
    this_causes_crash: Input(type="string", optional=True) = None, 
)
`

**Comment by 0mza987** [comment]
Hi @palmerss , we fixed this issue in our latest code and have made a private build for you to test, please have a try using this:

pip install mldesigner==0.0.72045852 --extra-index-url=https://azuremlsdktestpypi.azureedge.net/test-sdk-cli-v2/

Besides, the official release 0.1.0b6 that contains this fix will be released in a few days

**Comment by palmerss** [comment]
awesome, @0mza987 , I just tested this and it works, tyvm for the rapid response, looking forward to 0.1.0b6

**Comment by luigiw** [comment]
Thx @cloga  and @palmerss for the quick reply and turn around!
