### ISSUE TITLE
azureml sdk V2 component pipeline "optional Input <variable_name> must be placed in nested argument: $[[]].

### ISSUE THREAD

**Issue by palmerss** [Azure/azure-sdk-for-python#26252]
- **Package Name**: azure-ai-ml 
- **Package Version**:  0.1.0b6
- **Operating System**: ubuntu
- **Python Version**: 3.8.12

**Describe the bug**
A component I'm building has an optional argument, it seems like over night that all of our pipelines that were making use of optional arguments fail to launch from our launch scripts

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kristapratico** [comment]
dup of #26253
