### ISSUE TITLE
Setup SDK for Cognitive Services Personalizer

### ISSUE THREAD

**Issue by sharathmalladi** [Azure/azure-sdk-for-python#26255]
**Is your feature request related to a problem? Please describe.**
Not a problem. It is to add functionality for Personalizer.

**Describe the solution you'd like**
We want an SDK for Cognitive Services Personalizer.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kristapratico** [comment]
client library was released
