### ISSUE TITLE
FormRecognizer Prebuilt Receipt date is not JSON serializable

### ISSUE THREAD

**Issue by sam961124** [Azure/azure-sdk-for-python#26265]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.2.0
- **Operating System**: Windows
- **Python Version**: 3.8.5

**Describe the bug**
It causes "Object of type date is not JSON serializable" error when I run this script to analyze the sample receipt from 
https://github.com/Azure/azure-sdk-for-python/blob/5eb462494af1be848453f05fda0558208431e1aa/sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_forms/receipt/contoso-receipt.png.
The result is correct that I can print it out.
`'TransactionDate': DocumentField(value_type=date, value=datetime.date(2019, 6, 10), content=6/10/2019,`
However, it seems that `to_dict()` fails to convert it.

```
with open(input_file, "rb") as fd:
    document = fd.read()

poller = Microsoft.client.begin_analyze_document(
                        "prebuilt-receipt",
                        document)
result = poller.result().to_dict()
with open(
    str(output_results / input_file.stem) + '.json',
    'w',
    encoding='utf8',
) as f:
    json.dump(result, f, indent=2, ensure_ascii=False)
```

**Comment by kristapratico** [comment]
Hi @sam961124, thanks for the detailed issue. Please see this sample which demonstrates how to serialize the result: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_convert_to_and_from_dict.py#L61

To serialize the datetime, you must pass in the `AzureJSONEncoder` to your `json.dump` call. Updated code would look like this:

```
from azure.core.serialization import AzureJSONEncoder

with open(input_file, "rb") as fd:
    document = fd.read()

poller = Microsoft.client.begin_analyze_document(
                        "prebuilt-receipt",
                        document)
result = poller.result().to_dict()
with open(
    str(output_results / input_file.stem) + '.json',
    'w',
    encoding='utf8',
) as f:
    json.dump(result, f, indent=2, ensure_ascii=False, cls=AzureJSONEncoder)
```

Let us know if you have any other questions. Thanks!
