### ISSUE TITLE
Support HttpClientTimeout and MaximumExecutionTime 

### ISSUE THREAD

**Issue by Shawngbk** [Azure/azure-sdk-for-python#26283]
In Cosmos DB Table API .NET SDK. There exists below two configurations.
TableClientConfiguration.RestExecutorConfiguration.HttpClientTimeout 
TableRequestOptions.MaximumExecutionTime

However, I didn't find them in Python SDK. May I know if these are supported in Python SDK for Table API?
Or, are there similar configurations in Python SDK?

Thanks for the help ahead of time.

**Comment by l0lawrence** [comment]
Hi @Shawngbk thank you for the question, we will get back to you asap.

**Comment by SaurabhSharma-MSFT** [comment]
@Shawngbk RestExecutorConfiguration was part of the deprecated package - [Microsoft.Azure.Cosmos.Table](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table).  I do not think we have a similar configuration in the new package - [Azure.Data.Tables](https://www.nuget.org/packages/Azure.Data.Tables/) or in python sdk. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@Shawngbk We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
