### ISSUE TITLE
mldesigner: error: invalid choice: 'execute' (choose from 'generate')

### ISSUE THREAD

**Issue by palmerss** [Azure/azure-sdk-for-python#26293]
Package Name: azure-ai-ml
Package Version: 0.1.0b6 , mldesigner: 0.1.0b6
Operating System: ubuntu
Python Version: 3.8.12

**Describe the bug**
When launching a job it promptly fails with an mldesigner error in the std_log.txt, reading

"
usage: mldesigner [-h] {generate} ...
mldesigner: error: invalid choice: 'execute' (choose from 'generate')
"

I was last able to launch the same pipelines this past Friday with no issue

**Comment by l0lawrence** [comment]
Hi @palmerss thanks for the feedback, we'll investigate asap. @azureml-github

**Comment by palmerss** [comment]
Update on my part, reverting mldesigner back to  0.1.0b3 seems to allow me to launch pipelines again, however this also restricts me on the usage of optional arguments that mldesigner 0.1.0b6 addresses

**Comment by 0mza987** [comment]
Hi @palmerss, we have repro-ed this issue and currently working on a fix release. Sorry for the inconvenience casued, currently you can use this private build to mitigate:

pip install mldesigner==72212755 --extra-index-url=https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2/

**Comment by palmerss** [comment]
@0mza987 I'll give this a shot and report back within the next day

**Comment by palmerss** [comment]
@0mza987 I'm unable to use the conda.yml with my environment, whenever try to launch the version of my environment that uses the conda.yml I get an error when launching that reads along the lines of
"Environment <environment_name> with version <version with conda.yml> is already registered and cannot be changed"

However I did double check that the docker image for my job is updated with both
mldesigner==0.1.0b6 AND azure-ai-ml==0.1.0b6

I am now getting a different error shortly launching in the std_log.txt that looks to be in 
mldesigner/_utils.py line 223, in list_2_dict
`
key, value = item.split("=")

ValueError: too many values to unpack (expected 2)
`
keep in mind I'm using the python azure-ai-ml package and not the cli tool

**Comment by palmerss** [comment]
Oh and of course let me know if I should just open this up as a separate issue and close this one out, because this may seem different enough.

**Comment by 0mza987** [comment]
@palmerss  can I get a look at your component command of the failed component? This error looks like the command is not in correct format which should be like "--inputs a=1 b=2", if you are trying to use optional parameter, make sure you pass nothing at all instead of passing an empty string when consuming the component.

**Comment by 0mza987** [comment]
And can you please show us the interface of your component definition and how you consume it like below example?

![image](https://user-images.githubusercontent.com/2572521/192427064-69f31985-1b85-43e2-bb6e-253254f781c9.png)
![image](https://user-images.githubusercontent.com/2572521/192427119-041835b1-fc39-4f36-b405-364e8a6fa7ec.png)

**Comment by palmerss** [comment]
@0mza987 Sorry for the delay in response, have been pretty busy, before getting these screenshots for you I went ahead and tried updating azure-ai-ml to 0.1.0b7 with mldesigner at version 0.1.0b6, still am getting the same error, as mentioned above, reverting mldesigner back to 0.1.0b3 allows me to launch jobs for the time being, but doesn't allow me to make use of optional inputs

pipeline
![image](https://user-images.githubusercontent.com/21338791/193667393-115efb11-cb47-4a8a-88b9-0f164a57ba4c.png)



Command Component 
![image](https://user-images.githubusercontent.com/21338791/193667001-22bd5eb9-8660-452a-8391-e3076aa72697.png)

**Comment by palmerss** [comment]
This issue has been resolved with the latest version of azure-ai-ml and mldesigner, as of the date of this comment, not sure what version it was actually fixed.
