### ISSUE TITLE
dependency conflict between azure-mgmt-subscription and azure-devops

### ISSUE THREAD

**Issue by ttorsteinbo** [Azure/azure-sdk-for-python#26290]
- **Package Name**: azure-devops
- **Package Version**: 6.0.0b4
- **Operating System**: MacOS 12.6
- **Python Version**: 3.10.4

**Describe the bug**
Error was encountered while upgrading azure-mgmt-subscription from 3.0.0 to 3.1.0

Setting these dependencies in your pipfile and running `pipenv install` will result in a dependency conflict error:
```
azure-mgmt-subscription = "==3.1.0"
azure-devops = "==6.0.0b4"
```

Looking at the dependency graph output it looks like the devops dependency has an upper limit on its ms-rest dependency version which triggers this error

from azure-devops dep graph:
`- msrest [required: >=0.6.0,<0.7.0, installed: 0.7.1]`

from azure-mgmt-subscription 3.1.0 dep graph:
`- msrest [required: >=0.7.1, installed: 0.7.1]`

**Comment by l0lawrence** [comment]
Hi @ttorsteinbo thanks for the feedback. We will get back to you asap.

**Comment by msyyc** [comment]
Hi @ttorsteinbo, mgmt SDK can't downgrade dependency so I think it is better to open issue in https://github.com/microsoft/azure-devops-python-api/issues for a new release with higher version of msrest
