### ISSUE TITLE
score.py not found error

### ISSUE THREAD

**Issue by sujithaleshwaram99** [Azure/azure-sdk-for-python#26295]
>Description
I have was trying to deploy model to endpoint using python sdk . For this I have given Model, Environment and Score.py but when I passed code and scoring_script arguments to CodeConfiguration function error displayed as shown below. Also, I tried to pass code_path and scoring_script to ManagedOnlineDeployment but still no luck. Please Kindly fix it. I would really appreciate if this issue gets resolved.
___________________________________________________________________________________________________________________________________________________________________

>Error Image
![image](https://user-images.githubusercontent.com/67188427/191070816-623be2b1-47e9-4acd-af07-4ee4a4ac34d2.png)

___________________________________________________________________________________________________________________________________________________________________

  > Check: endpoint ManagedOnlineEndpoint({'public_network_access': 'Enabled', 'provisioning_state': 'Succeeded', 'scoring_uri': 'https://managed-01.eastus2.inference.ml.azure.com/score', 'swagger_uri': 'https://managed-01.eastus2.inference.ml.azure.com/swagger.json', 'name': 'managed-01', 'description': 'this online endpoint is to test MLOps', 'tags': {'created': 'Sujith'}, 'properties': {'azureml.onlineendpointid': '/subscriptions/eb5a257a-76e2-472d-9fdc-7f9b3172fcf6/resourcegroups/rg-kdevops-dev/providers/microsoft.machinelearningservices/workspaces/amlmlopspockgl02/onlineendpoints/managed-01', 'AzureAsyncOperationUri': 'https://management.azure.com/subscriptions/eb5a257a-76e2-472d-9fdc-7f9b3172fcf6/providers/Microsoft.MachineLearningServices/locations/eastus2/mfeOperationsStatus/oe:5681d05d-12b4-4b28-88c0-f7713367da4e:0672352b-25b2-4ff8-922f-09dd564b16f3?api-version=2022-02-01-preview'}, 'id': '/subscriptions/eb5a257a-76e2-472d-9fdc-7f9b3172fcf6/resourceGroups/rg-kdevops-dev/providers/Microsoft.MachineLearningServices/workspaces/amlmlopspockgl02/onlineEndpoints/managed-01', 'Resource__source_path': None, 'base_path': '/mnt/batch/tasks/shared/LS_root/mounts/clusters/saleshwaram1/code/Users/saleshwaram', 'creation_context': None, 'serialize': <msrest.serialization.Serializer object at 0x7f8cccdf5580>, 'auth_mode': 'key', 'location': 'eastus2', 'identity': <azure.ai.ml._restclient.v2022_02_01_preview.models._models_py3.ManagedServiceIdentity object at 0x7f8cccd13850>, 'traffic': {}, 'mirror_traffic': {}, 'kind': 'Managed'}) exists
  ---------------------------------------------------------------------------
  ResourceNotFoundError                     Traceback (most recent call last)
  Input In [54], in <cell line: 36>()
       24 # ml_client.begin_create_or_update(endpoint)
       25 blue_deployment = ManagedOnlineDeployment(
       26 name="blue",
       27 endpoint_name=endpoint,
     (...)
       34 instance_count=1
       35 )
  ---> 36 ml_client.online_deployments.begin_create_or_update(deployment=blue_deployment)
  
  File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/ai/ml/_telemetry/activity.py:258, in monitor_with_activity.<locals>.monitor.<locals>.wrapper(*args, **kwargs)
      255 @functools.wraps(f)
      256 def wrapper(*args, **kwargs):
      257     with log_activity(logger, activity_name or f.__name__, activity_type, custom_dimensions):
  --> 258         return f(*args, **kwargs)
  
  File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/ai/ml/operations/_online_deployment_operations.py:102, in OnlineDeploymentOperations.begin_create_or_update(self, deployment, local, vscode_debug, no_wait)
      100 # This get() is to ensure, the endpoint exists and fail before even start the deployment
      101 module_logger.info(f"Check: endpoint {deployment.endpoint_name} exists")
  --> 102 self._online_endpoint_operations.get(
      103     resource_group_name=self._resource_group_name,
      104     workspace_name=self._workspace_name,
      105     endpoint_name=deployment.endpoint_name,
      106 )
      107 orchestrators = OperationOrchestrator(
      108     operation_container=self._all_operations,
      109     operation_scope=self._operation_scope,
      110 )
      112 upload_dependencies(deployment, orchestrators)
  
  File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/core/tracing/decorator.py:78, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
       76 span_impl_type = settings.tracing_implementation()
       77 if span_impl_type is None:
  ---> 78     return func(*args, **kwargs)
       80 # Merge span is parameter is set, but only if no explicit parent are passed
       81 if merge_span and not passed_in_parent:
  
  File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/ai/ml/_restclient/v2022_02_01_preview/operations/_online_endpoints_operations.py:669, in OnlineEndpointsOperations.get(self, resource_group_name, workspace_name, endpoint_name, **kwargs)
      666 response = pipeline_response.http_response
      668 if response.status_code not in [200]:
  --> 669     map_error(status_code=response.status_code, response=response, error_map=error_map)
      670     error = self._deserialize.failsafe_deserialize(_models.ErrorResponse, pipeline_response)
      671     raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
  
  File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/core/exceptions.py:107, in map_error(status_code, response, error_map)
      105     return
      106 error = error_type(response=response)
  --> 107 raise error
  
  ResourceNotFoundError: Operation returned an invalid status 'Not Found'
  Content: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
  <title>404 - File or directory not found.</title>
  <style type="text/css">
  
  </style>
  </head>
  <body>
  <div id="header"><h1>Server Error</h1></div>
  <div id="content">
   <div class="content-container"><fieldset>
    <h2>404 - File or directory not found.</h2>
    <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
   </fieldset></div>
  </div>
  </body>
  </html>

[https://github.com/Azure/azure-sdk-for-python/blob/05e3ab3066c2263a17f0767513f9639bc6579106/sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment.py](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87d3b2ab-2427-f3cc-1baa-b435cd785e9f
* Version Independent ID: 0c958e62-5d03-5f27-b731-bfa31100e8d0
* Content: [azure.ai.ml.entities.CodeConfiguration class](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.codeconfiguration?view=azure-python-preview&viewFallbackFrom=azure-ml-py)
* Content Source: [preview/docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.CodeConfiguration.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/preview/docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.CodeConfiguration.yml)
* GitHub Login: @VSC-Service-Account

**Comment by l0lawrence** [comment]
Hi @sujithaleshwaram99 thanks for the feedback, we'll investigate asap.

**Comment by luigiw** [comment]
@sujithaleshwaram99 Thx for reporting the issue. Can you share on how did you create the online endpoint you're referring to? You need to create an online endpoint before creating an online deployment. The error seems to be saying the online endpoint you're referring to doesn't exist.

**Comment by sujithaleshwaram99** [comment]
@luigiw , I have created online endpoint using below code snippet:
    # create an online endpoint
    endpoint = ManagedOnlineEndpoint(
        name=online_endpoint_name,
        description="this online endpoint is to test MLOps",
        auth_mode="key",
        tags={"created": "Sujith"},
    )

I got output like this once endpoint created:
ManagedOnlineEndpoint({'public_network_access': 'Enabled', 'provisioning_state': 'Succeeded', 'scoring_uri': 'https://managed-01.eastus2.inference.ml.azure.com/score', 'swagger_uri': 'https://managed-01.eastus2.inference.ml.azure.com/swagger.json', 'name': 'managed-01', 'description': 'this online endpoint is to test MLOps', 'tags': {'created': 'Sujith'}, 'properties': {'azureml.onlineendpointid': '/subscriptions/eb5a257a-76e2-472d-9fdc-7f9b3172fcf6/resourcegroups/rg-kdevops-dev/providers/microsoft.machinelearningservices/workspaces/amlmlopspockgl02/onlineendpoints/managed-01', 'AzureAsyncOperationUri': 'https://management.azure.com/subscriptions/eb5a257a-76e2-472d-9fdc-7f9b3172fcf6/providers/Microsoft.MachineLearningServices/locations/eastus2/mfeOperationsStatus/oe:5681d05d-12b4-4b28-88c0-f7713367da4e:0672352b-25b2-4ff8-922f-09dd564b16f3?api-version=2022-02-01-preview'}, 'id': '/subscriptions/eb5a257a-76e2-472d-9fdc-7f9b3172fcf6/resourceGroups/rg-kdevops-dev/providers/Microsoft.MachineLearningServices/workspaces/amlmlopspockgl02/onlineEndpoints/managed-01', 'Resource__source_path': None, 'base_path': '/mnt/batch/tasks/shared/LS_root/mounts/clusters/saleshwaram1/code/Users/saleshwaram', 'creation_context': None, 'serialize': <msrest.serialization.Serializer object at 0x7f8cccd47a30>, 'auth_mode': 'key', 'location': 'eastus2', 'identity': <azure.ai.ml._restclient.v2022_02_01_preview.models._models_py3.ManagedServiceIdentity object at 0x7f8cc7c6f730>, 'traffic': {}, 'mirror_traffic': {}, 'kind': 'Managed'})

**Comment by luigiw** [comment]
@sujithaleshwaram99 thank you. Can you double check that the `endpoint_name` you set in the OnlineDeployment object is the name string of the endpoint you created? It seems you're passing in the endpoint object as `endpoint_name`?

**Comment by sujithaleshwaram99** [comment]
@luigiw I have changed endpoint object to endpoint name it's working. Thank you. I appreciate the support.
