### ISSUE TITLE
[azure-core] Add x-ms-error-code in http logging policy

### ISSUE THREAD

**Issue by mumurug-MSFT** [Azure/azure-sdk-for-python#26331]
**Is your feature request related to a problem? Please describe.**
There is a allow-list defined in azure.core [here ](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L360) and all other headers are redacted like 

System.Exception :     'x-ms-error-code': 'REDACTED',    'x-ms-error-code': 'REDACTED'    End of inner exception    

**Describe the solution you'd like**
Can we add x-ms-error-code to allow-list? This would be very useful for users to debug and understand the exception better.

Also, please change the variable name "DEFAULT_HEADERS_WHITELIST" to "DEFAULT_HEADERS_ALLOWLIST" as per [Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/whitelist).

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by l0lawrence** [comment]
Hi @mumurug-MSFT thank you for the feedback, we will get back to you asap.

**Comment by lmazuel** [comment]
@mumurug-MSFT this will go in the next azure-core release in January. Thanks!
