### ISSUE TITLE
No Metadata in BlobProperties 

### ISSUE THREAD

**Issue by hedu42** [Azure/azure-sdk-for-python#26355]
- **Package Name**: 
azure-storage-blob
- **Package Version**:
12.13.1
- **Operating System**:
Windows 10
- **Python Version**:
3.9.2

**Describe the bug**
BlobProperties objects returned when iterating over ContainerClient.list_blobs() do not contain metadata information of the blobs

**To Reproduce**
cc = ContainerClient.from_container_url(container_url=someurl)
for blob in cc.list_blobs():
    empty = blob.metadata['somekey']
    notEmpty = cc.get_blob_client(blob.name).get_blob_properties().metadata['somekey']

**Expected behavior**
The BlobProperties objects returned from ContainerClient.list_blobs() are identical to what is returned by ContainerClient.get_blob_client(blobname).get_blob_properties().

**Comment by l0lawrence** [comment]
Hi @hedu42 thanks for the feedback, we'll get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @hedu42, the `list_blobs` API does not return all properties, including metadata, by default. You need to explicitly ask for it using the `include` parameter (see [Doc](https://github.com/Azure/azure-sdk-for-python/blob/fcba1069c2df580246329b61b8510c4f3342329b/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L765)). There are a few options including one to include metadata.

Something like this should do the trick:
```py
cc = ContainerClient.from_container_url(container_url=someurl)
for blob in cc.list_blobs(include=['metadata']):
    ...
```
