### ISSUE TITLE
How to define a Content Id on an attachment using azure-communication-email?

### ISSUE THREAD

**Issue by exegonzalez** [Azure/azure-sdk-for-python#26361]
I need to add an image in base64 format as an attachment and define a Content Id to reference it in an `<img src="cid:myimagecid">` tag in the mail template. EmailAttachment only allows to define:
```
attachment = EmailAttachment(
    name="...",
    attachment_type="...",
    content_bytes_base64=...
)
```
Is there any way to define that Content Id in the attachment?
Thanks.

**Comment by l0lawrence** [comment]
Hi @exegonzalez thanks for the question, I will pass this off to @turalf

**Comment by navba-MSFT** [comment]
@exegonzalez Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@exegonzalez AFAIK, this is not available now. However, This ask has been tracked here https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/issues/51 So please track the status updates there.
