### ISSUE TITLE
Azure SDK for Python Quota Management

### ISSUE THREAD

**Issue by Mr-MSFT** [Azure/azure-sdk-for-python#26378]
There is no example documentation on how to use the Quota Management module of the Python for Azure SDK. Documentation should be created to demonstrate the use of the Quota module. The current documentation (https://github.com/Azure/azure-sdk-for-python/tree/azure-mgmt-quota_1.0.0b2/sdk/quota/azure-mgmt-quota) lacks any details specific Quota module.

**Comment by l0lawrence** [comment]
Hi @Mr-MSFT thanks for the feedback, we'll get back to you asap.

**Comment by msyyc** [comment]
We will add sample for quota soon.

**Comment by Mr-MSFT** [comment]
Yuchao,

Do you have an ETA?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by msyyc** [comment]
maybe 1~2 week

**Comment by Mr-MSFT** [comment]
@msyyc Any updates on the ETA for this?

**Comment by msyyc** [comment]
draft PR: https://github.com/Azure-Samples/azure-samples-python-management/pull/107
