### ISSUE TITLE
Uploading blob using Akamai CDN with overwrite=False fails with AuthenticationFailed

### ISSUE THREAD

**Issue by JeffreyCA** [Azure/azure-sdk-for-python#26381]
- **Package Name**: `azure-storage-blob`
- **Package Version**: 12.13.1
- **Operating System**: Windows 11
- **Python Version**: 3.10

**Describe the bug**
When uploading any blob to a storage account (with overwrite=False) using an Akamai CDN as the account URL, the upload request fails with an authentication error. This does not happen with any other CDN type.

**To Reproduce**
Create an Akamai CDN with default settings and run repro program below:

```py
from azure.storage.blob import BlobServiceClient

ACCOUNT_URL_CDN = "https://akamaicdn.azureedge.net"
ACCOUNT_NAME = "azstoragename"
ACCOUNT_KEY =  ""
CONTAINER_NAME = "media"

credential = { "account_name": ACCOUNT_NAME, "account_key": ACCOUNT_KEY }

blob_service_client = BlobServiceClient(
            account_url=ACCOUNT_URL_CDN,
            credential=credential,
)

blob_client = blob_service_client.get_blob_client(
            container=CONTAINER_NAME,
            blob=f'testblob.txt')

with open("myfile.txt", "rb") as stream:
    blob_client.upload_blob(stream, overwrite=False)
```

This throws the following error:

```txt
Traceback (most recent call last):
  File "C:\Users\Public\Documents\Dev\sdk-repro\support2.py", line 20, in <module>
    blob_client.upload_blob(stream, overwrite=False)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\storage\blob\_blob_client.py", line 731, in upload_blob
    return upload_block_blob(**options)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\storage\blob\_upload_helpers.py", line 197, in upload_block_blob
    process_storage_error(error)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:965c2fcb-f01e-0005-4509-ce90d6000000
Time:2022-09-21T22:26:27.5831524Z
ErrorCode:AuthenticationFailed
authenticationerrordetail:The MAC signature found in the HTTP request 'yVlyxxi9bDfelc5IRzqnhLDkYzgto/5bg/bqpLxO/8k=' is not the same as any computed signature. Server used following string to sign: 'PUT


5

application/octet-stream






x-ms-blob-type:BlockBlob
x-ms-client-request-id:6ed97100-39fc-11ed-88dc-6045bdae7cfa
x-ms-date:Wed, 21 Sep 2022 22:26:27 GMT
x-ms-version:2021-08-06
/jcastorage2/media/testblob.txt'.
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:965c2fcb-f01e-0005-4509-ce90d6000000
Time:2022-09-21T22:26:27.5831524Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'yVlyxxi9bDfelc5IRzqnhLDkYzgto/5bg/bqpLxO/8k=' is not the same as any computed signature. Server used following string to sign: 'PUT


5

application/octet-stream






x-ms-blob-type:BlockBlob
x-ms-client-request-id:6ed97100-39fc-11ed-88dc-6045bdae7cfa
x-ms-date:Wed, 21 Sep 2022 22:26:27 GMT
x-ms-version:2021-08-06
/jcastorage2/media/testblob.txt'.</AuthenticationErrorDetail></Error>
```

**Expected behavior**
Request should succeed if blob doesn't already exist, otherwise it should throw `BlobAlreadyExists`.

**Additional context**
I did some deeper investigation using Fiddler to inspect the PUT requests and narrowed it down to the `If-None-Match: *` header, which gets added to the upload HTTP request if `overwrite=False` and none of the `modified_access_conditions` are set:

https://github.com/Azure/azure-sdk-for-python/blob/935bdcd67260f9141ed4f8708ae5a04cc4d63630/sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py#L80-L81

`string_to_sign` from Python SDK:

```
PUT


4

application/octet-stream



*


x-ms-blob-content-disposition:attachment
x-ms-blob-content-type:application/json
x-ms-blob-type:BlockBlob
x-ms-client-request-id:a9d8ff41-3976-11ed-9d5e-6045bdae7cfa
x-ms-date:Wed, 21 Sep 2022 06:28:53 GMT
x-ms-version:2021-08-06
/jcastorage2/media/uploads/New_Text_.json
timeout:60
```

String that the server is checking against:
```
PUT


4

application/octet-stream






x-ms-blob-content-disposition:attachment
x-ms-blob-content-type:application/json
x-ms-blob-type:BlockBlob
x-ms-client-request-id:a9d8ff41-3976-11ed-9d5e-6045bdae7cfa
x-ms-date:Wed, 21 Sep 2022 06:28:53 GMT
x-ms-version:2021-08-06
/jcastorage2/media/uploads/New_Text_.json
timeout:60
```

Note how the `If-None-Match` header value (`*`) is not present in the latter.

Is this something that can be addressed on the client side to not send those headers? The legacy Python SDK (2.1.0) doesn't have this issue as the `If-None-Match` header is not sent by default. It's not clear what the workaround is if `overwrite` is set to `False`.

**Comment by jalauzon-msft** [comment]
Hi @JeffreyCA, we were able to verify this issue. It seems that the Akamai CDN is dropping the `If-None-Match` header when forwarding the request to the Storage service. Unfortunately, there is not much we can do about this from the client side, but you can try opening a support request on your CDN (or maybe Storage Account) or reaching out to whatever teams owns the CDN internally.

There may be some difficulties getting any traction here though as uploading data through a CDN is not really a normal/supported scenario. Usually, the purpose of a CDN to download (unauthenticated) data with the added functionality of caching and geo-local availability. Why are you trying to upload through the CDN? It may make sense to use the regular Storage account URL to upload and the CDN for download purposes only.

The `If-None-Match` header is needed when `overwrite=False` as, without that, the [PutBlob API](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob) which backs the `upload_blob` method will overwrite the blob. The `If-None-Match` is the only thing that prevents the blob from being overwritten in this case.

A possible workaround could be to check for existence of the blob using `exists` or `get_blob_properties` and then only calling upload (with `overwrite=True`) if the blob does not exist.

**Comment by JeffreyCA** [comment]
Thanks, appreciate the update. I originally discovered this issue through a recent update in django-storages which changed how the blob client connected to custom URLs. We made a fix there to ensure uploads and similar operations go through the storage endpoint instead.
