### ISSUE TITLE
error in Authenticate the client

### ISSUE THREAD

**Issue by JingchaoZhang** [Azure/azure-sdk-for-python#26394]
[Enter feedback here]

This code block 
ml_client = MLClient(
    DefaultAzureCredential(), subscription_id, resource_group, workspace
)
should be revised to
ml_client = MLClient(
    DefaultAzureCredential(), subscription_id, resource_group_name, workspace_name
)

The original code gives the error below:
TypeError: __init__() missing 1 required positional argument: 'resource_group_name

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4bd3893-7980-57f3-c1a7-28b5ddc6931b
* Version Independent ID: 70e9f892-5b42-b888-1881-5ba039c260b1
* Content: [Azure ML Package client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/ai-ml-readme?view=azure-python-preview)
* Content Source: [docs-ref-services/preview/ai-ml-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/ai-ml-readme.md)
* Service: **ml**
* GitHub Login: @azureml-github
* Microsoft Alias: **azureml-github**

**Comment by luigiw** [comment]
@JingchaoZhang Thx for reporting this. Are you referencing a block of sample code somewhere? Can you share a link to the sample code?

**Comment by JingchaoZhang** [comment]
I was referring to the code block on this page: Azure ML Package client library for Python | Microsoft Learn<https://learn.microsoft.com/en-us/python/api/overview/azure/ai-ml-readme?view=azure-python-preview>

Here is a screenshot:
[cid:745e0788-84c2-4d31-a00b-63e612834368]

According to the MLClient Class page, the correct parameter name should be resource_group_name and workspace_name.
azure.ai.ml.MLClient class | Microsoft Learn<https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.mlclient?view=azure-python-preview>
[cid:1d284530-6e98-4589-bfec-9c5d6c5f1f6a]

Jingchao


---

Jingchao Zhang

Sr. TPM | Azure HPC & AI CSI

Azure Engineering | Microsoft Corporation

________________________________

**Comment by luigiw** [comment]
@JingchaoZhang thx for your feedback. subscription_id, resource_group, workspace are refereeing to local variables one should define in advance.
