### ISSUE TITLE
Content-MD5 header does not validate properly for blob uploads in chunks

### ISSUE THREAD

**Issue by maximz** [Azure/azure-sdk-for-python#264]
I would like to use MD5 validation to ensure my data survives transport when I upload blobs to Azure storage. Per the documentation, I supply a content-MD5 header along with my upload, so that the service validates the incoming file against this header.

This works great for small files. **But once I try to upload files that require chunked uploads -- e.g. I'm currently trying to upload a 1GB file -- the validation is always unsuccessful.** I'm using `BlobService.put_block_blob_from_path(...)` for the upload.

For reference, here is how I calculate the MD5 locally and pass it along with my upload.

```
# md5 generation for validating uploads
import hashlib
def md5_for_file(f, block_size=2**20):
    md5 = hashlib.md5()
    while True:
        data = f.read(block_size)
        if not data:
            break
        md5.update(data)
    return md5.digest().encode('base64')[:-1] 
    
# do the uploads, with file path p
for p in paths:
    blob_name = path_leaf(p)
    original_md5 = md5_for_file(open(p, 'rb'))
    blob_service.put_block_blob_from_path(storage_container_name, blob_name, p, content_md5=original_md5) # specify md5 to do an md5 check automatically
```

I get a WindowsAzureError when I run the above, due to the MD5 not validating properly:

```
Traceback (most recent call last):
  File "azureUpload.py", line 44, in <module>
    blob_service.put_block_blob_from_path(storage_container_name, blob_name, p, content_md5=original_md5) # specify md5 to do an md5 check automatically
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 764, in put_block_blob_from_path
    progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 861, in put_block_blob_from_file
    x_ms_lease_id)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 696, in put_blob
    self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 150, in _perform_request
    _storage_error_handler(ex)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/__init__.py", line 889, in _storage_error_handler
    return _general_error_handler(http_error)
  File "/usr/local/lib/python2.7/dist-packages/azure/__init__.py", line 931, in _general_error_handler
    http_error.respbody.decode('utf-8'))
azure.WindowsAzureError
```

# The issue

My local MD5 computation isn't the issue -- I've checked it against Azure with small uploads, and it produces the same result as md5sum for my 1GB file.

**How should big files be uploaded with MD5 validation?** It seems that the API should be changed so that MD5 is computed for each chunk.

# How to reproduce

Create a >64MB file using `dd if=/dev/urandom of=65M.random bs=1M count=65`, then upload it with the code above. You get the same traceback as I did.

But if you chop 20MB off that using `dd if=/dev/urandom of=45M.random bs=1M count=45`, we won't trigger chunking, and the upload succeeds, along with MD5 validation.

If you remove MD5 validation (don't specify `content_md5` parameter), both uploads succeed.

Thus, the issue lies with MD5 validation with files that trigger chunking.

**Comment by huguesv** [comment]
Thanks for letting us know about this issue.

The documentation for Put Block List REST API says:
"Note that this header is associated with the request content, and not with the content of the blob itself."

So passing in the MD5 of the whole blob to Put Block List is definitely the wrong thing to do.

We should calculate the MD5 for each chunk and pass it to Put Block (Put Blob in the case of no chunking), if the user wants validation.  The content\_md5 parameter should be changed to a Boolean, matching the behavior of the useTransactionalMD5 parameter used in Node.js SDK:
https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.js

All Page Blob and Block Blob APIs should be reviewed for this, both upload and download.

**Comment by maximz** [comment]
@huguesv Thanks for the update. Let me know if there's any further way I can help. (For now, I've just disabled MD5 verification in my code)

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/11
