### ISSUE TITLE
[azure-mgmt-security] Defender pricings uses old API version, missing useful field

### ISSUE THREAD

**Issue by aeetos** [Azure/azure-sdk-for-python#26403]
- **Package Name**: azure.mgmt.security
- **Package Version**: 1.0.0
- **Operating System**: MacOS
- **Python Version**: 3.9

**Describe the bug**
The PricingOperations class in operations/_pricings_operations.py is hard-coded to API version 2018-06-01 and cannot be overridden. This API version is missing useful fields such `properties.subPlan` which can be important to determine service level and overall cost of covered resources by products such as Defender for Cloud. The currently published API version 2022-03-01 has this field.

Reference: [API docs](https://learn.microsoft.com/en-us/rest/api/defenderforcloud/pricings/get?tabs=HTTP)

**To Reproduce**
```
from azure.mgmt.security import SecurityCenter
sec_client = SecurityCenter(credential, subscription_id, '')
pricings = sec_client.pricings.list()
pricings.as_dict()
```

**Expected behavior**
Return results with the subPlan field.

**Additional Context**
Unsure if this is in context for the architecture of this SDK, but I would expect to be able to override the API version and still have the SDK make the API call and give me raw results. If that is not how the SDK is designed, I think it's worth considering and I'll file a feature request just for that.

**Comment by SaurabhSharma-MSFT** [comment]
@aeetos We are looking into it and get back to you for any additional information.

**Comment by Wzb123456789** [comment]
Hi @aeetos 

According to my investigation, you can get information including `subPlan` field using:
```python
pricings = sec_client.pricings.list().value
for item in pricings:
    print(item)
```
Hope it can help you
