### ISSUE TITLE
[doc] example how to instanciate the classe `ProvidersOperations(client, config, serializer, deserializer)`

### ISSUE THREAD

**Issue by copdips** [Azure/azure-sdk-for-python#26425]
Hello, 

I need to get all the providers of a subscription, in order to get the available `apiVersions` of each resource, because I'm writing some scripts that need to work with different Azure resources, that needs different apiVersions, for example: `resource_client.resources.get_by_id()`.

From azcli, it's as simple as `az  provider list`

It seems that the same thing from Python SDK is to use the `list` method of the class `ProvidersOperations`:
https://learn.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.resources.v2021_04_01.operations.providersoperations?view=azure-python

But I cannot figure out how to set the parameters of this class: `ProvidersOperations(client, config, serializer, deserializer)`, could you please provide some concret examples ? The online [doc ](https://learn.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.resources.v2021_04_01.operations.providersoperations?view=azure-python) is a little bit too concise for me:

```bash
Parameters
`client`
Required
Client for service requests.

`config`
Required
Configuration of service client.

`serializer`
Required
An object model serializer.

`deserializer`
Required
An object model deserializer.
```

**Comment by mccoyp** [comment]
Hi @copdips, thank you for opening an issue! I'll tag some folks who should be able to help, and we'll get back to you as soon as possible.

**Comment by msyyc** [comment]
Hi @copdips please refer to https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/resources/manage_providers.py
