### ISSUE TITLE
Sudden error with no change of code, data or sdk versions - Failed to upload outputs due to: Failure in UpdateRun while calling service RunHistory

### ISSUE THREAD

**Issue by edgBR** [Azure/azure-sdk-for-python#26433]
**Bug description**

A hyperdrive step which previously was working without any issue has started to fail. There has been no change of code, no change of data, no change of azureml sdk version, no change of anything.

Error is as follows:

![image](https://user-images.githubusercontent.com/14976422/192118281-7e65997e-bada-414d-9c46-407c4aa43f52.png)

`Failed to upload outputs due to: Failure in UpdateRun while calling service RunHistory; HttpMethod: PATCH; Response StatusCode: BadRequest; Exception type: Microsoft.RelInfra.Extensions.HttpRequestDetailException|-Microsoft.RelInfra.Common.Exceptions.ErrorResponseException`

The hyperdrive job works well:

![image](https://user-images.githubusercontent.com/14976422/192118303-4ed4ad48-18dc-4658-bd08-ecf080d1b13c.png)

And the trial worked:

![image](https://user-images.githubusercontent.com/14976422/192118322-b3f9fa3a-03e7-45a0-8071-1568ba67d2f2.png)

I suspect that maybe the problem is related with the high amount of input datasets I have as I add to implement a workaround for this #26329

Any help is welcome.

**Comment by mccoyp** [comment]
Hi @edgBR, thank you for opening an issue (and providing extra context with a linked issue)! I'll tag some folks who should be able to help, and we'll get back to you as soon as possible.

**Comment by mccoyp** [comment]
Tagging @azureml-github for awareness.

**Comment by luigiw** [comment]
@wangchao1230 can you help to triage this issue? Thank you.

**Comment by wangchao1230** [comment]
@edgBR Does this issue constantly repo? It may be related to some transient server issue at that time.

Could you share the pipeline run id/name to us?
