### ISSUE TITLE
Incorrect requirement for azure.mgmt.compute

### ISSUE THREAD

**Issue by ageorgou** [Azure/azure-sdk-for-python#2644]
It seems that the version requirement for `azure-common~=1.1` in `azure.mgmt.compute` is too broad: new versions of the package reference `azure.profiles`, which was introduced in `azure-common` 1.1.9.

For example, if I try to install the latest version (4.0.0rc2) of `azure.mgmt.common` in an environment which already has a previous, older version of `azure-common`, the installation completes successfully but I can't import anything from the new package.

Steps to reproduce:
1. From a clean environment, install an older version of `azure-common`, then install the latest `azure.mgmt.compute` from source.
```bash
pip install "azure-common<=1.1.8"
git clone https://github.com/Azure/azure-sdk-for-python.git
pip install azure-sdk-for-python/azure-mgmt-compute
```

2. In a Python console, import the new package.
```python
>>> import azure.mgmt.compute
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ageorgou/anaconda/envs/test-azure/lib/python3.6/site-packages/azure/mgmt/compute/__init__.py", line 8, in <module>
    from .compute_management_client import ComputeManagementClient
  File "/Users/ageorgou/anaconda/envs/test-azure/lib/python3.6/site-packages/azure/mgmt/compute/compute_management_client.py", line 16, in <module>
    from azure.profiles import KnownProfiles, ProfileDefinition
ModuleNotFoundError: No module named 'azure.profiles'
```

Expected behaviour is for the import to work, as it successfully does with newer (>=1.1.9) versions of `azure-common`.

**Comment by lmazuel** [comment]
Hi @ageorgou 
Yes you're right, I should write `~=1.1;>=1.1.9`. I didn't notice since I do fresh env each time, but on update it won't work. Will fix it asap. Thanks!

**Comment by ageorgou** [comment]
Hi @lmazuel,

Yes, I only noticed this when updating an existing installation.

I was looking at this again and realised that it happens in other packages too. A quick search (`grep "azure.profiles"`) shows:
- `azure-mgmt-compute`
- `azure-mgmt-resource`
- `azure-mgmt-storage`
- `azure-mgmt-network`
- `azure-mgmt-containerregistry`

The last two already require specific versions. I have submitted a PR for the other three in case that makes things easier, but please feel free to ignore it if not!

**Comment by lmazuel** [comment]
Hi @ageorgou 
I released storage this morning including the fix, so your PR conflicts :/. If you could remove storage from your PR, I'll merge it.
Thanks!

**Comment by ageorgou** [comment]
Hi @lmazuel, done now.
