### ISSUE TITLE
Files Data Lake samples issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#26442]
1.

Section [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/samples/datalake_samples_instantiate_client_async.py#L37):

![image](https://user-images.githubusercontent.com/80307197/192207998-e950815d-cc19-43a9-815b-03146041d943.png)

Reason:
NameError: name 'run' is not defined.

Suggestion:
Change `main()` to `run()`.

@lmazuel , @kyle-patterson , @kasobol-msft , @ro-joowan for notification.

**Comment by vincenttran-msft** [comment]
Hi @AFengKK Rudy, thanks for bringing this to our attention. I will make the necessary changes and address the problem in a PR to come 😄 
Thanks!
