### ISSUE TITLE
Communication Identity Readme issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#26443]
1.

Section [link](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-identity#examples):

![image](https://user-images.githubusercontent.com/80307197/192207014-d110fb93-9b81-476b-b117-aaafdc395cc5.png)

Reason:
Jump link error for code snippets of exammples.

Suggestion:
Add link to: `(#exchanging-azure-ad-access-token-of-a-teams-user-for-a-communication-identity-access-token)`

@lmazuel , @mayurid , @acsdevx-msft , @johanste for notification.

**Comment by mccoyp** [comment]
Tagging @turalf for awareness.
