### ISSUE TITLE
Python API document not accurate

### ISSUE THREAD

**Issue by kexugit** [Azure/azure-sdk-for-python#26450]
- **Package Name**:  msrestazure 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Python API ref document has typo and is not clear on measurement unit. 

**To Reproduce**
1. Go to https://learn.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_operation.azureoperationpoller?view=azure-python#msrestazure-azure-operation-azureoperationpoller-wait
2. Notice the description of 'timeout' parameter. It says: "Perion of time to wait for the long running operation to complete."

**Expected behavior**
Feedback from the doc page asked in what units is the parameter used. There also seems to be a typo ("Period" instead of "Perion")

**Screenshots**

**Additional context**

**Comment by lmazuel** [comment]
This code was used by our code generator alpha, and is no longer maintained nor used by any running code for at least 5 years. Given that, we don't plan to update the documentation as no customers can access this method anymore (no SDK will return this type anymore).
