### ISSUE TITLE
Outdated hyperlink on "Explore the Management APIs"

### ISSUE THREAD

**Issue by Cvaniak** [Azure/azure-sdk-for-python#26475]
### Outdated redirect  

On the bottom of this site there is button `Explore the Management APIs` which redirect to [this site](https://learn.microsoft.com/en-us/python/api/overview/azure/notificationhubs/management) which gives `404 error`. From what I see it should redirect to [this](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-notificationhubs-readme?view=azure-python) now.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7894a9aa-d9e7-1c81-52d9-a24dffdbec43
* Version Independent ID: cb4f4205-dc9b-b681-0f54-2d08211394dd
* Content: [Azure Notification Hubs SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/notification-hubs?view=azure-python)
* Content Source: [docs-ref-services/latest/notification-hubs.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/notification-hubs.md)
* Service: **notificationhubs**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by mccoyp** [comment]
Hi @Cvaniak, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible.

**Comment by msyyc** [comment]
Fix PR: https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1630

**Comment by xiangyan99** [comment]
Given the PR is merged. Marked as resolved.
