### ISSUE TITLE
Add support for coreOS

### ISSUE THREAD

**Issue by rboorgapally** [Azure/azure-sdk-for-python#265]
The following azure documentation uses azure xplat cli.

http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-coreos-how-to/

But, I don't see any support for coreOS in python SDK. When can we expect this feature?

**Comment by huguesv** [comment]
Looking at the linked document, I think the python SDK supports all the necessary APIs.

create_hosted_service
add_service_certificate
create_virtual_machine_deployment (for the first vm)
add_role (for additional vms)

The custom data is passed in via the custom_data field on the LinuxConfigurationSet class. Set it to the *contents* of the cloud-config.yaml file.

We'll look at adding more documentation for creating vms in the near future.

**Comment by huguesv** [comment]
You might want to take a look at this:
https://github.com/chanezon/azure-linux/tree/master/coreos/cluster
