### ISSUE TITLE
[Communication] Migrate tests to use the test proxy

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#26512]
Following the example of [`azure-communication-email`](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-email/tests), the remaining data-plane Communication packages need to migrate their tests to use the test proxy.

As described in the [Test proxy migration guide](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/test_proxy_migration_guide.md), the test proxy is a replacement for the current `vcrpy`-based test recording system. Aside from a new dependency on Docker (or [Podman](https://podman.io/)), the testing workflow with the test proxy is the same as the one today.

Migrating to the test proxy by early October is necessary to enable: 1. removing legacy testing infrastructure in the repository; 2. moving test recordings out of the `azure-sdk-for-python` repository.

**EDIT:** due to a recent improvement, Docker/Podman are no longer a dependency to use the test proxy.

**Comment by mccoyp** [comment]
`azure-communication-identity` was migrated with https://github.com/Azure/azure-sdk-for-python/pull/27469.

**Comment by danielortega-msft** [comment]
The PR for `azure-communication-phonenumbers` is currently open: https://github.com/Azure/azure-sdk-for-python/pull/27876

**Comment by mccoyp** [comment]
Update: most Communication libraries have been migrated to the test proxy, but [azure-communication-chat](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-chat), [azure-communication-networktraversal](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-networktraversal), and [azure-communication-rooms](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-rooms) still have YAML (vcrpy-formatted) recording files.

**Comment by mccoyp** [comment]
Update: `azure-communication-rooms` was also recently migrated via https://github.com/Azure/azure-sdk-for-python/pull/30217

**Comment by mccoyp** [comment]
Chat and Network Traversal have been migrated in https://github.com/Azure/azure-sdk-for-python/pull/30552 and https://github.com/Azure/azure-sdk-for-python/pull/30843, respectively -- meaning we can close this issue!
