### ISSUE TITLE
Strange digital twin ID when upserting a digital twin

### ISSUE THREAD

**Issue by gs9824** [Azure/azure-sdk-for-python#26537]
- **Package Name**: azure.digitaltwins.core
- **Package Version**: 1.2.0
- **Operating System**: Windows
- **Python Version**: 3.7

**Describe the bug**
Creating a digital twin via the upsert_digital_twin in python yields a strang $dtId

**To Reproduce**

    def CreateCustomer (CustomerName):   
        digital_twin_id=CustomerName,
        temporary_twin = {
        "$metadata": {
            "$model": 'dtmi:digitaltwins:DataEngine:customer;1'
        },
        "$dtId": digital_twin_id,
        "CustomerName": CustomerName
    }
    
    created_twin = service_client.upsert_digital_twin(digital_twin_id, temporary_twin)
    return created_twin

CreateCustomer("Test")

result is a number of strange characters in the $dtId field 

{'$dtId': "('Test',)",
 '$etag': 'W/"f4f8986d-52f7-476b-b558-7a9e4bdaabdd"',
 'CustomerName': 'Test',
 '$metadata': {'$model': 'dtmi:digitaltwins:DataEngine:customer;1',
  '$lastUpdateTime': '2022-09-29T08:11:01.5730059Z',
  'CustomerName': {'lastUpdateTime': '2022-09-29T08:11:01.5730059Z'}}}

**Expected behavior**
{'$dtId': "Test",
 '$etag': 'W/"f4f8986d-52f7-476b-b558-7a9e4bdaabdd"',
 'CustomerName': 'Test',
 '$metadata': {'$model': 'dtmi:digitaltwins:DataEngine:customer;1',
  '$lastUpdateTime': '2022-09-29T08:11:01.5730059Z',
  'CustomerName': {'lastUpdateTime': '2022-09-29T08:11:01.5730059Z'}}}

When using the [explorer ] (https://explorer.digitaltwins.azure.net/), these strange characters do not appear

**Screenshots**

**Additional context**

**Comment by mccoyp** [comment]
Hi @gs9824, thank you for opening an issue! I'll tag some folks who should be able to help, and we'll get back to you as soon as possible.

**Comment by navba-MSFT** [comment]
Adding Service team to assist on this.

**Comment by navba-MSFT** [comment]
@johngallardo, @ashish93-stack, @sjiherzig, @Satya-Kolluri Could you please look into this issue and provide an update ?

**Comment by johngallardo** [comment]
@gs9824 - I believe the issue is the comma on this line:
```
    digital_twin_id=CustomerName,
```

That creates a tuple of CustomerName ... which serializes as a string as ("ABC",) in your case. I believe you should remove the comma at the end of that line. Please reactivate if that isn't the case and I am misinterpreting something.

**Comment by gs9824** [comment]
@johngallardo sorry for the late response.
I can confirm that is/was indeed the issue. Thank you for the solution.

**Comment by github-Hesham** [comment]
- [•] -
