### ISSUE TITLE
Request: Include Enum for Types of Data Flows in the Data Factory 

### ISSUE THREAD

**Issue by mindlessroman** [Azure/azure-sdk-for-python#26542]
**Is your feature request related to a problem? Please describe.**
Instead of needing to expose a protected list of Data Flow types in `sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py` because it's bad practice to access protected properties/methods.

**Describe the solution you'd like**
It would be nice if there was an enum that was accessible `sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py`

**Describe alternatives you've considered**
Hardcoding the list is less desirable since things _could_ change in the future and that's more code to update elsewhere.

**Additional context**
n/a

**Comment by msyyc** [comment]
Hi @mindlessroman, you can import enum variable directly by `from azure.mgmt.datafactory.models import AmazonRdsForOraclePartitionOption` since it has been in `__all__` of `__init__.py`:
https://github.com/Azure/azure-sdk-for-python/blob/b061c2864632a7fc827f5320cadc8c98d2dd0586/sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py#L728-L733

**Comment by mindlessroman** [comment]
Hey @msyyc - I don't think that the enum exists right now. 

https://raw.githubusercontent.com/Azure/azure-sdk-for-python/main/sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py Line 18938:

> You probably want to use the sub-classes and not this class directly. Known sub-classes are:
    Flowlet, MappingDataFlow, WranglingDataFlow

An enum that contains those subtypes does not exist in `sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py`

Having these be in an Enum would be helpful for changes I'm trying to support in https://github.com/Azure/azure-cli-extensions/pull/5407.

**Comment by msyyc** [comment]
@mindlessroman SDK is generated with swagger. If you want to use these values as enum, there shall be relative enum definition in swagger. Unfortunately, I don't find it in swagger. So I advise you open an issue in https://github.com/Azure/azure-rest-api-specs/issues or make a PR to add it. (enum definition sample: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L5105-L5110)
