### ISSUE TITLE
Error load balancing port 80 between two virtual machines

### ISSUE THREAD

**Issue by rboorgapally** [Azure/azure-sdk-for-python#266]
Hi,

I wan to load balance two virtual machines on public port 80. The creation of the first virtual machine succeeded. But when I added the second virtual machine. I got the following error:

Port 80 is already in use by one of the endpoints in this deployment. Ensure that the port numbers are unique across endpoints within a deployment.

I am guessing this is because the SDK is based on old version of service management API. Is that right?

**Comment by huguesv** [comment]
Are you setting the load_balanced_endpoint_set_name field on the endpoint object?

**Comment by rboorgapally** [comment]
Thanks. That was helpful. Specifying the load_balanced_endpoint_set_name field worked.
