### ISSUE TITLE
InvalidContinuationToken when paginating results with azure-mgmt-compute

### ISSUE THREAD

**Issue by hussam-Tanium** [Azure/azure-sdk-for-python#26604]
**Package Name**: azure-mgmt-compute
**Package Version**: 28.0.1
**Operating System**: MacOS 12.6
**Python Version**: 3.8 and 3.9

**Describe the bug**
Operations in the ComputeManagementclient that require pagination are failing after upgrading the package to 28.0.0 and 28.0.1.

**To Reproduce**

1. Have a subscription with multiple pages of resources, in my case, VMs
2. Call `list_all()`

```
subscription_id = subscription.subscription_id
    compute_client = ComputeManagementClient(
            credential,
            subscription_id=subscription_id,
            api_version=compute_api_version
        )
        sub_vms = compute_client.virtual_machines.list_all()
        for vm in sub_vms:
            vm_id = vm.vm_id
```

**Expected behavior**
ComputeManagementClient.virtual_machines.list_all() should paginate successfully and return all resources.

**Screenshots**
Python 3.8and API version v2022-03-01

```
File "/tmp/tmpwe4ln3d0/my_script.py", line 164, in my_method
    for vm in sub_vms:
  File "/tmp/tmpwe4ln3d0/venv/lib/python3.8/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "/tmp/tmpwe4ln3d0/venv/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/tmp/tmpwe4ln3d0/venv/lib/python3.8/site-packages/azure/mgmt/compute/v2022_03_01/operations/_virtual_machines_operations.py", line 2263, in get_next
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidContinuationToken) Invalid continuation token in the request uri. Continuation token - 'continuation_token'
```

Python 3.9 and API version v2022-08-01

```
File "/Users/hussambteibet/PycharmProjects/zray_modules/modules/cloud_asset_inventory/azure_inventory.py", line 164, in get_subscription_data
    for vm in sub_vms:
  File "/Users/hussambteibet/PycharmProjects/zray_modules/venv/lib/python3.9/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "/Users/hussambteibet/PycharmProjects/zray_modules/venv/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/Users/hussambteibet/PycharmProjects/zray_modules/venv/lib/python3.9/site-packages/azure/mgmt/compute/v2022_08_01/operations/_virtual_machines_operations.py", line 2263, in get_next
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidContinuationToken) Invalid continuation token in the request uri. Continuation token - 'continuation_token'.

```

**Comment by jazelenk** [comment]
Any ETA? We require API version 2002-08-01, but neither 28.0.0 nor 28.0.1 are functional, and anything less than 28.x does not support that API version.

**Comment by jazelenk** [comment]
Are these generated using a different version of autorest than the 27.x packages? I see that in the newer packages, when paginating the new request is genreated by constructing HttpRequest directly, whereas in the 27.x packages the next request is generated with another call to build_xxx_request(). If I manually edit one of the list operations to do it the former way (calling build_xxx_request() again and passing template_url=next_link), it starts working.

**Comment by jazelenk** [comment]
Speculation: this autorest change https://github.com/Azure/autorest.python/pull/1307 may be related. It seems that the skiptoken escaping is getting mangled going through the new path.

**Comment by msyyc** [comment]
Thanks for your feedback and we will investigate it asap

**Comment by jazelenk** [comment]
You might try a trivial resource type that doesn't consume quota, such as capacity reservation group, dedicated host group, shared image gallery definition.

**Comment by hussam-Tanium** [comment]
Hello @msyyc , the last working version is 27.2.0

**Comment by msyyc** [comment]
> Hello @msyyc , the last working version is 27.2.0

Thanks! It is huge help for us and I will compare the two version to find root cause.

**Comment by msyyc** [comment]
Hi @hussam-Tanium 
Here is non-work code in 28.0.1: https://github.com/Azure/azure-sdk-for-python/blob/e3415c47d576d2c8f790d73854aa56cda82a9ffa/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2022_03_01/operations/_virtual_machines_operations.py#L2236-L2244
Here is work code in 27.2.0: https://github.com/Azure/azure-sdk-for-python/blob/1486a398c39cf9e2f1b7aa938a3e7e52f55fd6e1/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2022_03_01/operations/_virtual_machines_operations.py#L2275-L2287

**Comment by jazelenk** [comment]
@msyyc - I sent you e-mail with a local repro.

**Comment by hussam-Tanium** [comment]
@msyyc I have also sent you an email with the `next_link` value

**Comment by msyyc** [comment]
Hi @hussam-Tanium I find the error may be caused by urlencode and we fixed it: https://github.com/Azure/autorest.python/pull/1504. Could you help try the [private package](https://newstorageyyc.blob.core.windows.net/2022-10/sdk_pr_26805/azure_mgmt_compute-28.0.1-py3-none-any.whl)? Once it works well, we will release a public version.

**Comment by hussam-Tanium** [comment]
Hello @msyyc I will test it now

**Comment by hussam-Tanium** [comment]
Hello @msyyc I have confirmed that the package is working properly.

**Comment by msyyc** [comment]
fixed version is released : https://pypi.org/project/azure-mgmt-compute/29.0.0/
