### ISSUE TITLE
[Azure ML SDK v2] Registering Data Asset from Job output

### ISSUE THREAD

**Issue by tomasvanpottelbergh** [Azure/azure-sdk-for-python#26618]
**Is your feature request related to a problem? Please describe.**
The Azure ML SDK v1 provides the `register_on_complete` [method](https://learn.microsoft.com/en-us/azure/machine-learning/v1/how-to-create-machine-learning-pipelines#configure-data-with-dataset-and-outputfiledatasetconfig-objects) to register output datasets directly from the output of a step. Unfortunately the SDK v2 doesn't seem to provide any method to do the same.

**Describe the solution you'd like**
Ideally, the following code should work and register a new version of the Data Asset `test_output` or create it if it doesn't exist yet:
```
 from azure.ai.ml import command
 from azure.ai.ml.entities import Data
 from azure.ai.ml import Input, Output
 from azure.ai.ml.constants import AssetTypes
    
 my_job_outputs = {
     "prep_data": Output(type=AssetTypes.URI_FOLDER, path="azureml:test_output")
 }
    
 job = command(
     command="echo 'test' > ${
                 {outputs.prep_data}}",
     outputs=my_job_outputs,
     environment="test-env@latest",
     compute="cpu-cluster",
 )
    
 # submit the command
 returned_job = ml_client.create_or_update(job)
```

**Describe alternatives you've considered**
- I tried creating and registering Data Assets by using the SDK v2 within the Job code. This works, but has the disadvantage that the Data Asset will not have the metadata of the Job that created it.
- It is possible to manually register a Data Asset from a step output in the Azure ML Studio, but this prevents the complete automation of training / data preprocessing pipelines.

**Additional context**
The documentation would actually suggest that this is possible (see https://github.com/MicrosoftDocs/azure-docs/issues/98516), but it has been [confirmed](https://learn.microsoft.com/en-us/answers/questions/1011004/registering-data-asset-from-job-with-v2-sdkcli.html?childToView=1023035#comment-1023035) by @RohitMungi-MSFT that this is not yet implemented.

@azureml-github

**Comment by luigiw** [comment]
@tomasvanpottelbergh you don't need to register the job output as a data asset to use it as an input for another job. You can reference a job output by using pattern "azureml://jobs/<job-name>/outputs/<output-name>/paths/<path-to-your-artifacts>". Just use this pattern in `path` field of a job input. Does this help?

**Comment by tomasvanpottelbergh** [comment]
Thanks for the quick response @luigiw. I haven't used this path pattern yet, but instead the one in the overview tab of a pipeline step (under Outputs). This works, but doesn't really address my issue, since these paths are unpredictable because of the random job names. Therefore there is still a manual step involved to get the path to use as an input to another job.

What I would like to see is some functionality in the SDK v2 that can register datasets under a friendly and predictable name, such as is available in the Studio or in v1 of the SDK.

**Comment by cloga** [comment]
Hi @tomasvanpottelbergh ,
Output as named asset (parity feature of registered as in SDK v1) in our plan to support in following months. 

One more thing for this is you have mentioned the of the unpredictable child job name in the pipeline is:
you can promote the outputs of the steps to pipeline level, then you can refer this outputs to register data asset using pipeline job name which is return when you submit this pipeline job, instead the random step name system generated.

https://learn.microsoft.com/en-us/azure/machine-learning/reference-yaml-core-syntax#binding-inputs-and-outputs-between-steps-in-a-pipeline-job

**Comment by cloga** [comment]
Would you share more use cases why you need to register data asset then use in another job, instead of contain them in a single pipeline job as multi-steps?

**Comment by tomasvanpottelbergh** [comment]
> Hi @tomasvanpottelbergh , Output as named asset (parity feature of registered as in SDK v1) in our plan to support in following months.

That's great to hear @cloga!

> One more thing for this is you have mentioned the of the unpredictable child job name in the pipeline: you can promote the outputs of the steps to pipeline level, then you can refer this outputs to register data asset using pipeline job name which is return when you submit this pipeline job, instead the random step name system generated.

Thanks, that's useful indeed. Is there also a way to register these outputs as a "proper" named data asset using the SDK (outside of the pipeline)? That would be a decent workaround in the meantime.

> Would you share more use cases why you need to register data asset then use in another job, instead of contain them in a single pipeline job as multi-steps?

It would be a way to decouple pipelines and let downstream pipelines fall back to an older versions of a data asset when an upstream pipeline failed. As far as I can see, Azure ML doesn't support sub-pipelines which would at least solve the problem of pipelines that are hard to analyse, visualise and debug? 

Regardless of this use case, I think automatically registering datasets in a pipeline is useful to be able to analyse the history of pipeline outputs without having to search through all the pipelines and steps that generated them.

**Comment by luigiw** [comment]
@tomasvanpottelbergh thx for the feedback. We'll add the automatically registering datasets as a feature request. As @cloga was saying, our team has already been working on it.

**Comment by cloga** [comment]
Hi @tomasvanpottelbergh ,
Nice to hear you have interest in sub-pipelines, actually we already have initial version for private preview. I would like invite you to join our private preview for pipeline component (aka. sub-pipelines) feature.

Would you mind to contact me via lochen@miscrosoft.com, I will send you more detail about pipeline component feature.

**Comment by sebihoefle** [comment]
I am also interested in both features, output registration and sub-pipelines.

> Hi @tomasvanpottelbergh ,
Output as named asset (parity feature of registered as in SDK v1) in our plan to support in following months.

> Hi @tomasvanpottelbergh ,
Nice to hear you have interest in sub-pipelines, actually we already have initial version for private preview. I would like invite you to join our private preview for pipeline component (aka. sub-pipelines) feature.

Is there any estimate when these features will be available?

**Comment by antseng-deloitte** [comment]
same here, i also think registering the output as a data asset on complete will help to track the changes of the output

**Comment by abhay8051** [comment]
Hi @tomasvanpottelbergh 

I am trying to register a data asset in the job with SDKV2 code but unable to get past authentication errors. Any inputs will be helpful. 

thanks

**Comment by wangchao1230** [comment]
Below feature will allow user to specify name & version field of pipeline output which come in sdk version 1.5.0.

SDK example:
![image](https://user-images.githubusercontent.com/47586720/219287274-9b071a07-4015-42bc-a89e-43fce6f6e2a3.png)

CLI Example:
![image](https://user-images.githubusercontent.com/47586720/219287397-396aba52-55e8-4853-ad3a-740bbee5350a.png)

**Comment by cloga** [comment]
Hi @sebihoefle, please fill in the form: https://forms.office.com/r/pEguDEiqZL
Pipeline component is already under private preview, I will grant you access after you finish this form.
Thanks.

**Comment by tomasvanpottelbergh** [comment]
Thank you very much @wangchao1230! Have just tested it and it seems to be working as intended. Would be great to add this to the azureml-examples repo as well.
