### ISSUE TITLE
peek_messages

### ISSUE THREAD

**Issue by daniwk** [Azure/azure-sdk-for-python#26643]
From my testing it looks like peek_messages method is returning max 250 queue message. It would be nice if this was added to the documentation under [`max_message_count`](https://learn.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebusreceiver?view=azure-python#azure-servicebus-servicebusreceiver-peek-messages).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec48c175-0e94-dbfd-e3b2-6ab2639ab89a
* Version Independent ID: 8bfacb3c-7a43-6bb3-c39b-ab6b751d83ac
* Content: [azure.servicebus.ServiceBusReceiver class](https://learn.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebusreceiver?view=azure-python#azure-servicebus-servicebusreceiver-peek-messages)
* Content Source: [docs-ref-autogen/azure-servicebus/azure.servicebus.ServiceBusReceiver.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-servicebus/azure.servicebus.ServiceBusReceiver.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by pvaneck** [comment]
Hey, @daniwk. Thanks for the feedback! I'll tag some people who may be able to help.

**Comment by kashifkhan** [comment]
Thanks for this @daniwk. I've reached out to the service team to see if there is a hard coded value for this on the service side. It could very well be possible that this value fluctuates based on a number of factors such as message size, network  etc. Were you always testing with the same messages or number of messages ?

**Comment by kashifkhan** [comment]
Just wanted to update: Im waiting to confirm with the service team if this indeed the behavior from their end. I can repro this on python as well as dotnet. Thank you :)

**Comment by kashifkhan** [comment]
Hi @daniwk, wanted to give you an update on this. The limit of 250 messages for peek is by the service and not the SDK. I've asked the SDK team to update the documentation on their side to reflect that limit. In the meantime we've updated the API docs to point to that documentation and also add some clarity around `max_message_count`. Thank you 🙂
