### ISSUE TITLE
[pylint] linter rule for type or property name that is too long

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#26640]
Per @johanste, we should write a linter rule that checks the char length of type and property names and warn if the name is too long. What "too long" means is TBD, but we should write the rule and run it on existing libraries to find the right balance / signal:noise to determine what number to use / what feels pythonic.

**Comment by kristapratico** [comment]
@l0lawrence adding you as an assignee because I'm not sure who will have time to do this over MQ. Perhaps we tackle it together. :)

**Comment by l0lawrence** [comment]
added
