### ISSUE TITLE
generate blob sas

### ISSUE THREAD

**Issue by readynetworks** [Azure/azure-sdk-for-python#26728]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc13eca7-8c35-456c-cb38-016d2fa40df5
* Version Independent ID: d89dc470-199e-fe2a-e8ba-ec35c73e1bc4
* Content: [azure.storage.blob package](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-storage-blob/azure.storage.blob.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by rakshith91** [comment]
Hi @readynetworks 
Could you provide more details about the issue?
