### ISSUE TITLE
 azure.core.exceptions.ClientAuthenticationError: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity.

### ISSUE THREAD

**Issue by SrinivasaTouch** [Azure/azure-sdk-for-python#26729]
azure.core.exceptions.ClientAuthenticationError: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2022-01-07T13:54:01.319431o inactivity. The token was issued on 2022-01-07T13:54:01.3194315Z and was inactive for 90.00:00:00.\r\nTrace ID: cccc-cccccc-ccccc-ccc\r\nCorrelation ID: 7dddddd-dddd-ddddd-dddd\r\nTimestamp: 2022-10-10 13:10:01Z","error_codes":[700082],"timestamp":"2022-10-10 13:10:01Z","trace_id":"85b6b9fa-9664-4f28-86c7-f109cda89c00","correlation_id":"749be7b6-a551-44b2-9db3-83eb617c3303","error_uri":"https://login.microsoftonline.com/error?code=700082"}

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Not quite sure about your question.

Given the error log you shared, https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-visualstudiocodecredential-authentication-issues may help.
