### ISSUE TITLE
Linter rule: all exceptions should use raise/from

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#26760]
It can be either `raise FooError() from e` or `raise FooError() from None`, but should always have a `from` to have a neat exception.

Of course, this applies only of the exception is raised from a `except`, otherwise `from` don't make sense.

cc @johanste @annatisch

**Comment by l0lawrence** [comment]
There is a pylint rule we were ignoring, will enable it:  https://pylint.pycqa.org/en/latest/user_guide/messages/warning/raise-missing-from.html
