### ISSUE TITLE
Specifying A Blob File Path as Input Data

### ISSUE THREAD

**Issue by heyheys** [Azure/azure-sdk-for-python#26778]
Hi there,

I want to pass the URI_FOLDER as one of the inputs in a job. I tried using a blob path, a local path and a DataStore path. The first one didn't work and the last two ones worked. Can someone please advise how to specify the blob path correctly? I know this is a very newbie question, but I've been struggling for long and can't sort it out. 

**Packages versions:**
Python = 3.8.13
azure.ai.ml = 0.1.0b7

**My code is:**

file_path = 'https://digitalwstorage8357afaf7.blob.core.windows.net/azureml-blobstore-61a7bc0b-5ad3-ih34-9210-74d048c11ede/LocalUpload/f8f28d43309a8018fa46b29a934ec437/session'        # This doesn't work

file_path = './session'            # This works

file_path = 'azureml://datastores/workspaceblobstore/paths/LocalUpload/f8f28d43309a8018fa46b29a934ec437/session'    # This works

job = command(
    code="./src",  
    command="python DataPrep.py --file_path ${{inputs.file_path}}  --save_path ${{outputs.save_path}}",
    inputs={
    "file_path": Input(type=AssetTypes.URI_FOLDER, path = file_path)
},
    outputs={
    "save_path": Output(type=AssetTypes.URI_FOLDER,
        path="azureml://subscriptions/ae60af85-9fre-4042-bc82-8c0dafa8adbf/resourcegroups/MyResources/workspaces/MyWorkspace/datastores/workspaceblobstore/paths/test_outputs/")
}
)

**And I've got this error:**

Error

UserError

{"NonCompliant":"DataAccessError(ConnectionFailure { source: Some(hyper::Error(Connect, ConnectError(\"dns error\", Custom { kind: Uncategorized, error: \"failed to lookup address information: Name or service not known\" }))) })"}
{
  "code": "data-capability.UriMountSession.PyFuseError",
  "target": "",
  "category": "UserError",
  "error_details": [
    {
      "key": "NonCompliantReason",
      "value": "DataAccessError(ConnectionFailure { source: Some(hyper::Error(Connect, ConnectError(\"dns error\", Custom { kind: Uncategorized, error: \"failed to lookup address information: Name or service not known\" }))) })"
    },
    {
      "key": "StackTrace",
      "value": "  File \"/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/data_capability/capability_session.py\", line 70, in start\n    (data_path, sub_data_path) = session.start()\n\n  File \"/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/data_capability/data_sessions.py\", line 364, in start\n    options=mnt_options\n\n  File \"/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/azureml/dataprep/fuse/dprepfuse.py\", line 696, in rslex_uri_volume_mount\n    raise e\n\n  File \"/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/azureml/dataprep/fuse/dprepfuse.py\", line 690, in rslex_uri_volume_mount\n    mount_context = RslexDirectURIMountContext(mount_point, uri, options)\n"
    }
  ]
}

Many thanks!

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by luigiw** [comment]
Helllo @heyheys , can you confirm if you're trying to use the blob URL as input or output path? @SturgeonMi Do you know if storage URL as input path is supported yet?

**Comment by heyheys** [comment]
Hi Iuigiw! Thank you for your question. I had 3 trials:

#Trial        Input path              Output path
  1             Blob URL                DataStore path         Doesn't work
  2           DataStore path         DataStore path        Works
  3            Local path                DataStore path        Works

And the Blob URL is written as 

"https://digitalwstorage8357afaf7.blob.core.windows.net/azureml-blobstore-61a7bc0b-5ad3-ih34-9210-74d048c11ede/LocalUpload/f8f28d43309a8018fa46b29a934ec437/session" 

where "LocalUpload/f8f28d43309a8018fa46b29a934ec437/session" is folder path and I'm sure they are correct.

**Comment by heyheys** [comment]
Also, I found a potential typo in the documentation here: 

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-read-write-data-v2?tabs=cli#supported-paths

A path on Azure Storage    https://<account_name>.blob.core.windows.net/<container_name>/**path**

Should the path be <path>?

**Comment by Man-MSFT** [comment]
I believe we currently support public Azure storage paths but will support private Azure storage paths soon, and for private paths we recommend creating and using a datastore today (even if no credential is placed inside the datastore, this is the way to allow pass through authentication to work). Defer again to @SturgeonMi on when we don't need the datastore middle layer.

For the doc, yes, thanks for catching that! I can fix that momentarily.
