### ISSUE TITLE
delete_deployment does not pass comp=media to delete disks

### ISSUE THREAD

**Issue by okaram** [Azure/azure-sdk-for-python#268]
The delete deployment API (http://msdn.microsoft.com/en-us/library/azure/ee460815.aspx) allows for an optional parameter, comp=media, to delete all disks and storage for the VM be deleted also. servicemanagementservice.delete_deployment does not support this, which seems very useful.

I can try to do this, as it would help me get used to the codebase, if it's ok ...

**Comment by huguesv** [comment]
Yes, that sounds great!

**Comment by okaram** [comment]
Just sent a pull request, I think :)

**Comment by huguesv** [comment]
Thanks! I'll work on adding a test or two for it, then merge the pull request.

**Comment by huguesv** [comment]
It's in for the upcoming v0.10 release, thanks!
