### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED at service principal authentication to Azure Key Vault

### ISSUE THREAD

**Issue by codingbi56** [Azure/azure-sdk-for-python#26806]
**Describe the bug**
I'm authenticating to Azure Key Vault using python, Azure AD service principal and client secret 

***Exception or Stack Trace***
Error Message: ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

***Code Snippet / To Reproduce***

from azure.identity import ClientSecretCredential
from azure.identity import EnvironmentCredential
from azure.keyvault.secrets import SecretClient

strAZURE_TENANT_ID = ''
strAZURE_CLIENT_ID =  '' 
strAZURE_CLIENT_SECRET =  ''
strAZURE_AUTHORITY_HOST =  "login.microsoftonline.com"

KEYVAULT_NAME = ""
KEYVAULT_URI = f"https://" + KEYVAULT_NAME + ".vault.azure.net/"                

_credential = EnvironmentCredential(
AZURE_TENANT_ID = strAZURE_TENANT_ID, 
AZURE_CLIENT_ID = strAZURE_CLIENT_ID,
AZURE_CLIENT_SECRET = strAZURE_CLIENT_SECRET#, 
AZURE_AUTHORITY_HOST = strAZURE_AUTHORITY_HOST
)

_credential
_sc = SecretClient(vault_url=KEYVAULT_URI, credential=_credential)

secret = _sc.get_secret("testSecret")

**Expected behavior**
It should authenticate. Here is a working example: https://www.patreon.com/posts/accessing-azure-36555631

**Screenshots**

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.9]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]
- azure-identity              1.11.0
- azure-keyvault-certificates 4.6.0
- azure-keyvault-keys         4.7.0
- azure-keyvault-secrets      4.6.0
- msal                        1.20.0
- msal-extensions             1.0.0

**Additional context**
I've used both ClientSecretCredential and EnvironmentCredential.
I've read on other posts people recommending:
- verify = False
- updating/forcing the request library to use certain certificates 
- updating or using certify 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you help to share the trackback or entire error log?

It will help to identify where the error comes from.
