### ISSUE TITLE
Batch VirtualMachineConfiguration docstring has broken link

### ISSUE THREAD

**Issue by jafreck** [Azure/azure-sdk-for-python#2680]
This link in the docstring is broken.

https://github.com/Azure/azure-sdk-for-python/blob/9db9674585fe98265cb54680c4977645caac30cd/azure-batch/azure/batch/models/virtual_machine_configuration.py#L47

**Comment by lmazuel** [comment]
Hi @jafreck 
As suggested in your PR, that's a Swagger fix, please PR there, or open an issue there.
Thanks!
