### ISSUE TITLE
'EmailClient' object has no attribute 'get_sent_status'

### ISSUE THREAD

**Issue by cpajr** [Azure/azure-sdk-for-python#26818]
- **Package Name**: azure.communication.email
- **Package Version**: 1.0.0b1
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.10

**Describe the bug**
When attempting to get the email sent status, leverage example code, the repeated error is raised saying "AttributeError: 'EmailClient' object has no attribute 'get_sent_status'."

**To Reproduce**
1. Issue code as given in examples:
```
response = email_client.send(message)
status = email_client.get_sent_status(response.message_id)
```
**Expected behavior**
A sent status given with no error thrown.  

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Do you mean get_sen**d**_status?

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-email/samples/check_message_status_sample.py#L67

**Comment by cpajr** [comment]
I see that example code from your link.  However, your documentation is incorrect, both on the Microsoft's website and PyPi:

https://learn.microsoft.com/en-us/python/api/overview/azure/communication-email-readme?view=azure-python-preview#get-email-message-status

https://pypi.org/project/azure-communication-email/

![image](https://user-images.githubusercontent.com/36517688/196005894-d783a211-80c5-4501-ba96-0995ed34d9da.png)

**Comment by cpajr** [comment]
Glad I could help.

**Comment by xiangyan99** [comment]
@turalf Can you take a look?
