### ISSUE TITLE
Create documentation for Identity credential cache

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-python#26824]
Our current documentation for how our SDK interacts with the MSAL token cache is insufficient. We need to doc:

- What scenarios caching is useful for
- How caching is exposed from our library
- What expectations should be when caching is used (performance, throttling)
- How the disk cache is secured when used

**Comment by pvaneck** [comment]
Closed via https://github.com/Azure/azure-sdk-for-python/pull/30090
