### ISSUE TITLE
Converge azure.functions.ServiceBusMessage with azure.servicebus.ServiceBusMessage

### ISSUE THREAD

**Issue by metamoof** [Azure/azure-sdk-for-python#26827]
**Is your feature request related to a problem? Please describe.**
I deal with a lot of code in azure functions that requires me to process messages in a ServiceBus queue, and then pass that message on untouched. However, despite the fact that an Azure Functions ServiceBus Queue Trigger passes in an `azure.functions.ServiceBusMessage`,  `azure.servicebus.ServiceBusSender` does not accept that kind of message, preferring to throw the rather cryptic error: `Exception: TypeError: Only AmqpAnnotatedMessage, ServiceBusMessage instances or Mappings representing messages are supported. Received instead: ServiceBusMessage`.

And as such, my code is peppered with this boilerplate:

```python
# msg is my azure.functions.ServiceBusMessage passed in at the start
with azure.servicebus.ServiceBusClient.from_connection_string(
    os.environ["SERVICEBUS"]
) as sb:
    sender = sb.get_queue_sender("next-step")
    message = azure.servicebus.ServiceBusMessage(
        body=msg.get_body(),
        application_properties=msg.user_properties,
        message_id=msg.message_id,
        content_type=msg.content_type,
    )
    sender.send_messages(message)
```

Also, knowing when to use `application_properties` or `user_properties` drives me a little crazy, and means I can't just do something like `message = azure.servicebus.ServiceBusMessage(**msg.__dict__)` or somesuch.

**Describe the solution you'd like**
Ideally, some sort of convergence, in which `azure.functions.ServiceBusMessage` is a subclass of `azure.servicebus.ServiceBusMessage`, but implementing the old API as backwards-compatible aliases, and eventually deprecating the APIs that are not in  `azure.servicebus.ServiceBusMessage`. I can see no reason why they need to be separate classes.

**Describe alternatives you've considered**
Somewhat messier alternatives:
 * Allow `azure.servicebus.ServiceBusSender.send_messages()` to accept `azure.functions.ServiceBusMessage` instances
 * Make an `azure.servicebus.ServiceBusMessage.from_azure_functions_message()` constructor that creates one from the other

**Comment by tjprescott** [comment]
Thank you for the detailed issue. @kashifkhan could you please take a look.

**Comment by swathipil** [comment]
Hi @metamoof - Thanks for your thoughts!

The solution that you discussed would require changes in the `azure-functions` library, which is owned by the Azure Functions team. You can create an issue in the [azure-functions repo](https://github.com/Azure/Azure-Functions/issues).

The two alternative solutions that you provided would require `azure-servicebus` to take `azure-functions` as a dependency, and, unfortunately, this is not feasible.

You may have already explored this, but I took a look at using an [[output binding to send a message](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=in-process%2Cextensionv5&pivots=programming-language-python)]. Unfortunately, the outbound message currently does not support additional attributes like application properties. I found [[this related feature request](https://github.com/Azure/Azure-Functions/issues/1139)] in the functions repository that you can reply to/support.

From the SDK perspective, your current implementation seems to be the best workaround.
