### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.chinacloudapi.cn', port=443): Max retries exceeded with url: /_z95JCO4_gAfjyII5XUpYDr-.7J-ybk13y/oauth2/token (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')",),))

### ISSUE THREAD

**Issue by Echo-ZhangXu** [Azure/azure-sdk-for-python#26826]
import os
import traceback

from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.compute import ComputeManagementClient
from azure.mgmt.compute.models import DiskCreateOption

from msrestazure.azure_exceptions import CloudError
from msrestazure.azure_cloud import AZURE_CHINA_CLOUD

def run_example():
    """Virtual Machine management example."""
    #
    # Create all clients with an Application (service principal) token provider
    #

    # credentials, subscription_id = get_credentials()

    try:
        id = sys.argv[1]
        con = mdb.connect(host=db_address,user=db_username,passwd=db_password,db=db_name)
        con.autocommit(True)
        cur = con.cursor(mdb.cursors.DictCursor)
        cur.execute("SELECT access_key_id,secret_access_key,region,region_name FROM t_cfg_ecs_config where id= ' %s ' " % id)
        info = cur.fetchone()
        if info == None:
            print("No Configuration output information")
        try:
            subscription_id = info['region']
            credentials = ServicePrincipalCredentials(
                client_id=info['access_key_id'],
                secret=info['secret_access_key'],
                tenant=info['region_name'],
                resource="https://management.chinacloudapi.cn",
                authority=AZURE_CHINA_CLOUD.endpoints.resource_manager,
                china=True
            )

            resource_client = ResourceManagementClient(credentials, subscription_id,base_url="https://management.chinacloudapi.cn/")
            compute_client = ComputeManagementClient(credentials, subscription_id,base_url="https://management.chinacloudapi.cn/")
            network_client = NetworkManagementClient(credentials, subscription_id,base_url="https://management.chinacloudapi.cn/")

         
        except IndexError,e:
            print("Config information error")
        con.close()
    except mdb.Error, e:
        print("Mysql error %d: %s" % (e.args[0],e.args[1]))

    

if __name__ == "__main__":
    run_example()

**Comment by Echo-ZhangXu** [comment]
应该怎么解决

**Comment by Echo-ZhangXu** [comment]
应该怎么解决呢？




Zx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Azure/azure-sdk-for-python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Azure/azure-sdk-for-python] requests.exceptions.SSLError: HTTPSConnectionPool(host='login.chinacloudapi.cn', port=443): Max retries exceeded with url: /_z95JCO4_gAfjyII5XUpYDr-.7J-ybk13y/oauth2/token (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')",),)) (Issue #26826)





 
Label prediction was below confidence level 0.6 for Model:ServiceLabels: 'Compute:0.33864716,Service Bus:0.04201273,Event Hubs:0.036422167'

**Comment by xiangyan99** [comment]
Could you share the package versions?
