### ISSUE TITLE
cannot update ssl_certificate into application gateway

### ISSUE THREAD

**Issue by tommy-dunn** [Azure/azure-sdk-for-python#26840]
- **Package Name**: azure.mgmt.network
- **Package Version**: azure.mgmt.network.v2020_06_01.models 
- **Operating System**: linux
- **Python Version**:  3.9.2

**Describe the bug**
attempt to update ssl cert in application gateway results in a duplicate resource error:

azure.core.exceptions.HttpResponseError: (InvalidRequestFormat) Cannot parse the request.
Code: InvalidRequestFormat
Message: Cannot parse the request.
Exception Details:	(DuplicateResourceName) Resource /subscriptions//resourceGroups//providers/Microsoft.Network/applicationGateways/ has two child resources with the same name <name of cert>

**To Reproduce**

```
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.network.v2020_06_01.models import ApplicationGatewaySslCertificate

# create credentials
credentials = DefaultAzureCredential()

# create network client
network_client = NetworkManagementClient(credentials, SUBSCRIPTION_ID)

# get an existing application gateway
app_gw = network_client.application_gateways.get(RESOURCE_GROUP_NAME, APPLICATION_GATEWAY_NAME)

# local cert to be read/imported
pfx_cert = open(<cert>.pfx", 'rb').read()

# create an SSL certificate
ssl_cert = ApplicationGatewaySslCertificate(
    name=<name>,
    data=pfx_cert,
    password=<passowrd used to encrypt cert>,
    key_vault_secret_id =<kv_secret_id>"
)

# retrieve list of ssl_certificates and append cert into list
app_gw.ssl_certificates.append(ssl_cert)

# update the application gateway
network_client.application_gateways.begin_create_or_update(
    RESOURCE_GROUP_NAME,
    APPLICATION_GATEWAY_NAME,
    app_gw
)
```

**Expected behavior**
cert is appended to list and added to appgw. 

**Screenshots**

**Additional context**
The only working example of how to update an appgw via the python sdk is here: https://github.com/Azure-Samples/network-python-manage-application-gateway/blob/master/example.py

this example omits ssl_certificates and it uses `application_gateways.create_or_update()`, however the ApplicationGatewaysOperations Class has no `create_or_update` method. it has a [begin_create_or_update](https://learn.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_06_01.operations.applicationgatewaysoperations?view=azure-python#azure-mgmt-network-v2020-06-01-operations-applicationgatewaysoperations-begin-create-or-update).

additionally, no where in the docs (that i can find) does it mention what attributes are available to us for modifying the list. 

How can i update, add, delete, remove a ssl_certificate that exists in the appgw?

**Comment by tjprescott** [comment]
@tommy-dunn thank you for reaching out. @msyyc can you please take a look.

**Comment by msyyc** [comment]
Thanks for you feedback and we will investigate it asap

**Comment by Wzb123456789** [comment]
Hi @tommy-dunn，thanks for you feedback.

According to the error message you gave, when updating the information of `app_gw`, you need to pay attention to the problem of renaming. It is recommended to replace the names, because the original name already exists during the update, and the update operation cannot be performed. like:
```python
app_gw = network_client.application_gateways.get(RESOURCE_GROUP_NAME, APPLICATION_GATEWAY_NAME)

app_gw.frontend_ip_configurations.name = 'xxxxxxxx'
app_gw.frontend_ports.name = 'xxxxxx'
...
```

**Comment by tommy-dunn** [comment]
your resolution to this issue was to tell me that duplicate resource names cannot exist? I already know that from the output of the error. please tell me this was a joke @tjprescott

**Comment by Wzb123456789** [comment]
@tommy-dunn 

I observed your code, and I found that the `app_gw.ssl_certificates.append(ssl_cert)` you used is wrong, because an `ssl_cert` already exists in `ssl_certificates`, and then you append a `ssl_cert` with the same name directly, so this will lead to Report duplicate resource error.

You can use this code:
```python
for cert in app_gw.ssl_certificates:
   if cert.name == xx:
     cert.data = pfx_cert
```
In this way, only the expired ssl_cert is replaced, and the problem of renaming can be avoided.

Hope it can help you
