### ISSUE TITLE
$select parameter when reading user in AD

### ISSUE THREAD

**Issue by lipoteFR** [Azure/azure-sdk-for-python#26848]
I have a piece of code in .Net that add a "$select" item in the query when requesting the AD (graph-api) so the server returns only this selected columns
```
List<QueryOption> options = new List<QueryOption>            {
    new QueryOption("$select", UserDefaultSelect)                       };
```
In the UserDefaultSelect list of attributes one is important for me : the SamAccount and server doesn't return by default :( 
```
private const string UserDefaultSelect = "...bleId,  onPremisesSamAccountName  ,userTyp...";
```
Looking in :
/sdk/graphrbac/azure-graphrbac/azure/graphrbac/operations/users_operations.py
it seems "$select" parameter is not managed :( only api-version is pass as a parameter : 
   about row 175 : we have 
```
   def get(
...
        # Construct parameters
        query_parameters = {}
        query_parameters['api-version'] = self._serialize.query("self.api_version", self.api_version, 'str')
``` 
In Microsoft documentation a $select property allow to have this subset of fields selected
https://learn.microsoft.com/en-us/graph/query-parameters#select-parameter
  | /users?$select=givenName,surname

Do i miss something and the capability is already in place ?
Do you plan to add it in the code ?
Thx for your help 
Léopold

**Comment by lipoteFR** [comment]
adu = graphrbac_client.users.get(upn_or_object_id=em, custom_headers={'$select': 'onPremisesSamAccountName'})
make the job
![image](https://user-images.githubusercontent.com/25454894/196179108-fda2595d-141f-4617-bb1a-fb2800593789.png)
but select should be part of a "custom_parameters" that doesn't exists :(

**Comment by tjprescott** [comment]
@lipoteFR thank you for reaching out. @xiangyan99 could you take a look (or route to the appropriate individual)?

**Comment by xiangyan99** [comment]
@samwelkanda could you take a look?

**Comment by lmazuel** [comment]
`azure-graphrbac` is about Azure AD Graph API, which is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60

MS Graph is not an Azure product, so we can't help you on this repo unfortunately, but I would suggest you look into the "microsoftgraph" org on Github, starting here:
https://github.com/microsoftgraph/msgraph-sdk-python-core
