### ISSUE TITLE
Building inference image for ARM64 architecture using azureml.core.Model

### ISSUE THREAD

**Issue by ecm200** [Azure/azure-sdk-for-python#26849]
- **Package Name**: azureml.core
- **Package Version**: 1.46.0
- **Operating System**: Linux on ARM64
- **Python Version**:  3.8.10

**Describe the bug**

When trying to create an inference server image that be used on a Linux ARM64 OS, this process fails because some of the precompiled dependencies of the Azure ML Inference Server Service image are for X86 architecture only.

The current blocker is that the “standard” way in which an AzureML inference server container is produced currently, includes the copying of some executable code onto the inference service docker image that is being built, which is pre-compiled for X86 hardware (/var/iot_server). 

As a current workaround, I have found a way to use the Azure ML Inference Server python package directly (using `azmlinfsrv`), instead of the standard way in which the AzureML SDK generated inference docker containers are started, which uses `runsvdir /var/runit` to execute a number of services including Nginx and Gunicorn.

The result of this issue is that we cannot use the AzureML Python SDK to do ARM64 based builds for deployment to our instruments at this time. Ideally we would like to be able to perform a build process completely within the framework of the AzureML Workspaces and using the AzureML Python SDK as the build execution interface. This is to avoid unnecessary divergence of cloud and on-instrument serving solutions.

A start would be able to get access to the source code of the aforementioned precompiled X86 application to be able to build that in an ARM64 environment. 

That way, it can be built into the ARM64 base image, and referenced in the AzureML SDK `Model.package()` build process, without any additional modifications required.

**To Reproduce**

I have traced the issue with using the fully functional Azure ML Inference Container Service on ARM64 to a compiled application that is transferred to each AzureML base container via a separate docker container. The iot-server binary executable, which sits in the `/var/iot-server` directory on a built Azure ML Inference Server image appears to be the issue.

The aforementioned X86 application comes from the build process when taking a registered model from an AzureML workspace and using the `Model.pacakge()` method to generate a docker container and / or download a file package containing the model and Dockerfile for generating said image. In order to do this, you are required to provide a registered AzureML workspace environment (i.e. docker image or Dockerfile), and a scoring script as the entry point.

There is expectation that any inferencing environment has certain folders installed into the container file system in the /var directory, and these are to fascilitate the installation and running of the Azure ML Inference Server and supporting services for authenticated connection (Nginx), parallel requests handling (Gunicorn) and logging (rsyslog). Looking at the definitions of [Azure ML base containers from github](https://github.com/Azure/AzureML-Containers/blob/master/base/cpu/openmpi4.1.0-ubuntu20.04/Dockerfile), these folders come from the following source container image: `mcr.microsoft.com/azureml/o16n-base/python-assets:20220331.v12`. This image is imported into the build environment [here](https://github.com/Azure/AzureML-Containers/blob/268a27ece8be3994c36aecf5eb862530d57bc8ce/base/cpu/openmpi4.1.0-ubuntu20.04/Dockerfile#L3), and then copied to the `/var` directory [here](https://github.com/Azure/AzureML-Containers/blob/268a27ece8be3994c36aecf5eb862530d57bc8ce/base/cpu/openmpi4.1.0-ubuntu20.04/Dockerfile#L57). Below shows the full set of folders that are transferred from this resource, with the highlighted iot-server folder which contains the pre-compiled binaries.

![image](https://user-images.githubusercontent.com/34489160/196175832-7adb0fc3-4f36-419c-a5f5-d1386c3cd050.png)

This is the contents of the iot-server directory.

![image](https://user-images.githubusercontent.com/34489160/196175869-a3f6c64f-2d61-429a-86fd-a6d70cd0ce44.png)

Execution on an X86 based machine of the iot-server binary yields the following response:

![image](https://user-images.githubusercontent.com/34489160/196175994-f03d0150-6743-45f7-818a-4d5fc3f0a3e6.png)

However, execution on an ARM64 machine yields the following:

![image](https://user-images.githubusercontent.com/34489160/196176041-a4c788dc-e0ba-47da-9c0d-09f3e818b9f4.png)

From the terminal output attached `X86_run.txt`, you can see if I execute the usual startup command for an Azure ML Inference Server container (runsvdir /var/runit) then the X86 version correctly starts up the various services and starts listening for posts.

[x86_run.txt](https://github.com/Azure/azure-sdk-for-python/files/9800405/x86_run.txt)

However, when I run the same command on the `ARM64` built docker container, the execution error for the `iot-server` binary occurs and the service does not start.

[ARM64_run.txt](https://github.com/Azure/azure-sdk-for-python/files/9800412/ARM64_run.txt)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tjprescott** [comment]
@ecm200 thank you for reaching out. @bandsina could you please take a look?  cc/ @azureml-github

**Comment by ecm200** [comment]
Thanks @tjprescott , happy to assist in anyway.

**Comment by arunsu** [comment]
@ecm200, In the latest base images precompiled IoT binaries are removed. Please give a try now. Thanks.
