### ISSUE TITLE
AzureCliCredential fails due to Python deprecation message getting mixed with token output

### ISSUE THREAD

**Issue by micromaomao** [Azure/azure-sdk-for-python#26857]
- **Package Name**: azure-identity
- **Package Version**: 1.10.0
- **Operating System**: WSL
- **Python Version**: 3.6.0

**Describe the bug**
In https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L137, the option `"stderr": subprocess.STDOUT` makes `check_output` also include stderr in the returned string. I was trying to use this package in a container with a somewhat out-of-date python setup, which caused `az account get-access-token` to output some warnings to stderr:
![RequestsDependencyWarning from python screenshot](https://user-images.githubusercontent.com/6070533/196222634-a7674560-146b-4d33-85dd-7966b988f5ad.png)

Since `_run_command`'s return value is parsed as JSON, this caused an exception and resulted in a somewhat confusing error message:

```
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
...
```

**To Reproduce**
(Environment-specific, but reasoning for this issue described above)

**Expected behavior**
`AzureCliCredential` should work

**Comment by micromaomao** [comment]
I haven't got to it yet but I'm happy to send in a PR to fix this... Just need to bounce my thoughts first since I'm quite new to this and haven't looked into it a lot yet:

I think we can change the `stderr` option of the `check_output` call to `PIPE`. This way, in case of any error, the `CalledProcessError` that gets thrown will have the stderr content, which we can relay in our `ClientAuthenticationError` exception to provide more information to the user, if something does go wrong. And in my case this will just ignore the python warning message.

Let me know if I should follow this and work on a pull request.

**Comment by tjprescott** [comment]
@micromaomao thanks for reporting this! @xiangyan99 @pvaneck could either of you take a look at this?

**Comment by xiangyan99** [comment]
Thank you @micromaomao.

To help me understand better, in your case, it looks to me az account command outputs warning rather than the token.

How can we make it work?

**Comment by micromaomao** [comment]
Hi @xiangyan99 thanks for following up.

The issue is not that `az` does not output the token - it does, but it also outputs a warning (probably caused by a third-party library), which causes the JSON parsing in `azure-identity` to fail.

I have suggested a solution above. If the team agrees that this is a sensible approach I'm happy to make a pull request.

**Comment by xiangyan99** [comment]
@micromaomao Thanks for the confirmation. Please feel free to propose a PR and thanks for your contribution.
