### ISSUE TITLE
BlobClient.query_blob fails on parquet blobs with decimal columns

### ISSUE THREAD

**Issue by JacekPliszka** [Azure/azure-sdk-for-python#26850]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.14.0
- **Operating System**: CentOS Linux release 7.9.2009
- **Python Version**: 3.7

**Describe the bug**
When trying to run query_blob method of BlobClient on parquet file with decimal column I am getting:

azure.core.exceptions.HttpResponseError: Parquet column type validator: decimal type is not supported.
RequestId:093acd71-501e-0006-1926-e2b2a8000000
Time:2022-10-17T12:48:37.5248158Z
ErrorCode:ErrorProcessingQueryExpression
Content: <?xml version="1.0" encoding="utf-8"?>
<Error><Code>ErrorProcessingQueryExpression</Code><Message>Parquet column type validator: decimal type is not supported.
RequestId:093acd71-501e-0006-1926-e2b2a8000000
Time:2022-10-17T12:48:37.5248158Z</Message></Error>

**To Reproduce**
Run query_blob method on parquet blob with decimal column like this:
bl_cl.query_blob("select prod_skid from BlobStorage", blob_format='ParquetDialect')

**Expected behavior**
Returns BlobQueryReader.

**Comment by tjprescott** [comment]
@JacekPliszka thank you for reaching out. @jalauzon-msft @vincenttran-msft could either of you take a look at this?

**Comment by vincenttran-msft** [comment]
Hi @JacekPliszka, thanks for your inquiry. This is not really an "issue" with the Python SDK and instead seems like a feature request. I reached out to the correct contacts internally regarding support for decimal type, and the feature is something that is planned to be supported in the future, but I do not have any good estimates on when the feature will be completed.

With that being said, please feel free to submit your feedback regarding this feature at https://aka.ms/AzStorageFeedback by either upvoting a current idea that matches your feedback, or creating a new idea for others to be able to upvote. This will help the service team gauge interest and prioritize new features!

And so, I will mark the issue as resolved, but please do reach out if you have any other questions.

Thanks!
