### ISSUE TITLE
Content-Range response header exception for empty files

### ISSUE THREAD

**Issue by daviddavis** [Azure/azure-sdk-for-python#26871]
- **Package Name**: azure-blog-storage
- **Package Version**: 12.14.0
- **Operating System**: all
- **Python Version**: 3.10

**Describe the bug**
[This commit](https://github.com/Azure/azure-sdk-for-python/commit/28d44f1127319af58428285b36f24ac4c1c9d7e2#
) checks for missing or invalid content range headers. However, there's a problem with the check because the exception gets raised if the file is empty (ie `self._file_size` is 0).

**To Reproduce**
1. Upload an empty file to azure blob storage
2. Attempt to download it with azure-blob-storage

**Expected behavior**
File downloads properly.

**Comment by jalauzon-msft** [comment]
Thanks for finding this and fixing it (#26872). This is definitely a regression introduced in our latest release. I will work on getting a patch release out with the fix ASAP.

**Comment by daviddavis** [comment]
@jalauzon-msft it looks like you were right. I think this is an azurite issue:

https://github.com/Azure/Azurite/issues/1682
