### ISSUE TITLE
is there any python sdk for rotation of storage Access Keys  or Account keys ??

### ISSUE THREAD

**Issue by readynetworks** [Azure/azure-sdk-for-python#26888]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tjprescott** [comment]
@jalauzon-msft @vincenttran-msft could either of you address this question?

**Comment by vincenttran-msft** [comment]
Hi @readynetworks thanks for your inquiry. I believe the API you are looking for is `regenerate_key`. Here is a link to its [implementation](https://github.com/Azure/azure-sdk-for-python/blob/5b0060bef164b4522177ffd8fba0c408e8b2324b/sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2022_05_01/operations/_storage_accounts_operations.py#L1347) and also the relevant [documentation](https://learn.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.v2022_05_01.operations.storageaccountsoperations?view=azure-python#azure-mgmt-storage-v2022-05-01-operations-storageaccountsoperations-regenerate-key).

With that being said, an alternative is to rotate the keys in Azure Portal. 

Thanks!
