### ISSUE TITLE
Remove dependency on six

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#26895]
https://github.com/Azure/azure-sdk-for-python/issues/26893.

Ref: https://github.com/Azure/azure-sdk-for-python/pull/25565

- [ ] azure-ai-anomalydetector
- [ ] azure-appconfiguration  - code gen
- [ ] azure-security-attestation
- [ ] azure-ai-language-questionanswering
- [ ] azure-communication
- [ ] azure-containerregistry - test only?
- [x] azure-cosmos
- [ ] azure-eventgrid
- [x] azure-eventhub
- [ ] azure-ai-ml
- [ ] azure-monitor
- [ ] azure-search-documents
- [ ] azure-storage
- [ ] azure-data-tables
- [ ] azure-ai-translation-document
- [ ] azure-media-videoanalyzer-edge
- [x] azure-identity

**Comment by xiangyan99** [comment]
#30613

**Comment by edgarrmondragon** [comment]
Are there any updates on the progress here? Can the community help in any way?
