### ISSUE TITLE
SDK not uploading SSH public key

### ISSUE THREAD

**Issue by pphanireddy** [Azure/azure-sdk-for-python#269]
Hi,

I am using the following code to upload SSH public key while creating a new vm deployment:

                key_pair_path =  '/home/' + self.app_user + '/.ssh/id_rsa.pub'
                keypair = KeyPair(thumbprint, key_pair_path)
                vmconf.ssh = SSH()
                vmconf.ssh.key_pairs.key_pairs.append(keypair)

                result = self.sms.create_virtual_machine_deployment(service,
                        str(deployId),
                        slot,
                        str(roleId),
                        roleId,
                        vmconf,
                        osvhd,
                        network_config=netconf,
                        role_size=size)

The above code is not uploading the id_rsa.pub to the newly created vm. It also doesnt throw error.

**Comment by crwilcox** [comment]
Hi pphanireddy.

Appending the keypair to the configuration does not upload the cert and instead links to a servicemanagement certificate that is uploaded.

sms.add_service_certificate is the call you want to make to upload a certificate.  Below is a bit of code I wrote showing how to use that call.

def add_ssh_certificate(sms, service_name, cert_path):
    """Adds the specified SSH Certificate to the specified service_name."""
    # if you need to create the key/pem here is a sample
    #openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout filename.key -out filename.pem
    #openssl pkcs12 -export -in filename.pem -inkey filename.key -out filename.pfx

    with open(cert_path, "rb") as bfile:
        cert_data = base64.b64encode(bfile.read()).decode()
        cert_format = 'pfx'
        cert_password = ''
        cert_res = sms.add_service_certificate(service_name=service_name,
                            data=cert_data,
                            certificate_format=cert_format,
                            password=cert_password)

**Comment by crwilcox** [comment]
The adding of a keypair to configuration does not upload a certificate.  It simply makes a reference to an uploaded service certificate.  Your code looks alright but you will need to add the service certificate to the service before deploying this.  The function to do this is sms.add_service_certificate.

Here is some code using this as well as the openssl commands to create a cert.  I upload .pem certs, but pfx should also work.  It is a known oddity that the cert format should be left as 'pfx' even when uploading 'pem' certs.

`
"""Adds the specified SSH Certificate to the specified service_name."""
# if you need to create the key/pem here is a sample
#openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout filename.key -out filename.pem
#openssl pkcs12 -export -in filename.pem -inkey filename.key -out filename.pfx

with open(cert_path, "rb") as bfile:
	cert_data = base64.b64encode(bfile.read()).decode() # decode to make sure this is a str and not a bstr
	cert_format = 'pfx'
	cert_password = ''
	cert_res = sms.add_service_certificate(service_name=service_name,
						data=cert_data,
						certificate_format=cert_format,
						password=cert_password)
	wait_for_async(sms, cert_res.request_id, "Adding Service Management Cert", 30)
`

**Comment by pphanireddy** [comment]
Thanks, I knew that we need to upload the cert before using it as the ssh public key. But the problem was I was uploading PFX cert. When I uploaded PEM cert, it worked. Wierd!
