### ISSUE TITLE
Can i get the python code for fetching the Role Assignments for a specific Service Principle.

### ISSUE THREAD

**Issue by jamavinay** [Azure/azure-sdk-for-python#2690]
Hello Everyone,

One of my client is looking for the list of role assignments for a specific principal irrespective of  subscriptions in azure. The list  may be like below.

TenantID | SubscriptionID | SubscriptionName | RBACRoleDefinitionName | DisplayName | ObjectType | Scope
-- | -- | -- | -- | -- | -- | --

Could anyone please help me on this to get the list of service principals . 

Thanks in advance.

**Comment by lmazuel** [comment]
Hi @jamavinay 
Listing the sp will be using `azure-graphrbac`: https://pypi.org/project/azure-graphrbac/
Listing the rol assignment will be using `azure-mgmt-authorization`: https://pypi.org/project/azure-mgmt-authorization/

I unfortunately don't have specific samples, using the doc might help:
https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory?view=azure-python
https://docs.microsoft.com/en-us/python/api/azure.graphrbac.operations.serviceprincipalsoperations?view=azure-python#list
https://docs.microsoft.com/en-us/python/api/overview/azure/authorization?view=azure-python
https://docs.microsoft.com/en-us/python/api/azure.mgmt.authorization.operations.roleassignmentsoperations?view=azure-python#list

**Comment by MMollyy** [comment]
```
role_assignment = {'role_definition_id': ra.role_definition_id for ra in
                           auth_client.get(environment).role_assignments.list_for_resource_group(
                               resource_group_name=resource_group.get(environment).name,
                               filter=f"principalid eq '{service_principal.get(environment).object_id}'") if
                           ra.role_definition_id == role_definition.get(environment).get(
                               role_name)}
```
this piece of code looks up the role assignments, for a specific scope (the resource group), and filtering the service principal by object_id. 
And it will only select the role_assignment if the principal ids match.

Your use case seems a bit different, but i believe this should help you along the way with what Laurent already provided.
