### ISSUE TITLE
Receiving Events from Multiple Topics/EventHubs in one Consumer Group

### ISSUE THREAD

**Issue by amaendeepm** [Azure/azure-sdk-for-python#26916]
**Is your feature request related to a problem? Please describe.**
Kafka DSL allows consumer to have syntax where it can subscribe to more than one topic. I fail to find that so far in Azure Eventhub documentation. Should I be writing separate event souring scripts for that ?

**Describe the solution you'd like**
Please provide equivalent of this syntax from Kafka Consumer API
consumer.subscribe(Arrays.asList(topic1, topic2))
Or if it is already there, please document it out

**Describe alternatives you've considered**
Writing multiple event sourcing scripts one from each source topic, to write to our multi-tenanted single topic. That path does not sound fun :-/

**Additional context**
Try being a smarter copy cat of Apache Kafka ;-)

**Comment by tjprescott** [comment]
@kashifkhan or @swathipil could you take a look at @amaendeepm's question?

**Comment by kashifkhan** [comment]
Hi @amaendeepm, 

Thank you for your feedback. Each client (producer or consumer) is bound to a specific Event Hub instance itself and not to the namespace, so you would need to have a separate consumer per EventHub, stored in an array or have them running in background threads receiving events concurrently from their respective Event Hub instances.
