### ISSUE TITLE
[Question] How do I retrieve the outputs of each trials of a sweep job?

### ISSUE THREAD

**Issue by pievalentin** [Azure/azure-sdk-for-python#26922]
- **Package Name**:  azure.ai.ml.sweep
- **Package Version**:  1.0.0
- **Operating System**: Ubuntu
- **Python Version**: py38

I am running a Sweep job successfully on AzML and now I want to retrieve the outputs of each
trials for further exploration. 
Thing is reading the both the doc and the code I can't see how I am supposed to retrieve them. The `SweepJob` class does not seem to expose the run like hyperdrive used to.

I would love if any one could give me directions ❤️

**Comment by tjprescott** [comment]
@bandsina can you answer @pievalentin's question? cc/ @azureml-github

**Comment by luigiw** [comment]
@pievalentin you can do `ml_client.jobs.list(parent_job_name="sweep-job-name")`

**Comment by pievalentin** [comment]
@luigiw Thank you for answer.
Continuing on your answer, I have the following code:
```python
trial = next(ml_client.jobs.list(parent_job_name="upbeat_cumin_0lq28mbtln"))
mlflow.get_experiment(experiment_id=trial.experiment_name).artifact_location
```

**Comment by pievalentin** [comment]
Ok I guess I won't be able to have the same behavior as the sdk v1. Here is the closest thing I have for retrieving the ouput of a single trial of a sweep job.
```python
trial = next(ml_client.jobs.list(parent_job_name=returned_sweep_job.name))
client = mlflow.MlflowClient()
finished_mlflow_run = client.get_run(trial.name)
client.list_artifacts(finished_mlflow_run.info.run_id)
```
```bash
$ [<FileInfo: file_size=-1, is_dir=True, path='outputs'>,
 <FileInfo: file_size=-1, is_dir=True, path='system_logs'>,
 <FileInfo: file_size=-1, is_dir=True, path='user_logs'>]
```
Now you can doanload the output directory. 
```python
mlflow.artifacts.download_artifacts(run_id=finished_mlflow_run.info.run_id, artifact_path ="outputs",dst_path='sweep_trial_outputs')
```
I am not sure if the mlflow API enable file renaming

Hope this help someone in the future

**Comment by luigiw** [comment]
@pievalentin thx for sharing your solution. Another thing you can try is `ml_client.jobs.download(name=trial.name)`
