### ISSUE TITLE
Unable to install azureml-mlflow and azure-ai-ml due to conflicting dependencies

### ISSUE THREAD

**Issue by 0xfabioo** [Azure/azure-sdk-for-python#26947]
- **Package Name**: azureml-mlflow, azure-ai-ml
- **Package Version**: azureml-mlflow==1.4.0 and azure-ai-ml==1.0.0
- **Operating System**: Linux
- **Python Version**: 3.9

**Describe the bug**
Unable to install azureml-mlflow and azure-ai-ml due to conflicting dependencies. See screenshot below,

**To Reproduce**
1. pip install azure-ai-ml
2. pip install azureml-mlflow

**Expected behavior**
Installation should be successful. Both packages need to work together.  

**Screenshots**

![image](https://user-images.githubusercontent.com/1413985/196899868-f6b1b1a6-a2b9-44dc-b970-ca5150f70bd6.png)

**Comment by tjprescott** [comment]
@bandsina can you offer any advice to @fc90? cc/ @azureml-github

**Comment by harneetvirk** [comment]
We tried installing both azure-ai-ml and azureml-flow together as part of the same command in the conda environment, but pip didn't report any compatibility issues.

(azmlflow39) C:\Users\test>pip install azureml-mlflow azure-ai-ml
Collecting azureml-mlflow
  Downloading azureml_mlflow-1.46.0-py3-none-any.whl (811 kB)
     ---------------------------------------- 811.6/811.6 kB 12.7 MB/s eta 0:00:00
Collecting azure-ai-ml
  Downloading azure_ai_ml-1.0.0-py3-none-any.whl (4.0 MB)
     ---------------------------------------- 4.0/4.0 MB 10.6 MB/s eta 0:00:00
Collecting azure-mgmt-core<2.0.0,>=1.2.0
  Using cached azure_mgmt_core-1.3.2-py3-none-any.whl (26 kB)
Collecting azure-storage-blob<=12.13.0,>=12.5.0
  Using cached azure_storage_blob-12.13.0-py3-none-any.whl (377 kB)
Collecting azure-common<2.0.0,>=1.1
  Using cached azure_common-1.1.28-py2.py3-none-any.whl (14 kB)
Collecting azure-core!=1.22.0,<2.0.0,>=1.8.0
  Downloading azure_core-1.26.0-py3-none-any.whl (178 kB)
     ---------------------------------------- 178.9/178.9 kB 10.5 MB/s eta 0:00:00
Collecting jsonpickle
  Using cached jsonpickle-2.2.0-py2.py3-none-any.whl (39 kB)
Collecting msrest>=0.6.18
  Using cached msrest-0.7.1-py3-none-any.whl (85 kB)
Collecting cryptography
  Downloading cryptography-38.0.1-cp36-abi3-win_amd64.whl (2.4 MB)
     ---------------------------------------- 2.4/2.4 MB 11.1 MB/s eta 0:00:00
Collecting python-dateutil<3.0.0,>=2.7.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting mlflow-skinny
  Downloading mlflow_skinny-1.29.0-py3-none-any.whl (3.6 MB)
     ---------------------------------------- 3.6/3.6 MB 10.9 MB/s eta 0:00:00
Collecting azure-identity
  Downloading azure_identity-1.11.0-py3-none-any.whl (136 kB)
     ---------------------------------------- 136.9/136.9 kB ? eta 0:00:00
Collecting strictyaml<=1.6.1
  Using cached strictyaml-1.6.1.tar.gz (137 kB)
  Preparing metadata (setup.py) ... done
Collecting isodate
  Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Collecting tqdm<=4.63.0
  Using cached tqdm-4.63.0-py2.py3-none-any.whl (76 kB)
Collecting colorama<=0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting pyjwt<3.0.0
  Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
Collecting pydash<6.0.0
  Downloading pydash-5.1.1-py3-none-any.whl (84 kB)
     ---------------------------------------- 84.9/84.9 kB 4.7 MB/s eta 0:00:00
Collecting azure-storage-file-share<13.0.0
  Downloading azure_storage_file_share-12.10.1-py3-none-any.whl (252 kB)
     ---------------------------------------- 252.5/252.5 kB 15.1 MB/s eta 0:00:00
Collecting typing-extensions<5.0.0
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting azure-storage-file-datalake<13.0.0
  Downloading azure_storage_file_datalake-12.9.1-py3-none-any.whl (238 kB)
     ---------------------------------------- 238.8/238.8 kB 7.4 MB/s eta 0:00:00
Collecting pyyaml<7.0.0,>=5.1.0
  Downloading PyYAML-6.0-cp39-cp39-win_amd64.whl (151 kB)
     ---------------------------------------- 151.6/151.6 kB 8.8 MB/s eta 0:00:00
Collecting jsonschema<5.0.0,>=4.0.0
  Using cached jsonschema-4.16.0-py3-none-any.whl (83 kB)
Collecting marshmallow<4.0.0,>=3.5
  Downloading marshmallow-3.18.0-py3-none-any.whl (48 kB)
     ---------------------------------------- 48.8/48.8 kB 2.4 MB/s eta 0:00:00
Collecting requests>=2.18.4
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting six>=1.11.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting azure-storage-file-datalake<13.0.0
  Downloading azure_storage_file_datalake-12.9.0-py3-none-any.whl (238 kB)
     ---------------------------------------- 238.8/238.8 kB 7.4 MB/s eta 0:00:00
  Downloading azure_storage_file_datalake-12.8.0-py3-none-any.whl (225 kB)
     ---------------------------------------- 225.1/225.1 kB 14.3 MB/s eta 0:00:00
Collecting cffi>=1.12
  Using cached cffi-1.15.1-cp39-cp39-win_amd64.whl (179 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.18.1-cp39-cp39-win_amd64.whl (61 kB)
Collecting attrs>=17.4.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting packaging>=17.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting requests-oauthlib>=0.5.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\test\miniconda3\envs\azmlflow39\lib\site-packages (from msrest>=0.6.18->azureml-mlflow) (2022.9.24)
Collecting msal<2.0.0,>=1.12.0
  Downloading msal-1.20.0-py2.py3-none-any.whl (90 kB)
     ---------------------------------------- 90.0/90.0 kB ? eta 0:00:00
Collecting msal-extensions<2.0.0,>=0.3.0
  Using cached msal_extensions-1.0.0-py2.py3-none-any.whl (19 kB)
Collecting pytz<2023
  Downloading pytz-2022.5-py2.py3-none-any.whl (500 kB)
     ---------------------------------------- 500.7/500.7 kB 10.7 MB/s eta 0:00:00
Collecting click<9,>=7.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting protobuf<5,>=3.12.0
  Downloading protobuf-4.21.8-cp39-cp39-win_amd64.whl (525 kB)
     ---------------------------------------- 525.4/525.4 kB 16.6 MB/s eta 0:00:00
Collecting cloudpickle<3
  Downloading cloudpickle-2.2.0-py3-none-any.whl (25 kB)
Collecting sqlparse<1,>=0.4.0
  Downloading sqlparse-0.4.3-py3-none-any.whl (42 kB)
     ---------------------------------------- 42.8/42.8 kB ? eta 0:00:00
Collecting importlib-metadata!=4.7.0,<5,>=3.7.0
  Downloading importlib_metadata-4.13.0-py3-none-any.whl (23 kB)
Collecting databricks-cli<1,>=0.8.7
  Downloading databricks-cli-0.17.3.tar.gz (77 kB)
     ---------------------------------------- 77.9/77.9 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gitpython<4,>=2.1.0
  Downloading GitPython-3.1.29-py3-none-any.whl (182 kB)
     ---------------------------------------- 182.5/182.5 kB 10.8 MB/s eta 0:00:00
Collecting entrypoints<1
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting oauthlib>=3.1.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ---------------------------------------- 151.7/151.7 kB 8.8 MB/s eta 0:00:00
Collecting tabulate>=0.7.7
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.9-py3-none-any.whl (63 kB)
Collecting zipp>=0.5
  Downloading zipp-3.9.0-py3-none-any.whl (5.8 kB)
Collecting portalocker<3,>=1.6
  Downloading portalocker-2.6.0-py2.py3-none-any.whl (15 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting smmap<6,>=3.0.1
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting pywin32>=226
  Using cached pywin32-304-cp39-cp39-win_amd64.whl (12.2 MB)
Building wheels for collected packages: strictyaml, databricks-cli
  Building wheel for strictyaml (setup.py) ... done
  Created wheel for strictyaml: filename=strictyaml-1.6.1-py3-none-any.whl size=123916 sha256=858f3dd2980d33767536d145c8d0b19b3847533066f0bb37621fea09e3e1b68d
  Stored in directory: c:\users\test\appdata\local\pip\cache\wheels\cf\75\47\80052b1dbf92c00557e3febe22c84da4a15e1f509d8c6b393a
  Building wheel for databricks-cli (setup.py) ... done
  Created wheel for databricks-cli: filename=databricks_cli-0.17.3-py3-none-any.whl size=139084 sha256=6e7d8e6d6d196a14d47fdbd6c8c1c091720d1a2d1e6aea494e1c44da61038511
  Stored in directory: c:\users\test\appdata\local\pip\cache\wheels\7b\ef\c5\85718fa9e66dec117e42d8b4d7b8a2e40ebdec17232935615f
Successfully built strictyaml databricks-cli
Installing collected packages: pywin32, pytz, azure-common, zipp, urllib3, typing-extensions, tabulate, sqlparse, smmap, six, pyyaml, pyrsistent, pyparsing, pyjwt, pydash, pycparser, protobuf, portalocker, oauthlib, jsonpickle, idna, entrypoints, colorama, cloudpickle, charset-normalizer, attrs, tqdm, requests, python-dateutil, packaging, jsonschema, isodate, importlib-metadata, gitdb, click, cffi, strictyaml, requests-oauthlib, marshmallow, gitpython, databricks-cli, cryptography, azure-core, msrest, mlflow-skinny, azure-mgmt-core, msal, azure-storage-file-share, azure-storage-blob, msal-extensions, azure-storage-file-datalake, azure-identity, azure-ai-ml, azureml-mlflow
Successfully installed attrs-22.1.0 azure-ai-ml-1.0.0 azure-common-1.1.28 azure-core-1.26.0 azure-identity-1.11.0 azure-mgmt-core-1.3.2 azure-storage-blob-12.13.0 azure-storage-file-datalake-12.8.0 azure-storage-file-share-12.10.1 azureml-mlflow-1.46.0 cffi-1.15.1 charset-normalizer-2.1.1 click-8.1.3 cloudpickle-2.2.0 colorama-0.4.4 cryptography-38.0.1 databricks-cli-0.17.3 entrypoints-0.4 gitdb-4.0.9 gitpython-3.1.29 idna-3.4 importlib-metadata-4.13.0 isodate-0.6.1 jsonpickle-2.2.0 jsonschema-4.16.0 marshmallow-3.18.0 mlflow-skinny-1.29.0 msal-1.20.0 msal-extensions-1.0.0 msrest-0.7.1 oauthlib-3.2.2 packaging-21.3 portalocker-2.6.0 protobuf-4.21.8 pycparser-2.21 pydash-5.1.1 pyjwt-2.6.0 pyparsing-3.0.9 pyrsistent-0.18.1 python-dateutil-2.8.2 pytz-2022.5 pywin32-304 pyyaml-6.0 requests-2.28.1 requests-oauthlib-1.3.1 six-1.16.0 smmap-5.0.0 sqlparse-0.4.3 strictyaml-1.6.1 tabulate-0.9.0 tqdm-4.63.0 typing-extensions-4.4.0 urllib3-1.26.12 zipp-3.9.0

(azmlflow39) C:\Users\test>

Pip list shows the following installed packages/versions that meets the version compatibilities of both azure-ai-ml and azureml-mlflow package:
azure-ai-ml                 1.0.0
azure-storage-blob          12.13.0
azure-storage-file-datalake 12.8.0
azure-storage-file-share    12.10.1
azureml-mlflow              1.46.0

**Comment by fc90** [comment]
@harneetvirk and @tjprescott Thank you for the quick help. We are using pip-compile to generate a requirements.txt from a requirements.in file, and the screenshot is actually the output of this tool. It seems to be an issue of pip-compile which is not able to resolve the dependencies. After adding the constraint **azure-storage-file-datalake<12.9** manually, it's now working.
