### ISSUE TITLE
amlsdkfeedback@microsoft.com is no longer a live email address

### ISSUE THREAD

**Issue by nswitanek** [Azure/azure-sdk-for-python#26951]
We invite feedback on SDK v2 on the README of https://github.com/Azure/azureml-examples/tree/sdk-preview/sdk, but the linked email address, amlsdkfeedback@microsoft.com, is no longer valid.

Please either update the email address or direct all feedback to github issues.

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by harneetvirk** [comment]
The main branch has been updated to include the instructions to share the feedback with the product team:
https://github.com/Azure/azureml-examples/tree/main/sdk/python
