### ISSUE TITLE
Unable to connect to blob storage from AzureML notebook (using abfss: method)

### ISSUE THREAD

**Issue by skylernorgaard-syk** [Azure/azure-sdk-for-python#26959]
- **Package Name**: AzureML Notebook (with AzureML SDK V2)
- **Package Version**: 2
- **Operating System**: AzureML notebook
- **Python Version**: 3.10

**Describe the bug**
We’re facing some challenges when trying to (easily) connect to the data in our Azure blob storage from an AzureML notebook. In the [docs](https://learn.microsoft.com/en-us/azure/machine-learning/concept-data?tabs=uri-file-example%2Ccli-data-create-example), I see that it should be possible to access it using this format: abfss://<file_system>@<account_name>.dfs.core.windows.net/<folder>/<file>), but when I try that format in a normal AzureML notebook (vs a compute job), I get an authentication error. I also registered the container as a datastore, but was only seeing options for downloading from the datastore versus reading data directly from it.

In a Synapse notebook, I can use the same format as above, and it seems like the connection already exists. So I was wondering if it’s possible to do something similar from an AzureML notebook / if there’s an extra piece of code I can add that authorizes all connections to the storage account within the AzureML session.

**To Reproduce**
1. import pandas as pd
2. path1 = "abfss://contract-ai@stgdacustintelldev001.dfs.core.windows.net/3-ml-data/mad_squad_answers_V1.csv"
3. df = pd.read_csv(path1)

**Expected behavior**
I would expect for us to be able to load data from blob storage.

**Screenshots**
![image](https://user-images.githubusercontent.com/112725077/197046618-f5191e4c-f4d8-4600-a057-045aa7f6883b.png)

**Additional context**
We are working on this project with a technical architect from Microsoft. He recommended that I submit a bug report on this.

**Comment by tjprescott** [comment]
@bandsina please take a look at @skylernorgaard-syk's question. cc @azureml-github

**Comment by luigiw** [comment]
@skylernorgaard-syk, thx for your feedback. The support of this will come up very soon.

**Comment by navba-MSFT** [comment]
@luigiw Any update on this ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@skylernorgaard-syk A quick question, When you registered the container as a datastore what sort of authentication method were you using?

**Comment by skylernorgaard-syk** [comment]
@navba-MSFT we used the "Account key" type. However, in the above example, we were hoping to connect to ADLS using a more general container + blob URL (that works in other Microsoft features like synapse) vs utilizing the datastore feature

**Comment by navba-MSFT** [comment]
@skylernorgaard-syk I don't think we support any feature that authorizes all connections to the storage account in a session. You might have to use a datastore to connect your storage account using either a sas token or account key.
 
https://learn.microsoft.com/en-us/azure/machine-learning/concept-data?tabs=uri-folder-example%2Ccli-data-consume-example#datastore

**Comment by navba-MSFT** [comment]
@skylernorgaard-syk I hope you had a chance to look at the above comment. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
