### ISSUE TITLE
package azureml-* v2 for conda-forge 

### ISSUE THREAD

**Issue by h-vetinari** [Azure/azure-sdk-for-python#26968]
> Closing legacy issue. @h-vetinari please create a new issue if you have the same ask for AzureML SDK v2 packages.
>
> https://learn.microsoft.com/en-us/azure/machine-learning/concept-v2

_Originally posted by @luigiw in https://github.com/Azure/azure-sdk-for-python/issues/21713#issuecomment-1286295527_

Not legacy, need is still there.

**Comment by tjprescott** [comment]
@bandsina please take a look at @h-vetinari's issue. cc @azureml-github

**Comment by lmazuel** [comment]
@xiangyan99 actually this one is for you, add `azure-ai-ml` to our conda channel. 

cc @annatisch

**Comment by xiangyan99** [comment]
FYI. azure-ai-ml package for conda has been shipped. You can find it at https://anaconda.org/microsoft/azure-ai-ml.

(https://anaconda.org/microsoft is our official channel)

**Comment by h-vetinari** [comment]
Hey all, thanks for shipping this!

Are the recipes publicly visible somewhere? Would you be willing to add them to conda-forge (or have them be added there)? We run a lot of infrastructure automation, so there wouldn't even have to be manual intervention assuming that new versions build fine and pass the tests (that is, except updating lower & upper bounds of dependencies, unfortunately)...

I'm asking because - unless that Microsoft channel has exclusively python-only packages (i.e. no compiled code), it is strongly advised against to mix channels (as in: adding the Microsoft channel to an existing setup using conda-forge), because different channels might use different toolchains, versions, flags, etc. and so ABI compatibility cannot be guaranteed.

As such it would be a real benefit to everyone to publish these packages through conda-forge (also people who are fine with using the Microsoft channel in principle, for better interop with the biggest packaging ecosystem in conda-land).

I'd be willing to help you get started, if you need any pointers...

/unresolve

**Comment by xiangyan99** [comment]
This is the recipe we used to generate the conda package: https://gist.github.com/xiangyan99/7c1a585cce794fe3bf53d90f76ea791d

Unfortunately, we don't publish and maintain our conda packages directly to conda-forge.

Most of the packages in Microsoft channel are python-only (including azure-ai-ml). As you can see in https://anaconda.org/Microsoft/repo, we consolidated the package versions and dependencies to make them easier to use.

If you want to port the pypi one to conda-forge, you can just run 'conda skeleton pypi azure-ai-ml' to get the receipe.
