### ISSUE TITLE
Any operation on ledger client in Azure Confidential Ledger faced with NotAllowed error

### ISSUE THREAD

**Issue by GyroKGL** [Azure/azure-sdk-for-python#26979]
- **Package Name**: azure-confidentialledger
- **Package Version**: 1.0.0
- **Operating System**: Windows 10
- **Python Version**: 3.10.6

**Describe the bug**
 Azure Confidential Ledger client created in Python cannot execute any operations like `create_ledger_entry` or `get_user` and faces with `HttpResponseError: (NotAllowed) Not allowed to call POST`

**To Reproduce**
The Following code was used with the correct environment variables from the AAD App registered:

```
from azure.confidentialledger import ConfidentialLedgerClient
from azure.confidentialledger.certificate import ConfidentialLedgerCertificateClient
from azure.identity import DefaultAzureCredential, EnvironmentCredential

resource_group = "myResourceGroup"
ledger_name = "<your-unique-ledger-name>"
subscription_id = "<azure-subscription-id>"

identity_url = "https://identity.confidential-ledger.core.azure.com"
ledger_url = "https://" + ledger_name + ".confidential-ledger.azure.com"

identity_client = ConfidentialLedgerCertificateClient()
network_identity = identity_client.get_ledger_identity(
    ledger_id=ledger_name
)

ledger_tls_cert_file_name = "ledger_certificate.pem"
with open(ledger_tls_cert_file_name, "w") as cert_file:
    cert_file.write(network_identity["ledgerTlsCertificate"])

credential = DefaultAzureCredential()
ledger_client = ConfidentialLedgerClient(
    endpoint=ledger_url,
    credential=credential,
    ledger_certificate_path=ledger_tls_cert_file_name 
)

post_entry_result = ledger_client.create_ledger_entry(
        entry = {"contents": "Hello world!"}
    )
```

**Expected behavior**
The ledger entry was supposed to be appended successfully so that it could be later retrieved.

**Screenshots**
![image](https://user-images.githubusercontent.com/116369058/197229203-20e95b9b-acaf-435d-b8ff-c666e17b839f.png)

**Additional context**
The client `ledger_client` was successfully created with the correct credentials and environment variables. Only when the client is used to perform any operations on the ledger, the `HttpResponseError: (NotAllowed)` issue is faced.

**Comment by tjprescott** [comment]
@SaurabhSharma-MSFT can you route @GyroKGL's question to the Confidential Ledger team?

**Comment by lynshi** [comment]
Hi @GyroKGL, sorry for the inconvenience! This can happen if the identity retrieved by `DefaultAzureCredential` is not registered in the Confidential Ledger as an allowed user. Some possible explanations:
1. Multiple identities are available in the environment in which you have run the code. For example, the code is run on a virtual machine with an assigned identity and you have separately logged in to Azure CLI. [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python) has an order in which it checks for available credentials, so it's possible one of the credentials with higher priority was used thus skipping a later credential type that would be allowed to access the Confidential Ledger. To avoid this, you can use an explicit credential type, such as `EnvironmentCredential` or `AzureCliCredential`, that is designed for how you are providing credentials.
2. It sounds like you are attempting to authenticate with the Confidential Ledger using an AAD App. This AAD app may not have been correctly added to the Confidential Ledger service as a user. Note that the AAD App should have been added as a user by the object id of its Enterprise application, _not_ its application (client) id [0].

[0] - An AAD app may show up as both an `Enterprise applications` resource (URL looks like `https://ms.portal.azure.com/#view/Microsoft_AAD_IAM/ManagedAppMenuBlade/...`) and a `App registrations` resource (URL looks like `https://ms.portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/...`) in Azure Portal. This is unfortunately confusing, but the object id that should be registered with the Confidential Ledger is the object id of the `Enterprise application`.

**Comment by GyroKGL** [comment]
@lynshi Thank you for the clear explanation! The problem was solved by **adding the AAD app as a user using the object id of its Enterprise application** and also by using an explicit authentication credential, other than the `DefaultAzureCredential` shown in the example above.

Thank you so much!
