### ISSUE TITLE
`SharedTokenCacheCredential` with Custom `TokenCachePersistenceOptions` Does Not Persist

### ISSUE THREAD

**Issue by poocat** [Azure/azure-sdk-for-python#26982]
I am not getting the `SharedTokenCacheCredential` to work as expected. Considering the following script:

```
from azure.identity import (
    ChainedTokenCredential,
    InteractiveBrowserCredential,
    TokenCachePersistenceOptions,
)

TENANT_ID = "..."
cache_options = TokenCachePersistenceOptions(name="my.cache")

credential = ChainedTokenCredential(
    SharedTokenCacheCredential(
        tenant_id=TENANT_ID,
        cache_persistence_options=cache_options
    ),
    InteractiveBrowserCredential(
        tenant_id=TENANT_ID,
        cache_persistence_options=cache_options,
    )
)
credential.get_token(...)
```

The first time, it runs as expected. At `credential.get_token(...)`, a browser tab opens and I am prompted to sign in. On successful sign in, it generates the token, and the script returns.

On all subsequent runs, it does _not_ behave as expected.

- **Expected:** the token should be in the persistent cache, and thus, the `SharedTokenCacheCredential` should be used, and I should not be prompted to sign in again.
- **Actual:** it opens another browser tab and prompts me to sign in again, and prints the following to the terminal: `SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.`

The following workaround yields the expected behavior, but uses a "private" function from the `azure.identity` package.

```diff
from azure.identity import (
    ChainedTokenCredential,
    InteractiveBrowserCredential,
    TokenCachePersistenceOptions,
)
+from azure.identity._persistent_cache import _load_persistent_cache

TENANT_ID = "..."
cache_options = TokenCachePersistenceOptions(name="my.cache")

credential = ChainedTokenCredential(
    SharedTokenCacheCredential(
        tenant_id=TENANT_ID,
        cache_persistence_options=cache_options,
+        _cache=_load_persistent_cache(cache_options),
    ),
    InteractiveBrowserCredential(
        tenant_id=TENANT_ID,
        cache_persistence_options=cache_options,
    )
)
credential.get_token(...)
```

My question is: _is there another solution that uses the "public" api?_

My setup:
- OS: macOS Monterey (12.1)
- python: 3.7.15
- azure-identity: 1.11.0

**Comment by pvaneck** [comment]
Hey, @poocat. Thanks for reporting the issue.

Can you try setting the cache name to "msal.cache" (the default cache name) or removing `cache_persistence_options` from each of the credentials? I believe the custom cache name may not be propagating correctly, and `SharedTokenCacheCredential` keeps looking for "msal.cache" (which doesn't exist) instead of "my.cache".

**Comment by poocat** [comment]
> Hey, @poocat. Thanks for reporting the issue.
> 
> Can you try setting the cache name to "msal.cache" (the default cache name) or removing `cache_persistence_options` from each of the credentials? I believe the custom cache name may not be propagating correctly, and `SharedTokenCacheCredential` keeps looking for "msal.cache" (which doesn't exist) instead of "my.cache".

@pvaneck thank you very much for your reply.

Switching the name to `"msal.cache"` worked!

Removing `cache_persistence_options` did not.

**Comment by poocat** [comment]
> Hi @poocat. Thank you for opening this issue and giving us the opportunity to assist. We believe that this has been addressed. If you feel that further discussion is needed, please add a comment with the text “`/unresolve`” to remove the “issue-addressed” label and continue the conversation.

Yes, it has been addressed. Thank you!

In the meantime, until the bug gets fixed in a later release, it might be best to change the [documentation](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.tokencachepersistenceoptions?view=azure-python) so that it does not urge you in an enormous font to "specify a cache name to isolate the cache from other applications".

**Comment by pvaneck** [comment]
Hah, yea, the formatting is messed up on that doc page and will be fixed in the next release. Meanwhile, I opened #27030 which should fix the issue here.
