### ISSUE TITLE
[azure-mgmt-web] 0.35.0  vs 0.34.1 : TypeError __init__() missing 1 required positional argument: 'app_service_plan_name'

### ISSUE THREAD

**Issue by antonisppn** [Azure/azure-sdk-for-python#2698]
Hello, 

I was trying to run an Azure Sample code that I found on the https://github.com/Azure-Samples/app-service-web-python-manage

At first, I am trying to run the commands in a python 3.5 virtualenv with version 0.35.0 and I am getting TypeError: __init__() missing 1 required positional argument: 'app_service_plan_name'

This is the related code snippet. 

from azure.mgmt.web.models import AppServicePlan, SkuDescription, Site

service_plan_async_operation = web_client.app_service_plans.create_or_update(
    GROUP_NAME,
    SERVER_FARM_NAME,
    AppServicePlan(
        location=WEST_US,
        sku=SkuDescription(
            name='S1',
            capacity=1,
            tier='Standard'
        )
    )
)

With the previous version 0.34.1 everything runs smoothly

**Comment by lmazuel** [comment]
Hi @antonisppn 
The sample is written for the version 0.32.0 and was not updated to support 0.35.0.

Even that class itself is not mentioned explicitly, breaking changes were expected in 0.35.0 and advertised in the ChangeLog:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-web/HISTORY.rst#0350-2018-02-20

> Many models signature changed to expose correctly required parameters.

I keep this issue open to update the sample, but the SDK itself is as expected.

Thank for the report :)

**Comment by lmazuel** [comment]
Fixed in https://github.com/Azure-Samples/app-service-web-python-manage/commit/42ee64f5d0766f74029c18b60be12001758ae925
