### ISSUE TITLE
MLTable and Azure ML Datasets

### ISSUE THREAD

**Issue by adrianomartinelli** [Azure/azure-sdk-for-python#27058]
Hi,

I am trying to register a dataset with azure ml studio. I have my MLTable artifact on the azure blob store (access level: container).
I am able to load the MLTable with: 

```
url = https://<account_name>.blob.core.windows.net/<container_name>/path
tbl = mltable.load(uri=url)
df = tbl.to_pandas_dataframe()
``` 
However, if I try to register this dataset with:
```
my_data = Data(
    path=url,
    type=AssetTypes.MLTABLE,
    description="test",
    name="test-mltable",
)

ml_client.data.create_or_update(my_data)
```

I get the error
```
Invalid URL 'https:/<account_name>.blob.core.windows.net/<container_name>/<path>/MLTable': No host supplied
```
There is a missing `/` in the URL of the error message which might be a problem?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23d04020-3ab4-b2f2-558f-e90cdb1c1ea3
* Version Independent ID: 5ee94e1d-c95d-6def-dfbb-f31979170ed5
* Content: [azure.ai.ml.entities.Data class](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.data?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.Data.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.Data.yml)
* Service: **machine-learning**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by swathipil** [comment]
Hi @adrianomartinelli - Thanks for your bug report! Tagging the right people to take care of this.

**Comment by swathipil** [comment]
@azureml-github - can you take a look at this?

**Comment by pritamDas9191** [comment]
@adrianomartinelli This error is a non blocking one. You should still be able to successfully create your data asset. 
 This error occurs while validating MLTable schema and hence is supposed to non blocking which skips validation and creates the data asset.
 As for fixing the issue for validation(url problem you noticed) , the fix is in a PR and will be fixed as part of next release.
