### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by potiuk** [Azure/azure-sdk-for-python#27066]
**Is your feature request related to a problem? Please describe.**

I know it is eaarly (Python 3.11 has just been released yesterday) but we are hoping in Apache Airflow to a much faster cycle of adding new Python releases - especially that Pyhon 3.11 introduces huge performance improvements (25% is the average number claimed) due to a very focused effort to increase single-threaded Python performance (Specialized interpreter being the core of it but also many other improvements) without actually changing any of the Python code.

**Describe the solution you'd like**

I'd appreciate if someone in the Azure team attempted to migrate and have a PR running (and failing possibly until all prerequisite are met so that we can also track the progress and possibly help each other to solve any problems (and mark the package as Python 3.11 read with the next release). For azure also the uamqp is the problem but it is being worked on in https://github.com/Azure/azure-uamqp-python/issues/334 in similar manner.

**Describe alternatives you've considered**

Alternative is to remove apache-airflow-providers-microsoft-azure from the set of providers that support Python 3.11 when we release Airflow compatible with 3.11. This means that users of Airflow will not be able to use Azure integration. OUr 

**Additional context**
The azure-core is one of the dependencies of Airlfow that need to support newer Python version so this issue is here to make you aware that we are eaager (also to help if needed) to make it faster, possibly by talking to dependencies of Beam as well (who are oftten also direct dependencies of Airflow) and help them as well. I perfectly understand we need to bubble up support so that your dependencies support them first.

Nice summary of Py3.11 support is here: https://pyreadiness.org/3.11/ - it's not very green obviously, but I hope it gets greener soon.

I just opened such PR in Apache Airflow yesterday and plan to keep it open until it gets green :)

https://github.com/apache/airflow/pull/27264

I think it would be fantastic if we could as the open source community migrate to the new Python much faster.

Looking forward to cooperation on that one :)

**Comment by swathipil** [comment]
Hi @potiuk - We're actually planning to release azure-core (+ many other `azure-*` libraries!) with Python 3.11 support in the upcoming November release cycle. We're targeting 11/3/2022 for azure-core release.

Side note: We're targeting next week for the `uamqp` with Python 3.11 support release. 🙂

Thanks!

**Comment by potiuk** [comment]
Fantastic news!
