### ISSUE TITLE
[Container Instances] ContainerGroups list method result doesn't have instance_view info

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-sdk-for-python#27068]
- **Package Name**: azure-mgmt-containerinstance
- **Package Version**:  10.0.0
- **Operating System**: Mac OS
- **Python Version**:  3.8

**Describe the bug**
- container_groups of ContainerInstanceManagementClient list method can't collect `instance_view` info of container filed.

**To Reproduce**
1. Create Azure Container Instances
2. Get resource info using `ContainerInstanceManagementClient.container_groups.list()`
3. Get resource info using `ContainerInstanceManagementClient.container_groups.get()`
4. Compare result and check instance_view info in container field then `get` result has `instance_view` info but `list` result don't

**Expected behavior**

**Screenshots**
Here are screen shots.
- list_by_resource_group()
![image](https://user-images.githubusercontent.com/38625842/197451808-b86d4731-77c1-4674-881a-0387b12f40a4.png)

- get()
![image](https://user-images.githubusercontent.com/38625842/197452195-fe267d56-8cc6-4bd3-8b6d-72b2412f2725.png)

**Additional context**
I already reported issue [here](https://github.com/Azure/azure-rest-api-specs/issues/21280) and @Wzb123456789 recommended this issue to transfer here  
so if you follow up history of this issue go to the link.

**Comment by swathipil** [comment]
Hi @ImMin5 - Thanks for your report! We'll investigate asap!

**Comment by msyyc** [comment]
according to our investigation, it is the service issue so we transfer it to proper respo: https://github.com/Azure/azure-rest-api-specs/issues/21280. Please wait for the response of service team. Thanks!

**Comment by ImMin5** [comment]
/unresolve

Hi, Is this Issue solved?

**Comment by ImMin5** [comment]
Hi, @Wzb123456789 

I got it..! 

Thanks :)
