### ISSUE TITLE
[Web PubSub Service] web_pub_sub's get and list method doesn't work

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-sdk-for-python#27071]
- **Package Name**: azure-mgmt-webpubsub
- **Package Version**: 1.0.0
- **Operating System**: Mac OS
- **Python Version**:  3.8

**Describe the bug**

In my case, web_pub_sub's methods didn't work.
they returned `None`.
- get()
- list_by_subsrciption()
- list_by_resource_group()

I refered to these sites
- sdk reference
  - https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/webpubsub/azure-mgmt-webpubsub/azure/mgmt/webpubsub/operations/_web_pub_sub_operations.py
- rest api reference
  - https://learn.microsoft.com/en-us/rest/api/webpubsub/controlplane/web-pub-sub/list-by-subscription?tabs=HTTP&tryIt=true&source=docs#code-try-0

**To Reproduce**
1. Create Azure `Web PubSub Service`
2. Get resources using by `web_pubsub_service_client.web_pub_sub.list_by_subscription()` sdk method 
3. Get resources using by `GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.SignalRService/webPubSub?api-version=2022-08-01-preview` REST API method
4. Compare results then you can see sdk method didn't have any resource info about `Web PubSub Service`

**Expected behavior**

**Screenshots**

**Additional context**

It seems there is no document about `Web PubSub Service` for python sdk on the website.
- https://learn.microsoft.com/en-us/python/api/overview/azure/?view=azure-python

**Comment by swathipil** [comment]
Hi @ImMin5 - Thanks for opening an issue! Tagging the right people to take a look asap!

**Comment by ImMin5** [comment]
Hi, @swathipil, @msyyc 
I solved this problem. I was my bad.
So you guys do close or delete this issue.
But I think people need document on website about `azure-mgmt-webpubsub`.
-  https://learn.microsoft.com/en-us/python/api/overview/azure/web-pubsub?view=azure-python

**Comment by swathipil** [comment]
Hi @msyyc - Confirming that I can't find documentation for `azure-mgmt-webpubsub` in the [docs.microsoft.com](https://learn.microsoft.com/python/api/azure-messaging-webpubsubservice/azure.messaging.webpubsubservice.webpubsubserviceclient?view=azure-python) site.

The links in the "[Usage" section](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/webpubsub/azure-mgmt-webpubsub#usage) of the `azure-mgmt-webpubsub` README.md don't point to API docs either. I believe these need to be updated.

**Comment by msyyc** [comment]
Got it. And we will update the doc link asap

**Comment by ImMin5** [comment]
Hi, @msyyc 
I saw your PR!
I am waiting for merge

**Comment by msyyc** [comment]
related issue: https://github.com/Azure/azure-sdk-for-python/issues/21346
