### ISSUE TITLE
Let Azure Storage get_blob_properties() return part of the properties

### ISSUE THREAD

**Issue by yedeng-anomali** [Azure/azure-sdk-for-python#27074]
Testing env:
`azure-core==1.24.0`
`azure-storage-blob==12.10.0`
`Operating System: Ubuntu, Mac OS`

Azure Storage blob related APIs provide a function called `get_blob_properties` to return the properties of a blob.
We are using it to poll a blob to check its current properties (e.g. blob size). However, we find that there is no way to define what selected property fields to return. The whole returned property dictionary is pretty big (like 1k~2k), which is not very optimized for our usage scenario. Here below is a simplest code snippet to show our usage scenario.
Would you give `get_blob_properties` a new parameter to select the returned property fields? Like `get_blob_properties(... selected_properties=['creation_time', 'size'])`

```
from azure.storage.blob import BlobServiceClient

CONNECTION_STR = 'DefaultEndpointsProtocol=https;AccountName={};AccountKey={};EndpointSuffix=core.windows.net'
ACCOUNTNAME = 'storems365def'
ACCOUNTKEY = "************key_masked************"

CONTAINERNAME = "insights-logs-advancedhunting-emailevents"
BLOBNAME = "tenantId=8ab4b9aa-f07b-4927-a103-c20e857620a8/y=2022/m=10/d=07/h=22/m=00/PT1H.json"

blob_service_client_instance = BlobServiceClient.from_connection_string(
    CONNECTION_STR.format(ACCOUNTNAME, ACCOUNTKEY))

blob_client_instance = blob_service_client_instance.get_blob_client(
    CONTAINERNAME, BLOBNAME)

# The returned blob_properties is 1k~2k big. We need to make this call multiple times.
blob_properties = blob_client_instance.get_blob_properties()

# We only want these two fields below
print(blob_properties['size'])
print(blob_properties['creation_time'])

```

**Comment by swathipil** [comment]
Hi @yedeng-anomali - Thanks for opening an issue! Directing this to the right people.

**Comment by jalauzon-msft** [comment]
Hi @yedeng-anomali, are you concerned about the properties size from a network perspective or a client memory perspective? If it's from a network perspective, there is likely not much that can be done as the [service API](https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob-properties) that backs `get_blob_properties` will always return all the properties and does not support selecting only certain properties.

If you are just worried about the size from a client memory perspective, there is a possibility we could add client-side filtering, but we would still just be fetching everything from the service and only returning back what you ask for. There likely would not be much performance benefit to this.

If you wish to request this feature from the Storage service, please consider submitting this feedback via upvoting or creating a new idea at https://aka.ms/AzStorageFeedback. This will help the service team gauge interest and prioritize new features. If the feature becomes available in the service, it will be promptly added to the SDK.

**Comment by yedeng-anomali** [comment]
Hi @jalauzon-msft thanks for your reply. 
Ideally, I think we should resolve this issue from [service API](https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob-properties) side. 
Would you help me to forward this feature request to the appropriate engineering team? I filed a ticket on Azure cloud (and marked it as an Azure Storage Account related issue), and I get redirected to here.

**Comment by jalauzon-msft** [comment]
Hi @yedeng-anomali, your best bet is to make a post (or upvote an existing one) on [AzStorageFeedback](https://aka.ms/AzStorageFeedback) with the request for the service team. This will allow others to see it and possibly upvote it and help the service team prioritize feature requests. I can also forward the request along internally.

I will admit though that unfortunately the service team is quite busy, so something like this may not get much traction for some time unless they see the need for this feature increase.

**Comment by yedeng-anomali** [comment]
@jalauzon-msft 
Thanks for your suggestion. I made [a post](https://feedback.azure.com/d365community/idea/27fbe857-2f5a-ed11-a81b-000d3ae5ae95) for this on the Azure Storage forum.

**Comment by jalauzon-msft** [comment]
Thanks @yedeng-anomali! That is the best place for this type of request. I will go ahead and close this issue.
