### ISSUE TITLE
additional actions needed to restore a blob - undelete is not enough

### ISSUE THREAD

**Issue by lcasucciIT** [Azure/azure-sdk-for-python#27084]
[Enter feedback here]

In order to successfully restore a blob, undelete command is not enough.
I had to do also get the blob file url and subsequently issue a copy from url from the blob service client for that particular blob file
See this example below, basicaly the last line is what I think needs to be added to the documentation because the undelete only is not enough  :

source_blob = BlobClient(
        blob_service_client.url,
        container_name = source_container_name,
        blob_name = blob_name,
        credential = sas_token
    )
blob_delete =source_blob.undelete_blob()
copied_blob = blob_service_client.get_blob_client(container = source_container_name, blob = blob_name)
source_blob_url = account_url +"/"+ source_container_name+"/"+ blob_name +'?versionId='+ version_id
copied_blob.start_copy_from_url(source_blob_url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c573ca4-d03c-8651-5bc0-69debe989f9a
* Version Independent ID: 05961166-7e4d-6232-74b4-2607cd3318a1
* Content: [azure.storage.blob.BlobServiceClient class](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobserviceclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.BlobServiceClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-storage-blob/azure.storage.blob.BlobServiceClient.yml)
* Service: **storage**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by swathipil** [comment]
Hi @lcasucciIT - Thanks for your feedback! We'll take a look asap!

**Comment by jalauzon-msft** [comment]
Hi @lcasucciIT Lucia, thanks for the report. Just to confirm, this is the expected behavior only when "blob versioning" is enabled on the Storage account. This is documented [here](https://learn.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-manage?tabs=dotnet#restore-soft-deleted-objects-when-versioning-is-disabled-1) and [here](https://learn.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-manage?tabs=dotnet#restore-soft-deleted-blobs-when-versioning-is-enabled-1).

We can update the documentation with a note about this behavior with versioning enabled. Thanks

**Comment by lcasucciIT** [comment]
Correct,

This happens when versioning is enabled and you want to restore a specific
version.

Let me know when you update the documentation and by the way, I am a fellow
microsoft employee too :)

**Comment by jalauzon-msft** [comment]
Thanks @lcasucciIT, I just merged #27208 which included an update to the docstring for the `undelete_blob` about restoring the base blob when versioning is enabled. The docs are automatically generated from our code docstrings and therefore it will be some time before the docs online are updated. This change will need to be released and then the docs published.
