### ISSUE TITLE
How to use check if Advance Threat Protection is enabled azure-mgmt-security package? 

### ISSUE THREAD

**Issue by colbydh** [Azure/azure-sdk-for-python#27092]
I'm trying to find if ATP is enabled in my Azure subscription and having problems with the code. Am I on the right path? Here's what I have so far:

def azure_atp_enabled(client):

    security_features = client.advancedThreatProtectionSettings.get()
    if security_features.status == 'Enabled':
        result = outputs.json_results("pass")
    else:
        result = outputs.json_results("fail")

**Comment by swathipil** [comment]
Hi @colbydh - Thanks for opening an issue! Tagging the right people.

@msyyc - I wasn't able to find any `azure-mgmt-security` samples in the mgmt samples repository [[here](https://github.com/Azure-Samples/azure-samples-python-management/tree/main/samples)]. Would you be able to take a look? Thanks!

**Comment by msyyc** [comment]
@colbydh please refer to sample: https://github.com/Azure-Samples/azure-samples-python-management/tree/main/samples/security
