### ISSUE TITLE
AzureCliCredential not scoped correctly for global admin logins

### ISSUE THREAD

**Issue by skylaro** [Azure/azure-sdk-for-python#27116]
- **Package Name**: azure.identity
- **Package Version**: 1.11.0
- **Operating System**:
- **Python Version**: 3.9.13

**Describe the bug**
There exists a bug where after an 'az login' command and authentication flow completes, and then an empty AzureCliCredential is created, that the following stack trace prints:

> AzureCliCredential.get_token failed: Please run 'az login' to set up an account
> Traceback (most recent call last):
>   File "C:\Users\skylaronstot\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\azure\identity\_credentials\azure_cli.py", line 149, in _run_command
>     return subprocess.check_output(args, **kwargs)
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 424, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command **'['cmd', '/c', 'az account get-access-token --output json --resource .default']**' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:

[There is a command ](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L30) that fails if ran manually: 'az account get-access-token --output json --resource .default'.

Why is --resource needed here, and can it be removed to avoid any scoping issues?

**To Reproduce**
1. Use above package version and AzureCliCredential object to attempt login as global admin.

**Expected behavior**
Account token should pass to Python SDK without issue.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share how you used the AzureCliCredential?

If you want to use it to get a token, you need

cred = AzureCliCredential()
token = cred.get_token(SCOPE)

And the SCOPE will be used in the --resource argument.

**Comment by skylaro** [comment]
@xiangyan99 it's being used with a GraphClient from the msgraph.core library:

cli = AzureCliCredential()
client = GraphClient(credential=cli)
result = client.get('/me', headers={'Content-Type': 'application/json'})

**Comment by xiangyan99** [comment]
Thank you.

Could you tell me which library GraphClient comes from?

**Comment by skylaro** [comment]
msgraph-core: https://pypi.org/project/msgraph-core/

**Comment by xiangyan99** [comment]
MS Graph is not an Azure product, so we can't help you on this repo unfortunately. Please open issues in:
https://github.com/microsoftgraph/msgraph-sdk-python-core.

**Comment by pvaneck** [comment]
Can also try passing in the scope via the client as that looks like it is supported:
```
client = GraphClient(credential=AzureCliCredential(), scopes=["https://graph.microsoft.com"])
```

**Comment by skylaro** [comment]
@pvaneck that works! Thanks a ton!
