### ISSUE TITLE
Identity e2e tests for running fail in Azure Arc and Azure Container Instances

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-sdk-for-python#27139]
**Describe the issue:**
1.When test the Testing azure-identity in Azure Arc with [instructions for Test team](https://github.com/Azure/azure-sdk/issues/1908#issuecomment-724376120)(`Repro steps`) and run the `pytest -k managed_identity_live` command, it displays the error :
![image](https://user-images.githubusercontent.com/80496810/198200492-07a2f5a2-254c-42eb-8e1f-fb15a5091ffc.png)

2.When test the Testing azure-identity in Automate Azure Container Instances with [instructions ](https://github.com/Azure/azure-sdk/issues/925#issuecomment-572774347)(`Repro steps`) and run the `az container logs -g $RESOURCE_GROUP -n $CONTAINER_NAME` command, it displays the error :
![image](https://user-images.githubusercontent.com/80496810/198205162-a9fed1e3-3450-467e-ad2f-83ab5906d254.png)

**Environment:**
Env: `Azure Arc` and `Azure Container Instances`
package: https://pypi.org/project/azure-identity/1.12.0b2/
Related issue: https://github.com/Azure/azure-sdk/issues/1908 and https://github.com/Azure/azure-sdk/issues/925

**Expected behavior:**
Run the `pytest -k managed_identity_live` and `az container logs -g $RESOURCE_GROUP -n $CONTAINER_NAME`. expected output for each: `passed` for all tests run.

@josefree for notification.

**Comment by xiangyan99** [comment]
@pvaneck could you help to take a look? (Maybe we need to update the instructions)

**Comment by mccoyp** [comment]
Related issue: https://github.com/Azure/azure-sdk-for-python/issues/26237

**Comment by pvaneck** [comment]
#27182 pushes updated code/instructions that should fix the issues.

**Comment by v-jiaodi** [comment]
@xiangyan99 , @pvaneck It can work with Arc and Container Instances  instructions in https://github.com/Azure/azure-sdk-for-python/pull/27182.
