### ISSUE TITLE
[Web PubSub Service] Feature request for custom domain info

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-sdk-for-python#27145]
**Is your feature request related to a problem? Please describe.**

I want to get `custom doamin` information via sdk but i can't find it.
- https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/webpubsub/azure-mgmt-webpubsub/azure/mgmt/webpubsub/operations

if you look REST API [here](https://learn.microsoft.com/en-us/rest/api/webpubsub/controlplane/web-pub-sub-custom-domains/list?tabs=HTTP) Azure `Web PubSub Service` support getting `cutsom domain` information via REST API.

**Describe the solution you'd like**

So what i want is feature that can get `custom domain` information via sdk.

Or I want to know you have a plan for adding this.

**Describe alternatives you've considered**

**Additional context**

**Comment by swathipil** [comment]
Hi @ImMin5 - Thanks for your feedback! We'll take a look asap!

**Comment by navba-MSFT** [comment]
@ImMin5 Thanks for reaching out to us and reporting this issue. The [1.1.0 version of azure-mgmt-signalr](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/signalr/azure-mgmt-signalr/CHANGELOG.md#110-2022-03-28) package has added added operation group **[SignalRCustomDomainsOperations](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/_signal_rcustom_domains_operations.py#L186)**. 
Did you try to create a client instance of this and check if that helps ? There is [list function](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/_signal_rcustom_domains_operations.py#L209) which should list all custom domains. Hope this helps.

**Comment by ImMin5** [comment]
Additionally, I found an update 
- https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/webpubsub/azure-mgmt-webpubsub/azure/mgmt/webpubsub/operations
- https://pypi.org/project/azure-mgmt-webpubsub/1.1.0b1/

Thanks for your perfect feedback of this issue @swathipil @navba-MSFT @shanselman

**Comment by navba-MSFT** [comment]
> Hi, @navba-MSFT Thanks for your suggestion. Before test `SignalRCustomDomainsOperations`, I keep fail to make `Custom certificate` for Custom domain with this error
> 
> > I deleted some id values
> 
> ```
> Creating custom certificate 'pubsub-certi' failed with status: 'CustomerError' and 
> error: 'Custom certificate not valid: The user, group or application 'appid={};oid={};iss=https://sts.windows.net/{}/' does not have secrets get permission on key vault {my-kevualts-name};location=eastus'. 
> For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287
> Status: 403 (Forbidden)
> ```
> 
> and then I read this [documentation](https://go.microsoft.com/fwlink/?linkid=2125287) which is included in error msg. I follow the guide step by step but sadly i can not figure it out..
> 
> If possible, I need some help about this.

@ImMin5 Thanks for getting back. Could you please follow the suggestions provided in [this thread ](https://learn.microsoft.com/en-us/answers/questions/714847/error-the-user-group-or-application-does-not-have.html)? This should help in addressing the above error.

**Comment by ImMin5** [comment]
Hi @navba-MSFT 
Thanks for your advice. I fix the error :)

**Comment by navba-MSFT** [comment]
@ImMin5 Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
