### ISSUE TITLE
Enable MSI authentication for BlockBlobService

### ISSUE THREAD

**Issue by bob2build** [Azure/azure-sdk-for-python#2714]
Currently the class azure.storage.blob.BlockBlobService only supports storage key or Shared Access Token. 

However, storage itself supports MSI based authentication. Please enable support for using MSI to access storage blobs

**Comment by lmazuel** [comment]
Hi @bob2build 
Storage blob is managed directly by @zezha-msft in this repo:
https://github.com/Azure/azure-storage-python

Please create your issue there, since I unfortunately can't help you here :(
Thanks,
