### ISSUE TITLE
Usage examples Url is not found

### ISSUE THREAD

**Issue by rakeshvanga** [Azure/azure-sdk-for-python#2715]
The readme section has usage example which points to https://azure-sdk-for-python.readthedocs.org/en/latest/sample_azure-keyvault.html which is returning page not found error.

**Comment by lmazuel** [comment]
Thanks for you report @rakeshvanga 
This is fixed in the KV preview branch `keyvault_1.0_preview`, planned for release soon. Please allow me to close this issue then.
Thank you,
