### ISSUE TITLE
Identity e2e tests for running kill in Cloudshell

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-sdk-for-python#27163]
**Describe the issue:**
When test the Testing azure-identity in Cloudshell with [instructions ](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/tests/managed-identity-live/cloudshell.md)(`Repro steps`) and run the `pytest ./tests -vrs -m cloudshell` command, it displays the error :

![image](https://user-images.githubusercontent.com/80496810/198207126-4a0a519e-8935-4050-a7fa-8bea7843b2ab.png)

**Environment:**
Env: Cloudshell terminal
Package: https://pypi.org/project/azure-identity/1.12.0b2/
Related issue:  https://github.com/Azure/azure-sdk/issues/795

**Expected behavior:**
Run the `pytest ./tests -vrs -m cloudshell`. expected output looks like this.
![image](https://user-images.githubusercontent.com/80496810/198207574-7040e73f-b859-4a42-b537-17246691a9f0.png)

@josefree for notification.

**Comment by xiangyan99** [comment]
Could you help to collect some logs?

**Comment by pvaneck** [comment]
Updated cloudshell instructions in https://github.com/Azure/azure-sdk-for-python/pull/27182 which should now work.

**Comment by v-jiaodi** [comment]
@xiangyan99 , @pvaneck  It can work with cloudshell instructions in https://github.com/Azure/azure-sdk-for-python/pull/27182.  In addition, we need to update the code in [test_cloud_shell_async.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/tests/managed-identity-live/test_cloud_shell_async.py#L16).
![image](https://user-images.githubusercontent.com/80496810/198920248-4722ca82-943d-49d3-95ad-2040dcc0e30f.png)

Update `token = credential.get_token("https://vault.azure.net")` to 
`token = await credential.get_token("https://vault.azure.net")`
