### ISSUE TITLE
Identity e2e tests for running fail in Azure VM MSI

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-sdk-for-python#27164]
**Describe the issue:**
Test the Testing azure-identity in Azure VM MSI with [instructions ](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/tests/managed-identity-live/vm.md) (`Repro steps`). When install prerequisites, it displays the error :

![image](https://user-images.githubusercontent.com/80496810/198570586-7690a226-0c6b-480a-8280-624ffc408d9c.png)
 
We try to upgrade Python 3.8, but when install prerequisites, it still displays the same error.

**Environment:**
Env: Azure VM 
Package: https://pypi.org/project/azure-identity/1.12.0b2/
Related issue: https://github.com/Azure/azure-sdk/issues/815

**Expected behavior:**
Install prerequisites can pass.

@josefree for notification.

**Comment by xiangyan99** [comment]
Could you give more details about how you setup the machine and how you upgraded the Python?

e.g. did you use ubuntu 18.04? (its default Python version is 3.6)

**Comment by pvaneck** [comment]
Updated VM instructions with https://github.com/Azure/azure-sdk-for-python/pull/27182 which should now work. Note, that it now has the VMs created using an Ubuntu 20.04 image which now has Python 3.8 installed by default

**Comment by v-jiaodi** [comment]
@xiangyan99 , @pvaneck  According to the VM instructions with https://github.com/Azure/azure-sdk-for-python/pull/27182, **Install prerequisites** is passed , but **Run tests**, I encountered the following errors:

![image](https://user-images.githubusercontent.com/80496810/198926830-208661d5-6441-4b75-904f-e846b2c92dc5.png)

**Comment by v-jiaodi** [comment]
@xiangyan99 , @pvaneck  It can work with VM instructions in https://github.com/Azure/azure-sdk-for-python/pull/27182.

**Comment by joshfree** [comment]
@v-jiaodi can this be resolved/closed now?
