### ISSUE TITLE
[EventHub Mgmt] Deprecated Asyncio.coroutine decorator in test

### ISSUE THREAD

**Issue by kashifkhan** [Azure/azure-sdk-for-python#27175]
In Eventhub Management tests, [this line](https://github.com/Azure/azure-sdk-for-python/blob/87fa4a73fd098116fbeecfe387fafe02b8c0545d/sdk/eventhub/azure-mgmt-eventhub/tests/_aio_testcase.py#L21) is causing the Eventhub CI pipeline to fail in 3.11 at this [point](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1952726&view=logs&j=84b20eb0-323b-5722-f041-399ea9857d18&t=1024ff5b-59a4-5548-1c1b-bbb298ca1664&l=2439) 

The reason is that asyncio.coroutine is now [deprecated](https://docs.python.org/3/whatsnew/3.11.html#removed) in python 3.11

Below can be a simple fix for it :)

```python
def create_mgmt_aio_client(self, client, **kwargs):
        if self.is_live:
            from azure.identity.aio import DefaultAzureCredential
            credential = DefaultAzureCredential()
        else:
            credential = Mock(get_token=lambda _: self.mock_completed_future(AccessToken("fake-token", 0)))
        return client(
            credential=credential,
            subscription_id=self.settings.SUBSCRIPTION_ID
        )
    
    def mock_completed_future(self, result=None):
        future = asyncio.Future()
        future.set_result = result
        return future
  ```

**Comment by msyyc** [comment]
Thanks for your feedback and we will investigate it asap
