### ISSUE TITLE
Logic App Service Filter issue

### ISSUE THREAD

**Issue by jernejknechtl** [Azure/azure-sdk-for-python#27228]
- **Package Name**:    azure-mgmt-logic
- **Package Version**:  10.0.0
- **Operating System**: Windows
- **Python Version**:  3.9.9

**Describe the bug**

When using a filter to retrieve data from Azure I get an error while iterating over the iterator object returned. If re-running the code the error can occur at different stages of the iteration process (e.g. sometimes it fails at the 3rd iteration sometimes at the 29th). Everything works well if no filter is used.

**To Reproduce**

**Example 1 workflow_runs:**

```
response_runs = logic_app_client.workflow_runs.list(workflow_name=workflow, resource_group_name=resource_group, filter = "startTime gt 2022-09-23T15:02:16.078315Z")
for i, run in enumerate(response_runs):
   print(i)  
```

**Error:**

```
HttpResponseError: (InvalidQueryFilter) The provided query filter 'starTime gt 2022-09-23T15:02:16.078315Z' is not valid or not supported. Code: InvalidQueryFilter Message: The provided query filter 'starTime gt 2022-09-23T15:02:16.078315Z' is not valid or not supported.
```
**Example 2 workflow_trigger_histories :**
```
trigger_histories =  logic_app_client.workflow_trigger_histories.list(resource_group_name=resource_group, trigger_name= trigger, workflow_name=workflow, filter="Status eq 'Succeeded'") 

for i, trigger_histroy in enumerate(trigger_histories):
    print(i)
```

**Error:**
```
HttpResponseError: (InvalidQueryFilter) The provided query filter 'Status eq 'Succeeded',Status eq 'Succeeded'' is not valid or not supported.
Code: InvalidQueryFilter
Message: The provided query filter 'Status eq 'Succeeded',Status eq 'Succeeded'' is not valid or not supported.
```

**Expected behavior**
Return filtered data.

**Comment by Wzb123456789** [comment]
Hi @jernejknechtl 

We have released a new version about `azure-mgmt-logic`[here](https://pypi.org/project/azure-mgmt-logic/10.1.0b1/), the new version can solve your problem, please update `azure-mgmt-logic` to the latest version and try again.

**Comment by jernejknechtl** [comment]
Thank you! This seems to solve the problem.
