### ISSUE TITLE
 DefaultAzureCredential - RestError: [TokenExpired] Error validating token: 'S2S12086'

### ISSUE THREAD

**Issue by nathan-copperfrog** [Azure/azure-sdk-for-python#27266]
- Azure Identity: 
- 1.10 and 1.11: 
- Linux:
- 3.8: 

**Describe the bug**
We currently have an azure function app behind and API. This function interacts several third party services, Cosmo, Sales Force to name a through. The functions will run 

`    credential = DefaultAzureCredential(exclude_visual_studio_code_credential = True, exclude_shared_token_cache_credential=True)
    client = SecretClient(vault_url=f"https://{enviroment}apiapp.vault.azure.net/", credential=credential, logging_enable=True)`

After 24 hours we start seeing the error: "FailureException: ClientAuthenticationError: (Unauthorized) [TokenExpired] Error validating token: 'S2S12086'.Code: UnauthorizedMessage: [TokenExpired] Error validating token: 'S2S12086'"

If we restart the function app or wait about 15 minute it starts working again. 

**To Reproduce**
1.  Deploy function app that uses DefaultAzureCredential to access KeyVault. 
2. Run function every minute for 24 hours. 
3. After 24 hours you should start to receive this message. 

**Expected behavior**
I would expect the credential to not expire, or issue a new credential if it expires without a user seeing an error. 

**Additional context**
This was working through April. We did a deploy in May after 1.10 came out and we started having the problem. Did lots of trouble shooting and trying different settings. Eventually found a similar problem on the sdk for js. https://github.com/Azure/azure-sdk-for-js/issues/22722 that got us looking at release dates of version for the Python package that line up.

**Comment by xiangyan99** [comment]
Thanks for reporting the issue.

To help narrow down the cause, do you know which type of credential you used? ManagedIdentityCredential? Service principal?

Thanks.

**Comment by nathan-copperfrog** [comment]
We are using Service Principal.

**Comment by xiangyan99** [comment]
Thanks for the information.

Could you help to collect some logs?

e.g. you can add code like:
import logging
logging.basicConfig(filename='c:/temp/log.log', level=logging.DEBUG)

**Comment by nathan-copperfrog** [comment]
Here are some of the logs leading up to the errors. This is 24 hours after restarting the Function App running the code. 


> 2022-11-01T23:06:35.059 [Information] Response status: 401Response headers:'Cache-Control': 'no-cache''Pragma': 'no-cache''Content-Length': '96''Content-Type': 'application/json; charset=utf-8''Expires': '-1''WWW-Authenticate': 'Bearer authorization="https://login.windows.net/af8bf9d1-b1a5-44d4-9656-158f8e04c92e", resource="https://vault.azure.net"''x-ms-keyvault-region': 'westus''x-ms-client-request-id': 'd4e41130-5a39-11ed-8153-362ecba4621e''x-ms-request-id': '167d5617-f0c5-4c7c-9be8-7093906233f0''x-ms-keyvault-service-version': '1.9.538.1''x-ms-keyvault-network-info': 'conn_type=Ipv4;addr=13.83.90.17;act_addr_fam=InterNetwork;''X-Content-Type-Options': 'REDACTED''Strict-Transport-Security': 'REDACTED''Date': 'Tue, 01 Nov 2022 23:06:34 GMT'
> 2022-11-01T23:06:35.117 [Error] Executed 'Functions.Onboarding-POST-sf-search' (Failed, Id=3e0af86c-ab16-4782-92fc-16c98068a4dc, Duration=123ms)Result: FailureException: ClientAuthenticationError: (Unauthorized) [TokenExpired] Error validating token: 'S2S12086'.Code: UnauthorizedMessage: [TokenExpired] Error validating token: 'S2S12086'.Stack:   File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 406, in _handle__invocation_requestcall_result = await self._loop.run_in_executor(File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in runresult = self.fn(*self.args, **self.kwargs)File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 648, in _run_sync_funcreturn ExtensionManager.get_sync_invocation_wrapper(context,File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapperresult = function(**args)File "/home/site/wwwroot/Onboarding-POST-sf-search/__init__.py", line 73, in mainsfi = sforce.sf_instance()File "/home/site/wwwroot/shared_code/sforce.py", line 168, in sf_instancesalesforce_id(),File "/home/site/wwwroot/shared_code/sforce.py", line 145, in salesforce_idretrieved_secret = client.get_secret('sf-client-id')File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracerreturn func(*args, **kwargs)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_client.py", line 68, in get_secretbundle = self._client.get_secret(File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1574, in get_secretreturn mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracerreturn func(*args, **kwargs)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_generated/v7_3/operations/_key_vault_client_operations.py", line 702, in get_secretmap_error(status_code=response.status_code, response=response, error_map=error_map)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/exceptions.py", line 107, in map_errorraise error
> 2022-11-01T23:06:34.961676395Z MS_FUNCTION_AZURE_MONITOR_EVENT 4,salesena-prod-ver0866.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'salesena-prod-ver0866','roleInstance':'e2cdcf4cca54b758cbbec0e81d6dc1b0ca7d3455d0c9cf8066ba0a4c30a14c22','message':'Executing Functions.Onboarding-POST-sf-search (Reason=This function was programmatically called via the host APIs., Id=3e0af86c-ab16-4782-92fc-16c98068a4dc)','category':'Function.Onboarding-POST-sf-search','hostVersion':'3.17.0.0','functionInvocationId':'3e0af86c-ab16-4782-92fc-16c98068a4dc','functionName':'Functions.Onboarding-POST-sf-search','hostInstanceId':'a850c4b1-6b17-4ed5-a82e-21cc137b97d6','level':'Information','levelId':2,'processId':24,'eventId':1,'eventName':'FunctionStarted'}",11/01/2022 23:06:34
> 2022-11-01T23:06:34.973588158Z MS_FUNCTION_AZURE_MONITOR_EVENT 4,salesena-prod-ver0866.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'salesena-prod-ver0866','roleInstance':'e2cdcf4cca54b758cbbec0e81d6dc1b0ca7d3455d0c9cf8066ba0a4c30a14c22','message':'[+] Current environment: prod','category':'Function.Onboarding-POST-sf-search.User','hostVersion':'3.17.0.0','functionInvocationId':'3e0af86c-ab16-4782-92fc-16c98068a4dc','functionName':'Onboarding-POST-sf-search','hostInstanceId':'a850c4b1-6b17-4ed5-a82e-21cc137b97d6','level':'Information','levelId':2,'processId':24}",11/01/2022 23:06:34
> 2022-11-01T23:06:34.976520998Z MS_FUNCTION_AZURE_MONITOR_EVENT 4,salesena-prod-ver0866.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'salesena-prod-ver0866','roleInstance':'e2cdcf4cca54b758cbbec0e81d6dc1b0ca7d3455d0c9cf8066ba0a4c30a14c22','message':'[+] Current users Roles: [System.Admin]','category':'Function.Onboarding-POST-sf-search.User','hostVersion':'3.17.0.0','functionInvocationId':'3e0af86c-ab16-4782-92fc-16c98068a4dc','functionName':'Onboarding-POST-sf-search','hostInstanceId':'a850c4b1-6b17-4ed5-a82e-21cc137b97d6','level':'Information','levelId':2,'processId':24}",11/01/2022 23:06:34
> 2022-11-01T23:06:34.978922931Z MS_FUNCTION_AZURE_MONITOR_EVENT 4,salesena-prod-ver0866.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'salesena-prod-ver0866','roleInstance':'e2cdcf4cca54b758cbbec0e81d6dc1b0ca7d3455d0c9cf8066ba0a4c30a14c22','message':'Client: False','category':'Function.Onboarding-POST-sf-search.User','hostVersion':'3.17.0.0','functionInvocationId':'3e0af86c-ab16-4782-92fc-16c98068a4dc','functionName':'Onboarding-POST-sf-search','hostInstanceId':'a850c4b1-6b17-4ed5-a82e-21cc137b97d6','level':'Information','levelId':2,'processId':24}",11/01/2022 23:06:34
> 2022-11-01T23:06:34.980784357Z MS_FUNCTION_AZURE_MONITOR_EVENT 4,salesena-prod-ver0866.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'salesena-prod-ver0866','roleInstance':'e2cdcf4cca54b758cbbec0e81d6dc1b0ca7d3455d0c9cf8066ba0a4c30a14c22','message':'Triggered Search...','category':'Function.Onboarding-POST-sf-search.User','hostVersion':'3.17.0.0','functionInvocationId':'3e0af86c-ab16-4782-92fc-16c98068a4dc','functionName':'Onboarding-POST-sf-search','hostInstanceId':'a850c4b1-6b17-4ed5-a82e-21cc137b97d6','level':'Information','levelId':2,'processId':24}",11/01/2022 23:06:34
> 2022-11-01T23:06:34.983376392Z MS_FUNCTION_AZURE_MONITOR_EVENT 4,salesena-prod-ver0866.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'salesena-prod-ver0866','roleInstance':'e2cdcf4cca54b758cbbec0e81d6dc1b0ca7d3455d0c9cf8066ba0a4c30a14c22','message':'DefaultAzureCredential acquired a token from ManagedIdentityCredential','category':'Function.Onboarding-POST-sf-search.User','hostVersion':'3.17.0.0','functionInvocationId':'3e0af86c-ab16-4782-92fc-16c98068a4dc','functionName':'Onboarding-POST-sf-search','hostInstanceId':'a850c4b1-6b17-4ed5-a82e-21cc137b97d6','level':'Information','levelId':2,'processId':24}",11/01/2022 23:06:34

**Comment by xiangyan99** [comment]
@mccoyp Looks like we don't refresh the token in challenging scenario?

Could you help to take a look?

**Comment by nathan-copperfrog** [comment]
Following up to keep the post alive and see if there was any update on looking into the bug.

**Comment by sam-mtm** [comment]
@mccoyp Is there any update you can share on this ticket?

**Comment by mccoyp** [comment]
Hi @nathan-copperfrog and @sam-mtm, sorry about the delay. I was out of the office last week, but I'll look into this and provide an update as soon as possible.

**Comment by mccoyp** [comment]
Just to confirm, @nathan-copperfrog, is your code using `azure-keyvault-secrets` version 4.4.0? That was the first package to use API version 7.3 (which I see in the logs), and was the latest release when `azure-identity` 1.10.0 was released.

I'm still looking into the cause, but based on the output you shared, it looks like you received a 401 response/challenge request at the start of the interaction but no new token request was sent. We usually fetch a new token upon a challenge if we [need a new one](https://github.com/Azure/azure-sdk-for-python/blob/azure-keyvault-secrets_4.4.0/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L73), as indicated by the token's expiry time.

This makes me wonder if `azure-identity` is unable to correctly parse the expiration time of the tokens we're receiving, as was the case in the JS issue you linked -- though that specific issue should have already been fixed a while back in Python as well...

**Comment by nathan-copperfrog** [comment]
@mccoyp  Thank you for getting back. 

We currently don't have the azure-keyvault-secrets version locked so the most recent deploy is using 4.6.0.

Some added information, as an experiment last week we locked azure identity to version 1.9.0 and since then we have not had the authentication problem. Its only been three days since we stopped restarting the Azure function automatically every 12 hours, but we would normally see the problem at the 24 hour mark.

**Comment by xiangyan99** [comment]
@nathan-copperfrog As mccoyp pointed out, the difference between identity 1.9.0 and 1.10.0 is the msal-extension version.

Could you help to share the msal-extension version when you use identity 1.9.0 vs latest one?

Another experiment could be keep using the latest identity but downgrade msal-extension to 0.3.0 and see if the issue goes away.

Thanks.

**Comment by rayluo** [comment]
> The only difference between `azure-identity` 1.10.0 and 1.9.0, though, is that the required version of `msal-extensions` was changed from `~=0.3.0` to `<2.0.0,>=0.3.0`. `msal-extensions` is used for token caching behavior, so that might actually be causing the behavior change.

Although [`msal-extensions` received some changes between its 0.3.0 and 1.0.0](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/compare/0.3.0...1.0.0), they are mostly on the underlying file locking mechanism, whose potential failure would typically fail noisy as some sort of "unable to encrypt/descript" or "unable to read/write file" exceptions.

The symptom in this issue sounds like the app runs seemingly smoothly, and an expired token was somehow kept and reused, that doesn't sound like an `msal-extensions` issue. That being said, it does not harm to "try using a more recent version of azure-identity but keep msal-extensions at version 0.3.0" and see how that goes.

Also, when the issue occurs, see if you can get the expired token, and decode it via https://jwt.ms which will let us know whether the token is indeed expired (it probably is), and then we will need to investigate how it was served.

**Comment by KEMBL** [comment]
> After 24 hours you should start to receive this message.

I had the same problem, fix was not to cache `client = new SecretClient(...` (at least do not cache it forever, refresh once a hour or so). I started re-creating of `new ManagedIdentityCredential()` and make a new `SecretClient` from it and problem has gone for now.

Cant say it for sure, but it seems like one of the objects above makes a token which gets stale after some time.

I believe the similar problem is in issue #27266

I use @azure/identity 3.1.1
Package Name: @azure/identity
Package Version: ^3.1.1
Operating system: Linux
Nodejs version: 16.14.12

**Comment by KarishmaGhiya** [comment]
@KEMBL Were you using JS @azure/identity. Can you try using 3.1.2 version for JS @azure/identity and let me know if you still face the issues you mentioned?
