### ISSUE TITLE
Enquiry on query logs for Application Insights 

### ISSUE THREAD

**Issue by bendanye** [Azure/azure-sdk-for-python#27295]
Is there a way to use azure SDK to run custom query on application insights?

I am been able to use LogsQueryClient in azure-monitor-query to run query on log analytics but having no luck using the same for application insights because LogsQueryClient requires a workspace_id which Application Insights does not have any workspace_id.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by pvaneck** [comment]
Hey, @bendanye. I am assuming you are probably trying to query a [classic Application Insights](https://learn.microsoft.com/azure/azure-monitor/app/create-new-resource) resource which has been deprecated. It's strongly recommended that you [migrate to a workspace-based](https://learn.microsoft.com/azure/azure-monitor/app/convert-classic-resource) App Insights resource.

For querying classic resources, we did have [`azure-applicationinsights`](https://pypi.org/project/azure-applicationinsights/), but this is no longer maintained, so the suggestion for migrating to a workspace-based resource is the best way forward. Some info on sdk usage differences can be found in [this python app insights migration guide](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-query/migration_guide_app_insights.md).
