### ISSUE TITLE
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)

### ISSUE THREAD

**Issue by pankajkumar002** [Azure/azure-sdk-for-python#27303]
Hi,

I am trying to authenticate to a secure Azure ML workspace using an SPN. And the module is failing for a few team members while it is working for some of them.

**Error Message -** 
**Traceback (most recent call last):
  File "C:\Users\user_name\Anaconda3\envs\env_name\lib\site-packages\utils\auth\azkvsecret.py", line 46, in get_az_kv_secret
    secret_value = client.get_secret(name)**
  File "C:\Users\user_name\Anaconda3\envs\env_name\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\user_name\Anaconda3\envs\env_name\lib\site-packages\azure\keyvault\secrets\_client.py",
line 77, in get_secret
    **kwargs
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\keyvault\secrets\_generated\_operations_mixin.py", line 1574, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\tracing\decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\keyvault\secrets\_generated\v7_3\operations\_key_vault_client_operations.py", line 697, in get_secret
    **kwargs
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\_base.py", line
211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\_base.py", line
71, in send
    response = self.next.send(request)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\_base.py", line
71, in send
    response = self.next.send(request)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\_base.py", line
71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 467, in send
    raise err
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 445, in send
    response = self.next.send(request)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 119, in send
    response = self.next.send(request)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\_base.py", line
71, in send
    response = self.next.send(request)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\_base.py", line
71, in send
    response = self.next.send(request)
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\_base.py", line
71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\_base.py", line
103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "C:\Users\username\Anaconda3\envs\env_name\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 361, in send
    **raise error
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)**

**## get_az_kv_secret function defined in utils**
from azure.keyvault.secrets import SecretClient
from azure.identity import DefaultAzureCredential
from azure.identity import ClientSecretCredential

def get_az_kv_secret(
    az_kv_name: str='kvname', 
    secret_name: list=['keyname']
    ) -> dict:

    tenant_id = "TENANT_ID"
    client_id = "CLIENT_ID"
    client_secret = "CLIENT SECRET"
    	
    secret_dict = {}
    kv_uri = f"https://{az_kv_name}.vault.azure.net"
    credential = ClientSecretCredential(tenant_id=tenant_id, client_id=client_id, client_secret=client_secret)
    client = SecretClient(vault_url=kv_uri, credential=credential)

    for name in secret_name:
        **secret_value = client.get_secret(name)** ##Failing at this step
        secret_dict[name] = secret_value.value  # type: ignore

    return secret_dict  # type: ignore

**While this is working fine for a few team members, it is failing for some of them when they run it from their local conda environments.**

**Below are the environment details**
 - python==3.7.13
 - azure-identity==1.7.0
 - azure-keyvault-secrets==4.6.0
 - azure-core==1.22.1
 - azureml-core==1.42.0.post1

Some of the packages are installed as dependencies for azure sdk.
**Following the spn authentication mechanism from here for AML workspaces -** [Authentication in AzureML](https://github.com/Azure/MachineLearningNotebooks/blob/1f05157d24c8bd9866121b588e75dc95764ae898/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by pankajkumar002** [comment]
Hi @xiangyan99 @mccoyp any updates on this?

**Comment by mccoyp** [comment]
Hi @pankajkumar002, sorry about the delayed response. I was out of office last week, but I'll look into this and provide an update as soon as possible.

**Comment by mccoyp** [comment]
Hi again @pankajkumar002 -- after looking into this more, I'm pretty confident that this isn't particular to Key Vault. My guess would be that requests to different endpoints might fail with the same error, but correct me if I'm wrong.

I wouldn't expect that the Key Vault service is providing an invalid, self-signed certificate, so I think this should be a local configuration issue. Online searches suggest that installing the [pip-system-certs](https://pypi.org/project/pip-system-certs/) ([conda-forge link](https://anaconda.org/conda-forge/pip-system-certs)) package (which replaces `python-certifi-win32`) may fix this problem.

Synchronous KV requests use `requests` under the hood, so the sections discussing certificates (starting [here](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification)) in their docs may also shed some light on what may be the issue.

Let me know if installing `pip-system-certs` in problematic environments helps! You mentioned conda, so you may need to use
```
conda install -c conda-forge pip-system-certs
```

**Comment by jdickson-li** [comment]
Hello, I am experiencing the same error. Has it been confirmed installing pip-systems-certs resolves the issue.

If not how could it set SSL verify to false through the Azure Python SDK?

**Comment by mccoyp** [comment]
Hi @jdickson-li, I'm unfortunately not sure if `pip-system-certs` solves the issue since we haven't heard back on the original issue. I encourage you to give it a try and let us know if it helps, though!

As for disabling SSL certificate verification, that can be done by providing a custom transport to a client. The client library developer guide in `azure-core` describes how to do this: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#transport

By default, Key Vault clients currently use a `RequestsTransport` from `azure.core.pipeline.transport`. This transport accepts a `connection_verify` keyword argument, as described in the guide above, which is True by default but can be set to False. This will disable SSL certificate verification, but you should only disable this if you're sure about the security of your connection. You could use this with a `SecretClient` like so:
```python
from azure.core.pipeline.transport import RequestsTransport
from azure.keyvault.secrets import SecretClient

transport = RequestsTransport(connection_verify=False)
client = SecretClient(<vault_url>, <credential>, transport=transport)
```

**Comment by jdickson-li** [comment]
Hey, @mccoyp Thank you for your response. The pip-system-certs library did not work for me so I ended up using the request library and calling the REST API directly, which worked.

Thanks for sharing the doc details that will be useful to know for the future.

**Comment by shulkx** [comment]
It seems that the error occurs due to the unstable of the connection.
I introduced the mechanism of retrying inside the `prepdocs.py` and works fine for now. When the certificate verify failed, it will pass in the second trial.
Here is what I have modified. args.start_index is set once the progress is shut down, I can continue the progress from specific index.
```python
def process_file(filename):
    if args.verbose: print(f"Processing '{filename}'")
    if args.remove:
        remove_blobs(filename)
        remove_from_index(filename)
    elif args.removeall:
        remove_blobs(None)
        remove_from_index(None)
    else:
        if not args.skipblobs:
            upload_blobs(filename)
        print(f"Processing '{filename}'")
        page_map = get_document_text(filename)
        sections = create_sections(os.path.basename(filename), page_map)
        index_sections(os.path.basename(filename), sections)

if args.removeall:
    remove_blobs(None)
    remove_from_index(None)
else:
    if not args.remove:
        create_search_index()
    
    print(f"Processing files...")
    # Recursively find all files in the directory
    filenames = glob.glob(args.files, recursive=True)

    # Filter out directories
    filenames = [f for f in filenames if os.path.isfile(f)]

    # Maximum number of retry attempts
    max_retry_attempts = 3
    args.start_index = 0

    start_index = args.start_index if hasattr(args, 'start_index') and args.start_index < len(filenames) else 0

    for i in tqdm.tqdm(range(start_index, len(filenames)), desc="Processing files", unit="file"):
        filename = filenames[i]
        if os.path.isfile(filename):
            retry_attempts = 0
            while retry_attempts < max_retry_attempts:
                try:
                    process_file(filename)
                    break  # Break the while loop if processing was successful
                except Exception as e:
                    print(f"Error processing file {filename}. Error: {str(e)}. Attempt {retry_attempts+1} of {max_retry_attempts}")
                    retry_attempts += 1
```
