### ISSUE TITLE
[Azure ML SDK v2] Issue while reading data from `uri_folder` Input type via https://<account_name> scheme

### ISSUE THREAD

**Issue by glebrh** [Azure/azure-sdk-for-python#27318]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.0.0
- **Operating System**: Windows Server 2022 Standard
- **Python Version**: 3.9.13

**Describe the bug**
According to the documentation it should be possible to access public blob storage containers using `Input(type='uri_folder')` instance. While passing actual path of the data, [azure docs](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-read-write-data-v2?tabs=cli#supported-paths) say that it is possible to use either
`https://<account_name>.blob.core.windows.net/<container_name>/<path>`
or
`abfss://<file_system>@<account_name>.dfs.core.windows.net/<path>`
path format

I tried to use the first option (https://) with [diabetes dataset](https://learn.microsoft.com/en-us/azure/open-datasets/dataset-diabetes?tabs=azureml-opendatasets), which is available under the following link: `https://azureopendatastorage.blob.core.windows.net/mlsamples/diabetes`. However, this access method causes error like below:

```
{"NonCompliant":"DataAccessError(NotFound)"}
{
  "code": "data-capability.UriMountSession.PyFuseError",
  "target": "",
  "category": "UserError",
  "error_details": [
    {
      "key": "NonCompliantReason",
      "value": "DataAccessError(NotFound)"
    },
    {
      "key": "StackTrace",
      "value": "  File \"/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/data_capability/capability_session.py\", line 70, in start\n    (data_path, sub_data_path) = session.start()\n\n  File \"/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/data_capability/data_sessions.py\", line 364, in start\n    options=mnt_options\n\n  File \"/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/azureml/dataprep/fuse/dprepfuse.py\", line 696, in rslex_uri_volume_mount\n    raise e\n\n  File \"/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/azureml/dataprep/fuse/dprepfuse.py\", line 690, in rslex_uri_volume_mount\n    mount_context = RslexDirectURIMountContext(mount_point, uri, options)\n"
    }
  ]
}


AzureMLCompute job failed.
data-capability.UriMountSession.PyFuseError: [REDACTED]
  Reason: [REDACTED]
  StackTrace:   File "/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/data_capability/capability_session.py", line 70, in start
    (data
```

With the second option, i.e. `wasbs://mlsamples@azureopendatastorage.blob.core.windows.net/diabetes` job finishes successfully

**To Reproduce**
Execute the following code:

```python
ml_client = MLClient(...)

job = command(
    command="ls ${{inputs.diabetes}}",
    inputs={
        "diabetes": Input(
            type="uri_folder",
            path="https://azureopendatastorage.blob.core.windows.net/mlsamples/diabetes",
        )
    },
    environment="AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest",
    compute="cpu-cluster",
    display_name="data_access_test",
    # description,
    experiment_name="data_access_test"
)

ml_client.create_or_update(job)
```

**Expected behavior**
Job will complete successfully. User logs will show the list of files inside passed blob storage folder

**Comment by glebrh** [comment]
BTW with `uri_file` option works normally with paths like this: `https://azuremlexamples.blob.core.windows.net/datasets/iris.csv`

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by AndrewRTsao** [comment]
+1 I am facing this issue as well. I had to switch to using `URI_FILE` instead of `URI_FOLDER` as the initial input in my pipeline code as a workaround.

**Comment by luigiw** [comment]
Thx for reporting this. We'll investigate and get back to you.

**Comment by QianqianNie** [comment]
Hi, for uri_folder, please use wasbs schemed uri if its blob storage(wasbs://<containername>@<accountname>.blob.core.windows.net/<path_to_data>/)

or abfs(abfss://<filesystem>@<accountname>.dfs.core.windows.net/<path_to_data>/) if its adlsgen2 storage

**Comment by glebrh** [comment]
Then the documentation should be updated wherever it is mentioned that access to `uri_folder` is possible via https protocol, it should be removed?
For isntance [here](https://learn.microsoft.com/en-us/azure/machine-learning/concept-data?tabs=uri-file-example%2Ccli-data-create-example#uris) or [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-read-write-data-v2?tabs=cli)

Or eventually, support for https + `uri_folder` will be added?

**Comment by luigiw** [comment]
I think this will be a document improvement.

**Comment by ylnhari** [comment]
I am still facing this issue while submitting an Azure ML Job, using URI Folder with azure blob container storage as Input to the Job -> https://<account_name>.blob.core.windows.net/<container_name>/<path> 
![image](https://user-images.githubusercontent.com/45874226/228423025-cd80b9d6-1e52-43e4-b07f-92dca3437d51.png)

if I created an Azure ML Data Asset or Azure ML Datastore for the same Azure blob container storage path, the job is starting without any problems.

**Comment by madhuyadu** [comment]
Hi all,
I am facing issue when trying to read csv file stored on my github repository into azure ml. It throws following error: 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/56335301/233368976-842afd1f-1b44-4f7d-b4c2-25dcc36c5167.png">

**Comment by RyanTahnikoyev** [comment]
I found this problem interesting. It seems that you have to register the datastore with the subscription and resource group where the data is located. There should be a streamlined solution for this. 
![image](https://github.com/Azure/azure-sdk-for-python/assets/25973761/0add8e81-6843-41c0-9397-3d140d682fe0)
