### ISSUE TITLE
FormRecognizer behavior when service starts throttling

### ISSUE THREAD

**Issue by dev-td** [Azure/azure-sdk-for-python#27317]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.2.0
- **Operating System**: Windows / Linux
- **Python Version**:  3.8 / 3.9

**Describe the bug**
When service form recognizer starts to throttle it raises error I/O Operation on closed file.

**To Reproduce**
Please check code snippet below.
` 

    async def analyse_document_async(document: io.BytesIO):
          endpoint, key = ...
      
          # instantiate client
          document_analysis_client = DocumentAnalysisClient(
              endpoint=endpoint, credential=AzureKeyCredential(key)
          )
      
          # generate analysis_args
          analysis_args = {"model_id": "prebuilt-invoice", "document": document}
      
          # non blocking async call
          async with document_analysis_client:
              # Suppose to raise HttpError 429 when service starts to throttle (during scale-out)
              # Instead raise I/O Operation on closed file...
              poller = await document_analysis_client.begin_analyze_document(**analysis_args)
              result = await poller.result()
      
      
          return result

    async def orchestrate_async_function(documents: List[io.BytesIO]):
      
          tasks = [asyncio.create_task(analyse_document_async(doc)) for doc in documents]
          # concurrent call
          finished, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_EXCEPTION)
      
          return finished
`

**Expected behavior**
Should raise HttpError 429

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by catalinaperalta** [comment]
Thanks for reaching out @dev-td! If possible, could you please share the error message you're getting?

@vkurpad could you loop someone in from the service team to take a look?

**Comment by dev-td** [comment]
Hi @catalinaperalta , sure it's
ValueError: I/O operation on closed file
I can try to provide the error stack of that helps.

**Comment by kristapratico** [comment]
@catalinaperalta possibly related: https://github.com/Azure/azure-sdk-for-python/issues/20040

**Comment by catalinaperalta** [comment]
Ah I see, thanks for the info @dev-td and @kristapratico. Let me take a look

**Comment by catalinaperalta** [comment]
Hi @dev-td, I wanted to follow up and let you know that we're still looking into a fix for this issue. In the meantime, if possible, could you share the error stack please?
