### ISSUE TITLE
Q: DefaultAzureCredential with Key vault needs additionally_allowed_tenants? 

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk-for-python#27349]
If I'm connecting to Azure Storage, I can use a DefaultAzureCredential() but that doesn't work with Key vault, in which I can only get a secret if I configure the DefaultAzureCredential with tenants.

```
azure_credential = DefaultAzureCredential(additionally_allowed_tenants=['*'])
```

How should I know I need tenants when I'm reading the reference docs or quickstarts? I don't see it in the [quickstart](https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python?tabs=azure-cli#create-the-sample-code) but I need it when getting a secret from an Azure HTTP trigger function while running on my local computer. 

@scottaddie fyi

**Comment by xiangyan99** [comment]
I believe https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python?tabs=azure-powershell%2Cazure-cli#create-the-sample-code is out of date. In our latest code (which will be released this week and it will be a GA release), users don't need to specify additionally_allowed_tenants argument in DAC if they use cli credential which is used in the quickstart.

**Comment by diberry** [comment]
@xiangyan99 When do users need to specify additionally_allowed_tenants? Can you provide a link to documentation?

**Comment by xiangyan99** [comment]
We have the doc to describe the scenario in https://aka.ms/azsdk/blog/multi-tenant-guidance.
