### ISSUE TITLE
Readonly attribute will be ignored in class <class 'azure.mgmt.appconfiguration.v2022_05_01.models._models_py3.KeyValue'>

### ISSUE THREAD

**Issue by b0scode** [Azure/azure-sdk-for-python#27357]
Hi Sir,

We've used this SDK to create key-value with a specific label for App Configuration,
but encounter the error:
Readonly attribute label will be ignored in class <class 'azure.mgmt.appconfiguration.v2022_05_01.models._models_py3.KeyValue'>

Would you please help?
Thank you!

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Wzb123456789** [comment]
Hi @b0scode 

Could you provide me with your run code block? And the version of azure-mgmt-app configuration you are using, and the result you expect to better solve your problem.
