### ISSUE TITLE
[Pipelines] Windows test runs "ValueError: underlying buffer has been detached"

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#27402]
(as @kristapratico pointed out) On Windows, for python tests pipelines, when installing dependencies at the start of "Run Tests" you get a logging statement with the error "ValueError: underlying buffer has been detached"

Examples:

[ServiceBus](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1976652&view=logs&j=d4f72375-ff6a-522a-0e39-e9ab7520415c&t=3a088c44-811c-504b-9620-1239eb5d0d8b)
[TextAnalytics](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1971381&view=logs&j=53173ce0-af52-5d9c-4521-116e992c2b8d&t=68c6dd30-f3d3-5669-b6ec-3eb8ae1ab3e3 )

**Comment by benbp** [comment]
@l0lawrence So this does work if you pin on `3.7.9` ([pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1977852&view=results)) but not for `3.9` ([pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1977843&view=results)). I think the issue we may be seeing here was with vulnerabilities and the patch versions need to be pinned or set to `>=` for tests.

FYI @scbedd

**Comment by kristapratico** [comment]
@scbedd opened an issue on pypa/build and the maintainers think this is coming from setuptools: https://github.com/pypa/build/issues/540

**Comment by scbedd** [comment]
We haven't seen this issue recently.

[DataSource](https://dataexplorer.azure.com/clusters/azsdkengsys.westus2/databases/Pipelines)
```kusto
BuildLogLine
| where Timestamp > ago(60d)
| where Message has "ValueError: underlying buffer has been detached"
| count 
```
