### ISSUE TITLE
Q: strip hyphens from Key Vault resource name? 

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk-for-python#27425]
I ran into a situation with @pamelafox where the Key vault resource name was created with hyphens but the Azure portal removed the hypens for the endpoint URL. When constructing the URL for the SDK, instead of using the resource name, the hyphens had to be stripped out in order to successfully connect to the key vault. 

Is this a known/doc'd issue somewhere? When should customers use hyphens in resource names which will be used with Python SDKs? 

[Code](https://github.com/Azure-Samples/msdocs-python-etl-serverless/blob/main/shared/key_vault_secret.py) for reference is copied below:

```
import logging

from azure.keyvault.secrets import SecretClient


def get_key_vault_secret(azure_credential, key_vault_name, secret_name):

    # TODO: Does this need to have hyphens stripped?
    key_vault_uri = f"https://{key_vault_name}.vault.azure.net"
    logging.info("key_vault_uri=%s", key_vault_uri)

    client = SecretClient(vault_url=key_vault_uri, credential=azure_credential)
    logging.info("created client")

    key_vault_secret_response = client.get_secret(secret_name)
    logging.info("got secret")
    logging.info("secret= %s, value= %s", secret_name, key_vault_secret_response.value)

    return key_vault_secret_response.value
```

**Comment by mccoyp** [comment]
Hi @diberry, thank you for opening an issue! This isn't something I've seen before, and may be a regression. I personally use a Key Vault with a hyphen in its name and haven't had issues with it, but the vault was created a while back. I'll tag someone from the service team who can take a look.

cc @jlichwa

**Comment by mccoyp** [comment]
Pinging folks from the service team again who may be able to assist: @nkondamudi, @jackrichins, @jlichwa

**Comment by jlichwa** [comment]
@diberry it is likely issue on service side with this particular vault. We have no restrictions on using hyphens with vault name as documented here https://learn.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates#vault-name-and-object-name.
I recommend to create IcM for assistance.

**Comment by pamelafox** [comment]
I was with Dina when we ran into that issue- I'm still not sure why we saw the key vault URI with removed hyphens entirely, since I have successfully deployed key vaults with hyphenated names and hyphenated URIs since then.

However, the documentation does seem to leave out the fact that there can't be consecutive hyphens. I just got this error on a deployment where my auto-generated name had two hyphens:

```
VaultNameNotValid: The vault name 'simple-flask-api--vault' is invalid. A vault's name must be between 3-24 alphanumeric characters. The name must begin with a letter, end with a letter or digit, and not contain consecutive hyphens. Follow this link for more information: https://go.microsoft.com/fwlink/?linkid=2147742
```

**Comment by mccoyp** [comment]
@pamelafox, thank you for the information. @jlichwa, it does look like the [documentation you linked](https://learn.microsoft.com/azure/key-vault/general/about-keys-secrets-certificates#vault-name-and-object-name) should probably be updated to mention the consecutive hyphen restriction.

**Comment by jlichwa** [comment]
We will update the documentation.
