### ISSUE TITLE
Azure Service Bus Error while publish_message:: Handler failed: Authorization timeout.

### ISSUE THREAD

**Issue by shbanua** [Azure/azure-sdk-for-python#27472]
Packages: azure-servicebus==7.8.1 azure-identity==1.12.0
Operating System: Windows 10
Python Version: 3.7.9

**Environment Setup**
Running the service bus in Private VNET with the private end point configured and trying to access it from local machine with VPN.

**Describe the bug**
Not able to publish the message using connection_string (shared access policies) to the service bus, but able to do all the management level activities (creation of topic, creation of subscription)

**Observed error message:**
Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down.
TimeoutError: Authorization timeout.
Error while publish_message:: Handler failed: Authorization timeout..

**ServiceBus Explorer**
Tried connecting to Service Bus via Service Bus explorer using connection_string, able to list the topic, subscriptions created and able to publish the message to topic and receive the message the message from subscription through service bus explorer successfully, facing the issue while publishing the message through Python SDK (attached the screenshot of error).

**Reproducible Example:**
**Service Bus client**
```
 def get_servicebus_client(self):
        servicebus_client = ServiceBusClient.from_connection_string(conn_str=os.environ.get(SERVICEBUS_CONNECTION_STRING),
                                                         logging_enable=True)
        return servicebus_client
```
**Publish Message to Topic**
```
 async def publish_message(self, arg):
        '''publish data to topic'''
        topic_name = arg.topic_id
        try:
            topic_client = servicebus_client.get_topic_sender(topic_name)
            topic_data = json.dumps(json.loads(arg.topic_data))
            topic_client.send_messages(ServiceBusMessage(topic_data))
            response_wrapper = ResponseWrapper(
                CloudCommonKwargs(success=True, function_identifier='publish_message', type=str,
                                  value=str(topic_name)))
        except Exception as error:
            self.logger.error(
                'Error while publish_message:: %s', str(error))
            response_wrapper = ResponseWrapper(
                CloudCommonKwargs(success=False, failure=True, function_identifier='publish_message', code=500,
                                  message=str(error.args[0])))
        return response_wrapper.__dict__
```

**Service Bus Explorer Screenshot**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/108254020/201672466-cad33e17-569d-450c-83fe-f41422543686.png)

Error Message Screenshot
<img width="1400" alt="Screenshot 2022-11-14 at 7 01 06 PM" src="https://user-images.githubusercontent.com/108254020/201672766-c4ce626e-d0bc-47e0-bfbd-63eb6abfbb0e.png">

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment]
Hi @shbanua ,

I have some follow up questions:

* Is service bus explorer running on the same local machine as the python SDK ?
* Is the local machine part of the VNET ? are you able to run `nsloopup <eventhubs-namespace>.servicebus.windows.net` and get it resolved?
* Are you able to use websocket transport by passing in `transport_type=TransportType.AmqpOverWebsocket` in to from_connection_string ?

**Comment by shbanua** [comment]
Hi @kashifkhan 

Thank you for your inputs.

The 3rd step mentioned by you worked perfectly by passing the transport_type=TransportType.AmqpOverWebsocket in to from_connection_string, and able to publish the message to the service bus.
