### ISSUE TITLE
Use "CredentialData"  (AADHash) with azure-sdk-for-python

### ISSUE THREAD

**Issue by sfonteneau** [Azure/azure-sdk-for-python#27470]
Hello

I came across a powershell script that seems to do exactly what I want

https://github.com/Gerenios/AADInternals/blob/master/AzureADConnectAPI.ps1#L1190
https://github.com/Gerenios/AADInternals/blob/master/AzureADConnectAPI_utils.ps1#L296

I want to send azure ad the derivative of an md4 hash

In my case I do not have the password in clear

I can't find anything in "azure-sdk-for-python" that refers to CredentialData

Is this supported by azure-sdk-for-python?

I made this request in 2018: https://github.com/Azure/azure-sdk-for-python/issues/4018

Simon

**Comment by xiangyan99** [comment]
Thank you for the feedback. We will discuss the request with our architects.

**Comment by xiangyan99** [comment]
This is the doc for `InteractiveBrowserCredential`: https://learn.microsoft.com/en-us/dotnet/api/azure.identity.interactivebrowsercredential?view=azure-dotnet

**Comment by sfonteneau** [comment]
🧐 this does not solve my problem ...

"Credentialdata" used by "azure AD connect" why not use it? 

Will it be replaced by another equivalent method?

**Comment by xiangyan99** [comment]
Agreed that it does not 100% cover your scenario.

But unfortunately, this scenario is being deprecated and I am afraid there is no equivalent method to replace it.
