### ISSUE TITLE
Azure EventHub Error : azure.eventhub.exceptions.AuthenticationError: Unable to open authentication session on connection 

### ISSUE THREAD

**Issue by anup1227** [Azure/azure-sdk-for-python#27473]
**Packages**: azure-eventhub = "5.10.1" azure-identity==1.12.0
Operating System: Windows 10
Python Version: 3.7.9

**Environment Setup**
Running the event hub in Private VNET with the private end point configured and trying to access it from local machine with VPN.

**Describe the bug**
Not able to publish the message using connection_string (shared access policies) to the event hub in private network via code, but with service bus explorer able to publish the message using same connection string.

Also same code is working when eventhub is made public.

**Observed error message:**
azure.eventhub.exceptions.AuthenticationError: Unable to open authentication session on connection b'EHProducer-50b52b41-13c5-4e79-92aa-f3f4511fbc48'.
Please confirm target hostname exists: b'eus-d-cc-dev-eh.servicebus.windows.net'
Unable to open authentication session on connection b'EHProducer-50b52b41-13c5-4e79-92aa-f3f4511fbc48'.
Please confirm target hostname exists: b'eus-d-cc-dev-eh.servicebus.windows.net'

**ServiceBus Explorer**
Tried connecting to EventHub via Service Bus explorer using connection_string, able to list the eventhubs, consumer groups created and able to publish the message to eventhub and listen the message from consumer group through service bus explorer successfully, facing the issue while publishing the message through Python SDK (attached the screenshot of error).

**Reproducible Example:**
**EventHubProducer  client**
**Publish Message to Topic**
```
async def publish_message(self, arg):
        '''publish data to topic'''
        self.logger.info('Entering AZURE_EVENTHUB :: publish_topic')
        stream_name = arg.topic_id
        stream_data = arg.topic_data
        self.logger.info('topic id :: {} topic data :: {}'.format(stream_name, str(topic_data)))
        connection_str = os.environ.get(constants.AZURE_EVENTHUB_CONN_STR)
        producer = EventHubProducerClient.from_connection_string(connection_str, eventhub_name = stream_name)
        
        with producer:
            event_data_batch =  producer.create_batch()
            data = json.dumps(stream_data).encode(constants.UTF_8)
            event_data = EventData(data)

            try:
                event_data_batch.add(event_data)
                producer.send_batch(event_data_batch)

                self.logger.info('Exiting AZURE_EVENTHUB :: publish_message')
                response_wrapper = ResponseWrapper(CloudCommonKwargs(success=True, function_identifier='publish_message', type=str, value=str(stream_name)))
            except Exception as error:
                self.logger.error(
                    'Error while publish_message:: %s', str(error))
                response_wrapper = ResponseWrapper(CloudCommonKwargs(success=False, failure=True, function_identifier='publish_message', code=500, message=str(error.args[0])))
          
        return response_wrapper.__dict__
```

**Service Bus Explorer Screenshot**
<img width="949" alt="EHExplorerCapture" src="https://user-images.githubusercontent.com/95021856/201679691-f05f82fb-ae92-4086-98f3-b466238d043c.PNG">

Error Message Screenshot
<img width="949" alt="err1Capture" src="https://user-images.githubusercontent.com/95021856/201681001-1ec677ea-67b7-4b0d-9d71-28f65e873d58.PNG">
<img width="947" alt="err2Capture" src="https://user-images.githubusercontent.com/95021856/201681020-54aee7c5-0684-4ff2-8eb4-4e9054c6be77.PNG">

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment]
Hi @anup1227 , 

I have some follow up questions for you:
* Is service bus explorer running on the same local machine as the python SDK ?
* Is the local machine part of the VNET ? are you able to run `nsloopup <eventhubs-namespace>.servicebus.windows.net` and get it resolved?
* Are you able to use websocket transport by passing in `transport_type=TransportType.AmqpOverWebsocket` in to `from_connection_string` ?

**Comment by anup1227** [comment]
Hi @kashifkhan when passing in transport_type=TransportType.AmqpOverWebsocket to the producer client then able to publish the message with no such previous error, but is any any other way it can be fixed without using transport_type as an extra parameter?

**Comment by kashifkhan** [comment]
@anup1227 since websockets are working this means that port 443 is allowed on the firewall ( which is https traffic and also used for amqp over websockets ). My guess will be that the firewall on the vnet needs to allow the AMQP ports 5671 and 5672, this way you wont need to pass in a transport_type in to your connection string

[here](https://learn.microsoft.com/en-us/azure/event-hubs/troubleshooting-guide) is the connection troubleshooting guide that can assist with you with configuration.

**Comment by anup1227** [comment]
Thank you @kashifkhan for the resolution will look into our vnet if required for now closing the issue.
