### ISSUE TITLE
Blob service not working in version 0.9.0

### ISSUE THREAD

**Issue by MortI2C** [Azure/azure-sdk-for-python#275]
Hi,
I've been trying to upload a blob to my azure storage account with your SDK. First I cloned the latest changes on master (version 0.9.0), but when I tried to import azure.storage.blobservice it didn't work at all (python fails to locate the module).
After searching a bit for what could be happening I downgraded to v0.8.4 and it works as a charm.

I didn't have time to find what is the issue with your latest version, but I guess more people will have problems with this so I post it here so you are aware of it.

Anyway thanks for your job, since it helped me quickly uploading some data to my storage account without having to use any windows tools.

**Comment by huguesv** [comment]
0.9 introduced a dependency on an external package: python-dateutil

That should get installed automatically when you `pip install azure`.  But if you install manually from the sources, you probably just need to `pip install python-dateutil`, as I don't think the dependent packages get installed automatically in that case.

**Comment by MortI2C** [comment]
Ok thanks you huguesv, I installed first from sources and then with pip command, but probably it had messed up.
Now it is working fine.
