### ISSUE TITLE
Scale set virtual machine instance creation time

### ISSUE THREAD

**Issue by DoronGaznavi** [Azure/azure-sdk-for-python#27504]
- **Package Name**: azure.mgmt.compute
- **Package Version**: 29.0.0
- **Operating System**:Ubuntu 20.04
- **Python Version**: 3.8

**Describe the bug**
From api version 22-11-01 and up, the field timeCreated is available in the resource json of a scale set virtual machine instance.
But using the ComputeManagementClient is not resulting the new resource json format.
[ComputeManagementClient default api version is 22-08-01 which support the time created field](https://github.com/Azure/azure-sdk-for-python/blob/23016825ca59c8e83a26f0988e4de39f86064984/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2022_08_01/_compute_management_client.py#L136)

**To Reproduce**
1. Create a scale set
2. Initiate instances in the new scale set
3. Fill in and run the code below 

`from azure.mgmt.compute import ComputeManagementClient
compute_client = "{{create your compute client using}}'"

instance = compute_client.virtual_machine_scale_set_vms.get_instance_view(
    resource_group_name='{{insert here the resource group name in which you created your scale set}}',
    vm_scale_set_name='{{insert your scale set name}}',
    instance_id='{{insert an instance id from within your scale set }}'
)

instance.as_dict()`

**Expected behavior**
instance.as_dict will contain the timeCreated field.
instance.time_created will return the creation time of the scale set virtual machine instance. 
**Screenshots**
![image](https://user-images.githubusercontent.com/59790164/201951960-70810ae3-8ef9-4237-8e13-9014fa13bdb3.png)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Wzb123456789** [comment]
Hi @DoronGaznavi, thanks for your feedback.

Please provide what method you use when doing the `Initiate instances in the new scale set` operation, so that your problem can be better solved.
