### ISSUE TITLE
Instantiating a CosmosClient throws 'NoneType' object has no attribute 'ConsistencyPolicy' error

### ISSUE THREAD

**Issue by lisabecker-ml6** [Azure/azure-sdk-for-python#27547]
- **Package Name**:  azure-cosmos
- **Package Version**:  4.3.0
- **Operating System**:  WSL Ubuntu (in VSCode)
- **Python Version**:  3.7.5

**Describe the bug**
I'm trying to instantiate a CosmosClient from a connection string. It throws an `AttributeError: 'NoneType' object has no attribute 'ConsistencyPolicy'` error. The NoSQL resource exists and contains one database with one container, which is empty. The connection string is copied from the `PRIMARY CONNECTION STRING` in the `Keys` tab of the resource. (I'm getting the same error if I use `CosmosClient(url, key)` instead)

**To Reproduce**
```
from azure.cosmos import CosmosClient
CONNECTION_STRING = <myconnectionstring>
container_service = CosmosClient.from_connection_string(CONNECTION_STRING)
```

**Expected behavior**
An instantiated CosmosClient.

**Additional context**
I saw multiple people having a similar problem with closed issues, but it still seems to throw the error with the newest version of Azure Cosmos. #26123 #21663

Interestingly, 'sometimes' I get a different error instead, mentioning that the authentication token is expired and shows that the token validation time differs from the current server time. I assume that the errors are somehow connected.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by lisabecker-ml6** [comment]
Update: I believe the authentication token error is linked to WSL being out of sync after the laptop was in sleep mode (like described here and in other GitHub issues: https://github.com/microsoft/WSL/issues/4245)

Since resetting the WSL clock with `sudo hwclock -s` regularly, I haven't encountered the `'NoneType' object has no attribute 'ConsistencyPolicy'` anymore. Since I can't reproduce the error anymore, I'll close this issue for now as it's a WSL issue, not an Azure one.

Thank you anyway and have a great day!

**Comment by alittlesliceoftom** [comment]
Same issue running CosmosClient(url, key). 

On windows running in a python venv inside a cmdr terminal

**Comment by Uranium2** [comment]
I have the same issue with an Azure ML compute instance with MSI in system-assigned for ` CosmosClient(url, key)`

I get the master key with:

``` python
cosmos_db_management_client = CosmosDBManagementClient(
    DefaultAzureCredential(
        managed_identity_client_id=os.environ.get(
            "DEFAULT_IDENTITY_CLIENT_ID", None
        )
    ),
    subscription_id,
    "https://management.azure.com",
)
keys = cosmos_db_management_client.database_accounts.list_keys(
    resource_group, cosmosdb_account_name
)
```
I can get my key, It is the same in the portal.azure UI.
But I can not connect:

``` python
client = CosmosClient(
            url=cosmos_endpoint, credential=keys.primary_master_key
        )
```
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/azureuser/localfiles/hello_world/.venv/lib/python3.8/site-packages/azure/cosmos/cosmos_client.py", line 178, in __init__
    self.client_connection = CosmosClientConnection(
  File "/home/azureuser/localfiles/hello_world/.venv/lib/python3.8/site-packages/azure/cosmos/_cosmos_client_connection.py", line 213, in __init__
    self._set_client_consistency_level(database_account, consistency_level)
  File "/home/azureuser/localfiles/hello_world/.venv/lib/python3.8/site-packages/azure/cosmos/_cosmos_client_connection.py", line 230, in _set_client_consistency_level
    user_consistency_policy = database_account.ConsistencyPolicy
AttributeError: 'NoneType' object has no attribute 'ConsistencyPolicy'
```

This error message doesn't help at all, why would this class ask for `ConsistencyPolicy` if it has the primary key?

**Comment by simorenoh** [comment]
Solved with https://github.com/Azure/azure-sdk-for-python/pull/29256.

**Comment by simorenoh** [comment]
This issue is solved with release 4.4.0b1 and authentication messages should be properly raised now. Thanks!

**Comment by delrey1** [comment]
> I have the same issue with an Azure ML compute instance with MSI in system-assigned for ` CosmosClient(url, key)`
> 
> I get the master key with:
> 
> ```python
> cosmos_db_management_client = CosmosDBManagementClient(
>     DefaultAzureCredential(
>         managed_identity_client_id=os.environ.get(
>             "DEFAULT_IDENTITY_CLIENT_ID", None
>         )
>     ),
>     subscription_id,
>     "https://management.azure.com",
> )
> keys = cosmos_db_management_client.database_accounts.list_keys(
>     resource_group, cosmosdb_account_name
> )
> ```
> 
> I can get my key, It is the same in the portal.azure UI. But I can not connect:
> 
> ```python
> client = CosmosClient(
>             url=cosmos_endpoint, credential=keys.primary_master_key
>         )
> ```
> 
> ```shell
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/azureuser/localfiles/hello_world/.venv/lib/python3.8/site-packages/azure/cosmos/cosmos_client.py", line 178, in __init__
>     self.client_connection = CosmosClientConnection(
>   File "/home/azureuser/localfiles/hello_world/.venv/lib/python3.8/site-packages/azure/cosmos/_cosmos_client_connection.py", line 213, in __init__
>     self._set_client_consistency_level(database_account, consistency_level)
>   File "/home/azureuser/localfiles/hello_world/.venv/lib/python3.8/site-packages/azure/cosmos/_cosmos_client_connection.py", line 230, in _set_client_consistency_level
>     user_consistency_policy = database_account.ConsistencyPolicy
> AttributeError: 'NoneType' object has no attribute 'ConsistencyPolicy'
> ```
> 
> This error message doesn't help at all, why would this class ask for `ConsistencyPolicy` if it has the primary key?

As the answer isn't here and as this is one of the top results in Google, for your issue I believe the solution is now in the updated README. 

Your code should now look like this:

`client = CosmosClient(
            url=cosmos_endpoint, credential=keys.primary_master_key, consistency_level='Session'
        )`

Key bit being the addition of consistency_level, more information can be found here: https://learn.microsoft.com/en-us/azure/cosmos-db/consistency-levels

**Comment by mwPy247** [comment]
Using 

```client = CosmosClient( url=cosmos_endpoint, credential=primary_key, consistency_level='Session' )```

instead of

```client = CosmosClient( url=cosmos_endpoint, credential=primary_key )```

Solved the problem for me.

The error message

```'NoneType' object has no attribute 'ConsistencyPolicy'.```

makes sense now, but didn't really help troubleshooting.

**Comment by Badrul-Goomblepop** [comment]
@mwPy247 Thanks - that worked for me!
