### ISSUE TITLE
Service Mgmt - Reserved IP create/delete are async

### ISSUE THREAD

**Issue by alexwilbur** [Azure/azure-sdk-for-python#276]
I believe these are async REST API calls and are currently missing async=True from the POST/DELETE

**Comment by alexwilbur** [comment]
Perhaps this needs a newer SM REST API revision (azure x-pat CLI uses version '2014-10-01')

**Comment by huguesv** [comment]
If that's the case, you can easily test that in too:
```
        return self._perform_post(
            self._get_reserved_ip_path(),
            _XmlSerializer.create_reserved_ip_to_xml(name, label, location),
            async=True, x_ms_version='2014-10-01')
```
I'm having inconsistent/random failures right now, so I can't say whether you are correct or not.

**Comment by alexwilbur** [comment]
It's definitely a bug - I monkey patched this last night and it's working well. https://msdn.microsoft.com/en-us/library/azure/dn722413.aspx shows it's async.

**Comment by huguesv** [comment]
Thanks for reporting this. Fix is now in master.
