### ISSUE TITLE
Azure ModuleNotFound in Python examples for azure services (after upgrade to v5)

### ISSUE THREAD

**Issue by feuersteiner** [Azure/azure-sdk-for-python#27617]
- **Azure**: 
- **5**: 
- **MacOS**:
- **3.8**: 

**Describe the bug**
The azure team deprecated the python azure package as of v5. Yet most code examples rely on it.
There's no way to run the code samples now, unless I install the azure v4 example.

**To Reproduce**
1. download the azure batch python example (https://learn.microsoft.com/en-us/azure/batch/quick-run-python)
2. instal requirements.txt
3. navigate to the src and run the file
4. You'll get a "ModuleNotFound" error

**Expected behavior**
it should work... or The azure team should supply an alternative way to use the packages without passing by the azure samples.

What's weird to me, is that the install process specifies the "azure-batch" package, yet in the import, ON THE SAME REPO, it shows as azure.batch ... hence throwing the modulenotfound error.

**Screenshots**
![Screenshot 2022-11-20 at 2 32 28 PM](https://user-images.githubusercontent.com/18667704/202905055-767bcc42-9e94-4237-9cc2-9ed22b60f160.png)

![image](https://user-images.githubusercontent.com/18667704/202905080-cc6fcf8b-b92f-4820-8f34-35cd89a56ed6.png)
![image](https://user-images.githubusercontent.com/18667704/202905097-42fabbcd-9808-4bdc-9782-bb649af4550e.png)

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Did you use https://github.com/Azure-Samples/batch-python-quickstart/blob/master/src/requirements.txt?

The package versions do not match what they show in your screenshot and azure-storage-blob 1.4.0 is deprecated.

Maybe this is the reason?

**Comment by xiangyan99** [comment]
Thanks for your feedback.

Yes. Using venv to make sure it is a clean environment is a good idea. Unfortunately, we cannot recommend users to do that in our docs because it is not always true for all scenarios and we don't want to mislead our customers.
