### ISSUE TITLE
[azure-mgmt-web]  Site Model info broken at web_app

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-sdk-for-python#27652]
- **Package Name**: azure-mgmt-web
- **Package Version**:  7.0.0
- **Operating System**: Mac OS 
- **Python Version**: 3.8

**Describe the bug**

**To Reproduce**
1. you can see broken info [here](https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.models.site?view=azure-python)

**Expected behavior**

Helpful document for users

**Screenshots**
![스크린샷 2022-11-23 오전 11 31 26](https://user-images.githubusercontent.com/38625842/203458902-9066bb48-0fce-42f0-9eaf-6745407b7436.png)

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
Currently the doc is not updated automatically: https://github.com/Azure/azure-sdk-for-python/blob/be6b5156320678531bf30db64098232b033c7982/eng/scripts/Language-Settings.ps1#L299
@danieljurek Could you help on it?
