### ISSUE TITLE
python event hub connection closing and creating delay in consuming packet

### ISSUE THREAD

**Issue by vaishnavi-mindtree** [Azure/azure-sdk-for-python#27664]
- ****: 
- **Package Version**:
-azure-core==1.24.1
azure-eventhub==5.10.0
azure-eventhub-checkpointstoreblob==1.1.4
azure-eventhub-checkpointstoreblob-aio==1.1.4
azure-storage-file-share==12.9.0
 
- **Operating System**:
- **Python Version**: 3.9

Describe the bug
I am using the python sdk to receive events from an event hub. It worked for a while but now I am getting the below error:

ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')

**To Reproduce**
1. The issue occurs ocassionally and it is logged in our logger file

**Expected behavior**
The connection should be stable
**Screenshots**

**Additional context**
**Code Snippet **
def on_event(partition_context, events):
    for event in events:
        try:
            start(event)
            partition_context.update_checkpoint(event)
        except Exception as error:
            logger.error(error)
            print("Event: ", event)
            print("Error: ", error)
def start(event):
    try:
        kk = None
        for k, each_packet in enumerate(json.loads(event.body_as_str())):
            p_values=[]
            print(each_packet)
            type = each_packet['Header']['Type']
    except Exception as exc:
        logger.error(f"{exc} ")

if __name__ == '__main__':
    checkpoint_store = BlobCheckpointStore.from_connection_string(STORAGE_CONNECTION_STR, "storage name")
    client = EventHubConsumerClient.from_connection_string(
        CONNECTION_STR, "$Default", checkpoint_store=checkpoint_store)
    if True:
        with client:
            client.receive_batch(
                on_event_batch=on_event,
                starting_position="-1",
        )
    else:
        raise Exception('Some error occurred in EventHubConsumerClient.')

**Comment by Murugan-mindtree** [comment]
HI Azure Team, 

I am also facing the same issue, please address as earlier as possible

**Comment by kashifkhan** [comment]
Hi, 

Are there any more logs or information on your side. Its a challenge to determine what exactly is happening. Usually when a connection closes these are some of the common reasons:

* Intermittent network issues -> are there any problems in the connection dropping etc
* A long turn around time for the sdk to receive a reply from the service -> are they in the same region ?
* Connection via proxy or VPN that is not stable, causing issues.

Thanks
