### ISSUE TITLE
ImportError: cannot import name 'AbstractSummaryAction'

### ISSUE THREAD

**Issue by csaras84** [Azure/azure-sdk-for-python#27663]
Hello, I received an approval to use the gated preview of Azure's Abstractive Summarization and I'm following the sample code from here - https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/samples/sample_abstract_summary.py

However I get an import error:

   from azure.ai.textanalytics import (
ImportError: cannot import name 'AbstractSummaryAction'

versions used:

azure-ai-textanalytics 5.2.0b4
azure-common           1.1.28
azure-core             1.24.2

I also tried the --pre version and it still doesn't import 'AbstractSummaryAction'

**Comment by csaras84** [comment]
> pip install azure-ai-textanalytics==5.3.0b1

This doesn't work, here is the error:

Could not find a version that satisfies the requirement azure-ai-textanalytics==5.3.0b1 (from versions: 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5, 1.0.0b6, 1.0.0, 5.0.0, 5.1.0b1, 5.1.0b2, 5.1.0b3, 5.1.0b4, 5.1.0b5, 5.1.0b6, 5.1.0b7, 5.1.0, 5.2.0b1, 5.2.0b2, 5.2.0b3, 5.2.0b4)
No matching distribution found for azure-ai-textanalytics==5.3.0b1

Please note I'm using a python virtual environment.

**Comment by kristapratico** [comment]
@csaras84 which version of Python are you using? azure-ai-textanalytics==5.3.0b1 requires Python 3.7 or greater.

**Comment by kristapratico** [comment]
@csaras84 glad to hear this was resolved. I'm going to close out this issue since I see you opened a new issue regarding the difference in results. I will respond on that issue https://github.com/Azure/azure-sdk-for-python/issues/27683
