### ISSUE TITLE
link to workspace.write_config method  does not work

### ISSUE THREAD

**Issue by MonikaDy** [Azure/azure-sdk-for-python#27661]
Link  [workspace.write_config](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/%5Bhttps://aka.ms/ml-workspace-class%5D(https://aka.ms/ml-workspace-class)?view=azure-python) method, does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e5945db-4000-bb16-abce-130029f6fa59
* Version Independent ID: 6009dd46-d576-f0dd-ba3b-809b0fc50834
* Content: [azure.ai.ml.MLClient class](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.mlclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-ml/azure.ai.ml.MLClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.MLClient.yml)
* Service: **machine-learning**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Your link is broken.

Could you please fix it?

**Comment by RakeshMohanMSFT** [comment]
This has the wrong link https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.mlclient?view=azure-python

**Comment by achauhan-scc** [comment]
write_config is not support in ml client
