### ISSUE TITLE
AML Registry Model Download not working

### ISSUE THREAD

**Issue by marvinbuss** [Azure/azure-sdk-for-python#27670]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.1.1
- **Operating System**: Windows 11
- **Python Version**: 3.9.6

**Describe the bug**
When downloading a model from the registry the download is not executed successfully.
```python
client_reg.models.download(
    name="model",
    version="1",
)
```
Output:
```sh
Downloading the model model.pkl at .\model
```
When I check the folder, there is no model. This is different when downloading from a standard AML workspace.

**To Reproduce**
1. Create the MLClient for an AML registry.
2. Try to download the model.

**Expected behavior**
Model file is downloaded to the specified location.

**Screenshots**
Not required.

**Additional context**
Not required.

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by banibrata** [comment]
@marvinbuss as we synced up offline,   you are unblocked with the private build of SDK that I shared. The issue will be fixed in the January release of the SDK.
