### ISSUE TITLE
How to avoid repeatedly upload the source code

### ISSUE THREAD

**Issue by heyheys** [Azure/azure-sdk-for-python#27688]
When I use azure.ai.ml.command() to summit a job specifying:

command(code = <local_source_dir>)             # a local code folder to run

My local source code will be uploaded to the Blob Storage. If I run multiple experiments (i.e. submitting the job multiple times), my source code will be repeatedly uploaded to the Blob Storage, sitting at the sub-directories of different directories at Blob.

**Describe the solution you'd like**
Is there a way to avoid the source code being uploaded repeatedly?

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
@azureml-github

**Comment by luigiw** [comment]
@heyheys the azure-ai-ml package duplicates before uploading. i.e. your local folder will only be uploaded if there's a change in it.
