### ISSUE TITLE
Results from Abstractive Summary on language studio portal and python sdk are different

### ISSUE THREAD

**Issue by csaras84** [Azure/azure-sdk-for-python#27683]
I'm using Azure Abstractive Summarization to summarize a bunch of captions. I'm using Python SDK sample from here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/samples/sample_abstract_summary.py

I have a story with 10 sentences and no matter what max_sentence_count we provide, with the python sdk I'm getting just a single same sentence as result, while the same yields a different result on the language studio portal 'try it out' option.

Does the language studio 'try it out' option use a different api than the one used by sdk client? Why is my SDK result different from that of the language studio portal try out?

Original input:
document = ["a man looking at another man. a man in a suit. a man looking at another man. a man looking at another man. a stone structure with carvings. a stone structure with a cross. a man in a suit opening a door. a person opening a door. a man in a suit. a man in a suit"]

Result from SDK:
Summaries abstracted:
a man in a suit opening a door.

Result from language studio 'try it out':
a man in a suit looking at another man. a man looking at a stone structure with carvings. a man opening a door.

**Comment by kristapratico** [comment]
@csaras84 it looks like the Language studio sets the sentence count to 3 by default. If you want to match the behavior in the Python client library, you can do this by setting the `sentence_count` (not `max_sentence_count`) in the `AbstractSummaryAction`:

```python
document = ["a man looking at another man. a man in a suit. a man looking at another man. a man looking at another man. a stone structure with carvings. a stone structure with a cross. a man in a suit opening a door. a person opening a door. a man in a suit. a man in a suit"]
poller = text_analytics_client.begin_analyze_actions(
    document,
    actions=[
        AbstractSummaryAction(sentence_count=3),
    ],
)
```
I tested this and see the same result between Language studio and Python client library. Let me know if I can help with anything else.

**Comment by csaras84** [comment]
> @csaras84 it looks like the Language studio sets the sentence count to 3 by default. If you want to match the behavior in the Python client library, you can do this by setting the `sentence_count` (not `max_sentence_count`) in the `AbstractSummaryAction`:
> 
> ```python
> document = ["a man looking at another man. a man in a suit. a man looking at another man. a man looking at another man. a stone structure with carvings. a stone structure with a cross. a man in a suit opening a door. a person opening a door. a man in a suit. a man in a suit"]
> poller = text_analytics_client.begin_analyze_actions(
>     document,
>     actions=[
>         AbstractSummaryAction(sentence_count=3),
>     ],
> )
> ```
> 
> I tested this and see the same result between Language studio and Python client library. Let me know if I can help with anything else.

That sentence_count works like a charm. Thanks for the quick turnaround. I'm closing this thread.
