### ISSUE TITLE
SSL Error when connecting to Azure Sdk

### ISSUE THREAD

**Issue by ashweasly** [Azure/azure-sdk-for-python#27689]
I am using form recognizer through azure sdk. please see below code.

import calendar
import datetime
import pandas as pd

from azure.core.credentials import AzureKeyCredential
from azure.ai.formrecognizer import DocumentAnalysisClient

# Put your the credencials and the containerUrl
file = 'xxxx.pdf' # File Name

formUrl = "xxxxxx".format(file)

# Azure Form Recognizer
endpoint = "xxxxx"
key = "xxxxx"

# Model id to use
model_id = "format1-neural-v10"

document_analysis_client = DocumentAnalysisClient(
    endpoint=endpoint, credential=AzureKeyCredential(key),verify = False
) 

poller = document_analysis_client.begin_analyze_document_from_url(model_id, formUrl)

and getting the following error on function call in last line of code

---------------------------------------------------------------------------
ServiceRequestError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_19000\3432336315.py in <module>
----> 1 poller = document_analysis_client.begin_analyze_document_from_url(model_id, formUrl)
      2 result = poller.result()

~\Anaconda3\lib\site-packages\azure\core\tracing\decorator.py in wrapper_use_tracer(*args, **kwargs)
     76             span_impl_type = settings.tracing_implementation()
     77             if span_impl_type is None:
---> 78                 return func(*args, **kwargs)
     79 
     80             # Merge span is parameter is set, but only if no explicit parent are passed

~\Anaconda3\lib\site-packages\azure\ai\formrecognizer\_document_analysis_client.py in begin_analyze_document_from_url(self, model_id, document_url, **kwargs)
    190             )
    191 
--> 192         return self._client.begin_analyze_document(  # type: ignore
    193             model_id=model_id,
    194             analyze_request={"urlSource": document_url},  # type: ignore

~\Anaconda3\lib\site-packages\azure\ai\formrecognizer\_generated\_operations_mixin.py in begin_analyze_document(self, model_id, pages, locale, string_index_type, analyze_request, **kwargs)
    168         mixin_instance._serialize.client_side_validation = False
    169         mixin_instance._deserialize = Deserializer(self._models_dict(api_version))
--> 170         return mixin_instance.begin_analyze_document(model_id, pages, locale, string_index_type, analyze_request, **kwargs)
    171 
    172     def begin_analyze_id_document_async(  # pylint: disable=inconsistent-return-statements

~\Anaconda3\lib\site-packages\azure\core\tracing\decorator.py in wrapper_use_tracer(*args, **kwargs)
     76             span_impl_type = settings.tracing_implementation()
     77             if span_impl_type is None:
---> 78                 return func(*args, **kwargs)
     79 
     80             # Merge span is parameter is set, but only if no explicit parent are passed

~\Anaconda3\lib\site-packages\azure\ai\formrecognizer\_generated\v2022_08_31\operations\_form_recognizer_client_operations.py in begin_analyze_document(self, model_id, pages, locale, string_index_type, analyze_request, content_type, **kwargs)
    574         cont_token = kwargs.pop('continuation_token', None)  # type: Optional[str]
    575         if cont_token is None:
--> 576             raw_result = self._analyze_document_initial(  # type: ignore
    577                 model_id=model_id,
    578                 pages=pages,

~\Anaconda3\lib\site-packages\azure\ai\formrecognizer\_generated\v2022_08_31\operations\_form_recognizer_client_operations.py in _analyze_document_initial(self, model_id, pages, locale, string_index_type, analyze_request, content_type, **kwargs)
    497         request.url = self._client.format_url(request.url, **path_format_arguments)  # type: ignore
    498 
--> 499         pipeline_response = self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
    500             request,
    501             stream=False,

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in run(self, request, **kwargs)
    209             else _TransportRunner(self._transport)
    210         )
--> 211         return first_node.send(pipeline_request)  # type: ignore

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\policies\_redirect.py in send(self, request)
    151         redirect_settings = self.configure_redirects(request.context.options)
    152         while retryable:
--> 153             response = self.next.send(request)
    154             redirect_location = self.get_redirect_location(response)
    155             if redirect_location and redirect_settings['allow']:

~\Anaconda3\lib\site-packages\azure\core\pipeline\policies\_retry.py in send(self, request)
    465                             is_response_error = True
    466                         continue
--> 467                 raise err
    468             finally:
    469                 end_time = time.time()

~\Anaconda3\lib\site-packages\azure\core\pipeline\policies\_retry.py in send(self, request)
    443                 start_time = time.time()
    444                 self._configure_timeout(request, absolute_timeout, is_response_error)
--> 445                 response = self.next.send(request)
    446                 if self.is_retry(retry_settings, response):
    447                     retry_active = self.increment(retry_settings, response=response)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
     69         _await_result(self._policy.on_request, request)
     70         try:
---> 71             response = self.next.send(request)
     72         except Exception:  # pylint: disable=broad-except
     73             _await_result(self._policy.on_exception, request)

~\Anaconda3\lib\site-packages\azure\core\pipeline\_base.py in send(self, request)
    101         return PipelineResponse(
    102             request.http_request,
--> 103             self._sender.send(request.http_request, **request.context.options),
    104             context=request.context,
    105         )

~\Anaconda3\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py in send(self, request, **kwargs)
    358 
    359         if error:
--> 360             raise error
    361         if _is_rest(request):
    362             from azure.core.rest._requests_basic import RestRequestsTransportResponse

ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

------------------------------------------------------------------------------------------------------------------------------------
Tried this 

import requests
requests.get('https://login.microsoftonline.com/')

This works fine

Also tried installing and upgrading certificates

pip install certifi
pip install --upgrade certifi

None of these seem to solve my issues, kindly help on above

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by catalinaperalta** [comment]
Thanks for reaching out @ashweasly. The requests.get() call should be made on the Form Recognizer endpoint instead of the https://login.microsoftonline.com/ endpoint, since you aren't using a credential that will use that endpoint. 

Additionally, so that we can confirm that this issue is related to a certificate configuration problem, could you update the `verify` kwarg set on the client to `connection_verify=False` please? If that works, then it would indicate that this is probably related to some missing/incorrect certificate set up.
