### ISSUE TITLE
Intermittent dropping of files while mounting FileDataset in local machine.

### ISSUE THREAD

**Issue by deepankersingh96** [Azure/azure-sdk-for-python#27684]
- **Package Name**: azureml-core
- **Package Version**:  1.44.0 
- **Operating System**: Ubuntu 18.04.6 LTS
- **Python Version**: Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)

**Describe the bug**
The task is fairly simple. I have uploaded Synscapes dataset (https://synscapes.on.liu.se/download.html) to Azure Blob Storage and have registered the same in my AzureML Studio datastores. The dataset contains 25000 image ".png" files that needs to be mounted to the local machine and then on each image a small feature extraction using OpenCV needs to be done. The extracted features then are stored as a .pckl file. Out of the 25000 image files some files at random are not found in the mount path as suggested by the OpenCV error: [ WARN:0@12.457] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('<path/to/file/filename>.png'): can't open/read file: check file path/integrity
 
Refer this code snippet for details:
``` python
from azureml.core import Workspace, Dataset
workspace = Workspace(subscription_id, resource_group, workspace_name)
datastorage = Dataset.get_by_name(workspace, name='<azureml_datastore_name>')

with datastorage.mount() as mount_context:
    features = []
    mount_path = mount_context.mount_point

    for image_path in image_paths:
        image = cv2.imread(os.path.join(mount_path, label_path), cv2.IMREAD_UNCHANGED)
        features.append(get_feature(image))

    with open(save_path, "wb") as handle:
        pickle.dump(features , handle, protocol = pickle.HIGHEST_PROTOCOL)
```
Output: After running successfully for few thousand images, OpenCV throws the following
OpenCV error: [ WARN:0@12.457] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('<path/to/file/filename>.png'): can't open/read file: check file path/integrity

I have veryfied that the image file exists and is not corrupted. One thing that verifies this claim is that a given image gets loaded in few runs while throws error in other runs.

**To Reproduce**
1. Register Synscapes dataset to Azure Blob Storage.
2. Register the same to Azure datastorage.
3. Mount data to local machine as shown in the code snippet above. 
4. Wait for the errors to be thrown.

**Expected behavior**
All the 25000 images (in this scenario) should be accessible on the local machine after mounting the dataset from AzureML Studio.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
@azureml-github
