### ISSUE TITLE
Load Testing samples issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#27745]
1.

Section [link](https://github.com/Azure/azure-sdk-for-python/blob/fb678cd5ef4aba1cc261aa6a80b72baaf549dabb/sdk/loadtestservice/azure-developer-loadtesting/samples/check_jmx_validation.py#L45):

![image](https://user-images.githubusercontent.com/80307197/204724057-6827d349-7c6c-423f-83f6-56a818ca559e.png)

Reason:
AttributeError: 'LoadTestingAdministration' object has no attribute 'check_validation_status'.

Suggestion:
Change code to 
```
result = client.load_test_administration.get_load_test(TEST_ID)["inputArtifacts"]["testScriptUrl"]

print(result)
print(result["filename"])
```

@lmazuel , @mikekistler , @msyyc , @iscai-msft for notification.

**Comment by msyyc** [comment]
@AFengKK Thanks for you feedback. 
I think it is related with the operation name change in 1.0.0b2. Could you help make a PR to update the sample? @NiveditJain

**Comment by NiveditJain** [comment]
Thanks @AFengKK for pointing out and @msyyc for update, we are in process of updating this method, the latest PR would resolve this. Thanks!

**Comment by v-xuto** [comment]
@NiveditJain Regarding the fix of this issue, what is the current progress?

**Comment by NiveditJain** [comment]
Hi @v-xuto, this has been fixed already with the current code, kindly let me know if you have any questions or issue still persists.
Thanks!

**Comment by v-xuto** [comment]
@NiveditJain This sample does not exist anymore, we will close this issue.
