### ISSUE TITLE
Missing JobService class in import path

### ISSUE THREAD

**Issue by pievalentin** [Azure/azure-sdk-for-python#27758]
- **Package Name**:  azure.ai.ml
- **Package Version**: 1.1.2
- **Operating System**: Linux
- **Python Version**: py10

**Describe the bug**
I am trying to import the JobService class following[ this azure example ](https://github.com/Azure/azureml-examples/blob/main/sdk/python/jobs/single-step/scikit-learn/iris/iris-scikit-learn.ipynb)
It's failing on the import.
`from azure.ai.ml.entities import JobService`
returns
`ImportError: cannot import name 'JobService' from 'azure.ai.ml.entities' (/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/entities/__init__.py)`

I am running this code on a azure ml compute instance.

**To Reproduce**
1. `pip install azure-ai-ml==1.1.2`
2. Copy this [notebook](https://github.com/Azure/azureml-examples/blob/main/sdk/python/jobs/single-step/scikit-learn/iris/iris-scikit-learn.ipynb)
3. Run the first cell

**Expected behavior**
It should be able to import JobService

**Comment by kashifkhan** [comment]
Thanks for the feedback @pievalentin. We will investigate asap.

**Comment by needuv** [comment]
@TonyJ1, could you please take a look at this?

**Comment by TonyJ1** [comment]
Thanks @pievalentin!
Could you please run the below code and share the response?
Thanks!

```
!pip freeze | grep azure-ai-ml
!python -V

from azure.ai.ml.entities import JobService
print(JobService)
```
![image](https://user-images.githubusercontent.com/41344586/205839236-ad8eb46b-cc40-48ce-9245-af130b136b56.png)

**Comment by pievalentin** [comment]
@TonyJ1 Here is what I have in my notebook.
![image](https://user-images.githubusercontent.com/14977219/205998820-ca46a3be-1c8e-4d3e-8b43-2cab4cf1d2ac.png)

Here are imports
![image](https://user-images.githubusercontent.com/14977219/205999595-0f78dc9f-2313-428a-a0ec-bd2f167ff36d.png)

**Comment by pievalentin** [comment]
In my description I mentioned py30 but maybe the vscode is confused about which kernel to use

**Comment by TonyJ1** [comment]
Thanks @pievalentin  for trying and confirming the python version as 3.8.5.
Could you please try the following and provide the response?
Thanks!
```

from azure.ai.ml.entities import Job
print(Job)

from azure.ai.ml.entities import CommandJobLimits
print(CommandJobLimits)

```
![image](https://user-images.githubusercontent.com/41344586/206002917-fe83e782-c716-456a-967f-146e679a53b2.png)

**Comment by pievalentin** [comment]
```python
from azure.ai.ml.entities import Job
print(Job)

from azure.ai.ml.entities import CommandJobLimits
print(CommandJobLimits)
```
![image](https://user-images.githubusercontent.com/14977219/206003283-aa0f349d-4bb4-4407-82ba-8672e0084032.png)

**Comment by TonyJ1** [comment]
Though your python version is `3.8.5`, based on the below image, it looks like it is using  `3.10`
![image](https://user-images.githubusercontent.com/41344586/206004362-919d26ec-00e7-4f2d-9962-0b9a20ffd620.png)

**Comment by pievalentin** [comment]
Yes true. I am trying the same step on the jupyter server directly on azure ml and I still have this mismatch of python version

**Comment by pievalentin** [comment]
When I select the py10 kernel
`python -v` return 3.8
but the import points to the py10 🤔 
Any clue on how I could fix that?

**Comment by TonyJ1** [comment]
@pievalentin 
Could you please try the following?
1. uninstall `py10` 
2. create new `venv` or new `conda env`
