### ISSUE TITLE
[Function App] Specific SDK method for CORS info

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-sdk-for-python#27779]
- **Package Name**:  azure-mgmt-web
- **Package Version**: 7.0.0
- **Operating System**: Mac OS
- **Python Version**:  3.8

**Describe the bug**

It's not bug, I have a question about how to get CORS info for Function App

I searched [here](https://learn.microsoft.com/ko-kr/python/api/azure-mgmt-web/azure.mgmt.web.websitemanagementclient?view=azure-python) but I couldn't find that.

I need some help. 

Thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

![스크린샷 2022-12-01 오후 7 19 16](https://user-images.githubusercontent.com/38625842/205027702-ea9c3cc7-dcd6-427b-a126-e123c64484b7.png)

**Additional context**

**Comment by PramodValavala-MSFT** [comment]
@ImMin5 The [`CorsSettings` object](https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.models.corssettings?view=azure-python) is available in the [`SiteConfigResource` object](https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.models.siteconfigresource?view=azure-python) which can be fetched by using the [`get_configuration` method](https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.operations.webappsoperations?view=azure-python#azure-mgmt-web-v2021-02-01-operations-webappsoperations-get-configuration).

```py
client = WebSiteManagementClient(credential, subscription_id)
config = client.web_apps.get_configuration(resource_group_name, name)
corsSettings = config.cors
```

**Comment by ImMin5** [comment]
> @ImMin5 The [`CorsSettings` object](https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.models.corssettings?view=azure-python) is available in the [`SiteConfigResource` object](https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.models.siteconfigresource?view=azure-python) which can be fetched by using the [`get_configuration` method](https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.operations.webappsoperations?view=azure-python#azure-mgmt-web-v2021-02-01-operations-webappsoperations-get-configuration).
> 
> ```python
> client = WebSiteManagementClient(credential, subscription_id)
> config = client.web_apps.get_configuration(resource_group_name, name)
> corsSettings = config.cors
> ```

Hi, @PramodValavala-MSFT 

Thanks, exactly what I looking for
very helpful for me.
