### ISSUE TITLE
difficult to find full reference docs

### ISSUE THREAD

**Issue by lindacmsheard** [Azure/azure-sdk-for-python#27801]
I found it hard to find my way to the [comprehensive API reference documentation](https://learn.microsoft.com/en-gb/python/api/azure-ai-ml/azure.ai.ml?view=azure-python) from this page.
I reached this page from the [Azure ML documentation](https://learn.microsoft.com/en-us/azure/machine-learning/) in the side menu: `Reference`>`Python SDK v2` , which brings you to this page. 

you then have to determine that none of the links at the top take you to API reference documentation. You currently have to follow the link to https://aka.ms/azsdk/python/all from this page, and then search for the ml package, unless you notice that the navigation menu on the left is now different and has a next menu item below this page that gets you to what you need after another extra click: https://learn.microsoft.com/en-gb/python/api/azure-ai-ml/azure.ai.ml?view=azure-python

Can the comprehensive API docs be linked a bit more directly on the page about the SDK v2?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0d7f9b-a80a-4da1-dcd6-1b61a7bbf134
* Version Independent ID: 70e9f892-5b42-b888-1881-5ba039c260b1
* Content: [Azure ML Package client library for Python](https://learn.microsoft.com/en-gb/python/api/overview/azure/ai-ml-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/ai-ml-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/ai-ml-readme.md)
* Service: **ml**
* GitHub Login: @paulshealy1
* Microsoft Alias: **paulsh**

**Comment by achauhan-scc** [comment]
documentation was revised several times after the issue was reported.
