### ISSUE TITLE
3rd Party Marketplace Images

### ISSUE THREAD

**Issue by whoarethebritons** [Azure/azure-sdk-for-python#2780]
Is there a way to check if a 3rd party marketplace virtual machine image can be used by a subscription without trying to create the VM? For example is there some way I can list which images have already had agreements accepted?

Additionally, is there a way to authorize a subscription for a virtual machine image programmatically?

I would like to be able to determine or authorize a subscription for 3rd party marketplace image to run machines with managed disks.

**Comment by lmazuel** [comment]
@yugangw-msft opinion?

**Comment by yugangw-msft** [comment]
you can [query](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/operations/marketplace_agreements_operations.py#L42) the market-term and check the `accepted` field.

**Comment by yugangw-msft** [comment]
> I would like to be able to determine or authorize a subscription for 3rd party marketplace image to run machines with managed disks.
If you are asking about whether you can limit access to a subset of marketplace images, then I don't think there are such support, but in the near future, you can consider the [shared-image-gallery](https://azure.microsoft.com/en-us/blog/shared-image-gallery-now-in-limited-public-preview/) which you can leverage regular role based access control.

**Comment by yugangw-msft** [comment]
> For example if I check that subscription x has not accepted the marketplace terms can I accept the marketplace terms or prompt the user to accept the terms?

It depends on an individual application's context. If your app just delegates the current user (like lots of web applications), then you can prompt users to accept the term; if your app runs under its own credential (like lots of LOB application) with access to the subscription, then you can just accept the term before create a VMs for users

**Comment by whoarethebritons** [comment]
I appear to be having an issue querying the marketplace agreements

```
marketplace_ordering.marketplace_agreements.get('publisher', 'offer', plan)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python2.7/site-packages/azure/mgmt/marketplaceordering/operations/marketplace_agreements_operations.py", line 90, in get
    response = self._client.send(request, header_parameters, stream=False, **operation_config)
  File "lib/python2.7/site-packages/msrest/service_client.py", line 369, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "lib/python2.7/site-packages/msrest/exceptions.py", line 57, in raise_with_traceback
    raise error
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/{subscription}/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualmachine/publishers/{publisher}/offers/{offer}/plans/{serialized plan}/agreements/current?api-version=2015-06-01 (Caused by ResponseError('too many 502 error responses',))
```

**Comment by lmazuel** [comment]
Hyphen is a safe character, and we don't url-encode it. It's generally allowed in URL:
https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions

Could you link your old issue?

**Comment by whoarethebritons** [comment]
https://github.com/Azure/azure-cli/issues/3411#issuecomment-359123790

**Comment by lmazuel** [comment]
Hi @whoarethebritons 
I wasn't able to reproduce it:
```python
        result = self.client.marketplace_agreements.get(
            publisher_id="intel-bigdl",
            offer_id="bigdl_vm",
            plan_id="bigdl_vm_0p4"
        )
        from pprint import pprint
        pprint(result.as_dict())
```
gives me
```shell
{'accepted': False,
 'id': '/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/providers/Microsoft.MarketplaceOrdering/offerTypes/VirtualMachine/publishers/intel-bigdl/offers/bigdl_vm/plans/bigdl_vm_0p4/agreements/current',
 'license_text_link': 'https://storelegalterms.blob.core.windows.net/legalterms/3E5ED_legalterms_INTEL%253a2DBIGDL%253a24BIGDL%253a5FVM%253a24BIGDL%253a5FVM%253a5F0P4%253a24LPVML5SNN52KTQK2VUTTKOQB2GF5VLGDDHYIMTNCI5TVT54RPWAEFUUJFPSGA2SZ7YGQ4EEOVRA6UCUVLHC7JNZNNCNFUJT63EQ2XVI.txt',
 'name': 'bigdl_vm_0p4',
 'plan': 'bigdl_vm_0p4',
 'privacy_policy_link': 'https://www.intel.com/content/www/us/en/privacy/intel-privacy-notice.html',
 'product': 'bigdl_vm',
 'publisher': 'intel-bigdl',
 'retrieve_datetime': '2018-08-14T23:53:38.9764255Z',
 'signature': 'FH3SCI6A3JNV7EEEB6SCCGM4K5X2LPEROXSPQKDVHEUOHQYGOYKT4FSROUJMKTV6G4PTXEMUMC2A546FOFZKAYTP7FKG4OLVFE4FPEI',
 'type': 'Microsoft.MarketplaceOrdering/offertypes'}
```

Could you share the value you pass when you have your issue?

**Comment by whoarethebritons** [comment]
Ok, your code snippet was extremely helpful. Thank you so much. 

here's what I had:
```
azure_image_id = "appscale-marketplace:appscale:3:3.5.2"
publisher, offer, sku, version = azure_image_id.split(":")
compute_client = ComputeManagementClient(credentials, params['azure_subscription_id'])
zone = params['zone']
image = compute_client.virtual_machine_images.get(
          zone, publisher, offer, sku, version)
image_ref = ImageReference(publisher=publisher,
                           offer=offer,
                           sku=sku,
                           version=version)
marketplace_ordering = MarketplaceOrderingAgreements(credentials, params['azure_subscription_id'])
plan = image.plan
marketplace_ordering.marketplace_agreements.get(publisher, offer, plan)
```

but from your snippet if I change that last line to
`print marketplace_ordering.marketplace_agreements.get(publisher, offer, '3.5.2')`

then it works perfectly.

I had not connected "plan" as "version" until I saw your snippet.

But now I'm wondering is there a way to update 'accepted' to True?

**Comment by yugangw-msft** [comment]
you can check out how [CLI's logc](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py#L1342-L1344) does it and port over.

**Comment by lmazuel** [comment]
Thanks @yugangw-msft !
Writing the code here, so it stays forever:
```python
    term = market_place_client.marketplace_agreements.get(publisher, offer, plan)
    term.accepted = True
    market_place_client.marketplace_agreements.create(publisher, offer, plan, term)
```

Also @whoarethebritons , there was a small issue in your code, the line before the last should have been:
```python
plan = image.plan.name"
```
Since `image.plan` is a [complex object](https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2018_04_01.models.virtualmachineimage?view=azure-python), and you need a string.

**Comment by whoarethebritons** [comment]
Yes thanks I'm testing that in my code right now actually 😄 
Interesting... is `image.plan.name` always the same as the version?

**Comment by lmazuel** [comment]
@whoarethebritons that's an excellent question, and unfortunately I don't know for sure :(. @yugangw-msft ?

**Comment by yugangw-msft** [comment]
I don't know, as I have never been an market place image vendor. But for this image of `appscale-marketplace:appscale:3:3.5.2`, the plan name `3` is different from the version `3.5.2`, which makes sense as all versions of 3.x might share the same billing model.
I believe you do not need this anymore based on the code you provided. It always starts with querying the image and the plan information can be retrieved from the image, so the actual value should not matter. Also on top of Laurent's suggestion, for the call of `marketplace_ordering.marketplace_agreements.get(publisher, offer, plan)` , please propagate the publisher and product from `image.plan` as well
