### ISSUE TITLE
TypeError: load_component() missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by levalencia** [Azure/azure-sdk-for-python#27819]
load_component expects a path parameter which is not in the documentation and no matter what I do, I cant make this works

# importing the Component Package
from azure.ai.ml import load_component

# Loading the component from the yml file
train_component = load_component(source=os.path.join(train_src_dir, "train.yml"))

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f97f70b2-cf01-935c-3518-8476907c04be
* Version Independent ID: 455fd1a3-5529-efb9-8a36-63d43e45d6b8
* Content: [azure.ai.ml package](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-ml/azure.ai.ml.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.yml)
* Service: **machine-learning**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kashifkhan** [comment]
Thank you for the feedback @levalencia . We will investigate asap

**Comment by levalencia** [comment]
for some reason when I check my versions 

I have
azure-ai-ml              2.4.1

But the latest is  1.1.2

Whats going on here?
This is on a new compute instance using the v2 Kernel

**Comment by levalencia** [comment]
If I comment this:
print(f"Endpint {endpoint.name} provisioning state: {endpoint.provisioning_state}")

it works, the error not very friendly for just a print line.

**Comment by achauhan-scc** [comment]
tested with latest, I able to use load_component without any issue, closing the issue.

**Comment by levalencia** [comment]
I dont see the fix in a related commit,
