### ISSUE TITLE
SparkR statement support in azure-synapse-spark

### ISSUE THREAD

**Issue by shakeelansari63** [Azure/azure-sdk-for-python#27834]
- **Package Name**: azure-synapse-spark
- **Package Version**: 0.7.0
- **Operating System**: any
- **Python Version**: py3

**Describe the bug**
Now that Synapse notebooks support SparkR, please add support for sparkR in azure-synapse-spark so that we can submit sparkR statements using this package.

**To Reproduce**
1. Add SparkR in `kind` parameter of SparkStatementOptions

**Expected behavior**
Submit sparkR statement on Spark Pool

**Screenshots**

**Additional context**
Currently this package only support `spark`, `pyspark`, `dotnetspark`, `sql` statement kinds.

**Comment by kashifkhan** [comment]
Thank you for your feedback @shakeelansari63 . We will get back to you asap

**Comment by xiangyan99** [comment]
Thank you for the updates.

These enums come from https://github.com/Azure/azure-rest-api-specs/blob/main/specification/synapse/data-plane/Microsoft.Synapse/stable/2020-12-01/sparkJob.json#L1542.

Please open an issue in that repo.
