### ISSUE TITLE
"Explore the Management APIs" link is broken

### ISSUE THREAD

**Issue by bkane-msft** [Azure/azure-sdk-for-python#27830]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 311abc2c-2b72-72d9-87a5-7126043554eb
* Version Independent ID: 166e900f-b6b2-8f9f-c626-546491e4d2d7
* Content: [Azure Traffic Manager SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/traffic-manager?view=azure-python)
* Content Source: [docs-ref-services/latest/traffic-manager.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/traffic-manager.md)
* Service: **trafficmanager**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by bkane-msft** [comment]
Internal Team link: https://teams.microsoft.com/l/message/19:b1620cabfa8049329cee7ba42b06abe6@thread.skype/1670521562987?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=68ae9c56-b648-45f2-b7d3-c65feb9b3d20&parentMessageId=1670521562987&teamName=Python&channelName=General&createdTime=1670521562987

**Comment by msyyc** [comment]
Hi @sima-zhu @danieljurek the following link is broken, could you help us how to fix it? Thanks!
![image](https://user-images.githubusercontent.com/70930885/207266517-02fa95a1-6b43-4c0b-b5a7-eb17596a0fc2.png)

(https://learn.microsoft.com/en-us/python/api/overview/azure/traffic-manager?view=azure-python)

**Comment by sima-zhu** [comment]
@msyyc We can help update. Do you know the right link to use?

**Comment by msyyc** [comment]
Hi @sima-zhu I think the right link shall be https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-trafficmanager-readme?view=azure-python
By the way, I am wondering why different services have different Overview. For example,

![image](https://user-images.githubusercontent.com/70930885/210470552-f705912d-51a4-408c-9d53-dac1deab0b70.png)
[Traffic Manager Overview](https://learn.microsoft.com/en-us/python/api/overview/azure/traffic-manager?view=azure-python)
![image](https://user-images.githubusercontent.com/70930885/210470401-bcff0a0f-605f-48a5-b546-8584167bf683.png)
[Web PubSub Overview](https://learn.microsoft.com/en-us/python/api/overview/azure/web-pubsub?view=azure-python)

And I find many `Explore the Management APIs` doesn't work like [sql](https://learn.microsoft.com/en-us/python/api/overview/azure/sql?view=azure-python)
![image](https://user-images.githubusercontent.com/70930885/210470791-408629de-fa70-48bc-bde4-0a26e0b4c7a1.png)

So maybe we shall avoid use the `Explore the Management APIs`?

**Comment by sima-zhu** [comment]
@msyyc I think the easiest way we can go is to delete the service readme file and we will generate a default one like this https://learn.microsoft.com/en-us/dotnet/api/overview/azure/app-configuration?view=azure-dotnet

**Comment by sima-zhu** [comment]
@xboxeer FYI, the issue is talking about the same invalid blue button as email.

**Comment by msyyc** [comment]
@sima-zhu Got it and please help merge https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1669
