### ISSUE TITLE
Adding new task with dependencies returns error

### ISSUE THREAD

**Issue by krzysztofstepien-tomtom** [Azure/azure-sdk-for-python#27859]
- **azure-batch**: 
- **13.0.0**: 
- **macOS 11.6**:
- **Python 3.10.8**: 

**Describe the bug**
Once i try to create new batch task that depends on another one, I am getting the following error:
```
Task with id `1111` failed due to client error - UnsupportedProperty::{'additional_properties': {}, 'lang': 'en-US', 'value': 'One of the properties specified in the request body is not supported.\nRequestId:...\nTime:...'}
```

When i remove ids from ```task_ids``` field and leave it empty, the script launches without any errors.

**To Reproduce**
1.  Creating new task and appending it to the list. Then adding this collection to the batch client
```
tasks = []
job_id = 111
tasks.append(batchmodels.TaskAddParameter(
      id=...,
      command_line=...,
      container_settings=....,
      user_identity=....,
      depends_on=batchmodels.TaskDependencies(
          task_ids=["task_0"]))
)
batch_client.task.add_collection(job_id, tasks)

```

**Comment by kashifkhan** [comment]
Thanks for the feedback @krzysztofstepien-tomtom . We will investigate asap.

**Comment by andykitch** [comment]
Any update on this please?
