### ISSUE TITLE
Why is EventHub enqueued_time of type `Optional[datetime.datetime]`?

### ISSUE THREAD

**Issue by deeTEEcee** [Azure/azure-sdk-for-python#27867]
I'm using `EventHubConsumerClient` and when reading `on_event`, `enqueued_time` is a requirement for our system to use timestamp state and manage progress. 

Does the IotHub always return event objects with an enqueued_time?

**Comment by kashifkhan** [comment]
Hi @deeTEEcee, I'm working to get an answer for you and have reached out to the IoT hub team. Will update as soon as I have something.

**Comment by deeTEEcee** [comment]
thanks, appreciate that. my strong guess is that it never happens and i shouldn't worry too much about the type annotation

**Comment by kashifkhan** [comment]
Hi @deeTEEcee, the guess is correct :) There was one case where `enqueued_time` would not show up and that was in telemetry data. Cloud to device, device to cloud messages always have it. Now even telemetry data has that included and the typing in the SDK reflects that.

**Comment by deeTEEcee** [comment]
thanks, appreciate the quick response.
