### ISSUE TITLE
Installing azure-servicebus in the python-3.9-alpine

### ISSUE THREAD

**Issue by etutionlk** [Azure/azure-sdk-for-python#27902]
I am currently working on `python:3.9-alpine` docker image. I tried to install the `azure-servicebus==7.3.3 `and I got the following error. After that I tried with the lastest version of `azure-servicebus==7.8.1
`
Still I got the same error. Could you guys help me to overcome this issue ?

`Building wheel for uamqp (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for uamqp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [267 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/compat.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/mgmt_operation.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/constants.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/utils.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/address.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/sender.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/errors.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/client.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/message.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/connection.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/session.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/types.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/receiver.py -> build/lib.linux-x86_64-cpython-39/uamqp
      copying uamqp/__init__.py -> build/lib.linux-x86_64-cpython-39/uamqp
      creating build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      copying uamqp/async_ops/utils.py -> build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      copying uamqp/async_ops/connection_async.py -> build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      copying uamqp/async_ops/mgmt_operation_async.py -> build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      copying uamqp/async_ops/sender_async.py -> build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      copying uamqp/async_ops/client_async.py -> build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      copying uamqp/async_ops/receiver_async.py -> build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      copying uamqp/async_ops/session_async.py -> build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      copying uamqp/async_ops/__init__.py -> build/lib.linux-x86_64-cpython-39/uamqp/async_ops
      creating build/lib.linux-x86_64-cpython-39/uamqp/authentication
      copying uamqp/authentication/cbs_auth.py -> build/lib.linux-x86_64-cpython-39/uamqp/authentication
      copying uamqp/authentication/cbs_auth_async.py -> build/lib.linux-x86_64-cpython-39/uamqp/authentication
      copying uamqp/authentication/common.py -> build/lib.linux-x86_64-cpython-39/uamqp/authentication
      copying uamqp/authentication/__init__.py -> build/lib.linux-x86_64-cpython-39/uamqp/authentication
      running egg_info
      writing uamqp.egg-info/PKG-INFO
      writing dependency_links to uamqp.egg-info/dependency_links.txt
      writing requirements to uamqp.egg-info/requires.txt
      writing top-level names to uamqp.egg-info/top_level.txt
      reading manifest file 'uamqp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'uamqp.egg-info/SOURCES.txt'
      copying uamqp/c_uamqp.c -> build/lib.linux-x86_64-cpython-39/uamqp
      running build_ext
      will build uamqp in build/temp.linux-x86_64-cpython-39/cmake
      Building with generator flags: -G "Unix Makefiles"
      calling cmake /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release
      -- The C compiler identification is GNU 12.2.1
      -- The CXX compiler identification is GNU 12.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Deprecation Warning at deps/azure-macro-utils-c/CMakeLists.txt:4 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Warning (dev) at deps/azure-macro-utils-c/CMakeLists.txt:14 (option):
        Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
        --help-policy CMP0077" for policy details.  Use the cmake_policy command to
        set the policy and suppress this warning.
      
        For compatibility with older versions of CMake, option is clearing the
        normal variable 'run_int_tests'.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CMake Deprecation Warning at deps/umock-c/CMakeLists.txt:4 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- Looking for include file stdint.h
      -- Looking for include file stdint.h - found
      -- Looking for include file stdbool.h
      -- Looking for include file stdbool.h - found
      -- target architecture: x86_64
      -- Performing Test CXX_FLAG_CXX11
      -- Performing Test CXX_FLAG_CXX11 - Success
      -- Found OpenSSL: /usr/lib/libcrypto.so (found version "3.0.7")
      -- target architecture: x86_64
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/build/temp.linux-x86_64-cpython-39/cmake
      calling cmake --build . --config Release
      [  0%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/azure_base32.c.o
      [  1%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/azure_base64.c.o
      [  2%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/buffer.c.o
      [  3%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/constbuffer_array.c.o
      [  4%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/constbuffer_array_batcher.c.o
      [  5%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/connection_string_parser.c.o
      [  6%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/constbuffer.c.o
      [  7%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/consolelogger.c.o
      [  8%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/crt_abstractions.c.o
      [  9%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/constmap.c.o
      [ 10%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/doublylinkedlist.c.o
      [ 11%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gballoc.c.o
      [ 12%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gbnetwork.c.o
      [ 13%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gb_stdio.c.o
      [ 14%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gb_time.c.o
      [ 15%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gb_rand.c.o
      [ 16%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/hmac.c.o
      [ 17%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/hmacsha256.c.o
      [ 18%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/xio.c.o
      [ 19%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/singlylinkedlist.c.o
      [ 20%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/map.c.o
      [ 21%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/sastoken.c.o
      [ 22%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/sha1.c.o
      [ 23%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/sha224.c.o
      [ 24%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/sha384-512.c.o
      [ 25%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/strings.c.o
      [ 26%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/string_token.c.o
      [ 27%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/string_tokenizer.c.o
      [ 28%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/uuid.c.o
      [ 29%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/urlencode.c.o
      [ 30%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/usha.c.o
      [ 31%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/vector.c.o
      [ 32%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/xlogging.c.o
      [ 33%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/optionhandler.c.o
      [ 34%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/memory_data.c.o
      [ 35%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/agenttime.c.o
      [ 36%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/condition_pthreads.c.o
      [ 37%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/lock_pthreads.c.o
      [ 38%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/platform_linux.c.o
      [ 39%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/socketio_berkeley.c.o
      [ 40%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/tickcounter_linux.c.o
      [ 41%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/threadapi_pthreads.c.o
      [ 42%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/uniqueid_stub.c.o
      [ 43%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/envvariable.c.o
      [ 44%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/dns_resolver_sync.c.o
      [ 45%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/linux_time.c.o
      [ 46%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/httpapiex.c.o
      [ 47%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/httpapiexsas.c.o
      [ 48%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/httpheaders.c.o
      [ 49%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/httpapi_compact.c.o
      [ 50%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/http_proxy_io.c.o
      [ 51%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function 'engine_destroy':
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:762:9: error: 'ENGINE_free' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
        762 |         ENGINE_free(tls->engine); // Release structural reference.
            |         ^~~~~~~~~~~
      In file included from /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:9:
      /usr/include/openssl/engine.h:493:27: note: declared here
        493 | OSSL_DEPRECATEDIN_3_0 int ENGINE_free(ENGINE *e);
            |                           ^~~~~~~~~~~
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function 'engine_load':
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:772:5: error: 'ENGINE_by_id' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
        772 |     tls->engine = ENGINE_by_id(tls->engine_id);
            |     ^~~
      /usr/include/openssl/engine.h:336:31: note: declared here
        336 | OSSL_DEPRECATEDIN_3_0 ENGINE *ENGINE_by_id(const char *id);
            |                               ^~~~~~~~~~~~
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function 'add_certificate_to_store':
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:961:24: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
        961 |             bio_method = BIO_s_mem();
            |                        ^
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function 'create_openssl_instance':
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1058:9: error: 'TLSv1_2_method' is deprecated: Since OpenSSL 1.1.0 [-Werror=deprecated-declarations]
       1058 |         method = TLSv1_2_method();
            |         ^~~~~~
      In file included from /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:5:
      /usr/include/openssl/ssl.h:2031:50: note: declared here
       2031 | OSSL_DEPRECATEDIN_1_1_0 __owur const SSL_METHOD *TLSv1_2_method(void); /* TLSv1.2 */
            |                                                  ^~~~~~~~~~~~~~
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1062:9: error: 'TLSv1_1_method' is deprecated: Since OpenSSL 1.1.0 [-Werror=deprecated-declarations]
       1062 |         method = TLSv1_1_method();
            |         ^~~~~~
      /usr/include/openssl/ssl.h:2023:50: note: declared here
       2023 | OSSL_DEPRECATEDIN_1_1_0 __owur const SSL_METHOD *TLSv1_1_method(void); /* TLSv1.1 */
            |                                                  ^~~~~~~~~~~~~~
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1066:9: error: 'TLSv1_method' is deprecated: Since OpenSSL 1.1.0 [-Werror=deprecated-declarations]
       1066 |         method = TLSv1_method();
            |         ^~~~~~
      /usr/include/openssl/ssl.h:2015:50: note: declared here
       2015 | OSSL_DEPRECATEDIN_1_1_0 __owur const SSL_METHOD *TLSv1_method(void); /* TLSv1.0 */
            |                                                  ^~~~~~~~~~~~
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function 'tlsio_openssl_init':
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1224:5: error: 'ERR_load_BIO_strings' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
       1224 |     ERR_load_BIO_strings();
            |     ^~~~~~~~~~~~~~~~~~~~
      In file included from /usr/include/openssl/cryptoerr.h:17,
                       from /usr/include/openssl/crypto.h:38,
                       from /usr/include/openssl/bio.h:30,
                       from /usr/include/openssl/ssl.h:29:
      /usr/include/openssl/cryptoerr_legacy.h:31:27: note: declared here
         31 | OSSL_DEPRECATEDIN_3_0 int ERR_load_BIO_strings(void);
            |                           ^~~~~~~~~~~~~~~~~~~~
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function 'tlsio_openssl_deinit':
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1252:5: error: 'ERR_remove_thread_state' is deprecated: Since OpenSSL 1.1.0 [-Werror=deprecated-declarations]
       1252 |     ERR_remove_thread_state(NULL);
            |     ^~~~~~~~~~~~~~~~~~~~~~~
      In file included from /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:6:
      /usr/include/openssl/err.h:485:30: note: declared here
        485 | OSSL_DEPRECATEDIN_1_1_0 void ERR_remove_thread_state(void *);
            |                              ^~~~~~~~~~~~~~~~~~~~~~~
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function 'tlsio_openssl_setoption':
      /tmp/pip-install-w45mloaq/uamqp_5e181e9a33c143778a9546b9a086097d/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1724:13: error: 'ENGINE_load_builtin_engines' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
       1724 |             ENGINE_load_builtin_engines();
            |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/openssl/engine.h:358:28: note: declared here
        358 | OSSL_DEPRECATEDIN_3_0 void ENGINE_load_builtin_engines(void);
            |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      cc1: all warnings being treated as errors
      make[2]: *** [deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/build.make:790: deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o] Error 1
      make[1]: *** [CMakeFiles/Makefile2:943: deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/all] Error 2
      make: *** [Makefile:146: all] Error 2
      Traceback (most recent call last):
        File "/home/watchlist/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/watchlist/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/watchlist/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 260, in <module>
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-n_mt_wfc/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 134, in run
        File "<string>", line 188, in build_cmake
        File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2.
      [end of output]`

**Comment by kashifkhan** [comment]
Hi @etutionlk , 

The reason why that error is happening is because the dependency of `uamqp` is built on manyLinux2014 which doesn`t support alpine linux. There are instructions to install from source [here](https://github.com/Azure/azure-uamqp-python) but due to some recent updates with Alpine they are'nt working. 

There are two ways to go about building uamqp from source, so that it can be used

### Build wheel using cibuildwheel
1. `git clonehttps://github.com/Azure/azure-uamqp-python.git`
2.  open `pyproject.toml` and make the following changes
     Under `[tool.cibuildwheel]`
     Change `skip = ["*-musllinux*", "pp*"]` to `skip = ["manylinux*","pp*"]`
     Add `build = "cp39-musllinux_x86_64"` right below the above
3. `pip install dev_requirements.txt`
4. Docker is running or Docker Desktop is running (if on Windows )
5. `cibuildwheel --platform linux`

cp39-musllinux_x86_64 finished as the final output that can be installed on alpine

### Build using source
I made a Docker file with the following:

```docker
FROM python:3.9-alpine

RUN apk add --update python3 py-pip python3-dev cmake gcc g++ openssl-dev build-base git curl perl-dev linux-headers bash
RUN git clone https://github.com/Azure/azure-uamqp-python.git
WORKDIR azure-uamqp-python
RUN bash utils/install_openssl.sh
ENV OPENSSL_ROOT_DIR="/opt/pyca/cryptography/openssl"
ENV LIBRARY_PATH="/opt/pyca/cryptography/openssl/lib"
ENV CPATH="/opt/pyca/cryptography/openssl/include"
RUN pip3 install -r dev_requirements.txt
RUN python3 setup.py build_ext --inplace
RUN pip3 install uamqp
RUN pip3 install azure-servicebus
```

**Comment by Sakshi-Behl** [comment]
Hi @kashifkhan ,
I have been using the above docker solution given by you since some time now.
it used to work fine, but recently I have started seeing below exception for this. could you check if there is something recently added in the repo causing this issue.

creating build/lib.linux-x86_64-3.8
gcc -shared -L/usr/local/lib -o build/lib.linux-x86_64-3.8/cmake_uam***p.cpython-38-x86_64-linux-gnu.so
gcc: fatal error: no input fil***
compilation terminated.
/usr/local/lib/python3.8/site-packag***/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /opt/app/azure-uam***p-python/uam***p/c_uam***p.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
error: command 'gcc' failed with exit status 1
The command '/bin/sh -c python3 setup.py build_ext --inplace' returned a non-zero code: 1
##[error]The command '/bin/sh -c python3 setup.py build_ext --inplace' returned a non-zero code: 1
##[error]The proc***s '/usr/bin/docker' failed with exit code 1
