### ISSUE TITLE
941390684cf0d44cda50dc651764951fe4ba40bf

### ISSUE THREAD

**Issue by Spivasart** [Azure/azure-sdk-for-python#27908]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kristapratico** [comment]
@Spivasart The issue template must be filled out so we can assist you. I'm going to close this issue, but feel free to open a new issue with the necessary information.
