### ISSUE TITLE
[Perf] RandomStream is not threadsafe

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-python#27941]
When ending a parallel sync upload test, an `AuthenticationFailed` error is raised:

```
~/python/sdk/storage/azure-storage-blob$ perfstress UploadTest --size 1048756 --sync --warmup 0 --duration 3 --parallel 2

=== Test ===
Current         Total           Average
30              30              30.57
31              61              30.89
30              91              30.62
Exception: Server failed to authenticate the request.
Make sure the value of Authorization header is formed correctly including the signature.
ErrorCode:AuthenticationFailed
authenticationerrordetail:The MAC signature found in the HTTP request 'REDACTED' is not the same as any computed signature.
Server used following string to sign:
```

I have been able to repro under the following conditions:

* Client
  * Azure VM, size D4ds_v5
  * WSL on Windows dev machine
* OS: Ubuntu 20.04
* Python Versions: 3.7 and 3.11
* Blob Size: >= 1048756
* Parallel: >= 2
* Sync/Async: Sync

It does not repro if any of the following are true:

* OS: Windows 10 or Windows Server 2019
* Blob Size: 10240
* Parallel: 1
* Sync/Async: Async

It repros in our nightly perf runs:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2051826&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=49e32a0b-4245-531b-0723-9d45113ffbd3&l=5530

I was not able to see the failed request in the service diagnostic logs.  It's possible the service diagnostic logs do not include requests that failed authentication.

Capturing HTTP traffic in a tool like Fidder or WireShark might be helpful, though this is a little more difficult since it doesn't repro on Windows.

We suspect the issue might be related to the threading code in the perf framework, where the first thread to complete causes other threads to abort, which leads to this error.

https://github.com/Azure/azure-sdk-for-python/blob/1a39de24a23423df4766e3e87302c480865744b5/tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_runner.py#L191-L194

**Comment by annatisch** [comment]
It seems this may not be caused by exiting the `ThreadPoolExecutor` context prematurely - I restructured this code using the following structure across sync and async:
```python
if args.sync:
    with ThreadPoolExecutor(max_workers=args.parallel) as ex:
        tasks = [ex.submit(test.run_all_sync, duration) for test in tests]
        wait(tasks, return_when=ALL_COMPLETED)
else:
    tasks = [asyncio.create_task(test.run_all_async(duration)) for test in tests]
    await asyncio.wait(tasks, return_when=asyncio.ALL_COMPLETED)
for task in tasks:
    task.result()
```
And it seems like the authentication errors are still present.

**Comment by pvaneck** [comment]
An observation regarding that auth error: From the error message we see:

```
Server used following string to sign: 'PUT
[08:40:30.755] [STDERR]
[08:40:30.755] [STDERR]
[08:40:30.755] [STDERR] 1048576
[08:40:30.755] [STDERR]
[08:40:30.755] [STDERR] application/octet-stream
[08:40:30.755] [STDERR]
[08:40:30.755] [STDERR]

...
```

The 1048576 is suspect since my content length when testing is actually 10485760.  I'm thinking something might be up with the RandomStream since the server seems to be pulling that number based on what we have [here](https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-devtools/src/azure_devtools/perfstress_tests/_random_stream.py#L8).

In UploadTest, specifying: `self.upload_stream = RandomStream(self.args.size, initial_buffer_length=self.args.size)`
seems to also get rid of the error.

Seems the error arises when the size is greater than the initial_buffer_length.

**Comment by annatisch** [comment]
Confirmed that this is a race condition in the implementation of the RandomStream in the perf framework. I will add a quick lock as a short-term fix and we can do a more significant refactor of this class longer term.

**Comment by mikeharder** [comment]
The race condition is in method `get_random_bytes()`:

https://github.com/Azure/azure-sdk-for-python/blob/a585e63970a7c83b1709785e713d37e02699a411/tools/azure-devtools/src/azure_devtools/perfstress_tests/_random_stream.py#L12-L16

If two threads call this concurrently, with the same `buffer_length`, and `buffer_length > _BYTE_BUFFER[0]`:

1. Thread A reaches the end of line 14, updating `_BYTE_BUFFER[0]`, then is interrupted.
2. Thread B sees that `buffer_length == _BYTE_BUFFER[0]`, so skips the `if`, and returns `_BYTE_BUFFER[1][:buffer_length]`.

The problem is that `_BYTE_BUFFER[1]` has not been updated yet, so the returned buffer is smaller than requested, which violates the method contract and leads to the downstream bug reported above.

A lock should work as a short-term fix, but in the longer term we should be able to implement `RandomStream` without locks and without changing the size of the underlying buffer.
