### ISSUE TITLE
AzureCliCredential does not work as intended when using a Chinese version of Windows

### ISSUE THREAD

**Issue by tboerstad** [Azure/azure-sdk-for-python#27965]
- **Azure Identity**: 
- **1.12**: 
- **Windows 11**:
- **Python 3.7**: 

**Describe the bug**
`AzureCliCredential` returns an `ClientAuthenticationError` when `azure cli` is not installed, on a Chinese windows installation.

The correct error to return is a `CredentialUnavailableError`, which is returned if using English language version of Windows. Returning the wrong error, makes it not possible to use `AzureCliCredential` in a `ChainedTokenCredential` chain. 

I belive this bug is because AzureCliCredential is hardcoded to look for the English text:
[ex.stderr.startswith("'az' is not recognized")](https://github.com/Azure/azure-sdk-for-python/blob/3fa3e1c84810bedde50a7e6397bcb6797a3b6c84/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L152)

**To Reproduce**
1. Use a Chinese version of Windows 11.
2. Attempt to use AzureCliCredential, without having `azure cli` installed

**Expected behavior**
I expect the `CredentialUnavailableError` to be returned, not `ClientAuthenticationError`.

**Screenshots**

![image](https://user-images.githubusercontent.com/4872288/207887919-15d972bf-386b-4939-baef-3d58591821de.png)

**Comment by kristapratico** [comment]
Hi @tboerstad thanks for your issue, we'll take a look and get back to you as soon as possible.

**Comment by lmazuel** [comment]
@pvaneck @xiangyan99 This is a real issue, we must not assume the OS is in English to work properly. This is an example what you would get on a French machine:

```
>az
'az' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

Let's make sure we're not coupling our implementation with a given OS configuration.

**Comment by pvaneck** [comment]
@tboerstad Thanks for the issue!

@lmazuel Yea, definitely an oversight in implementation. I'll look into resolving this.
