### ISSUE TITLE
Incorrect variable description

### ISSUE THREAD

**Issue by KevinBrooke** [Azure/azure-sdk-for-python#27977]
recovery_point_id = ID of the backup copy to be recovered.
This is incorrect. It should actually be the recover point name (just the number).
Annoyingly ID in Azure land is generally the resource ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9f9861-76d1-8a07-9bd1-ae9054e85b0e
* Version Independent ID: 6f06b6a2-9b08-98fd-c773-eaee19d3665e
* Content: [azure.mgmt.recoveryservicesbackup.activestamp.models.IaasVMRestoreRequest class](https://learn.microsoft.com/en-us/python/api/azure-mgmt-recoveryservicesbackup/azure.mgmt.recoveryservicesbackup.activestamp.models.iaasvmrestorerequest?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-recoveryservicesbackup/azure.mgmt.recoveryservicesbackup.activestamp.models.IaasVMRestoreRequest.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-recoveryservicesbackup/azure.mgmt.recoveryservicesbackup.activestamp.models.IaasVMRestoreRequest.yml)
* Service: **site-recovery**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
Hi @KevinBrooke thanks for your issue. @msyyc does the swagger need to be updated to fix this documentation?

**Comment by navba-MSFT** [comment]
@KevinBrooke Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@KevinBrooke The above PR has been filed and it is currently under review.
