### ISSUE TITLE
Eventhub Opentelemetry Trace exception: "'MessageProperties' object has no attribute 'setdefault'"

### ISSUE THREAD

**Issue by erewok** [Azure/azure-sdk-for-python#27986]
- **Package Name**: `azure-eventhub`
- **Package Version**: `5.10.1`
- **Operating System**: Linux-Debian (docker container)
- **Python Version**:  3.11.1

**Describe the bug**
Today in an experiment with adding tracing spans to our `EventhubProducerClient` calls, I followed a [helpful example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventhubs.py) provided by the package `azure-core-tracing-opentelemetry`.

After some tracing spans were produced, I noticed an exception in the logs (but these did not prevent events from being published):

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/opentelemetry/trace/__init__.py", line 573, in use_span
    yield span
  File "/usr/local/lib/python3.11/site-packages/azure/eventhub/_utils.py", line 181, in trace_message
    event.properties.setdefault(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MessageProperties' object has no attribute 'setdefault'
```

In the `_utils.py` module, there's a [function called `trace_message`](https://github.com/Azure/azure-sdk-for-python/blob/2a44691fc9a37a7c0920bca2678eb921b5baa378/sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py#L176) with a few lines like this:

```python
                if not event.properties:
                    event.properties = dict()
                event.properties.setdefault(
                    b"Diagnostic-Id", message_span.get_trace_parent().encode("ascii")
                )
```

Here, if `event.properties` is truthy, then it will _not_ be a Python `dict` (as in my case), and instead it's an instance of [`MessageProperties` from the `uamqp` library](https://github.com/Azure/azure-uamqp-python/blob/5f3b26fb9cd398c71a05f602f37b388f882384ed/uamqp/message.py#L824), which has no `setdefault` function. 

To fix it, we could indent `setdefault` under the `if not event.properties` and add an `else` that sets the property differently for `MessageProperties`. 

I would be happy to submit a PR for this change if it is useful.

**To Reproduce**
1. Follow the [example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventhubs.py) for instrumenting an `EventhubProducerClient`
2. Produce some events.
3. Load tracing span waterfall graph matching this trace id.
4. See exception screenshot below

**Screenshots**

![Screenshot 2022-12-16 at 12 04 03 PM](https://user-images.githubusercontent.com/4587833/208179705-dfb8c771-1de2-4cac-b582-e22da5a0c449.png)

**Expected behavior**
No exceptions when instrumenting Eventhub calls with opentelemetry tracing spans.

**Comment by kristapratico** [comment]
Hi @erewok thanks for the detailed issue, we'll take a look and get back to you as soon as possible.

**Comment by swathipil** [comment]
Hi @erewok - Thanks for the investigation! It was very helpful in helping reproduce/track down the bug. We've made a few big changes recently to the SDK, so the fix will be a little bit more complex. However, we're working on getting the fix out now.

**Comment by erewok** [comment]
@swathipil, great! Glad to hear it and glad that this issue was useful. Thanks for following up.

**Comment by swathipil** [comment]
Hi @erewok - The fix for this bug has been merged and will be included in the upcoming release: `azure-eventhub` 5.11.0.

If you'd like to test the fix in the meantime, you can build and install the wheel by:
1. Cloning the azure-sdk-for-python repo.
2. Running `pip install wheel`
3. 
```
> cd azure-sdk-for-python/sdk/eventhub/azure-eventhub
azure-sdk-for-python/sdk/eventhub/azure-eventhub> python .\setup.py bdist_wheel -d <dest_folder>
```

Thanks!

**Comment by erewok** [comment]
Thanks for the update, @swathipil! I will wait until the latest version is up on PyPi. I appreciate the help.
