### ISSUE TITLE
Nested symlink is not resolved correctly

### ISSUE THREAD

**Issue by moajo** [Azure/azure-sdk-for-python#27980]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.2.0
- **Operating System**: Ubuntu 22.04.1 LTS
- **Python Version**: Python 3.10.5

**Describe the bug**
Executing the `az ml job create` in Azure ML CLI will result in error if directory has nested symlink in relative path:
```
Error with code: [Errno 2] No such file or directory: 'python'
```
This bug is problematic when using a `.venv` virtual environment.
(nested symlink will be created like: `.venv/bin/python3` -> `.venv/bin/python` -> (original executable path))

**To Reproduce**
Prepare a config file for azure as follows
```
# config.yml
$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: /home/moajo/code/test1
command: python main.py
compute: azureml:example
environment: azureml:example@latest
```
and prepare directory include nested symlink
```
echo 'print("hello")' > main.py
mkdir subdir
cd subdir
ln -s ../main.py symlink1.py
ln -s symlink1.py symlink2.py
cd ../
```

Finally, directory is prepared like this
```
.
|-- conf.yml
|-- main.py
`-- subdir
    |-- symlink1.py -> ../main.py
    `-- symlink2.py -> symlink1.py
```

Executing `az ml job create --file conf.yml` in this directory will result in error

```
Met error <class 'FileNotFoundError'>:[Errno 2] No such file or directory: '/home/moajo/code/test1/python'
Please check log by running the command with '--debug' for more details.
```

**Expected behavior**
No errors.

**Additional context**
The implementation causing this error is the `def get_directory_size` in `azure/ai/ml/_utils/_asset_utils.py`.

**Comment by kristapratico** [comment]
@moajo thanks for your detailed issue and for opening a PR. @azureml-github @luigiw can you take a look?
