### ISSUE TITLE
Configure IdleTimeoutInMinutes for a ConfigurationSetInputEndpoint

### ISSUE THREAD

**Issue by carmstrong** [Azure/azure-sdk-for-python#280]
We're trying to accomplish: http://azure.microsoft.com/blog/2014/08/14/new-configurable-idle-timeout-for-azure-load-balancer/

It looks like we can configure `idle_timeout_in_minutes` when creating a [PublicIP](https://github.com/Azure/azure-sdk-for-python/blob/dc6d2c5ff4155e18e17cc5285d4818e3e0b3a205/azure/servicemanagement/__init__.py#L1015), but it doesn't appear we can set it on an [Endpoint](https://github.com/Azure/azure-sdk-for-python/blob/dc6d2c5ff4155e18e17cc5285d4818e3e0b3a205/azure/servicemanagement/__init__.py#L1044-L1075) using the SDK, even though it looks like it's possible based on the above linked article.

Are we missing something here, or does the SDK not yet support this?

Thanks!

**Comment by huguesv** [comment]
Not supported yet. You could easily try this, and if it works, we'd be happy to take your pull request.

Add an idle_timeout_in_minutes field + constructor parameter defaulting to 4:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure/servicemanagement/__init__.py#L1075

Add serialization of the field:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure/servicemanagement/__init__.py#L2270

I think that's all you would need.

**Comment by timfpark** [comment]
Hi @huguesv - I'll make a PR here. Can you clarify how idle_timeout_in_minutes should be serialized in the XML - should it be IdleTimeoutInMinutes?

**Comment by timfpark** [comment]
Nevermind - I see it in this doc:

https://msdn.microsoft.com/en-us/library/azure/dn469417.aspx

I have what I need, I'll make a PR.

**Comment by timfpark** [comment]
PR: https://github.com/Azure/azure-sdk-for-python/pull/281
