### ISSUE TITLE
SharedTokenCacheCredential fails on macOS

### ISSUE THREAD

**Issue by tboerstad** [Azure/azure-sdk-for-python#28003]
- **Package Name**: Azure.Identity
- **Package Version**: 1.12
- **Operating System**: macOS Monterey
- **Python Version**: Python 3.11

**Describe the bug**
The following script will work the first time I run it. It will open a browser, and authenticate normally. 
The second time I run it, it will return with `ChainedTokenCredential failed to retrieve a token from the included credentials.`

```python
from azure.identity import (
    InteractiveBrowserCredential,
    TokenCachePersistenceOptions,
    SharedTokenCacheCredential,
    ChainedTokenCredential,
)

options = TokenCachePersistenceOptions(name="my-cache")
cred = ChainedTokenCredential(
    SharedTokenCacheCredential(cache_persistence_options=options),
    InteractiveBrowserCredential(cache_persistence_options=options),
)

token = cred.get_token("https://graph.microsoft.com/.default")
print(token)
```

I've done some digging, and [this is the underlying exception is triggered](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/ee452ea1560e02440b2b11e9bdbb42d9bad3b719/msal_extensions/persistence.py#L278) with exit status `-25293`. This means, iiic, [errKCAuthFailed = -25293](https://opensource.apple.com/source/CarbonHeaders/CarbonHeaders-18.1/MacErrors.h)
 

**To Reproduce**
1. Run the provided script twice on macOS. 

**Expected behavior**
The second time I run the script, I expect a token to be returned from the cache. 
Meaning no browser pop-up

**Screenshots**

**Additional context**

**Comment by pvaneck** [comment]
Thanks for the feedback. Unfortunately I do not have a macbook to try recreating, but seems like this may be an issue with macOS Keychain configuration.

If possible, can you try an unencrypted cache to verify: `TokenCachePersistenceOptions(name="my-cache", allow_unencrypted_storage=True)`?

I'm not too familiar with Keychain, but I did find this from someone else hitting the same exit code you are seeing: https://discussions.apple.com/thread/2280636. Not sure if the provided workaround would also work for you.

**Comment by tboerstad** [comment]
Hi Paul, thanks for the response. 

I have tested with `TokenCachePersistenceOptions(name="my-cache", allow_unencrypted_storage=True)`, and the same exception is raised at the same place in the code.

I am able to use the KeyChain viewer as shown in [step one of this guide](https://support.apple.com/en-gb/guide/keychain-access/kyca1085/mac) from Apple

**Comment by tboerstad** [comment]
@pvaneck I've investigated a bit further,[ it looks like Azure Identity/MSALExtensions](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/ee452ea1560e02440b2b11e9bdbb42d9bad3b719/msal_extensions/osx.py#L164) is calling this API:
[SecKeychainFindGenericPassword](https://developer.apple.com/documentation/security/1397301-seckeychainfindgenericpassword?language=obj)

As you can see from the link, this API has been deprecated.
 Perhaps it's no longer working as intended?

The workaround doesn't work for me. I also have had zero issues with Key Chain on my Mac, which I use daily

**Comment by pvaneck** [comment]
@rayluo Do you have any insight into how KeyChain is used in MSAL for an encrypted cache? Or if there is some special configuration that is needed on MacOS.

Also, based on what I see in the [identity code](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_persistent_cache.py#L82), only Linux supports unencrypted storage and not Mac/Windows. Not sure if this is intentional/oversight, but it's probably something that should be fixed.

**Comment by xiangyan99** [comment]
@tboerstad I ran your script on my Mac but I couldn't repro the issue.

There was a pop-up window and asked me to log in when I ran it the first time.

On second time, it printed out the token w/o my logging in.

I also tried 

cred = ChainedTokenCredential(
    SharedTokenCacheCredential(cache_persistence_options=options),
    # InteractiveBrowserCredential(cache_persistence_options=options),
)

on third time to make sure it read the token from cache and it still worked without any errors.

Could you provide more information how to make the repro?

**Comment by tboerstad** [comment]
Thanks you for testing on your Mac, @xiangyan99. 
I assumed that this was a general issue on Mac, but your testing proved my assumption wrong. 

I opened "Keychain Access" and manually deleted `Microsoft.Developer.IdentityService`. 
After that, I get the same correct results as you do. 

Since this works now, and I have a workaround (manually delete the entry) should it arise again, 
I will close the issue. Thanks again for your help!
