### ISSUE TITLE
Package Import Issue - Azure AI Text Analytics

### ISSUE THREAD

**Issue by markremmey** [Azure/azure-sdk-for-python#28002]
- **Package Name**: azure.ai.textanalytics
- **Package Version**: 5.3.0b1
- **Operating System**: Linux
- **Python Version**: 3.11.1

**Describe the bug**
I have been following the steps in the instructions listed at https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/textanalytics/azure-ai-textanalytics to import Azure Text Analytics but I'm getting an Import error "ImportError: cannot import name 'TokenCredential' from 'azure.core.credentials' (/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/credentials.py)". 

It appears that there is some kind of a dependency issue.

**To Reproduce**
Interaction with the service using the client library begins with a [client](#textanalyticsclient "TextAnalyticsClient").
To create a client object, you will need the Cognitive Services or Language service `endpoint` to
your resource and a `credential` that allows you access:

```python
from azure.core.credentials import AzureKeyCredential
from azure.ai.textanalytics import TextAnalyticsClient

credential = AzureKeyCredential("<api_key>")
text_analytics_client = TextAnalyticsClient(endpoint="https://<resource-name>.cognitiveservices.azure.com/", credential=credential)
```

**Expected behavior**
The code should execute and import the required text analytics package

**Screenshots**
![image](https://user-images.githubusercontent.com/53156818/208511754-13da5ee3-01e8-43d9-ae89-6cc58ce609e2.png)

**Additional context**

**Comment by kristapratico** [comment]
Hi @markremmey thanks for your issue. It looks like you're using a conda env. Could you please share the output of `conda list`? `azure-ai-textanalytics` requires `azure-core` >= 1.24.0. Also curious - in your issue you say you're using Python 3.11, but it looks like it's using 3.10 in your stack trace - is a different env meant to be used?

**Comment by markremmey** [comment]
Hi Krista - it looks like I am on 1.26.1 for Azure Core. And yes you are correct I am on Python 3.10 as you mentioned.

![image](https://user-images.githubusercontent.com/53156818/210444079-1f002679-b356-47b9-badb-1fca94fef8fc.png)

**Comment by kristapratico** [comment]
@markremmey thanks for sharing. I ran `pip install azure-ai-textanalytics==5.3.0b1` in a conda env and tried this locally in a notebook, but I'm not able to reproduce the error:

![image](https://user-images.githubusercontent.com/31998003/210451716-e42d9c7d-9d94-4972-9253-4fc9afff29a0.png)

Output of my `conda list`:

![image](https://user-images.githubusercontent.com/31998003/210451945-aa971af4-e7d3-4b2b-b9db-5e7c93e59869.png)


My best guess is that there is some venv issue related to how pip was used in a conda environment. There is a good post here which explains how this can lead to broken dependency issues: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

My suggestion is to recreate the conda env using the pip recommendations from the conda docs (https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment) and see if that resolves the dependency issue you're seeing. Let me know if that helps, happy to further troubleshoot with you.

**Comment by markremmey** [comment]
Hi Krista - it is working for me now. Thank you for your help.
