### ISSUE TITLE
NameError: name 'client' is not defined

### ISSUE THREAD

**Issue by rogerbrownmoj** [Azure/azure-sdk-for-python#28009]
- **azure-maps-route**: 
- **azure-maps-route==1.0.0b1**: 
- **macOS Monterey 12.6.2**:
- **Python Version 3.9**: 

**Describe the bug**
Having completed the steps up to this point when I run route_directions_result = client.get_route_directions(route_points=[LatLon(47.60323, -122.33028), LatLon(53.2, -106)]); I get the error in the title. I have amended the key to my Azure key. I am attempting to work the example before using my own data but it is just not working

**To Reproduce**
1. Follow the steps on https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/maps/azure-maps-route

**Expected behavior**
A clear and concise description of what you expected to happen. I expected to be able to access data from azure maps route

**Screenshots**

**Additional context**

**Comment by pvaneck** [comment]
Hey, @rogerbrownmoj. What variable name did you use when you instantiated `MapsRouteClient`? This may just be case of using `route_client.get_route_directions` instead of `client.get_route_directions` as it seems like `route_client` is used in the "Authenticate" section of the README.

**Comment by rogerbrownmoj** [comment]
Hi @pvaneck I have tried that as well but I initially got an error message relating to LatLon so I installed the package but I get this message now TypeError: 'LatLon' object is not subscriptable
pip install latlon3
from latlon import LatLon
import latlon

To test that LatLon is working I ran just route_points=[LatLon(47.60323, -122.33028), LatLon(53.2, -106)] and this worked
but when I run the full line of code 
route_directions_result = route_client.get_route_directions(route_points=[LatLon(47.60323, -122.33028), LatLon(53.2, -106)])
I'm getting the TypeError message

**Comment by pvaneck** [comment]
@rogerbrownmoj, the LatLon that is being used is a class inside the azure-maps-route package and not from latlon3, but I can understand the confusion. Seems LatLon shouldn't even be needed at all. Try out this sample: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-route/samples/sample_get_route_directions.py, as it appears to be a complete working example.

@alextts627, I think the README should be updated to not include the explicit LatLon usage in the exampleand also use consistent client variable names.

**Comment by navba-MSFT** [comment]
@pvaneck I have created the above PR to address this. @alextts627 Could you please review the same ?
