### ISSUE TITLE
[Mgmt] Update README.md template

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#28017]
we need to make https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-sdk-tools/packaging_tools/templates/packaging_files/README.md more friendly for users.
reference:
https://github.com/Azure/azure-sdk-for-js/blob/%40azure%2Farm-cdn_7.0.0/sdk/cdn/arm-cdn/README.md
https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager_2.21.0/sdk/resourcemanager/azure-resourcemanager/README.md
https://github.com/Azure/azure-sdk-for-go/blob/sdk%2Fresourcemanager%2Fcdn%2Farmcdn%2Fv1.0.0/sdk/resourcemanager/cdn/armcdn/README.md

e-mail: RE: Python SDK "Getting Started"

**Comment by mawarren642** [comment]
I've started trying to use this in the last 48 hours and am finding the documentation examples do not work at all for StorageManagementClient. If you can please prioritize this, our 1P service would very much like to start using this to regenerate storage keys.
