### ISSUE TITLE
getting a notification when a training job is done that was started natively inside an Azure Compute VM

### ISSUE THREAD

**Issue by monajalal** [Azure/azure-sdk-for-python#28023]
I have created a VM using the Azure Compute menu. I am running a Python training code that is long running via tmux directly inside the VM by SSH -i -X into it. However, since these VMs are expensive ($4 an hour), I would like the node to:

1-  send me an email notification when the job is done
or
1-  send me an email notification when the job is done
2-  stop (not delete) the VM so I won't be charged for it.

I have turned on all the notifications as you see below:
![Screenshot from 2022-12-21 12-03-04](https://user-images.githubusercontent.com/1892917/208964230-7ffbc52e-5087-4b53-b91a-06b2a647b9d9.png)

However, I have not been getting any email/text notifications for any of my Python jobs that have been finished. I only get email notification when an mlflow related script was run like below.

![Screenshot from 2022-12-21 12-02-23](https://user-images.githubusercontent.com/1892917/208964417-b011667b-9a4e-42a7-8c52-005df2a3914a.png)

Thanks a lot for any guidance.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mccoyp** [comment]
Hi @monajalal, thank you for opening an issue! Is there a particular package from the Azure SDK that you're using in your workflow? If not, you may get a reliable response by asking a question at a VM-specific forum like [this Q&A page](https://learn.microsoft.com/answers/topics/azure-virtual-machines.html) if you haven't already.

I'll tag the ML team either way in case someone would know how to help, but I would recommend opening an issue at the forum I linked. @luigiw @azureml-github

**Comment by luigiw** [comment]
Hello @monajalal. Have you tried to use compute clusters in AzureML? AzureML compute clusters automatically scale up/down based on your training job requirements. And you can subscribe to events of when the training finishes.

Here're some references.

AzureML compute cluster, https://learn.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-compute-cluster?tabs=python

Subscribe to when an AzureML training job finishes, https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-event-grid

**Comment by monajalal** [comment]
@luigiw for example, my job was killed since VM ran out of space and then the VM didn't exit even though I have enabled "auto shutdown" in "Preview Features" in Azure Compute.

Also, I cannot stop the VM as it is stated "Unusable". I was able to shutdown the VM by ssh-ing to it but am I billed for the duration the VM was Unusable? Also, how do I bring back the VM to usable?

<img width="643" alt="MicrosoftTeams-image (12)" src="https://user-images.githubusercontent.com/1892917/210384176-77f3839a-692c-4923-89ef-7d24518180c2.png">

![Screenshot from 2023-01-03 10-07-18](https://user-images.githubusercontent.com/1892917/210384301-3cc1dc19-2aab-4c6d-91ac-0f3d6d937917.png)

**Comment by luigiw** [comment]
@monajalal to clarify, I was suggesting you to use Azure Machine Learning service and the compute feature comes with AzureML. If your main use case for the VM is ML training, you should definitely checkout features provided by AzureML compute. https://learn.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-compute-cluster?tabs=python

**Comment by monajalal** [comment]
@xiangyan99 for this special case, I decide to run all my jobs as a pipeline using a compute cluster rather than a compute instance node. Since, I am running them as job, natively I get email when the job finishes or fails. However, it still remains true that a stand-alone training job (python train.py) inside azure compute instance would not yield any email upon successful finish or failure.
