### ISSUE TITLE
route_client.get_route_directions - TypeError: 'LatLon' object is not subscriptable

### ISSUE THREAD

**Issue by lucypitches** [Azure/azure-sdk-for-python#28020]
- **Package Name**: azure-maps-route
- **Package Version**: 1.0.0b1
- **Operating System**: Windows
- **Python Version**: 3.9

**Describe the bug**

**To Reproduce**
1. from azure.maps.route import MapsRouteClient

route_directions_result = route_client.get_route_directions(route_points=[LatLon(47.60323, -122.33028), LatLon(53.2, -106)])

**Expected behavior**
function output instead i get the error TypeError: 'LatLon' object is not subscriptable

**Screenshots**

**Additional context**

**Comment by pvaneck** [comment]
Thanks for the feedback. This is a similar predicament as another user. Let me know if my comment here helps you: https://github.com/Azure/azure-sdk-for-python/issues/28009#issuecomment-1361997503
