### ISSUE TITLE
ImportError: cannot import name 'TokenCredential' from 'azure.core.credentials

### ISSUE THREAD

**Issue by G3gayathri** [Azure/azure-sdk-for-python#28057]
Hi, We were trying create a python app using ms-graph SDK for python and got the following error:

    from .azure_identity_access_token_provider import AzureIdentityAccessTokenProvider
  File "C:\Users\Gayathri Prasad\anaconda3\envs\msgraph2\lib\site-packages\kiota_authentication_azure\azure_identity_access_token_provider.py", line 5, in <module>
    from azure.core.credentials import TokenCredential
ImportError: cannot import name 'TokenCredential' from 'azure.core.credentials' (C:\Users/Gayathri Prasad/AppData/Roaming/Python/Python310/site-packages\azure\core\credentials.py)

**Comment by SaurabhSharma-MSFT** [comment]
@G3gayathri Are you referring to any sample for this ? Can you please share your code snippet where you are getting this error?

**Comment by G3gayathri** [comment]
I was trying to follow the tutorial provided here https://learn.microsoft.com/en-us/graph/tutorials/python?tabs=aad

**Comment by SaurabhSharma-MSFT** [comment]
@G3gayathri I have followed the article and do not see any issues getting it run with Graph SDK package.  
![image](https://user-images.githubusercontent.com/38112130/210340479-492be9a9-c001-4554-b5ef-ca00951a2463.png)
Can you please check if you have installed `pip install azure-identity` and `pip install msgraph-sdk` before executing the main.py file.

**Comment by SaurabhSharma-MSFT** [comment]
@G3gayathri Please let us know if you have any questions.

**Comment by SaurabhSharma-MSFT** [comment]
@G3gayathri We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by malikaasen** [comment]
I'm having the same issue when importing defaultcredentials from the azure-ai-ml python library in an endpoint on machine learning studio. Any idea on why this happens? Haven't found any mention of the problem other than this issue...

**Comment by hshujuan** [comment]
@SaurabhSharma-MSFT I'm having the same issue when importing defaultcredentials from the azure-ai-ml python library in an endpoint on machine learning studio. Any suggestions ?

**Comment by malikaasen** [comment]
@hshujuan Refer to this, fixed the issue for me(should also be in current release) https://github.com/Azure/azure-sdk-for-python/issues/28369
