### ISSUE TITLE
[ACR] Get last pull for a tag

### ISSUE THREAD

**Issue by HW-Jeremy** [Azure/azure-sdk-for-python#28091]
we have a purge script that removes tags from our repositories following patterns. We use this SDK to do this.

It would be interesting to have the date of the last pull for a tag.

**Comment by mccoyp** [comment]
Hi @HW-Jeremy, thank you for opening an issue! This sounds like a feature request; I'll tag it as such so we can discuss the proposal. If this functionality is available today, someone from our team can let you know.

**Comment by YalinLi0312** [comment]
Hi @HW-Jeremy , you can get the date of the last pull for a tag from `ArtifactTagProperties.last_updated_on`. 
Here's the sample code you can try:
```python
with ContainerRegistryClient(endpoint, credential) as client:
    result = client.list_tag_properties("library/hello-world")
    for tag_props in result:
        print(tag_props.last_updated_on)
```
