### ISSUE TITLE
Migrate docs build from sphinx `3.5.4` --> `6.1.3`

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#28137]
We should make progress on this, but hold off on merging until [this issue](https://dev.azure.com/ceapex/Engineering/_workitems/edit/740808) is getting closer to resolution. 

~~We don't want to generate documentation that is incompatible with our docs.microsoft accidentally.~~

That stuff is getting closer to rollout now. We need to bump the sphinx version everywhere it's pinned, then debug the inevitable crashes that result.

Progress on this task is visible [here.](https://github.com/Azure/azure-sdk-for-python/tree/feature/update-sphinx-version)

**Comment by l0lawrence** [comment]
Also related -- after this bump is completed : #30956
