### ISSUE TITLE
Log Analytics Table List by Workspace results in NoRegisteredProviderFound

### ISSUE THREAD

**Issue by hinchliff** [Azure/azure-sdk-for-python#28161]
- **Package Name**: azure-mgmt-loganalytics
- **Package Version**: 12.0.0
- **Operating System**: Ubuntu (WSL) 
- **Python Version**: 3.8.10

**Describe the bug**
When trying to list the available Log Analytics tables, a NoRegisteredProviderFound exception is thrown.

The following message is printed:
> Message: No registered resource provider found for location 'centralus' and API version '2021-06-01' for type 'workspaces/tables'. The supported api-versions are '2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2021-12-01-preview, 2022-10-01'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiaeast, australiacentral, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacentral2, uaecentral, uaenorth, japanwest, brazilsoutheast, norwayeast, norwaywest, francesouth, southindia, koreasouth, jioindiacentral, jioindiawest, qatarcentral, canadaeast, westus3, swedencentral'.

The Log Analytics client does not seem to support [multi-api](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/mgmt/multiapi.md#overview-of-a-multi-api-client).  Passing in an `api_version` did not change the outcome:
```python
log_analytics_client = LogAnalyticsManagementClient(credential, subscription_id, api_version="2022-10-01")
```

**To Reproduce**
1. create a LogAnalyticsManagementClient
2. try to list tables in a workspace, e.g. `log_analytics_client.tables.list_by_workspace(resource_group_name, workspace_name)`

**Expected behavior**
A list of Log Analytics Tables should be available. 

**Screenshots**
Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.8/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "venv/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "venv/lib/python3.8/site-packages/azure/mgmt/loganalytics/operations/_tables_operations.py", line 115, in get_next
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'centralus' and API version '2021-06-01' for type 'workspaces/tables'. The supported api-versions are '2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2021-12-01-preview, 2022-10-01'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiaeast, australiacentral, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacentral2, uaecentral, uaenorth, japanwest, brazilsoutheast, norwayeast, norwaywest, francesouth, southindia, koreasouth, jioindiacentral, jioindiawest, qatarcentral, canadaeast, westus3, swedencentral'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'centralus' and API version '2021-06-01' for type 'workspaces/tables'. The supported api-versions are '2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2021-12-01-preview, 2022-10-01'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiaeast, australiacentral, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacentral2, uaecentral, uaenorth, japanwest, brazilsoutheast, norwayeast, norwaywest, francesouth, southindia, koreasouth, jioindiacentral, jioindiawest, qatarcentral, canadaeast, westus3, swedencentral'.
```

**Additional context**
This works in the AZ CLI.

**Comment by SaurabhSharma-MSFT** [comment]
@hinchliff We are looking into it and get back to you for any additional information.

**Comment by Wzb123456789** [comment]
Hi @hinchliff 

We have optimized this issue, please use the latest version to solve the problem.
https://pypi.org/project/azure-mgmt-loganalytics/13.0.0b6/

**Comment by hinchliff** [comment]
I updated to the `13.0.0b6` version of the `azure-mgmt-loganalytics` package, and I now get a different error:

> Content: Unsupported api version - 2022-10-01

Do I need to update any other packages?

partial log from pip install:
```
  Attempting uninstall: azure-mgmt-loganalytics
    Found existing installation: azure-mgmt-loganalytics 12.0.0
    Uninstalling azure-mgmt-loganalytics-12.0.0:
      Successfully uninstalled azure-mgmt-loganalytics-12.0.0

Successfully installed azure-mgmt-loganalytics-13.0.0b6
```

Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.8/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "venv/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "venv/lib/python3.8/site-packages/azure/mgmt/loganalytics/operations/_tables_operations.py", line 426, in get_next
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Invalid argument'
Content: Unsupported api version - 2022-10-01
```

**Comment by Wzb123456789** [comment]
You can try to remove the version specification.
```python
log_analytics_client = LogAnalyticsManagementClient(credentials, subscription)
```

**Comment by hinchliff** [comment]
i seem to get inconsistent responses for this api method.  occassionally it will work, but more often i get the (most recent) exception above (`Content: Unsupported api version - 2022-10-01`).

I mentioned testing with the API version in the initial post, because I was trying to see if this client supported multi-api, but it seems that it did not and does not support it.

I see that you added some sample code, and I'm using basically the same methods you are.  I am not specifying the API version.  

```python
log_analytics_client = LogAnalyticsManagementClient(credential, subscription_id)

for item in log_analytics_client.workspaces.list():
    print(item)

# resource_group_name = "example"
# workspace_name = "example"

for item in log_analytics_client.tables.list_by_workspace(resource_group_name, workspace_name):
    print(item)
    break
```

i had thought it might be a location issue, e.g. between East-US and Central-US, but it doesn't seem to be consistent.

at least one time, i saw this code work
```python
>>> for item in log_analytics_client.workspaces.list():
...     location = item.location
...     (_, resource_group, _, resource_name) = get_fields_from_azure_id(item.id)
...     for table in log_analytics_client.tables.list_by_workspace(resource_group_name, workspace_name):
...             print(f"{location} {table.name}")
...             break
...
eastus SecurityBaselineSummary
westus2 SecurityBaselineSummary
Central US SecurityBaselineSummary
```

but not every time:
```python
>>> for item in log_analytics_client.workspaces.list():
...     location = item.location
...     (_, resource_group, _, resource_name) = get_fields_from_azure_id(item.id)
...     for table in log_analytics_client.tables.list_by_workspace(resource_group_name, workspace_name):
...             print(f"{location} {table.name}")
...             break
...
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/alan/code/chassis/chassis-api/venv/lib/python3.8/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "/home/alan/code/chassis/chassis-api/venv/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/alan/code/chassis/chassis-api/venv/lib/python3.8/site-packages/azure/mgmt/loganalytics/operations/_tables_operations.py", line 426, in get_next
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Invalid argument'
Content: Unsupported api version - 2022-10-01
```

**Comment by msyyc** [comment]
Hi @hinchliff According to your code and log, I infer that service has not supported `2022-10-01` for `list_by_workspace` in all location. If you find some location don't support it, we can help transfer to service team to let them know.
nit: I think you can print location before call list_by_workspace. If it raises exception, we can know which location doesn't work.

**Comment by hinchliff** [comment]
Well, no, it doesn't seem to be that some locations don't support that api version. It seems that the API call succeeds sometimes and fails other times.

I added some exception handling in one instance of testing, and all three regions present for this subscription all failed with the exception above.

Sometimes all three regions succeed, but more often all three regions fail.

What could be causing that?

If it will be helpful for me to reach out to a service team, i can definitely do that.

**Comment by msyyc** [comment]
You can follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to get more detailed info about request/response to/from service. Once you catch the failed log, you can create issue in https://github.com/Azure/azure-rest-api-specs/issues. From service's perspective, I think you need to provide the rest api(you can find it in the log). The more detailed info they have, the faster they can  find the root cause

**Comment by wiperpaul** [comment]
Hi, I am experiencing the same error and wanted to add that when using `AzureCliCredential()` I get no errors however when using `ManagedIdentityCredential(managed_identity_client_id)` the error occurs.

**Comment by bigg01** [comment]
Hi, I have the same problem in `switzerlandnorth`.  Is there a way to specify the API Version or can a I use a previous version or should I go back and use simple rest calls.

Regards

`
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'switzerlandnorth' and API version '2021-06-01' for type 'workspaces/tables'. The supported api-versions are '2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2021-12-01-preview, 2022-10-01'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiaeast, australiacentral, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacent
`

**Comment by SaurabhSharma-MSFT** [comment]
> You can follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to get more detailed info about request/response to/from service. Once you catch the failed log, you can create issue in https://github.com/Azure/azure-rest-api-specs/issues. From service's perspective, I think you need to provide the rest api(you can find it in the log). The more detailed info they have, the faster they can find the root cause
@hinchliff Can you please provide the details as requested above.

**Comment by hinchliff** [comment]
@SaurabhSharma-MSFT -- i think i added that in https://github.com/Azure/azure-rest-api-specs/issues/22129 ?
