### ISSUE TITLE
Honor `inactive` package classifier, skip deprecated packages by default

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#28167]
- [ ] CI test invocation should **also** now scan the classifiers. If the `inactive` classifier is set, the package should be skipped in tox environments. We don't need to actively test it.
- [ ] If a user provides the argument `BUILD_INACTIVE=true` at queue time, these inactive packages should be built regardless of inactive status.

An inactive classifier will looks like this:

- `Development Status :: 7 - Inactive`

**Comment by lmazuel** [comment]
Please play with `core` first :p

Inactive:
- azure
- azure-common
- azure-mgmt
- azure-servicemanagement-legacy

Active:
- azure-core
- azure-core-experimental
- azure-core-tracing-opencensus
- azure-core-tracing-opentelemetry
- azure-mgmt-core

First goal would be to enforce black on the `core` folder, without having to black the inactive SDK.

Thanks!

**Comment by scbedd** [comment]
This is completed! We've entirely moved to individual `pyproject.toml` now!
