### ISSUE TITLE
Azure Bundle Does Not Install Clean

### ISSUE THREAD

**Issue by stefangordon** [Azure/azure-sdk-for-python#2818]
I saw storage went to 1.3 last night, probably related, but the Azure bundle does not install cleanly.

```
$ virtualenv test
$ source test/bin/activate
(test) $ pip install azure
```

results in 
```
azure-cosmosdb-table 1.0.3 has requirement azure-storage-common<1.2.0,>=1.1.0, but you'll have azure-storage-common 1.3.0 which is incompatible.
```

**Comment by lmazuel** [comment]
That's weird, I know pip dependency solver is bad, but at this level?.... Let me try to understand what's doing on here.
Thanks for the report!

**Comment by lmazuel** [comment]
Fixed by latest cosmosdb release
