### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by pignrooster** [Azure/azure-sdk-for-python#28181]
The Regression Job class, Forecasting Job class, and Classification Job class all inherit from AutoMLTabular, and each of the child class documentation pages only show the class specific attributes and none of the inherited attributes.  This is not user friendly, especially since there is no documentation page for the parent class AutoMLTabular.  

Additionally, the structure of the V2 documentation is incoherent.  The only way I could figure it out is by looking through this git repo:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl

which was shared by my favorite MS Data Scientist Kapil.  

I work for a Microsoft partner, so I want Azure to be the best.  Our customers are confused and the documentation is part of the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2f4ddb1-65e7-6adf-0ffe-d9de5ba4dae6
* Version Independent ID: 319a5410-32b0-e98d-5ae7-9df7dfe55d66
* Content: [azure.ai.ml.automl.RegressionJob class](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.automl.regressionjob?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-ml/azure.ai.ml.automl.RegressionJob.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.automl.RegressionJob.yml)
* Service: **machine-learning**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by pvaneck** [comment]
Hey, thanks for the docs feedback. Tagging @azureml-github to assist.

**Comment by achauhan-scc** [comment]
closing as obsolete
