### ISSUE TITLE
Failed to connect to SQL Azure from pymssql or pyodbc

### ISSUE THREAD

**Issue by PCSLee** [Azure/azure-sdk-for-python#282]
Hi,

I hit a bit of a brick wall in connecting from Python to SQL Azure. We planned to use SQL Azure as a main DBMS for the ePlanning Project of the NSW Government. This failure triggers the need to evaluate other alternatives.

I have tried pymssql and pyodbc libraries. But both failed for the same reason “server required encryption but support is not compiled in…”. Both Python libraries depend on a FreeTDS library to provide connection to SQL Server of SQL Azure. I have tried modifying the option for encryption in the configuration file “freetds.conf” ( encryption = off/request/required), but none of these options worked.

On the other hand, I can connect successfully to SQL Azure through SSMS or tsql (from FreeTDS).

I append my code as below.

Cheers.
Peter

My python code is
import pymssql
conn = pymssql.connect(server='myServer', user='yyy@server', password='XXXXXX', database='db1' )
cur = conn.cursor()
cur.execute('select field1, field2 from table1')
row = cur.fetchone()
while row:
    print "ID=%d, Name=%s" % (row[0], row[1])
    row = cur.fetchone()
conn.close()

My freetds.conf is
# server specific section
[global]
    # TDS protocol version
	tds version = 8.0
	client charset = UTF-8
        dump file = C:\FreeTDS\etc\freeTDS.log
	text size = 64512

[myServer]
	host = server.database.windows.net
	port = 1433
	encryption = required   #I have tried request or off. None of them worked. 
	tds version = 8.0	
	client charset = UTF-8

Message from the freetds.log
log.c:196:Starting log file for FreeTDS 0.91
	on 2015-02-11 01:11:37 with debug flags 0x4fff.
config.c:716:Setting 'dump_file' to 'C:\Windows\TEMP\freetds.log' from $TDSDUMP.
iconv.c:330:tds_iconv_open(0048E078, UTF-8)
iconv.c:353:Using trivial iconv
iconv.c:187:local name for ISO-8859-1 is ISO-8859-1
iconv.c:187:local name for UTF-8 is UTF-8
iconv.c:187:local name for UCS-2LE is UCS-2LE
iconv.c:187:local name for UCS-2BE is UCS-2BE
iconv.c:349:setting up conversions for client charset "UTF-8"
iconv.c:351:preparing iconv for "UTF-8" <-> "UCS-2LE" conversion
iconv.c:391:preparing iconv for "ISO-8859-1" <-> "UCS-2LE" conversion
iconv.c:394:tds_iconv_open: done
net.c:205:Connecting to 191.238.64.11 port 1433 (TDS version 7.1)
net.c:270:tds_open_socket: connect(2) returned "WSAEWOULDBLOCK: Resource temporarily unavailable."
net.c:310:tds_open_socket() succeeded
util.c:156:Changed query state from DEAD to IDLE
net.c:743:Sending packet
0000 12 01 00 34 00 00 00 00-00 00 15 00 06 01 00 1b |...4.... ........|
0010 00 01 02 00 1c 00 0c 03-00 28 00 04 ff 08 00 01 |........ .(......|
0020 55 00 00 02 4d 53 53 51-4c 53 65 72 76 65 72 00 |U...MSSQ LServer.|
0030 0c 06 00 00            -                        |....|

net.c:554:Received header
0000 04 01 00 25 00 00 01 00-                        |...%....|

net.c:605:Received packet
0000 04 01 00 25 00 00 01 00-00 00 15 00 06 01 00 1b |...%.... ........|
0010 00 01 02 00 1c 00 01 03-00 1d 00 00 ff 0b 00 04 |........ ........|
0020 df 00 02 03 00         -                        |.....|

login.c:1057:detected flag 3
login.c:1068:server required encryption but support is not compiled in
login.c:466:login packet rejected
util.c:156:Changed query state from IDLE to DEAD
util.c:331:tdserror(00490910, 0048E078, 20002, 0)
dblib.c:7929:dbperror(0202A538, 20002, 0)
dblib.c:7981:20002: "Adaptive Server connection failed"
dblib.c:8002:"Adaptive Server connection failed", client returns 2 (INT_CANCEL)
util.c:361:tdserror: client library returned TDS_INT_CANCEL(2)
util.c:384:tdserror: returning TDS_INT_CANCEL(2)
dblib.c:1443:dbclose(0202A538)
dblib.c:258:dblib_del_connection(01EAB18C, 0048E078)
mem.c:615:tds_free_all_results()
dblib.c:305:dblib_release_tds_ctx(1)
dblib.c:5882:dbfreebuf(0202A538)
dblib.c:739:dbloginfree(0202A790)

**Comment by huguesv** [comment]
I was hoping maybe someone that's familiar with pymssql or pyodbc would be able to help, but since that hasn't happened, I'm closing as this is external to python azure sdk.
