### ISSUE TITLE
AuthorizationFailed if a data asset is published within a job

### ISSUE THREAD

**Issue by olihofmann** [Azure/azure-sdk-for-python#28207]
- **azure.ai.ml**: 
- **1.2.0**: 
- **Linux**:
- **3.10**: 

**Describe the bug**
Within a job we create a dataset which should be published. As an artifact of the job we generate a CSV and a MLTable file from which a Data Object is created and by means of MLClient the Data Asset is to be created and updated. During the update an _AuthorizationFailed_ exception is thrown. The message is as follows:

Message: The client '<Principal ID>' with object id '<Principal ID>' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/datastores/read' over scope '/subscriptions/<GUID>/resourceGroups/<Name>/providers/Microsoft.MachineLearningServices/workspaces/<Name>/datastores/workspaceblobstore' or the scope is invalid. If access was recently granted, please refresh your credentials.

**To Reproduce**
1. Create or Update Job
2. Create MLClient within the job `ml_client: MLClient = MLClient.from_config(credential=DefaultAzureCredential())`
3. Create the CSV within the job `dataset.to_csv(delimited_file_path, index=False)`
4. Create an MLTable `
path = {
        "file": delimited_file_path
    }
    ml_table = mltable.from_delimited_files(
        paths=[path],
        delimiter=",",
        encoding=mltable.MLTableFileEncoding.utf8,
        include_path_column=False
    )
    ml_table.save(artifact_path)`
5. Create Data Object `food_size_data_asset = Data(
        path=artifact_path,
        type=AssetTypes.MLTABLE,
        name="the-dataset",
        description="The dataset description"
    )`
6. Create or update dataset `regsitred_data_asset = ml_client.data.create_or_update(food_size_data_asset)`

**Expected behavior**
The dataset is created correctly within the job. The compute cluster has a System Assigned Identity which has the necessary authorization to perform such steps.

**Screenshots**
![ml-workspace-error](https://user-images.githubusercontent.com/12451151/210950365-a1173f79-ea77-4040-bb91-f95e1c2f0416.png)

**Additional context**
With the old V1 SDK this worked without errors.

**Comment by pvaneck** [comment]
@azureml-github, can any of you shed some insight into why this might be happening?

**Comment by ttphan** [comment]
Can confirm, `ml_client.data.create_or_update(...)` throws an `AuthorizationFailed` exception on a compute cluster with system assigned identity.
However, using a compute instance with the right authorization succeeds.

**Comment by mehmetyuksel41** [comment]
Having the same issue. I`m able to do this using old SDK.

**Comment by achauhan-scc** [comment]
closing as obsolete
