### ISSUE TITLE
azureappconfigurationprovider.py cannot load KeyVault reference configs

### ISSUE THREAD

**Issue by batt001** [Azure/azure-sdk-for-python#28230]
- **Package Name**: azure.appconfiguration.provider
- **Package Version**: 1.0.0b1
- **Operating System**: Windows 11
- **Python Version**: 3,.9

**Describe the bug**
Trying to load KeyVault reference configurations from an App Configuration resource using AD credentials results in the following exception: "Exception: AttributeError: 'str' object has no attribute 'vault_url'"

**To Reproduce**
1. Deploy a KeyVault resource
2. Add a secret in deployed KeyVault eg. dummySecret
3. Deploy App Configuration and Azure Function App (python) resource
4. Grant secret reading Access Policies to both App Configuration and Azure Function App managed identity
5. Add KeyVault reference configuration to App Configuration which is pointing to dummySecret in deployed KeyVault
6. Deploy Azure Function which is trying to load all configs from App Configuration with the method presented here https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/appconfiguration/azure-appconfiguration-provider/samples/key_vault_reference_sample.py

**Expected behavior**
Load succeeds without any exceptions.

**Possible FIX**
Replace existing line number 123 in file _azureappconfigurationprovider.py with this:
(client for client in secret_clients.values() if client.vault_url == key_vault_identifier.vault_url), None

Code should iterate through the values of the secret_clients dictionary instead of the keys!

**Screenshot**

![Code_M1QdumYiWN](https://user-images.githubusercontent.com/16069848/211289197-a79d7b66-85fc-4735-839b-cd23e44e5448.png)

**Comment by batt001** [comment]
Hi @mrm9084 ,
I've updated my original comment with more detailed reproduction steps. The issue I found is that in "_azureappconfigurationprovider.py" file on line 123 when it iterates through the "secret_clients" dictionary it goes through the keys of that dictionary which are strings in this case. But it tries to call the "client.vault_url" which fails obviously because strings don't have "vault_url" attributes. However the values of this dictionary supposed to be instances of the "SecretClient" class which has this "vault_url" attribute.

**Comment by mrm9084** [comment]
@batt001, The code is correct there. The Configuration setting coming from App Configuration should be of content-type, 
application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8, which is a special type of configuration Setting, that has does have a vault_url.

How did you make your key vault reference. There is a special command in via the cli, and a different interface in the portal.

**Comment by batt001** [comment]
@mrm9084 I made the KeyVault references in my App Configuration using the Azure portal, manually.

The issue is not with the configs coming from the App Configuration but with the secret_clients, which are coming from the key_vault_options originally, but gets updated during loading KeyVault reference configs from App Configuration.
Let me try to explain it in a little more detail, maybe this will help to understand:

### My code ###
app_configuration_endpoint = "xy_app_config_endpoint"
credential = DefaultAzureCredential(
    additionally_allowed_tenants="*",
    exclude_shared_token_cache_credential=True
    )
key_vault_options = AzureAppConfigurationKeyVaultOptions(credential=credential)
secrets = AzureAppConfigurationProvider.load(endpoint=app_configuration_endpoint, credential=credential, key_vault_options=key_vault_options)

# This way key_vault_options.secret_clients = {}, this is the default behaviour of AzureAppConfigurationKeyVaultOptions()

### Azure SDK code ###
azure\appconfiguration\provider\_azureappconfigurationprovider.py: line 61: 
  Gets the 'secret_clients' which is {} in the beginning
azure\appconfiguration\provider\_azureappconfigurationprovider.py: line 77:
  Since the configs type is "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8" as you mentioned right, it calls the provider.__resolve_keyvault_reference(config, key_vault_options, secret_clients).
azure\appconfiguration\provider\_azureappconfigurationprovider.py: line 123:
  For the first KV reference config the 'secret_clients' is an empty dictionary, that's fine.
  But in line 134 it fills the 'secret_clients' dict, for example in my case this will be the content:

![Code_yAdolosbxB](https://user-images.githubusercontent.com/16069848/212291301-f126e434-95c5-47d2-841d-7b5de6a3a0af.png)

  As you can see the types are {string : azure.keyvault.secrets._client.SecretClient}!
  When the next KV reference config is being resolved the same line 123 is going through the KEYS (represented here as variable 'client') of the dictionary, which are simple string types.
  Then the exception happens, because 'client' which is a string doesn't have the '.vault_url' property.


Instead of iterating over the keys of the 'secret_clients' dictionary, it need to go through the values!

**Comment by mrm9084** [comment]
@batt001, I have figured out the issue, issue. I will have a PR with it soon.

**Comment by batt001** [comment]
@mrm9084 Great, do we know approximately when this will be part of a public release of the module?

**Comment by georgeOsdDev** [comment]
I faced same error.
Minimum reproduce code is below.
This code will throw exception If App Configuration has more than 1 key vault reference. It work If it have one key vault reference.

```
import os
from azure.appconfiguration.provider import (
    AzureAppConfigurationKeyVaultOptions,
    AzureAppConfigurationProvider,
)
from azure.identity import DefaultAzureCredential
credential = DefaultAzureCredential()
key_vault_options = AzureAppConfigurationKeyVaultOptions(credential=credential)
config = AzureAppConfigurationProvider.load(
    connection_string=os.environ.get("ACConnectionString"), key_vault_options=key_vault_options
)
print(config["myKeyInKeyVaultViaAppConfig"])
```

```
  File "/home/vscode/.local/lib/python3.9/site-packages/azure/appconfiguration/provider/_azureappconfigurationprovider.py", line 77, in load
    secret = provider.__resolve_keyvault_reference(config, key_vault_options, secret_clients)
  File "/home/vscode/.local/lib/python3.9/site-packages/azure/appconfiguration/provider/_azureappconfigurationprovider.py", line 122, in __resolve_keyvault_reference
    referenced_client = next(
  File "/home/vscode/.local/lib/python3.9/site-packages/azure/appconfiguration/provider/_azureappconfigurationprovider.py", line 123, in <genexpr>
    (client for client in secret_clients if client.vault_url == key_vault_identifier.vault_url), None
AttributeError: 'str' object has no attribute 'vault_url'
```

**Comment by mrm9084** [comment]
I have a fix for this up in a PR, it might be a small while before it is updated as the PR also adds Async Support.

**Comment by mrm9084** [comment]
@batt001 we don't have an exact date, but we will try to get it out as soon as we can. It needs to finish an internal review.

**Comment by andrea-cassioli-maersk** [comment]
Please hurry up!

**Comment by mrm9084** [comment]
@andrea-cassioli-maersk sorry. This got added into all the other changes we were making in the next beta. I hope it is out either later today, or tomorrow.

**Comment by mrm9084** [comment]
A new beta version has been released `azure-appconfiguration-provider 1.0.0b2`

**Comment by AppElent** [comment]
im experiencing this as well. Tried installing the beta but then I experience other issues
```
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ericj\.virtualenvs\api-tF_GQgrE\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ericj\.virtualenvs\api-tF_GQgrE\Lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\ericj\.virtualenvs\api-tF_GQgrE\Lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\ericj\.virtualenvs\api-tF_GQgrE\Lib\site-packages\django\core\management\__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\ericj\.virtualenvs\api-tF_GQgrE\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ericj\.virtualenvs\api-tF_GQgrE\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\ericj\.virtualenvs\api-tF_GQgrE\Lib\site-packages\django\apps\registry.py", line 124, in populate
    app_config.ready()
  File "D:\Dev\appelent-monorepo\django\api\api\apps.py", line 12, in ready
    AzureAppConfiguration.load(os.getenv("AZURE_APP_CONFIGURATION_ENDPOINT"), "django-api", os.getenv("ENVIRONMENT") or "LOCAL")
  File "D:\Dev\appelent-monorepo\django\api\api\modules\AzureAppConfiguration.py", line 50, in load
    self._config = AzureAppConfigurationProvider.load(endpoint=endpoint, credential=credential, key_vault_options=key_vault_options, selects=selects, trimmed_key_prefixes=trimmed_key_prefixes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AzureAppConfigurationProvider' has no attribute 'load'
```
Any idea if this is an issue in the beta release? When will the non-beta be released?

**Comment by AppElent** [comment]
Also, to add to the issue. My issue came up when I added the second keyvaultref. When I had 1 keyvaultref in appconfig, it was able to retrieve everything as normal, but when I added the same keyvaultref (with the same filterkey and label) then the issue occurred.

**Comment by mrm9084** [comment]
@AppElent, the API was updated in the latest version. It is now just

```python
from azure.appconfiguration.provider import load_provider
config = load_provider(endpoint=endpoint, credential=credential)
```

This is based off feedback we got. You can see it updated in the readme and samples.

**Comment by mrm9084** [comment]
This library is now GA. Note: some breaking changes were made for the GA, check out the announcement for info and links. https://github.com/Azure/AppConfiguration-Announcements/issues/28
