### ISSUE TITLE
This subscription cannot create TextAnalytics until you agree to Responsible AI terms for this resource

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [Azure/azure-sdk-for-python#28233]
"Create a Cognitive Services or Language service resource"

presenting cli approach probably doesn't make sense since creation of a service is not possible from cli:

![image](https://user-images.githubusercontent.com/17368813/211357492-8eea5228-03c4-4395-91e7-e793104a0aa3.png)
or add a warning

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23c50740-e66e-cbd1-e7af-c7bce651515b
* Version Independent ID: 15ad7d42-0291-0725-3f42-502541207423
* Content: [Azure Text Analytics client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/ai-textanalytics-readme?view=azure-python-preview&preserve-view=true)
* Content Source: [docs-ref-services/preview/ai-textanalytics-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/ai-textanalytics-readme.md)
* Service: **textanalytics**
* GitHub Login: @kristapratico
* Microsoft Alias: **krpratic**

**Comment by kristapratico** [comment]
Hi @AwdotiaRomanowna thanks for opening the issue. 

@peytonfraser - Do you know if it's possible to create a Language service resource in the CLI if you haven't accepted responsible AI terms in the Portal? If not, is there a way to accept the terms through the CLI? I tried to reproduce this with my test subscription, but since I've already accepted terms the CLI command works for me.

**Comment by kristapratico** [comment]
Okay, asked around and there isn't a way to accept the terms via CLI. This is explained in the docs [here](https://learn.microsoft.com/en-us/azure/cognitive-services/cognitive-services-apis-create-account-cli?tabs=windows#prerequisites), but I'll leave a note on the Readme as to not mislead people. Thanks for pointing this out, @AwdotiaRomanowna.

> You must create your first Face, Language service, or Computer Vision resources from the Azure portal to review and acknowledge the terms and conditions. You can do so here: [Face](https://portal.azure.com/#create/Microsoft.CognitiveServicesFace), [Language service](https://portal.azure.com/#create/Microsoft.CognitiveServicesTextAnalytics), [Computer Vision](https://portal.azure.com/#create/Microsoft.CognitiveServicesComputerVision). After that, you can create subsequent resources using any deployment tool (SDK, CLI, or ARM template, etc) under the same Azure subscription.
