### ISSUE TITLE
How to distinguish tables and figures

### ISSUE THREAD

**Issue by dunalduck0** [Azure/azure-sdk-for-python#28244]
I am using prebuilt-layout to extract tables from PDF papers. In this paper example [link](https://www.bing.com/ck/a?!&&p=547d11ce29b0c418JmltdHM9MTY3MzIyMjQwMCZpZ3VpZD0yNjM2MGZhOC1lNGVjLTY0NjItMjBiMS0xZWUwZTU1ZjY1MjYmaW5zaWQ9NTQyNg&ptn=3&hsh=3&fclid=26360fa8-e4ec-6462-20b1-1ee0e55f6526&psq=Dual+functional+star+polymers+for+lubricants+rsc&u=a1aHR0cHM6Ly9zY2ktaHViLnNlLzEwLjEwMzkvYzZyYTE3NDYxYiM6fjp0ZXh0PUR1YWwlMjBmdW5jdGlvbmFsJTIwc3RhciUyMHBvbHltZXJzJTIwZm9yJTIwbHVicmljYW50cy4sUlNDJTIwQWR2YW5jZXMlMkMlMjA2JTIwJTI4ODklMjklMkMlMjA4NjI1OSVFMiU4MCU5Mzg2MjY4LiUyMGRvaSUzQTEwLjEwMzklMkZjNnJhMTc0NjFiJTIwMTAuMTAzOSUyRmM2cmExNzQ2MWI&ntb=1), the model mistook the Fig 3 on page 5 as a table (a snapshot of the figure is attached at the end).

My question is two-fold:

1. Is there a built-in way to recognize figures and, therefore filter them out?
2. If the answer is no, I wanted to leverage the surrounding text (e.g. "Fig 3" or "Table 2") to recognize tables vs figures. I wanted to understand the data field bounding_regions.polygen. It has four X-Y points. What are these four points in tables/figures objects and what is the unit?

![image](https://user-images.githubusercontent.com/51274745/211430566-c2b49c23-b74b-4505-9c2f-e3c040de91fe.png)

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you tell us which library and version are you using??

**Comment by dunalduck0** [comment]
Hi @xiangyan99, I am using azure-ai-formrecognizer==3.2.0

**Comment by catalinaperalta** [comment]
Thanks for the questions @dunalduck0! There isn't currently an option to enable/disable specifically recognizing figures with prebuilt-layout. Tagging @vkurpad from the service side to provide more insight here. 

As for your second question, you can use the properties on bounding region to correlate the other recognized content that falls in the area you wish to search. The points of the polygon are the outline for the specific component. For for instance, the points of the bounding region on a table are those that outline the recognized table in the document. The unit depends on whether it's an image or a PDF. For images the unit is pixels and for PDFs it's inches. Here is the definition of the polygon on bounding region:
```
        A list of points representing the bounding polygon
        that outlines the document component. The points are listed in
        clockwise order relative to the document component orientation
        starting from the top-left.
        Units are in pixels for images and inches for PDF.
```

**Comment by dunalduck0** [comment]
Thank you @catalinaperalta for the answer. I was able to eliminate figures by checking whether the nearest (either above or bottom) text starts with "Figure" or "Fig". I hope it would work for most well-written paper.

I have 3 additional questions about table extraction quality.

1. Many tables in the papers of my interest contain both column and row headers. But it seems the package recognizes column headers only without row headers, because I found only two types of data in the extraction: columnHeader and content. There is no rowHeader type. 
2. Often the row/column headers are nested and the extraction struggled to understand them. An example is attached below. In the output (prefix columnHeader_ and content_ is added artifically), the nested column headers are sometimes merged into a single column header (column 2,3,4,5) while sometimes recognized correctly (6,7,8,9). Anything can be done to improve it?

Original table in paper
![image](https://user-images.githubusercontent.com/51274745/214433103-8d11751e-ca3b-4ba4-bf3e-190dae1053f9.png)

Form-recognizer extraction
![image](https://user-images.githubusercontent.com/51274745/214433510-aaeec361-a14d-4c67-b393-659a7046c93f.png)

3. Special symbols, superscripts or subscripts are lost in extracted data (see the same example above). Excel was able to preserve such information (see below), though still struggling with nested headers.

Excel extraction
![image](https://user-images.githubusercontent.com/51274745/214434648-26ec180c-6324-4c95-8abb-ebea661baa5d.png)

**Comment by catalinaperalta** [comment]
Glad to help @dunalduck0! These are good questions, seems that the `prebuilt-layout` algorithm is not recognizing all of the elements you're looking for with this set of documents. It might be that a custom model would help improve recognition for your specific set of documents.
@vkurpad should `prebuilt-layout` have the ability to return some of these content elements (such as the rowHeader in addition to columnHeader, nested headers, and the special symbols)?

**Comment by bojunehsu** [comment]
Hi @dunalduck0,

We are constantly improving our underlying table extraction algorithm.  I was able to get the correct nested column headers via https://formrecognizer.appliedai.azure.com/studio/layout (except 2 missed header text).  Can you try again?
![image](https://user-images.githubusercontent.com/1988517/215692831-37a30cda-cb25-4a68-bf64-8ff69afb08e8.png)

We do return rowHeader as a cell type in certain cases.  But in this particular table, with no visual indication, it subjective whether the Analog column is a rowHeader.  I personally would not label it as such.

The service does not yet support the recognition of super/subscripts, or mathematical formulas in general.
