### ISSUE TITLE
Azure-storage-blob returns `ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1045)` when uploading file to existing container

### ISSUE THREAD

**Issue by FaCoffee1984** [Azure/azure-sdk-for-python#28256]
- **Package Name**: azure-storage-blob
- **Package Version**:  12.14.1
- **Operating System**: Windows 10
- **Python Version**:  3.7.0

**Describe the bug**
Trying to upload a file to an existing container using the Python Azure SDK returns:
`ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1045)`

**To Reproduce**
```python
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient
import shutil
import tempfile
import os

account_url = "https://<storage-account-name>.blob.core.windows.net/"
container_name = <my-container-name>
key = <my-key>
blob_service_client = BlobServiceClient(account_url=account_url, credential=key)
container = blob_service_client.get_container_client(container=container_name)

temp_folder = tempfile.gettempdir()
download_folder = os.path.join(temp_folder, 'test_folder')


def upload_image_to_blob(container, local_file_name, local_file_path) -> str:
    '''Given an existing container, create a blob with a given name and upload file.'''
    
    # Create a blob client using the local file name as the name for the blob
    blob_name = local_file_name
    blob_client = container.get_blob_client(container, blob_name)
    
    # Upload the created file
    with open(file=local_file_path, mode="rb") as data:
        blob_client.upload_blob(data)
    
    return blob_client.url

# Execute function
blob_urls= []
for filename in os.listdir(download_folder):
	file_path = os.path.join(download_folder, filename)
	print(file_path)
	if os.path.isfile(file_path) or os.path.islink(file_path):
		blob_url = upload_image_to_blob(container=container, local_file_name=filename, local_file_path=file_path)
                blob_urls.append(blob_url)
```

**Expected behavior**
Expected: a copy of the file is taken from the local folder and uploaded to the container.

**Screenshots**
![image](https://user-images.githubusercontent.com/60174218/211583494-8707d216-be24-47a2-8755-f82fedc4bd10.png)

**Additional context**

**Comment by vincenttran-msft** [comment]
Hi @FaCoffee1984 Francesco thanks for your inquiry. Unfortunately, I was not able to reproduce your issue locally. However, one thing I found is that I was not able to run your sample code as provided and required minor changes.

Namely, this line in your sample code: `blob_client = container.get_blob_client(container, blob_name)` does not seem properly formed for the `get_blob_client` API for `ContainerClient` (documentation [here](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-get-blob-client)) and was giving me an error.

After replacing that line with `blob_client = container.get_blob_client(blob_name)`, I was able to successfully upload my file from my local machine to the container.

Typically SSL issues are related to environment setup issues or firewall policies, and so below are some recommendations that may help you resolve your issue:
- Check your firewall or VPN settings if applicable (especially if on a corporate network with a strict networking policy)
- Ensure all URLs are correctly formed and typo-free (i.e. `.blob.core.windows` vs. `.blob.corewindows`)
- Check on any network monitoring software or certificates for any network monitoring software (i.e. WireShark or Fiddler) as these can cause issues when using the SDK
- Lastly, to isolate this as an environment issue and not an SDK issue, you can follow the guidance [here](https://github.com/Azure/azure-sdk-for-python/issues/27921#issuecomment-1350247889) and set `connection_verify=False` to see if disabling SSL certificate verification altogether resolves your issue

With that being said, hopefully the above helps to resolve your issue.

Thanks!
