### ISSUE TITLE
Azure Resource Graph with python sdk: Trying to implement 'first' and 'skip' for paging the results but getting a warning as "first is not a known attribute of class .. and will be ignored"

### ISSUE THREAD

**Issue by humak** [Azure/azure-sdk-for-python#28251]
- **Package Name**:  azure.mgmt.resourcegraph
- **Package Version**:  8.0.0
- **Operating System**: Windows 10
- **Python Version**:  3.9.13

**Describe the bug**
I am working with a large data set and since graph api has limit for 1000 resources by default, I am trying on paging the results, as described here: https://learn.microsoft.com/en-us/azure/governance/resource-graph/concepts/work-with-data#paging-results
Here is how I use skip and first as an example:

argQueryOptions = arg.models.QueryRequestOptions(result_format="objectArray", first=10, skip=10)

I know that if I use **limit** in the query, skip will be ignored, as a result I need to use first to limit my output and be able to keep track of it.
Here is the warning that I am getting while using **first**.

**first is not a known attribute of class <class 'azure.mgmt.resourcegraph.models._models_py3.QueryRequestOptions'> and will be ignored**

My question is:
1. Is there a recommended way of using 'first', am I doing sth wrong?
2. If using 'first' and 'limit' is not possible in this case, what is the recommendation for large data sets, to limit the results, over 1000 results?

**To Reproduce**
1. Use the above package and attempt to similar query: 
 argQueryOptions = arg.models.QueryRequestOptions(result_format="objectArray", first=10, skip=10)
 getresources("Resources| where type == 'microsoft.network/virtualnetworks'| project name, id, type, location, subscriptionId, resourceGroup, tags| order by id asc")

**Expected behavior**
Being able to skipping and limiting results at the same time, either with limit or first.

**Comment by Wzb123456789** [comment]
Hi @humak 

According to my investigation, there is no first parameter in the QueryRequestOptions model parameters, you can try to use the top parameter.
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/_models_py3.py#L591-L619

You can refer to this sample:https://github.com/Wzb123456789/azure-samples-python-management/blob/main/samples/resourcegraph/resources_query.py#L46
