### ISSUE TITLE
"Required Content-Range response header is missing or malformed" while using download_blob in azure blob storage using cdn hostname

### ISSUE THREAD

**Issue by SudeshnaBora** [Azure/azure-sdk-for-python#28260]
- **Package Name**:  BlobClient
- **Package Version**:  12.14.1
- **Operating System**: mac
- **Python Version**:  Python 3.10.4 

**Describe the bug**
Not able to download a blob from a container using the cdn hostname **https://<redacted_hostname>.azureedge.net** instead of the origin hostname namely **https://<redacted_hostname_2>.blob.core.windows.net** . Get **Required Content-Range response header is missing or malformed** from **/azure/storage/blob/_download.py", line 435, in _initial_request function**

**To Reproduce**
1.  A connection string 

`connection_string = 'DefaultEndpointsProtocol=https;AccountName=<storage_account_name>;AccountKey=<redacted_account_key>;EndpointSuffix=azureedge.net'`

2. Code snippet to download 

```
from azure.storage.blob import BlobServiceClient, generate_container_sas , ContainerSasPermissions
from urllib.parse import urlparse
from azure.storage.blob import BlobClient

# get container details
blob_service_client = BlobServiceClient.from_connection_string(connection_string)
container_client = blob_service_client.get_container_client("container_name")

# get permission
perm = ContainerSasPermissions(read=True,list=True)

# set expiry
from datetime import datetime, timedelta
expiry=datetime.utcnow() + timedelta(hours=1)

# generate sas token
sas_token = generate_container_sas(
       container_client.account_name,
       container_client.container_name,
       account_key=container_client.credential.account_key,
       permission = perm,
       expiry=datetime.utcnow() + timedelta(hours=1)
   )

sas_url = f"https://<redacted_hostname>.azureedge.net/container_name?{sas_token}"
container_with_blob = "container_name/file.wav"
sas_url_parts = urlparse(sas_url)
account_endpoint = sas_url_parts.scheme + '://' + sas_url_parts.netloc
sas_token = sas_url_parts.query
blob_sas_url = account_endpoint + '/' + container_with_blob + '?' + sas_token;
blob_client = BlobClient.from_blob_url(blob_sas_url);
with open("download_file.wav", "wb") as current_blob:
    stream = blob_client.download_blob()
    current_blob.write(stream.readall())
```

**Expected behavior**
Should be able to download

**Screenshots**

**Additional context**
Able to download properly when using `.blob.core.windows.net` in the `blob_sas_url` . 

Have also tried `BlogEndpoint` in connection string with `azureedge.net` as value still failing in downloading with the cdn hostname.

**Comment by jalauzon-msft** [comment]
Hi @SudeshnaBora, thanks for reaching out. Which CDN pricing tier are you using? There is a known issue with `Microsoft CDN (classic)` with blob downloads where it does not respect the download range header and causes this error. See #22297 for details. The recommended fix is to use a different pricing tier if possible if you wish to use it with the Python SDK. There is also a workaround code snippet listed in that issue, but it seems that may not be working in all cases.
