### ISSUE TITLE
Cannot Import SearchAlias from azure.search.documents.indexes.models

### ISSUE THREAD

**Issue by TylrRssll** [Azure/azure-sdk-for-python#28283]
- **Package Name**:  azure-search-documents
- **Package Version**: 11.3.0
- **Operating System**: Windows
- **Python Version**:  3.8

**Describe the bug**
When trying to import the class SearchAlias from azure.search.documents.indexes.models the error "cannot import name 'SearchAlias' from 'azure.search.documents.indexes.models'" is thrown.

**To Reproduce**
I am using the code as per the sample https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_index_alias_crud_operations.py

**Expected behavior**
Class should be imported.

**Screenshots**
N\A
**Additional context**
N\A

**Comment by xiangyan99** [comment]
Thanks for reaching out.

SearchAlias is a preview feature that it was by design that we did not include it in our 11.3.0 stable release.

You can install latest beta search library https://pypi.org/project/azure-search-documents/11.4.0b2/ to try the feature.

**Comment by TylrRssll** [comment]
Thank you for identifying a version that does include this functionality.
