### ISSUE TITLE
list_blobs() leading to ErrorCode:AuthorizationPermissionMismatch

### ISSUE THREAD

**Issue by msgerneu** [Azure/azure-sdk-for-python#28284]
- Package Name: azure-storage-blob
- Package Version: current
- Operating System: windows 10
- Python Version: 3.9

**Describe the bug**
list_blobs() returns error

_This request is not authorized to perform this operation using this permission.
RequestId:8ec6ffdc-801e-0059-22af-25b14c000000
Time:2023-01-11T11:27:38.7270985Z
ErrorCode:AuthorizationPermissionMismatch
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:8ec6ffdc-801e-0059-22af-25b14c000000
Time:2023-01-11T11:27:38.7270985Z</Message></Error>_

when using **DefaultAzureCredential()** as authentication method.

**To Reproduce**
Run this code:

```
    token_credential = DefaultAzureCredential()
    account_url = f"https://{account_name.lower()}.blob.core.windows.net"
    blob_service_client = BlobServiceClient(account_url=account_url, credential=token_credential)

    account_info = blob_service_client.get_service_properties()
    print(account_info) # exhibit

    container_list = list(blob_service_client.list_containers(include_metadata=True))
    print(container_list)  # exhibit
    for container in container_list:

        container_client = blob_service_client.get_container_client(container.name)
        blob_list = list(container_client.list_blobs(fname)) # <------- error here
        for blob in blob_list:

# ... magic happens here

            print(r)

            break  # for loop, stop after first finding
    return
```

**Expected behavior**
No crash, getting listed blobs

**Additional context**
This code is working fine in SAS Token generated service client.

**Comment by jalauzon-msft** [comment]
Hi @msgerneu Gerrit, `AuthorizationPermissionMismatch` when using `DefaultAzureCredential` (AAD auth) typically indicates the RBAC permissions for whatever account you are authenticating with are not set correctly to be able to perform the operation in question. Looking [here](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#permissions-for-calling-data-operations), the permission needed for `list_blobs` is `Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read`.

This permission would be part of the [built-in role](https://learn.microsoft.com/en-us/azure/storage/blobs/authorize-access-azure-active-directory#azure-built-in-roles-for-blobs) `Storage Blob Data Reader` or you could set up a custom role. Please ensure the account `DefaultAzureCredential` is using has the correct RBAC permissions. Also note that `DefaultAzureCredential` can read an account from a few different sources and that is has a particular order so there is a chance it is using an account you do not expect. See the [doc](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python) for more info on that if needed.

**Comment by navba-MSFT** [comment]
@msgerneu I have looked at the backend logs for the failing request ID and the cause of the above error is due to the lack of RBAC permissions at the data plane level.

> **Data Action Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read** 

Please grant [Storage Blob Data Reader](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-reader)  or[ Storage Blob Data Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor) permissions at the container level (**meaXXXXents**) / account level (**stodaXXXXXXfrom**) and that should help.
