### ISSUE TITLE
create_or_update of VPN connections is not working as expected for adding connection mode as responder only

### ISSUE THREAD

**Issue by rahulbardia** [Azure/azure-sdk-for-python#28305]
- **Package Name**:  network_mgmt_client
- **Package Version**: 5.0.0
- **Operating System**: Linux
- **Python Version**: 3.7

**Describe the bug**
While creating VPN connection using SDK, setting the connection_mode attribute to "ResponderOnly" is not working. It is always setting as "Default".

**To Reproduce**
1. Create VPN site.
2. Making the API call using the SDK to set the VPN connection, passing the following payload(sample):
{'location': 'eastus', 'remote_vpn_site': <azure.mgmt.network.v2019_06_01.models._models_py3.VpnSite object at 0x7f010642cfd0>, 'enable_internet_security': False, 'vpn_link_connections': [{'vpn_site_link': <azure.mgmt.network.v2019_06_01.models._models_py3.VpnSiteLink object at 0x7f01063fcc10>, 'vpn_connection_protocol_type': 'ikev2', 'ipsec_policies': [{'location': 'eastus', 'sa_life_time_seconds': 27000, 'sa_data_size_kilobytes': 102400000, 'ipsec_encryption': 'AES256', 'ipsec_integrity': 'SHA256', 'ike_encryption': 'AES256', 'ike_integrity': 'SHA256', 'dh_group': 'ECP384', 'pfs_group': 'ECP384'}], 'enable_bgp': True, 'enable_rate_limiting': False, 'shared_key': 'eb2973aa-deec-4e9d-b', 'name': 'conn_230e2d36a1_alaska_eastus_64124115167', **'vpnLinkConnectionMode': 'ResponderOnly'**}]}

**Expected behavior**
Expecting a VPN connection creation with ConnectionMode as "ResponderOnly", instead, it always gets created with connection mode as Default.

**Screenshots**
![Uploading Screenshot 2023-01-12 at 1.42.05 PM.png…]()

**Comment by Wzb123456789** [comment]
Hi @rahulbardia thanks for your feedback.

Since I don't know the specific operation you are using, I can't effectively solve the problem for you. Please provide the code block you use so that I can solve your problem more quickly and effectively.

**Comment by rahulbardia** [comment]
Hi, this operation creates a VPN connection between the branch site and hub. This is for the SD-WAN solution. Attaching the code snippet which is used to create this VPN connection.


```
ipsec_policies = {
            "location": location,
            'sa_life_time_seconds': 27000,  # azure default
            'sa_data_size_kilobytes': 102400000,  # azure default
            'ipsec_encryption': esp_encryption,
            'ipsec_integrity': esp_integrity,
            'ike_encryption': encryption,
            'ike_integrity': integrity,
            'dh_group': dh_group,
            'pfs_group': pfs_group
        }
conn_params = {
    "location": location,
    'remote_vpn_site': vpn_site,
    'enable_internet_security': False,
    'vpn_link_connections': [{
        'vpn_site_link': vpn_site_link,
        'vpn_connection_protocol_type': ipsec_info['ike_group']['key_exchange'],
        'ipsec_policies': [ipsec_policies],
        'enable_bgp': True,
        'enable_rate_limiting': False,
        'shared_key': self_psk,
        'name': conn_name,
        'vpn_link_connection_mode': 'ResponderOnly'
    }]
}

context.LOG_LOCAL.info("Connection params: %s" % conn_params)

res_poller = context.network_mgmt_client.vpn_connections.create_or_update(r_group.name,
                                                                          gwy_name,
                                                                          conn_name,
                                                                          conn_params)

```
In above snippet 
vpn_site: It is the site resource object created in VPN site section of the virtual wan.
psk: It is the random PSK which will be set for the VPN connection(IPsec tunnel between site branch and hub)

Kindly let me know if you need any more information.

**Comment by Wzb123456789** [comment]
You first need to upgrade azure-mgmt-network to the latest version. Try again with the following code snippet:

```python
ipsec_policies = {
            "location": location,
            'sa_life_time_seconds': 27000,  # azure default
            'sa_data_size_kilobytes': 102400000,  # azure default
            'ipsec_encryption': esp_encryption,
            'ipsec_integrity': esp_integrity,
            'ike_encryption': encryption,
            'ike_integrity': integrity,
            'dh_group': dh_group,
            'pfs_group': pfs_group
        }
conn_params = {
    "location": location,
    'remote_vpn_site': vpn_site,
    'enable_internet_security': False,
    'vpn_link_connections': [{
        'vpn_site_link': vpn_site_link,
        'vpn_connection_protocol_type': ipsec_info['ike_group']['key_exchange'],
        'ipsec_policies': [ipsec_policies],
        'enable_bgp': True,
        'enable_rate_limiting': False,
        'shared_key': self_psk,
        'name': conn_name,
        'vpn_link_connection_mode': 'ResponderOnly'
    }]
}

context.LOG_LOCAL.info("Connection params: %s" % conn_params)

res_poller = context.network_mgmt_client.vpn_connections.begin_create_or_update(r_group.name,
                                                                          gwy_name,
                                                                          conn_name,
                                                                          conn_params)

```

**Comment by rahulbardia** [comment]
@Wzb123456789 what is the latest stable version for azure.mgmt.network package? SDK documentation is a bit confusing online and facing issues with importing ErrorException modules.

**Comment by Wzb123456789** [comment]
The latest stable package of `azure-mgmt-network` is 22.2.0, you try to delete this package before installing it.
