### ISSUE TITLE
[azure-mgmt-web] checked needed about web_apps.list_metadata_slot method

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-sdk-for-python#28329]
- **Package Name**: azure-mgmt-web
- **Package Version**: 7.0.0
- **Operating System**: Mac OS 
- **Python Version**: 3.8

**Describe the bug**

I created `Function App` Service at Azure Portal.
and then i tried to connect all git repository like github, bitbucket, local, and external.

I expected to get results from all options that I can connect.
but if i connect local git repository, I couldn't get any useful result.

**To Reproduce**
1.  Create Function App with at least `Premium V2`.
2. Create Deployment Slot.
3. Create Deployment Center at your Deployment slot.
4. Request via python sdk.
```
azure_client = WebSiteManagementClient(...)
...
azure_client.web_apps.list_metadata_slot(resource_group_name=resource_group_name, name=name, slot=slot)
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38625842/212249492-8252f2eb-5e90-49a8-a4df-a75c06dea006.png)

**Additional context**

**Comment by SaurabhSharma-MSFT** [comment]
@ImMin5 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@ImMin5 I am not able to reproduce this issue.  I could get the metadata properties correctly.
![image](https://user-images.githubusercontent.com/38112130/213143555-d89d61e4-0a30-4e5e-9ea6-89f86cba3ad5.png)

I am using version - 7.0.0 of `azure-mgmt-web` .  Can you please upgrade your package and check the behavior. Thanks.

**Comment by ImMin5** [comment]
Hi, @SaurabhSharma-MSFT 
Thank you for your investigation

Like you said I can get metadata properties correctly If I use Github, Bitbucket and External Git.

But If I choose `Local Git`  I can not get metadata properties.

<img width="284" alt="스크린샷 2023-01-19 오전 12 08 02" src="https://user-images.githubusercontent.com/38625842/213207662-36d50aaf-8acb-46e2-a66b-2318df7e53b8.png">
 
 Could you please check again? 
Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@ImMin5 I have checked with Local Git and I am getting the properties in the response -
![image](https://user-images.githubusercontent.com/38112130/213338931-b110e001-a044-48cd-80b6-d8f848abfd05.png)

**Comment by ImMin5** [comment]
/unrelove

@SaurabhSharma-MSFT 
Sorry for my late comment.

I'm still get this response. 

![스크린샷 2023-02-22 오후 4 17 35](https://user-images.githubusercontent.com/38625842/220553082-af1ce867-8ad8-467f-b440-0ed4f7b2a78a.png)


What I want to get is `Git Clone Uri` information.
So is there any other way to get this?
![스크린샷 2023-02-22 오후 4 35 05](https://user-images.githubusercontent.com/38625842/220554499-8ed5a6cf-6da8-4f44-a815-7ce1871b79f0.png)

**Comment by SaurabhSharma-MSFT** [comment]
@ImMin5 sorry for my late response.    Are you still having this issue?

**Comment by ImMin5** [comment]
@SaurabhSharma-MSFT 

Sorry for the late comment.
Can I reopen this issue?

I still have this problem.
I think you tried `Github` not a `Local Git` 
Can you check again?
