### ISSUE TITLE
Getting rid of interactive login when using ScriptRunConfig or PipelineStep

### ISSUE THREAD

**Issue by monajalal** [Azure/azure-sdk-for-python#28327]
I am asked for interactive login when I run my job (say train.py) using ScriptRunConfig, however, if I have more than 1 nodes in my cluster, the job will fail since it cannot be verified remotely and only works if I have one node in cluster.

As for PipelineStep, if I have train.py and inference.py and running each as a step in the pipeline, train.py waits on interactive login (that is not asked from me -- but shows why the node fails in the Job menu in Azure Compute), and cancels due to timeout and the inference job that is dependent on the result of train fails.
![Screenshot from 2023-01-12 22-56-22](https://user-images.githubusercontent.com/1892917/212233867-677ed1fe-c3fb-472a-bc37-139c9c66c4c2.png)

So, the question is:

How can I automate the interactive login inside the run_script.py that either runs ScriptRunConfig or 
Here's an example of what I'm asked if I use ScriptRunConfig:

CPython
3.8.13
uname_result(system='Linux', node='number', release='5.0.0-1036-azure', version='#38-Ubuntu SMP Sun Mar 22 21:27:21 UTC 2020', machine='x86_64', processor='x86_64')
Performing interactive authentication. Please follow the instructions on the terminal.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code code to authenticate.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share which Azure service and which library are you using?

**Comment by monajalal** [comment]
@xiangyan99 thanks a lot for spending time looking into this issue.

in `pipeline_run.py` code:

```
import os
import azureml.core
from azureml.core import (
    Workspace,
    Experiment,
    Dataset,
    Datastore,
    ComputeTarget,
    Environment,
    ScriptRunConfig
)
from azureml.data import OutputFileDatasetConfig
from azureml.core.compute import AmlCompute
from azureml.core.compute_target import ComputeTargetException
from azureml.pipeline.steps import PythonScriptStep
from azureml.pipeline.core import Pipeline



# You can find tenant id under azure active directory->properties
ws = Workspace.get(name='MLops-Test', subscription_id='number', resource_group='our-resource-group')

datastore = ws.get_default_datastore()

train_cfg = ScriptRunConfig(source_directory=script_path,
                     script='train.py',
                     arguments=script_args,
                     compute_target=compute_target,
                     environment=env)

train_step = PythonScriptStep(
    name="train step",
    arguments=script_args,
    source_directory=train_cfg.source_directory,
    script_name=train_cfg.script,
    runconfig=train_cfg.run_config,
)

inference_cfg = ScriptRunConfig(source_directory=script_path,
                     script='train2/inference.py',
                     arguments=inference_args,
                     compute_target=compute_target,
                     environment=env)

inference_step = PythonScriptStep(
    name="inference step",
    arguments=script_args,
    source_directory=inference_cfg.source_directory,
    script_name=inference_cfg.script,
    runconfig=inference_cfg.run_config,
)

pipeline = Pipeline(ws, steps=[train_step, inference_step])
run = exp.submit(pipeline)
```

in  the `train.py` code, I have. I need to have access to ws since I need to log various things inside train.py using mlflow.

```
ws = Workspace.get(name='MLops-Test', subscription_id='number', resource_group='our-resource-group')
script_path = os.getcwd()
print('training script path: ', script_path)
mlflow.set_tracking_uri(ws.get_mlflow_tracking_uri())
print("MLflow version:", mlflow.__version__)
print("Tracking URI:", mlflow.get_tracking_uri())
print("Artifact URI:", mlflow.get_artifact_uri())
```


Please let me know if you may have followup questions. When the pipleline is running, when I click on the train node (step), it asked for entering the code to a browser link. I want to eliminate this so that I can fully automate the pipeline.

**Comment by monajalal** [comment]
Issue was resolved with use of Service Principal.
