### ISSUE TITLE
Confidential ACI: `isolation_type` property is not allowed

### ISSUE THREAD

**Issue by jumaffre** [Azure/azure-sdk-for-python#28340]
- **Package Name**: azure-mgmt-containerinstance
- **Package Version**: 10.1.0b1
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.10

**Describe the bug**
It seems that the `"isolation_type"` property in the `ConfidentialComputeProperties` class (see [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/models/_models_py3.py#L306-L323)), yields the following error when trying to create a SEV-SNP enabled container:

```
azure.core.exceptions.HttpResponseError: (IsolationTypeNotSpecified) The Isolation Type is not specified.
Code: IsolationTypeNotSpecified
```

**To Reproduce**
Create a new ACI container via the Python SDK with the `ConfidentialComputeProperties` property set. 

**Expected behavior**
The Azure Container Instance, with the `ConfidentialComputeProperties` set should deploy successfully and the `isolation_type` property should be passed to the constructor of the `ConfidentialComputeProperties` object.

**Comment by SaurabhSharma-MSFT** [comment]
@jumaffre We are looking into it and get back to you for any additional information.

**Comment by Wzb123456789** [comment]
Hi @jumaffre thanks for your feedback.

Since I don't know the specific operation you are using, I can't effectively solve the problem for you. Please provide the code block you use so that I can solve your problem more quickly and effectively.
