### ISSUE TITLE
Subnet update for NSG disassociates Route Table

### ISSUE THREAD

**Issue by derek-andree** [Azure/azure-sdk-for-python#28350]
- **Package Name**:  azure-mgmt-network==19.0.0, azure-identity==1.6.1
- **Package Version**: azure-mgmt-network==19.0.0, azure-identity==1.6.1
- **Operating System**: macOS 12.6, linux centos7
- **Python Version**: Python 3.9.6

**Describe the bug**
I have Python code which updates NSG rules in Azure.  We also have a route table associated with the same subnet that the NSG is associated to.  Previously we were able to do subnets.begin_create_or_update without specifying the route_table argument in subnet parameters which worked as we wanted, that the NSG would be associated to the subnet and the existing route_table would remain unchanged.  A recent run of this code uncovered that the route table which was previously associated with the subnet was disassociated with the subnet as a result of associating the NSG to the subnet.

Basically, this code:
async_subnet_creation = client.subnets.begin_create_or_update(
                resource_group_name=region['rg'],
                virtual_network_name=region['vnet'],
                subnet_name=nsg['subnet'],
                subnet_parameters={
                 'address_prefix': region['subnets'][nsg['subnet']],
                 'network_security_group': live_nsg
                 },
            )

now needs to be this code:
async_subnet_creation = client.subnets.begin_create_or_update(
                resource_group_name=region['rg'],
                virtual_network_name=region['vnet'],
                subnet_name=nsg['subnet'],
                subnet_parameters={
                 'address_prefix': region['subnets'][nsg['subnet']],
                 'network_security_group': live_nsg,
                 'route_table': live_route_table
                 },
            )

**To Reproduce**
1. associate a subnet with both a route table and NSG
2. use subnets.begin_create_or_update to update the NSG association
3. view the route table associations and see that it is no longer associated with the subnet just updated

**Expected behavior**
Any existing associations should not be just blown away without the user specifying the argument in subnet_parameters.  Possibly this should also be true when associating a route table to a subnet which is also associated with an NSG, when the NSG is not passed to subnet_parameters.

**Screenshots**

**Additional context**

**Comment by swathipil** [comment]
@derek-andree - Thanks for your report! We'll take a look at this asap!

**Comment by msyyc** [comment]
@derek-andree When you want to use `begin_create_or_update` to update specefic parameter, you have to get all the parameters first. Otherwise, some existing parameters will be set to None. Please follow steps like:
```python
# get subnet which includes all existing properties
subnet  = client.subnets.get(
    resource_group_name=region['rg'],
    virtual_network_name=region['vnet'],
    subnet_name=nsg['subnet'])

# update some properties
subnet.address_prefix = region['subnets'][nsg['subnet']]
subnet.network_security_group = live_nsg

# update subset
async_subnet_creation = client.subnets.begin_create_or_update(
    resource_group_name=region['rg'],
    virtual_network_name=region['vnet'],
    subnet_name=nsg['subnet'],
    subnet_parameters=subnet)
```

**Comment by derek-andree** [comment]
@msyyc - I understand this is best practice, thank you, and I will use this methodology in the future.  My main question is around why this behavior changed recently.  Previously I was able to update a subnet without losing existing properties.  Is there some documentation which specifies when this behavior was changed in ARM?

**Comment by msyyc** [comment]
@derek-andree Actually it is related with the difference between [PUT and PATCH](https://josipmisko.com/posts/patch-vs-put-rest-api). For our case, begin_create_or_update correspond to PUT so it has such behavior.

**Comment by derek-andree** [comment]
/unresolve as we want to know what changed and when.  The SDK for Python changed at some point and we need to know the details so we can reflect that to our customers.

**Comment by Wzb123456789** [comment]
You can see what changes and when it changes [here](https://pypi.org/project/azure-mgmt-network/23.0.0b2/).
![image](https://user-images.githubusercontent.com/51410816/227869845-3359a547-03dc-40ba-9ccc-e0ba68e38871.png)

**Comment by msyyc** [comment]
`Previously I was able to update a subnet without losing existing properties. Is there some documentation which specifies when this behavior was changed in ARM?`
-> Python SDK is generated with swagger by tools automatically and swagger is developed by service team. Maybe you could make issue in https://github.com/Azure/azure-rest-api-specs/issues to ask service team.
