### ISSUE TITLE
Importing MLClient in online endpoint gives error "cannot import name TokenCredential from azure.core.credentials"

### ISSUE THREAD

**Issue by malikaasen** [Azure/azure-sdk-for-python#28369]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.2.0
- **Operating System**: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
- **Python Version**: 3.8

**Describe the bug**
When trying to use ml client in a deployed online endpoint, `from azure.ai.ml import MLClient` causes `cannot import name TokenCredential from azure.core.credentials`

**To Reproduce**
1. create an online deployment
2. create an online endpoint where you import mlclient

**Expected behavior**
No import error, and a working mlclient

**Additional context**
Perhaps you need another dependency(importing MLClient shouldn't cause an import error except for "could not import MLCient" if the azure-ai-ml was not installed). Here are the ones i give the environment:

```
name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.2
  - pip=22.3.1
  - scipy=1.7.1
  - pandas>=1.1,<1.2
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - applicationinsights==0.11.10
    - sentence-transformers ==2.2.2
    - pytorch-lightning == 1.7.6
    - azure-ai-ml
    - azure-identity 
    - azureml-defaults==1.38.0

```

**Comment by swathipil** [comment]
Hi @malikaasen - Thanks for opening an issue. Based on this error, it seems like `azure-core` has not been installed. However, `azure-core` is a dependency for `azure-ai-ml`, so it should be installed automatically when `azure-ai-ml` is installed. 

Is this the entire list of dependencies? If not, would you be able to reply with the output of running `pip freeze` in your environment? Thanks!

@azureml-github - Would you be able to take a look?

**Comment by malikaasen** [comment]
Thanks for responding @swathipil What you were saying were my thoughts exactly. 

That is the entire list of dependencies.

**Comment by harneetvirk** [comment]
@malikaasen: Is it possible to share the output of `pip list` command from the created environment to verify if azure-core is installed or not. What is the version of azure-core being installed in the environment.

**Comment by malikaasen** [comment]
Can confirm that output is the same as `pip list`
```
azure-ai-ml                   1.3.0
azure-common                  1.1.28
azure-core                    1.21.1
azure-graphrbac               0.61.1
azure-identity                1.7.0
azure-mgmt-authorization      0.61.0
azure-mgmt-containerregistry  8.2.0
azure-mgmt-core               1.3.0
azure-mgmt-keyvault           9.3.0
azure-mgmt-resource           20.1.0
azure-mgmt-storage            19.1.0
azure-storage-blob            12.11.0
azure-storage-file-datalake   12.6.0
azure-storage-file-share      12.7.0
azureml-core                  1.38.0.post2
azureml-dataprep              2.26.0
azureml-dataprep-native       38.0.0
azureml-dataprep-rslex        2.2.0
azureml-dataset-runtime       1.38.0
azureml-defaults              1.38.0
```

**Comment by harneetvirk** [comment]
The `pip list` output is showing very old version of azure-core installed in the environment.
azure-core==1.21.1 (Released: Dec 6, 2021).

Could you please pin the azure-core package to some newer versions in your env.yaml file?

**Comment by malikaasen** [comment]
sure, any rec or just latest?

**Comment by harneetvirk** [comment]
Any recent version of the azure-core should work.

**Comment by malikaasen** [comment]
Are there any lists of compatible versions @harneetvirk? I'm getting conflicts left right and center for these packages:
` - azure-core ==1.26.2
    - azure-ai-ml = 1.3.0
    - azure-identity 
    - azureml-defaults
`

The environment managed to build when i omitted azureml-defaults, but that caused other issues, namely the endpoint not being able to start... I had hoped that if i selected the latest versions of these 4 it would work, but azure-ai-ml clashes with various packages

**Comment by harneetvirk** [comment]
Could you refer to the workaround mentioned in this GitHub issue: https://github.com/Azure/azure-sdk-for-python/issues/25589#issuecomment-1401366546

**Comment by malikaasen** [comment]
Is there any example of a dockerfile like the one mentioned(Would be helpful if an example was included [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-environments-v2?tabs=python#create-an-environment-from-a-docker-build-context) in the future)? Do you have an estimate of the time it would take before the updated packages are released @harneetvirk ?

**Comment by malikaasen** [comment]
Thanks, the workaround did work. Any idea when the fixes will get released @harneetvirk?

**Comment by malikaasen** [comment]
I am now facing issues with authorization, do i need to do something additional now that i'm using docker rather than env? I tried to follow the managedidentity example by creating credential like this     `credential = ManagedIdentityCredential(client_id=os.getenv("UAI_CLIENT_ID"))`. using DefaultCredential gave me the same error
`
azure.core.exceptions.HttpResponseError: (AuthorizationFailed) The client \'X\' with object id \'X\' does not have authorization to perform action \'Microsoft.MachineLearningServices/workspaces/data/versions/read\' over scope \'/subscriptions/X/resourceGroups/X/providers/Microsoft.MachineLearningServices/workspaces/X/data/X/versions/1\' or the scope is invalid. If access was recently granted, please refresh your credentials.`

**Comment by harneetvirk** [comment]
The DefaultAzureCredential assumes the AZURE_CLIENT_ID, AZURE_TENANT_ID, and AZURE_CLIENT_SECRET environment variables are set.

More details on configuring your environment to use the DefaultAzureCredential can be found in the class's reference documentation: https://aka.ms/azsdk/python/identity/defaultazurecredential

**Comment by malikaasen** [comment]
Thanks, I'll go on my own from here on, so i'll close this issue. Thanks for the help!

**Comment by malikaasen** [comment]
Hi @harneetvirk, I was unsure if I should create a new task for this, but i have a related question(LMK if i should open a separate task if needed). What is Azure's recommended flow for this case: fetch data for an endpoint during endpoint startup.

I wanted the MLClient so that I could fetch a data-asset, but this proved quite challenging. The MLClient works fine now(after creating credentials that is fetched automatically) so thanks for that! However, the documentation is a bit lackluster on how to work with data in endpoints. 

I am able to fetch the data asset using MLClient, but the only example on fetching a data asset showed that you then used mltable to load it into a dataframe using the path from the data object MLClient returned. This then triggers another authentication flow(interractive). 

Is this the recommended way to fetch data assets, and if so, how can you automate the second authentication?
