### ISSUE TITLE
Executing a query using the SDK gives wrong results

### ISSUE THREAD

**Issue by robert1826** [Azure/azure-sdk-for-python#28396]
- **Package Name**:  azure-cosmos
- **Package Version**: 4.3.0
- **Operating System**: Windows 11
- **Python Version**: 3.7.4 

**Describe the bug**
Executing a query using the SDK gives the wrong results, while executing the same query on the azure portal on the same cosmos DB account gives the expected result.

query:
```
        select * from 
        (
            SELECT Count(1) as emails_received, c.user.id, c.project.id, TimestampToDateTime(MAX(c._ts*1000)) as last_received
            FROM c 
            where c.category = '...'
            group by c.user.id, c.project.id
        ) as d
        where d.emails_received < N and d.last_received < '...' 
```

**To Reproduce**
1. Install azure-cosmos 4.3.0
2. Execute the query using this SDK code:
```
    client = CosmosClient.from_connection_string(CONNECTION_STR)
    db = client.get_database_client(DB_NAME)
    container = db.get_container_client(CONTAINER_NAME)
    query = '<the above query>'
    res = list(container.query_items(query=query, enable_cross_partition_query=True))
```

**Expected behavior**
The last_recieved field shows that the date returned in it is NOT expected, as it shows an earlier date for the same user and project combo, however the same query returned the correct date in last_received field as expected when executing the query on the azure portal.

I tried setting enable_cross_partition_query to False to see if it's the problem but the code throws an exception in this case and says that it's required for the query to execute.

**Comment by swathipil** [comment]
@robert1826 - Thanks for your report! We'll investigate asap!

**Comment by robert1826** [comment]
> @robert1826 - Thanks for your report! We'll investigate asap!

@swathipil great, also I can reach out to you internally if that makes the process faster / easier for you to investigate.

**Comment by swathipil** [comment]
Hi @robert1826 - I don't own this SDK, so it would definitely be faster/easier to continue following up here. 🙂 The SDK owners should be reaching out to you soon. Thanks!

**Comment by simorenoh** [comment]
Hi @robert1826, was wondering if this was something you were still having issues with, and if such I'd greatly appreciate a sample document so that I can try and reproduce it from my end, thanks!
