### ISSUE TITLE
Get all active instances in a subscription

### ISSUE THREAD

**Issue by robot-love** [Azure/azure-sdk-for-python#28409]
**Is your feature request related to a problem? Please describe.**

We are monitoring all of our active instances for start/end times to correctly bill our customers. We launch our instances in a VMSS as part of a resource group.

Currently, to retrieve the list of active instances we need to perform a series of nested API calls for each active instances, something like:

```
list(get all clients and subscription ids)

for each (client-id, subscription-id) get resource groups
  for each resource group get vmss resources
    for each vmss resource get vmss instances
```

We have more than a few instances running at any given time and the nested API calls to retrieve one instance leads to very long retrieval time for all active instances.

It usually takes 1hr to 4hrs and sometimes more.

**Describe the solution you'd like**

A single endpoint or function to return all of our active instances.

**Describe alternatives you've considered**

We are not aware of an alternative way to get the list of all active instances in a subscription.

**Additional context**

N/A

**Comment by robot-love** [comment]
Hi, this is the package I'm referring to:

```
azure-mgmt-resource      3.0.0         Microsoft Azure Resource Management Client Library for 
```

**Comment by Wzb123456789** [comment]
Hi @robot-love 

Please update your `azure-mgmt-resource` to the latest version, The latest version is: `22.0.0`

You can use the following example to try to solve your problem:https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/resources/manage_resource_subscriptions.py
