### ISSUE TITLE
Documentation misspelled

### ISSUE THREAD

**Issue by wangzelin007** [Azure/azure-sdk-for-python#28408]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/18628534/213380976-61dd5b85-ecd4-4fec-94c9-25501ac684a3.png)
![image](https://user-images.githubusercontent.com/18628534/213381043-408e5453-4c37-4651-9dbd-76c7b3b93b0d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72e24a83-f589-362e-3207-c9510bc58bc9
* Version Independent ID: 4f64ffdb-f36e-fa4d-4a03-431393b3c4c8
* Content: [Azure Communication Email client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/communication-email-readme?view=azure-python-preview)
* Content Source: [docs-ref-services/preview/communication-email-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/communication-email-readme.md)
* Service: **communication**
* GitHub Login: @acsdevx-msft
* Microsoft Alias: **acsdevx-msft**

**Comment by PramodValavala-MSFT** [comment]
@wangzelin007 Thanks for catching that! We have worked up a PR to address this.
