### ISSUE TITLE
Ref docs issue

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-python#28429]
Error:
> Receiving objects:   5% (889/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:   6% (1067/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:   7% (1245/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:   8% (1423/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:   9% (1600/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:  10% (1778/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:  11% (1956/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:  12% (2134/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:  13% (2311/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:  14% (2489/17776), 18.19 MiB | 36.22 MiB/s
> Receiving objects:  14% (2569/17776), 34.46 MiB | 34.42 MiB/s
> error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
> fetch-pack: unexpected disconnect while reading sideband packet
> fatal: early EOF
> fatal: fetch-pack: invalid index-pack output
> ##[error]Git fetch failed with exit code: 128

For more details check here:
https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=342062&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
This looks like a transient error as later builds succeeded. It can be closed. Thanks!
