### ISSUE TITLE
Unregister/Deleting Models

### ISSUE THREAD

**Issue by Nephdz** [Azure/azure-sdk-for-python#28423]
- **Package Name**: AzureML
- **Package Version**: 1.43.0
- **Operating System**: Windows 11
- **Python Version**: 3.8.13

**Describe the bug**
Not sure if this is a bug or intentional feature but when running delete() on all versions of a model, all the associated data seems to be removed but the metadata is still kept around. This means if I try to register under the same name, the versioning continues from where it left off. 

**To Reproduce**
1. Register a model
2. Delete all versions of that model
3. Register a model under the same name
4. See that the version has picked up where it left off

**Expected behavior**
I would expect the versioning to reset if I deleted all the versions of a model. I also couldn't find where the files and metadata were being stored in the backend storage account. My guess is it's hidden but not entirely sure on that.

**Comment by swathipil** [comment]
@Nephdz - Thanks for your report! We'll investigate asap!

@azureml-github - Can you take a look?

**Comment by Nephdz** [comment]
If it turns out that this is an intended feature then I would like to know where I can find the metadata and files in the storage account so that I can try to make some manual changes.

**Comment by jaga-work** [comment]
Hi @Nephdz, Access to the metadata is restricted and cannot be shared to the end user.
