### ISSUE TITLE
NoneType error when calling 'list_manifest_properties' for ContainerRegistryClient

### ISSUE THREAD

**Issue by dmartin-r7** [Azure/azure-sdk-for-python#28432]
- **Package Name**: azure-containerregistry
- **Package Version**:  1.0.0
- **Operating System**: macOS
- **Python Version**:  3.8

**Describe the bug**
When calling `list_manifest_properties` a NoneType is being hit.

```
TypeError: 'NoneType' object is not iterable
  File "...", line 6034, in ...
    for manifest in registry_client.list_manifest_properties(repository):
  File "/usr/local/lib/python3.8/dist-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/usr/local/lib/python3.8/dist-packages/azure/containerregistry/_container_registry_client.py", line 316, in extract_data
    list_of_elem = cls(list_of_elem)
  File "/usr/local/lib/python3.8/dist-packages/azure/containerregistry/_container_registry_client.py", line 242, in <lambda>
    lambda objs: [
```

The `extract_data` method for `list_manifest_properties` is as follows:
```
def extract_data(pipeline_response):
    deserialized = self._client._deserialize(  # pylint: disable=protected-access
        "AcrManifests", pipeline_response
    )
    list_of_elem = deserialized.manifests
    if cls:
        list_of_elem = cls(list_of_elem)
    link = None
    if "Link" in pipeline_response.http_response.headers.keys():
        link = _parse_next_link(pipeline_response.http_response.headers["Link"])
    return link, iter(list_of_elem)
```
In the other `extract_data` method of `list_repository_names` the `list_of_elem` deserialization is handled like this:
`list_of_elem = deserialized.repositories or []`

Is this supposed to be the case for `list_manifest_properties` also? Looks like nothing is being deserialized here and the nonetype is passing into the rest of the call.

I also note this package has two unreleased versions, the latest having changes to manifest related calls. Is there a GA update coming soon?

**Comment by swathipil** [comment]
@dmartin-r7 - Thanks for your report! We'll take a look asap!

**Comment by YalinLi0312** [comment]
Hi @dmartin-r7 , we are focusing on new features development recently, will back to fix this bug when we get a chance. Thanks!

**Comment by YalinLi0312** [comment]
Hi @dmartin-r7 , we are working on it. Will get it fixed in our next preview release.

**Comment by YalinLi0312** [comment]
> hi @YalinLi0312 thanks for the update, what version number will this be released in?

Here's the release: https://pypi.org/project/azure-containerregistry/1.1.0b2/
