### ISSUE TITLE
Connection using Managed Identity

### ISSUE THREAD

**Issue by miqm** [Azure/azure-sdk-for-python#28430]
Is connection to App Configuration using Managed Identity supported in python? If yes, please update the page with an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68f21d4e-7ef5-143d-fde8-22f8fd0fc68f
* Version Independent ID: 0bedc6e5-8d74-2151-b603-74018149b162
* Content: [Azure App Configuration client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/appconfiguration-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/appconfiguration-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/appconfiguration-readme.md)
* Service: **appconfiguration**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by swathipil** [comment]
@miqm - Thanks for opening an issue! We'll take a look asap!

**Comment by xiangyan99** [comment]
@miqm Yes. App configuration supports managed identity credential. And it is already covered in https://learn.microsoft.com/en-us/python/api/overview/azure/appconfiguration-readme?view=azure-python#use-aad-token. 

Azure-identity supports multiple AAD credential types and Managed identity credential is one of them. (https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity/azure-identity#defaultazurecredential)

**Comment by miqm** [comment]
@xiangyan99 thanks. Perhaps it would be worth adding `(Managed Identity)` next to the AAD Token as this name is more widely known and used across MS docs?

**Comment by xiangyan99** [comment]
@miqm Thank you for your suggestion.

As you know, Managed Identity only works when you deploy the applications in Azure Hosted resources. (Azure VM, Azure App service, etc.). We don't want to mistakenly give our customers the impression that Managed Identity is the only recommended way.

Service principal and other authentication methods are also useful and important.

That's the reason that in our identity doc, we only use `AAD Token`.

**Comment by miqm** [comment]
Makes sense, thanks for detailed explanation.
