### ISSUE TITLE
msrest dependency conflict with other sdk libs

### ISSUE THREAD

**Issue by nidhaloff** [Azure/azure-sdk-for-python#28444]
- **Package Name**:  azure-storage-blob
- **Package Version**: latest (12.14.1)
- **Operating System**: Ubuntu
- **Python Version**: 3.7

**Describe the bug**

I have a project, where I want to use this lib and the azure-storage-blob lib. I'm having a dependency conflict since this lib requires `"msrest>=0.7.1,<0.8.0"`. 

This is the error I'm getting:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azure-devops 6.0.0b4 requires msrest<0.7.0,>=0.6.0, but you have msrest 0.7.1 which is incompatible.
```

**To Reproduce**

`pip install azure-storage-blob && pip install azure-devops`

**Expected behavior**

No dependency conflict.

**Additional context**

In the changeslog.md https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/CHANGELOG.md of the azure-storage-blob lib, I saw that msrest will be removed as a requirement in the next release (12.15.0b1). However it is not released yet. Would this version solve my problem when it is released?

**Comment by kashifkhan** [comment]
Thank you for the feedback @nidhaloff. We will investigate and get back to you.

**Comment by jalauzon-msft** [comment]
Hi @nidhaloff Nidhal, in our upcoming release, `12.15.0b1`, we have eliminated the dependency on `msrest` altogether so you should no longer have this issue if you use that version. That version is scheduled for release early next month (February) but is a preview release if that is an issue for you. The official release of `12.15.0` should come a few weeks after that and will also remove the `msrest` dependency.

**Comment by nidhaloff** [comment]
> Hi @nidhaloff Nidhal, in our upcoming release, `12.15.0b1`, we have eliminated the dependency on `msrest` altogether so you should no longer have this issue if you use that version. That version is scheduled for release early next month (February) but is a preview release if that is an issue for you. The official release of `12.15.0` should come a few weeks after that and will also remove the `msrest` dependency.

Nice! Thanks
