### ISSUE TITLE
get_blob not returning similar version blob as the properties provided

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-python#28448]
- **Package Name**:  azure.storage.blob
- **Package Version**: 12.14.1
- **Operating System**: linux
- **Python Version**: 3.10.8

**Describe the bug**
When using the get_blob_client function of the container client, if you provide blob properties which include a version number. It does not return the blob of that version but instead the latest version of that blob.

**To Reproduce**
1. Make a storage account with 1 blob that has two versions.
2. Run the following
```
blobs = container_client.list_blobs(include=["versions"])
for blob in blobs:
    print(blob)
    blob_client = container_client.get_blob_client(blob)
    print(blob_client.get_blob_properties())
```

**Expected behavior**
The blob object that is returned has the same version ID as the properties that was provided.

**Comment by kashifkhan** [comment]
Thank you for the feedback @AWendland-CryptoCompare . We will investigate and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @AWendland-CryptoCompare Alex, the `get_blob_client` method does not extract the `version_id` from the provided properties and pass it into the new`BlobClient`. We only extract the name. To use the version, you will need to provide the `version_id` property to whichever operation you need to perform on the blob, `get_blob_properties` in your sample. Here is what that looks like in your sample:

```py
blobs = container_client.list_blobs(include=["versions"])
for blob in blobs:
    print(blob)
    blob_client = container_client.get_blob_client(blob)
    print(blob_client.get_blob_properties(version_id=blob.version_id))
```

**Comment by AWendland-CryptoCompare** [comment]
Hi Jacob, thanks for clearing this up. Just to check, if I were to run.
```
blobs = container_client.list_blobs(include=["versions"])
for blob in blobs:
    if not (blob.is_current_version or blob.version_id is None):
        container_client.delete_blob(blob)
```
This would delete the top level blob instead of the blob of that given version?
Would it be possible to make this a feature request? I personally find this behaviour a little counter-intuitive.

**Comment by jalauzon-msft** [comment]
Hi @AWendland-CryptoCompare Alex, you are correct that that code snippet would delete the root blob and not the specific version. To delete the version, you would still need to pass `version_id=blob.version_id` to `delete_blob`. I do agree that this does not seem very intuitive. Let me chat with the team and see what we can do about making this better.

I see two feature requests here. Both of which would help to make this more intuitive and doing both would provide the best experience.
- Operations that accept a `BlobProperties` input could read the version from the properties and operate on that version.
- We could add `version_id` as a client constructor parameter, like we do for `snapshot` and all operations with that client would be performed on that version. In this case `ContainerClient.get_blob_client` could also take a `version_id` to return a `BlobClient` that points the right version. This would be very similar to how we handle `snapshot` today which is a similar concept to version.

**Comment by AWendland-CryptoCompare** [comment]
Hi Jacob, thank you for getting back to me. I agree with you on all accounts, please let me know how feasible these would be and the outcome of your discussion. Thank you for being so helpful.

**Comment by vincenttran-msft** [comment]
Hi, this feature request was completed as part of [STG90](https://github.com/Azure/azure-sdk-for-python/pull/31498). Thanks for your suggestion, and with that I will close the issue.
