### ISSUE TITLE
Parameters of Python function QueueService.delete_message() do not match the code

### ISSUE THREAD

**Issue by Amir-Katz-RSA** [Azure/azure-sdk-for-python#28446]
The documentation says:
  `delete_message(queue_name, message_id, pop_receipt, timeout=None)`

but the function signature in the package (azure/storage/queue/_queue_client.py) is
   `delete_message(message, pop_receipt, **kwargs)`

When I changed my code to pass the message ID as the first parameter, the code worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed1f1bda-5060-2297-70bc-bfb7d00e8cd3
* Version Independent ID: bc4006ae-8f63-6fac-2d51-0c3f6dabd40e
* Content: [azure.storage.queue.queueservice.QueueService class](https://learn.microsoft.com/en-us/python/api/azure-storage-queue/azure.storage.queue.queueservice.QueueService?view=azure-python-previous&preserve-view=true&viewFallbackFrom=storage-py-v2#delete-message-queue-name--message-id--pop-receipt--timeout-none-)
* Content Source: [previous/docs-ref-autogen/azure-storage-queue/azure.storage.queue.queueservice.QueueService.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/previous/docs-ref-autogen/azure-storage-queue/azure.storage.queue.queueservice.QueueService.yml)
* GitHub Login: @VSC-Service-Account

**Comment by Amir-Katz-RSA** [comment]
and BTW, the first parameter in the documentation does not make sense - since this function is a method of QueueService, which is already bound to a specific queue, so specifying a queue_name is redundant.

**Comment by kashifkhan** [comment]
Thank you for the feedback @Amir-Katz-RSA , we will investigate and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @Amir-Katz-RSA, thanks for reaching out. The documentation you linked and created the issue on if the legacy documentation for the older versions of the SDK (`<=2.X.X`) but it seems you are using a later version (`>12.X.X`) which has a different structure. 

[Here](https://learn.microsoft.com/en-us/python/api/azure-storage-queue/azure.storage.queue.queueclient?view=azure-python) is a link to the current documentation for the `QueueClient` in `azure/storage/queue/_queue_client.py`. Additionally, [this landing page](https://learn.microsoft.com/en-us/python/api/overview/azure/storage?view=azure-python) for the Python Storage documentation can be helpful place to start to ensure you are looking at current documentation and not legacy. You can check the "Version" drop down on the left side to ensure you are using "Latest",

**Comment by Amir-Katz-RSA** [comment]
Thank you. I think the reason I got to the old pages is because the Google search sent me there...

**Comment by Amir-Katz-RSA** [comment]
All is good
