### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by inhere-ua** [Azure/azure-sdk-for-python#28440]
update the 'prerequisites' section to install azure-identity as it's not included by default with azure-ai-ml
pip install azure-identity

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0d7f9b-a80a-4da1-dcd6-1b61a7bbf134
* Version Independent ID: 70e9f892-5b42-b888-1881-5ba039c260b1
* Content: [Azure ML Package client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/ai-ml-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/ai-ml-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/ai-ml-readme.md)
* Service: **ml**
* GitHub Login: @paulshealy1
* Microsoft Alias: **paulsh**

**Comment by kashifkhan** [comment]
Thank you for your feedback @inhere-ua, we will investigate and get back to you asap. 

cc @azureml-github

**Comment by xiangyan99** [comment]
Thank you for your feedback.

Let's use https://github.com/Azure/azure-sdk-for-python/issues/29226 to track the issue.
