### ISSUE TITLE
receive_message should inidicate what happens if the queue is empty

### ISSUE THREAD

**Issue by jaybo** [Azure/azure-sdk-for-python#28443]
is the return value None?  is an Exception thrown?  I have no clue!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca4d7b94-75d7-236c-517a-9ce46628a292
* Version Independent ID: 6a535359-e284-bc61-5be4-ae2bbd968d87
* Content: [azure.storage.queue.QueueClient class](https://learn.microsoft.com/en-us/python/api/azure-storage-queue/azure.storage.queue.queueclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-storage-queue/azure.storage.queue.QueueClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-storage-queue/azure.storage.queue.QueueClient.yml)
* Service: **storage**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kashifkhan** [comment]
Hi @jaybo, thank you for your feedback. Do you have any sample code or repro that can help the team debug the issue? Is this for the storage SDK ?

**Comment by jaybo** [comment]
Yes.... this is for the Storage SDK.  The question is:  what happens if receive_message() is called on an empty queue?
```
queueClient = QueueClient.from_connection_string(connectionString, queueName)
queueClient.clear_messages() # no messages are in the queue
message = queueClient.receive_message() # does this return Null or trigger an exception?
```
**The documentation for `receive_message` should indicate what happens if the queue is empty.**  My experimentation seems to indicate it returns Null, but hey, what do I know.  I'm just a random schmo.

**Comment by jalauzon-msft** [comment]
Hi @jaybo Jay, thanks for colling this out. I created #28885 to address this. You are correct that an empty Queue will cause this method to return `None`. I have updated the documentation as well as the return type hint so VS Code now sees the return type properly.
