### ISSUE TITLE
Bold text at the same time with keywords

### ISSUE THREAD

**Issue by JavierSanchezCastro** [Azure/azure-sdk-for-python#28442]
Is there any way to write in bold with some keywords as "congratulations" (an animation appears in the mail)?

For the bold I use <b> in the html arg, but the "congratulations" word doesn't work. It works in plain_text argv, but I don't know how to put bold in plain_text arg

Ty!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc09cd1a-f9b1-29b1-f611-85091dc4f724
* Version Independent ID: a1ded1e8-071c-2336-34b5-e66491ebfb81
* Content: [azure.communication.email.EmailContent class](https://learn.microsoft.com/en-us/python/api/azure-communication-email/azure.communication.email.emailcontent?view=azure-python-preview)
* Content Source: [preview/docs-ref-autogen/azure-communication-email/azure.communication.email.EmailContent.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/preview/docs-ref-autogen/azure-communication-email/azure.communication.email.EmailContent.yml)
* GitHub Login: @VSC-Service-Account

**Comment by kashifkhan** [comment]
Thank you for the feedback @JavierSanchezCastro . We will investigate and get back to you.

cc @turalf

**Comment by navba-MSFT** [comment]
@JavierSanchezCastro Could you please let me know if the below snippet helps ?

```
from azure.communication.email import EmailContent

# Create an EmailContent object
email_content = EmailContent()

# Add the word "congratulations" in bold
email_content.text = "<b>Congratulations</b>"

# send the email with the bold text
# send_email(email_content)

```
You can also use the `html property` HTML tags in the email content.

```
email_content.html = "<p><b>Congratulations</b></p>"
```

**Comment by navba-MSFT** [comment]
@JavierSanchezCastro I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.
