### ISSUE TITLE
eventhub: TransportType.AmqpOverWebsocket error: local variable 'WebSocketAddressException' referenced before assignment

### ISSUE THREAD

**Issue by KevinMarquette** [Azure/azure-sdk-for-python#28453]
- **Package Name**: azure-eventhub             
- **Package Version**: 5.11.0
- **Operating System**: ubuntu:20.04
- **Python Version**: 3.9.16

**Describe the bug**
Getting this error when trying to call `EventHubProducerClient.create_batch` with `TransportType.AmqpOverWebsocket` and not having the `websocket-client` module pre-installed.

```
INFO     azure.eventhub._client_base:_client_base.py:596 operation has exhausted retry. Last exception: EventHubError("local variable 'WebSocketAddressException' referenced before assignment\nlocal variable 'WebSocketAddressException' referenced before assignment").
```

**To Reproduce**
1. verify `websocket-client` module is not installed `pip list`
2. call `EventHubProducerClient.create_batch()`

```
from azure.eventhub import EventHubProducerClient, TransportType

client = EventHubProducerClient(
    fully_qualified_namespace=fully_qualified_name_space,
    eventhub_name=event_hub_name,
    credential=credential,
    transport_type=TransportType.AmqpOverWebsocket,
    logging_enable=False,
)
batch = client.create_batch()
```

**Expected behavior**

I expected to create a new batch or a concise error indicating that I needed to install the `websocket-client` module.

**Screenshots**
Error Message from pytest:
```
=========================== short test summary info ============================
FAILED project_integration_test.py::test_event_hub_send_data - azure.eventhub.exceptions.EventHubError: local variable 'WebSocketAddressException' referenced before assignment
local variable 'WebSocketAddressException' referenced before assignment
```

**Additional context**

There is an obvious bug here that is hiding the module not found error:
https://github.com/swathipil/azure-sdk-for-python/blob/69d88e04817a1cc02dad78190b30b3c6145a2672/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py#L730

It tries to catch an exception that is not loaded resulting in the confusing error message. If this was handled correctly, we would get a better error indicating that 'websocket' could not be loaded. While this is closer, it still is not specific enough to indicate that `websocket-client` is needed. It should also not be retrying for module import errors.

I am making the assumption that `websocket-client` is intended to be optional is why pip is not installing it as a dependency.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment]
Thank you @KevinMarquette. We are able to repro this on our side and will update this issue when we have a fix out.

**Comment by kashifkhan** [comment]
Hi @KevinMarquette , we have released a new patch version which will show the error message properly. Thank you for bringing this to our attention
