### ISSUE TITLE
Reading MLTable file with Filter field - "filter" field was unexpected

### ISSUE THREAD

**Issue by TomSB1423** [Azure/azure-sdk-for-python#28463]
**Is your feature request related to a problem? Please describe.**
I would like to be able to apply a filter on the mltable object, save it, then load it again. This would be useful for an two individual components, one for preprocessing and the other for computation when using AzureML pipelines.
However, even if you are not interested in pipeline, this completly inhibits your ability to load previously saved MLTable objects with the filter attribute.

When loading the mltable with the filter applied, your YAML schema gives the error:
`ValidationError: "Additional properties are not allowed ('filter' was unexpected)">], <unset>, <unset>, <unset>, (), None)`

**Describe the solution you'd like**
I would like the YAML schema to include the filter property and allow me to be able to load my previously saved mltable data.
This is even described in your documentation [here](https://learn.microsoft.com/en-gb/azure/machine-learning/how-to-mltable?tabs=cli%2Cadls#authoring-mltable-files)

Example:
```
import mltable
# Preprocessing pipeline component
tbl = mltable.load("C:\example")
tbl = tbl.filter("id < 5")
tbl.save("C:\example_new")
# Load mltable for computation pipeline component
tbl = mltable.load("C:\example_new") # Gives error
```

**Describe alternatives you've considered**
Could cut out saving the mltable, however in some cases this is unavoidable.

**Comment by FeiDeng** [comment]
Please try mltable 1.1.0 this bug should be fixed.

**Comment by TomSB1423** [comment]
Thank you. The filter is now included inside the schema. 
Could you please update the [documentation](https://learn.microsoft.com/en-us/azure/machine-learning/reference-yaml-mltable) and provide more detailed documentation for valid expressions are required on this filter method [here ](https://learn.microsoft.com/en-us/azure/machine-learning/v1/how-to-create-register-datasets#filter-datasets-preview) similar to the [docs on datasets.filter() method ](https://learn.microsoft.com/en-us/azure/machine-learning/v1/how-to-create-register-datasets#filter-datasets-preview) in v1.

### Introduces a new bug
However, this also introduces a new error: `Failed with execution error: error in streaming from input data sources` regarding the path pattern. Running the same example produces the following file pattern inside the newMLTable:
`pattern: file://C:\\example_new\\file:\\C:\\example\\*.csv`

This file path is incorrect, and therefore the MLTable cannot be converted to pd.DataFrame

**Comment by navba-MSFT** [comment]
@TomSB1423 @azureml-github, https://github.com/orgs/Azure/teams/azure-ml-sdk. Could you please look into this once you get a chance ?

**Comment by FeiDeng** [comment]
Yes. We are working on a fix.

**Comment by FeiDeng** [comment]
Please try mltable 1.2.0. It should fix the save-load issue.
