### ISSUE TITLE
 ARM template / Python SDK to enable Replication on VM

### ISSUE THREAD

**Issue by raviteja59** [Azure/azure-sdk-for-python#2847]
what  are Python SDK’s/ ARM templates  I can use to enable replication and add replication policies to Recovery Services vault ?  is there a testcase which we can look at  for azure – azure DR.

**Comment by lmazuel** [comment]
@DheerendraRathor ?

**Comment by sujayt** [comment]
Hi Ravi,

We do not have sample ARM templates for Azure to Azure scenario as of now. We plan to publish the sample ARM templates for "Azure VM replication" in a few weeks.

You can use the REST APIs from any client for your scenarios or PowerShell cmdlets to automate your scenarios.

https://docs.microsoft.com/en-us/rest/api/site-recovery/ 
https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-powershell

Note that both REST APIs/PowerShell are available for unmanaged disks only as of now. Managed disk VMs will be supported via REST APIs/PowerShell in a few weeks.


Thanks,
Sujay

**Comment by raviteja59** [comment]
Thanks @sujayt
