### ISSUE TITLE
Cannot set timeout when calling get_subscription_receiver with the NEXT_AVAILABLE_SESSION option

### ISSUE THREAD

**Issue by SBFrancies** [Azure/azure-sdk-for-python#28495]
- **Package Name**:  azure-servicebus
- **Package Version**: 7.8.2
- **Operating System**: Windows 11
- **Python Version**: 3.10.8

**Describe the bug**
Apologies if I have missed something but it currently does not seem to be possible to set the length of time that the `get_subscription_receiver` method on the `ServiceBusClient` class will wait for a session to be available. Unless I have missed something it always times out after 65 seconds with an `OperationTimeoutError` with the the following message:

> AMQP error occurred: (VendorLinkDetach('com.microsoft:timeout: The operation did not complete within the allotted timeout of 00:01:05. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions .

I can't find anything documenting this behaviour.

**To Reproduce**
1. Set up a service bus namespace with a topic.
2. Add a subscription to the topic with sessions enabled.
3. Run the following code against the empty topic:
```
service_bus_client = ServiceBusClient(<service_bus_namespace>, DefaultAzureCredential())

receiver = service_bus_client.get_subscription_receiver(
        topic_name=<topic_name>,
        session_id=NEXT_AVAILABLE_SESSION,
        subscription_name<subscritpion_name>)
```
4. After 65 seconds the error is thrown if no messages (with sessions) are added to the topic.

**Expected behavior**
Either the code should wait for a message (with a session) to come in and create the receiver or timeout after a documented or defined period of time.

**Additional context**
We are trying to set up a topic which will have many, short lived sessions. At certain points the topic will be empty and we would like to be able to configure the code to a reasonable timeout period rather than handle an exception every 65 seconds.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment]
Hi @SBFrancies, there is no option to specify the accept session wait time explicitly in the client. It's a setting on the service itself for 65 seconds and if it can't find a session in that time, forces a disconnect. The solution would be to implement retry logic in your application to handle the exception and then re-attempt for the session after a particular wait period.

**Comment by SBFrancies** [comment]
Thanks for the advice
