### ISSUE TITLE
[AzureML v2] - Unable to create an AzureML compute cluster with No Public IP nodes (on private endpoint)

### ISSUE THREAD

**Issue by jadhosn** [Azure/azure-sdk-for-python#28496]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.1.0
- **Operating System**: Ubuntu 20.04.5 LTS
- **Python Version**: Python 3.10.6

**Describe the bug**
Trying to create an AzureML compute cluster, on a private endpoint, with no public IPs enabled. 
Using [this code snippet](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-secure-training-vnet?tabs=python%2Crequired#compute-instancecluster-with-no-public-ip) in Azure's docs. 

```python
from azure.ai.ml.entities import AmlCompute

# specify aml compute name.
cpu_compute_target = "cpu-cluster"

try:
    ml_client.compute.get(cpu_compute_target)
except Exception:
    print("Creating a new cpu compute target...")
    compute = AmlCompute(
        name=cpu_compute_target, size="STANDARD_D2_V2", min_instances=0, max_instances=4,
        vnet_name="yourvnet", subnet_name="yoursubnet", enable_node_public_ip=False
    )
    ml_client.compute.begin_create_or_update(compute).result()
```

>Traceback (most recent call last):
  File "/home/azureuser/cloudfiles/code/[REDACTED]/src/aml_utils.py", line 16, in create_compute
    cpu_cluster = ml_client.compute.get(compute_target_name)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/_telemetry/activity.py", line 259, in wrapper
    return f(*args, **kwargs)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/operations/_compute_operations.py", line 78, in get
    rest_obj = self._operation.get(
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/_restclient/v2022_01_01_preview/operations/_compute_operations.py", line 577, in get
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'Not Found'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/entities/_compute/aml_compute.py", line 117, in __init__
    super().__init__(
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/entities/_compute/compute.py", line 55, in __init__
    super().__init__(name=name, description=description, **kwargs)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/entities/_resource.py", line 60, in __init__
    super().__init__(**kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

Pip list for Azure's package: 
>azure-ai-ml                  1.1.0
azure-common                 1.1.28
azure-core                   1.26.1
azure-graphrbac              0.61.1
azure-identity               1.7.0
azure-mgmt-authorization     2.0.0
azure-mgmt-containerregistry 10.0.0
azure-mgmt-core              1.3.2
azure-mgmt-keyvault          10.1.0
azure-mgmt-resource          21.2.1
azure-mgmt-storage           19.1.0
azure-storage-blob           12.13.0
azure-storage-file-datalake  12.8.0
azure-storage-file-share     12.10.1
azureml-core                 1.47.0
azureml-dataprep             4.5.7
azureml-dataprep-native      38.0.0
azureml-dataprep-rslex       2.11.4
azureml-mlflow               1.47.0
msrestazure                  0.6.4
opencensus-ext-azure         1.1.7

**To Reproduce**
Steps to reproduce the behavior, run the following code: 
1. Configure your `ml_client` to a private endpoint workspace
2. Create your aml compute and with no public ip access
3. Run the following snippet: 
```python
compute = AmlCompute(
        name="tmp-cluster", size="STANDARD_D13", min_instances=0, max_instances=2,
        vnet_name="myvnet", subnet_name="mysubnet", enable_node_public_ip=False)
```

Notes: my `ml_client` is already linked to a private endpoint workspace as mentioned [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-secure-training-vnet?tabs=python%2Crequired#compute-instancecluster-with-no-public-ip). 

Is it possible I'm using the wrong name for the vnet and subnet?
![image](https://user-images.githubusercontent.com/17963295/214876801-6b00ea27-4b28-4e66-87b2-7efd843f7b88.png)

**Expected behavior**
The same snippet should create an NPIP compute on the respective vnet and subnet

**Screenshots**
N/A

**Additional context**
N/A

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@azureml-github, https://github.com/orgs/Azure/teams/azure-ml-sdk. Could you please look into this once you get a chance ? Thanks in advance.

**Comment by nthandeMS** [comment]
@jadhosn Thank you for the feedback, we are looking into this.

**Comment by nthandeMS** [comment]
@jadhosn We are still looking into this. Given the nature of the issue, it does not appear to be caused by the SDK, but rather an issue at the backend. I will keep you posted.

**Comment by nthandeMS** [comment]
@jadhosn The `enable-node-public-ip` parameter was introduced in v1.3.0 of the SDK. Please update to this version or higher to create the cluster.

Our documentation is outdated regarding the creation of the compute cluster. Please try the following snippet instead:

```
from azure.ai.ml.entities import AmlCompute, NetworkSettings

# Specify the compute name

cpu_compute_target = "cpu-cluster"

# Specify the compute network settings
network_settings = NetworkSettings(vnet_name="yourvnet", subnet="yoursubnet")

compute = AmlCompute(
    name=cpu_compute_target,
    size="STANDARD_D2_V2",
    min_instances=0,
    max_instances=4,
    network_settings=network_settings,
    enable_node_public_ip=False,
)
ml_client.compute.begin_create_or_update(compute).result()
```

**Comment by jadhosn** [comment]
@nthandeMS do you support startup scripts as well through the SDK in 1.3.0?

**Comment by nthandeMS** [comment]
@jadhosn Yes, we have support for startup scripts since 1.0.0. Here is an example snippet:

```
from azure.ai.ml.entities import ComputeInstance, SetupScripts, ScriptReference

creation_script = ScriptReference(path="Users/yourusername/creation.sh", command="echo Created! > startup.txt", timeout_minutes=15)
startup_script = ScriptReference(path="Users/yourusername.creati", command="echo Started! >> startup.txt", timeout_minutes=10)
setup_scripts = SetupScripts(startup_script=startup_script, creation_script=creation_script)

compute_instance = ComputeInstance(name='my-ci-setup-script', size='STANDARD_DS3_v2', setup_scripts=setup_scripts)
                                                   
ml_client.compute.begin_create_or_update(compute_instance)
```

**Comment by jadhosn** [comment]
@nthandeMS Is it possible for specify a vnet from another resource group? We share the same vnet across different resource groups
![image](https://user-images.githubusercontent.com/17963295/221018720-c4f10f87-bb41-4ddf-85fc-06b39fa1d9c3.png)

**Comment by nthandeMS** [comment]
@jadhosn This is by design; compute resources reference a subnet within the same resource group. Do you have an example of where you were able to connect a Compute to a resource outside of the compute's resource group?

**Comment by jadhosn** [comment]
> @jadhosn This is by design; compute resources reference a subnet within the same resource group. Do you have an example of where you were able to connect a Compute to a resource outside of the compute's resource group?

Yes! the same snippet can connect to a vnet outside the compute's resource group on SDK v1.0.0

**Comment by nthandeMS** [comment]
@jadhosn I've investigated further and it is true that you should be able to use a vnet in a different resource group on the UI and through direct REST API calls.Howver, I still don't see how you could do this through v1.0.0 of `azure-ai-ml`.  How were you defining which vnet to use on the Compute? Were you using the `NetworkSettings` class, or something else?

**Comment by nthandeMS** [comment]
The bottom line is that we would need a code change to connect to a vnet outside of the compute's resource group. This is a gap in functionality between the different interfaces for AzureML, and we apologize for the inconvenience. We can change this, but it would take some time.

**Comment by jadhosn** [comment]
> The bottom line is that we would need a code change to connect to a vnet outside of the compute's resource group. This is a gap in functionality between the different interfaces for AzureML, and we apologize for the inconvenience. We can change this, but it would take some time.

Is it possible through the CLI?

**Comment by nthandeMS** [comment]
The CLI is dependent on the SDK, so the behavior of the SDK will be passed through to the CLI.

In your previous version, how did you define which resource group the vnet was in when it was different from the Compute's resource group? The NetworkSettings class does not contain a resource group parameter.

**Comment by jadhosn** [comment]
> The CLI is dependent on the SDK, so the behavior of the SDK will be passed through to the CLI.
> 
> In your previous version, how did you define which resource group the vnet was in when it was different from the Compute's resource group? The NetworkSettings class does not contain a resource group parameter.

I did not, by simply providing the vnet and subnet, the compute would create without issue. The same snippet running on 1.0.0 should work if you want to reproduce on your end.

**Comment by nthandeMS** [comment]
@jadhosn After some conversations on our end, we are going to fix this issue so that there's no difference between what you can do with 1.0.0 and our later versions. We will fix this by April. In the meantime, please use the Azure Machine Learning Studio to create computes with vnets in different resource groups.

**Comment by Dave-Bouchard** [comment]
Hi,

Do you have somes news about this issue?

Thanks
