### ISSUE TITLE
Unable to consume events using interactive browser credential

### ISSUE THREAD

**Issue by malthe** [Azure/azure-sdk-for-python#28498]
- **Package Name**:  azure-eventhub
- **Package Version**: 5.11.1
- **Operating System**: MacOS
- **Python Version**: Python 3.9

**Describe the bug**

With an `InteractiveBrowserCredential` credential I get the following error consuming via `azure.eventhub.aio.EventHubConsumerClient`:

```python
azure.eventhub._pyamqp.aio._session_async:Unable to attach new link: ValueError('Invalid link')
```

This problem goes away if I use `EventHubSharedKeyCredential`.

I am "Owner" on the event hub resource.

**To Reproduce**
1. Create event hub.
2. Connect via `InteractiveBrowserCredential`.

**Expected behavior**
No error.

**Screenshots**
N/A

**Additional context**
Digging deeper into the exception origin, I see the following error message:
```
Cannot get source or target. Detaching link
```
This happens in [_link_async.py](https://github.com/Azure/azure-sdk-for-python/blob/21c5a56efcfb0a376f3d4d2e575814adb1590248/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py#L170).

Note that within the same program run, the "happy path" of that code block is also visited frequently.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment]
Hi @malthe can you provide us some sample code for us to be able to repro and help you better :)

**Comment by malthe** [comment]
Here's the program I am using to test this – more or less taken directly from the Microsoft example page:
```python
import logging

from datetime import datetime
from os import environ as env

from asyncio import run
from azure.eventhub.aio import EventHubConsumerClient
from azure.eventhub.aio import EventHubSharedKeyCredential
from azure.identity.aio import DefaultAzureCredential
from azure.identity import InteractiveBrowserCredential
from azure.identity import TokenCachePersistenceOptions
from azure.identity.aio import SharedTokenCacheCredential
from azure.identity.aio import ChainedTokenCredential
from azure.storage.blob.aio import ContainerClient

logging.basicConfig()
logging.getLogger().setLevel("INFO")
logging.getLogger("azure").setLevel("WARN")


credential_token_cache_name = env.get("CREDENTIAL_TOKEN_CACHE_NAME")
if credential_token_cache_name:
    options = TokenCachePersistenceOptions(name=credential_token_cache_name)
    credential = ChainedTokenCredential(
        SharedTokenCacheCredential(cache_persistence_options=options),
        InteractiveBrowserCredential(cache_persistence_options=options),
    )
else:
    credential = DefaultAzureCredential()


async def on_event(sc_client, partition_context, event):
    # Print the event data.
    print(
        'Received the event: "{}" from the partition with ID: "{}"'.format(
            event.body_as_str(encoding="UTF-8"), partition_context.partition_id
        )
    )

    # Update the checkpoint so that the program doesn't read the events
    # that it has already read when you run it next time.
    await partition_context.update_checkpoint(event)


async def main():
    # Create a consumer client for the event hub.

    shared_access_policy = env.get("EVENT_HUB_SAS_POLICY")
    shared_access_key = env.get("EVENT_HUB_SAS_KEY")

    eh_client = EventHubConsumerClient(
        fully_qualified_namespace=env["EVENT_HUB_FULLY_QUALIFIED_NAMESPACE"],
        eventhub_name=env["EVENT_HUB_NAME"],
        consumer_group="$Default",
        credential=(
            EventHubSharedKeyCredential(shared_access_policy, shared_access_key)
            if shared_access_policy and shared_access_key else credential
        )
    )

    sc_client = ContainerClient(
        account_url=env["STORAGE_ACCOUNT_URL"],
        container_name=env["CONTAINER_NAME"],
        credential=credential,
    )

    def event_handler(*args):
        return on_event(sc_client, *args)

    async with eh_client:
        await eh_client.receive(on_event=event_handler, starting_position="-1")

    # Close credential when no longer needed.
    await credential.close()


if __name__ == "__main__":
    run(main())
```

**Comment by kashifkhan** [comment]
Thank you for the repro @malthe . I was able to confirm a couple of things happening here:

* Azure identity async doesn't support `InteractiveBrowserCredential` so you won't be able to use a sync version of the token while making async event hub calls
* I was able to use sync azure identity `InteractiveBrowserCredential` and sync event hub libraries just fine, both to send and receive events.

**Comment by malthe** [comment]
@kashifkhan I don't think that's necessarily the issue here.

I wrote the following wrapper:
```python
class AioCredentalWrapper:
    def __init__(self, credential):
        self._credential = credential

    async def get_token(self, *scopes: str, **kwargs):
        loop = get_event_loop()
        return await loop.run_in_executor(
            None,
            lambda: self._credential.get_token(*scopes, **kwargs),
        )
```

Same exact error – and `get_token` _does_ get invoked and the calling code receives an access token.

**Comment by kashifkhan** [comment]
> @kashifkhan I don't think that's necessarily the issue here.
> 
> I wrote the following wrapper:
> 
> ```python
> class AioCredentalWrapper:
>     def __init__(self, credential):
>         self._credential = credential
> 
>     async def get_token(self, *scopes: str, **kwargs):
>         loop = get_event_loop()
>         return await loop.run_in_executor(
>             None,
>             lambda: self._credential.get_token(*scopes, **kwargs),
>         )
> ```
> 
> Same exact error – and `get_token` _does_ get invoked and the calling code receives an access token.

@malthe can you also send me the snippet of how you are using the wrapper + the SDK please ?

**Comment by malthe** [comment]
I am using it like so:
```python
credential = AioCredentalWrapper(
    InteractiveBrowserCredential()
)
```

And simply putting that credential into `EventHubConsumerClient` as the `credential` keyword argument.

**Comment by kashifkhan** [comment]
Hi @malthe, 

interestingly enough, modifying one of our samples I was able to get it working for both sends and receives on the async side. This is the snippet that worked for me on  python 3.8 and python 3.9 on WSL

As such however azure-identity async doesn't support it officiall.

```python
import asyncio
import os
from azure.eventhub.aio import  EventHubProducerClient, EventHubConsumerClient
from azure.identity import InteractiveBrowserCredential
from azure.eventhub import EventData


class AioCredentalWrapper:
    def __init__(self, credential):
        self._credential = credential

    async def get_token(self, *scopes: str, **kwargs):
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None,
            lambda: self._credential.get_token(*scopes, **kwargs),
        )


fully_qualified_namespace = ''
eventhub_name = ''




async def run():
    credential = AioCredentalWrapper(InteractiveBrowserCredential())
  
    producer = EventHubProducerClient(fully_qualified_namespace=fully_qualified_namespace,
                                          eventhub_name=eventhub_name,
                                          credential=credential)

    consumer = EventHubConsumerClient(fully_qualified_namespace=fully_qualified_namespace,
                                          eventhub_name=eventhub_name, consumer_group="$Default",
                                          credential=credential)

    async def on_event(pid, data):
      print(data.message)

    async with producer:
            event_data_batch = await producer.create_batch()
            while True:
                try:
                    event_data_batch.add(EventData('Message inside EventBatchData'))
                except ValueError:
                    # EventDataBatch object reaches max_size.
                    # New EventDataBatch object can be created here to send more data.
                    break
            await producer.send_batch(event_data_batch)
    
    async with consumer:
      await consumer.receive(
        on_event=on_event,
        starting_position="-1"
      )


asyncio.run(run())
print('Finished sending.')
```

**Comment by malthe** [comment]
I can't get your example program to work either – same error.

This is on MacOS Ventura with the system-provided Python 3.9.6.

```bash
$ pip freeze
aiohttp==3.8.3
aiosignal==1.3.1
async-timeout==4.0.2
asyncio==3.4.3
attrs==22.2.0
azure-core==1.26.2
azure-eventhub==5.11.1
azure-identity==1.12.0
azure-storage-blob==12.14.1
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==39.0.0
fastavro==1.7.0
frozenlist==1.3.3
idna==3.4
isodate==0.6.1
msal==1.20.0
msal-extensions==1.0.0
msrest==0.7.1
multidict==6.0.4
oauthlib==3.2.2
portalocker==2.7.0
pycparser==2.21
PyJWT==2.6.0
requests==2.28.2
requests-oauthlib==1.3.1
six==1.16.0
typing_extensions==4.4.0
uamqp==1.6.3
urllib3==1.26.14
yarl==1.8.2
```

**Comment by kashifkhan** [comment]
This is quite interesting, I did a few tests to make sure I had my bases covered

I ran my script on Python 3.8, 3.9 and 3.10 on the following environments (every test was run with `AioCredentialWrapper` and then with just the `InteractiveBrowserCredential`). I did a mix of work and personal machines. A green check mark means it worked using AioCredentialWrapper but not using InteractiveBrowserCredential directly.

I set up the env using only `pip install azure-eventhub azure-identity` which gave me the following pip freeze output

```
azure-core==1.26.2
azure-eventhub==5.11.1
azure-identity==1.12.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.0.1
cryptography==39.0.0
idna==3.4
msal==1.20.0
msal-extensions==1.0.0
portalocker==2.7.0
pycparser==2.21
PyJWT==2.6.0
pywin32==305
requests==2.28.2
six==1.16.0
typing_extensions==4.4.0
urllib3==1.26.14
```

|   |  py 3.8 | py 3.9 | py 3.10 |
|---|---|---|---|
| Windows  | ✅   | ✅  | ✅  |
|  WSL Ubuntu 22.04 |  ✅ |  ✅ |  ✅ |
|  Windows Personal |  ✅ | ✅  | ✅  |
|  Fedora 37 Personal |  ✅ |  ✅ |  ✅ |
| MacOS M1 Personal  |  ✅ |  ✅ |  ✅ |

**Comment by malthe** [comment]
I just tried a fresh install on a Windows machine running Python 3.10 using your `pip freeze` output – with a brand new event hub resource and topic.

I get the same error:

> Unable to attach new link: ValueError('Invalid link')

**Comment by kashifkhan** [comment]
@malthe your IAM on the EH is `Azure Event Hubs Data Owner` ?

**Comment by malthe** [comment]
Yes I am Owner on the resource. On the RG as well.

man. 30. jan. 2023 kl. 19.52 skrev Kashif Khan ***@***.***>:

**Comment by kashifkhan** [comment]
I asked a colleague to test out my snippet on their machine as well. It started working for both sync and async as soon as they set their work email as data owner to the Event hub and namespace. Before they did that, the error showing up was `azure.eventhub.exceptions.ConnectionLostError: Unauthorized access. 'Send' claim(s) are required to perform this operation`.

**Comment by malthe** [comment]
I have the following (from "View my access"):

<img width="774" alt="image" src="https://user-images.githubusercontent.com/26405/215606756-fac816fe-4bf5-49d4-b80f-3a99b97ea853.png">

**Comment by kashifkhan** [comment]
@malthe can you add this one specifically please `Azure Event Hubs Data Owner` ?

**Comment by malthe** [comment]
Adding that role did the trick. I thought being Owner was enough to implicitly be allowed data access.

For future readers of this issue, wrapping the `InteractiveBrowserCredential` in a simple async wrapping class does work.
