### ISSUE TITLE
Support for Media Services

### ISSUE THREAD

**Issue by activatedgeek** [Azure/azure-sdk-for-python#285]
Does the Python SDK have support for [Media Services](http://azure.microsoft.com/en-us/services/media-services/)? I could not find it anywhere in the documentation though. 

Is it in the pipeline?

**Comment by huguesv** [comment]
It doesn't have support as of now, and it wasn't in the pipeline for the upcoming months.  I'll tag this as a feature and we'll prioritize.

If you need to use media services now, it looks like there are a few non .NET alternatives, such as PHP, Java and Node.js, or you can use the REST API directly.
https://msdn.microsoft.com/en-us/library/azure/hh973629.aspx#get_started

Of course, if you'd like to contribute support for it, we'll be happy to help you!

**Comment by activatedgeek** [comment]
Yes, anyways I'd have to implement on my own using the REST API, I would prefer to continue on the existing SDK.

**Comment by activatedgeek** [comment]
Can somebody help me get started?

**Comment by activatedgeek** [comment]
I am using `OAuth` to get access to an `Azure Media Services Account`. Using `POST` request (from Python requests library) to the URL `https://wamsprodglobal001acs.accesscontrol.windows.net/v2/OAuth2-13`, I get the appropriate access token. My next request is to create an `Asset` to the URL `POST https://media.windows.net/API/Assets`. I am setting the following headers:
```python
	"Authorization" : "Bearer "+response['access_token'],
	"Accept" : "application/json;odata=verbose",
	"x-ms-version" : "2.8",
	"DataServiceVersion" : "3.0", 
	"MaxDataServiceVersion" : "3.0",
	"Content-type" : "application/json;odata=verbose",
	"Host": "media.windows.net"
```
If I allow automatic redirects, this obviously doesn't work. It gave me a permanent redirect(301) to a new URL. Now I am trying `POST newURL/Assets` but I am getting an error of infinite redirects from the new URL.

And ideas?

**Comment by activatedgeek** [comment]
Hey @huguesv,
I am successfully able to create a new `Media Asset`, added the `Access Policy` ( `{"Permissions" : 1}`) to read, then a `Locator` which returns a `Path` in response, of the form, `http://<account>.streaming.mediaservices.windows.net/{GUID}/`. I have my blobs already uploaded in storage containers as `BlockBlobs`. Now, how do I link this asset to the given blob and generate the full streaming URL?

**Comment by huguesv** [comment]
Sorry, I have absolutely zero experience with the media services.  I'll ask to see if I can locate a person from that team.

**Comment by mingfeiy** [comment]
Hi @activatedgeek,

This article shows you how to create a streaming locator for your asset: https://msdn.microsoft.com/en-us/library/azure/jj129578.aspx#create_origin_URL_for_streaming. To reference a Smooth Streaming origin URL in a streaming media player, you must append the Path property with the name of the Smooth Streaming manifest file, followed by "/manifest". For example, using the origin URL shown in the previous example, the actual URL used by smooth streaming clients would be http://media.windows.net/52034bf6-dfae-4d83-aad3-3bd87dcb1a5d/samplevid.ism/manifest. And for HLS clients, the example would be http://media.windows.net/52034bf6-dfae-4d83-aad3-3bd87dcb1a5d/samplevid.isml/manifest(format=m3u8-aapl).

Meanwhile, your video file needs to be encoded as a multi-bitrates Mp4, if you want to have your asset dynamically packed on the fly to multiple streaming protocols. You will need 1 streaming reserved unit for this.

You can email me directly at yanmf@microsoft.com if you can't figure things out.

**Comment by activatedgeek** [comment]
@mingfeiy Hello, I have mailed you but haven't heard back. It would be great if you could reply as I need to get going fast.

**Comment by mingfeiy** [comment]
@activatedgeek I am sorry but I didn't receive any email. Could you forward the email to my personal email as well: Mingfeiy@gmail.com.

**Comment by lmazuel** [comment]
Hi @activatedgeek ,

Have you found the answers you needed with the help of @mingfeiy? Could we close the bug?
Thank you!

**Comment by lmazuel** [comment]
I close this bug for inactivity. Feel free to reopen it or a new one if necessary!
