### ISSUE TITLE
Missing docs on timeout in azure-storage

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#28506]
- **Package Name**: azure-storage-blob
- **Package Version**: [12.14.1]
- **Operating System**: OSX
- **Python Version**: 3.8

**Describe the bug**
The docs about timeout parameters, for instance in

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.14.1/azure.storage.blob.html#azure.storage.blob.BlobClient.upload_blob

does not describe the default value and what kind of behaviour to expect if left unset.

**Comment by jalauzon-msft** [comment]
Hi @andrea-cassioli-maersk Andrea, thanks for bringing up the issue. I agree that the documentation for the `timeout` parameter could be improved. We will work on getting a PR to improve this.

In case you wanted some more info now, this `timeout` parameter is the server-side timeout for the operation. The default and maximum value is usually 30 seconds for most operations, but upload/download have different timeouts that are based on blob size. See the [service documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations) for more info. This is not a client-side timeout and the client does not do anything with it. To configure client-side timeouts, see our [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/README.md#other-client--per-operation-configuration).
