### ISSUE TITLE
CosmosDB command line is unable to create unlimited collections

### ISSUE THREAD

**Issue by slyons** [Azure/azure-sdk-for-python#2850]
When using commands such as `az cosmosdb collection create --resource-group-name {myrg} --name {myaccount} --collection-name {mycollname} --db-name {mydb} --partition-key-path "/account"` the collection is always created as "Fixed", with no option to specify an "unlimited" variety.

**Comment by lmazuel** [comment]
Hi @slyons 
Please open this issue in the CLI tracker:
https://github.com/Azure/azure-cli/issues

Thank you,
