### ISSUE TITLE
Ref docs issue

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-python#28514]
Error:
> Mode                 LastWriteTime         Length Name                                                                                                                           
> d-----         1/27/2023   6:24 PM                docfx_yaml                                                           
> -a----         1/27/2023   6:05 PM          10252 build.ps1                                                            
> -a----         1/27/2023   6:05 PM           3608 conf.py.tpl                                                          
> -a----         1/27/2023   6:05 PM            987 generate_xrefmap.py                                                  
> -a----         1/27/2023   6:05 PM          10545 GetPackageCode.ps1                                                   
> -a----         1/27/2023   6:05 PM              0 index.rst                                                            
> -a----         1/27/2023   6:05 PM           3605 InstallPackage.ps1                                                   
> -a----         1/27/2023   6:05 PM            899 param_schema.json                                                    
> -a----         1/27/2023   6:05 PM          28997 PyCommon.ps1                                                         
> <CI INFO>: Running Sphinx build...
> <Warn Filter> Running commandline: & 'C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\sphinx-build.exe' . _build -b yaml 2>&1
> ##[error]The operation was canceled.

For more details check here:
https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=343296&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
This issue appears to have been caused by transient factors. Thanks!
