### ISSUE TITLE
Unexpected retry behavior in `ServiceBusReceiver.receive_messages` with `max_wait_time`

### ISSUE THREAD

**Issue by trylle** [Azure/azure-sdk-for-python#28522]
- **Package Name**: azure-servicebus (async API)
- **Package Version**: 7.8.1
- **Operating System**: Windows 10 19045.2486, macOS Monterey 12.6, Linux-5.4.0-1090-azure-x86_64-with-glibc2.29
- **Python Version**: 3.10.2, 3.9.12, 3.8.10

**Describe the bug**
The `max_wait_time` parameter of `ServiceBusReceiver.receive_messages` affects the retry behaviour of the operation. If a transient error occurs during the operation and there is not enough time to retry, the error is passed on to the user, even if it is perfectly recoverable. In our case, this meant our service would occasionally exit and restart with varying level of impact.

This behaviour was, to us, unexpected and troublesome to diagnose, because:
1. The retry behaviour becomes a leaky abstraction, rather than an automated and transparent affair
2. The documentation does not state the parameter affects retry, although it is arguably obvious in hindsight
3. When a transient error is given up on, the errors are difficult to decipher and understand:
    1. Given that many Azure-related loggers can be highly verbose, one has to know which modules should be logged ahead of time at what severity level. It was not practical for us to enable `DEBUG`-level logging for all Azure packages in the production environment. The levels we usually log (`WARNING` and above) did not assist in determining what the problem was. The warnings included `LinkDetach('ErrorCodes.UnknownError')`, which were pretty opaque. At log level `INFO`, the only hint indicating the bad retry behavior is that you will get an `operation has timed out` message
    2. The exception thrown by `receive_messages` was an obscure `azure.servicebus.exceptions.ServiceBusConnectionError: Service Bus has encountered an error. Error condition: ErrorCodes.UnknownError.`. In other cases, we've seen `uamqp.errors.MessageHandlerError: Message Receiver Client is in an error state. Please confirm credentials and access permissions. See debug trace for more details.`. The exceptions themselves do not give any information about the retry state

After rewriting our code not to use `max_wait_time` at all, the stability has been much improved.

**To Reproduce**
1. Loop on `receive_messages` with e.g. `max_wait_time=0.5`
2. Wait for or trigger a transient error (by OS-dependent mechanism) on the SB connection
3. Observe that `receive_messages` throws a vague exception

**Expected behavior**
While the behavior as-is may make sense for write-operations with a user-specified timeout, IMHO it does not for read (at least not where `max_wait_time` is concerned).

I suggest:
1. `receive_messages` should return whatever messages it received within `max_wait_time`, if any, and not throw an exception if the operation can be retried according to policy
2. Service Bus should keep track of retry internally and transparently, and only cause `receive_messages` to throw an exception when it has fully given up
3. The exception we do potentially get should include some details on what specifically failed (e.g. not `UnknownError` or generic error state messages). Retry status should be more visible to aid in troubleshooting, especially when it gives up

**Comment by l0lawrence** [comment]
Hi @trylle would you be able to try using the most recent version of azure-servicebus (7.11.0) and see if this problem persists? We introduced pyamqp this year as a fully python amqp stack replacement for uamqp in version 7.10.0 and above.

**Comment by ebuna** [comment]
I'm not the submitter, but have tested the latest version (7.11.1) and it now appears to be ignoring the `max_wait_time` parameter completely, unless I am misunderstanding what that parameter is meant to do. Here's a sample of what debug logging outputs from my application with the `max_wait_time` in `receive_messages` set to 10 (I've tried a variety of settings ranging from 10 to 60 and it behaves the same way each time. I've also tried omitting it from the call, also the same behavior). Happy to provide more details if needed if it helps get this solved!
[azure-servicebus.log](https://github.com/Azure/azure-sdk-for-python/files/12074386/azure-servicebus.log)

**Comment by trylle** [comment]
> Hi @trylle would you be able to try using the most recent version of azure-servicebus (7.11.0) and see if this problem persists? We introduced pyamqp this year as a fully python amqp stack replacement for uamqp in version 7.10.0 and above.

@l0lawrence We have been using azure-servicebus 7.10.0 since June 6, and we also rewrote our code not to rely on `max_wait_time` due to the problems described originally. Since then it has been able to recover from transient errors (e.g. server-side throttling, updates) without apparent issue. So far, we haven't noted any "unknown" errors in our logs as we received before.

In our case, we still see the behavior of `max_wait_time` affecting retry (tested on 7.11.1). If I use `max_wait_time=3` and turn off wifi, the application will still receive an exception with barely any retry. If I use `max_wait_time=None` and turn off wifi, the service bus library will retry as expected and resume message delivery when the wifi is turned back on. See below log snippets.

We use default retry options:

```
self._config.retry_mode
<RetryMode.Exponential: 'exponential'>
self._config.retry_backoff_factor
0.8
self._config.retry_backoff_max
120
```
[maxwait3-snip.log](https://github.com/Azure/azure-sdk-for-python/files/12215632/maxwait3-snip.log)
[maxwaitnone-snip.log](https://github.com/Azure/azure-sdk-for-python/files/12215633/maxwaitnone-snip.log)

**Comment by l0lawrence** [comment]
Hi @trylle, thank you for testing out the newer version of the package. 

I am able to reproduce what you are seeing. I will discuss with our team to find a solution and will update this issue with a PR when available!

**Comment by l0lawrence** [comment]
Hi @trylle, trying to get more background on this, is there a specific reason you were using the `max_wait_time` parameter on `receive_messages` rather than setting the `max_wait_time` on the ServicebusReceiver. Would you be opposed to only using the `max_wait_time` set on the ServicebusReceiver? 

The reason being, `max_wait_time` in `receive_messages` as you have noted does impact both retrying, and the amount of time we will wait for a message. Whereas `max_wait_time` on the ServicebusReceiver only impacts the amount of time we wait for a message.
