### ISSUE TITLE
Strongly typed classes

### ISSUE THREAD

**Issue by IDrumsey** [Azure/azure-sdk-for-python#28547]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like types to be associated with class properties for ease of development. For instance, the AnalyzeResult class has a property called `documents`, but when I go to access that property it is of the type `Any | None` when it should be `list[AnalyzedDocument] | None` or something like that.

**Describe alternatives you've considered**
I could manually define the type in my client code.

**Additional context**

**Comment by kristapratico** [comment]
Thanks @IDrumsey, we'll take a look and get back to you asap.

**Comment by catalinaperalta** [comment]
Thanks for reaching out @IDrumsey. We will be releasing a new SDK version soon with added typing in the package. I'll let you know when we are close to releasing the next package version and how you can target it!

**Comment by catalinaperalta** [comment]
@IDrumsey we released a new version with improved static typing, here is the link: https://pypi.org/project/azure-ai-formrecognizer/3.2.1/

I'll close this now, if you have any other questions or requests let us know! :)

**Comment by IDrumsey** [comment]
Awesome! Thanks :)

**Comment by IDrumsey** [comment]
@catalinaperalta, hello. It looks like there are still some types that are not consistent with the online documentation. For example, the BlobProperties class `name` property shows on the [documentation](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobproperties?view=azure-python#:~:text=Variables-,name,-str) as type `str`, but is of type `Any | None` in the actual code. I am using the 3.2.1 as mentioned above. I understand that perhaps adding all the types to be consistent with the docs is unreasonable to do in a short period of time, but is there a plan in the works to make this happen? Thanks!

**Comment by catalinaperalta** [comment]
Hi @IDrumsey!  The model you pointed out it part of the `azure-storage-blob` package which versions and adds features at a different cadence than the Form Recognizer SDK. Could you please open a new issue for the improvements you wish to see there? I'll keep an eye out for it and help tag the right people. Feel free to keep opening new issues for each SDK you see that still needs improved typing, we'll loop in the right people to take a look at them :)

**Comment by IDrumsey** [comment]
@catalinaperalta, I have opened an issue with the `azure-storage-blob` in the title cuz the package is in this same repository. I hope that works. Here is that issue - #30143. Thanks for your help :)
