### ISSUE TITLE
Managed Identity for Graph API seems to call old ADAL Endpoint?

### ISSUE THREAD

**Issue by aersam** [Azure/azure-sdk-for-python#28544]
- **Package Name**: azure.identity
- **Package Version**: 1.12.0
- **Operating System**: Linux / Azure App Services 
- **Python Version**: 3.9

**Describe the bug**

```
An unexpected error occured while fetching the AAD Token.Code: NoneMessage: An unexpected error occured while fetching the AAD Token.Stack:   File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 448, in _handle__invocation_requestcall_result = await self._run_async_func(File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 724, in _run_async_funcreturn await ExtensionManager.get_async_invocation_wrapper(File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 147, in get_async_invocation_wrapperresult = await function(**args)File "/home/site/wwwroot/function_app.py", line 78, in active_directory_httpawait read_active_directory(CreationContext.from_request(req))File "/home/site/wwwroot/active_directory.py", line 15, in read_active_directorytoken, expiry = await acquire_token(run, "Directory.Read.All")File "/home/site/wwwroot/azurerestapi.py", line 40, in acquire_tokentk = await cred.get_token(*scopes)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/aio/_internal/decorators.py", line 21, in wrappertoken = await fn(*args, **kwargs)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/aio/_credentials/managed_identity.py", line 120, in get_tokenreturn await self._credential.get_token(*scopes, **kwargs)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/aio/_internal/managed_identity_base.py", line 45, in get_tokenreturn await super().get_token(*scopes, **kwargs)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/aio/_internal/get_token_mixin.py", line 62, in get_tokentoken = await self._request_token(*scopes, **kwargs)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/aio/_internal/managed_identity_base.py", line 53, in _request_tokenreturn await cast(AsyncManagedIdentityClient, self._client).request_token(*scopes, **kwargs)File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/aio/_internal/managed_identity_client.py"


2023-01-31T11:55:06.527572116Z  ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS500011: The resource principal named Directory.Read.All was not found in the tenant named CENSORED. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
```

**To Reproduce**

```python
from azure.identity import ManagedIdentityCredential
ManagedIdentityCredential().get_token("Directory.Read.All") # also does not work with https://graph.microsoft.com/Directory.Read.All or https://graph.microsoft.com/.default
```

**Expected behavior**

Well, getting a token for Graph API should work. Also, why is ADAL mentioned in the log? I don't want ADAL, I want MSAL

**Comment by kashifkhan** [comment]
Thank you for the feedback @aersam . We will investigate and get back to you asap.

**Comment by aersam** [comment]
Closing it as https://graph.microsoft.com works. The only thing I didn't try before...

**Comment by aersam** [comment]
Still a bit confusing, everywhere else we're talking of scopes, not resources, right?

**Comment by aersam** [comment]
Still a bit confusing, everywhere else we're talking of scopes, not resources, right?

**Comment by xiangyan99** [comment]
@aersam You are right. Credential.get_token method uses scopes as inputs. You can get more details from https://learn.microsoft.com/azure/active-directory/develop/scopes-oidc.

**Comment by aersam** [comment]
> @aersam You are right. Credential.get_token method uses scopes as inputs. You can get more details from https://learn.microsoft.com/azure/active-directory/develop/scopes-oidc.

Well it should. But I had to pass a resource which is highly confusing. I'll reopen it

**Comment by xiangyan99** [comment]
We hear you. 

Unfortunately, it is by design that current graph APIs do not work well with track 2 azure identity library.

Please feel free to send feedback to the graph team for the feature request.

**Comment by aersam** [comment]
Sorry to come back again, but I don't see that this is a graph api only issue. If this is a design issue then it's an issue of the functions runtime or not?

Also the python sdk could at least stip the .default which would make it work at least the same way as ClientSecretCredential. Also it would make DefaultCredential work better

**Comment by aersam** [comment]
Also I used the .Net SDK a lot and never had that isse. I'll compare the code, maybe I find something

**Comment by aersam** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/6668127b79200f099b73c82a8650f4651ebb4ab0/sdk/identity/Azure.Identity/src/AppServiceManagedIdentitySource.cs#L57

**Comment by xiangyan99** [comment]
To make sure we are on same page, .net only accepts scopes as input too.

In the code you linked, they massage the scope to get the resource information to compose the request. That's implementation detail.

From API signature perspective, it is still scopes.

```cs
protected override Request CreateRequest(string[] scopes)
```

Did I miss anything?

**Comment by aersam** [comment]
Now we're on the right track! It should accept scopes, but it doesn't currently.

**Comment by xiangyan99** [comment]
What I meant by scope was something like "https://graph.microsoft.com/User.Read" rather than "Directory.Read.All".

In addition to the operation, you also need to provide the information of which Azure service you want to operate.

Are we still on same page? :)

**Comment by aersam** [comment]
Well, Directory.Read.All is a scope, too. If you don't provide a url it's a graph url, meaning it's the same as https://graph.microsoft.com/Directory.Read.All . That's a special case we can forget for now

However, for the ManagedIdentity Endpoint you have to pass a resource, meaning you have to do a conversion. You have to rewrite https://graph.microsoft.com/Directory.Read.All to https://graph.microsoft.com/ in order to make the API Surface work as intended

**Comment by xiangyan99** [comment]
I guess you were looking for https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_internal/__init__.py#L19?

**Comment by aersam** [comment]
That looks good, is that actually used? Doesn't seem like it

**Comment by xiangyan99** [comment]
It is called in https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py#L108.

**Comment by aersam** [comment]
Hm, looks good. Need to investigate more why it doesnt work then. Is it called in the aio variants, too?

**Comment by xiangyan99** [comment]
Yes. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/aio/_internal/managed_identity_client.py#L27

**Comment by aersam** [comment]
Ok, I agree it all looks good. I'll double check tomorrow why I have issues

**Comment by aersam** [comment]
I'm sorry it all seems to be good. Maybe I worked too long or so....

**Comment by xiangyan99** [comment]
No worries at all. Any feedback/questions are more than welcome.
