### ISSUE TITLE
graphrbac_client  groups  list

### ISSUE THREAD

**Issue by sfonteneau** [Azure/azure-sdk-for-python#28579]
With  graphrbac_client.groups.list 
Is there a way to retrieve the source anchor (immutable_id) of a group?

**Comment by YalinLi0312** [comment]
Hi @sfonteneau , thanks for contacting!

`azure-graphrbac` is about Azure AD Graph API, which is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API: https://github.com/azure-deprecation/dashboard/issues/60

MS Graph is not an Azure product, so we can't help you on this repo unfortunately, but I would suggest you look into the "microsoftgraph" org on Github, starting here: https://github.com/microsoftgraph/msgraph-sdk-python-core
