### ISSUE TITLE
next release for azure.mgmt.rdbms.postgresql

### ISSUE THREAD

**Issue by cgoenka1** [Azure/azure-sdk-for-python#28575]
**Is your feature request related to a problem? Please describe.**

When will next stable release of azure.mgmt.rdbms.postgresql happen? I see SameZone parameter was added for High Availability in beta release

**Describe the solution you'd like**
Stable release with SameZone parameter in HighAvailability.

**Comment by kashifkhan** [comment]
Thank you for the feedback @cgoenka1  . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
Hi @cgoenka1 azure-mgmt-rdbms contains 4 parts:
https:/github.com/Azure/azure-rest-api-specs/tree/main/specification/mariadb/resource-manager
https:/github.com/Azure/azure-rest-api-specs/tree/main/specification/mysql/resource-manager
https:/github.com/Azure/azure-rest-api-specs/tree/main/specification/postgresql/resource-manager
https:/github.com/Azure/azure-rest-api-specs/tree/main/specification/postgresqlhsc/resource-manager

Some part only has preview api-vresion so the version of whole package is preview. Could you check the latest beta version?
