### ISSUE TITLE
.method_request_received deprecated but no description on  .on_method_request_received is there

### ISSUE THREAD

**Issue by tervoju** [Azure/azure-sdk-for-python#28577]
[Enter feedback here]

deprecated since version 2.3.0: We recommend that you use the .on_method_request_received property to set a handler instead

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 178e6ad2-a925-7c36-7600-5c8160e8d81c
* Version Independent ID: 327ccd4e-78fb-f87d-9d0f-9b9ff6afc33c
* Content: [azure.iot.device.aio.IoTHubModuleClient class](https://learn.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.aio.iothubmoduleclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-iot-device/azure.iot.device.aio.IoTHubModuleClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-iot-device/azure.iot.device.aio.IoTHubModuleClient.yml)
* Product: **azure-iot**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you help to clarify what you expect?

**Comment by tervoju** [comment]
why there is .method_request_received at all but no .on_request_request_received? is it the same only name changed or what? I am interested as I cannot get (python) module to module2method call working. cloud to module direct method call works.

**Comment by xiangyan99** [comment]
Looks like the code is hosted in https://github.com/Azure/azure-iot-sdk-python/ and maintained by the service team.

I will close this one and please feel free to open issues in that repo.
