### ISSUE TITLE
Onboard ML packages to docs

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#28582]
`mltable` - https://learn.microsoft.com/en-us/python/api/mltable/?view=azure-ml-py
`azureml-fsspec` -- https://learn.microsoft.com/en-us/python/api/azureml-fsspec/?view=azure-ml-py

Can we add these packages to our metadata CSV? (this gets us ToC entries for very low cost) 

Coordinate removal of these packages from existing docs location to avoid ambiguous ToC problems.

**Comment by annatisch** [comment]
@danieljurek - these are not track2 libraries - do we normally place such packages alongside our GA docs?

**Comment by danieljurek** [comment]
@annatisch -- From my understanding, the track 2 ML libraries depend on these packages and there was a customer request to surface them near the main set of packages. If these packages are not in scope then it might make sense to document them elsewhere. As it is now, they're documented alongside the "v1" ML packages. 

Another alternative might be to include links to documentation of these packages in the [Package Level Overview](https://learn.microsoft.com/en-us/python/api/overview/azure/ai-ml-readme?view=azure-python) for relevant packages or the [Service Level Overview](https://learn.microsoft.com/en-us/python/api/overview/azure/machine-learning?view=azure-python).  

cc @harneetvirk, @weshaggard

**Comment by harneetvirk** [comment]
mltable and azureml-fsspec package are used in sdkv2 as an indirect dependency.
1) mltable is used for tabular interface.
2) azureml-fsspec is for filesystem interface.

The ref docs for mldesigner (design pipelines ) will be eventually added.

Customers using azure-ai-ml package have to look at multiple places to find the documentation for the dependent packages.
For e.g. The ref docs for mltable and azureml-fsspec is hosted along with sdkv1 docs but the sdkv2 ref docs are hosted along with other sdk packages, causing end users to make multiple hops to get ref docs.

**Proposed changes for ref docs layout:**

Machine-Learning

    Overview
    Core Operations (Replace Machine-Learning text)
        Overview
        azure-ai-ml

    Data for machine learning
         File Data (Text for azureml-fsspec)
            Overview
            azureml-fsspec
         Tabular Data (Text for mltable)
            Overview
            mltable

    Design pipelines (Text for mldesigner)
        overview
        mldesigner

**Comment by danieljurek** [comment]
Our ToC automation doesn't currently support two levels nesting for packages in these cases. The packages display names are alphabetized as well. A more plausible layout is: 

Machine Learning
  Overview
  Core Operations
    Overview
    azure-ai-ml
  Design Pipelines
    overview
    mldesigner
  File Data
    Overview
    azureml-fsspec
  Tabular Data 
    Overview
    mltable

**Comment by danieljurek** [comment]
This is done.
