### ISSUE TITLE
Python script hangs after some time

### ISSUE THREAD

**Issue by jysaghbini** [Azure/azure-sdk-for-python#28608]
Hi,

I created a script to retrieve logs from an Event Hub and forward them to a SIEM. I relied on the async sample code shown.
The script runs perfectly. I created a cronjob to execute the script every 5 minutes but I used flock to avoid launching the script if already running.

The script works perfectly for some time, and I believe it never ends and gives the change for the cronjob to kick in.

However, after some time, it just hangs. script doesn't exit but logs stop coming. Process is still running and I have to kill it for it respawn through the cronjob.

Any idea what is wrong with my script? it is running on centos box with the latest python 3 running.

Below is the script:

import os
import json
import logging
import logging.handlers
import asyncio
from azure.eventhub.aio import EventHubConsumerClient
from azure.eventhub.extensions.checkpointstoreblobaio import BlobCheckpointStore

connection_str = 'xxx'
consumer_group = '$Default'
eventhub_name = 'xxx'
storage_connection_str = 'xxx'
container_name = 'xxx'

# Set True to output to syslog, false to only save to file
syslog_output = True
# Enter the IP address or hostname of your syslog server
syslog_server = 'x.x.x.x'
# Change this to override default port
syslog_port = 514

# Set up logging (in this case to terminal)
log = logging.getLogger(__name__)
log.root.setLevel(logging.DEBUG)
log_formatter = logging.Formatter('%(levelname)s %(message)s')
log_handler = logging.StreamHandler()
log_handler.setFormatter(log_formatter)
log.addHandler(log_handler)

# Set up syslog output
syslog_handler = logging.handlers.SysLogHandler(address=(syslog_server, syslog_port))
syslog_formatter = logging.Formatter('%(message)s')
syslog_handler.setFormatter(syslog_formatter)
syslogger = logging.getLogger(__name__)
syslogger = logging.getLogger('SysLogger')
syslogger.addHandler(syslog_handler)

async def on_event_batch(partition_context, events):
    log.debug("Received event from partition {}".format(partition_context.partition_id))
    for event in events:
        body = json.dumps(json.loads(event.body_as_str())["records"][0])

        if syslog_output is True:
            syslogger.info(body)
        else:
            log.debug("New incoming event:")
            log.debug(event)

    await partition_context.update_checkpoint()

async def receive_batch():
    checkpoint_store = BlobCheckpointStore.from_connection_string(storage_connection_str, container_name)
    client = EventHubConsumerClient.from_connection_string(connection_str, consumer_group, eventhub_name=eventhub_name, checkpoint_store=checkpoint_store)
    async with client:
        await client.receive_batch(
            on_event_batch=on_event_batch,
            max_batch_size=100,
            starting_position="-1",  # "-1" is from the beginning of the partition.
        )
        await client.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(receive_batch())
    loop.close()
    quit()

Regards,

Jean-Yves

**Comment by kashifkhan** [comment]
Hi @jysaghbini , can you please let provide the version of the eventhub library and python that you are using ?

**Comment by jysaghbini** [comment]
Hi,

Python version is 3.9.16
azure-eventhub: 5.11.1

What sorts of logs you want me to share?

Regards,

Jean-Yves

**Comment by kashifkhan** [comment]
@jysaghbini debug logs will be the best in order to help us see why exactly the script stops working for you. 

Just one thing I noticed in the script:
* Are you using checkpointing ? if yes, then the following modification will be needed for the script, otherwise you can remove it altogether as its not needed to use the library. 
    ```python
       for event in events:
           await partition_context.update_checkpoint(event)
```

**Comment by jysaghbini** [comment]
Hi Kashif,

You mean by that that I move the update_checkpoint function on event per event basis instead of batch?

I am currently calling the function without parameters at the end of the event_batch function.

Is that wrong?

I will add debug logs within the code to see where it is hanging.

Regards,

Jean-Yves

**Comment by kashifkhan** [comment]
@jysaghbini yes currently update_checkpoint doesnt accept batch as an input. Right now simply doing this `await partition_context.update_checkpoint()` is not doing anything. If youd like to use checkpoint, then you can add in my snippet above else you can completely remove it.

**Comment by jysaghbini** [comment]
I am using checkpoint store in an Azure Blob Storage container.

Does this mean I need to run the update_checkpoint function?

Regards,

Jean-Yves

**Comment by kashifkhan** [comment]
> ```python
>    for event in events:
>        await partition_context.update_checkpoint(event)
> ```

yes, you can copy my snippet and that will make sure checkpoints are working :)

**Comment by jysaghbini** [comment]
Ok thank you.

I added it inside the loop instead of outside, and added the event as parameter.

I added the debug text in the code and running it now, waiting for it to hang.

Will keep you updated.

Regards,

Jean-Yves

**Comment by jysaghbini** [comment]
I put some debugging info in my script. It now looks like this:

import os
import json
import logging
import logging.handlers
import asyncio
from azure.eventhub.aio import EventHubConsumerClient
from azure.eventhub.extensions.checkpointstoreblobaio import BlobCheckpointStore

LOG_FILE_PATH = "/root/scripts/eventhub/log.txt"
connection_str = 'xxx'
consumer_group = '$Default'
eventhub_name = 'xxx'
storage_connection_str = 'xxx'
container_name = 'xxx'

# Set True to output to syslog, false to only save to file
syslog_output = True
# Enter the IP address or hostname of your syslog server
syslog_server = 'x.x.x.x'
# Change this to override default port
syslog_port = 514

# Set up logging (in this case to terminal)
log = logging.getLogger(__name__)
log.root.setLevel(logging.DEBUG)
log_formatter = logging.Formatter('%(levelname)s %(message)s')
log_handler = logging.StreamHandler()
log_handler.setFormatter(log_formatter)
log.addHandler(log_handler)

# Set up syslog output
syslog_handler = logging.handlers.SysLogHandler(address=(syslog_server, syslog_port))
syslog_formatter = logging.Formatter('%(message)s')
syslog_handler.setFormatter(syslog_formatter)
syslogger = logging.getLogger(__name__)
syslogger = logging.getLogger('SysLogger')
syslogger.addHandler(syslog_handler)

# Set up file logging
filelog_handler = logging.FileHandler(LOG_FILE_PATH)
filelog_formatter = logging.Formatter('%(message)s')
filelog_handler.setFormatter(filelog_formatter)
filelog = logging.getLogger('FileLogger')
filelog.root.setLevel(logging.DEBUG)
filelog.addHandler(filelog_handler)

async def on_event_batch(partition_context, events):
    try:
        log.debug("Received event from partition {}".format(partition_context.partition_id))
        filelog.debug("Received event from partition {}".format(partition_context.partition_id))
        for event in events:
            filelog.debug('Before dumping json')
            body = json.dumps(json.loads(event.body_as_str())["records"][0])

            filelog.debug('Before log handling')
            if syslog_output is True:
                filelog.debug('Before syslog forwarding')
                syslogger.info(body)
            else:
                log.debug("New incoming event:")
                log.debug(event)

            filelog.debug('Before update_checkpoint()')
            await partition_context.update_checkpoint(event)
    except Exception as e:
        filelog.debug('Error in on_event_batch: ' + str(e))

async def receive_batch():
    try:
        filelog.debug('Before checkpoint_store initialization')
        checkpoint_store = BlobCheckpointStore.from_connection_string(storage_connection_str, container_name)
        filelog.debug('Before client initialization')
        client = EventHubConsumerClient.from_connection_string(connection_str, consumer_group, eventhub_name=eventhub_name, checkpoint_store=checkpoint_store)
        async with client:
            filelog.debug('Before receive_batch')
            await client.receive_batch(
                on_event_batch=on_event_batch,
                max_batch_size=100,
                starting_position="-1",  # "-1" is from the beginning of the partition.
            )
            filelog.debug('After receive_batch')
            await client.close()
    except Exception as e:
        filelog.debug('Error in receive_batch:' + str(e))

if __name__ == '__main__':
    try:
        filelog.debug('Before get_event_loop()')
        loop = asyncio.get_event_loop()
        filelog.debug('Before loop.run_until_complete()')
        loop.run_until_complete(receive_batch())
        filelog.debug('After loop.run_until_complete()')
        loop.close()
        quit()
    except Exception as e:
        filelog.debug('Error in Main: ' + str(e))

After a while it hang as usual. I checked the log file and this is how it looks in the end:

Received event from partition 1
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Received event from partition 1
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Received event from partition 1
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Received event from partition 1
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Received event from partition 0
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Received event from partition 1
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Received event from partition 0
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Received event from partition 0
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Received event from partition 1
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()
Before dumping json
Before log handling
Before syslog forwarding
Before update_checkpoint()

and it just stops there. No error, no exception.

Any idea?

Regards,

Jean-Yves

**Comment by jysaghbini** [comment]
I also noticed something.

I checked all the log file. I never reach logging entries like:
after receive_batch 
after loop.run_until_complete

it looks as if it keeps on receiving batches, it never stops, and code never ends.
Or maybe, it is reaching the end of the batch but getting stuck there and not exiting.

I am out of ideas.

Jean-Yves

**Comment by kashifkhan** [comment]
@jysaghbini is it possible that there are no more events to pull back from the event hub? `receive_batch` will wait indefinitely in that case.

**Comment by jysaghbini** [comment]
Events are continuously arriving. The script hangs and never resumes unless I kill it. Then it picks up where it left off.

**Comment by jysaghbini** [comment]
Is there a way to force the script to exit if no more logs are being pulled?

**Comment by jysaghbini** [comment]
I launched the script again now after it hung before, and now after 5-10 minutes, it hung again.
Looks like it is getting all the logs, no more logs to get and hangs there. If new logs come in, it won't see them.

How can I remedy that?

Regards,

Jean-Yves

**Comment by jysaghbini** [comment]
@kashifkhan is there a way to exit the script if no more logs are there to fetch?

It looks like, at some point in time, no more logs are there, and receive_batch hangs while waiting. Even if new logs come, it doesn't fetch them anymore.

Regards,

Jean-Yves

**Comment by kashifkhan** [comment]
hi @jysaghbini , 

I was able to use the following script to close the consumer if nothing was received for 10 seconds, by using `max_wait_time` on `receive_batch`.  Another option would be to use `asyncio.create_task` and let it run for a specified amount of time before cancelling the task.

I also tested the scenario where I read all the events from the hub and then resumed sending a few events after a gap. The consumer client was able to resume receiving events. 

```python
import asyncio
import functools
import os
from azure.eventhub.aio import EventHubConsumerClient
from azure.eventhub.extensions.checkpointstoreblobaio import BlobCheckpointStore

CONNECTION_STR = ''
EVENTHUB_NAME = ''
STORAGE_CONNECTION_STR = ''
BLOB_CONTAINER_NAME = ""  # Please make sure the blob container resource exists.


async def on_event(client, partition_context, events):
    # Put your code here.
    if not events:
        print("received nothing going to close the producer")
        if client:
            await client.close()
            client = None
    print("Received event from partition: {}.".format(partition_context.partition_id))

    for event in events:
        await partition_context.update_checkpoint(event)


async def receive(client):
    """
    Without specifying partition_id, the receive will try to receive events from all partitions and if provided with
    a checkpoint store, the client will load-balance partition assignment with other EventHubConsumerClient instances
    which also try to receive events from all partitions and use the same storage resource.
    """
    on_event_partial = functools.partial(on_event, client)
    await client.receive_batch(
        on_event_batch=on_event_partial,
        max_wait_time=10,
        starting_position="-1",  # "-1" is from the beginning of the partition.
    )
    # With specified partition_id, load-balance will be disabled, for example:
    # await client.receive(on_event=on_event, partition_id='0'))


async def main():
    checkpoint_store = BlobCheckpointStore.from_connection_string(STORAGE_CONNECTION_STR, BLOB_CONTAINER_NAME)
    client = EventHubConsumerClient.from_connection_string(
        CONNECTION_STR,
        consumer_group="$Default",
        eventhub_name=EVENTHUB_NAME,
        checkpoint_store=checkpoint_store,  # For load-balancing and checkpoint. Leave None for no load-balancing.
    )
    async with client:
            await receive(client)        
    print("DONE RECEIVING")


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by jysaghbini** [comment]
Hi @kashifkhan ,

Thank you for your valuable input.

I am actually testing something similar now by calling the receive_batch function differently:

await asyncio.wait_for (
                client.receive_batch(
                    on_event_batch=on_event_batch,
                    max_batch_size=1000,
                    starting_position="-1",  # "-1" is from the beginning of the partition.
                ),
                timeout=60
            )

the timeout is set to 60 seconds. I also increased the batch size to 1000 to fetch the logs faster.

I will let you know how it turns out.

Regards,

Jean-Yves

**Comment by jysaghbini** [comment]
Hi @kashifkhan ,

my fix actually worked. I increased the timeout to 295 seconds and set my cronjob to run every 5 minutes.

After 295 seconds, my script is exiting and a new one is getting launched 5 seconds later.

I didn't get to test your fix, but since mine is working, I am happy :)

Thank you for all the support.

Regards,

Jean-Yves
