### ISSUE TITLE
Documentation for DurableOrchestrationClient.start_new() incorrect

### ISSUE THREAD

**Issue by waltervos** [Azure/azure-sdk-for-python#28602]
The documentation for the `start_new` method says that:

> If an orchestration instance with the specified ID already exists, the existing instance will be silently replaced by this new instance.

That's not what I'm observing though. I'm seeing an exception being raised, as follows:

```
{
    'Message': 'Something went wrong while processing your request',
    'ExceptionMessage': 'An Orchestration instance with the status Running already exists.',
    'ExceptionType': 'System.InvalidOperationException',
    'StackTrace': '
        at DurableTask.AzureStorage.AzureStorageOrchestrationService.CreateTaskOrchestrationAsync(TaskMessage creationMessage, OrchestrationStatus[] dedupeStatuses) in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs:line 1570\r\n
        at DurableTask.Core.TaskHubClient.InternalCreateOrchestrationInstanceWithRaisedEventAsync(String orchestrationName, String orchestrationVersion, String orchestrationInstanceId, Object orchestrationInput, IDictionary`2 orchestrationTags, OrchestrationStatus[] dedupeStatuses, String eventName, Object eventData, Nullable`1 startAt) in /_/src/DurableTask.Core/TaskHubClient.cs:line 614\r\n
        at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\ContextImplementations\\DurableClient.cs:line 210\r\n
        at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 875\r\n
        at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 306'
}
```

I don't necessarily mind this behaviour, it's a lot more explicit than what "silently replacing" an existing orchestration sounds like. I do think the docs should mention the correct behaviour. And if this Exception is the intended behaviour, [the example in the "Concepts"](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons?tabs=python) docs should probably include a try/except block, too. Something like:"

```
import logging
import azure.functions as func
import azure.durable_functions as df

async def main(req: func.HttpRequest, starter: str) -> func.HttpResponse:
    client = df.DurableOrchestrationClient(starter)
    instance_id = req.route_params['instanceId']
    function_name = req.route_params['functionName']

    existing_instance = await client.get_status(instance_id)

    if existing_instance.runtime_status in [df.OrchestrationRuntimeStatus.Completed, df.OrchestrationRuntimeStatus.Failed, df.OrchestrationRuntimeStatus.Terminated, None]:
        event_data = req.get_body()
        try:
            instance_id = await client.start_new(function_name, instance_id, event_data)
        except Exception as e:
            logging.info(f"Failed to start ochestration, due to: {e.args[0]['ExceptionMessage']}")
        logging.info(f"Started orchestration with ID = '{instance_id}'.")
        return client.create_check_status_response(req, instance_id)
    else:
        return {
            'status': 409,
            'body': f"An instance with ID '${existing_instance.instance_id}' already exists"
        }

```

Looking forward to hearing from you, it would be good to know what I should be counting on for this scenario. There is a very real chance of this happening in my application (attempting to start many orchestrations with the same ID, to serve as a singleton).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf8501a6-e09a-0054-36dc-9d958d1b56aa
* Version Independent ID: 534b19ae-7621-de54-d615-77af7fa16f36
* Content: [azure.durable_functions.DurableOrchestrationClient class](https://learn.microsoft.com/en-us/python/api/azure-functions-durable/azure.durable_functions.durableorchestrationclient?view=azure-python#azure-durable-functions-durableorchestrationclient-start-new)
* Content Source: [docs-ref-autogen/azure-functions-durable/azure.durable_functions.DurableOrchestrationClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-functions-durable/azure.durable_functions.DurableOrchestrationClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by YalinLi0312** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by waltervos** [comment]
Any news on this? I'd be very happy just to know "silently replaced" means in this bit of documentation, as I'm writing an application that has the possible race condition of checking for an active orchestration with a certain ID, concluding there's no instance active, then starting that instance, only to run into an exception that says there's an instance already active (because it was started by another running function that performed the same steps but was slightly earlier).

**Comment by SaurabhSharma-MSFT** [comment]
@waltervos Sorry, for the delay on this.  Yes, you are correct, this is a bug in the documentation. You can re-use instance IDs only if the existing orchestration instance is in a terminal state (Completed, Failed, or Terminated). You cannot re-use instance IDs if the existing orchestration instance is in a Running or Pending state.  So, you are in right direction to handle this exception as expected if two processes try to create the orchestration concurrently.
I am though internally working to get the documentation updated accordingly to avoid any confusions to future readers.  
Please let me know if you have any other questions.   Thanks

**Comment by franklixuefei** [comment]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.startnewasync?view=azure-dotnet#microsoft-azure-webjobs-extensions-durabletask-idurableorchestrationclient-startnewasync-1(system-string-system-string-0) please fix
