### ISSUE TITLE
Update documentation for trigger creation for ADF Pipelines.

### ISSUE THREAD

**Issue by marianaalanis93** [Azure/azure-sdk-for-python#28625]
- azure.mgmt.datafactory: 
- 2.10.0: 
- Windows:
- 3.8.0: 

This documentation is not up to date. (https://learn.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger?tabs=data-factory#python-sdk). There is needed more examples about trigger creation and setup, what is it expected for 'properties 'paramenter. 
Samples in current documentation does not work resulting in an ARM error (which is also unclear to now what's happening)

- Update documentation
- Better logging/handling errors in case a parameter is bad constructed and why.

**To Reproduce**
1.  Reproducing example in documentation

**Expected behavior**
- Updated documentation
- Better logging/handling errors in case a parameter is bad constructed and why.

**Screenshots**

**Additional context**

**Comment by YalinLi0312** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
I am owner of all the mgmt SDK including `azure-mgmt-datafactory` but not very familiar with how to use the package in different scenarios. I think it is better to let service team member to update the doc with latest `azure-mgmt-datafactory`. According to [commit history](https://github.com/MicrosoftDocs/azure-docs/commits/main/articles/data-factory/how-to-create-schedule-trigger.md), @dbradish-microsoft may help to update https://learn.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger?tabs=data-factory#python-sdk or address more proper experts.

**Comment by dbradish-microsoft** [comment]
@msyyc, @diberry  is the Python doc's lead.  As this doc is in the azure-sdk-for-python repo, you'll want to work with her first.

**Comment by diberry** [comment]
#in-progress Thanks for alerting me @dbradish-microsoft.

**Comment by xiangyan99** [comment]
@diberry any updates?

**Comment by xiangyan99** [comment]
The doc is updated.

**Comment by diberry** [comment]
@xiangyan99 @dbradish-microsoft Sorry about not responding sooner - @bobtabor is the lead for Python now.
