### ISSUE TITLE
Wrong Language detection result from azure-ai-textanalytics

### ISSUE THREAD

**Issue by qlycool** [Azure/azure-sdk-for-python#28629]
- **Package Name**: azure-ai-textanalytics 
- **Package Version**: 5.2.1
- **Operating System**:win11
- **Python Version**: 3.9

**Describe the bug**
Error results are returned when using this SDK for language type detection.
Input "你好" in Chinese and return the English language type.

**To Reproduce**
1. use https://github.com/MicrosoftLearning/AI-102-AIEngineer repo, run 01-getting-started/Python/sdk-client/sdk-client.py
Input "你好" in Chinese and return the "English" language type.

**Expected behavior**
When using this SDK for language type detection, 
input "你好" in Chinese and return the "Chinese_Simplified" language type.

**Screenshots**
![image](https://user-images.githubusercontent.com/8130671/216544482-4074aec4-193c-45e2-8d12-61c814b9c19b.png)

**Additional context**
if I use REST Client, 01-getting-started/Python/rest-client/rest-client.py in https://github.com/MicrosoftLearning/AI-102-AIEngineer repo.
I get the Language type is "Chinese_Traditional".
![image](https://user-images.githubusercontent.com/8130671/216544191-5339659a-e8da-4135-a9dd-df81280b4ced.png)

**Comment by kashifkhan** [comment]
Thank you for the feedback @qlycool . We will investigate and get back to you asap.

**Comment by kristapratico** [comment]
@qlycool thank you for your detailed issue. The reason there is a difference between the API vs SDK is that the SDK passes a default `country_hint` of "US" if none is provided by the user. You can override this behavior by passing `country_hint="none"` in your detect_language call:

```python
text = "你好"
detectedLanguage = client.detect_language(documents=[text], country_hint="none")[0]
```

This returns a detected language result of "Chinese_Traditional":
`[DetectLanguageResult(id=0, primary_language=DetectedLanguage(name=Chinese_Traditional, iso6391_name=zh_cht, confidence_score=0.67, script=None), warnings=[], statistics=None, is_error=False, kind=LanguageDetection)]`

Let me know if you have any other questions.
