### ISSUE TITLE
Scrape events under 'Planned Maintenance' in Service Health section

### ISSUE THREAD

**Issue by chouzee** [Azure/azure-sdk-for-python#28639]
Hi! I've installed azure-mgmt-resourcehealth 1.0.0b2 and everything seems to be ok, but I have difficulties getting entries from `Planned Maintenance` section. Could you clarify if it's possible to do using the package? Thanks in advance.
![Screenshot-6](https://user-images.githubusercontent.com/8557950/216706809-5e85ea8c-cfe7-4a96-9924-15189f9a8e48.png)

**Comment by YalinLi0312** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Wzb123456789** [comment]
Hi @chouzee 

Based on my survey, this package cannot obtain some entries for `planned maintenance`.

If you have this demand, you can try to submit your specific questions [here](https://github.com/Azure/azure-rest-api-specs/issues).
