### ISSUE TITLE
Error in documentation for spellcheck api

### ISSUE THREAD

**Issue by kennethjmyers** [Azure/azure-sdk-for-python#2863]
Wasn't sure if this was the best place to post but the [docs](https://docs.microsoft.com/en-us/python/api/azure.cognitiveservices.language.spellcheck.spellcheckapi?view=azure-python) were missing something important. The 'credentials' field says it is NoneType, but I believe it is actually by [CognitiveServicesManagementClient class](https://docs.microsoft.com/en-us/python/api/azure.mgmt.cognitiveservices.cognitiveservicesmanagementclient?view=azure-python)

edit: actually looking at the test code, it looks like the type pertains to 

`from msrest.authentication import CognitiveServicesCredentials`

which also wasn't clear until digging in the code

**Comment by lmazuel** [comment]
@kennmyers You're right, thank you for the bug report. Note too that there is samples available for this API:
https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/blob/master/samples/language/spellcheck_samples.py

Would have clarified I guess

**Comment by lmazuel** [comment]
Closing, since the issue will auto-fix itself at the next release of this package
