### ISSUE TITLE
More detailed gallery image example

### ISSUE THREAD

**Issue by originlake** [Azure/azure-sdk-for-python#28657]
I want to use azure python sdk to create a new image in this gallery from an existing disk/snapshot, but the document/examples couldn't guide me through it.

Need a detailed code example for creating an image for azure compute gallery.

What I need to do (with python SDK as I need it to be automated) 
1. create a VM from an existing image inside azure compute gallery, latest version (I know how to do this)
2. do some updates inside that VM. (I know how to do this)
3. use the disk for that VM to create a new image and use it as the latest version.

The example https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/compute/manage_galley.py
It creates a disk and creates a snapshot, but the following gallery-related operations have no reference to the snapshot. 

Also in the document, (for example https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_07_01.operations.galleryimagesoperations?view=azure-python), when one of the argument is application/json input, there is no detailed instruction of what should be provided.

**Comment by SaurabhSharma-MSFT** [comment]
@originlake We are looking into it and get back to you for any additional information.

**Comment by Wzb123456789** [comment]
Hi @originlake 

In order to better solve your problem, please tell me the detailed problem you encountered and the error message when the code runs.
