### ISSUE TITLE
cannot import name 'Self' from 'typing_extensions' when importing MLClient on Synapse Analytics

### ISSUE THREAD

**Issue by JessicaXYWang** [Azure/azure-sdk-for-python#28651]
- **Package Name**: azure.ai.ml
- **Package Version**: 1.3.0
- **Operating System**: Synapse Analytics, Spark 3.2 pool 
- **Python Version**: 3.8

**Describe the bug**
can not import ML client from azure.ai.ml on spark 3.2 pool

**To Reproduce**
1. open notebook in Synapse Analytics, choose spark 3.2 pool (no bug on 3.3 pool)
!pip install azure.ai.ml
from azure.ai.ml import MLClient

**Expected behavior**
MLClient successfully imported

**Screenshots**
![image](https://user-images.githubusercontent.com/108437381/216894849-50c21489-3e33-4927-a512-c1d1ba4282bb.png)

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @JessicaXYWang . We will investigate and get back to you

**Comment by JessicaXYWang** [comment]
I assume this should be similar to https://github.com/Azure/azure-sdk-for-python/issues/23697 but the reload method doesn't work on Synapse Analytics. I appreciate your help and look forward to hearing back from you.

**Comment by JessicaXYWang** [comment]
I found a workaround for this one.
```
!pip install typing_extensions==4.4.0
import typing_extensions
from importlib import reload
reload(typing_extensions)
!pip install azure.ai.ml
```
