### ISSUE TITLE
Clarify blob storage async `start_copy_from_url` use case

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#28655]
Hi,
I am trying to use the async version `start_copy_from_url` to copy files from a blob to another. I must admit I am a bit confused by the example

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_copy_blob_async.py

I would have assumed from the docs

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.0.0/azure.storage.blob.aio.html#azure.storage.blob.aio.BlobClient.start_copy_from_url

that the I would get a coroutine to await until the copy has done. But I see that I am supposed to poll and check a status manually. Is that the case? Is there any other way so to avoid explicit polling?

On top of this, is there a documentation about the possible status values?

**Comment by kashifkhan** [comment]
Thanks for the feedback @andrea-cassioli-maersk . We will investigate & get back to you asap

**Comment by vincenttran-msft** [comment]
Hi @andrea-cassioli-maersk Andrea, thanks for your inquiry. For starters, the documentation you linked may be out of date as it seems to be pointing to the package version `12.0.0`, whereas the current version at the time of writing this comment is `12.14.1`.

With that being said, hopefully this documentation can help clear up any confusion:
[start_copy_from_url in BlobClient](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.aio.blobclient?view=azure-python#azure-storage-blob-aio-blobclient-start-copy-from-url)

In general, the workflow for an asynchronous operation does require you to poll the status by using the `get_blob_properties` method and inspecting the `copy_status` value.

For the possible status values, it will either be `success` if the copy completed synchronously or `pending` if the copy has been started asynchronously but not yet completed.

Hopefully this clears up any doubts!
Thanks!

**Comment by andrea-cassioli-maersk** [comment]
Thanks @vincenttran-msft now I understand. Is there any other status? I guess that in case of error an exception will be raised.

On a minor note: you are right I was looking at an older doc version.... just realised it is because in

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.14.1/index.html#clients

the link to BlobClient redirects to 12.0.1
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.0.0/azure.storage.blob.html#azure.storage.blob.BlobClient

**Comment by jalauzon-msft** [comment]
Hi @andrea-cassioli-maersk Andrea, to clarify further on the status, if there is an error during an async copy, no exception would be raised in the client, rather you would also need to check for that when polling. The copy status can have one additional value, `failed` which indicate something went wrong (there can also be an error on `pending` status). To see the error message, you can look at the `status_description` property of the [`CopyProperties`](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.copyproperties?view=azure-python) returned by `get_blob_properties`.

On the docs, I did notice the same behavior with the linking which is pretty strange. I would maybe suggest using our [other documentation page](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python) as this one seems to be more consistent.
