### ISSUE TITLE
Blob upload hangs on uploading list of 300 images

### ISSUE THREAD

**Issue by arjun251** [Azure/azure-sdk-for-python#28662]
Hi I have an issue on uploading images to blob container using upload_blob. I have a 300 images in a list. upload_blob is giving me timeout error. 
If I try with a small list of 5 images it works well.

Any suggestions would be helpful.

```
def upload_images(document_id, images):
    blob_service_client = BlobServiceClient(account_url=f'https://{model_account_name}.blob.core.windows.net/', credential=model_account_key)
    n_digits = 3
    all_images_path = []
    for i, image in enumerate(images):
        image_name = "image_%0*d.jpg" % (n_digits, i)
        image_path = document_id+"/"+image_name
        all_images_path.append(image_path)
        doc_blob_client = blob_service_client.get_blob_client(container=model_container_name, blob=image_path)
        with tempfile.NamedTemporaryFile(suffix='.jpg') as fp:
            image.save(fp, format='JPEG')
            fp.seek(0)
            image_content_setting = ContentSettings(content_type='image/jpeg')
            doc_blob_client.upload_blob(fp.read(), overwrite=True, content_settings=image_content_setting)
    return all_images_path
```
Thanks

**Comment by kashifkhan** [comment]
Thank you for the feedback @arjun251 . We will investigate and get back to you asap.

**Comment by vincenttran-msft** [comment]
Hi @arjun251 thanks for your inquiry. Can you please try setting the `connection_timeout` parameter as found in the README [here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#other-client--per-operation-configuration) and see if that fixes your issue.
Thanks!

Note: `connection_timeout` is a client kwarg and should be passed when constructing the client itself, **not** the upload API call. This means that you may have to switch to constructing the `BlobClient` client directly so you can pass the client parameter in, rather using the `get_blob_client` API off the `BlobServiceClient`.
