### ISSUE TITLE
Deprecation not mentioned in docs

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#28674]
In the docs for the `StorageStreamDownloader` class 

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.14.1/azure.storage.blob.aio.html#azure.storage.blob.aio.StorageStreamDownloader.download_to_stream

There is no mention of the deprecation of the `download_to_stream` method.

**Comment by kashifkhan** [comment]
Thank you for the feedback @andrea-cassioli-maersk . We will investigate & get back to you asap.

**Comment by vincenttran-msft** [comment]
Hi @andrea-cassioli-maersk Andrea, thanks for pointing this out. I will engage with the team to get the docs updated and will close this issue once that has been done.
Thanks!
