### ISSUE TITLE
KubernetesOnlineDeployment not respecting timeout set in OnlineRequestSettings object

### ISSUE THREAD

**Issue by dennisbakhuis** [Azure/azure-sdk-for-python#28697]
- **Package Name**: azure.ml.ai
- **Package Version**: 1.4.0
- **Operating System**: Ubuntu Linux 20.04 (AzureML Compute Instance)
- **Python Version**: Python 3.10.8
- **AKS/k8s version**: v1.24.6
- **AZ & extension versions**: {
  "azure-cli": "2.44.1",
  "azure-cli-core": "2.44.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "k8s-extension": "1.3.9",
    "ml": "2.13.0"
  }
}

**Describe the bug**
After deploying a model on AKS using KubernetesOnlineDeployment while setting the timeout to a 16 seconds using OnlineRequestSettings, the deployed model still has timeouts (504) due to its default 5000ms timeout.

AKS has the latest k8s-extension with the inference option installed.

**To Reproduce**
1. Create a scoring script (included a minimal working example, not using a model)
2. Deploy `any model` using Azure SDK v2 to AKS, with the OnlineRequestSettings(request_timeout_ms=16000).
3. Do a simple request call -> timeout at 5000ms

```python
# failure_script.py
import time

def init():
    print("\n\n ---> Loading model <---\n\n")

def run(data):
    print("\n\nRequest received!\n\n")
    time.sleep(6000)  # default timeout is set to 5000
    response = {"message": "Not gonna happen today."}
    print("\n\nRequest processed!\n\n")
    return response
```

```python
# Submit script
from azure.ai.ml import MLClient
from azure.identity import DefaultAzureCredential
from azure.ai.ml.entities import (
    CodeConfiguration,
    OnlineRequestSettings,
    KubernetesOnlineDeployment,
)

deployment_name = ""
endpoint_name = ""
compute_name = ""
environment_name = ""
model_name = ""
code_path = ""

ml_client = MLClient.from_config(
    credential=DefaultAzureCredential(),
    path='/',
)

compute = ml_client.compute.get(name=compute_name)
environment = ml_client.environments.get(
        name=environment_name,
        label="latest",
    )
model = ml_client.models.get(
    name=model_name,
    label="latest",
)

code_configuration = CodeConfiguration(
    code='./scripts',
    scoring_script='failure_script.py',
)

request_settings = OnlineRequestSettings(
    max_concurrent_requests_per_instance=1,
    request_timeout_ms=16000,
    max_queue_wait_ms=32000,
)

deployment = KubernetesOnlineDeployment(
    name=deployment_name,
    endpoint_name=endpoint_name,
    model=model,
    environment=environment,
    code_configuration=code_configuration,
    instance_count=1,
    request_settings=request_settings,
)

ml_client.begin_create_or_update(deployment).result()

endpoint = ml_client.online_endpoints.get(name=endpoint_name)
endpoint.traffic = {deployment_name: 100}
ml_client.begin_create_or_update(endpoint).result()
```

```python
import requests

api_key = ""
deployment_name = ""
endpoint_uri = ""

headers = {
    'Content-Type': 'application/json',
    'Authorization': ('Bearer ' + api_key),
    'azureml-model-deployment': 'tennet-idc-coversheets',
}

r = requests.post(
    endpoint_uri,
    headers=headers,
)
print(f"status code: {r.status_code}")
```

**Expected behavior**
I expect the request_timeout_ms time to be used by the scoring server.

**Screenshots**

**Additional context**
I use this to run a larger Model in AKS which needs about 8 seconds to do its magic.

**Comment by kashifkhan** [comment]
Thank you for the feedback @dennisbakhuis . We will investigate & get back to you asap.

cc @azureml-github

**Comment by jiaochenlu** [comment]
This is a known issue we have fixed in the latest release. It can work right now, please try again.

**Comment by dennisbakhuis** [comment]
thanks for your answer @jiaochenlu.

Could you specify what package needs to be to the lastest version and what version that is?

I have updated `azureml-inference-server-http` to version 0.8.0 in the inference container
I already had `azure-ai-ml` at the latest version 1.4.0.

Currently I still have timeouts at 5 seconds as the set value is not respected.
Thanks!

**Comment by jiaochenlu** [comment]
Our release is based on the aml extension. Could you check if your aml-extension version is 1.1.19 (the latest one)?

**Comment by dennisbakhuis** [comment]
Thanks again for your response @jiaochenlu.

It is not clear what extension you mean. If you are talking about `extension`, are you talking about the `azure-cli` extension? If so, the version is 2.14.0 (updated from 2.13.0 as stated in my minimal working example above.

If you mean Python packages, I am on the latest versions:
```pip freeze
azure-ai-ml==1.4.0
azure-common==1.1.28
azure-core==1.26.2
azure-datalake-store==0.0.52
azure-identity==1.12.0
azure-mgmt-core==1.3.2
azure-storage-blob==12.13.0
azure-storage-file-datalake==12.8.0
azure-storage-file-share==12.10.1
```

Could you please clearify what `aml-extension` you mean? Maybe it was not clear from my working example, but I am on Azure Python SDK v2.

Thanks!

**Comment by mojokb** [comment]
The same issue arises for me. May I know the progress?

**Comment by siyuZL** [comment]
@dennisbakhuis 
The version means the extension you installed in your K8S cluster. You can check it by calling:
`az k8s-extension list -c <cluster-name> -t managedClusters -g <resource-group-name>`
If you are using Arc-connected cluster, replace `managedClusters` to `connectedClusters`.

You should get an extension with `"extensionType": "microsoft.azureml.kubernetes"`. If this extension version is low, try to update it. Our latest version is 1.1.21.

**Comment by dennisbakhuis** [comment]
Thanks @siyuZL for the clarification. I now indeed see the installed extension.

Unfortunately, it is already at version "1.1.21" and the problem still exists with the minimum working example as stated above.

**Comment by siyuZL** [comment]
Hi @dennisbakhuis 
I have checked this scenario. 
I create an AKS and install the latest extension, use your deploy config and sample script. And try to deploy it by Python SDK and CLI.
In both ways, I can get a correct timeout. I think there may have some config problem in your cluster. Can you try to uninstall and reinstall the extension and try again?

**Comment by dennisbakhuis** [comment]
Hi @siyuZL,
After the following steps:
- removal of k8s-extension 
- installation of k8s-extension (same version as I removed)
- deletion of all deployments and endpoints running on that particular k8s
- creation and deployment of endpoint en models

I can confirm that the set timeout is respected. 

Thanks a lot for the help.
