### ISSUE TITLE
Error registering the environment definition. Code: 504

### ISSUE THREAD

**Issue by MiaZhang17** [Azure/azure-sdk-for-python#28691]
- **Package Name**: azureml-core
- **Package Version**: 1.43.0
- **Operating System**:Gitlab Linux
- **Python Version**: 3.8

**Describe the bug**
Before today, everything works fine

Today, when I try to register the AML environment, it shows erro 504 Gateway Time-out
I login to the AML Studio and can't get any environment information and I can't create any new environment

```
$ python register_train_env.py
SDK version: 1.43.0
Traceback (most recent call last):
  File "register_train_env.py", line 43, in <module>
    env.register(ws)
  File "/opt/miniconda/lib/python3.8/site-packages/azureml/core/environment.py", line 923, in register
    response = environment_client._register_environment_definition(environment_dict)
  File "/opt/miniconda/lib/python3.8/site-packages/azureml/_restclient/environment_client.py", line 103, in _register_environment_definition
    raise Exception(message)
Exception: Error registering the environment definition. Code: 504
: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
**To Reproduce**
```
env = Environment.from_dockerfile(name='feature_engineering', dockerfile='dockerfiles/Dockerfile')
env.register(ws)
env.build(ws)
```

**Expected behavior**
Yesterday, it registered successfully and run pipeline well

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @MiaZhang17 . We will investigate & get back to you asap.

cc @azureml-github

**Comment by MiaZhang17** [comment]
It suddenly works now.  Maybe because of the shutdown of azure services in southeast asia that day
