### ISSUE TITLE
Switching over to ElementTree will help partially with the following issues:

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-sdk-for-python#287]
Switching over to ElementTree will help partially with the following issues:
Cannot use Azure SDK with IronPython #241 
Improve performance of table storage (and more?) #254

**Comment by huguesv** [comment]
Service Management APIs still use minidom, but the others (service bus, storage) now use ElementTree.

**Comment by lmazuel** [comment]
We won't do that in ASM legacy library. The new ARM version use JSON, which avoid this issue.
