### ISSUE TITLE
Support for packaing >22.0 for azureml-core

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-python#28735]
**Is your feature request related to a problem? Please describe.**
We would like to use azureml-core with latest version of black 23.1.0. However, black 23.1.0 requires packaing >=22.0. But the azureml-core strictly requries `Requires-Dist: packaging (<22.0,>=20.0)`. Can this be updated so that azureml-core will be compatible with black 23.1.0?

Thanks 
Here is the poetry resolve logs 
```
Because consigli-ml-inference (0.1.0) @ file:///home/than/localdevcode/monopy/libs/consigli-ml-inference depends on azureml-core (^1.48.0)
 and no versions of azureml-core match >1.48.0,<2.0.0, consigli-ml-inference (0.1.0) @ file:///home/than/localdevcode/monopy/libs/consigli-ml-inference requires azureml-core (1.48.0).
And because azureml-core (1.48.0) depends on packaging (>=20.0,<22.0), consigli-ml-inference (0.1.0) @ file:///home/than/localdevcode/monopy/libs/consigli-ml-inference requires packaging (>=20.0,<22.0).
And because black (23.1.0) depends on packaging (>=22.0)
 and no versions of black match >23.1.0,<24.0.0, consigli-ml-inference (0.1.0) @ file:///home/than/localdevcode/monopy/libs/consigli-ml-inference is incompatible with black (>=23.1.0,<24.0.0).
So, because fdvclassifier depends on both consigli-ml-inference (0.1.0) @ ../../libs/consigli-ml-inference and black (^23.1.0), version solving failed.Collapse
```

**Describe the solution you'd like**
Upgrade the required library version for packaging.

**Describe alternatives you've considered**

**Additional context**

**Comment by jaga-work** [comment]
Account has been deleted. Required azureml-core version for further investigation.
