### ISSUE TITLE
Azure BatchServiceClient does not work with DefaultAzureCredential

### ISSUE THREAD

**Issue by endeesa** [Azure/azure-sdk-for-python#28739]
- **Package Name**:  azure-batch==13.0.0
- **Package Version**:  13.0.0
- **Operating System**: Ubuntu 20.04(WSL)
- **Python Version**:  3.9.16

- **Package Name**:  azure-identity
- **Package Version**:  1.12.0
- **Operating System**: Ubuntu 20.04(WSL)
- **Python Version**:  3.9.16

- **Package Name**:  msrest
- **Package Version**:  0.7.1
- **Operating System**: Ubuntu 20.04(WSL)
- **Python Version**:  3.9.16

**Describe the bug**
When trying to create a pool in a batch account using a token credential i get an error: "AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'"
Apparently this has been addressed previously, but I am using the latest packages as of 2023-02-10

**To Reproduce**
1. Login with az cli
2. Initialise DefaultCredential
3. Initialise BatchServiceClient using the batch account URL and the DefaultCredential oject
4. Try to create a pool or call any management operation on the BatchServiceClient  object

**Expected behavior**
The batch service client must be able to get authorization tokens from DefaultCredential

**Screenshots**
![image](https://user-images.githubusercontent.com/14007831/218155006-b449f8f1-6e57-4ef2-b7c1-0d0b7859867f.png)

**Additional context**
The problem seems to be happening on the msrest package. Is there any work in progress to address this please?

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Unfortunately, azure-batch has not migrated to track 2 yet. It does not work well with azure-identity library.

Instead, it takes msrestazure Credentials https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/batch/azure-batch/azure/batch/_batch_service_client.py#L57
