### ISSUE TITLE
Clarify ServiceBusSender().create_message_batch vs ServiceBusMessageBatch

### ISSUE THREAD

**Issue by EysteinWaade** [Azure/azure-sdk-for-python#28737]
The  ![docs](https://learn.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebusmessagebatch?view=azure-python) states: 
`Please use the create_message_batch method of ServiceBusSender to create a ServiceBusMessageBatch object instead of instantiating a ServiceBusMessageBatch object directly.`

Let's say I have a sender, that will be sending 1k messages to a topic, with unknown size. It is then tempting to write a generator like this:

```sh
from azure.servicebus import ServiceBusMessageBatch, ServiceBusMessage, ServiceBusSender
from azure.servicebus.exceptions import MessageSizeExceededError

def get_batches(
    batch_size_limit: int, messages: list[ServiceBusMessage]
) -> list[ServiceBusMessageBatch]:
    """Service bus batch generator"""
    batch = ServiceBusMessageBatch(max_size_in_bytes=batch_size_limit)
    for message in messages:
        try:
            batch.add_message(message)
        except MessageSizeExceededError:
            yield batch
            batch = ServiceBusMessageBatch(max_size_in_bytes=batch_size_limit)
            batch.add_message(message)
    yield batch


sender: ServiceBusSender = servicebus_client.get_topic_sender()
for service_bus_messages_batch in get_batches(
        messages=service_bus_messages, batch_size_limit=SERVICEBUS_BATCH_SIZE
    ):
        sender.send_messages(service_bus_messages_batch)
```

And I am trying to figure out if this is a bad idea.

**Comment by kashifkhan** [comment]
Hi @EysteinWaade , 

The reason to use `create_message_batch` is that this method also has access to the max size allowed on the link, obtained during negotiation with the service. It returns a batch that is right-sized (either the users specified size if its less than or equal to max size allowed or max size itself) for use and won't cause immediate errors when trying to send messages to a queue or topic. Using `ServiceBusMessageBatch` leaves you open to receiving a batch that might not work from the get go if the wrong size is passed in. 

A simple change to use create_message_batch gives you essentially the same thing in a safer manner :)

```python
from azure.servicebus import ServiceBusMessageBatch, ServiceBusMessage, ServiceBusSender
from azure.servicebus.exceptions import MessageSizeExceededError

def get_batches(
    batch_size_limit: int, messages: list[ServiceBusMessage], sender: ServiceBusSender
) -> ServiceBusMessageBatch:
    """Service bus batch generator"""
    batch = sender.create_message_batch(max_size_in_bytes=batch_size_limit)
    for message in messages:
        try:
            batch.add_message(message)
        except MessageSizeExceededError:
            yield batch
            batch = sender.create_message_batch(max_size_in_bytes=batch_size_limit)
            batch.add_message(message)
    yield batch


sender: ServiceBusSender = servicebus_client.get_topic_sender()
for service_bus_messages_batch in get_batches(
        messages=service_bus_messages, batch_size_limit=SERVICEBUS_BATCH_SIZE, sender
    ):
        sender.send_messages(service_bus_messages_batch)
```

**Comment by EysteinWaade** [comment]
> Hi @EysteinWaade ,
> 
> The reason to use `create_message_batch` is that this method also has access to the max size allowed on the link, obtained during negotiation with the service. It returns a batch that is right-sized (either the users specified size if its less than or equal to max size allowed or max size itself) for use and won't cause immediate errors when trying to send messages to a queue or topic. Using `ServiceBusMessageBatch` leaves you open to receiving a batch that might not work from the get go if the wrong size is passed in.
> 
> A simple change to use create_message_batch gives you essentially the same thing in a safer manner :)
> 
> ```python
> from azure.servicebus import ServiceBusMessageBatch, ServiceBusMessage, ServiceBusSender
> from azure.servicebus.exceptions import MessageSizeExceededError
> 
> def get_batches(
>     batch_size_limit: int, messages: list[ServiceBusMessage], sender: ServiceBusSender
> ) -> ServiceBusMessageBatch:
>     """Service bus batch generator"""
>     batch = sender.create_message_batch(max_size_in_bytes=batch_size_limit)
>     for message in messages:
>         try:
>             batch.add_message(message)
>         except MessageSizeExceededError:
>             yield batch
>             batch = sender.create_message_batch(max_size_in_bytes=batch_size_limit)
>             batch.add_message(message)
>     yield batch
> 
> 
> sender: ServiceBusSender = servicebus_client.get_topic_sender()
> for service_bus_messages_batch in get_batches(
>         messages=service_bus_messages, batch_size_limit=SERVICEBUS_BATCH_SIZE, sender
>     ):
>         sender.send_messages(service_bus_messages_batch)
> ```

That was my initial approach, but I keep running into the sender not being able to create a fresh batch. It seems that some internal state in the sender prevents it from creating a empty batch.

here is my test to reproduce it:
```python
from azure.servicebus import ServiceBusMessage, ServiceBusSender, ServiceBusMessageBatch
import json
import uuid
from ..servicebus_message_batch import get_batches
from unittest.mock import MagicMock

payload = [
    {"guid": 1234, "content": "test conten 1"},
    {"guid": 1234, "content": "test conten 2"},
    {"guid": 1234, "content": "test conten 3"},
]
msg_metadata = {
    "job_id": str(uuid.uuid4()),
    "project_id": 42,
}

BATCH_SIZE_LIMIT= 240000
def test_size_ofservicebus_message_with_sender():
    num_messages = 1000
    body = json.dumps(payload)
    sender = MagicMock(ServiceBusSender)
    sender.create_message_batch.return_value = ServiceBusMessageBatch(BATCH_SIZE_LIMIT)
    messages = [
        ServiceBusMessage(
            body=body, application_properties=msg_metadata, content_type="application/json"
        )
        for i in range(num_messages)
    ]
    batches = get_batches(sender=sender, batch_size_limit=BATCH_SIZE_LIMIT, messages=messages)
    actual_num_messages = sum([batch._count for batch in batches])

    assert actual_num_messages == num_messages
```

**Comment by EysteinWaade** [comment]
After running a similiar test with a live connection to a service bus sender, I am not able to reproduce my issue. Must be a issue with my mocking of the service bus sender
