### ISSUE TITLE
Azure DL Storage Gen2 get_paths timeout

### ISSUE THREAD

**Issue by cmditch** [Azure/azure-sdk-for-python#28748]
- **Package Name**: 
 `from azure.storage.filedatalake import DataLakeServiceClient`
- **Package Version**: 
 12.9.1
- **Operating System**:
 macOS 12.6.1 / Running code inside ubuntu dev-container in vscode
- **Python Version**: 
 3.9.16

**Describe the bug**
Very similar to https://github.com/Azure/azure-sdk-for-python/issues/10219
`filesystem_client.get_paths("foo/bar/baz", timeout=10)` consistently fails, timing out after about 2 minutes. Also, setting the timeout kwarg seems to have no effect on the length of the timeout.
The issue happens intermittently, but frequently. I've gotten the function to work here and there, but when it starts timing out in consistently keeps timing out.

**To Reproduce**
```
paths = filesystem_client.get_paths("foo/bar/baz", timeout=10)`
print(list(paths))
```

**Expected behavior**
Expect to see a list of paths printed. Also expect it to timeout after 10 seconds instead of 2 mintues.

**Additional context**
Here is the exception thrown after about 2 mintues.
```
azure.core.exceptions.HttpResponseError: (OperationTimedOut) Operation could not be completed within the specified time.
RequestId:d9354267-601f-0002-23a0-3d5e46000000
Time:2023-02-10T22:41:49.6198201Z
Code: OperationTimedOut
Message: Operation could not be completed within the specified time.
RequestId:d9354267-601f-0002-23a0-3d5e46000000
Time:2023-02-10T22:41:49.6198201Z
```

Thanks for any assistance or fixes you can provide!

**Comment by annatisch** [comment]
Thank you for the report @cmditch!
Taking a look at the code - it seems that the `timeout` parameter _is_ being passed to the service from the client... however the `timeout` in this case refers to the service timeout, rather than the client timeout. I wonder if it's possible that the retry policy is kicking in, and even if the service is respecting the timeout value, the retry policy keeps reattempting the request which ultimately prolongs the total fail time to the 2 minutes you're observing?
You could test this by attempting to reduce the number of retry attempts using the optional kwargs described here (these kwargs can be used either at the Client constructor level, or on a per-operation level): https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core#configurations

It seems from the issue that you linked to, that account level throttling may play a role in the OperationTimeouts, @jalauzon-msft , we may need to run the request ID's by the service team for more info :)

**Comment by cmditch** [comment]
Thanks for the reply @annatisch 

> `timeout` in this case refers to the service timeout, rather than the client timeout

Ah yes, interesting. Good to know what timeout means in this instance. Usually, as an API consumer, I would assume timeout to mean "if my code has to wait more than X amount of time, give up".

> account level throttling may play a role in the OperationTimeouts

Also good to know. The issue is very intermittent, but also I'm not making a ton of requests so to hit some kind of throttling would be very odd. I believe am connecting through a service provider account we've set up, as I'm using ClientSecretCredentials. Though fwiw I've tried to get around the issue by using a plain old storage account key and still no luck.

Let me know if you have any luck finding out why I'm hitting the `OperationTimeouts`. I haven't been hitting them in the past week fwiw, but I'm also performing _very_ infrequent requests atm.

Here is my client initialization code in case it's helpful.
```
def _init_datalake_client() -> FileSystemClient:  # pragma: no cover
    client = _initialize_storage_account()
    filesystem_name = env.ClusterEnv.get().blob_container
    filesystem = client.get_file_system_client(filesystem_name)
    return filesystem


def _initialize_storage_account() -> DataLakeServiceClient:  # pragma: no cover
    cluster_env = env.ClusterEnv.get()
    ad_creds = ClientSecretCredential(
        tenant_id=cluster_env.azure_tenant_id,
        client_id=cluster_env.azure_client_id,
        client_secret=cluster_env.azure_client_secret.get_secret_value(),
    )

    client = DataLakeServiceClient(
        account_url=f"https://{cluster_env.azure_storage_account_name}.dfs.core.windows.net",
        credential=ad_creds,
    )
    return client
```

**Comment by jalauzon-msft** [comment]
Hi @cmditch Coury, sorry for my delay.

I see in your original post you are setting your `timeout` to 10 seconds and as Anna mentioned, this is the server-side timeout where if the service can't complete that operation in that amount of time, it will return the `OperationTimedOut` error. I believe Anna is also correct in saying that these are automatically retried so, given our default retry settings, that's probably where your 2-minute wait time is coming from.

There is small chance the service is actually expected to time out on your operation as sometimes listing operations can be very expensive. Here are some questions to help gauge if that's the case:
- How many total items are in the container that you are listing?
- Do you have soft-delete and/or blob versioning enabled on your account? If so, is there a chance there are a ton of old versions or soft-deleted blobs in the container? The service needs to iterate these even if they are not returned.

A couple of things to try:
- Increasing your `timeout` slightly. Depending on how intermittent this is, there is a chance you are right on the edge of the timeout and increasing to maybe 15 seconds would help mitigate the intermittent error. The maximum I believe is 30 seconds.
- You can also try playing around with the `max_results` parameter of `get_paths` which changes the page size for the listing operation. The default value is 5000 so it's possible reducing this will reduce the chances of a given page timing out (at the cost of more network requests).

I am also happy to look into the service logs for you, but our backend logs are cleared on a rolling basis and are usually only kept for a couple of days. Therefore, the request id from your initial post is likely gone but if you can provide me with a recent example, I can look at the backend logs for anything unusual. I will need the `RequestId` from the response. Thanks
