### ISSUE TITLE
NetworkSecurityGrouop - flowLogs is type list[str] not type list[FlowLog]

### ISSUE THREAD

**Issue by dslagle** [Azure/azure-sdk-for-python#28740]
The description for the attribute states the property is a list of references, however the type points to a complete FlowLog object.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3a7a10-0407-010e-b5f6-743b53efcd14
* Version Independent ID: 5d129597-7f6c-ee27-34bb-73783c68523a
* Content: [azure.mgmt.network.v2020_08_01.models.NetworkSecurityGroup class](https://learn.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2020_08_01.models.networksecuritygroup?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-network/azure.mgmt.network.v2020_08_01.models.NetworkSecurityGroup.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-network/azure.mgmt.network.v2020_08_01.models.NetworkSecurityGroup.yml)
* Service: **network-watcher**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by msyyc** [comment]
Hi @dslagle Do you mean the description is not accurate?
![image](https://user-images.githubusercontent.com/70930885/218938396-ef28a8b0-067d-4c1c-b91a-041caf41b1d8.png)

**Comment by dslagle** [comment]
Apologies, I missed the notification for this. The description is correct to me. The type, however, indicates that full `FlowLog` information is returned when really the API only returns a reference to each flow log. Hence I think the type should be changed from `list[FlowLog]` to `list[str]`. Unless I'm misunderstanding what the types represent. Please let know, thanks!

**Comment by Wzb123456789** [comment]
The `FlowLog` in `list[FlowLog]` represents a model type of data, not `str` type.
![image](https://user-images.githubusercontent.com/51410816/221737740-3cd1f57b-e610-472f-b125-4c2f2245fae5.png)

**Comment by msyyc** [comment]
Hi @dslagle, azure-mgmt-network is generated with [swagger](https://github.com/Azure/azure-rest-api-specs/blob/d1b57073903fc64486bf53a37f061e5c7ab9ca31/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/networkSecurityGroup.json#L908-L915) automatically which shows type of `flow_logs` is `array` of `FlowLog`
