### ISSUE TITLE
trouble importing RecoveryServicesBackupClient from azure.mgmt.recoveryservicesbackup

### ISSUE THREAD

**Issue by aernan** [Azure/azure-sdk-for-python#28757]
- library name: azure.mgmt.recoveryservicesbackup
- python version: 5.1.0: 
- linux version: Ubuntu 22.04 LTS:
- library version: 3.10.6: 

**Describe the bug**

**To Reproduce**
Writing a new Ansible playbook to ensure Azure CLI and permissions are setup correctly on host. 
Was not able to find any pre-made playbook and also very new to Ansible I wrote this small script. 

`- name: Verify Azure account details are setup correclty for publishing images
  hosts: REDACTED
  gather_facts: true
  tasks:
    - name: Get facts for all subscriptions, including ones that are disabled.
      azure.azcollection.azure_rm_subscription_info:
        all: True
      register: az_info

    - name: Print all account facts
      debug:
        msg: "{{ az_info }}"`

When running the script against this remote host I got a string of errors for missing python libraries. 
Installing the libraries one at a time with pip
`pip3 install packaging 
pip install msrest
pip install msrestazure
pip install azure.cli
pip install azure.storage.blob
pip install azure.mgmt.automation
pip install azure.mgmt.recoveryservicesbackup`

still results in the following error: 

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/home/ubuntu/.local/lib/python3.10/site-packages/azure/mgmt/recoveryservicesbackup/__init__.py)
fatal: [gce-packer-builder]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on REDACTED's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}`

Google search turned up this gem: 
https://github.com/ansible-collections/azure/issues/805

Caused me to attempt to install a another package which is now deprecated
`pip install 'ansible[azure]'`

Going direct to source (Microsoft): https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-recoveryservicesbackup-readme?view=azure-python

I installed the following python packages per the article: 
`pip install azure-mgmt-recoveryservicesbackup
pip install azure-identity`

manually reproducing the issue with interactive python3 on the host
`>>> from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/home/ubuntu/.local/lib/python3.10/site-packages/azure/mgmt/recoveryservicesbackup/__init__.py)
>>> `

**Expected behavior**
library should import

**Comment by annatisch** [comment]
Thanks for the report @aernan!
I have tagged the maintaining team to take a look :)

**Comment by annawicher** [comment]
it seems like I have the same issue, ubuntu 22.4 python 3.10.7 ansible core 2.14.2

`
TASK [az-network : create resource group] **************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.10/dist-packages/azure/mgmt/recoveryservicesbackup/__init__.py)
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on anw's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}`

**Comment by msyyc** [comment]
Hi @aernan Please try:
```python
from azure.mgmt.recoveryservicesbackup.activestamp import RecoveryServicesBackupClient
```
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/recoveryservices/azure-mgmt-recoveryservicesbackup#authentication

**Comment by annawicher** [comment]
@msyyc import OK:
Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.mgmt.recoveryservicesbackup.activestamp import RecoveryServicesBackupClient
>>> 

but still get the same error from script:

`TASK [az-network : create resource group] **************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.10/dist-packages/azure/mgmt/recoveryservicesbackup/__init__.py)
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on anw's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}`

**Comment by msyyc** [comment]
![image](https://user-images.githubusercontent.com/70930885/219248293-20c577c4-b654-4282-a424-dde90110d089.png)
`.activestamp`

**Comment by annawicher** [comment]
This is part of my code:
```
name: create resource group
  azure.azcollection.azure_rm_resourcegroup:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    name: '{{ resource_group }}'
    location: westeurope
    
```
   I'm not sure what and where I should update, could you please help?

**Comment by msyyc** [comment]
Here is sample about how the use the package: https://github.com/Azure-Samples/azure-samples-python-management/tree/main/samples/recoveryservicesbackup

**Comment by joechancellor** [comment]
Someone can probably get some interweb points:

    from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
to:
    from azure.mgmt.recoveryservicesbackup.activestamp import RecoveryServicesBackupClient
https://github.com/ansible-collections/azure/blob/c889f64aacd5243dd36ec0552a6c109f6feb3416/plugins/module_utils/azure_rm_common.py#L275
    import azure.mgmt.recoveryservicesbackup.activestamp.models as RecoveryServicesBackupModels
https://github.com/ansible-collections/azure/blob/c889f64aacd5243dd36ec0552a6c109f6feb3416/plugins/module_utils/azure_rm_common.py#L276

**Comment by hiaga** [comment]
> /unresolve

Hi @dkopec-mri, why do you want to unresolve this ? did the above [solution](https://github.com/Azure/azure-sdk-for-python/issues/28757#issuecomment-1448729884) didn't work ?
