### ISSUE TITLE
[Bug] Azure Metrics query serialization failure

### ISSUE THREAD

**Issue by kovarikthomas** [Azure/azure-sdk-for-python#28768]
- **Package Name**: azure-monitor-query
- **Package Version**:  1.1.0
- **Operating System**: Windows
- **Python Version**: 3.10.9

**Describe the bug**
A successful response from Azure Metrics fails internal serialization to MetricValue class. Upon further investigation, I discovered that this [line](https://github.com/Azure/azure-sdk-for-python/blob/c77510b70d4a836822ab0171cd546ee5123c76a2/sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py#L138) attempts to locate "time_stamp" within the HTTP response. However, the actual response from Azure Metrics has key named "timeStamp" and not "time_stamp" which leads to the error.

**To Reproduce**
1. Fails when querying any metric for Azure Cosmos DB.

**Comment by kashifkhan** [comment]
Hi @kovarikthomas , thank you for the feedback. We will investigate and get back to you asap.

**Comment by pvaneck** [comment]
Apologies for the regression! Fixed in the recently published [`1.1.1`](https://pypi.org/project/azure-monitor-query/1.1.1/) release (thanks @jamespic!) and a PR for improving for the test coverage was opened: https://github.com/Azure/azure-sdk-for-python/pull/28788.
