### ISSUE TITLE
Azure Communications Phone Numbers - Invalid Capabilities 

### ISSUE THREAD

**Issue by mclarkex** [Azure/azure-sdk-for-python#28779]
- **Package Name**: azure-communication-phonenumbers 1.0.1
- **Package Version**:  1.0.1
- **Operating System**: Windows 10 
- **Python Version**:  3.10.8

**Describe the bug**
While using Azures communications services when using the capabilities function as shown in the following documentation:

- https://pypi.org/project/azure-communication-phonenumbers/
- https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/telephony/get-phone-number?tabs=windows&pivots=programming-language-python

An error occurs: (InvalidInput) Unsupported capabilities requested.

This seems self-explanatory but the default values have been used. 

Using the package without capabilities works as expected.  

The full log is attached. 

**To Reproduce**
1. Write a Python script using azure.communication.phonenumbers package 
2. Create capabilities config as described in the documentation 
3. Run scripts to return phone numbers 
4. Error returns with (InvalidInput) Unsupported capabilities requested.

**Expected behavior**
a list of phone numbers that meet the criteria is returned. 

This works: 

```python 
purchased_phone_numbers = phone_numbers_client.list_purchased_phone_numbers()
for acquired_phone_number in purchased_phone_numbers:
    print(acquired_phone_number.phone_number)
```

This does not:

```python 
try:
    print('Azure Communication Services - Phone Numbers Quickstart')
    phone_numbers_client = PhoneNumbersClient.from_connection_string(connection_string)
    capabilities = PhoneNumberCapabilities(
        calling = PhoneNumberCapabilityType.INBOUND,
        sms = PhoneNumberCapabilityType.INBOUND_OUTBOUND
    )
    search_poller = phone_numbers_client.begin_search_available_phone_numbers(
        "GB",
        PhoneNumberType.TOLL_FREE,
        PhoneNumberAssignmentType.APPLICATION,
        capabilities,
        polling = True
    )
    search_result = search_poller.result()
    print ('Search id: ' + search_result.search_id)
    phone_number_list = search_result.phone_numbers
    print('Reserved phone numbers:')
    for phone_number in phone_number_list:
        print(phone_number)

except Exception as ex:
    print('Exception:')
    print(ex)
```

**Screenshots**

Some sensitive date was removed. Dev environment regardless. 

[IVRHub.log](https://github.com/Azure/azure-sdk-for-python/files/10723864/IVRHub.log)

**Additional context**

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by danielortega-msft** [comment]
Hello @mclarkex and thank you for your feedback. 

Currently, we do not support SMS capabilities in the UK. You could try using `PhoneNumberCapabilityType.NONE` for SMS, or searching for numbers in a country that does support it. For more information, here's a list document listing the available capabilities for each country: https://learn.microsoft.com/en-us/azure/communication-services/concepts/numbers/sub-eligibility-number-capability.

Hope this helps!

**Comment by mclarkex** [comment]
Thanks for looking into this. Please close the issue as resolved.

**Comment by navba-MSFT** [comment]
@mclarkex Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
