### ISSUE TITLE
Batch download/upload support

### ISSUE THREAD

**Issue by Laleee** [Azure/azure-sdk-for-python#28805]
Hello,

Since we have batch delete supported (delete_blobs on ContainerClient), have you considered adding batch download/upload support to the library?
If yes, when might we expect it?

**Comment by kashifkhan** [comment]
Thank you for the feedback @Laleee . Ill route this to the proper folks on the storage sdk.

**Comment by vincenttran-msft** [comment]
Hi @Laleee Lazar, I have spoken with the team, and it sounds like this is very low on the priority list (and even possibly likely to never be implemented in the near future). With that being said, I have noted that there is at least interest in the feature, and if this feature becomes something that more and more users would like, it may move up in the priority list.

With that being said, I will close out the issue.
Thanks!
