### ISSUE TITLE
Getting an error in sample_abstractive_summary.py - textanalyticsclient does not have begin_analyze_actions

### ISSUE THREAD

**Issue by vyakhya** [Azure/azure-sdk-for-python#28825]
- **Package Name**: 
- **Package Version**: 
- **Operating System**: 
- **Python Version**: 

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

Language Quickstart Feedback
* Content: [Quickstart: using document summarization and conversation summarization (preview) - Azure Cognitive Services](https://learn.microsoft.com/azure/cognitive-services/language-service/summarization/quickstart?pivots=programming-language-python)
* Content Source: [articles/cognitive-services/language-service/summarization/quickstart.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/cognitive-services/language-service/summarization/quickstart.md)
* Section: **Code-example**
* Service: **cognitive-services**
* Sub-service: **language-service**

**Comment by kristapratico** [comment]
Hi @vyakhya thanks for your issue. Which version of `azure-ai-textanalytics` are you using? To use abstractive summarization, you need version [5.3.0b1](https://pypi.org/project/azure-ai-textanalytics/5.3.0b1/) and you must call it through begin_analyze_actions like in this sample [here](https://github.com/Azure/azure-sdk-for-python/blob/azure-ai-textanalytics_5.3.0b1/sdk/textanalytics/azure-ai-textanalytics/samples/sample_abstract_summary.py#L66). Before you can call the API, you also must be approved to use the gated preview by sending a request with this [form](https://aka.ms/applyforgatedsummarizationfeatures). 

Another note - this repo is used for active development of the client libraries so not everything you see in the repo will be released yet. For example, the code in sample_abstractive_summary.py is planned for the next release. Let me know if this helps.

**Comment by vyakhya** [comment]
Thanks for the quick reply @kristapratico. I was able to use the code in sample_abstract_summary.py. Thanks.
