### ISSUE TITLE
Cannot specify experiment for scheduled Azure Machine Learning job if created via Python SDK2

### ISSUE THREAD

**Issue by jdb78** [Azure/azure-sdk-for-python#28858]
- **Package Name**: "azure-ai-ml"
- **Package Version**: "1.4.0"
- **Operating System**: ubuntu
- **Python Version**: 3.9

**Describe the bug**
When scheduling a job in azure machine learning, the experiment is "Default" and not the one specified in the job.

**To Reproduce**
When creating a new job like this and scheduling it:

```python
    pipeline_job = pipeline()
    returned_job = ml_client.jobs.create_or_update(
        pipeline_job, experiment_name="test"
    )

    trigger = CronTrigger(
        expression="0 2 * * 1-5",  # At 2am Monday to Friday
        start_time=datetime.datetime.utcnow(),
        time_zone=TimeZone.UTC,
    )
    print("schedule labelling")
    schedule = JobSchedule(name="scheduled_job", trigger=trigger, create_job=returned_job.name)
    ml_client.schedules.begin_create_or_update(schedule).wait()
```
The schedule is for the experiment "Default"

**Expected behavior**
The schedule should be for the experiment "test". If the job is scheduled via the Azure Machine Learning UI, the experiment is as expected "test".

**Comment by kashifkhan** [comment]
Thank you for the feedback @jdb78 . We will investigate & get back to you asap.

cc @azureml-github

**Comment by brynn-code** [comment]
@jdb78 Confirmed this is a client-side issue, thank you for reporting this, we appreciate your feedback. The bug will be fix and released in the next version.
