### ISSUE TITLE
Azure ML Python SDK v2 MLTable v1.1.0 no table save function

### ISSUE THREAD

**Issue by corticalstack** [Azure/azure-sdk-for-python#28884]
- **Package Name**: mltable
- **Package Version**:  1.1.0
- **Operating System**: 
- **Python Version**:  3.10

**Describe the bug**
Objective is to register an AML data asset from a folder of csv files in the default AML data store, using SDK v2.

Running a notebook using python 3.10 and AML sdk v2, attached to an Azure Machine Learning compute instance, that reads a folder of csv files into an mltable. can do a tbl.show() to show top rows in ml table. Objective is to create a registered data asset from the mltable. 

I am following the documentation here:
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-create-data-assets?tabs=Python-SDK#create-a-table-asset

Which then indicates that before a data asset can be registered, I need to author an ML table file:
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-mltable?tabs=cli%2Cpandas%2Cadls#authoring-mltable-files

However, after importing mltable, reading the csv's into mltable, I dont have have the save function, getting the error:

```
      1 # save MLTable file in the data directory
----> 2 tbl.save(".")

AttributeError: 'MLTable' object has no attribute 'save'
```

**To Reproduce**

```
!pip install -U mltable
import mltable

# Get the default datastore
default_ds = ml_client.datastores.get_default()

path = {
    'pattern': ('azureml:/' + default_ds.id + '/paths/data-diabetes/*.csv').replace('providers/Microsoft.MachineLearningServices/', '').lower()
}

# Create an mltable from the path on the datastore
tbl = mltable.from_delimited_files(paths=[path])
tbl.show()

# save MLTable file in the data directory
tbl.save(".")

```

```
$ pip show mltable
Name: mltable
Version: 1.1.0
Summary: Contains MLTable loading and authoring apis for the mltable package.
Home-page: https://docs.microsoft.com/python/api/overview/azure/ml/?view=azure-ml-py
Author: Microsoft Corp
Author-email: None
License: Proprietary https://aka.ms/azureml-preview-sdk-license 
Location: /anaconda/envs/azureml_py38/lib/python3.8/site-packages
Requires: jsonschema, python-dateutil, PyJWT, pyyaml, pytz, msrest, azure-mgmt-core, cryptography, azure-core, azureml-dataprep
```

**Expected behavior**
Expect an MLTABLE yml schema to be written to the data store directory

Sidenote: The documentation and working SDK v2 examples could really be improved, examples with MLtable already have an MLTABLE yml file present, so effectively misses a step.

Thanks

**Comment by nthandeMS** [comment]
@vipinnair22 , can you investigate this issue?

**Comment by vipinnair22** [comment]
@ChunyuMSFT, @shuyums2, @QianqianNie could you please help with this?

**Comment by ChunyuMSFT** [comment]
@corticalstack , the "save" function is in MLTable object, given you upgraded mltable package inside the notebook session, can you try restart the kernel? The version showed by pip might not be the version you are using.

**Comment by natehofmann** [comment]
@corticalstack I was unfortunately unable to recreate this issue with the details you provided. Lik @ChunyuMSFT, just to double check have you tried simple fixes like restarting the kernel, restarting the compute node, retrying on a new & different compute node, etc. If you have, could you please provide some other setup info such as the types of compute node used?
