### ISSUE TITLE
AzureML accessing datastore during pipeline job fills up disk space due to caching 

### ISSUE THREAD

**Issue by palmerss** [Azure/azure-sdk-for-python#28946]
- **Package Name**: 
    azure-ai-ml
    mldesigner

- **Package Version**: 
     1.2.0
     0.1.0b9

- **Operating System**:
- **Python Version**: 
    3.8.x

**Describe the bug**

Currently I am running a training job through an AzureML pipeline where one of the inputs to my pipeline is a URI path (specified as a uri_folder input type) that points to  a blob storage data store where I access my data files to train my algorithm (100s of gigs worth). I had noticed that after a couple hours of training my algorithm that the disk space for the job eventually depletes and the job crashes due to no more disk space available.

Upon further investigation I'v narrowed down the culprit of the disk space to be a folder that is mounted to the jobs docker container
If I docker exec into the container and run 

`df`

I notice that the /dev/sda1/ filesystem is the one that is getting bloated....
I go ahead and mount /dev/sda1 to a custom directory in the docker contariner (EX. /mnt/foobar/)
upon navigating to /mnt/foobar the path being bloated is
`/mnt/foobar/azureml/cr/j/<SOMEHASH>/cap/data-capability/tmp/.tmp<some short hash>/whole_file_cache/`

inside of this folder looks like its a cache of all of the files that I am reading in from the mounted data store, and as expected...if I delete this cache while the job is running it lowers the disk usage to acceptable ranges and then slowly starts to build back up.

Am I able to disable this cache or read data from the datastore without caching?

**Expected behavior**
That I'm able to turn off or limit the data caching such that the cache doesn't fill up disk and crash

**Comment by palmerss** [comment]
Update on my part on this one, it would seem that making an AzureML dataset out of the directory (and subdirectories) of my data directory and accessing it as an input parameter in "direct" mode has solved the caching issue...

Unsure if I need to close this issue or if there's still desire for there to be a way to disable this sort of caching

**Comment by nthandeMS** [comment]
@palmerss It sounds like you have managed to find a solution by yourself. I'm going to close this issue for now. You can reopen it if the same problem persists.

@vipinnair22 FYI

**Comment by palmerss** [comment]
@nthandeMS I haven't found a solution for this just yet, I added an edit to my last comment.. I was too quick to pull the trigger on thinking that I figured it out.

**Comment by nthandeMS** [comment]
@palmerss Since your issue persists, I have reopened this for you.

**Comment by vipinnair22** [comment]
@ChunyuMSFT, @shuyums2, @QianqianNie, could you please help with this?

**Comment by ChunyuMSFT** [comment]
@palmerss is it possible to share your run id? How large is the data you were trying to read in the job and how much space does the disk have? Also, the cache should be automatically cleaned if you close the file after reading is finished.

**Comment by palmerss** [comment]
> 

Unfortunately am unable to share my run id here as its associated with proprietary code from my company. 

The data is packaged in .npy files that are about 4.5 MB in size each file, and there's about 21,000 of these files

Earlier tests I ran where I tracked the number of open file descriptors indicated that the number of open file descriptors was not growing, but I'm going to try some different methods / libraries on trying to measure that to be sure

**Comment by lschaupp** [comment]
Having the same issue as the user above :) So reopening this ticket. In my case I am reading from a datastore and compiling a video using FFMPEG. The video is stored locally - but the images from the datastore used for the video is still being kept in the cache (and filling it up).

**Comment by achauhan-scc** [comment]
As design and no active work is happening. closing as obsolete
