### ISSUE TITLE
KeyVaultCertificate.cer property returns bytesarray instead of bytes

### ISSUE THREAD

**Issue by deepaerial** [Azure/azure-sdk-for-python#28959]
- **Package Name**: 
   `azure-keyvault-certificates`
- **Package Version**: 
   `4.6.0`
- **Operating System**:
   `Windows`
- **Python Version**: 
   `3.9.6`

**Describe the bug**
I'm trying to fetch imported certificate from Azure Key Vault. According to source code property `cer` of KeyVaultCertificate should return `bytes` object  or `None`:
```python
    @property
    def cer(self):
        # type: () -> Optional[bytes]
        """The CER contents of the certificate.

        :rtype: bytes or None
        """
        return self._cer
```
But in reality if throw `pdb` and try to read type of `KeyVaultCertificate.cer` you will get `byteaaray`:
```python
(Pdb++) type(cert.cer)
<class 'bytearray'>
```
**To Reproduce**
1. Import certificate to Azure Key Vault
2. Load certificate using code below:
```python
from azure.identity import DefaultAzureCredential
from azure.keyvault.certificates import CertificateClient

KEY_VAULT_NAME = "kv-test"  # replace with your key vault name
CERTIFICATE_NAME = "example"  # replace with your imported certificate name
key_client = CertificateClient(
      vault_url=f"https://{KEY_VAULT_NAME}.vault.azure.net/",
      credential=DefaultAzureCredential(),
)
cert = key_client.get_certificate(CERTIFICATE_NAME )
print(type(cert.cer))
```
**Expected behavior**
`KeyVaultCertificate.cer` should be of type `Optional[bytes]`

**Comment by kashifkhan** [comment]
Thank you for the feedback @deepaerial . We will investigate and get back to you asap.

**Comment by mccoyp** [comment]
Hi @deepaerial, thank you for opening an issue! I just double-checked, and you're correct about the discrepancy. I'll open a PR to fix this right away and link it to this issue.
