### ISSUE TITLE
Unable to query blob for selected column in parquet file

### ISSUE THREAD

**Issue by aurojaren** [Azure/azure-sdk-for-python#28963]
- **Package Name**:  azure-storage-blob
- **Package Version**:  12.13.1
- **Operating System**: Windows 21H2
- **Python Version**:  3.9.13

**Describe the bug**
When I try to query a parquet blob for the content of a specific column the results it cut short.

**To Reproduce**
1. Open a python console and specify the variables `connection_string` and `container_name`
2. Run the following code to create, upload and verify the content of a test.parquet blob:
```
import io
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
from azure.storage.blob import BlobServiceClient

blob_service = BlobServiceClient.from_connection_string(connection_string)
container = blob_service.get_container_client(container_name)
path = 'test.parquet'

np.random.seed(0)
data = {'range':np.arange(10), 'rand':np.random.rand(10)}
table_0 = pa.table(data)
with io.BytesIO() as buf_0:
    pq.write_table(table_0, buf_0)
    buf_0.seek(0)
    container.upload_blob(path, buf_0, overwrite=True)
blob = container.get_blob_client(path)

with io.BytesIO() as buf_1:
    blob.download_blob().readinto(buf_1)
    buf_1.seek(0)
    table_1 = pq.read_table(buf_1)
print(table_1)
```

4. Run the following code to see that when selecting the wildcard (*) the query work: 
```
data_reader = blob.query_blob(f'SELECT * FROM BlobStorage',
                              blob_format='ParquetDialect',
                              output_format='DelimitedJsonDialect',
                       )
data = data_reader.readall()
print(data)
```
This prints the following:
```
b'{"range":0,"rand":0.5488135039273248}\n{"range":1,"rand":0.7151893663724195}\n{"range":2,"rand":0.6027633760716439}\n{"range":3,"rand":0.5448831829968969}\n{"range":4,"rand":0.4236547993389047}\n{"range":5,"rand":0.6458941130666561}\n{"range":6,"rand":0.4375872112626925}\n{"range":7,"rand":0.8917730007820798}\n{"range":8,"rand":0.9636627605010293}\n{"range":9,"rand":0.3834415188257777}\n'
```

5. Run the following code to see that when selecting a named column the query doesn't work: 
```
data_reader = blob.query_blob(f'SELECT rand FROM BlobStorage',
                              blob_format='ParquetDialect',
                              output_format='DelimitedJsonDialect',
                       )
data = data_reader.readall()
print(data)
```
This prints the following:
```
b'{"rand":'
```
 
**Expected behavior**
I would expect step 5 to print the following:
```
b'{"rand":0.5488135039273248}\n{"rand":0.7151893663724195}\n{"rand":0.6027633760716439}\n{"rand":0.5448831829968969}\n{"rand":0.4236547993389047}\n{"rand":0.6458941130666561}\n{"rand":0.4375872112626925}\n{"rand":0.8917730007820798}\n{"rand":0.9636627605010293}\n{"rand":0.3834415188257777}\n'
```

**Comment by kashifkhan** [comment]
Thank you for the feedback @aurojaren . We will investigate and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @aurojaren, apologies for the delay. The parquet file format is actually still in preview/beta from the service team and therefore the feature may not work as expected. We have chatted with the eservice, and they think this issue is likely a known issue with parquet on their side. They were not able to share a timeline about this getting fixed though as the feature is still in preview with no official launch date. Sorry I don't have a better answer this and can't really offer a workaround or timeline for the service team to address the issue.

Also sorry for the confusion here and the lack of documentation around this being in preview. There was a bit of a mix up between us and the service team and this was probably released in the SDK before it should have been.

**Comment by jalauzon-msft** [comment]
Closing as parquet is in beta and the service would be responsible for fixing any issues. Service is aware of this issue.
