### ISSUE TITLE
Duplicate type annotation in azure-storage-file-datalake leads to downstream type checking error

### ISSUE THREAD

**Issue by jenshnielsen** [Azure/azure-sdk-for-python#28964]
- **Package Name**: azure-storage-file-datalake 
- **Package Version**:  12.10.0
- **Operating System**: Windows 11
- **Python Version**:  Python 3.10 and 3.11

**Describe the bug**
The async FileSystemClient defined [here]( 
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py#L88)

has its `__init__` methods return type defined both as an inline type annotation and as a type comment.

This leads to an error when typechecking a downstream package using mypy

```
...\Lib\site-packages\azure\storage\filedatalake\aio\_file_system_client_async.py:83: error: Function has duplicate type signatures  [syntax]
```
**To Reproduce**

1. Run mypy on a file containing this import

```
from azure.storage.filedatalake.aio import FileSystemClient
```

**Expected behavior**

No error 

**Additional context**

Mypy 1.0.1

**Comment by kashifkhan** [comment]
Thank you for the feedback @jenshnielsen . We will investigate and get back to you asap.

**Comment by vincenttran-msft** [comment]
Hi @jenshnielsen Jens, thanks for your contribution! I have gone ahead and put out a PR to address this issue (and another instance of the duplicate type annotation found in another file). I will attach the pull request to this issue and this issue will be closed out once the PR is merged. Thanks again for your contribution 😄

**Comment by jalauzon-msft** [comment]
@jenshnielsen Jens, just wanted to update that we released the fix for this issue today in a patch release. Version `12.10.1` should have the fix. Thanks.
