### ISSUE TITLE
multi tenant_id client creation with get_client_from_cli_profile(SubscriptionClient) fails 

### ISSUE THREAD

**Issue by kbroughton** [Azure/azure-sdk-for-python#2898]
If I have more than one tenant -> many subscriptions, then
    client = get_client_from_cli_profile(SubscriptionClient)
will fail if my most recent `az login` was for the non-subscription account.

Failure error: CLIError: Credentials have expired due to inactivity. Please run 'az login'

Steps to reproduce:
    az account clear
    az login  # for the default subscription account
    get_client_from_cli_profile(SubscriptionClient)   # success
    az login  # for a different email with different tenant
    get_client_from_cli_profile(SubscriptionClient)    # fails
    az login  # for the default subscription account again
    get_client_from_cli_profile(SubscriptionClient)    # success

Expected behaviour:
get_client_from_cli_profile should always pull the default subscription client regardless of the last login.  

Suggestion:
get_client_from_cli_profile should take a `subscription_id` argument so that it could be selected from accessTokens.json or some other .azure file.

def get_client_from_cli_profile(SubscriptionClient, subscription_id=None):
'''If subscription_id is supplied, retrieve a client for it, otherwise, get the default subscription client''' 

Currently, get_client_from_cli_profile does accept subscription_id as a kwarg, but it does not affect the result.

**Comment by lmazuel** [comment]
Hi @kbroughton !
That's by design, get_client_from_cli_profile is using the active subscription and tenant, as documented:
https://docs.microsoft.com/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-cli

The CLI has not public API in my knowledge to read the configuration file. What you can do is use the the second method get_client_from_auth_file and creates two files for your two configurations.

FYI @yugangw-msft if he has any comments.

**Comment by kbroughton** [comment]
Thanks for your reply.  My particular situation is one where i have login credentials for a readonly account (pen-testing) and do not have privileges to create the service principal required for the auth_file login.  lmazuel@microsoft.com recommended using get_client_from_cli_profile and passing in the subscription_id, but as I noted in the last line of the issue, passing subscription_id, although allowed by the function signature via kwargs, did not have any affect.

hacking the code for get_client_from_cli_profile() by starting with a call
set_active_subscription()
with the passed in subscription_id did work for me.

My main suggestion is that auth patterns supported by azcli should also work for the python-sdk.  Following that, there should be a way to use the profile/subscription_id without having to create service principals, which seems to currently be required for python-sdk.

Calling set_active_subscription seems to have the effect of `az account set --subscription <sub-id>`, but was discouraged by laurant so i'm looking for a way that is compatible with the python-sdk design.

**Comment by donaldguy** [comment]
It's a dirty abstraction violation but this seems to work these days:

```python
from azure.cli.core._profile import CredsCache

def get_azure_cli_credentials(resource=None, with_tenant=False, subscription_id=None):
    profile = get_cli_profile()

    # XXX: Abstraction break.
    # Don't use the global creds cache - or we can't manage to have both tenants in effect
    profile._creds_cache = CredsCache(profile.cli_ctx, profile.auth_ctx_factory, async_persist=profile._creds_cache._async_persist)

    cred, subscription_id, tenant_id = profile.get_login_credentials(resource=resource, subscription_id=subscription_id)
    return (cred, subscription_id, tenant_id)
```

It would be nice if there was a way to ask for this directly via `azure.common.credentials. get_azure_cli_credentials` or azure.common.credentials import get_cli_profile

**Comment by lmazuel** [comment]
@yugangw-msft what do you think?
