### ISSUE TITLE
Storage - Queues Readme and Sample Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#28984]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-queue#creating-a-queue), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-queue#sending-messages), [link3](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-queue#receiving-messages):

![image](https://user-images.githubusercontent.com/119990644/221104745-b01ba8f2-8fb7-4ffa-a901-97151be5d7c5.png)

**Reason:**
HttpResponseError: The specifed resource name contains invalid characters.

**Suggestion:**
Update to `myqueue` or `<my_queue>`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-queue/samples/queue_samples_message_async.py#L108), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-queue/samples/queue_samples_message_async.py#L152):

![image](https://user-images.githubusercontent.com/119990644/221104881-ce99ead2-0d89-4ab2-95a3-1b77c1428727.png)
![image](https://user-images.githubusercontent.com/119990644/221104901-dbda7b7e-e2a5-4d83-a622-dde0fde6f3c3.png)

**Reason:** 
Func called next didn't give a new queue name, which causes
ResourceExistsError: The specified queue is being deleted.

**Suggestion:** 
Update `myqueue3` in func `receive_one_message_from_queue` to`myqueue8`

@rohit-ganguly, @lmazuel, @kyle-patterson, @kasobol-msft, @annatisch for notification.

**Comment by vincenttran-msft** [comment]
Hi @ChenxiJiang333, thanks for catching this. I will add this and your other findings to a PR to resolve shortly.

Thanks!
