### ISSUE TITLE
DevCenter Readme and Sample Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#28987]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/devcenter/azure-developer-devcenter#dev-box-management), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/devcenter/azure-developer-devcenter#environment-management): 

![Screenshot_20230224_023826](https://user-images.githubusercontent.com/119990644/221109697-923501c6-df96-4d60-90c0-e91521051f0a.png)

**Reason:**
TypeError: DevCenterClient.__init__() missing 1 required positional argument: 'endpoint'

**Suggestion:**
Change code to 
```
endpoint = os.environ["DEVCENTER_ENDPOINT"]
client = DevCenterClient(credential=DefaultAzureCredential(), endpoint=endpoint)
```

2.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/devcenter/azure-developer-devcenter#environment-management):

![Screenshot_20230224_024905](https://user-images.githubusercontent.com/119990644/221111396-8cc98bb7-997d-4333-9c59-ab04e6c57c68.png)

**Reason:**
AttributeError: 'EnvironmentsOperations' object has no attribute 'list_artifacts_by_environment'

**Suggestion:**
Update to 
```
environment = client.environments.get_environment_by_user(target_project_name, "Dev_Environment")
LOG.info(environment)
```

3.
Section [link](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/devcenter/azure-developer-devcenter#environment-management):

![image](https://user-images.githubusercontent.com/119990644/221102759-110de8ab-dac8-4b7d-b5be-4690853f5567.png)

**Reason:**
Exception Details: UnexpectedNullArgument) Argument CatalogName cannot be null.

**Suggestion1:**
Add code 
`
target_catalog_name = list(client.environments.list_catalog_items(target_project_name, top=1))[0]['catalogName']
`

**Suggestion2:**
Update code 
`
"catalogItemName": target_catalog_item_name
`
 to 
`
"catalogName": target_catalog_name, "catalogItemName": target_catalog_item_name
`

@rohit-ganguly , @lmazuel for notification.

**Comment by SaurabhSharma-MSFT** [comment]
@ChenxiJiang333 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@ChenxiJiang333 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
