### ISSUE TITLE
Storage - Blobs Readme and Sample Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#28986]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#create-a-container), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#uploading-a-blob), [link3](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#downloading-a-blob), [link4](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#enumerating-blobs):

![Screenshot_20230224_024206](https://user-images.githubusercontent.com/119990644/221110357-42d350f4-1a87-42ce-9b7f-bc0745a4fa0e.png)

**Reason:**
HttpResponseError: The specifed resource name contains invalid characters.

**Suggestion1:** 
Update  to `<connection_string>`

**Suggestion2:**
Update  to `mycontainer` or `<my_container>`

2.
Section [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_authentication_async.py#L136):

![image](https://user-images.githubusercontent.com/119990644/221103508-786a1216-91e7-4935-8243-fe5d811257c4.png)

**Reason:** 
RuntimeWarning: coroutine 'BlobServiceClient.get_service_properties' was never awaited

**Suggestion:** 
Change code to 
`account_info = await blob_service_client.get_service_properties()
`

@rohit-ganguly, @lmazuel, @kyle-patterson, @kasobol-msft, @annatisch for notification.

**Comment by vincenttran-msft** [comment]
Hi @ChenxiJiang333, thanks for catching this. I will add this and your other findings to a PR to resolve shortly.

Thanks!
