### ISSUE TITLE
Storage - Files Shares Readme Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#28985]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-file-share#creating-a-file-share), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-file-share#uploading-a-file), [link3](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-file-share#downloading-a-file), [link4](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-file-share#listing-contents-of-a-directory):

![image](https://user-images.githubusercontent.com/119990644/221104306-1a4b55f1-8ca4-455a-817c-3212bcdc8fe0.png)

**Reason:**
HttpResponseError: The specifed resource name contains invalid characters.

**Suggestion:**
Update `my_share` to `myshare` or `<my_share>`

@rohit-ganguly, @lmazuel, @kyle-patterson, @kasobol-msft, @annatisch for notification.

**Comment by vincenttran-msft** [comment]
Hi @ChenxiJiang333, thanks for catching this. I will add this and your other findings to a PR to resolve shortly.

Thanks!
