### ISSUE TITLE
[ServiceBus] System.Byte[] error Pyamqp Sending Received Messages

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#28999]
Tests currently commented out, re-enable and fix bug:

`
with ServiceBusClient.from_connection_string(
    servicebus_namespace_connection_string, logging_enable=True) as sb_client:

    receiver = sb_client.get_queue_receiver(queue,
                                    max_wait_time=5,
                                    receive_mode=ServiceBusReceiveMode.PEEK_LOCK)
    sender = sb_client.get_queue_sender(queue)
    with receiver, sender:
        for i in range(1):
            message = ServiceBusMessage(
                body=b"Test message",
                application_properties={b'key': b'value'},
                subject=b'label',
                content_type=b'application/text',
                correlation_id=b'cid',
                message_id=b'mid',
                to=b'to',
                reply_to=b'reply_to',
                time_to_live=timedelta(seconds=60)
            )
            print("FIRST MSG")
            sender.send_messages(message)

`

Change this SBMessage to send application_properties as bytes and will get this error.

**Comment by swathipil** [comment]
fixed here: https://github.com/Azure/azure-sdk-for-python/commit/b627bde972931e21c4a578235ec0d8fa3576f1e7
