### ISSUE TITLE
Correlation ID in SAS-generating functions (Blob Storage)

### ISSUE THREAD

**Issue by matkozak** [Azure/azure-sdk-for-python#28995]
**Is your feature request related to a problem? Please describe.**
I am generating user delegated (container) SAS tokens for Blob Storage, authorized by a managed identity for an App Service. I would like to correlate SAS usage with application logs which should be possible according to the [documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#specify-a-correlation-id), but the `generate_(container)_sas` functions don't seem to be able to do this.

**Describe the solution you'd like**
A way to submit a uuid to the `generate_sas` functions and have it included as `scid` parameter.

**Comment by vincenttran-msft** [comment]
Hi @matkozak Mateusz, thanks for your inquiry. I believe this snippet of the codebase achieves the functionality you are looking for [here](https://github.com/Azure/azure-sdk-for-python/blob/66f339528488c07376b2a0d0df91eabc1e5a0aa0/sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py#L229).

Please pass a `correlation_id=` parameter to your `generate_container_sas` API call, or any of the applicable generate SAS APIs. With that being said, admittedly the documentation could use some improvement, and so I will work on getting a PR out to address this gap in the documentation.

Thanks!

**Comment by matkozak** [comment]
Thank you for your reply @vincenttran-msft , this does indeed create a delegated SAS with the supplied UUID.

However, I have just implemented this and the `CorrelationId` recorded in my StorageBlobLogs is different than the `scid` parameter supplied in the SAS token. This is perhaps outside the scope of this repo, but would you happen to know why?

**Comment by jalauzon-msft** [comment]
Hi @matkozak, I can't say that we're too familiar with how the audit logging works and how/where this correlation id would show up. I know there are a couple of different types of logs (legacy, Log Analytics, etc.) and different views of logs so perhaps it only shows up in certain places or in certain types of logs. My one obvious recommendation would be to ensure you are looking at logs for the specific operations that used that specific SAS and to be sure you are following the guidelines for providing the `scid`:

>The value is a GUID without braces and with lowercase characters.

Sorry I can't be more help than that. If you continue to have trouble, you could consider opening a support ticket to get some help from the service team.

**Comment by matkozak** [comment]
I understand. Thank you for your help, it's appreciated.
