### ISSUE TITLE
Async Eventhub Consumer with Pyamqp: Link Detached after long idle period Results in High "User Errors" volume

### ISSUE THREAD

**Issue by erewok** [Azure/azure-sdk-for-python#28996]
- package: **azure-eventhub**
- version: **5.11.1**
- OS: **Debian Container (kubernetes pod): `python:3.11-slim-bullseye`**
- Python version: **3.11.2**

**Describe the bug**
Long idle periods (greater than 1 hour) sometimes result in very high volume of "User Errors" reported in the metrics blade for our Eventhub. These high "User Error" volumes are correlated with our Consumer Clients *not* receiving events after idle period has ended and Producers have started publishing events again.

After setting log-level to `DEBUG` for our application, we have been able to correlate these "User Errors" with some errors in socket management in the `_pyamqp` module of the `azure-eventhub` package (see more details below).

Our consumer's log volume (when set at `DEBUG`) roughly correlates with User Errors volume (see screenshots) and seems to indicate a problem with socket connection being closed.

Lastly, our apps *sometimes* recover from this, but in other cases our Consumer Client pods must be **restarted** to begin consuming events again. (We had an outage this week as a result of this issue.)

**To Reproduce**
1. Build an async Eventhub Consumer similar to [this example](https://github.com/Azure/azure-sdk-for-python/blob/50927252aea1d649506a72822292da1c50940d5d/sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_store_async.py#L32) (Note: our app is very close to this example with some arbitrary processing in the event handler; the errors in question happen after long idle periods.)
2. Run the consumer with log-level set to DEBUG and no events going into Eventhub for longer than 1 hour (our event volume is closely tied to US Business Hours). 
3. Set Eventhub to "Disabled". (This seems to simulate the server socket disconnect.)
4. Re-enable Eventhub and see if Consumer Client can reconnect (ours go into failure loops).
5. Check Azure Eventhub until "User Errors" volume spikes (see screenshot) and correlate with logs.

**Expected behavior**
1. No "User Errors" managing closed sockets for idle consumers.
2. Idle consumers with closed connections are able to **reconnect**.
3. Also, less important but surprising behavior in `_pyamqp` module: errors in this library are called out in `log.info` calls (not `log.error`?), so not readily apparent with our typical logging setups ([Example](https://github.com/Azure/azure-sdk-for-python/blob/202d1335b8498cf73ce3d509d365052adcc3588f/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py#L170)).

**Screenshots**
A. User Errors Reported by Azure Eventhub metrics blade:
<img width="1404" alt="user-errors-metrics-sfevents-DEV" src="https://user-images.githubusercontent.com/4587833/221244108-8e6c5efa-d360-469f-acb8-f9d4f3daaeed.png">

B. Log Volume Correlated with high "User Errors":

<img width="1327" alt="user-errors-logs-correlations-sfevents-DEV" src="https://user-images.githubusercontent.com/4587833/221244151-8578affe-1e78-4e31-9cd1-65a3623cca29.png">

**Additional context**
Here are the log messages we see in order when this happens (full debug log dump available):

1. ["An error occurred when detaching the link](https://github.com/Azure/azure-sdk-for-python/blob/202d1335b8498cf73ce3d509d365052adcc3588f/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py#L257): `AMQPConnectionError('Error condition: ErrorCondition.SocketError\\n Error Description: Can not read frame due to exception: Server unexpectedly closed connection')"`
2. ["Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACHED: 0>"](https://github.com/Azure/azure-sdk-for-python/blob/202d1335b8498cf73ce3d509d365052adcc3588f/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py#L126)
3. ["An error occurred when detaching the link](https://github.com/Azure/azure-sdk-for-python/blob/202d1335b8498cf73ce3d509d365052adcc3588f/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py#L257): AMQPConnectionError('Error condition: ErrorCondition.SocketError\\n Error Description: Can not read frame due to exception: Server unexpectedly closed connection')"
7. "Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACHED: 0>"
8. "Management link receiver state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACHED: 0>"
9. "An error occurred when detaching the link: AMQPConnectionError('Error condition: ErrorCondition.SocketError\\n Error Description: Can not read frame due to exception: Server unexpectedly closed connection')"
10. "Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACHED: 0>"
11. "Management link sender state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACHED: 0>"
12. "An error occurred when ending the session: AMQPConnectionError('Error condition: ErrorCondition.SocketError\\n Error Description: Can not read frame due to exception: Server unexpectedly closed connection')"
13. "Session state changed: <SessionState.MAPPED: 3> -> <SessionState.UNMAPPED: 0>"
14. "An error occurred when closing the connection: AMQPConnectionError('Error condition: ErrorCondition.SocketError\\n Error Description: Can not read frame due to exception: Server unexpectedly closed connection')"
11. "Connection state changed: <ConnectionState.OPENED: 9> -> <ConnectionState.END: 13>"
15. "Connection state changed: None -> <ConnectionState.START: 0>"
16. GO THROUGH CONNECTION FLOW
17. "CBS completed opening with status: <ManagementOpenResult.OK: 1>"
18. "Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>"
19. ["Cannot get source or target. Detaching link"](https://github.com/Azure/azure-sdk-for-python/blob/202d1335b8498cf73ce3d509d365052adcc3588f/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py#L170)
20. "Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.DETACHED: 0>"
21. "Unable to attach new link: ValueError('Invalid link')"
22. "Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ERROR: 6>"
23. "Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.DETACH_SENT: 4>"
24. GOTO 1

**Notes**:
- The above flow seems to loop endlessly until we restart our consumer pods
- All of the above error messages are logged at level `INFO` (would prefer to have `WARN` or `ERROR` instead).
- At step 14 it looks like something has succeeeded, so it's unclear why the consumer goes into a loop afterward and can't recover.
- We set `idle_timeout` on a guess that it could help with long idle periods, but it has not.
- There are hundreds of "User Errors" per minute but it's not clear to us _what_ the Eventhub server itself is registering as a "User Error"?
- Our Consumers run in kubernetes pods and we also see this happen on Eventhubs with 1-24 partitions in different environments.

Also, worth mentioning that we have a Microsoft Support ticket: **TrackingID#2302210010000022**.

**Comment by kashifkhan** [comment]
Thank you for the detailed issue @erewok . We will take a look at it and get back to you asap.

**Comment by kashifkhan** [comment]
@erewok couple of follow up questions:

* Are yall using checkpointing as well ?
* Have the errors popped up before the hour mark or its strictly post that ?
* Have yall seen this happen on the sync client as well ?
* Can you paste in the debug log as well please ?

**Comment by erewok** [comment]
Hello @kashifkhan! Thanks for getting back to me.

> Are yall using checkpointing as well ?

Yes, our client is almost exactly the same as [the provided sample](https://github.com/Azure/azure-sdk-for-python/blob/50927252aea1d649506a72822292da1c50940d5d/sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_store_async.py#L32)

> Have the errors popped up before the hour mark or its strictly post that?

**Comment by erewok** [comment]
@kashifkhan, updated comment (accidentally hit enter before) with a CSV of logs at debug level. I think it's probably secure to share here(?) but I can remove after you have received it. Thanks again for your assitance.

**Comment by kashifkhan** [comment]
@erewok I have a copy of it so you can remove it, but for next time you email it to me :)

**Comment by kashifkhan** [comment]
no worries, Ill let you know as soon as I find something. Given the repro time is +1 hr my replies can be delayed. In the mean time let me know if something pops up on your end. 

Another question, yall arent seeing any errors with partition load balancing. Everything seems to be going fine and then all of a sudden the consumers just stop going in to that loop

**Comment by kashifkhan** [comment]
@erewok Another thing came up as we are trying to repro. For your debug logs can you also passing in `logging_enable=True` in to `EventHubConsumerClient.from_connection_string(` please ? This way we can see what AMQP frames are being sent across the wire as wel

**Comment by erewok** [comment]
Ah, you're right. I had that enabled on a different consumer. Unfortunately, this error-state is inconsistent and I haven't been able to reliably reproduce it. I turn up logging in our dev environment and then wake up the next day to see what data has appeared. I'll probably have to get back to you next week as a result (and keep my fingers crossed that it's reproducible 🤞for others).

**Comment by erewok** [comment]
> Another question, yall arent seeing any errors with partition load balancing. Everything seems to be going fine and then all of a sudden the consumers just stop going in to that loop

We _do_ see exactly the same issues as reported  in #28338, and we have tried similar strategies as described in there (changing to `LoadBalanceStrategy.BALANCED`, for example). However, in _this_ case, I believe the issue is an isolated issue because we are _not_ see those load-balancing issues in our dev environment where all of our Eventhubs have a single partition and we _did not_ see those issues in advance of what I reported above.

**Comment by kashifkhan** [comment]
Thanks for the response @erewok, I did ask that question wondering if check pointing was the issue. It does seem that when yall see partition load balancing errors, things arent completely stopping versus the other user is seeing that.

**Comment by erewok** [comment]
Yes, I think you're right. Even this issue only recently resulted in event-processing stopping.

**Comment by erewok** [comment]
One other update: after reviewing other logs, one of my other consumers with log level at `WARN` and `logging_enable=True` and also saw the telltale signs of this issue this morning. Unfortunately, we have only have two logs here

First:
```{"message": "END frame received on invalid channel. Closing connection.", "timestamp": "2023-02-24T19:37:24.764204+00:00", "application": "SF Event Hub Updater", "version": "pr7634-0.20.2-20230224.9"}```

After that, an endless repeat of (until service was restarted):

```{"message": "Unable to attach new link: ValueError('Invalid link')", "timestamp": "2023-02-24T19:37:25.417902+00:00", "application": "SF Event Hub Updater", "version": "pr7634-0.20.2-20230224.9"}```

I have redeployed this service with loglevel set higher and waiting to see if we can catch the invalid frame in action, but it seems like [this code](https://github.com/Azure/azure-sdk-for-python/blob/a6ede0d7c3d8acc078a9807d914b3c486b7d384e/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py#L551) may be close to the trigger. It occurs to me that if you have a way to terminate an Eventhub consumer connection on the server side, you may be able to reproduce without waiting for hours?

**Comment by erewok** [comment]
Speaking of, I may have a reproduction:

- When I set the Eventhub's "Status" to disabled (see attached) it triggers the same behavior ("User errors" chart spikes up and stays high until service restarted)
 
![Screenshot 2023-02-24 at 1 52 40 PM](https://user-images.githubusercontent.com/4587833/221300264-0e0753e9-f07f-4d3a-ab4d-808a99afc6a6.png)

This also gave me a way to reliably generate the erroring frames, I think. The log volume here spikes immediately after I disabled this Eventhub:

![Screenshot 2023-02-24 at 1 53 47 PM](https://user-images.githubusercontent.com/4587833/221300502-795d6ddd-edd3-4941-9a5a-ca2343a4ff8b.png)

@kashifkhan I have a new log dump to email: what address should I send it to?

**Comment by kashifkhan** [comment]
my github username at the company where I work :)

**Comment by kashifkhan** [comment]
@erewok received the email :)

**Comment by spbean75** [comment]
I am hitting this issue. I have a service up 24x7 reading from Event Hub and every few days something disables/reenables Event Hub causing program to just go into loop printing ValueLink errors. Is there a way to catch this and re-establish connection to EH? We are dead in water. Have tried everything.
"After that, an endless repeat of (until service was restarted):

{"message": "Unable to attach new link: ValueError('Invalid link')", "timestamp": "2023-02-24T19:37:25.417902+00:00", "application": "SF Event Hub Updater", "version": "pr7634-0.20.2-20230224.9"}

from azure.eventhub import EventHubConsumerClient

def run_prog():
    checkpoint_store = BlobCheckpointStore.from_connection_string(STORAGE_CONNECTION_STR, BLOB_CONTAINER_NAME)
    consumer_client = EventHubConsumerClient.from_connection_string(
        conn_str=CONNECTION_STR,
        consumer_group=CONSUMER_GROUP,
        eventhub_name=EVENTHUB_NAME,
        checkpoint_store=checkpoint_store,  # For load-balancing and checkpoint. Leave None for no load-balancing.
    )

    try:
        with consumer_client:
            """
            Without specified partition_id, the receive will try to receive events from all partitions and if provided
            with a checkpoint store, the client will load-balance partition assignment with other EventHubConsumerClient
            instances which also try to receive events from all partitions and use the same storage resource.
            """
            STARTING = time.time() - 60*60
            consumer_client.receive(
                on_event=on_event,
                starting_position=datetime.fromtimestamp(int(STARTING)),  # "-1" is from the beginning of the partition.
            )
            # With specified partition_id, load-balance will be disabled, for example:
            # client.receive(on_event=on_event, partition_id='0')
    except KeyboardInterrupt:
        print('Stopped receiving.')

**Comment by erewok** [comment]
I'd be curious if downgrading `azure-eventhub < 5.11` (and using `uamqp` instead of `pyamqp`) makes a difference.

**Comment by kashifkhan** [comment]
For the time being I would suggest that, trying an older version while we debug this. Its quite the tricky one

**Comment by kashifkhan** [comment]
@erewok are your disconnects for a certain period of time or are there any other errors that show up. 

reason being that I tried the enable/disable eventhub and can see the client looping, however when I reenable the hub it does resume receiving. Disconnect/Re-connects are also doing the same thing but it takes a longer time to reconnect. I'm trying to see if there is some other detail that is key to repro.

the debug log was helpful but do you happen to have snippets of the log before the fail happened, so we can see where it was before it goes in to that loop ?

**Comment by erewok** [comment]
Ah,  I was afraid of that: that you wouldn't be able to reproduce it so easily. I will run some queries and try to get another log with a larger window. At a glance, before the reconnect failures occur, the debug log looks like "azure-blob-storage checkpointing worked". 

If I can get the time, I think I will also try to build a simple repro that can be shared. I may need to wait a few days to see if the event happens organically: I have am slightly suspicious that my explicit disable-and-reenable triggers a similar-looking failure which may be different.

**Comment by kashifkhan** [comment]
@erewok I thought I had a repro, but the issue became if I left it running long enough it would go back to the reconnect loop. The re-enable/disable trick triggers a "failure" but its largely the service reporting back an error from the service, a special eventhub disabled error versus a network loss TimeOutError.

The re-enable / disable eventhub does resume rather quickly however, so was wondering if something else is going on.

**Comment by kashifkhan** [comment]
@erewok can you share the location where the event hubs are so we can also create them in the same region. Also are you seeing this error when you are using more than 1 partition or does it happen on any partition size?

**Comment by erewok** [comment]
We see this for Eventhubs with 1, 3, and 24 partitions. We see it in West US and West US 2. I still need to get you another set of logs. Apologies: will get it to you soon. Thanks again for looking into this.

**Comment by kashifkhan** [comment]
No worries about erewok, still working on it ourselves.

**Comment by erewok** [comment]
We had another event in a dev environment this morning and the event seems to have begun with this:

```
"<- DetachFrame(handle=0, closed=True, error=[b'amqp:connection:forced', b\"The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:2a8827fbd5ee48d9be0f2787f123da1b_G23, SystemTracker:gateway5, Timestamp:2023-02-28T15:27:18\", None])"
```

I sent more details via email.

**Comment by kashifkhan** [comment]
@erewok  thank you for the details and logs, looking through

**Comment by erewok** [comment]
Yesterday, I added `idle_timeout=60 * 4,` to our `EventHubConsumerClient.from_connection_string(...` call, and it may have helped. I picked 4 minutes because it was lower than the `allowed 300000 milliseconds` reported by the error. I will keep an eye on it and see.

**Comment by erewok** [comment]
Follow-up: it did not help. I've got one environment where it reliably occurs (even with `idle_timeout` set) and one where it seems to happen less often, both running the same container. The error looks the same in any event:

1. DetachFrame with `The connection was inactive for more than the allowed 300000 milliseconds and is closed by container`, followed by
2. Failure to attach until and looping until pod is restarted

**Comment by kashifkhan** [comment]
Hi @erewok , yeah the idle_time would just be pushing out the problem because over time when the timeout does happen, the empty frame going out causes stuff to go wonky . We are able to repro on our side reliably and are seeing whats happening in the code.

**Comment by erewok** [comment]
I decided to switch back to `uamqp` in order to leave this issue aside for now. I add `uamqp` back to my dependencies and I'm going to run with this for a while:

```python
    client = EventHubConsumerClient.from_connection_string(
        eventhub_conn_str,
        consumer_group=eventhub_consumer_group,
        eventhub_name=eventhub_name,
        uamqp_transport=True,
    )
```
