### ISSUE TITLE
check_existence_by_id raises 'Bad Request'

### ISSUE THREAD

**Issue by taverna0111** [Azure/azure-sdk-for-python#29016]
- **Package Name**: azure-mgmt-resource
- **Package Version**: 21.2.1
- **Operating System**: Windows 11
- **Python Version**: 3.10.6

**Describe the bug**
When I use the `check_existence_by_id` method of `ResourceManagementClient.resources` The following error is raised:
```
Traceback (most recent call last):
  File "<pyshell#63>", line 1, in <module>
    client.resources.check_existence_by_id("HIDDEN", "2021_04_01")
  File "C:\Users\tal\AppData\Roaming\Python\Python310\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\tal\AppData\Roaming\Python\Python310\site-packages\azure\mgmt\resource\resources\v2021_04_01\operations\_operations.py", line 10504, in check_existence_by_id
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
```

The subscription and resource ID used are valid, both objects exists in my Azure tenant.

**To Reproduce**
This is my code:
```
from azure.identity import InteractiveBrowserCredential
from azure.mgmt.resource import ResourceManagementClient

creds = InteractiveBrowserCredential()

S_ID = "HIDDEN_SUBSCRIPTION_ID"
client = ResourceManagementClient(creds, S_ID)

client.resources.check_existence_by_id("HIDDEN_RESOURCE_ID", "2021_04_01")
```

**Expected behavior**
The method should return `True` instead of raising an error

**Comment by kashifkhan** [comment]
Thank you for the feedback @taverna0111 . We will investigate and get back to you asap.

**Comment by PramodValavala-MSFT** [comment]
@taverna0111 Could you [enable HTTP logging](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-logging#enable-http-logging-for-a-client-object-or-operation) and share the logs for the same here?

**Comment by msyyc** [comment]
Hi @taverna0111 please replace `_` with `-` for `api_version`:
```python
...
client.resources.check_existence_by_id("HIDDEN_RESOURCE_ID", "2021-0401")
```

**Comment by taverna0111** [comment]
@msyyc Unfortunately it didn't worked, the same exception is raised.

@PramodValavala-MSFT As far as I can tell the `azure-mgmt-resource` library doesn't log anything (I looked at the source). I followed the guide you provided and used this:
```
from azure.identity import InteractiveBrowserCredential
from azure.mgmt.resource import ResourceManagementClient
import sys
import logging

logger = logging.getLogger('azure.mgmt.resource')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)

creds = InteractiveBrowserCredential(logging_enable=True)
client = ResourceManagementClient(creds, "HIDDEN_SID"), logging_enable=True)
client.resources.check_existence_by_id("HIDDEN_RESOURCE", "2021-04-01", logging_enable=True)
```
The output didn't contain any log, only the same exception as before.
Am I doing this wrong? Is there another way to get logging information?

Thank you both for your replies

**Comment by Wzb123456789** [comment]
Hi @taverna0111 

Please try the following code:

```python
from azure.identity import InteractiveBrowserCredential
from azure.mgmt.resource import ResourceManagementClient
import sys
import logging

logger = logging.getLogger('azure.mgmt.resource')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)

creds = InteractiveBrowserCredential(logging_enable=True)
client = ResourceManagementClient(creds, "HIDDEN_SID", logging_enable=True)
client.resources.check_existence_by_id("HIDDEN_RESOURCE", "2021-04-01", logging_enable=True)
```
I can run successfully.
![image](https://user-images.githubusercontent.com/51410816/222096256-0036561f-f936-499b-848e-2f93615c8ba4.png)

**Comment by taverna0111** [comment]
@Wzb123456789 
This is quite similar to what I did before.
I copy-pasted your code and still no change, same `Bad Request` exception

**Comment by msyyc** [comment]
Hi @taverna0111 According to description: https://github.com/Azure/azure-sdk-for-python/blob/4e6b795e5f90d1474f80c9c0716b02622a7348bd/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2021_04_01/operations/_operations.py#L10597-L10601

maybe microsoft.web doesn't support the rest call and you can try `azure-mgmt-web` to check whether the resource exists

**Comment by taverna0111** [comment]
@msyyc Thanks for your reply.

`ResourceManagementClient` not being the correct way to check the existence of a resource (especially given methods such as `check_existence` and `check_existence_by_id`) makes me want to consider other cloud solutions as well as my own sanity

**Comment by msyyc** [comment]
I write a [sample (https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/resources/manage_resource_check_exsistence.py) which works:
![image](https://user-images.githubusercontent.com/70930885/222309504-0b7c4ebb-12db-4f1d-b5a7-8f87ff7b4cce.png)
It proves that not the api but your parameter has the problem. Please:
(1) try DefaultAzureCredential
(2) check whether your resource_group_name or resource_name contains odd symbols like `/`
