### ISSUE TITLE
ContainerGroupNetworkProfile is missing from azure-mgmt-containerinstance

### ISSUE THREAD

**Issue by kurtqq** [Azure/azure-sdk-for-python#29015]
- **Package Name**: azure-mgmt-containerinstance
- **Package Version**: 1.5.0
- **Operating System**:
- **Python Version**: 

**Describe the bug**
The class `ContainerGroupNetworkProfile`
https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-containerinstance_1.5.0/sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/models/container_group_network_profile_py3.py

was moved/removed/something in newer versions but change log
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/containerinstance/azure-mgmt-containerinstance/CHANGELOG.md
doesn't say anything about it. please add clear instructions how to migrate from 1.5.0 with this class being used
better to edit the release notes and explain that

**Comment by kashifkhan** [comment]
Thank you for the feedback @kurtqq . We will investigate and get back to you asap.

**Comment by PramodValavala-MSFT** [comment]
@kurtqq [Network Profiles have been retired](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-virtual-network-concepts#network-profile). You may skip any steps related to them and just deploy containers by passing in details of the network configuration required as usual.

**Comment by msyyc** [comment]
Hi @kurtqq `azure-mgmt-containerinstance<7.0.0b1` is track1 version which has been retired. Please try latest track2 version(>= 7.0.0b1) and here is the guidance: https://devblogs.microsoft.com/azure-sdk/migrating-python-management-libraries/

**Comment by kurtqq** [comment]
Thank you, I still not quite sure why `azure-mgmt-containerinstance` release notes of version 7.0.0 don't specify this information.
Also the doc you shared doesn't show example of code prior to 7.0.0 with `ContainerGroupNetworkProfile `and how this code will look like after 7.0.0

I think this is not a very friendly experience to users. When package is breaking AIP the release note should be very details with explanations how to migrate (specifically for the code being broken) general service docs are usually more high level.
