### ISSUE TITLE
azure.cognitiveservices.speech - can't import with py2exe

### ISSUE THREAD

**Issue by pradsy90** [Azure/azure-sdk-for-python#29013]
- **Package Name**: azure.cognitiveservices.speech
- **Package Version**: 1.25.0
- **Operating System**: Windows 11
- **Python Version**: 3.10

**Describe the bug**
Azure package does not get pulled by py2exe for building into an executable. I have tried multiple versions of includes, excludes, packages.  Just keeping hitting the cannot find module azure error, all the time.  I have tried multiple different hacks and this problem does not seem to go away... The Executable being built by py2exe just cannot run if I use the azure sdk it looks like.

**To Reproduce**
1. import azure sdk and try a simple python program
2. generate an exe for this program using py2exe (basic set up, advanced setup don't care)
3. run the exe file

**Expected behavior**
The exe should run

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @pradsy90 . We will investigate and get back to you asap.

**Comment by kristapratico** [comment]
@pradsy90 you might try moving your issue to this repo: https://github.com/Azure-Samples/cognitive-services-speech-sdk. I would move it for you, but it doesn't look like I can. That repo houses the samples for the SDK, but the maintainers of the speech SDK are active there and will be able to help.
