### ISSUE TITLE
product names out of date

### ISSUE THREAD

**Issue by dcurwin** [Azure/azure-sdk-for-python#29022]
The section mentioning product names has out of date product names.

It states:  The name of the product which published this alert (Azure Security Center, Azure ATP, Microsoft Defender ATP, O365 ATP, MCAS, and so on).

These are the correct names:

Azure Security Center -> Microsoft Sentinel
Azure ATP -> Microsoft Defender for Identity
Microsoft Defender ATP -> Microsoft Defender for Endpoint
O365 ATP -> Microsoft Defender for Office
MCAS -> Microsoft Defender for Cloud Apps

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49150165-e6d3-3c19-c22a-6d26538b907d
* Version Independent ID: ba761653-5db3-d0f2-f731-e0732b8355d4
* Content: [azure.mgmt.security.v2021_01_01.models.Alert class](https://learn.microsoft.com/en-us/python/api/azure-mgmt-security/azure.mgmt.security.v2021_01_01.models.alert?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-security/azure.mgmt.security.v2021_01_01.models.Alert.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-security/azure.mgmt.security.v2021_01_01.models.Alert.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by msyyc** [comment]
Hi @dcurwin, `azure-mgmt-security` is generated with swagger. If you want to change the description, please make an PR to update [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/security/resource-manager/Microsoft.Security/stable/2022-01-01/alerts.json#L974). After your PR merged, we can release a new version for SDK then the doc will be updated automatically.

**Comment by dcurwin** [comment]
@msyyc  - It is unclear how I should make that PR. Perhaps, since you're more familiar with the process, you could submit it? If not, please provide clear and specific instructions.

**Comment by msyyc** [comment]
You can make PR like: https://github.com/Azure/azure-rest-api-specs/pull/22841/files

**Comment by dcurwin** [comment]
@msyyc  - That is definitely not the "clear and specific instructions" I mentioned above. Once again, I request that you either submit the PR, or explain **how** I should make the relevant PR.

cc: @ArthurMa1978

**Comment by msyyc** [comment]
Thanks for your kind remind and please help review https://github.com/Azure/azure-rest-api-specs/pull/22841

**Comment by dcurwin** [comment]
> Thanks for your kind remind and please help review [Azure/azure-rest-api-specs#22841](https://github.com/Azure/azure-rest-api-specs/pull/22841)

I reviewed and approved that PR, thanks.
