### ISSUE TITLE
DataTransferStep fails with Azure Datalake Gen2

### ISSUE THREAD

**Issue by LaurieCantaloube** [Azure/azure-sdk-for-python#29027]
- **Package Name**: azureml-sdk
- **Package Version**: 1.49.0 (same issue with 1.44.0)
- **Python Version**: 3.8.0

I try to use a DataTransferStep to copy data from one location to another in my Azure Data Lake Storage Gen2 datastore but I've this error:

![DataTransferStep error](https://user-images.githubusercontent.com/56597362/221577954-64250ec0-c25e-44eb-84f0-284be816b295.png)

I tried with DataReference and PipelineData as inputs, to auth with service principal authentication or not, but always the same error...
However, it works perfectly if the datastore is an Azure Blob Storage. 
Other info, DataBricksSteps work with the Azure Data Lake Storage Gen2 datastore. 

Any idea of what causes the issue?

**Comment by kashifkhan** [comment]
Thank you for the feedback @LaurieCantaloube . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by D-W-** [comment]
Hi @LaurieCantaloube, could you provide step run id, pipeline run id (if it's a pipeline run), workspace name, resource group name and subscription id for the failed step so we can investigate? You can find the step run id and pipeline run id in AzureML studio portal: 
![image](https://user-images.githubusercontent.com/7776147/228745477-d88ffe95-452f-4c73-9cc1-0727621543fc.png)
![image](https://user-images.githubusercontent.com/7776147/228745541-fc2f2db2-d098-489c-b9c8-c7b81ce6817b.png)
