### ISSUE TITLE
Flat listing does not work for ContainerClient

### ISSUE THREAD

**Issue by manoss96** [Azure/azure-sdk-for-python#29026]
- **Package Name**: azure-storage-blob
- **Package Version**: >= 12.14.0
- **Operating System**: Windows 10
- **Python Version**: 3.10.10

**Describe the bug**

The methods `azure.storage.blob.ContainerClient.{list_blobs, list_blob_names}` include virtual folders along with ordinary blob objects within their results. According to [List blobs with Python](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-list-python#use-a-flat-listing), this shouldn't be the case.

**To Reproduce**
1. Initialize an `azure.storage.blob.ContainerClient` instance connecting to a container in which resides a virtual folder containing both blob objects and virtual folders.
2. Invoke `list_blob_names`, where the argument `name_starts_with` is defined in such way so that it points to the virtual folder mentioned in Step 1.
3. Observe the results.

**Expected behavior**
The names of any virtual folders should not be included within the methods' output.

**UPDATE**: I've realized that this is due to Hierarchical Namespace feature being enabled. However, is there a way of differentiating between ordinary blobs and virtual folder blobs when this feature is on? All I can think of is to consider all blobs whose size is zero as virtual folders, but there might as well be ordinary blobs of that size...

**Comment by kashifkhan** [comment]
Thanks for the feedback @manoss96 . We will investigate and get back to you asap.

**Comment by vincenttran-msft** [comment]
Hi @manoss96, thanks for your inquiry. I see that in your edit you noted that hierarchical namespace is enabled on your Storage account. With that being said, I would recommend you use the [azure-storage-file-datalake](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-file-datalake) as that is the correct package intended to be used with hierarchical namespace accounts.

In this case, after switching to the `azure-storage-file-datalake` package, you will want to use the [get_paths ](https://github.com/Azure/azure-sdk-for-python/blob/e949aa0d2ef00604e80eef2499733ae7937e6a0e/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py#L528)API which is the equivalent function to the `list_blobs` API. You can differentiate between blobs and directories by looking at the response body from the `get_paths` API. Directories will have a `isDirectory` property with the value `True`, while blobs will not have this property.

With that being said, hopefully this can help you achieve what you are intending. 

Thanks!

**Comment by manoss96** [comment]
@vincenttran-msft I see. Is `azure-storage-file-datalake` only to be used with accounts where HNS is enabled, or does it essentially replace `azure-storage-blob` no matter the account?

**Comment by jalauzon-msft** [comment]
Hi @manoss96, `azure-storage-file-datalake` is intended to be used only for accounts with HNS enabled where `azure-storage-blob` is intended for accounts without HNS. Some operations from each SDK may work on the other account type but that's generally not recommended and not fully supported from our side. As you've seen, it can have unexpected results. Thanks.

**Comment by manoss96** [comment]
Is there a way of programmatically determining whether the account to which I am trying to connect has HNS enabled or not, so that I can use the correct API without having that knowledge beforehand?

**Comment by vincenttran-msft** [comment]
Hi @manoss96, [get_account_information](https://github.com/Azure/azure-sdk-for-python/blob/839362b1060267d348b8169a5cf26556c7b4c98f/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py#L219) is the API you are looking for to achieve this. The response from this API call will contain a bool property, `is_hns_enabled`

With that being said, I hope this will help you with your intended workflow! I believe this adequately answers the original issue posed in the original post, and so I will close the issue. Please let us know if this is not the case.

Thanks!
