### ISSUE TITLE
Batch upload/download

### ISSUE THREAD

**Issue by jmilicevic** [Azure/azure-sdk-for-python#29025]
Hello,

I am using ContainerClient and I was wondering if there is any chance to get batch download/upload support soon? I have tried using threads to increase the speed but it's still too slow.

Thanks!

**Comment by kashifkhan** [comment]
Thanks for the feedback @jmilicevic . We will investigate and get back to you asap.

**Comment by PramodValavala-MSFT** [comment]
@jmilicevic Duplicate of #28997

As mentioned in the above issue, this would be a feature request requiring service side changes before the SDKs support the same. Closing this in favor of that.
