### ISSUE TITLE
Azure EventHub - EventData.body_as_json returns a dict

### ISSUE THREAD

**Issue by ivandigiusto** [Azure/azure-sdk-for-python#29044]
EventData.body_as_json in Azure EventHub code currently returns a dictionary. This is not expected based on the name, as what is expected (in Python) is a string representing a json object.

Since there is already body_as_str method, I would suggest that this method gets renamed as body_as_dict.

In the interim, it could be kept for backwards compatibility, but it is not intuitive for new users of this module.

In Python, JSON != dict, at least not as a type. That is why we use json.loads to move JSON into a dict.

**Comment by kashifkhan** [comment]
Thanks for the feedback @ivandigiusto . We will investigate and get back to you asap.

**Comment by kashifkhan** [comment]
Hi @ivandigiusto, thank you for the issue and sorry for taking so long to get back to you on this. You are right that there is some confusion, and we can improve things by enhancing the description of the method & adding a code snippet showing how to get the actual string, while leaving the method intact given that it has been in GA for a number of years now. 

Defining json object as a type in python has quite the interesting read [here](https://github.com/python/typing/issues/182) so a `dict[str, any]` can be a json type just as a `str`. 

Thank you 🙂
