### ISSUE TITLE
[BUG] Spark Pipeline Components stuck in permanent preparing state

### ISSUE THREAD

**Issue by Ioannis-Mykelos** [Azure/azure-sdk-for-python#29056]
- **azure-ai-ml**: 
- **1.0.0 / 1.1.0 / 1.2.0**: 
- **Linux**:
- **3.10**: 

**Describe the bug**
Spark Job Component as part of a pipeline get stuck in a permanent "preparing" state.

**To Reproduce**
Followed the official tutorial here: [TUTORIAL](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=sdk) https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=sdk#spark-component-in-a-pipeline-job as it does not work.

**Expected behavior**
Pipeline jobs can have spark jobs or spark steps with the Spark automatic compute cluster, just as standalone spark jobs.

**Screenshots**

**Additional context**
<img width="574" alt="Screenshot 2023-02-28 at 11 59 39" src="https://user-images.githubusercontent.com/54843968/221837979-bc018cc4-e999-4698-b69e-4a65307d20e7.png">

<img width="574" alt="Screenshot 2023-02-28 at 11 58 44" src="https://user-images.githubusercontent.com/54843968/221837964-fa0460a6-cfdf-4539-a2fe-0b51074b450b.png">

<img width="614" alt="Screenshot 2023-02-28 at 12 15 41" src="https://user-images.githubusercontent.com/54843968/221839210-9d22697d-cfde-41cf-8708-19201d9140ec.png">

When the pipeline fails I am getting the following error:

Job failed, Error: {"Error":{"Code":"ServiceError","Severity":null,"Message":"InternalServerError","MessageFormat":null,"MessageParameters":null,"ReferenceCode":null,"DetailsUri":null,"Target":null,"Details":[],"InnerError":null,"DebugInfo":null,"AdditionalInfo":null}, ...,"ComponentName":"Execution"}

I created a simple standalone spark job (read delta tables  from the data lake) and it works absolutely fine.
Then, I was trying to implement a two step pipeline in SDKV2, with a Spark component as the first step.
The pipeline is stuck in the Spark component for about 3 to 4 hours until failure.

For the 2 step pipeline I am trying to do something simple, just read delta files, preprocess and train a simple model.

For this 2 step pipeline I am defining:

1. a spark job as a pipeline component (1st step), and
2. a training component (using a .yml file).

**Comment by kashifkhan** [comment]
Thanks for the feedback @Ioannis-Mykelos . We will investigate and get back to you asap.

cc @azureml-github.

**Comment by Ioannis-Mykelos** [comment]
> Thanks for the feedback @Ioannis-Mykelos . We will investigate and get back to you asap.
> 
> cc @azureml-github.

Any updates?

**Comment by vaibhj** [comment]
Can we please get Run Id, Subscription Id and workspace name for issue?

**Comment by Ioannis-Mykelos** [comment]
Dear @vaibhj, I tried to run again the "2-step-pipeline" with the first component to be a spark job.
It failed again after 3,5 hours.
<img width="700" alt="Screenshot 2023-03-30 at 14 11 07" src="https://user-images.githubusercontent.com/54843968/228832716-d260ec66-a3aa-49cf-814e-6804f5d717cc.png">
<img width="460" alt="Screenshot 2023-03-30 at 14 10 20" src="https://user-images.githubusercontent.com/54843968/228832771-7d64862c-2c6f-4b8d-ad55-4634806c5e89.png">

- Experiment: SparkComponent, 
- Run Id: 90d4014a-7a9d-4eb2-981c-d85518367254, 
- ComponentId: 5cad6238-2ac0-40db-ba06-ca2fac4f364b

**Comment by vaibhj** [comment]
Thanks @Ioannis-Mykelos for retry and providing jobId. Can you please confirm compute details. If you are using SDK you must be adding spark_step.compute = <compute name >. 

Please provide compute name and type. 

We saw this behavior when user try to run spark job on AmlCompte instead Attached Spark Compute. You can try hobo spark job by providing spark_step.resources  instead spark_step.compute 
spark_step.resources = {
        "instance_type": "Standard_E8S_V3",
        "runtime_version": "3.2.0",
    }

Please correct me if my assumption are wrong. 
Thanks

**Comment by vaibhj** [comment]
If you want to use Synapse Spark pool attached compute .. you must attach a compute first and later you can use it in spark step. You can ignore attaching synapse pool by using our hobo offering as I mentioned in above message.

**Comment by Ioannis-Mykelos** [comment]
@vaibhj Hello, thanks for your quick response.
I have contributor role in the datalake, since I acquired it to make a standalone spark job to work.
And it works just fine, perfectly I could say (Loading delta tables from datalake, process the data and saving them in the datalake). 
The spark_step.recourses I am using are the following (it works perfectly in the standalone spark job).

``` python
step_1_spark.resources = {
        "instance_type": "Standard_E64S_V3",
        "runtime_version": "3.2.0",
    }
```

But the 2 step pipeline with the first component as a spark job it tricky.

I am doing as you say: 

``` python
# Retrieve an already attached Azure Machine Learning Compute.
cluster_name = "gpu"
cluster = ml_client.compute.get(cluster_name)
``` 
and
``` python
# Define the spark job/component as the step 1:
# Without using the component YML file for step 1
spark_component = spark(
    name="SparkComponentStep1",
    inputs={
        "input_data": Input(type="uri_folder", mode="direct"),
    },
    outputs={
        "output_data": Output(type="uri_folder", mode="direct"),
    },
    # The source folder of the component
    code="./src",
    entry={"file": "spark_step_1.py"},
    driver_cores=2,
    driver_memory="4g",
    executor_cores=4,
    executor_memory="4g",
    executor_instances=4,
    args="--input_data ${{inputs.input_data}} --output_data ${{outputs.output_data}}",
)

# Load component no2 from YML
components_dir =  "src/components/"
train_model_component = load_component(source=os.path.join(components_dir, "spark_step_2.yml"))
```

And then I define my pipeline:

``` python
# Create the Pipeline
@dsl.pipeline(compute = cluster, description="Two step Pipeline with Spark 1st component --> spark") 
def spark_pipeline(spark_input_data):

    # STEP 1
    step_1_spark = spark_component(input_data=spark_input_data)
    step_1_spark.inputs.input_data.mode = InputOutputModes.DIRECT
    step_1_spark.outputs.output_data = Output(
        type="uri_folder",
        path="output_path_to_datalake"
    )
    step_1_spark.outputs.output_data.mode = InputOutputModes.DIRECT
    step_1_spark.identity = ManagedIdentityConfiguration()
    step_1_spark.resources = {
        "instance_type": "Standard_E64S_V3",
        "runtime_version": "3.2.0",
    }
    processed_data = step_1_spark.outputs.output_data 
    
    # STEP 2
    step_2_spark = train_model_component(input_data=processed_data)
    
    return {"train_job_output": step_2_spark.outputs.output_data} 
``` 

An call my pipeline
```  python
# Call the Pipeline function
input_path_ = "azureml://datastores/curated/paths/" + "input_path_to_datalake"
pipeline = spark_pipeline(
    spark_input_data=Input(
        type="uri_folder",
        path=input_path_
    )
``` 

Submit the pipeline
``` python
# submit the pipeline job
pipeline_job = ml_client.jobs.create_or_update(
    job=pipeline,
    experiment_name="SparkComponent",
    )
``` 
And the next step load forever
``` python
# Wait until the job completes
ml_client.jobs.stream(pipeline_job.name)
``` 

It feels that I am doing what the [official documentation](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=cli) says. Or maybe I am missing something. Can you please give me a hint or try to provide a solution?


Also when I tried to create a .yaml component for the spark component but it throws an error since the link appears not to exist 
``` 
$schema: http://azureml/sdk-2-0/SparkComponent.json
```

**Comment by shreeyaharma** [comment]
@Ioannis-Mykelos I made below change in your job and it worked for me:

 # STEP 2
    step_2_spark = train_model_component(input_data=processed_data)
    **step_2_spark.compute = cluster**
    

@dsl.pipeline(description="Two step Pipeline with Spark 1st component --> spark")  #**removed compute from the parameter**
    
 Let me know if it works.

**Comment by Ioannis-Mykelos** [comment]
@vaibhj Many thanks for the time and effort.
I applied the changes you recommended, and I can see that now it fails much much faster but with the following error, that is confusing for me:

`
Job Failed due to: Response status code does not indicate success: 404 (User assigned identity  is not attached to AML workspace ws-dev.).User assigned identity  is not attached to AML workspace ws-dev.
`

Run Id = `826dcab5-d493-4537-95e8-d3b52d28550d`

It looks weird since my ml_client holds the azure.identity...., for the related workspace.

``` python
# Configure credential
try:
    credential = DefaultAzureCredential()
    # Check if given credential can get token successfully.
    credential.get_token("https://management.azure.com/.default")
except Exception as ex:
    # Fall back to InteractiveBrowserCredential in case DefaultAzureCredential not work
    credential = InteractiveBrowserCredential()

# Get a handle to the workspace
ml_client = MLClient.from_config(credential=credential)
```

Any help would be highly appreciated.
Thanks in advance.

**Comment by shreeyaharma** [comment]
@Ioannis-Mykelos you are specifying Managed Identity if you do so you need to assign user assigned identity to workspace else you can use UserIdentity while submitting job

**Comment by Ioannis-Mykelos** [comment]
Dear @shreeyaharma,

Can you elaborate? Can you provide an example .ipynb or some documentation?

**Comment by Ioannis-Mykelos** [comment]
Dear @shreeyaharma,

The pipeline runs but I am getting a weird error (and the pipeline behaviour is slightly changed)

My python file (spark_step_1.py)  for the first step is the following:

```python

def batch_preprocessing(spark_dataframe: SparkDataFrame) -> pd.DataFrame:
    """
    Here we can do something .... 
    """

    # Groupby, agg
    spark_df = spark_dataframe.groupBy("ID").agg({"Quantity": "sum"})
   
    # Trasform the pyspark.sql.DataFrame to pandas DataFrame
    pandas_df = spark_df.toPandas()

    return pandas_df

if __name__ == "__main__":
    # Get the parameters
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_data", type=str, help="input datapath argument")
    parser.add_argument("--output_data", type=str, help="input datapath argument")
    args = parser.parse_args()

    # Initiate spark session
    spark = SparkSession.builder.appName("spark_load_delta_tables").getOrCreate()

    # Experiment run context
    run = Run.get_context()

    print("Loading Data...")
    # Load delta tables
    pyspark_df = spark.read.format("delta").load(args.input_data)
    pandas_df = batch_preprocessing(spark_dataframe=pyspark_df)

    print("Saving Data...")
    path = args.output_data
    os.makedirs(path, exist_ok=True)
    pandas_df.to_csv(os.path.join(path, "input_step_2.csv"))

    run.complete()
```

My step 2 python file is the following:

```python
def training_pipeline(data: pd.DataFrame):
    """
    Do something with the csv file
    """
    new_data = data.head(n=10)

    return new_data


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--input_data", type=str, help="input datapath argument")
    parser.add_argument("--output_data", type=str, help="output datapath argument")
    args = parser.parse_args()

    # Experiment run context
    run = Run.get_context()

    # Load the preprocessed
    print("Loading Data...")
    input_path = os.path.join(args.input_data, "input_step_2.csv")
    print(input_path)
    tutorial_data = pd.read_csv(input_path)

    print("Training model...")
    new_data = training_pipeline(tutorial_data)

    print("Saving Data...")
    path = args.output_data
    os.makedirs(path, exist_ok=True)
    new_data.to_csv(os.path.join(path, "output_step2.csv"))

    run.complete()

```

For some reason the pipeline instead of creating the single csv file "input_step_2.csv", it creates a folder "input_step_2.csv"
and of course the second step python file thows an error 
"IsADirectoryError: [Errno 21] Is a directory: '/mnt/azureml/cr/j/d8136e26f6934466be3b0c4e0e1e3a89/cap/data-capability/wd/INPUT_input_data/input_step_2.csv'"

Info:
RunId:[5f6d9edd-4f3d-4e98-a711-4c73d2455cf8] 
ParentRunId:[yellow_truck_9d807mg0b1] 
ComputeTarget:[AmlCompute]


And if I try to run the pipeline again I get the following error in the first step:
```path abfss://path_to_the_csv_file/input_step_2.csv already exists.```
I guess cannot overwrite the directory since it existed from the first run of the pipeline.

So I guess the main concern is that instead of a csv file it creates a directory named "input_step_2.csv"
<img width="1188" alt="Screenshot 2023-04-13 at 12 59 56" src="https://user-images.githubusercontent.com/54843968/231739080-fdba4afc-f9a2-47fa-b2af-fdc60e322310.png">

And the "input_step_2.csv" directory contains:

<img width="1160" alt="Screenshot 2023-04-13 at 13 00 18" src="https://user-images.githubusercontent.com/54843968/231739095-2b6f9e5e-a3b1-4299-a5a1-5b541e62710f.png">

Any hint would be greatly appreciated.
Thanks for your time and effort.

**Comment by Ioannis-Mykelos** [comment]
Dear @shreeyaharma, 

Any updates on my questions?

Thanks in advance.

**Comment by shreeyaharma** [comment]
@Ioannis-Mykelos we dont own this feature, Going through to_csv function might help. When I will get time, I will try to find answers to this problem.

**Comment by Ioannis-Mykelos** [comment]
Dear @shreeyaharma, many thanks for your help and tips.
I managed to make it work.
Thank you for the support!
