### ISSUE TITLE
AttributeError: 'CostManagementClient' object has no attribute 'generate_cost_details_report'

### ISSUE THREAD

**Issue by Madhava24** [Azure/azure-sdk-for-python#29082]
- **Package Name**: azure-mgmt-costmanagement 
- **Package Version**: 3.0.0 
- **Operating System**: Windows 11(64-bit)
- **Python Version**:  3.9.13

**Describe the bug**
1. I'm trying to get cost details report from azure cost management API using python. I am following the steps mentioned in the Microsoft Learn page - [GenerateCostDetailsReportByBillingAccountEnterpriseAgreementCustomerAndBillingPeriod](https://learn.microsoft.com/en-us/rest/api/cost-management/generate-cost-details-report/create-operation?tabs=Python#generatecostdetailsreportbybillingaccountenterpriseagreementcustomerandbillingperiod).
2. But when I run the code I'm getting the following error.
`AttributeError: 'CostManagementClient' object has no attribute 'generate_cost_details_report'`

**To Reproduce**
1. Install the required packages - azure-identity,  azure-mgmt-costmanagement
2. set the environment variables - AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET.
3. Sample Code:
```
from azure.identity import DefaultAzureCredential
from azure.mgmt.costmanagement import CostManagementClient
import os
os.environ['AZURE_CLIENT_ID'] = "<client-id>"
os.environ["AZURE_TENANT_ID"] = "<tenant-id>"
os.environ["AZURE_CLIENT_SECRET"] = "<secret-value>"
def main():
    client = CostManagementClient(
        credential=DefaultAzureCredential(),
    )
    response = client.generate_cost_details_report.begin_create_operation(
        scope="/providers/Microsoft.Billing/billingAccounts/<billingAccountId>",
        parameters={"metric": "ActualCost", "timePeriod": {"end": "2020-03-15", "start": "2020-03-01"}},
    ).result()
    
    print(response)
if __name__ == "__main__":
    main()

```

4.  Error
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 48, in <module>
  File "<string>", line 37, in main
AttributeError: 'CostManagementClient' object has no attribute 'generate_cost_details_report'

```
**Expected behavior**
It is expected that the generate_cost_details_report should return a JSON response that contains a reference link to Azure blob container. The expected behavior can be found from the reference links.
**Reference Links**
1. Create Operation - [GenerateCostDetailsReportByBillingAccountEnterpriseAgreementCustomerAndBillingPeriod](https://learn.microsoft.com/en-us/rest/api/cost-management/generate-cost-details-report/create-operation?tabs=Python#generatecostdetailsreportbybillingaccountenterpriseagreementcustomerandbillingperiod)
2. Get Operation - [Get details of the operation result]( https://learn.microsoft.com/en-us/rest/api/cost-management/gencost-details-report/get-operation-results?tabs=Python#tabpanel_1_Python)

I don't understand whether these methods are deprecated. If there is any mistake in my process please let me know.

**Comment by msyyc** [comment]
Hi @Madhava24 Please try 4.0.0b1: https://pypi.org/project/azure-mgmt-costmanagement/4.0.0b1/

**Comment by Madhava24** [comment]
@msyyc  Yes with `azure-mgmt-costmanagement 4.0.0b1` my code is working fine. Thank you.
I wish this information to be included in the respective documentation pages and/or code samples.
