### ISSUE TITLE
Event consumption using BlobCheckpointStore results in 'Invalid link' error after several hours.

### ISSUE THREAD

**Issue by petersbingham** [Azure/azure-sdk-for-python#29081]
**Describe the bug**

As in title. After consuming for several hours (indeterminate, I've seen 8 and 13 for eg) service starts consistently failing with:
```
azure.eventhub._pyamqp.aio._session_async ERROR    Unable to attach new link: ValueError('Invalid link')
```

Our code is based on example here: [https://learn.microsoft.com/en-us/python/api/overview/azure/eventhub-checkpointstoreblob-aio-readme?view=azure-python in the section ""](https://learn.microsoft.com/en-us/python/api/overview/azure/eventhub-checkpointstoreblob-aio-readme?view=azure-python#consume-events-using-a-blobcheckpointstore-to-do-checkpoint)

I'm hitting the breakpoint below in _link_async.py:
```
170  	        if not frame[5] or not frame[6]:
171  	            import pdb; pdb.set_trace()
172  ->	            _LOGGER.info("Cannot get source or target. Detaching link", extra=self.network_trace_params)
173  	            await self._set_state(LinkState.DETACHED)
174  	            raise ValueError("Invalid link")
```

**To Reproduce**

Issue has come about after updating from our previously pinned requirements:
```
    azure-common==1.1.25
    azure-core==1.26.1
    azure-eventhub==5.3.1
    azure-eventhub-checkpointstoreblob-aio==1.1.2
    azure-graphrbac==0.61.1
    azure-identity==1.6.1
    azure-keyvault-keys==4.7.0
    azure-keyvault-secrets==4.6.0
    azure-mgmt-compute==29.0.0
    azure-mgmt-containerservice==20.7.0
    azure-mgmt-core==1.3.2
    azure-mgmt-keyvault==10.1.0
    azure-mgmt-monitor==5.0.1
    azure-mgmt-resource==21.2.1
    azure-mgmt-storage==21.0.0
    azure-storage-blob==12.5.0
```

to the latest (unpinned) which are:
```
    azure-common==1.1.28
    azure-core==1.26.3
    azure-eventhub==5.11.1
    azure-eventhub-checkpointstoreblob-aio==1.1.4
    azure-graphrbac==0.61.1
    azure-identity==1.12.0
    azure-keyvault-keys==4.7.0
    azure-keyvault-secrets==4.6.0
    azure-mgmt-compute==29.1.0
    azure-mgmt-containerservice==21.2.0
    azure-mgmt-core==1.3.2
    azure-mgmt-keyvault==10.1.0
    azure-mgmt-monitor==5.0.1
    azure-mgmt-resource==22.0.0
    azure-mgmt-storage==21.0.0
    azure-storage-blob==12.15.0
```

Run for several hours with the latest azure package versions. Error appears.

I can provide more details on request.

The error is handled internally, so I can't catch easily and restart the service, although I think it's coming from a worker thread.

Seems somewhat similar to the issue here: https://github.com/Azure/azure-sdk-for-python/issues/28498 although I'm not directly specifying a credential.

**Expected behavior**

- Consumption should run without interruption.
- Errors should have enough information attached to allow customer resolution.
- Method to restart service if fails.

**Comment by kashifkhan** [comment]
Thank you for the feedback @petersbingham . This issue looks to be similar to the one created here #28996. We are currently investigating it and trying to get a reliable repro. If you can provide me with certain information such as number of partitions, debug logs ( esp with information before the failures start ) it would be very helpful

**Comment by petersbingham** [comment]
![image](https://user-images.githubusercontent.com/13222776/222421487-41c1ce5d-cdd2-4763-aa1d-b269c3c8ba90.png)
It might take a while to get the logs. I need to test if there are any intermediate versions of your python libraries which don't have this issue which will satisfy our urgent requirements.

**Comment by erewok** [comment]
@petersbingham, we have this issue as well and we have switched back to `uamqp` on our projects (while staying with the latest version of `azure-eventhub`: `5.11.1`). To make the switch we had to do the following:

1. pip install uamqp
2. Add `uamqp_transport=True,` to kwargs for `EventHubConsumerClient.from_connection_string(...`

I think you can also try version `5.10.1`?

**Comment by scoser** [comment]
> @petersbingham, we have this issue as well and we have switched back to `uamqp` on our projects (while staying with the latest version of `azure-eventhub`: `5.11.1`). To make the switch we had to do the following:
> 
>     1. `pip install uamqp`
> 
>     2. Add `uamqp_transport=True,` to kwargs for `EventHubConsumerClient.from_connection_string(...`
> 
> 
> So far, we've switched 3 of our consumers and these are looking stable over the last 24 hours.
> 
> I think you can also try version `5.10.1`?

I was running into this as well, reverted back to 5.10.1 and that worked. Now I'm testing out 5.11.1 with the `uamqp_transport=True` option, which seems to be working fine for the past few days.

**Comment by petersbingham** [comment]
I'll be testing `uamqp` over the weekend. Thanks guys.

**Comment by kashifkhan** [comment]
Hi @petersbingham, we have closed the other issue as we have a fix for the bug that was causing this. We will be releasing a new version of the client library soon

**Comment by kashifkhan** [comment]
Hi @petersbingham , we have just released a new version of the library and its available on pypi with the fix for this issue 😀

**Comment by petersbingham** [comment]
Thanks a lot!😀

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by petersbingham** [comment]
I will let you know if this fixes our issue. Might be a week or two.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
