### ISSUE TITLE
Missing source archives for azure-template on PyPi

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-sdk-for-python#29104]
The latest releases of the `azure-template` package are missing their source releases on PyPi.

See:

- https://pypi.org/project/azure-template/0.1.0b2599452/#files
- https://pypi.org/project/azure-template/0.1.0b2595685/#files

**Comment by scbedd** [comment]
1) I am pretty impressed someone noticed so quickly. Nice catch @glaubitz !
2) @kristapratico Template pipeline is intentionally used as a test pipeline. In this case, we were testing a [new release process](https://github.com/Azure/azure-sdk-for-python/pull/29004) and this exact problem turned into a follow-up issue for the team that owns that new release process. At the end of the day it doesn't truly matter aside from the fact that it is a good smoke-test for our release process in general.
3) Said ESRP team pushed a fix over the weekend and I'll be testing that momentarily. If everything goes well the next template release should have the source dist again.
