### ISSUE TITLE
Azure cosmos API is locale dependent when sending RFC 1123 dates

### ISSUE THREAD

**Issue by MadJlzz** [Azure/azure-sdk-for-python#29109]
- **Package Name**: azure-cosmos
- **Package Version**: 4.3.1
- **Operating System**: Linux
- **Python Version**: 3.9.5

**Describe the bug**
Azure Cosmos API expects a RFC 1123 date format. When the format is wrong, we are receiving:
```
Message: The input date header is invalid format. Please pass in RFC 1123 style date format.
```
from the server.

Headers of the request are build within the library:
https://github.com/Azure/azure-sdk-for-python/blob/d33f0205bf340253dded4d46471034f319f3213f/sdk/cosmos/azure-cosmos/azure/cosmos/_base.py#L240-L241

The problem I have is that my personal locale is **not English**. It's **Luxemburgish**. That being said, `datetime.datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT")` will return a date with the given format that is following my locale `Do, 02 Mär 2023 16:43:01 GMT` instead of `Thu, 02 Mar 2023 16:43:01 GMT`

This breaks the server and we get a `exceptions.CosmosHttpResponseError` error at the client level.

**To Reproduce**
1. Switch your locale to Luxemburgish (didn't try to put a different one)
2. Initialize a `CosmosClient`
3. Do a call to the API ; in my case ; `list_databases()`
4. _Dramatic explosion_

**Expected behavior**
I let you guys decide what would be the best way to fix that but personally I would either force the date generation with an hard coded locale (not the best) or make the locale transparent on the server side.

Hopefully I am being clear 😄

**Comment by kashifkhan** [comment]
Thank you for the feedback @MadJlzz . We will investigate and get back to you asap.

**Comment by simorenoh** [comment]
Hi @MadJlzz, thank you for using our SDK. I will be leaving this link here while I start an internal conversation on adding the Babel package into our SDK to deal with scenarios like these: https://stackoverflow.com/questions/985505/locale-date-formatting-in-python

Was just wondering if you found a workaround for this, or how you went about using Cosmos after running into this.

**Comment by MadJlzz** [comment]
Hello there @simorenoh. Thanks for picking up this issue.

I have indeed found a workaround: (pretty intrusive though) I've changed my system locale to be the English one.

**Comment by simorenoh** [comment]
I see - yeah that was the second option that was recommended but I can see how that is not ideal for several reasons. Will keep you posted on what happens with this, happy to know you could at least get past this.

**Comment by bambriz** [comment]
Hi! This issue is currently being fixed. See [PR 30125](https://github.com/Azure/azure-sdk-for-python/pull/30125)

**Comment by bambriz** [comment]
This issue has been addressed in the following [PR30125](https://github.com/Azure/azure-sdk-for-python/pull/30125)

**Comment by bambriz** [comment]
@MadJlzz Verson 4.4.0b2 is now available and it includes the RFC fix.
