### ISSUE TITLE
azure-storage-blob is broken

### ISSUE THREAD

**Issue by blu3pr1n7-ofh** [Azure/azure-sdk-for-python#29110]
- azure-storage-blob
- ^12.15.0
- Linux
- 3.10 

**Describe the bug**
the azure blob storage client fundamentally does not work in a container.

**To Reproduce**
Steps to reproduce the behaviour: any use of the azure blob storage client in a docker container

**Expected behaviour**
to work as expected.

**Additional context**
Problem has been raised without fixes numerous times:
https://github.com/Azure/azure-sdk-for-python/issues/27953
https://github.com/Azure/azure-sdk-for-python/issues/13363

**Comment by kashifkhan** [comment]
Thanks for the feedback @blu3pr1n7-ofh . Can you provide some further details such as version of python, repro code etc please ?
