### ISSUE TITLE
Retraining with a pipeline uses cached data. 

### ISSUE THREAD

**Issue by akrsrivastava** [Azure/azure-sdk-for-python#29137]
- **azure-ai-ml**: 
- **SDK v2**: 
- **NA**:
- **Python Version 3.8**: 

**Describe the bug**
I created a ML training pipeline using a CSV file which was registered as a Data Asset. I then published the pipeline. Now I want to run the training with an updated CSV. But when I resubmit the pipeline, it is still using the old data from some cached location. How to I make the pipeline use the latest data in the CSV? How do i update the data asset with the new data CSV and how do I make sure my pipeline uses this new training data?

**Comment by kashifkhan** [comment]
Thanks for the feedback @akrsrivastava . Could you provide some repro code which can help the team better assist you. 

cc @azureml-github

**Comment by akrsrivastava** [comment]
This is the code to instantiate the pipeline
`pipeline = sail_model_train_pipeline(
    pipeline_job_data_input=Input(type="uri_file", path=ml_data.path),
    pipeline_job_test_train_ratio=0.20,
    pipeline_job_n_estimator=100,
    pipeline_job_registered_model_name=registered_model_name
)`

`pipeline_job = ml_client.jobs.create_or_update(
    pipeline,
    # Project's name
    experiment_name="sail_model_training",
)`

ml_data is my Data Asset which points to the training CSV file. 

The pipeline run shows the following information

<img width="306" alt="image" src="https://user-images.githubusercontent.com/19535249/222901140-2cac758d-d212-40cd-bc47-8ec42381df23.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/19535249/222901183-86bb2b27-0fe7-402c-a574-39762e31d8d7.png">

I change the training dataset CSV and the click on Resubmit 
<img width="310" alt="image" src="https://user-images.githubusercontent.com/19535249/222901493-24585f21-8b65-48b0-a6ba-fd499c7bbf4c.png">

But the pipeline does not pick up the latest dataset. Instead it trains the model on the same previous dataset.

How do I ensure that when i change my training CSV file, it should first get registered as an updated version of the Data Asset ml_data and then my pipeline run should pick up this latest data instead of continuing to use the data set which was used for the first time the pipeline was run and published.

Thanks!

**Comment by YingChen1996** [comment]
Hi, @akrsrivastava . Could I ask how you change the training dataset CSV? Do you change the csv in the datastore like this
![image](https://user-images.githubusercontent.com/26239730/223013882-326d4c97-2baa-41a8-9d68-15917a7732c2.png)
and then click resubmit button?

**Comment by akrsrivastava** [comment]
I have the CSV located as follows 

<img width="298" alt="image" src="https://user-images.githubusercontent.com/19535249/223030199-3b79fc2a-7b98-4d52-adb9-571ca8edd75b.png">

and I am registering it with Workspace
<img width="530" alt="image" src="https://user-images.githubusercontent.com/19535249/223030367-60a10a60-d208-4e45-b4ff-b8ce9fa3368b.png">

Then I proceed to build the training pipeline. Most of the code for it is similar to https://learn.microsoft.com/en-us/azure/machine-learning/tutorial-pipeline-python-sdk

I go up to the section Submit the Job. 

<img width="577" alt="image" src="https://user-images.githubusercontent.com/19535249/223031979-42341b37-c675-434a-bd63-343cbe2b6992.png">

The pipeline job runs and created a model. Then I also publish it as a Pipeline endpoint. 

In the next step, I overwrite the data/MLTrainTable.csv file with latest data and now I want to run the training on this dataset. I dont rerun the notebook again, becuase in production I just want to be triggering the training pipeline when I need to retrain the model on a new training data.
I go to the pipeline page which was created in the previous step and click on Resubmit
<img width="305" alt="image" src="https://user-images.githubusercontent.com/19535249/223031282-5072c63f-6fc8-4fa1-9378-a9be2f8f5874.png">

or I go to the Pipeline Endpoint page and click Submit
<img width="401" alt="image" src="https://user-images.githubusercontent.com/19535249/223031353-49e2b178-2a54-45f2-83d4-356a13c41870.png">

The pipeline runs but does not pick up the latest data which I just overwrote at data/MLTrainTable.csv
It still is working with the same previous data.

**Comment by YingChen1996** [comment]
Hi, @akrsrivastava , Could you describe more about how you manually overwrite the data/MLTrainTable.csv? 
Do you just edit the data in the datastore, save it and then resubmit? Our Ux colleague has tried to do this, and it seems the modified data take effect.

**Comment by akrsrivastava** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/19535249/223384787-c66b639b-6841-4778-84c3-f4bd3a1611ac.png">

I upload the new file using the above. I check the Overwrite if already exists

**Comment by YingChen1996** [comment]
Hi, @akrsrivastava, checked with UI teammates. This's by-design for now since when you resubmit, the input assetId and path won't change, and this node will reuse last successful one. 
One workaround is that for data register component, you can set ```is_deterministic: False``` and then when you resubmit, it will always run again

**Comment by akrsrivastava** [comment]
I moved the data to a Azure Storage container and created a DataAsset based on that location. Now whenever I run the pipeline it is taking up the latest data. The one part I can not still figure out is how to register the new data as a version update to the Data Asset from within the pipeline run.

**Comment by YingChen1996** [comment]
Hi, @akrsrivastava. Sorry for late response. I'm not sure what do you mean by "register the new data as a version update to the Data Asset from within the pipeline run".  Maybe doc here can help you: 
1. https://learn.microsoft.com/en-us/azure/machine-learning/how-to-create-data-assets?tabs=Python-SDK
2. https://learn.microsoft.com/en-us/azure/machine-learning/how-to-read-write-data-v2?tabs=python

**Comment by akrsrivastava** [comment]
Please close this.
