### ISSUE TITLE
Microsoft channel in Anaconda, but not in ReadMEs

### ISSUE THREAD

**Issue by Sclafus** [Azure/azure-sdk-for-python#29130]
**Is your feature request related to a problem? Please describe.**
Just stumbled upon [this channel](https://anaconda.org/Microsoft/repo) on Anaconda. Is this yours? I have never seen it in any ReadME, but from my understanding it is an official channel. 

**Describe the solution you'd like**
In all the ReadMEs, the Anaconda package is not cited at all, only the PyPi package. I would like to see it as an alternative if it is officially supported.

**Comment by rohit-ganguly** [comment]
Hi! Yes, that link is the official channel on Anaconda. Tagging @xiangyan99 and @lmazuel for visibility.

Thanks for bringing this up. We have official releases every 3 months to Anaconda, but there are conda-forge packages that update whenever a library is updated (these also have way more downloads than our releases - which gives us a few options on how to proceed).

**Comment by rohit-ganguly** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/28456#issuecomment-1401235049

Here's a previous explanation by Xiang on why we release to Anaconda in the way that we do.

**Comment by xiangyan99** [comment]
Thank you for the feedback. I like the idea. :) @Sclafus

**Comment by xiangyan99** [comment]
Added into READMEs.

**Comment by Sclafus** [comment]
@xiangyan99 Hello, I am not really sure where you added them... Is it on a non-public branch and it will be added on this repo in the future?

**Comment by xiangyan99** [comment]
@Sclafus we added the link into each readme. They are all public.

e.g. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/README.md
![image](https://user-images.githubusercontent.com/14350651/226035637-0307cd4f-371e-4148-9238-50cf17a63996.png)

**Comment by Sclafus** [comment]
I did not see that it was completed by #29342!
Thank you for the very fast response 🥇
