### ISSUE TITLE
Duplicate type signatures in fileshare/_file_client.py

### ISSUE THREAD

**Issue by wiwski** [Azure/azure-sdk-for-python#29156]
- **Package Name**: azure-storage-file-share
- **Package Version**: 12.11.0
- **Operating System**: Ubuntu
- **Python Version**: 3.10

**Describe the bug**
There is a function that has duplicate type signatures, preventing mypy from running.

```
/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/azure/storage/fileshare/_file_client.py:185: error: Function has duplicate type signatures  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

**Comment by kristapratico** [comment]
Thanks for the issue @wiwski, we'll take a look asap.

**Comment by jalauzon-msft** [comment]
Hi @wiwski, this has already been fixed in #28979 and the fix will be part of our next release. Thanks.

**Comment by stdedos** [comment]
Which is ...? For a "linting-showstopper", your cadence is a little bit disappointing 😕 

![image](https://user-images.githubusercontent.com/133706/223730028-08f30da3-14b1-4487-a553-7eb4d362408f.png)

**Comment by jalauzon-msft** [comment]
@wiwski and @stdedos, we released this fix in a patch release today. Version `12.11.1` should have the fix for this. Thanks.
