### ISSUE TITLE
readme snippet tool needs cushion between tags and python snippets for github.io

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#29166]
A sample without a newline between the tags and the python snippet:

![image](https://user-images.githubusercontent.com/31998003/223266698-e2ce3c02-6b2b-4b28-8a9f-5ab8cc45cdf7.png)

will render like this in the github.io docs:

![image](https://user-images.githubusercontent.com/31998003/223265893-e5bd3a72-b8e2-49e0-abfb-16dda091b7c8.png)

Note that it renders fine on the README in Github. For some reason, github.io is just a little bit different.

**Comment by kristapratico** [comment]
FYI @xiangyan99

**Comment by catalinaperalta** [comment]
Form Recognizer snippets are also looking like that ^
