### ISSUE TITLE
Azure/azure-sdk KeyVault - accessing secret from App Service is not working.

### ISSUE THREAD

**Issue by jettinag** [Azure/azure-sdk-for-python#29189]
Authentication is working with 'DefaultAzureCredential' but when I try to access the value by key getting error as
"Bearer token authentication is not permitted for non-TLS protected (non-https) URLs." Reproduced same issue by running code at VM.

cred = DefaultAzureCredential()
client = SecretClient(vault_url="https://sample-name.vault.azure.net/)", credential=cred)
client.get_secret("sample-key")

Any assistance you can provide would be greatly appreciated.

**Comment by kristapratico** [comment]
Hi @jettinag thanks for the feedback. Can you share which versions of the azure-identity and azure-keyvault-secrets packages you are using?

**Comment by mccoyp** [comment]
Hi @jettinag, this error means that your SecretClient is attempting to make a request to a non-HTTPS endpoint (i.e. a URL not starting with `https://`). Do you know if you're using a proxy or running in an environment that may explain this? Also, are you able to see the content of the request that raised this error?

**Comment by jettinag** [comment]
> azure-keyvault-secrets
Hi @mccoyp, the above 2 packages are latest versions I am referring in the code.
azure-identity 1.12.0
azure-keyvault-secrets==4.6.0

**Comment by mccoyp** [comment]
Hi @jettinag, thank you for the version information. Are you able to capture and share any content of the outgoing request that causes the issue? Specifically, I'd like to see the endpoint being used in the `get_secret` request.

The request itself most likely isn't actually getting sent to the service, so the easiest way to capture this request would be to set a breakpoint or logging at the start of the `_enforce_tls` method: https://github.com/Azure/azure-sdk-for-python/blob/6749e4ca341d89dee9b4caf999440ed47e2b1dc0/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L38-L43

For example, on the line before the error is raised, you could try logging the URL that's causing the problem:
```python
def _enforce_tls(request):
    # type: (PipelineRequest) -> None
    if not request.http_request.url.lower().startswith("https"):
        # Log the endpoint that causes the exception
        import logging
        logging.error(f"Non-HTTPS request endpoint: {request.http_request.url}")
        raise ServiceRequestError(
            "Bearer token authentication is not permitted for non-TLS protected (non-https) URLs."
        )
```
