### ISSUE TITLE
azure-ml - maintain different package version on main and release branches

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#29196]
azure-ml package is published from release branches and not from main branch. Scheduled nightly and Individual CI runs from main branch. Package version is same on both release branch as well as main branch and this causes confusion when API review gets created from release branch when pipeline is triggered manually and from main branch when pipeline is triggered by scheduled run.

This can be handled in APIView be retaining an API revision for each `major.minor` package version combination but unfortunately that won't resolve issue for azure-ml package because package version is always same on both main and release branch.

We have implemented a short solution of creating automatic API revision only when pipeline is triggered manually for azure-ml.

Purpose of this this issue is to track long term solution.
Long term solution should be to have different versions on main branch and release branch for python package so APIView can have different revisions for each version.

**Comment by achauhan-scc** [comment]
closing as obsolete
