### ISSUE TITLE
Service Bus Async with Opentelemetry: receiver._add_span_request_attributes never awaited

### ISSUE THREAD

**Issue by erewok** [Azure/azure-sdk-for-python#29199]
- **Package Name**: 
  - `azure-servicebus = "^7.8.2"`
  - `azure-core-tracing-opentelemetry = "^1.0.0b9"`

- **Operating System**: OSX/Debian Container `python:3.11-slim-bullseye`
- **Python Version**: 3.11.2

**Describe the bug**
Async service-bus receiver with opentelemetry enabled warns: 

```sh
/my-app/.venv/lib/python3.11/site-packages/azure/servicebus/_common/utils.py:287: RuntimeWarning: coroutine 'BaseHandler._add_span_request_attributes' was never awaited
  receiver._add_span_request_attributes(receive_span)  # type: ignore  # pylint: disable=protected-access
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**To Reproduce**

I made a gist which reproduces this: https://gist.github.com/erewok/7cf27c54673f0e6fa0265e5ef24df6ff

**Expected behavior**
No warnings: span-context is added as expected.

**Additional context**
It looks like [this method](https://github.com/Azure/azure-sdk-for-python/blob/e99e1f8a47cec1e9568c7e2eea9bd21bf2d52915/sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py#L390) is async but it's being called by [this sync method](https://github.com/Azure/azure-sdk-for-python/blob/e99e1f8a47cec1e9568c7e2eea9bd21bf2d52915/sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py#L223).

Worth noting: the python opentelemetry implementation [may be changed in the future](https://github.com/open-telemetry/opentelemetry-python/issues/62) to support async spans.

Also: _sending_ a message does not show the same warning in the logs.

**Comment by kashifkhan** [comment]
Hi there @erewok . Thank you for the feedback, I think we had a similar issue where we addressed it but looks like another one snuck in.

**Comment by kashifkhan** [comment]
Looks like it will be taken care of by this PR #28761

**Comment by erewok** [comment]
Sounds good @kashifkhan. We can close this one and I'll look for that release. Thanks for the update.

**Comment by kashifkhan** [comment]
Ill close it once it goes out :)

**Comment by erewok** [comment]
Appreciate it. Apologies: I should have searched before opening this. I just had this feeling that the async-python+otel users would be a smallish group at this point... 🤷

**Comment by kashifkhan** [comment]
@erewok no worries about that at all :)

**Comment by kashifkhan** [comment]
Hi @erewok , we released a new version of azure-servicebus yesterday with the fix for this. Thank you :)

**Comment by erewok** [comment]
Sounds good. Thanks for letting me know.
