### ISSUE TITLE
Azure ML SDK v2 (azure-ai-ml) no longer installing azure-identity as a dependency

### ISSUE THREAD

**Issue by glebrh** [Azure/azure-sdk-for-python#29226]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.3.0 and 1.4.0 (The last working one was 1.2.0)
- **Operating System**: Windows Server 2022. MacOS  Ventura 13.2
- **Python Version**: 3.9.16

**Describe the bug**
After installing `azure-ai-ml` SDK version 1.3.0+ `azure-idenitity` module is no longer installed by default. This behavior changed, since for SDK versions <=1.2.0 it was done by default.

Missing dependency requires explicit installation of `azure-identity` module, which is not mentioned in any of the tutorials/READMEs for `azure-ai-ml` (saying only installation of `azure-ai-ml` is sufficient). Examples [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/README.md#install-the-package) and [here](https://github.com/Azure/azureml-examples/blob/sdk-preview/sdk/README.md#getting-started)

Either documentation should be changed or missing dependency should be incorporated.

**To Reproduce**
1. Create a virtual environment using Python 3.9.16 (tested with 3.10.9 - also not working as expected)
2. Try to install `azure-ai-ml==1.4.0`
3. Check for `azure-identity` - it will be missing

**Expected behavior**
`azure-identity` will be installed automatically.

**Comment by kristapratico** [comment]
Hi @glebrh thanks for your issue. @azureml-github will take a look and get back to you as soon as possible.

**Comment by kdestin** [comment]
Thank you for the feedback.

`azure-identity` was removed as an explicit dependency of `azure-ai-ml` in preparation for our `1.0.0` release.

We'll work to improve the documentation to reflect that.

**Comment by glebrh** [comment]
Hi @kdestin,

Thanks for the feedback. This is strange, since `azure-identity` is still **implicitly** installed for versions <=1.2.0 and only missing for >=1.3.0.

So just to reconfirm: the target approach will be no implicit installation of `azure-identity` while installing `azure-ai-ml`, causing need `azure-identity` to install it separately?

**Comment by kdestin** [comment]
> Thanks for the feedback. This is strange, since `azure-identity` is still **implicitly** installed for versions <=1.2.0 and only missing for >=1.3.0.

Ah, thank you for pointing this out. I was able to reproduce this. Looks like this caused by dependency removed in 1.3.0 which itself depended on `azure-identity`.
 
> So just to reconfirm: the target approach will be no implicit installation of `azure-identity` while installing `azure-ai-ml`, causing need `azure-identity` to install it separately?

The intended installation experience would be:

```
pip install azure-ai-ml
pip install azure-identity
```

This should be in alignment with the other Azure Python SDKs.

**Comment by glebrh** [comment]
Good, thanks for the confirmation. I guess docs should be figured out then. Should we have a separate issue for that?

**Comment by kdestin** [comment]
> Good, thanks for the confirmation. I guess docs should be figured out then. Should we have a separate issue for that?

No need, we can track that here.
