### ISSUE TITLE
cannot import name 'CaseInsensitiveEnumMeta' from 'azure.core'

### ISSUE THREAD

**Issue by mclacore** [Azure/azure-sdk-for-python#29253]
- **Package Name**: `azure.core`
- **Package Version**: `1.26.3`
- **Package Name**: `azure-ai-ml`
- **Package Version**: `1.4.0`
- **Package Name**: `azure-identity`
- **Package Version**: `1.12.0`
- **Package Name**: `msrest`
- **Package Version**: `0.7.1`
- **Operating System**: Ubuntu 20.04.4 LTS
- **Python Version**: Python 3.8.10

**Describe the bug**

Error when trying to run a notebook with fully updated packages.

**To Reproduce**
1. Run this:
```python
#import required libraries for workspace
from azure.ai.ml import MLClient
from azure.identity import DefaultAzureCredential

#import required libraries for environments examples
from azure.ai.ml.entities import Environment, BuildContext

#Enter details of your Azure Machine Learning workspace
subscription_id = '<sub_id>'
resource_group = '<resource_grp>'
workspace = '<workpace>'

#connect to the workspace
ml_client = MLClient(DefaultAzureCredential(), subscription_id, resource_group, workspace)
```

**Expected behavior**

The notebook to execute without a problem

**Screenshots**

![image](https://user-images.githubusercontent.com/8037512/224117060-7da2995b-1c63-4c99-80fc-0a6d5296a87e.png)

**Additional context**

**Comment by kashifkhan** [comment]
Thanks for the feedback @mclacore . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by kdestin** [comment]
I can't reproduce. I can run the provided script with no errors in the following environment:

```console
 $ python --version
Python 3.8.10
```
```console
 $ pip freeze
attrs==22.2.0
azure-ai-ml==1.4.0
azure-common==1.1.28
azure-core==1.26.3
azure-identity==1.12.0
azure-mgmt-core==1.3.2
azure-storage-blob==12.15.0
azure-storage-file-datalake==12.10.1
azure-storage-file-share==12.11.1
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
colorama==0.4.6
cryptography==39.0.2
idna==3.4
importlib-resources==5.12.0
isodate==0.6.1
jsonschema==4.17.3
marshmallow==3.19.0
msal==1.21.0
msal-extensions==1.0.0
msrest==0.7.1
oauthlib==3.2.2
packaging==23.0
pkgutil-resolve-name==1.3.10
portalocker==2.7.0
pycparser==2.21
pydash==5.1.2
PyJWT==2.6.0
pyrsistent==0.19.3
python-dateutil==2.8.2
PyYAML==6.0
requests==2.28.2
requests-oauthlib==1.3.1
six==1.16.0
strictyaml==1.6.2
tqdm==4.65.0
typing-extensions==4.5.0
urllib3==1.26.14
zipp==3.15.0
```
---

It's possible that the packages in your Jupyter kernel may be out of date. You can check by running `%pip freeze` in one of your notebook cells and inspecting the output.
