### ISSUE TITLE
ServiceRequestError: Can't connect to HTTPS URL because the SSL module is not available for Azure BLOD Storage account

### ISSUE THREAD

**Issue by rama-22** [Azure/azure-sdk-for-python#29275]
from azure.storage.blob import ContainerClient

container_client = ContainerClient.from_connection_string(conn_str=connection_string, container_name="files-1")

container_client.create_container()

`Error:  ServiceRequestError: Can't connect to HTTPS URL because the SSL module is not available.`

**Comment by kashifkhan** [comment]
Hi @rama-22, can you please provide some more information about your setup such as OS, python version, installed dependencies, conda etc that will help us assist you. Thanks
