### ISSUE TITLE
Why is the documentation so anemic and difficult to navigate?

### ISSUE THREAD

**Issue by kalebdfischer** [Azure/azure-sdk-for-python#29283]
The documentation for the python Azure SDK is vastly inferior to the other cloud providers in terms of developer experience. The package code is more useful than the documentation. It would be so much better if there was easy-to-locate, clear, and concise documentation of models, methods, functions, and inputs/outputs. Python's weak typing makes this information critical and Microsoft has really dropped the ball here with documentation standards/culture. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29f4a073-90d6-7b05-e160-1264d14e97ce
* Version Independent ID: f97dbe18-c983-bb4a-cc53-adbc3890b703
* Content: [azure-mgmt-compute package](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-compute/index.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-compute/index.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
Hi @kalebdfischer thanks for your feedback. Adding @rohit-ganguly to take a look.

**Comment by rohit-ganguly** [comment]
Hi @kalebdfischer! Thanks for the feedback.

We're currently doing research on updating our Python docs on MS Learn to support a better developer experience through our docs. One thing we're especially aware of are these redundant overview pages in the example you linked, and we are working through solutions on how to auto-generate our docs in a clearer way. 

If there's any specific things that you found especially confusing or annoying, we'd love to hear your honest thoughts. You can comment here or send me an email at my first name (Rohit) dot last name (Ganguly) at microsoft.com.
