### ISSUE TITLE
pls provide some examples for create_or_update or get methods

### ISSUE THREAD

**Issue by KarthikATOS22** [Azure/azure-sdk-for-python#29306]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aef29dff-2214-2a90-3872-0763bbf43cc7
* Version Independent ID: a8fe4273-36e9-3520-4c80-d673ced27dd4
* Content: [azure.purview.scanning.operations.FiltersOperations class](https://learn.microsoft.com/en-us/python/api/azure-purview-scanning/azure.purview.scanning.operations.filtersoperations?view=azure-python-preview)
* Content Source: [preview/docs-ref-autogen/azure-purview-scanning/azure.purview.scanning.operations.FiltersOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/preview/docs-ref-autogen/azure-purview-scanning/azure.purview.scanning.operations.FiltersOperations.yml)
* GitHub Login: @VSC-Service-Account

**Comment by l0lawrence** [comment]
Hello @KarthikATOS22 thank you for the feedback, we will get back to you asap.

**Comment by msyyc** [comment]
Hi @KarthikATOS22 Please refer to this sample: https://github.com/Azure/azure-sdk-for-python/blob/db22a733e7c9f68be298db845b8922ace465eae4/sdk/purview/azure-purview-scanning/samples/create_workflow.py

**Comment by msyyc** [comment]
I don't have much domain knowledge about this scenario and I am looking for help from other experts. Before that, maybe you can get help from swagger examples: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/purview/data-plane/Azure.Analytics.Purview.Scanning/preview/2022-07-01-preview/examples

**Comment by xiangyan99** [comment]
> I don't have much domain knowledge about this scenario and I am looking for help from other experts. Before that, maybe you can get help from swagger examples: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/purview/data-plane/Azure.Analytics.Purview.Scanning/preview/2022-07-01-preview/examples

@KarthikATOS22 Please let us know if it works.
