### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by krisrajzlive** [Azure/azure-sdk-for-python#29309]
https://learn.microsoft.com/en-us/python/api/overview/azure/iot/management

**Comment by l0lawrence** [comment]
Hi thanks for the feedback, we will get back to you asap.

**Comment by SaurabhSharma-MSFT** [comment]
@krisrajzlive How did you come to this link?

**Comment by navba-MSFT** [comment]
@krisrajzlive Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
