### ISSUE TITLE
Unable to set "x-ms-correlation-request-id" header in SDK call

### ISSUE THREAD

**Issue by saisankargochhayat** [Azure/azure-sdk-for-python#29325]
- **Package Name**: azure-mgmt-resourceconnector
- **Package Version**: "1.0.0b3"
- **Operating System**: Windows
- **Python Version**: 3:10

**Describe the bug**
As per [ARM RPC](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#client-request-headers) we should be able to set the above header as a part of client request
However when we try setting this in Python SDK RP call this is not being set in the out going request

**To Reproduce**
```
rpHeaders = {
                        "x-ms-client-request-id": <any valid guid>,
                    }
appl_client.appliances.begin_create_or_update(resource_group_name=resourceData['resource']['resource_group'],
                                                      resource_name=resourceData['resource']['name'],
                                                      parameters=appliance, headers=rpHeaders)
```

**Expected behavior**
Expected request should pass the header passed in the request, however a random GUID is send as shown in example below.

**Screenshots**
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '176'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '4159a480-c203-11ed-b9e5-6045bdc724a4'
cli.azure.cli.core.sdk.policies:     'x-ms-return-client-request-id': 'True'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'CommandName': 'arcappliance deploy vmware'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--config-file --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.45.0 (PIP) azsdk-python-mgmt-resourceconnector/1.0.0b3 Python/3.10.8 (Windows-10-10.0.22000-SP0) arcappliance-extension-version/1.0.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'

**Additional context**
Is there any example of callers using this feature, or am I missing something in passing this header?

**Comment by kashifkhan** [comment]
Thank you for the feedback @saisankargochhayat . We will investigate and get back to you

**Comment by msyyc** [comment]
Hi, could you refer to https://github.com/Azure-Samples/azure-samples-python-management/blob/383e56e4c2b970be93d24daffcc95a9a8b01916c/samples/resourceconnector/manage_create.py. I can set `"x-ms-client-request-id"` successfully in the sample:
![image](https://user-images.githubusercontent.com/70930885/225187239-1a358f91-4c0d-4a50-878e-4dc312f93b54.png)

**Comment by saisankargochhayat** [comment]
Hi @msyyc thanks for the snippet and confirmation, I was able to set it as well via the script. Realized the issue was CLI core overwriting this header passed in.
