### ISSUE TITLE
Deploy and score a machine learning model locally unable to access GPU in container

### ISSUE THREAD

**Issue by HeChengHui** [Azure/azure-sdk-for-python#29357]
[Python SDK azure-ai-ml v2]
[ubuntu20.04]
[python 3.10.9]

**Describe the bug**

1. When ran inside the container in docker engine (windows)
```
>>> import torch

>>> torch.cuda.is_available()
False
```

2. Unable to use `nvidia-smi`

3.  onnxruntime-gpu error when loading model
```
>>> import onnxruntime
>>> session = onnxruntime.InferenceSession(model_path, None, providers=['CUDAExecutionProvider'])  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:124 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=0 ; hostname=7fa6809dc806 ; expr=cudaSetDevice(info_.device_id); 
```

**To Reproduce**

```
deployment = ManagedOnlineDeployment(
    name=name,
    endpoint_name=local_endpoint_name,
    model=model
    environment=Environment(
        image="mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.6-cudnn8-ubuntu20.04",
        conda_file="/environmentV2.yml",
        name=env_name,
    ),
    code_configuration=CodeConfiguration(
        code=r'\Azure\ML', scoring_script="score_test.py"
    )
)

print("starting endpoint...")
ml_client.online_endpoints.begin_create_or_update(endpoint, local=True)
print("Done endpoint\n")

print("Starting deployment...")
ml_client.online_deployments.begin_create_or_update(
    deployment=deployment, local=True)
print("Done deployment\n")
```

**Additional context**
Tried:
1. https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit
2. `apt-get -y install cuda-drivers`  (no sudo command found)

**Comment by l0lawrence** [comment]
Hi @HeChengHui thanks for the feedback, we will direct this to @azureml-github

**Comment by harneetvirk** [comment]
If the version of CUDA on Docker is different from the version of CUDA on the PC, it can lead to compatibility issues between the software and the GPU. This can result in reduced performance, errors, or even crashes. To ensure compatibility, it's important to match the version of CUDA on Docker with the GPU driver version of CUDA on the PC.

You can see the minimum driver versions required to support specific CUDA versions in table 2: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions

If you want to use CUDA in a container, you may try NVIDIA container toolkit to enable the portability in Docker images that leverage NVIDIA GPUs: https://github.com/NVIDIA/nvidia-docker

**Comment by HeChengHui** [comment]
@harneetvirk 
I am running on a Windows10 host. Besides changing the CUDA version to match the base image of "mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.6-cudnn8-ubuntu20.04", do I need to install NVIDIA container toolkit on my host? From what I [read](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#linux-distributions), it seems to be only for Linux OS?

**Comment by HeChengHui** [comment]
@harneetvirk 
I have tried on a Ubuntu 20.04 host with CUDA 11.6.2, using the above code. However, still 
```
>>> torch.cuda.is_available()
False
```

**Comment by fernandorovai** [comment]
Any news on this? I'm facing exactly the same problem while deploying locally using GPU

**Comment by rishavmandal771** [comment]
facing the same problem here as well

**Comment by xiangyan99** [comment]
Close the issue as 1.8.0 has shipped.
