### ISSUE TITLE
azure.mgmt.resource - missing Anaconda Python package

### ISSUE THREAD

**Issue by AaronSaikovski** [Azure/azure-sdk-for-python#29377]
It appears that the following package is missing from the Microsoft Anaconda repo - https://anaconda.org/microsoft/repo

when trying to use the following import in my python code:
**from azure.mgmt.resource import ResourceManagementClient**

The package: 
azure.mgmt
is not available in Anaconda but available in PyPi. Will this be added in the future? Or is it rolled up into a different package like azure-core?

**Comment by xiangyan99** [comment]
We pack mgmt SDKs in one conda package azure-mgmt. https://anaconda.org/microsoft/azure-mgmt.

You can find more information in https://github.com/Azure/azure-sdk-for-python/blob/main/conda-releaselogs/azure-mgmt.md.
