### ISSUE TITLE
[Form Recognizer] The operation was canceled due to pipeline timeout.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-python#29381]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error description:**
The tests in the Form Recognizer are taking too long to run on the `Canary` and `UsGov` clouds (some up to two hours). This caused the operation to be canceled due to pipeline timeout.

Here is the latest result in weekly pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2630885&view=results
![image](https://user-images.githubusercontent.com/81678720/225527006-bafd3ca2-a358-4607-806d-40db4165501a.png)

**Notes:** The same thing happened in the master.

Here is the latest result in daily pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2632115&view=results

**Expected Behavior:**
All tests can run normally in `Canary` and `UsGov` clouds.

@benbp , @rohit-ganguly , @lmazuel , @achandmsft , @mayurid , @catalinaperalta for notification.

**Comment by catalinaperalta** [comment]
The service team is aware of the issue and has said they are going to roll out a fix tomorrow.

**Comment by catalinaperalta** [comment]
The service team pushed a fix today and the pipeline is no longer timing out. There are a couple of test issues that are showing up in canary that we are investigating. Will close this now since the original issue is resolved.
