### ISSUE TITLE
Support path segments on InteractiveBrowserCredential redirect URIs

### ISSUE THREAD

**Issue by jackStalnaker** [Azure/azure-sdk-for-python#29393]
**Is your feature request related to a problem? Please describe.**
Our organization (and probably others) uses redirect URIs of the form http://localhost:11111/foo for some historical reason. If I specify this as the redirect_uri parameter of the `InteractiveBrowserCredential` constructor, `azure.identity._credentials.browser.InteractiveBrowserCredential._request_token()` parses the provided URI and reconstructs it using just the hostname and port. Authorization fails because the reconstructed URI does not match the one specified in the client.

**Describe the solution you'd like**
Support path segments in redirect URIs.

**Describe alternatives you've considered**
For now, I am monkeypatching the line in _request_token() from

    redirect_uri = "http://{}:{}".format(self._parsed_url.hostname, self._parsed_url.port)

to

    redirect_uri = "http://{}:{}{}".format(self._parsed_url.hostname, self._parsed_url.port, self._parsed_url.path)

but this is very fragile, and not at all future proof.

**Additional context**
I understand that this is probably all very intentional as a first line security feature. But since Azure allows redirect URIs of the form above, the Python SDK should support it, too.

**Comment by l0lawrence** [comment]
Hi @jackStalnaker thanks for the feedback, we will get back to you asap.

**Comment by rayluo** [comment]
> **Describe alternatives you've considered** For now, I am monkeypatching the line in _request_token() from
> 
> ```
> redirect_uri = "http://{}:{}".format(self._parsed_url.hostname, self._parsed_url.port)
> ```
> 
> to
> 
> ```
> redirect_uri = "http://{}:{}{}".format(self._parsed_url.hostname, self._parsed_url.port, self._parsed_url.path)
> ```
> 
> but this is very fragile, and not at all future proof.

Was that line from an older version of Azure SDK? I do not see that line in the [latest Azure SDK](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/browser.py#L64).


> Is your feature request related to a problem? Please describe.
> Our organization (and probably others) uses redirect URIs of the form http://localhost:11111/foo for some historical reason.

Did your organization previously use Azure SDK with `http://localhost:11111/foo` and it worked before? Or is this the first time that you start to use Azure SDK and run into this?

**Comment by rayluo** [comment]
> It is the version in PyPi, which is 1.12.0.

Thanks. Found it [here](https://github.com/Azure/azure-sdk-for-python/blob/azure-identity_1.12.0/sdk/identity/azure-identity/azure/identity/_credentials/browser.py#L70). So, Azure SDK never supported a path segment before. Then, we are not talking about a regression (CC @xiangyan99 ), we are talking about whether to introduce a "new feature".

> **Additional context**
> I understand that this is probably all very intentional as a first line security feature. But since Azure allows redirect URIs of the form above, the Python SDK should support it, too.

Azure Portal's allowing redirect URI to be `http://localhost:1234/foo/bar/baz` does not mean those foo bar thing has any significance in itself. It merely allows app developer to specify a redirect URI matching what their local HTTP server expects.

Assuming you are still using your own auth implementation, and then when/if your local HTTP server changes to a different implementation which expects a different path or no path, you (or your app's admin) would have to change the redirect URI setting in Azure Portal to match your new local HTTP server's implementation.

Now, your switching to use Azure SDK (which internally uses MSAL's `acquire_token_interactive()` is a new implementation which expects a path-less redirect URI. So, the correct way to solve this is to change your app's redirect URI in Azure Portal.

> Our organization used web api calls and a local HTTP server (not much different from what seems to happen here). The server doesn't care about the path segment. The only thing that cares is the validation against the app registration.

As you mentioned, your local HTTP server "doesn't care about the path segment" either. So, arguably, that `/foo` segment in your existing redirect URI was meaningless in the first place.

**Comment by jackStalnaker** [comment]
Point taken. My only counter would be that Azure lets you register redirect URIs with that syntax. On the other hand, it is very clearly documented in the msal module docs for acquire_token_interactive().

**Comment by rayluo** [comment]
> My only counter would be that Azure lets you register redirect URIs with that syntax.

Just to clarify. Azure Portal allows many different redirect URI formats. Some are even for different platforms such as Android, iOS, and different scenarios. Any given client-side SDK typically only supports a small subset of those scenarios. It is never a design goal for an auth SDK to match *all* redirect URI that Azure Portal can take.



> On the other hand, it is very clearly documented in the msal module docs for acquire_token_interactive().

Thanks for reading [MSAL's docs](https://msal-python.readthedocs.io/en/latest/#msal.PublicClientApplication.acquire_token_interactive). Now I feel [my effort on docs](https://github.com/AzureAD/microsoft-authentication-library-for-python/commit/6cc124fe7503c1ef315bb55469fa2011e011009f) was well worth it, and I dodged a bullet. :-)

Shall we close this issue as a WontFix now?
