### ISSUE TITLE
Review and add notebook for running ML atop Log Analytics

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-python#29405]
**Context:**
Conduct a technical review and add (to the Python SDK repo) a Jupyter notebook that demonstrates:

- Running queries on top of LA demo workspace using AzMon query library
- Exploration of data and running very basic ML training, scoring, finding anomalies on top LA (without need to export). We can also and point to example of splitting big queries - its super relevent for ML use case.
- Returning anomalies back to LA using Logs Ingestion library. The LA content developer will add needed explanations to the notebook.

As discussed in a 3/15 meeting with Ilana, create a new _samples_ directory in the root of the repo. Store the notebook in that newly created directory. Link to the notebook in the appropriate places within the Monitor Ingestion and Query libraries.

**Comment by pvaneck** [comment]
Closed via https://github.com/Azure/azure-sdk-for-python/pull/30682
