### ISSUE TITLE
EnableSupportLogging (Allow extraction of all MSAL logs)

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-python#29406]
**Context:**
When customers encounter bugs in MSAL, the MSAL team needs detailed logs to diagnose the issue. The Azure Identity library doesn't have a provision to extract all these logs. In particular, we need verbose logs with PII information. For context, MSAL exposes 2 knobs for logging:

1. The log verbosity, which is very closely related to Azure SDK’s verbosity, i.e. Verbose, Info, Warning, Error.
2. A PII flag, false by default. Note: For a cheat sheet of what gets logged, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/PII.

The request is to allow app developers using the Azure Identity library to collect Verbose + PII logs from MSAL, on request, which are sometimes needed for supportability. The Azure Identity library exposes some knobs already, but there's no alignment over PII.

**Comment by pvaneck** [comment]
Some notes:

MSAL Python does not have the capability to enable PII logging and pretty much always work in non-PII mode. According to the MSAL team, a need for PII logs in troubleshooting hasn't really been encountered, so it was chosen to just not log PII.

Standard logging through the `logging` library is still the appraoch to use for gathering additional MSAL log information.

**Comment by joshfree** [comment]
Related https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1755813/?triage=true

**Comment by joshfree** [comment]
Needs new feature in MSAL for Python to enable this feature at our layer of the stack.  Other languages (C#, Java, JS/TS) support this capability already.

**Comment by joshfree** [comment]
@schaabs and @pvaneck will sync up today on choosing a name for this flag
