### ISSUE TITLE
Enable web view customization for interactive authN

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-python#29412]
**Context:**
Azure PowerShell relies on the Azure Identity library to use MSAL. Currently, we're required to customize the web view displayed after authentication, which requires the Azure Identity library to open new properties that are already supported by MSAL.

The primary scenario to enable here is to expose an option to control whether the embedded or system browser will be invoked.

**Comment by christothes** [comment]
see .NET PR for an example: https://github.com/Azure/azure-sdk-for-net/pull/34095

**Comment by xiangyan99** [comment]
From Python msal:

There is no such thing as embedded webview in Python language. All we can do is to launch system browser.

Close as N/A for Python.
