### ISSUE TITLE
[azure ml] missing option to register model with associated data asset in sdk v2

### ISSUE THREAD

**Issue by MarkusDressel** [Azure/azure-sdk-for-python#29429]
- **azure.ai.ml**: 
- **1.4.0**: 
- **Linux 20xx**:
- **3.10**: 

**Describe the bug**
I want to register a trained model to azure ml model registry. It is important to also attach the associated data asset to the model so it get displayed under the `Data` section.
![image](https://user-images.githubusercontent.com/50589320/225867915-1d39f682-981f-453c-bbf1-071de43fbcfd.png)

**To Reproduce**
1. Connect to workspace
```python
# get a handle to the workspace
ml_client = MLClient.from_config(DefaultAzureCredential())
print(ml_client.workspace_name, ml_client.resource_group_name, sep='\t\t')
```
2. get registered data asset
```python
data_asset_name = "file-dataset"
data_asset = ml_client.data.get(name=data_asset_name, version=1)
```
3. train an arbitrary model
4. register model **with data asset**
```python
from azure.ai.ml.entities import Model
from azure.ai.ml.constants import AssetTypes

file_model = Model(
    path="mlflow-model/model.pkl",
    type=AssetTypes.CUSTOM_MODEL,
    name="local-file-example",
    description="Model created from local file.",
    # in sdk v1 there was an attribute called datasets
)
ml_client.models.create_or_update(file_model)

```

**Expected behavior**
To have a documented way on how to associate data assets to the trained and registered model

**Comment by kashifkhan** [comment]
Thank you for the feedback @MarkusDressel . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by hugoaponte** [comment]
Hello,

Thanks for the feedback. The new SDK doesn't offer this functionality. We have this in the backlog but no ETA yet. I am adding this post to the backlog item for tracking.

We don't have a great work around unfortunately.

As an alternative, the Studio UI shows the job that trained a model, and you could navigate to the data assets used in the job.

Programmatically though, a workaround would be to add the data to the artifacts registered with the model. I am unsure on how you may want to use the data assets later, but this option could be an alternative even if you need the data asset at deployment time.

Thanks,

Hugo
