### ISSUE TITLE
azure-keyvault-secrets 4.7.0: SecretClient Pyright reports error error: Type of "begin_delete_secret" is partially unknown  

### ISSUE THREAD

**Issue by zhouwangzw** [Azure/azure-sdk-for-python#29448]
- **Package Name**:  azure-keyvault-secrets
- **Package Version**:  4.7.0
- **Operating System**:
- **Python Version**: 3.10

**Describe the bug**
When upgrading from azure-keyvault-secrets from 4.6.0 to 4.7.0, Pyright V1.1.236 as well as V1.1.299 (the latest one) reports the following errors:
 error: Type of "begin_delete_secret" is partially unknown
    Type of "begin_delete_secret" is "(name: str, **kwargs: Unknown) -> LROPoller[DeletedSecret]" (reportUnknownMemberType)
error: Type of "get_secret" is partially unknown
    Type of "get_secret" is "(name: str, version: str | None = ..., **kwargs: Unknown) -> KeyVaultSecret" (reportUnknownMemberType)
error: Type of "set_secret" is partially unknown
    Type of "set_secret" is "(name: str, value: str, **kwargs: Unknown) -> KeyVaultSecret" (reportUnknownMemberType)
error: Type of "begin_recover_deleted_secret" is partially unknown
    Type of "begin_recover_deleted_secret" is "(name: str, **kwargs: Unknown) -> LROPoller[SecretProperties]" (reportUnknownMemberType)

**To Reproduce**
1. 

**Expected behavior**
V4.7.0 should work fine with Pyright too, 

**Screenshots**

**Additional context**

**Comment by mccoyp** [comment]
Hi @zhouwangzw, thank you for opening an issue! I'll look into this and provide a response as soon as possible.

**Comment by mccoyp** [comment]
Thank you again, @zhouwangzw, for taking the time to bring this up with an issue! 🙂 I opened https://github.com/Azure/azure-sdk-for-python/issues/29482 to track `pyright` work for each Key Vault library in the SDK. I'll update this issue when `azure-keyvault-secrets` is addressed as part of that larger effort.
