### ISSUE TITLE
[azureml python sdk v2] access files in URI_FOLDER output after job has finished?

### ISSUE THREAD

**Issue by movingabout** [Azure/azure-sdk-for-python#29446]
I have a training job that persists some files in an URI_FOLDER output.
_How can I access those through the v2 SDK API after the job has finished?_

### 1. job setup
The output is set up like this in the `command`:
```
job = command(
    # ...
    outputs=dict(
        outputs=Output(type=AssetTypes.URI_FOLDER, mode='rw_mount'),
    ),
    command="python training_script.py " + 
            "--outputs_dir ${{outputs.outputs}} " +
            # ...other arguments...
)
```
This seems to work fine, the corresponding folder is mounted correctly and accessible in the training script.

### 2. training script
In the training script, I persist a dataframe like this:
```
parser.add_argument("--outputs_dir", dest="outputs_dir", default=DEFAULT_MODEL_DIR)
# ...
some_dataframe.to_csv(os.path.join(args.outputs_dir, 'some_dataframe.csv'), index=True)
```
This works fine.

### 3. resulting dataset
After the job has finished, the outputs are available as a dataset.
This is what is shown in Azure ML Studio in the "Overview" tab for job `ivory_octopus_yd6by49kxf`:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/876829/226120425-90dabf23-b0cd-488e-828c-fdaed1f24eb9.png">

The dataset is successfully stored in the `workspaceblobstore` datastore. I checked it in the Azure ML Studio and it looks fine.

### 4. accessing the persisted data
After the job has finished, I access the run using a `MlflowClient()`
```
MLFLOW_TRACKING_URI = ml_client.workspaces.get(name=ml_client.workspace_name).mlflow_tracking_uri
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
mlflow_client = MlflowClient()

mlflow_run = mlflow_client.get_run("ivory_octopus_yd6by49kxf")
```
or
```
run = ml_client.jobs.get('ivory_octopus_yd6by49kxf')
# returns NodeOutput class
```

**_How can I programmatically list / get / download the outputs connected to the job?_**

Thanks!

**Comment by mccoyp** [comment]
Hi @movingabout, thank you for opening an issue! I'll tag the appropriate team so we can get back to you as soon as possible. @azureml-github

**Comment by harneetvirk** [comment]
Could you try adding additional arguments in the download call.

Link to the SDK Reference documentation of job download: https://learn.microsoft.com/python/api/azure-ai-ml/azure.ai.ml.operations.joboperations?view=azure-python#azure-ai-ml-operations-joboperations-download


ml_client.jobs.download(my_job.name, **all=True**)
ml_client.jobs.download(my_job.name, **output_name='result_file'**)


![image](https://user-images.githubusercontent.com/20194110/226455912-be3d08be-3052-4400-a312-3c2053c7abdc.png)

**Comment by movingabout** [comment]
Thanks, that did it!
