### ISSUE TITLE
Add PyPy support 

### ISSUE THREAD

**Issue by auvipy** [Azure/azure-sdk-for-python#29449]
**Is your feature request related to a problem? Please describe.**
the package is currently breaking out CI with PyPy to build uamqp in kombu

**Describe the solution you'd like**
testing pypy in the CI will help to add support for it eventually

**Comment by mccoyp** [comment]
Hi @auvipy, thank you for opening an issue? Could I ask which Python SDK package(s) you're using in your scenario?

**Comment by mccoyp** [comment]
Thank you for the added details! I'll tag some folks who should be able to help, and we'll get back to you as soon as possible.

**Comment by auvipy** [comment]
I already made the CI work with cpython only. I'm not sure how many will use it with pypy so not a big issue for now from my end.

**Comment by kashifkhan** [comment]
@auvipy would you be interested in the beta ? Its all in python ( uamqp dependency is made optional ) and depending on how yall use it can an option

**Comment by auvipy** [comment]
beta can be tried, it is https://pypi.org/project/azure-servicebus/7.9.0b1/ right?

**Comment by auvipy** [comment]
I'm testing this https://github.com/celery/kombu/pull/1682

**Comment by kashifkhan** [comment]
@auvipy just checking in to see how things are going with the beta?

**Comment by auvipy** [comment]
with beta the CI was green. but after the stable release it was failing again showing uamp failures. so I put cpython only in the ci with latest release and CI is green

**Comment by kashifkhan** [comment]
@auvipy do you happen to have the failure messages with you ? That version of the beta should not have relied on uamqp at all , so would definitely want to investigate if something slipped by.
