### ISSUE TITLE
Cosmos Sample Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#29455]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/database_management_async.py#L46)
![Screenshot 2023-03-20 140205](https://user-images.githubusercontent.com/119990644/226259719-a376fe14-18bb-4a7d-afb8-ce77f91b47e1.png)

**Reason**:
CosmosClient.query_databases() takes 1 positional argument but 2 were given

**Suggestion**:
Update to
`
query_databases_response = client.query_databases(query={
        "query": "SELECT * FROM r WHERE r.id=@id",
        "parameters": [
            { "name":"@id", "value": id }
        ]
    })
`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/MultiMasterOperations/MultiMasterScenario.py#L30)
![image](https://user-images.githubusercontent.com/57166602/227938193-bdf41665-df77-4f8c-a106-dcf95c728875.png)

**Reason**:
Unsupported retry policy. Must be an azure.cosmos.ConnectionRetryPolicy, int, or urllib3.Retry

**Suggestion1**:
Add code
`
from azure.cosmos import ConnectionRetryPolicy
`

**Suggestion2**:
Add code
`
connection_policy.ConnectionRetryConfiguration = ConnectionRetryPolicy.no_retries()
`

@rohit-ganguly, @lmazuel, @kyle-patterson, @KrzysztofCwalina, @annatisch  for notification.

**Comment by simorenoh** [comment]
Thanks for pointing this out @ChenxiJiang333 - seems like all the samples under the MultiMasterOperations are due for a cleaning, going through them now!

**Comment by simorenoh** [comment]
Code snippets here are bound to be affected by changes: https://learn.microsoft.com/azure/cosmos-db/nosql/how-to-manage-conflicts?tabs=dotnetv2%2Capi-async%2Casync#create-custom-conflict-resolution-policy-lww-python

**Comment by ChenxiJiang333** [comment]
Sorry I made a mistake. A wrong position was given. The code mentioned in suggestion2 is better to be added here.
![Screenshot 2023-03-27 110724](https://user-images.githubusercontent.com/119990644/227831250-7800fde3-07c9-45e3-a012-41752f450340.png)
It's more likely I met this error when I trying to create the client, probably for the default ConnectionRetryConfiguration value in ConnectionPolicy was set to None. 
All other code works perfectly to me. @simorenoh

**Comment by ChenxiJiang333** [comment]
Thank you for the quick update. It works well. This issue will be closed.
