### ISSUE TITLE
[formrecognizer] Investigate failing tests

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#29450]
The following tests are failing in the live test pipeline: 
FAILED tests\test_dac_analyze_prebuilts.py::TestDACAnalyzePrebuilts::test_receipt_locale_error
FAILED tests\test_dac_analyze_prebuilts_async.py::TestDACAnalyzePrebuiltsAsync::test_receipt_locale_error
FAILED tests\test_logging.py::TestLogging::test_logging_info_dac_client
FAILED tests\test_logging.py::TestLogging::test_logging_info_dmac_client
FAILED tests\test_logging_async.py::TestLogging::test_logging_info_dac_client
FAILED tests\test_logging_async.py::TestLogging::test_logging_info_dmac_client

NOTES:
- The receipt locale tests seem to be failing because the error return has changed. Instead of getting an InvalidRequest back from the service, the error is returning a 404 Resource not found error. 
- Similar to the test above, the logging tests are also returning a 404 Resource not found error

**Comment by kristapratico** [comment]
Seems all endpoints are returning 404 in canary (it's not immediately apparent since we skip flaky tests for the rest). Will reach out to the service team on the channel.

**Comment by catalinaperalta** [comment]
Fix to the decorator was added in #29506 & #29416. The other failures were service related.
