### ISSUE TITLE
The startTime for query_items_change_feed() API seems to be missing in version 4.3.1

### ISSUE THREAD

**Issue by sxb075** [Azure/azure-sdk-for-python#29500]
The startTime in the query_items_change_feed() API will help in pulling the change feed incrementally.  The _COMMON_OPTIONS in _azure/cosmos/base.py doesn't have any option that signifies startTime.  If the mechanism to fetch change feed based on a startTime is different, or uses other options, can you please clarify?  This is for the pull model.

**Comment by mccoyp** [comment]
Hi @sxb075, thank you for opening an issue! I'll tag some folks who should be able to help, and we'll get back to you as soon as possible.

**Comment by simorenoh** [comment]
Hi @sxb075, thank you for using our SDK. For using our change feed methods, the option we expose to our users is through the method-specific option `is_start_from_beginning` - this will let you choose whether or not to start your change feed from the creation of the container or from the current time. This is also noted in the method description:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/30335873/226930105-db65f199-1116-493f-b00e-cdef0f45ebc6.png">

Hope this answers your question!

**Comment by sxb075** [comment]
@simorenoh if I specify is_start_from_beginning = False, and if there has been a change to the container/items in the past, will I receive said container/items in the change feed?  what I am trying to achieve, is that between a startTime in the past and the current time, what were the changes in the change feed?  Also, is there a way to tell if the all the items that belong to an _lsn are present in the change feed?  I was wondering if it would be possible to get partial transactions as a part of the pull method.

**Comment by sxb075** [comment]
Hi @simorenoh thanks for the reply. and the pointers.  I have gone through them.  I think there's a nuance that I'm trying to get to.  I want to use a startTime on the changeFeed that's in the past.  https://github.com/Azure/azure-webjobs-sdk-extensions/pull/691 seems to talk about it, but it's unclear how would I go about accessing this.  Are you saying that the python SDK doesn't support this?  Also, https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-processor?tabs=dotnet talks about a startTime in the past that can be set on the changeFeed.  but this seems to indicate that the dotNet package has it.  so I'd think that the underlying infrastructure does support a startTime in the past?  or please clarify, if I'm missing something.

**Comment by simorenoh** [comment]
@sxb075 Yep, I didn't realize .NET and Java SDKs support starting from a point in time, but in Python we currently only expose `start_from_beginning` or `start_from_current` (`start_from_beginning` flag set to false).

Like you said, perhaps the underlying API is prepared to receive something of the sort - but in the Python SDK we do not currently support it.

**Comment by sxb075** [comment]
hi @simorenoh sounds good.  any chance that the feature can be introduced?  I would really prefer to use python as opposed to java :)

also, I was wondering if there were a way to list all the partitionKeys ?  if the startTime were available, then I could spawn off multiple processes/threads on a per partitionKey/Container based on startTime to grab all the data, and I'd like to think that'd be pretty fast/efficient?   would like to mention that SQL Server has CDC (Change Data Capture) that allows to start grabbing data starting from an LSN (Log Sequence Number), and perhaps that'd be a great feature too?  sorry for loading all of this here.  please let me know if there's a separate thread that I sould create?

**Comment by simorenoh** [comment]
We do not have a way to list all the partition key values in your items.

And no worries, glad there's users asking for more features. What I would do in this case is create a new issue with a feature request for the Cosmos team explaining all of these change feed additions you'd like - this way the PM's can look at it as well. Thanks!

**Comment by sxb075** [comment]
thanks.  I've created the following feature requests.

https://github.com/Azure/azure-sdk-for-python/issues/29712
https://github.com/Azure/azure-sdk-for-python/issues/29711

I'm closing this issue given that the feature requests have been created.

**Comment by sxb075** [comment]
Feature requests have been created to address the missing requirements as reported in this issue, and after discussions with @simorenoh
