### ISSUE TITLE
cla.azure.com not working

### ISSUE THREAD

**Issue by hdost** [Azure/azure-sdk-for-python#2950]
I was not sure where this should go, but I figure the project which I'm interested in joining might work.

**Comment by lmazuel** [comment]
Hi @hdost 
I'm not sure I get what you mean exactly? Could you give me more context?
Thanks,

**Comment by hdost** [comment]
My apologies, the website,https://cla.azure.com/ is non-responsive. I was planning to review/ potentially sign. I don't know who actually has ownership of it (the website), but I figured someone like yourself might have a better idea of who to contact to get it back up and running.

If it helps I'm located out of the eastern US.

**Comment by lmazuel** [comment]
@dend is this blog post still accurate? Opinions?

**Comment by hdost** [comment]
It is also here: https://azure.github.io/guidelines/#cla

**Comment by tysonn** [comment]
When I check the CLA automation in the repo, it appears to be functioning as expected, it's now incorporated into the checks. The blog article is from 2014, we were using a different CLA system then.

**Comment by hdost** [comment]
Created https://github.com/Azure/azure.github.io/issues/58 since this new CLA process is not documented publicly. I as a person looking to sign this CLA have not found where this is.

**Comment by hdost** [comment]
@lmazuel Based on com information, it sounds as if the real issue is that the README should probably be updated in this project, and maybe others. As apparently azure.github.io is going away in favor of https://opensource.microsoft.com/
