### ISSUE TITLE
CosmosClient  Raise "Status code: 404" exception when create database 

### ISSUE THREAD

**Issue by tengfei86** [Azure/azure-sdk-for-python#29537]
- **azure.cosmos.CosmosClient**: 
- **4.3.1**: 
- **centos 7**:
- **Python 3.10.6**: 

**Describe the bug**
always raise "Status code: 404" exception  
it's weird!!!

**To Reproduce**
```python
client = CosmosClient("https://mongodb-tiger-esaosp.mongo.cosmos.azure.com:443/",credential=COSMOS_ACCOUNT_KEY,consistency_level='Session')
   #cosmos_db = client.get_database_client(DATABASENAME)
   #db_offer = cosmos_db.read_offer()
   database_name = "testDatabase"
   try:
           database = client.create_database(id=database_name)
   except exceptions.CosmosResourceExistsError:
           database = client.get_database_client(database=database_name)
```
**Expected behavior**
Create the database successfully 

**Screenshots**
![image](https://user-images.githubusercontent.com/524484/227158811-e477b9cd-b76c-413f-96c3-d6ed30798e2a.png)

**Additional context**

**Comment by kashifkhan** [comment]
Hi @tengfei86 , thank you for the feedback. We will investigate and get back to you asap.

**Comment by tengfei86** [comment]
@simorenoh 
i think there should me some misunderstandings.
i want to use cosmos client not just to create database, also i want to get the RU of exist database.

**Comment by simorenoh** [comment]
@tengfei86 from the information you shared in your image, you are using an account endpoint finishing in `mongo.cosmos.azure.com` - this is a MongoDB account and not an SQL API account, and as such cannot be used with our cosmos client.

If you'd like to use an SQL API account, here is a link showing how to get started: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-python-get-started?tabs=env-virtual%2Cazure-cli%2Cwindows

I am not a Mongo developer, and as such cannot help you out if you are trying to use Mongo. Please open another issue with Mongo in the title if you'd like to get help from a developer who can help you there. Thanks!

**Comment by tengfei86** [comment]
> 

Thank you ,this is very helpful for me
