### ISSUE TITLE
Subscriptions class does not return associated tags

### ISSUE THREAD

**Issue by tanjoht** [Azure/azure-sdk-for-python#29545]
- **Package Name**: azure-mgmt-resource
- **Package Version**:  22.0.0
- **Operating System**: mac
- **Python Version**: 3.10

**Describe the bug**
The subscriptions class in the azure-mgmt-resource module does not return the tags

**To Reproduce**
from azure.mgmt.resource.subscriptions import SubscriptionClient
from azure.identity import DefaultAzureCredential

subscriptionClient = SubscriptionClient(loginCredentials)
subscriptionObjectList = subscriptionClient.subscriptions.list()

for subscriptionObject in subscriptionObjectList:
    print(subscriptionObject)

{'additional_properties': {}, 'id': '/subscriptions/f5f8d7b7-8edf-xx', 'subscription_id': 'f5f8d7b7-8edf-4fd0-xx', 'display_name': 'Visual Studio Professional Subscription', 'tenant_id': '5d3e2773-e07f-xx', 'state': 'Enabled', 'subscription_policies': <azure.mgmt.resource.subscriptions.v2021_01_01.models._models_py3.SubscriptionPolicies object at 0x106f89c60>, 'authorization_source': 'RoleBased', 'managed_by_tenants': [], **_'tags': None_**}

**Expected behavior**
the tags property should list the tags associated with the subscription

**Screenshots**

**Additional context**

**Comment by tanjoht** [comment]
hi @msyyc any ideas?

It looks like the equivalent REST API is working (although it shows all tags to all resources under the subscription instead of just the subscription itself):

https://learn.microsoft.com/en-us/rest/api/resources/tags/list

**Comment by Wzb123456789** [comment]
Hi @tanjoht 
If you just want to retrieve subscription tags, please try the following code:
```python
from azure.mgmt.resource import ResourceManagementClient
resource_client = ResourceManagementClient(credentials, subscription)
resource_client.tags.list()
```
The SDK release is sometime behind the rest api release, the 'tags' feature has not been added into current azure-mgmt-resource SDK.

**Comment by Wzb123456789** [comment]
The SDK API does not have this function yet, you can find a way to get the tags you want from all the tags.

**Comment by kentnsw** [comment]
```python
# NOTE the SubscriptionClient in azure.mgmt.subscription won't work!
from azure.mgmt.resource import SubscriptionClient
```
