### ISSUE TITLE
[AzureML v2] - Unable to set schedule for compute start/stop 

### ISSUE THREAD

**Issue by jadhosn** [Azure/azure-sdk-for-python#29540]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.4.0
- **Operating System**: Ubuntu 20.04.5 LTS
- **Python Version**: 3.8.15

**Describe the bug**
Unable to schedule an AzureML compute instance to start/stop based on a trigger, following Azure's documentation

**To Reproduce**
```python
# create compute instance
from datetime import datetime
from azure.ai.ml.entities import ComputeInstance, NetworkSettings, IdentityConfiguration, ManagedIdentityConfiguration, ComputeSchedules, ComputeStartStopSchedule
from azure.ai.ml.entities import SetupScripts, ScriptReference

m_id = ManagedIdentityConfiguration(
    resource_id=f"/subscriptions/{args.NER_SUBSCRIPTION_ID}/resourcegroups/{args.NER_RESOURCE_GROUP}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{args.NER_MANAGED_IDENTITY_NAME}")
c_id = IdentityConfiguration(
    type="UserAssigned",
    user_assigned_identities=[m_id])
c_net = NetworkSettings(subnet=f"/subscriptions/{args.NER_SUBSCRIPTION_ID}/resourceGroups/{args.NER_SUBNET_RESOURCE_GROUP}/providers/Microsoft.Network/virtualNetworks/{args.NER_VNET_NAME}/subnets/{args.NER_SUBNET_NAME}")
creation_script = ScriptReference(path="path/to/my/startup/script/<XXXXXXX>.sh", timeout_minutes=15)


recurrence_trigger = RecurrenceTrigger(frequency="week", interval=1, schedule=RecurrencePattern(week_days=["Friday"], hours=15, minutes=[30]))
myschedule = ComputeStartStopSchedule(start_time=datetime.now(), time_zone=TimeZone.EASTERN_STANDARD_TIME, trigger=recurrence_trigger, action="start")
com_sch = ComputeSchedules(compute_start_stop=[myschedule])

my_compute = ComputeInstance(name="test-compute",
description="AzureML compute instance",
size="STANDARD_D2S_V3",
ssh_public_access_enabled=False,
network_settings=c_net,
identity=c_id,
idle_time_before_shutdown_minutes=90,
schedules=com_sch,
setup_scripts=SetupScripts(creation_script=creation_script),
enable_node_public_ip=False)

ml_client.compute.begin_create_or_update(my_compute)
```

Traceback
> HttpResponseError                         Traceback (most recent call last)
Cell In[26], line 30
     17 com_sch = ComputeSchedules(compute_start_stop=[myschedule])
     19 my_compute = ComputeInstance(name="XXXXXXXXXXX",
     20 description="AzureML compute instance",
     21 size="STANDARD_D2S_V3",
   (...)
     27 setup_scripts=SetupScripts(creation_script=creation_script),
     28 enable_node_public_ip=False)
---> 30 ml_client.compute.begin_create_or_update(my_compute)
File /anaconda/envs/ner_inferencing_env/lib/python3.8/site-packages/azure/core/tracing/decorator.py:78, in distributed_trace..decorator..wrapper_use_tracer(*args, **kwargs)
     76 span_impl_type = settings.tracing_implementation()
     77 if span_impl_type is None:
---> 78     return func(*args, **kwargs)
     80 # Merge span is parameter is set, but only if no explicit parent are passed
     81 if merge_span and not passed_in_parent:
File /anaconda/envs/ner_inferencing_env/lib/python3.8/site-packages/azure/ai/ml/operations/_compute_operations.py:131, in ComputeOperations.begin_create_or_update(self, compute)
    124 compute._set_full_subnet_name(
    125     self._operation_scope.subscription_id,
    126     self._operation_scope.resource_group_name,
    127 )
    129 compute_rest_obj = compute._to_rest_object()
...
  "environment": "XXXXXXXXXXXXXX",
  "location": "XXXXXXXXXXXXX",
  "time": "2023-03-23T14:16:08.5875286+00:00",
  "componentName": "machinelearningcompute"
}

**Expected behavior**
Compute created with a schedule

**Screenshots**
N/A

**Additional context**
N/A

@nthandeMS

**Comment by needuv** [comment]
Hi @jadhosn, could you please share the full HTTP error details?

**Comment by jadhosn** [comment]
> Hi @jadhosn, could you please share the full HTTP error details?

>Traceback (most recent call last):
  File "/home/azureuser/cloudfiles/code/Users/test.py", line 49, in <module>
    ml_client.compute.begin_create_or_update(my_compute)
  File "/anaconda/envs/ner_inferencing_env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/anaconda/envs/ner_inferencing_env/lib/python3.8/site-packages/azure/ai/ml/operations/_compute_operations.py", line 131, in begin_create_or_update
    poller = self._operation.begin_create_or_update(
  File "/anaconda/envs/ner_inferencing_env/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/anaconda/envs/ner_inferencing_env/lib/python3.8/site-packages/azure/ai/ml/_restclient/v2022_10_01_preview/operations/_compute_operations.py", line 803, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/anaconda/envs/ner_inferencing_env/lib/python3.8/site-packages/azure/ai/ml/_restclient/v2022_10_01_preview/operations/_compute_operations.py", line 738, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'If you specify a TimeZone, you must also specify the StartTime. Default TimeZone of UTC is auto adde'
Content: {
  "error": {
    "code": "UserError",
    "severity": null,
    "message": "If you specify a TimeZone, you must also specify the StartTime. Default TimeZone of UTC is auto added and can create this issue. Its recommended to have both StartTime and TimeZone added to your script.",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": null,
    "additionalInfo": null
  },
  "correlation": {
    "operation": "241aa96087307a7c17601d6be01b5028",
    "request": "a4123223888d9633"
  },
  "environment": "XXX",
  "location": "XXX",
  "time": "2023-03-24T18:15:52.6091264+00:00",
  "componentName": "machinelearningcompute"
}

**Comment by needuv** [comment]
We will need the request payload sent to the service to continue debugging. Could you add the following to your code:

```python
import sys 
import logging 
 # Create a logger for the 'azure' SDK 
logger = logging.getLogger('azure') 
logger.setLevel(logging.DEBUG) 
# Configure a console output 
handler = logging.StreamHandler(stream=sys.stdout) 
logger.addHandler(handler)
```

and when you create your `MLClient`, can you add the following?

```python
ml_client = MLClient(
    ...
    logging_enable=True
)
```

You should see a request body with the compute details in the log output in a `PUT` request to `https://management.azure.com...`. Would you be able to share the request body?

**Comment by jadhosn** [comment]
@needuv not on here, it contains my credentials and authentication token. Is there an email I can send this to? I already have a ticket open for this issue (TrackingID#2303230050002265)

**Comment by xiangyan99** [comment]
Close the issue and please use the ticket to track it.
