### ISSUE TITLE
Redeploy VM via py sdk

### ISSUE THREAD

**Issue by krunalmsft** [Azure/azure-sdk-for-python#29555]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
Add feature to redeploy via python sdk like C#, powershell

**Describe alternatives you've considered**
Powershell

**Additional context**
https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/redeploy-to-new-node-linux

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.compute.virtualmachineresource.redeploy?view=azure-dotnet#azure-resourcemanager-compute-virtualmachineresource-redeploy(azure-waituntil-system-threading-cancellationtoken)

**Comment by xiangyan99** [comment]
@krunalmsft Are you asking for a new feature? Could you give more details like which library are you using?

Thanks.

**Comment by krunalmsft** [comment]
By feature, asking for support from python sdk to perform Redeploy <https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.compute.virtualmachineresource.redeploy?view=azure-dotnet> operation like from azure .net sdk/powershell.

Currently Azure python sdk does support VM compute operations, but its is limited.

Krunal
________________________________

**Comment by msyyc** [comment]
Hi @Wzb123456789 Please try to write sample with reference of https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/redeploy-to-new-node-linux and https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/find_sdk/find_sdk_in_cli_command.md

**Comment by msyyc** [comment]
@krunalmsft hope this sample https://github.com/Azure-Samples/azure-samples-python-management/pull/133 could help you
