### ISSUE TITLE
Chunk size calculation logic errors in Azure Monitor ingestion

### ISSUE THREAD

**Issue by tfrederick74656** [Azure/azure-sdk-for-python#29563]
- **Package Name**: azure.monitor.ingestion
- **Package Version**: 1.0.0
- **Operating System**: Windows
- **Python Version**: 3.10.10

**Describe the bug**
The chunking functionality in [_helpers.py](https://github.com/Azure/azure-sdk-for-python/blob/azure-monitor-ingestion_1.0.0/sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py) has multiple logic errors related to event size calculation.

**Error 1**: The chunking functionality in [_helpers.py:30](https://github.com/Azure/azure-sdk-for-python/blob/azure-monitor-ingestion_1.0.0/sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py#L30) incorrectly calculates size based on a fixed 4 bytes per character: `size = len(json.dumps(log)) * CHAR_SIZE_BYTES`. As logs are ultimately encoded in UTF-8 (see [_helpers.py:48](https://github.com/Azure/azure-sdk-for-python/blob/azure-monitor-ingestion_1.0.0/sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py#L48)), the bytes-per-character is not fixed and will range from 1 to 4 bytes/character based on the characters in use. The assumption of 4 bytes/character has the effect of dramatically (4x) overstating the size of most logs with only plain ASCII content (1 byte/character). This results in a substantial increase in overhead and latency, as the resulting chunk size is often as little as 256KB of the 1MB limit, which equates to quadruple the number of requests/round-trips to ingest the same content.

In order to properly calculate sizing for UTF-8 encoded text, something like `size = len(json.dumps(log).encode('utf-8))` should be done to account for the variable byte/character ratio.

**Error 2**: The size calculation algorithm does not properly take into account the separators and opening/closing braces added in the final `json.dumps()` in [_helpers:48](https://github.com/Azure/azure-sdk-for-python/blob/azure-monitor-ingestion_1.0.0/sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py#L48).

Take the following three JSON events as an example: 
`{"name":"event1"}`, `{"name":"event2"}`, and `{"name":"event3"}`

If all three of these events are added to a single chunk, they will be packed as:
`[{"name":"event1"},{"name":"event2"},{"name":"event3"}]`

However, only the size of `{"name":"event1"}`, `{"name":"event2"}`, and `{"name":"event3"}` are taken into account in `_split_chunks()`. The `[`, `]`, and two separating `,` characters are added after the size calculation is performed. This can result in an oversize message when the raw events are close to or at the 1MB limit.

To address this:
- The size calculation in `_split_chunks()` should start with `chunk_size = len('[]'.encode('utf-8'))` to account for the opening/closing braces.
- Each event should check if a separator is needed and add the appropriate overhead. Since a separator is only added on the second event, something like this would provide proper calculation:
```
SEPARATOR_SIZE = len(','.encode('utf-8'))
overhead = SEPARATOR_SIZE if curr_chunk.count() else 0 # First event will not have a separator
size = len(json.dumps(log).encode('utf-8)) + overhead
```

**Comment by annatisch** [comment]
Thank you so much for this detailed analysis @tfrederick74656!
@pvaneck are you able to take a look?

**Comment by pvaneck** [comment]
Hey @tfrederick74656, thanks for the descriptive feedback! You are right, we definitely do not need to be multiplying each len by `CHAR_SIZE_BYTES`, and I will update the code accordingly. 

For the second problem, was this an issue you encountered when using the ingestion SDK? I think this is a valid concern, but since we are not uploading raw data and are sending gzip-compressed data, I think it's safe to disregard the brackets/commas in the count. The API service limit for compressed data is 1 MB, and since gzip does quite well at compressing JSON, we have a lot of room to work with. Generally after compression, we are well below the 1MB limit. 

One thing I've been meaning to investigate was the possibility of compressing on the fly so that we can make full use of the 1 MB after compression, but I haven't had a chance to look into it yet.

**Comment by tfrederick74656** [comment]
@pvaneck No problem, thanks for taking a look so quickly!

The second problem is definitely theoretical, I haven't encountered this in practice with the SDK. I'm migrating from a homebuilt client where we weren't compressing data and thus had to actually take that into account. Completely agree with you regarding gzip, that should leave plenty of headroom. 

Love the idea of doing on-the-fly compression. I had actually [mocked up some rough code](https://gist.github.com/tfrederick74656/a2d979705306f6804b5c50c9da263d8f) for this a few months ago that you're welcome to borrow from if it's helpful. Zlib isn't exactly great for doing streaming compression because you have to flush the compressor at regular intervals to determine the current compressed size. I took the approach of first compressing 1MB of raw text, then subtracting the resulting compressed size from 1MB to get _X_ bytes remaining, then compressing _X_ bytes of raw text, and so on and so forth, until all space is exhausted. It's a tradeoff of decreasing efficiency (since each subsequent block is smaller, yielding a lower compression ration) for a guarantee of never exceeding the max size and always compressing to an event boundary. I'm sure there's a better way to implement this, but it's still a great deal more space efficient than a single compression pass.
