### ISSUE TITLE
Fix azure-mgmt-monitor example code

### ISSUE THREAD

**Issue by legdba** [Azure/azure-sdk-for-python#29571]
- **Package Name**:  azure-mgmt-monitor
- **Package Version**: 5.0.1
- **Operating System**: Ubuntu 22.04.2 LTS
- **Python Version**: 3.10.6

**Describe the bug**
Sample code from documentation (https://learn.microsoft.com/en-us/python/api/overview/azure/monitoring?view=azure-python-previous&viewFallbackFrom=azure-python) does not work:

```shell
Traceback (most recent call last):
  File "./test", line 88, in <module>
    print("{} ({})".format(item.name.localized_value, item.unit.name))
AttributeError: 'str' object has no attribute 'name'
```

`item.unit.name` should be `item.unit`.

I also suggest updating the example to be a fully functional code, not just a snippet. As it is, it misses credentials.

**To Reproduce**
1. Run Azure sample code

**Expected behavior**
Executes and returns value.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by mccoyp** [comment]
Hi @legdba, thank you for opening an issue! I'll tag some folks who should be able to help and we'll get back to you as soon as possible.
