### ISSUE TITLE
Azure Semantic Search query_type='semantic' not found

### ISSUE THREAD

**Issue by Anirudh42** [Azure/azure-sdk-for-python#29589]
- **Package Name**:  azure-search-documents
- **Package Version**:  11.3.0
- **Operating System**: Windows
- **Python Version**: 3.9.13

**Describe the bug**
I am trying to use the 'semantic' capabilities of azure cognitive search through the Python SDK. I have followed all the file changes made here [#17690](https://github.com/Azure/azure-sdk-for-python/pull/17690) and tested the code exactly as mentioned in the sample_semantic_search.py file. But the following is the error I receive

```
Message: The request is invalid. Details: Requested value 'semantic' was not found
```

As per the documentation I executed the code `client.search(search_text="luxury", query_type="semantic", query_language="en-us"))`. For some reason it is not able to identify the keyword 'semantic'. I looked into the python source code files and found out that under the Enum Class QueryType there are only two values: 'simple' and 'full' but there is not 'semantic'

**To Reproduce**
1. Follow the sample_semantic_search.py file as shown here `sdk/search/azure-search-documents/samples/sample_semantic_search.py` in the github repository
2. Run the code to reproduce the same issue

**Expected behavior**
I expected it to fetch a list descriptions that were semantically similar to my query.

**Additional context**
I have already gone through all the documentation and finished the necessary setup in my azure portal. On another note I faced this similar issue with the `semanticConfiguration` parameter as well

**Comment by Anirudh42** [comment]
Hi @kashifkhan I ran the code you have provided and saw this error

 

`cannot import name 'SemanticConfiguration' from 'azure.search.documents.indexes.models'`

 

So I checked this file which has the `SemanticConfiguration` class imported

 

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/azure/search/documents/indexes/models/__init__.py

 

However in the version I have `11.3.0` I do not have this class in the same file.

 

I did do `pip install azure-search-documents --upgrade` and seems like `11.3.0` is the latest version however seems like the `main` branch is different from what is being fetched through `pip`

 

I could potentially copy all the code from the latest branch and do it but this would be a workaround. Please let me know the next steps. Thanks for the help in advance!

**Comment by xiangyan99** [comment]
Sorry @Anirudh42 . This feature is not GAed on the service side and we cannot make a stable library with this feature ready.

For now, the only way to use it is to install a preview version of azure-search-documents.

You can install it by pip install --pre.

Thanks.

**Comment by Anirudh42** [comment]
Ok understood @xiangyan99 . I will install the preview version and use it. I will close this issue for now. Thanks for the assistance. May I know what is the timeline for the release for this new feature?

**Comment by xiangyan99** [comment]
We know it has been in preview for a while. Unfortunately, there is no precise ETA yet. But the service team is currently working on it.

**Comment by Anirudh42** [comment]
Ok thanks for letting me know 🙂

**Comment by skeretna** [comment]
I installed the preview version

Name: azure-search-documents
Version: 11.4.0b3

**Still getting the same error:** 
ImportError: cannot import name 'SemanticConfiguration' from 'azure.search.documents.indexes.models' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/search/documents/indexes/models/__init__.py)
