### ISSUE TITLE
Feature that allows to always run the last/selected component

### ISSUE THREAD

**Issue by dss-nkraszewska** [Azure/azure-sdk-for-python#29596]
Hi. Is there any opportunity to create a pipeline where one (last or selected) of the components is always executed? No matter if the pipeline is failed or successful. I need to always run the last component of every pipeline and cannot find a solution that allows me to do that.

**Comment by kashifkhan** [comment]
Hi @dss-nkraszewska , can you please provide some additional details such as the library name, repro code, python version etc so that we can route to the appropriate team and assist.

**Comment by dss-nkraszewska** [comment]
Hi @kashifkhan, of course, I can :)
Library name: Azure Machine Python SDK v2
Repo code: https://github.com/Azure/azure-sdk-for-python - the repo where I created the ticket :)
Python version I'm using: 3.7.16

My question is how I can add a component to the Azure ML pipeline that is always executed - whether a pipeline is failed or successful. 
For example, my current Azure ML pipeline works like this:
A(passed) -> B(passed) -> C(failed) -> D(not executed, because C failed)

And I want it to execute like this:
A(passed) -> B(passed) -> C(failed) -> D(passed, executed although C was failed)

Thanks!

**Comment by dss-nkraszewska** [comment]
But my question is about the ability to use AzureML SDK v2 for creating a pipeline with one component that is always executed. I don't have any repo with this code and I don't have any errors/issues :) I created this ticket just to ask if there is a feature like that (or if there are plans to add it) because I cannot find it in the official documentation.

**Comment by wangchao1230** [comment]
Do you mean you want a node in pipeline that always schedule to run at the end of pipeline? 
Even if there is other failing node in pipeline.
It's like a finalize step of pipeline?

**Comment by dss-nkraszewska** [comment]
Hi @wangchao1230. Yes, exactly :)

**Comment by cloga** [comment]
@dss-nkraszewska 
Thanks for your feedback. We have this feature in our backlog now. The idea for this is 
- we will introduce initialize and finalize step in root pipeline job. 
- both of these two is option
- initialize will always run before all steps.
- finalize will always run after all steps, even there are some steps is failed.

But, unfortunately, we didn't have a clear ETA for this feature, will keep you update, thanks.

**Comment by dss-nkraszewska** [comment]
Thank you so much @cloga  :) Is there any known workaround that can be used until this feature will be available?

**Comment by cloga** [comment]
Hi @dss-nkraszewska ,

Unfortunately, seems there is no workaround now, especially, for the failed job case.

**Comment by achauhan-scc** [comment]
ask is not supported hence closing as design,
