### ISSUE TITLE
ACR: swagger inconsistencies 

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#29617]
I found a couple of minor inconsistencies in ACR swagger transformations that lead to public API differences. Would be great to align unless there are Python-specific reasons not to:
- [ ] `Annotations.created` is called `createdOn` in [.NET](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Content/OciAnnotations.cs#L14) and [JS](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/containerregistry/container-registry/swagger#rename-created-to-createdon-in-ociannotations). Java change is in progress.
- [ ] `OciManifest.config` based on arch board feedback should be renamed to `configuration`, here's an example in [NET repo](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/autorest.md?plain=1#L130)

The rest looks great!

**Comment by YalinLi0312** [comment]
Hi @lmolkova, in our latest apiview, we decided to not publish `Annotations`, `Descriptor` and `OCIManifest` in python sdk. So I think the inconsistencies are no longer an issue.
