### ISSUE TITLE
Unclosed client session error logs seen when using azure-identity library (CertificateCredential() API)

### ISSUE THREAD

**Issue by sangam007** [Azure/azure-sdk-for-python#29618]
- Packages:
azure-identity == 1.12.0
aiohttp == 3.8.1
- Operating System: Linux
- Python Version: 3.7

**Describe the bug**
When fetching the oauth token using CertificateCredential() API, I have the following output:

> base_events.py(18410):default_exception_handler:1619] Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7f7bd814c090>
> 
> base_events.py(18410):default_exception_handler:1619] Unclosed connector
> connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f7bf050cd00>, 7527336.779447736)]']
> connector: <aiohttp.connector.TCPConnector object at 0x7f7bd81665d0>

Even after calling the async close() api for the credential object, still see the same error logs.

Reference code:

>                 # Fetch Oauth token
>                 oauth_token = CertificateCredential(tenant_id, client_id, cert_path)
> 
>                 # Store OAuth Token
>                 TokenRefresh.oauth_token.set_oauth_token(oauth_token)
> 
>                 #close async credentials
>                 await oauth_token.close()
> 

**To Reproduce**

- Create CertificateCredential()

**Expected behavior**
Expected no errors.

**Comment by kashifkhan** [comment]
Thank you for the feedback @sangam007 . We will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
Could you help to try use `async with` and check if it still exists?

**Comment by sangam007** [comment]
I'm afraid `async with` can't be used as I cache the credential object (returned by CertificateCredential()) for 60 minutes. If `async with` is used the credential object would be deleted when it comes out of the `with` block. FYI, I have mentioned the reference code above.

**Comment by xiangyan99** [comment]
Did you have a chance to try it?

If `async with` works, we can dig into how to use it in your scenario.
