### ISSUE TITLE
Wrong IO base class used in isinstance check in azure-synapse-artifacts

### ISSUE THREAD

**Issue by neerajanil** [Azure/azure-sdk-for-python#29615]
- **Package Name**: azure-synapse-artifacts
- **Package Version**: 0.15.0
- **Operating System**: Windows
- **Python Version**: 3.8.10

**Describe the bug**
Some apis on the `azure-synapse-artifacts` library are using the `typing.IO` class instead of the `io.IOBase` in the isinstance check to detect IO classes. eg:- [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/synapse/azure-synapse-artifacts/azure/synapse/artifacts/operations/_pipeline_operations.py#L376-L379)
```
if isinstance(pipeline, (IO, bytes)):
    _content = pipeline
else:
    _json = self._serialize.body(pipeline, "PipelineResource")
```
This check fails for `TextIOWrapper`, `StringIO` etc. because those classes inherit from `io.IOBase` and not `typing.IO`

**To Reproduce**
1. Save a sample pipeline to a json file `sample_pipeline.json`
2. Try to create the pipeline using the following code:
    ```python
    from azure.synapse.artifacts import ArtifactsClient
    from azure.identity import DefaultAzureCredential

    credential = DefaultAzureCredential()
    ac = ArtifactsClient(credential, "<<Endpoint URL>>")
    with open("sample_pipeline.json") as pipeline_file:
        operation = ac.pipeline.begin_create_or_update_pipeline("SamplePipeline", pipeline_file)
        operation.wait()
        print(operation.result())

    ```
3. This results in the following exception:
```
(', DeserializationError: (", AttributeError: \'_io.TextIOWrapper\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'_io.TextIOWrapper\' object has no attribute \'get\'"))', 'Unable to build a model: (", AttributeError: \'_io.TextIOWrapper\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'_io.TextIOWrapper\' object has no attribute \'get\'"))', DeserializationError(", AttributeError: '_io.TextIOWrapper' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'_io.TextIOWrapper' object has no attribute 'get'")))
AttributeError: '_io.TextIOWrapper' object has no attribute 'get'
```
**Expected behavior**
IO classes should be detected correctly and should not fail with above exception

**Additional context**
Some sample code to test the hypothesis:
```python
from typing import IO
from io import StringIO, TextIOWrapper, IOBase


print(issubclass(TextIOWrapper, IO))  # This results in false
print(issubclass(TextIOWrapper, IOBase))  # this results in true
```

**Comment by kashifkhan** [comment]
Thank you for the feedback @neerajanil . We will investigate and get back to you asap.

**Comment by neerajanil** [comment]
While the bug is being looked at, I wanted to provide a workaround that I am using:
```python
from azure.synapse.artifacts import ArtifactsClient
from azure.identity import DefaultAzureCredential
from typing import IO
from io import StringIO

class __StreamWrapper(StringIO, IO):
    ...


credential = DefaultAzureCredential()
ac = ArtifactsClient(credential, "<<Endpoint URL>>")
with open("sample_pipeline.json") as pipeline_file:

    wrapped_pipeline_file = __StreamWrapper(pipeline_file.read())

    operation = ac.pipeline.begin_create_or_update_pipeline("SamplePipeline", wrapped_pipeline_file)
    operation.wait()
    print(operation.result())

```

**Comment by xiangyan99** [comment]
Thanks for your feedback.

begin_create_or_update_pipeline method looks for PipelineResource object.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/synapse/azure-synapse-artifacts/azure/synapse/artifacts/operations/_pipeline_operations.py#L423

**Comment by neerajanil** [comment]
> Thanks for your feedback.
> 
> begin_create_or_update_pipeline method looks for PipelineResource object.
> 
> https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/synapse/azure-synapse-artifacts/azure/synapse/artifacts/operations/_pipeline_operations.py#L423

There is a second overload to `begin_create_or_update_pipeline` which accepts `IO` objects 
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/synapse/azure-synapse-artifacts/azure/synapse/artifacts/operations/_pipeline_operations.py#L459

**Comment by iscai-msft** [comment]
yep, i will work on this today, thanks!

**Comment by iscai-msft** [comment]
i've made a pr to fix this on the code generation side: https://github.com/Azure/autorest.python/pull/1842

I should be able to do a release on Monday. Once that's out, we can regenerate and release a new azure-synapse-artifacts package cc @xiangyan99

**Comment by iscai-msft** [comment]
slight delay: the pr should be good to release tomorrow, @xiangyan99 i'll reach out to you when it's released. thanks for your patience!

**Comment by msyyc** [comment]
Hi @neerajanil I think we have resolved the problem. Could you try the private package to confirm that? Once it works as expected, we will merge https://github.com/Azure/azure-sdk-for-python/pull/30050 and release a new version.

**Comment by msyyc** [comment]
https://pypi.org/project/azure-synapse-artifacts/0.16.0/

**Comment by neerajanil** [comment]
@msyyc I can confirm that the fix is working. Thanks!
