### ISSUE TITLE
[ACR] containerregistry get_manifest_properties haven't deserialized related_artifacts manifests

### ISSUE THREAD

**Issue by wenli200133** [Azure/azure-sdk-for-python#29646]
- **Package Name**: azure-containerregistry
- **Package Version**: 1.1.0b2
- **Operating System**: Ubuntu-22.04
- **Python Version**: python 3.8

**Describe the bug**
containerregistry `get_manifest_properties` doesn't returned expected related artifacts manifests

**To Reproduce**
1.  New a client `ContainerRegistryClient` with azure account and registry endpoint
2. call function `get_manifest_properties` with parameter repository and digest which are already existed in the azure container registry
3. response of `get_manifest_properties` doesn't include the properties about related artifacts or manifests of that repository and digest.

**Expected behavior**

We expect that `get_manifest_properties` returned the related artifacts or manifests value of that repository and digest.
for example: 
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py#L410~L414

`ArtifactManifestProperties` class would also include the property of `related_artifacts` like class `class ManifestAttributesBase(_serialization.Model)` did in here https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/containerregistry/azure-containerregistry/azure/containerregistry/_generated/models/_models.py#L781

**Screenshots**

**Additional context**

**Comment by pvaneck** [comment]
Thanks for the feedback. I'll tag someone who can potentially assist.

**Comment by YalinLi0312** [comment]
Hi @wenli200133 , thanks for reaching out!

The `related_artifacts` is a list of [ArtifactManifestPlatform](https://github.com/YalinLi0312/azure-sdk-for-python/blob/8d049c884c38d0af1159730b8b164e5cd8b02212/sdk/containerregistry/azure-containerregistry/azure/containerregistry/_generated/models/_models.py#L284) type. You can get each property value from the return of `get_manifest_properties()`. 
If you want to get the manifest data itself, it's in another function call [download_manifest()](https://github.com/YalinLi0312/azure-sdk-for-python/blob/8d049c884c38d0af1159730b8b164e5cd8b02212/sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py#L955).

Please let me know if your question has been answered, thanks!
