### ISSUE TITLE
"Authorization header doesn't confirm to the required format." with resource_token SQL request

### ISSUE THREAD

**Issue by dylan-atura** [Azure/azure-sdk-for-python#29659]
- **Package Name**: azure-cosmos
- **Package Version**: 4.3.1
- **Operating System**: Windows 10
- **Python Version**: 3.11

**Describe the bug**
We are providing a resource_token to a 3rd party to have Read access to the cosmos DB. We cannot provide them with a master key as this wouldn't satisfy our security and compliance needs. Our client needs to execute a SELECT query to get all documents between two timestamps (property on the doc), in a daily batched process.

When using the resource_token for a call to get all documents in the collection it works, but when calling with an SQL query we get `b'{"code":"Unauthorized","message":"Authorization header doesn't confirm to the required format. Please verify and try again ..., Microsoft.Azure.Documents.Common/2.14.0"}''`

**To Reproduce**
Here is the code we have managed to reproduce the 3rd party issue with:
```
def generate_resource_token(endpoint_uri, primary_key, database_id, container_id, permission_mode):
    # Define endpoint and authorization parameters
    endpoint = endpoint_uri
    master_key = primary_key
    client = cosmos_client.CosmosClient(endpoint, credential={"masterKey": master_key})

    # Generate resource token
    database_link = 'dbs/' + database_id
    container_link = database_link + '/colls/' + container_id
    database_proxy = client.get_database_client(database_id)
    user = database_proxy.create_user(body={'id': 'testuser11'})
    permission_definition = {
        "id": "CONTAINER_ALL_PERMISSION",
        "permissionMode": permission_mode,
        "resource": container_link,
    }

    permission = create_permission_if_not_exists(user, permission_definition)
    token = {}
    token[container_link] = permission.properties["_token"]
    resource_token = token[container_link]

    return resource_token

def query_items(container, partition_key, res_token):
    print('\nQuerying for an  Item by Partition Key\n')
    options = {"enableCrossPartitionQuery": True, "partitionKey": partition_key,
               "Authorization": res_token}
    items = list(container.query_items(
        query="SELECT * FROM r WHERE r.partitionKey=@partition_key",
        parameters=[
            { "name":"@partition_key", "value": partition_key }
        ],
        partition_key="Eva",
        options=options
    ))
    print(json.dumps(items, indent=True))
```
   
With a main function that calls both of the above functions and all of the variables correctly set for database params and all function params.

We have also tried the Http call for the SQL query, despite the microsoft docs mentioning that that wasn't allowed with a resource_token.

In our production case we would provide the resource_token from an API, but neither that approach or the above case of getting the token in python using the master key seems to allow us to make the SQL query in python using the resource_token.

In this example we simplified the query for testing purposes.

**Expected behavior**
We want the SQL query to return the documents.

**Comment by pvaneck** [comment]
Thanks for the feedback, we'll investigate as soon as able. Tagging appropriate folks.

**Comment by dylan-atura** [comment]
Hi @simorenoh , thanks for the response.

To be honest the code I shared was just the latest iteration at the time. I've been through many testing out various possible solutions. Python is not our primary dev language, so I apologize if the code quality wasn't the greatest.

Just to summarise our use case again (which isn't directly covered by the samples). We are providing a 3rd party with a resource token via a .Net API. One question I do have is should the token we provide be url encoded or not? Initially we were encoding it, but I've removed that variable in debugging the issue.

We have tested with code that is very close to the sample code, but the token we get (as a string) needs to come from an API call. 

Here is a snippet of the updated code. We have simplified the query and made the cross partition param change you mentioned.

```
def query_items(container):
    print('\nQuerying for an  Item by Partition Key\n')

    items = list(container.query_items(
        query="SELECT * FROM r",

        partition_key="[Eva]",
        enable_cross_partition_query=False
    ))

    print(json.dumps(items, indent=True))
```

With the token coming from the external .Net API we have built (with no encoding and all permissions).

Here we create the container and call the query method:

```
    tokenString = urllib.parse.quote_plus(tokenString)
    token[CONTAINER_LINK] = tokenString
    consistency_level = "Session" #Had to add this in order to resolve a consistency error when querying
    token_client = cosmos_client.CosmosClient(HOST, token, consistency_level)
    token_db = token_client.get_database_client(DATABASE_ID)
    token_container = token_db.get_container_client(CONTAINER_ID)
    sql_return = query_items(token_container)
```
The `tokenString` above comes from the aforementioned API.

What we are not sure of is if there is an issue with the way the container is being created or the way that the container query is being used or if it's SDK related. The error messages are very obscure as to what is happening. We are still getting the "Authorization header doesn't confirm to the required format. Please verify and try again." error.

**Comment by simorenoh** [comment]
@dylan-atura Hope you're no longer having these issues - with that said, the fact that you were using the "Session" explicit consistency level option to get around the NoneType issue pointed out here https://github.com/Azure/azure-sdk-for-python/issues/27547 means that your resource token is not proper for authorization, and is actually failing to authenticate the client. You should now see authentication errors being surfaced properly for times like these.

In this case one thing I would recommend is to try using your actual credentials you are using to create the resource token to instead read the token from within the Python SDK using the `get_permission` method on the User proxy and then comparing it to the one you receive from .NET - if there's any inconsistencies there you know that there's an issue. Otherwise, the issue would lie with the permissions being given to the token, and I'd recommend looking into whether you're using the right ones - we have samples within the SDK that show how to use it.

**Comment by dylan-atura** [comment]
Thanks for the response @simorenoh . 

We will investigate your suggestion.

We just want to clarify that the scenario we are attempting is possible. (Some of it isn't via the REST API according to Microsoft documentation)

1. Create user token with read only permission in .Net appilication and provide to Python client via API
2. Retrieve token created in 1 in python application
3. Use retrieved token to make an SQL query against the Cosmos DB resource to get all items of a given type that have a certain value between two ranges

We just want to clarify that we aren't barking up the wrong tree with this functionality that we are trying to achieve and provide to a third party in a secure way.

**Comment by simorenoh** [comment]
Sounds good @dylan-atura, do let me know what the results of your investigation are.

**Comment by mohamed-atura** [comment]
Hi @simorenoh  

I'm @dylan-atura 's work colleague. 

We have tried your suggestion regarding comparing the token we receive from .NET to the token we obtained from the get_permission method in the Python SDK, and we noticed that they were not the same.

Moreover, we used the create_permission method in the Python SDK, and called the get_permission method thereafter and found the tokens were different. 

Here is a snippet of the code we implemented using the Python SDK which we have taken from the online Azure Github "access_cosmos_with_resource_token.py" sample

 `try:
        try:
            db = client.create_database(DATABASE_ID)
        except exceptions.CosmosResourceExistsError:
            db = client.get_database_client(DATABASE_ID)

        try:
            container = db.create_container(
                id=CONTAINER_ID, partition_key=PARTITION_KEY
            )
        except exceptions.CosmosResourceExistsError:
            container = db.get_container_client(CONTAINER_ID)

        user = create_user_if_not_exists(db, USERNAME)

        # Permission to perform operations on all items inside a container
        permission_definition = {
            "id": CONTAINER_ALL_PERMISSION,
            "permissionMode": documents.PermissionMode.All,
            "resource": container.container_link
        }

        permission = create_permission_if_not_exists(user, permission_definition)
        token = {}
        token[container.id] = permission.properties["_token"]

        # Use token to connect to database
        token_client = cosmos_client.CosmosClient(HOST, token)
        token_db = token_client.get_database_client(DATABASE_ID)
        token_container = token_db.get_container_client(CONTAINER_ID)

        # Query for items in a certain partition
        token_client_query(token_container, USERNAME)

    except exceptions.CosmosHttpResponseError as e:
        print("\nrun_sample has caught an error. {0}".format(e.message))`

The "create_permission_if_not_exists" method calls the "create_permissions" and if the permissions already exists, it calls the "get_permissions" method in the catch (as its shown in the azure github sample).

On the "token_client_query" method is where we keep getting the "Unauthorized: Authorization header doesn't confirm to the required format" error.

This is the snippet of the "token_client_query" method:

`def token_client_query(container, username):
    try:
        for item in container.query_items(
            query="SELECT * FROM my_container c WHERE c.username=@username",
            parameters=[{"name": "@username", "value": username}],
            partition_key=username,
        ):
            print(json.dumps(item, indent=True))
        print('\nQuerying for an  Item by Partition Key\n')

        print(json.dumps(items, indent=True))
    except exceptions.CosmosHttpResponseError as e:
        print("Error in querying item(s)")`
