### ISSUE TITLE
ServiceBusReceiver raises ServiceBusError instead of SessionLockLostError when trying to complete a message with an expired lock

### ISSUE THREAD

**Issue by IdoWSC** [Azure/azure-sdk-for-python#29667]
- **Package Name**:  azure-servicebus 
- **Package Version**: 7.8.1
- **Operating System**: Linux
- **Python Version**: 3.7.9

**Describe the bug**
ServiceBusReceiver raises ServiceBusError instead of SessionLockLostError when trying to complete a message with an expired lock

**To Reproduce**
1. put message on the servicebus
2. collect in with peek-lock mode
3. wait until the lock expires
4. try to complete the message
5. catch exception raise

**Expected behavior**
raise SessionLockLostError according to the [documentation](https://learn.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebusreceiver?view=azure-python#azure-servicebus-servicebusreceiver-complete-message).

The bug is clearly visible [here](https://github.com/Azure/azure-sdk-for-python/blob/d2092ee6eeac8d09d7365c158049a50eeddf372a/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py#L487). 

should be: 
```
if not self._session and message._lock_expired:
            raise SessionLockLostError(
                message="The lock on the message lock has expired.",
                error=message.auto_renew_error,
            )
```

**Screenshots**

**Additional context**
```

azure.servicebus.exceptions.ServiceBusError

The lock on the message lock has expired.

  File "/usr/local/lib/python3.8/site-packages/algotools/service/service_classes/message_service_abstract.py", line 82, in do_service
    self.complete_message()

  File "/usr/local/lib/python3.8/site-packages/algotools/service/service_classes/message_service_abstract.py", line 312, in complete_message
    self.message_manager.complete_message(self.message)

  File "/usr/local/lib/python3.8/site-packages/algotools/service/messages_manager/azure_servicebus_msg_receiver.py", line 66, in complete_message
    self.receiver.complete_message(message)

  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/_servicebus_receiver.py", line 853, in complete_message
    self._settle_message_with_retry(message, MESSAGE_COMPLETE)

  File "/usr/local/lib/python3.8/site-packages/azure/servicebus/_servicebus_receiver.py", line 490, in _settle_message_with_retry
    raise ServiceBusError(
```

**Comment by kashifkhan** [comment]
Thanks @IdoWSC . Ill take a look in to it, there is a comment right above that line where the generic error is being thrown due to a gap in features in the underlying protocol. Once I have a better understanding of whats happening Ill update this thread.
