### ISSUE TITLE
policy_client.policy_assignments.get_by_id throws an API error when executed

### ISSUE THREAD

**Issue by josvo** [Azure/azure-sdk-for-python#29669]
- **azure-mgmt-resource:**: 
- **22.0.0:**: 
- **Linux**:
- **3.11,3.10,3.9**: 

**Describe the bug**
`policy_client.policy_assignments.get_by_id()` does not work anymore and fails with the error:
```shell
An unexpected excetpion occured: (InvalidApiVersionParameter) The api-version '2021-06-01' is invalid. The supported versions are '2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

**To Reproduce**
Use this script as example:
```python
from azure.mgmt.resource.policy import PolicyClient
from azure.identity import DefaultAzureCredential

subscription_id = "Put-your-subscription-id-here"
policy_name = "Put-your-policy-name-here"

policy_client = PolicyClient(
    credential=DefaultAzureCredential(),
    subscription_id=subscription_id
)

policy_assignment_id = f"/subscriptions/{subscription_id}/providers/"
f"Microsoft.Authorization/policyAssignments/{policy_name}"
try:
  response = policy_client.policy_assignments.get_by_id(policy_assignment_id)
except Exception as exc:
    print(f"An unexpected exception occured: {exc}")
```

This used to work, however, I cannot find a working version of azure-managment-resources anymore. 
In _policy_client.py, the default API is defined as: `DEFAULT_API_VERSION = '2021-06-01'`

**Expected behavior**
Get a valid result for the `get_by_id`. It still works for `get`.

**Comment by pvaneck** [comment]
Thanks for the feedback. Let me loop in appropriate folks.

**Comment by SaurabhSharma-MSFT** [comment]
@josvo I do not see any issues getting the policy.
![image](https://user-images.githubusercontent.com/38112130/229930084-6667ff0e-7874-4fb0-a6b4-ee4d714f7edc.png)
Can you please try adding `\` to fstring and execute your script or try getting the without a fstring string formation.

**Comment by josvo** [comment]
I can't reproduce by running the exact same code. It is quite uncool that the Azure API shows a flaky behavior...
Feel free to close this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@josvo Thanks for the confirmation. We will now proceed to close this thread.
