### ISSUE TITLE
Unable to install IBM DB2 Azure Fending Agent - Failed dependencies python3-azure-sdk RHEL 8.6

### ISSUE THREAD

**Issue by johnem-msft** [Azure/azure-sdk-for-python#29675]
Currently unable to install fencing agent provided by IBM for DB2 fencing: 
https://www-01.ibm.com/marketing/iwm/platform/mrs/assets?source=mrs-db2pcmk&_ga=2.31425788.296289340.1604345966-344484498.1579133947

[azureadmin@RHEL86LVM2 ~]$ rpm -qp fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch.rpm --requires
/usr/libexec/platform-python
fence-agents-common = 4.7.1-3.el8.db2pcmk
python3-azure-sdk
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1

Repro:
====
Rsync or SCP files to RHEL 8.6 Marketplace VM within: Db2_Azure_fence_agent_4.7.1-3_noarch.tar (from above link)
    fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch.rpm
    fence-agents-common-4.7.1-3.el8.db2pcmk.noarch.rpm
     (Note: fence-agents-common-4.7.1-3.el8.db2pcmk.noarch.rpm installs fine after meeting libcurl dependency, only fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch.rpm is affected)

Error:
====
[azureadmin@RHEL86LVM2 ~]$ rpm -ihv fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch.rpm
error: Failed dependencies:
        python3-azure-sdk is needed by fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch

Attempts  dependency "python3-azure-sdk" via pip3 fail with Msg: 
sudo pip3 install azure
Starting with v5.0.0, the 'azure' meta-package is deprecated ...

Attempts to install dependencies via yum do not yield specific packages (we do not see python3-azure-sdk or python-azure-mgmt-compute or python-azure-identity in the repo)
-sudo yum search azure indicates only rhui-azure-rhel8-eus.noarch which is already installed (and grafana-azure-monitor which does not seem relevant here)

Per error msg/instructions: https://github.com/Azure/azure-sdk-for-python/issues/10646
-Installed many azure sdk packages via pip3 which did not satisfy the requirements:
 sudo pip3 install azure-mgmt-compute
 sudo pip3 install azure-mgmt-storage
 sudo pip3 install azure-mgmt-resource
 sudo pip3 install azure-keyvault-secrets
 sudo pip3 install azure-storage-blob
 sudo pip3 install azure-identity
-same error after installing all of these ^

[azureadmin@RHEL86LVM2 ~]$ rpm -ihv fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch.rpm
error: Failed dependencies:
        python3-azure-sdk is needed by fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch

-Installed version 4 all packges via: 
  sudo pip3 install azure==4.0.0  
  Installation finishes successfully, but the issue is still the same, the dependency is not met:

[azureadmin@RHEL86LVM2 ~]$ rpm -ihv fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch.rpm
error: Failed dependencies:
        python3-azure-sdk is needed by fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch

IBM documentation indicates only the following regarding the RPM package:
"It uses Azure SDK for Python" and yields no specific instructions:
https://www.ibm.com/support/pages/setting-two-node-db2-hadr-pacemaker-cluster-fencing-microsoft-azure
The choice of configuration should be based on your specific business requirements by taking recovery time and cost of implementation into account.  Fencing on Microsoft Azure is done via the fence_azure_arm agent. The fence_azure_arm is a Fencing agent for Azure Resource Manager. It uses Azure SDK for Python to connect to Azure.

The following documentation on msft learn does not appear to be specific to the requirements as DB2 with purescale is exclusively mentioned: https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/mainframe-rehosting/ibm/ibm-db2-purescale-azure 

Ask:
===
-What is the current proper method to install the Azure SDK on RHEL 8.6?
-As the RPM package provided in this example indicates that it's dependency is specifically "pyton3-azure-sdk" how do we get that installed?
If a combination of packages can be installed to meet the requirements via pip3 installation, is there a process to validate what that combination may be?

**Comment by pvaneck** [comment]
Hey, I'm not entirely sure who publishes/maintains the python3-azure-sdk rpm. What version and where is this package being pulled from? @lmazuel, do you know anything?

**Comment by xiangyan99** [comment]
@johnem-msft Thanks for reaching out. As showed in the error message. package azure is deprecated. In track 2, we separated it into different packages. Please choose the one you want. e.g. sudo pip3 install azure-mgmt-compute

**Comment by johnem-msft** [comment]
> @johnem-msft Thanks for reaching out. As showed in the error message. package azure is deprecated. In track 2, we separated it into different packages. Please choose the one you want. e.g. sudo pip3 install azure-mgmt-compute

Hello as mentioned in the original submission - the issue is the same after installing many packages including azure-mgmt-compute:
> Per error msg/instructions: #10646
> -Installed many azure sdk packages via pip3 which did not satisfy the requirements:
> sudo pip3 install azure-mgmt-compute
> sudo pip3 install azure-mgmt-storage
> sudo pip3 install azure-mgmt-resource
> sudo pip3 install azure-keyvault-secrets
> sudo pip3 install azure-storage-blob
> sudo pip3 install azure-identity
> -same error after installing all of these ^

Hence the asks remain the same here:
**If a combination of packages can be installed to meet the requirements via pip3 installation, is there a process to validate what that combination may be?**

Note: after installing: azure-mgmt-compute, azure-mgmt-storage, azure-mgmt-resource, azure-keyvault-secrets, azure-storage-blob,  install azure-identity we still do not meet the dependencies required by the RPM for "python3-azure-sdk" and the same error remains:
[azureadmin@RHEL86LVM2 ~]$ rpm -ihv fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch.rpm
error: Failed dependencies:
python3-azure-sdk is needed by fence-agents-azure-arm-4.7.1-3.el8.db2pcmk.noarch

**Comment by xiangyan99** [comment]
Took offline and closing.
