### ISSUE TITLE
(_ssl.c:997) Error

### ISSUE THREAD

**Issue by wxzassdsa** [Azure/azure-sdk-for-python#29684]
AzureCliCredential.get_token failed: ERROR: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /0a640576-a3d0-4bde-9983-25735cc5ff4e/oauth2/v2.0/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

The eventhub was good for a while. Then suddently I am encountering this error. Can someone helpe me with it?

**Comment by pvaneck** [comment]
This could potentially be a transient issue with the oauth2 service provider if it was working previously. Is this error consistent?

Can you also provide details about your environment (i.e. running locally or on cloud, operating system, python version, azure-identity version, azure-eventhub version, etc.)

**Comment by wxzassdsa** [comment]
@pvaneck 

Thank you for your response. 

It was working one month ago. Then I was working on other projects. It suddenly doesn't work. 

I am using az login and credential = AzureCliCredential() to use eventhub. Now I can do az login but it gaves me error here:
eventhub_consumer = EventHubConsumerClient(fully_qualified_namespace=consumer_eventhub_namespace,
                                           eventhub_name=consumer_eventhub_name,
                                           consumer_group=consumer_group,
                                           credential=credential)
.


Running locally,
Operating system: windows
python version: 3.7.13
azure-identity: 1.10.0
azure-eventhub: 5.9.0

Many thanks!!!!

**Comment by kashifkhan** [comment]
hi @wxzassdsa , as @pvaneck mentioned it looks like some sort of transient error that is happening causing connection drop outs. Its difficult to say however without some debug logs etc. Is the error happening all the time now ?

I do notice that your eventhub version is a little old, would be able to test with a newer version for both eventhub and identity ?

**Comment by kashifkhan** [comment]
@wxzassdsa are you able to share any debug logs? Have there been any recent changes in your environment or permissions that can be causing issues for identity not working?

Another thing to try and isolate the problem, can you try another language such as dotnet and connect to event hub ?
