### ISSUE TITLE
Create an e2e test for the FL node that uses it inside a @pipeline decorated method

### ISSUE THREAD

**Issue by garg-amit** [Azure/azure-sdk-for-python#29680]
**Is your feature request related to a problem? Please describe.**

The e2e test for the `azure-ai-ml` package is currently broken. It would be beneficial to have an e2e test for the FL node that uses it inside a @pipeline decorated method to execute the expected user behavior.

**Describe the solution you'd like**
Create an e2e test for the FL node that uses it inside a @pipeline decorated method.

**Comment by achauhan-scc** [comment]
closing as obsolete
