### ISSUE TITLE
Provide doc on deprecation of a package

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#29698]
The story is:
Change the classifier of the package from Stable or Beta to Inactive
Add a disclaimer at the beginning of the Readme to explain it's deprecated, and a link to migration guide if any

As PyPI does not allow direct update on the website, it has to be done with a release. If there are no code changes, we can do a post-release. For instance, if the latest release was 1.2.3, we release a 1.2.3.post1. This is a special system in Python that explains to PyPI that the changes are only in the metadata

technical guidance and how to achieve it, the PM has to do a PR to the azure-sdk-for-python (I can provide a template if that helps). Get the PR reviewed and merged. Trigger the release pipeline like their team have been doing for actual code release, and push the button at the end of the release pipeline to accept the release once the CI is green.

**Comment by mario-guerra** [comment]
Thanks Laurent. For consistency with our Deprecation Strategy wiki, please make sure the document clearly states that the deprecation message should be structured as follows:

The download page for each deprecated package on each package manager needs to be updated to include one of the following messages:

For packages with a differently named replacement:
_Please note, this package has been deprecated and will no longer be maintained after <EOLDate>. We encourage you to upgrade to the replacement package, <Replace>, to continue receiving updates. Refer to the migration guide (<ReplaceGuide>) for guidance on upgrading. Refer to our deprecation policy (https://aka.ms/azsdk/support-policies ) for more details._

For packages with the same name:
_Please note, this package has been deprecated and will no longer be maintained after <EOLDate>. We encourage you to upgrade to the latest version to continue receiving updates. Refer to the migration guide (<ReplaceGuilde>) for guidance on upgrading. Refer to our deprecation policy (https://aka.ms/azsdk/support-policies ) for more details._
