### ISSUE TITLE
replace **attahchmentType** with **contentType** in example code

### ISSUE THREAD

**Issue by harisharmamicro** [Azure/azure-sdk-for-python#29696]
[Enter feedback here]
In sample code of sending emails with attachment, replace **attahchmentType** with **contentType**
as attachmentType is not recognised by library and throws error that contentType is missing.

https://learn.microsoft.com/en-us/python/api/overview/azure/communication-email-readme?view=azure-python-preview
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72e24a83-f589-362e-3207-c9510bc58bc9
* Version Independent ID: 4f64ffdb-f36e-fa4d-4a03-431393b3c4c8
* Content: [Azure Communication Email client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/communication-email-readme?view=azure-python-preview)
* Content Source: [docs-ref-services/preview/communication-email-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/communication-email-readme.md)
* Service: **communication**
* GitHub Login: @acsdevx-msft
* Microsoft Alias: **acsdevx-msft**

**Comment by kashifkhan** [comment]
Thank you @harisharmamicro . We will investigate and get back to you asap. 

cc @turalf

**Comment by SaurabhSharma-MSFT** [comment]
@harisharmamicro The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
