### ISSUE TITLE
AWS Lambda import error

### ISSUE THREAD

**Issue by KostadinovicNikola** [Azure/azure-sdk-for-python#29742]
I have this error: **"errorMessage": "Unable to import module 'lambda_function': cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (unknown location)",**
When I'm trying to import _azure-storage-blob_ in my lambda function. 
To install my dependencies for AWS i used this method: `pip install --platform manylinux2017_aarch64 --target=. --implementation cp --python 3.9 --only-binary=:all: --upgrade azure-storage-blob`. But with _azure-storage-blob_ I had compatibility errors between _azure-storage-blob_ and _cryptography_. So I tried to do just `pip install` without specifying the platform, but then I have the error I stated above.

**Comment by tjprescott** [comment]
@jalauzon-msft can you please take a look at this issue?

**Comment by jalauzon-msft** [comment]
Hi @KostadinovicNikola Nikola, this looks like an issue with installing `cryptography` which is one of our dependencies. Moreover, it looks like there are some known issues around installing `cryptography` in AWS Lambda. See https://github.com/pyca/cryptography/issues/6481.

They link to some specific notes in their FAQ:
https://cryptography.io/en/latest/faq/#i-m-getting-errors-installing-or-importing-cryptography-on-aws-lambda
