### ISSUE TITLE
Unable to deserialize: Dataflow' object has no attribute 'lower'

### ISSUE THREAD

**Issue by aayushsin** [Azure/azure-sdk-for-python#29741]
- **azure.ai.ml.MLClinet**: 
- ** Azure Synpase**:
- **Python 3.10**: 

**Describe the bug**

SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'Dataflow' object has no attribute 'lower', DeserializationError: Unable to deserialize to object: type, AttributeError: 'Dataflow' object has no attribute 'lower

**To Reproduce**
1. Followed the steps on https://learn.microsoft.com/en-us/azure/machine-learning/how-to-configure-auto-train#configure-your-experiment-settings
2. Changed the dataset used from CSV
3. datastore = ws.get_default_datastore()
4. training_pd = training_data.toPandas().to_csv('training_pd.csv', index=False)
5. datastore.upload_files(files = ['training_pd.csv'],target_path = 'train-dataset/tabular/',overwrite = True,show_progress = True)
6. dataset_training = Dataset.Tabular.from_delimited_files(path = [(datastore, 'train-dataset/tabular/training_pd.csv')])
7. Error in returned_job = ml_client.jobs.create_or_update(
    classification_job
)  # 

**Expected behavior**
The training should start

**Comment by tjprescott** [comment]
@luigiw @azureml-github can you please take a look at this issue?

**Comment by achauhan-scc** [comment]
closing as obsolete
