### ISSUE TITLE
Azure Functions (Python V2 model) doesn't seem to support Session-based Service Bus Queue triggering

### ISSUE THREAD

**Issue by TDehaene** [Azure/azure-sdk-for-python#29761]
- **Package Name**: azure-functions
- **Package Version**: 1.13.3
- **Operating System**: WSL Ubuntu (in VSCode) and Windows 11
- **Python Version**: 3.10.4

**Describe the bug**
I'm trying to create a Azure Service Bus Queue - triggered function using the Python v2 programming model, but I'm running into a bug.

The error message is as follows:
```
[Error]   ReceiveBatchAsync Exception: System.InvalidOperationException: It is not possible for an entity that requires sessions to create a non-sessionful message receiver.
```

It works fine for a non-Session-aware Queue trigger, but it starts throwing the error if I make it Session-aware. I also can't seem to find any parameter for the decorator that would allow me to specify the Session-id.

**To Reproduce**

I'm mainly following the steps outlined in this article: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cin-process%2Cextensionv5&pivots=programming-language-python

The only difference being that the Queue I have created is Session-aware.

I'm trying to figure out how to specify the Session-id, but can't seem to find it back in the documentation, nor anywhere online.
![image](https://user-images.githubusercontent.com/22496343/230016364-96848187-6307-4409-8517-852feb5fb474.png)

**Expected behavior**
That I'm either able provide the Session-id as a decorator parameter, or that the functioning of the Queue-trigger for session-aware queues is agnostic, and can take in messages normally.

**Screenshots**
Full screenshot from the logstream:
![image](https://user-images.githubusercontent.com/22496343/230017194-6f302fcf-fa7c-45b8-ada6-e722165d8774.png)

**Comment by kashifkhan** [comment]
Hi @TDehaene , 

Thank you for the feedback. This repo is for the python client libraries and for azure functions youll have to head on over [here](https://github.com/Azure/Azure-Functions) and open a new issue on that repo.  They will be able to provide you with up to date information on the progress & state of the v2 model.

With that said, v2 is in preview and some things would be in flux as they approach GA. I would suggest looking in to the v1 model which does support session based queues using [configurations](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cin-process%2Cextensionv5&pivots=programming-language-python#configuration)
