### ISSUE TITLE
How to list all pipelines available in a workspace?

### ISSUE THREAD

**Issue by LukaszMilaszewski** [Azure/azure-sdk-for-python#29766]
Hi. I have a question about AzureML SDK v2. How can I list all available pipelines in my workspace? In SDK v1 my code looks like:
```
from azureml.core import Workspace, Pipeline
workspace = Workspace.from_config()
pipeline_list = Pipeline.list(workspace)
```
What about AzureML SDK v2? I cannot find any info in the official documentation. I'd appreciate your help.

**Comment by tjprescott** [comment]
@luigiw @azureml-github can you please answer @LukaszMilaszewski's question?

**Comment by cloga** [comment]
Hi @LukaszMilaszewski ,
In SDK v2, there no separate concept of pipeline any more, it is just one type of job, please use job interface to interact with them like:  https://learn.microsoft.com/en-us/cli/azure/ml/job?view=azure-cli-latest

**Comment by achauhan-scc** [comment]
Please use V2 as we are not taking any feature request in V1
