### ISSUE TITLE
Page is empty

### ISSUE THREAD

**Issue by akingscote** [Azure/azure-sdk-for-python#29764]
Page is empty

Im looking for an example of catching a downstream error, due to throttled requests
![image](https://user-images.githubusercontent.com/25075013/230053306-430e81ae-0e25-481d-87a5-8b8199d4303c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e481dd61-903a-d3aa-ccd3-68bf9029c846
* Version Independent ID: a48e6e01-8064-534f-b210-b7fd43338870
* Content: [azure.common.exceptions module](https://learn.microsoft.com/en-us/python/api/azure-common/azure.common.exceptions?view=azure-python)
* Content Source: [docs-ref-autogen/azure-common/azure.common.exceptions.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-common/azure.common.exceptions.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kashifkhan** [comment]
Hi @akingscote , `azure.common` has been [deprecated](https://azure.github.io/azure-sdk/releases/deprecated/python.html). As such youll find information about azure.core exceptions [here](https://learn.microsoft.com/en-us/python/api/azure-core/azure.core.exceptions?view=azure-python). Depending on the client library you are using there could be more focused errors that are pertinent and could help with the flow of activities etc.
