### ISSUE TITLE
Unable to install azure-mgmt-compute 3.0.0 on python3.5

### ISSUE THREAD

**Issue by dhawal1304** [Azure/azure-sdk-for-python#29779]
Trying to install azure-mgmt-compute 3.0.0 on python3.5 and getting the below error. I get that this is old version but we need this.

.2-py3-none-any.whl
Collecting cryptography>=1.1.0 (from adal<2.0.0,>=0.5.0->msrestazure~=0.4.11->azure-mgmt-compute==3.0.0)
  Using cached https://files.pythonhosted.org/packages/15/d9/c679e9eda76bfc0d60c9d7a4084ca52d0631d9f24ef04f818012f6d1282e/cryptography-40.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-8b6lvfd4/cryptography/setup.py", line 90
        print(f"    Python: {'.'.join(str(v) for v in sys.version_info[:3])}")
                                                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8b6lvfd4/cryptography
You are using pip version 7.1.2, however version 23.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@ktserver4 rpms]#

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Unfortunately, azure-mgmt-compute 3.0.0 is deprecated and we recommend to use newer versions.

If you don't mind, could you share the reason why you want to use this old version?

Thank you.

**Comment by dhawal1304** [comment]
Thanks @xiangyan99.

Yes we get that this is very old and unfortunately all our legacy code has been written with this version.  It would be very difficult for us, to change all of that in one go.  So if we have some workaround , till we re-write using new version it would help.

**Comment by xiangyan99** [comment]
Thanks for the information.

New versions of cryptography does not support py3.5.

Can you try install cryptography<4 before you start installing azure-mgmt-compute 3.0.0?

**Comment by dhawal1304** [comment]
We can close this , after installing all the dependencies which are supported , it works now.
