### ISSUE TITLE
azure.identity ManagedIdentityCredential doesn't allow to specify AuthorityHosts, preventing Azure Function Apps in China or Azure Gov to Authenticate using MSI

### ISSUE THREAD

**Issue by jocortems** [Azure/azure-sdk-for-python#29789]
- **Package Name**:  azure.identity ManagedIdentity
- **Package Version**: All
- **Operating System**: Azure Functions
- **Python Version**: 3.9

**Describe the bug**
[ManagedIdentitytCredential Class](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.managedidentitycredential?view=azure-python) doesn't expose a way to specify the Authority and it uses https://management.azure.com by default. The reason this is a problem is because Function Apps deployed in either Azure Gov or Azure China are unable to retrieve a token when using MSI (either system or user assigned)

**To Reproduce**
Create a function app that creates a credential using ManagedIdentity class and use that credential to authenticate to other Azure services. Deploy the function app in either Azure China or Azure gov. Following is a code sample:

```python
import json
import logging
import os
import azure.functions as func
import urllib3
from azure.identity import ManagedIdentityCredential
from azure.mgmt.resource import SubscriptionClient

def function_handler(event):
    func_client_id = event["func_client_id"]

    credentials = ManagedIdentityCredential(client_id=func_client_id) 
    subscription_client = SubscriptionClient(credentials, base_url='https://management.core.chinacloudapi.cn')
    subscription = next(subscription_client.subscriptions.list())
    subscription_id = subscription.subscription_id    
    
    return subscription_id


def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("HTTP Trigger Processed")
    
    event = {
        "func_client_id": os.environ["func_client_id"]
    }
    try:
      logging.info("Invoking Function Handler")
      cred = function_handler(event)
    except Exception as err:
      logging.exception(f"Error has occurred: {str(err)}")
      return func.HttpResponse(
        "Oops, something went wrong",
        status_code=500
    )
    return func.HttpResponse(
         body=json.dumps(cred),
         status_code=200,
         mimetype="application/json"
     )
```

**Expected behavior**
The function app successfully retrieves a token and is able to authenticate with other Azure services

**Screenshots**

**Additional context**
After adding a lot of instrumentation to debug the issue I could see that ManagedIdentity() is trying to retrieve a token for resource https://management.azure.com; there is no way to specify the endpoints for Azure China or Azure Government 

Subscription Client Object: 
{'_client': <azure.mgmt.core._pipeline_client.ARMPipelineClient object at 0x7fce4a43da60>,
 '_config': <azure.mgmt.resource.subscriptions._configuration.SubscriptionClientConfiguration object at 0x7fce4a43d6d0>,
 'profile': <KnownProfiles.default: <azure.profiles.DefaultProfile object at 0x7fce4a707bb0>>}
DEBUG:azure.core.pipeline.policies._universal:Request URL: 'http://169.254.130.5:8081/msi/token?api-version=2017-09-01&resource=https://management.azure.com&clientid=ba2xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
Request method: 'GET'
Request headers:
    'secret': '9edxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    'User-Agent': 'azsdk-python-identity/1.7.1 Python/3.9.16 (Linux-5.4.0-1098-azure-x86_64-with-glibc2.31)'
Request body:
This request has no body
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 500

**Comment by pvaneck** [comment]
I think you may also need to specify `credential_scopes` in the `SubscriptionClient` as it seems the default credential scope is `["https://management.azure.com/.default"]`.

```python
subscription_client = SubscriptionClient(
    credentials,
    base_url="https://management.core.chinacloudapi.cn",
    credential_scopes=["https://management.core.chinacloudapi.cn/.default"]
)
```

Can you try that out?

**Comment by jocortems** [comment]
Thanks for your prompt response @pvaneck . I tested with that argument and it is now working.
