### ISSUE TITLE
get 'none' of instance view when check VM os information with Microsoft Azure SDK for Python

### ISSUE THREAD

**Issue by Iristes** [Azure/azure-sdk-for-python#29793]
customer is using Azure SDK for Pythonto check vm os information.

![image](https://user-images.githubusercontent.com/130134616/230563074-e7fbb939-a42c-4a08-8b2c-070a34531eaf.png)

But he got 'none' of instance view as bellow:
![image](https://user-images.githubusercontent.com/130134616/230563249-004371f7-5114-48a7-8e91-839e85a62916.png)

Could help to figure out the reason?
Reference:
https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-compute-readme?view=azure-python

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Iristes** [comment]
Hi@SaurabhSharma-MSFT 《do you have any ideas about this?

**Comment by SaurabhSharma-MSFT** [comment]
@Iristes What specifically your customer is looking for. Values may be showing None's if your VM doesn't have those properties setup.  Please check the [REST API](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/get) if it is returning any properties which are not available as part of the `virtual_machines.get()` function.
