### ISSUE TITLE
Upload large files (40+ GB) from HTTP request to azure storage blob.

### ISSUE THREAD

**Issue by stevehizmi** [Azure/azure-sdk-for-python#29806]
- **azure_storage_blob version 12.14.1**: 
- **mac os**:
- **Python 3.9**: 

**Describe the bug**
Runtime exception occurs when I try to upload a large file (40+ GB) using azure functions timer trigger.

**To Reproduce**
container_client = ContainerClient.from_connection_string(
        os.environ["AzureWebJobsStorage"], "testenvironment", max_block_size=4 * 1024 * 1024 + 2, timeout=None)
    try:
        response = requests.get(url, stream=True)
        blob_name = get_filename(str(response.headers.get('content-disposition')))

        blob_client = container_client.get_blob_client(str(path) +str(blob_name))
        block_list = []
        for chunk in response.iter_content(chunk_size=1024*1024*4): 
            if chunk:
                blk_id = str(uuid.uuid4())
                blob_client.stage_block(block_id=blk_id, data=chunk)
                block_list.append(BlobBlock(block_id=blk_id))
        blob_client.commit_block_list(block_list)
    except Exception as e:
        logging.info(e)
* Replace 'url' with a url that downloads a large file (40+gb)*

**Expected behavior**
When the function is triggered it will behave as expected by uploading in chunks. However, when it gets to the 10 minute mark I receive a timeout exception.

**Additional context**
Uploading around 5gb works fine.

**Comment by kashifkhan** [comment]
Thank you for the feedback @stevehizmi . We will investigate and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @stevehizmi, could you share a little more details around the timeout error you get? (i.e. the actual exception and stack trace). Is it the call to `stage_block` that is timing out or is it perhaps your `requests.get` call timing out after 10 minutes (maybe its closed by the server hosting your other file)?

Assuming that it is the `stage_block` call and it's a client-side networking timeout, the timeout can be adjusted with the `connectin_timeout` keyword argument to client constructor. The is the client-side networking timeout for connecting to the server and has a default value of 20 seconds. This would mean you would have to upload the 4 MiB chunk in that 20 second window. Given the small chunk size, it seems unlikely you would hit a timeout here but perhaps there is network congestion or other factors that could cause this.

One other thing to consider: It looks like you are trying to copy some data from a website URL into a blob. Have you considered using the [Copy Blob from URL](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url?tabs=azure-ad) API? This can copy a blob from any website URL directly into a blob and the copy is handled server-side by the Storage service. In the Python SDK, this is done with the `BlobClient.start_copy_from_url` API. See [sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_copy_blob.py).

**Comment by stevehizmi** [comment]
Hi @jalauzon-msft, I was not aware of there being a copy from blob URL function in the Python SDK. I tried it out and I was able to do what I wanted. I uploaded about 33GB in file size that took about 30-40 minutes. It is a little long, however for my goals that is just fine (as long as its not something like 2+ hours). Thanks for the help I appreciate it! 

Side note: How can I set the the Request URL and Response Status logs to verbose rather than information? 
I tried `copied_blob.start_copy_from_url(source_blob, logging_body=False, logging_enable=False)` and that didn't seem to make a difference.

**Comment by jalauzon-msft** [comment]
Hi @stevehizmi, thanks for the information. I'm glad Copy Blob from URL can help in your scenario.

For setting the logging level, see [this section](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-logging#set-logging-levels) of the docs. This doc also contains a bunch more information about logging.
