### ISSUE TITLE
start_copy_from_url not working to for Archive blob

### ISSUE THREAD

**Issue by gopi9210** [Azure/azure-sdk-for-python#29838]
Hi Team,
           I am trying to copy Archive tier blob from one container to another container using the method start_copy_from_url(Sourceblob_url). If the blob is in Hot /Cold tier, the method is working fine. But if the source blob is Archive tier, I am getting the error "This operation is not permitted on an archived blob".

According to the microsoft documentation, even though we can't able to read Archive tier blob we can copy to some other container.

https://learn.microsoft.com/en-us/azure/storage/blobs/archive-rehydrate-to-online-tier?tabs=azure-portal
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-copy-python

python SDK : azure.storage.blob 

please let me know if i am missing something or this functionality is not implemented with python sdk.
Thanks in advance.
Regards,
Gopichand

**Comment by kashifkhan** [comment]
Thank you for the feedback @gopi9210 . We will investigate and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @gopi9210, does your destination blob you are copying into (the one you created your `BlobClient` for) already exist? If it does exist, what is its tier? I believe you can only rehydrate blobs when copying meaning you need to copy into a Blob that is either Hot or Cool tier.

If your destination does not already exist, perhaps you can try creating it first? I'm not too familiar with the archive/rehydration process but perhaps when rehydrating a blob, the destination needs to already exist so the service can know the tier?

**Comment by gopi9210** [comment]
Hi @jalauzon-msft , sorry for delayed response. Here i am trying to copy blob to different storage account. Within same storage account its working without any issues.

To copy into different storage account, i added SAS Toke at the end of url. Now Its working fine in this scenario also. Hence closing this issue.
Thanks for your support.
