### ISSUE TITLE
It seems can left credentials parameter empty while modify base_url to proxy server when construct azure SDK

### ISSUE THREAD

**Issue by shenshanyoumu** [Azure/azure-sdk-for-python#29856]
```py
from azure.mgmt.storage import StorageManagementClient
from azure.mgmt.containerservice import ContainerServiceClient

// proxy server maintain credentials that used to authenticate with azure, 
proxy_url="xxxxx"

subscription_id = "xxx"

storage_client = StorageManagementClient(credential="",subscription_id=subscription_id,base_url=proxy_url)
client = ContainerServiceClient(subscription_id=subscription_id,credential="",base_url=proxy_url)

storage_accounts = storage_client.storage_accounts.list()
print("storage_accounts",storage_accounts)

for account in storage_accounts:
    print(account.name)

for cluster in client.managed_clusters.list():
    print("Cluster name: {}".format(cluster.name))
    print("Kubernetes version: {}".format(cluster.kubernetes_version))
    print("Location: {}".format(cluster.location))
    print("Node count: {}".format(cluster.agent_pool_profiles[0].count))


```

above code snippet is working,  btw I thinks it's good for my scenarios. but I'm not sure why it works

**Comment by Wzb123456789** [comment]
Hi @shenshanyoumu thanks for your feedback!

What is the version number of the service you are using?

**Comment by shenshanyoumu** [comment]
@Wzb123456789 , for azure.mgmt.storage is 21.0.0

**Comment by msyyc** [comment]
`// proxy server maintain credentials that used to authenticate with azure`
Credential is to be used to authenticate rest api and according to your code and comment, it seems that your `proxy_url` doesn't need the authentication. Could you check your proxy server?

**Comment by shenshanyoumu** [comment]
> `// proxy server maintain credentials that used to authenticate with azure` Credential is to be used to authenticate rest api. According to your code and comment, it seems that your `proxy_url` doesn't need the authentication. Could you check your proxy server?

thanks for your reply, yes that's how proxy-server works. anyway I will check azure authenticate workflow in a deep way
