### ISSUE TITLE
[ServiceBus] receive_messages -- OperationTimeOutError

### ISSUE THREAD

**Issue by mattias-de-coninck-ad** [Azure/azure-sdk-for-python#29878]
- **Package Name**: azure-servicebus
- **Package Version**: 7.8.3
- **Operating System**: WSL Ubuntu
- **Python Version**: 3.8.10

**Describe the bug**
We have a session enabled Subscription that is going to be used in a competing consumer scenario. Session are paramount in order to ensure the order in which the messages are handled. Every time the subscription is empty the function **receive_messages** called via a ServicebusReceiver returns the following error:
`Exception has occurred: OperationTimeoutError
The operation did not complete within the allotted timeout of 00:01:05. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions . TrackingId:18150524-db3f-4d27-9a10-b1af3c8a4319_B10, SystemTracker:G18:278550257:receiver-link-609f91a0-56df-483b-b6ad-c01a267ef15d, Timestamp:2023-04-13T12:24:18 TrackingId:f0ea5fd9868649ffb7fbe7750799364b_G18, SystemTracker:gateway7, Timestamp:2023-04-13T12:24:18 Error condition: com.microsoft:timeout.
uamqp.errors.VendorLinkDetach: com.microsoft:timeout: The operation did not complete within the allotted timeout of 00:01:05. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions . TrackingId:18150524-db3f-4d27-9a10-b1af3c8a4319_B10, SystemTracker:G18:278550257:receiver-link-609f91a0-56df-483b-b6ad-c01a267ef15d, Timestamp:2023-04-13T12:24:18 TrackingId:f0ea5fd9868649ffb7fbe7750799364b_G18, SystemTracker:gateway7, Timestamp:2023-04-13T12:24:18`

Even when it is called with the following parameters `receive_messages(max_message_count=1, max_wait_time=1)`

**Expected behavior**
The receive_messages function should return an empty list when there are no more messages available.

**Comment by kashifkhan** [comment]
Hi @mattias-de-coninck-ad , thank you for the feedback. We will investigate and get back to you asap.

**Comment by kashifkhan** [comment]
just wanted to provide you with an update @mattias-de-coninck-ad . This is a bug and I'm able to see it on my side as well. I do have a follow up question, do yall see this even if session lock has not been lost ?

**Comment by mattias-de-coninck-ad** [comment]
@kashifkhan I pass a default AutoLockRenewer object to my receiver. Not sure if this is supposed to maintain a lock on the session for the default max_lock_renawal = 300 s. My receiver is instantiaded as shown below:
```python
renewer = AutoLockRenewer()
receiver = self.servicebus_client.get_subscription_receiver(
    topic_name=topic,
    subscription_name=subscription,
    session_id=NEXT_AVAILABLE_SESSION,
    max_wait_time=1,
    receive_mode=ServiceBusReceiveMode.PEEK_LOCK,
    auto_lock_renewer=renewer,
)
```

**Comment by mattias-de-coninck-ad** [comment]
@kashifkhan any updates on this?

**Comment by kashifkhan** [comment]
@mattias-de-coninck-ad  still working on this, we are making some changes to service bus for the upcoming release so trying to see where a fix would fit
