### ISSUE TITLE
Azure maps route directions doesn't include urban sectionType

### ISSUE THREAD

**Issue by Monaim1** [Azure/azure-sdk-for-python#29877]
Azure.maps.route 
Windows 10.
Python 3.10

i'm trying to use azure maps API to get route directions from an origin to a destination, but it seems that 'urban' sectionType is not a allowed value in the query countrary to what is specified in the documentation. also, i dont get the appropriate route sectionTypes, it is always specified as 'travel_mode'.

is it possible to know if a section is 'urban'?

import requests
import json

subscription_key = os.getenv("AZUREMapsKey")
api_endpoint = 'https://atlas.microsoft.com/route/directions/json'
# Define the start and end coordinates

start_coords = '40.74940921379206,-73.98601124103097'
end_coords = '38.90645807542766,-77.02840889289668'

query_params = {
    'api-version': '1.0',
    'subscription-key': subscription_key,
    'query': f'{start_coords}:{end_coords}',
    'travelMode': 'car',
    # 'computeBestOrder': True,
    'routeType': 'shortest',
    'sectionType': 'urban' #motorway
}

response = requests.get(api_endpoint, params= query_params)

**Comment by navba-MSFT** [comment]
@Monaim1 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Monaim1 Azure Maps Route Directions API provides various section types such as "highway", "toll road", "arterial", "local road", "street", "pedestrian", "ferry", "trail", "mountain bike", and "travel mode". However, "urban" is not a supported section type in Azure Maps.

To check if a section is urban or not, you can use other available attributes such as speed limit, road class, and road name. In general, urban areas have lower speed limits, more traffic lights, and more buildings and pedestrian traffic, while rural areas have higher speed limits and less traffic. Road classes also differ in urban and rural areas, with more minor roads in rural areas.

To get the section types in the response, you can check the "segmentType" attribute in the "routeLeg" object of the response. The "segmentType" attribute can have values such as "highway", "toll road", "arterial", "local road", "street", "pedestrian", "ferry", "trail", and "mountain bike".

Here is an example Python code using Azure Maps Route Directions API to get route directions and print the segment types:

```
import requests
import json

api_endpoint = "https://atlas.microsoft.com/route/directions/json"

subscription_key = "<your_subscription_key>"
start_coords = '40.74940921379206,-73.98601124103097'
end_coords = '38.90645807542766,-77.02840889289668'

query_params = {
    'api-version': '1.0',
    'subscription-key': subscription_key,
    'query': f'{start_coords}:{end_coords}',
    'travelMode': 'car',
    'routeType': 'shortest',
    'sectionType': 'highway'
}

response = requests.get(api_endpoint, params=query_params)

data = json.loads(response.text)

# Print the segment types
for leg in data["routes"][0]["legs"]:
    for segment in leg["segments"]:
        print(segment["segmentType"])

```

**Comment by Monaim1** [comment]
Thank you for your feedback.
is it possible to get these attributes ( speed limit, road class, and road name) in the same query without having to use the Traffic API?

**Comment by navba-MSFT** [comment]
@Monaim1 Thanks for getting back. AFAIK, Azure Maps Route Directions API should provide the speed limit and road class attributes in the response, in addition to the road name attribute.

The below sample code example that gets the speed limit, road class, and road name attributes in the response:

```
import requests
import json

api_endpoint = "https://atlas.microsoft.com/route/directions/json"

subscription_key = "<your_subscription_key>"
start_coords = '40.74940921379206,-73.98601124103097'
end_coords = '38.90645807542766,-77.02840889289668'

query_params = {
    'api-version': '1.0',
    'subscription-key': subscription_key,
    'query': f'{start_coords}:{end_coords}',
    'travelMode': 'car',
    'routeType': 'shortest',
    'sectionType': 'highway'
}

response = requests.get(api_endpoint, params=query_params)

data = json.loads(response.text)

# Print the speed limit, road class, and road name attributes
for leg in data["routes"][0]["legs"]:
    for segment in leg["segments"]:
        speed_limit = segment.get("speedLimit")
        road_class = segment.get("roadClass")
        road_names = segment.get("names", [])
        print(f"Speed limit: {speed_limit}, Road class: {road_class}, Road names: {road_names}")

```
Note that the above code example prints the speed limit, road class, and road name attributes for the "highway" sections of the route. You can change the "sectionType" parameter to any other supported section type to get the corresponding attributes.

**Comment by Monaim1** [comment]
**When i use the same query. i get a statusCode 400. 'highway' is also not supported** 

_response = {'error': {'code': '400 BadRequest',
  'message': 'Invalid sectionType value. Allowed value(s): carTrain, country, ferry, motorway, pedestrian, tollRoad, tollVignette, traffic, travelMode, tunnel'}}_
 
**and for the valid SectionTypes, we cannot retrieve these variables:
       speed_limit = segment.get("speedLimit")
        road_class = segment.get("roadClass")
        road_names = segment.get("names", []).**
        
 **Actually there is no attributes 'segments' in 'legs'.
 here's a sample 'leg' returned by the API:**

_{'summary': {'lengthInMeters': 366334,
  'travelTimeInSeconds': 13616,
  'trafficDelayInSeconds': 0,
  'trafficLengthInMeters': 0,
  'departureTime': '2023-04-19T07:56:00-04:00',
  'arrivalTime': '2023-04-19T11:42:55-04:00'},
 'points': [{'latitude': 40.74914, 'longitude': -73.98621},
  {'latitude': 40.74926, 'longitude': -73.9865},
  {'latitude': 40.74966, 'longitude': -73.98746},
  {'latitude': 40.74978, 'longitude': -73.98776},
  {'latitude': 40.74987, 'longitude': -73.98795},
  {'latitude': 40.74992, 'longitude': -73.98807},
  {'latitude': 40.75088, 'longitude': -73.99035},
  {'latitude': 40.75099, 'longitude': -73.99061}, 
...._

**Comment by navba-MSFT** [comment]
@Monaim1 I apologize for the confusion in my previous response and I deleted that comment to avoid further confusion.

Regarding the 400 error you are receiving when specifying "highway" or "urban" as the sectionType. As your rightly said, The sectionType parameter only supports the values of "carTrain", "country", "ferry", "motorway", "pedestrian", "tollRoad", "tollVignette", "traffic", "travelMode", and "tunnel". 

To answer your original question, No, the Azure Maps Route Directions API does not provide the speed limit or road class attributes in the response.

**Comment by navba-MSFT** [comment]
@Monaim1 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any follow-up queries on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Monaim1 I hope you had a chance to look at the above comment. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
