### ISSUE TITLE
Retrieve refresh token from Azure Credential

### ISSUE THREAD

**Issue by jinlow** [Azure/azure-sdk-for-python#29898]
**Is your feature request related to a problem? Please describe.**
I want a public method to be exposed to retrieve a refresh token from an azure credential object.  
I _think_ this is only valid with credentials such as `DeviceCodeCredential` and `InteractiveBrowserCredential`? But if this worked with other credential classes that would also be great.

**Describe the solution you'd like**
Once a token has been created, I would like that token object to have a `refresh_token` attribute, for example.
```python
from azure.identity import DeviceCodeCredential
credential = DeviceCodeCredential()
token = credential.get_token("https://storage.azure.com/.default")
token.refresh_token
```

**Describe alternatives you've considered**
Right now, I am able to retrieve the token in this hacky method, but it seems liable to break in the future.
```python
import json
from azure.identity import DeviceCodeCredential, TokenCachePersistenceOptions
cache_options = TokenCachePersistenceOptions(allow_unencrypted_storage=True)
credential = DeviceCodeCredential(cache_persistence_options=cache_options)
token = credential.get_token("https://storage.azure.com/.default")
j = json.loads(credential._cache.serialize())
refresh_token = list(j["RefreshToken"].values())[0]["secret"]
refresh_token
```

**Additional context**
I am using the refresh token in this refresh token flow, for connecting Spark to an azure datalake, [docs on this here](https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html#OAuth_2.0:_Refresh_Token).

**Comment by jinlow** [comment]
Hi @xiangyan99 , this seems to be a constraint by the [`hadoop-azure`](https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html#OAuth_2.0:_Refresh_Token) library. We are using this library for connecting spark to our azure datalake.
The refresh token flow is the only approach we have been able to get to work to connect spark to the datalake, there is no way I have been able to figure out how to make this connection using the access token.

**Comment by xiangyan99** [comment]
To help me understand better, do you want to access datalake from your spark pool managed by Azure?

**Comment by jinlow** [comment]
Correct, we have a spark cluster, running on an Azure VM. I need to connect that spark cluster to the azure Gen2 Datalake.
I am using the the [hadoop-azure](https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html#OAuth_2.0:_Refresh_Token) library to do this. From everything we have tried, in order to get this to work, we need to use a refresh token.

**Comment by xiangyan99** [comment]
@jinlow Thanks for providing the information.

I would recommend you talk to the owner of the [hadoop-azure](https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html#OAuth_2.0:_Refresh_Token) library to get some samples.

azure.identity does not have refresh token information for `DeviceCodeCredential` and `InteractiveBrowserCredential` and it is very risky to use refresh token directly.

**Comment by jinlow** [comment]
Hi @xiangyan99 Thank you for the input, I will look to reach out to that team.
However, I just wanted to clarify something, you said 
> azure.identity does not have refresh token information for `DeviceCodeCredential` and `InteractiveBrowserCredential`

However, from the example I shared originally, I am able to get the refresh token from the credential objects `._cache` attribute. So do you just mean it's not something publicly exposed?

**Comment by xiangyan99** [comment]
You can see the code https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py#L82.

azure-identity just provides the cache to msal and we don't actually use it.

In other words, we have no idea which information is stored in _cache and there is no guarantee that you can get the refresh_token information from _cache.

**Comment by jinlow** [comment]
@xiangyan99 Thanks, this makes sense. Appreciate all the info and prompt response, you have been very helpful!
I will close this issue.
