### ISSUE TITLE
azure-mgmt-resource check_existence_by_id Method Not Allowed

### ISSUE THREAD

**Issue by wymangr** [Azure/azure-sdk-for-python#29922]
- **Package Name**:  azure-mgnt-resource
- **Package Version**:  15.0.0 - 23.0.0
- **Operating System**: Linux
- **Python Version**: 3.8 & 3.11

**Describe the bug**
The check_existence_by_id method is using a HEAD request type when calling the Azure Management API, however that method is not supported and we are getting the following error when calling:

HttpResponseError: Operation returned an invalid status 'Method Not Allowed'

**To Reproduce**
pip install azure-mgmt-resource==23.0.0

python
(substituting <subscription_id> and <resource_id> 
```
>>> from azure.mgmt.resource import ResourceManagementClient
>>> from azure.identity import DefaultAzureCredential
>>> azure_credential = DefaultAzureCredential()
>>> SubscriptionId = '<subscription_id>'
>>> resource_client = ResourceManagementClient(azure_credential,SubscriptionId)
>>> api_version = '2019-07-01'
>>> resource = "<resource_id>"
>>> check = resource_client.resources.check_existence_by_id(resource, api_version)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 10711, in check_existence_by_id
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Method Not Allowed'
```

**Expected behavior**
Boolean response from method

**Screenshots**

**Additional context**
I have tried this on all versions of azure-mgnt-resource between 15.0.0 and 23.0.0. I have also tried changing the method in `build_resources_check_existence_by_id_request` to `GET` and got a 200 response, however that method is not looking for a 200 response, so it's still throwing an error:

```
  10709 if response.status_code not in [204, 404]:
  10710     map_error(status_code=response.status_code, response=response, error_map=error_map)
> 10711     raise HttpResponseError(response=response, error_format=ARMErrorFormat)
  10713 if cls:
  10714     return cls(pipeline_response, None, {})

HttpResponseError: Operation returned an invalid status 'OK'
Content: {
  "name": "<resource_name>",
  "id": "<resource_id>",
  "type": "Microsoft.Compute/snapshots",
  "location": "eastus2",
  "sku": {
    "name": "Standard_LRS",
    "tier": "Standard"
  },
  "properties": {
    "creationData": {
      "createOption": "Copy",
      "sourceResourceId": "<resource_id>",
      "sourceUniqueId": "<id>"
    },
    "diskSizeGB": 128,
    "encryption": {
      "type": "EncryptionAtRestWithPlatformKey"
    },
    "incremental": false,
    "timeCreated": "2022-04-11T04:33:29.8627096+00:00",
    "provisioningState": "Succeeded",
    "diskState": "Unattached",
    "diskSizeBytes": 137438953472,
    "uniqueId": "<id>"
  }
}

```

This also impacts the `check_existence` method.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
@wymangr Sorry for the confusion.

Yes. It is owned by Microsoft too.

What @SaurabhSharma-MSFT meant was this package was generated based on the swagger file which describes the RestAPI and unfortunately for this method, the swagger is wrong.

Please open an issue in repo https://github.com/Azure/azure-rest-api-specs.

That is the source that this SDK comes from.

**Comment by wymangr** [comment]
@xiangyan99 Thanks for the clarification. I'll open another issue.

**Comment by SaurabhSharma-MSFT** [comment]
@wymangr sorry, if I have not provided a clear context. yes, it is owned by Micrsoft as well and as per earlier internal discussion with the team this could be a limitation of the rest api and I have started an internal conversation with the product team as well.  However, please feel free to open an issue in at https://github.com/Azure/azure-rest-api-specs.  Sorry for your trouble.

**Comment by wymangr** [comment]
I've opened the following issue under the auzre-rest-api-specs repo. Feel free to add any other needed details.

https://github.com/Azure/azure-rest-api-specs/issues/23675

**Comment by wymangr** [comment]
If anyone else runs into this issue, this is what I used to get around it:

```
from azure.identity import DefaultAzureCredential
import requests 

def resource_exists(resource_id):
    
    headers = {'Authorization': f'Bearer {azure_credential.get_token("https://management.azure.com/.default").token}'}
    management_api_url = f"https://management.azure.com{resource_id}?api-version=2021-12-01"
    r = requests.get(management_api_url, headers=headers)
    if r.status_code == 200:
        return True
    return False
    

azure_credential = DefaultAzureCredential()
resource_id = <resource_id>

resource_exists(resource_id)
 ```
