### ISSUE TITLE
ResourceNotFoundError: (404) Resource not Found 

### ISSUE THREAD

**Issue by RAravindDS** [Azure/azure-sdk-for-python#29938]
Your new release 3.3.0.b1 has some issue with the version. Can you please check what is the problem. 

This is the error: 
ResourceNotFoundError: (404) Resource not found 
code;: 404 
Message: Resource not Found

**Comment by kashifkhan** [comment]
Hi @RAravindDS , can you provide some information about the package that you are using, python version, some sample code to reproduce the error etc so that we can better assist you ?
