### ISSUE TITLE
'utf-8' codec can't decode byte 0x9a in position 61: invalid start byte

### ISSUE THREAD

**Issue by BeyondEvil** [Azure/azure-sdk-for-python#29944]
- **Package Name**: azure-servicebus
- **Package Version**: 7.9.0
- **Operating System**: WSL2 (Ubuntu 22.04) on Windows 10
- **Python Version**: 3.10.6

**Describe the bug**
This [example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/async_samples/receive_queue_async.py) fails with:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 61: invalid start byte
```

**To Reproduce**
1. Use the example code to connect to a Service Bus Queue using a connection string.
2. Have a Service Hooks integration where `Work item updated` events are put on the queue.
3. Fetch messages and try to print them in the loop.

**Expected behavior**
Message should be printed.

**Comment by BeyondEvil** [comment]
This prints:

```python
  print("type: ", type(msg))
  print("body: ", msg.body)
  print("body type: ", msg.body_type)
  print("session id: ", msg.session_id)
  print("message: ", msg.message)
  print("raw: ", msg.raw_amqp_message)
```

Generate:

```
type:  <class 'azure.servicebus._common.message.ServiceBusReceivedMessage'>
body:  <generator object DataBody.data at 0x7f5ad1e4e030>
body type:  AmqpMessageBodyType.DATA
session id:  None
message:  'utf-8' codec can't decode byte 0x9a in position 61: invalid start byte
```

`raw_amqp_message` gives the same error.

**Comment by BeyondEvil** [comment]
```python
for b in msg.body:
    print("b: ", b)
```

Gives:

```
b:  b'@\x06string\x083http://schemas.microsoft.com/2003/10/Serialization/\x9a\xe2\x02{"id":"48167c35-dc4d-42c1-ae0f-4285f85a0c43","eventType":"workitem.updated","publisherId":"tfs","message":null,"detailedMessage":null,"resource":{"id":114,"url":"https://co.visualstudio.com/aed57e45-b69e-4d78-b8c2-312c3c5fc6a3/_apis/wit/workItems/385/updates/114","workItemId":385},"resourceVersion":"5.1-preview.3","resourceContainers":{"collection":{"id":"cc8322e0-5d0a-4c37-87a6-f99e62feaff7","baseUrl":"https://co.visualstudio.com/"},"account":{"id":"5c635985-ba80-49e9-a2ca-c2f46cf8caf5","baseUrl":"https://co.visualstudio.com/"},"project":{"id":"aed57e45-b69e-4d78-b8c2-312c3c5fc6a3","baseUrl":"https://co.visualstudio.com/"}},"createdDate":"2023-04-18T14:48:31.2024052Z"}\x01'
```

**Comment by kashifkhan** [comment]
Hi @BeyondEvil, thank you for the issue and the resolution itself 🙂. Ill add this as an item in our troubleshooting guide.

**Comment by rr-peter** [comment]
@kashifkhan is there any workaround if we cannot change  serialisation on sender's side? In our case most of consumers are using .net and it seems to be able to deserialise it properly but when we are using python SDK we hit this issue. 
Thanks

**Comment by BeyondEvil** [comment]
Maybe this can help: https://stackoverflow.com/questions/14251765/is-there-a-way-to-read-c-sharp-serialized-objects-into-python#14252132
