### ISSUE TITLE
Create virtual machine with image from a different tenant

### ISSUE THREAD

**Issue by BarVaserman** [Azure/azure-sdk-for-python#29962]
- **Package Name**:  azure.mgmt.compute
- **Package Version**:   29.0.0
- **Operating System**: macOS
- **Python Version**:  3.9

**Describe the bug**
I want to be able to create a virtual machine in target subscription (inside target tenant), from an image inside source subscription (inside source tenant).

I found this one - https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/share-images-across-tenants#create-the-app-registration
That describes how to do so with azure CLI, and everything works, but I don't find the way to do it with the python-sdk.  

I got: 
```
.... 
however the current tenant 'XXX is not authorized to access linked subscription 'XXX'.
```

**To Reproduce**
```python
source_creds = ClientSecretCredential(SOURCE_TENANT, c.app_id, c.secret)
target_creds = ClientSecretCredential(TARGET_TENANT, c.app_id, c.secret)

creds = ChainedTokenCredential(source_creds, target_creds)

client = ComputeManagementClient(creds, "target-subscription")

self.client.virtual_machines.begin_create_or_update({
..
"storage_profile": {
                "image_reference": {"id": image_id_from_target_subscription_gallery},
                }
..
})

```
**Expected behavior**
Create a VM in my target subscription, using the image provided inside the source subscription. 

**Screenshots**
No screenshots

**Additional context**

**Comment by SaurabhSharma-MSFT** [comment]
@BarVaserman We are looking into it and get back to you for any additional information.

**Comment by msyyc** [comment]
Hi @BarVaserman Please refer to https://github.com/Azure-Samples/azure-samples-python-management/pull/134.
nit: make sure install `azure-mgmt-core>=1.4.0`
