### ISSUE TITLE
Authenticating to Eventhub from python sdk using Workload identity federation for AKS in azure

### ISSUE THREAD

**Issue by prashansag62** [Azure/azure-sdk-for-python#29981]
I am using python sdk for EventHub, currently I am authenticating using connection strings, but I would have to change to some better way. 

I have enabled workload identity on my aks cluster, I, therefore want to make use of workload identity deferated credentials to authenticate to EventHub. On EventHub, I have added sender access policies to aad application associated with aks cluster federated credentials. 

In the code, I am making use of async defaultcredential to authenticate to EventHub via workload identity. 

Importing this :
```
from azure.identity.aio import DefaultAzureCredential as AsyncDefaultAzureCredential

def get_async_credential(self):
        try:
            credential = AsyncDefaultAzureCredential()
            self._logger.info("Async Credential fetched from Azure Auth successfully")
            return credential
        except Exception as ex:
            self._logger.critical("Exception in fetching async credential from Azure Auth: {}".format(str(ex)))
            raise ex
```

    async def get_writer_client(self):
        try:
            self._logger.info("Creating Eventhub Producer Client")
            self._auth = AzureAuth()
            credential = self._auth.get_async_credential()
            event_hub_producer = EventHubProducerClient(
                credential=credential,
                fully_qualified_namespace=self._event_hub_fully_qualified_namespace,
                eventhub_name=self._event_hub_name,
                buffered_mode=self._event_hub_buffered_mode,
                on_error=self.on_error,
                on_success=self.on_success,
                max_buffer_length=10000)
            self._logger.info("Eventhub Producer Client created successfully")
            return event_hub_producer
        except Exception as e:
            self._logger.exception("Event Hub Producer Client creation error:{} ".format(str(e)))

But I am getting following error :
```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
ManagedIdentityCredential: cannot schedule new futures after interpreter shutdown
```

Please let me know whats wrong am I doing here.

**Comment by xiangyan99** [comment]
@prashansag62 Thanks for reaching out.

@kashifkhan For the error message "cannot schedule new futures after interpreter shutdown", does this come from eventhub?

**Comment by kashifkhan** [comment]
@xiangyan99 that message is not one that eventhub raises.

**Comment by xiangyan99** [comment]
@prashansag62 does this help? https://stackoverflow.com/questions/67419800/error-cannot-schedule-new-futures-after-interpreter-shutdown-while-working-thr

**Comment by prashansag62** [comment]
@xiangyan99 @kashifkhan , this message is given by threadpoolexecutor package, I am in my code no where making use of this. However, on digging deep, I can see eventhub sdk making use of threadpool executor library, which might be causing this. 

We are making use of workload identity for authenticating to keyvault client in the same code, that is working properly, however when doing same with eventhub it is breaking up :(

**Comment by kashifkhan** [comment]
@prashansag62 it sounds like something is blocking the client from reaching out. Make sure you follow the steps [here](https://learn.microsoft.com/en-us/azure/event-hubs/troubleshooting-guide) in terms of firewall settings etc to make sure there is nothing blocking an outbound connection.

**Comment by prashansag62** [comment]
It is resolved now :) Thanks a lot for helping on this. Keeping the main thread alive worked !
