### ISSUE TITLE
mgmt-sqlvirtualmachine don't work with DefaultAzureCredential()

### ISSUE THREAD

**Issue by bejgli** [Azure/azure-sdk-for-python#29988]
- **Package Name**: azure-mgmt-sqlvirtualmachine
- **Package Version**: 0.5.0
- **Operating System**: Windows 10 and Fedora 37
- **Python Version**: 3.11.2

**Describe the bug**
The package can't use DefaultAzureCredential() logged in with az-cli. If trying to run the way it's shown in the examples it's raising an exception.
AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'

Other clients like ComputeManagementClient, ResourceManagementClient and NetworkManagementClient work with this authentication.

**To Reproduce**
1. Log in with 'az login'
2. Run code shown below
```
from azure.identity import DefaultAzureCredential
from azure.mgmt.sqlvirtualmachine import SqlVirtualMachineManagementClient

client = SqlVirtualMachineManagementClient(
        credentials=DefaultAzureCredential(),
        subscription_id="MY_AZ_SUBSCRIPTION",
   )

response = client.sql_virtual_machines.list()
    for item in response:
        print(item)
```

**Expected behavior**
List sql virtual machines from subscription.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Yes. azure-mgmt-sqlvirtualmachine 0.5.0 does not work with azure-identity library.

Please use the latest one 1.0.0b5 instead.
