### ISSUE TITLE
Wrong reference to Microsoft Graph Python SDK

### ISSUE THREAD

**Issue by isvargasmsft** [Azure/azure-sdk-for-python#29998]
Hello @lmazuel, 

In this article (https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/graphrbac/azure-graphrbac#readme) the link to the Microsoft Graph Python SDK is pointing to the core library. Could you please correct the link to use https://github.com/microsoftgraph/msgraph-sdk-python instead?

![image](https://user-images.githubusercontent.com/70350956/233457399-5a04281e-0392-45f6-a1cd-a157c9bc586e.png)

**Comment by isvargasmsft** [comment]
I tried to create a PR myself but it failed.

**Comment by lmazuel** [comment]
Done :)
