### ISSUE TITLE
No Response with error urllib3.connection.HTTPSConnection Failed to establish a new connection [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by puneetvaza-star** [Azure/azure-sdk-for-python#30010]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.2.0
- **Operating System**: windows
- **Python Version**: 3.7

**Describe the bug**
I am using the SDK for getting predictions from invoices and receipt pre-build models. I create a exe of this python file using pyinstaller. initially it was running properly. but suddenly this is giving me below error. 
No Response with error urllib3.connection.HTTPSConnection Failed to establish a new connection [Errno 11001] getaddrinfo failed

**To Reproduce**
1. 

**Expected behavior**
This should return the expected output object.

**Screenshots**

**Additional context**

```
import argparse
import os
from azure.ai.formrecognizer import DocumentAnalysisClient
from azure.core.credentials import AzureKeyCredential
pstr_az_endpoint = r"https://xyz.cognitiveservices.azure.com/"
pstr_az_key = "xyz"
document_analysis_client = DocumentAnalysisClient(endpoint=pstr_az_endpoint, credential=AzureKeyCredential(pstr_az_key))
if __name__ == '__main__':
    # import ctypes
    parser = argparse.ArgumentParser(description='For testing purposes')
    parser.add_argument('-path', dest='path', type=str, default=None)
    parser.add_argument('-model', dest='model', type=str, default=None)
    args = parser.parse_args()
    if args.path:
           with open(args.path, "rb") as fileitem:
                lftr_file = fileitem.read()
                lbyte_file = bytearray(lftr_file)
                poller = document_analysis_client.begin_analyze_document(args.model, lbyte_file)
                print(poller.result())
    else:
        print(f"path is not specified")



```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

This error shows that you don't have a working network connection.

Please check your network setting.

**Comment by puneetvaza-star** [comment]
now i am also getting 
 ("('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))",)

its working fine when I make exe using below code
`import argparse
import os
from azure.ai.formrecognizer import DocumentAnalysisClient
from azure.core.credentials import AzureKeyCredential

pstr_az_endpoint = r"https://xyz.cognitiveservices.azure.com/"
pstr_az_key = "xyz"

document_analysis_client = DocumentAnalysisClient(endpoint=pstr_az_endpoint, credential=AzureKeyCredential(pstr_az_key))

if __name__ == '__main__':
    # import ctypes
    parser = argparse.ArgumentParser(description='For testing purposes)
    parser.add_argument('-path', dest='path', type=str, default=None)
    parser.add_argument('-model', dest='model', type=str, default=None)


    args = parser.parse_args()
    if args.path:
            with open(args.path, "rb") as fileitem:
                lftr_file = fileitem.read()
                lbyte_file = bytearray(lftr_file)
            poller = document_analysis_client.begin_analyze_document(args.model, lbyte_file)
            print(poller.result())
            
    else:
        print(f"path is not specified")
`

but in production exe I am making a object of document_analysis_client and reusing it for every API call to that exe. cant figure out whats going wrong for once it worked fine but next call it gave the above error
