### ISSUE TITLE
MonitorManagementClient metrics.list method doesn't work with multiple metrics

### ISSUE THREAD

**Issue by kkrueger** [Azure/azure-sdk-for-python#30016]
- **Package Name**: azure-mgmt-monitor
- **Package Version**: 6.0.0
- **Operating System**: Windows 10
- **Python Version**: 3.9.2

**Describe the bug**
With version 6.0.0, passing multiple metricnames into the list method as a comma separated list results in an HttpResponseError:

> (BadRequest) Failed to find metric configuration for provider: Microsoft.Cache, resource Type: Redis, metric: cachehits,serverLoad

As the parameter name implies, it should be possible to pass in multiple metricnames. This worked in version 5.0.1.

**To Reproduce**

```
from azure.mgmt.monitor import MonitorManagementClient
end_time = datetime.datetime.utcnow()
start_time = end_time - datetime.timedelta(hours=1)
monitor_client = MonitorManagementClient(credential, subscription_id)
metric_data = monitor_client.metrics.list(
        resource_id, # This example uses a Azure Cache for Redis resource
        metricnames='cachehits,serverLoad',
        timespan=f"{start_time}/{end_time}",
        interval='PT1M',
        aggregation='Total,Average,Minimum,Maximum,Count'
    )
```

**Expected behavior**
The list method returns the requested metric data for multiple metrics

**Comment by kashifkhan** [comment]
Thank you for the feedback @kkrueger . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
simliare issue: https://github.com/Azure/azure-rest-api-specs/issues/23669

**Comment by xiangyan99** [comment]
Because this is tracked in https://github.com/Azure/azure-rest-api-specs/issues/23669, close the issue.
