### ISSUE TITLE
azureml-dataset-runtime not available in Python 3.10

### ISSUE THREAD

**Issue by siva-msft** [Azure/azure-sdk-for-python#30015]
I am using Parallel run and Batch inference step in AzureML; and need to install [azureml-dataset-runtime](https://pypi.org/project/azureml-dataset-runtime/)

My environment is Python 3.10 and my pip version is 23.1.

Downgrading to Python 3.7 solved my problem, however, is there any plan to make these modules available for newer versions of Python 3.8+?

**Comment by siva-msft** [comment]
Additional info: I am building an AML environment based on a docker image with Ubuntu 22 where Python 3.10 is the default version available.
I want to ensure the Python versions in my local environments and the ones used on AML are consistent.

**Comment by achauhan-scc** [comment]
please reopen if this still a problem.
