### ISSUE TITLE
How to swap VM OS disk?

### ISSUE THREAD

**Issue by MingweiSamuel** [Azure/azure-sdk-for-python#3001]
In the azure cli, it's super easy to swap the os disk:
`az vm update --resource-group paz --name vm-swap-test --os-disk new-osdisk-id`

How can I replace the OS disk using the azure sdk? Replacing it using `compute_client.virtual_machines.create_or_update(...)` results in
```
msrestazure.azure_exceptions.CloudError: Azure Error: PropertyChangeNotAllowed
Message: Changing property 'osDisk.createOption' is not allowed.
Target: osDisk.createOption
```

Example code: https://gist.github.com/MingweiSamuel/46b952a4f9475be80d9affc4ef5e8a5c

**Comment by lmazuel** [comment]
You should do a get to get the actual object, modify it (change os disk), and then call `create_or_update`. 
See here how I attach a new disk: get, modify, create_or_update:
https://github.com/Azure-Samples/virtual-machines-python-manage/blob/245833272ad48b67f45bd0acae5110f8617cdbd0/example.py#L136-L157

**Comment by MingweiSamuel** [comment]
Got it to work, it only accepts the disk in a very particular way:
```
vm_info.storage_profile.os_disk = {
    'create_option': vm_info.storage_profile.os_disk.create_option, #'attach',
    'managed_disk': {
        'id': swap_os_disk.managed_disk.id, # new disk id
        'storage_account_type': 'Premium_LRS' # this might be optional
    }
}
```

**Comment by MingweiSamuel** [comment]
@dikadali 

I have the following: (not sure which ones actually matter for this though)
```
# Azure Requirements
azure-common==1.1.14
azure-mgmt-compute==4.0.* # (4.0.1)
azure-mgmt-network==2.0.* # (2.0.1)
azure-mgmt-resource==2.0.* # (2.0.0)
# azure-cli-core needed for automatic auth.
azure-cli-core==2.0.42
```

**Comment by dikadali** [comment]
> @dikadali
> 
> I have the following: (not sure which ones actually matter for this though)
> 
> ```
> # Azure Requirements
> azure-common==1.1.14
> azure-mgmt-compute==4.0.* # (4.0.1)
> azure-mgmt-network==2.0.* # (2.0.1)
> azure-mgmt-resource==2.0.* # (2.0.0)
> # azure-cli-core needed for automatic auth.
> azure-cli-core==2.0.42
> ```

Thank you for taking time and responding in detail. Looks like you are using SDK 4.0
Below are my version details which is not working.
azure-mgmt-compute==3.0.1
azure-mgmt-network==1.7.1
azure-mgmt-resource==1.2.2
