### ISSUE TITLE
Why did the Python SDK hung forever when passed wrong name of vault

### ISSUE THREAD

**Issue by k3rcaft** [Azure/azure-sdk-for-python#30023]
- azure-keyvault-secrets
- 4.7.0
- MacOS Ventura
- 3.9.16

When I tried to get all secrets of a vault when any problem when interacted with vault the Azure Key Vault library still worked correctly (it notified detail message with guide) except the case that I passed wrong name of vault which wasn't exist in my organization. It hung forever and did not response any error. When I debugged, I recognized this line was hanged as image below.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/82924654/233820645-246cdccf-32a8-4b36-9bd2-3e9ddd0b7e84.png">

**Comment by kashifkhan** [comment]
Thanks for the feedback @k3rcaft . We will investigate and get back to you asap.

**Comment by mccoyp** [comment]
Hi @k3rcaft, thank you for opening an issue! I haven't been able to reproduce this behavior, so I left the details of my attempt below. When you say that execution hangs at the `secret_properties = secret_client.list_properties_of_secrets()` line, do you mean that the value of `secret_properties` was never returned? Or, do you mean that the program would hang when you attempt to iterate over `secret_properties`?

If operations are hanging, it might be possible that your requests don't have an appropriate timeout value set. When you create a SecretClient with `self.get_secret_client`, are you [providing a custom transport](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#transport) to the client constructor?

I tried reproducing your issue on my end by doing the following:
```python
from azure.identity.aio import DefaultAzureCredential
from azure.keyvault.secrets.aio import SecretClient

credential = DefaultAzureCredential()
client = SecretClient("https://fake-vault.vault.azure.net", credential)
properties = client.list_properties_of_secrets()
```

`list_properties_of_secrets()` returns immediately here, and `properties` is an `azure.core.async_paging.AsyncItemPaged` object. When I try to actually iterate over the `AsyncItemPaged` instance by using `async for property in properties:`, the program hangs for a few seconds before I get the following exception:
```
azure.core.exceptions.ServiceRequestError: Cannot connect to host fake-vault.vault.azure.net:443 ssl:True [getaddrinfo failed]
```

This is expected; iterating over the `AsyncItemPaged` object triggers a request to the vault URL, and we get a connection failure after the request times out.

**Comment by k3rcaft** [comment]
> Hi @k3rcaft, thank you for opening an issue! I haven't been able to reproduce this behavior, so I left the details of my attempt below. When you say that execution hangs at the `secret_properties = secret_client.list_properties_of_secrets()` line, do you mean that the value of `secret_properties` was never returned? Or, do you mean that the program would hang when you attempt to iterate over `secret_properties`?
> 
> If operations are hanging, it might be possible that your requests don't have an appropriate timeout value set. When you create a SecretClient with `self.get_secret_client`, are you [providing a custom transport](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#transport) to the client constructor?
> 
> I tried reproducing your issue on my end by doing the following:
> 
> ```python
> from azure.identity.aio import DefaultAzureCredential
> from azure.keyvault.secrets.aio import SecretClient
> 
> credential = DefaultAzureCredential()
> client = SecretClient("https://fake-vault.vault.azure.net", credential)
> properties = client.list_properties_of_secrets()
> ```
> 
> `list_properties_of_secrets()` returns immediately here, and `properties` is an `azure.core.async_paging.AsyncItemPaged` object. When I try to actually iterate over the `AsyncItemPaged` instance by using `async for property in properties:`, the program hangs for a few seconds before I get the following exception:
> 
> ```
> azure.core.exceptions.ServiceRequestError: Cannot connect to host fake-vault.vault.azure.net:443 ssl:True [getaddrinfo failed]
> ```
> 
> This is expected; iterating over the `AsyncItemPaged` object triggers a request to the vault URL, and we get a connection failure after the request times out.

Thanks for your feedback, I wanted to mean that the program would hang when I tried to attempt to iterate over secret_properties. I did not declare any custom transport. The program hang over 45 - 55 seconds when I fetched a vault that was not exist in my organization.

**Comment by k3rcaft** [comment]
This is my code, the Redis turned off.
`    async def get_secret_client(self, vault_name):
        """Get secret client to interact with Azure Vault service.

        :param str vault_name: name of vault
        """

        return SecretClient(
            vault_url=f"https://{vault_name}.vault.azure.net/",
            credential=self.get_azure_portal_credential())

    @redis_cache(
        status=RedisStatus.CACHED,
        keyword="VaultService:get_all_secrets",
        mapper=dict_to_secret_list_mapper
    )
    async def get_all_secrets(self, vault_name):
        """Get all secrets of vault (doublecheck permission necessary).

        :param str vault_name: name of vault
        """

        try:
            secret_client = await self.get_secret_client(vault_name)
            secret_properties = secret_client.list_properties_of_secrets()
            secrets = [
                Secret(
                    name=secret_client.get_secret(sp.name).name,
                    value=secret_client.get_secret(sp.name).value)
                for sp in secret_properties
            ]
            return secrets
        except (HttpResponseError, ClientAuthenticationError, ServiceRequestError) as e:
            logger.error(f"Occur some problem when interact with {vault_name} vault.")
            logger.error(e.message)
            raise AzureVaultException(status_code=e.status_code, detail=e.message)`

**Comment by mccoyp** [comment]
Hi @k3rcaft, thanks for the update. I have a few more questions to try to narrow down the cause:

1. What environment is this code being run in? For example, is this in a VM and/or Managed Identity environment? Are you using a proxy?
2. What credential are you using? I see that you call a `get_azure_portal_credential` method -- does this return a DefaultAzureCredential? If so, do you know which credential in the chain you're attempting to use?
3. You mentioned that the program hangs for about 45-55 seconds. After hanging for that period of time, does an error get raised? Or, would this continue to hang until you halt the program manually?
4. Is the vault you're trying to communicate with an existing vault that exists outside of your organization, or is it a nonexistent endpoint?

**Comment by k3rcaft** [comment]
> Hi @k3rcaft, thanks for the update. I have a few more questions to try to narrow down the cause:
> 
> 1. What environment is this code being run in? For example, is this in a VM and/or Managed Identity environment? Are you using a proxy?
> 2. What credential are you using? I see that you call a `get_azure_portal_credential` method -- does this return a DefaultAzureCredential? If so, do you know which credential in the chain you're attempting to use?
> 3. You mentioned that the program hangs for about 45-55 seconds. After hanging for that period of time, does an error get raised? Or, would this continue to hang until you halt the program manually?
> 4. Is the vault you're trying to communicate with an existing vault that exists outside of your organization, or is it a nonexistent endpoint?

1. I have already run it in my PC and haven't any proxies. This is my environment's configuration:

```txt
name: azure-integration-api
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=22.2.2
  - python=3.10.0
  - pip:
      - azure-devops==7.1.0b3
      - azure-common==1.1.28
      - azure-mgmt-resource==23.0.0
      - azure-identity==1.13.0
      - azure-mgmt-web==7.1.0
      - azure-storage-file-share==12.12.0
      - azure-storage-blob==12.16.0
      - azure-keyvault-secrets==4.7.0
      - azure-appconfiguration==1.4.0
      - msrest==0.7.1
      - fastapi==0.95.1
      - pydantic==1.10.7
      - starlette==0.26.1
      - openpyxl==3.1.2
      - pandas==2.0.1
      - XlsxWriter==3.1.0
      - python-multipart==0.0.6
      - redis==4.5.5
      - uvicorn==0.22.0
      - gunicorn==20.1.0
      - passlib==1.7.4
      - python-jose==3.3.0
      - bcrypt==4.0.1
      - chardet==5.1.0
      - hurry.filesize==0.9
      - certifi==2023.5.7
      - GitPython==3.1.31
```

2. I have used the ClientSecretCredential instead.
```python
    def _get_azure_portal_credential(self):
        """Get a credential to interact with Azure Portal services.

        :return:
        """

        return ClientSecretCredential(
            client_id=self._app_conf.CLIENT_ID,
            client_secret=self._app_conf.CLIENT_SECRET,
            tenant_id=self._app_conf.TENANT_ID)
```
3. It will be thrown the exception after long time that hang the program.
```txt
azure.core.exceptions.ServiceRequestError: (<urllib3.connection.HTTPSConnection object at 0x0000022E01D8AFE0>, 'Connection to kvstarter03.vault.azure.net timed out. (connect timeout=300)')
```
4. I don't know if the vault is exist in any organizations. But it was not exist in my orgarzation. Accidentally , I've passed my vault that was wrong by its name and I've gotten this case.

**Comment by mccoyp** [comment]
Hi again @k3rcaft, thank you for the information. I've tried recreating your setup but again, I'm getting a `urllib3.exceptions.NewConnectionError` ("Cannot connect to host") instead of your `urllib3.exceptions.ConnectTimeoutError` ("Connection timed out").

Could I ask you to try a request to the nonexistent vault with `urllib3` directly? For example, in a fresh Python terminal, try the following:
```cmd
>>> import certifi
>>> import urllib3
>>> http = urllib3.PoolManager(cert_reqs="CERT_REQUIRED", ca_certs=certifi.where())
>>> request = http.request("GET", "https://kvstarter03.vault.azure.net/secrets/fakesecret?api-version=7.4")
```

When I try this on my end I get the same `NewConnectionError` that I see when using the KV client.

One other thing: do you have environment variables `HTTP_PROXY` or `HTTPS_PROXY` set in your environment? I ask because [`azure-core` will automatically use these values for a proxy](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#proxy-settings), which could mean that your connection is accidentally going through a proxy. That's the only reason our behavior might differ that I can think of after a good bit of digging.

**Comment by k3rcaft** [comment]
```txt
>>> import certifi  
>>> import urllib3
>>> http = urllib3.PoolManager(cert_reqs="CERT_REQUIRED", ca_certs=certifi.where())
>>> request = http.request("GET", "https://kvstarter03.vault.azure.net/secrets/fakesecret?api-version=7.4")
Traceback (most recent call last):
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000020E366544F0>, 'Connection to kvstarter03.vault.azure.net timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\macos\anaconda3\envs\azure-integration-api-upgrade\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kvstarter03.vault.azure.net', port=443): Max retries exceeded with url: /secrets/fakesecret?api-version=7.4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020E366544F0>, 'Connection to kvstarter03.vault.azure.net timed out. (connect timeout=None)'))
```

I've still got the timeout error. I've not used any proxy before.

**Comment by mccoyp** [comment]
@k3rcaft thank you for giving it a try. Knowing that we each get the same errors as before when using `urllib3` is good -- that suggests there's a lower-level configuration issue, rather than something going on in the Azure SDK.

What version of `urllib3` is your Python environment using? In [my most recent comment](https://github.com/Azure/azure-sdk-for-python/issues/30023#issuecomment-1548830154)* I was using version 1.26.14. I get the same error when using version 1.26.15 (the last 1.x.x version) and version 2.0.2 (the most recent release).

One other thing I want to check is whether your machine has any system-level proxies set without your knowledge. You can check this by opening a Python terminal and running:
```cmd
>>> import urllib.request
>>> print(urllib.request.getproxies())
```
On my end the output is `{}`; i.e. no proxies are set.

\* Here's the full stack trace from my end, for reference:
```cmd
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import certifi
>>> import urllib3
>>> http = urllib3.PoolManager(cert_reqs="CERT_REQUIRED", ca_certs=certifi.where())
>>> request = http.request("GET", "https://kvstarter03.vault.azure.net/secrets/fakesecret?api-version=7.4")
Traceback (most recent call last):
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\venvs\310_clean\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D392D487C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\venvs\310_clean\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\venvs\310_clean\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\venvs\310_clean\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\venvs\310_clean\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\venvs\310_clean\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kvstarter03.vault.azure.net', port=443): Max retries exceeded with url: /secrets/fakesecret?api-version=7.4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D392D487C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by k3rcaft** [comment]
I've checked my application again. I've run without any proxy. As you mentioned I used the version 1.26.15 of urllib3. Now I try to pick another approriate version to resolve error. Do you have any idea ?
```bash
pip list | findstr urllib3 
urllib3                  1.26.15
```

**Comment by k3rcaft** [comment]
After that, thanks for your help, I will recheck some network points. See ya!
