### ISSUE TITLE
Send events to event hub error: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by summertony15** [Azure/azure-sdk-for-python#30029]
I am using Python 3.9 module to send event to event hub with connection string

Here are the demo code:

      import asyncio
      from azure.eventhub import EventData
      from azure.eventhub.aio import EventHubProducerClient
      EVENT_HUB_CONNECTION_STR = "EVENT_HUB_CONNECTION_STR"
      EVENT_HUB_NAME = "EVENT_HUB_NAME"
      
      async def run():
          # Create a producer client to send messages to the event hub.
          # Specify a connection string to your event hubs namespace and
          # the event hub name.
          producer = EventHubProducerClient.from_connection_string(
              conn_str=EVENT_HUB_CONNECTION_STR, eventhub_name=EVENT_HUB_NAME
          )
          async with producer:
              # Create a batch.
              event_data_batch = await producer.create_batch()
      
              # Add events to the batch.
              event_data_batch.add(EventData("First event "))
              event_data_batch.add(EventData("Second event"))
              event_data_batch.add(EventData("Third event"))
      
              # Send the batch of events to the event hub.
              await producer.send_batch(event_data_batch)
      
      asyncio.run(run())

I get the EVENT_HUB_CONNECTION_STR from the default RootManageSharedAccessKey with the "Connection string–primary key"
But I get the error:
ConnectionResetError: [Errno 54] Connection reset by peer

**Comment by kashifkhan** [comment]
Hi @summertony15 just checking but does the connection string have all the proper claims. Another thing to try is modify the script to use AMQP over websockets, this can help us determine if there is something blocking the connection. 

`from azure.eventhub import TransportType`

`producer = EventHubProducerClient.from_connection_string(
          conn_str=EVENT_HUB_CONNECTION_STR, eventhub_name=EVENT_HUB_NAME, transport_type=TransportType.AmqpOverWebsocket
      )

**Comment by summertony15** [comment]
I tried without connecting to VPN, and it works.
