### ISSUE TITLE
Communication Phone Numbers Readme Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#30031]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-phonenumbers#release-phone-number), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-phonenumbers#updating-phone-number-capabilities):
![image](https://user-images.githubusercontent.com/119990644/233918122-a0bb373a-d29e-41b0-af02-ad8e401b2c24.png)

**Reason**:
NameError: name 'self' is not defined

**Suggestion**:
Update to
`
phone_numbers_client
`

@rohit-ganguly, @lmazuel, @mayurid, @danielav7 for notification.

**Comment by SaurabhSharma-MSFT** [comment]
@ChenxiJiang333 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
