### ISSUE TITLE
Purview Sharing Readme and Sample Issues

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#30034]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#create-sent-share), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/purview/azure-purview-sharing/samples/sent_shares_examples.py#L51):
![image](https://user-images.githubusercontent.com/119990644/233946189-60e36291-23e9-4f94-90d6-9ad5c9195111.png)

**Reason1**:
Message: Properties.DisplayName is not a valid display name. Display names can only contain alphanumeric characters and hyphens.

**Reason2**:
SentSharesOperations.begin_create_or_replace() missing 1 required positional argument: 'sent_share'
Content: {"errors":{"":["Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 560."],"sentShare":["The sentShare field is required."]}

**Suggestion1**:
Update to
`
sampleeqshare
`

**Suggestion2**:
Update to
`
sent_share=send_share
`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#list-sent-shares), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#list-sent-share-invitations):
![image](https://user-images.githubusercontent.com/119990644/233955535-4b24c746-5665-4a9f-b8a1-09c9159f33c2.png)
![image](https://user-images.githubusercontent.com/119990644/233958810-563156ee-2db6-40d1-9d3f-2ff6f05e85f0.png)

**Reason1&2**:
AttributeError: 'ItemPaged' object has no attribute 'result'

**Suggestion1**:
Update to
```
for list_response in list_request:
    print(list_response)
```

**Suggestion2**:
Update to
```
for list_response in list_request:
    result_list = json.loads(list_response)
    print(result_list)
```

3.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#create-sent-share-invitation):
![image](https://user-images.githubusercontent.com/119990644/233952809-1a8b84a8-54f0-4fb4-8363-05d93d98a44a.png)

**Reason**:
Content: {"errors":{"":["Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 160."],"sentShareInvitation":["The sentShareInvitation field is required."]}

**Suggestion**:
Update to
`
sent_share_invitation=invitation
`

4.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#create-a-received-share), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#get-received-share):
![image](https://user-images.githubusercontent.com/119990644/233920340-8c37dc4e-6a3d-4fc0-9e95-230083a69279.png)

**Reason**:
TypeError: the JSON object must be str, bytes or bytearray, not ItemPaged

**Suggestion**:
Update to
```
received_share = next(x for x in list_detached_response)
```

@rohit-ganguly, @lmazuel, @iscai-msft for notification.

**Comment by SaurabhSharma-MSFT** [comment]
@ChenxiJiang333 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

**Comment by yamanwahsheh** [comment]
There is another PR created for this, to address the readme fixes suggested here
