### ISSUE TITLE
Cosmos Sample Issues

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#30030]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/document_management.py#L121), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/document_management_async.py#L139):
![image](https://user-images.githubusercontent.com/119990644/233916166-a2883b1d-5a15-48f0-b577-dec397540b2d.png)

**Reason**:
AttributeError: 'list' object has no attribute 'get'

**Suggestion**:
Update to
`
response['items'][0].get("discount")
`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/examples_async.py#L170), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/examples_async.py#L175):
![image](https://user-images.githubusercontent.com/119990644/233916910-49f87293-e797-4641-8f4c-7b61ef6f31b6.png)

**Reason**:
TypeError: object AsyncItemPaged can't be used in 'await' expression

**Suggestion**:
Delete this snippet code.

@rohit-ganguly, @lmazuel, @kyle-patterson, @KrzysztofCwalina, @annatisch for notification.

**Comment by SaurabhSharma-MSFT** [comment]
@ChenxiJiang333 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
