### ISSUE TITLE
Prevent workflow for forked repository

### ISSUE THREAD

**Issue by jeesang7** [Azure/azure-sdk-for-python#30042]
For the recently added [scheduling workflow](https://github.com/Azure/azure-sdk-for-python/blob/main/.github/workflows/scheduled-event-processor.yml), I confirmed that it works in the forked repository.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/30719956/234123652-017efe10-177b-4ece-8e2e-9b5b23d53d8a.png">

Minimize the forked repository action setup, and it would be nice to only work here in the upstream repository.
For example, there seems to be a way to use the `github.repository_owner` information in the [github action context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).
Thanks.

**Comment by xiangyan99** [comment]
@JimSuplizio Can you take a look?

**Comment by JimSuplizio** [comment]
@jeesang7 the email that was sent out to the leads when this was enabled said you need to disable the actions on user forks. The leads were supposed to have passed this on. GitHub is supposed to disable scheduled actions on user forks but there are currently active issues on this. On the page you'll need to select the workflow and the "..." button near the search on the upper right and disable it.
<img width="225" alt="image" src="https://user-images.githubusercontent.com/13556087/234709161-7b084d8f-a080-4f5c-9fd6-3f606edf8a9d.png">
