### ISSUE TITLE
UAMQP Client fails to open underlying connections on azure functions

### ISSUE THREAD

**Issue by SamuelYvon** [Azure/azure-sdk-for-python#30052]
## Context:
- **azure-servicebus v 7.8.1**: 
- **OS is from container mcr.microsoft.com/azure-functions/python:4-python3.9** (so debian variant)
- **Python 3.9**

**Describe the bug**

Getting errors of the style
```log
b'Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.' 
(b'/project/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters
/tlsio_openssl.c':b'on_underlying_io_open_complete':849)
```

**To Reproduce**

This occurs randomly, but seems to happen mostly in the morning EST. I bother mentioning since we are running on azure functions and it may have something to do with the environment.

**Expected behavior**
The connection is not supposed to hang for
this long. We have retries setup to the default of 3, exponential backoff to .8 and maxi
mum to two minutes. More importantly, I don't expect that in a managed environment the resources are unavailable.

**Screenshots**

I attached a bigger log with all the errors. I've had to redact some stuff but it does not impact the global logs.
[azure_log.csv](https://github.com/Azure/azure-sdk-for-python/files/11322944/azure_log.csv)

**Additional context**
We are running these in azure functions. We are using **UAMQP over websockets**. I doubt this would change anything considering the low-level nature of the errors, but I'm including it regardless.

**Comment by kashifkhan** [comment]
Hi @SamuelYvon , 

Thank you for the feedback. Looking at the logs it seems like authentication is not happening as the client is not able to reach the endpoint `Please confirm target hostname exists`. The code goes in to a retry loop and sees the same issue. Are there any other network things happening on your side that would cause this?

**Comment by SamuelYvon** [comment]
> Hi @SamuelYvon ,
> 
> Thank you for the feedback and providing the logs. Looking at the logs it seems like authentication is not happening as the client is not able to reach the endpoint `Please confirm target hostname exists`. The code goes in to a retry loop and sees the same issue. Are there any other network things happening on your side that would cause this?

This is where it gets hard; the other endpoint is an azure service bus, on the same service bus plan that triggered the azure function itself. Looking at the [azure status](https://azure.status.microsoft/en-us/status) page, there hasn't been any outages so in _theory_ the queue should have been accessible. 

However, I'd also expect that the retry loop stops before using ~16m cpu time when the timeout is set to 30 seconds. 

Here's the flamegraph for reference:
![image](https://user-images.githubusercontent.com/12652003/234294890-7365842a-13a6-4ecb-9432-98baf61d3bb8.png)

(I do not think the flamegraph is for the exact same execution, but the error is the same)

**Comment by SamuelYvon** [comment]
@kashifkhan Done :) Please confirm reception :)

**Comment by kashifkhan** [comment]
Thanks, got it @SamuelYvon. Ill update when I hear back so that we have a better idea of next steps.

**Comment by SamuelYvon** [comment]
Even if the service bus team had access to more information, I feel like there's an issue in the client API; if I give a timeout of 30 seconds, I do not expect the operation to take more than that timeout value (allowing for, of course, the retries and additional time taken by the backoff). Given that I am using default values (except timeout, which I set to 30 seconds), a blocking call of around 9 minutes seems wrong (unless the backoff is very severe?)

**Comment by kashifkhan** [comment]
@SamuelYvon sorry about the delay. Im working on this today and will see how the timeout parameter works together with the server. It could be a mix of things happening here causing that, but I want to confirm

**Comment by SamuelYvon** [comment]
> sorry about the delay.

No worries, I was making sure the connection was still alive ;) Take the time needed :)

**Comment by SamuelYvon** [comment]
@kashifkhan Any update? This is a serious issue for us (when it happens)

**Comment by kashifkhan** [comment]
@SamuelYvon sorry for the response. We are planning to start working on this issue this sprint as we had a previous release we had to get out. Its using a new amqp python library and uamqp is no longer a requirement

**Comment by SamuelYvon** [comment]
Sounds good! Thanks for the reply.

**Comment by SamuelYvon** [comment]
Hi! We have noticed and integrated. However, it seems that we now have issues with the socket _connect_ timeout. I think this is starting to look like an azure service bus issue more than an API issue. We are monitoring to see reduced error rate but it seems like it is working for now. Thank you so much for your hard work!

**Comment by kashifkhan** [comment]
@SamuelYvon the new update also had fixes for large messages and completing large messages. The socket_timeout kwarg was added for another issue which was experiencing timeout when sending large messages (25 mb each) between far away regions. This has resolved the issue for them, but they were not using azure functions.
