### ISSUE TITLE
Wrong type hint for function make_link in azure.ai.ml._utils._html_utils.py 

### ISSUE THREAD

**Issue by martinResearch** [Azure/azure-sdk-for-python#30092]
- **Package Name**:  azure.ai.ml
- **Package Version**: 1.5.0
- **Operating System**: Windows
- **Python Version**:  3.10

**Describe the bug**

when I run mypy on my code I get a error with the function make_link. The type hint is wrong for that function: 
```
def make_link(link_string, link_text=None):
    # type: (str) -> str
    if not link_text:  # Actually want truthy string
        link_text = "Link"
    return LINK_FMT.format(escape(link_string), link_text)

```
it should be
```
def make_link(link_string, link_text=None):
    # type: (str, Optional[str]) -> str
    if not link_text:  # Actually want truthy string
        link_text = "Link"
    return LINK_FMT.format(escape(link_string), link_text)

```

**Comment by kashifkhan** [comment]
Thanks for the feedback @martinResearch . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by achauhan-scc** [comment]
we fixed multiple mypy issue, closing as obsolete
