### ISSUE TITLE
azure-mgmt-apimanagement / can only set only one tag instead of multiple tags in query param

### ISSUE THREAD

**Issue by copdips** [Azure/azure-sdk-for-python#30103]
- **Package Name**:  azure-mgmt-apimanagement
- **Package Version**:  3.0.0
- **Operating System**: ubuntu 20.04
- **Python Version**: 3.10

**Describe the bug**
As per [API doc](https://github.com/Azure/azure-rest-api-specs/issues/23731#issuecomment-1525151467), the query param accepts multiple tags in the form of `&tags=a&tags=b`, which means multiple query params with the same name.

But the python sdk accept only one tag:
https://github.com/Azure/azure-sdk-for-python/blob/60dd9429b48036b252d8376f4f6789d2877e22a7/sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_api_operations.py#L88-L89

**To Reproduce**
The SDK just accepts `tags` field as a simple str:
https://github.com/Azure/azure-sdk-for-python/blob/60dd9429b48036b252d8376f4f6789d2877e22a7/sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_api_operations.py#L41-L49

**Expected behavior**

Whether key `tags` as `str`, but do some internal split before sending to backend API, whether make `tags` as `list[str]`

**Screenshots**

**Additional context**
I only checked azure-mgmt-apimanagement, maybe same issue for other modules too.

**Comment by msyyc** [comment]
Hi @copdips SDK is generated with [swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/apimanagement/resource-manager) by tools. For this issue, we need to make sure:
(1) Does https://github.com/Azure/azure-rest-api-specs/issues/23731#issuecomment-1525151467 work? I understand not all the service support multi query values. If service doesn't support that and you want this feature, please make issue in https://github.com/Azure/azure-rest-api-specs/issues
(2) If service supports that, service team needs to update the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/817e7cea0b7e3194868825cbef6d4e62a7895951/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/apimapis.json#L73-L77) with guidance: https://swagger.io/docs/specification/2-0/describing-parameters/
(3) After (1) and (2) done, SDK team can release a new version to support that.

**Comment by copdips** [comment]
@msyyc 
thank you very much for your check, I just dropped a message to APIM API team on github.
