### ISSUE TITLE
[FEATURE REQ] Add new overload to AzureKeyCredential Policy for value prefix

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#30120]
We have services that requires to send:
```
Authorization: SharedAccessKey my-key-here
```

After discussion with the Azure Core alias, the proposition is to add a new overload (or option value, whatever works best for your language) to the already existing AzureKeyCredentialPolicy:

Example:
- AzureKeyCredentialPolicy(“MyHeaderKey”) => MyHeaderKey: key-from-credential
- AzureKeyCredentialPolicy(“HeaderName”, “Prefix”) => HeaderName: Prefix key-from-credential
- AzureKeyCredentialPolicy(“Authorization”, “SharedAccessKey”) => Authorization: SharedAccessKey key-from-credential

I'm targeting the June release cycle (release early June) at worst, in order to plug this feature in our codegen, as we have services writing customization to workaround this right now.

Thanks!

See also:
-	[[FEATURE REQ] Add new overload to AzureKeyCredential Policy for value prefix · Issue #35879 · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/issues/35879)
-	[[FEATURE REQ] Add new overload to AzureKeyCredential Policy for value prefix · Issue #34697 · Azure/azure-sdk-for-java (github.com)](https://github.com/Azure/azure-sdk-for-java/issues/34697)
-	[[FEATURE REQ] Add new overload to AzureKeyCredential Policy for value prefix · Issue #30120 · Azure/azure-sdk-for-python (github.com)](https://github.com/Azure/azure-sdk-for-python/issues/30120)
-	[[FEATURE REQ] Add new overload to AzureKeyCredential Policy for value prefix · Issue #25683 · Azure/azure-sdk-for-js (github.com)](https://github.com/Azure/azure-sdk-for-js/issues/25683)

**Comment by xiangyan99** [comment]
Completed.
