### ISSUE TITLE
Import bug: 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup'

### ISSUE THREAD

**Issue by jozeecp** [Azure/azure-sdk-for-python#30147]
**Describe the bug**
This is more or less a duplicate of this issue: https://github.com/Azure/azure-sdk-for-python/issues/28757
There was a fix proposed but no one has actually implemented it. I'd be happy to create a PR for it.

**Comment by xiangyan99** [comment]
Please feel free to open a PR and thanks for the contribution.

**Comment by gbsmith** [comment]
I am still seeing the 

`ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup'`

error. Was a PR never open and merged on this?

**Comment by msyyc** [comment]
Here is the right way to use the package: https://github.com/Azure/azure-sdk-for-python/issues/28757#issuecomment-1448729884
