### ISSUE TITLE
How can I disable health probe of an instance in a VMSS using Python so that the application gateway stops sending new requests to that instance?

### ISSUE THREAD

**Issue by shobhanaquickride** [Azure/azure-sdk-for-python#30142]
I have an application gateway which has a backend pool configured. The backend pool points to a VMSS which contains multiple instances. Health probe is also configured. When I want to downscale the VMSS instances from say 4 to 3, I want the application gateway to stop sending new requests to the instance which gets selected for deletion. I have been told that I need to listen to the terminate events and disable the health probe on that instance to achieve this. 

How can I disable the health probe of an instance in a VMSS using Python scripts? I have tried the following, but there is an error which indicates that there is no "update" option available on the VMSS. 
Error: AttributeError: 'VirtualMachineScaleSetVMsOperations' object has no attribute 'update' 

I am running this on a Ubuntu 20.04 instance. I installed these libs: 
pip3 install azure-mgmt-compute 
pip3 install msrestazure 

Code is shown below; please help me to fix this:

```
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.compute import ComputeManagementClient

subscription_id = 'subs_id'
credentials = ServicePrincipalCredentials(
    client_id='client_id',
    secret='secret',
    tenant='tenant_id'
)

compute_client = ComputeManagementClient(
    credential=credentials,
    subscription_id=subscription_id
)

compute_client.virtual_machine_scale_set_vms.update(
    resource_group_name='my_rg',
    vm_scale_set_name='vmss_name',
    instance_id='instance_id',
    parameters={
        'additional_capabilities': {
            'ultra_performance_enabled': False,
            'accelerated_networking_enabled': False
        }
    }
)
```

**Comment by hilaryw29** [comment]
Hi @shobhanaquickride, thanks for your feedback! This area is used for API issues, Bugs, & product questions, your best bet for answers like this are on [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/393/azure-vm-scalesets) or [StackOverflow](https://stackoverflow.com/questions/tagged/azure-vm-scale-set).
