### ISSUE TITLE
 azure.identity 1.12.0 for Python 3.10 does not install properly in Azure Automation

### ISSUE THREAD

**Issue by stvpwrs** [Azure/azure-sdk-for-python#30157]
- **azure.identity**: 
- **1.12.0**: 
- **Linux/Azure Automation Runbook**:
- **3.10**: 

**Describe the bug**
When installing azure.identity 1.12.0 for Python 3.10 in Azure Automation, a number of dependencies do not properly import. 

**To Reproduce**
1. Upload the `azure_identity-1.12.0-py3-none-any.whl` file to Azure Automation for Python 3.10 .
2. Start a runbook with `from azure.identity import DefaultAzureCredential`.

**Expected behavior**
The azure.identity should successfully install with all dependences for the package.

**Additional context**
In order of encountered errors as dependencies were manually installed in an attempt to resolve the issues:

`Traceback (most recent call last): File "/usr/src/tmp/6d3287fe-5366-4524-9d8b-96fc139a9589/runbooks/PythonNewTest.py", line 2, in <module> from azure.identity import DefaultAzureCredential File "/usr/local/lib/python3.10/dist-packages/azure/identity/__init__.py", line 10, in <module> from ._credentials import ( File "/usr/local/lib/python3.10/dist-packages/azure/identity/_credentials/__init__.py", line 5, in <module> from .authorization_code import AuthorizationCodeCredential File "/usr/local/lib/python3.10/dist-packages/azure/identity/_credentials/authorization_code.py", line 9, in <module> from .._internal.aad_client import AadClient File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/__init__.py", line 5, in <module> from .aad_client import AadClient File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/aad_client.py", line 11, in <module> from .aad_client_base import AadClientBase File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/aad_client_base.py", line 12, in <module> import six ModuleNotFoundError: No module named 'six'`

`Traceback (most recent call last): File "/usr/src/tmp/6d3287fe-5366-4524-9d8b-96fc139a9589/runbooks/PythonNewTest.py", line 2, in <module> from azure.identity import DefaultAzureCredential File "/usr/local/lib/python3.10/dist-packages/azure/identity/__init__.py", line 10, in <module> from ._credentials import ( File "/usr/local/lib/python3.10/dist-packages/azure/identity/_credentials/__init__.py", line 5, in <module> from .authorization_code import AuthorizationCodeCredential File "/usr/local/lib/python3.10/dist-packages/azure/identity/_credentials/authorization_code.py", line 9, in <module> from .._internal.aad_client import AadClient File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/__init__.py", line 5, in <module> from .aad_client import AadClient File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/aad_client.py", line 11, in <module> from .aad_client_base import AadClientBase File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/aad_client_base.py", line 20, in <module> from .aadclient_certificate import AadClientCertificate File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/aadclient_certificate.py", line 7, in <module> from cryptography import x509 ModuleNotFoundError: No module named 'cryptography'`

`ModuleNotFoundError: No module named '_cffi_backend' thread '<unnamed>' panicked at 'Python API call failed', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.15.2/src/err/mod.rs:582:5 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace Traceback (most recent call last): File "/usr/src/tmp/6d3287fe-5366-4524-9d8b-96fc139a9589/runbooks/PythonNewTest.py", line 2, in <module> from azure.identity import DefaultAzureCredential File "/usr/local/lib/python3.10/dist-packages/azure/identity/__init__.py", line 10, in <module> from ._credentials import ( File "/usr/local/lib/python3.10/dist-packages/azure/identity/_credentials/__init__.py", line 5, in <module> from .authorization_code import AuthorizationCodeCredential File "/usr/local/lib/python3.10/dist-packages/azure/identity/_credentials/authorization_code.py", line 9, in <module> from .._internal.aad_client import AadClient File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/__init__.py", line 5, in <module> from .aad_client import AadClient File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/aad_client.py", line 11, in <module> from .aad_client_base import AadClientBase File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/aad_client_base.py", line 20, in <module> from .aadclient_certificate import AadClientCertificate File "/usr/local/lib/python3.10/dist-packages/azure/identity/_internal/aadclient_certificate.py", line 7, in <module> from cryptography import x509 File "/usr/local/lib/python3.10/dist-packages/cryptography/x509/__init__.py", line 6, in <module> from cryptography.x509 import certificate_transparency File "/usr/local/lib/python3.10/dist-packages/cryptography/x509/certificate_transparency.py", line 10, in <module> from cryptography.hazmat.bindings._rust import x509 as rust_x509 pyo3_runtime.PanicException: Python API call failed`

**Comment by pvaneck** [comment]
I am not super familiar with Azure Automation. Seems like this is more of the nature of Azure Automation environments where you either need to upload all the `whl` files and the `whl` files of their dependencies or perhaps try following [this](https://learn.microsoft.com/azure/automation/python-3-packages?tabs=py3#import-a-package-with-dependencies) which looks to be able to help with importing dependencies. From the looks of your environment, `cryptography` still needs the `cffi` package installed.
