### ISSUE TITLE
Word Salad

### ISSUE THREAD

**Issue by jrumbau2** [Azure/azure-sdk-for-python#30152]
[Enter feedback here]
Examples (simple query) doesn't work because DefaultAzureCredential isn't working and there's no link to follow that mgiht have the additional 700 pages needed to figure out why.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 086893ce-7b34-6c37-f2e5-36a3505baa69
* Version Independent ID: 14650046-8b8a-8f9c-b5be-8ae6bd27044b
* Content: [Azure Monitor Query client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/monitor-query-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/monitor-query-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/monitor-query-readme.md)
* Service: **monitor**
* GitHub Login: @pvaneck
* Microsoft Alias: **paulvaneck**

**Comment by pvaneck** [comment]
Hey, thanks for the feedback! You are right in that the README should be pointing users to the Troubleshooting guide. I've created a PR to address this. 

For your specific error, defintely try reading this section of the [guide](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-query/TROUBLESHOOTING.md#authentication-errors)
