### ISSUE TITLE
Integration with Azure Keyvault from AksCompute cluster in Azure ML SDK V1 throws CredentialUnavailableException

### ISSUE THREAD

**Issue by techdev0312** [Azure/azure-sdk-for-python#30177]
We developed some internal packages for python that are hosted in our private artifact feed. These libraries use Azure key vault to fetch secrets and the retraining process and Inferencing logic needs access to this library. The keyvault is in a different resource group  outside of MLS workspace. The problem we are facing currently is that AksCluster is not able to authenticate with KeyVault and throwing an error **"Azure KeyVault: Azure.Identity.CredentialUnavailableException: DefaultAzureCredential failed to retrieve a token from the included credentials"**

Tried adding identity of the workspace as well as identities of cluster and node pool from AksCluster to the Keyvault but these changes did not work.

Sample code for workspace connection to Artifact feed

**ws.set_connection(name="token-name", 
 category = "PythonFeed",
target = "https://<my-company-name>.pkgs.visualstudio.com", 
authType = "PAT", 
value = "mytoken")**

Sample code for adding internal package

**cd = CondaDependencies()
cd.add_pip_package("mycustompackage==1.0.0")
cd.set_pip_option("--extra-index-url https://<My-Company-Name> .pkgs.visualstudio.com/_packaging/<My-PackageFeedName>/pypi/simple/")
env.python.conda_dependencies=cd**

Sample code for AksCompute creation. 

prov_config = AksCompute.provisioning_configuration(vm_size = "Standard_A4m_v2",
                                                        agent_count = 2,
                                                        location = "eastus")

aks_name = 'myAksName'

aks_target = ComputeTarget.create(workspace = ws,
                                      name = aks_name,
                                      provisioning_configuration = prov_config)

aks_target.wait_for_completion(show_output = True)

Followed documentation link from Microsoft to configure workload-identity on AKS Cluster but not sure how from step **Deploy your application** , "azure.workload.identity/use: "true"  can be set from the sdk v1 through python code during creation of cluster.  
https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster

Can you please elaborate what are the recommended steps of integrating with Azure Keyvault from AksCluster compute in SDK v1 or do we need to upgrade to v2 and change the compute types? Is there a connection that can be established at workspace level that gives access to the keyvault for all computes created within the workspace similar to how we set Artifact Feed connection or any other alternative way ?

**Comment by xiangyan99** [comment]
Thanks for reaching out. To make sure I understand your scenario correctly, could you help to give more information about SDK v1 vs SDK v2?

**Comment by techdev0312** [comment]
@xiangyan99 
 
I am using Azure Machine Learning SDK v1 for python to create the AksCluster and deploying the endpoint on it that is used for inferencing. Please let me know if you need additional information.

Below is the link that talks about the upgrade from v1 to v2

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-migrate-from-v1?view=azureml-api-2

**Comment by xiangyan99** [comment]
Thank you for the information.

If you don't mind, could you tell me which library did you use for AksCompute?

**Comment by techdev0312** [comment]
I used Azure ML SDK v1(azureml.core.compute.aks ->AksCompute class)  to create AksCompute. Below is the sample code for creating compute and deploying model to endpoint.

Compute creation

prov_config = AksCompute.provisioning_configuration(vm_size = "Standard_A4m_v2",
agent_count = 2,
location = "eastus")

aks_name = 'myAksName'

aks_target = ComputeTarget.create(workspace = ws,
name = aks_name,
provisioning_configuration = prov_config)

aks_target.wait_for_completion(show_output = True)


Model deployment

aks_target = AksCompute(ws, "myAksComputeName")

inference_config = InferenceConfig(entry_script='myinferencescript.py', environment=env)

deployment_config = AksWebservice.deploy_configuration(period_seconds = 30,
                                                       failure_threshold = 10,
                                                       timeout_seconds = 30,
                                                       max_request_wait_time= 60000,
                                                       num_replicas =2,
                                                       enable_app_insights = True)

service = Model.deploy(ws, "myendpointname", [model], inference_config, deployment_config, aks_target)
service.wait_for_deployment(show_output = True)

**Comment by xiangyan99** [comment]
Thanks for the information.

I asked this because the managed identity implementation in ML hosted pool is different from others.

@luigiw @azureml-github, could you help to take a look?

**Comment by techdev0312** [comment]
Hi Team,

Checking to see if there is any update on this issue.

**Comment by achauhan-scc** [comment]
Please use SDK V2 as we have limited support for SDK V1
