### ISSUE TITLE
Error in documentation for receive_messages

### ISSUE THREAD

**Issue by martinitus** [Azure/azure-sdk-for-python#30184]
Regression of: https://github.com/Azure/azure-sdk-for-python/issues/21378
Regressed in: https://github.com/Azure/azure-sdk-for-python/pull/14855

The original issue was fixed [here](https://github.com/Azure/azure-sdk-for-python/pull/21463) , but now the documentation again says, that the minimum is 0, where it actually seems to be 1.

https://github.com/Azure/azure-sdk-for-python/blob/66e2d1a45d956349368cfec9c0866fc069b3eef8/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L470-L477

and 

https://github.com/Azure/azure-sdk-for-python/blob/66e2d1a45d956349368cfec9c0866fc069b3eef8/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L555-L561

**Comment by martinitus** [comment]
Also the same documentation changes should be applied to the async client versions in the `aio`  submodule.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by jalauzon-msft** [comment]
Hi @martinitus Martin, thanks for the feedback. I agree the documentation needs to be updated for `recevie_message` (singular) as the default value and minimum value are incorrect. This should match the documentation (that was fixed a while back) for `receive_messages` (plural).

For `send_message` however, I believe the documentation is correct. This documentation aligns with the service documentation for [Put Message](https://learn.microsoft.com/en-us/rest/api/storageservices/put-message#uri-parameters) which is the API that backs this method. When sending a message, it is valid (and the default behavior) to set visibility timeout to 0 to make the message immediately visible.

We will create a PR soon to address `receive_message` (sync and async) though. Thanks!

**Comment by vincenttran-msft** [comment]
Hi @martinitus Martin, thanks for your contribution! I have gone ahead and merged the pull-request containing the correction of the typos you have identified. Thanks for your contribution!
