### ISSUE TITLE
authentication  error

### ISSUE THREAD

**Issue by g-r-m-n** [Azure/azure-sdk-for-python#30200]
authentication does not work.

I receive the following error, even thought the cognitiveservices is up and running and the key and endpoint are correct.

azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorResponseException: (401) Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
>>> print(f"The description of the image is: {described_response.captions[0].text} with confidence {described_response.captions[0].confidence}")
Traceback (most recent call last):

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f91b0f03-d716-3421-9023-8e871c188188
* Version Independent ID: 4565d28a-0c4d-f663-b9ea-b53e51389d10
* Content: [Azure Cognitive Services Computer Vision SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/cognitiveservices-vision-computervision-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/cognitiveservices-vision-computervision-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/cognitiveservices-vision-computervision-readme.md)
* Service: **cognitive-services**
* Sub-service: **computer-vision**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by xiangyan99** [comment]
Thanks for reaching out. 

Could you help to provide more information?

e.g. which library are you using? which version?

if possible, could you share your code snippets?

Thanks.
