### ISSUE TITLE
Registry environments can't be updated

### ISSUE THREAD

**Issue by elesel** [Azure/azure-sdk-for-python#30208]
- **azureml-ai-ml**: 
- **1.5.0**: 
- **Windows**:
- **3.9.5**: 

**Describe the bug**
When calling `MLClient.environments.create_or_update()` and passing it an existing registry name and version, I'm not able to update the environment's mutable properties, like its tags or description. This is because the function always tries to create a temporary data ref for the build context, and when the call returns an HTTP 409, the SDK simply does a GET for the existing version and returns it.

**To Reproduce**
```python
import logging
from azure.ai.ml import MLClient
from azure.identity import AzureCliCredential
from azure.ai.ml.entities import Environment

logging.basicConfig(level=logging.DEBUG)

registry = "<registry_name>"

ml_client = MLClient(
    credential=AzureCliCredential(),
    registry_name=registry,
)

env = Environment(
    name="alpine",
    version="1",
    description="Environment based on alpine image.",
    image="docker.io/alpine:latest",
    tags={'Preview': ""},  # Toggling this line should allow you to create or remove the Preview tag
)
updated_env = ml_client.environments.create_or_update(env)
print("Updated environment:", updated_env)
```

**Expected behavior**
I expect the method to skip uploading the build context if the environment already exists, and just update the mutable properties.

**Comment by nancy-mejia** [comment]
Hello @elesel 
Thank you for the feedback.
We have investigated the issue, and the fix will be included in the next release.

**Comment by achauhan-scc** [comment]
validated, Code is able to update tag
