### ISSUE TITLE
Run Managed HSM tests only weekly

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#30205]
Only provision and test Managed HSMs weekly instead of nightly. See https://github.com/Azure/azure-sdk-for-net/pull/35770 for files you can copy directly, such as tests.yml and test-resources.json. Any tests requiring those resources should be skipped to avoid erring.

At the same time, you might also disable attestation tests in Canary as the PR does, since these having been failing and, along with EngSys, we felt we have sufficient coverage across other clouds.

**Comment by mccoyp** [comment]
Resolved by https://github.com/Azure/azure-sdk-for-python/pull/29909.
