### ISSUE TITLE
UX issue when trying to use user assigned managed identity.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#30214]
Docs say set 'AZURE_CLIENT_ID'. If I only do that, I get this error:

`Incomplete environment configuration. These variables are set: AZURE_CLIENT_ID`

That is because it tries to use EnvironmentConfig first.

I'd like to see the docs updated to say you must disable EnvironmentConfig with exclude_environment_credential=True if you want to use user assigned managed identity.

**Comment by jongio** [comment]
Or detect that user has only set AZURE_CLIENT_ID and assume they want to use user assigned MI

**Comment by DataKnox** [comment]
Can confirm this was a major pain in the ass for me to figure out when using Azure Container Apps (assignment at the app, then assignment at the container revision,  then adding the environment variables).
