### ISSUE TITLE
Option to preserve `last_modified` and `creation_time` when using `blob_client.start_copy_from_url`

### ISSUE THREAD

**Issue by seanslma** [Azure/azure-sdk-for-python#30225]
This is for `azure.storage.blob`.

**Is your feature request related to a problem? Please describe.**
There currently is not a method used to move a blob to another folder, whether in the same container or not. To move the blob file I have to first copy the blob to another folder and then delete it.

The `creation_time` and `last_modified` properties contain important info related to the blob file. Ideally these info should be preserved when copy the blob to another place. However, `blob_client.start_copy_from_url` method does not have such an option to preserve the original info of the blob file.

**Describe the solution you'd like**
Add an option in `blob_client.start_copy_from_url` so the user can preserve the timestamp info if they want to.

**Describe alternatives you've considered**
A better solution might be creating a new method to move the blob file with default option to preserve the file properties.

**Additional context**
The `last_modified` property has been preserved when using `Storage Explorer`, so technically this should be doable in the Python sdk.

**Comment by vincenttran-msft** [comment]
Hi @seanslma Sean, thanks for reaching out with your inquiry. Unfortunately, this is not something that is technically possible from the Python SDK. I noticed that you also mentioned it being possible using Storage Explorer, but after inquiring with the team that manages that tool, it also doesn't seem like preserving `last_modified` or `creation_time` properties strictly is something possible when interacting with blobs through Storage Explorer (perhaps your source blob upload and destination blob copy finished at the same time, leading to the conclusion that you _can_ preserve those properties?)

With that being said, I can provide two possible workflows that I believe will achieve the functionality you are looking for:

1. Consider storing the relevant values (in this case, `last_modified` and `creation_time`) as metadata. Although this would require a little bit more logic in your code, this would allow you to have explicit control over when these values are modified.
2. AzCopy (which backs Storage Explorer) has an alternative way to preserve several properties as POSIX properties, but again this also just stores it in metadata (but may have greater out-of-the-box support)

If you do decide to go with option 2, the team has shared with me the following information:
`azcopy copy --help` details information about the `--preserve-posix-properties` flag, and here is the metadata names used for POSIX property preservation in AzCopy:
```
const ( // POSIX property metadata
   POSIXNlinkMeta         = "posix_nlink"
   POSIXINodeMeta         = "posix_ino"
   POSIXCTimeMeta         = "posix_ctime"
   LINUXBTimeMeta         = "linux_btime"
   POSIXBlockDeviceMeta   = "is_block_dev" // todo: read & use these
   POSIXCharDeviceMeta    = "is_char_dev"
   POSIXSocketMeta        = "is_socket"
   POSIXFIFOMeta          = "is_fifo"
   POSIXDevMeta           = "posix_dev"
   POSIXRDevMeta          = "posix_rdev"
   POSIXATimeMeta         = "posix_atime"
   POSIXFolderMeta        = "hdi_isfolder" // todo: read & use these
   POSIXSymlinkMeta       = "is_symlink"
   POSIXOwnerMeta         = "posix_owner"
   POSIXGroupMeta         = "posix_group"
   POSIXModeMeta          = "permissions"
   POSIXModTimeMeta       = "modtime"
   LINUXAttributeMeta     = "linux_attribute"
   LINUXAttributeMaskMeta = "linux_attribute_mask"
   LINUXStatxMaskMeta     = "linux_statx_mask"
)
```

And so, I will close this issue for now as this is not a feature request that we can support on the Python SDK side, and hopefully one of these alternatives will suit your use case. Please reach out if you have any questions!
Thanks!
