### ISSUE TITLE
filedatalake (and other storage libs) give type hint error when using async credential types

### ISSUE THREAD

**Issue by jabbera** [Azure/azure-sdk-for-python#30234]
- **Package Name**:  azure-storage-file-datalake
- **Package Version**:  12.11.0
- **Operating System**: Ubuntu
- **Python Version**: 3.10

**Describe the bug**
The following code yields type hinting errors. I would think the async versions of the sdk clients should also accept the async protocol from azure.core for identity here:

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/credentials_async.py

Code runs fine at runtime.

```
from azure.identity.aio import AzureCliCredential()
from azure.storage.filedatalake.aio import DataLakeServiceClient

DataLakeServiceClient("doesn't matter", AzureCliCredential())
```

```
Argument of type "AzureCliCredential" cannot be assigned to parameter "credential" of type "str | Dict[str, str] | AzureNamedKeyCredential | AzureSasCredential | TokenCredential | None" in function "__init__"
  Type "AzureCliCredential" cannot be assigned to type "str | Dict[str, str] | AzureNamedKeyCredential | AzureSasCredential | TokenCredential | None"
    "AzureCliCredential" is incompatible with "str"
    "AzureCliCredential" is incompatible with "Dict[str, str]"
    "AzureCliCredential" is incompatible with "AzureNamedKeyCredential"
    "AzureCliCredential" is incompatible with "AzureSasCredential"
    "AzureCliCredential" is incompatible with protocol "TokenCredential"
      "get_token" is an incompatible type
        Type "(*scopes: str, **kwargs: Any) -> Coroutine[Any, Any, AccessToken]" cannot be assigned to type "(*scopes: str, claims: str | None = None, tenant_id: str | None = None, **kwargs: Any) -> AccessToken"
  ...
```

**To Reproduce**
1. pip install azure-storage-file-datalake
2. Type code above into VSCode configured for python

**Expected behavior**
No Type hint error

**Screenshots**

**Additional context**
This is pervasive across the storage SDK in general.

**Comment by jabbera** [comment]
The label on this is wrong, but I can't change it.

**Comment by vincenttran-msft** [comment]
Hi @jabbera Mike, thanks for your inquiry! I will have a fix for this shortly and will attach it to this issue. Thanks!

**Comment by jabbera** [comment]
Thanks for the quick turnaround!
