### ISSUE TITLE
[BUG] Not retry on PATCH request

### ISSUE THREAD

**Issue by YalinLi0312** [Azure/azure-sdk-for-python#30241]
There's a failure in blob upload in acr(details: https://github.com/Azure/azure-sdk-for-python/issues/29738), but we didn't see the 404 error as described in the attached issue. I found the reason is we didn't retry when a `ServiceRequestError: Server disconencted` or `ServiceRequestError: [WinError 64] The specified network is no longer available` occurred on a `PATCH` request in [`upload_blob()`](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py#L980). I tried with [these](https://github.com/Azure/azure-sdk-for-python/commit/78f4f1dbf5f0ea798b67a1687ab5d1061b23ee66) updates in `azure-core`, can get the expected error:
```text
 _content: {"errors":[{"code":"BLOB_UPLOAD_INVALID","message":"blob upload invalid"}]}
 _status_code: 404
```

**Comment by xiangyan99** [comment]
I think you are asking for https://github.com/Azure/azure-sdk-for-python/issues/16284

**Comment by YalinLi0312** [comment]
> I think you are asking for #16284

Yes, the configurable retryable method can fix my issue. I notice the linked issue was opened in 2021, just curious when will it be available?

**Comment by johanste** [comment]
Under what circumstances is the 404 response retryable? You should be able to provide the retryable HTTP methods (including PATCH) in the request context you pass to the pipeline. Is there something else that is needed?

**Comment by YalinLi0312** [comment]
> Under what circumstances is the 404 response retryable? You should be able to provide the retryable HTTP methods (including PATCH) in the request context you pass to the pipeline. Is there something else that is needed?

- In the acr issue, we want to retry when there's a `ServiceRequestError` occured on a `PATCH` request, so that can get error with status code `404` in the end. Otherwise only see the `ServiceRequestError` which we cannot determine if it is the expected error as in other languages.
- It works by passing a retryable method from sdk(it works without updates I did in azure-core). 

Still having one question, why `PATCH` is not included in the retryable [method white list](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L77)? Does it intend to?

**Comment by johanste** [comment]
It depends on the content type. We probably should make PATCH + content-type: application/merge-patch+json request body retryable. I opened #30332 to track this.

**Comment by lmazuel** [comment]
Closed, tracked by https://github.com/Azure/azure-sdk-for-python/issues/30332 instead
