### ISSUE TITLE
StorageManagementClient not raising HttpResponseError exception upon throttling

### ISSUE THREAD

**Issue by wushingmushine** [Azure/azure-sdk-for-python#30258]
- **Package Name**: azure-managment-storage
- **Package Version**: 2022_09_01
- **Operating System**: Ubuntu 22.04.2 LTS on WSL2 (5.10.102.1-microsoft-standard-WSL2)
- **Python Version**: 3.10.6

**Describe the bug**
If receiving a 'throttled' response (status code `429`) when calling storage_accounts.get_properties, no error is raised so the throttling error can't be caught and handled. Instead, the client hangs until the 'retry_after' value in the throttling response has elapsed.

**To Reproduce**
1. Run the below code until you are throttled:
```
from azure.mgmt.storage import StorageManagementClient
from azure.core import exceptions

storage_client = StorageManagementClient("tokenCredential", "mySubscriptionId")

while True:
    try:
        account_properties = storage_client.storage_accounts.get_properties(account_name="myStorageAccount", resource_group_name="myResourceGroup")
        print(account_properties)
    except exceptions.HttpResponseError as httpErr:
        print("###Caught exception###")
        print(httpErr.message)
        break
```

**Expected behavior**
A HttpResponseError - or an error of some form - is raised. Much like how a `404` error is raised if you provide an invalid storage account name.

**Additional context**
Debug logs show the following request-response pair when hitting throttling: 
*Request:*
```
{"asctime": "2023-05-05 09:14:10,271", "levelname": "DEBUG", "name": "azure.core.pipeline.policies._universal", "filename": "_universal.py", "lineno": 330, "threadName": "createstorageaccount", "message": "Request URL: 'https://management.azure.com/subscriptions/mySubscriptionId/providers/Microsoft.Storage/storageAccounts?api-version=2022-05-01'\nRequest method: 'GET'\nRequest headers:\n    'Accept': 'application/json'\n    'x-ms-client-request-id': 'requestId'\n    'User-Agent': 'azsdk-python-azure-mgmt-storage/20.1.0 Python/3.10.6 (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35)'\n    'Authorization': 'myBearerToken'\nRequest body:\nThis request has no body"}
```
*Response:*
```
{"asctime": "2023-05-05 09:14:10,330", "levelname": "DEBUG", "name": "azure.core.pipeline.policies._universal", "filename": "_universal.py", "lineno": 375, "threadName": "createstorageaccount", "message": "Response status: '429'\nResponse headers:\n    'Cache-Control': 'no-cache'\n    'Pragma': 'no-cache'\n    'Content-Length': '226'\n    'Content-Type': 'application/json'\n    'Expires': '-1'\n    'Retry-After': '282'\n    'x-ms-request-id': 'requestId'\n    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'\n    'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'\n    'x-ms-ratelimit-remaining-subscription-reads': '11799'\n    'x-ms-correlation-request-id': '84...'\n    'x-ms-routing-request-id': 'UKWEST:20...'\n    'X-Content-Type-Options': 'nosniff'\n    'Date': 'Fri, 05 May 2023 08:14:12 GMT'\n    'Connection': 'close'\nResponse content:\n{\"error\":{\"code\":\"TooManyRequests\",\"message\":\"The request is being throttled as the limit has been reached for operation type - List_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits\"}}"}
```
The client does not raise any error at all, the 429 response is logged only as a DEBUG-level event. Is this intended behavior? If so, how can I induce the client to raise an error upon throttling? Passing in an `error_map` to the `get_properties` call does not seem to have any effect: `storage_client.storage_accounts.get_properties(account_name="myStorageAccount", resource_group_name="myResourceGroup", error_map={429: HttpResponseError})`. For our implementation, it is necessary to use polling at scale.

**Comment by msyyc** [comment]
Hi @wushingmushine It is by design:https://github.com/Azure/azure-sdk-for-python/blob/fbb7a4a5889c92551f6552e06a7d67256219023a/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L184
Since throttle is temporary for a few seconds, SDK will retry after `retry-after` of response and users don't need to know it.
If you really want to raise exception for `429`, please set customized retry policy like:
```python
...
from azure.core.pipeline.policies import RetryPolicy
storage_client = StorageManagementClient(..., retry_policy=RetryPolicy(retry_on_status_codes=set(range(999)) - set(range(506)) + set([408, 500, 502, 503, 504]))
...
```

**Comment by wushingmushine** [comment]
Thanks @msyyc. In our experience, the throttle tended to last for a few minutes, which is why we thought it odd that it hung for that duration with no feedback.

That customized RetryPolicy doesn't seem to work due to the unsupported operand combining the sets
![image](https://github.com/Azure/azure-sdk-for-python/assets/42030279/a1250892-5940-4bd9-986c-1fc6cb819fc0)

But even if the sets or successfully combined (e.g. `set(range(999)) - set(range(506))).union(set([408, 500, 502, 503, 504])`), it doesn't work if there's a `Retry-After` header present in the response (which seems to usually be the case, at least for the operation in the example code) due to the early return in `is_retry` [here](https://github.com/Azure/azure-sdk-for-python/blob/fbb7a4a5889c92551f6552e06a7d67256219023a/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L197).

Would there be any way to override that behaviour?

**Comment by msyyc** [comment]
It seems that you have to customize the retry policy. For example:
```python
class MyRetryPolicy(RetryPolicy):
    def is_retry():
        # your customized retry logic
storage_client = StorageManagementClient(..., retry_policy=MyRetryPolicy(retry_on_status_codes=set(range(999)) - set(range(506)) | set([408, 500, 502, 503, 504]))
```

**Comment by wushingmushine** [comment]
That makes sense - thanks for the help! Happy for this to be closed :)
