### ISSUE TITLE
Inconsistency on default int type.

### ISSUE THREAD

**Issue by dlech** [Azure/azure-sdk-for-python#30261]
This page states that the INT64 type is required which implies a Python `int` would be INT32 by default. However, the docstrings for `EdmType` state:

> ```python
>   INT32 = "Edm.Int32"
>   """ Represents a number between -(2^15) and 2^15. Must be specified or numbers will default to INT64. """
> ```

This are saying the opposite so only one can be true. Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f065e29-9f83-458f-5044-7dfc3ca3a9ef
* Version Independent ID: 6417a292-2442-452c-faa7-331fdf28117c
* Content: [azure.data.tables.EntityProperty class](https://learn.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables.entityproperty?view=azure-python)
* Content Source: [docs-ref-autogen/azure-data-tables/azure.data.tables.EntityProperty.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-data-tables/azure.data.tables.EntityProperty.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment]
Hi @dlech , the default `int` is **INT32**, we'll update the docstring.
