### ISSUE TITLE
Issue with DefaultAzureCredential

### ISSUE THREAD

**Issue by satishgunjal** [Azure/azure-sdk-for-python#30288]
We are using the below Power BI Agent guide to try to connect to Power BI dashboard. Our code is in Azure Databricks python notebook.

[Power BI Dataset Agent](https://python.langchain.com/en/latest/modules/agents/toolkits/examples/powerbi.html)

We are  facing issues with the below line of code.

powerbi=PowerBIDataset(dataset_id="<dataset_id>", table_names=['table1', 'table2'], credential=DefaultAzureCredential())

Error:

ConfigError: field "credential" not yet prepared so type is still a ForwardRef, you might need to call PowerBIDataset.update_forward_refs().

We tried searching to solve the issues we no luck so far. Is there any configuration we are missing? Can you share more details, is there any specific configuration or access required on power BI side?

thanks in advance...

**Comment by kashifkhan** [comment]
Hi @satishgunjal , thank you for the feedback. Can you provide some more of lines from your code up to the point of the problem please ? This will help our team in assisting you better

**Comment by satishgunjal** [comment]
> Hi @satishgunjal , thank you for the feedback. Can you provide some more of lines from your code up to the point of the problem please ? This will help our team in assisting you better

Our code is exactly same what is available on Langachain site. We have just added our OpenAI API key. [reference](https://python.langchain.com/en/latest/modules/agents/toolkits/examples/powerbi.html)

Code snippet:

```
from langchain.agents.agent_toolkits import create_pbi_agent
from langchain.agents.agent_toolkits import PowerBIToolkit
from langchain.utilities.powerbi import PowerBIDataset
from langchain.llms.openai import AzureOpenAI
from langchain.agents import AgentExecutor
from azure.identity import DefaultAzureCredential

fast_llm = AzureOpenAI(temperature=0.5, max_tokens=1000, deployment_name="gpt-35-turbo", verbose=True)
smart_llm = AzureOpenAI(temperature=0, max_tokens=100, deployment_name="gpt-4", verbose=True)

toolkit = PowerBIToolkit(
    powerbi=PowerBIDataset(dataset_id="<dataset_id>", table_names=['table1', 'table2'], credential=DefaultAzureCredential()), 
    llm=smart_llm
)

agent_executor = create_pbi_agent(
    llm=fast_llm,
    toolkit=toolkit,
    verbose=True,
)
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

It looks to me it is a bug in langchain: https://github.com/hwchase17/langchain/blob/master/langchain/utilities/powerbi.py

`TokenCredential` is only defined in TYPE_CHECKING.

I would recommend you open an issue in langchain repo.

**Comment by flipg1995** [comment]
Hi, do we have a solutions for this issue?

**Comment by muhammadsmalik** [comment]
Also looking for a solution to this. Any workarounds for now would also be appreciated.

**Comment by cheefuyoong** [comment]
Hi, is there any solutions yet? Would be appreciated

**Comment by pvaneck** [comment]
Seems like this issue is being addressed here: https://github.com/hwchase17/langchain/pull/4534
