### ISSUE TITLE
Update documentation for upload_page in blob storage?

### ISSUE THREAD

**Issue by erikpa1** [Azure/azure-sdk-for-python#30311]
**Is your feature request related to a problem? Please describe.**
I need to upload blob in chunks  (client sends 1MB in every http request on my webpage, and and want to store that 1MB, client send another,....) and I can't find normal working example on internet for this (I see in python there is some support for this but I can't write it), could be nice to add example for this.

**Describe the solution you'd like**
Update the documentation.

**Additional context**
What I do is, on frontend user put 1GB big file and I'm splitting it on frontend end sending it to server and from server to azure storage and I need to ensure this streaming.

**Comment by erikpa1** [comment]
I found this:

https://xhinker.medium.com/how-to-upload-large-files-to-azure-blob-storage-with-python-dacf2b969a90

its nice example could be added to documentation

**Comment by erikpa1** [comment]
Please, also put BIG warning about this from documentation:

(I was doing only increment, 0, 1, 2, 3, 4) and it crashed because string has to be same lenght

**For a given blob, the length of the value specified for the blockid parameter must be the same size for each block. Note that the Base64 string must be URL-encoded.**

**Comment by erikpa1** [comment]
Ok update,  my "0001" is not working because i started blob with "0", after crash on "10" a wanted to change indexig, but can't because its set on 1 char block_id,  HOW do I reset is ?  (removing blob ? but blob don't exists ?)

**Comment by vincenttran-msft** [comment]
Hi @erikpa1, thanks for your inquiry! There is quite a bit of information to parse through here, so I will do my best to address your main concerns first, which will in turn hopefully resolve some of your follow-ups as well 😄 

Firstly, I notice that your title references the `upload_page` API (used with `PageBlob`), but the code sample that you linked as a solution to your problem has `blob_type="BlockBlob"`. With that being said, below I will provide a code sample and explain some of the keywords and functionalities that I believe are relevant to your use case.

Code Sample:
```
from azure.storage.blob import BlobClient, ContainerClient

# Account Information Strings
ACCOUNT_URL = f"https://<ACCOUNT_NAME>.blob.core.windows.net"
ACCOUNT_NAME = <ACCOUNT_NAME>
ACCOUNT_KEY = <ACCOUNT_KEY>

# Creating your container
container_client = ContainerClient(account_url=ACCOUNT_URL, credential=ACCOUNT_KEY, container_name=<TEST_CONTAINER_NAME>)
try:
    container_client.create_container()
except:
    pass


# Uploading your local file in 1MB chunks
# Block Blob
blob_client = BlobClient(account_url=ACCOUNT_URL, credential=ACCOUNT_KEY, container_name=<CONTAINER_NAME>, blob_name=<BLOB_NAME>, max_block_size=1024*1024, max_single_put_size=1024)
with open(<LOCAL_FILE_NAME>, "rb") as data:
    blob_client.upload_blob(data, blob_type="BlockBlob")

# Page Blob
blob_client = BlobClient(account_url=ACCOUNT_URL, credential=ACCOUNT_KEY, container_name=<CONTAINER_NAME>, blob_name=<BLOB_NAME>, max_page_size=1024*1024, max_single_put_size=1024)
with open(<LOCAL_FILE_NAME>, "rb") as data:
    blob_client.upload_blob(data, blob_type="PageBlob")
```

Some things to note:

1. `max_single_put_size` is set ridiculously low to ensure all uploads >1024KB are chunked (please see documentation for more info)
3. Chunking is done [automatically](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L596-L603) and more information on the keywords to tweak the chunking behavior can be found [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L121-L129) (with some of the relevant ones in the highlighted section)
4. When using page blobs, the relevant variable for chunk sizes would be `max_page_size`
5. When using block blobs, the relevant variable for chunk sizes would be `max_block_size`

Hopefully this sample provides you with some clarity on how to use our SDK for your provided use case! Another great resource for getting familiar with the library is our [samples ](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob/samples)section. 

Lastly, we do hear your concerns about improving our documentation, and there is currently an active effort in the team to improve our documentation in the near future.

Thanks!

**Comment by erikpa1** [comment]
@vincenttran-msft Hi Vincent, thanks for answer but your solution is useless, and already in examples. In my use-cases I upload Big file ( > 1GB) in browser on client side, chunk it there, send junks on server, and from server, staging blobs on azure storage. The thing you are advertising is totally outside of context. You can't send big file to web app on azure in 1 Post because of azure time out on slow internet. For this purpose, storage has stage_block function, which I need, and provided (in link), all you had to do is copy code from webpage and put it to documentation examples 😄 Or please explain me how your code will work, in case user will want to send 20 GB file via browser to my web app and I want to store it to azure storage, yeah and user has 100Kb upload only.

**Comment by jalauzon-msft** [comment]
Hi @erikpa1, as Vincent mentioned above, the `upload_blob` API will **automatically chunk the blob** and internally call a series of `stage_block` followed by a `commit_block_list` at the end. By default, the SDK will chunk any blob larger than 64 MiB and has a chunk size of 4 MiB, but as Vincent also mentioned, these values can be configured with `max_block_size` (chunk size) and `max_single_put_size` (size threshold for chunking). These are keyword arguments to client constructors. So, no matter the size of the blob, `upload_blob` should be able to handle the upload without timeouts assuming you apply the correct configuration.

The medium article you linked was not fully correct when they moved away from `upload_blob` because of timeout issues. They were obviously not aware of the correct configuration around chunk size and timeouts. More information on the correct timeout configuration can also be found [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/README.md#other-client--per-operation-configuration).

We were providing this example as an alternative approach to doing the chunking yourself and using `stage_block`. However, that solution is also fine if you choose. It is also already documented [here](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-upload-python#upload-a-block-blob-by-staging-blocks-and-committing) (along with other solutions).

We plan to update our samples/documentation around upload/download in the near future to include more information and make the sample Vincent shared and the one I linked above to be more discoverable/unified. Thanks.

**Comment by erikpa1** [comment]
@jalauzon-msft  Thanks for answer. The link you provided, is nice, I could find it I went form [Here](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python?tabs=managed-identity%2Croles-azure-portal%2Csign-in-azure-cli) straight to examples on github. The link you provided I see first time.

**To answer second part of your answer:**
This is what I'm looking for, it could be nice to add it to the github examples also because I think, its important for some developers.

**To answer first part of your answer:**
I don't understand why are you still answering with this answer, as I said twice , its totally out of my use case, just impossible to implement in that way, I can`t 

```
with open(file, "rb") as file:
   blob.upload_blob("path.extension", file);
```
because  file I'm sending is **NOT on my machine** !!! 

In real world web application  I can't just take 20GB file put to HTML form send it (on slow internet) to azure web app (because web app will time). That's why client need to chunk it on client -> send chunk to azure web app -> azure web app will stage_block.

With this I can also restore upload...

**Comment by jalauzon-msft** [comment]
Hi @erikpa1 Erik, sorry for the delay and sorry that we did not realize the file was not on your machine. If you are downloading a remote file in chunks and looking to upload in chunks, `stage_blob` is the way to go. It seems the link I already provided is what you were looking for so hopefully that helped.

There is a chance that you could also leverage [Copy Blob from URL](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url?tabs=azure-ad) via [start_copy_from_url](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-start-copy-from-url) to copy the whole blob without it going through your machine at all. This API can work with public URLs that are not in Storage so may work for you. Thanks.
