### ISSUE TITLE
Job permanently running in 'preparing' status regardless of job or compute (cluster + instance) 

### ISSUE THREAD

**Issue by VEshelbyMTT** [Azure/azure-sdk-for-python#30340]
- **Package Name**: azure-ai-ml
- **Package Version**:  1.4.0
- **Operating System**: W11
- **Python Version**: 3.8

**Describe the bug**

Running lab 2 from the course material in git (https://github.com/MicrosoftLearning/mslearn-azure-ml) which highlighted the issue. Tested it out using my own scripts. Lab is in perpetual status along with any other jobs proceeding it regardless of compute, or region (see image) or job command

Evidence this worked in the past: 
![image](https://github.com/Azure/azure-sdk-for-python/assets/104829457/0e53c0de-98f2-4c62-b555-afd258a01493)

**To Reproduce**
1. import the git repo shared in the 'describe the bug' and run lab 2 in Azure Machine learning
2. Create a storage account that matches the assets described in the jupyter notebook or clone directly from the instructions

**Expected behavior**
job should run and complete after 20-60 seconds 

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/104829457/1760bd44-eeed-4074-853b-804faa5f839d)

**Additional context**
Azure status declare AML to up and running. Is there something up with the compute?

**Comment by diondrapeck** [comment]
@rytsang Could you please look into this for Execution Service?

**Comment by achauhan-scc** [comment]
closing as obsolete
