### ISSUE TITLE
Inconsistent upload behavior of the 'code' argument in the command function

### ISSUE THREAD

**Issue by TimonDaniels** [Azure/azure-sdk-for-python#30392]
- azure-ai-ml
- 1.5
- Ubuntu 20.04
- 3.10

I noticed that when I use `ml_client.create_or_update(job_command)` in different branches of my code the behavior of the 'code' argument in the [command function](https://learn.microsoft.com/nl-nl/python/api/azure-ai-ml/azure.ai.ml.entities.command?view=azure-python) is different. In the code directory I have several .yaml and .json files I use for configuration but the upload behavior seems inconsistent. 

When I created the the Job and check it out in AzureML studio I see in the code tab that sometimes my .json files are uploaded and sometimes they are not, which causes errors.

I expect the behavior to be consistent or at least an explanation of the uploading behavior , but so far I could not find any documentation on this. 

Can anyone explain what the behavior is or is this a bug?

Cheers,

Timon

**Comment by kashifkhan** [comment]
Thank you for the feedback @TimonDaniels . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by achauhan-scc** [comment]
closing as obsolete
