### ISSUE TITLE
Missing sample

### ISSUE THREAD

**Issue by stephanmiehe** [Azure/azure-sdk-for-python#30408]
The sample at the bottom of the page leads to a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 235574af-54a7-fffb-9a63-f65814aa9f9d
* Version Independent ID: ff8553a6-c819-6cbd-4201-f1ce7c382fc0
* Content: [Azure Resources SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/resources?view=azure-python)
* Content Source: [docs-ref-services/latest/resources.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/resources.md)
* Service: **resources**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by iscai-msft** [comment]
thank you for opening this issue @stephanmiehe, we will look into this

**Comment by msyyc** [comment]
It shall be fixed by https://github.com/Azure/azure-sdk-for-python/issues/30408
