### ISSUE TITLE
Parallel job in a pipeline stops logging and updating metrics

### ISSUE THREAD

**Issue by louisflorentin** [Azure/azure-sdk-for-python#30421]
- **Package Name**: azure.ai.ml
- **Package Version**: 1.6.0
- **Operating System**: AzureML compute instance: STANDARD_NV6 (west europe)
- **Python Version**: 3.10

**Describe the bug**
The **job_progress_overview.\<timestamp>.txt** log file and metrics like "Job progress" from a **parallel job inside of a pipeline** are not updated anymore after some time.
The last displayed messages in job_progress_overview.\<timestamp>.txt are:
`2023-05-16T22:20:53.233813 Processed 4117 of 20000 mini batches in 5:02:14. Estimated remaining time 19:25:59.`
`2023-05-16T22:22:08.962071 The overviewer on 7 stopped.`
The parallel job didn't fail and is still running, hours after logging and metrics stopped being updated.

**To Reproduce**
1. Create and submit an AzureML pipeline using the Python SDK v2 containing a Parallel job step.
Values of some parameters used in the Parallel job:
```mini_batch_size="1"
instance_count=200
max_concurrency_per_instance=1
mini_batch_error_threshold=1000
retry_settings=dict(max_retries=1, timeout=1800)
```

**Expected behavior**
Logging files like job_progress_overview.\<timestamp>.txt and metrics like "Job progress" should be updated as long as the parallel run is running.

**Additional context**
**A few nodes got preempted** during the execution of the pipeline, not sure if it could cause this issue.
I tried to attach the full logs here but **all logs from the Parallel job are too big: 5.47 GB**. Could it be the reason why logging stopped?

**Comment by kashifkhan** [comment]
Thanks for the feedback @louisflorentin. We will investigate and get back to you asap. 

cc @azureml-github

**Comment by JunAn-Chen** [comment]
Thanks for feedback @louisflorentin . I guess that the "overview task" of your job was exited by some reason, but the job is still running, you can find the progress from metric too. 
As for the root cause, I need more logs for futher investigation, you can archive and upload the sys logs under `logs/sys`, or you can send them to my email `junan.chen@microsoft.com` if they are too big to upload here, thanks.

**Comment by louisflorentin** [comment]
Thanks @JunAn-Chen, as you explained to me offline this was a transient issue related to a DNS error threshold being met for jobs submitted in the Western Europe region. As discussed this is fixed since the beginning of the week.
