### ISSUE TITLE
Azure EventHub Error : azure.eventhub.exceptions.AuthenticationError: Unable to open authentication session on connection 

### ISSUE THREAD

**Issue by skedilay** [Azure/azure-sdk-for-python#30430]
- Packages:
azure-identity == 1.12.0
aiohttp == 3.8.1
Operating System: Linux
Python Version: 3.7

- Operating System: Linux

- Python Version: 3.7

**Describe the bug**
```
            producer = EventHubProducerClient.from_connection_string(conn_str=conn_str, eventhub_name=eventhub)
```

Above code, the following exceptions are seen when it tries to push events to eventhub:
```
Event Hub offlinedebugseh-prod resulted in Authentication Error: Unable to open authentication session on connection b'EHProducer-a500e864-beaa-4ab7-b0ef-68bbedb9e141'.
Please confirm target hostname exists: b'colab-eventhubns.servicebus.windows.net'
Unable to open authentication session on connection b'EHProducer-a500e864-beaa-4ab7-b0ef-68bbedb9e141'.
```

Expected behavior
Expected no errors.

**Comment by skedilay** [comment]
Just FYI:
I verified that nsloopup <eventhubs-namespace>.servicebus.windows.net gets resolved.

**Comment by kashifkhan** [comment]
Thank you for the feedback @skedilay . can you try by setting the transport to amqp over websocket, by passing in `transport_type=TransportType.AmqpOverWebsocket`. Just want to make sure the ports are open etc. Are you behind a proxy by any chance ?

**Comment by skedilay** [comment]
Thanks for the response. As we are seeing this issue in production, I am afraid I can't give make any changes like you mentioned. Is there anything else we can try to ensure the ports are open?

**Comment by kashifkhan** [comment]
Hi @skedilay, this is the connectivity guide for amqp that can be used https://learn.microsoft.com/en-us/azure/event-hubs/troubleshooting-guide. There are ports 5671 and 5672 that need to be open on the firewall. 

Is there any way you can test locally because that can help us narrow down the issue. If from local, you can connect to an Eventhub then we definitely know its a port or proxy issue.

**Comment by skedilay** [comment]
Hi, It looks like an issue at Azure Eventhubs and I am raising the ticket with Azure support. Please close this ticket for now. Will update this thread if any help is needed from here. Thanks!
