### ISSUE TITLE
Bug in python_snippert_updater.py

### ISSUE THREAD

**Issue by mengaims** [Azure/azure-sdk-for-python#30452]
When generating code snippet first time, a blank line will be inserted between `<!-- SNIPPET:sample_file.sample_name-->` and ```python. But when run this script second time, the pattern could not be matched due to this blank line, so that the code snippet could not be updated in the second run.
![image](https://github.com/Azure/azure-sdk-for-python/assets/50131889/baa85db9-817e-4fc4-99b0-9ee9dde37111)

**Comment by iscai-msft** [comment]
thank you for opening this issue! we'll take a look into it

**Comment by xiangyan99** [comment]
Fixed.
