### ISSUE TITLE
[azure-iot-device] Ref docs issue

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-python#30469]
## Ref docs error in `azure-iot-device` 

There is an error in `azure-iot-device` that prevents generating documentation. To fix: 

1. Correct error in `azure-iot-device` package
2. Release package to PyPI
3. Remove the entry from `$PackageExclusions` (basically, [revert this change](https://github.com/Azure/azure-sdk-for-python/pull/30489))

For error message content, see comment here: https://github.com/Azure/azure-sdk-for-python/issues/30469#issuecomment-1557987548

## Original message: 

Error:

> exception (exception: No documentation for this module.)
> ##[error]<Exit Code Error(2)>: Command exited with non-zero code.
> At D:\a\_work\1\s\common\WarningFilter.ps1:96 char:9
>          throw ("<Exit Code Error($exitCode)>: Command exited with non ...
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (<Exit Code Erro... non-zero code.:String) [], RuntimeException
>     + FullyQualifiedErrorId : <Exit Code Error(2)>: Command exited with non-zero code.
>  
> 
> ##[error]Process completed with exit code 1 and had 1 error(s) written to the error stream.

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=363514&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
Thanks. It looks like the azure-iot-device is blocking up the docs build and didn't get caught by our internal heuristics. Removed and testing.

**Comment by danieljurek** [comment]
Unassigning myself so this can be triaged.

**Comment by danieljurek** [comment]
After speaking with Jun on this: 

* In the onboarding remove `"prefer_source_distribution": "true"` property.

**Comment by danieljurek** [comment]
- [x] Re-add `azure-iot-device` to onboarding https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1741
- [x] Remove from `PackageExclusions` -- https://github.com/Azure/azure-sdk-for-python/pull/30520
- [x] Open issue to track how we determine that we need to set `"prefer_source_distribution": "true"` https://github.com/Azure/azure-sdk-for-python/issues/30519
