### ISSUE TITLE
Azure: VM create failed with exception (BadRequest) Security type of VM is not compatible with the security type of attached OS Disk. Code: BadRequest

### ISSUE THREAD

**Issue by Mrbm5** [Azure/azure-sdk-for-python#30479]
- **Package Name**:  azure-mgmt-compute
- **Package Version**:  27.2.0
- **Operating System**: Linux
- **Python Version**: 3.8

**Describe the bug**
Creating a VM from from pre-created OS disk created from the snapshot of another VM which configured with `Security type: TrustedLaunch` failing with the message `Azure: VM create failed with exception (BadRequest) Security type of VM is not compatible with the security type of attached OS Disk. Code: BadRequest` even though  `SecurityProfile` settings has been provided as mentioned in the Reproduce section.

This settings are working as expected with REST API but not with SDK

**To Reproduce**
1.  Create VM on azure portal with `Security Type : Trusted Launch Virtual Machines`
2. Take snapshot of OS disk using Python SDK.
3. Create Disk from the previously taken snapshot Verify the OS disk is created with `Security Type :Trusted launch`
4. Create VM from recently created OS disk along with following `SecurityProfile` settings preserved from the original VM 
```        
 "securityProfile": {
     "uefiSettings": {
     "secureBootEnabled": true,
     "vTpmEnabled": true
    },
     "securityType": "TrustedLaunch"
 }
```
5.  VM creating fails with error `Message: Security type of VM is not compatible with the security type of attached OS Disk., error code: 400
Azure: VM create failed with exception (BadRequest) Security type of VM is not compatible with the security type of attached OS Disk.
Code: BadRequest`

**Cone snippet used for same** 
```
atype = "Standard_LRS"
        vmresgrp = "balaji.markante"
        location = "eastus2"
        vmsize = "Standard_B1s"
        caching = "ReadWrite"
        tags = { "OWNER": "balaji.markante"}
        plan = None
        disk_size_gb = 32
        ostype = "Linux"
        vmname = "Test-VM-22"
        location = "eastus2"
        osdiskid = "/subscriptions/{subscriptionsid}/resourceGroups/{vmresgrp}/providers/Microsoft.Compute/disks/test-vm-1_OsDisk"
        newvm = VirtualMachine(location=location)
        newvm.plan = Plan.from_dict(plan) if plan else None
        newvm.hardware_profile = HardwareProfile()
        newvm.hardware_profile.vm_size = vmsize
        newvm.storage_profile = StorageProfile()
        newvm.storage_profile.os_disk = OSDisk(create_option="attach")
        newvm.storage_profile.os_disk.caching = caching
        newvm.storage_profile.os_disk.disk_size_gb = disk_size_gb
        newvm.storage_profile.os_disk.managed_disk = ManagedDiskParameters()
        newvm.storage_profile.os_disk.managed_disk.storage_account_type = \
            atype
        security_type = "TrustedLaunch"
        v_tpm_enabled = "True"
        secure_boot_enabled = "True"
        uefi_settings = UefiSettings(v_tpm_enabled=v_tpm_enabled, secure_boot_enabled=secure_boot_enabled)
        newvm.security_profile = SecurityProfile()
        newvm.security_profile.security_type = security_type
        newvm.security_profile.uefi_settings = uefi_settings
        newvm.storage_profile.os_disk.managed_disk.id = osdiskid
        newvm.storage_profile.os_disk.os_type = ostype
        newvm.network_profile = NetworkProfile()
        newvm.network_profile.network_interfaces  = [{"id" :"/subscriptions/{subscriptionID}/resourceGroups/{vmresgrp }/providers/Microsoft.Network/networkInterfaces/test-vm-10_nic_1684"}]
        newvm.tags = tags
poller = computeclient.virtual_machines .begin_create_or_update(resgrp, name, newvm)
vm = poller.result()

```

**Expected behavior**
Expected behavior is VM should get created with expected securityProfile Settings.

**Screenshots**
OS disk of Original VM 
![image](https://github.com/Azure/azure-sdk-for-python/assets/63775459/fe77b3f3-4034-47d0-91f0-e474c183c853)

OS disk created  from the snapshot of original VM which will be going to attach to new virtual machine which Im trying to create:
![image](https://github.com/Azure/azure-sdk-for-python/assets/63775459/1e2ab62a-f462-48e5-a054-2246f8d214b5)

**Additional context**
I tried same settings  with Azure REST  API there this settings are working as expected.
```
https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{myresourceGrp}/providers/Microsoft.Compute/virtualMachines/test-?api-version=2022-03-01

body:
{
  "location": "eastus2",
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_B1s"
    },
    "securityProfile": {
      "uefiSettings": {
        "secureBootEnabled": true,
        "vTpmEnabled": true
      },
      "securityType": "TrustedLaunch"
    },
    "storageProfile": {
      "osDisk": {
	    "osType": "Linux",
        "caching": "ReadWrite",
        "managedDisk": {
          "storageAccountType": "Standard_LRS",
          "id":"/subscriptions/{subscriptionID}/resourcegroups/{myRG}/providers/Microsoft.Compute/disks/test-os-disk"
        },
        "createOption": "Attach",
      }
    },
    "networkProfile": {
       ......
    }
  }
}
```
Requesting team to have look into the settings  and suggest anything wrong here or issue is with SDK. 

Thanks in advance,
Balaji Markante

**Comment by kashifkhan** [comment]
Thank you for the feedback @Mrbm5 . We will investigate and get back to you asap.

**Comment by kashifkhan** [comment]
Thank you for responding back @Mrbm5 and I'm glad the issue was resolved. If its not too painful, can you post the solution ( or steps) here please? in case someone finds this issue while searching it could help them out as well 🙂
