### ISSUE TITLE
Examples don't explain how to import `load()` is in App Configuration Provider

### ISSUE THREAD

**Issue by bendavis78** [Azure/azure-sdk-for-python#30488]
On this page, all the examples reference a `load()` function without explaining where that function comes from, or how to define or import it.

for example:

```python
config = load(connection_string="your-connection-string")
```

Where does `load` come from?

Also, once you get the `config` instance, what do you actually do with it? How do you use it to get the appconfig items?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7575a40a-a5dc-c139-0145-7fdd8bcf72a0
* Version Independent ID: 635f6510-4133-75bf-769b-95090b32f18b
* Content: [Azure App Configuration Python Provider client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/appconfiguration-provider-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/appconfiguration-provider-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/appconfiguration-provider-readme.md)
* Service: **appconfiguration**
* GitHub Login: @xiangyan99
* Microsoft Alias: **xiangyan**

**Comment by xiangyan99** [comment]
Thanks for your feedback.
@mrm9084 could you take a look?

**Comment by mrm9084** [comment]
@bendavis78 thanks for pointed out the missing imports. I'll get them updated in the doc. In the mean time here is a link to the samples that show the imports. https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/appconfiguration/azure-appconfiguration-provider/samples

**Comment by bendavis78** [comment]
Thanks! I was able to find the load function in the samples. Here's what I ended up going with:

```python
        credential = DefaultAzureCredential()
        key_vault_options = provider.AzureAppConfigurationKeyVaultOptions(credential=credential)
        selects = {provider.SettingSelector(key_filter='*', label_filter="prod")}
        config = provider.load(
            endpoint=os.environ.get('APPCONFIG_ENDPOINT'),
            credential=credential,
            key_vault_options=key_vault_options,
            selects=selects,
        )
        for key, value in config.items():
            os.environ.setdefault(key, value)
```

It would also be useful to explain in the docs that the `load()` function returns a dict-like object of key/value pairs.

**Comment by mrm9084** [comment]
This has been updated and in the preview version, will be updated when the new GA version is released.
