### ISSUE TITLE
[Azure-Data-Tables, Azure-Storage-Blob] - Connection Issues

### ISSUE THREAD

**Issue by filandra** [Azure/azure-sdk-for-python#30480]
- **azure-data-tables and azure-storage-blob**: 
- **12.4.1 and 12.16.0**: 
- **Linux**:
- **3.10**: 

**Describe the bug**
We are encountering connection issues / retrying issues. Common exceptions that we encounter are:

azure.core.exceptions.ServiceResponseError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')

azure.core.exceptions.ServiceRequestError: EOF occurred in violation of protocol (_ssl.c:2396)

azure.core.exceptions.ServiceRequestError: (<urllib3.connection.HTTPSConnection object at 0x7ff1dc158040>, 'Connection to [...](...) timed out. (connect timeout=30)

requests.exceptions.ConnectionError: HTTPSConnectionPool(...)', port=443): Read timed out

We are using standard interactions with Tables and Blobs and we would expect these issues to be not very common, but right know these happen at least once every 1000 interactions (rough estimate).

**To Reproduce**
1. Create a Table
2. Add, Remove, Update Entities etc.
3. Create a container
4. Add, Remove, Update blobs etc.

**Expected behavior**
We would expect that these errors are very rare.

**Additional context**
We use the default retry policy. We are running the code on AKS. We are using Hot storage for both Tables and Blobs and Standard tier. Is there a recommended better retry policy? How should be handle this behavior?

**Comment by kashifkhan** [comment]
Thank for you for the feedback @filandra . We will investigate and get back to you asap.

**Comment by pall-j** [comment]
Any update on this? Lately, we are frequently encountering these issues in our production system.

**Comment by jalauzon-msft** [comment]
Hi @filandra and @pall-j, I can mostly only speak to `azure-storage-blob` as that's what I work with, but our default retry policy will retry these types of network errors up to 3 times and then return the error back to the calling code if we exceed that. If you have a high number of these network errors making it through to your code, you can consider increasing the retry count.

The easiest way to do this is pass retry count keywords to client constructors. You can set `retry_total`, `retry_status`, `retry_connection`, and `retry_read` to something greater than 3 (5 might be a good option). 
```py
service_client = BlobServiceClient(
    account_url=<account-url>
    credential=<creds>,
    retry_total=5,
    retry_status=5,
    retry_connection=5,
    retry_read=5)
```

You may notice though that retries start to take a long time do to our default backoff times (which we realize are not ideal and will be updating in the future). You may want to configure those timings as well if your request is time sensitive which can be done by creating and passing your own instance of the retry policy.
```py
from azure.storage.blob import BlobServiceClient, ExponentialRetry

retry = ExponentialRetry(
    initial_backoff=1,
    retry_total=5,
    retry_status=5,
    retry_connection=5,
    retry_read=5)
service_client = BlobServiceClient(
    account_url=<account-url>
    credential=<creds>,
    retry_policy=retry)
```

For tables, things look similar but I'm not sure how to configure timings. See [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/README.md#retry-policy-configuration)

---

All that being said, consistently running into network errors that make it past our default retry policy is usually unexpected and can indicate something else is going wrong outside of the SDK where retries may not help much. A couple of things to consider:

- We most frequently see an elevated number of network errors when the CPU/Network load on the client is too high. Please check the machines running your application for high load during times when you see these network errors. This is the most common cause of network errors like this as high load can cause timeouts or even exhaustion of the connection pool.
- There may be some network issue between your client machine and Storage. Please ensure the network health on your end looks good.
- Finally, there could be a network issue within Azure. If you feel this is the case, please open support ticket to have the backend team investigate further. The easiest way to do this is from the bottom of the left side panel of your Storage Account page in Azure Portal.
![image](https://github.com/Azure/azure-sdk-for-python/assets/96087589/0683a486-1f0a-477f-9b8e-662840c45aab)

**Comment by filandra** [comment]
Thank you for the response, we have taken it into consideration and came up with a solution.
