### ISSUE TITLE
What are the steps to create Recovery Service Backup policy using Azure Python SDK

### ISSUE THREAD

**Issue by indumathyn** [Azure/azure-sdk-for-python#3051]
Initially created vault using below cmd,
recovery_client.vaults.create_or_update('resrcgrpname','TestBackupDemo', params_create)

Need API to change backup configuration storage replication type from  geo to locally redundant 
Need api to set backup policy
Need api to add items to backup

**Comment by DheerendraRathor** [comment]
@indumathyn APIs for backup operations are present under backup client.
https://docs.microsoft.com/en-us/python/api/azure-mgmt-recoveryservicesbackup/azure.mgmt.recoveryservicesbackup.recoveryservicesbackupclient?view=azure-python

**Comment by indumathyn** [comment]
thats what me too searching...help me exact api to change geo to locally redundant

**Comment by DheerendraRathor** [comment]
@WebSpider For parameters, you can use class [BackupResourceConfigResource](https://docs.microsoft.com/en-us/python/api/azure-mgmt-recoveryservicesbackup/azure.mgmt.recoveryservicesbackup.models.backupresourceconfigresource?view=azure-python)

**Comment by WebSpider** [comment]
Yeah that's what I'm struggling with. Would that then be:
```python
bu_client.backup_resource_storage_configs.update(vault_name, resourcegroup_name, BackupResourceConfigResource(BackupResourceConfig(storage_type=val1, storage_model_type=val1)))
```

**Comment by DheerendraRathor** [comment]
It will be `BackupResourceConfigResource(properties=BackupResourceConfig(storage_type="LocallyRedundant", storage_type_state="Unlocked")`

**Comment by pvrk** [comment]
Trying to clean up issues. @indyumathyn: did this help? Is the issue resolved?

**Comment by pvrk** [comment]
#please-close
We believe the customer got the right response. Can re-open if the provided answer didn't help.

**Comment by indumathyn** [comment]
No thanks...working

Indumathy N.

**Comment by pvrk** [comment]
Thanks for confirming @indumathyn
Closing this issue.
