### ISSUE TITLE
Creating subscriptions

### ISSUE THREAD

**Issue by hvt** [Azure/azure-sdk-for-python#30580]
(I was directed here by Open Source Software Support Azure App Services NA.)

I am trying to create subscriptions using the Azure Python SDK. And recently a question exactly like this [was answered](https://learn.microsoft.com/en-us/answers/questions/1237114/how-to-create-azure-subscription-using-python-sdk). However, I have been unable to find the `create()` definition that is mentioned there.

At the `SubscriptionClient` class reference there is currently is no `create()` definition in the subscription operation class (see https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2022_12_01/operations/_operations.py#L300-L664).
 
So the example from the answer link -- where the `SubscriptionClient` is actually used -- using `subscription_client.subscriptions.create()`, does not work (anymore?).

Is there currently a way to create new subscriptions using the SDK?

**Comment by msyyc** [comment]
Hi @hvt You can use another package [azure-mgmt-subscription](https://pypi.org/project/azure-mgmt-subscription/3.2.0b1/). Here is the sample: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/subscription/azure-mgmt-subscription/generated_samples/create_alias.py.
Here is [doc ](https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-microsoft-customer-agreement?tabs=rest) to show how to get billingAccount/other necessary which is needed to create subscriptions. Hope the sample and doc can help you.

**Comment by hvt** [comment]
(Thanks @msyyc, this appears to be working, although I'm waiting on Azure Support to lift our subscription quota. Will report back once that's resolved.)

**Comment by hvt** [comment]
I was able to create subscriptions with the package you mentioned @msyyc :tada:, so thank you :+1: .

The code looks like this:

```python
from azure.core.exceptions import ResourceExistsError
from azure.identity import AzureCliCredential
from azure.mgmt.subscription import SubscriptionClient

subscription_name = 'new-subscription-name'

credential = AzureCliCredential()
subscription_client = SubscriptionClient(credential)

try:
    subscription_alias = subscription_client.alias.begin_create(
        alias_name=subscription_name,
        body={
            'properties': {
                'billingScope': '<the Azure billing scope>',
                'displayName': subscription_name,
                'workload': 'Production',
                'additionalProperties': {
                    'managementGroupId': None,
                    'subscriptionOwnerId': None,
                    'subscriptionTenantId': '<the Azure tenant ID>',
                    'tags': {
                        'foo': 'bar',
                    },
                },
            }
        },
    ).result()
except ResourceExistsError:
    subscription_alias = subscription_client.alias.get(alias_name=subscription_name)

print(subscription_alias)
```
