### ISSUE TITLE
EventGridClient - can't seem to find the right type for AcknowledgeOptions

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-python#30598]
- **Package name**: azure-eventgrid
- **Package Version**: azure-eventgrid==4.12.0b1 
- **Operating System**: Windows
- **Python Version**: Python 3.11 

**Describe the bug**

I can't seem to get my types to line up properly for the typechecker when using AcknowledgeOptions, which you need to use to acknowledge events. Using this snippet:

```python
from azure.eventgrid import EventGridClient
from azure.eventgrid.models import AcknowledgeOptions
from azure.core.credentials import AzureKeyCredential
from azure.core.messaging import CloudEvent

# (client creation elided)

result = client.receive_cloud_events("testtopic1", "testsubscription1", max_events=1, max_wait_time=10)
print(datetime.now())

lock_tokens = [r.broker_properties.lock_token for r in result.value]

opts = AcknowledgeOptions(lock_tokens=lock_tokens)

#
# Type error for the `opts` parameter:
# Argument of type "Model" cannot be assigned to parameter "lock_tokens" of type "AcknowledgeOptions"
#  "Model" is incompatible with "AcknowledgeOptions"
#
client.acknowledge_cloud_events("testtopic1", "testsubscription1", lock_tokens=opts)
```

**To Reproduce**
1. Use the code snippet above
2. The type checker complains about a type mismatch, basically.

**Expected behavior**

> A clear and concise description of what you expected to happen.

Type check fails. Tears.

**Comment by l0lawrence** [comment]
this model no longer exists
