### ISSUE TITLE
ImportError: cannot import name 'RequestsTransport' from 'azure.core.pipeline.transport'

### ISSUE THREAD

**Issue by b-gonzalez** [Azure/azure-sdk-for-python#30594]
I am trying to follow this tutorial:

https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python?tabs=managed-identity%2Croles-azure-portal%2Csign-in-azure-cli

When I get to this line of code:

`from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient`

I get the following error [ImportError: cannot import name 'RequestsTransport' from 'azure.core.pipeline.transport']

I can import and reference the azure core pipeline transport e.g.

`import azure.core.pipeline.transport as acpt`

but if I try `from azure.core.pipeline.transport import RequestsTransport` I get the same error

The version of azure-core I had installed was 1.26.4. I tried downgrading to 1.26.3 but it made no difference. The version of python I have installed should be 3.7 (I am using Anaconda.)

I found that this issue was previously discussed [here](https://github.com/Azure/azure-sdk-for-python/issues/29245) but don't see any solutions I can use to fix my issue. I'd appreciate any help. Thanks!

**Comment by kristapratico** [comment]
Hi @b-gonzalez, I'm not able to reproduce the issue. I suggest creating a new virtual environment and reinstalling the packages to see if that resolves the import error. 

Also, since you mentioned Anaconda, there can sometimes be issues with using pip to install packages in conda environments. I recommend following the best practices outlined here: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

Let me know if this helps.

**Comment by lasleandro** [comment]
Exactly the same problem here. I'm trying to deploy an Azure Batch with a start up task running the following commands: 
`command_list = ["sudo apt-get install unzip",
                "sudo apt-get install zip",
                #"sudo apt-get install python3-pip -y",
                "sudo apt-get install python3.8 -y",
                "sudo apt-get install python3.8-distutils -y",
                "wget https://bootstrap.pypa.io/get-pip.py",
                "python3.8 get-pip.py",
                "python3.8 -m pip install --upgrade pip",\
                "python3.8 -m pip install -r requirements.txt",\
                "python3.8 -m pip install --upgrade cryptography",
                "python3.8 -m pip install --upgrade geopandas"
                #"python3.8 -m pip install geobr --ignore-installed geopandas"
                #"python3 -m pip install --upgrade pip",\
                #"python3 -m pip install -r requirements.txt",\
                #"python3 -m pip install --upgrade cryptography"               
               ]`


And with the following libs in the requirements:

`numpy
geopandas
pandas
azure-core
azure-common
azure-storage-blob
azure-batch
fastparquet
pyarrow
unidecode
scikit-learn
psutil
libpysal`

Then, exactly the same error pointed by @b-gonzalez occurs.

**Comment by lasleandro** [comment]
I fixed it by including "requests" and "pyOpenSSL" in the requirements and updating "pyOpenSSL" in the start up task:

`command_list = ["sudo apt-get install unzip",
                "sudo apt-get install zip",
                "sudo apt-get install python3.8 -y",
                "sudo apt-get install python3.8-distutils -y",
                "wget https://bootstrap.pypa.io/get-pip.py",
                "python3.8 get-pip.py",
                "python3.8 -m pip install --upgrade pip",\
                "python3.8 -m pip install -r requirements.txt",\
                "python3.8 -m pip install --upgrade PyOpenSSL",\
                "python3.8 -m pip install --upgrade cryptography",\
                "python3.8 -m pip install --upgrade geopandas"
               ]`
