### ISSUE TITLE
Parameter descriptions missing for ModelBatchDeploymentSettings Class

### ISSUE THREAD

**Issue by guidorietbroek** [Azure/azure-sdk-for-python#30616]
Parameter descriptions are missing and the ones showed seems to be incorrect.

`ModelBatchDeploymentSettings(*, mini_batch_size: int | None, instance_count: int | None = None, max_concurrency_per_instance: int | None = None, output_action: BatchDeploymentOutputAction | None = None, output_file_name: str | None = None, retry_settings: BatchRetrySettings | None = None, environment_variables: Dict[str, str] | None = None, error_threshold: int | None = None, logging_level: str | None = None, **kwargs)` 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a263eb0-6394-2fbc-7b76-a193fb651402
* Version Independent ID: 19f4cba8-2a4e-87a7-8c84-fa785359cb25
* Content: [azure.ai.ml.entities.ModelBatchDeploymentSettings class](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.modelbatchdeploymentsettings?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.ModelBatchDeploymentSettings.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.ModelBatchDeploymentSettings.yml)
* Service: **machine-learning**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kashifkhan** [comment]
Thank you for the feedback @guidorietbroek . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by achauhan-scc** [comment]
Closing as obsolete
