### ISSUE TITLE
Setting the number of Analytics Units from python

### ISSUE THREAD

**Issue by StevenKoppens** [Azure/azure-sdk-for-python#3062]
Hello all,

I can't figure out how to set the number of Analytics Units (AUs) from the Python SDK.
Is someone here aware of how to set this (eg. using the job properties)?

Thanks,

Steven

**Comment by lmazuel** [comment]
Hi @StevenKoppens 
This is a general repo for a lot of SDK, could you precise what is the service you want to use? I could guess maybe Batch or Data Factory, but unsure :)
Thanks,

**Comment by StevenKoppens** [comment]
Hi Imazuel,

I would like to set it for jobs run on data lake analytics using the  DataLakeAnalyticsJobManagementClient from azure.mgmt.datalake.analytics.job libary.

Kind regards,

Steven

**Comment by lmazuel** [comment]
Does it help?
https://docs.microsoft.com/en-us/azure/data-lake-analytics/data-lake-analytics-manage-use-python-sdk

**Comment by wangweiming800** [comment]
@Imazuel, it looks python sdk already contains it. The name of the property is degree_of_parallelism. Please refer the following page.

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/datalake/azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_job_parameters.py

**Comment by lmazuel** [comment]
Closing, since issue seems answered
