### ISSUE TITLE
Error: Not able to create cost reports using the python sdk, throwing "Message: ServiceToServiceAuthorizationProvider.IsRPRegistered: {"error":{"code":"InvalidSubscriptionId","message":"The provided subscription identifier 'providers' is malformed or invalid."}}"

### ISSUE THREAD

**Issue by rugvedkarnati** [Azure/azure-sdk-for-python#30654]
- **Operating System**: Linux
- **Python Version**: Python 3.9
- **Package Name**: [azure-mgmt-costmanagement 4.0.0]

**Describe the bug**
When trying to use the SDK to create a billing export via Create Or Update method it seems to throw a 400 error when using a valid subscription_id. Looking at the traceback it looks as if its some how setting the subscription_id to providers. My only guess for that is something is pursing out the ID from the URL but pulling the wrong part.

Exception or Stack Trace

 if response.status_code not in [200, 201]:
>           raise models.ErrorResponseException(self._deserialize, response)
` azure.mgmt.costmanagement.models._models_py3.ErrorResponseException: (400) ServiceToServiceAuthorizationProvider.IsRPRegistered: {"error":{"code":"InvalidSubscriptionId","message":"The provided subscription identifier 'providers' is malformed or invalid."}}`
**To Reproduce**

1. Get CostManagementClient session
2. Set scope to "/subscriptions/{subscription_id}/"
3. Set export name
4. Set required parameters for export
5. Run costmgmt_client.exports.create_or_update(scope, export_name, parameters)
6. Code Snippet

```
scope = f"/subscriptions/{subscription_id}/"
    costmgmt_client = CostManagementClient(creds, subscription_id)
    parameters = {
        "deliveryInfo": {
            "destination": {
                "container": "cost",
                "rootFolderPath": "exports",
                "resourceId": "costmgmttest",
            },
        },
        "definition": {
            "dataSet": {"granularity": "daily"},
            "timeframe": "MonthToDate",
            "type": "ActualCost"
        }
    }
    costmgmt_client.exports.create_or_update(scope, "testexport", parameters)
```
**Expected behavior**
Billing export to be created correctly

It's almost like the API is pulling the providers string from the URL instead of the subscription_id.

[0] - https://docs.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update#code-try-0

**Comment by kashifkhan** [comment]
Thank you for the feedback @rugvedkarnati . We will investigate and get back to you asap.

**Comment by Wzb123456789** [comment]
Hi @rugvedkarnati You can try to use this example to solve your problem.https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/costmanagement/manage_exports.py

**Comment by msyyc** [comment]
Here are also some samples which may help: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/costmanagement/azure-mgmt-costmanagement/generated_samples
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/2d6fef75-76e3-470a-885a-46f411a8d7d2)
