### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by dzauzig** [Azure/azure-sdk-for-python#30656]
I have searched and searched for documentation about how get role assignments for a secret in Azure Key Vault. The authorizations package seems to be the closest I've found so far. But I can only find cursory documentation. The only example I can find is a mention of "authorization_client.permissions.list_for_resource_group()". No other methods or attributes are listed or described.

I know that there is more to the AuthorizationManagementClient package because I can use python to dump the members and submembers of the class. 

from azure.mgmt.authorization import AuthorizationManagementClient
credential = DefaultAzureCredential()
keyvault = "XXX"
subscription_id = "YYY"
group_name = "ZZZ"

authorization_client = AuthorizationManagementClient(credential, subscription_id)
print(authorization_client._doc_)   # doc is supposed to be dunder doc but your editor removes the underscores
dir(authorization_client)
etc.

Please document these classes for Python.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78323a2f-3b72-1e79-437e-47377e4684e0
* Version Independent ID: 283b912b-7797-92f1-e71b-c834358aa7f5
* Content: [Microsoft Azure SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-authorization-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/mgmt-authorization-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/mgmt-authorization-readme.md)
* Service: **authorization**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kashifkhan** [comment]
Thank you for the feedback @dzauzig . We will investigate and get back to you asap.

**Comment by Wzb123456789** [comment]
Hi @dzauzig First make sure you are using the latest version of azure-mgmt-authorization, and then try to use this example. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/authorization/azure-mgmt-authorization/generated_samples/get_permissions.py
