### ISSUE TITLE
Azure Python SDK returning 501 not implemented error when endpoint is incorrect entered with the table name

### ISSUE THREAD

**Issue by mahmoudsamy27** [Azure/azure-sdk-for-python#30653]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Azure Python SDK returning 501 not implemented error when endpoint is incorrect entered with the table name.

**To Reproduce**
credential = AzureNamedKeyCredential('storageaccountname', 'key')
  service = TableServiceClient(endpoint='https://storageaccountname.table.core.windows.net/tablename', credential=credential)
  client = service.get_table_client(table_name='tablename')
  entity = client.get_entity('key', 'rowkey')

**Expected behavior**
A meaning full error should describe the syntax error.

**Comment by YalinLi0312** [comment]
Hi @mahmoudsamy27 , thanks for contacting us! To better understand your issue, I have some questions:
-  did you create a table and used the real table name to url in your code? 
-  what's the "endpoint is incorrect" mean? The whole endpoint is incorrect or just the table name is incorrect?

Thanks

**Comment by mahmoudsamy27** [comment]
what's the package version, python version and os you are using?

- azsdk-python-data-tables/12.4.2 
what's the "endpoint is incorrect" mean? Is the account name in endpoint incorrect or the table name is incorrect?
- Both storage account name and table are correct, but I got the error when I passed the table name in the endpoint so it seems that the endpoint should have the account fqdn only without table name. 
do you mean the key in your test is in string "key"?
- No, the string key is for passing the access key. 
 
can you provide the stack trace after running the sample code?
n/a
