### ISSUE TITLE
Unclear documentation of function publish_telemetry

### ISSUE THREAD

**Issue by kleegrewec** [Azure/azure-sdk-for-python#30667]
From my perspective the documentation of function "publish_telemetry" is unclear. The description

`'Publish telemetry **from** a digital twin, which is then consumed by one or many destination endpoints (subscribers) defined under...' `

suggests that telemetry data is pushed out from the twin and not into it. Please change this to some more clear description.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b756d98f-aae2-0f34-be99-b5662f0b84dd
* Version Independent ID: 43320159-bbcf-2f6b-d8ba-11fc199e3029
* Content: [azure.digitaltwins.core.DigitalTwinsClient class](https://learn.microsoft.com/en-us/python/api/azure-digitaltwins-core/azure.digitaltwins.core.digitaltwinsclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-digitaltwins-core/azure.digitaltwins.core.DigitalTwinsClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-digitaltwins-core/azure.digitaltwins.core.DigitalTwinsClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by navba-MSFT** [comment]
@kleegrewec Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@kleegrewec The above PR has been filed and it is currently under review. Thanks again for your feedback on improving our docs.
