### ISSUE TITLE
Getting a Bad Request 400 Everytime i try to upload a file using ShareClient

### ISSUE THREAD

**Issue by yogansh-zvolv** [Azure/azure-sdk-for-python#30661]
I am using a function upload_file from the ShareClient. This function was working fine but suddenly has started returning an html response with error. The error is--
_______________________________________________________________________________________
azure.core.exceptions.HttpResponseError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd"><HTML><HEAD><TITLE>Bad Request</TITLE><META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD><BODY><h2>Bad Request - Invalid URL</h2><hr><p>HTTP Error 400. The request URL is invalid.</p></BODY></HTML>
_________________________________________________________________
Stack Trace --

  File "/usr/local/lib/python2.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer,
    return func(*args, **kwargs),
    **kwargs),
  File "/usr/local/lib/python2.7/site-packages/azure/storage/fileshare/_file_client.py", line 527, in upload_file,
  File "/usr/local/lib/python2.7/site-packages/azure/storage/fileshare/_file_client.py", line 94, in _upload_file_helper,
    process_storage_error(error),
  File "/usr/local/lib/python2.7/site-packages/azure/storage/fileshare/_shared/response_handlers.py", line 180, in process_storage_error,
    raise error
_________________________________________________________________

I searched a lot and found nothing around this on Azure docs. Can you help me and tell what exactly is wrong. I would really appreciate it. 
Note : Before 3 June I was able to upload files to the client server. Now suddenly I keep getting this error. Whenever I call the upload_file function.

**Comment by yogansh-zvolv** [comment]
Hi Kashif,

The library which I'm using is azure-storage-file-share 12.12.0.
The Python version is Python 2.7.17
OS is Linux
-----------------------------------------------------------------------------------
The things were working fine earlier. After 3rd June 2023 I started getting this error. Also the issue seems to be intermittent. it works for 1 or 2 files successfully uploads them but them suddenly throws a 400. I am also attaching the error message below.
--------------------------
Error Message From Service --
----------------------------------------------------------
azure.core.exceptions.HttpResponseError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd"><HTML><HEAD><TITLE>Bad Request</TITLE><META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD><BODY><h2>Bad Request - Invalid URL</h2><hr><p>HTTP Error 400. The request URL is invalid.</p></BODY></HTML>
---------------------------------------------------------------------

Please feel free to reach out to me for more information.

Thanks,
Yogansh
________________________________

**Comment by kashifkhan** [comment]
Thanks for the information @yogansh-zvolv . Just a heads up that we have stopped supporting py 2 and as a minimum require py 3.7 and higher. I'll be assigning this to a colleague who can assist better.

**Comment by yogansh-zvolv** [comment]
Hi,

Extremely Sorry for the delay in my response. The issue was resolved.

The issue was a bit weird. On Server a file was created with a "?" in its name which was causing the problem during the upload_file function of the Shareclient library. When i was going through the file directory i noticed one file had a name which appeared like this - 270623175151000000_?_0003.rcv' . I just removed this file from the directory and the solution was running fine.

I don't know how the file got created with this question mark and caused problem during upload. If you need more information please reach out to me.

Thanks,
Yogansh
________________________________
