### ISSUE TITLE
Region Configuration Mismatch After Maintenance

### ISSUE THREAD

**Issue by Nephdz** [Azure/azure-sdk-for-python#30673]
- **Package Name**:  azureml-sdk, MSAL
- **Package Version**:  1.43.0, 1.21.0
- **Operating System**: Ubuntu 18.04
- **Python Version**:  3.8.13

**Describe the bug**
I'm running a voila (0.2.16) app on Azure App Service plans and after a maintenance, the following error showed up.
![image](https://github.com/Azure/azure-sdk-for-python/assets/59887159/c084ddf7-593b-479a-b8fb-4ebbaef64d34)

I tried a downgrading the MSAL version since I was told the region is configured in that package but I haven't gotten any results. What is correct way to fix this warning and correctly configure the region?

**Expected behavior**
Correctly configured regions.

**Comment by kashifkhan** [comment]
Thank you for the feedback @Nephdz . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by achauhan-scc** [comment]
Closing as obsolete
