### ISSUE TITLE
'Profile' object has no attribute 'validate'

### ISSUE THREAD

**Issue by viranch** [Azure/azure-sdk-for-python#30686]
- **Package Name**: azure-mgmt-trafficmanager
- **Package Version**: 1.1.0b1
- **Operating System**: ArchLinux, CentOS, MacOS
- **Python Version**: 3.10.5

**Describe the bug**
When using azure-mgmt-trafficmanager==1.1.0b1 and trying to create a DNS record that is aliased to a traffic manager profile, it fails with the error in the title (full trace below). This is a new exception that does not occur in previous versions of the package (also as shown below).

**To Reproduce**
```
>>> from azure.mgmt.trafficmanager import __version__
>>> __version__
'1.1.0b1'
>>>
>>> from azure.identity import ClientSecretCredential
>>> from azure.mgmt.dns import DnsManagementClient
>>> from azure.mgmt.dns.models import RecordSet
>>> from azure.mgmt.trafficmanager.models import Profile
>>> client = DnsManagementClient(credential=ClientSecretCredential('asdf','asdf','asdf'),subscription_id='')
>>> params = RecordSet(target_resource=Profile(), ttl=300)
>>> client.record_sets.create_or_update('rg', 'example.com', 'www', 'CNAME', params)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test/env/lib/python3.10/site-packages/azure/mgmt/dns/v2018_05_01/operations/_record_sets_operations.py", line 201, in create_or_update
    body_content = self._serialize.body(parameters, 'RecordSet')
  File "/tmp/test/env/lib/python3.10/site-packages/msrest/serialization.py", line 628, in body
    errors = _recursive_validate(data_type, data_type, data)
  File "/tmp/test/env/lib/python3.10/site-packages/msrest/serialization.py", line 160, in _recursive_validate
    return data.validate()
  File "/tmp/test/env/lib/python3.10/site-packages/msrest/serialization.py", line 254, in validate
    validation_result += _recursive_validate(attr_name, attr_type, value)
  File "/tmp/test/env/lib/python3.10/site-packages/msrest/serialization.py", line 160, in _recursive_validate
    return data.validate()
AttributeError: 'Profile' object has no attribute 'validate'
>>>
```
This same exception happens even with valid credentials, resource group, subscription ID, profile parameters etc.

**Expected behavior**
Same as the behavior in previous versions of the package - below shows authentication failed due to dummy values, but no validation exception like the above:
```
>>> from azure.mgmt.trafficmanager import __version__
>>> __version__
'1.0.0'
>>>
>>> from azure.identity import ClientSecretCredential
>>> from azure.mgmt.dns import DnsManagementClient
>>> from azure.mgmt.dns.models import RecordSet
>>> from azure.mgmt.trafficmanager.models import Profile
>>> client = DnsManagementClient(credential=ClientSecretCredential('asdf','asdf','asdf'),subscription_id='')
>>> params = RecordSet(target_resource=Profile(), ttl=300)
>>> client.record_sets.create_or_update('rg', 'example.com', 'www', 'CNAME', params)
ClientSecretCredential.get_token failed: Authentication failed: Unable to get authority configuration for https://login.microsoftonline.com/asdf. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or
GUID is correct.
```

**Screenshots**
N/A

**Additional context**
None.

**Comment by catalinaperalta** [comment]
Thanks for reaching out @viranch! Looping in @msyyc to help investigate.

**Comment by msyyc** [comment]
Hi @viranch Which version of azure-mgmt-dns are you using? According to latest dns==8.1.0b1, [target_source](https://github.com/Azure/azure-sdk-for-python/blob/60f20f745c82bf8ba931018ecb03cfd46c1d5984/sdk/network/azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/models/_models_py3.py#L394) type shall be `SubResource` instead of model from traffic manager

**Comment by viranch** [comment]
@msyyc I am using azure-mgmt-dns==8.0.0.

Can you share the changelog that mentions this breaking change?

**Comment by msyyc** [comment]
I download [source code of 8.0.0](https://pypi.org/project/azure-mgmt-dns/8.0.0/#files) and find that the `target_source` type is still `SubResource`. Is there any context why you use model from other package here?
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/3874440f-5f59-4215-aedb-006f58e967a5)

**Comment by viranch** [comment]
It's intuitive to reference the profile object as target_resource. Why does it start breaking now? Why did the profile object lose the validate method?

**Comment by msyyc** [comment]
Not sure why it works before but it is not recommended way to write code like that. Users shall input correct type as declared in SDK code.

**Comment by viranch** [comment]
Where is that recommendation documented?

**Comment by msyyc** [comment]
You can see the [source code](https://github.com/Azure/azure-sdk-for-python/blob/60f20f745c82bf8ba931018ecb03cfd46c1d5984/sdk/network/azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/models/_models_py3.py#L394) or sample: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/network/azure-mgmt-dns/generated_samples/create_or_update_aaaa_recordset.py

**Comment by ross** [comment]
> Not sure why it works before but it is not recommended way to write code like that.

That'd still be a regression. If octoDNS was relying on that working then other things could be too. Safest bet would be to support the previous usage, optionally with a warning, even if it wasn't "recommended" since the release it's breaking in is a point release and not a major version.

**Comment by viranch** [comment]
> Not sure why it works before

@msyyc Looks like https://github.com/Azure/azure-sdk-for-python/pull/27557 switched over the underlying class from `msrest.serialization.Model` that had the [`validate` method](https://github.com/Azure/msrest-for-python/blob/master/msrest/serialization.py#L231) to the new (re)implementation of it within `azure-mgmt-trafficmanager` ([`_serialization.Model`](https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-trafficmanager_1.1.0b1/sdk/trafficmanager/azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/_serialization.py#L271)) that doesn't have the `validate` method.

See https://github.com/Azure/azure-sdk-for-python/pull/27557/files#diff-fec9506d179ea4380c62543f04d24fd3e336983b3b242cfc1f01ef0ba5b99decL172

Can we have the `validate` method added to `_serialization.Model` to fix this regression before the next stable non-beta release?

**Comment by msyyc** [comment]
@viranch Please try latest [azure-mgmt-dns==8.1.0b1](https://pypi.org/project/azure-mgmt-dns/8.1.0b1/) and I think it can work well with azure-mgmt-trafficmanager==1.1.0b1

**Comment by viranch** [comment]
Using `azure-mgmt-dns==8.1.0b1` works:

```
$ pip freeze | grep mgmt
azure-mgmt-core==1.4.0
azure-mgmt-dns==8.1.0b1
azure-mgmt-trafficmanager==1.1.0b1
$
$ cat test.py
from azure.identity import ClientSecretCredential
from azure.mgmt.dns import DnsManagementClient
from azure.mgmt.dns.models import RecordSet
from azure.mgmt.trafficmanager.models import Profile

client = DnsManagementClient(credential=ClientSecretCredential('asdf','asdf','asdf'),subscription_id='')
params = RecordSet(target_resource=Profile(), ttl=300)
client.record_sets.create_or_update('rg', 'example.com', 'www', 'CNAME', params)
$
$ python test.py
ClientSecretCredential.get_token failed: Authentication failed: Unable to get authority configuration for https://login.microsoftonline.com/asdf. Authority would typically be in a for
mat of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
```

No exception for `validate` method.

@msyyc Is there the supported version matrix documented anywhere? It shouldn't be left up to the user to guess which versions of various azure python packages will work well with each other.

**Comment by msyyc** [comment]
(1) We can't promise SDK can always work when users use it in wrong way
(2) There is no version matrix and we recommend users try to upgrade to the latest version 
(3) https://pypi.org/project/azure-mgmt-dns/8.1.0/ is released.
