### ISSUE TITLE
Can't Serialize and Deserialize Token Filters

### ISSUE THREAD

**Issue by dillon-ms** [Azure/azure-sdk-for-python#30691]
- **Package Name**: azure-search-documents
- **Package Version**:  11.3.0
- **Operating System**: Mac OS and Windows
- **Python Version**: 3.11.3

**Describe the bug**
Once a Search Index is serialized, the JSON it produces is not able to be deserialized, if it contains Token Filters. Attempting to deserialize the index JSON raises an exception.

**To Reproduce**
1. Create a search index that includes Token Filters using SDK classes.
2. Serialize the index.
3. Deserialize the index. 
```python

fields = [
    SimpleField(name="id",
                type=SearchFieldDataType.String, key=True),
    SearchableField(name="document_name",
                    type=SearchFieldDataType.String,
                    filterable=True,
                    analyzer_name="en.microsoft"),
    SearchableField(name="phonetic_ta4h",
                    collection=True,
                    index_analyzer_name="phonetic-analyzer",
                    search_analyzer_name="phonetic-analyzer"),
    SearchableField(name="ngram_ta4h",
                    collection=True,
                    index_analyzer_name="ngram-analyzer",
                    search_analyzer_name="ngram-analyzer"),
]

analyzers = [
    CustomAnalyzer(name="phonetic-analyzer", tokenizer_name="classic", token_filters=[
        "lowercase",
        "asciifolding",
        "phonetic_filter"
    ]),
    CustomAnalyzer(name="ngram-analyzer", tokenizer_name="classic", token_filters=[
        "lowercase",
        "asciifolding",
        "n-gram_filter"
    ])
]

token_filters = [
    PhoneticTokenFilter(
        name="phonetic_filter", encoder=PhoneticEncoder.DOUBLE_METAPHONE, replace_original_tokens=True),
    # NGramTokenFilterV2(name="n-gram_filter", min_gram=4, max_gram=6)
]

index = SearchIndex(
    name="my_index",
    fields=fields,
    scoring_profiles=[],
    analyzers=analyzers,
    token_filters=token_filters,
    cors_options=CorsOptions(
        allowed_origins=["*"], max_age_in_seconds=60)
)

serialized = index.serialize()
deserialized = SearchIndex.deserialize(serialized)
""" ^ raises exception
Exception has occurred: DeserializationError
("Unable to deserialize to object: type, KeyError: 'EdgeNGramTokenFilterV2'", KeyError('EdgeNGramTokenFilterV2'))
KeyError: 'EdgeNGramTokenFilterV2'

During handling of the above exception, another exception occurred:

  File "/Users/dillonhall/Documents/engagements/cvs/bug report/main.py", line 139, in simulate_cvs_index
    deserialized = SearchIndex.deserialize(serialized)
"""
```

**Expected behavior**
I expect the Deserialize method to return an identical object to the index which was originally serialized.

**Screenshots**
![Screenshot 2023-06-08 at 10 52 03 AM](https://github.com/Azure/azure-sdk-for-python/assets/112519793/5252d50c-04a0-48f6-9240-ee2689a39d84)

**Additional context**
We would like to create search indexes with the Python SDK, store the JSON files in a blob. Then deserialize them when needed.

Note from @seanytak:
It looks like the underlying issue is related to the deprecation of msrest which is still being referenced in the latest release version v11.3.0. On the latest main it looks like the serialization code has been updated to be part of the SDK itself, however there is no publicly released version with this change incorporated.

**Comment by xiangyan99** [comment]
The fix is merged and will be available in next release.
