### ISSUE TITLE
https://github.com/Azure-Samples/resource-manager-python-resources-and-groups points to nowhere

### ISSUE THREAD

**Issue by gambitcomminc** [Azure/azure-sdk-for-python#30705]
[[https://github.com/Azure-Samples/resource-manager-python-resources-and-groups points to nowhere]]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 235574af-54a7-fffb-9a63-f65814aa9f9d
* Version Independent ID: ff8553a6-c819-6cbd-4201-f1ce7c382fc0
* Content: [Azure Resources SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/resources?view=azure-python)
* Content Source: [docs-ref-services/latest/resources.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/resources.md)
* Service: **resources**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback.

Please open the issue in https://github.com/MicrosoftDocs/azure-docs-sdk-python repo.
