### ISSUE TITLE
expose x-ms-request-charge in HTTP response header when operating Cosmos DB with "azure.data.tables"

### ISSUE THREAD

**Issue by chshihMSFT** [Azure/azure-sdk-for-python#30717]
**Is your feature request related to a problem? Please describe.**
When communicating with Cosmos DB - Table API by [azure.data.tables](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/tables/azure-data-tables), it's not exposed "x-ms-request-charge" in the returned HTTP headers. This is important information for client-side to monitor how much throughput is consumed.

**Describe the solution you'd like**
[azure.data.tables](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/tables/azure-data-tables) now is the main API for users to deal with both "Cosmos DB - Table API" and "Storage - Table Service" data. But the throughput concept is applicable for Cosmos DB only. Can we have some mechanism to differentiate these two services while initiating connection, and return "x-ms-request-charge" in the afterward CRUD operations and its HTTP response headers accordingly?
ref - [Common Azure Cosmos DB REST response headers](https://learn.microsoft.com/en-us/rest/api/cosmos-db/common-cosmosdb-rest-response-headers)

**Additional context**
If we enable logging, we can only see these HTTP headers in the response:
```
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://<dbaccountname>.table.cosmos.azure.com:443/TableSample01'
Request method: 'POST'
Request headers:
    'Content-Type': 'application/json;odata=nometadata'
    'Content-Length': '234'
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': 'd9126191-06a6-11ee-8b5f-eb30f21d4a75'
    'x-ms-date': 'REDACTED'
    'Date': 'Fri, 09 Jun 2023 09:20:17 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.4.2 Python/3.10.7 (Windows-10-10.0.22621-SP0)'
    'Authorization': 'REDACTED'
A body is sent with the request
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ettable.table.cosmos.azure.com:443
DEBUG:urllib3.connectionpool:https://<dbaccountname>.table.cosmos.azure.com:443 "POST /TableSample01 HTTP/1.1" 201 None
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 201
Response headers:
    'Content-Type': 'application/json;odata=minimalmetadata'
    'Date': 'Fri, 09 Jun 2023 09:20:16 GMT'
    'ETag': 'W/"datetime'2023-06-09T09%3A20%3A17.3562888Z'"'
    'Location': 'REDACTED'
    'Transfer-Encoding': 'chunked'
```

**Comment by chshihMSFT** [comment]
Hi @YalinLi0312 ,

Thanks for your response. Yes, this is a feature request indeed.
Did a quick test in my env again, if I sent request to Table API gateway directly via Postman, there is nothing useful in HTTP response headers.
So I'm wondering if Cosmos DB Compute gateway of Table API will expose those HTTP response headers like NoSQL API.
Maybe we need to engage Cosmos DB - Table API component team and check internally.

![image](https://github.com/Azure/azure-sdk-for-python/assets/45855145/04290b79-7af4-4663-8540-2ed7aece61a1)

**Comment by YalinLi0312** [comment]
- I also checked our recording folder, don't find the header `x-ms-request-charge` exists in any response.
- You expect the header can reply in CRUD response, which CRUD you mean? The CRUD on `Tables` or `Entity`? This will help us to understand your issue.

**Comment by chshihMSFT** [comment]
Thanks @YalinLi0312 ,

The expected RU consumption tracking (via exposing x-ms-request-charge in HTTP response header) should be on data-plane level, which is the CRUD operation on entity, (insert entity, update entity, delete entity, query entity). control-plane RU tracking is not required, users won't (and shouldn't) modify their table settings very frequently in a short time. 

RU consumption is a basic but import concept in Cosmos DB, because we measure every consumed system resource (CPU, memory, IOPS) for data-plane requests in RU (Request Units), so it's more like a currency unit to tell customers their operation is expensive or not. With such information, Customers can track their API workload (with Application Insights or similar tools), as well as have better ideas to understand why they are receiving 429-throttling errors. Such as, it's because a few expensive requests exceed provisioned throughput, or a lot of requests flood in around the same time then consumed a bunch of RUs concurrently.

**Comment by YalinLi0312** [comment]
@chshihMSFT Thanks for the details, it helps us to understand the requirement. I'm talking with service team on the support, will update here.

**Comment by YalinLi0312** [comment]
After talking with service team, it's a feature request that service haven't supported yet. And there's no plan for it so far. Will close this issue.

**Comment by chshihMSFT** [comment]
Thanks for your clarification.
