### ISSUE TITLE
how to use synapse msi to get access token for an api (in scala) ? How to getAccess Token on Synapse Notebook using its managed identity

### ISSUE THREAD

**Issue by saravindit** [Azure/azure-sdk-for-python#30726]
Looking for help on How to getAccess Token on Synapse Notebook using its managed identity ?
For Scala we dont find any reference.
But for pyspark we found some reference but still getting this error
"ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
Exception occurred: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found."

from azure.identity import ManagedIdentityCredential
from azure.core.credentials import AccessToken

def get_access_token():
    try:
        # Create an instance of ManagedIdentityCredential
        credential = ManagedIdentityCredential()

        # Define the resource or scope for which you want to acquire the token
        resource = "https://example.com"

        # Obtain an access token
        token = credential.get_token(resource)

        # Access the access token value
        access_token = token.token

        print(f"Access token: {access_token}")
        return access_token

    except Exception as e:
        print(f"Exception occurred: {str(e)}")
        return None
        
Any help ?

**Comment by kashifkhan** [comment]
Hi @saravindit , can you provide us some more information about the python environment, OS, version of azure-identity you are using ?

**Comment by saravindit** [comment]
We are using in Azure synapse environment and we are running the notebook in synapse workspace. azure-identity 1.7.0. OS- windows 11
We actually need that to be implemented in Scala but trying to figure out in pyspark too .

**Comment by xiangyan99** [comment]
Thanks for the information. Unfortunately, azure-identity library does not work in synapse workspace.

You can refer https://learn.microsoft.com/en-us/azure/synapse-analytics/synapse-service-identity for more information.

**Comment by saravindit** [comment]
"/unresolve"

**Comment by xiangyan99** [comment]
Took offline.
