### ISSUE TITLE
user defined batch scoring script makes environment is required for mlflow models

### ISSUE THREAD

**Issue by uberj** [Azure/azure-sdk-for-python#30741]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.7.2
- **Operating System**: Linux
- **Python Version**: 3.8.16

**Describe the bug**
I'm using batch scoring to evaluate an mlflow model on a test set. I am trying to use a user defined scoring script in the batch deployment, but I get an error:
```
Errors:
[
  {
    "PropertyName": "ModelConfiguration.EnvironmentId",
    "ErrorMessage": "'Environment Id' must not be empty.",
    "ErrorCode": "ArgumentNullOrEmpty"
  }
]
```
I think the correct behavior should be to allow a custom scoring script, but still use the environment packged with the mlflow model.

**To Reproduce**
1. Try create a deployment with an existing mlflow model
2. Use a user defined batch scoring file
3. Do not specify an environment

**Expected behavior**
Deployment should use the conda env found in the packaged mlflow model and use the user defined scoring function.

**Additional context**
Currently, the only option to get prediction results is to use BatchOutputAction.AppendRow, but this creates a massive output file as it includes all the input fields. Using a user defined scoring function that omits the input data in the resulting csv seemed like the best way around this.

**Comment by kashifkhan** [comment]
Thank you for the feedback @uberj . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by hswang-wang** [comment]
Hi @uberj Thank you for your feedback. 

These are the scenarios we currently support for MLFLOW model batch deployment:
1. No Code model deployment - Neither scoring script nor environment is required
2. Custom model deployment -  Provide both custom scoring script and environment

In your case, you would need to specify an environment if you would like use a custom scoring script. 
Please let us know if you have any other questions.

**Comment by uberj** [comment]
One advantage of 1, is that invoking code doesn't need to understand what versions of libraries were packaged with. To bridge that functionality gap, in scenario 2, how could I set the environment knowing only the model (i.e. `<model-name>:<model-version>`)?

**Comment by hswang-wang** [comment]
@uberj Thank you for your reply.

We have a documentation about how to deploy a MLflow model to batch endpoint using a custom scoring script and that includes the guidance on creating an environment.
[Customizing MLflow models deployments with a scoring script](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-mlflow-batch?view=azureml-api-2&tabs=cli#customizing-mlflow-models-deployments-with-a-scoring-script)

You could create an environment from base image with conda.yaml. The conda.yaml is in the MLflow model and should have all packages needed to run the model and the custom scoring script.

If your model is already registered in the model registry, you could download/copy the conda.yaml file associated with your model by going to [Azure Machine Learning studio](https://ml.azure.com/) > Models > Select your model from the list > Artifacts. Open the root folder in the navigation and select the conda.yaml file listed. Click on Download or copy its content.

For the base image, it could be either a CPU or GPU, depending on your use case: 
mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04

Here's the script you could run to create an environment:

```
environment = Environment(
    name="batch-mlflow-xgboost", //Replace with your environment name
    conda_file="environment/conda.yaml", //Replace with your conda.yaml file path
    image="mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest", //Replace with your base image
)
```
Please let us know if you have any other questions.

**Comment by santiagxf** [comment]
Hi @uberj. Thanks for your feedback. We understand it would be handy to have AzureML build the environment the model needs and still indicate an scoring script. We might consider adding this in the feature. By the time being, if you indicate the scoring script you need to indicate the environment. The reason for that is that decision is that most of the time when you author an scoring script you introduce new code that typically require other libraries.

Again, we can consider adding this in the feature. In the meantime, the doc [Customizing MLflow models deployments with a scoring script](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-mlflow-batch?view=azureml-api-2&tabs=cli#customizing-mlflow-models-deployments-with-a-scoring-script) explains a simple way you can use to generate the environment from any MLflow model.

**Comment by uberj** [comment]
I appreciate the effort and information you have put into this issue, thanks! I have solved matching an inference environment to that of a model by using the following code:
```
    model_path = f'/tmp/model-download'
    model_name = "..."
    model_version = "..."
    client_aml.models.download(model_name, model_version, model_path)
    conda_env_path = os.path.join(model_path, model.name, "model/conda.yaml")
    with open(conda_env_path, "r") as fd:
        injected = fd.read().replace("- pip:\n", "- pip:\n  - azureml-core\n")

    injected_conda_env_path = os.path.join(model_path, model.name, "model/injected-conda.yaml")
    with open(injected_conda_env_path, "w+") as fd:
        fd.write(injected)

    environment = Environment(
        conda_file=injected_conda_env_path,
        image="mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest",
    )
```
This is a bit ugly as "azure-core" must be installed during batch inference, but it isn't necessarily used when the mlflow model is packaged.
