### ISSUE TITLE
How to call Azure Partner Center Rest API in my server

### ISSUE THREAD

**Issue by indumathyn** [Azure/azure-sdk-for-python#3074]
Dono how to use Azure Partner center rest api to fetch csp account billing info in my application.

am searching below url,but dono how to integrate,

https://apidocs.microsoft.com/services/partnercenterbilling#/

**Comment by lmazuel** [comment]
Hi @indumathyn 
This SDK is not Azure, and not handled by us. I suggest you click on support and ask questions directly there:
https://partner.microsoft.com/en-us/support/csp-support
