### ISSUE TITLE
Allow to specify the mount path in an Azure ML Job with SDK v2

### ISSUE THREAD

**Issue by sarah-wayve** [Azure/azure-sdk-for-python#30755]
**Is your feature request related to a problem? Please describe.**
When creating an Azure ML Job using the python sdk, I can't specify the path on the compute where I want my data asset to be mounted. This is an issue, as this functionality existed in sdk v1, and a lot of our pipeline code expects to find the data at a specific path on the compute.
In sdk v1, the mount path could be specified as follows:
```
dataset.as_mount(path_on_compute=<mount-path>)
```

**Describe the solution you'd like**
When creating an Azure ML Job, I would like to be able to specify the path on the compute where I want my data asset to be mounted. For example, in the Input class:
```
Input(type='uri_folder', path=<data-asset-path>, mode='ro_mount', path_on_compute=<mount-path>)
```

**Describe alternatives you've considered**
I can't think of an alternative.

**Comment by kashifkhan** [comment]
Thank you for the feedback @sarah-wayve . We will investigate and get back to you asap. 

cc @azureml-github

**Comment by sarah-wayve** [comment]
I was told about this workaround, in case anyone comes across the same problem:
```
job = command(...)
job.properties["properties[f"AZURE_ML_INPUT_PathOnCompute_{input_name}"] = desired_mount_path
```
