### ISSUE TITLE
Azure Partner Center SDK  - try Rest api result as 401

### ISSUE THREAD

**Issue by indumathyn** [Azure/azure-sdk-for-python#3079]
authentication_endpoint = 'https://login.windows.net/'
resource  = 'https://graph.windows.net/'
application_id = 'partner center app id'
application_secret = 'partner center secret id'
tenant = 'partner center Commerce ID'

context = adal.AuthenticationContext(authentication_endpoint + tenant)
token_response = context.acquire_token_with_client_credentials(resource, application_id, application_secret)
access_token = token_response.get('accessToken')
headers = {"Authorization": 'Bearer ' + access_token}
endpoint = "https://api.partnercenter.microsoft.com/v1/invoices"
json_output = requests.get(endpoint,headers=headers)

return json_output 

**Output**:

<Response [401]>

**Comment by lmazuel** [comment]
As I told you in https://github.com/Azure/azure-sdk-for-python/issues/3074, this API is not handled by our team.
Please ask for support in https://partner.microsoft.com/en-us/support/csp-support
Thank you,
