### ISSUE TITLE
Error in provided example

### ISSUE THREAD

**Issue by darkag** [Azure/azure-sdk-for-python#30802]
The provided example is wrong, it should be:

message = ServiceBusMessage(
"Hello World!!",
session_id="MySessionID",
application_properties={'data': 'custom_data'},
time_to_live=datetime.timedelta(seconds=30),
**subject**='MyLabel'
)

and not

message = ServiceBusMessage(
"Hello World!!",
session_id="MySessionID",
application_properties={'data': 'custom_data'},
time_to_live=datetime.timedelta(seconds=30),
**label**='MyLabel'
)

by the way, this kind of issue would not have existed if you didn't use two words for the same concept :
"subject
xref:Optional[[str](https://docs.python.org/3/library/stdtypes.html#str)]
The application specific subject, sometimes referred to as label."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c9b4162-c26e-9f86-4c66-b26449bbd077
* Version Independent ID: 1bb2b238-82fa-274b-a43d-55d5d1a72252
* Content: [azure.servicebus.ServiceBusMessage class](https://learn.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebusmessage?view=azure-python)
* Content Source: [docs-ref-autogen/azure-servicebus/azure.servicebus.ServiceBusMessage.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-servicebus/azure.servicebus.ServiceBusMessage.yml)
* Service: **service-bus**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by mccoyp** [comment]
Hi @darkag, thank you for opening an issue! I'll tag some folks who can take a look; we'll get back to you as soon as possible.

**Comment by kashifkhan** [comment]
Thank you @darkag . We have a linked PR that will address this
