### ISSUE TITLE
PurviewSharingClient does not list dettached received shares correctly

### ISSUE THREAD

**Issue by cic1988** [Azure/azure-sdk-for-python#30800]
- **azure-purview-sharing**: 
- **1.0.0b2**: 
- **MacOS 13.4**:
- **3.9.x**: 

**Describe the bug**
With the SPN with permission of Purview root collection admin and data reader role, and storage account blob contributor role, the received schare method does not return any results even though the results available.

**To Reproduce**
```
credential = ClientSecretCredential(
    tenant_id=tenant_id,
    client_id=client_id,
    client_secret=client_secret
)

reference_name="<reference_name>"

client = PurviewSharingClient(endpoint=endpoint, credential=credential)
attached = client.received_shares.list_attached(
    reference_name=reference_name
)
```

The output result is: "azure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'Not Found'"

**Expected behavior**
Return the available received shares.

**Comment by mccoyp** [comment]
Hi @cic1988, thank you for opening an issue! I'll tag some folks who should be able to help; we'll get back to you as soon as possible.

**Comment by msyyc** [comment]
(1) please check reference_name which has pattern like `"/subscriptions/4D8FD81D-431D-4B1D-B46C-C770CFC034FC/resourceGroups/contoso-rg/providers/Microsoft.Storage/storageAccounts/blobAccount"`.
(2) Please make sure your credential has relevant access to the resource
(3) Could you make sure whether the resource exist now?

**Comment by cic1988** [comment]
Hi @msyyc . Thanks for the heads up. (1) yes, the reference_name was given. To double-check this I have tested the API endpoint via Postman, which returns me a 200 Ok status code (2) the SPN used is granted Purview admin and storage account contributor role. This can be verified via the API as well. (3) the resource exists. I could see that the detached endpoint via the Purview instance returns correct value (once I am logged in via my User).

Here below is the sample response via the Chrome developer. I am very confused that whether it has to do with the SDK itself or the SPN. But given the admin permission, I highly doubt:

{
    "value": [
        {
            "properties": {
                "createdAt": "2023-06-14T06:37:19.4090524Z",
                "sharedAt": "2023-06-14T06:37:19.6238198Z",
                "displayName": "DATAPRODUCT002",
                "state": "Succeeded",
                "shareStatus": "Detached",
                "receiverEmail": "xxxxx",
                "senderName": "xxxxx",
                "senderEmail": "xxxxx",
                "senderTenantName": "xxxxx",
                "assetLocation": "westeurope",
                "assetStoreKind": "AdlsGen2Account"
            },
            "shareKind": "InPlace",
            "id": "<id>",
            "type": "ReceivedShare"
        }
    ]
}

**Comment by msyyc** [comment]
`Here below is the sample response via the Chrome developer.`
How do you get the response by Chrome developer. SDK is just tool to help users send/receive request/response in convenience. So if you can get response by REST API, you can do same thing with SDK. Please follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to print the log so you can check whether you set right parameters like you do with Chrome developer.
nit: endpoint shall be something like: `https://fake_account.share.purview.azure.com`

**Comment by cic1988** [comment]
Hi @mccoyp . I have one running purview instance to test. The above is only for comparison. I still have received from the SDK "Not found" error, which is unclear for me. Have you an idea? The SPN used is granted purview admin permission. Thanks.

**Comment by mccoyp** [comment]
Hi @cic1988, I would second @msyyc's suggestion to enable debug logging with the instructions from https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md. Detailed error logs could help us figure out why the SDK's response may differ from what you're seeing in Postman. I personally don't work with the Purview library, so I'll defer to the folks assigned to this issue for assistance.

**Comment by cic1988** [comment]
Hi both @mccoyp  @msyyc , thanks for your heads up.

In the debug log there i have seen that the error was an 404. I have changed then the old URL used, which is referred to the docs: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/purview/azure-purview-sharing/README.md

from https://<purview account>.purview.azure.com/ to https://<purview account>.purview.azure.com/share/. Then the SDK works. It seems to me a mismatch compared to the docs. Have you an idea whether my instance has potentially other setup?
