### ISSUE TITLE
Invalid channel number received

### ISSUE THREAD

**Issue by phil-aurecon** [Azure/azure-sdk-for-python#30815]
package name: azure-eventhub
package version:  "5.11.2"
operating system:  Linux 8d29b3f7f5b6 5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 GNU/Linux
python version: 3.10

**Describe the bug**

This is not likely a bug and is more likely a problem with the way we are creating and close EventHubProducerClient instances. Apologies if this should be posted elsewhere.

We are seeing the error 'Invalid channel number received' when publishing to an event hub.

We have a set of 4 EventHubProducerClient which operate in a single thread.
They each sleep for a short period, check if there are any messages on a queue and then publish those messages.
We are creating a new EventHubProducerClient on each iteration.
We are not using buffered mode.
We are using the AMQP transport type (default)

**To Reproduce**
We are not certain on how to reproduce.
This problem appears to happen if our application runs for a significant period - 24-48 hours.
Initially we wont see these errors but eventually we do.

**Comment by annatisch** [comment]
Thanks @phil-aurecon!
We really appreciate the issue report!
This is definitely an error message we have seen before - though it's a very low-level one that basically means the value of a single incoming byte was not as expected, which could have a wide variety of causes!
@kashifkhan - I think you've already done some digging on this one, though maybe that was in the context of Service Bus?

@phil-aurecon, a couple of follow up questions,
When the errors kick in after that initial 24-48 period, what behaviour do you start to see? Are the errors random and intermittent such that events are still eventually being sent, but performance is downgraded? Or do they become constant and effectively bring the application to a halt?
We deployed a new AMQP transport in 5.11 back in January - does that seem to correlate with when these errors began? Or has it been more recent than that?
Last question, when you say "sleep for a short period", are we talking in the order of seconds? Minutes? Tens of minutes?

Thanks again for the details! Hopefully we can get a resolution for you soon :)

**Comment by kashifkhan** [comment]
Hi @annatisch, we have definitely seen these errors before. In the context of Service Bus these were occurring when a large message that was incorrectly put together was missing an id, which would cause the server to issue a disconnect, leading to this error. I wonder if the same is happening with Event Hub where there is a period of inactivity and after reaching the limit a disconnect is issued by the service. I am currently trying to see what the best way is to fix this :)
