### ISSUE TITLE
[azure.mgmt.network] Add implementation for `az network vnet subnet list-available-ips`

### ISSUE THREAD

**Issue by heyjustyn** [Azure/azure-sdk-for-python#30822]
**Is your feature request related to a problem? Please describe.**
`azure-cli` has a command [`az network vnet subnet list-available-ips`](https://learn.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-list-available-ips), but the Azure SDK for Python doesn't.

**Describe the solution you'd like**
Add an implementation for this in [`SubnetsOperations Class`](https://learn.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2022_05_01.operations.subnetsoperations?view=azure-python).

**Describe alternatives you've considered**
I think my only alternative is to use the method [`virtual_networks.check_ip_address_availability`](https://learn.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.v2022_05_01.operations.virtualnetworksoperations?view=azure-python#azure-mgmt-network-v2022-05-01-operations-virtualnetworksoperations-check-ip-address-availability)?  If I set the parameter `ip_address` to an IP within the subnet, it seems to return available IPs within that subnet.

**Additional context**
N/A

**Comment by msyyc** [comment]
Hi, according to your context, the issue is more related with the usage problem of CLI in specific scenario other than SDK issue. You can raise issue in https://github.com/Azure/azure-cli/issues to seek help from CLI team.

**Comment by heyjustyn** [comment]
/unresolve

@msyyc sorry if my description was confusing. This is not a question on how to use Azure CLI.

My request is to bring the Azure SDK for Python to parity with Azure CLI by adding a function that is equivalent to [az network vnet subnet list-available-ips](https://learn.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-list-available-ips) into Azure SDK for Python.

**Comment by navba-MSFT** [comment]
Adding service team to look into this.

**Comment by msyyc** [comment]
Hi @heyjustyn, Azure CLI bases on Python SDK so I look through [CLI source code](https://github.com/Azure/azure-cli/blob/0982e1c02d64d3c50d199e83593eeb414133458f/src/azure-cli/azure/cli/command_modules/network/custom.py#L5850-L5869) and try to find how they use SDK API. Please try the following code:
```python
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.identity import DefaultAzureCredential
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.network.models import Subnet

"""
# PREREQUISITES
    pip install azure-identity
    pip install azure-mgmt-network
# USAGE
    python subnet_get.py

    Before run the sample, please set the values of the client ID, tenant ID and client secret
    of the AAD application as environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID,
    AZURE_CLIENT_SECRET. For more info about how to get the value, please see:
    https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal
"""


def main():
    client = NetworkManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id="subid",
    )

    subnet: Subnet = client.subnets.get(
        resource_group_name="subnet-test",
        virtual_network_name="vnetname",
        subnet_name="subnet1",
    )
    try:
        address_prefix = subnet.address_prefixes[0]
    except KeyError:
        address_prefix = subnet.address_prefix
    start_ip = address_prefix.split("/")[0]

    result = client.virtual_networks.check_ip_address_availability(
        resource_group_name="subnet-test",
        virtual_network_name="vnetname",
        ip_address=start_ip,
    )
    for item in result:
        print(item)


# x-ms-original-file: specification/network/resource-manager/Microsoft.Network/stable/2022-11-01/examples/SubnetGet.json
if __name__ == "__main__":
    main()
```

**Comment by heyjustyn** [comment]
@msyyc Thank your for looking into how it is implemented in the CLI source code. 

The provided code will print IP addresses with the modifications below, but sample code isn't equivalent to the CLI source code because it isn't calling [`CheckIpAddress`](https://github.com/Azure/azure-cli/blob/0982e1c02d64d3c50d199e83593eeb414133458f/src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/_check_ip_address.py#L17) right?

```python
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.identity import DefaultAzureCredential
from azure.identity import AzureCliCredential
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.network.models import Subnet, IPAddressAvailabilityResult

"""
# PREREQUISITES
    pip install azure-identity
    pip install azure-mgmt-network
# USAGE
    python subnet_get.py

    Before run the sample, please set the values of the client ID, tenant ID and client secret
    of the AAD application as environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID,
    AZURE_CLIENT_SECRET. For more info about how to get the value, please see:
    https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal
"""


def main():
    subscription_id="<replace-with-value>"
    vnet_resource_group_name="<replace-with-value>"
    virtual_network_name="<replace-with-value>"
    subnet_name="<replace-with-value>"

    client = NetworkManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id=subscription_id,
    )

    subnet: Subnet = client.subnets.get(
        resource_group_name=vnet_resource_group_name,
        virtual_network_name=virtual_network_name,
        subnet_name=subnet_name,
    )

    if subnet.address_prefixes != None:
      try:
        address_prefix = subnet.address_prefixes[0]
      except KeyError:
        address_prefix = subnet.address_prefix
    else:
       address_prefix = subnet.address_prefix
    start_ip = address_prefix.split("/")[0]

    result: IPAddressAvailabilityResult = client.virtual_networks.check_ip_address_availability(
        resource_group_name=vnet_resource_group_name,
        virtual_network_name=virtual_network_name,
        ip_address=start_ip,
    )
    for item in result.available_ip_addresses:
        print(item)


# x-ms-original-file: specification/network/resource-manager/Microsoft.Network/stable/2022-11-01/examples/SubnetGet.json
if __name__ == "__main__":
    main()
```

My feature request is to have a new method added to Azure SDK for Python. The new method would be similar to the method `subnet_list_available_ips` in the CLI source code, but made available in the SDK. Will the team accept this feature request or deny it?

**Comment by msyyc** [comment]
SDK is generated automatically with swagger. So SDK's API is one to one to swagger. While CLI not,some CLI code is handwritten so it will use set of SDK API to help users do something in convenience. So I am afraid SDK can't do the same thing like CLI.

**Comment by heyjustyn** [comment]
/unresolve 

@msyyc thank you for the clarification. Which repository is for the SDK API? I would like to submit a feature request there and reference this issue.

**Comment by msyyc** [comment]
@heyjustyn That makes sense. Once service team define this kind of REST API, SDK team will release a new version to support it. Please open an issue in https://github.com/Azure/azure-rest-api-specs/issues with detailed context and mark `feature-request` label
