### ISSUE TITLE
Incrrect link for https://learn.microsoft.com/en-us/python/api/overview/azure/monitoring/management

### ISSUE THREAD

**Issue by GrannyProgramming** [Azure/azure-sdk-for-python#30835]
When following hyperlink to next page it gives error 404 for the link https://learn.microsoft.com/en-us/python/api/overview/azure/monitoring/management

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cab65a33-b8b2-5380-7231-adfb0732cdf4
* Version Independent ID: 4a83acbb-e203-216a-4d86-5a98f5e95d47
* Content: [Azure Monitor SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/monitor?view=azure-python)
* Content Source: [docs-ref-services/latest/monitor.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/monitor.md)
* Service: **monitor**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by pvaneck** [comment]
Thanks for the feedback! Looks like that page needs an update overall. I will add this to my to-do list, as it's not even mentioning anything about monitor query and ingestion.

I believe the correct link for that would probably be: https://learn.microsoft.com/python/api/overview/azure/mgmt-monitor-readme

**Comment by pvaneck** [comment]
Updated in https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1762
