### ISSUE TITLE
Dataset registered for collected inference data has wrong data types

### ISSUE THREAD

**Issue by waqassiddiqi** [Azure/azure-sdk-for-python#30844]
- **Package Name**: azureml-monitoring
- **Package Version**:  0.1.0a21
- **Operating System**: linux
- **Python Version**:  3.7

**Describe the bug**
Data collection is enabled for a model deployed using Azure ML SDK v1, which is being collected fine as csv files & also registered as tabular dataset in Azure ML workspace. However, the issue is when this dataset was registered, it completely messed up with the data types. 

**To Reproduce**
1. Deploy a registered model on Kubernetes with model data collection enabled e.g.
```
deployment_config = AksWebservice.deploy_configuration(... collect_model_data=True)
```
2. In scoring script use `ModelDataCollector` to collect inference data
```
def init():
    global feature_set, inputs_dc
    ....
    dc_columns = feature_set.columns.values.tolist()
    dc_columns.append('score')
    inputs_dc = ModelDataCollector('model-v1', designation="inputs", feature_names=dc_columns)

def run(request):
    ....
    X["score"] = y_pred # X is pandas dataframe, y_pred is ML scrore
    inputs_dc.collect(X)
    ....
```

**Expected behavior**
Expectation was registered dataset to have same datatypes pandas dataframe had.

**Additional context**
Looks like the reason this lies in how collected data is saved as csv files and types are auto inferred on reading.

**Comment by pvaneck** [comment]
Hey, thanks for the input. It seems like `azureml-monitoring` package is quite old and seemingly unmaintained, so I'm uncertain if this issue will be addressed if it does require a bug fix. 

@luigiw, @azureml-github, can you provide insight on this, and shed some light on the monitoring plans for the v2 ML SDK?

**Comment by ahughes-msft** [comment]
Hi @waqassiddiqi 

The `azureml-monitoring` package is for data collection with the SDK v1. It is currently unmaintained. 

The recommended approach for inference data collection is to use the data collection package `azureml-ai-monitoring` ([pypi page](https://pypi.org/project/azureml-ai-monitoring/)) and deploy your model with the SDK v2. Documentation on how to do so can be found [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-collect-production-data?view=azureml-api-2&tabs=azure-cli).
