### ISSUE TITLE
Bad import of RecoveryServicesBackupClient in azure_rm_common.py

### ISSUE THREAD

**Issue by dzauzig** [Azure/azure-sdk-for-python#30857]
- **Package Name**:  plugins/module_utils/azure_rm_common.py (from https://github.com/ansible-collections/azure/)
- **Package Version**:  v1.16.0 (https://github.com/ansible-collections/azure/commit/931d566b3ae1c2d0f395a6c5c3d07b35c4ff6f04)
- **Operating System**: Linux (in docker container with base image python:3.9.10)
- **Python Version**:  3.9.10

**Describe the bug**
In azure_rm_common.py, line 275, the import statement is wrong.
    from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
Should be:
    from azure.mgmt.recoveryservicesbackup.activestamp import RecoveryServicesBackupClient
Refer to documentation at: https://pypi.org/project/azure-mgmt-recoveryservicesbackup/

This results in the following error message:

Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_roleassignment_payload_1b15a2fs/ansible_azure.azcollection.azure_rm_roleassignment_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 275, in <module>
    from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.9/site-packages/azure/mgmt/recoveryservicesbackup/__init__.py)

**To Reproduce**
1.  Create Docker container "FROM python:3.9.10"
2. Import the following Azure packages:
    azure-cli==2.49.0
    azure-mgmt-network==23.1.0
    azure-storage-blob==12.16.0
    azure-mgmt-automation==1.0.0
3. Install ansible and the azure collection for ansible
    ansible-galaxy collection install azure.azcollection --force
4. Run ansible playbook calling this module:
    azure.azcollection.azure_rm_roleassignment: 

**Expected behavior**
Uh. Ansible should not crash on Azure bug.

**Screenshots**

**Additional context**
This is an obvious bug and easy to fix. It would be very much appreciated if you could expedite this fix.

**Comment by pvaneck** [comment]
Hey @dzauzig, seems like the best course of action is to open an issue in https://github.com/ansible-collections/azure instead of here since the change is needed in that repo. From a cursory look, it appears a [requirements-azure.txt](https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt) file is provided with pinned versions that are likely needed for the script to properly work. Might be worth a shot to see if you can get by with those pinned dependencies.
