### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by adankert70** [Azure/azure-sdk-for-python#30855]
You do not specify what to "import" to get the examples working. No need to be so secretive about it!
Also, a complete code example would be helpfull.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6eacc65c-8d34-8fd6-cf1f-98ac3ed7ebd1
* Version Independent ID: 9d6d5c4e-8e9d-8646-4ec9-c2877d0fbd9f
* Content: [Azure Azure Digital Twins Core client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/digitaltwins-core-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/digitaltwins-core-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/digitaltwins-core-readme.md)
* Service: **digitaltwins**
* GitHub Login: @johngallardo
* Microsoft Alias: **jgalla**

**Comment by navba-MSFT** [comment]
@adankert70 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
