### ISSUE TITLE
Add 'environment_variables' arguments to ContainerInstanceManagementClient.container_groups.begin_start()

### ISSUE THREAD

**Issue by eses-wk** [Azure/azure-sdk-for-python#30866]
**Is your feature request related to a problem? Please describe.**
I am trying to start a task-based container instance (within an Azure Trigger Function) that I previously deployed on Azure. However, I realize I cannot add env var when I start the container run with```ContainerInstanceManagementClient.container_groups.begin_start()```

[see docs](https://learn.microsoft.com/en-us/python/api/azure-mgmt-containerinstance/azure.mgmt.containerinstance.operations.containergroupsoperations?view=azure-python#azure-mgmt-containerinstance-operations-containergroupsoperations-begin-start)

This limits the capability for me to customize each container run with additional flexibility. This issue should apply to anyone who has the need to programmatically start a container instance with the Azure Python SDK.

**Describe the solution you'd like**
Add 'environment_variables' arguments to ```ContainerInstanceManagementClient.container_groups.begin_start()```, so that environment variables can be assigned to the container upon each run. Other Container settings (e.g. memory_in_gb, cpu) can also be added for more flexibility.

Ideally, the solution should look like this

```python

env_var1 = EnvironmentVariable(name='ENV_NAME1', value='ENV_VALUE1')
env_var2 = EnvironmentVariable(name='ENV_NAME2', value='ENV_VALUE2')

client = ContainerInstanceManagementClient(
    credential=DefaultAzureCredential(),
    subscription_id=os.environ["AZURE_SUBSCRIPTION_ID"])
    
response = client.container_groups.begin_start(
    resource_group_name=os.environ["AZURE_RESOURCE_GRP_NAME"],
    container_group_name=os.environ["AZURE_CONTAINER_GRP_NAME"],
    environment_variables=[env_var1,env_var2]
    ).result()
logging.info('Cantainer Run: SUCCESSFUL')

```

**Describe alternatives you've considered**
I learned that there are ways to set up environment variables for a task-based container, however, it requires users to **create a new Container Group** each run, **which takes a lot of time and requires feeding in all config of the container** each time.
https://learn.microsoft.com/en-us/python/api/overview/azure/container-instance?view=azure-python#create-task-based-container-group

**Additional context**
N/A

**Comment by pvaneck** [comment]
Hey, thanks for the input. Seems like this is something that the ARM API would need to account for when starting the container group. I'll let @msyyc or someone else from the mgmt team chime in with some guidance or insights on the feasibility of this feature request.

**Comment by msyyc** [comment]
Hi @eses-wk, Python SDK is generated automatically with swagger. Unfortunately, the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/89e91a02e7cf20da48bb84c34eda694faed4dc5c/specification/containerinstance/resource-manager/Microsoft.ContainerInstance/stable/2023-05-01/containerInstance.json#L392-L415) of `ContainerInstanceManagementClient.container_groups.begin_start()` doesn't accept environment variables. The only method is **update** the existing container groups like:
```python
...
# update evnironment variables for each container under the container group
env_var1 = EnvironmentVariable(name='ENV_NAME1', value='ENV_VALUE1')
env_var2 = EnvironmentVariable(name='ENV_NAME2', value='ENV_VALUE2')

container_group = client.container_groups.get(resource_group_name="XXX", container_group_name="XXX")
for container in container_group.containers:
    container.environment_variables = [env_var1, env_var2]
container_group_parameters = client.container_groups.begin_create_or_update(
    resource_group_name="",
    container_group_name="",
    parameters=container_group
).result()

...
```

It `update` (not `create`) the existing container group so it shall faster than `create`. If you still want that `begin_start` can accept environment_variables, please open issue in https://github.com/Azure/azure-rest-api-specs/issues. Once swagger adds the feature, Python SDK can release a new version to support it.

**Comment by eses-wk** [comment]
@msyyc your recommendation works great for me! 

Just pointing out one typo: ```parameters``` attribute in the ```begin_create_or_update()``` should be ```container_group```. Referring to [the doc](https://learn.microsoft.com/en-us/python/api/azure-mgmt-containerinstance/azure.mgmt.containerinstance.operations.containergroupsoperations?view=azure-python#azure-mgmt-containerinstance-operations-containergroupsoperations-begin-create-or-update)

For others, you may check out [this doc](https://learn.microsoft.com/en-us/python/api/azure-mgmt-containerinstance/azure.mgmt.containerinstance.models.container?view=azure-python) to learn about what other container settings can be changed

Closing this issue for now.
