### ISSUE TITLE
Support Multi Tenant Auth with DAC - Workload Identity

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-python#30863]
Currently, DAC reads in tenant ID for Workload Identity from env only, it needs to honour the tenant ID supplied in code options to support multi tenant auth.

<img width="1073" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/5430778/7e6d4c7a-6a46-4025-a135-304864203e13">

The code that needs to be updated to support tenant ID from code options:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/default.py#L152

**Comment by xiangyan99** [comment]
#30861
