### ISSUE TITLE
Purview Sharing Readme and Samples Issues

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#30878]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#create-sent-share-invitation):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/4446f7e1-ba19-4aa2-a96e-dd59de955098)

**Reason1**:
AttributeError: 'dict' object has no attribute 'result'

**Suggestion**:
Update to
```
created_invitation = json.dumps(invitation_request)
print(created_invitation)
```

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#using-azure-active-directory):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/48be16e8-e25b-4493-a3b4-4c38896f0c98)

**Suggestion**:
Update to `"https://<my-account-name>.purview.azure.com/share"`

3.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#list-received-shares):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/42d652bb-d632-4850-974a-12861e513eba)

**Reason**:
`list_detached_response` is an iterator.

**Suggestion**:
Update to
```
for list_response in list_detached_response:
    print(list_response)
```

4.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#attach-a-received-share):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/2d1396d0-09cc-4eea-b218-7d87fa283047)

**Reason**:
ReceivedSharesOperations.begin_create_or_replace() missing 1 required positional argument: 'received_share'

**Suggestion**:
Update to `received_share=received_share`

5.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#get-received-share):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/c95cbd44-62ae-419e-8c3b-d830ce3a1aa9)

**Reason1**:
TypeError: the JSON object must be str, bytes or bytearray, not ItemPaged

**Suggestion**:
Update to
`
received_share = next(x for x in list_detached_response)
`

**Reason2**:
TypeError: the JSON object must be str, bytes or bytearray, not dict

**Suggestion**:
Update to
`
retrieved_share = json.dumps(get_share_response)
`

6.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#list-attached-shares):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/78c5c101-96b1-427d-8b88-ec965fffb668)

**Reason**:
`list_attached_response` is an iterator.

**Suggestion**:
Update to
```
for list_response in list_attached_response:
    print(list_response)
```

7.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/purview/azure-purview-sharing/samples/sent_shares_examples.py#L78):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/d9a39fb9-c436-4bb5-8822-e89694156a0a)

**Reason**:
KeyError: 'properties.artifact.storeReference.referenceName'

**Suggestion**:
Update to
`
str(sent_share["properties"]["artifact"]["storeReference"]["referenceName"])
`

@rohit-ganguly, @lmazuel, @iscai-msft for notification.

**Comment by ai-naymul** [comment]
Hey @rohit-ganguly , I would love to work on this , may I?

**Comment by cic1988** [comment]
Hi @ChenxiJiang333 . Just an off-topic question: does the list_detached() work for you? By me the result is always an empty array.

**Comment by ChenxiJiang333** [comment]
> Hi @ChenxiJiang333 . Just an off-topic question: does the list_detached() work for you? By me the result is always an empty array.

You can create a new share under your purview account through this [document](https://learn.microsoft.com/en-us/azure/purview/how-to-share-data?tabs=azure-portal), please have a try.

**Comment by SaurabhSharma-MSFT** [comment]
@ChenxiJiang333 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

**Comment by ChenxiJiang333** [comment]
> @ChenxiJiang333 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

Hi, I have reviewed your PR. I need to apologize if there's something I didn't express well. 

1. This [line](https://github.com/Azure/azure-sdk-for-python/pull/31005/files#diff-cc963273bae5f2c84997173fa0ddf423c01ed7ae6f77c3925da2e249115c0aa1R169) should be deleted either, for that what the method `create_invitation` returns is a dict object already. The whole code is better to updated like this:

```
invitation_request = client.sent_shares.create_invitation(
    sent_share_id=str(sent_share_id),
    sent_share_invitation_id=str(sent_share_invitation_id),
    sent_share_invitation=invitation)

created_invitation = json.dumps(invitation_request)
print(created_invitation)
```

2. Issue4 still not fixed, new error occurs: `TypeError: dumps() missing 1 required positional argument: 'obj'`. The code [here](https://github.com/Azure/azure-sdk-for-python/pull/31005/files#diff-cc963273bae5f2c84997173fa0ddf423c01ed7ae6f77c3925da2e249115c0aa1R248) should be updated like this:

```
update_request = client.received_shares.begin_create_or_replace(
    received_share['id'],
    content_type="application/json",
    received_share=received_share)
```

Please review and fix.

**Comment by ChenxiJiang333** [comment]
@SaurabhSharma-MSFT

**Comment by SaurabhSharma-MSFT** [comment]
@ChenxiJiang333 Thanks the feedback. I have updated the PR with the suggested changes.  Please let me know if you need anything else. Thanks

**Comment by ChenxiJiang333** [comment]
@SaurabhSharma-MSFT This update works well. I will close this issue. Thanks.
