### ISSUE TITLE
Communication Rooms Readme issues

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#30875]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-rooms#create-a-room), [link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-rooms#add-or-update-participants-in-a-room):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/050a837e-1494-4b58-b0c8-48ff86734128)

**Reason2**:
TypeError: 'CommunicationUserIdentifier' object is not subscriptable.
TypeError: RoomParticipant.__init__() takes 2 positional arguments but 3 were given.

**Suggestion1**:
Add code `from dateutil.relativedelta import relativedelta`

**Suggestion2**:
Update code to
```
participants.append(RoomParticipant(communication_identifier=CommunicationUserIdentifier("<ACS User MRI identity 1>")))
participants.append(RoomParticipant(communication_identifier=CommunicationUserIdentifier("<ACS User MRI identity 2>"), role=ParticipantRole.CONSUMER))
participants.append(RoomParticipant(communication_identifier=CommunicationUserIdentifier("<ACS User MRI identity 3>"), role=ParticipantRole.PRESENTER))
```

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-rooms#list-participants):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/33c76f7a-5cdc-43a0-b1c4-779c011cd361)

**Reason**:
 name "rooms _client" is not defined
**Suggestion**:
Update code to `client.list_participants(room_id="id of the room to list participants")`

3.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-rooms#remove-participants):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/d07c1ac8-8c22-4bbc-9811-f8d09e628bf8)

**Suggestion**:
Update code to `room_id="id of the room to remove participants"`

@rohit-ganguly, @lmazuel, @mayurid, @alexokun for notification.

**Comment by v-xuto** [comment]
@turalf Regarding this issue, what is the current progress?

**Comment by v-xuto** [comment]
Close this issue, because PR https://github.com/Azure/azure-sdk-for-python/pull/32092 merged.
