### ISSUE TITLE
Cosmos Sample Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#30876]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/examples_async.py#L105), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/document_management_async.py#L97), [link3](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/index_management_async.py#L122), [link4](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/index_management_async.py#L381):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/6a286e8b-ac52-4175-a13c-0a7f4e792739)

**Reason**:
TypeError: ClientSession._request() got an unexpected keyword argument 'enable_cross_partition_query'

**Tracking the issue**:
`enableCrossPartitionQuery`'s vaule is decided by argument `partition_key`  in async client.

**Suggestion**:
Delete code or update it to
`
partition_key=None
`

@rohit-ganguly, @lmazuel, @kyle-patterson, @KrzysztofCwalina, @annatisch for notification.

**Comment by simorenoh** [comment]
Changes have been merged, thank you!
