### ISSUE TITLE
[azure-core] error happened if next_link contains `{`

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#30900]
This issue is derived from https://portal.microsofticm.com/imp/v3/incidents/details/401204018/home. According to log, error happens here: https://github.com/Azure/azure-sdk-for-python/blob/4bbd687f25bd94adee57923cea42cfa9687260df/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L94

I can reproduce error with following code (sensitive info has been concealed:
```python
def _format_url_section(template, **kwargs):
    """String format the template with the kwargs, auto-skip sections of the template that are NOT in the kwargs.

    By default in Python, "format" will raise a KeyError if a template element is not found. Here the section between
    the slashes will be removed from the template instead.

    This is used for API like Storage, where when Swagger has template section not defined as parameter.

    :param str template: a string template to fill
    :param dict[str,str] kwargs: Template values as string
    :rtype: str
    :returns: Template completed
    """
    components = template.split("/")
    while components:
        try:
            return template.format(**kwargs)
        except KeyError as key:
            formatted_components = template.split("/")
            components = [c for c in formatted_components if "{{{}}}".format(key.args[0]) not in c]
            template = "/".join(components)


next_link = "https://management.azure.com/subscriptions/000000000000000/resourceGroups/resourceGroupName/providers/Microsoft.Network/dnsForwardingRulesets/XXX/virtualNetworkLinks?$skipToken=%5b{\"token\"%3a\"%2bRID%3a~kIByAPZ5oYKeSh8AAAAAAA%3d%3d%23RT%3a1%23TRC%3a100%23RTD%3aZ4EDKE9HD3IUT33r7gFKBXdqc3V2000000000000000000000000000000000000000000000000000000000%3d%3d%23ISV%3a2%23IEO%3a65567%23QCF%3a8%23FPC%3aAgF7fXsCAD28fSgAcgqA%2f5%2f2I0D%2ff307%2bv8RQOP%2bIUDK%2fxJA%2f%2b38%2fxJA%2f5f9%2fxJAH5gIAA%3d%3d\"%2c\"range\"%3a{\"min\"%3a\"\"%2c\"max\"%3a\"FF\"}}%5d&api-version=2022-07-01"

print(_format_url_section(next_link))
```

**Additional Context** 
1. related swagger definition: https://github.com/Azure/azure-rest-api-specs/blob/d8fbbdf15d10f5c708c4cc4a795b3df3a24c6a26/specification/dnsresolver/resource-manager/Microsoft.Network/stable/2022-07-01/dnsresolver.json#L1644-L1667
2. related SDK API: https://github.com/Azure/azure-sdk-for-python/blob/4bbd687f25bd94adee57923cea42cfa9687260df/sdk/dnsresolver/azure-mgmt-dnsresolver/azure/mgmt/dnsresolver/operations/_virtual_network_links_operations.py#L1014-L1038

**Comment by msyyc** [comment]
The root cause is that DNS server service returns next_link that contains `{}` which is very different common type like [here](https://github.com/Azure/azure-sdk-for-python/blob/4bbd687f25bd94adee57923cea42cfa9687260df/sdk/ml/azure-ai-ml/tests/recordings/feature_set/e2etests/test_feature_set.pyTestFeatureSettest_list_materialization_jobs.json#L2246)

**Comment by lmazuel** [comment]
With the given url, I get that error:
```
>               return template.format(**kwargs)
E               ValueError: unexpected '{' in field name

azure/core/pipeline/transport/_base.py:94: ValueError
```

We didn't protect for a url that would contains culry braces, and Python thinks they are un-replaced template parameters.

**Comment by lmazuel** [comment]
Closing in favor of https://github.com/Azure/autorest.python/issues/1984
This is not an azure-core issue
