### ISSUE TITLE
Azure Container App Support for Managed Identity

### ISSUE THREAD

**Issue by miztiik** [Azure/azure-sdk-for-python#30910]
[This page](https://learn.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#managed-identity-support) does not list "Azure Container Apps" as supported service for managed identity. But this page https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=portal%2Cpython implies that it is indeed supported. Which of them is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13bfe6a5-7920-bc4f-1604-403a406bc4dc
* Version Independent ID: 4ac2e58d-78a8-0675-284c-3df6c9cab28e
* Content: [Azure Identity client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#authenticating-with-defaultazurecredential)
* Content Source: [docs-ref-services/latest/identity-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/identity-readme.md)
* Service: **identity**
* GitHub Login: @pvaneck
* Microsoft Alias: **paulvaneck**

**Comment by tjprescott** [comment]
@pvaneck @xiangyan99 can you look into this? It sounds like the readme may be out-of-date.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

From https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=portal%2Chttp#rest-endpoint-reference,

seems like it follows the same protocol of app service.

So it should work.

**Comment by alexpovel** [comment]
Just for reference... just used this class:

https://github.com/Azure/azure-sdk-for-python/blob/dfbaf61313fbe5acb5255c1a03a7aeaf307591c4/sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py#L21-L44

successfully from a container app **job** (so not exactly a container app, as asked in the OP).

The docs are still out of date though, and at first I experienced a crash as I wasn't aware `ManagedIdentityCredential` uses `SystemAssigned` first (which wasn't present). [These docs](https://learn.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#authenticate-with-a-system-assigned-managed-identity) and the class docstring clarify that though, so no action needed there.
