### ISSUE TITLE
Link to client API goes to 404

### ISSUE THREAD

**Issue by robtaylor** [Azure/azure-sdk-for-python#30929]
On current version of this page, the link for client API gives a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf431c22-6242-c2af-04e0-b856e2a6a864
* Version Independent ID: ec7d89d4-879f-9785-3ac0-fc55bf804d49
* Content: [Azure Batch SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/batch?view=azure-python)
* Content Source: [docs-ref-services/latest/batch.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/batch.md)
* Service: **batch**
* GitHub Login: @jingjlii
* Microsoft Alias: **jingjli**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by SaurabhSharma-MSFT** [comment]
@robtaylor Are you still seeing this error as I have tried but couldn't see any error clicking on 
![image](https://github.com/Azure/azure-sdk-for-python/assets/38112130/d749ca3a-2071-4d3e-8a9d-e710214f767f)
Please let know if you are still having issues.

**Comment by robtaylor** [comment]
Thanks. Seem to be working for me now.

**Comment by SaurabhSharma-MSFT** [comment]
@robtaylor Thanks for the confirmation. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
