### ISSUE TITLE
Does subscription receiver auto lock work when using async iterator

### ISSUE THREAD

**Issue by hchandola** [Azure/azure-sdk-for-python#30962]
Is there a known issue with the sdk where if i call `get_subscription_receiver`, pass an `auto_lock_renewer` - it does not register the message for locking if i iterate (`async for message in receiver`) instead of calling `receive_messages`.

I was looking [here in the code](https://github.com/Azure/azure-sdk-for-python/blob/ed913268d2981a49b7a8f24a3a172815368b504d/sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py#L74) and i only see `register` being called in `receive_messages` and not in `__anext__` or any of its downstream calls.

**Comment by kashifkhan** [comment]
Thank you for the feedback @hchandola . We will investigate and get back to you asap.

**Comment by swathipil** [comment]
Hi @hchandola - I've not been able to reproduce this issue. Would you be able to provide a sample to reproduce this issue reliably as well as the `azure-servicebus` package version that you're using? Thanks!

**Comment by hchandola** [comment]
I was able to also verify that this is a non issue. Closing this.
