### ISSUE TITLE
[azure-mgmt-storage] Fails to Retrieve 'BlobStorage' Kind

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-sdk-for-python#30967]
- **Package Name**:  azure-mgmt-storage
- **Package Version**:  21.0.0
- **Operating System**: Mac OS
- **Python Version**:  3.8

**Describe the bug**

I'm experiencing an issue where the SDK doesn't return the `BlobStorage` kind, but when I make the same request using the HTTP API directly
(https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/list?tabs=HTTP#code-try-0)

![image](https://github.com/Azure/azure-sdk-for-python/assets/38625842/a31cdba6-0bb4-4b1e-9bc8-b3c0a45b2484)

**To Reproduce**

1. create two kind of storage account
- one is storage kind  the other one is blobstorage kind

2. use StorageManagementClient().storage_accounts.list()

3. compare result with http request
- https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/list?tabs=HTTP#code-try-0
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.v2022_09_01.operations.storageaccountsoperations?view=azure-python#azure-mgmt-storage-v2022-09-01-operations-storageaccountsoperations-list

**Expected behavior**
- same result for sdk and http request

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @ImMin5 . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
Hi @ImMin5, could you check whether you create storage account successfully before `list`? I follow your steps and get all my created storage account. Here is my code:
```python
import os
from dotenv import load_dotenv
from azure.identity import DefaultAzureCredential
from azure.mgmt.storage import StorageManagementClient
from azure.mgmt.storage.models import StorageAccountCreateParameters, Sku


load_dotenv()
client = StorageManagementClient(
    credential=DefaultAzureCredential(),
    subscription_id=os.getenv("AZURE_SUBSCRIPTION_ID"),
)

parameters = StorageAccountCreateParameters(kind="Storage", location="eastus", sku=Sku(name="Standard_GRS"))
response = client.storage_accounts.begin_create(
    resource_group_name="testgroupx",
    account_name="storagekindstorage",
    parameters=parameters,
).result()
print(response.as_dict())

parameters = StorageAccountCreateParameters(kind="BlobStorage", location="eastus", sku=Sku(name="Standard_GRS"), access_tier="Cool")
response = client.storage_accounts.begin_create(
    resource_group_name="testgroupx",
    account_name="storagekindblobstorage",
    parameters=parameters,
).result()
print(response.as_dict())

result = client.storage_accounts.list()
for item in result:
    print(item.name + " - " + item.kind)
```
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/4a322ec1-cd31-4d87-816c-b3d9bd4ef3f7)

**Comment by ImMin5** [comment]
> Hi @ImMin5, could you check whether you create storage account successfully before `list`? I follow your steps and get all my created storage account. Here is my code:
> 
> ```python
> import os
> from dotenv import load_dotenv
> from azure.identity import DefaultAzureCredential
> from azure.mgmt.storage import StorageManagementClient
> from azure.mgmt.storage.models import StorageAccountCreateParameters, Sku
> 
> 
> load_dotenv()
> client = StorageManagementClient(
>     credential=DefaultAzureCredential(),
>     subscription_id=os.getenv("AZURE_SUBSCRIPTION_ID"),
> )
> 
> parameters = StorageAccountCreateParameters(kind="Storage", location="eastus", sku=Sku(name="Standard_GRS"))
> response = client.storage_accounts.begin_create(
>     resource_group_name="testgroupx",
>     account_name="storagekindstorage",
>     parameters=parameters,
> ).result()
> print(response.as_dict())
> 
> parameters = StorageAccountCreateParameters(kind="BlobStorage", location="eastus", sku=Sku(name="Standard_GRS"), access_tier="Cool")
> response = client.storage_accounts.begin_create(
>     resource_group_name="testgroupx",
>     account_name="storagekindblobstorage",
>     parameters=parameters,
> ).result()
> print(response.as_dict())
> 
> result = client.storage_accounts.list()
> for item in result:
>     print(item.name + " - " + item.kind)
> ```
> 
> ![image](https://user-images.githubusercontent.com/70930885/250764901-4a322ec1-cd31-4d87-816c-b3d9bd4ef3f7.png)

@msyyc 
Thank you for reply. 
You're right.. I have confirmed that the blob storage information is returned correctly.
Sorry for wasting your time.
Thanks again.
