### ISSUE TITLE
VirtualMachinesOperations.get() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by RyanMesser** [Azure/azure-sdk-for-python#30983]
- **Package Name**: azure-mgmt-compute
- **Package Version**: 30.0.0
- **Operating System**: Ubuntu 22.04 LTS on Azure
- **Python Version**: 3.10.6

**Describe the bug**

When running fence_azure_arm --msi --plug=host --action=status (or any other action) the following error is recieved 
VirtualMachinesOperations.get() takes 3 positional arguments but 4 were given

If I install version 29.0.0 this issue isn't present, not sure if bug or missing information that is needed.

**To Reproduce**
1. ssh/cli to Ubuntu host
2. Run above fence_azure_arm command and error is seen
3. Other than status the action doesn't complete

**Expected behavior**
For actions such as "off" and "reboot" the host to reboot or stop

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @RyanMesser . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
Hi @RyanMesser Could you check if your error is raised by the SDK breaking change?
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/69a441a9-c2ba-437d-86c7-49e6b5477889)

**Comment by RyanMesser** [comment]
> Hi @RyanMesser I think your error is related with `expand` that is changed from **positional argument** to **keyword-only argument** since expand is query parameter. It can be fixed by:
> 
> ```python
> ...
> client.virtual_machines.get(..., expand="xxx")
> ```
> 
> ![image](https://user-images.githubusercontent.com/70930885/251324963-2587a38f-0e0f-4c72-a664-73b9eb55c169.png)

Hi,

I'm not trying to set any IP configuration. The command I was running fine before version 30.0 was

fence_azure_arm - - msi - - plug=host - - resourceGroup=RG - - action=reboot

I can also run status and action and what's strange is even though it throws that error I get a response with the status. This isn't true though of the off, on or reboot action.

Is there something else I need to input that I didn't need to previously?

**Comment by RyanMesser** [comment]
> Hi @RyanMesser I think your error is related with `expand` that is changed from **positional argument** to **keyword-only argument** since expand is query parameter. It can be fixed by:
> 
> ```python
> ...
> client.virtual_machines.get(..., expand="xxx")
> ```
> 
> ![image](https://user-images.githubusercontent.com/70930885/251324963-2587a38f-0e0f-4c72-a664-73b9eb55c169.png)

Is this a fix you're going to release or is this something i need to do manually on each host?

**Comment by msyyc** [comment]
You need to do it manually.

**Comment by RyanMesser** [comment]
/unresolve

I think more information is needed for this as I don't feel it really awnsers the question or provides enough context for the awnser.

> Hi @RyanMesser, since you haven’t asked that we `/unresolve` the issue, we’ll close this out. If you believe further discussion is needed, please add a comment `/unresolve` to reopen the issue.

**Comment by msyyc** [comment]
@RyanMesser, Is your source code here? https://github.com/ClusterLabs/fence-agents/tree/main
If so, you just need to change [this line](https://github.com/ClusterLabs/fence-agents/blob/d989961f691c8e84b8a94f1b68ac88296753072d/agents/azure_arm/fence_azure_arm.py#L75) to 
```python
vmStatus = compute_client.virtual_machines.get(rgName, vmName, expand="instanceView")
```
