### ISSUE TITLE
An attribute in the usage example is mispelled

### ISSUE THREAD

**Issue by VadarVillage** [Azure/azure-sdk-for-python#30987]
an attribute is misspelled in the usage example:
ResourceManagementClient(**credentials**, subscription_id) --> ResourceManagementClient(**credential**, subscription_id)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 235574af-54a7-fffb-9a63-f65814aa9f9d
* Version Independent ID: ff8553a6-c819-6cbd-4201-f1ce7c382fc0
* Content: [Azure Resources SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/resources?view=azure-python)
* Content Source: [docs-ref-services/latest/resources.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/resources.md)
* Service: **resources**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by swathipil** [comment]
Hi @VadarVillage - Thanks for opening an issue! I've linked a PR that should resolve this. Will update once that's merged. Thanks!

**Comment by swathipil** [comment]
Hey @msyyc - I have a PR open in the docs repo [[here](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1765)] to address this. According to the errors, there are a few issues with the listed publish date/service/etc. I'm not surewhat should be listed there. A few options:
- If you respond with the information, I can update my PR.
- If you'd like to open your own PR, I can close mine.
- Feel free to update my PR as well with the fixes.
Please let me know which works best for you, thanks! 🙂

**Comment by swathipil** [comment]
Hi @msyyc - I was mistaken; there are no errors in the PR. They are just warnings, which are listed [[here](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1765#issuecomment-1622502096)] if you'd like to open a separate PR to resolve them. To close this issue, we can merge the PR.

**Comment by msyyc** [comment]
Hi @swathipil Your PR lack some code and I can't commit to your branch so I open another PR: https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1768

**Comment by lmazuel** [comment]
Closing, as PR from @msyyc has been merged
