### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by muthugit** [Azure/azure-sdk-for-python#30995]
In the documentation page, in the example section, there is a typo (Missing `<`) in the message variable (content -> html).

```
message = {
    "content": {
        "subject": "This is the subject",
        "plainText": "This is the body",
        "html": "html><h1>This is the body</h1></html>"
    },
    "recipients": {
        "to": [
            {
                "address": "customer@domain.com",
                "displayName": "Customer Name"
            }
        ]
    },
    "senderAddress": "sender@contoso.com",
    "attachments": [
        {
            "name": "attachment.txt",
            "attachmentType": "text/plain",
            "contentInBase64": file_bytes_b64.decode()
        }
    ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19153078-fc91-1dc9-e1fb-4b0f4a1b16ec
* Version Independent ID: 4f64ffdb-f36e-fa4d-4a03-431393b3c4c8
* Content: [Azure Communication Email client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/communication-email-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/communication-email-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/communication-email-readme.md)
* Service: **communication**
* GitHub Login: @acsdevx-msft
* Microsoft Alias: **acsdevx-msft**

**Comment by swathipil** [comment]
Hi @muthugit - Thanks for opening an issue!

Hey @turalf - I have a PR open in the docs repo [[here](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1767)] to address this. According to the errors, there are a few issues with the listed service/author/etc. I'm not sure who/what should be listed there. A few options:
- If you respond with the information, I can update my PR.
- If you'd like to open your own PR, I can close mine.
- Feel free to update my PR as well with the fixes.
Please let me know which works best for you, thanks! 🙂

**Comment by swathipil** [comment]
Hi @turalf - Sorry I was mistaken; there are no errors in the PR. They are just warnings, which are listed [[here](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1767#issuecomment-1622523266)] if you'd like to open a PR to resolve them. To close this issue, we can merge the PR.
