### ISSUE TITLE
VMSS operation : How to scale?

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-sdk-for-python#30997]
Hi,

I'm searching for a mean to scale a VMSS with the sdk.
From az cli I can do this
`az vmss scale --resource-group rg-infra-fc --name {vmss} --new-capacity {capacity}`

The operation list seems to not have a scale "only" operation, and begin_update does not seems to ba able to change vmss capacity

**Comment by swathipil** [comment]
Hi @lmussier - Thanks for opening an issue! Tagging people who can take a look at this.

In the meantime, would be able to provide the following information?
- package and version that you are using

**Comment by lmussier** [comment]
Hi @swathipil,

I'm doing this right now

```
async def scaleUp(amd64_tpm:bool, amd64:bool, arm64:bool) -> None:
    logging.info("Starting to scaleup")

    # See what we have
    vmss_client = ComputeManagementClient(credential=DefaultAzureCredential(), subscription_id=SUBSCRIPTION_ID)
    vmssList = vmss_client.virtual_machine_scale_sets.list(resource_group_name=VMSS_RESSOURCE_GROUP_NAME)
    
    new_scale = list()

    # Inspect every vmss to see if it is a target
    for vmss in vmssList:
        name = vmss.name
        tags = vmss.tags
        capacity = vmss.sku.capacity
        
        logging.info(f'Found : {name} tags [{tags}] current capacity {capacity}')
        if "ghe-label" in tags :
            ghe_label = vmss.tags["ghe-label"]
            logging.debug(f'Found ghe-label {ghe_label}')
            if ghe_label == "amd64" and amd64 :
                logging.debug(f'Ask for +1 on instance count for {name}')
                new_scale.append((name, capacity+1))
                
    await vmssScale(new_scale)
```

The scale function is this one 

```
async def vmssScale(scale:list[tuple[str,int]]) -> None :
# https://stackoverflow.com/questions/54291010/python3-how-to-asyncio-gather-a-list-of-partial-functions

    processes = []
    for vmss, capacity in scale:
        logging.info(f'Change capacity of {vmss} to {capacity}')
        processes.append(asyncio.create_subprocess_shell(f'az vmss scale --resource-group rg-infra-fc --name {vmss} --new-capacity {capacity}',
                                                          stdout=asyncio.subprocess.PIPE,
                                                          stderr=asyncio.subprocess.PIPE))
        
    results = await asyncio.gather(*processes)

    for process in results:
        await process.wait()
```

So yes I'm using the management package but without specifying an api version.

**Comment by msyyc** [comment]
Hi @lmussier Azure CLI bases on Python SDK so if you are familiar with CLI source code, it is very easy to find related SDK API. Here is the guideline https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/find_sdk/find_sdk_in_cli_command.md which may help.

**Comment by lmussier** [comment]
> Hi @lmussier Azure CLI bases on Python SDK so if you are familiar with CLI source code, it is very easy to find related SDK API. Here is the guideline https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/find_sdk/find_sdk_in_cli_command.md which may help.

This is better than the direct answer to my question!
A big thanks for this!
