### ISSUE TITLE
Zones Field Missing for Public IP Addresses When Using `ResourceManagementClient.resources.get_by_id()`

### ISSUE THREAD

**Issue by epierotto** [Azure/azure-sdk-for-python#31029]
- **Package Name**:  azure-mgmt-resource
- **Package Version**: 22.0.0
- **Operating System**: Debian buster
- **Python Version**: 3.9

**Describe the bug**
While attempting to fetch the details of resources of type `"Microsoft.Network/publicIPAddresses"` via the `ResourceManagementClient.resources.get_by_id()` method, the returned response does not contain the `"zones"` field for the Public IP Addresses.

**To Reproduce**
1. Create a Public IP with multiple zones
2.  Get the Public IP resource details using `ResourceManagementClient.resources.get_by_id()`, example:
 ```
from azure.identity import DefaultAzureCredential
from azure.mgmt.resource import ResourceManagementClient
import json

credentials = DefaultAzureCredential()
resource_client = ResourceManagementClient(credentials, "<your-subscription-id>")
resource_id = "<your-resource-id>"
api_version = "2022-05-01"

resource = resource_client.resources.get_by_id(resource_id, api_version)
resource_dict = resource.as_dict()

print(json.dumps(resource_dict, indent=4))

```
3. The output does not contain the Public IP `zones`. 

**Expected behaviour**
The "zones" field for the Public IP Address should be present in the returned response when using the `ResourceManagementClient.resources.get_by_id()` method.

**Screenshots**
This is an example Public IP address resource details returned by `ResourceManagementClient.resources.get_by_id()`:
```json
{
    "id": "<resource id>",
    "name": "nginx-ingress",
    "type": "Microsoft.Network/publicIPAddresses",
    "location": "eastus",
    "tags": {
        "expiry": "01012029",
        "workload": "DevOps"
    },
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "f9c77124-48fb-4071-9470-ecf361b57f2d",
        "ipAddress": "20.72.181.55",
        "publicIPAddressVersion": "IPv4",
        "publicIPAllocationMethod": "Static",
        "idleTimeoutInMinutes": 4,
        "ipTags": [],
        "ipConfiguration": {
            "id": "<some other resource id>"
        }
    },
    "sku": {
        "name": "Standard",
        "tier": "Regional"
    }
}
```

**Comment by kashifkhan** [comment]
Thank you for the feedback @epierotto . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
Hi @epierotto, Python SDK is generated with swagger automatically. I find the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/5758cc23b0022e403d876662d9799f02c9bba3e6/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L3590-L3595) of `ResourceManagementClient.resources.get_by_id()` shows its return type is [GenericResource](https://github.com/Azure/azure-rest-api-specs/blob/5758cc23b0022e403d876662d9799f02c9bba3e6/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L3618) which [doesn't contain zones](https://github.com/Azure/azure-rest-api-specs/blob/5758cc23b0022e403d876662d9799f02c9bba3e6/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L5538-L5568). So please make an issue in https://github.com/Azure/azure-rest-api-specs/issues. Once service team accept the feature request and update swagger, we can release a new SDK version to support that.

**Comment by epierotto** [comment]
I've created the follow up issue with the rest-api team: https://github.com/Azure/azure-rest-api-specs/issues/24859
