### ISSUE TITLE
Automate Azure Identity SDK Manual/Vendor Tests

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#31037]
We should leverage @christothes 's work on https://github.com/Azure/azure-sdk-for-net/pull/33017/files to fully automate the list of manual/vendor test scenarios which are documented in the issues here: https://github.com/Azure/azure-sdk/issues?q=is%3Aopen+is%3Aissue+label%3AAzure.Identity

This includes:

- [x] ~~Automate Azure Arc testing~~
  - Currently not worth the ROI on automating. 
- [x] Automate Azure Identity multi tenant testing
- [x] Automate Azure Kubernetes Service
  - https://github.com/Azure/azure-sdk-for-python/pull/33742
- [x] ~~Automate Azure Container Instances testing~~
  - Similar coverage is already completed with AKS testing
- [x] Automate Azure WebJobs testing
  - Web Apps covered in lieu of WebJobs (still App Service)
  - https://github.com/Azure/azure-sdk-for-python/pull/33742
- [x] Automate Azure Service Fabric testing
  - Currently not worth the ROI on automating.  
- [x] Automate Azure Functions testing
  - https://github.com/Azure/azure-sdk-for-python/pull/33742
- [x] Automate VM MSI testing
  - https://github.com/Azure/azure-sdk-for-python/pull/34070
- [x] ~~Automate Pod Identity testing~~
  - Deprecated. Will be covered by AKS workload identity testing
- [x] ~~Automate Cloudshell testing~~
  - Requires manually navigating to a cloud shell, and not sure how to automate.

**Comment by joshfree** [comment]
@pvaneck could you update the progress here (checkboxes above)

**Comment by pvaneck** [comment]
Closing this as completed. Can revisit Arc and Service Fabric test automation separately if we determine it's worth the ROI.
