### ISSUE TITLE
iso-8601 format datetime fails to be deserialized in Face SDK

### ISSUE THREAD

**Issue by lebronJ** [Azure/azure-sdk-for-python#3104]
In generated Face SDK, `TrainingStatus` has three [members](https://github.com/Azure/azure-sdk-for-python/blob/restapi_auto_cognitiveservices/data-plane/Face/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/training_status.py#L55-L57) of type `iso-8601`, generated from [Face.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/Face/stable/v1.0/Face.json#L3458-L3475) (`"type": "string", "format": "date-time"`)  from azure-rest-api-specs.

When I use this Python SDK and specify westus public API endpoint, such error occurred (Seems like a parsing error): 
`msrest.exceptions.DeserializationError: Cannot deserialize datetime object., ValueError: Invalid datetime string: 08/08/2018 08:46:06`.

**Comment by lmazuel** [comment]
It's indeed right, `08/08/2018 08:46:06` is not a valid ISO8601. If the server actually returns that value, Swagger needs to be fixed to describe the correct date format.

**Comment by lebronJ** [comment]
Thanks @lmazuel for your reply. Yes, actually our service [returns ](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/599ae32c6ac60f11b48b5aa5)datetime like `08/08/2018 08:46:06`.

* Copied from our API reference:
`A combined UTC date and time string that describes large person group created time, delimited by a space. E.g. 12/21/2017 12:55:39.`

* Copied from Swagger:
`
"createdDateTime": {
          "type": "string",
          "format": "date-time",
          "description": "A combined UTC date and time string that describes the created time of the person group, large person group or large face list.",
          "x-ms-client-name": "created"
        },
`

* Copied from generated Python SDK
`'created': {'key': 'createdDateTime', 'type': 'iso-8601'},`

I confirm this Swagger generates class of type `Datetime` in C# which works perfectly, any suggestion on how to change the Swagger to make Python SDK work with this? Many thanks.

**Comment by lmazuel** [comment]
@lebronJ This is unfortunately not a standard format, and does not following [Microsoft guideline](https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#112-guidelines-for-dates-and-times). And [Swagger](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) does not support it either.
You're lucky it works in C#, and probably everybody else will fail to parse it :/
The only solution is to update the Swagger to describe it as a string, so at least the global object can be parsed.
There is way to customiz the Python code and provide a personal parser, if you want to we can discuss it.

**Comment by lebronJ** [comment]
@lmazuel yes, I agree that ISO8601 should be the standard API datatime format. 
For now, we have changed Face container to use ISO8601 (tested the Python SDK works well) and add a task to update Face API's datatime format.
