### ISSUE TITLE
406: Not Acceptable error when calling serial_ports.connect()

### ISSUE THREAD

**Issue by spledfx** [Azure/azure-sdk-for-python#31066]
- **Package Name**: azure-mgmt-serialconsole
- **Package Version**: 1.0.0
- **Operating System**: Windows 10 Laptop & Azure Function running on Linux consumption plan
- **Python Version**: Python/3.7.0

**Describe the bug**
Getting response of Response content: 406: Not Acceptable, when calling the serial_ports.connect() method.

**To Reproduce**
Trying with simple connect call and printing the response.
response = client.serial_ports.connect(
        resource_group_name="myResourceGroup",
        resource_provider_namespace="Microsoft.Compute",
        parent_resource_type="virtualMachines",
        parent_resource="myVM",
        serial_port="0",
    )
    print(response)
 

**Expected behaviour**
Not sure yet :)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
(1) Did you create the serial port before connect? If no, please follow https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/serialconsole/azure-mgmt-serialconsole/generated_samples/create_a_new_serial_port_resource..py
nit: please make sure resoure group and virtual machine exists.
(2) If it doesn't work, please follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md which  can provide detailed log for deep investigation.

**Comment by spledfx** [comment]
Hi @msyyc ,

Yes, serial port is present.

{'additional_properties': {}, 'id': '/subscriptions/XXXX/resourcegroups/XXXX/providers/Microsoft.Compute/virtualMachines/XXXX/providers/Microsoft.SerialConsole/serialPorts/0', 'name': '0', 'type': 'Microsoft.SerialConsole/serialPorts', 'state': 'enabled'}

Here is the full log:
[serial_console_406_error_log.txt](https://github.com/Azure/azure-sdk-for-python/files/12121974/serial_console_406_error_log.txt)

**Comment by msyyc** [comment]
@spledfx Python SDK is just tool to send/receive http request/response. According to log, 406 is returned by service. Since we are not domain expert, we have to seek help from service team.
