### ISSUE TITLE
AzureML – No token received for serverless compute with Managed Identity

### ISSUE THREAD

**Issue by mikwieczorek** [Azure/azure-sdk-for-python#31071]
- **Package Name**:  azure-identity
- **Package Version**: 1.12
- **Operating System**: Ubuntu 22
- **Python Version**: 3.8.15

**Describe the bug**
User or Managed Identity token cannot be retrieved inside job submitted to Serverless Compute in Azure Machine Learning.

**Additional context**
Iam testing Azure Machine Learning using both AZ CLI, Python SDKv2 and AML Studio. I successfully created custom docker, environment, compute instance and run a sample training. The compute instance has attached Managed Identity that I created with ACRPull and Workspace Contributor roles. Training finished successfully, and the Model is saved at the end of the training script.

However, when I tried using serverless compute I got completely stuck. Every attempt ended with error retrieving token

```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: No token received.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
Traceback (most recent call last):
  File "train_HM_azure.py", line 35, in <module>
    credential.get_token("https://storage.azure.com/")
  File "/opt/venv/myenv/lib/python3.8/site-packages/azure/identity/_credentials/default.py", line 168, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "/opt/venv/myenv/lib/python3.8/site-packages/azure/identity/_credentials/chained.py", line 101, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: No token received.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

The lines that I put at the beginning of the script are:

```
credential = DefaultAzureCredential()
ml_client = MLClient(credential, subscription_id, resource_group, workspace)
print(list(ml_client.environments.list()))
```
which works as the list of environments in the workspace is listed. However, the script fails at the last line, which is

```
ml_client.models.create_or_update(file_model)
```
 
The user-defined Managed Identity is given all permissions listed here https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/machine-learning/how-to-identity-based-service-authentication.md#workspace and when it is attached to ComputeInstance all works. The job to serverless is submitted using following line:

```
job = command(
    command="python train_azure.py",
    environment=env,
    identity=ManagedIdentityConfiguration(client_id='xxx'),
    instance_type="STANDARD_NC12S_V3",
    instance_count=1,
    display_name="train model",
    code="train",
)
# Submit the command
ml_client.jobs.create_or_update(job)
```
I tried also with

```
identity=ManagedIdentityConfiguration(resource_id='xxx'),
```
and

```
identity=UserIdentityConfiguration()
```
but neither flavor worked. I read the documentation and I have no more ideas, which vectors to explore.

EDIT: Minor spelling and formatting fixes

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by mikwieczorek** [comment]
The initial description is inconsistent as these lines throw exception
```
credential = DefaultAzureCredential()
ml_client = MLClient(credential, subscription_id, resource_group, workspace)
print(list(ml_client.environments.list()))
```
The exception:
```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.
	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
	AzureCliCredential: Azure CLI not found on path
	AzurePowerShellCredential: PowerShell is not installed
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

This error just showed you did not have the auth token to call the API.

Which auth method did you want to use?

**Comment by mikwieczorek** [comment]
Hi @xiangyan99,

I followed documentation on running jobs on serverless compute and I assigned a (User-)Managed identity to workspace. However, when I submitted the job using the `command` from my initial post where the same ManagedIdentity was assigned to serverless job and in my train script I used `credential = DefaultAzureCredential()` it didn't work. 
To make it work one of the two changes needed to introduced into the train script:

- Replace `credential = DefaultAzureCredential()` with `credential = ManagedIdentityCredential(client_id="CLIENT_ID_OF_MANAGED_IDENTITY_ASSIGNED_TO_WORKSPACE")`
- Set at the beginning of the script `AZURE_CLIENT_ID` environmental variable, such that `os.environ["AZURE_CLIENT_ID"] = "CLIENT_ID_OF_MANAGED_IDENTITY_ASSIGNED_TO_WORKSPACE"` and then use `credential = DefaultAzureCredential()`

Even though this works it seems like unnecessary break of nicely streamlined flow of making use of automatic credentials resolution provided by `DefaultAzureCredential`. Also in documentation such case is not described anywhere (or at least I didn't dig into it).

Here somewhat related issues:
#24282 
https://github.com/fsspec/adlfs/issues/411#issuecomment-1660323309

**Comment by xiangyan99** [comment]
Thanks for the feedback.

**Comment by jennan** [comment]
Hello,

I am running in the same issue, and unfortunately @mikwieczorek's solution is not working for me.

- I have created a user managed identity, gave all the rights according to recommendations listed in https://learn.microsoft.com/en-US/azure/machine-learning/how-to-identity-based-service-authentication?view=azureml-api-2&tabs=cli#workspace
- I have updated my Azure ML workspace to use it in addition of the system managed identity, following instructions in https://learn.microsoft.com/en-US/azure/machine-learning/how-to-identity-based-service-authentication?view=azureml-api-2&tabs=cli#to-update-user-assigned-identities-for-a-workspace-includes-adding-a-new-one-or-deleting-the-existing-ones-use-one-of-the-following-methods and a configuration file looking like this
```
- identity:
   type: system_assigned, user_assigned
   user_assigned_identities:
    '<UAI resource ID 1>': {}
primary_user_assigned_identity: <UAI resource ID 1>
```
- then trying to run a pipeline consisting of one command, where `client_id` is my user managed identity client ID
```
extract_component = command(
    name="XXXX",
    display_name="XXXX",
    description="XXXX",
    code="./src",
    command=(
        "python XXXX"
    ),
    inputs={"fields": Input(type="string")},
    outputs={"output_folder": Output(type="uri_folder")},
    environment=environment,
    instance_type="Standard_D1",
    instance_count=1,
    identity=ManagedIdentityConfiguration(client_id=client_id),
    environment_variables={"AZURE_CLIENT_ID": client_id},
)
```
- and the python code running in the job has the following snippet to test credential retrieval
```
    from azure.identity import ManagedIdentityCredential
    from azure.keyvault.secrets import SecretClient

    credential = ManagedIdentityCredential(client=os.environ["AZURE_CLIENT_ID"])

    credential.get_token("https://management.azure.com/.default")
```

This fails with a failure to retrieve a token when running in serverless mode
```
2023-08-18 01:40:41,041 :: azure.identity._internal.decorators :: WARNING :: ManagedIdentityCredential.get_token failed: No token received.
```

I have also tried the `DefaultAzureCredential` + `AZURE_CLIENT_ID` environment variable approach, without success.

I have tried the same from a compute instance of the ML workspace (with user managed identity attached to it), credentials just worked.

Here is some additional context if it can help:
- I was originally trying to access the Azure ML workspace keyvault, and I thought this could work with the system managed identity out-of-the-box... it didn't, same credential failures,
- I tried to pass a user identity, it didn't work (no token),
- I tried the `AzureMLOnBehalfOfCredential` + user identity, it didn't work (no token),

So... is there something special/additional that need to be configured in serverless mode :)?
Thank you for your help.

**Comment by jennan** [comment]
Hello again,

Actually the `DefaultAzureCredential` + `AZURE_CLIENT_ID` environment variable approach worked (I was not using the right ID as client ID for the managed identity).

Thank you so much @mikwieczorek , I have spent many hours trying to figure out this.

**Comment by mikwieczorek** [comment]
Hi @xiangyan99 is there any updated on the fix of this issue or any opinionated way of handling such a case?

**Comment by Sedherthe** [comment]
Facing the same issue, created a managed identity and assigned it to the workspace. When trying to pass it to the command utility function, it says that the managed identity with the associated client id is not attached to the AML workspace. Would love a fix for this!
Didn't clearly understand @mikwieczorek's way will try experimenting with it.

**Comment by Sedherthe** [comment]
Hey @jennan Can you tell more about what changes you did? Did you had to do one of the two changes suggested by @mikwieczorek or both of them? If both, can you specify the exact changes as well?

**Comment by jennan** [comment]
Hi @Sedherthe , I did both changes, but what was important was to find the right string to put as user managed identity ID.
In the Azure dashboard, there are multiple things that look an ID for the user managed identity ID. The one working was the `Client ID`  (format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx , where x is a letter or a number), not the `Object (principal) ID` and not the one starting with `/subscriptions/xxx...`.

**Comment by mshorrosh** [comment]
> Hi @Sedherthe , I did both changes, but what was important was to find the right string to put as user managed identity ID. In the Azure dashboard, there are multiple things that look an ID for the user managed identity ID. The one working was the `Client ID` (format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx , where x is a letter or a number), not the `Object (principal) ID` and not the one starting with `/subscriptions/xxx...`.

This was exactly our issue, once we populated the actual Client/App ID not the object ID it was working.

**Comment by cecheta** [comment]
I get a slightly different error when using `DefaultAzureCredential` on serverless:

```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
	ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8"
Content: InternalError - :{
Info: Request failure status code: 404

}
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    print(credential.get_token("https://management.azure.com/.default"))
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_credentials/default.py", line 225, in get_token
    token = super().get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/azure/identity/_credentials/chained.py", line 123, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
	ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8"
Content: InternalError - :{
Info: Request failure status code: 404

}
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.

```

This still works, however

> Hi @xiangyan99,
> 
> I followed documentation on running jobs on serverless compute and I assigned a (User-)Managed identity to workspace. However, when I submitted the job using the `command` from my initial post where the same ManagedIdentity was assigned to serverless job and in my train script I used `credential = DefaultAzureCredential()` it didn't work. To make it work one of the two changes needed to introduced into the train script:
> 
> * Replace `credential = DefaultAzureCredential()` with `credential = ManagedIdentityCredential(client_id="CLIENT_ID_OF_MANAGED_IDENTITY_ASSIGNED_TO_WORKSPACE")`
> * Set at the beginning of the script `AZURE_CLIENT_ID` environmental variable, such that `os.environ["AZURE_CLIENT_ID"] = "CLIENT_ID_OF_MANAGED_IDENTITY_ASSIGNED_TO_WORKSPACE"` and then use `credential = DefaultAzureCredential()`
> 
> Even though this works it seems like unnecessary break of nicely streamlined flow of making use of automatic credentials resolution provided by `DefaultAzureCredential`. Also in documentation such case is not described anywhere (or at least I didn't dig into it).
> 
> Here somewhat related issues: #24282 [fsspec/adlfs#411 (comment)](https://github.com/fsspec/adlfs/issues/411#issuecomment-1660323309)
