### ISSUE TITLE
[stress] memray command is missing in the Python stress tests

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-python#31077]
I found a rather deep and difficult to diagnose issue in the Python stress tests where the `memray` command was not found. It's impossible to know how or where that should be installed, but please put your best engineer on the messaging team on it.

The pod that failed with this is the `amemray` version of the tests.

@kashifkhan believes this is going to need a Python change, and is prepping a cpython change now.

**Comment by kashifkhan** [comment]
Thank you for your feedback @richardpark-msft. We will investigate and get back to you asap.
