### ISSUE TITLE
New receiver 'nil' with higher epoch of '1689114528157893058' is created hence current receiver 'nil' with epoch '1689108836876353493' is getting disconnected

### ISSUE THREAD

**Issue by StephanyBatista** [Azure/azure-sdk-for-python#31084]
- **azure.eventhub.aio**: 
- **5.11.2**: 
- **Linux**:
- **3.11**: 

**Describe the bug**
Sometimes my consumer is receving this error: "New receiver 'nil' with higher epoch of '1689114528157893058' is created hence current receiver 'nil' with epoch '1689108836876353493' is getting disconnected". 
I searched this problem but I did not find how to fix this problem.

**To Reproduce**
Steps to reproduce the behavior: My current code
```python
sync def receive(consumer, config):
    await consumer.receive_batch(
        on_event_batch=on_event_batch,
        on_error=on_error,
        owner_level=time.time_ns(),
        track_last_enqueued_event_properties=True,
        prefetch=config.prefetch_count,
        max_batch_size=config.max_batch_size
    )


async def consume_messages_event_hub(config, consumer):
    
    LOGGER.debug("call consume_messages_event_hub")

    async with consumer:
        await receive(consumer, config)

def start():
    try:    
        consumer = EventHubConsumerClientBuilder().build(CONFIG.event_hub)
        asyncio.run(consume_messages_event_hub(CONFIG.event_hub, consumer))
        consumer.credential.close()
        
    except Exception as ex:
        LOGGER.exception('An unexpected exception occurred during program execution', extra={'error': ex})


if __name__ == "__main__":
    start()
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment]
Hi @StephanyBatista , 

That error typically happens when there are two instances of an application or receivers configured to use the same Event Hubs consumer group. It can also occur if multiple receivers are using the same consumer group but using another checkpoint store instance but since I dont see a checkpoint store in the provided sample, I dont think that is the issue. 

To remedy this
* Please make sure only one receiver is reading from the consumer group at a time
* Use separate consumer groups for different receivers

**Comment by StephanyBatista** [comment]
Hi @kashifkhan, we use as the code can be see below:

I did understand the problem, this consumer is used on k8s with 8 pods, so we can´t use many instance of this code?

```python
class EventHubConsumerClientBuilder(EventHubConsumerBuilder):

    def build(self, config) -> EventHubConsumerClient:
        checkpoint_store = BlobCheckpointStore.from_connection_string(
            config.storage_account_connection_string,
            config.storage_account_container_name
        )
        return EventHubConsumerClient.from_connection_string(
            config.event_hub_connection_string,
            config.consumer_group,
            eventhub_name=config.name,
            checkpoint_store=checkpoint_store
        )
```

**Comment by kashifkhan** [comment]
@StephanyBatista Can you provide me some information on the set up of your event hub such as # of partitions etc. please ?

**Comment by StephanyBatista** [comment]
About the configuration of event hub
<img width="348" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/6475229/70251f11-0a01-4721-bc4b-ad717a502c87">

I think we have less pods than partition, I don´t see problem with this configuration. What do you think?

**Comment by kashifkhan** [comment]
@StephanyBatista that shouldnt be a problem at all, with 8 nodes and a consumer per node every consumer should be pulling in data from 2 partitions. Is your checkpoint storage also in the same location as the consumer nodes ?

**Comment by StephanyBatista** [comment]
About the same location, I´m seeing this now with our SREs

**Comment by StephanyBatista** [comment]
I don´t see the region of the storage account, so for tests, I created a new storage account in the same region of event hub. Need the storage account stay in the same subscription of the event hub? Which configuration is right to create the storage account?

**Comment by kashifkhan** [comment]
I think region being the same should be more than enough. I'm not aware of any special configuration needed for storage as such, for testing I just use the boilerplate from portal.

**Comment by StephanyBatista** [comment]
I made a test using the same region and after some time I had these erros like these:
2023-07-12 13:43:24.699 UTC-4 New receiver 'nil' with higher epoch of '1689181638265012047' is created hence current receiver 'nil' with epoch '1689181620700629780' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:070f0b6d000e06dc0021baca64aeddc2_G2S2_B15S3, SystemTracker:eventhub-stg1:eventhub:authorization|consumer_r, Timestamp:2023-07-12T17:43:24
ErrorCodes.LinkStolen: New receiver 'nil' with higher epoch of '1689181638265012047' is created hence current receiver 'nil' with epoch '1689181620700629780' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:070f0b6d000e06dc0021baca64aeddc2_G2S2_B15S3, SystemTracker:eventhub-stg1:eventhub:authorization|consumer_r, Timestamp:2023-07-12T17:43:24
partition_id: "14"
pod_name: "t-744dc8f7d-n5622"

2023-07-12 13:43:30.729 UTC-4 New receiver 'nil' with higher epoch of '1689181620014898802' is created hence current receiver 'nil' with epoch '1689181581632330186' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:d6ed9249000e06dc0021baa464aedda6_G5S1_B15S3, SystemTracker:eventhub-stg1:eventhub:authorization|consumer_r, Timestamp:2023-07-12T17:43:30
ErrorCodes.LinkStolen: New receiver 'nil' with higher epoch of '1689181620014898802' is created hence current receiver 'nil' with epoch '1689181581632330186' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:d6ed9249000e06dc0021baa464aedda6_G5S1_B15S3, SystemTracker:eventhub-stg1:eventhub:authorization|consumer_r, Timestamp:2023-07-12T17:43:30
partition_id: "7"
pod_name: "t-744dc8f7d-wrdss"

So I think the problem is not same regions

**Comment by StephanyBatista** [comment]
of course, so like this: 

```
sync def receive(consumer, config):
    await consumer.receive_batch(
        on_event_batch=on_event_batch,
        on_error=on_error,       
        track_last_enqueued_event_properties=True,
        prefetch=config.prefetch_count,
        max_batch_size=config.max_batch_size
    )
```

**Comment by kashifkhan** [comment]
yes :)

**Comment by StephanyBatista** [comment]
I got some errors:

2023-07-12 17:25:55.553 New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used.
partition_id: "14"
pod_name: "t-887447f54-7nzx2"

2023-07-12 17:25:59.529 New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used.
partition_id: "6"
pod_name: "t-887447f54-7nzx2"

2023-07-12 17:26:11.471 New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used.
partition_id: "8"
pod_name: "t-887447f54-7nzx2"

I´m not understaind because is the same pod (887447f54-7nzx2) and it is trying to connect in many partition in little time. Other think, now the epoc is 0, so there are not exclusive reader attempts to assert ownership for the same partition

**Comment by kashifkhan** [comment]
This is quite interesting. Other customers setups are generally a consumer per pod. One single checkpoint store ( blob ) and an Event Hub with partitions. 

After some initial load balancing every pod should have a few partitions to itself ( for ex 16 partitions, 9 pods would end up being seven pods with 2 partitions and two of them with 1 each ). They might load balance again in case nodes go down etc but should largely retain their partitions. 

One other instance of such a problem occured when "Soft Delete" or "Blob versioning" was enabled for the blob checkpoint store, as this can cause some delays with check pointing and coordination

**Comment by StephanyBatista** [comment]
Hi, thanks for your informations
"Other customers setups are generally a consumer per pod. One single checkpoint store ( blob ) and an Event Hub with partitions." - we too, we have a consume per pod.

"One other instance of such a problem occured when "Soft Delete" or "Blob versioning" was enabled for the blob checkpoint store, as this can cause some delays with check pointing and coordination" - where do I configure it?

**Comment by kashifkhan** [comment]
Hi @StephanyBatista, 

You can use the instructions at this [link](https://learn.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-enable?tabs=azure-portal) to turn off Soft Delete. Blob versioning will be an option on the same page as Soft Delete, but these are the instructions to turn it off https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-enable?tabs=portal

**Comment by StephanyBatista** [comment]
Hi, we are using this config, A difference that I saw is that using a storage account as performance premium the error decrease, but not finish.

A question, my pod is location: "us-east1" and the event hub is us-east2, can it cause the error?

**Comment by kashifkhan** [comment]
Is that something we can try just to eliminate ? Though I would think it shouldn't make a difference.

**Comment by kashifkhan** [comment]
No I havent, there was only one issue that was very similar to this one and here are snippets from that issue

> We were able to resolve all of these issues by making sure our Eventhub consumers are using a File Storage account in the same region as the deployment and connecting over service endpoints. The one Eventhub Consumer where we were seeing this issue was deployed in AKS in west central US and in AKS in west US 2 and both cluster consumers were misconfigured to checkpoint in a file storage account in east US. Switching to the same-region file storage account dropped the "lost owernship" count to 0 in each case.

**Comment by jtwears1993** [comment]
@kashifkhan sorry to hijack this thread. I get the same error as reported in this post. My setup is:

- storage: northeurope. With each eventhub having its own container for checkpointing
- eventhub: northeurope, 20 partitions, 2 consumer groups
- AKS: northeurope, running 10 pods for my hotstorage consumer on 1 consumer group, then 10 consumers for my cold storage running on the second consumer group 
- reciever configured as follows:

```
async def construct_eh_consumer(
    reciever_config: TsRecieverConfig, 
    processing_func: Callable, 
    on_error_func: Callable, 
    checkpoint_store_func: Callable
):

    client = EventHubConsumerClient.from_connection_string(
            conn_str=reciever_config.connection_str,
            consumer_group=reciever_config.consumer_group,
            eventhub_name=reciever_config.eventhub_name,
            checkpoint_store=checkpoint_store_func(reciever_config.blob_storage_conn_str, reciever_config.blob_storage_container),
            logging_enable=True,
            load_balancing_interval=int(os.getenv("LOAD_BALANCING_INTERVAL", 60)),
    )
    async with client:
        logging.getLogger("azure").setLevel(logging.ERROR)
        await client.receive(
            on_event=processing_func,
            prefetch=reciever_config.max_message_count,
            on_error=on_error_func,
            starting_position=-1,
            on_partition_close=on_partition_close,
            on_partition_initialize=on_partition_initialize
        )
```

I notice numerous errors like this daily `Error Description: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:9b8d694a0001bbdc004813b164b65fe3_G25_B2, SystemTracker:ts-eventhub-namespace:eventhub:ts-ingestion-eventhub~9833|ts-ingestion-consumer-group-default, Timestamp:2023-07-18T20:48:20`.

I have tried all the suggestions in this thread to no avail and keep loosing data downstream as a result. Please advise

**Comment by kashifkhan** [comment]
@jtwears1993 Thank you  for the details. Can you provide us with some debug logs please. In your current code youd would just up the error level. This way we can see whats happening behind the scenes, as its quite tricky to reproduce on our end.

**Comment by StephanyBatista** [comment]
Hi Guys, my last feedback, the error still exist but we decrease drastically our error using a storage account premium, not default. 
@jtwears1993 sometimes this can help you.

**Comment by kashifkhan** [comment]
Thank you for the update @StephanyBatista . This is very interesting that premium reduced the problem. Do you happen to have the storage request IDs, we can look to see if the queries were slow for storage
