### ISSUE TITLE
Wrong description for begin_create_or_update_slot() SDK

### ISSUE THREAD

**Issue by Catastrophe1** [Azure/azure-sdk-for-python#31095]
https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-web_7.1.0/sdk/appservice/azure-mgmt-web/azure/mgmt/web/v2022_09_01/operations/_web_apps_operations.py

Regarding to the SDK description:

```
 @distributed_trace
    def begin_create_or_update_slot(
        self,
        resource_group_name: str,
        name: str,
        slot: str,
        site_envelope: _models.Site,
        **kwargs: Any
    ) -> LROPoller[_models.Site]:
        """Creates a new web, mobile, or API app in an existing resource group, or updates an existing
        app.

        Description for Creates a new web, mobile, or API app in an existing resource group, or updates
        an existing app.
```

The SDK is not used to create a new app. It is used to create a slot on an existing app. The explanation confuses the users and need to be clarified. The Azure doc definition also needs to be updated: https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2019_08_01.operations.webappsoperations?view=azure-python#azure-mgmt-web-v2019-08-01-operations-webappsoperations-begin-create-or-update-slot

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
Hi @Catastrophe1 Python SDK is generated with swagger automatically. So please make an issue update [swagger description](https://github.com/Azure/azure-rest-api-specs/blob/925ba149e17454ce91ecd3f9f4134effb2f97844/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/WebApps.json#L8668). After swagger fixed, we can release a new SDK version.

**Comment by Catastrophe1** [comment]
Hi @msyyc 
Issue is raised for swagger as well: https://github.com/Azure/azure-rest-api-specs/issues/24852

**Comment by msyyc** [comment]
Let us wait for the swagger fix.
