### ISSUE TITLE
generate_blob_sas can generate invalid SAS URLs

### ISSUE THREAD

**Issue by seanytak** [Azure/azure-sdk-for-python#31090]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.13.0
- **Operating System**: Ubuntu 20.04.6 LTS (via WSL2)
- **Python Version**: 3.10.9

**Describe the bug**
When using the function `generate_blob_sas`, an invalid SAS URL can be created when given insufficient information in the parameters.

**To Reproduce**

Given the following call
```python
account_key = os.environ["BLOB_ACCOUNT_KEY"]
blob_sas = generate_blob_sas(
    account_name="my_account_name",
    container_name= "my_container_name",
    blob_name="my_blob_name",
    account_key=account_key,
    permissions=BlobSasPermissions(read=True),
    expiry=datetime.utcnow()+3600,
)
```
This call actually contains a typo on `permissions` (should be just `permission`) which while a user error, leads to the function returning an invalid SAS URL instead of throwing an error.

On a subsequent request using this `blob_sas`, it will be missing an `sp` parameter and will fail.

**Expected behavior**
Ideally, the function would instead throw an error that the generated SAS URL is an invalid one, rather than passing silently only for a later caller using `blob_sas` to fail.

**Screenshots**
N/A

**Additional context**
The bug / feature request is for this function to throw an error if an invalid SAS URL would be generated.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by jalauzon-msft** [comment]
Hi @seanytak Sean, thanks for reporting the issue! It does seem like we do not do proper validation on the inputs for our SAS parameters. We'll look into adding some input validation to this method (and out other SAS methods) at some point soon.

**Comment by vincenttran-msft** [comment]
Hi @seanytak Sean, sorry for the delay! My response to this issue is long overdue, but rest assured the issue has been addressed!

Pull request #32704 was added as a result of this GitHub issue and has been successfully merged. The SAS input validation changes are live and are included in our latest release of `azure-storage-blob` ([12.9.0](https://pypi.org/project/azure-storage-blob/12.19.0/))

Thanks again for your contribution! 😄
