### ISSUE TITLE
Azure Search Index filters not working at all / throwing errors

### ISSUE THREAD

**Issue by gitprojects619** [Azure/azure-sdk-for-python#31138]
I got some errors(at the bottom of this body) in my actual code, so I thought of creating a simpler scenario only to realize that the filters are not working at all for me.

imports are as follows:  
``` from azure.core.credentials import AzureKeyCredential
from azure.search.documents.indexes import SearchIndexClient
from azure.search.documents import SearchClient
import pandas as pd
from uuid import uuid4
from azure.search.documents.indexes.models import *
``` 

My data is a dataframe:
```from uuid import uuid4
data = [{'uuid':str(uuid4()),'Numb_Str':'10','Sent':'Stand-up comedy is a comedic performance to a live audience in which the performer addresses the audience directly from the stage','Topic':'Standup'},
        {'uuid':str(uuid4()),'Numb_Str':'20','Sent':'A stand-up defines their craft through the development of the routine or set','Topic':'Standup'},
        {'uuid':str(uuid4()),'Numb_Str':'30', 'Sent':'Experienced comics with a popular following may produce a special.','Topic':'Standup'}]

df = pd.DataFrame(data)
```  
The dataframe looks like [![enter image description here][1]][1]  

I create the search index using the below function that takes a dataframe , creates an index and puts it into this index using the code below:
```
def create_search_index(index_name:str,df:pd.DataFrame)->None:

    index_client = SearchIndexClient(endpoint=f"https://{AZURE_SEARCH_SERVICE}.search.windows.net/",
                                     credential=AzureKeyCredential(AZURE_SEARCH_KEY))

    index = SearchIndex(
        name=index_name,
        fields=[
            SimpleField(name="uuid", type="Edm.String", key=True),
            SimpleField(name="Numb_Str", type="Edm.String", filterable=True, facetable=True),
            SearchableField(name="Sent", type="Edm.String", analyzer_name="en.microsoft"),
            SimpleField(name="Topic", type="Edm.String", filterable=True, facetable=True),
        ],
        semantic_settings=SemanticSettings(
            configurations=[SemanticConfiguration(
                name='default',
                prioritized_fields=PrioritizedFields(
                    title_field=None, prioritized_content_fields=[SemanticField(field_name='Sent')]))])
    )
    print(f"Creating {index} search index")
    index_client.create_index(index)

    search_client = SearchClient(endpoint=f"https://{AZURE_SEARCH_SERVICE}.search.windows.net/",
                                 index_name=index_name,
                                 credential=AzureKeyCredential(AZURE_SEARCH_KEY))
    sections = df.to_dict("records")
    search_client.upload_documents(documents=sections)

create_search_index('test-index-simple-2',df)
```  

I use the below code for running the 'search' and get 2 results in the print irrespective of the `filter` parameter.   You may use "Topic ne 'Standup'" or 'abcd xkcd' for that matter as filter and you will get the same result!

```
search_client = SearchClient(
            filter = "Topic eq 'Standup'",
            endpoint=f"https://{AZURE_SEARCH_SERVICE}.search.windows.net",
            index_name='test-index-simple-2',
            credential=AzureKeyCredential(AZURE_SEARCH_KEY))

results = search_client.search('What is standup comedy?')

for item in results:
    print(item['uuid'])
```  

**Issue 1**:  What's wrong in the code above to account for such weird behaviour of filters not working  

  

**Issue 2**: My actual code gives the 2 below errors (ran independently of each other) that I have tried to detail out without actually getting into the code  

**Issue 2.a**    

    Error: () Invalid expression: A binary operator with incompatible types was detected. Found operand types 'Edm.String' and 'Edm.Int32' for operator kind 'Equal'  

   
for the filter arg = ''max_tokens_in_chunk eq 200'  
   
where **max_tokens_in_chunk** is a column in the search index created as `SimpleField(name="max_tokens_in_chunk", type="Edm.String", filterable=True, facetable=True)`

  
**Issue 2.b**  
```
Error: () Invalid expression: Could not find a property named 'Tesla' on type 'search.document'.
Parameter name: $filter
Code:
Message: Invalid expression: Could not find a property named 'Tesla' on type 'search.document'.
Parameter name: $filter
```
for the filter arg  = 'company eq Tesla'

'where company is a column created as `SimpleField(name="company", type="Edm.String", filterable=True, facetable=True)` . I can gaurantee Tesla is present because I printed it out from the Search Index

Note:  
Everything is in python  
I have already checked the previous related questions and didn't find an apt answer

  [1]: https://i.stack.imgur.com/Q5NhS.png

**Comment by gitprojects619** [comment]
@xiangyan99 may be you would be able to help as you had also written the https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_filter_query.py.

I amunfortunately unable to use your code as there is no place where it is shown how the search index being referenced in the file is created

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
As showed in https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_filter_query.py, you need to specify the filter argument in search method.

We don't support specifying filter in the constructor.

Can you try it again and see if the problem still presents?

Thanks.

**Comment by gitprojects619** [comment]
@xiangyan99 , yes this works. Thanks for the quick response. I will close the issue
