### ISSUE TITLE
What's the data used for creating the search index in sample_filter_query.py ?

### ISSUE THREAD

**Issue by gitprojects619** [Azure/azure-sdk-for-python#31139]
I see hotels-sample-index being referenced in https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_filter_query.py but no sample shows how this search index was created.. 

I think it was created from https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/files/hotel_small.json  but can someone also tell the code which was used to create this ??

@xiangyan99 may be you would be able to help :)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
(Assuming you are asking which code to create the index)

Here is the code: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_index_crud_operations.py
