### ISSUE TITLE
How to use a newer version of NetworkManagementClient in an azure automation runbook?

### ISSUE THREAD

**Issue by arne21a** [Azure/azure-sdk-for-python#3113]
the default NetworkManagementClient version in a python 2 automation runbook does not feature the attribute load_balancer_backend_address_pools.

```
from pydoc import help
from azure.mgmt.network import NetworkManagementClient
print help(NetworkManagementClient)
```
results in:

```
Help on class NetworkManagementClient in module azure.mgmt.network:

class NetworkManagementClient(__builtin__.object)
 |  Composite Swagger for Network Client
...
|  __init__(self, credentials, subscription_id, api_version='2017-03-01', base_url=None)
...
|  ----------------------------------------------------------------------
|  Data descriptors defined here:
...
|  express_route_service_providers
|  
|  load_balancers
|  
|  local_network_gateways
...
```
As [documented](https://docs.microsoft.com/de-de/python/api/azure-mgmt-network/azure.mgmt.network.v2017_03_01.operations.loadbalancersoperations?view=azure-python), this version [(2017-03-01)](https://github.com/Azure/azure-sdk-for-python/tree/master/azure-mgmt-network/azure/mgmt/network/v2017_03_01) does not feature the attribute load_balancer_backend_address_pools.

My question:
Is there a way to use a newer version of NetworkManagementClient in an azure runbook, without using a hybrid runner?

**Comment by lmazuel** [comment]
Tagging people from the Automation team:
@Francisco-Gamino @vrdmr @avkaur @DeveloperTommy

**Comment by lmazuel** [comment]
To answer in terms of versionning, this is available in 2017-06-01 for the first time, which is 1.6.0 Python version.

**Comment by vrdmr** [comment]
@Diastro Could you please take a look?

**Comment by andyw248** [comment]
Support for Python 3.x should become available on Linux Hybrid Workers in early 2020.

**Comment by andyw248** [comment]
Closing because work on updating to Python 3 is in progress, which should eliminate the issue described above.
