### ISSUE TITLE
Slow processing for azure.core.paging.ItemPaged

### ISSUE THREAD

**Issue by andrewzheng1618** [Azure/azure-sdk-for-python#31142]
**Is your feature request related to a problem? Please describe.**
I run vector search and then process results whose type is azure.core.paging.ItemPaged like below:

   results = search_client.search(  
        search_text='',  
        vector=Vector(
            value=embedding,
            k=3,
            fields='embedding'),  
        select=['question', 'answer'] 
    )
    for result in results:
        continue

I found that vector search is fast which takes 10ms - 20ms. But just iterating results is slow, which takes 200ms - 300ms. Is it because I do not process azure.core.paging.ItemPaged in the right way, or ItemPaged is just so slow?

**Describe the solution you'd like**
How to process ItemPaged faster?

**Describe alternatives you've considered**
N/A

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
Can you give more details?

Search method may return lots of results hence we make it paged return.

This means `search_client.search` just return the PagedItem object but does not retrieve real data.

`for result in results:`
Does the real work to get results for you.

It is expected that `for result in results:` may be slower than `search_client.search` depends how many results you find.

**Comment by andrewzheng1618** [comment]
search_client.search() does retrieve real data. search_client.search() takes 10ms - 20ms. But just “for result in results:” takes 200ms - 300ms for 3 results which it is too slow.

**Comment by xiangyan99** [comment]
Could you give more details why you think it does retrieve real data?

**Comment by andrewzheng1618** [comment]
Because I use it in production and it works. But I find that the whole method latency is so high, so I dig out each part latency.

**Comment by xiangyan99** [comment]
Thanks for the reply.

I don't think I fully understand it. 

Because I use it in production and it works. 

You mean you get real data when you call search_client.search() without anything else?

If you don't mind, could you share your code snippet?

**Comment by andrewzheng1618** [comment]
Sure. In the following code snippet, t1  = 10ms - 20ms, t2  = 200ms - 300ms. t2 is too slow and I want to know how to speed it up.

def retrieve_relevant_qa(embedding, index_name):
    t0 = time.time()
    search_client = SearchClient(azure_search_service_endpoint, index_name, azure_search_credential)
    results = search_client.search(  
        search_text='',  
        vector=Vector(
            value=embedding,
            k=3,
            fields='embedding'),  
        select=['question', 'answer'] 
    )
    t1 = time.time() - t0
    for result in results:
        continue
    t2 = time.time() - t1

**Comment by xiangyan99** [comment]
Thanks for sharing.

to make sure we are on same page:

```py
def retrieve_relevant_qa(embedding, index_name):
t0 = time.time()
search_client = SearchClient(azure_search_service_endpoint, index_name, azure_search_credential)
results = search_client.search(
search_text='',
vector=Vector(
value=embedding,
k=3,
fields='embedding'),
select=['question', 'answer']
)    # here we only create the iterator but do not retrieve any data
t1 = time.time() - t0
for result in results:   # here we do real work to retrieve data. hence this operation is slower.
    continue
t2 = time.time() - t1
```

**Comment by andrewzheng1618** [comment]
any update?

**Comment by lmazuel** [comment]
@andrewzheng1618 I confirm what @xiangyan99 said that the `search` call itself do NOT fetch any data. It's job is to create an iterator object that upon call, will actually connect to Azure. You can see the design by yourself, based on a callback system called when you iterate in the loop:

https://github.com/Azure/azure-sdk-for-python/blob/c4c18a7b427633c0519016d762dc141ae743e41b/sdk/search/azure-search-documents/azure/search/documents/_paging.py#L124

You can also enable logging, and you will be able to see that the 10ms you spend in the initial call is just construction of the iterator, not any HTTP calls on the wire.

It's not a surprise then that you get slower time when actually calling Azure for real, compared to create an iterator object.

That being said, maybe there are some optimization we should/could do in the code, but the assumption that the first call is a HTTP call is incorrect.

**Comment by andrewzheng1618** [comment]
Thanks for the detailed explanation. In the meanwhile, does it have way I could try to speed up the process?

**Comment by xiangyan99** [comment]
Here are some general approaches you may try:
- concurrency
- limit number of results
- network latency
