### ISSUE TITLE
CostManagementClient DeserializationError on Error code "NotDefined"

### ISSUE THREAD

**Issue by kaankoseler** [Azure/azure-sdk-for-python#31169]
- **Package Name**: azure-mgmt-costmanagement
- **Package Version**: 4.0.0
- **Operating System**: Ubuntu 20.04.5 LTS
- **Python Version**: Python 3.9.16

**Describe the bug**
When calling the `get_execution_history` method in the `azure/mgmt/costmanagement/operations/_exports_operations.py` file, there is apparently a `NotDefined` error code returned, which leads to a `DeserializationError` with the following message:

```
DeserializationError: (", ValueError: invalid literal for int() with base 10: \'NotDefined\'", \'Unable to deserialize response data. Data: NotDefined, int\', ValueError("invalid literal for int() with base 10: \'NotDefined\'"))', 'Unable to deserialize response data.
```

**To Reproduce**
1. Call the `get_execution_history` method with an export that returns as `NotDefined` error code.
Here is an example of the response we received that caused this `DeserializationError` with the subscriptionId stripped out. If there is a place to provide this subscriptionId in private so that it is not public, please let me know.
```
{\'id\': \'subscriptions/STRIPPED_SUBSCRIPTION_ID/providers/Microsoft.CostManagement/exports/steveBillingExport/Run/9119aea0-01d8-414e-9878-026b397b0c6f\', \'name\': None, \'type\': None, \'eTag\': None, 
\'properties\': 
{\'runSettings\': {\'format\': \'Csv\', \'deliveryInfo\': 
{\'destination\': 
{\'resourceId\': \'/subscriptions/STRIPPED_SUBSCRIPTION_ID/resourceGroups/eclairStandardLBGroup/providers/Microsoft.Storage/storageAccounts/stevetestauditsetting\', \'container\': \'billingexports\', \'rootFolderPath\': \'billing\'}},
\'definition\': {\'type\': \'ActualCost\', \'timeframe\': \'MonthToDate\', \'dataSet\': {\'granularity\': \'Daily\'}}},
\'executionType\': \'Scheduled\', \'status\': \'Failed\', \'submittedBy\': \'System\', \'submittedTime\': \'2021-03-28T22:20:56.1608488Z\', \'processingStartTime\': \'2021-03-28T22:20:56.1608488Z\', \'processingEndTime\': \'2021-03-28T22:32:04.1154776Z\', \'fileName\': \'billing/steveBillingExport/20210301-20210331/steveBillingExport_9119aea0-01d8-414e-9878-026b397b0c6f.csv\', 
\'error\': {\'code\': \'NotDefined\', \'message\': None}}}
```

**Expected behavior**
It should not return a `DeserializationError` and should execute as normal. The error should be appropriately handled in the deserializer. It appears to be expecting an `int` and cannot handle the `NotDefined` error code, which is a string. 

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @kaankoseler . We will investigate & get back to you asap.

**Comment by msyyc** [comment]
It is swagger issue and it was fixed in https://github.com/Azure/azure-rest-api-specs/pull/23790/files. Now we only need to release a new SDK version.

**Comment by msyyc** [comment]
It is fixed in https://pypi.org/project/azure-mgmt-costmanagement/4.0.1/
