### ISSUE TITLE
Current version of `azure-monitor-opentelemetry-exporter` is not compatible with recent OTEL release

### ISSUE THREAD

**Issue by macieyng** [Azure/azure-sdk-for-python#31164]
- **Package Name**: azure-monitor-opentelemetry-exporter
- **Package Version**: 1.0.0b14
- **Operating System**: macOS/linux
- **Python Version**: 3.8

**Describe the bug**
`opentelemetry-api` update to recent 1.19.0 downgrades `azure-monitor-opentelemetry-exporter` to 1.0.0b10. This is due to `azure-monitor-opentelemetry-exporter` requirement `opentelemetry-api==1.18.0`.

**To Reproduce**
1. Install `azure-monitor-opentelemetry-exporter==1.0.0b14`
2. try to install `opentelemetry-api==1.19.0`
3. You either receive dependency issue or `azure-monitor-opentelemetry-exporter` will be downgraded to `1.0.0b10` (where `opentelemetry-api` version was not yet specified) 

**Expected behavior**
I should be able to use `azure-monitor-opentelemetry-exporter==1.0.0b14` with `opentelemetry-api==1.19.0` - I could not find an information how these versions are not compatible.

**Screenshots**
-

**Additional context**
Communication also on [CNCF slack channel #otel-python](https://cloud-native.slack.com/archives/C01PD4HUVBL/p1689585307079509).

cc @jeremydvoss @lzchen

**Comment by macieyng** [comment]
@jeremydvoss Thanks!

Regarding your comment:

> This versioning is currently pinned because OTel python logs is currently marked as unstable.

What is the reason for Python logs being marked as unstable? Is there any information when they can be considered stable? Any resources I could read on the subject?

**Comment by lzchen** [comment]
@macieyng 

You can refer to [project status](https://github.com/open-telemetry/opentelemetry-python#project-status) section of Opentelemetry python
