### ISSUE TITLE
[ServiceBus] AMQP client fails to create a receiver link

### ISSUE THREAD

**Issue by ahmadhany** [Azure/azure-sdk-for-python#31161]
- **Package Name**: azure-servicebus
- **Package Version**: 7.10.0
- **Operating System**: Azure Kubernetes (alpine3.16)
- **Python Version**: 3.9

**Describe the bug**
Getting the below error while listening to a service-bus topic.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/_base_handler.py", line 411, in _do_retryable_operation
    return operation(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/_transport/_pyamqp_transport.py", line 617, in iter_next
    receiver._open()
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/_servicebus_receiver.py", line 361, in _open
    while not self._handler.client_ready():
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/_pyamqp/client.py", line 392, in client_ready
    if not self._client_ready():
  File "/usr/local/lib/python3.9/site-packages/azure/servicebus/_pyamqp/client.py", line 809, in _client_ready
    self._link = self._session.create_receiver_link(
AttributeError: 'NoneType' object has no attribute 'create_receiver_link'
```

**To Reproduce**
This occurs randomly, but seems to happen mostly when the subscription receiver becomes Idle for a while.
I'm using the below snippet.
```
with self.servicebus_client:
    receiver = self.servicebus_client.get_subscription_receiver(topic_name=self.TOPIC_NAME, subscription_name=self.SUBSCRIPTION_NAME)
    for msg in receiver:
        self.process_message(msg, receiver)
```
I have to mention something that sounds weird, I'm getting this error most likely on Thursday and Friday at least for the past two weeks.

**Comment by kashifkhan** [comment]
Thank you for the feedback @ahmadhany.  The context about the subscription receiver being idle is key in us trying to repro the issue. 

There are a couple of things Id like you to try on your side please
* Upgrade to the latest version of `azure-servicebus` 7.11.1. We had a few bug fixes in there which maybe could solve this
* Turn on debug logging and pass in `logging_enable=True`. This way we can see what exactly happens as this error surfaces and could further help in a repro. Your code above would need to be modified like this
```python

from azure.servicebus import ServiceBusClient
import logging
import sys

logger = logging.getLogger('azure.servicebus')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)

CONNECTION_STR = ''
#QUEUE_NAME = ''
TOPIC_NAME = ''
SUBSCRIPTION_NAME = ''

servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR,  logging_enable=True)
```

> I have to mention something that sounds weird, I'm getting this error most likely on Thursday and Friday at least for the past two weeks.

Its not that weird if Friday is a day off and Thursday is a low activity day as it would correlate to less activity and the receiver idling as there isnt much activity. Is that a fair assumption that your systems see less traffic and usage on Thursday & Friday ?

**Comment by kashifkhan** [comment]
Thank you for the update @ahmadhany. One more follow up, are you using AMQP transport only ?

**Comment by ahmadhany** [comment]
> are you using AMQP transport only ?

@kashifkhan  Yes, the default settings, I'm not using `uamqp`.

**Comment by kashifkhan** [comment]
Thanks for the update @ahmadhany. Im able to repro this on my side, will link the PR once its ready

**Comment by kashifkhan** [comment]
@ahmadhany I initially thought this issue was related to another bug in the code, but I think Im mistaken. Are you by any chance running the receiver with multiple threads ?

**Comment by ahmadhany** [comment]
@kashifkhan Yes, I'm running the receiver with multiple threads.

Here's an example:
```
with self.servicebus_client:
    receiver = self.servicebus_client.get_subscription_receiver(topic_name=self.TOPIC_NAME,subscription_name=self.SUBSCRIPTION_NAME)
    for msg in receiver:
    x = Thread(target=trio.run, args=(self.process_message, msg, receiver))
    x.start()
```

Sorry for my late reply.

**Comment by kashifkhan** [comment]
@ahmadhany Thank you for the update. The issue here is because the service bus client library is not threadsafe, so your code is running in to a situation where some thread has jumped ahead and trying to access objects that have not been initialized by the other thread. Our recommendation is that the application using the client handle thread safety, so a lock around the client being accessed would be a way to solve the issue.

**Comment by ahmadhany** [comment]
@kashifkhan Thank you for the update and for identifying the root cause of the issue.
