### ISSUE TITLE
How to list all jobs for a compute target in AzureML SDK v2?

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-sdk-for-python#31192]
I'm trying to list all jobs for a compute target in AzureML SDK v2 but I can't see how to do it. In SDK v1 the code would look like this:

```py
from azureml.core import Workspace, ComputeTarget, Run
workspace = Workspace.from_config()
compute = ComputeTarget(workspace, "name")
runs = Run.list_by_compute(compute=compute)
```

If it's not possible, will support be added to reach parity with v1?

**Comment by YalinLi0312** [comment]
Hi @letmaik , thanks for your contact! We'll investigate asap!

**Comment by achauhan-scc** [comment]
currently its not supported in SDK V2

**Comment by achauhan-scc** [comment]
adding a backlog item.
