### ISSUE TITLE
AzMon OpenTelemetry Distro: support Azure SDK in statbeats

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#31196]
When the distro starts reporting statbeats, it should be able to determine if telemetry is coming from Azure SDK by looking into the library name in the instrumentation scope. If it starts with `azure.`, then it should be recorded as telemetry coming from Azure SDK.

There is no need to distinguish individual libraries at the moment.

**Comment by lzchen** [comment]
Fixed with https://github.com/Azure/azure-sdk-for-python/pull/27756
