### ISSUE TITLE
InvalidHeaderValue spawned in put_blob according to given size

### ISSUE THREAD

**Issue by schaefi** [Azure/azure-sdk-for-python#312]
I see a weird issue which causes an exception from put_blob. The error I got is

```
azure.WindowsAzureError: Unknown error (The value for one of the HTTP headers is not in the correct format.)
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Mesage>The value for one of the HTTP headers is not in the correct format.
RequestId:c6c6d441-0001-0050-49f7-a3a700000000
Time:2015-03-06T09:05:27.5183848Z</Message><HeaderName>x-ms-blob-content-length</HeaderName><HeaderValue>1680</HeaderValue></Error>
```

I stumbled over this just by accident when testing blob uploads of small test files. If you set
a different size in put_blob e.g 1024, or 2048 the error is gone.

Bug or feature ?

Thanks

**Comment by huguesv** [comment]
What type of blob (x_ms_blob_type parameter)?  Page blobs needs to be aligned to 512 bytes.  Block blobs don't have that requirement.

**Comment by schaefi** [comment]
Thanks that explains it, I used PageBlob and wasn't aware of the 512 byte alignment requirement.
Adapted my code accordingly
