### ISSUE TITLE
ModuleNotFoundError: No module named 'msrestazure'

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#31210]
It looks like the azure-mgmt-servermanager library imports `msrestazure`, but doesn't take a dependency on it: 

https://github.com/Azure/azure-sdk-for-python/blob/fd93053fcd9f30a90e4d55e07d254989132ea771/sdk/servermanager/azure-mgmt-servermanager/azure/mgmt/servermanager/server_management.py#L14

Test failures: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2931348&view=logs&j=11a651e3-713b-5092-386c-1f3b6f7ebbbd&t=6fbf28f9-d2de-5c6e-ba72-80f998604aaa&l=722

https://github.com/Azure/azure-sdk-for-python/blob/fd93053fcd9f30a90e4d55e07d254989132ea771/sdk/servermanager/azure-mgmt-servermanager/setup.py#L68-L72

Should this be updated?

**Comment by msyyc** [comment]
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/93d9585e-b797-46a9-a7ad-d8343bb31592)

It is not updated for a long time and no service team to ask for update so I am afraid the service may be not maintained anymore.

**Comment by kristapratico** [comment]
@msyyc got it. My motivation is to get CI green again for this package by either fixing the issue or disabling tests if we think this package is inactive. Which would you prefer?

**Comment by msyyc** [comment]
There is no need to pay effort on the abandoned package so I prefer to disable its tests.

**Comment by kristapratico** [comment]
Okay thanks, I disabled the pipeline.
