### ISSUE TITLE
[azure-search-documents] Generating url is not complied with standard Cognitive Search REST API   

### ISSUE THREAD

**Issue by HakjunMIN** [Azure/azure-sdk-for-python#31218]
- **Package Name**: azure-search-documents
- **Package Version**: 11.4.0b6
- **Operating System**: WSL
- **Python Version**:  3.9

**Describe the bug**

https://github.com/Azure/azure-sdk-for-python/blob/azure-search-documents_11.4.0b6/sdk/search/azure-search-documents/azure/search/documents/_generated/_search_index_client.py#L36

Why this request url is generated to `{endpoint}/indexes('{indexName}')` instead of `{endpoint}/indexes/{indexName}`
Since integrating Cognitive Search API as a backend API on APIM, found out it is impossible to use `{endpoint}/indexes('{indexName}')` as front endpoint. 

According to [official REST API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/preview/2023-07-01-Preview/searchindex.json#L585), url in SDK should be generated to  `{endpoint}/indexes/{indexName}`

**To Reproduce**
1. setup APIM then make backend endpoint like `test.search.windows.net/indexes`. Front endpoint is like `https://test.azure-api.net/indexes`
2. use SDK via above APIM endpoint https://aoai.azure-api.net

```python
search_client = SearchClient(
    endpoint=f"https://test.azure-api.net",
    index_name=AZURE_SEARCH_INDEX,
    credential=AzureKeyCredential("key"))
```

then call to url: https://test.azure-api.net/indexes('gptkb-vector')/docs/search.post.search?api-version=2023-07-01-Preview
But should be this : https://test.azure-api.net/indexes/gptkb-vector/docs/search.post.search?api-version=2023-07-01-Preview

**Expected behavior**
SDK must follow standard spec of Cognitive Search REST API

**Screenshots**

**Additional context**

Not just this version, other can be found like this issue on generating Url

**Comment by kashifkhan** [comment]
Thank you for your feedback @HakjunMIN . We will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
@iscai-msft could you help to take a look?

**Comment by xiangyan99** [comment]
This is what is defined in swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/preview/2023-07-01-Preview/searchindex.json#L13:

"hostTemplate": "{endpoint}/indexes('{indexName}')",

**Comment by HakjunMIN** [comment]
@xiangyan99 Thank you for your response

Very weird to see the swagger. MSFT official doc says index/{indexname} accrording to https://learn.microsoft.com/en-us/rest/api/searchservice/search-documents
And a lot of samples in MSFT official doc saying the same. see https://learn.microsoft.com/en-us/azure/search/samples-rest

Moreover, this structure can not be integrated to Azure API Management since first element in uri can be dynamic using {indexname} in index('{indexname})'. This is what I'm failing to configure. 

Why this weird non standard uri path is used at the swagger and python sdk?

**Comment by xiangyan99** [comment]
(I am also interested)

If you don't mind, please open an issue in https://github.com/Azure/azure-rest-api-specs.

**Comment by HakjunMIN** [comment]
@xiangyan99 Sure. I'll post it on rest api side as well. 
I think python sdk can be modified first before swagger changed because their rest API can already accept `index/{index}`. 
Big telecommunication company in Korea is waiting for this fix.

**Comment by xiangyan99** [comment]
While we are evaluating the changes in swagger, you can try use custom hook to update the url, here is the sample:

https://gist.github.com/xiangyan99/94aa0bdadcf28040f4bffb7f9bb1c213

Please let me know if it works.

**Comment by HakjunMIN** [comment]
@xiangyan99 Thank you for your workaround. But what I meant to do is not in python, just APIM front end URL prefix which is not applicable by any code base even regex.

**Comment by xiangyan99** [comment]
Sorry. I am a little confused.

Could you give more details how you want to use the libraries and what's the blocker?

**Comment by HakjunMIN** [comment]
Refer to https://github.com/Azure/azure-sdk-for-python/issues/31218#issuecomment-1646995295 again and the code of this issue.

App (this python sdk) -> Azure APIM -> Cognitive Search REST

uri prefix in APIM can not handle `/index('{indexname})'`. only can do /index/{indexname}

**Comment by xiangyan99** [comment]
Thank you.

With the custom hook, https://gist.github.com/xiangyan99/94aa0bdadcf28040f4bffb7f9bb1c213, 

the request uri sent by the Python SDK would be /index/{indexname}.

Doesn't it work?

**Comment by HakjunMIN** [comment]
@xiangyan99 Ah. What you're talking about hooking was this! I'll try your way, it will be worked. Thank you much!
