### ISSUE TITLE
Configure auto-shutdown when creating Virtual Machine

### ISSUE THREAD

**Issue by edumugi** [Azure/azure-sdk-for-python#31230]
I have automated the launching of Azure Virtual Machines with python sdk. However I have not been able to found out how to configure auto-shutdown. This can easily be done when launching a VM from the Azure Portal. Am I missing something or is this feature not yet implemented in the python sdk?

Here is my code:

```

from azure.mgmt import compute

compute_client = compute.ComputeManagementClient(credential, subscription_id)
compute_client.virtual_machines.begin_create_or_update(
        resource_group,
        vm_name,
        {
            "location": location,
            "storage_profile": {
                "image_reference": {
                    "id": IMAGE_ID
                },
                "os_disk": {
                    "caching": "ReadWrite",
                    "managed_disk": {"storage_account_type": "StandardSSD_LRS"},
                    "name": f"{vm_name}osdisk",
                    "create_option": "FromImage",
                },
            },
            "hardware_profile": {"vm_size": MY_INSTANCE_TYPE},
            "os_profile": {
                "computer_name": vm_name,
                "admin_username": MY_USER,
                "linux_configuration": {
                    "disable_password_authentication": True,
                    "ssh": {
                        "public_keys": [
                            {
                                "path": MY_PATH,
                                "key_data":MY_KEY,
                            }
                        ]
                    },
                },
                "custom_data": custom_data,
            },
            "network_profile": {"network_interfaces": [{"id": MY_NI_ID}]},
        },
    )

```

`

**Comment by kashifkhan** [comment]
Thank you for the feedback @edumugi . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
Hi @edumugi Python SDK is generated with swagger automatically. Related swagger is here https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/virtualMachine.json#L3031 and I don't find similar feature. So please open issue in https://github.com/Azure/azure-rest-api-specs/issues and mark with label `feature request`. Once swagger is fixed, python SDK will release new version to support it.
