### ISSUE TITLE
azure-eventhub async BlobCheckpointStore restarts at partition start if Eventhub connection lost

### ISSUE THREAD

**Issue by erewokMF** [Azure/azure-sdk-for-python#31258]
- **Package Name**: 
  - `azure-eventhub`
  - `azure-eventhub-checkpointstoreblob-aio`
- **Package Version**: 
  - 5.11.3
  - 1.1.4
- **Operating System**:
  - debian linux container: (see `python:3.11-slim-bookworm` base)
- **Python Version**: 
  - `3.11.4`

**Describe the bug**
We see the following happening:
1. Eventhub consumer loses its connection due to inactivity
1. Eventhub consumer reconnects after a few minutes and starts over _at the beginning of the partition_ (which for us is a few thousand messages back).

The consumer here is a kubernetes pod, and we can see that no other pod has claimed the partition in the meantime. In effect, when the consumer loses its connection and reconnects, it **ignores** the latest checkpoint (which has been otherwise spot-checked in Azure Blob Storage and is working as expected) and starts over from the beginning.

**To Reproduce**
1. Run a few Eventhub consumers (async) across a 3-partition eventhub
1. Enable checkpointing
1. Run lots of events through
1. Wait until one of the consumers gets disconnected
1. Check if consumer reconnects and starts over at the beginning of the partition

**Expected behavior**
We expected the consumer to reconnect and continue on from the latest checkpoint.

**Logs**
Here is a sequence of log messages from a **single** kubernetes pod illustrating the problem (in chronological order, timestamps in UTC):

```json
// Event received as normal: sequence_number for this partition is 104602
{"message": "", "main": "EventhubConsumer", "sequence_number": 104602, "partition": "1", "event": "Received event", "application": "SFUpdater", "version": "v1.9.1-20230714.1", "span": {"span_id": "0x52e63afe8bf5d049", "trace_id": "0xc2c76b3bff23ea667e23adadaadc7045", "parent_span_id": "0x79c66f44913e6f2b"}, "level": "info", "timestamp": "2023/07/21 21:28:30"}

// next log message after the above, a disconnect due to inactivity
{"message": "Connection closed with error: [b'amqp:connection:forced', b\"The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:33bc532ce6c44e56a82a607f4429ad7b_G8S3, SystemTracker:gateway5, Timestamp:2023-07-21T21:36:16\", None]", "timestamp": "2023-07-21T21:36:16.576876+00:00", "application": "SFUpdater", "version": "v1.9.1-20230714.1"}

// immediately following the disconnect, the next log message is as follows with sequence_number 101258
{"message": "", "main": "EventhubConsumer", "sequence_number": 101258, "partition": "1", "event": "Received event", "application": "SFUpdater", "version": "v1.9.1-20230714.1", "span": {"span_id": "0x73b260e0d803999c", "trace_id": "0x1f6f8ea301aa51c685f13d3263fa1700", "parent_span_id": "0x4a236ec29b9c8f9c"}, "level": "info", "timestamp": "2023/07/21 21:36:17"}

// the pod is now very busy reconsuming all events from the beginning of the partition
// large number of log messages follow...
```

Footnote: I mentioned this problem to @kashifkhan a couple of weeks ago and he suggested upgrading to `azure-eventhub` `5.11.3`, and you can see that from the "connection inactive" message above.

Also, possibly related to #29961?

**Comment by erewokMF** [comment]
Thanks for your reply. The **only** log messages I am seeing now are those above. I wanted to check which loggers to enable (checkpoint library, for example) before turning them on. I can do that. Unfortunately, it took a week for it to happen this last time, so it may be some time before I have some useful logs. I will enable these and keep an eye on it.

**Comment by kashifkhan** [comment]
Thank you very much @erewokMF. Just to confirm, in your blob storage you can see the proper sequence number correct ? Its the client that starts from some point in the past ?

**Comment by erewokMF** [comment]
Yes, but I have discovered the problem has happened after it's been reset and I'm getting alarms from log alerts. Under regular operation, when I look at the checkpoint file in Blob storage, I see in the metadata the **expected** `sequence_number` matching the last event processed.

**Comment by erewokMF** [comment]
I discovered this morning that I could trigger this in our dev environment by setting the eventhub status to "Disabled" and then setting it back to "Active". 

Our application logs include the sequence number and you can see the sequence number starting back at partition start when I do this:

```
16103
16103
16103
16103
16103
16104
16104
16104
16104
16105
16105
16105
16105
16105
16105
16090
16090
16090
16090
16090
16090
16091
16091
16091
16091
16091
```

I have a large volume of debug logs associated with this but no blob-storage logs at the moment.

**Comment by kashifkhan** [comment]
Thank you so much for this @erewokMF and also the detailed email with logs. We will pour over those and Ill update this when we can repro on our end 🙂

**Comment by erewokMF** [comment]
You are welcome. Thanks for your assistance, as always!

**Comment by swathipil** [comment]
Hi @erewokMF - Trying to repro this right now. How quickly do you re-enable the hub after disabling?

**Comment by erewokMF** [comment]
I am slow; usually takes me 30s to 1m to re-enable.

**Comment by swathipil** [comment]
Thanks @erewokMF! Another follow up: Are you checkpointing on_event_batch/per event/by event count/something else? Can you provide a sample of when/how you update the checkpoint?

**Comment by erewokMF** [comment]
Hello @swathipil! I have a few different strategies I've tried in order to make sure the bug isn't something weird we're doing. Right now, we're single single-event receipt (as opposed to batch) and checkpointing after every event is handled. In other words, we are running something _very_ close to [this example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_store_async.py). 

However, we are using `azure-identity` to auth with the Blob Storage  container and with the Eventhub. Today, I want to try adding `azure-identity` to the DEBUG logs and figure out why Blob Storage client logs are not appearing.

**Comment by erewokMF** [comment]
Potentially useful update: I just tried to run the same app with `uamqp_transport=True,` and see if I could reproduce the issue and **I could not**. After disabling and reenabling the consumer it did not start over at the beginning of the partition.

**Comment by kashifkhan** [comment]
Thanks for the updates & logs @erewokMF. We will link out a PR for the fix to this issue

**Comment by kashifkhan** [comment]
Hi @erewokMF, we have now released an update with the fix. Appreciate your help to fix this issue :)
