### ISSUE TITLE
virtual_machine_run_commands.begin_create_or_update with treatFailureAsDeploymentFailure property lead to failed execution state

### ISSUE THREAD

**Issue by martintintintin** [Azure/azure-sdk-for-python#31251]
- **azure.mgmt.compute**
- **python dep is 30.0.0 and api version 2023-03-01 // azure-cli 2.50.0 with azure-mgmt-resource 23.1.0b2**
- **Ubuntu**
- **3.8**:

**Describe the bug**
`compute_client.virtual_machine_run_commands.begin_create_or_update` results in ` Execution failed: failed to get configuration: json validation error: invalid public settings JSON: treatFailureAsDeploymentFailure: Additional property treatFailureAsDeploymentFailure is not allowed`, whereas the same command using `az vm run-command create` succeeds.

Inspecting VM it can be seen that `runCommands` resources created by the former (sdk) contain the `treatFailureAsDeploymentFailure` property, whereas they don't for the latter (`az`).

**To Reproduce**
```python
    credential = AzureCliCredential()
    compute_client = ComputeManagementClient(credential, subscription_id)

    vm = compute_client.virtual_machines.get(rg, vm_name)
    p = compute_client.virtual_machine_run_commands.begin_create_or_update(
        rg,
        vm_name,
        run_command_name="fails",
        run_command=compute_client.virtual_machine_scale_set_vm_run_commands.models.VirtualMachineRunCommand(
            location=vm.location,
            source=compute_client.virtual_machine_run_commands.models.VirtualMachineRunCommandScriptSource(
                script='ls'
            ),
        ),
    )
    p.wait(180)
    s = compute_client.virtual_machine_run_commands.get_by_virtual_machine(
        rg, vm_name, run_command_name="fails", expand="instanceView"
    )
    iw = s.instance_view
    logging.info(
        f"{iw.execution_state}, {iw.execution_message}, {iw.exit_code}, {iw.error}"
    )
```

for same "values"

`az vm run-command create --name "n" --vm-name "v" --resource-group "rg" --script "echo Hello World!"`

leads to success.

**Expected behavior**
The use of SDK should work as az cli

**Screenshots**

**Additional context**

* treatFailureAsDeploymentFailure was part of python sdk since late May, but I guess many others should have been impacted, but you will take a look and help me out.

Full instanceView of failed command:
```
  "instanceView": {
    "endTime": "2023-07-21T11:49:22+00:00",
    "error": "",
    "executionMessage": "Execution failed: failed to get configuration: json validation error: invalid public settings JSON: treatFailureAsDeploymentFailure: Additional property treatFailureAsDeploymentFailure is not allowed",
    "executionState": "Failed",
    "exitCode": 3,
    "output": "",
    "startTime": "2023-07-21T11:49:22+00:00",
    "statuses": null
  }
```

Command resources (Microsoft.Compute/virtualMachines/runCommands) created in VM and failing look like

```
        {
            "type": "Microsoft.Compute/virtualMachines/runCommands",
            "apiVersion": "2023-03-01",
            "name": "...",
            "location": "northeurope",
            "dependsOn": [
               ...
            ],
            "properties": {
                "source": {
                    "script": "ls"
                },
                "timeoutInSeconds": 300,
                "asyncExecution": false,
                "treatFailureAsDeploymentFailure": false
            }
        },

```

while those created with az cli don't contain `treatFailureAsDeploymentFailure` property.

* Downgrading to `29.1.0` makes the problem go away. **** me, took me too long to realize :D. Anyway, hope you'll have a look.

**Comment by kashifkhan** [comment]
Thank you for the feedback @martintintintin . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
It may be service issue: https://github.com/Azure/azure-rest-api-specs/issues/24963

**Comment by ChenxiJiang333** [comment]
@martintintintin I have tested about this and the issue seems been fixed, please have a try and give feedback.
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/3b001669-027a-4056-8ba6-c859ec54dda2)
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/c9295fe6-353b-465d-bffb-5896f1fa75f3)

**Comment by martintintintin** [comment]
It works on 30.0.0 now. Thanks
