### ISSUE TITLE
Got InvalidApiVersionParameter when use az keyvault network-rule add --name "keyvaultname" --subnet "subnetresourceid

### ISSUE THREAD

**Issue by kabhMSFT** [Azure/azure-sdk-for-python#31266]
There are over 100 KeyVaults in customer's subscription. When customer called the command:
az keyvault network-rule add --name "keyvaultname" --subnet "subnetresourceid", they got below error message:

(InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

The nextlink has the right api-version 2015-11-01, but the next call changes the api-version to 2023-02-01, which is incorrect.
[image](https://user-images.githubusercontent.com/66855967/254835032-ea7cb6ce-2675-425f-9e10-734ccccbdd77.png)

This is impacting customer's production, please help fix it ASAP. thanks.

**Related command**
az keyvault network-rule add --name "keyvaultname" --subnet "subnetresourceid"

**Errors**
(InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

**Issue script & Debug output**
az keyvault network-rule add --name "keyvaultname" --subnet "subnetresourceid" --debug >> ErrorOutput.txt
![image](https://github.com/Azure/azure-sdk-for-python/assets/128568300/35fe71b5-dcc3-460f-9065-fab4d785a481)

**Expected behavior**
It should work when there are more than 100 key vaults in the subscription.

**Environment Summary**
{
"azure-cli": "2.50.0",
"azure-cli-core": "2.50.0",
"azure-cli-telemetry": "1.0.8",
"extensions": {
"ai-examples": "0.2.5",
"ml": "2.18.0",
"ssh": "1.1.6"
}
}

**Additional Context:**
This issue was initially raised here: https://github.com/Azure/azure-cli/issues/26950

**Comment by msyyc** [comment]
We have found the root cause and will fix it asap.

**Comment by msyyc** [comment]
Hi @kabhMSFT Could you please try whether the following package fix your issue? If yes, we will release a new version ASAP:

[azure_mgmt_keyvault-10.2.3-py3-none-any.zip](https://github.com/Azure/azure-sdk-for-python/files/12156798/azure_mgmt_keyvault-10.2.3-py3-none-any.zip)
(nit: just need decompress it to get `.whl`)

**Comment by kabhMSFT** [comment]
@msyyc I cannot reproduce this issue in my env, however customer was able to fix it by adding --resource-group parameter in the existing command.

where do I use this whl? I am not sure how to test this.

**Comment by msyyc** [comment]
Fix version https://pypi.org/project/azure-mgmt-keyvault/10.2.3/ is released
