### ISSUE TITLE
CosmosClient.get-database-client not raising CosmosResourceNotFoundError exception when database doesn't exist

### ISSUE THREAD

**Issue by LHHegland** [Azure/azure-sdk-for-python#31287]
- **Package Name**: azure.cosmos
- **Package Version**:  4.3.1
- **Operating System**: system='Windows', node='DESKTOP-2V17ULL', release='10', version='10.0.19045', machine='AMD64'
- **Python Version**:  3.11.4

**Describe the bug**
Call to azure.cosmos.CosmosClient.get-database-client(db_id) not raising CosmosResourceNotFoundError exception when database does not exist.

**To Reproduce**
1. See [attached Python code](https://github.com/Azure/azure-sdk-for-python/files/12156102/ms_azure_cosmosdb_get_database_client_py.txt)

**Expected behavior**
Expected CosmosResourceNotFoundError exception to be raised. However, even the [Learn](https://learn.microsoft.com/en-us/?view=azure-python) > [Reference](https://learn.microsoft.com/en-us/python/api/overview/azure/?view=azure-python) > [Cosmos DB](https://learn.microsoft.com/en-us/python/api/overview/azure/cosmos-db?view=azure-python) > [azure-cosmos](https://learn.microsoft.com/en-us/python/api/azure-cosmos/?view=azure-python) > [azure.cosmos.cosmos_client](https://learn.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.cosmos_client?view=azure-python) > 
CosmosClient Class documentation for [get_database_client](https://learn.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.cosmos_client.cosmosclient?view=azure-python#azure-cosmos-cosmos-client-cosmosclient-get-database-client) lists an inconsistent exception return (i.e. CosmosResourceExistsError)
![image](https://github.com/Azure/azure-sdk-for-python/assets/44125353/a6555cdf-71c9-4120-b1c0-929d5463a320)

**Screenshots**
[image](https://github.com/Azure/azure-sdk-for-python/assets/44125353/8ea8050f-58a6-4d00-8603-9f48607a0719)

**Additional context**
- Python Code: [ms_azure_cosmosdb_get_database_client_py.txt](https://github.com/Azure/azure-sdk-for-python/files/12156102/ms_azure_cosmosdb_get_database_client_py.txt)
- OUTPUT LOG: [ms_azure_cosmosdb_get_database_client_20230724191248.log](https://github.com/Azure/azure-sdk-for-python/files/12155982/ms_azure_cosmosdb_get_database_client_20230724191248.log)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by simorenoh** [comment]
Hi @LHHegland, thanks for using our SDK and opening this issue. The `get_xxx_client` methods do not throw exceptions ever, and instead just instantiate a Proxy object for you to use with your application. It is only doing other operations like create, read, replace, delete, etc with those Proxy objects that you may run into errors.

Seems like in this case we need to update our public documentation on this, but the behavior is as expected - if it does not exists or already exists, you should not get an error regardless.
