### ISSUE TITLE
azure-mgmt-quota is giving ResourceNotFoundError on Microsoft.Compute

### ISSUE THREAD

**Issue by joybwang** [Azure/azure-sdk-for-python#31293]
- **Package Name**: azure-mgmt-quota
- **Package Version**: 1.0.0
- **Operating System**: Microsoft Windows [Version 10.0.19044.3086]
- **Python Version**: 3.9.13 

**Describe the bug**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test\lib\site-packages\azure\core\paging.py", line 123, in __next__     
    return next(self._page_iterator)
  File "test\lib\site-packages\azure\core\paging.py", line 75, in __next__      
    self._response = self._get_next(self.continuation_token)
  File "test\lib\site-packages\azure\mgmt\quota\operations\_quota_operations.py", line 874, in get_next
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "test\lib\site-packages\azure\core\exceptions.py", line 112, in map_error    
  raise error
azure.core.exceptions.ResourceNotFoundError: (InvalidResourceType) 
The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2023-02-01'.
Code: InvalidResourceType
Message: The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2023-02-01'.
```

**To Reproduce**
1. install
```
pip install azure-identity==1.13.0 azure-mgmt-quota==1.0.0
``` 
2. use QuotaMgmtClient
```
from azure.identity import DefaultAzureCredential
from azure.mgmt.quota import QuotaMgmtClient

group_name = 'my_group'
location = "westus2"
subscription = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
quota_client = QuotaMgmtClient(
    DefaultAzureCredential(),
    subscription_id=subscription,
)
scope = f'/subscriptions/{subscription}/providers/Microsoft.Compute/location/{location}'
d = quota_client.quota.list(scope=scope)
data = list(d)
```

**Comment by Cor5in** [comment]
Based on the information provided, it has been confirmed through Microsoft's official documentation that the '2023-02-01' version of the API is not supported. Here is the link to the official documentation. 
https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/allversions

Using the unsupported API version may result in encountering unsupported resource types or limitations on features related to that API version. If you need further assistance with this matter, please feel free to inquire through comments. Good luck!

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ajhous44** [comment]
Would like to add to this. When trying to pip install azure-mgmt-quota: The candidate selected for download or install is a yanked version. Reason for being yanked: References inaccessible web API

**Comment by xiangyan99** [comment]
There is a new version of azure-mgmt-quota released. Could you help to try if it works?
