### ISSUE TITLE
DigitalTwins, Maps, and Storage tests failing

### ISSUE THREAD

**Issue by jeremydvoss** [Azure/azure-sdk-for-python#31301]
- **azure-monitor-opentelemetry**: 
- Checks for DigitalTwins, Maps, and Storage are failing and blocking [this PR](https://github.com/Azure/azure-sdk-for-python/pull/30089)

**Describe the bug**
Checks unrelated to migrating package are blocking PR.

**To Reproduce**
1. Make a PR

**Expected behavior**
Checks for preexisting code should pass.

**Screenshots**

**Additional context**
How should I go about addressing these issues?

**Comment by xiangyan99** [comment]
Your PR modified 4099 files.

Could you clean up your PR or make it into smaller ones?
