### ISSUE TITLE
Backward Incompatibility of azure-ai-ml 1.9.0

### ISSUE THREAD

**Issue by trajepl** [Azure/azure-sdk-for-python#31319]
- **Package Name**: azure-ai-ml
- **Package Version**:  1.9.0
- **Operating System**: Unix
- **Python Version**: python3.8

**Describe the bug**
azure-ai-ml (=1.9.0) can not accept Pathlib for command `code` .

But when 1.9.0 was released, the following change will never allow `PathLike` arguments which is incompatibility with the version less than 1.9.0. Also the returning is kept as `str, os.PathLike` still. Not sure the typing checking is by design or not. Please help double check.

(BTW, it is not blocking our codes. We can always cast PathLike to str before assignment. Just raise it up in case there are anything missed)

![image](https://github.com/Azure/azure-sdk-for-python/assets/13343117/121b9df9-d14c-420f-8238-fc0103ddfce9)

https://github.com/Azure/azure-sdk-for-python/blob/1356c85959f4ba182a92491f6d99d016411c8ab1/sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/command_component.py#L142C1-L149C1

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by diondrapeck** [comment]
Hi @trajepl, I'll include a fix for this in an upcoming PR. Thank you for bringing it to our attention.

**Comment by diondrapeck** [comment]
@elliotzh - could you please address the backcompat issue introduced in this PR: https://github.com/Azure/azure-sdk-for-python/commit/1356c85959f4ba182a92491f6d99d016411c8ab1?

![image](https://github.com/Azure/azure-sdk-for-python/assets/16376603/e28d9490-51a5-4612-814f-eaf14ff64356)

**Comment by elliotzh** [comment]
Thanks for the report! @trajepl Yes this type check is not by-design and should also accept `os.PathLike`, will fix it ASAP.
