### ISSUE TITLE
No module named 'azure.identity'; 'azure' is not a package

### ISSUE THREAD

**Issue by passo-giau** [Azure/azure-sdk-for-python#31329]
- **Package Name**: azure-identity
- **Package Version**: 1.13.0
- **Operating System**: Ubuntu 20.04.6 LTS (Azure VM)
- **Python Version**: 3.8.10

**Describe the bug**
I installed the python modules **pip3 install azure-keyvault-secrets azure-identity** and got import error
`ModuleNotFoundError: No module named 'azure.identity'; 'azure' is not a package`
**To Reproduce**
1. I started the python3 interactively and typed in
2. from azure.identity import DefaultAzureCredential
3. and received the same error

**Expected behavior**
Nothing, successful import

**Screenshots**
![azure0](https://github.com/Azure/azure-sdk-for-python/assets/42697637/ab906284-b5c0-49c3-8290-8ba8ec4d64fa)

**Additional context**
As the screenshot shows, the **pip list** shows that the module is installed

**Comment by xiangyan99** [comment]
Could you show the full list of pip3 list?

**Comment by passo-giau** [comment]
Thanks for the quick reply. Here is the full list:
`root@cmmc-stg-usermgmt-1:/home/cmmcadmin# pip list
Package                   Version
------------------------- --------------------
altgraph                  0.17.3
attrs                     19.3.0
Automat                   0.8.0
azure-common              1.1.28
azure-core                1.28.0
azure-identity            1.13.0
azure-keyvault-secrets    4.7.0
blinker                   1.4
certifi                   2019.11.28
chardet                   3.0.4
Click                     7.0
cloud-init                23.2.1
colorama                  0.4.3
command-not-found         0.3
configobj                 5.0.6
constantly                15.1.0
cryptography              2.8
dbus-python               1.2.16
distro                    1.4.0
distro-info               0.23ubuntu1
entrypoints               0.3
httplib2                  0.14.0
hyperlink                 19.0.0
idna                      2.8
importlib-metadata        1.5.0
incremental               16.10.1
isodate                   0.6.1
Jinja2                    2.10.1
json3                     1.0
jsonpatch                 1.22
jsonpointer               2.0
jsonschema                3.2.0
keyring                   18.0.1
language-selector         0.1
launchpadlib              1.10.13
lazr.restfulclient        0.14.2
lazr.uri                  1.0.3
MarkupSafe                1.1.0
more-itertools            4.2.0
msal                      1.23.0
msal-extensions           1.0.0
netifaces                 0.10.4
oauthlib                  3.1.0
pexpect                   4.6.0
pip                       23.2.1
portalocker               2.7.0
pyasn1                    0.4.2
pyasn1-modules            0.2.1
PyGObject                 3.36.0
PyHamcrest                1.9.0
pyinstaller               5.13.0
pyinstaller-hooks-contrib 2023.6
PyJWT                     1.7.1
pymacaroons               0.13.0
PyNaCl                    1.3.0
pyOpenSSL                 19.0.0
pyparted                  3.11.2
pyrsistent                0.15.5
pyserial                  3.4
python-apt                2.0.1+ubuntu0.20.4.1
python-debian             0.1.36+ubuntu1.1
PyYAML                    5.3.1
requests                  2.22.0
requests-unixsocket       0.2.0
SecretStorage             2.3.1
service-identity          18.1.0
setuptools                45.2.0
simplejson                3.16.0
six                       1.14.0
sos                       4.4
ssh-import-id             5.10
systemd-python            234
Twisted                   18.9.0
typing_extensions         4.7.1
ubuntu-advantage-tools    8001
ufw                       0.36
unattended-upgrades       0.1
urllib3                   1.25.8
wadllib                   1.3.3
WALinuxAgent              2.2.46
wheel                     0.34.2
zipp                      1.0.0
zope.interface            4.7.1
`

**Comment by xiangyan99** [comment]
Hi tried the dependencies but could not repro the issue.

Here is my pip list result:

altgraph                  0.17.3
attrs                     19.3.0
Automat                   0.8.0
azure-common              1.1.28
azure-core                1.28.0
azure-identity            1.13.0
azure-keyvault-secrets    4.7.0
blinker                   1.4
certifi                   2019.11.28
cffi                      1.15.1
chardet                   3.0.4
Click                     7.0
colorama                  0.4.3
configobj                 5.0.6
constantly                15.1.0
cryptography              2.8
distro                    1.4.0
entrypoints               0.3
httplib2                  0.14.0
hyperlink                 19.0.0
idna                      2.8
importlib-metadata        1.5.0
incremental               16.10.1
isodate                   0.6.1
Jinja2                    2.10.1
json3                     1.0
jsonpatch                 1.22
jsonpointer               2.0
jsonschema                3.2.0
keyring                   18.0.1
launchpadlib              1.10.13
lazr.restfulclient        0.14.2
lazr.uri                  1.0.3
MarkupSafe                1.1.0
more-itertools            4.2.0
msal                      1.23.0
msal-extensions           1.0.0
netifaces                 0.10.4
oauthlib                  3.1.0
pbr                       5.11.1
pexpect                   4.6.0
pip                       23.2.1
portalocker               2.7.0
ptyprocess                0.7.0
pyasn1                    0.4.2
pyasn1-modules            0.2.1
pycparser                 2.21
PyHamcrest                1.9.0
pyinstaller               5.13.0
pyinstaller-hooks-contrib 2023.6
PyJWT                     1.7.1
pymacaroons               0.13.0
PyNaCl                    1.3.0
pyOpenSSL                 19.0.0
pyrsistent                0.15.5
pyserial                  3.4
PyYAML                    5.3.1
requests                  2.22.0
requests-unixsocket       0.2.0
SecretStorage             2.3.1
service-identity          18.1.0
setuptools                45.2.0
simplejson                3.16.0
six                       1.14.0
ssh-import-id             5.10
testresources             2.0.1
Twisted                   18.9.0
typing_extensions         4.7.1
urllib3                   1.25.8
wadllib                   1.3.3
wheel                     0.34.2
zipp                      1.0.0
zope.interface            6.0

**Comment by passo-giau** [comment]
FYI: I resolved it by putting the virtual environment site-packages as the first path entry:

sys.path = ['/home/ams/.venv/lib/python3.10/site-packages', '/opt/azure/lib/python3.10/site-packages', ....]

**Comment by DeepakPradeepKumar** [comment]
Hi - I have the same issue where I have installed azure-identity and then do the import getting modulenotfound error.

**Comment by passo-giau** [comment]
Forget those modules, save yourself grief and just use REST

**Comment by santosh0705** [comment]
Make sure your script filename is not `azure.py`.

**Comment by AidanStrong** [comment]
> Make sure your script filename is not `azure.py`.

This was the fix for me.

**Comment by DeepakPradeepKumar** [comment]
Thank you for your response, appreciate it.

I got it resolved by uninstall python and all other libraries and started
from scratch to resolve the issue.

*Thanks & Regards,*
*:-Deepak.P.*
