### ISSUE TITLE
Library to easily mock/stub Azure Python SDK methods?

### ISSUE THREAD

**Issue by jinkang23** [Azure/azure-sdk-for-python#31330]
Are there any library to easily mock and stub Azure Python SDK methods for writing unit tests?

I noticed that [azure-devtools](https://github.com/Azure/azure-python-devtools) project may offer this capability but it has been archived since 2020.
What I'm looking for is similar to [Moto library for AWS boto3 SDK](https://github.com/getmoto/moto) but for Azure Python SDK. 

Thank you.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Usually we use modk.patch to mock a method.

Does this work for you?

**Comment by annatisch** [comment]
Hi @jinkang23,
Depending on your needs for the mock, I find that the [Azure SDK transport](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#transport) is a good way to achieve this.
All Azure SDKs accept a replacement `transport` at the constructor, which allows you to swap out the actual service request for your own logic, so you can inspect the outgoing payload or inject your own response or errors.

Here's an example I made for some unit tests in the Tables SDK:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/tests/test_encoder.py#L47-L77

As mentioned, all our SDKs support this, so you should be able to share the implementation between any combination of SDKs you might be using.
The protocol is pretty straightforward:
```python
from azure.core.pipeline.transport import HttpTransport

class MockTransport(HttpTransport):
    def send(request: HttpRequest, **kwargs) -> HttpResponse:
        # This is where you add any test logic, for example, testing a connection failure:
        # raise azure.core.exception.ServiceResponseError("something went wrong!")

# Then we can plug this into any SDK via kwargs:
storage_client = BlobServiceClient(account_url, credential, transport=MockTransport())
```

**Comment by pamelafox** [comment]
@annatisch Could you possibly advise on mocking AsyncHttpTransport? I'm having a harder time with that, starting from your code. Current status:

```
    class MockTransport(AsyncHttpTransport):
        async def send(self, request: HttpRequest, **kwargs) -> HttpResponse:
            if request.url.endswith("notfound.pdf"):
                raise ResourceNotFoundError()
            else:
                return HttpResponse(request, 200, b"test content")

        async def __aenter__(self):
            return self

        async def __aexit__(self, *args):
            pass

        async def open(self):
            pass

        async def close(self):
            pass

    # Then we can plug this into any SDK via kwargs:
    blob_client = BlobServiceClient(f"https://{os.environ['AZURE_STORAGE_ACCOUNT']}.blob.core.windows.net",
        credential=MockAzureCredential(), transport=MockTransport())
    blob_container_client = blob_client.get_container_client(os.environ["AZURE_STORAGE_CONTAINER"])
```

The HttpResponse needs to be a different type, but haven't figured out what yet. I'll keep digging into the code.

**Comment by pamelafox** [comment]
Update: My test is passing now, but is *very* slow (20 seconds), so I'm wondering if the SDK code is waiting/sleeping somewhere. Typically I expected tests with mocked out network calls to be quite fast.
