### ISSUE TITLE
[azure-core] Some resources trigger an infinite loop when making requests with the SDK clients

### ISSUE THREAD

**Issue by parsons90** [Azure/azure-sdk-for-python#31346]
- **Package Name**: azure-core
- **Package Version**: 1.28.1
- **Operating System**: Any
- **Python Version**: 3.9

**Describe the bug**
Clients which use the `PipelineClientBase` will enter an infinite loop when making requests for resource IDs with specific formats. 
The loop comes from this function: https://github.com/Azure/azure-sdk-for-python/blob/9cb79477740fed1d5057fe6a14cdc0ab10e332d3/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L79-L100
This occurs for resources where the resource name has a pair of curly braces and between the braces is a string with a `.`  in it. This triggers a KeyError when formatting the string and the function retries infinitely.

Here's an example resource ID which triggers the issue: `/subscriptions/1234abcd-1234-abcd-5678-1234abcd5678/resourceGroups/my-test-rg/providers/Microsoft.Sql/servers/mytestserver/databases/{Object.value}`

This is a valid name for a SQL database, the Azure portal allows you create a database with this name. 

**To Reproduce**
The easiest way to reproduce the error is to run the function in a Python shell.
1. Copy the `_format_url_section` function into a Python shell
2. The URL of the requests contains the resource ID, so just call the function with the example resource ID:
```
_format_url_section("/subscriptions/1234abcd-1234-abcd-5678-1234abcd5678/resourceGroups/my-test-rg/providers/Microsoft.Sql/servers/mytestserver/databases/{Object.value}")
```
3. The function will loop infinitely

**Expected behavior**
The function does not enter an infinite loop and the clients successfully make requests for these resources.

**Screenshots**
The Portal allows SQL databases with this name:
<img width="533" alt="Screenshot 2023-07-27 at 11 34 24 AM" src="https://github.com/Azure/azure-sdk-for-python/assets/43612608/c1475f64-83b6-4fc5-b228-75bd222bd7fe">

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
While I am working on the fix, could you help to provide a concrete example what is the expected output?

Thank you.

**Comment by ava-silver** [comment]
Hi @xiangyan99, 
I'm working with @parsons90, and for some context, an example of where we get here is from [client.metric_definitions.list](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2018_01_01/aio/operations/_metric_definitions_operations.py#L56). 

For a concrete example we get when debugging, within the method [format_url()](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L625), we would expect that the function `_format_url_section()`, when given a template like `//subscriptions/1234abcd-1234-abcd-5678-1234abcd5678/resourceGroups/my-test-rg/providers/Microsoft.Sql/servers/mytestserver/databases/{Object.value}/providers/Microsoft.Insights/metricDefinitions?api-version=2018-01-01` and empty kwargs, would just return the url path (the template arg) like it would for any other resource.

One other thing to note is through our testing we found any resource names containing `{*}` to be an issue, usually raising an `IndexError`.

Thanks for looking into this!

**Comment by xiangyan99** [comment]
Unfortunately, our current design is if the key is missing, we remove it from the final url.
So:
format_url("//subscriptions/1234abcd-1234-abcd-5678-1234abcd5678/resourceGroups/my-test-rg/providers/Microsoft.Sql/servers/mytestserver/databases/{Object.value}/providers/Microsoft.Insights/metricDefinitions?api-version=2018-01-01") will return "//subscriptions/1234abcd-1234-abcd-5678-1234abcd5678/resourceGroups/my-test-rg/providers/Microsoft.Sql/servers/mytestserver/databases/providers/Microsoft.Insights/metricDefinitions?api-version=2018-01-01"

**Comment by ava-silver** [comment]
As a design I don't have too much of an issue with that, it will cause an error later but that is not as much of a concern. If you try running the code with those inputs, you get an infinite loop, which is a much bigger issue.

Example:
```py
PipelineClientBase("some_base_url").format_url("//subscriptions/1234abcd-1234-abcd-5678-1234abcd5678/resourceGroups/my-test-rg/providers/Microsoft.Sql/servers/mytestserver/databases/{Object.value}/providers/Microsoft.Insights/metricDefinitions?api-version=2018-01-01")
```

Will run in a loop infinitely. This is the specific behavior we are worried about as it can cause bigger issues like DoS if not protected against.

**Comment by xiangyan99** [comment]
The fix is merged and will be available in next release.

**Comment by xiangyan99** [comment]
Assuming you are using azure-mgmt-monitor library, we just released a new version with the fix. (We encode url in the library hence it should not cause infinite loop in core).

We are working on a fix in the core too (thanks again for reporting the issue).

We believe you can get unblocked if you upgrade the azure-mgmt-monitor package.

Thank you.

**Comment by msyyc** [comment]
The fix version is https://pypi.org/project/azure-mgmt-monitor/6.0.2/
