### ISSUE TITLE
azure.ai.ml.dsl.pipeline decorate should support identity argument

### ISSUE THREAD

**Issue by gravesee** [Azure/azure-sdk-for-python#31351]
**Is your feature request related to a problem? Please describe.**
The PipelineJob python class and YAML schema supports an identity attribute, yet the dsl.pipeline decorator provides no way to pass this in.

**Describe the solution you'd like**
It is unclear whether pipelines should be usable with UserIdentityConfiguration. We are using a compute cluster where user ACLs are used to authenticate to ADLS gen v2. We can submit single jobs with the identity argument just fine.

**Describe alternatives you've considered**
We are currently setting the identity attribute on the PipelineJob instance directly. This seems like an anti-pattern.

**Additional context**
Are pipeline jobs intended to be used with UserIdentityConfiguration? Or this this an anti-pattern?

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by achauhan-scc** [comment]
closing as obsolete
