### ISSUE TITLE
Conversational Language Understanding Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#31363]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/README.md#conversational-summarization)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/2759ac45-ed5c-464f-a7a5-22273918dd32)

**Reason:**
Invalid role for conversation item. The supported roles are Customer, Agent for issue resolution summarization.

**Suggestion1:**
Add code
`
"role":"Agent",
`

**Suggestion2:**
Add code
`
"role": "Customer",
`

**Suggestion3:**
Add code
`
"role": "Agent",
`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/README.md#import-a-conversation-project)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/eedd65a5-1dd2-4fe9-ad64-ff45ffa1da18)

**Reason:**  
HttpResponseError: (InvalidArgument) The value `` provided for the parameter `StringIndexType` is invalid.
Code: InvalidArgument

**Suggestion:**
Update code to 
```
project={
        "assets": exported_project_assets,
        "metadata": {
            "projectKind": "Conversation",
            "settings": {"confidenceThreshold": 0.7},
            "projectName": "EmailApp",
            "multilingual": True,
            "description": "Trying out CLU",
            "language": "en-us",
            
        },
        "projectFileVersion": "2022-05-01",
        "StringIndexType": "Utf16CodeUnit"
    },
```

@rohit-ganguly  @lmazuel @kristapratico for notification.

**Comment by kashifkhan** [comment]
Thank you for the feedback @jerryshia  . We will investigate and get back to you asap.
