### ISSUE TITLE
Cognitive Search Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#31364]
1.
Section [link1](https://github.com/azure-sdk/azure-sdk-for-python/tree/main/sdk/search/azure-search-documents#creating-an-index):

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/f03d8b7c-37f2-4436-92d6-cde0776c3a0f)

**Reason:**
Client is not defined

**Suggestion:**
Add code
`
client = SearchIndexClient(service_endpoint, AzureKeyCredential(key))
`

@rohit-ganguly  @lmazuel @hector-norza  @pallavit  @xiangyan99 for notification.

**Comment by kashifkhan** [comment]
Thank you for the feedback @jerryshia . We will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
It is defined in above blocks. https://github.com/azure-sdk/azure-sdk-for-python/tree/main/sdk/search/azure-search-documents#querying

**Comment by xiangyan99** [comment]
Fixed.
