### ISSUE TITLE
Maps Render Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#31365]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-render/README.md#get-maps-attribution), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-render/README.md#get-maps-tile),[link3](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-render/README.md#get-maps-tileset),[link4](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-render/README.md#get-maps-static-image),[link5](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-render/README.md#get-maps-copyright-for-world):

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/57c89e2c-7df5-4a3b-afd7-bd9fdd4de232)

**Reason:**
Maps_render_client  is not defined

**Suggestion:**
Add code
`
credential = AzureKeyCredential(os.environ.get("AZURE_SUBSCRIPTION_KEY"))
maps_render_client = MapsRenderClient(credential=credential)
`

@rohit-ganguly @lmazuel  @markweitzel @johanste @alextts627 for notification.

**Comment by kashifkhan** [comment]
Thank you for the feedback @jerryshia  . We will investigate and get back to you asap.

**Comment by SaurabhSharma-MSFT** [comment]
@jerryshia The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
