### ISSUE TITLE
DefaultAzureCredential() cannot access az cli credentials

### ISSUE THREAD

**Issue by shobhit-coder** [Azure/azure-sdk-for-python#31369]
- **Package Name**:  azure.identity
- **Package Version**: 1.13.0
- **Operating System**: windows 11
- **Python Version**:  3.10.6
- **AZ CLI VERSION**: 2.50.0

**Describe the bug**
AZ CLI login isn't working with default azure credential

**To Reproduce**
az login
then run python code with DefaultAzureCredential()

**Expected behavior**
Login should succeed with az cli credentials.

**Screenshots**
I have enabled debug logs. here is the output:
<img width="652" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/22573271/417e290a-f995-461c-8a5a-dd3c91c19624">
<img width="629" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/22573271/de2644c1-ea76-416d-a1f7-79e56ece9a37">

**Additional context**
When i manually run that az command, i get this error. but in the troubleshoot, the given command is different, and that works:
az account get-access-token --output json --resource https://management.core.windows.net

<img width="834" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/22573271/67e5b3bc-b272-4ebb-89c1-f021387b7023">

**Comment by kashifkhan** [comment]
Thank you for the feedback @shobhit-coder  . We will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

The resource information is passed in by the caller.

Could you tell us which library are you using and if possible, share some snippets?

Thanks.

**Comment by shobhit-coder** [comment]
here is a snippet:
```
import os, uuid
from azure.identity import DefaultAzureCredential, AzureCliCredential
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient

import logging
import sys

logger = logging.getLogger('azure.identity')
logger.setLevel(logging.DEBUG)

handler = logging.StreamHandler(stream=sys.stdout)
formatter = logging.Formatter('[%(levelname)s %(name)s] %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)


try:
    print("Azure Blob Storage Python quickstart sample")
    account_url = "https://RANDOM.blob.core.windows.net"
    default_credential = DefaultAzureCredential()
    container_name = "mycontainer"

    # Create the BlobServiceClient object
    blob_service_client = BlobServiceClient(account_url, credential=default_credential)
    print(default_credential.get_token("openid"))

    download_file_path = os.path.join("downloads/", "blob.gz")
    container_client = blob_service_client.get_container_client(container= container_name) 
```

**Comment by shobhit-coder** [comment]
storage blob version 12.17.0

**Comment by xiangyan99** [comment]
print(default_credential.get_token("openid"))

I guess this line caused the issue?

**Comment by shobhit-coder** [comment]
my bad! i probably forgot about that line of code. apologies.
