### ISSUE TITLE
How to export all/some documents from Azure Search Index

### ISSUE THREAD

**Issue by gitprojects619** [Azure/azure-sdk-for-python#31406]
By documents , I mean each line item in the Azure Search Index 

I need to frequently see what's present in my search index, modify/delete some line items from there. Have been trying to find python scripts/methods that can help me do this easily but seems like there is no straight forward way to this.

**Ask** : I basically want to export all rows/ some rows(based on filters on `filterable fields`) from the Search Index I already have in place. Just want to visualize everything in the index in a dataframe/json

**I have already seen the below resources:** 
1. [SearchIndexClient Class documentation](https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.indexes.searchindexclient?view=azure-python) - no method to achieve this
2. [SearchClient Class documentation](https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.searchclient?view=azure-python) - no method to achieve this
3. [Export data from an Azure Cognitive Search index - Azure Samples](https://learn.microsoft.com/en-us/samples/azure-samples/azure-search-dotnet-samples/export-data/) - is not in Python

**I have already looked into [this](https://stackoverflow.com/questions/59539229/azure-search-export-results-to-csv) answer from 2019, but it's too complicated as:**  
1. it has variables like facet_value, facet_fields. The page size is being set to 1000 (is this a limitation?) 
2. what does page_size mean compared to the Document object that Azure Search Index calls each row in the index as

Any other answer on Stackoverflow doesn't really answer this.. I am surprized that there's no easy way to do this

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Not 100% sure if I understand corretly, does 

```py
search_client = SearchClient(service_endpoint, index_name, AzureKeyCredential(key))
results = search_client.search(search_text="*")
for result in results:
    print(result)
```

work for you?

**Comment by gitprojects619** [comment]
Thanks for the reply. Do you expect this snippet to give out all rows from the search index without any exceptions?
Is there a limitation on the number of rows that can be extracted? I will have 100k rows in the index.

@xiangyan99 @kashifkhan

**Comment by gitprojects619** [comment]
@xiangyan99 Moreover, this would now cover the case where I want to extract based on some filters. Is there a less hacky way to do this

**Comment by xiangyan99** [comment]
> Thanks for the reply. Do you expect this snippet to give out all rows from the search index without any exceptions? Is there a limitation on the number of rows that can be extracted? I will have 100k rows in the index.
> 
> @xiangyan99 @kashifkhan

We do pagination when the service returns multiple results.

(This is what you found by "The page size is being set to 1000").

Each query returns no more than 1000 results.

`for result in results:`

will get all results page by page.

Please let us know if it does not work.

**Comment by xiangyan99** [comment]
> @xiangyan99 Moreover, this would now cover the case where I want to extract based on some filters. Is there a less hacky way to do this

We expose some parameters in search method to do the filtering.

Does this work for you?

**Comment by gitprojects619** [comment]
I willl test today and let you know. Would be grateful if this issue is kept open until tomorrow morning.
