### ISSUE TITLE
Azure python SDK file descriptor leak under multi-thread stress enviroment

### ISSUE THREAD

**Issue by lyan-git** [Azure/azure-sdk-for-python#3142]
We recently found file descriptor leaking while stress testing with Azure solution. Two APIs we nailed down so far:
1.	subnets.list
2.	storage_account.list_key
We are using Azure 2.0.0 running on ubuntu 14.0.4. Our application use default number of file descriptor 1024(soft limit) and 4096 hard limit. 
We found file descriptor leaking is caused by using the python uuid lib under multi-thread environment.

**Comment by lmazuel** [comment]
THanks @lyan-git !
After investigation, I found several link that indeed shows uuid1 and thread is a complicated story:
https://stackoverflow.com/questions/25007264/uuid-uuid1-uuid-generate-time-and-threads
https://github.com/andymccurdy/redis-py/issues/601

Fast workaround, at the beginning of your app:
```python
import uuid
uuid.uuid1 = uuid.uuid4
```
Do this *only* if you are sure your application or any of the not Azure one does not depend on the uuid1 behavior to work.

Secure workaround:
Disable the automatic x-ms-client-request-id header and set it yourself for each call:
```python
# For each client
client.config.generate_client_request_id = False

# For each call, pass this:
custom_headers={'x-ms-client-request-id': str(uuid.uuid4())}
```
If you don’t provide this header, the call will work but you might disable part of the cache system of ARM and slow down your app.

Side note for reference:
https://stackoverflow.com/questions/1785503/when-should-i-use-uuid-uuid1-vs-uuid-uuid4-in-python

**Comment by lmazuel** [comment]
SDK is using "uuid4" by default now, closing
