### ISSUE TITLE
Missing Azure Service Bus message properties in Python SDK message, only message body available

### ISSUE THREAD

**Issue by lurifaxel** [Azure/azure-sdk-for-python#31453]
- **Package Name**: azure-servicebus
- **Package Version**: 7.11.1
- **Operating System**: MacOS Ventura 13.4.1
- **Python Version**: 3.10.12

**Describe the bug**
Only the message body is available when receiving them from an Azure Service Bus Topic Subscription. The message properties (both broker properties and custom properties) are missing.

**To Reproduce**
1. Create a service bus client from connection string
2. Create a receiver using `servicebus_client.get_subscription_receiver`
3. Enumerate the messages in the receiver
4. Inspect message contents, e.g. with `print(str(msg))`

**Expected behavior**
I was expecting properties such as message_id, content_type, custom_properties and body to be there. They are not, and the contents of the body are the only available information on the message (and there is no property named body either, they are all in the root of the object).

**Comment by kashifkhan** [comment]
Thanks for your feedback @lurifaxel . We will investigate and get back to you asap.

**Comment by swathipil** [comment]
Hi @lurifaxel - In order to print all properties, you can call `print(repr(message))`. `print(str(message))` will only print the body. Thanks!
