### ISSUE TITLE
Please provide an example of how to use the Azure Consumption python sdk

### ISSUE THREAD

**Issue by weltonrodrigo** [Azure/azure-sdk-for-python#31473]
Hi,

please provide in that page an example of how to use the Azure Consumption python sdk.

Something like: how to create a csv export (like [the one available at the azure portal](https://portal.azure.com/#view/Microsoft_Azure_Ea/EnterpriseMenuBlade/~/enrollmentUsageAndCharges/scopeId/%2Fproviders%2FMicrosoft.Billing%2FbillingAccounts%2F9999999/noParentBlade~/false)) of the billing period `202306` for the billingAccount `9999999`.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c273bd7f-1d12-2088-d726-9c926cfdf78c
* Version Independent ID: 7efc43f5-208d-1fb9-9c56-44d52d1703bc
* Content: [Azure Consumption SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/consumption?view=azure-python)
* Content Source: [docs-ref-services/latest/consumption.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/consumption.md)
* Service: **consumption**
* GitHub Login: @sandeepnl
* Microsoft Alias: **sandeepnl**

**Comment by catalinaperalta** [comment]
@weltonrodrigo thanks for reaching out, could you please provide a link to the page you would like to see the example on? I'm looping in @msyyc who can help investigate.

**Comment by weltonrodrigo** [comment]
> @weltonrodrigo thanks for reaching out, could you please provide a link to the page you would like to see the example on? I'm looping in @msyyc who can help investigate.

Those issues are generated from a button in the doc pages. The url is in the metadata it inserted below my comment: https://learn.microsoft.com/en-us/python/api/overview/azure/consumption?view=azure-python

**Comment by ChenxiJiang333** [comment]
Hi @weltonrodrigo  
Please know that Python SDK is generated with swagger automatically. 
Related swagger is [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/stable/2023-05-01/consumption.json#L42 ) and it seems that there's no `export` method but only `list`. 
If you want to export usage details through Python SDK. You can try to first list them, then export the results to csv manually.

Or, you can request a new feature about this method by opening an issue in https://github.com/Azure/azure-rest-api-specs/issues and mark it with label `feature request`. Both Python SDK and examples will be updated once the swagger fixed.

Hope this answer can help you, thanks a lot.

**Comment by weltonrodrigo** [comment]
I see that the portal calls the management api to generate the CSV. So the rest endpoint is there but I suppose it's just not exported as a python library?

**Comment by ChenxiJiang333** [comment]
Thanks for the feedback. 
The api does exist as you mentioned, yet for some reason it's not defined in the latest [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/stable/2021-10-01/consumption.json#L42). Which also means that the python sdk cannot contain such method unless the swagger updated to add the `download` definition. As it was mentioned, the whole python sdk is generated on the basis of that.
That's why to fix it, you need to send your request to the service team by opening an issue in https://github.com/Azure/azure-rest-api-specs.

**Comment by weltonrodrigo** [comment]
> Thanks for the feedback. The api does exist as you mentioned, yet for some reason it's not defined in the latest swagger shows [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/stable/2021-10-01/consumption.json#L42). Which also means that the python sdk cannot contain such method unless the swagger updated to include the api like it once included in the [past](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/preview/2019-05-01-preview/consumption.json#L167). As it was mentioned, all the models and methods in the sdk is generated based on that. That's why to fix it, you need to send your request to the service team by opening an issue in https://github.com/Azure/azure-rest-api-specs. Then we could generate and release a new version of sdk which supports the method you need,

Maybe you could open that with them? I suppose an internal request will have much more force.

**Comment by ChenxiJiang333** [comment]
> > Thanks for the feedback. The api does exist as you mentioned, yet for some reason it's not defined in the latest swagger shows [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/stable/2021-10-01/consumption.json#L42). Which also means that the python sdk cannot contain such method unless the swagger updated to include the api like it once included in the [past](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/preview/2019-05-01-preview/consumption.json#L167). As it was mentioned, all the models and methods in the sdk is generated based on that. That's why to fix it, you need to send your request to the service team by opening an issue in https://github.com/Azure/azure-rest-api-specs. Then we could generate and release a new version of sdk which supports the method you need,
> 
> Maybe you could open that with them? I suppose an internal request will have much more force.

Sure, a request has been sent and I would keep following it.
