### ISSUE TITLE
When will be Azure form recognizer 2023-07-31 version released

### ISSUE THREAD

**Issue by akashtalole** [Azure/azure-sdk-for-python#31472]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.2.1
- **Operating System**: Windows 11
- **Python Version**: 3.10

**Describe the bug**
Azure form recoginzer version 2022-08-31 is not properly detecting complex structure. It is mixing up some columns into 1 column.

**To Reproduce**
1. Use version 2022-08-31
2. Upload complex pdf doc with complex table structure
3. output result for table is not correct

**Expected behavior**
table structure must be maintained 

**Screenshots**

**Additional context**
Kindly released sdk version ASAP. I have tested latest version in form recoginzer studio and it is working well.

**Comment by FWin22** [comment]
Would love to see the new release added to the Python SDK as well

**Comment by catalinaperalta** [comment]
Thanks for reaching out! We are planning on releasing a new version of the SDK with support for the new service API version this week I'll post here once it's been released. As for the issues with the quality of data returned from the service looping in @ctstone @vkurpad @bojunehsu

**Comment by catalinaperalta** [comment]
Hello! We just released azure-ai-formrecognizer 3.3.0 with support for the latest service api version "2023-07-31": https://pypi.org/project/azure-ai-formrecognizer/3.3.0/
