### ISSUE TITLE
There is no version listed even though the link is for "version"

### ISSUE THREAD

**Issue by mjturtora** [Azure/azure-sdk-for-python#31486]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 333ec75f-10d1-1e2a-7855-0f33e398e5e8
* Version Independent ID: de9e3410-b4cd-5a38-e168-757f4be1ba81
* Content: [azure.cognitiveservices.vision.computervision.version module](https://learn.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-computervision/azure.cognitiveservices.vision.computervision.version?view=azure-python-preview)
* Content Source: [preview/docs-ref-autogen/azure-cognitiveservices-vision-computervision/azure.cognitiveservices.vision.computervision.version.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/preview/docs-ref-autogen/azure-cognitiveservices-vision-computervision/azure.cognitiveservices.vision.computervision.version.yml)
* GitHub Login: @VSC-Service-Account

**Comment by xiangyan99** [comment]
Thanks for your feedback. We will take a look.

**Comment by swathipil** [comment]
Hi @mjturtora - Apologies for the delayed response. This package is being deprecated and will be replaced by [azure-ai-vision-imageanalysis](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/vision/azure-ai-vision-imageanalysis). If this issue still persists in the replacement package, please file an issue for the new package.
