### ISSUE TITLE
"ServiceBusReceiver" is not iterable

### ISSUE THREAD

**Issue by MaxiPigna** [Azure/azure-sdk-for-python#31491]
I get this warning on VS Code, even if code works as expected.
![image](https://github.com/Azure/azure-sdk-for-python/assets/33937977/5d8747ad-2a90-4269-b7e6-b6550cc73e9c)

Same error with the sample published [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/async_samples/receive_iterator_queue_async.py).

Pylance: v2023.8.10
Python: 3.11.4
azure-servicebus: 7.11.1

**Comment by kashifkhan** [comment]
Thanks for the feedback @MaxiPigna . We will investigate and get back to you asap.

**Comment by kashifkhan** [comment]
@MaxiPigna we tried reproducing this with the exact set up you provided in dev containers, our local set ups between windows & wsl and were unable to do so. Can you check if your venv is properly set up or a refresh still shows this issue for you ?

**Comment by MaxiPigna** [comment]
I am using dev-container with this image `mcr.microsoft.com/devcontainers/python:1-3.11-bullseye` and the issue persists.

**Comment by kashifkhan** [comment]
chatted with @MaxiPigna yesterday off. This issue happens with the new type checking option in vscode. The code works as expected and in a non blocker. We have an incoming PR to add in more type information in to Service Bus that we hope will resolve this

**Comment by kashifkhan** [comment]
spoke with @MaxiPigna offline after a few more tests. Tried out pycharm as well and the error didn't propagate there. Advised them to open an issue with vscode as it seems to be a problem with the type checker that is shipped and not the code.
