### ISSUE TITLE
[azure-mgmt-servicebus] Creating Topic Rule "Bad Request"

### ISSUE THREAD

**Issue by ChrisBNR** [Azure/azure-sdk-for-python#3149]
Following an example similar to: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-servicebus/tests/test_azure_mgmt_servicebus_topic.py#L67 , if you do not apply all 3 access rights (i.e. [AccessRights.manage, AccessRights.send, AccessRights.listen]) when creating a rule for a specified topic an error is returned: ErrorResponseException: Operation returned an invalid status code 'Bad Request'.

topic_operations.py:
[L446]     `request = self._client.put(url, query_parameters)`
[L447]     `response = self._client.send(request, header_parameters, body_content, stream=False, **operation_config)`

```
url = https://management.azure.com/subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.ServiceBus/namespaces/xxxxx/topics/xxxxx/authorizationRules/AuthorizationRule
query_parameters = {'api-version': '2017-04-01'}
body_content = {'properties': {'rights': ['Manage']}}
header_parameters = {'accept-language': 'en-US', 'Content-Type': 'application/json; charset=utf-8', 'x-ms-client-request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'}

```

**Comment by lmazuel** [comment]
For what I understand, it's a RestAPI issue right?

**Comment by ChrisBNR** [comment]
I believe that is correct, the response status code after the send request is 400.

**Comment by bearrito** [comment]
Maintainers is there an update on this?

**Comment by lmazuel** [comment]
@bearrito I contacted the team explicitly right now. I would suggest to wait a little, but if you don't hear anything in this thread by the end of the week, open a support ticket.

**Comment by axisc** [comment]
@ChrisBNR  - apologies for the delay in the response.

could you try changing 
`body_content = {'properties': {'rights': ['Manage', 'Send', 'Listen']}} `

That should work. Let me know if it doesn't

**Comment by jfggdl** [comment]
@ChrisBNR, The error reported should be according to the behavior expected. Per our documentation in https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas, the Manage right includes both "Send" and "Receive" rights. This is the relevant part of the documentation:

"Manage' - Confers the right to manage the topology of the namespace, including creating and deleting entities
The 'Manage' right includes the 'Send' and 'Receive' rights."

I will be closing this issue, but feel free to reopen it if you have any additional questions.
