### ISSUE TITLE
azure-mgmt-network not correctly seeing App Gateway WAF V2 enabled?

### ISSUE THREAD

**Issue by tc-mgriff** [Azure/azure-sdk-for-python#31497]
package- **azure-mgmt-network**
Version- **azure-mgmt-5.0.0.zip**
OS- **macOS**
Python- **Python 3.11.4**

**Describe the bug**
It looks like the package isn't correctly seeing that the WAFv2 is enabled for App Gateway.

`'web_application_firewall_configuration': None, 'firewall_policy': <azure.mgmt.network.models._models.SubResource object at 0x10396dc10>`

**To Reproduce**
```
from azure.identity import DefaultAzureCredential
from azure.mgmt.network import NetworkManagementClient


# Replace the following variables with your Azure subscription ID and resource group name
subscription_id = "XXXX"
resource_group_name = "XXXX"
application_gateway_name = "XXXX"

# Initialize the Azure credentials
credentials = DefaultAzureCredential()

# Initialize the Network Management Client
network_client = NetworkManagementClient(credentials, subscription_id)

# Get the Application Gateway WAF policy
try:
    application_gateway = network_client.application_gateways.get(
        resource_group_name, application_gateway_name
    )
    
    #print application_gateway Waf v2 configuration
    print("Application Gateway WAF v2 Configuration:")
    print(f"Appgateway: {application_gateway}")
    print(f"ID: {application_gateway.id}")
    print(f"Name: {application_gateway.name}")
    print(f"Type: {application_gateway.type}")  
    print(f"Web Application Firewall (WAF) Policy: {application_gateway.web_application_firewall_configuration}")


except Exception as e:

    print(f"Error: {str(e)}")
```

**Expected behavior**
It should show that the waf is enabled and you should be able to look at the settings

**Comment by lmazuel** [comment]
Hello, can you clarify what version of the package you are using? 5.0.0 is unclear, or you are using a very old version. Pip freeze should tell you the exact version of `azure-mgmt-core`. Thanks.
cc @msyyc

**Comment by tc-mgriff** [comment]
`azure-mgmt-core==1.4.0`

**Comment by ChenxiJiang333** [comment]
Seems you could get it through `application_gateway.sku.tier`.

**Comment by tc-mgriff** [comment]
Is this comment for me? I'm not seeing any additional info here. It would be nice if the WAFv2 enabled flag and policy configuration details followed the same object model as v1.

I had to open a similar request for https://github.com/microsoft/ARI and i think they had to call the updated API for App Gateway.

**Comment by ChenxiJiang333** [comment]
> Is this comment for me? I'm not seeing any additional info here. It would be nice if the WAFv2 enabled flag and policy configuration details followed the same object model as v1.
> 
> I had to open a similar request for https://github.com/microsoft/ARI and i think they had to call the updated API for App Gateway.

Hi @tc-mgriff, If you want to open a request for an update of api, the correct link is https://github.com/Azure/azure-rest-api-specs/issues and please mark it with label `feature request`.

**Comment by tc-mgriff** [comment]
@xiangyan99 i think you misunderstand my statement. The python package is not calling the updated api to get the current information for the Application Gateway WAF v2 information. It does utilize the azure api's to pill this information, no?

Either way shouldn't WAFv1 and WAFv2 enabled be in the same objects?
/unresolve

**Comment by ChenxiJiang333** [comment]
Sorry for the late response.
Whether WAF or WAF V2, they call the same api to get information, so it's possibly a service issue: https://github.com/Azure/azure-rest-api-specs/issues/25329.
