### ISSUE TITLE
TypeError: 'AzureSqlTableDataset' object is not subscriptable

### ISSUE THREAD

**Issue by mrluthra** [Azure/azure-sdk-for-python#31505]
Getting dataset properties throwing error

```
#!/usr/bin/env python

from azure.identity import DefaultAzureCredential
from azure.mgmt.datafactory import DataFactoryManagementClient
from azure.mgmt.datafactory.models import DatasetResource
from azure.identity import DefaultAzureCredential
from azure.identity import ClientSecretCredential
import json

# Replace with your Azure subscription ID and resource group name
subscription_id = '<subid>'
credential = DefaultAzureCredential()
resource_group_name = "<myrg>"
data_factory_name = "<myadf>"

adf_client = DataFactoryManagementClient(credential, subscription_id)

# Define dataset properties
dataset_name = "test_dataset"
dataset = '{"properties": {"linkedServiceName": { "referenceName": "AzureSqlDatabase1","type": "LinkedServiceReference"},"type": "AzureSqlTable","folder": {"name": "azuresql_test"},"typeProperties": {"schema": "sales","table": "customers"}}}'
dataset = json.loads(dataset)
print(dataset)

# Create the dataset in the Data Factory
adf_client.datasets.create_or_update(resource_group_name, data_factory_name, dataset_name, dataset)
print("created dataset")

# Fetch the dataset schema
print("Fetch the dataset schema")
dataset = adf_client.datasets.get(resource_group_name, data_factory_name, dataset_name)
print('dataset', dataset)
schema = dataset.properties["typeProperties"]["schema"]

# Now you can use the 'schema' dictionary to get information about column names, data types, etc.
print(schema)
```

Dataset created but I am getting error, while fetching the dataset schema,
TypeError: 'AzureSqlTableDataset' object is not subscriptable

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac5193bb-f6de-6274-54fa-af2b3898eed6
* Version Independent ID: 6fa6f87f-6c5a-ed5f-7483-2fe202d22d85
* Content: [Microsoft Azure SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-datafactory-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/mgmt-datafactory-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/mgmt-datafactory-readme.md)
* Service: **datafactory**
* GitHub Login: @hvermis
* Microsoft Alias: **hvermis**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Try `schema = dataset["properties"]["typeProperties"]["schema"]`

**Comment by mrluthra** [comment]
@ChenxiJiang333 same error

```
>>> schema = dataset["properties"]["typeProperties"]["schema"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'DatasetResource' object is not subscriptable
```

**Comment by ChenxiJiang333** [comment]
> @ChenxiJiang333 same error
> 
> ```
> >>> schema = dataset["properties"]["typeProperties"]["schema"]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: 'DatasetResource' object is not subscriptable
> ```

Hi, @mrluthra 
Sorry if confused you. I have tried the code and found the way that you can get the schema through
`schema = dataset.properties.schema_type_properties_schema`
or
`schema = dataset.as_dict()["properties"]["schema_type_properties_schema"]`

Thanks for your patient. Please have another try and I will be very appreciative.

**Comment by mrluthra** [comment]
Thanks @ChenxiJiang333 for the new set of commands. 
Both commands return me just schema name of the table

```
>>> schema = dataset.properties.schema_type_properties_schema
>>> schema
'sales'
>>> schema = dataset.serialize()["properties"]["typeProperties"]["schema"]
>>> schema
'sales'
```

I am looking for api call to get schema (including column names and type) similar output what we get on UI when click on Import schema button.

![Import_Schema](https://github.com/Azure/azure-sdk-for-python/assets/78226166/45bed2c4-9fe1-47a8-a9e1-b02f16420350)

**Comment by ChenxiJiang333** [comment]
@mrluthra 

After schema imported and changes published, you could get column names and types using `schema = dataset.properties.schema` and the output is like:
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/b3ea868a-f9d5-4a43-8d3f-ff40774fbeb9)

But for importing schema from sql database, I guess the api is as below and it's not supported by python sdk. 
```
https://dpeastus.svc.datafactory.azure.com/dataplane/subscriptions/{subscriptions}/resourcegroups/{resourcegroups}/providers/Microsoft.DataFactory/factories/{factories}/executeTabularData?commandBehavior=SchemaOnly&previewCount=10&api-version=2018-06-01
```

**Comment by mrluthra** [comment]
Thanks @ChenxiJiang333 This is the major blocker to deploy ADF objects at scale. 
I am using python SDKs to deploy objects in azure data factory, including datasets, dataflows & pipeline at scale. I can't switch to UI to import schema for 100s of datasets.

Its not just for sql database, but any dataset type, its same behavior.

Any idea, if any other deployment methods like Terraform will have same limitation?
How can I raise this feature request to have this dataset import support available by python sdk?

**Comment by ChenxiJiang333** [comment]
@mrluthra
To raise a feature request, please open an issue in https://github.com/Azure/azure-rest-api-specs/issues and mark with label `feature request`.

**Comment by mrluthra** [comment]
Thanks @ChenxiJiang333 for your help with this, and confirming the issue here. I raised new issue but seems like don't have access to add labels.

https://github.com/Azure/azure-rest-api-specs/issues/25391
