### ISSUE TITLE
How to set environment variables when building an environment

### ISSUE THREAD

**Issue by jinlow** [Azure/azure-sdk-for-python#31565]
**Is your feature request related to a problem? Please describe.**
I want to be able to set environment variables when building an `azure.ai.ml.entities.Environment`.

**Describe the solution you'd like**
I want to be able to pass in environment variables when creating the environment, for example consider the `environment_variables` parameter that could be added like this...

```python
ml_client = MLClient(
    credential=cred,
    subscription_id=os.environ["SUBSCRIPTION_ID"],
    resource_group_name=os.environ["RESOURCE_GROUP_NAME"],
    workspace_name=os.environ["WORKSPACE_NAME"],
)

env = Environment(
    name=env_name,
    image="mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04",
    conda_file=str(conda_file_path),
    environment_variables={"FOO": "BAR"}
)


ml_client.environments.create_or_update(env)
```

**Describe alternatives you've considered**
I haven't been able to find any alternatives to this.

**Additional context**
I need to be able to do this to build an environment without pip dependencies. This is because the issue I am having described on issue #31545 which hasn't been resolved yet.

**Comment by iscai-msft** [comment]
@Azure/ml-github-maintainers

**Comment by iscai-msft** [comment]
@jinlow thank you for opening this issue, the ML team will get back to you

**Comment by fschlz** [comment]
I also need this feature!
