### ISSUE TITLE
Mypy complains with new version of azure-core

### ISSUE THREAD

**Issue by ludokriss** [Azure/azure-sdk-for-python#31564]
https://github.com/Azure/azure-sdk-for-python/blob/a0374d47632be335354ae2efbf456876954fc5e7/sdk/core/azure-core-tracing-opentelemetry/README.md?plain=1#L47

The above line has a different typing of the tracing implementation than the current one implements. Is the docs up to date or is there a new way of achieving it?

**Comment by ludokriss** [comment]
for reference, this is the error:

´´´
error: Incompatible types in assignment (expression has type "type[OpenTelemetrySpan]", variable has type "str | type[AbstractSpan] | None")  [assignment]
´´´

**Comment by pvaneck** [comment]
Thanks, @ludokriss. Several typing updates to azure-core have been added, so there is likely a devation in the OpenTelemetrySpan's implementation of AbstractSpan that is prompting that mypy error. Probably some method signature typing is off somewhere. I'll spend some time investigating soon and will update the docs if necessary.

In the meantime, one way to get mypy to stop complaining is to set the tracing implementation using a string:

```python
settings.tracing_implementation = "opentelemetry"
```
