### ISSUE TITLE
azure-mgmt-synapse - How to query pipeline runs by workspace

### ISSUE THREAD

**Issue by LeonardoSanBenitez** [Azure/azure-sdk-for-python#31577]
* **Package Name:** azure-mgmt-synapse
* **Package Version:** 2.1.0b5
* **Operating System:** Linux
* **Python Version:** 3.8.10

I would like to get all pipeline executions for a given workspace, similar to what is done in [this endpoint of graph API](https://learn.microsoft.com/en-us/rest/api/synapse/data-plane/pipeline-run/query-pipeline-runs-by-workspace?tabs=HTTP).

This functionality seems to be implemented in the method [PipelineRunOperations.query_pipeline_runs_by_workspace](https://learn.microsoft.com/en-us/python/api/azure-synapse/azure.synapse.artifacts.operations.pipelinerunoperations?view=azure-python-preview#azure-synapse-artifacts-operations-pipelinerunoperations-query-pipeline-runs-by-workspace), but i don't know how to invoke this method.

**To Reproduce**
```python
from azure.mgmt.synapse import SynapseManagementClient
from azure.identity import DefaultAzureCredential

subscription_id = "xxx"
resource_group = "xxx"
workspace_name = "xxx"
credential = DefaultAzureCredential()
client = SynapseManagementClient(
    credential=credential,
    subscription_id=subscription_id,
)

client.operations.query_pipeline_runs_by_workspace()
```

**Expected behavior**
Get pipelines

**Actual behavior**
`AttributeError: 'Operations' object has no attribute 'query_pipeline_runs_by_workspace'`

**Comment by kashifkhan** [comment]
Thank you for the feedback @LeonardoSanBenitez . We will investigate and get back to you asap.

**Comment by ChenxiJiang333** [comment]
I guess you need to use package `azure-synapse-artifacts` and here's the example
```
from azure.synapse.artifacts import ArtifactsClient
from azure.identity import DefaultAzureCredential

subscription_id = "xxx"
resource_group = "xxx"
endpoint = "xxx"

credential = DefaultAzureCredential()
client = ArtifactsClient(
    credential=credential,
    subscription_id=subscription_id,
    endpoint=endpoint
)

client.pipeline_run.query_pipeline_runs_by_workspace(filter_parameters={"lastUpdatedAfter": "2023-07-20T00:00:00.0000000Z", "lastUpdatedBefore": "2023-08-15T00:00:00.0000000Z"})
```

**Comment by LeonardoSanBenitez** [comment]
It worked, thank you very much :smile:
