### ISSUE TITLE
QueueMessage class attributes lack type hints

### ISSUE THREAD

**Issue by andrewDoing** [Azure/azure-sdk-for-python#31571]
- **Package Name**: 
  - azure-storage-queue
- **Package Version**: 
  - 12.6.0
- **Operating System**:
  - Windows
- **Python Version**: 
  - 3.10.11

**Describe the bug**
QueueMessage class attributes lack type hints

**To Reproduce**
1. Observe the QueueMessage class code in `_models.py`

**Expected behavior**
I expect those attributes to have type hints (there are probably other cases where they could be added as well). I suspect there may be a reason to omit them (backwards compatibility perhaps?) but I figured I would file a bug report to find out.

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @andrewDoing . We will investigate and get back to you asap.

**Comment by vincenttran-msft** [comment]
Hi @andrewDoing Andrew, thanks for reaching out! We are actively working on a huge typing overhaul, and coincidentally the `azure-storage-queue` package is the first package to get this overhaul! Rest assured, this lack of type hints will be resolved as part of this typing effort (and this work will be done across the whole `azure-sdk-for-python`).

Unfortunately, this is a rather large task and so I don't have a great ETA on when the work will be completed, but I will let you know as soon as it is making its way in 😄 

Thanks!

**Comment by vincenttran-msft** [comment]
Hi @andrewDoing Andrew, sorry for the delay, but I wanted to make you aware that the **huge** Queue typing overhaul changes has been merged in #29045. We will follow up with a release shortly that should contain these changes 😄 With that being said, I will go ahead and close out this issue. Thanks again for your inquiry!

Thanks!
