### ISSUE TITLE
begin_import_image command is hanging when uploading images from one container registry to another

### ISSUE THREAD

**Issue by patrykkulik-microsoft** [Azure/azure-sdk-for-python#31579]
- **Package Name**: Azure CLI
- **Package Version**: 2.48.1
- **Operating System**: Linux
- **Python Version**: 3.8.10

**Describe the bug**
We are running the `begin_import_image` command on a ContainerRegistryManagementClient in our Azure CLI extension.  If this command is run multiple times, the command starts to hang. 

 I've hit the same issue when trying to upload 8 artifacts and the command usually starts hanging on the 6th artifact to be uploaded. I have tried changing the order of the artifacts to be uploaded. This did not fix the issue. 

I had a look at the debug logs for this issue and it looks like the POST request triggered by the `begin_import_image` is triggered correctly but the subsequent GETs triggered by the poller which we have implemented as shown below, are continually receiving a 202 response and never succeed despite waiting for up to 1 hour. 

```python 

result_poller = container_registry_client.begin_import_image(
       resource_group_name=target_registry_resource_group_name,
       registry_name=target_registry_name,
       parameters=import_parameters,
)

LongRunningOperation(cli_ctx, "Importing image...")(result_poller)
```

**To Reproduce**
1. Set up a container registry in Azure with at least 8 different images
2. Set up another empty container registry
3. Write a Python script which utilises the SDK to copy the images from one ACR to the other in a for loop. Use the code pasted above for the actual import image operation
4. Try running the script

**Expected behavior**
All the images should be uploaded and the command should not hang. 

**Screenshots**
N/A

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @patrykkulik-microsoft . We will investigate and get back to you asap.

**Comment by ChenxiJiang333** [comment]
Hi @patrykkulik-microsoft

Seems it's caused by service behavior, please open an issue in https://github.com/Azure/azure-rest-api-specs/issues for suggestions.
