### ISSUE TITLE
Unable to update TLS version using Python management SDK on Service bus namespace

### ISSUE THREAD

**Issue by testenvmicro** [Azure/azure-sdk-for-python#31580]
- **Package Name**: azure-mgmt-servicebus
- **Package Version**: 7.1.0 and 8.2.0
- **Operating System**: Windows
- **Python Version**: Python 3.6 and 3.7

**Describe the bug**
This morning I've been trying to change/update the TLS version of my Service Bus namespace using the Python SDK. However, every time I run the code, I can make changes to other components of the namespace, however the TLS version remains the same. For example, here's the code:

-----------------------------------------
import os

from azure.identity import DefaultAzureCredential, AzureCliCredential
from azure.mgmt.servicebus import ServiceBusManagementClient

def main():

SUBSCRIPTION_ID = "SUBSCRIPTION_ID"
GROUP_NAME = "RESOURCEGROUPNAME"
NAMESPACE = "SERVICEBUSNAMESPACE"

# Create client
servicebus_client = ServiceBusManagementClient(
credential=AzureCliCredential(),
subscription_id=SUBSCRIPTION_ID
)

# Get namespace
namespace = servicebus_client.namespaces.get(
GROUP_NAME,
NAMESPACE
)
print("Get namespace:\n{}".format(namespace))

# Update namespace
namespace = servicebus_client.namespaces.update(
GROUP_NAME,
NAMESPACE,
{
"properties": {
"minimumTlsVersion": "1.2"
}
}
)
print("Update namespace:\n{}".format(namespace))

if __name__ == "__main__":
main()

-------------------------------------------
My namespace currently is on 1.1 so I ran the code, but it did not change the version to 1.2, regardless of the Python version or azure-mgmt-servicebus I have tested both below:

Python 3.6, azure-mgmt-servicebus==7.1.0 
Python 3.7, azure-mgmt-servicebus==8.2.0 

Both got the same result.

**Expected behavior**
I do expect to be able to change the version of TLS.

**Additional context**
If I want to update tags, I can without a problem. Reference https://github.com/Azure/azure-sdk-for-python/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by kashifkhan** [comment]
Thank you for the feedback @testenvmicro . We will investigate and get back to you asap.

**Comment by ChenxiJiang333** [comment]
Hi, @testenvmicro 
azure-mgmt-servicebus generated based on multi api versions, and I found that `minimumTlsVersion` is defined in version `2022-10-01-preview` under method `create_or_update`. So you need to create a client using different version and change the method.
The main code is like:
```
    SUBSCRIPTION_ID = "xxx"
    GROUP_NAME = "xxx"
    NAMESPACE = "xxx"

    servicebus_client = ServiceBusManagementClient(
    credential=AzureCliCredential(),
    subscription_id=SUBSCRIPTION_ID,
    api_version="2022-10-01-preview"
    )

    namespace = servicebus_client.namespaces.begin_create_or_update(
    GROUP_NAME,
    NAMESPACE,
    {"location": "eastus","properties": {"minimumTlsVersion": "1.2"}})
    print("Update namespace:\n{}".format(namespace.result()))
```

**Comment by testenvmicro** [comment]
Hi @ChenxiJiang333 by using above code, I am forced to set a location property and if I do that, I get the following:

Code: InvalidResourceLocation
Message: The resource 'premiumsbgonzo' already exists in location 'centralus' in resource group 'RG01'. A resource with the same name cannot be created in location 'eastus'. Please select a new resource name.


If I remove the location I get the following instead:

azure.core.exceptions.HttpResponseError: (LocationRequired) The location property is required for this definition.
Code: LocationRequired
Message: The location property is required for this definition.

**Comment by ChenxiJiang333** [comment]
> Hi @ChenxiJiang333 by using above code, I am forced to set a location property and if I do that, I get the following:
> 
> Code: InvalidResourceLocation Message: The resource 'namespacename' already exists in location 'centralus' in resource group 'resourcegroupname'. A resource with the same name cannot be created in location 'eastus'. Please select a new resource name.
> 
> If I remove the location I get the following instead:
> 
> azure.core.exceptions.HttpResponseError: (LocationRequired) The location property is required for this definition. Code: LocationRequired Message: The location property is required for this definition.

Sorry I didn't mention it clearly, since your resource is in location 'centralus', you need to update the value of location to 'centralus' in the code as well.

**Comment by rajesh-Microsoft** [comment]
Hi @ChenxiJiang333 

I ran this code. i am able to update the tls version. but it requires to have location property to be set. why is location required? can't we update tls without passing location property.

**Comment by rajesh-Microsoft** [comment]
Hi @ChenxiJiang333 

I ran this code. i am able to update the tls version. but it requires to have location property to be set. why is it required? can't we update tls without passing location property.

**Comment by ChenxiJiang333** [comment]
> Hi @ChenxiJiang333
> 
> I ran this code. i am able to update the tls version. but it requires to have location property to be set. why is location required? can't we update tls without passing location property.

First please know that sdk is generated by the swagger definition.
I found you use `update` method at first and it don't need the `location` property, but it's required when you try to `create_or_update` a resource, and `minimumTlsVersion` only defined [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/servicebus/resource-manager/Microsoft.ServiceBus/preview/2022-10-01-preview/namespace-preview.json#L695) as parameter of `create_or_update` operation, yet for just `update`(definition can be found [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/servicebus/resource-manager/Microsoft.ServiceBus/preview/2022-10-01-preview/namespace-preview.json#L789)), there's not.

That's why for now you have to use `create_or_update` and pass location property with it.

To solve it, you can request to add `minimumTlsVersion` property for `update` operation by opening an issue in https://github.com/Azure/azure-rest-api-specs/issues and mark it with label `feature-request`. Once swagger updated, a new version of python sdk will be released.
