### ISSUE TITLE
Container name is not in the correct format.

### ISSUE THREAD

**Issue by emelyanovVlad** [Azure/azure-sdk-for-python#3159]
Hi all,
I faced the issue with next error message:

> Traceback (most recent call last):
  File "delete.py", line 299, in <module>
    run()
  File "delete.py", line 281, in run
    recovery_backup_client)
  File "delete.py", line 207, in delete_cmk_tenant_recovery_vault
    protected_item_name=protected_item.name
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/recoveryservicesbackup/operations/protected_items_operations.py", line 259, in delete
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: BMSUserErrorContainerNameIncorrectFormat
Message: Container name is not in the correct format.

I cannot understand what name it requires from me.
By this link https://docs.microsoft.com/en-us/python/api/azure-mgmt-recoveryservicesbackup/azure.mgmt.recoveryservicesbackup.operations.protecteditemsoperations?view=azure-python#delete I found documentation information and wrote script for backup protected item deletion.
```
protected_items = recovery_backup_client.backup_protected_items.list(recovery_vault_name, group_name)
for protected_item in protected_items:
        logging.info("Deleting protected item: {}".format(protected_item.properties.friendly_name))
        recovery_backup_client.protected_items.delete(
            vault_name=recovery_vault_name,
            resource_group_name=group_name,
            fabric_name="Azure",
            container_name=protected_item.properties.friendly_name(also tried protected_item.properties.container_name/protected_item.name),
            protected_item_name=protected_item.name
)
```

@DheerendraRathor , can you help me, please?

**Comment by emelyanovVlad** [comment]
Guys, please, give attention to this issue. I still can't resolve it.

**Comment by DheerendraRathor** [comment]
@emelyanovVlad Sorry for missing documentation there. container_name will be f"iaasvmcontainer;{protected_item.properties.container_name}".

**Comment by emelyanovVlad** [comment]
@DheerendraRathor it seems like it works. Thank you for your help 
Also, I see that `delete` is asynchronous operation. What is the best way to wait operation's end? After which I will delete recovery-vault

**Comment by annatisch** [comment]
Hi @emelyanovVlad, you can find the long running operation documentation here:
https://docs.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_operation.azureoperationpoller?view=azure-python

When waiting for an operation to complete you can call either:
- `poller.result(timeout=None)` if you are expecting an Azure resource to be returned from the operation.
- `poller.wait(timeout=None)` to wait until completion with no return value (e.g. for delete)

Where `poller` is the object returned by the operation, e.g.:
`poller = recovery_backup_client.protected_items.delete(...)`

Both are blocking calls with an optional timeout value.
Hope this helps!

**Comment by emelyanovVlad** [comment]
Basically, my main goal is to delete recovery vault with all the data inside. Maybe there is some way to delete it with few operations? 
Currently I'm trying to delete it with:
`recovery_client.vaults.delete(group_name, recovery_vault_name)`
but it throws and exception

> msrestazure.azure_exceptions.CloudError: Azure Error: ServiceResourceNotEmptyWithContainerDetails
Message:  Vault cannot be deleted as there are existing resources within the vault. Please ensure there are no backup items, protected servers or backup management servers associated with this vault. Unregister the following containers associated with this vault before proceeding for deletion : *recovery-vault-name* 
Unregister all containers from the vault and then retry to delete vault

**Comment by emelyanovVlad** [comment]
@annatisch I tried your approach but my `recovery_backup_client.protected_items.delete` operation returns `None`. If I'm adding `raw=True` to `delete` operation it returns `[ClientRawResponse](https://docs.microsoft.com/en-us/python/api/msrest/msrest.pipeline.clientrawresponse?view=azure-python)` where `output` is `None` and `response` is  `<Response [204]>`
There is no operation Id or smth else which I can use in for getting ResultStatus :/

**Comment by annatisch** [comment]
Thanks @emelyanovVlad - in that case the delete operation is not considered a long running operation.
This is potentially an error in the API specification if the operation does not in fact complete during the initial request.
Is this the operation you're calling?
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/operations/protected_items_operations.py#L194

@DheerendraRathor - could you comment on the service behavior here?

**Comment by emelyanovVlad** [comment]
@annatisch yes this one but I found it in MS documentation here https://docs.microsoft.com/en-us/python/api/azure-mgmt-recoveryservicesbackup/azure.mgmt.recoveryservicesbackup.operations.protecteditemsoperations?view=azure-python#delete

**Comment by DheerendraRathor** [comment]
Delete is long running operation. Currently we don't have support of long running operations in SDKs. It will be coming in upcoming releases. 
For now operation id can be fetched from header `Azure-AsyncOperation` and then `backup_operation_status.get` can be used to get status. 

Sample implementation: 
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-recoveryservicesbackup/tests/recoveryservicesbackup_testcase.py#L226
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-recoveryservicesbackup/tests/recoveryservicesbackup_testcase.py#L352

**Comment by emelyanovVlad** [comment]
@DheerendraRathor is there some easier way to delete recovery vault with backup items inside?

**Comment by emelyanovVlad** [comment]
@DheerendraRathor I will try provided examples in a few hours. My delete request still returns 204 error :/

**Comment by DheerendraRathor** [comment]
@emelyanovVlad All backed-up items must be manually deleted before vault deletion. That's by design and no shortcut is provided so that protected data is not lost when vault is deleted by mistake. 

Also can you provide value of header "x-ms-client-request-id" for deletion calls where you're getting 204. I will analyze it from service side. You can get header value either by dumping headers (using raw response) or by using some middle layer tool like fiddler.

**Comment by emelyanovVlad** [comment]
@DheerendraRathor and @annatisch thank you very much for your help. Today I found that I missed with container name. I was passing `f"iaasvmcontainer;{protected_item.properties.friendly_name}"` instead of `f"iaasvmcontainer;{protected_item.properties.container_name}"`

My issue is resolved. I really appreciate your help! <3
