### ISSUE TITLE
BlobClient append_block() overwrites existing blob

### ISSUE THREAD

**Issue by th0ger** [Azure/azure-sdk-for-python#31629]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.17.0
- **Operating System**: Ubuntu 23.04
- **Python Version**: 3.10

**Describe the bug**
The `BlobClient.create_append_blob()` method overwrites existing blobs without error, causing data to be lost.
Issue was found when working with Azurite storage emulator (not yet sure if it applies to real Azure Blob Storage).

**To Reproduce**
1. In VS Code *Azurite: Start Blob Service*
2. Something like:
```python
from azure.storage.blob import BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string(CONNECTION_STRING)
blob_client = blob_service_client.get_blob_client(container=CONTAINER_NAME, blob=BLOB_NAME)
blob_client.create_append_blob()
blob_client.append_block(data="123456789", length=9)
blob_client.blob_client.append_block(data="123456789", length=9) # Will not raise error, but delete the blob/content created above.
```

**Expected behavior**
`create_append_blob()` should raise `409: ResourceExistsError` if blob already exists.

This looks to have been the intention as seen in [error_map](https://github.com/Azure/azure-sdk-for-python/blob/2818d8e7f4aa7f6d1ee09791ff62134895167623/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_append_blob_operations.py#L505C15-L505C15).

**Additional context**
When debugging into the library, I found that the [http_response](https://github.com/Azure/azure-sdk-for-python/blob/2818d8e7f4aa7f6d1ee09791ff62134895167623/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_append_blob_operations.py#L596C29-L596C29) is `201 Created`, even on repeated runs.

**Comment by vincenttran-msft** [comment]
Hi @th0ger Martin, thanks for your inquiry. This is actually expected behavior and is a result of the REST API call that backs `create_append_blob`.

Here is a link to the relevant REST API documentation: [Put Blob](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=azure-ad), namely this section:
"When you update an existing block blob, you overwrite any existing metadata on the blob. Partial updates are not supported with Put Blob. **The content of the existing blob is overwritten with the content of the new blob.**"

With that being said, I can see how this can be a little confusing (and may lead to accidental overwrites), and I have made a note to bring this up in a wider team discussion to consider possibly reworking this behavior.

Thanks!

**Comment by th0ger** [comment]
Thanks @vincenttran-msft this makes sense. I agree this is a matter of documentation.

1) The REST API docs you quote specifically mentions only *block* blob overwrites.
The next section on page/append block does not clearly state the intended behaviour:
> A call to a Put Blob to create a page blob or an append blob only initializes the blob. To add content to a page blob, call the Put Page operation. To add content to an append blob, call the Append Block operation.

It not clear the *initializes* means overwrite if exists.

2) Can you add a docstring in the python SDK?
And maybe clarify why there is error handling implemented specifically for resource exists, that are never supposed to be reached.

My code now works fine with blobclient.exists() instead try/except construct.

**Comment by vincenttran-msft** [comment]
Hi @th0ger Martin, sorry for the delay. I am glad that you were able to find a work-around to unblock your workflow! I agree that the documentation can be a bit ambiguous in this regard. With that being said, I am working on the two following items to clear up this gap in documentation:

1. This [PR](https://github.com/Azure/azure-docs-rest-apis/pull/5580) resolves the ambiguity in the REST documentation by moving out the sentence about overwritten contents to be applicable to all `Put Blob` operations and leaves the next block to be more on the specifics of updating an existing block blob. I believe this was the original intention of the documentation to describe the behavior of this API.
2. This [PR](https://github.com/Azure/azure-sdk-for-python/pull/31765) adds more context in the docstring of the `create_append_blob` API, explicitly calling out the overwriting of existing contents and points the user to alternatives if this is not their intention.

With that being said, thanks again for your contribution and I will mark this issue resolved once these two items have been merged!

Thanks!

**Comment by th0ger** [comment]
Excellent @vincenttran-msft .
(The first PR link is 404.)

**Comment by vincenttran-msft** [comment]
Hi @th0ger Martin, just wanted to update that both changes have been merged and should be reflected shortly. Thanks again for your contribution!

**Comment by th0ger** [comment]
Thanks @vincenttran-msft 🎉
