### ISSUE TITLE
Azure functions blob copy operation using start_copy_from_url fails after function ends

### ISSUE THREAD

**Issue by XshalevX** [Azure/azure-sdk-for-python#31636]
- **BlobServiceClient and BlobClient**: 
- **Ubuntu**:
- **Python Version 3.10.12**: 

**Describe the bug**
I am using durable functions to run some service, in one of the `activity_triggers` i am trying to copy a blob, Now when i wait for the operation the end by checking the copy status it works and the operation works, but when i am trying to copy the blob without waiting as soon as the whole function ends the operation fails.
**To Reproduce**
1. Create a new durable function
2. Use start_copy_from_url in the function
3. return after the the copy

if you need more information let me know

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.
