### ISSUE TITLE
azure.search.documents.aio.SearchClient type annotation does not accept Chained Async Credential

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-sdk-for-python#31633]
- **Package Name**:  azure-search-documents
- **Package Version**: 11.4.0b6
- **Operating System**: macOS
- **Python Version**: 3.10

**Describe the bug**
The `__init__` method for the Async Search Client says it accepts a Union of `Union[AzureKeyCredential, AsyncTokenCredential]` which means that type checkers will raise a warning when  an async `ChainedTokenCredential` is used. Looking at the underlying code, only the `async .get_token()` method is assumed on the interface, so it is compatible with a chained async token credential (and this code works), but pylance raises an error.

**To Reproduce**
Minimum reproducible sample:

```python
from azure.identity.aio import DefaultAzureCredential
from azure.search.documents.aio import SearchClient

AZURE_SEARCH_SERVICE = "foobar"
AZURE_SEARCH_INDEX = "index1"

azure_credential = DefaultAzureCredential(exclude_shared_token_cache_credential = True)

search_client = SearchClient(
    endpoint=f"https://{AZURE_SEARCH_SERVICE}.search.windows.net",
    index_name=AZURE_SEARCH_INDEX,
    credential=azure_credential)
```

Here is the full error from Pyright

```default
Argument of type "DefaultAzureCredential" cannot be assigned to parameter "credential" of type "AzureKeyCredential | AsyncTokenCredential" in function "__init__"
  Type "DefaultAzureCredential" cannot be assigned to type "AzureKeyCredential | AsyncTokenCredential"
    "DefaultAzureCredential" is incompatible with "AzureKeyCredential"
    "DefaultAzureCredential" is incompatible with protocol "AsyncTokenCredential"
      "__aenter__" is an incompatible type
        Type "() -> Coroutine[Any, Any, DefaultAzureCredential]" cannot be assigned to type "() -> Coroutine[Any, Any, None]"
          Function return type "Coroutine[Any, Any, DefaultAzureCredential]" is incompatible with type "Coroutine[Any, Any, None]"
      "__aexit__" is an incompatible type
        Type "(*args: Unknown) -> Coroutine[Any, Any, None]" cannot be assigned to type "(exc_type: Unknown, exc_value: Unknown, traceback: Unknown) -> Coroutine[Any, Any, None]"
  ...
```

**Comment by tonybaloney** [comment]
CC @xiangyan99

**Comment by kashifkhan** [comment]
Thank you for the feedback @tonybaloney . We will investigate and get back to you asap.

**Comment by pvaneck** [comment]
Hey, @tonybaloney. We have recently been implementing typing updates in many of the SDKs, but there are likely still some issues to work out. Hower in this case, it looks similar to https://github.com/Azure/azure-sdk-for-python/issues/27704, which was actually _just_ recently resolved. 

What version of `azure-core` do you have installed? If you grab the latest, I believe pywright shouldn't complain here.

**Comment by pvaneck** [comment]
Spoke a bit too soon, and seems like there were some issues in the azure-core AsyncTokenCredential protocol.

Will close this and track in #27704.
