### ISSUE TITLE
Type annotation for AzureError.message is confusing at best, but more likely just plain wrong

### ISSUE THREAD

**Issue by TorgeirBrenn** [Azure/azure-sdk-for-python#31656]
- **Package Name**: `azure.core`
- **Package Version**: `1.29.1`
- **Operating System**: NA
- **Python Version**: NA

**Describe the bug**
The previously untyped declaration `self.message: Optional[str] = str(message)`
can be found in https://github.com/Azure/azure-sdk-for-python/blob/d0e378e4bbcede2aab113b71bb5340eebd776d4f/sdk/core/azure-core/azure/core/exceptions.py#L300, with the type annotation introduced in https://github.com/Azure/azure-sdk-for-python/commit/d0e378e4bbcede2aab113b71bb5340eebd776d4f.

The consequence it that code which has assumed that `.message` always is a `str` based on the previous implementation, like ours, now fails `mypy` checks. The checks themselves are just a matter of convenience, but more importantly demonstrate broken expectations since future incidents of `.message=None` will break code like ours. 

The type annotation seems to be either 
a. Wrong: `str()` always returns a `str` type object. Even though `message: Optional[object]`, `message=None` will result in `self.message="None"`. 
b. Confusing: If `AzureError.message` is ment to be later mutated to `None`, or that subclasses could choose to instantiate it as such, this goes against the class docstring and IMO should be avoided but at the very least explained with an inline comment.

Based on the class docstring stating `:ivar str message: A stringified version of the message parameter` I feel it is natural to assume this as an error and therefore report it as a bug.

**To Reproduce**
A slightly simplified but nonetheless valid and standalone example:
```python
from azure.core.exceptions import AzureError


def is_secret_not_found_error(e: AzureError) -> bool:
    return "SecretNotFound" in e.message
```
Here `mypy` will raise `error: Unsupported right operand type for in ("str | None")`.

**Expected behavior**
Either a corrected type `self.message: str = str(message)` OR an update to the `AzureError` docstring clarifying that it may indeed be excepted that `AzureError.message = None` in some scenarios.

**Screenshots**
NA

**Additional context**
I would be happy to provide a small PR which fixes this, based on feedback w.r.t. whether `None` is a possible value for the attribute.

**Comment by lmazuel** [comment]
Hi @TorgeirBrenn 

You're right, it shouldn't be optional. I made it optional following another exception implementation, and mis-judged it, my bad! I have an open PR and we'll release the fix asap.

Thanks for opening the issue!

**Comment by TorgeirBrenn** [comment]
> Hi @TorgeirBrenn
> 
> You're right, it shouldn't be optional. I made it optional following another exception implementation, and mis-judged it, my bad! I have an open PR and we'll release the fix asap.
> 
> Thanks for opening the issue!

Thank you for the quick response, @lmazuel !
