### ISSUE TITLE
How do I update columns from a given entity on Purview?

### ISSUE THREAD

**Issue by guimatheus92** [Azure/azure-sdk-for-python#31699]
**What is your desired outcome**
I was successful by updating description for a given entity on Purview (in my case is a Kusto table). I am also trying to update each column description also, that way I could have all information in place for our users.

**What have you tried so far**
The way I did was:

1. Used the `get_by_guid()` function to retrieve all information I have and understand the response. So I saw that every column description is under the `referredEntities` dict.
2. Same query I used to update the entity description, I tried with `create_or_update()` function but despite the message is not retrieving any error, the descriptions is not being updated also.
3. My query:

``` python
# Define the keywords and updated description
updated_description = "New description for the asset"

# Create the entity input with the updated description
entity_input = {
  "referredEntities": {
        "typeName": "azure_data_explorer_column",
        "attributes": {                
                "qualifiedName": "https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest#ID_VM",
                "name": "ID_VM",
                "description": updated_description,
                "userDescription": "<div>VM Id</div>",
            },
      },
  "entity": {
    "typeName": "azure_data_explorer_table",
    "attributes": {
      'qualifiedName': 'https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest',
      'name': 'DimensionDevicesTest', 
    }
  }  
}

try:
    # Call create_or_update to update the asset
    response = client_catalog.entity.create_or_update(entity=entity_input)
    print("Asset updated successfully:", response)
except HttpResponseError as e:
    print("Error updating asset:", e)
```
This the output of query above:

`Asset updated successfully: {'guidAssignments': {'-271567942211068': 'f31eeb6a-d9b0-48d3-a461-f9f6f6f60000'}}`

**Desktop:**
 - OS: Windows 11 Enterprise, version 22H2, build 22621.2134

**Additional context**
The query that is working and that I am using to update my entity description is this one:

``` python
# Define the keywords and updated description
updated_description = "New description for the asset"

# Create the entity input with the updated description
entity_input = {
  "referredEntities": {},
  "entity": {
    "typeName": "azure_data_explorer_table",
    "attributes": {
      'qualifiedName': 'https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest',
      'name': 'DimensionDevicesTest', 
      "userDescription": updated_description,
    }
  }
}

try:
    # Call create_or_update to update the asset
    response = client_catalog.entity.create_or_update(entity=entity_input)
    print("Asset updated successfully:", response)
except HttpResponseError as e:
    print("Error updating asset:", e)
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by guimatheus92** [comment]
@xiangyan99 I don't know if that is the best solution, but I was able to solve, different properties was missing. This is my solution:

``` python
# Define the keywords and updated description
updated_description = "New description for the asset"

entity_input = {
  "referredEntities": {},
  "entity": {
    "typeName": "azure_data_explorer_column",
    "attributes": {
        'data_type': 'Guid',
        'qualifiedName': 'https://cluster.eastus.kusto.windows.net/database/DimensionDevicesTest#ColumnId',
        'name': 'ColumnId', 
        "userDescription": updated_description,
    }
  }
}

```
try:
    # Call create_or_update to update the asset
    response = client_catalog.entity.create_or_update(entity=entity_input)
    print("Asset updated successfully:", response)
except HttpResponseError as e:
    print("Error updating asset:", e)
