### ISSUE TITLE
Add Microsoft.Communication.* enums

### ISSUE THREAD

**Issue by Frankkkkk** [Azure/azure-sdk-for-python#31696]
**Describe the solution you'd like**
Call Automation receives call events, like:
- `Microsoft.Communication.CallConnected`
- `Microsoft.Communication.PlayCompleted`
- etc.

These enums are not written on this repo.

It'd be great if you could add them too

Cheers

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share the information which language did you use? (I asked because the name looks like .net. :))

**Comment by Frankkkkk** [comment]
Hi, my issue is for the python sdk, but it is the same for the other languages as the enum is not listed in https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/CallAutomation/preview/2023-06-15-preview/communicationservicescallautomation.json and thus not autogenerated into the sdks.

Thanks and cheers
