### ISSUE TITLE
Commerce: Rate Card "meter_sub_category" output format has changed!

### ISSUE THREAD

**Issue by ttruong-a10** [Azure/azure-sdk-for-python#3171]
Was wondering why my code for outputting VM price started failing. Found out the "meter_sub_category" for the Rate Card meter object has changed.  For instance D8v3 use to have output:

Standard_D8_v3 VM

Now it outputs 

Dv3/DSv3 Series

This is problematic because compute_client.virtual_machine_sizes.list() gives the first format (Standard_D8_v3)

What an easy way to match up VM Size with the Rate card pricing?

**Comment by annatisch** [comment]
@yugangw-msft have you encountered this?

**Comment by annatisch** [comment]
Wrong service - adding Commerce.
Sorry @yugangw-msft - as you were :)

**Comment by lmazuel** [comment]
Hi @ttruong7 
Could you confirm that you used the same package, and suddenly your code has stopped working? This would mean the RestAPI changed suddenly one day, and I would route this problem differently.
Thanks!

**Comment by gsimore** [comment]
I'm also getting this issue. This feature is very important to our customers for us to predict rates on VMs. In the past month or so the rate card meters started returning different sub categories that broke our code. I need to be able to map VM sizes to meters, but I don't see a consistent pattern between the naming conventions. 
For example, 'Basic_A0' VM size is equivalent to the 'A Series Basic' sub_category in meters,
but 'Standard_A0' is just the 'A0' sub_category, but 'Standard_DS2_v3' is also very different. Is there an easy way to map the VM sizes to meters?

**Comment by lmazuel** [comment]
@yugangw-msft for ideas?

**Comment by ttruong7** [comment]
Adding to this. Why are region names in a different format than other Azure APIs?  For instance, the region name when querying rate card gives 'meter_region': 'EU West'.  For Compute API, region name is 'Europe West'. Similarly, 'Asia East' is 'AP East'.  This mismatch in standards is rather aggravating.

**Comment by gsimore** [comment]
I found this file: http://download.microsoft.com/download/4/6/4/464DEF8A-4D12-4956-9066-34750C84219F/AzureMeterMapping-en.xlsx available for mapping old naming conventions to new ones. Pretty hefty file to read from though, but glad it exists.

**Comment by gsimore** [comment]
The region names are also pretty aggravating to me.

**Comment by ttruong7** [comment]
@gsimore  Thanks for this!

**Comment by gsimore** [comment]
np :)

**Comment by xiangyan99** [comment]
@ttruong-a10 Given latest azure-mgmt-commerce is 6.0.0, could you help to check if this issue is stall valid?

Thank you.
