### ISSUE TITLE
ServiceBusReceiver.peek_messages when receive_mode=ServiceBusReceiveMode.RECEIVE_AND_DELETE, consumes 1 message.

### ISSUE THREAD

**Issue by lubomirmatus** [Azure/azure-sdk-for-python#31712]
- **Package Name**: azure-servicebus
- **Package Version**: 7.11.1 (in 7.8.2 was OK)
- **Operating System**: Windows 10 x64
- **Python Version**:  3.11.1

**Describe the bug**
ServiceBusReceiver with `receive_mode=ServiceBusReceiveMode.RECEIVE_AND_DELETE` method `peek_messages` consumes 1 message from topic/subscription. When `receive_mode=ServiceBusReceiveMode.PEEK_LOCK` then method `peek_messages` is working OK.
This behavior was spotted in `azure-servicebus` `7.1.11`, for example older version `7.8.2` was OK.

**To Reproduce**
`client = ServiceBusClient.from_connection_string(conn_str='my_connection', logging_enable=False)`
`receiver = client.get_subscription_receiver(topic_name='my_topic', subscription_name='my_subscription', receive_mode=ServiceBusReceiveMode.RECEIVE_AND_DELETE, keep_alive=0, prefetch_count=0)`
`messages = receiver.peek_messages(max_message_count=1000, timeout=10)`  # Peeks messages and consumes 1st message from topic.

**Expected behavior**
The method `peek_messages` should not modify topic and consume/delete messages.

**Comment by kashifkhan** [comment]
@lubomirmatus Im trying to reproduce this and I wanted to clarify a few things. Assuming my topic/subscription has 100 messages I should see the following behavior

* if I set `receive_mode=ServiceBusReceiveMode.RECEIVE_AND_DELETE` then only 1 message will come back
* If I set `receive_mode=ServiceBusReceiveMode.PEEK_LOCK` then up to 100 messages might come back ?

**Comment by kashifkhan** [comment]
Thank you @lubomirmatus . I'm able to reproduce this on my end and will update this thread once we have a fix in place.

**Comment by kashifkhan** [comment]
@lubomirmatus just out of curiosity, we were wondering why set `RECEIVE_AND_DELETE` and then peek messages?  `PEEK_LOCK` and complete messages ( with auto lock renewer) can work similarly

**Comment by lubomirmatus** [comment]
I have been performing debugging/tests of our system. In some points of code I wanted to see messages in the topic before they have been received and processed so I used peek to see them but not touch them. The recevier was created with `RECEIVE_AND_DELETE` mode, I expected that `peek_messages` does not consume messages, and then I found this strange behaviour.

**Comment by kashifkhan** [comment]
Thank you for the update @lubomirmatus . We are able to reproduce this and will update when the fix will go in

**Comment by swathipil** [comment]
Hi @lubomirmatus - We've found the bug and are currently working on the right fix. We'll keep you updated as continue to work on it. Thanks!

More info: Our default prefetch behavior should be "off". However, even when it's off, we're currently prefetching a message.

**Comment by swathipil** [comment]
Hi @lubomirmatus - We've merged the fix into the main branch of the repo. We will be releasing the fix this week. If you'd like to test out the change beforehand, you can build the wheel off of the main branch. Thanks!

**Comment by swathipil** [comment]
Hi @lubomirmatus - The fix has been released - https://pypi.org/project/azure-servicebus/7.11.3/

Thanks!

**Comment by lubomirmatus** [comment]
Ok, thank you.
