### ISSUE TITLE
ADF Dataset Operations, how can we commit to develop/any branch using the Python library?

### ISSUE THREAD

**Issue by saulcruz** [Azure/azure-sdk-for-python#3172]
As of now If I do  `datasets.create_or_update(...)` the API **publishes** a dataset to the Data Factory itself, is there any way we can use the Python library to commit to a specific branch (GitHub) instead?

Azure data factory has GitHub integration and using the UI, you can  either commit to your collaboration branch or to  the Data Factory itself (publish or deployment) , if i run my python scripts, it will make all of these changes directly to the data factory itself, making it hard to source control every change.

![image](https://user-images.githubusercontent.com/28897049/44362710-cd831a80-a48f-11e8-80dd-b97e3906cc4c.png)

**Comment by annatisch** [comment]
Hi @hvermis - are you able to provide any insights here? :)

**Comment by hvermis** [comment]
Our UI has a lot of custom code to support git interaction, you would have to mimic all that in order to use git from Python. technically you can serialize the objects into json files and store then into git, but you would have to implement branching, merging, creating folders, etc.

**Comment by saulcruz** [comment]
got it, thanks
