### ISSUE TITLE
Azure Search Expand WaterMark Support

### ISSUE THREAD

**Issue by fruitymedley** [Azure/azure-sdk-for-python#31736]
**Is your feature request related to a problem? Please describe.**
I am trying to build an indexer in Azure Search which utilizes the parameters configuration settings `convertHighWaterMarkToRowVersion` and `disableOrderByHighWaterMarkColumn`. The current `IndexingParametersConfiguration` class excludes these two settings, and passing a dictionary containing these settings directly ignores them when making a request to the API.

The functionality of these parameters is described [in the Azure Search documentation](https://learn.microsoft.com/en-us/azure/search/search-howto-connecting-azure-sql-database-to-azure-search-using-indexers#configure-and-run-the-azure-sql-indexer)

**Describe the solution you'd like**
Add these two fields to the class IndexingParametersConfiguration in file azure\search\documents\indexes\_generated\models\_models_py3.py among other relevant declarations.

**Describe alternatives you've considered**
I intended to put in a pull request myself, however, the files in question are code-generated, so any changes I make would be overwritten. The documentation only points to the [Rest API Specs](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/search) but does not seem to include information related to the data model.

**Additional context**
N/A

**Comment by kristapratico** [comment]
@fruitymedley thanks for your feature request. @xiangyan99 - can you take a look?

**Comment by xiangyan99** [comment]
Thank you for reaching out.

As you figured out, those code is auto generated based on https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/preview/2023-07-01-Preview/searchservice.json

Please open an issue in https://github.com/Azure/azure-rest-api-specs repo.
