### ISSUE TITLE
[AKS] Update to inline type hint

### ISSUE THREAD

**Issue by jeesang7** [Azure/azure-sdk-for-python#31731]
**Is your feature request related to a problem? Please describe.**
I found a code that uses type comments in AKS.
However, since Python version 3.5, the use of type annotations has been deprecated.

**Describe the solution you'd like**
Use type annotation using [typing](https://docs.python.org/3/library/typing.html) and refer to [the guidance](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/static_type_checking_cheat_sheet.md#general-guidance)

**Additional context**
https://github.com/Azure/azure-sdk-for-python/blob/63476fb0c624515386944f1c164e033b57899137/sdk/aks/azure-mgmt-devspaces/azure/mgmt/devspaces/_configuration.py#L62

https://github.com/Azure/azure-sdk-for-python/blob/63476fb0c624515386944f1c164e033b57899137/sdk/aks/azure-mgmt-devspaces/azure/mgmt/devspaces/_dev_spaces_management_client.py#L93

**Comment by kristapratico** [comment]
Hi @jeesang7 thanks for your feedback. Since this is a generated library, we'll need to regenerate with the latest version of the generator to update the deprecated type comments. cc/ @msyyc

**Comment by ChenxiJiang333** [comment]
Fix version https://pypi.org/project/azure-mgmt-devspaces/1.0.0b3/ is released

**Comment by jeesang7** [comment]
I see, It seems to be updated well.

**Comment by ChenxiJiang333** [comment]
We use [autorest](https://github.com/Azure/autorest/tree/main/docs) to generate sdk from swagger definition.

**Comment by jeesang7** [comment]
Oh, let's take a look. thank you.
