### ISSUE TITLE
[Storage-Blob] Type hinting update required

### ISSUE THREAD

**Issue by FacerAin** [Azure/azure-sdk-for-python#31733]
**Is your feature request related to a problem? Please describe.**

The code below uses **deprecated type hinting** (eg. #type: ) in storage-blob module. So, I think an update is needed.
https://github.com/Azure/azure-sdk-for-python/blob/63476fb0c624515386944f1c164e033b57899137/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py#L195
https://github.com/Azure/azure-sdk-for-python/blob/63476fb0c624515386944f1c164e033b57899137/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L267
https://github.com/Azure/azure-sdk-for-python/blob/63476fb0c624515386944f1c164e033b57899137/sdk/storage/azure-storage-blob/azure/storage/blob/_deserialize.py#L102

**Describe the solution you'd like**
I think it needs to be modified according to the [guideline](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/static_type_checking_cheat_sheet.md).

**Comment by kristapratico** [comment]
@FacerAin thanks for the feedback! I believe this is a work-in-progress, but I'll let @vincenttran-msft @jalauzon-msft share the update. :)

**Comment by jalauzon-msft** [comment]
Hi @FacerAin, as Krista mentioned, we are actually actively working on updating type hints for all of our Storage packages, starting with Queue. This is a long, slow process for us, but the Queue work is mostly done, and Blob will likely be next. WE have already started blob a while back in this branch.
https://github.com/Azure/azure-sdk-for-python/tree/feature/storage-blob-typing/sdk/storage

**Comment by jalauzon-msft** [comment]
We are tracking this work as part of #28615, closing this one as duplicate. Thanks
