### ISSUE TITLE
Wrong typehints for generate_directory_sas function

### ISSUE THREAD

**Issue by KazzyJr** [Azure/azure-sdk-for-python#31751]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.13.0b1
- **Operating System**: Windows 10
- **Python Version**:  3.8.17

**Describe the bug**
Wrong typehints for the generate_directory_sas function. *permissions* attribute should be of type DirectorySasPermissions.
This leads to scope mismatching of the generating functions and their respective permission models.

**To Reproduce**
```
from azure.storage import filedatalake

directory_permissions = filedatalake.DirectorySasPermissions(read=True, add=True)
filedatalake.generate_directory_sas(permission=directory_permissions, ...)
```
This code is the intended use of said function. Static typechecking results in errors when trying to use DirectorySasPermissions since the type is incorrectly specified as FileSasPermissions

**Expected behavior**
DirectorySasPermission displayed as typehint for permission attribute since that is the class that generates the correct behavior, not FileSasPermissions.

**Screenshots**

**Additional context**
Might want to check other libraries that use sas generator functions for scope mismatching.

**Comment by vincenttran-msft** [comment]
Hi @KazzyJr Sergiu, thanks for your inquiry! We are actually currently working on a huge package-wide typing overhaul in the background, but I have just put out a PR to address this typo as per your inquiry. With that being said, thanks again for your contribution, and I will mark this issue as resolved upon the successful merge of the open pull requests. Thanks!
