### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by Padmapriya-09** [Azure/azure-sdk-for-python#31750]
- **Package Name**: azure.mgmt.network.NetworkManagementClient.network_interfaces
- **Package Version**: 
- **Operating System**: linux
- **Python Version**: 

**Describe the bug**
One of our client is using the given package and have faced issues while creating and deleting ENIC's using the package. They have received 503 Service Unavailable from the APIs.
Wanted to confirm if there any outage during this time period 2023-08-15 

**To Reproduce**
1. Transient, did not see this issue later.

Error Message:
File '/home/site/wwwroot/qaas/azure/deployment/management.py', line 198, in delete_injection_enics
    delete_nics_fn(customer_liftr_client, nics, mpp_resource_id).wait()
  File '/home/site/wwwroot/.python_packages/lib/site-packages/qaas_utils/cloud/azure/deploy/network.py', line 261, in wait
    p.wait()
  File '/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator.py', line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File '/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/polling/_poller.py', line 261, in wait
    raise self._exception  # type: ignore
  File '/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/polling/_poller.py', line 176, in _start
    self._polling_method.run()
  File '/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/polling/base_polling.py', line 734, in run
    raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err
azure.core.exceptions.HttpResponseError: Operation returned an invalid status Service Temporarily Unavailable
Content: <html>
<head><title>503 Service Temporarily Unavailable</title></head>

**Comment by kristapratico** [comment]
@Padmapriya-09 thanks for your issue, we'll investigate as soon as possible.

**Comment by ChenxiJiang333** [comment]
Hi, @Padmapriya-09. Since it's a service problem, please open an issue in https://github.com/Azure/azure-rest-api-specs/tree/main. Thanks.
