### ISSUE TITLE
Release: Ensure 'azure-sdk' keyword on PyPI package

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#31773]
On release we should ensure that packages in PyPI have the ~`azure-sdk`~ `azure sdk` keyword so downstream automation can find those packages. 

This was observed in the most recent release of the [`azure-communication-callautomation`](https://pypi.org/project/azure-communication-callautomation/#history) package which was not added into the metadata CSV file or release DevOps project.

**Comment by scbedd** [comment]
> On release we should ensure that packages in PyPI have the `azure-sdk` keyword so downstream automation can find those packages.
> 
> This was observed in the most recent release of the [`azure-communication-callautomation`](https://pypi.org/project/azure-communication-callautomation/#history) package which was not added into the metadata CSV file or release DevOps project.

Do you mean `keyword` or `classifiers?`

**Comment by danieljurek** [comment]
The word "Classifier" is incorrect. @scbedd you got it right. The property is "Keyword", not "Classifier".

**Comment by danieljurek** [comment]
Also, the value checked for should be `azure sdk` not `azure-sdk` as the update script is querying for `azure sdk` ... https://github.com/Azure/azure-sdk/blob/main/eng/scripts/Query-Azure-Packages.ps1#L164-L165

**Comment by scbedd** [comment]
I have added a branch with all `setup.py` fixed [here.](https://github.com/Azure/azure-sdk-for-python/commit/538fde1e429a80937ceecb5a273d2ce35ceba3cc) Need to do a quick visual inspection then pass it to an admin for merge.
