### ISSUE TITLE
Identity e2e tests on Service Fabric fail

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#31789]
https://github.com/Azure/azure-sdk/issues/901#issuecomment-1689461651
![image](https://github.com/Azure/azure-sdk-for-python/assets/1302850/d9bf0561-6773-4165-8d2e-a66c8882e1d2)

**Comment by xiangyan99** [comment]
It is not worth the ROI, so closing this out.

Also see [MQ: Automate Azure Identity SDK Manual/Vendor Tests · Issue #37471 · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/issues/37471)
