### ISSUE TITLE
Pylint doesn't allow import of another Azure SDK Package

### ISSUE THREAD

**Issue by jeremydvoss** [Azure/azure-sdk-for-python#31805]
- **Package Name**:  azure-monitor-opentelemetry
- **Package Version**:  1.0.0b16
- **Operating System**: Windows and CI pipeline
- **Python Version**: 3.x

**Describe the bug**
[Pylint complains](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3032430&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=5da75d26-b661-5189-46a3-f9dd247b5d85&l=296) about the distro importing the exporter which has a similar module location. The imports are as follows:
```python
from logging import getLogger
...

from opentelemetry._logs import get_logger_provider, set_logger_provider
...

from azure.core.settings import settings
...
from azure.monitor.opentelemetry._types import ConfigurationValue
from azure.monitor.opentelemetry.exporter import (  # pylint: disable=import-error
    ApplicationInsightsSampler,
    AzureMonitorLogExporter,
    AzureMonitorMetricExporter,
    AzureMonitorTraceExporter,
)
...
```

**To Reproduce**
1. Run pylint on package. Run the following command from the azure-monitor-opentelemetry directory.
`tox -v -c ../../../eng/tox/tox.ini --root .`

**Expected behavior**
Pylint says the import of the exporters are invalid:
`azure/monitor/opentelemetry/_configure.py:37: [E0611(no-name-in-module), ] No name 'exporter' in module 'azure.monitor.opentelemetry'`

**Screenshots**

**Additional context**
At first I thought that perhaps other Azure-SDK need to be imported in the "3rd party" section like the opentelemetry.x imports. But it seems pylint accepts the azure core imports. So, I don't understand what's different about the exporter imports.

**Comment by jeremydvoss** [comment]
My guess is this has something to do with the fact that the exporter's module namespace, "azure.monitor.opentelemetry.exporter", is _within_ the namespace of the distro, "azure.monitor.opentelemetry" while azure core's namespace is further up.

**Comment by jeremydvoss** [comment]
Here is the [draft PR](https://github.com/Azure/azure-sdk-for-python/pull/31796/files) where I am trying to enable Pylint

**Comment by l0lawrence** [comment]
Hi @jeremydvoss, I will take a look and get back to you asap. Thanks!

**Comment by l0lawrence** [comment]
It seems, like you said, that pylint does not recognize `azure.monitor.opentelemerty.exporter` as a 3rd party package. It looks like this may also be related to the `pylint:disable = import-error`that  is there already. I would, for now, add `no-name-in-module` to the disable statement as it is a false positive. I can make an issue in the pylint repo as this is one of their checkers.

**Comment by jeremydvoss** [comment]
Using `# pylint: disable=import-error,no-name-in-module` does seem to solve the problem locally. Waiting to the pipeline to run in the PR. Thanks! This does seem to be a pylint bug. So, an issue would be good, whether the outcome is a fix or an instruction to move the import somewhere else.
