### ISSUE TITLE
Ref docs issue

### ISSUE THREAD

**Issue by NanaXiong00** [Azure/azure-sdk-for-python#31807]
Error:

> <CI INFO>: Unpacking sdist file D:\a\_work\1\s\dist_temp\10\azure-ai-translation-text-1.0.0b1.zip to destination source_code\10.
> <CI INFO>: Uncompressing the zip file D:\a\_work\1\s\dist_temp\10\azure-ai-translation-text-1.0.0b1.zip.
> <CI INFO>: Getting name information of package in D:\a\_work\1\s\dist_temp\10\azure-ai-translation-text-1.0.0b1.
> <Warn Filter> Running commandline: & 'python' setup.py --quiet --dry-run --name 2>&1
> azure-ai-translation-text
> <CI INFO>: Getting version information of package in D:\a\_work\1\s\dist_temp\10\azure-ai-translation-text-1.0.0b1.
> <Warn Filter> Running commandline: & 'python' setup.py --quiet --dry-run --version 2>&1
> 1.0.0b1
> <CI INFO>: Getting author information of package in D:\a\_work\1\s\dist_temp\10\azure-ai-translation-text-1.0.0b1.
> <Warn Filter> Running commandline: & 'python' setup.py --quiet --dry-run --author 2>&1
> Microsoft Corporation
> <CI INFO>: Unpacked D:\a\_work\1\s\dist_temp\10\azure-ai-translation-text-1.0.0b1.zip into source_code\10...
> <CI INFO>: Fetching source code from PyPI...
> <CI INFO>: Downloading azure-ai-vision==0.13.0b1 from PyPI...
> Looking in indexes: https://build:***@apidrop.pkgs.visualstudio.com/Content%20CI/_packaging/Content_CI_PublicPackages/pypi/simple
> ##[error]ERROR: Could not find a version that satisfies the requirement azure-ai-vision==0.13.0b1 (from versions: none)
> ERROR: No matching distribution found for azure-ai-vision==0.13.0b1
> <CI ERROR>: Downloading failed.

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=382187&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
This issue has been resolved. Turns out the problem isn't the cache, it's that the package is published in a way that fails when specifying the default `prefer_source_distribution` of `true` in our EngSys. This has been corrected in the metadata JSON file for that package.
