### ISSUE TITLE
CMK parameter for Postgresql_FlexibleServer

### ISSUE THREAD

**Issue by Mina69** [Azure/azure-sdk-for-python#31808]
I am gonna use CMK(dataEncryption) for postgresql_flexibleservers when I create the server using python SDK. However I do not see any parameter for it under Azure [doc](https://learn.microsoft.com/en-us/python/api/azure-mgmt-rdbms/azure.mgmt.rdbms.postgresql_flexibleservers.models.server?view=azure-python) in Server Class or other classes for [azure.mgmt.rdbms.postgresql_flexibleservers](https://learn.microsoft.com/en-us/python/api/azure-mgmt-rdbms/azure.mgmt.rdbms.postgresql_flexibleservers.models?view=azure-python). 

This parameter needs to be supported by the SDK.

**Here is what I expect it to be:**
```
from azure.mgmt.rdbms.postgresql_flexibleservers.models import Server, Network, Sku, Storage, Database, DataEncryption


def create_database_server(flexible_client, resource_group_name, subnet_id, dns_zone_id, server_name,
                           admin_user, admin_password, tags):
    network = Network(
        delegated_subnet_resource_id=subnet_id,
        private_dns_zone_arm_resource_id=dns_zone_id,
    )
    sku = Sku(
        name="Standard_B2s",
        tier="Burstable",
    )
    storage = Storage(
        storage_size_gb=32,
    )
    data_encryption = DataEncryption(
         primaryKeyURI : "your_key_vault_uri",
         primaryUserAssignedIdentityId : "your_key_identifier",
          type: "AzureKeyVault",
    )
    parameters = Server(
        location="norwayeast",
        tags=tags,
        administrator_login=admin_user,
        administrator_login_password=admin_password,
        sku=sku,
        version="13",
        network=network,
        storage=storage,
        data_encryption = data_encryption
        )
  )
```

**Alternative solution**
Alternative would be not to use SKD and go for the [API](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-create-server-customer-managed-key-azure-api) instead.

**Comment by kristapratico** [comment]
@Mina69 thanks for your issue, we'll investigate and get back to you as soon as possible.

**Comment by ChenxiJiang333** [comment]
The feature you request is supported in beta version, please use it instead.
[azure-mgmt-rdbms-10.2.0b8](https://pypi.org/project/azure-mgmt-rdbms/10.2.0b8/)
