### ISSUE TITLE
azure-cosmos CosmosClient.query_databases "parameters" argument incorrect typing

### ISSUE THREAD

**Issue by Lee-W** [Azure/azure-sdk-for-python#31811]
- **Package Name**:  azure-cosmos
- **Package Version**:  9.2.0
- **Operating System**: mac OS
- **Python Version**: 3.10.6

**Describe the bug**
Type inconsistency between https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-cosmosdb_9.2.0/sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py#L389 and https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-cosmosdb_9.2.0/sdk/cosmos/azure-cosmos/samples/database_management.py#L41-L46.

**To Reproduce**. 

**Expected behavior**
The type of https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-cosmosdb_9.2.0/sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py#L389 should be `list[dict[str, Any]]` instead

**Screenshots**

**Additional context**

**Comment by kristapratico** [comment]
Hi @Lee-W thanks for your feedback, we'll take a look and get back to you soon.

**Comment by simorenoh** [comment]
@Lee-W Thank you for pointing this out, you are correct. We have pushed the changes for this now in the PR referenced. Thanks!
