### ISSUE TITLE
BatchEndpoint and batch_deployments python API is not working

### ISSUE THREAD

**Issue by Jing-MSFT-2020** [Azure/azure-sdk-for-python#31839]
Hi, 

I was using ```BatchEndpoint``` and ```ml_client.batch_deployments.begin_create_or_update``` to create batch inference pipeline and it works last week. 

 

But this week, I am creating the pipeline with the exact code but it no longer works. Is there any break changes in these API?

 

Here is the latest error code from the log: 

 

 

Azure Machine Learning Batch Inference Start

[2023-08-28 21:55:00.064476] No started flag set. Skip creating started flag.

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /azureml-envs/azureml_c2e3d2f674c8d9e57282f184f70243c9/lib/libtinfo.so.6: no version information available (required by /bin/bash)

Unknown asset type: None

Unknown asset type: None

Azure Machine Learning Batch Inference End

Cleaning up all outstanding Run operations, waiting 300.0 seconds

2 items cleaning up...

Cleanup took 0.1821897029876709 seconds

Traceback (most recent call last):

  File "driver/amlbi_main.py", line 275, in <module>

    main()

  File "driver/amlbi_main.py", line 226, in main

    sys.exit(exitcode_candidate)

SystemExit: 42

**Comment by hugoaponte** [comment]
I believe the issue reported at the top is different than the follow up comment.

@Jing-MSFT-2020: Could you confirm the version of the SDK v2 generating that error? Did you recently upgraded?

@doursand: This is SDK v1. Is there error consistently reproducible? Do you see the "www-authenticate header" in the logs?

**Comment by doursand** [comment]
the error is always there, it was working perfectly still last week I think, the code didn't change at all. Here is the longer version of the error : 

`2023-09-27 06:44:56,477|ERROR|27|23278173509440|
["module": "azure.core.exceptions", "name": "ClientAuthenticationError",
"message": "Operation returned an invalid status 'Server failed to authenticate the request. Please refer to the information in the www-authenticate header.'" \
           "\nErrorCode:NoAuthenticationInformation",
"compliant_message": "Operation returned an invalid status 'Server failed to authenticate the request. Please refer to the information in the www-authenticate header.'\nErrorCode:NoAuthenticationInformation",
"formatted_traceback": "  File \"/mnt/azureml/cr/j/7cebb06d4d9a4fb59fc4facc539906a9/exe/wd/driver/sys_main.py\", line 94, in main\n    " \
                       "job_starter.start()\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/job_starter.py\", line 301, in start" \
                       "    self.run_tasks()\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/job_starter.py\", line 286, in run_tasks" \
                       "    loop.run_until_complete(self.start_tasks())\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete" \
                       "    return future.result()\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/job_starter.py\", line 233, in start_tasks" \
                       "    if job_state.reached(JobStage.MASTER_STOPPED):\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/job_state.py\", line 126, in reached" \
                       "    self.stage_cache[stage] = JobStageCacheItem(stage, self.blob_exists(stage))\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/job_state.py\", line 109, in blob_exists" \
                       "    return blob.exists()\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/append_blob.py\", line 71, in exists" \
                       "    blob_prop = blob_client.get_blob_properties()\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer" \
                       "    return func(*args, **kwargs)\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py\", line 1299, in get_blob_properties" \
                       "    process_storage_error(error)\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 185, in process_storage_error" \
                       "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n  File \"<string>\", line 1, in <module>\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py\", line 1289, in get_blob_properties" \
                       "    blob_props = self._client.blob.get_properties(\n  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n    return func(*args, **kwargs)" \
                       "  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py\", line 1875, in get_properties\n    map_error(status_code=response.status_code, response=response, error_map=error_map)" \
                       "  File \"/tmp/1f0c8e00-4f70-4e98-a8a7-d724e5e2567f/prs_prod/lib/python3.8/site-packages/azure/core/exceptions.py\", line 164, in map_error\n    raise error", "cause": null]`

**Comment by santiagxf** [comment]
Hi @Jing-MSFT-2020. Thanks for reaching out about this issue. Can you please help us understand which is the API broken that you are referring to? You mentioned using `ml_client.batch_deployments.begin_create_or_update` which is used to create a deployment. However, the logs you shared look to be be of the execution of a batch job. So that's part of the invocation. 

@doursand. batch endpoints is a V2-only capability so it is not related with what you are showing. Please, kindly open a new issue so we can take a look and help you out!

**Comment by helenzusa1** [comment]
Hello, I got the same error, but in different scenario. I created an AzureML registry, and shared some models from workspace1 to registry, then pushed the pipeline/model from registry to workspace2. I got pipeline endpoint in workspace2. Then I ran the pipeline in workspace2, it's inferencing. Got error.

Execution failed. User process '/azureml-envs/azureml_fbb3bb7a11dccea6277bcbcea67feb96/bin/python' exited with status code 42. Please check log file 'user_logs/std_log_0.txt' for error details. Error: Traceback (most recent call last):
  File "driver/amlbi_main.py", line 275, in <module>
    main()
  File "driver/amlbi_main.py", line 226, in main
    sys.exit(exitcode_candidate)
SystemExit: 42

below is std_log_0.txt:
Azure Machine Learning Batch Inference Start
[2024-01-16 01:56:57.441773] No started flag set. Skip creating started flag.
Azure Machine Learning Batch Inference End
Cleaning up all outstanding Run operations, waiting 300.0 seconds
2 items cleaning up...
Cleanup took 0.19039106369018555 seconds
Traceback (most recent call last):
  File "driver/amlbi_main.py", line 275, in <module>
    main()
  File "driver/amlbi_main.py", line 226, in main
    sys.exit(exitcode_candidate)
SystemExit: 42

Please help.
Thanks,
Helen

**Comment by helenzusa1** [comment]
Then I tried to deploy the model as real-time endpoint from registry to workspace. I did inference in the workspace, everything is fine.

**Comment by santiagxf** [comment]
Hi @helenzusa1. The error you describe is not related with this issue as per your description. Please open a new issue and share your logs. We are happy to take a look. When doing so, please disambiguate if you are deploying models or pipelines. You've used the wording " pipeline/model" but that distinction is very important.
