### ISSUE TITLE
The type of order_by should be string

### ISSUE THREAD

**Issue by Vivihung** [Azure/azure-sdk-for-python#31837]
The type of **order_by** parameter of **search()** should be string instead of a list of string.
I got the following error if passing the order_by commands as a list

```python
results = client.search(
        search_text="*",
        search_fields=["content"],
        select=["id", "userId", "sessionId", "content", "timestamp"],
        order_by=["timestamp asc"],
    )
```

![image](https://github.com/Azure/azure-sdk-for-python/assets/4814277/12b0e50a-b60d-4195-90fd-5ce62086b320)

Update to the following code resolved the error

```python
results = client.search(
        search_text="*",
        search_fields=["content"],
        select=["id", "userId", "sessionId", "content", "timestamp"],
        order_by="timestamp asc",
    )
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0d307f6-e957-5635-6a9e-1e6a7bae8a5d
* Version Independent ID: 5e6245e9-82c2-7043-e7c4-b3fcefd1b46f
* Content: [azure.search.documents.SearchClient class](https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.searchclient?view=azure-python#azure-search-documents-searchclient-search)
* Content Source: [docs-ref-autogen/azure-search-documents/azure.search.documents.SearchClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-search-documents/azure.search.documents.SearchClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
#31856

**Comment by xiangyan99** [comment]
The fix is merged and will be available in next release.
