### ISSUE TITLE
Azure - DCR Associations not exposed in azure-mgmt-monitor module

### ISSUE THREAD

**Issue by raviguhcl** [Azure/azure-sdk-for-python#31847]
- **Package Name**: azure-mgmt-monitor
- **Package Version**: 6.0.1
- **Operating System**: Windows
- **Python Version**:  3.10.7

**Describe the bug**
Unable to get DCR Associations resource details using _dcr_client.data_collection_rule_associations.list_by_rule(<RG Name>, <DCR Name>)_

**To Reproduce**
1. Login to Azure Subscription using Python SDK
_dcr_client = MonitorManagementClient(credential,item.subscription_id, api_version="2022-06-01")_
2. Get DCR Associations
_dcr_client.data_collection_rule_associations.list_by_rule(<RG Name>, <DCR Name>)_
3. expose all details of that object
4. Association details are missing in Object.

**Expected behavior**
We should get details of all associations of said DCR.

**Screenshots**
Visual Studio screenshot attached where object doesn't expose association details.
![DCRAssociationMissing](https://github.com/Azure/azure-sdk-for-python/assets/99799971/2cf5a98d-e7b6-4482-aa15-1bcb4a1ee54f)

**Additional context**
FYR: Already open an issue initially but didn't get any response. 
https://github.com/Azure/azure-rest-api-specs/issues/25261

**Comment by raviguhcl** [comment]
apologies as i forgot to iterate the returned object.
closing this thread

**Comment by navba-MSFT** [comment]
@raviguhcl Thanks for getting back and sharing the update. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
