### ISSUE TITLE
Bug Report: API-Version Error in azure-mgmt-consumption when Retrieving Budgets

### ISSUE THREAD

**Issue by niklash-dev** [Azure/azure-sdk-for-python#31878]
- **Package Name**:  azure-mgmt-consumption
- **Package Version**: 10.0.0
- **Operating System**: MacOS
- **Python Version**: 3.11

**Describe the bug**
When attempting to use the ConsumptionManagementClient to retrieve budgets, an api-version error occurs. The issue persists even after explicitly setting the api-version.

**To Reproduce**
1. Import ConsumptionManagementClient from azure.mgmt.consumption.
2. Initialize the ConsumptionManagementClient with credentials and subscriptionId.
3. Attempt to retrieve budgets using consumption_client.budgets.get().

**Expected behavior**
The API should return the requested budgets without any errors.

**Screenshots**
N/A

**Additional context**
We suspect the issue is related to a hardcoded api-version in this file: [Budget Operations Py file on GitHub](https://github.com/Azure/azure-sdk-for-python/blob/d71a2cd3ac2397caf1e2f0fc8e79e4a5d0bb9048/sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_budgets_operations.py#L72C26-L72C26).

**Comment by kashifkhan** [comment]
Thank you for your feedback @niklash-dev . We will investigate and get back to you asap.

**Comment by niklash-dev** [comment]
Thank you @kashifkhan! 

**Here is an example:**

```python
from azure.mgmt.consumption import ConsumptionManagementClient
from azure.identity import DefaultAzureCredential

subscriptionId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
resourceGroupName = "xxxxxx-xxxxxx-xxxxxx"
budgetname = "xxxxxx-xxxxxx-xxxxxx"

credentials = DefaultAzureCredential()

consumption_client = ConsumptionManagementClient(credentials, subscriptionId)

# consumption_client._config.api_version = "2022-09-01"

result = consumption_client.budgets.get(
    scope=f'/subscriptions/{subscriptionId}/resourceGroup/{resourceGroupName}',
    budget_name=budgetname,
)
```
**Results in:**

```bash
azure.core.exceptions.HttpResponseError: (InvalidApiVersionParameter) The api-version '2021-10-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
```

Same thing even if you use `consumption_client._config.api_version = "2022-09-01"`.

**Comment by ChenxiJiang333** [comment]
Hi, @niklash-dev. 
Seems the error message returned was very irrelevant and has made a confusion. There's nothing about `api_version`.
What truly caused the failure is that the scope value you had passed was incorrect, it should be like `f'/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}'`.

Here's my code and it's output is: `api_version: 2022-09-01`.
```
from azure.mgmt.consumption import ConsumptionManagementClient
from azure.identity import DefaultAzureCredential

subscriptionId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
resourceGroupName = "xxxxxx-xxxxxx-xxxxxx"
budgetname = "xxxxxx-xxxxxx-xxxxxx"

credentials = DefaultAzureCredential()

consumption_client = ConsumptionManagementClient(credentials, subscriptionId, api_version="2022-09-01")

result = consumption_client.budgets.get(
    scope=f'/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}',
    budget_name=budgetname,
)

assert result
print("api_version:",consumption_client._config.api_version)
```

**Comment by niklash-dev** [comment]
Hello @ChenxiJiang333,

Thank you for taking the time resolving this confusion! 

The Error is indeed misleading. I have build this function to test the scope (Please note the last example):

```python
def validate_azure_scope(scope):
    # Regex for matching scope
    pattern = r"^\/subscriptions\/[a-zA-Z0-9\-]{36}(\/resourceGroups\/[a-zA-Z0-9_\-\.]{1,90})?$"
    
    return bool(re.fullmatch(pattern, scope))

# Example:
validate_azure_scope("/subscriptions/12345678-p183-04d9-5g16-83040191nd5l/resourceGroups/myGroup") # True
validate_azure_scope("/subscriptions/87654321-b393-50s3-9u16-93548361lf3l")  # True
validate_azure_scope("/subscriptions/43216578-a254-95f5-7g/resourceGroups/myGroup")  # False due to invalid subscription ID length
validate_azure_scope("/subscriptions/12345678-a283-82f7-7g16-84548361nd8u/resourceGroup/myGroup")  # False due to 'resourceGroup' instead of 'resourceGroups'
```

I figured I'd drop this here in case anyone has the bandwidth to add it in.

**Comment by ChenxiJiang333** [comment]
Thanks for your contribution!
Yet we can't directly add it to the SDK for it's actually generated from swagger definition.
You can ask the service team to add such feature by opening an issue in https://github.com/Azure/azure-rest-api-specs/issues.

**Comment by niklash-dev** [comment]
@ChenxiJiang333 Thank you! I will have a look.

Closing this issue now.
