### ISSUE TITLE
Machine Learning Samples Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#31899]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_authentication.py#L74)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/03f3c766-2953-4988-96c7-264f6b4c858a)

**Reason:**
'inputs' is not defined

**Suggestion:**
Update code to
`inputs={"uri":"sample_uri","data_asset":"sample_data_asset","local_data":"sample_local_data"}`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_authentication.py#L46)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/b8a46f28-23f1-4154-b06b-013808f66adf)

**Reason:**
MLClient.__init__() got multiple values for argument 'credential'

**Suggestion:**
Update code to
```
ml_client = MLClient(
            DefaultAzureCredential(authority=AzureAuthorityHosts.AZURE_CHINA),
            subscription_id,
            resource_group,
            workspace,
            **kwargs
        )
```

3.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_authentication.py#L37)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/587cd4b2-3db8-4a1f-9eac-1b9e7d90e04d)

**Reason:**
MLClient.__init__() got multiple values for argument 'credential'

**Suggestion:**
Update code to

```
workspace = <Machine Learning Workspace>
ml_client = MLClient(DefaultAzureCredential(),subscription_id,resource_group, workspace)
```

4.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_authentication.py#L69)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/ffa1404c-ed2f-4d81-8060-ed4a5586863d)

**Reason:**
Unable to import 'command' package correctly

**Suggestion:**
Update code to

```
from azure.ai.ml.entities import AmlTokenConfiguration
from azure.ai.ml import command
```
@rohit-ganguly  @lmazuel @mayurid @shutchings for notification.

**Comment by diondrapeck** [comment]
@jerryshia - thanks for making the issue. A fix for this is already underway. Our samples testing was disabled and I'm working through re-enabling it and getting all of them working properly.

**Comment by jerryshia** [comment]
fixed https://github.com/Azure/azure-sdk-for-python/pull/31907
