### ISSUE TITLE
Purview Sharing Readme and Samples Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#31900]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/purview/azure-purview-sharing/README.md)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/3e340c67-ac6b-443f-89db-ec2fab4f4862)

**Reason:**
Link directed to invaild page.

**Suggestion:**
Add link"https://pypi.org/project/azure-purview-sharing/" to " Package (PyPI)"

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/purview/azure-purview-sharing/README.md#send-share-invitation-to-a-user),[link2](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#get-sent-share),[link3](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#delete-sent-share),[link4](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#get-sent-share-invitation),[link5](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#list-sent-share-invitations),[link6](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/purview/azure-purview-sharing#delete-sent-share-invitation)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/a07443b9-e39e-434d-81a5-af048a7cce36)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/c758ceff-b995-49c8-8872-f25f53f0e971)

**Reason1:**
Method requires an existing sent share but a random `sent_share_id` gived here

**Suggestion1:**
Update code to

`sent_share_id = "<sent_share_id>"`

**Reason2:**
Method requires existing sent share and sent share invitation but random id gived here

**Suggestion2:**
Update code to

`sent_share_invitation_id="<sent_share_invitation_id>"`

3.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/purview/azure-purview-sharing/samples/sent_shares_examples.py#L98)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/6fa9461a-a4ac-42ee-9036-37c245dfbc47)

**Reason:**
HttpResponsError:(65003)Cannot update Recipientkind for Recipient:2510e715-d34a-457b-be82-e2361a6ab87e
The previously defined 'sent_share_invition_id' has already been used to send a user invitiaton, another "sent_share_invitation_id" is required to send the new service invitation but it's not defined.

**Suggestion:**
Add code `sent_share_invitation_id = uuid.uuid4()`  before `invitation_response` on line 98.

@rohit-ganguly  @lmazuel @iscai-msft for notification.

**Comment by SaurabhSharma-MSFT** [comment]
@jerryshia The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
