### ISSUE TITLE
Broken link to management api's

### ISSUE THREAD

**Issue by greijer** [Azure/azure-sdk-for-python#31916]
[Enter feedback here]

The link is broken: "Explore the management Apis"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc1c70b-6ce5-8115-921d-8db80c1d43db
* Version Independent ID: 5b033609-afc0-a8e0-4059-89e77bbcd28d
* Content: [Azure Compute SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/compute?view=azure-python&source=docs)
* Content Source: [docs-ref-services/latest/compute.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/compute.md)
* Service: **compute**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

@danieljurek Could you help to take a look?

**Comment by danieljurek** [comment]
@lmazuel [CODEOWNERS](https://github.com/Azure/azure-sdk-for-python/blob/main/.github/CODEOWNERS) doesn't have an obvious owner for `compute`... Can you help route this? 

This line needs to be updated: https://github.com/Azure/azure-sdk-for-python/blob/main/.github/CODEOWNERS

**Comment by xiangyan99** [comment]
Seems like it is fixed.
