### ISSUE TITLE
metrics.list method doesnt return results after changing authorization type

### ISSUE THREAD

**Issue by amaznis** [Azure/azure-sdk-for-python#31918]
- **Package Name**: azure-mgmt-monitor
- **Package Version**: 6.0.0
- **Operating System**:Windows/Linux
- **Python Version**: 3.9

**Describe the bug**
metrics.list method doenst return results after changing authorization method from AzureCliCredential() to DefaultAzureCredential().
When tested it locally using the AzureCliCredential() authorization the method metrics.list return metrics well but when change to DefaultAzureCredential auth and deployed to azure function the method metrics.list didnt return any data.
The response status on the logs are 200.
the subscription_id and the resource group are the same locally and on deployment (Functions configuration).

Logs  from the deployment:
[Information]   {'additional_properties': {}, 'cost': None, 'timespan': None, 'interval': None, 'namespace': None, 'resourceregion': None, 'value': []}
2023-09-01T08:17:41Z   [Information]   metrics data request begin
2023-09-01T08:17:41Z   [Information]   Request URL: 'https://management.azure.com/subscriptions/{subscription_id}/resourceGroups/{rgroup}/providers/microsoft.insights/components/{comp}/providers/Microsoft.Insights/metrics?timespan=REDACTED&metricnames=REDACTED&aggregation=REDACTED&api-version=REDACTED&metricnamespace=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': '04b01de6-48a0-11ee-b61e-6e7d08aea5ce'
    'User-Agent': 'azsdk-python-azure-mgmt-monitor/6.0.0 Python/3.9.17 (Linux-5.15.116.1-1.cm2-x86_64-with-glibc2.31)'
    'Authorization': 'REDACTED'
No body was attached to the request
2023-09-01T08:17:41Z   [Information]   Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-request-id': '6f94bd03-5cb9-4d36-94a5-dbe5c9638a88'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 01 Sep 2023 08:17:40 GMT'
    'Content-Length': '133'

Logs from local: 
[2023-09-01T08:37:02.744Z] Request URL: 'https://management.azure.com/subscriptions/{subscription_id}/resourceGroups/{rgoup}/providers/microsoft.insights/components/{compo}/providers/Microsoft.Insights/metrics?timespan=REDACTED&metricnames=REDACTED&aggregation=REDACTED&api-version=REDACTED&metricnamespace=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': 'b9644a10-48a2-11ee-9453-8c8caa0e5b0f'
    'User-Agent': 'azsdk-python-azure-mgmt-monitor/6.0.0 Python/3.9.13 (Windows-10-10.0.19044-SP0)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2023-09-01T08:37:02.743Z] metrics in else begin
[2023-09-01T08:37:02.925Z] Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-ratelimit-remaining-subscription-reads': '11992'
    'Request-Context': 'REDACTED'
    'x-ms-request-id': '{38ed4b8d-b749-45ea-a87a-2bbe3a1d1a68}'
    'Strict-Transport-Security': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 01 Sep 2023 08:37:01 GMT'
    {'additional_properties': {}, 'cost': 4, 'timespan': '2023-09-01T08:31:52Z/2023-09-01T08:36:52Z', 'interval': datetime.timedelta(seconds=60), 'namespace': 'mac_address_camera_status', 'resourceregion': 'westeurope', 'value': [<azure.mgmt.monitor.v2021_05_01.models._models_py3.Metric object at 0x000002A4903466A0>]}

**Expected behavior**
Its supposed to return the same as the local one after changing the authorization type.

**Comment by kashifkhan** [comment]
Thank you for the feedback @amaznis . We will investigate and get back to you asap.

**Comment by ChenxiJiang333** [comment]
Hi, @amaznis 
`DefaultAzureCredential` is a credential chain which attempts to get token from credentials in queue. Please provide the information about which single credential actually gave the token when using azure function. 
It can be found in the log like:
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/62e75342-ee54-402c-9617-b05793288998)
