### ISSUE TITLE
AzureMonitorWorkspacesOperations Class does not support to publicNetworkAccess configuration.

### ISSUE THREAD

**Issue by romangallego** [Azure/azure-sdk-for-python#31921]
**Is your feature request related to a problem? Please describe.**
I am using "azure-mgmt-monitor==6.0.2" to create azure monitor workspace.
the following block would create it:
```
def create_azure_monitor_workspace(rdata: PMap) -> None:
        """
        Creates/updates Azure Monitor Workspace
        :Param data: pmap or v with the info
        """
        subscription_id = rdata['subscription_id']
        resource_group_name = rdata['resource_group_name']
        # parameters = rdata['parameters']
        #For clarity I declare below the value of parameters
        parameters = {
                'location': "westeurope",
                'tags': {
                    'env': 'test1'
                },
                'properties': {
                    "publicNetworkAccess": "Disabled"
                }
        }
        name = rdata['name']
        monitor_client = MonitorManagementClient(credential, subscription_id)
        amw = monitor_client.azure_monitor_workspaces.create(resource_group_name, name, parameters)
```
It creates the AMW without problem EXCEPT it ignores to leave the Public Network Access disabled. The parameter block is a type AzureMonitorWorkspaceResource or IO that accepts as parameters location and tags but not other specs such as the publicnetworkaccess. 

As result using the Azure SDK it is NOT possible to set the desired public network access as it should.

I am open to workarounds, if anybody knows any!

**Describe the solution you'd like**
The block `parameters`as mentioned  above or similar should be able to set the publicNetworkaccess of the created AMW.

**Describe alternatives you've considered**
There is NONE if you pursue full automation.

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Python sdk is generated from the swagger definition. Such feature is already defined in the [stable api version](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Monitor/stable/2023-04-03/monitoringAccounts_API.json#L466) and may be applied in python package in the next releases.

**Comment by romangallego** [comment]
Hey @ChenxiJiang333 ,
I am using ** "azure-mgmt-monitor==6.0.2"** that was regenerated after [stable api version](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Monitor/stable/2023-04-03/monitoringAccounts_API.json#L466).

As you can see I am passing a dict to set it up:
parameters = {
                'location': "westeurope",
                'tags': {
                    'env': 'test1'
                },
                'properties': {
                    "publicNetworkAccess": "Disabled"
                }
        }
which is compliant with the REST API spec. I believe that property is readonly or similar because the execution does not fail NOR updates the publicNetworkAccess property.

**Comment by ChenxiJiang333** [comment]
Hi, @romangallego.
I have tried the code and the execution didn't return any failure as well, but it doesn't mean that the parameters passed were all suitable.
Here's my log. You can see that invaild parameters would be abandoned in the serialization so the `publicNetworkAccess` property would not be included in the request body and was not sent at the beginning.
```
2023-09-05 13:04:37,445 - azure.core.pipeline.policies._universal - DEBUG - Request URL: 'https://management.azure.com/xxxxx'
Request method: 'PUT'
Request headers:
    'Content-Type': 'application/json'
    'Content-Length': '52'
    'Accept': 'application/json'
    'x-ms-client-request-id': 'b4b0fa37-4ba9-11ee-868e-a8b13b79b46f'
    'User-Agent': 'azsdk-python-azure-mgmt-monitor/6.0.2 Python/3.10.11 (Windows-10-10.0.22621-SP0)'
    'Authorization': xxxxx'
Request body:
{"tags": {"env": "test1"}, "location": "westeurope"}
```

Also, the source code of the latest package can be found [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/_monitor_management_client.py#L66). It shows that when it comes to the operations about `azure_monitor_workspaces`, the current api used is still in preview version.

**Comment by romangallego** [comment]
Thank you @ChenxiJiang333! I do appreciate your help!
I will open the issue to the azure-rest-api-specs
