### ISSUE TITLE
PartionKey and/or RowKey dropped for empty string

### ISSUE THREAD

**Issue by gr-rob** [Azure/azure-sdk-for-python#31920]
https://github.com/Azure/azure-sdk-for-python/blob/87c886d5d61db93f2d7d221602ee93a6b4123b62/sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py#L161

https://github.com/Azure/azure-sdk-for-python/blob/87c886d5d61db93f2d7d221602ee93a6b4123b62/sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py#L166

PartitionKey and RowKey will be dropped if their value is an empty string as an empty string is evaluated as False by Python.

161 and 166 should explicitly check for None value:

    # Partition key is a known property
    partition_key = properties.pop("PartitionKey", None)
    if partition_key is not None:
        entity["PartitionKey"] = partition_key

    # Row key is a known property
    row_key = properties.pop("RowKey", None)
    if row_key is not None:
        entity["RowKey"] = row_key

**Comment by kashifkhan** [comment]
Thank you for the feedback @gr-rob . We will investigate and get back to you asap.

**Comment by YalinLi0312** [comment]
Hi @gr-rob , we have fix it in the latest release 12.4.4 which just published today: https://pypi.org/project/azure-data-tables/ Please give it a try and let us know any further issues.
