### ISSUE TITLE
SDK misses operation for creating "Managed Private Endpoint" for Managed Grafana 

### ISSUE THREAD

**Issue by romangallego** [Azure/azure-sdk-for-python#31933]
**Is your feature request related to a problem? Please describe.**
azure-mgmt-dashboard v1.0 or azure-mgmt-network lastest version don't support the creatation of Managed Private Endpoint for Managed Grafana.

For full automation of managed grafana using azure sdk for python that is a MUST when the customer as us is using Private Endpoints to access to Managed Prometheus.

If somebody has a workaround about how to automate it, please share it with us. 

**Describe the solution you'd like**
As in datafactory add a class that creates Managed Privated Endpoints.

Right now we have to do it portal.azure.com with users elevated permissions instead of using service principals.
<img width="930" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/17048028/5564ff59-aa92-463a-bd04-09545faab901">

**Describe alternatives you've considered**
There is NONE for automating the build, unless better suggestion.

**Additional context**

**Comment by romangallego** [comment]
Anybody on azure side would be able to take a look to this?

**Comment by mccoyp** [comment]
Hi @romangallego, thank you for opening an issue! I'm tagging folks who should be able to help; we'll get back to you as soon as possible.

**Comment by ChenxiJiang333** [comment]
Hi @romangallego 
Seems such feature was not included in the swagger https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dashboard/resource-manager/Microsoft.Dashboard/stable/2022-08-01/grafana.json#L433.  
Please open issue in https://github.com/Azure/azure-rest-api-specs/issues and mark with label `feature request`. Once swagger is fixed, python SDK will release new version to support it.

**Comment by xiangyan99** [comment]
@romangallego Please open issues in https://github.com/Azure/azure-rest-api-specs repo to track it.
