### ISSUE TITLE
SDKs do not support base64 encoded input type for Azure Form Recognizer. The same is supported via REST API.

### ISSUE THREAD

**Issue by shawrk3387** [Azure/azure-sdk-for-python#31934]
**Is your feature request related to a problem? Please describe.**
Python SDK does not allow the base64 encoded input data type to Azure Form Recognizer 

**Describe the solution you'd like**
Just like REST API, I would like the Python SDK to support base64 encoded input type to Azure Form Recognizer.

**Comment by mccoyp** [comment]
Hi @shawrk3387, thank you for opening an issue! I'm tagging folks who should be able to help; we'll get back to you as soon as possible.

**Comment by shawrk3387** [comment]
Any update on this issue? The Customer is looking for a quick resolution of the same.

**Comment by catalinaperalta** [comment]
Thanks for reaching out @shawrk3387! We're discussing adding this feature in our next release. Is the customer using base64 through the REST API currently? What endpoints are you targeting?

**Comment by vidyann** [comment]
Hi @catalinaperalta the customer resource is in JioIndiaWest region & he is trying with General model.

**Comment by netrasagarmal** [comment]
I also need this azure form recognizer feature support of base64 for python sdk.

**Comment by catalinaperalta** [comment]
Hi folks, just letting you know we're trying to find a possible workaround to unblock you. Thanks!

**Comment by YalinLi0312** [comment]
Hi folks, we are working on it now. It will be available in a patch release soon, thanks!

**Comment by YalinLi0312** [comment]
Hi @shawrk3387, it should be supported in a rebranding package [azure-ai-documentintelligence](https://pypi.org/project/azure-ai-documentintelligence/). Can you try on it?
