### ISSUE TITLE
Communication: CallAutomation: `invitation_timeout` is not a known attribute of `AddParticipantRequest`

### ISSUE THREAD

**Issue by Frankkkkk** [Azure/azure-sdk-for-python#31938]
- **Package Name**:  azure-communication
- **Package Version**: latest 

**Describe the bug**
Hi,
When adding a participant to a call, I get the following warning:
```
WARNING:azure.communication.callautomation._generated._serialization:invitation_timeout is not a known attribute of class <class 'azure.communication.callautomation._generated.models._models.AddParticipantRequest'> and will be ignored
```

Indeed, we can see that `add_participant` creates an `AddParticipantRequest` [with the `invitation_timeout` parameter](https://github.com/Azure/azure-sdk-for-python/blob/505d4108da0b5a5fae45adc7e438d267301f592f/sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py#L348), whereas the [`AddParticipantRequest` wants `invitation_timeout_in_seconds`](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py#L144).

**To Reproduce**
use the `CallConnection.add_participant`  fun

**Expected behavior**
no warning + passed parameters

Cheers

**Comment by mccoyp** [comment]
Hi @Frankkkkk, thank you for opening an issue! I'm tagging folks who should be able to help; we'll get back to you as soon as possible. cc @turalf

**Comment by minwoolee-msft** [comment]
Thank you for the feedback - i will take a look at the issue.

**Comment by Frankkkkk** [comment]
Thanks for the fix. Could you also deploy a new pypi version ?

**Comment by minwoolee-msft** [comment]
Hi Frank,
I will have new version (1.1.0b2) released this week.
Also note, new 1.1.0 with this fix will be released this year.
I will post here once 1.1.0b2 is released.

**Comment by minwoolee-msft** [comment]
I am still working on the release - will write here once i have an update

**Comment by minwoolee-msft** [comment]
Update: latest stable version (1.1) released with fix here: https://pypi.org/project/azure-communication-callautomation/#history
