### ISSUE TITLE
Support Multiple Ip address in generate_blob_sas function in Azure store SDK

### ISSUE THREAD

**Issue by rahul-sontakke** [Azure/azure-sdk-for-python#31957]
**Is your feature request related to a problem? Please describe.**
We are trying to generate azure SAS for blobs and wanted to provide ip level restrictions.
Currently we can provide wither IP address  or range of IP addresses e.g. 121.12.34.15 or 121.12.34.15 - 121.12.34.20 

**Describe the solution you'd like**
We would like to provide separate multiple different IP addresses like 121.12.34.15 or 121.15.30.255 or  121.2.2.10

Location in code:

from azure.storage.common.sharedaccesssignature import (

def generate_blob_sas(
        account_name,  # type: str
        container_name,  # type: str
        blob_name,  # type: str
        snapshot=None,  # type: Optional[str]
        account_key=None,  # type: Optional[str]
        user_delegation_key=None,  # type: Optional[UserDelegationKey]
        permission=None,  # type: Optional[Union[BlobSasPermissions, str]]
        expiry=None,  # type: Optional[Union[datetime, str]]
        start=None,  # type: Optional[Union[datetime, str]]
        policy_id=None,  # type: Optional[str]
def generate_blob_sas(
        account_name,  # type: str
        container_name,  # type: str
        blob_name,  # type: str
        snapshot=None,  # type: Optional[str]
        account_key=None,  # type: Optional[str]
        user_delegation_key=None,  # type: Optional[UserDelegationKey]
        permission=None,  # type: Optional[Union[BlobSasPermissions, str]]
        expiry=None,  # type: Optional[Union[datetime, str]]
        start=None,  # type: Optional[Union[datetime, str]]
        policy_id=None,  # type: Optional[str]
        ip=None,  # type: Optional[str]
        **kwargs # type: Any
    ):        **kwargs # type: Any
    ):

**Comment by mccoyp** [comment]
Hi @rahul-sontakke, thank you for opening an issue! I'll tag some folks who can take a look at your feature request as soon as possible.

Just to clarify, which Storage library does this apply to?

**Comment by rahul-sontakke** [comment]
@mccoyp  This is applicable to storage -> azure storage blob  library.

to be precise I am using following function 

block_blob_service.generate_blob_shared_access_signature(container_name,blob_name,permission,expiry,protocol,ip)

**Comment by vincenttran-msft** [comment]
Hi @rahul-sontakke, thanks for your inquiry!

This particular feature will require support from the Storage service before it can be added to the SDK. Please consider submitting this feedback to the Storage service team via upvoting or creating a new idea at [https://aka.ms/AzStorageFeedback](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzStorageFeedback&data=05%7C01%7Cvincenttran%40microsoft.com%7Cd97d58f24b624451914108daa7fb0bd6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638006993974197392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jfpqXMo6WR%2BrQqGK8actrFbPOZEUumYoOd2jEP7d4As%3D&reserved=0).
 
This will help the service team gauge interest and prioritize new features. If the feature becomes available in the service, it will be promptly added to the SDK.

Thanks!
