### ISSUE TITLE
ContainerClient.list_blobs(prefix=...) has no effect on the listing

### ISSUE THREAD

**Issue by akx** [Azure/azure-sdk-for-python#31952]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.17.0
- **Operating System**: any
- **Python Version**: 3.11

**Describe the bug**

`ContainerClient.list_blobs(prefix="foo")` is the same as `ContainerClient.list_blobs()`, but does not raise an "unknown argument" sort of error.

This is caused by how `prefix` in the (undocumented!) `**kwargs`  is partialed into `list_blob_flat_segment` here:  https://github.com/Azure/azure-sdk-for-python/blob/c2ca191e736bb06bfbbbc9493e8325763ba990bb/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L821-L825
but overwritten on the next line with the value of `name_starts_with` (since `ItemPaged` eventually overrides the partialed `prefix`):
https://github.com/Azure/azure-sdk-for-python/blob/c2ca191e736bb06bfbbbc9493e8325763ba990bb/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L826-L828

Other arbitrary `**kwargs` may end up being eventually passed down to `Transport.send` (unless they're consumed by `list_blob_flat_segment`), leading to e.g. `TypeError: Session.request() got an unexpected keyword argument 'blorpfix'`. This isn't good behavior either, but that's not the point of this issue.)

In other words, `prefix` is accepted but never does anything of consequence, leading to inadvertently listing the entirety of a container, which can be pretty slow and heavy.

**To Reproduce**

1. Construct a `ContainerClient` for a container with some data, say, `aa` and `bb`.
2. Call `ContainerClient.list_blobs(prefix="a")`, expecting to find `"aa"`.
3. The return value will contain both `aa` and `bb`, since `prefix` does nothing.

**Expected behavior**

I think the reasonable behavior would be either to:

* a ValueError should be raised if a non-empty `prefix` is passed, since it will never be used
* if `name_starts_with` is not passed, but `prefix` is, a warning "you should use `name_starts_with` instead" should be raised, and the value of `prefix` should be used for `name_starts_with`.

More broadly, the API should not pass arbitrary `**kwargs` around, but that seems like a more systemic issue.

**Comment by kashifkhan** [comment]
Thank you for the feedback @akx . We will investigate and get back to you asap.

**Comment by vincenttran-msft** [comment]
Hi @akx Aarni, thanks for your inquiry. I can see how this can be confusing, and quite frankly I am unsure as to why `prefix` seemed to have been renamed to `name_starts_with` with the release of Track2 `azure-sdk-for-python`. This is not the first instance of this issue we have seen, likely due to the fact that in Track1 the same API seemed to accept `prefix` but was renamed since then 😄 

With that being said, I will inquire with the team to see how we can best resolve this specific instance.

Thanks!

**Comment by vincenttran-msft** [comment]
Hi @akx Aami, sorry for the delay. We have gone ahead and finalized what the expected behavior should be in this case and the fix will be present as part of our next release. I have attached the pull-request containing the fix above 😄 

Thanks!
