### ISSUE TITLE
Remove pin of `opentelemetry-api` from `azure-core-tracing-opentelemetry`

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#31965]
Newest `1.20.0` release of opentelemetry packages breaks `latestdependency` for `azure-core-tracing-opentelemetry`.

This is due to an irreconcilable conflict when installing the following packages:

```bash
opentelemetry-api==1.20.0
opentelemetry-sdk # any version
opentelemetry-instrumentation-requests
```

The problem is this.

```bash
opentelemetry-sdk 1.20.0 depends on opentelemetry-semantic-conventions==0.41b0
opentelemetry-instrumentation-requests 0.40b0 depends on opentelemetry-semantic-conventions==0.40b0
opentelemetry-sdk 1.20.0 depends on opentelemetry-semantic-conventions==0.41b0
opentelemetry-instrumentation-requests 0.39b0 dependson on opentelemetry-semantic-conventions==0.40b0
...
```

`opentelemetry-sdk` and `api` can depend on a version of `opentelemetry-semantic-conventions` just fine, but when we introduce `opentelemetry-instrumentation-requests` there isn't a combination of packages that satisfies _all_ their dependencies on this requirement.

Going to pin to 1.19.0 and wait for reconciliation. CC @xiangyan99

**Comment by lzchen** [comment]
@scbedd 

This can be reverted due to the releasing of openelemetry-instrumentation-requests v0.41b https://pypi.org/project/opentelemetry-instrumentation-requests/
