### ISSUE TITLE
Creating linked services (e.g. Azure Databricks) can lead to broken linked service definitions in DataFactory

### ISSUE THREAD

**Issue by myrlo123** [Azure/azure-sdk-for-python#31975]
- **Package Name**: azure.mgmt.datafactory 
- **Package Version**: 3.1.0
- **Operating System**: Windows / WSL -> VsCode devcontainer
- **Python Version**: 3.10

**Describe the bug**
When creating a linked service on ADF via DataFactory SDK, there's no type check e.g. for Databricks (AzureDatabricksLinkedService) numerical values, e.g. new_cluster_num_of_worker. Expected would be a string (e.g. "1") but it's also possible to invoke the function with an integer. That ultimately leads to and invalid linked service definition in ADF, which furthermore breaks the ADF UI (see screenshot)

**To Reproduce**
1. Create a new linked service via SDK (->DataFactoryClient.linked_services.create_or_update) or directly edit a json in ADF linked service and set property "new_cluster_num_of_worker" from string (e.g. "1") to int (e.g. 1). 
2. Save and publish
3. Try to open the linked service properties via ADF UI, it is not displayed correctly and breaks (needs a reload) if trying to correct it.
(see invalid_config.png for further details.)

**Expected behavior**
1. TypeCheck or automatically correct invalid types in the function signature
2. @ADF: Make a check before posting invalid Json or fix it automatically.

**Screenshots**
![invalid_config](https://github.com/Azure/azure-sdk-for-python/assets/46593982/c78d4fe6-f03d-4997-8c75-3f6cd53b2425)
![valid_config](https://github.com/Azure/azure-sdk-for-python/assets/46593982/1f7742cd-4912-466d-ba1a-b7d19e2af871)

**Additional context**

**Comment by mccoyp** [comment]
Hi @myrlo123, thank you for opening an issue! I'll tag some folks who should be able to help; we'll get back to you as soon as possible.

**Comment by ChenxiJiang333** [comment]
Python sdk is generated by swagger definitions. An issue has been opened for a fix.
