### ISSUE TITLE
ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.10/dist-packages/azure/mgmt/recoveryservicesbackup/__init__.py)

### ISSUE THREAD

**Issue by markarping** [Azure/azure-sdk-for-python#31993]
- **Package Name**:  azure.mgmt.recoveryservicesbackup 
- **Package Version**: 
- **Operating System**: 22.04.3 LTS
- **Python Version**: python 3.10

**Describe the bug**
We have been trying to setup an azure integration with ansible on azure Linux vms. when we execute the playbook, it's failed to execute.  We have opened MS ticket to troubleshoot these issues and asked us to reach product team for the support. Could you please help us to fixing this issue asap. 

**To Reproduce**
1. ansible 2.10.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

2. # python3 --version
Python 3.10.12

3. ---
- name: Get Azure VM Info
  hosts: localhost
  gather_facts: no  # We don't need facts for this playbook
  tasks:
    - name: Get VM Info
      azure_rm_virtualmachine_info:
        resource_group: "{{ Resourcegroupname }}"
        name: "{{ vmname}}"
      register: vm_info
    - name: Display VM Info
      debug:
        msg: vm_info

**Expected behavior**
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_virtualmachine_info_payload_98uulu_q/ansible_azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 275, in <module>
    from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.10/dist-packages/azure/mgmt/recoveryservicesbackup/__init__.py)

**Screenshots**

**Additional context**

**Comment by mccoyp** [comment]
Hi @markarping, thank you for opening an issue! I'll tag some folks who should be able to help; we'll get back to you as soon as possible.

**Comment by ChenxiJiang333** [comment]
This issue would be fixed in the next release(before 9/20). For now, you can try to use this [private package](https://newstorageyyc.blob.core.windows.net/2023-08/sdk_pr_31872/azure_mgmt_recoveryservicesbackup-6.0.0-py3-none-any.whl) to develop.

**Comment by markarping** [comment]
We tried to install the package and after that we are getting a below error message. can you please refer the below message and assist me to provide the solutions. 


The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_virtualmachine_payload_8x9l6hi9/ansible_azure_rm_virtualmachine_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 276, in <module>
    import azure.mgmt.recoveryservicesbackup.models as RecoveryServicesBackupModels
ModuleNotFoundError: No module named 'azure.mgmt.recoveryservicesbackup.models'
fatal: [127.0.0.1]: FAILED! => {

**Comment by ChenxiJiang333** [comment]
@markarping 
I found the source code of the tool you're using: https://github.com/ansible-collections/azure/.
This [line](https://github.com/ansible-collections/azure/blob/dev/plugins/module_utils/azure_rm_common.py#L276,
) should be updated to `import azure.mgmt.recoveryservicesbackup.activestamp.models as RecoveryServicesBackupModels`.
Please open issue to turn to the tool developer to fix it.
