### ISSUE TITLE
Creating AudioOutputConfig object with the filename parameter specified results in type checking error

### ISSUE THREAD

**Issue by Ivanes1** [Azure/azure-sdk-for-python#32055]
- [**azure-cognitiveservices-speech**](https://pypi.org/project/azure-cognitiveservices-speech/): 
- package version: **v1.32.1*: 
- operating system: **macOS Ventura 13.3.1 (a)**:
- python version: **3.11.4**: 

**Describe the bug**
When I try to create an audio configuration for my speech synthesizer as follows:
```python
audio_config = speechsdk.audio.AudioOutputConfig(filename=output_dir)
``` 
(so I use an output file, not output stream),
my type checker gives me the following error:
```
Argument of type "None" cannot be assigned to parameter "stream" of type "AudioOutputStream" in function "__init__"
```
even though the `stream` parameter is `None` by default

**To Reproduce**
1. Enable type checker by creating `./.vscode/settings.json` with the following code:
```json
{
    "python.analysis.typeCheckingMode": "basic"
}
```
2. Create a python file and add the following code to it:
```python
import azure.cognitiveservices.speech as speechsdk

audio_config = speechsdk.audio.AudioOutputConfig(filename="your_file")
```

**Expected behavior**
No type checking error should appear

**Comment by pvaneck** [comment]
Hey @Ivanes1. The `azure-cognitiveservices-speech` package isn't maintained in this repository. Try moving your issue to this repo: https://github.com/Azure-Samples/cognitive-services-speech-sdk. This is for speech SDK samples, but the maintainers of the speech SDK are active there and can help.
