### ISSUE TITLE
Pip installation failure

### ISSUE THREAD

**Issue by cjemmott** [Azure/azure-sdk-for-python#3209]
When I run

`pip install azure
`
I get the failure:

```
  Found existing installation: azure-mgmt-iothubprovisioningservices 0.1.0
    Uninstalling azure-mgmt-iothubprovisioningservices-0.1.0:
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\cjemmott\\AppData\\Local\\Temp\\pip-uninstall-zx6wxpwi\\users\\cjemmott\\appdata\\roaming\\python\\python36\\site-packages\\azure\\mgmt\\iothubprovisioningservices\\models\\__pycache__\\shared_access_signature_authorization_rule_access_rights_description.cpython-36.pyc'
```
Just to be safe I ran `pip uninstall azure` and `pip uninstall azure-storage` first.

Windows 10, Python 3.6.5 :: Anaconda, pip 18.0.

Any ideas?

**Comment by lmazuel** [comment]
Might be a long path issue, did you enable long path support?
https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

**Comment by cjemmott** [comment]
Nailed it!

For the next person, here are detailed instructions for enabling in Windows 10: https://stackoverflow.com/questions/27680647/does-max-path-issue-still-exists-in-windows-10
