### ISSUE TITLE
Problem in fetching blob url using new sdk

### ISSUE THREAD

**Issue by vmksuw** [Azure/azure-sdk-for-python#321]
Hi, i get nothing in blob url in the following call. It used to work with old sdk.

blobs = blob_service.list_blobs(container_name)
for blob in blobs:
    print blob.url

**Comment by prashanthmadi** [comment]
Hi,

There is no url in that response. It has only name and properties 

https://msdn.microsoft.com/en-us/library/azure/dd135734.aspx

**Comment by prashanthmadi** [comment]
May be you can create blob url's using name received from blob_list. 

BLOB_URL = https://myaccount.blob.core.windows.net/CONTAINER_NAME/BLOB_NAME

**Comment by huguesv** [comment]
They deprecated this in the REST api.  You can use this helper function:
```
public_url = blob_service.make_blob_url(container_name, blob_name)
```

**Comment by vmksuw** [comment]
Hi  huguesv,
Using the same since i am using new sdk (master branch).
Thanks for the reply.
