### ISSUE TITLE
SDKs do not support base64 encoded input type for Azure Form Recognizer. The same is supported via REST API

### ISSUE THREAD

**Issue by netrasagarmal** [Azure/azure-sdk-for-python#32104]
*Is your feature request related to a problem? Please describe.*
Python SDK does not allow the base64 encoded input data type to Azure Form Recognizer.

*Describe the solution you'd like*
Just like REST API, I would like the Python SDK to support base64 encoded input type to Azure Form Recognizer.

**Comment by kashifkhan** [comment]
Thank you for the feedback @netrasagarmal . We will investigate and get back to you asap.

**Comment by catalinaperalta** [comment]
This issue is a repeat of #31934. Closing and tracking in the other issue. Let's follow up there, thanks!
