### ISSUE TITLE
Image not rendering - "Error Fetching Resource" displayed

### ISSUE THREAD

**Issue by mukmookk** [Azure/azure-sdk-for-python#32118]
[Enter feedback here]
At the bottommost image, the image is not rendered. It might be a link broken. Actually the situation also happens some other "Overview" pages under management section. please check.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63fd23d8-4407-1340-3b20-8e30a2bb2ddf
* Version Independent ID: abf3fc9e-264e-7253-f463-0f257df6f54f
* Content: [Microsoft Azure SDK for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-applicationinsights-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/mgmt-applicationinsights-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/mgmt-applicationinsights-readme.md)
* Service: **azure-monitor**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by swathipil** [comment]
Hi @mukmookk - Thanks for opening an issue! We'll take a look asap!

**Comment by ChenxiJiang333** [comment]
Thanks for the feedback.
Since the service didn't work any longer, we would just cut out this invalid link.
