### ISSUE TITLE
ImportError: cannot import name 'SemanticConfiguration' from 'azure.search.documents.indexes.models'

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Azure/azure-sdk-for-python#32121]
Hi,

Doing

```python
from azure.search.documents.indexes.models import (
    SemanticConfiguration,
)
```

results in 

```
Traceback (most recent call last):
  File "/Users/FRANCESCO.ZUPPICHINI/Documents/dbi_alphaai_document_llm_search/scripts/embed_with_azure_cognitive_search.py", line 16, in <module>
    from azure.search.documents.indexes.models import (
ImportError: cannot import name 'SemanticConfiguration' from 'azure.search.documents.indexes.models' (/Users/FRANCESCO.ZUPPICHINI/Documents/dbi_alphaai_document_llm_search/.venv/lib/python3.11/site-packages/azure/search/documents/indexes/models/__init__.py)
```

I remember somewhere in the less intuitive place ever there was something about I need to install something special for that, what was it?

thanks

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Do you mean `SemanticSettings`?

**Comment by hmih** [comment]
> Thanks for reaching out.
> 
> Do you mean `SemanticSettings`?

I can't find this import: `ImportError: cannot import name 'PrioritizedFields' from 'azure.search.documents.indexes.models' (.venv/lib/python3.11/site-packages/azure/search/documents/indexes/models/__init__.py)` on python 3.11 with a pin on the sdk: 

```
[[package]]
name = "azure-search-documents"
version = "11.4.0"
description = "Microsoft Azure Cognitive Search Client Library for Python"
optional = false
python-versions = ">=3.7"
files = [
    {file = "azure-search-documents-11.4.0.tar.gz", hash = "sha256:599f269f106fb51e646ff426a218c21811575598e6a769b23fa4a0127c0f57e0"},
    {file = "azure_search_documents-11.4.0-py3-none-any.whl", hash = "sha256:e435266dc992a3450dc475309c9475f89a4bb0e9dac838140e609d9f1c7608ac"},
]
```

**Comment by ivy-intano** [comment]
I am running this notebook that "Azure Cognitive Search LangChain Vector Code Sample".

I get an error "cannot import name 'SemanticSettings' from 'azure.search.documents.indexes.models" when i run the code under section "Create embeddings and vector store instances"

https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-python-langchain-sample.ipynb

python version : 3.10.10
azure-search-documents==11.4.0

**Comment by hmih** [comment]
@ivy-intano rollback to `11.4.0b8`

**Comment by inrock1** [comment]
Hi, guys.
in azure-search-documents==11.4.0 was renamed this fields:
    HnswAlgorithmConfiguration,  # HnswVectorSearchAlgorithmConfiguration is old
    SemanticPrioritizedFields,  # PrioritizedFields outdated
    SemanticSearch,  # SemanticSettings outdated
