### ISSUE TITLE
Add Support for Workload Identity Federation for Azure Service Connections

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#32143]
Tracking item to add WorkloadIdentityCredential support for Azure Service Connections (App Config).  @KarishmaGhiya is driving the investigation.

Original partner ask: https://github.com/Azure/azure-sdk-for-js/issues/27093

From @KarishmaGhiya: 
> @joshfree I spoke to @ChristineWanjau Looks like App Configuration is using the preview feature Azure Devops for their authenication for service connection using workload identity. Essentially what happens is when they request an idToken, it gets supplied by Azure Devops (https://devblogs.microsoft.com/devops/public-preview-of-workload-identity-federation-for-azure-pipelines/#custom-azure-tasks-and-extensions). But this idToken is not written to a file, it's speculated to be supplied through the env. So the ask was that do we support the scenario.

**Comment by LiliDeng** [comment]
@joshfree @xiangyan99 any plan for this? thanks!
