### ISSUE TITLE
ADF V2- Can we test a linked service connection via the python library?

### ISSUE THREAD

**Issue by saulcruz** [Azure/azure-sdk-for-python#3214]
In the UI, it is possible to test the connection of an already defined LinkedService

![image](https://user-images.githubusercontent.com/28897049/44746772-48c07e00-aad9-11e8-9f03-56563f7f7f53.png)

We are automating the creation of our pipelines using a mapping table and this library, and as part of our unit testing we test our code by checking if an object got created or not, however we have not been able to automate the testing of our linked service connection, is there a way to test the connection via this library? 

The way we do it now is by creating a pipeline and datasets, the creation of  these objects would fail if a reference is not successfully linked to a database/adls/azure storage/etc.

**Comment by lmazuel** [comment]
@hvermis ?

**Comment by hvermis** [comment]
These API-s are not available in our swagger/SDK-s, they are only used in our UI.
