### ISSUE TITLE
[formrecognizer] Expose send_request method on clients

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#32151]
Expose a `send_request` method on `FormRecognizerClientBase` and `FormRecognizerClientBaseAsync`. 

- [ ] `send_request` should leverage the `send_request` method on the generated clients. 
- [ ] Add convenience for relative paths.
   - Allow users to specify a relative path and simply append to the base url (endpoint) that is on the client
- [ ] Make sure the correct `api_version` is appended to the request. 
   - If the `api_version` is included in the url then leave as is, else if the `api_version` is missing append it to the url
- [ ] Add tests
- [ ] Add samples

For more information, refer to the implementation in the keyvault library: https://github.com/Azure/azure-sdk-for-python/blob/a193fbc54bdd8145a4b0643939af19a8ea2abb32/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py#L137

**Comment by YalinLi0312** [comment]
This issue is for resolving https://github.com/Azure/azure-sdk-for-python/issues/31934
