### ISSUE TITLE
DefaultAzureCredential doesn't work on GraphRbacManagementClient

### ISSUE THREAD

**Issue by ToxicGLaDOS** [Azure/azure-sdk-for-python#32160]
- **Package Name**: azure-graphrbac
- **Package Version**: 0.61.1
- **Operating System**: Linux
- **Python Version**: Python 3.11.4

**Describe the bug**

We get `AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'` when using the `DefaultAzureCredential` to authenticate to `GraphRbacManagementClient`
```
Traceback (most recent call last):
  File "/home/jeff/azure-sdk-test/./new.py", line 18, in <module>
    print(list(graph_object))
          ^^^^^^^^^^^^^^^^^^
  File "/home/jeff/azure-sdk-test/env/lib/python3.11/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/home/jeff/azure-sdk-test/env/lib/python3.11/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeff/azure-sdk-test/env/lib/python3.11/site-packages/azure/graphrbac/operations/objects_operations.py", line 98, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeff/azure-sdk-test/env/lib/python3.11/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeff/azure-sdk-test/env/lib/python3.11/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeff/azure-sdk-test/env/lib/python3.11/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeff/azure-sdk-test/env/lib/python3.11/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'
```

**To Reproduce**
1. Run this script
```
#!/usr/bin/env python
from azure.identity import DefaultAzureCredential
from azure.graphrbac import GraphRbacManagementClient

tenant_id = "<tenant_id>"
principal_id = '<principal_id>'
principal_type = 'User'


graph_rbac_management_client = GraphRbacManagementClient(DefaultAzureCredential(), tenant_id)

graph_object = graph_rbac_management_client.objects.get_objects_by_object_ids({
    'object_ids': [principal_id],
    'types': [principal_type]
})
print(list(graph_object))
```
**Expected behavior**
We should be able to authenticate with `AzureDefaultCredential`

**Additional context**
All python packages in the virtual environment:
```
>pip freeze
adal==1.2.7
azure-common==1.1.28
azure-core==1.29.4
azure-graphrbac==0.61.1
azure-identity==1.14.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
cryptography==41.0.4
idna==3.4
isodate==0.6.1
msal==1.24.0
msal-extensions==1.0.0
msrest==0.7.1
msrestazure==0.6.4
oauthlib==3.2.2
portalocker==2.8.2
pycparser==2.21
PyJWT==2.8.0
python-dateutil==2.8.2
requests==2.31.0
requests-oauthlib==1.3.1
six==1.16.0
typing_extensions==4.8.0
urllib3==2.0.5
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

azure-graphbrac is a track 1 library which does not work well with azure-identity.

Did you have a chance to look at https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md?

**Comment by ToxicGLaDOS** [comment]
@xiangyan99 Is it possible to mix the two in the same script? Most of the libraries I'm using are newer and fine with accepting `DefaultAzureCredential`, but when I use `get_client_from_cli_profile` it warns me that I need to use `azure-cli-core<2.21.0`, but that doesn't install properly due to 
```
Collecting jsmin~=2.2.2 (from azure-cli<2.21.0)
  Using cached jsmin-2.2.2.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in jsmin setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

which I'm guessing is because the old version of the library doesn't support python 3.11.

I'm just not sure how to get a credential for `GraphRbacManagementClient` if `DefaultAzureCredential` and `get_client_from_cli_profile` doesn't work.

**Comment by ToxicGLaDOS** [comment]
After some more digging I found a solution that seems to work. Using the `CredentialWrapper` class from [this post](https://stackoverflow.com/a/64129363) we can auth using `azure-identity`. A fairly complete example can be found [here](https://stackoverflow.com/a/69463717). That post also says
> EDIT May 2022: As of May 2022, all SDKs have been re-released with native support for azure-identity. If you still encounter this error with a given SDK on its latest version, please open an issue asking for a re-release of that SDK here: https://github.com/Azure/azure-sdk-for-python/issues

Which is why I thought I'd open this issue, but maybe `azure-graphrbac` is a special case.

**Comment by xiangyan99** [comment]
Unfortunately, azure-graphrbac is a special case. You can see that its last release was on 05/2019: https://pypi.org/project/azure-graphrbac/#history.
