### ISSUE TITLE
Incorrect type for DeploymentProperties.rate_limits

### ISSUE THREAD

**Issue by LukeZeller** [Azure/azure-sdk-for-python#32177]
- **Package Name**: azure-mgmt-cognitiveservices
- **Package Version**: 13.5.0
- **Operating System**: MacOS Ventura 13.5
- **Python Version**: 3.11.4

**Describe the bug**
The inferred type of `azure.mgmt.cognitiveservices.models.DeploymentProperties.rate_limits` is `None`, not `azure.mgmt.cognitiveservices.models.ThrottlingRule`.

**To Reproduce**
Code similar to the following, depending on environment:
```
azure_credentials = DefaultAzureCredential()
azure_client = CognitiveServicesManagementClient(
    credential=azure_credentials, 
    subscription_id=...,
)
deployment = azure_client.deployments.get(
    resource_group_name=...,
    account_name=...,
    deployment_name=...
)
rate_limits = deployment.properties.rate_limits # inferred type: None
```

**Expected behavior**
Expected type is `list[azure.mgmt.cognitiveservices.models.ThrottlingRule]`, as stated in the docstring for `DeploymentProperties`:
```
:ivar rate_limits:
:vartype rate_limits: list[~azure.mgmt.cognitiveservices.models.ThrottlingRule]
```

**Screenshots**

**Additional context**

**Comment by swathipil** [comment]
Hi @LukeZeller - Thanks for opening an issue! We'll take a look asap!

**Comment by SaurabhSharma-MSFT** [comment]
@LukeZeller I am not able to reproduce this.  I am getting ThrottlingRule object only.  Please find below the screenshot-
![image](https://github.com/Azure/azure-sdk-for-python/assets/38112130/86ff3d23-eba5-4dd8-b3ed-00698ac0810d)

**Comment by LukeZeller** [comment]
That looks like the actual object type at runtime? That's fine for me as well; I'm referring to the type inferred during static type-checking:
<img width="573" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/3392222/bf78c08e-2ec1-4ca7-8fad-b426f6e1b7e0">

It makes sense that the type inferred is `None`, as the variable is set to `None` in the constructor [here](https://github.com/Azure/azure-sdk-for-python/blob/66c2b8c5858f26eb80a40a672d568087897ccf5d/sdk/cognitiveservices/azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/_models_py3.py#L1734) and not given an explicit type hint; however the library declares itself PEP 561 compliant so I'd expect the static types to be correct.

**Comment by msyyc** [comment]
@ChenxiJiang333 Please help on this issue

**Comment by ChenxiJiang333** [comment]
got it, working on this now.

**Comment by ChenxiJiang333** [comment]
> Thanks for the reply! That looks like the actual object type at runtime - correct? That's fine for me as well; I'm referring to the type inferred during static type-checking: <img alt="image" width="573" src="https://private-user-images.githubusercontent.com/3392222/270139237-bf78c08e-2ec1-4ca7-8fad-b426f6e1b7e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzgwMDYsIm5iZiI6MTcwODkzNzcwNiwicGF0aCI6Ii8zMzkyMjIyLzI3MDEzOTIzNy1iZjc4YzA4ZS0yZWMxLTRjYTctOGZhZC1iNDI2ZjZlMWI3ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMDg1NTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFlMzI0MzBhNjFkZWMzYmMzMDgzNjRjZGY1MzJkMWE1NWQ0MzM1YTlmYmU4ODMyNTFkYzc3YWJmMDg2YzIxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PYPpf9QhT2Ra30qHHdG3mmaIDoKjqWGmLq7eK-tM6p4">
> 
> It makes sense that the type inferred is `None`, as the variable is set to `None` in the constructor [here](https://github.com/Azure/azure-sdk-for-python/blob/66c2b8c5858f26eb80a40a672d568087897ccf5d/sdk/cognitiveservices/azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/_models_py3.py#L1734) and not given an explicit type hint; however the library declares itself PEP 561 compliant so I'd expect the static types to be correct.

Hi, @LukeZeller I don't think `rate_limits` should have an inferred type as it's a read-only parameter. Its value is only returned by the service, and there's nothing to do on it from client side.
