### ISSUE TITLE
Volume creation issue after upgrading version of azure-mgmt-netapp package

### ISSUE THREAD

**Issue by noorjahansn94** [Azure/azure-sdk-for-python#32189]
- **Package Name**: azure-mgmt-netapp
- **Package Version**: 10.0.0
- **Operating System**:
- **Python Version**: 

**Describe the bug**
After updating it to version 10.0.0 , while creating an SMB volume, the following error occurs:
{'status': 'failure', 'volume': 'SFSN-WE1-noors02-936TF', 'message': '(InvalidInputUnixPermissionForNtfsSecurityStyleVolume) Unix permissions are not allowed for specified volume configuration, Create SMB or dual protocol volume with NTFS security style, without unix permissions.\\nCode: InvalidInputUnixPermissionForNtfsSecurityStyleVolume\\nMessage: Unix permissions are not allowed for specified volume configuration, Create SMB or dual protocol volume with NTFS security style, without unix permissions.'}

note: When creating NFS volume, it is working fine. And the version 4.0.0 is also working fine for SMB volume creation. but when upgraded to 10.0.0, it gets a default unix permission value. But for SMB volume creation, unix permission value should be none.

**To Reproduce**
1. upgrade the package azure-mgmt-netapp to version 10.0.0. Create a volume of SMB type.

**Expected behavior**
Volume creation success

**Screenshots**

**Additional context**

**Comment by swathipil** [comment]
Hi @noorjahansn94 - Thanks for opening an issue! We'll take a look asap!

**Comment by ChenxiJiang333** [comment]
Hi, @noorjahansn94. 
According to the definition layer https://github.com/Azure/azure-rest-api-specs/blob/main/specification/netapp/resource-manager/Microsoft.NetApp/stable/2022-09-01/netapp.json, unix permissions settings were rewritten in an octal 4-digit format property and would have a default value, so you need to manually set the value of property `unixPermissions` as `None` when creating the resouce.
