### ISSUE TITLE
Run certain tests from module for Travis

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-sdk-for-python#322]
Travis requires test runs are under 50 minutes currently and some of our tests take a while.  We need a way to run the fast tests on travis for build test runs.  

A way needs to be created that only a few, but varied, tests are run so we get decent coverage.

**Comment by zooba** [comment]
Have a look at the `@skip` decorators - you can make certain tests skip when an environment variable is (or is not) set.

**Comment by lmazuel** [comment]
I think this is the purpose of the `vcrpy` library used currently by @huguesv, which allows us to run full tests in Travis in 4minutes.
If I miss the point, tell me ;-)
