### ISSUE TITLE
What is `handle` parameter?

### ISSUE THREAD

**Issue by sigit-idn** [Azure/azure-sdk-for-python#32203]
I want to generate byte output and send to client side instead of play audio on server side in my flask backend.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04acfa1c-63c7-95d5-66b0-f48cc5654980
* Version Independent ID: c4931ce4-44ed-0c69-e138-ec44b5e9f741
* Content: [azure.cognitiveservices.speech.audio.AudioOutputStream class](https://learn.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.audio.audiooutputstream?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cognitiveservices-speech/azure.cognitiveservices.speech.audio.AudioOutputStream.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-cognitiveservices-speech/azure.cognitiveservices.speech.audio.AudioOutputStream.yml)
* Service: **cognitive-services**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kristapratico** [comment]
@sigit-idn apologize for the late reply, the speech SDK does not reside in this repo. Please move your issue to this repo: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues where the maintainers of the library will be able to help. Thanks!
