### ISSUE TITLE
Machine Learning Samples Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#32208]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_compute.py#L44)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/bbb78e83-1118-4e79-8fd6-42d4ebc35f63)

**Reason:**
Numbers cannot be the ending of the name if the previous character is a minus symbol (-).

**Suggestion:**
Update  code to

`f"ci-{randint(1, 1000)}-sample"`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_misc.py#L594),[link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_misc.py#L598),[link3](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_misc.py#L607),[link4](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_misc.py#L613),[link5](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_misc.py#L617),[link6](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_misc.py#L621),[link7](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/samples/ml_samples_misc.py#L627)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/19a445be-e226-4a0c-88ab-45d3e5fc80d8)

**Reason:**
Data version data-asset-name:2.0 (dataContainerName:version) not found. The name of the previously created `data_operation` is `data_asset_name`

**Suggestion:**
Update code to `data_asset_name`

@rohit-ganguly @lmazuel  @mayurid @diondrapeck for notification.

**Comment by diondrapeck** [comment]
I'll address this one
