### ISSUE TITLE
Cognitive Search Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#32207]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/search/azure-search-documents#authenticate-in-a-national-cloud)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/b0c4edfe-0da7-4c9b-b719-13d9c952d161)

**Reason:**
Misspelling

**Suggestion:**
Update code to `credential`

@rohit-ganguly @lmazuel @achandmsft @mayurid @xiangyan99 for notification.

**Comment by xiangyan99** [comment]
Fixed.
