### ISSUE TITLE
"'DefaultAzureCredential' object has no attribute 'signed_session'" encountered

### ISSUE THREAD

**Issue by jyggorath** [Azure/azure-sdk-for-python#32210]
- **Package Name**: azure-identity and azure-graphrbac
- **Package Version**:  1.14.0 (azure-identity) and 0.61.1 (azure-graphrbac)
- **Operating System**: Windows 11
- **Python Version**: 3.11.5

**Describe the bug**
Ref Laurent Mazuel's edit to this SO comment: https://stackoverflow.com/a/64129363 
I'm encountering an AttributeError exception with message "'DefaultAzureCredential' object has no attribute 'signed_session'" when attempting to create a GraphRbacManagementClient object using a DefaultAzureCredential from the azure.identity package. Appearently this is not supposed to happen.

**To Reproduce**
My code:
```
from os import getenv
from azure.identity import DefaultAzureCredential
from azure.graphrbac import GraphRbacManagementClient

graph_client = GraphRbacManagementClient(credentials=DefaultAzureCredential(), tenant_id=getenv('aad_tenant_id'))
user = graph_client.users.get('[obviously redacted, used my own UPN in our AAD tenant]')

```

**Expected behavior**
Not 100% sure, currently just in the experimantal phase and not exactly drowning in documentation for this SDK. But not expecting it to raise an exception.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Unfortunately, azure-graphrbac is a track 1 library which does not work well with azure-identity.

Did you have a chance to look at https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md?

**Comment by storebrand-mats** [comment]
@xiangyan99 no I did not, thanks!

I also was not aware that azure-graphrbac was known to not work with azure-identity. Is this something that is on the backlog somewhere, or is azure-graphrbac facing deprecation at some point in the future?

**Comment by xiangyan99** [comment]
@storebrand-mats unfortunately this is the decision needs to be made by the graph team. I don't have an answer either. :(

**Comment by jyggorath** [comment]
I ended up implement user fetching with the Graph API instead, thanks for explaining the deal with azure-graphrbac 😁
