### ISSUE TITLE
azure-mgmt-recoveryservicesbackup - installed multiple times but shows error 

### ISSUE THREAD

**Issue by sloharadmin** [Azure/azure-sdk-for-python#32228]
- **azure-mgmt-recoveryservicesbackup**: 
- **>azure-mgmt-recoveryservicesbackup) (2.25.1)**: 
- **Operating System**: Ubuntu 22
- **Python Version**:   python3.10 --version
Python 3.10.12 ansible [core 2.15.4]

**Describe the bug**
TASK [Creating resource group] ******************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.recoveryservicesbackup.models'
fatal: [localhost]: FAILED! => {
    "changed": false

**To Reproduce**
1. I am unable to install this module, tried on Ubuntu, package is already there but it shows error while running the playbook.

**Expected behavior**
Ansible playbook should run without showing this module not found error.

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share more details like how to repro it?

It is not quite clear to me:

"I am unable to install this module, tried on Ubuntu, package is already there"
