### ISSUE TITLE
No way to authenticate to custom docker registry for cluster runs

### ISSUE THREAD

**Issue by microsoft-sampsa** [Azure/azure-sdk-for-python#32231]
There seems to be no way to authenticate to a custom docker registry and to pull a custom image from there (in the old v1 API there was something like this).

In the arguments:
```
command(*, name: str | None = None, description: str | None = None, tags: Dict | None = None, properties: Dict | None = None, 
display_name: str | None = None, command: str | None = None, experiment_name: str | None = None, environment: str | Environment | 
None = None, environment_variables: Dict | None = None, distribution: Dict | MpiDistribution | TensorFlowDistribution | 
PyTorchDistribution | RayDistribution | None = None, compute: str | None = None, inputs: Dict | None = None, outputs: Dict | None = 
None, instance_count: int | None = None, instance_type: str | None = None, locations: List[str] | None = None, docker_args: str | None = 
None, shm_size: str | None = None, timeout: int | None = None, code: PathLike | str | None = None, identity: 
ManagedIdentityConfiguration | AmlTokenConfiguration | UserIdentityConfiguration | None = None, is_deterministic: bool = True, 
services: Dict[str, JobService | JupyterLabJobService | SshJobService | TensorBoardJobService | VsCodeJobService] | None = None, 
job_tier: str | None = None, priority: str | None = None, **kwargs) -> Command
```
.. there may be many potential objects where the docker username and passwd could be inserted..?  (I'd like to use a service principal id and secret).  Along these lines:

```
identity=ManagedIdentityConfiguration(how-to-put-docker-registry-username-and-password-in-here?)
environment=Environment(image=docker-image-uri, how-to-put-docker-registry-username-and-password-in-here?)
...
```

**How to tell the cluster run to authenticate correctly to a custom azure docker registry so that it can pull an image from there?**

Otherwise I'll just have to make my azure docker registry public and assume that it is microsoft's policy for all their developers :)

Related: https://stackoverflow.com/questions/77178034/using-custom-container-registy-in-azure-ml-api-v2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39bcc254-72ac-e4e4-013e-70e0391b56b7
* Version Independent ID: 56ceaec5-170d-a444-09ac-180c1034f498
* Content: [azure.ai.ml.entities.Command class](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.command?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.Command.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.Command.yml)
* Service: **machine-learning**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by banibrata** [comment]
This is not supported today from SDK v2, did you try managed identity wayof doing it : https://learn.microsoft.com/en-us/azure/machine-learning/how-to-identity-based-service-authentication?view=azureml-api-2&tabs=python#build-azure-machine-learning-managed-environment-into-base-image-from-private-acr-for-training-or-inference

**Comment by ZhiliangWu** [comment]
> This is not supported today from SDK v2, did you try managed identity wayof doing it : https://learn.microsoft.com/en-us/azure/machine-learning/how-to-identity-based-service-authentication?view=azureml-api-2&tabs=python#build-azure-machine-learning-managed-environment-into-base-image-from-private-acr-for-training-or-inference

@banibrata I tried it out, and it seems to be working with the following file

```yaml
name: ws_connection
type: container_registry
target: <url_of_container_registry>
credentials:
  type: username_password
  username: ***
  password: ***
```

The type `username_password` was guessed from the error message I got when I put wrong variables names such as `PatTokenConfiguration`. Are they any dedicated docs to describe how this `yaml` file should be configured?
