### ISSUE TITLE
Azure Monitor opentelemetry exporter uses deprecated locale.getdefaultlocale

### ISSUE THREAD

**Issue by jenshnielsen** [Azure/azure-sdk-for-python#32232]
- **Package Name**:  azure-monitor-opentelemetry-exporter
- **Package Version**:  1.0.0.b17
- **Operating System**: windows 11
- **Python Version**:  python 3.11

**Describe the bug**
Using Azure Monitor Opentelemetry exporter triggers a deprecation warning

  C:\Users\jenielse\Miniconda3\envs\myenv\Lib\site-packages\azure\monitor\opentelemetry\exporter\_utils.py:57: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead
    "ai.device.locale": locale.getdefaultlocale()[0],

**To Reproduce**
1. Configure export with azure monitor opentelemetry exporter.

Or any other opteration that triggers an import of _utils.py from the package

**Expected behavior**

No deprecation warning.

**Additional context**

Afaik this only became deprecated in python 3.11 

Note however that on windows the replacement has some issues https://github.com/python/cpython/issues/82986

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by jenshnielsen** [comment]
@pamelafox Yes I actually reported that one over here https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1970 (this issue was fixed in opentelemetry sdk/api a few months ago but not in contrib/instrumentation yet

**Comment by lzchen** [comment]
@jenshnielsen 

Interesting that you are seeing the warning messages. DeprecationWarnings should be ignored for code that is not directly executed from [main](https://docs.python.org/3/library/warnings.html#warning-categories) but this will definitely come up possibly in CI runs.

Regardless, it seems that `getdefaultlocale()` will be removed in [py3.13](https://docs.python.org/3/library/locale.html#locale.getdefaultlocale) so we might want to switch over before that happens to avoid breaking code. The [windows issue](https://github.com/python/cpython/issues/82986) with `getlocale() is a bit concerning so we might be better off simply just to ignore deprecation warnings before py3.13 comes out. Thoughts?

**Comment by pamelafox** [comment]
I don't know about @jenshnielsen but I use pytest to test our app code, and pytest defaults to showing warnings like the deprecation warnings, so they add a lot of noise to pytest output. We can filter them out but it's always nicer when code is upgraded, where it makes sense.

**Comment by jenshnielsen** [comment]
I indeed noticed it via our test suite and pytest too.

**Comment by lzchen** [comment]
@pamelafox 

There's a [pr](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1973) in upstream opentelemetry that will fix [this issue](https://github.com/Azure/azure-sdk-for-python/issues/32232#issuecomment-1739239915)
