### ISSUE TITLE
Feature Request: Implement group owner operations in graphrbac

### ISSUE THREAD

**Issue by todd-davenport** [Azure/azure-sdk-for-python#3225]
It would be very useful to have group management operations from Microsoft Graph implemented in the Azure SDK for Python. Currently you can perform CRUD operations on [Azure AD groups with the Python SDK](https://github.com/Azure/azure-sdk-for-python/blob/dev/azure-graphrbac/azure/graphrbac/operations/groups_operations.py)  but you cannot manage the Owners of groups.

Can the following be implemented?
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_post_owners
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/group_list_owners
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_delete_owners

**Comment by lmazuel** [comment]
Good point, thanks for bringing this :)

**Comment by lmazuel** [comment]
Would unlock https://github.com/Azure/azure-cli/issues/6799

**Comment by jhendrixMSFT** [comment]
Opened https://github.com/Azure/azure-rest-api-specs/issues/3790 to track updating the swagger.

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
