### ISSUE TITLE
Update Azure Monitor Ingestion authZ scope

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-python#32278]
For context, see https://github.com/Azure/azure-sdk-for-net/issues/38998.

**Comment by pvaneck** [comment]
Currently, a user can pass in a custom credential scope using the `credential_scopes` kwarg on the client (added in https://github.com/Azure/azure-sdk-for-python/pull/30739)

I'll add a note/example in the README about configuring the clients for non-public clouds. The query package already has something [similar](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-query#configure-clients-for-non-public-azure-clouds).
