### ISSUE TITLE
Move credential and header policies after retry policy for async client 

### ISSUE THREAD

**Issue by mnogolik** [Azure/azure-sdk-for-python#32312]
- **Package Name**:  azure-storage-blob 
- **Package Version**:  12.18.2
- **Operating System**: Linux
- **Python Version**: 3.11

**Describe the bug**
PR https://github.com/Azure/azure-sdk-for-python/pull/14629   has fixed the issue when during retrial header gets expired.  This has been fixed for sync client only and still not fixed in async https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client_async.py

**To Reproduce**

**Expected behavior**
It should be fixed in async client too 

**Screenshots**
not needed 

**Additional context**

**Comment by YalinLi0312** [comment]
@mnogolik Thanks for contacting us, we'll take a look ASAP!

**Comment by weirongw23-msft** [comment]
Hi @mnogolik Peter, we have already merged in the pull request #37616 with the changes and released new versions of the Storage SDK containing the fix. 

We're closing the Github issue now. Thank you!
