### ISSUE TITLE
azure-monitor-opentelemetry-exporter will support pure fileConfig/dictConfig configurability?

### ISSUE THREAD

**Issue by jesinity** [Azure/azure-sdk-for-python#32322]
@lzchen 

As OpenCensus is sunsetting and we are preparing to move to OpenTelemetry implementation, I wonder if new implementation makes it possibile to  move all logging configuration and setup to fileConfig (or dictConfig):

With the current OpenCensus library I can for example move everything to configuration file:

```
import logging
import logging.config

my_logging_conf = "/my/logging.config"
logging.config.fileConfig(my_logging_conf)

```

with a config such as:

```
[loggers]
keys=root

[handlers]
keys=opencensus_handler

[formatters]
keys=basic_formatter

[logger_root]
level=INFO
handlers=opencensus_handler

[handler_opencensus_handler]
class=opencensus.ext.azure.log_exporter.AzureLogHandler
level=INFO
formatter=message_formatter

[formatter_basic_formatter]
format=[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s
datefmt=
style=%
validate=True
class=logging.Formatter

```

I wonder if also the new library will enable such scenario or will I have to write something programmatic at app bootstrap as specified in the examples like:

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_log.py

Thank

**Comment by lzchen** [comment]
The opentelemetry based solution uses the Python logging library the exact same way as opencensus does. Have you tried it out and are experiencing issues?

**Comment by jesinity** [comment]
yes I see that the ```LoggingHandler``` can be added through configuration, but we still need to configure somewhere the exporter:

```
trace.set_tracer_provider(TracerProvider())
tracer = trace.get_tracer(__name__)
set_logger_provider(LoggerProvider())

exporter = AzureMonitorLogExporter.from_connection_string(
    os.environ["APPLICATIONINSIGHTS_CONNECTION_STRING"]
)
get_logger_provider().add_log_record_processor(BatchLogRecordProcessor(exporter))
```

as now the role of logging and exporting are somewhat separated responsibilities.

Could also the exporting functionality something that could be somewhat moved to logging configuration as well (at handler creation time for example) or should be configure the exporter at application startup?

**Comment by lzchen** [comment]
@jesinity 

Ahh yes I see what you mean now. In OpenTelemetry you must setup the exporter pipeline separately from logging configuration if you are using the exporter package directly. If you want a more "one-stop-shop" kind of experience in which you want to call one api to setup the exporter pipeline for you, take a look at the [opentelemetry distro](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry). You can call `configure_azure_monitor` in one line and then use that along side your logging configuration. Here is the [getting started](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=python) page.
