### ISSUE TITLE
Azure Data factory Pipelines, created using git version control reposatory(Azure DevOps Git), are not fetched by azure-mgmt-datafactory library

### ISSUE THREAD

**Issue by regarhariram** [Azure/azure-sdk-for-python#32321]
- **Package Name**: **azure-mgmt-datafactory**
- **Package Version**: 3.1.0
- **Operating System**: LINUX
- **Python Version**: 3.8.10

**Describe the bug**
Azure Data factory Pipelines, created using git version control repository (**Azure DevOps Git**), are not fetched by azure-mgmt-datafactory library.

following function to fetch list of all the azure data factory pipelines  is showing blank list of pipeline in the response even if there are so many pipelines there:
-----------------------------------------------------------------
**def get_data_factory_pipelines():
    client = DataFactoryManagementClient(
        credential=credential,
        subscription_id=subscription_id,
    )

    response = client.pipelines.list_by_factory(
        resource_group_name=resource_group_name,
        factory_name=data_factory_name,
    )
    for pipeline in response:
        print(pipeline)
    return response**
--------------------------------------------------------------------------
Other functions are not working as well for pipeline with the source of Azure DevOps Git repository.
Kindly help me to fix the issue ASAP.

Thanks

**Comment by ChenxiJiang333** [comment]
Hi, @regarhariram 
Could you find your pipelines under the tab "Pipelines" as expected in the Azure Data Factory Studio?
If so, please make sure you have published all these changes.
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/d92c0716-9ad7-44df-961a-ad8e4e77879c)

**Comment by regarhariram** [comment]
Yes,  we find all the pipelines under the tab "Pipelines" as expected in the Azure Data Factory Studio. Now, can we fetch all the pipelines data without publishing it on data factory directly from Azure DevOps Git?

**Comment by ChenxiJiang333** [comment]
@regarhariram 
Afraid not. There are only api and sdk methods that allow you to get the resources stored in the factory, which you can see from live mode.
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/7668fa5e-503e-47a2-ae4d-cf20aaab6119)
You can try to  follow https://learn.microsoft.com/en-us/azure/data-factory/continuous-integration-delivery-improvements#create-an-azure-pipeline to config auto publishing, or open an issue in https://github.com/Azure/azure-rest-api-specs/issues to request this feature.
