### ISSUE TITLE
Issue with returning Float columns in azure file system query acceleration

### ISSUE THREAD

**Issue by FnayouSeif** [Azure/azure-sdk-for-python#32324]
- **azure-storage-file-datalake**: 
- **12.9.0b1**: 
- **Ubuntu 20.04**:
- **3.8.10**: 

**Describe the bug**
The query acceleration method to query a parquet file behaves strangely when choosing a float column

**To Reproduce**

```
import json
from azure.storage.filedatalake import DataLakeServiceClient, DelimitedJsonDialect ,QuickQueryDialect
import pandas as pd


datalake_service_client = DataLakeServiceClient.from_connection_string(<REDACTED>)
path = "YOUR_DIR/test.parquet"
file_client = datalake_service_client.get_file_client(CONTAINER_NAME,path)

df = pd.DataFrame([{"col_string":"Ok","col_float":109.56,"col_int":2}, {"col_string":"Ok","col_float":9.2656,"col_int":4}])

parquet_binary = df.to_parquet()
file_client.upload_data(parquet_binary ,overwrite=True)

x = file_client.query_file(query_expression="SELECT col_float FROM DataLakeStorage"
                           , file_format=QuickQueryDialect.PARQUET
                           , output_format=DelimitedJsonDialect(delimiter="|")
                          )
for i in x.records():
    print(i)
``` 

Now when the query selects col_float explicitly, it returns this incomplete faulty row: 
query:  `"SELECT col_float FROM DataLakeStorage"` 
```>>>b'{"col_float":'``` 
and it stops there. 

Another example 
query: `"SELECT col_string, col_int, col_float FROM DataLakeStorage"` 
returns incomplete records
```>>> b'{"col_string":"Ok","col_int":2,"col_float":' ``` 

when the query becomes : `"SELECT * FROM DataLakeStorage"` 
the output is correct: 
``` 
>>> b'{"col_string":"Ok","col_float":109.56,"col_int":2}'
>>> b'{"col_string":"Ok","col_float":9.265599999999999,"col_int":4}'
>>> b''
``` 

if you choose string and int columns:  `"SELECT col_string, col_int FROM DataLakeStorage"` 
the output is also correct: 
```
b'{"col_string":"Ok","col_int":2}'
b'{"col_string":"Ok","col_int":4}'
b''
``` 

**Expected behavior**
Return the float value columns when selected explicitly in the Select Expression.

**Comment by YalinLi0312** [comment]
Hi @FnayouSeif - Thanks for the feedback, we'll investigate ASAP.

**Comment by vincenttran-msft** [comment]
Hi @FnayouSeif , thank you for the inquiry. I will forward this to the query acceleration team who will be able to better assist us with this issue!

**Comment by vincenttran-msft** [comment]
Hi @FnayouSeif, after reaching out to the query acceleration team, they have confirmed the bug reproduces on their end. They have opened a bug report internally to track the work to correct this issue, but currently parquet support is in public preview stage and there are no near-term plans to bring it to GA. With that being said, I cannot give you a great estimate of when this item will be resolved, but I will be sure to update you when I am made aware of any fixes.

Thanks!

**Comment by FnayouSeif** [comment]
@vincenttran-msft 
Thanks. This should be mentioned somewhere I guess to prevent any developer from working on this and losing time without knowing. 

The only pages referencing query acceleration are not well documented in regards to accepted input formats and their relative GA status.
https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-query-acceleration-how-to?tabs=azure-powershell
https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-query-acceleration

**Comment by vincenttran-msft** [comment]
Hi @FnayouSeif , sorry for the delay. I have just attached a pull-request which addresses your concerns and will hopefully steer any developers from needlessly chasing down a bug on a preview feature. Thank you for your contribution and patience!

**Comment by CollardOlivier** [comment]
Hi,

Just to add that the problem also reproduces with BlobClient query_file:
SELECT float_column FROM BlobStorage
fails, but 
SELECT * FROM BlobStorage
properly returns all columns including floats.

Happy to try workarounds if any.

Thanks!
