### ISSUE TITLE
Cannot Train Models with a Custom Job Environment (in Azure ML)

### ISSUE THREAD

**Issue by sraza-onshape** [Azure/azure-sdk-for-python#32323]
- **Package Name**: `azureml-core` (I think)
- **Package Version**: `1.51.0.post1`
- **Operating System**: Ubuntu - on an Azure Machine Learning compute instance, type `STANDARD_DS11_V2`
- **Python Version**: 3.10

**Describe the bug**
I am trying to run the OOTB notebook, `train-model.ipynb`, that comes pre-loaded on Azure ML VMs. It involves the following cell of code, when configuring the command used to execute a training job on our Azure ML compute cluster:

```python
from azure.ai.ml.entities import Environment

custom_env_name = "aml-scikit-learn"

custom_job_env = Environment(
    name=custom_env_name,
    description="Custom environment for Credit Card Defaults job",
    tags={"scikit-learn": "0.24.2"},
    conda_file=os.path.join(dependencies_dir, "conda.yaml"),
    image="mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest",
)
custom_job_env = ml_client.environments.create_or_update(custom_job_env)

print(
    f"Environment with name {custom_job_env.name} is registered to workspace, the environment version is {custom_job_env.version}"
)
```
However, later when this `custom_job_env` is used to configure the training job command, it leads to an error in the Azure ML web UI for the job. It is reported as the following:

```
"Failed to pull Docker image cadsearchdev.azurecr.io/azureml/azureml_3355d46209fc74a4517af345fc918282. This error may occur because the compute could not authenticate with the Docker registry to pull the image. If using ACR please ensure the ACR has Admin user enabled or a Managed Identity with `AcrPull` access to the ACR is assigned to the compute. If the ACR Admin user's password was changed recently it may be necessary to synchronize the workspace keys."
```

**To Reproduce**
1. Create a workspace in Azure ML
2. Create a CPU instance
3. Start the CPU instance 
4. Run the code in the `~/get-started-notebooks/train-model.ipynb` notebook (the web version can be found [here](https://learn.microsoft.com/en-us/azure/machine-learning/tutorial-train-model?view=azureml-api-2&source=recommendations)) - go down until the code cell with the heading, **"View job output and wait for job completion"**.
5. Use the link outputted by the code cell that invokes the training job, to go to the web UI for Azure ML - then watch for the job to fail.

**Expected behavior**
The job should not fail with a custom job environment. 

**Screenshots**
N/A

**Additional context**
This could be more of a question than an issue - but why does the error message mention ACR? To the best of my knowledge, we are not using ACR to create the custom job environment (as stated in the code snippet ^above), since the Docker image is being pulled from MCR.

**Comment by vizhur** [comment]
Environment creates a derived images using the base image and conda dependencies you specified. Derived image is materialized in the ACR associated with your workspace. BTW,  ubuntu18.04 is deprecated but that is not the cause of the issue.

**Comment by sraza-onshape** [comment]
> Environment creates a derived images using the base image and conda dependencies you specified. Derived image is materialized in the ACR associated with your workspace. BTW, ubuntu18.04 is deprecated but that is not the cause of the issue.

Ok, so I can definitely see the ACR registry that got created to store the derived image for my `Environment` @vizhur. I suppose the next question is RE: the second part of the error message: 

```
...If using ACR please ensure the ACR has Admin user enabled or a Managed Identity with `AcrPull` access to the ACR is assigned to the compute. If the ACR Admin user's password was changed recently it may be necessary to synchronize the workspace keys."
```

Since the ACR was created by Azure ML, where would I go to make my user an admin?

**Comment by sraza-onshape** [comment]
closing this for now, @vizhur followed up over email and gave a solution (I don't know if the solution is confidential, if you want me to share feel free to reopen this). Thanks team and Happy New Year!
