### ISSUE TITLE
BlobClient (and maybe others?) links open SDK docs in wrong version

### ISSUE THREAD

**Issue by ericthomas1** [Azure/azure-sdk-for-python#32349]
Hello,

When I click the `BlobClient` link under the [`Clients` section](https://learn.microsoft.com/en-us/python/api/overview/azure/storage-blob-readme?view=azure-python#clients), the Azure SDK for Python website opens up...but it opens up to a very old version of the package (`12.0` whereas the current version is `12.18`).

![image](https://github.com/Azure/azure-sdk-for-python/assets/42788729/6f97ea05-451e-42b2-b41a-48656f51fb26)

Now that I know, its cool, I can just make the change the version. But those who don't know, are referring versions of the SDK. 

This stumped me for a while. I was like "I could have swore this method was implmented...". 

How this helps someone!

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8ec2272-9f68-4c9a-1372-61434035ba21
* Version Independent ID: 50dc1d72-d6c0-0edd-1b9c-884440075694
* Content: [Azure Storage Blobs client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/storage-blob-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/storage-blob-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/storage-blob-readme.md)
* Service: **storage**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by xiangyan99** [comment]
Thanks for reporting the issue. We have updated the link.
