### ISSUE TITLE
Support for using acquired refresh token as an auth method to support GDAP

### ISSUE THREAD

**Issue by jameskirsop** [Azure/azure-sdk-for-python#32352]
**Is your feature request related to a problem? Please describe.**

We use the Partner Center API to acquire a Refresh Token which we then use in our multi-tenant application. We are happy to manually refresh token ourselves, but there is no currently supported way (that I can see) of providing a Refresh Token as a parameter to one of the Authentication functions to gain an access token.

A sample of a working auth flow and MS Graph API call using the Requests library:
```
url = "https://login.microsoftonline.com/{CUSTOMER_TENANT_ID}/oauth2/v2.0/token"
        payload = f'grant_type=refresh_token&client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&refresh_token={RERESH_TOKEN}&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default'
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
auth_response = requests.request("POST", url, headers=headers, data=payload)

first_group = requests.get('https://graph.microsoft.com/beta/groups?$top=1', headers = {"Authorization": f"Bearer {auth_response.json()['access_token']}"} )
```

We can't present our end-users an Interactive Authentication Request to get a new refresh token themselves because:
- This would be a terrible UX; and more importantly
- They don't have access to the user credentials for the Azure AD Service Account that provides delegated access into our customer tenants (this flow is [documented here](https://tminus365.com/my-automations-break-with-gdap-the-fix/)). This is why we need to manually refresh the token as an administrative function and then store it for our app to auth.

**Describe the solution you'd like**
An extension of the ClientSecretCredential function to allow for providing a Refresh Token as an optional parameter so that it can be used alongside the Client ID and Client Secret to get an Access Token (and then to use the credential to authenticate against Graph using `msgraph.core.GraphClient`)

Example code flow:
```
graph_credentials = ClientSecretCredential(
    client_id = CLIENT_ID,
    client_secret = CLIENT_SECRET,
    tenant_id = CUSTOMER_TENANT_ID,
    refresh_token = REFRESH_TOKEN,
)

client = GraphClient(
    credential=graph_credentials,
    api_version = APIVersion.beta if beta else APIVersion.v1,
    scope=['Organization.Read.All','User.Read.All','Directory.Read.All']
)
```

**Describe alternatives you've considered**
I haven't been able to come up with one apart from replacing the entire `GraphClient` with `requests` and authenticating for every single API hit (which would kill performance).

**Additional context**
ClientSecretCredential was historically working fine until GDAP was switched on. It no longer works for the reasons outlined in the [aforementioned article](https://tminus365.com/my-automations-break-with-gdap-the-fix/).

**Comment by xiangyan99** [comment]
Thanks for reaching out. We will take a look.

**Comment by xiangyan99** [comment]
Thanks for the suggestions. Unfortunately, the graph sdk does not support azure-identity library.
