### ISSUE TITLE
SecretClient.get_secret() takes a long time to finish

### ISSUE THREAD

**Issue by abertasi** [Azure/azure-sdk-for-python#32354]
- **Package Name**: azure-keyvault-secrets
- **Package Version**: 4.7.0
- **Operating System**: Windows 10 Enterprise
- **Python Version**: 3.10.9

**Describe the bug**
Retrieving secret using the SecretClient.get_secret() takes a long time - around 20-35 seconds. The Azure key vault logging confirms there are no response time delays from their side. Location: Western Europe.

**To Reproduce**
1. Run the following code:
```
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

credential = DefaultAzureCredential(
    exclude_environment_credential=True,
    exclude_managed_identity_credential=True,
    exclude_shared_token_cache_credential=True,
    exclude_visual_studio_code_credential=True,
)
client = SecretClient(vault_url=key_vault, credential=credential)
key = client.get_secret(secret_name)
```

**Expected behavior**
The waiting time for `key = client.get_secret(secret_name)` to take no more than a second.

**Comment by xiangyan99** [comment]
Thanks for reporting the issue.

`key = client.get_secret(secret_name)` includes several operations.

One is to get the access token. The other is to get the secret.

Could you help to add some tracing information that can help narrow down which step takes long time?

**Comment by abertasi** [comment]
Hi @xiangyan99, I am not entirely sure how to achieve this. How do I profile the get_secret() method in-line?

**Comment by xiangyan99** [comment]
There are a few ways you can profile an app. 

e.g. cProfile.

Or if you can access the source code, you can print timestamps to collect the information.

**Comment by abertasi** [comment]
Hi, while investigating I found the root of the issue - the hit times were much higher than initially though. The actual connection time takes a bit less than a second.

Thank you very much for your help!
