### ISSUE TITLE
Importing azure-devops on Python 3.12 can break other azure packages due to missing import

### ISSUE THREAD

**Issue by remyjette** [Azure/azure-sdk-for-python#32365]
- **Package Name**: all when also used with azure-devops
- **Package Version**: any
- **Operating System**: Windows 11
- **Python Version**: Python 3.12

**Describe the bug**
The azure-devops has a `azure/__init__.py` that does an `import pkg_resources` despite not declaring a dependency on setuptools.
If this is installed, *all* `import azure` breaks, even other packages, unless setuptools is also installed independently.

I reported the issue in https://github.com/microsoft/azure-devops-python-api/issues/470 but since that repository doesn't have much activity and the issue is impacting the use of other azure packages I wanted to also post it here.

**To Reproduce**
1. Install Python 3.12.
2. Create a venv. On one of my machines it broke even on the main install, but it will definitely break in a venv thanks to https://github.com/python/cpython/issues/95299
3. Install azure-devops along with any other azure-sdk-for-python package
4. Try to import

**Expected behavior**
Import should succeed

**Screenshots**
```
>>> import azure.cosmosdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rejett\Documents\src\env\Lib\site-packages\azure\__init__.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Additional context**
This might be related to azure-devops still using the legacy 'setup.py install' method https://github.com/microsoft/azure-devops-python-api/issues/441

**Comment by YalinLi0312** [comment]
Hi @remyjette , `azure-devops-python-api` is the right place to report this issue. I see you logged an issue in that repo in May and got response on the same day, you can wait for updates there again.

**Comment by tonybaloney** [comment]
Fix in https://github.com/microsoft/azure-devops-python-api/pull/469

**Comment by xiangyan99** [comment]
Closing. Please use https://github.com/microsoft/azure-devops-python-api/pull/469 to track the issue.
