### ISSUE TITLE
azure.mgmt.datafactory sdk output for pipelines is working for activities but not for data flow activity.

### ISSUE THREAD

**Issue by AmareswarapuBhavani** [Azure/azure-sdk-for-python#32382]
- **azure.mgmt.datafactory**: 
- **3.1.0**: 
- **Windows 11**:
- **3.10.9**: 

**Describe the bug**
I tried to extract Json of dataflow activity using azure.mgmt.datafactory sdk but the JSON output is not referencing the dataflow as per my [SO thread](https://stackoverflow.com/questions/77110265/issues-with-serialization-of-pipeline-json-from-azure-sdk-for-python/77141908#77141908) answer.

**To Reproduce**
When I tried to get the JSON of a pipeline that has a data flow activity using the code below:

```
from azure.identity import DefaultAzureCredential
from azure.mgmt.datafactory import DataFactoryManagementClient
import json

client = DataFactoryManagementClient(
    credential=DefaultAzureCredential(),
    subscription_id="<subscriptionId>"
)

response = client.pipelines.get(
    resource_group_name="<resourceGroupName>",
    factory_name="<ADFName>",
    pipeline_name='<pipeline>'
)

# Convert the response to JSON
pipeline_json = response.serialize()

# Print the JSON representation of the pipeline
print(json.dumps(pipeline_json, indent=4))

```

I got the JSON as shown below:

![enter image description here](https://i.imgur.com/YU41kzT.png)

It is in the same format that you got, but when I tried with the execute pipeline activity, I was able to get the type properties as mentioned below:

![enter image description here](https://i.imgur.com/fVbWrgD.png)

It is working for all activities, but it is not working only for the data flow activity. This might be a bug.

**Comment by annatisch** [comment]
Thanks for the report @AmareswarapuBhavani 
I'm a bit confused by the question - the two different JSON outputs above look accurate for the two different Activity types - all of the subtypes of `ExecutionActivity` will have a different structure of `typeProperties`.

Are there additional properties of the `"ExecuteDataFlow"` type that you would expect to see here?
If so then it might either mean that the specification we use to generate these response models is incorrectly describing the service behaviour. Or perhaps that the service is not returning the information.
If you could provide some more details as to what is missing from the `ExecuteDataFlowActivity` we can hopefully help to track down the cause.
