### ISSUE TITLE
Monitor metric calculation pipeline failing with custom preprocessing component

### ISSUE THREAD

**Issue by adfi** [Azure/azure-sdk-for-python#32427]
- **Package Name**: azure-ml-ai
- **Package Version**: 1.11.0
- **Operating System**: Ubuntu
- **Python Version**: 3.10

**Describe the bug**
I am trying to get a Monitor up and running for the case where I have my own production data. I have followed all the [instructions](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-monitor-model-performance?view=azureml-api-2&tabs=python#set-up-model-monitoring-by-bringing-your-own-production-data-to-azure-machine-learning) and comply with the prerequisites. 
When running the python code from the instructions the monitor is created just fine. However when executing the pipeline for the metric calculation the Preprocessing Component fails with the following error:
_Failed to submit job due to Exception: Response status code does not indicate success: 400 (Must specify ComputeType in the request when submit job to Global Job Dispatcher.).
Must specify ComputeType in the request when submit job to Global Job Dispatcher.._

The other components in the pipeline all have the serverless spark compute assigned to it but the Custom Preprocessing component does not.

**To Reproduce**
1. Create a custom preprocessing component
2. Follow the [instructions](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-monitor-model-performance?view=azureml-api-2&tabs=python#set-up-model-monitoring-by-bringing-your-own-production-data-to-azure-machine-learning) to create a monitor
3. Manually trigger the pipeline to calculate the metrics

**Expected behavior**
I expected the pipeline to complete successfully.

**Comment by annatisch** [comment]
Thanks for the report @adfi!
I have looped in the ML team to take a look :)

**Comment by anaarmas-sys0** [comment]
Here the issue

**Comment by anaarmas-sys** [comment]
Hi again!! Any suggestion until now?

**Comment by ahughes-msft** [comment]
Hello @adfi, 

For creating the custom preprocessing component to preprocess your data, please see the examples here: https://github.com/Azure/azureml-examples/tree/main/cli/monitoring/components/custom_preprocessing

I would like to understand more about the challenges your are experiencing here and the format of the data you are attempting to preprocess. If you could please share a contact email I will reach out to you to schedule a call. 

Many thanks,
Alex

**Comment by anaarmas-sys0** [comment]
Hello Alex!

For sure!, my email is ***@***.***
In the meantime I'm going to check the example in the link.

Thank you!

**Comment by anaarmas-sys** [comment]
Hello Alex!
The example in the link solved the problem about the _ComputeType_ requested. Thank you so much!

**Comment by adfi** [comment]
The matter isn't relevant for me anymore. As @anaarmas-sys reports it to be resolved, we can close the issue.
