### ISSUE TITLE
[Doc] Add sphinx in CI validation, and make it fail for ERROR

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#32435]
The title says everything, it helps getting the downstream doc better

cc @scbedd , while I feel confident I can touch the Python script that runs Sphinx, I will need your support to actually put in in the right YAML in the right Analyze spot.

**Comment by scbedd** [comment]
You completed this with the addition of `strict_sphinx` tox env. Closing.
