### ISSUE TITLE
[Doc] Add a pyproject.toml flag for treating WARNING as ERROR in Sphinx

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#32434]
As we want to make an effort to improve our doc, we should have a flag to force Sphinx to consider WARNING as ERROR. Sphinx itself does have that flag as simply `-W`, so it's quite easy to do.

**Comment by kristapratico** [comment]
This was completed awhile ago, flag is called `strict_sphinx` and can be set to true in a package's pyproject.toml
