### ISSUE TITLE
Job list with parent_job_name limit to show 50 jobs

### ISSUE THREAD

**Issue by yufang67** [Azure/azure-sdk-for-python#32440]
i would like to show the children jobs from one pipeline job. When specifying parent_job_name, only 50 jobs are shown with add top=100.

jb_it = ml_client.jobs.list(parent_job_name="job_name", top=100) shows the first 100 children jobs.

i also opened a PR: https://github.com/Azure/azure-sdk-for-python/pull/32443

Thanks,

**Comment by annatisch** [comment]
Thanks for your contribution @yufang67!
Looping in the ML team to help take a look :)

**Comment by nemanjarajic** [comment]
Fix to issue has been included for the upcoming February release since January release has been cancelled and December release has been postponed.
