### ISSUE TITLE
Impossible to retrieve data from cognitive search by exluding keywords

### ISSUE THREAD

**Issue by ivanvaccarics** [Azure/azure-sdk-for-python#32459]
- **Package Name**: azure-search-documents
- **Package Version**: 11.4.0b6
- **Operating System**: Windows
- **Python Version**:  3.10

**Describe the bug**
I'm trying to perform a hybrid search (vector + text) on cognitive search with the aim of excluding some keywords from the search. The text to search for is the following: "renewable energies" -"h2o".
The data I want to receive from cognitive search are related to the words "renewable energies" but excluding where "h2o" is mentioned. I set the searchMode to "all" to cover all constraints at once but using the python library it also returns candidates with "h2o" in their text. By executing the same query from the portal (text only and without vectors) the results presented to me are correct. How can I implement this solution via the library?

**To Reproduce**
I tried all the combinantion between query_type and search_mode and also all combination between search by text, vector or hybrid. Tested also with the use_sematioc_captions

**Expected behavior**

**Screenshots**

**Additional context**
Portal query: "renewable energies" -"h2o"&$filter= search.ismatch('4289*', 'category', 'full', 'all')&searchMode=all&queryType=semantic

Python code:
```
query_text = "renewable energies" -"h2o"
filter= search.ismatch('4289*', 'category', 'full', 'all')
query_vector = [0.015146714635193348, -0.017691470682621002, -0.0020151627250015736, -0.0007525135879404843, -0.007498909719288349, 0.008940487168729305, -0.014266878366470337, -0.036303386092185974, -0.015999479219317436, -0.026327399536967278, 0.022131258621811867, 0.037142615765333176, 0.003006670158356428, -0.0022046659141778946, ...]
r = self.search_client.search(query_text, 
                                        filter=filter,
                                        query_type=QueryType.SEMANTIC, 
                                        query_language="en-us", 
                                        query_speller="lexicon", 
                                        semantic_configuration_name="default", 
                                        top=3, 
                                        query_caption="extractive|highlight-false" if use_semantic_captions else None,
                                        vector=query_vector, 
                                        top_k=50 if query_vector else None,
                                        vector_fields="embedding" if query_vector else None,
                                        search_mode=SearchMode.ALL
                                      )
```

**Comment by ivanvaccarics** [comment]
> Steps to reproduce the behavior:
I tried all the combinantion between query_type and search_mode and also all combination between search by text, vector or hybrid. Tested also with the use_sematioc_captions

**Comment by annatisch** [comment]
Thanks for reaching out @ivanvaccarics 
@xiangyan99 - are you able to provide some guidance here?

**Comment by xiangyan99** [comment]
Please open a ticket for search service for the feature request.
