### ISSUE TITLE
azure.mgmt.billing > invoices.list_by_billing_account does not work for EA Customers

### ISSUE THREAD

**Issue by Git-BT-Hub** [Azure/azure-sdk-for-python#32457]
- **Package Name**:  azure.mgmt.billing
- **Package Version**:  latest
- **Operating System**: 
- **Python Version**:  3.7+

Package:  azure.mgmt.billing
def main():
    client = BillingManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id="SUBSCRIPTION_ID",
    )

    response = client.invoices.list_by_billing_account(
        billing_account_name="{billingAccountName}",
        period_start_date="2018-01-01",
        period_end_date="2018-06-30",
    )
    for item in response:
        print(item)

This does not seems to work as expected for Customers with Enterprise Agreement Accounts, where the billing_account_name and billing_account_id is the same thing

Error : (BadRequest) Invalid billing account name.

I am sending Enrollment Account number in [ billing_account_name="{billingAccountName}"]

The REST API works with Billing Account ID / Enrollment Account number >
GET https://management.azure.com/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/invoices?api-version=2019-10-01-preview&periodStartDate={periodStartDate}&periodEndDate={periodEndDate}

Please can you fix this or let me know which version will work as per REST API 

Thanks

**Comment by annatisch** [comment]
Thanks for the report @Git-BT-Hub!
@msyyc, could please help take a look to determine if this issue is in our SDK or the swagger spec?

**Comment by msyyc** [comment]
@ChenxiJiang333 Please help on this issue.

**Comment by ChenxiJiang333** [comment]
Hi @Git-BT-Hub
SDK method is used to call the api as well and this error was raised by the service. Since the api version `2019-10-01-preview` works with REST API, it might also work with sdk methods.
You could try to use sdk methods to call api in that version by updating your code on creating the client like:
```
client = BillingManagementClient(
    credential=DefaultAzureCredential(),
    subscription_id=SUBSCRIPTION_ID,
    api_version="2019-10-01-preview"
)
```

**Comment by Git-BT-Hub** [comment]
Hi @ChenxiJiang333 - Thanks for your help, adding api_version="2019-10-01-preview" still does not work 
Also this issue is not limited to "client.invoices.list_by_billing_account" , there are others which result in same error 
Please  see below screenshot , let me know if you need more details

Thanks

![image](https://github.com/Azure/azure-sdk-for-python/assets/47550225/fbb9ece6-c10b-45b6-a6bc-1353dd44a2b6)

**Comment by ChenxiJiang333** [comment]
Hi @Git-BT-Hub 
Please follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to get the detailed log and see whether the Request URL in the log is expected.
