### ISSUE TITLE
WAM sign in should default to the currently signed in windows account, if no account is already in cache

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-python#32460]
Example here: https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/desktop-mobile/wam

**Comment by scottaddie** [comment]
Per Ray Luo in the 2/1 MSAL sync, the calling pattern in Python is `acquire_token_interactive(..., prompt="none")`.
