### ISSUE TITLE
Typos in doc /doc/dev/tests.md

### ISSUE THREAD

**Issue by dargilco** [Azure/azure-sdk-for-python#32489]
First typo:

- This page: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/tests.md#tox
- shows: (env) > pip install tox<5
- What is the "<5"? I think it's a typo and should be removed.

Second typo:

- This page: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/tests.md#environment-prerequisites
- Shows: "Git version > 2.30.0 is to on the machine and in the path"
- I think it was meant to say "installed on the machine" instead of "is to on the machine"

**Comment by shubhusion** [comment]
@dargilco kindly assign this issue to me.

**Comment by dargilco** [comment]
@shubhusion done! thanks.

**Comment by shubhusion** [comment]
@dargilco i have made a PR for this.

**Comment by dargilco** [comment]
Thank you @shubhusion!
