### ISSUE TITLE
ContainerApps - list job executions filter usage

### ISSUE THREAD

**Issue by peppePE** [Azure/azure-sdk-for-python#32486]
- **Package Name**: azure.mgmt.appcontainers
- **Package Version**: 3.0.0
- **Operating System**: Windows 10
- **Python Version**: 3.10

**Describe the question**
I'm trying to retrieve only failed container apps job's executions but I can't understand how the filter string should work nor I found any documentation that describes the behavior. What is the correct way to use the filter string?

There is another way to filter the retrieved executions?

**To Reproduce**
1. client = ContainerAppsAPIClient(credential=DefaultAzureCredential(exclude_shared_token_cache_credential=True),                                subscription_id="XXXXXXX")
2. client.jobs_executions.list(resource_group_name="XXXXXX", job_name="XXXXX", filter="status=Failed")
3. exception: 
> azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Internal Server Error'
Content: {"error":{"code":"InternalServerError","message":"Internal server error occurred. correlation ID: 15a04c35-1fe7-424a-a308-4a14c790a185","details":null,"target":null,"additionalInfo":null}}

**Expected behavior**
A clear description of what the format of the filter string is expected to be or a more descriptive error.

**Comment by pvaneck** [comment]
Hey, sorry that you are having issues filtering. I'm not familiar with the service or what precisely is the expected format, but if it's like other services, it might expect the OData expression syntax. (Example documentation for search: https://learn.microsoft.com/en-us/azure/search/search-query-odata-filter). @msyyc can correct me if I am wrong.

In any case, azure-mgmt-appcontainers could still benefit from improved docstrings for the `filter` param and/or some samples demonstrating using it.

**Comment by peppePE** [comment]
Hi @pvaneck, thanks for the suggestion. I did some try but it seems that is not working

I'll try something else in the next days 😄 thanks anyway

**Comment by peppePE** [comment]
Hi @ChenxiJiang333
it was one of my first attempts but I got always a 500 Internal Server Error, tried again a few minutes ago but nothing changed

**Comment by ChenxiJiang333** [comment]
Turn to service team for support https://github.com/Azure/azure-rest-api-specs/issues/26257.

**Comment by xiangyan99** [comment]
Closing and please use https://github.com/Azure/azure-rest-api-specs/issues/26257 to track the issue.
