### ISSUE TITLE
Span attribute that is a list is exported to AI as string

### ISSUE THREAD

**Issue by macieyng** [Azure/azure-sdk-for-python#32483]
- **Package Name**: azure-monitor-opentelemetry
- **Package Version**: 1.0.0
- **Operating System**: macos
- **Python Version**: 3.11.2

**Describe the bug**
Span attribute that is a list is exported to AI as string or exported data is interpreted by AI as string.

**To Reproduce**
1. Use this example
```python
from azure.monitor.opentelemetry import configure_azure_monitor
from opentelemetry import trace
import logging

configure_azure_monitor()

logger = logging.getLogger(__name__)

tracer = trace.get_tracer(__name__)

with tracer.start_as_current_span("hello") as span:
    span.set_attribute("list_attr", ["attr1", "attr2"])
    logger.warning("Hello, World!", extra={"list_attr": ["attr1", "attr2"]})
    print("Hello, World!")

input()

```
2. Go to Application Insights
3. Span attributes and logger extra that used to be a list are now a string that looks like tuple.

**Expected behavior**
If I pass a list of simple types they should 
- appear in the AI as separate searchable values.
    ie. 
    what is now `customDimensions {"list_attr":"('attr1', 'attr2')"}`
    should be `customDimensions {"list_attr": ["attr1", "attr2"]}`
- be searchable in the transaction search filters by single value
- order of items should have no matter
    ie.
    span attr `span.set_attribute("list_attr", ["attr1", "attr2"])`
    should be the same as `span.set_attribute("list_attr", ["attr2", "attr1"])` 
    meaning that both are collections of identical items

**Screenshots**
<img width="523" alt="Zrzut ekranu 2023-10-13 o 14 08 14" src="https://github.com/Azure/azure-sdk-for-python/assets/82878433/b1611416-5cff-4cd6-8332-af8f9fe06150">

<img width="501" alt="Zrzut ekranu 2023-10-13 o 14 08 36" src="https://github.com/Azure/azure-sdk-for-python/assets/82878433/1edd305d-d070-4099-9be4-0d92cc09f9c6">

<img width="996" alt="Zrzut ekranu 2023-10-13 o 14 11 09" src="https://github.com/Azure/azure-sdk-for-python/assets/82878433/ad72b2b9-ada2-461b-b968-ba3f5e768b30">

<img width="492" alt="Zrzut ekranu 2023-10-13 o 14 17 42" src="https://github.com/Azure/azure-sdk-for-python/assets/82878433/a2fe4d17-435a-49ff-9ae4-2f0d75e3bf55">

**Additional context**
I do understand that there is a limitation for objects nested deeper - have no issue with it, but if we are allowed to pass a list of things (simple types) we should be able to retrieve it as such.

**Comment by lzchen** [comment]
@macieyng 

Values in `customDimensions` in AppInsights are represented by strings so we must do string conversion even if the attribute value is a list.
