### ISSUE TITLE
Add custom exporter support for all pillars

### ISSUE THREAD

**Issue by jeremydvoss** [Azure/azure-sdk-for-python#32498]
Migrated from https://github.com/microsoft/ApplicationInsights-Python/issues/283
Enable console exporting and such via env vars. While we still won't be able to allow custom metrics readers, this is close.

**Comment by lzchen** [comment]
Enabled through env vars:

https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry#usage
