### ISSUE TITLE
semantic_query missing from search_client in 11.4.0b11 azure-search-documents SDK

### ISSUE THREAD

**Issue by claremonahan** [Azure/azure-sdk-for-python#32526]
- **Package Name**: azure-search-documents
- **Package Version**: 11.4.0b11
- **Operating System**: windows
- **Python Version**: 3.11

**Describe the bug**
AzureSearch SDK should include support for the semantic_query model. https://github.com/Azure/azure-sdk-for-python/blob/671c865a8350f1c987afd0ffd9356f58610fdb15/sdk/search/azure-search-documents/azure/search/documents/_generated/models/_models_py3.py#L1044

However, the SDK throws an exception when semantic_query is passed to the search client. It appears that the search_client model is missing the semantic_query parameter: https://github.com/Azure/azure-sdk-for-python/blob/671c865a8350f1c987afd0ffd9356f58610fdb15/sdk/search/azure-search-documents/azure/search/documents/_search_client.py

**To Reproduce**

## search index
results = search_client.search(
    search_text = QUERY,
    query_type = QueryType.SEMANTIC,
    query_language=QUERY_LANGUAGE,
    semantic_query = "new york apartments?",
    query_caption= "extractive|highlight-true" if USE_CAPTIONS else None,
    query_answer= "extractive|count-3" if USE_ANSWERS else None,
    semantic_error_handling="partial",
    semantic_max_wait_in_milliseconds="780")
    
-->    Exception has occurred: TypeError
request() got an unexpected keyword argument 'semantic_query'

**Expected behavior**
Request should succeed. API directly to client confirms behavior succeeds

**Screenshots**

**Additional context**

**Comment by catalinaperalta** [comment]
Thanks for reaching out @claremonahan ! We'll investigate and get back to you asap
