### ISSUE TITLE
Docs are not correctly referencing types, type annotations are not cross-checked with docs

### ISSUE THREAD

**Issue by temporaer** [Azure/azure-sdk-for-python#32535]
This concerns docs for azure-ai-ml:

https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.azureblobdatastore?view=azure-python

The link for the `credential` parameter type(s) has been broken since at least March 2023:

![image](https://github.com/Azure/azure-sdk-for-python/assets/27792/2b99fa1c-feb7-474b-9b83-213310dfafda)

The reason is likely that the type annotation does not match the manually maintained type in the docs:

![image](https://github.com/Azure/azure-sdk-for-python/assets/27792/ee715b0b-3116-4fb0-a5d9-9d762d73ddab)

This is an error that should be caught by sphinx.  Since it is not, it seem that *warnings are being ignored during docs build*.

Arguably, *types should read from the python type annotations by sphinx*, there are plugins which are capable of doing this, instead of manually maintaining them and risking divergence.

**Comment by catalinaperalta** [comment]
Thanks for reaching out @temporaer! Adding @azureml-github team to help address this issue

**Comment by diondrapeck** [comment]
Thanks for pointing this out. I'll figure out how to improve our infrastructure to catch these issues.

**Comment by diondrapeck** [comment]
We're in the process of adding strict-sphinx check to the repo which should catch this going forward.
