### ISSUE TITLE
Role in Python SDK is None, but is sectionHeader in the RestAPI

### ISSUE THREAD

**Issue by jaceaser** [Azure/azure-sdk-for-python#32549]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.3.1
- **Operating System**: Windows
- **Python Version**: 3.9

**Describe the bug**
Using the document here https://portal.unifiedpatents.com/patents/patent/US-7551599-B2 when using the form recognizer studio it will return ABSTRACT in a paragraph with a role sectionHeader, however using the Python SDK it returns it as none.

**To Reproduce**
1. Use  azure_document_analyzer_instance.begin_analyze_document(
                "prebuilt-layout", document=f, locale="en-US"
            ) where document is the patent, observe the output to see that the paragraph with ABSTRACT only has role type none.

**Expected behavior**
role type should be sectionHeader

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment]
Hi @jaceaser , what's the service api version you are using in sdk and in studio?
