### ISSUE TITLE
Support other cloud providers as input when creating blobs

### ISSUE THREAD

**Issue by DhruvDuseja** [Azure/azure-sdk-for-python#32557]
**Is your feature request related to a problem? Please describe.**
I've been struggling to find a way to transfer data from other cloud providers (AWS, GCP, Alibaba) to my Azure container DIRECTLY FROM THE URL. It is not always feasible to download and reupload data to the Azure container.
I am aware of AzCopy and the functionality (using the [Put Block From URL](https://learn.microsoft.com/en-us/rest/api/storageservices/put-block-from-url?tabs=azure-ad) method) it provides but I'd appreciate if there was a way for this to be done in Python.

**Describe the solution you'd like**
I would like functionality similar to AzCopy to be able to copy data to Azure directly from a URL using Python.
There is a `upload_blob_from_url` method in the azure storage SDK for Python but from the [doc](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-upload-blob-from-url) it looks like it only supports transfer from other Azure blobs.

Is there any way this can be done using an Amazon S3 URL? Also, it would be great if it could be as fast as AzCopy!

**Describe alternatives you've considered**
I have considered calling AzCopy using `subprocess` from a Python script but this isn't the cleanest approach.

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by vincenttran-msft** [comment]
Hi @DhruvDuseja Dhruv, thank you for your inquiry. From my own testing I was able to successfully use the `upload_blob_from_url` with a non-Azure Storage URL. However, I do not readily have access to test this with specifically an Amazon S3 URL, so please give that a try and let me know that doesn't work for you!

With that being said, another option is to try `start_copy_from_url`. I believe that something similar to the sample linked [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_copy_blob.py) may achieve what you are looking for using the `start_copy_from_url` API. 

Please note that by default this operation is completed asynchronously, and its status can be checked by polling the copy status using `get_blob_properties`. You can also set copies to be synchronous (by setting parameter `requires_sync=True`), however this is limited to a file size limit of 256MB.

Hopefully one of the above recommendations can help unblock your workflow, and please let me know if you have any other concerns.

Thanks!

**Comment by DhruvDuseja** [comment]
Thank you for the quick reply @vincenttran-msft! So I tried this out with my S3 URL and that worked fine.

I do have one more point of concern. It looks like AzCopy supports copying over a "directory" using the `--recursive` option, however, using `upload_blob_from_url` & `start_copy_from_url` seem to only copy files over and not directories. Can you please let me know if I've missed something here or whether this isn't currently supported?

Thanks!

**Comment by jalauzon-msft** [comment]
Hi @DhruvDuseja, unfortunately we do not support that functionality (copying entire directories) in Python today. You would have to do that manually. Currently we offer AzCopy for that functionality or we are working on creating a library with this functionality in C#/.NET [Azure.Storage.DataMovement.Blobs](https://www.nuget.org/packages/Azure.Storage.DataMovement.Blobs/12.0.0-beta.3) which is in beta right now.

Unfortunately, no plans to bring this functionality to Python at this time.

**Comment by DhruvDuseja** [comment]
Got it @jalauzon-msft. Thanks a lot for the help and prompt replies, it is greatly appreciated!
