### ISSUE TITLE
Not able to append data using 'file_client.append_data'

### ISSUE THREAD

**Issue by abhi7878** [Azure/azure-sdk-for-python#32559]
- **Package Name**: azure/storage/filedatalake
- **Package Version**: 12.8.0 
- **Operating System**: Linux
- **Python Version**:  3.6.15 

**Describe the bug**
'append_data' is not appending data to the file in the container.
return :'etag': None, 

**To Reproduce**
1.  Container has Only read permission

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by abhi7878** [comment]
Got the issue -
the container does not have read permission and hence was not able to get file size using 'file_client.get_file_properties()'
Since was not providing the existing file size in 'file_client.flush_data()',  Data was not getting uploaded.
