### ISSUE TITLE
Additional troubleshooting suggestion for the Azure Monitor Ingestion client library

### ISSUE THREAD

**Issue by robertparker9** [Azure/azure-sdk-for-python#32562]
**Is your feature request related to a problem? Please describe.**
The log ingestion API can return 204 but no log entry is created. One possible cause for this is that the json body parameter is not an array.

**Describe the solution you'd like**
The "[Troubleshooting missing logs](https://github.com/Azure/azure-sdk-for-python/blob/azure-monitor-ingestion_1.0.2/sdk/monitor/azure-monitor-ingestion/TROUBLESHOOTING.md#troubleshooting-missing-logs)" section needs updating to say only a json array works (it currently says "data should be in the form of a JSON _object_ or array") 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by catalinaperalta** [comment]
Thanks for reaching out @robertparker9 ! Looping in @pvaneck to take a look

**Comment by pvaneck** [comment]
Thanks for the feedback @robertparker9. You are right as that text is misleading. I went ahead and created a PR to update the text, and add a check to the `upload` method to verify the type for `logs`: https://github.com/Azure/azure-sdk-for-python/pull/32591
