### ISSUE TITLE
accept request files data in tuple format

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#32566]
For multipart/form-data in azure-core, we restrict the types passed in a request's
files to a certain format in this function: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/utils/_pipeline_transport_rest_shared.py#L336

In cases where I want to, for example, send my files as bytes with a filename, this is not possible today:

`HttpRequest(files={"file": (filename, file, "application/octet-stream")})`

requests, aiohttp, and httpx all support the information: filename, data, and content-type. This is a feature request to be able to accept the format above as valid.

**Comment by lmazuel** [comment]
We will accept the three syntaxes:
- bytes like obj
- (filename, bytes like obj)
- (filename, bytes like obj, content-type)
