### ISSUE TITLE
CosmosDB Trigger > retrieve documents directly

### ISSUE THREAD

**Issue by mirkomancin** [Azure/azure-sdk-for-python#3258]
It would be very useful to have directly Document(s) that trigger python function like in C# or js. If I try to retrieve the document with a subsequent query, I'm not sure if I give me the exact document.

**Comment by lmazuel** [comment]
My feeling is that your question belongs on the DocDB repo?
https://github.com/Azure/azure-documentdb-python

If not, could you describe a little more, since I'm not able to understand what code you are talking about :(
Thank you,

**Comment by mirkomancin** [comment]
Probably I have not explained well. The problem is when I create a function on Azure in python and I want to trigger it with cosmosDB (when a document is loaded or edited). The trigger arrives correctly, but unlike javascript or c#, I am not returned the document (s) that triggered the event. I can not query the DB after the event because I would risk not having the exact document (s).

**Comment by lmazuel** [comment]
Ok, didn't understand you're talking about Azure Function. @asavaritayal ? Thoughts?

**Comment by lmazuel** [comment]
Closing this issue as non-SDK issue. If the design doesn't still allow in current Azure Function to do this scenario properly, please do a feedback on the Azure Function service on the Azure Portal.
