### ISSUE TITLE
Cannot see images created using Azure Portal via list_os_images()

### ISSUE THREAD

**Issue by peterinfra** [Azure/azure-sdk-for-python#326]
Steps:
1. Create Linux VM using Azure web portal
2. Run sudo waagent -deprovision 
3. Shutdown vm
4. Capture role (using Azure web portal)
5. Verify if the image is present in Virtual Machine->Images
6. Use python sdk
  sms = ServiceManagementService('account-id','path to pem file')
  images = [i for i in sms.list_os_images() if i.category=='User']
  for i in images: print i.name

I dont see the captured VM image in the list. However, I can see it via the xplat-cli.
Also I can only see images which dont have the Source field populated.

**Comment by prashanthmadi** [comment]
Hi,

I have one image in my account which i created last week and above method gives me the result as below. It may not be problem with SDK.

If you see the last line of result. It has mine
mycentos|||---|||----User


for osimage in result:
        print len(result);
        print osimage.name+"|||"+osimage.publisher_name+"---|||----"+osimage.category;

489
........
ad072bd3082149369c449ba5832401ae__Windows-Server-Remote-Desktop-Session-Host-on-Windows-Server-2012-R2-20140403-2126|||Microsoft Windows Server Remote Desktop Group---|||----Public

9b7cfe55da0349d5a8316a8cc4741f87__Internal-StorSimple-VirtualAppliance-1100-20141230|||Microsoft Hybrid Cloud Storage Group---|||----Public

9b7cfe55da0349d5a8316a8cc4741f87__Internal-StorSimple-VirtualAppliance-1100-201412312|||Microsoft Hybrid Cloud Storage Group---|||----Public

mycentos|||---|||----User


Check if there is something you are missing while creating it in portal

**Comment by prashanthmadi** [comment]
Try creating a new virtual machine from gallery and check if the image you have created is listed in portal.

It would be visible in the first step "Choose an Image". Click on MY Images in left nav and you should see that image

**Comment by huguesv** [comment]
Try `list_vm_images` instead, what you are getting out of a capture on the portal is most likely a vm image, not an os image.  That's pretty confusing, but vm images is a newer concept that replaces os images.  os images were restricted to a single disk, where vm images can be multiple disks.

**Comment by huguesv** [comment]
Please reopen if you still need help.
