### ISSUE TITLE
aka.ms/pysdkmodels link broken/TODO

### ISSUE THREAD

**Issue by akx** [Azure/azure-sdk-for-python#3261]
Hi!

The link https://aka.ms/pysdkmodels referred to in the https://github.com/Azure/azure-sdk-for-python/blob/4a76ec8443613f0ed3add530f9896d77eabd899d/azure-mgmt-compute/azure/mgmt/compute/models.py#L13-L14 deprecation warning is broken.

Or, I mean, it points to https://github.com/Azure/azure-sdk-for-python/wiki/Direct-access-to-%22models%22-is-deprecated which is rather barren.

**Comment by lmazuel** [comment]
Hi @akx 
Ok, that's on me :/. I postponed, and postponed and then forgot.... Put it back on my TODO. Sorry about that.

**Comment by boumenot** [comment]
Friendly bump.  I was excited to read how to fix this.

I just followed the link today, and found that it was a TODO.

**Comment by lmazuel** [comment]
@boumenot @akx I wrote the article, please let me know what you think before I close the issue :)
Thank you!

**Comment by akx** [comment]
Thank you :)

Wouldn't Solution 3 be to import the model from the package for the particular API version, for e.g. code completion or `typing`?

**Comment by akx** [comment]
Check. Well, I'll pinky swear I'll keep those imports only within `if typing.TYPE_CHECKING:` blocks. Is that fine? :D
