### ISSUE TITLE
App Configuration Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#32678]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/appconfiguration/azure-appconfiguration/README.md#create-a-configuration-setting)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/a765027c-e589-4af5-86c2-f6b833309421)

**Reason:**
Wrong parameter.

**Suggestion:**
Update code  to `added_config_setting`

2.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/appconfiguration/azure-appconfiguration/README.md#get-a-configuration-setting)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/57593de2-3ec1-4830-bee8-fe83fb133f46)

**Reason:**
missing parameter.

**Suggestion:**
Update code  to `key="MyKey", label="MyLabel"`

@rohit-ganguly @lmazuel @sandeep-sen @jsquire @albertofori  for notification.

**Comment by YalinLi0312** [comment]
@jerryshia The second issue is not correct, the parameter `label` is optional in this operation:
https://github.com/Azure/azure-sdk-for-python/blob/98a4da6497bee981c84226ef5b1173109c383f7d/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py#L229-L236

**Comment by jerryshia** [comment]
@YalinLi0312 Yes,the parameter label is optional in this operation. But considering that the method of create the `ConfigurationSetting` in the previous section used `label` as a parameter,we believe that the method of get the `ConfigurationSetting` requires `label` as a parameter, otherwise an error will be reported.
![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/7d8e0200-c2b6-4e5a-b3ec-96dd45c187af)
