### ISSUE TITLE
Service Bus Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#32676]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/README.md#send-and-receive-a-message-from-a-session-enabled-queue)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/0efd6113-6868-4643-a0a6-dc34de610f94)

**Reason:**
Environment variable error

**Suggestion:**
Update code to
`SERVICE_BUS_SESSION_QUEUE_NAME`

@rohit-ganguly  @lmazuel  @ronniegeraghty  @JoshLove-msft  @annatisch for notification.

**Comment by shubhusion** [comment]
Kindly assign this to me i will do the PR asap.

**Comment by swathipil** [comment]
Hi @jerryshia - We have a PR open to fix this and will merge it by EOD. Thanks!

Hi @shubhusion - We have the PR out for this one already, thanks! If you're interested in contributing to the repo, please take a look at [issues tagged with good-first-issue](https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) in our repo. 🙂
