### ISSUE TITLE
Cognitive Search Sample Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#32677]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_vector_search.py#L58), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_vector_search.py#L77)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/b3ca1df6-0159-40d7-90dd-0f3b6b00aeae)
![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/d6428b52-b00e-4961-9726-f8bc51ef188e)

**Reason:**
The field 'descriptionVector' uses a vector search algorithm configuration '' which is not defined.

**Suggestion:**
1.Add `VectorSearchProfile` to this code ,update  to

```
from azure.search.documents.indexes.models import (
        SearchIndex,
        SearchField,
        SearchFieldDataType,
        SimpleField,
        SearchableField,
        VectorSearch,
        VectorSearchProfile,
        HnswVectorSearchAlgorithmConfiguration,
    )
```

2.Add `profiles=[VectorSearchProfile(name="my-vector-config", algorithm="my-algorithms-config")]`  to this code ,update  to

```
vector_search = VectorSearch(
        profiles=[VectorSearchProfile(name="my-vector-config", algorithm="my-algorithms-config")],
        algorithms=[HnswVectorSearchAlgorithmConfiguration(name="my-algorithms-config", kind="hnsw")]
    )
```

@rohit-ganguly  @lmazuel  @achandmsft  @mayurid @xiangyan99  for notification.

**Comment by xiangyan99** [comment]
#32561

**Comment by xiangyan99** [comment]
Fixed.

**Comment by jerryshia** [comment]
@xiangyan99  [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_vector_search.py#L87) The parameters of this function still have errors. The parameter `name` of `HnswAlgorithmConfiguration` must match `algorithm_ configuration_ name` consistent. So please update `HnswAlgorithmConfiguration(name="my-vector-config") ` to `HnswAlgorithmConfiguration(name="my-algorithms-config")`

**Comment by dfauland** [comment]
> @xiangyan99 [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_vector_search.py#L87) The parameters of this function still have errors. The parameter `name` of `HnswAlgorithmConfiguration` must match `algorithm_ configuration_ name` consistent. So please update `HnswAlgorithmConfiguration(name="my-vector-config") ` to `HnswAlgorithmConfiguration(name="my-algorithms-config")`

Thank you! This finally fixed it. Struggled for almost 2 days to finally create the index properly.
Please update your documentation/samples: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_vector_search.py

**Comment by JeffSchedin** [comment]
@xiangyan99 This sample is still not updated. 

Also this line is bad 
embedding = client.embeddings.create(input=[text], model="text-embedding-ada-002")

I had to change it to embedding = client.embeddings.create(input=text, model=deployment_id)  where deployment id is the name of the deployment in Azure AI  and not the model name. 

SDK seems to have constant issues between the OpenAI and Azure changes,  makes adoption difficult,

**Comment by xiangyan99** [comment]
Fixed.
