### ISSUE TITLE
azure-monitor-ingestion: add input type check for logs

### ISSUE THREAD

**Issue by adalli13** [Azure/azure-sdk-for-python#32681]
**Is your feature request related to a problem? Please describe.**
I have been troubleshooting why my logs do not arrive in my destination in LogAnalytics Workspace, even though there was no error. At the end, my error was that my input for the logs argument in `LogIngestionClient.upload()` was a dict instead of a list.

**Describe the solution you'd like**
It would be nice to raise an error if the logs input has a wrong type.

**Alternative solution**
Alternatively, it could also be a solution to allow a dictionary and a list as input for `logs`.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by pvaneck** [comment]
Hey, @adalli13. Nice timing. This was actually just added not too long ago: https://github.com/Azure/azure-sdk-for-python/pull/32591. A new release will be cut early November.

As a side note, the service team for Azure Monitor has been working on adding DCR diagnostic logs for logging error messages when a malformed payload is received. This will also be visible to the user. This feature is currently in private preview, but will likely GA by the end of the year.

Hopefully, both these changes will improve the user experience.
