### ISSUE TITLE
Docs updates

### ISSUE THREAD

**Issue by wtrombly** [Azure/azure-sdk-for-python#32683]
**Is your feature request related to a problem? Please describe.**
Much of the documentation needs to be updated. This is not limited to but an example of improper documentation.

https://learn.microsoft.com/en-us/python/api/overview/azure/monitor-opentelemetry-exporter-readme?view=azure-python-preview

The examples in trace documentation are incorrect. Much of the functions that are being suggested don't exist and have been renamed.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by andife** [comment]
Isn't there a way that we can have this automatically checked through the CI pipeline for the most updated version of the package? This could then be the occasion to get to know what no longer works?

**Comment by lzchen** [comment]
@wtrombly 

Where are you accessing that link from? It could be an outdated location. The official microsoft docs for the exporter are located [here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=python)

**Comment by lzchen** [comment]
@wtrombly 

> The examples in trace documentation are incorrect. Much of the functions that are being suggested don't exist and have been renamed.

Could you provide specific examples of where the documentation is incorrect? I don't seem to see which parts you are referring to as all the components listed seem to still be working.

**Comment by wtrombly** [comment]
Thank you for your reply
