### ISSUE TITLE
AML jobs create new containers in an arbitrary blob storage account to save the code snapshots

### ISSUE THREAD

**Issue by louisflorentin** [Azure/azure-sdk-for-python#32680]
- **azure.ai.ml**: 1.11.0
- **Python Version**: 3.10.11

**Describe the bug**
AML jobs create new containers in a blob storage account to save the code snapshots. This blob storage account contains the container that gets mounted in all these AML jobs. Each time the code changes it created new containers that need to be deleted manually later.

**To Reproduce**
1. Submit an AML job that mounts a container from a blob storage account
2. Once the job is submitted it will create a new container in this blob storage that contain the code snapshot

**Expected behavior**
Code snapshots shouldn't be saved in an arbitrary location, in new containers belonging to a storage account that is mounted for a different purpose than storing code snapshots.

**Screenshots**
New containers that get saved in our blob storage account:
![image](https://github.com/Azure/azure-sdk-for-python/assets/64954736/f7876479-4459-44e9-913a-e20d58e1f7c5)

**Comment by diondrapeck** [comment]
Hi @louisflorentin - this is intended behavior. If the artifacts for snapshots are not referenced by any AzureML service within 24 hours of creation, they'll be garbage collected; otherwise, they will remain.

**Comment by Marmarello** [comment]
Hi, @diondrapeck, thank you for your reply!

I can't help but notice that SDK v2 used to save snapshots at: 
https://{redacted}.blob.core.windows.net/azureml-blobstore-{redacted}/LocalUpload/snapshot_id/tracked-files
Which is a very logical thing to do.

But when it is saved at:
https://{redacted}.blob.core.windows.net/snapshot_id/tracked-files
The storage account becomes difficult to navigate due to the clutter created by numerous snapshot containers.
It feels inconsistent with the way other types of assets are stored.

Is there a reason why creating a new container for every snapshot is beneficial over storing them in one location?
Why was it chosen over the first approach?

If it is indeed intended, can they be saved in a different storage account?

**Comment by diondrapeck** [comment]
Hi @Marmarello - thank you for the feedback. We changed from that original snapshot design to allow more RBAC for workspace storage usage. We will continue to be open-minded and receptive to feedback, so thank you for your thoughts and proposals.

**Comment by thomasfrederikhoeck** [comment]
Hi @diondrapeck . We are also facing this issue/intended behaviour. Could clarify what `referenced` mean is this context?

> If the artifacts for snapshots are not referenced by any AzureML service within 24 hours of creation, they'll be garbage collected; otherwise, they will remain.

Is there a way to specify a seperate storage account for these snapshots? Then they at least won't pollute the strucutre of `https://{redacted}.blob.core.windows.net/`

**Comment by diondrapeck** [comment]
> Hi @diondrapeck . We are also facing this issue/intended behaviour. Could clarify what `referenced` mean is this context?
> 
> > If the artifacts for snapshots are not referenced by any AzureML service within 24 hours of creation, they'll be garbage collected; otherwise, they will remain.
> 
> Is there a way to specify a seperate storage account for these snapshots? Then they at least won't pollute the strucutre of `https://{redacted}.blob.core.windows.net/`
> 
> It also looks like others where caught a little by suprise: https://learn.microsoft.com/en-us/answers/questions/1379985/how-to-prevent-that-a-new-blob-storage-container-i
> 
> Is this change documented anywhere?

@thomasfrederikhoeck 

- Referenced means called within a subsequent job. Code snapshots can be reused, so if the same exact directory is used as a code reference for a new job within that time period, it will persist.
- There is currently no way to specify a separate storage account for them.
- Thank you for linking to that forum. Yes, we've received feedback from users that the new design is not ideal and "polluting" aesthetically. The change wasn't originally documented as it wasn't considered a major customer-facing change; however, I have created [a PR](https://github.com/Azure/azure-sdk-for-python/pull/34332) to retroactively update the 1.7.0 CHANGELOG to make this clear.

Reiterating what I said above to Marmello, we really appreciate the feedback and are looking to see how we can move forward in a way that maintains the RBAC benefits of the change while addressing UX concerns.

**Comment by thomasfrederikhoeck** [comment]
@diondrapeck thank you for the reply. I think a good "middelway" would be a seperate Storage Account for code snapshots then but eager to see what you come up with.
