### ISSUE TITLE
[FormRecognizer] Formula object data type is incorrect

### ISSUE THREAD

**Issue by toothache** [Azure/azure-sdk-for-python#32728]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**:  3.3.1
- **Operating System**: Windows
- **Python Version**: 3.8.5

**Describe the bug**
According to the [documentation](https://learn.microsoft.com/en-us/python/api/azure-ai-formrecognizer/azure.ai.formrecognizer.documentpage?view=azure-python#azure-ai-formrecognizer-documentpage-formulas), the formula object should be type `DocumentFormula` instead of `DocumentBarcode`.

**To Reproduce**
```:python
    with open(path_to_sample_documents, "rb") as f:
        poller = document_analysis_client.begin_analyze_document(
            "prebuilt-layout", document=f, features=[AnalysisFeature.FORMULAS]
        )
    result = poller.result()
    print(type(result.pages[0].formulas[0]))
```
**Expected behavior**
The type should be `DocumentFormula` instead of `DocumentBarcode`.

**Screenshots**
![sceenshot](https://github.com/Azure/azure-sdk-for-python/assets/2187096/c9bf4d82-85e7-4fa5-9327-0e36cc0712de)

**Additional context**

**Comment by YalinLi0312** [comment]
Hi @toothache , thanks for your contribution! We'll prepare a release for it in next month.
