### ISSUE TITLE
Issue in Setting CMK encryption to azure net app volume

### ISSUE THREAD

**Issue by noorjahans** [Azure/azure-sdk-for-python#32730]
Package Name: azure-mgmt-netapp
Package Version: 10.0.0
- **Operating System**:
- **Python Version**: 

**Describe the bug**
I wanted to encrypt the azure net app volume with customer managed key. when searched the documentation, I could find one parameter encryption_key_source in volume class. But the possible value is Microsoft.keyvault. But I could not see how to set the values of keyvault ID and key name and to which parameter it should be set because the class definition says nothing about it.
Class reference:  https://learn.microsoft.com/en-us/python/api/azure-mgmt-netapp/azure.mgmt.netapp.models.volume?view=azure-python

Please assist how to fix this
![image](https://github.com/Azure/azure-sdk-for-python/assets/36265816/3d6e5b9a-5159-4b3f-b89d-523d89215226)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi @noorjahans 
According to the [reference](https://learn.microsoft.com/en-us/azure/azure-netapp-files/configure-customer-managed-keys#requirements). Keyvault id and key name should have been attached to your netapp account at the first place.
What you need to do is to set `encryption_key_source` 's value as `Microsoft.KeyVault` and provide a key vault private endpoint as the value of `key_vault_private_endpoint_resource_id`, which was also the selected virtual network when you created the volume.

**Comment by noorjahans** [comment]
So that means, we can only encrypt the volumes of a netapp account with the same key and keyvault right?

**Comment by noorjahans** [comment]
If we set CMK in the netapp account level, can we have both type of volumes , some with MMK and some with CMK inside the same netapp account?

**Comment by noorjahans** [comment]
And also , I have some existing volumes that use microsoft managed key encryption in a net app account. If I set CMK for netapp account,  will it affect the existing volumes that have MMK encryption enabled

**Comment by ChenxiJiang333** [comment]
@noorjahans 
If you enable the CMK, both CMK and MMK would be available on new volumes, existing MMK volumes won't be affected.
And yes, the volumes would just share the same encryption settings.
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/42ef4464-255c-4ec3-bad0-eae95d76d6ee)
