### ISSUE TITLE
In cases where result currency field doesn't have the valueCurrency, overall document.to_dict() fails.

### ISSUE THREAD

**Issue by roopakprajapat** [Azure/azure-sdk-for-python#32760]
- **formrecognizer**: 
- **Package Version**: 
- **NA**:
- **3.10**: 

**Describe the bug**
In cases where result currency field doesn't have the valueCurrency, overall document.to_dict() fails. There is lack of error handling in sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py.

function to_dict(self), doesn't handle situations where self.value is None, this happens when value_type currency doesn't have valueCurrency data. When self.value is None, then entire AnalyzeDocument to_dict method fails. This can happen for other value_types.

**To Reproduce**
1. Analyze a document that had value_type currency has missing valueCurrency data

**Expected behavior**
Error handling for self.value None scenarios so that AnalyzedDocument class to_dict function works.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment]
Hi @roopakprajapat , thanks for reporting the issue. You can have a `None` check in your end as a workaround, it could be:
```
if document.value:
    document.to_dict()
    ...
```
Btw, we're rebranding `azure-ai-formrecognizer` to `azure-ai-documentintelligence`. API version `2023-10-31-preview` and later will only be available in the new SDK. Welcome to try on the new one, here's the migration guide: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/MIGRATION_GUIDE.md

Thanks!
