### ISSUE TITLE
Question: "Push" Opentelemetry data to Azure Monitor (and not to Application Insights?)

### ISSUE THREAD

**Issue by andife** [Azure/azure-sdk-for-python#32765]
Hello,
I'm new to the topic, and I may not have the full picture yet.

In https://learn.microsoft.com/en-us/python/api/overview/azure/monitor-opentelemetry-exporter-readme?view=azure-python-preview it says "Microsoft OpenTelemetry exporter for Azure Monitor"? Shouldn't it rather be called for Application Insights? 
Or is it possible from Python to send information with/via OpenTelemetry to Azure Monitor? (without having to have/using Application Insights?).

My thought then was to use Grafana for visualization instead of Application Insights?

**Comment by lzchen** [comment]
@andife 

Application Insights is a product under Azure monitor. In the context of `Microsoft OpenTelemetry exporter for Azure Monitor`, the exporter will export to Application Insights (we just use the Azure montor moniker since it is more consistent with other Azure products).
