### ISSUE TITLE
[azure.ai.ml.parallel.RunFunction] Incorrect parsing of arguments when a space character is in the value

### ISSUE THREAD

**Issue by louisflorentin** [Azure/azure-sdk-for-python#32766]
- **azure.ai.ml**: 1.11.0
- **Python Version**: 3.10.11

**Describe the bug**
When passing arguments to `azure.ai.ml.parallel.RunFunction` through its `program_arguments` argument, values containing a space character will be split even if they are surrounded by quotes or if backlashes are added in front of space characters.

**To Reproduce**
1. Submit a parallel job using `azure.ai.ml.parallel.RunFunction`
2. The `program_arguments` of `azure.ai.ml.parallel.RunFunction` should be a string like this:
- `"--arg 'this is the value'"`
- `'--arg "this is the value"'`
- `"--arg this\ is\ the\ value"`

3. Notice how AML parses arguments in a wrong way. Parsed arguments will be:
- `["--arg", "'this", "is", "the", "value'"]`
- `['--arg', '"this is the value"']`
- `["--arg", "this\", "is\", "the\", "value"]`

...instead of `["--arg", "this is the value"]`

**Expected behavior**
If an argument value is surrounded by quotes or if we add a backlash in front of space characters, these values shouldn't be split when parsed.

**Comment by bupt-wenxiaole** [comment]
@louisflorentin  We had an internal team discussion, the

**Comment by bupt-wenxiaole** [comment]
@louisflorentin  We had an internal team discussion, basically, this is by-design, SDK needs to support both positional arguments and the flag arguments, the service will split the program arguments with space,
another solution without trim is using input binding like the "test_arg" in below code snippets.
`# Declare parallel job with run_function task
many_model_training_with_partition_keys = parallel_run_function(
    name="train_many_models_with_partition_keys",
    display_name="Train Many Models With Partition Keys",
    description="parallel job to train many models with partition_keys on mltable input",
    tags={
        "azureml_parallel_example": "oj_many-model_sdk",
    },
    inputs=dict(
        data_source=Input(
            type=AssetTypes.MLTABLE,
            description="Input mltable with predefined partition format.",
            mode=InputOutputModes.DIRECT,  # [Important] To use 'partition_keys', input MLTable is required to use 'direct' mode.
        ),
        drop_cols=Input(
            type="string",
            description="Columns need to be dropped before training. Split by comma.",
        ),
        target_col=Input(
            type="string",
            description="The column name for label of the input data.",
        ),
        date_col=Input(
            type="string",
            description="The column name for datatime. This will be used for generating time-series lagging data.",
        ),
        lagging_orders=Input(
            type="string",
            description="List of int which indicate how to generate lagging data for time-series input. Split by comma.",
        ),
        test_arg=Input(
            type="string",
            description="Test argument for parallel job.",
        ),
    ),
    outputs=dict(
        model_folder=Output(
            type=AssetTypes.URI_FOLDER,
            mode=InputOutputModes.RW_MOUNT,
        ),
    ),
    input_data="${{inputs.data_source}}",  # Define which input data will be splitted into mini-batches
    partition_keys=[
        "Store",
        "Brand",
    ],  # Use 'partition_keys' as the data division method. This method requires MLTable input with partition setting pre-defined in MLTable artifact.
    instance_count=2,  # Use 2 nodes from compute cluster to run this parallel job.
    max_concurrency_per_instance=1,  # Create 2 worker processors in each compute node to execute mini-batches.
    error_threshold=-1,  # Monitor the failures of item processed by the gap between mini-batch input count and returns. 'Many model training' scenario doesn't fit this setting and '-1' means ignore counting failure items by mini-batch returns.
    mini_batch_error_threshold=5,  # Monitor the failed mini-batch by exception, time out, or null return. When failed mini-batch count is higher than this setting, the parallel job will be marked as 'failed'.
    retry_settings=dict(
        max_retries=2,  # Define how many retries when mini-batch execution is failed by exception, time out, or null return.
        timeout=60,  # Define the timeout in second for each mini-batch execution.
    ),
    logging_level="DEBUG",
    environment_variables={
        "AZUREML_PARALLEL_EXAMPLE": "1a_sdk",
    },
    task=RunFunction(
        code="./src/parallel_train/",
        entry_script="parallel_train.py",
        environment=Environment(
            image="mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04",
            conda_file="./src/parallel_train/conda.yaml",
        ),
        program_arguments="--drop_cols ${{inputs.drop_cols}} "  # Passthrough input parameters into parallel_train script.
        "--target_col ${{inputs.target_col}} "
        "--date_col ${{inputs.date_col}} "
        "--lagging_orders ${{inputs.lagging_orders}} "
        "--model_folder ${{outputs.model_folder}} "
        "--test_arg ${{inputs.test_arg}} ",
    ),
)`
