### ISSUE TITLE
Run custom startup scripts when provisioning an Azure VM via python SDK

### ISSUE THREAD

**Issue by rachelywong** [Azure/azure-sdk-for-python#32772]
**Is your feature request related to a problem? Please describe.**
I would like to be able to run custom Python startup scripts when provisioning a VM via the python SDK.

I've been working closely with the Azure VM support team to create a `provision_vm.py` script that will auto create Azure VMs. Previously, I used GCP to do so and I was able to add a startup script to be run each time a VM is provisioned. It seems Azure does not have this functionality, and this was confirmed by the Azure support team. They suggested I create an issue here.

**Describe the solution you'd like**
[Documentation on GCP startup scripts](https://cloud.google.com/compute/docs/instances/startup-scripts/linux). It would be nice to have this option in Azure.

**Describe alternatives you've considered**
Staying with GCP because they have this functionality.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi @rachelywong 
Python SDK is generated with swagger automatically. This issue would be transferred to [Azure REST API Specifications](https://github.com/Azure/azure-rest-api-specs/issues) for support. Once swagger is updated, python SDK will release new version to support it.

Related swagger might be https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-07-01/virtualMachine.json#L3076.

**Comment by rachelywong** [comment]
> Hi @rachelywong Python SDK is generated with swagger automatically. Please open an issue at [Azure REST API Specifications](https://github.com/Azure/azure-rest-api-specs/issues) for the feature request. Once swagger is updated, python SDK will release new version to support it.
> 
> Related swagger might be https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-07-01/virtualMachine.json#L3076.

Issue has been created [here](https://github.com/Azure/azure-rest-api-specs/issues/26472)

**Comment by ChenxiJiang333** [comment]
Hope we could get a quick response.
