### ISSUE TITLE
Logic Management Client workflow_runs.list operation mishandles `top` parameter

### ISSUE THREAD

**Issue by wushingmushine** [Azure/azure-sdk-for-python#32791]
- **Package Name**: azure-mgmt-logic
- **Package Version**: 10.0.0 and 10.1.0b1
- **Operating System**: Ubuntu 22.04 on WSL2
- **Python Version**:  3.10.6

**Describe the bug**
 - In the current stable release (10.0.0): when passing an integer value to the `top` parameter in the LogicManagementClient.workflow_runs.list operation, e.g. `top = 10`, the desired number of results are returned, then value validation incorrectly fails, returning an error like the following: `(InvalidTopInQueryString) The value for top of '10,10' is not an integer; the value must be an integer value greater than zero.`. 

 - In the beta release (10.1.0b1): when passing an integer value to the `top` parameter in the LogicManagementClient.workflow_runs.list operation, the value for top is entirely ignored, returning more results than desired.

**To Reproduce**
1. 
```
workflow_runs = logic_client.workflow_runs.list(resource_group_name="my-rg", workflow_name="my-workflow", top = 10)
for i, run in enumerate(workflow_runs):
    print(i)
```
In the 10.0.0 package this prints numbers 0 through 9 but then the following error:
```
(InvalidTopInQueryString) The value for top of '10,10' is not an integer; the value must be an integer value greater than zero.\nCode: InvalidTopInQueryString\nMessage: The value for top of '10,10' is not an integer; the value must be an integer value greater than zero.\nTraceback (most recent call last):\n  File \"/home/user/test.py\", line 39, in run\n    for i, run in enumerate(workflow_runs):\n  File \"/home/user/.local/lib/python3.10/site-packages/azure/core/paging.py\", line 124, in __next__\n    return next(self._page_iterator)\n  File \"/home/user/.local/lib/python3.10/site-packages/azure/core/paging.py\", line 76, in __next__\n    self._response = self._get_next(self.continuation_token)\n  File \"/home/user/.local/lib/python3.10/site-packages/azure/mgmt/logic/operations/_workflow_runs_operations.py\", line 253, in get_next\n    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)\nazure.core.exceptions.HttpResponseError: (InvalidTopInQueryString) The value for top of '10,10' is not an integer; the value must be an integer value greater than zero.\nCode: InvalidTopInQueryString\nMessage: The value for top of '10,10' is not an integer; the value must be an integer value greater than zero.\n
```
With the 10.1.0b1 package this would prints the numbers 0 through 262 (the number of workflow runs I currently have), showing that the `top` parameter is ignored. 

**Expected behavior**
Passing integer X to the `top` parameter results in X workflow runs being returned in the response.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi, @wushingmushine 
Sorry but the `top` parameter is still not completely supported in the sdk. 
Please keep use with version 10.1.0b1 and you could add this feature locally by dealing with the results:
```
