### ISSUE TITLE
NoRegisteredProviderFound for creating diagnostic setting

### ISSUE THREAD

**Issue by kamalyesh** [Azure/azure-sdk-for-python#32856]
- **azure-mgmt-monitor**: 
- **5.0.1**: 
- **Ubuntu 22.04.3 LTS**:
- **python 3.10.12**: 

**Describe the bug**
I am trying to create diagnostic settings, to enable logging in the blob container in a storage account. 

If I try without specifying API version, the automatically selected version is 2021-05-01-preview, but I am getting error "NoRegisteredProviderFound".

If I specify API version to be api_version="2021-05-01", then error says "API version 2021-05-01 does not have operation group 'diagnostic_settings'".

Please suggest solution to this problem. Is there some alternate REST API that I can call instead?

**To Reproduce**
1. run following script

    def foo():
        from azure.identity import DefaultAzureCredential
        from azure.mgmt.monitor import MonitorManagementClient
        # client = MonitorManagementClient(credential=default_credential, subscription_id=subscription_id, api_version="2021-05-01-preview")
        # NoRegisteredProviderFound

        # client = MonitorManagementClient(credential=default_credential, subscription_id=subscription_id, api_version="2021-05-01")
        # API version 2021-05-01 does not have operation group "diagnostic_settings"

        default_credential = default_credential = DefaultAzureCredential(exclude_interactive_browser_credential=False)
        client = MonitorManagementClient(credential=default_credential, subscription_id=subscription_id)
        diagnostics_setting = DiagnosticSettingsResource(
            storage_account_id=storage_acccout_id,
            workspace_id=workspace_id,
            logs=[
                {
                    "category": None,
                    "categoryGroup": "audit",
                    "enabled": False,
                    "retentionPolicy": {
                        "days": 0,
                        "enabled": False
                    }
                },
                {
                    "category": None,
                    "categoryGroup": "allLogs",
                    "enabled": True,
                    "retentionPolicy": {
                        "days": 1,
                        "enabled": False
                    }
                }
            ],
            metrics=[
                {
                    "enabled": False,
                    "retentionPolicy": {
                        "days": 1,
                        "enabled": False
                    },
                    "category": "Transaction"
                }
            ],
        )
        return client.diagnostic_settings.create_or_update(
            resource_uri=resource_uri,
            name=diagnostics_setting_name, 
            parameters=diagnostics_setting,
        )

**Expected behavior**
Diagnostic setting should be created

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/15943943/dc6e5e07-1b51-48fb-a1f3-ac07750afd94)

**Additional context**
The setting is to be created on storage account so that all blob storage logs are seen on log analytics workspace

**Comment by ChenxiJiang333** [comment]
There's nothing about api versions. It seems because that the url requested was in an incorrect format.

Please update `resource_uri` to the format below and try again. (just need to change the value in the curly braces)
```
/subscriptions/{subscriptions}/resourceGroups/{resourceGroups}/providers/Microsoft.Storage/storageAccounts/{storageAccounts}/blobServices/default
```

**Comment by kamalyesh** [comment]
Thanks, I will try this correction and update about it as soon as possible.

**Comment by kamalyesh** [comment]
It is working! Thank you!
