### ISSUE TITLE
AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session' for azure.graphrbac

### ISSUE THREAD

**Issue by anilmawji** [Azure/azure-sdk-for-python#32869]
- **Package Name**: azure.graphrbac
- **Package Version**: 0.61.1
- **Operating System**: Windows 11 Home, version 22H2, build 22621.2428
- **Python Version**: 3.11.0

**Describe the bug**
Received the error `Exception: AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'` when attempting to iterate over the list of users returned from from GraphRbacManagementClient.users.list().

**To Reproduce**
1. Run the following script:
```
from azure.identity import DefaultAzureCredential
from azure.graphrbac import GraphRbacManagementClient

credential = DefaultAzureCredential()

rbac_client = GraphRbacManagementClient(credentials=credential, tenant_id="xxxxxxxxxxx")

users = rbac_client.users.list()

# Error only occurs when trying to iterate
for user in users:
    None
```

**Expected behavior**
Expect to be able to iterate over the list of returned users without the error.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/36245645/bfe76625-01b1-49cb-be1d-86d7362f5d65)

**Additional context**
The top answer to [this question on SO](https://stackoverflow.com/questions/63384092/exception-attributeerror-defaultazurecredential-object-has-no-attribute-sig) suggests upgrading to the latest packages to support azure-identity. In this case, both `azure.identity` and `azure.graphrbac` have been upgraded to their latest versions.

**Comment by pvaneck** [comment]
Hey, @anilmawji, sorry you are running into this. The `azure-graphrbac` package has been deprecated, and the recommendation is to use the following SDK: https://pypi.org/project/msgraph-sdk/ which is maintained at https://github.com/microsoftgraph/msgraph-sdk-python.

Some usage samples can be found here:
https://github.com/microsoftgraph/msgraph-sdk-python#23-initialize-a-graphserviceclient-object

Let me know if that works for you.

**Comment by anilmawji** [comment]
Thank you @pvaneck this issue can be closed.
