### ISSUE TITLE
How to upgrade Azure Python SDK version while maintaining support for existing API calls?

### ISSUE THREAD

**Issue by prmjh4** [Azure/azure-sdk-for-python#32913]
Is it possible to upgrade to a newer version of Azure Python SDK while being able to use older Azure SDK API calls? I have an existing script that relies on the older version, but I want to take advantage of new Azure SDK modules and API calls available in the updated version. My objective is to improve my script by incorporating new features while retaining compatibility with the existing functionalities provided by the older Azure SDK version. What would be the recommended approach to achieve this integration?

**Comment by prmjh4** [comment]
We had a script that was written in python2.7 but now the system demands to integrate the latest features like Disk Encryption Sets which is only available in the latest SDK version and also the support for python2.7 is deprecated thus this will work only with newer python versions.
What you would suggest to leverage the latest available features of Azure using latest SDKs calls and improve the product experience and integration with the Azure cloud.
Sorry for the late response I was busy with higher priority tasks.
Thanks you!

**Comment by xiangyan99** [comment]
Thanks for the feedback. 

Please find our Python version support policy https://github.com/Azure/azure-sdk-for-python/wiki/Azure-SDKs-Python-version-support-policy.
