### ISSUE TITLE
Azure Service Bus client receives messages from Azure Service Bus with lock already expired. 

### ISSUE THREAD

**Issue by s17b2-voroneckij** [Azure/azure-sdk-for-python#32943]
- **Package Name**: azure.servicebus - but the issue also happens with the library for Java
- **Package Version**: 7.11.2
- **Operating System**: Windows, Linux
- **Python Version**: 3.11
**Describe the bug**
When I try to receive a large message from Azure Service Bus, it arrives with a lock that has already expired. 

**To Reproduce**
1. Create an ASB queue with Premium. For example, the ASB location can be UK South
2. Run the following code from a virtual machine in UK South area: `import datetime

from azure.servicebus import ServiceBusClient, ServiceBusMessage

conn_string = ""
queue_name = ""

if __name__ == "__main__":
    client = ServiceBusClient.from_connection_string(conn_string)
    sender = client.get_queue_sender(queue_name)
    with sender:
        print("about to send message")
        message = ServiceBusMessage("0" * 1024 * 1024 * 25)
        sender.send_messages(message)
        print("message sent")

`
3. Launch a virtual machine in UAE region and run the following code: `import datetime

from azure.servicebus import ServiceBusClient, ServiceBusMessage

conn_string = ""
queue_name = ""

if __name__ == "__main__":
    client = ServiceBusClient.from_connection_string(conn_string)

    receiver = client.get_queue_receiver(queue_name)
    with receiver:
        print("about to receive")
        message = receiver.receive_messages(1)[0]
        print("received, locked until", message.locked_until_utc)
        print(datetime.datetime.utcnow())
        receiver.complete_message(message)
        print("completed")

`

**Expected behavior**
successfully receiving message and removing it from queue

**Screenshots**
about to receive
received, locked until 2023-11-03 18:40:59.312000+00:00
2023-11-03 18:42:26.968377
Traceback (most recent call last):
  File "/home/dima/PycharmProjects/async-iris/my_asb.py", line 25, in <module>
    receiver.complete_message(message)
  File "/home/dima/PycharmProjects/async-iris/venvpypy/lib/pypy3.8/site-packages/azure/servicebus/_servicebus_receiver.py", line 842, in complete_message
    self._settle_message_with_retry(message, MESSAGE_COMPLETE)
  File "/home/dima/PycharmProjects/async-iris/venvpypy/lib/pypy3.8/site-packages/azure/servicebus/_servicebus_receiver.py", line 473, in _settle_message_with_retry
    error=message.auto_renew_error,
azure.servicebus.exceptions.MessageLockLostError: The lock on the message lock has expired.
**Additional context**

**Comment by kashifkhan** [comment]
@s17b2-voroneckij Can you describe the issue at hand in more detail please and add in information about the package version, python version etc so that we can better assist you. Additionally, sample code that can reproduce the issue will also help

**Comment by s17b2-voroneckij** [comment]
@kashifkhan, I wanted to report an issue that is common to all SDKs for Azure Service Bus, but I realised that it is easier for me to give example errors for the Java SDK, so I filed this issue instead: [https://github.com/Azure/azure-sdk-for-java/issues/37497#issuecomment-1792623264](url)

After submitting that issue, I also submitted this one by mistake. 
If you would like to look into the issue closer with regards to Python SDKs, I could provide you part of the code and logs.

**Comment by swathipil** [comment]
Hi @s17b2-voroneckij - It looks like you've received an answer on the Java issue, that the default lock duration should be bumped because of size of the message and location of the host vs. client. This answer applies across all of the SDKs. Thanks!
