### ISSUE TITLE
ValueError: No value for given attribute raised by MLClient

### ISSUE THREAD

**Issue by LucasColas** [Azure/azure-sdk-for-python#32944]
- **Package Name**: azure.ai.ml
- **Package Version**: 1.8.0
- **Operating System**:Linux
- **Python Version**: 3.10 - SDK V2

**Describe the bug**
Whenever I try to see if a compute target already exists I use an instance of MLClient but an error is raised (even though I do a try except). And also this print is executed : `print("Creating a new gpu compute target...")`.

**To Reproduce**
1. I followed [this documentation](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-train-pytorch?view=azureml-api-2)
2. Code : 
```py
# Handle to the workspace
from azure.ai.ml import MLClient

# Authentication package
from azure.identity import DefaultAzureCredential

credential = DefaultAzureCredential()
ml_client = MLClient(
    credential=credential,
    subscription_id=subscription_id,
    resource_group=resource_group,
    workspace_name=workspace_name
)

from azure.ai.ml.entities import AmlCompute

gpu_compute_target = "lucas01"
try:
    # let's see if the compute target already exists
    gpu_cluster = ml_client.compute.get(gpu_compute_target)
    print(
        f"You already have a cluster named {gpu_compute_target}, we'll reuse it as is."
    )

except Exception:
    print("Creating a new gpu compute target...")

    # Let's create the Azure ML compute object with the intended parameters
    gpu_cluster = AmlCompute(
        # Name assigned to the compute cluster
        name="gpu-cluster",
        # Azure ML Compute is the on-demand VM service
        type="amlcompute",
        # VM Family
        size="STANDARD_NC6s_v3",
        # Minimum running nodes when there is no job running
        min_instances=0,
        # Nodes in cluster
        max_instances=4,
        # How many seconds will the node running after the job termination
        idle_time_before_scale_down=180,
        # Dedicated or LowPriority. The latter is cheaper but there is a chance of job termination
        tier="Dedicated",
    )

    # Now, we pass the object to MLClient's create_or_update method
    gpu_cluster = ml_client.begin_create_or_update(gpu_cluster).result()

print(
    f"AMLCompute with name {gpu_cluster.name} is created, the compute size is {gpu_cluster.size}"
)

```
**Expected behavior**
I should except to have a print saying "You already have a cluster named lucas01, we'll reuse it as is."

**Additional context**
Full error : 
Creating a new gpu compute target...
> ValueError                                Traceback (most recent call last)
> /home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb Cell 6 line 6
>       [4](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#X40sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3) try:
>       [5](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#X40sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4)     # let's see if the compute target already exists
> ----> [6](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#X40sdnNjb2RlLXJlbW90ZQ%3D%3D?line=5)     gpu_cluster = ml_client.compute.get(gpu_compute_target)
>       [7](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#X40sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6)     print(
>       [8](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#X40sdnNjb2RlLXJlbW90ZQ%3D%3D?line=7)         f"You already have a cluster named {gpu_compute_target}, we'll reuse it as is."
>       [9](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#X40sdnNjb2RlLXJlbW90ZQ%3D%3D?line=8)     )
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/tracing/decorator.py:76, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
>      [75](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/tracing/decorator.py:75) if span_impl_type is None:
> ---> [76](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/tracing/decorator.py:76)     return func(*args, **kwargs)
>      [78](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/tracing/decorator.py:78) # Merge span is parameter is set, but only if no explicit parent are passed
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/_telemetry/activity.py:263, in monitor_with_activity.<locals>.monitor.<locals>.wrapper(*args, **kwargs)
>     [262](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/_telemetry/activity.py:262) with log_activity(logger, activity_name or f.__name__, activity_type, custom_dimensions):
> --> [263](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/_telemetry/activity.py:263)     return f(*args, **kwargs)
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/operations/_compute_operations.py:78, in ComputeOperations.get(self, name)
>      [70](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/operations/_compute_operations.py:70) """Get a compute resource.
>      [71](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/operations/_compute_operations.py:71) 
>      [72](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/operations/_compute_operations.py:72) :param name: Name of the compute
> ref='/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/operations/_compute_operations.py:0'>0</a>;32m   (...)
>      [75](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/operations/_compute_operations.py:75) :rtype: Compute
> ...
> --> [760](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/msrest/serialization.py:760)     raise ValueError("No value for given attribute")
>     [762](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/msrest/serialization.py:762) try:
>     [763](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/msrest/serialization.py:763)     if data_type in self.basic_types.values():
> 
> ValueError: No value for given attribute

**Comment by kristapratico** [comment]
@LucasColas thanks for your issue, @azureml-github can you take a look?

**Comment by khataei** [comment]
Hey @LucasColas ,
I had the same issue, after looking at the source code I realized `resource_group` is changed to `resource_group_name`.

So instead of
ml_client = MLClient(
    credential=credential,
    subscription_id=subscription_id,
    resource_group=resource_group,
    workspace_name=workspace_name
)
go with

ml_client = MLClient(
    credential=credential,
    subscription_id=subscription_id,
    **resource_group_name**=resource_group,
    workspace_name=workspace_name
)

I hope this fixes your issue as well.
Cheers
J

**Comment by LucasColas** [comment]
Thanks !
