### ISSUE TITLE
Can't create a Azure Data Lake Storage Gen2 dataset with modifiedDatetime fields using the SDK

### ISSUE THREAD

**Issue by FancyGecko** [Azure/azure-sdk-for-python#32959]
- **Package Name**: azure-mgmt-datafactory
- **Package Version**: 3.1.0
- **Operating System**: MacOS 14.0 (23A344)
- **Python Version**: 3.8.18

**Describe the bug**
In Azure Data Factory UI you can create an Azure Data Lake Storage Gen2 dataset with dynamic content in the fields Start time (UTC) and End time (UTC) under "Filter by last modified". If you try to use the SDK there seems to be no support for this.

The Data Factory model AzureBlobFSDataset does not look to have the parameters modified_datetime_start and modified_datetime_end similar to AzureBlobDataset.

When I try to use JSON the fields modifiedDatetimeStart and or modifiedDatetimeEnd don't make it to the dataset in Data Factory.

**To Reproduce**
1. Use DataFactoryManagementClient with dataset operation create_or_update to create a dataset in data facotry
2. Have a dataset payload with type AzureBlobFSFile and fields modifiedDatetimeStart or modifiedDatetimeEnd in it
```json
"properties": {
        "linkedServiceName": {
            "referenceName": "storageLinkedService001",
            "type": "LinkedServiceReference"
        },
        "annotations": [],
        "type": "AzureBlobFSFile",
        "typeProperties": {
            "fileName": "*",
            "folderPath": "incoming",
            "modifiedDatetimeEnd": {
                "value": "@pipeline().TriggerTime",
                "type": "Expression"
            }
        }
    }
```
3.  Check the dataset in Data Factory to see if the content made it.

**Expected behavior**
modifiedDatetimeStart and modifiedDatetimeEnd can be set using the SDK and type being AzureBlobFSFile

**Comment by kristapratico** [comment]
@FancyGecko thanks for your issue, we'll take a look and get back to you as soon as possible.

**Comment by ChenxiJiang333** [comment]
Hi @FancyGecko Python SDK is generated with swagger automatically. Related swagger is [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Dataset.json#L1446-L1468) and we do not have property `modifiedDatetimeStart` and `modifiedDatetimeEnd` for `AzureBlobFSFile`. 
Please open issue in https://github.com/Azure/azure-rest-api-specs/issues and mark with label feature request. Once swagger is fixed, python SDK will release new version to support it.
