### ISSUE TITLE
Exists method for ShareFileClient

### ISSUE THREAD

**Issue by FFranz93** [Azure/azure-sdk-for-python#32969]
**Is your feature request related to a problem? Please describe.**
Using the Azure SDK for .NET the `ShareFileClient` has a method `Exists()`, to check if a file exists.
While in the Azure SDK for Python the `ShareDirectoryClient` also has such a method, the `ShareFileClient` does not have such a method, so it would be a great if this would be added as well, since currently it requires a workaround to check the existence of a file.

**Describe the solution you'd like**
Add method `exists()` to `ShareFileClient` in Azure SDK for Python.

**Describe alternatives you've considered**
There is no alternative to that feature, there is only workarounds like calling `get_file_properties()` on the instance of `ShareFileClient` and to check if it throws a `ResourceNotFoundError` to check if a file exists.

Checking for specific expections and returning `True` or `False` based on the outcome of the request is basically how `Exists()` works in the .NET SDK.
But it would be a way better approach to have this logic encapsulated within a method that comes with the client itself, then to force all users into writing their own workaround if they want to check on the existence of a file.

**Additional context**

**Comment by kristapratico** [comment]
@FFranz93 thanks for your feature request, the team will take a look and get back to you as soon as possible.

**Comment by jalauzon-msft** [comment]
Hi @FFranz93, thanks for reaching out. This is likely just something we missed in the original implementation. We will get a PR to address this soon. However, we do not have a planned release until February at the earliest so it may be a little while until this is available in the library. For now, you can continue to use the workaround of catching the `ResourceExistsException` yourself. Thanks.
