### ISSUE TITLE
Typo "a Azure Cognitive Search"→"an Azure Cognitive Search"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-sdk-for-python#32965]
Typo "a Azure Cognitive Search"→"an Azure Cognitive Search"
https://learn.microsoft.com/en-us/python/api/overview/azure/search-documents-readme?view=azure-python
#PingMSFTDocs

![image](https://github.com/Azure/azure-sdk-for-python/assets/40815708/818c4f22-936f-4ea2-a6c8-da999a47e529)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df132c46-f26a-665f-bce4-2a365560448e
* Version Independent ID: 45b881bd-1574-6b25-c48f-93859f4b3d4a
* Content: [Azure Cognitive Search client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/search-documents-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/search-documents-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/search-documents-readme.md)
* Service: **search**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by kristapratico** [comment]
Thanks @hyoshioka0128, we'll look at getting this fixed as soon as possible.
