### ISSUE TITLE
where I can find azure_rm_common.py in a fedora 37 ansible instance

### ISSUE THREAD

**Issue by eliassal** [Azure/azure-sdk-for-python#32977]
- **Package Version**: 
- ansible [core 2.15.5]
  config file = None
  configured module search path = ['/home/salam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/salam/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/salam/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/salam/.local/bin/ansible
  python version = 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

- **Operating System**: Fedora 37
- **Python Version**:  3.11

**Describe the bug**
Can somebody tell me where the file azure_rm_common.py  is located. Following a post regarding a bug for azure, here I understood that I need to replace the following 2 lines

```
 from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
 import azure.mgmt.recoveryservicesbackup.models as RecoveryServicesBackupModels
```
by
```
from azure.mgmt.recoveryservicesbackup.activestamp import RecoveryServicesBackupClient
import azure.mgmt.recoveryservicesbackup.activestamp.models as RecoveryServicesBackupModels
```

I searched all hard drive for this file, nothing is found

**Comment by kristapratico** [comment]
@eliassal the ansible source code is not in this repo. I think the file you are looking for might be found in this repo: https://github.com/ansible-collections/azure

I'm not familiar with the ansible code. What is the azure bug requiring you to replace those lines?

**Comment by eliassal** [comment]
I have an issue when running ansible-playbook

> ModuleNotFoundError: No module named 'azure.mgmt.recoveryservicesbackup.models'

After googling this morning I came across this thread here
https://github.com/ansible-collections/azure/issues/1260#issuecomment-1723531288
pointing to 
https://github.com/Azure/azure-sdk-for-python/issues/28757#issuecomment-1448729884

**Comment by eliassal** [comment]
@kristapratico , yes I have already mentioned this, as I said, I have installed ansible (by following instructions for setup ansible on Fedora) recently so I presume that it has this fix which is not the case. So how should I proceed?

**Comment by kristapratico** [comment]
Please track the issue you created in the ansible repo: https://github.com/ansible-collections/azure/issues/1322

That library is responsible for specifying the versions of its dependencies.
