### ISSUE TITLE
Command is incorrect in the engineer system checks doc

### ISSUE THREAD

**Issue by wuweiran** [Azure/azure-sdk-for-python#33005]
In [eng_sys_checks.md](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/eng_sys_checks.md#latest-dependency-test), the command `tox run -e latestdependency -c ../../../tox/tox.ini --root .` should be `tox run -e latestdependency -c ../../../eng/tox/tox.ini --root .`. Please check and fix.

**Comment by kristapratico** [comment]
Thanks for pointing that out @wuweiran. Fixed in https://github.com/Azure/azure-sdk-for-python/pull/33006
