### ISSUE TITLE
`azure-mgmt-labservices` ResourceNotFoundError: lab creation failing with unique resource groups for image_gallery & lab_plan

### ISSUE THREAD

**Issue by d-gipson** [Azure/azure-sdk-for-python#33023]
- **Package Name**: `azure-mgmt-labservices`
- **Package Version**: `2.0.0`
- **Operating System**: `linux`
- **Python Version**: `3.9.16`

**description**
I have a wrapper for `lab_services_client` called `Lab` that takes a `LabPlan` object and creates a lab. I run into some confusing behavior with the shared gallery image lookup - the image is not found, and the returned template URL for the lookup reflects the resource group of the lab_plan rather than that of the shared image gallery.  For context, the image gallery does not exist in the same resource group as the lab_plan/lab which is being created, but the shared gallery set in the lab_plan_body and the lab_plan are the same.

**steps**
if I specify the `imageReference` in the lab body with `{"id" : "/subscriptions/<subscription-id-A>/resourceGroups/<resource-group-A>/providers/Microsoft.Compute/galleries/<gallery-name>/images/<sku>/versions/1.0.1"}` and use my `lab.create_lab()`, I get
```
azure.core.exceptions.HttpResponseError: (ResourceNotFound) Resource with ID '/subscriptions/<subscription-id-B>/resourceGroups/<resource-group-B>/providers/Microsoft.LabServices/labPlans/<labPlanName>/images/1.0.1' cannot be found or does not exist
```

alternatively, when I build the lab body with `publisher`, `offer`, `sku`, `version` for `imageReference`, I error out with
```
azure.core.exceptions.HttpResponseError: (ResourceNotFound) Resource with ID '/subscriptions/<subscription-id-B>/resourceGroups/<resource-group-B>/providers/Microsoft.LabServices/labPlans/<labPlanName>/images/<Publisher>.<Offer>.<Sku>' cannot be found or does not exist
```

**expected**
The template url/resource ID for the lab is built in [`build_create_or_update_request()`](https://github.com/Azure/azure-sdk-for-python/blob/daf3eda6854ba33e1dade77aa5798a72740f9d82/sdk/labservices/azure-mgmt-labservices/azure/mgmt/labservices/operations/_lab_plans_operations.py#L135-L168). Why is the same URL used for the image lookup? is this what we should expect for the image lookup? i would expect a separate template URL formatting scheme for the image lookup, but it seems that the image version just gets appended on to the template url built for the lab plan.

this behavior seems to imply that the shared gallery where the image lives needs to be in the same resource group as the lab plan that's being created - is this true?

**additional**
according to the docs, these properties (`id`, and the set of `publisher/offer/sku`) are mutually exclusive. it would make sense to use `id` property when referencing an image that does not reside in the same resource group as the lab.

**Comment by ChenxiJiang333** [comment]
Hi, @d-gipson 
For the image lookup, you need to [attach your compute gallery to the lab plan](https://learn.microsoft.com/en-us/azure/lab-services/how-to-attach-detach-shared-image-gallery?tabs=azure-cli#attach-a-new-compute-gallery-to-a-lab-plan) and enable the specify image first. The compute gallery and lab plan don't have to be in the same resource group.

**Comment by d-gipson** [comment]
thank you!
I did need to grant ownership to the lab services principal. However, my understanding is that passing a valid `sharedGalleryId` property in the lab plan body (once permissions are set) should attach the gallery to the lab plan. 
This doesn't seem to be the case, so am I curious how I should attach the gallery to the lab plan programmatically (since the [create lab plan example](https://learn.microsoft.com/en-us/azure/lab-services/how-to-create-lab-plan-python) doesn't attach a gallery, and the [create lab example](https://learn.microsoft.com/en-us/azure/lab-services/how-to-create-lab-python) only shows an image reference to an already-attached gallery.

**Comment by ChenxiJiang333** [comment]
@d-gipson 
It does work for me to attach the gallery through sdk:
```
client.lab_plans.begin_update(resource_group_name,lab_plan_name,body={"sharedGalleryId":"/subscriptions/{subscriptions}/resourceGroups/{resourceGroups}/providers/Microsoft.Compute/galleries/{gallery}"}).result()
```
And to enable the image:
```
client.images.update(resource_group_name,lab_plan_name,image_name,body={"enabledState":"Enabled"})
```
