### ISSUE TITLE
Can't run sample usage to get data assets

### ISSUE THREAD

**Issue by LucasColas** [Azure/azure-sdk-for-python#33049]
- **Package Name**: azure-core
- **Package Version**: 1.27.1
- **Operating System**:Linux
- **Python Version**: 3.10

**Describe the bug**
I used the code given by azure ml to use to get my data asset. But I got an error : 

> AttributeError                            Traceback (most recent call last)
> /home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb Cell 8 line 1
>       [8](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#Y115sdnNjb2RlLXJlbW90ZQ%3D%3D?line=7) workspace = Workspace(subscription_id, resource_group, workspace_name)
>      [10](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#Y115sdnNjb2RlLXJlbW90ZQ%3D%3D?line=9) dataset = Dataset.get_by_name(workspace, name='object_detection_images')
> ---> [11](vscode-notebook-cell://amlext%2B2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031/home/azureuser/cloudfiles/code/Users/lucas.colas/segmentation-of-windows-and-doors/detection/train_model.ipynb#Y115sdnNjb2RlLXJlbW90ZQ%3D%3D?line=10) dataset.download(target_path='.', overwrite=False)
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/_loggerfactory.py:132, in track.<locals>.monitor.<locals>.wrapper(*args, **kwargs)
>     [130](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/_loggerfactory.py:130) with _LoggerFactory.track_activity(logger, func.__name__, activity_type, custom_dimensions) as al:
>     [131](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/_loggerfactory.py:131)     try:
> --> [132](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/_loggerfactory.py:132)         return func(*args, **kwargs)
>     [133](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/_loggerfactory.py:133)     except Exception as e:
>     [134](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/_loggerfactory.py:134)         if hasattr(al, 'activity_info') and hasattr(e, 'error_code'):
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:155, in FileDataset.download(self, target_path, overwrite, ignore_not_found)
>     [150](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:150) download_list = None
>     [151](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:151) if not is_empty and not overwrite:
>     [152](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:152)     # need to fail if destination is not empty and download would have collisions
>     [153](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:153)     download_list = [
>     [154](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:154)         os.path.abspath(os.path.join(target_path, '.' + p))
> --> [155](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:155)         for p in self._to_path(activity='download.to_path')
>     [156](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:156)     ]
>     [158](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:158)     for p in download_list:
>     [159](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:159)         # encode p to avoid UnicodeEncodeError from os.path.exists
>     [160](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:160)         if os.path.exists(_encode_if_needed(p)):
> ...
> --> [677](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:677)     (prefix_path, _) = dataflow._find_path_prefix()
>     [678](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:678)     portable_path = 'Portable Path'
>     [679](https://vscode-remote+amlext-002b2f737562736372697074696f6e732f38316565363437662d326134322d343935392d623234352d6466393933653065303331372f7265736f7572636547726f7570732f41524941494d4c2f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f61726961696d6c2f636f6d70757465732f6c756361733031.vscode-resource.vscode-cdn.net/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/data/file_dataset.py:679)     get_portable_path = dataprep().api.functions.get_portable_path
> 
> AttributeError: 'Dataflow' object has no attribute '_find_path_prefix'

**To Reproduce**
1. Create a data asset (URI_Folder) for images.
2. Go to consume and use the code : 
![Capture d'écran 2023-11-08 144400 floute](https://github.com/Azure/azure-sdk-for-python/assets/51634013/770493b6-4927-41c0-9a00-c8ab32c6a340)

**Expected behavior**
I should be able to download the data asset.

**Comment by kristapratico** [comment]
@LucasColas thanks for your issue. @azureml-github will take a look and respond as soon as possible.

**Comment by LucasColas** [comment]
Good. Thank you.

**Comment by anliakho2** [comment]
Thank you for reporting this. As it stands today the only type of V2 data asset that is supported in V1 SDK is MLTable.
With currently released code you have two options:
- Use V2 sdk to download data
- Create an MLtable pointing to the same data and register it as MLTable asset, then load it by name in V1 SDK.

I have added code to support both UriFolder and UriFile data assets in V1 SDK, so it should be released with the next azureml-sdk version (1.56 most likely)
Hope this helps

**Comment by isaudagar** [comment]
Thanks @anliakho2 , @LucasColas I will update next azureml-sdk release version 1.56.0

**Comment by isaudagar** [comment]
Hi @LucasColas , 
we released SDK 1.56.0 in pypi.org could you please validate and confirm?
