### ISSUE TITLE
replacement of Environment.add_private_pip_wheel(workspace=<>,file_path = <>,exist_ok=True) in SDK V2

### ISSUE THREAD

**Issue by shishirdash24** [Azure/azure-sdk-for-python#33042]
I am bound to use private wheel package in my ML pipeline code, but unable to find the feature in SDK V2. In SDK V1, the same was available through Environment.add_private_pip_wheel(workspace=<>,file_path = <>,exist_ok=True) under azureml.core.environment import Environment. 

Please could you share the package in V2 which will help me to do the same. It's urgent. 

There seems to be too many gaps in SDK V2.

**Comment by kristapratico** [comment]
Hi @shishirdash24, please share the following information to help us better assist you with your question:

Package Name: 
Package Version: 
Operating System:
Python Version:

I think you are referring to the azure-ai-ml package? @azureml-github to took a look.

**Comment by shishirdash24** [comment]
Hi,

This package doesn't exist in Azure ML SDK V2. How will I be able to provide the details ?
Package Name: No idea. Please help to find.
Package Version: No idea. Please help to find.
Operating System: 
Python Version: 3.10

I want to add a private wheel package to the environment in Azure ML SDK V2 pipeline.
Please share the solution for the same. 
I explored a lot & found that Microsoft has actually missed this package in SDK V2.

**Comment by banibrata-de** [comment]
@shishirdash24 it is indeed a very useful feature. We'll look into that and try to prioritize, can't promise any short-term solution though. We'll create a feature request on our end.
