### ISSUE TITLE
[AppConfig] Inconsistent usage of "etag" in sync and async set_configuration_setting()

### ISSUE THREAD

**Issue by YalinLi0312** [Azure/azure-sdk-for-python#33073]
Here's the current etag usage in sync `set_configuration_setting()`:
https://github.com/Azure/azure-sdk-for-python/blob/0deb396b14fa2741dfab80c3276bb83e6411a932/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py#L369-L370
Here's the usage in async:
https://github.com/Azure/azure-sdk-for-python/blob/0deb396b14fa2741dfab80c3276bb83e6411a932/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_appconfiguration_client_async.py#L388-L389

Based on the difference, we need to investigate:
- which `etag` value should we use in `if_match` and `if_none_match`? From keyword `etag` or `configuration_setting.etag`?
- what's the behavior when users set `match_condition=MatchConditions.IfNotModified/IfModified`? Also, need to update the docstring accordingly.

Some discussions happened in [Teams](https://teams.microsoft.com/l/message/19:4175567f1e154a80ab5b88cbd22ea92f@thread.skype/1698981285372?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1698981285372&teamName=Azure%20SDK&channelName=Language%20-%20Python%20-%20Reviews&createdTime=1698981285372)

**Comment by annatisch** [comment]
This parameter needs to be evaluated throughout the API. It's also not used in `set_read_only`.

**Comment by YalinLi0312** [comment]
This issue has been resolved in PR https://github.com/Azure/azure-sdk-for-python/pull/33684. And double checked the `etag` usage in this package, it's consistent between sync and async ops now.
