### ISSUE TITLE
(ImportError) cannot import name 'VectorizableTextQuery' from 'azure.search.documents.models'

### ISSUE THREAD

**Issue by Koushik15042000** [Azure/azure-sdk-for-python#33085]
**Describe the bug**
Unable to import VectorizableTextQuery from azure.search.documents.models

**Expected behavior**
Should be able to import VectorizableTextQuery from azure.search.documents.models as suggested in :

https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-python-sample.ipynb

**Comment by kristapratico** [comment]
@Koushik15042000 thanks for your issue, we will take a look and respond as soon as possible.

**Comment by xiangyan99** [comment]
Thanks for the feedback. This new feature has not shipped yet.

**Comment by alexmonti19** [comment]
Hi, any updates on when this feature will be shipped? I see it is present in pre-release version 11.6.0b1 from January 31st, but I'd love to use a full stable version.

**Comment by PratigyaPatidar145** [comment]
ImportError: cannot import name 'VectorizedQuery' from 'azure.search.documents.models' (c:\Users\Coditas\AppData\Local\Programs\Python\Python311\Lib\site-packages\azure\search\documents\models\__init__.py)






i am facing error while importing 'VectorizedQuery . how to resolve it
