### ISSUE TITLE
Error handling function in azure-storage-blob prints DeprecationWarning in Python 3.12

### ISSUE THREAD

**Issue by kfrydel** [Azure/azure-sdk-for-python#33096]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.19.0
- **Operating System**: Linux/Windows (it doesn't matter)
- **Python Version**: 3.12

**Describe the bug**
A `DeprecationWarning` is printed from https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py#L104
The warning is: `DeprecationWarning: Testing an element's truth value will raise an exception in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.`

Traceback:
```
...
..\venv\Lib\site-packages\azure\core\tracing\decorator.py:78: in wrapper_use_tracer
    return func(*args, **kwargs)
..\venv\Lib\site-packages\azure\storage\blob\_container_client.py:541: in get_container_properties
    process_storage_error(error)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

storage_error = ResourceNotFoundError("Operation returned an invalid status 'The specified container does not exist.'")

    def process_storage_error(storage_error) -> NoReturn:  # pylint:disable=too-many-statements
        raise_error = HttpResponseError
        serialized = False
        if not storage_error.response:
            raise storage_error
        # If it is one of those three then it has been serialized prior by the generated layer.
        if isinstance(storage_error, (PartialBatchErrorException,
                                      ClientAuthenticationError, ResourceNotFoundError, ResourceExistsError)):
            serialized = True
        error_code = storage_error.response.headers.get('x-ms-error-code')
        error_message = storage_error.message
        additional_data = {}
        error_dict = {}
        try:
            error_body = ContentDecodePolicy.deserialize_from_http_generics(storage_error.response)
            try:
>               error_body = error_body or storage_error.response.reason
E               DeprecationWarning: Testing an element's truth value will raise an exception in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.

..\venv\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py:104: DeprecationWarning
```

**To Reproduce**

It looks like the warning is printed every time Azure responds with an error, for example:
1. create a container client (`BlobServiceClient.get_container_client`) for an unexisting container name
2. run `get_container_properties` on the client

Example error that triggered the warning in our case:
```
..\venv\Lib\site-packages\azure\storage\blob\_generated\operations\_container_operations.py:1078: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

status_code = 404
response = <RequestsTransportResponse: 404 The specified container does not exist., Content-Type: application/xml>
error_map = {304: <class 'azure.core.exceptions.ResourceNotModifiedError'>, 401: <class 'azure.core.exceptions.ClientAuthenticatio..., 404: <class 'azure.core.exceptions.ResourceNotFoundError'>, 409: <class 'azure.core.exceptions.ResourceExistsError'>}

    def map_error(
        status_code: int, response: _HttpResponseCommonAPI, error_map: Mapping[int, Type[HttpResponseError]]
    ) -> None:
        if not error_map:
            return
        error_type = error_map.get(status_code)
        if not error_type:
            return
        error = error_type(response=response)
>       raise error
E       azure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'The specified container does not exist.'
E       Content: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
E       <Error>
E         <Code>ContainerNotFound</Code>
E         <Message>The specified container does not exist.
E       RequestId:b763c7cc-3cb1-4398-929a-027d8d1b3808
E       Time:2023-11-08T21:29:13.454Z</Message>
E       </Error>

..\venv\Lib\site-packages\azure\core\exceptions.py:165: ResourceNotFoundError

```

**Expected behavior**
No warning printed.

**Screenshots**
Not applicable.

**Additional context**
Nothing to add.

**Comment by kristapratico** [comment]
@kfrydel thanks for your feedback. We'll investigate and get back to you as soon as possible.

**Comment by jalauzon-msft** [comment]
Hi @kfrydel Kamil, thanks for reaching out! we have not officially released support for Python 3.12 for the Storage libraries but are running our test pipelines in 3.12 and everything is working so the support is imminent. We will get this fixed up in the next release or two along with adding official support for Python 3.12 (mainly through a PyPi classifier).

If you encounter any other issues with Python 3.12, please reach out. Thanks!

**Comment by kfrydel** [comment]
Thank you!

**Comment by vincenttran-msft** [comment]
Hi @kfrydel Kamil, thanks again for bringing this to our attention. I have just put up a pull request that contains the fix for this `DeprecationWarning`, and will include this fix in all packages shortly. With that being said, upon successful merge, I will also close out the thread 😄 

Thanks!

**Comment by kfrydel** [comment]
@vincenttran-msft Thank you!

**Comment by kfrydel** [comment]
I do not understand why github-actions resolved it. The related PR has not yet been merged. So let's unresolve it:

/unresolve
