### ISSUE TITLE
Custom Vision: azure.identity credentials aren't supported

### ISSUE THREAD

**Issue by szulcmaciej** [Azure/azure-sdk-for-python#33094]
- **Package Name**: azure-cognitiveservices-vision-customvision
- **Package Version**: 3.1.0
- **Operating System**: Windows 10
- **Python Version**: 3.9

**Describe the bug**
I'm trying to authenticate to Custom Vision using an SPN.
When using `DefaultAzureCredential`, I get this error:
`AttributeError: 'DefaultAzureCredential' object has no attribute 'signed_session'.`

I also tried using `ServicePrincipalCredentials` from `msrestazure.azure_active_directory`, but it fails with:
`azure.cognitiveservices.vision.customvision.training.models._models_py3.CustomVisionErrorException: Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.`

The roles assigned to the SPN are:
* Cognitive Services Contributor
* Cognitive Services Custom Vision Contributor
* Cognitive Services User

**To Reproduce**
```
from azure.identity import DefaultAzureCredential
from azure.cognitiveservices.vision.customvision.training import CustomVisionTrainingClient

endpoint = os.getenv('CUSTOM_VISION_TRAINING_ENDPOINT')

token_credential = DefaultAzureCredential()
trainer = CustomVisionTrainingClient(endpoint, token_credential)

# Create a new project
print ("Creating project...")
project_name = uuid.uuid4()
project = trainer.create_project(project_name)
```

ServicePrincipalCredentials
```
from msrestazure.azure_active_directory import ServicePrincipalCredentials
from azure.cognitiveservices.vision.customvision.training import CustomVisionTrainingClient

client_id = os.getenv('AZURE_CLIENT_ID')
client_secret = os.getenv('AZURE_CLIENT_SECRET')
tenant_id = os.getenv('AZURE_TENANT_ID')
endpoint = os.getenv('CUSTOM_VISION_TRAINING_ENDPOINT')

spn_credential = ServicePrincipalCredentials(client_id, client_secret, tenant=tenant_id)
trainer = CustomVisionTrainingClient(endpoint, spn_credential)

# Create a new project
print ("Creating project...")
project_name = uuid.uuid4()
project = trainer.create_project(project_name)
```

**Expected behavior**
`azure.identity` credentials classes working with Custom Vision.

**Additional context**
Due to my client's policy, I cannot use key-based authentication. SPNs are required by the project architect. I cannot find a way to use SPNs with Custom Vision. Even if there are no plans to update the package, any tips on how to acheive that would be appreciated :)

**Comment by szulcmaciej** [comment]
I found a workaround:
```
token = token_credential.get_token('https://cognitiveservices.azure.com/.default').token
api_key_credentials = ApiKeyCredentials(in_headers={"Authorization": f'Bearer {token}'})
trainer = CustomVisionTrainingClient(endpoint, api_key_credentials)
```
Still, it would be nice if `azure.identity` credentials just worked ;)

**Comment by kristapratico** [comment]
Thanks for your detailed issue @szulcmaciej. @xiangyan99 @pvaneck - is there a workaround for using azure.identity credentials with track 1 libraries?

**Comment by xiangyan99** [comment]
Thanks for the feedback, did you have a chance to read

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md?

Does it help?
