### ISSUE TITLE
get_deployment_by_name() does not show input endpoints

### ISSUE THREAD

**Issue by techhat** [Azure/azure-sdk-for-python#331]
I have the following piece of code:
```
import azure.servicemanagement
client = azure.servicemanagement.ServiceManagementService(subscription_id, certificate_path, management_host)
data = client.get_deployment_by_name(
    service_name=service_name,
    deployment_name=deployment_name',
)
```
When I execute this code, `data.input_endpoint_list` shows up as `None`. However, if I dump out the XML that is being returned, I can see that I have three input endpoints listed.

This seems to be problematic in other areas of the code too. For instance, listing hosted services shows no deployments, even though I do have deployments inside my hosted services.

**Comment by huguesv** [comment]
Hi techhat,

I can see my input endpoints when I look inside each role, like this:
```
deployment.role_list[0].configuration_sets[0].input_endpoints[0].port
deployment.role_list[0].configuration_sets[0].input_endpoints[0].protocol
```

The `input_endpoint_list` at the root is probably used in the context of a different REST API that shares the same data model class, or maybe it's obsolete now.  I'll have to investigate.  There is no XML for input endpoints at that level (off the root) in the response that I'm looking at.

**Comment by huguesv** [comment]
Please reopen if you still need help.
