### ISSUE TITLE
Error when deleting a container: The specified container does not exist but container.deleted is None

### ISSUE THREAD

**Issue by phosseini** [Azure/azure-sdk-for-python#33110]
I'm trying to delete containers and everything is going pretty well. In particular, I first check and see if `container.deleted` is `None` then I make a call using `.delete_container`. The reason for checking first is that I just simply want to skip a container if it's already deleted and don't make any call to the client. The thing is for some containers, even though the `container.deleted` is `None` (meaning the container is not deleted yet and should exist?), when I try to delete the container I get the following error: **The specified container does not exist.**:

```
The specified container does not exist.
RequestId:<the-request-id>
Time:2023-11-10T23:30:20.0036591Z
ErrorCode:ContainerNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:<the-request-id>
Time:2023-11-10T23:30:20.0036591Z</Message></Error>
```

I wonder if there's any other way than checking `container.deleted` to see if the container does or does not exist before making the call? The idea is to make this deletion process a bit faster, specially when dealing with a large number of deletions, and there's no point in making a call to the client if a container has been already deleted.

**Comment by kristapratico** [comment]
@phosseini - Thanks for your feedback. This repo houses many different client libraries for azure, is this issue about azure-storage-blob? Would you mind filling out the issue template information so we can tag the right people to help?

Package Name:
Package Version:
Operating System:
Python Version:

Preemptively tagging @vincenttran-msft @jalauzon-msft for storage questions.
