### ISSUE TITLE
This line does not work in the latest "azure-search-documents"

### ISSUE THREAD

**Issue by bogazci** [Azure/azure-sdk-for-python#33120]
https://github.com/Azure/azure-sdk-for-python/blob/306e13816fec0452427a0e6c8add386a8e41e656/sdk/search/azure-search-documents/samples/sample_vector_search.py#L28C1-L29C1

`I am receiving "ImportError: cannot import name 'VectorizedQuery' from 'azure.search.documents.indexes' (/usr/local/lib/python3.10/dist-packages/azure/search/documents/indexes/__init__.py)"
`
when using `!pip install azure-search-documents --pre --upgrade`.

**Comment by pvaneck** [comment]
Hey, @bogazci. In your script, you have `from azure.search.documents.models import VectorizedQuery` like in the sample? Based on that error message, seems like `VectorizedQuery` is being imported from the incorrect location (i.e. `from azure.search.documents.index import VectorizedQuery`)

**Comment by EvanYang0527** [comment]
Hi @pvaneck I am having the same issue. I copied code from the example.
`from azure.search.documents.models import VectorizedQuery`
