### ISSUE TITLE
Azure Purview eDiscovery Premium/Standard API support

### ISSUE THREAD

**Issue by arunavdev89** [Azure/azure-sdk-for-python#33121]
Azure Purview [eDiscovery APIs](https://devblogs.microsoft.com/microsoft365dev/ediscovery-api-for-microsoft-graph-is-now-generally-available/) became GA in 2022. Is there any plan to make the APIs available through Python SDK?

**Comment by l0lawrence** [comment]
Hi @arunavdev89 thanks for the feedback, we will get back to you asap.

**Comment by pvaneck** [comment]
Hey, @arunavdev89. Looks like this is a MS Graph API for which the corresponding SDK is maintained here: https://github.com/microsoftgraph/msgraph-sdk-python.

I would take a look at available APIs and potentially raising an issue there.
