### ISSUE TITLE
Listing Blobs does not retrieve expected metadata

### ISSUE THREAD

**Issue by JCF-SES** [Azure/azure-sdk-for-python#33154]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.19.0
- **Operating System**:Windows
- **Python Version**: 3.11.0

**Describe the bug**
Erratic metadata behavior when listing blobs. 
Listed blobs metadata attribute are always empty (at least for this and other tests I have executed).
The attribute is there, but never populated. Getting the properties through the blob client shows the expected metadata.

**To Reproduce**

```python
from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobProperties, ContainerClient

file_name = "name of fiel.ext"
file_content = random_read_bytes_function(file_name)

# reference to empty container
client: ContainerClient = ContainerClient.from_container_url(container_url="url-to-sta-container", credential=DefaultAzureCredential())

client.upload_blob(name=file.name, data=file_content, metadata={'flag1': 'flag1'})
blobs = list(client.list_blobs())
print(blobs)
```
>[{'name': file_name, 'container': container_name, 'snapshot': None, 'version_id': None, 'is_current_version': None, 'blob_type': <BlobType.BLOCKBLOB: 'BlockBlob'>, 'metadata': {},.....}]

This is unexpected behavior since the metadata was assigned correctly and it is displayed in the portal.
To proof this:

```python
print(client.get_blob_client(blobs[0].name).get_blob_properties())
```
>{'name': file_name, 'container': container_name, 'snapshot': None, 'version_id': None, 'is_current_version': None, 'blob_type': <BlobType.BLOCKBLOB: 'BlockBlob'>, 'metadata': {'flag1': 'flag1'},......}

Which shows the expected metadata.

Behavior is also persistent when using `from azure.storage.blob.aio import ContainerClient`

**Expected behavior**
Metadata to be available when listing blob, not only when getting properties through BlobClient.

**Additional context**
Please let me know if this is the expected behavior or not. Having an empty argument when listing blob is misleading and causes confusions when this metadata is needed.

**Comment by jalauzon-msft** [comment]
Hi @JCF-SES, to get metadata to be returned when calling `list_blobs` you have to specify that you want metadata to be included in your request using the `include` parameter.
https://github.com/Azure/azure-sdk-for-python/blob/4fe0646eea104aa5bcb36b1cfeec8af97213af36/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L804-L807

So, something like this:
```py
blobs = list(client.list_blobs(include=['metadata']))
```

This aligns with the `include` parameter of the [REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=microsoft-entra-id#uri-parameters) and tells the service to include metadata (and other things) in the response.

Give that a try and that should resolve your issue. Thanks.
