### ISSUE TITLE
hide Git credential in Azure machine learning

### ISSUE THREAD

**Issue by yuerlong** [Azure/azure-sdk-for-python#33153]
**Is your feature request related to a problem? Please describe.**
When the job is submitted in command type by python SDK v2, the AML job page will show  "Git repository" in properties. If the job is submitted from a folder under a git repo with git config "https://username:token@xxxx", the string  "username:token" will also show at the "Git repository" column of AML job page

**Describe the solution you'd like**
hide the token and username

**Describe alternatives you've considered**
Use a password-protected SSH key.

**Comment by l0lawrence** [comment]
Hi @yuerlong thank you for the feedback, going to direct this question to @azureml-github to address asap.
