### ISSUE TITLE
`azure.monitor.opentelemetry.exporter.AzureMonitorMetricExporter.export` ignores `opentelemetry.Resource`

### ISSUE THREAD

**Issue by stoney95** [Azure/azure-sdk-for-python#33176]
**Is your feature request related to a problem? Please describe.**
I would like to store metrics with **custom dimensions (custom properties)**. I know that I can add them to every metric call: 

```python
meter = metrics.get_metric_provider().get_meter("some name")
counter = meter.create_counter("some other name")

counter.add(1, {"custom_dim_1": "value 1", "custom_dim_2": "value 2"})
```

We have some dimensions that need to be present for every metric. E.g. we run ML pipelines and would like to store the pipeline id to later visualize metrics per pipeline.
This is tedious and error prone, as we need to assure that every metric call includes the required custom dimensions. 

**Describe the solution you'd like**
I would like to define custom dimensions that are automatically stored with every metric. From my understanding the opentelemetry concept for that is [the Resource](https://opentelemetry.io/docs/concepts/resources/). The [documentation of `opentelemetry.sdk.resources`](https://opentelemetry-python.readthedocs.io/en/latest/sdk/resources.html#module-opentelemetry.sdk.resources) further specifies:

> The [Resource](https://opentelemetry-python.readthedocs.io/en/latest/sdk/resources.html#opentelemetry.sdk.resources.Resource) passed to a provider is available to the exporter, which can send on this information as it sees fit.

The `AzureMonitorMetricExporter` only uses some of the conventional resource names (e.g. `service.name`), but ignores custom resource attributes. 

`_convert_point_to_envelope` is used inside `AzureMonitorMetricExporter.export´. [This section](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py#L188-L201) of `_convert_point_to_envelope` sets the properties of the metric. It only uses `point.attributes`. 

I am not aware of opentelemetry internals. I think one option would be that here the attributes of the resource are also taken into account. 

**Describe alternatives you've considered**
I am not aware of an alternative solution to my request. In case there is a different way, I am happy to use it.

**Comment by lzchen** [comment]
This would be a feature request as we have not implemented this in the exporters. Original [issue](https://github.com/Azure/azure-sdk-for-python/issues/24689)

**Comment by stoney95** [comment]
@lzchen I checked the mentioned issue. Which is not active. Is there a way to push this topic?

**Comment by lzchen** [comment]
@stoney95 

We are in discussion to develop an opt-in mechanism to autopopulate custom dimensions from Resouce attributes.

**Comment by stoney95** [comment]
@lzchen, thanks for providing the hack. As it is not recommended and would require to setup all telemetry exporters manually and without the distro, I will stick to adding the custom dimensions to each metric call. Of course, this makes me look forward to you implementing "an opt-in mechanism to autopopulate custom dimensions from Resource attributes."

Could you also provide an example how I can use the `Processor` for adding custom dimensions to logs? I am currently (mis-)using a `logging.Filter` for that.

**Comment by lzchen** [comment]
@stoney95 

You would do something similar as above except override [emit](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/export/__init__.py#L349) on the `BatchLogRecordProcessor` instead.
