### ISSUE TITLE
StorageStringDownloader.readinto() fails when encoding specified.

### ISSUE THREAD

**Issue by abridgland** [Azure/azure-sdk-for-python#33198]
When calling `download_blob` with `encoding='utf-8'` (or any non-None value) the resulting downloader, typed `StorageStringDownloader[str]`, fails when calling `readinto` with an `io.StringIO` stream, despite that being the correct type according to the type singature of `readinto` (`def readinto(self, stream: IO[T]) -> int` where `T` is `str` for this case).

I believe this is because the private `self._current_content` field is always `bytes` so in the following code it will need to be decoded using `self._encoding` before writing to `stream`.

https://github.com/Azure/azure-sdk-for-python/blob/60b273f26bc39dded38f3dbff3daca9d94aa32a3/sdk/storage/azure-storage-blob/azure/storage/blob/_download.py#L732-L733

Error:
```
>>> str_stream = io.StringIO()
>>> container_client.download_blob(blob_path, encoding='utf-8').readinto(str_stream)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 733, in readinto
    stream.write(content)
TypeError: string argument expected, got 'bytes'
```

**Comment by l0lawrence** [comment]
Hi @abridgland thanks for the feedback, we will get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @abridgland Alex, thanks for the detailed report! I believe you are correct, and this is a bug with `readinto`. We will look into getting this fixed as soon as we are able.

**Comment by vincenttran-msft** [comment]
Hi @abridgland Alex, thanks again for your inquiry. After some investigating, this actually is just a case of a mistyped argument. I have gone ahead and attached a pull request that resolves this issue, and so this issue will be closed alongside the successful merge of that PR. Thanks again for bringing this to our attention!
