### ISSUE TITLE
How can I retrieve/compute an X509 certificate's thumbprint in Python and then use it for accessing Service Management APIs from Python SDK?

### ISSUE THREAD

**Issue by Priyanka-Ambekar** [Azure/azure-sdk-for-python#332]
Hello,

I am using Azure Python SDK to perform calls to ServiceManagement APIs.

I have a .publishsettings file generated for my account which includes an encoded version of my X509 certificate and all of my subscription IDs.

How can I retrieve/compute an X509 certificate's thumbprint in Python?

Following is the code snippet that helps us do it in .Net.

Is there a similar approach to do it in Python?

var publishSettingsFile = @"C:\temp\CORP DPE Account-11-16-2011-credentials.publishsettings";

XDocument xdoc = XDocument.Load(publishSettingsFile);

var managementCertbase64string = xdoc.Descendants("PublishProfile").Single().Attribute("ManagementCertificate").Value;

var importedCert = new X509Certificate2(Convert.FromBase64String(managementCertbase64string));

thumbprint = importedCert.Thumbprint;

Once I have the thumbprint, how can I use that thumbprint to access Service Management APIs from Python SDK?

Thank you in Advance!

**Comment by huguesv** [comment]
Hi!

Please have a look at these:

To get the certificate out of publish settings:
http://azure-sdk-for-python.readthedocs.org/en/latest/servicemanagement.html#using-the-azure-publishsettings-certificate

To initialize service management with the certificate:
http://azure-sdk-for-python.readthedocs.org/en/latest/servicemanagement.html#initialization

**Comment by Priyanka-Ambekar** [comment]
Works perfectly fine !  Thanks :)
