### ISSUE TITLE
Remove `MacOS X` support tag from PyPI page for azure-ai-vision

### ISSUE THREAD

**Issue by hakontonne** [Azure/azure-sdk-for-python#33209]
- **Package Name**: azure-ai-vision
- **Package Version**: azure-ai-vision
- **Operating System**: MacOS X
- **Python Version**: Not relevant

**Describe the bug**
The PyPi page of azure-ai-vision has MacOS X listed as supported operating systems, but is not actually supported. 
If a user tries to follow the install instructions on PyPI (`pip install azure-ai-vision`), an error message appears. 

Either add MacOS X support or remove the tag to avoid confusion. 

**To Reproduce**
1. Go to https://pypi.org/project/azure-ai-vision/ and see the tag under "Classifier" and "Operating System"

**Expected behavior**
Either the tag removed or add MacOS X support 

![azure](https://github.com/Azure/azure-sdk-for-python/assets/21296540/0d9cc40a-beed-4215-b98f-f1736ba48669)

**Comment by l0lawrence** [comment]
Thanks for the feedback, tagging @BrianMouncer to help answer.
