### ISSUE TITLE
error creating azure function with azure-mgmt-web==0.40.0

### ISSUE THREAD

**Issue by vishleshpatel** [Azure/azure-sdk-for-python#3324]
I am receiving this error traceback while creating azure function from the below code:

           test:     create_function: 138 -    INFO - adding appsetting to site to make it a function
           test:     create_function: 157 -   ERROR - __init__() takes exactly 1 argument (3 given)
Traceback (most recent call last):
  File "test.py", line 139, in create_function
    site_config.app_settings.append(NameValuePair('AzureWebJobsStorage', con_string))
TypeError: __init__() takes exactly 1 argument (3 given)

Code:

```
def create_function(self):
            functionapp_def = Site(location=self.location, site_config=site_config)
            con_string = self.validate_and_get_connection_string(rg, storage_account_name)
            # adding appsetting to site to make it a function
            logger.info("adding appsetting to site to make it a function")
            site_config.app_settings.append(NameValuePair('AzureWebJobsStorage', con_string))
            site_config.app_settings.append(NameValuePair('AzureWebJobsDashboard', con_string))
            site_config.app_settings.append(NameValuePair('WEBSITE_NODE_DEFAULT_VERSION', '6.5.0'))
            if consumption_plan_location is None:
                site_config.always_on = True
            else:
                site_config.app_settings.append(NameValuePair('WEBSITE_CONTENTAZUREFILECONNECTIONSTRING',
                                                              con_string))
                site_config.app_settings.append(NameValuePair('WEBSITE_CONTENTSHARE', name.lower()))

            poller = self.client.web_apps.create_or_update(rg, name, functionapp_def)
            functionapp = poller.result()
            return functionapp
```

<cba5f440b6bf73-06acb48d93f01066d96bd3 autoscaler]# pip freeze| grep azure

**Comment by lmazuel** [comment]
Hi @vishleshpatel 
Please see in the ChangeLog published on PyPI that positional arguments are not allowed anymore:
https://pypi.org/project/azure-mgmt-web/

This `NameValuePair('AzureWebJobsStorage', con_string)` needs to be replaced by this `NameValuePair(name='AzureWebJobsStorage', value=con_string)`

Thank you,

**Comment by vishleshpatel** [comment]
Thanks @lmazuel  for the quick response. That should work for sure. 

in the meantime, I settled it up with : 
pair = NameValuePair()
pair.name, pair.value = 'testname', 'testvalue'

about the same thing.
