### ISSUE TITLE
Add Listening and sending from/to Azure Relay Hybrid Connections

### ISSUE THREAD

**Issue by swingtempo** [Azure/azure-sdk-for-python#3325]
Maybe I'm missing something - I couldn't find any docs.  I saw that there are APIs added to manage Azure relays, but I couldn't find APIs or docs on how to actually communicate via an Azure relay.  For example the node js SDK has APIs like:
https.createRelayListenUri(ns, path);
https.createRelayedServer()

that can send and receive via the hybrid connection.  i.e. all you need are:
const ns = "{RelayNamespace}";
const path = "{HybridConnectionName}";
const keyrule = "{SASKeyName}";
const key = "{SASKeyValue}";

and you can connect.  I couldn't find anything like that in the Python SDK.  If it exists, can you point me to the APIs (and create an example)?  Or if not, can you add them?

**Comment by lmazuel** [comment]
@v-Ajnava could you provide some help here? Thank you!

**Comment by v-Ajnava** [comment]
@jayongg , we don't have Runtime Python SDK for Relay, but we do have  sample for Relay server in Python which supports HTTP to send 

Sample Link: https://github.com/azure/azure-relay/issues/28

**Comment by jayongg** [comment]
Thanks - may I get this registered as a feature request?

**Comment by jayongg** [comment]
@v-Ajnava

**Comment by jayongg** [comment]
how do I assign this to someone?

**Comment by jfggdl** [comment]
@swingtempo, thanks for creating this issue and letting us know your interest in a Python SDK. We have created an internal tracking item and according to user interest we will consider implementing a Python SDK for Azure Relay.

I will be closing this issue, but please feel free to reopen it if you have additional questions.

**Comment by dlstucki** [comment]
I added a note to the internal item tracking this feature that it got another vote.

**Comment by bleuknight** [comment]
I would like to also emphasize the need for this
