### ISSUE TITLE
VMSS example doesn't work as is

### ISSUE THREAD

**Issue by ntabris** [Azure/azure-sdk-for-python#33268]
- **Package Name**: `azure-mgmt-compute`
- **Package Version**: `30.3.0`
- **Operating System**: macOS
- **Python Version**: `3.11.6`

There seems to be a mismatch between the VMSS endpoint and the autogenerated API docs such that https://github.com/Azure/azure-sdk-for-python/blob/0e147ccc6470d431db6770a36b92faf63c3b8ee4/sdk/compute/azure-mgmt-compute/generated_samples/virtual_machine_scale_set_examples/virtual_machine_scale_set_create_with_priority_mix_policy.py doesn't run.

When I try to run that example (after filling in placeholders for subscription, resource group, etc), I get this error: `Required parameter 'platformFaultDomainCount' is missing (null).`

Then when I add `"platformFaultDomainCount": 1` (under `properties`) I get a new error:

```
Code: NetworkApiVersionMustBeSpecifiedWithNetworkInterfaceConfigurations
Message: Network api version in network profile of virtual machine /subscriptions/REDACTED_SUB_ID/resourceGroups/REDACTED_RG/providers/Microsoft.Compute/virtualMachines/exampless_caedac91 must be specified if network interface configurations are specified.
```

Eventually I figured out I needed to add `"networkApiVersion": "2020-11-01"` under `networkProfile` (see [my comment here](https://learn.microsoft.com/en-us/answers/questions/1178711/create-a-vmss-using-python-sdk?page=1&orderby=Helpful&comment=answer-1180972#newest-answer-comment)) and now I can successfully make the VMSS.

**Comment by ChenxiJiang333** [comment]
@ntabris 
Thanks for pointing this out! 
We have a PR open to fix this and will auto-close this issue when the PR get merged.

**Comment by ChenxiJiang333** [comment]
Close for the [example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/generated_samples/virtual_machine_scale_set_examples/virtual_machine_scale_set_create_with_priority_mix_policy.py) has been updated.
