### ISSUE TITLE
max_item_count

### ISSUE THREAD

**Issue by paddygoat** [Azure/azure-sdk-for-python#33266]
`def read_items(container):
    print('\nReading all items in a container:\n')

    # NOTE: Use MaxItemCount on Options to control how many items come back per trip to the server
    #       Important to handle throttles whenever you are doing operations such as this that might
    #       result in a 429 (throttled request)
    item_list = list(container.read_all_items(max_item_count=1))

    print('Found {0} items'.format(item_list.__len__()))`

...... returns all rows in database, not 1 row as would be expected.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you help to provide the information which Azure service do you use?
