### ISSUE TITLE
How to read form-data within Azure ML endpoint run function?

### ISSUE THREAD

**Issue by abhishekperambai** [Azure/azure-sdk-for-python#33260]
I'm trying to send form-data from postman to the ML endpoint in the backend which uses the Azure python SDK v1.  Below is the code that I'm using to read the request from postman in the run function in my entry /scoring script.

```
@rawhttp
def run(data):
    try:
        aml_request = AMLRequest(data)
        file_data = aml_request.get_data()
        file_type = aml_request.get_header("file_type")
        return {"input_structure":file_data.read(),
               "file_type":file_type}
    except Exception as e:
        error = {"error": str(e)}
        return json.dumps(error)
```

The above function is just a dummy script to see how the endpoint returns the input structure being sent to the it. Apparently below is the error that I get when I send the post request in POSTMAN.

**_

> "{\"error\": \"AMLRequest.__init__() takes 1 positional argument but 2 were given\"}"

_**

Furthermore, if I directly read the request and print it without the AMLRequest class, it prints an **_empty string_** which according to me means that the data is not being passed from postman to the backend endpoint.

PFB the screenshot of the postman request

![image](https://github.com/Azure/azure-sdk-for-python/assets/16097379/231b650d-1989-405c-8dc8-fe961680a784)

The above screenshot has the file upload and file_type key indicating the extension of the file.

Can someone help me on how to read the request in the run function when the request sent is form-data from postman?

**Comment by Ramya-ML18** [comment]
Hi @abhishekperambai can you try to send raw from postman.
![image](https://github.com/Azure/azure-sdk-for-python/assets/142423093/e60679df-d784-495c-a1c5-b8a807790b62)

**Comment by abhishekperambai** [comment]
> Hi @abhishekperambai can you try to send raw from postman. When I am using the form-data its showing the error. ![image](https://private-user-images.githubusercontent.com/142423093/303635448-e60679df-d784-495c-a1c5-b8a807790b62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTA4OTksIm5iZiI6MTcwOTA5MDU5OSwicGF0aCI6Ii8xNDI0MjMwOTMvMzAzNjM1NDQ4LWU2MDY3OWRmLWQ3ODQtNDk1Yy1hMWM1LWI4YTgwNzc5MGI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwMzIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTgwY2JlNTZmMGVjOTdmNGRhNmE3NmQyODRjODE5MjliNzg3YTNkYmRmMDVhZjQ3MTM2OGFkMjI2OGIwMjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WOM3gO2Aijcu7A1OIbE9e9bF4HjzKhzgTC1TgA0l8YQ)



Hi Ramya,

My requirement is to send it as an attachment from the front-end as this endpoint will be integrated with UI. 

Is there a way to do this?

**Comment by Ramya-ML18** [comment]
Hi Abhishek
can you try to take the data from the python file and add the context to read the file and send from the postman.

![image](https://github.com/Azure/azure-sdk-for-python/assets/142423093/f1b2c981-4fbf-4a8b-af83-170ec66ffdbf)

**Comment by isaudagar** [comment]
By mistake clicked reopen.
