### ISSUE TITLE
Form recognizer not working in linux machine

### ISSUE THREAD

**Issue by venkateshkumar** [Azure/azure-sdk-for-python#33276]
- **Package Name**: azure-ai-formrecognizer
- **Package Version**: 3.2.0
- **Operating System**: RHEL Linux
- **Python Version**: 3.6.0

**Describe the bug**

Getting ModuleNotFoundError: No module named 'azure.ai.formrecognizer' but there are libraries found.

Displaying the module already present
pip show azure.ai.formrecognizer
Name: azure-ai-formrecognizer
Version: 3.2.0
Summary: Microsoft Azure Form Recognizer Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /usr/local/lib/python3.8/site-packages
Requires: azure-common, azure-core, msrest, typing-extensions

**To Reproduce**
1. Run the library with following 

**Expected behavior**

**Screenshots**

**Additional context**
Is there any Python version is required to upgrade ?

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment]
Hi @venkateshkumar , thanks for contacting! It's expected to use python 3.7+ since version 3.2.0b6([CHANGELOG](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md#other-changes-3)).

**Comment by sergiorfoliveira** [comment]
The issue persists.
