### ISSUE TITLE
no matches found: azure-ai-generative[index,evaluate,promptflow]

### ISSUE THREAD

**Issue by CarlosUrteaga** [Azure/azure-sdk-for-python#33279]
- **Package Name**:  azure-ai-generative
- **Package Version**: last 
- **Operating System**: Mac
- **Python Version**: 3.7

**Describe the bug**
no matches found: azure-ai-generative[index,evaluate,promptflow] after try to install in a fresh conda enviroment using python 3.7 and 3.9

**To Reproduce**
1. open terminal
2. create a environment  with python 3.7 or python 3.9 [conda create -n RAG-2 python=3.7]
3. activate the environment conda activate RAG-2
4. % pip install azure-ai-generative[index,evaluate,promptflow]

**Expected behavior**
installation of the evaluate to  import correctly 
from azure.ai.generative import evaluate

**Screenshots**
![Screenshot 2023-11-22 at 11 58 52 AM](https://github.com/Azure/azure-sdk-for-python/assets/3679087/4cd09464-702e-42ae-bd29-17096e8141ce)

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Did you try to install azure-ai-generative from conda forge?

Because the package is still in preview, we have not shipped azure-ai-generative onto our conda repo yet.

https://anaconda.org/microsoft

**Comment by devanshithakar12** [comment]
Hi @xiangyan99 I am having issues running `from azure.ai.generative.evaluate import evaluate` . I am getting a **ModuleNotFoundError: No module named 'azure.ai.generative'**. Using Python 3.10 in AML Notebooks. 
<img width="1535" alt="Screenshot 2024-03-10 212741" src="https://github.com/Azure/azure-sdk-for-python/assets/33441411/04aff2fb-5ae8-4472-9262-06a8c04da376">
