### ISSUE TITLE
Resource properties not returning

### ISSUE THREAD

**Issue by cnadler-MSFT** [Azure/azure-sdk-for-python#33277]
Hello!

I'm trying to return the resource properties of an Azure Arc object, specifically the status and it is returning none with the following code:

`import os
from azure.identity import AzureCliCredential
from azure.mgmt.resource import ResourceManagementClient
import re
cred = AzureCliCredential()
sub_id = ""

resource_client = ResourceManagementClient(cred, sub_id)

for rg in resource_client.resource_groups.list():
    try:
        
        resource_list = resource_client.resources.list_by_resource_group(rg.name, expand="createdTime,changedTime,properties")
        column_width =36
        print(f"\n{rg.name}")
        print("Resource".ljust(column_width) + "Type".ljust(column_width) + "Create date".ljust(column_width) + "Change date".ljust(column_width) + "Properties".ljust(column_width))
        print("-" * (column_width * 5))

        for resource in list(resource_list):
            if resource.type == "Microsoft.HybridCompute/machines":
                print(f"{resource.name:<{column_width}}{resource.type:<{column_width}}"
                    f"{str(resource.created_time):<{column_width}}{str(resource.changed_time):<{column_width}}{str(resource.properties):<{column_width}}")
        
    except Exception as e:
        print(e)`

<img width="714" alt="Screenshot 2023-11-22 072902" src="https://github.com/Azure/azure-sdk-for-python/assets/52507427/a881b7c2-16cb-4644-977c-9091c07e4a43">

I can return the value with Azure CLI no problem:

![MicrosoftTeams-image (6)](https://github.com/Azure/azure-sdk-for-python/assets/52507427/df6269e1-58c8-46ec-8809-1c03ef6985e7)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi, @cnadler-MSFT 
To get properties of an Azure Arc machine, it's suggested to try this [sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/hybridcompute/azure-mgmt-hybridcompute/generated_samples/machine/machines_list_by_subscription.py).
