### ISSUE TITLE
Include APi Version 2023-10-31 (Preview) to Azure Document Intelligence Python SDK

### ISSUE THREAD

**Issue by kschober123** [Azure/azure-sdk-for-python#33278]
We are working with the Azure Document Intelligence Python SDK (class: DocumentAnalysisClient). There is a hard check for the API version which does not allow for changing the version to 2023-10-31 (Preview). We have use cases where the latest preview version performs significantly better than the currently supported ones. Removing the hard check would benefit the usability of the package. Optionally you could include a warning if a version is used that is not GA as off now.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Unfortunately, our SDK has not supported API version 2023-10-31 yet.

@YalinLi0312 do you know when we plan to add the new API version support?

**Comment by YalinLi0312** [comment]
Hi @kschober123 , the API version `2023-10-31-preview` is supported in a rebranding package [azure-ai-documentintelligence](https://pypi.org/project/azure-ai-documentintelligence/). We are not planning to support any new API in azure-ai-formrecognizer.

Additionally, there are some breaking changes comparing with the latest API version `2023-07-31` used in azure-ai-formrecognizer. We are working on updating the changelog to include the breaking change details.
