### ISSUE TITLE
OpenTelemetry Python - Azure Functions hangs when configure_azure_monitor is present

### ISSUE THREAD

**Issue by mathieuisabel** [Azure/azure-sdk-for-python#33289]
- **Package Name**:  azure-monitor-opentelemetry
- **Package Version**:  1.1.0
- **Operating System**: Windows 11
- **Python Version**:  3.10.11
- **Function Runtime**: 4.21.1.20667

**Describe the bug**
Azure Functions won't start when the following call is present:

configure_azure_monitor(
    connection_string=os.getenv('APPLICATIONINSIGHTS_CONNECTION_STRING'),
    disable_offline_storage=True
)

[2023-11-23T14:15:22.275Z] Requesting metadata from worker failed.
[2023-11-23T14:15:22.277Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.

**To Reproduce**
1. 

**Expected behavior**
Functions app starts normally.

**Screenshots**

**Additional context**
Here's how it's setup in the Functions App. I'm not certain this is correct. The APPLICATIONINSIGHTS_CONNECTION_STRING is defined in local.settings.json

# App Insights
root_logger = logging.getLogger()
for handler in root_logger.handlers[:]:
    root_logger.removeHandler(handler)

from azure.monitor.opentelemetry import configure_azure_monitor

configure_azure_monitor(
    connection_string=os.getenv('APPLICATIONINSIGHTS_CONNECTION_STRING'),
    disable_offline_storage=True
)

**Comment by kurt-mueller-osumc** [comment]
This happens to me. `configure_azure_monitor` will prevent my azure functions app from booting (Azure functions will simply hang). Commenting it out allows my app to boot.

**Comment by schoi80** [comment]
I have the same issue.
I was able to resolve by locking `opentelemetry-api = "1.20"`

**Comment by mrostan** [comment]
I was experiencing the same issue, but only when the Azure Function was configured to use a vnet, the issue was fixed upgrading `azure-monitor-opentelemetry` to `1.2.0` (released Jan 19th)

**Comment by xiangyan99** [comment]
Given the PR was merged, close the issue as fixed.
