### ISSUE TITLE
Change data type of the 'enabled' parameter in the DeploymentCollection class from str to bool

### ISSUE THREAD

**Issue by sraza-onshape** [Azure/azure-sdk-for-python#33293]
**Is your feature request related to a problem? Please describe.**
I feel that initializing objects of the [`DeploymentCollection`](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.deploymentcollection?view=azure-python) class using the Python SDK has unnecessary ambiguity. When setting the `enabled` parameter, I got confused earlier today regarding if I should pass `"true"` or `"True"`. The [docs](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.deploymentcollection?view=azure-python) don't offer useful explanation/examples that it's supposed to be the former. 

**Describe the solution you'd like**
Is there any way we could change the type of this parameter to be a `bool` instead of `str`? 

**Describe alternatives you've considered**
- We can replace the type of the parameter with an `enum` - so it at least constrains the number of "correct" values one can pass in as an argument to some degree
- make the argument case insensitive - so that either "true" or "True" works

**Comment by nemanjarajic** [comment]
Hi @sraza-onshape, thanks for raising this issue. I have a fix going out for this. The plan is to make the argument case insensitive because changing it to a bool would be a breaking change for other customers.

**Comment by nemanjarajic** [comment]
https://github.com/Azure/azure-sdk-for-python/commit/1f88d675782020eb7e092f94fb58a3d8130d5ccf
