### ISSUE TITLE
Ref docs issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-python#33291]
Error:

> ##[error]Run-WithWarningFilter : <Matched Error>: C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\azure\ai\ml\ope
> rations\_batch_deployment_operations.py:docstring of 
> azure.ai.ml.operations._batch_deployment_operations.BatchDeploymentOperations:1: ERROR: Error in "literalinclude" 
> directive:
> At D:\a\_work\1\s\python\build.ps1:150 char:13
>              Run-WithWarningFilter -Command $sphinxBuildPath -Paramete ...
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Run-WithWarningFilter
>  
> 
> WARNING: <Plain Warning>: invalid option block.
> WARNING: <Plain Warning>: System.Management.Automation.RemoteException
> WARNING: <Plain Warning>: .. literalinclude:: ../samples/ml_samples_workspace.py
> WARNING: <Plain Warning>:     :start-after: [START outbound_rule_begin_create]
> WARNING: <Plain Warning>:     :end-before: [END outbound_rule_begin_create]
> WARNING: <Plain Warning>:     :language: python
> WARNING: <Plain Warning>:     :dedent: 8
> WARNING: <Plain Warning>:     :caption: Create an FQDN outbound rule for a workspace with the given name,
> WARNING: <Plain Warning>:     similar can be done for PrivateEndpointDestination or ServiceTagDestination.

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=399623&view=results

@danieljurek for notification.

**Comment by diondrapeck** [comment]
@faynef - ack'ed. Thanks for noting this. We already have [a PR](https://github.com/Azure/azure-sdk-for-python/pull/33248) in the works to fix this and all other sphinx issues in the ml package and we'll be subsequently turning on strict-sphinx to prevent these errors from being merged going forward.
