### ISSUE TITLE
Unable to connect to Azurite with DefaultCredential

### ISSUE THREAD

**Issue by phoebusm** [Azure/azure-sdk-for-python#33297]
- **Package Name**: 
azure-identity
- **Package Version**:
1.15.0 
- **Operating System**:
linux
- **Python Version**: 
3.8

**Describe the bug**
Fail to connect to Azurite with `DefaultCredential`
According to https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#azure-blob-storage and https://github.com/Azure/Azurite/issues/2303#issuecomment-1825058477, it is doable with `.net` library.

**To Reproduce**
python:
```
token_credential = DefaultAzureCredential()
blob_service_client = BlobServiceClient(
    account_url="https://127.0.0.1:10000/devstoreaccount1", credential=token_credential, connection_verify=False
)
azurite_container = "abc"
container_client = blob_service_client.get_container_client(container=azurite_container)
```
The command for starting Azurite:
```
azurite --skipApiVersionCheck --blobPort 10000 --blobHost 127.0.0.1 -d debug.log --key server.key --cert server.pem --oauth basic
```
Error:
The sdk tried to connect to the "real" azure storage for the authentication, which is wrong as I was testing against `Azurite`
```
EnvironmentCredential: Authentication failed: Unable to get authority configuration for https://login.microsoftonline.com/f997392c-e15a-4ad8-af9e-cd6966caba7f. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
```
**Expected behavior**
Authentication successful. The script runs with no error 

**Screenshots**
NA

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

To make sure we are on same page, what @blueww mentioned was to make Azurite accept the token got by DefaultAzureCredential.

The error you showed was your code failed to get a token using DefaultAzureCredential. (It is the step before you can use the token in Azurite)

You can refer https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/README.md#defaultazurecredential to get more details how to get a token using AzureDefaultCredential.

Thank you.

**Comment by phoebusm** [comment]
/unresolve
@xiangyan99 
Thanks for your reply. I have gone through the manual. The problem is, like I mention above, is, with .net SDK, I can connect to Azurite with token_credential. But not with python SDK. I have shown the script I use for testing and I am wondering if there is anything I have missed.

**Comment by xiangyan99** [comment]
The error message you saw:

EnvironmentCredential: Authentication failed: Unable to get authority configuration for https://login.microsoftonline.com/f997392c-e15a-4ad8-af9e-cd6966caba7f. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.

was not related to Azurite.

I believe you can repro it with code:

```py
token_credential = DefaultAzureCredential()
token_credential.get_token("https://storage.azure.com/.default")
```

You failed to get credential because there was something wrong in the environment settings. (I guess .net should also fail if you run your .net code in this environment).
