### ISSUE TITLE
How To Resolve Azure Function `Stream Too Long` Error (blob trigger)

### ISSUE THREAD

**Issue by GeraldRupp** [Azure/azure-sdk-for-python#33296]
- **Package Name**: azure.functions 
- **Package Version**: 4.0.5198
- **Operating System**: OS Name:                   Microsoft Windows 10 Pro N
                                      OS Version:                10.0.19045 N/A Build 19045
                                      OS Manufacturer:           Microsoft Corporation
- **Python Version**:  3.9.16

**Describe the bug**
I am using a azure function blob trigger to process some json-files and got a `Stream Too Long` Error if the file (which triggered the function) is very big (~2.5 GiB). After talking with Microsoft Azure Community we think the file is loaded in memory (https://learn.microsoft.com/en-us/answers/questions/1433195/how-to-resolve-azure-function-stream-too-long-erro). Is there a way to only get the name of blob and not to load file in memory? 

**To Reproduce**
1. create very large json-file
2. Create durable azure function blob trigger which takes blob.name and gives it to orchestrator-function
3. store json file in storage account (blob trigger "looks" at this file)  

**Expected behavior**
Error: Stream too long

**Screenshots**

**Additional context**

**Comment by pvaneck** [comment]
Thanks for the feedback, I've assigned some folks who may be able to provide some insight.

**Comment by jalauzon-msft** [comment]
Hi @GeraldRupp this does not seem like an issue with any library inside the Azure SDK repo. There is a chance they use `azure-storage-blob` internally in the functions service but we have no way of knowing that. I think it may be better to redirect your issue to https://github.com/Azure/azure-functions-python-library? The owners of this repo are not familiar with the inner workings of Azure Functions or that SDK. Thanks!

**Comment by xiangyan99** [comment]
Closing this one and please feel free to open an issue in azure-functions repo.
