### ISSUE TITLE
ResourceNotFoundError (404) with DocumentIntelligenceClient

### ISSUE THREAD

**Issue by ffalkenberg** [Azure/azure-sdk-for-python#33312]
**Environment:**
- Python Version: 3.9.13
- Old SDK: azure-ai-formrecognizer 3.3.2
- New SDK: azure-ai-documentintelligence 1.0.0b1

**Issue:**
I am facing a `ResourceNotFoundError (404)` when using `DocumentIntelligenceClient` in the new Azure SDK version 1.0.0b1. The old SDK version 3.3.2 (`DocumentAnalysisClient`) works fine with the same endpoint and key.

**Reproducible Steps:**
1. **Working Code with Old SDK (`azure-ai-formrecognizer 3.3.2`):**
    ```python
    from azure.core.credentials import AzureKeyCredential
    from azure.ai.formrecognizer import DocumentAnalysisClient

    endpoint = os.environ["ENDPOINT"]
    key = os.environ["API_KEY"]

    client = DocumentAnalysisClient(endpoint=endpoint, credential=AzureKeyCredential(key))
    with open(path_to_sample_documents, "rb") as f:
        poller = client.begin_analyze_document("prebuilt-layout", f)
    ```

2. **Non-Working Code with New SDK (`azure-ai-documentintelligence 1.0.0b1`):**
    ```python
    from azure.core.credentials import AzureKeyCredential
    from azure.ai.documentintelligence import DocumentIntelligenceClient

    endpoint = os.environ["ENDPOINT"]
    key = os.environ["API_KEY"]

    client = DocumentIntelligenceClient(endpoint=endpoint, credential=AzureKeyCredential(key))
    with open(path_to_sample_documents, "rb") as f:
        poller = client.begin_analyze_document("prebuilt-layout", f)
    ```

**Error Message:**
```
azure.core.exceptions.ResourceNotFoundError: (404) Resource not found
```

**Comment by YalinLi0312** [comment]
Hi @ffalkenberg , thanks for contacting!
- Are you using the same resource in the old and new SDK?
- Can you provide stack trace which could help us to investigate?

**Comment by calmdown13** [comment]
I'm also running into the exact same issue. I'm using the same resource with both the old and the new client. Only the new client returns a 404.

**Comment by YalinLi0312** [comment]
Hi @ffalkenberg and @calmdown13 ,

You have to override the default `content_type` while analyzing a local doc in our first beta release `azure-ai-documentintelligence 1.0.0b1`. 

Can you try the code below?
```python
from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient

endpoint = os.environ["ENDPOINT"]
key = os.environ["API_KEY"]

client = DocumentIntelligenceClient(endpoint=endpoint, credential=AzureKeyCredential(key))
with open(path_to_sample_documents, "rb") as f:
    poller = client.begin_analyze_document("prebuilt-layout", f, content_type="application/octet-stream")
```

**Comment by ffalkenberg** [comment]
@YalinLi0312 Hi, I used your code from above with `content_type` but still get the error, here is my stack trace

```
Traceback (most recent call last):
  File "/path/to/my/project/test.py", line 18, in <module>
    poller = client.begin_analyze_document("prebuilt-layout", f, content_type="application/octet-stream")
  File "/path/to/python-environment/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/path/to/python-environment/site-packages/azure/ai/documentintelligence/_operations/_operations.py", line 752, in begin_analyze_document
    raw_result = self._analyze_document_initial(  # type: ignore
  File "/path/to/python-environment/site-packages/azure/ai/documentintelligence/_operations/_operations.py", line 510, in _analyze_document_initial
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/path/to/python-environment/site-packages/azure/core/exceptions.py", line 164, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (404) Resource not found
Code: 404
Message: Resource not found
```

**Comment by calmdown13** [comment]
@YalinLi0312 Same as @ffalkenberg. Still a 404 even after overriding the `content_type`.

**Comment by YalinLi0312** [comment]
@calmdown13  @ffalkenberg Do you still see `404` with the region from the available list?

**Comment by ericthomas1** [comment]
> FYI I think it is to do with the region, I found this [here](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-layout?view=doc-intel-4.0.0). ![image](https://private-user-images.githubusercontent.com/70471360/291066898-f759d952-a75f-4401-9ec9-89801480a483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTU1MDYsIm5iZiI6MTcwNjE1NTIwNiwicGF0aCI6Ii83MDQ3MTM2MC8yOTEwNjY4OTgtZjc1OWQ5NTItYTc1Zi00NDAxLTllYzktODk4MDE0ODBhNDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA0MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOGEzMjZhY2Q2MjU1MmJmOWYxMjc4OTczZDEwZmE0MWYwN2U1ODA0MTFhZTZlOTIwNTc3ZWZmMWI4NzQzMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MtE6ZcochdhbU2HolYicAYZBJD_WSMtt6A23KetIYWc)

I ran `pip install azure-ai-documentintelligence` and am trying to send a blob URL that is in Blob Storage. Using Azure Function. The Doc Intel resource has `Storage Blob Data Reader` role assigned, but I still receive 404.

How do I know which `api-version` I'm using? The App Insights request shows `REDACTED` for `api-version`!

My Doc Intel resource is deployed in `Central US` region.

![image](https://github.com/Azure/azure-sdk-for-python/assets/42788729/97e262c7-4098-47b9-b2fa-21e1afc4a7b3)

![image](https://github.com/Azure/azure-sdk-for-python/assets/42788729/1d63453f-0265-41b5-827c-0317e691d49a)

**Comment by ericthomas1** [comment]
Man...what a time sink! I spun up a new Doc Intel resource in `West2 US` region, updated the Doc Intel endpoint, and tried again... BINGO, went through the first time. 

It would be very useful if available regions are the only options when deploying a new Azure Resource! This is not the first time I've spent hours on an ambiguous error only to find that the resource is unavailable (and shouldn't even have been allowed to be created!) in the region I created it in...

**Comment by ericthomas1** [comment]
Redeploy in an allowed region.

**Comment by ninhvuonglinh** [comment]
solve my problem by deployed in East US region, even with North Central US doesn't support as of now.

**Comment by adilbleedai** [comment]
Change of region solved my issue as well

**Comment by YalinLi0312** [comment]
> > FYI I think it is to do with the region, I found this [here](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-layout?view=doc-intel-4.0.0). ![image](https://private-user-images.githubusercontent.com/70471360/291066898-f759d952-a75f-4401-9ec9-89801480a483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTU1MDYsIm5iZiI6MTcwNjE1NTIwNiwicGF0aCI6Ii83MDQ3MTM2MC8yOTEwNjY4OTgtZjc1OWQ5NTItYTc1Zi00NDAxLTllYzktODk4MDE0ODBhNDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA0MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOGEzMjZhY2Q2MjU1MmJmOWYxMjc4OTczZDEwZmE0MWYwN2U1ODA0MTFhZTZlOTIwNTc3ZWZmMWI4NzQzMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MtE6ZcochdhbU2HolYicAYZBJD_WSMtt6A23KetIYWc)
> 
> I ran `pip install azure-ai-documentintelligence` and am trying to send a blob URL that is in Blob Storage. Using Azure Function. The Doc Intel resource has `Storage Blob Data Reader` role assigned, but I still receive 404.
> 
> How do I know which `api-version` I'm using? The App Insights request shows `REDACTED` for `api-version`!
> 
> My Doc Intel resource is deployed in `Central US` region.
> 
> ![image](https://private-user-images.githubusercontent.com/42788729/299534052-97e262c7-4098-47b9-b2fa-21e1afc4a7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzc2MzIsIm5iZiI6MTcxNTI3NzMzMiwicGF0aCI6Ii80Mjc4ODcyOS8yOTk1MzQwNTItOTdlMjYyYzctNDA5OC00N2I5LWIyZmEtMjFlMWFmYzRhN2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE3NTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NTQ0YThmZmZhZWM2Y2Y0OTJmOTYwOGFjZmM1M2U5ZGZjZGUyNDBhMzkzOGM4ZGRlMGVjMTQ1NGU0NGM4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxUtMyYg03o7-aPvQCRqv_J23o_9-BGnk1lvhluQrxk)
> 
> ![image](https://private-user-images.githubusercontent.com/42788729/299534148-1d63453f-0265-41b5-827c-0317e691d49a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzc2MzIsIm5iZiI6MTcxNTI3NzMzMiwicGF0aCI6Ii80Mjc4ODcyOS8yOTk1MzQxNDgtMWQ2MzQ1M2YtMDI2NS00MWI1LTgyN2MtMDMxN2U2OTFkNDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE3NTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMTMwMTE2OTRkMWZiODg4YjQ3OTgzNTcyNDg1MDAxM2JlYWQxODE0NGJiMDEzYjAxZWUwMWI1MmU5MTM4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l2Mely0SI9uyJa0lv9I0SJY6eNiQ3OEvJGT5As_2pJU)

Did you get the issue resolved in the redeployed region? I'm asking because I notice the role you are using may not work, we recommend to use `Cognitive Services User` role which is mentioned in our [README.md](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/documentintelligence/azure-ai-documentintelligence#create-the-client-with-an-azure-active-directory-credential).

For your question about how to know the `api-version` you're using - you can check by debugging the client or request, or check the SDK version and API version table in our [README.md](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/documentintelligence/azure-ai-documentintelligence#installating-the-package)

Thanks
