### ISSUE TITLE
Missing: The Docs for the MonitoringTarget class doesn't describe the allowed values for the ml_task parameter

### ISSUE THREAD

**Issue by sraza-onshape** [Azure/azure-sdk-for-python#33319]
On the page describing the [`MonitoringTarget`](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.monitoringtarget?view=azure-python) class, there's no clear description of the values that can be accepted by the `ml_task` parameter. 

This is somewhat unexpected, as I can see the allowed values specified in the [source code file](https://github.com/Azure/azure-sdk-for-python/blob/d7b3abc69e3303eb1ee93aa2fbec701d9eb243ab/sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/target.py#L16C5-L16C102) for this class: 

```
:keyword ml_task: Type of task. Allowed values: Classification, Regression, and QuestionAnswering
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc236d3-95f1-c9a7-2b2c-9a4d1917dd3d
* Version Independent ID: 6d8c8e6e-9fc8-f936-f9d4-54e6cbb2ec50
* Content: [azure.ai.ml.entities.MonitoringTarget class](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.monitoringtarget?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.MonitoringTarget.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.MonitoringTarget.yml)
* Service: **machine-learning**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by diondrapeck** [comment]
@sraza-onshape - Thanks for bringing this to our attention! I believe this is due to a syntax error. We'll work on getting this fixed.
