### ISSUE TITLE
Support Azure Machine Learning managed identity

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#33325]
The Azure ML managed identity API is no longer the same as the App Service 2017-09-01 API, so we need to add explicit support. The main differences vs. App Service are that `expires_on` is an int and token requests must specify a `clientid` parameter, even for system assigned identities. The platform provides a default client ID in environment variable `DEFAULT_IDENTITY_CLIENT_ID`. See https://github.com/Azure/azure-sdk-for-go/pull/21851 for an example implementation and here's [a test recording](https://github.com/Azure/azure-sdk-assets/blob/go/azidentity_db4a26f583/go/sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_AzureMLLive.json).

Related: #31032, #32921

**Comment by xiangyan99** [comment]
Done.
