### ISSUE TITLE
Connection reset by peer from content safety

### ISSUE THREAD

**Issue by polavishnu4444** [Azure/azure-sdk-for-python#33330]
- **Package Name**: azure-ai-contentsafety
- **Package Version**: 1.0.0b1
- **Operating System**: Linux
- **Python Version**:  3.9

**Describe the bug**
Getting error `('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"`

**To Reproduce**
1. Create client
2. If no request say for couple of hours, and then when making request, it fails with above error.

**Expected behavior**
As connection retries and read retries are already configured, it should not have hit this exception and should have done the retries.

**Additional context**
Seeing this problem when using cross cloud especially.

**Comment by pvaneck** [comment]
Thanks for the feedback. I'm wondering if there are issues on the service side that are causing this error despite the default retries. @mengaims any ideas?

**Comment by polavishnu4444** [comment]
@pvaneck - When you mean service side it's the Azure RAI service?

**Comment by pvaneck** [comment]
@polavishnu4444 Right, this could be a service issue, but not sure. Based on the error message and context, it seems that the service is closing the connection after a period of inactivity, which is relatively normal, but typically retries should get it working again. Some questions that may assist on debugging:

- What client method are you calling when you get this error?
- Are you using the sync client (as opposed to the async client)?
- Does the `ConnectionResetError` occur only after a long period of inactivity?
- Can you share the full logs/stacktrace, or is there anything in the logs/stacktrace that indicate the request is being retried? I'm wondering if perhaps the ConnectionResetError isn't being retried by the RetryPolicy of the client.
