### ISSUE TITLE
Azure Search FieldMappingFunctions not being called or applied

### ISSUE THREAD

**Issue by gkinnell** [Azure/azure-sdk-for-python#33348]
- **Package Name**:  azure-search-documents
- **Package Version**: azure-search-documents==11.4.0b3
- **Operating System**: Windows 11
- **Python Version**:  3.12

**Describe the bug**
The FieldMapping function does not apply assigned FieldMappingFunctions to source fields. It also doesn't raise an error if an invalid FieldMappingFunction is passed - it just doesn't do anything with this argument.

**To Reproduce**
1. Create an indexer, and a list of field mappings, making use of the FieldMappingFunction capability to transform the source field
2. Run the indexer and index the files
3. Check the index
4. nothing has been applied to the input, and also no error has been raised to indicate that it isn't working.

**Expected behavior**
It should apply the passed FieldMappingFunction (or even just call it and raise an error...)

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/35457585/a8ac37c5-0e18-458e-b2c8-e4f357f025fb)

![image](https://github.com/Azure/azure-sdk-for-python/assets/35457585/b821c17b-65ef-4443-94e3-aebb48617c00)
function clearly isn't called as it just passes the original url through.

**Additional context**

I have also tested urlDecode, base64Decode etc as shown on this page:
https://learn.microsoft.com/en-us/azure/search/search-indexer-field-mappings?tabs=rest

**Comment by xiangyan99** [comment]
If it works, could you help to share more details about the code snippets how you create the indexer?

It will help us narrow down the issue.

**Comment by gkinnell** [comment]
> If it works, could you help to share more details about the code snippets how you create the indexer?
> 
> It will help us narrow down the issue.

Sure
We create a list of the fieldmappings (simplified version here)
![image](https://github.com/Azure/azure-sdk-for-python/assets/35457585/dfce2aa6-eca0-461c-bf63-0962536ab19b)
corresponding field definitions:
![image](https://github.com/Azure/azure-sdk-for-python/assets/35457585/6483e8ba-da35-40ff-8373-15eca25b488b)

We then create the index using azure.search.documents.indexes.models.SearchIndex (passing the field definitions)
![image](https://github.com/Azure/azure-sdk-for-python/assets/35457585/ad0c4de7-2681-493d-8203-73d8502a0a63)

And using azure.search.documents.indexes.models.SearchIndexer, we point it at the index we just created and pass the pdf_output_field_mappings list we created above
![image](https://github.com/Azure/azure-sdk-for-python/assets/35457585/fbe9fda2-18b2-4f6e-a2a9-b92617bb0ba1)


(apologies, this is all abstracted within object methods, the list of field mappings above (pdf_output_field_mappings) is passed to the output_field_mappings arg, field_mappings itself is and empty list

**Comment by xiangyan99** [comment]
Thanks for sharing.

The argument name of mapping function is `mapping_function` rather than `mappingFunction`. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/azure/search/documents/indexes/_generated/models/_models_py3.py#L3289

Does it work if you use `mapping_function` instead?
