### ISSUE TITLE
Export an Azure SQL

### ISSUE THREAD

**Issue by mendiney** [Azure/azure-sdk-for-python#3335]
hello!
I am trying to Export an Azure SQL database to a BACPAC file with the cli(I already do it in the portal), but I can't find any way to do it with a python script.

I find this class in the doc 
https://docs.microsoft.com/en-us/python/api/azure-mgmt-sql/azure.mgmt.sql.models.export_request_py3.exportrequest?view=azure-python
but I can't understand how to send the request.

please help me!

**Comment by mendiney** [comment]
Hi @lmazuel 

I find this post with your answer in it! 
https://stackoverflow.com/questions/51217739/how-to-create-azure-mgmt-serializer-deserializer-parameters

I have the exact same problem but I can't get enough info to understand how to provide the serializer and the deserializer parameter to the function 

in my case, I need to use this class 
https://docs.microsoft.com/en-us/python/api/azure-mgmt-sql/azure.mgmt.sql.operations.databases_operations.databasesoperations?view=azure-python#export

thanks

**Comment by lmazuel** [comment]
It's an internal class that you should try to create by yourself. You MUST create a SqlManagementClient, and this instance will have an attribute databases.

https://docs.microsoft.com/en-us/python/api/overview/azure/sql?view=azure-python#example
