### ISSUE TITLE
[azure ml SDK V2] Support for passing output of a completed PipelineJob to input of a new pipeline.

### ISSUE THREAD

**Issue by sivaguru-nathan** [Azure/azure-sdk-for-python#33368]
**Problem:**

I am attempting to automate a pipeline in SDKv2. I have a completed pipeline job and a created pipeline component. The goal is to pass the output of the completed pipeline job to the pipeline component as input.

**Current Approach:**

Retrieve the pipeline job object using ml_client.jobs.get with the job name as input.
Successfully obtain the output object via object.outputs

**Issue:**
Encountering a validation error when attempting to pass the output object to the pipeline input. The error message indicates that < class azure.ai.ml.entities._job.pipeline._io.base.PipelineOutput> is not supported.

**Feature Request:**
Requesting support for passing PipelineOutput objects as inputs to a pipeline in SDKv2. This enhancement would greatly facilitate the automation process. Open to any alternative solutions if available.

Please provide guidance on this matter. Thank you!

**Comment by wangchao1230** [comment]
We don't have plan to supprt this in short term. 

There are workarounds to achieve similar exprience, you can: 
- register pipeline output as named asset, and pass named asset to next job. Learn more in this [doc](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-inputs-outputs-pipeline?view=azureml-api-2&tabs=cli#how-to-register-output-as-named-asset)
- set the output path of the pipeline output , construct a new Input with that path to next job.

**Comment by wangchao1230** [comment]
The system do generate random name for the ${{name}} macro. As job name is designed to be unique in the system.

You could add some thing like date to make your pipeline job output path unique given your scenario.  
Basiclly explicitly declare the output path to a unique string can help you here.

**Comment by wangchao1230** [comment]
Close this issue as customer confirm it works.

**Comment by sivaguru-nathan** [comment]
@wangchao1230 I cannot consider the issue resolved solely based on the alternate solution provided. The resolution, in my view, should involve the support for the PipelineOutput object in the input of the pipeline.

**Comment by wangchao1230** [comment]
@sivaguru-nathan  
Let me confirm you get my suggestion. 
You can promote node output as pipeline output. and set pipeline output to some value before you submit your job, like below:
```python
from datetime import datetime
t = datetime.now().strftime('%Y-%m-%d-%H%M')
pipeline_job.outputs.trained_model.path = "azureml://datastores/workspaceblobstore/paths/azureml/"+f"{t}/your_output_name"
```

For a more full example you can get back the job output and use it in next step. 
![image](https://github.com/Azure/azure-sdk-for-python/assets/47586720/07aab3d7-20f3-40f7-b0bd-e7824fd84cb5)

The reason we don't accept PipelineOutput object directly as input of the pipeline job is 
- The input of a Job must be a Input class. If we support the PipelineJobOutput object as Job Input, then from consistency perspective, we need to do that for all other type of jobs. That might be something we would avoid for now. 
- Pipeline job output path has those special macros like ${{name}}, we won't be able to resolve for such case when submit next job.

**Comment by sivaguru-nathan** [comment]
@wangchao1230 I get it. Thank you for the explanation.
