### ISSUE TITLE
Build status after creating an environment from a Docker build context

### ISSUE THREAD

**Issue by ZhiliangWu** [Azure/azure-sdk-for-python#33377]
**Is your feature request related to a problem? Please describe.**

According to the [docs of creating an env. from a docker build context](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-environments-v2?view=azureml-api-2&tabs=python#create-an-environment-from-a-docker-build-context)

> Azure Machine Learning will start building the image from the build context when the environment is created. You can monitor the status of the build and view the build logs in the studio UI.

Note, the status of the build is not available in other formats apart from going to the studio UI. This makes it very difficult if I want to automate this environment creation in some CI jobs, as the CI jobs would simply succeed without checking the build status. As the environment is the basis for running some scripts/components/pipelines in AML, it essentially blocks the automation using CI jobs, but one has to fall back to manual processes.

**Describe the solution you'd like**
Add a [method](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.environment?view=azure-python) to check the build status of the env, e.g., `check_build_process(max_time=800)` to check the build process for maximal 800 seconds. If the build succeeds within the max time, it will return `True`. 

**Describe alternatives you've considered**
I have tried the [`validate` method](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.environment?view=azure-python#azure-ai-ml-entities-environment-validate). But it doesn't return anything on whether an environmental build is successful.  

Another alternative is to treat the environment build as a component in one pipelines, but there are 1) no docs on this topic that I can refer to; 2) I doubt if this is really necessary to introduce another level of complexity. 

**Additional context**
This feature is rather more important for creating an environment from a Docker build context, as building docker containers might be an error-prone process.

**Comment by swathipil** [comment]
Hi @ZhiliangWu - Thanks for opening an issue. We'll take a look asap!

@azureml-github - Can you take a look?

**Comment by ZhiliangWu** [comment]
Hi @swathipil, thanks for investigating this! If you need more input from my side, just let me know.

**Comment by banibrata** [comment]
Right now we don't have this exposed.  Thanks for the feedback, I added one feature ask into our internal backlog and will review it.

**Comment by ZhiliangWu** [comment]
@banibrata Thanks for adding this. Let me know if you need more input from my side.

**Comment by ZhiliangWu** [comment]
@banibrata-de Is this already completed? Any docs on how it works?
