### ISSUE TITLE
Lenguajes 

### ISSUE THREAD

**Issue by DawallAZllon91** [Azure/azure-sdk-for-python#33372]
Implementar nuevas acciones de lenguaje CC+

**Comment by DawallAZllon91** [comment]
> Implementar nuevas acciones de lenguaje CC+

```
Verification non ci ci joint le chargeur de téléphone portable pour le téléphone portable 📱
```

**Comment by xiangyan99** [comment]
Sorry. I don't understand it. Could you open it in English?

**Comment by DawallAZllon91** [comment]
> Lo siento. No lo entiendo. ¿Podrías abrirlo en inglés?

Ready :)
