### ISSUE TITLE
Data drop 400: 109: Field 'typeName' on type 'ExceptionDetails'

### ISSUE THREAD

**Issue by macieyng** [Azure/azure-sdk-for-python#33397]
- **Package Name**:  azure-monitor-opentelemetry-exporter
- **Package Version**: 1.0.0b14
- **Operating System**: debian
- **Python Version**: 3.11

**Describe the bug**

Every once in a while we get this error. Not sure if it's misconfigured on our end or if it's a bug.

```
Data drop 400: 109: Field 'typeName' on type 'ExceptionDetails' is required but missing or empty. 
Expected: string 
{
'additional_properties': {}, 
'version': 1, 
'name': 'Microsoft.ApplicationInsights.Exception', 
'time': '2023-12-05T14:25:51.098915Z',
'sample_rate': 100, 
'sequence': None, 
'instrumentation_key': '<key>', 
'tags': 
{
  'ai.device.id': 'e3c4d6859f04', 
  'ai.device.locale': 'en_US', 
  'ai.device.osVersion': '#1 SMP Wed Jun 21 23:17:09 UTC 2023', 
  'ai.device.type': 'Other', 
  'ai.internal.sdkVersion': 'py3.11.6:otel1.18.0:ext1.0.0b14', 
  'ai.cloud.role': '<service-name>', 
  'ai.cloud.roleInstance': '04d4bf52f693266441b170bf46cebd271f527fb80901df8f7ea26b618af74c76', 
  'ai.internal.nodeName': '04d4bf52f693266441b170bf46cebd271f527fb80901df8f7ea26b618af74c76', 'ai.operation.id': '00000000000000000000000000000000', 
  'ai.operation.parentId': '0000000000000000'
}, 
'data': <azure.monitor.opentelemetry.exporter._generated.models._models_py3.MonitorBase object at 0x7c869c3f00d0>}.
```

**To Reproduce**
Not sure.

**Expected behavior**
If typeName is empty then it should be sent with some default value, but sent.

**Screenshots**

**Additional context**

**Comment by swathipil** [comment]
Hi @macieyng - Thanks for opening an issue. We'll take a look asap!

**Comment by lzchen** [comment]
@macieyng 

Can you upgrade to the latest version of the exporter and see if that fixes your issue?

**Comment by macieyng** [comment]
We have a pending upgrade for that app sometime next week, but it's 1.0.0b17 (as per https://github.com/Azure/azure-sdk-for-python/pull/32897#issuecomment-1841685887).

I reported this cause I couldn't find similar issue.
