### ISSUE TITLE
[Azure ml sdkv2] How to pass string output in a component?

### ISSUE THREAD

**Issue by sivaguru-nathan** [Azure/azure-sdk-for-python#33417]
**Description**:
I was able to declare output as a string type while defining the component

`command(outputs={"model_name": Output(type="string")}`

However, the documentation lacks examples on how to pass output as a string. it would be beneficial to include explicit examples in the documentation.

**Expected**:
Provide examples in the documentation demonstrating the correct syntax for declaring output as a string type in a component and how it has to be passed as a output while defining Pipeline.

**Comment by swathipil** [comment]
Hi @sivaguru-nathan - Can you please provide the following information?

* Package name
* Package version

**Comment by sivaguru-nathan** [comment]
azure-ai-ml 1.12.1

**Comment by Stephen1993** [comment]
Hi @sivaguru-nathan We will add a sample to show how to use string, which is my PR:
https://github.com/Azure/azureml-examples/pull/2904/files

You can refer to the usage method first:
https://github.com/Stephen1993/azureml-examples/blob/add_primitive_output_sample/sdk/python/jobs/pipelines/pipeline_with_components_use_primitive_output/pipeline_with_components_use_primitive_output.ipynb

**Comment by dazeandconfusion** [comment]
Hello, @Stephen1993 .
I have the same question as @sivaguru-nathan .  I want to pass string values between my components with `Output(type="string")` without saving my string to the file and then reading it in the following component. Is it possible?
