### ISSUE TITLE
azure-mgmt-costmanagement CostManagementClient Query ignores pagination

### ISSUE THREAD

**Issue by digaoddc** [Azure/azure-sdk-for-python#33429]
- **azure-mgmt-costmanagement**: 
- **4.0.1**: 
- **Linux**:
- **3.8.17**: 

**Describe the bug**
When I invoke CostManagementClient.query.usage() for a query with a lot of results, such as all billing costs for a whole month, I get an incomplete result. It only returns the first 5000 rows, and the response is a `QueryResult` object with a method called `next_link` which returns the link for a paginated result. The SDK does not have any way to pass this `next_link` and continue the pagination.
The issue: It is not possible to get all the results from the API because the API returns a paginated response, but the SDK ignores this pagination and only returns the first result set of the pagination.

**To Reproduce**

The code below shows the costs for a given subscription. Please test this with a subscription that has a lot of billing costs for the month specific in the `time_period`, so you will be able to get a paginated response and see the issue.

```python
import datetime 
from azure.identity import ClientSecretCredential
from azure.mgmt.costmanagement import CostManagementClient
from azure.mgmt.costmanagement.models  import QueryDefinition, ExportType, QueryTimePeriod, QueryGrouping, QueryDataset, QueryAggregation

COSTS_DIMENSIONS = {
  "ResourceId": "resource_id",
  "ServiceName": "service_name",
  "MeterSubCategory": "meter_sub_categoty",
  "ResourceLocation": "resource_location",
  "Product": "product",
  "Meter": "meter",
  "ChargeType": "charge_type",
  "PublisherType": "publisher_type",
  "PartnerEarnedCreditApplied": "partner_earned_credit_applied",
  "ServiceFamily": "service_family",
  "PricingModel": "pricing_model",
  "UnitOfMeasure": "unit_of_measure"
}

client = CostManagementClient(credential=ClientSecretCredential(
  tenant_id='foo',
  client_id='bar',
  client_secret='baz',
))
scope = f"/subscriptions/{'subscription-id'}/"
parameters = QueryDefinition(
  type=ExportType("ActualCost"), 
  timeframe="Custom",
  time_period=QueryTimePeriod(
    from_property=datetime.datetime(2023, 11, 1), 
    to=datetime.datetime(2023, 11, 30)
    ),
  dataset=QueryDataset(
    granularity='Daily',
    grouping=[QueryGrouping(type="Dimension", name=x) for x in COSTS_DIMENSIONS],
    aggregation={ "totalCostUSD": QueryAggregation(name="CostUSD", function="sum") }
  )
)
response = client.query.usage(scope=scope, parameters=parameters)
response.rows # only returns the first 5000 results

response.next_link 
# the response object has the next link for pagination, but there's no way to use it
# the format will be: https://management.azure.com/subscriptions/id/providers/Microsoft.CostManagement/query?api-version=2022-10-01&$skiptoken=AQAAAA%3D%3D
```

**Expected behavior**

The SDK should work and get the paginated results(not only the first 5000 rows).

** For Reference **
https://learn.microsoft.com/en-gb/rest/api/cost-management/query/usage?view=rest-cost-management-2023-03-01&tabs=HTTP

** Related Issues **
https://github.com/Azure/azure-sdk-for-python/issues/18927

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
It seems the structure of [QueryResult](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-11-01/costmanagement.json#L2218) does not meet the expected structure (like this [example](https://github.com/Azure/autorest/blob/main/docs/openapi/examples/pollingPaging.json#L79) shows) to use the `pageable` extension. 
Would turn to service team for further support.

**Comment by ChenxiJiang333** [comment]
For now, this private package might be able to use as a temporary solution.
[azure-mgmt-costmanagement-1.0.0b1.zip](https://github.com/Azure/azure-sdk-for-python/files/13646585/azure-mgmt-costmanagement-1.0.0b1.zip)

**Comment by xiangyan99** [comment]
Since this is a service issue, closing the one in SDK repo and please use https://github.com/Azure/azure-rest-api-specs/issues/27044 to track.
