### ISSUE TITLE
[azure ml sdkv2] Reference Base Jobs for Components in PipelineJob.jobs attribute

### ISSUE THREAD

**Issue by sivaguru-nathan** [Azure/azure-sdk-for-python#33426]
**Description**
When using `ml_client.job.get` to load a completed pipeline job, the `PipelineJob` object is created successfully. 
However, when trying to access the finished job at the component level, the base job for the component is not referenced in `PipelineJob.jobs` attribute.

To access the component level job object i have to get component level job name from the Machine learning studio and load with `ml_client.job.get`

**proposal**
The `PipelineJob.jobs` attribute should reference the base job for each component, allowing easier access at the component level base job. 

**Package azure-ai-ml==1.12.1**

**Comment by Stephen1993** [comment]
Hi @sivaguru-nathan Do you want to get all the jobs? The following method can obtain all jobs.
```
for job in ml_client.jobs.list(parent_job_name=pipeline_job.name):
    print(job)
```

**Comment by sivaguru-nathan** [comment]
@Stephen1993 Thank you for the replay. it helps!
