### ISSUE TITLE
Logging is not published to Application Insights if `configure_azure_monitor` is called in another module.

### ISSUE THREAD

**Issue by shingotoda** [Azure/azure-sdk-for-python#33456]
- **Package Name**: azure-monitor-opentelemetry
- **Package Version**:  1.1.1
- **Operating System**: MacOS, Debian (bullseye)
- **Python Version**: 3.11

**Questions**
I'm new to OpenTelemetry and Django so my usage might be wrong but when I'm instrumenting Django app, logging does not get published to Application Insights if python's logging API is called in the different module file from one that calls `configure_azure_monitor()`. 

In my app, firstly it's called in Django's setting module `settings.py`.

```
if os.getenv('APPLICATIONINSIGHTS_CONNECTION_STRING'):
    print('Enabling OpenTelemetry...')
    from azure.monitor.opentelemetry import configure_azure_monitor

    configure_azure_monitor()
    logger = logging.getLogger(__name__)
    logger.warning('OpenTelemetry has been enabled')
else:
    print('Environment variable APPLICATIONINSIGHTS_CONNECTION_STRING is not set. Skipping OpenTelemetry configuration')
```

The warning log `OpenTelemetry has been enabled` was sent to traces table in Application Insights. But it wasn't published in another module. The example below emits exception logs but it's not shown up in Application Insights, regardless the `configure_azure_monitor()` is called or not in the module.

```
from rest_framework.views import APIView
from rest_framework.response import Response
from azure.monitor.opentelemetry import configure_azure_monitor

import os
import logging

# configure_azure_monitor()
logger = logging.getLogger(__name__)

class ExceptionTraceViews(APIView):
    permission_classes = []
    authentication_classes = []

    def post(self, request):
        data = request.data
        try:
            int('aaa')  # Exception as it tries to convert non-numeric string to integer
        except:
            message = f"{data.get('exception').get('message')}"
            logger.exception(data.get('exception').get('message'), extra={'custom_dimensions': {'api': 'logging', 'type': 'exception_telemetry'}})
        return Response({'message': 'OK'}, status=200)
```

And if `configure_azure_monitor()` is called, the following warning messages are shown and sent to Application Insights so I assumed calling `configure_azure_monitor()` multiple times is not ideal.

```
WARNING Overriding of current TracerProvider is not allowed
WARNING Overriding of current LoggerProvider is not allowed
WARNING Overriding of current MeterProvider is not allowed
WARNING Attempting to instrument while already instrumented
WARNING Attempting to instrument while already instrumented
WARNING Attempting to instrument while already instrumented
WARNING Attempting to instrument while already instrumented
WARNING Attempting to instrument while already instrumented
```

As far as I read the source code, it looks that OTEL configuration is set to root logger so I thought it's OK to use it without calling `configure_azure_monitor()` multiple times. What is correct practice to configure instrumentation with `azure-monitor-opentelemetry` if it is used in multiple modules.

**To Reproduce**
1. call `configure_azure_monitor()` in one module and call logging API in another module.

**Expected behavior**
Ideally, once `configure_azure_monitor()` is called, logging is published. Or if some specialized logger is configured within the library then I wish to know how to retrieve it.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by lzchen** [comment]
@shingotoda 

Thanks for using the Azure monitor OpenTelemetry Distro. You are correct in assuming that `configure_azure_monitor()` should not be called multiple times. As for the missing logging from `ExceptionTraceViews`, I was not able to replicate the issue. I modified the [basic django app](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry/samples/tracing/django/sample/sample/settings.py) to include `configure_azure_monitor()` in the `settings.py` file and was able to capture logging telemetry with `logger.warning` sent from `settings.py` as well as [views.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry/samples/tracing/django/sample/example/views.py) (I removed `configure_azure_monitor()` from `views.py`). As for best practices, I would recommend the following:

1. Place the `configure_azure_monitor()` call in the views file in which you will be making the majority of your request calls that you want to track.
2. Only call `configure_azure_monitor()` once.
3. To only capture logs sent from `logging.X(...)` calls that only belong to your app, set the root logger that you want to capture in the configuration for `configure_azure_monitor()` as shown below:
```python
...
configure_azure_monitor(logger_name="<name-of-logger-you-want-to-track>")
...
```
Note that any logger that is a children of the logger you put in logger name will also be tracked (just like how Python standard logging works).

**Comment by shingotoda** [comment]
@lzchen Thank you for the suggestion. I think I managed to make it work to capture logs. I found that there is a root logger setting in my `settings.py` as below.

```
    "root": {
        "handlers": ["console"]
    }
```

If I remove this, then it starts capturing logs in another module. Do you think the root logger setting in `settings.py` harmful?

Also I found that `logger.exception` is not captured though I thought this is at `ERROR` level. Is this a limitation?

**Comment by lzchen** [comment]
> This would not be helpful for local development.

It is fine to have it setup the way you are currently if you don't mind the excessive noise, because you will be capturing logs from the distro itself if you do add it to the root logger.

> Also I found that logger.exception is not captured though I thought this is at ERROR level. Is this a limitation?

Did you check the `exceptions` table? `logger.exception()` calls wind up in that table instead of the traditional `traces` table.

**Comment by shingotoda** [comment]
@lzchen

> Did you check the exceptions table? logger.exception() calls wind up in that table instead of the traditional traces table.

exception itself is shown in the exceptions table but message sent by `logger.exception()` is not shown up in neither exceptions nor traces tables. But it's a minor issue so I'm OK with this.

> It is fine to have it setup the way you are currently if you don't mind the excessive noise, because you will be capturing logs from the distro itself if you do add it to the root logger.

Understood that recommendation is to use named logger rather than root. But I saw some behaviors that I do not really understand with named logger approach.

Now I call `configure_azure_monitor` with arg `logger_name='azure'` like this.

```
    from azure.monitor.opentelemetry import configure_azure_monitor
    configure_azure_monitor(logger_name='azure')
```

And configure root logger like this so that it will emit logs >=INFO to console.

```
    "root": {
        "handlers": ["console"],
        "level": 'INFO'
    }
```

And instrumentation is like this. See that now it get logger with name `azure`.

```
logger = logging.getLogger('azure')

class ExceptionTraceViews(APIView):
    permission_classes = []
    authentication_classes = []

    def post(self, request):
        data = request.data
        try:
            int('aaa')
        except:
            logger.exception('exception: ' + data.get('exception').get('message'), extra={'value': '123'})  # exception is NOT sent
            logger.critical('critical: ' + data.get('exception').get('message'))  # critical is sent
            logger.error('error: ' + data.get('exception').get('message'))        # error is sent
            logger.warn('warn: ' + data.get('exception').get('message'))        # warn is sent
            logger.info('info: ' + data.get('exception').get('message'))            # info starts to be sent when root's log level is INFO
            logger.debug('debug: ' + data.get('exception').get('message'))   # debug is NOT sent
        return Response({'message': 'OK'}, status=200)
```

Firstly, it starts emitting a lot of the following logs and they are ingested to Application Insights traces table. How can I prevent this?

```
INFO Request URL: 'https://japaneast-1.in.applicationinsights.azure.com//v2.1/track'
Request method: 'POST'
Request headers:
    'Content-Type': 'application/json'
    'Content-Length': '3163'
    'Accept': 'application/json'
    'x-ms-client-request-id': '40e674f0-9b1f-11ee-b6b1-da23c070c806'
    'User-Agent': 'azsdk-python-azuremonitorclient/unknown Python/3.11.2 (macOS-14.2-arm64-arm-64bit)'
A body is sent with the request
INFO Response status: 200
Response headers:
    'Content-Type': 'application/json; charset=utf-8'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 15 Dec 2023 07:55:02 GMT'
    'Content-Length': '49'
INFO Transmission succeeded: Item received: 3. Items accepted: 3
```

Secondary, the name logger starts to send INFO logs even though I did not set log level to this named logger. What I did is to set INFO log level to the root logger. I thought default log level is WARN for the named logger so INFO logs wouldn't be sent. How can I control log level to be sent to Application Insights?

**Comment by lzchen** [comment]
> Now I call configure_azure_monitor with arg logger_name='azure' like this.

Please name your logger something that doesn't start with `azure`. Our SDKs are under the `azure` namespace which is why you are most likely capturing logs sent by the SDK as well :).


> Secondary, the name logger starts to send INFO logs even though I did not set log level to this named logger.

The named logger takes the configuration from the ROOT logger unless overridden. Set the log level to WARN explicitly for your named logger to get WARN level messages and above.

**Comment by shingotoda** [comment]
@lzchen Thank you for the suggestion. OK, I will take another logger name not starting from `azure`. Also I understand that log level should be explicitly set to a named logger. But I still see the following message is emitted to stdout then results in being ingested to Log Analytics workspace.

```
INFO Request URL: 'https://japaneast-1.in.applicationinsights.azure.com//v2.1/track'
Request method: 'POST'
Request headers:
    'Content-Type': 'application/json'
    'Content-Length': '893'
    'Accept': 'application/json'
    'x-ms-client-request-id': 'e164e506-9b7e-11ee-94dd-92dfbd47e697'
    'User-Agent': 'azsdk-python-azuremonitorclient/unknown Python/3.11.7 (Linux-5.15.0-1052-azure-x86_64-with-glibc2.31)'
A body is sent with the request
INFO Response status: 200
Response headers:
    'Content-Type': 'application/json; charset=utf-8'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 15 Dec 2023 19:19:33 GMT'
    'Content-Length': '49'
INFO Transmission succeeded: Item received: 1. Items accepted: 1
```

After I debugged with pdb, it looks that this line is processed when telemetry is sent to Application Insights.

https://github.com/Azure/azure-sdk-for-python/blob/d8bcdc57c0287dca6b6bdc192c9255616c4f36d3/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L509C1-L512C23

```
            if http_request.body:
                log_string += "\nA body is sent with the request"
                logger.info(log_string)
                return
```

This logger has root as parent.

```
(Pdb) logger.name
'azure.core.pipeline.policies.http_logging_policy'
(Pdb) logger.parent
<RootLogger root (INFO)>
```

I would think that since this message is too verbose from application perspective and it takes root logger, this should call `logger.debug()` like other lines of this code like this.

https://github.com/Azure/azure-sdk-for-python/blob/d8bcdc57c0287dca6b6bdc192c9255616c4f36d3/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L324

Though it, I'm new to this codebase so my assumption might be wrong. Please let me know if there is a workaround to suppress this message.

**Comment by shingotoda** [comment]
@lzchen I think this issue is expanding from original question so I raised separate issue to discuss the verbose log.
https://github.com/Azure/azure-sdk-for-python/issues/33623

Please feel free to close this issue.
