### ISSUE TITLE
Setting instance_count in ModelBatchDeploymentSettings as described in the documentation does not work.

### ISSUE THREAD

**Issue by marcmmbcn** [Azure/azure-sdk-for-python#33470]
The documentation mentions that you need to set instance_count in ModelBatchDeploymentSettings, but the setting is not changed and it always defaults to 1.

I was able to change the setting by using resources=JobResourceConfiguration(instance_count=2) in ModelBatchDeployment.
Please correct the documentation as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a263eb0-6394-2fbc-7b76-a193fb651402
* Version Independent ID: 19f4cba8-2a4e-87a7-8c84-fa785359cb25
* Content: [azure.ai.ml.entities.ModelBatchDeploymentSettings class](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.modelbatchdeploymentsettings?view=azure-python)
* Content Source: [docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.ModelBatchDeploymentSettings.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.ModelBatchDeploymentSettings.yml)
* Service: **machine-learning**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by santiagxf** [comment]
Thanks for reporting this issue. @banibrata, documentation is accurate and it's the expected behavior according to our contracts. We should repair this item. `resources` is a key in the REST API, which is probably why it showing here. We should accept `instance_count` and reject (not ignore) `resources`.

**Comment by banibrata-de** [comment]
Thanks for reporting this issues, we have created a backlog item to track this however we don't have a timeline now to share when it will be fixed.

**Comment by nemanjarajic** [comment]
Hi @marcmmbcn, @santiagxf , @banibrata-de ,

I have recently merged a fix for this issue. Fix should be going out with the beginning of April for the 1.15.0 release.

**Comment by tom-christie** [comment]
@santiagxf Here is documentation that shows use of instance_count in ModelBatchDeploymentSettings, saying "Number of instances the interfering will run on."

https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.modelbatchdeploymentsettings?view=azure-python

**Comment by marcmmbcn** [comment]
[like]  Marc Mezquita reacted to your message:
________________________________

**Comment by marcmmbcn** [comment]
[0]     Marc Mezquita reacted to your message:
________________________________
