### ISSUE TITLE
`properties/providerName` not working on API_VERSION 2022-12-01-preview.

### ISSUE THREAD

**Issue by brendalf** [Azure/azure-sdk-for-python#33474]
- **Package Name**: azure-mgmt-securityinsight
- **Package Version**: 1.0.0
- **Operating System**: macos
- **Python Version**: 3.10.13

**Describe the bug**
I have a code where I list all the incidents coming from Azure Sentinel.
I need to filter the incidents by severity and if the providerName is equal to "Azure Sentinel".
The code works up to the API version 2022-06-01-preview but not in the default one (2022-12-01-preview).
Filtering by this value in the `az` cli also works.

**To Reproduce**
1. `az sentinel list -g RESOURCE_GROUP -w WORKSPACE_NAME --filter "properties/providerName eq 'Azure Sentinel'"` works.
2. The following code also works if the api version 2022-06-01-preview is hardcoded:
```python
response = self.security_insights.incidents.list(
    resource_group_name=resourcegroup_name,
    workspace_name=workspace_name,
    filter="properties/providerName eq 'Azure Sentinel'",
    orderby="properties/createdTimeUtc desc",
    api_version="2022-06-01-preview",  # required for the providerName property
)
```

**Expected behavior**
Since the `az` CLI works and the providerName property is listed in the official [documentation](https://learn.microsoft.com/nl-nl/rest/api/securityinsights/incidents/list?view=rest-securityinsights-2023-02-01&tabs=HTTP), I believe something is wrong in the default API [version 2022-12-01-preview](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/securityinsight/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/_incidents_operations.py#L55).

The code also works if I set the api_version param to be 2023-02-01 (based on the securityinsights package documentation), so maybe we just need to update the default version to the newest one? I'm happy to open a pull request.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi @brendalf
Thanks to point it out, yet, as the SDK was automatically generated, it's not suggested to directly make changes on it.
Instead, since this error was raised by service, I suggest to open an issue in https://github.com/Azure/azure-rest-api-specs/issues to turn to the service team to fix it on the service side.
