### ISSUE TITLE
FastAPIInstrumentor header capture incompatible with AzureMonitorTraceExporter

### ISSUE THREAD

**Issue by brandonwatts** [Azure/azure-sdk-for-python#33476]
- **Package Name**: azure-monitor-opentelemetry-exporter
- **Package Version**: 1.0.0b19
- **Operating System**: macOS Ventura 13.6.3
- **Python Version**: 3.11.7

**Describe the bug**
According to the docs of the FastAPIInstrumentor one should be able to set the OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST to capture the request headers. This performs as expected and creates a server span with custom properties like:

```
{ 
    'http.request.header.content_type': ['application/json'], 
    'http.request.header.user_agent': ['PostmanRuntime/7.35.0'], 
    'http.request.header.accept': ['*/*']
}
```

I would expect these properties to flow to App Insights as customDimensions and this is in fact what happens if you provide an additional property: {"test": "example"}. I believe this isn't working because it looks like custom properties with the http.* prefix [are being filtered out as part of the span](https://github.com/Azure/azure-sdk-for-python/blob/25e64606d72628e1d59f322dac9b16277a423353/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py#L503).

**To Reproduce**
1. Enable OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST to capture FastAPI headers

**Expected behavior**
I would expect that any headers provided to OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST would show up in the customDimensions at at least somewhere in app insights.

**Additional context**
Im not sure if this is a FastAPIInstrumentor problem with the way it names its custom span properties or a AzureMonitorTraceExporterr problem with the way it handles it but either way it creates confusion when the flag is turned on and no data shows in app insights even when the span has the properties it needs. It looks like the FlaskInstrumentor has the same sort of convention.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by brandonwatts** [comment]
If anyone comes across this a quick workaround is to basically rewrite the span properties that start with _http.request.header_ via a server request hook. This works and the headers become customDimensions. This seems a bit hacky though but it does work:

```
def server_request_hook(span: trace.Span, scope: dict):
    if span and span.is_recording():
        header_attributes = [a for a in span.attributes if a.startswith("http.request.header")]
        for attribute in header_attributes:
            value: tuple = span.attributes[attribute]
            span.set_attribute(attribute.lstrip("http."), value[0])
    
FastAPIInstrumentor.instrument_app(app, tracer_provider=trace.get_tracer_provider(), excluded_urls="/$,health", server_request_hook=server_request_hook)
```

**Comment by lzchen** [comment]
@brandonwatts 

You are correct that the exporter is currently designed to filter out OpenTelemetry based attributes from custom dimensions. We are currently discussing whether or not capturing these attributes in some way into custom dimensions is a desired feature we want to include as part of the exporter. For now, your workaround is a great mechanism in doing so :)

**Comment by MahrRah** [comment]
Are there any updates on this, as I am facing similar issues trying to propagate specific headers through our system?

Also, @brandonwatts thanks for the workaround!

**Comment by lzchen** [comment]
@MahrRah 

No updates from a feature perspective, we have not committed yet to adding this as a feature. On a side note, if your goal is propagation, have you tried using the [baggage api](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/baggage/propagation/__init__.py#L29) and referencing this [example](https://github.com/open-telemetry/opentelemetry-python/blob/main/docs/examples/basic_context/child_context.py) to propagate headers through the context?
