### ISSUE TITLE
Custom Events in Application Insights using azure-monitor-opentelemetry

### ISSUE THREAD

**Issue by DibranMulder** [Azure/azure-sdk-for-python#33472]
**Is your feature request related to a problem? Please describe.**
Azure Application Insights has a Custom Events interface. To my knowing there is no way of sending Custom Events using the Azure SDK for Python. I have tried to find it in the azure-monitor-opentelemetry but I couldn't find it.

**Describe the solution you'd like**
I would like to have an API using the azure-monitor-opentelemetry package to send a custom event to Application Insights. Or have it clearly documented that its not part of the spec and what alternatives people have.

**Describe alternatives you've considered**
I have no alternative, I guess.

**Additional context**

**Comment by lzchen** [comment]
@DibranMulder 

You can use the [Azure Monitor Events Extension](https://github.com/microsoft/ApplicationInsights-Python/blob/main/azure-monitor-events-extension/README.md) in conjunction with `azure-monitor-opentelemetry` to send custom event telemetry to Application Insights. Please note that this extension is in beta.

**Comment by DibranMulder** [comment]
Thanks, really appreciate your swift response.

**Comment by preethamrajk** [comment]
Hi @lzchen, I don't believe it is released yet, right?

**Comment by lzchen** [comment]
@preethamrajk 

It is already released. https://pypi.org/project/azure-monitor-events-extension/0.1.0/
