### ISSUE TITLE
How to find the azure spark pool availability in synapse analytics dynamically

### ISSUE THREAD

**Issue by veeru54** [Azure/azure-sdk-for-python#33488]
Hi ,

I want to schedule azure synapse notebooks from the pipeline, So the pipeline should dynamically pick the available azure spark pool from the list. How to get that list and fetch the available spark pool?

Thanks,
Satya

**Comment by wonner** [comment]
You can list spark pool by calling this API:
rest api: https://learn.microsoft.com/en-us/rest/api/synapse/resourcemanager/big-data-pools/list-by-workspace?view=rest-synapse-resourcemanager-2021-06-01-preview&tabs=HTTP
python sdk: https://learn.microsoft.com/en-us/python/api/azure-mgmt-synapse/azure.mgmt.synapse.operations.bigdatapoolsoperations?view=azure-python#azure-mgmt-synapse-operations-bigdatapoolsoperations-list-by-workspace

**Comment by wonner** [comment]
Feel free to reopen this issue if you have further question, thanks.
