### ISSUE TITLE
The api-version '2023-02-01' is invalid

### ISSUE THREAD

**Issue by jaymzh** [Azure/azure-sdk-for-python#33497]
- **Package Name**: azure-mgmt-quota
- **Package Version**: 1.1.0
- **Operating System**: MacOS
- **Python Version**: 3.11.5

**Describe the bug**
When calling `quota_client.quota.begin_update(...)` I get:

```
azure.core.exceptions.HttpResponseError: (InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
Message: The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

That's the default version that the azure SDK sends and the one that is recommend [in the docs](https://learn.microsoft.com/en-us/rest/api/quota/quota/update?view=rest-quota-2023-02-01&tabs=Python#code-try-0).

**To Reproduce**
1. Try to begin a quota change using the python sdk with code like:

```
credential = DefaultAzureCredential()
quota_client = QuotaMgmtClient(credential=credential)
quota_type = 'standardDSv3Family'
expected = ...
response = quota_client.quota.begin_update(
    resource_name=quota_type,
    scope=quota_info['scope'],
    create_quota_request={
        "properties": {
            "limit": {"limitObjectType": "LimitValue", "value": expected},
            "name": {"value": quota_type},
        },
    },
).result()
```

**Expected behavior**
It begins a quota change request.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
Took offline. Closing.

**Comment by jaymzh** [comment]
I don't think this should be closed, while I have a workaround, it's not a great one, not to mention the error was woefully misleading.

To help others who might hit this - the server didn't like the `scope` I passed in, and unfortunately errored with `invalidApiVersion`. Womp womp.

Further details:
In an attempt to build a scope for the quota library out of the subscription I had, I took the location out of the subscription object which is a shortname for the region. I then got a list of all locations in the subscription, and when I found one whose shortname matched, I grabbed that ID which was VERY close to the scopes that are expected.

But not quite you need to do:

```python
location.id.replace('/locations/', '/providers/Microsoft.Compute/locations/')
```

to get a valid scope.

So I think this bug should stay open for a few reasons:

1. There needs to be a better way to get scopes give the quota library works with lots of other libraries.
2. We should detect an invalid scope and report on that rather than return an InvalidApiVersion error
