### ISSUE TITLE
Idea: CloudError subclasses

### ISSUE THREAD

**Issue by akx** [Azure/azure-sdk-for-python#3349]
It would be very nice to have concrete CloudError subclasses for the various errors Azure spews out, instead of everything being CloudError.
Currently, to handle a particular error type you need to do something awkward like 

```python
try:
    self.compute_client.virtual_machines.get(...)
except CloudError as ce:
    if ce.error.error == 'ResourceNotFound':
        # ... process resource not found...
    else:
        raise  # some other error...
```

while you could do

```python
try:
    self.compute_client.virtual_machines.get(...)
except ResourceNotFound:
    # ... process resource not found...
```

instead.

Some technical notes/thoughts:

* I'd probably steer away from magic such as generating these exception classes at runtime, because that tends to just confuse static analysis and IDEs.
* Generating an `exceptions.py` sort of file for each service should be easy, since the it seems the various error codes are well-known, see e.g. [here](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/error-messages).
* Call sites raising `CloudError` won't need to be modified, since `__new__` magic could be added to `CloudError`; that is, raising a `CloudError` could actually end up raising a more specific subclass thereof. For a less magical (Explicit Is Better Than Implicit) approach, though, `raise CloudError.from_response(resp)` could also work.

**Comment by lmazuel** [comment]
That's an excellent question. Current SDKs are generated from [Autorest](https://github.com/Azure/autorest) and [Swagger files](https://github.com/Azure/azure-rest-api-specs). I think some people have thought about adding some explicit metadata in the Swagger, to allow this, but I don't know the details yet.
May I ask you to open an Autorest bug directly with the exact same message? You could just add a final sentence to say it's not Python specific (but they will get it anyway).
https://github.com/Azure/autorest/issues

FYI @johanste

**Comment by akx** [comment]
Done deal (https://github.com/Azure/autorest/issues/2998).
