### ISSUE TITLE
No support of network/subnet creation

### ISSUE THREAD

**Issue by vmksuw** [Azure/azure-sdk-for-python#335]
Hi,
It seems that sdk doesn't have support for network and subnet creation.
Let me know if it has the support.

Thanks,
Vaibhav

**Comment by huguesv** [comment]
Not yet. Please see the comment I just added to https://github.com/Azure/azure-sdk-for-python/issues/155.

**Comment by vmksuw** [comment]
Thanks for the reply.
Temporarily I locally added support for virtual network/subnet creation in sdk.
