### ISSUE TITLE
substring /virtualNetworks/ not found in subnet_id

### ISSUE THREAD

**Issue by julio-cmdr** [Azure/azure-sdk-for-python#33512]
- **azureml-core**: 
- **1.54.0.post1**: 
- **Windows**:
- **Python 3.8**: 

**Describe the bug**
I'm trying to print workspace.compute_targets, but I'm getting the following error:
![image](https://github.com/Azure/azure-sdk-for-python/assets/24497834/ec75c731-9d9d-4d9e-b260-08fe7267b795)

In the file computeinstance.py, class ComputeInstance, function _initialize(), line 121, the code is trying to extract the information of virtualNetworks from the variable subnet_id. But the information about virtualNetworks inside subnet_id has the letter v capitalized for me: VirtualNetworks

**To Reproduce**
Try to get the compute_networks of a workspace with virtual network.

**Expected behavior**
Print all compute_targets without errors.

**Suggestion**
Change `vnet_name = subnet_id[subnet_id.index("/virtualNetworks/") + len("/virtualNetworks/"):subnet_id.index("/subnets")]` to `vnet_name = subnet_id[subnet_id.index("/VirtualNetworks/") + len("/VirtualNetworks/"):subnet_id.index("/subnets")]`

**Comment by banibrata** [comment]
Thanks for the feedback I added this t our internal backlog for prioritization.

**Comment by isaudagar** [comment]
Hi @julio-cmdr ,
Tried to reproduce this issue but unable to reproduce. 
Could you please check the Network Security Group (NSG) associated with the subnet or network.
Inspect the inbound and outbound rules in the NSG to understand firewall settings.
![image](https://github.com/Azure/azure-sdk-for-python/assets/142884096/ae6d37e2-008f-4799-958b-36d789948f83)

**Comment by isaudagar** [comment]
HI @julio-cmdr,
Could you please edit and save subnet. If edit and save not working then try with delete and recreate if possible.
![image](https://github.com/Azure/azure-sdk-for-python/assets/142884096/ee9019d0-8097-47da-9e2e-c8c47fc91167)

**Comment by isaudagar** [comment]
HI @julio-cmdr, 
Could you please update about above suggestion, Did above approach working for you?

**Comment by julio-cmdr** [comment]
Hi @isaudagar.
Thanks for your reply. Unfortunally, I'm using a resource group that I don't have access to manage the subnets.

To carry out your suggestion to edit and save the subnet (or maybe recreate it), I believe I will need to open an internal ticket, which will probably not be answered, considering the impacts that will be generated by modifying the subnet.

Were you able to reproduce the errors?

**Comment by isaudagar** [comment]
Hi @julio-cmdr, Thanks for response. We tried multiple ways to reproduce but not able to reproduce.

**Comment by julio-cmdr** [comment]
No, the problem has not been resolved. I still have the same problem. I just informed you that my vNet is a managed vNet, which doesn't allow me to perform the requested tests.

**Comment by isaudagar** [comment]
Hi @julio-cmdr, As per my investigation that substring is case sensitive in Python.
subnet resource ID has lowercase "/virtualnetworks/" and the you are searching for index of  "/virtualNetworks/".
please use lowercase and update us.

**Comment by julio-cmdr** [comment]
Hi @isaudagar
I'm just trying to list workspace.compute_targets in my code. The problem is within the azureml-core library. The source of the error is described in this issue.

**Comment by isaudagar** [comment]
Hi @julio-cmdr, 
Could you please explain about below point letter v capitalized, how did you capitalized? 
substring is case sensitive in Python and due to that reason getting error.
![image](https://github.com/Azure/azure-sdk-for-python/assets/142884096/d1839be4-0047-4fc3-89c4-eaa1a8a84874)

**Comment by julio-cmdr** [comment]
This is the original source code of the library azureml-core, with letter v in lower case:
![image](https://github.com/Azure/azure-sdk-for-python/assets/24497834/75599630-8a79-4a93-b0c2-dad870f6abdf)

After editing the library in my local environment, capitalizing letter v, I got it working. But I'm reporting it here so that it can be fixed for all users.

If you prefer, we can have a meeting on Microsoft Teams. I am working in the GMT-3 time zone.

**Comment by isaudagar** [comment]
Hi @julio-cmdr, Above code is working for all users if we are making this change it will break for them . I want to know how and why it is v letter capital for you. Could you please share your teams id to connect.
My teams ID v-isaudagar@microsoft.com.

**Comment by isaudagar** [comment]
Thank you for reporting this issue, This is now fixed and will be released in the next update to azureml-core package.

**Comment by julio-cmdr** [comment]
Thank you, @isaudagar!

**Comment by julio-cmdr** [comment]
After updating to azureml-core==1.55.0.post2, it's working!
