### ISSUE TITLE
Bug Report for Azure Machine Learning 

### ISSUE THREAD

**Issue by SaM-92** [Azure/azure-sdk-for-python#33513]
Package Name: Azure Machine Learning SDK (azure.ai.ml)
Package Version:V2
Operating System: Windows 10
Python Version: 3.9.13

### Describe the bug: 
When attempting to execute a Python script using a command from azure.ai.ml that incorporates an XGBoost model, I encounter an issue related to the environment versioning. Despite trying to customize the environment within the command, I keep receiving an error message indicating the need to assign a version to the environment. However, the Environment class in Azure ML SDK does not seem to accept a version argument.

**Error that I get:  At least one required parameter is missing\u001b[39m\u001b[39m\n\nDetails: \n\n\u001b[31m(x) Failed to extract version when parsing asset my_env of type environments as arm id. Version must be provided**

### To Reproduce
**Steps to reproduce the behavior:**

1. Create a custom environment from a Conda specification (conda_env.yml) using Environment.from_conda_specification.
2. Register the environment to a workspace.
3. Configure a job with command, specifying the environment by name.
4. Submit the job using ml_client.create_or_update.
5. The error occurs indicating a version needs to be assigned to the environment.

**Expected behavior**
I expected the environment to be correctly recognized and the job to be submitted without requiring an explicit version assignment since the Environment class does not accept a version parameter.

```
Conda Environment YAML File

yaml
Copy code
name: my_env
dependencies:
- pip:
  - python=3.9.13
  - azureml-defaults~=1.34.0
  - scikit-learn==1.2.2
  - xgboost==1.7.3
  - numpy==1.23.5
  - pandas==1.5.3


Job Configuration Code:


ws = Workspace.get(name=workspace_name,
                          subscription_id=subscription_id,
                          resource_group=resource_group)

# get dataset id 
ml_client = MLClient(
    DefaultAzureCredential(), subscription_id, resource_group, workspace_name
)

data_asset = ml_client.data.get("my-dataset", version="1")

custom_env = Environment.from_conda_specification(name="my_env", file_path="conda_env.yml")
custom_env.register(workspace=ws)

job = command(
    code="./src",
    command="python train-model-mlflow.py --training_data ${{inputs.training_data}}",
    environment="my_env",
    compute="aml-cluster",
    display_name="building-energy-train",
    experiment_name="demo-test1", 
    tags={"model_type": "xgboost", "model": "my dataset"},
    inputs={'training_data': Input(path=data_asset.id,
              type=AssetTypes.URI_FILE,
              mode=InputOutputModes.RO_MOUNT)}  # Reference the dataset by name
)

# Submit job
returned_job = ml_client.create_or_update(job)
aml_url = returned_job.studio_url
print("Monitor your job at", aml_url)
```
### Additional context
The issue persists despite various attempts to adjust the environment setup and job configuration. The lack of clarity on how to assign a version to the environment when using Azure ML SDK's Environment class is a key concern.

**Comment by SaM-92** [comment]
Thank you indeed!

**Comment by banibrata** [comment]
Could you check your SDK version and make sure only azure-ai-ml package is installed, it should not have Environment.from_conda_specification in SDK v2 , here is the documentation: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-environments-v2?view=azureml-api-2&tabs=python#create-an-environment

**Comment by SaM-92** [comment]
Hi @banibrata , thank you very much for pointing this out and sorry for the late reply as I was on leave. 

Yes, this one solved the issue. Unfortunately, the. changes between v1 and V2 sometimes can be very confusing as I could not find a proper documentation to tell me what is the V2 alternative for V1 commands. 

I also flagged the same issue here but no once could resolved it. 
https://learn.microsoft.com/en-us/answers/questions/1462405/assigning-version-to-custom-environment-in-azure-a?comment=question#newest-question-comment 

Any way, thanks for your help and assistance! :)
