### ISSUE TITLE
Problem with traffic manager is causing `az aks list` to fail

### ISSUE THREAD

**Issue by luisdavim** [Azure/azure-sdk-for-python#3353]
You can see more details in this slack thread:
https://kubernetes.slack.com/archives/C5HJXTT9Q/p1535546773000100

> I think it’s related to api geo-location and trafficmanager failure. I guess the api server returns a paginated list with a http://acs-eastus.trafficmanager.net address as the next page base url. Even if your list is fitting on a single page, that url is tried.
> 
> 3 strange things are going on here, 1. The base url is changed from https://management.azure.com to http://acs-eastus.trafficmanager.net
> 2. The protocol is now http
> 3. This should be the last page. So why a next_link?

**Comment by lmazuel** [comment]
@mboersma I don't know if it's a AKS or TF issue? Thought?
