### ISSUE TITLE
Cannot import AzureOpenAIEmbeddingSkill from azure-search-documents:11.4.0

### ISSUE THREAD

**Issue by kboom** [Azure/azure-sdk-for-python#33597]
- **azure-search-documents**: 
- **11.4.0**: 
- **Win 11**:
- **3.11**: 

**Describe the bug**
ImportError: cannot import name 'AzureOpenAIEmbeddingSkill' from 'azure.search.documents.indexes.models'

**To Reproduce**
Simply try to import it:
```
from azure.search.documents.indexes.models import (
    AzureOpenAIEmbeddingSkill
)
```

Same happens for 

1. SemanticConfiguration,  
2. SemanticField,  
3. SemanticSettings

**Expected behavior**
It should import this type. It is referenced in most tutorials... without it, the library is unusable.

**Comment by xiangyan99** [comment]
Took offline. This is by design.
