### ISSUE TITLE
It it possible to create non english windows azure vm  ?

### ISSUE THREAD

**Issue by dimag25** [Azure/azure-sdk-for-python#33609]
It it possible to create non english windows azure vm  ?
with built in azure vm image.
Tried to find here without success
https://az-vm-image.info/

please advise.

**Comment by xiangyan99** [comment]
Could you give more details what you want to achieve?

E.g. do you want to use API/SDK or do you want to create VM using Azure portal?

**Comment by dimag25** [comment]
im creating vm via python sdk , im using sku win10-22h2 , its english as default.
 my question is there are available skus with builtin other non english languages? or I need to modify the language on created vm via scripts?

**Comment by ChenxiJiang333** [comment]
Hi, @dimag25 
According to https://az-vm-image.info/?cmd=--all+--publisher+MicrosoftWindowsDesktop+--offer+windows-10+--sku+win10-22h2, for win10-22h2, it seems there're only skus with english or chinese built in, so if you need other language preferred, please modify it through scripts.
