### ISSUE TITLE
Can't use environments from registry directly for model endpoint deployment.

### ISSUE THREAD

**Issue by alegend4u** [Azure/azure-sdk-for-python#33611]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.12.0
- **Operating System**: Ubuntu 22.04
- **Python Version**: 3.11.2

**Describe the bug**
There is no way to use Environments from Registry which are workspace agnostic to deploy models without registering the same Environment to the workspace. Even registering an Environment from registry to a workspace isn't possible right now.

**To Reproduce**
1. Attach a KubernetesCompute to the workspace
2. Open Azure ML Studio
3. Open Models
4. Select a model and click deploy real-time (or batch)
![image](https://github.com/Azure/azure-sdk-for-python/assets/20675955/ceb366af-ce72-4db3-8df0-8b8d037b8514)

5. Select Subscription and workspace
![image](https://github.com/Azure/azure-sdk-for-python/assets/20675955/f1ffabac-8d30-46cc-af5d-a02526efb63f)

6. Select endpoint as new and give it a name.
7. Select compute as Kubernetes and click Next.
8. Keep default values for `Model` and `Deployment` sections and click Next to go to `Code + Environment` section.
![image](https://github.com/Azure/azure-sdk-for-python/assets/20675955/3c86bd22-3ade-41e8-b46e-4a19de29281d)

9. Select custom environments and it'll only show environments from this workspace even though I have other environments registered in the global ML registry.
![image](https://github.com/Azure/azure-sdk-for-python/assets/20675955/e6c42302-e1db-47d5-a91f-aa690e321983)

**Expected behavior**
When selected "Custom Environments" in `Environment Type` drop down, it should also include Environments from the global registry.

**Screenshots**

**Additional context**
If tried to achieve same thing using python SDK `azure-ai-ml`,
```
KubernetesOnlineDeployment(
   ...
   environment=ml_client_registry.environments.get(name=env_name, version=env_version),
   ...
)
```
It fails with `ACRTokenExchangeFailed` even though the workspace's identity has all the required role assignments on the Azure ML Registry.

**Comment by YalinLi0312** [comment]
Hi @alegend4u , thanks for your contact, we'll investigate ASAP.

@azureml-github Can anyone in ml team help on it?

**Comment by alegend4u** [comment]
Hi @banibrata ,

Here are the Steps to reproduce using SDK:

1. Make sure a KubernetesCompute is attached to the workspace.
2. Register an environment to the registry (not the workspace).
Here's the output of `print(ml_client_registry.environments.get(name=model_environment_name, version=model_environment_version))`:
```
creation_context:
  created_at: '2023-10-19T11:26:56.976309+00:00'
  created_by: Rishabh Prajapati
  created_by_type: User
  last_modified_at: '2023-10-19T11:26:56.976309+00:00'
  last_modified_by: Rishabh Prajapati
  last_modified_by_type: User
description: ''
id: azureml://registries/soroco-wgm-dev/environments/pytorch_transformers/versions/2
name: pytorch_transformers
os_type: linux
tags: {}
version: '2'
```
3. Register a model to the workspace. (Using model from registry doesn't work either. Refer #33598)
4. Create `MLClient` instances for workspace and registry.
```
ml_client_workspace = MLClient(
      DefaultAzureCredential(),
      subscription_id,
      resource_group,
      workspace_name,
      logging_enable=True,
  )

ml_client_registry = MLClient(
    credential=DefaultAzureCredential(),
    registry_name=registry_name,
    registry_location=registry_location,
    logging_enable=True,
)
```
5. Get environment from registry and model from workspace
```
environment = ml_client_registry.environments.get(name=model_environment_name, version=model_environment_version)
model = ml_client_workspace.models.get(name=model_name, version=model_version)
```
6. Create endpoint and deployment objects
```
endpoint = KubernetesOnlineEndpoint(
    name=endpoint_name,
    description=endpoint_description,
    compute=compute,
    auth_mode="key",
)
deployment = KubernetesOnlineDeployment(
    name=deployment_name,
    endpoint_name=endpoint_name,
    model=model.id,
    environment=environment.id,
    code_configuration=CodeConfiguration(
        code=str(model_script_path.parent), scoring_script=model_script_path.name
    ),
    instance_type=instance_type,
    instance_count=instance_count,
)
```
7. Create the endpoint and deployment.
```
ml_client_workspace.online_endpoints.begin_create_or_update(endpoint).result()
ml_client_workspace.online_deployments.begin_create_or_update(deployment).result()  # This raises.
```

The last statement above raises following exception with traceback:

```
---------------------------------------------------------------------------
OperationFailed                           Traceback (most recent call last)
File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:757, in LROBasePolling.run(self)
    756 try:
--> 757     self._poll()
    759 except BadStatus as err:

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:789, in LROBasePolling._poll(self)
    788 if _failed(self.status()):
--> 789     raise OperationFailed("Operation failed or canceled")
    791 final_get_url = self._operation.get_final_get_url(self._pipeline_response)

OperationFailed: Operation failed or canceled

The above exception was the direct cause of the following exception:

HttpResponseError                         Traceback (most recent call last)
Cell In[38], line 1
----> 1 ml_client_workspace.online_deployments.begin_create_or_update(deployment).result()

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:251, in LROPoller.result(self, timeout)
    242 def result(self, timeout: Optional[float] = None) -> PollingReturnType_co:
    243     """Return the result of the long running operation, or
    244     the result available after the specified timeout.
    245 
   (...)
    249     :raises ~azure.core.exceptions.HttpResponseError: Server problem with the query.
    250     """
--> 251     self.wait(timeout)
    252     return self._polling_method.resource()

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/tracing/decorator.py:78, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
     76 span_impl_type = settings.tracing_implementation()
     77 if span_impl_type is None:
---> 78     return func(*args, **kwargs)
     80 # Merge span is parameter is set, but only if no explicit parent are passed
     81 if merge_span and not passed_in_parent:

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:270, in LROPoller.wait(self, timeout)
    266 self._thread.join(timeout=timeout)
    267 try:
    268     # Let's handle possible None in forgiveness here
    269     # https://github.com/python/mypy/issues/8165
--> 270     raise self._exception  # type: ignore
    271 except TypeError:  # Was None
    272     pass

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:185, in LROPoller._start(self)
    181 """Start the long running operation.
    182 On completion, runs any callbacks.
    183 """
    184 try:
--> 185     self._polling_method.run()
    186 except AzureError as error:
    187     if not error.continuation_token:

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:772, in LROBasePolling.run(self)
    765     raise HttpResponseError(
    766         response=self._pipeline_response.http_response,
    767         message=str(err),
    768         error=err,
    769     ) from err
    771 except OperationFailed as err:
--> 772     raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err

HttpResponseError: (None) DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:ACRTokenExchangeForbidden Details:Cluster exchange ACR token failed because AAD token is unauthorized. The role assignment takes some time, please wait a moment and try again. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
Code: None
Message: DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:ACRTokenExchangeForbidden Details:Cluster exchange ACR token failed because AAD token is unauthorized. The role assignment takes some time, please wait a moment and try again. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
Exception Details:	(None) DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:ACRTokenExchangeForbidden Details:Cluster exchange ACR token failed because AAD token is unauthorized. The role assignment takes some time, please wait a moment and try again. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
	Code: None
	Message: DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:ACRTokenExchangeForbidden Details:Cluster exchange ACR token failed because AAD token is unauthorized. The role assignment takes some time, please wait a moment and try again. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
```

Please note that the UserAssigned identity that is assigned to workspace and the attached KubernetesCompute has following role assignments:

![Screenshot 2023-12-20 000602](https://github.com/Azure/azure-sdk-for-python/assets/20675955/0c6f7da0-76ef-4666-aad3-7445e2d5140a)

**Comment by yuyue9284** [comment]
> Hi @banibrata ,
> 
> Here are the Steps to reproduce using SDK:
> 
> 1. Make sure a KubernetesCompute is attached to the workspace.
> 2. Register an environment to the registry (not the workspace).
>    Here's the output of `print(ml_client_registry.environments.get(name=model_environment_name, version=model_environment_version))`:
> 
> ```
> creation_context:
>   created_at: '2023-10-19T11:26:56.976309+00:00'
>   created_by: Rishabh Prajapati
>   created_by_type: User
>   last_modified_at: '2023-10-19T11:26:56.976309+00:00'
>   last_modified_by: Rishabh Prajapati
>   last_modified_by_type: User
> description: ''
> id: azureml://registries/soroco-wgm-dev/environments/pytorch_transformers/versions/2
> name: pytorch_transformers
> os_type: linux
> tags: {}
> version: '2'
> ```
> 
> 3. Register a model to the workspace. (Using model from registry doesn't work either. Refer [Can't deploy a model directly from AML registry to a workspace: InferenceContainerConfiguration.ServingContainer.Image: 'Image' must not be empty. #33598](https://github.com/Azure/azure-sdk-for-python/issues/33598))
> 4. Create `MLClient` instances for workspace and registry.
> 
> ```
> ml_client_workspace = MLClient(
>       DefaultAzureCredential(),
>       subscription_id,
>       resource_group,
>       workspace_name,
>       logging_enable=True,
>   )
> 
> ml_client_registry = MLClient(
>     credential=DefaultAzureCredential(),
>     registry_name=registry_name,
>     registry_location=registry_location,
>     logging_enable=True,
> )
> ```
> 
> 5. Get environment from registry and model from workspace
> 
> ```
> environment = ml_client_registry.environments.get(name=model_environment_name, version=model_environment_version)
> model = ml_client_workspace.models.get(name=model_name, version=model_version)
> ```
> 
> 6. Create endpoint and deployment objects
> 
> ```
> endpoint = KubernetesOnlineEndpoint(
>     name=endpoint_name,
>     description=endpoint_description,
>     compute=compute,
>     auth_mode="key",
> )
> deployment = KubernetesOnlineDeployment(
>     name=deployment_name,
>     endpoint_name=endpoint_name,
>     model=model.id,
>     environment=environment.id,
>     code_configuration=CodeConfiguration(
>         code=str(model_script_path.parent), scoring_script=model_script_path.name
>     ),
>     instance_type=instance_type,
>     instance_count=instance_count,
> )
> ```
> 
> 7. Create the endpoint and deployment.
> 
> ```
> ml_client_workspace.online_endpoints.begin_create_or_update(endpoint).result()
> ml_client_workspace.online_deployments.begin_create_or_update(deployment).result()  # This raises.
> ```
> 
> The last statement above raises following exception with traceback:
> 
> ```
> ---------------------------------------------------------------------------
> OperationFailed                           Traceback (most recent call last)
> File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:757, in LROBasePolling.run(self)
>     756 try:
> --> 757     self._poll()
>     759 except BadStatus as err:
> 
> File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:789, in LROBasePolling._poll(self)
>     788 if _failed(self.status()):
> --> 789     raise OperationFailed("Operation failed or canceled")
>     791 final_get_url = self._operation.get_final_get_url(self._pipeline_response)
> 
> OperationFailed: Operation failed or canceled
> 
> The above exception was the direct cause of the following exception:
> 
> HttpResponseError                         Traceback (most recent call last)
> Cell In[38], line 1
> ----> 1 ml_client_workspace.online_deployments.begin_create_or_update(deployment).result()
> 
> File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:251, in LROPoller.result(self, timeout)
>     242 def result(self, timeout: Optional[float] = None) -> PollingReturnType_co:
>     243     """Return the result of the long running operation, or
>     244     the result available after the specified timeout.
>     245 
>    (...)
>     249     :raises ~azure.core.exceptions.HttpResponseError: Server problem with the query.
>     250     """
> --> 251     self.wait(timeout)
>     252     return self._polling_method.resource()
> 
> File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/tracing/decorator.py:78, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
>      76 span_impl_type = settings.tracing_implementation()
>      77 if span_impl_type is None:
> ---> 78     return func(*args, **kwargs)
>      80 # Merge span is parameter is set, but only if no explicit parent are passed
>      81 if merge_span and not passed_in_parent:
> 
> File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:270, in LROPoller.wait(self, timeout)
>     266 self._thread.join(timeout=timeout)
>     267 try:
>     268     # Let's handle possible None in forgiveness here
>     269     # https://github.com/python/mypy/issues/8165
> --> 270     raise self._exception  # type: ignore
>     271 except TypeError:  # Was None
>     272     pass
> 
> File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:185, in LROPoller._start(self)
>     181 """Start the long running operation.
>     182 On completion, runs any callbacks.
>     183 """
>     184 try:
> --> 185     self._polling_method.run()
>     186 except AzureError as error:
>     187     if not error.continuation_token:
> 
> File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:772, in LROBasePolling.run(self)
>     765     raise HttpResponseError(
>     766         response=self._pipeline_response.http_response,
>     767         message=str(err),
>     768         error=err,
>     769     ) from err
>     771 except OperationFailed as err:
> --> 772     raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err
> 
> HttpResponseError: (None) DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:ACRTokenExchangeForbidden Details:Cluster exchange ACR token failed because AAD token is unauthorized. The role assignment takes some time, please wait a moment and try again. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
> Code: None
> Message: DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:ACRTokenExchangeForbidden Details:Cluster exchange ACR token failed because AAD token is unauthorized. The role assignment takes some time, please wait a moment and try again. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
> Exception Details:	(None) DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:ACRTokenExchangeForbidden Details:Cluster exchange ACR token failed because AAD token is unauthorized. The role assignment takes some time, please wait a moment and try again. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
> 	Code: None
> 	Message: DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:ACRTokenExchangeForbidden Details:Cluster exchange ACR token failed because AAD token is unauthorized. The role assignment takes some time, please wait a moment and try again. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
> ```
> 
> Please note that the UserAssigned identity that is assigned to workspace and the attached KubernetesCompute has following role assignments:
> 
> ![Screenshot 2023-12-20 000602](https://private-user-images.githubusercontent.com/20675955/291682792-0c6f7da0-76ef-4666-aad3-7445e2d5140a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTU3MzQsIm5iZiI6MTcwMzIxNTQzNCwicGF0aCI6Ii8yMDY3NTk1NS8yOTE2ODI3OTItMGM2ZjdkYTAtNzZlZi00NjY2LWFhZDMtNzQ0NWUyZDUxNDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAzMjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZjBmNTU2YWI2MWI0ZWFjZTg2MDVhYmZmMzY2YWExMmM3ZTI5OWQxNTJkM2VkZjc2OWMwYTgyNTlhZmI4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QCDOYLe9eFk6Nm91BTcrxAexx9jHEiRiZIxq7WNaaEc)

Hi @alegend4u , have you granted the environment's ACR `ACRPull` role to the online endpoint's identity? If it still failed, could you provide the subscription, resource group, workspace, endpoint name?

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-resources-from-endpoints-managed-identities?view=azureml-api-2&tabs=system-identity-cli#give-access-permission-to-the-managed-identity

**Comment by alegend4u** [comment]
> Hi @alegend4u , have you granted the environment's ACR ACRPull role to the online endpoint's identity? If it still failed, could you provide the subscription, resource group, workspace, endpoint name?
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-resources-from-endpoints-managed-identities?view=azureml-api-2&tabs=system-identity-cli#give-access-permission-to-the-managed-identity

@yuyue9284, the endpoint is able to fetch environments images if the selected environment is registered in the workspace. Meaning it has required permissions to access workspace's own ACR.

However, the issue arises when the selected environment for endpoint is from Azure Machine Learning Registry (which is workspace agnostic). Also refer the step 2 in "Steps to Reproduce", the `id` of the environment says `azureml://registries/<registry_name>/environments/<env_name>/versions/2`. 

Now as shown in the screenshot (which lists the role assignments of the managed identity assigned to the workspace and `KubernetesCompute` attached to it), the managed identity has role `Contributor` role assigned to the Azure Machine Learning Registry. Still, it's raising the error.

One more thing I've observed: In the resource overview page of Azure Machine Learning Registry, there's an attribute named `managed resource group` which contains a Storage Account and an ACR. The managed resource group's Access Control section has `Deny Assignments` set as below:
![image](https://github.com/Azure/azure-sdk-for-python/assets/20675955/d735fd74-b61e-4278-9d21-6d6d1462dc7e)

This means that I can't assign `ACRPull` role on that managed resource group's ACR to that managed identity.

**Comment by yuyue9284** [comment]
> > Hi @alegend4u , have you granted the environment's ACR ACRPull role to the online endpoint's identity? If it still failed, could you provide the subscription, resource group, workspace, endpoint name?
> > https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-resources-from-endpoints-managed-identities?view=azureml-api-2&tabs=system-identity-cli#give-access-permission-to-the-managed-identity
> 
> @yuyue9284, the endpoint is able to fetch environments images if the selected environment is registered in the workspace. Meaning it has required permissions to access workspace's own ACR.
> 
> However, the issue arises when the selected environment for endpoint is from Azure Machine Learning Registry (which is workspace agnostic). Also refer the step 2 in "Steps to Reproduce", the `id` of the environment says `azureml://registries/<registry_name>/environments/<env_name>/versions/2`.
> 
> Now as shown in the screenshot (which lists the role assignments of the managed identity assigned to the workspace and `KubernetesCompute` attached to it), the managed identity has role `Contributor` role assigned to the Azure Machine Learning Registry. Still, it's raising the error.
> 
> One more thing I've observed: In the resource overview page of Azure Machine Learning Registry, there's an attribute named `managed resource group` which contains a Storage Account and an ACR. The managed resource group's Access Control section has `Deny Assignments` set as below: ![image](https://private-user-images.githubusercontent.com/20675955/292477384-d735fd74-b61e-4278-9d21-6d6d1462dc7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzM1ODQsIm5iZiI6MTcwMzQ3MzI4NCwicGF0aCI6Ii8yMDY3NTk1NS8yOTI0NzczODQtZDczNWZkNzQtYjYxZS00Mjc4LTlkMjEtNmQ2ZDE0NjJkYzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDAzMDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNzBkYWIwOWYzZWFjYjRlYmQ1YTJiNDA4ZTRkODkwYjVkMGUzNmYzMzQ0MmY5MWRiMjNlNTdjY2FmMGYzN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ik7vDkk3r4BdhTbN2i2skQKCjqIdokwh4SR7wGmmjtw)
> 
> This means that I can't assign `ACRPull` role on that managed resource group's ACR to that managed identity.

Hi @alegend4u, registry is not supported for compute type: kubernetes,  if you are using the CLI v2 it should return the error message state that it is not supported explicitly, sorry for the confusion.

**Comment by alegend4u** [comment]
Thanks for letting me know.
Currently, I have a workaround that is about downloading the weights from the registry to local and then registering to the workspace.
```
ml_client_registry.models.download(
    name=model_name, version=model_version, download_path=download_path
)
ml_client_workspace.models.create_or_update(
    Model(name=model_name, version=model_version, path=Path(download_path) / model_name / model_name)
)
```

But this is a bit tedious.

Just like we have a way to share model [(source)](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-share-models-pipelines-across-workspaces-with-registries?view=azureml-api-2&tabs=python#share-a-model-from-workspace-to-registry):
```
# share the model from the registry to workspace
ml_client.models.share(name="nyc-taxi-model", version=1, registry_name=<registry_name>, share_with_name=<new-name>, share_with_version=<new-version>)
```

Do we have a way to share an environment/model from a registry to a workspace directly?
If not, is there any roadmap planned for this feature?

**Comment by yuyue9284** [comment]
> Thanks for letting me know. Currently, I have a workaround that is about downloading the weights from the registry to local and then registering to the workspace.
> 
> ```
> ml_client_registry.models.download(
>     name=model_name, version=model_version, download_path=download_path
> )
> ml_client_workspace.models.create_or_update(
>     Model(name=model_name, version=model_version, path=Path(download_path) / model_name / model_name)
> )
> ```
> 
> But this is a bit tedious.
> 
> Just like we have a way to share model [(source)](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-share-models-pipelines-across-workspaces-with-registries?view=azureml-api-2&tabs=python#share-a-model-from-workspace-to-registry):
> 
> ```
> # share the model from the registry to workspace
> ml_client.models.share(name="nyc-taxi-model", version=1, registry_name=<registry_name>, share_with_name=<new-name>, share_with_version=<new-version>)
> ```
> 
> Do we have a way to share an environment/model from a registry to a workspace directly? If not, is there any roadmap planned for this feature?

Currently there is no plan to support registry.
