### ISSUE TITLE
[Document Intelligence] Reference docs not showing up correctly

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#33620]
The reference documentation on MS learn is not showing up correctly for the Document Intelligence preview SDK. The methods on the client are not showing up: https://learn.microsoft.com/en-us/python/api/azure-ai-documentintelligence/azure.ai.documentintelligence.documentintelligenceclient?view=azure-python-preview#methods

Example of how the methods show up for the Form Recognizer SDK: https://learn.microsoft.com/en-us/python/api/azure-ai-formrecognizer/azure.ai.formrecognizer.documentanalysisclient?view=azure-python#methods

**Comment by YalinLi0312** [comment]
Issue has been fixed.
