### ISSUE TITLE
retrieve the AML job's compute statistics

### ISSUE THREAD

**Issue by TheBugKing** [Azure/azure-sdk-for-python#33633]
**Is your feature request related to a problem? Please describe.**
is there any way to retrieve the aml job's compute statistics as shown below?
I am not able to find it in any documentation
![image](https://github.com/Azure/azure-sdk-for-python/assets/40294161/6ea20b9b-a2a6-48c9-a35d-b8761e2e7b68)

**Describe the solution you'd like**
way to retrieve the aml job's compute as shown in the monitoring tab:
![image](https://github.com/Azure/azure-sdk-for-python/assets/40294161/48158e47-ed54-427f-a1d7-81d0e5f0de45)

**Describe alternatives you've considered**
Could not find any alternative way to programmatically retrieve the data using sdk v2

**Additional context**
None

**Comment by diondrapeck** [comment]
@banibrata-de is this your area? If not, do you know the right character.

**Comment by banibrata-de** [comment]
Right now unfortunately we do not have a way to get it programmatically, we may revisit this later using SDK thanks for your feedback
