### ISSUE TITLE
Typo on DnsResolverManagementClient

### ISSUE THREAD

**Issue by liviozanol** [Azure/azure-sdk-for-python#33631]
Just a minor typo at https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/dnsresolver/azure-mgmt-dnsresolver/README.md

`DnsresolverManagementClient` should be `DnsResolverManagementClient`

**Comment by liviozanol** [comment]
PR: https://github.com/Azure/azure-sdk-for-python/pull/33632/files

**Comment by pvaneck** [comment]
Closed via https://github.com/Azure/azure-sdk-for-python/pull/33632
