### ISSUE TITLE
DataLakeFileClient.upload_data fails when overwrite=False

### ISSUE THREAD

**Issue by sharmuz** [Azure/azure-sdk-for-python#33630]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.14.0
- **Operating System**: macOS 14.2
- **Python Version**: 3.11.4

**Describe the bug**
DataLakeFileClient.upload_data fails when argument overwrite is set to False, despite no such file already existing. I receive "ResourceNotFoundError: The specified path does not exist." When overwrite is to True (again no file already present), the operation is successful as expected.

**To Reproduce**
1. Execute following code:

```python
# Perform usual steps to create file_system_client
directory_client = file_system_client.get_directory_client(
    directory="my-directory"
)
file_client = directory_client.get_file_client(
    file="my-data.csv"
)
my_df = pd.DataFrame({
    'a': ['apple', 'carrot'],
    'b': [1, 2],
})
csv_file = new_df.to_csv(index=False)
file_client.upload_data(csv_file, overwrite=False)
```

**Expected behavior**
Data successfully uploaded --> new file present in ADLS.

**Screenshots**

**Additional context**
Older issue seems relevant:
https://github.com/Azure/azure-sdk-for-python/issues/16166

**Comment by pvaneck** [comment]
Thanks for the issue. I'll tag the appropriate people, and we'll investigate as soon as we can.

**Comment by jalauzon-msft** [comment]
Hi @sharmuz, this is by-design and has to do with how the Datalake APIs work. Basically `upload_data` requires the file already be created or it will create the file for you if `overwrite=True`. Creating a file and appending data are actually two different API calls and the Datalake append APIs do not support appends from multiple sources and therefore access conditions must be used when performing appends.

So, for `upload_data` you must either create the file first and specify the required match conditions OR specify `overwrite=True` which will internally create the file for you and specify the correct access conditions for the append operation. Here are some examples:

```py
from azure.core import MatchConditions

# 1. Create file first, then call upload_data to perform the append/flush
# NOTE: create_file WILL OVERWRITE an existing file by default. To prevent this, you must use match conditions like this:
response = file_client.create_file(match_condition=MatchConditions.IfMissing)
file_client.upload_data(data, overwrite=False, match_condition=MatchConditions.IfNotModified, etag=response['etag'])

# 2. Use upload_data with overwrite=True AND match conditions
file_client.upload_data(data, overwrite=True, match_condition=MatchConditions.IfMissing)

# 3. Use a create + append/flush workflow yourself.
file_client.create_file(match_condition=MatchConditions.IfMissing)
file_client.append_data(data, offset=0, length=len(data), flush=True)
```

I realize this may be a bit confusing and is not very well documented so we can work on that but basically if you think of `overwrite` parameter more as "whether to create the file or not" and then use match conditions for controlling whether to overwrite an existing file or not, it should hopefully be a bit more clear. Thanks.

**Comment by sharmuz** [comment]
Clear, thanks!
