### ISSUE TITLE
Communication JobRouter Sample Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#33658]
1.
This issue exists in each function and each sample file, sections below are how it occurs in sample `exception_policy_crud_ops.py`
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py#L23),[link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py#L32),[link3](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py#L74),[link4](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py#L143),[link5](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py#L206), [link6](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py#L219),[link7](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py#L234),[link8](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py#L253)

![image](https://github.com/Azure/azure-sdk-for-java/assets/139106314/60377998-43e7-4549-a0d4-4cdfc2783246)
![image](https://github.com/Azure/azure-sdk-for-java/assets/139106314/39a8ca7b-ed18-4a12-ab45-cffbfaa7b981)

**Reason:**
Variable names are incorrect.

**Suggestion:**
1.Update code to `connection_string = os.environ["AZURE_COMMUNICATION_SERVICE_CONNECTION_STRING"]`
2.Update code to `connection_string`

@rohit-ganguly , @lmazuel , @lfraleigh ,  @mayurid ,  @sarkar-rajarshi for notification.

**Comment by lmazuel** [comment]
Closing, as PR has been merged
