### ISSUE TITLE
`--delete-snapshots` `include-leased` not allowed when deleting file share with a snapshot with active lease

### ISSUE THREAD

**Issue by calvinhzy** [Azure/azure-sdk-for-python#33659]
- **Package Name**: azure-storage-file-share
- **Package Version**:  12.16.0b1
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Redirected from this CLI issue. Fix https://github.com/Azure/azure-cli/issues/21196
Seems like the latest SDK version has not allowed the new delete option `include-leased`
https://github.com/Azure/azure-sdk-for-python/blob/977fd0e30dfb3c4a05b0f1d9b5ed8ddb37651783/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/models/_azure_file_storage_enums.py#L33-L34

Seems only `include` is allowed here
https://github.com/Azure/azure-sdk-for-python/blob/977fd0e30dfb3c4a05b0f1d9b5ed8ddb37651783/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py#L491-L499

**To Reproduce**
1. Run the function with `delete_snapshots=include-leased`

**Expected behavior**
Should allow this option `include-leased`

**Screenshots**

**Additional context**

**Comment by jalauzon-msft** [comment]
As discussed internally, it looks like the Python SDK is missing this option. We will work to get this added in an upcoming release. Thanks!

**Comment by jalauzon-msft** [comment]
Addressed with #34042. Will be included in the next release.
