### ISSUE TITLE
ClientAssertionCredential constructor fails if kwargs are provided

### ISSUE THREAD

**Issue by ppaglilla** [Azure/azure-sdk-for-python#33673]
- **Package Name**: azure-identity
- **Package Version**: 1.15.0
- **Operating System**: Linux 6.1.58+ x86_64 GNU/Linux
- **Python Version**: 3.11.5 and 3.9.2

**Describe the bug**
The [ClientAssertionCredential](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/client_assertion.py) constructor accepts the `authority` and `additionally_allowed_tenants` arguments through kwargs. However, if any of those arguments are provided, they are [incorrectly bubbled up through a super().__init__(**kwargs) call](https://github.com/Azure/azure-sdk-for-python/blob/6aa171f81c0111996a2785b14864e961a7942e87/sdk/identity/azure-identity/azure/identity/_credentials/client_assertion.py#L44) to `GetTokenMixin` and `abc.ABC`. That ultimately makes construction fail with:

```
super(GetTokenMixin, self).__init__(*args, **kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**To Reproduce**
``` python
from typing import Callable
from azure.identity import ClientAssertionCredential

tenant_id: str= "TENANT_ID"
client_id: str= "CLIENT_ID"
func: Callable[[], str] = lambda: "TOKEN"

credential: ClientAssertionCredential = ClientAssertionCredential(
    tenant_id=tenant_id,
    client_id=client_id,
    func=func,
    additionally_allowed_tenants=[])
```

**Expected behavior**
The `ClientAssertionCredential` object is built successfully.

**Additional context**
I'm currently working around this by forcefully inspecting the credential object and injecting the settings as needed.

``` python
credential: ClientAssertionCredential = ClientAssertionCredential(
    tenant_id=tenant_id,
    client_id=client_id,
    func=func)

credential._client._additionally_allowed_tenants = []
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
The fix is merged. It will be available in next release.
