### ISSUE TITLE
failed to install azure-ai-vision

### ISSUE THREAD

**Issue by MyNameIsTakenOMG** [Azure/azure-sdk-for-python#33676]
- **Package Name**: azure-ai-vision
- **Package Version**:  latest version 0.15.1b1
- **Operating System**: macos
- **Python Version**: 3.12.1

**Describe the bug**
unable to install the azure-ai-vision package.  Error message: `ERROR: Could not find a version that satisfies the requirement azure-ai-vision==0.15.1b1 (from versions: none)` & `ERROR: No matching distribution found for azure-ai-vision==0.15.1b1`

**To Reproduce**
1.  python3 -m venv venv
2. source venv/bin/activate
3. pip install azure-ai-vision==0.15.1b1

**Expected behavior**
The package should be installed successfully.

**Screenshots**
<img width="834" alt="Screenshot 2024-01-01 at 4 55 44 PM" src="https://github.com/Azure/azure-sdk-for-python/assets/44120999/2be92b6e-bc17-4d55-978e-f65b1024bcf7">

**Additional context**
I'm studying the Module: [Detect, analyze, and recognize faces](https://learn.microsoft.com/en-us/training/modules/detect-analyze-recognize-faces/?WT.mc_id=cloudskillschallenge_045dddda-f6f3-4077-8072-7d5b157b3849&ns-enrollment-type=Collection&ns-enrollment-id=5d3kh0jz4gp). And I tried to follow the exercise **Exercise - Detect, analyze, and identify faces** to install the package, but couldn't install it
successfully.  [The exercise link](https://microsoftlearning.github.io/mslearn-ai-vision/Instructions/Exercises/04-face-service.html)

**Comment by xiangyan99** [comment]
Thanks for reaching out.

azure-ai-vision 0.15.1b1 does not have mac support.

https://pypi.org/project/azure-ai-vision/0.15.1b1/#files

**Comment by MyNameIsTakenOMG** [comment]
@xiangyan99  Thank you for the response! I already switched to Windows env, and it worked as expected. I'm going to close this issue now.

**Comment by carlosarturoceron** [comment]
dang! stuck here for sometime and i was wondering if maybe it had to do something with Mac.

**Comment by zjubirdfly** [comment]
Just a FYI, I have the same issue on Debian.
