### ISSUE TITLE
list images python api call not listing the images present on the azure account.

### ISSUE THREAD

**Issue by prmjh4** [Azure/azure-sdk-for-python#33688]
How to list Azure images using python API calls?
I want to use Azure python SDK/API calls to list all images that are available in my account. This is to implement the functionality of creating a virtual machine using custom images. I take the customer image name or id as the user input for creating a VM, and I want to use the Azure python API calls to validate if that image name/id is correct. Please let me know how I can achieve this using Python Azure API calls.
I saw on the Azure Python SDK, a link where sample code for list all images is there but that link I believe is not working now.
I tried the following code to list but is not responding and no error is also reported as well for the script
images = compute_client.images.list_by_resource_group(resource_group)
and
images = compute_client.images.list()

Please help me out with the request.
Thanks!

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi @prmjh4 
Sorry for the delay response. If you want to validate the image used in an existing VM, through python, you can run:
```
response = client.virtual_machines.get(resource_group_name, vm_name)
print(response.storage_profile.image_reference)
```
`client.images.list()` is for the custom images or so called `my image`,  which you uploaded to Azure Portal though this [method](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/generated_samples/image_examples/image_create_from_ablob.py). To create a VM with an image in this type through python, see sample https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/generated_samples/virtual_machine_examples/virtual_machine_create_from_acustom_image.py.

`shared image` are your images stored on Azure Portal in another way, storing multiple images in a [gallery](https://learn.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli), specified by parameters: Publisher, Offer and Sku. To use it ,see https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/generated_samples/virtual_machine_examples/virtual_machine_create_from_ageneralized_shared_image.py.

`community image` are images from community gallery, to create a community gallery: https://learn.microsoft.com/en-us/azure/virtual-machines/create-gallery?tabs=portal%2Cportaldirect%2Cportal2#create-a-community-gallery.

Under `masterplace` there are the images provided by Azure, use it by inputting its parameters: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/generated_samples/virtual_machine_examples/virtual_machine_create_linux_vm_with_automatic_by_platform_settings.py#L64 

For your final question, I'm not pretty sure if there's something similar to image project, in Azure, images are specified whether by its defination(Publisher, Offer, Sku, Version) or its resource id.

Hope that answers your question. Please know that I'm not domain expert, for further queries on service side, it's better to seek help from service team https://github.com/Azure/azure-rest-api-specs.
