### ISSUE TITLE
Cannot get ManagedIdentity from a VM within Azure ML

### ISSUE THREAD

**Issue by mauibar** [Azure/azure-sdk-for-python#33694]
- **Azure Identity**: 
- **1.15.0**: 
- **Linux**:
- **3.8.5**: 

**Describe the bug**
This is more a question than a bug as it works for other users but not for this specific one and I am a bit desperate.

We are not able to retrieve Azure Managed Identity from a notebook running on a VM inside Azure ML workspace.

The user gets the following error:

> ClientAuthenticationError: ChainedTokenCredential failed to retrieve a token from the included credentials. Attempted credentials: EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue. ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8" Content: SSO failure: unable to retrieve a token. Error Token service plemaitre-cpu2. Token not found To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.

We tried to get the token manually using this piece of code:

```
import os
import requests
msi_endpoint = os.environ.get("MSI_ENDPOINT", None)
msi_secret = os.environ.get("MSI_SECRET", None)
client_id = os.environ.get("UAI_CLIENT_ID", None)

print(msi_endpoint)
print(msi_secret)
print(client_id)

token_url = msi_endpoint + "?resource=https://management.azure.com"
headers = {"secret": msi_secret, "Metadata": "true"}
resp = requests.get(token_url, headers=headers)
resp.raise_for_status()
access_token = resp.json()["access_token"]

print(access_token)
```

It works for every user except for this one. He is getting a 404 error.
MSI_ENDPOINT is set to **http://127.0.0.1:46808/MSI/auth** and MSI_SECRET is correctly set

All the VM have been created using the same configurations, and every users have Owner permissions on the tenant.

The Azure ML Workspace uses a User Assigned Identity that has Contributor role on the tenant

Any help would be appreciated

**Expected behavior**
User is able to retrieve the ManagedIdentity

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share the information how you configured/enabled the managed identity on the VM?

Did you use system-assigned managed identity or user-assigned managed identity?

**Comment by xiangyan99** [comment]
If you use user-assigned managed identity, you need to include the client id information in your request.

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-identity-based-service-authentication?view=azureml-api-2&tabs=cli#compute-cluster

Can you try it again?

**Comment by mauibar** [comment]
Thanks @xiangyan99 

So we tried on a machine with user-assigned-identity this piece of code

```
from azure.identity import ManagedIdentityCredential
import os

client_id = os.environ.get('DEFAULT_IDENTITY_CLIENT_ID')
credential = ManagedIdentityCredential(client_id=client_id)
token = credential.get_token('https://management.azure.com')
```

The user is able to retrieve correctly a token, however the call that he is doing is a call to retrieve artifacts from Azure MLFlow and the authentication is implicit and thus still fails as it is not using the token we managed to get with this method.
We tried setting the MLFLOW_TRACKING_TOKEN env var with the token we got but without success.

**Comment by xiangyan99** [comment]
If you don't mind, could you share the code snippet how you use Azure MLFlow?

**Comment by mauibar** [comment]
Hi @xiangyan99,

We simply do a `run = mlflow.get_run(run_id=run_id)`

Turns out it works now, but we didn't do anything more so I am a bit puzzled.
