### ISSUE TITLE
Support AAD-based access of Tables

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-sdk-for-python#33692]
https://learn.microsoft.com/en-us/azure/storage/tables/authorize-access-azure-active-directory#azure-built-in-roles-for-tables describes AAD support for Azure Tables. The JavaScript SDK supports AAD: https://learn.microsoft.com/en-us/javascript/api/overview/azure/data-tables-readme?view=azure-node-latest#tableserviceclient-with-tokencredential-aad. However, the Python SDK doesn't: https://learn.microsoft.com/en-us/python/api/overview/azure/data-tables-readme?view=azure-python#types-of-credentials

Given that AAD is generally the recommended auth type, it should be supported.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment]
Hi @letmaik, AAD is supported in Python SDK, it would be:
```python
from azure.data.tables import TableServiceClient
from azure.identity import DefaultAzureCredential
        
# DefaultAzureCredential expects the following three environment variables:
# - AZURE_TENANT_ID: The tenant ID in Azure Active Directory
# - AZURE_CLIENT_ID: The application (client) ID registered in the AAD tenant
# - AZURE_CLIENT_SECRET: The client secret for the registered application
        
account_name = "<account_name>"
endpoint_suffix = "<endpoint_suffix>"
client = TableServiceClient(
    endpoint=f"{account_name}.table.{endpoint_suffix}",
    credential=DefaultAzureCredential(),
)
```
We will update the document and provide a sample for AAD in README. Thanks for your report!

**Comment by letmaik** [comment]
@YalinLi0312 Just a note that I have tested it and it works. I also see you updated the docs. I'm closing this issue since it's all done. Thanks!
