### ISSUE TITLE
Low BLOB_MAX_CHUNK_DATA_SIZE leads to performance hits for max_connections=1

### ISSUE THREAD

**Issue by Segsfault** [Azure/azure-sdk-for-python#337]
When using azure.storage.blobservice.get_blob_to_file, the algorithm will download a 64MB (or smaller) file in one call REST call.

However larger files are chunked in 4MB blocks.  For a 65MB file this would result in 17 calls, which significantly decreases performance.  For my application, changing _BLOB_MAX_CHUNK_DATA_SIZE to be the same as _BLOB_MAX_DATA_SIZE (64MB) improved performance drastically.

Not sure of all use cases to know if this will impact other applications, but if it cannot be hard coded to 64MB, perhaps allowing a chunk_size  argument would help.

**Comment by huguesv** [comment]
Thanks for letting us know about this.  Looking at the node storage sdk, it appears that download chunk size may not be limited to 4MB, unless the md5 is requested.  I'll do some testing.

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/10
