### ISSUE TITLE
keep_alive property can not be set for the EventHubProducer created in EventHubProducerClient

### ISSUE THREAD

**Issue by repoww** [Azure/azure-sdk-for-python#33726]
- **Package Name**: 
- azure-eventhub
- **Package Version**: 
- 5.11.5
- **Operating System**:
- ubuntu
- **Python Version**: 
- 3.7

**Describe the bug**

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py#L376
when create EventHubProducer in EventHubProducerClient, the kwargs are not passed

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/azure/eventhub/_producer.py#L97
However, the `keep_alive` property is read from kwargs, `keep_alive = kwargs.get("keep_alive", None)`

**To Reproduce**
1. simply install the package 
2. instantiate an EventHubProducerClient with `keep_alive=30` as kwargs, check the `keep_alive` of its producer after 

**Expected behavior**
expected `keep_alive` is set to 30, and the connection is long-living,
however, with current version, the `keep_alive` is None, and the connection is lost after idling for 240s

**Comment by repoww** [comment]
![image](https://github.com/Azure/azure-sdk-for-python/assets/59852083/e8bba3e7-f87d-40c5-bd3b-ae464c3f7ec5)
![image](https://github.com/Azure/azure-sdk-for-python/assets/59852083/85ab95fe-8aaa-44fb-a864-3122f496b062)

**Comment by kashifkhan** [comment]
Thank you for the feedback @repoww . We will investigate and get back to you asap.

**Comment by kashifkhan** [comment]
Hi @repoww , wanted to give you an update that we are working on enabling keep alive for event hub. I did notice that you are running python 3.7 and we recently [dropped](https://github.com/Azure/azure-sdk-for-python/wiki/Azure-SDKs-Python-version-support-policy) support python 3.7 as it is [end of life](https://devguide.python.org/versions/). We would strongly encourage you to use python 3.8 and up, as those versions continue to get security updates and bug fixes.

**Comment by repoww** [comment]
thanks for update

**Comment by kashifkhan** [comment]
@repoww the work to enable that was merged in yesterday and is on track to be in our next release. In the meantime, you can test out the feature by building the wheel from source.

**Comment by kashifkhan** [comment]
@repoww the update with the fix is now on pypi
