### ISSUE TITLE
Sample_vector_search.py type Error 

### ISSUE THREAD

**Issue by wickkiey** [Azure/azure-sdk-for-python#33739]
**Describe the bug**
[sample_vector_search.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_vector_search.py)

**To Reproduce**
Run the notebook to create index. 

**Expected behavior**
Cognitive Search should be created.

Typo details.
The below line should have "my-agorithms-config" instead of "my-vector-config". 

https://github.com/Azure/azure-sdk-for-python/blob/2c1b886c3a578e1c9beff1f6bb93f285da6f63f8/sdk/search/azure-search-documents/samples/sample_vector_search.py#L89

Once I change the config it works. A small typo.

**Comment by xiangyan99** [comment]
Thanks for reporting the issue.

The fix has been merged.
