### ISSUE TITLE
'Cold' not documented as an available StandardBlobTier

### ISSUE THREAD

**Issue by nbut1er** [Azure/azure-sdk-for-python#33777]
### Type of issue

Missing information

### Description

As in title, the 'Cold' option for StandardBlobTier (https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py) isn't included in the documentation.

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.models.standardblobtier?view=azure-python-previous

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/previous/docs-ref-autogen/azure-storage-blob/azure.storage.blob.models.StandardBlobTier.yml

### Document Version Independent Id

1b4a5e56-4f25-f2a2-0f69-f2e229fa73f6

### Article author

@VSC-Service-Account

### Metadata

* ID: 06de2651-2302-78b1-64f0-90f1a49ef510

**Comment by vincenttran-msft** [comment]
Hi @nbut1er Nick, the documentation you linked above is actually the legacy documentation (Track 1).
![image](https://github.com/Azure/azure-sdk-for-python/assets/101599632/469a3955-2293-4b9c-ae33-4e54c062b188)

[Here ](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.standardblobtier?view=azure-python)is the correct, up-to-date documentation.

For reference, here is the a link to the up to date documentation landing page: 
https://learn.microsoft.com/en-us/python/api/overview/azure/storage?view=azure-python

With that being said, I will continue with the closure of this issue.

Thanks!
