### ISSUE TITLE
Purview Catalog Client get_by_unique_attributes won't take any other attribute except the qualified name

### ISSUE THREAD

**Issue by amsteel** [Azure/azure-sdk-for-python#33787]
- **Package Name**: azure.purview.catalog
- **Package Version**: 1.0.0b4
- **Operating System**: Ubuntu 22.04.3 LTS
- **Python Version**:  3.10.13

**Describe the bug**
entity.get_by_unique_attributes will not take another other attribute except the qualified name

**To Reproduce**
1.  calling catalog_client.entity.get_by_unique_attributes(type_name='azure_datalake_gen2_path',  attr_qualified_name='xxx') returns ResourceNotFoundError, which is ok.
2. calling catalog_client.entity.get_by_unique_attributes(type_name='azure_datalake_gen2_path',  name='xxx') returns TypeError: Session.request() got an unexpected keyword argument 'name'. Tried several different attributes and it returns the same error.

**Expected behavior**
It should either return a unique entity or return ResourceNotFoundError if it finds None or more than one entity.

**Additional context**
Are there any other ways to use attributes other than qualified name? It stated in REST API reference (https://learn.microsoft.com/en-us/rest/api/purview/datamapdataplane/entity/get-by-unique-attributes?view=rest-purview-datamapdataplane-2023-09-01&tabs=HTTP#atlasentity) can be changed to other attributes.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

It looks to me `name` is not a valid argument for `get_by_unique_attributes` method.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/purview/azure-purview-catalog/azure/purview/catalog/operations/_operations.py#L449

**Comment by amsteel** [comment]
/unresolve 
Please check in this link of REST API: https://learn.microsoft.com/en-us/rest/api/purview/datamapdataplane/entity/get-by-unique-attributes?view=rest-purview-datamapdataplane-2023-09-01, in the "URI Parameters" section,  it says "The qualified name of the entity. (This is only an example. qualifiedName can be changed to other unique attributes)". 
So it should be ok to use other unique attributes as part of the parameters.  I think the current Python Client implementation only allows "The qualified name" and nothing else.

**Comment by xiangyan99** [comment]
In the doc, it says:

GET {endpoint}/datamap/api/atlas/v2/entity/uniqueAttribute/type/{typeName}?minExtInfo={minExtInfo}&ignoreRelationships={ignoreRelationships}&attr:qualifiedName={attr:qualifiedName}


attr:qualifiedName -The qualified name of the entity. (This is only an example. qualifiedName can be changed to other unique attributes)

The value of `attr:qualifiedName` can be changed to other unique attributes. But the query parameter is `attr_qualified_name`.

catalog_client.entity.get_by_unique_attributes(type_name='azure_datalake_gen2_path', attr_qualified_name='any_unique_attributes')
