### ISSUE TITLE
[Core] test of main branch fails 

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#33799]
Test fails even nothing changes in https://github.com/Azure/azure-sdk-for-python/pull/33798. Here is [log](https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/3396966/logs/274) 

![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/bdffd477-9907-4ecc-9bd7-9e03a2939787)

**Comment by xiangyan99** [comment]
trio had a new release on 1/9 which introduced a breaking change.

We are working on it.

**Comment by pvaneck** [comment]
Closing. This was resolved when the `anyio` dependency was removed in https://github.com/Azure/azure-sdk-for-python/pull/33282.
