### ISSUE TITLE
Version 0.10.0 fails with 'SocketReader' object has no attribute 'tell'

### ISSUE THREAD

**Issue by jkubrynski** [Azure/azure-sdk-for-python#338]
In version 0.10.0 there is a bug in ```azure/storage/__init__.py``` causing 
```AttributeError: 'SocketReader' object has no attribute 'tell'```

**Comment by huguesv** [comment]
Unfortunately, the new algorithm that parallelizes uploads requires the streams to be seekable.  We'll have to go back to the previous code (0.9) when max_connections==1 to allow for this to work.  Thanks for letting us know.

**Comment by huguesv** [comment]
I just merged the fix, if you haven't tested it yet, please do try it and let us know if that works for you. Thanks!
