### ISSUE TITLE
Error importing openai in azure-ai-generative

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-sdk-for-python#33827]
- **Package Name**: azure-ai-generative
- **Package Version**: 1.0.0b2
- **Operating System**: Mac
- **Python Version**: 3.11

**Describe the bug**

We get this error when using QADataGenerator:

```
    from azure.ai.generative.synthetic.qa import QADataGenerator, QAType
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/generative/synthetic/qa.py", line 33, in <module>
    openai.error.ServiceUnavailableError,
    ^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'error'
```

I fixed it by adding openai==0.28.1 to our requirements.txt.

**To Reproduce**
1. Checkout repo at this point: https://github.com/Azure-Samples/ai-rag-chat-evaluator/tree/a96606c45d260ba6a690697eecac588b6dd3162f
2. Run `python3 -m scripts generate --output=example_input/qa.jsonl --numquestions=2 --persource=5`

**Comment by xiangyan99** [comment]
@kristapratico FYI.

**Comment by luigiw** [comment]
We have a release candidate that will support openai 1.x. That will fix this issue.

**Comment by pamelafox** [comment]
I am trying release candidate now, but it didn't realize that my installed openai (0.28) was incompatible. I think you need to bump the version constraints in https://github.com/Azure/azure-sdk-for-python/blob/75da6ac8e0ead6235ac09e3f725adce405b5adad/sdk/ai/azure-ai-generative/setup.py#L101 ?

**Comment by paulshealy1** [comment]
Closing this issue for `azure-ai-generative`.
