### ISSUE TITLE
How I get error code of REST response?

### ISSUE THREAD

**Issue by impepc** [Azure/azure-sdk-for-python#33840]
- **azure-storage-blob**: 
- **12.14.1**: 
- **Mac/Windows**:
- **3.9.18**: 

**Describe the bug**
I want to get error code on I appended to blob over 50,000 times(BlockCountExceedsLimit).
 But, I didn't find out to how to get this error code.
https://learn.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes

AzureError seems have error_code property but was not in document.
and also azure.storage.blob.StorageErrorCode was defined, but I couldn't find to how to use it.

**To Reproduce**
like this code
```python
from pprint import pprint
from azure.storage.blob import BlobClient, ContainerClient


CONNECT_STRING = 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;'  # noqa: E501

if __name__ == '__main__':
    container: ContainerClient = ContainerClient.from_connection_string(CONNECT_STRING, 'logs')
    blob: BlobClient = container.get_blob_client('limit.txt')
    if not blob.exists():
        blob.create_append_blob()
    try:
        while True:
            blob.append_block('abc\n')
    except BaseException as e:
        pprint(e)
        print(e.error_code)
```

**Expected behavior**
Add Document how to get Error Code. 
also, type annotate to Exception(Error).

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by vincenttran-msft** [comment]
Hi @impepc , sorry for the late response! This completely slipped through my radar. After taking a look through your attached code snippet, I have gone ahead and revised it with a couple changes, and will provide some annotations below:

```
from pprint import pprint
from azure.storage.blob import BlobClient, ContainerClient, StorageErrorCode
from azure.core.exceptions import AzureError


CONNECT_STRING = 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;'  # noqa: E501

if __name__ == '__main__':
    container: ContainerClient = ContainerClient.from_connection_string(CONNECT_STRING, 'logs')
    blob: BlobClient = container.get_blob_client('limit.txt')
    if not blob.exists():
        blob.create_append_blob()
    try:
        while True:
            blob.append_block('abc\n')
    except AzureError as e:
        pprint(e)
        print(e.error_code == StorageErrorCode.BLOCK_COUNT_EXCEEDS_LIMIT.value)
        print("Error Code:", e.error_code)
        print("Error Message:", e.message)
        print("Error Reason:", e.reason)
        print("Status Code:", e.status_code)

```

1. As you mentioned, `AzureError` does seem to have `error_code`. The documentation is something we will look to improve, but one way to check currently for what fields are accessible is to set a breakpoint after getting an error `e` and looking at its fields. In my example above, I have expanded it to include most of the fields you would want to access.
2. I included an example of using `StorageErrorCode`. It is an enum, so you would want to address it as above (StorageErrorCode.<ENUM>, and to get it's value add a `.value`. My example uses it in it equality check

For more information on other valid `StorageErrorCode` enum values, here is a [link ](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/models.py#L77) to the model. Hopefully this code snippet helps to resolve any of your misunderstandings.

Thanks!

**Comment by impepc** [comment]
> The documentation is something we will look to improve

I'm looking forward to it.

> but one way to check currently for what fields are accessible is to set a breakpoint after getting an error e and looking at its fields. In my example above, I have expanded it to include most of the fields you would want to access.

Thank you. It's very useful code. I'll try debugging.

> I included an example of using StorageErrorCode. It is an enum, so you would want to address it as above (StorageErrorCode., and to get it's value add a .value. My example uses it in it equality check

Thank you. It seems I could handle not only exceed maximum appending error, and also other errors.
