### ISSUE TITLE
Failed to extract version when parsing asset //datastores/inference/paths... of type codes as arm id. Version must be provided

### ISSUE THREAD

**Issue by sjLeonGalan** [Azure/azure-sdk-for-python#33845]
I'm encountering an issue with the ModelBatchDeployment class, specifically when using the parameter of type CodeConfiguration and providing a path from a datastore. The error I'm facing indicates that a version must be provided. 
If I provide a local path it works perfectly, and also, I am providing datastore path in others parameters as the model and works as well.
Thanks in advance!

**Comment by kashifkhan** [comment]
Hi @sjLeonGalan, can you provide some further details around the package being used, some code that can reproduce the issue, python version etc. so that I can assign to the right folks to help you out. 

Thanks
