### ISSUE TITLE
Please enable `DefaultAzureCredential` for `azure.graphrbac` library...

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-sdk-for-python#33841]
**Is your feature request related to a problem? Please describe.**
There are others who have brought the issue up.

**Describe the solution you'd like**
I'd like to use *consistent* auth mechanisms for my apps and automations. This is so far the only Azure Python library I've come across that doesn't support the use of `from azure.identity import DefaultAzureCredential`.  Seems to require older mechanisms that require A LOT of additional work (setting up a Service Principal, managing secret material for the `client_secret`, creating Key Vault secrets, add Key Vault functions, etc..). 

**Describe alternatives you've considered**
I'm avoiding scripting this because of the additional work. 

**Additional context**
This should just work...
```
from azure.identity import DefaultAzureCredential
from azure.graphrbac import GraphRbacManagementClient
import json

# Azure Configuration - replace with your tenant ID
TENANT_ID = 'my-tenant-id'

# Initialize the Azure credentials
credential = DefaultAzureCredential()

# Initialize the GraphRbacManagementClient
graphrbac_client = GraphRbacManagementClient(credential, TENANT_ID)

# Fetch and save user principals
users = graphrbac_client.users.list()
with open('azure_users.json', 'w') as file:
    json.dump([user.as_dict() for user in users], file, indent=4)

# Fetch and save group principals
groups = graphrbac_client.groups.list()
with open('azure_groups.json', 'w') as file:
    json.dump([group.as_dict() for group in groups], file, indent=4)

# Fetch and save service principals
service_principals = graphrbac_client.service_principals.list()
with open('azure_service_principals.json', 'w') as file:
    json.dump([sp.as_dict() for sp in service_principals], file, indent=4)
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
[azure-graphrbac](https://pypi.org/project/azure-graphrbac) is deprecated.

Please use https://pypi.org/project/microsoftgraph-python/ instead.
