### ISSUE TITLE
RE: Assigned namespace does not appear when logging... - TrackingID#2312280050001656

### ISSUE THREAD

**Issue by pavelmay** [Azure/azure-sdk-for-python#33855]
Azure exporter for the Python Open Telemetry distro does not have setting a custom namespace for metrics which was previously available in beta releases of several available APIs.

Setting custom namespace for metrics in Azure Monitor/Application Insight is a critical feature for Amdocs AI Digital Platform and used heavily in its ML-related use cases for multiple telcos.

Hereby we request to provide an earlier existed custom namespace functionality to enable a proper monitoring of our products.

**Comment by kashifkhan** [comment]
Thank you for the feedack @pavelmay . We will investigate and get back to you asap.

**Comment by lzchen** [comment]
Please refer to this [comment](https://github.com/Azure/azure-sdk-for-python/pull/32897#issuecomment-1843463543). We are in the midst of discussing whether we want to bring back this feature.

**Comment by lzchen** [comment]
We have decided we will enable this feature via an opt-in environment variable. Will be available in the next released version of the exporter once this PR is merged.

https://github.com/Azure/azure-sdk-for-python/pull/34463
