### ISSUE TITLE
Improve Probing Logic for Azure Instance Metadata Service (IMDS) for Virtual Machines

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#33889]
Tracking issue for addressing customer feedback on IMDS VM delays with DefaultAzureCredential due to IMDS probing retry logic in Azure Identity SDK.  @ahsonkhan is driving this investigation.

Currently our SDKs are inconsistent across languages where some languages have zero retries, some have a single 0.5 second retry, and others (.NET) have up to 8-seconds of retries.

We need to review all languages here and make them consistent across languages, as well as publish a Sample and Blog about IDMS on VMs with Azure Identity SDK and how customers can write 2-3 lines of cose to skip IMDS when needed.

**Comment by joshfree** [comment]
Related: https://github.com/Azure/azure-sdk-for-rust/issues/1503

**Comment by ahsonkhan** [comment]
C++ issue for tracking: https://github.com/Azure/azure-sdk-for-cpp/issues/5279

**Comment by pvaneck** [comment]
Closed via https://github.com/Azure/azure-sdk-for-python/pull/35070
