### ISSUE TITLE
Issues with caling and validating environment

### ISSUE THREAD

**Issue by TucoFernandes** [Azure/azure-sdk-for-python#33882]
- **Package Name**: azure.ai.ml
- **Package Version**: 
- **Operating System**: Linux
- **Python Version**: 3.7

**Describe the bug**
One of my production codes started breaking today. I didn't update anything on my Python environment, so I'm guessing there were changes on the MS Azure side. The error message is:

/miniconda3/envs/ct_cvird_env/lib/python3.7/site-packages/azure/ai/ml/entities/_util.py", line 187, in validate_attribute_type
    error_type=ValidationErrorType.INVALID_VALUE, 
azure.ai.ml.exceptions.ValidationException: Expecting (<class 'str'>, <class 'azure.ai.ml.entities._assets.environment.Environment'>) for environment, got <class 'dict'> instead.

The error occurs when calling the ml_client job list and checking if the job has finished.

**To Reproduce**

``` python
  print(f"Waiting for batch job deployment {job.name}", end="")
  while ml_client.jobs.get(name=job.name).status not in ["Completed", "Failed"]:
      sleep(60)
      print(".", end="")
  
  print(" [DONE]")
```

**Expected behavior**
When passing an environment variable that was returned from a new job I would expect it to run and not give me an error. A fun fact is that the job does run on Azure.

**Screenshots**

**Additional context**

**Comment by TucoFernandes** [comment]
I narrowed down the issue to the get function. Independent of the job name that I pass I will get the same error. 

job = ml_client.jobs.get(name = 'batchjob-jobname')

**Comment by bassim1** [comment]
I have the same issue. 
Package Name: azure.ai.ml
Linux
python 3.8

When trying to get a job object by name:

"job.py", line 318, in _from_rest_object
    raise JobParsingError(
azure.ai.ml.exceptions.JobParsingError: Expecting (<class 'str'>, <class 'azure.ai.ml.entities._assets.environment.Environment'>) for environment, got <class 'dict'> instead."

**Comment by santiagxf** [comment]
Dup from #33835

**Comment by santiagxf** [comment]
A patch has been applied to the service and we have confirmed it solved the issue. The roll out has been completed today. I will proceed to close the issue but @TucoFernandes and @bassim1 please reopen the issue if you continue having troubles with the service. Happy to help with it.

**Comment by TucoFernandes** [comment]
Hi @santiagxf I can confirm that the patch fixed the issue for me. Thanks!
