### ISSUE TITLE
Custom environment creation in AML with `build-arg`

### ISSUE THREAD

**Issue by ZhiliangWu** [Azure/azure-sdk-for-python#33902]
**Is your feature request related to a problem? Please describe.**
According to the [docs of creating an env. from a docker build context](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-environments-v2?view=azureml-api-2&tabs=python#create-an-environment-from-a-docker-build-context)

> Instead of defining an environment from a prebuilt image, you can also define one from a Docker [build context](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#understand-build-context)

```python
from azure.ai.ml.entities import Environment, BuildContext
env_docker_context = Environment(
    build=BuildContext(path="docker-contexts/python-and-pip"),
    name="docker-context-example",
    description="Environment created from a Docker context.",
)
ml_client.environments.create_or_update(env_docker_context)
```
Meanwhile, in the specified `Dockerfile`, build-time arguments cannot be passed in like what we do with [`docker build --build-arg`](https://docs.docker.com/engine/reference/commandline/build/#build-arg).  This blocks using [CI-JOB-TOKEN](https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html) inside CI jobs to authenticate for e.g., installation [from private package registries using poetry](https://python-poetry.org/docs/repositories/#installing-from-private-package-sources) and any other settings requiring credentials. 

**Describe the solution you'd like**
Add `--build-args` to the class `BuildContext` so that we can pass in respective built-time arguments. 

**Describe alternatives you've considered**
Include all credentials in the Dockerfile, but this is apparently a bad idea. 

**Additional context**

**Comment by ZhiliangWu** [comment]
> Thank you for the feedback @ZhiliangWu . We will investigate and get back to you asap.
> 
> cc @azureml-github

@kashifkhan Thanks for your reply. I think technically this shouldn't be a big implementation as you are under the hood using `docker build` to build the images. I really hope to see some progress on this.

**Comment by vizhur** [comment]
We'll look into that. That is a pretty big feature unless we don't care about security aspect of exposing the secrets/tokens. Otherwise with the same success you can hardcode them into context. Other aspect is reproducibility, assuming we store just a reference to user secrets/parameters, how to make sure that we invalidate the cache once the value is changed.

**Comment by ZhiliangWu** [comment]
> We'll look into that. That is a pretty big feature unless we don't care about security aspect of exposing the secrets/tokens. Otherwise with the same success you can hardcode them into context. Other aspect is reproducibility, assuming we store just a reference to user secrets/parameters, how to make sure that we invalidate the cache once the value is changed.

Hi @vizhur, thanks for your reply.

It would be a really necessary feature for CI jobs from my perspective. 

For GitLab CI jobs, the security issue is not that big, as the [CI/CD job token](https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html) is only valid during the pipeline time. That's why we need to be able to assign it dynamically instead of hard-code them in the `DOCKERFILE`.  The reproducibility remains as long as we build the environment using the same CI setup. 

Apart from that, there are also several use-cases within an enterprise environment. I.e., we can use `--build-arg` to pass some (dynamic) enterprise proxy information into the docker build process. Otherwise, we must hard-code this information in the `DOCKERFILE`.

**Comment by vizhur** [comment]
@ZhiliangWu it is indeed a very useful feature. We'll look into that and try to prioritize, can't promise any short-term solution though. We'll create a feature request on our end.
