### ISSUE TITLE
Add a sample to show case how to use SessionId to create sticky sessions in Search SDK

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-python#33915]
Search team recently reached with a customer reported issue complaining about duplicate / incorrect results while paging using the filter. It was determined the root cause of the issue was that service expects sticky session to support page query in a multi-replica service.
 
The way to mitigate this is to use the session id feature [https://learn.microsoft.com/en-us/azure/search/index-similarity-and-scoring#scoring-statistics-and-sticky-sessions](https://learn.microsoft.com/en-us/azure/search/index-similarity-and-scoring)

Given the issue we want to add a sample to educate the customers of this gap.

**Comment by xiangyan99** [comment]
Done
