### ISSUE TITLE
[Event Hubs] Indefinite Wait After Rotating Primary Key While Receiving Events

### ISSUE THREAD

**Issue by g1t-out** [Azure/azure-sdk-for-python#33926]
- **Package Name**: azure-eventhub
- **Package Version**: 5.11.5
- **Operating System**: Debian 11.7
- **Python Version**: 3.11.4

**Describe the bug**
When receiving data from the event hub, if the primary key is rotated, the program will wait indefinitely receiving no data. It never throws an exception or attempts are reconnect (After leaving it wait for 30+ minutes).

**To Reproduce**
1. Receive data on an event hub
2. Rotate the Primary Key in Azure for the EventHub

**Expected behavior**
The SDK should detect that it is no longer connected and receiving data from the EventHub. An exception should be eventually thrown.

**Screenshots**

**Additional context**
I've been working around this for now by passing a max_wait_time of 30 seconds to the receive_batch function. I keep track of the number of sequential callbacks without event data and will eventually throw an exception, but it would be cleaner to handle it in the SDK.

**Comment by kashifkhan** [comment]
Thank you for the feedback @g1t-out. How exactly are you rotating the primary key ?

**Comment by g1t-out** [comment]
> Thank you for the feedback @g1t-out. How exactly are you rotating the primary key ?

I do it through the Azure Portal. Open Event Hubs, then click on the Event Hub Namespace, then click on the Event Hub, then click "Shared access policies", then click "Regenerate Primary Key".

![image](https://github.com/Azure/azure-sdk-for-python/assets/45244911/a6517c55-2cf1-4aee-a100-7215dfb6c591)

**Comment by kashifkhan** [comment]
Thanks @g1t-out . Im able to reproduce this error and will update this thread once I have a fix out.
