### ISSUE TITLE
DefaultAzureCredential support OIDC 

### ISSUE THREAD

**Issue by BrageKanKode** [Azure/azure-sdk-for-python#33921]
**Is your feature request related to a problem? Please describe.**
Trying to log in using Python's Azure.Identity library, my organisation uses OIDC to log in. However, since this is not supported, I cannot make a Github Docker container action that logs in to Azure. 
Searching the docs and the web, I haven't found any support for this at all.

**Describe the solution you'd like**
I would like support for OIDC login, preferably using AzureDefaultCredentials

**Describe alternatives you've considered**
I have tried to log in before calling my custom action, but it has to be done in the local repository.
I have tried to log in using steps in the custom action, but Docker Container Action does not support multiple steps as far as I've seen.
I have tried to log in using AzureDefaultCredentials, but there is no support for OIDC.

**Comment by kashifkhan** [comment]
Thank you for the feedback @BrageKanKode. We will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

azure-identity library focuses on Microsoft Entra ID.

You need to connect OIDC with Microsoft Entra ID to make it work.

You can ger more information from https://learn.microsoft.com/entra/architecture/auth-oidc
https://learn.microsoft.com/entra/identity-platform/v2-protocols-oidc
