### ISSUE TITLE
Update azure.mgmt.securityinsight

### ISSUE THREAD

**Issue by prose-leviathan** [Azure/azure-sdk-for-python#33957]
**Is your feature request related to a problem? Please describe.**
The package was not updated since 2 years, and I have troubles deploying AlertRules resources to Sentinel. I receive API imcompatibility errors, and passing api_version to the client does not resolve it.

**Describe the solution you'd like**
Update the package to model the latest version of the API.

**Comment by prose-leviathan** [comment]
Another issue was opened for missing features since the SDK was created #32311

**Comment by kristapratico** [comment]
@prose-leviathan thanks for your issue. We'll take a look and respond as soon as possible.

**Comment by prose-leviathan** [comment]
Small update here : it was not clear from the documentation that we need to pass the Alert UUID into the `rule_id `param of [AlertRulesOperations.create_or_update() method ](https://learn.microsoft.com/en-us/python/api/azure-mgmt-securityinsight/azure.mgmt.securityinsight.operations.alertrulesoperations?view=azure-python#azure-mgmt-securityinsight-operations-alertrulesoperations-create-or-update)method. I tried passing it, but something must have been not setup correctly on my end, and I explored other approaches. When looking at the [ScheduledAlert model](https://learn.microsoft.com/en-us/python/api/azure-mgmt-securityinsight/azure.mgmt.securityinsight.models.securityalert?view=azure-python), it mentions the fully qualified resource ID and the issues I ran through where due to it, since it intereferred with this line of code in the SDK.

```python
    create_or_update.metadata = {
        "url": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/alertRules/{ruleId}"
    }
```

Here it is more visible that the ruleId refers to the resource UUID. 

Furthermore, the missing ATT&CK Technique support was resolved by using the SDK version 2.0.0b2, which is not the default version when downloading with PiPy

I propose two things which are more documentation oriented:

1. Clearly explicit on the SDK documentation that the `rule_id `parameter refers to the Alert **UUID**
2. Highlight on the doc that version 2 (currently beta) of the SDK will add several very important feature.

**Comment by prose-leviathan** [comment]
@ChenxiJiang333 Thanks, but if you re-read the message I left, as I pointed out I figured it out already. The point I was making was to make the documentation clearer wrt rule_id being the UUID of the AlertRule - for example I didn't find the sample you linked after a lot of googling. A better approach is to link the samples on the documentation page.

**Comment by ChenxiJiang333** [comment]
@prose-leviathan The description of param `ruld_id` was defined [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2023-11-01/AlertRules.json#L1857) and you may need to open an issue at https://github.com/Azure/azure-rest-api-specs to turn to the service team for an update. As for the doc page, we would update it once a new package released,

**Comment by prose-leviathan** [comment]
Since the problem was on docs and not on package, closing
