### ISSUE TITLE
"AzureOpenAIParameters" and "AzureOpenAIVectorizer" are missing from azure.search.documents.indexes.models in 11.4.0, are in 11.4.0b11

### ISSUE THREAD

**Issue by JetterMcTedder** [Azure/azure-sdk-for-python#33952]
- azure-search-documents: 
- 11.4.0: 
- N/A
- 3.7+

**Describe the bug**
Between going from 11.4.0b11 to 11.4.0, for azure.search.documents.indexes.models, the following are missing and not in the release notes as breaking changes:

    "AzureOpenAIEmbeddingSkill",
    "AzureOpenAIParameters",
    "AzureOpenAIVectorizer", 

**To Reproduce**
1. create a python file and try the following:
from azure.search.documents.indexes.models import (
    AzureOpenAIParameters,
    AzureOpenAIVectorizer,
)

this works with 11.4.0b11 but not with the 11.4.0 release.

**Expected behavior**
I expect to be able to use the following in the 11.4.0 release
    "AzureOpenAIEmbeddingSkill",
    "AzureOpenAIParameters",
    "AzureOpenAIVectorizer",

File links to compare

https://github.com/Azure/azure-sdk-for-python/blob/azure-search-documents_11.4.0b11/sdk/search/azure-search-documents/azure/search/documents/indexes/models/__init__.py

https://github.com/Azure/azure-sdk-for-python/blob/azure-search-documents_11.4.0/sdk/search/azure-search-documents/azure/search/documents/indexes/models/_index.py

**Comment by kristapratico** [comment]
@JetterMcTedder thanks for your issue. We'll take a look and get back to you as soon as possible.

**Comment by xiangyan99** [comment]
Thanks for catching it. We added it in https://github.com/Azure/azure-sdk-for-python/pull/33975.
