### ISSUE TITLE
Python SDK serialization. Property case is not preserved.

### ISSUE THREAD

**Issue by mchen727** [Azure/azure-sdk-for-python#33959]
- **Package Name**: 
- msrest Deserializer/Serializer 
- github.com/Azure/azure-sdk-for-go/sdk/azcore v1.7.1
- github.com/Azure/azure-sdk-for-go/sdk/internal v1.3.0
- **Package Version**: 
- **Operating System**:
- **Python Version**: python version 3.9

**Describe the bug**
When an object is serialized from HTTP response, the case of the key's name is not preserved. "osSKU" is serialized as "osSku"

**To Reproduce**
1. Make a HTTP request and get a valid response.
2. Parse the response and serialize it into the respective response object.
3. "osSKU" key gets serialized as "osSku"

**Expected behavior**
The case of the property name should be preserved.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/20915060/859e5626-86a8-46ea-a00c-26d58f7531df)

**Additional context**

**Comment by msyyc** [comment]
@mchen727 which python azure sdk are you using?

**Comment by mchen727** [comment]
@msyyc Im using Azure/azure-sdk-for-go (azcore and internal)

**Comment by msyyc** [comment]
We advise you use Python SDK to contact azure service since msrest is going to be deprecated gradually. Which REST API of https://github.com/Azure/azure-rest-api-specs/tree/main/specification are your calling? We can help you find the proper Python SDK

**Comment by mchen727** [comment]
We used an autorest commands to generate the SDK for python and go. Here are the commands we used.

For Python:
`modelerfour:`
`  lenient-model-deduplication: true`
`$ versions_flags=(--version=3.6.3 --use=@autorest/python@~5.8.4 --use=@autorest/python@~5.8.4 --use=@autorest/modelerfour@~4.19.3)`
`$ autorest ./readme.md --tag=package-2024-01 --python-sdks-folder=~/repos/hybridaks-utils/azure-sdk-for-python --python --python-mode=update --track2 "${versions_flags[@]}"`

For Golang:
`module-version: 0.2.0`
`autorest ./readme.md --tag=package-2024-01 --use=@autorest/go@4.0.0-preview.55 --go --track2 --honor-body-placement=false --remove-unreferenced-types=true --output-folder=~/repos/hybridaks-utils/azure-sdk-for-go/hybridaks/generated`

**Comment by msyyc** [comment]
It is better to use latest autorest.python to generate code. Here is cmd that SDK team use:
`autorest D:\dev\azure-rest-api-specs\specification\xxx\resource-manager\readme.md --generate-sample=True --include-x-ms-examples-original-file=True --python --python-sdks-folder=D:\dev\azure-sdk-for-python\sdk --use=@autorest/python@6.7.1 --use=@autorest/modelerfour@4.26.2 --version=3.9.7 --version-tolerant=False`

**Comment by mchen727** [comment]
Hi I tried using the newly generated SDK and am still getting the same issue
![image](https://github.com/Azure/azure-sdk-for-python/assets/20915060/6fea8661-6f6c-4e44-8350-625d7259fa8c)

**Comment by mchen727** [comment]
/unresolve
I tested with the newly generated SDK and seems like the serialization from the HTTP response is fine. 
key `osSKU` is deserialized into `os_sku`
![image](https://github.com/Azure/azure-sdk-for-python/assets/20915060/b065d699-d26e-46b3-9fb4-fac207cc5717)

However, it seems that in the lower cli core layers, os_sku gets serialized into osSku. Is there anyway to preserve osSKU ?
Would using a key like os_SKU work?

**Comment by ChenxiJiang333** [comment]
> Hi I tried using the newly generated SDK and am still getting the same issue ![image](https://private-user-images.githubusercontent.com/20915060/303126845-6fea8661-6f6c-4e44-8350-625d7259fa8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzU2NTEsIm5iZiI6MTcwODIzNTM1MSwicGF0aCI6Ii8yMDkxNTA2MC8zMDMxMjY4NDUtNmZlYTg2NjEtNmY2Yy00ZTQ0LTgzNTAtNjI1ZDcyNTlmYThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA1NDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NWIwNmQ0NzhkMjMxMDkxNzcxMjQ4N2I3MmYxMGNiNTYwZThkYmI1OTE1YTM2MDBjMzhhYzliYWQ5ODkxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6JQagHW0CQSZCxtq0uadb_D-ESdXz1drbGiHORQnthw)

Hi @mchen727, which method did you use for serializing the response? I have manually run the SDK function and tried `response.serialize()` after receiving the HTTP response, then the outcome was like
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/8e636a98-0800-4341-850c-0884d414c836)

**Comment by mchen727** [comment]
I think the problem here is that the CLI is deserializing the HTTP response first into `os_sku`. Then later when the response is printed out in the CLI, it is serialized into osSku, losing the case.

We are using `deserialized = self._deserialize('ProvisionedCluster', pipeline_response)` _deserialize() method from the autorest auto generated SDK.

I believe it is this generated definition:
```
    @classmethod
    def deserialize(cls: Type[ModelType], data: Any, content_type: Optional[str] = None) -> ModelType:
        """Parse a str using the RestAPI syntax and return a model.

        :param str data: A str using RestAPI structure. JSON by default.
        :param str content_type: JSON by default, set application/xml if XML.
        :returns: An instance of this model
        :raises: DeserializationError if something went wrong
        """
        deserializer = Deserializer(cls._infer_class_models())
        return deserializer(cls.__name__, data, content_type=content_type)  # type: ignore

```

**Comment by ChenxiJiang333** [comment]
Have you tried to run SDK and print out the serialized response without the CLI? I guess it might be the CLI behavior to forcibly print out the response in camel case, otherwise it would just be serialized as what it's defined in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/hybridaks/resource-manager/Microsoft.HybridContainerService/preview/2023-11-15-preview/provisionedClusterInstances.json#L1303).

**Comment by ChenxiJiang333** [comment]
> I see it is probably the CLI's behavior. I printed out the response and saw `os_sku`

And with `.serialize()` you may see it serialized as `osSKU`
