### ISSUE TITLE
Unable to use azure.monitor.opentelemetry.configure_azure_monitor on read only file system

### ISSUE THREAD

**Issue by yli02** [Azure/azure-sdk-for-python#33962]
- **Package Name**: azure-monitor-opentelemetry
- **Package Version**: 1.1.1
- **Operating System**: python:3.8.18-slim docker image
- **Python Version**: Python 3.8.18

**Describe the bug**
The `azure.monitor.opentelemetry.configure_azure_monitor` triggers the creation of a temp directory even though I configured `disable_offline_storage` to be `True`

**To Reproduce**
1. Configure container file system to be read only
2. Start Python script by call `configure_azure_monitor` with `disable_offline_storage=True`

**Expected behavior**
Only create the temp storage directory when `disable_offline_storage=False`

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/141815872/64fb12b5-b6e1-47fc-bf23-5f70db6a67fc)

**Additional context**
![image](https://github.com/Azure/azure-sdk-for-python/assets/141815872/558496db-dc39-4e34-aa76-944f2ddf91c6)

**Comment by kristapratico** [comment]
@yli02 thanks for your feedback. We'll investigate and get back to you as soon as possible.

**Comment by yli02** [comment]
Hi @jeremydvoss and @lzchen, may I ask your opinion about this bug, and approximately when I could expect a fix will be provided? Thanks a lot.

**Comment by yli02** [comment]
@jeremydvoss thanks. It crashed upon the first attempt at directory creation.

**Comment by jeremydvoss** [comment]
Thanks. I've confirmed that this is a bug with how the exporter constructor is written. Working on the fix.
