### ISSUE TITLE
Potential improvements to AdvancedBuild/cibuildwheel

### ISSUE THREAD

**Issue by jalauzon-msft** [Azure/azure-sdk-for-python#33972]
A couple of requests that would make working with the new AdvancedBuild/cibuildwheel a little easier.

- When cibuildwheel fails, the build stage of the pipeline should fail. Currently if cibuildwheel fails, the build stage passes, and the pipeline moves on to test phases. If the build stage is for whatever reason not able to produce the expected package list, it really should fail to indicate to us and the rest of the pipeline that something is not right. Currently I believe the test phases will fail if the build fails, preventing the whole pipeline from passing, but we shouldn't rely on that to know to check the build.
  - If cibuildwheel fails, the build phase will still produce one wheel file (I think it's the wheel for the Python version/platform of the build machine) which can also be a bit misleading.
- It would be nice if the logs from cibuildwheel bubbled up into the pipeline output on ADO. Currently you have to download the log file to see any output from cibuildwheel.
  - Along similar lines, maybe we could bubble up warnings from cibuildwheel as pipeline warnings that show up on the main page for the pipeline run.
- This may be less about AdvancedBuild and more specific to C extension packages but for `azure-storage-extensions` we ignore a ton of tox envs. Each one we ignore generates a warning on the pipeline run. Since this will be the case for ALL Storage pipeline runs going forward, it would be nice if we could suppress those warnings somehow. Perhaps suppress per package or something.

**Comment by scbedd** [comment]
2) is already resolved in `feature/storage-extensions` branch that you're working on. I'll resolve 1) and 3) in a follow-up PR.
