### ISSUE TITLE
No artifacts matching outputs/model.pkl found from Job.

### ISSUE THREAD

**Issue by amalprem** [Azure/azure-sdk-for-python#33978]
- **Package Name**:  azure-ai-ml
- **Package Version**:  1.9.0
- **Operating System**: Linux
- **Python Version**:  3.10

**Describe the bug**
Whenever I try to run the below command : 
ml_client.models.create_or_update(model)
I get the error with a message : 
HttpResponseError: (UserError) The request is invalid.
Code: UserError
Message: The request is invalid.
Exception Details:	(NoMatchingArtifactsFoundFromJob) No artifacts matching outputs/model.pkl found from Job.
	Code: NoMatchingArtifactsFoundFromJob
	Message: No artifacts matching outputs/model.pkl found from Job.
Additional Information:Type: ComponentName
Info: {
    "value": "managementfrontend"
}Type: Correlation
Info: {
    "value": {
        "operation": "41e223c0ac33ec0cf0522c36bb2abb6f",
        "request": "d0543d8ad0e0924b"
    }
}Type: Environment
Info: {
    "value": "northcentralus"
}Type: Location
Info: {
    "value": "northcentralus"
}Type: Time
Info: {
    "value": "2024-01-23T21:21:30.7046919+00:00"
}

**To Reproduce**
1.  Run the AzuremL code  I provided to create the Model , deploy it.

**Expected behavior**
I get the above mentioned error when I try to run TCNForecaster as the allowed model. I will be providing my exact script and error message as attachment. The same script run when Prophet model is used.
I have tried running the same code with Prophet in allowed models and it executes successfully. I tried matching this code with the Azure documentation  and didnot found any issue as such.

**Screenshots**
<img width="575" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/37649277/2581c4b2-c249-46a1-820b-21629a077c8a">

<img width="491" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/37649277/21c77eea-94a0-42d9-b0c3-2605f1983558">

**Additional context**
 Have added two files, issue.txt has the code that I am using.
 Forecasting.txt has the forecasting script

[issue.txt](https://github.com/Azure/azure-sdk-for-python/files/14035569/issue.txt)
[forecasting_script.txt](https://github.com/Azure/azure-sdk-for-python/files/14035570/forecasting_script.txt)

**Comment by jashshah-dev** [comment]
Hi team,
I am also facing the same issue. My code is similar, What fix can be implemented?

**Comment by kristapratico** [comment]
@amalprem @jashshah-dev thanks for bring this to our attention, @azureml-github can you take a look?

**Comment by amalprem** [comment]
Hi team,
Do we have any update on this issue?
@Azure/azure-ml-sdk @azureml-github.

**Comment by amalprem** [comment]
Hi team, 
Wanted to follow up on this issue. Did we identify any bugs here?
Looking forward to hearing from you soon.
