### ISSUE TITLE
Save Job source code in default datastore

### ISSUE THREAD

**Issue by AzizNadirov** [Azure/azure-sdk-for-python#33979]
I'm submitting job with default datastore = "default_datastore", which is in "storage_accout" account. But when I submit the job, its source code situated inside another account's temporary container. Looks like each job creates a container for itself, but I hant to make so that it will save code inside another account. In my case - inside `storage_accout`.

**Comment by AzizNadirov** [comment]
I found my issue here, but there is no solution
https://learn.microsoft.com/en-us/answers/questions/1379985/how-to-prevent-that-a-new-blob-storage-container-i

**Comment by kristapratico** [comment]
@AzizNadirov can you include the following information to assist us with helping on this issue?

- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

If you have example code that reproduces this problem that will also help. Thanks!
