### ISSUE TITLE
azureml-fsspec glob returns empty list

### ISSUE THREAD

**Issue by Dekermanjian** [Azure/azure-sdk-for-python#33985]
- **Package Name**:  azureml-fsspec
- **Package Version**: 1.3.0
- **Operating System**: Linux/Windows
- **Python Version**: 3.10.13

**Describe the bug**
fs.glob(".") returns empty list while fs.ls() returns an actual path

**To Reproduce**
1. init an fs using `AzureMachineLearningFileSystem`
2. call `fs.ls()` verify a path is returned then call `fs.glob(".")`
**Expected behavior**
`fs.glob('.')` should return list of paths not an empty list

**Comment by kristapratico** [comment]
@Dekermanjian thanks for your feedback, @azureml-github can you take a look?

**Comment by Dekermanjian** [comment]
@kristapratico @azureml-github
Okay, as an update. The `fs.glob()` is broken in azureml-fsspec versions 1.1.1, 1.20, and 1.30. The last version it was functional in was azureml-fsspec 1.1.0

**Comment by FeiDeng** [comment]
Please use fs.glob("*") instead

**Comment by Dekermanjian** [comment]
@FeiDeng Thank you for your response. I already had tried `fs.glob("*")` it also incorrectly returns an empty list.

**Comment by FeiDeng** [comment]
Can you share some more detail how you setup the fs?

**Comment by Dekermanjian** [comment]
@FeiDeng 
Yes, of course.
```
from azureml.fsspec import AzureMachineLearningFileSystem
url = azureml://subscriptions/<subid>/resourcegroups/<rgname>/workspaces/<workspace_name>/datastore/datastorename/
fs = AzureMachineLearningFileSystem(url)
fs.ls() # This works and gives me the available folders and files in the url path
fs.glob('.') # Does not work nor does putting in the name of a folder that is in the path
```
As a note the glob whether I use "*" or "." or give it a directory name works in azureml-fsspec version 1.1.0

**Comment by FeiDeng** [comment]
Thanks. Also what is the datastore type?

**Comment by Dekermanjian** [comment]
The datastore is a data lake storage gen 2.

**Comment by FeiDeng** [comment]
Also what is the azureml-dataprep version?

**Comment by Dekermanjian** [comment]
I am using azureml-dataprep 5.1.2

**Comment by FeiDeng** [comment]
Could you also try use a different compute (from notebook) and some other datastore? I think there are something special for this case.

**Comment by FeiDeng** [comment]
I seems not able to reproduce this

**Comment by Dekermanjian** [comment]
Hi @FeiDeng thank you for your help with this issue. 

I just tried a new compute in a new notebook and new environment using a Blob Storage this time and I am getting the same issue. See below:
![image](https://github.com/Azure/azure-sdk-for-python/assets/39779176/fe900a85-9af1-4d90-b2fd-598c0acc19df)

**Comment by FeiDeng** [comment]
I see. It seems you use the url as "azureml://subscriptions/***/resourcegroups/***/workspace/****/datastores/***/paths/"
please use "azureml://subscriptions/***/resourcegroups/***/workspace/****/datastores/***". The last part "paths/" is not a valid use case.
Let me know if that fix the issue.

**Comment by Dekermanjian** [comment]
@FeiDeng I am still getting the same issue:
![image](https://github.com/Azure/azure-sdk-for-python/assets/39779176/d882a91f-6c11-43b0-95b8-c67d1bedd80b)

**Comment by Dekermanjian** [comment]
@FeiDeng Here is how I set up the environment:
1). Create and start a new compute
2). Create a new environment:
`conda create -n test_fsspec python=3.10 -y`
3). activate and install required packages:
`pip install pip --upgrade`
`pip install azureml-fsspec==1.3.0`
'pip install azure-ai-ml'
`pip install ipykernel`
4). Run the notebook that is shown in the images I pasted above.

**Comment by FeiDeng** [comment]
Ok. Let us try this flow:
Open the AzureML studio from Azure portal
1) create a new compute, use the default python 3.8 if possible
![image](https://github.com/Azure/azure-sdk-for-python/assets/1747997/3ec06617-2be9-4197-b352-e600720f1aff)

2) do no use conda (I know there were some bug if use with studio, not sure if it is fixed or not)
3) create a new notebook, add one code block:
!pip install azureml-dataprep==5.1.3
!pip install azureml-fsspec==1.3.0
!pip install azure-ai-ml
4) restart the kernal 
![image](https://github.com/Azure/azure-sdk-for-python/assets/1747997/df526eca-9eec-4781-a192-82f029e4ee9c)
5) run the 3) script again
6) add another code block to run the fsspec test.

Hope this works.

**Comment by Dekermanjian** [comment]
@FeiDeng Okay, here are my findings. Using the azureml_py38 environment it does work. However, using a new environment as I showed above or using the built in azureml_py310_sdkv2 does not work. For the latter I get the following error:
![image](https://github.com/Azure/azure-sdk-for-python/assets/39779176/9a82dbb8-654d-444c-b8e9-aec00b40c154)

It is very restrictive if the only version that this will work with is python 3.8 as that is now in security fixes updates only and reaching end of life.

**Comment by FeiDeng** [comment]
Glad it works. So yes it should support python 3.10. I will check.

**Comment by Dekermanjian** [comment]
@FeiDeng Okay, I figured this out. The reason it is not working in other environments because there is a clash between fsspec versions. If you follow my instructions above you it will automatically install fsspec version 2023.12.2 and azureml-fsspec glob method does not work with that version of fsspec. If you install fsspec version 2023.5.0 which is the version that comes installed in the default azureml_py38 environment then azureml-fsspec glob method will work. Conversely, if you upgrade fsspec 2023.5.0 on the azureml_py38 environment to 2023.12.2 the azureml-fsspec glob method will stop working.

**Comment by FeiDeng** [comment]
My local machine use py38 with fsspec 1.3.0 and It seems fine with glob. Which version is 2023.12.2? Is that 1.3.0?

**Comment by Dekermanjian** [comment]
@FeiDeng fsspec is a dependency of azureml-fsspec. The latest version is 2023.12.2 you can find it here: https://pypi.org/project/fsspec/

**Comment by FeiDeng** [comment]
Thanks for the explanation. I see now. So for the python 3.10 env to work, it uses 2023.12.2?

**Comment by Dekermanjian** [comment]
@FeiDeng No, for both Python 3.8 and python 3.10 using version 2023.12.2 makes it not work. If you use version 2023.5.0 then both Python 3.8 and Python 3.10 will work.

**Comment by FeiDeng** [comment]
Thanks you for the details. I will add one task item to check this issue.

**Comment by Dekermanjian** [comment]
@FeiDeng thank you very much!

**Comment by FeiDeng** [comment]
So I tried setup with the default python 3.8 (same approach as above only pin the fsspec version)
!pip install azureml-dataprep==5.1.3
!pip install fsspec==2023.12.2
!pip install azureml-fsspec==1.3.0

Again it seems working fine with glob("*").
Mind to share your repo steps?

**Comment by Dekermanjian** [comment]
@FeiDeng 
I followed your process.
1) create new compute instance
2) install packages from inside the notebook
3) restart the notebook
4) run the notebook code. 

Can you please verify that you installed the correct versions of your packages. 
!pip install can install packages in the wrong environment if you are running it in a notebook. You should use %pip install instead. 

Here is a screenshot of following your steps and pinning fsspec version to 2023.12.2:
![image](https://github.com/Azure/azure-sdk-for-python/assets/39779176/bd1cf0f1-3e3d-4d7b-9343-3a6724699c39)

**Comment by FeiDeng** [comment]
Right. Seems this does not work for blob storage.

**Comment by Dekermanjian** [comment]
@FeiDeng 
It also does not work for ADLS2 as that was the original storage that was causing the problem before you asked me to try a different storage.

**Comment by FeiDeng** [comment]
Please try azureml-fsspec 1.3.1 version. https://pypi.org/project/azureml-fsspec/ 
Thanks
