### ISSUE TITLE
Unable to download file from output of job using mlclient - Azure python sdk v2

### ISSUE THREAD

**Issue by taruntadikonda** [Azure/azure-sdk-for-python#34005]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.12.1
- **Operating System**:linux
- **Python Version**: 3.9

**Describe the bug**
Unable to download a file from the outputs which are generated after job is completed.

`ml_client.jobs.download(name=job_name)`

Using the above code I am able to download all the files which are there in the outputs. And the azure blob path from where it is downloaded is `azureml://datastores/workspaceartifactstore/ExperimentRun/dcid.job_name`

When I mention a specific file to download like `ml_client.jobs.download(name=job_name,output_name=file_name)` then is looking at different data store that is `azureml://datastores/workspaceblobstore/paths/azureml/job_name/file_name`, But actually the file is in different location.

**Comment by kristapratico** [comment]
@taruntadikonda thanks for your feedback, @azureml-github can you take a look at this issue?

**Comment by banibrata-de** [comment]
What type of job is this? Also could you share the debug logs for the download call?  

For the SDK, you can enable debug logs by following these steps:

Make sure that when the ml_client is instantiated, the logging_enable parameter is set to "True". For example:
ml_client = MLClient(..., logging_enable=True)
Just before the call that is failing in the SDK, insert the following code:
import logging
logging.basicConfig(level=logging.DEBUG)

**Comment by taruntadikonda** [comment]
[download_file.txt](https://github.com/Azure/azure-sdk-for-python/files/14121854/download_file.txt)

Attached the log file.

**Comment by banibrata-de** [comment]
Thanks for the logs, looks like we have a bug to fix for single file. However, right now don't have an ETA for this. Until then please use download all files or you may want to download a single file from Azure ML studio portal.

**Comment by taruntadikonda** [comment]
@banibrata-de As you have closed the issue, is the bug fixed?

**Comment by friggog** [comment]
This bug still seems to be present `ml_client.jobs.download(name=job_name)` download _all_ the outputs/logs of the job, but specifying `output_name` seems to not download anything

Any updates?

**Comment by IliasAarab** [comment]
Same issue observed from my side.

**Comment by 0xfabioo** [comment]
@diondrapeck So, you will close this ticket without a bug fix? How do you make sure this will ever get fixed?

**Comment by pedrojrv** [comment]
I am facing the exact same issue, something change and I am now unable to donwload the models. Any fixes?

**Comment by ayumu0622** [comment]
Any update?
