### ISSUE TITLE
Json response function for azure ai document intelligence for document_intelligence_client

### ISSUE THREAD

**Issue by muizzhaque** [Azure/azure-sdk-for-python#34027]
Hi, I was using azure document intelligence client for testing out layout and invoice model
The script to do that is:
```
with open(path_to_sample_documents, "rb") as f:
    poller = document_intelligence_client.begin_analyze_document(
        "prebuilt-layout", analyze_request=f, content_type="application/octet-stream"
    )
result = poller.result()
```
Now, I wanted to store this result value as a json file but couldn't do so since the object was json unserializable
tried `json.dumps(result)` but it failed.

**Describe the solution you'd like**
I found out a way which is:
```
data = result.as_dict()
out_file = open(output_path+'.json', "w") 
json.dump(data, out_file, indent = 4) 
out_file.close()
```

I was hoping that this can be integrated as a function called json_response or something into the code base so folks don't have to spend time to just get simple json file output.

One amazing thing about this function is that it lets you store the json object  and if you wanna get any specific information then you don't have to call azure api to repeat task again and again for the same document

**Comment by kristapratico** [comment]
@muizzhaque thanks for your feature request. We'll review and get back to you as soon as possible.

**Comment by muizzhaque** [comment]
Sure!
Looking forward to it

**Comment by jp-pumpkin** [comment]
@muizzhaque 

Does this solve your issue?
``` 
from azure.core.serialization import AzureJSONEncoder

data = json.dumps(result.as_dict(), cls=AzureJSONEncoder)
```

**Comment by iMicknl** [comment]
It seems that in the new Document Intelligence SDK (https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/documentintelligence) doesn't have the as_dict() method. I face the same issue.

```
AttributeError: 'AnalyzeResult' object has no attribute 'to_dict'
```

**Comment by muizzhaque** [comment]
Yes, the `to+dict()` doesn't exist in the new document intelligence SDK, as_dict is the method to get the json response.

**Comment by YalinLi0312** [comment]
> It seems that in the new Document Intelligence SDK (https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/documentintelligence) doesn't have the `to_dict()`, but now calls it `as_dict` method.
> 
> ```
> AttributeError: 'AnalyzeResult' object has no attribute 'to_dict'
> ```
> 
> **Edit**: At a second thought not directly the same issue as OP, but would be great to have this documented / visible in a sample.

Hi @iMicknl , we've added samples for getting Json response in Document Intelligence([sync](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_convert_to_dict.py#L52)/[async](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/samples/aio/sample_convert_to_dict_async.py#L55)) and Form Recognizer([sync](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/sample_convert_to_and_from_dict.py#L56)/[async](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/async_samples/sample_convert_to_and_from_dict_async.py#L60)).
