### ISSUE TITLE
404 on Face API Python quickstart 

### ISSUE THREAD

**Issue by melissaverduci** [Azure/azure-sdk-for-python#34045]
### Type of issue

Typo

### Description

[Enter feedback here]
I click on the link Face API Python quickstart which is :
https://learn.microsoft.com/en-us/azure/cognitive-services/Face/Tutorials/FaceAPIinPythonTutorial

But I received a 404 not found

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/cognitive-services?view=azure-python

### Content source URL

https://learn.microsoft.com/en-us/python/api/overview/azure/cognitive-services?view=azure-python

### Document Version Independent Id

4be4d10c-800a-39b2-90f0-39e6de554c5d

### Article author

@azure-sdk

### Metadata

* ID: d561eda3-44eb-6bf2-3b57-4c862436eba8 
* Service: **cognitiveservices**

**Comment by rohit-ganguly** [comment]
Hi, thanks for opening this issue. If you still need a link, it seems to exist here:

https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/quickstarts-sdk/identity-client-library?tabs=windows%2Cvisual-studio&pivots=programming-language-python
