### ISSUE TITLE
Obtaining tokens via DefaultCredential should honor AZURE_CONFIG_DIR

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-sdk-for-python#34051]
- **Package Name**: azure-identity==1.14.0, azure-core==1.29.5, azure-common==1.1.28
- **Package Version**: See above
- **Operating System**: MacOS Sonoma 14.3
- **Python Version**: Python 3.9.18 (main, Sep 11 2023, 08:38:23)  [Clang 14.0.6 ]

**Describe the bug**
When customizing the Azure CLI directory with AZURE_CONFIG_DIR, DefaultCredential continues to pull from ~/.azure which can cause tenant mismatches and fail token aquisition.

**To Reproduce**
1. Set AZURE_CONFIG_DIR=${HOME}/.azure-otherenv
2. Try to obtain token using default credential, for example `pfazure ...`

**Expected behavior**
Tokens are acquired using the credentials in ~/.azure-otherenv instead of ~/.azure.

**Actual behavior**

```
azure.core.exceptions.ClientAuthenticationError: (InvalidAuthenticationTokenTenant) The access token is from the wrong issuer 'https://sts.windows.net/<tid-otherenv>/'. It must match one of the tenants 'https://sts.windows.net/<tid>/,https://sts.windows.net/<tid>/' associated with this subscription. Please use any authority (URL) from 'https://login.windows.net/<tid>,https://login.windows.net/<tid>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
```

**Additional context**

**Comment by l0lawrence** [comment]
Hi @stewartadam thanks for the feedback, we will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

We start a new subprocess to run the az command.

Instead of using `Set`, did you try use `export` to set the environment variable?

**Comment by stewartadam** [comment]
Hi @xiangyan99, yeah I've tried setting the shell variable locally as well as exporting it to the same effect. Perhaps this is PromptFlow-specific?

**Comment by xiangyan99** [comment]
In terms of "PromptFlow-specific", could you share more details how you reproed the issue? :)

**Comment by stewartadam** [comment]
Sure - I had ~/.azure setup with my normal tenant and ~/.azure-customer setup with my customer tenant, and had shell aliases to export AZURE_CONFIG_DIR and switch between them easily.

When running `pfazure` from the promptflow-tools package, I noticed it was ignoring my shell exports and always trying to authenticate with a token from ~/.azure. I assumed it might be a bug here since it uses this sdk, but maybe it's promptflow specific (ie it doesn't pass the shell exports to a sub process or something).
