### ISSUE TITLE
Content Safety Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#34059]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/contentsafety/azure-ai-contentsafety#general)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/88c068cf-53a9-473c-94ee-f2f892217129)

**Reason:**

Syntax error. Wrong word used.

**Suggestion:**
Replace `it` with `if`.

@rohit-ganguly , @lmazuel , @JieZhou000  for notification.

**Comment by v-xuto** [comment]
Low priority, close it.
