### ISSUE TITLE
Bug in UTF-8 decoding while reading only part of a (text) blob

### ISSUE THREAD

**Issue by Indy2222** [Azure/azure-sdk-for-python#34065]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.19.0
- **Operating System**: Linux
- **Python Version**: 3.10

**Describe the bug**

When downloading only part of a UTF-8 decoded text blob, the SDK sometimes raises `UnicodeDecodeError` with error message `'utf-8' codec can't decode byte 0xe2 in position ...: unexpected end of data`. See the code example below.

```python
downloader = (
    client
    .get_blob_client(some_txt_blob)
    .download_blob(timeout=30, encoding='utf-8-sig')
)
# The line below sometimes raises
downloader.read(10 * 1024 * 1024)
```

I think that this line https://github.com/Azure/azure-sdk-for-python/blob/5ee1d7add8963c82a5a8d5bf80636e21dabda681/sdk/storage/azure-storage-blob/azure/storage/blob/_download.py#L643 assumes that the accumulated data (variable `data`) always starts and ends on a UTF-8 character boundary. Depending on the blob content (e.g. presence of non-ASCII characters) and the value passed to the `read()` method, the assumption may be untrue.

**Expected behavior**

Ideally, the API should accept the number of characters to download, in the case of text decoding, instead of the number of bytes. Alternatively, it could fetch a few extra bytes if needed. At a minimum, reading a specific number of bytes (or characters) combined with text decoding should not be allowed; for example, an explicit exception should be raised, and this behavior should be documented, or the API should not even allow it.

**Additional context**

We need to gradually download and parse a large CSV file/blob. Loading the whole file into memory and parsing it all at once is not feasible.

**Comment by l0lawrence** [comment]
Hi @Indy2222 thanks for the feedback, we will investigate and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @Indy2222 Martin, thanks for bringing this to our attention and for you investigation. This does indeed seem to be an issue we overlooked when adding the `read` method. I think you are right that ultimately arbitrary length reads should not really be supported if encoding is specified however the tricky part is we can't just remove the support as that would be a breaking change. Maybe we can read a few extra bytes or something but that could get pretty complex. It may be that the best we can do now is generate a loud warning (maybe even deprecation warning) if we see people trying to use `read(size=x)` with `encoding` specified.

We will chat internally about how to best handle this and work on making some change. Thanks again.

**Comment by Indy2222** [comment]
> Hi @Indy2222 Martin, thanks for bringing this to our attention and for you investigation. This does indeed seem to be an issue we overlooked when adding the `read` method. I think you are right that ultimately arbitrary length reads should not really be supported if encoding is specified however the tricky part is we can't just remove the support as that would be a breaking change. Maybe we can read a few extra bytes or something but that could get pretty complex. It may be that the best we can do now is generate a loud warning (maybe even deprecation warning) if we see people trying to use `read(size=x)` with `encoding` specified.
> 
> We will chat internally about how to best handle this and work on making some change. Thanks again.

I have implemented correct encoding myself. Luckily, it is possible to derive last UTF-8 char boundary from just a few bytes preceding the end of the binary string. It can be guaranteed that the resulting string is no more than 3 bytes shorter (in bytes) than the requested number of bytes.

However, BOM decoding (`utf-8-sig`) and all other encodings require special treatment so in the end, it might result in a lot of additional code.

Alliteratively, you can utilize `io.TextIOWrapper` which would provide nice and standard API without the need to implement all the encoding complexity inside the SDK. This can be used under the hood to provide the old API for backward compatibility as well.

**Comment by Indy2222** [comment]
Hi, is there any progress on the issue?

**Comment by jalauzon-msft** [comment]
Hi @Indy2222 Martin, convenient timing, I just put up #35740 which should address this issue by adding a new keyword to `read` called `chars` that allows for reading a specific number of chars instead of bytes (we will use an `IncrementalDecoder` in the background). We could not change the meaning of `size` as that would be breaking but hopefully this new keyword will work for your scenario. Please let me know if this will not address this issue for you.

Still some things to work out on the PR but hopefully it will be coming in our next release or two.

**Comment by jalauzon-msft** [comment]
PR has merged, fix will be part of our next release which is targeted for sometime in July.
