### ISSUE TITLE
[Storage] Consider adding support for Batch Delete of Blob Versions

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-python#34068]
Related - https://github.com/Azure/azure-sdk-for-net/issues/40849

This is not time sensitive.  Use this issue to determine if there is customer demand for this feature.

**Comment by jalauzon-msft** [comment]
Looks like this is already supported:
https://github.com/Azure/azure-sdk-for-python/blob/773cb29f71834a4bf1863ed3049061719d655fa0/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L1485-L1486

You can specify a specific version for each blob you give as input.
