### ISSUE TITLE
SemanticSettings is missing from azure-search-documents/azure/search/documents/indexes/models /__init__.py

### ISSUE THREAD

**Issue by JetterMcTedder** [Azure/azure-sdk-for-python#34067]
- azure-search-documents: 
- 11.4.0: 
- NA:
- 3: 

**Describe the bug**
SemanticSettings is missing from azure-search-documents/azure/search/documents/indexes/models /__init__.py

**To Reproduce**
1. try and reference SemanticSettings in 11.4.0 release. It is present in the 11.4.0b11 release

**Expected behavior**
should be able to reference SemanticSettings

**Screenshots**

**Additional context**

**Comment by l0lawrence** [comment]
Hi @JetterMcTedder, thank you for the feedback we will get back to you asap.

**Comment by JetterMcTedder** [comment]
@xiangyan99 yes and it is not in there.

**Comment by JetterMcTedder** [comment]
Any updates on this?
