### ISSUE TITLE
QADataGenerator doesn't generate QA pairs in non-English languages

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-sdk-for-python#34099]
- **Package Name**: azure-ai-generative
- **Package Version**: 1.0.0b2
- **Operating System**: Linux/Debian
- **Python Version**: 3.11

**Describe the bug**

When we use the `QADataGenerator(model_config=openai_config)` with Brazilian Portuguese texts, the QA pairs generated are always in English.

I believe that is a known issue, but it needs to be documented clearly, as customers expect LLM-based tools to work in non-English languages.

**To Reproduce**

Pass in Portuguese text to this code:

        result = qa_generator.generate(
            text=text,
            qa_type=QAType.LONG_ANSWER,
            num_questions=2,
        )

And get English answers instead.

**Expected behavior**

Portuguese answers.

**Comment by l0lawrence** [comment]
Hi @pamelafox thank you for the feedback, forwarding your request to @azureml-github and they will get back to you asap.

**Comment by diondrapeck** [comment]
@pamelafox Thank you for bringing this to our attention. We will update the reference documentation to make the language limitations clear.

**Comment by diondrapeck** [comment]
@EMjetrot - the azure-ai-generative package was deprecated earlier this year, so no updates will be made to any of the classes. Instead, it's recommended that you use the [azure-ai-evaluation](https://pypi.org/project/azure-ai-evaluation/) package. The analogous class is in that library is the `Simulator` (and its subclasses) which does have support for multiple non-English languages. [Here's](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/develop/simulator-interaction-data#multi-language-adversarial-simulation) an example.
