### ISSUE TITLE
Python 3.12 support blocked by aiohttp

### ISSUE THREAD

**Issue by martin-traverse** [Azure/azure-sdk-for-python#34093]
**Is your feature request related to a problem? Please describe.**

To use async IO with the azure-core library there is a dependency on aiohttp. The aiohttp project currently does not publish wheels for Python 3.12. Although the async transport is an optional dependency of azure-core, it is a hard dependency of the Azure fsspec implementation, [adlfs](https://github.com/fsspec/adlfs). We would like to support Python 3.12 on Azure and cannot do so until this issue is resolved. This will also be impacting other projects that require async transport.

The lead maintainers of the aiohttp project are saying they need help to make the necessary updates, and that there are significant testing gaps which they are concerned about and wish to fix before a 3.12-compatible version can be released. To drive the point home, they also published this image in a recent thread on the subject:

![301373614-f71722c2-f634-4cab-b828-fe0ce77e1192](https://github.com/Azure/azure-sdk-for-python/assets/2040008/15c968bd-285b-4aac-ada2-b246734a03fe)

**Describe the solution you'd like**

I think this is a broader issues than simply getting the 3.12 package for aiohttp out of the door. I can see two potential solutions:

* MS can contribute development effort to aiohttp, to resolve this specific issue and help maintain the package going forward as and when issues or feature requirements arise
* I see there is an alternate async transport in development using HTTPX, with sample code in the azure-core-experimental library and also in a separate module called "corehttp". If the HTTPX transport were completed and made available in azure-core that should remove the dependency on aiohttp for projects requiring async, including the Azure implementation of fsspec.

**Describe alternatives you've considered**

The Apache Arrow project is also working on an Azure implementation of their FileSystem interface, for projects using Apache Arrow these Python libraries may not be needed at all once that is available. This might help my particular project eventually, but probably doesn't help most people who want to use Python on Azure.

**Additional context**

Issue thread for aiohttp: https://github.com/aio-libs/multidict/issues/887
Note in adlfs about requirement of aiohttp: https://github.com/fsspec/adlfs/issues/452
Azure core docs on HTTP transport: [CLIENT_LIBRARY_DEVELOPER#transport](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md?rgh-link-date=2022-09-06T11%3A12%3A07Z#transport)
Azure core experimental library: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core-experimental
Azure corehttp library: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/corehttp

**Comment by xiangyan99** [comment]
Thanks for reaching out. 

It seems to me aiohttp has released 3.12 support. https://pypi.org/project/aiohttp/#files

Did I miss anything?

**Comment by martin-traverse** [comment]
There is a thing called "multidict", a library which is part of the AIO project and sits near the bottom of the stack. The aiohttp package has a hard dependency on multidict, and multidict is not available for Python 3.12.

https://github.com/aio-libs/multidict
https://pypi.org/project/multidict/#files

Running `pip install aiohttp`, or `pip install adlfs` or even `pip install azure-core[aio]` on Python 3.12 will trigger a build for multidict, which fails if you don't have the C build chain installed and configured.

**Comment by xiangyan99** [comment]
There was a new multidict library released which supported 3.12 about half hours ago.
(I saw you were in the thread so maybe you knew it already).

**Comment by martin-traverse** [comment]
The issue in aiohttp is now resolved which addresses the immediate problem, Python 3.12 now works with azure-core AIO so fsspec (adlfs) and anything else using async storage is unblocked (including my own project). I am happy if this issue is closed.

I do think it is worth discussing the broader point around the open source dependency tree. There are obviously big upsides to a shared ecosystem of common components but two major downsides are inconsistent support model and proliferation of dependency bloat. These issues can be mitigated in specific cases, either by contributing upstream or selecting dependencies with a well defined support model and small transitive dependency tree.

In this case both options are available, ether [working with the upstream project](https://github.com/aio-libs/multidict/issues) or [selecting alternate dependencies](https://github.com/encode/httpx) could help alleviate issues before they arise.
