### ISSUE TITLE
Getting error on uploading file using put_page_blob_from_path

### ISSUE THREAD

**Issue by vmksuw** [Azure/azure-sdk-for-python#341]
Hi,
I got following error while uploading file as page blob-

azure/storage/blobservice.py\", line 1318, in put_page_blob_from_path
retry_wait)
IOError: close() called during concurrent operation on the same file object.

Thanks,
Vaibhav

**Comment by huguesv** [comment]
Hi!  Is this something you can repro consistently?  Could you include the code I can use to repro it, including the size of the file you are trying to upload?

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/9
