### ISSUE TITLE
AzureMonitorLogExporter logs are not visible in Application Insights

### ISSUE THREAD

**Issue by sudharsan2020** [Azure/azure-sdk-for-python#34111]
- **Package Name**: azure-monitor-opentelemetry
- **Package Version**: 
```
azure-monitor-opentelemetry==1.2.0
azure-monitor-opentelemetry-exporter==1.0.0b21
azure-core-tracing-opentelemetry==1.0.0b11
azure-monitor-opentelemetry==1.2.0
azure-monitor-opentelemetry-exporter==1.0.0b21
opentelemetry-api==1.22.0
opentelemetry-instrumentation==0.43b0
opentelemetry-instrumentation-asgi==0.43b0
opentelemetry-instrumentation-dbapi==0.43b0
opentelemetry-instrumentation-django==0.43b0
opentelemetry-instrumentation-fastapi==0.43b0
opentelemetry-instrumentation-flask==0.43b0
opentelemetry-instrumentation-psycopg2==0.43b0
opentelemetry-instrumentation-requests==0.43b0
opentelemetry-instrumentation-urllib==0.43b0
opentelemetry-instrumentation-urllib3==0.43b0
opentelemetry-instrumentation-wsgi==0.43b0
opentelemetry-resource-detector-azure==0.1.3
opentelemetry-sdk==1.22.0
opentelemetry-semantic-conventions==0.43b0
opentelemetry-util-http==0.43b0
```
- **Operating System**: Linux
- **Python Version**:  3.11

**Describe the bug**
`AzureMonitorLogExporter` logs are not displayed in the Azure application insights

**To Reproduce**
```
import logging

from azure.monitor.opentelemetry.exporter import AzureMonitorLogExporter
from opentelemetry._logs import set_logger_provider
from opentelemetry.sdk._logs import LoggerProvider, LoggingHandler
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
from opentelemetry.sdk.resources import Resource


class LogHandler:
    def __init__(
        self,
        app_name: str,
        app_version: str,
        **kwargs,
    ):
        """_summary_

        Args:
            app_name: app name
            app_version: app version
            kwargs Additional logging parameters
        """
        self.app_name = app_name
        self.app_version = app_version
        self.kwargs = kwargs

        # Create the logging provider
        self.logger_provider = LoggerProvider(resource=self._get_resource())
        set_logger_provider(self.logger_provider)
        exporter = AzureMonitorLogExporter(
            connection_string=os.environ["APPLICATIONINSIGHTS_CONNECTION_STRING"],
        )
        self.logger_provider.add_log_record_processor(BatchLogRecordProcessor(exporter))

        # Create the logging handler
        self.handler = LoggingHandler()

        # Attach LoggingHandler to root logger
        self._logger = logging.getLogger(self.app_name)
        self._logger.addHandler(self.handler)
        self._logger.setLevel(logging.INFO)
```
**Implementation**:
```
    with tracer.start_as_current_span(name="my-application") as application_span:
        start_time = time.time()

        # Update the operation parameters
        application_span.set_attributes(OPERATION_PARAMETERS_DICT)

        logger.info(
          f"Function app service trigger received"
          extra={'region_name':'Central US'},
        )

```

**Expected behavior**
`AzureMonitorLogExporter` logs should be displayed in the Azure application insights.
We could see the same telemetry events in the `Performance` tab of Azure application insights when using `AzureMonitorTraceExporter`. The working traces are attached in the screenshot

**Screenshots**
![2024-02-02_11-43](https://github.com/Azure/azure-sdk-for-python/assets/9370130/8731c9a4-76e6-452d-8b36-866e44a92c38)

**Additional context**

**Comment by l0lawrence** [comment]
Hi @sudharsan2020 thanks for the feedback, we will get back to you asap.

**Comment by lzchen** [comment]
```
logger.info(
          f"Function app service trigger received"
          extra={'region_name':'Central US'},
        )
```
Is `logger` an instance of `LogHandler`? How are you instantiating `logger`?

**Comment by sudharsan2020** [comment]
@lzchen We are using the instance of Logger like below:

```
logger = LogHandler(
    application_name='app-name',
    activity_name='activity-name',
    app_version=1.1.0,
    **OPERATION_PARAMETERS_DICT
).logger
```
Please refer the updated `Logger` code.

```
from azure.monitor.opentelemetry.exporter._generated.models import ContextTagKeys

# Operation parameters
OPERATION_PARAMETERS_DICT = {
    ContextTagKeys.AI_OPERATION_NAME.value: 'my-operation-name',
    ContextTagKeys.AI_APPLICATION_VER.value: 1.1.0,
}
```

**Comment by lzchen** [comment]
Just to confirm, if you go to your `traces` table in AppInsights, you aren't able to see any of your logging records? The given screenshot also doesn't seem to be matching your code, there should be a dependency with name "my-application" in there that i don't see. Is the example outdated?

**Comment by sudharsan2020** [comment]
@lzchen I've given a mock application name just as a placeholder. 
Yes I couldn't see any traces from application insights.
Please let me know if any additional details are required

**Comment by sudharsan2020** [comment]
@lzchen Do you have any updates on the issue?

**Comment by lzchen** [comment]
@sudharsan2020 

We are investigating your issue.

**Comment by lzchen** [comment]
@sudharsan2020 

I've replicated your use case with a minimal example with just an in_proc dependency and a simple log message.

```python
import os
import logging

from opentelemetry._logs import (
    get_logger_provider,
    set_logger_provider,
)
from opentelemetry.sdk._logs import (
    LoggerProvider,
    LoggingHandler,
)
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor

from azure.monitor.opentelemetry.exporter import AzureMonitorLogExporter

from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

from azure.monitor.opentelemetry.exporter import AzureMonitorTraceExporter

class LogHandler:
    def __init__(
        self,
        app_name: str,
        app_version: str,
        **kwargs,
    ):
        """_summary_

        Args:
            app_name: app name
            app_version: app version
            kwargs Additional logging parameters
        """
        self.app_name = app_name
        self.app_version = app_version
        self.kwargs = kwargs

        # Create the logging provider
        self.logger_provider = LoggerProvider()
        set_logger_provider(self.logger_provider)
        exporter = AzureMonitorLogExporter(
            connection_string=os.environ["APPLICATIONINSIGHTS_CONNECTION_STRING"],
        )
        self.logger_provider.add_log_record_processor(BatchLogRecordProcessor(exporter))

        # Create the logging handler
        self.handler = LoggingHandler()

        # Attach LoggingHandler to root logger
        self._logger = logging.getLogger(self.app_name)
        self._logger.addHandler(self.handler)
        self._logger.setLevel(logging.INFO)

log_handler = LogHandler(app_name='app-name', app_version=1.0)
logger = log_handler._logger


exporter = AzureMonitorTraceExporter.from_connection_string(
    os.environ["APPLICATIONINSIGHTS_CONNECTION_STRING"]
)

tracer_provider = TracerProvider()
trace.set_tracer_provider(tracer_provider)
tracer = trace.get_tracer(__name__)
span_processor = BatchSpanProcessor(exporter, schedule_delay_millis=60000)
trace.get_tracer_provider().add_span_processor(span_processor)

with tracer.start_as_current_span(name="my-application") as application_span:
    logger.info("test log message")

input()
```

The logging messages appears under the end-to-end transaction view as "traces available" corresponding to the correlated dependency telemetry, as shown below:

![image](https://github.com/Azure/azure-sdk-for-python/assets/11580155/5d08c102-f839-4924-9189-27ea1ff9ce29)

Could you see if you have a similar icon as shown in the screenshot? That should be where your logging message appears.

FYI, the trace telemetry and dependency telemetry show up properly under the "Logs" view so the telemetry is indeed there and correct. Please note that the `id` in the dependency telemetry and the `operation_parentId` in the trace telemetry are the same, meaning they are correctly correlated.

![image](https://github.com/Azure/azure-sdk-for-python/assets/11580155/773e5b93-60aa-4527-bd13-b91bf22aecd3)

![image](https://github.com/Azure/azure-sdk-for-python/assets/11580155/e385e471-9946-4efb-bb8d-0a1934567cba)

**Comment by sudharsan2020** [comment]
@lzchen I was trying to add some property filters to log. Is it due to that the logs aren't displayed?
Still no logs are displayed in the traces

```
        self._logger.addFilter(JobIdFilter(LogHandler.job_id))
        self._logger.addFilter(AppPropertiesFilter(
            application_name=self.application_name,
            app_version=self.app_version,
            **self.kwargs
        ))
```

```
class JobIdFilter(logging.Filter):

    def __init__(self, job_id: contextvars.ContextVar):
        self.job_id = job_id
        super().__init__()

    def filter(self, record):
        """update custom dimensions with job_id"""
        record.__setattr__("job_id", self.job_id.get("None"))
        # Set the operation id
        record.traceId = self.job_id.get("None")
```
```
class AppPropertiesFilter(logging.Filter):
    """App properties ID filter to append job id from contextvars to custom dimensions"""

    def __init__(
            self,
            application_name: str,
            app_version: str,
            **kwargs,
    ):
        self.application_name = application_name
        self.app_version = app_version
        self.kwargs = kwargs
        super().__init__()

    def filter(self, record):
        """update custom dimensions """
        record.__setattr__("application_name", self.application_name)
        record.__setattr__("app_version", self.app_version)
```

**Comment by lzchen** [comment]
@sudharsan2020 

Please confirm whether or not the original diagnosis of your issue has addressed your concerns before modifying or changing your code. Do you see traces in your transaction view via "traces available" or "traces" under the "Logs" tab in Application Insights? Your initial screenshot indicates you do indeed have traces.

**Comment by sudharsan2020** [comment]
@lzchen Yes traces are working, but **unable to view logs**. Is `addFilter` supported by `Open Telemetry`. Now I will try removing it and validate

**Comment by sudharsan2020** [comment]
@lzchen No I am unable to see any **traces**. This looks very strange. I could still see logs when using the **Opencensus** library. Recently after migrating to the **Opentelemetry**, the logs couldn't be seen in the Application Insights.

**Comment by sudharsan2020** [comment]
@lzchen Found one observation after modifying the logging configuration in the `host.json`. 

**Old configuration**
```
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "maxTelemetryItemsPerSecond" : 20,
        "excludedTypes": "Request"
      }
    }
  }
```


**New configuration**
After enabling the below configuration, I **could see traces**, however, the log messages logged in the below format aren't appearing.

```
logger.info(
      f"Service bus trigger received for transaction id: {request_model.transaction_id}",
      extra=request_model.model_dump(exclude_none=True),
  )
```
![image](https://github.com/Azure/azure-sdk-for-python/assets/9370130/91ebfff1-0180-4dcb-babd-57bfc457df9b)


```
  "logging": {
    "fileLoggingMode": "debugOnly",
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "maxTelemetryItemsPerSecond" : 20,
        "excludedTypes" : "Dependency;Event",
        "includedTypes" : "Trace"
      },
      "enableLiveMetrics": true,
      "enableDependencyTracking": true,
      "enablePerformanceCountersCollection": true
    }
  },
```
Can you please confirm if any issues with the logger configuration in **host.json** ?

**Comment by sudharsan2020** [comment]
@lzchen Thanks for your awesome support. The traces are now visible in the Application Insights.

![image](https://github.com/Azure/azure-sdk-for-python/assets/9370130/caa18533-fed6-4ba1-a74b-ef5d5818ce7c)

However, I couldn't set the **Operation Name** to the logs. Can you guide on this?

![image](https://github.com/Azure/azure-sdk-for-python/assets/9370130/9d4b8064-1373-4f63-8d48-b326d8e46281)

The **Operation Name** parameter is found only in Traces and not in Logs in the SDK:

![image](https://github.com/Azure/azure-sdk-for-python/assets/9370130/b2bee9af-844a-4462-b1a4-336ce00462e7)

**Comment by lzchen** [comment]
@sudharsan2020 

`operation.name` is only available for distributed tracing type telemetry (Traces).
