### ISSUE TITLE
How to Perform Bulk Delete in Azure Resource Group using Azure Python SDK

### ISSUE THREAD

**Issue by tamilhce** [Azure/azure-sdk-for-python#3415]
For Example, how to delete a list of virtual machines in a resource group  in a  single api call.Bcoz,In my infrastructure, i have 100's of VM's, deleting them  sequentially  one by one consumes lot of api calls.How we achieve the same through the scripts which is 
similar to the below action in the azure portal. 
<img width="1207" alt="n3h10" src="https://user-images.githubusercontent.com/4208906/45944830-2e5ebf00-c009-11e8-820c-2affe3723c68.png">

**Comment by lmazuel** [comment]
Hi @tamilhce 

Unfortunately, the batch endpoint is Portal only and is not supported by SDKs. This issue for discussion: https://github.com/Azure/msrestazure-for-python/issues/74

@johanste

**Comment by lmazuel** [comment]
Keeping the issue opened, tagged as RestAPI and ARM.

**Comment by brendandburns** [comment]
ARM has no current plans to expose the batch endpoint. This should be closed.

**Comment by lmazuel** [comment]
We can't support the functionalities in SDK if the RestAPI does not support it :( Since this is a SDK repo, I have to close the issue as won't fix...

You can open a discussion on https://feedback.azure.com/ if you want to discuss this feature at the RestAPI level.
