### ISSUE TITLE
Incorrect URL azure-sdk-python is in many places in this repo

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-sdk-for-python#34174]
- **Package Name**: Many packages
- **Package Version**:  N/A
- **Operating System**: N/A
- **Python Version**:  N/A

**Describe the bug**

See this line in setup.py:

https://github.com/Azure/azure-sdk-for-python/blob/4cb239a6ec965710149907234a41bcbdfc1f18f7/sdk/ai/azure-ai-generative/setup.py#L138

It points to https://github.com/Azure/azure-sdk-python but that is an archived repository.

It should instead point here.

This results is misleading dependabot links, like the "compare view" link from this PR- https://github.com/Azure-Samples/ai-rag-chat-evaluator/pull/43

**Comment by mccoyp** [comment]
Hi @pamelafox, thank you for opening an issue! I'll take a look at this as soon as possible.
