### ISSUE TITLE
Resource property values are not returned from list_by_resource_group method output

### ISSUE THREAD

**Issue by dyrx** [Azure/azure-sdk-for-python#34189]
- **Package Name**: azure-mgmt-resource
- **Package Version**:  23.0.1
- **Operating System**: Windows
- **Python Version**: 3.10.4

**Describe the bug**
Resources returned by ResourceManagementClient(credential, subscription_id).resources.list_by_resource_group(resource_group) have empty Property values

Code:
![image](https://github.com/Azure/azure-sdk-for-python/assets/25497556/4e5103ec-0d9e-4d78-980b-7aa091bd96e0)
Output:
![image](https://github.com/Azure/azure-sdk-for-python/assets/25497556/ce85a724-c996-4c29-93ef-cb31eb4335b2)

This is isolated to the Resources returned by the above method, the following works correctly and returns the Resource's property value correctly:

![image](https://github.com/Azure/azure-sdk-for-python/assets/25497556/32e58461-42b3-446e-a591-e3ff68dd547c)

**Expected behavior**
The returned Resources should have a non-None property attribute

**Comment by mccoyp** [comment]
Hi @dyrx, thank you for opening an issue! I'll tag someone who should be able to provide some clarity; we'll get back to you as soon as possible.

**Comment by ChenxiJiang333** [comment]
Hi @dyrx 
Shortly, the method `resources.list_by_resource_group()` cannot get detailed information about resource properties like method `resources.get_by_id()` can do. For its request was sent to the provider `Microsoft.Resources` which does not have the schema to describe a specified resource, so it can only return basic information(id, name, tag, sku, location, etc.). Yet by using method `resources.get_by_id()`, the request was sent to the related provider, for example, when getting properties of a storage account, the request will be sent to `Microsoft.storage`, which has the schema of its properties that can return detailed information.

So, if you want to get all detailed resource properties among a resource group, try circularly run the method `resources.get_by_id()`.
