### ISSUE TITLE
Azure-Identity: AzurePowerShellCredential() raises exception "failed to invoke PowerShell"

### ISSUE THREAD

**Issue by georgkuenz** [Azure/azure-sdk-for-python#34194]
- **Package Name**: azure-identity
- **Package Version**: 1.15.0
- **Operating System**: Windows 10, 22H2
- **Python Version**: 3.11.4
- **Visual Studio Code Version**: 1.86
- **Powershell Version**: 5.1.19041.3930

**Describe the bug**
I'm trying to read Azure KeyVault Secrets using the Azure Identity Library using *AzurePowerShellCredential*

Code:
![image](https://github.com/Azure/azure-sdk-for-python/assets/159158094/c5151faa-000d-469e-805b-13485d8aab70)

The execution fails with the exception: *AzurePowerShellCredential.get_token failed: Failed to invoke PowerShell*

The login using *Connect-AzAccount* is successful and it is also possible to read secrets via Powershell, e.g. *Get-AzKeyVaultSecret -VaultName 'kv-cbm-databricks' -Name "eventhub-name" -AsPlainText*, 

**To Reproduce**
1. Create Python - Project in Visual Studio Code
2. Add above code
3. Connect to AZ account via Powershell using *Connect-AzAccount* (wait for reply)
4. Execute Code

**Expected behavior**
Secret is read out successfully

**Additional context**
If *AzureCliCredential* is used instead, everything works fine
![image](https://github.com/Azure/azure-sdk-for-python/assets/159158094/548ba375-85ff-4b1c-8dc9-1212816dcabb)
Step 3) Replace with: Connect to AZ using via CLI using *az login*

**Comment by mccoyp** [comment]
Hi @georgkuenz, thank you for opening an issue! I'll tag some folks who should be able to help; we'll get back to you as soon as possible.

**Comment by pvaneck** [comment]
Hey @georgkuenz, Do you mind re-running with debug logging enabled? This can be done by adding the following at the top of your script:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

This might expose if the powershell command is returning any errors.

**Comment by georgkuenz** [comment]
@pvaneck See attached log file
[debuglog.txt](https://github.com/Azure/azure-sdk-for-python/files/14191754/debuglog.txt)

**Comment by xiangyan99** [comment]
Thanks for sharing the log.

Could you try run `pwsh.exe` & `powershell.exe` separately and share the results?

**Comment by pvaneck** [comment]
Thanks, @georgkuenz.

I think the issue might be stemming from how we error check. First, `cmd /c pwsh ...` is run, and if that is not found, we try `cmd /c powershell ...`

I'm assuming the call to `pwsh` is failing, and normally we check for if "is not recognized" is in the stderr message before falling back to trying `powershell`. Given that for you, stderr is printing: `Der Befehl "pwsh" ist entweder falsch geschrieben oder konnte nicht gefunden werden.`, we may have to see if there is a better way to check if `pwsh` can't be found. Would be good to confirm that `pwsh` is indeed not available by running the commands as @xiangyan99 suggested.

**Comment by georgkuenz** [comment]
Dear @xiangyan99 @pvaneck: i can confirm that pwsh is not available:

![image](https://github.com/Azure/azure-sdk-for-python/assets/159158094/f9122871-3213-4a37-9191-9012326f68ea)

**Comment by pvaneck** [comment]
Thanks, I think that pretty much confirms the issue. As an immediate workaround, installing a newer version of powershell should enable the `pwsh` command in command prompt: https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-windows


I will look into seeing if we can reliably check the exit code from the internal call to `cmd /c pwsh` to determine if we should fall back to powershell.exe.

**Comment by georgkuenz** [comment]
@pvaneck Updating Powershell to the latest version solved the issue. Thx for your help!
