### ISSUE TITLE
Refactor appears to have broken retries for azure-core pipelines

### ISSUE THREAD

**Issue by davidhao3300** [Azure/azure-sdk-for-python#34203]
- **Package Name**: azure-core
- **Package Version**: 1.29.6
- **Operating System**: MacOS
- **Python Version**:  3.11

**Describe the bug**

The retry header is sometimes a float (like 0.941641). Right now the retry header parsing logic assumes either an int or a datetime.

The error looks something like ValueError(Not a valid date) since the code falls back to date-parsing if int-casting fails.

**To Reproduce**
I ran `ContainerRegistryClient(...).delete_repository(...)` in a loop when encountering the issue

**Expected behavior**

The loop should not encounter a ValueError from the retry-header parsing logic

**Additional context**

I took a look at the git history. I think a refactor 4 years ago caused the regression.

[Pre-refactor](https://github.com/Azure/azure-sdk-for-python/commit/336f3f7c75d371695f0e2050359d3459b2410c87#diff-8bd31568d4a10d8798e276761a980925a9eb4a6d310bc5ffbde2ce8d77c8b8d7L171)
[Post-refactor](https://github.com/Azure/azure-sdk-for-python/commit/336f3f7c75d371695f0e2050359d3459b2410c87#diff-547f37bcea6e5e085b596c30ef94ad2f9cff42b392d6f187143f6c4263c20369R68)

Note how we used to cast to float, but now it's an int. I think the solution is to simply restore the float cast, but will leave that to y'all.

I edited the code locally and ran my script, and no longer encounter the value error

**Comment by mccoyp** [comment]
Hi @davidhao3300, thank you for opening an issue! I'll tag some folks who can take a look; we'll get back to you as soon as possible.

**Comment by xiangyan99** [comment]
Per https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.3:

A delay-seconds value is a non-negative decimal integer, representing time in seconds.

Looks like this is a service bug?

**Comment by xiangyan99** [comment]
And just FYI, we will update azure-core to accept float "retry-after" header. (see attached PR).

It will be available in next release.

**Comment by davidhao3300** [comment]
Waiting for PR to merge to resolve!

**Comment by xiangyan99** [comment]
PR is merged. :)
