### ISSUE TITLE
Question regards to getting _models.BlobContainer object of public container

### ISSUE THREAD

**Issue by landscapepainter** [Azure/azure-sdk-for-python#34209]
I'm trying to interact with the public container using the sdk. For the containers I created under my subscription id, I'm using the following script to successfully get the _models.BlobContainer object:
```
      container = self.storage_client.blob_containers.get(
          self.resource_group_name,
          self.storage_account_name,
          self.name
      )
```

But for public containers, I cannot find a way to do so. What are some recommended ways to interact with a public container object?

**Comment by mccoyp** [comment]
Hi @landscapepainter, thank you for opening an issue! It looks like you're using a Storage library, but would you be able to share what package you're using (and which version) specifically?

I'll tag some folks who should be able to help; we'll get back to you as soon as possible.

**Comment by landscapepainter** [comment]
Hi @mccoyp, I'm currently using the following package:
```
Name: azure-mgmt-storage
Version: 21.1.0
Summary: Microsoft Azure Storage Management Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /opt/conda/envs/sky-dev/lib/python3.9/site-packages
Requires: azure-common, azure-mgmt-core, isodate
Required-by: azure-cli
```

And the `self.storage_client` I am using is an instance of from `from azure.mgmt.storage import StorageManagementClient`

**Comment by landscapepainter** [comment]
@msyyc @mccoyp Also, how do I check if the url of the public container provided exists or not?

Thanks for all the great work. I'm currenty working to integrate Azure blob storage into Skypilot: https://github.com/skypilot-org/skypilot/pull/3032

**Comment by ChenxiJiang333** [comment]
Hi @landscapepainter. 
For public container, do you mean the container that allows public read access? If so, you can get its data through this sample:
```
    account_url = "https://<storageaccount>.blob.core.windows.net"
    client = BlobServiceClient(
        #credential=DefaultAzureCredential(), do not pass credential
        account_url=account_url,
    )

    container_client = client.get_container_client(<containername>)

    print(container_client.exists())

    for blob in container_client.list_blobs():
        print(f"blobs: {blob.name}")
```

But if you also want to modify it, I guess there's no such a way since it needs further authorization.
