### ISSUE TITLE
Conda not found when Deploying Foundation Model for BatchDeployment 

### ISSUE THREAD

**Issue by michalmiki** [Azure/azure-sdk-for-python#34214]
SDKv2

**Describe the bug**
I am getting `conda not found` error while trying  follow examples from [text-generation-batch](https://github.com/Azure/azureml-examples/blob/main/sdk/python/foundation-models/system/inference/text-generation/text-generation-batch-endpoint.ipynb ) but for any MistralAI models. 
Notebook works for PHI-2 model, but fails for MistralAI for some reason at the stage of building an image. 

**To Reproduce**
1.  Follow [text-generation-batch](https://github.com/Azure/azureml-examples/blob/main/sdk/python/foundation-models/system/inference/text-generation/text-generation-batch-endpoint.ipynb ) 
2. Use `model_name = "mistralai-Mixtral-8x7B-v01, model_version = "3"` in place of the model. 

**Expected behavior**
For `microsoft-phi-2` it works. 

Output from the std_log.txt of prep_image job: 

`Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
[0mRemoving intermediate container d4dde29932db
 ---> 2aa34cd3be67
Step 7/17 : COPY azureml-environment-setup/mutated_conda_dependencies.yml azureml-environment-setup/mutated_conda_dependencies.yml
 ---> 18268e1b3b87
Step 8/17 : RUN ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_5862a4b4306383e4a8a813c7601a759d -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig
 ---> Running in e1944eca8331
[91m/bin/sh: 1: conda: not found
The command '/bin/sh -c ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_5862a4b4306383e4a8a813c7601a759d -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig' returned a non-zero code: 127
[0m`

Edit: 

I tried to use my own environment, but ended up with very same error.

**Comment by mccoyp** [comment]
Hi @michalmiki, thank you for opening an issue! I'll tag some folks who should be able to help; we'll get back to you as soon as possible. cc @azureml-github

**Comment by michalmiki** [comment]
Hey guys, any update on this? @azureml-github @novaturient95 
Could it be because I am trying to deploy chat-completion model (Mixtral-Instruct) for text generation task?

**Comment by michalmiki** [comment]
Update from my side. Getting exactly same error while  trying to use recent Llama-13b, version 16. Version 15 works, so it seems like it is something on docker side.

**Comment by novaturient95** [comment]
Thanks for reaching out @michalmiki. We are looking internally and working on a fix for Mixtral batch deployment failure. We will share updates soon. Thanks

**Comment by novaturient95** [comment]
@michalmiki also, for chat we should not use text-gen task notebook. Right now, image build fails which is common for both Mixtral base and instruct model. We are looking internally to get base model batch deployment fixed. Thanks

**Comment by michalmiki** [comment]
Thanks @novaturient95 for quick response. Can you advise how can I use batch endpoint for chat-completion task? Is it possible?

**Comment by banibrata-de** [comment]
We investigated into this and found Mistral not supported for model on Batch Endpoint.
