### ISSUE TITLE
Deprecated python module

### ISSUE THREAD

**Issue by SeryioGonzalez** [Azure/azure-sdk-for-python#34220]
### Type of issue

Typo

### Description

     When executing the snippet in this page, I get this error:
 
      Starting with v0.4.0, this package cannot be installed anymore, please use [azure-mgmt-monitor](https://pypi.org/project/azure-mgmt-monitor/) instead.
      
The snippet should be updated and make use of https://pypi.org/project/azure-mgmt-monitor/

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/monitor-ingestion-readme?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/monitor-ingestion-readme.md

### Document Version Independent Id

14cf0dab-306e-8246-7479-b2691748218c

### Article author

@azure-sdk

### Metadata

* ID: e67a5881-fb27-08c2-0b12-d8d21b4e2936 
* Service: **monitor**

**Comment by mccoyp** [comment]
Hi @SeryioGonzalez, thank you for opening an issue! I'll tag someone who can take a look; we'll get back to you as soon as possible.

**Comment by pvaneck** [comment]
Hey @SeryioGonzalez, In the document linked, I don't see any code snippet where `azure-monitor` is being installed. There is a `pip install azure-monitor-ingestion` which should work. Perhaps, `azure-monitor` was mistakenly used instead of `azure-monitor-ingestion`?
