### ISSUE TITLE
@received_timestamp_utc property for ServiceBusReceivedMessage

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [Azure/azure-sdk-for-python#34238]
I often need to record and then re-play streams of `ServiceBusMessage`s. For that i'd like to record the time at which the message was received so i can replay the traffic accurately. I'm using the private property `_ received_timestamp_utc` but it would be a bit neater if it was also exposed via @property as a public read-only attribute.

**Comment by kashifkhan** [comment]
Hi @MarcinKonowalczyk, 

Can you please expand on the use case for recording & replaying streams of the received messages? This way we can help advise on the situation a bit better. 

As such Service Bus cannot replay messages and the message in the receiver is what the service thinks is the next message (so ordering is not strictly guaranteed). This property therefore doesn't apply to service bus capabilities, as the class is simply meant to represent the data from the broker, so we will not be accepting the PR.

**Comment by MarcinKonowalczyk** [comment]
I'm receiving messages from an external source, and I need to be able to reapply them in the future, in the exact order they were received, for testing purposes. I have a simple client which establishes the connection, records a bunch of received messages and then serialises them with joblib.

On the we side of this, i've written a simple MockServiceBusClient which reads the messages from a file and "sends" them as if they were received at their respective receive time.

**Comment by MarcinKonowalczyk** [comment]
> This property therefore doesn't apply to service bus capabilities, as the class is simply meant to represent the data from the broker

And I would argue that a read-only property of a data received from the broker is the time at which it was received, regardless of my specific application of replaying the message stream. As a different use case, imagine that in the message processing code there is a need for the current time. Of course one could call `datetime.now()` again, but depending on the complexity of the code, this point might actually be quite far in the future and, if one wants to record the time when the message was received they'd have to then carry that variable alongside the message through a lot of dove, or package the message and the timestamp into a custom dataclass/namedtuple/younameit. It's not difficult but it's a bother and makes the code messy, especially when the ServiceBusReceivedMessage *already has* that attribute. I'm just proposing to expose it as public (not that there really is such a thing as private attribute in python, but besides) for convenience.

**Comment by kashifkhan** [comment]
After discussing with a few folks, the recommendation was to use the `sequence_number` or even `enqueue_time` to accomplish that. There is perhaps a way to look at the `expire_at_utc` and knowing the lock time, to calculate when the message was taken off the queue.  As there can be multiple receivers on a queue / topic the time received can have a completely different meaning based on who received things and when, so making it public can imply features that SB doesn't support such as asking for a particular message from the queue. As is there isnt an ordering guarantee.

**Comment by MarcinKonowalczyk** [comment]
cheers for looking into that. judging by the response i think i've had a bit of a different vision of what the `ServiceBusReceivedMessage` represents. in my view it was an object that represents something i have gained control over on the client side, and therefore a natural property of such an object is the time at which i received it - a property imparted onto it by the client. that's not what the `ServiceBusReceivedMessage` actually is then(?)

as an aside; your proposed solution of using the `sequence_number`, `enqueue_time` or `expire_at_utc` would not work. `sequence_number` has nothing to do with realtime clock. `enqueue_time` tells me about the time the message was put onto the queue, not the time i've received it, and `expire_at_utc` tells me when the message will expire, not the time i've received it.

and again; this is not a serious problem i have. it is trivial to wrap a `ServiceBusReceivedMessage` into another object and then add whatever the soul desires as additional properties. i'm merely surprised that, what i'd personally consider to be a very basic property of the message is not exposed as a public property (but still recorded as a private one). i do accept this will not be added to the api though.

**Comment by kashifkhan** [comment]
@MarcinKonowalczyk the `ServiceBusReceivedMessage` is a representation of the data from the broker, its state in there, so we don't want to mutate it or enrich it going in or out. Taking a look at the object in other languages (JavaScript, C#, Go, Java etc.), there isn't a received timestamp in there either (such a change would warrant an update across languages to maintain uniformity).
 
In our codebase, that property isn't used anywhere other than a mock object in a test.  It was probably added by mistake and not removed. As such we won't make it part of the public API giving the impression that its fine to use and a feature supported by the service today.
