### ISSUE TITLE
An unexpected error occurred: (', DeserializationError: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', 'Unable to build a model: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError(",  AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'")))

### ISSUE THREAD

**Issue by pj250183** [Azure/azure-sdk-for-python#34242]
- **Package Name**: from azure.mgmt.datafactory.models import TumblingWindowTrigger, TriggerReference
- **Package Version**: azure-mgmt-datafactory 5.0.0
- **Operating System**: Windows 10 64 bit
- **Python Version**: 3.8.9

**Describe the bug**
While running this code facing issue:
An unexpected error occurred: (', DeserializationError: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', 'Unable to build a model: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError(", 
AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'")))

Code:
`import trigger_config
from azure.identity import DefaultAzureCredential
from azure.mgmt.datafactory import DataFactoryManagementClient
from azure.mgmt.datafactory.models import TumblingWindowTrigger, TriggerReference
from azure.core.exceptions import HttpResponseError

subscription_id = trigger_config.SUBSCRIPTION_ID
resource_group_name = trigger_config.RESOURCE_GROUP
data_factory_name = trigger_config.DATA_FACTORY_NAME

trigger_name = 'test1'
pipeline_name = 'src2stg_accountsreceivable_edw_tedw_wf'  

credential = DefaultAzureCredential()

adf_client = DataFactoryManagementClient(credential, subscription_id)
print("adf_client",adf_client)

pipeline_id = adf_client.pipelines.get(resource_group_name, data_factory_name, pipeline_name).id
print("pipeline_id", pipeline_id)
trigger_properties = TumblingWindowTrigger(
    pipeline=pipeline_name,
    frequency='Hour',
    interval=24,
    start_time='2024-02-08T07:00:00Z',
    delay='00:00:00',
    max_concurrency=1,
    retry_policy={'count': 3, 'intervalInSeconds': 60},
    depends_on=[]
)
print("trigger_properties",trigger_properties)
try:

    trigger_reference = TriggerReference(type='PipelineReference', reference_name=pipeline_id)
    print(trigger_reference,"trigger_reference")

    adf_client.triggers.create_or_update(resource_group_name, data_factory_name, trigger_name, trigger_properties, trigger_reference)
    print("Trigger created successfully.")

except HttpResponseError as ex:
    print(f"Failed to create trigger: {ex.response.status_code}: {ex.message}")
except Exception as e:
    print(f"An unexpected error occurred: {str(e)}")`

**To Reproduce**
1. Install the mentioned packages
2. Run the shared code
3. the error would occur than

**Expected behavior**
Trigger creation in the respected subscription of Azure Data Factory

**Screenshots**

**Additional context**
I am trying to create Trigger using SDK for python on Azure Datafactory and while achieving this facing the issue.

**Comment by mccoyp** [comment]
Hi @pj250183, thank you for opening an issue. If I'm reading your code correctly, it looks like the exception is coming from the `except Exception as e:` portion. Is this nested under the `except HttpResponseError as ex:` block? i.e. Is this exception coming from an exception while trying to run
```Python
print(f"Failed to create trigger: {ex.response.status_code}: {ex.message}")
```
? If that's the case, have you tried exposing the HttpResponseError directly, without attempting to parse it manually?

If possible, it would be great if you can reformat your code into a Python code block so it's more clear.

I'll loop in someone who should be able to help further; we'll get back to you as soon as possible.

**Comment by ChenxiJiang333** [comment]
Hi @pj250183 
You have wrongly passed the parameter [pipeline](https://learn.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.models.tumblingwindowtrigger?view=azure-python#parameters) which should be an object instead of string. Please update the code as the sample below and try.
```
import trigger_config
from azure.identity import DefaultAzureCredential
from azure.mgmt.datafactory import DataFactoryManagementClient
from azure.mgmt.datafactory.models import TumblingWindowTrigger, TriggerPipelineReference, PipelineReference, TriggerResource
from azure.core.exceptions import HttpResponseError

subscription_id = trigger_config.SUBSCRIPTION_ID
resource_group_name = trigger_config.RESOURCE_GROUP
data_factory_name = trigger_config.DATA_FACTORY_NAME

trigger_name = 'test1'
pipeline_name = 'pipeline1'  

credential = DefaultAzureCredential()

adf_client = DataFactoryManagementClient(credential, subscription_id)

trigger_properties = TumblingWindowTrigger(
    pipeline=TriggerPipelineReference(pipeline_reference=PipelineReference(reference_name='pipeline1', type="PipelineReference")),
    frequency='Hour',
    interval=24,
    start_time='2024-02-08T07:00:00Z',
    delay='00:00:00',
    max_concurrency=1,
    retry_policy={'count': 3, 'intervalInSeconds': 60},
    depends_on=[]
)

try:
    trigger = TriggerResource(properties=trigger_properties)
    adf_client.triggers.create_or_update(resource_group_name, data_factory_name, trigger_name, trigger)
    print("Trigger created successfully.")
except HttpResponseError as ex:
    print(f"Failed to create trigger: {ex.response.status_code}: {ex.message}")
except Exception as e:
    print(f"An unexpected error occurred: {str(e)}")
```
