### ISSUE TITLE
Service bus messages intermittently taking a long time to send (~5 seconds) after upgrading to azure-core 1.26.3, azure-servicebus 7.11.4

### ISSUE THREAD

**Issue by sbfrancies-onyx** [Azure/azure-sdk-for-python#34243]
- **Package Name/Verision**: 
  azure-servicebus 1.26.3
  azure-core 7.11.4
  azure-identity 1.8.0

- **Operating System**:
  Linux (Azure App Service) Docker image (python:3.10-buster)

- **Python Version**: 
  3.10

**Describe the bug**
After upgrading the packages sending service bus messages to a topic is taking an inconsistent amount of time. It is usually a matter of milliseconds but can also take around 5 seconds every few dozens messages. This is causing performance issues in our system.

**To Reproduce**

Below is a simplified approximation of our code without the business logic:

```
from azure.servicebus import (
    ServiceBusClient,
    ServiceBusMessage,
    NEXT_AVAILABLE_SESSION,
)
from azure.servicebus.exceptions import OperationTimeoutError, SessionLockLostError
from azure.identity import DefaultAzureCredential
import logging


def example():
    namespace = "my-namespace"
    subscription_name = "my-subscription"
    receiver_topic_name = "my-receiver-topic"
    sender_topic_name = "my-sender-topic"

    with (
        ServiceBusClient(namespace, DefaultAzureCredential()) as client,
        client.get_topic_sender(sender_topic_name) as sender,
    ):
        while True:
            try:
                with client.get_subscription_receiver(
                    topic_name=receiver_topic_name,
                    subscription_name=subscription_name,
                    session_id=NEXT_AVAILABLE_SESSION,
                ) as receiver:
                    
                    fetch_messages = True

                    while True:
                        try:
                            received_messages = receiver.receive_messages(max_message_count=1, max_wait_time=5)
                            fetch_messages = len(received_messages) != 0


                            for received_message in received_messages:
                                sender.send_messages(
                                    ServiceBusMessage("""{0}, {1}""".format("Hello", "World"))
                                )  # PROBLEM IS WITH THIS CODE - LONG DELAYS

                                receiver.complete_message(received_message)
                        except SessionLockLostError:
                            logging.info("The session lock expired before the timeout period expired")
                            fetch_messages = False

            except OperationTimeoutError:
                logging.info("No session was assigned to subscription receiver")
```

**Expected behaviour**

Performance remains consistent following package upgrades.

**Additional context**
We use [message sessions](https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions) to lock messages into a certain ServiceBus subscription. Prior to completing one message from the subscription we send another message to another topic. We upgraded the service-bus package and now get long delays when sending messages. The delays are intermittent but often take around 5 seconds. As the topic is session locked, no other messages with the same session can be processed during this time.

We use [Azure Managed Identity](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) to authenticate communication between service bus and the python service (hosted in an Azure App Service for Linux Containers).

We had been running the code for sometime with no issues, we then pushed a change that only updated two of the azure packages:

_Before_
azure-core==1.23.0
azure-identity==1.8.0
azure-servicebus==7.8.2

_After_
azure-core==1.26.3
azure-identity==1.8.0
azure-servicebus==7.11.4

Note: The `azure-identity` package was not upgraded.

We have considered - and failing any other resolution - will attempt the following:

1. Upgrading the `azure-identity` package
2. Moving away from managed identity to connection string based authentication
3. Changing the lifetime of the `ServiceBusSender` so that a new one is instantiated for every receiver instance

These are all speculative though and since the packages are all compatible with each other it seems like there is a bug or instability somewhere. Our best guess is it relates to authentication as the upgraded service bus packages uses the new python based amqp library.

**Comment by kashifkhan** [comment]
Thank you for the detailed issue @sbfrancies-onyx. While I try to repro this on my side, can you provide me the following please:

* DEBUG logs with network level trace using the following snippet - `logging_enable` will also output frame level data and make it quite verbose, but this will help us see whats happening on your side.

```python
import logging
import sys

handler = logging.StreamHandler(stream=sys.stdout)
logger = logging.getLogger('azure.servicebus')
logger.setLevel(logging.DEBUG)
logger.addHandler(handler)

...

from azure.servicebus import ServiceBusClient

client = ServiceBusClient(..., logging_enable=True)
```
* Another thing to try as we narrow down where the problem might be is to switch back to the old AMQP library. This can be done using the following. We can see if going back to that solve the problem. This will be a short term mitigation as we want all customers to move on to the new library. 

```python
client = ServiceBusClient.from_connection_string(
    connection_str, uamqp_transport=True
)
```

**Comment by sbfrancies-onyx** [comment]
@kashifkhan thank you very much for the helpful suggestions. I have implemented the debug logging. Prior to that I thought I should update some other packages that were on older versions, so made the following changes:

azure-core 1.26.3 --> 1.30.0
azure-identity 1.8.0 --> 1.15.0
msal 1.17.0 --> 1.26.0 
msal-extensions 0.3.1 --> 1.1.0
typing_extensions 4.1.1 --> 4.9.0

Since making those changes I have not been able to replicate the issue with simple testing either locally or in a test environment. I am going to do more thorough testing tomorrow to properly simulate a production load but it is possible that the previous combination of packages is what led to the issue. I will update this issue when I know more.

**Comment by kashifkhan** [comment]
thats great @sbfrancies-onyx. Hopefully if something does happen the logs will help us out :)
