### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement azureml-dataprep-rslex&lt;1.1.0a,&gt;=1.0.0dev0 (from azureml-dataprep&lt;2.3.0a,&gt;=2.2.0a-&gt;azureml-dataset-runtime~=1.15.0-&gt;azureml-automl-core==1.15.0)

### ISSUE THREAD

**Issue by yeamusic21** [Azure/azure-sdk-for-python#34264]
- **Packages & Versions**: 
`dbutils.library.installPyPI("numpy", version="1.16.2")
dbutils.library.installPyPI("pandas", version="0.23.4")
dbutils.library.installPyPI("scikit-learn", version="0.20.3")
dbutils.library.installPyPI("lightgbm", version="3.0.0")

dbutils.library.installPyPI("azure-common", version="1.1.25") # previously 1.1.25
dbutils.library.installPyPI("azure-core", version="1.9.0") # previously 1.8.2
dbutils.library.installPyPI("azure-graphrbac", version="0.61.1")
dbutils.library.installPyPI("azure-identity", version="1.5.0") # previously 1.4.0
dbutils.library.installPyPI("azure-mgmt-authorization", version="0.61.0")
dbutils.library.installPyPI("azure-mgmt-containerregistry", version="2.8.0")
dbutils.library.installPyPI("azure-mgmt-keyvault", version="2.2.0")
dbutils.library.installPyPI("azure-mgmt-resource", version="10.2.0")
dbutils.library.installPyPI("azure-mgmt-storage", version="11.2.0")
dbutils.library.installPyPI("azureml-automl-core", version="1.15.0")
dbutils.library.installPyPI("azureml-automl-runtime", version="1.15.0")
dbutils.library.installPyPI("azureml-core", version="1.15.0")
dbutils.library.installPyPI("azureml-dataprep", version="2.2.3")
dbutils.library.installPyPI("azureml-dataprep-native", version="22.0.0")
dbutils.library.installPyPI("azureml-dataprep-rslex", version="1.0.1")
dbutils.library.installPyPI("azureml-dataset-runtime", version="1.15.0")
dbutils.library.installPyPI("azureml-defaults", version="1.15.0")
dbutils.library.installPyPI("azureml-explain-model", version="1.15.0")
dbutils.library.installPyPI("azureml-interpret", version="1.15.0")
dbutils.library.installPyPI("azureml-model-management-sdk", version="1.0.1b6.post1")
dbutils.library.installPyPI("azureml-pipeline", version="1.15.0")
dbutils.library.installPyPI("azureml-pipeline-core", version="1.15.0")
dbutils.library.installPyPI("azureml-pipeline-steps", version="1.15.0")
dbutils.library.installPyPI("azureml-sdk", version="1.15.0")
dbutils.library.installPyPI("azureml-telemetry", version="1.15.0")
dbutils.library.installPyPI("azureml-train", version="1.15.0")
dbutils.library.installPyPI("azureml-train-automl", version="1.15.0")
dbutils.library.installPyPI("azureml-train-automl-client", version="1.15.0.post1")
dbutils.library.installPyPI("azureml-train-automl-runtime", version="1.15.0")
dbutils.library.installPyPI("azureml-train-core", version="1.15.0")
dbutils.library.installPyPI("azureml-train-restclients-hyperdrive", version="1.15.0")

#dbutils.library.installPyPI("msrest", version="0.6.21") # https://github.com/Azure/azure-sdk-for-python/issues/24765
dbutils.library.installPyPI("msrest", version="0.6.19") # new

dbutils.library.restartPython()  # Removes Python state, but some libraries might not work without calling this function`

- **Operating System & Python Version**:
https://docs.databricks.com/en/archive/runtime-release-notes/7.3lts.html
Operating System: Ubuntu 18.04.5 LTS
Python: 3.7.5

**Describe the bug**
Following error is produced

`org.apache.spark.SparkException: Process List(/local_disk0/pythonVirtualEnvDirs/virtualEnv-2e6c0db9-dacd-45a8-b4f3-5a4c60103d40/bin/python, /local_disk0/pythonVirtualEnvDirs/virtualEnv-2e6c0db9-dacd-45a8-b4f3-5a4c60103d40/bin/pip, install, azureml-automl-core==1.15.0, --disable-pip-version-check) exited with code 1. ERROR: Could not find a version that satisfies the requirement azureml-dataprep-rslex&lt;1.1.0a,&gt;=1.0.0dev0 (from azureml-dataprep&lt;2.3.0a,&gt;=2.2.0a-&gt;azureml-dataset-runtime~=1.15.0-&gt;azureml-automl-core==1.15.0) (from versions: 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.13.0, 1.14.0, 1.15.1, 1.16.1, 1.17.0, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.19.1, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 2.0.0, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0, 2.7.1, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.10.0, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.11.4, 2.12.0, 2.12.1, 2.13.0, 2.14.0, 2.15.0, 2.15.1, 2.15.2, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.17.0, 2.17.1, 2.17.2, 2.17.5, 2.17.6, 2.17.7, 2.17.8, 2.17.9, 2.17.10, 2.17.11, 2.17.12, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.18.5, 2.18.6, 2.18.7, 2.19.0, 2.19.1, 2.19.2, 2.19.3, 2.19.5, 2.19.6, 2.19.7, 2.19.8, 2.20.0, 2.20.1, 2.21.0, 2.21.1, 2.22.0, 2.22.1, 2.22.2)`

On the following line

`dbutils.library.installPyPI("azureml-automl-core", version="1.15.0")`

**To Reproduce**
Run the following in a Databricks notebook on a Databricks cluster running 7.3 LTS runtime

`dbutils.library.installPyPI("numpy", version="1.16.2")
dbutils.library.installPyPI("pandas", version="0.23.4")
dbutils.library.installPyPI("scikit-learn", version="0.20.3")
dbutils.library.installPyPI("lightgbm", version="3.0.0")

dbutils.library.installPyPI("azure-common", version="1.1.25") # previously 1.1.25
dbutils.library.installPyPI("azure-core", version="1.9.0") # previously 1.8.2
dbutils.library.installPyPI("azure-graphrbac", version="0.61.1")
dbutils.library.installPyPI("azure-identity", version="1.5.0") # previously 1.4.0
dbutils.library.installPyPI("azure-mgmt-authorization", version="0.61.0")
dbutils.library.installPyPI("azure-mgmt-containerregistry", version="2.8.0")
dbutils.library.installPyPI("azure-mgmt-keyvault", version="2.2.0")
dbutils.library.installPyPI("azure-mgmt-resource", version="10.2.0")
dbutils.library.installPyPI("azure-mgmt-storage", version="11.2.0")
dbutils.library.installPyPI("azureml-automl-core", version="1.15.0")
dbutils.library.installPyPI("azureml-automl-runtime", version="1.15.0")
dbutils.library.installPyPI("azureml-core", version="1.15.0")
dbutils.library.installPyPI("azureml-dataprep", version="2.2.3")
dbutils.library.installPyPI("azureml-dataprep-native", version="22.0.0")
dbutils.library.installPyPI("azureml-dataprep-rslex", version="1.0.1")
dbutils.library.installPyPI("azureml-dataset-runtime", version="1.15.0")
dbutils.library.installPyPI("azureml-defaults", version="1.15.0")
dbutils.library.installPyPI("azureml-explain-model", version="1.15.0")
dbutils.library.installPyPI("azureml-interpret", version="1.15.0")
dbutils.library.installPyPI("azureml-model-management-sdk", version="1.0.1b6.post1")
dbutils.library.installPyPI("azureml-pipeline", version="1.15.0")
dbutils.library.installPyPI("azureml-pipeline-core", version="1.15.0")
dbutils.library.installPyPI("azureml-pipeline-steps", version="1.15.0")
dbutils.library.installPyPI("azureml-sdk", version="1.15.0")
dbutils.library.installPyPI("azureml-telemetry", version="1.15.0")
dbutils.library.installPyPI("azureml-train", version="1.15.0")
dbutils.library.installPyPI("azureml-train-automl", version="1.15.0")
dbutils.library.installPyPI("azureml-train-automl-client", version="1.15.0.post1")
dbutils.library.installPyPI("azureml-train-automl-runtime", version="1.15.0")
dbutils.library.installPyPI("azureml-train-core", version="1.15.0")
dbutils.library.installPyPI("azureml-train-restclients-hyperdrive", version="1.15.0")

#dbutils.library.installPyPI("msrest", version="0.6.21") # https://github.com/Azure/azure-sdk-for-python/issues/24765
dbutils.library.installPyPI("msrest", version="0.6.19") # new

dbutils.library.restartPython()  # Removes Python state, but some libraries might not work without calling this function` 

**Expected behavior**
Installs run without error

**Screenshots**
N/A

**Additional context**
This worked fine for months and only started erroring out today, 2/9/2024, during our 2am Eastern US Time, and has continued to error ever since.

**Comment by mccoyp** [comment]
Hi @yeamusic21, thank you for opening an issue. I'll tag some folks who can take a look; we'll get back to you as soon as possible.
cc @azureml-github

**Comment by yeamusic21** [comment]
It's been over a week I think now, any updates?

**Comment by mccoyp** [comment]
Hi @yeamusic21, thank you for your patience. @vivram, can you take a look?

**Comment by yeamusic21** [comment]
It's been over a month now, any updates?

_Note that since I opened this issue I waited for weeks, literally went on vacation, and upon my return the progress on this is still 0% :-(._

**Comment by sachinparyani** [comment]
@yeamusic21 Please move this line `dbutils.library.installPyPI("azureml-dataprep", version="2.2.3")` above  `dbutils.library.installPyPI("azureml-automl-core", version="1.15.0")` and remove `dbutils.library.installPyPI("azureml-dataprep-rslex", version="1.0.1")` and `dbutils.library.installPyPI("azureml-dataprep-native", version="22.0.0")` as installing `azureml-dataprep` will automatically install `azureml-dataprep-rslex` and `azureml-dataprep-native`.

Also, is there a specific reason you're trying to install versions from mid-2020? We would HIGHLY recommend installation of the latest versions of all the packages as there have been massive feature additions, perf improvements, bug fixes etc since 2020.

I work for the team that develops `azureml-dataprep` specifically and I know that the latest version (5.1.6) is in good shape. https://pypi.org/project/azureml-dataprep/#description

**Comment by yeamusic21** [comment]
All of these installs are in support of running an Azure AutoML model that we built in mid-2020.  Is it still your recommendation to upgrade azureml-dataprep to the latest version?  Wouldn't that cause errors when we go to run our model?

**Comment by yeamusic21** [comment]
Made the recommended changes and still getting error.

`pip, install, azureml-dataprep==2.2.3, --disable-pip-version-check) exited with code 1. ERROR: Could not find a version that satisfies the requirement azureml-dataprep-rslex&lt;1.1.0a,&gt;=1.0.0dev0 (from azureml-dataprep)`

**Comment by sachinparyani** [comment]
Technically, it shouldn't be a problem to upgrade to latest versions unless we have a major forward compatibility bug. If there is no harm in trying, I would do that.

I did manage to repro that bug that you're facing. Unfortunately, it does seem like we made some errors while releasing `azureml-dataprep` versions `2.2.2` - `2.6.6`. I'm sorry for that, but if you want to stick to a 2020 version, the nearest to `2.23` that aren't installation-faulty are `2.7.0` and `2.2.1`. Please give those a try, if you'd like.

But if I was in your place, I'd try the latest versions to see if everything works using those.

**Comment by yeamusic21** [comment]
“ Unfortunately, it does seem like we made some errors while releasing azureml-dataprep versions 2.2.2 - 2.6.6.”

Can you elaborate on this?

I’m still trying to understand how code / pip installs work fine without error (not one error) for 4 years, and then one day they completely fall apart and now consistently error out.  

The only explanation that makes sense to me is that changes were recently made to these old package versions?  Is that right?

**Comment by sachinparyani** [comment]
Good question. We had to delete older versions of our azureml-dataprep-rslex package on pypi because of max size limit. And this was a recent change (made last month).

**Comment by yeamusic21** [comment]
> Good question. We had to delete older versions of our azureml-dataprep-rslex package on pypi because of max size limit. And this was a recent change (made last month).

Thank you @sachinparyani, this response is extremely helpful, and without a doubt the most helpful made so far on this thread.

I will close this issue out with this comment.

A few concluding thoughts here:

1. I would like to note for the developers of the Azure SDK that it took roughly 11 comments and 1.5 months before the root cause of the issue was explained.  If the root cause had been explained, the solution and options would have been more clear from day 1.  Instead I waited a very long time to be given workarounds for an issue that was given no context.    
2. This is also not my first experience with Azure SDK working fine for months or years only for things to start failing out of the blue, see https://github.com/Azure/azure-sdk-for-python/issues/24765.  
3. I'd like to touch on the comment _"Also, is there a specific reason you're trying to install versions from mid-2020? We would HIGHLY recommend installation of the latest versions of all the packages as there have been massive feature additions, perf improvements, bug fixes etc since 2020._"  I agree that we all should stay up to date with the times... but the idea that if we don't rebuild our code every few years using the latest Azure SDK then our software is in jeopardy... this is not a lovely idea and it encourages me to stay away from services like Azure AutoML.

Thanks again :)
