### ISSUE TITLE
update support for openai > 1.0

### ISSUE THREAD

**Issue by franperezlopez** [Azure/azure-sdk-for-python#34279]
**Is your feature request related to a problem? Please describe.**
The library azure.ai.generative.synthetic.qa uses openai < 1.0, while most libraries migrated towards version > 1.0. Thus, for example, we can't use the current version of langchain with synthetic.qa

**Describe the solution you'd like**
Upgrade openai version > 1.0

**Comment by diondrapeck** [comment]
This issue is fixed as of version 1.0.0b6.

```
pip show azure-ai-generative 
Name: azure-ai-generative
Version: 1.0.0b6

pip show openai
Name: openai
Version: 1.11.1
```
