### ISSUE TITLE
Unable to query Trigger connection parameters from Keyvault - Azure functions v2 - Linux docker container

### ISSUE THREAD

**Issue by sudharsan2020** [Azure/azure-sdk-for-python#34278]
- **Package Name**: azure-functions
- **Package Version**: 1.18.0
- **Operating System**:Linux
- **Python Version**: 3.11

**Describe the bug**
I am using the Service Bus trigger for my application.
To load the Service Bus trigger connection string, currently, we rely on the Docker environment variable, which is dynamically set when the Azure pipeline is triggered

**Code**
```
@app.service_bus_topic_trigger(
    arg_name="azservicebus",
    subscription_name="mysubscription",
    topic_name="mysbtopic",
    connection="ServiceBusConnectionString",
)
def servicebus_topic_trigger(azservicebus: func.ServiceBusMessage):
    logging.info(
        "Python ServiceBus Topic trigger processed a message: %s",
        azservicebus.get_body().decode("utf-8"),
    )
```

The `ServiceBusConnectionString` is referred as a `Docker environment variable` in the Dockerfile as below:
```
FROM mcr.microsoft.com/azure-functions/python:4-python3.11


ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureWebJobsFeatureFlags=EnableWorkerIndexing \
    PYTHON_ENABLE_DEBUG_LOGGING=1 \
    FUNCTIONS_WORKER_RUNTIME=python \
    ServiceBusConnectionString=#{MyOrg--ServiceBus--ConnectionString}#
```

**To Reproduce**
1. However when I tried to read from Keyvault, the function app wasn't starting. **Note: Key vault secrets are loaded at start of the function app**   
```
@app.service_bus_topic_trigger(
    arg_name="azservicebus",
    subscription_name="mysubscription",
    topic_name="mysbtopic",
    connection="MyOrg--ServiceBus--ConnectionString",
)
def servicebus_topic_trigger(azservicebus: func.ServiceBusMessage):
    logging.info(
        "Python ServiceBus Topic trigger processed a message: %s",
        azservicebus.get_body().decode("utf-8"),
    )
```
2. I am getting the below error stating 
```
The listener for function 'Functions.service_bus_topic_trigger' was unable to start. Microsoft.Azure.WebJobs.Extensions.ServiceBus: Service Bus account connection string 'MyOrg--ServiceBus--ConnectionString' does not exist. Make sure that it is a defined App Setting
```
3. The official documentation says the `connection` points to an environment variable that contains the **Service Bus connection string**. https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-python#connections

**Expected behavior**
**The Service bus trigger connection string should be successfully loaded from Azure Key vault upon function app startup**

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/9370130/8ce7dcfd-8418-4fd5-a8a0-38daeab0e514)

**Additional context**
The Azure function app V2 is deployed through AKS as Docker containers.

**Comment by pvaneck** [comment]
Hey, @sudharsan2020. Azure Functions triggers aren't maintained in this repo, but instead [here](https://github.com/Azure/azure-functions-python-library). Can try there, or you might also have better luck posting here: https://learn.microsoft.com/en-us/answers/questions/

I'm not too familiar with functions, but is `MyOrg--ServiceBus--ConnectionString` the name of the environment variable? Seems like `ServiceBusConnectionString` is the name, but it's trying to look up the supposed value.

**Comment by deepak-thanapal** [comment]
Hey @pvaneck , we are trying to load `MyOrg--ServiceBus--ConnectionString` from a secure space but the function app is getting booted up even before we try to load it.

**Comment by lmazuel** [comment]
Hi @deepak-thanapal , as @pvaneck is saying, we do not own Azure Function, please create a support ticket, or report to https://github.com/Azure/azure-functions-python-library as there is nothing we can do here.

Thank you
