### ISSUE TITLE
Call to /metadata/instance/compute failed

### ISSUE THREAD

**Issue by yli02** [Azure/azure-sdk-for-python#34303]
- **Package Name**: azure.monitor.opentelemetry.exporter
- **Package Version**: 1.0.0b22
- **Operating System**: Debian
- **Python Version**: 3.8

**Describe the bug**
There is a call to [metadata/instance/compute](http://169.254.169.254/metadata/instance/compute?api-version=2021-12-13&format=json) even though `APPLICATIONINSIGHTS_STATSBEAT_DISABLED_ALL` has been set to "true".

![image](https://github.com/Azure/azure-sdk-for-python/assets/141815872/705e44a5-5676-48be-b0f1-e66ed80bbb0b)

The following traceback info is shown in call stack
```bash
Traceback (most recent call last):
  File "/app/.venv/lib/python3.8/site-packages/opentelemetry/trace/__init__.py", line 573, in use_span
    yield span
  File "/app/.venv/lib/python3.8/site-packages/opentelemetry/sdk/trace/__init__.py", line 1046, in start_as_current_span
    yield span_context
  File "/app/.venv/lib/python3.8/site-packages/opentelemetry/instrumentation/urllib/__init__.py", line 274, in _instrumented_open_call
    raise exception.with_traceback(exception.__traceback__)
  File "/app/.venv/lib/python3.8/site-packages/opentelemetry/instrumentation/urllib/__init__.py", line 244, in _instrumented_open_call
    result = call_wrapped()  # *** PROCEED
  File "/app/.venv/lib/python3.8/site-packages/opentelemetry/instrumentation/urllib/__init__.py", line 200, in call_wrapped
    return opener_open(opener, request_, data=data, timeout=timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**To Reproduce**
You could use the following script to reproduce the issue, and have the `APPLICATIONINSIGHTS_STATSBEAT_DISABLED_ALL` to be "true".

```python
import asyncio
import os
from azure.monitor.opentelemetry import configure_azure_monitor
from opentelemetry import metrics
from opentelemetry.metrics import (
    CallbackOptions, Observation
)
from opentelemetry.sdk.metrics import Counter, MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from azure.monitor.opentelemetry.exporter import AzureMonitorMetricExporter


def setup_azure_monitor():
    """Setup Azure Monitor for OpenTelemetry.
    """
    conn_str = os.environ.get("APPLICATIONINSIGHTS_CONNECTION_STRING")
    statsbeat = os.environ.get("APPLICATIONINSIGHTS_STATSBEAT_DISABLED_ALL")

    print(f'connect_str: {conn_str}')
    print(f'Is statsbeat disabled: {statsbeat}')

    configure_azure_monitor(
        connection_string=conn_str,
        disable_offline_storage=True,
    )


    az_metrics_exporter = AzureMonitorMetricExporter(
        connection_string=conn_str,
        disable_offline_storage=True
    )
    metrics_reader = PeriodicExportingMetricReader(
        exporter=az_metrics_exporter,
        export_timeout_millis=60
    )
    metrics.set_meter_provider(
        meter_provider=MeterProvider(
            metric_readers=[metrics_reader]
        )
    )

    meter = metrics.get_meter_provider().get_meter(
        "DummyService"
    )
    produce_msg_counter = meter.create_counter(
        "ProducedMessages"
    )
    consume_msg_counter = meter.create_counter(
        "ConsumedMessages"
    )


    asyncio.get_event_loop().run_until_complete(asyncio.sleep(300))


if __name__ == "__main__":
    setup_azure_monitor()
```

**Expected behavior**
1. If `APPLICATIONINSIGHTS_STATSBEAT_DISABLED_ALL` is set to "true", then there should no above request
2. If `APPLICATIONINSIGHTS_STATSBEAT_DISABLED_ALL` is not set to "true", then the request should not fail

**Screenshots**

**Additional context**

**Comment by pvaneck** [comment]
Hey, thanks for the feedback. I'll tag some people, and we'll investigate as soon as possible.

**Comment by yli02** [comment]
Hi @jeremydvoss and @lzchen, the failed requests seem caused by the metrics export part.

**Comment by yli02** [comment]
Hi @jeremydvoss and @lzchen, it seems that my bug description was not correct, the issue seems not really related to statsbeat, I tried to check the error traces

![image](https://github.com/Azure/azure-sdk-for-python/assets/141815872/e90d6fba-44ae-4d12-af6c-fb704c09e029)

![image](https://github.com/Azure/azure-sdk-for-python/assets/141815872/ff2b949a-c4ef-41c8-a61b-c1f03afe26a5)

![image](https://github.com/Azure/azure-sdk-for-python/assets/141815872/bc80196f-d606-4ebd-a849-9beaec8fe23f)

![image](https://github.com/Azure/azure-sdk-for-python/assets/141815872/1b7cb9fc-f393-4e55-b0c1-7aa52aa35a70)

**Comment by lzchen** [comment]
@jeremydvoss 

I think we simply need to add the SUPPRESS_INSTRUMENTATION context key before request call so urllib instrumentation does not pick this up.

**Comment by lzchen** [comment]
Tracking issue: https://github.com/open-telemetry/opentelemetry-python/issues/3684

**Comment by lzchen** [comment]
Tracking issue: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2179

**Comment by lzchen** [comment]
@yli02 

Also on a side note, it is not recommended to use the exporters alongside the azure monitor distro. You should EITHER use `configure_azure_monitor()` (distro) or `AzureMonitorXExporter()` (exporters) but not BOTH since the distro instantiates these underneath the api.

**Comment by yli02** [comment]
@lzchen thanks for your suggestion, I adapted my code accordingly.
