### ISSUE TITLE
Change PartitionKeyType from List to Sequence?

### ISSUE THREAD

**Issue by trevorcreech** [Azure/azure-sdk-for-python#34313]
**Describe the bug**
First off, thanks for all the typing you all have added!

Our partition_keys are always strings so we'd like our internal methods to have type `Union[str, list[str], None]`, but that's not compatible with the [PartitionKeyType](https://github.com/Azure/azure-sdk-for-python/blob/e8f06862f5fd3f8db7019010eb99304534ec595f/sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py#L57) in the SDK because lists are mutable

[GitHub issue with explanation](https://github.com/python/mypy/issues/3351) of why `list[str]` isn't compatible with e.g. `list[str | int]`

Assuming these functions never modify the partition_keys that are passed in, so could we change that type from List to Sequence?

**To Reproduce**
[mypy playground: List failure case](https://mypy-play.net/?mypy=latest&python=3.12&gist=9956fbb4efd12a218bb51619c213c514)
[mypy playground: Sequence success case](https://mypy-play.net/?mypy=latest&python=3.12&gist=d7dcd7d6637790b1488409fc579f0b65)

**Expected behavior**
Users of the sdk can restrict their partition key types to a stricter subset

**Comment by annatisch** [comment]
This is a great catch @trevorcreech - thank you for the report!
I believe your assumption is correct - @simorenoh are you able to confirm whether the partitionkey value is ever modified prior to the request being sent? If not, I think this should be a good change to make. I can update my [existing paritionkey typing PR](https://github.com/Azure/azure-sdk-for-python/pull/34306)

**Comment by annatisch** [comment]
Ping @bambriz and @simorenoh on this one.

**Comment by bambriz** [comment]
@annatisch I think it would be a goof change, there shouldn't be any changes to the partition key values as it gets sent. It also wouldn't matter if the values are passed in a list or a tuple (in regard to subpartitioning pk values) as it will be the same for the json request headers.

**Comment by annatisch** [comment]
Done :)
Thanks @trevorcreech! This will go out in the next release.
