### ISSUE TITLE
Get StorageManagementClient private_endpoint_connections fails in USGov cloud

### ISSUE THREAD

**Issue by sudapudi** [Azure/azure-sdk-for-python#34347]
- **Package Name**: azure-mgmt-storage
- **Package Version**: 21.1.0
- **Operating System**: image name = adm-ubuntu-1804-l  version = v30
- **Python Version**:  3.8

**Describe the bug**
Get a private endpoint connection to a storage account (from synapse) and approve it. We are providing the appropriate management url for gov cloud in the ctor "management.usgovcloudapi.net/".  We get the below error of a mismatched in access token type. 

Code: InvalidAuthenticationTokenAudience
2024-01-28 09:11:16.428112: Message: The access token has been obtained for wrong audience or resource ' https://management.azure.com/ '. It should exactly match with one of the allowed audiences ' https://management.core.usgovcloudapi.net/ ',' https://management.core.usgovcloudapi.net/ ',' https://management.usgovcloudapi.net/ ',' https://management.usgovcloudapi.net/ '.

**To Reproduce**
class PrivateEndpointManager:
    """
    Handle the approval of private endpoint between Synapse and Storage Account.
    """
    def __init__(self) -> None:
        self.env_vars = EnvVarsInitializer()
        self.storage_account_name = os.environ["StorageAccountName"]
        self.logger = get_logger()
        self.client: StorageManagementClient = self.init_mgmt_client()

    def get_credentials(self) -> ClientSecretCredential:
        client_secret_cred = ClientSecretCredential(
            tenant_id=self.env_vars.tenant_id,
            client_id=self.env_vars.vault_app_id,
            client_secret=self.env_vars.vault_app_key,
        )
        return client_secret_cred

    def init_mgmt_client(self) -> StorageManagementClient:
        mgmt_url = f"https://{self.env_vars.managementUrl}" # gov cloud this is "management.usgovcloudapi.net/"
        client_secret_cred = self.get_credentials()

        self.logger.info("Creating storage mgmt client")
        storage_mgmt_client = StorageManagementClient(
            credential=client_secret_cred,
            subscription_id=self.env_vars.sub_id,
            base_url=mgmt_url
        )
        self.logger.info("Successfully created storage mgmt client")
        return storage_mgmt_client

    def get_synapse_private_endpoint(self) -> PrivateEndpointConnection:
        self.logger.info("Getting private endpoint for Synapse workspace")
        existing_endpoints = self.client.private_endpoint_connections.list(
            resource_group_name=self.env_vars.rg_name,
            account_name=self.storage_account_name
        )
        for private_ep in existing_endpoints:
            # work only on the endpoint associated with the Synapse workspace
            if self.env_vars.ws_name in private_ep.private_endpoint.id:
                self.logger.info(f"Synapse private endpoint: {private_ep.private_endpoint.id}")
                return private_ep

        # if no matching endpoint was returned, raise an exception
        msg = "No private endpoint found for Synapse"
        self.logger.error(msg)
        if not self.env_vars.using_resilient_release:
            raise ValueError(msg)

def main() -> None:
    private_endpoint_manager = PrivateEndpointManager()
    private_endpoint_manager.get_synapse_private_endpoint()

**Expected behavior**
Print either of the above log messages.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/159577909/f06c5c87-3286-4ef2-81da-81f28d97df78)

**Additional context**
Code is at https://microsoft.visualstudio.com/WDATP/_git/MD.System.DataPlatform.Synapse?path=/EV2DeploymentSynapse/Scripts/ApproveSynapsePEConnection.py
Our env variables are 
            self.loginUrl = "login.microsoftonline.us"
            self.managementUrl = "management.usgovcloudapi.net/"
            self.blobSuffixUri = ".blob.core.usgovcloudapi.net"
            self.synapseEndpointUrl = "https://web.azuresynapse.usgovcloudapi.net"
            self.synapseDevEndpointSuffixUri = "dev.azuresynapse.usgovcloudapi.net"

EV2 https://ev2portal.azure.net/#/Rollout/WDATP.Infra.Timna/bb8e5ba2-2836-4beb-84c4-deec33f13e8a?RolloutInfra=Fairfax

**Comment by pvaneck** [comment]
Hey, @sudapudi. Here is the current guidance for interacting with non-public clouds with our SDKs: https://learn.microsoft.com/azure/developer/python/sdk/azure-sdk-sovereign-domain

Can you try the following:


1. Set the authority in the credential:

```python
from azure.identity import AzureAuthorityHosts

authority = AzureAuthorityHosts.AZURE_GOVERNMENT
client_secret_cred = ClientSecretCredential(
    tenant_id=self.env_vars.tenant_id,
    client_id=self.env_vars.vault_app_id,
    client_secret=self.env_vars.vault_app_key,
    authority=authority
)
```

  This can also be done without code changes via environment variable by setting `AZURE_AUTHORTY_HOST="login.microsoftonline.us"`

2. Set the credential scope in the client:

```python
storage_mgmt_client = StorageManagementClient(
    credential=client_secret_cred,
    subscription_id=self.env_vars.sub_id,
    base_url=mgmt_url,
    credential_scopes=[mgmt_url + ".default"]
)
```

Hopefully these changes should get it working.

**Comment by sudapudi** [comment]
We are working on trying out the recommended options.

Shweta
________________________________

**Comment by sudapudi** [comment]
The solution above worked. Thank you.
