### ISSUE TITLE
PostgresSQLManagementClient operations  begin_delete() : LROPoller result() wrongly returns end of operation 

### ISSUE THREAD

**Issue by stockersky** [Azure/azure-sdk-for-python#34351]
- **Package Name**: azure-mgmt-rdbms
- **Package Version**: 10.1.0
- **Operating System**: Windows 10
- **Python Version**: 3.12.1

**Describe the bug**
I have a script that delete a PostgreSQL Flexible Server & then recreate it from another Server.
Kind of a "refresh" operation to bring fresh data to staging environments.

The problem : while the LROPoller indicates the 'begin_delete()' operation has ended (`result()`), I cannot immediately recreate a Server with the same name. I'd have to pause for more than 5 minutes to be able to recreate a Server with the same name.
I can clearly see in the Azure UI Console that the Server has gone. But it sounds like you cannot immediately recreate a Server with the same name.

Exception is not very helping : 
```
azure.core.exceptions.HttpResponseError: (InternalServerError) An unexpected error occured while processing the request. Tracking ID: 'xxxxxxx'
```

In the Monitor Activity log, the error message associated with the "Update PostgreSQL server Create" is :
**Error code** : `ResourceOperationFailure`
**Message** : `The resource operation completed with terminal provisioning state 'failed'`

**However, if I give my script some `sleep()` in between the `begin_delete()` and `begin_create()` operations, this works well.**
See following snippet.

**To Reproduce**

A snippet:

```
client = PostgreSQLManagementClient(....)

print("Delete PosgreSQL Server")
poller_delete = client.servers.begin_delete(....)
print("Wait for operation to process...")
result = poller_delete.result()
print("Done Deleting Server")

# time.sleep 300    # this would - very probably work - if I pause in between the two operations

print("Create PosgreSQL Server")
poller_create = client.servers.begin_create(....)
print("Wait for operation to process...")
result = poller_create.result()
print("Done creating Server")
```

Without pausing a reasonable time (7 minutes is usually safe), it'd throw the aforementioned Exception. 

**Expected behavior**
When the LROPoller indicates that the Server delete operation has ended, I should be able to recreate the Server.
It sounds like the Azure internal infrastructure hasn't yet ended to completely delete the resources.

**Comment by ChenxiJiang333** [comment]
Hi, @stockersky. 
The `result()` function would return the result of a long operation, but it doesn't mean the operation has ended, it's still on process on portal. So yes, you may need to manually set a pause between two operations to avoid some conflicts. 

Or you can add a callback by using [
add_done_callback()](https://learn.microsoft.com/en-us/python/api/azure-core/azure.core.polling.lropoller?view=azure-python#azure-core-polling-lropoller-add-done-callback) to receive notifications once the operation is done, see the sample below:
```
def create_server(args):
    print("Done Deleting Server")

def main():
    client = PostgreSQLManagementClient(...)
    poller_delete = client.servers.begin_delete(...)
    print("Wait for operation to process...")
    poller_delete.add_done_callback(func=create_server)
```
