### ISSUE TITLE
Hang on client.list_configuration_settings iterator 

### ISSUE THREAD

**Issue by ingie** [Azure/azure-sdk-for-python#34372]
- **azure.appconfiguration (azure-appconfiguration-provider)**: 
- **Package Version 1.1.0**: 
- **Ubuntu Kernel 5.15 [Mint 21.13] and also MacOS 10.15 + Homebrew**:
- **Python 3.9.13**: 

**Describe the bug**
Hang on request to client get_configuration_setting or client list_configuration_settings iterator, or get_configuration_setting, seemingly when resource is being throttled, but no actual throttling error is raised. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a throttled App Configuration resource. ( my situation specifically is I'm bouncing on my limit, but now trying to employ back-off code as I'm not trying to hit it hard - it's a personal home device app -not a _hungry_ app in any performant or service need sense, but I'd been restarting it for other debugging reasons, which had been refreshing its local config each time, and I hadn't noticed it creep up to the limit, arguably I should use more specific key wildcards to iterate and it would let me last longer without throttling, but that's by the by as there's only 4 of them i need each restart :) ... but aaanyway )

2. Request a list of of configuration settings, and then try to iterate over those (azure.core.paging.ItemPaged) with their keys
```
# e.g.
settings = client.list_configuration_settings("FOO_*")
for setting in settings: # this iterator will seem to "hang" if throttled
    print("Here", flush=True)
    print(setting.key)
```
3. (seemingly) If resource is recently throttled, 5min+ hang (minimum - tho I've had it sit there for 10 mins+ on occasion) occurs as the azure paging next iterator is called (i.e. we never reach the print "Here" line) - Ctrl-C-ing reveals it being hung in the azure lib's own backing-off loop under core pipeline . 

**Expected behaviour**
Either: Key values returned, or: Exception thrown that resource is being throttled [and therefore to signal backoff] 

The above is perhaps "Working as intended", but I'd consider that by _not_ flagging to the caller that backing off is being done/should have been done (and therefore just hanging the calling code in a secret wait loop) isn't a perfect solution. 

So perhaps, a 'retry_after" property and an "is_throttled()" method need adding to the AzureAppConfigurationClient and the iterator, so that this can be expected in caller code, and so it can pre-emptively back off or throw/return a failure.
```
# e.g. to allow a calling loop something morelike
client = AzureAppConfigurationClient.from_connection_string(CS)

# pre-empt throttling and don't even try getting settings for a while
if client.is_throttled():
  print("Throttled until", client.retry_after)
  ...
  return (None, client.retry_after)

# we weren't definitely throttled above, but by now, we might be throttled all the same...
settings = client.list_configuration_settings("FOO_*")
for setting in settings:
    # ...so if that iterator _was_ throttled at the time of each next(), lets not try and force the issue
    if setting.is_throttled():
        print("**WARNING ** Resource is throttled sleeping suggested backoff: ", setting.retry_after)
        time.sleep(setting.retry_after)
    ...
```

This would _allow the current protective internal-to-the-azure-package backoff system to continue as it currently does_ (i.e. backing off internally within the iterator paging - and still "hanging" in the way I experience), whilst additionally providing a reason for any hang, and so better resilience and knowledge of it being likely to happen, or having just happened, to the caller.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by swathipil** [comment]
Hi @ingie - thanks for opening an issue. Tagging the right people to take a look.

**Comment by YalinLi0312** [comment]
Hi @ingie -
*  our SDK is retrying as configured in retry policy, it is sleeping based on the `Retry_after` value in response.
*  adding "is_throttled()" method is a feature request that we need to evaluate. @mrm9084 do you/your team know is there anyway to detect if the resource is throttled?

**Comment by mrm9084** [comment]
@YalinLi0312, best way to know this is in the portal I would think. We have a doc on it. See https://learn.microsoft.com/azure/azure-app-configuration/faq#are-there-any-limits-on-the-number-of-requests-made-to-app-configuration, and the linked doc.

**Comment by YalinLi0312** [comment]
Hi @ingie ,  since there's request limits to App Config, did you follow the link and try to reduce requests as recommended?
