### ISSUE TITLE
Unauthorized Operation Error Using Azure Python SDK Despite Owner Permissions

### ISSUE THREAD

**Issue by tomershukhman** [Azure/azure-sdk-for-python#34371]
- **Package Name**:  azure.identity
- **Package Version**: 1.15.0
- **Operating System**:  14.2.1 (23C71)
- **Python Version**:  3.9
- **Azure Cli Version**:  2.56

**Describe the bug**
I am encountering an "Unauthorized Operation" error when attempting to perform operations using the Azure Python SDK. This issue arises despite having logged in with the Azure CLI (az login) and confirming that all permissions appear correctly set, with my account being the owner of the Azure project.
The error I am getting is:
`azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.`

**To Reproduce**

1. Log in using Azure CLI with the command az login.
2. Run a Python script using DefaultAzureCredential and try to upload a file

**Expected behavior**
The Script should use the CLI credentials and therefor be allowed to preform any action that the role premits.

**code**
```
from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient

import os

static_config = {
    "AZURE_STORAGE_ACCOUNT_NAME": "tomerstatic",
    "AZURE_STORAGE_CONTAINER_NAME": "$web"
}


class AzureProvider:
    def __init__(self, config):
        self.config = config
        self.blob_service_client = self._create_client()

    def _create_client(self):
        print("Creating BlobServiceClient")
        account_url = f"https://{self.config['AZURE_STORAGE_ACCOUNT_NAME']}.blob.core.windows.net"
        print(f"Account URL: {account_url}")

        default_credential = DefaultAzureCredential()
        return BlobServiceClient(account_url, credential=default_credential)

    def upload_file(self, local_file_path, upload_file_path):
        blob_client = self.blob_service_client.get_blob_client(container=self.config["AZURE_STORAGE_CONTAINER_NAME"],
                                                               blob=upload_file_path)

        print("\nUploading to Azure Storage as blob:\n\t" + local_file_path)

        # Upload the created file
        with open(file=local_file_path, mode="rb") as data:
            blob_client.upload_blob(data)


azureProvider = AzureProvider(static_config)
azureProvider.upload_file("output1.txt", "test.txt")
```

**Comment by spcnz** [comment]
I have the same issue

**Comment by swathipil** [comment]
Hi @tomershukhman - thanks for opening an issue. We'll investigate and get back to you asap!

**Comment by pvaneck** [comment]
A few other things to check:

Does uploading from the CLI directly work for you?
```bash
az storage blob upload -f ./output1.txt -c <container_name> -n test.txt --account-name <storage_account_name>
```

If not, then it likely is some type of permission/role issue.

If so, then `DefaultAzureCredential` might be trying a different credential in the credential chain and not using `AzureCliCredential` underneath. Do you happen to have any Azure-related environment credentials set (AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, etc)?

**Comment by tomershukhman** [comment]
@pvaneck is yes using az cli works

**Comment by jalauzon-msft** [comment]
Hi @tomershukhman, as Paul mentioned, `DefaultAzureCredential` will try a long series of credentials and they happen in order, until one is found. The list of credential types in order can be seen [here](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python). So, if any credential listed before Azure CLI is found in your environment, DefaultAzureCredential will use that and not CLI. Please ensure that Azure CLI is the credential being chosen.

If you want to force Azure CLI credential, you can try using [AzureCliCredential](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.azureclicredential?view=azure-python).
