### ISSUE TITLE
Incorrect error message in exception handler in async_samples

### ISSUE THREAD

**Issue by patheikkinen** [Azure/azure-sdk-for-python#34393]
See here:

https://github.com/Azure/azure-sdk-for-python/blob/3a27963083ed2f520f603efe225911972fa7e53a/sdk/eventhub/azure-eventhub/samples/async_samples/iot_hub_connection_string_receive_async.py#L99

Isn't there an extra word "not" that shouldn't be there?

**Comment by kashifkhan** [comment]
Thank you for the feedback @patheikkinen . That is indeed an extra "not" in there :) .. will get this patched up
