### ISSUE TITLE
Create or update certificate returns error azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Accepted'

### ISSUE THREAD

**Issue by Hasanofal** [Azure/azure-sdk-for-python#34395]
### Type of issue

Code doesn't work

### Description

When using the python sdk to create a certificate, I get error: Operation returned an invalid status 'Accepted'.

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2023_01_01.operations.certificatesoperations?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-web/azure.mgmt.web.v2023_01_01.operations.CertificatesOperations.yml

### Document Version Independent Id

284b2cde-1df5-768a-2abf-6507c5632b26

### Article author

@lmazuel

### Metadata

* ID: c5c81a2f-9b05-479c-e3f5-06757121cfad 
* Service: **app-service**
* Sub-service: **web-apps**

**Comment by swathipil** [comment]
Hi @Hasanofal - thanks for opening an issue. Tagging the right people to take a look. In the meantime, would you be able to provide the following info?
* A sample to reproduce this issue.
* Confirm whether you are using `azure-mgmt-web` v7.2.0.

**Comment by msyyc** [comment]
Could you provide more detailed code about how to reproduce the error?

**Comment by Hasanofal** [comment]
Hi, thanks for your reply

1. yes I'm using azure-mgmt-web 7.2.0

2. To reproduce the issue, first I have to add the correct A/CNAME and TXT records to my domain provider. Next, I create a host name binding. Then I create the certificate using the custom domain. The error only happens when creating a certificate and not when updating it. After getting the invalid status error, Azure still creates the certificate even though I got the error. So if I run it a second time after a few minutes, I won't get the error as the certificate will have been created already and it will only update it. Make sure all domain records are added to the domain provider so you don't get validation error.
`
from azure.identity import DefaultAzureCredential
from azure.mgmt.web import WebSiteManagementClient

credential = DefaultAzureCredential()
app_service_client = WebSiteManagementClient(
            credential, subscription_id
        )
app_service_client.web_apps.create_or_update_host_name_binding(
                RESOURCE_GROUP_NAME,
                web_app_name,
                custom_domain,
                {}
            )
app_service_client.certificates.create_or_update(
                RESOURCE_GROUP_NAME,
                "certificate_name",
                {
                    "location": "uaenorth",
                    "canonicalName": custom_domain,
                    "serverFarmId": web_app_plan_id,
                },
            )
`

**Comment by ChenxiJiang333** [comment]
according to the swagger definition [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2023-01-01/Certificates.json#L189), response with status code except 200 would be considered as a failure, please follow this issue for updated news: https://github.com/Azure/azure-rest-api-specs/issues/27962.

**Comment by xiangyan99** [comment]
Closing the issue and please use https://github.com/Azure/azure-rest-api-specs/issues/27962 to track.
