### ISSUE TITLE
ServiceManagementService.get_operation_status should accept AsynchronousOperationResult

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#344]
It's not really obvious that you need to pass the attribute of `op` in this code:

```python
op = sms.create_virtual_machine_deployment(**args)
sms.wait_for_operation_status(op.request_id)
```

Should be easy enough to support just passing `op` in this case, or even making `AsynchronousOperationResult` behave more like a future with `.wait()` and maybe `.add_done_callback()` (with some thread-based implementation behind it).

**Comment by lmazuel** [comment]
I don't think we will do it in the legacy code now.
In the latest 2.0.0 version, async methods returns an [AzureOperationPoller](http://msrestazure.readthedocs.org/en/msrestdoc/msrestazure.html#msrestazure.azure_operation.AzureOperationPoller) instance with the [.wait()](http://msrestazure.readthedocs.org/en/msrestdoc/msrestazure.html#msrestazure.azure_operation.AzureOperationPoller.wait) and the [.add_done_callback()](http://msrestazure.readthedocs.org/en/msrestdoc/msrestazure.html#msrestazure.azure_operation.AzureOperationPoller.add_done_callback) methods.
