### ISSUE TITLE
Azure SDK V2-Time duration setup for target data

### ISSUE THREAD

**Issue by ukhan67** [Azure/azure-sdk-for-python#34414]
**Package Name: azure-ai-ml Azure SDK V2
Package Version: 1.12.1:
Operating System: Linux, running it on azure notebooks on Azure portal.:
Python Version: 3.10:**

**Describe the bug**
Unable to set duration for target data properly. For instance, let's say we are setting up drift monitor on 30th of Jan and we set up target data range as "P10D", so ideally it should pick data from 20th of Jan to 30th of Jan but instead it looks for the data between 10th of Jan to 20th of Jan which should not be the case given that we are interested in last 10 days of data. Document does not show how to setup time duration as of now. [https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.productiondata?view=azure-python](url)

**To Reproduce**
1. Setup a monitor with ProductionData having parameter data_window_size setup as P10D.

**Expected behavior**
To have last 10 days as target data window duration.

**Comment by swathipil** [comment]
Hi @ukhan67 - Tagging the right people. Is this issue among the multiple errors you mentioned in #34413?
cc/ @azureml-github

**Comment by nemanjarajic** [comment]
Hi @ukhan67, thank you for bringing this issue up! I believe this has to do with the default data window offset for the production data. Next release 1.14.0 will have a fix for this in which you can specify the offset for the production data.

**Comment by nemanjarajic** [comment]
Release 1.14.0 is in the process of being finalized and release 3/11/2024. This should resolve the issue.
