### ISSUE TITLE
Azure SDK V2-Data Drift Signal Monitor error when entire column contains same integer value

### ISSUE THREAD

**Issue by ukhan67** [Azure/azure-sdk-for-python#34416]
**Package Name: azure-ai-ml Azure SDK V2
Package Version: 1.12.1
Operating System: Linux, running it on azure notebooks on Azure portal.:
Python Version: 3.10**

**Describe the bug**
One column containing single integer value eg. [20, 20, 20, 20] cause an error 
**float() argument must be a string or a real number, not 'NoneType'** on Model_Monitor_Output_Metrics component. if converted to float [20.0, 20.0, 20.0] then it works.

Follow up error
Upon fixation of above error. another error starts to appear. **Cannot set multiple terminal states for a run** i.e. related to mlflow error. Monitor name with the error is no longer useable.

**To Reproduce**
1. Create Drift monitor with one integer column that contains same integer values.[20, 20, 20]

**Expected behavior**
To get executed with out **float() argument must be a string or a real number, not 'NoneType** error
once converted to float [20.0, 20.0, 20.0]. It should setup mlflow accordingly **Cannot set multiple terminal states for a run**

**Screenshots**
![Screenshot 2024-02-09 113005](https://github.com/Azure/azure-sdk-for-python/assets/103506988/d23b629b-ed1f-4c45-8f0f-5cd49568e46e)
![Screenshot 2024-02-09 153338](https://github.com/Azure/azure-sdk-for-python/assets/103506988/a9ed5b5c-798b-4a7d-a388-152832dbe92b)

**Comment by yunjie-hub** [comment]
Thanks for reporting this issue, could you please share more information about the input dataset (regarding "One column containing single integer value eg. [20, 20, 20, 20] cause an error")? If possible could you share your sample input datasets and the settings of your monitor so that we can repro the issue from our side

**Comment by nemanjarajic** [comment]
Closing this issue as there has been no response for the past 2 weeks.
