### ISSUE TITLE
Data Drift Signal Monitor error on single value in an integer column

### ISSUE THREAD

**Issue by ukhan67** [Azure/azure-sdk-for-python#34415]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by swathipil** [comment]
@ukhan67 - Please fill out the bug report here so that we can investigate. Thanks!

cc/ @azureml-github

**Comment by swathipil** [comment]
Seems to be a repeat of #34416
