### ISSUE TITLE
Azure Advisor SDK and API endpoint response missing attributes

### ISSUE THREAD

**Issue by DevOpsStyle** [Azure/azure-sdk-for-python#34452]
- **Azure-mgmt-advisor**: 
- **9.0.0**: 
- **Windows Server 2022**:
- **3.12**: 

**Describe the bug**
The Azure Advisor JSON response is missing some attributes, like the "description" field.

**To Reproduce**
1. GET https://management.azure.com/subscriptions/subscriptionId/providers/Microsoft.Advisor/recommendations?api-version=2023-01-01
2. Read the response

**Expected behavior**
Response like that:

"value": [
    {
      "id": "/resourceUri/providers/Microsoft.Advisor/recommendations/recGUID1",
      "name": "recGUID1",
      "properties": {
        "category": "HighAvailability",
        "impact": "Medium",
        "impactedField": "Microsoft.Compute/availabilitySets",
        "impactedValue": "armavset",
        "lastUpdated": "2017-02-24T22:24:43.3216408Z",
        "risk": "Warning",
        "remediation": {
          "additionalProperties": {
            "httpMethod": "POST",
            "uri": "uri",
            "details": "link to document"
          }
        },
        "shortDescription": {
          "problem": "To ensure high availability add one or more virtual machines to this availability set",
          "solution": "To ensure high availability add one or more virtual machines to this availability set"
        },
        "resourceMetadata": {
          "resourceId": "/subscriptions/subscriptionId/resourceGroups/resourceGroup/providers/Microsoft.Compute/availabilitysets/abc",
          "action": {
            "additionalProperties": {
              "actionType": "Document",
              "link": "https://link3",
              "caption": "Enable Soft Delete to protect blob data",
              "description": "Enable Soft Delete to protect blob data"
            },
            "metadata": {
              "id": "/subscriptions/subscriptionId"
            }
          },
          "singular": "Availability set",
          "plural": "Availability sets"
        },
        "actions": [
          {
            "additionalProperties": {
              "actionType": "Document",
              "link": "https://link1",
              "caption": "Enable Soft Delete to protect blob data",
              "description": "Enable Soft Delete to protect blob data"
            },
            "metadata": {
              "id": "/subscriptions/subscriptionId"
            }
          }
        ],
        "description": "After enabling Soft Delete, deleted data transitions to a soft deleted state instead of being permanently deleted. When data is overwritten, a soft deleted snapshot is generated to save the state of the overwritten data. You can configure the amount of time soft deleted data is recoverable before it permanently expires.",
        "label": "Enable Soft Delete",
        "learnMoreLink": "https://link2",
        "potentialBenefits": "Save and recover your data when blobs or blob snapshots are accidentally overwritten or deleted"
      },
      "type": "Microsoft.Advisor/recommendations"
    }

But instead I got:

{
   "properties":{
      "category":"HighAvailability",
      "impact":"High",
      "impactedField":"MICROSOFT.COMPUTE/DISKS",
      "impactedValue":"AADJoinVM_OsDisk_1_01c956f5872647f3ad36daee1c169805",
      "lastUpdated":"2024-02-25T20:59:57.0398805Z",
      "recommendationTypeId":"d4102c0f-ebe3-4b22-8fe0-e488866a87af",
      "shortDescription":{
         "problem":"Use Azure Disks with Zone Redundant Storage for higher resiliency and availability",
         "solution":"Use Azure Disks with Zone Redundant Storage for higher resiliency and availability"
      },
      "extendedProperties":{
         "Location":"westus2"
      },
      "resourceMetadata":{
         "resourceId":"/subscriptions/subid/resourceGroups/AVD/providers/Microsoft.Compute/disks/AADJoinVM_OsDisk_1_01c956f5872647f3ad36daee1c169805"
      }
   },
   "id":"/subscriptions/subid/resourceGroups/AVD/providers/Microsoft.Compute/disks/AADJoinVM_OsDisk_1_01c956f5872647f3ad36daee1c169805/providers/Microsoft.Advisor/recommendations/99c3c772-f9f1-8447-91c2-94102cc65f97",
   "type":"Microsoft.Advisor/recommendations",
   "name":"99c3c772-f9f1-8447-91c2-94102cc65f97"
}

**Screenshots**

**Additional context**
The sample response reported in the documentation is here: https://learn.microsoft.com/en-us/rest/api/advisor/recommendations/list?view=rest-advisor-2023-01-01&tabs=HTTP

**Comment by ChenxiJiang333** [comment]
By the different recommendation type, the response schema could be different as well. Besides, since it's a service issue, it's suggested to seek help from service team: https://github.com/Azure/azure-rest-api-specs/tree/main/specification.

**Comment by DevOpsStyle** [comment]
Opened parallel issue as reported

**Comment by ChenxiJiang333** [comment]
Hope that there will be a quick response.

**Comment by xiangyan99** [comment]
Given there is nothing SDK can do, I will close the issue and please use https://github.com/Azure/azure-rest-api-specs/tree/main/specification to track it.
