### ISSUE TITLE
Getting google.rpc module error from opencensus library.

### ISSUE THREAD

**Issue by DeepKariaX** [Azure/azure-sdk-for-python#34455]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.13.0
- **Operating System**: Linux
- **Python Version**:  3.10

**Describe the bug**
Tried to install azure-ai-ml and run the python code. It was giving google.rpc module error.
It comes from the opencensus/trace/status.py at line 15

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/86719707/0468b085-d90b-4b15-8527-0444dbcc1028)

**Comment by diondrapeck** [comment]
Hi @DeepKariaX - did you get this error during the installation command or while trying to run azure-ai-ml code? If the latter, can you share the code you ran?
