### ISSUE TITLE
azure.mgmt.authorization RoleAssignmentsOperations list_for_scope: Incorrect error handling

### ISSUE THREAD

**Issue by wiperpaul** [Azure/azure-sdk-for-python#34456]
- **Package Name**: azure.mgmt.authorization
- **Package Version**:  v2022_04_01
- **Operating System**: Windows
- **Python Version**: 3.11.7

**Describe the bug**
I am using list_for_scope with a filter to look for a specific assignment. 
`filter_str = f"roleDefinitionId eq '{ROLE_DEFINITION_ID}' and principalId eq '{principle_id}'"
    role_assignments = auth_client.role_assignments.list_for_scope(
        scope=rg_scope, filter=filter_str
    )`

When passing a broken query, where I forgot to clean principle_id for instance this is what ends up in the query section of the request ( I am aware this filter is not valid as there is no AND operator ):
`""roleDefinitionId eq 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx' and principalId eq '{'xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx'}'""`

Although we get `status_code: 400` and `reason: 'Bad Request'`

 the internal_response.content is not as expected: and returns `b'{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}'`
 
I believe this is not intentional and it should report there was a parsing issue with the query. Instead the behavior within the  def `prepare_request ` seems to slice down the query missing essential query parameters:

 
`"https://management.azure.com/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/xxx-rg/providers/Microsoft.Authorization/roleAssignments`

instead of 

`"https://management.azure.com/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/xxx-rg/providers/Microsoft.Authorization/roleAssignments?$filter=roleDefinitionId eq 'xxxx-xxxx-xxxx-xxxx-xxxxxxxx' and principalId eq 'xxxxx-xxxx-xxxx-xxxx-xxxxxx'&api-version=2022-04-01"`

**Expected behavior**
Failure with bad filter query or Failure if missing query parameters due to poor filter.

**Comment by wiperpaul** [comment]
usually the response with an incorrect query is:

`error: The filter 'principalId eq ''' is not supported. Supported filters are either 'atScope()' or 'principalId eq '{value}''.`

**Comment by ChenxiJiang333** [comment]
The `{value}` here means you need to replace it with your own input, so the correct way to pass the value is to follow this format https://github.com/Azure/azure-sdk-for-python/issues/34747#issuecomment-1995316570.

**Comment by wiperpaul** [comment]
> @wiperpaul The `{value}` here means you need to replace it with your own input, so the correct way to pass the value is to follow this format [#34747 (comment)](https://github.com/Azure/azure-sdk-for-python/issues/34747#issuecomment-1995316570).

Please read the entire git issue... you can clearly see I pass real  principal I'd.

**Comment by ChenxiJiang333** [comment]
> > @wiperpaul The `{value}` here means you need to replace it with your own input, so the correct way to pass the value is to follow this format [#34747 (comment)](https://github.com/Azure/azure-sdk-for-python/issues/34747#issuecomment-1995316570).
> 
> Please read the entire git issue... you can clearly see I pass real principal I'd.

If you pass filter in this format `principalId eq '{'xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx'}'`, the curly braces in its values will raise `KeyError` with the method str.format() when process the request url (see [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L102)), and as the result of it, parameter `api-verison` would be wrongly removed from request url and that's why it returns the error message `The api-version query parameter (?api-version=) is required for all requests.` So it's an error only when you pass curly braces in the values.
