### ISSUE TITLE
ImportError: cannot import name 'get_file_items'

### ISSUE THREAD

**Issue by cdreetz** [Azure/azure-sdk-for-python#34460]
- **Package Name**: azure-search-documents
- **Package Version**: 11.4.0
- **Operating System**: Linux-4.15.0-1173-azure-x86_64-with-glibc2.27
- **Python Version**: '3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]'

**Describe the bug**
Not able to import SearchClient
`ImportError: cannot import name 'get_file_items' from 'azure.core.utils._pipeline_transport_rest_shared' (/home/trusted-service-user/cluster-env/clonedenv/lib/python3.10/site-packages/azure/core/utils/_pipeline_transport_rest_shared.py)
`

**To Reproduce**
1. from azure.search.documents import SearchClient

**Expected behavior**
Import SearchClient

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/117322020/a1907e92-79a7-47d4-907b-aaee8e1e61b8)

**Additional context**
I am trying to run this in a Fabric Notebook, I have upgraded both azure-core and azure-search-documents
![image](https://github.com/Azure/azure-sdk-for-python/assets/117322020/17d926dd-f99c-441d-809b-16c3505cb845)

**Comment by kashifkhan** [comment]
Thanks for the feedback @cdreetz . We will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
Thanks for reaching out. Could you help to share the azure-core version you are using?

**Comment by xiangyan99** [comment]
Thanks for the information.

Unfortunately, I could not repro the issue on my machine.

Here is my pip list:

Package                Version
---------------------- --------
azure-common           1.1.28
azure-core             1.30.0
azure-search-documents 11.4.0
certifi                2024.2.2
charset-normalizer     3.3.2
idna                   3.6
isodate                0.6.1
pip                    24.0
requests               2.31.0
setuptools             65.5.0
six                    1.16.0
typing_extensions      4.10.0
urllib3                2.2.1

Could you try creating a new virtual environment and installing those packages?

Is it still repro-able?
