### ISSUE TITLE
There should be a way of creating mixed case instrumentation names when using the configure_azure_monitor() convenience method.

### ISSUE THREAD

**Issue by freemansoft** [Azure/azure-sdk-for-python#34465]
- **Package Name**:  azure-monitor-opentelemetry
- **Package Version**:  1.2.0
- **Operating System**: Windows but it is immaterial
- **Python Version**:  3.9.13

**Describe the bug**
`configure_azure_monitor()` doesn't support a way of providing or later adding Metrics Views.  This means that metrics change their names when moving from OpenCensus to OpenTelemetry if the old names were mixed cases with spaces.

The Python Open telemetry SDK converts all meter (gauge, counter, etc) names to lowercase. 
 See: https://github.com/open-telemetry/opentelemetry-python/issues/3207 Experimentation shows that it fails if there are spaces in the metrics names.

The Azure OpenCensus API supported mixed case names with spaces via the view functionality.  

It looks like Azure OpenTelemetry API may support mixed case via Views.   It is hard to tell because there are zero examples of mixed case or spaces. This page https://learn.microsoft.com/en-us/python/api/overview/azure/monitor-opentelemetry-exporter-readme?view=azure-python-preview#metric-custom-views shows that it is possible to add views via the `Meter Provider`

```python
reader = PeriodicExportingMetricReader(exporter, export_interval_millis=5000)
provider = MeterProvider(
    metric_readers=[
        reader,
    ],
    views=[
        change_metric_name_view,
    ],
)
metrics.set_meter_provider(provider)
``

azure.monitor.opentelmetry._confgure invokes `_setupmetrics()`  That method does not accept or configure views.  Views cannot be added once the Provider is configured.

```python
def _setup_metrics(configurations: Dict[str, ConfigurationValue]):
    resource: Resource = configurations[RESOURCE_ARG] # type: ignore
    metric_exporter = AzureMonitorMetricExporter(**configurations)
    reader = PeriodicExportingMetricReader(metric_exporter)
    meter_provider = MeterProvider(
        metric_readers=[reader],
        resource=resource
    )
    set_meter_provider(meter_provider)
```

**To Reproduce**
1. 

**Expected behavior**
The convenience method `configure_azure_monitor()` should accept Views or there should be a way to inject them.  Or documentation should be added to say that the convenience method cannot be used for views.

Documentation should show or say whether or not the names in the views can be mixed case and include spaces as they did in the past with OpenCensus.

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @freemansoft . We will investigate and get back to you asap.

**Comment by lzchen** [comment]
@freemansoft 

Our team is currently discussing Views configuration through the distro api at the moment. Will comment on this issue if there are any updates.

**Comment by freemansoft** [comment]
You can see an example of how someone might use the current `configure_azure_monitor` in combination with environment variables to tune the auto-instrumented pieces. Variables for integrations and to determine if metrics, tracing, or logs get sent.  Then your API to control the Azure/Microsoft specific pieces https://joe.blog.freemansoft.com/2024/02/using-opentelemetry-to-send-python.html

**Comment by lzchen** [comment]
This is currently on our agenda to work on so this is WIP.

**Comment by freemansoft** [comment]
Finally got around to validating this by running queries against CustomMetrics and the quick check looks good

These are three of the views I configured.  Note that the `instrument_name` has to be specified in lower case.  It doesn't seem to match if it is mixed case.  The actual instrument_name is in lower case even if specified as mixed case. I think this is the OT standard.  Seems like a defect that the `instrument_name` here may not automatically toLowerCase()

Here we are using the default aggregation.  These are synchronous gauges so the the aggregation is _probably_ the same as the asynch gauge.

```python
    _st_servers_time_view = SdkView(
        instrument_name="st_servers_time",
        name="ST Servers Time",
        description="get servers",
    )
    _st_best_servers_time_view = SdkView(
        instrument_name="st_best_servers_time",
        name="ST Best Servers Time",
        description="get best servers",
    )
    _st_ping_time_view = SdkView(
        instrument_name="st_ping_time",
        name="ST Ping Time",
        description="last ping",
    )
```

The Azure monitor query picks up the new view name (yay!) and the old non-view all-lower-case name.  My new metrics are the former.  The old metrics are the latter.

```
customMetrics | where name == "ST Ping Time" or name == "st_ping_time"
```

**Comment by thelazydogsback** [comment]
Is there still no way to preserve case in metric names by default?  
As of 8/5/2024, names are still getting smashed to lower case. 
Or do I need to pass in a custom view for every one of my metrics into the `MeterProvider` `views` collection?
