### ISSUE TITLE
[Identity] Credential chain can be disrupted by empty environment variables

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#34487]
**Library versions used:**
- `azure-identity==1.15.1`
- `python-dotenv==1.0.0`

**Description:**

With some environment variable configurations, the DefaultAzureCredential may raise an exception during initialization instead of continuing down the credential chain. The scenario motivating this issue looks like the following:

1. DefaultAzureCredential is created
2. DefaultAzureCredential attempts to use EnvironmentCredential
3. EnvironmentCredential attempts to use ClientSecretCredential
4. ClientSecretCredential raises an uncaught `ValueError` in its constructor
5. DefaultAzureCredential raises this `ValueError` and fails initialization

**Steps to reproduce:**

1. Open the `.env` file used for local testing
2. Set `AZURE_TENANT_ID`, `AZURE_CLIENT_ID`, and/or `AZURE_CLIENT_SECRET` to be an empty string, `''` (e.g. `AZURE_TENANT_ID=''`)
3. Open a terminal window and `cd` into the `azure-sdk-for-python`
4. Run `python`
5. Run the following lines:
```
>>> from dotenv import load_dotenv
>>> load_dotenv()
>>> from azure.identity import DefaultAzureCredential
>>> credential = DefaultAzureCredential()
```

A `ValueError` like the following should be raised:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mcpatino/azure-sdk-for-python/sdk/identity/azure-identity/azure/identity/_credentials/default.py", line 149, in __init__
    credentials.append(EnvironmentCredential(authority=authority, _within_dac=True, **kwargs))
  File "/home/mcpatino/azure-sdk-for-python/sdk/identity/azure-identity/azure/identity/_credentials/environment.py", line 71, in __init__
    self._credential = ClientSecretCredential(
  File "/home/mcpatino/azure-sdk-for-python/sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py", line 45, in __init__
    raise ValueError("client_id should be the id of a Microsoft Entra application")
ValueError: client_id should be the id of a Microsoft Entra application
```

This happens because of differing logic in how the EnvironmentCredential and ClientSecretCredential each detect the availability of service principal environment variables.

The EnvironmentCredential checks that each of these variables is `not None`: https://github.com/Azure/azure-sdk-for-python/blob/e92e4cb7446cf3c101ffb34387def005ca898d55/sdk/identity/azure-identity/azure/identity/_credentials/environment.py#L69-L70

Whereas the ClientSecretCredential checks for the boolean value of each: https://github.com/Azure/azure-sdk-for-python/blob/e92e4cb7446cf3c101ffb34387def005ca898d55/sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py#L44-L49

In the case where at least one of these variables is set to an empty string, the former check succeeds while the latter fails and causes a `ValueError`, disrupting the DefaultAzureCredential chain.

**Comment by xiangyan99** [comment]
This behavior is by design. :)

If the environment variable is set (even to ''), we don't know if user wants to ignore it or it is a mistake.

It is by design that we don't want DefaultAzureCredential to silently skip it if it does not work. It may end up with accidentally using another credential, e.g. cli.
