### ISSUE TITLE
rendered documentation not published

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#34488]
### Type of issue

Missing information

### Description

We found the documentation of the newly released service `liftr-astronomer` has been rendered and pushed to the repository : https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/liftr-astronomer.md, yet strangely, there's none of its page could be found from the [reference](https://learn.microsoft.com/en-us/python/api/overview/azure/?view=azure-python-preview).

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/liftr-astronomer?view=azure-python-preview

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/liftr-astronomer.md

### Document Version Independent Id

not yet

### Article author

@azure-sdk

### Metadata

* Service: **liftr-astronomer**

**Comment by ChenxiJiang333** [comment]
@rohit-ganguly @danieljurek could you help take a look at it about why this page was not published?

**Comment by danieljurek** [comment]
@ChenxiJiang333 -- Azure SDK reference documentation publishes to the live docs site every Wednesday morning. Please confirm the docs are live now.

**Comment by ChenxiJiang333** [comment]
Found the pages, thanks!
