### ISSUE TITLE
How to use SearchAlias in azure-search-documents

### ISSUE THREAD

**Issue by kachely** [Azure/azure-sdk-for-python#34494]
**Is your feature request related to a problem? Please describe.**
I'd like to use the search alias feature but failed with error 

> cannot import name 'SearchAlias' from 'azure.search.documents.indexes.models'

Then I found an issue related with this problem. It mentioned to use a pre-release version `11.4.0b2`
https://github.com/Azure/azure-sdk-for-python/issues/28283

I tried that version; it does include the SearchAlias model while new error occurs.

> cannot import name 'VectorizedQuery' from 'azure.search.documents.models' 

Could you please guide me how to use the SearchAlias function?
Besides, could we also add some examples on how to query the index with alias? Thank you!

**Describe the solution you'd like**
Use both `SearchAlias` and `VectorizedQuery` 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by xiangyan99** [comment]
`SearchAlias` is a preview feature.

Have you tried the latest preview https://pypi.org/project/azure-search-documents/11.6.0b1/?

Did it work for you?
