### ISSUE TITLE
Failed to download azure-cosmos on Power (ppc64le) systems.

### ISSUE THREAD

**Issue by sshuklao** [Azure/azure-sdk-for-python#34499]
- **Package Name**: azure-cosmos
- **Package Version**: 4.3.1/4.5.1
- **Operating System**: RH Power systems
- **Python Version**: 3.10

**Describe the bug**
Failed to download using pip on power systems.

**To Reproduce**
1. pip install --upgrade azure-cosmos==4.3.1

**Expected behavior**
it should download the package.

**Screenshots**
<img width="1728" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/17142187/7a623b50-2cc8-4bbe-ae1c-54ec0c273c10">

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @sshuklao . We will investigate and get back to you asap.

**Comment by sshuklao** [comment]
its working now, thanks.
