### ISSUE TITLE
Unexpected delay when receive service bus queue message

### ISSUE THREAD

**Issue by lezi226** [Azure/azure-sdk-for-python#345]
Hi, I wrote two simple python code using the sdk for service bus Queue, one for send a message, another one has an infinite loop to receive message. I found there is big delay between send message and the time message received most of the time, some may even delay more than 1 minute.

But I also tried same thing using C# library, there is no such delay.

Is this a known issue? What's the difference in underlying connection between Python & C# client library? I know this Python sdk using httplib though.

Thanks

**Comment by huguesv** [comment]
That's not a known issue.  If you set the value of the timeout parameter in the call to peek_lock_queue_message/read_delete_queue_message to be lower than the default 60 secs, do you see a change in behavior?

**Comment by dengxi** [comment]
Hi, huguesv, I tried low the value to 10 secs, still be able to repro the issue. What I do is:
1. Send multiple messages quickly. e.g. sending all these messages within 20 secs.
2. Invoke receive_queue_message(internally invoke read_delete_queue_message) in a while loop with timeout 10 secs.  It may take several minutes to read all the messages sent in step 1.

Could you help to investigate? I can send you the test code with the problematic service bus connection string, also the C# code I used to compare.

**Comment by huguesv** [comment]
I created a new service bus namespace in the West US region and I'm not seeing the issue.  If you haven't tried already, I'd recommend creating a new namespace, maybe in a different region.  Maybe you are unlucky and got a bad server?

sender.py
```
from azure.servicebus import ServiceBusService, Message
from datetime import datetime
from time import sleep

import config

service = ServiceBusService(
    service_namespace=config.ns_name,
    shared_access_key_name=config.key_name,
    shared_access_key_value=config.key_value,
)

service.create_queue(config.queue_name)

index = 0
while True:
    message = Message('MSG {0} sent at {1}'.format(index, datetime.now()))
    index += 1
    service.send_queue_message(config.queue_name, message)
    sleep(5)


```

receiver.py
```
from azure.servicebus import ServiceBusService, Message
from datetime import datetime
from time import sleep

import config

service = ServiceBusService(
    service_namespace=config.ns_name,
    shared_access_key_name=config.key_name,
    shared_access_key_value=config.key_value,
)

service.create_queue(config.queue_name)

while True:
    message = service.receive_queue_message(config.queue_name, peek_lock=True, timeout=60)
    if message is not None:
        print(message.body + ' received at {0}'.format(datetime.now()))
        message.delete()
    else:
        print('<no message> at {0}'.format(datetime.now()))

```

As you can see from the receiver output, it's getting the message relatively fast, usually less than a second:
```
MSG 0 sent at 2015-04-24 12:17:16.822000 received at 2015-04-24 12:17:18.330000
MSG 1 sent at 2015-04-24 12:17:23.091000 received at 2015-04-24 12:17:27.834000
MSG 2 sent at 2015-04-24 12:17:33.703000 received at 2015-04-24 12:17:34.579000
MSG 3 sent at 2015-04-24 12:17:39.244000 received at 2015-04-24 12:17:39.731000
MSG 4 sent at 2015-04-24 12:17:44.769000 received at 2015-04-24 12:17:45.100000
MSG 5 sent at 2015-04-24 12:17:50.097000 received at 2015-04-24 12:17:50.747000
MSG 6 sent at 2015-04-24 12:17:55.746000 received at 2015-04-24 12:17:56.098000
MSG 7 sent at 2015-04-24 12:18:01.096000 received at 2015-04-24 12:18:01.554000
MSG 8 sent at 2015-04-24 12:18:06.545000 received at 2015-04-24 12:18:07.554000
MSG 9 sent at 2015-04-24 12:18:11.835000 received at 2015-04-24 12:18:12.103000
```

**Comment by dengxi** [comment]
It's strange. It's my output below. You can see big delay(~ 1 minute for message 1), and also message 2 & 4 is missing. I tried to create new two service bus, one in east asia and another in central us, both have same behavior. Can you share you email? I can send the access key of my bus to you, just to double confirm the behavior from your side for the exactly same bus. Thanks

MSG 0 sent at 2015-04-25 00:08:16.456000 received at 2015-04-25 00:08:33.993000
MSG 5 sent at 2015-04-25 00:08:43.219000 received at 2015-04-25 00:08:43.577000
MSG 3 sent at 2015-04-25 00:08:32.447000 received at 2015-04-25 00:08:50.233000
MSG 1 sent at 2015-04-25 00:08:21.781000 received at 2015-04-25 00:09:14.134000

**Comment by dengxi** [comment]
BTW: I tried using C# to write similar sender/writer, then there is no such issue. Is it possible the way python library used to send request cause the difference? e.g. UserAgent ?

**Comment by huguesv** [comment]
I am now able to reproduce the delay.  It is due to using a queue that has partitioning enabled.  If you use the portal to create the queue, select custom, and on the second page you have the option of using partitioning.  By default it is on.  If you create it programmatically with `create_queue`, it will be off.

![partitioning](https://cloud.githubusercontent.com/assets/1696845/7354288/5b8ccce4-eccf-11e4-8c58-a3b38bb81988.png)

I'll work on a solution for when partitioning is enabled.  As far as C# is concerned, it doesn't use the REST api, and so is bypassing the issue.

**Comment by dengxi** [comment]
Awesome! Thanks very much for figuring it out.

**Comment by huguesv** [comment]
Using the requests library, which has connection pooling, improves performance with partitioning quite a bit.  Still the occasional message that has a long delay, but in general it behaves much like when partitioning is off.  We already have plans to completely switch over to using requests, but we're not quite ready to do it now.  I hope disabling partitioning is a usable workaround until then.

**Comment by lezi226** [comment]
Yes, disable partition works for me. Thanks

**Comment by lalitb** [comment]
Is the delay "acceptable" when partitioning is enabled, and we don't specify any partitioning key while inserting and fetching the data. Or is there any issue opened for it ?

**Comment by lmazuel** [comment]
Hi @lalitb the Service Bus team now suggests to use the AMQP protocol with [Proton](https://qpid.apache.org/proton/) if performance and delay are important.
Thanks,

**Comment by Totzmaster** [comment]
Hi,
we are dequeuing data with HTTP requests (out of Oracle PL/SQL)
and are experiencing the same delays on partitioned queues.
I think, the REST middleware/interface has a bug.
The lock timeout has something to do with the delay.
If its 1 min, then the delay will be x times 36 seconds (0 sec, 36 sec, 72sec ,...)

Bye

**Comment by gabrieljoelc** [comment]
i am getting ~5 second response times from both partition on/off on REST. Changing the lock duration doesn't affect anything either.

this is for an integration with a third-party where they using AMQP is non-trivial.

**Comment by Totzmaster** [comment]
Hi,
we were successful doing various optimizations at our HTTP/REST interface, including:
- change to "keep-alive" -> connection stays alive for days
- change to premium account ($$$) -> overall throughput increases significantly
The interface is now running 2 years very satisfying.

Bye

PS: A few weeks ago we had a bit trouble because of this:   [Azure TLS certificate changes](https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes)

**Comment by gabrieljoelc** [comment]
> - change to "keep-alive" -> connection stays alive for days

@Totzmaster thanks for the info. Was this change just setting the header for the request?

**Comment by Totzmaster** [comment]
At Oracle PL/SQL you have to:
- set utl_http.set_persistent_conn_support(req, true); 
- set the header utl_http.set_header(req,'Connection','Keep-Alive');
- and don't close the connection.
I think, that depends on the API you are using.

What I forgit: For even more throughput we parallelized the interface (3 threads/connections at the same time)
