### ISSUE TITLE
Need documentation on Programming Model V2 objects (azure.functions.FunctionApp, azure.functions.Blueprint, etc...)

### ISSUE THREAD

**Issue by drobert-bfm** [Azure/azure-sdk-for-python#34506]
### Type of issue

Missing information

### Description

Need documentation on Programming Model V2 objects (azure.functions.FunctionApp, azure.functions.Blueprint, etc...)

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/functions?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/functions.md

### Document Version Independent Id

be263e59-b2c6-525f-1fad-296155cc4d4c

### Article author

@azure-sdk

### Metadata

* ID: f672819f-a1d5-cf69-346a-ef6f4f3bec14 
* Service: **functions**

**Comment by kashifkhan** [comment]
Hi @drobert-bfm, as this is related to Azure Functions documentation the issue needs to be created in the functions repo [here](https://github.com/Azure/Azure-Functions).
