### ISSUE TITLE
Blob storage copy completion time is None

### ISSUE THREAD

**Issue by hector-sab** [Azure/azure-sdk-for-python#34502]
- **Package Name**:  azure-storage-blob
- **Package Version**: 12.19.0
- **Operating System**: Linux
- **Python Version**: 3.11.5

**Describe the bug**
When requesting the blob properties through the python sdk, the completion time of the copy information of the blob is unavailable through the CopyProperties.

**To Reproduce**
1. Create a Storage Account in Azure
2. Create a Contanier
3. Upload whatever file you want to it
4. Run the code below and chech the `properties.copy.completion_time`

```python
from azure import identity
from azure.storage import blob

credential = identity.DefaultAzureCredential()
container = 'mycontainer'
account_url = "https://myaccount.blob.core.windows.net/"
bsc = blob.BlobServiceClient(
    account_url=account_url,
    credential=credential,
)
container_client = bsc.get_container_client(container)

path = 'myfile.txt'
blob_client = container_client.get_blob_client(path)
properties = blob_client.get_blob_properties()

print(properties.copy.completion_time)  # This will show nothing as it is None
```

**Expected behavior**
The copy information contains the completion time of the copy.

**Screenshots**
In the srceenshot you can see the initialization of the CopyProperties dataclass and that `kwargs.get('x-ms-copy-completion_time')` returns nothing, but `kwargs.get('x-ms-copy-completion-time')` returns a datetime object
![image](https://github.com/Azure/azure-sdk-for-python/assets/11972724/03220e1d-0708-44df-bd3f-fc3fca83b0c6)

**Additional context**
I created this PR that fixes it. It is a really simple fix. https://github.com/Azure/azure-sdk-for-python/pull/34500

**Comment by vincenttran-msft** [comment]
Hi @hector-sab Héctor, thanks for your inquiry! This does seem like it is simply a typo (using `_` where it should be a `-`). I can take your pull-request fix as you have correctly identified the root cause, but I will leave some guidance on what is missing from the pull-request in the PR comments 😄 
Thanks!
