### ISSUE TITLE
TRying to create a search index with parameters

### ISSUE THREAD

**Issue by Nalin879** [Azure/azure-sdk-for-python#34529]
Created a skillset with azure search documents indexes models but setting the parameters for indexers facing an issue
---------------------------------------------------------------------------
HttpResponseError                         Traceback (most recent call last)
Cell In[172], line 29
     13 indexer = SearchIndexer(  
     14     name=indexer_name,  
     15     description="Indexer to index documents and generate embeddings",  
   (...)
     25     field_mappings=[FieldMapping(source_field_name="metadata_storage_name", target_field_name="title")]  
     26 )  
     28 indexer_client = SearchIndexerClient(endpoint, credential)  
---> 29 indexer_result = indexer_client.create_or_update_indexer(indexer)  
     31 # Run the indexer  
     32 indexer_client.run_indexer(indexer_name)  

File ~\AppData\Local\anaconda3\Lib\site-packages\azure\core\tracing\decorator.py:78, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
     76 span_impl_type = settings.tracing_implementation()
     77 if span_impl_type is None:
---> 78     return func(*args, **kwargs)
     80 # Merge span is parameter is set, but only if no explicit parent are passed
     81 if merge_span and not passed_in_parent:

File ~\AppData\Local\anaconda3\Lib\site-packages\azure\search\documents\indexes\_search_indexer_client.py:134, in SearchIndexerClient.create_or_update_indexer(self, indexer, match_condition, **kwargs)
    132 kwargs.update(access_condition)
    133 name = indexer.name
--> 134 result = self._client.indexers.create_or_update(
    135     indexer_name=name, indexer=indexer, prefer="return=representation", error_map=error_map, **kwargs
    136 )
    137 return result

File ~\AppData\Local\anaconda3\Lib\site-packages\azure\core\tracing\decorator.py:78, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
     76 span_impl_type = settings.tracing_implementation()
     77 if span_impl_type is None:
---> 78     return func(*args, **kwargs)
     80 # Merge span is parameter is set, but only if no explicit parent are passed
     81 if merge_span and not passed_in_parent:

File ~\AppData\Local\anaconda3\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexers_operations.py:827, in IndexersOperations.create_or_update(self, indexer_name, prefer, indexer, if_match, if_none_match, skip_indexer_reset_requirement_for_cache, disable_cache_reprocessing_change_detection, request_options, **kwargs)
    825     map_error(status_code=response.status_code, response=response, error_map=error_map)
    826     error = self._deserialize.failsafe_deserialize(_models.SearchError, pipeline_response)
--> 827     raise HttpResponseError(response=response, model=error)
    829 if response.status_code == 200:
    830     deserialized = self._deserialize("SearchIndexer", pipeline_response)

HttpResponseError: () The request is invalid. Details: The property 'parsingMode' does not exist on type 'Microsoft.Azure.Search.V2023_10_01_Preview.IndexingParameters'. Make sure to only use property names that are defined by the type.
Code: 
Message: The request is invalid. Details: The property 'parsingMode' does not exist on type 'Microsoft.Azure.Search.V2023_10_01_Preview.IndexingParameters'. Make sure to only use property names that are defined by the type.

**Comment by kashifkhan** [comment]
Thank you for the feedback @Nalin879 . We will investigate and get back to you asap.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you help to provide the information:

the version of azure-search-documents and azure-core libraries.

The code snippet to repro the issue?

Thank you.

**Comment by Nalin879** [comment]
azure search documents 
VERSION = "11.6.0b1"  # type: str
azure core
VERSION = "1.30.0"

**Comment by xiangyan99** [comment]
Thanks for sharing your code.

I am afraid it is not the recommended way to create the indexer.

Could you follow the sample and try again?

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_indexer_datasource_skillset.py#L119
