### ISSUE TITLE
sdk/textanalytics/azure-ai-textanalytics/samples/sample_multi_category_classify.py

### ISSUE THREAD

**Issue by B2-krunalrana** [Azure/azure-sdk-for-python#34530]
- **Psample_multi_category_classify.py**: 
- ****: 
- **windows**:
- **3.10**: 

**Describe the bug**
Module Existence: The MultiCategoryClassifyAction module might not be available in the version of the azure-ai-textanalytics package you have installed. It's possible that this module was introduced in a newer version.

Namespace Change: The module might exist in a different namespace or under a different name in the version you are using. Double-check the documentation or release notes for the package to see if there have been any changes in module organization.

Compatibility: Ensure that you are using a version of the azure-ai-textanalytics package that is compatible with the module you are trying to import.

**To Reproduce**
1. try to run below script 
script path : sdk/textanalytics/azure-ai-textanalytics/samples/sample_multi_category_classify.py
script link : https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/samples/sample_multi_label_classify.py

**Expected behavior**
it not gone run 
Traceback (most recent call last):
  File "D:\ahaguru\ahaguru-analytics-aI-integration-scripts\Krunal - Ahaguru\prediction_api\modal_test1.py", line 81, in <module>
    from azure.ai.textanalytics import TextAnalyticsClient,MultiCategoryClassifyAction
ImportError: cannot import name 'MultiCategoryClassifyAction' from 'azure.ai.textanalytics' (D:\ahaguru\.a\Lib\site-packages\azure\ai\textanalytics\__init__.py)

**Screenshots**

![image](https://github.com/Azure/azure-sdk-for-python/assets/90046525/a4e48ed7-66a1-49af-bf3a-3e0e7877a2a5)

**Additional context**
Try to test multilabel classification locallly

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kristapratico** [comment]
@B2-krunalrana the model is called `MultiLabelClassifyAction`, not `MultiCategoryClassifyAction`. Can you try that in your code and let us know if it doesn't work?
