### ISSUE TITLE
BUG REPORT : Custom Text Classification using python sdk 

### ISSUE THREAD

**Issue by B2-krunalrana** [Azure/azure-sdk-for-python#34531]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kashifkhan** [comment]
Hi @B2-krunalrana, can you please provide details around the issue you are having, add in repro code, python version and the name of the packages.
