### ISSUE TITLE
Azure AI Search Sample Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#34551]
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/samples/sample_indexer_datasource_skillset.py#L119)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/79193c00-125e-45e9-abc9-e9be23801378)

**Reason:**
Missing parameter `queryTimeout`. Configuration property 'queryTimeout' is not supported for the data source of type 'azureblob'.

@rohit-ganguly , @lmazuel , @achandmsft,  @mayurid,  @xiangyan99 for notification.

**Comment by xiangyan99** [comment]
query_timeout is a string type. It cannot be none. Did I miss anything?

**Comment by v-xuto** [comment]
@xiangyan99 Regarding the fix for this issue, what progress have you made so far?
