### ISSUE TITLE
AuthorizationPermissionMismatch when trying to read blob files via DefaultAzureCredential() from cloud shell

### ISSUE THREAD

**Issue by OCDolan** [Azure/azure-sdk-for-python#34556]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.19.0
- **Operating System**: Ubuntu 22.04 LTS
- **Python Version**: 3.10.12

**Describe the bug**
I am unable to read/download blobs using via `DefaultAzureCredential()`. I am able to use powershell to read the same blob with the same service account just fine...

**To Reproduce**

I've used `az storage account show -n <REDACTED> -g <REDACTED> --query "primaryEndpoints.blob"` to get the correct connection string...

1. Open an azure cloud shell
2. `python3 -m pip install azure-storage-blob azure-identity`
3. Run the following code in an interactive `python3` shell
    `from azure.identity import DefaultAzureCredential`
    `from azure.storage.blob import BlobServiceClient`
    `blob_service_client = BlobServiceClient("https://<REDACTED>.blob.core.windows.net/", DefaultAzureCredential())`
    `container_client = blob_service_client.get_container_client(container='<REDACTED>')`
    `container_client.download_blob('test.yaml').readall()`

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/dylan/.local/lib/python3.9/site-packages/azure/storage/blob/_container_client.py", line 1313, in download_blob
    return blob_client.download_blob(
  File "/usr/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/dylan/.local/lib/python3.9/site-packages/azure/storage/blob/_blob_client.py", line 942, in download_blob
    return StorageStreamDownloader(**options)
  File "/home/dylan/.local/lib/python3.9/site-packages/azure/storage/blob/_download.py", line 366, in __init__
    self._response = self._initial_request()
  File "/home/dylan/.local/lib/python3.9/site-packages/azure/storage/blob/_download.py", line 462, in _initial_request
    process_storage_error(error)
  File "/home/dylan/.local/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 184, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.
RequestId:<REDACTED>
Time:2024-03-01T10:50:03.9012904Z
ErrorCode:AuthorizationPermissionMismatch
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:<REDACTED>
Time:2024-03-01T10:50:03.9012904Z</Message></Error>
```

However, when trying to do the same thing using powershell, it works fine...
`$storageAccount = Get-AzStorageAccount -ResourceGroupName <REDACTED> -Name <REDACTED>`
`(Get-AzStorageBlobContent -Container "<REDACTED>" -Blob "test.yaml" -Destination "/home/dylan/test" -Context $storageAccount.Context).Content`
Here i receive the content of the file ok!

(I also obviously have access to download these blobs via the Azure Portal GUI)

**Expected behavior**
I expect the python sdk to receive the blob content just the same way as the powershell code does above.

**Screenshots**
None

**Additional context**
I've been following this page as a guide: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python
Is this a bug in the python SDK? Is there something else I need to give to the python SDK in order to identify myself?

I have reproduced this error on in the Azure portal Cloud Shell, Using my local machine with an `az login` using my account, using `az login --service-principal`, and by using `EnvironmentCredential` variables as per https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-environmentcredential-authentication-issues.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

DefaultAzureCredential is a chain of different credentials.

It is possible that a credential before powershell failed and it did not try powershell credential.

Could you enable debugging and share the logs?

You can add code like:

import logging
logging.basicConfig(filename='c:/temp/log.log', level=logging.DEBUG)

to enable logging.

**Comment by OCDolan** [comment]
Heya,

Here's the logs as requested...

`INFO:azure.identity._credentials.environment:No environment configuration found.`
`INFO:azure.identity._credentials.managed_identity:ManagedIdentityCredential will use Cloud Shell managed identity`
`DEBUG:azure.identity._internal.decorators:EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.`
`Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.`
`Traceback (most recent call last):`
`  File "/home/dylan/.local/lib/python3.9/site-packages/azure/identity/_internal/decorators.py", line 33, in wrapper`
`    token = fn(*args, **kwargs)`
`  File "/home/dylan/.local/lib/python3.9/site-packages/azure/identity/_credentials/environment.py", line 150, in get_token`
`    raise CredentialUnavailableError(message=message)`
`azure.identity._exceptions.CredentialUnavailableError: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.`
`Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.`
`INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'http://localhost:50342/oauth2/token'`
`Request method: 'POST'`
`Request headers:`
`    'Metadata': 'REDACTED'`
`    'User-Agent': 'azsdk-python-identity/1.15.0 Python/3.9.14 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'`
`A body is sent with the request`
`DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:50342`
`DEBUG:urllib3.connectionpool:http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2422`
`INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200`
`Response headers:`
`    'X-Powered-By': 'REDACTED'`
`    'Content-Type': 'application/json; charset=utf-8'`
`    'Content-Length': '2422'`
`    'ETag': 'W/"976-lcodna4W9NJ8U/mTFlHamPjfhAM"'`
`    'Date': 'Tue, 05 Mar 2024 09:16:07 GMT'`
`    'Connection': 'keep-alive'`
`    'Keep-Alive': 'REDACTED'`
`DEBUG:msal.token_cache:event={`
`    "data": {},`
`    "response": {`
`        "access_token": "********",`
`        "expires_in": "4442",`
`        "expires_on": 1709634609,`
`        "not_before": "1709628919",`
`        "refresh_token": "********",`
`        "resource": "https://storage.azure.com/",`
`        "token_type": "Bearer"`
`    },`
`    "scope": [`
`        "https://storage.azure.com/"`
`    ]`
`}`
`DEBUG:azure.identity._internal.get_token_mixin:CloudShellCredential.get_token succeeded`
`DEBUG:azure.identity._internal.decorators:ManagedIdentityCredential.get_token succeeded`
`DEBUG:azure.identity._internal.decorators:[Authenticated account] Client ID: <REDACTED>. Tenant ID: <REDACTED>. User Principal Name: unavailableUpn. Object ID (user): <REDACTED>`
`INFO:azure.identity._credentials.chained:DefaultAzureCredential acquired a token from ManagedIdentityCredential`
`INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://<REDACTED>.blob.core.windows.net/dsl-images/test.yaml'`
`Request method: 'GET'`
`Request headers:`
`    'x-ms-range': 'REDACTED'`
`    'x-ms-version': 'REDACTED'`
`    'Accept': 'application/xml'`
`    'User-Agent': 'azsdk-python-storage-blob/12.19.0 Python/3.9.14 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'`
`    'x-ms-date': 'REDACTED'`
`    'x-ms-client-request-id': '<REDACTED>'`
`    'Authorization': 'REDACTED'`
`No body was attached to the request`
`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): <REDACTED>.blob.core.windows.net:443`
`DEBUG:urllib3.connectionpool:https://<REDACTED>.blob.core.windows.net:443 "GET /dsl-images/test.yaml HTTP/1.1" 403 279`
`INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 403`
`Response headers:`
`    'Content-Length': '279'`
`    'Content-Type': 'application/xml'`
`    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'`
`    'x-ms-request-id': '<REDACTED>'`
`    'x-ms-client-request-id': '<REDACTED>'`
`    'x-ms-version': 'REDACTED'`
`    'x-ms-error-code': 'AuthorizationPermissionMismatch'`
`    'Date': 'Tue, 05 Mar 2024 09:16:07 GMT'`
`DEBUG:azure.storage.blob._generated._serialization:Ran into a deserialization error. Ignoring since this is failsafe deserialization`
`Traceback (most recent call last):`
`  File "/home/dylan/.local/lib/python3.9/site-packages/azure/storage/blob/_generated/_serialization.py", line 1542, in failsafe_deserialize`
`    return self(target_obj, data, content_type=content_type)`
`  File "/home/dylan/.local/lib/python3.9/site-packages/azure/storage/blob/_generated/_serialization.py", line 1413, in __call__`
`    data = self._unpack_content(response_data, content_type)`
`  File "/home/dylan/.local/lib/python3.9/site-packages/azure/storage/blob/_generated/_serialization.py", line 1571, in _unpack_content`
`    raise ValueError("This pipeline didn't have the RawDeserializer policy; can't deserialize")`
`ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize`

To note: the Object ID (user) given is the same one when running `az ad signed-in-user show` in an azure cloud shell

**Comment by xiangyan99** [comment]
@vincenttran-msft @jalauzon-msft seems like the app successfully got the token using the cloud shell extra id.

Could you check what permission the CloudShellCredential needs to access the blob?

**Comment by OCDolan** [comment]
My account has the Contributor BuiltInRole, so I believe I should just work as-is?. Also when using the powershell commands from the same cloud shell session I do have access, and I also have access to read/write blobs in the Azure portal UI, so I don't think it's a permissions issue?

**Comment by jalauzon-msft** [comment]
Hi @OCDolan, this is a pretty common issue we get, and the likely cause is you need one of the "Storage Blob Data *" built-in roles as well to use these credentials with the SDK. There is [Storage Blob Data Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-contributor), [Owner](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-owner), and [Reader](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-reader). These are separate from the built-in role of Contributor.

I don't fully understand why this is the case, but CloudShell/Azure CLI/Portal have a special auth mechanism that allows them to work without these roles. The SDK makes direct REST calls to the service, without any pre-authentication and therefore requires the Storage specific roles to be present. I will do some research internally and find out why specifically this is and get back to you but for now, try granting your account one of the Storage specific roles and it should work.

**Comment by jalauzon-msft** [comment]
@OCDolan, thanks for confirming. Glad the fix worked for you.

So, I checked with our Powershell team and did learn why this is the case. CloudShell (as well as Azure CLI and Portal) do in fact work a little differently. When you run a command like `Get-AzStorageAccount`, PSH makes a call to fetch the Storage account keys and cache them into memory for that session. Then when you make blob requests, it will actually use the account key to authenticate the request. The "Contributor" role is enough permission to allow you to access the account keys on the account through the management plane.

This differs for the SDK as `DefaultAzureCredential` just grabs the identity from CloudShell, not the session (with the account key) and then tries to use OAuth with that identity. OAuth for dataplane operations (Blob access) requires the "Storage Blob Data *" roles.

If you wanted to force CloudShell to use OAuth like the SDK, that could be done like this:
```powershell
$ctx = New-AzStorageContext -StorageAccountName <REDACTED>
(Get-AzStorageBlobContent -Container "<REDACTED>" -Blob "test.yaml" -Destination "/home/dylan/test" -Context $ctx).Content
```

Hopefully that makes some sense and helps to clarify what is happening. I am going to close this as resolved now but feel free to reach out if you have any more questions. Thanks.

**Comment by OCDolan** [comment]
Thanks for getting back to me @jalauzon-msft !

Ah that makes a bit more sense, thanks. Could that explanation be added to the documentation for the azure blob SDKs? It feels very un-intuitive that the permissions required to read a storage blob can differ depending on the language that you are using.
