### ISSUE TITLE
Duplicates when loading the documents from azure search index to dataframe

### ISSUE THREAD

**Issue by amritamadhav** [Azure/azure-sdk-for-python#34554]
Name: azure-search-documents
Version: 11.4.0
64-bit operating system, x64-based processor
Python 3.9.13

**Describe the bug**
encountering duplicates while loading the documents from azure search index into list or dataframes

**To Reproduce**
Azure Cognitive Search index replica is set to 3.
1. connect to Azure cognitive search index using python sdk
2. set the search parameters with "search_text": "*" and "include_total_count": True
3. Search the azure search index with the parameters
4. Append the above results to a list
5. Convert to dataframe

**Expected behavior**
1. Count should match between Azure search index documents and dataframe
2. No duplicates on the key or unique field in the dataframe. There are already no duplicates on the search index.

**Comment by kashifkhan** [comment]
Thank you for the feedback @amritamadhav . We will investigate and get back to you asap. 

in the meantime can you also provide a sample of the code that you are using please ?

**Comment by amritamadhav** [comment]
search_client= SearchClient(endpoint=endpoint,
                            index_name=index_name,
                            credential=AzureKeyCredential(key))

# Define the search parameters
search_parameters = {
    "search_text": "*",  
    #"filter": filter_query,
    #"top": 1000,         # Adjust the number of results as per pagination
    "include_total_count": True
}

# Perform the search
results_data = search_client.search(**search_parameters)
data_list = []
for result in results_data:
    data_list.append(result)

df_data = pd.DataFrame(data_list)

print(df_data.head())
print(len(df_data))
print(df_data.uniquefieldname.value_counts()) --this shows duplicates only when replica is set to 3, when replica is set to1 -- no duplicates. There are no duplicates in the index which was validated. We can connect over teams too, I am part of Microsoft. Let me know if this is feasible.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

It seems like a bug in service behavior.

Please open a ticket for the service team to investigate.
