### ISSUE TITLE
azure-sdk-for-python CI step fails if yaml tag code block for a package contains suppressions with file names

### ISSUE THREAD

**Issue by kalbert312** [Azure/azure-sdk-for-python#34570]
**Describe the bug**
The python track 2 CI step is failing in my PR: [Add stable deployment stacks swagger by kalbert312 · Pull Request #27529 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/27529/checks?check_run_id=22178941427). Looking at the logs for the step, I see these lines:

`04:39:53.39 cmdout 	[automation_generate.sh]   "package-policy-2023-04": "fatal: invalid object name 'from'. from: policySetDefinitions.json",`

```
04:39:55.18 cmdout 	[automation_generate.sh]     raise Exception("Found files that do not set api_version: \n" + "\n".join(result))
04:39:55.18 cmdout 	[automation_generate.sh] Exception: Found files that do not set api_version: 
04:39:55.18 cmdout 	[automation_generate.sh] sdk/resources/azure-mgmt-resource/azure/mgmt/resource/policy/v2023_04_01/_configuration.py
04:39:55.18 cmdout 	[automation_generate.sh] sdk/resources/azure-mgmt-resource/azure/mgmt/resource/policy/v2023_04_01/aio/_configuration.py
```
I thought it might have been a problem with the auto rest configuration files in the PR, but after checking multiple times I'm not seeing anything obvious. This "policy 2023-04" package is included in the configuration I'm editing but is not the one I'm modifying.

After digging through the pipeline code, I believe it's either a bad autorest config setup or a bug in this code: https://github.com/Azure/azure-sdk-for-python/blob/fb60783c782bbb57f3c8e055bf4793bd1473bf52/tools/azure-sdk-tools/packaging_tools/sdk_generator.py#L132

This is the auto rest config that script is reading:
https://github.com/kalbert312/azure-rest-api-specs/blob/e4dd3e7e4d0402a81b2bef7dd754d3e46e8a8ab5/specification/resources/resource-manager/readme.md

It has supressions listed in the yaml tag code block containing the input files. If the config file is valid, then it looks like the pipeline automation should be only checking lines within the `input-file` array.

I need help determining what should be done here. I'm guessing the suppressions need to be moved to the existing yaml code block with directives for suppression in that file?

**Comment by kalbert312** [comment]
I tried a PR pipeline run via https://github.com/Azure/azure-rest-api-specs/pull/27529 after moving the policy package suppressions in the config file in https://github.com/kalbert312/azure-rest-api-specs/commit/dbf77986ab8a3192b2cc78298c0b606fad34ca65. It resolved the `"fatal: invalid object name 'from'. from: policySetDefinitions.json"` issue I was seeing but it's still failing: https://github.com/Azure/azure-rest-api-specs/pull/27529/checks?check_run_id=22253422334
Log snippet:
```
03:57:19.211 cmdout 	[automation_generate.sh] Successfully installed azure-mgmt-core-1.4.0 azure-mgmt-resource-23.1.0b2
03:57:19.310 cmdout 	[automation_generate.sh] Traceback (most recent call last):
03:57:19.310 cmdout 	[automation_generate.sh]   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
03:57:19.326 cmdout 	[automation_generate.sh]     return _run_code(code, main_globals, None,
03:57:19.326 cmdout 	[automation_generate.sh]   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/runpy.py", line 86, in _run_code
03:57:19.326 cmdout 	[automation_generate.sh]     exec(code, run_globals)
03:57:19.326 cmdout 	[automation_generate.sh]   File "/mnt/vss/_work/1/s/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/sdk_generator.py", line 391, in <module>
03:57:19.326 cmdout 	[automation_generate.sh]     generate_main()
03:57:19.327 cmdout 	[automation_generate.sh]   File "/mnt/vss/_work/1/s/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/sdk_generator.py", line 387, in generate_main
03:57:19.327 cmdout 	[automation_generate.sh]     main(args.generate_input, args.generate_output)
03:57:19.327 cmdout 	[automation_generate.sh]   File "/mnt/vss/_work/1/s/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/sdk_generator.py", line 338, in main
03:57:19.327 cmdout 	[automation_generate.sh]     check_api_version_in_subfolder(sdk_code_path)
03:57:19.327 cmdout 	[automation_generate.sh]   File "/mnt/vss/_work/1/s/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_utils.py", line 40, in check_api_version_in_subfolder
03:57:19.327 cmdout 	[automation_generate.sh]     raise Exception("Found files that do not set api_version: \n" + "\n".join(result))
03:57:19.327 cmdout 	[automation_generate.sh] Exception: Found files that do not set api_version: 
03:57:19.327 cmdout 	[automation_generate.sh] sdk/resources/azure-mgmt-resource/azure/mgmt/resource/policy/v2023_04_01/_configuration.py
03:57:19.327 cmdout 	[automation_generate.sh] sdk/resources/azure-mgmt-resource/azure/mgmt/resource/policy/v2023_04_01/aio/_configuration.py
03:57:19.369 cmdout 	[automation_generate.sh] [Generate] codegen done!!!
03:57:19.369 cmdout 	[automation_generate.sh] [Autorest]/mnt/vss/_work/1/s/azure-sdk-for-python_tmp/venv-sdk/auto_temp.json does not exist!!!Error happened during codegen
03:57:19.369 error C 	Script return with result [failed] code [1] signal [null] cwd [azure-sdk-for-python]: sh scripts/automation_generate.sh
```

**Comment by snarkywolverine** [comment]
@scbedd Is there any update here? This is blocking our service update and push for GA, which we are targeting for end of the month.

**Comment by msyyc** [comment]
Python SDK generation failure is caused by another PR https://github.com/Azure/azure-rest-api-specs/pull/24542/files#r1515369167 and we will fixed it soon.

**Comment by msyyc** [comment]
Fixed: 
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/031835a7-31d5-471f-a6e6-2e953859c161)
