### ISSUE TITLE
Get content of azure runbook is not working

### ISSUE THREAD

**Issue by shiva08** [Azure/azure-sdk-for-python#34595]
- **Package Name**:  azure-mgmt-automation
- **Package Version**:   1.0.0
- **Operating System**: Windows 11
- **Python Version**: 3.11.4

**Describe the bug**
According to [documentation](https://learn.microsoft.com/en-us/python/api/azure-mgmt-automation/azure.mgmt.automation.operations.runbookoperations?view=azure-python#azure-mgmt-automation-operations-runbookoperations-get-content), runbook.get_content returns IO object.
I tried using this method as suggested in [sample](https://github.com/Azure/azure-sdk-for-python/blob/f5cc8f35bdb16a024dfd6b160f6d1bcb9917ae05/sdk/automation/azure-mgmt-automation/generated_samples/get_runbook_content.py#L32), this gave an error 
```
raise DecodeError("Cannot deserialize content-type: {}".format(mime_type))
azure.core.exceptions.DecodeError: Cannot deserialize content-type: application/octet-stream
```

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ChenxiJiang333** [comment]
Hi @shiva08 Please use version 1.1.0b3 `pip install azure-mgmt-automation==1.1.0b3` and try.
Also, you can add the code below to get readable contents.
```
result = b"".join(r for r in response)
print(result)
```
