### ISSUE TITLE
Issue installing Azure package from pip on Anaconda 64bit 2.7

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-sdk-for-python#346]
----- Installing 'azure' -----

----- Installing 'azure' -----
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting azure
  Downloading azure-0.10.0.zip (130kB)
Collecting python-dateutil from https://pypi.python.org/packages/any/p/python-dateutil/python_dateutil-2.4.2-py2.py3-none-any.whl#md5=c817289a1d95a355cc088e2292791a77 (from azure)
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)
Collecting pyopenssl from https://pypi.python.org/packages/py2.py3/p/pyOpenSSL/pyOpenSSL-0.15.1-py2.py3-none-any.whl#md5=8ca6d74b42df1e3178e59e9b08746d77 (from azure)
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
Requirement already up-to-date: futures in c:\users\smortaz\appdata\local\continuum\anaconda\lib\site-packages (from azure)
Requirement already up-to-date: six>=1.5 in c:\users\smortaz\appdata\local\continuum\anaconda\lib\site-packages (from python-dateutil->azure)
Collecting cryptography>=0.7 from https://pypi.python.org/packages/cp27/c/cryptography/cryptography-0.8.2-cp27-none-win_amd64.whl#md5=ae66183a1073ea56ed3ac540a751c14f (from pyopenssl->azure)
  Downloading cryptography-0.8.2-cp27-none-win_amd64.whl (1.4MB)
Requirement already up-to-date: enum34 in c:\users\smortaz\appdata\local\continuum\anaconda\lib\site-packages (from cryptography>=0.7->pyopenssl->azure)
Requirement already up-to-date: cffi>=0.8 in c:\users\smortaz\appdata\local\continuum\anaconda\lib\site-packages (from cryptography>=0.7->pyopenssl->azure)
Collecting setuptools from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-15.1-py2.py3-none-any.whl#md5=b9eba737aec42a67c6e48ec42dacc07f (from cryptography>=0.7->pyopenssl->azure)
  Downloading setuptools-15.1-py2.py3-none-any.whl (501kB)
Requirement already up-to-date: pyasn1 in c:\users\smortaz\appdata\local\continuum\anaconda\lib\site-packages (from cryptography>=0.7->pyopenssl->azure)
Collecting pycparser from https://pypi.python.org/packages/source/p/pycparser/pycparser-2.12.tar.gz#md5=debde3e37af8566c95d2c0a0504397e7 (from cffi>=0.8->cryptography>=0.7->pyopenssl->azure)
  Downloading pycparser-2.12.tar.gz (297kB)
Installing collected packages: pycparser, setuptools, cryptography, pyopenssl, python-dateutil, azure
  Found existing installation: pycparser 2.10
    DEPRECATION: Uninstalling a distutils installed project (pycparser) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pycparser-2.10:
      Successfully uninstalled pycparser-2.10
  Running setup.py install for pycparser
    Build the lexing/parsing tables
  Found existing installation: setuptools 14.3
    Cannot remove entries from nonexistent file c:\users\smortaz\appdata\local\continuum\anaconda\lib\site-packages\easy-install.pth
----- Failed to install 'azure' -----

**Comment by crwilcox** [comment]
Shahrokh failed to get this to install on anaconda during a bash.  It seems anaconda installed versions and pip versions are fighting.  Rerun with -vv to get better output.

**Comment by crwilcox** [comment]
I had no issues running this command.  Can  you elaborate perhaps?  Maybe your environment isn't clean?

Fresh VM With:
- Windows 8.1
- VS2015
- Anaconda 64bit 2.7

cmd.exe.

C:\Users\crwilcox>pip -v install azure
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 38298
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting azure
  Getting page https://pypi.python.org/simple/azure/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/azure/ HTTP/1.1" 200 682
  URLs to search for versions for azure:
  * https://pypi.python.org/simple/azure/
  Getting page https://pypi.python.org/simple/azure/
  Analyzing links from page https://pypi.python.org/simple/azure/
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.1.zip#md5
=7aa19bebf7ed23c10044083854dde78e (from https://pypi.python.org/simple/azure/),
version: 0.1
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.10.0.zip#
md5=305b0036df5696d68369807835f554ae (from https://pypi.python.org/simple/azure/
), version: 0.10.0
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.2.zip#md5
=236942a4550dd15bb17b93fe4ffc10ac (from https://pypi.python.org/simple/azure/),
version: 0.2
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.5.1.zip#m
d5=19611915af7ef3b1998f321ed9474f15 (from https://pypi.python.org/simple/azure/)
, version: 0.5.1
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.5.2.zip#m
d5=010dad715018c2f48cf880fff540ed93 (from https://pypi.python.org/simple/azure/)
, version: 0.5.2
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.5.zip#md5
=17c76c2af06dddab6e93f834a3ae7edf (from https://pypi.python.org/simple/azure/),
version: 0.5
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.6.1.zip#m
d5=70612e541bb43e946432583971b6ec11 (from https://pypi.python.org/simple/azure/)
, version: 0.6.1
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.6.2.zip#m
d5=688f2a141c4c19e46c2bb0746bdaaac3 (from https://pypi.python.org/simple/azure/)
, version: 0.6.2
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.6.zip#md5
=5472666ee734defa880d82a512343828 (from https://pypi.python.org/simple/azure/),
version: 0.6
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.7.0.zip#m
d5=39ed72e8bc38c598bc0f357942e387e5 (from https://pypi.python.org/simple/azure/)
, version: 0.7.0
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.7.1.zip#m
d5=f2d25fe3be6faded9d5a68cb90ebdf51 (from https://pypi.python.org/simple/azure/)
, version: 0.7.1
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.8.0.zip#m
d5=5cb1eacad3746e7b518b663159354c06 (from https://pypi.python.org/simple/azure/)
, version: 0.8.0
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.8.0pr1.zi
p#md5=d15b6dbe9e39ee5679174782e9c3309d (from https://pypi.python.org/simple/azur
e/), version: 0.8.0pr1
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.8.1.zip#m
d5=02b012a31f295b73e7c14fab9ba2f5f0 (from https://pypi.python.org/simple/azure/)
, version: 0.8.1
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.8.2.zip#m
d5=4232761d4ba12cb1cb4b8772a1fdbe46 (from https://pypi.python.org/simple/azure/)
, version: 0.8.2
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.8.3.zip#m
d5=b9209cda4160de1a6ef0f08a9cf58375 (from https://pypi.python.org/simple/azure/)
, version: 0.8.3
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.8.4.zip#m
d5=5140a67f6ea62341e746c398179da344 (from https://pypi.python.org/simple/azure/)
, version: 0.8.4
    Found link https://pypi.python.org/packages/source/a/azure/azure-0.9.0.zip#m
d5=9616767cf45c1c00794624e2a0889f23 (from https://pypi.python.org/simple/azure/)
, version: 0.9.0
  Using version 0.10.0 (newest of versions: 0.10.0, 0.9.0, 0.8.4, 0.8.3, 0.8.2,
0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.2, 0.6.1, 0.6, 0.5.2, 0.5.1, 0.5, 0.2, 0.1)
  "GET /packages/source/a/azure/azure-0.10.0.zip HTTP/1.1" 200 130240
  Downloading azure-0.10.0.zip (130kB)
  Downloading from URL https://pypi.python.org/packages/source/a/azure/azure-0.1
0.0.zip#md5=305b0036df5696d68369807835f554ae (from https://pypi.python.org/simpl
e/azure/)
    100% |################################| 131kB 650kB/s
  Running setup.py (path:c:\users\crwilcox\appdata\local\temp\pip-build-nw0lva\a
zure\setup.py) egg_info for package azure
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info\azure.egg-info
    writing requirements to pip-egg-info\azure.egg-info\requires.txt
    writing pip-egg-info\azure.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\azure.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\azure.egg-info\dependency_links.txt

    writing manifest file 'pip-egg-info\azure.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\azure.egg-info\SOURCES.txt'
    writing manifest file 'pip-egg-info\azure.egg-info\SOURCES.txt'
  Source in c:\users\crwilcox\appdata\local\temp\pip-build-nw0lva\azure has vers
ion 0.10.0, which satisfies requirement azure
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in c:\
users\crwilcox\appdata\local\continuum\anaconda\lib\site-packages (from azure)
Requirement already satisfied (use --upgrade to upgrade): pyopenssl in c:\users\
crwilcox\appdata\local\continuum\anaconda\lib\site-packages (from azure)
Requirement already satisfied (use --upgrade to upgrade): futures in c:\users\cr
wilcox\appdata\local\continuum\anaconda\lib\site-packages (from azure)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in c:\users\c
rwilcox\appdata\local\continuum\anaconda\lib\site-packages (from python-dateutil
->azure)
Installing collected packages: azure
  Running setup.py install for azure
    Running command C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\python.ex
e -c "import setuptools, tokenize;__file__='c:\\users\\crwilcox\\appdata\\local\
\temp\\pip-build-nw0lva\\azure\\setup.py';exec(compile(getattr(tokenize, 'open',
 open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --rec
ord c:\users\crwilcox\appdata\local\temp\pip-tney_d-record\install-record.txt --
single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\azure
    copying azure\__init__.py -> build\lib\azure
    creating build\lib\azure\http
    copying azure\http\batchclient.py -> build\lib\azure\http
    copying azure\http\httpclient.py -> build\lib\azure\http
    copying azure\http\requestsclient.py -> build\lib\azure\http
    copying azure\http\winhttp.py -> build\lib\azure\http
    copying azure\http\__init__.py -> build\lib\azure\http
    creating build\lib\azure\servicebus
    copying azure\servicebus\servicebusservice.py -> build\lib\azure\servicebus
    copying azure\servicebus\__init__.py -> build\lib\azure\servicebus
    creating build\lib\azure\storage
    copying azure\storage\blobservice.py -> build\lib\azure\storage
    copying azure\storage\cloudstorageaccount.py -> build\lib\azure\storage
    copying azure\storage\queueservice.py -> build\lib\azure\storage
    copying azure\storage\sharedaccesssignature.py -> build\lib\azure\storage
    copying azure\storage\storageclient.py -> build\lib\azure\storage
    copying azure\storage\tableservice.py -> build\lib\azure\storage
    copying azure\storage\__init__.py -> build\lib\azure\storage
    creating build\lib\azure\servicemanagement
    copying azure\servicemanagement\schedulermanagementservice.py -> build\lib\a
zure\servicemanagement
    copying azure\servicemanagement\servicebusmanagementservice.py -> build\lib\
azure\servicemanagement
    copying azure\servicemanagement\servicemanagementclient.py -> build\lib\azur
e\servicemanagement
    copying azure\servicemanagement\servicemanagementservice.py -> build\lib\azu
re\servicemanagement
    copying azure\servicemanagement\sqldatabasemanagementservice.py -> build\lib
\azure\servicemanagement
    copying azure\servicemanagement\websitemanagementservice.py -> build\lib\azu
re\servicemanagement
    copying azure\servicemanagement\__init__.py -> build\lib\azure\servicemanage
ment
    running install_lib
    creating C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-package
s\azure
    creating C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-package
s\azure\http
    copying build\lib\azure\http\batchclient.py -> C:\Users\crwilcox\AppData\Loc
al\Continuum\Anaconda\Lib\site-packages\azure\http
    copying build\lib\azure\http\httpclient.py -> C:\Users\crwilcox\AppData\Loca
l\Continuum\Anaconda\Lib\site-packages\azure\http
    copying build\lib\azure\http\requestsclient.py -> C:\Users\crwilcox\AppData\
Local\Continuum\Anaconda\Lib\site-packages\azure\http
    copying build\lib\azure\http\winhttp.py -> C:\Users\crwilcox\AppData\Local\C
ontinuum\Anaconda\Lib\site-packages\azure\http
    copying build\lib\azure\http\__init__.py -> C:\Users\crwilcox\AppData\Local\
Continuum\Anaconda\Lib\site-packages\azure\http
    creating C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-package
s\azure\servicebus
    copying build\lib\azure\servicebus\servicebusservice.py -> C:\Users\crwilcox
\AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\servicebus
    copying build\lib\azure\servicebus\__init__.py -> C:\Users\crwilcox\AppData\
Local\Continuum\Anaconda\Lib\site-packages\azure\servicebus
    creating C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-package
s\azure\servicemanagement
    copying build\lib\azure\servicemanagement\schedulermanagementservice.py -> C
:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\servic
emanagement
    copying build\lib\azure\servicemanagement\servicebusmanagementservice.py ->
C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\servi
cemanagement
    copying build\lib\azure\servicemanagement\servicemanagementclient.py -> C:\U
sers\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\servicema
nagement
    copying build\lib\azure\servicemanagement\servicemanagementservice.py -> C:\
Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\servicem
anagement
    copying build\lib\azure\servicemanagement\sqldatabasemanagementservice.py ->
 C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\serv
icemanagement
    copying build\lib\azure\servicemanagement\websitemanagementservice.py -> C:\
Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\servicem
anagement
    copying build\lib\azure\servicemanagement\__init__.py -> C:\Users\crwilcox\A
ppData\Local\Continuum\Anaconda\Lib\site-packages\azure\servicemanagement
    creating C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-package
s\azure\storage
    copying build\lib\azure\storage\blobservice.py -> C:\Users\crwilcox\AppData\
Local\Continuum\Anaconda\Lib\site-packages\azure\storage
    copying build\lib\azure\storage\cloudstorageaccount.py -> C:\Users\crwilcox\
AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\storage
    copying build\lib\azure\storage\queueservice.py -> C:\Users\crwilcox\AppData
\Local\Continuum\Anaconda\Lib\site-packages\azure\storage
    copying build\lib\azure\storage\sharedaccesssignature.py -> C:\Users\crwilco
x\AppData\Local\Continuum\Anaconda\Lib\site-packages\azure\storage
    copying build\lib\azure\storage\storageclient.py -> C:\Users\crwilcox\AppDat
a\Local\Continuum\Anaconda\Lib\site-packages\azure\storage
    copying build\lib\azure\storage\tableservice.py -> C:\Users\crwilcox\AppData
\Local\Continuum\Anaconda\Lib\site-packages\azure\storage
    copying build\lib\azure\storage\__init__.py -> C:\Users\crwilcox\AppData\Loc
al\Continuum\Anaconda\Lib\site-packages\azure\storage
    copying build\lib\azure\__init__.py -> C:\Users\crwilcox\AppData\Local\Conti
nuum\Anaconda\Lib\site-packages\azure
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\http\batchclient.py to batchclient.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\http\httpclient.py to httpclient.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\http\requestsclient.py to requestsclient.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\http\winhttp.py to winhttp.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\http\__init__.py to __init__.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicebus\servicebusservice.py to servicebusservice.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicebus\__init__.py to __init__.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicemanagement\schedulermanagementservice.py to schedulermanage
mentservice.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicemanagement\servicebusmanagementservice.py to servicebusmana
gementservice.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicemanagement\servicemanagementclient.py to servicemanagementc
lient.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicemanagement\servicemanagementservice.py to servicemanagement
service.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicemanagement\sqldatabasemanagementservice.py to sqldatabasema
nagementservice.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicemanagement\websitemanagementservice.py to websitemanagement
service.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\servicemanagement\__init__.py to __init__.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\storage\blobservice.py to blobservice.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\storage\cloudstorageaccount.py to cloudstorageaccount.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\storage\queueservice.py to queueservice.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\storage\sharedaccesssignature.py to sharedaccesssignature.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\storage\storageclient.py to storageclient.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\storage\tableservice.py to tableservice.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\storage\__init__.py to __init__.pyc
    byte-compiling C:\Users\crwilcox\AppData\Local\Continuum\Anaconda\Lib\site-p
ackages\azure\__init__.py to __init__.pyc
    running install_egg_info
    running egg_info
    creating azure.egg-info
    writing requirements to azure.egg-info\requires.txt
    writing azure.egg-info\PKG-INFO
    writing top-level names to azure.egg-info\top_level.txt
    writing dependency_links to azure.egg-info\dependency_links.txt
    writing manifest file 'azure.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'azure.egg-info\SOURCES.txt'
    writing manifest file 'azure.egg-info\SOURCES.txt'
    Copying azure.egg-info to C:\Users\crwilcox\AppData\Local\Continuum\Anaconda
\Lib\site-packages\azure-0.10.0-py2.7.egg-info
    running install_scripts
    writing list of installed files to 'c:\users\crwilcox\appdata\local\temp\pip
-tney_d-record\install-record.txt'
Successfully installed azure-0.10.0
Cleaning up...

**Comment by stxlvt** [comment]
See https://github.com/pypa/pip/issues/2751
