### ISSUE TITLE
"context" parameter automatically set back to default value when using the python sdk

### ISSUE THREAD

**Issue by johannesgoldbeck** [Azure/azure-sdk-for-python#34623]
### Type of issue

Code doesn't work

### Description

I am managing my Azure AI skillset via the python SDK. When using the EntityRecognitionSkill, I set the context parameter of the class to "/document/pages/*", since I want the Entity Extraction for each page of the document.
When I use the create_or_update_skillset method of the SearchIndexerClient class to update my skillset it will throw no errors, but the context parameter of the Entity Recognition Skill will be set back to its default value "/document", which I can see in the json of the skillset displayed in the Azure Portal. I have to change it manually in the Portal, s.t. the skill will be executed without error when indexing.

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.indexes.models.entityrecognitionskill?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-search-documents/azure.search.documents.indexes.models.EntityRecognitionSkill.yml

### Document Version Independent Id

3a3ff14f-2b0e-c83f-0e51-f48136ff7a15

### Article author

@lmazuel

### Metadata

* ID: d674ff86-de21-e3e3-c363-96b5e35bd829

**Comment by kashifkhan** [comment]
Thank you for the feedback @johannesgoldbeck . We will investigate and get back to you asap. 

Could you also provide some sample code that can help repro the issue ?

**Comment by johannesgoldbeck** [comment]
this my skill:

EntityRecognitionSkill(categories=["Organization", "Location", "DateTime"],
                            default_language_code="de",
                            context="/document/pages/*", # changes to default /document in the cloud
                            minimum_precision=0.5,
                            inputs=[{"name": "text",
                                        "source": "/document/pages/*"},
                                    {"name": "languageCode",
                                        "source": "/document/languageCode_clean"}],
                            outputs=[{"name": "organizations",
                                        "targetName": "entity_organizations"},
                                        {"name": "locations",
                                        "targetName": "entity_locations"},
                                        {"name": "dateTimes",
                                        "targetName": "entity_dateTimes"}]


this my request to create/update the skillset:

indexer_client = SearchIndexerClient(endpoint,
                                             AzureKeyCredential(key))
skillset = SearchIndexerSkillset(name=name,
                                        description=
                                        "Some document enrichment",
                                        cognitive_services_account={
                                        "@odata.type":
                                        "#Microsoft.Azure.Search.CognitiveServicesByKey",
                                        "key": cog_service_key
                                        },
                                        skills=skills
                                        )
indexer_client.create_or_update_skillset(skillset)

**Comment by johannesgoldbeck** [comment]
This my skill:
![image](https://github.com/Azure/azure-sdk-for-python/assets/49227207/2aa78f18-551c-4798-ac0c-501fe58ade5f)

This my Request to Create/Update the skillset:
![image](https://github.com/Azure/azure-sdk-for-python/assets/49227207/743d40f3-b49c-430d-8b89-c8ba9e51c0b8)

**Comment by johannesgoldbeck** [comment]
Yea thank YOU for the assistance when it seems like I found a super obvious bug in your code I am paying a shit ton of money to use. I was just wasting ages looking into my code to find the mistake because of which I could not properly deploy the service, but ok.

Can you tell me, when your fix will be deployed?
