### ISSUE TITLE
How to generate .ocr.json files programatically?

### ISSUE THREAD

**Issue by ai-learner-00** [Azure/azure-sdk-for-python#34654]
**Is your feature request related to a problem? Please describe.**
I didn't find the code to generate `.ocr.json` files. This [sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/sample_convert_to_and_from_dict.py) only produces the result part, but there seems to be additional fields.

```json
{
	"status": "succeeded",
	"createdDateTime": "2023-03-24T16:53:24Z",
	"lastUpdatedDateTime": "2023-03-24T16:53:29Z",
	"analyzeResult": {
		"apiVersion": "2023-02-28-preview",
		"modelId": "prebuilt-layout",
		"stringIndexType": "utf16CodeUnit",
		"content":
```
[sample_form](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_forms/classifier/IRS-1040-A/train/IRS_1040_1_01.pdf.ocr.json)

**Describe the solution you'd like**
A [GetRawResponse](https://learn.microsoft.com/en-us/answers/questions/1379003/formsrecognizer-how-to-create-ocr-json-files-progr) method to get the entire json.

**Additional context**
These files are needed to train a classifier.

**Comment by YalinLi0312** [comment]
@ai-learner-00 Thanks for your contact! You can get raw response by passing `callback()`, here's the test you can follow: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts.py#L203-L223
