### ISSUE TITLE
Include FeaturesMode in Azure-AI-Search SDK

### ISSUE THREAD

**Issue by mohanajuhi166** [Azure/azure-sdk-for-python#34651]
**Is your feature request related to a problem? Please describe.**
The preview REST API for Azure AI search provides a parameter called "featuresMode" 
that can provide more detail about relevance at the field level. **FeaturesMode** you can get information about individual fields, as expressed in a @search.features structure.

**Describe the solution you'd like**
Added as part of the search functionality here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/azure/search/documents/_search_client.py

**Comment by xiangyan99** [comment]
Thank you for the feedback.

Could you share where you find the `featuresMode` feature?

**Comment by mohanajuhi166** [comment]
@xiangyan99  https://learn.microsoft.com/en-us/rest/api/searchservice/preview-api/search-documents

**Comment by xiangyan99** [comment]
It is missing in the swagger https://github.com/Azure/azure-rest-api-specs/tree/main/specification/search/data-plane/Azure.Search.

Thanks for catching it.

Please open an issue in https://github.com/Azure/azure-rest-api-specs repo and we will have it added.

**Comment by mohanajuhi166** [comment]
@xiangyan99 raised https://github.com/Azure/azure-rest-api-specs/issues/28170

**Comment by mohanajuhi166** [comment]
@xiangyan99 is it possible if we can create a PR to add this feature in the SDK?

**Comment by xiangyan99** [comment]
@mohanajuhi166 Thanks for the follow-up. 

The SDK is based on the swagger.

Unfortunately, currently, we can do nothing on the client SDK side until the swagger is updated.

Please feel free to reopen the issue or create a new one when the swagger is updated.
