### ISSUE TITLE
Document intelligence layout-model doesn't detect tables for .xlsx

### ISSUE THREAD

**Issue by hamer101** [Azure/azure-sdk-for-python#34687]
- **Package Name**: azure-ai-documentintelligence
- **Package Version**: 1.0.0b1

No tables are detected for a .xlsx file - the poller's result field of `tables` remains empty. 

Although I suspected loosely written tables might not get detected, I assumed that areas that have been declared as "tables" in the excel application will get extracted.

The analyzed .xlsx file contained one such defined table, along with few subtotal fields. Code used:

```
with open('/tmp/example.xlsx','rb') as f:
    poller = document_intelligence_client.begin_analyze_document(
        model_id="prebuilt-layout",
        analyze_request=f, 
        content_type="application/octet-stream"
    )
    form_recognizer_results_markdown = poller.result()
print(form_recognizer_results_markdown.tables)
```

I was about to consider it a feature request, but given it some thought, it deviates quite a bit from behavior I expected :)

**Comment by YalinLi0312** [comment]
@hamer101 Thanks for your contact, we'll investigate asap!

**Comment by YalinLi0312** [comment]
Hi @hamer101 , unfortunately we are not supporting the feature so far, it is saying "Table is not supported if the input file is XLSX." in our doc([link](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-layout?view=doc-intel-4.0.0#tables)). I'll tag the service team to aware your request, thanks!

**Comment by maltenlz** [comment]
Is there any update on this? This feature be very appreciated!

**Comment by YalinLi0312** [comment]
Add @bojunehsu to bring more attention on this feature request on layout-model.

**Comment by bojunehsu** [comment]
@hamer101 Thanks for the feedback.  Can you please share more information about the intended use scenarios to help us prioritize the work?  Thanks.

**Comment by hamer101** [comment]
I wanted to feed a xlsx to a LLM via a pipeline that already deals with tables by `tables` parameter of layout-model's result.

**Comment by bojunehsu** [comment]
@hamer101 Thanks for sharing the scenario.  We will add this request to our backlog.

**Comment by YalinLi0312** [comment]
@hamer101 Since this is not an SDK issue, will close it. Thanks

**Comment by clausagerskov** [comment]
@bojunehsu Where can we track this feature request?

**Comment by MyaLeoni** [comment]
We have the same problem. We want to get back a table if there is a table in my excel sheet. Where can I get direct support to this request?

**Comment by bojunehsu** [comment]
We don't yet have direct support for this capability.  A suboptimal workaround is to print spreadsheet to PDF first if the tables fit within a single page.

**Comment by clausagerskov** [comment]
> We don't yet have direct support for this capability. A suboptimal workaround is to print spreadsheet to PDF first if the tables fit within a single page.

Do you have this in a roadmap somewhere?

**Comment by mjvdvlugt** [comment]
Same here! Would be nice to keep one generic workflow for all document types.

**Comment by MyaLeoni** [comment]
We talked to Microsoft and xlsx Support is on the road map. But if it takes 3 oder 9 month we don’t know!
