### ISSUE TITLE
Update `ml` docker test files

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#34700]
Update:

- sdk/ml/azure-ai-ml/tests/test_configs/components/additional_includes/docker/DockerFile
- sdk/ml/azure-ai-ml/tests/test_configs/internal/additional_includes/docker/DockerFile
- sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/my_exp/docker/DockerFile

To `mariner` or the like.

This is due to this [warning](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3570318&view=logs&j=bc38e8b8-e027-53cb-48e7-2adbd1070eca&t=e946b54a-a418-51a5-c9d8-3ba4f53f489a) that is now a fact of life due to the `1ES` transition.

On 3/31 this warning will become a hard error.

**Comment by elliotzh** [comment]
fixing in this PR: https://github.com/Azure/azure-sdk-for-python/pull/34825

**Comment by kdestin** [comment]
Resolved by #34825
