### ISSUE TITLE
I am unable to create events using python django

### ISSUE THREAD

**Issue by Rithwik-Bojja** [Azure/azure-sdk-for-python#34716]
**Describe the bug**

I am unable  to create events using python django

myapp/views.py

```
import logging
from opentelemetry import trace

class SomeView(LoginRequiredMixin, TemplateView):
    login_required = True
    template_name = "myapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        tracer = trace.get_tracer(__name__)

        with tracer.start_as_current_span("SomeView") as span:
            if span.is_recording():
                span.set_attribute("user.id", self.request.user.id)
                span.set_attribute("user.email", self.request.user.email)

                span.add_event("log", {
                    "log.severity": "info",
                    "log.message": "Mark was here.",
                    "user.id": self.request.user.id,
                    "user.email": self.request.user.email,
                })

                span.add_event("This is a span event")
                logging.getLogger().error("This is a log message")

        context['something'] = SomeThing.objects.all()
        
        return context
```

To get more information on refer this[ SO-Thread](https://stackoverflow.com/questions/78129823/python-opentelemetry-events-in-application-insights)

**Expected behavior**

![enter image description here](https://i.imgur.com/KghlGzj.png)

**Comment by scoopseven** [comment]
I'm experiencing this as well: https://stackoverflow.com/questions/78129823/python-opentelemetry-events-in-application-insights

**Comment by Rithwik-Bojja** [comment]
Thnaks scoopseven, opentelemetry-api==1.23.0

**Comment by xiangyan99** [comment]
Thanks for the information.

This repo is for Azure SDK libraries.

For opentelemetry-api library, maybe https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-api is the right repo.
