### ISSUE TITLE
from azure.core.exceptions import HttpResponseError

### ISSUE THREAD

**Issue by sfrancesco1** [Azure/azure-sdk-for-python#34715]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-core/azure.core?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-core/azure.core.yml

### Document Version Independent Id

a946bf9d-eb2a-cbd3-3f44-067543ca0177

### Article author

@lmazuel

### Metadata

* ID: 868127f5-1be7-8a8e-acda-e40f53d86c7b

**Comment by kashifkhan** [comment]
Hi @sfrancesco1, can you provide some more details around the issue you are facing, with sample code, python version etc. This will help us assist you better.
