### ISSUE TITLE
AzureMonitorLogExporter breaks if the LoggingHandler is added to the root logger

### ISSUE THREAD

**Issue by johschmidt42** [Azure/azure-sdk-for-python#34787]
- **azure-monitor-opentelemetry-exporter**: 
- **1.0.0b23**: 
- **macOS 14.3.1 (23D60)**:
- **3.10.13**: 

**Describe the bug**
The example for the AzureMonitorLogExporter: [Export Hello World Log](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter#export-hello-world-log) fails if the `LoggingHandler` is added to the **root logger** (maybe recursive behaviour?). It works fine if the `LoggingHandler` is added to a **named logger**.

**To Reproduce**
1. Install Requirements
```shell
asgiref==3.7.2
azure-core==1.30.1
azure-core-tracing-opentelemetry==1.0.0b11
azure-monitor-opentelemetry==1.3.0
azure-monitor-opentelemetry-exporter==1.0.0b23
certifi==2024.2.2
charset-normalizer==3.3.2
Deprecated==1.2.14
fixedint==0.1.6
idna==3.6
importlib-metadata==6.11.0
isodate==0.6.1
msrest==0.7.1
oauthlib==3.2.2
opentelemetry-api==1.23.0
opentelemetry-instrumentation==0.44b0
opentelemetry-instrumentation-asgi==0.44b0
opentelemetry-instrumentation-dbapi==0.44b0
opentelemetry-instrumentation-django==0.44b0
opentelemetry-instrumentation-fastapi==0.44b0
opentelemetry-instrumentation-flask==0.44b0
opentelemetry-instrumentation-psycopg2==0.44b0
opentelemetry-instrumentation-requests==0.44b0
opentelemetry-instrumentation-urllib==0.44b0
opentelemetry-instrumentation-urllib3==0.44b0
opentelemetry-instrumentation-wsgi==0.44b0
opentelemetry-resource-detector-azure==0.1.3
opentelemetry-sdk==1.23.0
opentelemetry-semantic-conventions==0.44b0
opentelemetry-util-http==0.44b0
packaging==24.0
pip==23.3.1
requests==2.31.0
requests-oauthlib==1.4.0
setuptools==68.2.2
six==1.16.0
typing_extensions==4.10.0
urllib3==2.2.1
wheel==0.41.2
wrapt==1.16.0
zipp==3.18.1
```
2. Run the example [Export Hello World Log](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter#export-hello-world-log).

```python
import logging
import os
import sys

from azure.monitor.opentelemetry.exporter import AzureMonitorLogExporter
from opentelemetry._logs import set_logger_provider
from opentelemetry.sdk._logs import LoggerProvider, LoggingHandler
from opentelemetry.sdk._logs._internal.export import SimpleLogRecordProcessor

logger_provider = LoggerProvider()
set_logger_provider(logger_provider)
exporter = AzureMonitorLogExporter(
    connection_string=os.environ["APPLICATIONINSIGHTS_CONNECTION_STRING"]
)
logger_provider.add_log_record_processor(SimpleLogRecordProcessor(exporter))

# fails
root_logger = logging.getLogger()
root_logger.addHandler(LoggingHandler())
root_logger.addHandler(logging.StreamHandler(stream=sys.stdout))
root_logger.setLevel(logging.NOTSET)

my_logger = logging.getLogger(__name__)
my_logger.setLevel(logging.INFO)
my_logger.warning("Hello World!")

# works
my_logger = logging.getLogger(__name__)
my_logger.addHandler(LoggingHandler())
my_logger.addHandler(logging.StreamHandler(stream=sys.stdout))
my_logger.setLevel(logging.INFO)
my_logger.warning("Hello World!")

```

Output:

```shell
...
A body is sent with the request
https://westeurope-5.in.applicationinsights.azure.com:443 "POST //v2.1/track HTTP/1.1" 200 None
Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json; charset=utf-8'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 15 Mar 2024 20:21:18 GMT'
Envelopes could not be exported and are not retryable: maximum recursion depth exceeded while calling a Python object.
Envelopes could not be exported and are not retryable: maximum recursion depth exceeded while calling a Python object.
Transmission succeeded: Item received: 1. Items accepted: 1
Starting new HTTPS connection (18): westeurope-5.in.applicationinsights.azure.com:443

Process finished with exit code 137 (interrupted by signal 9:SIGKILL)
```

**Expected behavior**
It should be possible to add the logging handler to the root logger.

**Comment by lzchen** [comment]
@johschmidt42 

The azure monitor exporter and distro were designed to be used with namespaced loggers, since the SDKs themselves use the python logger to log diagnose log messages. If you add the handler to the root logger, those log messages will also be tracked and then exported, which will generate more log messages, and then those will be tracked and exported and so on...which is why you are getting recursive errors.

**Comment by johschmidt42** [comment]
Thanks for clarifying this @lzchen. If the root logger is not supposed to be used, how would one go about sending the logs to Application Insights from imported libraries? Adding the handlers to every imported library is possible but very impractical.

Usually all libraries/modules have their own named logger and propagate their logs to the root logger (including the logger used for the application). Only the root logger contains the handlers. This guarantees that important logs will be handled at the top level.

**Comment by johschmidt42** [comment]
@summahto
A namespaced logger is just a named logger:

`logging.getLogger("my_logger")`

If you don't provide a name, you'll get the root logger in Python.

The docs actually explain why and when to use the Azure Monitor Distro or the Exporter directly. First one is a one stop shop solution whereas the second gives you more flexibility. If you take a look inside at the create_azure_monitor function, you'll notice that it just sets up the Exporter.

**Comment by lzchen** [comment]
@summahto 

@johschmidt42 explained it perfectly, the distro is for a one api solution with simple configuration, whereas the exporter is for more complex telemetry scenarios where we give the user more control over the individual components.

>  If the root logger is not supposed to be used, how would one go about sending the logs to Application Insights from imported libraries?

@johschmidt42 

That's a great question. I am assuming you are trying to collect logs from imported libraries that are not created by you or not in your control (otherwise, you can just namespace the libraries appropriately and just use one namespace that is a prefix of all of your namespaces). Collecting ALL logs from every library is a not a common telemetry scenario. Like you mentioned, add the handler to every namespaced logger in each library you want to track would work but very tedious. With that being said, adding to the root handler technically possible. The only reason you are getting recursion errors is because you are using the `SimpleLogRecordProcessor` which exports logs immediately as they are collected. Our documentation recommends using the `BatchLogRecordProcessor`, which queues up the log records to be exported as a batch using a worker thread. This way, you won't get spammed with log record exports as they will be exporting on a timer instead. Now, this won't solve the recursion problem, as we still send logs from the exporter on export, which will then be collected by the logging handler and then exported again. What you can do is setup your logging handler as to IGNORE logs sent from the SDK library. You can do this by matching the name with `azure.monitor.` and adding a custom processor.

```python
# Replace BatchLogRecordProcessor with this custom processor

class CustomBatchLogRecordProcessor(BatchLogRecordProcessor):
     
   def emit(self, log_data: LogData):
        if log_data.instrumentation_scope.name.startswith("azure.monitor"):
            pass
        else:
            super().emit(log_data)

## IN YOUR CODE
...
get_logger_provider().add_log_record_processor(CustomBatchLogRecordProcessor(exporter, schedule_delay_millis=5000))

...
```

You can also achieve similar behavior if you use Python logging [filter](https://docs.python.org/3/library/logging.html#filter-objects) and apply the same logic.

**Comment by johschmidt42** [comment]
I think it wouldn't harm to add some comments about this topic (root handler vs named logger) in the documentation, what do you think? @lzchen

**Comment by lzchen** [comment]
@johschmidt42 

I think that would be a great idea. Feel free to open a PR if you see it fitting somewhere appropriate.

**Comment by summahto** [comment]
@johschmidt42 @lzchen ,

How would you get to know the namespace for the dependencies you have added? I am assuming that have a namespace for your application and you are propagating logs from your submodules to this namespace?

Can you give an example for this?

**Comment by johschmidt42** [comment]
@summahto 
> How would you get to know the namespace for the dependencies you have added?

If you're in control of the modules/libraries, you decide on the name for these loggers, e.g.

```python
logger = logging.getLogger("my_module")
``` 

but if the modules/libraries are outside of your control, e.g. third party libraries installed from PyPI, then what you usually see, is the following convention:

```python
logger = logging.getLogger(__name__)
```

If that's not the case, you can try to import the logger of a library to get it's name. (Note that it's not always straight forward to find the loggers in a module. Sometimes there are no loggers defined.)

```python
from httpx._client import logger as httpx_logger # there is a second one in httpx._config
from dotenv.main import logger as dotenv_logger

print(httpx_logger.name)
print(dotenv_logger.name)
```

This outputs:

```shell
> httpx
> dotenv.main
```

> I am assuming that have a namespace for your application and you are propagating logs from your submodules to this namespace?

In the example I gave, logs from other loggers do not propagate to the application logger. Instead, I add the `LoggingHandler` to all loggers of interest to me. That way these library logs are treated the same as my application logs, because they have the same handler.

**Comment by summahto** [comment]
@johschmidt42 ,

Thanks for the explanation. 
Few questions though:

- The ```LoggingHandler()```  from the package ```from opentelemetry.sdk._logs``` : It is being added to all the loggers you are creating. Why so ? 
```py
my_logger.addHandler(LoggingHandler())
my_logger.addHandler(logging.StreamHandler(stream=sys.stdout))
```

- I was trying to do all the configuration through a yaml config file. Is it possible to do it through an external config file? I am not sure if we can get use Opentelemetry's LoggerProvider and LoggerHandler in the config file [here](https://github.com/Azure/azure-sdk-for-python/issues/34830) , though ?

**Comment by johschmidt42** [comment]
> The LoggingHandler() from the package from opentelemetry.sdk._logs : It is being added to all the loggers you are creating. Why so ?

Some modules/libraries I use in an application should send logs to Application Insights. For this, the handler `LoggingHandler` needs be attached to a logger to receive logs. Since modules/libraries use different loggers than my app (different named loggers), I have two options:
- add the `LoggingHandler` (& other handlers) to every module logger I'm interested in
- add the `LoggingHandler` only to the root logger but filter out some logs (for example the ones in azure.monitor to prevent recurvise logging). Named loggers propagate their logs to the root logger, so the handlers (e.g. `LoggingHandler`) in the root logger will be handling all logs.

I think both approaches are fine. It probably depends on how you like to do things. On one hand, you must explicitely update some named loggers. So you might forget some. But on the other hand, if you allow all logs that are propagated to the root logger to be handled by your handlers, you must think about filtering some of them to not flood your backend with logs.

**Comment by RollerKnobster** [comment]
Chiming in late, but based on the discussion above, does it make sense to extend the README for the exporter, which currently suggests adding a handler to the root logger in most of the examples? ([link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/README.md#export-hello-world-log)).

**Comment by johschmidt42** [comment]
Opened a PR where I extended the README.md for the exporter @RollerKnobster. Feel free to comment. Thanks for the reminder by the way.

**Comment by RollerKnobster** [comment]
@johschmidt42 Legend!

**Comment by xiangyan99** [comment]
@lzchen has this issue been solved?

**Comment by lzchen** [comment]
Since the original issue has been resolved and the appropriate documentation has been merged for better guidance for users, I believe this can be closed.
