### ISSUE TITLE
configure_azure_monitor failed to resolve 'westus-0.in.applicationinsights.azure.com'

### ISSUE THREAD

**Issue by yooontheearth** [Azure/azure-sdk-for-python#34804]
- **Package Name**:  azure-monitor-opentelemetry
- **Package Version**: 1.3.0
- **Operating System**: python:3.11-slim on Docker on Azure App Service
- **Python Version**: 3.11.8

**Describe the bug**
I ran the following code on Azure App Service, but it gives me the error  `Retrying due to server request error: <urllib3.connection.HTTPSConnection object at 0x72d28cec0dd0>: Failed to resolve 'westus-0.in.applicationinsights.azure.com' ([Errno -5] No address associated with hostname).`. Also there is no logs on Application Insights.

```
from azure.monitor.opentelemetry import configure_azure_monitor 
from opentelemetry import trace

configure_azure_monitor(
   connection_string="<Connection string>"
)

tracer = trace.get_tracer("test.tracer")
with tracer.start_as_current_span("test.span") as span:
    print("hello, telemetry span")
    span.set_attribute("span_test_string", "Here is a message in a span")
```

**Additional context**
What I don't get is that my App Service region is in Japan East (IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/), but according to the error message, it looks like it tying to access to westus-0.in.applicationinsights.azure.com.

**Comment by lzchen** [comment]
Please try setting an env var `APPLICATIONINSIGHTS_STATSBEAT_DISABLED_ALL` to `True` and see if you issue still persists.

**Comment by yooontheearth** [comment]
@lzchen That did the trick. Thank you.
