### ISSUE TITLE
List snapshots and list disk API call failed if any other api hits at same time 

### ISSUE THREAD

**Issue by pavanpawar4591** [Azure/azure-sdk-for-python#34821]
- **Package Name**: azure-mgmt-compute
- **Package Version**: 29.1.0 and 10.3.0.1
- **Operating System**: RHEL
- **Python Version**: 10.9.18

**Describe the bug**
We are listing the disk and snapshots using computre client and it faild to list with error

 ", (InvalidResourceType) The resource type 'disks' could not be found in the namespace 'Microsoft.Compute' for api version '2020-06-01'. The supported api-versions are '2017-03-30,2018-04-01,2018-06-01,2018-09-30,2019-03-01,2019-07-01,2019-11-01'..Code: InvalidResourceType.Message: The resource type 'disks' could not be found in the namespace 'Microsoft.Compute' for api version '2020-06-01'. The supported api-versions are '2017-03-30,2018-04-01,2018-06-01,2018-09-30,2019-03-01,2019-07-01,2019-11-01'"

**To Reproduce**
1. call list snapshot API or List disk API 
2. during the pagination call  the other api call of the compute client hits

**Expected behavior**
we 100+ snapshots in subscription and when we enable the debug logs we can see pagination logic is working . idealy nextLink:"" have proper api versio i.e. 2019-07-01 but at same time some other compute clinet api hits with version 2020-06-01 and that cause the isssue 

**Screenshots**
<img width="491" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/9477929/ede6d787-2a2a-4c42-8d81-88c810e636e4">

**Additional context**
we suspect issue is introduce from this PR https://github.com/Azure/azure-sdk-for-python/pull/26327
compute version = 28.0.0

on compute client =27.2.0 issue not reproduced 

here are some code changes to pick api version from context not from nextLink

**Comment by msyyc** [comment]
it is fixed in https://pypi.org/project/azure-mgmt-compute/30.6.0/
