### ISSUE TITLE
Vector Embeddings Wrongly Described as High-Dimensional Compared with Keyword Vectors: Incorrect, They are Low-Dimensional.

### ISSUE THREAD

**Issue by strahl2e** [Azure/azure-sdk-for-python#34832]
### Type of issue

Other (describe below)

### Description

Wrongly states: " It represents documents and queries as vectors in a high-dimensional space called an embedding" when comparing vector search using embeddings to keyword search. This is wrong. A keyword search represents documents as very high-dimensional vectors and a vector embedding creates a low-dimensional rich representation of those high-dimensional keyword vectors. Should say " It represents documents and queries as vectors in a [low]-dimensional space called an embedding"

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/search-documents-readme?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/search-documents-readme.md

### Document Version Independent Id

45b881bd-1574-6b25-c48f-93859f4b3d4a

### Article author

@azure-sdk

### Metadata

* ID: df132c46-f26a-665f-bce4-2a365560448e 
* Service: **cognitive-search**

**Comment by xiangyan99** [comment]
@HeidiSteen Could you help to take a look?

**Comment by HeidiSteen** [comment]
@robertklee can you respond?

**Comment by robertklee** [comment]
@strahl2e thank you for submitting the correction. You are correct. I think it was originally written from the perspective that compared to everyday 3d world, 1536 dimensions is high. But in terms of information theory, it is concentrating information and reducing dimensionality. I propose the following correction that addresses the needs of both data scientists and non-expert search users while being technically correct.

@HeidiSteen / @farzad528  as a fyi for messaging. Could we also update https://learn.microsoft.com/en-us/azure/search/vector-search-overview and some of the other conceptual docs to clarify this technicality?

> It represents documents, queries, and other data by converting them into vectors within a specialized space known as an embedding. This space is a highly abstract, rich, compact representation of the original content compared to traditional methods like keyword searches. Under the hood of an embedding model, it maps data tokens from a sparse higher-dimensional space into a rich low-dimension space where similar data are close together via a selected similarity metric. Due to the dimensionality far exceeding real-world 3-dimensional space, visualizing the embedding space is often both extremely difficult and unnecessary for search applications.

**Comment by HeidiSteen** [comment]
I can update the vector search overview.  I'll also update the SDK docs that are the subject of this issue, but heads up that the SDK docs are on a different publishing schedule so it might take a week or two before edits are live.

**Comment by robertklee** [comment]
#Close

**Comment by robertklee** [comment]
@xiangyan99 could you please close this as "issue addressed"

**Comment by xiangyan99** [comment]
issue addressed.
