### ISSUE TITLE
azure-mgmt-nspkg 3.0.1 breaks installation of azure>=2.0.0,<3

### ISSUE THREAD

**Issue by manneorama** [Azure/azure-sdk-for-python#3485]
Recently (11 minutes at the time of writing) azure-mgmt-nspkg 3.0.1 was released (https://pypi.org/project/azure-mgmt-nspkg/#history). I just happened to be updating a virtualenv shortly after and was met by the following error:

`
Collecting azure-nspkg>=2.0.0 (from azure-batch~=3.0.0->azure<3,>=2.0.0->gatekeeper>=0.6.0->-r req.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/1e/0b/41cf166cb9b3fcaf24d68c59a6358e05ab974117bbe7368c86689b9c127c/azure-nspkg-3.0.1.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/azure_nspkg.egg-info
    writing pip-egg-info/azure_nspkg.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/azure_nspkg.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/azure_nspkg.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/azure_nspkg.egg-info/SOURCES.txt'
    error: package directory 'azure' does not exist
`

Setting a requirement on azure-mgmt-nspkg<3.0.1 in the line before azure>=2.0.0,<3 solves the issue. For technical reasons, we depend on being able to install azure<3, is this no longer supported and if so, does this workaround bring any unintended side effects to the best of your knowledge?

**Comment by kwirkykat** [comment]
+1 this also just happened to all my tests that were previously working
@lmazuel
```
Downloading https://files.pythonhosted.org/packages/45/2d/1cd3391bf8a46402aac5d68590782a9993eb507ece0716ef8afb30a3f4df/azure-mgmt-nspkg-3.0.1.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\azure_mgmt_nspkg.egg-info
    writing requirements to pip-egg-info\azure_mgmt_nspkg.egg-info\requires.txt
    writing pip-egg-info\azure_mgmt_nspkg.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\azure_mgmt_nspkg.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\azure_mgmt_nspkg.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\azure_mgmt_nspkg.egg-info\SOURCES.txt'
    error: package directory 'azure\mgmt' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\appveyor\appdata\local\temp\1\pip-install-l7geut\azure-mgmt-nspkg\
Command exited with code 1
```

**Comment by lmazuel** [comment]
Could you all confirm this is Python 2 and is fixed now?

**Comment by lmazuel** [comment]
Was closed by github actually on merging the PR for 3.0.2. If you still experience the issue once 3.0.2 is on PyPI, please still comment here.
Thank you,

**Comment by kwirkykat** [comment]
@lmazuel It's fixed for me now. Thanks!
Yes, all my tests were running Python 2.7
