### ISSUE TITLE
Incorrect dependency version on typing-extensions in azure-servicebus

### ISSUE THREAD

**Issue by YaroBear** [Azure/azure-sdk-for-python#34868]
- **Package Name**:  azure-servicebus
- **Package Version**: 7.12.1
- **Operating System**: Windows 10
- **Python Version**: 3.11.3

**Describe the bug**
The dependency on typing-extensions is incorrect.  https://github.com/Azure/azure-sdk-for-python/blob/006b24954eee7efdb0fc919123989507191d8e1d/sdk/servicebus/azure-servicebus/setup.py#L71
It's currently set to >= 4.0.1, but should be >= 4.6.0 because the `Buffer` object used on the following line was not [introduced until 4.6.0](https://typing-extensions.readthedocs.io/en/latest/index.html#abstract-base-classes)

https://github.com/Azure/azure-sdk-for-python/blob/006b24954eee7efdb0fc919123989507191d8e1d/sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_encode.py#L35

![image](https://github.com/Azure/azure-sdk-for-python/assets/5227017/d66a63d6-ea72-499b-a27c-19708f04485b)

So any environment that has >= 4.0.1  and < 4.6.0 of the package present throws an exception when importing azure-servicebus.

**To Reproduce**
1. Create a virtual environment. Using this example requirements.txt:

```
typing-extensions==4.4.0
azure-servicebus==7.12.1
```

run `pip install -r .\requirements.txt`

2. Open python interactive terminal and run `from azure.servicebus import ServiceBusClient`. See the following exception:

```
>>> from azure.servicebus import ServiceBusClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Source\typing-extensions-debug\.venv\Lib\site-packages\azure\servicebus\__init__.py", line 10, in <module>
    from ._servicebus_client import ServiceBusClient
  File "C:\Source\typing-extensions-debug\.venv\Lib\site-packages\azure\servicebus\_servicebus_client.py", line 12, in <module>
    from ._base_handler import (
  File "C:\Source\typing-extensions-debug\.venv\Lib\site-packages\azure\servicebus\_base_handler.py", line 19, in <module>
    from ._pyamqp.utils import generate_sas_token
  File "C:\Source\typing-extensions-debug\.venv\Lib\site-packages\azure\servicebus\_pyamqp\__init__.py", line 10, in <module>
    from ._connection import Connection
  File "C:\Source\typing-extensions-debug\.venv\Lib\site-packages\azure\servicebus\_pyamqp\_connection.py", line 15, in <module>
    from ._transport import Transport
  File "C:\Source\typing-extensions-debug\.venv\Lib\site-packages\azure\servicebus\_pyamqp\_transport.py", line 52, in <module>
    from ._encode import encode_frame
  File "C:\Source\typing-extensions-debug\.venv\Lib\site-packages\azure\servicebus\_pyamqp\_encode.py", line 35, in <module>
    from typing_extensions import Buffer
ImportError: cannot import name 'Buffer' from 'typing_extensions' (C:\Source\typing-extensions-debug\.venv\Lib\site-packages\typing_extensions.py)
```

**Expected behavior**
Importing azure-servicebus should work without throwing an error because of a dependency on the wrong version of typing-extensions.

**Screenshots**

**Additional context**
I ran into this issue inside of the [Databricks 14.2 Spark runtime](https://docs.databricks.com/en/release-notes/runtime/14.2.html), where typing-extensions 4.4.0 is pre-installed.

**Comment by kashifkhan** [comment]
Thank you for the feedback @YaroBear . We will investigate and get back to you asap.

**Comment by kashifkhan** [comment]
Hi @YaroBear , a colleague informed that they have faced this issue before with databricks and there might be some other steps in this [thread](https://github.com/Azure/azure-sdk-for-python/issues/23697#issuecomment-1110154625) that you might have to take in order to resolve the issue. 

otherwise, your PR looks great and we should update the min version of typing_extensions.

**Comment by YaroBear** [comment]
@kashifkhan nice, thanks for sharing. A third option, which I opted for, was to override the typing-extensions dependency in the yaml for my Databricks Asset Bundle, like so:

```
tasks:
  ...
  libraries:
    - pypi:
        package: typing-extensions==4.10.0
```

I am using a Job Compute, which gets spun up and torn down between each run.

For All purpose compute, it can be overridden though the UI or set in Cluster Policy as well.

![image](https://github.com/Azure/azure-sdk-for-python/assets/5227017/2b8c288b-c55d-45e3-8078-7144c5a6c426)

![image](https://github.com/Azure/azure-sdk-for-python/assets/5227017/9971579e-c39c-40fe-b284-535d383402e7)
