### ISSUE TITLE
Variable share_usage_bytes always returns None (file_shares.get)

### ISSUE THREAD

**Issue by OldScratchy** [Azure/azure-sdk-for-python#34892]
- **Package Name**: azure.mgmt.storage
- **Package Version**: 21.1.0
- **Api Version**: 2023-01-01
- **Operating System**: Windows 10 Pro (22H2)
- **Python Version**: 3.10.0

**Describe the bug**
When attempting to retrieve the usage of my file shares in Azure using Python, I've encountered an issue with the variable share_usage_bytes. Despite following the appropriate steps as per the official documentation, the value assigned to this variable is always None:

![image](https://github.com/Azure/azure-sdk-for-python/assets/109864728/31b9ec84-2ce9-4f54-8dea-10bff55b41e7)

**To Reproduce**

get_fs = storage_client.file_shares.get(resource_group, account_name, share_name)

print (get_fs.share_usage_bytes)

**Expected behavior**
According to the docs:

share_usage_bytes
[int](https://docs.python.org/3/library/functions.html#int)
The approximate size of the data stored on the share. Note that this value may not include all recently created or recently resized files.

**Comment by ChenxiJiang333** [comment]
@OldScratchy Could you please share the package version you're using, instead of the api version?

**Comment by OldScratchy** [comment]
> @OldScratchy Could you please share the package version you're using, instead of the api version?

Just updated the description (__version__ from azure.mgmt.storage)

**Comment by ChenxiJiang333** [comment]
@OldScratchy sorry for the late response, since it might be a service problem, I have opened an issue https://github.com/Azure/azure-rest-api-specs/issues/28499 to seek help from service team, please follow that issue to get support.
