### ISSUE TITLE
Allow using dicts instead of specific classes

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#349]
Classes are nice for interactive coding, but it would be better if you could define an entire configuration in dicts and lists. That way it can be more easily saved/loaded from configuration files.

**Comment by JamieCressey** [comment]
+1

**Comment by lmazuel** [comment]
Hello,

Thank you for your comment and sorry for this late answer.
The API at the time you wrote this comment is now in "legacy" and will be replaced soon by the ARM version. The ARM API allows you to save JSON configuration file as you can see here:
https://github.com/Azure/azure-quickstart-templates

Please feel free to re-open this bugs if you think my answer is not accurate to your request.
