### ISSUE TITLE
Event Hubs Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#34909]
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/eventhub/azure-eventhub#prerequisites)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/62ab69a1-f78d-4a0f-85da-10769af60677)

**Reason:**
Link error.

**Suggestion:**
Add link"https://azure.microsoft.com/zh-cn/free/python/" to ` create an account`

@rohit-ganguly , @lmazuel , @ronniegeraghty , @jsquire , @annatisch for notification.

**Comment by kashifkhan** [comment]
Thank you for the feedback @jerryshia. We will investigate and get back to you asap.
