### ISSUE TITLE
Cosmos DB Readme and Sample Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#34910]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cosmos/azure-cosmos#create-an-analytical-store-enabled-container)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/98a26e0c-15f6-4eff-ad77-4c24772d40b1)

**Reason:**
`analyticalStorageTtl` is not a valid property in the current payload.

**Suggestion:**
Update code to `partition_key=PartitionKey(path="/productName")`

2.
Section [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/document_management.py#L215)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/0b1ae2ab-64be-48d2-863c-f4b0a8825497)

**Reason:**
BAD_REQUEST - Request being sent is invalid 

**Suggestion:**
Update code to `'account_number': 'Account1', "message": "item was replaced"`

@rohit-ganguly , @lmazuel , @kyle-patterson , @KrzysztofCwalina , @annatisch for notification.

**Comment by simorenoh** [comment]
@jerryshia the first one is a code snippet in our README showing users how to set the `analytical_ttl` keyword, it is not a sample meant to be run directly. The second bit is correct, and has been corrected in both its sync and async versions here: https://github.com/Azure/azure-sdk-for-python/pull/36566

**Comment by simorenoh** [comment]
PR has been merged.
