### ISSUE TITLE
Azure Search - cannot import NativeBlobSoftDeleteDeletionDetectionPolicy

### ISSUE THREAD

**Issue by mattgotteiner** [Azure/azure-sdk-for-python#34914]
- **azure-search-documents**: 
- **11.6.0b2**: 
- **Windows**:
- **3.11**: 

**Describe the bug**
Cannot import NativeBlobSoftDeleteDeletionDetectionPolicy from azure.search.documents.indexes.models
I can import this from azure.search.documents.indexes._generated.models

**To Reproduce**
1. Try to import from the publicly named module, fails
2. Try to import from the generated module, succeeds

**Expected behavior**
I don't need to refer to the generated module to import this class

**Comment by mattgotteiner** [comment]
> Thanks for the feedback! We are routing this to the appropriate team for follow-up. cc @bleroy @MarkHeff @miwelsh @tjacobhi.

@jsquire, @hector-norza   any way to turn these off?  We are mentioning the wrong folks here. Please let me know.

**Comment by jsquire** [comment]
> > Thanks for the feedback! We are routing this to the appropriate team for follow-up. cc @bleroy @MarkHeff @miwelsh @tjacobhi.
> 
> @jsquire, @hector-norza any way to turn these off? We are mentioning the wrong folks here. Please let me know.

They're driven by CODEOWNERS.  If the contacts are incorrect, please update the appropriate service label block there.

**Comment by mattgotteiner** [comment]
@jsquire this file? I took a look and the folks mentioned above are not in it

https://github.com/Azure/azure-sdk-for-python/blob/fcaa29d23578331403ea3fa0e2a91f86e02d4d82/.github/CODEOWNERS#L337-L340

**Comment by jsquire** [comment]
@mattgotteiner:  You're in the wrong spot:
https://github.com/Azure/azure-sdk-for-python/blob/main/.github/CODEOWNERS#L833
