### ISSUE TITLE
Web Search Operation returned an invalid status code 'Resource Not Found'

### ISSUE THREAD

**Issue by ibrahim-kabir** [Azure/azure-sdk-for-python#34917]
- **Package Name**: azure-cognitiveservices-search-websearch
- **Package Version**: 2.0.0
- **Operating System**: Microsoft Windows 11 Home
- **Python Version**: 3.12.2

**Describe the bug**
My endpoint `https://api.bing.microsoft.com` does not work with the azure-sdk-for-python. I get this error when I make a search:
`azure.cognitiveservices.search.websearch.models._models_py3.ErrorResponseException: Operation returned an invalid status code 'Resource Not Found'`

From my understanding, the endpoint has changed overtime and the new endpoint isn't working with the newest version of azure-cognitiveservices-search-websearch.

**To Reproduce**
1. Download the package
2. Follow this documentation to make a query: [Quickstart: Use a Bing Web Search Python client library](https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/quickstarts/sdk/web-search-client-library-python)
![image](https://github.com/Azure/azure-sdk-for-python/assets/117961703/2fef8128-1c4f-4f6b-83f5-47e648f91986)
3. Run the snippet to create a web client

**Expected behavior**
```bash
    web_data = client.web.search(query=query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    raise models.ErrorResponseException(self._deserialize, response)
azure.cognitiveservices.search.websearch.models._models_py3.ErrorResponseException: Operation returned an invalid status code 'Resource Not Found'
```

**Proposition to fix the issue**
In the file `azure/cognitiveservices/search/websearch/_configuration.py`
modify this line
from:
```python
base_url = '{Endpoint}/bing/v7.0'
```
to:
```python
base_url = '{Endpoint}/v7.0'
```
**TEMPORARY SOLUTION**
Add the line `client.config.base_url = '{Endpoint}/v7.0'` right after creating the client. This will fix the endpoint
Exemple:
```python 
client = WebSearchClient(endpoint="https://api.bing.microsoft.com", credentials=CognitiveServicesCredentials(subscription_key))
client.config.base_url = '{Endpoint}/v7.0' # Temporary change to fix the error
web_data = client.web.search(query=query)
```

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by Gintasz** [comment]
I'm also getting this error.

**Comment by xiangyan99** [comment]
This package is no longer being maintained. Please refer to the samples in the [Bing Search for Python repo](https://github.com/microsoft/bing-search-sdk-for-python/tree/main) instead.

For additional support, please open a new issue in the [Issues](https://github.com/microsoft/bing-search-sdk-for-python/issues) section of the Microsoft Bing Search SDK for Python repo.
