### ISSUE TITLE
Can't create pipeline to execute notebook with custom environment

### ISSUE THREAD

**Issue by hectordanielc** [Azure/azure-sdk-for-python#34915]
- **azureml-core**: 
- **1.55.1.post2**: 
- **Linux**:
- **3.10**: 

**Describe the bug**
I'm trying to replicate this notebook https://github.com/balakreshnan/Samples2021/blob/main/AzureMLPipelineNotebook/notebookpipelineexec.md, but I can only use one curated environment. If I try to create an environment like in this code snipet (With USE_CURATED_ENV =False):

    from azureml.core.runconfig import RunConfiguration
    from azureml.core.conda_dependencies import CondaDependencies
    from azureml.core import Environment 
    
    aml_run_config = RunConfiguration()
    #compute_target as defined in "Azure Machine Learning compute" section above
    aml_run_config.target = compute_target
    
    USE_CURATED_ENV = True
    if USE_CURATED_ENV :
        curated_environment = Environment.get(workspace=ws, name="AzureML-Tutorial")
        aml_run_config.environment = curated_environment
    else:
        aml_run_config.environment.python.user_managed_dependencies = False
        #Add some packages relied on by data prep step
        aml_run_config.environment.python.conda_dependencies = CondaDependencies.create(
            conda_packages=['pandas','scikit-learn','seaborn','tqdm'], 
            pip_packages=['azureml-sdk', 'azureml-dataprep[fuse,pandas]','seaborn','tqdm'], 
            pin_sdk_version=False)

the pipeline won't run and will return the error:

"This pipeline didn't have the rawdeserializer policy can't deserialize"

It only works with one curated environment that stats with AzurML and it doesn't matter if I clone it, the clone fails too and no other curated environment works neither.

The only curated environment that works doesn't have the required libraries so in order to use them I tried adding them, but  adding libraries on it doesn't work neither, maybe because it doesn't have conda dependencies.

Something I noticed is the when I run:
Environment.list(worspace=ws)

The only printed envrionment is the one that works, all the other available environments are not printed.

**Expected behavior**
The pipeline should execute properly with every environment.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/118506104/76de881c-eea0-4ad8-88e3-26116af5860e)

**Additional context**
The trial.py its only a Hello World print.

**Comment by Ramya-ML18** [comment]
Hi @ hectordanielc 
when I am using the USE_CURATED_ENV =False the default custom environment is created succesfully and the pipeline jobs gets succeeded.
and also please share the repro steps?

**Comment by hectordanielc** [comment]
I'm exactly following the repo https://github.com/balakreshnan/Samples2021/blob/main/AzureMLPipelineNotebook/notebookpipelineexec.md and it works only with the Microsoft's curated environment "AzureML-ACPT-pytorch-1.13-py38-cuda11.7-gpu:10". All the others even the others curated environments aren't working.

I followed the error and here is the log:

![image](https://github.com/Azure/azure-sdk-for-python/assets/118506104/5c08ff7d-3193-45b7-9808-fbdd50523f38)

**Comment by Ramya-ML18** [comment]
Hi @hectordanielc 
From the error message its saying that the Authentication error from the storage. Can you please check the permissions of the storage account whether storage account has the necessary permissions to access the workspace or not.
