### ISSUE TITLE
Run configure_azure_monitor during PyTest testing

### ISSUE THREAD

**Issue by progxaker** [Azure/azure-sdk-for-python#34935]
- **Package Name**: `azure-monitor-opentelemetry`
- **Package Version**: 1.1.1, 1.3.0
- **Operating System**: RHEL, Debian
- **Python Version**: 3.9, 3.12

**Describe the bug**
PyTest fails when running the `configure_azure_monitor` function.
`ERROR test_main.py - ValueError: Instrumentation key cannot be none or empty.`

<details>
<summary>PyTest output</summary>

```
# pytest --disable-warnings -q

============================================================================================= ERRORS =============================================================================================
_________________________________________________________________________________ ERROR collecting test_main.py __________________________________________________________________________________
test_main.py:7: in <module>
    configure_azure_monitor()
/usr/local/lib/python3.12/site-packages/azure/monitor/opentelemetry/_configure.py:87: in configure_azure_monitor
    _setup_tracing(configurations)
/usr/local/lib/python3.12/site-packages/azure/monitor/opentelemetry/_configure.py:113: in _setup_tracing
    trace_exporter = AzureMonitorTraceExporter(**configurations)
/usr/local/lib/python3.12/site-packages/azure/monitor/opentelemetry/exporter/export/_base.py:86: in __init__
    parsed_connection_string = ConnectionStringParser(kwargs.get('connection_string'))
/usr/local/lib/python3.12/site-packages/azure/monitor/opentelemetry/exporter/_connection_string_parser.py:39: in __init__
    self._validate_instrumentation_key()
/usr/local/lib/python3.12/site-packages/azure/monitor/opentelemetry/exporter/_connection_string_parser.py:84: in _validate_instrumentation_key
    raise ValueError("Instrumentation key cannot be none or empty.")
E   ValueError: Instrumentation key cannot be none or empty.
==================================================================================== short test summary info =====================================================================================
ERROR test_main.py - ValueError: Instrumentation key cannot be none or empty.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
1 warning, 1 error in 5.00s
```

</details>

**To Reproduce**
1. Clone the [empty-connection-string](https://github.com/progxaker/empty-connection-string) repository.
2. Follow instructions in the README.md file.

**Expected behavior**
There are no errors in PyTests.

**Additional context**
* I tried setting `connection_string=None` (`configure_azure_monitor(...=None)`), but that didn't work.
* The error occurs only at the PyTest step. If run `main.py` directly, there is no problem getting the value from `APPLICATIONINSIGHTS_CONNECTION_STRING`, as documented in the [azure-docs-sdk-python](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/3243669f5b588fa5e956976c2c6bd464d7f67add/monitor-opentelemetry-readme.md#L71) repository.
* PyTests full trace: [pytest-full-trace.log](https://github.com/Azure/azure-sdk-for-python/files/14758143/pytest-full-trace.log).

**Comment by progxaker** [comment]
Does a client have to specify the string even in the testing phase? Or is there a dummy value that can be used instead?

**Comment by lzchen** [comment]
@progxaker 

Set the env var explicitly in `configure_azure_monitor(connection_string="<your-cstring>")` or set the env var explicitly in your test_main code:

```python
import os

os.environ["APPLICATIONINSIGHTS_CONNECTION_STRING"] = "<your-cstring>"

**Comment by progxaker** [comment]
It looks like no: `ValueError: dictionary update sequence element #0 has length 1; 2 is required`.

I would like to not use the actual connection string while testing. Perhaps there is a way to mock the function? How did you do it for `tests/configuration/test_configure.py`?

**Comment by lzchen** [comment]
@progxaker 

I used a dummy connection string.

**Comment by progxaker** [comment]
I think so too. Thank you for the help.
