### ISSUE TITLE
"ManagedIdentityCredential: Unexpected content type "text/html"" error during AzureMachineLearningFileSystem function call

### ISSUE THREAD

**Issue by Wor0001** [Azure/azure-sdk-for-python#34936]
- **Package Name**: azureml-fsspec
- **Package Version**: 1.1.1
- **Operating System**: linux Debian 11
- **Python Version**: 3.8.17

**Describe the bug**
When executing a function of an instance of AzureMachineLearningFileSystem (such as .ls()) that is initialized to point to an AML datastore, DefaultAzureCredential fails when attempting to authenticate with the ManagedIdentityCredential, with the reason "Unexpected content type "text/html"". Screenshot of full error message below.

**To Reproduce**
1. Initialize a AzureMachineLearningFileSystem object with an AML datastore URI, no other arguments.
2. Call a function of the filesystem object, such as .ls().

**Expected behavior**
DefaultAzureCredential attempts to authenticate with ManagedIdentityCredential, fails (because I'm running in VS Code on a local machine), and it continues attempting other authentication methods (eventually landing on CLICredential, which works).

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/58856680/d41d4dda-5cd9-4d30-80a5-b99843dd77e6)

**Additional context**
With this same setup, any time I use DefaultAzureCredential, I have to include the arg "exclude_managed_identity_credential=True", otherwise this same failure with the ManagedIdentityCredential will cause an error. This works for things like MLClient, where one can give it a credential to use when instantiating. To use an MLClient, for example, I could create a DefaultAzureCredential with "exclude_managed_identity_credential=True", then pass that credential into MLClient when initializing it. If I don't do this, I will get the same error when trying to do anything with the MLClient that required authentication. I'm also on USGovCloud.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you help to clarify the questions?

e.g. you want to know more about the failure "Unexpected content type "text/html"" or you want azureml-fsspec to allow specifying credential object?

**Comment by Wor0001** [comment]
Thanks for the quick reply. It would be great if I could tell AzureMachineLearningFileSystem to skip the managed identity credential check, like I can by doing the "exclude_managed_identity_credential=True" arg with DefaultAzureCredential. Or to be able to pass a credential to AzureMachineLearningFileSystem to use specifically. I just want to avoid the error from the managed identity credential check.

**Comment by xiangyan99** [comment]
Thanks for the clarification.

azureml-fsspec package is not monitored in this repo.

Please open a ticket for the machine learning team.
