### ISSUE TITLE
Not able to halt early receiving messages from Service bus queue

### ISSUE THREAD

**Issue by Niladri24dutta** [Azure/azure-sdk-for-python#34941]
I am refering to the below sample code given in - [https://learn.microsoft.com/en-us/python/api/overview/azure/servicebus-readme?view=azure-python](https://learn.microsoft.com/en-us/python/api/overview/azure/servicebus-readme?view=azure-python)

```
from azure.servicebus import ServiceBusClient

import os
connstr = os.environ['SERVICE_BUS_CONNECTION_STR']
queue_name = os.environ['SERVICE_BUS_QUEUE_NAME']

with ServiceBusClient.from_connection_string(connstr) as client:
    # max_wait_time specifies how long the receiver should wait with no incoming messages before stopping receipt.
    # Default is None; to receive forever.
    with client.get_queue_receiver(queue_name, max_wait_time=30) as receiver:
        for msg in receiver:  # ServiceBusReceiver instance is a generator.
            print(str(msg))
            # If it is desired to halt receiving early, one can break out of the loop here safely.
```
But I am not able to break out of the loop while iterating the receiver which is a generator as mentioned here -
  **# If it is desired to halt receiving early, one can break out of the loop here safely.**

I am expecting a lot of messages in the queue so I am trying to achieve below -

1.  Iterate through all the messages and then check the value of a specific property in the message json body , if the condition matches then mark the message as `complete_message()` to remove it from the queue. Otherwise I am using `abandon_message()` to release the lock and put the message back to queue. It is time consuming but it is failing while trying to break out of the loop . I have tried using `return,yield,break` etc . All the messages are going into dead letter queue after `break` is executed(except the one marked as complete)

OR

2. Filter all the messages in the service bus queue without iterating all of them based on the filter condition to check the value of a specific property in the message json body. Then mark the message as complete.  This is a better option for me but I am curious to know if it is feasible to achieve this if there are too many messages in the queue without iterating them.

**Service bus sdk version : 7.6.0**

**Comment by kashifkhan** [comment]
Thank you for the feedback @Niladri24dutta . Can you share your sample code that you are using right now ?

servicebus 7.6.0 is a really old version and is no longer supported. Could you please update to 7.12.1 as well please?

**Comment by Niladri24dutta** [comment]
@kashifkhan  is there any breaking change between 7.6.0 and 7.12.1 ?

**Comment by kashifkhan** [comment]
@Niladri24dutta based on our changelog there is one breaking change if you use websockets. While not a breaking change you will be using the new amqp library

The full changes are listed here in case I missed something https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/CHANGELOG.md

Could you also share how your code looks please?

**Comment by Niladri24dutta** [comment]
> @Niladri24dutta based on our changelog there is one breaking change if you use websockets. While not a breaking change you will be using the new amqp library
> 
> The full changes are listed here in case I missed something https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/CHANGELOG.md
> 
> Could you also share how your code looks please?

Here is sample code - 
```
import os
from azure.servicebus import ServiceBusClient
from azure.identity import DefaultAzureCredential

FULLY_QUALIFIED_NAMESPACE = os.environ['SERVICEBUS_FULLY_QUALIFIED_NAMESPACE']
QUEUE_NAME = os.environ["SERVICEBUS_QUEUE_NAME"]

credential = DefaultAzureCredential()

servicebus_client = ServiceBusClient(FULLY_QUALIFIED_NAMESPACE, credential)

with servicebus_client:
    receiver = servicebus_client.get_queue_receiver(queue_name=QUEUE_NAME)
    with receiver:
        for msg in receiver:
            print(str(msg))
            if <value of some key in msg json body == somevalue> : 
                receiver.complete_message(msg)
                return #this is not working and the remaining messages in the queue are going into dead letter after waiting for sometime
          else
               receiver.abandon_message(msg) #push the message back to queue and release the lock
```

**Comment by kashifkhan** [comment]
@Niladri24dutta there can be 2 things impacting this, with service bus queues there is:

* max delivery count - There's a limit on number of attempts to deliver messages for Service Bus queues and subscriptions. The default value is 10. Whenever a message has been delivered under a peek-lock, but has been either explicitly abandoned or the lock has expired, the delivery count on the message is incremented. When the delivery count exceeds the limit, the message is moved to the DLQ.
* message time to live - Message time to live determines how long a message will stay in the queue before it expires and is removed or dead lettered. When sending messages, it is possible to specify a different time to live for only that message. This default will be used for all messages in the queue which do not specify a time to live for themselves.

When I tried to reproduce this on my side, I ran in to max delivery count. My data was set up with either "hi" or "bye", I was abandoning all the "bye" messages.  They would end up back in the queue and would attempt to be delivered again, which would get abandoned. Eventually it would hit max delivery count and then be put into the dlq.

The other one could be TTL, are you running into a situation where this limit is reached and the messages are dead lettered?

outside of these I was not able to see my messages gettting sent to the DLQ randomly using the new version of the client library.


my repro code. I had 10 records in the queue

```python
import os
from azure.servicebus import ServiceBusClient

from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

CONNECTION_STR = os.environ['SERVICEBUS_CONNECTION_STR']
QUEUE_NAME = os.environ["SERVICEBUS_QUEUE_NAME"]

servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR)

with servicebus_client:
    receiver = servicebus_client.get_queue_receiver(queue_name=QUEUE_NAME)
    with receiver:
        for msg in receiver:
            if str(msg) == "Hi":
                print("Received: Hi")
                receiver.complete_message(msg)
                break
            else:
                print("Received: Bye")
                receiver.abandon_message(msg)

print("Receive is done.")
```

```bash
Received: Bye
Received: Hi
Receive is done.
```

**Comment by Niladri24dutta** [comment]
@kashifkhan I have 2 questions on this -

1. Can we use keyword like `break,return` inside the loop to break out safely from the generator ? Will it raise any generatorexit exeception ?
2. If the queue has more than 200 messages then in that case can we try this second approach? Is this actually feasible?
> Filter all the messages in the service bus queue without iterating all of them based on the filter condition to check the value of a specific property in the message json body. Then mark the message as complete. This is a better option for me but I am curious to know if it is feasible to achieve this if there are too many messages in the queue without iterating them.

**Comment by kashifkhan** [comment]
@Niladri24dutta you should be able to return or break out of the generator like my example code above, without any issue. If you are using the context manager it'll close the receiver as the scope is exited. 

Filters are not available on queues, but they are a feature of [topics](https://learn.microsoft.com/en-us/azure/service-bus-messaging/topic-filters).

**Comment by Niladri24dutta** [comment]
> you should be able to return or break out of the generator like my example code above, without any issue. If you are using the context manager it'll close the receiver as the scope is exited.
> 
> Filters are not available on queues, but they are a feature of [topics](https://learn.microsoft.com/en-us/azure/service-bus-messaging/topic-filters).

@kashifkhan  thanks for the explanation . Yes it worked for me , However I have another issue now . 
1.  As you mention using `Abandon` will increase the delivery count and finally it will be send to dead letter queue. So I want to put the message back to the main queue (active) but I dont want the message to be reattempted for delivery automatically. I should be able to receive the message next time I open a connection to the Service bus receiver . is this possible to achieve?Please refer to the below code -

```
credential = DefaultAzureCredential()

servicebus_client = ServiceBusClient(FULLY_QUALIFIED_NAMESPACE, credential)

with servicebus_client:
    receiver = servicebus_client.get_queue_receiver(queue_name=QUEUE_NAME)
    with receiver:
        for msg in receiver:
           # make some rest api call here but dont remove the message from queue
           # put the message back to the queue with redelivering it

```

```
 next time I open a new connection I should be able to receive the message now
 credential = DefaultAzureCredential()

servicebus_client = ServiceBusClient(FULLY_QUALIFIED_NAMESPACE, credential)

with servicebus_client:
    receiver = servicebus_client.get_queue_receiver(queue_name=QUEUE_NAME)
    with receiver:
        for msg in receiver:
            receiver.complete_message(msg) # complete the message here 
```

2. Is it possible to send a message directly to dead letter queue using `send_message()` ?

**Comment by kashifkhan** [comment]
@Niladri24dutta As long as messages are available in the queue to be delivered they will be sent as long as you are iterating over them, so simply abandoning them wont give you that ability. There is an option to [defer messages](https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-deferral) but that would require you to remember the sequence number when using `receive_deferred_messages` to retrieve them. A combination of `peek_messages` & `receive_deferred_messages` would work.

to send a message directly to dead letter you can use `dead_letter_message`

**Comment by Niladri24dutta** [comment]
> @Niladri24dutta As long as messages are available in the queue to be delivered they will be sent as long as you are iterating over them, so simply abandoning them wont give you that ability. There is an option to [defer messages](https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-deferral) but that would require you to remember the sequence number when using `receive_deferred_messages` to retrieve them. A combination of `peek_messages` & `receive_deferred_messages` would work.
> 
> to send a message directly to dead letter you can use `dead_letter_message`
@kashifkhan  thanks for your suggestion , can you please confirm if we can defer a message after it is peeked ? I am trying to use peek_messages instead of receive_messages

**Comment by kashifkhan** [comment]
Hi @Niladri24dutta, yes you should be able to defer messages after you peek them. Peeking just allows you to browse the available messages in a queue without removing them from the queue. https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-browsing?tabs=csharp
