### ISSUE TITLE
azure-search-documents: Ability to pass additional custom HTTP headers

### ISSUE THREAD

**Issue by rukasakurai** [Azure/azure-sdk-for-python#34981]
**Is your feature request related to a problem? Please describe.**
Python developers that I am working with would like to perform search requests against Azure AI Search Indexes that are exposed through Azure API Management. There is the requirement to pass a valid Azure API Management Subscription Key. 

With https://pypi.org/project/azure-search-documents/, while it seems possible to specify an Azure API Management endpoint instead of an Azure AI Search endpoint, there doesn't seem to be a way to pass an Azure API Management Subscription Key in the HTTP header.

The developers would therefore need to write and maintain custom code using tools like urllib.

**Describe the solution you'd like**
I would like developers to be able to pass additional HTTP headers when using https://pypi.org/project/azure-search-documents/

**Describe alternatives you've considered**
As mentioned above, an alternative is for developers to write and maintain custom code similar to https://pypi.org/project/azure-search-documents/ with the added capability of passing additional HTTP headers.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

You can specify headers in your call: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/README.md#configurations

e.g.

client.search(headers={"CustomValue": "Bar"})
