### ISSUE TITLE
Not able to get the restore point collection  got exception get() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by pavanpawarveritas** [Azure/azure-sdk-for-python#34982]
- **Package Name**: azure.mgmt.package 
- **Package Version**: 30.6.0
- **Operating System**: RHEL
- **Python Version**: Python 3.9.18

**Describe the bug**
```python
def get_restore_point_collection(clientId, tenantId, secret, rg_name, rpc_name):
        credentials = ClientSecretCredential(tenant_id=tenantId, client_id=clientId,
                                              client_secret=secret, cloud_environment=cloud)
        sc = SubscriptionClient(credentials, base_url=cloud_base_url)
        for s in sc.subscriptions.list():
            print("Discovering subscriptionId = {}".format(s.subscription_id))
            computeclient = ComputeManagementClient(credentials,
                                                s.subscription_id,
                                                base_url=cloud_base_url)
            try:
                expand = RestorePointCollectionExpandOptions.RESTORE_POINTS
                restore_point_list = computeclient.restore_point_collections.get(rg_name, rpc_name, expand)
                logging.info("Restore Point: {}".format(restore_point_list))
            except Exception as e:
                logging.exception("Failed to get restore point collection {}. Error: {}".format(rpc_name, e))
```
While we are calling  “computeclient.restore_point_collections.get(rg_name, rpc_name, expand)” it failed with the following exception. 

`06:32:43,250 root ERROR Failed to get restore point collection nbsm-rpc-92a4f917-06a2-4e10-83d4-2a7e4f76f504. Error: get() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/tmp/azure_get_restore_point_collection.py", line 27, in get_restore_point_collection
    restore_point_list = computeclient.restore_point_collections.get(rg_name, rpc_name, expand)
  File "/tmp/cloudpoint/libs/azure/lib/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
TypeError: get() takes 3 positional arguments but 4 were given
`
**To Reproduce**
1. run the code onazure.mgmt.package (30.6.0) mentioned in Describe the bug

**Expected behavior**
we are able to list on the older version of SDK 29.1.0

**Screenshots**

**Additional context**
found similar issue https://github.com/Azure/azure-sdk-for-python/issues/30983 already fixed for VM

**Comment by ChenxiJiang333** [comment]
hi, @pavanpawarveritas please try adding the keyword `expand`:
```
restore_point_list = computeclient.restore_point_collections.get(rg_name, rpc_name, expand=expand)
```

**Comment by pavanpawarveritas** [comment]
issue resolved by your suggetion
