### ISSUE TITLE
Azure Functions API Reference doesn't offer documentation for FunctionApp and Blueprint classes

### ISSUE THREAD

**Issue by metamoof** [Azure/azure-sdk-for-python#34985]
### Type of issue

Missing information

### Description

Azure Functions Python v2 projects use the azure.functions.Blueprint and FunctionApp classes, as well as a number of standard decorators, but there is no documentation for those classes and their decorators in the API reference.

They should be included in the Classes  and methods section of the package reference.

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-functions/azure.functions?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-functions/azure.functions.yml

### Document Version Independent Id

33be62d6-06f4-9c93-ba62-df4dfd96ddca

### Article author

@lmazuel

### Metadata

* ID: 27839837-0e98-4389-b589-0562936f436c 
* Service: **azure-functions**

**Comment by metamoof** [comment]
There is a related issue with durable functions in #34983

**Comment by kashifkhan** [comment]
Hi @metamoof, this repo is for the Azure Python SDK. For items related to Azure Functions issues need to be opened [here](https://github.com/Azure/Azure-Functions)
