### ISSUE TITLE
Azure Durable Functions API Reference doesn't offer documentation for DFApp and Blueprints classes

### ISSUE THREAD

**Issue by metamoof** [Azure/azure-sdk-for-python#34983]
### Type of issue

Missing information

### Description

Azure Functions Python v2 projects use the `azure.durable_functions.Blueprint` and `DFApp` classes, but there is no documentation for those classes and their decorators in the API reference.

They should be included in the Classes section of the package reference.

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-functions-durable/azure.durable_functions?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-functions-durable/azure.durable_functions.yml

### Document Version Independent Id

ca0470bb-40c6-66a7-a764-71e29509afcf

### Article author

@lmazuel

### Metadata

* ID: a95fe6a1-3abb-7c46-99e4-bb932ea82918

**Comment by kashifkhan** [comment]
Hi @metamoof, this repo is for the Azure Python SDK. For items related to Azure Functions issues need to be opened [here](https://github.com/Azure/Azure-Functions)

**Comment by metamoof** [comment]
@kashifkhan This issue is opened becasue the link provided on the bottom of the page. https://learn.microsoft.com/en-us/python/api/azure-functions-durable/azure.durable_functions?view=azure-python 

I will open an issue for my problem in the other location, but please also look at correcting that link.
