### ISSUE TITLE
How to get the community gallery image's Security type and Accelerated networking from python sdk

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-sdk-for-python#35024]
I can't get the Security type and Accelerated networking from below returned value image, is any way to achieve this?

image = compute_client.community_gallery_images.get(location='eastus', public_gallery_name='gallery name', gallery_image_name='image name'

![image](https://github.com/Azure/azure-sdk-for-python/assets/10083705/ce72547a-2152-4168-9ea8-edb2d59afd7d)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi @LiliDeng , if `Accelerated networking` or `Security type` has a non-default value, then you could find them in the property `image.features`.
```
if image.features:
    print([(feature.name, feature.value) for feature in image.features])
```
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/259ab868-60cb-48f9-8c47-03594d5a2d95)

**Comment by LiliDeng** [comment]
> Hi @LiliDeng , if `Accelerated networking` or `Security type` has a non-default value(`disabled`&`standard`), then you could find them in the property `image.features`.
> 
> ```
> if image.features:
>     print([(feature.name, feature.value) for feature in image.features])
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/119990644/320268294-259ab868-60cb-48f9-8c47-03594d5a2d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzE1NjIsIm5iZiI6MTcxMjYzMTI2MiwicGF0aCI6Ii8xMTk5OTA2NDQvMzIwMjY4Mjk0LTI1OWFiODY4LTYwY2ItNDhmOS04YzQ3LTAzNTk0ZDVhMmQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMjU0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTE5NjNiYjMxYTJkMGYzOWMzYjNiMjhiNmRlNjA3YWJkZmFhMmY5MjhjZjk3ZTE1ZTVjYjI4YmM2NzhjNDMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V7YK0FBlJOB2jV502UlHUq1IzXx6GlC4g-jXRPHdinQ)

thanks!
