### ISSUE TITLE
when retryable error happens, cosmos client returns empty result for pagination query

### ISSUE THREAD

**Issue by hihihuhu** [Azure/azure-sdk-for-python#35021]
- **Package Name**:  azure-cosmos
- **Package Version**:  4.5.2b5 (as well as master)
- **Operating System**: linux
- **Python Version**:  3.11

**Describe the bug**
the very first pagination query, means no continuation token, returns no result if a retryable error happens

specifically, if https://github.com/Azure/azure-sdk-for-python/blob/azure-cosmos_4.5.2b5/sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/base_execution_context.py#L127 throws exception, `_has_started`, which is set to `True` already, won't be revert back to the original value, thus when retry calling into `_fetch_items_helper_no_retries`, it will skip the `while` loop if there is continuation token, and returns 0 result.

we have verified, if we try catch https://github.com/Azure/azure-sdk-for-python/blob/azure-cosmos_4.5.2b5/sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/base_execution_context.py#L127 and revert `_has_started` back to the original value, then the issue is resolved.

**To Reproduce**
1. send any no `QueryItems` query with expected non empty result concurrently
2. until hitting 429
3. some of the query start returning empty result

**Expected behavior**
the query should either fail or return correct result

**Screenshots**

**Additional context**

**Comment by bambriz** [comment]
This issue is addressed and fixed in [PR 35090](https://github.com/Azure/azure-sdk-for-python/pull/35090) @hihihuhu @nicknotfun
