### ISSUE TITLE
[Test Proxy] Support HTTPX transport

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#35030]
We currently redirect requests to the test proxy by monkey patching the `send` methods of `RequestsTransport` and `AioHttpTransport`: https://github.com/Azure/azure-sdk-for-python/blob/5c4c683dcb8b13555b323dd83c34142fbfbedc2d/tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py#L195-L215

[`corehttp`](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/corehttp) introduces `(Async)HttpXTransport`, which will need explicit support in test proxy tooling. Recordings should be agnostic of the transport; i.e. we should be able to record a test with `RequestsTransport` and run the same test in playback with `HttpXTransport` (and vice versa).

**Comment by kdestin** [comment]
The ML team recently did some work to enable recording requests from `openai~=1.x` with the test-proxy.

`openai=1.x` uses httpx under the hood, so it may be possible to reuse some of that work.

See #34424

**Comment by mccoyp** [comment]
@kdestin thank you for the heads-up! This is definitely helpful. I also noticed that https://github.com/Azure/azure-sdk-for-python/issues/34086 already tracks the HTTPX support effort, so I can close this one as a duplicate and assign myself to that one.
