### ISSUE TITLE
Unable to install from private Python Feeds in Docker Build Context

### ISSUE THREAD

**Issue by jinlow** [Azure/azure-sdk-for-python#35036]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.15.0
- **Operating System**: Launching from Windows, However Error in Docker build.
- **Python Version**: 3.11.8

**Describe the bug**
I have set up a private workspace connection in order to connect to a private python feed as described in the [docs here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-package-models?view=azureml-api-2&tabs=sdk#package-a-model-that-has-dependencies-in-private-python-feeds). I know this is working, because when I create an environment with internal packages, using a conda file, as described in the aforementioned docs I am able to install our private packages.

However, when I try to build a docker container which installs from this internal feed, it fails. Here is my Docker file.
```Dockerfile
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

RUN python -m pip install --extra-index-url https://<Link to internal antifactory> our_internal_package==1.0.0
```
And then here is how I create the environment.

```python
from azure.ai.ml import MLClient
from azure.ai.ml.entities import BuildContext, Environment
from azure.identity import AzureCliCredential

cred = AzureCliCredential()
ml_client = MLClient.from_config(credential=cred, path="config.json")

env_docker_context = Environment(
    build=BuildContext(path="environment"),
    description="Environment created from a Docker context.",
)
```

However, whenever this environment is built, I get the following error in my build context output.

```log
2024-04-02T13:07:15:     username, password, save = self._prompt_for_password(parsed.netloc)
2024-04-02T13:07:15:   File "/opt/miniconda/lib/python3.10/site-packages/pip/_internal/network/auth.py", line 455, in _prompt_for_password
2024-04-02T13:07:15:     username = ask_input(f"User for {netloc}: ") if self.prompting else None
2024-04-02T13:07:15:   File "/opt/miniconda/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 251, in ask_input
2024-04-02T13:07:15:     return input(message)
2024-04-02T13:07:15: EOFError: EOF when reading a line
```
This error is because my docker build is trying to log into this internal repo, instead of using the existing workspace connection which should allow it to authenticate automatically.

As I mentioned before, when I build an environment, with a `conda.yml` file, passing the `conda_file="path to yaml"` to the `Environment` class , the connection to the private repository just works. Looking at the output of the build context I see the following docker file is being used...
```Docker
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04@sha256:ce9c0d7c5b4371de7ee00881624b5cdd2e1503edf7ce40b1d31c1dde4131dccb
USER root
RUN mkdir -p $HOME/.cache
WORKDIR /
COPY azureml-environment-setup/99brokenproxy /etc/apt/apt.conf.d/
RUN if dpkg --compare-versions `conda --version | grep -oE '[^ ]+$'` lt 4.4.11; then conda install conda==4.4.11; fi
COPY azureml-environment-setup/mutated_conda_dependencies.yml azureml-environment-setup/mutated_conda_dependencies.yml
RUN ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_7459a71437df47401c6a369f49fbbdb6 -
f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROO
T_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm
 -rf {} + && ldconfig
# AzureML Conda environment name: azureml_7459a71437df47401c6a369f49fbbdb6
ENV PATH /azureml-envs/azureml_7459a71437df47401c6a369f49fbbdb6/bin:$PATH
ENV AZUREML_CONDA_ENVIRONMENT_PATH /azureml-envs/azureml_7459a71437df47401c6a369f49fbbdb6
ENV LD_LIBRARY_PATH /azureml-envs/azureml_7459a71437df47401c6a369f49fbbdb6/lib:$LD_LIBRARY_PATH
COPY azureml-environment-setup/spark_cache.py azureml-environment-setup/log4j.properties /azureml-environment-setup/
RUN if [ $SPARK_HOME ]; then /bin/bash -c '$SPARK_HOME/bin/spark-submit  /azureml-environment-setup/spark_cache.py'; fi
ENV AZUREML_ENVIRONMENT_IMAGE True
CMD ["bash"]
```
Looking through this, I it looks like there are likely several networking things going on/proxies being used that allow the connections to the internal repository to be set up. However, I don't know what's in some of these files, such as the `99brokenproxy` file. Could these files be shared somewhere, so that we  could build custom docker containers, and connect to internal repositories? Building a environment with a `conda.yml` is not flexible enough for our needs.

**To Reproduce**
1. Create a simple Dockerfile, like in my above example, and try to install a package from an private python feed.

**Expected behavior**
Because the workspace connection is setup, I would expect the docker build context to be able to directly authenticate to the private python feed.

**Comment by banibrata-de** [comment]
Could you check if this is helpful: https://github.com/Azure/azure-sdk-for-python/issues/29942

**Comment by jinlow** [comment]
No, this only pertains to Conda environments. As I stated in my original post, that works, it specifically environments built with docker scripts that do not work with private repos.
Is there no way that the scripts used in the conda images docker build process can be provided to the public?

**Comment by banibrata-de** [comment]
I looked into this further does not look like it is supported today. We may consider adding this feature depending on   future priorities. If you are premium customer, please feel free to log ticket for this. In the meantime, I added to our backlog for later consideration.

**Comment by jinlow** [comment]
When you say a premium customer, you just mean I should open a support ticket in the portal?
