### ISSUE TITLE
Spans do not have the parent child relationship when created using the decorator :  @tracer.start_as_current_span()

### ISSUE THREAD

**Issue by summahto** [Azure/azure-sdk-for-python#35042]
- **Package Name and version **: azure-monitor-opentelemetry :1.3.0 , azure-monitor-opentelemetry-exporter :1.0.0b23
- **Operating System**: Ubuntu WSL 2.0
- **Python Version**: 3.11.8

**Describe the bug**
Different behavior is seen in Application Insights when a span is created with and without a decorator.

**To Reproduce**
1. Create a sample FastAPI application and create an endpoint.
2. Call a function test1() within this endpoint.
3. Within the function test1() call 2 more functions test2() and test3()

Here is the sample code :

# CASE 1:
```py
logger = logging.getLogger(__name__)
logger.setLevel(logger.parent.level)
tracer = trace.get_tracer('doc_generator_api')

configure_azure_monitor(
        connection_string= os.getenv("APPLICATIONINSIGHTS_CONNECTION_STRING"),
        logger_name=docgen_logger.name
    )

FastAPIInstrumentor.instrument_app(app)


# This generates test2 and test3 span as child spans within test1 span. which is as expected.
@app.get("/healthcheck")
async def healthcheck():
    """Responses with HTTP status code 200 and empty body"""
    await test1()
    return Response()


async def test1():
    with tracer.start_as_current_span("test1"):
        for i in range(10, 20):
            logger.info(i)
        await test2()
        await test3()

@tracer.start_as_current_span("test2")
async def test2():
    for i in range(20, 30):
        logger.info(i)

@tracer.start_as_current_span("test3")
async def test3():
    for i in range(30, 40):
        logger.info(i)

```

# CASE 2:
```py

# This generates 3 separate spans without any parent child relationship between them
@tracer.start_as_current_span("test1")
async def test1():
    for i in range(10, 20):
        logger.info(i)
    await test2()
    await test3()

@tracer.start_as_current_span("test2")
async def test2():
    for i in range(20, 30):
        logger.info(i)

@tracer.start_as_current_span("test3")
async def test3():
    for i in range(30, 40):
        logger.info(i)

```

**Expected behavior**
Behavior should be the same in both the CASES 1 and 2.  The correct one being the spans seen in CASE 1. Attached the screenshots for the spans as visualized in Application Insights in the following section. 

According to Opentelemetry's documentation [Create-span-using-decorator](https://opentelemetry.io/docs/languages/python/instrumentation/#creating-spans-with-decorators) : 

Creating spans with decorators
It’s common to have a single [span](https://opentelemetry.io/docs/concepts/signals/traces/#spans) track the execution of an entire function. In that scenario, there is a decorator you can use to reduce code:

```py
@tracer.start_as_current_span("do_work")
def do_work():
    print("doing some work...")

```
Use of the decorator is equivalent to creating the span inside do_work() and ending it when do_work() is finished.
To use the decorator, you must have a tracer instance available global to your function declaration. Based on this definition
of how tracer decorator should create spans, the behavior of CASE1 and CASE2 should be the same.

**Screenshots**
Spans seen in Application Insights CASE1 (which is fine and expected) :
![image](https://github.com/Azure/azure-sdk-for-python/assets/20516618/d799a1cc-0776-4e1d-8e2e-a1fb2f82fd8d)

Spans seen in Application Insights CASE2 (which is wrong and should be the same as CASE 1 ) :
![image](https://github.com/Azure/azure-sdk-for-python/assets/20516618/f0204ec5-a098-4632-89ba-2008cdc5e7f3)

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share the information which Azure service and Azure SDK do you use?

**Comment by summahto** [comment]
Here are the dependencies which we are using for our FastAPI application:

```
[tool.poetry.dependencies]
aiohttp = "^3.8"
aiofiles = "^23.2"
azure-cosmos = "^4.3"
azure-identity = "^1.13"
azure-monitor-opentelemetry = "^1.2.0"
azure-purview-catalog = "1.0.0b4"
azure-storage-blob = "12.18.2"
fastapi = "^0"  # TODO Pin minor version before releasing to PROD
fastapi-sessions = "^0"
httpx = "^0"  # TODO Pin minor version before releasing to PROD
opentelemetry-instrumentation = "^0.44b0"
opentelemetry-instrumentation-aiohttp-client = "^0.44b0"
opentelemetry-instrumentation-httpx = "^0.44b0"
opentelemetry-instrumentation-asyncio = "^0.44b0"
opentelemetry-instrumentation-logging = "^0.44b0"
opentelemetry-distro = "^0.44b0"
uvicorn = { extras = ["standard"], version = ">=0.21, <0.22" }

```

**Comment by lzchen** [comment]
@summahto 

This seems to be an issue related to the opentelemetry sdk and not specifically azure monitor. Please open up an issue in the [opentelemetry](https://github.com/open-telemetry/opentelemetry-python/issues/new/choose) repository.

**Comment by summahto** [comment]
@lzchen 

All right. Can we link the 2 issues once I have created the issue in [opentelemetry](https://github.com/open-telemetry/opentelemetry-python/issues/new/choose) repository.

**Comment by xiangyan99** [comment]
Please use the one in open-telemetry repo to track the issue.
