### ISSUE TITLE
Incorrect resource ID check

### ISSUE THREAD

**Issue by adamartin** [Azure/azure-sdk-for-python#35044]
- **Package Name**: azure-cosmos
- **Package Version**: 4.6.0

**Describe the bug**
PR #33341 introduced _validate_resource() which is using regex from _VALID_COSMOS_RESOURCE to validate **any** resource ID. But in reality all the resources have quite different rules for their IDs. The one that is causing problems for me right now after updating cosmos package is forcing document ID to be maximum of 255 characters even though Cosmos allows currently for 1023 chars.

But also the restriction on specific characters vary between different resources.  E.g., according to https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-item-limits document ID can't contain '/' and '\\' although by my tests via portal's Data Explorer the ID can't contain '/' and '#'.

To me it seems that every type of resource needs its own rule, there is no common one. E.g., having separate regex for each type of resource. Or, perhaps, not having any check at all and leave it to the DB engine to fail, which was the original behaviour before.

**To Reproduce**
```
from azure.cosmos import CosmosClient
container_client = CosmosClient.from_connection_string("****").get_database_client("****").get_container_client("****")
container_client.upsert_item({"id": "123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789|123456789"})

```

**Expected behavior**
Document will be stored without exception

**Comment by simorenoh** [comment]
Changes have been released.
