### ISSUE TITLE
set the environment variable

### ISSUE THREAD

**Issue by ylearning86** [Azure/azure-sdk-for-python#35085]
In this step as blow, when you want to set the environment variable on Bash, you need to use `export` command.

https://learn.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-list-resource-groups?view=azure-python-preview&tabs=bash#4-run-the-scripts

Because I couldn't set the environment variable by using `AZURE_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000` but I could set `export AZURE_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000`.

I hope anyone confirm that and will edit expression of learn pages as needed.

-----

- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for your feedback.

If you set a variable without using export, it is treated as a shell variable and is only available in the current shell session.

You can decide if you want to add export or not based on your scenario.
