### ISSUE TITLE
Code example for creating online endpoint which defines it's identity as a `ManagedServiceIdentity`

### ISSUE THREAD

**Issue by nutansahoo** [Azure/azure-sdk-for-python#35097]
### Type of issue

Other (describe below)

### Description

No code example for assigning managed identity to the online endpoint.
Here's a code example which works and can be added [here](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.managedonlineendpoint?view=azure-python).
```
from azure.ai.ml.entities import (
    ManagedOnlineEndpoint,
    IdentityConfiguration,
    ManagedIdentityConfiguration,
)
from azure.identity import AzureCliCredential
from azure.mgmt.msi import ManagedServiceIdentityClient

credential = AzureCliCredential()
msi_client = ManagedServiceIdentityClient(subscription_id="abc",credential=credential)

uai_identity = msi_client.user_assigned_identities.get(
    resource_group_name="xyz",
    resource_name="testmi",
)

# Define an endpoint name
endpoint_name = "test-endpoint-1"

# create an online endpoint
endpoint = ManagedOnlineEndpoint(
    name=endpoint_name,
    description="this is a sample online endpoint",
    auth_mode="key",
    tags={"eval": "online"},
    identity = IdentityConfiguration(type="user_assigned", 
                                     user_assigned_identities=[
                                         ManagedIdentityConfiguration(resource_id=uai_identity.id)
                                         ]
                                    )
)

```

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.managedonlineendpoint?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.entities.ManagedOnlineEndpoint.yml

### Document Version Independent Id

253df083-7b84-c025-195b-0c75be07b20c

### Article author

@lmazuel

### Metadata

* ID: d35e6724-0e5f-89a0-37ad-4434644974de 
* Service: **machine-learning**

**Comment by nutansahoo** [comment]
Hi, 
I think it'd be super helpful for users if a code snippet showing how to asign user assigned managed identity can be assigned to an endpoint in the above concerned documentation page. Thanks for your consideration.

**Comment by banibrata-de** [comment]
Thanks for your suggestion, let me add a backlog item to track this, however we don't have an ETA now, we need to talk about this ask within the team and prioritize.
