### ISSUE TITLE
OpenTelemetry does not log anything from a container on Azure App Service

### ISSUE THREAD

**Issue by yooontheearth** [Azure/azure-sdk-for-python#35101]
- **Package Name**: azure-monitor-opentelemetry
- **Package Version**: 1.3.0
- **Operating System**: python:latest docker image
- **Python Version**: python:latest docker image

**Describe the bug**
The following code does not log anything on traces of Application Insights. Weirdly traces show logs which are set from my local machine but not from Azure App Service. I can see a message "App started" which I implemented in the following code after running the app locally.
```
import os
from azure.monitor.opentelemetry import configure_azure_monitor
import logging

from flask import (Flask, redirect, render_template, request, send_from_directory, url_for)
app = Flask(__name__)

logger_name = __name__
opentelemetery_logger_name = f'{logger_name}.opentelemetry'
configure_azure_monitor(
    logger_name=opentelemetery_logger_name   
)
otelLogger= logging.getLogger(opentelemetery_logger_name)
stream = logging.StreamHandler()
otelLogger.addHandler(stream)
otelLogger.setLevel(logging.INFO)
otelLogger.info('App started')
```

**To Reproduce**
What I did are
- I set `APPLICATIONINSIGHTS_CONNECTION_STRING` at Environment variables on Azure App Service with a connection string from Application Insights.
- I enabled allLogs of Diagnostic setting at Application Insights.
- I took a flask sample code from the following tutorial.
https://learn.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=flask%2Cwindows%2Cazure-cli%2Cazure-cli-deploy%2Cdeploy-instructions-azportal%2Cterminal-bash%2Cdeploy-instructions-zip-azcli
- I appended the code above at the beginning of app.py.
- I built a docker image and pushed it to Azure App Service via Azure Container Registry
- The dockerfile I use is the following.
```
FROM python:latest
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
ENV PYTHONUNBUFFERED=1
EXPOSE 5000
CMD exec gunicorn --workers 4 --bind 0.0.0.0:5000 --timeout 600 app:app
```
- requirements.txt
```
Flask==2.2.2
gunicorn
Werkzeug==2.2.2
azure-monitor-opentelemetry==1.3.0
```

**Comment by yooontheearth** [comment]
@lzchen 

> Just to clarify, the only issue you are experiencing is with LOGGING correct?   

I'm not familiar with Azure Application Insights so I'm not sure other stuff of Application Insights is working correctly, but yes, logging is not working. Could you please tell me where to look at if there is something I can confirm?

I enabled all the settings on Diagnostic setting of Application Insights as below, but the overview page of Application Insights doesn't show any activity. So there might be other problems.
![image](https://github.com/Azure/azure-sdk-for-python/assets/2125182/4584918c-0d13-4463-a192-16939b15c4c1)


> You are seeing the traces table in appinsights and it IS being populated on your local machine but it is NOT being populated in Appservice correct?  

Yes, this is correct. For some reason I don't know, it logged a same message twice though.

![image](https://github.com/Azure/azure-sdk-for-python/assets/2125182/5fdc67dd-4acd-40c4-ba4f-250cdba787c3)

**Comment by jeremydvoss** [comment]
Running the sample I see logs in App Insights. I am unable to reproduce this issue with the provided sample. Could you confirm that the shown sample does not work for you:
```python
import os
from azure.monitor.opentelemetry import configure_azure_monitor
import logging

from flask import (Flask, redirect, render_template, request, send_from_directory, url_for)
app = Flask(__name__)

logger_name = __name__
opentelemetery_logger_name = f'{logger_name}.opentelemetry'
configure_azure_monitor(
    logger_name=opentelemetery_logger_name   
)
otelLogger= logging.getLogger(opentelemetery_logger_name)
stream = logging.StreamHandler()
otelLogger.addHandler(stream)
otelLogger.setLevel(logging.INFO)
otelLogger.info('App started')
```

**Comment by yooontheearth** [comment]
@jeremydvoss 
Thank you for your try. I changed a log message to `otelLogger.info('Confirm app started')` and ran on my machine, then the message was populated on traces of Application Insights as below.

![image](https://github.com/Azure/azure-sdk-for-python/assets/2125182/61e96de8-539e-4b3d-a110-d42118bdc31d)
 
After that, rebuild a docker image and pushed it to App Service and restarted App Service, but nothing was populated. I had also modified the index.html a little bit to check whether re-deployment succeeded or not, and I could confirm that the new build was successfully deployed. 

Here is my Environment variables. I did not touch any settings which are checked on Deployment slot setting though.
![image](https://github.com/Azure/azure-sdk-for-python/assets/2125182/bb58ca78-d17b-438c-bd57-76457928da62)

Might it be a location issue? Here is the locations of the resources.
![image](https://github.com/Azure/azure-sdk-for-python/assets/2125182/74df89cd-8821-4d9e-a1a7-f0a6d381dcbe)

**Comment by yooontheearth** [comment]
The error was happened due to my misconfiguration. To build the image on my machine, I had to set a proxy in the Dockerfile with an environment variable. But I forgot to set it with an empty value in App Service, so the app tried to reach a proxy server whenever logging and failed.

Sorry about that.
