### ISSUE TITLE
BUG: Azure SDK's logging behaviour breaks Python's standard library logging module pattern

### ISSUE THREAD

**Issue by pat-hearps** [Azure/azure-sdk-for-python#35113]
- **Package Name**: azure-ai-ml  |  azure-core
- **Package Version**: 1.12.1  |  1.30.0
- **Operating System**: Windows 11  /  Ubuntu 22.04 on WSL2
- **Python Version**: 3.10.11

**Describe the bug**
Logs are not available in an AzureML job's `'Output + logs'` tab under `user_logs/std_log.txt` - the file is empty unless custom pattern of instantiating python loggers is used.

**To Reproduce**
1. Use [python's standard recommended pattern](https://docs.python.org/3/library/logging.html#logger-objects) of instantiating loggers with `logging.getLogger(__name__)` 
2. Run an AzureML job with python code I wrote, which uses the MLClient from azure-ai-ml
3. Look for logs for the AzureML job

**Expected behavior**
I would expect to see logs from my code that use Python3's standard library logging module, not an empty file.

**Screenshots**
AzureML job with standard logging setup (no logs)
![image](https://github.com/Azure/azure-sdk-for-python/assets/44293239/616f9cb3-a6e8-41ac-b181-34f061a98614)

AzureML job with workaround prefix logging setup (logs are available)
![image](https://github.com/Azure/azure-sdk-for-python/assets/44293239/47b9a07a-72b3-4a45-b253-93442fed06f0)

**Additional context**
It appears that this is a known issue, in fact perhaps a 'feature' of using AzureML / Azure SDK, but it is _very_ poorly documented. In fact the only reference I could find to help me solve the problem was a [similarly raised GitHub issue](https://github.com/Azure/azure-sdk-for-python/issues/14130) to which another user has posted a solution.
This [documentation tangentially mentions](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-logging#set-logging-levels) that "SDK source code frequently uses the statement `logging.getLogger(__name__)`". However it is not clear to an outsider that this pattern would lead to logging being unreadable from the same call within my own custom module. 
There appears to be some behaviour where even within my custom code (e.g. `myapp/src/my_training_module.py`, when I call `logging.getLogger(__name__)` (where in this case `__name__` should evaluate to `my_training_module`), this logger is somehow already taken by the azure SDK.

I solved the problem by changing getLogger calls in my own code with an extra prefix to the logger name, i.e. 
`logger = logging.getLogger(f"azlog_{__name__}")`

But this is a sub-optimal solution. I posit that this is a BUG, not a FEATURE, if the Azure python SDK is constructed in such a way that using the recommended pattern of Python's standard library logging module leads to a silent and unexplained failure to produce logs.

1. The requested action is to fix/change the Azure SDK so this behaviour no longer occurs.
2. Until such time that this fix is available, this poor logging behaviour and the recommended options to create a workaround solution (such as the extra prefix solution above) are documented clearly and crosslinked to from any locations within the Microsoft Azure SDK documentation to make it easy to search and find.

**Comment by banibrata-de** [comment]
Thanks for reporting this, we added it to our backlog to look into it, but don't have a timeline now to share.

**Comment by pat-hearps** [comment]
How about some better documentation at least?
