### ISSUE TITLE
Angle for OCR in azure ai imageanalysis

### ISSUE THREAD

**Issue by MaurusGubser** [Azure/azure-sdk-for-python#35117]
**Is your feature request related to a problem? Please describe.**
We used the library `azure-ai-vision` (https://pypi.org/project/azure-ai-vision/) to extract text from images. When analyzing an image, this library included information about the inferred angle of the image. This helped us to detect if an image was rotated.
Since this library was yanked, we changed to the `azure-ai-vision-imageanalysis` library. This basically works, however, there is no information provided about the rotation angle of the image.

**Describe the solution you'd like**
It would be great, if the inferred angle of the image is part of the answer from the `azure-ai-vision-imageanalysis` response.

**Describe alternatives you've considered**
We found this documentation https://learn.microsoft.com/en-us/rest/api/computervision/recognize-printed-text/recognize-printed-text?view=rest-computervision-v3.1&tabs=HTTP where a parameter `textAngle` is provided in the answer from the service. However, I believe this library is not the most current one.

**Comment by kristapratico** [comment]
Thanks for your feature request @MaurusGubser, we'll take a look and get back to you as soon as possible.

**Comment by dargilco** [comment]
Thank you @MaurusGubser for opening this issue. I will communicate this request to the relevant folks in the service team. The REST API for Image Analysis OCR was simplified during the preview period, before it was made generally available to the public. That included no longer delivering the text angle as you noticed. 

As an alternative, please consider using the [Document Intelligence](https://learn.microsoft.com/azure/ai-services/document-intelligence/) service. The OCR there has much more advanced features than Image Analysis OCR.

**Comment by Dybe** [comment]
@MaurusGubser 

Image Analysis Read API is optimized for general, non-document images. We removed global textAngle from Image Analysis OCR because it is not well-defined for non-document images. You can calculate the text angle for each returned text line from the bounding_polygon using sample code below:

        polygon = line.bounding_polygon
        left_center_x = (polygon[0].x + polygon[3].x) / 2
        left_center_y = (polygon[0].y + polygon[3].y) / 2
        right_center_x = (polygon[1].x + polygon[2].x) / 2
        right_center_y = (polygon[1].y + polygon[2].y) / 2
        text_angle = math.atan2(right_center_y - left_center_y, right_center_x - left_center_x)

If you are processing documents or images of documents we encourage you to use [Document Intelligence Read API](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-read?view=doc-intel-4.0.0) which still returns textAngle in the API response.

**Comment by MaurusGubser** [comment]
@dargilco @Dybe  Thanks for suggestion to use the Document Intelligence service. We don't work with documents, we use  images, but we can assume the text is always oriented in the same way. Thus we should be able to use the angle of detected text to obtain information about the orientation of the image.

@Dybe Thanks, your solution works fine; I did not realize the bounding polygons are always oriented corresponding to the detected text. Just one remark, for our purposes, we use

```python
math.atan2(-(right_center_y - left_center_y), right_center_x - left_center_x)
```

because of the orientation of the y-axis for images.
