### ISSUE TITLE
Unable to retrieve AzureDataLakeGen2Datastore datastore - SDKv2

### ISSUE THREAD

**Issue by obiii** [Azure/azure-sdk-for-python#35114]
- **Package Name**: 
- **Package Version**: SDKv2
- **Operating System**:
- **Python Version**: 3.11
- 
Hi, we are migration to SDKv2, and facing few problems.

**The bug**
1. Unable to get datastore (created by SDKv1) using SDKv2 using managed identity authentication.
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/614d716f-9f7b-4f28-a25c-00006c144a07)

2. Unable to get datastore (created by SDKv2) using SDKv2 using managed identity authentication. The datastore is created but the `**Subscription ID**` and `**Resource Group Name**` are empty.

![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/f5189e0f-5f4d-4f13-8c50-136325112a1b)

**To Reproduce**
```
from azure.ai.ml import MLClient
from azure.identity import ManagedIdentityCredential
from azure.ai.ml.entities import AzureDataLakeGen2Datastore
from azure.storage.filedatalake import DataLakeServiceClient
from azure.core.exceptions import ResourceExistsError

def managed_identity_auth(func):
    def wrapper(*args, **kwargs):
        credentials = ManagedIdentityCredential(client_id=<my_client_id>)
        return func(credentials, *args, **kwargs)
    return wrapper

@managed_identity_auth
def create_datastore(credentials):
    # Authenticate with Azure using the provided credentials
    ml_client = MLClient(credential=credentials, subscription_id=<subscripton_id>, resource_group_name=<rg_name>, workspace_name=<workspace_name>)

    # Create a new file system (container) in Azure Data Lake Storage Gen2
    storage_account_name = <storage_account_name>
    file_system_name = "sdkv2-test2"

    service_client = DataLakeServiceClient(account_url=f"https://{storage_account_name}.dfs.core.windows.net", credential=credentials)
    file_system_client = service_client.get_file_system_client(file_system=file_system_name)
    try:
        file_system_client.create_file_system()
        print(f"Created file system: {file_system_name}")
    except ResourceExistsError:
        print(f"File system {file_system_name} already exists.")

    # Create the Azure Data Lake Storage Gen2 Datastore using the managed identity
    adls_gen2_datastore = AzureDataLakeGen2Datastore(
        name="sdkv2_datastore2",
        account_name=storage_account_name,
        filesystem=file_system_name
    )
    ml_client.datastores.create_or_update(adls_gen2_datastore)


@managed_identity_auth
def get_datastore(credentials, subscription_id, resource_group_name, datastore_name):
    ml_client = MLClient(subscription_id=subscription_id, 
                         resource_group_name=resource_group_name,
                         credential=credentials
    )
    datastore = ml_client.datastores.get(name=datastore_name)
    return datastore

create_datastore()
get_datastore(subscription_id=<subscription_id>, resource_group_name=<rg_name>, datastore_name=<datastore_name>)
```

**Expected behavior**
1.There should be Subscription ID and RG Name in the created datastore, currently its empty:
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/4c767dff-03d3-46be-933e-142a3391cdbc)

2. It should just return the existing datastore, currently returns:  ***** ValueError: No value for given attribute**

**Comment by kristapratico** [comment]
Thanks for your issue @obiii. Can you also share the version of azure-ai-ml that you are using? @azureml-github will take a look.

**Comment by justkr** [comment]
Hi, I have the same problem while migrating to to SDKv2.

**Comment by banibrata-de** [comment]
Currently this is not supported, we added it to our feature request to triage it  as a feature ask.
