### ISSUE TITLE
azure vnet subnet usage data

### ISSUE THREAD

**Issue by xiaopeng163** [Azure/azure-sdk-for-python#35139]
- **Package Name**:  azure-mgmt-network 
- **Package Version**:  25.3.0
- **Operating System**:  MacOS Sonoma 14.4.1
- **Python Version**:  3.11.7

**Describe the bug**

test code

```
from azure.identity import DefaultAzureCredential
from azure.mgmt.network import NetworkManagementClient

"""
# PREREQUISITES
    pip install azure-identity
    pip install azure-mgmt-network
# USAGE
    python virtual_network_list_usage.py

    Before run the sample, please set the values of the client ID, tenant ID and client secret
    of the AAD application as environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID,
    AZURE_CLIENT_SECRET. For more info about how to get the value, please see:
    https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal
"""


def main():
    client = NetworkManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id="*********",
    )

    response = client.virtual_networks.list_usage(
        resource_group_name="rg********",
        virtual_network_name="vnet-********",
    )
    for item in response:
        print(item)
```

one of the item is

```
{'additional_properties': {'isAdjustable': False}, 'current_value': -1.0, 'id': '/subscriptions/**********, 'limit': -1.0, 'name': <azure.mgmt.network.models._models.VirtualNetworkUsageName object at 0x1078e8b90>, 'unit': 'Count'}
```

**the value of current_value and limit are -1.0 which is not correct I think.**

**To Reproduce**

```
from azure.identity import DefaultAzureCredential
from azure.mgmt.network import NetworkManagementClient

"""
# PREREQUISITES
    pip install azure-identity
    pip install azure-mgmt-network
# USAGE
    python virtual_network_list_usage.py

    Before run the sample, please set the values of the client ID, tenant ID and client secret
    of the AAD application as environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID,
    AZURE_CLIENT_SECRET. For more info about how to get the value, please see:
    https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal
"""


def main():
    client = NetworkManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id="*********",
    )

    response = client.virtual_networks.list_usage(
        resource_group_name="rg********",
        virtual_network_name="vnet-********",
    )
    for item in response:
        print(item)
```

**Expected behavior**

the correct value of vnet/subnet usage data

**Screenshots**

**Additional context**

**Comment by ChenxiJiang333** [comment]
Hi @xiaopeng163 I failed to reproduce this issue, and since the properties' values were returned by the service, please follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to get detailed log for deep investigation.

**Comment by xiaopeng163** [comment]
<img width="2595" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/5743757/e40603e9-081d-45b9-8220-dc67fc3b9a71">
FYI

**Comment by xiaopeng163** [comment]
ok, make sense.

another question or feature request from our side is,  if both IPv4 and IPv6 enabled for the subnet, is that possible to have separated data for them in the usage report? like:

```
{
    "current_value_v4" : 1, 
    "current_value_v6": 2,
    "limit_v4": xxxxxx,
    "limit_v6": xxxxxx
    ....
}
```

**Comment by ChenxiJiang333** [comment]
> ok, make sense.
> 
> another question or feature request from our side is, if both IPv4 and IPv6 enabled for the subnet, is that possible to have separated data for them in the usage report? like:
> 
> ```
> {
>     "current_value_v4" : 1, 
>     "current_value_v6": 2,
>     "limit_v4": xxxxxx,
>     "limit_v6": xxxxxx
>     ....
> }
> ```

Here's the related swagger https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-11-01/virtualNetwork.json#L2148, python sdk is just a tool to call its api, to request feature, you need to turn to the service team by opening an issue at https://github.com/Azure/azure-rest-api-specs/tree/main.
