### ISSUE TITLE
Same issue - cannot import name 'AzureOpenAIEmbeddingSkill' from 'azure.search.documents.indexes.models'

### ISSUE THREAD

**Issue by misslapina123** [Azure/azure-sdk-for-python#35140]
Took offline. This is by design.

_Originally posted by @xiangyan99 in https://github.com/Azure/azure-sdk-for-python/issues/33597#issuecomment-1861054694_

Same issue:
azure-search-documents: 11.4.0
Python: 3.11

**Describe the bug**
_ImportError: cannot import name 'AzureOpenAIEmbeddingSkill' from 'azure.search.documents.indexes.models'_

**To Reproduce**
Simply try to import it:

```
from azure.search.documents.indexes.models import (
    AzureOpenAIEmbeddingSkill
)
```

**Expected behavior**
It should import this type. It is referenced in most tutorials... without it, the library is unusable.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

This feature is still under preview.

Please use latest preview version: https://pypi.org/project/azure-search-documents/11.6.0b3/

**Comment by sarvarip** [comment]
@xiangyan99 your link doesn't mention embedding at all, so it's not a suitable answer for the question. 
Normally preview features can still be used, so I don't think preview is the issue here.
In any case, if something is not available yet, maybe avoid putting it in tutorials so people don't get confused?

**Comment by misslapina123** [comment]
@xiangyan99 using azure-search-documents==11.6.9b3 did not help, I still encounter the same issue. 

`ImportError: cannot import name 'AzureOpenAIEmbeddingSkill' from 'azure.search.documents.indexes.models'`

![image](https://github.com/Azure/azure-sdk-for-python/assets/136738469/18f9e523-cd6e-4dbe-9986-d6a5fcaf3546)

**Comment by misslapina123** [comment]
Thanks @xiangyan99 ! 

Using `azure-search-documents==11.6.0b3` solved the import error.
