### ISSUE TITLE
Update Azure Machine Learning Compute Instances with Python SDKv2

### ISSUE THREAD

**Issue by jayashankargs** [Azure/azure-sdk-for-python#35156]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.8.0
- **Operating System**: Linux -  20.04.1-Ubuntu
- **Python Version**: 3.8.5

**Describe the bug**
The `ml_client.begin_create_or_update` operation for updating the existing compute instance  giving me the below warning and error.

**Warning** : 'Location' is not supported for compute type computeinstance and will not be used.
**Error** : AttributeError: 'NoneType' object has no attribute 'lower'

But the same operation works fine when updating `AmlCompute`.

**To Reproduce**
1.  Below is the code i'm using to update.

```python
schedule_start_time = datetime.now()
from azure.ai.ml.entities import ComputeInstance,AmlCompute

for compute_instance in ml_client.compute.list():
    if compute_instance.name == "v-jgs9":
        rec_trigger = RecurrenceTrigger(start_time="2024-01-10T00:00:00", time_zone=TimeZone.CENTRAL_EUROPEAN_STANDARD_TIME , frequency="day", interval=1, schedule=RecurrencePattern(hours=20, minutes=[0]))
        myschedule = ComputeStartStopSchedule(trigger=rec_trigger, action="stop")
        com_sch = ComputeSchedules(compute_start_stop=[myschedule])
        compute_instance.schedules = com_sch
        compute_instance.idle_time_before_shutdown = "PT30M"
        compute_instance.idle_time_before_shutdown_minutes = 30
        ml_client.begin_create_or_update(compute_instance)
```

**Expected behavior**
The `idle_time_before_shutdown`  and `schedules` should have updated instead it giving me the error.

**Screenshots**

Error screenshot.

![](https://i.imgur.com/DmqIdoz.png)

**Additional context**
I have tried with creating new compute instance object giving current instance name the code works but in portal the `idle_time_before_shutdown ` and `schedules` shows blank.

Below is the code.

```python
schedule_start_time = datetime.now()
from azure.ai.ml.entities import ComputeInstance,AmlCompute

for compute_instance in ml_client.compute.list():
    if compute_instance.name == "v-jgs9":
        rec_trigger = RecurrenceTrigger(start_time="2024-01-10T00:00:00", time_zone=TimeZone.CENTRAL_EUROPEAN_STANDARD_TIME , frequency="day", interval=1, schedule=RecurrencePattern(hours=20, minutes=[0]))
        myschedule = ComputeStartStopSchedule(trigger=rec_trigger, action="stop")
        com_sch = ComputeSchedules(compute_start_stop=[myschedule])
        compute_instance.schedules = com_sch
        my_compute = ComputeInstance(name="v-jgs9",idle_time_before_shutdown="PT30M",idle_time_before_shutdown_minutes=30,schedules=com_sch)
        ml_client.begin_create_or_update(my_compute)
```

Output:

![](https://i.imgur.com/KgleM93.png)

But in portal shows blank.

![](https://i.imgur.com/QBU5Vin.png)

**Comment by Uranium2** [comment]
This issue is related to my stackoverflow post here: https://stackoverflow.com/questions/78303180/update-azure-machine-learning-compute-instances-with-python-sdkv2

**Comment by kristapratico** [comment]
Thanks for your issue @Uranium2, @azureml-github will take a look and get back to you as soon as possible.

**Comment by banibrata-de** [comment]
This could be a bug in our SDK code, have you tried updating/adding the schedule from the UI and did it worked?

**Comment by jayashankargs** [comment]
yes it worked from the UI.

**Comment by Uranium2** [comment]
I aslo confirm that it works in UI.
I know it's not the same project, but if someone could up also the same feature for terraform, it could be amazing. Originally I'm creating compute instances in terraform and wanted to add a schedule and idle shutdown. But the feature is not yet done in terraform. This is why I went with the python alternative. 
https://github.com/hashicorp/terraform-provider-azurerm/issues/20973

**Comment by banibrata-de** [comment]
Ok, good that you are at least unblocked using UI, let me add a backlog item to track this, however we  don't have an ETA now, we need to talk about this ask within the team and prioritize.

**Comment by Uranium2** [comment]
For me I'm blocked because UI is not automation, so whenever I create Compute instances automatically (for example 10 or 20 for new users), I have to go on UI after my CICD script to add schedule/IDLE one by one after our daily CICD. And since terraform issue is opened since nearly a year now, there's been not a single automation possible for this feature that could save a LOT of money and a lot of electricity.
