### ISSUE TITLE
AttributeError: 'NetworkManagementClient' object has no attribute 'public_ip_prefixes'

### ISSUE THREAD

**Issue by spoloj** [Azure/azure-sdk-for-python#3518]
Im trying to test this resource provider operation `"Microsoft.Network/publicIPPrefixes/write"` using Pytest. and tried with different attributes of public_ip prefixes but always the same AttributeError 
'NetworkManagementClient' object has no attribute 'public_ip_prefixes'.
the version im using is `azure-mgmt-network==1.7.1`.
below is the sample code 
```
def test_create_public_ip_prefix():
	parameters = {
	    "PublicIPPrefix": {
	    	"location": "westus2",
	        "name": "ipprefix",
	        "sku": "Basic",
	        "publicIpAddressVersion": "IPv4",
	        "prefix_length":"/30"
	        }
	        }
	az_response=network_client.public_ip_prefixes.create_or_update(GROUP_NAME, PUB_IP_PREFIX_NAME, parameters)
```
Can someone please help me with this issue.

**Comment by lmazuel** [comment]
Hi @spoloj 
As mentionned in the ChangeLog on PyPI, public ip prefixes were introduced in 2.1.0:
https://pypi.org/project/azure-mgmt-network/

Update the package and you should be fine :)

Thank you,
