### ISSUE TITLE
Has the HnswVectorSearchAlgorithmConfiguration beed moved?

### ISSUE THREAD

**Issue by vlavorini** [Azure/azure-sdk-for-python#35183]
Hello,

I tried the versions 11.4.0 and 11.6.0b3 of `azure-search-documents` for Python, but the module `HnswVectorSearchAlgorithmConfiguration`, present in version 11.4.0b11, is not there.

Has it been moved somewhere else, or is it deprecated? Does it exist an alternative, non-breaking implementation?

Thank you!

**Comment by xiangyan99** [comment]
It is renamed to `HnswAlgorithmConfiguration`.

Thanks.
