### ISSUE TITLE
Typings for azure.identity wrong in 1.16.0, causing issues with pyright

### ISSUE THREAD

**Issue by aersam** [Azure/azure-sdk-for-python#35184]
- **Package Name**: azure-identity
- **Package Version**: 1.16.0
- **Operating System**: Windows
- **Python Version**: 3.11

**Describe the bug**
running pyright for this code:

```python
with InteractiveBrowserCredential() as credential:
        return credential.get_token(POWERBI_API_SCOPE).token
```
gives `error: Cannot access member "get_token" for type "MsalCredential"`

This is because in msal_credentials.py, `__enter__` is typed wrong:
```def __enter__(self) -> "MsalCredential":```

instead it should be:
```python

from typing_extensions import Self

def __enter__(self) -> "Self":
```

**Comment by scottaddie** [comment]
@xiangyan99 Can this issue be closed now? I see a linked PR.

**Comment by xiangyan99** [comment]
Usually we mark it "issue-addressed" when we ship the release. :)
