### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED error when using Form Recogniser and Document Intelligence SDK for python

### ISSUE THREAD

**Issue by Aizen-sama214** [Azure/azure-sdk-for-python#35197]
- **Package Name**: Form Recogniser
- **Package Version**: v3.2
- **Operating System**: Windows 10
- **Python Version**: 3.11.4

**Describe the bug**

**To Reproduce**
1. Run the async samples code provided in https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/async_samples/sample_analyze_layout_async.py

**Expected behavior**

**Error on Console**
azure.core.exceptions.ServiceRequestError: Cannot connect to host {myendpoint}.cognitiveservices.azure.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]

```[tasklist]
### Tasks
```

**Comment by Aizen-sama214** [comment]
hi @xiangyan99 , I am using document analysis client of form recogniser of azure.ai.formrecognizer.aio and v 3.2

**Comment by xiangyan99** [comment]
Thank you. Could you also provide the version information of 
azure-core
aiohttp?

**Comment by Aizen-sama214** [comment]
azure-core==1.30.1
aiohttp==3.9.3
azure-ai-formrecognizer==3.3.0

**Comment by xiangyan99** [comment]
Thank you.

I tried it in my local devbox but could not repro it.

Could you share more context about the repro?

**Comment by Aizen-sama214** [comment]
This is my code : 
    path_to_sample_documents = "./downloads/tabs-Full-stack Engineer Assignment.pdf"

    from azure.core.credentials import AzureKeyCredential
    from azure.ai.formrecognizer.aio import DocumentAnalysisClient

    endpoint = os.environ["AZURE_FORM_RECOGNIZER_ENDPOINT"]
    key = os.environ["AZURE_FORM_RECOGNIZER_KEY"]

    
    document_analysis_client = DocumentAnalysisClient(
        endpoint=endpoint, credential=AzureKeyCredential(key)
    )
    print(document_analysis_client)
    async with document_analysis_client:
        with open(path_to_sample_documents, "rb") as f:
            poller = await document_analysis_client.begin_analyze_document(
                "prebuilt-layout", document=f
            )
        result = await poller.result()


and my error :
azure.core.exceptions.ServiceRequestError: Cannot connect to host docextractor214.cognitiveservices.azure.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]

**Comment by xiangyan99** [comment]
Thank you.

I tried your code but I could not repo the failure.

Did you have a chance to try using some other environments?

**Comment by chnlyi** [comment]
I have experienced the same problem in my local laptop. But the problem is gone in azure compute instance.
aiohttp==3.9.3
azure-core==1.29.5
My Code:
`import os 
import asyncio
from azure.ai.formrecognizer.aio import DocumentAnalysisClient
from azure.core.credentials import AzureKeyCredential
from dotenv import load_dotenv
load_dotenv()

formrecognizerservice = os.getenv('FORMS_RECOGNIZER_SERVICE')
endpoint =f"https://{formrecognizerservice}.cognitiveservices.azure.com/"
credential = AzureKeyCredential(os.getenv('FORMS_RECOGNIZER_KEY'))

client = DocumentAnalysisClient(endpoint, credential, verify=False)

async def rum():
    res = await client.begin_analyze_document_from_url("prebuilt-layout", "https://www.irs.gov/pub/irs-pdf/fw4.pdf")
    print(res.result())

loop = asyncio.get_event_loop()
loop.run_until_complete(rum())
loop.close()`
