### ISSUE TITLE
Issue with Load Balancer FrontendIPConfiguration

### ISSUE THREAD

**Issue by spoloj** [Azure/azure-sdk-for-python#3519]
When trying to create Loadbalancer with Public-ip configuration and default values, It is creating loadbalancer but not the public ip address. when Im trying to add manually
this is the error i'm seeing 

![image](https://user-images.githubusercontent.com/44011132/46709769-2b6feb00-cc13-11e8-97bb-24dd8c5ab728.png)

sample code:
```
network_client.load_balancers.create_or_update(GROUP_NAME,LOAD_BALANCER_NAME,
		{
		"location":"eastus",
		"FrontendIPConfiguration":[{
		# "name": "LoadBalancerFrontEnd",
		"publicIpAddress": {
		#"id": 
		"location":"eastus",
		 "sku": "Basic",
		 "name": "testpub",
		 "publicIPAllocationMethod": "Dynamic",
	         "idleTimeoutInMinutes": 4,
	         "publicIpAddressVersion": "IPv4",
	         "domainNameLabel": "myip"
		}
		}
                ]
		}
		)
```
can someone correct me where I went wrong and anything more about that error?

**Comment by lmazuel** [comment]
You need to create the publicIP before, and assign it at creation time:
https://github.com/Azure-Samples/network-python-manage-loadbalancer
