### ISSUE TITLE
Python client gives wrong error message when you misspell a character filter

### ISSUE THREAD

**Issue by jvans1** [Azure/azure-sdk-for-python#35208]
- **Package Name**: 
- azure-search-documents
- **Package Version**: 
- 11.4.0
- **Operating System**:
- mac osx
- **Python Version**: 
- 3.11.4

**Describe the bug**
Spelling a character filter wrong creates an incorrect error message that complains of a missing tokenizer.

**To Reproduce**

1.  Try to create an index with the python client and this config:
```

{'name': 'test_index',
 'fields': [{'name': 'search_field',
   'type': 'Edm.String',
   'retrievable': True,
   'filterable': True,
   'sortable': True,
   'facetable': False},
  {'name': 'id',
   'type': 'Edm.String',
   'key': True,
   'retrievable': True,
   'searchable': True,
   'filterable': True}],
 'vectorSearch': None,
 'suggesters': [],
 'scoringProfiles': [],
 'analyzers': [{'name': 'mytestanalyzer',
   'tokenizer': 'classic',
   'charFilters': ['spelledwrong'],
   'tokenFilters': ['lowercase']}]}
```

The error message reports a missing tokenizer:

HttpResponseError: () The request is invalid. Details: definition : The analyzer 'mytestanalyzer' of type 'CustomAnalyzer' must specify a tokenizer.
Code: 
Message: The request is invalid. Details: definition : The analyzer 'mytestanalyzer' of type 'CustomAnalyzer' must specify a tokenizer.

**Expected behavior**
The java client gives the correct error message:

`The analyzer 'mytestanalyzer' uses a char filter 'spelledwrong' which is unknown or not supported in the API version used. Parameters: definition"`

**Comment by xiangyan99** [comment]
This error is directly from the service side. Please open a service ticket for investigation.

**Comment by mattgotteiner** [comment]
@jvans1 It appears you are using the python mode that takes a dictionary representation of the API request and turns it into the appropriate SDK representation. Unfortunately, your API request is not valid. You are missing an @odata.type specifier on your custom analyzer

```
{
 '@odata.type': '#Microsoft.Azure.Search.CustomAnalyzer',
  'name': 'mytestanalyzer',
   'tokenizer': 'classic',
   'charFilters': ['spelledwrong'],
   'tokenFilters': ['lowercase']
}
```

When I update this in the python SDK, the following code gives me the expected error message

```
from azure.search.documents.indexes.models import SearchIndex
from azure.search.documents.indexes import SearchIndexClient
from azure.identity import DefaultAzureCredential

credential = DefaultAzureCredential()
endpoint = "https://magottei-s1m.search.windows.net"

client = SearchIndexClient(endpoint, credential)
client.create_or_update_index(SearchIndex.deserialize({'name': 'test_index',
 'fields': [{'name': 'search_field',
   'type': 'Edm.String',
   'retrievable': True,
   'filterable': True,
   'sortable': True,
   'facetable': False},
  {'name': 'id',
   'type': 'Edm.String',
   'key': True,
   'retrievable': True,
   'searchable': True,
   'filterable': True}],
 'vectorSearch': None,
 'suggesters': [],
 'scoringProfiles': [],
 'analyzers': [{'name': 'mytestanalyzer',
   '@odata.type': '#Microsoft.Azure.Search.CustomAnalyzer',
   'tokenizer': 'classic',
   'charFilters': ['spelledwrong'],
   'tokenFilters': ['lowercase']}]}))
```

The error:
```
Code: InvalidRequestParameter
Message: The request is invalid. Details: definition : The analyzer 'mytestanalyzer' uses a char filter 'spelledwrong' which is unknown or not supported in the API version used.
```
