### ISSUE TITLE
Trying to get my WAF mode (and more if possible) with the Python Azure SDK

### ISSUE THREAD

**Issue by Stantrh** [Azure/azure-sdk-for-python#35202]
- **Package Name**: azure.mgmt.network
- **Package Version**: 25.3.0
- **Operating System**: Windows 10
- **Python Version**: 3.11.7

**Describe the bug**
Hello, I am currently making a python script that can get data from AzureMonitor for a WAF, to be able to make statistics about the WAF logs. So for that, i'd need to get the WAF mode (detection or prevention) to be able to use a different request in function of the type of the WAF mode.
What I did, i made a connection using azure.identity DefaultAzureCredential
```from azure.identity import DefaultAzureCredential
from azure.mgmt.network import NetworkManagementClient
import os

os.environ["AZURE_CLIENT_ID"] = "XXX"
os.environ["AZURE_TENANT_ID"] = "XXX"
os.environ["AZURE_CLIENT_SECRET"] = "XXX"
credentials = DefaultAzureCredential()
```

Then, I tried to make a NetworkManagementClient using my subscription id and the credentials I made earlier.
```subscription_id = 'XXX'
network_client = NetworkManagementClient(credentials, subscription_id)
```

To finish, I tried to get access to the ApplicationGateway of the WAF I want to analyze, which I verified, returns me a real application gateway object, with the right tags defined on Azure Portal.
I read the doc : https://learn.microsoft.com/en-sg/python/api/azure-mgmt-network/azure.mgmt.network.models.applicationgateway?view=azure-python

And I saw that you can get the WAF configuration via : web_application_firewall_configuration and then the firewall_mode property.
But my code keeps returning me None as the web_application_firewall_configuration object. I tried to search on the web etc. but can't find any answer to my question.
Here's the final code, and the output : 
```application_gateway = network_client.application_gateways.get('hub-asteria-dev-rg', 'asteria-nprod-web-ag')
# print(str(application_gateway))
print(str(application_gateway.web_application_firewall_configuration))
# returns None, while on Azure portal my WAF is here and existing
```

**To Reproduce**
1. Just put the code parts i put above together and replace with your Azure ids and it should work.

**Expected behavior**
I should be able to get a not None object that represents the WAF configuration of my AG.

**Comment by ChenxiJiang333** [comment]
Hi, @Stantrh what's the tier of your ApplicationGateway? WAF or WAF_v2?

**Comment by Stantrh** [comment]
> Hi, @Stantrh what's the tier of your ApplicationGateway? WAF or WAF_v2?

Hey, it's WAF V2

**Comment by ChenxiJiang333** [comment]
It might be a service problem that only return the web_application_firewall_configuration object with tier waf, but not waf_v2.
I have opened an [issue](https://github.com/Azure/azure-rest-api-specs/issues/25329) for it before that you could follow it to get some news.

**Comment by ChenxiJiang333** [comment]
> If you're interested, I could tell you another way I used to get access to my WAF config, even if it's tier 2

Is that still using the package `azure.mgmt.network` ?

**Comment by Stantrh** [comment]
> > If you're interested, I could tell you another way I used to get access to my WAF config, even if it's tier 2
> 
> Is that still using the package `azure.mgmt.network` ?

Hey, sorry for the late response, was in vacation. So i did use the package azure.mgmt.network.
I can here give you the code I wrote to still get my WAF infos.

```py
from azure.identity import DefaultAzureCredential
from azure.mgmt.network import NetworkManagementClient
import os, re

os.environ["AZURE_CLIENT_ID"] = "XXX"
os.environ["AZURE_TENANT_ID"] = "XXXX"
os.environ["AZURE_CLIENT_SECRET"] = "XXX"
credentials = DefaultAzureCredential()

id_res = '/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Network/applicationGateways/XXX-ag'
# then i extract from my id_res the resource group and the subscription id
nom_rg = re.search(r"resourceGroups/(.*?)/providers", id_res).group(1)
id_sub = re.search(r"/subscriptions/(.*?)/resourceGroups", id_res).group(1)

network_client = NetworkManagementClient(credentials, id_sub)

ag = network_client.application_gateways.get(nom_rg, 'my_ag_id_that_uses_my_waf')
config = ag.firewall_policy

# then i get my waf name after getting its id
id_waf = getattr(config, 'id')
nom_waf = re.search(r"/ApplicationGatewayWebApplicationFirewallPolicies/(.*)", id_waf).group(1)

# and here i get my WAF properties
wp = network_client.web_application_firewall_policies.get(nom_rg, nom_waf)
```

**Comment by ChenxiJiang333** [comment]
Never thought that, thanks for let me know this!
