### ISSUE TITLE
how to turn off automatic decompression when download gzipped file

### ISSUE THREAD

**Issue by imeya** [Azure/azure-sdk-for-python#3521]
when use the following to download gzipped file, The download works but Azure or the SDK decompresses my gzipped files on the fly when the files are fetched. 
how can I turn off this behavior? thanks

```
BLOB_SERVICE = BlockBlobService(account_name=AZURE_BLOB_SERVICE_ACCOUNT_NAME, account_key=AZURE_BLOB_SERVICE_ACCOUNT_KEY)

BLOB_SERVICE.get_blob_to_path(
            guid,
            name,
            path,
        )
```

**Comment by lmazuel** [comment]
Hi @imeya 
Storage questions can't be answered here unfortunately. Please re-open your issue on the Storage tracker:
https://github.com/Azure/azure-storage-python

Thank you,
