### ISSUE TITLE
Azure Service Bus receiver Invalid ReceiveMode Error

### ISSUE THREAD

**Issue by Binoyman** [Azure/azure-sdk-for-python#35214]
### Type of issue

Code doesn't work

### Description

Hello,
Recently  i found the need to use the Service Bus in receive_and_delete Mode using Azure Service Bus SDK for Python.
But with in the documentation there is no clear code or way on how to set the mode. 
The Document  just states as below - 

`
The receive_mode with which messages will be retrieved from the entity. The two options are PEEK_LOCK and RECEIVE_AND_DELETE. Messages received with PEEK_LOCK must be settled within a given lock period before they will be removed from the queue. Messages received with RECEIVE_AND_DELETE will be immediately removed from the queue, and cannot be subsequently rejected or re-received if the client fails to process the message. The default receive_mode is PEEK_LOCK.

But trying to set the receive mode to any of the below would give me error.

`
Traceback (most recent call last):
  File "myfile.py", line 71, in <module>
    with client.get_queue_receiver(queuename ,receive_mode='RECEIVE_AND_DELETE') as receiver:
  File "myenv/lib64/python3.9/site-packages/azure/servicebus/_servicebus_client.py", line 427, in get_queue_receiver
    handler = ServiceBusReceiver(
  File "myenv/lib64/python3.9/site-packages/azure/servicebus/_servicebus_receiver.py", line 215, in __init__
    self._populate_attributes(
  File "myenv/lib64/python3.9/site-packages/azure/servicebus/_common/receiver_mixins.py", line 39, in _populate_attributes
    self._receive_mode = ServiceBusReceiveMode(
  File "/usr/lib64/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib64/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'RECEIVE_AND_DELETE' is not a valid ServiceBusReceiveMode

Similarily got value errors for other variations

ValueError: 'receive_and_delete' is not a valid ServiceBusReceiveMode
ValueError: 'ServiceBusReceiveMode.RECEIVE_AND_DELETE' is not a valid ServiceBusReceiveMode
`

The Correct String to pass to the Receive Mode Turned out to be as below
`
receiver = servicebus_client.get_queue_receiver(queue_name, receive_mode='receiveanddelete')
`

Please Do let me know if i am making any mistakes in its use or what the correct way to set the receive mode would be if this seems to be wrong.
If not Please update the documentation to be a bit more userfriendly.

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/servicebus-readme?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/servicebus-readme.md

### Document Version Independent Id

ff2b2f4b-22df-7960-f3db-6d3e67d25f00

### Article author

@azure-sdk

### Metadata

* ID: 8fa61aeb-289e-7b6a-bd70-ba4055d456b0 
* Service: **service-bus-messaging**

**Comment by Binoyman** [comment]
After Digging into it i realized the way expected was to refer to it using  ServiceBusReceiveMode.RECEIVE_AND_DELETE . But the Python Definition says the expected value for it is a String hence the confusion and the error at 'ServiceBusReceiveMode.RECEIVE_AND_DELETE'. I hope we can update more clearly in the Documentation on the right way to change the mode.

**Comment by kashifkhan** [comment]
Thank you for the feedback @Binoyman. Ill update the file to include an example to set the receive mode and that should get the docs updated as well. In general our typing for enums allows for the enum or the value represented by that enum as valid input https://learn.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebusreceiver?view=azure-python
