### ISSUE TITLE
The list method does not return all subscripitoin information

### ISSUE THREAD

**Issue by Fred-sun** [Azure/azure-sdk-for-python#35224]
- **Package Name**:  azure-mgmt-resource
- **Package Version**:  v21.1.0
- **Operating System**:  Ubuntu
- **Python Version**: v3.8.0

**Describe the bug**
https://github.com/Azure/azure-sdk-for-python/blob/9e9d5ebfddf73248c4003ec001c8bfe204c549cb/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_operations.py#L455,This method should get all subscription. But it only returns me the details about the subscription info for the ID provided. 
**To Reproduce**
****.subscriptions.list()
**Expected behavior**
Return all subscrition facts
**Screenshots**

**Additional context**

**Comment by ChenxiJiang333** [comment]
Hi, @Fred-sun I was succeeded to to list all subscriptions under my tenant though... Make sure you followed this [sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resource/generated_samples/subscriptions/get_subscriptions.py#L31), and please follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to provide detailed log for deep investigation.

**Comment by Fred-sun** [comment]
@ChenxiJiang333 Ye, you can obtain the subscription information local cached by az login.  If you use other authorization methods.  you can't get the subscription infomation.  Such as you can consider using ClientSecretCredential or EnvironmentCredential instead of az login.  Thank you!!

**Comment by ChenxiJiang333** [comment]
> @ChenxiJiang333 Ye, you can obtain the subscription information local cached by az login. If you use other authorization methods. you can't get the subscription infomation. Such as you can consider using ClientSecretCredential or EnvironmentCredential instead of az login. Thank you!!

I see. It was because your principal didn't have the necessary [read permission](https://learn.microsoft.com/en-us/graph/permissions-reference#subscriptionreadall) among subscriptions under single tenant. To assign such permission, you may need to request the admin consent of the tenant as well, otherwise to authorize with AzureCliCredential is suggested.

**Comment by Fred-sun** [comment]
@ChenxiJiang333 Thank you for your reply. I will soon get authorization and try. Thank you!

**Comment by Fred-sun** [comment]
@github-actions @xiangyan99 Thanks for your help! It has been resolved!
