### ISSUE TITLE
test_multipart_files_content & test_multipart_data_and_files_content fail with aiohttp 3.9.4

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#35220]
#35212

**Comment by pvaneck** [comment]
Seems like this change: https://github.com/aio-libs/aiohttp/commit/cebe526b9c34dc3a3da9140409db63014bc4cf19#diff-d582bf292efb8e19696d88c895b99e0937687cb909d9d00b5c2f1d948a5cbae5R873 where they no longer add the `Content-Length` header in payloads for `multipart/form-data`.

The motivation was to conform to this RFC: https://datatracker.ietf.org/doc/html/rfc7578#section-4.8 where the `Content-Length` header is not allowed.
