### ISSUE TITLE
Calling HnswVectorSearchAlgorithmConfiguration as_dict() throws error

### ISSUE THREAD

**Issue by VincentMcLoughlin** [Azure/azure-sdk-for-python#35253]
- **Package Name**:  azure-search-documents
- **Package Version**:  11.4.0b8b
- **Operating System**: Ubuntu 20.04.6 LTS
- **Python Version**: 3.10.11

**Describe the bug**
Calling the .as_dict() method on any HnswVectorSearchAlgorithmConfiguration  throws an error. This also causes error when calling .as_dict() on a SearchIndex object containing a HnswVectorSearchAlgorithmConfiguration  object

**To Reproduce**
Call .as_dict() on any HnswVectorSearchAlgorithmConfiguration object

For example, the following snippet throws an error on my machine

```
from azure.search.documents.indexes.models import (    
    HnswVectorSearchAlgorithmConfiguration,
)

Hnsw_m_parameter = 4
Hnsw_ef_construction = 400
Hnsw_ef_search = 500
vector_search_metric = "cosine"
vector_search_dim = 1536
example_config =  HnswVectorSearchAlgorithmConfiguration(
                name="vector-config-discover",
                kind="hnsw",
                parameters={
                    "m": 1,
                    "efConstruction": Hnsw_ef_construction,
                    "efSearch": Hnsw_ef_search,
                    "metric": vector_search_metric
                }
            )
example_config.as_dict()
```

**Expected behavior**
I expect it to return a dictionary containing information about the HnswVectorSearchAlgorithmConfiguration object.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/36211993/152bd6ed-ab57-4446-8331-7f92dad5d018)

**Additional context**
The error message from the screenshot is 

```
SerializationError: (", AttributeError: 'dict' object has no attribute '_attribute_map'", "Attribute None in object dict cannot be serialized.\n{'m': 1, 'efConstruction': 400, 'efSearch': 500, 'metric': 'cosine'}", AttributeError("'dict' object has no attribute '_attribute_map'"))

```

**Comment by xiangyan99** [comment]
Thanks for reaching out. Please try code like this:

```py
from azure.search.documents.indexes.models import (
    HnswAlgorithmConfiguration, HnswParameters
)

Hnsw_m_parameter = 4
Hnsw_ef_construction = 400
Hnsw_ef_search = 500
vector_search_metric = "cosine"
vector_search_dim = 1536
example_config = HnswAlgorithmConfiguration(
                name="vector-config-discover",
                kind="hnsw",
                parameters=HnswParameters(
                    m=1,
                    ef_construction=Hnsw_ef_construction,
                    ef_search=Hnsw_ef_search,
                    metric=vector_search_metric,
                )
            )
example_config.as_dict()
```

**Comment by VincentMcLoughlin** [comment]
Hi @xiangyan99 that does work! Only I had to change the import from HnswAlgorithmConfiguration to HnswVectorSearchAlgorithmConfiguration but I think that might have been a typo. Thank you for sending that. Is there any way we could change the HnswVectorSearchAlgorithmConfiguration object to reflect the fact that you won't have full functionality if you pass in the dictionary? It seems odd to allow for the passing of a dictionary when that causes some of the class methods to break. A more descriptive error message would also be helpful.
