### ISSUE TITLE
Http Error in Poller function of Azure Document intelligence

### ISSUE THREAD

**Issue by AdityaR-B** [Azure/azure-sdk-for-python#35267]
I am trying to custom extract fields like Title, Subtitle, Header, Footer from a policy document (pdf).

I am using the below code as suggested on your documentation.

from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeResult

endpoint = "https:<.........>cognitiveservices.azure.com/"
key = "**************************"

docUrl=r"https://<Storage_Name>.blob.core.windows.net/sample-99-container/xhygauscubc.pdf"

document_analysis_client = DocumentIntelligenceClient(endpoint=endpoint, 
    credential=AzureKeyCredential(key))

poller = document_analysis_client.begin_analyze_document(
    "prebuilt-document", docUrl)
result: AnalyzeResult = poller.result()

______________________________________________________________________________________________________________________
I am getting the below error in the poller.

Message: Invalid argument.
Inner error: {
    \"code\": \"ParameterMissing\",
    \"message\": \"The parameter urlSource or base64Source is required.\"
}"
}

**Comment by YalinLi0312** [comment]
Hi @AdityaR-B , thanks for your contact! The error is because the url is expected to pass through a "Request", can you try the code below?
```python
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest

poller = document_analysis_client.begin_analyze_document(
    "prebuilt-document", AnalyzeDocumentRequest(url_source=docUrl
)
result: AnalyzeResult = poller.result()
```
We also have a sample file you can follow: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_analyze_receipts_from_url.py

Thanks

**Comment by Goldziher** [comment]
/unresolve

Issue still persists with the newest version of the SDK.

1. please explicitly explain what is required - are raw bytes unsupported? do you have to provide a URL?
2. please update the typing of the library to reflect this, currently it does not require a request object.
3. using a request object fails with broken pipeline.
