### ISSUE TITLE
azure-identity logs env vars as error msg

### ISSUE THREAD

**Issue by nagworld9** [Azure/azure-sdk-for-python#35273]
- **Package Name**: azure-identity
- **Package Version**:  1.9.0
- **Operating System**: Mariner/Ubuntu 
- **Python Version**: 3.9.19

**Describe the bug**
`2024-04-18T21:47:20Z.868 [ERROR] [MainThread] Incomplete environment configuration. These variables are set: AZURE_CLIENT_ID
`
The error msg misleading when the actual authentication successful

**To Reproduce**
1. I set the user managed identity through environment variable AZURE_CLIENT_ID and calls DefaultAzureCredential

**Expected behavior**

The msg needs improvement and log as info than error when authentication successful and may be error/warning when authentication fails.

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for your feedback.

Could you share more details like what error message you expected to see?

And if possible, share some code snippets?

**Comment by nagworld9** [comment]
@xiangyan99 I don't expect to see error msg or no log is fine if the authentication successful.

For managed identity authentication, user need to set only AZURE_CLIENT_ID. But why it logs error as incomplete configuration. It only required that one variable.

`Incomplete environment configuration. These variables are set: AZURE_CLIENT_ID `

**Comment by xiangyan99** [comment]
This is by design because you use DefaultAzureCredential. It attempts EnvironmentCredential first and it fails.

The error message comes from EnvironmentCredential.

For more information, please see https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/README.md#defaultazurecredential

**Comment by nagworld9** [comment]
@xiangyan99 well, our logs filled with these error msg, as we create lot of vms in our automation
