### ISSUE TITLE
azure_monitor_configure() breaks when used with Credentials

### ISSUE THREAD

**Issue by codesmon** [Azure/azure-sdk-for-python#35303]
- Package - azure.monitor.opentelemetry
- Version - 1.4.0
- OS - Win 10 & Win 11
- Python - 3.10.11

**Describe the bug**
Using the correlated_logs sample (https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry/samples/logging/correlated_logs.py) - when we set the credentials (required for App Insights with local authentication turned off) we see 500 results coming back and no logs stored in AppInsights,

**To Reproduce**
1. Set up the sample as follows:

![image](https://github.com/Azure/azure-sdk-for-python/assets/18485862/9563d2c9-d0e4-4447-8e84-5e9772587af0)

Run it

**Expected behavior**
I expect to see the 6 logs in App Insights within a few minutes. When we run it, we do not see this. The first connection is AppInsights is successful:

![image](https://github.com/Azure/azure-sdk-for-python/assets/18485862/30b319fe-1509-40e9-b26d-b30aa5b06a64)

(interestingly, our connection string points to uk-south, but this connection is to westeurope)

Subsequent calls (we assume are the actually telemetry being sent) return a 500 response

![image](https://github.com/Azure/azure-sdk-for-python/assets/18485862/828ab3b9-f0db-4eca-8d0c-5d8f2fb8711b)

**Comment by lzchen** [comment]
@codesmon 

We only support clientsecret or managed identity methods of authentication. See samples [here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter/samples/authentication)

**Comment by jeremydvoss** [comment]
As Leighton mentioned, this is not one of the credential types we support. Additionally, I've tested and cannot reproduce this issue. When passing in even a Default credential, all 4 logs arrive as expected in a regular application insights resource (The log level is set at warn by default, so not all 6 are expected). Please check that your application insights resource is configured correctly, and that the connection string used is appropiate.

**Comment by jeremydvoss** [comment]
Why can't you use Managed credentials or secrets? Are you "on prem" or in Azure?
