### ISSUE TITLE
Reference url of Container class is incorrect

### ISSUE THREAD

**Issue by Wisteria30** [Azure/azure-sdk-for-python#35313]
### Type of issue

Typo

### Description

The JobTemplate documentation for Azure Container Apps Jobs is incomplete.

"Keyword-Only Parameters" refers to the Container class of containers in the official Python documentation, but in fact I thought "azure.mgmt.appcontainers. Container" should be linked.

Before: https://docs.python.org/3/library/typing.html#typing.Container
After: https://learn.microsoft.com/en-us/python/api/azure-mgmt-appcontainers/azure.mgmt.appcontainers.models.container?view=azure- python

Translated with www.DeepL.com/Translator (free version)

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-mgmt-appcontainers/azure.mgmt.appcontainers.models.jobtemplate?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-appcontainers/azure.mgmt.appcontainers.models.JobTemplate.yml

### Document Version Independent Id

476cd042-f8b4-0b6d-4fbd-08a81c3f4411

### Article author

@lmazuel

### Metadata

* ID: 1c9d633d-c158-f686-cda3-93a6ed634597

**Comment by ChenxiJiang333** [comment]
It might be the issue during the rendering, @rohit-ganguly could you help take a look at this?

**Comment by rohit-ganguly** [comment]
Investigating, thanks for the ping

**Comment by rohit-ganguly** [comment]
@Wisteria30 Thanks for opening this issue! We're in the process of upgrading our Sphinx version from 6 to 7+ on our Microsoft Learn docs. When generating docs with v7 locally, we see the proper cross-reference: 
![image](https://github.com/Azure/azure-sdk-for-python/assets/20001884/46efb74c-34df-408e-a074-9d5467586318)


cc @ChenxiJiang333 @kristapratico @lmazuel @kyle-patterson FYI
