### ISSUE TITLE
Connection Reset by Peer in Function App 

### ISSUE THREAD

**Issue by obs-gh-nikhildua** [Azure/azure-sdk-for-python#35319]
- **Operating System**: Linux 
- **Python Version**: 3.9 

**Describe the bug**
Hi there! Not sure if this is directly related to Python or Function app issue. We have a function app that is running on Azure located here: https://observeinc.s3.us-west-2.amazonaws.com/azure/azure-collection-functions-0.11.0.zip

About 5-10% of the invocations, we see a "Connection Reset by Peer" issue and unsure how to resolve it.  We're also not sure if its detrimental if this causes the function worker to crash, as the function app is responsible for sending data externally and we don't want data to get dropped if this error is seen. 

**To Reproduce**
1. Run Function App for a while to collection invocations

**Expected behavior**
Error should not occur

**Screenshots**

<img width="1663" alt="Screenshot 2024-04-23 at 11 31 59 AM" src="https://github.com/Azure/azure-sdk-for-python/assets/124205220/6ed674a6-05e4-4d12-8d6a-f18710b16225">

Error:
```
Full Exception :
 Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException : python exited with code 255 (0xFF) 
 System.Exception : urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),    raise ConnectionError(err, request=request),requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))    End of inner exception

```

**Additional context**

**Comment by obs-gh-nikhildua** [comment]
I have tried increasing the FUNCTIONS_WORKER_PROCESS_COUNT to 2 and still saw the same issue.

**Comment by obs-gh-nikhildua** [comment]
Hi there! Wanted to see if anyone had a chance to look into this error? Thank you!

**Comment by xiangyan99** [comment]
It seems like a service issue.

Please open a service ticket for the help.
