### ISSUE TITLE
Code: BadRequest Message: The JSON provided in the request body is invalid. Property 'sizeWindow' value is not convertible to type 'System.Int32'.

### ISSUE THREAD

**Issue by jp250739** [Azure/azure-sdk-for-python#35339]
- **azure-mgmt-streamanalytics**: 
- **Version: 1.0.0**: 
- **Window 10**:
- **Python 3.11.8**: 

**Describe the bug**
during creation of stream analytics jobs via sdk 

**To Reproduce**
1. script is attached to reproduce issue.

**Expected behavior**
new stream analytics jobs need to be created and run via script.
[ASAJobCreation.txt](https://github.com/Azure/azure-sdk-for-python/files/15092350/ASAJobCreation.txt)

**Screenshots**

**Additional context**

**Comment by ChenxiJiang333** [comment]
Hi @jp250739 This bug should has been fixed with azure-mgmt-streamanalytics==2.0.0b2, please use that version and try.

**Comment by jp250739** [comment]
Hi @ChenxiJiang333  now i am getting below error.
raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (422) The required property 'timeWindow' is missing from the request.
Code: 422
Message: The required property 'timeWindow' is missing from the request

**Comment by ChenxiJiang333** [comment]
> Hi @ChenxiJiang333 now i am getting below error. raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat) azure.core.exceptions.HttpResponseError: (422) The required property 'timeWindow' is missing from the request. Code: 422 Message: The required property 'timeWindow' is missing from the request

Hi, have you changed the request content after that? I used the script you gived and it worked well.
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/dcf146f7-3f6a-4b35-85b8-db509e77a1ae)

**Comment by jp250739** [comment]
Hi @ChenxiJiang333  i noted this as well. this created job and configured input and output. checking further.

**Comment by jp250739** [comment]
As far i have checked.  azure-mgmt-streamanalytics==2.0.0b2 worked for me. thanks
