### ISSUE TITLE
Cannot install any python packages

### ISSUE THREAD

**Issue by Grantglass** [Azure/azure-sdk-for-python#35340]
- **Package Name**: 
- azure-sdk-for-python/pypi/simple
- **Package Version**: 
- ?
- **Operating System**:
- Mac OS 14.4.1 
- **Python Version**: 
3.10.12

**Describe the bug**
I cannot install any packages on my computer.
Looking in indexes: https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/
ERROR: Could not find a version that satisfies the requirement ipykernel (from versions: none)
ERROR: No matching distribution found for ipykernel

**To Reproduce**
1. pip install anything

**Expected behavior**
the package is installed. 

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Seems like it is not an issue for SDK repo.

Maybe stackoverflow can help.
