### ISSUE TITLE
Document Intelligence Readme Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#35380]
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/documentintelligence/azure-ai-documentintelligence#using-the-general-document-model)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/a62a8e23-ac8a-4fea-8dea-b158c3dc2f91)

**Reason:**
`list` object has no attribute `words`

**Suggestion:**
Update code to `page`

@rohit-ganguly  , @lmazuel  ,  @achandmsft , @mayurid for notification.

**Comment by YalinLi0312** [comment]
Hi @jerryshia , we did some updates for the sample recently, can you take a look? Additionally, the `Reason` is not correct: `result.pages` is a list object, `page` is in [DocumentPage](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/models/_models.py#L2212) type which has attribute `words`.

**Comment by YalinLi0312** [comment]
This is a duplicate issue of https://github.com/Azure/azure-sdk-for-python/issues/35404 , close this issue as it has been fixed.
