### ISSUE TITLE
Document Intelligence README Issue

### ISSUE THREAD

**Issue by dotnet-7** [Azure/azure-sdk-for-python#35404]
Section [link1](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/documentintelligence/azure-ai-documentintelligence#using-the-general-document-model)

![image](https://github.com/Azure/azure-sdk-for-python/assets/57525824/ff3219c6-cf82-4a4c-ae41-d278e2b3384b)

#### Reasons:
'list' object has no attribute 'words'.

#### Suggestions:

Update code to `page`.

@rohit-ganguly , @lmazuel  , @YalinLi0312  for notification.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment]
The reason `Reasons` is not correct. `page` is in type `DocumentPage` not list, it has an attribute words. Here are the link to model [AnalyzeResult](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/models/_models.py#L176) and [DocumentPage](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/models/_models.py#L2186).

**Comment by jerryshia** [comment]
This issue no longer exists.
