### ISSUE TITLE
Servicebus azure.servicebus._pyamqp.message.Message types don't match usage in this package's unit tests

### ISSUE THREAD

**Issue by travcunn** [Azure/azure-sdk-for-python#35424]
- **Package Name**: azure-servicebus
- **Package Version**: latest
- **Operating System**: 
- **Python Version**: 3.10

**Describe the bug**
The types from `azure.servicebus._pyamqp.message.Message` don't match those in the unit tests.

In commit https://github.com/Azure/azure-sdk-for-python/commit/f8f223d8774b0434526d83290fed5c64e6230160, `Message.data` is now forced to a type: `data: Optional[bytes] = None,` however in unit tests in this package, it is treated as an array. See these tests: https://github.com/Azure/azure-sdk-for-python/blob/5fd2c52de5aaa8aaac129168b3713166f2cf069b/sdk/servicebus/azure-servicebus/tests/test_message.py#L175

Does the linter on this package not scan unit tests? Can you please fix the types on the `Message` class?

**Comment by kashifkhan** [comment]
Thank you for the feedback @travcunn . We will investigate and get back to you asap.

**Comment by swathipil** [comment]
Hi @travcunn - Thanks for your feedback! We're currently updating the type of Message.data, and the fix should be included in the next release of `azure-servicebus`.
