### ISSUE TITLE
Added “Resource visualizer” export functionality

### ISSUE THREAD

**Issue by gogo25171** [Azure/azure-sdk-for-python#35423]
Good morning,

I'm contacting you because I have a problem: I want to export the "Resource visualizer" in PNG format, but this is impossible for me. I tried to export the JSON template of my resource group to use it with AzViz, but without success, and moreover, it does not work in Python.

Could you help me resolve this issue? I thank you in advance.

Sincerely

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share more details?

e.g. which SDK do you use? Or do you use az cli?

Thanks.

**Comment by gogo25171** [comment]
Thank you for contacting me.

To answer your question, I'm using the Azure SDK for Python to interact with Azure services in my script. I specifically use the azure.identity libraries for authentication and azure.mgmt.resource for managing Azure resources. I don't use the Azure CLI in this context, because my approach is entirely based on programming with Python.

Additionally, I am facing a challenge: I want to export the “Resource visualizer” in PNG format, but this seems impossible with the tools I have at my disposal. I've attempted to export my resource group's JSON model for use with AzViz in PowerShell mode, but with mixed success, and it appears this isn't easily done in Python.

Do you have any tips or resources to suggest to help me resolve this issue? Any assistance would be greatly appreciated.

I thank you in advance for your help and remain at your disposal for any additional information.

Sincerely, Gauthier C.

**Comment by xiangyan99** [comment]
Thanks.

I am still not quite clear. Could you give more details?

e.g. which API in the SDK you want to use?

What is the error message?

**Comment by gogo25171** [comment]
Hello,

Thank you for your response. I would like to specify that I am using Python and the following Azure SDKs for my project:

```python
from azure.identity import ClientSecretCredential
from azure.mgmt.resource import ResourceManagementClient
```
Please let me know if these are the correct SDKs to meet the requirements.

Thank you in advance for your help.

**Comment by ChenxiJiang333** [comment]
Hi @gogo25171, did you have any tremble in exporting the resource group schema? You can do it through code:
```
response = client.resource_groups.begin_export_template(
        resource_group_name={resource-group-name},
        parameters={"resources": ["*"]},
    ).result()
schema = requests.get(response.template['$schema']).json()
```
Yet for the use of AzViz , since it's a Third-Party tool, you may need to turn to its developer https://github.com/PrateekKumarSingh/AzViz for support.
