### ISSUE TITLE
get_instance_view function doesn't return statuses 

### ISSUE THREAD

**Issue by chkp-eddiek** [Azure/azure-sdk-for-python#35436]
- **Package Name**: azure-mgmt-compute
- **Package Version**: latest
- **Operating System**: windows
- **Python Version**:  3.11

**Describe the bug**
The function doesn't reply with expected response as documented in official documentation:
https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/get-instance-view?view=rest-compute-2023-10-02&tabs=Python#response

**To Reproduce**
1.  Run the python script documented in official documentation as above on instances or vmss instrances.

**Expected behavior**
The function should reply with the following structure as in documentation:
  "statuses": [
    {
      "code": "ProvisioningState/succeeded",
      "level": "Info",
      "displayStatus": "Provisioning succeeded",
      "message": null,
      "time": "2020-06-05T04:59:58.1852966+00:00"
    },
    {
      "code": "PowerState/running",
      "level": "Info",
      "displayStatus": "VM running",
      "message": null,
      "time": null
    }
  ]

**Screenshots**

**Additional context**
Received response example:
{'additional_properties': {}, 'platform_update_domain': 1, 'platform_fault_domain': 1, 'rdp_thumb_print': None, 'vm_agent': None, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2023_09_01.models._models_py3.DiskInstanceView object at 0x000002234315E910>], 'extensions': None, 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2023_09_01.models._models_py3.BootDiagnosticsInstanceView object at 0x000002234315FA50>, 'statuses': [<azure.mgmt.compute.v2023_09_01.models._models_py3.InstanceViewStatus object at 0x000002234315F990>, <azure.mgmt.compute.v2023_09_01.models._models_py3.InstanceViewStatus object at 0x000002234315DD90>], 'assigned_host': None, 'placement_group_id': 'a99be6a6-b5a4-4ac0-95dd-6ac6bfd5d53e', 'computer_name': None, 'os_name': None, 'os_version': None, 'hyper_v_generation': 'V1'}

**Comment by Drewm3** [comment]
@TravisCragg-MSFT, I am going to assign this one to you for now. Could you please move it over to Kanika once she is setup in GitHub.

**Comment by lmazuel** [comment]
`get_instance_view` returns an instance of `VirtualMachineScaleSetVMInstanceView`:
https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2023_09_01.models.virtualmachinescalesetvminstanceview?view=azure-python

If you print a model, the SDK is trying to show you a preview of the model content, but it doesn't do this recursively (it's just for preview in logs as a string). The current example you show, is actually a result of `print(result)`

You can access the "statuses" by attribute syntax:
```pythonn
for status in result.statuses:
    print(f"Code: {status.code}, Level: {status.level}, Display: {status.display_status}, Message: {status.message}")
```

Or convert the entire model recursively to dict, and access what he wants with dict syntax:
```python
dictified_result = result.as_dict()
for status in dictified_result["statuses"]:
    print(" ".join([f"{key}: {value}" for key, value in status.items()]))
```

Running this code gives something like:
```
Code: ProvisioningState/succeeded, Level: Info, Display: Provisioning succeeded, Message: None
Code: PowerState/running, Level: Info, Display: VM running, Message: None
code: ProvisioningState/succeeded level: Info display_status: Provisioning succeeded time: 2024-05-16T06:42:02.964781Z
code: PowerState/running level: Info display_status: VM running
```

Let us knonw if there are more questions!
