### ISSUE TITLE
Configurable connection pool size in azure.storage package

### ISSUE THREAD

**Issue by bertek41** [Azure/azure-sdk-for-python#35456]
- **Package Name**: azure-storage-blob, azure-identity
- **Package Version**: 12.19.1 - 1.15.0
- **Operating System**: Ubuntu
- **Python Version**: 3.10.12

**Describe the bug**
I've seen configurable pool_size in here https://github.com/Azure/azure-sdk-for-python/issues/12102 but I am using BlobServiceClient and this doesn't work for here.

**To Reproduce**
initialize with BlobServiceClient. 
Have a 10 threads.
And simultaneously execute #get_blob_client#upload_blob 

Errors:
```
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0f5be97a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/**HIDDEN**/url
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
```

My BlobServiceClient
```
    BlobServiceClient(
        AZURE_ACCOUNT_URL,
        credential=ClientSecretCredential(
            client_id=os.getenv("AZURE_CLIENT_ID"),
            client_secret=os.getenv("AZURE_CLIENT_SECRET"),
            tenant_id=os.getenv("AZURE_TENANT_ID"),
        ),
    )
```

**Comment by pvaneck** [comment]
Hey @bertek41, how are you specifying your pooling configuration? I believe you should be able to supply your own transport to the `BlobServiceClient` as shown [here](https://github.com/Azure/azure-sdk-for-python/blob/a7519f925cfcc57e0f90561b69b50e9d6c08e9ba/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md).

**Comment by bertek41** [comment]
> Hey @bertek41, how are you specifying your pooling configuration? I believe you should be able to supply your own transport to the `BlobServiceClient` as shown [here](https://github.com/Azure/azure-sdk-for-python/blob/a7519f925cfcc57e0f90561b69b50e9d6c08e9ba/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md).

I tried the transport parameter, but no matter what I type, nothing changes. I tried the transport parameter, but no matter what I type, nothing changes. I even gave str to the transport parameter, it didn't give any warning, I don't think it worked.

**Comment by swathipil** [comment]
Hi @bertek41 - The transport parameter accepts should take in a Transport object such RequestsTransport as shown [here](https://github.com/Azure/azure-sdk-for-python/blob/a7519f925cfcc57e0f90561b69b50e9d6c08e9ba/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#transport), rather than a string. For a list of other Transport classes supported, please refer to [this documentation](https://learn.microsoft.com/python/api/azure-core/azure.core.pipeline.transport?view=azure-python).

As @pvaneck mentioned, a snippet of code that shows how you are creating your client and specifying pooling configuration would allow us to provide more assistance.

**Comment by bertek41** [comment]
I figured out. If I use BlobServiceClient like this:
```
    BlobServiceClient(
        AZURE_ACCOUNT_URL,
        credential=ClientSecretCredential(
            client_id=os.getenv("AZURE_CLIENT_ID"),
            client_secret=os.getenv("AZURE_CLIENT_SECRET"),
            tenant_id=os.getenv("AZURE_TENANT_ID"),
        ),
        transport=...
    )
```
Nothing changes. But when I use like this:
```
BlobServiceClient.from_connection_string(AZURE_CONNECTION_STRING, transport=...)
```
Service does use transport.
