### ISSUE TITLE
Looking for alternate version of  `npm i @azure/communication-calling@1.2.0-beta.1 ` since This version has been deprecated 

### ISSUE THREAD

**Issue by Sampath280** [Azure/azure-sdk-for-python#35454]
### Type of issue

Outdated article

### Description

I have worked on this 
Call diagnostics
Call diagnostics is an extended feature of the core Call API and allows you to diagnose an active call.

	```js
	const callQualityApi = call.api(Features.CallQuality);
	```
Subscribe to the diagnosticChanged event to monitor call diagnostics.
	```js
	/**
	 *  Each diagnostic has the following data:
     * - diagnostic is the type of diagnostic, e.g. NetworkSendQuality, DeviceSpeakWhileMuted, etc...
 	 * - value is DiagnosticQuality or DiagnosticFlag:
 	 *     - DiagnosticQuality = enum { Good = 1, Poor = 2, Bad = 3 }.
 	 *     - DiagnosticFlag = true | false.
 	 * - valueType = 'DiagnosticQuality' | 'DiagnosticFlag'
 	 * - mediaType is the media type associated with the event, e.g. Audio, Video, ScreenShare. These are defined in `CallDiagnosticEventMediaType`.
	 */
	 const diagnosticChangedListener = (diagnosticInfo: NetworkDiagnosticChangedEventArgs | MediaDiagnosticChangedEventArgs) => {
		console.log(`Diagnostic changed: ` +
					`Diagnostic: ${diagnosticInfo.diagnostic}` +
					`Value: ${diagnosticInfo.value}` + 
					`Value type: ${diagnosticInfo.valueType}` +
					`Media type: ${diagnosticInfo.mediaType}` +

		if (diagnosticInfo.valueType === 'DiagnosticQuality') {
			if (diagnosticInfo.value === DiagnosticQuality.Bad) {
				console.error(`${diagnosticInfo.diagnostic} is bad quality`);

			} else if (diagnosticInfo.value === DiagnosticQuality.Poor) {
				console.error(`${diagnosticInfo.diagnostic} is poor quality`);
			}

		} else if (diagnosticInfo.valueType === 'DiagnosticFlag') {
			if (diagnosticInfo.value === true) {
				console.error(`${diagnosticInfo.diagnostic}`);
			}
		}
	};

	this._currentCall.api(Features.Diagnostics).media.on('diagnosticChanged', diagnosticChangedListener);
	this._currentCall.api(Features.Diagnostics).network.on('diagnosticChanged', diagnosticChangedListener);


```
However, the First thing is that the logs of calls are not reflected in  ```console.log```. 
The important thing is that “Call Diagnostic”  call logs on Azure take more time to reflect more than 1 hour / sometimes 5 hours.  Look for both things and package updates.
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/communication-callautomation-readme?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/communication-callautomation-readme.md

### Document Version Independent Id

450f94bf-89b4-529c-823c-a5d2e63892a3

### Article author

@azure-sdk

### Metadata

* ID: ad2ded9b-cc0a-ec2d-e78b-5ed35073fe57 
* Service: **communication**

**Comment by xiangyan99** [comment]
Looks like this is a js package.

Please open it in https://github.com/Azure/azure-sdk-for-js repo.
