### ISSUE TITLE
Entra access token authentication policies such as `BearerTokenAuthenticationPolicy` should respect `refresh_on` information

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-python#35473]
Long lived credentials such as those received from managed identity authentication include additional metadata concerning when a token can/should be refreshed. Our authentication policies should take this information into account when refreshing access tokens.

This involves:
- Modifying relevant authentication policies
- Modifying the `AccessToken` type to include this optional information
- Modifying Azure.Identity credential implementations to populate the refresh_on information in the `AccessToken`

**Comment by joshfree** [comment]
Related

https://github.com/Azure/azure-sdk-for-java/issues/40027

https://github.com/Azure/azure-sdk-for-python/issues/35473

https://github.com/Azure/azure-sdk-for-js/issues/29576

https://github.com/Azure/azure-sdk-for-go/issues/22837

https://github.com/Azure/azure-sdk-for-cpp/issues/5598

https://github.com/Azure/azure-sdk-for-rust/issues/1657

**Comment by joshfree** [comment]
Tagging as `Discuss in Office Hours` /cc @schaabs

**Comment by joshfree** [comment]
Next step: @pvaneck and @scottaddie to follow up in next MSAL sync up

**Comment by xiangyan99** [comment]
Done.
