### ISSUE TITLE
Alternate authentication methods for Azure AI Vision Image Analysis Python SDK

### ISSUE THREAD

**Issue by 3051360** [Azure/azure-sdk-for-python#35481]
I have used the following authentication methods with Azure AI Vision Image Analysis REST API:

1. **Client Secret Credentials**
2. **Default Azure Credentials**
3. **Managed Identity Credentials**

But for the Image Analysis Python SDK, I can only see examples which use subscription keys to access the service.

Is there a way to utilize the above mentioned authentication methods instead of subscription keys?

**Comment by dargilco** [comment]
Hello @3051360 you are correct that at the moment you can only use computer vision key to authenticate the image analysis client (package https://pypi.org/project/azure-ai-vision-imageanalysis/). The next version will include additional authentication methods. I do not yet have a release date for the next version. Probably around July.
