### ISSUE TITLE
mypy: Type signature has too few arguments  [syntax]

### ISSUE THREAD

**Issue by gncs** [Azure/azure-sdk-for-python#35495]
https://github.com/Azure/azure-sdk-for-python/blob/1c3628232a5b4197dccd581c9021c2b6c851139d/sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_html_utils.py#L104-L105

```
.../azure/ai/ml/_utils/_html_utils.py:104: error: Type signature has too few arguments  [syntax]
```

**Comment by swathipil** [comment]
Hi @gncs - Thanks for the feedback! We'll address this asap!

**Comment by kingernupur** [comment]
Hi @gncs 
The mypy issue has been fixed and merged in the [master](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_html_utils.py#L102). It should be available in the next release.

Thank you for the feedback!
