### ISSUE TITLE
[azure-monitor-opentelemetry] how to force_flush() from a logger instance

### ISSUE THREAD

**Issue by copdips** [Azure/azure-sdk-for-python#35493]
- **Package Name**: azure-monitor-opentelemetry
- **Package Version**:  1.4.1
- **Operating System**: ubuntu 20.04
- **Python Version**: 3.12

**Describe the bug**

With package `azure-monitor-opentelemetry`, I run `configure_azure_monitor(logger_name=my_logger_name)` to configure the logger.
Then I can get a logger instance from `logging.getLogger(my_logger_name)` that can send logs to Azure Application Insights.

For some use cases, I need to flush the logs instead of waiting for the auto flush interval. I find there's `logger_provider.force_flush()` method, but I need to access the `logger_provider` instance in advance. I'm wondering how to get this provider in my application.
From the logger instance, I can not find the related logger provider instance.

PS: maybe similar request for trace and metric.

**Comment by swathipil** [comment]
Hi @copdips - Thanks for opening an issue! We'll take a look asap!

**Comment by lzchen** [comment]
@swathipil 

Hey sorry for the late reply. You can use the OpenTelemetry api's `get_logger_provider()` method to get an instance of the currently configured logger provider. NOTE: The logging signal is still in an [experimental](https://github.com/open-telemetry/opentelemetry-python?tab=readme-ov-file#project-status) state so use these APIs at your own discretion. 

```
...
from opentelemetry import _logs

lp = _logs.get_logger_provider()

lp.force_flush()
...
```

**Comment by copdips** [comment]
Thx @lzchen, this indeed finds the log provider.
