### ISSUE TITLE
ClientSecretCredential.get_token failed: Authentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

### ISSUE THREAD

**Issue by takkouet** [Azure/azure-sdk-for-python#35519]
I'm using the azusre SDK to retrieve secrets from key vault.

```
from azure.identity import ClientSecretCredential
from azure.keyvault.secrets import SecretClient
from dotenv import load_dotenv
import os

load_dotenv()
TENANT_ID = os.getenv("AZURE_TENANT_ID")
CLIENT_ID = os.getenv("AZURE_CLIENT_ID")
CLIENT_SECRET = os.getenv("AZURE_CLIENT_SECRET")


class AzureKeyVault:
    def __init__(self, vault_name: str):
        self.vault_url = f"https://{vault_name}.vault.azure.net/"

    def __auth(self):
        try:
            credential = ClientSecretCredential(
                tenant_id = TENANT_ID,
                client_id = CLIENT_ID,
                client_secret = CLIENT_SECRET,
                # connection_verify=False # Only in dev, investigating for furthere stable solution
            )
            client = SecretClient(vault_url=self.vault_url, credential=credential)
            return client
        except Exception as e:
            error_message = f"Couldn't authenticate key vault {self.vault_url}, due to:\n {e}"
            raise Exception(error_message)

    def GetSecret(self, secret_name: str, secret_version: str = None) -> str:
        try:
            client = self.__auth()
            secret = client.get_secret(secret_name, secret_version).value
            return secret
        except Exception as e:
            error_message = f"Couldn't retrieve secret {secret_name} from {self.vault_url}, due to:\n {e}"
            raise Exception(error_message)

print(AzureKeyVault("key-vault-XXXXXXXX").GetSecret("admin-username"))
>> pqvinh2 (This was returned when uncomment connection_verify = False)
>> ClientSecretCredential.get_token failed: Authentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997) (This was returned when comment connection_verify = False)
```

As you can see if i uncomment connection_verify = False when declaring credential, it works perfectly fine. I also use this script on my PC at work and no issue was to be found, but it keeps telling me that my cert is expired when I tried to run the script on my PC at home.

Please help me to identify and resolve this problem. Thank you!

**Comment by xiangyan99** [comment]
Thanks for reaching out.

It looks to me there might be something wrong in your environment. e.g. did you set certificate on your home machine?

I cannot repro the issue on my machine.

**Comment by takkouet** [comment]
> Thanks for reaching out.
> 
> It looks to me there might be something wrong in your environment. e.g. did you set certificate on your home machine?
> 
> I cannot repro the issue on my machine.

Hi Xiangyan,
Sorry I'm quite vague about this security thing. Below are all the certs on my home PC. Can I ask which specific kind of certificate may cause the issue I'm raising?
![image](https://github.com/Azure/azure-sdk-for-python/assets/90700476/590563ab-955f-4f41-87a2-a735e0d61398)

**Comment by pvaneck** [comment]
On your home computer, try running `pip install --upgrade certifi` in your Python environment to see if that resolves the cert error.
