### ISSUE TITLE
AttributeError when trying azureml.core.model.Model.register

### ISSUE THREAD

**Issue by olbermann** [Azure/azure-sdk-for-python#3553]
Hi, I run into the following exception when running
https://github.com/Azure/MachineLearningNotebooks/blob/master/01.getting-started/10.register-model-create-image-deploy-service/10.register-model-create-image-deploy-service.ipynb

I am on python3.5,

> pip freeze

absl-py==0.5.0
adal==1.1.0
antlr4-python3-runtime==4.7.1
applicationinsights==0.11.7
argcomplete==1.9.4
asn1crypto==0.24.0
astor==0.7.1
azure-cli-command-modules-nspkg==2.0.2
azure-cli-core==2.0.47
azure-cli-nspkg==3.0.3
azure-cli-profile==2.1.1
azure-cli-telemetry==1.0.0
azure-cognitiveservices-nspkg==2.0.0
azure-cognitiveservices-vision-customvision==0.3.0
azure-cognitiveservices-vision-nspkg==2.0.0
azure-common==1.1.16
azure-graphrbac==0.50.0
azure-mgmt-authorization==0.50.0
azure-mgmt-containerregistry==2.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-resource==2.0.0
azure-mgmt-storage==3.0.0
azure-nspkg==3.0.2
azure-storage-blob==1.3.1
azure-storage-common==1.3.0
azure-storage-nspkg==3.0.0
azureml==0.1.1
azureml-core==0.1.65
azureml-pipeline==0.1.65
azureml-pipeline-core==0.1.65
azureml-pipeline-steps==0.1.65
azureml-sdk==0.1.65
azureml-telemetry==0.1.65
azureml-train==0.1.65
azureml-train-automl==0.1.65
azureml-train-core==0.1.65
azureml-train-restclients-hyperdrive==0.1.65
azureml-train-widgets==0.1.65
backcall==0.1.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.1.4
bleach==3.0.1
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
colorama==0.4.0
contextlib2==0.5.5
cryptography==2.3.1
cycler==0.10.0
decorator==4.3.0
defusedxml==0.5.0
docker==3.5.0
docker-pycreds==0.3.0
entrypoints==0.2.3
gast==0.2.0
grpcio==1.15.0
h5py==2.8.0
humanfriendly==4.16.1
idna==2.7
ipykernel==5.1.0
ipython==7.0.1
ipython-genutils==0.2.0
ipywidgets==7.4.2
isodate==0.6.0
jedi==0.13.1
Jinja2==2.10
jmespath==0.9.3
JsonForm==0.0.2
jsonpickle==1.0
jsonschema==2.6.0
JsonSir==0.0.2
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==6.0.0
jupyter-core==4.4.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
knack==0.4.3
lightgbm==2.2.1
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==3.0.0
mistune==0.8.3
msrest==0.6.0
msrestazure==0.5.0
nbconvert==5.4.0
nbformat==4.4.0
ndg-httpsclient==0.5.1
notebook==5.7.0
numpy==1.15.2
oauthlib==2.1.0
opencv-python==3.4.3.18
pandas==0.23.4
pandocfilters==1.4.2
paramiko==2.4.2
parso==0.3.1
pathspec==0.5.9
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.3.0
portalocker==1.2.1
prometheus-client==0.4.1
prompt-toolkit==2.0.5
protobuf==3.6.1
ptyprocess==0.6.0
pyasn1==0.4.4
pycparser==2.19
Pygments==2.2.0
PyJWT==1.6.4
PyNaCl==1.3.0
pyOpenSSL==18.0.0
pyparsing==2.2.2
python-dateutil==2.7.3
Python-EasyConfig==0.1.7
pytz==2018.5
PyYAML==3.13
pyzmq==17.1.2
qtconsole==4.4.1
requests==2.19.1
requests-oauthlib==1.0.0
Resource==0.2.1
ruamel.yaml==0.15.51
scikit-learn==0.19.1
scipy==1.1.0
SecretStorage==2.3.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
sklearn-pandas==1.7.0
tabulate==0.8.2
tensorboard==1.11.0
tensorflow-gpu==1.11.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
tornado==5.1.1
tqdm==4.26.0
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.53.0
Werkzeug==0.14.1
widgetsnbextension==3.4.2
xmltodict==0.11.0

> import azureml.core
> print("SDK version:", azureml.core.VERSION)`

SDK version: 0.1.65

> from azureml.core import Workspace
> ws = Workspace.from_config()

> from azureml.core.model import Model
> import sklearn

> library_version = "sklearn"+sklearn.__version__.replace(".","x")

> model = Model.register(model_path = "sklearn_regression_model.pkl",
                       model_name = "sklearn_regression_model",
                       tags = {'area': "diabetes", 'type': "regression", 'version': library_version},
                       description = "Ridge regression model to predict diabetes",
                       workspace = ws)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-8430cf6aeef0> in <module>
      8                        tags = {'area': "diabetes", 'type': "regression", 'version': library_version},
      9                        description = "Ridge regression model to predict diabetes",
---> 10                        workspace = ws)

~/venv/lib/python3.5/site-packages/azureml/core/model.py in register(workspace, model_path, model_name, tags, properties, description)
    257         artifact_client.upload_artifact_from_path(model_tar_path, origin, container, tar_name)
    258         prefix_values = [{'prefix': '{}/{}/{}'.format(origin, container, tar_name)}]
--> 259         create_asset_result = asset_client.create_asset(model_name, prefix_values, None)
    260         asset = create_asset_result.content
    261         if isinstance(asset, bytes):

~/venv/lib/python3.5/site-packages/azureml/_restclient/assets_client.py in create_asset(self, model_name, artifact_values, metadata_dict, project_id, run_id, tags, properties)
     58                    "meta": metadata_dict,
     59                    "CreatedTime": created_time}
---> 60         headers = self._client._client.creds.get_authentication_header()
     61         self._logger.debug("Create Asset url: {}\nPayload: {}".format(
     62             create_asset_url, str(payload)))

AttributeError: 'ServiceClient' object has no attribute 'creds'

-------------------------------------------------------------------------------------------------------

It seems to me the line 60 in assets_client.py is just missing an underscore,
and should read
`headers = self._client._client._creds.get_authentication_header()` ???

**Comment by lmazuel** [comment]
Hi,
This package is not developed in this repo, so I can't help you :(
@huguesv do you happen to know where this package is done?

**Comment by sums241987** [comment]
Yes adding that underscore fixed the issue. Thanks.

**Comment by olbermann** [comment]
@lmazuel Thanks for the important info, I hope that https://github.com/MicrosoftDocs/MachineLearning-Python-Feedback is the correct repo (I do not see the corresponding source code in there, but now it seems to me that the intended place is over there.)

**Comment by lmazuel** [comment]
I would think it's the correct one.

Closing the issue here, azureml issue should be created on the mentionned repo. Sorry for the trouble :(
