### ISSUE TITLE
Azure Search python sdk returns "Operation returned an invalid status 'Partial Content'"

### ISSUE THREAD

**Issue by ashikns** [Azure/azure-sdk-for-python#35575]
- **Package Name**: azure-search-documents
- **Package Version**: 11.6.0b3
- **Operating System**: Windows 11
- **Python Version**: 3.11

**Describe the bug**

When trying to enumerate results returned from search client using "async for <results>.by_page()" the sdk raises an error "Operation returned an invalid status 'Partial Content'".

**To Reproduce**
1. Just try to enumerate search results of async search client using `by_page()`.

**Expected behavior**
The results should enumerate.

**Additional context**
This was already working code deployed to server. It has retroactively stopped working. I don't know who messed up what, but this is pretty terrible. I haven't faced an issue from Microsoft sdks yet where already working code was retroactively broken. That too on a Friday :(

**Comment by ashikns** [comment]
Update: Reproducible in 11.4.0, with or without `by_page()`.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Please open a service ticket for the help.

**Comment by abhilash-phamax** [comment]
@xiangyan99  @ashikns Facing the same issue. Our apps are down in production. Please check into this.

**Comment by abhilash-phamax** [comment]
@xiangyan99 You marked it as completed, but still facing the issue. Is it an issue with AI search or some update was released which the sdk doesn't support?

**Comment by ashikns** [comment]
@xiangyan99 Why have you closed this issue? The sdk is not working as of now. If a service ticket has to be filed please provide details. Either way the sdk is not working so I don't see why this issue should be closed?

**Comment by vijayoct27** [comment]
I am having the same issue, specifically with the Python SDK to an Azure AI search service when trying to run a configured semantic reranker. 

I am seeing this issue even when running the provided tutorial https://github.com/Azure-Samples/azure-search-python-samples/blob/main/Quickstart-Semantic-Search/semantic-search-quickstart.ipynb

The error is HttpResponseError: Operation returned an invalid status 'Partial Content'

**Comment by Incrementing-coder** [comment]
> I am having the same issue, specifically with the Python SDK to an Azure AI search service when trying to run a configured semantic reranker.
> 
> I am seeing this issue even when running the provided tutorial https://github.com/Azure-Samples/azure-search-python-samples/blob/main/Quickstart-Semantic-Search/semantic-search-quickstart.ipynb
> 
> The error is HttpResponseError: Operation returned an invalid status 'Partial Content'

@vijayoct27 This issue started like an hour and a half ago. Still waiting for Microsoft to respond.

**Comment by odobosevych** [comment]
same for me

**Comment by xiangyan99** [comment]
To open service support ticket, you can go to: https://azure.microsoft.com/support/create-ticket

**Comment by xiangyan99** [comment]
For updates: https://github.com/Azure/azure-sdk-for-python/issues/35576#issuecomment-2104995097:

Azure responded to the ticket I opened earlier this morning. They mentioned that this behavior is occurring due to an outage issue, and they are currently collaborating with the engineering team to resolve it.

**Comment by vishnup85** [comment]
@xiangyan99 Is this issue resolved, if yes what is the resolution?

**Comment by mehnoorsiddiqui** [comment]
I'm also facing the same issue. @xiangyan99

**Comment by gabor-fefundinfo** [comment]
I'm facing this issue today, too. Is there any fix for this?
