### ISSUE TITLE
Azure Search python sdk returns "Operation returned an invalid status 'Partial Content'"

### ISSUE THREAD

**Issue by abhilash-phamax** [Azure/azure-sdk-for-python#35576]
Package Name: azure-search-documents
Package Version: 11.6.0b1, 11.4.0b11
Operating System: Windows 11
Python Version: 3.11

Describe t he bug

When trying to enumerate results returned from search client using "async for .by_page()" the sdk raises an error "Operation returned an invalid status 'Partial Content'".

To Reproduce

Just try to enumerate search results of async search client using by_page().

Expected behavior
The results should enumerate.

Additional context
This was already working code deployed to server and in production. It has retroactively stopped working. I haven't faced an issue from Microsoft sdks yet where already working code was retroactively broken. It broke on Friday too! Clients are raising tickets. 

Related issue (Which was closed):
[https://github.com/Azure/azure-sdk-for-python/issues/35575](https://github.com/Azure/azure-sdk-for-python/issues/35575)

```
Error Logs:
---------------------------------------------------------------------------
HttpResponseError                         Traceback (most recent call last)
Cell In[239], line 1
----> 1 async for page in results.by_page():
      2     print(page)
      3     async for document in page:

File [D:\Dev Env\Dev Env](file:///D:/Dev Env/Dev Env)Dev Env\scripts\.venv\Lib\site-packages\azure\core\async_paging.py:94, in AsyncPageIterator.__anext__(self)
     92     raise StopAsyncIteration("End of paging")
     93 try:
---> 94     self._response = await self._get_next(self.continuation_token)
     95 except AzureError as error:
     96     if not error.continuation_token:

File [D:\Dev Env\Dev Env](file:///D:/Dev Env/Dev Env)Dev Env\scripts\.venv\Lib\site-packages\azure\search\documents\aio\_paging.py:108, in AsyncSearchPageIterator._get_next_cb(self, continuation_token)
    106 async def _get_next_cb(self, continuation_token):
    107     if continuation_token is None:
--> 108         return await self._client.documents.search_post(search_request=self._initial_query.request, **self._kwargs)
    110     _next_link, next_page_request = unpack_continuation_token(continuation_token)
    112     return await self._client.documents.search_post(search_request=next_page_request, **self._kwargs)

File [D:\Dev Env\Dev Env](file:///D:/Dev Env/Dev Env)Dev Env\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator_async.py:77, in distributed_trace_async.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
     75 span_impl_type = settings.tracing_implementation()
     76 if span_impl_type is None:
---> 77     return await func(*args, **kwargs)
     79 # Merge span is parameter is set, but only if no explicit parent are passed
     80 if merge_span and not passed_in_parent:

File [D:\Dev Env\Dev Env](file:///D:/Dev Env/Dev Env)Dev Env\scripts\.venv\Lib\site-packages\azure\search\documents\_generated\aio\operations\_documents_operations.py:417, in DocumentsOperations.search_post(self, search_request, request_options, **kwargs)
    415     map_error(status_code=response.status_code, response=response, error_map=error_map)
    416     error = self._deserialize.failsafe_deserialize(_models.SearchError, pipeline_response)
--> 417     raise HttpResponseError(response=response, model=error)
    419 deserialized = self._deserialize("SearchDocumentsResult", pipeline_response)
    421 if cls:

HttpResponseError: Operation returned an invalid status 'Partial Content'
```

**Comment by abhilash-phamax** [comment]
@xiangyan99  

```
results = await search_client.search(
                    search_text=query_text,
                    filter=_filter,
                    query_type=QueryType.SEMANTIC,
                    query_language="en-us",
                    scoring_profile=None,
                    query_speller="lexicon",
                    semantic_configuration_name="default",
                    top=top,
                    query_caption="extractive|highlight-false" if use_semantic_captions else None,
                    vector_queries=vec,
                )
```

Only happening when I'm passing the query_type as Semantic.

**Comment by abhilash-phamax** [comment]
@ShivangiReja  @joseharriaga @jairmyree @dgetu @weidongxu-microsoft

**Comment by pdjohntony** [comment]
I'm also having this same issue with azure-search-documents==11.4.0.

**Comment by vijayoct27** [comment]
I am having the issue even when running the semantic reranker tutorial notebook https://github.com/Azure-Samples/azure-search-python-samples/blob/main/Quickstart-Semantic-Search/semantic-search-quickstart.ipynb

Error is: HttpResponseError: Operation returned an invalid status 'Partial Content'

**Comment by GabrielBats** [comment]
I'm encountering the same error. Currently, I've had to temporarily switch the query type to QueryType.FULL to bypass this issue, but it's resulting in lower relevance in retrievals. It seems to be a widespread problem, affecting Azure AI Playground as well. It appears to be related to a resource issue on Azure.

**Comment by Incrementing-coder** [comment]
Yes, I've done changed the query type and that works, but the results are really bad. Hoping this is fixed soon.

**Comment by sunitaparbhu** [comment]
This is a critical bug to resolve. Can it be esclated.

**Comment by Incrementing-coder** [comment]
Please try raising a support request in Azure too.

**Comment by GabrielBats** [comment]
Azure responded to the ticket I opened earlier this morning. They mentioned that this behavior is occurring due to an outage issue, and they are currently collaborating with the engineering team to resolve it.

**Comment by xiangyan99** [comment]
Thanks for reporting the issue.

This is a service issue and please use https://azure.microsoft.com/support/create-ticket to open support ticket for help.
