### ISSUE TITLE
Deserialization issue for the polymorphism support with python SDK generated in swagger PR

### ISSUE THREAD

**Issue by jiec-msft** [Azure/azure-sdk-for-python#35589]
- **Package Name**: sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform
- **Package Version**: Not generated in this repo yet. We downloaded "azure-mgmt-appplatform-9.0.0.zip" from Swagger PR [Add AppPlatform 2024-05-01-preview by haoozhang · Pull Request #28341 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/28341/checks?check_run_id=22960942794)
- **Operating System**: windows 11
- **Python Version**: 2.56.0

**Describe the bug**
Deserialization issue for the polymorphism support with python SDK generated in swagger PR.

**To Reproduce**
1. If there swagger denotes the response with HTTP response 200 and 202, like swagger "[jobs/{jobName}/start](https://github.com/Azure/azure-rest-api-specs/blob/6704dac3bba1d4eafb0a13f01b2f7ab7083f7358/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2024-05-01-preview/appplatform.json#L9078-L9092)"
2. and if the backend is not doing async and directly return the HTTP 200 with response payload.
3. and if the response class need polymorphism support, like [UserSourceInfo](https://github.com/Azure/azure-rest-api-specs/blob/6704dac3bba1d4eafb0a13f01b2f7ab7083f7358/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2024-05-01-preview/appplatform.json#L13115), and its subclasses like "[BuildResultUserSourceInfo](https://github.com/Azure/azure-rest-api-specs/blob/6704dac3bba1d4eafb0a13f01b2f7ab7083f7358/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2024-05-01-preview/appplatform.json#L13232C6-L13232C31)".
4. and if in the CLI extension, we directly return the poller, like "return client.job.begin_start(resource_group, service, name, job_execution_template)"
5. Then the CLI SDK will fail to do deserialization for the polymorphism support, like below example:

```
> az spring job start -n hello-world-job --debug

...
Mason try to reproduce issue in _start_initial, "pipeline_response": f<azure.core.pipeline.PipelineResponse object at 0x000001DBAE8CC790>, "cls": <function JobOperations.begin_start.<locals>.<lambda> at 0x000001DBAE89D300>, "deserialized.job_snapshot.source.type": BuildResult, "deserialized.job_snapshot.trigger_config.trigger_type": Manual
azext_spring.vendored_sdks.appplatform._serialization: Discriminator type is absent or null, use base class UserSourceInfo.
azext_spring.vendored_sdks.appplatform._serialization: Discriminator trigger_type is absent or null, use base class JobTriggerConfig.
Mason try to reproduce issue in get_long_running_output, "pipeline_response": f<azure.core.pipeline.PipelineResponse object at 0x000001DBAE8CC790>, "cls": None, "deserialized.job_snapshot.source.type": None, "deserialized.job_snapshot.trigger_config.trigger_type": None

...output

{
  "endTime": null,
  "jobSnapshot": {
    "managedComponentReferences": [],
    "provisioningState": null,
    "source": {
      "buildResultId": "/subscriptions/0753feba-86f1-4242-aff1-27938fb04531/resourceGroups/jiec-rg-target/providers/Microsoft.AppPlatform/Spring/jiec-e-df-eus-acs-gen1/buildServices/default/builds/hello-world-job/results/2",
      "type": null,
      "version": null
    },
    "template": {
      "args": null,
      "environmentVariables": [],
      "resourceRequests": {
        "cpu": "1",
        "memory": "2Gi"
      }
    },
    "triggerConfig": {
      "triggerType": null
    }
  },
  "name": "hello-world-job-0511054547125-7fc078",
  "startTime": null,
  "status": "Pending",
  "template": {
    "args": null,
    "environmentVariables": [],
    "resourceRequests": {
      "cpu": null,
      "memory": null
    }
  }
}
```

**Expected behavior**
Expect output by CLI like below in the right:
![image](https://github.com/Azure/azure-sdk-for-python/assets/22190245/5e498e20-23c0-4014-8a53-dda9ee0b3e20)

**Screenshots**

**Additional context**
1. The python sdk should be downloaded here: [Add AppPlatform 2024-05-01-preview by haoozhang · Pull Request #28341 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/28341/checks?check_run_id=22960942794) "[azure-mgmt-appplatform-9.0.0.zip](https://openapistorageprod.blob.core.windows.net/sdkautomation/Azure/28341/azure-sdk-for-python/track2_azure-mgmt-appplatform/azure-mgmt-appplatform-9.0.0.zip?sv=2022-11-02&ss=b&srt=sco&sp=rtf&se=2026-08-28T14:18:23Z&st=2023-08-26T06:18:23Z&spr=https&sig=YbCJ9rV%2F9vWVs%2BNOa2bpQ%2F1W%2FEcdzf5WgWY%2Brygkh3s%3D)".
2. I added some code to show above output, you can see the diff in this PR ([[Don't merge] Add code to investigate the issue by jiec-msft · Pull Request #7606 · Azure/azure-cli-extensions (github.com)](https://github.com/Azure/azure-cli-extensions/pull/7606))
3. The full output for above CLI command with debug messages, see attched [cli-debug-output.txt](https://github.com/Azure/azure-sdk-for-python/files/15282792/cli-debug-output.txt)
4. CLI core versions > az version
{
  "azure-cli": "2.56.0",
  "azure-cli-core": "2.56.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "0.5.137",
    "spring": "1.24.0"
  }
}

**Comment by iscai-msft** [comment]
thanks for opening the issue @jiec-msft . We know what's causing this issue, it's a known bug in LRO, in case the LRO finish immediately while the return is a polymorphic type. Polymorphic deserialization pops from the resulting JSON, and if the LRO is done twice, we deserialize twice, but the second time the discriminator is not here anymore so we're not returning the polymorphic child.

Since there's a customer ticket we're going to restart our discussions on how best to solve this issue

**Comment by msyyc** [comment]
FYI: same issue as https://github.com/Azure/autorest.python/issues/2428

**Comment by msyyc** [comment]
Fixed in https://github.com/Azure/autorest.python/pull/2628 and we will release a new version ASAP.

**Comment by jiec-msft** [comment]
> Fixed in [Azure/autorest.python#2628](https://github.com/Azure/autorest.python/pull/2628) and we will release a new version ASAP.

@msyyc May I ask is the fix released?

**Comment by ChenxiJiang333** [comment]
> > Fixed in [Azure/autorest.python#2628](https://github.com/Azure/autorest.python/pull/2628) and we will release a new version ASAP.
> 
> @msyyc May I ask is the fix released?

Hi, it has been released, https://pypi.org/project/azure-mgmt-appplatform/9.1.0/
