### ISSUE TITLE
Empty documents fields of same image with data on studio

### ISSUE THREAD

**Issue by ArthurEgide** [Azure/azure-sdk-for-python#35583]
## Package:

- azure-ai-formrecognizer==3.3.0

## OS:

- Manjaro Linux
- Ubuntu 22

## Description:

I used a document in Document Intelligence Studio and correctly got the data back.
Using the same document via the API or the Python SDK, the fields are not identified.

## To Reproduce

1. Take a PNG image;
2. Use via Studio and successfully obtain the fields recognized with key/value;
3. Use the same via Python SDK and have an empty result for the fields.

## Expected behavior
Same result between Studio and SDK.

## Screenshots

Both results were using the same image

### Expected behavior successfully executed by Studio
![Studio fields](https://github.com/Azure/azure-sdk-for-python/assets/28968329/a822b648-e191-4574-9088-9841097e610b)

### Unexpected behavior successfully executed by Studio. Missing "Fields"
![Python SDK fields](https://github.com/Azure/azure-sdk-for-python/assets/28968329/ae120f8b-a115-4b37-be80-b80f1c4e53e8)

## Used Snippet
```python
# import libraries
import os
from azure.core.credentials import AzureKeyCredential
from azure.ai.formrecognizer import DocumentAnalysisClient
import base64

with open("IMAGE_PATH", "rb") as image_file:
  readed_image = image_file.read()

endpoint = os.getenv('AZURE_ENDPOINT')
key = os.getenv('SUBSCRIPTION_KEY')

def analyze_invoice():
    document_analysis_client = DocumentAnalysisClient(
      endpoint=endpoint, 
      credential=AzureKeyCredential(key)
    )
    
    poller = document_analysis_client.begin_analyze_document(
        model_id="prebuilt-healthInsuranceCard.us", 
        document= readed_image
    )

    hci_us = poller.result()
    

    if(hci_us == None):
      return
    if hci_us.documents:
      
        for idx, az_document in enumerate(hci_us.documents):
          # Here the problem for any number of documents
          
          az_document.fields # EMPTY
          az_document.fields.get("Copays") # EMPTY, any key


if __name__ == "__main__":
    analyze_invoice()
```

**Comment by swathipil** [comment]
Hi @ArthurEgide - thanks for opening an issue! We'll take a look asap!

**Comment by ArthurEgide** [comment]
Hello @swathipil, just adding information...

Even when I use the demonstrative image, the values are empty.

``` python
poller = document_analysis_client.begin_analyze_document_from_url(
  model_id="prebuilt-healthInsuranceCard.us",
  document_url='https://raw.githubusercontent.com/Azure-Samples/cognitive-services-REST-api-samples/master/curl/form-recognizer/rest-api/insurance-card.png'
)
```

**Comment by YalinLi0312** [comment]
Hi @ArthurEgide , 
* Can you provide the API version and endpoint you're using in Studio? This would help me to investigate the issue in SDK. 
* I notice you're using `azure-ai-formrecognizer`, we have rebranded it to `azure-di-documentintelligence`. New APIs and features support will only be available in the new package, it's recommended to switch to the new one. You can follow this doc for migration: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/MIGRATION_GUIDE.md

Thanks
