### ISSUE TITLE
get_root_directory_client() method for  azure.storage.filedatalake.FileSystemClient class

### ISSUE THREAD

**Issue by Lackshu** [Azure/azure-sdk-for-python#35596]
The current method to operate on the root directory is _get_root_directory_client() which is a protected method. It works fine when I try to operate on the ACL of the root directory. However it's not ideal to use a protected method of the class.

Please implement a public method so that we have a safer way to work with the root folder. The get_directory_client method did not work when I tried supplying in the root folder as a parameter.

If it's possible to leverage the get_directory_client method to operate on the root directory, please provide an example. Thanks.

I'm using the class library to apply ACLs to root directory and also provisioning ACLs for specific folders and propagating to the descendants.

![image](https://github.com/Azure/azure-sdk-for-python/assets/7438759/eff9e2e4-a626-4066-94c0-471aeff5d2d3)

**Comment by jalauzon-msft** [comment]
Hi @Lackshu, you should be able to just call `get_directory_client('/')` to get the root directory client. That's all the private method does anyway.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py#L964
