### ISSUE TITLE
ServiceBusReceiver receive_messages max_wait_time race condition locks the message but sends back empty list

### ISSUE THREAD

**Issue by cabal-daniel** [Azure/azure-sdk-for-python#35591]
- **Package Name**:  `pip install azure-servicebus` 

- **Package Version**: `7.12.2`
- **Operating System**: MacOS and Ubuntu
- **Python Version**:  3.8.18

**Describe the bug**

Receiving code:
```
with sb_client.get_queue_receiver(queue) as receiver:
    messages = receiver.receive_messages(
        max_message_count=max_message_count,
        max_wait_time=max_wait_time,
    )
    print(messages)
    for message in messages:
           receiver.complete_message(message)
```

If `max_wait_time` is set in `ServiceBusReceiver.receive_messages`, then a race condition can happen where a message gets locked by the `receive_message` action but `receive_messages` returns back an empty list, locking this message for the duration of the lockout period.

**To Reproduce**
1. We used max_wait_time to 2 and are receiving 1 message at a time
2. Spin up 10 workers, constantly calling the Receiving code above in a polling interval in a while loop
3. Have a sender send 100 or so messages to the queue 1 at a time with a decently large body
Actual behaviour: some of the messages will get locked in the queue. From our experiments roughly 2-4 messages out of 100 get put into the locked state without them being complete. The receive_messages method shouldn't lock a message unless it can return that message in full.

**Expected behavior**
All the messages will get completed. No message would get locked out.

I suspect the code for that behaviour is somewhere in here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py#L454

Perhaps it can be configured so that max_time_out can allow a bit of "grace period" to allow the full message to be received and then terminate afterwards once the max_time_out is reached.

**Comment by kashifkhan** [comment]
Thank you for the feedback @cabal-daniel . We will investigate and get back to you asap.

**Comment by cabal-daniel** [comment]
Have you guys looked into this? It's happening in our prod environments a lot. We can't not set the max time out so messages get dropped

**Comment by cabal-daniel** [comment]
@[rakshith91](https://github.com/Azure/azure-sdk-for-python/commits?author=rakshith91)
@swathipilrakshith91 and [swathipil](https://github.com/Azure/azure-sdk-for-python/commits?author=swathipil)

It seems like you guys are the original authours for this line. We are seeing frames being dropped by service bus. Could you please possibly comment on a remedy for this line?

[https://github.com/Azure/azure-sdk-for-python/blob/d335a043d50cb3f4c484202dedf77bb[…]b4/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py](https://github.com/Azure/azure-sdk-for-python/blob/d335a043d50cb3f4c484202dedf77bbf0b2422b4/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py#L906)

**Comment by l0lawrence** [comment]
Sorry for the delay @cabal-daniel, we are working on a fix in our receive that will put in a Drain call after the timeout is reached and ensure there are no messages left on the link. Will update here when it is released

**Comment by cabal-daniel** [comment]
Hi @l0lawrence may I inquire on the progress?

**Comment by l0lawrence** [comment]
Hi @cabal-daniel, I'm sorry for the lack in update -- have you updated to a more recent version and seen this problem persist? I was not able to reproduce this with the latest version. Also, are you seeing the delivery count increase on messages when they are being locked?

**Comment by cabal-daniel** [comment]
Yes this still happens with release-7.13.0 we just checked. And yes we see the delivery count increase even though no receiver has received the message.
