### ISSUE TITLE
Wrong object type return for `ResourceManagementClient.resources.list()`

### ISSUE THREAD

**Issue by Ledge2494** [Azure/azure-sdk-for-python#35615]
### Type of issue

Code doesn't work

### Description

Hello Community,

I'm using the `list` method for `ResourceManagementClient.resources` and got a strange error while trying to look the return value :
`TypeError: 'async for' requires an object with __aiter__ method, got PageIterator`
The return object type is not the one describe by the documentation (except AsyncPageIterator instead of PageIterator)

I'm using api version `2022-09-01`

### Page URL

https://learn.microsoft.com/fr-fr/python/api/azure-mgmt-resource/azure.mgmt.resource.resources.v2022_09_01.aio.operations.resourcesoperations?view=azure-python#azure-mgmt-resource-resources-v2022-09-01-aio-operations-resourcesoperations-list

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-resource/azure.mgmt.resource.resources.v2022_09_01.aio.operations.ResourcesOperations.yml

### Document Version Independent Id

b84c0206-f275-e214-3bf1-9f3eb998aa9d

### Article author

@lmazuel

### Metadata

* ID: 6be464c1-9927-3d69-51a1-5a92dc8afbd1 
* Service: **azure-resource-manager**

**Comment by ChenxiJiang333** [comment]
Hi, @Ledge2494 It was the page for aio operations, so you need to import the client by `from azure.mgmt.resource.resources.aio import ResourceManagementClient`
