### ISSUE TITLE
Discrepancy Between Document Intelligence Python SDKs and UI Labels

### ISSUE THREAD

**Issue by SyedUmairHasan** [Azure/azure-sdk-for-python#35663]
- **azure-ai-formrecognizer and azure-ai-documentintelligence*: 
- **azure-ai-formrecognizer 3.3.3 and azure-ai-documentintelligence 1.0.0b2**: 
- **Windows**:
- **3.11**: 

**Describe the bug**
I trained a custom extraction model using Document Intelligence UI API version 2024-02-29-preview. When testing with both the Python SDK for Azure AI Document Intelligence and Azure AI Form Recognizer, the cell content of custom tables differs between the UI and the SDKs. The behaviour is not deterministic for some files.

**To Reproduce**
1. Train custom extraction of model having complex tables
2. Test from UI and python SDK

**Expected behavior**
The output of python SDK and UI should be same for all files

**Screenshots**

![image](https://github.com/Azure/azure-sdk-for-python/assets/35225652/fbc155b8-92a3-46bf-8499-6079fef74faf)
![image](https://github.com/Azure/azure-sdk-for-python/assets/35225652/2aea8da9-75c4-40f0-ac28-0761710cace4)
![image](https://github.com/Azure/azure-sdk-for-python/assets/35225652/bb9ea870-cc85-40ba-9036-37e47ff48a60)

**Additional context**
I have created complete post with details in the MS QA forum:
https://learn.microsoft.com/en-us/answers/questions/1661837/discrepancy-between-document-intelligence-python-s?comment=question#newest-question-comment

**Comment by YalinLi0312** [comment]
Hi @SyedUmairHasan , thanks for your contact! 

This probably because `azure-ai-formrecognizer` and `azure-ai-documentintelligence` are using different service APIs:
`azure-ai-formrecognizer 3.3.3`: `2023-07-31`
`azure-ai-documentintelligence 1.0.0b2`: `2024-02-29-preview`

@bojunehsu Does the custom model analyzing the same file in different APIs could get different results?

**Comment by bojunehsu** [comment]
@SyedUmairHasan Can you please verify that you are sending the same exact input file to both Python SDK and Document Intelligence Studio?  I am surprised that the detected text angle differs.

If verified, can you please share the training data and test file with us via formrecog_contact@microsoft.com so we can investigate this further?  Thanks.
