### ISSUE TITLE
Unable to log more than 200 parameters in a single job

### ISSUE THREAD

**Issue by 0xfabioo** [Azure/azure-sdk-for-python#35685]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.16.0
- **Operating System**: Linux
- **Python Version**: 3.11

**Describe the bug**
Attempting to log more than 200 parameters in a job fails with the following error message:

```
INVALID_PARAMETER_VALUE: Response: {'Error': {'Code': 'ValidationError', 'Severity': None, 'Message': 'A field of the entity is over the size limit. FieldName=Parameters, Limit=200, Size=210. See https://aka.ms/azure-machine-learning-limits for service limits documentation.' .... 
```
This limitation is not documented at the provided link (https://aka.ms/azure-machine-learning-limits), nor could I find any reference to it elsewhere.

This limitation appears to originate from Azure Machine Learning (AML) itself, as the same code works correctly when using a local MLflow instance.

**To Reproduce**
```python
mlclient = MLClient(
    credential=DefaultAzureCredential(),
    subscription_id=subscription_id,
    resource_group_name=resource_group_name,
    workspace_name=workspace_name,
)

tracking_uri = mlclient.workspaces.get(workspace_name).mlflow_tracking_uri

mlflow.set_tracking_uri(tracking_uri)

mlflow.set_experiment("Default") # Use Default experiment

with mlflow.start_run() as run:
    for idx in range(0, 201):
        mlflow.log_param(f"param_{idx}", f"value_param_{idx}")


# Same with 
with mlflow.start_run() as run:
    for idx in range(0, 201):
        # sleep(0.1)
        mlflow.log_param(f"param_{idx}", f"value_param_{idx}")
```

**Expected behavior**
It should be possible to log more than 200 parameters in a single job. If this limit is intentional, it should be clearly documented. Additionally, a limit of 200 parameters is quite low and can be reached quickly with the current state-of-the-art network architectures.

**Screenshots**

**Additional context**

**Comment by dsamarov-prudentiasciences** [comment]
Following, is there any updates here?

**Comment by hatboyzero** [comment]
Curious about the status of this as well.  Currently running into this issue when attempting to run a Phi-3 training job.

**Comment by santiagxf** [comment]
Logging metrics is `for` loops is not advisable. Please use asynchronous logging as explained at [Log metrics asynchronously](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-log-view-metrics?view=azureml-api-2&tabs=interactive#log-metrics-asynchronously). That will help scale up to millions of metrics. This note is on our documentation:

> **Performance considerations:** If you need to log multiple metrics (or multiple values for the same metric), avoid making calls to mlflow.log_metric in loops. Better performance can be achieved by using [asynchronous logging](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-log-view-metrics?view=azureml-api-2&tabs=interactive#log-metrics-asynchronously) with mlflow.log_metric("metric1", 9.42, synchronous=False) or by [logging a batch of metrics](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-log-view-metrics?view=azureml-api-2&tabs=interactive#log-curves-or-list-of-values).

**Comment by 0xfabioo** [comment]
@santiagxf This issue is about logging parameters and not metrics. Please reopen

**Comment by santiagxf** [comment]
Apologies for the mistake. Indeed this is a boundary in our product. I have updated the documentation and it shoud be reflected soon. Wondering why do you need more than 200 parameters? Are you sure you are using them? Accomodating 200 parameters in our UX is complex and it makes things a bit unreadable. If you have a requirement for them, happy to listen to it.

In the meantime, you can open a support ticket using the Azure portal and request a limit increase and we are happy to take a look.

**Comment by achauhan-scc** [comment]
As confirmed by @santiagxf, its a product limitation and azure support channel can be used for increasing the limit, no further action require on ticket, closing it.

**Comment by 0xfabioo** [comment]
> Apologies for the mistake. Indeed this is a boundary in our product. I have updated the documentation and it shoud be reflected soon. Wondering why do you need more than 200 parameters? Are you sure you are using them? Accomodating 200 parameters in our UX is complex and it makes things a bit unreadable. If you have a requirement for them, happy to listen to it.
> 
> In the meantime, you can open a support ticket using the Azure portal and request a limit increase and we are happy to take a look.

Basically we have a large model, and we experiment with a lot of input variations. Therefore we log the inputs as parameters so that we can use the comparison view and see directly what is the difference in terms of inputs and hyper-parameters.

**Comment by santiagxf** [comment]
Interesting. Thanks for sharing. I'm taking this feedback in as I can see how the compare feature may be interesting in this scenario.
