### ISSUE TITLE
Support Azure CLI 64-bit on Windows #18766

### ISSUE THREAD

**Issue by Moazzem-Hossain-pixel** [Azure/azure-sdk-for-python#35697]
## Workaround

Azure CLI today doesn't release an 64-bit MSI installer and the workaround is to

1. Download Python 64-bit from the official site https://www.python.org/downloads/windows/ 
2. Run `pip` to install Azure CLI from PyPI https://pypi.org/project/azure-cli/: 
    ```
    pip install azure-cli
    ```

Appliance team has tried the suggested manual workaround and it works. However, Appliance VMware customers will have to do the same manual workaround to deploy Appliance which could be an adoption barrier and will require documentation.
 
## Additional information

GCP & AWS also support 64-bit MSI installers:

- Installing Google Cloud SDK: https://cloud.google.com/sdk/docs/downloads-versioned-archives
- AWS Command Line Interface: https://aws.amazon.com/cli/

_Originally posted by @jiasli in https://github.com/Azure/azure-cli/issues/18766#issuecomment-885430443_

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Please open the issue into repo https://github.com/Azure/azure-cli
