### ISSUE TITLE
Register Model with data-assets associated - Missing documentation

### ISSUE THREAD

**Issue by obiii** [Azure/azure-sdk-for-python#35706]
Hi @MarkusDressel.  Thank you for opening this issue and giving us the opportunity to assist.  We believe that this has been addressed.  If you feel that further discussion is needed, please add a comment with the text “`/unresolve`” to remove the “issue-addressed” label and continue the conversation.

_Originally posted by @ghost in https://github.com/Azure/azure-sdk-for-python/issues/29429#issuecomment-1500455373_

Hi, I see comments ttatign this has been fixed,  but can you please point us to the right documentation? The documentation here: https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.model?view=azure-python

does not show that the model constructor takes any associated data assets. Or if possible, please shows us an example.

**Comment by obiii** [comment]
Hi, is there any update on this please?

**Comment by achauhan-scc** [comment]
SDK V2 does not support this functionality today.
https://github.com/Azure/azure-sdk-for-python/issues/29429
