### ISSUE TITLE
Tags scope permission is needed when fetching blobs

### ISSUE THREAD

**Issue by Crosswind** [Azure/azure-sdk-for-python#35718]
**Problem Statement**

I have a project that fetches blobs from a container and selects the ones to use based on the tags. We have a simple scenario set up where we simply check if the tag `processed = true`. I started using SAS to authenticate and when I switched to using my EntraID instead I received the following error message:
`azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.`

The piece of code that is creating this error:
```python
blob_service_client = BlobServiceClient(
    account_url=ACCOUNT_URL,
    credential=get_credential())

report_container_client = blob_service_client.get_container_client(
    container=CSV_REPORT_CONTAINER
)

report_list = report_container_client.list_blobs(include="tags")

for report_blob in report_list:
    # Error is produced
```

The problem is that my user ID originally only had Storage Blob Data Contributor. The built-in role is missing the ability to read tags and therefore the above method fails. If I remove `include="tags"` from the `list_blobs()` call everything just works. I find that counter-intuitive because tags are advertised as a way to structure blobs so someone that has access to the data should clearly be able to select it by using tags. 

The only way I could find with built-in roles was to assign Defender for Storage Data Scanner role to my user. This looks weird as I am not doing any data scanning / defending anything.

The error message pasted above didn't help in diagnosing the problem. It never occurred to me that I was missing the permission to read tags.

**What I would like to see**

I could see multiple ways of how to handle this. 
1. My preferred option would be to allow working with tags for the Storage Blob Data Contributor role. I haven't found a rationale why that shouldn't be done. Since a contributor has the option to create/delete blobs the tag would always be deleted as well (i.e., if the tags were used to store some important information that must be preserved). 

2. To help others not run into the same problem it would be great if the error message could be improved to specify exactly what permission is missing. With other Azure services I normally get a precise description of what permission is missing. This is different here. I know that Azure support is going to check the problem based on the RequestId but this doesn't help me as a user.

3. And the last option would be to include a hint in the docs saying that querying tags needs special permissions that are not included in the built-in roles. 
For one: The API documentation for list blobs specifies that tags can be included but doesn't mention that further permissions are required: https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=microsoft-entra-id
In fact the authorization section only mentions Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read as a required scope.

Also, on the Python docs for the ContainerClient class no mention of this additional scope can be found: https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-list-blobs

I hope this helps in finding a solution that will help future developers not run into the same issue. Let me know if you have any questions.

**Comment by jalauzon-msft** [comment]
Hi @Crosswind David, sorry for the delay. I'm not too familiar with RBAC so I'm reaching out to folks internally to see if I can provide a better recommendation and hope to get back to you soon. Thanks.

**Comment by jalauzon-msft** [comment]
@Crosswind David, I got a quick reply :)... I have confirmed that "Storage Blob Data Contributor" does not have permission to interact with tags. The only built-in role with tags permission would be [Storage Blob Data **Owner**](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-owner). If that does not work, you can use [custom roles](https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles) to customize the permissions you want specifically. Tags has [these permissions](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#role-based-access-control) and I believe the `read` one is all that would be needed for List Blobs.

I agree that the documentation is lacking here. I will start the process internally to update the List Blobs permission section to mention Blob Tags and the special permissions. Thanks.
