### ISSUE TITLE
Was AADObject removed from the latest version?

### ISSUE THREAD

**Issue by bclements** [Azure/azure-sdk-for-python#3571]
aad_object.py is in 0.40.0 but doesn't look to be in the models directory in the latest version. Was this removed or replaced?

**Comment by lmazuel** [comment]
Yes it has been removed in 0.50.0, please refer to the ChangeLog in PyPI:
https://pypi.org/project/azure-graphrbac/

> - objects.get_current_user has been removed. Use signed_in_user.get instead. The main difference is this new method returns a DirectoryObjectList, where every elements could be sub-type of DirectoryObject (User, Group, etc.)
> - objects.get_objects_by_object_ids now returns a DirectoryObjectList, where every element could be sub-type of DirectoryObject (User, Group, etc.)
> - Groups.get_members now returns a DirectoryObjectList, where every element could be sub-type of DirectoryObject (User, Group, etc.)
