### ISSUE TITLE
AADSTS9002327 error when using InteractiveBrowserCredential with custom app registration

### ISSUE THREAD

**Issue by carlosjourdan** [Azure/azure-sdk-for-python#35722]
- **Package Name**:  azure-identity
- **Package Version**: 1.16.0
- **Operating System**: Windows
- **Python Version**: 3.11.7

**Describe the bug**
When trying to authenticate using the `InteractiveBrowserCredential` with a custom app registration,  the code fails with a `ClientAuthenticationError` exception and the message `Authentication failed: AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.`

**To Reproduce**
1. Create an App Registration in azure with spa authentication flow and redirect URI set  to "http://localhost50000", with api permissions to the graph service
2. Run the code below, using the client id and tenant id from the application
```python
from azure.identity import InteractiveBrowserCredential

AZURE_TENANT_ID =  ...
AZURE_CLIENT_ID = ...
PORT = 50000

credential = InteractiveBrowserCredential(
    additionally_allowed_tenants=AZURE_TENANT_ID,
    client_id = AZURE_CLIENT_ID,
    redirect_uri = f'http://localhost:{PORT}/'
)

credential.get_token("https://graph.microsoft.com/.default")
```

**Expected behavior**
Expected authentication to succeed.

**Additional context**

According to this [stackoverflow answer](https://stackoverflow.com/a/67280275/24440886) this error occurs when the `Origin: http://localhost` header is not set on the requests made.

The authentication works if I monkey patch the `_TelemetryContext.generate_headers` method using the code below to add this header

```python
import msal.telemetry 

generate_headers_orig = msal.telemetry._TelemetryContext.generate_headers

def generate_headers_mod(self):
    headers = generate_headers_orig(self)
    headers.update({'Origin':'http://localhost'})
    return headers

msal.telemetry._TelemetryContext.generate_headers = generate_headers_mod
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

As you can see, _TelemetryContext is a private member that msal does not expose.

Please open an issue in https://github.com/AzureAD/microsoft-authentication-library-for-python repo to request the support.

**Comment by carlosjourdan** [comment]
Hi. Maybe I didn't make myself clear. The `_TelemtryContext` is just a hack that I found to work arround the bug. The real problem here is that the `InteractiveBrowserCredential` is not working as expected for a custom single page app registration.

**Comment by xiangyan99** [comment]
Yes. I understood. :)

`InteractiveBrowserCredential` calls msal APIs for the implementation. We need msal to expose the customize-ability to be able to set the header.

**Comment by carlosjourdan** [comment]
Thanks @xiangyan99. But it is still not clear to me why creating a `InteractiveBrowserCredential` with the documented `client_id` and `redirect_uri` properties fails out of the box. Is there any special setup that needs to be done when creating the App Registration?

**Comment by carlosjourdan** [comment]
I was able to figure it out. Instead of using spa as the authentication method for my app registration, the code works if I set mobile/desktop authentication with a redirect uri pointing to `http://localhost`, and removing the `redirect_uri` argument when calling `InteractiveBrowserAuthentication`

So now the code looks like this


```python
from azure.identity import InteractiveBrowserCredential

AZURE_TENANT_ID =  ...
AZURE_CLIENT_ID = ...

credential = InteractiveBrowserCredential(
    additionally_allowed_tenants=AZURE_TENANT_ID,
    client_id = AZURE_CLIENT_ID
)

credential.get_token("https://graph.microsoft.com/.default")
```
