### ISSUE TITLE
 See "Token credentials not supported by the File Share service" when using DefaultAzureCredential with ShareServiceClient

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-sdk-for-python#35755]
We use azure cli task in devops to login the azure, then in python code we use `DefaultAzureCredential()`

With below code, we see error "Token credentials not supported by the File Share service", how I can resolve this issue, we need eliminate the usage of storage account key.

```
    share_service_client = ShareServiceClient(
        f"https://{account_name}.file.{cloud.suffixes.storage_endpoint}",
        credential,
    )
```

**Comment by LiliDeng** [comment]
@vibhansa-msft , I used the sample here, it didn't work. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-share/samples/file_samples_authentication.py#L85, any idea?

**Comment by jalauzon-msft** [comment]
Hi @LiliDeng, what version of `azure-storage-file-share` are you using? OAuth support was only added to file-share somewhat recently in version `12.12.0`, see [CHANGELOG](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-share/CHANGELOG.md#12120-2023-04-12). You will need to be using at least this version to use a `TokenCredential` with the Files service. Also please be sure you are passing `token_intent` as the sample code does as this is required for Files OAuth. Also note that file-share has its own set of [RBAC roles](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage).

Additionally, there are some restrictions with Files OAuth in that it will only work on File/Directory level operations and will not currently work with Share level operations like Create Share, Delete Share, etc. Support for Share level operations is currently being worked on by the service team and should be coming to the SDK later this year.

**Comment by LiliDeng** [comment]
> Hi @LiliDeng, what version of `azure-storage-file-share` are you using? OAuth support was only added to file-share somewhat recently in version `12.12.0`, see [CHANGELOG](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-share/CHANGELOG.md#12120-2023-04-12). You will need to be using at least this version to use a `TokenCredential` with the Files service. Also please be sure you are passing `token_intent` as the sample code does as this is required for Files OAuth. Also note that file-share has its own set of [RBAC roles](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage).
> 
> Additionally, there are some restrictions with Files OAuth in that it will only work on File/Directory level operations and will not currently work with Share level operations like Create Share, Delete Share, etc. Support for Share level operations is currently being worked on by the service team and should be coming to the SDK later this year.

Thank you, I will upgrade the package and have a try.
