### ISSUE TITLE
Race condition between non-async AI Search methods.

### ISSUE THREAD

**Issue by hamer101** [Azure/azure-sdk-for-python#35778]
- **Package Name**: azure-search-documents
- **Package Version**: 11.4.0

There seems to be an issue with race condition between upload, delete and search sync methods of AI-search service. 

The snippet below serves as an example:

    def upload(batch):
        search_client.upload_documents(documents=batch)
    
    def delete(user, document_name):
        raw_results = search_client.search(
            "",
            filter=f"owner eq '{user}' and sourcefile eq '{document_name}'",
            query_type=QueryType.SIMPLE,
            select="id",
            top=1000
        )
        docs_to_delete = [{"id": doc["id"]} for doc in raw_results]
        if len(docs_to_delete) > 0:
            deleteds = search_client.delete_documents(docs_to_delete)
            print([(x.succeeded, x.status_code) for x in deleteds])
    
    def listfiles(user):
        raw_results = search_client.search(
            "",
            filter=f"owner eq '{user}'",
            query_type=QueryType.SIMPLE,
            select="sourcefile",
            top=1000
        )
        files = list(set([doc["sourcefile"] for doc in raw_results]))
        return {"files": files}

    print(listfiles(owner, assistantId))
      
    print("\n", "-"*10, "[sleeping for 2s]", "-"*10, "\n")
    time.sleep(2)
      
    print("upload(batch)")
    upload(batch)
    print(listfiles(owner, assistantId))
      
    print("\n", "-"*10, "[sleeping for 2s]", "-"*10, "\n")
    time.sleep(2)
      
    print(listfiles(owner, assistantId))
      
    print("\n", "-"*10, "[sleeping for 2s]", "-"*10, "\n")
    time.sleep(2)
      
    print("delete(owner, assistantId, sourcefile)")
    delete(owner, assistantId, sourcefile)
    print(listfiles(owner, assistantId))
      
    print("\n", "-"*10, "[sleeping for 2s]", "-"*10, "\n")
    time.sleep(2)
      
    print(listfiles(owner, assistantId))

With the result being:

    {'files': []}
    
     ---------- [sleeping for 2s] ---------- 
    
    upload(batch)
    {'files': []}
    
     ---------- [sleeping for 2s] ---------- 
    
    {'files': ['Testtest']}
    
     ---------- [sleeping for 2s] ---------- 
    
    delete(owner, assistantId, sourcefile)
    [(True, 200)]
    {'files': ['Testtest']}
    
     ---------- [sleeping for 2s] ---------- 
    
    {'files': []}

In such scenario, I'd like to either not receive a `True` value in `succeeded` attribute or have a way of telling whether the operation has actually finished (like the `.done()` method of `poller` object used, for example, in document translation).

**Comment by mattgotteiner** [comment]
@hamer101 unfortunately the response from the add, update, or delete documents API does not say when an operation is complete, only that it's been started. Depending on the load of the service it may take time for the deletes and updates to propagate

https://learn.microsoft.com/en-us/rest/api/searchservice/addupdate-or-delete-documents


> Status code: 200 is returned for a successful response, meaning that all items have been stored durably and will start to be indexed. Indexing runs in the background and makes new documents available (that is, queryable and searchable) a few seconds after the indexing operation completed. The specific delay depends on the load on the service.
