### ISSUE TITLE
Regenrating Log Analytics Workspace Shared Keys fails with missing parameter that cannot be set.

### ISSUE THREAD

**Issue by KjeldSchmidt** [Azure/azure-sdk-for-python#35777]
- Library: **azure-mgmt-loganalytics**
- Library version: **12.0.0**
- OS: **Windows 10**
- Python Version: **3.11.8**

**Describe the bug**
Regenerating shared keys using `LogAnalyticsManagementClient.shared_keys.regenerate` is impossible.

**To Reproduce**
1. Create a Log Analytics Workspace, create a `LogAnalyticsManagementClient`.
2. For posterity, note that `LogAnalyticsManagementClient.shared_keys.get_shared_keys` returns exact matches for the shared keys on the workspace agent configuration tab.
3. Attempt to use `LogAnalyticsManagementClient.shared_keys.regenerate` according to the [sample on the API page](https://learn.microsoft.com/en-us/rest/api/loganalytics/shared-keys/regenerate?view=rest-loganalytics-2023-09-01&tabs=Python#regeneratesharedkeys). 
4. You will now receive an error with code `InvalidParameter` and the message `keyType value must equal primarySharedKey or secondarySharedKey.`
5. Investigate the code for `regenrate` and notice that there is no way to pass this parameter, and the function doesn't set it. The API according to the documentation linked above does not expect it, either.

**Expected behavior**
I would like to be able to pass a parameter for which key to regenerate OR for the function to rotate both keys. (The former seems more sensible, but I am happy with either)

**Screenshots**
I don't have screenshots, but the offending file is here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/loganalytics/azure-mgmt-loganalytics/azure/mgmt/loganalytics/operations/_shared_keys_operations.py

Note that this does not make any attempt to pass a keyType parameter to the API - as the API also does not claim 

**Additional context**
n/a

**Comment by KjeldSchmidt** [comment]
I found some extra information about the API call (notably: the parameter is expected to be set via a query argument) and opened a related issue here: https://github.com/Azure/azure-rest-api-specs-examples/issues/4533

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
@KjeldSchmidt, thanks for pointing this out, this function `LogAnalyticsManagementClient.shared_keys.get_shared_keys` was latest generated from [the swagger definiton](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01/SharedKeys.json#L85) and it seems being an issue for a long time. I would tranfer your this issue https://github.com/Azure/azure-rest-api-specs-examples/issues to https://github.com/Azure/azure-rest-api-specs/issues to seek help from service team. Once the swagger is updated, python will release a new version to fix it as well.

**Comment by xiangyan99** [comment]
@KjeldSchmidt w/o a fix in the swagger, there is nothing SDK can do.

Please open issues in the https://github.com/Azure/azure-rest-api-specs/issues and use that one to track the issue.

Once the swagger is fixed, we will have a new SDK release with the fix.
