### ISSUE TITLE
How to determine the given Container url is either public or private

### ISSUE THREAD

**Issue by landscapepainter** [Azure/azure-sdk-for-python#35770]
Hi, I'm currently trying to implement a method that determines either the given container url(such as `https://my_storage_account.blob.core.windows.net/my_container`) has private or public access. I've been implementing this feature by running the following script until now
```
container_url = (f'https://{storage_account_name}.blob.core.windows.net/{container_name}')
container_client = ContainerClient.from_container_url(container_url)
container_client.exists()
```
to see if `container_client.exists()` throws `ClientAuthenticationError`, and if it does, it means the container is private, and if it doesn't, then it means it's public. However, I thought this method is quite hacky. Do you have a formal method to check the access policy of the container given the endpoint url?

**Comment by landscapepainter** [comment]
cc @swathipil @msyyc @ChenxiJiang333

**Comment by msyyc** [comment]
According to your description, it is package `azure-storage-blob`. I find @vincenttran-msft in Github commit history who may provide help or address more proper expert on this issue.

**Comment by vincenttran-msft** [comment]
Hi @landscapepainter Doyoung, thanks for your inquiry. While there is no way to tell purely from the URL itself, there is a programmatic way to check this case by looking at [headers](https://learn.microsoft.com/en-us/rest/api/storageservices/get-container-properties?tabs=microsoft-entra-id#response-headers).

In the link above, specifically we are concerned with the section about `x-ms-blob-public-access`
![image](https://github.com/Azure/azure-sdk-for-python/assets/101599632/529a5924-4f50-4ea5-9d86-88114d06654e)

So using the Python SDK, going off your example using a `container_client`, we could do something like this to check what headers are contained the response:
```
container_properties = container_client.get_container_properties()
print(container_properties)
```

Which would yield us this:
`{'name': 'public', 'last_modified': datetime.datetime(2024, 5, 28, 22, 58, 9, tzinfo=datetime.timezone.utc), 'etag': '"0x8DC7F69A4FD63C0"', 'lease': {'status': 'unlocked', 'state': 'available', 'duration': None}, 'public_access': None, 'has_immutability_policy': False, 'deleted': None, 'version': None, 'has_legal_hold': False, 'metadata': {}, 'encryption_scope': <azure.storage.blob._models.ContainerEncryptionScope object at 0x000001BDC7E06210>, 'immutable_storage_with_versioning_enabled': False}` (in this example, my container name is `public`)

From the above, we can see there is a field in the dictionary, `public_access`, which is None in this example, meaning this is a private Storage account. 

With that being said, I think the resources provided above and example code should help you achieve what you are looking for. For a simple example, you could then check that it is not None (i.e. either `blob` or `container`):
```
if container_properties.get('public_access') is not None:
    # At this point, we know it's public, could do another if check to see if it's blob or container level
```

And then this code could be improved even more by having different codepaths dependent on the actual value of the header etc. Hopefully this helps, please reach out if you have any other questions or concerns.

Thanks!

**Comment by landscapepainter** [comment]
@vincenttran-msft Thanks for the quick support. 
IIUC, I can use `container_properties = container_client.get_container_properties()` only when I already know either the container is public or private. This is because I have to decide either to provide the credential or not to `ContainerClient.from_container_url()` as an argument. If the container url is public and I provide credentials, then it errors out and if I don't provide credentials to a private container, then it also errors out. Is there a way to know the access policy(either public or private) of the provided `container_url` without having to know it's policy in advance?

**Comment by vincenttran-msft** [comment]
Hi @landscapepainter Doyoung, understood. I can see that my above suggestion to check programmatically does not help us get any closer to being able to determine whether to provide credentials or not _before_ querying Azure Storage. Unfortunately, there is no mechanism provided by Azure Storage to check the access policy in advance. 

In that case, I would recommend some sort of naming scheme that implies access policy (if this is viable option in your use-case), otherwise a try-except block would probably be your best option.

Thanks!
