### ISSUE TITLE
Error while trying to delete local endpoint

### ISSUE THREAD

**Issue by alexmpm** [Azure/azure-sdk-for-python#35809]
- **Package Name**:  azure-ai-ml
- **Package Version**:  1.16.1
- **Operating System**: Ubuntu
- **Python Version**: 3.10

**Describe the bug**
When trying to delete a local deployed endpoint using its name, the package gives an error saying that the local endpoint does not exist. 
See attached print screen - it shows that the endpoint I am trying to delete does exist. 

**To Reproduce**
1. Create a local endpoint
2. get the endpoint details
3. try to delete the local endpoint using the command _ml_client.online_endpoints.begin_delete(local=True, name=<endpointname>)_

**Expected behavior**
If all parameters are correct and endpoint does exists, that the endpoint gets deleted

**Screenshots**
Error
![image](https://github.com/Azure/azure-sdk-for-python/assets/71778727/234db620-176f-4dae-8d0a-cd69f65c61b4)

Package and Python version
![image](https://github.com/Azure/azure-sdk-for-python/assets/71778727/2bb544d3-dcf0-498c-8aaf-2e95141213ca)

**Comment by achauhan-scc** [comment]
unable to repo with latest version 1.21.0
