### ISSUE TITLE
Document the APPLICATIONINSIGHTS_OPENTELEMETRY_RESOURCE_METRIC_DISABLED environment variable

### ISSUE THREAD

**Issue by progxaker** [Azure/azure-sdk-for-python#35808]
### Type of issue

Missing information

### Description

During https://github.com/Azure/azure-sdk-for-python/pull/31355, @jeremydvoss added the following environment variable, but I didn't find it documented.

https://github.com/Azure/azure-sdk-for-python/blob/f621bd036d9d77913dd9b00c33301357c4d02d75/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py#L10-L11

I think it should be documented since the `_APPRESOURCEPREVIEW_` metric, which is triggered by this mechanism, spends the client's money, and the variable can help disable this optional metric.

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/monitor-opentelemetry-readme?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/monitor-opentelemetry-readme.md

### Document Version Independent Id

8eefd374-125d-c1b1-2084-56753ab6feb4

### Article author

@azure-sdk

### Metadata

* ID: 1a2694fd-b008-e858-e599-84c36add4003 
* Service: **monitor**

**Comment by progxaker** [comment]
Hello team. Could you please tell if there are any updates?

**Comment by lzchen** [comment]
@progxaker 

We are currently re-designing how we are going to be exposing resource metrics in Application Insights. The disabling environment variable is a temporary measure so we do not want to advocate for it's usage. If users would like to disable the resource metrics, they can.
