### ISSUE TITLE
Workspace AmlCompute does not have correct compute region from SDK.

### ISSUE THREAD

**Issue by Mmdixon** [Azure/azure-sdk-for-python#35820]
- **Package Name**: azure-ai-ml
- **Package Version**: 1.16.1
- **Operating System**: MINGW64_NT-10.0-22621
- **Python Version**:  3.11.9

**Describe the bug**

```python
# ws: MLClient
ws.compute.get("compute_name")
```
returns the wrong region in the `location` field.

**To Reproduce**
1. Have workspace in a region, say centralus
2. Create a compute in another region, say eastus2
3. `ws.compute.get("compute_name").location`

**Expected behavior**
Expect the `location` to say eastus2 which is the region of the compute, not centralus, which is the region of the workspace. There is no other field or property to indicate the compute region if `location` is indeed meant to only be for the workspace information.

**Screenshots**

**Additional context**
AzureML Studio does show the eastus2 region for the compute.
In Azure, the Resource JSON does have the structure
```
...
    "name": "compute_name",
    "type": "Microsoft.MachineLearningServices/workspaces/computes",
    "location": "centralus",
    "properties": {
        "computeType": "AmlCompute",
        "computeLocation": "eastus2",
        ...
```
but these properties are `{}` when retrieved from the SDK.

**Comment by achauhan-scc** [comment]
@Mmdixon - when running fetch script, I am getting the correct region
![image](https://github.com/user-attachments/assets/212d5ad0-50bf-43c4-b7f4-30ddb7fbf835)
**Can you please share more details on how you are creating your compute?**
I used below CLI command
az ml compute create -g <rg name> --workspace-name <ws name> --name test-compute-1 --size Standard_D2s_v3 --location northcentralus --type AmlCompute
while my workspace is in eastus2

**Comment by achauhan-scc** [comment]
Thanks @Mmdixon - Able to see the different, will provide an update.
