### ISSUE TITLE
Azure Identity should not use Azure CLI's app ID

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#35825]
**Is your feature request related to a problem? Please describe.**
Currently, Azure Identity by default uses Azure CLI's first-party app ID `04b07795-8ddb-461a-bbee-02f9e1bf7b46`

https://github.com/Azure/azure-sdk-for-python/blob/7e050d9b5a8b0170cc6f4665a70cc1dc54f1f4a3/sdk/identity/azure-identity/azure/identity/_constants.py#L7

as `client_id` in `InteractiveBrowserCredential` and `DeviceCodeCredential`:

https://github.com/Azure/azure-sdk-for-python/blob/7e050d9b5a8b0170cc6f4665a70cc1dc54f1f4a3/sdk/identity/azure-identity/azure/identity/_credentials/browser.py#L79-L79

https://github.com/Azure/azure-sdk-for-python/blob/7e050d9b5a8b0170cc6f4665a70cc1dc54f1f4a3/sdk/identity/azure-identity/azure/identity/_credentials/device_code.py#L74

This is a bad practice as **Azure CLI's app ID should only be used by [Azure CLI](https://github.com/Azure/azure-cli) itself**. Using Azure CLI's app ID in Azure SDK has some problems:

1. It depends on the pre-authorization configured on the app ID. It may lack certain permissions or change without notification. For example, requesting `User.ReadWrite` scope on Microsoft Graph API with Azure CLI's app ID will fail since `User.ReadWrite` is not pre-authorized.
2. It causes unnecessary security alerts for dynamic `user_impersonation` scope.
3. It can pollute telemetry related to Azure CLI, as not all traffic for that app ID is from Azure CLI.

**Describe the solution you'd like**
Azure Identity should request the user to provide a third-party app ID as `client_id`, instead of using Azure CLI's app ID.

**Describe alternatives you've considered**
Azure Identity SDK can request its own first-party application.

**Additional context**
- https://github.com/Azure/azure-sdk-for-python/issues/18008

**Comment by xiangyan99** [comment]
The Azure CLI client ID serves as the default value for both the InteractiveBrowserCredential and DeviceCodeCredential. Removing this default and making the client ID a required parameter would be a significant breaking change, causing considerable inconvenience to our users—including those who do not rely on the CLI client IDs. Therefore, we decided to maintain the existing behavior while documenting best practices to encourage users to register and use their own applications. 

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/browser.py#L30-L33
