### ISSUE TITLE
Error (SearchIndexClient) Creating Index for Edm.ComplexType => The complex field ... cannot have the retrievable property set (STILL ONGOING)

### ISSUE THREAD

**Issue by mgrogger-i11** [Azure/azure-sdk-for-python#35836]
- **Package Name**: azure-search-documents
- **Package Version**: 11.4.0
- **Operating System**: macOS Ventura 13.2.1
- **Python Version**: Python 3.10.9

**Describe the bug**
I am facing the exact same error as what is detailed in #33280

The comments say that a fix was merged and that it would be available in the next release (December 2023). However, this issue persists today and is making it impossible to create an index with ComplexFields from a JSON file. 

The error persists even when I set `"retrievable": false` In both the ComplexField and Sub Fields. i.e., regardless of the value I pass, the issue persists

Please provide update on when the fix will be available via pip upgrade .

Error:
`HttpResponseError: (InvalidRequestParameter) The request is invalid. Details: definition : The complex field 'rooms' cannot have the retrievable property set. Instead, set the retrievable property on sub-fields of the complex type.`

JSON Schema

```
{
 "name": "dummy-test-schema",
    "fields":[
         {
          "name": "hotelId",
          "type": "Edm.String",
          "key": true,
          "retrievable": true,
          "searchable": false,
          "filterable": true,
          "sortable": true,
          "facetable": true
        },
        {
          "name": "rooms",
          "type": "Edm.ComplexType",
          "retrievable": false,
          "fields": [
            {
              "name": "description",
              "type": "Edm.String",
              "key": false,
              "retrievable": false,
              "searchable": true,
              "filterable": false,
              "sortable": false,
              "facetable": false,
              "analyzer": "en.lucene"
            },
            {
              "name": "descriptionFr",
              "type": "Edm.String",
              "key": false,
              "retrievable": false,
              "searchable": true,
              "filterable": false,
              "sortable": false,
              "facetable": false,
              "analyzer": "fr.lucene"
            },
            {
              "name": "type",
              "type": "Edm.String",
              "key": false,
              "retrievable": false,
              "searchable": true,
              "filterable": true,
              "sortable": false,
              "facetable": true
            }
         ]
       }
    ]
} 
```

**To Reproduce**
Use the json schema to create an index then run the following:
1.` try:
        upload_schema = admin_client.create_index(index)
        if upload_schema:
            print(f"Schema uploaded; Index created for {index_name}.")
        else:
            exit(0)
    except:
        print("Unexpected error:", sys.exc_info()[0])`

**Expected behavior**
Expect to create an index successfully

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Seems like you are still using the version that does not have the fix.

Have you tried https://pypi.org/project/azure-search-documents/11.6.0b4/?

**Comment by mgrogger-i11** [comment]
Thanks - didn't see it was part of an unstable release! Will switch to that for now and make sure it doesn't add any issues to other parts of our code :)
