### ISSUE TITLE
Invoice prebuilt models of Document Intelligence does not detect all line items

### ISSUE THREAD

**Issue by galvangoh** [Azure/azure-sdk-for-python#35847]
- **Package Name**: azure-ai-documentintelligence
- **Package Version**: 1.0.0b2
- **Operating System**: Windows
- **Python Version**: 3.10.9

**Describe the bug**
I have a 2 page invoice document (1st page table 18 rows of line items, 2nd page table 1 row of line item) of total 19 line items. I am using both the studio and sdk for testing purposes.

The prebuilt model does not really extract all line items out neatly. For context, the document is searchable so there should be no issue in detecting each line.

Questions:

1. Why the invoice prebuilt model cannot detect each line item?
2. Any document preprocessing needed from user side to enhance model performance?
3. How often are the prebuilt models retrained? 

**Expected behavior**
All line items in table detected.

**Screenshots**
This is a screenshot from studio. There are 2 rows in the document that are being detected as a single entity.
![image](https://github.com/Azure/azure-sdk-for-python/assets/125248069/923a080d-6b62-4c40-8f1e-34aaf3fcda72)

Original document (texts are highlighted to show that they are searchable)
![image](https://github.com/Azure/azure-sdk-for-python/assets/125248069/50bc8c39-0da1-4ef7-994c-802913951961)

**Comment by YalinLi0312** [comment]
Hi @galvangoh , thanks for your feedback, we'll investigate ASAP!

@bojunehsu This issue is from `prebuilt-invoice` model, can you help to answer the questions?

**Comment by bojunehsu** [comment]
@galvangoh Can you please share the original input file with us (formrecog_contact@microsoft.com) to assist with debugging?  We regularly update the models a few times a year to improve quality and reflect feedback such as this.  Thanks.

**Comment by galvangoh** [comment]
@bojunehsu I have shared the document with you via the email address you provided.

**Comment by galvangoh** [comment]
Hey @bojunehsu are there any updates with the debugging?

**Comment by TFR258** [comment]
Hi @galvangoh ,

I hope all is well with you. I don't know if you saw our email response. This issue is caused by table detection dropping the 11 from the table.

![image](https://github.com/Azure/azure-sdk-for-python/assets/12031629/77200ba6-7744-430f-b7ad-766da51c4b45)

We are looking potential improvements we will circle back when we have an update.

Thanks

**Comment by galvangoh** [comment]
Hi @TFR258 thank you for your reply.
