### ISSUE TITLE
ClientSecretCredentials  getToken() 

### ISSUE THREAD

**Issue by sofiasmolen-8451** [Azure/azure-sdk-for-python#35885]
We use ClientSecretCredential class from Microsoft’s azure-identity package to extract security token and we use this token to connect to Snowflake.
The problem with ClientSecretCredential is - when it gets first token, it caches it. Every time you request a new token – ClientSecretCredential return the same cached token until this token expires ( which is 60 min). After 60 min ClientSecretCredentials refreshes token automatically.
There is no way to force ClientSecretCredential to refresh token which has not expired.  In the case when this token is about to expire ( let’s say it expires in 10 seconds), ClientSecretCredential returns cached token and, by the time this token reaches Snowflake – its already expired; Snowflake throws ‘token expired’ exception. 
 

**Describe the solution you'd like**
We would like to add one more method to ClientSecretCredential which would allow us to force get new (not cached) token when the original token is about to expire.

**Describe alternatives you've considered**
We can create a new instance of ClientSecretCredential every time we need a new (not cached) token.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you share some samples code how you use the credential?

**Comment by sofiasmolen-8451** [comment]
class AuthSess:
  

    def __init__(
            self,
            client_secret: str,
            tenant: str,
            app_id: str,
            sub_id_par: str
    ) -> object:
        """

        @type sub_id_par: object
        """
        self.client_secret = client_secret
        self.tenant = tenant
        self.auth_token = {}
        self.app_id = app_id
        self.scopes = f"{app_id}/.default"
        self.default_credential = ClientSecretCredential(tenant_id=tenant, client_id=app_id,
                                                         client_secret=client_secret)
        self.sub_id = sub_id_par

        self.auth_token = self.default_credential.get_token(self.scopes)

    def _request_new_auth_token(self):

        return self.default_credential.get_token(self.scopes)

    def _get_or_refresh_auth_token(self):

        time_till_expire = (
                int(self.default_credential.get_token(self.scopes)[1]) - int(time.time())
        )
        if time_till_expire < 60:
            self.auth_token = self._request_new_auth_token()

    @property
    def subacct(self) -> str:
        return self.sub_id

    @property
    def access_token(self):
        try:
            self._get_or_refresh_auth_token()
            return self.auth_token[0]
        except Exception:
            raise ValueError(f"Error authenticating user")
