### ISSUE TITLE
How to add permission to builtin role in storage account?

### ISSUE THREAD

**Issue by himanshu219** [Azure/azure-sdk-for-python#3588]
I have a storage account and I want to give permission to one of my App Service in  "Storage Account Key  Operator Service Role".
Similar to the below action in Azure portal.

<img width="541" alt="screen shot 2018-10-12 at 9 09 38 am" src="https://user-images.githubusercontent.com/3620468/46846740-a517fc80-cdfe-11e8-876f-6ed24b3f2d0b.png">

**Comment by lmazuel** [comment]
Hi @himanshu219 
Storage account questions have a more focused issue tracker:
https://github.com/Azure/azure-storage-python

Thank you,

@zezha-msft FYI
