### ISSUE TITLE
Policy definition properties are of generic type "object"

### ISSUE THREAD

**Issue by kmai** [Azure/azure-sdk-for-python#3589]
Hi,

I'm trying to create policy definitions using the Python SDK. On the documentation both `policy_rule`, `parameters` and `metadata` are type `object`, even though there seems to be no class that defines the data model for those fields.

- Is this standard behaviour? Is it missing for any reason? Is there a standard way of implementing this, besides writing my own class for it? The intent is to avoid implementing code twice.

- How should the policy rules be defined within the object? Should it be a dict? Should it be an Object too?

I'm relying on [this](https://docs.microsoft.com/en-gb/python/api/azure-mgmt-resource/azure.mgmt.resource.policy.v2018_03_01.models.policy_definition.policydefinition?view=azure-python) and [this](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/policy/v2016_12_01/operations/policy_definitions_operations.py) to create the policy definitions.

I've noticed that there is a new version of the models/operators from 2018 but it's not been "implemented" on the code (it's still using 2016's one)

**Comment by lmazuel** [comment]
Hi @kmai 
`object` means that anything you put will be sent "as-is" part of the JSON to Azure. Whatever it's a dict, a string or anything else. This is usually done by the service team when the format can be so may different things, that it's difficult to take only one type of object.

Example:
```json
        definition = self.policy_client.policy_definitions.create_or_update(
            policy_name,
            {
                'policy_type':'Custom',
                'description':'Don\'t create a VM anywhere',
                'policy_rule':{  
                    'if':{  
                      'allOf':[  
                        {  
                          'source':'action',
                          'equals':'Microsoft.Compute/virtualMachines/write'
                        },
                        {  
                          'field':'location',
                          'in':[  
                            'eastus',
                            'eastus2',
                            'centralus'
                          ]
                        }
                      ]
                    },
                    'then':{  
                      'effect':'deny'
                    }
                }
            }
        )
```
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/tests/test_mgmt_resource_policy.py

About the 2018/2016, you are right that I forgot to update the model alias, my bad. To import the right model, please use:
``` json
models = PolicyClient.models()
models.PolicyDefinition()
...
```
