### ISSUE TITLE
BlobSasPermissions needs to support `List` 

### ISSUE THREAD

**Issue by skyline75489** [Azure/azure-sdk-for-python#35899]
**Is your feature request related to a problem? Please describe.**

It is not currently easy to add `List` permission using `BlobSasPermissions`, unless directly using string `l` for permission.

**Describe the solution you'd like**

Maybe add an argument named `list` here:

https://github.com/Azure/azure-sdk-for-python/blob/990a87b8b04559416edcbbd9e0720f239871371d/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py#L913

**Describe alternatives you've considered**

**Additional context**

All possible permissions: https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#specify-permissions

**Comment by jalauzon-msft** [comment]
Hi @skyline75489 Chester, the "list" permission is only applicable to containers, not individual blobs, and therefore is not present on `BlobSasPermissions` but rather [`ContainerSasPermissions`](https://github.com/Azure/azure-sdk-for-python/blob/73cf501eacd74e8efc2ee19a860e2c3220697aa7/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py#L805). This can be used with [`generate_container_sas`](https://github.com/Azure/azure-sdk-for-python/blob/73cf501eacd74e8efc2ee19a860e2c3220697aa7/sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py#L384) to generate a SAS with list permissions on a specific container.

Hopefully that helps but let us know if you have any further questions. Thanks.

**Comment by skyline75489** [comment]
Thanks! I didn't know that ContainerSasPermissions exists until now.
