### ISSUE TITLE
calling list after create_or_update data does not return any ItemPaged. sdk/ml/azure-ai-ml/azure/ai/ml/operations/_datastore_operations.py create_or_update 

### ISSUE THREAD

**Issue by seekerofsai** [Azure/azure-sdk-for-python#35906]
- **Package Name**: azure.ai.ml
- **Package Version**: azure-ai-ml==1.16.1
- **Operating System**: mac os 14.5
- **Python Version**: Python 3.11.9

**Describe the bug**
Calling list after create_or_updates does not return items

**To Reproduce**
   dataset = Data(
        path=config['data_path'],
        type=AssetTypes.URI_FILE,
        description=config['dataset_desc'],
        name=config['dataset_name'],
    )
    ml_client.data.create_or_update(aml_dataset)
    dataitems = ml_client.data.list((name =config['dataset_name'])

**Expected behavior**
 expect dataitems to have non zero items

**Screenshots**

**Additional context**
seems there is delay in data.list to get items after data.create_or_update call.

**Comment by achauhan-scc** [comment]
@seekerofsai - Can you please confirm the output of create_or_update? I used below script and its providing expected results.



credential = DefaultAzureCredential()
ml_client = MLClient(
    credential=credential,
    subscription_id=subscription_id,
    resource_group_name=resource_group,
    workspace_name=workspace_name,
)
config_db_name ="testingGHIssue"
dataset = Data(
path="D:\\mlflow\\code\\data\\ames_housing.csv",
type=AssetTypes.URI_FILE,
description="testData",
name=config_db_name,
)
data = ml_client.data.create_or_update(dataset) #capture the output and use it while fetching data object in next line.
dataItem = ml_client.data.get(name=data.name,version=data.version)
print(f"asset URI: {dataItem.path}")
v1df = pd.read_csv(dataItem.path)
print(v1df.head(5))

dataItems = ml_client.data.list(config_db_name)

for i, r in enumerate(dataItems):
    print(r.name + r.version)

**Comment by achauhan-scc** [comment]
@seekerofsai - I lost track of this sorry about that, but I tried today again with the latest build and still unable to repo. 
Let's try with CLI and see if you can get the same result back.
**az ml data list -g <resource group name> --workspace-name <workspace name> --output table**
If you still get empty result, can you please grab the debug logs of cli and share those?
**Please note - you need to clear the sensitive information before sharing them.**

**Comment by seekerofsai** [comment]
sorry for the delay. i will retry and update in couple of days.

**Comment by achauhan-scc** [comment]
closing as no response
