### ISSUE TITLE
Facing Intermittent SSL Certification Failure error in azure-servicebus

### ISSUE THREAD

**Issue by kamleshsolanki-crest** [Azure/azure-sdk-for-python#35927]
### **Issue Details**

We are experiencing intermittent SSL certificate verification issues when utilizing the Azure Service Bus SDK on a virtual machine. The specific error encountered is **`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)`**. Interestingly, this issue does not arise when the same SDK is used on cloud-based machines, such as those on AWS. Additionally, the problem is inconsistent, as sometimes the issue will resolve itself after several attempts and the SDK functions as expected. All the traffic is allowed in the machine and firewall is also disabled.

### **SDK Utilization**

- **SDK**: **`azure-servicebus==7.12.1`**
- **Packaging**: This SDK has been integrated directly into our plugin.

### **Error Message**
`azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)`

### **Methods Employed**

**To send messages to the Azure Service Bus queue:**

```python
import os
from azure.servicebus import ServiceBusClient, ServiceBusMessage

CONNECTION_STR = os.environ['SERVICEBUS_CONNECTION_STR']
QUEUE_NAME = os.environ["SERVICEBUS_QUEUE_NAME"]

def send_single_message(sender):
    message = ServiceBusMessage("Single Message")
    sender.send_messages(message)

servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR, logging_enable=True)
with servicebus_client:
    sender = servicebus_client.get_queue_sender(queue_name=QUEUE_NAME)
    with sender:
        send_single_message(sender)
        # Assuming the implementations of send_a_list_of_messages(sender) and send_batch_message(sender) are defined elsewhere
``` 

**To list messages present on the Azure Service Bus queue:**

```python
import os
from azure.servicebus.management import ServiceBusAdministrationClient

CONNECTION_STR = os.environ['SERVICEBUS_CONNECTION_STR']

with ServiceBusAdministrationClient.from_connection_string(CONNECTION_str) as servicebus_mgmt_client:
    # Assuming the implementations of create_queue, get_and_update_queue, get_queue_runtime_properties, and delete_queue are defined elsewhere
    def list_queues(servicebus_mgmt_client):
        print("-- List Queues")
        for queue_properties in servicebus_mgmt_client.list_queues():
            print("Queue Name:", queue_properties.name)
        print("")
    
    list_queues(servicebus_mgmt_client)
``` 
**Error Traceback**
```python
Traceback (most recent call last):
  File "/opt/netskope/plugins/Devrepo/azure_service_bus/main.py", line 184, in list_queues
    for queue_properties in servicebus_mgmt_client.list_queues():
  File "/usr/local/lib/python3.9/site-packages/azure/core/paging.py", line 132, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/netskope/plugins/Devrepo/azure_service_bus/lib/azure/servicebus/management/_utils.py", line 104, in get_next_template
    list_func(skip=start_index, top=max_page_size, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/netskope/plugins/Devrepo/azure_service_bus/lib/azure/servicebus/management/_generated/operations/_operations.py", line 842, in list_entities
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 160, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 512, in send
    raise err
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 484, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 382, in send
    raise error
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
```

**Comment by kashifkhan** [comment]
Hi @kamleshsolanki-crest , 

This issue is coming from the ServiceBusAdmin client. There could a couple of things at play here which basically boil down to - are the certificates installed and accessible on the VM

* Can you try upgrading/installing certifi `pip install -U certifi`
* Are there any proxies involved on the network ?

**Comment by kamleshsolanki-crest** [comment]
Hi @kashifkhan,

Thanks for the quick response!

- I'm using the latest certifi (version 2024.6.2).
- There is no proxy involved. This is a corporate network, so the traffic is navigating via VPN and firewall. I have checked for any blockages, and everything is enabled in the network.

**Comment by kashifkhan** [comment]
@kamleshsolanki-crest do things work as expected without the VPN ?

**Comment by kamleshsolanki-crest** [comment]
@kashifkhan As this is an corporate network in order to access the VM VPN is must. But as I mentioned in the description that in cloud platform such as Amazon EC2 and Azure it is working fine.

Also note that our service is running on Docker containers.

**Comment by kashifkhan** [comment]
@kamleshsolanki-crest I would have to say there is something with the VM and the corp environment. Given that that sdk is working fine in other places, the only other suggestion I have here is making sure that certs.pm has the necessary information needed on the VM.

**Comment by kamleshsolanki-crest** [comment]
Thank you for your feedback. I agree that the issue might be related to the VM and the corporate environment, especially since the SDK is functioning correctly in other places.

I will ensure that the certs.pm file on the VM has all the necessary information. Could you provide more details on what specific information or configurations should be included in certs.pm? Additionally, are there any other environment settings or prerequisites that we should verify on the VM?

**Comment by kashifkhan** [comment]
Hi @kamleshsolanki-crest this stackoverflow thread has a few good options to try out https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate

Some things to try

*  See if the network admin for your company can help you point to the certs and it can be added via `REQUESTS_CA_BUNDLE` https://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification
*  Microsoft CA root from the trust store needs to be added to the environment
