### ISSUE TITLE
DataLakeDirectoryClient get_paths() to list paths within a directory

### ISSUE THREAD

**Issue by tomi-neuron** [Azure/azure-sdk-for-python#35928]
It is annoying that while you can list the paths under a directory using **FileSystemClient** and the **name** of the directory using .get_paths(path), you cannot do so using the **DataLakeDirectoryClient**, which would be very useful as most of the file system level functions are already implemented in the directory client but not the **get_paths**().

What is available: 
_paths = file_system_client.get_paths(path=directory_name)_

What would be useful:
_paths = directory_client.get_paths()_

because now I have to drag the file system client, directory client, and directory name through my code, instead of just the directory client once I defined it at the start.

**Comment by jalauzon-msft** [comment]
Hi @tomi-neuron, thanks for reaching out. This is a reasonable ask and some of our other languages do offer this functionality. We will look into adding this to Python. It may be a little while though as we other priorities at the moment.

**Comment by jalauzon-msft** [comment]
Hi @tomi-neuron, sorry for the delay here but we recently merged #37220 (into a feature branch) that contains this feature. This will be part of our next releases in October (preview) and November (GA). Thanks!
