### ISSUE TITLE
Error Message: The requested stream was not found. Please make sure the request uri is correct. SDKv1 and SDKv2

### ISSUE THREAD

**Issue by ErvinPuratos** [Azure/azure-sdk-for-python#35949]
- **Package Name**: azureml-dataprep5.1.6 SDKv2 and azureml-dataprep 5.1.6 SDKv1
- **Operating System**: Linux
- **Python Version**: 3.12 for v2 and 3.8 for v1

**Describe the bug**
In both SDK versions, I am able to load the dataset using the respective synthax but when I use the to_pandas_dataframe() method on those dataset I will get the following error:

`{
	"name": "UserErrorException",
	"message": "\nError Code: ScriptExecution.StreamAccess.NotFound\nNative Error: Dataflow visit error: ExecutionError(StreamError(NotFound))\n\tVisitError(ExecutionError(StreamError(NotFound)))\n=> Failed with execution error: error in streaming from input data sources\n\tExecutionError(StreamError(NotFound))\nError Message: The requested stream was not found. Please make sure the request uri is correct.| session_id=l_0c303b7e-feb1-42f2-8647-97776653d682",`

**To Reproduce**
1. register a dataset
2. Load dataset using its constructor
3. use the to_pandas_dataframe() method on the dataset object

**Expected behavior**
A dataframe to be returned
**Screenshots**

**Additional context**
The only version I found  where this does not happen is:

azureml-dataprep                     4.9.7
azureml-core                         1.49.0

**Comment by xiangyan99** [comment]
Thanks for reaching out.

azureml-dataprep is not monitored in this repo.

**Comment by ErvinPuratos** [comment]
so would you mind directing where I can raise this issue? IN the end I am unable to use any of the azureml fonctionalities because of this bug...
