### ISSUE TITLE
Question: Can Another Backend Instance Continue Polling if One Instance Restarts During Document Intelligence Analysis?

### ISSUE THREAD

**Issue by aymenfurter** [Azure/azure-sdk-for-python#35945]
Hi there! 😊

I'm using Document Intelligence in my stateless backend, which is horizontally scaled with multiple instances running. If one of my instances restarts while the document analysis is still running, can another instance continue polling?

I implemented the following solution, but I'm not entirely satisfied with it. I'd be interested to know if there's a more elegant or built-in way to achieve this.

```python
# Trigger the DI analysis
client = DocumentIntelligenceClient(endpoint, AzureKeyCredential(key))
poller = client.begin_analyze_document("prebuilt-layout", AnalyzeDocumentRequest(url_source=url), output_content_format=ContentFormat.MARKDOWN)
continuation_token = poller.continuation_token()
 
# Continue Polling (on process restart)
client = DocumentIntelligenceClient(endpoint, AzureKeyCredential(key))
polling_method = LROBasePolling()
new_poller = LROPoller.from_continuation_token(
    polling_method=polling_method,
    continuation_token=continuation_token,
    deserialization_callback=deserialize_analyze_result,
    client=client._client
)
result = new_poller.result()
```

Is there a better solution? Ideally I would prefer to be able to directly interact with the downstream document intelligent API (i.e. trigger the analysis job, get the Operation-location & read the status)

**Comment by lmazuel** [comment]
@aymenfurter I'm actually impressed that you were able to figure out this low level "continue polling" code. All my respect for that :)

The official way is something like (not tested, so a few adjustement may be necessary):
```python
poller = client.begin_analyze_document(
   None,
   continuation_token=continuation_token
)
```

The code will bypass starting the operation, and recreate the poller. See here:
https://github.com/Azure/azure-sdk-for-python/blob/0b99ee1eb697c96dcbbef0f9033d37dda84808ae/sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_operations/_operations.py#L3626-L3641

It's not ideal that we have to pass a fake `None` to all required parameters, so I asked @kashifkhan to redesign, but it may take some time.

In the meantime, your code, or the official code, all works fine.

**Comment by lmazuel** [comment]
@aymenfurter what you want is do-able with the SDK, the approach is the following:
- pass `polling=False` ([see](https://github.com/Azure/azure-sdk-for-python/blob/0b99ee1eb697c96dcbbef0f9033d37dda84808ae/sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_operations/_operations.py#L3623)). You will receive an empty poller that you can discard
- pass a `raw_response_hook` callback ([see](https://github.com/Azure/azure-sdk-for-python/blob/66d5de409d0980d3b2c7b82971cc648f9d5cd6a5/sdk/core/azure-core/samples/test_example_policies.py#L28-L45)). This gives you access to the initial response, from which you can pull the `Operation-Location`
- call `send_request` on the client ([see](https://github.com/Azure/azure-sdk-for-python/blob/0b99ee1eb697c96dcbbef0f9033d37dda84808ae/sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_client.py#L77)), which allow you to pass an `HttpRequest` object, giving full RestAPI access, while having all auth troubles solved for free. This is a sample of `send_request` for KV, that can be easily adapted to DocIntel ([see](https://github.com/Azure/azure-sdk-for-python/blob/0b99ee1eb697c96dcbbef0f9033d37dda84808ae/sdk/keyvault/azure-keyvault-keys/samples/send_request.py))

The code should look like this (not tested, a few adjustements might be necessary):

```python
operation_location = None
def extract_operation_location(pipeline_response):
   operation_location = pipeline_response.response.headers['operation-location']
client.begin_analyze_document(
  **required_params,
  polling=False,
  raw_response_hook=extract_operation_location
)

request = HttpRequest("GET", operation_location)
http_response = client.send_request(request)
```

I didn't have the opportunity to run it to confirm it's all 100% runnable as-is, if what I wrote is not enough, let me know and I'll spend some time to run it and write a tested runnable sample. Thanks!

**Comment by aymenfurter** [comment]
Thank you for your support 🤗
