### ISSUE TITLE
Difference in values of confusion matrix after training between python sdk and what's displayed on vision portal.

### ISSUE THREAD

**Issue by rishk2697** [Azure/azure-sdk-for-python#35946]
- **Package Name**: azure-cognitiveservices-vision-customvision
- **Package Version**: 3.1.0
- **Operating System**: Windows 11 Pro
- **Python Version**: 3.12.3

**Describe the bug**
Im trying to perform object detection to determine if my book called X which has different front covers is present in the image or not!

Using python sdk, annotated images in local system, uploaded images & annotations via sdk, checked on portal - got uploaded with the region, did regular training via sdk and printed the performance metrics to cross check with what is shown in portal under performance tab, and got different results. 

**To Reproduce**
1. Take set of images(100) for object detection 
2. Annotate them
3. Upload images & annotations on the portal using sdk
4. Regular train the model using python SDK
5. Print confusion metrics in local 
6. Compare with what is displayed on the portal

**Expected behavior**
Difference in values between what is displayed on portal and what is fetched using python sdk

**Screenshots**
![Metrics displayed on local](https://github.com/Azure/azure-sdk-for-python/assets/171917349/a717928e-7b09-48b8-a4ca-133e357b799f)
![Metrics displayed on portal](https://github.com/Azure/azure-sdk-for-python/assets/171917349/228d68c8-baa9-4324-a619-cf7f816bc8ff)

**Additional context**
Also have made sure Iteration ID is correct, please refer both screenshots. Also I'd like to point it out again, Ive only done training, not quick test and I'm unable to understand why is there a difference in values.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by pj-ms** [comment]
Please check the documentation especially 
- the parts related to Probability Threshold and Overlap Threshold to better understand the metrics 
- how to use the API: get_iteration_performance.

https://learn.microsoft.com/en-us/rest/api/customvision/iterations/get-performance?view=rest-customvision-v3.3&tabs=HTTP

You can also search "mAP vs IOU" and "Precision & Recall vs Probability Threshold to find" to know more about those metrics.

**Comment by swathipil** [comment]
Hi @rishk2697 - We will be officially deprecating the azure-cognitiveservices-vision-customvision package and are no longer maintaining it. We will not be unpublishing the packages from PyPI so they will still be installable.

As this is not SDK related, we'll close the issue.
