### ISSUE TITLE
[breaking changes tracker] Update suppression mechanism to support more complex suppression scenarios

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-python#35988]
- We might want to suppress changes reported at the function or property level for all models or operations.
- We may want to add suppressions across libraries. 

Example:
Mgmt plane libraries migrating to dpg will need to widely suppress changes between msrest and the new dpg design on all models.

**Comment by catalinaperalta** [comment]
Some scenarios to consider:
- Suppress a change on a parameter in a whole library
- Suppress a change on a method in a whole library
- Suppress a change across multiple libraries. i.e. suppress the removed *ListResult model across all mgmt specs.

Should we be able to suppress a change with a regex to match model names following that pattern?

**Comment by catalinaperalta** [comment]
Do we also need an exception mechanism for mass suppressions? i.e. suppress changes reported throughout all of the mgmt libs except for one.

**Comment by msyyc** [comment]
> Do we also need an exception mechanism for mass suppressions? i.e. suppress changes reported throughout all of the mgmt libs except for one.

As MGMT SDK owner, I hope we could have the exception mechanism.
