### ISSUE TITLE
Accessing message type, IoT  Hub and encoding information via `azure.servicebus.ServiceBusReceivedMessage`

### ISSUE THREAD

**Issue by Time0o** [Azure/azure-sdk-for-python#35999]
**Is your feature request related to a problem? Please describe.**

When routing telemetry to e.g. a Servicebus topic, certain properties set by the device cannot be reconstructed on the cloud side using the interface provided by `azure.servicebus.ServiceBusReceivedMessage`. I have gone through the relevant documentation and it's not clear to whether this is due to how Servicebus message are structured, due to missing SDK features or whether I'm supposed to solve my issue in an entirely different way. 

**Describe the solution you'd like**

Concretely, for every message read via a Servicebus Topic subscription I'd like to know:

1. Is this telemetry?
2. What IoT Hub does this come from?
3. What device does this come from?
4. When was this created?
5. How is this encoded?

Using the `ServiceBusReceivedMessage` interface I can solve:

3. (`iothub-connection-device-id` in application properties)
4. (`iothub-creation-time-utc` in application properties)

But I cannot solve:

1. Other messages routed to the service bus topic, e.g. device twin change events, have a different format. But there seems to be no message property I can switch on to find out whether something is telemetry.
2. Device SDKs seem to support setting `user-id` but I don't know how to access this from the cloud side.
5. Device SDKs seem to support setting `content-encoding` but I don't know how to access this from the cloud side. This one is especially dire because it means if I encode my telemetries with e.g. gzip, a generic backend program can't possibly know how to decode them.

**Describe alternatives you've considered**

I've manually verified that the MQTT topic that my device sends telemetry to looks okay. But again, I'm not sure if the supported properties with special meaning in the property bag are documented anywhere:

```
devices/my_device/messages/events/%24.uid=my_iot_hub&%24.ct=application%2Fjson&%24.ce=utf-8&%24.ctime=2024-06-10T15:08:23.0000000Z
```

**Comment by l0lawrence** [comment]
Hi @Time0o, 

Could you please provide the steps to repro your scenario - how are you routing telemetry to the service bus topic?

**Comment by Time0o** [comment]
Hello @l0lawrence 

In my IoT Hub I have set up the following message route:

```json
$ az iot hub message-endpoint show --hub-name my-iot-hub --route-name RouteDeviceTelemetryToServicebusTopic
{
  "condition": "true",
  "endpointNames": [
    "my-events"
  ],
  "isEnabled": true,
  "name": "RouteDeviceTelemetryToServicebusTopic",
  "source": "DeviceMessages"
}
```

With the custom endpoint `my-integration-endpoints` which points to a service bus topic:

```json
$ az iot hub message-endpoint show --hub-name my-iot-hub --endpoint-name my-events
{
  "authenticationType": "keyBased",
  "connectionString": "Endpoint=sb://my-org.servicebus.windows.net:5671/;SharedAccessKeyName=iothubroutes_my-iot-hub;SharedAccessKey=****;EntityPath=my-events",
  "endpointUri": null,
  "entityPath": null,
  "id": "07701905-2e42-48e2-bb4b-74f1d970ffe8",
  "identity": null,
  "name": "my-events",
  "resourceGroup": "development",
  "subscriptionId": "19b63fd9-664d-4ed1-893f-92a4467c404e"
}
```

```
$ az servicebus topic show  --resource-group development --namespace-name gfservicebus -n my-events
{
  "accessedAt": "2024-06-12T13:16:34.743017Z",
  "autoDeleteOnIdle": "P10675199DT2H48M5.4775807S",
  "countDetails": {
    "activeMessageCount": 0,
    "deadLetterMessageCount": 0,
    "scheduledMessageCount": 0,
    "transferDeadLetterMessageCount": 0,
    "transferMessageCount": 0
  },
  "createdAt": "2024-06-05T10:15:02.0572002Z",
  "defaultMessageTimeToLive": "P14D",
  "duplicateDetectionHistoryTimeWindow": "PT10M",
  "enableBatchedOperations": true,
  "enableExpress": false,
  "enablePartitioning": false,
  "id": "/subscriptions/19b63fd9-664d-4ed1-893f-92a4467c404e/resourceGroups/development/providers/Microsoft.ServiceBus/namespaces/gfservicebus/topics/my-events",
  "location": "westeurope",
  "maxMessageSizeInKilobytes": 256,
  "maxSizeInMegabytes": 1024,
  "name": "gapfruit-integration-events",
  "requiresDuplicateDetection": false,
  "resourceGroup": "development",
  "sizeInBytes": 331334249,
  "status": "Active",
  "subscriptionCount": 1,
  "supportOrdering": false,
  "type": "Microsoft.ServiceBus/namespaces/topics",
  "updatedAt": "2024-06-05T10:16:57.9025919Z"
}
```

**Comment by l0lawrence** [comment]
Hi @Time0o thanks for the setup, could you please provide:

- a code sample of how you are sending the messages to the Hub
- a code sample of how you are calling the Azure Servicebus SDK to receive the messages
- a sample message that is being sent to the iothub
