### ISSUE TITLE
[identity] DefaultAzureCredentials do not work properly under a proxy environment

### ISSUE THREAD

**Issue by odgrso** [Azure/azure-sdk-for-python#35991]
The following is the same bug in python
https://github.com/Azure/azure-sdk-for-js/issues/28595

**Comment by Th3OnlyN00b** [comment]
I am also getting this with the following code:
```py
AZURE_SERVICE_CREDENTIAL = DefaultAzureCredential()
logging.warn(constants.AZURE_SERVICE_CREDENTIAL.get_token("https://graph.microsoft.com/.default")) # This returns a real token
client = CosmosClient(constants.COSMOS_URL, credential=AZURE_SERVICE_CREDENTIAL, enable_diagnostics_logging=True) # This fails
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

It is known that managed identity does not work correctly behind a proxy. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#azure-virtual-machine-managed-identity

You can disable managed identity in DefaultAzureCredential when you want to use it under a proxy environment.
