### ISSUE TITLE
azure-identity support for few remaining clients

### ISSUE THREAD

**Issue by vitalybondarenko** [Azure/azure-sdk-for-python#35992]
I still need to use CredentialWrapper with some azure.mgmt.* clients:

azure.mgmt.documentdb: DocumentDB
azure.mgmt.sqlvirtualmachine: SqlVirtualMachineManagementClient

I'm leaving a request to re-release these SDKs as suggested here 
https://stackoverflow.com/questions/63384092/exception-attributeerror-defaultazurecredential-object-has-no-attribute-sig
by @lmazuel 

Vitaly

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Looks like you are using track1 libraries for DocumentDB & SqlVirtualMachineManagementClient.

It is by design that identity library does not work with track 1 libraries.

Please upgrade your libraries.

**Comment by vitalybondarenko** [comment]
@xiangyan99, thank you for your response. I have checked and see that I have the latest non-beta versions of both libraries. Could you please specify which exact versions I should try?

**Comment by xiangyan99** [comment]
Thanks for the confirmation.

@msyyc do you know if we have schedule to ship track 2 DocumentDB & SqlVirtualMachine mgmt SDKs?

**Comment by msyyc** [comment]
- documentdb is not released over 7 years https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cosmos/azure-mgmt-documentdb and we don't have plan to update it since no service team ask for the SDK release
- SqlVirtualMachine has beta version 1.0.0b6 https://pypi.org/project/azure-mgmt-sqlvirtualmachine/1.0.0b6/ which is track2.

**Comment by vitalybondarenko** [comment]
So, what is necessary to get a track2 release for documentdb? If this SDK is no longer supported, maybe it makes sense to clearly state that.
And what is necessary to move SqlVirtualMachine track2 from beta to release?
Vitaly

**Comment by vitalybondarenko** [comment]
Okay, thank you for the clarification. It looks like there is no easy way to get it fixed; procedural actions require much effort compared to the benefit obtained. I will stay with workarounds that work for me now.
