### ISSUE TITLE
ServiceRequestError: SSL Certificate Verification Failure with Azure Document Intelligence

### ISSUE THREAD

**Issue by Nirmalpatil19** [Azure/azure-sdk-for-python#36003]
- **Package Name - azure-ai-documentintelligence**: 
- **Package Version - 1.0.0b3**: 
- **Operating System -  Windows 10 **:
- **Python Version - 3.10.4**: 

**Describe the bug**
I am encountering a ServiceRequestError when attempting to analyze a PDF document using the Azure Document Intelligence service. The error seems to be related to SSL certificate verification. Below is the full traceback for your reference:

ServiceRequestError Traceback (most recent call last)

...

ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

I want to disable the SSL Verification.  How do I do that using Document Intelligence Client
**To Reproduce**

````
import os
import re
import json
import base64
import logging
from io import BytesIO
from PyPDF2 import PdfWriter, PdfReader
from azure.core.credentials import AzureKeyCredential

from azure.ai.documentintelligence import DocumentIntelligenceClient
def get_text_from_pdf(fname):
    #try:
        fstream = open(fname, "rb")
        inputpdf = PdfReader(fstream)
        page_dict = {}

        document_intelligence_client = DocumentIntelligenceClient(endpoint=config['doc_intel_endpoint'],
                                                                  credential=AzureKeyCredential(config['doc_intel_key']),pipeline=pipeline)
        for i in range(len(inputpdf.pages)):
            output = PdfWriter()
            output.add_page(inputpdf.pages[i])
            response_bytes_stream = BytesIO()
            output.write(response_bytes_stream)

            poller = document_intelligence_client.begin_analyze_document(
                "prebuilt-layout",
                AnalyzeDocumentRequest(bytes_source=response_bytes_stream.getvalue()),
                output_content_format=ContentFormat.MARKDOWN
            )
            result: AnalyzeResult = poller.result()
            page_dict[i + 1] = result.content

        fstream.close()
        return page_dict
    # except Exception as e`
```

Install the required libraries using pip install azure-ai-documentintelligence pypdf2.
Run the provided code snippet with the given PDF file path.
Observe the ServiceRequestError during the document analysis process.
**Expected behavior**
It will give an SSL  Verification error.  It is mostly due to firewall at my companies VDI. I need help in disabling it. 


**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you clarify what you mean by "I need help in disabling it. "?

Do you want to disable the ssl verification?

**Comment by Nirmalpatil19** [comment]
Hello Xiang Yan,

Thank you for your response. I am getting SSL verification error. So the way we say in request(verify=False), can we do something similar in Azure SDK for Document intelligence?



Regards,
Nirmal

**Comment by xiangyan99** [comment]
Thanks for the clarification.

You can add connection_verify=False when you create the client to disable the ssl verification. https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/README.md#configurations

Please note that by setting that, you will not validate the certificate when communicating to the service. It will be insecure.

**Comment by Nirmalpatil19** [comment]
"/unresolve"
Now I am getting 404 Resource not found. I double checked the API key and the endpoint
region - eastus2 

Code :

```

def get_text_from_pdf(fname):
    #try:
        fstream = open(fname, "rb")
        inputpdf = PdfReader(fstream)
        page_dict = {}

        document_intelligence_client = DocumentIntelligenceClient(endpoint=config['doc_intel_endpoint'],
                                                                  credential=AzureKeyCredential(config['doc_intel_key']),connection_verify =False)
        for i in range(len(inputpdf.pages)):
            output = PdfWriter()
            output.add_page(inputpdf.pages[i])
            response_bytes_stream = BytesIO()
            output.write(response_bytes_stream)

            poller = document_intelligence_client.begin_analyze_document(
                "prebuilt-document",
                AnalyzeDocumentRequest(bytes_source=response_bytes_stream.getvalue()),
                output_content_format=ContentFormat.MARKDOWN
            )
            result: AnalyzeResult = poller.result()
            page_dict[i + 1] = result.content

        fstream.close()
        return page_dict
```
Package Name - azure-ai-documentintelligence:
Package Version - 1.0.0b3:
**Operating System - Windows 10 **:
Python Version - 3.10.4:

**Comment by xiangyan99** [comment]
"Now I am getting 404 Resource not found. "

This issue is different from the original one.

To make it more trackable, please open another one. (likely it needs help from a different dev)
