### ISSUE TITLE
Failed to create a index while adding Customer managed keys using SearchResourceEncryptionKey

### ISSUE THREAD

**Issue by SSVSuryaTeja** [Azure/azure-sdk-for-python#36017]
I have reviewed this document, I have followed all the steps below:

https://learn.microsoft.com/en-us/azure/search/search-security-manage-encryption-keys?tabs=portal-pp%2Cmanaged-id-sys

I have used system assigned MI for AI Search and add the required permissions on key vault

I have attached this file to index in blob storage

I am using the sample code:

from azure.core.credentials import AzureKeyCredential
from azure.identity import DefaultAzureCredential
from azure.search.documents.indexes import SearchIndexClient, SearchIndexerClient
from azure.search.documents.indexes.models import *
from azure.keyvault.keys import KeyClient
from azure.identity import ClientSecretCredential

# Configuration values (replace with your actual values)
subscription_id = ""
resource_group_name = "testrg"
search_service_name = "testaisearchtier"
storage_account_connection_string = "storageconnstr"
blob_container_name = "testcontain"
key_vault_name = "keyvalutazureaicrypto"
key_name = "key"
key_version = "version"

# Create a search index client using managed identity
index_client = SearchIndexClient(
    endpoint=f"https://{search_service_name}.search.windows.net",
    credential=DefaultAzureCredential())

# Define the index schema based on the dataset
index_name = "hdi-index"
fields = [
    SimpleField(name="iso3", type=SearchFieldDataType.String, key=True),
    SimpleField(name="country", type=SearchFieldDataType.String, searchable=True),
    SimpleField(name="hdicode", type=SearchFieldDataType.String, filterable=True),
    SimpleField(name="region", type=SearchFieldDataType.String, filterable=True),
    SimpleField(name="hdi_rank_2021", type=SearchFieldDataType.Double, filterable=True, sortable=True),
    SimpleField(name="hdi_1990", type=SearchFieldDataType.Double),
    SimpleField(name="hdi_2021", type=SearchFieldDataType.Double)  # Add other years as needed
]

index = SearchIndex(name=index_name, fields=fields)

# Create the index
index_client.create_index(index)

# Set up Key Vault client
key_vault_client = KeyClient(vault_url=f"https://{key_vault_name}.vault.azure.net", credential=DefaultAzureCredential())
key = key_vault_client.get_key(key_name, key_version)

# Define the encryption key
encryption_key = **SearchResourceEncryptionKey(**
    name=key.name,
    version=key.version,
    vault_url=key_vault_client.vault_url,
)

# Define the data source for the indexer
data_source_name = "hdi-blob-datasource"
data_source = SearchIndexerDataSourceConnection(
    name=data_source_name,
    type="azureblob",
    connection_string=storage_account_connection_string,
    container=SearchIndexerDataContainer(name=blob_container_name),
    description="Blob data source for HDI data",
    encryption_key=encryption_key
)

indexer_client = SearchIndexerClient(
    endpoint=f"https://{search_service_name}.search.windows.net",
    credential=DefaultAzureCredential()
)

# Create the data source
indexer_client.create_data_source_connection(data_source)

# Define the indexer
indexer_name = "hdi-blob-indexer"
indexer = Indexer(
    name=indexer_name,
    data_source_name=data_source_name,
    target_index_name=index_name,
    schedule=None,
    parameters=IndexingParameters(
        configuration={"parsingMode": "delimitedText"},
    )
)

# Create the indexer
indexer_client.create_indexer(indexer)
[HDI.csv](https://github.com/user-attachments/files/15780705/HDI.csv)

print(f"Indexer {indexer_name} created successfully.")

This method SearchResourceEncryptionKey is below error:

**Invalid index schema: encryptionKey - encryptionKey must be a `array` type, but the final value was: `null` (cast from the value `{ 'keyVaultKeyName': '\\'cmk-aisearch-we-tst-air-01-tst-ds-1a-dummy\\'', 'keyVaultKeyVersion': '\\'\\'', 'keyVaultUri': '\\'https://kvwetstair01tstds1adummy.vault.azure.net/\\'', 'accessCredentials': 'undefined', 'identity': 'undefined' }`). If 'null' is intended as an empty value be sure to mark the schema as `.nullable()`**

I need help is resolving this issue

**Comment by SSVSuryaTeja** [comment]
reference class:

https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.indexes.models.searchresourceencryptionkey?view=azure-python

**Comment by xiangyan99** [comment]
Thanks for reaching out.


Could you double check the parameter you provided?

key_name str Required. The name of your Azure Key Vault key to be used to encrypt your data at rest.
key_version  str  Required. The version of your Azure Key Vault key to be used to encrypt your data at rest.
vault_uri  str  Required. The URI of your Azure Key Vault, also referred to as DNS name, that contains the key to be used to encrypt your data at rest. An example URI might be https://my- keyvault-name.vault.azure.net.
application_id  str  Required. An AAD Application ID that was granted the required access permissions to the Azure Key Vault that is to be used when encrypting your data at rest. The Application ID should not be confused with the Object ID for your AAD Application.
application_secret  str  The authentication key of the specified AAD application.

**Comment by SSVSuryaTeja** [comment]
Hi @xiangyan99 , I removed my original values 

below is the screenshot:

![image](https://github.com/Azure/azure-sdk-for-python/assets/44781409/08a7dffd-38a7-409c-ba7a-d066b66cd1c3)

removing the my app registration:

# Configuration values (replace with your actual values)
subscription_id = ""
resource_group_name = "testrg"
search_service_name = "testaisearchtier"
storage_account_connection_string = ""
blob_container_name = "testcontain"
key_vault_name = "keyvalutazureaicrypto"
key_name = "encryptaisearchkey"
key_version = "04e7362ce3f140f9a83f09a91f8e79a2"


I am reading the key vault here:

# Set up Key Vault client
credential = DefaultAzureCredential()
key_vault_client = KeyClient(vault_url=f"https://{key_vault_name}.vault.azure.net", credential=credential)
key = key_vault_client.get_key(key_name, key_version)

**Comment by SSVSuryaTeja** [comment]
Hi @xiangyan99  can you please repro with same code ?

**Comment by xiangyan99** [comment]
Thanks for the information.

I was not asking for the values of the parameters. What I meant was:

encryption_key = SearchResourceEncryptionKey(
name=key.name,
version=key.version,
vault_url=key_vault_client.vault_url,
)

it was supposed to be

encryption_key = SearchResourceEncryptionKey(
__key_name__=key.name,
__key_version__=key.version,
vault_url=key_vault_client.vault_url,
)

and you missed the application_id.

**Comment by saschaschramm** [comment]
I get the same error. I've tried the Azure SDK and the REST-API directly.
Minimal example:

```bash
curl -X POST "https://AAA.search.windows.net/indexes?api-version=2024-05-01-preview" -H "Content-Type: application/json" -H "api-key:BBB" --data-raw "{\"name\":\"hotels\",\"fields\":[{\"name\":\"HotelId\",\"type\":\"Edm.String\",\"key\":true,\"filterable\":true}],\"encryptionKey\":{\"keyVaultUri\":\"https://CCC.vault.azure.net/\",\"keyVaultKeyName\":\"DDD\",\"keyVaultKeyVersion\":\"EEE\"}}"
```

```
Ungültiges Indexschema: encryptionKey - encryptionKey must be a `array` type, but the final value was: `null` (cast from the value `{ "keyVaultKeyName": "\"DDD\"", "keyVaultKeyVersion": "\"EEE\"", "keyVaultUri": "\"https://CCC.vault.azure.net/\"", "accessCredentials": "undefined", "identity": "undefined" }`). If "null" is intended as an empty value be sure to mark the schema as `.nullable()`
```

The search service that connects using a managed identity.
