### ISSUE TITLE
No way to register associated data assets when registering Model with SDKv2

### ISSUE THREAD

**Issue by obiii** [Azure/azure-sdk-for-python#36055]
azure.ai.ml:
1.4.0:
Linux 20xx:
3.10:

**Describe the bug**
We wan to register a trained model in the shared ML registry.

**To Reproduce**
1. Connect to workspace
```
# get a handle to the workspace
ml_client = MLClient.from_config(DefaultAzureCredential())
print(ml_client.workspace_name, ml_client.resource_group_name, sep='\t\t')
```
2. get registered data asset
```
data_asset_name = "file-dataset"
data_asset = ml_client.data.get(name=data_asset_name, version=1)
```
3. train an arbitrary model

4. register model with data asset
```
from azure.ai.ml.entities import Model
from azure.ai.ml.constants import AssetTypes
file_model = Model(
    path="mlflow-model/model.pkl",
    type=AssetTypes.CUSTOM_MODEL,
    name="local-file-example",
    description="Model created from local file.",
    # in sdk v1 there was an attribute called datasets
)
ml_client.models.create_or_update(file_model)
```

**Expected behavior**
There should be a way to attach data assets to the model just like with sdkv1 there was a **datasets** argument in **run.register_model** fucntion.

**Comment by edgBR** [comment]
Ey, same problem here.

BR
E

**Comment by seniut** [comment]
Hello. I have met the same problem on my side

**Comment by SzymonSowinski** [comment]
Hi, I have the same issue

**Comment by Abel-24pal** [comment]
Hi, we have the same problem

**Comment by PratibhaShrivastav18** [comment]
@obiii Thanks for bringing this up. Can you help explain the use case for which you want to attach data assets to the model?

**Comment by obiii** [comment]
@PratibhaShrivastav18 

We have a typical machine learning model training scenario where we require the following capabilities:

Reproducibility: Ensuring that the exact data used for training the model is associated with the model. This is crucial for verifying results and conducting experiments consistently.

Traceability: Keeping track of which datasets were used for training the model. This is essential for monitoring jobs, auditing processes, and understanding the lineage of model development.

Convenience: Providing easy access to the associated datasets for future reference, re-training, or further analysis.

The fact that this was possible with SDKV1 and not possible with  SDKV2 (among alot of other missing features) makes us regret the migration now.

**Comment by edgBR** [comment]
Hi @PratibhaShrivastav18 in here:

https://github.com/Azure/azure-sdk-for-python/issues/29429

This was reported and it was mentioned that it was in the backlog but not ETA yet. Is there any update on this?

**Comment by edgBR** [comment]
Hi @PratibhaShrivastav18  @banibrata-de  any chance to look at this?

BR
E

**Comment by PratibhaShrivastav18** [comment]
Hi, SDK V2 unfortunately doesn't support this. We do have a backlog item but no ETA yet. I would encourage you to checkout [this ](https://github.com/Azure/azure-sdk-for-python/issues/29429#issuecomment-1476439870)comment for a workaround while we work on prioritising this functionality.
