### ISSUE TITLE
Fake breaking change for model property

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#36072]
When I compared [SDK generated from swagger](https://github.com/azure-sdk/azure-sdk-for-python/blob/c3dfd475df7f83a8967572a04d583369c58e68ad/sdk/scvmm/azure-mgmt-scvmm/azure/mgmt/scvmm/models/_models_py3.py#L292-L309) and [SDK generated from Typespec](https://github.com/azure-sdk/azure-sdk-for-python/blob/07202827cf3e7bf65cfb83e53d8b6f85618a286e/sdk/scvmm/azure-mgmt-scvmm/azure/mgmt/scvmm/models/_models.py#L231-L256), breaking_change_detection reports breakings but actually it is not:

![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/cfb445aa-aa79-4252-b93b-8ce564ea0f9a)

![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/1c1455ff-4f9f-4658-aa7c-387ef4d09461)

![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/430476e5-ed9d-4962-bcba-b76e0e14e35b)

**Comment by catalinaperalta** [comment]
This is related to: [#35985](https://github.com/Azure/azure-sdk-for-python/issues/35985). 

The tool is not processing overloads today.

**Comment by catalinaperalta** [comment]
@msyyc  this should be fixed with the updated class property detection support in the tool. Let me know if it's resolved so that I can close this issue, thanks!
