### ISSUE TITLE
[Feature Request] Support split step for breaking change detection

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#36070]
Old breaking change tool supports generate `code_report` then output breaking changes, the cmd is like:
```
PS D:\dev\azure-sdk-for-python> python -m packaging_tools.code_report --last-pypi azure-mgmt-cosmosdb
PS D:\dev\azure-sdk-for-python> python -m packaging_tools.code_report azure-mgmt-cosmosdb
PS D:\dev\azure-sdk-for-python> python -m packaging_tools.change_log sdk/cosmos/azure-mgmt-cosmosdb/code_reports/8.0.0b1/report.json sdk/cosmos/azure-mgmt-cosmosdb/code_reports/latest/report.json
```

If we have 2 SDKs generated from swagger and typespec which are not published to pypi, it is convenient to use old tool to detect breaking change between these 2 SDKs.
Now we hope new `breaking_change_detect` could also support similar feature.

**Comment by catalinaperalta** [comment]
Do we need this for breaking change tracking or changelog reporting? 

Technically we do not have breaking changes if a package was not released as stable on pypi.

**Comment by msyyc** [comment]
@catalinaperalta Currently SDK team is working on migration from swagger to typespec, and during the process we must confirm **there is no breakings between SDK generated from swagger and typespec before release**. If any breaking found, we may have to fix the typespec before release. 
Now I have to make some code changes inside your tool to compare SDK between swagger and typespec. It is inefficient since there are many packages in the queue. Appreciate if you could put more priority on this feature request.

**Comment by catalinaperalta** [comment]
I see, ok I will prioritize this item next. I'm currently looking into increasing the flexibility in the suppression mechanism.
