### ISSUE TITLE
Memory leak in ServiceBusClient

### ISSUE THREAD

**Issue by mbenabda** [Azure/azure-sdk-for-python#36090]
- **Package Name**: azure-servicebus
- **Package Version**: 7.11.4
- **Operating System**: Ubuntu 22.04.1
- **Python Version**: 3.12.3

**Describe the bug**
Memory leak in ServiceBusClient

**To Reproduce**
The code below results in a leak of ~750kb/iteration:

```python
import gc
import os
import asyncio
from azure.identity.aio import DefaultAzureCredential
from azure.servicebus.aio import ServiceBusClient, AutoLockRenewer
from azure.servicebus import NEXT_AVAILABLE_SESSION
from azure.servicebus.exceptions import OperationTimeoutError
import logging
logger = logging.getLogger(__name__)

NAMESPACE_FQN = os.environ["SERVICEBUS_NAMESPACE"]
TOPIC_NAME = os.environ["SERVICEBUS_TOPIC_NAME"]
SUBSCRIPTION_NAME = os.environ["SERVICEBUS_SUBSCRIPTION_NAME"]

async def main():
	logging.basicConfig(level=logging.INFO)
	logging.getLogger("azure").setLevel(logging.CRITICAL)

	servicebus_client = ServiceBusClient(
		fully_qualified_namespace = NAMESPACE_FQN,
		credential = DefaultAzureCredential(),
		logging_enable = True,
	)
	async with servicebus_client:
		while True:
			logger.info("opening new receiver")
			receiver = servicebus_client.get_subscription_receiver(
				topic_name=TOPIC_NAME,
				subscription_name=SUBSCRIPTION_NAME,
				auto_lock_renewer = AutoLockRenewer(),
				session_id = NEXT_AVAILABLE_SESSION,
			)
			try:
				async with receiver:
					pass
			except OperationTimeoutError:
				pass
			gc.collect()

asyncio.run(main())
```

**Expected behavior**
No memory leaks.

**Screenshots**
![Screenshot from 2024-06-14 17-42-23](https://github.com/Azure/azure-sdk-for-python/assets/3693756/6307a649-455a-44f9-96a5-9fe4b7b603f7)

**Additional context**
This issue has apparently been present in the client since at least v7.3.1 as per #19777
memray flamegraph of the run: https://jsfiddle.net/v63paxLt/

**Comment by kashifkhan** [comment]
Thank you for the feedback @mbenabda . Ill try and see if I can repro this on my side. The issue you have linked to is when the library was using another amqp library, so it might not be the same case here.

**Comment by mbenabda** [comment]
@kashifkhan thank you for looking into this !

**Comment by kashifkhan** [comment]
Hi @mbenabda,  I just saw that the SDK version is 7.11.4 which was released in Nov 2024. Would be able to upgrade to the latest version from pypi ( 7.12.2 ) and see if this issue still persists.

**Comment by mbenabda** [comment]
@kashifkhan azure-servicebus 7.12.2 seems free of the issue. i'll upgrade on my side. thanks
