### ISSUE TITLE
blank_issues_enabled: false contact_links:   - name: GitHub Community Support     url: https://github.com/orgs/community/discussions     about: Please ask and answer questions here.   - name: GitHub Security Bug Bounty     url: https://bounty.github.com/     about: Please report security vulnerabilities here.

### ISSUE THREAD

**Issue by rosal38** [Azure/azure-sdk-for-python#36101]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.automl.forecasthorizonmode?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-ai-ml/azure.ai.ml.automl.ForecastHorizonMode.yml

### Document Version Independent Id

e67ca541-a0a1-caa1-e1d5-20b6381ae1d9

### Article author

@lmazuel

### Metadata

* ID: 17314f97-83d1-ff27-d453-e3603a667612 
* Service: **machine-learning**

**Comment by kashifkhan** [comment]
Hi @rosal38 , can you please add more information as to what the issue is with that page?
