### ISSUE TITLE
Issue after creating a VM in azure availability zones with the help of python sdk/api call.

### ISSUE THREAD

**Issue by prmjh4** [Azure/azure-sdk-for-python#36129]
I am trying to create a VM in azure availability zones with the help of python sdk/api call.
When I am creating the public ip by making the ip as static and having standard sku in its parameter and then creating the VM by passing all other relevant parameters to the API call then the VM gets created and visible as running on the azure portal under VM section but I am not able to able to access the public ip of the created vm for other operation in the flow of the python script in order to create the remote access which I do by following steps after the VM is created in the same script:

get the IP using Azure python API call. which we get a valid IP in the above case.
do the port check process using the below function where port = 445 and the local_execute function simply creates a subprocess to execute the command using -> p = subprocess.Popen(args, stdout = subprocess.PIPE, stderr = subprocess.PIPE, env = env)
def portAccess(ipAddress, port):
cmd = "nc -z -w 5 " + ipAddress + " " +str(port)
(code, out, err) = local_execute(shlex.split(cmd.encode('ascii')))
print("Port checking on IP address %s and port %s output is: Code: %s, Output: %s, Error: %s" % (ipAddress, port, code, out, err))
return code

This always returns ->Port checking on IP address "ip addr" and port 445 output is: Code: 1, Output: , Error:
And after retry count which I had, we finally are printing the error message as follow if not successfully executed. "Not able to reach IP = %s for VM = %s" % (ipAddress, vmName))"
What is the issue here in the above code please explain this issue is faced in case when zone is used as a availability option and usually not for other normal cases where we either use No Infrastructure redundancy required or availability set as an options.
Please help me clarify this doubt. If I am doing something wrong?

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
@ChenxiJiang333 Please provide help on this issue

**Comment by ChenxiJiang333** [comment]
> @ChenxiJiang333 Please provide help on this issue
got it.

**Comment by ChenxiJiang333** [comment]
Hi @prmjh4, it seems a new created vm uses port 22 to connect, try use port 22 instead of 445.

**Comment by prmjh4** [comment]
Hello @ChenxiJiang333,
Our purpose is to use port 445 specifically when working with windows VM
that is why we want to check and have access to port 445 whereas we make
use of port 22 for Linux vm only.
Are there any other options available?

**Comment by prmjh4** [comment]
1.So does the VM created not have Port 445 open by default? 
2.Even though after adding a new inbound port rule in the network settings, it might not be able to scan by netcat then should we use any other option to check if port is open?

**Comment by ChenxiJiang333** [comment]
> 1.So does the VM created not have Port 445 open by default? 2.Even though after adding a new inbound port rule in the network settings, it might not be able to scan by netcat then should we use any other option to check if port is open?

Mostly created VM does not have Port 445 open unless you choose to open all the ports when you create the vm, otherwise you must create an inbound port rule to allow access to specified ports. Then you need to listen to a port on the vm side(could be done by run command `nc -l -p <port> -v` on vm terminal) before you could scan it on the client side. Or you can follow https://learn.microsoft.com/en-us/azure/virtual-machines/network-security-group-test#test-inbound-connections to test whether the security rules are as expected.

**Comment by prmjh4** [comment]
Since we are creating a fresh VM using the Azure Python SDK and once created we are just simply checking the port access after that in continuation as a next step so we do not have the option to run an service in between on the Port 445 as Even after creating an inbound port rule, a port might not be accessible if there's no service actively listening on it within the VM. so, In that case what would the team suggest to check the port access without running any service on the port 445 on Azure.

**Comment by ChenxiJiang333** [comment]
> Since we are creating a fresh VM using the Azure Python SDK and once created we are just simply checking the port access after that in continuation as a next step so we do not have the option to run an service in between on the Port 445 as Even after creating an inbound port rule, a port might not be accessible if there's no service actively listening on it within the VM. so, In that case what would the team suggest to check the port access without running any service on the port 445 on Azure.

Hi, by following https://learn.microsoft.com/en-us/azure/virtual-machines/network-security-group-test#test-inbound-connections to test inbound connections.

**Comment by prmjh4** [comment]
Thanks @ChenxiJiang333 for the resource that you shared but this shows to do changes from Azure portal. 
Can we perform this same steps using the Azure Python SDKs as well?
Also, If I did these changes then also you mentioned that we need to make that port run any service so that the netcat command can confirm that the port is open. So I want alternate way to check the port access using script where we can overcome this barrier to make the port run a service just to check if that port is open. So any suggestions to check the port access in a simpler way?

**Comment by ChenxiJiang333** [comment]
Hi @prmjh4, to create an security rule, follow: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/network/azure-mgmt-network/generated_samples/network_security_group_rule_create.py#L35.

To make a port open, you can try creating a script for azure vm to run by following https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-run-commands/create-or-update?view=rest-compute-2024-03-01&tabs=Python#create-or-update-a-run-command to add commands like `nc -l -p <port> -v` to start to listen to the port, then follow https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/generated_samples/run_command_examples/virtual_machine_run_command.py to run the script.

**Comment by prmjh4** [comment]
Thanks @ChenxiJiang333 I will try the mentioned solution and revert. Thanks again!

**Comment by ChenxiJiang333** [comment]
> This Port 445 access issue came only in case of VM when created using the Zone as availability options and not in other cases like using No Infrastructure redundancy required or in case of availability set. Can you please investigate why the VM is behaving differently in the case of zone. Apart from this Thanks @ChenxiJiang333 I will try the mentioned solution for VM created with zones and revert.

I have checked new created  vm using no infrastructure redundancy required, it seems their behaviors are just same though...
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/8dfaa72c-0178-4a9e-8093-28a397f349fa)

**Comment by prmjh4** [comment]
Yes but when we do not use the zone option  for all other option the output for the below function which we used to check the access of the port using script comes as follow:
def portAccess(ipAddress, port):
cmd = "nc -z -w 5 " + ipAddress + " " +str(port)
(code, out, err) = local_execute(shlex.split(cmd.encode('ascii')))
print("Port checking on IP address %s and port %s output is: Code: %s, Output: %s, Error: %s" % (ipAddress, port, code, out, err))
return code
Output:
06/13/2024 08:02:34 AM  DEBUG: 18980:140347970209600: log.py:28: Port checking on IP address 1.111.111.111 and port 445 output is: Code: 1, Output: , Error:
06/13/2024 08:02:59 AM  DEBUG: 18980:140347970209600: log.py:28: Port checking on IP address 1.111.111.111 and port 445 output is: Code: 1, Output: , Error:
06/13/2024 08:03:24 AM  DEBUG: 18980:140347970209600: log.py:28: Port checking on IP address 1.111.111.111 and port 445 output is: Code: 1, Output: , Error:
06/13/2024 08:03:49 AM  DEBUG: 18980:140347970209600: log.py:28: Port checking on IP address 1.111.111.111 and port 445 output is: Code: 1, Output: , Error:
06/13/2024 08:04:14 AM  DEBUG: 18980:140347970209600: log.py:28: Port checking on IP address 1.111.111.111 and port 445 output is: Code: 0, Output: , Error:
where output with Code: 1, comes multiple times then it gives the Code: 0 and returns back to main caller.
where 1.111.111.111 is a dummy IP.
What could be the reason behind this behavior of Azure Windows VM created.

**Comment by prmjh4** [comment]
Hello @ChenxiJiang333 
I used the same script for the Linux machine as well where port 22 is open by default and we are also using port 22 for Linux machine to check the port access using the function with port 22.
But when I created the VM without zone then the script passed and completed successfully after checking the port 22 on access it using the same port access function mentioned above.
but when created the VM using zone then it also got stuck like the windows VM and exit with the error message.

**Comment by prmjh4** [comment]
So as per my observations, I think that VM created with the help of zone as an availability options, the Public IP that gets created is a static public IP with Standard SKU and in other general cases the Public IP is dynamic. which might not allow the access to any port unless explicitly passed by using NSG with necessary inbound rules created inside it and in rest other cases the IP usually gets access to the port when checked.
What are your views on it? Please share. Thanks!

**Comment by ChenxiJiang333** [comment]
> So as per my observations, I think that VM created with the help of zone as an availability options, the Public IP that gets created is a static public IP with Standard SKU and in other general cases the Public IP is dynamic. which might not allow the access to any port unless explicitly passed by using NSG with necessary inbound rules created inside it and in rest other cases the IP usually gets access to the port when checked. What are your views on it? Please share. Thanks!

Hi, I created a vm with zones and without any NSG settings. 
The first moment I tried to connect the port, it had failed as well, yet just after waiting for a while, the NSG would be auto created and associated (which can be seen on portal), then the connection would be succeeded. 
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/43e4eb27-3814-47d0-83f7-9706a3da7d3d)

So, I guess the error was just because the vm was not fully configured may you need to wait for a while. The behavior does not really change by whether you use the Zone or not.

**Comment by prmjh4** [comment]
Hello @ChenxiJiang333 Did you tried to create the VM directly from the Azure console? As It by default creates a new NSG group that gets attached to it when we create a new VM using Azure GUI console.
But we are using azure python SDKs where we are not attaching any NSG to the VM, we just simply attach NIC to it and we ahead with the mandatory parameters creations that are required to create the VM.
So, In the case, we might need to create a NSG in our script as well as a must step to make sure that we have access to the desired ports which we require?

**Comment by ChenxiJiang333** [comment]
> Hello @ChenxiJiang333 Did you tried to create the VM directly from the Azure console? As It by default creates a new NSG group that gets attached to it when we create a new VM using Azure GUI console. But we are using azure python SDKs where we are not attaching any NSG to the VM, we just simply attach NIC to it and we ahead with the mandatory parameters creations that are required to create the VM. So, In the case, we might need to create a NSG in our script as well as a must step to make sure that we have access to the desired ports which we require?

Just used python SDK and attached the NIC only following [sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/generated_samples/virtual_machine_examples/virtual_machine_create_from_acommunity_gallery_image.py), then I found it on portal that a NSG still created and associated a few whiles after a VM created. And I guess no NSG means no security rules, which means all ports should be free to access, so the error is not because of the lack of NSG, but the VM & NSG's not fully configured.

**Comment by prmjh4** [comment]
1.As far as I followed the Azure documentation, I understood that without attaching any NSG (either at the VM's NIC level or subnet level), the VM will have all inbound traffic blocked by Azure's default security policies.
2.I again created the VM using Python SDK and attached the NIC by creating a fresh one that does not have any NSG attached to it and also created the fresh subnet and attached to the VM which also does not have any NSG attached to it. Then finally the VM created and I fired the netcat command and as expected we were not able to access any port.
As suggested, I waited for a while around 10 minutes and then again tried firing the same netcat command and it again errored out with same error message and no NSG got attached to it as we did not passed to it during VM creation using Python SDKs.
I think if we do not pass the NSG to the NIC or subnet while creating a VM then there is no point of an NSG getting fully configured with the VM.
And If there is some kind of behavior like this then it is not an expected behavior and must not be there. Although, I did not faced any such behavior.

**Comment by prmjh4** [comment]
Hello @ChenxiJiang333 
Most of the cases we are try to run the script to create and then check the port access status of the VM created from a vCenter created VM which has been assigned with an Internal IP Address: This is a private IP address used within a virtual network created and managed by vCenter. And then it creates the VM successfully but is not able to check the port status with the above nc command. Is there any restrictions?

**Comment by ChenxiJiang333** [comment]
> 1.As far as I followed the Azure documentation, I understood that without attaching any NSG (either at the VM's NIC level or subnet level), the VM will have all inbound traffic blocked by Azure's default security policies. 2.I again created the VM using Python SDK and attached the NIC by creating a fresh one that does not have any NSG attached to it and also created the fresh subnet and attached to the VM which also does not have any NSG attached to it. Then finally the VM created and I fired the netcat command and as expected we were not able to access any port. As suggested, I waited for a while around 10 minutes and then again tried firing the same netcat command and it again errored out with same error message and no NSG got attached to it as we did not passed to it during VM creation using Python SDKs. I think if we do not pass the NSG to the NIC or subnet while creating a VM then there is no point of an NSG getting fully configured with the VM. And If there is some kind of behavior like this then it is not an expected behavior and must not be there. Although, I did not faced any such behavior.

@prmjh4
Such behavior does happen when run the script with python sdk commands. Have you associated a public ip with the network interface and set it as the primary ip config?
Here's my script to create a configured network interface.
```
def main():
    client = NetworkManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id="sub",
    )

    response = client.virtual_networks.begin_create_or_update(
        resource_group_name="rg",
        virtual_network_name="test-vnet",
        parameters={
            "location": "westus2",
            "properties": {"addressSpace": {"addressPrefixes": ["10.0.0.0/16"]}, "flowTimeoutInMinutes": 10},
        },
    ).result()

    response = client.subnets.begin_create_or_update(
        resource_group_name="rg",
        virtual_network_name="test-vnet",
        subnet_name="default",
        subnet_parameters={"properties": {"addressPrefix": "10.0.0.0/16"}},
    ).result()

    response = client.public_ip_addresses.begin_create_or_update(
        resource_group_name="rg",
        public_ip_address_name="test-ip",
        parameters={
            "location": "westus2",
            "properties": {
                "idleTimeoutInMinutes": 10,
                "publicIPAddressVersion": "IPv4",
                "publicIPAllocationMethod": "Dynamic",
            },
            "sku": {"name": "Basic"},
        },
    ).result()

    response = client.network_interfaces.begin_create_or_update(
        resource_group_name="rg",
        network_interface_name="test-nic",
        parameters={
            "location": "westus2",
            "properties": {
                "enableAcceleratedNetworking": True,
                "ipConfigurations": [
                    {
                        "name": "ipconfig1",
                        "properties": {
                            "publicIPAddress": {
                                "id": "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.Network/publicIPAddresses/test-ip"
                            },
                            "subnet": {
                                "id": "/subscriptions/sub/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/test-vnet/subnets/default"
                            },
                            "primary": True
                        },
                    },
                ],
            },
        },
    ).result()
```

**Comment by prmjh4** [comment]
Yes, I associated a public ip with the network interface and set it as the primary ip config.

**Comment by ChenxiJiang333** [comment]
> Yes, I associated a public ip with the network interface and set it as the primary ip config.

Well, not sure about the portal behavior, if with the above script you still didn't see a NSG created, just to pass a NSG to the NIC might solve the problem: https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-interfaces/create-or-update?view=rest-virtualnetwork-2023-11-01&tabs=HTTP#networksecuritygroup. About the cause of VM behavior difference in availability zones, since we're not the domain expert, to open an issue at https://github.com/Azure/azure-rest-api-specs/issues might be more helpful.

For issue about not able to connect a vcenter managed VM, did you mean you want to connect to a VM that only have an internal IP? I'm not sure whether there could be a method that can be used to directly connect a device assigned an Internal IP from outside. A VM should have a public IP or it must forward its port if you want to connect it from your local device.

**Comment by prmjh4** [comment]
No, the above script helps us connect the NSG to the NIC somehow Port 445 access is not given instantaneously and thus I am thinking to add a sleep timer for 2-4 minutes so that changes are updated and then I can check if it works or not and will update you once.

**Comment by ChenxiJiang333** [comment]
> instantaneously

For port 445, you may need to additionally add an inbound rule.

**Comment by prmjh4** [comment]
Hello Team, I am sorry for the delayed response. My issue got resolved after creating the necessary NSG for the created VM and attaching it with the NIC. Then I added a sleep timer of 3 minutes so that it gets properly  linked to the VM as advised. After that I did my operations which were successfully completed. Thanks Team for the support that you provided. Thanks a lot!
