### ISSUE TITLE
[Feature Request] allow breaking changes for MGMT SDK

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#36152]
When I want to use `detect_breaking_changes` locally for MGMT SDK, I have to annotate the skip logic as following which is inconvenient:
https://github.com/Azure/azure-sdk-for-python/blob/20e6f288aa94a712d1f9a9fd6f8adef3da15b4fe/scripts/breaking_changes_checker/detect_breaking_changes.py#L399-L402
So I make PR https://github.com/Azure/azure-sdk-for-python/pull/36051 to allow breakings detection for all MGMT SDK. However, it seems that the breaking detection tool is adopted in release pipeline:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3877372&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=090c7790-4f5a-56e9-60dd-0909d5f779fb
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/1cbe5f68-0cc1-48a2-963b-9c16c1c84019)

To unblock release, I have to revert it in https://github.com/Azure/azure-sdk-for-python/pull/36104. 

I notice https://github.com/Azure/azure-sdk-for-python/blob/20e6f288aa94a712d1f9a9fd6f8adef3da15b4fe/scripts/breaking_changes_checker/README.md#ignore-a-reported-breaking-change declares how to suppress breakings but it needs add it package by package and item by item which cost much effort. I hope it could also support regex like `RUN_BREAKING_CHANGES_PACKAGES` so that we could suppress breaking warning for all languages. 
In one word, I hope to use the tool to show breakings but don't hope it reports error in release pipeline.

**Comment by catalinaperalta** [comment]
This is a repeat of [#35988](https://github.com/Azure/azure-sdk-for-python/issues/35988) will track this change there. Currently working on enabling this.
