### ISSUE TITLE
Azure AI Search - SearchClient obtained from SearchIndexClient.get_search_client() should inherit API key setting

### ISSUE THREAD

**Issue by acwwat** [Azure/azure-sdk-for-python#36168]
- **Package Name**: azure-search-documents
- **Package Version**: 11.4.0
- **Operating System**: Microsoft Windows 11 Pro 10.0.22631 Build 22631
- **Python Version**: 3.12.3

**Describe the bug**

The [`SearchIndexClient` class](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-search-documents/11.4.0/azure.search.documents.indexes.aio.html#azure.search.documents.indexes.aio.SearchIndexClient) has a `get_search_client` function that returns a client to perform operations on Azure AI Search. The returned [`SearchClient` instance](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-search-documents/11.4.0/azure.search.documents.html#azure.search.documents.SearchClient) does not inherit the `api_version` setting from the `SearchIndexClient` instance, so it would be using the default API version instead. While it can be passed into `get_search_client()` manually, the setting should be inherited for consistency.

**To Reproduce**
1. Construct a `SearchIndexClient` instance with the `api_key` argument provided (for example, set it to `2024-03-01-preview`).
2. Call `get_search_client()` on the `SearchIndexClient` instance to get a `SearchClient` instance.
3. Observe that the class has `api_key` set to the default API version, which is currently `2023-11-01`. The same can be observed when making any API requests and observing the HTTP client debug logs.

**Expected behavior**
The `SearchClient` that is instantiated from `SearchIndexClient.get_search_client()` should have the `api_key` set to the same value as the `SearchIndexClient` instance.

**Screenshots**
n/a

**Additional context**
I found this issue while developing with the LlamaIndex [Azure AI Search module](https://docs.llamaindex.ai/en/stable/examples/vector_stores/AzureAISearchIndexDemo/), specifically the [`AzureAISearchVectorStore` class](https://docs.llamaindex.ai/en/v0.9.48/api/llama_index.vector_stores.AzureAISearchVectorStore.html).

**Comment by xiangyan99** [comment]
Thank you for the feedback.

Yes. This makes total sense.
