### ISSUE TITLE
Whether it is possible to parallel processing in "upload_blob" and "download_blob" function in Python.

### ISSUE THREAD

**Issue by ogu11111** [Azure/azure-sdk-for-python#36170]
As title, I would like to know if parallel processing is possible with "upload_blob" and "download_blob" function in Python.
And, if that is possible in Python, I would also like to know samples, if possible.

-  upload_blob
https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-upload-blob
-  download_blob
https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-download-blob
 
According to the MS document below, I think uploading in parallel can be done in "C#" by using "UploadAsync" function.
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-scalable-app-upload-files
 
Thanks.

**Comment by jalauzon-msft** [comment]
Hi @ogu11111, yes both `upload_blob` and `download_blob` take an optional keyword called `max_concurrency` which controls how many parallel threads will be used to upload/download the blob. If not specified, it defaults to 1. The SDK will break the Blob into chunks (4 MiB by default but configurable) and then use up to `max_concrrecny` threads to upload/download the chunks in parallel. 

You can have a look at [this doc on performance tuning](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-tune-upload-download-python) for more information about it and other useful parameters that can be tuned. Thanks.
