### ISSUE TITLE
Copying blob within account with BlobClient.upload_blob_from_url fails with ErrorCode:CannotVerifyCopySource

### ISSUE THREAD

**Issue by Lincoln-GR** [Azure/azure-sdk-for-python#36176]
- **Package Name**: azure.storage.blob
- **Package Version**: 12.11.0
- **Operating System**: Linux
- **Python Version**: 3.8

**Describe the bug**
Coping blob within account, but to different container, with upload_blob_from_url fails with ErrorCode:CannotVerifyCopySource.

The docs here https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-upload-blob-from-url say

> If the source is in another account, the source must either be public or must be authenticated via a shared access signature. If the source is public, no authentication is required

Which seems to imply that copying a blob within the same account requires no authentication for the source blob? am I wrong?

**To Reproduce**
Anonymized code:
```python
blob_service_client = BlobServiceClient.from_connection_string(
    'DefaultEndpointsProtocol=https;AccountName=my-account;AccountKey=key;EndpointSuffix=core.windows.net'
)
dest_blob_client = blob_service_client.get_blob_client(
    container="destination-container", blob="destination_blob.txt"
)
content_settings = ContentSettings(
    content_disposition='attachment; filename="example.txt"',
)
dest_blob_client.upload_blob_from_url(
    source_url="https://my-account.blob.core.windows.net/source-container/source_blob.txt",
    include_source_blob_properties=False,
    overwrite=True,
    content_settings=content_settings,
)
````

**Expected behavior**
Blob is copied to new Blob

**Actual error**
```txt
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://my-account.blob.core.windows.net/destination-container/destination_blob.txt'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '0'
    'x-ms-blob-content-disposition': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'x-ms-copy-source': 'REDACTED'
    'x-ms-copy-source-blob-properties': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.11.0 Python/3.8.17 (Linux-5.15.0-1064-azure-x86_64-with-glibc2.2.5)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '<removed>'
    'Authorization': 'REDACTED'
No body was attached to the request
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 401
Response headers:
    'Content-Length': '297'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '<removed>'
    'x-ms-client-request-id': '<removed>'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Thu, 20 Jun 2024 08:08:28 GMT'

Traceback (most recent call last):
  <redacted>
  File "/usr/local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 570, in upload_blob_from_url
    process_storage_error(error)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 568, in upload_blob_from_url
    return self._client.block_blob.put_blob_from_url(**options)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 491, in put_blob_from_url
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/usr/local/lib/python3.8/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId: '<removed>
Time:2024-06-20T08:08:28.5480836Z
ErrorCode:CannotVerifyCopySource
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:'<removed>
Time:2024-06-20T08:08:28.5480836Z</Message></Error>
```

**Comment by weirongw23-msft** [comment]
Hi @Lincoln-GR Lincoln, we were able to get a successful repro of your issue. After taking a look at the [service documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url?tabs=microsoft-entra-id) for `x-ms-copy-source:name`,

> The source blob must either be public or be authorized via a shared access signature.

and some further testing on the behavior of `upload_blob_from_url`, require a SAS even if the source blob is on the same account as the destination blob. We recognize the existing documentation doesn't match this behavior, so we will be sure to update it 😄 

To use `upload_blob_from_url`, you will need to generate a SAS that has read access to the source blob to the end of your source URL. You can use [generate_blob_sas](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python#azure-storage-blob-generate-blob-sas) to build a SAS if needed.

As a workaround, try using `start_copy_from_url` ([docs](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-start-copy-from-url)):

```python
dest_blob_client.start_copy_from_url(
    source_url="https://my-account.blob.core.windows.net/source-container/source_blob.txt",
)
```

Note that `start_copy_from_url` may sometimes be async for larger blobs and therefore could be slower.

**Comment by Lincoln-GR** [comment]
@weirongw23-msft Thanks for your response. Using a SAS token has worked for me.
