### ISSUE TITLE
Document Intelligence: support for multiple language at the same time during extraction

### ISSUE THREAD

**Issue by galvangoh** [Azure/azure-sdk-for-python#36173]
- **Package Name**: azure-ai-documentintelligence
- **Package Version**: 1.0.0b2
- **Operating System**: Windows
- **Python Version**: 3.10.9

Hello all, there are certain prebuilt models that are utilizes an OCR engines to retrieve text from the document. I am currently in the testing phase of my project using the prebuilt invoice model.

I am interested to know:
1. If there are/will be multilingual support for those models?
2. Does being explicit with the `locale` parameter (e.g. specifically tell the model that the document contents are in mandarin) of `DocumentIntelligenceClient.begin_classify_document` improve OCR performance?
3. Before performing OCR on the documents submitted, are there any image preprocessing happening behind the scenes? So that OCR performance can be improved?

Thank you.

**Comment by bojunehsu** [comment]
1. Yes, many of our models support multiple locales/languages.  Please see [here](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/language-support-prebuilt?view=doc-intel-4.0.0&tabs=languages%2Cthermal#invoice) for a list of locales supported by prebuilt invoice.
2. Being explicit with locale may help in situations where the text is highly confusable and we are absolutely certain that the document only contains content in the specified locale.  In the vast majority of cases, specifying locale will not make a difference.
3. The OCR model is fairly robust.  However, if there are specific image preprocessing in your scenario that would help human better understand the text, the model will likely benefit from those as well.
