### ISSUE TITLE
ManagedIdentityCredential failing with  version 1.17.0

### ISSUE THREAD

**Issue by ben05allen** [Azure/azure-sdk-for-python#36184]
- azure-identity
- 1.17.0
- Docker image: python:3.12-slim-bookworm
- running in an Azure Container Instance

**Describe the bug**
Authentication with Managed Identity failing since upgrading from 1.16.0 to 1.17.0

Error Trace
```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
	ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8"
	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
	AzureCliCredential: Azure CLI not found on path
	AzurePowerShellCredential: PowerShell is not installed
	AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**Remediation**
Authentication is successful after rolling back to 1.16.0

**Comment by kingsleyadam** [comment]
I can also confirm, we're having the same issues running in an Azure Container Instance. Rolling back to 1.16.1 seems to work without issues.

```
ManagedIdentityCredential: Unexpected content type "text/plain; charset=utf-8"
```

**Comment by xiangyan99** [comment]
Thanks for the feedback.

Could you help to check if this only repros when you use it in DefaultAzureCredential?

Does it also repro if you use ManagedIdentityCredential directly?

Thanks.

**Comment by nicholascm** [comment]
I have this same issue. Currently working around  on ACI by using ManagedIdentityCredential directly.

**Comment by ben05allen** [comment]
> ManagedIdentityCredential

Does not repro when using ManagedIdentityCredential

**Comment by xiangyan99** [comment]
Azure-identity 1.17.1 with the fix has shipped. Please let us know if it does not work.

https://pypi.org/project/azure-identity/1.17.1/
