### ISSUE TITLE
Effective Identity with Service Principal in Python

### ISSUE THREAD

**Issue by Karthik-Indium** [Azure/azure-sdk-for-python#36194]
### Type of issue

Missing information

### Description

I would like to use effective identity with Service Principal for Power BI embedded solution in Python. Its not clear how to set this up. 

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/power-bi?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/power-bi.md

### Document Version Independent Id

fff79500-7d5f-6c4a-aab0-684b8a6b90e2

### Article author

@azure-sdk

### Metadata

* ID: b5109ef0-5dd6-309f-3e04-7d492e9a8020 
* Service: **powerbi**

**Comment by lmazuel** [comment]
Hi @Karthik-Indium 

Working on your issue, we realized that to answer your question, we need to reship a new version of that SDK first, since it's still using a legacy auth system and we would want you to use a new one. I asked @msyyc to schedule that work.

Thanks!

**Comment by msyyc** [comment]
I see and will release a new version ASAP.

**Comment by msyyc** [comment]
@Karthik-Indium Please have a try for latest version : https://pypi.org/project/azure-mgmt-powerbiembedded/3.0.0/

**Comment by Karthik-Indium** [comment]
Thank you. I will have my team to check this out.

Best Regards,
Karthik
