### ISSUE TITLE
Documentation of the previous version of Python SDK is not visible/accessible for  

### ISSUE THREAD

**Issue by sagarkeswani** [Azure/azure-sdk-for-python#36191]
### Type of issue

Missing information

### Description

We have released a new version of the API and its Python SDK documentation is visible. But the documentation of the previous version is not visible. 

When I try to change the version to the legacy from the drop down, I keep getting redirected to the latest version. 

How can we access the older version documentation? 

Relevant link for the workloads Python SDK:  https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-workloadssapvirtualinstance-readme?view=azure-python-preview

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-mgmt-workloadssapvirtualinstance/azure.mgmt.workloadssapvirtualinstance.workloadssapvirtualinstancemgmtclient?view=azure-python-preview&viewFallbackFrom=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/preview/docs-ref-autogen/azure-mgmt-workloadssapvirtualinstance/azure.mgmt.workloadssapvirtualinstance.WorkloadsSapVirtualInstanceMgmtClient.yml

### Document Version Independent Id

f1d7607d-f703-67b0-7537-718f5ab04036

### Article author

@VSC-Service-Account

### Metadata

* ID: a5d78979-4447-141b-3fe5-cb5382e0ef12

**Comment by xiangyan99** [comment]
Thanks for the feedback.

@scbedd @ronniegeraghty is this by design?

**Comment by ronniegeraghty** [comment]
Hi @sagarkeswani, 
In the Learn docs "Legacy" does not refer to previous versions of the libraries but instead refers to track 1 library, which are Azure service libraries that were release before the Azure SDK was unified and the services made they own libraries fully independently. These will often be different packages that covered the same service. The Latest option will show the docs for the latest stable version of track 2 libraries which are libraries in the unified Azure SDK like the one you released. 

cc @kyle-patterson for SDK Docs awareness

**Comment by rohit-ganguly** [comment]
Hi @sagarkeswani, we also have specific versioned reference docs available at https://azure.github.io/azure-sdk-for-python/. Our Microsoft Learn reference documentation will either:

- Latest version
- Latest preview version
- Legacy (Track 1, likely deprecated)
