### ISSUE TITLE
Is there no way to stream or wait for environment creation with ml_client

### ISSUE THREAD

**Issue by obiii** [Azure/azure-sdk-for-python#36218]
- **Package Name**: azure.ai.ml.entities
- **Package Version**: V2
- **Operating System**: Linux Ubuntu 20.04
- **Python Version**: 31.11

**Describe the bug**
We are creating aml environments within the aml pipeline before actually submitting the job. We cannot find a way to wait for the environment creation to finish. Like with jobs, there is no stream functionality with environments.

**To Reproduce**

```
ml_client_workspace = get_client_workspace(
    credentials, e.subscription_id, e.resource_group, e.workspace_name
)

gpu_image = "mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04"
cpu_image = "mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04"
env_docker_conda = Environment(
    image=gpu_image if gpu_accelerated else cpu_image,
    conda_file=conda_dependencies_file,
    name=env_name,
    description="Environment created from a Docker image plus Conda environment.",
)
env = ml_client.environments.create_or_update(env_docker_conda)

```
**Expected behavior**
There should be a way to wait for environment creation and get completion/failure status.

**Comment by kristapratico** [comment]
@obiii thanks for your feedback, @azureml-github will take a look and get back to you as soon as possible.

**Comment by diondrapeck** [comment]
@obiii There is no support for this in V2 today. It is a known feature ask in our backlog; however, there are not concrete plans to address it. If that changes, we will update this issue.
