### ISSUE TITLE
SyntaxWarning: invalid escape sequence - azure-mgmt-network

### ISSUE THREAD

**Issue by shekhawatajit** [Azure/azure-sdk-for-python#36232]
- **azure-mgmt-network**: 
- **25.4.0**: 
- **alpine-3 docker image**:
- **3.12**: 

**Describe the bug**
We are using docker images in K8s cluster. During startup the k8s-worker throws these warnings:

    python -m k8s_worker.app
    /venv/lib/python3.12/site-packages/azure/mgmt/network/models/_models.py:36691: SyntaxWarning: invalid escape sequence '\ '
      """The network security perimeter link resource.
    /venv/lib/python3.12/site-packages/azure/mgmt/network/models/_models.py:36785: SyntaxWarning: invalid escape sequence '\ '
      """                                             
    /venv/lib/python3.12/site-packages/azure/mgmt/network/models/_models.py:36844: SyntaxWarning: invalid escape sequence '\ '
      """The network security perimeter linkReference resource.
    /venv/lib/python3.12/site-packages/azure/mgmt/network/models/_models.py:36930: SyntaxWarning: invalid escape sequence '\ '
      """

**Comment by ChenxiJiang333** [comment]
related issue with https://github.com/Azure/azure-sdk-for-python/issues/36233

**Comment by giotab** [comment]
@msyyc @ChenxiJiang333 can we get feedback also about this, similar to https://github.com/Azure/azure-sdk-for-python/issues/36233 ?
Thank you in advance!

**Comment by msyyc** [comment]
SDK team plan to release a new version by the end of this month

**Comment by MartinCura** [comment]
This is surely a warning since Python 3.12.
