### ISSUE TITLE
yntaxWarning: invalid escape sequence - azure-mgmt-keyvault

### ISSUE THREAD

**Issue by shekhawatajit** [Azure/azure-sdk-for-python#36233]
- **azure-mgmt-keyvault**: 
- **10.3.0**: 
- **alpine-3 docker image**:
- **3.12*: 

**Describe the bug**
We are using docker images in K8s cluster. During startup the k8s-worker throws these warnings:

    /venv/lib/python3.12/site-packages/azure/mgmt/keyvault/v2023_07_01/models/_models_py3.py:4343: SyntaxWarning: invalid escape sequence '\ '
      """Properties of the vault.
    /venv/lib/python3.12/site-packages/azure/mgmt/keyvault/v2023_07_01/models/_models_py3.py:4462: SyntaxWarning: invalid escape sequence '\ '
      """

**Comment by msyyc** [comment]
similar issue with https://github.com/Azure/autorest.python/issues/2551 and is fixed after https://github.com/Azure/autorest.python/blob/main/packages/autorest.python/CHANGELOG.md#2024-04-30---61316. We will release a new package version after upgrade autorest.python

**Comment by giotab** [comment]
Hi @msyyc ,

Any ETA for this?

Thank you in advance

**Comment by msyyc** [comment]
@ChenxiJiang333 Let's release a new version for `azure-mgmt-keyvault`

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
Hi @shekhawatajit, @giotab, a fix version of sdk has been released.
