### ISSUE TITLE
Using Azure SDK for Python to run Workflows in Azure Purview

### ISSUE THREAD

**Issue by RicSpd** [Azure/azure-sdk-for-python#36234]
- **Package Version**: 
  - requests==2.31.0
  - azure-common==1.1.28 
  - azure-core==1.30.1 
  - azure-cosmos==4.3.1 
  - azure-identity==1.17.1 
  - azure-purview-workflow==1.0.0b2 
  - azure-storage-blob==12.19.1 
  - azure-storage-file-datalake==12.14.0
- **Python Version**: 3.11

**Describe the bug**
We are working inside Azure Databricks. We are trying to use Azure SDK for Python (previously we tried to use Purview REST APIs as can be seen [here](https://stackoverflow.com/questions/78663537/using-rest-api-in-python-to-run-workflows-in-azure-purview)) to make a user request that should be able to trigger a Purview workflow run. The workflow should trigger whenever the user is trying to update an asset, for example its `userDescription`.

**To Reproduce**
We tried the following code:
```
from azure.identity import ClientSecretCredential
from azure.purview.workflow import PurviewWorkflowClient

client_id = 'XXX'
client_secret = 'YYY'
tenant_id = 'ZZZ'
purview_endpoint = "https://ABCDE.purview.azure.com"

def get_credentials():
     credentials = ClientSecretCredential(client_id=client_id, client_secret=client_secret, tenant_id=tenant_id)
     return credentials
 
credentials = get_credentials()
client = PurviewWorkflowClient(endpoint=purview_endpoint, credential=credentials)

json_payload = {
    "operations": [
        {
            "type": "UpdateAsset",
            "payload": {
                "entities":
                    {
                        "typeName": "azure_sql_table",
                        "attributes": {
                            "guid": "f00553c6-7a45-479f-b2fe-f9f6f6f60000",
                            "userDescription": "New description from ADB with workflow API",
                            "qualifiedName": "mssql://ABCDE.database.windows.net/.../dbo/...",
                            "name": "RichiesteOffertaBandite",
                            "description": "Description from ADB with workflow API"
                        }
                    }
            }
        }
    ],
    "comment": "please work"
}

response = client.user_requests.submit(
        user_requests_payload = json_payload,
        content_type = 'application/json'
)
```

We are getting the following error:
```
{'error': {'requestId': '3ea14555-aa4c-48e7-b1b6-1d683f39515b',
  'code': 'Workflow.DataCatalogError.InvalidJsonRequestPayload',
  'message': "Invalid Json request payload: '.entities(missing)'"}}
```

We do not understand what is missing inside "entities". The documentation ([link](https://learn.microsoft.com/en-us/python/api/azure-purview-workflow/azure.purview.workflow.operations.userrequestsoperations?view=azure-python-preview) and [link](https://learn.microsoft.com/en-us/rest/api/purview/workflowdataplane/user-requests/submit?view=rest-purview-workflowdataplane-2023-10-01-preview&tabs=HTTP#userrequestpayload)) is really not clear on what a user request payload should contain, and we think we have inserted the `typeName` and `attributes` correctly.
Any suggestions?

**Comment by kristapratico** [comment]
@RicSpd thanks for your feedback, we'll take a look and get back to you as soon a possible. cc @yifan-zhou922

**Comment by RicSpd** [comment]
After a brief session with Microsoft Purview support team, we managed to find the solution: it's necessary to have a second `entities` entry inside the first `entities` entry, and this second entry must be a list of dicts.  
Furthermore, the `guid` parameter must be outside the `attributes` dictionary in order for the workflow request to show changes correctly inside Purview.

```
json_payload = {
    "operations": [
        {
            "type": "UpdateAsset",
            "payload": {
                "entities": {
                    "entities": [
                        {
                            "guid": "f00553c6-7a45-479f-b2fe-f9f6f6f60000",
                            "typeName": "azure_sql_table",
                            "attributes": {
                                "userDescription": "New description from ADB via workflow API",
                                "qualifiedName": "mssql://XXXXX.database.windows.net/XXXXX/dbo/YYYYY",
                                "name": "YYYYY",
                                "description": "Description field from ADB via workflow API"
                            }
                        }
                    ]
                }
            }
        }
    ],
    "comment": "Thanks!"
}
```

**Comment by kristapratico** [comment]
Thank you for posting the solution!
