### ISSUE TITLE
Cosmos DB Sample Issue

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-sdk-for-python#36278]
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/examples.py#L122)

![image](https://github.com/Azure/azure-sdk-for-python/assets/139106314/aae90746-a37f-4801-84aa-93ba81ed1610)

**Reason:**
TypeError: Session.request() got an unexpected keyword argument 'priority_level'.

**Suggestion:**
Update code to `priority`.

@rohit-ganguly , @lmazuel , @kyle-patterson , @KrzysztofCwalina , @annatisch  for notification.

**Comment by simorenoh** [comment]
PR has been merged, thanks @jerryshia for catching this!
