### ISSUE TITLE
[Service Bus] Improve use of the SDK in Azure Functions

### ISSUE THREAD

**Issue by ntaylor-ads** [Azure/azure-sdk-for-python#36305]
**Is your feature request related to a problem? Please describe.**
Examples of how to use the ServiceBus sdk have the following pattern:
```python
# Creates serviceBusClient
with servicebus_client:
    # Creates a queueSender
    with sender:
        # Sends a message!
```
Under this pattern a new connection is established at each invocation of the code. 

This pattern does not work well in Azure Functions for two main reasons:

1. Functions are often designed to be fairly lightweight. Establishing a connection on each function invocation introduces serious overhead relative to the usual duration of the invocation, potentially causing throughput and/or cost issues. This pattern is simply too heavyweight for microservices.
2. Function instances have a connection limit. In fact, [the Azure Function documentation explicitly preclude the above pattern](https://learn.microsoft.com/en-us/azure/azure-functions/manage-connections?tabs=csharp#:~:text=Application%20Insights.-,Static%20clients,a%20shared%20helper%20class%20if%20different%20functions%20use%20the%20same%20service.,-Client%20code%20examples), instead recommending singleton clients that persist for the duration of the function instance.

**Describe the solution you'd like**
I would like a good way to use the Azure ServiceBus SDK for python in Azure Functions. If such a way already exists, I would like the pattern to be included in the examples and documentation.

**Describe alternatives you've considered**
I have tried implementing a singleton pattern as suggested by the Functions documentation, where a single client is lazily created and then persisted for the lifetime of the function invocation, with new senders and receivers being spawned off of it as needed.

However, in a sync Function the invocations are run in a threadpool and this library is not thread-safe. In an async Function the client would be shared across coroutines and [this library is also not coroutine safe](https://github.com/Azure/azure-sdk-for-python/issues/35618#:~:text=As%20you%20know%20the%20library%20currently%20is%20not%20coroutine%20safe%2C%20so%20our%20recommendation%20to%20users%20is%20to%20use%20a%20lock%20when%20accessing%20the%20producer%20like%20in%20your%20repro)?! So it appears there is no simple way of implementing the singleton pattern. Practically speaking, my attempts lead to AMQP socket timeout exceptions being thrown after 10-20 minutes.

Obviously, Azure Functions offers trigger and output bindings for the service bus, but these are not feature complete and there are many reasons why in practice one might need access to the actual service bus client.

**Additional context**
This request seems very related to #33608 (and I stole the pattern code from there). But I decided to open a separate issue to highlight the incompatibility of this library with Azure Functions and/or to find out the intended usage therein.

**Comment by swathipil** [comment]
Hi @ntaylor-ads - We do not maintain Azure Functions, so we cannot add any samples specifically for usage with Functions. As you mentioned the azure-servicebus library is not thread-safe, so if you want to use the singleton pattern, you will need to use a lock around the client.

If you would like to request features for the Functions output bindings/triggers, please create an issue in the Functions repo: https://github.com/Azure/azure-functions-python-library
