### ISSUE TITLE
Service bus: Message to a partitioned entity with duplicate detection enabled must have either PartitionKey or MessageId

### ISSUE THREAD

**Issue by bertek41** [Azure/azure-sdk-for-python#36333]
This issue is already opened https://github.com/Azure/azure-sdk-for-python/issues/21955
but it was closed and issue still persist

**Comment by kashifkhan** [comment]
Thank you for the feedback @bertek41 . Im checking with the service team and will get back to you as I hear from them

**Comment by bertek41** [comment]
Hello, I would like to know if there is any development on this issue?

**Comment by kashifkhan** [comment]
sorry about the delay @bertek41. I was able to confirm that this is not implemented by the service, with the recommendation being not to use batching if deduplication is needed on a partitioned entity.

**Comment by bertek41** [comment]
> sorry about the delay @bertek41. I was able to confirm that this is not implemented by the service, with the recommendation being not to use batching if deduplication is needed on a partitioned entity.

Got it. Thank you for the explanation.
