### ISSUE TITLE
Exporters fail when global tracer provider isn't set.

### ISSUE THREAD

**Issue by avramdj** [Azure/azure-sdk-for-python#36362]
https://github.com/Azure/azure-sdk-for-python/blob/8b6e24d0f3b5ca9ed1d0c5f7229c2834c70419d6/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py#L86

Why not let `tracer_provider` be a kwarg in `BaseExporter`? It's useful in complex systems where you have multiple providers (e.g reinitializing tracer providers in forks). It's also a step towards letting people opt out of global state, which (to me) is a very iffy part of the opentelemetry ecosystem.

I'd be willing to add a little PR. Afaik all that's needed is a kwarg line in `BaseExporter.__init__` and something like `tracer_provider = self._tracer_provider or get_tracer_provider()` wherever get_tracer_provider() is being called in it's subclasses

**Comment by avramdj** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/36363

**Comment by avramdjo** [comment]
This is solved in PR above afaik
