### ISSUE TITLE
Make `BaseExporter`  fork-safe.

### ISSUE THREAD

**Issue by avramdj** [Azure/azure-sdk-for-python#36364]
**Is your feature request related to a problem? Please describe.**
`AzureMonitorLogExporter` gives lots of `Envelopes could not be exported and are not retryable` when logging from lots of forks.

**Describe the solution you'd like**
Make `BaseExporter` fork-safe by having an `os.register_at_fork(after_in_child=...)` hook. Maybe in `BaseExporter.__init__` so it actually changes the state of the object by giving it another client connection.

**Describe alternatives you've considered**
Currently, I'm solving this by reinitializing my entire opentelemetry context (tracer provider, logger provider, exporters, handlers) on forks, because they all depend on the exporter which has to be reinitialized.

**Additional context**
I could be wrong about the mechanics of what causes the issue for me, but it feels like `BaseExporter`s connection (or any other unsafe resource) to azure is being shared among forks. This would explain why the problem disappears for me when I reinitialize it every time.

**Comment by pvaneck** [comment]
Hey, thanks for the issue and explanation. 

@lzchen @jeremydvoss Any ideas here?

**Comment by lzchen** [comment]
> Make BaseExporter fork-safe

I am not sure if there is anything about the exporter that isn't "fork safe". Our recommendation to users is to user name-spaced loggers so the logging calls emitted by the exporter are not captured as telemetry and exported (causing recursion and a tremendous amount of logs). If you are receiving `Envelopes could not be exported and are not retryable` logging statements and have configured the `LoggingHandler` to be attached to your root logger, this is actually expected behavior.

**Comment by avramdj** [comment]
> > Make BaseExporter fork-safe
> 
> I am not sure if there is anything about the exporter that isn't "fork safe". Our recommendation to users is to user name-spaced loggers so the logging calls emitted by the exporter are not captured as telemetry and exported (causing recursion and a tremendous amount of logs). If you are receiving `Envelopes could not be exported and are not retryable` logging statements and have configured the `LoggingHandler` to be attached to your root logger, this is actually expected behavior.

Yeah the handler is attached to a namespaced logger, not root. My only workaround that doesn't cause `Envelopes could not be exported and are not retryable` was to reinit the exporter in the fork. 

If anyone has ideas regarding what I can do to provide more info on the issue, I'm willing to do it.

**Comment by lzchen** [comment]
@avramdj 

Interesting, could you share a snippet of your code in how you instrument with the exporter? Also, does this behavior occur if you are not using forks? What library are you using to generate this behavior?
