### ISSUE TITLE
Azure service bus: K8 pods become idle after AMQP connection error

### ISSUE THREAD

**Issue by juhitiwari** [Azure/azure-sdk-for-python#36368]
- **Package Name**: azure-servicebus
- **Package Version**: 7.11.1
- **Operating System**: Debian Container (kubernetes pod)
- **Python Version**:  3.9.19

**Describe the bug**
The issue we are facing is similar to #28996. Our K8 pods listen to service bus messages continuously, process these messages and sends another message to a service bus queue. Often we see messages like "Connection keep-alive for 'SendClientAsync' failed: AMQPConnectionError('Error condition: ErrorCondition.SocketError\n Error Description: Can not read frame due to exception: [Errno 104] Connection reset by peer')." These mostly are temporary and the pods get reconnected on their own. But we have seen instances when this does not happen. In that case the pod just becomes idle and does not process any messages, unless the pod is restarted. We have faced many outages because of this behaviour. There are no more logs emitted from the pod again, only this last log message. This is also logged as Log.Info and not thrown as an error from the SDK, hence we are unable to capture these in our try-catch for retry upon our end.

**To Reproduce**
We do not have a full proof way to repro this as it happens randomly, but one way to try this would be to 
1. Build a service bus consumer and publisher (SendClientAsync seems to be in the publisher module, hence we are thinking this might be coming from here)
2. Keep the channel idle for 2-3 hours
3. Check for last log message as "Connection keep-alive for 'SendClientAsync' failed: AMQPConnectionError('Error condition: ErrorCondition.SocketError\n Error Description: Can not read frame due to exception: [Errno 104] Connection reset by peer')."
4. Put a message in service bus, the message will not be consumed.

We do have a sequence of logs that comes during this event.

**Expected behavior**
Pods should be able to reconnect.
If not, an error should be thrown that can help us handle retries or automatically kill pods.

Chain of events leading to this error:
[debugLogs.txt](https://github.com/user-attachments/files/16105082/debugLogs.txt)

**Comment by kashifkhan** [comment]
@juhitiwari would you also be able to provide some frame logs when this happens  please. The current snippet of logs is not enough

logging_enable=True is key here :)

```python
import logging
import sys

handler = logging.StreamHandler(stream=sys.stdout)
logger = logging.getLogger('azure.servicebus')
logger.setLevel(logging.DEBUG)
logger.addHandler(handler)

...

from azure.servicebus import ServiceBusClient

client = ServiceBusClient(..., logging_enable=True)
```

**Comment by juhitiwari** [comment]
I had enabled logging but we are not able to see them because the logging level is set to info. Will debug be required to see these ones?

**Comment by juhitiwari** [comment]
I have enabled debug logs as well. Since, we can't repro this consistently on our end, I will post the new logs here once we face this issue again.
