### ISSUE TITLE
Method `get_words` not defined inside cope samples

### ISSUE THREAD

**Issue by paolobighignoliaccenture** [Azure/azure-sdk-for-python#36375]
### Type of issue

Code doesn't work

### Description

The method  `get_words` which is inside most of the code samples in the examples in the page, is not defined inside the code samples, and therefore the provided code won't work. 

[I would love to add the definition of such method in order to contribute to this documentation.]

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/ai-documentintelligence-readme?view=azure-python-preview#examples

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/preview/ai-documentintelligence-readme.md

### Document Version Independent Id

be033072-fc7b-832b-eb4e-475685478e43

### Article author

@azure-sdk

### Metadata

* ID: e9ce343e-062b-55bc-fa32-caaf3a3242c8 
* Service: **documentintelligence**

**Comment by pvaneck** [comment]
Hey, thanks for the feedback!

@YalinLi0312 Can you take a look?

**Comment by YalinLi0312** [comment]
@paolobighignoliaccenture Please check the full code in sample file: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_analyze_layout.py#L31 
We'll include the helper function in sample code snippet, thanks for your feedback!

**Comment by YalinLi0312** [comment]
Hi @paolobighignoliaccenture , we have merged some updates today, can you take a look the latest sample code in [README.md](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/README.md#extract-layout)? The public doc portal will update soon.

Thanks

**Comment by paolobighignoliaccenture** [comment]
@YalinLi0312 to be it sounds resolved!
