### ISSUE TITLE
Skip breaking change detection in release pipeline

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#36370]
We plan to adopt breaking changes tool when generating SDK so that we could recognize potential SDK breakings in advance. However, when open it for Mgmt SDK, it blocks SDK release so I have to revert it in https://github.com/Azure/azure-sdk-for-python/pull/36104.

I understand one solution is follow https://github.com/Azure/azure-sdk-for-python/tree/main/scripts/breaking_changes_checker#types-of-breaking-changes-detected to suppress each breaking item but it is not flexible. Is there any way I can only adopt the tool but not block SDK release?

**Comment by raych1** [comment]
@catalinaperalta 
to integrate into the spec PR pipeline, the breaking change tool must support the detection within a specific service scope. This could be achieved by passing the service name when running the command of breaking change tool.

**Comment by catalinaperalta** [comment]
> @catalinaperalta to integrate into the spec PR pipeline, the breaking change tool must support the detection within a specific service scope. This could be achieved by passing the service name when running the command of breaking change tool.

The tool is scoped to run within a specific sdk directory.

**Comment by catalinaperalta** [comment]
@msyyc I'm thinking we could probably suppress all change reports for a specific library but you wont see what the breaking changes are for that library in the pipeline. Or do you want the pipeline not to block on the breaking changes check? I think the pipeline configuration should be changed in that case.

**Comment by msyyc** [comment]
@catalinaperalta I find the way to disable breaking change: https://github.com/Azure/azure-sdk-for-python/blob/14dd5826d0738d1df5e593e70263e58f19ae3cb2/eng/pipelines/templates/steps/run_breaking_changes.yml#L12-L24. We just need to set `Skip.BreakingChanges` as `true` then this step will be skipped.
Let me check it and if it works, I will close this issue.

**Comment by catalinaperalta** [comment]
@msyyc did your solution work?

**Comment by msyyc** [comment]
I will try it after https://github.com/Azure/azure-sdk-for-python/pull/36601 merged
