### ISSUE TITLE
FOCUS specification Cost and Usage Report for all subscription types

### ISSUE THREAD

**Issue by lokesh-heeddata** [Azure/azure-sdk-for-python#36413]
I checked the consumption usage details API to get the FOCUS specification keys and values. I am not able to find the suitable api call with required parameters. 
Is their any new API is introduced to get that data?
How can we get the complete FOCUS specification data through an API call?  Please, provide the suitable api call to move further steps.
@shanselman @osake @archerzz

**Comment by lokesh-heeddata** [comment]
> Hi @lokesh-heeddata, thank you for opening an issue. Would you be able to share more information for us to triage this issue? Which Azure SDK library are you using? Are you able to share any service documentation that you're referring to so we can better understand your scenario?

Hi @mccoyp , We need an API call to get the data with FOCUS format naming conventions which was released by the FinOps FOCUS organization[https://focus.finops.org/]. Please help me to find any public api call to get the required data.

**Comment by ChenxiJiang333** [comment]
Hi @lokesh-heeddata, I have checked the swagger [definitions](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/stable/2023-11-01/consumption.json). It seems there's no such API among the consumption usage details APIs and they are possibly going to be retired by generate cost details APIs.
For now, you could take a try on this [sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/costmanagement/azure-mgmt-costmanagement/generated_samples/generate_cost_details_report_by_billing_account_enterprise_agreement_customer_and_billing_period.py).
