### ISSUE TITLE
ImportError: cannot import name 'build_import_method_request'

### ISSUE THREAD

**Issue by jeremycline** [Azure/azure-sdk-for-python#36416]
- **Package Name**: azure-mgmt-sql
- **Package Version**: 4.0.0b17
- **Operating System**: Linux
- **Python Version**:  3.12

**Describe the bug**
Version 4.0.0b17 includes an import for a function that doesn't exist.

**To Reproduce**
1. pip install azure-mgmt-sql==4.0.0b17
2. python -c 'from azure.mgmt.sql.aio import operations'

```
❯ python -c 'from azure.mgmt.sql.aio import operations'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jcline/.virtualenvs/az-sql/lib64/python3.12/site-packages/azure/mgmt/sql/aio/__init__.py", line 9, in <module>
    from ._sql_management_client import SqlManagementClient
  File "/home/jcline/.virtualenvs/az-sql/lib64/python3.12/site-packages/azure/mgmt/sql/aio/_sql_management_client.py", line 20, in <module>
    from .operations import (
  File "/home/jcline/.virtualenvs/az-sql/lib64/python3.12/site-packages/azure/mgmt/sql/aio/operations/__init__.py", line 12, in <module>
    from ._databases_operations import DatabasesOperations
  File "/home/jcline/.virtualenvs/az-sql/lib64/python3.12/site-packages/azure/mgmt/sql/aio/operations/_databases_operations.py", line 33, in <module>
    from ...operations._databases_operations import (
ImportError: cannot import name 'build_import_method_request' from 'azure.mgmt.sql.operations._databases_operations' (/home/jcline/.virtualenvs/az-sql/lib64/python3.12/site-packages/azure/mgmt/sql/operations/_databases_operations.py). Did you mean: 'build_import_request'?
```

**Expected behavior**
It doesn't crash.

**Screenshots**

**Additional context**
I hit this when attempting to update the azure-cli in Fedora which requires this version of azure-mgmt-sql. As part of the standard build check it attempts to import all the public modules in the package, which found this particular issue. I'd recommend introducing a similar check to your CI so you catch this sort of thing before publishing. The script used in Fedora is here: https://src.fedoraproject.org/rpms/python-rpm-macros/blob/rawhide/f/import_all_modules.py

**Comment by mccoyp** [comment]
Hi @jeremycline, thank you for reporting this issue. I'll tag the appropriate folks to look into fixing this.

**Comment by msyyc** [comment]
Hi, we will take an investigation soon.

**Comment by msyyc** [comment]
Hi @jeremycline Please help try latest version https://pypi.org/project/azure-mgmt-sql/4.0.0b18/

**Comment by jeremycline** [comment]
Works for me, thanks!
