### ISSUE TITLE
SyntaxWarning: invalid escape sequence - azure-search-documents

### ISSUE THREAD

**Issue by jeffreyrubi** [Azure/azure-sdk-for-python#36428]
- **Package Name**: azure-search-documents
- **Package Version**: 11.6.0b4
- **Operating System**: Docker base (python:3.10-slim / Debian)
- **Python Version**: 3.10

**Describe the bug**
When running the with the library, there is a Deprecation warning: invalid escape sequence. 

**To Reproduce**
1. Build a docker image with a python app importing the captioned library.

**Expected behavior**
No warning.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/44762348/67556a76-b418-4644-8f49-5f14d7229f50)

**Additional context**
Seems relate to https://github.com/Azure/azure-sdk-for-python/issues/36232, https://github.com/Azure/azure-sdk-for-python/issues/36233

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by pabloapast** [comment]
+1, having this same issue with:
- Package Name: azure-search-documents
- Package Version: 11.5.1
- Operating System: Docker base (python:3.12.0-slim)
- Python Version: 3.12

@xiangyan99 any updates?

**Comment by xiangyan99** [comment]
I am working on a fix.

Could you help to share your repro steps so I can make sure it works?

**Comment by pzavolinsky** [comment]
:wave: @xiangyan99 , here's a quick repro in docker:

1) Save this to `Dockerfile`:
```dockerfile
FROM python:3.12.5-slim
RUN pip install --no-compile -v azure-search-documents==11.5.1
CMD ["python", "-c", "import azure.search.documents"]
```
2) In that same dir:
```shell
docker build -t test .
docker run --rm -ti test
```

Hope this helps!
