### ISSUE TITLE
AzureAIDocumentIntelligence : Analyze request Parameter in begin_analyze_document throwing error

### ISSUE THREAD

**Issue by sakshi1989** [Azure/azure-sdk-for-python#36434]
- **Package Name:: azure-ai-documentintelligence**: 
- **Package Version: : 1.0.0b3**: 
- **Operating System: Windows**:
- **Python Version : 3.11**: 

**Describe the bug**
The begin_analyze_document method of the DocumentIntelligenceClient is throwing the below error - 
`HttpResponseError: (InvalidArgument) Invalid argument.
Code: InvalidArgument
Message: Invalid argument.
Inner error: {
    "code": "ParameterMissing",
    "message": "The parameter urlSource or base64Source is required."
}`
I am trying this resource as per the example - [Example](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-ai-documentintelligence/latest/index.html#examples)

**To Reproduce**
1. Install `azure-ai-documentintelligence` library
2. Import the libraries - 
`from azure.core.credentials import AzureKeyCredential`
`from azure.ai.documentintelligence import DocumentIntelligenceClient`
`from azure.ai.documentintelligence.models import AnalyzeResult`
3. Use the endpoint and the api key to use the `azure-ai-documentintelligence` resource.
4. Use any local PDF file 
5. Write the below code -
`document_intelligence_client = DocumentIntelligenceClient(endpoint=endpoint, credential=AzureKeyCredential(api_key))`

`with open(path_to_sample_documents, "rb") as f: `

    print(type(f))

    poller = document_intelligence_client.begin_analyze_document(model_id="prebuilt-layout",
                                                                 analyze_request=f,
                                                                 output_content_format="markdown")
`result : AnalyzeResult = poller.result()`

**Expected behavior**
The document should have got processed

**Additional context**
The same issue was opened here, but it was closed as no response was received from the person who opened the issue.
[Existing Issue](https://github.com/Azure/azure-sdk-for-python/issues/35893)

After debugging the internal code of the library it is failing at line 507
` pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )`
at path [Internal Code](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_operations/_operations.py)

**Comment by YalinLi0312** [comment]
Hi @sakshi1989 , can you try with passing parameter `content_type`?
```python
print(type(f))

poller = document_intelligence_client.begin_analyze_document(model_id="prebuilt-layout",
                                                             analyze_request=f,
                                                             output_content_format="markdown",
                                                             content_type="application/octet-stream",)
```
Or passing in a `AnalyzeDocumentRequest`:
```python
print(type(f))

poller = document_intelligence_client.begin_analyze_document(model_id="prebuilt-layout",
                                                             AnalyzeDocumentRequest(bytes_source=f),
                                                             output_content_format="markdown",)
```

Thanks

**Comment by sakshi1989** [comment]
Thanks @YalinLi0312 for your reply. Your first suggestion works, but not the second one. With the second one I am receiving below error - 
`TypeError: cannot pickle '_io.BufferedReader' object`

Also, I would like to point out that in documentation there is nowhere mentioned to have the parameter `content_type="application/octet-stream"`, it would be good to mention the same in the documentation so that users don't run into the same error. in the example, yes this parameter is mentioned but not in the documentation.

**Comment by YalinLi0312** [comment]
Hi @sakshi1989, thanks for the feedback! We'll mention the type in our documentation.
For the second one, it should pass `f.read()` instead. I updated in the previous comment, please try it again.

**Comment by sakshi1989** [comment]
> ```python
> model_id="prebuilt-layout",
>                                                              AnalyzeDocumentRequest(bytes_source=f.read()),
>                                                              output_content_format="markdown",
> ```

Hi @YalinLi0312 , thank you for your quick response on the issue. Yes, now both the options are working.

**Comment by sathish331977** [comment]
### encountered the same problem 

with open("cd_0001.pdf", "rb") as f:
  poller = document_intelligence_client.begin_analyze_document(
    "prebuilt-layout",
    AnalyzeDocumentRequest(bytes_source=f.read()),
    output_content_format ="markdown",
  )
result: AnalyzeResult = poller.result()

### running into following error

ResourceNotFoundError: (NotFound) Resource not found.
Code: NotFound
Message: Resource not found.
Inner error: {
    "code": "OutputOptionNotFound",
    "message": "The output option was not found: Failed to generate the analyze results in the output option format. Output option should be informed in analyze call."
}

### version: azure-ai-documentintelligence 1.0.0b4
