### ISSUE TITLE
No documentation for HTTPRequest class

### ISSUE THREAD

**Issue by will-0** [Azure/azure-sdk-for-python#36442]
### Type of issue

Typo

### Description

There's no documentation for attributes of the HTTPRequest file attributes (or other attributes, for that matter).

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-functions/azure.functions.http.httprequest?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-functions/azure.functions.http.HttpRequest.yml

### Document Version Independent Id

556f723c-5e29-edae-17e2-b8b93c79416f

### Article author

@lmazuel

### Metadata

* ID: 43cd60a6-2858-89d4-f77e-fbd1f76cbcc0 
* Service: **azure-functions**

**Comment by mccoyp** [comment]
Hi @will-0, thank you for opening an issue. The `azure-functions` library is actually owned by another team, so I created another issue in their GitHub repository to track this: https://github.com/Azure/azure-functions-python-worker/issues/1528.

I'll close this issue, but we'll also look into correctly linking bug reports on the doc page to the appropriate GitHub repository.
