### ISSUE TITLE
azure.identity.aio.CertificateCredential constructor does not support x5c via send_certificate_chain

### ISSUE THREAD

**Issue by gabloe** [Azure/azure-sdk-for-python#36441]
- **Package Name**:  azure.identity.aio.CertificateCredential 
- **Package Version**: 1.17.1
- **Operating System**: multiple
- **Python Version**: 3.11

**Describe the bug**
The constructors for azure.identity.CertificateCredential and azure.identity.aio.CertificateCredential are inconsistent. The aio version does not support the send_certificate_chain argument that the non-aio version supports. This means that SN+I is not possible in the aio version.

**To Reproduce**
Using an SPN configured for SN+I and without a pinned cert the following code fails with a invalid_client (AADSTS700027) error.

```
from azure.identity.aio import CertificateCredential

credential = CertificateCredential(
    tenant_id="<Your tenant id>",
    client_id="<Your client id>",
    certificate_path='<Your cert>',
    send_certificate_chain=True
)

await credential.get_token(".default")
```

**Expected behavior**
It should succeed

**Comment by xiangyan99** [comment]
Thanks for reaching out.

We don't have async support for SNI certificate. https://github.com/Azure/azure-sdk-for-python/issues/13349

Please use sync one as a work around.
