### ISSUE TITLE
serial_console_client.serial_ports.list is returning an empty list on a Bootdiagnostics enabled Azure VM

### ISSUE THREAD

**Issue by shruti25ratnam** [Azure/azure-sdk-for-python#36440]
- **Package Name**: azure.mgmt.serialconsole 
- **Package Version**: 
- **Operating System**: Windows and Ubuntu
- **Python Version**: 3.12

**Describe the bug**
List Serial port is returning an empty list.
ACCClient action status: Serial ports: []

https://cirrusperf.azurewebsites.net/v1/testpassinstances/c/207210660/runsets/339057174/runs/3cfbe5cb-4342-45b4-9b99-afe435f297a0/actions/1/actiondetail

**To Reproduce**
1. from azure.mgmt.serialconsole.models import SerialPort
2. Enable BootDiagnostics for the VM: vm.diagnostics_profile.boot_diagnostics = BootDiagnostics(enabled=True)   
4. try:
            TestContext.sdk.inform(f"Testing serial console connection for VM {vm_name}")
            serial_ports_result = await serial_console_client.serial_ports.list(
                resource_group_name=resource_group_name,
                resource_provider_namespace="Microsoft.Compute",
                parent_resource=vm_name,
                parent_resource_type="virtualMachines"
            )
            serial_ports = serial_ports_result.value
          except Exception as e:
            TestContext.sdk.inform(f"Failed to test serial console connection for VM {vm_name}: {e}")
            return False

    return True

**Expected behavior**
To return atleast 1 serial port. 
Serial console is enabled on the subscription by default.
**Screenshots**
https://cirrusperf.azurewebsites.net/v1/testpassinstances/c/207210660/runsets/339057174/runs/3cfbe5cb-4342-45b4-9b99-afe435f297a0/actions/1/actiondetail

**Additional context**
This is a CloudEx validation test

**Comment by msyyc** [comment]
@shruti25ratnam please help on this issue

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
Hi, @shruti25ratnam 
I failed to reproduce the issue. the connection may need some time to be prepared so please wait for a while after a vm created.
![image](https://github.com/user-attachments/assets/0e1df82b-916d-443d-85a3-ed99ac34ac1a)

**Comment by shruti25ratnam** [comment]
@ChenxiJiang333 after some wait I was able to retrieve the port but the port shows status = enabled even when the serial-console is disabled. Do you happen to know what port 0 is for? is it a COM port?

**Comment by ChenxiJiang333** [comment]
> @ChenxiJiang333 after some wait I was able to retrieve the port but the port shows status = enabled even when the serial-console is disabled. Do you happen to know what port 0 is for? is it a COM port?

Not sure about this, since we're not domain expert on this server, you can open an issue at https://github.com/Azure/azure-rest-api-specs/issues to get suggestion from the service team.

**Comment by xiangyan99** [comment]
This is the service behavior and please open ticket for the service for help.

https://azure.microsoft.com/support/create-ticket
