### ISSUE TITLE
[ISSUE]: __init__() missing 1 required positional argument: 'certificate_path'

### ISSUE THREAD

**Issue by abhi7878** [Azure/azure-sdk-for-python#36455]
**Version**
```
Name: azure-identity
Version: 1.10.0
```
**Constructor:**

credential = CertificateCredential(tenant_id=<tenant_id>, client_id=<client_id>, certificate_data=certificate_data)

Error:
__init__() missing 1 required positional argument: 'certificate_path'

How to resolve the above error 

@azure-sdk

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Please upgrade your azure-identity library.

**Comment by abhi7878** [comment]
Hi @xiangyan99 
Thank you so much for the reply,
