### ISSUE TITLE
Test samples step broken after switching to UseFederatedAuth

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#36467]
The test samples step stopped running (just shows pass) after UseFederatedAuth: true is set in the tests.yml. 

Not sure if this is the source of the error:

> Last exit code: 
Error: no "view" rule for type "text/x-python" passed its test case
       (for more information, add "--debug=1" on the command line)
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening '/mnt/vss/_work/1/s/scripts/devops_tasks/dispatch_tox.py'

Example with eventgrid:

Added UseFederatedAuth: true on 5/31: https://github.com/Azure/azure-sdk-for-python/pull/35851/files

Test samples step before PR (5/30): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3833023&view=logs&j=fe7804ca-eaac-501a-67e8-e2604a50cb52&t=fef01369-6249-5df0-3692-3e5dec542b9f

Test samples step after PR (7/10): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3950597&view=logs&j=c8837ca9-7e4f-5904-07be-77c9cad87f76&t=c74bc2cc-a575-5ee1-ad8c-df8b1ef5314a

**Comment by scbedd** [comment]
Taking a look today.

**Comment by pvaneck** [comment]
This doesn't appear to be resolved based on the latest event grid tests: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3983007&view=logs&j=ea4469f7-e198-5c30-a507-21b1bcb5db0b&t=7ae4e0ce-7a3f-56a5-9faf-a2456a6dc00e

Also ran into this when trying to enable Monitor sample testing: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3983713&view=logs&j=ea4469f7-e198-5c30-a507-21b1bcb5db0b&t=7ae4e0ce-7a3f-56a5-9faf-a2456a6dc00e&l=21

**Comment by scbedd** [comment]
Agreed. I don't think the federated samples ever worked tbh. I think this PR fixes it. #36598
