### ISSUE TITLE
send_certificate_chain is missing in get_client_credential from OnBehalfOfCredential class in Azure.Idenitty module.

### ISSUE THREAD

**Issue by pradumnalenka** [Azure/azure-sdk-for-python#36489]
- **Package Name**:  1Latest
- **Package Version**:  Latest
- **Operating System**:
- **Python Version**:  3.11

**Describe the bug**
A clear and concise description of what the bug is. send_certificate_chain is missing in get_client_credential from OnBehalfOfCredential class in Azure.Idenitty module. There is no way to support SNI for OnBehalfOfCredential class.
`credential = get_client_credential(
                    certificate_path=None, password=kwargs.pop("password", None), certificate_data=client_certificate
                )`

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pvaneck** [comment]
Thanks for the feedback, I think this is something we can definitely add.
