### ISSUE TITLE
Python SDKv2 as well as CLI do not archive environment

### ISSUE THREAD

**Issue by BennoWingender** [Azure/azure-sdk-for-python#36527]
- **Package Name**: azure.ai.ml as well as Azure CLI
- **Package Version**: Multiple Versions are affected
- **Operating System**: Ubuntu - Version: 20.04.6 LTS (Focal Fossa)
- **Python Version**:  3.8.16 current, and more

**Describe the bug**
The Python SDKv2 and the CLI both do not archive a given environment.
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-environments-v2?view=azureml-api-2&tabs=cli

**To Reproduce**
1. CLI: az ml environment archive --name [name] --resource-group [grp_name] --workspace-name [ws_name]
2. SDK:
from azure.ai.ml import MLClient
ml_client = MLClient(DefaultAzureCredential(), subscription_id, res_grp, workspace_name)
ml_client.environments.archive(name=env_name, version=1) #can use other versions

**Expected behavior**
We expect the environment to be archived.

**Additional context**
We tried to use the function on different versions.
We have sufficient rights to archive environments (We can archive environments over the graphical overlay)
Code does not return an error.

**Comment by achauhan-scc** [comment]
@BennoWingender - I just tried to archive an environment using CLI and archived env got removed from list command
az ml environment archive -g <rg> --workspace-name <ws> -n <env-name>
az ml environment list -g <rg> --workspace-name <ws> -o table
<img width="427" alt="image" src="https://github.com/user-attachments/assets/43443503-6f04-41cc-9ba3-e5aadd18a634">

But I can fetch the environment using show command
az ml environment show -g <rg> --workspace-name <ws> -n <env-name> --version <version>

Also after archive, I am not seeing it on ML studio UI, Can you please help me what do you mean *not working*.
Are they continue to appear on list command or UI?
If yes, can you capture the debug logs for both archive command and list command and share it?
please ensure to remove the sensitive information from the logs.

**Comment by achauhan-scc** [comment]
@BennoWingender - are you still able to repo with latest release of CLI or SDK?
if yes, please az ml commands? as I am still unable to repo.

And really sorry for such long pause.
