### ISSUE TITLE
ai-search-documents. Unable to build a model

### ISSUE THREAD

**Issue by BenConstable9** [Azure/azure-sdk-for-python#36539]
- **Package Name**: ai-search-documents
- **Package Version**: 11.6.0b4 (happens on other versions)
- **Operating System**: Windows
- **Python Version**: 3.12

**Describe the bug**

azure.core.exceptions.SerializationError: Unable to build a model: Unable to deserialize response data. Data: [<azure.search.documents.indexes._generated.models._models_py3.SemanticConfiguration object at 0x000002CC7C98CEF0>], [SemanticConfiguration] 

Unable to serialize Semantic Configurations. 

**To Reproduce**

```python
fields = [
    SimpleField(name="Id", type=SearchFieldDataType.String, filterable=True),
    SearchableField(
        name="Title", type=SearchFieldDataType.String, filterable=True
    ),
    SearchableField(
        name="ChunkId",
        type=SearchFieldDataType.String,
        key=True,
        analyzer_name="keyword",
    ),
    SearchableField(
        name="Chunk",
        type=SearchFieldDataType.String,
        sortable=False,
        filterable=False,
        facetable=False,
    ),
    SearchableField(
        name="Keywords", type=SearchFieldDataType.String, collection=True
    ),
    SearchableField(
        name="Source",
        type=SearchFieldDataType.String,
        sortable=True,
        filterable=True,
        facetable=True,
    ),
]

semantic_config = SemanticConfiguration(
    name="semantic-config",
    prioritized_fields=SemanticPrioritizedFields(
        title_field=[SemanticField(field_name="Title")],
        content_fields=[SemanticField(field_name="Chunk")],
        keywords_fields=[SemanticField(field_name="Keywords")],
    ),
)

semantic_search = SemanticSearch(configurations=[semantic_config])

index = SearchIndex(
    name="index",
    fields=index_fields,
    semantic_search=semantic_search,
)
index_client.create_or_update_index(index)
```

**Expected behavior**

Index should deploy with the semantic configuration.

**If you apply the same configuration via the Portal, it works fine. But it does not work via the Python SDK.**

**Comment by xiangyan99** [comment]
Please use latest stable release 11.5.0: https://pypi.org/project/azure-search-documents/11.5.0/

**Comment by BenConstable9** [comment]
/unresolve

Stable release doesn't support semantic search. Is there any eta on 11.6 stable release?

**Comment by xiangyan99** [comment]
I looked into the code snippet. 

Seems like the type of title_field should be `SemanticField` rather than `List[SemanticField]`

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/azure/search/documents/indexes/_generated/models/_models_py3.py#L9278

Could you modify your code to

```py
semantic_config = SemanticConfiguration(
    name="semantic-config",
    prioritized_fields=SemanticPrioritizedFields(
        title_field=SemanticField(field_name="Title"),
        content_fields=[SemanticField(field_name="Chunk")],
        keywords_fields=[SemanticField(field_name="Keywords")],
    ),
)
```

and see if it works?
