### ISSUE TITLE
[Cosmos] Session Token helpers

### ISSUE THREAD

**Issue by TheovanKraay** [Azure/azure-sdk-for-python#36584]
****Is your feature request related to a problem? Please describe.**
Implementing sharing of session tokens in order to achieve read-after-write consistency for multiple clients can be difficult to manage. 

**Describe the solution you'd like**
Add session token helper functionality to Python SDK that makes sharing of session tokens between clients more transparent

**Describe alternatives you've considered**
Bounded staleness can be used, but this has other undesirable trade-offs

**Additional context**

**Comment by tvaron3** [comment]
These are the samples for managing session tokens across clients. 
https://github.com/Azure/azure-sdk-for-python/blob/d96f8973ca5c19ff014c38f4f700f565c737a318/sdk/cosmos/azure-cosmos/samples/session_token_management_async.py

https://github.com/Azure/azure-sdk-for-python/blob/d96f8973ca5c19ff014c38f4f700f565c737a318/sdk/cosmos/azure-cosmos/samples/session_token_management.py
