### ISSUE TITLE
Not able to get the nodes list related to the particular AKS cluster

### ISSUE THREAD

**Issue by lokesh190496** [Azure/azure-sdk-for-python#36581]
@mccoyp
I tried to get the clusters list available in the subscription. But, I am not able to fetch the connected NODES with respect to the cluster.
I used the following library to fetch the clusters list - "azure-mgmt-containerservice==29.0.0"
I need the library to fetch the list of NODES connected to the cluster in a single api call.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
@ChenxiJiang333 please help on this issue

**Comment by ChenxiJiang333** [comment]
Hi @lokesh190496, you can try these codes below.
```
response = client.managed_clusters.list()
print(next(response).agent_pool_profiles[0].as_dict())
```
