### ISSUE TITLE
[Cosmos] Full Text Search (preview)

### ISSUE THREAD

**Issue by TheovanKraay** [Azure/azure-sdk-for-python#36586]
* We can use this to track Full Text Search

**Is your feature request related to a problem? Please describe.**
More details to follow. 

**Describe the solution you'd like**
More details to follow. 

**Describe alternatives you've considered**
More details to follow.

**Comment by simorenoh** [comment]
Done with https://github.com/Azure/azure-sdk-for-python/pull/38275.
