### ISSUE TITLE
list_blobs support for returning prefix

### ISSUE THREAD

**Issue by Segsfault** [Azure/azure-sdk-for-python#366]
Hypothetical container contents:

readme.txt
2014/06/10/logfile.txt
2015/06/10/logfile.txt

I'd like to get a list of the file and prefixes for the top level of the container.
`list_blobs` with '/' as a delimiter returns just 'readme.txt', but would be useful to get ['readme.txt','2014/', '2015/']  Unless I know the prefixes in advance, I can't list the contents of specific subdirectories programmatically.

Is any such support planned?

**Comment by huguesv** [comment]
I think this will do what you want:
```
        self._create_container(self.container_name)
        data = b'hello world'
        self.bs.put_blob(self.container_name, '2014/06/10/logfile.txt', data, 'BlockBlob')
        self.bs.put_blob(self.container_name, '2015/06/10/logfile.txt', data, 'BlockBlob')
        self.bs.put_blob(self.container_name, 'readme.txt', data, 'BlockBlob')

        resp = self.bs.list_blobs(
            self.container_name, delimiter='/')

        print('files')
        for blob in resp:
            print(blob.name)

        print('folders')
        for prefix in resp.prefixes:
            print(prefix.name)

```

Which will print:
```
files
readme.txt
folders
2014/
2015/
```

**Comment by Segsfault** [comment]
Ya, this is exactly it..thanks for the quick response.
