### ISSUE TITLE
Alternatives for accessing Azure Storage Account without using SAS when creating an environment

### ISSUE THREAD

**Issue by boynextdoor-cze** [Azure/azure-sdk-for-python#36603]
I am creating a training environment in my Azure ML Workspace using docker, as the code below:
```python
credential = DefaultAzureCredential()
ml_client = MLClient.from_config(credential, path='config.json')
environment = Environment(
    name=args.environment_name,
    description=args.description,
    build=BuildContext(path=args.docker_context_path, dockerfile_path=args.dockerfile_name)
)
ml_client.environments.create_or_update(environment)
```

As Microsoft has disabled SAS access to storage account internally, when deploying the code above on Azure DevOps I got the following error: `azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Key based authentication is not permitted on this storage account.'`. I guess the reason is that `create_or_update` methods uses SAS URI for environment creation so that the problem seems to be inevitable.

I've tried using `ManagedIdentityCredential()` but the error message became `ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.`

Therefore, I wonder if there's any alternative to avoid using SAS, either via Python SDK or Azure CLI

**Comment by swathipil** [comment]
Hi @boynextdoor-cze - Thanks for opening an issue. We'll take a look at this asap!

**Comment by achauhan-scc** [comment]
assuming error in occurring while uploading the image file to storage account, can you please help with full exception trace?
I think what you need a key less data store.
https://github.com/Azure/azureml-examples/blob/main/sdk/python/resources/datastores/datastore.ipynb

**Comment by boynextdoor-cze** [comment]
Problem has been solved. I granted the app registration the reader & contributor access and then everything works well
