### ISSUE TITLE
DefaultAzureCredential / SharedCacheCredential do not differentiate between realms when considering cached tokens

### ISSUE THREAD

**Issue by 2ps** [Azure/azure-sdk-for-python#36614]
- **Package Name**: `azure-identity`
- **Package Version**: `1.16.0`
- **Operating System**: `ubuntu 20.04`
- **Python Version**:  `3.11.8`

**Describe the bug**

`SharedCacheCredential` cannot differentiate between tokens for the same `home_account_id` but for different `realm`s.  

**To Reproduce**

consider the following scenario.  user alice@contoso.com has an account in home tenant contoso.  alice@contoso.com is also an administrator to additional tenant fabrikam.  

we use the following python code to cache the alice@contoso.com's token into the shared cache.

```
from azure.identity import DefaultAzureCredential, TokenCachePersistenceOptions
options = TokenCachePersistenceOptions(name='my_secret_cache')
creds = DefaultAzureCredential(
    exclude_interactive_browser_credential=False,
    interactive_browser_tenant_id='contoso_tenant_id',
    cache_persistence_options=options,
    redirect_uri='http://localhost:8100',
)
token = creds.get_token('https://management.azure.com/.default')
creds = DefaultAzureCredential(
    exclude_interactive_browser_credential=False,
    interactive_browser_tenant_id='fabrikam_tenant_id',
    cache_persistence_options=options,
    redirect_uri='http://localhost:8100',
)
token = creds.get_token('https://management.azure.com/.default')
```

e.g., in the example above, the cotoso realm cached token is in position 1 in the cache, and the fabrikam realm cached token is in position 2 in the cache.  

Now, consider trying to sign in alice@contoso.com to the fabrikam realm to perform operations against the fabrikam tenant:

```
from azure.identity import DefaultAzureCredential, TokenCachePersistenceOptions
options = TokenCachePersistenceOptions(name='my_secret_cache')
creds = DefaultAzureCredential(
    exclude_interactive_browser_credential=False,
    shared_cache_tenant_id='contoso_tenant_id',
    cache_persistence_options=options,
    redirect_uri='http://localhost:8100',
)
```

`creds` in the example above will *always* retrieve the first credential in the cache since both cached tokens have the same  `home_account_id`, but there is no way to retrieve and use the cached fabrikam token.  

**Expected behavior**

We should be able to target the cached credential for a specific tenant / realm.

**Screenshots**
n/a

**Comment by xiangyan99** [comment]
Thanks for reaching out.

I don't quite understand your scenario.

Do you want to persist your token like https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/samples/user_authentication.py?

**Comment by 2ps** [comment]
The scenario is that we are writing is short-term caching of tokens after interactively authenticating.  e.g., interactively authenticate against contoso to perform operation 1 on the contoso tenant, and then interactively authenticate against fabrikam to perform operation 2 on the fabrikam tenant, and then used cache credentials to perform operation 3 on the contoso tenant.  Because operation 3 is performed near the same time as operation 1, we don't want to have the user interactively relogin again (e.g., just like the azure cli).

**Comment by 2ps** [comment]
Theoretically, we should be able to do the above with a chained credential (like `DefaultAzureCredential`) that has the `SharedTokenCacheCredential` before the `InteractiveBrowserCredential`.

**Comment by 2ps** [comment]
@xiangyan99 -- apologies, you are right, I updated the steps to reproduce to include the `cache_persistence_options` parameter, which I had inadvertently omitted.

**Comment by 2ps** [comment]
@xiangyan99  -- I can have a pull request ready for this, but the question I had is did you prefer changing the semantics of the existing `shared_cache_tenant_id` parameter of `DefaultAzureCredential` and `tenant_id` parameter of `SharedTokenCacheCredential` or by adding new parameters for `shared_cache_realm` / `realm`?

**Comment by xiangyan99** [comment]
Thank you for the information.

If I understand correctly, your situation involves multiple users wanting to log into the same app, and you plan to cache the tokens for them.

As noted, when we cache the token, we do not store user information. Therefore, we cannot identify which user the token belongs to.

For an app that needs to be shared by multiple users, I would recommend not caching the token, as it increases security risks.

**Comment by 2ps** [comment]
@xiangyan99  -- that is not our scenario.  We have the same user logging into multiple tenants.  Not multiple users using the same app.  And, from what I see in the code and in the cache when I try locally -- user information is stored in the cache.  Currently, the shared cache token lookup occurs based on the home tenant ID of the user trying to login (e.g., alice@example.com's home tenant).  However, we should also allow the lookup to be done by the "realm id," i.e., the target tenant that alice@example.com is managing.

**Comment by xiangyan99** [comment]
Logically, tenants are isolated. alice@contoso.com in tenant 1 and alice@contoso.com in tenant 2 could be completely unrelated.

Lookup by realm id may result into unwanted cache-hit.
