### ISSUE TITLE
[Cosmos] Add SDK retries to 449 errors

### ISSUE THREAD

**Issue by simorenoh** [Azure/azure-sdk-for-python#36612]
Even though other Cosmos SDKs retry on 449 error codes, we don't have any retry logic built around that in the Python Cosmos SDK - it is even pointed out in public documentation that we should do as much: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/conceptual-resilient-sdk-applications#should-my-application-retry-on-errors

**Comment by tvaron3** [comment]
Python is a gateway sdk and gateway already retries 449s and 410s internally.
