### ISSUE TITLE
The latest version of azure-mgmt-rdbms uses old API and doesn`t return properties.privateEndpointConnections field

### ISSUE THREAD

**Issue by vit-corp** [Azure/azure-sdk-for-python#36625]
- **Package Name**: azure-mgmt-rdbms
- **Package Version**: 10.1.0
- **Operating System**: Any
- **Python Version**: Any

**Describe the bug**
The latest version of azure-mgmt-rdbms uses old API and doesn`t return properties.privateEndpointConnections field. When I try to list all MYSQL Flexible Severs, it returns json without properties.privateEndpointConnections field. It blocks us in our development goals. 

**Expected behavior**
{
    "sku": {
        "name": "Standard_D2ds_v4",
        "tier": "GeneralPurpose"
    },
    "systemData": {
        "createdAt": "2024-07-22T20:15:40.1653375Z"
    },
    "properties": {
        "administratorLogin": "admin",
        "storage": {
            "storageSizeGB": 20,
            "iops": 360,
            "autoGrow": "Enabled",
            "autoIoScaling": "Disabled",
            "storageSku": "Premium_LRS",
            "logOnDisk": "Disabled",
            "storageRedundancy": "LocalRedundancy"
        },
        "version": "5.7",
        "state": "Ready",
        "fullyQualifiedDomainName": "mysqlserver.mysql.database.azure.com",
        "availabilityZone": "3",
        "maintenanceWindow": {
            "customWindow": "Disabled",
            "dayOfWeek": 0,
            "startHour": 0,
            "startMinute": 0
        },
        "replicationRole": "None",
        "replicaCapacity": 10,
        "network": {
            "publicNetworkAccess": "Enabled"
        },
        "backup": {
            "backupRetentionDays": 7,
            "backupIntervalHours": 24,
            "geoRedundantBackup": "Disabled",
            "earliestRestoreDate": "2024-07-22T20:25:40.1653375+00:00"
        },
        "highAvailability": {
            "mode": "Disabled",
            "state": "NotEnabled",
            "standbyAvailabilityZone": ""
        },
        "privateEndpointConnections": [
            {
                "properties": {
                    "privateEndpoint": {
                        "id": "/subscriptions/1111111111111111111111111111/resourceGroups/resource-group/providers/Microsoft.Network/privateEndpoints/endpoint"
                    },
                    "groupIds": [
                        "mysqlServer"
                    ],
                    "privateLinkServiceConnectionState": {
                        "status": "Approved",
                        "description": "Auto-approved",
                        "actionsRequired": "None"
                    },
                    "provisioningState": "Ready"
                },
                "id": "/subscriptions/1111111111111111111111111111/resourceGroups/resource-group/providers/Microsoft.DBforMySQL/flexibleServers/mysqlserve/privateEndpointConnections/endpoint-1111111111111111111111111111"
            }
        ]
    },
    "location": "East US",
    "tags": {},
    "id": "/subscriptions/1111111111111111111111111111/resourceGroups/resource-group/providers/Microsoft.DBforMySQL/flexibleServers/mysqlserver",
    "name": "mysqlserver",
    "type": "Microsoft.DBforMySQL/flexibleServers"
}

**Actual behavior**

  {
    "id": "/subscriptions/1111111111111111111111111111/resourceGroups/resource-groupn/providers/Microsoft.DBforMySQL/flexibleServers/mysqlserver",
    "name": "mysqlserver",
    "type": "Microsoft.DBforMySQL/flexibleServers",
    "tags": {},
    "location": "East US",
    "sku": {
      "name": "Standard_D2ds_v4",
      "tier": "GeneralPurpose"
    },
    "systemData": {
      "createdAt": "2024-07-22T20:15:40.165337Z"
    },
    "properties": {
      "administratorLogin": "admin",
      "version": "5.7",
      "availabilityZone": "3",
      "replicationRole": "None",
      "replicaCapacity": 10,
      "state": "Ready",
      "fullyQualifiedDomainName": "mysqlserver.mysql.database.azure.com",
      "storage": {
        "storageSizeGB": 20,
        "iops": 360,
        "autoGrow": "Enabled",
        "storageSku": "Premium_LRS"
      },
      "backup": {
        "backupRetentionDays": 7,
        "geoRedundantBackup": "Disabled",
        "earliestRestoreDate": "2024-07-22T20:25:40.165337Z"
      },
      "highAvailability": {
        "mode": "Disabled",
        "state": "NotEnabled",
        "standbyAvailabilityZone": ""
      },
      "network": {
        "publicNetworkAccess": "Enabled"
      }
    },
    "resourceGroup": "resource-group"
  }
 

**Additional context**
Please add properties.privateEndpointConnections field.

**Comment by swathipil** [comment]
Hi @vit-corp - Thanks for opening an issue. We'll take a look asap.

**Comment by msyyc** [comment]
Hi @vit-corp , could you try latest version https://pypi.org/project/azure-mgmt-rdbms/10.2.0b17/?

**Comment by vit-corp** [comment]
Hi @msyyc , thanks for your advice but it still doesn`t return required field.

**Comment by msyyc** [comment]
@ChenxiJiang333 Please take an investigation for this issue.

**Comment by ChenxiJiang333** [comment]
> Hi @msyyc , thanks for your advice but it still doesn`t return required field.

Hi, I successfully got the `privateEndpointConnections` with 10.2.0b17 & latest api version, or did you specify another api version?
![image](https://github.com/user-attachments/assets/4e64444f-ca2d-4d4b-9f95-7a20dc9be0ec)

**Comment by ChenxiJiang333** [comment]
Hi, I successfully got the `privateEndpointConnections` with azure-mgmt-rdbms==10.2.0b17 & api version 2024-02-01-preview, 
please check. Or did you specify another api version?
![Screenshot 2024-07-31 102701](https://github.com/user-attachments/assets/c31efb5d-a539-4f7a-ae8b-cb54fa54aced)

**Comment by vit-corp** [comment]
Hi @ChenxiJiang333, thanks for your help, I checked again and this version of API returns "privateEndpointConnections" field.
Thanks all! The issue could be closed.
