### ISSUE TITLE
ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.

### ISSUE THREAD

**Issue by mani3887** [Azure/azure-sdk-for-python#36637]
- **Package Name**: 
- azure-identity==1.17.1
- **Package Version**: 
- azure-identity==1.17.1
- **Operating System**:
- Self managed Kubernetes Cluster
- **Python Version**: 
3.8
**Describe the bug**
We have deployed our application in containers/pods in our self managed K8s clusters running on Ubuntu VMSS. We have enabled managed identity for the storage account resources in these VMSS. We are using the below command to retrieve the credentials:
cred = ManagedIdentityCredential(client_id=os.getenv('managed_identity_client_id'), logging_enable=True)

We have provided permissions for this managed identity to the storage account. Our application is deployed in 32 pods, and uploading 40K+ files in 1-2 hours to storage account(blob storage) and insert in table storage using these creds. For the first hour of this flow, we are able to see the uploads working as intended. But after that, we keep getting this exception:

ImdsCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.

We had also tried using default azure credential after setting the env variable AZURE_CLIENT_ID:
cred = DefaultAzureCredential(logging_enable=True)

At this time, we saw the below errors:
EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
AzureCliCredential: Azure CLI not found on path
AzurePowerShellCredential: PowerShell is not installed
AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.

When we looked into the documentation for environment credential, it suggested that we can use it only with the client secret, which we could not use it with managed identity, so we went only with managed identity credential. 

Can you please let us know how to proceed forward in this case? How does the retry logic work? Is this being handled by the SDK? It looks like it retries but fails after few retries.

**To Reproduce**
1. Deploy 32 pods of this application. Continuously upload 40K+ files in 1-2 hours in azure blob storage.
2. First 40 mins works fine, but after that it throws this error:
ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.

**Expected behavior**
1. Auth should be available at all times; if it fails, it should retry and eventually succeed. Or there should be some kind of handle for the users to retry.

**Comment by xiangyan99** [comment]
Took offline.
