### ISSUE TITLE
Query LROPoller object while invoking commands in Azure VMS separately

### ISSUE THREAD

**Issue by Rahulnigam28** [Azure/azure-sdk-for-python#3666]
I am currently using Azure Python SDK in my project. I have few questions regarding how to get the results of an LROPoller object (virtual_machines.run_command(vmname,resourcegroupname, run_command_parameters)) without polling continuously. I can get the result by doing poller.result(). However, I am trying to pass this LROPoller object to a custom API which will get the result. Is it possible to serialize this object into JSON and then deserialize it back so as to get the result ?

I tried doing this : 

I can get the result from the same function as below
```python
poller = compute.client.virtual_machines.run_command(vmname,resourcegroupname, run_command_parameters)
while  not poller.done() : 
   time.sleep(5)
result = poller.result()
```

But if I try to get the result by passing the dict form of poller to another API and then getting the result it errors out.

```python
y = poller.__dict__
f = LROPoller(y['_client'], y['_response'], y['_callbacks'], y['_polling_method'])
f.status()
```
if I do `f.result()` it gives me an empty value.

Thank You for your time

**Comment by lmazuel** [comment]
Hi @Rahulnigam28 

First, `result` is a blocking call that waits for you, so your `done` loop is not necessary:
```python
poller = compute.client.virtual_machines.run_command(vmname,resourcegroupname, run_command_parameters)
result = poller.result()  # Will be unlocked when done
```

If you want to move this poller to another process, the idea of using `LROPoller` is the right one, but the parameters you pass are not correct:

First do the initial call without polling, and asking the complete raw answer:
```python
poller = compute.client.virtual_machines.run_command(
  vmname,
  resourcegroupname, 
  run_command_parameters, 
  raw=True,
  polling=False
)
raw_response_no_polling = poller.result()  # Will exit instantly with the initial answer as raw HTTP
```

Then, create your poller using these parameters:
```python
from msrestazure.polling.arm_polling import ARMPolling

arm_poller = ARMPolling(
  lro_options={'final-state-via': 'location'}  # Critical for run_command
}

poller = LROPoller(
  compute.client,  # The compute mgmt client
  raw_response_no_polling, # The initial raw response
  RunCommandResult, # The expected return type as Python type
  arm_poller  # The algorithm to use for polling, here it's ARM with location header
)
```

Using `__dict__` here is an interesting idea, however, several things are not ok:
- since you do a "polling=True" call, you create a thread and that's not efficient. At least, pass "polling=False"
- You're using private members, which is not recommended
- You're using `_callbacks` as arg 3, which is incorrect. Arg 3 is a deserialization callback (or a type)
- Polling class is not reentrant, you cannot re-use it in another poller, since state would be incorrect

Hope this helps, let me know if you have additional questions.

Side note: This works only if the SDK is generated with the v3.x generator. Check the ChangeLog for `LROPoller` to know if the package is ready. For compute, it's v4.0.0

**Comment by lmazuel** [comment]
@johanste FYI

**Comment by Rahulnigam28** [comment]
Thank You  so much!

raw_response_no_polling is a msrest.pipeline.ClientRawResponse object,  Can I serialize this ? 

I am running the run_command and then passing the raw_response_no_polling  object as JSON string to another API after 5 minutes so as to get the output.

How can I serialize raw_response_no_polling into JSON string and then deserialize it back to get the poller.result() ?

**Comment by lmazuel** [comment]
@Rahulnigam28 correct, raw_response_no_polling is a msrest.pipeline.ClientRawResponse.

You probably want to actually take "raw_response_no_polling.response", which is a "requests.Response" (LROPoller will take both, not a problem). A "requests.Response" can be [pickled](https://docs.python.org/3.7/library/pickle.html), and then can be sent other the wire to anyone. You might need to encode with base64 the pickle result if you really use JSON to communicate (pickle format  will be binary).

**Comment by Rahulnigam28** [comment]
Thank You ,
I am doing this 
x = poller.response()
x = jsonpickle.encode(poller.response)



At the other end of API deconstructing this back:
poller_string    = base64.b64decode(poller_string64)
no_polling_poller = jsonpickle.decode(poller_string) 
arm_poller = ARMPolling(lro_options={'final-state-via': 'location'})
poller = LROPoller(compute_client,no_polling_poller,RunCommandResult,arm_poller)

It still waits when I do poller.result(0

I was thinking that for commands which take long (> 10 mins ) to run I can call the invoke_runcommand convert  LROPoller to no poller , wait for 10 mins and then on the receiving API , I could deconstruct the object and get no poller result .

Does that mean that on the receiving API everytime I deconstruct poller object back and then run poller.result(), it will run that command again and I have to wait for output ?

**Comment by Rahulnigam28** [comment]
I am getting this error "Unable to find status link for polling" Sorry for multiple comments. I am using azure-mgmt-compute 4.1.1 , How do I know if SDK is generated using v3x generator ? 
Thank You for your help

**Comment by lmazuel** [comment]
The poller is actually just responsible to wait for the long running operation to be done. So recreating the poller will allow you to wait on the operation to be finished, but it won't re-do the initial POST of the run_command. Does this answer your question?

**Comment by Rahulnigam28** [comment]
Yes that answers my question.

You mentioned that  LROPoller object will only work if SDK  is generated with the v3.x generator. Check the ChangeLog for LROPoller to know if the package is ready. For compute, it's v4.0.0

How do I know if I am using v3.x generator

**Comment by lmazuel** [comment]
Looking at the ChangeLog, for instance you will see for compute 4.0.0rc1:
https://pypi.org/project/azure-mgmt-compute/

> This version uses a next-generation code generator that might introduce breaking changes.
> ...
> New Long Running Operation:
>   Return type changes from msrestazure.azure_operation.AzureOperationPoller to msrest.polling.LROPoller. External API is the same.

I pay attention to copy this ChangeLog each time I switched a package to the new system.

If you want to auto-detect it from your Python code, testing the return type is msrest.polling,LROPoller is enough (it wasn't that type before)

**Comment by Rahulnigam28** [comment]
Thank  You,
I have spun a new docker container and was running that command over there but it did not work. I have updated npm and nodejs and installed autorest and it still failed even though the return type was msrest.polling.poller.LROPoller. 


I will look into that and update this thread if I am able to make that command work from my container .


Thank You for your help and time in helping me making this poller object asynchronous
