### ISSUE TITLE
Error when configuring Azure Monitor with ManagedIdentityCredential: Instrumentation Key Validation Fails

### ISSUE THREAD

**Issue by StromFLIX** [Azure/azure-sdk-for-python#36670]
- **Package Name**: `azure-monitor-opentelemetry`
- **Package Version**: `1.5.0`
- **Operating System**: Docker (mcr.microsoft.com/devcontainers/python:3.11) on WSL2 Ubuntu 22.04
- **Python Version**: `3.11.9`

---

**Describe the Bug**  
When calling `configure_azure_monitor` with a `ManagedIdentityCredential`, an error is thrown during the configuration process.

**Code Snippet**
```python
from azure.identity import ManagedIdentityCredential
from azure.monitor.opentelemetry import configure_azure_monitor

configure_azure_monitor(
   credential=ManagedIdentityCredential(),
)
```

**Error Traceback**
```bash
File "/workspaces/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/_configure.py", line 105, in configure_azure_monitor
    _setup_tracing(configurations)
File "/workspaces/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/_configure.py", line 137, in _setup_tracing
  trace_exporter = AzureMonitorTraceExporter(**configurations)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspaces/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/export/_base.py", line 86, in __init__
  parsed_connection_string = ConnectionStringParser(kwargs.get('connection_string'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspaces/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/_connection_string_parser.py", line 39, in __init__
  self._validate_instrumentation_key()
File "/workspaces/.venv/lib/python3.11/site-packages/azure/monitor/opentelemetry/exporter/_connection_string_parser.py", line 84, in _validate_instrumentation_key
  raise ValueError("Instrumentation key cannot be none or empty.")
```

**To Reproduce**
1. Follow the configuration steps as per the [documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-configuration?tabs=python#enable-microsoft-entra-id-formerly-azure-ad-authentication).
2. Execute the provided code snippet.
3. Observe the error.

**Expected Behavior**
The configuration should succeed and use the managed identity without validating a non-existent connection string.

**Additional Context**
The issue seems to come from the base exporter where the connection string validation happens before checking for the existence of credentials:

---

`azure/monitor/opentelemetry/exporter/export/_base.py`
```python
86 parsed_connection_string = ConnectionStringParser(kwargs.get('connection_string'))
87 
88 self._api_version = kwargs.get('api_version') or _SERVICE_API_LATEST
89 self._credential = kwargs.get('credential')
```

---

This validation logic should be adjusted to account for scenarios where credentials are provided directly, bypassing the need for a connection string.

**Comment by lzchen** [comment]
@StromFLIX 

Thanks for reporting this. The docs are actually incorrect in this regard. You still need to pass in a connection string to identify what resource you are sending telemetry to. We will update the docs accordingly thanks.

**Comment by StromFLIX** [comment]
@lzchen I also need to pass in the instrumentation key as part of the connection string or can i use a placeholder there to make better use of the managed identity ?

**Comment by lzchen** [comment]
@StromFLIX 

You need to pass in a valid connection string as a whole like normal. The managed identity and connection string serve different purposes.

**Comment by spygi** [comment]
Can you expand on this @lzchen ?

> The managed identity and connection string serve different purposes.

We were looking on using managed identities as a way to be "secret-less" but if we have to pass the connection string anyway, I don't see what benefit we get by switching to managed identities.

**Comment by lzchen** [comment]
@spygi 

The connection string is used to specify WHERE to send your data to. More specifically it needs to contain resource identification (via instrumentation key) and ingestion endpoint. The managed identity is only used for authentication. You create an identity that is authorized to send data to that specific resource. See [this doc](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) for more details. Just a note that the credentials themselves don't have information about the resource so it is not a viable replacement for the instrumentation key.

**Comment by spygi** [comment]
Thank you for the clarification @lzchen! 

Interesting that the instrumentation key is needed to identify the resource. In the connection string there is also an applicationId. I thought the purpose of this is to identify the resource, can you clarify in that case what it's needed for?

**Comment by dburik** [comment]
As far as I understand this: if we want to use managed identity (or any Entra service principal) authentication in App Insights, we need to disable the so called "local authentication" (see screenshot). Once this is disabled, you cannot just use connection string to ingest telemetry, but each request must be authenticated with a service principal (e.g., managed identity). The identity must have the `Monitoring Metrics Publisher` role assigned on the scope of App Insights instance.

@lzchen is correct assumption? Is this scenario is supported by the `azure-monitor-opentelemetry` package?

See this docs for more information: [Microsoft Entra authentication for Application Insights](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?WT.mc_id=Portal-AppInsightsExtension&tabs=net)

![image](https://github.com/user-attachments/assets/660ebbf9-56be-4fb3-8e2f-988afd4f6d00)

**Comment by lzchen** [comment]
> can you confirm this is a correct assumption? Is this scenario supported by the azure-monitor-opentelemetry package?

This is correct and is supported. 

@spygi 

> Interesting that the instrumentation key is needed to identify the resource. In the connection string there is also an applicationId. I thought the purpose of this is to identify the resource, can you clarify in that case what it's needed for?

ApplicationId is not used at all by the `azure-monitor-opentelemetry` package. Only `instrumentation_key` is used to identify resource.
