### ISSUE TITLE
Looking for change default path with custom path when running job for input data

### ISSUE THREAD

**Issue by arpitjivanitecan** [Azure/azure-sdk-for-python#36689]
Hello I want to set some specific path for my dataset while training custom job on compute instance like **"/workspace/dataset"** but right now I am getting default path for dataset like **"/mnt/azureml/cr/j/39098fe075cf4b97a87bf1c855cb67b4/cap/data-capability/wd/INPUT_data"** if you can integrate this feature in your python sdk or if this feature already there then please send me documentation link.

**Comment by achauhan-scc** [comment]
created an internal work item to triage.
