### ISSUE TITLE
[FEATURE REQ] Migrate Dev Tools credentials to use Msal callbacks

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-python#36683]
To optimize code flows in pipelines and development environments, migrate the following credentials to use MSAL callbacks and leverage MSAL caching:

Azure PowerShell credential
Azure CLI credential
Azure Developer CLI credential
This migration will enhance performance by utilizing the MSAL cache to retrieve tokens, reducing the need to fetch a new token from the respective development tool for each request.

**Comment by joshfree** [comment]
Discussed in office hours will close out these issues for the time being (we may revisit this in the future with a slightly different design / opt-in mechanism).
