### ISSUE TITLE
send_certificate_chain/SNI auth missing from aio.CertificateCredential 

### ISSUE THREAD

**Issue by daviddavis** [Azure/azure-sdk-for-python#36693]
**Is your feature request related to a problem? Please describe.**
The regular (sync) CertificateCredential  has the support for Subject Name/Issuer (SNI) authentication via a [send_certificate_chain option](https://github.com/Azure/azure-sdk-for-python/blob/2bf9936e20f504246a7fd69c21dc7a2bf9d8707b/sdk/identity/azure-identity/azure/identity/_credentials/certificate.py#L37-L39) but this appears to be missing from the async CertificateCredential class. There's no `send_certificate_chain` or SNI option for [aio.ClientCertificate](https://github.com/Azure/azure-sdk-for-python/blob/2bf9936e20f504246a7fd69c21dc7a2bf9d8707b/sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py#L14).

**Describe the solution you'd like**
SNI auth for aio.CertificateCredential.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

We don't have async support for SNI certificate. https://github.com/Azure/azure-sdk-for-python/issues/13349

Please use sync one as a work around.

**Comment by daviddavis** [comment]
@xiangyan99 thank you for the response. Will the sync credential work with async clients? Pylance seems to raise an error. Can I safely ignore this?

```
error: Argument of type "DefaultAzureCredential" cannot be assigned to parameter "credential" of type "AsyncTokenCredential" in function "__init__"
    "DefaultAzureCredential" is incompatible with protocol "AsyncTokenCredential"
      "__aexit__" is not present
      "__aenter__" is not present
        "get_token" is an incompatible type
          Type "(*scopes: str, claims: str | None = None, tenant_id: str | None = None, **kwargs: Any) -> AccessToken" is incompatible with type "(*scopes: str, claims: str | None = None, tenant_id: str | None = None, enable_cae: bool = False, **kwargs: Any) -> Coroutine[Any, Any, AccessToken]"
            Function return type "AccessToken" is incompatible with type "Coroutine[Any, Any, AccessToken]"
        "close" is an incompatible type
          Type "() -> None" is incompatible with type "() -> Coroutine[Any, Any, None]"
    ... (reportArgumentType)
```

**Comment by xiangyan99** [comment]
Here is an example: https://gist.github.com/xiangyan99/79004beae47179f8b17bf5bc61b3fc62
