### ISSUE TITLE
Programmatically generate the consent code  for credential manager for APIM 

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [Azure/azure-sdk-for-python#36697]
**Is your feature request related to a problem? Please describe.**
Is there a way to programmatically generate the consent code? There is an SDK to confirm once the user visits the page.
Link to the page: https://learn.microsoft.com/en-us/rest/api/apimanagement/authorization/confirm-consent-code?view=rest-apimanagement-2022-08-01&tabs=Python

`client. authorization.confirm_consent_code(
        resource_group_name="rg1",
        service_name="apimService1",
        authorization_provider_id="oauthcode",
        authorization_id="authz1",
        parameters={"consentCode": "theconsentcode"},
    )`

**Describe the solution you'd like**
We are looking for—a way for users to skip consent without leaving our site. Our site is already configured as an OAuth provider to the credential manager. 

**Additional context**
We want to avoid the screen when authorizing credential managers and using the authorization code method.

![image](https://github.com/user-attachments/assets/8851342a-90b5-4273-985f-b729ad0cc522)

**Comment by sanjaydatasciencedojo** [comment]
Any update on this? This has been block for us.

**Comment by msyyc** [comment]
@ChenxiJiang333 Please help on this issue

**Comment by ChenxiJiang333** [comment]
Hi @sanjaydatasciencedojo, do you mean you are looking for an API/SDK method that to generate a consent code that can be used by users to get authorized to access your site without manually approval? As far as I know, such API does not exist. Yet since we are not a domain expert to this service, it's suggested to transfer the issue to https://github.com/Azure/azure-rest-api-specs/issues to get the answer from service team.

**Comment by sanjaydatasciencedojo** [comment]
Yes. We are looking for a way to create an attended scenario where users don't have to leave our site and authorize. In the Microsoft page for consent, thank you for your help.

**Comment by xiangyan99** [comment]
We need service support for the request. Please open issues in https://github.com/Azure/azure-rest-api-specs/issues repo.
