### ISSUE TITLE
[DI] Convert JSON to AnalyzeResult

### ISSUE THREAD

**Issue by ngocntp** [Azure/azure-sdk-for-python#36691]
I use Document Intelligence Service to get content of pdf files and convert it (AnalyzeResult) to JSON by using the following code:
`
result: AnalyzeResult = poller.result()
result_dict = result.as_dict()
with open(json_path, "w") as output_file:
    json.dump(result_dict, output_file, ensure_ascii=False, indent=3)
`
Now I want to load result_dict from json_path and convert it to AnalyzeResult. How should I do it?

**Comment by kashifkhan** [comment]
Hi @ngocntp , you can use `from_dict` in `AnalyzeResult` to do that 

https://learn.microsoft.com/en-us/python/api/azure-ai-formrecognizer/azure.ai.formrecognizer.analyzeresult?view=azure-python#azure-ai-formrecognizer-analyzeresult-from-dict

```python

with open("some path", "r") as input:
    result_dict = json.load(input_file)

result = AnalyzeResult.from_dict(result_dict)

```
