### ISSUE TITLE
AML SDK v2 - Unable to create AML workspace with storage from different subscription

### ISSUE THREAD

**Issue by iyangchen** [Azure/azure-sdk-for-python#36735]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. Create AML workspace using existing storage from different subscription doesn't work, it will try to replace storage subscription with the workspace subscription, and result in Not Found error.
![image](https://github.com/user-attachments/assets/05936d5c-e6f5-417d-a144-a3634421caff)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by achauhan-scc** [comment]
capability was added 1.21.0 onwards
