### ISSUE TITLE
azure.mgmt.web.WebSiteManagementClient.web_apps.create_or_update doesn't validate function app name.

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#3673]
create_or_update needs to validate if provided name is valid or not. E.g. underscore is not allowed and you can see it via the portal.

This method sendsa request, response contains 400: Bad request with no details. Hard to guess the issue.

**Comment by lmazuel** [comment]
Hi @logachev 
That's a good point, I created an issue in our RestAPI description repo to ask for this update. Once the JSON description of the service will be updated, all SDK (not only Python) will check for the validity of the name.
Thanks for the report!
