### ISSUE TITLE
[breaking change detector] doesn't work well for multiapi package of Mgmt SDK

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#36755]
For multiapi package of Mgmt SDK, current breaking change detector doesn't work well. For example:

(1) azure-mgmt-eventhub of PR https://github.com/Azure/azure-sdk-for-python/pull/36724
- chagnelog from detector
![image](https://github.com/user-attachments/assets/de174efc-0404-45c4-9efb-14edfb8751fd)

- changelog from old tool
![image](https://github.com/user-attachments/assets/8a3f509e-47c9-42c2-8843-b7f399174623)

(2) azure-mgmt-compute of https://github.com/Azure/azure-sdk-for-python/pull/36725

- changelog from dector is empty
![image](https://github.com/user-attachments/assets/c71cc2b1-3a21-4dc2-a1b8-e0fc57dcc3e6)

- changelog from old tool
![image](https://github.com/user-attachments/assets/346385e4-1620-4bf9-9110-6b2e2b4fdbc6)

FYI: old changelog tool will generate code report for each api-version, then merge these code report into one, then generate changelog.

**Comment by catalinaperalta** [comment]
@msyyc I looked into this and the code report is reporting on all modules....however not incrementally as you mentioned that the old tool did. How was the "merge" performed in the old tool? Was the latest version only merged on top of the last version? Or do we need to merge all module version? And is there any value in that? Seems like merging with the last version should be enough to get the changes listed.

**Comment by catalinaperalta** [comment]
Could we compare the latest version against the last data based version?

**Comment by msyyc** [comment]
old tool will generate report for each api-versin subfolder then [merge](https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-sdk-tools/packaging_tools/code_report.py#L205) these reports. The merge logic is that sort the subfolder then update them one by one. So the latest api-version wins while some types that only exists in older api-version are still kept.



> @msyyc I looked into this and the code report is reporting on all modules....however not incrementally as you mentioned that the old tool did. How was the "merge" performed in the old tool? Was the latest version merged on top of the last version released (preview or stable)? Or do we need to merge all module versions? And is there any value in that? Seems like merging with the last version should be enough to get the changes listed.

**Comment by catalinaperalta** [comment]
Got it, I'll work on a way to do this in the new tool. Thanks for the info
