### ISSUE TITLE
AzureCliCredential can't be imported

### ISSUE THREAD

**Issue by CaishenNefri** [Azure/azure-sdk-for-python#36778]
- **Package Name**: azure-identity
- **Package Version**: 1.17.1
- **Operating System**: 20.04.6 LTS (Focal Fossa)
- **Python Version**:  3.11.9

**Describe the bug**
I am trying to use AzureCliCredential but I am getting following error. 

```bash
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from azure.identity import AzureCliCredential
ImportError: cannot import name 'AzureCliCredential' from 'azure.identity' (/usr/lib/python3/dist-packages/azure/identity/__init__.py)
```

**To Reproduce**
1. Create `main.py` file
2. Insert following code
```python
from azure.identity import AzureCliCredential
token_credential = AzureCliCredential()
```
3. Save & Run python script: `python3.11 main.py`

**Expected behavior**
I should be able to import AzureCliCredential

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Unfortunately, I cannot repro the issue.

Have you tried creating a new virtual environment and install azure-identity?

**Comment by CaishenNefri** [comment]
You are right. Sorry for such a nooby problem.
