### ISSUE TITLE
Need instructions for enabling diagnostic settings for Entra ID using MonitorManagementClient from azure.mgmt.monitor.

### ISSUE THREAD

**Issue by Shantanudevil** [Azure/azure-sdk-for-python#36776]
### Type of issue

Code doesn't work

### Description

I am willing to enable diagnostic settings for Entra ID & forward those logs to an EventHub. However, the existing code available on the internet is not functional. 

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-mgmt-monitor/azure.mgmt.monitor.monitormanagementclient?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-monitor/azure.mgmt.monitor.MonitorManagementClient.yml

### Document Version Independent Id

ee43dd9e-a405-9abb-eda9-9d2fc6494066

### Article author

@lmazuel

### Metadata

* ID: 2e99e12f-3e80-f021-9ad8-2279a4458b2d 
* Service: **monitoring-alert**

**Comment by pvaneck** [comment]
Hey @Shantanudevil, do you mind providing a code snippet along with what errors you are encountering using the `azure-mgmt-monitor` library?

**Comment by msyyc** [comment]
Add @ChenxiJiang333 for help

**Comment by Shantanudevil** [comment]
@pvaneck - I am not able to understand what to pass as resource URI for Entra ID diagnostic settings available, additionally defining the log categories that needs to be enabled.

Below is the attached snip of code which is used for enabling diagnostic settings for subscription.

![image](https://github.com/user-attachments/assets/391f58d6-92f1-46bc-852f-2c8239edd80b)

**Comment by Shantanudevil** [comment]
@pvaneck / @msyyc / @ChenxiJiang333 any promt help on this would be really appreciated.

**Comment by ChenxiJiang333** [comment]
> @pvaneck - I am not able to understand what to pass as resource URI for Entra ID diagnostic settings available, additionally defining the log categories that needs to be enabled.
> 
> Below is the attached snip of code which is used for enabling diagnostic settings for subscription.
> 
> ![image](https://private-user-images.githubusercontent.com/43336357/355703131-391f58d6-92f1-46bc-852f-2c8239edd80b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjExODQsIm5iZiI6MTcyMzAyMDg4NCwicGF0aCI6Ii80MzMzNjM1Ny8zNTU3MDMxMzEtMzkxZjU4ZDYtOTJmMS00NmJjLTg1MmYtMmM4MjM5ZWRkODBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA4NTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2N2QyMTgzODczYzU0NGJiYzEzNmRlNTc3OWE5MDEwZjIzNjc2ZGI1MGY2Zjk2ZWQ1MDVmMjEzOTIxMTBmNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjsEB2AOlFlHGWLDtjQvUXDwce3LBCnZDF_ay4jjZ-s)

Hi, not sure whether such operation can be done in a tenant scope, maybe you can try pass the `resource_uri` with `/tenants/<TENANT ID>/providers/Microsoft.aadiam`.

**Comment by Shantanudevil** [comment]
@ChenxiJiang333 - it's not working throwing below error - 

![image](https://github.com/user-attachments/assets/5801c0f6-4f1d-48fc-a977-faad01253e9d)


Parameters - 

![image](https://github.com/user-attachments/assets/e0c792de-c346-4d44-807a-ffaa135c5667)


Would you please be able to let me know the correct syntax / function code to enable diagnostic settings with a category of logs being forwarded to an EventHub? as I have been performing guesswork for a long time now, with no success.

**Comment by pvaneck** [comment]
I believe for Azure Monitor, diagnostics settings can only be applied to specific resources and not the subscription itself. Resource URIs (also known as Resource IDs) are of the format: 

```
/subscriptions/{guid}/resourceGroups/{resource-group-name}/{resource-provider-namespace}/{resource-type}/{resource-name}`
```

You'll likely have to apply diagnostic settings to each resource of interest.

A sample I found for this specific method is [here](https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/monitor/disable_manage_diagnostic_setting.py#L178), which may help.

If you need to find a list of resources in a subscription, then you can use the `azure-mgmt-resource` package:

```python
from azure.identity import DefaultAzureCredential
from azure.mgmt.resource import ResourceManagementClient

subscription_id = 'your-subscription-id'
credential = DefaultAzureCredential()
resource_client = ResourceManagementClient(credential, subscription_id)

# List all resources in the subscription
resources = resource_client.resources.list()

for resource in resources:
    # Do something with resource.id
```

Let me know if this helps.

@ChenxiJiang333, I think it would be nice to update the `resource_uri` docstring to include the expected format similar to: https://learn.microsoft.com/en-us/rest/api/resources/resources/get-by-id?view=rest-resources-2021-04-01#uri-parameters

**Comment by ChenxiJiang333** [comment]
> I believe for Azure Monitor, diagnostics settings can only be applied to specific resources and not the subscription itself. Resource URIs (also known as Resource IDs) are of the format:
> 
> ```
> /subscriptions/{guid}/resourceGroups/{resource-group-name}/{resource-provider-namespace}/{resource-type}/{resource-name}`
> ```
> 
> You'll likely have to apply diagnostic settings to each resource of interest.
> 
> A sample I found for this specific method is [here](https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/monitor/disable_manage_diagnostic_setting.py#L178), which may help.
> 
> If you need to find a list of resources in a subscription, then you can use the `azure-mgmt-resource` package:
> 
> ```python
> from azure.identity import DefaultAzureCredential
> from azure.mgmt.resource import ResourceManagementClient
> 
> subscription_id = 'your-subscription-id'
> credential = DefaultAzureCredential()
> resource_client = ResourceManagementClient(credential, subscription_id)
> 
> # List all resources in the subscription
> resources = resource_client.resources.list()
> 
> for resource in resources:
>     # Do something with resource.id
> ```
> 
> Let me know if this helps.
> 
> @ChenxiJiang333, I think it would be nice to update the `resource_uri` docstring to include the expected format similar to: https://learn.microsoft.com/en-us/rest/api/resources/resources/get-by-id?view=rest-resources-2021-04-01#uri-parameters

The docstring was defined in swagger, has opened an issue to report it.
https://github.com/Azure/azure-rest-api-specs/issues/30116

**Comment by Shantanudevil** [comment]
Hi @ChenxiJiang333 ,

I want to enable diagnostic settings for Entra Tenant instead of a specific resource with the requirement being a certain category of logs would be forwarded to an EventHub. Hope I am clear on the requirements.

**Comment by Shantanudevil** [comment]
@msyyc / @ChenxiJiang333 / @msyyc **any prompt help on this would be really appreciated.**

**Comment by Shantanudevil** [comment]
Any help? ＞﹏＜ @pvaneck / @msyyc / @ChenxiJiang333

**Comment by pvaneck** [comment]
Hey, sorry. I'm not really all that familiar with this SDK, so my knowledge is very limited here, and unfortunately, I don't currently have the means to test tenant-level operations.

I did find this issue: https://github.com/Azure/azure-sdk-for-python/issues/18476 which seems to indicate that this scenario isn't supported, and instead, a user has to send REST requests manually to the `https://management.azure.com/providers/microsoft.aadiam/diagnosticSettings/` endpoint.

I see some blogs showcasing this usage like [here](https://rozemuller.com/monitor-conditional-access-changes-using-openai-and-teams/) and [here](https://stackoverflow.com/questions/53666223/azure-permissions-over-microsoft-aadiam-diagnosticsettings-write).

@ChenxiJiang333 @msyyc Do you happen to know any more about a client for these tenant-level diagnostic settings management operations?

**Comment by msyyc** [comment]
SDK is generated with swagger but I am not from service team so don't have enough domain knowledge about specific usage scenario of specific azure service. @Shantanudevil I advise you open an issue in https://github.com/Azure/azure-rest-api-specs/issues to seek help from service team about whether there is REST API for your required scenario. Once you find the REST API, we could help you find the related SDK API.

**Comment by Shantanudevil** [comment]
Hi @msyyc - I can see a related issue already opened - https://github.com/Azure/azure-rest-api-specs/issues/11085. Wehre they have mentioned the rest API available i.e., - PUT /providers/microsoft.aadiam/diagnosticSettings/testDiagSetting?api-version=2017-04-01.

Would request you to please let me know the related SDK for this.

**Comment by msyyc** [comment]
It is never released as SDK API. Since SDK team only release SDK when service team asks, I will contact service team whether this REST API could be released with SDK.

**Comment by Shantanudevil** [comment]
yeah, it is working for us as of now. It would be really great if a SDK can be released as we are willing to stick to the python SDK instead of using request library with REST Api. 

Additionally, is there any expected ETA or time delay for the release of SDK ?

**Comment by Shantanudevil** [comment]
Hi @msyyc - any update on this ?

**Comment by msyyc** [comment]
Let me contact service team and will update later

**Comment by Shantanudevil** [comment]
Apologies @msyyc, I am really not sure if Microsoft Graph is really relevant here i.e., **For Diagnostic settings for Entra tenant**. 

Additionally, I do not find -  https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azureactivedirectory/resource-manager helpful.
Would you be able to share a code snippet example? or import statements with the specific function to enable the same?

**Comment by msyyc** [comment]
![image](https://github.com/user-attachments/assets/aacab02c-ce77-4e2a-8543-3eae7d74bf5d)
This rest API is defined in https://github.com/Azure/azure-rest-api-specs/blob/48dcf5d28914f6d5ba2d66aa1689241b29bac49d/specification/azureactivedirectory/resource-manager/Microsoft.Aadiam/stable/2017-04-01/azureactivedirectory.json#L106-L183. However this folder is not updated for years and I can't find member of service team to confirm whether this API is still recommended to use.

**Comment by Shantanudevil** [comment]
@msyyc - would you please be able to confirm on the way ahead on this? or whom should I reach out to ?

**Comment by msyyc** [comment]
I advise you open an issue in https://github.com/Azure/azure-rest-api-specs/issues to confirm whether https://github.com/Azure/azure-rest-api-specs/blob/48dcf5d28914f6d5ba2d66aa1689241b29bac49d/specification/azureactivedirectory/resource-manager/Microsoft.Aadiam/stable/2017-04-01/azureactivedirectory.json is still maintained. If there is comment from a member of service team, we can contact them to release SDK if possible

**Comment by Kaloszer** [comment]
@msyyc this is already there and not touched by anyone for ages now
https://github.com/Azure/azure-rest-api-specs/issues/11085

**Comment by msyyc** [comment]
It proves that this service may be not maintained actively so SDK team won't release SDK for it. I am afraid you have to find another service to replace it.

**Comment by Kaloszer** [comment]
@msyyc I mean, it's used in the `Azure Entra` Data Connector in `Microsoft Sentinel` which is a `Microsoft` solution connector, so it's not like I can look for another service to replace it 🤣.

**Comment by msyyc** [comment]
Is it possible to use private package? Since our SDK is also generated from swagger with codegen tool, the content of public SDK actually same with private package. And here is the guidance of how to get private package by yourself: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/private_package/get_private_package.md
