### ISSUE TITLE
Request Assistance for Providing Azure Storage Cost Recommendations via Azure SDK for Python or RestApi.

### ISSUE THREAD

**Issue by lokesh190496** [Azure/azure-sdk-for-python#36772]
@osake , @notlaforge , @archerzz **I need guidance on how to provide cost recommendations for Azure Storage using the Azure SDK for Python or RESTAPI. Specifically, I am looking for help with:

1. Fetching storage account details, including total and used capacity.
2. Applying cost optimization strategies such as tier optimization, changing redundancy settings, implementing lifecycle management policies, and recommending reserved capacity.**

**Comment by msyyc** [comment]
Add @ChenxiJiang333 for help

**Comment by lokesh190496** [comment]
> @osake , @notlaforge , @archerzz **I need guidance on how to provide cost recommendations for Azure Storage using the Azure SDK for Python or RESTAPI. Specifically, I am looking for help with:
> 
>     1. Fetching storage account details, including total and used capacity.
> 
>     2. Applying cost optimization strategies such as tier optimization, changing redundancy settings, implementing lifecycle management policies, and recommending reserved capacity.**



> Add @ChenxiJiang333 for help

**Comment by lokesh190496** [comment]
> Add @ChenxiJiang333 for help

sure.

**Comment by lokesh190496** [comment]
@ChenxiJiang333 , I need guidance on how to provide cost recommendations for Azure Storage using the Azure SDK for Python or RESTAPI. Specifically, I am looking for help with:

    Fetching storage account details, including total and used capacity.
    Applying cost optimization strategies such as tier optimization, changing redundancy settings, implementing lifecycle management policies, and recommending reserved capacity.**

**Comment by ChenxiJiang333** [comment]
Hi @lokesh190496 
To get storage account details, you can follow this sample: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-mgmt-storage/generated_samples/storage_account_get_properties.py
To update storage account settings, see reference: https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/update?view=rest-storagerp-2023-05-01&tabs=Python
To set lifecycle management policies, see: https://learn.microsoft.com/en-us/rest/api/storagerp/management-policies/create-or-update?view=rest-storagerp-2023-05-01&tabs=HTTP

Yet to get a reserved capacity, I guess you can only do it through the portal: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-reserved-capacity#purchase-azure-storage-reserved-capacity

**Comment by lokesh190496** [comment]
> Hi @lokesh190496 To get storage account details, you can follow this sample: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-mgmt-storage/generated_samples/storage_account_get_properties.py To update storage account settings, see reference: https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/update?view=rest-storagerp-2023-05-01&tabs=Python To set lifecycle management policies, see: https://learn.microsoft.com/en-us/rest/api/storagerp/management-policies/create-or-update?view=rest-storagerp-2023-05-01&tabs=HTTP
> 
> Yet to get a reserved capacity, I guess you can only do it through the portal: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-reserved-capacity#purchase-azure-storage-reserved-capacity

My request it is possible to give recommendations.

**Comment by ChenxiJiang333** [comment]
Hi @lokesh190496, about recommendations, is that mean you want us to provide a suggested configuration for your storage account resource? As we are not domain expert to give the recommendations, please raise a help ticket on Azurite portal to get help from related team: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header.
