### ISSUE TITLE
Breaking Changes check is failing unexpectedly

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#36784]
On more than a few pipelines.

[Here is a kusto query](https://dataexplorer.azure.com/clusters/azsdkengsys.westus2/databases/Pipelines?query=H4sIAAAAAAAAA6WQTWvDMAyG7%2F0VwqcEQnMsFLKyrBQC2cdh96HEmuOttost7yPsxy9eaFe2Y3UQ0ivpfUB11HvZOtVqS4sveB%2FIEzxqQ4HRHOAKULlsJfPT7JZCQEUwYADRecJXbdUadtdNK6Yl%2BmCycgFT1Mm6Cux75EwMzIewLktJb0sco6dl70wpCrj3Cq0ekbWzd2ioAJHkB%2B9eqOdGpv6pS16lpxD3HDY%2FXSOraa2ey7z4RW7pWVud7C6FH5UZv5En4zP29kxMXwrRGPR6JLhx0XLVp5zl0H0eX%2FfvcMb8Eb8B85OQtpkBAAA%3D) that shows all the failures and which pipelines are affected.

Need to dig in and identify a resolution.

**Comment by msyyc** [comment]
Recently I adopted breaking change detector in https://github.com/Azure/azure-sdk-for-python/pull/36601 however it blocks release. Then I find we could skip it by set `Skip.BreakingChanges` when running release pipeline https://github.com/Azure/azure-sdk-for-python/issues/36370#issuecomment-2232215460. I don't expect it blocks CI of other data-plane packages... 
Thanks @scbedd for the fix and I think add `breaking=false` in pyproject.toml is better way and I will add it for all mgmt packages to avoid similar issues.

**Comment by scbedd** [comment]
Yep agree with your assessment. Thanks @msyyc !
