### ISSUE TITLE
VMs created from captured image retain old hostname

### ISSUE THREAD

**Issue by kobybecker** [Azure/azure-sdk-for-python#368]
Windows VMs created from a captured VM image retain the old hostname, even when using the servicemanagementservice.add_role() api and passing a valid computer_name. 

The label on the Azure Management portal is updated, but the hostname remains the same.

**Comment by huguesv** [comment]
Is this for a generalized image?  Did you sysprep it before calling capture_vm_image?  If not, I would try that.

Also, are you implying that for the same vm image, create_virtual_machine_deployment will set the hostname, but not add_role?

**Comment by kobybecker** [comment]
Thanks for the quick response! Basically, I captured a vm image manually from the management portal using the steps mentioned here - http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-capture-image-windows-server/

This includes sysprepping, so the image is 'generalized' I guess.

Then I create a cloud service, use the create_virtual_machine_deployment and add_role APIs. But all of the VMs using these APIs, I end up getting the (same) hostname of the original VM that I captured to create the image. In summary, all the 30 VMs I created got the same hostname.

Is this expected? I'm thinking this might be either an issue with the API something to do with the image itself, and the way I sysprep it. I am able to repro this, and will be happy to share a gist of the code.

**Comment by huguesv** [comment]
I followed the instructions in the link above to capture a VM.

![capture](https://cloud.githubusercontent.com/assets/1696845/7823580/538ce788-03b1-11e5-9eee-a6f071358276.png)

This deletes my original VM, which was named 'huguesvpython'.

Then I created a new VM with the following code.  Notice my naming convention 'hvmm' for cloud service name + vm name:
```
from azure.servicemanagement import *

sms = ServiceManagementService(
    subscription_id='<censored>',
    cert_file='<censored>',
)

image_name = 'huguesvpython-20150526-169874'
service_name = 'hvmmcs'
name = 'hvmmvm1'
location = 'West US'

result = sms.create_hosted_service(
    service_name,
    service_name + 'label',
    service_name + 'description',
    location,
)

sms.wait_for_operation_status(result.request_id, timeout=100)

windows_config = WindowsConfigurationSet(name, '<censored>', False, False, 'Pacific Standard Time', 'azureuser')
windows_config.domain_join = None
windows_config.win_rm = None

result = sms.create_virtual_machine_deployment(
    service_name,
    name,
    'production',
    name + 'label',
    name,
    system_config=windows_config,
    os_virtual_hard_disk=None,
    vm_image_name=image_name,
)

sms.wait_for_operation_status(result.request_id, timeout=100)
```

The portal shows the correct names:

![dashboard](https://cloud.githubusercontent.com/assets/1696845/7823631/b8040ab6-03b1-11e5-9938-8b3b03075320.png)

After I add an endpoint to remote connect to the machine, I log on to see the correct computer name:

![computer_name](https://cloud.githubusercontent.com/assets/1696845/7823645/d58b51fc-03b1-11e5-860b-ff09db57df6e.png)

**Comment by kobybecker** [comment]
Thanks @huguesv!! Your response is much appreciated. ! I tried the same steps with a vanilla windows server image as you pointed out, and the host names are getting populated correctly. 

But I'm also able to reproduce my original issue using an existing VM with some installed applications, that I sysprep'ed to capture as image. When I create VMs using this particular image, the old host-name is getting retained. The image is a 'Generalized' image and not a specialized one. Now I thought this is some issue with the way I'm creating the image, but I'm able to reliably reproduce this. So I think this is a bug at the server side, and not with the SDK. Is there anyway I can contact the team that owns VM provisioning at Azure?

**Comment by huguesv** [comment]
I sent an email to a product manager and pointed him to this issue.  I was going to suggest you post on the azure support forum, but I see you've already done that:
https://social.msdn.microsoft.com/Forums/azure/en-US/174d3092-7854-40f0-ae48-03dd0915ce03/vm-created-out-of-a-sysprep-image-keeps-the-same-hostname?forum=WAVirtualMachinesforWindows

**Comment by kobybecker** [comment]
![image](https://cloud.githubusercontent.com/assets/11913834/7825665/88dec060-03c4-11e5-9fe6-85a8535af997.png)

You are Awesome

**Comment by kobybecker** [comment]
If the PM is looking at this, Dear PM - this is the possible root cause: There is a bug with sysprep when it's done multiple times on the same image.

I follow this process:

1. Create a VM from any Windows Server image.
2. Sysprep and Capture Image as 'img01'
3. Create new VM from Image 'img01'.
4. Sysprep and Capture again - repeat this process 2 more times.

Any VM created this way will retain the same hostname.

Why would I do such a crazy thing you ask? Because when I capture image, the original VM is destroyed, so I want to keep making changes to whatever VMs I have (these VMs could have undergone the capture process multiple times).

**Comment by huguesv** [comment]
Closing as external, it's unlikely we can do anything from the SDK to help with this.
