### ISSUE TITLE
Keep getting speechsdk.ResultReason.NoMatch error with USB microphone on Raspberry Pi

### ISSUE THREAD

**Issue by rivendell1984** [Azure/azure-sdk-for-python#36820]
I am using a USB microphone on a Raspberry Pi and following the Azure Cognitive Services speech recognition sample code in Python from GitHub:

[speech_sample.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py)

```
...
    result = speech_recognizer.recognize_once()

    # Check the result
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized")

...
```

I haven't spoken, but it keeps returning the `speechsdk.ResultReason.NoMatch` error instead of recognizing speech:

```
SpeechRecognitionResult(result_id=787567342c65413589efb200b6fbf086, text="", reason=ResultReason.NoMatch)
```

It always interrupts the speech recognition, how can I get it to return recognized speech instead of the NoMatch error?

**Comment by kristapratico** [comment]
@rivendell1984 apologize for the late reply, the speech SDK does not reside in this repo. Please move your issue to this repo: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues where the maintainers of the library will be able to help. Thanks!

**Comment by rivendell1984** [comment]
> @rivendell1984 apologize for the late reply, the speech SDK does not reside in this repo. Please move your issue to this repo: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues where the maintainers of the library will be able to help. Thanks!

Thanks a lot for your reply, I'll close this issue.
