### ISSUE TITLE
ImportError: cannot import name 'AzureOpenAIParameters' from 'azure.search.documents.indexes.models'

### ISSUE THREAD

**Issue by TaisukeIto** [Azure/azure-sdk-for-python#36832]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. ImportError: cannot import name 'AzureOpenAIParameters' from 'azure.search.documents.indexes.models' 
ImportError
cannot import name 'AzureOpenAIParameters' from 'azure.search.documents.indexes.models' (/home/taisukeito/.venv/lib/python3.12/site-packages/azure/search/documents/indexes/models/__init__.py)
  File "/home/taisukeito/20240809_azure-search-vector-samples/demo-python/code/basic-vector-workflow/azure-search-vector-python-sample.py", line 68, in <module>
    from azure.search.documents.indexes.models import (
ImportError: cannot import name 'AzureOpenAIParameters' from 'azure.search.documents.indexes.models' (/home/taisukeito/.venv/lib/python3.12/site-packages/azure/search/documents/indexes/models/__init__.py)

**Expected behavior**

**Screenshots**
![error](https://github.com/user-attachments/assets/e3c28aef-fa41-4931-b559-acf3d11f0ce2)

**Additional context**

pip install azure-search-documents 11.6.0b4

azure-search-vector-samples\demo-python\code\basic-vector-workflow\azure-search-vector-python-sample.ipynb

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Unfortunately, I cannot repro the issue.

Could you try create a new virtual environment and install the package again?

**Comment by wyunchi-ms** [comment]
I meet the same problem:
* OS: Win11
* Python version: 3.12.4
* Package version: azure_search_documents-11.5.1-py3-none-any.whl

**Comment by wyunchi-ms** [comment]
I raised a PR: https://github.com/Azure/azure-search-vector-samples/pull/264 to fix this
