### ISSUE TITLE
which program will work?　（Program which can upload a text file to vector index of Azure AI search ）

### ISSUE THREAD

**Issue by TaisukeIto** [Azure/azure-sdk-for-python#36833]
I'm looking for a basic python program that will upload a text file to the vector index of Azure AI search, but
everything gives me an error, and I can't find the version number of the azure search documents package or a working ptyhon program anywhere.
Everything gives me an error.
I guess it's probably because the development is so hard that they haven't been able to check the operation of the developed program, but which program will work?

GitHub
Azure/azure-search-vector-samples
Azure/azure-sdk-for-python

**Comment by rohit-ganguly** [comment]
Hi @TaisukeIto! Sorry to hear about your experience with the AI Search library - it's a rapidly growing service so sometimes the API changes on newer versions and samples become outdated fast. 

One of our most popular samples uses the AI Search library and should have accurate behavior - here's what I found for a quick search of the `SearchClient.upload_files()` method: [link](https://github.com/Azure-Samples/azure-search-openai-demo/blob/55b0961b98bf22b44fc6fd45c9ef0fc583c14f6e/app/backend/prepdocslib/searchmanager.py#L203). It looks like this sample is on `11.6.0b1`. 

The API reference is also [here](https://learn.microsoft.com/en-us/python/api/azure-search-documents/azure.search.documents.searchclient?view=azure-python#azure-search-documents-searchclient-upload-documents) if you're curious about the details. 

If you're still running into errors, please post the specific error you're running into.
