### ISSUE TITLE
ZB

### ISSUE THREAD

**Issue by fkrlm** [Azure/azure-sdk-for-python#36835]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.throughputproperties?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-cosmos/azure.cosmos.ThroughputProperties.yml

### Document Version Independent Id

e1db95e3-07df-f398-d457-1b8ba9f17668

### Article author

@lmazuel

### Metadata

* ID: 033c938a-b62c-9c4c-1550-faad0ca70426 
* Service: **cosmos-db**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you provide more details?
