### ISSUE TITLE
QuotaMgmtClient does not raise exception for response 429 (Too many requests)

### ISSUE THREAD

**Issue by AdrianM10** [Azure/azure-sdk-for-python#36853]
- **Package Name**: azure-mgmt-quota
- **Package Version**: 1.1.0
- **Operating System**: Windows 11 
- **Python Version**: 3.11.9

**Describe the bug**
The Azure Quota Management SDK (QuotaMgmtClient) does not raise an exception when receiving a 429 (Too Many Requests) response from the API when requesting quota increases. Instead the response code is shown in the terminal output, this makes it difficult to handle rate limiting scenarios properly

**To Reproduce**
1. Install library
`pip install azure-mgmt-quota`
2. Run code snippet using QuotaMgmtClient (Simplified code snippet)

```
try:
        client = QuotaMgmtClient(
            credential=DefaultAzureCredential(),
        )

        poller = client.quota.begin_create_or_update(
            resource_name=quota_sku,
            scope=f"subscriptions/{subscription_id}/providers/{provider}/locations/{quota_region}",
            create_quota_request={
                "properties": {
                    "limit": {
                        "limitObjectType": "LimitValue",
                        "value": quota_new_limit,
                    },
                    "name": {"value": quota_sku},
                }
            },
        )
        # Periodically check the status and try to access the result
        while not poller.done():
            logging.info(f"poller status: {poller.status()}")
            try:
                intermediate_result = poller.result(timeout=1)
                logging.info(f"Intermediate result: {intermediate_result}")

                return intermediate_result
            except (HttpResponseError, ServiceRequestError) as e:
                logging.error(
                    f"Failed to make the request - feel free to retry. But the specifics are here: {e}"
                )
                raise e
            except TimeoutError:
                logging.info("poller not complete yet, waiting...")
            time.sleep(10)  # Wait for 10 seconds before checking again

        # Once the poller is complete, access the final result
        final_result = poller.result()
        logging.info(f"Final result: {final_result}")

        logging.info("Successfully requested quota increase.")

        return final_result
    except (HttpResponseError, ServiceRequestError) as e:
        logging.error(
            f"Failed to make the request - feel free to retry. But the specifics are here: {e}"
        )
        raise e
```

3. Observe that when the API returns a 429 status, no exception is raised.

**Expected behavior**
When the API returns a 429 status code, the SDK should raise an HttpResponseError with a status code of 429. This will allow developers to catch and handle rate limiting scenarios appropriately. 

**Screenshots**
![Screenshot 2024-08-12 145507](https://github.com/user-attachments/assets/1ad865bc-39dc-43b1-bc36-4359c96f9202)

**Additional context**
The current behaviour makes it challenging to implement proper rate limiting in applications using this SDK. It's especially problematic in serverless environments like Azure Functions where a timeout can occur without properly handling the error

**Comment by kashifkhan** [comment]
Thank you for the feedback @AdrianM10 . We will investigate and get back to you asap.

**Comment by ChenxiJiang333** [comment]
Hi @AdrianM10, by the swagger definition [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/quota/resource-manager/Microsoft.Quota/stable/2023-02-01/quota.json#L237), quota has defined another exception model to raise instead of raising HttpResponseError. Please use `from azure.mgmt.quota.models import ExceptionResponse` to catch error info.

**Comment by AdrianM10** [comment]
Hi @ChenxiJiang333, I've updated my exception handling to catch the "ExceptionResponse" instead of "HttpResponseError". Despite these changes, I'm still not able to catch the 429 response. No exception is caught or raised.

**Comment by ChenxiJiang333** [comment]
Hi @AdrianM10, not able to reproduce the error to catch locally, could you take a try at `from azure.core.exceptions import ServiceResponseError` ?

**Comment by AdrianM10** [comment]
Hi @ChenxiJiang333, still the same. That also doesn't catch the error.

**Comment by ChenxiJiang333** [comment]
> Hi @ChenxiJiang333, still the same. That also doesn't catch the error. To reproduce the error you'll need to send the same request multiple times for a quota increase in quick succession.

Would there be any error message I wonder? Have you tried `except Exception as e:  logging.error(e)` to check whether there would be an exception raised when receive the response 429? If there's not, then it might be the issue of the package.

**Comment by AdrianM10** [comment]
Still not even with `except Exception as e`, just to test I intentionally sent a malformed payload, this returns an error (Response status 400) see below:

```
{
  "id": null,
  "message": "(InvalidResourceName) Name standardBSFamil is not valid resource name.\nCode: InvalidResourceName\nMessage: Name standardBSFamil is not valid resource name."
}
```

Looks like somehow the 429 response in particular isn't being treated as an exception.

**Comment by ChenxiJiang333** [comment]
Hi @AdrianM10, has found the root. Response 429 follows the [retry policy](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L219), so it won't raise any exception but to resend the request after a specified time.
![image](https://github.com/user-attachments/assets/c8f72045-110f-43b8-b7e3-adbd99e32465)

**Comment by AdrianM10** [comment]
Hi @ChenxiJiang333, is there any sample code that I can reference to access the response status, response headers / object once the call has been made ? I had spent a week or so prior to raising the issue and had no luck.

**Comment by AdrianM10** [comment]
I have been unable to use any method that can access the HTTP response object, is there any example code or docs I can use as reference?

**Comment by ChenxiJiang333** [comment]
Hi @AdrianM10, I have found a way to disable the retry policy and raise the exception.
Try update the code to:
```
        poller = client.quota.begin_create_or_update(
            resource_name=quota_sku,
            scope=f"subscriptions/{subscription_id}/providers/{provider}/locations/{quota_region}",
            create_quota_request={
                "properties": {
                    "limit": {
                        "limitObjectType": "LimitValue",
                        "value": quota_new_limit,
                    },
                    "name": {"value": quota_sku},
                }
            },
            retry_total = 0
        )
```

**Comment by AdrianM10** [comment]
Hi @ChenxiJiang333, Thank you so much for your help and for providing this solution! I really appreciate your time and effort in addressing my issue.
