### ISSUE TITLE
Bug: WebPubSubServiceClient can't connect to API / Connection string parsing problems.

### ISSUE THREAD

**Issue by discounter24** [Azure/azure-sdk-for-python#36850]
- **Package Name**:  azure-messaging-webpubsubservice
- **Package Version**: 1.2.0
- **Operating System**: Windows
- **Python Version**:  3.11

**Describe the bug**
WebPubSubServiceClient, created by a connection string raises `ValueError: The value provided for the url part endpoint was incorrect, and resulted in an invalid url` when sending messages.

**To Reproduce**
1. Create Python 3.11 venv with azure-messaging-webpubsubservice==1.2.0
2. Get unmodifed connection string for wps service directly from the Azure Portal (Portal -> PubSub Service -> Keys -> Primary Connection string)
3. Run the following test code with the connection string inserted:
```
from azure.messaging.webpubsubservice import WebPubSubServiceClient
service = WebPubSubServiceClient.from_connection_string(connection_string='<ConnectionStringPastedFromAzurePortal>', hub='test')
service.send_to_group("testgroup", "testmessage")
```
4. Error is raised on send_to_group.

**Expected behavior**
The ServiceClient ist supposed to send "testmessage" to "testgroup" without raising an exception. 

**Screenshots**
None required.

**Additional context**
Looks like the error got introduced in package version 1.2.0, as downgrading to 1.1.0 fixes the problem without any code change.

**Comment by kashifkhan** [comment]
Thank you for the feedback @discounter24 . We will investigate and get back to you asap.

**Comment by Coca-ColaCo** [comment]
Same issue here. 

Downgrading also worked for me.

Package Name: azure-messaging-webpubsubservice
Package Version: 1.2.0
Operating System: Windows 11
Python Version: 3.10

**Comment by msyyc** [comment]
1.2.0 was released recently by @cqnguy23 and add him for help.

**Comment by cqnguy23** [comment]
It seems that when running tool to update client to use new api_version, it modifies some code in the `WebPubSubServiceClient` class that eventually causes this issue. Working on a fix to resolve this

**Comment by cqnguy23** [comment]
@discounter24 @Coca-ColaCo released a fix for this in the latest version (`1.2.1`). Could you please upgrade to the latest version and let me know if the issue still persists? Thank you and sorry for the inconvenience.

**Comment by discounter24** [comment]
Works for me, thank you!

**Comment by Coca-ColaCo** [comment]
It's working for me as well, cheers!
