### ISSUE TITLE
Missing disableLocalAuth property for azureml computeInstance class

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure/azure-sdk-for-python#36886]
The [ current `computeInstance` property for azureml-python-sdk](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.computeinstance?view=azure-python) was missing an property called `disableLocalAuth` which is a boolean variable. Could yop please enable this property

**Comment by achauhan-scc** [comment]
we have added enable_sso feature for compute instance.
https://github.com/Azure/azure-sdk-for-python/pull/36628

**Comment by jayendranarumugam** [comment]
Hi @achauhan-scc I think the original request is to add a new property called `disableLocalAuth` property and not `enable_sso` which is a separate property. Since this issue is closed. I have opened a [new issue for this to track](https://github.com/Azure/azure-sdk-for-python/pull/36628)
