### ISSUE TITLE
Cannot get storage account access via Azure Arc

### ISSUE THREAD

**Issue by lovettchris** [Azure/azure-sdk-for-python#36881]
- **Package Name**: see below
- **Package Version**: see below
- **Operating System**: Windows Server 2019 version 1809
- **Python Version**: 3.10.14

asyncio                          3.4.3
attrs                            24.2.0
azure-common                     1.1.28
azure-core                       1.30.2
azure-cosmosdb-nspkg             2.0.2
azure-cosmosdb-table             1.0.6
azure-data-tables                12.5.0
azure-identity                   1.17.1
azure-keyvault-keys              4.9.0
azure-keyvault-secrets           4.8.0
azure-messaging-webpubsubservice 1.1.0
azure-nspkg                      3.0.2
azure-storage-blob               12.22.0

**Describe the bug**

I see this [pull request](https://github.com/Azure/azure-sdk-for-python/pull/15020/files#diff-4354ce3fa0bcfa5e4eb0aa6e953313b590eb15b0c440f796b0e30eac4df095dc) added support for AzureArcCredentials which is great, and I can create your `AzureArcCredential` and get_token succeeds.  But when I try and use this credential in a `BlobServiceClient` it fails with `ErrorCode:NoAuthenticationInformation` even though I have provisioned access to the storage account for my Azure-Arc machine using the system assigned identity.

**To Reproduce**

```python
    account_url = "https://adaserverstorage.blob.core.windows.net/"
    credentials = AzureArcCredential()
    token = await credentials.get_token(account_url)
    print(f"Access token: {token.token}")

    # now see if it works in the blob store access!
    managed = DefaultAzureCredential()
    client = BlobServiceClient(account_url, credentials=managed)
    container = client.get_container_client(container="firmware")
    print(container.exists())
```

**Expected behavior**

The blob store authentication should work.

**Screenshots**

```
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:79a2746a-301e-001c-2cdc-edba32000000
Time:2024-08-13T23:57:40.3820483Z
ErrorCode:NoAuthenticationInformation
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:79a2746a-301e-001c-2cdc-edba32000000
Time:2024-08-13T23:57:40.3820483Z</Message></Error>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000026F6E4FC6A0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000026F6E4CFC40>, 8753.968)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000026F6E4FC730>
```

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

I am a little confused about the code you shared.

Did you use a sync client or an async client?

It seems to me you use AzureArcCredential to get the token but then use DefaultAzureCredential to access the storage.

And seems like the error happened when you tried to use DefaultAzureCredential to get token.

**Comment by lovettchris** [comment]
@xiangyan99, I was just checking that AzureArcCredential does actually return a token successfully, which it does.  But the DefaultAzureCredential should be delegating to the AzureArcCredential  (based on looking at your code) but something is still not working when it comes to getting access to my storage account from an Azure-Arc connected machine.

**Comment by xiangyan99** [comment]
Can you try to use

managed = AzureArcCredential()

instead of 

managed = DefaultAzureCredential()

to reduce some noise?

**Comment by lovettchris** [comment]
Oh, yeah, sorry, that was the first thing I tried, but that gives the same error.

**Comment by lovettchris** [comment]
Note that it is getting the token from:

IDENTITY_ENDPOINT=http://localhost:40342/metadata/identity/oauth2/token

So is there some sort of federation going on here to Azure and is that were things might be broken here?

**Comment by xiangyan99** [comment]
(Assuming you successfully got a token from AzureArcCredential) @jalauzon-msft @vincenttran-msft do you know what the error message means?

**Comment by jalauzon-msft** [comment]
@xiangyan99 - I believe that would indicate that no `Authorization` header was present in the request, which would be odd. Storage uses a mostly standard `BearerTokenCredentialPolicy` [here](https://github.com/Azure/azure-sdk-for-python/blob/2a8551d20849dba3fd3b0c643abb89acbbaf8199/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py#L680) which should be adding the header. Perhaps there is some weird interaction with the Arc credential (I am not familiar with that cred type).

**Comment by xiangyan99** [comment]
Thank you. @jalauzon-msft 

@lovettchris Could you confirm both of your BlobServiceClient and AzureArcCredential are async?

**Comment by lovettchris** [comment]
> Thank you. @jalauzon-msft
> 
> @lovettchris Could you confirm both of your BlobServiceClient and AzureArcCredential are async?

Ah, didn't know about `from azure.storage.blob.aio import BlobServiceClient` until just now, so I switched to that and added await on the `result = await container.exists()` check, but it fails with the same error, but you can see the `aio` code path in the stack trace now:


```
Traceback (most recent call last):
  File "C:\temp\test.py", line 72, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\.conda\envs\ada\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\.conda\envs\ada\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\temp\test.py", line 68, in main
    result = await container.exists()
  File "C:\Users\Administrator\.conda\envs\ada\lib\site-packages\azure\core\tracing\decorator_async.py", line 94, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\ada\lib\site-packages\azure\storage\blob\aio\_container_client_async.py", line 547, in exists
    process_storage_error(error)
  File "C:\Users\Administrator\.conda\envs\ada\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 186, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\.conda\envs\ada\lib\site-packages\azure\storage\blob\aio\_container_client_async.py", line 543, in exists
    await self._client.container.get_properties(**kwargs)
  File "C:\Users\Administrator\.conda\envs\ada\lib\site-packages\azure\core\tracing\decorator_async.py", line 94, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\ada\lib\site-packages\azure\storage\blob\_generated\aio\operations\_container_operations.py", line 241, in get_properties
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Users\Administrator\.conda\envs\ada\lib\site-packages\azure\core\exceptions.py", line 161, in map_error
    raise error
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:3115fb94-f01e-003c-5b7f-efc195000000
Time:2024-08-16T01:53:47.4256715Z
ErrorCode:NoAuthenticationInformation
```

**Comment by xiangyan99** [comment]
Let's collect some verbose logs.

Please ping me offline.

**Comment by xiangyan99** [comment]
Worked offline and figured out in
```
client=BlobServiceClient(account_url, credentials=credentials)
```

the argument name should be credential (no "s").

**Comment by lovettchris** [comment]
That was it, thanks!
