### ISSUE TITLE
[formrecognizer] Documentation implies Form Recognizer will return Key-Value Pairs that may lack keys and/or values

### ISSUE THREAD

**Issue by edrogers** [Azure/azure-sdk-for-python#36892]
The documentation for Azure Form Recognizer includes example snippets on usage. (Many thanks to @kristapratico, @catalinaperalta, and @maririos for working to add those in #20996 and #29193!)

In those snippets is a pair of if-statements: `if kv_pair.key:` [here](https://github.com/Azure/azure-sdk-for-python/blob/682d021b316db3e21bd8886ad2fcbcec0ad9db9d/sdk/formrecognizer/azure-ai-formrecognizer/README.md?plain=1#L352) and `if kv_pair.value` [here](https://github.com/Azure/azure-sdk-for-python/blob/682d021b316db3e21bd8886ad2fcbcec0ad9db9d/sdk/formrecognizer/azure-ai-formrecognizer/README.md?plain=1#L359). Is there any chance that either of `kv_pair.key` or `kv_pair.value` will come back "falsy" or missing?

If so, is there somewhere in the documentation that could help me understand the usage of key-value pairs that are missing either the key, the value, or both? 

(On the other hand, if they'll never be missing, could those conditionals be removed?)

**Comment by YalinLi0312** [comment]
@edrogers Thanks for your contact! 
This is the documentation of `DocumentKeyValuePair` class: https://learn.microsoft.com/en-us/python/api/azure-ai-formrecognizer/azure.ai.formrecognizer.documentkeyvaluepair?view=azure-python#attributes 
`key` and `confidence` properties are required, `value` could be `None`.

**Comment by edrogers** [comment]
Ah, thanks for this clarification & link to the documentation @YalinLi0312! 

So, this means [the first if-statement](https://github.com/Azure/azure-sdk-for-python/blob/682d021b316db3e21bd8886ad2fcbcec0ad9db9d/sdk/formrecognizer/azure-ai-formrecognizer/README.md?plain=1#L352) is unnecessary (since key is a required property), but [the second if-statement](https://github.com/Azure/azure-sdk-for-python/blob/682d021b316db3e21bd8886ad2fcbcec0ad9db9d/sdk/formrecognizer/azure-ai-formrecognizer/README.md?plain=1#L359) is important since `kv_pair.value` may be None. Is my understanding correct?

If so, would you be willing to review/accept a pull request that removes the first if-statement?

**Comment by YalinLi0312** [comment]
Hi @edrogers , sure thing, we would review your PR and welcome any contributions. Thanks in advance! One more thing you may don't know for this sample - you can update the `sample_analyze_general_documents.py` and use the snippet in `README.md`.
