### ISSUE TITLE
Can't create vm with exsiting vm image + fix found work for me 

### ISSUE THREAD

**Issue by zhitongLIU** [Azure/azure-sdk-for-python#369]
Bug found: when I use create_virtual_machine_deployment to  create a new virtual machine with a existing vm image, i got this 

`<bad request : No Configuration Set should be specified while using a VMImage with a specialized OS Disk Configuration>`

---------------------------------------------------------------------------------------------
Corrige found in: `azure/servicemanangement/__init__.py`
in function role_to_xml,
`if system_configuration_set or network_configuration_set:`

should be changed to
`if (system_configuration_set or network_configuration_set) and not vm_image_name:`

Else it will add `<ConfigurationSets>` tag and the api server will refuse this request.

Please fixed this in the next update, thankyou!

**Comment by huguesv** [comment]
That's not going to work for generalized vm images

To use a generalized vm image, you have to specify a vm_image_name and a system_configuration_set (to give it admin name+password, computer name, etc).  Your code change means that the system config would be ignored.

In your scenario, you should pass None for system_configuration_set and network_configuration_set.  I don't think we prevent that, but if we do, I think that's what we would have to fix.
