### ISSUE TITLE
Typo in documentation for TableClient class

### ISSUE THREAD

**Issue by jz4o** [Azure/azure-sdk-for-python#36940]
### Type of issue

Typo

### Description

There is a typo in the example section of the update_entity method on the documentation page.

current: `Updating an already exiting entity in a Table`
i think: `Updating an already existing entity in a Table`

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables.tableclient?view=azure-python#azure-data-tables-tableclient-update-entity

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-data-tables/azure.data.tables.TableClient.yml

### Document Version Independent Id

a53bc37d-1e8d-dde1-3b7f-da7345ec6b60

### Article author

@lmazuel

### Metadata

* ID: b3f0fbc3-700d-812f-1cc7-dbac5c748a9b

**Comment by rohit-ganguly** [comment]
Thanks for spotting it! You're right - the code sample under [update_entity](https://learn.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables.tableclient?view=azure-python#azure-data-tables-tableclient-update-entity) says `exiting` instead of `existing`. We'll get this fixed ASAP :)

**Comment by YalinLi0312** [comment]
Hi @jz4o , we've fixed the typo in SDK but haven't updated in doc portal yet. Our doc team is working on it, and I'll update here once it's done. Thanks for your patience!

**Comment by jz4o** [comment]
Hi @YalinLi0312 , thanks for fixed and status update.
I look forward to updates to the doc portal!

**Comment by YalinLi0312** [comment]
Hi @jz4o Got to know from doc team that this typo can't manually update by them, it should update automatically with next release of this package. Stay tuned!
Since we already fixed the typo in our SDK, will close the issue.
