### ISSUE TITLE
SearchableField using Collection(String) type will create a String only searchable field instead of Collection

### ISSUE THREAD

**Issue by jkristal-nubiral** [Azure/azure-sdk-for-python#36956]
- **Package Name**: azure-search-documents
- **Package Version**: 11.5.0
- **Operating System**: Ubuntu 24.04
- **Python Version**:  3.12.3

**Describe the bug**
When creating an Index using a SearchableField with Collection(String) type it ends up creating one that only supports Strings.

**To Reproduce**
1. Define a fields list that includes `SearchableField(name="keywords_es", type=SearchFieldDataType.Collection(SearchFieldDataType.String), analyzer_name="es.lucene")` for example.
2. Create a SearchIndex with that list.
3. Call SearchIndexClient.create_or_update_index to create the index with the field. 
4. Field `keywords_es` is now a searchable field of type **String** instead of **Collection(String)**

**Expected behavior**
The field `keywords_es` should be of type **Collection(String)**

**Screenshots**
-

**Additional context**
As a workaround, one can instead use a `SearchField` and specifically ask for all their attributes and it does create the field properly:

```
SearchField(name="keywords_es", filterable=False, facetable=False, searchable=True, type=SearchFieldDataType.Collection(SearchFieldDataType.String), analyzer_name="es.lucene"),
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

type is not a valid argument for SearchableField. If you want to create a collection using SearchableField, you can use

SearchableField(collection=True)

**Comment by jkristal-nubiral** [comment]
oh thanks! closing it then
