### ISSUE TITLE
Issue with VectorSearchCompression Subtype Mapping in Azure SDK

### ISSUE THREAD

**Issue by AndreaArmx** [Azure/azure-sdk-for-python#36975]
I'm encountering an issue when attempting to use ScalarQuantizationCompression in the vector_search.compressions field of a SearchIndex. The problem seems to be related to subtype mapping within the SDK.

**Steps to Reproduce:**

Define an index with vector search configuration, including ScalarQuantizationCompression in the compressions list.
Print the type of the compression object after creating the index.
Observe the resulting warning and error. The following is a minimal example to reproduce the issue:

```python
from azure.search.documents.indexes.models import SearchIndex
from azure.search.documents.indexes import SearchIndexClient

azure_params = {
    "name": 'test_index',
    "fields": [
        {
            "name": "HotelId",
            "type": "Edm.String",
            "key": "true",
            "searchable": "true",
            "filterable": "false",
            "sortable": "false",
            "facetable": "false"
        },
        {
            "name": "HotelDescription",
            "type": "Edm.String",
            "searchable": "true",
            "filterable": "false",
            "sortable": "false",
            "facetable": "false"
        },
        {
            "name": "embedding",
            "type": "Collection(Edm.Single)",
            "searchable": "false",
            "filterable": "false",
            "sortable": "false",
            "facetable": "false",
            "vector_search_dimensions": 384,
            "vector_search_profile_name": "default"
        }
    ],
    "vector_search": {
        "profiles": [
            {
                "name": "default",
                "algorithm_configuration_name": "hnsw"
            }
        ],
        "algorithms": [
            {
                "name": "hnsw",
                "kind": "hnsw",
                "parameters": {
                    "metric": "cosine",
                    "m": 10,
                    "ef_construction": 200,
                    "ef_search": 200
                }
            }
        ],
        "vectorizers": [],
        "compressions": [
            {
                "compression_name": "myCompression",
                "kind": "ScalarQuantizationCompression"
            }
        ]
    },
}

index = SearchIndex.from_dict(azure_params)
print(type(index.vector_search.compressions[0]))  # Expecting ScalarQuantizationCompression

client = SearchIndexClient(
            endpoint=..., credential=..., ...
        )

client.create_index(index=cast(SearchIndex, index))
```

**Expected Behavior:**

The output of print(type(index.vector_search.compressions[0])) should correctly display ScalarQuantizationCompression. Additionally, the index creation should not produce errors related to the kind field.

**Actual Behavior:**

The output is **<class 'azure.search.documents.indexes._generated.models._models_py3.VectorSearchCompression'>**, with this warning **"Subtype value ScalarQuantizationCompression has no mapping, use base class VectorSearchCompression."**, indicating the subtype value is not correctly mapped.
During index creation, the error message is: **The request is invalid. Details: vectorSearch.compressions[0].kind : The kind field is required.**

**Additional Information:**

The issue seems related to the **__subtype_map_** defined in the VectorSearchCompression class. Specifically, the _**_classify**_ method in the **Model** class within **azure/search/documents/indexes/_generated/_serialization.py** is unable to infer the correct subtype based on the provided kind value because it does not match the expected key.

The _subtype_map is defined as follows:

```python
_subtype_map = {
    "kind": {
        "binaryQuantization": "BinaryQuantizationCompression",
        "scalarQuantization": "ScalarQuantizationCompression",
    }
}
```

However, the kind value passed is **ScalarQuantizationCompression**, which does not correspond to the expected key in the _subtype_map. Consequently, this leads to the warning and the error when creating the index.

Attempting to pass "scalarQuantization" directly as a kind value results in the following error: **"Input should be 'BinaryQuantizationCompression' or 'ScalarQuantizationCompression'","input":"scalarQuantization","ctx":{"expected":"'BinaryQuantizationCompression' or 'ScalarQuantizationCompression'"}**.

**Temporary and dirty workaround**
To temporarily work around the issue with a dirty solution, we can define the following new key extractor function:

```python
def _get_proper_vector_search_compression_subtype(
       attr: str, attr_desc: Dict[str, Any], data: Dict[str, Any]
  ) -> Optional[Any]:
      """
      Adjust the `VectorSearchCompression` subtype mapping for the `vector_search` attribute if necessary.

      This method checks if the provided `attr` is `vector_search`. If it is, the method will validate and
      update the `VectorSearchCompression` subtype mapping based on the `compressions` data provided in the
      `vector_search` dictionary. If the `kind` of compression is not found in the existing subtype map but
      is a known value, it will be added to the map.

      :param attr: The name of the attribute being processed. Expected to be "vector_search".
      :param attr_desc: A dictionary containing metadata about the attribute, including its type.
      :param data: The data dictionary containing the `vector_search` attribute and its configuration.
      :return: The `vector_search` attribute data.
      """
      if attr != "vector_search":
          return None

      vector_search = data.get(attr, None)
      if (
          vector_search is None
          or not isinstance(vector_search, dict)
          or "compressions" not in vector_search
      ):
          return data[attr]

      from azure.search.documents.indexes._generated.models import (
          VectorSearchCompression,
      )

      for compression in vector_search["compressions"]:
          if (
              compression["kind"]
              not in VectorSearchCompression._subtype_map["kind"].keys()
              and compression["kind"]
              in VectorSearchCompression._subtype_map["kind"].values()
          ):
              VectorSearchCompression._subtype_map["kind"][compression["kind"]] = (
                  compression["kind"]
              )

      return data[attr]
```

then, when creating an instance of SearchIndex using from_dict, make sure to pass this new key extractor function in the first position of the key_extractors list. 

```python
key_extractors = [
    _get_proper_vector_search_compression_subtype,
    attribute_key_case_insensitive_extractor,
    rest_key_case_insensitive_extractor,
    last_rest_key_case_insensitive_extractor,
]

index = SearchIndex.from_dict(azure_params, key_extractors=key_extractors) # type: ignore
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

The `SearchIndex` model is not exactly same as the one for restful API.

The input of `from_dict` method is for the scenario that you have a model and serialize it with `as_dict`.

Have you tried use the constructor to create the model instance?

**Comment by AndreaArmx** [comment]
I fixed the issue. I realized afterwards that the mistake was in my code. Thanks anyway!
