### ISSUE TITLE
TableService does not work if locale is set to 'es_ES.utf8'

### ISSUE THREAD

**Issue by rchamorro** [Azure/azure-sdk-for-python#370]
If you set the locale, the table service does not authenticate correctly so, it does not work. Example

```python
    import locale  
    locale.setLocale(locale.LC_ALL, 'es_ES.utf8')
    from azure.storage import TableService
    table_service = TableService(account_name, account_key)
    entity = table_service.get_entity(table_name, partition_key, row_key)
```
It throws an authentication exception. 
If you do not set the locale, everything is OK.

The problem is converting from current time to string in the request headers
    current_time = datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')

In spanish locale, it returns: 
**vie**, 29 may 2015 10:35:51 GMT

Instead of:
**Fri**, 29 May 2015 10:35:51 GMT

https://msdn.microsoft.com/en-us/library/azure/dd135714.aspx

**Comment by huguesv** [comment]
Very good catch. Thanks for the proposed fix too.  I merged Chris' implementation which saves us a bit of maintenance and should work just as well.
https://github.com/Azure/azure-sdk-for-python/pull/379
