### ISSUE TITLE
DialogServiceConnector does not set provided synthesized speech format 

### ISSUE THREAD

**Issue by mja8122** [Azure/azure-sdk-for-python#37012]
- **Package Name**: azure.cognitiveservices.speech.dialog
- **Package Version**: 1.40.0
- **Operating System**: Ubuntu 22.04.3 LTS
- **Python Version**: Python 3.10.12

I am working on a direct line speech bot integration with an IVR system that only supports ULAW audio streams.  I am able to set the incoming stream format for the speech-to-text input like so:

```
# setup the audio stream
stream_format = speechsdk.audio.AudioStreamFormat(
    channels=1, 
    bits_per_sample=8, 
    samples_per_second=8000, 
    wave_stream_format=speechsdk.audio.AudioStreamWaveFormat.MULAW)
stream = speechsdk.audio.PushAudioInputStream(stream_format=stream_format)
audio_config = speechsdk.audio.AudioConfig(stream=stream)

# setup bot config
bot_config = speechsdk.dialog.BotFrameworkConfig(subscription=SUBSCRIPTION_KEY, region=REGION)
dialog_service = speechsdk.dialog.DialogServiceConnector(bot_config, audio_config)
```
There does not seem to be a method to set the Synthesized Speech Output like there is with **SpeechSynthesizer**.  However, there is a **set_property()** method that does nothing:

```
bot_config.set_property(speechsdk.PropertyId.SpeechServiceConnection_SynthOutputFormat, "Raw8Khz8BitMonoMULaw")
```
Synthesized speech is still 16Khz PCM WAV.

**To Reproduce**

```
bot_config.set_property(speechsdk.PropertyId.SpeechServiceConnection_SynthOutputFormat, "Raw8Khz8BitMonoMULaw")
```

**Expected behavior**
Expect the audio data from the **activity_received** event to be in the specified format.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by kristapratico** [comment]
@mja8122 the speech SDK does not reside in this repo. Please move your issue to this repo: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues where the maintainers of the library will be able to help. Thanks!

**Comment by mja8122** [comment]
Moving to correct repo
