### ISSUE TITLE
Read timed out issue with CosmosDB

### ISSUE THREAD

**Issue by maxiedaniels** [Azure/azure-sdk-for-python#37079]
- **Package Name**: azure-cosmos 
- **Package Version**: 4.5.1
- **Operating System**: Mac 13.6.8
- **Python Version**: 3.9.15

I'm using FastAPI, and have setup cosmos in my app.state:
```
app.state.cosmos_client = CosmosClient(
        cosmosdb_url,
        credential=cosmosdb_key,
        retry_total=3,
        retry_backoff_max=10,
        retry_on_status_codes=[429, 500, 503],
        retry_backoff_factor=1.5,
    )
```
    
    
I'm using a dev clone of my CosmosDB database, so it's only myself hitting the database right now.

Multiple times in the last twenty minutes, I've gotten an error:
`ServiceResponseError`, and all it says is read timed out, and says read timeout default is 300.

This occurs when doing:
`users_container.query_items(query=query, parameters=parameters, enable_cross_partition_query=True))`

I've checked on Azure and don't see any errors reported, or anything strange. My RU usage is hitting a max of 8%.

Funny enough, I remember putting in the retry values in the CosmosClient instantiation because of this exact issue. I also have Sentry running on our production server, and I can see this error comes up a decent amount.

Any idea why this would be happening?

**Comment by kristapratico** [comment]
@maxiedaniels thanks for your issue, the team will take a look and get back to you as soon as possible.

**Comment by simorenoh** [comment]
Hi @maxiedaniels, sorry about the delay getting back to you. Could you please enable cosmos diagnostics logging following this guide here (https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cosmos/azure-cosmos#logging-diagnostics) and share some of those with us as this happens? ServiceRequestErrors are rare and generally have to do with network conditions more so than anything SDK related, but with some diagnostics we may be able to find more about this.
