### ISSUE TITLE
Typo on Bash code snippet

### ISSUE THREAD

**Issue by biggernaaz** [Azure/azure-sdk-for-python#37076]
Under the "Create a resource group and Azure Container Registry" sub heading in Step 3:

ACR_PASSWORD=$(az acr credential show \
--resource-group web-app-simple-rg \
--name webappacr123 \
--query "passwords[?name == 'password'].value" \
--output tsv)

should be 

$ACR_PASSWORD=(az acr credential show \
--resource-group web-app-simple-rg \
--name webappacr123 \
--query "passwords[?name == 'password'].value" \
--output tsv)

--------------
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kristapratico** [comment]
@biggernaaz can you share a link for where you see this typo? I can't find it. Thanks!

**Comment by biggernaaz** [comment]
> @biggernaaz can you share a link for where you see this typo? I can't find it. Thanks!

Hi @kristapratico - https://learn.microsoft.com/en-us/azure/developer/python/tutorial-containerize-simple-web-app-for-app-service?tabs=web-app-flask

In this code snippet the $ needs to be in front of "ACR_PASSWORD=" I believe. 

ACR_PASSWORD=$(az acr credential show \
--resource-group web-app-simple-rg \
--name webappacr123 \
--query "passwords[?name == 'password'].value" \
--output tsv)

Corrected version:
$ACR_PASSWORD=(az acr credential show \
--resource-group web-app-simple-rg \
--name webappacr123 \
--query "passwords[?name == 'password'].value" \
--output tsv)

**Comment by YalinLi0312** [comment]
Hi @biggernaaz , thanks for your feedback! Our doc team is working on it, I'll update here when the snippet is updated.

**Comment by YalinLi0312** [comment]
@biggernaaz We've merged the fix in our end, the portal content would get updated soon.

**Comment by biggernaaz** [comment]
> @biggernaaz We've merged the fix in our end, the portal content would get updated soon.

You're very welcome @YalinLi0312. Thanks for the heads-up.
