### ISSUE TITLE
attach databricks compute via python sdk2

### ISSUE THREAD

**Issue by WenjuanOlympus** [Azure/azure-sdk-for-python#37090]
I recently upgraded my machine learning code from `azure-core` to `azure-ai-ml`. However, I couldn't find documentation or example code on how to attach Databricks compute using the Python SDK v2. I would appreciate it if the ability to attach Databricks compute could be added as a feature in the latest version. This would allow for a consistent Azure ML experience without the need to maintain both `azure-core` and `azure-ai-ml` dependencies. Thank you for considering this enhancement in future updates.

**Comment by achauhan-scc** [comment]
Thanks for reporting the issue, currently Azure Data brick compute is unsupported in SDK V2, I am adding it the internal list of asks and closing the ticket.
