### ISSUE TITLE
Confidential Ledger Content Validation Issue for github.io website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37125]
1.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-confidentialledger/1.1.1/genindex.html):

![image](https://github.com/user-attachments/assets/a24fa213-ed76-44d3-bd0e-64ebd71aa97d)

**Reason:**
Format validation Issue: Text exceeds page size.

2.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-confidentialledger/1.1.1/azure.confidentialledger.html):

![image](https://github.com/user-attachments/assets/274ccd58-840c-46ef-af2e-7d4df497bb52)

[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-confidentialledger/1.1.1/azure.confidentialledger.html):

![image](https://github.com/user-attachments/assets/9e8e4497-4815-4634-994c-3a615bbaa964)

[link3](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-confidentialledger/1.1.1/index.html):

![image](https://github.com/user-attachments/assets/46614ce9-560a-48f8-8f42-940c54a67f71)

**Reason:**
Format validation Issue: Extra symbols `-` , `~` and `_` .

3.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-confidentialledger/1.0.0/index.html):

![image](https://github.com/user-attachments/assets/71cf10a7-cbfa-481d-b205-805ff3616cbc)

**Reason:**
Link validation Issue: Broken links.
![image](https://github.com/user-attachments/assets/8f929ce7-4a18-4f37-b7ea-c37566ec2e23)

@rohit-ganguly , @lmazuel , @christothes , @lynshi  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
