### ISSUE TITLE
Confluent Content Validation Issue for github.io website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37126]
1.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-confluent/2.1.0/genindex.html):

![image](https://github.com/user-attachments/assets/e700221d-0ba4-4281-ae09-5d0d38ea5abe)

**Reason:**
Format validation Issue: Text exceeds page size.

2.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-confluent/2.1.0/azure.mgmt.confluent.operations.html)

![image](https://github.com/user-attachments/assets/3f288ccd-0a75-45d1-8fda-be4cfb9e7d7e)

[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-confluent/2.1.0/index.html):

![image](https://github.com/user-attachments/assets/9c6edecd-f810-4447-bbc0-aa534c4d89fe)

**Reason:**
Format validation Issue: Extra symbols `-` and `_` .

@rohit-ganguly , @lmazuel , @MaryGao  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
