### ISSUE TITLE
Computefleet Content Validation Issue for github.io website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37124]
1.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/genindex.html):

![image](https://github.com/user-attachments/assets/3ec2d89c-df6c-4085-ad5b-c6ce699fedb2)

 [link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.ComputeProfile), [link3](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.Fleet), [link4](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.ImageReference), [link5](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.Resource), [link6](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.SecurityPostureReference), [link7](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.ServiceArtifactReference), [link8](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.TrackedResource), [link9](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.VMGalleryApplication), [link10](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.VirtualMachineScaleSet), [link11](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.VirtualMachineScaleSetNetworkProfile), [link12](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings):

![image](https://github.com/user-attachments/assets/2eba5eed-cb6a-4c36-b155-eec468f68c24)

**Reason:**
Format validation Issue: Text exceeds page size.

2.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.BaseVirtualMachineProfile), [link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.LinuxPatchAssessmentMode), [link3](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.LinuxPatchSettings), [link4](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.PatchSettings), [link5](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.VaultCertificate), [link6](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.VirtualMachineScaleSetDataDisk), [link7](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.VirtualMachineScaleSetOSProfile), [link8](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.models.html#azure.mgmt.computefleet.models.WinRMListener):
![image](https://github.com/user-attachments/assets/14aba860-9d8f-4a89-8fb7-2bb1066217ce)

**Reason:**
Format validation Issue: Format messy.

3.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/azure.mgmt.computefleet.operations.html):

![image](https://github.com/user-attachments/assets/b1072275-a8e1-42dc-a2ba-431c58a39121)

[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-computefleet/1.0.0b1/index.html):

![image](https://github.com/user-attachments/assets/fb0c4e4c-4766-4e91-b9d3-cdfda518766d)

**Reason:**
Format validation Issue: Extra symbols `-` and `_` .

@rohit-ganguly , @lmazuel  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
