### ISSUE TITLE
Cosmos DB for PostgreSQL Content Validation Issue for github.io website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37127]
1.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/genindex.html):

![image](https://github.com/user-attachments/assets/d09114cd-795f-4ccd-9db9-69ffe16aba6e)

[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.Cluster), [link3](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.ClusterServer), [link4](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.Configuration), [link5](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.FirewallRule), [link6](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.PrivateEndpointConnection), [link7](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.PrivateLinkResource), [link8](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.ProxyResource), [link9](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.ServerConfiguration), [link10](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.SimplePrivateEndpointConnection), [link11](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.models.html#azure.mgmt.cosmosdbforpostgresql.models.TrackedResource):

![image](https://github.com/user-attachments/assets/e7d1ad0a-3bfe-49c5-b37b-62b69a9fb832)

**Reason:**
Format validation Issue: Text exceeds page size.

2.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.operations.html):

![image](https://github.com/user-attachments/assets/9826eccc-735c-41e3-8b82-ebf34f3e93f3)

[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/index.html):

![image](https://github.com/user-attachments/assets/9fb7a1e4-3bb1-4f60-b83a-38e22fe191ea)

**Reason:**
Format validation Issue: Extra symbols `-` and `_`.

3.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdbforpostgresql/1.1.0b1/azure.mgmt.cosmosdbforpostgresql.operations.html):

![image](https://github.com/user-attachments/assets/1b971974-1628-4fe1-9786-7faab3abe043)

**Reason:**
Typing annotation Issue: Please unify the format, update to `*args:Any, **kwargs:Any` or `*args, **kwargs`.

@rohit-ganguly , @lmazuel , @kyle-patterson , @mayurid , @KrzysztofCwalina  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
