### ISSUE TITLE
RateCard api UsageAggregates list() ignores usage_start and usage_end datetimes

### ISSUE THREAD

**Issue by ewongbb** [Azure/azure-sdk-for-python#3714]
With the following code:

        cc = UsageManagementClient(ret_cred, sub_id)
        usage = cc.usage_aggregates.list(
            "20181001T00:00:00Z",
            "20181029T00:00:00Z",
        ulist = []
        for item in usage:
            ulist.append(item.as_dict())

When I look at the individual entries in the ulist, I get:
instance_data
|-- UsageType: ComputeHR_SW
|-- ServiceType: Standard_B2ms
|-- usage_end_time: 2018-10-01T00:00:00.000Z
|-- meter_id: 2core
|-- quantity: 2.0
|-- usage_start_time: 2018-09-30T00:00:00.000Z

I'm confused as to why the start time is set as Sept 30th?  Shouldn't
it say something like:

usage_start_time: 2018-10-01T00:00:00.000Z
usage_end_time: 2018-10-27T00:00:00.000Z

?
Or did I misunderstand the whole ratecard api?

Thanks

**Comment by lmazuel** [comment]
Hi @ewongbb 
It's a RestAPI behavior, so as the Python guy I don't know :(. I tagged the service team on it, let's see what they think. If you have no responses in a few days, please "up" the issue and I will reach out to them directly.

**Comment by xiangyan99** [comment]
@ewongbb latest azure-mgmt-commerce is 6.0.0. Does it work for you?
