### ISSUE TITLE
'NoneType' object has no attribute 'clear_route_to_location' when querying an Azure CosmosDB table using azure-cosmos python SDK

### ISSUE THREAD

**Issue by abhimanyusingh-sigfyn** [Azure/azure-sdk-for-python#37214]
- **Package Name**: azure-cosmos 
- **Package Version**: 4.6.0
- **Operating System**: Linux (Azure Functions Consumption Plan)
- **Python Version**: 3.9.19

**Describe the bug**
I am encountering the following error while querying data from CosmosDB using the azure-cosmos Python SDK:
`AttributeError("'NoneType' object has no attribute 'clear_route_to_location'")`.

**Sample Query**
`"SELECT C.Col1, C.Col2, C.Col3 FROM C WHERE C.ID IN (<Str1>, <Str2>, <Str3>....) AND (C.Date IN (<Date1>, <Date2>, <Date3>...))"`

**Table Details**
- TTL: Off
- Geospatial Configuration: Geography
- Indexing Mode: Consistent
- Composite Indexes: 
`{
      "path": "/ID",
      "order": "ascending"
},
{
    "path": "/Date",
    "order": "ascending"
}
`
- PartitionKey: /ID

Upon further investigation, I came across 3 files in azure.cosmos library, that are referencing **clear_route_to_location** function:
- _endpoint_discovery_retry_policy.py
- _session_retry_policy.py
- _timeout_failover_retry_policy.py

**Relevant code for initializing Azure CosmosClient for querying the table**

```
from azure.cosmos import CosmosClient

def get_client():
    global client

    if not client:
        cosmodb_logger = getLogger("azure.core.pipeline.policies.http_logging_policy")
        cosmodb_logger.setLevel(WARNING)

        response_string = get_secret(COSMOS_DB_SECRET)
        key = response_string["key"]

        client = CosmosClient(environ.get(COSMOS_DB_ENDPOINT), credential=key, logger=cosmodb_logger)

    return client

def get_container(database_name, container_name):
    database = get_client().get_database_client(database=database_name)
    container = database.get_container_client(container_name)
    return container

def query_items(database_name, container_name, query, max_item_count=100):
    container = get_container(database_name, container_name)
    query_items_response = container.query_items(query=query, enable_cross_partition_query=True, max_item_count=max_item_count)
    items = [item for item in query_items_response]
    return items
```

**To Reproduce**
The error is not consistently reproducible.

**Expected behavior**
The query runs successfully and data is returned back.

**Comment by kristapratico** [comment]
@abhimanyusingh-sigfyn thanks for your issue, the team will take a look and get back to you as soon as possible.

**Comment by bambriz** [comment]
Hello @abhimanyusingh-sigfyn Thank you for bringing this to our attention. It seems this error is happening because the request object for the query is None while a retryable error occured. (One of the retryable errors you mentioned). One other question I have is how are you currently using the query_items() method you showed? Could you provide an example of how it is used?

**Comment by abhimanyusingh-sigfyn** [comment]
Hello @bambriz. Here's an example of how **query_items()** is being used:

```
def get_data_from_db(container_name, query):
    data = query_items("db_name", container_name, query, max_item_count=10000)
    data_df = pd.Dataframe(data)
    return data_df

def my_func():
    query = "SELECT C.Col1, C.Col2, C.Col3 FROM C WHERE C.ID IN (<Str1>, <Str2>, <Str3>....) AND (C.Date IN (<Date1>, <Date2>, <Date3>...))"
    data_df = get_data_from_db("db_container_name", query)
```

**Comment by bambriz** [comment]
@abhimanyusingh-sigfyn This is currently being fixed with [PR 37578](https://github.com/Azure/azure-sdk-for-python/pull/37578).

**Comment by bambriz** [comment]
@abhimanyusingh-sigfyn The PR with the fix for this issue has been merged.
