### ISSUE TITLE
[question] azure.storage.blob from within VM

### ISSUE THREAD

**Issue by supRy** [Azure/azure-sdk-for-python#37227]
Sorry if this is an obvious answer, but I didn’t see it documented anywhere. 

If I use this package to download from blob storage on a VM in the same region/availability zone as the blob storage, will I incur an egress cost? It looks like it is making an HTTP request, but I want sure if it would automatically stay within the availability zone or if that initiates an internet egress.

**Comment by vincenttran-msft** [comment]
Hi @supRy , thanks for your inquiry. Here is the relevant documentation regarding pricing:
https://azure.microsoft.com/en-us/pricing/details/bandwidth/

If you scroll down towards the FAQ section near the bottom, there is a bullet point containing information relevant to your question:
![image](https://github.com/user-attachments/assets/1985312a-1efd-4a22-bc9c-ee03509967bb)

Thanks!
