### ISSUE TITLE
Unable to send email with excel attachment using Azure CS email and python

### ISSUE THREAD

**Issue by Palash-Doshi-Git** [Azure/azure-sdk-for-python#37239]
**Package Name**: azure-communication-email
**Package Version**: 1.00
**Operating System**: Windows 10 
**Python Version**: 3.11

**Describe the bug**
I am trying to create an azure function that sends an email with an attachment. I have successfully managed to send a plain text email using the azure-communication-email package but cannot get excel attachments to work

```
An error occurred: (BadRequest) Request body validation error. See property 'attachments[0].contentInBase64'
Code: BadRequest
Message: Request body validation error. See property 'attachments[0].contentInBase64'
```

**Steps to reproduce the behaviour:**

1. Download and install azure-communication-email
2. Connect to email client
3. Try to run the below code 

**Expected behavior:**
I expect to be at least able to send simple files as shown in the documentation

My Code:

````
import base64
import os
import azureSqldatabase as az_sql
from azure.communication.email import EmailClient
from dotenv import load_dotenv

load_dotenv()


def send_email_with_attachment(file_path,email):
    try:
        # Initialize the EmailClient with the connection string
        connection_string = os.getenv("ACS_CONNECTION_STRING")  # Replace with your ACS connection string
        client = EmailClient.from_connection_string(connection_string)
        sender_address = os.getenv('senderAddress')

        # Read the Excel file to attach
        with open(file_path, 'rb') as file:
            file_content = file.read()

        # Create the email message
        message = {
            "senderAddress": sender_address,  # Replace with your verified sender email
            "recipients": {
                "to": [{"address": email}]  # Replace with recipient email
            },
            "content": {
                "subject": "Excel Report",
                "plainText": "Please find the attached Excel report."
            },
            "attachments": [
                {

                    "contentBytesBase64": base64.b64encode(file_content).decode('utf-8'),
                    "contentType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "name": os.path.basename(file_path)
                }
            ]
        }

        # Send the email message
        poller = client.begin_send(message)
        result = poller.result()  # Wait for the sending operation to complete

        print(f"Email sent successfully. Message ID: {result.message_id}")

    except Exception as ex:
        print(f"An error occurred: {ex}")

def main():
    # Create the Excel file
    excel_df = az_sql.fetch_attendance()
    file_path = az_sql.save_to_excel(excel_df)

    # Send the email with the Excel file attachment
    send_email_with_attachment(file_path,email)


# Run the main function
if __name__ == "__main__":
    main()

```

Screenshots - 

![Capture](https://github.com/user-attachments/assets/eb2163e8-26b4-407a-9f3e-5cc639c840c4)

**Comment by RodrigoDiasDeOliveira** [comment]
Whats Up?!
I hope i can help....
The error you are encountering, (BadRequest) Request body validation error. See property 'attachments[0].contentInBase64', suggests that there is an issue with the way the attachment content is being handled in the request body. Specifically, the error points to the contentInBase64 field, which likely means that the attachment content is either not correctly encoded in Base64 or the field is misnamed.

Here are a few steps you can follow to resolve this issue:

1. Check the Property Name
In your code, you're using contentBytesBase64. According to the error message, the correct property should be contentInBase64. Try changing the property name in your message dictionary.

Update the attachments part of the message dictionary as follows:

python

"attachments": [
    {
        "contentInBase64": base64.b64encode(file_content).decode('utf-8'),  # Change the key here
        "contentType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "name": os.path.basename(file_path)
    }
]
2. Verify the Base64 Encoding
Ensure that the file is being correctly read and encoded into Base64. The code you have looks correct for encoding the file, but if the file is large or has any issues, consider printing the first few characters of the Base64 encoded string to verify that it's correctly encoded.

python
Copiar código
print(base64.b64encode(file_content).decode('utf-8')[:100])  # Print the first 100 characters of the Base64 string
3. Validate the Request Body
Ensure that the message dictionary you are passing to client.begin_send() is formatted correctly. Specifically, double-check that all required fields are present and correctly named, especially in the attachments section.

4. Debug the Azure Communication Service (ACS) Response
To get more details on the issue, enable the debug mode when running your code to capture more information on what might be going wrong:

bash

az configure --defaults logging=debug
Final Code Example
Here's the updated version of your code with the suggested changes:

python

import base64
import os
import azureSqldatabase as az_sql
from azure.communication.email import EmailClient
from dotenv import load_dotenv

load_dotenv()

def send_email_with_attachment(file_path, email):
    try:
        # Initialize the EmailClient with the connection string
        connection_string = os.getenv("ACS_CONNECTION_STRING")  # Replace with your ACS connection string
        client = EmailClient.from_connection_string(connection_string)
        sender_address = os.getenv('senderAddress')

        # Read the Excel file to attach
        with open(file_path, 'rb') as file:
            file_content = file.read()

        # Create the email message
        message = {
            "senderAddress": sender_address,  # Replace with your verified sender email
            "recipients": {
                "to": [{"address": email}]  # Replace with recipient email
            },
            "content": {
                "subject": "Excel Report",
                "plainText": "Please find the attached Excel report."
            },
            "attachments": [
                {
                    "contentInBase64": base64.b64encode(file_content).decode('utf-8'),  # Updated key
                    "contentType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "name": os.path.basename(file_path)
                }
            ]
        }

        # Send the email message
        poller = client.begin_send(message)
        result = poller.result()  # Wait for the sending operation to complete

        print(f"Email sent successfully. Message ID: {result.message_id}")

    except Exception as ex:
        print(f"An error occurred: {ex}")

def main():
    # Create the Excel file
    excel_df = az_sql.fetch_attendance()
    file_path = az_sql.save_to_excel(excel_df)

    # Send the email with the Excel file attachment
    send_email_with_attachment(file_path, email)


# Run the main function
if __name__ == "__main__":
    main()

Make sure you update the property name in the attachments section from contentBytesBase64 to contentInBase64. Also, verify that the file content is correctly encoded in Base64. With these changes, your issue should be resolved, and you'll be able to send an email with an Excel attachment using Azure Communication Service.

**Comment by Palash-Doshi-Git** [comment]
Hey RodrigoDiasDeOliveira ,
 Thanks for the correction! I was pretty sure I was missing a small detail. I corrected the code according to your suggestion, and it's working great!

**Comment by Palash-Doshi-Git** [comment]
Have a Great Time!

**Comment by RodrigoDiasDeOliveira** [comment]
thanxz bro! i see you around!
