### ISSUE TITLE
[breaking change detector][Feature Request] optimization for changelog about new features

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#37289]
SDK generated from swagger has msrest model while SDK from Typespec has DPG model. Compared with msrest model, DPG model has new structure. However, we don't hope users care about too many details when change from msrest mode to DPG model so we hope the changelog could ignore some items for `Features Added` part.

For example:
![image](https://github.com/user-attachments/assets/aa491dfb-48ed-448b-8eba-117df6fabdd7)
(https://github.com/Azure/azure-rest-api-specs/pull/30503/checks?check_run_id=29974232492)
We could there could be `IGNORE_FEATURES` like [IGNORE_BREAKING_CHANGES](https://github.com/Azure/azure-sdk-for-python/blob/7aeef6f433e98571b0b7624f57d3d89570b94949/scripts/breaking_changes_checker/breaking_changes_allowlist.py#L14C1-L14C25) to permit us to ignore some feature items.

**Comment by catalinaperalta** [comment]
You can add suppressions for these changes in the `IGNORE_BREAKING_CHANGES` list. I'll open a PR to rename the variable unless you want to do it in the same one you open to add the suppressions for these properties. Let me know if you have any questions!

**Comment by msyyc** [comment]
I see. [IGNORE_BREAKING_CHANGES](https://github.com/Azure/azure-sdk-for-python/blob/7aeef6f433e98571b0b7624f57d3d89570b94949/scripts/breaking_changes_checker/breaking_changes_allowlist.py#L14C1-L14C25) could also work for non-breaking changes. I think renaming it to `IGNORE_CHANGES` is better if we want to keep all ignores in one place.
