### ISSUE TITLE
Async AzureAppConfigurationClient context manager aiohttp.client warnings

### ISSUE THREAD

**Issue by gorun2git** [Azure/azure-sdk-for-python#37290]
- **Package Name**: azure.appconfiguration.aio
- **Package Version**: 1.6.0
- **Operating System**: macOS Sanoma 14.6.1
- **Python Version**: 3.11.9
- **aiohttp Version**: 3.10.5

**Describe the bug**
This might be similar to the issue [28527](https://github.com/Azure/azure-sdk-for-python/issues/28527), but instead error message I'm getting warning. 

I'm trying to get list of configuration settings from AppConfig by using async AzureAppConfigurationClient (context manger) with DefaultAzureCredentials. As a result I'm getting warning message of unclosed aiohttp client session. 

Here is the code I'm trying to execute

```
import asyncio

from azure.appconfiguration.aio import AzureAppConfigurationClient
from azure.identity.aio import DefaultAzureCredential


async def get_configuration_settings():
    credential = DefaultAzureCredential()
    async with AzureAppConfigurationClient(
        base_url="https://***********.azconfig.io", credential=credential
    ) as client:
        conf_settings = await client.get_configuration_setting(
            key="/existing/test/key/1"
        )
        print(f"Single config settings: {conf_settings}")


async def list_configuration_settings():
    credential = DefaultAzureCredential()
    async with AzureAppConfigurationClient(
        base_url="https://**********.azconfig.io", credential=credential
    ) as client:
        conf_settings = client.list_configuration_settings(
            key_filter="/existing/test/*"
        )
        print("List config settings: ")
        async for item in conf_settings:
            print(item)


async def main():
    await get_configuration_settings()
    await list_configuration_settings()


if __name__ == "__main__":
    asyncio.run(main())
```

Here is the output:

```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1062de7d0>
Single config settings: {'additional_properties': {}, 'key': '/existing/test/key/1, 'label': None, ......}
List config settings: 
{'additional_properties': {}, 'key': '/existing/test/key/1', 'label': None, .....}
{'additional_properties': {}, 'key': '/existing/test/key-new/1', 'label': None, ....}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1062dc9d0>
```

**To Reproduce**
1. Initialise default credential
2. Initilise async AzureAppConfigurationClient using context manager
3. Try to list app config settings using filter with existing keys
4. Try to get configuration settings for an existing key
5. az login
6. execute commands async

**Expected behavior**
Adequate configs returned without warning message.
Properly closing all underlying aiohttp client sessions

**Comment by YalinLi0312** [comment]
Hi @gorun2git , the unclosed session is from `credential`, you should manually close it or using `with` keyword. Please follow the examples in this doc: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/README.md#async-credentials

**Comment by gorun2git** [comment]
Hi @YalinLi0312, thank you for your quick reply.

It makes sense, I've missed this fact somehow 🤦 

With closing session, everything is working as charm. Thank you for checking this and for your help 🙏 

Closing the issue.
