### ISSUE TITLE
Authorization Content Validation Issue for learn.microsoft website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37325]
1.
**Section link:**

- https://learn.microsoft.com/en-us/python/api/overview/azure/authorization?view=azure-python#create-the-management-client
![image](https://github.com/user-attachments/assets/f7d15825-2590-455a-b2ff-b686686c7c58)

**Reason:**
Link validation issue: Broken link, please upload the correct link.

2.
**Section** [link1](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2015_07_01.models.provideroperation?view=azure-python#keyword-only-parameters), [link2](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2018_01_01_preview.models.erroradditionalinfo?view=azure-python#variables), [link3](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2018_01_01_preview.models.provideroperation?view=azure-python#keyword-only-parameters), [link4](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2018_07_01_preview.models.erroradditionalinfo?view=azure-python#variables), [link5](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2018_09_01_preview.models.erroradditionalinfo?view=azure-python#variables), [link6](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2019_08_01_preview.models.erroradditionalinfo?view=azure-python#variables), [link7](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2020_04_01_preview.models.erroradditionalinfo?view=azure-python#variables), [link8](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2020_10_01_preview.models.erroradditionalinfo?view=azure-python#variables), [link9](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2022_04_01.models.erroradditionalinfo?view=azure-python#variables), [link10](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2022_04_01.models.provideroperation?view=azure-python#keyword-only-parameters), [link11](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2022_05_01_preview.models.erroradditionalinfo?view=azure-python#variables):

![image](https://github.com/user-attachments/assets/6fbb680c-3c0b-410d-8d90-a221d3f98aa6)

**Reason:**
Format validation Issue: Format messy.

@rohit-ganguly , @lmazuel  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
