### ISSUE TITLE
Azure Stack HCI Content Validation Issue for learn.microsoft website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37328]
1.
**Section links:**

- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.arcsettingspatch?view=azure-python-preview#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.erroradditionalinfo?view=azure-python-preview#variables
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.extension?view=azure-python-preview#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.extensionpatchparameters?view=azure-python-preview#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.precheckresult?view=azure-python-preview#keyword-only-parameters

![image](https://github.com/user-attachments/assets/bf55644b-176f-4241-9333-daf245e8750a)

**Reason:**
Format validation Issue: Format messy.

2.
**Section links:**

- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.arcidentityresponse?view=azure-python-preview#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.clusteridentityresponse?view=azure-python-preview#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.passwordcredential?view=azure-python-preview#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestackhci/azure.mgmt.azurestackhci.models.rawcertificatedata?view=azure-python-preview#keyword-only-parameters

![image](https://github.com/user-attachments/assets/a6a39125-7331-4510-aaff-371c6499d38f)

**Reason:**
Format validation Issue: Miss Description.

@rohit-ganguly , @lmazuel  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
