### ISSUE TITLE
Azure Stack  Content Validation Issue for learn.microsoft website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37327]
1.
**Section** [link1](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.aio.operations.cloudmanifestfileoperations?view=azure-python#constructor), [link2](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.aio.operations.customersubscriptionsoperations?view=azure-python#constructor), [link3](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.aio.operations.linkedsubscriptionsoperations?view=azure-python#constructor), [link4](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.aio.operations.operations?view=azure-python#constructor), [link5](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.aio.operations.productsoperations?view=azure-python#constructor), [link6](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.aio.operations.registrationsoperations?view=azure-python#constructor), [link7](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.operations.cloudmanifestfileoperations?view=azure-python), [link8](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.operations.customersubscriptionsoperations?view=azure-python), [link9](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.operations.linkedsubscriptionsoperations?view=azure-python), [link10](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.operations.operations?view=azure-python), [link11](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.operations.productsoperations?view=azure-python), [link12](https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.operations.registrationsoperations?view=azure-python#constructor):

![image](https://github.com/user-attachments/assets/0c6ea513-1a07-4f74-be64-9d555008665f)

**Reason:**
Typing annotation Issue: Please unify the format, update to `*args:Any, **kwargs:Any` or `*args, **kwargs`.
![image](https://github.com/user-attachments/assets/3f946efb-b751-48d3-a6be-ff2060fcaea5)

2.
**Section links:**

- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.models.cloudmanifestfiledeploymentdata?view=azure-python#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-azurestack/azure.mgmt.azurestack.models.trackedresource?view=azure-python#keyword-only-parameters

![image](https://github.com/user-attachments/assets/eae576a7-1794-4f33-821b-245d3afb7f13)

**Notes:** Most subpages of the `models` all have this issue.

**Reason:**
Format validation Issue: Miss Description.

@rohit-ganguly , @lmazuel  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
