### ISSUE TITLE
Azure VMware Solution Content Validation Issue for learn.microsoft website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37329]
1.
**Section link:**

- https://learn.microsoft.com/en-us/python/api/azure-mgmt-avs/azure.mgmt.avs.models.erroradditionalinfo?view=azure-python#variables

![image](https://github.com/user-attachments/assets/5769985c-aac1-4076-a006-aad640069854)

**Reason:**
Format validation Issue: Format messy.

@rohit-ganguly , @lmazuel  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
