### ISSUE TITLE
Batch Content Validation Issue for learn.microsoft website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37331]
1.
**Section links:**

- https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.custom.custom_errors.createtaskserrorexception?view=azure-python#parameters
- https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.models.accountlistpoolnodecountsoptions?view=azure-python#azure-batch-models-accountlistpoolnodecountsoptions-as-dict

![image](https://github.com/user-attachments/assets/6b6f3b47-63a7-4fb6-8f63-e10a0dcec7a6)

**Notes:** Most subpages of the `models` all have this issue.

**Reason:**
Format validation Issue: Format messy.

2.
**Section links:**

- https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.models.accountlistpoolnodecountsoptions?view=azure-python#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.batch_auth.sharedkeyauth?view=azure-python#parameters
- https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.batch_auth.sharedkeycredentials?view=azure-python#parameters

![image](https://github.com/user-attachments/assets/fe8106be-e69f-40cb-aa1b-956afe4e0575)

**Notes:** Most subpages of the `models` and `batch_auth` all have this issue.

**Reason:**
Format validation Issue: Miss Description.

3.
**Section links:**

- https://learn.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.automaticosupgradepolicy?view=azure-python#keyword-only-parameters
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.upgrademode?view=azure-python
- https://learn.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.upgradepolicy?view=azure-python#keyword-only-parameters

![image](https://github.com/user-attachments/assets/ac539da8-c76c-4bdc-b845-9c5606dd2acb)

**Reason:**
Format validation Issue: Extra symbols `<br />`.

4.
**Section** [link1](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.accountoperations?view=azure-python#constructor), [link2](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.applicationoperations?view=azure-python#constructor), [link3](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.certificateoperations?view=azure-python#constructor), [link4](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.computenodeextensionoperations?view=azure-python#constructor), [link5](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.computenodeoperations?view=azure-python#constructor), [link6](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.fileoperations?view=azure-python#constructor), [link7](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.joboperations?view=azure-python#constructor), [link8](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.jobscheduleoperations?view=azure-python#constructor), [link9](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.pooloperations?view=azure-python#constructor), [link10](https://learn.microsoft.com/en-us/python/api/azure-batch/azure.batch.operations.taskoperations?view=azure-python#constructor):

![image](https://github.com/user-attachments/assets/5f867401-eaa5-4c72-b6c9-0e321311b7f2)

**Reason:**
Typing annotation Issue: Please unify the format, update to `*args:Any, **kwargs:Any` or `*args, **kwargs`.
![image](https://github.com/user-attachments/assets/5a7226e0-b0ee-4318-a942-7601931e0e21)

5.
**Section link:**

- https://learn.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.pool?view=azure-python#keyword-only-parameters

![image](https://github.com/user-attachments/assets/4f29e8c7-ae2e-4a45-8e29-9d971347910a)

**Reason:**
Link validation issue: Broken link, open the link displays `404`.

@rohit-ganguly , @lmazuel , @ronniegeraghty , @cRui861 , @dpwatrous for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
