### ISSUE TITLE
BareMetal Infrastructure Content Validation Issue for learn.microsoft website

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37330]
1.
**Section link:**

- https://learn.microsoft.com/en-us/python/api/azure-mgmt-baremetalinfrastructure/azure.mgmt.baremetalinfrastructure.models.erroradditionalinfo?view=azure-python-preview#variables

![image](https://github.com/user-attachments/assets/cf4bf401-8f8b-4699-9403-12b58f70f24b)

**Reason:**
Format validation Issue: Format messy.

@rohit-ganguly , @lmazuel  for notification.

**Comment by v-xuto** [comment]
Close this issue as we'll put it into a summarzied one.
