### ISSUE TITLE
Broken links on https://learn.microsoft.com/en-us/python/api/overview/azure/compute?view=azure-python

### ISSUE THREAD

**Issue by lovettchris** [Azure/azure-sdk-for-python#37361]
### Type of issue

Missing information

### Description

Most of the samples linked on https://learn.microsoft.com/en-us/python/api/overview/azure/compute?view=azure-python are broken links, can you fix this please?

### Page URL

https://learn.microsoft.com/en-us/python/api/overview/azure/compute?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/compute.md

### Document Version Independent Id

5b033609-afc0-a8e0-4059-89e77bbcd28d

### Article author

@azure-sdk

### Metadata

* ID: 1fc1c70b-6ce5-8115-921d-8db80c1d43db 
* Service: **compute**

**Comment by kristapratico** [comment]
@lovettchris thanks for bringing to our attention, we'll get those links patched up as soon as possible!

**Comment by ChenxiJiang333** [comment]
blue hyperlinks are broken links
![image](https://github.com/user-attachments/assets/0700df6f-e27f-455c-bf1d-3b5ed787cfb1)

**Comment by ChenxiJiang333** [comment]
close issue for link fixed

**Comment by lovettchris** [comment]
Thanks, no for extra credit, setup a system that always checks and reports all broken links.
