### ISSUE TITLE
Maps Content Validation Issue for github.io website

### ISSUE THREAD

**Issue by Yionse** [Azure/azure-sdk-for-python#37371]
1.

Section links:

- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-geolocation/1.0.0b1/index.html
- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-geolocation/1.0.0b1/azure.maps.geolocation.html
- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-search/2.0.0b1/index.html
- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-maps/2.1.0/index.html
  ![image](https://github.com/user-attachments/assets/537690c2-3780-48c8-8e59-25c32429db38)

**Reason:**

Format validation issue: Extra symbols `_`.

2.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-search/2.0.0b1/azure.maps.search.aio.html#batch-response-model):
![image](https://github.com/user-attachments/assets/b8394089-34ae-4e75-801d-55abac6268b4)
[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-search/2.0.0b1/azure.maps.search.aio.html#id10), [link3](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-search/2.0.0b1/azure.maps.search.aio.operations.html#batch-response-model), [link4](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-search/2.0.0b1/azure.maps.search.operations.html#batch-response-model), [link5](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-maps/2.1.0/azure.mgmt.maps.models.html#azure.mgmt.maps.models.Creator)

**Reason:**

Format validation issue: Text exceeds page size.(Note: Multiple occurrences)

3.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-render/2.0.0b1/azure.maps.render.aio.operations.html#azure.maps.render.aio.operations.RenderOperations):
![image](https://github.com/user-attachments/assets/f89b5e42-0b50-4b8a-a525-139c6317dc65)
[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-render/2.0.0b1/azure.maps.render.operations.html#azure.maps.render.operations.RenderOperations), [link3](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-route/1.0.0b1/azure.maps.route.models.html#azure.maps.route.models.BatchResultSummary), [link4](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-maps-search/2.0.0b1/azure.maps.search.aio.html#id10), [link5](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-maps/2.1.0/azure.mgmt.maps.operations.html#azure.mgmt.maps.operations.AccountsOperations)

**Reason:**

Typing annotation issue: Please unify the format, update to `*args:Any`, `**kwargs:Any` or `*args`, `**kwargs`.(Note: Multiple occurrences).

4.

Section link:

- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-maps/2.1.0/azure.mgmt.maps.models.html#azure.mgmt.maps.models.CreatedByType

![image](https://github.com/user-attachments/assets/0b390f84-5560-49db-bf00-2e06723227c2)

**Reason:**

Typing annotation issue: Missing type annotation for value.

@rohit-ganguly, @lmazuel, @markweitzel, @dubiety, @Lakicar95 for notification.

**Comment by dubiety** [comment]
Hi @Yionse, thank you for reporting this issue. We'll fix the issue soon!

**Comment by Yionse** [comment]
Close this issue as we'll put it into a summarzied one.
