### ISSUE TITLE
WebPubSubClient::close emits unexpected warning 

### ISSUE THREAD

**Issue by admindgard** [Azure/azure-sdk-for-python#37390]
- **Package Name**: azure-messaging-webpubsubclient
- **Package Version**: 1.1.0, 1.0.1
- **Operating System**: Mac
- **Python Version**: 3.10

**Describe the bug**
When attempting to close the webpubsub client, a warning is emitted: "The client is stopping state. Stop recovery."

It's not clear that this warning is actionable, and I can't see any way to prevent it (other than leaving the connection open, or filtering logs).

**To Reproduce**
1. create webpubsub client
2. open connection
3. (exchange messages)
4. call `client.close()`

Similarly, via the context manager:

```python
wps_url = "wss://xxxxx.webpubsub.azure.com/client/hubs/xxxxxx?access_token=xxxxxx"
credentials = WebPubSubClientCredential(client_access_url_provider=wps_url)
wps_client = WebPubSubClient(credential=credentials)
with wps_client:
    pass
```

**Expected behavior**
No warning message for happy-path usage.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
Let me take an investigation.
