### ISSUE TITLE
Allow certain response headers coming from AzurePipelinesCredential to be logged

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-python#37412]
These two response headers are useful for the service team to debug and diagnose issues, and hence it is requested that we do log them.
- x-vss-e2eid
- x-msedge-ref

We decided, other than logging them, to also add these header values to the exception message that is thrown, so they are always visible, even with logging disabled.

Given our logged headers are based on an allow list, currently these two headers are REDACTED.

https://github.com/Azure/azure-sdk-for-python/blob/0a8dfb57ae574d38a304ca447957c27aa7224f2c/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L399-L426

**Comment by ahsonkhan** [comment]
See https://github.com/Azure/azure-sdk-for-cpp/pull/6001 for an example change from C++.

**Comment by xiangyan99** [comment]
Done
