### ISSUE TITLE
The api-version '2022-04-01' is invalid. when using  malformed scope for role_assignments.list_for_scope method.

### ISSUE THREAD

**Issue by db0** [Azure/azure-sdk-for-python#37423]
The method I'm trying to use is documented here:

https://learn.microsoft.com/en-in/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2022_04_01.operations.roleassignmentsoperations?view=azure-python#azure-mgmt-authorization-v2022-04-01-operations-roleassignmentsoperations-list-for-scope

When trying to use it, once received this exception:

```
azure.core.exceptions.HttpResponseError: (InvalidApiVersionParameter) The api-version '2022-04-01' is invalid. 
```

Using a different API version results in a missing endpoint exception.

The same can be replicated directly from the azure API here: https://learn.microsoft.com/en-us/rest/api/authorization/role-definitions/list

So it seems that the Azure API removed this endpoint.

I'm using version 4.0.0 of azure-mgmt-authorization on Ubuntu.

The code I'm using for reference is

```
from azure.mgmt.authorization import AuthorizationManagementClient

[...]

  def get_role_assignments_for_vm(self, vm_id, role_definition_id, authorization_client):
    # Get role assignments for a given VM and role definition ID
    role_assignments = authorization_client.role_assignments.list_for_scope(vm_id)
    assigned_members = []
    for role_assignment in role_assignments:
        if role_assignment.role_definition_id == role_definition_id:
            principal_id = role_assignment.principal_id
            assigned_members.append(principal_id)
```

And the vm_id I'm sending is like

```
/subscriptions/00000000-0000-0000-0000-42c2f52c69f8/resourceGroups/rsg-resourcegroup-001/microsoft.compute/virtualmachines/VMNAME
```

and the authorization_client is 

```
authorization_client = AuthorizationManagementClient(credential, subscription_id)
```

**Comment by db0** [comment]
OK I managed to trace that this is a case of a malformed scope. Passing a scope which doesn't exist like the one I sent 

```
/subscriptions/00000000-0000-0000-0000-42c2f52c69f8/resourceGroups/rsg-resourcegroup-001/microsoft.compute/virtualmachines/VMNAME
```

returns a missing API.

However the correct scope

```
/subscriptions/00000000-0000-0000-0000-42c2f52c69f8/resourceGroups/rsg-resourcegroup-001/providers/microsoft.compute/virtualmachines/VMNAME
```

Works

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi @db0, the HttpResponseError was because the scope you passed was a part of the request url, so a malformed scope would make a request sent to an invaild url and cause the error. Since you have found the solution for it, I will just close this issue. You can reopen it once you have any other question.
