### ISSUE TITLE
Metrics API not working for OpenAI deployments

### ISSUE THREAD

**Issue by chintanckg** [Azure/azure-sdk-for-python#37449]
**Describe the bug**
sdk/monitor/azure-monitor-query/samples/async_samples/sample_metrics_query_async.py

--- Example given in above sample python script doesn't work with OpenAI deployments

**To Reproduce**
Run the sample script for OpenAI deployments

**Expected behavior**
OpenAI deployment related metrics should be populated (like token counts etc.)

**Comment by kristapratico** [comment]
@chintanckg can you share the the package version and example code the reproduces the issue? The sample you linked to doesn't target any metrics for Azure OpenAI (see here for supported metrics: https://learn.microsoft.com/azure/azure-monitor/reference/supported-metrics/microsoft-cognitiveservices-accounts-metrics)
