### ISSUE TITLE
AzMon Distro should enable Azure AI Inference instrumentation

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#37479]
Azure AI Inference instrumentation being added in https://github.com/Azure/azure-sdk-for-python/pull/36890 uses monkey-patching approach for instrumentation and needs someone to call `AIInferenceApiInstrumentor().Instrument()`.

The approach can change in the future and hopefully can be done inside azure-ai-inference. For now it'd be great for AzMon distro to enable it by default along with other Azure SDKs.

Once #36890 is merged, we'll need to update distro to instrument it.

**Comment by lzchen** [comment]
@lmolkova 

We've had a discussion/contract with Azure-sdk architects that we will only add future (unstable) instrumentations only as an opt-in model. This was part of our agreement to be able to include unstable components as part of a stable product (distro). Is this something that we can do for AI Inference Instrumentor as well?
