### ISSUE TITLE
[breaking change detector] fake breaking report

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#37513]
For https://github.com/Azure/azure-sdk-for-python/pull/37101/files#diff-305c23c901389ecd04810715b4aabde38dd61be024cdf58b6bde5ead8841e85b, there are many breaking items about `system_data`:
![image](https://github.com/user-attachments/assets/b3e4adb2-c9e6-4f08-9d65-1b93e0da0a48)

Actually they are fake report. For example, `Application` is inherited from `Resource`:
- In previous SDK, `Resource` doesn't have `system_data` and it is defined directly in `Application`: https://github.com/Azure/azure-sdk-for-python/blob/34a03ee1636b7f9b98b2f96a9cfeda9631dc0dbb/sdk/desktopvirtualization/azure-mgmt-desktopvirtualization/azure/mgmt/desktopvirtualization/models/_models_py3.py#L306
- In current SDK, `Resource` already has `system_data` and `Application` could call `super().__init__` to have it: https://github.com/Azure/azure-sdk-for-python/blob/f8c9b7d6f659c6d1a286cbdacf04bb7a00b1cdf9/sdk/desktopvirtualization/azure-mgmt-desktopvirtualization/azure/mgmt/desktopvirtualization/models/_models_py3.py#L168

**Comment by catalinaperalta** [comment]
Looking into this one, I'll let you know what I find
