### ISSUE TITLE
TokenCachePersistenceOptions apparently not working with DeviceCodeCredential

### ISSUE THREAD

**Issue by benprofessionaledition** [Azure/azure-sdk-for-python#37576]
- **Package Name**:  `azure.identity`
- **Package Version**:  1.18.0
- **Operating System**: Linux/Mariner
- **Python Version**: 3.10.14

**Describe the bug**
When instantiating a `DeviceCodeCredential` using `TokenCachePersistenceOptions`, nothing appears to be cached and I need to re-authenticate using the device code flow every time.

**To Reproduce**
The following script is a minimal example using AzureML. It prompts for a Device Code and then logs in. 
```
import os

from azure.ai.ml import MLClient
from azure.identity import DeviceCodeCredential, TokenCachePersistenceOptions

from .constants import AML_SUBSCRIPTION_ID, AML_RESOURCE_GROUP, AML_WORKSPACE


cache_path = os.path.expanduser("~/.azure/msal_token_cache.json")

token_cache_options = TokenCachePersistenceOptions(name=cache_path, allow_unencrypted_storage=True)
credential = DeviceCodeCredential(token_cache_persistence_options=token_cache_options)

client = MLClient(
    credential=credential,
    subscription_id=AML_SUBSCRIPTION_ID,
    resource_group_name=AML_RESOURCE_GROUP,
    workspace_name=AML_WORKSPACE,
)

# do something useless that requires authentication
jobs = client.jobs.list()
_ = [j.name for j in jobs]

print("Successfully ran the script")
```

**Expected behavior**
I would expect that running this script a second time, or instantiating a new DeviceCodeCredential and getting a token from it, would not request authentication again. 

**Screenshots**
n/a

**Additional context**
I have scoured every single available resource online, including documentation and the source code and cannot figure out how to actually cache these credentials/tokens/authorization records/whatever it is that's necessary to prevent having to log in every single time. I am fine using a different credential type if the cache exists, however `DefaultAzureCredentials` uses a different tenant ID, and seemingly continues to do so even if I specify the tenant ID in the constructor.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Please refer https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TOKEN_CACHING.md for samples how to authenticate a user silently.

**Comment by Saxamos** [comment]
Hello, I have exactly the same issue here. I can't manage to see the created file. I have also tried the following:
```        
cache = SerializableTokenCache()
if os.path.exists(token_cache_file):
    with open(token_cache_file, "r") as f:
        cache.deserialize(f.read())

def cache_persistence_callback(token_cache):
    with open(token_cache_file, "w") as f:
        f.write(token_cache.serialize())

cache_persistence_options = TokenCachePersistenceOptions(
            before_cache_access=cache_persistence_callback,
            after_cache_access=cache_persistence_callback,
            allow_unencrypted_storage=True
)
DeviceCodeCredential(
            timeout=timeout,
            token_cache=cache,
            cache_persistence_options=cache_persistence_options,
)
```
