### ISSUE TITLE
additionally_allowed_tenants config not found in Spark session for Multi-tenant app

### ISSUE THREAD

**Issue by soumikdas-oa** [Azure/azure-sdk-for-python#37583]
We have a multi-tenant Azure app (Tenant A, Tenant B). We are using Tenant A's Service Principle credentials to access the ADLS files on Tenant B. We are using pySpark for this job.

Using the above multi-tenant app credential, we are getting 401 unauthorized error in spark session.

But if we are using Python library (azure.identity), then using the following 'additionally_allowed_tenants' options enables us to authorize the access Tenant B's ADLS containers using Tenant A's credentials.

`default_credential = DefaultAzureCredential(additionally_allowed_tenants=['*'])`

We want to achieve the same with pySpark, but we can't see any option or configuration available to do it through Spark session.

We are using:
- Apache Spark 3.5.0
- Databricks Notebook (Runtime Version 14.3 LTS)
- [Azure Service Principle](https://docs.databricks.com/en/connect/storage/azure-storage.html#language-Azure%C2%A0service%C2%A0principal)
- Latest version of Identity (1.18.0) and Storage (12.23.0) as on today while connecting the ADLS container using Python libraries.

Please guide us to resolve this issue.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

This repo is for azure sdks.

If you want to submit a feature request for pyspark, you can open issues in https://github.com/apache/spark/tree/master/python.
