### ISSUE TITLE
Machine Learning Readme Issue

### ISSUE THREAD

**Issue by zimuli157** [Azure/azure-sdk-for-python#37608]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ml/azure-ai-ml/README.md):

![image](https://github.com/user-attachments/assets/b819126f-9b44-45d4-8a30-e180282965b8)

**Reason:**
Link error: Link Mismatch.

**Suggestion:**
Add link `https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/ml/azure-ai-ml/samples` to `Samples`.

@rohit-ganguly , @lmazuel , @johanste , @achauhan-scc  for notification.

**Comment by achauhan-scc** [comment]
@zimuli157 - Samples link is correctly pointing to example repo which has detail samples with scenario, sample folder in SDK repo is mostly used for doc string generation.
