### ISSUE TITLE
Cannot set metadata from the "upload_blob_from_url" function in blob services

### ISSUE THREAD

**Issue by EchelonFour** [Azure/azure-sdk-for-python#37634]
**Describe the bug**
In an azure blob service, the `upload_blob_from_url()` function is what calls the [Put Blob From URL](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url) API, but it does not support setting metadata values with the `x-ms-meta-name` header. It looks like the bindings aren't in python at all.

**Expected behavior**
Being able to set metadata in the same call as the upload blob command.

**Comment by jalauzon-msft** [comment]
Hi @EchelonFour Frank, it looks like you are correct, and we don't currently support `metadata` for the `upload_blob_from_url` API. This is likely just something we missed. We will work to get it added in an upcoming release.

As a workaround, you can try specifying the metadata headers yourself in the `headers` keyword that all APIs support. This is just a dictionary of any custom header you would like to provide to any request. This is actually all the SDK does for APIs that support metadata. See [here](https://github.com/Azure/azure-sdk-for-python/blob/f6f3011c38a495d9b5cdddcd00c7b6713a62f318/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client_helpers.py#L145-L146) and [here](https://github.com/Azure/azure-sdk-for-python/blob/f6f3011c38a495d9b5cdddcd00c7b6713a62f318/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/request_handlers.py#L140) for example.

This would look something like this:
```py
headers = {'x-ms-meta-key1': 'value1', 'x-ms-meta-key2': 'value2'}
blob_client.upload_blob_from_url(..., headers=headers)
```
