### ISSUE TITLE
Deserialize data error

### ISSUE THREAD

**Issue by snelis** [Azure/azure-sdk-for-python#37646]
- **Package Name**: 
azure-mgmt-billing
- **Package Version**: 
7.0.0
- **Operating System**:
linux
- **Python Version**: 
3.12.4

**Describe the bug**
```
client.billing_subscriptions.list_by_billing_account(
    BILLING_ACCOUNT,
    top=1,
)
```

throws error:
```
Traceback (most recent call last):
  File ".../lib/python3.12/site-packages/azure/mgmt/billing/_serialization.py", line 1959, in deserialize_iso
    raise ValueError("Invalid datetime string: " + attr)
ValueError: Invalid datetime string: 2020-04-21
```

**Expected behavior**
Expected serialized response, not an exception

**Additional context**
debugging `azure/mgmt/billing/_serialization.py` :
```
match = Deserializer.valid_date.match(attr)
if not match:
    breakpoint()
    raise ValueError("Invalid datetime string: " + attr)
```
```
ipdb> attr
'2020-04-21'

ipdb> Deserializer.valid_date
re.compile('\\d{4}[-]\\d{2}[-]\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.?\\d*Z?[-+]?[\\d{2}]?:?[\\d{2}]?')
```

**Comment by kashifkhan** [comment]
Thank you for the feedback @snelis . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
@ChenxiJiang333 Please help on this issue.

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
Hi, @snelis, could you help follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to share the log about how the datetime shows like in the response from the service?

**Comment by snelis** [comment]
Well with the debugging logs I dont see the response body

```
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': 'edf7d1ee-861e-11ef-bb96-c12373fc2cdf'
    'User-Agent': 'azsdk-python-mgmt-billing/7.0.0 Python/3.12.4 (Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35)'
    'Authorization': 'REDACTED'
No body was attached to the request
2024-10-09 11:14:48,034 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Content-Length': '33655'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-ratelimit-remaining-tenant-resource-requests': '499'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-service-version': 'REDACTED'
    'api-supported-versions': 'REDACTED'
    'X-Frame-Options': 'REDACTED'
    'x-ms-request-id': '9237989d-dbd5-4f6c-9978-57678b906bac'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'X-Cache': 'REDACTED'
    'X-MSEdge-Ref': 'REDACTED'
    'Date': 'Wed, 09 Oct 2024 09:14:47 GMT'
```

however like i said in my first message i did put a breakpoint where it fails to inspect the response.
If i step back to the response i see this:

```
'enrollmentAccountSubscriptionDetails': {'enrollmentAccountStartDate': '2020-04-21', 'subscriptionEnrollmentAccountStatus': 'Deleted'}
```

This property is defined as iso-8601 
https://github.com/Azure/azure-sdk-for-python/blob/c065216fc6a324480df24e7b0e9ba26cf6e551ea/sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/_models_py3.py#L4055

This deserializer uses:
```
ipdb> Deserializer.valid_date
re.compile('\\d{4}[-]\\d{2}[-]\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.?\\d*Z?[-+]?[\\d{2}]?:?[\\d{2}]?')
```

And `2020-04-21` does not match this regex

**Comment by ChenxiJiang333** [comment]
Hi @snelis, by this [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/billing/resource-manager/Microsoft.Billing/stable/2024-04-01/billingSubscription.json#L1790), `enrollmentAccountStartDate`'s format was defined as `date-time` which should follow the [iso-8601](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) protocol. So, the value `2020-04-21` returned by the service is not correct and SDK owner cannot solve it. Please open an issue at https://github.com/Azure/azure-rest-api-specs/issues to turn to the service team for the fix.
