### ISSUE TITLE
Document Intelligence analysis is taking forever

### ISSUE THREAD

**Issue by galvangoh** [Azure/azure-sdk-for-python#37659]
- **Package Name**: azure-ai-documentintelligence==1.0.0b2
- **Operating System**: Windows
- **Python Version**: 3.10.9

**Describe the bug**
Running the following code which uses a custom classifier and it takes forever to complete. Same goes for the studio. 

**To Reproduce**
```python
from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import ClassifyDocumentRequest

document_intelligence_client = DocumentIntelligenceClient(
    endpoint='my-document-intelligence-endpoint',
    credential=AzureKeyCredential(doc_intel_key)
)

result = document_intelligence_client.begin_classify_document(
            classifier_id='my-classifier-id',
            classify_request=ClassifyDocumentRequest(
                url_source='the-blob-sas-url'
            ),
            split='auto'
).result()
```

**Expected behavior**
Classification should take at most 7 to 8 seconds.

**Comment by jricke** [comment]
I'm having issues as well with dotnet sdk using blob url with sas token. taking the generated url pulls down the image from my machine, but no response when processing from the SDK. get an error when trying the document intelligence studio with the same url saying it can't access the url.

**Comment by YalinLi0312** [comment]
@jricke Thanks for your contact, we'll investigate asap!
You attached the timeout issue in sovereign clouds, I'm wondering is this issue also happened in sovereign clouds? We have a similar [test](https://github.com/Azure/azure-sdk-for-python/blob/51a22b0399298b00ac2da11e659c97a11178649f/sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_classify_document.py#L83) on public cloud, but don't see the issue.

@bojunehsu It's hanging when classifying document using SDK and studio. it looks like an issue in service. Can you help to take a look?

**Comment by jricke** [comment]
Hi @YalinLi0312 , the service seems to be working as intended now. For a couple of days earlier this week, the service was not coming back with a response. I just processed a document and it came back right away.

**Comment by YalinLi0312** [comment]
@jricke Glad to hear the issue is resolved, thank you!
