### ISSUE TITLE
[Document Intelligence] Incremental training on Studio & Python SDK

### ISSUE THREAD

**Issue by galvangoh** [Azure/azure-sdk-for-python#37680]
Will there be a release for incremental training of custom models in the studio and python sdk?

**Comment by xiangyan99** [comment]
Thanks for reaching out, we’ll investigate asap.

**Comment by bojunehsu** [comment]
There are currently no plans to support this.  One option is to retain the original training data and train a new custom with the combined data.  You can now increase [max_training_hours](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-ai-documentintelligence/latest/azure.ai.documentintelligence.models.html#azure.ai.documentintelligence.models.BuildDocumentModelRequest) to more effectively utilize larger training set size.
