### ISSUE TITLE
max_size_in_bytes value error incorrect f-string

### ISSUE THREAD

**Issue by arheops** [Azure/azure-sdk-for-python#37695]
- azure/service_bus/aio: 
- current: 
- MacOs:
- python 3.10: 

**Describe the bug**
In serviceBusSender create_message_batch at line 484 it has line like this

"acceptable max batch size is: {self._max_message_size_on_link} bytes."

missed f-string, should be like this

f"acceptable max batch size is: {self._max_message_size_on_link} bytes."f

**To Reproduce**
1
create batch with size of 10Mb

**Expected behavior**
Correct message about error

**Screenshots**
![image](https://github.com/user-attachments/assets/a7fab871-cb14-4133-8572-8c2fe41184b3)

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @arheops . We will get a fix out quickly :)
