### ISSUE TITLE
Azure AI Inference: remove @distributed_trace(_async) from chat completion operations

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#37729]
Chat completion operations are being instrumented in https://github.com/Azure/azure-sdk-for-python/pull/36890 .

Along with  https://github.com/Azure/azure-sdk-for-python/blob/c0a71880f091802a7b5f6e530a4ecec30c339abb/sdk/ai/azure-ai-inference/azure/ai/inference/aio/_patch.py#L440 they result in redundant span recorded by `@distributed_trace` annotation. 

![image](https://github.com/user-attachments/assets/bada0e42-c2d4-4ce7-ae12-4d70c99988a3)

We need to make sure we don't double-instrument chat completion calls (and others what we might instrument in the future).

**Comment by dargilco** [comment]
Thank you for reporting this @lmolkova! @M-Hietala can you please have a look at this?

**Comment by M-Hietala** [comment]
This has already been removed.
