### ISSUE TITLE
AzureCliCredential timeout when called in parallel.

### ISSUE THREAD

**Issue by xkszltl** [Azure/azure-sdk-for-python#37739]
- **Package Name**: azure-identity
- **Package Version**: latest
- **Operating System**: Linux
- **Python Version**: All

**Describe the bug**

AzureCliCredential always times out when called in parallel.
In our test we have 11 concurrent calls and 3-5 of them will fail, with a confusing msg suggesting azure cli not found instead of request timeout:
- https://github.com/Azure/azure-sdk-for-python/blob/c0a71880f091802a7b5f6e530a4ecec30c339abb/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L257

We also believe the 10s default timeout is too short:
- https://github.com/Azure/azure-sdk-for-python/blob/c0a71880f091802a7b5f6e530a4ecec30c339abb/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L54

**Comment by xiangyan99** [comment]
Thanks for reaching out.

the process_timeout is configurable. You can use AzureCliCredential(process_timeout=30).

Does this work for you?

**Comment by xkszltl** [comment]
We are aware of that config but that only works for the direct user of it.
For libs using AzureCliCredential internally without exposing this option, e.g. a functional lib or a auth wrapper, there's no much we can do for mitigation.
This is especially true for libs using DefaultAzureCredential, as the config pass-through is not well-documented and people are more likely to expect DefaultAzureCredential to work by default.

**Comment by xiangyan99** [comment]
I don't think "using AzureCliCredential internally without exposing this option" is the right way to use the identity library.

Can you share the reason why you implement in this way?

Please feel free reach out to me offline.

**Comment by xkszltl** [comment]
For example, module built upon an azure service, e.g. a tool depending in private azure blob, would auth internally with DefaultAzureCredential so that user can call this tool without massing with auth details.

Another example is tool depending on many azure service, each with their own scope or permission, would have many instances of credentials hiding deep inside.

When we want to integrate this kind of tools to our own code, there's no way for us to provide custom auth.

**Comment by xiangyan99** [comment]
Thank you for the information.

Azure CLI is primarily a development/DevOps tool and not ideal for production environments.

If I understand correctly, you’ve hardcoded `DefaultAzureCredential` in your library. So if you need a longer timeout, would it be possible to hardcode that in the library as well?

Does that work for you?
