### ISSUE TITLE
Getting default subscription

### ISSUE THREAD

**Issue by markjbrown** [Azure/azure-sdk-for-python#37736]
- **azure.mgmt.resource.subscriptions.aio**: 
- **23.1.1**: 
- **Windows-11-10.0.26100-SP0**:
- **3.12.7**: 

Also tried:
- **azure.mgmt.subscription.aio**
- **3.1.1**

**Describe the bug**
Trying to get the default subscription for current logged in user.

**To Reproduce**
1. Following the example provided here, https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/resources/manage_resource_subscriptions.py#L20-L24

**Expected behavior**
I thought that the State = Enabled property determined whether a subscription was the default but they all return this. I'm trying to replicate the behavior of az cli to allow a user to simply authenticate and not have to know the current subscription they are working in without having to use az cli.

**Additional context**
This is for a series of azure management SDK samples for Cosmos DB, https://github.com/AzureCosmosDB/management-sdk-samples

**Comment by kashifkhan** [comment]
Thank you for the feedback @markjbrown . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
@ChenxiJiang333 Please help on this issue.

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
Hi @markjbrown, subscription is a container for the resources, and it seems there's not a method to bind a user with one subscription. For the SDK, subscription id is a necessary parameter to manage resources, and I guess users would still need to choose a subscription when running az cli commands to manage resources as well.

**Comment by ChenxiJiang333** [comment]
> I think you misunderstood.
> 
> How do I replicate this using Python SDK? `az account list`
> 
> The subscription information returned here includes a property, "isDefault" I want that value so I can filter for true, then return the subscription id so the user can then do subsequent operations on resources within it.

The "isDefault" property is set by command `az account set --subscription`, and it's stored in local. Subscription does not have such property defined in the service so the SDK cannot get it.

**Comment by markjbrown** [comment]
Ah got it. That explains why I could not find it. Thank you!
