### ISSUE TITLE
Message to a partitioned entity with duplicate detection enabled must have either PartitionKey or MessageId

### ISSUE THREAD

**Issue by arielpontes** [Azure/azure-sdk-for-python#37744]
Same as issue #21955, I don't understand why it was closed with no explanation.

**Comment by kashifkhan** [comment]
Hi @arielpontes, I have addressed this in #36333 and will link it here for searching etc. I was able to confirm that this is not implemented by the service, with the recommendation being not to use batching if deduplication is needed on a partitioned entity.
