### ISSUE TITLE
Clarify Azure ML client reuse

### ISSUE THREAD

**Issue by bastbu** [Azure/azure-sdk-for-python#37780]
**Is your feature request related to a problem? Please describe.**

I am using the Azure ML SDK inside an Azure Function. I've measured that reusing a (global) Azure ML SDK `MLClient` instance throughout the application is significantly faster, compared to instantiating a new client for every operation, even when reusing the Azure Identity credential. Since synchronous Azure Functions can be scaled via a thread pool, this means that the `MLClient` would be shared across multiple threads.

Is `MLClient` and its instance methods thread-safe and supports being reused throughout the application?

Other Azure SDKs, such as the [Azure Blob Storage SDK](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-client-management?tabs=python#client-immutability-and-thread-safety) or [Azure Identity](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/TOKEN_CACHING.md#in-memory-token-caching) document whether their API is thread-safe or not.

**Describe the solution you'd like**

If the `MLClient` is safe to be shared across threads, it would be great to document it is. If it's not, it would be great to make it thread safe.

**Describe alternatives you've considered**

Creating an `MLClient` on each request, or alternatively maintain our own pool of `MLClient`s.

**Comment by achauhan-scc** [comment]
Thanks for feedback, Credential and other configuration values can't be modified after an instance of ML client is created makes it immutable object, I have created an internal work item to update the documentation.

**Comment by achauhan-scc** [comment]
SDK current implementation has a limitation, where environments.share method is overriding the client to registry client causing multi thread application to break.
