### ISSUE TITLE
MAX_BLOCK_SIZE / documentation outdated?

### ISSUE THREAD

**Issue by AljoSt** [Azure/azure-sdk-for-python#3778]
Here: https://docs.microsoft.com/en-gb/python/api/azure-storage-blob/azure.storage.blob.blockblobservice.BlockBlobService?view=azure-python it's specified that `Each block can be a different size, up to a maximum of 4 MB`. In the sdk (`blockblobservice.py`) it says: `Each block can be a different size, up to a maximum of 100 MB`. The variable that (I guess) corresponds to this specifies 4MB (`MAX_BLOCK_SIZE = 4 * 1024 * 1024`). 
Dunno which is correct as I just started to play with the sdk, but I guess something needs to be updated.

**Comment by lmazuel** [comment]
@AljoSt This is a Storage issue, wich is handled in its own repo for now.

@zezha-msft now you can transfer issue to your repo with Github, look at the "Transfer this issue [Beta]" button on the bottom right. I would encourage you to do it here :)

**Comment by zezha-msft** [comment]
Hi @AljoSt, the max block size limit is 100MB, the docs need to be regenerated. Thanks for bringing up this issue!

@lmazuel I do not see the issue transfer button, could you please transfer it to the Storage repo?

**Comment by lmazuel** [comment]
@zezha-msft I need admin permissions on your repo to do so. I won't use that power to do any harm, I promise ;)

**Comment by zezha-msft** [comment]
Hi @lmazuel, sure! Sorry for the late reply, I've been OOF.

@pemari-msft Could you please add @lmazuel to our repo?
