### ISSUE TITLE
DefaultAzureCredentials.get_token invalid response after using az login

### ISSUE THREAD

**Issue by mmicek** [Azure/azure-sdk-for-python#37841]
azure-identity = "^1.19.0"
Ubuntu 20
Python 3.11

I am using DefaultAzureCredentials and i want to use AzureCliCredential. I would like to call get_token() method for BlobStorage and get token for logged user.

This is my very simple code:

`credential = AzureCliCredential()
token = credential.get_token("https://storage.azure.com/.default")
print(token.token)`

Before that i am using **az login** in terminal inside python environment, and i am succesfully logged in.

In **azure.identity._credentials.azure_cli.parse_token** method i am getting exception due to invalid json.
Azure can see me be logged into, and returns access_token and other stuff but adds some additional 
invalid signs at the end of string so it makes string invalid json.

![Image](https://github.com/user-attachments/assets/cab465ab-c4a1-44e7-b37f-813b1eeba55d)

How to get AzureCliCredential working properly?

Exception:
`  AzureCliCredential: Unexpected output from Azure CLI: '{
  ****,
  "expiresOn": "2024-10-10 19:23:33.461197",
  "subscription": "proper_value_here",
  "tenant": "proper_value_here",
  "tokenType": "Bearer"
}
'. 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.`

**Comment by pvaneck** [comment]
This appears to be some edge case dealing with console colorization when running code directly in PyCharm as described here: https://github.com/tartley/colorama/issues/263

This was supposedly fixed for `AzureCliCredential` in this [PR](https://github.com/Azure/azure-sdk-for-python/pull/11362) a while back.

Can you run `az --version` in the terminal you are using and paste the contents? I am wondering if this could be mitigated by just updated `az`.

**Comment by mmicek** [comment]
`azure-cli                         2.0.81

core                              2.0.81
telemetry                          1.0.4

Python location '/usr/bin/python3'
Extensions directory '/home/adn/.azure/cliextensions'

Python (Linux) 3.8.10 (default, Sep 11 2024, 16:02:53) 
[GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Unable to check if your CLI is up-to-date. Check your internet connection.
Please let us know how we are doing: https://aka.ms/clihats

**Comment by mmicek** [comment]
`azure-cli                         2.0.81

core                              2.0.81
telemetry                          1.0.4

Python location /usr/bin/python3
Extensions directory '/home/adn/.azure/cliextensions'

Python (Linux) 3.8.10 (default, Sep 11 2024, 16:02:53) 
[GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Unable to check if your CLI is up-to-date. Check your internet connection.
Please let us know how we are doing: https://aka.ms/clihats`

**Comment by mmicek** [comment]
I have some old version of this library, and i tried to update it but why newest version of azure-cli depends on some old azure-mgn-containerapp library?

`Because azure-cli (2.65.0) depends on azure-mgmt-appcontainers (2.0.0)
 and no versions of azure-cli match >2.65.0,<3.0.0, azure-cli (>=2.65.0,<3.0.0) requires azure-mgmt-appcontainers (2.0.0).
So, because epo-data-loader depends on both azure-mgmt-appcontainers (^3.0.0) and azure-cli (^2.65.0), version solving failed.`

**Comment by pvaneck** [comment]
Yep, looks it this is just a matter of the `azure-cli` version being too old. 

`azure-cli` pins a lot of dependencies which might not work well with your application's dependencies if you installed `azure-cli` via `pip`/`poetry`. Typically, it's recommended to install the CLI using your OS distribution's package manager, as this will isolate the `azure-cli` dependencies. Check the instructions [here](https://learn.microsoft.com/cli/azure/install-azure-cli-linux?pivots=apt).
