### ISSUE TITLE
Retrieve the usage for the automation account got failed

### ISSUE THREAD

**Issue by Fred-sun** [Azure/azure-sdk-for-python#37856]
- **Package Name**:  azure-mgmt-automation
- **Package Version**:  v1.0.0 / v1.1.0b3
- **Operating System**: Ubuntu
- **Python Version**:  3.10.12

**Describe the bug**
Try to retrieve the usage for the automation account.  Failed to iterate over the returned result with error code: InternalServerError
Error Msg: An error has occurred
**To Reproduce**
1.  Create a new automation account by _automation_account_operations.py create_or_update method,
2. Try to retrieve the usage for the automation account by _usages_operations.py list_by_automation_account method
3. Failed while traversing the return result,  Error Code( InternalServerError)

**Expected behavior**
Retrieve the usage for automation account!
**Screenshots**
![Image](https://github.com/user-attachments/assets/0e978b56-e06c-4386-9e23-aaa912be4dd6)

**Additional context**

**Comment by Fred-sun** [comment]
Any update?

**Comment by msyyc** [comment]
@ChenxiJiang333 please help on this issue.

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
Hi @Fred-sun It's the service issue and we have to seek help from service team, please follow this issue: https://github.com/Azure/azure-rest-api-specs/issues/31077.

**Comment by Fred-sun** [comment]
@ChenxiJiang333 Yes， Thanks for your feedback! We can close it!
