### ISSUE TITLE
Data Assets Created with SDK1 No Longer Appear in the Data Asset List

### ISSUE THREAD

**Issue by mouhannadali** [Azure/azure-sdk-for-python#37875]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
We have encountered an issue where data assets that were created using the Azure Machine Learning SDK v1 are no longer appearing in the Data Asset List in the Azure ML Studio or via SDK v2. This issue has impacted our ability to manage and access older datasets.

**To Reproduce**
1. Create a data asset using Azure ML SDK v1.
2. Navigate to the Data Assets section in Azure ML Studio or attempt to list the data assets using SDK v2.
3. Observe that the data asset created with SDK1 does not appear in the list.

**Expected behavior**
Data assets created using SDK v1 should still be visible and accessible in the Data Asset List, even after upgrading to SDK v2 or using the Azure ML Studio interface.

**Comment by achauhan-scc** [comment]
@mouhannadali - You can map your V1 data assets with V2. Please follow the link below
https://learn.microsoft.com/en-us/azure/machine-learning/migrate-to-v2-assets-data?view=azureml-api-2
