### ISSUE TITLE
Exceptions are reported twice in Application Insights using Azure Functions

### ISSUE THREAD

**Issue by viktor-morin** [Azure/azure-sdk-for-python#37919]
- **azure-monitor-opentelemetry**: 
- **1.6.1**: 
- **Linux**:
- **3.11**: 

**Describe the bug**
Running an Azure Function, which listen to an eventhub (not sure if it's relevant), causing exception to be logged twice.

**To Reproduce**
function_app.py
```python
import azure.functions as func
import json
import os
from typing import Iterable
from azure.monitor.opentelemetry import configure_azure_monitor

counter = 0
app = func.FunctionApp()

@app.blob_input(
    arg_name="eventconfig",
    connection="AzureWebJobsStorage",
    path="config/event_config.json",
    data_type=func.DataType.BINARY,
)
@app.event_hub_message_trigger(
    arg_name="events",
    data_type=func.DataType.BINARY,
    event_hub_name="EVENT_HUB_NAME",
    connection="EVENT_HUB_CONNECTION_STRING",
    consumer_group=os.environ["EVENT_HUB_CONSUMER_GROUP"],
    cardinality=func.Cardinality.MANY,
)
def eventhub_trigger(events: Iterable[func.EventHubEvent], eventconfig: bytes):
    configure_azure_monitor()
    global counter
    counter = counter + 1
    raise Exception(f"Counter: {counter}")

```

requirements.txt
```text
azure-functions
azure-data-tables==12.*
azure-identity==1.*
azure-keyvault-secrets==4.*
tzdata
```
local.settings.json
```json
{
  "IsEncrypted": false,
  "Values": {
    "APPLICATIONINSIGHTS_CONNECTION_STRING": "InstrumentationKey=xxxxx"
  }
}
```

**Expected behavior**
We expect the exception to only be logged once in Application Insights

**Screenshots**
Same exception is shown twice
![Image](https://github.com/user-attachments/assets/a8b72f7f-fcad-41d4-9f20-ca52ce978455)

**Additional context**
NA

**Comment by kashifkhan** [comment]
Hi @viktor-morin, for azure functions an issue needs to be created in their repo https://github.com/Azure/Azure-Functions/issues. The trigger for eventhub is managed by them.
