### ISSUE TITLE
[ML] Fix pylint

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#37910]
The following pylint in [this pr](https://github.com/Azure/azure-sdk-for-python/pull/37909) has been disabled in order to unblock core -- 

these need to be reviewed and accurately handled to align with best coding practices: @azureml-github

**Comment by PratibhaShrivastav18** [comment]
This is taken care of with this PR https://github.com/Azure/azure-sdk-for-python/pull/38979
