### ISSUE TITLE
Sample for azure-ai-documentintelligence fails with "NameError: name 'AnalyzeDocumentRequest' is not defined"

### ISSUE THREAD

**Issue by dcasota** [Azure/azure-sdk-for-python#37924]
- **azure-ai-documentintelligence**: 
- **1.0.0b4**: 
- **Windows Server 2025 Build 26304.5000**:
- **3.13.0**: 

**Describe the bug**
The python sample in https://learn.microsoft.com/en-us/training/modules/plan-form-recognizer-solution/3-resources?pivots=python fails with 
"NameError: name 'AnalyzeDocumentRequest' is not defined"

**To Reproduce**
1. Install vanila Windows Server 2025
2. Python Releases for Windows | Python.org --> download and install python 3.13.0
3. `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py` 
4. Add path to user variable PATH 
5. `pip install azure-ai-documentintelligence`
6. Python IDLE shell, open a document and paste the python code 

```
from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeResult

endpoint = "xxxxx"
key = "xxxxx"

docUrl = "https://www.ensi.ch/en/wp-content/uploads/sites/5/2024/09/Organigramm_E_01.10.2024.pdf"

document_analysis_client = DocumentIntelligenceClient(endpoint=endpoint, 
    credential=AzureKeyCredential(key))

poller = document_analysis_client.begin_analyze_document("prebuilt-layout", AnalyzeDocumentRequest(url_source=docUrl))
result: AnalyzeResult = poller.result()
```

Accordingly to https://github.com/Azure/azure-sdk-for-python/blob/azure-ai-documentintelligence_1.0.0b4/sdk/documentintelligence/azure-ai-documentintelligence/MIGRATION_GUIDE.md, the function has been migrated.

**Expected behavior**
Sample runs smoothly.

**Screenshots**
![Image](https://github.com/user-attachments/assets/3acb7d00-fcbb-4021-99f5-17a4fe726a1d)

**Comment by YalinLi0312** [comment]
Hi @dcasota , thanks for your contact!
You didn't import `AnalyzeDocumentRequest`, please add `from azure.ai.documentintelligence.models import AnalyzeDocumentRequest` and try running again.

**Comment by dcasota** [comment]
@YalinLi0312 Thank you. Yes, that function import was missing. I didn't start thinking and simply processed the docs' content instead of browsing the class. Shame on me.

```
from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeResult
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest 

endpoint = "<your endpoint>"
key = "<your key>"

docUrl = "<your url>"

document_analysis_client = DocumentIntelligenceClient(endpoint=endpoint, 
    credential=AzureKeyCredential(key))

poller = document_analysis_client.begin_analyze_document("prebuilt-layout", AnalyzeDocumentRequest(url_source=docUrl))
result: AnalyzeResult = poller.result()
```
