### ISSUE TITLE
ManagedIdentityCredential.get_token behaves inconsistenly depending on how you pass client_id

### ISSUE THREAD

**Issue by joepatol** [Azure/azure-sdk-for-python#37960]
- **Package Name**: azure-identity
- **Package Version**: 1.19.0
- **Operating system**: Ubuntu 22.04.5 LTS
- **Python Version**: 3.11

**Describe the bug**
Depending on where `client_id` is passed to the constructor of `ManagedIdentityCredential` the `get_token` method behaves differently.

```python
managed_identity = None
cred = ManagedIdentityCredential(identity_config={"client_id": managed_identity})
cred.get_token("some_scope")
```

Raises a `CredentialUnavailableError`

```python
managed_identity = None
cred = ManagedIdentityCredential(client_id=managed_identity)
cred.get_token("some_scope")
```

Returns a token based on system assigned managed identity (with an id value of `''`)

**To Reproduce**
1. Run the code as described above

**Expected behavior**
I'd expect the behavior to be identical regardless of how `client_id` is passed.

**Screenshots**

**Additional context**
I believe the issue originates from the `ManagedIdentityClientBase` class.

```python
class ManagedIdentityClientBase(abc.ABC):
    # pylint:disable=missing-client-constructor-parameter-credential
    def __init__(
        self,
        request_factory: Callable[[str, dict], HttpRequest],
        client_id: Optional[str] = None,
        identity_config: Optional[Dict] = None,
        **kwargs: Any
    ) -> None:
        self._custom_cache = False
        self._cache = kwargs.pop("_cache", None)
        if self._cache:
            self._custom_cache = True
        else:
            self._cache = TokenCache()
        self._content_callback = kwargs.pop("_content_callback", None)
        self._identity_config = identity_config or {}
        if client_id:  # Here client_id is not appended to identity_config if its None
            self._identity_config["client_id"] = client_id
        self._pipeline = self._build_pipeline(**kwargs)
        self._request_factory = request_factory
```

Later on in `_format_parameters_helper` an error is raised if any of the `identity_config` parameters is `None`. But in the case where it was passed as a keyword argument it's never appended to the `identity_config`.

When using `ChainedTokenCredential` this is especially cumbersome. In my use-case when `client_id = None` I want another credential to be used, so the case where an error is raised is what I need. Since we upgraded from 1.17.0 I was forced to choose between passing `client_id` in the constructor directly or in `identity_config` due to the added validation check, and suddenly my code broke since I picked the direct option.

I also noticed that the type hint for `identity_config` is `dict[str, str]` so `client_id` is not allowed to be `None` it seems. I'm not really sure what the intended behavior is, but it's at least confusing.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

As you can see client_id=None is not invalid in identity_config.

Please use string instead or don't set client_id into identity_config if it is none.

**Comment by joepatol** [comment]
Hi @xiangyan99 thanks for your reply.

Thats my point, `identity_config` is not valid is `None`, although it does exactly what I need. Namely for `ManagedIdentityCredential.get_token` to fail so I can fallback to another credential. 

If I pass it as a keyword argument, then `ManagedIdentityCredential.get_token` **always** returns a possibly invalid token as it's not validated in the that case.

This makes using `ChainedTokenCredential` impossible as it just always returns a token. 

So either the type hint for `identity_config` is incorrect or the behavior when passing `client_id` as an argument is incorrect.
