### ISSUE TITLE
ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials'

### ISSUE THREAD

**Issue by jtamma** [Azure/azure-sdk-for-python#37961]
- **Package Name**: nexusidentity
- **Package Version**: 1.0.0b1
- **Operating System**: windows
- **Python Version**:  3.11

**Describe the bug**
When running the "az nexusidentity gen-keys" cli, I am running into the below error.

`az nexusidentity gen-keys`
`The command failed with an unexpected error. Here is the traceback:
cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\core\credentials.pyc)`

**To Reproduce**
1.  az extension add --name nexusidentity
2.  az nexusidentity gen-keys

**Expected behavior**
Cli should work with prompting any errors.

**Possible Cause**
Nexusidentity extension installs latest version of azure_identity which relies on AccessTokenInfo from azure.core.credentials. However azure-cli doesn't have the packages installed and expecting the package to be present.

**Observation**
Though the packages are installed in this path '~\.azure\cliextensions\nexusidentity`, expectation is the packages to be present in this below path 'C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages`
Manually copying the `azure` `azure_identity` `azure_core` to this `C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages` resolving the issue

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Please open the issue in https://github.com/Azure/azure-cli repo.
