### ISSUE TITLE
After latest update `azure-cli` rejects to install `azure-devops` extension due to the pip modules

### ISSUE THREAD

**Issue by erik-bershel** [Azure/azure-sdk-for-python#37979]
- **Package Name**: azure-batch, azure-mgmt-servicelinker
- **Package Version**: latest
- **Operating System**: macOS
- **Python Version**: 3.12

**Describe the bug**
Modules contain escaping characters and those break installation of azure-devops cli extension

**To Reproduce**
1. brew install azure-cli
2. az extension add -n azure-devops
3. Get:
```console
/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/batch/models/_models_py3.py:4839: SyntaxWarning: invalid escape sequence '\s'
  """A Job Preparation Task to run before any Tasks of the Job on any given
/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/mgmt/servicelinker/models/_models_py3.py:77: SyntaxWarning: invalid escape sequence '\ '
  """The access key directly from target resource properties, which target service is Azure
/opt/homebrew/Cellar/azure-cli/2.65.0/libexec/lib/python3.12/site-packages/azure/mgmt/servicelinker/models/_models_py3.py:114: SyntaxWarning: invalid escape sequence '\ '
  """
```

**Expected behavior**
`az extension add -n azure-devops` to be executed successfully, extension to be installed 

**Screenshots**
![Image](https://github.com/user-attachments/assets/b33ac5c1-492b-41bc-829a-5b0adbb41ad3)

**Additional context**
Issue_1: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/batch/azure-batch/azure/batch/models/_models.py#L1747
Issue_2: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicelinker/azure-mgmt-servicelinker/azure/mgmt/servicelinker/models/_models_py3.py#L92
Issue_3: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicelinker/azure-mgmt-servicelinker/azure/mgmt/servicelinker/models/_models_py3.py#L121

**Comment by erik-bershel** [comment]
`Homebrew` team rolled back to the previous behaviour: https://github.com/Homebrew/homebrew-core/pull/194884
That mitigated the issue, but seems as a temporary solution since migration to Python@3.12 will happen once.

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Please open cli issues in https://github.com/Azure/azure-cli repo.
