### ISSUE TITLE
The output option was not found: Failed to generate the analyze results in the output option format. Output option should be informed in analyze call.

### ISSUE THREAD

**Issue by sathish331977** [Azure/azure-sdk-for-python#38076]
- **Package Name**: azure-ai-documentintelligence
- **Package Version**: 1.0.0b4
- **Operating System**: linux
- **Python Version**: Python 3.11.0

**Describe the bug**
encountered the same problem
with open("cd_0001.pdf", "rb") as f:
poller = document_intelligence_client.begin_analyze_document(
"prebuilt-layout",
AnalyzeDocumentRequest(bytes_source=f.read()),
output_content_format ="markdown",
)
result: AnalyzeResult = poller.result()

running into following error
ResourceNotFoundError: (NotFound) Resource not found.
Code: NotFound
Message: Resource not found.
Inner error: {
"code": "OutputOptionNotFound",
"message": "The output option was not found: Failed to generate the analyze results in the output option format. Output option should be informed in analyze call."
}

**Comment by Kai-lash** [comment]
Have you tried adding the output option with the request?
Here is a Python example for reference: https://learn.microsoft.com/en-us/python/api/overview/azure/ai-documentintelligence-readme?view=azure-python-preview&preserve-view=true#extract-figures-from-documents
