### ISSUE TITLE
Adding tags and description to the assets created as output of pipeline jobs

### ISSUE THREAD

**Issue by trancenoid** [Azure/azure-sdk-for-python#38081]
Service : Azure ML
Package : azure-ai-ml 1.21.1

**Is your feature request related to a problem? Please describe.**
Currently there is no simple way to add tags and descriptions to assets created from jobs. It is an unpleasant code design to include additional code after calling a job in a pipeline and updating the created asset with tags and description. The problem is aggravated by the fact that the tags might originate from the properties of the asset itself (like model metrics, data statistics, date ranges etc) which has to be passed separately as output from the job itself. From a code maintenance pov as well, it is tedious to update both job file and the pipeline script to add / remove the tags. 

**Describe the solution you'd like**
Some easy way to specify tags and description of the assets created in jobs. Probably allow returning Data and Model entities directly which can be published by the pipeline runner. 

**Describe alternatives you've considered**
The alternative is described above along with why they are not desirable.

**Additional context**
A similar forum in MS Learn [thread](https://learn.microsoft.com/en-us/answers/questions/1805986/how-to-tag-job-outputs-data-assets-directly).

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you provide more information?

e.g. which Azure service do you use? Some repro steps if possible?

**Comment by trancenoid** [comment]
Apologies for not mentioning the service, I have updated the first comment. This is not an issue but a feature request and hence there are no specific steps to reproduce. But this can be experienced by trying to register the output of a ml pipeline job with tags and description.

**Comment by achauhan-scc** [comment]
Created an internal work item so it can participate in triage process. NO ETA yet.

**Comment by achauhan-scc** [comment]
[Task 3617454](https://msdata.visualstudio.com/Vienna/_workitems/edit/3617454): Adding tags and description to the assets created as output of pipeline jobs
