### ISSUE TITLE
[azure-mgmt-core] update `ARMChallengeAuthenticationPolicy` for CAE

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#38113]
Parent class [BearerTokenCredentialPolicy](https://github.com/Azure/azure-sdk-for-python/blob/d89ecd9934d9e94dc936fb67c3df7ac37f5887e0/sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py#L183-L198) of [ARMChallengeAuthenticationPolicy](https://github.com/Azure/azure-sdk-for-python/blob/d89ecd9934d9e94dc936fb67c3df7ac37f5887e0/sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_authentication.py#L57-L70) already supports CAE, so ARMChallengeAuthenticationPolicy just need to inherit from it completely.

**Comment by archerzz** [comment]
@msyyc Can you add a mock test? Thus, I don't need to file a separate issue. Thanks.

**Comment by msyyc** [comment]
We could refer test cases of other languages:
- https://github.com/Azure/azure-sdk-for-net/pull/47138

**Comment by msyyc** [comment]
> [@msyyc](https://github.com/msyyc) Can you add a mock test? Thus, I don't need to file a separate issue. Thanks.

Sure, will do it.
