### ISSUE TITLE
Azure Data Tables rejects Microsoft Entra authentication using Azure Cosmos DB for Table

### ISSUE THREAD

**Issue by seesharprun** [Azure/azure-sdk-for-python#38120]
- **Package Name**:  `azure-data-tables`
- **Package Version**: `12.5.0` (latest)
- **Operating System**: Windows
- **Python Version**: `3.12.2`

**Describe the bug**

You cannot use the `azure-data-tables` library today to authenticate to Azure Cosmos DB for Table using Microsoft Entra authentication. The

**To Reproduce**

1. Get the **endpoint** for an Azure Cosmos DB for Table account with RBAC enabled for the current identity. ([/azure/cosmos-db/table/security/how-to-grant-data-plane-role-based-access](https://learn.microsoft.com/azure/cosmos-db/table/security/how-to-grant-data-plane-role-based-access?tabs=built-in-definition%2Cpython)

1. Install the `azure-data-tables` and `azure-identity` packages.

1. Create this client logic:

    ```python
    from azure.data.tables import TableServiceClient, TableClient
    from azure.identity import DefaultAzureCredential
    
    endpoint = "<account-endpoint>"
    
    credential = DefaultAzureCredential()
    
    client = TableServiceClient(endpoint, credential=credential)
    
    table = client.get_table_client("<table-name>")
    ```

1. Run the application.

1. Observe the following error message:

    ```output
    azure.core.exceptions.ClientAuthenticationError: Operation returned an invalid status 'Unauthorized'
    Content: {"odata.error":{"code":"Unauthorized","message":{"lang":"en-us","value":"Request blocked by Auth Provided AAD token is intended for [https://storage.azure.com]. This database account accepts tokens intended for [https://<account-name>.documents.azure.com, https://<account-name>.sql.cosmos.azure.com, https://<account-name>.sqlx.cosmos.azure.com, https://cosmos.azure.com].
    ```

**Expected behavior**

**Comment by annatisch** [comment]
Thank you @seesharprun  - this is a good catch! Looks like we're mistakenly falling back to the Storage auth scope for a Cosmos endpoint.
And we really appreciate the PR as well!
Adding @YalinLi0312 to help review.
