### ISSUE TITLE
ServiceFabricClientAPI's is unable to use Azure-Identity Credentials

### ISSUE THREAD

**Issue by tayven-bigelow** [Azure/azure-sdk-for-python#38169]
- **Package Name**: azure.servicefabric / ServiceFabricClientAPIs
- **Package Version**: 8.2.0.0
- **Operating System**: MacOS 
- **Python Version**: 3.10

**Describe the bug**
ServiceFabricClientAPIs are unable to sign on using the DefaultCredential from Azure-Identity Credentials. 
The error is: 
`'DefaultAzureCredential' object has no attribute 'signed_session'` 
According to [this](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md) it appears to be using the old azure-common credentials. 

Azure-Identity is version 1.19.0

**To Reproduce**

Install Requirements:
`pip3 install azure-servicefabric azure-identity`

Code Snippet:
```
from azure.identity import DefaultAzureCredential
from azure.servicefabric import ServiceFabricClientAPIs

cluster_url = "https://CLUSTERURL:19000"
# Initialize the credentials
credential = DefaultAzureCredential()
#Initialize the client
sf_client = ServiceFabricClientAPIs(
            credentials=credential,
            base_url=cluster_url
        )
#Execute a command
apps = sf_client.get_application_info_list()
```

**Expected behavior**
An iterator of Applications is returned

**Screenshots**
N/A
**Additional context**

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Unfortunately, azure-servicefabric library is a track 1 library which does not work well with azure-identity library. 

You can take https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md for the reference. (The wrapper way you mentioned also works.)

**Comment by tayven-bigelow** [comment]
> Thanks for reaching out.
> 
> Unfortunately, azure-servicefabric library is a track 1 library which does not work well with azure-identity library.
> 
> You can take https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/migration_guide.md for the reference. (The wrapper way you mentioned also works.)

Apologies but I don't know what a Track 1 Library is. 

Is there an alternative library to use for service fabric management? Or I guess a better question is, will the library ever be updated to support the documented azure-identity authentication? Is there a better spot for this libraries documentation? That page links to [this](https://learn.microsoft.com/en-us/azure/developer/python/sdk/authentication/overview?tabs=cmd) which only references Azure-Identity as the sign-on method.
