### ISSUE TITLE
DefaultAzureCredential not working on an Azure Arc enabled Linux Server

### ISSUE THREAD

**Issue by lovettchris** [Azure/azure-sdk-for-python#38183]
- **Package Name**: 
  azure-common                     1.1.28
  azure-core                       1.31.0
  azure-cosmosdb-nspkg             2.0.2
  azure-cosmosdb-table             1.0.6
  azure-data-tables                12.5.0
  azure-identity                   1.19.0
  azure-keyvault-keys              4.10.0
  azure-keyvault-secrets           4.9.0
  azure-messaging-webpubsubservice 1.2.1
  azure-nspkg                      3.0.2
  azure-storage-blob               12.23.1
- **Package Version**: 
- **Operating System**: Linux Ubuntu Server 5.15.0-124-generic 
- **Python Version**: 3.10.15

**Describe the bug**
I have connected the machine to Azure using Azure Arc, the machine appears in Azure, then I granted that machine access to my storage account, but a BlobClient created with DefaultAzureCredential fails to connect to the storage account.

**To Reproduce**
1. blob_client = BlobClient(account_url, "firmware", "TeensyFirmware.TEENSY40.hex", credential=DefaultAzureCredential())
2. blob_client.exists()

**Expected behavior**
Should work

**Screenshots**

**Additional context**

```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        AzureCliCredential: ERROR: AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2024-10-29T00:11:12.8479019Z and the maximum allowed lifetime for this request is 43200. Trace ID: cf42c050-29f4-4d70-b9db-438b5dd53d00 Correlation ID: f4e21b33-dbbb-4ead-a398-6c3e94fa5aa0 Timestamp: 2024-10-30 02:52:54Z
Interactive authentication is needed. Please run:
az login --scope https://storage.azure.com/.default

        AzurePowerShellCredential: PowerShell is not installed
        AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**Comment by xiangyan99** [comment]
Thanks for reaching out.

We use environment viable to detect the Azure Arc env.

Could you check if env var IDENTITY_ENDPOINT & IMDS_ENDPOINT are set?

**Comment by lovettchris** [comment]
Ah, I see thanks, I seem to have something wrong with my setup because the [managed-identity-authentication](https://learn.microsoft.com/en-us/azure/azure-arc/servers/managed-identity-authentication) is giving me permission denied, but works when I run it as sudo, so looks like my azure arc setup is not complete... thanks for the pointer.
