### ISSUE TITLE
Algorithm name cannot be updated. Parameters: definition

### ISSUE THREAD

**Issue by balakreshnan** [Azure/azure-sdk-for-python#38203]
- **Package Name**: azure-search-documents==11.6.0b4
- **Package Version**: 
- **Operating System**: windows python virtual environment.
- **Python Version**: 3.12

**Describe the bug**
(.venv) C:\Code\RAI\aistudioeval>python embupgrade.py
Traceback (most recent call last):
  File "C:\Code\RAI\aistudioeval\embupgrade.py", line 395, in <module>
    main()
  File "C:\Code\RAI\aistudioeval\embupgrade.py", line 362, in main
    createnewindex(new_index_name)
  File "C:\Code\RAI\aistudioeval\embupgrade.py", line 317, in createnewindex
    result = index_client.create_or_update_index(index)
  File "C:\Users\babal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\azure\core\tracing\decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\babal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\azure\search\documents\indexes\_search_index_client.py", line 269, in create_or_update_index
    result = self._client.indexes.create_or_update(
  File "C:\Users\babal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\azure\core\tracing\decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\babal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 707, in create_or_update
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () The request is invalid. Details: definition : Algorithm name cannot be updated.
Code:
Message: The request is invalid. Details: definition : Algorithm name cannot be updated.
Exception Details:      () Algorithm name cannot be updated. Parameters: definition
        Code:
        Message: Algorithm name cannot be updated. Parameters: definition

**To Reproduce**
def createnewindex(new_index_name):
    # Create a search index
    index_client = SearchIndexClient(
        endpoint=endpoint, credential=credential)
    fields = [
        SimpleField(name="id", type=SearchFieldDataType.String, key=True, sortable=True, filterable=True, facetable=True),
        SearchableField(name="title", type=SearchFieldDataType.String, sortable=True, filterable=True, facetable=True),
        SearchableField(name="name", type=SearchFieldDataType.String, sortable=True, filterable=True, facetable=True),
        SearchableField(name="chunk", type=SearchFieldDataType.String,
                        filterable=True),
        SearchField(name="chunkVector", type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                    searchable=True, vector_search_dimensions=3072, vector_search_profile_name="myHnswProfile"),
        SearchableField(name="location", type=SearchFieldDataType.String),
        SearchableField(name="page_num", type=SearchFieldDataType.Int32),
    ]

    # https://github.com/Azure/azure-search-vector-samples/blob/main/demo-python/code/e2e-demos/azure-ai-search-e2e-build-demo.ipynb
    # Configure the vector search configuration  
    vector_search = VectorSearch(
        algorithms=[
            HnswAlgorithmConfiguration(
                name="myHnsw",
                parameters=HnswParameters(
                    m=4,
                    ef_construction=400,
                    ef_search=500,
                    metric=VectorSearchAlgorithmMetric.COSINE,
                ),
            )
        ],
        profiles=[
            VectorSearchProfile(
                name="myHnswProfile",
                algorithm_configuration_name="myHnsw",
                vectorizer="myVectorizer"
            )
        ],
        vectorizers=[
            AzureOpenAIVectorizer(
                name="myVectorizer",
                kind="azureOpenAI",
                azure_open_ai_parameters=AzureOpenAIParameters(
                    resource_uri=os.getenv("AZURE_OPENAI_ENDPOINT"),
                    deployment_id="text-embedding-3-large",
                    model_name="text-embedding-3-large",
                    api_key=os.getenv("AZURE_OPENAI_API_KEY")
                )
            )
        ]
    )

    semantic_config = SemanticConfiguration(
        name="my-semantic-config",
        prioritized_fields=SemanticPrioritizedFields(
            title_field=SemanticField(field_name="title"),
            keywords_fields=[SemanticField(field_name="name")],
            content_fields=[SemanticField(field_name="chunk")]
        )
    )

    # Create the semantic settings with the configuration
    semantic_search = SemanticSearch(configurations=[semantic_config])

    # Create the search index with the semantic settings
    index = SearchIndex(name=index_name, fields=fields,
                        vector_search=vector_search, semantic_search=semantic_search)
    result = index_client.create_or_update_index(index)
    print(f' {result.name} created')
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by balakreshnan** [comment]
Here is what i was following: https://github.com/Azure/azure-search-vector-samples/blob/main/demo-python/code/basic-vector-workflow/azure-search-vector-python-sample.ipynb

**Comment by xiangyan99** [comment]
Thanks for reaching out.

I see in 
VectorSearchProfile(
            name="myHnswProfile",
            algorithm_configuration_name="myHnsw",
            vectorizer="myVectorizer"
        )

it should be 

VectorSearchProfile(
            name="myHnswProfile",
            algorithm_configuration_name="myHnsw",
            vectorizer_name="myVectorizer"
        )

Could you try it again?

**Comment by balakreshnan** [comment]
ok testing

**Comment by balakreshnan** [comment]
Same error:  File "C:\Users\babal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\azure\core\tracing\decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\babal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 707, in create_or_update
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () The request is invalid. Details: definition : Algorithm name cannot be updated.
Code:
Message: The request is invalid. Details: definition : Algorithm name cannot be updated.
Exception Details:      () Algorithm name cannot be updated. Parameters: definition
        Code:
        Message: Algorithm name cannot be updated. Parameters: definition

**Comment by balakreshnan** [comment]
vector_search = VectorSearch(
        algorithms=[
            HnswAlgorithmConfiguration(
                name="myHnsw",
                parameters=HnswParameters(
                    m=4,
                    ef_construction=400,
                    ef_search=500,
                    metric=VectorSearchAlgorithmMetric.COSINE,
                ),
            )
        ],
        profiles=[
            VectorSearchProfile(
                name="myHnswProfile",
                algorithm_configuration_name="myHnsw",
                vectorizer_name="myVectorizer"
            )
        ],
        vectorizers=[
            AzureOpenAIVectorizer(
                name="myVectorizer",
                kind="azureOpenAI",
                azure_open_ai_parameters=AzureOpenAIParameters(
                    resource_uri=os.getenv("AZURE_OPENAI_ENDPOINT"),
                    deployment_id="text-embedding-3-large",
                    model_name="text-embedding-3-large",
                    api_key=os.getenv("AZURE_OPENAI_API_KEY")
                )
            )
        ]
    )

    semantic_config = SemanticConfiguration(
        name="my-semantic-config",
        prioritized_fields=SemanticPrioritizedFields(
            title_field=SemanticField(field_name="title"),
            keywords_fields=[SemanticField(field_name="name")],
            content_fields=[SemanticField(field_name="chunk")]
        )
    )

    # Create the semantic settings with the configuration
    semantic_search = SemanticSearch(configurations=[semantic_config])

**Comment by xiangyan99** [comment]
Seems like there are some issues in your code.

```py
vector_search = VectorSearch(
    algorithms=[
        HnswAlgorithmConfiguration(
            name="myHnsw",
            parameters=[HnswParameters(
                m=4,
                ef_construction=400,
                ef_search=500,
                metric=VectorSearchAlgorithmMetric.COSINE,
            )],
        )
    ],
    profiles=[
        VectorSearchProfile(name="myHnswProfile", algorithm_configuration_name="myHnsw", vectorizer_name="myVectorizer")
    ],
    vectorizers=[
        AzureOpenAIVectorizer(
            name="myVectorizer",
            parameters=[AzureOpenAIVectorizerParameters(
                resource_uri=os.getenv("AZURE_OPENAI_ENDPOINT"),
                deployment_id="text-embedding-3-large",
                model_name="text-embedding-3-large",
                api_key=os.getenv("AZURE_OPENAI_API_KEY"),
            )],
        )
    ],
)

semantic_config = SemanticConfiguration(
    name="my-semantic-config",
    prioritized_fields=SemanticPrioritizedFields(
        title_field=SemanticField(field_name="title"),
        keywords_fields=[SemanticField(field_name="name")],
        content_fields=[SemanticField(field_name="chunk")],
    ),
)
```
