### ISSUE TITLE
No module for Azure Maps calls, just management

### ISSUE THREAD

**Issue by eavanvalkenburg** [Azure/azure-sdk-for-python#3824]
Why isn't there a package to do calls to Azure Maps from Python?

**Comment by lmazuel** [comment]
Hi @eavanvalkenburg 
Somehow I missed your message, it's available now:
https://pypi.org/project/azure-mgmt-maps/
Thanks,

**Comment by eavanvalkenburg** [comment]
Hi @lmazuel that is not what I was looking for, I meant being able to actually talk to the API's of Azure Maps, basically a call to this endpoint, but then wrapped in a nice way: https://docs.microsoft.com/en-us/rest/api/maps/route/getroutedirections, so a MapsClient, to complement a MapsManagementClient!

**Comment by lmazuel** [comment]
Gotcha, sorry for the misunderstanding, re-opening the issue.

**Comment by eavanvalkenburg** [comment]
Any updates on this?

**Comment by lmazuel** [comment]
@kaerm is this team in your backlog of data-plane? There is no swagger but it seems a RestAPI exists.

**Comment by kaerm** [comment]
@jongio is maps in the inventory?

**Comment by kaerm** [comment]
Confirmed, this is accounted for in our data-plane SDK backlog, but no ETA as for now

**Comment by tjprescott** [comment]
The Maps team is currently working on these SDKs.

**Comment by dubiety** [comment]
Hi @eavanvalkenburg,

We have published the following packages for Azure Maps. Sorry for waiting so long. Happy coding! :)

| PyPi Links  | README | Samples |
|-------------|-----------|----------|
|[azure-maps-search](https://pypi.org/project/azure-maps-search/)| [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-search/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/maps/azure-maps-search/samples)
|[azure-maps-route](https://pypi.org/project/azure-maps-route/) | [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-route/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/maps/azure-maps-route/samples)
|[azure-maps-render](https://pypi.org/project/azure-maps-render/) | [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-render/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/maps/azure-maps-render/samples)
|[azure-maps-geolocation](https://pypi.org/project/azure-maps-geolocation/) | [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-geolocation/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/maps/azure-maps-geolocation/samples)

You can also refer to all Azure Maps REST SDK on [Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-maps/rest-sdk-developer-guide)

**Comment by eavanvalkenburg** [comment]
Thanks for circling back, I will have a look!
