### ISSUE TITLE
keep-alive issue

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-python#383]
Does azure-sdk-for-python support keep-alive option if I would like to perform a lot of requests? If so, how to support it? Thanks.

**Comment by huguesv** [comment]
Right now, you can pass a requests.Session() to the service management classes initializer.  This will enable keep-alive.

For runtime (storage and servicebus), it's not currently exposed as a parameter to the service classes.

You can either change the code for BlobService,QueueService, etc to do the same.  You could also access the internal field from your code like this:
```
tableservice_object._httpclient.request_session = requests.Session()
```
Our plan is to use `requests` exclusively in the future.

**Comment by bingosummer** [comment]
It works for me and reduces 25% time. Thank you for your help.

**Comment by huguesv** [comment]
Great!  v0.11.1 that was just released to PyPI has the request_session parameter on all service classes now.  Note that there's a few issues with table ACL functions when using requests library. It's filed here:
https://github.com/Azure/azure-sdk-for-python/issues/384
