### ISSUE TITLE
Add instructions that PRs should be made to Azure/azure-rest-api-specs

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-sdk-for-python#3831]
Since the changes to the specs need to go to the upstream repo, there should be an indication in this repo about this. Possible locatons for the note:
- README.md
- PULL_REQUEST_TEMPLATE.md
- Contributing.md

**Comment by lmazuel** [comment]
Thanks for opening this issue :). That's definitely true (and not just true for Python by the way).

**Comment by lmazuel** [comment]
Adding a note in the contributing file:
https://github.com/Azure/azure-sdk-for-python/commit/863ceaf877fa0193e2e1aaca2d79bc11e689cf2e
