### ISSUE TITLE
Does azure-mgmt-sql uses updated sql api versions?

### ISSUE THREAD

**Issue by rasagnareddy2003** [Azure/azure-sdk-for-python#38355]
Recently, we got an email to upgrade azure sql api versions from 2014-04-01 to 2021-xx-xx versions.
regarding to this as we are not using any api calls directly in our code base, we have updated sql version from 0.14.0 to 3.0.1. But when checked internal scripts of azure/mgmt/sql it's still have references of 2014 api version of sql api's.

**Comment by rasagnareddy2003** [comment]
Any update?

**Comment by msyyc** [comment]
Please have a try for latest version https://pypi.org/project/azure-mgmt-sql/4.0.0b20/
