### ISSUE TITLE
The latest version of "azure-mgmt-eventgrid" doesnt return "properties.minimumTlsVersionAllowed" in api response

### ISSUE THREAD

**Issue by vit-corp** [Azure/azure-sdk-for-python#38373]
- **azure-mgmt-eventgrid**: 
- **Latest**: 
- **any**:
- **any**: 

**Describe the bug**
The latest version of "azure-mgmt-eventgrid" doesnt return "properties.minimumTlsVersionAllowed" in api response.

**To Reproduce**

**Expected behavior**
"azure-mgmt-eventgrid" will return "properties.minimumTlsVersionAllowed" 

**Additional context**
https://learn.microsoft.com/en-us/rest/api/eventgrid/controlplane/domains/list-by-subscription?view=rest-eventgrid-controlplane-2024-06-01-preview&tabs=HTTP#tlsversion
![Image](https://github.com/user-attachments/assets/52c0af88-361e-4037-b605-f39eeebc88df)

**Comment by kashifkhan** [comment]
Thank you for the feedback @vit-corp . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
@ChenxiJiang333 Please help on this issue.

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
Hi @vit-corp, you can update the SDK to `azure-mgmt-eventgrid==10.3.0b4` to get the feature.
