### ISSUE TITLE
azure-monitor-opentelemetry distro should configure event provider

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#38412]
OTel events are not captured by default. A workaround:

```python
from opentelemetry._events import set_event_logger_provider
from opentelemetry.sdk._events import EventLoggerProvider

configure_azure_monitor()
event_provider = EventLoggerProvider()
set_event_logger_provider(event_provider)
```

**Comment by lmolkova** [comment]
@lzchen @jeremydvoss wdyt given that event API is merged into logs and won't last long.

**Comment by lzchen** [comment]
@lmolkova 

We would probably want to include this as part of the distro. It might not be a good idea to recommend users to manually use experimental apis (especially ones that will disappear soon).
