### ISSUE TITLE
Azure Search - SearchField in GA SDK should support vectorEncodingFormat

### ISSUE THREAD

**Issue by mattgotteiner** [Azure/azure-sdk-for-python#38439]
- **Package Name**: azure.search.documents
- **Package Version**: 11.5.2
- **Operating System**: Windows
- **Python Version**: 3.10.11

**Describe the bug**
[SearchField](https://github.com/Azure/azure-sdk-for-python/blob/f87fb01ad231ebe03e92d241205ae27ba41e8b4d/sdk/search/azure-search-documents/azure/search/documents/indexes/models/_index.py#L212) should support the `vector_encoding_format` parameter in the GA SDK as well as the preview one

**To Reproduce**
1. Attempt to specify `vector_encoding_format` when creating a field in the GA SDK. It is ignored.

**Expected behavior**
1. This parameter is accepted.
GA Swagger parameter
https://github.com/Azure/azure-rest-api-specs/blob/766fbdcae199a5b2a3b7d2910f32b37cac7947de/specification/search/data-plane/Azure.Search/stable/2024-07-01/searchservice.json#L7163

**Comment by xiangyan99** [comment]
Seems like we already have vector_encoding_format support. https://github.com/Azure/azure-sdk-for-python/blob/search_11.5.0/sdk/search/azure-search-documents/azure/search/documents/indexes/models/_index.py#L205

Could you share a repro?
