### ISSUE TITLE
Specifying network_api_version with azure-mgmt-network==28.0.0

### ISSUE THREAD

**Issue by r4victor** [Azure/azure-sdk-for-python#38507]
The 28.0.0 release introduced a breaking change:

> This package now only targets the latest Api-Version available on Azure and removes APIs of other Api-Version. After this change, the package can have much smaller size. If your application requires a specific and non-latest Api-Version, it's recommended to pin this package to the previous released version; If your application always only use latest Api-Version, please ingore this change.

This breaks code that specified `network_api_version` like so:

```python
network_profile=NetworkProfile(
    network_api_version=network_mgmt.NetworkManagementClient.DEFAULT_API_VERSION,
)
```

Now gives an error `type object 'NetworkManagementClient' has no attribute 'DEFAULT_API_VERSION'`.

My question is how do we create models like `NetworkProfile()` starting with azure-mgmt-network==28.0.0. Apparently, it requires specifying `network_api_version` since if I omit it or specify `None`, I get an error response:

```
 azure.core.exceptions.HttpResponseError:                   
                    (NetworkApiVersionMustBeSpecifiedWithNetworkInterfaceConfig
                    urations) Network api version in network profile of virtual
                    machine
```

More details: https://github.com/dstackai/dstack/issues/1987

**Comment by msyyc** [comment]
@r4victor I don't see a property named "network_api_version" in all [models](https://github.com/Azure/azure-sdk-for-python/blob/29d71c1e3be5ed836041f04d8f1fdbf1efc7b92e/sdk/network/azure-mgmt-network/azure/mgmt/network/models/_models_py3.py) of network. Could you please share more context?

**Comment by r4victor** [comment]
@msyyc, I was referring to a NetworkProfile model:

https://github.com/Azure/azure-sdk-for-python/blob/29d71c1e3be5ed836041f04d8f1fdbf1efc7b92e/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2024_07_01/models/_models_py3.py#L4774-L4775

Although it's a model from compute, it expects a network API version.

**Comment by msyyc** [comment]
After converting to single-api packages, client of azure-mgmt-network doesn't have property `DEFAULT_API_VERSION` anymore. And you can find the api-version configured for latest version here: 
![Image](https://github.com/user-attachments/assets/b8b3ba9a-d52d-47cc-864a-734fccc914d7)

So for 28.0.0, it is "2024-03-01"

**Comment by r4victor** [comment]
@msyyc, thanks!
