### ISSUE TITLE
Python service bus client with custom_endpoint_address always uses AmqpOverWebsocket

### ISSUE THREAD

**Issue by jvanegmond** [Azure/azure-sdk-for-python#38515]
- **Package Name**: azure-servicebus
- **Package Version**: 7.13.0
- **Operating System**: WSL
- **Python Version**: 3.12.0

**Describe the bug**
When using `ServiceBusClient` and specifying both a `custom_endpoint_address` and `transport_type = TransportType.Amqp`, the actual connection is made with `TransportType.AmqpOverWebsocket` instead.

**To Reproduce**
```
with ServiceBusClient.from_connection_string(
    conn_str="Endpoint=sb://localenvironment.local;SharedAccessKeyName=1234;SharedAccessKey=password",
    custom_endpoint_address="https://localhost:5672",
    transport_type=TransportType.Amqp,
) as client:
    print(client._config.transport_type) # Prints TransportType.AmqpOverWebsocket
```

On the server side, the following packet is received:
```GET /$servicebus/websocket HTTP/1.1
Upgrade: websocket
Host: localhost:5672
Origin: https://localhost:5672
Sec-WebSocket-Key: .....
Sec-WebSocket-Version: 13
Connection: Upgrade
Sec-WebSocket-Protocol: AMQPWSB10
```

**Expected behavior**
The service bus client connects using Amqp as specified by the `transport_type` parameter.

**Additional context**
When using a local Amqp 1.0 emulator, I want to use a `custom_endpoint_address` along with `transport_type = TransportType.Amqp`.

The relevant code behavior is in configuration.py:#L62 but it is unknown why this is being done and is not further documented.

**Comment by kashifkhan** [comment]
Thank you for the feedback @jvanegmond . We will investigate and get back to you asap.

**Comment by l0lawrence** [comment]
Hi @jvanegmond we merged a pr to add custom endpoint support over AMQP, when TransportType.Amqp is specified. We don't release packages during the month of December, but if you want to test out these changes you can build a wheel off of the main branch. We will update this thread when the fix is released.

**Comment by jvanegmond** [comment]
I have tested the changes and can verify it works as expected. Thanks for the quick turnaround.
