### ISSUE TITLE
Unable to add a data asset reference to the model in ML Studio with Python SDK

### ISSUE THREAD

**Issue by TCodingB** [Azure/azure-sdk-for-python#38513]
- **Package Name**: azureml.core
- **Package Version**: 1.58.0
- **Operating System**: Linux
- **Python Version**:  3.10.12

**Describe the bug**
When making a data asset reference to the model in ML Studio with the help of python SDK I'm unable to add a data asset of type MLTable (composed of a parquet file and it's complementary mltable definition), but there doesn't seem to be an issue adding a MLTable deriving from .csv file.

**To Reproduce**
1. Register a model to the ML Studio
2. Registering the .csv and parquet datasets as MLtable to the data assets in the ML Studio
3. Getting the data assets per name:
    - Dataset.get_by_name(ws, name=data_asset_name)
    - Saving the data assets as reference_dataset_csv and reference_dataset_parquet
4. Adding the data asset reference to the registered model
    - model.add_dataset_references([("dataset csv", reference_dataset_csv), ("dataset parquet", reference_dataset_parquet)])
5. After running there is no errors that would signalise that there is anything wrong.

**Expected behavior**
Both data assets to be referenced to the model in the ML Studio.

**Screenshots**
.csv data asset:
![Image](https://github.com/user-attachments/assets/adb00e25-1f64-4138-bba6-f421cfdfa8f1)

.parquet data asset:
![Image](https://github.com/user-attachments/assets/27894d1a-aed8-472e-9095-3cb218f829a6)

Model data references:
![Image](https://github.com/user-attachments/assets/6edfef38-088b-4221-bdeb-e5a23df38d9a)

**Comment by TCodingB** [comment]
Hi, we managed to find a better solution going with registering pandas dataframe as data asset to the ML Studio. Still I find it odd that you can't reference the data asset that is otherwise completely functional (can be downloded and processed etc.) but can't be referenced to the model. Another thing that was odd was, that after running the code, we didn't get any feedback (good or bad) that the dataset was or wasn't referenced to the model.

Thank you for taking the time,

Kind regards,

Tadej

**Comment by TCodingB** [comment]
Hi, I don't have the file here. I can say it was a parquet file created
with pandas version 1.5.1. If you need the exact file I can maybe provide
it laters.

Kind regards,

Tadej Boncelj


V V čet., 21. nov. 2024 ob 13:38 je oseba Jagadeesh Boyidi <
***@***.***> napisala:

**Comment by jaga-work** [comment]
we would like to test with file that have given the issue. Kindly share as early as possible.

**Comment by TCodingB** [comment]
[input_data_test.zip](https://github.com/user-attachments/files/17903417/input_data_test.zip)

**Comment by jaga-work** [comment]
Hi @TCodingB, we tried to replicate the issue, we are able to add dataset references model.add_dataset_references([("dataset csv", reference_dataset_csv), ("dataset parquet", reference_dataset_parquet)]) and validated by checking model details. Could you please share the snippets that you are using to validate.
