### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\W'

### ISSUE THREAD

**Issue by Goldziher** [Azure/azure-sdk-for-python#38562]
- **Package Name**: azure-search-documents
- **Package Version**: 11.5.2
- **Operating System**: MacOS
- **Python Version**: 3.12.7

**Describe the bug**
The following is thrown when loading the library with Python 3.12:

```text
azure/search/documents/indexes/_generated/models/_models_py3.py:5644: SyntaxWarning: invalid escape sequence '\W'
pattern: str = "\W+",
azure/search/documents/indexes/_generated/models/_models_py3.py:5869: SyntaxWarning: invalid escape sequence '\W'
pattern: str = "\W+",
```

**To Reproduce**
Load ai search in python 3.12. This issue is also reported by mypy.

**Comment by xiangyan99** [comment]
Thanks for the feedback.

This model is private.

The public one has 'r' added.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/azure/search/documents/indexes/models/_models.py#L685

**Comment by Goldziher** [comment]
Good to know this isnt a dangerous bug. Its still pretty annoying though - I am also getting warning when just running CLI commands, example:

```shell
➜  temp git:(main) az login
/opt/homebrew/Cellar/azure-cli/2.66.0/libexec/lib/python3.12/site-packages/azure/batch/models/_models_py3.py:4839: SyntaxWarning: invalid escape sequence '\s'
  """A Job Preparation Task to run before any Tasks of the Job on any given
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
```

**Comment by ashb** [comment]
This model being private doesn't mean the file isn't imported.

Running this on Python 3.12+ leads to loads of warnings like this. (Synapse is the worse offender with 311 warnings!)

**Comment by pamelafox** [comment]
I'm getting this as well, but I'm assuming I'm behind a version, as the offending line does have a r in the main branch:

https://github.com/Azure/azure-sdk-for-python/blob/27e54c997ff2164f41b09db8f8d00e394321c69b/sdk/search/azure-search-documents/azure/search/documents/indexes/_generated/models/_models_py3.py#L6857

**Comment by jejamnicki-fadv** [comment]
switched from python 3.11 to **3.12** after https://github.com/Azure/azure-sdk-for-python/issues/38725

and now this...

/home/site/wwwroot/azure/search/documents/indexes/_generated/models/_models_py3.py:5869: SyntaxWarning: invalid escape sequence '\W'

under operation_Name: ""
