### ISSUE TITLE
Surpress Azure Monitor Log writting to StdErr

### ISSUE THREAD

**Issue by johnkattenhorn** [Azure/azure-sdk-for-python#38624]
**Is your feature request related to a problem? Please describe.**
Azure Monitor Open Telemetry to Console write log entries destined for Azure Monitor to the Console using StdErr which makes the output noisy.

**Describe the solution you'd like**
Like to be able to suppress the output of Azure Monitor so that it doesn't write to StdErr

**Describe alternatives you've considered**
Tried to find a way to redirect the output to dummy file using alternative stream but this seemed to have undesired side-effects.

**Additional context**
Any logs that we want outputted to the console are being managed through another logger using structlog

![Image](https://github.com/user-attachments/assets/d0cc1381-04c7-4460-9843-c305b3f90178)

**Comment by lzchen** [comment]
Could you paste your `pip freeze` as well as a code snippet of how you are instrumenting with Azure monitor OpenTelemetry SDK. Also, which logs specifically are noisy? The INFO logs?

**Comment by johnkattenhorn** [comment]
Hi,

Thanks for coming back to me, in the end I took a different approach and wrote a processor for `structlog` which allow me to post to Azure Monitor via the REST API so I could keep the structured logging and console output and also achieve a push to Azure Monitor. 

Just some other feedback, since migration away from OpenCensus to OpenTelemetry I found it quite difficult to just push logs, no spans or anything just yet.

I know the Azure Log Handler is there and it might be just my use case but integrating with structlog which is quite popular was tricker than I hoped. 

If you would like to see the code for this please let me know else I'll close this issue and thank you again for your time.

John
