### ISSUE TITLE
Expose `ownership` and `permissions` permission in `ContainerSasPermissions`

### ISSUE THREAD

**Issue by janjagusch** [Azure/azure-sdk-for-python#38637]
**Is your feature request related to a problem? Please describe.**

The `ContainerSasPermissions` class doesn't expose a way to set the `ownership` or `permissions` permission:
https://github.com/Azure/azure-sdk-for-python/blob/a71376d5d0942c08f431178c40ec230d851f54a0/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py#L929-L950

As a workaround, I have to provide the string repesentation directly to the `generate_sas_container` function:

```python
generate_container_sas(permission="op")
```

**Describe the solution you'd like**

I want to use the `ContainerSasPermissions` class:
```python
generate_container_sas(permission=ContainerSasPermissions(ownership=True, permissions=True))
```

**Comment by kristapratico** [comment]
@janjagusch thanks for the request, we'll take a look and get back to you as soon as possible!

**Comment by jalauzon-msft** [comment]
Hi @janjagusch, `ownership` and `permission` are specific to HNS (Datalake) accounts and therefore are not supported in the Blob SDK. Instead, you would want to use our Datalake SDK (`azure-storage-file-datalake`) and [generate_file_system_sas](https://github.com/Azure/azure-sdk-for-python/blob/6d7ee6bdc5d386f2b5dc3d55fd37ba228be1860c/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py#L101) where you can specify a [FileSystemSasPermissions](https://github.com/Azure/azure-sdk-for-python/blob/6d7ee6bdc5d386f2b5dc3d55fd37ba228be1860c/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py#L368) which has `manage_ownership` and `manage_access_control` keywords that correspond to the `o` and `p` SAS parameters.

**Comment by janjagusch** [comment]
> Hi [@janjagusch](https://github.com/janjagusch), `ownership` and `permission` are specific to HNS (Datalake) accounts and therefore are not supported in the Blob SDK. Instead, you would want to use our Datalake SDK (`azure-storage-file-datalake`) and [generate_file_system_sas](https://github.com/Azure/azure-sdk-for-python/blob/6d7ee6bdc5d386f2b5dc3d55fd37ba228be1860c/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py#L101) where you can specify a [FileSystemSasPermissions](https://github.com/Azure/azure-sdk-for-python/blob/6d7ee6bdc5d386f2b5dc3d55fd37ba228be1860c/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py#L368) which has `manage_ownership` and `manage_access_control` keywords that correspond to the `o` and `p` SAS parameters.

Thanks, @jalauzon-msft.
