### ISSUE TITLE
connectedvmware: ConnectedVMwareMgmtClient.virtual_machine_instances.begin_create_or_update fails to create a new VM

### ISSUE THREAD

**Issue by giskarda** [Azure/azure-sdk-for-python#38651]
- **Package Name**: 
connectedvmware
- **Package Version**: 
1.0.0
- **Operating System**:
MacOS
- **Python Version**: 
python 3.13.0
**Describe the bug**

begin_create_or_update() wont create a new Virtual Machine as the HybridCompute URI doesn't exists.

**To Reproduce**
1. Run the following code

from azure.identity import AzureCliCredential
from azure.mgmt.connectedvmware import ConnectedVMwareMgmtClient

SUBSCRIPTION_ID=""
RESOURCE_GROUP=""
client = ConnectedVMwareMgmtClient(credential=AzureCliCredential(),subscription_id=SUBSCRIPTION_ID,)
response = client.virtual_machine_instances.begin_create_or_update( resource_uri=f"subscriptions/{SUBSCRIPTION_ID}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.HybridCompute/machines/DemoVM",).result()
print(response)

OUTPUT:

>>> response = client.virtual_machine_instances.begin_create_or_update( resource_uri="subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.HybridCompute/machines/DemoVM",).result()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    response = client.virtual_machine_instances.begin_create_or_update( resource_uri="subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.HybridCompute/machines/DemoVM",).result()
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rsetti/venv3/lib/python3.13/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/rsetti/venv3/lib/python3.13/site-packages/azure/mgmt/connectedvmware/operations/_virtual_machine_instances_operations.py", line 466, in begin
_create_or_update
    raw_result = self._create_or_update_initial(
        resource_uri=resource_uri,
    ...<6 lines>...
        **kwargs
    )
  File "/Users/rsetti/venv3/lib/python3.13/site-packages/azure/mgmt/connectedvmware/operations/_virtual_machine_instances_operations.py", line 336, in _crea
te_or_update_initial
    map_error(status_code=response.status_code, response=response, error_map=error_map)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rsetti/venv3/lib/python3.13/site-packages/azure/core/exceptions.py", line 163, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (ResourceNotFound) The Resource 'Microsoft.HybridCompute/machines/DemoVM' under resource group 'redacted
' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.HybridCompute/machines/DemoVM' under resource group 'redacted' was not found. For more details please go to https://
aka.ms/ARMResourceNotFoundFix

**Expected behavior**

An (empty) virtual machine would be created.

**Additional context**

The example above follows the one provided by the SDK:

https://github.com/Azure/azure-sdk-for-python/blob/3f68bf3572c03b398310ef8125cd91badc2693ed/sdk/connectedvmware/azure-mgmt-connectedvmware/generated_samples/create_virtual_machine_instance.py

The `az` CLI:

az connectedvmware vm create --name $MachineName --resource-group $ResourceGroup --vcenter $vCenter --datastore $Datastore --cluster $Cluster --vm-template $VMTemplate --admin-password $AdminPassword

(latest version of az) works fine. I tried to figure out if it was patched as the sdk is vendored in the extension, or at least I believe it is but Im not smart enough to see if something is different there.

(venv3) [~] ➔  pip list
Package                    Version
-------------------------- ---------
azure-common               1.1.28
azure-core                 1.32.0
azure-identity             1.19.0
azure-mgmt-connectedvmware 1.0.0
azure-mgmt-core            1.5.0
blessed                    1.20.0
bpython                    0.24
certifi                    2024.8.30
cffi                       1.17.1
charset-normalizer         3.4.0
cryptography               43.0.3
curtsies                   0.4.2
cwcwidth                   0.1.9
greenlet                   3.1.1
idna                       3.10
isodate                    0.7.2
msal                       1.31.1
msal-extensions            1.2.0
pip                        24.2
portalocker                2.10.1
pycparser                  2.22
Pygments                   2.18.0
PyJWT                      2.10.0
pyxdg                      0.28
requests                   2.32.3
six                        1.16.0
typing_extensions          4.12.2
urllib3                    2.2.3
wcwidth                    0.2.13
(venv3) [~] ➔  python --version
Python 3.13.0
(venv3) [~] ➔

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
@ChenxiJiang333 Please help on this issue.

**Comment by ChenxiJiang333** [comment]
got it

**Comment by ChenxiJiang333** [comment]
Hi @giskarda, so your question is why using sdk cannot create empty vms with an invaild HybridCompute resource uri, but by using azure cli, it worked?

One thing for sure is that Azure cli do patch the SDK codes so there could be some differences between their behaviors. You can find the patches in here: https://github.com/Azure/azure-cli-extensions/blob/main/src/connectedvmware/azext_connectedvmware/custom.py#L955.

**Comment by giskarda** [comment]
Hi @ChenxiJiang333 ,

thank you for showing us how the maintainers of the extension circumnavigated the "possible" bug in the sdk.

I mentioned the azure cli because it's clear that somehow it's possible to use the Arc API to setup a VM on VMWare. 

Since, instead, is not clear to me how to create a VM through the official python SDK, and the current SDK example raises an error I wonder where the bug is (I'm totally open to accept the problem is that I didn't understand how to use the SDK properly let's be clear)

Currently we are already shelling out to `az` because as you can imagine is not realistic to re-use the custom code but this solution is less than ideal.

**Comment by giskarda** [comment]
@ChenxiJiang333,

the goal here is to use a python API to create a virtual machine on a local VMWare instance through ARC.

the assumption is that via `ConnectedVMwareMgmtClient` I can `begin_create_or_update` a new VM. Am I wrong? (again I can be completely wrong, I would you to confirm this to me)

> Hi [@giskarda](https://github.com/giskarda), I wonder whether you have created a resource before you run this sample. In the sample you mentioned, the resource URI must point to a valid resource, so you can't directly use the value in the sample but need to create your own resource (you can follow https://learn.microsoft.com/en-us/azure/azure-arc/servers/learn/quick-enable-hybrid-vm#generate-installation-script) and paste its resource URI into your code.

Yeah, if I do so it defeats the purpose of writing code if I have to go through the website to obtain a valid URI.

> Or if you just want to create a sample vm with a preset image instead of using Azure Arc machines, I guess to follow https://learn.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-virtual-machines?tabs=cmd#3-write-code-to-create-a-virtual-machine might be better.

Same here, but this time you want me to use ComputeManagementClient that AFAIK is different from ConnectedVMwareMgmtClient, I want a VM to be deployed on our VMWare cluster.

My assumption is that I would be able to instantiate a VM on a VMWare cluster through the ARC API, because the `az` cli can do it. 

I went through the custom(.py) code you sent me and I believe the custom part that I need is this

https://github.com/Azure/azure-cli-extensions/blob/main/src/connectedvmware/azext_connectedvmware/custom.py#L1159

`except ResourceNotFoundError:
        m = Machine(
            location=location,
            kind=vcenter.kind,
            tags=tags,
        )
        machine = machine_client.create_or_update(resource_group_name, resource_name, m)`

where `machine_client` is an object of `HybridComputeManagementClient`


If this is what you suggest me to do, I believe this is also what the SDK should do in case of ResourceNotFoundError, either via the begin_create_or_update() with a custom argument or to have the example remind people to execute the code above.

what do you think?

**Comment by giskarda** [comment]
I wend down the rabbit hole of checking the "vendored_sdk" and it's no way close to what is provided here so I guess either we wait until that code lands GA in the meantime we will shell out. Very unfortunate but it is what it is

**Comment by ChenxiJiang333** [comment]
> If this is what you suggest me to do, I believe this is also what the SDK should do in case of ResourceNotFoundError, either via the begin_create_or_update() with a custom argument or to have the example remind people to execute the code above.

I think here it's the exception handling of method [HybridComputeManagementClient.machines.get()](https://github.com/Azure/azure-cli-extensions/blob/main/src/connectedvmware/azext_connectedvmware/custom.py#L1132), not `ConnectedVMwareMgmtClient.virtual_machine_instances.begin_create_or_update()` that to create a new resource if the specified Azure Arc machine is not found. Those code are still just a to make sure to send a valid resource URI when [creating the vm](https://github.com/Azure/azure-cli-extensions/blob/main/src/connectedvmware/azext_connectedvmware/custom.py#L1361).

And for your advice, please know that python mgmt SDK is just a tool that is auto generated by API documentations and all its methods are just to send http requests & receive responses through single API. `ResourceNotFoundError` is a clear message returned by the service to indicate that the specified resource does not exist in Azure portal and we would not bypass it in the source code by exception handlings and multiple APIs callings. Not to say these APIs are from different providers and are in the charge of different service teams that are very unlikely to be integrated into one package. It should be the users to import different packages and build such logic by their own.

One more thing is that I found azure cli is using azure-mgmt-hybridcompute in a very old [version](https://github.com/Azure/azure-cli-extensions/blob/main/src/connectedvmware/azext_connectedvmware/vendored_sdks/hybridcompute/_version.py). For now, all public versions of this SDK do not have the method `machines.create_or_update` anymore (according to this [config](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/hybridcompute/resource-manager/readme.python.md?plain=1#L25)). So, if you want to create a VM through ARC API using SDK, I believe this [step](https://learn.microsoft.com/en-us/azure/azure-arc/servers/learn/quick-enable-hybrid-vm#generate-installation-script) is still necessary.

**Comment by giskarda** [comment]
I'm not sure I understand.

Let me clarify what you said. Please correct me if I'm wrong.

The api `ConnectedVMwareMgmtClient.machine_instances.begin_create_or_update` doesn't create anything, despite *create* in the name, if the URI of the VM doesn't exists in advance. There is no way right now through the API to create the resource, either via the connectedvmware or hybridcomputemgmtclient, (even tho is clear that azure-cli team understood the exercise and customized a solution around the deficiencies of other teams API design) if not by issuing an HTTP request manually or to go through the website UI (defeating the purpose of having an SDK)
This is by design and there is no intention of having it to work, right now at the least, in the SDK because Microsoft teams don't cooperate between each other.

Hopefully I understood it wrong.

Do not take this personally. I understand you are just the messenger.

To be fair at this point it's clear to me what I need to do. Thanks also to you to point me towards the right direction.

I'm perfectly happy to have the github team close this issue and mark it as wontfix / out of scope / xyz.

**Comment by ChenxiJiang333** [comment]
> The api `ConnectedVMwareMgmtClient.machine_instances.begin_create_or_update` doesn't create anything, despite _create_ in the name, if the URI of the VM doesn't exists in advance. There is no way right now through the API to create the resource, either via the connectedvmware or hybridcomputemgmtclient, (even tho is clear that azure-cli team understood the exercise and customized a solution around the deficiencies of other teams API design) if not by issuing an HTTP request manually or to go through the website UI (defeating the purpose of having an SDK) This is by design and there is no intention of having it to work, right now at the least, in the SDK because Microsoft teams don't cooperate between each other.

Sorry if I didn't clarify it clearly. Please let me correct something. There are two kinds of resources we mentioned here: a connected machine and the VM instance based on it. 
![Image](https://github.com/user-attachments/assets/ec3e6e20-25e5-4e59-abab-a91d8a7086fe)

It's the resource uri of a connected machine need to be passed to `ConnectedVMwareMgmtClient.virtual_machine_instances.begin_create_or_update` to create a VM instance and if it's not vaild, it would raise the error. Yet for some reason you can not create this resource by SDK (somehow azure cli can do it because it's using the vendored SDK in an old version which now is not public, and it has the logic to first check the connected machine's existance and create one if receive 404, which also can not be applied in mgmt SDK for the SDK is auto generated). 

So yes, for now, I guess you have to create a connected machine by sending an HTTP request or go through the Website ui, then pass its resource uri to `ConnectedVMwareMgmtClient.machine_instances.begin_create_or_update` to create the VM instance you want.
