### ISSUE TITLE
Functions, failed on trigger timer

### ISSUE THREAD

**Issue by mirkomancin** [Azure/azure-sdk-for-python#3870]
Hello, I have a problem from last friday. I have a scenario that use v1 functions wrote in python and from few days, functions that trigger on timer, give me this error:

Function (xxx) Error: The listener for function 'Functions.xxx' was unable to start. mscorlib: One or more errors occurred. Microsoft.WindowsAzure.Storage: The remote server returned an error: (403) Forbidden.

I don't find anything on documentation about this problem. Please help me. Thank you

**Comment by lmazuel** [comment]
Hi @mirkomancin 
Sorry for the later answer, tagging the service team on this (not Python SDK specific)

**Comment by lmazuel** [comment]
Closing this issue, since it was a Function issue. If the problem is still there, please open a feedback on Azure Portal for the Function team directly, as this repo is focused on SDK. Thanks.
