### ISSUE TITLE
Azure Identity cryptography Exception

### ISSUE THREAD

**Issue by baswarajmamidgi** [Azure/azure-sdk-for-python#38721]
- **azure-identity**: 
- **1.19.0**: 
- **Azure Functions Linux**:
- **3.10**: 

**Describe the bug**
```
from azure.identity import DefaultAzureCredential 
```
is throwing following exception

```
from azure.identity import DefaultAzureCredential File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/__init__.py", line 10, in <module> from ._credentials import ( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/__init__.py", line 5, in <module> from .authorization_code import AuthorizationCodeCredential File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/authorization_code.py", line 9, in <module> from .._internal.aad_client import AadClient File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_internal/__init__.py", line 5, in <module> from .aad_client import AadClient File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_internal/aad_client.py", line 11, in <module> from .aad_client_base import AadClientBase File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_internal/aad_client_base.py", line 20, in <module> from .aadclient_certificate import AadClientCertificate File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_internal/aadclient_certificate.py", line 7, in <module> from cryptography import x509 File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/x509/__init__.py", line 7, in <module> from cryptography.x509 import certificate_transparency, verification File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/x509/certificate_transparency.py", line 8, in <module> from cryptography.hazmat.bindings._rust import x509 as rust_x509
```

** Possible reason **
Last night there was an update in cryptography version, since cryptogrphy version is loosly pinned in the azure identity package, new builds are failing 

**To Reproduce**
1. Install latest version of azure identity
2. Import latest version of cryptography
3. ImportDefaultAzureCredential

**Expected behavior**
following import should not give any error  from azure.identity import DefaultAzureCredential 

**Screenshots**
![Image](https://github.com/user-attachments/assets/26c29a5d-77cd-4bb3-b5a0-3d9237b1ec9a)

**Additional context**
https://cryptography.io/en/latest/changelog/#v44-0-0

**Comment by kirtigargg** [comment]
We were getting same issue with azure.identity.DefaultAzureCredential() where it returned `NameError: name azure not found`.

We were able to temporarily resolve it by installing `cryptography==43.0.3` before installing `azure-identity`

**Comment by pvaneck** [comment]
Will use https://github.com/Azure/azure-sdk-for-python/issues/38725 for tracking since that has more context/info.
