### ISSUE TITLE
Cannot read AML metrics log with azureml-core (SDK V1) with AML SDK V2 mlflow way

### ISSUE THREAD

**Issue by nsphung** [Azure/azure-sdk-for-python#38724]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.22.4
- **Operating System**: Linux
- **Python Version**:  3.10

**Describe the bug**

We wrote AzureML metrics with `azureml-core` ([Python AML SDK V1](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-track-monitor-analyze-runs?view=azureml-api-1&tabs=python)) but we cannot read AML metrics with [AML SDK V2 mlflow](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-track-experiments-mlflow?view=azureml-api-2#get-params-and-metrics-from-a-run) way.

**To Reproduce**
```
import mlflow
runs = mlflow.search_runs(experiment_names=[ "my_exp" ], filter_string="tags.run_id='my_run_id'",output_format="list")
runs[0]
```

It's displaying that the metrics is empty:

```
<Run: data=<RunData: metrics={}, params={}, tags={'alias': 'None',
...
```

Whereas when querying the same run with AML SDK V1:

```
from azureml.core import Experiment
exp = Experiment(workspace=workspace, name="my_exp")
run = list(exp.get_runs(tags={"run_id": "my_run_id"}))[0]
run.get_metrics()
```

Here's my metrics is displayed like expected.

**Expected behavior**
Will it be possible to read metrics from [AML SDK V2 mlflow](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-track-experiments-mlflow?view=azureml-api-2#get-params-and-metrics-from-a-run) which were written using `azureml-core` ([Python AML SDK V1](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-track-monitor-analyze-runs?view=azureml-api-1&tabs=python)) ?

**Screenshots**
We want to get these metrics out of our experiment run:

![Image](https://github.com/user-attachments/assets/99374e0c-7bef-473e-90c4-37a2f30ce8e7)

**Additional context**

**Comment by achauhan-scc** [comment]
below code worked for me

```
import mlflow
from azure.identity import DefaultAzureCredential
from azure.ai.ml import MLClient

def printMetrics(metrics):
  for key, value in metrics.items():
    print(key, value)

ml_client = MLClient.from_config(DefaultAzureCredential())
exp_name="my-exp"
workspace_name ="my_workspace_name"
ws = ml_client.workspaces.get(name=ml_client.workspace_name)
client = mlflow.tracking.MlflowClient(tracking_uri=ws.mlflow_tracking_uri)
run_id_or_name ="<run name or run id>"

exp = client.get_experiment_by_name(name=exp_name)
runs = client.search_runs(experiment_ids=[exp.experiment_id])

for run in runs:
 if run.info.run_name == run_id_or_name or run.info.run_id== run_id_or_name:
    metrics = run.data.metrics
    printMetrics(metrics)
