### ISSUE TITLE
`azure.core.settings` triggers cyclic import to get `AbstractSpan`

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#38723]
At this line, `azure.core.settings` imports `azure.core.tracing` to get a type - as far as I can tell, solely for type checking purposes.

https://github.com/Azure/azure-sdk-for-python/blob/347b6cbc1fda32568357d3ebf6f9ddc3f881e034/sdk/core/azure-core/azure/core/settings.py#L47

Unfortunately, this triggers an import of `azure.core.pipeline`:

https://github.com/Azure/azure-sdk-for-python/blob/347b6cbc1fda32568357d3ebf6f9ddc3f881e034/sdk/core/azure-core/azure/core/tracing/_abstract_span.py#L23

Which imports `azure.core.pipeline._base`:

https://github.com/Azure/azure-sdk-for-python/blob/347b6cbc1fda32568357d3ebf6f9ddc3f881e034/sdk/core/azure-core/azure/core/pipeline/__init__.py#L191

Which imports `azure.core.pipeline.policies`:

https://github.com/Azure/azure-sdk-for-python/blob/347b6cbc1fda32568357d3ebf6f9ddc3f881e034/sdk/core/azure-core/azure/core/pipeline/_base.py#L44

Which imports `azure.core.pipeline.policies._distributed_tracing`:

https://github.com/Azure/azure-sdk-for-python/blob/347b6cbc1fda32568357d3ebf6f9ddc3f881e034/sdk/core/azure-core/azure/core/pipeline/policies/__init__.py#L36

Which tries to import `settings` again:

https://github.com/Azure/azure-sdk-for-python/blob/347b6cbc1fda32568357d3ebf6f9ddc3f881e034/sdk/core/azure-core/azure/core/pipeline/policies/_distributed_tracing.py#L40

I can't explain how this is working in test suites, though I assume it's something to do with the pkgutil hacks for namespace packages (which you neither need, nor should be using for `azure.core`). It's very easy to construct optimised layouts (for faster install/import times) that break the flimsy hack, and I would suggest just relying on normal Python semantics. For the few cases where you genuinely want namespace packages, omit the `__init__.py` or add the additional search paths very explicitly.

This particular issue is also easily fixed by moving imports that are solely for type checking under `if typing.TYPE_CHECKING` tests, such as the one I referenced first.

**Comment by kristapratico** [comment]
Thanks @zooba, we'll take a look at this asap!

Also adding @pvaneck since this might involve some refactoring of tracing code.

**Comment by pvaneck** [comment]
Thanks for the detailed info, @zooba! We can certainly add the `if typing.TYPE_CHECKING` for that import since it is only for typing. I'd be curious to hear how you found this, as I haven't been able to get Python to complain when importing `settings`. Did you encounter an import error?

**Comment by zooba** [comment]
I'm using a non-standard importer (I have it all [packed into a DLL](https://github.com/zooba/pymsbuild#dll-packing)), so that would be my guess.

It really shouldn't make any difference though, which is why I'm more suspicious of the `pkgutil`/`pkg_resources` tricks - those are certainly not going to work with my importer, but they shouldn't be necessary for the overall import to succeed (only where users have installed parts of the SDK into separate directory trees). But the import cycle should always be there, which is what confuses me.

My best guess is that `pkgutil` does _something_ that breaks the cycle, and because my importer breaks `pkgutil` it also breaks the accidental fix.
