### ISSUE TITLE
Improve documentation of service bus ServiceBusReceiveMode and ServiceBusMessageState

### ISSUE THREAD

**Issue by CaselIT** [Azure/azure-sdk-for-python#38728]
Since there classes are subclasses of str and int respectively the docs include all the str and int methods, that don't make much sense in this context.

Webpage:
- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.html#azure.servicebus.ServiceBusMessageState
- https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.html#azure.servicebus.ServiceBusReceiveMode

edit: it applies also to ServiceBusSubQueue https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.html#azure.servicebus.ServiceBusSubQueue and many names in the https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/latest/azure.servicebus.management.html# module

**Comment by kashifkhan** [comment]
Thank you for the feedback @kashifkhan . We will investigate and get back to you asap.

**Comment by l0lawrence** [comment]
Hi @CaselIT we have a pr out to fix this issue, thanks for bringing this to our attention.

**Comment by CaselIT** [comment]
thanks!
