### ISSUE TITLE
Multiple processor processing same partition if they create ownership at same time

### ISSUE THREAD

**Issue by MartinKosicky** [Azure/azure-sdk-for-python#38812]
On the following line:
https://github.com/Azure/azure-sdk-for-python/blob/5d2f42bd11ff6330805093789fda96acc098964a/sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/_blobstoragecsaio.py#L141

it seems that if the ownership blob doesnt exist, because the Overwrite is set to TRUE, it can silently cause that 2 processors are processing same partition which i am seeing on the blob.  I would like if someone can validate if my thinking is wrong :D, but that is what I am seeing in log analytics that both are uploading the same blob and then both processing same partition id.

**Comment by kashifkhan** [comment]
Hi @MartinKosicky,

I would need some more information about your set up before we can understand what is happening: -

* How many partitions are there in the EventHub ?
* How many processors are there consuming from it?
* Are they all using the same storage for checkpointing ?

The function that you are seeing is during load balancing, where the partitions are split across consumers to make sure they are assigned partitions in a fair manner. So at that time you might see multiple of them trying to assert ownership of a partition. Once that is done the consumers should have their set and they stick to that, unless a pod dies and then rebalancing needs to happen.

**Comment by MartinKosicky** [comment]
the function i am seeing is when the processors are in initial state.  They all are reading from the same eventhub, same consumer group and use the standard checkpoint store and EventHubProcessor.    I have 16 partitions and 2 pods at startup.    And in the logs it's quite obvious that they are processing the same partition, but after first misunderstanding they get ownerhisp lost,  but the first batch they are indeed both processing same partition.

The code is called from _claim_one_partition , but since the overwrite is set to True,  both do an upsert and think they claimed the partition

**Comment by kashifkhan** [comment]
Are you able to share the debug logs with `logging_enable` set to true please? Also can you share any of your code that is being used?

```python
import logging
import sys

handler = logging.StreamHandler(stream=sys.stdout)
log_fmt = logging.Formatter(fmt="%(asctime)s | %(threadName)s | %(levelname)s | %(name)s | %(message)s")
handler.setFormatter(log_fmt)
logger = logging.getLogger('azure.eventhub')
logger.setLevel(logging.DEBUG)
logger.addHandler(handler)

...

from azure.eventhub import EventHubProducerClient, EventHubConsumerClient

producer = EventHubProducerClient(..., logging_enable=True)
consumer = EventHubConsumerClient(..., logging_enable=True)
```python

**Comment by MartinKosicky** [comment]
Ok the logs are rotated out and we did some changes to mitigate the issue and now I cannot simulate this. Only peace of log I have left was a CSV exported from [my_bug2.csv](https://github.com/user-attachments/files/18109812/my_bug2.csv)

If you look for the line 
`has claimed partition '13'`
you will see that it happened almost at same time on both containers, 
`a02503f6067b7104ab2d90533aa7c9bf0ef31483be6ac922f75436e0bbbd247c`
and `a85f4089e2114ae80cfb44659020d3421a589bec489b0acf68e185baaee80265`

**Comment by kashifkhan** [comment]
Hi @MartinKosicky, 

Based on the logs what Im seeing is normal. If you look at the section right above your original link in code, we are using an eTag so if there is a conflict then the first one in wins.  We are also using a service mechanism used to assert exclusive ownership over a partition known as the epoch, which is set to 0. There can be some overlap of 1 - 2 batches as ownership changes, load balancing happens etc. after which it should not be possible for both to be reading from the same partition.
