### ISSUE TITLE
Scheduled delivery with Storage queues and Service Bus queues

### ISSUE THREAD

**Issue by wobeng** [Azure/azure-sdk-for-python#3881]
Hi,

According to https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted#advanced-capabilities both Storage queues and Service Bus queues support Scheduled delivery.

Can you please provide a sample on how to do this?

Thank you in advance

**Comment by lmazuel** [comment]
@zezha-msft for Stoage, @annatisch for Service Bus if you knwo :)

**Comment by zezha-msft** [comment]
@wobeng please refer to our [samples](https://github.com/Azure/azure-storage-python/blob/master/samples/queue/queue_usage.py#L141).

**Comment by wobeng** [comment]
any update @zezha-msft and @annatisch

**Comment by zezha-msft** [comment]
Hi @wobeng, sorry for the delayed reply, I've been OOF recently.

To clarify, visibility_timeout in the `put_message` method dictates exactly how long to wait before the message is visible, thereby delaying the delivery. 

For more information, please refer to our [reference documentation](https://azure-storage.readthedocs.io/ref/azure.storage.queue.queueservice.html#azure.storage.queue.queueservice.QueueService.put_message).

**Comment by wobeng** [comment]
@zezha-msft are you sure? If yes then what do I use to make the message invisible to other consumers while it is being processed?

**Comment by zezha-msft** [comment]
Hi @wobeng, there's also a `visibility_timeout` parameter for [get_message](https://azure-storage.readthedocs.io/ref/azure.storage.queue.queueservice.html#azure.storage.queue.queueservice.QueueService.get_messages), which specifies what you just described.

**Comment by wobeng** [comment]
ahhh....make sense...so put message visibility_timeout is to delay message to storage and get message visibility_timeout is to delay to make the message invisible to other consumers while it is being processed?

If yes, they need to make that clear in the documentation. Can you see how I was confused?

**Comment by zezha-msft** [comment]
Hi @wobeng, which documentation are you referring to?

Are you saying that the reference doc([put_message](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-queue/azure/storage/queue/queueservice.py#L737) and [get_message](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-queue/azure/storage/queue/queueservice.py#L805)) is unclear?

**Comment by wobeng** [comment]
[put_message](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-queue/azure/storage/queue/queueservice.py#L737)  

A better description will be : 

> The visibility timeout specifies the time a message becomes available for processing by a system at a certain time. After the visibility timeout expires, the message will transition an active state. If a visibility timeout is not specified, the message will be available immediately.

**Comment by zezha-msft** [comment]
Hi @wobeng, I think we should avoid language like "becomes available for processing by a system", as we want the description to be about the Queue itself only, not any user application. Also, "the message  will transition an active state" begs a definition for what "active state" means; this is not an Azure Queue concept, but visibility is.

Thus, I think the current description is more appropriate:

> The visibility timeout specifies the time that the message will be invisible. After the timeout expires, the message will become visible. If a visibility timeout is not specified, the default value of 0 is used.

**Comment by wobeng** [comment]
@zezha-msft got it, however, when I  think of visibility timeout, I think of other clients not being able to process message while in flight. I don't see anything about schedule or delay for put message which is what is intended for

**Comment by zezha-msft** [comment]
@wobeng 

> After the timeout expires, the message will become visible.

The message gets put right away, it's just not visible for a certain period of time. This is scheduled delivery.

**Comment by wobeng** [comment]
ok thank you
