### ISSUE TITLE
Do Azure Cosmos DB full text functions (FullTextContains, FullTextScore, etc.) not support cross partition queries?

### ISSUE THREAD

**Issue by sachintha180** [Azure/azure-sdk-for-python#38857]
Hi, **I'm trying to understand if Full Text Search (on Azure Cosmos DB Python SDK) isn't supported across partitions**.

I'm led to believe this as a result of the following:

- When I run this query to get a few documents from my Azure Cosmos DB collection using **Full Text Search**, where I provide the partition key (no cross partition querying enabled):
```python
summary_nodes = self.cosmos.query_items(
    query="""
    SELECT c.id, c.text
    FROM c
    ORDER BY RANK FullTextScore(c.text, @text)
    """,
    partition_key="cbd31f95-a3a6-4a85-ba8a-67925980d37c",
    parameters=[
        {"name": "@text", "value": text},
    ],
    verbose=True,
)
print(summary_nodes)
```

- I get the desired output:
```
[{'id': 'cbd31f95-a3a6-4a85-ba8a-67925980d37c', 'text': "The letter dated 11th October 2024...."}]
```

- However, when I run the **exact same query without providing the partition key with cross partition querying enabled**:
```python
summary_nodes = self.cosmos.query_items(
    query="""
    SELECT c.id, c.text
    FROM c
    ORDER BY RANK FullTextScore(c.text, @text)
    """,
    parameters=[
        {"name": "@text", "value": text},
    ],
    verbose=True,
    enable_cross_partition_query=True,
)
print(summary_nodes)
```

- I'm met with the following error:
```
{"code":"BadRequest","message":"One of the input values is invalid.\r\nActivityId: 9c5f1c20-e0eb-4dcd-b965-c404a2af537b, Windows/10.0.20348 cosmos-netstandard-sdk/3.18.0"}
```

**I've set up all indexing policies + full text policies correctly** (as evident by the working code snippet). 

Here are the policies for reference:
```python
full_text_policy = {
    "defaultLanguage": "en-US",
    "fullTextPaths": [{"path": "/text", "language": "en-US"}],
}

# Reference: https://learn.microsoft.com/en-us/azure/cosmos-db/index-policy
indexing_policy = {
    "indexingMode": "consistent",
    "automatic": True,
    "includedPaths": [
        {
            "path": "/*",
        }
    ],
    "excludedPaths": [{"path": '/"_etag"/?', "path": "/vector/*"}],
    "fullTextIndexes": [
        {
            "path": "/text",
        }
    ],
    "vectorIndexes": [
        {
            "path": "/vector",
            "type": "quantizedFlat",
        }
    ],
}
```

In the above code snippets, I've used my own `self.cosmos.query_items` function - which is a function that shadows the Azure Cosmos Python SDK's `container.query_items` function, as follows:
```python
def query_items(
    self,
    query: str,
    partition_key: str | None = None,
    verbose=False,
    parameters: List[Dict[str, object]] | None = None,
    **kwargs,
):
    try:
        items = list(
            self.container.query_items(
                query=query,
                parameters=parameters,
                partition_key=partition_key,
                **kwargs,
            )
        )
        if verbose:
            print("[AZCOSMOSDB]\tFound {0} items".format(len(items)))
        return items
    except exceptions.CosmosHttpResponseError as e:
        if verbose:
            print("[AZCOSMOSDB]\tCannot query items.")
            print(e.http_error_message)
```

Looking forward to any clarification - thank you for your time!

**Comment by Pilchie** [comment]
@simorenoh  - can you take a look?

**Comment by simorenoh** [comment]
Hi @sachintha180, thank you for opening this issue. This is actually a known gap in the FTS query feature for the service currently - parametrized cross partition queries using `Order By Rank` will not work. We are currently working on fixing this.

However, you can still get cross partition queries to work with FTS by sending the entire query directly, ie
`query="SELECT c.id, c.text FROM c ORDER BY RANK FullTextScore(c.text, ['text-here']) "`, or using string formatting directly using either `%s` or Python's `.format` string method on the query before sending it.

Do let me know if this answers your question or if there's anything else you need help with - I can also ping in this issue again once we have merged the fix on our end if you'd like.

**Comment by sachintha180** [comment]
It definitely does! - I was a bit hesitant in using string formatting due to SQL injection. But I'll write a few checks to overcome this prior formatting the query. 

Thank you very much, looking forward to a ping when the issue is merged. Thank you for your time!
