### ISSUE TITLE
Role from get_role() fucntion does not contains public ip address

### ISSUE THREAD

**Issue by zhitongLBN** [Azure/azure-sdk-for-python#389]
Using `get_role()` to get the role, in its `configuration_sets` then in its `public_ips`, i got no public ip address
`{'idle_timeout_in_minutes': 4, 'name': u'publicIP', 'address': None}`

But using `get_delpoyments()` then find the role in its `role_instance_list`, in this role instance's `public_ips` i got my public ip address
`{'idle_timeout_in_minutes': 4, 'name': u'publicIP', 'address': u'104.47.140.144'}`

please fix this bugs! thank you!

**Comment by zhitongLBN** [comment]
I would like to know also why the public ip continue exist on my machine event run out of it's idle_timeout_in_minuites, and why the public address i got change every time, it dosen't matche the address of my reserved IP?????????? Thank you!

**Comment by ligangma** [comment]
I also use the method, but no VIP, please help me to find the RCA

delpoyments=sms.get_deployment_by_name(service_name, deployment_name)

for role_instance in delpoyments.role_instance_list:
                
                    print vars(role_instance)

{'instance_upgrade_domain': 0, 'instance_endpoints': <azure.servicemanagement.InstanceEndpoints object at 0x02807ED0>, 'instance_size': u'Medium', 'fqdn': u'', 'instance_fault_domain': 0, 'instance_name': u'allentestfile', 'role_name': u'allentestfile', 'host_name': u'allentestfile', 'power_state': u'Started', 'instance_error_code': u'', 'ip_address': u'10.209.54.21', 'instance_status': u'ReadyRole', 'instance_state_details': u''}

**Comment by lmazuel** [comment]
Unfortunately it's a limitation on the RestAPI, which does not give the Public IP for "get role":
https://msdn.microsoft.com/en-us/library/azure/jj157193.aspx

We won't be able to fix the problem :(
