### ISSUE TITLE
commit_batch to respect 100 entity limit

### ISSUE THREAD

**Issue by coffenbacher** [Azure/azure-sdk-for-python#402]
Rather than leave it up to the user to decipher this* cryptic error message and implement the 100 entity limitation on batching themselves, it would be great if the library could handle this.

*WindowsAzureBatchOperationError('99:One of the request inputs is not valid.RequestId:*******Time:2015-06-30T20:19:29.9051959Z',)

**Comment by huguesv** [comment]
That's an excellent suggestion!

**Comment by crwilcox** [comment]
Issue Migrated to https://github.com/Azure/azure-storage-python/issues/1
