### ISSUE TITLE
DLQ vs. ActiveMessages?

### ISSUE THREAD

**Issue by johnlento** [Azure/azure-sdk-for-python#4073]
https://github.com/Azure/azure-sdk-for-python/blob/1fe4be68a026be3cf411d3ad58c8739258a10285/azure-servicebus/azure/servicebus/models.py#L120

Can we add support for getting ActiveMessages vs. dead letter queue messages?  This appears to be supported in the C# libraries.

**Comment by lmazuel** [comment]
@annatisch ?

**Comment by KieranBrantnerMagee** [comment]
Hey Johnlento,
Have to apologize that this fell through the cracks so long, but in an effort to at least have an answer for anyone who comes across this with similar questions/to close the loop on this, I'd call out that our current generation azure-mgmt-servicebus package provides these details via the `count_details` object on a Queue/Subscription (inner field `dead_letter_message_count`), like so:

```
ServiceBusManagementClient(credential, subscription).queues.get(resource_group_name, servicebus_namespace_name, queue_name).count_details.dead_letter_message_count
```

Don't hesitate to reopen this or reach out if this doesn't address the problem in question, or if any other clarification is needed.
