### ISSUE TITLE
Azure Python SDK for ClassicAdministrator role

### ISSUE THREAD

**Issue by spoloj** [Azure/azure-sdk-for-python#4087]
Requesting for  python SDK to list classicAdministrator/ServiceAdministrator role assignment for list of subscriptions.
In this package `azure.mgmt.authorization.v2015_06_01` there is a classicadminitrator operation but I was unable to use the filter to list for all the subscriptions which I have access to. And also didn't find any particular operation related to this in later released packages.

Please let me know if I missed to check any further operations or packages related to this.

**Comment by lmazuel** [comment]
@yugangw-msft could you give some explainations that I could translate in SDK language? Thanks!

**Comment by yugangw-msft** [comment]
This API returns co-admins which have the highest privileges on the subscription. For context, co-admins are from old ASM world, but for compatibility ARM provision them in the AAD graph and maintain the accesses through giving out the owner role. It is not specific to the current users.  Let me know in case I have not quite understood your goals.

**Comment by spoloj** [comment]
Hi @yugangw-msft ,
we have a use case in our governance project where we need to get the data of classicAdministrators. Currently we are using this API 
https://docs.microsoft.com/en-us/rest/api/authorization/classicadministrators/list  but this is not so feasible as It is hard to filter out  just active subscriptions and our automation scripts are breaking because of deleted subscriptions.
Can we please get a python SDK for this ?

**Comment by yugangw-msft** [comment]
To filter out `active subscriptions`, you probably should go with azure-mgmt-resource and use the subscription client to find the accurate list. Check out the code [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/_profile.py#L828)

**Comment by uday1kiran** [comment]
How to check the list of roles assigned to the user logged in with?

**Comment by xiangyan99** [comment]
latest azure-mgmt-authorization is 2.0.0. Does it work for you?
