### ISSUE TITLE
GraphRBAC API: Invalid domain name in the request url 

### ISSUE THREAD

**Issue by kmai** [Azure/azure-sdk-for-python#4097]
Relevant stack trace:
```
  File "/Users/kmai/.virtualenvs/tenant-automation/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/kmai/.virtualenvs/tenant-automation/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/kmai/.virtualenvs/tenant-automation/lib/python3.7/site-packages/azure/graphrbac/operations/groups_operations.py", line 339, in internal_paging
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: Invalid domain name in the request url.
```

Request:

`https://graph.windows.net/<correct-tenant-id>/groups?$filter=startswith%28displayName%2C%20%27<correct-group-name>%27%29&api-version=1.6`

Response (400 Bad Request):
`'{"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"Invalid domain name in the request url."},"requestId":"764cb351-a492-45f8-af57-ac83c2e18bc6","date":"2018-12-19T13:25:39"}}'`

This worked until yesterday at this time. What's going on?

**Comment by yugangw-msft** [comment]
is the `<correct-tenant-id>` still existing? Can you check out with `https://login.windows.net/<correct-tenant-id>/.well-known/openid-configuration`. If yes, please send me the payload on the wire to yugangw at microsoft dot com

**Comment by kmai** [comment]
Issue reappeared again. Sending payload to you.

**Comment by Praburaj** [comment]
Is there any update on this issue. I am running into a similar issue as well.

**Comment by KKomarov** [comment]
It could happen because of tenant_id in token and tenant_id in request url mismatch

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60

**Comment by kmai** [comment]
I'm amazed by how an issue I opened two years ago has just been solved because the SDK has been deprecated. 

Way to go guys! This is one of the reasons I stopped using Azure.

**Comment by lmazuel** [comment]
@kmai I can't deny that the experience with that issue is disappointing, I'm the first one sad to be honest :(. This doesn't represent the time and energy we put in SDK globally, it happened that we can't be top priority on every single issue (and this one seems client configuration issue, and didn't get any update for a year).
