### ISSUE TITLE
Problems with the method predict_image

### ISSUE THREAD

**Issue by GeisaFaustino** [Azure/azure-sdk-for-python#4117]
I created and trained a project using only the portal and I´d like to use the SDK only for prediction purpose but I had some problems with the method predict_image.  According to the code, the parameter iteration_id is not mandatory (it´s default value is None, see image below). 

![capture1](https://user-images.githubusercontent.com/32823639/50609330-79188e80-0eb6-11e9-9400-87b65b818ec4.PNG)

However, if we don´t provide the iteration id the method predict_image return the error: HttpOperationError: Operation returned an invalid status code 'Not Found', which is not clear. (I wasted a couple of hours to understand what was happening). 

<img width="835" alt="capture2" src="https://user-images.githubusercontent.com/32823639/50609370-951c3000-0eb6-11e9-8d09-b95b30499627.PNG">

Thus, I´d like to suggest you change the message error and put the parameter iteration_id as mandatory (or fix the code to works without this parameter).  :-)

Thank you so much.

**Comment by ChrisHMSFT** [comment]
Hi @GeisaFaustino,

Please re-try with the latest version of the SDK 

Thanks,
Chris
