### ISSUE TITLE
ResourceManagementClient's resource_groups.create_or_update() gives Authentication failed

### ISSUE THREAD

**Issue by ewongbb** [Azure/azure-sdk-for-python#4124]
In the past,I used the ServicePrincipalCredentials to get the information, but noticed that the new way is to run get_client_from_{json_dict,auth_file}()   So I changed the code(as I was getting the same error).

I've updated to the latest azure pip package and with the following code:
```
#!/bin/env python

from azure.common.client_factory import get_client_from_auth_file
from azure.mgmt.resource import ResourceManagementClient as RmC
import os

hp = os.environ.get('USERPROFILE', None)
if hp is not None:
    cfile = os.path.join('cred.info')
    r = get_client_from_auth_file(RmC, cfile)
    r.resource_groups.create_or_update(
        'gandalf', {'location': 'eastus2'})


```
I get the following:
```
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    'gandalf', {'location': 'eastus2'})
  File "e:\azuresdk\azure-mgmt-resource\azure\mgmt\resource\resources\v2017_05_10\operations\resource_groups_operations.py", line 152, in create_or_update
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: AuthenticationFailedInvalidHeader
Message: Authentication failed. The 'Authorization' header is provided in an invalid format.

```
I went to line 144 of resource_groups_operations.py, and added:

  print(header_parameters)

And apparently, it doesn't have the Authorization Header.   Shouldn't the Authorization header be set during the get_client_from_auth_file's execution?

I have the correct clientSecret, subscriptionId, clientId and tenantId in the json dict
and copied the *EndpointUrl/ResourceId from https://docs.microsoft.com/en-us/python/api/azure-common/azure.common.client_factory?view=azure-python

Thanks

**Comment by lmazuel** [comment]
Hi @ewongbb 

To answer your question, no the header is not set during get_client_from_auth_file but later.

Could you update msrestazure and msrest to latest, and see if the message is different?
`pip install -U msrest msrestazure`

**Comment by ewongbb** [comment]
I think that fixed it.  Sorry for the pebcak.

**Comment by lmazuel** [comment]
No trouble, I'm glad it works :). I'm closing it, but feel free to re-open if necessary. Thanks!
