### ISSUE TITLE
Support for Service Bus Metrics

### ISSUE THREAD

**Issue by mandrie** [Azure/azure-sdk-for-python#413]
There are currently only a few metrics (like current Queue Count) that are available through the python SDK for Service Bus. It would be really nice to see the rich Metrics that are available through the REST API ( https://msdn.microsoft.com/en-us/library/azure/dn163589.aspx ) supported in the Python SDK as well so the Metrics are easier to access and work with. Specifically my team is interested in monitoring the incoming messages throughput, and today you can't do that through the Python SDK

**Comment by lmazuel** [comment]
Hello,

Sorry for the late answer.
In `servicebusmanagementservice`, you have the four methods:
* get_metrics_data_queue
* get_metrics_data_topic
* get_metrics_data_relay
* get_metrics_data_notification_hub

which are made for your purpose.

Please note that these methods are currently in the SDK "legacy" Service Management API. We are currently working to introduce the ARM new API (see change log for details).

If you think that my answer is not accurate to your problem, please feel free to re-open this bug.

Thank you!
