### ISSUE TITLE
Parameter to support append Libraries by databricks_notebook_activity

### ISSUE THREAD

**Issue by sgupta227** [Azure/azure-sdk-for-python#4144]
Hi,

It seems like we don't have parameter option available while creation of DatabricksNotebookActivity using databricks_notebook_activity.py scipt. Is it something can be achieved by some other way or do we need to fix this issue ?

To append the libraries we need another parameter let's say append_libraries which can be something like this:

'append_libraries ': {'key': 'typeProperties.baseParameters', 'type': '{object}'}
 may be need to consider to update in _attribute_map as well.

    _attribute_map = {
        'additional_properties': {'key': '', 'type': '{object}'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'depends_on': {'key': 'dependsOn', 'type': '[ActivityDependency]'},
        'type': {'key': 'type', 'type': 'str'},
        'linked_service_name': {'key': 'linkedServiceName', 'type': 'LinkedServiceReference'},
        'policy': {'key': 'policy', 'type': 'ActivityPolicy'},
        'notebook_path': {'key': 'typeProperties.notebookPath', 'type': 'object'},
        'base_parameters': {'key': 'typeProperties.baseParameters', 'type': '{object}'},

**Comment by sgupta227** [comment]
Hi Team, i see now databricks_notebook_activity_py3.py script which has all the required libraries option to attach it ? but if i just install azure and try to import azure.mgmt.datafactory.models import * the class i am using is DatabricksNotebookActivity, doesn't has the libraries parameter... just wondering how i can use _py3 scripts ? Any suggestion will be helpful

**Comment by hvermis** [comment]
@sgupta227 DatabricksNotebookActivity has property called "libraries". Is this what you are looking for?
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-datafactory/azure/mgmt/datafactory/models/databricks_notebook_activity.py#L46

**Comment by sgupta227** [comment]
@hvermis  ya thanks for your comment. I see these features are available with the new release of 0.7.0 version of data-factory-mgmt. But i saw a issue while using it. If i am trying to create a databricks linked service using AzureDatabricksLinkedService it needs the access token to passed as SecureString but when i provide the token as SecureString i am getting this error: 
TypeError: __init__() takes 1 positional argument but 2 were given. Which is working fine version 0.6.0. And if i provide access_token without SecureString it works fine. I am just wondering if i am missing here something ? looking forward to hearback from you.

**Comment by hvermis** [comment]
Can you paste your script here?

**Comment by sgupta227** [comment]
credentials = ServicePrincipalCredentials(client_id=service_principal_id, secret=service_principal_key, tenant=tenant_id)
adfv2_client_obj = DataFactoryManagementClient(credentials, subscription_id)
azure_databricks = AzureDatabricksLinkedService(domain=domain, access_token=SecureString(adb_access_token))
databricks_ls = adfv2_client_obj.linked_services.create_or_update(resource_group_name=rg_name, factory_name=df_name, linked_service_name='AzureDatabricks_Python1',properties=azure_databricks)

**Comment by hvermis** [comment]
@lmazuel  can you help? The difference between previous version of AzureDatabricksLinkedService and the current one is the latest has  **kwargs instead named arguments. Same for SecureString.

@sgupta227 Are you sure the AzureDatabricksLinkedService line is the one giving you the error? Can you paste full error here?

**Comment by sgupta227** [comment]
@hvermis  yes i am sure about the error. Since i tested quite number of times. As i know create_or_update method will take parameter if we provide the securestring for token else we will get an error while creation.

![image](https://user-images.githubusercontent.com/9718087/52773425-2d234280-303b-11e9-9277-3e0b36194234.png)

**Comment by sgupta227** [comment]
@hvermis, did you get any updates on the issue running adf v2 pipelines using azure 0.7.0 version ?

**Comment by hvermis** [comment]
@sgupta227 Did you get your error resolved?

**Comment by hvermis** [comment]
Closing as it diverged from original topic which was resolved.
