### ISSUE TITLE
Batch documentation out of date

### ISSUE THREAD

**Issue by lowandrew** [Azure/azure-sdk-for-python#4162]
It appears that the documentation for the batch service python API hasn't been updated to reflect the changes made in version 6.0 of the `azure-batch` python package.

For example, as per [History.rst](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-batch/HISTORY.rst) the `BatchServiceClient` had its `base_url` parameter changed to `batch_url` and the argument was made mandatory, but the [documentation for that class (as of today, January 11)](https://docs.microsoft.com/en-gb/python/api/azure-batch/azure.batch.batch_service_client.batchserviceclient?view=azure-python) still lists `base_url`.

It'd be nice to have the documentation updated to reflect the breaking changes.

**Comment by lmazuel** [comment]
@xingwu1 @matthchr @bgklein to comment (I think this is a known issue work in progress?)

**Comment by bgklein** [comment]
This should be resolved now. Den merged the PR yesterday (https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/398)

**Comment by lmazuel** [comment]
Indeed live, closing. Thanks @lowandrew for the feedback!
