### ISSUE TITLE
Limit per page results

### ISSUE THREAD

**Issue by Signorini** [Azure/azure-sdk-for-python#4166]
Good morning

It possible to set some per page limit in list_all|list methods?

Like compute_client.virtual_machines.list_all(per_page=1)

thanks

**Comment by lmazuel** [comment]
Hi @Signorini 

May I ask you what is the problem you are trying to solve first? :) Memory? Anything else? You describe a solution, but I want to make sure it fits the actual need you have ;)

Now, to strictly answer your question it depends on the API. It's usually called "top" when it exists, and the API you mention does not support it.

Thanks

**Comment by xiangyan99** [comment]
Close due to inactivity
