### ISSUE TITLE
VirtualMachineScaleSetIPConfiguration unexpected keyword argument 'dns_settings'

### ISSUE THREAD

**Issue by liorko87** [Azure/azure-sdk-for-python#4174]
I'm trying to create virtual machines scale set (vmss). 
When I'm trying to create an instance of `VirtualMachineScaleSetIPConfiguration` I got an error:

```
vmss_ips = VirtualMachineScaleSetIPConfiguration('%s_ips' % protocol_name, dns_settings=vmss_dns)
TypeError: __init__() got an unexpected keyword argument 'dns_settings'
```
pip freeze output:

```
azure==3.0.0
azure-batch==4.1.3
azure-cli-core==2.0.54
azure-cli-nspkg==3.0.3
azure-cli-telemetry==1.0.0
azure-common==1.1.16
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.3
azure-datalake-store==0.0.22
azure-eventgrid==0.1.0
azure-graphrbac==0.40.0
azure-keyvault==0.3.7
azure-mgmt==2.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==0.2.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==2.0.0
azure-mgmt-cognitiveservices==2.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==3.0.1
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==0.3.1
azure-mgmt-containerregistry==1.0.1
azure-mgmt-containerservice==3.0.1
azure-mgmt-cosmosdb==0.3.1
azure-mgmt-datafactory==0.4.0
azure-mgmt-datalake-analytics==0.3.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.3.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==1.2.0
azure-mgmt-eventgrid==0.4.0
azure-mgmt-eventhub==1.2.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iothub==0.4.0
azure-mgmt-iothubprovisioningservices==0.1.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-loganalytics==0.1.0
azure-mgmt-logic==2.1.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementpartner==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==0.2.0
azure-mgmt-monitor==0.4.0
azure-mgmt-msi==0.1.0
azure-mgmt-network==1.7.1
azure-mgmt-notificationhubs==1.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-powerbiembedded==1.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.2.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.1.0
azure-mgmt-resource==1.2.2
azure-mgmt-scheduler==1.1.3
azure-mgmt-search==1.0.0
azure-mgmt-servermanager==1.2.0
azure-mgmt-servicebus==0.4.0
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.6
azure-mgmt-storage==1.5.0
azure-mgmt-subscription==0.1.0
azure-mgmt-trafficmanager==0.40.0
azure-mgmt-web==0.34.1
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.1.2.9
azure-servicemanagement-legacy==0.20.6
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-file==1.1.0
azure-storage-nspkg==3.0.0
azure-storage-queue==1.1.0
msrestazure==0.4.34
```

**Comment by lmazuel** [comment]
Hi @liorko87 
This is correct, this parameter does not exist in `azure-mgmt-compute` 3.0.1
https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-compute_3.0.1/azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/virtual_machine_scale_set_ip_configuration.py#L74

And this parameter does not exist in the lastet API either:
https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2018_10_01.models.virtualmachinescalesetipconfiguration?view=azure-python

@tjprescott Do you know in what model DNS settings could be used?

**Comment by liorko87** [comment]
Hi @lmazuel 
Thank you for your reply.
The fifth parameter in `VirtualMachineScaleSetIPConfiguration` the is `public_ip_address_configuration`.
In order to create instance of `VirtualMachineScaleSetPublicIPAddressConfiguration` I need to pass the `dns_settings` parameter.

API reference: 
[https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2018_10_01.models.virtualmachinescalesetpublicipaddressconfiguration?view=azure-python](https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2018_10_01.models.virtualmachinescalesetpublicipaddressconfiguration?view=azure-python)

**Comment by lmazuel** [comment]
@liorko87 you then miss a level, `VirtualMachineScaleSetPublicIPAddressConfiguration` contains the attribute/parameter `public_ip_address_configuration` which is typed `VirtualMachineScaleSetPublicIPAddressConfiguration` and add an attribute `dns_settings`

The error suggests you tried to assign `dns_settings` directly to `VirtualMachineScaleSetPublicIPAddressConfiguration`, which is incorrect.

**Comment by liorko87** [comment]
@lmazuel Thank you, I really missed a level.
