### ISSUE TITLE
cosmosdb client create_or_update() method throws inconsistent and uninformative error with malformed name.

### ISSUE THREAD

**Issue by jreynolds01** [Azure/azure-sdk-for-python#4210]
```
client = get_client_from_cli_profile(azure.mgmt.cosmosdb.CosmosDB)
async_cosmosdb_create = client.database_accounts.create_or_update(
    resource_group,
    account_name,
    {
        'location': location,
        'locations': [{
            'location_name': location
        }]
    }
)
```

Throws an uninformative client 400 error: 

```
CloudError: 400 Client Error: BadRequest for url: https://management.azure.com/subscriptions/XXXX-XXX-XXX-XXXX/resourceGroups/XXX-XX-XX/providers/Microsoft.DocumentDB/databaseAccounts/XXX_XX_XX-XXXX?api-version=2015-04-08
```

The error is that the cosmosDB account name cannot contain underscores. The error thrown by the sdk should be consistent with the error provided in the portal, which points out the name constraint when setting up the service.

**Comment by lmazuel** [comment]
Hi @jreynolds01 
You're totally right, I created an issue on our repo that describes the endpoint, asking for a regexp to validate the name. This way, the message will be way more informative.
Keeping this open until the Python package is updated.
Thanks!

**Comment by changlong-liu** [comment]
Hi @Abyssknight , help to verify whether this is fixed in latest release.

**Comment by MehaKaushik** [comment]
I validated that it is fixed in the latest release. Closing this. Please feel free to open if you have any other questions related to this.
