### ISSUE TITLE
Password for App/Service Principal

### ISSUE THREAD

**Issue by kmai** [Azure/azure-sdk-for-python#4217]
Hi, 

As for what I've been researching, I found out the Service Principals use credentials from the Application.

I can create a Credential using the sdk, but when I try to use the service principal to log-in to something like a Container Registry, it doesn't work. 

How is the value specified in the `value` in `models.password_credential_py3.PasswordCredential` treated? Should the value be used as a password? Should it be base64 encoded? There is really not  much information about the GraphRBAC API and even less about the behavior to expect with this operations.

**Comment by lmazuel** [comment]
@yugangw-msft do you know the answer?

**Comment by yugangw-msft** [comment]
The value inside `PasswordCredential` should be the plain password text. Azure CLI has set the password like that all the time.

**Comment by lmazuel** [comment]
Closing since I think @yugangw-msft solved the question, feel free to comment still if not. Thanks!
