### ISSUE TITLE
Hard to infer parameter types from docs.

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-python#422]
I've been looking at `servicemanagement.create_virtual_machine_deployment` parameters. For instance `system_config` argument is very well described:

![image](https://cloud.githubusercontent.com/assets/159209/8736538/35aa793e-2bce-11e5-9492-06d5d583acbf.png)

I exactly know what to pass. But then I look at `resource_extension_references`:
![image](https://cloud.githubusercontent.com/assets/159209/8736551/5be8e874-2bce-11e5-8a98-170659979492.png)

I'm not 100% sure, but by using tab completion under `servicemanagement`, I can locate `servicemanagement.ResourceExtensionReference`.

Now I'm looking at the `network_config` parameter:

![image](https://cloud.githubusercontent.com/assets/159209/8736565/7d9b06c8-2bce-11e5-83da-7ae48f4a4abf.png)

Again, doesn't tell me what  type to pass here at all and I can't find a similar type under `servicemanagement` module.

I think these should be documented better. I wonder how others find their way around this.

**Comment by lmazuel** [comment]
Fix in https://github.com/Azure/azure-sdk-for-python/pull/507

Thank you!
