### ISSUE TITLE
Some authentication methods not in azure.common.credentials module

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#4221]
Looking at the docs page at https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python, I see some authentication methods are imported from `azure.common.credentials` while others come directly from `msrestazure.azure_active_directory`.

I'd suggest exposing them all from `azure.common.credentials` - even if they're just being directly imported - as that helps with discoverability. It also ensures that they can be deprecated/managed through the SDK even in the presence of changes to the underlying library (e.g. it could become a subclass or a total replacement without breaking backwards compatibility).

**Comment by johanste** [comment]
Yes - we did get some feedback on usage of types from msrest/msrestazure. And I think that @zooba is correct in that it would be less surprising if the types were exposed from azure.common.credentials.

**Comment by lmazuel** [comment]
@mmacy wanted confirmation that people doesn't like `msrest.authentication.CognitiveServicesCredentials` and would prefer `azure.common.credentials.CognitiveServicesCredentials`

**Comment by zooba** [comment]
To put it another way, I'd be happy if they're all in the one place - even `adal` would be fine.

The problem is that once I see one authentication method and decide I don't want to use it, I'm only really going to look in the same namespace for the other ones. So if the _only_ place I ever see is `msrestazure.azure_active_directory`, that's fine (well... I can live with it...), but right now it takes a decent amount of luck to find out that I can use MSIAuthentication from a different library.

**Comment by xiangyan99** [comment]
msrestazure is deprecated. Please use azure-identity library instead.
