### ISSUE TITLE
Enable accelerated networking on existing nic

### ISSUE THREAD

**Issue by bobkodex** [Azure/azure-sdk-for-python#4241]
Hi there,

im currently struggling on enabling/disabling accelerated networking on an existing network interface of a deallocatet vm with the python SDK.

Via
`
network_client.network_interfaces.create_or_update( .., ..., { ...  'enable_accelerated_networking': True} )
`
i'm of course able to create a new network interface with the desired setting. But **create_or_update** does not seem to let me update an existing nic as i'm getting the error

> msrestazure.azure_exceptions.CloudError: Azure Error: IpConfigDeleteNotSupported
> Message: IP Configuration pub-nicn0013 cannot be deleted. Deletion and renaming of primary IP Configuration is not supported

I'm missing here a simple update function that is for example provided with the compute_client. There it is possible to update a single value, for example:
`
compute_client.disks.update(resource_group_name, disk.name, {'disk_size_gb': 100})
`

Thanks in advance!

**Comment by lmazuel** [comment]
@tjprescott would you know this scenarion? Thanks!

**Comment by bobkodex** [comment]
Any update on this issue?

**Comment by allegradomel** [comment]
@bobkodex, 
Thank you for bringing this to our attention - we're currently looking into this issue and will update soon.

**Comment by allegradomel** [comment]
@KarenHammons can you transfer this to Datapath, since it's a NIC/Accelerated Networking issue?

**Comment by KarenHammons** [comment]
I’ll have to create a new tag for that.  For now, @Krishnan Rangachari<mailto:Krishnan.R@microsoft.com> or @Aanand Ramachandran<mailto:aanandr@microsoft.com> – can you help with this GitHub question please?

**Comment by KarenHammons** [comment]
Adding AccelNet PM, @Laxmana Rao Battula<mailto:labattul@microsoft.com>

From: Karen Hammons <karenha@microsoft.com>
Sent: Wednesday, December 11, 2019 2:46 PM
To: Azure/azure-sdk-for-python <reply@reply.github.com>; Azure/azure-sdk-for-python <azure-sdk-for-python@noreply.github.com>; Krishnan Rangachari <Krishnan.R@microsoft.com>; Aanand Ramachandran <aanandr@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-sdk-for-python] Enable accelerated networking on existing nic (#4241)

I'll have to create a new tag for that.  For now, @Krishnan Rangachari<mailto:Krishnan.R@microsoft.com> or @Aanand Ramachandran<mailto:aanandr@microsoft.com> - can you help with this GitHub question please?

**Comment by laxmanrb** [comment]
Make sure to stop/deallocate the VM before enabling AN for the existing NIC. Refer the link - https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#enable-accelerated-networking-on-existing-vms for additional details.

**Comment by allegradomel** [comment]
If there are no further issues, we can close this issue 
#please-close
