### ISSUE TITLE
Type error: Parameter 'notifications' must be of type '{Notification}'

### ISSUE THREAD

**Issue by todd-davenport** [Azure/azure-sdk-for-python#4243]
https://github.com/Azure/azure-sdk-for-python/blob/41b27ad5b1031fc7806927ac89b2c1fd897b537a/azure-mgmt-consumption/azure/mgmt/consumption/models/budget.py#L80

When trying to create a Budget with notifications, I am getting this error:
`ValidationError: Parameter 'notifications' must be of type '{Notification}'`

I can create a Budget() object, but when I try to pass it to `client.budgets.create_or_update()` It gets a type error. What sort of object is this expecting?

Example of Budget() obj below.

```print(budget_data)
{'additional_properties': {}, 'id': None, 'name': None, 'type': None, 'e_tag': None, 'category': 'Cost', 'amount': 20.0, 'time_grain': 'Monthly', 'time_period': <azure.mgmt.consumption.models.budget_time_period.BudgetTimePeriod object at 0x10fd68128>, 'filters': None, 'current_spend': None, 'notifications': <azure.mgmt.consumption.models.notification.Notification object at 0x111bdc8d0>}
```

**Comment by todd-davenport** [comment]
To clarify, this looks like a bug to me. I can create the `Notification` object and pass it to the `Budget` object. I have not seen an object nested inside a dict in this way before. 

If it's not a bug, I'd like to know how to construct the proper object to avoid getting this error.

**Comment by lmazuel** [comment]
Hi @todd-davenport 
`{Notification}` means a `dict<str, Notification>`. I understand this is confusing and the doc / error could be improved...

**Comment by todd-davenport** [comment]
@lmazuel, thank you for the clarification. I see that if I give a dictionary with any key, it creates the budget with the notification. 

I appreciate your time.
