### ISSUE TITLE
Add Sync-Token header for real-time consistency

### ISSUE THREAD

**Issue by lenala** [Azure/azure-sdk-for-python#4244]

**Comment by lmazuel** [comment]
Hi @lenala 
Would you tag you issue with Client, or more specifics tag, I thought it was a customer issue at first :)

Thanks!

**Comment by lenala** [comment]
@lmazuel I am very sorry, it was supposed to go to java repo. Still learning ZenHub. Closing for now, didn't want to interfere with python work.

**Comment by lmazuel** [comment]
No worry ;)
