### ISSUE TITLE
[ServiceBus] Update HTTP mgmt API to latest version

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#4247]
This will support creating/managing partitioned queues along with other entity properties.
Should investigate with this can/should be done with swagger.

**Comment by yunhaoling** [comment]
Closing the issue here. We're shifting our main efforts to the new generation of python servicebus library 7.0.0.

Support for latest HTTP mgmt API would be brought in 7.0.0b3.
