### ISSUE TITLE
[ServiceBus] Add support for rules and subscription filters

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#4248]
Currently this can only be achieved in the legacy HTTP based API.
Need to update new AMQP-based API to support this.

**Comment by K3UL** [comment]
Any plan to implement this ?

**Comment by KieranBrantnerMagee** [comment]
Hey folks;

Sorry that this sat for so long, as we're picking up work in this SDK in force we're going to be implementing this within the track 2 (non 0.*) release.  Please keep an eye out for this work and the planning surrounding it as we move past Preview1 of the new lib.

If there's a critical need for this in T1 don't hesitate to reopen/follow up with us so we can prioritize accordingly.

**Comment by KieranBrantnerMagee** [comment]
Edit:  Reopening and tagging as a track2 work item, thanks for your patience with the alert-spam!

**Comment by KieranBrantnerMagee** [comment]
An update for those interested:  Design has begun for Rule support in our Track2 release, but is currently blocked on a potential service issue.  Will loop back as we get further details on how we'll be proceeding with this.

**Comment by yunhaoling** [comment]
closing duplicate issue.
please uset the issue: https://github.com/Azure/azure-sdk-for-python/issues/11444 to track the progress.
