### ISSUE TITLE
[ServiceBus] Support websockets

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#4250]
This is also needed for EventHubs. Blocked by support needed in uAMQP.

**Comment by dennispg** [comment]
What is the update on this? Is my pull request redundant with upcoming updates , or can it be merged as a minor update to the current version of the library at least?

**Comment by KieranBrantnerMagee** [comment]
Hey Dennis,

Apt timing, as we're very literally on a call discussing this right now.  (There was some back and forth under whether this would be coming in via our next major version, but we've settled on looking into this now.)

Thanks in advance for all your patience thus far re: the delay to our engaging in this.  Expect PR comments shortly :)

**Comment by dennispg** [comment]
Thanks for the update, I'll work through all the comments this weekend!

**Comment by dennispg** [comment]
@KieranBrantnerMagee @yunhaoling are the updates ok?

**Comment by yunhaoling** [comment]
Closing the issue as the PR is merged already.

Apart from that, azure-servicebus 7.0.0b1 is out: https://pypi.org/project/azure-servicebus/7.0.0b1/ with websockets support.

**Comment by dennispg** [comment]
will there be a 0.50.3 release?

**Comment by KieranBrantnerMagee** [comment]
I see you wrote NVM but just in case for any other interested parties, we're intending to do a 0.50.3 release within the next few weeks, keep an eye out on the repo/release notes (or don't hesitate to ping us) for any updates.

Thanks again!
