### ISSUE TITLE
Publish Image Support

### ISSUE THREAD

**Issue by schaefi** [Azure/azure-sdk-for-python#427]
At SUSE we use a Windows Powershell procedure to publish an image. The details on the request api seems not documented, at least I couldn't find public information so far.

Are there plans to support this in the SDK ?

We are open to contribute on this part too

Thanks

**Comment by huguesv** [comment]
No plans to manually implement it, but I'm trying to find out if metadata for this will be available for the code generator.  Applies to this and #428.  I'll let you know what I find.

**Comment by schaefi** [comment]
Thanks, looking forward to get feedback. Please let me know if there is an opportunity for me to contribute here. So far I have only internal information about the XML body for this api

**Comment by huguesv** [comment]
I found some of this implemented in the Node.js SDK, but I don't know if it works.
https://raw.githubusercontent.com/Azure/azure-sdk-for-node/master/lib/services/computeManagement/lib/computeManagementClient.js

Under VirtualMachineVMImageOperations and VirtualMachineOSImageOperations.  Replicating is there, but I don't see publishing?

Node.js SDK is usually what I look at when documentation is wrong or missing :)

I was able to track down the program manager that owns image publishing.  @cavanes may be able to help you further.

**Comment by schaefi** [comment]
Thanks for the information.

I was reading the node sdk code. One question which came to my mind was that all the methods around replication and sharing are restricted to people "registered as image publisher". Thus I was wondering if there there is an easy way to test those api calls ?

With regards to publish an image I was reading the code in VirtualMachineVMImageOperations.prototype.beginSharing. To me sharing an image with the permission bit set to "public" feels like publishing an image :) Is that correct or does publishing means something different in Azure ?

Last but not least the nodejs code says sharing is only possible for already replicated images. Why is it required to replicate an image before I can publicly share it ? Or did I misunderstand that comment block

Thanks much

**Comment by schaefi** [comment]
ok, I have started to add support for replicate and unreplicate, as expected I got permission errors when I tested it with my subscription, thus I'm going to send a pull request without a test case in the first place.

Maybe you should consider to do real unit testing for the code (mock) and have an extra integration test platform. There are several features one can only test with newer subscriptions e.g resource groups or more permissions e.g publisher

While working with service management I also saw there is the legacy service management code which I'm going to start with and the new mgmt code which works with resource groups. I guess you plan to have both in place for some time ?

Nevertheless I have tested the new mgmt sdk code with our azure-updates subscription which is available on the new portal but it did not really work for me. I will open an issue for that with more
details

**Comment by schaefi** [comment]
Just for reference: here is the commit adding publish support

https://github.com/SUSE/azure-sdk-for-python/commit/2ec196b6c5b3cdc63a97fac080173cdf651924e8

we are still testing this, thus no pull request so far

**Comment by bear454** [comment]
Replication and publishing is now supported in `azurectl`, using PR #497, #501, #511, #514.

**Comment by lmazuel** [comment]
Thank you for your report @bear454 ! Do you think we can close this bug now?

**Comment by schaefi** [comment]
yep this can be closed

**Comment by bear454** [comment]
Yes!

**Comment by lmazuel** [comment]
Thank you!
