### ISSUE TITLE
Replicate Published Image across regions

### ISSUE THREAD

**Issue by schaefi** [Azure/azure-sdk-for-python#428]
At SUSE we use a Windows Powershell procedure to replicate a published image to be available in a set of regions. The details on the request api seems not documented, at least I couldn't find public information so far.

Are there plans to add replication support in the SDK ?

We are open to contribute on this part too

Thanks

**Comment by schaefi** [comment]
For reference here is the commit adding replication support. 

https://github.com/SUSE/azure-sdk-for-python/commit/169e58014dfff9d5a3984fb7f3cbb6811e0d844d

This one is already tested and in productive use by my team. I plan to provide pull requests as soon as we have tested publishing

**Comment by lmazuel** [comment]
Hi @schaefi 

Did you or @bear454 finally do the PR about this one? Do I still need to keep this issue open?

Thank you!

**Comment by bear454** [comment]
This was merged in as https://github.com/Azure/azure-sdk-for-python/pull/497 . Please close the issue, @lmazuel !

**Comment by lmazuel** [comment]
Thank you for the quick feedback! :)
