### ISSUE TITLE
Azure Cognitive services/Custom Vision/Text recognition - in order to get the operation-location header, I must pass in raw=True to the call

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#4285]
This is in reality a long running operation. I would expect that SDK should give me an object that I can poll on as the return value. 

See: [this](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/computer_vision_api.py#L627) for an example method that is very difficult to use.

**Comment by lmazuel** [comment]
We don't plan to fix that generation of SDK and change the pattern there, the new approach will take care of it.
