### ISSUE TITLE
cancel scheduled messages in new servicebus sdk 

### ISSUE THREAD

**Issue by wobeng** [Azure/azure-sdk-for-python#4300]
@annatisch When I schedule a message and save it in DB, and later try to cancel, I get no error, assuming the message has been cancelled 

When I go to the queue in service bus on the portal.azure.com, I see it has not been cancelled. 

Either portal.azure.com does not reflect cancel schedule messages immediately or something is wrong with the new service bus sdk

**Comment by wobeng** [comment]
any update on this?

**Comment by lmazuel** [comment]
Hi @wobeng , Anna is currently in vacation and won't be here before 2/15. I unfortunately can't help here, but just give you the date when she will have a chance to look at it :(
Thanks

**Comment by wobeng** [comment]
ok no worries, thank @lmazuel
