### ISSUE TITLE
WindowsAzureError - when creating new queue

### ISSUE THREAD

**Issue by SokolovVV** [Azure/azure-sdk-for-python#431]
Hi all, I create new azure cloud storage project and use python interactive from project want to create queue. But when i create queue, i take some error.
My steps:
1. from azure.storage import CloudStorageAccount
2.  storage_account = CloudStorageAccount('devstoreaccount1', 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==')
3. queue_service = storage_account.create_queue_service()
4. queue_service.create_queue('abc')
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\temp_vs_projects\AzureCloudService1\WorkerRole1\env\lib\site-packages\azure\storage\queueservice.py", line 240, in create_queue
    _dont_fail_on_exist(ex)
  File "C:\temp_vs_projects\AzureCloudService1\WorkerRole1\env\lib\site-packages\azure\__init__.py", line 527, in _dont_fail_on_exist
    raise error
WindowsAzureError: Unknown error (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:5ef0d450-0003-003b-6d58-cfa1e3000000
Time:2015-08-05T08:26:57.7662669Z</Message><AuthenticationErrorDetail>Request date header too old: 'Wed, 05 Aug 2015 07:27:22 GMT'</AuthenticationErrorDetail></Error>
```

**Comment by zooba** [comment]
Is the time on your computer correct? The last line seems telling.

**Comment by huguesv** [comment]
Looks like you are trying to use the storage emulator.  You'll need to set the EMULATED env variable, and pass None for both account name and key.  Improving this is on our TODO list:
https://github.com/Azure/azure-sdk-for-python/issues/375
https://github.com/Azure/azure-sdk-for-python/issues/388

**Comment by SokolovVV** [comment]
Thanks for answers
In my Django Web Role, i put this code in settings.py and this work
import os
os.environ["EMULATED"] = "true"
