### ISSUE TITLE
Move all service packages under an sdk folder

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-python#4319]
Based on https://github.com/Azure/azure-sdk/blob/master/docs/engineering-system/repo-structure.md which is trying to add some consistency across our azure-sdk repo's we should move all the packages under an sdk directory. Like:

```
sdk\<service name>\<package name>\README.md
sdk\<service name>\<package name>\*src*
sdk\<service name>\<package name>\*tests*
sdk\<service name>\<package name>\*samples*
```
Examples:
```
sdk\keyvault\azure-mgmt-keyvault\README.md
sdk\keyvault\azure-mgmt-keyvault\azure\mgmt\keyvault\
sdk\keyvault\azure-mgmt-keyvault\tests
sdk\keyvault\azure-mgmt-keyvault\samples
sdk\keyvault\azure-keyvault\README.md
sdk\keyvault\azure-keyvault\azure\keyvault\
sdk\keyvault\azure-keyvault\tests
sdk\keyvault\azure-keyvault\samples
```

A few things that we know needs to be updated when we make this restructuring:

1. The README files in the azure-rest-api-specs repo needs to be updated so the autorest tools can still function. We also need to stage the updates so that we don't disrupt too many in-flight PRs.
2. The build/CI scripts need to be updated so they understand the new structure. We should probably stage it so it understands both structures in the short term to enable incremental moving and minimize disruptions.
3. The documentation configuration system needs to be updated so it knows the new location of the README files and we don't break the documentation automation process.

**Comment by weshaggard** [comment]
template project was updated to new structure with #4564

**Comment by scbedd** [comment]
Plan of attack.

* I update the existing scripts to also support new location
* I migrate data-plane myself
* I get a list of the “quiet” management libraries from Laurent. Migrate those myself 
    * For the subset of “busy” management libraries, Laurent wants to take care of moving them immediately after closing AutoRest PRs for them. This is a manual step that HE is executing, so would prefer to own updating the code location as well

List of necessary scripts from Laurent:
This is what I have, that must work exactly the same (executed from the root):
-	python ./scripts/dev_setup.py
-	python ./setup.py install
-	python ./scripts/multiapi_init_gen.py azure-mgmt-compute
-	python -m packaging_tools.code_report azure-mgmt-compute 
-	pytest
-	python ./setup.py travis_deploy      # With TRAVIS_TAG=azure-mgmt-compute_5.0.0 and TRAVIS_BUILD_DIR=<root of your clone> (this guy doesn’t push, don’t worry 😊)

Also, let’s kill:
-	azure.pyproj
-	azure.sln

Also, let’s update:
-	.github/CODEOWNERS
-	https://github.com/Azure/azure-sdk-for-python/blob/d7306fde32f60a293a7567678692bdad31e4b667/swagger_to_sdk_config.json#L9 to “./sdk”

Also need to track updates for **Documentation** here. A large subset of the docs pull from the published packages on PyPI. However, some do still pull from `./` directory. Need to update that as necessary.
