### ISSUE TITLE
Worker Role does not start.

### ISSUE THREAD

**Issue by SokolovVV** [Azure/azure-sdk-for-python#432]
Hi all. I Create cloud service project and add two roles - django web role and worker role.
When i run project, thath OK. I see standart page in browser and i can write some code in web role.
But when i write code in worker role:
if __name__ == '__main__':
    while True:
           with open('C:/temp_vs_projects/test.txt','w') as w_f:
                   w_f.write('test')
            sleep(10.0)

This code does not work, but project compile right.
May be i dont set eny parameters for correct work web role with worker role?

Microsoft Azure Compute Emulator Log

[fabric] Role Instance: deployment27(235).AzureNeuralNetwork.NNWorkerRole.0
[fabric] Role state Busy
[runtime] Role entrypoint . CALLING   OnStart(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[runtime] Role entrypoint . COMPLETED OnStart(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[runtime] Role entrypoint . CALLING   Run(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[WaWorkerHost.exe] Exited with error code 0.
[WaWorkerHost.exe] 
[WaWorkerHost.exe] 
[runtime] Role entrypoint . COMPLETED Run() ==> ROLE RECYCLING INITIATED: Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[runtime] Role instance recycling is starting
[runtime] Role entrypoint . CALLING   OnStop(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[runtime] Role entrypoint . CALLING   OnStopping()
[runtime] Role entrypoint . COMPLETED OnStop(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[fabric] Role state Started
[runtime] Role entrypoint . CALLING   OnStart(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[runtime] Role entrypoint . COMPLETED OnStart(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[runtime] Role entrypoint . CALLING   Run(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[WaWorkerHost.exe] Exited with error code 0.
[WaWorkerHost.exe] 
[WaWorkerHost.exe] 
[runtime] Role entrypoint . COMPLETED Run() ==> ROLE RECYCLING INITIATED: Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[runtime] Role instance recycling is starting
[runtime] Role entrypoint . CALLING   OnStop(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint
[runtime] Role entrypoint . CALLING   OnStopping()
[runtime] Role entrypoint . COMPLETED OnStop(): Microsoft.WindowsAzure.ServiceRuntime.ProgramEntryPoint

**Comment by huguesv** [comment]
I have PTVS 2.2, VS 2015 and Azure Tools 2.6, and that worked fine for me.  I created a new cloud service, in the wizard I added a worker role and a django web role.  Then I edited the worker role to have just your main loop.  Your snippet doesn't have the `from time import sleep`, maybe double-check that you have that.  Anyway, the web site launched in a browser, and the test file was created.

Debugging a worker or web role is difficult, so I typically set the web or worker role as the active project in PTVS, and Start Debugging.  That way you can set breakpoints, break on exceptions, etc.  You may have to manually start the storage emulator if you are using it.

**Comment by SokolovVV** [comment]
Thanks, i set worker role to active project and its work for me. But when i deploy my simple project for azure cloud service, my web role work fine, but my worker role does not start.
My project description:
1.i have django web role. In this role i take soap request for client, then generate uuid and put this uuid to queue.
2.In my worker role, i take message from queue than generate some string, etc 'this is worker role', and put this to table.
3. Then client send new reqeust. In web role, i get from table message "this is worker role' and return it to client.
That work fine in local machine, but in azure cloud service, i think my worker role does not start.

**Comment by SokolovVV** [comment]
when i run my project local i chech Microsoft Azure Compute Emulator and some local folder for worker role. And found folder directory\DiagnosticStore\LogFiles with LaunchWorker.err file.
in this file i found error
Traceback (most recent call last):
  File "C:\temp_vs_projects\AzureCloudService1\AzureCloudService1\csx\Debug\roles\WorkerRole1\approot\env\Lib\site.py", line 703, in <module>
    main()
  File "C:\temp_vs_projects\AzureCloudService1\AzureCloudService1\csx\Debug\roles\WorkerRole1\approot\env\Lib\site.py", line 670, in main
    virtual_install_main_packages()
  File "C:\temp_vs_projects\AzureCloudService1\AzureCloudService1\csx\Debug\roles\WorkerRole1\approot\env\Lib\site.py", line 553, in virtual_install_main_packages
    f = open(os.path.join(os.path.dirname(__file__), 'orig-prefix.txt'))
IOError: [Errno 2] No such file or directory: 'C:\\temp_vs_projects\\AzureCloudService1\\AzureCloudService1\\csx\\Debug\\roles\\WorkerRole1\\approot\\env\\Lib\\orig-prefix.txt
Some one know about this error?

**Comment by SokolovVV** [comment]
My Solution is - use Web Role python env in Worker Role python
