### ISSUE TITLE
[Azconfig] Comparison between Key/Value types

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-python#4323]
- If both have etags, simply compare the etag + lastModified. In the ideal world, we would just compare etags, but the service team said that there is a small change of etags randomly being equal. We initially said that in addition to etag, we will compare key/value, but I think LastModified would be faster and 100% reliable (as it's a monotonically increasing long)
- If one or both don't have etags, compare all fields except for ETag and LastModified, as these are generated by the server.

For more information, see PR implementation for .NET: https://github.com/Azure/azure-sdk-for-net-lab/pull/103

**Comment by maririos** [comment]
FYI @johanste

**Comment by xiangyan99** [comment]
It is not applicable for Python.
