### ISSUE TITLE
Is there any way to pass subscription id  as an argument to these python APIs:

### ISSUE THREAD

**Issue by spoloj** [Azure/azure-sdk-for-python#4334]
- [budget_operations](https://docs.microsoft.com/en-us/python/api/azure-mgmt-consumption/azure.mgmt.consumption.operations.budgets_operations.budgetsoperations?view=azure-python#create-or-update-budget-name--parameters--custom-headers-none--raw-false----operation-config-)

- [action groups](https://docs.microsoft.com/en-us/python/api/azure-mgmt-monitor/azure.mgmt.monitor.operations.action_groups_operations.actiongroupsoperations?view=azure-python#create-or-update-resource-group-name--action-group-name--action-group--custom-headers-none--raw-false----operation-config-)

- [resource groups and resource locks](https://docs.microsoft.com/en-us/python/api/overview/azure/azure.mgmt.resource?view=azure-python)

**Comment by lmazuel** [comment]
Hi @spoloj 
In all the operations, the subscription_id is a parameter of the main client:
```python
from azure.mgmt.resource import ResourceManagementClient

LOCATION = 'eastus'
GROUP_NAME ='sample_resource_group'

resource_client = ResourceManagementClient(credentials, subscription_id)
resource_client.resource_groups.create_or_update(GROUP_NAME, {'location': LOCATION})
```

If you have a set of subscription_id, you then will need to create several clients.

Thanks,
