### ISSUE TITLE
Worker Role does not work after deploy

### ISSUE THREAD

**Issue by SokolovVV** [Azure/azure-sdk-for-python#434]
Hi all.
I deploy my project to azure cloud service and i have some problem with worker role.
My project has - web and worker role. 
From local machine its work ccorrectly.
About program:
I send some soap request  to web role and web role correct catch message and answer to me. In this soap request i send some data, this data puts into table by web role.
Worker role take data from table and procceding them. After this, worker role set new status from table to this data.
From client side after send data, my script wait 2 second and make new request to web role for answer.
But web role return status "Procces", but if worker procces data, he set status "Done".
I think that worker role does work correct in azure cloud service.
How can i resolved this problem?

**Comment by SokolovVV** [comment]
I find solution.
My error its just python package, i cant setup package by pip and i compile it in windows and put in site-packages folder from worker role and this work correct from local machine.
But when i deploy solution into azure, this package dont deploy and worker crush.
I setup remote desktop to worker role and create folder in worker role with package.
Then i redeploy solution and enter to remote desktop, find my project, copy package and paste into site-packages from python2.7 into remote desktop, then reset worker role and all work correct!

**Comment by zooba** [comment]
You should read the PTVS documentation on [cloud service projects](https://github.com/Microsoft/PTVS/wiki/Cloud-Project), especially the part about handling dependencies.
