### ISSUE TITLE
Objects not created at the cloud

### ISSUE THREAD

**Issue by liorko87** [Azure/azure-sdk-for-python#4340]
I'm writing a wrapper for the Azure SDK. 

In order to create a public IP for my scale set, I'm using this line:
`vmss_public_ip = VirtualMachineScaleSetPublicIPAddressConfiguration(name='%s_%d_public_ip'
                                                                                     % (protocol_name, idx),
                                                                                idle_timeout_in_minutes=3600)`

When I'm creating an object at the code, I cannot see it at my subscription. If initialization of an object instance object does not create a corresponding resource at the cloud, what the purpose of the Object?

**Comment by lmazuel** [comment]
Hi @liorko87 
The object is here to define the parameters only, you need to authenticate and send it to Azure after that.

More docs:
https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python
https://docs.microsoft.com/en-us/python/api/overview/azure/virtualmachines?view=azure-python

Thank you
