### ISSUE TITLE
Using local/development storage?

### ISSUE THREAD

**Issue by laptopdude90** [Azure/azure-sdk-for-python#436]
I'm using the Azure Storage Emulator. How do I tell Python to connect to my development emulator instead of the official server?

**Comment by huguesv** [comment]
See my comment here:
https://github.com/Azure/azure-sdk-for-python/issues/431

**Comment by laptopdude90** [comment]
Added that to the top of my code - No change.

**Comment by huguesv** [comment]
Can you share your code?

**Comment by laptopdude90** [comment]
from lib.post import PostLoader
from azure.storage import TableService, Entity
import json, urllib2, urllib
import os
from datetime import datetime
from time import sleep
os.environ["EMULATED"] = "true"
# Read config
tiwt_keys = open('keys.json')
keys = json.load(tiwt_keys)
tiwt_keys.close()

graph_url = "https://graph.facebook.com/v2.2/"
table_service = TableService(account_name=keys['azure_storage_account'], account_key=keys['azure_storage_key'])

That's enough to cause the problem

**Comment by huguesv** [comment]
Change that last line to:
```
table_service = TableService(account_name=None, account_key=None)
```

**Comment by laptopdude90** [comment]
Now it complains that the HTTP values are not in the correct format. Either way, authentication is still required for the emulator

**Comment by huguesv** [comment]
When it sees None or empty for account name and key, and ENVIRON set, it will set the correct flag and use the emulator credentials.
https://github.com/Azure/azure-sdk-for-python/blob/master/azure/storage/storageclient.py#L89

It sounds like you may be getting a different unrelated error now.  Are you running this inside a worker role in PTVS?  If not, did you manually start the emulator first?

You should paste the exact error you are getting.

**Comment by laptopdude90** [comment]
This is what I get: Traceback (most recent call last):
  File "main.py", line 99, in <module>
    main()
  File "main.py", line 67, in main
    table_service.create_table('posts')
  File "F:\Python27\lib\site-packages\azure\storage\tableservice.py", line 261,
in create_table
    _dont_fail_on_exist(ex)
  File "F:\Python27\lib\site-packages\azure\__init__.py", line 527, in _dont_fai
l_on_exist
    raise error
azure.WindowsAzureError: Unknown error (The value for one of the HTTP headers is
 not in the correct format.)
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
  <code>InvalidHeaderValue</code>
  <message xml:lang="en-US">The value for one of the HTTP headers is not in the
correct format.</message>
</error>

What's a worker role PTVS thing?

**Comment by huguesv** [comment]
https://github.com/microsoft/ptvs/wiki/Cloud-Project

I'm able to create a table successfully when the emulator is running.  If I don't start it, I get an error that it refused connection.  Not really sure what could be causing the error you are seeing.  If you can print out the contents of the request, that might help.  All the calls will go through this:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure/http/httpclient.py#L218

**Comment by laptopdude90** [comment]
So I'm not using PTVS. Can you elaborate on printing out the contents of the request?
