### ISSUE TITLE
[ComputeManagementClient] RunCommand timeout

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/azure-sdk-for-python#4369]
After provisioning a VM, I have code that then calls run_command to execute a multi-hour process (roughly 12 hours). However, after some period of time, the polling object that I get back from the run_command throws the following exception:

msrestazure.azure_exceptions.CloudError: Azure Error: VMExtensionProvisioningTimeout
Message: Provisioning of VM extension 'RunCommandLinux' has timed out. Extension installation may be taking too long, or extension status could not be obtained.

How do I avoid this exception in this use-case?

**Comment by lmazuel** [comment]
@yugangw-msft do you recognize this problem?

**Comment by yugangw-msft** [comment]
@koralski, please clarify

**Comment by Drewm3** [comment]
The Run Command has a timeout of 90 minutes currently. See the following documentation for more details: [https://docs.microsoft.com/en-us/azure/virtual-machines/windows/run-command](url)
