### ISSUE TITLE
[azure-mgmt-monitor] Cannot get activity logs following documentation

### ISSUE THREAD

**Issue by kawo123** [Azure/azure-sdk-for-python#4372]
I was following https://github.com/Azure/azure-sdk-for-python/blob/master/doc/sample_azure-monitor.rst#id1 to obtain activity logs for my Azure resource group and found few issues (possibly out-of-date documentation)

1. Importing `from azure.monitor import MonitorClient` fails
2. Importing `from azure.mgmt.monitor import MonitorMgmtClient` fails
3. Using `UserPassCredentials` fails with error `adal.adal_error.AdalError... Due to a configuration change made by your administrator, or because you moved to a new location, you must enroll in multi-factor authentication to access...`

---

The below is what I did to obtain the activity logs:
1. Import `from azure.mgmt.monitor import MonitorManagementClient`
2. Use service principal 
3. Use `monitor_mgmt_client` to query for activity logs

See below for snippets of the functional code
```
from azure.mgmt.monitor import MonitorManagementClient
from azure.common.credentials import ServicePrincipalCredentials

subscription_id = '[redacted]'
TENANT_ID = '[redacted]'
KEY = '[redacted]'
CLIENT = '[redacted]'

credentials = ServicePrincipalCredentials(
    client_id = CLIENT,
    secret = KEY,
    tenant = TENANT_ID
)

monitor_mgmt_client = MonitorManagementClient(
    credentials,
    subscription_id
)
.
.
.
activity_logs = monitor_mgmt_client.activity_logs.list(
    filter=filter,
    select=select
)
```

Here is an useful resource for creating service principal through Azure portal (https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal). It will be great if someone can update the documentation accordingly! Thank you!

**Comment by iscai-msft** [comment]
Hi, can you look at this [updated sample](https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring?view=azure-python)? Thank you for bringing this to our attention and apologies for the old doc still existing, we will take actions to remove it. Thanks!

**Comment by kawo123** [comment]
@iscai-msft Thanks for the change. Closing this ticket...
