### ISSUE TITLE
Can't specifiy driver node type in AzureDatabricksLinkedService model

### ISSUE THREAD

**Issue by jarandaf** [Azure/azure-sdk-for-python#4377]
Currently there is no difference between driver and worker node types (new kwargs e.g. `new_cluster_driver_type`/`new_cluster_worker_type` should be included). See https://docs.databricks.com/user-guide/clusters/node-types.html.

**Comment by iscai-msft** [comment]
@hvermis can you take a look at this? Thanks!

**Comment by hvermis** [comment]
This has been fixed in latest commits, pending new Python release.

**Comment by jarandaf** [comment]
@hvermis great, thank you!
