### ISSUE TITLE
msrestazure.azure_exceptions.CloudError: Azure Error: AuthorizationFailed DevTestLab

### ISSUE THREAD

**Issue by karaca** [Azure/azure-sdk-for-python#4379]
`from azure.common.client_factory import get_client_from_cli_profile,get_azure_cli_credentials
from azure.mgmt.devtestlabs.models.custom_image import CustomImage
from azure.mgmt.devtestlabs import DevTestLabsClient
from azure.mgmt.devtestlabs.models import LabVirtualMachine,GalleryImageReference
from azure.mgmt.devtestlabs.operations import GalleryImagesOperations,LabsOperations

#pre-defined variables
rg_name = "rgName"
lab_name = "labName"
vm_name="vmName"  

#clients-credential
credentials, subscriptions = get_azure_cli_credentials()
devtestlab_client = DevTestLabsClient(credentials,subscriptions)

#lab-virtual-machine-gallery-image-reference
lab_gallery_image_reference=GalleryImageReference(offer="WindowsServer",os_type="Windows",publisher="MicrosoftWindowsServer", sku="2019-Datacenter", version="latest")

#lab-virtual-machine
lab_virtual_machine=LabVirtualMachine(gallery_image_reference=lab_gallery_image_reference,user_name="uName",password="pwd",size="Standard_DS1_v2",lab_subnet_name="subnetName",location="westeurope",lab_virtual_network_id="/subscriptions/subscriptionID/resourceGroups/rg_name/providers/Microsoft.Network/virtualNetworks/vnName",disallow_public_ip_address=True,storage_type="standart")

#devtestlab_client.virtual_machines.list(rg_name,lab_name)
devtestlab_client.virtual_machines.create_or_update(rg_name, lab_name, vm_name,lab_virtual_machine,raw=True)`

My role is "DevTest Labs User" on this lab.

I can create a virtual machine over both Portal and Azure CLI but not python script even though I use CLI Credential to connect Azure.

Can anybody explain me what is wrong with my code?

**Comment by karaca** [comment]
> msrestazure.azure_exceptions.CloudError: Azure Error: AuthorizationFailed
> Message: The client 'XXX' with object id 'XXXid' does not have authorization to perform action 'Microsoft.DevTestLab/labs/virtualmachines/write' over scope '/subscriptions/subscriptionID/resourceGroups/rgName/providers/Microsoft.DevTestLab/labs/labName/virtualmachines/vmName'

**Comment by iscai-msft** [comment]
Taking a look at the [built in roles](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#devtest-labs-user), it doesn't appear that DevTest Labs Users have write access for virtual machines. Adding new roles, like contributor, would allow you access to perform write actions on virtual machines.

**Comment by karaca** [comment]
> Taking a look at the [built in roles](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#devtest-labs-user), it doesn't appear that DevTest Labs Users have write access for virtual machines. Adding new roles, like contributor, would allow you access to perform write actions on virtual machines.

**Comment by joaocosta** [comment]
Any insight into why when one has the "DevTest Labs User" VM creations succeeds trough the azure CLI but not the SDK ?
