### ISSUE TITLE
Azure keyvault sign() function gives errors on size of bytes for value

### ISSUE THREAD

**Issue by tezzigator** [Azure/azure-sdk-for-python#4399]
Im using the [official SDK docs](https://docs.microsoft.com/en-us/python/api/azure-keyvault/azure.keyvault.v7_0.key_vault_client.keyvaultclient?view=azure-python#sign-vault-base-url--key-name--key-version--algorithm--value--custom-headers-none--raw-false----operation-config-) which states only that the 'value' variable passed to the sign function should be in bytes.  I attempted to use the sign() function but got an error saying `Invalid length of 'value': 44 bytes. ES256 requires 32 bytes, encoded with base64url.`  so then I take my 32bytes and pass those 32bytes to the urlsafe_b64encode and use that result in value for the sign() function, and I still get same error.  I suspect that we are actually not supposed to base64urlencode it first?  Please confirm if we are supposed to take the direct 32byte hash and supply that to the sign() function?  Or if indeed some base64 needs to happen in some manner?

This can easily be duplicated
```
#!/usr/bin/env python3

from azure.keyvault import KeyVaultClient
from msrestazure.azure_active_directory import MSIAuthentication
from base64 import urlsafe_b64encode
from hashlib import blake2b
from binascii import unhexlify

kvclient = KeyVaultClient(MSIAuthentication(resource='https://vault.azure.net'));
op = urlsafe_b64encode(blake2b(unhexlify('00112233'), digest_size=32).digest())
print(op)
sig = kvclient.sign('https://REDACTED1.vault.azure.net', 'REDACTED2', 'REDACTED3', 'ES256', op)

$ ./aclient.py
b'QO46UZnfhhh93VCTkagtPzWj1Z-4PvmzmKdsmA4fepY='
Traceback (most recent call last):
  File "./aclient.py", line 12, in <module>
    sig = kvclient.sign('https://REDACTED1.vault.azure.net', 'REDACTED2', 'REDACTED3', 'ES256', op)
  File "/home/dev/hsm/lib/python3.6/site-packages/azure/keyvault/v7_0/key_vault_client.py", line 1022, in sign
    raise models.KeyVaultErrorException(self._deserialize, response)
azure.keyvault.v7_0.models.keyvault.v7_0.models.key_vault_error_py3.KeyVaultErrorException: (BadParameter) Invalid length of 'value': 44 bytes. ES256 requires 32 bytes, encoded with base64url.
```

**Comment by tezzigator** [comment]
on second thought - that error message is probably only there to support the REST API, which *does* require a text string of base64 encoded version of 32bytes

**Comment by iscai-msft** [comment]
@schaabs can you take a look into this issue please? Thanks!

**Comment by schaabs** [comment]
@tezzigator I believe you're correct that the error message is misleading here.  The SDK does indeed just take in bytes and it handles the encoding for you.  I'm not sure but I think the issue here is the hash algorithm you're using.  I believe that the ES256 sign algorithm expects a digest created with SHA256.  Could you try changing your hash algorithm to SHA256 instead of blake2 and see if that fixes your issue?

**Comment by tezzigator** [comment]
Hi - i actually have it working after i figured out the message was a red herring for my particular instance (using SDK and not REST-API).  my apoligies if my 2nd message wasnt clear as it was meant to mean that I had it all figured out and was working as that message only applies to REST
