### ISSUE TITLE
issue in computer vision prediction 

### ISSUE THREAD

**Issue by abdulbasit24434** [Azure/azure-sdk-for-python#4402]
Traceback (most recent call last):
  File "C:\Users\as\AppData\Local\Programs\Python\Python37\create.py", line 24, in <module>
    results = predictor.predict_image(Project_Id, test_data.read(), '' )
  File "C:\Users\as\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cognitiveservices\vision\customvision\prediction\custom_vision_prediction_client.py", line 206, in predict_image
    raise HttpOperationError(self._deserialize, response)
msrest.exceptions.HttpOperationError: Operation returned an invalid status code 'Access Denied'

**Comment by iscai-msft** [comment]
@areddish what do you think? Thanks!

**Comment by socpool** [comment]
For Access Denied the first thing to check is to make sure you are providing and using the correct ApiKey = prediction key from the settings page.

**Comment by areddish** [comment]
Check that there’s a valid Prediction key (can be found in the project settings) specified with the client and that project ID is valid for that.

For the client, the Prediction key is passed via the ApiKey property on the client object.

**Comment by abdulbasit24434** [comment]
got result in this form .unnormalized rectangle
![image](https://user-images.githubusercontent.com/47850472/53472993-104f2c00-3a8b-11e9-8436-283a28910794.png)

**Comment by abdulbasit24434** [comment]
my script:

predictor = CustomVisionPredictionClient(prediction_key, endpoint=ENDPOINT)
 
# Open the sample image and get back the prediction results.
with open("D:\\C.png", mode="rb") as test_data: 
    results = predictor.predict_image(project_id, test_data)

# Display the results.
 
img =  cv2.imread("D:\\C.png")
 
for pred in results.predictions:
   
       x = int(pred.bounding_box.width * img.shape[0])
       y = int(pred.bounding_box.height * img.shape[1])

       x2 = x + int(pred.bounding_box.left * img.shape[0])
       y2 = y + int(pred.bounding_box.top * img.shape[1])

       img = cv2.rectangle(img,(x,y),(x2,y2),(255,0,0), 2) 
       cv2.imshow('frame',img)

**Comment by areddish** [comment]
Hi @abdulbasit24434 

Assume cv2.rectangle takes opposite corners of the rectangle, I think you want this:

```
   x = int(pred.bounding_box.left* img.shape[0])
   y = int(pred.bounding_box.top* img.shape[1])

   x2 = x + int(pred.bounding_box.width* img.shape[0])
   y2 = y + int(pred.bounding_box.height* img.shape[1])

   img = cv2.rectangle(img,(x,y),(x2,y2),(255,0,0), 2) 
   cv2.imshow('frame',img)
```

**Comment by abdulbasit24434** [comment]
Thaks @areddish but problem remain unsolved below given two images one is from the out of your code and the second one from the portal which is what I doing for.
![image](https://user-images.githubusercontent.com/47850472/53484855-9b89eb00-3aa6-11e9-8858-426a75d66a14.png)
![image](https://user-images.githubusercontent.com/47850472/53484961-da1fa580-3aa6-11e9-872f-516c181b2b6b.png)

**Comment by abdulbasit24434** [comment]
solved thanks @areddish @iscai-msft .inter change shape -1to 0 and 0to1
 x = int(pred.bounding_box.left* img.shape[1])
   y = int(pred.bounding_box.top* img.shape[0])

   x2 = x + int(pred.bounding_box.width* img.shape[1])
   y2 = y + int(pred.bounding_box.height* img.shape[0])

   img = cv2.rectangle(img,(x,y),(x2,y2),(255,0,0), 2) 
   cv2.imshow('frame',img)
