### ISSUE TITLE
azure-mgmt-sql firewall_rules.get() does not return values

### ISSUE THREAD

**Issue by boscopaul** [Azure/azure-sdk-for-python#4403]
azure-mgmt-sql firewall_rules.list_by_server() does not return firewall rules. The resource group name and server name were provided. 

A 'firewallrulepaged' object was returned. Its current_page was an empty list.
I have setup around 3 firewall rules via UI.

**Comment by iscai-msft** [comment]
list_by_server returns an iterator, so it is by design that the current page is empty before you touch the iterator because of lazy loading. If you'd like to access all of the firewall rules, you can do a simple for loop or do a list call on the object, like 
```python
list(firewall_rules.list_by_server())
```
or
```python
for firewall_rule in firewall_rules.list_by_server():
    print(firewall_rule.id)
```

**Comment by boscopaul** [comment]
Thank you for the reply.
This works for me.
