### ISSUE TITLE
Include tests in each sdist

### ISSUE THREAD

**Issue by jayvdb** [Azure/azure-sdk-for-python#4412]
As there is no plan to distribute a single meta package (c.f. https://github.com/Azure/azure-sdk-for-python/issues/815), please include tests in each sdist.

Otherwise each openSUSE package needs to add a copy of the entire repo in its staging area in order to find and use the appropriate tests.

It should be only a matter of adding `tests/` to each `MANIFEST.in`, and updating any templates so new packages also get this right, but it might also require adding other directories if test data isnt located under tests/.

Ideally also ensure that `python setup.py test` in each sdist runs the tests, doing any prep required.

**Comment by jayvdb** [comment]
It would also be nice to have separate changelogs in each sdist.

Having to get it from GitHub is annoying.

Either I need to clone a large repo to get the tags, scroll through pages at https://github.com/Azure/azure-sdk-for-python/releases/, or guess it for a package, and in this case I failed to guess it based on apparent tag naming conventions https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-storage-common_1.4.0 is 404

**Comment by lmazuel** [comment]
Hi @jayvdb 
I wanted to check the Python guidelines before coming to you, and you're right, tests should be in the sdist:
https://docs.python.org/2/distutils/sourcedist.html#principle

Regarding the ChangeLog, it's already inside and named HISTORY.rst (we are moving to HISTORY.md since now PyPI supports Markdown)

**Comment by lmazuel** [comment]
Hi @jayvdb 
I merge my MANIFEST template that I use for all packages, new packages starting now will have tests inside.
Thanks for the report!
