### ISSUE TITLE
[azure-mgmt-eventhub] Support network rule sets

### ISSUE THREAD

**Issue by DenisBiondic** [Azure/azure-sdk-for-python#4456]
[FEATURE REQUEST]

Support definition of event hub namespace network rule sets through Azure Python SDK.

[INFO]

There is a feature, currently in preview, to define firewall rules on Event Hub namespaces. However, this is currently supported only through ARM templates: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-service-endpoints

**Comment by lmazuel** [comment]
@v-Ajnava are you aware of any Swagger update coming to support this feature?
Thanks!

**Comment by v-Ajnava** [comment]
@lmazuel and @DenisBiondic  Soon there will be update and current stable version will support network rule sets. will update the thread about it.

**Comment by lmazuel** [comment]
Released https://pypi.org/project/azure-mgmt-eventhub/2.5.0/
