### ISSUE TITLE
Subscription ID should not be required for PolicyClient

### ISSUE THREAD

**Issue by stefangordon** [Azure/azure-sdk-for-python#4474]
The `PolicyClient` in `azure-mgmt-resource` requires a Subscription ID.  However, when the client is used for defining/assigning Policies to a management group the user may not have any subscription ID to provide and it is not used for the API calls.

Here is the validation I am speaking of in `2018_05_01`:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/policy/v2018_05_01/policy_client.py#L40

So today when I use this I just pass in junk if I'm dealing with a management group:

```
        # SDK incorrectly requires subscription ID to have a value
        if management_group_id:
            self.client = PolicyClient(self.credentials, "not applicable")
        else:
            self.client = PolicyClient(self.credentials, self.subscription_id)
```

**Comment by lmazuel** [comment]
Hi @stefangordon 
You're right indeed, not all operations needs a subscription ID. However, the way we generate our code for now, does not allow us to make it optional :(.
I need to think about this a little more to see if we can improve our code generator. In the meantime, your hack with a string will work perfectly.

**Comment by changlong-liu** [comment]
Hi, Add @lmazuel for it's a codegen issue.

**Comment by lmazuel** [comment]
One year later my last comment, the current recommendation is to split this clients in two clients, since there is no simple way to make this parameter optional. This would be a Swagger rework.
