### ISSUE TITLE
New in 2012-02-12: service bus topic options that are missing

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-sdk-for-python#45]
According to http://msdn.microsoft.com/en-us/library/windowsazure/1b759576-0668-4018-8483-846e7bb193be#RESTAPI_2
```
Name: Xml Element Name
====================
MaximumNumberOfSubscriptions: MaxSubscriptionsPerTopic
MaximumNumberOfSqlFilters: MaxSqlFiltersPerTopic
MaximumNumberOfCorrelationFilters: MaxCorrelationFiltersPerTopic
EnableDeadLetteringOnFilterEvaluationExceptions: DeadLetteringOnFilterEvaluationExceptions
```

**Comment by lmazuel** [comment]
The first one will be covered in ARM (package `azure-arm-servicebus` to come), the three others don't exist anymore even in the "classic" RestAPI:
https://msdn.microsoft.com/en-us/library/azure/hh780749.aspx
