### ISSUE TITLE
Can not install azure 1.0.0rc1

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-python#451]
I want to install azure 1.0.0rc1 following https://github.com/Azure/azure-sdk-for-python/tree/master/azure.
But,
"pip install azure" will install 0.11.1.
"pip install azure==1.0.0rc1" failed because "Could not find a version that satisfies the requirement"

**Comment by huguesv** [comment]
I just published those today, it should work now.  Note that you may need to pass in the `--pre` option to pip.
