### ISSUE TITLE
disk_size_gb no longer taken into account for OSDisk ?

### ISSUE THREAD

**Issue by wandhydrant** [Azure/azure-sdk-for-python#4532]
Hello!

We are creating CentOS 7 VMs through the Azure Python SDK. The disks are unmanaged. We want to specify the size for the OS disk (root disk) at creation time. We do _not_ want to expand / resize the disk later, or to add data disks.

Until some months ago, this worked by specifying the 'disk_size_gb' parameter for OSDisk:
```
compute.virtual_machines.create_or_update(
  resource_group, vm_name, VirtualMachine(...,
    storageProfile=StorageProfile(
      osDisk=OSDisk(...,
        disk_size_gb=60
      )
   )
)
```
And we did have 60 GB for the root disk (after growing the file system within cloud-init). But right now, we make the same call, do not get any errors, and the disk size is only 30 GB, the size of the image. The disk_size_gb parameter seems to get ignored.

**Comment by lmazuel** [comment]
@yugangw-msft @williexu any ideas?

**Comment by williexu** [comment]
@adewaleo

**Comment by adewaleo** [comment]
@wandhydrant @lmazuel @williexu Hmm this is strange, the CLI's vm create allows me to specify the os disk size I desire...:

```
(cli-venv) [03:08 PM] Work-Mac:azure-cli tosin$ az vm create -n tosin-centos-60 \
     -g ova-test --image centos --os-disk-size-gb 62


(cli-venv) [03:11 PM] Work-Mac:azure-cli tosin$ az vm show -n tosin-centos-60 -g ova-test --query "{Name:name, OsDisk:storageProfile.osDisk}"
{
  "Name": "tosin-centos-60",
  "OsDisk": {
    "caching": "ReadWrite",
    "createOption": "FromImage",
    "diffDiskSettings": null,
    "diskSizeGb": 62,
    "encryptionSettings": null,
    "image": null,
    "managedDisk": {
      "id": "/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/ova-test/providers/Microsoft.Compute/disks/tosin-centos-60_OsDisk_1_c7d795f6fa2541009853d3d71b563054",
      "resourceGroup": "ova-test",
      "storageAccountType": "Premium_LRS"
    },
    "name": "tosin-centos-60_OsDisk_1_c7d795f6fa2541009853d3d71b563054",
    "osType": "Linux",
    "vhd": null,
    "writeAcceleratorEnabled": null
  }
}

```
The  service seems to respect the vm configuration I use. FYI: vm create uses an ARM template.

This might either be a programmatic error or a bug with the sdk or service for some specific scenario.

**Comment by wandhydrant** [comment]
Ahem. Very sorry!
Our growfs scripts needed to be more robust. The disk itself was all right, and disk_size_gb is correctly handled. Sorry for the noise!

**Comment by lmazuel** [comment]
No problem @wandhydrant if you encounter any other issue, feel free to ask ;)
