### ISSUE TITLE
Invalid Header for listKeys api call on api-version=2015-05-01-preview

### ISSUE THREAD

**Issue by schaefi** [Azure/azure-sdk-for-python#454]
I have tested the azure.mgmt.storage.storagemanagement SDK code along with a subscription supporting resource groups. I just wanted to list the storage keys with the method:

   StorageAccountOperations::list_keys()

The result was:

```
azure.common.AzureHttpError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Header</h2>
<hr><p>HTTP Error 400. The request has an invalid header name.</p>
</BODY></HTML>
```

I have added the following debug code into the SDK list_keys(self, resource_group_name, account_name): method:

     print http_request.url
     print http_request.headers

Here is what I got (tokens obfuscated)

```
https://management.azure.com/subscriptions/foofoo/resourceGroups/Default-Storage-WestUS/providers/Microsoft.Storage/storageAccounts/susesuselinuxenterprises/listKeys?api-version=2015-05-01-preview

{'x-ms-client-request-id': '9889b18d-e1d1-4054-9eed-1b1004a6b88f'}
```
Is there anything broken with the SDK or is this a "preview" related problem ? I can see all the information if I look it up from the new web portal page

Thanks

**Comment by schaefi** [comment]
ok I guess the reason for this is the access token I provided with the test. I still have no clue how to obtain such a token and most probably wrongly added the base64 encoded cert from the publish settings data

Please advise what is this access token and how can it be obtained ?

**Comment by huguesv** [comment]
I'm working on instructions on how to get tokens and will be adding them to the various readme files.  This should be ready in the next day or so.

Here's what I have so far.  I know the code sample works, but I still have to verify that the setup instructions I link to are sufficient.

How to setup AAD:
https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/

How to obtain a token:
```
import requests

def get_token_from_client_credentials(endpoint, client_id, client_secret):
    payload = {
        'grant_type': 'client_credentials',
        'client_id': client_id,
        'client_secret': client_secret,
        'resource': 'https://management.core.windows.net/',
    }
    response = requests.post(endpoint, data=payload).json()
    return response['access_token']

# TODO: Replace endpoint, client id and secret for your application
# In Azure portal, in your application configure page:
# - Click on View Endpoints, use the OAuth 2.0 Token Endpoint
# - The client id is already generated for you
# - The client secret is only displayed when the key is created the first time
auth_token = get_token_from_client_credentials(
    endpoint='https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/token',
    client_id='11111111-1111-1111-1111-111111111111',
    client_secret='2222222222222222222222222222222222222222222=',
)

from azure.mgmt.common import SubscriptionCloudCredentials
from azure.mgmt.resource import ResourceManagementClient

# TODO: Replace this with your subscription id
subscription_id = '33333333-3333-3333-3333-333333333333'
creds = SubscriptionCloudCredentials(subscription_id, auth_token)

resource_client = ResourceManagementClient(creds)
result = resource_client.resource_groups.list(None)
for group in result.resource_groups:
    print(group.name)
```

**Comment by huguesv** [comment]
The part that's missing with the article linked above is giving permissions to the application.  There's no UI for doing that in the portal.
The alternative is to use powershell or cli.
I've commited changes to a couple of the readmes, one is at:
https://github.com/Azure/azure-sdk-for-python/tree/master/azure-mgmt-storage

They now link to instructions for using the cli, but there are some problems with those instructions.
https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/

The author has been notified, hopefully we'll have an end-to-end story working soon.

**Comment by schaefi** [comment]
Thanks much for the token request code that is very helpful

Regarding the registration of the application I found the articles you posted yesterday too. I gave up at the point when it was said powershell is required to create the key pair in the active directory, because no Windows around ;) I was able to register my application on the web console but so far I have no keys.

The azure nodejs based tool seems to have support for that as you mentioned but on a first shot it did not work for me. I'll give it another try later

Thanks for your help

**Comment by huguesv** [comment]
We contacted the author of:
https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/

and he made some fixes to it (the node CLI section).

I just got it working following the CLI instructions.

The following additional articles were useful in using the CLI:
https://azure.microsoft.com/en-us/documentation/articles/xplat-cli-connect/
https://azure.microsoft.com/en-us/documentation/articles/xplat-cli/

One issue I encountered was that since I have multiple subscriptions on my Azure account, the wrong subscription was active. That active subscription happened to not have a tenant id associate with it, so I kept getting an error:
```
error:   tenantID cannot be null.
```

You can list your subscriptions with:
```
azure account list
```
Then to set the active subscription:
```
azure account set <subcriptionid>
```

After that the instructions worked as expected.  I'll update the readme files later, just be aware that the password you use in the `azure ad app create` command is the `client_secret`, and `client_id` is the ApplicationId.  I don't know if it's possible to get the endpoint from the CLI, I just used the portal for that.
```
auth_token = get_token_from_client_credentials(
    endpoint=<click view endpoints on the portal bottom toolbar and choose OAuth 2.0 Token Endpoint>',
    client_id='<ApplicationId>',
    client_secret='<password>',
)
```

If you get any errors along the way, let me know the details of the error.  I might have just encountered them myself at some point.

**Comment by huguesv** [comment]
I forgot to mention:
Since my Azure account is an outlook.com email address, I had to follow the instructions in https://azure.microsoft.com/en-us/documentation/articles/xplat-cli-connect/ in the section "use the log in method" to create a user and give it admin rights.  Then I was able to log in to the CLI using that user.

**Comment by schaefi** [comment]
all right, retrieving the access token works for me now :)

**Comment by schaefi** [comment]
>The part that's missing with the article linked above is giving permissions to the application. There's 
>no UI for doing that in the portal.

ok I think I'm at that point now. I got the following response:

```
azure.common.AzureHttpError: {"error":{"code":"AuthorizationFailed","message":"The client '5c6...' with object id '5c6c...' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/ce.../resourceGroups/Default-Storage-WestUS/providers/Microsoft.Storage/storageAccounts/suseazurerd'."}}
```

This errors refers to the missing permissions right ?

looking into the permissions docs next

**Comment by huguesv** [comment]
List keys gives out sensitive information, so that probably requires more permissions than 'Reader'.  Try setting it to 'Owner'.
https://azure.microsoft.com/en-us/documentation/articles/resource-group-rbac/

**Comment by schaefi** [comment]
sorry for the delay, I'm side tracked by another issue which I have to resolve first. I'll come back to this one soon

**Comment by schaefi** [comment]
I have tried to set the role to Reader via the azure nodejs tool: 'azure role assignment create ...'
but it seems the command requires to be logged in to an account. 

I called

```
azure config mode arm
azure login
```

but none of our accounts can authenticate this login session. I'm puzzled about this. The login command says:  Please note that currently you can login only via Microsoft organizational account or service principal. How is this different from our accounts we use to authenticate against the
Azure management portal ?

I really would love to be able to do this role assignment by a the management portal, it's imho the only part missing in the registration of the resource

**Comment by lmazuel** [comment]
Hi @schaefi, the role assignment can be made as @huguesv said by the portal using:
https://azure.microsoft.com/en-us/documentation/articles/resource-group-rbac/

Also, the new 2.0.0a1 release has Azure AD GraphRBAC API + Authorization API, which should allows us to assign roles using the SDK (didn't try this specific scenario for now however).

What is your thoughts about all this post and the latest release? What is for you the needed requirement to close this issue in a good way :) ?

Thank you!

**Comment by lmazuel** [comment]
Close this issue due to inactivity. Feel free to re-open it if you want to continue the discussion and you think there is something more to say.
Thank you!
