### ISSUE TITLE
Readme Content Verification - need to format readmes to match template doc

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#4554]
The following data-plane items need to be addressed. Validation has failed on the following readme list items.

tl;dr: Readmes should have at least have sections that correspond to the main sections as defined in the [template readme.](https://github.com/scbedd/azure-sdk/blob/master/docs/README-TEMPLATE.md) 

This is what the **tool checks**, but the ideal scenario is the readme is reworked to be somewhat like the [readme example.](https://github.com/scbedd/azure-sdk/blob/master/docs/README-EXAMPLE.md)

For a rundown on what you need to do to resolve these breaking issues ASAP, check out aka.ms/azure-sdk-analyze-failed

## ITEMS
31 readmes have at least one missing required section.
 - [ ] \README.rst is missing headers with patterns:
 * Azure .+ client library for Python
 * ^Getting started$
 * ^Key concepts$
 * ^Examples$
 * ^Troubleshooting$
 * ^Next steps$
 * ^Contributing$

(the items below have identical failures as the root readme as well, explicit list omitted for brevity)
 - [ ] sdk\attestation\azure-attestation\README.md
 - [ ] sdk\synapse\azure-synapse\README.md
 - [ ] \azure-applicationinsights\README.rst
 - [ ] \azure-batch\README.rst
 - [ ] \azure-cognitiveservices-knowledge-nspkg\README.rst
 - [ ] \azure-cognitiveservices-knowledge-qnamaker\README.rst
 - [ ] \azure-cognitiveservices-language-luis\README.rst
 - [ ] \azure-cognitiveservices-language-nspkg\README.rst
 - [ ] \azure-cognitiveservices-language-spellcheck\README.rst
 - [ ] \azure-cognitiveservices-language-textanalytics\README.rst
 - [ ] \azure-cognitiveservices-search-autosuggest\README.rst
 - [ ] \azure-cognitiveservices-search-customimagesearch\README.rst
 - [ ] \azure-cognitiveservices-search-customsearch\README.rst
 - [ ] \azure-cognitiveservices-search-entitysearch\README.rst
 - [ ] \azure-cognitiveservices-search-imagesearch\README.rst
 - [ ] \azure-cognitiveservices-search-newssearch\README.rst
 - [ ] \azure-cognitiveservices-search-nspkg\README.rst
 - [ ] \azure-cognitiveservices-search-videosearch\README.rst
 - [ ] \azure-cognitiveservices-search-visualsearch\README.rst
 - [ ] \azure-cognitiveservices-search-websearch\README.rst
 - [ ] \azure-cognitiveservices-vision-computervision\README.rst
 - [ ] \azure-cognitiveservices-vision-contentmoderator\README.rst
 - [ ] \azure-cognitiveservices-vision-customvision\README.rst
 - [ ] \azure-cognitiveservices-vision-face\README.rst
 - [ ] \azure-cognitiveservices-vision-nspkg\README.rst
 - [ ] \azure-eventgrid\README.rst
 - [ ] \azure-graphrbac\README.rst
 - [ ] \azure-keyvault\README.rst
 - [ ] \azure-loganalytics\README.rst
 - [ ] \azure-servicebus\README.rst
 - [ ] \azure-servicefabric\README.rst
 - [ ] \azure-servicemanagement-legacy\README.rst

**Comment by Prernajha2609** [comment]
Hii I would want to contribute please guide me further

**Comment by scbedd** [comment]
> Hii I would want to contribute please guide me further

Hey @Prernajha2609, apologies for the late response, I've been quite buried under an upcoming release.

We built a markdown scanner that can evaluate documents and ensure that they follow the basic structure that we decide. In this case, we have decided that we want our readmes to at least have the major sections:

- Azure .+ client library for Python
- ^Getting started$
- ^Key concepts$
- ^Examples$
- ^Troubleshooting$
- ^Next steps$
- ^Contributing$

Which pans out to markdown that follow general shape of:

```markdown
# Azure storage blob client library for Python
## Getting Started
<content>
## Key Concepts
<content>
<... other headers follow>
```

This is a simple proxy check to ensure that the readmes cover topics that we have decided are important.

If you're still interested in contributing, I would recommend that you pick a single readme from the above list and start converting it to the shape that we laid out above.

Other readmes to reference:
- [azure-core](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/README.md)
- [azure-appconfiguration](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/appconfiguration/azure-appconfiguration/README.md)

If you do end up contributing a readme update, please @ me in the PR! I'm much more on top of notifications nowadays.

**Comment by shubhusion** [comment]
Hi , I would also like to work on this issue.

**Comment by scbedd** [comment]
Instructions are above! Contributions are always welcome 👍

**Comment by shubhusion** [comment]
@scbedd can provide me a resource on how to run the markdown scanner ?

**Comment by kristapratico** [comment]
Closing, since this should be addressed in the python generator for the listed libraries
