### ISSUE TITLE
GraphRbacManagementClient Access token missing or malformed

### ISSUE THREAD

**Issue by MMollyy** [Azure/azure-sdk-for-python#4557]
Hello,
First off, i'm still very much new to python and the azure sdk is one of my first things I am trying out. So forgive me if what I'm asking is stupid.

I am trying to do things with the graphrbac and from what I can tell authentication with my service principal should work.

```
from azure.common.credentials import ServicePrincipalCredentials
from azure.graphrbac import GraphRbacManagementClient

# print('hello world')

AZURE_TENANT_ID = "###"
AZURE_CLIENT_ID = "###"
AZURE_CLIENT_SECRET = "###"
AZURE_SUBSCRIPTION_ID = "###"

credentials = ServicePrincipalCredentials(client_id=AZURE_CLIENT_ID, secret=AZURE_CLIENT_SECRET, tenant=AZURE_TENANT_ID)

graph_client = GraphRbacManagementClient(credentials, AZURE_TENANT_ID, base_url=None)
```
This part succeeds. Which should mean that the service principal that I am using passed authentication. Otherwise my last bit of code should already fail, and nothing should be loaded into 'graph_client'.

However running the following piece of code:
```
application = graph_client.applications.get('XYZ###')
print(application)
```

Outputs error:
```
azure.graphrbac.models.graph_error_py3.GraphErrorException: Access Token missing or malformed.
```

I can only read the following in the documentation: 
```
Parameters
credentials
<xref:msrestazure.azure_active_directory> 
Credentials needed for the client to connect to Azure.
```

but the type that is in the credential is different:
```
type(credentials)
<class 'msrestazure.azure_active_directory.ServicePrincipalCredentials'>
```

Also, I tested this SP in powershell:
It is allowed to do the things I want it to do so I know for sure it's not a permissions thing with the SP. Difference is, powershell can't use the SP with a token, it requires a certificate to authenticate against AzureAD.

Might it be possible that I can't use a service principal? Or maybe it needs to be with a certificate as well?

**Comment by MMollyy** [comment]
I had also found this page:
https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory?view=azure-python

Where it shows an example to use the `UserPassCredential'

**Comment by MMollyy** [comment]
Okay, I've gotten somewhat further.
Testing one of my other service principals I actually got an Access Denied, much like I get for my personal credentials. 

But the client_secrets are identical in terms of formatting.
So there shouldn't be any reason why this application service principal shouldn't get at least the same Access Denied 🤔

I understand the error is pretty straight-forward, but if the one sp with the same formatting works and this one doesn't. Then it actually isn't so much, and I've already tried 10 new keys.

**Comment by lmazuel** [comment]
Hi @MMollyy 
In order to access GraphRbac, you *need* to set the `resource` parameter on the credentials instance:
https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory

``` python
credentials = UserPassCredentials(
            'user@domain.com',      # Your user
            'my_password',          # Your password
            resource="https://graph.windows.net"
    )
```

Otherwise, the token is not authorized for this scope (hence, I believe, your issue).

**Comment by MMollyy** [comment]
that piece of code is exactly the same as mine:
```
credentials = ServicePrincipalCredentials(client_id=AZURE_CLIENT_ID, secret=AZURE_CLIENT_SECRET, tenant=AZURE_TENANT_ID)
```
Except your suggested piece of code is for a user. I don't want to use user credentials, because this piece of code is going into an automated pipeline and I don't want any user credential used in it.

**Comment by iscai-msft** [comment]
The same applies for using ServicePrincipalCredentials. I used the following method of defining my ServicePrincipalCredentials and it worked.
```python
ServicePrincipalCredentials(
    client_id=AZURE_CLIENT_ID, 
    secret=AZURE_CLIENT_SECRET, 
    tenant=AZURE_TENANT_ID,
    resource="https://graph.windows.net")

```
Let me know if this fixes your problem!

**Comment by MMollyy** [comment]
Hi @iscai-msft ,

I was already using that piece of code. Except this part:
```
resource="https://graph.windows.net"
```
Apparently that parameter is a requirement. I would kind of expect the graphrbac client to automatically go this endpoint, or is there some reason it would go to some other endpoint?

so thanks for that @iscai-msft !
Issue closed :)
