### ISSUE TITLE
delivery_tag vs x-opt-lock-token

### ISSUE THREAD

**Issue by fatal10110** [Azure/azure-sdk-for-python#4598]
According to the docs, lock token is not guaranteed on annotations as `x-opt-lock-token` , delivery tag should be preferred... But I don's see any code related to delivery tag... 

DOCS: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#message-renew-lock

ps. 

It's implemented in Golang library
https://github.com/Azure/azure-service-bus-go/blob/98fec12aac8b52e81ead4bdec8738987b8c33fa1/message.go#L483

and C# 

https://github.com/Azure/azure-service-bus-dotnet/blob/bf6acc9f25d69aadc9b5c328a0331329cd3bca6b/src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs#L336

**Comment by lmazuel** [comment]
@annatisch your thought? Thanks!

**Comment by annatisch** [comment]
Sorry - I missed this...
Thanks @fatal10110!
Yes you are correct, delivery tag is the preferred method for extracting the lock token.
Currently the C library we are using for the AMQP protocol layer does not expose the delivery tag for us to retrieve this information so we are falling back to using the message annotations.

I will add this to the back log to address before GA.

**Comment by fatal10110** [comment]
@annatisch Thanks!

p.s I tried to add it by myself, but saw that there is no access to it from python, but in the C library itself I saw some references to `delivery_tag`
https://github.com/Azure/azure-uamqp-c/search?q=delivery_tag&unscoped_q=delivery_tag

In uamqp-python it's commented out, seems like some work should be done
https://github.com/Azure/azure-uamqp-python/blob/e3e26b1621ae87ec72ecb68071dd40a18118ef85/src/vendor/inc/c_amqp_definitions.pxd#L52

**Comment by annatisch** [comment]
Thanks @fatal10110,

Yes some work needs to be done... while the delivery tag type is defined in the C library - the "TRANSFER_HANDLE" struct that it is defined as part of is not exposed in Python. So we will need to find an alternative means of exposing this... maybe in a similar was to `messagereceiver_get_received_message_id`:
https://github.com/Azure/azure-uamqp-python/blob/e3e26b1621ae87ec72ecb68071dd40a18118ef85/src/message_receiver.pyx#L62

**Comment by annatisch** [comment]
PR is now open to support this:
https://github.com/Azure/azure-uamqp-python/pull/94

**Comment by luipir** [comment]
> PR is now open to support this:
> [Azure/azure-uamqp-python#94](https://github.com/Azure/azure-uamqp-python/pull/94)

great, tnx @annatisch

**Comment by yunhaoling** [comment]
The issue has been fixed in our October uamqp release (>=1.2.3).
Close it for now, but feel free to re-open if the issue still exist.
