### ISSUE TITLE
Are there default values of "timeout" and "retries"? 

### ISSUE THREAD

**Issue by shitada** [Azure/azure-sdk-for-python#4599]
We can set timeout, reties or etc as extra parameters for each operations by "operation_config".

https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-operation-config?view=azure-python

Are there default values of "timeout" and "retries"?

**Comment by lmazuel** [comment]
Hi @shitada 
Default are customized in our runtime, when we receive no override:
- [Timeout is 100](https://github.com/Azure/msrest-for-python/blob/f1fec7dc142f36b84c461ae9660420c26b5fdcdd/msrest/universal_http/__init__.py#L427) (this object stick to [requests interpretation of timeout,](http://docs.python-requests.org/en/master/user/advanced/#timeouts) you can pass a tuple)
- [retries is a custom implementation of urllib3.Retry](https://github.com/Azure/msrest-for-python/blob/3653d29fc44da408898b07c710290a83d196b777/msrest/universal_http/requests.py#L331-L393)

Thanks!
