### ISSUE TITLE
Keyring cache token has failed for keyvault

### ISSUE THREAD

**Issue by akshaybabloo** [Azure/azure-sdk-for-python#4610]
I am trying to get secrets from the keyvault and I keep on getting a warning as:

```
Keyring cache token has failed: (1783, 'CredWrite', 'The stub received bad data')
```

Why am I even getting this? Is there a way to remove this warning?

**Comment by lmazuel** [comment]
Hi @akshaybabloo 
Just update your msrestazure dependency to at least 0.5.0, this would fix the issue automatically.
I'll let you close the issue if works, otherwise please share the version of your msrestazure dep.
Thanks!

**Comment by akshaybabloo** [comment]
Ok that worked. Will this requirement be updated anytime soon?

**Comment by lmazuel** [comment]
It's updated in the latest packages, all new install should install the latest msrestazure by default.
Closing since I believe we solved your question ;). Feel free to open a new issue if ncessary.
Thanks!
