### ISSUE TITLE
Expecting different behaviour when using roleassignments create operation 

### ISSUE THREAD

**Issue by MMollyy** [Azure/azure-sdk-for-python#4621]
Hello,

I'm using the following: 
https://docs.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2018_01_01_preview.operations.roleassignmentsoperations?view=azure-python#create-scope--role-assignment-name--parameters--custom-headers-none--raw-false----operation-config-

My code looks like:
```
role_assignment_parameters = {'role_definition_id': AZURE_TERRAFORM_ROLE.id, 'principal_id': created_service_principal.app_id}
sp_role_assignment = auth_client.role_assignments.create(scope, application.display_name, role_assignment_parameters, custom_headers=None)
```

And gives the error:
```
sp_role_assignment = auth_client.role_assignments.create(scope, application.display_name, role_assignment_parameters, custom_headers=None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\user\bootstrapper\lib\site-packages\azure\mgmt\authorization\v2018_01_01_preview\operations\role_assignments_operations.py", line 327, in create
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidRoleAssignmentId
Message: The role assignment ID '999-infra-user-testtesttest' is not valid. The role assignment ID must be a GUID.
```

But why is it asking me to supply a GUID? The Azure platform should generate a GUID for this role assignment.

Another part of my confusion: The documentation says it should be a name, but then asks for a GUID as input. 
It is very confusing to see terms being used inter exchangably. While a name can be a GUID, a GUID definatly cannot be a name. Names are not unique, GUIDs (Globally Unique IDentifier) are.

Some powershell output of a role assignment to a service principal:
```
Get-AzureRmRoleAssignment -ObjectId <object_id>

RoleAssignmentId   : /subscriptions/<subscription_id>/providers/Microsoft.Authorization/roleAssignments/10b19406-8fe7-43fc-a15e-8dfe2d944630
Scope              : /subscriptions/<subscription_id>
DisplayName        : bootstrapper
SignInName         : 
RoleDefinitionName : bootstrapper
RoleDefinitionId   : cda5bef2-541b-41b7-b84d-c77a55117891
ObjectId           : <object_id>
ObjectType         : ServicePrincipal
CanDelegate        : False
```

Doing this command in powershell I give the role assignment a scope, I give it an existing role definition ID or a role definition name and I get returned a role assignment with a valid GUID.
Example from powershell:
```
New-AzureRmRoleAssignment -ObjectId <ServicePrincipal ObjectID> -ResourceGroupName <Resourcegroup name> -RoleDefinitionName <Role definition name>
```

If this piece of the SDK is unfinished my suggestions would be:
- Remove the role_assignment_name entirely, because just as for powershell it is entirely obsolete.
- Change the role_assignment_name to be an optional parameter which is redefined as role_definition_name: Allowing for roles to be selected by name, which allows for regex expressions, and logical steps based on functional names.
- Move this to the RoleAssignmentProperties class and redefine it as an optional role_definition_name as per the previous suggestion.
- In all these suggestions: Let the azure platform handle the GUID assignment. Just like the SDK does for applications & service principals creates.

Right now I am very curious as to how I should approach this using the SDK ..

**Comment by lmazuel** [comment]
Hi @MMollyy 
Yes, the role assignement takes a GUID, this is an example:
```python
    role_assignment = authorization_client.role_assignments.create(
        resource_group.id,
        uuid.uuid4(), # Role assignment random name
        {
            'role_definition_id': contributor_role.id,
            'principal_id': msi_identity
        }
    )
```
Azure RestAPI does not generate an GUID unfortunately. CLI and Powershell are doing this for you, but SDK being generated from a endpoint description, they don't know this information and you have to provide one. I'm sorry for the confusion here :(

**Comment by lmazuel** [comment]
I'm tagging the ARM team if they want to comment on this limitation.

**Comment by MMollyy** [comment]
Okay thank you Imazuel.

Any suggestion how I can prevent GUID from already existing? 

Should we then create a uuid using uuid library, and create a search for the uuid to make sure it doesn't exist, before trying to create a roleassignment?

**Comment by MMollyy** [comment]
By the way, did you test this?
I get an exception raised on the uuid input from uuid.uuid4():
```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\Users\sadfr\bootstrapper\lib\site-packages\azure\mgmt\authorization\v2018_01_01_preview\operations\role_assignments_operations.py", line 327, in create
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: BadRequestFormat
Message: The request was incorrectly formatted.
```

Also tested with 
```
str(uuid.uuid4())
```

**Comment by lmazuel** [comment]
Yes, this code is tested and I extracted it from a bigger sample actually here:
https://github.com/Azure-Samples/compute-python-msi-vm

It's really unlikely the error comes from the uuid part, likely on the three others elements is wrong, could you share the actual call parameter you did?

uuid collision is usually not a problem, even CLI or Powershell are not testing it ([CLI example](https://github.com/Azure/azure-cli/blob/64a406554d7cad6fd463b81670b41469db391b2a/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py#L1067))

**Comment by MMollyy** [comment]
my piece of code:
```
scope = f'/subscriptions/{AZURE_SUBSCRIPTION_ID}/resourceGroups/{resource_group}'
AZURE_TERRAFORM_ROLE= {'terraform-ro': 'c86d87cd-74c3-4a35-b76b-7aa1c6992926'}
created_service_principal = graph_client.service_principals.create(sp_parameters, custom_headers=None)

role_assignment_parameters = {'role_definition_id': AZURE_TERRAFORM_ROLE['terraform-ro'],
                              'principal_id': created_service_principal.app_id}

sp_role_assignment = auth_client.role_assignments.create(scope, uuid.uuid4(), role_assignment_parameters, custom_headers=None)
```

**Comment by lmazuel** [comment]
You need to pass the SP object ID, and not the app ID

If you use the latest azure-graphrbac 0.61.0, there is now a method for that:

```python
        # Testing getting SP id by app ID
        result = self.graphrbac_client.applications.get_service_principals_id_by_app_id(app.app_id)
        assert result.value == sp.object_id
```

**Comment by MMollyy** [comment]
Man, I was very excited because I've walked up against using the app_id vs the obj_id in the past also with powershell.

But even so:
```
sp_role_assignment = auth_client.role_assignments.create(
    '/subscriptions/3240967642345/resourceGroups/rg999',
    uuid.uuid4(),
    {'role_definition_id': 'c86d87cd-74c3-4a35-b76b-7aa1c6992926',
     'principal_id': '5f5b4915-7fcd-4eca-acfe-812e5719217d'}
    )
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "C:\Users\user\bootstrapper\lib\site-packages\azure\mgmt\authorization\v2018_01_01_preview\operations\role_assignments_operations.py", line 327, in create
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: BadRequestFormat
Message: The request was incorrectly formatted.
```
I'm trying it with just the values in there to make sure they're not accidentally incorrect. But still the same error. 
So I tried making a new project and installing all the packages with latest version: same result.

**Comment by lmazuel** [comment]
@yugangw-msft would you know if I'm missing something here?

**Comment by yugangw-msft** [comment]
All I can suggest is to create the instance from a model type of `RoleAssignmentCreateParameters`, this way the correct serialization will happen.

**Comment by MMollyy** [comment]
Okay, I'd like to try that, but from what I can see I am already calling the `RoleAssignmentCreateParameters` model type using the create operation for roleassignments.

Got an example how to approach?

**Comment by MMollyy** [comment]
well I think I got as far as this:
```
role_assignment_parameters = auth_client.role_assignments.models.RoleAssignmentCreateParameters(
    role_definition_id=AZURE_TERRAFORM_ROLE['infra-user'],
    principal_id=created_service_principal.object_id)
sp_role_assignment = auth_client.role_assignments.create(RG.id, uuid.uuid4(), role_assignment_parameters,
                                                         custom_headers=None)
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "C:\Users\Moll\bootstrapper\lib\site-packages\azure\mgmt\authorization\v2018_01_01_preview\operations\role_assignments_operations.py", line 327, in create
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: BadRequestFormat
Message: The request was incorrectly formatted.
role_assignment_parameters
<azure.mgmt.authorization.v2018_01_01_preview.models.role_assignment_create_parameters_py3.RoleAssignmentCreateParameters object at 0x0501EE70>
```

Still the same error message though, and im also not sure this is the correct way to serialize the object..

**Comment by lmazuel** [comment]
Can you activate debug logging to see if we get more information? Your issue is really unexpected :(
Use logging with DEBUG, AND activate HTTP logging:
```python
auth_client.config.enable_http_logger = True
```
You should see your 4xx JSON answer, could you past it here?

**Comment by MMollyy** [comment]
```
import logging

auth_client.config.enable_http_logger = True

try:
    role_assignment_parameters = auth_client.role_assignments.models.RoleAssignmentCreateParameters(
        role_definition_id=AZURE_TERRAFORM_ROLE['infra-user'],
        principal_id=created_service_principal.object_id)
    sp_role_assignment = auth_client.role_assignments.create(RG.id, uuid.uuid4(), role_assignment_parameters,
                                                             custom_headers=None)
except Exception as error:
    logging.debug(error)


auth_client.config.enable_http_logger = True

try:
    role_assignment_parameters = auth_client.role_assignments.models.RoleAssignmentCreateParameters(
        role_definition_id=AZURE_TERRAFORM_ROLE['infra-user'],
        principal_id=created_service_principal.object_id)
    sp_role_assignment = auth_client.role_assignments.create(RG.id, uuid.uuid4(), role_assignment_parameters,
                                                             custom_headers=None)
except Exception as error:
    logging.error(error)
    
ERROR:root:Azure Error: BadRequestFormat
Message: The request was incorrectly formatted.
```
So i'm not sure at this very moment. I'm going to create a new pycharm project, load the full azure packages instead of just the ones for graphrbac, authorization and resource. also I will change the api_version to the one from 2015/2016?? instead of having it default to 2018_01_01
I will try all the things again, including the http log output.
Because I don't see any additional logging on debug or on error level

**Comment by yugangw-msft** [comment]
@MMollyy, I suggest you cross check what CLI does on the payload, use it as reference and then compare with the payload submitted by your code.
Here is what Azure CLI does
```
- request:
    body: '{"properties": {"roleDefinitionId": "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
      "principalId": "03bdb50e-9ad2-49bb-865a-fe94fcae9541"}}'
    headers:
      Accept: [application/json]
      Accept-Encoding: ['gzip, deflate']
      CommandName: [role assignment create]
      Connection: [keep-alive]
      Content-Length: ['233']
      Content-Type: [application/json; charset=utf-8]
      Cookie: [x-ms-gateway-slice=productionb]
      ParameterSetName: [--assignee --role -g]
      User-Agent: [python/3.7.1 (Windows-10-10.0.17763-SP0) msrest/0.6.4 msrest_azure/0.4.34
          azure-mgmt-authorization/0.50.0 Azure-SDK-For-Python AZURECLI/2.0.59]
      accept-language: [en-US]
    method: PUT
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_role_assign000001/providers/Microsoft.Authorization/roleAssignments/88888888-0000-0000-0000-000000000001?api-version=2018-01-01-preview

```

**Comment by MMollyy** [comment]
ah but there we go, I see a very clear difference and I can't believe I didn't actually test that scenario …
You are using the full resource id, if a role definition can be called a resource, but let's for now.
I'm using just the id itself, which is considered the name in the documentation.

I now have it working using the role_definition.id instead of the role_definition.name
Didn't matter what I had changed around it, the actual input was still incorrect as the error keeps pointing out: **ERROR:root:Azure Error: BadRequestFormat
Message: The request was incorrectly formatted.**

For future reference for anyone else:
Incorrect id input format:
'role_definition_id': 'c86d87cd-74c3-4a35-b76b-7aa1c6992926'
correct id input format:
'role_definition_id': '/subscriptions/##################/providers/Microsoft.Authorization/roleDefinitions/6d7abd95-a71b-4940-9c7d-93fa33f41132'

Lesson learned for me 👍 
Thanks for the assistance and teaching!

PS: If I'd like to try and help update that documentation. Should I make a pull request and update the help properties for a class/function, or how would that work?
