### ISSUE TITLE
No documentation for publish_iteration

### ISSUE THREAD

**Issue by MixolydianV** [Azure/azure-sdk-for-python#4668]
With the [new release](https://pypi.org/project/azure-cognitiveservices-vision-customvision/1.0.0/), it appears that we are required to have a published iteration in order to call `CustomVisionPredictionClient.classify_image`. In order to publish, it looks like we have to call `publish_iteration(self, project_id, iteration_id, publish_name, prediction_id, custom_headers, raw, **operation_config)`, but when I check the custom_vision_training_client.py file it only gives "The id of the prediction resource to publish to".

Since [all of the current documentation](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-customvision/azure.cognitiveservices.vision.customvision.prediction.custom_vision_prediction_client.customvisionpredictionclient?view=azure-python#main) is referring to the old methods (0.4.0), I can't seem to find any information on where this `prediction_id` argument should come from. Ideally the docs.microsoft.com documentation should be updated, but otherwise it would be good to find out how/where to find this prediction_id.

**Comment by lmazuel** [comment]
@areddish what do you think ?

**Comment by lmazuel** [comment]
Hi @MixolydianV , the doc should update automatically soon, if not please ping me again in a few days and I will contact the doc team. Thanks!

**Comment by areddish** [comment]
@MixolydianV - yes, I submitted the PR to update the docs this morning and it's going through the publish process. I'd expect them to be updated by tomorrow morning.

In the interim, you can find your prediction id in the custom vision portal project settings page.

**Comment by xiangyan99** [comment]
Solved
