### ISSUE TITLE
Provide Cognitive Service create account Python function

### ISSUE THREAD

**Issue by roalexan** [Azure/azure-sdk-for-python#4669]
I don't see a way how to create a Cognitive Service account programmatically using Python - in my case I want to create a LUIS account. I see how to do it [from the portal](https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-apis-create-account). Other services, such as for [ResourceGroups ](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/operations/deployments_operations.py)or [AzureSearch](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-search/azure/mgmt/search/operations/services_operations.py), provide a 'create_or_update' function. This would be nice to have when automating deployment.

**Comment by roalexan** [comment]
I suppose I could call the resource management REST API from Python, but my request is to have this built into the Python SDK. BTW, for now I'll use an ARM script.

**Comment by lmazuel** [comment]
Hi @roalexan 
The CLI is using this very SDK repo :)
What you want is inside https://pypi.org/project/azure-mgmt-cognitiveservices/
Thanks!

**Comment by roalexan** [comment]
Thanks, but I don't think I expressed myself very clearly. I am familiar with the REST API, CLI, and SDKs, and I'm happy to be corrected, but I don't believe they support the ability to create a LUIS account programmatically. App, intent, entities, etc. yes, but not an account with associated authoring key. I muddied the water when I said I could resort to using the CLI - this (I think) cannot be done using REST, CLI, or SDK.

I think this person did a better job expressing my request - see [Programatic access to LUIS authoring key](https://github.com/Microsoft/botbuilder-tools/issues/550).

**Comment by lmazuel** [comment]
Hi @roalexan 
I confirm this is possible with this package, but I admit there is no documentation on how to do it.

**Comment by roalexan** [comment]
oh? it's possible to create a LUIS account programmatically? I'll have to look at the code.

**Comment by lmazuel** [comment]
@roalexan I didn't try yet, but I see a LUIS option in the package which is a good sign, take my assumption with a grain of salt still since I didn't executed any code :)
This link might be useful as well:
https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/tree/master/samples/language/luis

It's likely that you can create an ARM runtime account, but maybe not a authoring account.

I will try to investigate in more details and give a more concrete example with real code.
Thanks!
