### ISSUE TITLE
Installing azure installs packages with potentially-incompatible licensing

### ISSUE THREAD

**Issue by ttmc** [Azure/azure-sdk-for-python#4671]
The `azure` package (a Python package available from PyPI) has an MIT license.

https://github.com/Azure/azure-sdk-for-python/blob/b678123b1d24d62df826085a7599c5edb6f6a472/LICENSE.txt#L1

If I install the `azure` package using `pip install azure`, then many Python packages get installed, including `certifi` and `chardet`.

## certifi

[certifi](https://pypi.org/project/certifi/) is licensed under a Mozilla Public License 2.0 (MPL-2.0). According to the [MPL 2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/):

> Q8: I want to distribute (outside my organization) executable programs or libraries that I have compiled from someone else's unchanged MPL-licensed source code, either standalone or part of a larger work. What do I have to do?
> 
> You must inform the recipients where they can get the source for the MPLed code in the executable program or library you are distributing (i.e., you must comply with Section 3.2). You may distribute any executables you create under a license of your choosing, as long as that license does not interfere with the recipients' rights to the source under the terms of the MPL.

Therefore, as I interpret it, the `azure` package should inform recipients where they can get the source code of `certifi`. I believe that is:

https://github.com/certifi/python-certifi

## chardet

[chardet](https://pypi.org/project/chardet/) is licensed under an LGPL license.

As such, I don't think the `azure` package can be based on chardet or require it, unless the license of the `azure` package itself is changed to LGPL or something similar to LGPL.

## Notice

I am not a lawyer and this is not legal advice. Please consult someone who is qualified to give licensing advice. Many projects use the`azure` package and they need the licensing to be handled properly.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by ttmc** [comment]
Regarding `chardet` and its LGPL license, I found the same issue discussed in the GitHub repository of the (widely-used) `requests` package (which is licensed Apache 2.0 and also imports `chardet`). See:

https://github.com/kennethreitz/requests/issues/3389

It seems they have come to terms with it. I'm still not a lawyer, I just try to do the right thing.

**Comment by lmazuel** [comment]
Hi @ttmc 
Dependencies are `azure` have been discussed with Microsoft lawyers, and we got their approval. I'm not a lwayer myself, but trusting the people who are :)
I'm closing your issue, since I was told everything is ok. 
Thank you for your question though :)
