### ISSUE TITLE
Shared Access Signatures don't work with Premium Storage Accounts

### ISSUE THREAD

**Issue by pneumee** [Azure/azure-sdk-for-python#468]
I'm getting the following error message when trying to copy a blob between Premium Storage accounts:

```
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>CannotVerifyCopySource</Code><Message>Could not verify the copy source within the specified time.
RequestId:
Time:2015-09-02T00:14:20.1883717Z</Message></Error>
```

Using version 0.11.1 of the SDK. I've verified that the same blob copy logic works with regular Storage Accounts.

**Comment by huguesv** [comment]
Please file issues regarding azure storage to their new repo: https://github.com/Azure/azure-storage-python/issues

The storage service team should have more ideas on what could be causing this.

**Comment by pneumee** [comment]
Will do, thanks.
