### ISSUE TITLE
Install fails on cognitive services

### ISSUE THREAD

**Issue by msraidli** [Azure/azure-sdk-for-python#4707]
When I install the toolkit using the following steps:

```
conda create -n azure python=3.6 anaconda
conda activate azure
pip install azure-cli-core
pip install azure
cd ~
git clone git://github.com/Azure/azure-sdk-for-python.git
cd ~/azure-sdk-for-python
python setup.py install
```

I get the following error:

```
Extracting azure_cognitiveservices_knowledge_qnamaker-0.1.0-py3.6.egg to c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages
error: [Errno 2] No such file or directory: 'c:\\program files (x86)\\microsoft visual studio\\shared\\python36_64\\lib\\site-packages\\azure_cognitiveservices_knowledge_qnamaker-0.1.0-py3.6.egg\\azure\\cognitiveservices\\knowledge\\qnamaker\\models\\__pycache__\\delete_kb_contents_dto_py3.cpython-36.pyc.1697067920024'
```

Did I skip a step?

**Comment by lmazuel** [comment]
It's likely a long path problem, could you activate long path support on your Windows machine?
https://betanews.com/2016/05/29/long-paths-windows-10/

**Comment by msraidli** [comment]
Thanks for your quick answer. 

Group policy blocks my permissions and the recommend path in user in Regedit doesn't begin to come close to existing on my machine. I used another hack here: https://lifehacker.com/windows-10-allows-file-names-longer-than-260-characters-1785201032  which worked.

So it got me past the issue.
