### ISSUE TITLE
How can I modify the VM list of the backend pools of load balancers?

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-sdk-for-python#471]
I have a load balancer configure in Azure (ARM) and I have 2 back end pools: prod, stage. Through the GUI, when I want to promote a staging server to production, I remove it from the stage pool and place it in the prod pool. I'm very confused about how this all works because when I provision the stack, I first provision the load balancer and when I provision the NIC that the VM will attach to, I place that NIC in the backend pool I want. However, when I want to move the VM to another pool, I no longer do that at the NIC level. I have to do that at the load balancer. 

Using the Python SDK, I am able to see which NIC is in the backend pool if I query the LB but there seems to be no way to modify that. I can also query the NIC and see which backend pool it's associated with but again, no way to modify (from what I can tell). This is what I have so far:

    # Create the client
    network_client = azure.mgmt.network.NetworkResourceProviderClient(creds)

    # Get all LBs
    lbs = network_client.load_balancers

    # select LB in question
    lb = lbs.get(group,'cc-lb01')

    # get all pools
    pools = lb.load_balancer.backend_address_pools

    # set variables for pools
    prod = pools[0]
    stage = pools[1]
    
The output of print(dir(stage)) is:

    ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_backend_ip_configurations', '_etag', '_id', '_load_balancing_rules', '_name', '_provisioning_state', 'backend_ip_configurations', 'etag', 'id', 'load_balancing_rules', 'name', 'provisioning_state']

So I thought I was onto something when I saw 'backend_ip_configurations'. When look at my options there (by typing this):

    print(stage.backend_ip_configurations)

It returns an array of objects:

    [<azure.mgmt.network.networkresourceprovider.ResourceId object at 0x03C9C090>]

There is only 1 item in that array so I set that item to a variable:

    beip = stage.backend_ip_configurations[0].id

and when I see what my options are with 'beip', this is where I dead end. 

    /subscriptions/xxx-xxx-xxx/resourceGroups/myresourcegroup/providers/Microsoft.Network/networkInterfaces/app-green04-nic/ipConfigurations/ipconfig1

The output of print(dir(beip)) is:

    ['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

I cannot figure out how to see what NICs are in the backend pool and modify that pool other than through the GUI.

**Comment by huguesv** [comment]
Resource references are currently inconvenient to follow, because there's no get() that allow you to fetch using a reference id. So you need to parse the names of the resources that make up the id.

In this case, you need to parse the resource id to get the names 'myresourcegroup', 'app-green04-nic' and 'ipconfig1'.  With these, you'll be able to access the NIC with `network_client.network_interfaces.get('myresourcegroup, 'app-green04-nic')`.

Looking at LoadBalancerOperations, it looks like you should be able to do a get(), modify the contents of the load_balancer.backend_address_pools[0].backend_ip_configurations by adding/modifying/removing ResourceId objects, and then call create_or_update() with the modified LoadBalancer object.

Obtaining a resource id to create a ResourceId is easy, no need to build the string yourself, you can usually just call a get() method and Azure will populate and return the id for you.  For example, to get the resource id for a NIC configuration:

```
result = network_client.network_interfaces.get('myresourcegroup', 'app-green04-nic')
result.network_interface.ip_configurations[0].name
#ipconfig1
result.network_interface.ip_configurations[0].id
#/subscriptions/xxx-xxx-xxx/resourceGroups/myresourcegroup/providers/Microsoft.Network/networkInterfaces/app-green04-nic/ipConfigurations/ipconfig1
```

You can't index by name on those collections, so you'll need to iterate to find the one you are looking for.

**Comment by cicorias** [comment]
Take a look at this video and GitHub repo that demonstrates handling modifying the Pool membership via REST and Python.

In the end, it's about getting to the proper json that get's sent via updates

https://mix.office.com/watch/f4cvoa3cnfoe

Note in the following the /src path has the Python version

https://github.com/cicorias/AzureLoadbalancedPoolUpdater

**Comment by lmazuel** [comment]
Hi @aarsan, I just wanted to know if you are still having an issue here after @huguesv and @cicorias advice?
Thank you!

**Comment by aarsan** [comment]
You can go ahead and close it. I don't recall what I did but I know I eventually figured out a workaround. Thanks.

**Comment by lmazuel** [comment]
Ok, thank you for your return!
