### ISSUE TITLE
main setup.py should override the install command

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-sdk-for-python#473]
The main setup.py just delegates to the many setup.py for each package in the repo.
We should override the install command so that only install delegates, ie. we don't want the help command to delegate.
Example of overriding a command:
https://github.com/Microsoft/PTVS/blob/master/Python/Product/PyKinect/PyKinect/setup.py

**Comment by lmazuel** [comment]
Actually, this is interesting. For instance, I'm able to build every wheel with this command:
```python
python .\setup.py bdist_wheel -d ../wheelhouse
```
with no need for a build script (which reduce the number of places where I have to write an explicit list of packages to build).
