### ISSUE TITLE
Can someone provide an example of deploying an ARM template?

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-sdk-for-python#478]
I am trying to deploy an existing JSON ARM Template but running into problems. The code I have is:

    result = self.resource_client.deployments.create_or_update(
        resource_group_name="mygroup",
        deployment_name="test_deploy"
    )

The error I get is:
    create_or_update() missing 1 required positional argument: 'parameters'

I don't know how to create this parameters object and don't know what the parameters needed are. I also don't know when/how I pass in my template.

**Comment by huguesv** [comment]
Sorry, we don't have an example for Python but I'll see if I can find one for another language.  They all call the same REST apis, so even a C# example is a good reference.

As far as the 'parameters', the docstring says it's a 'Deployment', see the class here: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/resourcemanagement.py#L845

The only thing that is stored there is a 'properties', which looks like 'DeploymentProperties', defined here: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/resourcemanagement.py#L1672

and that has attributes to specify template information.

**Comment by huguesv** [comment]
This page has some info on the attributes you'll need to set on 'DeploymentProperties':
https://msdn.microsoft.com/en-us/library/azure/dn790564.aspx

**Comment by aarsan** [comment]
This code is right from the tests in this repo:
        def test_deployments(self):
        self.create_resource_group()

        deployment_name = "pytestdeployment"

        deploy_parameter = azure.mgmt.resource.Deployment()
        deploy_parameter.mode = azure.mgmt.resource.DeploymentMode.incremental
        deploy_parameter.parameters = '{"siteName": {"value": "mctest0101"},"hostingPlanName": {"value": "mctest0101"},"siteMode": {"value": "Limited"},"computeMode": {"value": "Shared"},"siteLocation": {"value": "North Europe"},"sku": {"value": "Free"},"workerSize": {"value": "0"}}'

        template_uri = azure.mgmt.resource.TemplateLink()
        template_uri.uri = 'https://testtemplates.blob.core.windows.net/templates/good-website.js'
        deploy_parameter.template_link = template_uri

        result = self.resource_client.deployments.create_or_update(self.group_name, deployment_name, deploy_parameter);

        deployment_list_result = self.resource_client.deployments.list(self.group_name, None)
        deployment_get_result = self.resource_client.deployments.get(self.group_name, deployment_name)

        self.resource_client.resource_groups.delete(self.group_name);

and when I run this, I get the following error:

    azure.common.AzureHttpError: b'{"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: \'Required property \'properties\' not found in JSON. Path \'\', line 1, position 2.\'."}}

I am further than I was before but still can't get it to work. i'm running python 3.4.3

**Comment by aarsan** [comment]
Ok, I did get to this to work but this is what I had to do:

    deployment_name = "from-python-sdk"

    template_link = azure.mgmt.resource.resourcemanagement.ParametersLink(
			uri="https://path.to.templates.json"
		)

    parameters_link = azure.mgmt.resource.resourcemanagement.TemplateLink(
			uri="https://path.to.params.json"
		)

    properties = azure.mgmt.resource.resourcemanagement.DeploymentProperties(
			mode="incremental",
			template_link=template_link,
			parameters_link=parameters_link
		)

    deploy_parameter = azure.mgmt.resource.Deployment()
    deploy_parameter.properties=properties

    result = self.resource_client.deployments.create_or_update(
        resource_group_name=self.group,
        deployment_name=deployment_name,
        parameters=deploy_parameter
    )

**Comment by huguesv** [comment]
Added test and documentation for this. Thanks for the feedback.
