### ISSUE TITLE
Update matrix for livetests - python

### ISSUE THREAD

**Issue by KarishmaGhiya** [Azure/azure-sdk-for-python#4803]
Livetests in python need to be run on more platform (Windows, Linux, MacOS) and python versions (2.7, 3.4, 3.5, 3.6, 3.7) (for both servicebus and eventhub as discussed with Anna)

**Comment by AlexGhiondea** [comment]
This is a dupe of https://github.com/azure/azure-sdk-for-python/issues/4793
