### ISSUE TITLE
Investigate ways of sharing common utility functionality across python packages

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#4818]
Johann brought this up as a result of our Python team's experience with the IOT folks.

The question, boiled down:
How can we share internal code like azure-common
 * **without** publishing a "common" utility package
 * from module to module inter-repo
 * from module to module intra-repo

We don't really want to go with a common utility package, as they can become dumping grounds where no package taking a dependency uses more than a few of the functions..

**Comment by kurtzeborn** [comment]
Once we publish azure-core for track 2 in the next few weeks, we'll have to tackle this for sure.  One possible solution to this is to point all of our python builds at a DevOps feed which will resolve all package requests itself and then "pass through" requests it can't resolve to PyPi.

**Comment by scbedd** [comment]
Packages in our repo are using is leveraging the `_shared` methodology.
