### ISSUE TITLE
Unable to deploy template using inline json

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-sdk-for-python#482]
Hi all, 
There's probably something wrong with my code, but as there's no documentation around, hopefully someone can help me. Im trying to deploy a template using local jsons - i don't want to go the "templatelink" route of publishing content to a storage group first. Here's my code:
```
resource_client = azure.mgmt.resource.ResourceManagementClient(creds)

GROUP_NAME = "arm-python"
REGION = 'westeurope'
result = resource_client.resource_groups.create_or_update(
    GROUP_NAME,
    azure.mgmt.resource.ResourceGroup(
        location=REGION,
    ),
)


template = """{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "location": {
      "type": "string",
      "allowedValues": [
        "East US",
        "West US"
      ],
      "metadata": {
        "description":"The location"
      }
    }
  },
  "resources": [
    {
      "type": "Microsoft.Compute/availabilitySets",
      "name": "availabilitySet1",
      "apiVersion": "2015-05-01-preview",
      "location": "West US",
      "properties": {}
    }
  ]
}
"""

parameters = """
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "location":{
            "value": "West US"
        }
    }
}
"""

properties = azure.mgmt.resource.resourcemanagement.DeploymentProperties(
        mode="incremental",
        template=template,
        parameters=parameters
    )

deploy_parameter = azure.mgmt.resource.Deployment()
deploy_parameter.properties=properties

result = resource_client.deployments.create_or_update(
    resource_group_name="arm-python",
    deployment_name="depname",
     parameters=deploy_parameter
)
```

The credentials part work, because the first call to create the resource group works fine. THe error I'm getting is:
b'{"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: \'Error converting value \\"1.0.0.0\\" to type \'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition\'. Path \'properties.parameters.contentVersion\', line 1, position 520.\'."}}'

The SDK seems unable to correctly parse my json, but the same template/parameter content works fine if using powershell to create the deployment. Any pointers appreciated! (and to maintainers: Please provide samples!)

**Comment by huguesv** [comment]
I was able to get your code working by changing the parameters json.  Apparently, when it's inline, the top level objects aren't needed.
https://msdn.microsoft.com/en-us/library/azure/dn790564.aspx
```
parameters = """
{
    "location":{
        "value": "West US"
    }
}
```

**Comment by trondhindenes** [comment]
Nice, that works perfectly. Thanks!

**Comment by huguesv** [comment]
Added test and documentation for this. Thanks for the feedback.

**Comment by rshirani** [comment]
Hey folks,

I have the same issue using C#. I also tried to do what you recommended in this thread but did not work. Any thoughts?

Here is the full exception:

Error: System.AggregateException: One or more errors occurred. ---> Microsoft.Rest.Azure.CloudException: The request content was invalid and could not be deserialized: 'Error converting value "

}" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Templates.Schema.Template'. Path 'properties.template', line 3, position 23171.'.
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication1.Program.<CreateTemplateDeploymentAsync>d__3.MoveNext() in

**Comment by SattaRavi** [comment]
@huguesv you are a saver, my couple of days of searching ended here with your link to MSDN. (i was trying an inlined template and paramater from the nodejs sdk)

**Comment by arcotek-ltd** [comment]
> Added test and documentation for this. Thanks for the feedback.
@huguesv could you provide a link to said documentation please?

**Comment by lmazuel** [comment]
Hi @arcotek-ltd 
I don't find the documentation, but this unitest might help:
https://github.com/Azure/azure-sdk-for-python/blob/c04531af1ef6d76384c9f3e61eead7ace04fcc03/azure-mgmt/tests/test_mgmt_resource.py#L201-L319

**Comment by abhi1509** [comment]
But isn't this then incompatible with what New-AzureRmResourceGroupDeployment in Powershell?
That expects the full json with outer elements.

**Comment by nakhanha** [comment]
How was this issue resolved. Hitting same issue with C#

**Comment by jlongo62** [comment]
To clarify the workaround:
The parameters file from the portal looks something like this:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "name": {
      "value": "ImagingFunctionsd49b41"
    },
    "location": {
      "value": "eastus"
    }
  }
}
```
To work-around the problem, remove the header elements to make the parameters file look like this:

```
{
    "name": {
      "value": "ImagingFunctionsd49b41"
    },
    "location": {
      "value": "eastus"
    }
}
```

**Comment by pmanikantasai1996** [comment]
Hi Friends,

Getting the same error while deploying the template in deploy if not exists Azure policy action 

 error: '{\"error\":{\"code\":\"InvalidTemplate\",\"message\":\"Deployment template parse failed: 'Error converting value \\\"Standard_LRS\\\" to type 'Microsoft.WindowsAzure.ResourceStack.Common.Core.Definitions.Resources.ResourceSku'. Path ''.'.\"}}'.",
