### ISSUE TITLE
KeyVaultCredential does not reflect changes in www-authenticate header

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-python#4851]
If the customer moves a key vault from one tenant to another, the www-authenticate header changes, but the KeyVaultCredential class does not detect the new value and use the previous forever. The process keeps requesting tokens for the wrong tenant and becomes unable to access that specific key vault again.  This caused an incident that required rebooting of servers in the cloud.

The issue is that http_bearer_challange_cache is global to the process and is never updated, or checked if the cached challenge is out of date.  The proposed fix is when the request fails with 401 we check to see if the returned challenge matches our cached version.  If not we need to update the cache and re-authenticate.

**Comment by Petermarcu** [comment]
Wont fix this unless we have a request to fix it.
