### ISSUE TITLE
Is Destination class in the CaptureDescription class of the event hub support EventHubArchive.AzureDataLake ?

### ISSUE THREAD

**Issue by MyronFanQiu** [Azure/azure-sdk-for-python#4866]
In the Azure Portal, the Capture settings for an event hub can use Data Lake Storage. I wonder, does the python sdk just support Storage Account now?
https://github.com/Azure/azure-sdk-for-python/blob/2f3e214f5c9344d3e0842b1d7435ccd006ceda0b/azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/destination.py#L42-L43

**Comment by lmazuel** [comment]
@v-Ajnava would you know?

**Comment by v-Ajnava** [comment]
@MyronFanQiu , right now it doesn't support  EventHubArchive.AzureDataLake properties.

**Comment by MyronFanQiu** [comment]
@v-Ajnava  @lmazuel  I see. Thanks very much. By the way, is there any schedule or plan to support it?

**Comment by v-Ajnava** [comment]
@ShubhaVijayasarathy can you please update on this.

**Comment by ShubhaVijayasarathy** [comment]
@MyronFanQiu - yes there is a debt and we plan to support this by EOY. By then we might also add the ADLS Gen 2 support as well. Hope this helps.

**Comment by MyronFanQiu** [comment]
@ShubhaVijayasarathy @v-Ajnava Thanks! Wish everything goes fine!
