### ISSUE TITLE
Secret version will always be None after some operations

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#4929]
The base class `SecretAttributes` parses secret IDs (e.g. https://myvault.vault.azure.net/secrets/my-secret/version) and exposes the vault base URL, secret name, and version as properties. However, IDs returned from some operations (e.g. list) lack a version component, causing the `version` property to return `None`.

This could cause confusion and frustration when a user wants to get a value for a listed secret because `get_secret` requires a version, but the list item's `version` would be `None`. We should consider refactoring the models to avoid exposing `version == None`.

**Comment by AlexGhiondea** [comment]
[triage] We decided this was not an issue. Closing.
