### ISSUE TITLE
BlobService class blobs with "question marks" in the path issue

### ISSUE THREAD

**Issue by liormizr** [Azure/azure-sdk-for-python#494]
Hi guys,

We are using Azure storage with one of our clients, and we are using the python sdk.

When we yield over the container_name with list_blobs method we get blobs with "question marks".
After that if we try to get the same blob thru the get_blob_to_file (or get_blob) method,
We get "Not found (The specified blob does not exist.)" exception.

I see that the issue is in the "_update_request_uri_query" method.
You guys expect a query string after "question marks" but you allowing blobs with "question marks" in the path...

For example:
if my path is: "test_path/test name?.txt"
I see that in the request the path is "/<container_name>/test_path/test name"

B.T.W:
I see that in the C# sdk it was fixed
http://stackoverflow.com/questions/12242120/azure-blob-reference-to-file-with-question-mark-in-the-name

please advice,

Thanks,
Lior
li.mizr@gmail.com

**Comment by huguesv** [comment]
Moved issue to the azure storage GitHub repository.
