### ISSUE TITLE
Add support for subscribing to event hub using AMQP

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-sdk-for-python#495]
Receiving events is not possible using the REST API, but we could implement it via `python-qpid-proton`.

https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-python/

**Comment by lmazuel** [comment]
The ServiceBus team told us that the recommended way is Proton for AMQP:
https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-python/
http://www.mikelanzetta.com/2014/11/talking-to-eventhub-with-amqp-1-0/

**Comment by peterkshultz** [comment]
Updated link for the Mike Lanzetta post is right [here](http://www.mikelanzetta.com/talking-to-eventhub-with-amqp-1-0.html).
