### ISSUE TITLE
azure-mgmt-automation client contains useless parameter spec

### ISSUE THREAD

**Issue by yuwzho** [Azure/azure-sdk-for-python#4965]
In the init method of AutomationClient, it requires `count_type1`, which is not consistent with all other mgmt clients and seems it is an unused param.

https://github.com/Azure/azure-sdk-for-python/blob/cd4297981633f17222cdb5498fd5823638183996/azure-mgmt-automation/azure/mgmt/automation/automation_client.py#L202-L203

**Comment by lmazuel** [comment]
Hi @yuwzho 
You're right, thanks for the report!

**Comment by lmazuel** [comment]
Fixed in 0.1.1
