### ISSUE TITLE
Provide distributed tracing pipeline policy and hook

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#4976]
By default, we should make sure that we support [opencensus](https://opencensus.io). 

Requirements:
1) pipeline policy that encode the current trace state into outgoing HTTP requests.
2) All public library methods generate a span if distributed tracing is enabled. No need to add attributes to the span other than the well-known HTTP ones.
3) No hard dependency on open census (other tracing mechanisms are to be supported.

**Comment by lmazuel** [comment]
@johanste please label and put your issue in correct epic :p

**Comment by bryevdv** [comment]
cc @suyogsoti

**Comment by xiangyan99** [comment]
Solved
