### ISSUE TITLE
can't use azure-sdk-for python in china

### ISSUE THREAD

**Issue by shenhaizhilong** [Azure/azure-sdk-for-python#498]
hi team
we can't use azure-sdk-for python in china. after I replaced from windows.net to chinacloudapi.cn still can't use it.

**Comment by huguesv** [comment]
I've listed the various base URLs to use here:
https://github.com/Azure/azure-sdk-for-python/issues/284

**Comment by huguesv** [comment]
Will close this.  If you still have trouble, please reopen and include the relevant code snippets.  Thanks.
