### ISSUE TITLE
Implement sync Certificate client

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#4997]

**Comment by K3UL** [comment]
Why is this closed ? It would be a big plus to be able to do this

**Comment by chlowell** [comment]
We had duplicate issues for this and arbitrarily kept #6322. A certificate client is still on the roadmap; in fact, #6353 has a first implementation.

**Comment by K3UL** [comment]
Then now it does have the information of duplication thank you :)
I actually saw the PR after leaving my comment, great news !
