### ISSUE TITLE
Unable to specify import container for SQL database

### ISSUE THREAD

**Issue by slyons** [Azure/azure-sdk-for-python#5011]
In the REST API / Java SDK the SQL Database part of the SDK supports the ability to create databases using the "RestoreExternalBackup" option, specifying a Storage URL and SAS token to use as the source. This option is not currently supported in this SDK.

[Here](https://github.com/Azure/azure-sdk-for-java/blob/master/sql/resource-manager/v2017_03_01_preview/src/main/java/com/microsoft/azure/management/sql/v2017_03_01_preview/ManagedDatabaseUpdate.java#L84) is where it's implemented in the Java SDK.

**Comment by lmazuel** [comment]
Hi @slyons 
This is actually available:
https://github.com/Azure/azure-sdk-for-python/blob/2a1223d5b3202c9b710f307989f6eb06dd2b39b4/azure-mgmt-sql/azure/mgmt/sql/models/managed_database_update.py#L113

It has been added with azure-mgmt-sql 0.9.1 
Thanks!
