### ISSUE TITLE
[autorest] test_http fails

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#5036]
if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
>           raise models.ErrorException(response, self._deserialize)
E           httpinfrastructure.models._models_py3.ErrorException: Operation returned an invalid status code 'Request Timeout'

Expected\AcceptanceTests\Http\httpinfrastructure\aio\operations_async\_http_retry_operations_async.py:65: ErrorException

**Comment by xiangyan99** [comment]
Maybe a dup of #5034. But keep it open for now.

**Comment by mayurid** [comment]
[https://github.com/Azure/azure-sdk-for-python/issues/5124](url)

**Comment by xiangyan99** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-python/commit/c0d8339d198f7a0987ea6136dc3b0e266b946d6b
