### ISSUE TITLE
Need sample code for Storage Lifecycle Management

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#5047]
I saw code for Storage Lifecycle Management has been committed.

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/management_policies_operations.py

https://github.com/Azure/azure-sdk-for-python/tree/master/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models

Some sample code for managing lifecycle policies would be much helpful. Analyzing how to build the policy and call the methods from source code is very time consuming and not very practicable for common users.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by shravanchaudhary** [comment]
Yes, it's possible. Refer these two, it was hard finding out the sample code.

Rules reference: https://docs.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview?tabs=azure-portal

Python sample code reference: https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/storage/manage_management_policy.py

**Comment by jiasli** [comment]
After working on Azure CLI project for over 2 years, I still find **using SDKs to build complex object** difficult. 

Per @shravanchaudhary's reply, 

https://github.com/Azure-Samples/azure-samples-python-management/blob/ff4b08c3f99aba5e907ea1a1bfe7ce5766fd3183/samples/storage/manage_management_policy.py#L39-L45

```py
    storage_client.storage_accounts.begin_create(
        GROUP_NAME,
        STORAGE_ACCOUNT,
        {
          "sku": {
            "name": "Standard_GRS"
          },
```

SDK does support **passing a JSON as `parameters` directly**. 

**Is this called out some where in the doc?** At least, the doc string only talks about `azure.mgmt.storage.v2021_06_01.models.StorageAccountCreateParameters` as the type, not JSON string.

https://github.com/Azure/azure-sdk-for-python/blob/fd80cb7a31a15275b2a5008d68f91dbe35493543/sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2021_06_01/operations/_storage_accounts_operations.py#L187-L188

```py
        :param parameters: The parameters to provide for the created account.
        :type parameters: ~azure.mgmt.storage.v2021_06_01.models.StorageAccountCreateParameters
```
