### ISSUE TITLE
Release Azure.Identity Library Preview

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#5048]
Goal:

Release the Azure.Identity library
Integrate this library in the other client libraries.

- [x] azure-core
  - [x] TokenCredential ABC
  - [x] BearerTokenAuthenticationPolicy
- [x] azure-identity
  - [x] AzureCredential
  - [x] ClientSecretCredential
  - [x] ClientCertificateCredential
  - [x] ManagedIdentityCredential
  - [ ] ~TokenCredentialProvider~
  - [ ] ~EnvironmentCredentialProvider~
  - [ ] ~MSICredentialProvider~

**Comment by joshfree** [comment]
Closing Preview 1 (July Preview) Epic
