### ISSUE TITLE
[Error] Quickstart: Analyze text content for objectionable material in Python

### ISSUE THREAD

**Issue by EdgardoValdez** [Azure/azure-sdk-for-python#5049]
An Error occurs while executing the Quickstart: Analyze text content for objectionable material in Python at: https://docs.microsoft.com/en-us/azure/cognitive-services/content-moderator/text-moderation-quickstart-python 
also at: 
https://github.com/Azure-Samples/cognitive-services-content-moderator-samples/blob/master/documentation-samples/python/text-moderation-quickstart-python.py

Sample Error:

(cmtextpy) C:\Projects\cmtextpy>cmtextpy.py
Traceback (most recent call last):
  File "C:\Projects\cmtextpy\cmtextpy.py", line 35, in <module>
    classify=True
  File "C:\Projects\cmtextpy\lib\site-packages\azure\cognitiveservices\vision\contentmoderator\operations\text_moderation_operations.py", line 106, in screen_text
    request = self._client.post(url, query_parameters, header_parameters, body_content)
  File "C:\Projects\cmtextpy\lib\site-packages\msrest\service_client.py", line 193, in post
    request = self._request('POST', url, params, headers, content, form_content)
  File "C:\Projects\cmtextpy\lib\site-packages\msrest\service_client.py", line 108, in _request
    request = ClientRequest(method, self.format_url(url))
  File "C:\Projects\cmtextpy\lib\site-packages\msrest\service_client.py", line 155, in format_url
    base = self.config.base_url.format(**kwargs).rstrip('/')
KeyError: 'Endpoint'

Error only occurs with latest version: 1.0.0 (2019-01-02)

It works with previous version: 0.1.0 (2018-02-06)

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @lmazuel

**Comment by lmazuel** [comment]
@PatrickFarley your thoughts?

**Comment by PatrickFarley** [comment]
The issue here was that the quickstart uses an older version of the SDK, and there has been a breaking change since then.

@EdgardoValdez How do I uninstall the old version so I can get the latest version?

**Comment by EdgardoValdez** [comment]
I would try using pip uninstall
azure-cognitiveservices-vision-contentmoderator==0.1.0 and then do pip
install azure-cognitiveservices-vision-contentmoderator
