### ISSUE TITLE
[azure-core] Rationalize session management

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#5124]
The lifetime and share:ability of sessions is unclear in the current azure core implementation. This needs to be rationalized.

[ ] Create and close session implicitly if one is not provided. We should not inherit the backcompat implementation from msrest where sessions were opt-in.
[ ] Design how a session can be passed in to a client without the client taking ownership of the session (take_ownership parameter w. default value==True)
[ ] Normalize lifetime for a client. Clients should, in addition to being a context manager, have an explicit `close(self)` method.
[ ] Document how to share the "native" session for the given transport among all clients in my application (including non-azure libraries)

**Comment by xiangyan99** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-python/commit/c0d8339d198f7a0987ea6136dc3b0e266b946d6b
