### ISSUE TITLE
[Azure.Core] Implement proxy support

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#5125]
Configuration:
- [ ]  Shared for all clients in the process
- [x]  Per-client 

Authentication:
- [x]  No authentication
- [x]  Basic authentication
- [ ]  Digest authentication

Estimate: 2 days

Now we can catch the error of 
- [x] Proxy server is not reachable
- [x] Basic authentication fails
- [ ] Digest authentication fails

**Comment by xiangyan99** [comment]
Added #5267 & #5268 . Close this one.
