### ISSUE TITLE
Optimize Sphinx Docs Generation

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5147]
Right now, it takes a grand total of about 1 hour 15 minutes to completely generate sphinx docs. Need to do what we can to optimize.

Possibilities:
* `collapse_navigation`, update traversal depth
* `sphinx-build -j <N>`
    * My limited experience, this didn't help much.
* Hold onto `doctrees` so as to not have to rebuild _everything_  on every run.

**Comment by bryevdv** [comment]
> Hold onto doctrees so as to not have to rebuild everything on every run.

I will be very curious to see if this kind of approach is feasible.

**Comment by scbedd** [comment]
We generate individually now. Closing.
