### ISSUE TITLE
No documentation on how to run/create tests

### ISSUE THREAD

**Issue by bear454** [Azure/azure-sdk-for-python#517]
From https://github.com/Azure/azure-sdk-for-python/pull/501#issuecomment-161407088 :
> We have a new developer working on the SDK starting next week that will go through this, and we'll make sure that one of the first tasks is to produce a doc that explains how to set AAD for testing.

As I'm adding new tests, from Linux, I'd like to see this happen soon ;-)

**Comment by lmazuel** [comment]
Hi,

I'm the quoted new dev, and yes it's one of my first tasks (note the use of "one of the first tasks", it was not the only first task :-) )
I hope to be able to work on this soon. In the meantime, please feel free to write here your questions. I will post here a direct the documentation link asap.

**Comment by schaefi** [comment]
Hi we are happy to have you on board, especially with the recordings for new methods in the SDK a documented working solution from Linux would be really great. So far I wasn't able to manage token based authentication without the need of the nodejs azure utility. In the end I still can't get the authentication to work which is for sure just me being too stupid :smile: 

This would also help us to support this auth method in azurectl in the future. At the moment we use
the publish settings file method which works well but is considered as legacy method.

That having said if you can share any plans about the possible EOL for publish settings based authentication would help us a lot

Thanks

**Comment by bear454** [comment]
I found https://msdn.microsoft.com/en-us/library/azure/ee460782.aspx#bk_cert , but it seems to no longer be valid, as "Windows Azure Service Management API" isn't on the list anymore...

I was able to get a token for ARM by following https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/ , but that doesn't help with ASM ;-)

**Comment by lmazuel** [comment]
I was finally able to get a valid token from a AAD user/password, working with ASM....
I'm writing that tomorrow here:
https://github.com/Azure/azure-sdk-for-python/wiki/Contributing-to-the-tests

**Comment by bear454** [comment]
YAY :+1: :fireworks: :tada:

**Comment by lmazuel** [comment]
Hi @bear454 

I updated the link with useful information about login. Please tell me if you are able to get a token with AAD for ASM.

Thank you!

**Comment by bear454** [comment]
Got it, and added a recording to https://github.com/Azure/azure-sdk-for-python/pull/519 (which is now passing :D ) ... Close at your discression

**Comment by lmazuel** [comment]
Awesome! :+1:
I close this bug, I assume that the doc is clear and useful if you get the record :). Feel free to re-open if you want more details about something, or open a more specific bug.
Thank you!
