### ISSUE TITLE
What the minimum version need of Service bus Python library which support the property of CorrelationId? 

### ISSUE THREAD

**Issue by wec2018** [Azure/azure-sdk-for-python#5171]
We didn’t see **correlation id** in 'message' document https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.message?view=azure-python. 
We would like to consult SDK team whether this feature realized in latest SDK. 
Thank you!!! 

- [ ] What the minimum version need of Service bus Python library which support the property of CorrelationId?

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by JackyCloud** [comment]
@wec2018 Thanks We Ling, I'm Jacky Guo(jacky.guo@clobotics.com), and this is my git hub account, I will follow this issue, and keep look forward which the version could to support. Thanks

**Comment by wec2018** [comment]
Hi Scott, 

Thank you for your reply! 
Is there any team can help for this issue ? :)
Appreciate your help.

Best Regards,
Weiling

**Comment by lmazuel** [comment]
@annatisch ?

**Comment by wec2018** [comment]
Hello Laurent, 

Thanks! Could you help on this ?

**Comment by wec2018** [comment]
Hello @annatisch 

Could you please help on this ? 
Thank you

**Comment by annatisch** [comment]
Hi @wec2018 
Sorry for the delay, we haven't exposed correlation ID directly in the service bus Message object, however you can access it via the Message.properties attribute:
```python
sb_message = azure.servicebus.Message("some data")
sb_message.properties.correlation_id = "correlationID"
```

**Comment by wec2018** [comment]
@annatisch 
Thank you for your reply! 

What the minimum **version** need of Service bus Python library which support the Message.properties attribute?

**Comment by annatisch** [comment]
Thanks @wec2018 - that would be the current version - 0.50.0

**Comment by wec2018** [comment]
Thank you for your help !! @annatisch

**Comment by JackyCloud** [comment]
@wec2018 @annatisch Thanks all for help, I will try these days

**Comment by dragonsappire** [comment]
I used the following code(0.50.0):
from azure.servicebus.control_client import ServiceBusService
from azure.servicebus.common.message import Message
bus_service = ServiceBusService(
                host_base=host_base,
                service_namespace=service_namespace,
                shared_access_key_name=shared_access_key_name,
                shared_access_key_value=shared_access_key_value)

message = Message("sb")
message.properties.correlation_id = 2
bus_service.send_topic_message(topic, message)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/.local/lib/python2.7/site-packages/azure/servicebus/control_client/servicebusservice.py", line 663, in send_topic_message
    request.headers = message.add_headers(request)
AttributeError: 'Message' object has no attribute 'add_headers'

After commenting this add_headers and resending the message, I checked the message in service bus, the correlation_id field was not set. 

Any ideas?

**Comment by wec2018** [comment]
Hi @annatisch 
Could you please help on this new update from the customer ? 
Thank you!

**Comment by wec2018** [comment]
Hi @annatisch
Could you please help on this new update from the customer ?
Thank you!

**Comment by wec2018** [comment]
Hi @annatisch
Good day to you! Could you please help on this new update from the customer ?
Thank you!

**Comment by wec2018** [comment]
Hi @lmazuel 

It seems that @annatisch is busy recently.
Coudl you please find other engineer to help us? 

appreciate your help!!

**Comment by annatisch** [comment]
Hi @wec2018,

The code you're using above is currently combining the old API (under the `control_client` namespace) and the new API.
If you wish to use the old API, you will need to import the Message object from the same namespace.
The old Message object supports correlation ID via providing broker properties:
```python
from azure.servicebus.control_client import ServiceBusService
from azure.servicebus.control_client import Message
bus_service = ServiceBusService(
    host_base=host_base,
    service_namespace=service_namespace,
    shared_access_key_name=shared_access_key_name,
    shared_access_key_value=shared_access_key_value)

message = Message(body="sb", broker_properties={'CorrelationId': 'my_id_value'})
bus_service.send_topic_message(topic, message)
```

If you wish to use the new AMQP-based API, then the code will look more like:
```python
from azure.servicebus import ServiceBusClient, Message

sb_client = ServiceBusClient(...)
topic_client = sb_client.get_topic("MyTopic")
with topic_client.get_sender() as sender:
    message = Message("sb")
    message.properties.correlation_id = 2
    sender.send(message)
```

**Comment by wec2018** [comment]
Hi @annatisch, 

**Could you please help to check the customer's reply , appreciate for your help.**

I have tested : 

from azure.servicebus import ServiceBusClient, Message
 
from azure.servicebus import ServiceBusClient, Message
 
sb_client = ServiceBusClient(...)
topic_client = sb_client.get_topic("MyTopic")
with topic_client.get_sender() as sender:
    message = Message("sb")
    message.properties.correlation_id = 2 
    #message.properties.correlation_id = "2" was also tested
    sender.send(message)
with azure.servicebus==0.50 python2.7.14,  it did not work

then, i tested another codes you mentioned before

from azure.servicebus import ServiceBusService
from azure.servicebus import Message
bus_service = ServiceBusService(
    host_base=host_base,
    service_namespace=service_namespace,
    shared_access_key_name=shared_access_key_name,
    shared_access_key_value=shared_access_key_value)
 
message = Message(body="sb", broker_properties={'CorrelationId': '2'})
bus_service.send_topic_message(topic, message)
with azure.servicebus==0.21.1 python2.7.14,  it still did not work. I did not find "azure.servicebus.control_client".

Yulu
2019-07-17

**Comment by annatisch** [comment]
I believe this issue is now resolved - please let me know if I need to reopen.
