### ISSUE TITLE
Why `models = models`?

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#5172]
e.g.: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-consumption/azure/mgmt/consumption/operations/usage_details_operations.py#L28

This results in documentation like https://docs.microsoft.com/en-us/python/api/azure-mgmt-consumption/azure.mgmt.consumption.operations.usagedetailsoperations?view=azure-python#models

If there's no good reason for the extra (totally unused?) attribute, remove it. If there _is_ a good reason (and at this point, you may consider backwards compatibility to be a good reason), explaining it with another `:ivar:` field should override that doc section.

**Comment by kurtzeborn** [comment]
@praries880 and I are not sure if this is a model issue or a generator issue.  @lmazuel can you take a look.

**Comment by lmazuel** [comment]
That's not an issue, that's a feature :)
https://github.com/Azure/azure-sdk-for-python/wiki/Direct-access-to-%22models%22-is-deprecated

@zooba , I created an Autorest issue and closing this. Thanks!

**Comment by zooba** [comment]
@lmazuel Should the operations implementations be using `self.models` as well then? At least in the couple I looked at they weren't

**Comment by lmazuel** [comment]
`models = models` means that `from .. import models` == `self.models`, so that's not necessary :)
