### ISSUE TITLE
Access denied- When Trying to create a new project

### ISSUE THREAD

**Issue by Yohzel** [Azure/azure-sdk-for-python#5185]
I was trying to create a new project and upload my images to custom visions. I followed all the steps from the documentation and grabbed the correct keys but I keep getting this error and can not get it to work.
Creating project...
Traceback (most recent call last):
  File "C:/Users/x/Downloads/sample.py", line 10, in <module>
    project = trainer.create_project("My New Project")
  File "C:\Users\x\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cognitiveservices\vision\customvision\training\custom_vision_training_client.py", line 1748, in create_project
    raise models.CustomVisionErrorException(self._deserialize, response)
azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionErrorException: Operation returned an invalid status code 'Access Denied'
>>>

**Comment by lmazuel** [comment]
@areddish what do you think?

**Comment by ericjiang18** [comment]
needed the same help :(
Mine is like: 

File "/Users/broccoli/Desktop/bus_stop_sign_detection-master/code/env/lib/python3.7/site-packages/azure/cognitiveservices/vision/customvision/training/custom_vision_training_client.py", line 2749, in create_tag
raise models.CustomVisionErrorException(self._deserialize, response)
azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionErrorException: Name not unique: busStop, Project: <<NOT SHOWN>>

**Comment by areddish** [comment]
@yohzel - If you are sure the training key is correct, please check the endpoint as well. The example specifies SouthCentral US region of Azure but if your keys are for a resource in a different region then you will need to change the endpoint to that region

@ericjiang18 The error message you are getting is saying "Name not unique: busStop" so it seems you are trying to create a project with a name that already exists. You'll need to use a different name or delete the busStop project if you want to recreate it.

**Comment by ericjiang18** [comment]
> @Yohzel - If you are sure the training key is correct, please check the endpoint as well. The example specifies SouthCentral US region of Azure but if your keys are for a resource in a different region then you will need to change the endpoint to that region
> 
> @ericjiang18 The error message you are getting is saying "Name not unique: busStop" so it seems you are trying to create a project with a name that already exists. You'll need to use a different name or delete the busStop project if you want to recreate it.

Ha! I changed the name and it work fine! Thanks for the quick response!
