### ISSUE TITLE
Test matrix should support additional installation options during test setup

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5189]
Best way to describe this is to speak in the context of `azure-core`. Right now, `azure-core` has an `extras_require` [option](https://github.com/Azure/azure-sdk-for-python/blob/azure-core/azure-core/setup.py#L87) for async support.

With the methodology of our current test harness, we don't ever cover the situation where someone doesn't choose to install the extras. So for `azure-core`, this means that we don't cover testing the package with async _disabled_.

Essentially, we need to be able to add an extras requirement pivot to our test matrix.

**Comment by scbedd** [comment]
@lmazuel re-introduced this issue today. For this instance, instead of an `extras` install, we need to test a package with and without a `tracing` package installed. Both should test correctly. 

I'm thinking we extend our test matrix to pass additional `tox` environments outside of the base.

**Comment by xiangyan99** [comment]
It is already done, right?

**Comment by scbedd** [comment]
No. This is not done.

**Comment by scbedd** [comment]
Superceded by issue #23146 that has all the requirements in a more organized fashion. Closing.
