### ISSUE TITLE
Can't access disconnected regions with ASM

### ISSUE THREAD

**Issue by bear454** [Azure/azure-sdk-for-python#522]
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicemanagement-legacy/azure/servicemanagement/constants.py#L27 defines one specific hostname for API access. This effectively blocks use of the SDK for disconnected regions with their own API endpoints, like China East & China North.

The publishsettings file includes a management endpoint reference ( /PublishData/PublishProfile/Subscription/ServiceManagementUrl ), that could be used instead (like the nodejs tools); or a general mapping could be made of Azure regions to endpoints, e.g. `'West US' => 'management.core.windows.net', 'China North' => 'management.core.chinacloudapi.cn'`.

As it stands though, I don't see any possible way to access disconnected regions.

**Comment by huguesv** [comment]
You should be able to override that by passing a different value for the `host` parameter when you instantiate your service class:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementservice.py#L67

**Comment by bear454** [comment]
Are you suggesting that _every app_ that consumes this SDK and supports disconnected regions should provide a method of overriding the SDK?

**Comment by lmazuel** [comment]
Hi @bear454 !

@huguesv was just answered to your sentence:
> I don't see any possible way to access disconnected regions

This is possible, since you can specify the host in the \_\_init\_\_ method :)

Could you be more specific and describe what you expected?
Thank you!

**Comment by bear454** [comment]
I will move forward with an override in [azurectl](https://github.com/suse/azurectl), if this project chooses not to natively support disconnected regions, but what I expected is for this project to maintain parity with azure SDKs for other languages/environments:

* https://github.com/Azure/azure-xplat-cli/blob/896b1bae02e56c5a732358b665ebf3bab2f9d7b7/lib/util/profile/publishSettings.js#L70
* https://github.com/Azure/azure-sdk-for-go/blob/master/management/publishSettings.go#L70
* https://github.com/Azure/azure-xplat-cli#azure-cli-with-china-cloud

**Comment by lmazuel** [comment]
We had already thought about a way to create a ASM client instance directly from the publish profile. We have an issue with `requests`, which do not handle in-memory certificate currently (your Go link shows clearly that they use in-memory certificate)
We chose that it's a too serious security issue to write the certificate in a temp file automatically. But the code to extract it is available:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicemanagement-legacy/azure/servicemanagement/publishsettings.py

Knowing that, tell me what could help you or submit a PR expanding this to something useful for you.

**Comment by bear454** [comment]
Of course! It's no problem to contribute a pull request; I just wanted to establish the issue first. ;-)

**Comment by bear454** [comment]
We've elected to handle this locally in the app, and explicitly send an endpoint to the SDK.
