### ISSUE TITLE
Build config standardization for Cosmos

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#5220]
The current pipeline YAML files should be brought in to conform with existing templates. This should happen after #5214 and ideally after ES changes to isolate pipelines per-service is complete.

**Comment by bryevdv** [comment]
@weshaggard can you point me at a file you would like to me to emulate. Alot has changed on the ES side I want to make sure I follow the example you intend

**Comment by weshaggard** [comment]
We haven't done the work for python repo yet. Part of it is at https://github.com/Azure/azure-sdk-for-python/pull/5426 but we haven't yet done the similar test changes. I suspect we will do that for you once we tackle this repo.

**Comment by mitchdenny** [comment]
What we could do is rename the ```python - cosmos - ci``` definition since it is in conflict with the standard approach we are taking (but we don't loose the pipeline just yet). That would allow me to merge my changes in and get the new pipelines up and running, then we can look at how to integrate what the current definition does.

**Comment by weshaggard** [comment]
My intention in naming it `python - cosmos - ci` was that we would fold in those steps into the ci leg cosmos. However if you want to pull that step in later then please do feel free to renaming to get the tracks laid down and then pull in this.

**Comment by mitchdenny** [comment]
Yeah - I think that makes the most sense. I'll rename the pipeline.

**Comment by bryevdv** [comment]
I'm fine with whatever you guys need do just please keep me in the loop :)

**Comment by bryevdv** [comment]
@weshaggard any updates on what is needed here? (Or is this really a task for someone on the ES side of things?)

**Comment by weshaggard** [comment]
I've assigned to @danieljurek who will be working on the standardizing of the pipelines.
