### ISSUE TITLE
[Face] Issue with SnapshotOperations.take and .apply

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-python#5223]
[SnapshotOperations.take](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/snapshot_operations.py#L129) and [SnapshotOperations.apply](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/snapshot_operations.py#L458) return None unless you pass raw=True.

As a result I can see no way to get the operation ID to verify the success of the take/apply operation unless I:
1. Pass raw=True to take/apply.
2. Get the value of the Operation-Location HTTP header returned by the service and parse it for the operation ID. E.g.:
    operation_id = take_snapshot_result.response.headers['Operation-Location'].replace('/operations/', '')

It would be easier for users if take/apply, by default, returned an object with an operation_id property.

Please let me know if I can provide any additional information.
Thank you!

**Comment by lmazuel** [comment]
Hi @v-jaswel 
You're 100% right, this SDK would need API clarification here:
@binderjoe

**Comment by v-jaswel** [comment]
Relevant locations are now
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/_snapshot_operations.py#L131
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/_snapshot_operations.py#L458

**Comment by wiazur** [comment]
Hi @Imazuel, have there been any updates with this issue? Thanks much.

**Comment by lmazuel** [comment]
Hi @wiazur we are redesigning CS SDK right now (see Text Analytics https://github.com/Azure/azure-sdk-for-python/pull/8568 for instance). We didn't address Face API yet, but it will eventually be on the list.
FYI @mayurid @kristapratico

**Comment by wiazur** [comment]
That sounds great, @Imazuel, thanks for the update!
