### ISSUE TITLE
[Face] Issue with SnapshotOperations.get_operation_status

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-python#5224]
[SnapshotOperations.get_operation_status](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/snapshot_operations.py#L511) deserializes the response from the server into an OperationStatus instance, but not in the way one expects from looking at the definition of [OperationStatus](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/operation_status.py). This is because the JSON object attribute names in the server response do not match the attribute map used to deserialize the response into an OperationStatus.

The JSON object in a typical server response to GET /operations looks like this:

```
{
  "CreatedTime": "2019-05-09T16:12:11.5891562Z",
  "LastActionTime": "2019-05-09T16:12:15.1138077Z",
  "Message": "Failed to retrieve the source object. This failure can be caused by deleting source object or training source object during snapshot taking.",
  "ResourceLocation": null,
  "Status": "failed"
}
```

However, the attribute map for the OperationStatus object looks like [this](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/operation_status.py#L59):

```
_attribute_map = {
    'status': {'key': 'status', 'type': 'OperationStatusType'},
    'created_time': {'key': 'createdTime', 'type': 'iso-8601'},
    'last_action_time': {'key': 'lastActionTime', 'type': 'iso-8601'},
    'resource_location': {'key': 'resourceLocation', 'type': 'str'},
    'message': {'key': 'message', 'type': 'str'},
}
```

(The attribute map is used by the [_deserialize](https://github.com/Azure/msrest-for-python/blob/master/msrest/serialization.py#L1230) method of the MSRest library.

The capitalization in the 'key' values in the attribute map is different from that of the JSON object attribute names. As a result, the JSON object attributes all end up in OperationStatus.additional_properties, which is an inherited property from the msrest.serialization.Model class. So the deserialized OperationStatus object looks like this:

```
{
    'additional_properties': {
        'Status': 'succeeded',
        'LastActionTime': '2019-05-07T18:42:58.0682132Z',
        'Message': None,
        'ResourceLocation': '/snapshots/92d24aff-498c-4b4a-9671-f7f0a721546c',
        'CreatedTime': '2019-05-07T18:42:54.9835478Z'
    },
    'status': None,
    'created_time': None,
    'last_action_time': None,
    'resource_location': None,
    'message': None
}
```

If a user looks at the definition of OperationStatus, they'll expect to see data in the fields 'status', 'resource_location', etc., but it won't be there. They won't know about the additional_properties field unless they dump the OperationStatus object to output.

In my local copy of operation_status_py3.py, I changed the OperationStatus attribute map to:

```
_attribute_map = {
    'status': {'key': 'Status', 'type': 'OperationStatusType'},
    'created_time': {'key': 'CreatedTime', 'type': 'iso-8601'},
    'last_action_time': {'key': 'LastActionTime', 'type': 'iso-8601'},
    'resource_location': {'key': 'ResourceLocation', 'type': 'str'},
    'message': {'key': 'Message', 'type': 'str'},
}
```

That caused the JSON object in the server response to be deserialized to the OperationStatus object as expected:

```
{
    'additional_properties': {},
    'status': <OperationStatusType.succeeded: 'succeeded'>,
    'created_time': datetime.datetime(2019, 5, 10, 17, 19, 32, 505582, tzinfo=<isodate.tzinfo.Utc object at 0x000002A70AED0A58>),
    'last_action_time': datetime.datetime(2019, 5, 10, 17, 19, 33, 749810, tzinfo=<isodate.tzinfo.Utc object at 0x000002A70AED0A58>),
    'resource_location': '/persongroup/57b294e9-5341-4c12-a011-c62f0637d693',
    'message': None
}
```

Please let me know if I can provide any additional information.
Thank you!

**Comment by lmazuel** [comment]
Hi @v-jaswel 
You're right, that's a bug in the Swagger description used to create this SDK. I created an issue for this:
https://github.com/Azure/azure-rest-api-specs/issues/5953

**Comment by v-jaswel** [comment]
Looks like this is resolved.
I created a snapshot operation (c6a58efd-c303-41aa-875d-72172eda8a45) and got its status in the test console (https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/operationstatus-get).
Response:
```
{
  "createdTime": "2019-07-08T16:46:57.0410474Z",
  "lastActionTime": "2019-07-08T16:46:57.9998871Z",
  "message": null,
  "resourceLocation": "/snapshots/953af728-97aa-4e79-95c8-90a3bcae8716",
  "status": "succeeded"
}
```
This matches the casing in https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/_models_py3.py#L1165
```
class OperationStatus(Model):
# ...
    _attribute_map = {
        'status': {'key': 'status', 'type': 'OperationStatusType'},
        'created_time': {'key': 'createdTime', 'type': 'iso-8601'},
        'last_action_time': {'key': 'lastActionTime', 'type': 'iso-8601'},
        'resource_location': {'key': 'resourceLocation', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
}
```
The key fields in the attribute map match the casing in the server response.
