### ISSUE TITLE
France South and Australia Central regions not usable through API?

### ISSUE THREAD

**Issue by wandhydrant** [Azure/azure-sdk-for-python#5242]
On the Azure console, I can see prices for all regions, including Germany Central, Germany Northeast, France South, Australia Central and Australia Central 2.

I understand that the German regions are special ( https://github.com/Azure/azure-sdk-for-python/issues/814 ) but what about the other three? The error message seems to indicate that France South and the two Australian Central regions are not available, yet other regions in France and Australia are:

```
Message: No registered resource provider found for location 'francesouth' and API version '2019-03-01' for type 'locations/vmSizes'. The supported 
api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01,
2018-10-01, 2019-03-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope,
eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral,
canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, southafricanorth'.
```
Are there new API versions coming up supporting these?

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @lmazuel

**Comment by lmazuel** [comment]
Hi @wandhydrant 
It's possible that this API version is not yet rolled out on these three regions. If you don't need the latest feature, you can configure your API version profile to something deployed for sure:
https://github.com/Azure-Samples/Hybrid-Compute-Python-Manage-VM

That being said, I am not aware of all deployments of all API versions worldwide, and this page seems to think it should be available:
https://azure.microsoft.com/status/

I would open a support ticket on the portal, there is nothing I can do on the Python side :(
Thank you

**Comment by ChethanChandra** [comment]
I have been waiting for last couple of months for this error message to go away, hoping the new API will be available. It appears newer regions have this issue.

This is the error:
CloudError: Azure Error: NoRegisteredProviderFound
Message: No registered resource provider found for location 'australiacentral' and API version '2018-06-01' for type 'locations/vmSizes'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, southafricanorth'.

Its not easy for me to understand what is missing:
1. **No** registered resource provider found for location 'australiacentral' and API version **'2018-06-01'**.

2 .**The supported** api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, **2018-06-01**, 2018-10-01, 2019-03-01'.

Any idea when this will be fixed? I do not want to manage multiple API profiles.
