### ISSUE TITLE
Filtering metrics from Microsoft Insights components

### ISSUE THREAD

**Issue by bulkware** [Azure/azure-sdk-for-python#5243]
I am trying to filter metrics under Microsoft Insights components. I'm using this example to filter metrics:
https://github.com/Azure/azure-sdk-for-python/blob/master/doc/sample_azure-monitor.rst#Metrics

Using this example, I get an error:
> azure.mgmt.monitor.models.error_response.ErrorResponseException: only supports conditions of the form '<name> eq <value>' or '<name> ne <value>' : name.value eq 'Percentage CPU' and aggregationType eq 'Total' and startTime eq 2019-05-14 and endTime eq 2019-05-15 and timeGrain eq duration'PT1H'

So I fiddled around that filter and came up with the following:

```
filter = " and ".join([
    "name.value eq 'Percentage CPU'",
    "aggregationType eq 'Total'",
    "startTime eq '{}'".format(yesterday),
    "endTime eq '{}'".format(today),
    "timeGrain eq 'PT1H'"
])
```

Using this I get an error "TypeError: 'Response' object is not iterable". So I printed out the response object and changed the part where the metrics are printed:

```
for item in metrics_data.value:
    # azure.mgmt.monitor.models.Metric
    print("{}, {} ({})".format(item.name.value, item.name.localized_value, item.unit.name))
    print item
    for timeserie in item.timeseries:
        print("timeserie: {}".format(timeserie))
        for data in timeserie.data:
            # azure.mgmt.monitor.models.MetricData
            print("{}: {}".format(data.time_stamp, data.total))
```

That part was taken from:
https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring?view=azure-python

I kept changing the filter items, "name.value" to things I found from:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftinsightscomponents

I changed the aggregationType, startTime, endTime and timeGrain to various things. The results I get in the response object are always:

```
{
  'cost': 0.0,
  'resourceregion': 'westeurope',
  'timespan': '2019-05-15T11:12:28Z/2019-05-15T12:12:28Z',
  'interval': 'PT1M',
  'namespace': 'microsoft.insights/components',
  'value': [
    {
      'unit': 'Percent',
      'type': 'Microsoft.Insights/metrics',
      'timeseries': [ ],
      'name': {
        'localized_value': 'Availability',
        'value': 'availabilityResults/availabilityPercentage'
      }
    }
  ]
}
```

Anything I pass to the filter doesn't seem to have any effect. To me this seems like the filter doesn't return what it should. How can I get the filter working?

Edit: fenced code blocks for better readability.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by lmazuel** [comment]
Hi @bulkware 
Filter is deprecated, I should remove the first sample you mention :(
```python
metrics_data = client.metrics.list(
    resource_id,
    timespan="{}/{}".format(yesterday, today),
    interval='PT1H',
    metricnames='Percentage CPU',
    aggregation='Total'
)

for item in metrics_data.value:
    # azure.mgmt.monitor.models.Metric
    print("{} ({})".format(item.name.localized_value, item.unit.name))
    for timeserie in item.timeseries:
        for data in timeserie.data:
            # azure.mgmt.monitor.models.MetricData
            print("{}: {}".format(data.time_stamp, data.total))
```
IOW, the filter has been replaced by actual Python parameters. When you pass `filter`, it's lost in kwargs :(

**Comment by bulkware** [comment]
Ok, thank you. I will close the issue.
