### ISSUE TITLE
Version numbers, packaging, and releases

### ISSUE THREAD

**Issue by rjschwei** [Azure/azure-sdk-for-python#525]
Hi,

We are trying to provide the azure-sdk-for-python as a package to openSUSE and SUSE Linux Enterprise users. We are also using this as a basis to develop azurectl. While this is possible today it has become much more cumbersome since the reorganization of the project structure a while back. Also there is some inconsistency that can cause confusion and it would be great if these things can be eliminated and addressed.

Let me start out by describing what we would like to see and what is common accepted practice. We would like to see releases show up on pypi as "some-name.tar.gz", this can be the name of the release tarball from the github project, i.e. azure-sdk-for-python-1.0.3.tar.gz or some other name. This tarball should contain all the parts that are considered part of the SDK (currently that's apparently  azure-mgmt, azure-servicebus, azure-servicemanagement-legacy, and azure-storage only) and preferably a setup.py that conforms to common accepted practices.

As it stands today pypi provides either the components azure-mgmt, azure-servicebus, azure-servicemanagement-legacy, and azure-storage as download or a "wrapper" azure-1.0.3.zip. The wrapper itself provides basically no source code. Since the components are versioned separately and supplied as separate downloads this causes a great deal of confusion about a.) the version number that the SDK should have and b.) what is part of the SDK. According to the github release the following are part of the release (1.0.3):

azure
azure-common
azure-mgmt
azure-mgmt-common
azure-mgmt-compute
azure-mgmt-network
azure-mgmt-nspkg
azure-mgmt-resource
azure-mgmt-storage
azure-nspkg
azure-servicebus
azure-servicemanagement-legacy

while according to pypi only

azure-mgmt
azure-servicebus
azure-servicemanagement-legacy
azure-storage

are part of the sdk release.

Can this be sorted out such that we can download 1 tarball from pypi that represents the source code that the primary developers of the code base consider to be a release?

Thanks in advance

**Comment by lmazuel** [comment]
Hello,

First of all, azure-storage is not in this repository (managed directly by the storage team), I will not be able to make one unique tar.gz with everything including storage.
However, using the "release" on github you are able to download the full source code easily:
https://github.com/Azure/azure-sdk-for-python/archive/v1.0.3.tar.gz

We are currently working on the 2.0.0 release, where some versioning strategy might change for sub-package.

The other solution is download each separate package from Pypi.

azure-mgmt is itself a bundle package that install every azure-mgmt-* packages, but I agree that the Pypi "azure" page should display the entire dependencies tree.

**Comment by zooba** [comment]
Also, our intent is that the version of the `azure` package should reflect the overall SDK version, as it will (should) pin the versions of the subpackages.

So installing `azure==x.y.z` may not get you the latest version of `azure-storage`, but it will always get the same one. Users who want/need a later patch to the storage APIs are able to directly update that, which is only reliable with `pip` (as used by the majority of our users) using the current meta-package approach as opposed to a single consolidated package.

We do appreciate that this makes it more difficult for redistribution and vendoring of the whole package, but that's a relatively rare scenario, and we get some significant workflow benefits from splitting up the packages.

(FWIW, `pip install --target <dir> azure` will get you all the extracted sources in an easily vendored/redistributable directory.)

**Comment by rjschwei** [comment]
OK, I know storage is managed separately and I probably should have left it out. Our best approach there is to probably create a python-azure-storage package and manage that version according to that project.

I also suppose it is fair to call the current pypi "package" azure as it is a conglomeration of azure related Python modules, even if they are only used by reference and all these have their own version. Still this creates a big nightmare if help is needed by someone as it is way to easy to do a "pip install azure", which provides a certain version of the components but then do a "pip install A_COMPONENT" and lead the user right into potential trouble with compatibility or other issues.

Thus if the intention is to manage everything other than storage as one it would appear to be less risky for users to have a python-azure-storage release on pypi and have the azure release point to it + storage.

On the other hand if things go in the direction that different teams rather be on their own island than collaborate with each other it may be better to not have the top level azure-python-sdk and just have separately managed projects for the other components just like storage. 

So with storage set aside let me ask, if the intention is to keep azure-python-sdk together why not have a azure-python-sdk package on pypi that reflects the release state, and most important include the code, of this project? And if you are not willing to do that, can we at least get the release tarballs on GitHub signed, such that those downloading the tarball can at least verify that the downloaded tarball matches what those that released the code intended to be downloaded.

**Comment by zooba** [comment]
The intention is actually to keep splitting up azure-python-sdk, but unless the correct team is able to actually care for the package we prefer to keep them.

I'll admit I'm still trying to figure out what you're asking for. Certainly any single release of the `azure` package has an associated fixed set of code, but because they can be managed separately we don't release that big piece of code in a way that `pip` is going to install (and inevitably, mismanage).

What if whenever we updated `azure`, _we_ ran the install command above and put the resulting directory in a tarball on GitHub? It would be installable by copying, rather than having a `setup.py`, but it would be a complete and accurate representation of all of the referenced packages at that time.

**Comment by lmazuel** [comment]
I think I can close this issue, since the discussion went further in the #815 issue, and I think it's a better reference now.
Feel free to still comment on this one if I'm wrong.
Thank you!
