### ISSUE TITLE
How do you do AppRoleAssignment??

### ISSUE THREAD

**Issue by bachoang** [Azure/azure-sdk-for-python#5254]
I am currently helping a customer using python azure sdk.  He is looking for an equivalent way in Python to do the same thing as these 2 PowerShell command:

New-AzureADGroupAppRoleAssignment
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadgroupapproleassignment?view=azureadps-2.0
 
or New-AzureADUserAppRoleAssignment
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureaduserapproleassignment?view=azureadps-2.0

Can you offer some guidance?

**Comment by lmazuel** [comment]
Hi @bachoang 
Sure! Use the `azure-mgmt-authorization` client :)

I don't have specific sample, but the unitest should help you:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-authorization/tests/test_mgmt_authorization.py

Thanks!

**Comment by bachoang** [comment]
What you are referring to is something else @lmazuel.  You are referring to Azure RBAC role.  The customer is looking for Azure AD Application Role (see https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles)  The PS command does that.  It's making calls to this object  https://docs.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-beta

**Comment by lmazuel** [comment]
My bad, you need `azure-graphrbac` then.
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-graphrbac/tests/test_graphrbac.py

**Comment by bachoang** [comment]
Sorry but I am not seeing anything in that file to help me manage approleassignment object :(

**Comment by tobygale** [comment]
Over a year later but I've also just run into this issue.

@bachoang do you remember how you worked around the problem?  I guess you had to use the Graph API directly without the SDK? I know it was a long time ago now but any code/pointers you could share would be useful :smiley:

**Comment by lmazuel** [comment]
`azure-graphrbac` is about AAD Graph:
https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/api-catalog

The given link is for Microsoft Graph:
https://docs.microsoft.com/en-us/graph/api/resources/approleassignment

There is no Microsoft Graph package yet available in Python for this feature.

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
