### ISSUE TITLE
iot Hub

### ISSUE THREAD

**Issue by afeldman** [Azure/azure-sdk-for-python#527]
Hi all,

I really like to use the python azure sdk to work with for rapid prototyping. In the past I work with the event hub but I want to use the IoT hub too. Is there a timeline to include the IoT Hub Service for python? 

cheers

Anton

**Comment by lmazuel** [comment]
Hi Anton,

The way the Python SDK is built now requires that the IoT Hub team makes a Swagger description of their REST API. They didn’t publish it currently, I just forward your message as a proof of interest by our customers to the IoT team for an ETA on the Swagger file. I’ll let you know when I receive an answer. Please feel free to do a follow up if it takes too much time.

Thank you!

Laurent

**Comment by MatijaSrbic** [comment]
Hi Laurent,

Any news on Python SDK for IoT Hub?

Thank you,

Matija

**Comment by lmazuel** [comment]
The Swagger spec is currently in review, which means that I should be able to do a preview package soon.
https://github.com/Azure/azure-rest-api-specs/pull/356

Thank you for your patience!

**Comment by lmazuel** [comment]
I just released the first preview version of IoTHub Management client:
https://pypi.python.org/pypi/azure-mgmt-iothub

There is no sample yet, but the basic test can help you to start:
https://github.com/Azure/azure-sdk-for-python/blob/dev/azure-mgmt/tests/test_mgmt_iothub.py

The is also IoTHub device SDK for Python, handled directly by the IoTHub team:
https://github.com/Azure/azure-iot-sdks/tree/master/python/device

Please let me an,y feedback/problem you encounter, do not hesitate to open an issue :)
