### ISSUE TITLE
Messages > 256KB are not supported

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#5286]
@jaganth commented on [Mon Apr 15 2019](https://github.com/Azure/azure-event-hubs-python/issues/106)

[debug.log](https://github.com/Azure/azure-event-hubs-python/files/3082590/debug.log)

Currently Event Hubs support messages size up to 1 MB (the old limit was 256KB). Current when sending a message larger than 256KB we get the below error:

2019-04-15 15:30:50,167 uamqp.c_uamqp INFO     b'<- [DISPOSITION]* {true,1,NULL,true,* {* {amqp:link:message-size-exceeded,The received message (delivery-id:0, size:262412 bytes) exceeds the limit (262144 bytes) currently allowed on the link. TrackingId:1971a5ae-2aac-4708-ae41-976b40bf6243_B10, SystemTracker:NoSystemTracker, Timestamp:2019-04-15T22:30:50,NULL}},NULL}'

sender.send(EventData('ABCDEFGHIJKLMNOPQRSTUVWXYZ012345' * 8200))

Using EventHubClient to send messages are restricted to 256KB on the link. It seems we need a hook into the setting the ‘max-message-size’ property so that we can send messages of 1 MB size. 1 MB is the new default (256KB being the old default).

https://github.com/Azure/azure-uamqp-python/blob/813e3ce6636016948f32d5afa8435c8bfe39b0f2/uamqp/client.py - SendClient

self._max_message_size = kwargs.pop('max_message_size', None) or constants.MAX_MESSAGE_LENGTH_BYTES

https://github.com/Azure/azure-uamqp-python/blob/e3e26b1621ae87ec72ecb68071dd40a18118ef85/src/constants.pyx - default max size is 256KB

MAX_MESSAGE_LENGTH_BYTES = 256 * 1024

---

@zhengwia commented on [Tue May 07 2019](https://github.com/Azure/azure-event-hubs-python/issues/106#issuecomment-490023357)

Hi Is this bug fix included in the next release please?

Thanks

---

@annatisch commented on [Tue May 07 2019](https://github.com/Azure/azure-event-hubs-python/issues/106#issuecomment-490100101)

Yes it will be in the next release. :)

---

@zhengwia commented on [Tue May 07 2019](https://github.com/Azure/azure-event-hubs-python/issues/106#issuecomment-490100803)

thanks so in a week's time?

**Comment by zhengwia** [comment]
Hi is this bug fix released yet pls? I see the issue status is still open

**Comment by annatisch** [comment]
Hi @zhengwia - yes this should be fixed in the new preview release:
https://pypi.org/project/azure-eventhub/5.0.0b1/

**Comment by arati-barracuda** [comment]
Hi,
 I did following to upgrade to latest azure-event package. 
pip3.6 uninstall azure-eventhub
pip3.6 install --pre azure-eventhub

However while importing EventHubClient i get below error
python3.6
Python 3.6.8 (default, Nov  6 2019, 00:53:51)
[GCC 4.3.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.eventhub import EventHubClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'EventHubClient'
>>>

**Comment by annatisch** [comment]
Resolved with updated uamqp release.
To support larger message sizes with either stable of preview EH SDKs, update uamqp:
```
pip install --upgrade uamqp
```
