### ISSUE TITLE
Installation Fails: x not in list

### ISSUE THREAD

**Issue by new-gen23** [Azure/azure-sdk-for-python#5291]
I followed the installation manual from:

> https://github.com/Azure/azure-sdk-for-python

until: python setup.py install

Here, I get the error: 

`Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    content_package.remove("azure-common")
ValueError: list.remove(x): x not in list
`

Checked out git version: fd643a07a08f5ae912344c45f91ecd7278e9049b
Any advise?

**Comment by lmazuel** [comment]
Hi @new-gen23 
It got broken recently by some reorg in the repo, I intend to fix it.
Thanks,

**Comment by scbedd** [comment]
@new-gen23 I have updated setup.py to resolve this error in #5449 

Can you confirm that it works for you now?
