### ISSUE TITLE
EventProcessorHost do not create consumer group container under blob container

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#5304]
@yuhaii commented on [Thu Apr 18 2019](https://github.com/Azure/azure-event-hubs-python/issues/108)

I specified different consumer groups, the python SDK omit generating container with consumer name, it simple create the partition lease file under “pythoneventhub” container. 

![image](https://user-images.githubusercontent.com/39817657/56402822-79843c00-6291-11e9-9061-8e9e36e9160e.png)

![image](https://user-images.githubusercontent.com/39817657/56402826-830da400-6291-11e9-94dd-f15cece68b28.png)

![image](https://user-images.githubusercontent.com/39817657/56402831-8acd4880-6291-11e9-9317-8b970c9e9891.png)

We compared with Java code. We can see it will create container with consumer name, then create the partition lease file under consumer container.

![image](https://user-images.githubusercontent.com/39817657/56402864-a0db0900-6291-11e9-9d8a-a7c9c21ec188.png)

![image](https://user-images.githubusercontent.com/39817657/56402880-bea86e00-6291-11e9-9607-df61c1324cea.png)

![image](https://user-images.githubusercontent.com/39817657/56402950-f9aaa180-6291-11e9-85d1-fb4c81a24da7.png)

---

@yuhaii commented on [Sun Apr 21 2019](https://github.com/Azure/azure-event-hubs-python/issues/108#issuecomment-485289664)

Hello, do you have any update on this issue? Thanks!

---

@annatisch commented on [Mon Apr 22 2019](https://github.com/Azure/azure-event-hubs-python/issues/108#issuecomment-485517965)

Hi @yuhaii - thanks for the report!
We are planning to have an updated release for EventHubs in early-mid May - so we will try to address this for that release.
Also - we will be moving this SDK into the azure-sdk-for-python repo. At that time, any issues that are still open in this repo I will move over to that repo.

Thanks!

---

@yuhaii commented on [Mon Apr 22 2019](https://github.com/Azure/azure-event-hubs-python/issues/108#issuecomment-485586839)

Hello @annatisch , got it. Thanks for your update. I look forward to your next update. Thanks!

**Comment by yuhaii** [comment]
Hello @annatisch , may I know whether there is any update of the release? Thanks in advance!

**Comment by yuhaii** [comment]
Hello @yunhaoling  and @annatisch , could you please update me the current status of the release. Thanks!

**Comment by yunhaoling** [comment]
Fixed this problem in 5.0.0b1.
And we have a new event processor design to replace the old eventprocessorhost in 5.0.0b2 and future releases. We will have other storage options.
