### ISSUE TITLE
Slow running tasks don't checkpoint frequently

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#5319]
@annatisch commented on [Sat Aug 04 2018](https://github.com/Azure/azure-event-hubs-python/issues/50)

Seeing behaviour in EPH where tasks that take a long time to process (~10 seconds) result in a large number of failed connections and failed checkpoints. 

Current recommendations:
- Try droping `EHOptions.prefetch_count` and `EhOptions.max_batch_size` to 1, or a very low value.
- Try increasing the `lease_duration` to ~60 seconds, and the `lease_renew_interval` to ~10 seconds.
- Try wrapping any blocking calls in the task processor in an async processor:
`loop.run_in_executor(None, functools.partial(my_blocking_event_processing, event))`

**Comment by annatisch** [comment]
EPH has since been largely rewritten - closing.
