### ISSUE TITLE
Package azure==2.0.0.a1 fails to install from pypi

### ISSUE THREAD

**Issue by chaudum** [Azure/azure-sdk-for-python#532]
Traceback:

```
...
Getting distribution for 'msrestazure'.
error: [Errno 2] No such file or directory: 'readme.rst'
An error occurred when trying to install msrestazure 0.0.1. Look above this message for any errors that were output by easy_install.
While:
  Installing azure-sdk.
  Getting distribution for 'msrestazure'.
Error: Couldn't install: msrestazure 0.0.1
```
[full log](https://gist.github.com/chaudum/c551aca3c7b8620f30a8#file-terminal-log)

This is because `readme.rst` is missing from the `msrestazure` package on pypi. There is an open issue already: https://github.com/Azure/autorest/issues/718

**Comment by lmazuel** [comment]
Hi,

The source package are broken (but not the wheels, it's why we did not notice that during our tests). I found the issue I will speak with the Autorest team to fix that ASAP

Thank you!

**Comment by lmazuel** [comment]
PR in Autorest repo https://github.com/Azure/autorest/pull/732

**Comment by ldimans** [comment]
+1

**Comment by lmazuel** [comment]
Just release the new versions of the broken dependencies of Pypi:
https://pypi.python.org/pypi/msrestazure/0.0.2
https://pypi.python.org/pypi/msrest/0.0.3

Content:
https://github.com/Azure/autorest/pull/761

Sorry about the delay... I close this bug, feel free to re-open if your problem still persist.

**Comment by chaudum** [comment]
works now. thanks!
