### ISSUE TITLE
Live Testing Python 3.5.3

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#5336]
@danieljurek commented on [Mon May 20 2019](https://github.com/Azure/azure-sdk/issues/374)

Python 3.5.3 is not available in `Agent.ToolsDirectory` and can't be installed from the [UsePythonVersion task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops). We want to be able to test arbitrary version of Python if they aren't on the agent machine.

A couple options we've discussed
* Build and install Python (perhaps cache build outputs periodically so we don't have to spend machine time building) 
* Run jobs within a Docker container

**Comment by scbedd** [comment]
@scbedd follow-up on which version is getting installed here.

**Comment by danieljurek** [comment]
We're running 3.5.7 today: 

```
Found tool in cache: Python 3.5.7 x64
```

**Comment by danieljurek** [comment]
On Linux it's Python 3.5.7, on Windows it's Python 3.5.4
