### ISSUE TITLE
Resolving references?

### ISSUE THREAD

**Issue by pneumee** [Azure/azure-sdk-for-python#534]
Is there any helper function or API functionality that I'm missing that will resolve references to objects? Eg: Retrieve a VM instance, which has a reference to its network interface (NetworkInterfaceReference). I want a NetworkInterface object, not a reference. Is the only way to do this to pick apart the reference URI to grab the resource group name and network interface name and then do get()?

**Comment by lmazuel** [comment]
Hi,

Unfortunately, the `VirtualMachine` REST API which we use only gives the reference:
https://msdn.microsoft.com/en-us/library/azure/mt163682.aspx

Moreover, `Network` is not the same client of `Compute` and they are two separate packages with no inter-dependencies.

So, you have to do something like this:
```python
vm = compute_client.virtual_machines.get('vm1', 'vm1')
network_interface_full_id = vm.network_profile.network_interfaces[0].id
network_interface_short_id = network_interface_full_id.split('/')[-1]
network_interface_details = network_client.network_interfaces.get('vm1',network_interface_short_id)
print(network_interface_details.location)
```

**Comment by pneumee** [comment]
Thanks for confirming!

**Comment by csm10495** [comment]
@pneumee has there been a feature request for something like this (the ability to resolve a reference via some mechanism)?
