### ISSUE TITLE
Investigate running Python tests in parallel

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#5371]
@chlowell mentioned that we could save time running pytest tests in parallel. He suggested looking into https://pypi.org/project/pytest-xdist/

**Comment by danieljurek** [comment]
Discussed this further with Charles today. This would require:
* Ability to `pip install` a dependency for tests that require it 
* Specify the module in the python command

We can do targeted validation of this with KeyVault

**Comment by danieljurek** [comment]
This is possible to do today however only one instance of the Key Vault tests (tests that can be run in parallel today) can run at any given time. There is an issue open to enable this: https://github.com/Azure/azure-sdk-for-python/issues/5843

**Comment by scbedd** [comment]
`pytest-xdist` is installed for the `livetest` runs right now.
