### ISSUE TITLE
ResourceGraphClient's resources method not handling correctly HTTP 429 responses

### ISSUE THREAD

**Issue by helderpinto** [Azure/azure-sdk-for-python#5412]
In a scenario where the Azure Resource Graph API is throttling requests for a specific tenant, the `ResourceGraphClient`'s `resources` method is not handling correctly HTTP 429 responses. Instead of implementing a retry policy, it simply throws a generic `ErrorResponseException`. See debug trace below:

```
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "POST /providers/Microsoft.ResourceGraph/resources?api-version=2019-04-01 HTTP/1.1" 429 2
DEBUG:msrest.exceptions:Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get'
DEBUG:msrest.exceptions:Operation returned an invalid status code ''
```

This is raising an `azure.mgmt.resourcegraph.models.ErrorResponseException`

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by lmazuel** [comment]
Hi @helderpinto 
Could you share some code, and a more complete stacktrace? You can also enable HTTP trace logging by doing `client.config.enable_http_logger = True`
Thank you

**Comment by helderpinto** [comment]
@pharaujo, can you please share more details as asked by @lmazuel?

**Comment by pharaujo** [comment]
Hi @lmazuel 

I created a gist with all the requested information (a minimal-ish python script that triggers the issue, a more complete log generated with HTTP trace logging enabled, the stack trace seen). Additionally, I also include the versions used. Here is the gist: https://gist.github.com/pharaujo/43c110e68cf381dca9b731bd0715b7e9

**Comment by lmazuel** [comment]
Hi @pharaujo @helderpinto 
The retry mechanism is not triggered because your reply does not contain a Retry-After as it should:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits#waiting-before-sending-next-request

I would suggest to open a support ticket for the Resource Graph team, or ARM team and see if they can fix it.
Thanks!

**Comment by helderpinto** [comment]
Thank you for the feedback @lmazuel. We just opened a support ticket (119061325001439).

**Comment by helderpinto** [comment]
Hi! Just to let you know that as a consequence of the ticket we opened, a Resource Graph API fix was deployed by the second half of July and that the issue wasn't seen anymore since then. This issue can be closed. Thank you!
