### ISSUE TITLE
Get/Set metadata story is a bummer

### ISSUE THREAD

**Issue by bryanar** [Azure/azure-sdk-for-python#542]
The following code should 'just work', in my opinion:

```
metadata = blob_service.get_container_metadata(state)
blob_service.set_container_metadata(state, metadata)
```

What I am expecting to happen here is that I retrieve the metadata, and then re-write it. At the moment this isn't possible and returns with the following error:

```
azure.common.AzureHttpError: The metadata specified is invalid. It has characters that are not permitted.
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidMetadata</Code><Message>The metadata specified is invalid. It has characters that are not permitted.
RequestId:a91a1861-0001-0067-3cf0-7b83d1000000
Time:2016-03-11T23:47:14.5882290Z</Message></Error>

```

This EXACT scenario isn't required/necessary, but it is the crux of the problem where I'd simply like to 'append' metadata to existing metadata. In order to work around this I suspect (unless someone points out otherwise) I will need to strip out the x-ms-meta- prefix out of the keys and THEN I can resubmit. That's a lot of extra cycles for the developer, as well as the computer that do nothing but get in the way.

**Comment by emgerner-msft** [comment]
Issue Migrated to Azure/azure-storage-python#141
