### ISSUE TITLE
Install `setup.py` as part of the nightly build verification

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5447]
It's not essential for _each package_ in the repo, but is an essential part of making certain our local dev story isn't broken.

Ref this issue: #5291

**Comment by kurtzeborn** [comment]
Is this intended to test our built packages?  If yes, then this is probably something we should include in the work to implement smoke tests for all languages which load all libraries into the same process.

**Comment by scbedd** [comment]
This is intended to test the default `install the world` that is executed. 

Exact method. From root of the repo, execute `python setup.py develop`

I consider this a lower pri ask, but also something that we should get around to eventually.

**Comment by scbedd** [comment]
Tox `sdist` environment fixes this.
