### ISSUE TITLE
required positional argument: 'self' in add_receiver() method

### ISSUE THREAD

**Issue by MarieS1415** [Azure/azure-sdk-for-python#5482]
Hello,

I am trying to use azure-eventhub, but I have some problems when trying to use the add_receiver method.

I have the following code:

> client = azureEventHub.EventHubClient(url + "/" + eh_cfg.hub_name, eh_cfg.key_name, eh_cfg.key, false, nil, 60, nil)
> receiver = client.add_receiver(consumer_group: consumer_group, partition: num_partition)

The error in the logs states:

> PyError: <class 'TypeError'>: add_receiver() missing 1 required positional argument: 'self'

Therefore I added self:client in add_receiver, though it seems strange to me:

> client.add_receiver(consumer_group: consumer_group, partition: num_partition, self: client)

But now the error is:

> PyError: <class 'AttributeError'>: type object 'EventHubClient' has no attribute 'address'
> File "/home/marie/.local/lib/python3.6/site-packages/azure/eventhub/client.py", line 400, in add_receiver
> path = self.address.path + operation if operation else self.address.path

Am I uncorrectly declaring the client?

I am using python 3.6.7 and azure-eventhub 1.3.1, but the main app is on ruby and I use pycall to call python code inside the ruby app.

Thanks for your help!

**Comment by lmazuel** [comment]
@annatisch ?

**Comment by MarieS1415** [comment]
Hello,
Is it the good place to ask this question? If not, please tell me where I can ask.
Thank you very much

**Comment by yunhaoling** [comment]
Hi @MarieS1415 ,

Please take a look at the sample code here:
https://github.com/Azure/azure-sdk-for-python/blob/release/eventhub-v1/sdk/eventhub/azure-eventhubs/examples/recv.py


Besides we have recently release eventhub 5.0.0, please take a try on the latest library. Any feedback is welcome :)
