### ISSUE TITLE
get_instance_view for virtual machine?

### ISSUE THREAD

**Issue by nitzmahone** [Azure/azure-sdk-for-python#549]
Unless I'm missing something, it looks like in the 2.0rc there's no way to get the instance view for a virtual machine? Specifically, we need access to the PowerState of the VM- unless something's changed, the instance view is the only place I'm aware of to get it.

**Comment by lmazuel** [comment]
Hi,

There was already an issue for this one which was solved:
https://github.com/Azure/azure-sdk-for-python/issues/548

It seems clear now that I have to improve the documentation on this :)
Please feel free to re-open if you think the linked issue does not solve your problem.

**Comment by nitzmahone** [comment]
Looks like that'll do what I need- thanks!
