### ISSUE TITLE
Dealing with dev requirements inherited from azure-core

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-python#5504]
We recently had a series of challenges getting a more narrowly scoped PR/CI validation pipeline running for modules under ```sdk/keyvault/```. The reason was that they were having trouble loading modules from ```sdk/core/``` - specifically ```AsyncPipelineClient``` during test execution.

Currently the ```__init__.py``` swallows syntax error and import exceptions when developers have the requisite version of python or dependencies (such as ```aiohttp```) installed. The assumption is that without those installed they just aren't going to be wanting to do async and we can silently continue.

However as we start working on our client libraries that depend on ```azure-core``` we are going to need to make sure we install these dev-time dependencies when we run our PR validation pipelines.

Should we have a global set of requirements that we install? Should we explicitly reference things like ```aiohttp``` in modules that depend on ```azure-core``` even when it is only a transitive dependency?

**Comment by mitchdenny** [comment]
Adding @scbedd and @chlowell for thoughts on how to approach this holistically moving forward.

**Comment by scbedd** [comment]
I do really like the idea of a global dev_requirements. However, for specific package debugging the most common pattern I've seen is just pip install -e `requirements.txt` prior to installing your package. I'm wondering if we can have nested requirements.txt. Will take a look around.

**Comment by mitchdenny** [comment]
That wouldn't work in this particular case because ```aiohttp``` is not listed as a requirement. But it is in ```dev_requirements.txt``` for ```azure-core``` so may be do both?

**Comment by scbedd** [comment]
You're right. Even if I made it so that a relative reference to the global dev_requirements was present, it wouldn't also pick up stuff from azure-core.

Unless, of course, `azure-core` _is_ the base dependency. For track 2 stuff it probably will be.

**Comment by mitchdenny** [comment]
It is a runtime requirement IF people want to use async on language versions of python that support it, but its not the only async over HTTP implementation we support.

**Comment by scbedd** [comment]
Closing in favor of extensions to the `tox` discovery.
