### ISSUE TITLE
Keyvault Python rename all the list operations to start with get

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-python#5519]
@samvaity commented on [Wed May 29 2019](https://github.com/Azure/azure-sdk/issues/389)

Update names of list operations to be called get operations in keys and secrets client.

list_keys => get_keys
list_deleted_keys => get_deleted_keys
list_key_versions => get_key_versions
list_secrets => get_secrets
list_deleted_secrets => get_deleted_secrets
list_key_secrets => get_key_secrets

---

@adrianhall commented on [Wed May 29 2019](https://github.com/Azure/azure-sdk/issues/389#issuecomment-497025558)

@samvaity please update the issue with all the information required for a change.  You can see this information when selecting the template in New Issue.

This is probably not a good idea.  In Java, getKeys() would be more indicative of a property called "Keys" - i.e. in .NET, it would be Client.Keys (returning a separate collection) and not an async method that got the keys from the backend. (Cc: @jonathanGiles)

**Comment by chlowell** [comment]
The architects agreed consistency within each language is more important here, so we'll continue using `list_` in accord with the Python guidelines.
