### ISSUE TITLE
network_security_group ignored during network.models.NetworkInterface creation.

### ISSUE THREAD

**Issue by aznashwan** [Azure/azure-sdk-for-python#552]
I know we had a similar issue with subnets in the NetworkInterfaceIPConfiguration init.
Reporting it so you guys know what to check when you re-gen that part of the code.

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-network%2Fazure%2Fmgmt%2Fnetwork%2Fmodels%2Fnetwork_interface.py#L76

**Comment by lmazuel** [comment]
Thank you for the report!

This is fixed on dev branch using the fixed generator:
https://github.com/Azure/azure-sdk-for-python/blob/dev/azure-mgmt-network/azure/mgmt/network/models/network_interface.py

I let this issue open until the next version is released.

**Comment by lmazuel** [comment]
I just released 2.0.0rc2 which fixes the bug. Please feel free to re-open if you experience any trouble.

Thank you again for your report!
