### ISSUE TITLE
Keyvault update param `key_ops` to `key_operations`

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-python#5520]
ADP meeting review meeting feedback to update param name `key_ops` to `key_operations` in keys and secrets client.

**Comment by AlexGhiondea** [comment]
@samvaity @chlowell are we still tracking this for Preview 1?

**Comment by AlexGhiondea** [comment]
Nevermind, saw that this is in PR already :).

**Comment by samvaity** [comment]
Closed with #5993
