### ISSUE TITLE
Can't list service fabric applications using mgmt package

### ISSUE THREAD

**Issue by themucha** [Azure/azure-sdk-for-python#5536]
I'm encountering an deserialization error when I try to list Service Fabric applications via the mgmt service fabric package.

### Code:
        apps = servicefabric_client.application.list(resource_group_name=resource_group,
                                                     cluster_name=cluster.name) # line 29

### Error:
Error:Traceback (most recent call last):
  File ".\find-service-fabric-app-types.py", line 29, in <module>
    cluster_name=cluster.name)
  File "D:\Src\ms\lib\site-packages\azure\mgmt\servicefabric\operations\application_operations.py", line 447, in list
    deserialized = self._deserialize('ApplicationResourceList', response)
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1228, in __call__
    return self._deserialize(target_obj, data)
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1294, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1478, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1478, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1460, in deserialize_data
    return self._deserialize(obj_type, data)
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1294, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "D:\Src\ms\lib\site-packages\msrest\serialization.py", line 1476, in deserialize_iter
    type(attr)
msrest.exceptions.DeserializationError: Cannot deserialize as [ApplicationParameter] an object of type <class 'dict'>

**Comment by lmazuel** [comment]
Hi @themucha,

This particular error means that the RestAPI meta-description of the service was not accurate when I generated this package. It turns out there is an update to this meta-description, let me try to generate this code and see if this fix the issue. If it's not, I will create an issue for the service team to fix there meta-description.
Thanks!

**Comment by themucha** [comment]
Great, @lmazuel  Thanks for the quick response!

**Comment by lmazuel** [comment]
Hi @themucha 
I released the latest version of the RestAPI description, which I believe fix your issue:
https://pypi.org/project/azure-mgmt-servicefabric/0.3.0/

Beware since this SDK was in preview, we had to do some renaming to follow current guidelines (`servicefabric_client.application` is now `servicefabric_client.applications`). Complete list on PyPI front page.

Please confirm if this solves your issue.
Thanks!

**Comment by themucha** [comment]
I tried testing this, but I get a "NoRegisteredProviderFound" error. I'll see if I can find out how to get access to a preview API, unless you have tips on how to do this. Thanks for your help, @lmazuel.

Traceback (most recent call last):
  File ".\find-service-fabric-app-types.py", line 30, in <module>
    cluster_name=cluster.name)
  File "D:\Src\money-saver\lib\site-packages\azure\mgmt\servicefabric\operations\applications_operations.py", line 455, in list
    raise models.ErrorModelException(self._deserialize, response)
azure.mgmt.servicefabric.models.error_model_py3.ErrorModelException: (NoRegisteredProviderFound) No registered resource provider found for location 'westus2' and API version '2019-03-01-preview' for type 'clusters/applications'. The supported api-versions are '2016-03-01, 2016-09-01, 2017-07-01-preview, 2017-07-01-privatepreview'. The supported locations are 'westus, westus2, westcentralus, eastus, eastus2, centralus, westeurope, northeurope, ukwest, uksouth, australiaeast, australiasoutheast, northcentralus, eastasia, southeastasia, japanwest, japaneast, southindia, westindia, centralindia, brazilsouth, southcentralus, koreacentral, koreasouth, canadacentral, canadaeast, francecentral, southafricanorth'.

**Comment by lmazuel** [comment]
Region can indeed creates this message, since in theory the SDK will auto-register the provider if it's possible.
Otherwise, you can try to register manually with the CLI:
https://docs.microsoft.com/en-us/cli/azure/provider?view=azure-cli-latest#az-provider-register
```
az provider register --namespace 'Microsoft.ServiceFabric'
```

**Comment by themucha** [comment]
@lmazuel - After further investigation (i.e. looking at the RP manifest), I can't access that version of the API because it's behind a feature flag.

**Comment by lmazuel** [comment]
Hi @themucha 
The service team just answered me that they have removed the need for a feature flag, and that should work now. Could you re-try and confirm?
Thank you

**Comment by themucha** [comment]
@lmazuel - I verified that the version 0.3.0 fixes the issue. Thanks for your help!
