### ISSUE TITLE
Cosmos emulator tests should skip if no emulator present

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5554]
* add `emulator_config` fixture to conftest. Something like this in [servicebus](https://github.com/Azure/azure-sdk-for-python/blob/b08df32b697bde324cf1cfd88d8a30e7ddb97789/sdk/servicebus/azure-servicebus/conftest.py#L201)
* Add the fixture to any test that requires an emulator to pass

Short term mitigation to unblock merge will be taken in #5553

**Comment by bryevdv** [comment]
I'd like to push back on this. There are 191 tests that would need to be cluttered up individually to do things this way (and that work would need to be repeated manually on the v3 branch afaik).  That's also fragile for anyone on the cosmos team writing new tests, if the forget to add this boilerplate to every new test. 

I understand reticence to maintain per-project flags on your end. What about ES defining a single generic mark for skipping tests, that any project can use any time they have tests with special requirements to be run in alternative pipelines?

**Comment by scbedd** [comment]
I _could_ see the need for the single alternative `skip this in ci` option. `pytest.mark.alt_pipeline` is as good as any. 

I really value the experience of consistent pytest execution (aka, having it handle these errors gracefully), but it's not like we have a huge wealth of data-plane projects that prove this out. Right now we have livetest execution handled in this method. `cosmos` is the first one with real "other" usages required. Will discuss with the rest of my team as well.

**Comment by bryevdv** [comment]
@scbedd What is the current state of things here? I feel like I noticed some changes recently on the ES side that maybe point to this issue being close-able

**Comment by scbedd** [comment]
I'll be honest @bryevdv I have _no idea_ let me sync with @danieljurek

**Comment by scbedd** [comment]
This is actually where @danieljurek  left it. [See here](https://github.com/Azure/azure-sdk-for-python/blob/10ddfaa64f5a2ccab96f3167d2cc2285f466c478/eng/pipelines/templates/stages/cosmos-sdk-client.yml#L16)
