### ISSUE TITLE
P1: Only one network security rule can be added successfully.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-python#556]
I have created a network security group and associated it to my subnet. When I were using azure-sdk-for-python to add multiple rules, only one rule could be added successfully. Do I need to use other methods to check the last result until it succeeds every time before creating a new rule? Expect a solution.

Please see my code as below. You can see more code [here](
https://github.com/AbelHu/azure-quickstart-templates/blob/test/bosh-setup/scripts/setup_env.py#L45-L57)
```python
    for name,port in rules['TCP'].items():
        params = azure.mgmt.network.models.SecurityRule(
            'TCP',
            '*',
            static_ip+"/32",
            'Allow',
            'Inbound',
            source_port_range='*',
            destination_port_range=port,
            priority=priority,
            name=name)
        priority += 1
        ret=network_client.security_rules.create_or_update(settings["RESOURCE_GROUP_NAME"], nsg_name, name, params)
```

Error Trace:
statusCode:429 serviceRequestId:93206980-37d9-4693-a0fd-9fc7b9569902 statusMessage:{"error":{"code":"RetryableError","message":"A retryable error occured.","details":[{"code":"RetryableErrorDueToAnotherOperation","message":"Operation PutSecurityRuleOperation (4bf85bce-c1b2-4963-9ed5-61e07f145dd9) is updating resource /subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourceGroups/abel-template1/providers/Microsoft.Network/networkSecurityGroups/nsg-cf."}]}}

**Comment by lmazuel** [comment]
Hi,

We worked a lot on the documentation recently and I think the version in `dev` branch currently is more accurate that the one in `latest`: [ReadTheDocs on security_rules.create_or_update](http://azure-sdk-for-http://azure-sdk-for-python.readthedocs.org/en/dev/ref/azure.mgmt.network.operations.html#azure.mgmt.network.operations.SecurityRulesOperations.create_or_update)

You can see that `create_or_update` returns a `AzureOperationPoller` object which is the object you get when the method is async.
From an `AzureOperationPoller` object, you can call `wait` to wait the operation to complete.

Then I would change your last line by:
```python
ret=network_client.security_rules.create_or_update(settings["RESOURCE_GROUP_NAME"], nsg_name, name, params)
ret.wait()
```

FYI, the `dev` branch will be released as rc2 next Tuesday.

**Comment by AbelHu** [comment]
@lmazuel Thanks so much. It works.
