### ISSUE TITLE
CloudEnvironement and track 2

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#5561]
What's the story for tack and the CloudEnvironment definition?
https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_cloud.py

That's important for both ARM and data-plane, which makes a placement in azure-core too extreme but a placement in azure-mgmt-core not enough as well.

**Comment by johanste** [comment]
Pending https://github.com/Azure/azure-sdk/issues/663
