### ISSUE TITLE
Check upstream dependencies for changed versions, trigger a build if an upstream dependency has been released

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5567]
Recently, cryptography released a package without windows wheels. This immediately breaks any and all windows python packages that take a dependency on crypto.

Our loops should be:
* Check (leverage `analyze_deps` to get full list)
* If upstream deps changed from last one, trigger nightly build

To add onto this, we also need to check the following, and issue a stronger signal than simply triggering a build.
* So a new upstream dependency updated, _can we pull in this new release with our packages current version specifier?_ 
   * Real Example: `azure-eventhubs` takes a dependency on `azure-storage-blobs-1.3.X`, but `azure-storage-blobs` has released version `2.0.X`. This is a major version change that we missed!
* Verify that in-repo depdendencies version specifier  _also_ doesn't omit new releases from our own repo! Same check as above, but for package A depending on package B in the repository.

**Comment by kurtzeborn** [comment]
Is this still a problem if we pin versions without the ^ meaning we don't automatically take higher versions?

Automatically kicking off builds based on changes/releases done with external packages is concerning here as well.

CC: @weshaggard

**Comment by scbedd** [comment]
In the python world, it is recommended that either `^` or `>= 1.2; < 2` (aka accept above current that's not a major patch)

It is rare that exact dependencies are taken.

Examples from _extremely_ popular github repos:
[Flask](https://github.com/pallets/flask/blob/d4b688bd035b9704b3168b28fed39c8fcfe3b997/setup.py#L40)
[Django](https://github.com/django/django/blob/8ba20d9071e9e1b8f2c81d4df977db4278342085/setup.py#L86)
[HTTPie](https://github.com/jakubroztocil/httpie/blob/fd44f1af93ce1d2c84f324b8474d2d075b5a7b13/setup.py#L37)

All use the `float forward` logic.

**Comment by weshaggard** [comment]
@scbedd do you know how they handle these issues where they need to rebuild based on a new dependency being released? Also if you use ranges how can you have a wheel that will work with all the packages in that range?

**Comment by scbedd** [comment]
So...unfortunately, I don't have a good answer here. Let me talk to a couple people more knowledgeable than me and circle back.

Note that the ranges pretty much never cross major version lines.

**Comment by weshaggard** [comment]
If they don't cross major version lines then why would we be broken :) Either they didn't follow the SemVer rules or we are trusting them more then we should, and thus we should consider pinning the version.

**Comment by scbedd** [comment]
Aha. I was not clear in my first response. People float `minor` versions forward as good practice. Relying on SEMVER rules to not be broken by other people. 

It's funny because JS was recently broken by a minor version change :P

**Comment by johanste** [comment]
@weshaggard, you are correct that for libraries that follow semantic versioning (which not all python projects do), we **shouldn't** be broken by a minor change. 

But we have been in the past. It is entirely possible to accidentally take a dependency on non-contractual implementation details or flat out bugs in another package. Or that the other package shipped with an accidental breaking change.

**Comment by scbedd** [comment]
Closing as we already build nightly.
