### ISSUE TITLE
figure out a way to use the full features of implementations

### ISSUE THREAD

**Issue by SuyogSoti** [Azure/azure-sdk-for-python#5586]
Necessary so that we can get the span from the context and also to properly use the propagator in our policy header.

Options So Far:
+ Import implementation when the span wrappers are initialized
+ Use extensions so that the user must install extra packages
+ Policy just has a bunch of If statements to import the proper implementation
+ Sub Policies that each import the proper implementation

I think the first way is going to be the best way as we already have span wrappers. The first way would also allow us to support all the features even for implementations without the extension architecture. The first way can allow the client to turn this feature on with just a flip of an environment variable. The second way would force the client to install an extra package. The fourth way would require code change and redeployment of the app.
[Initial Discussion](https://github.com/Azure/azure-sdk-for-python/pull/5444#discussion_r288774169)

**Comment by SuyogSoti** [comment]
cc: @bryevdv @johanste

**Comment by lmazuel** [comment]
@SuyogSoti Please label your issue so I don't have to triage them ;). Thanks!

**Comment by SuyogSoti** [comment]
We went with option 1 and possibly two.
