### ISSUE TITLE
Typo in documentation for Computer Vision VisualFeatureTypes enum

### ISSUE THREAD

**Issue by LukeBayler** [Azure/azure-sdk-for-python#5588]
https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-computervision/azure.cognitiveservices.vision.computervision.models.visualfeaturetypes?view=azure-python

I was trying to specify "image_type" for the VisualFeatureTypes enum when calling analyze_image_in_stream on a computer vision client, and it turns out that in order for the call to work, I must specify it without the underscore as "imagetype"

**Comment by lmazuel** [comment]
Hi @LukeBayler 
Could you share an example of code just to be sure I get the exact syntax, since enum can be subtle in the parser actually. Thanks!

**Comment by LukeBayler** [comment]
Here is an example:

local_image = open(local_image_path, "rb")
local_image_features = ["imagetype"]
local_image_analysis = computervision_client.analyze_image_in_stream(local_image, local_image_features)

print("\nImage type of local image:")
print("Clip art type: " + str(local_image_analysis.image_type.clip_art_type))
print("Line drawing type: " + str(local_image_analysis.image_type.line_drawing_type))

**Comment by lmazuel** [comment]
Hi @LukeBayler 
There two ways to specify this:

- Using the RestAPI syntax: https://docs.microsoft.com/en-us/rest/api/cognitiveservices/computervision/analyzeimageinstream/analyzeimageinstream
Then the correct string is "imagetype" or "imageType"

- Using the [enum](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-computervision/azure.cognitiveservices.vision.computervision.models.computer_vision_client_enums.visualfeaturetypes?view=azure-python)
```python
from azure.cognitiveservices.vision.computervision.models import VisualFeatureTypes
VisualFeatureTypes.image_type
```

The string "image_type" is indeed invalid.

For what I see here, you confused the name of the field in the enum, with the actual string to send.

Hope this clarifies! Thank you,

**Comment by LukeBayler** [comment]
Yes. This does clarify. Thank you for your help.
