### ISSUE TITLE
Share code between sync and async tests

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#5630]
A/sync test code is currently duplicated. Each async test is essentially a copy of a sync test with `async/await` and a decorator added. Sharing the code would be preferable.

**Comment by SiddhantJ19** [comment]
Hi I'd like to work on this issue.
Is this still open and free for me to contribute.

**Comment by chlowell** [comment]
Yes, it's still open, and we haven't done any work to close it. It's been a low priority for us because duplicating test cases has been less painful than developing a better alternative. What do you have in mind for a solution?

**Comment by SiddhantJ19** [comment]
Hi @chlowell.
I'm new to open-source so it took me some time to go through the codebase. But as per my understanding I think we can refactor the sync parts into utility functions, context managers, etc.
That would definitely reduce the redundant parts and improve code sharing.
What do you say?

**Comment by chlowell** [comment]
It's true there's a lot of repetition across the Key Vault tests we could factor out into a shared test package (preparers, `VaultClient`, etc.). This issue is tracking something larger, the duplication of test cases themselves. For example, from `azure-keyvault-keys`:

```py
def test_sign_and_verify(self, vault_client, **kwargs):
    key_client = vault_client.keys

    key_name = self.get_resource_name("keysign")

    md = hashlib.sha256()
    md.update(self.plaintext)
    digest = md.digest()

    imported_key = self._import_test_key(key_client, key_name)
    crypto_client = key_client.get_cryptography_client(imported_key)

    key_id, algorithm, signature = crypto_client.sign(SignatureAlgorithm.rs256, digest)
    self.assertEqual(key_id, imported_key.id)

    verified = crypto_client.verify(algorithm, digest, signature)
    self.assertTrue(verified.result)
```

```py
async def test_sign_and_verify(self, vault_client, **kwargs):
    key_client = vault_client.keys

    key_name = self.get_resource_name("keysign")

    md = hashlib.sha256()
    md.update(self.plaintext)
    digest = md.digest()

    imported_key = await self._import_test_key(key_client, key_name)
    crypto_client = key_client.get_cryptography_client(imported_key)

    key_id, algorithm, signature = await crypto_client.sign(SignatureAlgorithm.rs256, digest)
    self.assertEqual(key_id, imported_key.id)

    verified = await crypto_client.verify(algorithm, digest, signature)
    self.assertTrue(verified.result)
```
I manually produced the async test by adding async/await to the sync one. That was tedious but easy, and we rarely write new cases, so building a generator hasn't been worth the effort.

Anyway, it's okay not to have a happy solution to the trickier problem, I sure don't 😁. You're thinking more about consolidating helpers and infrastructure code?

**Comment by saumyaborwankar** [comment]
Hi, I'd like to work on this issue.
I would like to contribute to this issue if it's still open? And if it's open where can I get more detail about the issue?

**Comment by chlowell** [comment]
Yes, it's still open, I don't know of any work in progress. All the details are in this issue. My last comment sums it up: our sync and async clients have the same API, so test case logic is duplicated--is there a reasonable way to instead write test cases once?

**Comment by SiddhantJ19** [comment]
Yes, go ahead. I haven't figured out anything yet. It'd be really good to see how you make it better.

**Comment by mr-nand** [comment]
Hi @chlowell 

I would love to work on this issue if nobody else is working on it currently?

**Comment by chlowell** [comment]
I don't know of any work in progress. It's a complicated problem without an obvious good solution, and still a low priority because the status quo isn't too painful. What do you have in mind?

**Comment by mr-nand** [comment]
I think that inheritance is the way to go, by creating a base class that will contain the shared code.

**Comment by chlowell** [comment]
I'm not sure I follow, can you describe it in more detail? What would be inherited in [my example above](https://github.com/Azure/azure-sdk-for-python/issues/5630#issuecomment-539131301)? The complete code is [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py#L95) and [here (async)](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py#L97).

**Comment by mr-nand** [comment]
@chlowell 

For instance, the CryptoClientTestsBase would contain only the test code implementation

```
class CryptoClientTestsBase:
    _sign_and_verify(self, vault_client, **kwargs):
        key_client = vault_client.keys
        
        key_name = self.get_resource_name("keysign")

        md = hashlib.sha256()
        ....
```
Then you can just make the CryptoClientTests class inherit from it  and call the inherited test code in the actual test case.

class CryptoClientTests(CryptoClientTestsBase, KeyVaultTestCase):
    @ResourceGroupPreparer(name_prefix=name_prefix)
    @VaultClientPreparer(permissions=NO_GET)
    def test_sign_and_verify(self, vault_client, **kwargs):
        self._sign_and_verify(vault_client, kwargs)

**Comment by chlowell** [comment]
How would you test the async client?

```py
class CryptoClientTests(CryptoClientTestsBase, AsyncKeyVaultTestCase):
    @ResourceGroupPreparer(name_prefix=name_prefix)
    @AsyncVaultClientPreparer(permissions=NO_GET)
    @AsyncKeyVaultTestCase.await_prepared_test
    async def test_sign_and_verify(self, vault_client, **kwargs):
        # TypeError: _sign_and_verify isn't awaitable
        await self._sign_and_verify(vault_client, **kwargs)

# assume we worked around the TypeError
class CryptoClientTestsBase:
    def _sign_and_verify(self, vault_client, **kwargs):
        ...
        # this is an async client
        crypto_client = vault_client.get_cryptography_client(imported_key)

        # so result is a coroutine
        result = crypto_client.sign(SignatureAlgorithm.rs256, digest)

        # and we get AttributeError here
        self.assertEqual(result.key_id, imported_key.id)
```

**Comment by mr-nand** [comment]
There are couple of solutions:

1. You can create a custom decorator to wrap a funtion to coroutine
2. Or you can use asyncio.coroutine

```
class CryptoClientTests(CryptoClientTestsBase, AsyncKeyVaultTestCase):
    @ResourceGroupPreparer(name_prefix=name_prefix)
    @AsyncVaultClientPreparer(permissions=NO_GET)
    @AsyncKeyVaultTestCase.await_prepared_test
    async def test_sign_and_verify(self, vault_client, **kwargs):
        # TypeError: _sign_and_verify isn't awaitable
        await asyncio.coroutine(self._sign_and_verify(vault_client, **kwargs))()

```

**Comment by chlowell** [comment]
Sure, there are reasonable ways to make code awaitable (though `asyncio.coroutine` is deprecated in 3.8), and passing an arbitrary client into a test is straightforward (handled today by `AsyncVaultClientPreparer`). But we'd still see the `AttributeError` because async client methods return coroutines, and the base code in this hypothetical must support non-async clients and Python 2.7. That's the hard problem for which I don't see an obvious reasonable solution 😊

**Comment by mr-nand** [comment]
@chlowell 

You can pass only a flag to 

`self._sign_and_verify(vault_client, async,  **kwargs) the method call.`

and after that conditionally deal with async and sync client

**Comment by chlowell** [comment]
How would you conditionally deal with a/sync calls in code supporting 2.7?

**Comment by brunojuliao** [comment]
I hope the script below helps :)
[create_sync_test.zip](https://github.com/Azure/azure-sdk-for-python/files/4208888/create_sync_test.zip)

I tried to find a way to avoid code duplication as requested, but this (a)sync seems we can't scape it. So, I thought you and your team could do something like create the async tests. They will be the base of the sync tests. Then, just call the attached script and voilà! The sync script will be created. Whenever an async test script is changed, just call it again and that's it. That was the simplest solution I could come up with :)

**Comment by chlowell** [comment]
I'm closing this because I doubt we'll find a general solution that's preferable to the status quo. Thank you everyone for the ideas.
