### ISSUE TITLE
Can't create SSD managed disks?

### ISSUE THREAD

**Issue by blueto01h** [Azure/azure-sdk-for-python#5692]
I have searched all documentation but just couldn't find a way to create a managed disk which is not a HDD. is this simply a missing feature or undocumented, or me being blind?

**Comment by lmazuel** [comment]
Hi @blueto01h 
The type of the disk is handled by the "sku"
https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2018_09_30.models.disksku?view=azure-python

> Possible values include: 'Standard_LRS', 'Premium_LRS', 'StandardSSD_LRS', 'UltraSSD_LRS'

```python
        async_creation = self.compute_client.disks.create_or_update(
            resource_group.name,
            'my_disk_name',
            {
                'location': location,
                'sku': 'StandardSSD_LRS',
                'disk_size_gb': 20,
                'creation_data': {
                    'create_option': DiskCreateOption.empty
                }
            }
        )
        disk_resource = async_creation.result()
```

Thanks!

**Comment by blueto01h** [comment]
thanks, i was able to create create an ssd disk using a dict  in the sku option like this
'sku' {
        'name': 'Premium_LRS'
    }
but not with a string as it threw an attribute error 
(AttributeError: 'str' object has no attribute 'get')
azure 4.0.0, azure-mgmt 4.0.0,msrest 0.6.4, mrestazure 0.6.0

but it works now :) i guess i was confused due to the previously used disk_type option
