### ISSUE TITLE
Deployment template launch fail missing error code or reason

### ISSUE THREAD

**Issue by lyan-git** [Azure/azure-sdk-for-python#577]
We found that when deployment template launch failed, the exception doesn't provide error code or reason.

Here is snippet of code:

        try:
            result = resource_client.deployments.create_or_update(
                    resource_group,
                    deployment_name,
                    properties=DeploymentProperties(
                        mode=DeploymentMode.incremental,
                        template=template_json,
                        parameters=param_json,
                    )
                ).result()

        except Exception as e:
            reason = str(e)
            self.logger.error(reason)
            raise ConnectToLegacyVNetErr(reason)

So the exception we captured was “Long running operation failed with status 'Failed'”. This doesn’t tell us exactly why the template deployment failed. Is there way to capture the reason of deployment failure?

Thanks.
Li

**Comment by lmazuel** [comment]
In this situation you will a ClourError:
https://msrestazure.readthedocs.org/en/latest/msrestazure.html#msrestazure.azure_exceptions.CloudError

You have two attributes:
- error, string of the error
- response, which is the requests.Response full last response where you should have to error

**Comment by lyan-git** [comment]
I dumped the CloudError exception here is the output:

{'error': <Response [200]>,
 'inner_exception': <Response [200]>,
 'message': "Long running operation failed with status 'Failed'",
 'request_id': None,
 'response': <Response [200]>,
 'status_code': 200}

Looks like it's not giving any detailed information of why the VM deployment template failed(in my case it should fail at the image storage).

Could you help to check if more detailed info can be provided/

Thanks.
Li

**Comment by lmazuel** [comment]
Hi,

You should be able to get the information you need using the `list` of `deployment_operations`
https://azure-sdk-for-python.readthedocs.org/en/latest/ref/azure.mgmt.resource.resources.operations.html#azure.mgmt.resource.resources.operations.DeploymentOperationsOperations.list

Which correspond to this REST API:
https://msdn.microsoft.com/en-us/library/azure/dn790518.aspx

Please tell me if it helps or if you don't get the information you need,
Thank you,

**Comment by lyan-git** [comment]
The list of deployment_operations works well, now we can have detail error if the template fails. Here is snippet of the code if any one is interested:
dep_itr=resource_client.deployment_operations.list(resource_group,
                              deployment_name)
...
And the detail error seems to reside at
dep_op.properties.status_message['error']['details'][0]

Thanks.
Li
