### ISSUE TITLE
Missing API Management SDK documentation

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#5775]
[Microsoft docs](https://docs.microsoft.com/en-us/python/azure/?view=azure-python) are missing API Management documentation pages.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @lmazuel

**Comment by lmazuel** [comment]
Hi @logachev 
I updated our doc CI with API Management, it should appear in "Others" soon:
https://docs.microsoft.com/en-us/python/api/overview/azure/other?view=azure-python

Once it's there, we will create the section in the left column.

Thanks!

**Comment by nickzhums** [comment]
@lmazuel Hi Laurent, just wanna check if  "API Management" section has been created yet?

**Comment by lmazuel** [comment]
Hi don't see it @docs-product @rloutlaw for insights

**Comment by xiangyan99** [comment]
@scbedd any ideas?

**Comment by logachev** [comment]
/unresolve

I still don't see it.

**Comment by jack-toussaint** [comment]
Has there been any progress on the documentation?

**Comment by xiangyan99** [comment]
https://docs.microsoft.com/azure/api-management/.
