### ISSUE TITLE
azure-eventhubs takes dependency on azure-storage-blob

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5776]
According to Johan, this requirement shouldn't be here.

[Line in setup.py](https://github.com/Azure/azure-sdk-for-python/blob/47fc3c4209545c8f29ae08aee7ee4b9871a0d613/sdk/eventhub/azure-eventhubs/setup.py#L68)

**Comment by lmazuel** [comment]
Fixed on master

(randomly found this issue, but since I'm here :p )
