### ISSUE TITLE
Any API to list out ARM supported VM locations and sizes?

### ISSUE THREAD

**Issue by lyan-git** [Azure/azure-sdk-for-python#578]
We found that some of the classical portal supported VM sizes such as ExtraSmall and etc are not supported in ARM and the locations supported in ARM is different too. 

Is there an API to get the above info? Right now we workaround by looking at the ARM portal and figure out what is supported.

Thanks.
Li

**Comment by lmazuel** [comment]
From a [compute client](https://azure-sdk-for-python.readthedocs.org/en/latest/resourcemanagementcomputenetwork.html), you have the `virtual_machine_sizes` attribute with a list function:
https://azure-sdk-for-python.readthedocs.org/en/latest/ref/azure.mgmt.compute.operations.html#azure.mgmt.compute.operations.VirtualMachineSizesOperations.list

**Comment by lyan-git** [comment]
Thanks. We are able to get vm sizes available to certain region through the above api.
How do we get supported regions for ARM?
And one comment on the APIs, I found region parameter require different format for different APIs, for this list function region need to be used with lowercase and without space such as 'westus'. But some of the APIs in ARM use original 'West US'. Either the document need to mention the format or the API parameter make it consistent.

Thanks.
Li.

Li

**Comment by huguesv** [comment]
For an example of enumerating locations:
https://github.com/Azure/azure-sdk-for-python/blob/master/examples/AzureResourceViewer/AzureResourceViewer/models.py#L147

**Comment by lmazuel** [comment]
I close this issue since it seems that we solved the question, but feel free to re-open it if needed.
