### ISSUE TITLE
HTTPRequestType has no attribute "headers"

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#5796]
The type variable `HTTPRequestType` defined in `azure.core.pipeline` lacks a `headers` attribute. Mypy therefore considers accessing the headers of a `PipelineRequest`'s inner HTTP request an error; see e.g. `BearerTokenCredentialPolicy` in `azure.core.pipeline.policies.authentication`.

**Comment by xiangyan99** [comment]
Discussed with Charles offline. Close
