### ISSUE TITLE
AsyncHTTPPolicy's next attribute is Optional[Any]

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#5797]
Looks like this should be `Optional[AsyncHTTPPolicy]` instead; would `next` ever be anything else?

**Comment by chlowell** [comment]
Reopening this for further consideration because it creates mypy errors in subclasses. For example, line 94 of this code gets "Item "None" of "Optional[Any]" has no attribute "send"":
https://github.com/Azure/azure-sdk-for-python/blob/dc95dbfc82b105e3e402fa7d42b6ecd1f3a9334e/sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_arc.py#L89-L94

This can of course be worked around in the subclass but it would be better for AsyncHTTPPolicy to have the correct type.
Similar to [HTTPPolicy](https://github.com/Azure/azure-sdk-for-python/blob/dc95dbfc82b105e3e402fa7d42b6ecd1f3a9334e/sdk/core/azure-core/azure/core/pipeline/policies/_base.py#L64), I think that type would be `Union[AsyncHTTPPolicy, AsyncHttpTransport]`, which aligns with actual usage and the class's documentation. However, fixing this is more complicated than just changing the type because AsyncRedirectPolicy and AsyncRetryPolicy transitively inherit HTTPPolicy.

**Comment by xiangyan99** [comment]
@chlowell We refactored HttpPolicy & AsyncHttpPolicy in https://github.com/Azure/azure-sdk-for-python/pull/15831. Now AsyncHTTPPolicy is not a sub-class of HTTPPolicy any longer. Could you help to check if this issue is fixed?

**Comment by chlowell** [comment]
Yes, that worked for my case.
