### ISSUE TITLE
Randomize Key Vault names in live test runs

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#5843]
When running live, each test creates (and destroys) a vault. The vault's name is a deterministic function of the test's name. This is necessary to ensure the tests can be run again from a recording, which enables running the test suite offline and is useful for debugging failed live tests.

However, because vault names must be globally unique, the deterministic naming prevents the test suite as a whole from successfully executing in parallel. That is to say if the tests are executing in the nightly pipeline while a developer is also running live tests, or two platforms in the nightly test matrix run simultaneously, or two developers run live tests simultaneously, someone's tests will fail.

**Comment by iscai-msft** [comment]
implemented already using md5 hashing so closing this
