### ISSUE TITLE
test_storage.py in azure-keyvault package cannot be re-recorded

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5858]
`azure-blob-storage` is now being loaded from local, which means that our tooling needs to leverage track 2 blob APIs. This fundamentally changes the `test_e2e` execution. Due to _that_ change, the test must be re-recorded. However, we cannot currently re-record the test due to ARM API constraints.

We leverage an `credential` to stand up the necessary resources prior to recording the tests.  [These](https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python) are the supported methods now. Note that `UserCredential` (how this test was _originally_ recorded) no longer can be leveraged to get a token from Azure. The user/pass login has been deprecated. I swapped the test to leverage a `ServicePrincipal` instead, and now all the test resources successfully update. However, when attempting to execute the keyvault function `set_storage_account` in the `test_e2e` test within `/sdk/keyvault/azure-keyvault/tests/test_storage.py`, we get a 403 FORBIDDEN error. This is due to the fact that this keyvault function can _only_ execute with a `UserCredential`!  We can no longer USE `UserCredential` to get a token from Azure, so we can't record this test again. 

I am skipping this test, also mentioning the issue in the comment on `@pytest.mark.skip()`

Note that it is only necessary to re-record in the `storage-track2` branch. [Relevant PR](https://github.com/Azure/azure-sdk-for-python/pull/5810) that resolves broken tests due to `azure-storage-blob`

**Comment by kurtzeborn** [comment]
We discussed this and the result was that you should just delete the test.

**Comment by AlexGhiondea** [comment]
@scbedd will you remove the tests or do you want us to do that? 

/cc @chlowell

**Comment by scbedd** [comment]
We're actually blowing azure-keyvault away entirely with this latest PR. I will close this issue when that action is completed.

**Comment by scbedd** [comment]
It's done.
