### ISSUE TITLE
AutoRest adding commits where no sdk_packaging.toml present

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#5919]
Reference this [pr.](https://github.com/Azure/azure-sdk-for-python/pull/5918/files)

My understanding was that if there is an sdk_packaging.tml present, unless it is explicitly disabled AutoRest will do it's work. However, for packages where this are _no_ sdk_packaging.toml present, it shouldn't be adding one.

Will reach out to @lmazuel and find out why it's running on folders that have no `sdk_packaging.toml` present. If that's the default behavior, we'll probably need to adjust this behavior.

**Comment by lmazuel** [comment]
I think we can close this right now, to be honest there is way more mgmt package in automation that there is data-plane with it, so if we want to be fair to usage, automation activated by default makes sense to me.
