### ISSUE TITLE
 AADSTS50059 when using AD User/Password 

### ISSUE THREAD

**Issue by one1zero1one** [Azure/azure-sdk-for-python#594]
If the Organizational Account is a guest in another tenant, or multiple tenants, then you must specify the specific **tenant** that you want the token issued by, yet this is not currently possible.

```
from azure.common.credentials import UserPassCredentials
credentials = UserPassCredentials(
    'user@domain.com',    # Your new user
    'my_smart_password',  # Your password
    
)
```

**Comment by lmazuel** [comment]
Hi @one1zero1one 

The full documentation of `UserPassCredentials` is available here:
http://msrestazure.readthedocs.io/en/latest/msrestazure.html#msrestazure.azure_active_directory.UserPassCredentials

You can see that the kwargs accept the `tenant` parameter (which is at `common` by default)

**Comment by one1zero1one** [comment]
Thank you for the clarification @lmazuel , I came to this from the ansible azure_rm_resourcegroup module - I'll do the follow up there.
