### ISSUE TITLE
Bloated zip due to historical test data

### ISSUE THREAD

**Issue by crazyglasses** [Azure/azure-sdk-for-python#5957]
Due to historical test data, the size of the uncompressed file is bloated which causes issue in  uploading the package to functions ( lambda ) . Might consider adding it to .gitignore

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @lmazuel

**Comment by lmazuel** [comment]
Hi @crazyglasses 
I have no idea what you are talking about :(. Could you precise what "file" you are mentioning? What "zip" is bloated? ...
Thanks

**Comment by RodgeFu** [comment]
Close old issues without update for 3+ month. Feel free to reopen if needed. thanks.
