### ISSUE TITLE
Does the SDK support Billing API?

### ISSUE THREAD

**Issue by rockypandalu** [Azure/azure-sdk-for-python#600]
Hi, I want to get the resource usage data form my Azure VM, and I think I need to use the Billing API (Resource Usage API) to do this. I am wondering whether there is any class that support the Billing API in the python SDK?
Appreciate for the help!

**Comment by lmazuel** [comment]
Hi,

I will publish a preview package called azure-mgmt-commerce this week. I keep this issue open till them, and do not hesitate to provide feedback if you have issues on it!

Thank you!

**Comment by rockypandalu** [comment]
Thanks a lot, looking forward to your new package!

**Comment by lmazuel** [comment]
Package just released:
https://pypi.python.org/pypi/azure-mgmt-commerce/0.30.0rc4

As part of the azure 2.0.0rc4 distribution:
https://pypi.python.org/pypi/azure/2.0.0rc4

Sample:
http://azure-sdk-for-python.readthedocs.io/en/latest/resourcemanagementcommerce.html

This is a preview package. Please fill an issue if you encounter difficulties.

Thank you!

**Comment by rockypandalu** [comment]
Dear Mr. Imazuel,
Thank you so much for the package. I can now download some object using your package. But I am wondering how can I load the data inside the object. For example, the usage data I can retrieve using your package is like 
<azure.mgmt.commerce.models.usage_aggregation_paged.UsageAggregationPaged object at 0x7f593994cd90>
But I do not know how can I get the understandable data from this object. Could you please give me some instruction?
Thank you so much!
Yan
