### ISSUE TITLE
Revisit default pipeline definition

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#6012]
The default pipeline defined in `PipelineClient` needs some revision. In particular, it doesn't include a proxy policy, and the authentication policy may belong after the retry policy.

**Comment by xiangyan99** [comment]
We need to review before we update code

**Comment by johanste** [comment]
All pipelines should include a proxy policy. This includes management/control plane/autogenerated clients. And, yes the authentication policy should be after the retry policy.

**Comment by xiangyan99** [comment]
Fixed
