### ISSUE TITLE
Support get_client_from_cli_profile with StorageService

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-sdk-for-python#6041]
I'm trying to use `get_client_from_cli_profile`  (as specified by the [documentation](https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-cli)), but I'm getting an error. This is my code:
```
from azure.common.client_factory import get_client_from_cli_profile
from azure.storage.common.storageclient import StorageClient

client = get_client_from_cli_profile(StorageClient)
```
And this is the error:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    client = get_client_from_cli_profile(StorageClient)
  File "<>/lib/python3.7/site-packages/azure/common/client_factory.py", line 100, in get_client_from_cli_profile
    return _instantiate_client(client_class, **parameters)
  File "<>/lib/python3.7/site-packages/azure/common/client_factory.py", line 35, in _instantiate_client
    return client_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'credentials'
```
I think this is because `StorageService` does not support `credentials` as one of it's arguments. After reading the [CLI code](https://github.com/Azure/azure-cli/blob/5c7ddcb1066236c3d6a634c50428fc0f2a94fce3/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L149), look like an access key or SAS is required.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by lmazuel** [comment]
Hi @omerlh 
You're right, this factory doesn't support the Storage client yet. That's a vliad work item I'm adding in the backlog. In the meantime, if you have mgmt access you can provide download the key and use it to create the client.

**Comment by lmazuel** [comment]
Supported in https://pypi.org/project/azure-common/1.1.24/ for storage SDKs after v12.
