### ISSUE TITLE
Installation error on jetson nano devices

### ISSUE THREAD

**Issue by sojohan** [Azure/azure-sdk-for-python#6050]
Hi experts 

When I try to install azure-eventhub I get an error during the install of uamqp. Here is the error message:

RROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-o68px1x_/uamqp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-agjlsgeo/install-record.txt --single-version-externally-managed --compile:

Any hints?
Thanks,
sojohan

**Comment by kurtzeborn** [comment]
@loarabia suggested that @wickste might have some insights on this...

CC: @jfggdl

**Comment by sojohan** [comment]
Let me know if you want the full list of errors.......

**Comment by loarabia** [comment]
@sojohn. What distro and version of Linux are you running? I'm wondering if it supports ManyWheel. We've seen this in other IoT scenarios like Alpine Linux. [uamqp Issue 51](https://github.com/Azure/azure-uamqp-python/issues/51)

If there are other errors, it could be good to paste in or attach a zip for our reference.

@annatisch any thoughts on this ?

**Comment by sojohan** [comment]
Hi Loarabia

By magic I was now able to install the package azure-eventhubs. On the Nvidia Jetson Nano. 

I used the following command:

sudo  apt-get install -y build-essential libssl-dev uuid-dev cmake libcurl4-openssl-dev pkg-config 

I then re-started the board and used:

sudo pip3 install azure-eventhubs

Thanks, 

sojohans

**Comment by loarabia** [comment]
Thanks @sojohan for letting us know. I'll close this issue out but for my own reference I'd still be curious to know if the Linux distro on your Jetson nano is L4T or if you used a custom one.
