### ISSUE TITLE
Avro EventData silently dropped

### ISSUE THREAD

**Issue by jacobpledger** [Azure/azure-sdk-for-python#6076]
Using azure-eventhub 1.3.1, binary Avro messages fail to reach Event Hub properly. The same code sending a list of strings works - it's basically identical to your sample code, but when I encode the data into Avro, the messages captured in Azure are 508 byte empty files. No errors are thrown.

**Comment by lmazuel** [comment]
@annatisch ?

**Comment by annatisch** [comment]
Hi @jacobpledger - thanks for the report!
I'm afraid I have no experience/knowledge of Avro - could you please provide us with some sample code that generates these binary messages so that we can reproduce the issue?

Adding @yunhaoling and @YijunXieMS 

Thanks!

**Comment by yunhaoling** [comment]
Hi @jacobpledger , I'm clearing up old issues.
Please feel free to re-open it and provide us with code that causes the error.

We've recently released azure-eventhub 5.0.0, please try the latest sdk to see if problem still exists.
