### ISSUE TITLE
azure.mgmt.costmanagement ExportRecurrencePeriod doesn't initialize 'to' parameter

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-sdk-for-python#6100]
Calling Azure Cost Management exports.create_or_update() fails if ExportRecurrencePeriod() does not set a "to" parameter which is supposed to be optional. It looks like the "to" date is uninitialized and gets set to a date in the past.

**Comment by lmazuel** [comment]
Thansk @gbowerman 
That would be a s Swagger issue here then:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-01-01/costmanagement.json#L1223

**Comment by lmazuel** [comment]
Adding @melmullen

**Comment by xiangyan99** [comment]
@gbowerman latest azure-mgmt-costmanagement is 3.0.0. Does it work for you?
