### ISSUE TITLE
azure.mgmt.costmanagement create_or_update() operation fails with 401 unauthorized if authenticated as a service principal

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-sdk-for-python#6101]
azure.mgmt.costmanagement create_or_update() operation fails with 401 unauthroized if authenticated as a service principal, but works fine if authenticated as an interactive user. Repro provided by email.

Traceback (most recent call last):
  File ".\setup_cost_export.py", line 66, in <module>
    main()
  File ".\setup_cost_export.py", line 62, in main
    export = cclient.exports.create_or_update(scope, export_name, parameters)
  File "C:\Users\guybo\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\mgmt\costmanagement\operations\exports_operations.py", line 238, in create_or_update
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.costmanagement.models.error_response_py3.ErrorResponseException: (401) Unauthorized (Request ID: 658c30ab-ec24-487d-8a51-81f873e35196)

**Comment by lmazuel** [comment]
Hi @gbowerman 
Tagging @melmullen to the rescue

**Comment by changlong-liu** [comment]
Hi @Abyssknight , help to have a try on this.

**Comment by xiangyan99** [comment]
latest azure-mgmt-costmanagement is 3.0.0. Does it work for you?
