### ISSUE TITLE
Help setting cloud_roleName using Azure SDK for Python

### ISSUE THREAD

**Issue by bulkware** [Azure/azure-sdk-for-python#6103]
I need help setting the cloud_roleName while retrieving metrics using the Azure SDK for Python. I found some links where this is done using different programming languages or using the Application Insights SDK:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-map#set-cloud-role-name
https://github.com/microsoft/ApplicationInsights-Python/issues/147
https://westerndevs.com/app_insights_appname/

I would like to know how I can filter metrics and use this setting to do it, if possible. If this setting is only available when using the Application Insights SDK for Python, please be kind and let me know.

Thanks in advance.

**Comment by lmazuel** [comment]
Hi @bulkware 
That's a good question, I unfortunately don't know the answer which is Azure specific and not Python specific. Maybe @tjprescott or @alexeldeib would know?

**Comment by morgangrobin** [comment]
Yes, you would need to use the [App Insights Python SDK](https://github.com/Microsoft/ApplicationInsights-Python) to set the cloud role name. Please note that this is not currently a supported SDK and not recommended for production use.
