### ISSUE TITLE
Azure Container Services missing from SDK

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-sdk-for-python#611]
The other SDKs supply a "composite swagger" flag in their config file (here: https://github.com/Azure/azure-sdk-for-python/blob/master/swagger_to_sdk_config.json#L33) which picks up both the compute and container services files.  That flag is missing in the python SDK (node has it).

**Comment by lmazuel** [comment]
You will have it in a few seconds :). I was about publishing RC4 and this is part of it.

**Comment by lmazuel** [comment]
Released as Compute 0.30.0rc4
https://pypi.python.org/pypi/azure-mgmt-compute/0.30.0rc4

Please fill  an issue if something wrong :)
