### ISSUE TITLE
Re-record single hdinsight test leveraging keyvault

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#6117]
Exact test skip that needs to be updated [here.](https://github.com/Azure/azure-sdk-for-python/blob/1ee4f3697701804a97c17cfadd7d8bcfcd320dbb/sdk/hdinsight/azure-mgmt-hdinsight/test/test_mgmt_hdinsight.py#L136)

Going to do this locally with a combination of `EnvironmentCredential` for the keyvault `KeyClient` interactions + a standard `mgmt_settings_real.py` for the management setup that it currently runs.

**Comment by scbedd** [comment]
@mayurid This slipped my mind due to the chaos of the releases. We skip a single test because we need to

**Comment by aim-for-better** [comment]
We will fix it soon.
