### ISSUE TITLE
ImportError: No module named 'azureml.train.automl'

### ISSUE THREAD

**Issue by kritdikoon** [Azure/azure-sdk-for-python#6120]
I have installed Azure SDK in Databricks as below.

Source: Upload Python Egg or PyPi
PyPi Name: azureml-sdk[databricks]
Select Install Library

I can confirm SDK version.
However, I cannot import "azureml.train.automl'.
What should I do to solve this issue?

PS, I did the same thing yesterday and there is no error.

==============================

print("SDK version:", azureml.core.VERSION)

SDK version: 1.0.45

===============================

import azureml.core
from azureml.core.experiment import Experiment
from azureml.core.workspace import Workspace
from azureml.train.automl import AutoMLConfig
from azureml.train.automl.run import AutoMLRun

print("SDK version:", azureml.core.VERSION)

Failure while loading azureml_run_type_providers. Failed to load entrypoint hyperdrive = azureml.train.hyperdrive:HyperDriveRun._from_run_dto with exception (idna 2.1 (/databricks/python3/lib/python3.5/site-packages), Requirement.parse('idna<2.9,>=2.5'), {'requests'}).
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.StepRun = azureml.pipeline.core:StepRun._from_dto with exception (idna 2.1 (/databricks/python3/lib/python3.5/site-packages), Requirement.parse('idna<2.9,>=2.5'), {'requests'}).
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.ReusedStepRun = azureml.pipeline.core:StepRun._from_reused_dto with exception (idna 2.1 (/databricks/python3/lib/python3.5/site-packages), Requirement.parse('idna<2.9,>=2.5'), {'requests'}).
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.PipelineRun = azureml.pipeline.core:PipelineRun._from_dto with exception (idna 2.1 (/databricks/python3/lib/python3.5/site-packages), Requirement.parse('idna<2.9,>=2.5'), {'requests'}).
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.scriptrun = azureml.core.script_run:ScriptRun._from_run_dto with exception (idna 2.1 (/databricks/python3/lib/python3.5/site-packages), Requirement.parse('idna<2.9,>=2.5'), {'requests'}).
ImportError: No module named 'azureml.train.automl'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command-3452817210161354> in <module>()
      2 from azureml.core.experiment import Experiment
      3 from azureml.core.workspace import Workspace
----> 4 from azureml.train.automl import AutoMLConfig
      5 from azureml.train.automl.run import AutoMLRun
      6 

ImportError: No module named 'azureml.train.automl'

**Comment by lmazuel** [comment]
Hi @kritdikoon 
I'm sorry, but the AzureML team is not integrated in this repo and have their own issues system:
https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureMachineLearningService

Thank you

**Comment by rodneyjoyce** [comment]
This is the wrong place, but you can get around this with an earlier version of the Azure Machine Learning SDK - see https://social.technet.microsoft.com/Forums/scriptcenter/en-US/ffd021cb-6828-41e5-b87f-8da276e9766e/databricks-importerror-no-module-named-azuremltrainautoml?forum=AzureMachineLearningService
