### ISSUE TITLE
how to use List alerts method in azure-mgmt-security package?

### ISSUE THREAD

**Issue by imeya** [Azure/azure-sdk-for-python#6124]
I want to list azure security center alerts by using azure-mgmt-security package, but I don't know how to configure the [AlertsOperations()](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/security/azure-mgmt-security/azure/mgmt/security/operations/alerts_operations.py#L19) methods, could you please give me some guides? Thank you.

Here is my code:

```
from azure.mgmt.security.operations import alerts_operations

#I don't know how to configure AlertsOperations method
client = alerts_operations.AlertsOperations()
client.list()
```

**Comment by lmazuel** [comment]
Hi @imeya 
You don't create directly this object, you create a client first:
```python
from azure.mgmt.security import SecurityCenter

client = SecurityCenter(credentials, subscription_id, asc_location="centralus")
client.alerts.list() # Returns an iterable object, use a list() if you want it as a list
```

For more details on how to create a credentials class, please refer to this doc:
https://docs.microsoft.com/python/azure/python-sdk-azure-authenticate

Thanks,
