### ISSUE TITLE
Guard typing imports

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#6133]
`typing` isn't in azure-core's `install_requires` and isn't part of 2.7's standard library, so the first `from typing import ...` can raise on 2.7. Fix would be to either take the dependency on `typing` or guard imports e.g.:
```py
try:
    from typing import TYPE_CHECKING
except ImportError:
    TYPE_CHECKING = False

if TYPE_CHECKING:
    # pylint:disable=unused-import
    from typing import Any, Mapping, Optional, Type
```

**Comment by mayurid** [comment]
Azure core already introduced this dependency. Per the conversation with @johanste each library should have its own dependency (aka not reply on core to bring it)

**Comment by lmazuel** [comment]
Actually as of today on the repo all packages have a dependency on typing already :)
