### ISSUE TITLE
Reorder azure-core version specifiers

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#6154]
To allow libraries to pass validation by analyze_deps, the frozen version for azure-core in shared_requirements must be "azure-core<2.0.0,>=1.0.0b1", and libraries must match it exactly. Placing the specifiers in ascending order, i.e. "azure-core>=1.0.0b1,<2.0.0" would be canonical, although setuptools considers the strings equivalent. We should prefer the canonical ordering once #6153 is resolved.

**Comment by mayurid** [comment]
Ideally this should not matter and this may just be a CI issue which is #6153. Please reopen if this is something we want addressed
