### ISSUE TITLE
Inconsistent dependencies in azure-cosmos

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-python#6161]
Requirement 'six>=1.6' is declared in the following libraries but has not been frozen:
  * azure-cosmos

The following libraries declare requirement 'requests>=2.10.0' which does not match the frozen requirement 'requests>=2.18.4':
  * azure-cosmos

**Comment by bryevdv** [comment]
FWIW I was running with 

* requests==2.21.0
* six==1.12

when working on Cosmos, so I would not expect any issues with 'requests>=2.18.4' I don't know how to "freeze" six

**Comment by bsiegel** [comment]
Pushed 9501455 to #6160 which should resolve this issue.
