### ISSUE TITLE
[azure-storage] Add devops step for validating shared code

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#6167]
The 3 storage SDKs have a large internal module of shared code.
We should add a CI step to validate the each SDK has the most up-to-date version of the shared module.
The CI step should also validate the error code enum against the swagger specs.

**Comment by scbedd** [comment]
Rakshith swung by to give some additional details here. I can't get to this before preview 4, but given that, here's my thoughts.

Folder Structure for Storage `_shared` modules:

```
sdk/storage/azure-storage-blob/
   azure/
       storage/
          _shared      
```
The above `_shared` occurs in all 3 of the storage libaries. We need to validate that all contents are identical between these 3 packages.

I see this being possible in a few ways (not an exhaustive list):
1) Adding an additional step to `build-test.yml` that _always_ runs a script that compares all `_shared` folders within a servicedir.
2) Add additional steps to the `ci.yml` for the storage 
3) Add a lookup file w/ `run X custom scripts per service dir check`. Something along the lines of:
> in `sdk/storage` ci runs, add this additional custom step.

**Comment by scbedd** [comment]
`azure-storage-Y/_shared` should be autodetected, and then ensure that all values of `Y` would be compared.

`azure-storage-file/queue/blob` all the _shared should be exactly the same.

**Comment by tasherif-msft** [comment]
Hi @scbedd it doesn't seem that this was ever shipped? any updates on this?

**Comment by annatisch** [comment]
Bringing this thread back to life again.
Another approach we can look into is whether the shared directory can be maintained separately, in a single place in the repo, where it can be vendored into the packages as part of a pipeline.
In order for that to work, work would need to be done to make sure the shared directory is truly identical between all Storage SDKs.

**Comment by annatisch** [comment]
This is now an issue across several SDKs - closing this in favour of a new issue that covers the broader scope: #28232
