### ISSUE TITLE
how to enable TLSv1.2 when using KeyVaultClient to connect to Azure Key Vault via auzre keyvault sdk for python

### ISSUE THREAD

**Issue by VampireDaniel** [Azure/azure-sdk-for-python#6168]
I dont find any special param to set the ssl/tls version
I am refering this [article](https://docs.microsoft.com/en-us/python/api/overview/azure/key-vault?view=azure-python#examples) to setup the python app, and there is nothing realtive to ssl/tls version, By default its TLSv1
![image](https://user-images.githubusercontent.com/12490709/60329205-76f53f80-99c2-11e9-8a92-5ee5785eeede.png)

![image](https://user-images.githubusercontent.com/12490709/60329388-d6534f80-99c2-11e9-90a7-356116758777.png)

**Comment by loarabia** [comment]
Hi @VampireDaniel, thanks for reporting this we'll have someone on the team take a look.

**Comment by VampireDaniel** [comment]
Hi @loarabia , thanks for replying. 
I really desire for this TLS v1.2 feature, may I have an ETA for this?

**Comment by johanste** [comment]
This should already be supported. I'll have to set up a test environment to verify, but in the meantime, can you run `python -c "import requests; print(requests.get('https://www.howsmyssl.com/a/check').json()['tls_version'])"` to see if TLS 1,2 is supported on your system.

**Comment by VampireDaniel** [comment]
thanks @johanste . one more thing is, the azure portal for keyvault don’t provide the option for me to set the minimal TLS version which don’t like other PaaS.

get response from chrome
```{
"given_cipher_suites": [
"TLS_GREASE_IS_THE_WORD_3A",
"TLS_AES_128_GCM_SHA256",
"TLS_AES_256_GCM_SHA384",
"TLS_CHACHA20_POLY1305_SHA256",
"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
"TLS_RSA_WITH_AES_128_GCM_SHA256",
"TLS_RSA_WITH_AES_256_GCM_SHA384",
"TLS_RSA_WITH_AES_128_CBC_SHA",
"TLS_RSA_WITH_AES_256_CBC_SHA",
"TLS_RSA_WITH_3DES_EDE_CBC_SHA"
],
"ephemeral_keys_supported": true,
"session_ticket_supported": true,
"tls_compression_supported": false,
"unknown_cipher_suite_supported": false,
"beast_vuln": false,
"able_to_detect_n_minus_one_splitting": false,
"insecure_cipher_suites": {},
"tls_version": "TLS 1.3",
"rating": "Probably Okay"
}```

response in python venv
```
print(requests.get('https://www.howsmyssl.com/a/check').json())
{u'unknown_cipher_suite_supported': False, u'able_to_detect_n_minus_one_splitting': True, u'rating': u'Bad', u'tls_compression_supported': False, u'tls_version': u'TLS 1.0', u'insecure_cipher_suites': {}, u'session_ticket_supported': True, u'given_cipher_suites': [u'TLS_DHE_RSA_WITH_AES_256_CBC_SHA', u'TLS_DHE_DSS_WITH_AES_256_CBC_SHA', u'TLS_DHE_RSA_WITH_AES_128_CBC_SHA', u'TLS_DHE_DSS_WITH_AES_128_CBC_SHA', u'TLS_RSA_WITH_AES_256_CBC_SHA', u'TLS_RSA_WITH_AES_128_CBC_SHA', u'TLS_EMPTY_RENEGOTIATION_INFO_SCSV'], u'ephemeral_keys_supported': True, u'beast_vuln': False}

```

**Comment by johanste** [comment]
Are you by any chance using the system installed version of Python on a Mac? And which Python version are you using - and from where did you install it from? Can you run: 

```python
python -c "import ssl; print ssl.OPENSSL_VERSION"
```
to check the version of openssl? 

Older versions of openssl do not support TLS1.2. Something which has been problematic on some installs.

**Comment by VampireDaniel** [comment]
I am using venv and created Python 2.7.

the result of command is 
`import ssl; print ssl.OPENSSL_VERSION
`

**Comment by johanste** [comment]
This [version of openssl does not support TLS1.2](https://stackoverflow.com/questions/48178052/when-was-tls-1-2-support-added-to-openssl). Which explains why you end up with TLS 1.1. 

Are you looking for a way for the client to fail unless it supports TLS 1.2 (refuse downgrade of the version) or to make your client actually support TLS 1.2?

Some background: http://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html

**Comment by VampireDaniel** [comment]
@johanste sorry I got confused, I am talking about the TLSv setting in auzre keyvault sdk for python. I dont see any special param to set the ssl/tls version in auzre keyvault sdk. 
also the azure portal for keyvault don’t provide the option for me to set the minimal TLS version which don’t like other PaaS.

**Comment by johanste** [comment]
The `azure-keyvault` package for Python is using `[requests`](https://2.python-requests.org/en/master/) under the hood, It, in turn, will use openssl. Depending on which version of and how you installed Python, it will end up calling into different versions of openssl.

I don't have an answer as to what the service does (or does not) support w. regards to disabling TLS <=1.1. I've pinged some people internally who can hopefully provide more information.

**Comment by VampireDaniel** [comment]
@johanste got it, so how to set tls version in azure-keyvault package for Python?

**Comment by johanste** [comment]
As I mentioned above, by default, it will be negotiated to use the best (latest) possible version supported by both the client and the service. So if you update your Python installation so that it uses a later version of openssl, it will start using TLS 1.2.

If you want to set the lowest version that your client application is willing to use, it is a bit more trickery involved. The current version of the keyvault libraries don't have an explicit knob/parameter to do so. You'd have to [create a `requests.adapters.HTTPAdapter` and configure your pool manager](https://2.python-requests.org//en/latest/user/advanced/#example-specific-ssl-version), but I don't see a good way to get access to the `requests.Session()` instance that you'd need to mount it to...

Incidentally, we just released a preview of the (next generation of client libraries for Python)[https://aka.ms/azure-sdk-preview1-python], which would allow you to specify a specific `requests.Session()` when you create your client, and thus would allow you to provide a specific `requests.Session()` instance...

**Comment by VampireDaniel** [comment]
@johanste After install latest requests, its still using TLSv1.
![image](https://user-images.githubusercontent.com/12490709/61015281-7181f700-a3bd-11e9-97a8-9a0ea54059ad.png)

![image](https://user-images.githubusercontent.com/12490709/61015346-d1789d80-a3bd-11e9-815a-62da84b19927.png)

**Comment by johanste** [comment]
You need to make sure that the `openssl` version is 1.0.1 or higher (actually, you probably want it even later than that). Installing `requests` will not update the `openssl` version. 

[This](https://stackoverflow.com/questions/18752409/updating-openssl-in-python-2-7) post on stackoverflow has some information on how to update openssl on various platforms.

**Comment by VampireDaniel** [comment]
Thanks a lot, I can get tlsv1.2 now
![image](https://user-images.githubusercontent.com/12490709/61192286-da32e180-a6e5-11e9-8411-b8baa4225abe.png)

**Comment by johanste** [comment]
Closing as the issue has been resolved..

**Comment by som-nitjsr** [comment]
> Thanks a lot, I can get tlsv1.2 now
> ![image](https://user-images.githubusercontent.com/12490709/61192428-cb006380-a6e6-11e9-84c3-068f9195d734.png)

Hi which tool you are using to capture this.

**Comment by som-nitjsr** [comment]
> Thanks a lot, I can get tlsv1.2 now
> ![image](https://user-images.githubusercontent.com/12490709/61192428-cb006380-a6e6-11e9-84c3-068f9195d734.png)

Hi which tool you are uisng to capture this.
