### ISSUE TITLE
VM create error

### ISSUE THREAD

**Issue by th3v0ice** [Azure/azure-sdk-for-python#617]
Hello everyone. 

While I was using the RC3 version without problems, with RC4 I am getting this error:

public_ip_address=azure.mgmt.network.models.ResourceId(
AttributeError: 'module' object has no attribute 'ResourceId'

The newest release candidate was installed with pip. Both "pip install azure==2.0.0rc4" and "pip install --pre azure" are giving this error. Can You please resolve this?

**Comment by lmazuel** [comment]
Hi,

Could you give more details about the exact operation you call here?

Thank you,

**Comment by th3v0ice** [comment]
Hi Imazuel,

Sure, I am just calling slightly modified "create_network_interface" from the documentation. Here is the code  

```
	def create_network_interface(self,network_client, region, group_name, interface_name,network_name, subnet_name, ip_name):
	
		result = self.network_client.virtual_networks.create_or_update(
			group_name,
			network_name,
			azure.mgmt.network.models.VirtualNetwork(
				location=region,
				address_space=azure.mgmt.network.models.AddressSpace(
						address_prefixes=[
						'10.0.0.0/16',
						],
				),
				subnets=[
					azure.mgmt.network.models.Subnet(
						name=subnet_name,
						address_prefix='10.0.0.0/24',
					),
				],
			),
		)
		result.wait()
		subnet = self.network_client.subnets.get(group_name, network_name, subnet_name)
	
		result = self.network_client.public_ip_addresses.create_or_update(
			group_name,
			ip_name,
			azure.mgmt.network.models.PublicIPAddress(
				location=region,
				public_ip_allocation_method=azure.mgmt.network.models.IPAllocationMethod.dynamic,
				idle_timeout_in_minutes=4,
			),
		)
		result.wait()
		public_ip_address = self.network_client.public_ip_addresses.get(group_name, ip_name)
		public_ip_id = public_ip_address.id
	
		result = self.network_client.network_interfaces.create_or_update(
			group_name,
			interface_name,
			azure.mgmt.network.models.NetworkInterface(
				location=region,
				ip_configurations=[
					azure.mgmt.network.models.NetworkInterfaceIPConfiguration(
						name='default',
						private_ip_allocation_method=azure.mgmt.network.models.IPAllocationMethod.dynamic,
						subnet=subnet,
						public_ip_address=azure.mgmt.network.models.ResourceId(
							id=public_ip_id,
						),
					),
				],
			),
		)
		result.wait()
		network_interface = self.network_client.network_interfaces.get(
			group_name,
			interface_name,
		)
		
		return network_interface.id
```

The rest of the code is also very similar to the one from the documentation. 
Thanks.

**Comment by lmazuel** [comment]
`public_ip_address` takes a PublicIPAddress object in parameter:
https://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.network.models.html#azure.mgmt.network.models.PublicIPAddress

But it was always the case in RC3:
http://azure-sdk-for-python.readthedocs.io/en/v2.0.0rc3/ref/azure.mgmt.network.models.html#azure.mgmt.network.models.NetworkInterfaceIPConfiguration

It wasn't suppose to work in RC3 :). Replace by PublicIPAddress and you are good.

**Comment by th3v0ice** [comment]
Thank You for the answer :). That indeed removed the error that I was getting. However newly created VM's are created without any IP address. Status for the VM just says "Failed", and as far as Audit logs are concerned there was no error. What could be the problem?

**Comment by th3v0ice** [comment]
Thank You very much. That indeed solved my problem.  :) One side question, why is in the documentation and the code samples "ResourceId" put instead of the "PublicIPAddress"?

**Comment by lmazuel** [comment]
Good catch with the doc, it's an error from the previous 1.x versions. I will fix.

Thank you!
