### ISSUE TITLE
Add wheel checks to release process (or interim step in build)

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#6174]
In our most recent release, we were bit by the fact that we uploaded a wheel that was _not_ universal.

This is due to the fact that there was a missing configuration file `setup.cfg` with `universal=1` that causes the build system to properly build a universal wheel. [Example.](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/setup.cfg)

So how do we avoid this situation again?
1) `update_pr` is not used for our data plane. We should adjust and use it for automagic on minute configuration like this.
2) Add a final step to test the code using the `wheels` themselves, versus the editable install
    * A simple check on whether the package will install successfully will also catch these errors
3) Explicitly force packages to universal in twine upload step

**Comment by chlowell** [comment]
If we want to enforce universal wheels for everything, it's a command line flag as well: `python setup.py bdist_wheel --universal`

**Comment by kurtzeborn** [comment]
@chlowell's suggestion fixes the immediate problem being pointed out here, but more generally, we think that the smoke tests that @JonathanCrd is working on (#6297) will address these types of problems by testing against the actual wheel package.

**Comment by kurtzeborn** [comment]
Per @scbedd this is actually done now by virtue of the TOX work.
