### ISSUE TITLE
Example for deploying template from file

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-sdk-for-python#618]
Hi, 
Whatever I do, I cannot do file.read() on a json template and create a deployment from it. I'm getting "request content was invalid and could not be serialized". When trying the exact same template in the azure portal everything works, so there's nothing wrong with my template. This was working before I updated to the 2.0.0-wave of the python module. Could you please provide a working example of how to load a json template and deploy it?

**Comment by lmazuel** [comment]
Hi,
This could help:
http://azure-sdk-for-python.readthedocs.io/en/latest/resourcemanagement.html#create-deployment-from-template

I guess you give the template as a string, but we actually take a dict as a template. Add a simple `json.loads` should be enough :)

**Comment by trondhindenes** [comment]
okay, I'll try parsing the file with json.loads instead of just sending the string streight to the def. I guess that's a breaking change from the earlier python versions.

**Comment by lmazuel** [comment]
Yes, in 1.x versions of the SDK we were using a string. Since the 2.x, it's directly a dict.
I wrote this here:
https://github.com/Azure/azure-sdk-for-python/wiki/Migrate-from-1.0.0-ARM-preview-to-2.0.0rc1#models

But it's not really easy to find I agree...

**Comment by trondhindenes** [comment]
:-) no worries.

**Comment by lmazuel** [comment]
Hi @trondhindenes 

Did you have the expected answer, can we close this issue?
Thank you!

**Comment by lmazuel** [comment]
Close this bug now, feel free to open a new issue if you have another problem!
Thank you!
