### ISSUE TITLE
Question about load data got from Billing API

### ISSUE THREAD

**Issue by rockypandalu** [Azure/azure-sdk-for-python#620]
Dear Mr. Imazuel,
Thank you so much for the package. I can now download some object using your package. But I am wondering how can I load the data inside the object. For example, the usage data I can retrieve using your package is like 

azure.mgmt.commerce.models.usage_aggregation_paged.UsageAggregationPaged object at 0x7f593994cd90

But I do not know how can I get the understandable data from this object. Could you please give me some instruction?
Thank you so much!
 Yan

**Comment by rockypandalu** [comment]
The code I am using are just follow the instruction provided on the instruction:

from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.commerce import UsageManagementClient
from azure.mgmt.resource.resources import ResourceManagementClient
from datetime import date, timedelta
import json

subscription_id = ''
credentials = ServicePrincipalCredentials(
    client_id = '',
    secret = '',
    tenant = ''
)

commerce_client = UsageManagementClient(
    credentials,
    subscription_id
)

resource_client = ResourceManagementClient(
    credentials,
    subscription_id
)
resource_client.providers.register('Microsoft.Commerce')


# Takes onky dates in full ISO8601 with 'T00:00:00Z'
usage_list = commerce_client.usage_aggregates.list(
    str(date.today() - timedelta(days=1))+'T00:00:00Z',
    str(date.today())+'T00:00:00Z'
)
print usage_list

But when print the usage_list, I still can not get the usage data I want.

**Comment by rockypandalu** [comment]
I just find the document at

http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.commerce.models.html?highlight=azure.mgmt.commerce.models

So this issue can be closed, thanks for the Azure team!

**Comment by lmazuel** [comment]
Thank you for your feedback, if you want modification or update in the docs, just tell me :)

**Comment by lmazuel** [comment]
Thank you for your feedback, if you want modification or update in the docs, just tell me :)

**Comment by andreicolta** [comment]
hi guys,

I have the same issue, my code looks like:
usage_list = commerce_client.usage_aggregates.list("2016-09-01T00:00:00Z", "2016-09-02T00:00:00Z", "true", "Hourly" )            
                                                                                                                                 
print(usage_list)                                                                                                                

But output is looking like:
<azure.mgmt.commerce.models.usage_aggregation_paged.UsageAggregationPaged object at 0x1044cc898>


Anyone has any ideas ?

Thanks,
Andrei

**Comment by rockypandalu** [comment]
Hi, I think you need to print usage_list.next()

**Comment by rockypandalu** [comment]
Hi andreicolta, I think you need to print usage_list.next()

**Comment by andreicolta** [comment]
hi,

Seems it works, at least the output is empty, no error.
If you do not mind can you point to the right direction to doc, and why usage_list.next()? 

Thanks a lot for your help.

Andrei

**Comment by rockypandalu** [comment]
Then I think lmazuel is the right person to answer this question, I just manage to make it work in my project

**Comment by lmazuel** [comment]
Hi @andreicolta 

`list` methods always return an [iterable object](https://docs.python.org/3/glossary.html#term-iterable). The string representation is not available, since the object if using lazy loading: while your iterate on it it will call the Azure RestAPI only if necessary (when you reach the end of the current JSON answer). This is best for memory consumption.

Basic usage in then:
```python
for item in usage_list:
    print(item.id)
```
As any iterable object in Python, you can convert it to an explicit list:
```python
usage_list = list(usage_list)
```
This will force the object to avoid lazy loading and load every objects in memory.

The `next` method is for advanced usage, since your force the object to load the next page. This implies  you want to manage the pages returned by Azure manually.

Please tell me if I can answer to anything else :)

**Comment by andreicolta** [comment]
hi,

Thanks for guiding, however i get in return something like this:
/subscriptions/${subscription_number}/providers/Microsoft.Commerce/UsageAggregates/Daily_BRSDT_20160903_0000
/subscriptions/${subscription_number}/providers/Microsoft.Commerce/UsageAggregates/Daily_BRSDT_20160903_0000

Do you know what this means ? and how i can get the data correctly ?

Thanks,
Andrei

**Comment by lmazuel** [comment]
Hi @andreicolta ,

I wrote `item.id` as an example, the item instance you got is an [UsageAggregation](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.commerce.models.html#azure.mgmt.commerce.models.UsageAggregation) instance.

**Comment by indumathyn** [comment]
My Python api code 
commerce_client = UsageManagementClient(credentials, subscription_id)		
usage_list = commerce_client.usage_aggregates.list("2016-09-02T00:00:00Z", "2016-09-01T00:00:00Z")
		for item in usage_list:
			print(item)

Resultant:
File "/usr/local/lib/python3.4/dist-packages/azure/mgmt/commerce/operations/usage_aggregates_operations.py", line 106, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.commerce.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

**Comment by lmazuel** [comment]
Hi @indumathyn 
Your "start" is after your "end".
Thanks,

**Comment by indumathyn** [comment]
sorry i couldn't understand...

**Comment by indumathyn** [comment]
**Updated Code**,
credentials = ServicePrincipalCredentials(
	client_id=args.id,
	secret=args.secret,
	tenant=args.tenant
)
commerce_client = UsageManagementClient(credentials, subscription_id)
usage_list = commerce_client.usage_aggregates.list("2016-09-01T00:00:00Z", "2016-09-02T00:00:00Z")
for item in usage_list:
    print(item)

But still showing,
 File "/usr/local/lib/python3.4/dist-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python3.4/dist-packages/azure/mgmt/commerce/operations/usage_aggregates_operations.py", line 106, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.commerce.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

**Comment by lmazuel** [comment]
Could you try more recent dates? I don't know if data disappears with time and if 2016-09-01 are still available.

**Comment by lmazuel** [comment]
Did you also look into the new packages azure-mgmt-billing and azure-mgmt-consumption? I didn't have the opportunity so far to test them in details, but maybe they have what you need. The team made unittests that might help:

- https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_billing.py
- https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_consumption.py
