### ISSUE TITLE
When can the commerce (billing) package be integrated into the azure official release

### ISSUE THREAD

**Issue by rockypandalu** [Azure/azure-sdk-for-python#623]
Hi, thank you so much for designing the azure-mgmt-commerce python package, it helped my work significantly.

Now I have programmed using this package and test it. And now I want to deploy my code on cloud. To do that I will put all library I need in a requirements.txt, the cloud server will help me to launch these packages using "pip" install.

However, it seems that the sdk downloaded by "pip install --pre azure" does not contain the azure-mgmt-commerce package. So I am wondering whether you could provide me with an estimation about when will the commerce package exists in the official release that can be installed by pip?

Thank you very much!

**Comment by lmazuel** [comment]
Hi!
To give you a full overview, this is our planned roadmap for package publishing:
- Early summer move the "azure" meta-package to stable 2.0.0 including several package to stable at the same time. At least Compute, Resource, SQL Management, KeyVault, Storage, WebApp, Network. This is the minimal list to release as stable, there will be no stable release if one is missing.
- We might decide that some package not in this list are ready to be released as stable too. I didn't decided yet for Commerce. I have to contact the team first.
- Some package will stay as preview and will not be installed by "azure". Which means that it's possible that some packages which are currently installed by "azure" will not in the future, waiting for them to be validated by the service team as stable before being included in the stable "azure" meta-package.

This way, when people will install "azure" they will be sure to have installed stable package. But they can decide to install preview package using explicitly the `--pre` flag.

I hope this answers your question :)

**Comment by rockypandalu** [comment]
Hi Imazuel, thank you for your reply! But I am not sure whether I understand your answer correctly.

It seems that you think I can get the azure-mgmt-commerce "preview" package by "pip install --pre azure". But I have tested for 4 times on different machines, and can not get the package. Actually I have checked all packages I installed from "pip install --pre azure" under "azure-mgmt" prefix, and the commerce package is the only one that I can not get.

As long as I can get the preview version by "pip install --pre azure", it will be totally fine for my current work. So is it possible for you to make the commerce package be able to installed by "pip install --pre azure"?

Appreciate for the help!

**Comment by lmazuel** [comment]
Sorry if I was not clear. I know you don't have commerce using `pip install --pre azure`, because I didn't plug it yet.

To do a more direct short answer: I need to discuss the "preview" tag with the commerce team before planning to plug it inside "azure", since "azure" will shortly move to "stable".

In the best case, commerce could be inside "azure" for the end of June, in the worst case commerce don't want it to be published as stable and it will be (I guess) more fall 2016.

**Comment by rockypandalu** [comment]
Dear Imazurl, now I understand. Thank you a lot. Our application will be launched in fall, I will try the C# solution.
But still thank you a lot for your help!

**Comment by lmazuel** [comment]
Dear @rockypandalu 

I'm sad to hear that you will move from Python to C# :(
Could you provide me more context of your situation by email? I would like to understand your scenario and see if I can help.
My email is my github alias + @microsoft.com

Thank you!
