### ISSUE TITLE
Can't manage and request Just in Time access to VM using python SDK

### ISSUE THREAD

**Issue by damianw2** [Azure/azure-sdk-for-python#6239]
No support for this API endpoint:
https://docs.microsoft.com/en-us/rest/api/securitycenter/jitnetworkaccesspolicies

**Comment by lmazuel** [comment]
Actually there is support in the azure-mgmt-security package :)
https://pypi.org/project/azure-mgmt-security/

I agree however there is no reference documentation for it, like the link you pushed for the RestAPI. I keep this one open until the reference doc for Python is online.

Thanks!

**Comment by lmazuel** [comment]
Ref doc is now online:
https://docs.microsoft.com/en-us/python/api/azure-mgmt-security/azure.mgmt.security?view=azure-python

Thanks!
