### ISSUE TITLE
Add approval to Python release

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-python#6248]
This will bring it in alignment with the rest of the release pipelines.  

When we do this, we'll also need to make sure that @lmazuel and other management plane folks have proper permissions to approve their own releases.

**Comment by scbedd** [comment]
Created security groups for each language, waiting for them to propagate before creating the release-specific security groups.

[Added Wiki Page](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki?pagePath=%2FReleasing%20Packages%2FApproval%20Groups&pageId=65&wikiVersion=GBwikiMaster)
