### ISSUE TITLE
cannot install sdk on RaspberryPi

### ISSUE THREAD

**Issue by shitada** [Azure/azure-sdk-for-python#6268]
I cannot install sdk on RaspberryPi.

I executed following commands without errors on RaspberryPi.

> sudo apt-get update
> sudo apt-get upgrade
> sudo apt-get install python-pip

And I got error on the command.

> sudo pip install azure-eventhub

error message. 
------
　　Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RiTjh9/uamqp/setup.py';
　　f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');
　　f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Hxbkt9-record/install-record.txt 
　　--single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-RiTjh9/uamqp/
------

Is the python SDK supported on RaspberryPi?

I succeeded to execut these commands on WIndowOS(8.1) and Ubunts18.04,

**Comment by annatisch** [comment]
Thanks @shitada 

I have transferred your issue to the current repo for the Event Hubs SDK.
You are correct that the underlying library - uAMQP - does not yet support installation on raspberry pi.
There's an issue open for it here:
https://github.com/Azure/azure-uamqp-python/issues/15

Adding @YijunXieMS and @yunhaoling
