### ISSUE TITLE
azure-mgmt-applicationinsights: check_name functionality missing

### ISSUE THREAD

**Issue by romanlutz** [Azure/azure-sdk-for-python#6269]
The check_name functionality as it exists for other resources is missing and would be useful to have to check whether or not a name can be used.

**Comment by lmazuel** [comment]
Hi @romanlutz 
That would be a RestAPI feature first, before SDK can wrap it.
@alexeldeib thoughts?

**Comment by xiangyan99** [comment]
@romanlutz latest azure-mgmt-applicationinsights is 1.0.0. Does it work for you?

**Comment by romanlutz** [comment]
@xiangyan99 I'm afraid I don't really have a way to try this out at the moment. If you know it's supported now please feel free to close the issue. If I need this again at a later point and can't figure it out I'll be happy to reopen it. Thanks for your response!

**Comment by xiangyan99** [comment]
@romanlutz Sounds good. Thank you.
