### ISSUE TITLE
Can not deploy a webservice on a AKScompute that was provisioned with a ssl certificate

### ISSUE THREAD

**Issue by ShengChenMSFT** [Azure/azure-sdk-for-python#6274]
I created an AKS compute that was provisioned with a ssl certificate. It was succeed. 
Then, I created an image that contained a scoring model, which was also succeed.
When I deploy the image on to the above AKScompute. I was failed with following error:

WebserviceException: Received bad response from Model Management Service:
Response Code: 500
Headers: {'Date': 'Tue, 09 Jul 2019 22:14:59 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:2d2e8e63-272e-4b3c-8598-4ee570a0e70d', 'api-supported-versions': '1.0, 2018-03-01-preview, 2018-11-19', 'x-ms-client-request-id': '191052ffc11a4f15bda15a0266240414', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"InternalServerError","statusCode":500,"message":"An internal server error occurred. Please try again. If the problem persists, contact support"}'

Here is my deployment code in python

stage='PPE'
cluster_name='AKS-AML-PPE-WUS2'

#Set the web service configuration (using default here)
aks_config = AksWebservice.deploy_configuration()
attach_config = AksCompute.attach_configuration(resource_group=ws.resource_group, cluster_name=cluster_name)
aks_target = ComputeTarget.attach(ws, cluster_name, attach_config)
serviceName = 'casenote-web-service-wus2'
service = Webservice.deploy_from_image(workspace=ws,
                                       name=serviceName,
                                       image=image,
                                       deployment_config=aks_config,
                                       deployment_target=aks_target
                                      )
service.wait_for_deployment(show_output=True)

**Comment by lmazuel** [comment]
Hi @ShengChenMSFT 
AzureML package support is not on this repo unfortunately, please contact:
https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureMachineLearningService
Thanks
