### ISSUE TITLE
mgmt.compute: deserialization code is wrong on azure container service

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-sdk-for-python#629]
The fix should be from either swagger or code-gen. This makes the "list/get" unusable
Check out the generated code [here](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/models/container_service.py#L78-L82). The `String`, should be 'str'

```python
'id': {'key': 'id', 'type': 'String'},
'''

**Comment by xingwu1** [comment]
Not repro with latest code gen.

**Comment by lmazuel** [comment]
If Autorest is ok, will be fixed officially in the next release, in theory next week.
