### ISSUE TITLE
Support device code authentication (async)

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#6293]

**Comment by astafan8** [comment]
I've noticed that this task has been open for ~3 years, so I wonder what is the known "workaround" to use a device-code credential with async clients e.g. AsyncDataLakeServiceClient? Is there a way to acquire token using sync device code credential class and pass it to (e.g.) AsyncDataLakeServiceClient? Or perhaps a completely other way?

**Comment by xiangyan99** [comment]
Replied in https://github.com/Azure/azure-sdk-for-python/issues/6451#issuecomment-1248344963
