### ISSUE TITLE
Cosmos API docs restructure

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#6296]
The current ES docs automation includes many things that the Cosmos team would like to have excluded:

![60934030-9a996f00-a279-11e9-9e55-5ffff56f4231](https://user-images.githubusercontent.com/1078448/61003519-fbc44f80-a318-11e9-8853-f5ad8897ce0b.png)

More or less, all the important user-facing content is completely located in `azure.cosmos`, and they would like just this content presented. Is it worth making some of these other modules "private" (underscored) so that they are automatically excluded from the current ES automation? Or is there another way to limit the docs output keeping the current public module structure?

cc @christopheranderson @johanste @scbedd @weshaggard

**Comment by johanste** [comment]
Per the updated python design guidelines, we should make the internal modules underscored.

**Comment by scbedd** [comment]
As for how we do it, we can either hand edit the generated RST, or update the generation step in your azure-cosmos doc folder to generate specifically the sources that we care about.

For this first one, my plan is to remove Sphinx source files for stuff we don't want to index, and then use `exclude-member` argument to the directive in the sphinx source itself for the ones where we need to exclude non-private modules.

**Comment by annatisch** [comment]
This _should_ now be resolved as of Preview 4.
Will confirm by end of the week.

**Comment by annatisch** [comment]
Yup docs looking much cleaner:
https://azure.github.io/azure-sdk-for-python/ref/azure.cosmos.html
