### ISSUE TITLE
Not able to add multiple inbound security rules to the existing NSG 

### ISSUE THREAD

**Issue by karthiknannapaneni** [Azure/azure-sdk-for-python#6309]
Not able to add multiple inbound security rules to the existing NSG 

Error Message

Unable to build a model: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get'
==============================================================
```python
from azure.mgmt.network.v2017_03_01.models import NetworkSecurityGroup
from azure.mgmt.network.v2017_03_01.models import SecurityRule
    parameters = ["SecurityRule('Tcp', '*', '*', 'Allow', 'Inbound', description='All SSH Access',source_port_range='*', destination_port_range='99', priority=105)", "SecurityRule('Tcp', '*', '*', 'Allow', 'Inbound', description=' SSH Access',source_port_range='*', destination_port_range='292', priority=priority1, name='SSss')"]


    names = ['nfs','vfs']

    for i in names:
        print i, type(i)
        for j in parameters:
            print j, type(j)
            try:
                network_client.security_rules.create_or_update(resource_group_name, nsg_name, i,j, raw=True)
            except Exception as err:
                logging.error(err.message)
                print(err.message)
                exit(0)
```

**Comment by karthiknannapaneni** [comment]
trying to add multiple inbound rules to an existing NSG.

**Comment by kurtzeborn** [comment]
Thanks for reporting this issue!  I've hopefully routed it to the appropriate team for further investigation.

**Comment by lmazuel** [comment]
Hi @karthiknannapaneni 
Your code is incorrect, you have a list of strings, and not a list of Security Rules object. Please remove the extra double-quote from each element of you list:

```python
parameters = [
    SecurityRule('Tcp', '*', '*', 'Allow', 'Inbound', description='All SSH Access',source_port_range='*', destination_port_range='99', priority=105),
    SecurityRule('Tcp', '*', '*', 'Allow', 'Inbound', description=' SSH Access',source_port_range='*', destination_port_range='292', priority=priority1, name='SSss')
]
```

**Comment by lmazuel** [comment]
This unittest gives example of usage:
https://github.com/Azure/azure-sdk-for-python/blob/1dd0602647bcf224de1dfb46a8d4d0e1d90b17d2/sdk/network/azure-mgmt-network/tests/test_mgmt_network.py#L472-L510

**Comment by karthiknannapaneni** [comment]
@imazuel Can you please share the documentation link or code snippet on adding inbound rules with source: service tag/IP Addresses
destination: application security group/Virtual Networks

**Comment by karthiknannapaneni** [comment]
I didn't find the required parameters in the documentation
 https://github.com/Azure/azure-sdk-for-python/blob/1dd0602647bcf224de1dfb46a8d4d0e1d90b17d2/sdk/network/azure-mgmt-network/azure/mgmt/network/v2019_04_01/models/_models_py3.py#L10935

**Comment by karthiknannapaneni** [comment]
Not able to find the below parameters in the documentation

Source: service tag/Application Security group
Source service tag: Azure load balancer
Destination: Application security group/Virtual Networks
Source application security group: 'value'
