### ISSUE TITLE
VirtualMachineSizeTypes mistmatch causes deserialization errors

### ISSUE THREAD

**Issue by madhulika** [Azure/azure-sdk-for-python#632]
Currently the VirtualMachineSizeTypes enum misses out the 'F' size types 
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/models/compute_management_client_enums.py

Deserialization fails when we try to get the list of vms using
compute_client.virtual_machines.list_all() and we can't access the returned object.

It makes automation of vm creation impossible when a 'F' size is chosen.

**Comment by lmazuel** [comment]
Hi @madhulika,

This issue was supposed to be fixed in the RC4. You can see in the ChangeLog the "Enum refactoring" part:
https://github.com/Azure/azure-sdk-for-python/releases/tag/v2.0.0rc4

Could you confirm your version?

Thank you,

**Comment by madhulika** [comment]
Thank you @lmazuel 
I was using rc3. I moved to rc4 and the soft enum fix is there.
