### ISSUE TITLE
AioHttpTransportResponse is incompatible with ContentDecodePolicy

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#6331]
When the request was made with `stream=False`, anyway; `ContentDecodePolicy` does nothing with streamed responses.

In the unstreamed case, `ContentDecodePolicy` will raise when given an `AioHttpTransportResponse`. `AioHttpTransportResponse` wraps `aiohttp.ClientResponse`, which can represent the response's content-type header as a string, e.g. 'application/json; charset=utf8'. Such a string is problematic for `ClientDecodePolicy`:
- `deserialize_from_http_generics` [assumes `content_type` is a list](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/universal.py#L353). It parses the above string into 'a' and passes it along to `deserialize_from_text`, for whom it's unintelligible.
- `ClientDecodePolicy` doesn't parse the content type's charset, and its [static collection of MIME types](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/universal.py#L269) doesn't include charsets, so `deserialize_from_text` raises `DecodeError` for the above string.

**Comment by lmazuel** [comment]
@chlowell I was telling to @annatisch that I was surprised by the redesign of this policy compared to the initial msrest.

The initial one doesn't have any of these flaws: don't assume content-type is an array (?!!?) and extract charset:
https://github.com/Azure/msrest-for-python/blob/master/msrest/pipeline/universal.py#L217

Also, I'm sad with the contract that was changed:
- `deserialize_from_http_generics` was named to be "gimme bytes and headers as dict", hence the name. Changing the input type to "response" totally breaks this contract
- `deserialize_from_text` was designed to take a "text like" object, and same, changing input to response doesn't make sense.

I was telling to @johanste that at some point I wanted to change this policy to be a little more than before, maybe it's the right time :)

**Comment by mayurid** [comment]
@lmazuel : take a quick look and see if this is already fixed

**Comment by lmazuel** [comment]
@mayurid the problem described by @chlowell has been fixed: `content_type` MUST be a string, and if it's not a string it's a transport issue actually.

That being said, we should fix what I said as corollary, and I did a PR for that:
https://github.com/Azure/azure-sdk-for-python/pull/7730

**Comment by lmazuel** [comment]
Closed totally thanks to #7730
