### ISSUE TITLE
[service-bus] Sender is crashing when used without context manager

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#6332]
Issue fully documented with repro steps in uAMQP repo:https://github.com/Azure/azure-uamqp-python/issues/84

Will likely involve fixes to both uAMQP and service bus SDK, which needs to properly open and close the sender even when used without a context manager.

**Comment by yunhaoling** [comment]
Closing the issue here as uAMQP v1.2.5+ should have get this problem resolved.
