### ISSUE TITLE
Looking for Blob handling advice

### ISSUE THREAD

**Issue by dxkaufman** [Azure/azure-sdk-for-python#6333]
I apologize if this is not really the appropriate place for this kind of question, but I'm not having much luck with trial & error or web searches.  I am having a problem now that I have increased my app to 3 instances, where I am getting two instances of the same function working on the same blobs, and I can't seem to figure out how to avoid that.  I think there are two problems (I am using an http triggered function written in Python using Visual Studio Code):

1- I am trying to append a new json snippet onto an existing blob.  I open the blob, read the whole thing, remove the closing ], then add ,<new json>], and write the file back up.  The file is basically one big "Event":[<event 1 json>,<event 2 json>,...].  I suspect that this is not the best way to do this, but with only one instance, it wasn't causing any problems.  I went up to 3 instances because my functions were performing very badly for a while yesterday, and I was hoping that 3 instances would allow the user-facing function to work in a tolerable amount of time.  As a result, however, I occasionally have a situation where two instances open, read, and write the file at about the same time, resulting in one instance failing to write because the blob has been changed.  I tried to open the blob for writing as one would a file on disk so that I could just read to the position before last and write the new json there, but I couldn't seem to get that to work.

2- I probably should really be appending the new json, and I probably don't need the whole file to be an array, though that would mean it isn't quite valid json when at rest.  Unfortunately, I also couldn't figure out how to set up a blob for append operations.

Thank you, in advance, for any help you can give.  Also, if there is a better place for this sort of question, I would greatly appreciate your pointing me at it.

Thanks!
Dylan

**Comment by annatisch** [comment]
Hi @dxkaufman,

Thanks for your question!
The storage service actually offers multiple ways to approach this problem.

1. If you are only ever using "append" operations, then Storage actually offers a specific blob type for this where you upload the additional data and it will be added to the end of the blob. This was specifically designed for logging scenarios, however it may work for your usecase as well. For more information, you can read here:
https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-append-blobs.

2. You could use leases. A given instance can take a lease out on the blob in order to write to it. This acts like a lock on the blob, and the other instances will be blocked from acting on it until the lease is released.

3. You could use modification headers. These provide conditions under which the operation is completed, for example "only write this data to the blob if is hasn't been modified since I last read from it".

Depending on which version of the storage SDK you're using, I can give you code snippets demonstrating these concepts :)

**Comment by dxkaufman** [comment]
Thanks for the reply, @annatisch.  

This is what I have in the requirements.txt file; I know there's a way to see the version of each that is installed in the env, but I can't remember it now:
azure-functions-worker==1.0.0b4
azure-functions==1.0.0b3
azure-storage-blob

One of my concerns about the append blob is that it can only take 50,000 pieces, and I'm going to be appending pretty small snippets.  I'm not sure that's a big deal right now, but it might be as we scale... I'm trying to keep the number of blobs under control.  I'm not really sure why, to be honest, because if and when we process that raw data, it'll have to be done programmatically anyway.  But I'm trying at the moment.

I was thinking about trying to do a lease.  I'm also trying to figure out how to spot the 'AzureConflictHttpError' response, so perhaps I can just retry in that case.  Right now, what happens is that once in a while, I find a failure for this function in the Azure monitor and it has the AzureConflictHttpError in it, as a response to the create_blob_from_text call.  I thought I would be able to take the return value of that call and find it, but it doesn't seem so, and since I'm not actually making the REST API call myself, I can't see (as far as I know) the request object.

I'm definitely concerned about whether I'm doing the right thing by reading the current file, appending to it in memory, and writing it back up.  

I suppose another way to do it would be just to write every single event as its own blob... I could just try to write it with the timestamp down to the millisecond, like 2019-07-12_15:13:01.123.json and if that fails it means there's already a file with that name, so I could add _#, incrementing the number over and over until I succeed... so if I got enough events, I could easily have a bunch of them all with the same timestamp plus _0, _1, etc. on the end.  But then I'd have a TON of files...  As far as I can tell, there's no pricing component based on sheer number of files, but I don't know if there's effectively a minimum block size per file, in which case wasting a ton of that block space with small files would be expensive over time.

The way I have it now is definitely an attempt to keep from having a bajillion files while also keeping the per-event processing time down (I'm currently limiting each blob to 10MiB), but I'm contemplating switching to queue triggers... so my event handler will stick each event into two queues and stop.  Then one queue trigger function will do the raw data storage function while another actually processes the event (which I haven't written yet) and writes information about it to SQL server.  I wrote this in the MSDN forums earlier today, which is probably where I should have posted for this topic too, now that I think of it (https://social.msdn.microsoft.com/Forums/en-US/d91f8c63-da97-4099-897f-3189e6d4f714/possible-to-peek-at-queue-message-with-queue-trigger-trying-to-enable-dev-vs-prod-code?forum=AzureFunctions).

**Comment by dxkaufman** [comment]
Speaking of the AzureConflictHttpError, I should mention that I changed my code to catch any exception at that point, and log an error for me with the exception and exception args.  Now I'm waiting for an error!

**Comment by kurtzeborn** [comment]
Closing this issue as there's no code changes being tracked here.  @dxkaufman, please let us know if you have further questions by either reactivating (if it's the same topic) or opening a new issue.  Thanks again for reaching out on this and hopefully we've provided you enough information to move forward.
