### ISSUE TITLE
API Management Service update function throws exception when trying to update SKU to Premium tier

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Azure/azure-sdk-for-python#6335]
Code:
   ```
self.session.client('azure.mgmt.apimanagement.ApiManagementClient').api_management_service.update(
            'rg',
            'name',
            ApiManagementServiceUpdateParameters(sku=ApiManagementServiceSkuProperties(name='Premium', capacity=8)))

```
Expected:
Service is updated to Premium tier with 8 units

Actual:
Error:
'Operation failed with status: \'Bad Request\'. Details: Setting EnableClientCertificate flag to false is not supported for Premium SKU.'

**Comment by lmazuel** [comment]
Hi @anastasiia-zolochevska 
I need to investigate in more detail why this is happening, in the meantime you can workaround this issue:
```python
ApiManagementServiceUpdateParameters(
    sku=ApiManagementServiceSkuProperties(name='Premium', capacity=8), 
    enable_client_certificate=None
)
```
It won't serialize it on the wire then:
```python
ApiManagementServiceUpdateParameters(
    sku=ApiManagementServiceSkuProperties(name='Premium', capacity=8), 
    enable_client_certificate=None
).serialize()
#{'properties': {'virtualNetworkType': 'None'}, 'sku': {'name': 'Premium', 'capacity': 8}}
```

Thanks

**Comment by lmazuel** [comment]
That's a serialization issue in the code generator. I have no ETA at this time to fix it, it's a known subtle issue, please use the workaround for now.
Thanks

**Comment by xiangyan99** [comment]
@anastasiia-zolochevska latest azure-mgmt-apimanagement is 2.1.0. Does it work for you?
