### ISSUE TITLE
Python Authentication, creating SP, --password is not supported

### ISSUE THREAD

**Issue by luisgutierrez707** [Azure/azure-sdk-for-python#6341]
On DOC:

https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-authenticate?view=azure-python

it states:
az ad sp create-for-rbac --name "MY-PRINCIPAL-NAME" --password "STRONG-SECRET-PASSWORD"
"
As of Azure CLI 2.0.68, the --password parameter to create a service principal with a user-defined password is no longer supported to prevent the accidental use of weak passwords.
Per new release, --password is not supported.
"

https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest

**Comment by kurtzeborn** [comment]
Thanks for the issue report.  I've attempted to route this to the correct team for further investigation.

**Comment by lmazuel** [comment]
Hi @luisgutierrez707 
Thanks for the report! I did a PR to fix the doc:
https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/512
