### ISSUE TITLE
Search API exception if response filter has more than 1 item

### ISSUE THREAD

**Issue by applechief** [Azure/azure-sdk-for-python#6370]
In the websearch API, if the `response_filter` or `promote` parameters contain more than one item in the list the API returns an error.

As noted in this issue in the javascript version of the SDK it seems that the items are comma separated in the request and are being url encoded which is breaking the API.

# https://github.com/Azure/azure-sdk-for-js/issues/4244

**Comment by lmazuel** [comment]
Hi @applechief 
Based on the Javascript issue, it's likely a RestAPI issue ;(. I'm tagging the team and will try to contact them.
Thanks for the report
