### ISSUE TITLE
No fixed retry policy in python azure core

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#6419]
I don't see a config param about fixed retry delay in azure-core python.
https://github.com/Azure/azure-sdk-for-python/blob/a6751434467d4f7b12192793f82bf1f9a0075ff9/sdk/core/azure-core/azure/core/pipeline/policies/retry.py#L119
            'total': options.pop("retry_total", self.total_retries),
            'connect': options.pop("retry_connect", self.connect_retries),
            'read': options.pop("retry_read", self.read_retries),
            'status': options.pop("retry_status", self.status_retries),
            'backoff': options.pop("retry_backoff_factor", self.backoff_factor),
            'max_backoff': options.pop("retry_backoff_max", self.BACKOFF_MAX),
            'methods': options.pop("retry_on_methods", self._method_whitelist),
            'history': []

**Comment by xiangyan99** [comment]
We need a design review before updating the code.

**Comment by johanste** [comment]
We should add one.

**Comment by xiangyan99** [comment]
Fixed
