### ISSUE TITLE
Implement async interactive authentication

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#6451]

**Comment by astafan8** [comment]
Similar to #6293, I've noticed that this task has been open for ~3 years, so I wonder what is the known "workaround" to use an interactive credential with async clients e.g. AsyncDataLakeServiceClient? Is there a way to acquire token using sync interactive credential class and pass it to (e.g.) AsyncDataLakeServiceClient? Or perhaps a completely other way?

**Comment by xiangyan99** [comment]
Thanks for asking.

A simple workaround is you can implement an async interactive credential class and in 

```py
async def get_token(self, *scopes: str, **kwargs: "Any") -> "AccessToken":
```

method, you call the sync one and return the token.

Please let us know if it doesn't work.

**Comment by astafan8** [comment]
thank you @xiangyan99 ! indeed, this workaround worked very well.

Shall such an implementation be submitted to the package? I'm happy to open a PR. Wouldn't even a minimal class implementing this be of help? or are there concerns?

**Comment by xiangyan99** [comment]
Thanks for the suggestion.

We decide not to ship the workaround in our package because we don't want to lie to our customers. :)

I will have a gist snippet to demo the workaround.

**Comment by xiangyan99** [comment]
The gist: https://gist.github.com/xiangyan99/361cf21bf4f78170d5a237ec72a1e9bd
