### ISSUE TITLE
azure-keyvault-keys should use async safe context for http challenge

### ISSUE THREAD

**Issue by SuyogSoti** [Azure/azure-sdk-for-python#6452]
https://github.com/Azure/azure-sdk-for-python/blob/0e0d17e50a86b458b0dd9b459bbe1079b55254aa/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/http_challenge_cache.py#L23-L25

Maybe we extract tracing_context in the core out of tracing and use it here.

**Comment by chlowell** [comment]
Talked through this with Johan and Laurent, we couldn't come up with a scenario in which it's dangerous. A yield within the lock would be a problem, but in this case all we do while holding the lock is read or update a dictionary.
