### ISSUE TITLE
Main page README docs link 404s

### ISSUE THREAD

**Issue by kjschiroo** [Azure/azure-sdk-for-python#6462]
Under the "Need help?" section there is a link to detailed documentation that goes to this address: https://github.com/Azure/azure-sdk-for-python/blob/master/aka.ms/python-docs which just 404s

**Comment by lmazuel** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-python/commit/89c1ce4a7f2f71d0d9f8b3388286dcb9458b2e12 thanks for the report!

**Comment by lmazuel** [comment]
@johanste FYI
