### ISSUE TITLE
Unexpected keyword argument 'name' creating NetworkInterface

### ISSUE THREAD

**Issue by techhat** [Azure/azure-sdk-for-python#648]
Found this trying to create a `NetworkInterface` in Salt Cloud:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1446, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1281, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1089, in create
    data = request_instance(kwargs=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 907, in request_instance
    iface_data = create_interface(kwargs=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 846, in create_interface
    ip_configurations=ip_configurations,
TypeError: __init__() got an unexpected keyword argument 'name'
```
Looking closely, `__init__()` inside `azure/mgmt/network/models/network_interface.py` doesn't have `name` specified, even though it's referenced several other times in the file.

**Comment by techhat** [comment]
Also finding the same thing in `azure/mgmt/compute/models/virtual_machine.py`.

**Comment by techhat** [comment]
#649 addresses both now.

**Comment by lmazuel** [comment]
Hi @techhat 
Thank you for you feedback. However, there is no mistake, "name" is a read_only attribute which cannot be set by the user. To create a network interface, code will look like this (you can see, no need to set `name` in the `NetworkInterface.__init__` method) :

```python
result = network_client.network_interfaces.create_or_update(
        group_name,
        interface_name,
        NetworkInterface(
            location=region,
            ip_configurations=[
                NetworkInterfaceIPConfiguration(
                    name='default',
                    private_ip_allocation_method=IPAllocationMethod.dynamic,
                    subnet=subnet,
                    public_ip_address=PublicIPAddress(
                        id=public_ip_id,
                    ),
                ),
            ],
        ),
    )
```

I don't see mention of the 2.0.0 SDK version here:
https://docs.saltstack.com/en/latest/topics/cloud/azure.html

Are you trying to move to this version? Let me know if you need help or support, I'm always glad to help using this SDK.

Regards,

**Comment by techhat** [comment]
Hi @lmazuel. The Azure doc still refers to the old driver, using the service management stuff. It will be updated once we get our ARM driver stable.

**Comment by techhat** [comment]
I'm updating my code to remove the `name` attribute for `NetworkInterface`. However, are you also saying that the `name` attribute is read-only for `VirtualMachine` as well?

**Comment by lmazuel** [comment]
Yes, exactly, you will see that name will be given as methods parameter of the create.

Before (in 1.0 series), you would have been able to do things like this (pseudo-code):
```python
client.virtual_machine.create(
    name=name,
    VirtualMachine(
        name=name
    )
)
```

which was confusing, because the `name` inside `VirtualMachine` was ignored anyway. Now, the models have in their `__init__` methods only the parameters which can be changed by the user.

**Comment by techhat** [comment]
Thanks @lmazuel, I have my code updated.
