### ISSUE TITLE
Add Async libraries to Smoke Test for Python

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-for-python#6482]
PR on Python for Smoke Tests [#6412](https://github.com/Azure/azure-sdk-for-python/pull/6412) lack the use of the Async clients.

The same actions perform by the smoke test with the not async clients should be performed with the async clients as well.

**Comment by danieljurek** [comment]
Chatted more with @chlowell .. I think we can unblock this: 

To unblock install `aiohttp>=3.0` (as seen in https://github.com/Azure/azure-sdk-for-python/blob/master/shared_requirements.txt) 

This installs a default network stack that the async implementation can use. This should be added to `requirements.txt`.
