### ISSUE TITLE
Unable to change time zone

### ISSUE THREAD

**Issue by SharmaAnshuman** [Azure/azure-sdk-for-python#6488]
Azure Functions Core Tools (2.7.1480)
Function Runtime Version: 2.0.12555.0
FUNCTIONS_WORKER_RUNTIME = python

Name
WEBSITE_TIME_ZONE
Value
India Standard Time

Value from https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc749073(v=ws.10)

**Comment by lmazuel** [comment]
Hi @SharmaAnshuman 
Please open your issue on the Function repo:
https://github.com/Azure/azure-functions-python-worker

Thanks!
