### ISSUE TITLE
HttpResponse headers attributes should be case insensitive

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#6508]
When I get a `azure.core.pipeline.transport.HttpResponse` object, I expect the `headers` attribute to be case insensitive, and both these statements to work:

```python
'content-type' in http_response.headers
'Content-Type' in http_response.headers
```

@johanste your thoughts?

**Comment by lmazuel** [comment]
Closing since, after investigation:
- aiohttp is indeed case insensitive
- requests is indeed case insensitive

However, when mock with aiohttp and vcrpy, the response returned by vcrpy is case sensitive. That that would be a vcrpy bug on aiohttp support

**Comment by johanste** [comment]
It should be case insensitive.
