### ISSUE TITLE
Serverless secure user records

### ISSUE THREAD

**Issue by ductranit** [Azure/azure-sdk-for-python#6513]
Hi there,
I just move to Cosmos from Google Firebase database.
I'm trying to setup cosmos python sdk & try to develop a system with user authentication & a user collection to store user data.
In Firebase, there is a [security](https://firebase.google.com/docs/database/security) rule to protect user record from being read from other users.
Something like this:
```
{
  "rules": {
    "users": {
      "$uid": {
        ".write": "$uid === auth.uid"
      }
    }
  }
}
```
I wonder is there anything similiar to do this in cosmos without coding? Because I prefer the serverless solution

**Comment by shurd** [comment]
Hi @ductranit, thank you for the question. Would this authentication be at the document level? This SDK works primarily with control plane operations. If this authentication would be for data plane actions, then the contributors at [azure-cosmos-python](https://github.com/Azure/azure-cosmos-python) might be able to help.

**Comment by shurd** [comment]
Hi @ductranit, I am going to close this issue now. If you still need help with this question, you can open a new issue in the data plane SDK [azure-cosmos-python](https://github.com/Azure/azure-cosmos-python). This SDK deals with control plane operations.
