### ISSUE TITLE
'Storage accounts update' operation has required field that should be optional

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-sdk-for-python#652]
`storage_accounts.update` takes a `StorageAccountUpdateParameters` object.
This `StorageAccountUpdateParameters` object takes a `Sku` object.
`Sku` has a name field that is required.

This means to update a storage account, you **have** to set Sku.name which is not the case with the raw REST API.

I've marked this as an issues in the azure-rest-api-specs repo [#370](https://github.com/Azure/azure-rest-api-specs/issues/370).

However, the issue should be tracked here also as the SDK may have to be updated was the swagger spec is updated also.

**Comment by lmazuel** [comment]
Hi @derekbekoe 

The Sku name is actually the account_type, see here:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_storage.py#L46

**Comment by lmazuel** [comment]
Hi @derekbekoe 

As you can see here the ''sku"object is optional:
http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.storage.models.html#azure.mgmt.storage.models.StorageAccountUpdateParameters

If you use "Sku", you have to give a name. But you don't have to use Sku.

Just use something like this and you should be good:
```python
new_domain = CustomDomain(name=self.custom_domain['name'],
                                          use_sub_domain=self.custom_domain['use_sub_domain'])
parameters = StorageAccountUpdateParameters(custom_domain=new_domain)
try:
     self.storage_client.storage_accounts.update(self.resource_group, self.name, parameters)
except Exception as exc:
     self.fail("Failed to update custom domain: {0}".format(str(exc)))
```

**Comment by derekbekoe** [comment]
Thanks @lmazuel this does indeed resolve the issue.

e.g.
```
sku = Sku(skuName) if skuName else None
params = StorageAccountUpdateParameters(sku=sku, tags=tags, custom_domain=custom_domain)
```
