### ISSUE TITLE
Release Notes for v2.0.0rc5 has a Broken Link

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-python#654]
This bullet's link is broken.

There is some breaking changes in the Storage client, due to the update the latest API-Version. There is a storage sample with the new version available here: **https://github.com/Azure-Samples/storage-python-manage**

**Comment by lmazuel** [comment]
Yes, the github account is still private, in review by the documentation team :(. Bad timing.
In the meantime, you could use the unittesting I made to see the change:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_storage.py

I keep this issue opened until they finally move this repository to public "state".
Thank you for the feedback!

**Comment by lmazuel** [comment]
The link is now public, sorry about the inconvenience, I didn't expect this will last that long... :(
