### ISSUE TITLE
passwordPolicies 

### ISSUE THREAD

**Issue by sfonteneau** [Azure/azure-sdk-for-python#655]
I find nothing for " passwordPolicies " , is something that we just add ?

https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/entity-and-complex-type-reference#passwordprofiletype

**Comment by lmazuel** [comment]
For what I understand the password policies is fixed on Azure AD:
https://azure.microsoft.com/en-us/documentation/articles/active-directory-passwords-policy/

I'm not an expert in this specific point, you could comment the previous article to ask how to change the password policies for a given tenant in AAD. If this is possible and there is a Rest endpoint for that, we could ask for support.

**Comment by sfonteneau** [comment]
I'm not an expert.

I may well pass the parameter "passwordPolicies" on this line:
https://github.com/Azure/azure-sdk-for-python/blob/3e80c20b0008ba6004753004be1462f0295c4b1b/azure-mgmt/tests/recordings/test_graphrbac.test_graphrbac_users.yaml#L59

This is a missing parameter " UserCreateParameters " ?

Simon

**Comment by lmazuel** [comment]
I asked the question to the RestApi spec group: https://github.com/Azure/azure-rest-api-specs/issues/375

**Comment by lmazuel** [comment]
Close, can use additionalProperties
