### ISSUE TITLE
RFC: How do you handle different clouds?

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-python#656]
I opened an [issue][1] against the Azure/go-autorest team to better support Azure Stack.  One of the questions was how do other SDKs intend to support Azure Stack.  (I am not sure if this is the right place to log the issue or not.)

The go-autorest library has a [type][2] to encapsulate the various links that are required to support a different cloud environment.  I could not find anything equivalent in the Python SDK.  I do see comments where a Boolean can be passed to indicate China, but nothing to indicate the other supported cloud, e.g. US Government.  Is Azure Stack still something you're thinking about?  The user's request for Azure Stack was a preparatory request because he does not have an immediate need yet.

[1]: https://github.com/Azure/go-autorest/issues/72
[2]: https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go

**Comment by lmazuel** [comment]
Hi @boumenot 

You can do it by changing the `base_url` of each client and overriding the authentication endpoint (or use ADAL 0.3.0 to get the token). However, I agree that it's not convenient.
We have a task in our backlog to support an "Environment". An "Environment" is inspired of what does NodeJS right now:
https://github.com/Azure/autorest/blob/master/ClientRuntimes/NodeJS/ms-rest-azure/lib/azureEnvironment.js

We will provide static environment for China, Governement, etc.and allow the user to define one.

This is also related to this issue:
https://github.com/Azure/autorest/issues/1082

**Comment by boumenot** [comment]
Thank you!

**Comment by lmazuel** [comment]
Adding a doc for multi-cloud here:
http://azure-sdk-for-python.readthedocs.io/en/latest/multicloud.html
