### ISSUE TITLE
Cookies an aiohttp

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#6564]
I just discovered that aiohttp is doing some magic under the hood with cookies. If a query comes back with a “Set-Cookie” header, aiohttp catches it and send it back with the next query (I guess there is a condition of “same host”, “same url”, etc. I’m not sure my test is on the same url).

“requests” lib doesn’t do that, and that made some tests for LRO reacts differently if they were executed as “sync” or as “async” (some LRO tests uses Cookies to differentiate two calls on same verb same url for retry scenario).

And because it stays inside aiohttp, it’s not visible in any logs from “azure-core” (I had to use Wireshark to convince myself it was re-injected).

Not sure the impact, but I thought at least it should be known.

@johanste suggested to change the [cookie conf](https://docs.aiohttp.org/en/stable/client_advanced.html#cookie-jar) of aiohttp session to `DummyCookieJar`. Indeed it helps:
-	If I change from “localhost” to “127.0.0.1”, cookie logic doesn’t work anymore (as they document)
-	If I set the dummy cookie jar in azure-core, same, cookie logic is disabled

If we want a “pure” pipeline with the less possible interaction from the transport layer, probably passing “DummyCookieJar” is best

**Comment by xiangyan99** [comment]
Fixed
