### ISSUE TITLE
"Import examples" in "eph.py" gives exception "No module named 'examples' "

### ISSUE THREAD

**Issue by davidklett** [Azure/azure-sdk-for-python#6572]
Sorry if this is an obvious thing for others, but I'm not making any progress with this.

**Comment by davidklett** [comment]
This is in the event hubs sdk by the way!

**Comment by loarabia** [comment]
Hi @davidklett thanks for reporting this routing it to the right teammate to take a look. CC @ramya-rao-a

**Comment by YijunXieMS** [comment]
Hi @davidklett Thanks for trying out EventHubs.
Could you put folder examples' parent folder (if you clone the whole azure-sdk-for-python repository, it should be the path ...\azure-eventhubs) to environment variable PYTHONPATH? I think this will work. We'll update  example code to avoid this env var config in the next release.

**Comment by davidklett** [comment]
Thanks for your help!
