### ISSUE TITLE
Newly created StorageAccounts are returned with no ID or name

### ISSUE THREAD

**Issue by krimkus** [Azure/azure-sdk-for-python#663]
StorageManagementClient.storage_accounts.create() returns an instance of AzureOperationPoller, which eventually returns an instance of StorageAccount. But, most fields are empty. The account is created and is available in the Portal, but there is no way to fetch additional information about the account from the SDK since there is no name or ID returned to pass to .get_properties().

**Comment by lmazuel** [comment]
Hi @krimkus 
This is a bug with the internal dependencies msrestazure 0.4.0. Please update to 0.4.1 and this should be ok ([ChangeLog in Pypi](https://pypi.python.org/pypi/msrestazure) for reference).
Thank for the report!

**Comment by lmazuel** [comment]
Hi @krimkus , could you conform updating to msrestazure 0.4.1 solves the issue?
Thanks!

**Comment by krimkus** [comment]
Yes, that was it. Thanks for the update!
