### ISSUE TITLE
tracing policy names network span as raw url paths

### ISSUE THREAD

**Issue by SuyogSoti** [Azure/azure-sdk-for-python#6631]
This can get bad if the url has a secret that can not be exposed

**Comment by lmazuel** [comment]
So, current beahvior is this:
```python
In [2]: url = "https://host.org/a/b/c?a=b#foo"

In [3]: urllib.parse.urlparse(url).path
Out[3]: '/a/b/c'
```
That would hide headers or query params (like CS key). But indeed will expose things like subscription id for ARM.
