### ISSUE TITLE
Remove hard-coded user agent

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#6637]
The generated `KeyVaultClientConfiguration` class adds an incomplete, [hard-coded user agent string](https://github.com/Azure/azure-sdk-for-python/blob/2488abb/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v7_0/_configuration.py#L35) in the wrong format. Getting the right string there would take some work because it would require the version of the client library. Probably easier to remove the hard-coded string and let the `UserAgentPolicy` be entirely configured by `kwargs`.

**Comment by mayurid** [comment]
@chlowell : Please see if this is already fixed

**Comment by chlowell** [comment]
The generated client provides a [default](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v7_0/_configuration.py#L35) which isn't in line with the design guidelines. Key Vault libraries override that and send a User-Agent which is, e.g. `azsdk-python-keyvault-secrets/4.0.0b2 Python/3.5.4 (Windows-10-10.0.18362-SP0)`.

So this isn't blocking the release but we may want autorest to generate something better. I'll remove the blocking label and leave this open in case @lmazuel wants it for tracking.

**Comment by lmazuel** [comment]
Issue moved to [Azure/autorest.python #479](https://github.com/Azure/autorest.python/issues/479) via [**ZenHub**](https://www.zenhub.com/)
