### ISSUE TITLE
azure-mgmt-web list_skus() always gets empty list from Azure Mgmt API

### ISSUE THREAD

**Issue by clauney** [Azure/azure-sdk-for-python#6671]
In the azure-mgmt-web SDK, WebSiteManagementClient.list_skus() seems to always return an empty response for multiple subscriptions I've tried it against.

Debug shows that the management API call being used (https://management.azure.com/subscriptions/<my_sub_id>/providers/Microsoft.Web/skus?api-version=2018-02-01) is always returning an empty list (response.text = {"value":[]})

Is this an old method that doesn't work anymore? Or a new method that isn't yet supported by the mgmt api? Even though the Python SDK has this in documentation (https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.websitemanagementclient?view=azure-python#list-skus-custom-headers-none--raw-false----operation-config-), I couldn't find any matching call in the Azure REST API docs (https://docs.microsoft.com/en-us/rest/api/azure/), nor find many google results for the actual URL the SDK is hitting. Curiously, I also don't see a general list_skus feature in the az cli, either, which is why I'm wondering if this is just a relic.

My environment is python 3.7.4 on MacOS, msrest/0.6.2 msrest_azure/0.6.0 azure-mgmt-web/0.42.0. I can provide more detailed info about the environment if you can't repro the issue.

**Comment by loarabia** [comment]
Hi @clauney thanks for reporting the bug. I'm labeling the issue so that the management plane SDK team can find it and take a look.

**Comment by xiangyan99** [comment]
@clauney latest azure-mgmt-web is 5.0.0. Does it work for you?

**Comment by rcampos87** [comment]
I'm having the exact same issue with azure-mgmt-web 0.48.0 where the list_skus() return empty no matter which subscription i call it with. Even trying out https://docs.microsoft.com/en-us/rest/api/appservice/list-skus/list-skus results in an empty response.
