### ISSUE TITLE
Implement azure compute and network api in single request

### ISSUE THREAD

**Issue by cssbrianhsu** [Azure/azure-sdk-for-python#6679]
As I refer from [AWS Python SDK,](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_addresses
) it can get VM detail information (ex: name, size, location) via single api request through Parameters Filters (list).

But from Azure Python SDK, it can get VM details information via its private IP, but still need to execute twice which is not efficiency compare to AWS api. 

Can the following possible to be implement which same as AWS API to get all vm information in once? 
https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.computemanagementclient?view=azure-python
https://docs.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.networkmanagementclient?view=azure-python

**Comment by loarabia** [comment]
Hi @cssbrianhsu, I labeled this so that the folks on the management plane SDK team can take a look.

**Comment by msyyc** [comment]
Python SDK is generated by [swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification). This issue is more related with rest api. Please open an issue in https://github.com/Azure/azure-rest-api-specs/issues
