### ISSUE TITLE
Value Error when calling receive_queue_message method 

### ISSUE THREAD

**Issue by FlavioAlexander** [Azure/azure-sdk-for-python#669]
Hello,

I have been using the azure SDK for some time now. I have never really bothered to look into the codebase until it started throwing a `ValueError` few days ago. The problem comes when calling `receive_queue_message` method which calls other methods. By looking at the code, the error is caused by this line [_create_message](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/azure/servicebus/_serialization.py#L101). It seems like we are expecting some string that will be cast into a float, then integer and then back to string. However, I am getting something like `max-age=31536000` which will fail to be cast. 

<img width="652" alt="_azure_ _python" src="https://cloud.githubusercontent.com/assets/7468482/16588134/b8da237e-429b-11e6-83c1-4e056980a96a.png">

Have anyone faced the same issue before? Any recommendation is appreciated.

Best,

Flavio

**Comment by lmazuel** [comment]
Hi @FlavioAlexander ,

Yes, you are not alone :). It's a change in the SB RestAPI. I released the servicebus SDK 0.20.2 to fix this problem:
https://pypi.python.org/pypi/azure-servicebus/0.20.2

**Comment by FlavioAlexander** [comment]
@lmazuel I am glad to hear that :). By reading the description, it seems I need to upgrade `python sdk` in order to use `azure-servicebus`.

**Comment by lmazuel** [comment]
@FlavioAlexander Actually just `pip install -U azure-servicebus` should be enough if you have azure >= 1.x. If you use azure < 1.0 (like 0.10), yes, you will have to move to azure 1.0.3 first.

**Comment by FlavioAlexander** [comment]
@lmazuel Sadly, I am running azure 0.7.1. Well, sooner or later I needed to move to a new version.

**Comment by lmazuel** [comment]
@FlavioAlexander Moving to 0.11.0 should be easy, this is the same generation of API. You could start with that. It's the last one before 1.0
Moving to 1.0 will require you to read the ChangeLog of the 1.0.0 which describes the update process. It essentially package/module/classes renaming.

I close this issue since I think your initial question is answered. Feel free to open an issue if you have any trouble migrating to the new version.

Thanks!
