### ISSUE TITLE
[Spell Check] Spell check method path is /spellcheck; should be /bing/v7.0/spellcheck

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-python#6698]
- **Package Name**: azure-cognitiveservices-language_spellcheck
- **Package Version**: 1.0.0
- **Operating system**: Windows 10 Enterprise 1803
- **python version**: 3.7.3

**Describe the bug**
The path for the spellcheck method is '/spellcheck' when it should be '/bing/v7.0/spellcheck'. As a result, requests to the service return 404 unless the user appends '/bing/v7.0' to their endpoint.

***Exception or Stack Trace***
```
Traceback (most recent call last):
  File "spell.py", line 27, in <module>
    result = client.spell_checker('bill gtaes')
  File "C:\Program Files (x86)\Python\Lib\site-packages\azure\cognitiveservices\language\spellcheck\spell_check_api.py", line 360, in spell_checker
    raise models.ErrorResponseException(self._deserialize, response)
azure.cognitiveservices.language.spellcheck.models.error_response_py3.ErrorResponseException: Operation returned an invalid status code 'Resource Not Found'
```

**To Reproduce**
1. Get a Bing Spell Check subscription key.
1. Set the environment variable SPELLCHECK_SUBSCRIPTION_KEY to your subscription key.
1. Set the environment variable SPELLCHECK_ENDPOINT to the endpoint for your subscription key (e.g. "https://westus.api.cognitive.microsoft.com").
1. Install Python 3.
1. Install the package azure-cognitiveservices-language_spellcheck.
1. Run the following code.

***Code Snippet***
```
from azure.cognitiveservices.language.spellcheck import SpellCheckAPI
from msrest.authentication import CognitiveServicesCredentials

import json, os, sys

key_var_name = 'SPELLCHECK_SUBSCRIPTION_KEY'
if not key_var_name in os.environ:
    raise Exception('Please set/export the environment variable: {}'.format(key_var_name))
subscription_key = os.environ[key_var_name]

endpoint_var_name = 'SPELLCHECK_ENDPOINT'
if not endpoint_var_name in os.environ:
    raise Exception('Please set/export the environment variable: {}'.format(endpoint_var_name))
endpoint = os.environ[endpoint_var_name]

# Instantiate a Bing Spellcheck client
#endpoint = endpoint + "/bing/v7.0"
client = SpellCheckAPI(CognitiveServicesCredentials(subscription_key), endpoint)

result = client.spell_checker('bill gtaes')
print(result)
```

**Expected behavior**
Expected output:
```
{'additional_properties': {}, '_type': 'SpellCheck', 'id': None, 'flagged_tokens': [<azure.cognitiveservices.language.spellcheck.models.spelling_flagged_token_py3.SpellingFlaggedToken object at 0x03C37610>, <azure.cognitiveservices.language.spellcheck.models.spelling_flagged_token_py3.SpellingFlaggedToken object at 0x03C37630>]}
```

To fix the error, uncomment the following line in the code snippet:
```
endpoint = endpoint + "/bing/v7.0"
```

**Additional context**
Same issue as https://github.com/Azure/azure-sdk-for-python/issues/6472.

**Comment by ChrisHMSFT** [comment]
Hi @v-jaswel ,
Looks like this issue was solved with the updated libraries. Please re-open if you continue to experience the problem

thanks!
Chris
