### ISSUE TITLE
add or update tags on all resources in resource group

### ISSUE THREAD

**Issue by gangularamya** [Azure/azure-sdk-for-python#6716]
Is there a method to add/update tags on all resources in resource group by any chance ?

I have tried below code but it updates it only on resource group but not resources inside it.

```
 resource_group_params = {"location": "centralus"}
 compute_client = ResourceManagementClient(credentials, subscription_id)
# Modify the Resource group
 print("Modify Resource Group")
 resource_group_params.update(tags={"test": "test123"})
 print_item(
 compute_client.resource_groups.create_or_update(
 GROUP_NAME, resource_group_params)
 ) 
```

**Comment by Drewm3** [comment]
Removing the compute label because tagging behavior is managed by Azure Resource Manager (ARM) instead of the resource providers such as the compute resource provider

**Comment by zikalino** [comment]
@gangularamya 
unfortunately there's no single function to achieve that.
what you need to do is:
(1) list all the resource ids in the resource group
(2) update tags on every resource using resource id one by one

Example code can be found for instance in Azure CLI:

https://github.com/Azure/azure-cli/blob/5573b5fbbc256574308822588b52fbcd7c450fea/src/azure-cli/azure/cli/command_modules/resource/custom.py#L915

I can write an example code to perform (1) and (2) when I have some more time

**Comment by leylakazemi** [comment]
You can use policy to modify tags on resources and scope it to a given resource group https://docs.microsoft.com/en-us/azure/governance/policy/concepts/effects#modify

**Comment by kenieva** [comment]
You are able to add/update tags using Modify. 

Here are more details.  https://docs.microsoft.com/en-us/azure/governance/policy/tutorials/govern-tags
Here are some samples: https://github.com/Azure/azure-policy/tree/master/samples/Tags
