### ISSUE TITLE
Set encoding on replies, dont use chardet

### ISSUE THREAD

**Issue by WebSpider** [Azure/azure-sdk-for-python#6723]
Currently, default behavior is to leave encoding settings of the reply in the air, causing the requests library to use chardet to determine the response encoding. This is causing perfomance issues.

When the reply is sufficiently large enough, such as the ratecard get (https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/commerce/azure-mgmt-commerce/azure/mgmt/commerce/operations/rate_card_operations.py#L39), which currently is about 12MB in size, running chardet over this takes a number of seconds.

Resolution would be simple: Use r.encode('utf-8')  to set the response encoding, instead of having to guess it, which results in seconds of delay, for the same result.

**Comment by loarabia** [comment]
Hi @WebSpider Thanks for pointing out the issue and proposing a change. I've labeled this so the right teams should be able to find it but if you're also willing to propose a Pull Request, we'd be happy to look at that.

**Comment by SaurabhSharma-MSFT** [comment]
@zikalino Do you have any updates on this issue.
