### ISSUE TITLE
[ServiceBus] Implement retry policy according to the Python design guideline

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#6731]
Implement and expose retry options to sdk users in Track 2 like what has been to Event Hub.
Documentations should be updated.

**Comment by andrewkittredge** [comment]
Did this happen?  What is the retry policy by default?

I am looking for something similar to this, https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus.

**Comment by yunhaoling** [comment]
Hello @andrewkittredge , thanks for reaching out.

We're in the middle of plan for next ServiceBus preview.
Retry policy is definitely something we'll add support to, but we can't guarantee a specific time.

Thanks for your patience in advance and will update you if there's any progress.

**Comment by KieranBrantnerMagee** [comment]
Hey Andrew, just following up on this:

Our Preview release of the Track 2 Service Bus SDK was rolled out yesterday. (full disclosure, not at feature parity, currently supports queue functionality, will be reaching that in incremental releases over the next few months)

This release allows you to specify “retry_total", "retry_backoff_refactor", "retry_backoff_max" as part of the get_* functions (e.g. get_queue_receiver).  Currently only exponential backoff is supported.

Closing this for now, but don't hesitate to respond/reopen if there are issues or other questions.

**Comment by andrewkittredge** [comment]
@KieranBrantnerMagee 

I am testing the retry parameters on ServiceBusClient, it is not clear if/how they work.  In the below, I expect the receiver to yield the message once a second for 15 seconds then push the message to the dead letter queue.  Instead, the message is re-delivered about once a minute.

Am I doing something wrong, do I not understand how retry works?

```
client = ServiceBusClient.from_connection_string(
    "my_connection_string",
    retry_backoff_max=1,
    retry_total=15,
    retry_mode="fixed"
)
receiver = client.get_subscription_receiver(
    topic_name="my_topic_name", subscription_name="my_subscription"
)

last_retry = datetime.now()

for message in receiver:
    print(f"time since last retry is {datetime.now() - last_retry}")
    last_retry = datetime.now()
```
