### ISSUE TITLE
[Python Track2] [azure-eventhubs] Live connection string in track2 sample.

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-sdk-for-python#6736]
https://github.com/Azure/azure-sdk-for-python/blob/5a6db48f47b23cf6b13a6c35a9b65088794ba8cf/sdk/eventhub/azure-eventhubs/examples/iothub_recv.py#L19

Please remove and regenerate.

**Comment by yunhaoling** [comment]
@digimaun 

oops! thanks for the notice! will remove it immediately!

**Comment by digimaun** [comment]
Thanks @yunhaoling. Regarding regenerate, I actually meant....if the resource was still needed for testing to regenerate the access keys :blush:.
