### ISSUE TITLE
[Python Track2] [azure-eventhubs] [5.0.0b2] EventProcessor should support EventPosition

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-sdk-for-python#6739]
The `EventPosition` class supports multiple position types (offset, sequence or timestamp) where a consumer starts. It would be great to add support to `EventProcessor`. Currently it looks like `EventProcessor` supports offset only i.e. `amqp.annotation.x-opt-offset`.

**Comment by YijunXieMS** [comment]
Hi Paymaun, do you prefer an EventPosition that accepts multiple position types or key word arguments (**kwargs)  that accept offset, sequence, and enqueued_time separately? Or you're indifferent as long as we have them all. This is just a small survey.

**Comment by digimaun** [comment]
I appreciate you asking my thoughts on this.

I see advantage either way. EventPosition would provide more convenience and kwargs would provide more specificity. I lean a bit more towards EventPosition, due to a concern with too many kwargs (especially overtime) for EventProcessor initialization would become unwieldly. I suppose that could be offset with clear/concise documentation though.

One more advantage to EventPosition is the concept is already being used with `EventHubClient`'s `create_consumer` method...and overall I'd prefer consistency with patterns.

Thanks again.

**Comment by annatisch** [comment]
This is supported in preview B5.
The option in B6 will be renamed from `initial_event_posisiotn` to `starting_position`.
