### ISSUE TITLE
Missing support for getting policy assignments by management group

### ISSUE THREAD

**Issue by jeffsigmon** [Azure/azure-sdk-for-python#6754]
Given a management group, I want to pull a list of all policy assignments scoped to that MG. The API docs do not mention that this is supported. However, the implementation of the API looks to support it - so it's possible the API doc need updating...

I was able to monkey-patch the python library to get this to work.

```python
policy_client.policy_assignments.list.metadata["url"] = "/providers/Microsoft.Management/managementGroups/my-mg/providers/Microsoft.Authorization/policyassignments"
```
If the API supports it, the python bindings should also support it.

**Comment by mentat9** [comment]
The SDK is current w.r.t. the backend. The List* operations are limited and left in place for back compat. Preferred and documented way to get/list at MG scope is via the Get operation.
