### ISSUE TITLE
[uAMQP] Enable c-uamqp and python uamqp for shared connection

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#6757]
Enable multiple sessions on single connection with a cbs session.

The underlying uamqp-c library doesn't support the feature at present.
There is an issue opened to track this problem:https://github.com/Azure/azure-uamqp-c/issues/306

**Comment by yunhaoling** [comment]
temporarily closing this issue, this is gonna largely happen in the pure python version of uamqp
