### ISSUE TITLE
[keyvault-keys][readme]AttributeError: 'Key' object has no attribute 'value'

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#6762]
When I run 
key = key_client.get_key("key-name")

print(key.name)
print(key.value)
It complains
AttributeError: 'Key' object has no attribute 'value'

**Comment by johanste** [comment]
Why do you expect a [Key](https://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.keys.html#azure.keyvault.keys.models.Key) to have a value attribute? Is this snippet taken from our documentation?

**Comment by xiangyan99** [comment]
> Why do you expect a [Key](https://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.keys.html#azure.keyvault.keys.models.Key) to have a value attribute? Is this snippet taken from our documentation?

This is from readme.

**Comment by chlowell** [comment]
Fixed by #6766
