### ISSUE TITLE
AutoLockRenew for Message in service bus version 0.50.0

### ISSUE THREAD

**Issue by neerajmangal** [Azure/azure-sdk-for-python#6776]
Our message processing required more time than the Peek Lock Timeout. 

```bash
from azure.servicebus.control_client import ServiceBusService, Subscription

sbs = ServiceBusService(
        service_namespace=config.AZURE_SB_NAMESPACE,
        shared_access_key_name=config.AZURE_SB_SHARED_KEY_NAME,
        shared_access_key_value=config.AZURE_SB_SHARED_KEY_VALUE
 )

msg = sbs.receive_subscription_message(
                    constants.AZURE_SB_TOPIC_METRIC_COLLEECTION,
                    constants.AZURE_SB_SUBSCRIPTION
                    peek_lock=True
)
```
We need to do an auto-lock renew on the received message if it is not processed within Peek Lock Timeout (configured as 300s) to avoid getting duplicate messages to subscribers. 

After looking at https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.autolockrenew?view=azure-python which seems to fulfill our requirement but it seems with version 0.50.0 the Message type is used from https://github.com/Azure/azure-sdk-for-python/blob/169a092048ffd6f01c9669a34c4ad5b9c426c886/sdk/servicebus/azure-servicebus/azure/servicebus/control_client/models.py#L149 which is not the supported type in AutoLockRenew Class which requires a renewable type as of https://github.com/Azure/azure-sdk-for-python/blob/169a092048ffd6f01c9669a34c4ad5b9c426c886/sdk/servicebus/azure-servicebus/azure/servicebus/common/message.py#L21 

Is there anything I am missing or new control_client Message should be supported in AutoLockRenew class.

**Comment by annatisch** [comment]
Thanks @neerajmangal 
The `control_client.Message` is not intended to be supported by the AutoLockRenew class.
Have you tried receiving messages through the SubscriptionClient?
```python
sub_client = SubscriptionClient.from_connection_string(conn_str, subscription_name, topic=topic_name)
with sub_client.get_receiver(idle_timeout=5) as receiver:
    for message in receiver:
        auto_renewer.register(message)
        process_message(message)
        message.complete()
```

**Comment by neerajmangal** [comment]
Thanks for quick reply, @annatisch. 

We looked at the SubscriptionClient before as this supports AutoLockRenew Class. We had to use ServiceBusService due to below reasons - 

- We need to run our application (consumer of Azure Service Bus) in Corporate Network. Currently, we are not able to connect to service bus from the corporate network over AMQP using a connection string or via ServiceBusClient. 

```bash
connection_str = "Endpoint=sb://{}.servicebus.windows.net/;SharedAccessKeyName={};SharedAccessKey={}".format(
    service_namespace, key_name, key_value)

topic_name= "Test_topic"
subscription_name = "Test"
client = SubscriptionClient.from_connection_string(name=subscription_name,
                                                   conn_str=connection_str,
                                                   topic=topic_name)

# Or using ServiceBusClient as well

client = ServiceBusClient(
        service_namespace=service_namespace,
        shared_access_key_name=key_name,
        shared_access_key_value=key_value
    )

subs_client = client.get_subscription(
        topic_name=topic,
        subscription_name=subscription
)
```

Getting below error in both cases. 
```bash
Traceback (most recent call last):
  File "/Users/mangal/anaconda3/lib/python3.6/site-packages/azure/servicebus/receive_handler.py", line 311, in open
    while not self._handler.auth_complete():
  File "/Users/mangal/anaconda3/lib/python3.6/site-packages/uamqp/client.py", line 369, in auth_complete
    raise compat.TimeoutException("Authorization timeout.")
TimeoutError: Authorization timeout.
```

Though this can be a firewall issue, IIUIC python SDK for ServiceBus does not have WebSockets supports as of now for AMQP? Is there anything I am missing in here, I could not find any option to provide transport type?

Also, we did not get this issue with ServiceBusService from control_client as this is HTTP based?

- We also get this message, not sure how to set up certificates for this, seems to be coming from here - https://github.com/Azure/azure-uamqp-python/blob/7f667c1fb9c0d3bc5a2783af68ffe2dac1c6175b/uamqp/authentication/common.py#L106 

```
Unable to set external certificates.
```

Thanks.

**Comment by annatisch** [comment]
It seems like this issue will be resolved once websockets are supported.
Websocket support is already an open issue #4250

**Comment by deeagar** [comment]
@neerajmangal - I have a follow up question for the exact same issue in this thread.
Even if you use AutoLockRenew.register() method in python which takes care of automatically renewing the lock for you - in case the `renewable.renew_lock()` throws an exception if message lock expired, it fails silently and it doesn't give  

The parent thread which is still executing business logic keeps on executing (until it calls `message.complete()` when actually it would know about it) but the same time, the same message appears in the queue and second instance takes it up for processing! This mean the same message is now being processed simultaneously by 2 different receivers!

What is the recommended way of resolving this?
