### ISSUE TITLE
NetApp ANF snapshots not preserving 'tags' or returning 'creation_date'

### ISSUE THREAD

**Issue by bnaylor** [Azure/azure-sdk-for-python#6778]
There seem to be a couple of missing bits in the snapshot api.

The definition includes both tags and a (readonly) creation_date:

```
class Snapshot(Model):
    """Snapshot of a Volume.
    Variables are only populated by the server, and will be ignored when
    sending a request.
    All required parameters must be populated in order to send to Azure.
    :param location: Required. Resource location
    :type location: str
    :ivar id: Resource Id
    :vartype id: str
    :ivar name: Resource name
    :vartype name: str
    :ivar type: Resource type
    :vartype type: str
    :param tags: Resource tags
    :type tags: object
    :ivar snapshot_id: snapshotId. UUID v4 used to identify the Snapshot
    :vartype snapshot_id: str
    :param file_system_id: fileSystemId. UUID v4 used to identify the
     FileSystem
    :type file_system_id: str
    :ivar creation_date: name. The creation date of the snapshot
    :vartype creation_date: datetime
    :ivar provisioning_state: Azure lifecycle management
    :vartype provisioning_state: str
    """
```

UI Note: In the Azure UI, I can definitely see a creation date exists for a given snapshot, however there are no UI knobs for tags (screenshots attached)..

I am sending tags in a create request but they don't "stick":

create:
```
{'additional_properties': {}, 'location': 'eastus', 'id': None, 'name': None,
 'type': None, 'tags': {'snaptag1': 'atag', 
'dfo-id': '1ff6cdaa-bde6-11e9-839e-f40f24312fd8', 
'dfo-creation-time': 'Tue Aug 13 16:19:28 2019'}, 
'snapshot_id': None, 'file_system_id': '038973af-3829-a1c1-3213-6c56b4e0f26a', 
'creation_date': None, 'provisioning_state': None}
```

..however when the same snapshot is retrieved with 'get', 'tags' and 'creation_date' are None:

```
{'additional_properties': {}, 'location': 'eastus', 
'id': '/subscriptions/d7a8de29-b829-45c0-b898-2cbafd35e3a3/resourceGroups/scratch-rg/providers/Microsoft.NetApp/netAppAccounts/scratch/capacityPools/scratch-pool1/volumes/honk/snapshots/snap4', 
'name': 'scratch/scratch-pool1/honk/snap4', 
'type': 'Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots', 
'tags': None, 'snapshot_id': '7835e10a-611a-44fe-7e83-1d045065b2f4', 
'file_system_id': '038973af-3829-a1c1-3213-6c56b4e0f26a', 
'creation_date': None, 'provisioning_state': 'Succeeded'}
```

<img width="1057" alt="Screen Shot 2019-08-13 at 12 28 57 PM" src="https://user-images.githubusercontent.com/15640869/62959079-f77ecc80-bdc5-11e9-8043-14bf6dd73389.png">

<img width="1415" alt="Screen Shot 2019-08-13 at 12 29 48 PM" src="https://user-images.githubusercontent.com/15640869/62959144-17ae8b80-bdc6-11e9-8b48-63304f0f1572.png">

**Comment by johanste** [comment]
The [OpenAPI specification for the service](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/netapp/resource-manager/Microsoft.NetApp/stable/2019-06-01/netapp.json#L2219) looks incorrect to me. Should be addressed by the service team.

**Comment by lichunli-ms** [comment]
Tags are not supported for Snapshot. It is a bug that the REST API spec listed it in the definition. We will update the API spec to remove it. Regarding creation_date, it should have return values instead of “None”. We will work on fixing this second bug. Thank you for reporting the issues to us!

**Comment by kartikshah9** [comment]
@lichunli-ms could you provide an update on the bug called out above. If the bug has been fixed request if you can close the GitHub issue.

**Comment by amishra-dev** [comment]
Please reactivate if you are still facing this
