### ISSUE TITLE
Add generic PATCH support to ResourcesOperations

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Azure/azure-sdk-for-python#682]
azure.mgmt.resource.resources.operations.ResourcesOperations supports PUT via create_or_update but it would be preferable to also support PATCH for resources that benefit from it. One example come to mind immediately: update policies on a KeyVault.

**Comment by lmazuel** [comment]
Hi @clarkbreyman-yammer 

I agree with you, but we need to handle this by adding definition inside the Resources Swagger file. Could you open this issue on the RestApi repo?
https://github.com/Azure/azure-rest-api-specs/issues
Thanks,

**Comment by lmazuel** [comment]
I have created the issue in the RestApi repository. I close this bug here, when the RestApi issue will be closed, if they add the Patch operation it will be automatically pushed here.
Thanks for the report!
