### ISSUE TITLE
Need support in the sdk to query the currently supported k8s versions 

### ISSUE THREAD

**Issue by subodh-dharma** [Azure/azure-sdk-for-python#6820]
I have observed in the recent past that AKS/Container Services (Kubernetes) discontinues support to some k8s versions and add some more, this is dynamic and unexpected when it comes to creating an Azure Kubernetes cluster using the SDKs. We need to update the configuration files manually based on the command line output given below or the AKS support page.

It would be great if there is a function in Golang and Python SDKs to check for the available k8s versions that are currently supported by AKS and also get a list of allowable upgrade k8s version from the current version.

The output can be a json map with output similar to what the following command has:

```
az aks get-versions --location eastus --output table

KubernetesVersion    Upgrades
-------------------  ------------------------
1.14.5               None available
1.13.9               1.14.5
1.12.8               1.13.9
1.12.7               1.12.8, 1.13.9
1.11.10              1.12.7, 1.12.8
1.11.9               1.11.10, 1.12.7, 1.12.8
1.10.13              1.11.9, 1.11.10
1.10.12              1.10.13, 1.11.9, 1.11.10
```

**Comment by subodh-dharma** [comment]
Creating this issue based on suggestion from @MicahMcKittrick-MSFT in the issue https://github.com/MicrosoftDocs/azure-docs/issues/37102

**Comment by seanmck** [comment]
Available versions can be queried from the "list orchestrators" API: https://docs.microsoft.com/en-us/rest/api/container-service/container%20service%20client/listorchestrators 
Upgrade options for a given cluster is available via "upgrade profile": https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/getupgradeprofile

Both should be accessible via the SDKs.
