### ISSUE TITLE
azure dependency are in conflict with minimal azure dependecies from ansible

### ISSUE THREAD

**Issue by ssbarnea** [Azure/azure-sdk-for-python#6830]
I was surprised to discovered that installing latest `azure==4.0.0` with pip brings an outdated versions of `azure-mgmt-storage~=2.0.0` which is older then the minimal version needed by ansible `3.1.0`.

I suspect this is caused by outdated dependencies in azure:
```
azure-mgmt 4.0.0 has requirement azure-mgmt-storage~=2.0, but you have azure-mgmt-storage 4.0.0.
```

**Comment by johanste** [comment]
Good catch. @scbedd, we should make sure that we warn if the metapackages drift from the latest non-preview version of referenced packages.

**Comment by lmazuel** [comment]
`azure` meta-package is now officially deprecated and can't be installed anymore
