### ISSUE TITLE
[EventProcessor] Sync version of EventProcessor

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#6842]
Implement sync EventProcessor and sync data store plug-in.

**Comment by ramya-rao-a** [comment]
@yunhaoling, @YijunXieMS Didnt we do this for the latest preview 5? If so, please provide a link to the package and close this issue

**Comment by yunhaoling** [comment]
internal sync event processor is supported, close this issue.
Related packages:
https://pypi.org/project/azure-eventhub/5.0.0b5/
https://pypi.org/project/azure-eventhub-checkpointstoreblob/
