### ISSUE TITLE
Add CI Check to ensure latest metapackage dependencies match latest dependency in the repository

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#6854]
Example: `azure-mgmt` metapackage [dependency](https://github.com/Azure/azure-sdk-for-python/blob/cccc5f72a1c0c57cc8f2f6fe0f0a123b99a1193e/sdk/core/azure-mgmt/setup.py#L89
) for `azure-mgmt-storage` is set to `~=2.0.0`

The newest value of this package (inside the repo!) is `azure-mgmt-storage-4.0.0`. 

[setup.py reflecting this](https://github.com/Azure/azure-sdk-for-python/blob/cccc5f72a1c0c57cc8f2f6fe0f0a123b99a1193e/sdk/storage/azure-mgmt-storage/azure/mgmt/storage/version.py#L8)

We need to ensure that the build picks up the drifting metapackage dependencies.

#6830

**Comment by praveenkuttappan** [comment]
@lmazuel : We have discussed about this pending item on metapackage dependency. Could you please let us know if there is any new info on this one.

**Comment by lmazuel** [comment]
Meta-packages have been deprecated
