### ISSUE TITLE
AutoLockRenew instantiation error?

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-sdk-for-python#6878]
I am trying to use `AutoLockRenew` functinality in service bus and there must be something I really miss out, as I cannot even create a lock object. I boiled down to the following

```
09:03 $ python3
Python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:13:32) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.servicebus.aio import AutoLockRenew
>>> locker = AutoLockRenew()
Traceback (most recent call last):
  File "/Users/aca286/anaconda3/lib/python3.6/site-packages/azure/servicebus/common/utils.py", line 27, in get_running_loop
    return asyncio.get_running_loop()
AttributeError: module 'asyncio' has no attribute 'get_running_loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aca286/anaconda3/lib/python3.6/site-packages/azure/servicebus/aio/async_utils.py", line 47, in __init__
    self.loop = loop or get_running_loop()
  File "/Users/aca286/anaconda3/lib/python3.6/site-packages/azure/servicebus/common/utils.py", line 31, in get_running_loop
    raise RuntimeError('No running event loop')
RuntimeError: No running event loop
>>> 
```

Installed versions follows:

```
09:10 $ pip3 freeze | grep azure
azure-common==1.1.23
azure-cosmos==3.0.2
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.20.0
azure-mgmt-network==0.20.1
azure-mgmt-nspkg==1.0.0
azure-mgmt-resource==0.20.1
azure-mgmt-storage==0.20.0
azure-nspkg==3.0.2
azure-servicebus==0.50.0
azure-servicemanagement-legacy==0.20.1
azure-storage-blob==1.4.0
azure-storage-common==1.4.0
azure-storage-file==1.4.0
azure-storage-nspkg==3.0.0
azure-storage-queue==1.4.0
msrestazure==0.6.1
```

**Comment by annatisch** [comment]
Thanks @andreacassioli - when running the async version as is the case here, there does need to be a running event loop. It looks like you're running from terminal rather than from a script? In that case you could try something like:
```python
from azure.servicebus.aio import AutoLockRenew
import asyncio

loop = asyncio.get_event_loop()
lock = AutoLockRenew(loop=loop)
```

**Comment by andreacassioli** [comment]
@annatisch I have a small application that monitors a service bus and process messages. Each processing can be pretty long and therefore I need to autorenew the lock (in the current implementation we implement the heartbeat ourselves...). 

I would expect the API to create the event loop itself. No mention of `loop` in the docs:
https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.autolockrenew?view=azure-python

I'll give it a try.

**Comment by annatisch** [comment]
Thanks @andreacassioli - I will update the documentation.
I'll close this issue as resolved for now - if you're still having trouble here, let me know if I need to reopen it :)
