### ISSUE TITLE
Using blob.upload_blob from blob.aio causes Unclosed client session

### ISSUE THREAD

**Issue by pkarb** [Azure/azure-sdk-for-python#6888]
**Using blob.upload_blob from blob.aio causes Unclosed client session**
Test code taken from the documentation: [https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob )
and samples: [https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob/tests](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob/tests)

_**Code**_ : 
`import azure.storage.blob.aio as storage`
`import asyncio`

`async def uploadBlob():`
    `with open("./info.txt", "rb") as data:`
       `await blob.upload_blob(data)`

`blob = storage.BlobClient.from_connection_string("DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxxx;EndpointSuffix=core.windows.net", container="asynctest", blob="my_blob")`
`#asyncio.run(uploadBlob())`
`loop = asyncio.get_event_loop()`
`loop.run_until_complete(uploadBlob())`

**Causes:**
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D33B5C8988>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001D33B7139A8>, 113308.796)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001D33B5C87C8>

**Comment by annatisch** [comment]
Thanks @pkarb!
Try running in an async context manager (`async with`):
```python
import azure.storage.blob.aio as storage
import asyncio

async def uploadBlob(blob_client):
    async with blob_client as blob:
        with open("./info.txt", "rb") as data:
            await blob.upload_blob(data)

blob = storage.BlobClient.from_connection_string("DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxxx;EndpointSuffix=core.windows.net", container="asynctest", blob="my_blob")
loop = asyncio.get_event_loop()
loop.run_until_complete(uploadBlob(blob))
```

**Comment by pkarb** [comment]
> Thanks @pkarb!
> Try running in an async context manager (async with):

Can you please provide the complete code that you think will work? I tried using @asynccontextmanager but that did not help. I am using 3.7

**Comment by annatisch** [comment]
Hi @pkarb - the code I provided in the snippet above should work without the warning.
You could also do it like this:
```python
import azure.storage.blob.aio as storage
import asyncio

async def upload_blob(conn_str):
    async with storage.BlobClient.from_connection_string(conn_str, container="asynctest", blob="my_blob") as blob:
        with open("./info.txt", "rb") as data:
            await blob.upload_blob(data)

conn_str = "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxxx;EndpointSuffix=core.windows.net"
loop = asyncio.get_event_loop()
loop.run_until_complete(upload_blob(conn_str))
```

**Comment by pkarb** [comment]
Thanks. Both the code snippets work. Thanks for your help.

**Comment by vikramadhav** [comment]
Above soultion still fails if ResourceExistsError exception thrown , Any work around for that ?
