### ISSUE TITLE
Service-level README

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#6913]
From a [PR comment](https://github.com/Azure/azure-sdk-for-python/pull/5679#issuecomment-505662667):

>Even if there is no metapackage there should be a general key vault service level readme with simple links to specific key vault package READMEs and one line explanations on when to use them - otherwise navigating the repo gets complicated and confusing

Which is to say, we should have a readme about Key Vault generally in azure-sdk-for-python/sdk/keyvault/

**Comment by mayurid** [comment]
#7740 is taking care of this
