### ISSUE TITLE
Will there be an Azure Blob Storage persistence client for event hub checkpointing in the new sdk for python?

### ISSUE THREAD

**Issue by harycane** [Azure/azure-sdk-for-python#6924]
The new azure-sdk-for-python library has an example of sqllite implementation as means for persisting checkpointing with the new event processor architecture. Will there be a similar implementation class that would enable persisting checkpointing in azure blob storage, as was available in the old sdk library - azure-event-hubs-python?

**Comment by kaerm** [comment]
Hi @harycane thanks for reaching out! Tagging appropriate teams cc: @ramya-rao-a

**Comment by vikrantlw** [comment]
Hi @yunhaoling

After installing the latest master branch of git repo:https://github.com/Azure/azure-sdk-for-python.git
by python setup.py install command which include above updated links in SDK folder.
following error occurred:
    from azure.eventhub.extensions.checkpointstoreblobaio import BlobPartitionManager
ModuleNotFoundError: No module named 'azure.eventhub.extensions.checkpointstoreblobaio'

**Comment by yunhaoling** [comment]
Hello @vikrantlw

Just to confirm:
Have you run the install command for both packages (azure-eventhub and azure-eventhub-checkpointstoreblob-aio)?

If so, are you installing them in edit mode or non-edit mode?

**Comment by vikrantlw** [comment]
Hi Adam,

Yes,I install both the packages.
It's installed using non-edit mode by following command
Python setup.py install

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yunhaoling** [comment]
Hello @vikrantlw ,

Yes, I confirm the problem you said. Can you try installing the packages by go into the package directory and run command `pip install .` to install the packages?

**Comment by fatal10110** [comment]
@yunhaoling Hi, thanks for the blob storage checkpoint store!

But isn't it require to set a lease on a blob?
Example: On k8s when you release a new version in case you have a running consumer pod, then k8s will run another consumer pod, so there will be some point in time when there are two consumers listening to the same EventHub and same consumer group, then both of them will raise to update the checkpoint.

I thought maybe it should set a lease on the blob for X minutes, and renew the lease on each checkpoint update.

Thanks!

**Comment by yunhaoling** [comment]
Hi @fatal10110 ,

In our currently implementations, we don't rely on the blob lease for partition ownership management. We're doing the ownership management by ourselves.

Internally, we've defined a new ownership class which is responsible for maintaining the ownership information of each partitions. It contains information about the ownership duration, ownerid etc. 

More detailed implementation can be found [here](https://github.com/Azure/azure-sdk-for-python/blob/1ad000af6a1e64c6c2399acea03285a9558d08da/sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/blobstoragepmaio.py#L81).

**Comment by annatisch** [comment]
Azure Blob storage checkpoint store is now published as a standalone package:
https://pypi.org/project/azure-eventhub-checkpointstoreblob/
https://pypi.org/project/azure-eventhub-checkpointstoreblob-aio/

Note: Preview B6 will be released shortly, which will include breaking changes from the current B5.
For compatibility, the preview version of the checkpoint store should match that of the eventhubs SDK (e.g. eventhubs 5.0.0b5 with checkpointstoreblob 1.0.0b5)
