### ISSUE TITLE
Cognitive Services docstrings state that uploads can be used, but library doesn't actually support it

### ISSUE THREAD

**Issue by yuhui** [Azure/azure-sdk-for-python#6933]
# Expected result

The Cognitive Services docstrings state that uploads can be sent to the endpoint.

E.g.
https://github.com/Azure/azure-sdk-for-python/blob/decd1a4f9220146f0e6e263a65938cadb3d6c527/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py#L19-L26

Note this line:

```
Two input methods are supported -- (1) Uploading an image or (2) specifying an image URL.
```

# Actual result

In reality, the code doesn't actually support uploads. E.g. for the `analyze_image()` function, only a publicly reachable `url` of an image can be used.

# Next steps

Update the docstrings to reflect how the library's functions should be used in reality.

**Comment by suside** [comment]
Worth noting that this still works:
```python
image = open('./test.jpg', 'rb')
results = computervision_client.analyze_image_in_stream(image)
```
so this is indeed only docstrings issue.

**Comment by lmazuel** [comment]
Closing this issue, since we will not re-ship version of this pakage anymore (new versions are coming in a different package name), and the issue was documentation only, with behavior ok (thanks @suside for the snippet :)).
