### ISSUE TITLE
Trigger Builds of Dependent Packages on PR

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#6953]
Situation: there are code changes under `sdk/core/azure-core`

Right now, only `python - core - ci` build will be triggered. What about the packages that _depend_ on `azure-core`? 

We need to either:
A) Trigger Additional Builds
B) Expand Package Selection to include the dependent packages

I will note that we really don't want to gate `azure-core` checkins based on building _every package_ that depends on it. PR pipelines will get super long in that method.

Possibly trigger `python - storage - ci` based on sdk/core TOO? That would work.

Additionally, this should apply to the `tools` folder as well as any of the `sdk` packages.

**Comment by lmazuel** [comment]
Just note that you said in Teams @scbedd : should apply to "tools" folder as well, so any code changes in the test framework test everything

**Comment by scbedd** [comment]
@lmazuel Ack. See edited description

**Comment by scbedd** [comment]
Finish tools folder changes prior to closing this.

**Comment by lmazuel** [comment]
Done, closing
