### ISSUE TITLE
Always Run Pylint/MyPy

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#6954]
Right now failures during test execution will cause Pylint and MyPy to not run. Need to add `succeededOrFailed()` condition to the two jobs.

**Comment by praveenkuttappan** [comment]
Scott has already added SucceededOrFailed condition. Leaving it open for few more days to learn about engineering systems

**Comment by praveenkuttappan** [comment]
Scott has already taken care of these changes
