### ISSUE TITLE
API version should not be generated as a parameter with a default value for operations classes when using composite swagger

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#697]
For example, as of rc5, the vm operations class generated for the compute mgmt package (https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/operations/virtual_machines_operations.py) has the following definition for the get method:

    def get(self, resource_group_name, vm_name, api_version="2016-03-30", expand=None, custom_headers=None, raw=False, **operation_config):

Since specifying an API version other than 2016-03-30 has the potential to break the client (the schema for responses is allowed to change between API versions), the api_version shouldn't be a parameter to the method. Instead, it should be a class level attribute or similar.

**Comment by lmazuel** [comment]
Thanks for the bug report :)

Yes, this should be an operation class attribute.

**Comment by lmazuel** [comment]
@johanste Could you write your exact needs. I mean, not what it should not be, but what you need in your code :)
I told @annatisch that it was a metadata inspection, is this correct?

**Comment by lmazuel** [comment]
Fixed in 0.30.0rc6: https://pypi.python.org/pypi/azure-mgmt-compute/0.30.0rc6
Thanks!
