### ISSUE TITLE
Missing enum UltraSSD_LRS in StorageAccountTypes

### ISSUE THREAD

**Issue by samyak4680** [Azure/azure-sdk-for-python#6975]
I am using Ultra SSD disks (available in the preview mode).
Using Python SDK, I am getting the following output while getting the VM details in REST API:

->
Deserializer is not able to find UltraSSD_LRS as valid enum in <enum 'StorageAccountTypes'>
<-

Can you please get the UltraSSD_LRS enum added to the StorageAccountTypes to fix this issue?

I am using following azure versions:
azure==4.0.0
azure-storage==0.36.0
azure-storage-blob==1.5.0
azure-storage-common==1.4.2
azure-storage-file==1.4.0
azure-storage-queue==1.4.0

**Comment by zezha-msft** [comment]
Hi @samyak4680, this seems to be an issue in the management-plane SDK, not the data-plane ones you've listed. Could you please provide a full `pip freeze`?

On a side note, it appears that you have both the legacy monolithic library `azure-storage` and the split packages installed at the same time. Please uninstall and then re-install the split packages only.

**Comment by samyak4680** [comment]
Thanks @zezha-msft, and all for looking in this issue.

I have tried uninstalling all the azure sdk, and then install the specific ones.
Following is the pip freeze output:

#pip freeze | grep azure
azure-common==1.1.23
azure-mgmt-compute==6.0.0
azure-mgmt-dns==3.0.0
azure-mgmt-network==5.0.0
azure-nspkg==3.0.2
azure-storage==0.36.0
msrestazure==0.6.1

Still I am getting the same output:

Deserializer is not able to find UltraSSD_LRS as valid enum in <enum 'StorageAccountTypes'>

Can you please confirm if above packages are not the latest ones, or if I am missing something.

Thanks.

**Comment by zezha-msft** [comment]
@annatisch could you please tag the management plane SDK's maintainer here?

**Comment by annatisch** [comment]
Thanks @zezha-msft - though I believe this is a generated SDK driven by the swagger spec.
Adding the swagger code owners: @jasonyang-msft @xiaonlimsft

FYI @lmazuel

**Comment by samyak4680** [comment]
Any updates on this..?

**Comment by xiafu-msft** [comment]
Hi @samyak4680,

Sorry about the delay of response! I'm looking it now

**Comment by vinjiang** [comment]
@blueww , can you take a look from mgmt SDK perspective.

**Comment by blueww** [comment]
'StorageAccountTypes' is defined in compute management plane swagger, not in storage swagger. The API is owned by compute team/
https://github.com/Azure/azure-rest-api-specs/blob/535109d5f9dae0e789affb02cb13bce8727feb44/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json#L7106

So remove storage tag, and add compute tag.

**Comment by Vaibhav-Agar** [comment]
Since the issue was opened very close to the actual launch of Ultra SSD, this might just be due to the changes rolling after the issue was created. Can @samyak4680 or someone verify if the issue still exists? If not, I will like to close this. Thanks!

**Comment by Vaibhav-Agar** [comment]
Hi @samyak4680,

I am resolving this now as I don't believe that this issue exists anymore. If you still see this, please feel free to re-open.
