### ISSUE TITLE
unable to obtain userdelegationkey

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-sdk-for-python#6977]
The current storage API does not have the ability to obtain a userdelegationkey.  As is, there doesn't appear to be a way for a user with "Storage Blob Delegator" permissions to generate SAS tokens.

https://docs.microsoft.com/en-us/rest/api/storageservices/get-user-delegation-key

The previous incarnation of azure.storage.blob supported this via get_user_delegation_key().  The results could be passed into generate_blob_shared_access_signature().

**Comment by zezha-msft** [comment]
@bmc-msft thanks for reaching out!

This has been fixed in version 12.0.0b3. The docs are [here](https://azure.github.io/azure-sdk-for-python/ref/azure.storage.blob.html#azure.storage.blob.blob_service_client.BlobServiceClient.get_user_delegation_key).
