### ISSUE TITLE
[Storage] ImportError: Unable to create async transport

### ISSUE THREAD

**Issue by sakintoye** [Azure/azure-sdk-for-python#6978]
I'm trying to use the async implementation of `download_blob()` from the Blob Client.
```
from azure.storage.blob.aio import BlobClient

client = BlobClient("<<my-blob-url-with-sas-token>>")

with open("<<my-directory-path>>", "wb") as handler:
     stream = await self.client.download_blob()
     blob_data = await stream.content_as_bytes()
     handler.write(blob_data)
```

When I run the code above,  an exception `ImportError: Unable to create async transport. Please check aiohttp is installed.` is raised

Does the SDK not ship with `aiohttp`?

**Comment by sakintoye** [comment]
Thanks @annatisch. "Extras" could be an approach worth considering 
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by kurtzeborn** [comment]
As @annatisch mentioned, we don't ship aiohttp by default.  For developers wanting to use the async functionality, they need to install it themselves or an alternative http library.
