### ISSUE TITLE
azure-cognitiveservices-language-luis 0.3.0 & python 3.6, 3.7 

### ISSUE THREAD

**Issue by in4margaret** [Azure/azure-sdk-for-python#6987]
TypeError: Attempted to reuse key: 'failed'

Reproduce: 
pip install azure-cognitiveservices-language-luis
Create app.py 
add to that file:
from azure.cognitiveservices.language.luis.authoring import LUISAuthoringClient
from msrest.authentication import CognitiveServicesCredentials
Run app.py

Code: 
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/_luis_authoring_client_enums.py#L25

**Comment by lmazuel** [comment]
Sorry for the late answer here, this issue has been fixed after 0.3.1.
Thanks!
