### ISSUE TITLE
ImportError: No module named 'msrest'

### ISSUE THREAD

**Issue by zfrenchee** [Azure/azure-sdk-for-python#703]
Hello Azure developers! 

I've just done a fresh install of python 3, then fresh `pip3.5 install azure` and I open up the shell, and do `from azure.common.credentials import ServicePrincipalCredentials` and this is what I get:

	Python 3.5.1 (default, Jan 22 2016, 08:54:32)
	[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
	Type "help", "copyright", "credits" or "license" for more information.
	>>> from azure.common.credentials import ServicePrincipalCredentials
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/site-packages/azure/common/credentials.py", line 19, in <module>
	    from msrest.authentication import (
	ImportError: No module named 'msrest'

Now, my guess is msrest is not a package I'm supposed to have by default on my machine, so I'm perplexed why it isn't listed as a dependency and installed with "azure" when I use pip. 

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-common/azure/common/credentials.py

Let me know if I've misunderstood this in any important way. Otherwise, this issue is a request that the Azure PyPi package be packaged to also list and install msrest as a dependency.

**Comment by lmazuel** [comment]
The documentation you used for this code is using the 2.0.0RC5 version of the SDK. Since it's a release candidate, you have to install it using the `--pre` flag:
http://azure-sdk-for-python.readthedocs.io/en/latest/#installation

If you don't use the flag, you will install the `1.0.3` version which does not have `msrest` in dependencies. We plan to release the stable version which will avoid using `--pre` very soon (this month probably).

**Comment by zfrenchee** [comment]
Using the `--pre` flag I get errors: 

    Failed building wheel for azure
    ----------------------------------------
    Failed building wheel for azure-mgmt

**Comment by lmazuel** [comment]
Coud you give the full trace of your `pip install --pre azure` command? And what OS / Python version used?
Thanks,

**Comment by zfrenchee** [comment]
~/Documents/Fraenkel/fraenkel_galaxy_scripts » pip install --pre azure                [py3env]Alex@Maxs-MacBook-Pro-3
    Collecting azure
      Downloading azure-2.0.0rc5.zip
    Collecting azure-mgmt==0.30.0rc5 (from azure)
      Downloading azure-mgmt-0.30.0rc5.zip
    Collecting azure-batch==0.30.0rc5 (from azure)
      Downloading azure_batch-0.30.0rc5-py2.py3-none-any.whl (275kB)
        100% |████████████████████████████████| 276kB 2.5MB/s
    Collecting azure-graphrbac==0.30.0rc5 (from azure)
      Downloading azure_graphrbac-0.30.0rc5-py2.py3-none-any.whl (50kB)
        100% |████████████████████████████████| 51kB 6.8MB/s
    Requirement already satisfied (use --upgrade to upgrade): azure-servicebus==0.20.1 in ./py3env/lib/python3.5/site-packages (from azure)
    Collecting azure-storage==0.32.0 (from azure)
      Downloading azure_storage-0.32.0-py3-none-any.whl (160kB)
        100% |████████████████████████████████| 163kB 4.1MB/s
    Collecting azure-servicemanagement-legacy==0.20.3 (from azure)
      Downloading azure_servicemanagement_legacy-0.20.3-py2.py3-none-any.whl (78kB)
        100% |████████████████████████████████| 81kB 3.2MB/s
    Collecting azure-mgmt-authorization==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_authorization-0.30.0rc5-py2.py3-none-any.whl
    Collecting azure-mgmt-batch==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_batch-0.30.0rc5-py2.py3-none-any.whl
    Collecting azure-mgmt-cdn==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_cdn-0.30.0rc5-py2.py3-none-any.whl (57kB)
        100% |████████████████████████████████| 61kB 5.5MB/s
    Collecting azure-mgmt-cognitiveservices==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_cognitiveservices-0.30.0rc5-py2.py3-none-any.whl
    Collecting azure-mgmt-commerce==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_commerce-0.30.0rc5-py2.py3-none-any.whl
    Collecting azure-mgmt-compute==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_compute-0.30.0rc5-py2.py3-none-any.whl (141kB)
        100% |████████████████████████████████| 143kB 5.2MB/s
    Collecting azure-mgmt-logic==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_logic-0.30.0rc5-py2.py3-none-any.whl (60kB)
        100% |████████████████████████████████| 61kB 5.7MB/s
    Collecting azure-mgmt-network==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_network-0.30.0rc5-py2.py3-none-any.whl (175kB)
        100% |████████████████████████████████| 184kB 3.9MB/s
    Collecting azure-mgmt-notificationhubs==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_notificationhubs-0.30.0rc5-py2.py3-none-any.whl (47kB)
        100% |████████████████████████████████| 51kB 7.2MB/s
    Collecting azure-mgmt-powerbiembedded==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_powerbiembedded-0.30.0rc5-py2.py3-none-any.whl
    Collecting azure-mgmt-redis==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_redis-0.30.0rc5-py2.py3-none-any.whl
    Collecting azure-mgmt-resource==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_resource-0.30.0rc5-py2.py3-none-any.whl (131kB)
        100% |████████████████████████████████| 133kB 5.3MB/s
    Collecting azure-mgmt-scheduler==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_scheduler-0.30.0rc5-py2.py3-none-any.whl (51kB)
        100% |████████████████████████████████| 61kB 8.1MB/s
    Collecting azure-mgmt-storage==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_storage-0.30.0rc5-py2.py3-none-any.whl
    Collecting azure-mgmt-web==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure)
      Downloading azure_mgmt_web-0.30.0rc5-py2.py3-none-any.whl (249kB)
        100% |████████████████████████████████| 256kB 3.1MB/s
    Requirement already satisfied (use --upgrade to upgrade): azure-common[autorest]==1.1.4 in ./py3env/lib/python3.5/site-packages (from azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): requests in ./py3env/lib/python3.5/site-packages (from azure-servicebus==0.20.1->azure)
    Requirement already satisfied (use --upgrade to upgrade): azure-nspkg in ./py3env/lib/python3.5/site-packages (from azure-storage==0.32.0->azure)
    Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./py3env/lib/python3.5/site-packages (from azure-storage==0.32.0->azure)
    Requirement already satisfied (use --upgrade to upgrade): azure-mgmt-nspkg in ./py3env/lib/python3.5/site-packages (from azure-mgmt-authorization==0.30.0rc5->azure-mgmt==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): msrestazure<0.5.0,>=0.4.0; extra == "autorest" in ./py3env/lib/python3.5/site-packages (from azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): msrest<0.5.0,>=0.4.0; extra == "autorest" in ./py3env/lib/python3.5/site-packages (from azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./py3env/lib/python3.5/site-packages (from python-dateutil->azure-storage==0.32.0->azure)
    Requirement already satisfied (use --upgrade to upgrade): chardet>=2.3.0 in ./py3env/lib/python3.5/site-packages (from msrest<0.5.0,>=0.4.0; extra == "autorest"->azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): certifi>=2015.9.6.2 in ./py3env/lib/python3.5/site-packages (from msrest<0.5.0,>=0.4.0; extra == "autorest"->azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in ./py3env/lib/python3.5/site-packages (from msrest<0.5.0,>=0.4.0; extra == "autorest"->azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): keyring>=5.6 in ./py3env/lib/python3.5/site-packages (from msrest<0.5.0,>=0.4.0; extra == "autorest"->azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): requests-oauthlib>=0.5.0 in ./py3env/lib/python3.5/site-packages (from msrest<0.5.0,>=0.4.0; extra == "autorest"->azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): isodate>=0.5.4 in ./py3env/lib/python3.5/site-packages (from msrest<0.5.0,>=0.4.0; extra == "autorest"->azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Requirement already satisfied (use --upgrade to upgrade): oauthlib>=0.6.2 in ./py3env/lib/python3.5/site-packages (from requests-oauthlib>=0.5.0->msrest<0.5.0,>=0.4.0; extra == "autorest"->azure-common[autorest]==1.1.4->azure-batch==0.30.0rc5->azure)
    Building wheels for collected packages: azure, azure-mgmt
      Running setup.py bdist_wheel for azure ... error
      Complete output from command /Users/Alex/Google_Drive/Documents/Fraenkel/fraenkel_galaxy_scripts/py3env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/c7/_cfym4nj2zng9zf206vbxs9m0000gp/T/pip-build-di9siwmi/azure/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/c7/_cfym4nj2zng9zf206vbxs9m0000gp/T/tmp9v4wb5cgpip-wheel- --python-tag cp35:
      running bdist_wheel
      running build
      installing to build/bdist.macosx-10.11-x86_64/wheel
      running install
      running install_egg_info
      running egg_info
      writing top-level names to azure.egg-info/top_level.txt
      writing requirements to azure.egg-info/requires.txt
      writing azure.egg-info/PKG-INFO
      writing dependency_links to azure.egg-info/dependency_links.txt
      warning: manifest_maker: standard file '-c' not found

      reading manifest file 'azure.egg-info/SOURCES.txt'
      writing manifest file 'azure.egg-info/SOURCES.txt'
      Copying azure.egg-info to build/bdist.macosx-10.11-x86_64/wheel/azure-2.0.0rc5.data/purelib/azure-2.0.0rc5-py3.5.egg-info
      running install_scripts
      writing list of installed files to 'RECORD.txt'
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/c7/_cfym4nj2zng9zf206vbxs9m0000gp/T/pip-build-di9siwmi/azure/setup.py", line 63, in <module>
          'azure-servicemanagement-legacy==0.20.3',
        File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
          self.run_command(cmd)
        File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/Users/Alex/Google_Drive/Documents/Fraenkel/fraenkel_galaxy_scripts/py3env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
          archive_basename = self.get_archive_basename()
        File "/Users/Alex/Google_Drive/Documents/Fraenkel/fraenkel_galaxy_scripts/py3env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/Users/Alex/Google_Drive/Documents/Fraenkel/fraenkel_galaxy_scripts/py3env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
          assert tag == supported_tags[0]
      AssertionError

      ----------------------------------------
      Failed building wheel for azure
      Running setup.py clean for azure
      Running setup.py bdist_wheel for azure-mgmt ... error
      Complete output from command /Users/Alex/Google_Drive/Documents/Fraenkel/fraenkel_galaxy_scripts/py3env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/c7/_cfym4nj2zng9zf206vbxs9m0000gp/T/pip-build-di9siwmi/azure-mgmt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/c7/_cfym4nj2zng9zf206vbxs9m0000gp/T/tmp31hsa8_ypip-wheel- --python-tag cp35:
      running bdist_wheel
      running build
      installing to build/bdist.macosx-10.11-x86_64/wheel
      running install
      running install_egg_info
      running egg_info
      writing top-level names to azure_mgmt.egg-info/top_level.txt
      writing requirements to azure_mgmt.egg-info/requires.txt
      writing azure_mgmt.egg-info/PKG-INFO
      writing dependency_links to azure_mgmt.egg-info/dependency_links.txt
      warning: manifest_maker: standard file '-c' not found

      reading manifest file 'azure_mgmt.egg-info/SOURCES.txt'
      writing manifest file 'azure_mgmt.egg-info/SOURCES.txt'
      Copying azure_mgmt.egg-info to build/bdist.macosx-10.11-x86_64/wheel/azure_mgmt-0.30.0rc5.data/purelib/azure_mgmt-0.30.0rc5-py3.5.egg-info
      running install_scripts
      writing list of installed files to 'RECORD.txt'
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/c7/_cfym4nj2zng9zf206vbxs9m0000gp/T/pip-build-di9siwmi/azure-mgmt/setup.py", line 71, in <module>
          'azure-mgmt-web==0.30.0rc5',
        File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
          self.run_command(cmd)
        File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/Users/Alex/Google_Drive/Documents/Fraenkel/fraenkel_galaxy_scripts/py3env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
          archive_basename = self.get_archive_basename()
        File "/Users/Alex/Google_Drive/Documents/Fraenkel/fraenkel_galaxy_scripts/py3env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/Users/Alex/Google_Drive/Documents/Fraenkel/fraenkel_galaxy_scripts/py3env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
          assert tag == supported_tags[0]
      AssertionError

      ----------------------------------------
      Failed building wheel for azure-mgmt
      Running setup.py clean for azure-mgmt
    Failed to build azure azure-mgmt
    Installing collected packages: azure-mgmt-authorization, azure-mgmt-batch, azure-mgmt-cdn, azure-mgmt-cognitiveservices, azure-mgmt-commerce, azure-mgmt-compute, azure-mgmt-logic, azure-mgmt-network, azure-mgmt-notificationhubs, azure-mgmt-powerbiembedded, azure-mgmt-redis, azure-mgmt-resource, azure-mgmt-scheduler, azure-mgmt-storage, azure-mgmt-web, azure-mgmt, azure-batch, azure-graphrbac, azure-storage, azure-servicemanagement-legacy, azure
      Found existing installation: azure-mgmt-compute 0.20.1
        Uninstalling azure-mgmt-compute-0.20.1:
          Successfully uninstalled azure-mgmt-compute-0.20.1
      Found existing installation: azure-mgmt-network 0.20.1
        Uninstalling azure-mgmt-network-0.20.1:
          Successfully uninstalled azure-mgmt-network-0.20.1
      Found existing installation: azure-mgmt-resource 0.20.1
        Uninstalling azure-mgmt-resource-0.20.1:
          Successfully uninstalled azure-mgmt-resource-0.20.1
      Found existing installation: azure-mgmt-storage 0.20.0
        Uninstalling azure-mgmt-storage-0.20.0:
          Successfully uninstalled azure-mgmt-storage-0.20.0
      Found existing installation: azure-mgmt 0.20.2
        Uninstalling azure-mgmt-0.20.2:
          Successfully uninstalled azure-mgmt-0.20.2
      Running setup.py install for azure-mgmt ... done
      Found existing installation: azure-storage 0.20.3
        Uninstalling azure-storage-0.20.3:
          Successfully uninstalled azure-storage-0.20.3
      Found existing installation: azure-servicemanagement-legacy 0.20.2
        Uninstalling azure-servicemanagement-legacy-0.20.2:
          Successfully uninstalled azure-servicemanagement-legacy-0.20.2
      Running setup.py install for azure ... done
    Successfully installed azure-2.0.0rc5 azure-batch-0.30.0rc5 azure-graphrbac-0.30.0rc5 azure-mgmt-0.30.0rc5 azure-mgmt-authorization-0.30.0rc5 azure-mgmt-batch-0.30.0rc5 azure-mgmt-cdn-0.30.0rc5 azure-mgmt-cognitiveservices-0.30.0rc5 azure-mgmt-commerce-0.30.0rc5 azure-mgmt-compute-0.30.0rc5 azure-mgmt-logic-0.30.0rc5 azure-mgmt-network-0.30.0rc5 azure-mgmt-notificationhubs-0.30.0rc5 azure-mgmt-powerbiembedded-0.30.0rc5 azure-mgmt-redis-0.30.0rc5 azure-mgmt-resource-0.30.0rc5 azure-mgmt-scheduler-0.30.0rc5 azure-mgmt-storage-0.30.0rc5 azure-mgmt-web-0.30.0rc5 azure-servicemanagement-legacy-0.20.3 azure-storage-0.32.0

**Comment by lmazuel** [comment]
Based on your trace, the installation was still possible anyway and is written `Successfully installed` (` Running setup.py install for azure-mgmt ... done)`

We had problems with wheels building and `azure` and `azure-mgmt` packages with old version of `pip`. Could you try to update your pip and retry?

**Comment by zfrenchee** [comment]
I'm using 8.1.2, it still gives me the same output.

**Comment by lmazuel** [comment]
I uploaded `azure` and `azure-mgmt` wheel files on PyPI. Should be better now if you could try?

**Comment by zfrenchee** [comment]
success!
