### ISSUE TITLE
event_processor.py:87> exception=KeyError('partition_ids')

### ISSUE THREAD

**Issue by hbensalem** [Azure/azure-sdk-for-python#7054]
I'm trying out the event_processor example and I keep getting this error:
`future: <Task finished coro=<EventProcessor.start() done, defined at C:\Users\bensa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\eventhub\eventprocessor\event_processor.py:87> exception=KeyError('partition_ids')>
Traceback (most recent call last):
  File "C:\Users\bensa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\eventhub\eventprocessor\event_processor.py", line 98, in start
    partition_ids = await self._eventhub_client.get_partition_ids()
  File "C:\Users\bensa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\eventhub\aio\client_async.py", line 156, in get_partition_ids
    return (await self.get_properties())['partition_ids']
KeyError: 'partition_ids'`

**Comment by yunhaoling** [comment]
Hello @hbensalem,

are you trying to connect to an iothub or an eventhub?

**Comment by mayurid** [comment]
@hbensalem : Are you still experiencing this issue? Please let us know.

**Comment by annatisch** [comment]
Hi @hbensalem - I'm going to close this as I think it has been resolved.
If you are still experiencing errors, please let us know and we can re-open :)
