### ISSUE TITLE
Face: How can I dumps 'detect' result into json string?

### ISSUE THREAD

**Issue by xenogew** [Azure/azure-sdk-for-python#7072]
From the title question.
And all other of the package models that is object when return from function call or other else.
I can't use `json.dumps(obj)` to show the json string out of the model object.

**Comment by kaerm** [comment]
@xenogew thanks for reporting this! Our team will take a look at this

**Comment by v-xuto** [comment]
Hi, @xenogew 
The solution to this problem is shown in the following code.
```
import json

result = 'Return value of function or method'

if isinstance (result, (list, dict, str)):
  # If the return value type is:  list dict str
  json.dumps (result)
if isinstance (result, object):
  # If the return value is an object
  json.dumps (result .__ dict__)
```

**Comment by v-xuto** [comment]
@jongio

**Comment by v-xuto** [comment]
Hi @xenogew,
How is this issue going? Feel free to let us know if further help is needed.

**Comment by tzhanl** [comment]
we are going to close this issue because we haven’t heard from you in a few days, but please re-open it if the issue still persists.
