### ISSUE TITLE
Cosmos DB: Python SDK reference API docs issue

### ISSUE THREAD

**Issue by deborahc** [Azure/azure-sdk-for-python#7088]
This link: http://cosmosproto.westus.azurecontainer.io/#azure.cosmos.CosmosClient appears to be broken. 

In addition, the Microsoft reference docs (https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.cosmos_client.cosmosclient?view=azure-python&viewFallbackFrom=azure-python-preview) still reflect V3 of the SDK. Can the V4 preview API reference docs be published under the Preview banner?

@christopheranderson , @srinathnarayanan, @SnehaGunda

**Comment by zikalino** [comment]
i will check this.

**Comment by kaerm** [comment]
@deborahc preview docs have been staged [here](https://review.docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.cosmos_client.cosmosclient?view=azure-python-preview&branch=master) and will be merged soon

**Comment by annatisch** [comment]
The links in the readme have been fixed and the latest preview 4 docs should be live by the end of the week.
Preview docs are also published here:
https://azure.github.io/azure-sdk-for-python/
