### ISSUE TITLE
find out the nodes that are scheduled for patching in update management using log analytics

### ISSUE THREAD

**Issue by shashankpai** [Azure/azure-sdk-for-python#7090]
I want to find out if a particular node is scheduled for patching or not using log analytics . I want to know the deployment schedule of that particular node in update management. How can i find out?

I am using LogAnalyticsDataClient currently. Can anyone please help ?

```
query = {"query": """Update
                | where TimeGenerated>ago(5h) and OSType!="Linux" and (Optional==false or Classification has "Critical" or Classification has "Security") 
                | summarize hint.strategy=partitioned arg_max(TimeGenerated, UpdateState, Classification, Approved) by Computer, SourceComputerId, UpdateID 
                | where (UpdateState=~"Installed" or UpdateState=~"Needed")  and Approved!=false and Computer=~ "{}" """.format(node_name)}
i = self.loganalys_client.query(self.workspace_id,tquery)
```

I am getting the patching status , Need to know if any node is scheduled for patching as well as its patching schedule.

**Comment by kaerm** [comment]
Thanks @shashankpai I am tagging the right team to take a look at this

**Comment by shashankpai** [comment]
any update on this issue @kaerm

**Comment by jomessec** [comment]
Upcoming schedules aren't available from within Log Analytics. You will need to query the Automation APIs to get the software update configurations. Please note that any update configurations which use dynamic groups will resolve the final set of machines at patch time, so there is not an a priori way to reliably show upcoming patch runs on a given machine.
