### ISSUE TITLE
analyze_deps should discover true incompatibilities, versus differing version specifiers

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#7102]
Example:
* `azure-storage-blob` takes dependency on `azure-core<2.0.0,>=1.0.0b3`
* `azure-keyvault-secrets` takes dependency on `azure-core<2.0.0,>=1.0.0b2`

There are no true incompatibilities here, 1.0.0b3 will work with `azure-keyvault-secrets`. Can our dependency analysis check the actual incompatibility of the selected versions instead of whether or not the version specifiers match?

I spoke with @bsiegel for additional context after a quick discussion with @chlowell and @lmazuel . Our understanding is that this was a deliberate choice by the higher-ups to keep things straightforward. This was the reason that the `analyze_deps` was implemented this way.

**Comment by bsiegel** [comment]
Our dependency story has basically two phases.

Phase 1: All libraries within an SDK ***must*** use the same version range / specifier for a given dependency. Deviations / overrides are permitted temporarily but must be resolved before GA. This is the easiest way to enforce that we ship libraries that will work together correctly (both technically, and it's the easiest policy to reason about), but it adds some burden / overhead on the library developers when one library needs a newer version of a dependency. We are in Phase 1 right now.

Phase 2: All libraries within an SDK ***should*** use the same version range / specifier for a given dependency. Permanent deviations are permitted as long as the alternate version range / specifier remains compatible with the specifier(s) used by all other libraries in the SDK. Incompatible deviations are permitted temporarily but must be resolved before GA. We want to get to here but most likely after GA of Track 2.

**Comment by xiangyan99** [comment]
And it will be great that 
1. If the dependencies are compatible, we don't stop the check in.
2. If the dependencies does not perfectly match, we generate a report and developers can decide how to fix it.

**Comment by bsiegel** [comment]
We discussed this a bit at length on Monday and it sounds like we may decide not to go this route. We'll have further discussions but it sounds like the policy of keeping exact dependency version specifiers in sync for all libraries in an SDK may not change.

**Comment by xiangyan99** [comment]
It makes total sense that we have same dependency version within an SDK when we release.  And I don't think there is a conflict between release one version vs we allow different versions in the development mode(temporarily). If we use incompatibility check during the development mode and enable the strict check in the release pipeline. Do you think it make sense?

**Comment by scbedd** [comment]
Investigate using `poetry` tool to solve this problem.

**Comment by scbedd** [comment]
We still want a `warning` thrown from the `analyze_deps` step if the version specifiers don't match. Just because they're `compatible` does not mean that we shouldn't keep these up to date.

**Comment by scbedd** [comment]
I spoke with @johanste this afternoon. I am removing the `blocking_release` label as this is not actually blocking release right now. The issue stays open and should be addressed much sooner rather than later.

**Comment by scbedd** [comment]
Resolved in #29224!
