### ISSUE TITLE
Python SDK for  azure AKS available 

### ISSUE THREAD

**Issue by tamilhce** [Azure/azure-sdk-for-python#7112]
I'm looking for python sdk for azure AKS service.
I need python API to create /delete AKS cluster 
Do we have any update on this.

**Comment by kaerm** [comment]
Hi @tamilhce thanks for asking. Tagging it so that the right team can help you find answers. Thanks!

**Comment by vishaltak** [comment]
@zikalino - The [docs](https://docs.microsoft.com/en-us/azure/container-service/kubernetes/container-service-kubernetes-walkthrough) mention that ACS has retried and it sees not active development. Most ACS APIs are also blocked.

Starting Azure==5.0.0 release, all packages are split into individual packages. However, there is no clarity about which SDK to use for AKS.

Could you provide some clarification regarding the above whether to use the same "azure-mgmt-containerservice" SDK for interacting with AKS or is there something else. Any documented SDK code example to create/delete k8s clusters would be greatly helpful.

Thanks!

**Comment by RodgeFu** [comment]
@vishaltak, a quick answer as Zim mentioned, yes, azure-mgmt-containerservice is for interacting with AKS.

@zikalino , could you help to provide some example? Thanks.

**Comment by vishaltak** [comment]
@RodgeFu - Thanks for the clarification. Could you also shed some light about the deprecation? Will AKS SDK for Python continue to be a part of "azure-mgmt-containerservice"; especially since ACS is deprecated. Sorry for bothering you but I was confused after reading the deprecation notes for ACS and assumed that the library also would not see active development.

**Comment by RodgeFu** [comment]
Add 'service attention' label for service team to provide more details about the deprecation of ACS. thanks.

**Comment by kaerm** [comment]
Thanks for the clarification. I am closing this as it seems that `azure-mgmt-containerservice` is the right package to use in this case. Feel free to open a new issue in case of any follow ups
