### ISSUE TITLE
ServiceBus Abandon Message to re-queue 

### ISSUE THREAD

**Issue by silencev** [Azure/azure-sdk-for-python#7120]
## Reproduce
1. session enabled queue
2. put two messages to queue with **same session ID**
    - The two messages have sequence numbers of 1 and 2 respectively
3. start a **SessionReceiver** with **Prefetch set to 0**
4. receive first message with PeekLock mode sequence number is **1**
5. **abandon** first message.
6. receive next message, however, the sequence number is **2**
7. keep receiving message, sequence number is **1**

## Expected result
when message is get abandoned, the order of message in SAME session should not be changed.

I'm not sure if my expected result is correct, please correct me if I'm wrong

**Comment by kaerm** [comment]
@silencev thanks for reporting this - I am tagging the right team to take a look at it

**Comment by annatisch** [comment]
Thanks @silencev 
@nemakam - could you please confirm the correct service behaviour in this scenario?

**Comment by annatisch** [comment]
@binzywu  - Are you able to confirm the service behaviour in this scenario?

**Comment by nemakam** [comment]
@annatisch I just wrote a sample app with .net sdk and unable to repro this. 
Once I abandon a message, I get back the same message. Could you debug this further on the python sdk.?

**Comment by mayurid** [comment]
@KieranBrantnerMagee : could you please take a look at this

**Comment by KieranBrantnerMagee** [comment]
Look taken :)  

The problem appears to be dealt with via AMQP 1.2.3.  
Was able to produce a repro under 1.2.2 and validate fixed post-upgrade.

Users can apply this fix via `pip install --upgrade uamqp` or specifying a > version dependency in a requirements file.

Am integrating the test to ensure this into a larger parallel effort to improve tests; if others would prefer a standalone I can certainly do so but will post-factum link this with that PR when it appears.

Thanks both for reporting this and for your patience @silencev!
