### ISSUE TITLE
How do you use resource filters?

### ISSUE THREAD

**Issue by lvh** [Azure/azure-sdk-for-python#713]
I've successfully made a ResourceManagementClient and it can list resources with `client.resources.list()`. I'd like to filter them by type, to e.g. access compute resources. The list method has a `filter` kwarg that looks appropriate, but the docstring/Swagger doesn't explain how to use it.

I've found this document online: https://msdn.microsoft.com/en-us/library/azure/dn790569.aspx which suggests a format. I've tried both:

```
filter="startswith(resourceType, \"Microsoft.Storage\")"
```

and 

```
filter="startswith(resourceType, Microsoft.Storage)")
```

... and in both cases I get:

```
CloudError: Invalid $filter 'startswith(resourceType, Microsoft.Storage)' specified in the query string.
```

I've also looked at the C# client, but that appears to have a bunch of extra magic so that people don't have to construct strings themselves.

**Comment by lvh** [comment]
I have also tried `'type eq "Microsoft.Storage/storageAccounts"'`, with and without quotes, and URL-quoted variants of all of the above.

**Comment by lmazuel** [comment]
The odata filter is using single quotes:
```python
graphrbac_client.user_operations.list(filter="displayName eq 'Test Buddy'")
```

**Comment by lvh** [comment]
Awesome, thanks! Where can I find the full set of available properties? `kind` seems like what I want.

**Comment by lvh** [comment]
The expression `list(rmc.resources.list(filter="type eq 'Microsoft.Storage/storageAccounts'"))` results in the same aforementioned error.

**Comment by lmazuel** [comment]
Each service team decides what they want to support, so I recommend looking at the RestAPI documentation of the specific operation you want. Base on the one you gave, it seems that the supported property are `tagname`, `tagvalue` `name`, `location` and `resourceType`.

**Comment by lmazuel** [comment]
Hi @lvh 

Did you retry using resourceType?
```python
list(rmc.resources.list(filter="resourceType eq 'Microsoft.Storage/storageAccounts'")
```

**Comment by lvh** [comment]
Hey; sorry -- I wasn't sure that that was an appropriate thing to add for the resolution of this ticket. This was a few days ago, but ISTR that resourceType worked fine. Is there a way to find this in a standardized way other than Googling and hoping for the best?

**Comment by lmazuel** [comment]
Not really, each service team supports a different set of keyword :(
The best way I recommend is to look at the RestAPI documentation of the given operation you need, since we don't parse the string and send them directly to the RestAPI.

**Comment by lmazuel** [comment]
Hi @lvh 
Could we close this issue? Thanks!

**Comment by lvh** [comment]
Sure! I mean, it's not really "solved" in the general sense but this isn't a reasonable place to track it :)

**Comment by YashrajSP7** [comment]
How do you query using multiple tags or attributes
