### ISSUE TITLE
LiveTest runs are yellow due to no coverage file being generated

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#7210]
During the `publish coverage` phase of the pipeline, there is no `.coverage` file to `generate xml` off of. This is because we disable coverage during livetests.

Our tests are _not_ failing, but this failing step is turning the job status to yellow. Just need to update the `build-test.yml` to properly handle this so that our livetests will be green again.

**Comment by weshaggard** [comment]
@praveenkuttappan  can you look to see if this is still an issue?

**Comment by praveenkuttappan** [comment]
Sure. I will take a look at it today.
