### ISSUE TITLE
Broken cross-ref links in various docs

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#7219]
Several package docs at https://azure.github.io/azure-sdk-for-python/ have cross-references to classes that do not render properly, e.g.:

<img width="591" alt="Screen Shot 2019-09-11 at 2 20 07 PM" src="https://user-images.githubusercontent.com/1078448/64736415-70457700-d49f-11e9-8113-a58a30a641e0.png">

* https://azure.github.io/azure-sdk-for-python/ref/azure.eventhub.html#azure.eventhub.consumer.EventHubConsumer.receive

* https://azure.github.io/azure-sdk-for-python/ref/azure.servicebus.html#azure.servicebus.servicebus_client.ServiceBusClient.get_queue

* https://azure.github.io/azure-sdk-for-python/ref/azure.storage.queue.html#azure.storage.queue.queue_client.QueueClient.create_queue

* https://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.secrets.html#azure.keyvault.secrets.client.SecretClient.backup_secret

(This list is not exhaustive, just specific examples in different packages)

I made a small PR to fix this in keyvault: https://github.com/Azure/azure-sdk-for-python/pull/7215 using explicit directives:
```
:class:`~foo.Bar`
```
 etc. But noted that although things work with this change, the rendered appearance is also different from the "implicitly" rendered cross reference links (I guess these are generated by sphinx-apidoc?)  i.e.

<img width="346" alt="Screen Shot 2019-09-11 at 2 25 10 PM" src="https://user-images.githubusercontent.com/1078448/64736661-011c5280-d4a0-11e9-96b6-b61fd11e0efb.png"> 

VS

<img width="314" alt="Screen Shot 2019-09-11 at 2 24 25 PM" src="https://user-images.githubusercontent.com/1078448/64736675-06799d00-d4a0-11e9-971d-0d5351fff1a6.png">

The second version is the version with explicit `:class:` (though without a leading tilde to shorten) and is apparently used already in some SDKs. I am not sure how else to fix this problem except to use explicit directives, and FWIW I have only ever used explicit directives in the past.

**Comment by chlowell** [comment]
My belief (may well be incorrect) is that tildes control the rendered style. So in your penultimate screenshot, I infer the link was "~foo.Pipeline", and that "\`~foo.Pipeline\`" would have rendered with the same style as your final screenshot.

**Comment by bryevdv** [comment]
The tildes control whether the full dotted path is displayed or not. So 
```
:class:`foo.Bar`  ==> "foo.Bar:"

but 

:class:`~foo.Bar` ==> "Bar"
```
The difference between the last two that I am specifically referring to is the "plain text" blue link (which is how the implicit cross refs seem to render everywhere) vs the "outlined" fixed width text (which is how the explicit `:class:` version renders everywhere).

**Comment by chlowell** [comment]
Sorry, I meant "backticks" when I wrote "tildes".

**Comment by bryevdv** [comment]
Oh, no adding just backticks without the `:class:` in front just renderers the same broken link text, only italicized (I tried, just to be sure). Also, most of the working implicit cross ref links *don't* have backticks

**Comment by bryevdv** [comment]
Also, AFAIK, single backticks don't actually do much useful, so I have been surprised to see them so much. If you want fixed-width `<pre>` kind of text, that takes *double* backticks.

**Comment by xiangyan99** [comment]
Looks like it is fixed.
