### ISSUE TITLE
Missing model fields in Event Hubs Management class

### ISSUE THREAD

**Issue by F-Joachim** [Azure/azure-sdk-for-python#7231]
The model class `azure.mgmt.eventhub.v2017_04_01.models.Destination` does not include the properties: 
- `dataLakeSubscriptionId`
- `dataLakeAccountName`
- `dataLakeFolderPath`

Under these circumstances it is not possible to enable the "Capture" feature with specifying an Azure DataLake Store.

Hint: A direct HTTP request to the corresponding address `https://management.azure.com/subscriptions/{SubscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.EventHub/namespaces/{EventHubsNamespace}/eventhubs/{EventHubsEntity}` (with specified API-Version 2017-04-01) accepts/expects the fields.

**Comment by ha-gg-i** [comment]
Hello,

can you estimate when the issue will be processed?

Thank you

**Comment by kaerm** [comment]
@zikalino do you have any estimates?

**Comment by MarkLeon** [comment]
Any updates on this? Thanks.

**Comment by kaerm** [comment]
@nickzhums could you take a look at this?

**Comment by vamathan** [comment]
Hi Team,

Is there an ETA on this ? With this issue, Microsoft.Azure.Management.EventHub .NET SDK is not able to successfully create EventHubs.

Is there a work around or alternative to create Azure EventHub namespaces and EventHubs via .NET C# SDK ?

**Comment by nickzhums** [comment]
@RodgeFu @zikalino could you please help with this

**Comment by vamathan** [comment]
I see a similar issue with .Net SDK. Do we have an issue tracker for .Net SDK ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nickzhums** [comment]
@vamathan could you please open a new issue in .NET for this? thanks

**Comment by nickzhums** [comment]
@vamathan @ha-gg-i it looks like the properties are not present in the swagger, therefore they are not exposed in the SDK. To expose these properties we need to start from the swagger, here's the issue to track:
https://github.com/Azure/azure-rest-api-specs/issues/2255

This is the swagger we are discussing about:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2017-04-01/EventHub.json

**Comment by xiangyan99** [comment]
@F-Joachim latest azure-mgmt-eventhub is 10.0.0. Does it work for you?

**Comment by F-Joachim** [comment]
@xiangyan99 Thanks for your reply.

At the moment I do not use the Python SDK. Therefore I can't test the new feature. Maybe another user can test the implementation.

**Comment by xiangyan99** [comment]
@F-Joachim Thanks for the reply. I will close the issue and please feel free to reopen it if you see it again.
