### ISSUE TITLE
[uAMQP] Change uamqp LinkRedirect logging from warning to info

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#7254]
When an EventHubConsumer that is created from an EventHubClient with IoT hub connection string receives events for the 1st time, a LinkRedirect redirects the client to the IoT hub's EventHubs endpoint. This is by design.
But uamqp logs "WARNING:uamqp.receiver:LinkRedirect(u'ErrorCodes.LinkRedirect',)".
This should be an INFO. Nothing is wrong.

**Comment by rakshith91** [comment]
this is fixed - LinkRedirect is already an info
https://github.com/Azure/azure-uamqp-python/blob/cdcf44c06a5d066447f702ddc959e3193495c300/uamqp/receiver.py#L267
