### ISSUE TITLE
Unable to make queries against newly created subscriptions from the Python SDK

### ISSUE THREAD

**Issue by KyrelJerome** [Azure/azure-sdk-for-python#7257]
When testing the “List Enabled Subscriptions” with the management group, we are unable to immediately see the newly created subscription but it was confirmed that this takes time to propagate in portal as well.
The subscription may be referenced through subscription ID, which is supplied in the 202 returned when querying to create a subscription. We've implemented this as a workaround in a production workflow. 
It is required that subscriptions are made visible for production automation, as subscription information is required for linking under management groups.

**Comment by anuragdalmia** [comment]
Apologies for the delay @KyrelJerome . Can you please help clarify your ask - are you asking that subscriptions be made available faster in the "List Enabled Subscriptions" API and that your current workaround doesnt work?

**Comment by anuragdalmia** [comment]
@KyrelJerome ping on this ask. Can you please clarify your ask.

**Comment by KyrelJerome** [comment]
A workaround has been found and documented, I'll close this ticket now.

**Comment by KyrelJerome** [comment]
Sorry for the late response, thank you for getting back to me!
