### ISSUE TITLE
'Resource Not Found' when trying to use ContentModeratorClient

### ISSUE THREAD

**Issue by EBazarov** [Azure/azure-sdk-for-python#7288]
Hi,

Already several days that I can't find what I have missed.
So I'm trying to make a small test of Azure `image_moderation` capability.
I'm using `SUBSCRIPTION_KEY="xxxxxxxxx"` and `CONTENT_MODERATOR_ENDPOINT="https://xxxxxxx.cognitiveservices.azure.com/contentmoderator"` which I was copied from my dashboard (quick start page). Here's my Subscription ID if you will search more info (a03e1f72-05de-480d-8915-19295c65cb1e).

So what I'm trying to do is simple as this :
```Python
from azure.cognitiveservices.vision.contentmoderator import ContentModeratorClient
from azure.cognitiveservices.vision.contentmoderator.models import Evaluate
from msrest.authentication import CognitiveServicesCredentials

SUBSCRIPTION_KEY="xxxxxxxxxx"
CONTENT_MODERATOR_ENDPOINT="https://xxxxxx.cognitiveservices.azure.com/contentmoderator"

client = ContentModeratorClient(
    endpoint=CONTENT_MODERATOR_ENDPOINT,
    credentials=CognitiveServicesCredentials(SUBSCRIPTION_KEY)
)

path_img = "path/to/img.jpeg"
with open(path_img, 'rb') as image:
    evaluation = client.image_moderation.evaluate_file_input(
        image_stream=image
    )
```
Or I have also tried to do with url
```
evaluation = client.image_moderation.evaluate_url_input(
    content_type="application/json",
    cache_image=False,
    data_representation="URL",
    value="https://images-na.ssl-images-amazon.com/images/I/61e%2BfD8ZYxL._UX679_.jpg"
)
```
And at the moment when I'm making call to API, when using `evaluate_file_input` or `evaluate_url_input` it gives me error like this :
```
---------------------------------------------------------------------------
APIErrorException                         Traceback (most recent call last)
<ipython-input-51-2fb729b8d71d> in <module>
      1 with open(path_img, 'rb') as image:
      2     response = client.image_moderation.evaluate_file_input(
----> 3         image_stream=image
      4     )

~/.local/share/virtualenvs/affinitas/lib/python3.5/site-packages/azure/cognitiveservices/vision/contentmoderator/operations/image_moderation_operations.py in evaluate_file_input(self, image_stream, cache_image, custom_headers, raw, callback, **operation_config)
    624 
    625         if response.status_code not in [200]:
--> 626             raise models.APIErrorException(self._deserialize, response)
    627 
    628         deserialized = None

APIErrorException: Operation returned an invalid status code 'Resource Not Found'
```
I already contacted azure services support and they said this shouldn't be the case and it should work. I hope you will help me find where is the issue.

**Comment by ChrisHMSFT** [comment]
Hi @EBazarov,

Please try using just the base part of the URL: https://xxxxxx.cognitiveservices.azure.com. The SDKs do not use the /contentmoderator part of the input. 

Thanks,
Chris

**Comment by ChrisHMSFT** [comment]
Hi @EBazarov,

Did the above suggestion solve your issue?

Thanks,
Chris

**Comment by EBazarov** [comment]
Thank you @ChrisHMSFT suggestion is worked for me 👍

**Comment by ChrisHMSFT** [comment]
Great to hear. Closing this issue. We have also opened a backlog item to review the content in the quick page on the portal to clarify the correct endpoint to use. 

Thanks!
Chris
