### ISSUE TITLE
[Core] Improve aiohttp ImportError catching

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#7298]
Currently in Core we catch an `ImportError` if aiohttp is not installed and suppress it.
This led to one situation where a more complicated error was hidden - so we should probably be a bit more clever about checking the error that we're suppressing to make sure it is what we think it is.
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/transport/__init__.py#L66

This could be simply doing a string comparison on the error message.

**Comment by xiangyan99** [comment]
Checked with Anna offline. Close it as by design.
