### ISSUE TITLE
[Key Vault] When creating vault, Sku.family has to be specified

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-sdk-for-python#733]
In https://github.com/Azure/azure-sdk-for-python/blob/dev/azure-mgmt-keyvault/azure/mgmt/keyvault/models/sku.py, Sku.family is marked as optional when it appears the server requires this.

Creating this issue to track https://github.com/Azure/azure-rest-api-specs/issues/462 as the API spec would be the root cause.

**Comment by lmazuel** [comment]
Thanks @derekbekoe !

**Comment by derekbekoe** [comment]
Refers to PR https://github.com/Azure/azure-sdk-for-python/pull/736

**Comment by lmazuel** [comment]
Fixed in 0.30.0rc6: https://pypi.python.org/pypi/azure-mgmt-keyvault/0.30.0rc6
Thanks!
