### ISSUE TITLE
CostManagementClient can't deserialize REST API response

### ISSUE THREAD

**Issue by jodzga** [Azure/azure-sdk-for-python#7338]
AFAIK in current version CostManagementClient simply does not work.
See example workaround here:
https://github.com/cloud-custodian/cloud-custodian/blob/e7197f1ea40c5e084c678a1020b70495854e48c7/tools/c7n_azure/c7n_azure/filters.py#L845

This is how it is used:
https://github.com/cloud-custodian/cloud-custodian/blob/e7197f1ea40c5e084c678a1020b70495854e48c7/tools/c7n_azure/c7n_azure/filters.py#L899

**Comment by ramaganesan-rg** [comment]
This is already fixed. Please feel free to validate if this issue persists and reopen as needed.
