### ISSUE TITLE
[uAMQP] Update underlying uAMQP-c library to the latest version

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#7342]
Need to contribute to the uAMQP-c library implementing desired-capabilities and share connection first and then update the dependency.

----------

The work needs more consideration.
- Are there strong points to update to the latest uamqp-c library, e.g. bug fix/new feature
- If we want to update the latest uamqp-c, we need to update our changes back to uamqp-c library as well.
- Maintenance of the c library

**Comment by ramya-rao-a** [comment]
@yunhaoling Didnt we get this done for the last preview 5 release?

**Comment by yunhaoling** [comment]
closing this issue -- The long term goal is to implement pure-python uamqp library, not c-based.
