### ISSUE TITLE
session enabled queue [serviceBus]

### ISSUE THREAD

**Issue by diegoguidotti** [Azure/azure-sdk-for-python#738]
I am trying to send and receive messages to a queue with sessionID enabled. I am not able to assign a sessionID to the message. I get a 405 code with the following message:

> "The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value."

I tried in several way to assign a sessionID to message with no result.

``` python
msg = Message()
msg.body="Test Message1212121212";
msg.group_id="111112222";
msg.session_id="111112222";
msg.sessionId="111112222";
msg.SessionId="111112222";
msg.custom_properties={'SessionId':121212121212}
bus_service.send_queue_message('SumQueue', msg)
```

**Comment by lmazuel** [comment]
The sessionId has to be defined in the broker_properties header:
```python
msg.broker_properties = '{"ForcePersistence": false, "Label": "My label" }'
```

more details about the syntax here:
https://msdn.microsoft.com/en-us/library/azure/hh780742.aspx

**Comment by lmazuel** [comment]
Hi @diegoguidotti do you confirm it's solves your problem?

Thank you

**Comment by diegoguidotti** [comment]
Thank you @lmazuel I have just tested now and it works.

Thank you,
Diego

**Comment by lmazuel** [comment]
Glad to help :)

**Comment by Grigorsuv96** [comment]
@lmazuel how can i receive when sessionId is enable ?
`msg = Message()
msg.broker_properties = {"SessionId":"test1"}
bus_service.receive_queue_message(EntityPath,msg)
`
