### ISSUE TITLE
How to you upload/download large files via python?

### ISSUE THREAD

**Issue by markseger** [Azure/azure-sdk-for-python#74]
I posted this in the azure forum and was told to ask here.  The bottom line is I couldn't find any example of how to do this and suspect my real problem is in how to specify the range of date I want to move around.

I'm trying to interact with blob storage from a python script and am discovering if the object is >60MB (I don't have an exact number) the upload fails.  Further reading told me I have to do it in chunks.  Still further reading pointed me to the x_ms_range optional parameter to the get/put calls.  It wasn't until many hours of digging through google and ultimately source code I discovered I need to say unicode('x-y') to get the range field recognized.

So now I have a piece of python code that looks like:

﻿﻿﻿print "GET 10k"
blob1 = blob_service.get_blob('mycontainer', '10k')
print "LEN 10K:", len(blob1)
blob2 = blob_service.get_blob('mycontainer', '10k', x_ms_range=unicode('1-100'))
print "LEN 10K:", len(blob2)

but when I run it I get, noting the GETBLOB and HEAD are additional print statements within the api code itself to prove it's recognizing the range I'm passing:

GET 10k
LEN 10K: 10000
GETBLOB: 1-100
HEAD: [('x-ms-range', '1-100'), ('x-ms-lease-id', None), ('x-ms-range-get-content-md5', None)]
LEN 10K: 10000

So this then turns into a multi-part question:
- am I specifying the range correctly?
- why isn't my second get returning 100 bytes instead of the whole object
- are there any examples of how to get a large object with the python API
  ﻿
  I'm exhausted, having already put multiple days into this and am hoping someone can save me...

-mark

**Comment by the-hof** [comment]
Which "blob_storage" object has a put_blob method?

**Comment by lmazuel** [comment]
Hi @the-hof , since the initial time when this issue was created, the storage data SDK is now here:
https://github.com/Azure/azure-storage-python
