### ISSUE TITLE
[Storage Blob] Request breaks when blob_name has a '~' character. 

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#7407]
The latest version of urllib3 (1.25.4) encodes ~ as %7E. This breaks the request since the Storage signing service refuses to accept %7E instead of ~. 

Issue in urllib3 to track: https://github.com/urllib3/urllib3/issues/1683 

Acceptability Criteria:
Fix this and uskip this [test](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/tests/test_common_blob.py#L231).

**Comment by lmazuel** [comment]
Fixed in urllib 1.25.6
