### ISSUE TITLE
Delete virtual machine returns None if succeed

### ISSUE THREAD

**Issue by zechenjiang** [Azure/azure-sdk-for-python#7416]
Trying to use the newest version to delete a virtual machine
```
compute_client = create_compute_client(credentials, subscription_id)
deletion_result = compute_client.virtual_machines.delete(group_name, name)
return deletion_result.result()
```
After debugging, deletion_result._polling_method._operation.resource is None. Should this return some info about deletion status?

**Comment by Drewm3** [comment]
@zechenjiang, I believe this is likely occurring because the async operation has not completed yet. Could you try adding the following line before attempting to view the results:

deletion_result.wait()

**Comment by zechenjiang** [comment]
@Drewm3 I tried your suggestion and still got None. This only happens when calling deletion api but I can get correct result for creating vm.

**Comment by zechenjiang** [comment]
Also at least for me it seems that result() function won't return until deletion has been completed.

**Comment by Drewm3** [comment]
Thanks @zechenjiang for your feedback. I will identify someone who has more details on the Python SDK to look into this issue.

**Comment by Drewm3** [comment]
Hi @zechenjiang, through my initial discussions with development the person I spoke with told me that he believes that None is the standard result for a successful delete. I am following-up with another expert to confirm this belief is correct.

**Comment by zechenjiang** [comment]
Hi @Drewm3 Thanks so much for the update. Using None as standard result for a successful delete could be misleading and this contradicts the comments in deletion function. Also, may I ask if Azure uses unique error code? network_client.subnets.get() returns "NotFound" as error code while  network_client.virtual_networks.get() return "ResourceNotFound" as error code. Is this design intended? There is no documentation for error code and this makes it difficult for developers to use.

**Comment by Drewm3** [comment]
Adding @zikalino to investigate why a response is not being returned here.

**Comment by zikalino** [comment]
@Drewm3 i have ben busy a bit, but I am checking this issue right now

**Comment by Drewm3** [comment]
@zikalino agreed to investigate this issue as an issue in the SDK.

**Comment by RodgeFu** [comment]
the response content and code is determined by service team and the defined swagger. Add "Service Attention" label to include service team to comment on the proper response expected. thanks.
