### ISSUE TITLE
[Storage Blob] Fails to cancel upload and re-upload with a different size

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#7430]
We get this error when uploading a valid content.

```
azure.core.exceptions.HttpResponseError: The specified blob or block content is invalid.
RequestId:41cf5647-701e-00a1-6530-73c15b000000
Time:2019-09-24T23:31:43.2698299Z
ErrorCode:InvalidBlobOrBlock
Error:None
```

Here are the steps to reproduce

1.  Start uploading a blob (overwrite an existing one) ( let's say 500 MB )
2. Interrupt the upload using Ctrl+C. Don't let it finish the upload
3. Start uploading the blob again, but with a different size (let's say 50 MB)

**Comment by rakshith91** [comment]
Note: if i delete the blob and upload it again, this issue won't happen.

**Comment by mikeharder** [comment]
An additional constraint may be that the cancelled upload was split into blocks, while the last upload is not split into blocks.  I observed this using the .NET client, the 500 MB upload is split into chunks, while the 50 MB upload is not.

**Comment by tasherif-msft** [comment]
This issue is resolved.
