### ISSUE TITLE
Service Bus type Message doesn't have a method to get the payload

### ISSUE THREAD

**Issue by epomatti** [Azure/azure-sdk-for-python#7440]
How can I get the payload from a Message other than calling `message.__str__()`?

I've spent some time looking for it and I couldn't find any. It's just weird to call it that way. I tried `body()` method but it returns a complex object instead of the actual "body" by which I mean the payload.

Tutorials and examples also give the standard `print(message)`.

Am I missing something?

Tried the reference too..

https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.common.message.message?view=azure-python

**Comment by kaerm** [comment]
Hi @epomatti thanks for asking, I'm tagging it for the right team take a look at this.

**Comment by annatisch** [comment]
Thanks @epomatti - you can access the data using the `body` attribute you described. This field simply returns a generator.
Messages can contain multiple sections of data, which is why it's present this way. So you could interact with it multiple ways:
```python
data = next(message.body)
data = list(message.body)[0]
```

**Comment by epomatti** [comment]
@annatisch thanks that did the trick, python newbie here
