### ISSUE TITLE
Adding public SSH key while creating a VM using ComputeManagementClient issue

### ISSUE THREAD

**Issue by tmarballi** [Azure/azure-sdk-for-python#745]
I am working on creating a virtual machine using this logic: http://azure-sdk-for-python.readthedocs.io/en/latest/resourcemanagementcomputenetwork.html#create-virtual-machine. In this I was hard coding the username and password to login until now and it works fine. But now, I want to add my public SSH key while creating a VM to allow login using ssh keys.
All I could find to do that belonged to the legacy code section: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementservice.py#L1290 where we can pass a configuration with the ssh key data. Is that recommended now to use or is there a way to do the same using the ComputeManagementClient way of creating a Virtual machine?

**Comment by lmazuel** [comment]
Hi @tmarballi 

Yes, you can do it. Take a look at the VM sample in Python here:
https://github.com/Azure-Samples/virtual-machines-python-manage/blob/master/example.py#L280

The `os_profile` node should be like this ([taken from here](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-sshkey)):
```python
'os_profile': {
      'computer_name': VM_NAME,
      'admin_username': USERNAME,
      "linux_configuration": {
         "disable_password_authentication": True,
         "ssh": {
             "public_keys": [{
                  "path": "/home/{}/.ssh/authorized_keys".format(USERNAME),
                  "key_data": "ssh-rsa ABCD....."
             }]
        }
     }
}
```
If you don't use the dict syntax, you can still use the model instance:
http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.compute.models.html#azure.mgmt.compute.models.OSProfile

**Comment by tmarballi** [comment]
Great @lmazuel I was not able to find it until now! Thanks a ton! I will try using that!

**Comment by tmarballi** [comment]
This worked, so closing this issue! Thanks for your help!
