### ISSUE TITLE
docs.microsoft.com is out of date respective to the master branch

### ISSUE THREAD

**Issue by sputnik13** [Azure/azure-sdk-for-python#7455]
The python SDK documentation on docs.microsoft.com is out of date respective to the master branch of the git repo.  Specifically

https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2019_03_01.operations.virtualmachinescalesetvmsoperations?view=azure-python#get-resource-group-name--vm-scale-set-name--instance-id--custom-headers-none--raw-false----operation-config-

does not reflect the change made in 

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_virtual_machine_scale_set_vms_operations.py#L520

This change was made in v7.0.0 of the compute module, and the current release (at least on pypi) is v8.0.0, so it doesn't seem like docs.microsoft.com is being updated automatically.

**Comment by kurtzeborn** [comment]
@scbedd, this is probably just a matter of when and how we release which I think just requires an explanation to the Mgmt team to set expectations.

**Comment by scbedd** [comment]
I will check the automation for this package.

**Comment by scbedd** [comment]
I'm confirming this is good to go now.

[Link to Appropriate Code Location](https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2019_03_01.operations.virtualmachinescalesetvmsoperations?view=azure-python#get-resource-group-name--vm-scale-set-name--instance-id--expand-none--custom-headers-none--raw-false----operation-config-)

Seems to me that it's successfully seeing `str or InstanceViewType` now.
