### ISSUE TITLE
conda list stops working after installing azure sdk

### ISSUE THREAD

**Issue by gtejeda** [Azure/azure-sdk-for-python#7461]
Guys, following the instructions found here:
https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-environment#local

from this tutorial, and right before running this command:
**pip install azureml-sdk[notebooks,automl]**

I can do a conda list and conda export, no problem.
after installing the sdk, conda list and conda export crash

....
....
....
....
An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y

any thoughts?

**Comment by vizhur** [comment]
That looks much like a conda issue
https://github.com/conda/conda/issues/9104

it was resolved with 4.7.12 version shipped on Sep 12. 
https://github.com/conda/conda/pull/9132

You can try to use latest version of conda or do pip freeze or pip list to get list of packages installed with pip only

**Comment by gtejeda** [comment]
You were 100% right vizhur
updating conda prior to installing the sdk solved the issue.
thanks

**Comment by johanste** [comment]
It sounds like this issue has been resolved. Closing.
