### ISSUE TITLE
Update EventHub Documentation to align with docs.microsoft requirements

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#7477]
Here is the [official documentation](https://review.docs.microsoft.com/en-us/help/onboard/admin/reference/python/documenting-api?branch=master#constructor-parameters) source if you need it.

Working Example:
[Source Code](https://github.com/Azure/azure-sdk-for-python/blob/dc7dfb004778c99f92a5d3e0b03e6de722c01888/sdk/core/azure-core/azure/core/pipeline/base.py#L101)
[Reflected on Docs.Microsoft](https://review.docs.microsoft.com/en-us/python/api/azure-core/azure.core.pipeline.pipeline?view=azure-python-preview&branch=master)

Failing Example:
[Source Code](https://github.com/Azure/azure-sdk-for-python/blob/dc7dfb004778c99f92a5d3e0b03e6de722c01888/sdk/eventhub/azure-eventhubs/azure/eventhub/aio/eventprocessor/event_processor.py#L28)
[Reflected on Docs.Microsoft](https://review.docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub.aio.eventprocessor.eventprocessor?view=azure-python-preview&branch=master)

The only difference I can tell between the two methods (one of which works and the other doesn't) is the fact that on the working one, _all_ RST is directly under the first doc comment. 

The broken one is broken because the params are placed on the `__init__` method rather than directly after the `class` def.

**Comment by annatisch** [comment]
All public facing EH docs now declare constructor params at the class level rather than the __init__ level
