### ISSUE TITLE
azure-appconfiguration component is not shipping HISTORY.md on PyPi

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-sdk-for-python#7494]
The ```azure-appconfiguration``` component is currently not shipping the ```HISTORY.md``` file on PyPi which is required by the ```setup.py``` script. Building the package from source is therefore not possible.

**Comment by kaerm** [comment]
@glaubitz thanks for reporting this! We will take a look at it

**Comment by scbedd** [comment]
I believe this will be fixed with the next release. Fixed as part of another [commit[(https://github.com/Azure/azure-sdk-for-python/commit/ab3f145f1cebafa8ed4e533073ad7eaf75b37108#diff-2eac4e3cd68e73f8d6fb0f2039669508).

**Comment by mayurid** [comment]
Thanks for reporting this. @xiangyan99 lets verify after the next release and update the issue.

**Comment by xiangyan99** [comment]
Verified in latest release on pypi. Fixed.
