### ISSUE TITLE
Feature request: Delete key/password_credentials & create additional next to existing one

### ISSUE THREAD

**Issue by MMollyy** [Azure/azure-sdk-for-python#7495]
https://docs.microsoft.com/en-us/python/api/azure-graphrbac/azure.graphrbac.operations.applicationsoperations?view=azure-python

In Powershell I have the option to delete keys & password, the Python SDK seems to be missing this functionality.
While update suffices for creating new tokens and updating existing ones, there is no option to delete keys.

Example:
Application has 10+ keys.
3 are expired, 7 are in use.
I want to delete just the 3 expired ones by means if itteration or whatever.

Use-case: I need to perform lifecycle management on the tokens of many applications, which I want a pipeline to take care of for me. So I need to itterate through a list of tokens on a list of applications to only delete tokens that validate against a time-period before deleting.

Edit:
Also the option to create another secret without overwriting the existing ones.

It seems the python sdk always overwrites the existing one.
As I can see here: https://github.com/Azure/azure-sdk-for-go/
That in the go SDK code there is support for multiple different use-cases, and it's basically all of these that I would like to see available in the python SDK for Azure as well. :)
In the code: https://github.com/hashicorp/vault-plugin-secrets-azure/blob/master/provider.go

**Comment by kaerm** [comment]
@MMollyy thanks for reporting this! I am tagging the right teams to take a look at this.

**Comment by MMollyy** [comment]
@kaerm Can I update the OP to include the creation of new tokens next to existing ones as well?
It seems the python sdk always overwrites the existing one.

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
