### ISSUE TITLE
Update Track 2 package Examples to leverage admonition directive.

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#7501]
## Context
Our `examples` are not rendering properly on docs.microsoft.com. Given our timelines, the docs team will not be able to make adjustments to support the pure `literalinclude` that we currently use. 

To account for this, we need to surround our literalincludes with `admonition` directives. Details follow.

## Direction

The issue here isn't that we are doing anything specifically _wrong_  so much as _different_ from what the doc team's CI pipelines ingestion requirements.

[Details from Doc's Team Documentation](https://review.docs.microsoft.com/en-us/help/onboard/admin/reference/python/documenting-api?branch=master#include)

### Example of Current Non-Compatible Code
This is the [Source](https://github.com/Azure/azure-sdk-for-python/blob/dbe3dce588db0ee7dc15131bac2d36879bcb97df/sdk/core/azure-core/azure/core/pipeline/base.py#L101) for additional context.

```
    Example:
        .. literalinclude:: ../examples/test_example_sync.py
            :start-after: [START build_pipeline]
            :end-before: [END build_pipeline]
            :language: python
            :dedent: 4
            :caption: Builds the pipeline for synchronous transport.
```

### Example of New, Compatible Code

The above code has been transformed _exactly_ as necessary to render properly. Note the sensitivity of a whitespace line between the literalinclude and the `admonition` directive. 

The whitespace is also consistent between these two examples. If you run `tox -e sphinx -c ../../../eng/tox/tox.ini` you should be able to ensure that your `example` is rendering properly. It should look something like this: 

```
    .. admonition:: Example:
    
        .. literalinclude:: ../examples/test_example_sync.py
            :start-after: [START build_pipeline]
            :end-before: [END build_pipeline]
            :language: python
            :dedent: 4
            :caption: Builds the pipeline for synchronous transport.
```

The goal is to ensure that your `literalinclude` is specified the same way as the above example. 

Please work through your codebases, and give a checkbox for all updated. The examples should look like this:

![image](https://user-images.githubusercontent.com/45376673/65909459-9020da00-e37d-11e9-8273-11c861b7d5a3.png)

## Checklist

- [x] `azure-core`
- [ ] `azure-identity`
- [ ] `azure-keyvault-keys`
- [ ] `azure-keyvault-secrets`
- [ ] `azure-keyvault-certificates`
- [x] `azure-storage-blob`
- [x] `azure-storage-file`
- [x] `azure-storage-queue`
- [ ] `azure-eventhub`
- [ ] `azure-eventhubs-checkpointstoreblob-aio`

**Comment by scbedd** [comment]
I am working through an example render with the docs team to 100% confirm the above with a test run.

**Comment by bryevdv** [comment]
FWIW here is a one-liner that should handle the obvious cases:
```
find . -name '*.py' -print0 | xargs -0 perl -pi -e 's/^    Example:$/    \.\. admonition:: Example:\n/g'
```

**Comment by scbedd** [comment]
Den published an individual test pipeline to confirm my changes. Example is showing now!

![image](https://user-images.githubusercontent.com/45376673/66104364-341ca800-e56d-11e9-8aac-1acc80799cec.png)

I adjusted a single docstring in `azure.core.pipeline`, and that example is now rendering!

**Comment by scbedd** [comment]
All our packages do this now, as all our packages are showing example code sourced out of the package itself. 👍
