### ISSUE TITLE
[Storage] Make offset and length consistent across APIs

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#7509]
Currently in some APIs we use offset and length and use start_range and end_range in others.

Behavior should be offset and length across APIs

**Comment by bryevdv** [comment]
If this is done then https://github.com/Azure/azure-sdk-for-python/issues/7061 can also be closed

**Comment by xiafu-msft** [comment]
https://github.com/xiafu-msft/azure-sdk-for-python/pull/2
