### ISSUE TITLE
azure-identity component is not shipping HISTORY.md on PyPi

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-sdk-for-python#7524]
The ```azure-identity``` component is currently not shipping the ```HISTORY.md``` file on PyPi which is required by the ```setup.py``` script. Building the package from source is therefore not possible.

**Comment by maggiepint** [comment]
Good call out!

@scbedd - last I checked you were the boss of python packaging?

**Comment by scbedd** [comment]
Hey @glaubitz, thanks for the report on this one as well.

As with the other issue, this is resolved in this [commit](https://github.com/Azure/azure-sdk-for-python/commit/ab3f145f1cebafa8ed4e533073ad7eaf75b37108#diff-2eac4e3cd68e73f8d6fb0f2039669508).

**Comment by johanste** [comment]
@chlowell, can you verify that this has been addressed?

**Comment by chlowell** [comment]
It has, our published source for 1.0.0b4 builds.

**Comment by chlowell** [comment]
Closing this as fixed, thank you for opening it.
