### ISSUE TITLE
403 AuthenticationFailedServer failed to authenticate the request

### ISSUE THREAD

**Issue by HassankSalim** [Azure/azure-sdk-for-python#7525]
[https://openshiftstagingv39logs.blob.core.windows.net/project-1/device-1/abc%20def?sr=b&sp=rw&sig=doNotExposeSignatureHereItIsNotSafeForYourAccount&sv=2018-03-28&se=2019-10-01T16%3A30%3A15Z&comp=block&blockid=MDAwMDAwMQ==](url)

Issue occured when trying to upload a file with blank space in name.

**Python 2**
`
from urllib import quote
`
`
encoded_file_path = quote(file_path)
`

Steps taken
1. the filename was url encoded. tried both (device-1/abc%20def) and (device-1%2Fabc%20def) 
2. the signed url was properly formed

but on posting data it throw the below error 

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:0e378e5d-301e-017d-4d43-784z08000100
Time:2019-10-01T10:30:26.3687928Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was rw

2019-10-01T16:30:15Z
/blob/tstagingv2ogs/project-1/device-1/abc def
2018-03-28
</AuthenticationErrorDetail></Error>

**Comment by maggiepint** [comment]
Hi,
It seems like you are trying to upload a file, which leads me to believe you are attempting to access Azure storage, but to be honest I"m not sure. Assigning storage for now but can you clarify?

**Comment by HassankSalim** [comment]
Yes , I am trying to use azure blob storage, 
the code works fine in case of blob names without any special characters

**Comment by amishra-dev** [comment]
Thanks @maggiepint. Thanks @HassankSalim, we will look at this and update you tomorrow PST.

**Comment by xiafu-msft** [comment]
Hi @HassankSalim
Thanks a lot for reaching out.
I believe the problem isn't caused by white space in the blob name. You could verify that by purely create a new blob with that name ^_^

Based on the url you provided, I assumed you were trying to stage a block to a blob using the sas token for the blob. Based on that assumption I wrote the script which does the same thing and it succeeded.
Here is the script I wrote:

        # bsc is an instance of BlobServiceClient
        blob_client = self.bsc.get_blob_client(self.container_name, 'device-1/abc%20def')

        # get sas token for the blob 'device-1/abc%20def'
        token = blob_client.generate_shared_access_signature(
            permission=BlobPermissions.READ + BlobPermissions.WRITE,
            expiry=datetime.utcnow() + timedelta(hours=1)
        )

        # Act
        blob_client1 = BlobClient(blob_client.url, credential=token)
        blob_client1.stage_block('1', b'AAA')
        blob_client1.stage_block('2', b'BBB')
        blob_client1.stage_block('3', b'CCC')
`

**Comment by HassankSalim** [comment]
@xiafu-msft 
i used the BlobSharedAccessSignature to generate the token could that be the problem. And we are making Rest call to Put Block and Put Block List to upload the file. 

I'm OOO for few days could this issue be kept open till next week. Meanwhile if i get time i will checkout above script to generate token and see if it works for us.

**Comment by xiafu-msft** [comment]
@HassankSalim 
Sounds good you can keep the issue open. Also I edited the url you pasted, it's not safe to put the signature there since the repo is public and could be seen by everyone.

**Comment by rakshith91** [comment]
Hi @HassankSalim ,
Can you confirm if this issue is resolved for you? Thanks a lot.

**Comment by HassankSalim** [comment]
Sorry, for the late reply. the issue was resolved. It was a mistake from my part.
Thanks for the help.
