### ISSUE TITLE
Blob storage SDK accesses `internal_response` member of HTTP response

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#7532]
https://github.com/Azure/azure-sdk-for-python/blob/09417f610219d5008d044ed3116872f8cb6d70f8/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies_async.py#L57

I'm not at all clear why this is necessary, but the transport I'm working on does not have a settable "body" member here, so this is causing everything to fail.

Perhaps the common response type needs a new method added? Or there's some issue with one of the existing pipelines not implementing its `load_body` correctly?

**Comment by mayurid** [comment]
@rakshith91 : Can you take a look

**Comment by rakshith91** [comment]
REsolved
