### ISSUE TITLE
Private IP allocation for multiple VMs

### ISSUE THREAD

**Issue by tmarballi** [Azure/azure-sdk-for-python#756]
Hi,
I am using the sdk to create multiple vms under the same resource group. The code for the same is as below. Despite of choosing the method of private ip allocation as dynamic,  it somehow seems to assign the same IP  for example :'10.1.0.4' to all the VMs. That does not work for my application as it uses private IPs to communicate internally amongst the multiple nodes. Also giving the address space and subnet address prefix is mandatory so I have to pass a range in and it somehow always chooses the same one from that range. Am I missing something or do I need to specify some parameter which chooses different IPs? Or do I need to configure the network interface any differently?

```python
print ("Creating/Updating the Virtual Network")
address_space = AddressSpace(address_prefixes=['10.1.0.0/16'])
subnet1 = Subnet(name=subnet_name, address_prefix='10.1.0.0/24')
result = network_client.virtual_networks.create_or_update(group_name, network_name, VirtualNetwork(location=region, address_space=address_space, subnets=[subnet1]))
self.sleep_until_update_operation_done(result, network_name, verbose)
subnet = network_client.subnets.get(group_name, network_name, subnet_name)

print ("Creating/Updating the Public IP Address")
ip_address = PublicIPAddress(location=region, public_ip_allocation_method=IPAllocationMethod.dynamic, idle_timeout_in_minutes=4)
result = network_client.public_ip_addresses.create_or_update(group_name,ip_name, ip_address)
self.sleep_until_update_operation_done(result, ip_name, verbose)
public_ip_address = network_client.public_ip_addresses.get(group_name, ip_name)

print ("Creating/Updating the Network Interface")
network_interface_ip_conf = NetworkInterfaceIPConfiguration(name='default', private_ip_allocation_method=IPAllocationMethod.dynamic, subnet=subnet, public_ip_address=PublicIPAddress(id=(public_ip_address.id)))
result = network_client.network_interfaces.create_or_update(group_name, interface_name, NetworkInterface(location=region,ip_configurations=[network_interface_ip_conf]))
self.sleep_until_update_operation_done(result, interface_name, verbose)
```

**Comment by lmazuel** [comment]
Hi @tmarballi 

Could you confirm which version of the SDK you use?
Thanks!

**Comment by tmarballi** [comment]
@lmazuel The latest one and that is 2.0.0rc5 I believe!

**Comment by lmazuel** [comment]
I just retested and it works just fine, if you provide the same subnet id for all the NIC you want in the same subnet.
Could you share the code that creates two VMs? Just to be sure you use correctly the same subnet id.

**Comment by tmarballi** [comment]
So I should be using the same network interface across VMs? I think I tried that before and I got an error while creating a VM because it said that this subnet / virtual network is already in use with another resource sort of an error. The code I attached above is a method called create_network_interface and I create a new network interface for each VM. Do you have any example of how the same subnet can be used. Because I remember trying that once but I got an error like I just mentioned.

for _ in range(count):
      vm_network_name = Haikunator().haikunate()
      self.create_network_interface(network_client, parameters,
        vm_network_name, vm_network_name, vm_network_name, vm_network_name)
      network_interface = network_client.network_interfaces.get(
        resource_group, vm_network_name)
      self.create_virtual_machine(credentials, network_client,
        network_interface.id, parameters, vm_network_name)

**Comment by lmazuel** [comment]
Not the same network interface, the same subnet id.

Create your Virtual Network and your Subnet, and then use the same "subnet" object for each Network Interface you create.

**Comment by tmarballi** [comment]
Gotcha! I will try that and let you know! Thanks for your help!

**Comment by tmarballi** [comment]
Using the same Subnet object worked perfectly! Thanks a ton! Closing this issue!
