### ISSUE TITLE
Update intersphinx list for track 2 dependencies

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#7563]
Need to add the base url where we would download teh objects.inv.

Example from @lmazuel 
Add aiohttp `https://aiohttp.readthedocs.io/en/stable/objects.inv ` so that we can have a nice formatted link to the ref docs for that one.

This is not **all** generated packages, just dependencies that we require.

**Comment by kurtzeborn** [comment]
@scbedd, I think this is docs related, but I'm not 100% sure based on the title and description.  I put it in the github.io vNext epic.  If I got this wrong, let's find a better place for it.
