### ISSUE TITLE
ValueError: could not convert string to float: 'max-age=31536000'

### ISSUE THREAD

**Issue by ianleaman** [Azure/azure-sdk-for-python#763]
When running the example code from docs I get an error in the azure/servicebus/_serialization.py file.  The package I am using is: azure.servicebus.

It is attempting to turn the string value "max-age=#" into a float in a check which triggers the error. I got the error in the first minute of following the Azure tutorial for the python SDK. 

The line that triggers the error is:
`
msg = bus_service.receive_queue_message(queue_name)
`

**Comment by lmazuel** [comment]
Hi @ianleaman,

This is fixed in ServiceBus release 0.20.2 (current is 0.20.3). Just update your package with `pip install -U azure-servicebus`
Release note:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/HISTORY.rst

Thanks,

**Comment by ianleaman** [comment]
Thanks for the quick response i'll update the package.
