### ISSUE TITLE
Broken links in azure-appconfiguration readme

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#7664]
The file at https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/appconfiguration/azure-appconfiguration/README.md contains a number of poorly formatted or unspecified links.

There are also a couple of relative links that do not render correctly when published to https://pypi.org/project/azure-appconfiguration/ (see the `AzureAppConfigurationClient` link, for example).

**Comment by xiangyan99** [comment]
Fixed in preview 5
