### ISSUE TITLE
404 Client Error in _information_protection_policies_operations.py

### ISSUE THREAD

**Issue by x4v13r64** [Azure/azure-sdk-for-python#7687]
I'm getting the following exception when calling https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_information_protection_policies_operations.py#L170:

`404 Client Error: Not Found for url: https://management.azure.com/subscriptions/<subscription ID>/providers/Microsoft.Security/informationProtectionPolicies?api-version=2017-08-01-preview`

The issue isn't with the subscription's ID as if I provide an invalid one I get a `SubscriptionNotFound` error instead.

Additionally, shouldn't https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_information_protection_policies_operations.py#L193 be:
```python
'scope': self._serialize.url("scope", scope, 'str', skip_quote=True)
```
?

**Comment by kaerm** [comment]
@j4v thanks for reporting this - tagging the right team to take a look at this

**Comment by j4v** [comment]
@kaerm is there a timeline for this issue?

**Comment by lilyjma** [comment]
@kaerm, do we have any update on this?

**Comment by kaerm** [comment]
Maybe @nickzhums can follow up on this
