### ISSUE TITLE
No module named 'azure.core.tracing.context'

### ISSUE THREAD

**Issue by Fukkei** [Azure/azure-sdk-for-python#7691]
Hey guys,

azure-storage-blob 12.0.0b3  is incompatible with azure-core 1.0.0b4

clean install:
```
$ pip install azure-storage-blob --pre
Collecting azure-storage-blob
  Using cached https://files.pythonhosted.org/packages/9e/ff/6b4765c781b81f72995442b0c431038ff278aee3e186cbc4497a8f6a639b/azure_storage_blob-12.0.0b3-py2.py3-none-any.whl
Collecting azure-core<2.0.0,>=1.0.0b3 (from azure-storage-blob)
  Using cached https://files.pythonhosted.org/packages/a7/ce/601b03eb5367d95ef7ed6783982a7374d08b86559fda344946b2718cbdd8/azure_core-1.0.0b4-py2.py3-none-any.whl
...
...
Installing collected packages: azure-core, azure-storage-blob
Successfully installed azure-core-1.0.0b4 azure-storage-blob-12.0.0b3
```

After that if you try to use the package you'll get the following exception:
```
...
...
    from azure.storage.blob import BlobClient, BlobServiceClient
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\storage\blob\__init__.py", line 11, in <module>
    from .blob_client import BlobClient
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\storage\blob\blob_client.py", line 25, in <module>
    from ._shared.uploads import IterStreamer
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\storage\blob\_shared\uploads.py", line 16, in <module>
    from azure.core.tracing.context import tracing_context
ModuleNotFoundError: No module named 'azure.core.tracing.context'
```

Temp fix: forcibly install azure-core 1.0.0b3 which is ok. (`pip install azure-core==1.0.0b3`)

**Comment by kaerm** [comment]
@Fukkei thanks for letting us know! Someone from our team is going to take a look at this cc: @rakshith91

**Comment by mayurid** [comment]
Hi @Fukkei thanks for reporting this issue. We do indeed have breaking changes in the new azure core and as you have identified one will need to revert to the older version of azure core for it.
The latest release of storage is now out which works well with the latest azure core and has more improvements. Please do try it out and let us know

**Comment by Fukkei** [comment]
Wow, that was fast.

@mayurid The most recent version `azure-storage-blob-12.0.0b4` works flawlessly, thanks a lot!
