### ISSUE TITLE
Update SDist Artifact naming conventions `_` instead of `-`

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#7698]
By default, `sdist` generation in tooling produces `package-name.zip` formatted naming.
`whl` produces artifacts with `_` as the separator, followed by `-` to separate the properties in the artifact name. 

If we update the `sdist` to also have `_` as the separator, we won't need to special case the artifact copy in the unified pipelines.

**Comment by praveenkuttappan** [comment]
As per python standard naming convention, sdist has "-". Artifacts copy operation takes care of  this different naming by whole directory. Marking issue as closed.
