### ISSUE TITLE
Scaleset create_or_update doesn't include protected settings object

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-sdk-for-python#770]
ext = VirtualMachineScaleSetExtension(...protected_settings=protected_settings...)
vmss.virtual_machine_profile.extension_profile.extensions.append(ext)
client.virtual_machine_scale_sets.create_or_update(resource_group_name, vmss_name, vmss)

Expected: vmss extension has its protected settings saved
Actual: protected settings are empty

Note: the extension is successfully added, but the protected settings are missing

**Comment by lmazuel** [comment]
Hi,

Not sure I get it, where are the protected settings missing? in the create_or_update return object?

**Comment by BurtBiel** [comment]
It was missing from the return object, which I think is actually by design.  Our issue looks to be further upstream, so I will look to the service teams to resolve this issue instead.  Sorry for the false alarm.

**Comment by lmazuel** [comment]
No problem :)
