### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'signed_session'

### ISSUE THREAD

**Issue by goblain** [Azure/azure-sdk-for-python#7720]
I want to use python script based on my `az login` authentication to get some network info

```
#!/usr/bin/env python3

from azure.mgmt.network import NetworkManagementClient
from azure.common.credentials import get_azure_cli_credentials

subscription = "mysubname"
credentials = get_azure_cli_credentials()
network = NetworkManagementClient(credentials, subscription)

lbs = network.load_balancers.list_all()

for lb in lbs:
  pass
```
but all I get is 
```
Traceback (most recent call last):
  File "./x.py", line 12, in <module>
    for lb in lbs:
  File "/home/goblin/.local/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/home/goblin/.local/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/goblin/.local/lib/python3.6/site-packages/azure/mgmt/network/v2018_12_01/operations/load_balancers_operations.py", line 436, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "/home/goblin/.local/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/home/goblin/.local/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/goblin/.local/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/goblin/.local/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
```

**Comment by kaerm** [comment]
@goblain thanks for reporting this! I'm tagging it for the right team to take a look at this

**Comment by goblain** [comment]
it looks to me like it's more about `azure.common.credentials` then `azure.mgmt.network import`

looks like the object returned by `get_azure_cli_credentials()` does not have method `signed_session`

**Comment by kaerm** [comment]
gotcha thanks! I missed that //cc: @jamesc

**Comment by yonzhan** [comment]
@zikalino @fengzhou-msft  please take a look.

**Comment by fengzhou-msft** [comment]
@goblain subscription should be id, not name. And `get_azure_cli_credentials()` wil return it for you. You can use it as:
```python
credentials, subscription  = get_azure_cli_credentials()
network = NetworkManagementClient(credentials, subscription)

```

**Comment by goblain** [comment]
if that was the case, then `get_azure_cli_credentials()` should throw an exception, furthermore, if it passes successfully and returns network mgmt client with the client returned without failure, it should have 'signed_session'. Finally, to validate my point I changed my example from the beginning of this issue to `subscription = <mysbid>` but no luck, stil fails in exactly the same way.

**Comment by fengzhou-msft** [comment]
`get_azure_cli_credentials()` won't be affected, `network = NetworkManagementClient(credentials, subscription)` is where it went wrong and throws the error when it actually send request to get info.

**Comment by fengzhou-msft** [comment]
Please check whether your `mysubid` mactches the one returned by `get_azure_cli_credentials()`

**Comment by goblain** [comment]
ok, thanks for pointing me in the right direction
