### ISSUE TITLE
Make configuration a kwargs for azure-core

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#7721]
We deprecated already "Configuration" in track2 packages, but it's still visible in azure-core in `PipelineClient` and `AsyncPipelineClient`. This issue is about making them a little more internal, until one day we kill them for good.

- For `PipelineClient` make "config" kwargs only (disapear from signature). Change code so if no config is provided, a default one is created with the default policies created. Adapt any track2 libs that are not using kwargs syntax
- For `AsyncPipelineClient` make it a kwargs-only syntax (`*` syntax). Same logic apply to create a default one.

**Comment by xiangyan99** [comment]
Fixed
