### ISSUE TITLE
Apply the de-duplication of module in azure-coreb4 for real.

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#7722]
Mostly this issue is about finishing https://github.com/Azure/azure-sdk-for-python/pull/7633

Also, this includes doing a PR to autorest branch azure-core for the new path for exceptions, and regenerate the necessary projects with that new version.

PR #7633 should *not* be merged until the Autorest PR is merged and regeneration have been done.

**Comment by lmazuel** [comment]
@xiangyan99 need the regeneration of all track2 with https://github.com/Azure/autorest.python/pull/126 before closing this issue

**Comment by lmazuel** [comment]
See also https://github.com/Azure/azure-sdk-for-python/pull/7837

**Comment by xiangyan99** [comment]
Fixed
