### ISSUE TITLE
[Documentation] Missing documentation for CertificateAttributes

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#7727]
See `attributes` parameter for: 

https://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.certificates.html?highlight=keyvault#azure.keyvault.certificates.models.Certificate

**Comment by chlowell** [comment]
That documentation's out of date, the [docstring in master](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/models.py#L263) is different (and looks correct to me).

@scbedd when is the doc site updated?

**Comment by scbedd** [comment]
[Now](https://dev.azure.com/azure-sdk/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=5682)

**Comment by chlowell** [comment]
Thanks, content is up to date now but the reference in the docstring is still broken, #7733 fixes it :blush:

**Comment by chlowell** [comment]
Fixed in #7428
