### ISSUE TITLE
[Feature Request] Add azure.common.credentials.UserPassCredentials() to Accept AD OAuth with MFA

### ISSUE THREAD

**Issue by taylorsmcclure** [Azure/azure-sdk-for-python#774]
According to the [docs](http://azure-sdk-for-python.readthedocs.io/en/v2.0.0rc5/resourcemanagementauthentication.html#using-ad-user-password) I cannot login AD users with MFAs enabled. Wanting to keep up with security best practices I don't have any accounts without MFA to use with my application.

For the purposes of my use case we are not using pre-shared keys with the application, this should work immediately with any given subscription by inheriting the AD user's permissions. My application is to be given out to anyone with an Azure AD login with no interaction on their end's to authorize this application.

I am definitely open to alternatives to satisfy authorization with my use-case, but for the time being I think setting up a catch for a MFA token would be ideal.

**Comment by lmazuel** [comment]
Hi @taylorsmcclure 
+ @brettcannon 

We are currently looking to replace authentication with the official Azure lib [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-python).
I think what you ask will be covered by this library. If it doesn't not, could you open an issue on the ADAL tracker to explain your situation?

**Comment by taylorsmcclure** [comment]
Hey @lmazuel 

Thanks for the response! Just skimming over ADAL it looks like I could get this to work well with my use case. As far as implementation goes, if I don't want to wait would modifying the Azure Python SDK require a sizable code change? Is this something that could be easily completed in my own fork?

Thanks again!

**Comment by lmazuel** [comment]
Once ADAL gave ou a token, you should be able to create a credentials instance this way:
```python
    from msrest.authentication import BasicTokenAuthentication
    credentials = BasicTokenAuthentication(
        token = {
            'access_token':adal_auth_token
        }
    )
```

**Comment by lmazuel** [comment]
Hi @taylorsmcclure 

I included yesterday a wrapper to ADAL for simple use with the SDK. See documentation on RTD:
http://azure-sdk-for-python.readthedocs.io/en/latest/quickstart_authentication.html#using-adal

This allows you to use any ADAL tutorials and to get a `Credential` instance you can use directly inside any package. This requires only to update `msrestazure` to 0.4.5.

**Comment by lmazuel** [comment]
I close this issue, since I truly think we solved the issue. Please feel free to comment agasin on it if necessary or open a new issue.
Thanks,
