### ISSUE TITLE
Storage async poller should need only one await.

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#7744]
Current code will need to "await await" to get the poller result.
This is not the expected syntax, see autorest:
https://github.com/Azure/autorest.python/blob/a251e361218598b55b0621db2275aafcb7158a5c/test/azure/Expected/AcceptanceTests/Lro/lro/aio/operations_async/_lr_os_operations_async.py#L128

Two occurences in Storage;
https://github.com/Azure/azure-sdk-for-python/blob/e2266ebfed086fec1ac50fdd5aaef9cbc522efe8/sdk/storage/azure-storage-file/azure/storage/file/aio/directory_client_async.py#L304

https://github.com/Azure/azure-sdk-for-python/blob/e2266ebfed086fec1ac50fdd5aaef9cbc522efe8/sdk/storage/azure-storage-file/azure/storage/file/aio/file_client_async.py#L912

**Comment by kristapratico** [comment]
merged
