### ISSUE TITLE
azure-mgmt-web not present on docs.ms.com

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#7755]
[build automation ](https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=89876)

You can repro locally leveraging the following commands:

1. `pip install tox tox-monorepo`
2. `cd sdk/appservice/azure-mgmt-web`
3. `tox -e sphinx -c ../../../eng/tox/tox.ini`

This is the error from the official documentation build
![image](https://user-images.githubusercontent.com/45376673/66530214-afc1ac00-eabb-11e9-9ec6-5580a4528fac.png)

Locally, this is just a warning, but it does repro!

```
WARNING: autodoc: failed to import module 'operations' from module 'azure.mgmt.web'; the following exception was raised:
No module named 'azure.mgmt.web.operations'
```

This package is blocking the documentation build from publishing new versions right now.

**Comment by leyshon** [comment]
Does this issue in anyway explain why the documentation on the live site is missing? I reported the issue here https://github.com/MicrosoftDocs/feedback/issues/2100 but it doesn't seem to be of any concern that it's missing. If you visit https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/index?view=azure-python you'll receive a 404. The same is true if you visit https://docs.microsoft.com/en-us/python/api/?view=azure-python and find the azure-mgmt-web link and click it.

**Comment by scbedd** [comment]
@leyshon Thank you very much for the follow-up here. I'm investigating to see what action items the assignee took. 

In the meantime, you can find this documentation [here ](https://azure.github.io/azure-sdk-for-python/ref/Web-Apps.html) if you are looking for it now.

**Comment by scbedd** [comment]
I have located the root cause of the missing documentation, and have submitted the request to get it fixed.

**Comment by leyshon** [comment]
Thanks for looking into it. Just as a note though the link you suggested as an alternative doesn't have all of the documentation, specifically the submodules are just blank pages e.g. https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-web/0.43.1/azure.mgmt.web.operations.html

**Comment by scbedd** [comment]
Thank you for reporting all of these. It took way too long, but both 
[docs.ms.com](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/index?view=azure-python) and [github.io](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-web/0.43.1/index.html) are reflecting what they should be.
