### ISSUE TITLE
Block CI on no matching change log

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#7776]
- need an option to enable on specific packages
- block CI when there is no change log entry for the version being built

**Comment by scbedd** [comment]
Additional Context:

This will prevent instances of "impoperly" formatted changelogs biting people _at release time_.

**Comment by scbedd** [comment]
Note: make certain that our users are notified of new breaking `Analyze` step change.

**Comment by lmazuel** [comment]
See https://github.com/Azure/azure-sdk-for-python/pull/8213
