### ISSUE TITLE
Changes from UX studies and API reviews

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#7796]
@heaths commented on [Thu Oct 10 2019](https://github.com/Azure/azure-sdk-for-net/issues/8035)

We have a separate table of proposed/required changes we're keeping cross-language internally.

**Comment by chlowell** [comment]
- [ ] certificates
  - [ ] Certificate -> KeyVaultCertificate (also Properties)
  - [ ] rename generic classes e.g. Action->LifeTimeActionType, Contact->CertificateContact, Error->CertificateError, Issuer->CertificateIssuer
  - [ ] Certificate.CER -> Certificate.Cer
  - [ ] Add CertificatePolicy.Default member
- [ ] keys
  - [ ] Remove iv, authenticationData, and authenticationTags from parameters and properties
  - [ ] rename generic classes e.g. Key -> KeyVaultKey (Properties as well)
  - [ ] Hsm parameter (now hardwareProtected) should default to false and be removed from ctor
  - [ ] Key.KeyMaterial -> KeyVaultKey.Key
  - [ ] Lift Key.KeyMaterial.KeyType to Key.KeyType
  - [ ] Lift Key.KeyMaterial.KeyOps to Key.KeyOperation
- [ ] secrets
  - [ ] rename generic classes e.g. Secret -> KeyVaultSecret (also Properties)

**Comment by heaths** [comment]
I don't see the "created_on", etc. changes. Did you list everything from the OneNote? There were a few changes discussed in Teams to it as well.

**Comment by chlowell** [comment]
They aren't listed here but we have renamed expires, created, updated to *_on.

**Comment by heaths** [comment]
@chlowell, can you review the OneNote and make sure everything was captured. There were a few updates after our meeting the other day, which is why I wanted to keep it centralized.
