### ISSUE TITLE
Rename sync methods that return a poller with a `begin_` prefix.

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#7833]
Anything that returns a poller should have a method name that starts with `begin_`. This allows flexibility for when services move from sync to async (or async to sync) for a given method. It is also a consistency issue.

We have a small number of methods that return a poller now. And it would be a breaking change to do it later.

@mayurid, FYI.

**Comment by annatisch** [comment]
Resolved in #7834
