### ISSUE TITLE
Detect breaking change when default value changes cross API version

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-sdk-for-python#7857]
Hope python SDK can treat the following scenario as breaking change: 
Default value changes cross different API version.

For example, for supportsHttpsTrafficOnly prpoerty, it changed to true in the new API version. https://github.com/Azure/azure-rest-api-specs/blob/8188f2ed896ed7f345c5a324f3c62aaca926a35b/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/storage.json#L1378

It is a breaking change for us who will use this property during implementation, but we don't know about it until error occurs.

**Comment by tasherif-msft** [comment]
@Juliehzl We will keep this in mind moving forward
