### ISSUE TITLE
Logging instructions do not work

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-python#7890]
For the key vault UX study I wanted to try and setup network trace logging with the keyvault.
I used an instructions in preview.4 Readme.md to setup logging.
I noticed 2 issues:
1)client = KeyClient(vault_endpoint=url, credential=credential, logging_enable=True) - constructor does not accept logging as an argument
2) when passine logging_enable to a method and follow rest of the setup instruction, logging trace does not appear on the console

**Comment by kaerm** [comment]
Thanks @elraikhm! //cc: @chlowell @iscai-msft

**Comment by iscai-msft** [comment]
Thanks so much @elraikhm and @kaerm for bringing this to our attention, I currently have a PR out for (#8162)
