### ISSUE TITLE
Storage sample misses a few steps

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-sdk-for-python#7910]
- [x] Doesn't tell you how to create a resource group. Assumes you have one. 
- [x] Doesn't tell you how to create a container but expects you to have one for upload and download.
- [x] Doesn't show you how to set the right permissions to be able to upload a blob to a container.
- [x] Needs to do a better job highlighting using default credentials after logging into the CLI. Note, that we need to figure out the right thing to do on Mac and Linux if default credentials aren't supported there.

**Comment by kaerm** [comment]
Thanks @Petermarcu //cc: @rakshith91

**Comment by Petermarcu** [comment]
I made a PR to address the first item in #7972
