### ISSUE TITLE
recommended_vm_size is not populated

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-python#793]
I'm using `azurectl` to publish an image, but I'm having issues with the `recommended_vm_size` field.

It never seems to be populated. You can see here:
https://github.com/SUSE/azurectl/blob/d903d0fe24d03332a4fda178dcaf117105932687/azurectl/instance/image.py#L295

All they're doing is grabbing the os_image object returned by the python-sdk and passing through the values.

This makes me think that there's a bug in the deserialization logic for that field. Is that possible? I'm willing to hotfix my local environment if someone spots it quickly. Thanks.

**Comment by colemickens** [comment]
For example, in PowerShell:

`Get-AzureVMImage -ImageName "rhel-68-20160914"` returns an object with a field `RecommendedVMSize : Standard_D2,....`

But if I make this call through `azurectl`, the field is empty because the python SDK is returning the field as empty.

**Comment by colemickens** [comment]
The only test I see for this is:

`        self.assertGreaterEqual(len(image.recommended_vm_size), 0)`

which will pass even if the `recommended_vm_size` field is empty...

**Comment by colemickens** [comment]
If I put a `pprint.pprint(vars(response))` here: https://github.com/Azure/azure-sdk-for-python/blob/c0e7da5389a96b2ce17ea7813b8504381c377c80/azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementclient.py#L366
 and put pretty print the results of the `parse_response`... I can clearly see the XML element is populated, but the field on the object returned is not.

**Comment by lmazuel** [comment]
Thanks for the feedback! If you have the oppourtunity to do a PR, would be awesome! Otherwise, I will check that tomorrow.
Thanks again!

**Comment by colemickens** [comment]
I spent a while on this yesterday afternoon and couldn't figure out where the bug in the deserialization was. I'm hoping someone more familiar with python and the python SDK will be able to spot it :).

I'm already clobbering my python-sdk install with a fork so I can adopt any fixes and test them quickly.

**Comment by lmazuel** [comment]
Hi @colemickens 
I'll see what I can do, I'll let you know :)
