### ISSUE TITLE
`show_in_gui` updates do not take effect

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-python#794]
Similar to #793 but different...

I have now put a debug line on the `_perform_put` in the service management client.

I can see that the XML is what I'd expect:

```shell
<OSImage xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/windowsazure"><Label>Red Hat Enterprise Linux 6.8</Label><Eula>http://www.redhat.com/licenses/cloud_CSSA/Red_Hat_Cloud_Software_Subscription_Agreement_for_Microsoft_Azure.pdf</Eula><Description>Red Hat Enterprise Linux is the world\'s leading enterprise Linux platform built to meet the needs of today\'s modern enterprise. Red Hat Enterprise Linux is the preferred choice for enterprise Linux workloads on Microsoft Azure. Red Hat Enterprise Linux is an open, reliable, and secure platform designed for customers who want deployment flexibility for their business-critical workloads - from the data center to the Azure cloud - backed by tightly integrated, enterprise-grade support from Red Hat and Microsoft</Description><ImageFamily>Red Hat Enterprise Linux 6.8</ImageFamily><PublishedDate>2016-09-14T07:00:00Z</PublishedDate><ShowInGui>false</ShowInGui><IconUri></IconUri><PrivacyUri>http://www.redhat.com/licenses/cloud_CSSA/Red_Hat_Privacy_Statement_for_Microsoft_Azure.pdf</PrivacyUri><RecommendedVMSize></RecommendedVMSize><SmallIconUri></SmallIconUri><Language></Language></OSImage>
```

But the ShowInGui value for the image isn't actually updated. Is it possible there's an ordering problem here for the values inside `<OSImage>`?

**Comment by colemickens** [comment]
Yikes. It is the xml element ordering... wow.

Please transpose the lines 1203/1204 of [_serialization.py](https://github.com/Azure/azure-sdk-for-python/blob/32a8f678fe0899200f88aeb89195d02f5ea71697/azure-servicemanagement-legacy/azure/servicemanagement/_serialization.py#L1203) to resolve this issue.

**Comment by lmazuel** [comment]
Hi @colemickens 
Thanks for the PR! I agree that this is not really beautiful... This is one of the reason the [ASM RestAPI of Azure](https://msdn.microsoft.com/en-us/library/azure/jj157198.aspx) is now replaced by ARM...

I merge your PR and keep this issue opened until I published the package on PyPI

**Comment by colemickens** [comment]
Yes, it's replaced by ARM which completely lacks image publishing APIs entirely...

**Comment by colemickens** [comment]
Anyway, thanks for merging the fix. Also, the issue auto-closed when you merged my PR because of the commit text.

**Comment by lmazuel** [comment]
I made more tests on the method, will add another PR with more small fixes before publishing.
