### ISSUE TITLE
ResourceManagementClient resources list operation doesn't include resource tags

### ISSUE THREAD

**Issue by antgonmir** [Azure/azure-sdk-for-python#7956]
I want to list resources in Azure filtering by a specific tag and then perform operations based on other tags the resource might have.
Listing resources by tag works correctly. However, the resources returned by the list operation always have the following:

```
tags = {NoneType} None
```

Even though the resources have tags. 

Code snippet:
```
def get_resources_by_tag(tag_name, tag_value):
    """
    Retrieves a list of resources in Azure that contain a specific tag with a certain value.
    :param tag_name: The name of the tag to filter resources
    :param tag_value: The value of the tag to filter resources
    :return: A list of resources matching the tag criteria
    """
    rm_client = get_client_from_cli_profile(ResourceManagementClient)
    logger.info(f"Collecting Azure resources for {tag_name} = {tag_value}")
    resources = rm_client.resources.list(filter=f"tagName eq '{tag_name}' and tagValue eq '{tag_value}'")

    return list(resources)
```

I am using:
```
Python 3.7.3
```
And I have tried with ``` azure-mgmt-resource 2.2.0 ``` up to ```  azure-mgmt-resource 5.0.0 ```

**Comment by ifeoluwaokunoren** [comment]
Hi @antgonmir,
Thanks for reporting this issue - Do you mind attaching a sample response of the list operation that you tried so @hamidtirmizi can take a look?
Thanks.

**Comment by hamidtirmizi** [comment]
Hi @antgonmir, this is currently the expected behavior. Listing resource using tag filters does not return tags at present.
This is one of the things we are working on, and targeting for enabling early next year.

**Comment by antgonmir** [comment]
Thanks @hamidtirmizi, 

I have verified that I can retrieve the resource tags by using the **list_by_resource_group** method, which provides a reasonable workaround.

I would suggest mentioning the limitation that listing resources using tag filters has in the documentation. 
Other than that, I guess this issue can be closed.

Thanks.

**Comment by ifeoluwaokunoren** [comment]
Thanks @antgonmir 
Documentation would be updated as suggested - https://github.com/Azure/azure-rest-api-specs/pull/7721
