### ISSUE TITLE
[Python Track2] Investigate Client Side Encryption (Looks Like a Bug)

### ISSUE THREAD

**Issue by xiafu-msft** [Azure/azure-sdk-for-python#7957]
When we enable client side encryption, if the blob can not be fully downloaded with one http call, the decrypted content is not the same as the uploaded content

https://dev.azure.com/msazure/One/_workitems/edit/5496432

**Comment by annatisch** [comment]
Thanks @xiafu-msft - is this now resolved with PR#7965?

**Comment by xiafu-msft** [comment]
Hi Anna @annatisch!
Thanks for reviewing that pr! Yes, this issued is addressed by PR #7965

**Comment by rakshith91** [comment]
REsolved.
