### ISSUE TITLE
OAuth2 Authorization code was already redeemed during InteractiveBrowserCredential

### ISSUE THREAD

**Issue by cfe84** [Azure/azure-sdk-for-python#7960]
I've been trying to make `InteractiveBrowserCredential` work for a customer, I'm thinking there might be a bug in there but I'm stuck at debugging.

The premise is the following:
- Provisioned an app-registration, using public client, added API permission user_impersonation on storage account.
- Provisioned a storage account to which user has access
- Using the following requirements:

```txt
azure-identity
azure-storage-blob
azure-common
```

- Wrote the following code:

```python
import os
import uuid
import sys
from azure.storage.blob import BlockBlobService
from azure.identity import InteractiveBrowserCredential, DeviceCodeCredential
from azure.storage.common import TokenCredential


def get_credentials():
    credentials = InteractiveBrowserCredential(
        client_id='xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx',
        authority='login.microsoftonline.com/xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/',
    )
    token = credentials.get_token(
        'https://*.dfs.core.windows.net/user_impersonation')
    cred = TokenCredential(token.access_token)
    return cred

def run_sample():
    try:
        file_name = 'file.txt'
        path = 'file.txt'
        creds = get_credentials()
        container = 'containername1'
        print('Calling blob service')
        block_blob_service = BlockBlobService(
            account_name='storageaccountname1',
            token_credential=creds)
        file = open(path,  'w')
        file.write("Hello, World!")
        file.close()
        block_blob_service.create_blob_from_path(
            container, file_name, path)
        generator = block_blob_service.list_blobs(container_name)
        for blob in generator:
            print("\t Blob name: " + blob.name)

    except Exception as e:
        print(e)


# Main method.
if __name__ == '__main__':
    run_sample()
```

When executing, browser is opened, user signs in, then code breaks on `token = credentials.get_token(
        'https://*.dfs.core.windows.net/user_impersonation')` with error:

```log
Authentication failed: AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.
Trace ID: b7494bb1-ed5d-44e7-9325-0b0272707d00
Correlation ID: 9242cc65-fd9d-4038-8cbc-df96485eb58b
Timestamp: 2019-10-17 00:49:27Z
```

Digging down `get_token(self, *scopes, **kwargs)` in `browser.py`, a code is correctly returned redirection from authentication. I've put a break-point there and tried to call the `token` endpoint from Fiddler, got an access_token successfully:

```json
{"token_type":"Bearer","scope":"user_impersonation","expires_in":"3599","ext_expires_in":"3599","expires_on":"1571275300","not_before":"1571271400","resource":"https://*.dfs.core.windows.net","access_token":"eyJ0e[...]bnLZw","refresh_token":"AQA[...]A","id_token":"ey[...]Q"}
```

Digging down the code of the SDK, the issue seems to be in the `msal_transport_adapter.py`. The `def post` method of `MsalTransportAdapter` get called once, and triggers this:

```python
self._pipeline.run(
            request, stream=False, connection_timeout=timeout, connection_verify=verify, **kwargs
        )
```
How the pipeline is assembled is not super clear to be honest, what I understand is that this single call to `post` is calling twice method `_TransportRunner.send()` in `azure.core.pipeline/base.py`, which makes the collection of an access_token fail on the second call.

Did I miss something in the config? Or is that a bug?

**Comment by kaerm** [comment]
@cfe84 thanks for reporting this, someone will take a look at it //cc: @chlowell

**Comment by chlowell** [comment]
It looks like you're using an older version of `azure-storage-blob` library (2.x?) which predates `azure-identity`. The newest released version (12.0.0) accepts `azure-identity` credentials and its clients handle token authentication for you, so you can write code like this:
```py
from azure.identity import InteractiveBrowserCredential
from azure.storage.blob import BlobClient

credential = InteractiveBrowserCredential()
client = BlobClient.from_blob_url(blob_url, credential)
with open(__file__, 'r') as file:
    blob = client.upload_blob(file.read())
```

**Comment by cfe84** [comment]
Interesting, looks like this is it. I didn't specify any version in the requirements, I'm assuming it grabbed whatever was cached.

Any how, ⬆️ this worked - thanks!

**Comment by chlowell** [comment]
Ah, that explains it. If you don't specify a version, pip will surprise you with the latest: 🎁

Glad you got it sorted.
