### ISSUE TITLE
Deleting deployment in a resource group doesn't delete the resources in the deployment

### ISSUE THREAD

**Issue by lyan-git** [Azure/azure-sdk-for-python#797]
I opened this issue #585 regarding a while ago and we still feel strongly that resource_client.deployments.delete() should delete the resources under the deployment just as delete resource group does .  
We have a case where we have a vnet that contains a load balancer with multiple gateways attached to it. The load balancer and the gateway need to be within one resource group. So we have a resource group that contain both load balancer deployment and multiple gateway deployments.
Now if the user want to delete one gateway only, we try to delete deployment logic entity rather than delete the whole resource group which will delete both load balancer and all gateway deployments. T hen we are facing the fact that the resources under deployment are not deleted. Do we need to delete those resources one by one throughout deployment? If we can create a deployment in one template, why can't we delete the deployment template resources at one time just like resource group? I thought the delete deployment should bring in that function.

Thanks.
Li

**Comment by lmazuel** [comment]
Hi @lyan-git 

Unfortunately, I can't help you right now, this is not really a Python issue :(
I can cite here the same people as in #585 if you like, to still continue the discussion. And send your issue by email at the ARM team.
Thanks, sorry to be not really helpful....

**Comment by lyan-git** [comment]
Thanks Laurent! I couldn’t find a way to reopen that case, seems I didn’t get the response back, wonder if there is another category I can open the case.

Li

**Comment by lmazuel** [comment]
On Github, you can open the issue here: https://github.com/Azure/azure-rest-api-specs
It will be cross-language and not Python specific, and easier to get the right person to answer.

**Comment by lyan-git** [comment]
Will do, thanks! You can close this issue then.

Li

**Comment by lmazuel** [comment]
Ok, thank you for your support!
