### ISSUE TITLE
azure-mgmt-advisor returns invalid resource ID

### ISSUE THREAD

**Issue by wesley-smith** [Azure/azure-sdk-for-python#7978]
I received a resource ID from the [Advisor Recommendations - list](https://docs.microsoft.com/en-us/python/api/azure-mgmt-advisor/azure.mgmt.advisor.operations.recommendationsoperations?view=azure-python#list-filter-none--top-none--skip-token-none--custom-headers-none--raw-false----operation-config-) method which failed validation/parsing by the functions in [`msrest.tools`](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/tools.py).

Here is the resource ID which failed validation with identifying information removed. I did nothing but access the `id` [attribute](https://docs.microsoft.com/en-us/python/api/azure-mgmt-advisor/azure.mgmt.advisor.models.resourcerecommendationbase?view=azure-python#variables) of the returned recommendation object:

```
/subscriptions/<uuid>/resourceGroups/<rg>/providers/Microsoft.Compute//providers/Microsoft.Advisor/recommendations/<recommendation_id>
```

I don't think the `/providers/Microsoft.Compute/` segment should be present in this string. Normally these resources only have `/providers/Microsoft.Advisor/recommendations/` present.

Here are the relevant packages installed:
```
azure-common==1.1.16
azure-mgmt-advisor==2.0.1
msrestazure==0.6.1
```

**Comment by kaerm** [comment]
Hi @wesley-smith thank you for reporting this, someone from our team is going to take a look at this
