### ISSUE TITLE
Listing nics for a scale set throws an error

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-sdk-for-python#798]
NetworkInterfacesOperations.list_virtual_machine_scale_set_network_interfaces

This throws error:
No registered resource provider found for location 'westus' and API version '2016-06-01' for type 'virtualMachineScaleSets/networkInterfaces'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest'.

I'm using 2.0.0rc6

**Comment by lmazuel** [comment]
Thanks for the report, I will wait for https://github.com/Azure/azure-rest-api-specs/issues/570 fix to publish a new package. I'll close this issue at that time.

**Comment by lmazuel** [comment]
Still didn't fix at the Swagger level. Workaround from @tjprescott is to create a second network client using api_version `2016-03-30` and to use it only for this operation. `api_version` is a parameter at the client creation level.

**Comment by lmazuel** [comment]
Fixed
