### ISSUE TITLE
Small parameter name issue in code samples on creating BlobClient

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#7985]
I noticed to that to create an BlobClient using `from_connection_string()`, the parameter names should be `container_name` and `blob_name` but on the code sample, it's just `container` and `blob`. The error that's thrown when using the wrong parameter names specifies the correct parameter names though: 
TypeError: from_connection_string() missing 2 required positional arguments: 'container_name' and 'blob_name'

This is the page I'm referring to: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob

**Comment by lilyjma** [comment]
Note that this wasn't an issue when I tried the previous preview version of the library.

**Comment by kaerm** [comment]
Thanks @lilyjma! //cc: @rakshith91

**Comment by annatisch** [comment]
This is fixed in the readmes with #8127 :)
