### ISSUE TITLE
Credentials don't allow per-request configuration

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#7989]
Each credential has its own HTTP pipeline, separate from any service client's. All credentials accept kwargs to `get_token` but may not pass them through to these pipelines.

Also, azure-core's `BearerTokenCredentialPolicy` doesn't pass request context to `get_token`, so per-request configuration provided to a service client won't reach the credential's pipeline.

**Comment by xiangyan99** [comment]
@chlowell could you provide more information? :)

**Comment by chlowell** [comment]
Per-request pipeline kwargs passed to client methods don't apply to authentication requests because the client's pipeline doesn't pass them to the credential's pipeline. To give a concrete example, when someone calls `client.Foo(raw_request_hook=some_callback)`, the client will call `some_callback` for the service request but not for a token request, should the credential send one. I opened this issue because although `get_token(**kwargs)` in the auth policy solves the problem, I believe it requires some more thought. I was uncertain whether blindly passing along all kwargs is a good idea, and how big a problem this is, i.e. what customer scenarios, if any, are blocked by it.
