### ISSUE TITLE
Downloading blob as shown in sample code throws error

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#7992]
The download blob sample as is throws a type error because of `writelines()`: 

my_blob.writelines(blob_data.content_as_bytes())
TypeError: a bytes-like object is required, not 'int'

But if you change it to `write()` like the async download sample, it works fine.

**Comment by kaerm** [comment]
Thanks @lilyjma!  // cc: @rakshith91

**Comment by rakshith91** [comment]
fixed
