### ISSUE TITLE
Transport timeout should be normalized

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#8000]
Right now `connection_timeout` is passed directly to the transport implementation.

This means if I want to customize timeout if I know transport is `requests`:
```python
# Connect and read
socket_timeout = (11, 0.000000000001)
BlocServiceClient(connection_timeout=socket_timeout, **kwargs)
```

However, if I want to do the same thing with async, I have to do this:
```python
import aiohttp
socket_timeout = aiohttp.ClientTimeout(sock_connect=11, sock_read=0.000000000001)
BlocServiceClient(connection_timeout=socket_timeout, **kwargs)
```

We should have a common description of how to define timeout, and each transport should map it to how their implementation is handling it.

**Comment by lmazuel** [comment]
Last but not least, the exception is not the same, and does not carry the same text (guess it's the original one, didn't looked at the type though)

**Comment by lmazuel** [comment]
Note: once it's fixed, fix storage test test_retry_on_socket_timeout_async

**Comment by xiangyan99** [comment]
Need a design review.

**Comment by lmazuel** [comment]
Kwargs:
-	timeout (global one for everything in sec)
-	read_timeout (just for read, use “timeout” for connection, in sec)
-	connection_timeout (just for connection, use “timeout” for read, in sec)

send(foo, timeout=12) # 12s seconds on both connection and read
send(foo, read_timeout=12) # 12s seconds on read, default on connection
send(foo, connection_timeout=12) # 12s seconds on connection, default on read
send(foo, read_timeout=17, connection_timeout=12) # 12s seconds on connection, 17s on read
send(foo, timeout=45, read_timeout=17, connection_timeout=12) # 12s seconds on connection, 17s on read (ignore timeout).

**Comment by johanste** [comment]
`timeout` should be the total operation timeout.

**Comment by lmazuel** [comment]
Let's restart this spec from scratch:
- `connection_timeout` should be a single float in seconds for the connection timeout. Default 5min
- `read_timeout` should be a single float in seconds for the read timeout. Default 5min

Requests implementation:
https://requests.kennethreitz.org/en/master/user/advanced/#timeouts
Aiohttp implementation:
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientTimeout

**Comment by lmazuel** [comment]
The tuple behavior is actually used in storage as a constant, so suggestiong the following update:
- If `connection_timeout` is a tuple, log a deprecation warning and split it correctly into `connection_timeout` and `read_timeout`
- If both `connection_timeout` is a tuple and `read_timeout` is provided, raise ValueError for inconsistent parameters.

**Comment by xiangyan99** [comment]
Fixed
