### ISSUE TITLE
AuthorizationCodeCredential doesn't use client secret

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#8004]

**Comment by xiangyan99** [comment]
@chlowell could you provide more information? :)

**Comment by ortonomy** [comment]
+1

**Comment by dyn4mic** [comment]
@chlowell Whats the alternative to authenticate for Confidential applications with a link to a user?

**Comment by chlowell** [comment]
It depends on the details of your scenario. Does your app run on a server or on client machines, and does it need to access resources owned by users?

**Comment by dyn4mic** [comment]
yes the app runs on a server, and it needs access to resources owned(own onedrive) and bound to user(group share, user is part of the group)

**Comment by chlowell** [comment]
That sounds like a case for the on-behalf-of flow (documented [here](https://learn.microsoft.com/entra/identity-platform/v2-oauth2-on-behalf-of-flow)), which azure-identity supports with [OnBehalfOfCredential](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/latest/azure.identity.html#azure.identity.OnBehalfOfCredential).

**Comment by charantejmandali18** [comment]
Hi @chlowell i am also facing the same issue, but in my flow i am using AuthorizationCodeCredntial where the user logs in to the created application by giving consent, i get a auth_cde too the call back url, and i have to generate the access_token, i am able to generate the access token using msal , but not able to pass it to GraphServiceClient
