### ISSUE TITLE
[Queues] Using TextXMLEncodePolicy/TextXMLDecodePolicy by default is confusing

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk-for-python#8035]
The default policy for `QueueClient` is to use `TextXMLEncodePolicy` and `TextXMLDecodePolicy` when encoding and decoding text from the wire.  The rationale here is that the wire format for the storage APIs is XML, and the documentation mentions that the message content needs to be XML Encoded.

However, it appears that the underlying XML library that we use to construct the actual request is already encoding the text, which means we end up double XML encoding data.  This means if you send a message to a queue and that contains data that has to be XML escaped, the message will be "corrupted" as it flows across the wire.  If you look at the message in the portal, you will note that characters like `<`, `>`, and `&` have been escaped.  In addition, if you receive the message in Java, .NET or JavaScript, you'll get back expected content.  Since Python also double decodes by default, if you receive back with Python, you'll get the expected behavior.

Consider the following program:

```python
from azure.identity import SharedTokenCacheCredential
from azure.storage.queue import QueueClient, NoEncodePolicy, NoDecodePolicy, TextXMLEncodePolicy

cred = SharedTokenCacheCredential("matell@microsoft.com");
defaultClient = QueueClient("https://matellsa.queue.core.windows.net/", "test-queue", cred)
noEncodeClient = QueueClient("https://matellsa.queue.core.windows.net/", "test-queue", cred, message_encode_policy=NoEncodePolicy(), message_decode_policy=NoDecodePolicy())

defaultClient.enqueue_message("<!-- A comment --> Also there is some stuff here & there")
noEncodeClient.enqueue_message("<!-- A comment --> Also there is some stuff here & there")
```

After running, the Azure Portal shows this double escaping:

![image](https://user-images.githubusercontent.com/9602953/67127780-d7e19700-f1ae-11e9-9de8-4afe4d347e91.png)

In addition, if you look at the raw response from the service, when you do an operation like Peek, you'll see in the XML the double escaping has happened:

```
<?xml version="1.0" encoding="utf-8"?>
<QueueMessagesList>
  <QueueMessage>
    <MessageId>9fb5debe-5ca7-484e-bd51-8dc1b5e6b987</MessageId>
    <InsertionTime>Fri, 18 Oct 2019 20:39:31 GMT</InsertionTime>
    <ExpirationTime>Fri, 25 Oct 2019 20:39:31 GMT</ExpirationTime>
    <DequeueCount>0</DequeueCount>
    <MessageText>&amp;lt;!-- A comment --&amp;gt; Also there is some stuff here &amp;amp; there</MessageText>
  </QueueMessage>
  <QueueMessage>
    <MessageId>e8e3f235-7f51-49d4-8130-2dc422940a98</MessageId>
    <InsertionTime>Fri, 18 Oct 2019 20:39:32 GMT</InsertionTime>
    <ExpirationTime>Fri, 25 Oct 2019 20:39:32 GMT</ExpirationTime>
    <DequeueCount>0</DequeueCount>
    <MessageText>&lt;!-- A comment --&gt; Also there is some stuff here &amp; there</MessageText>
  </QueueMessage>
</QueueMessagesList>
```

Given that the underlying rest framework also does the escaping, I think we should remove `TextXMLEncodePolicy` and `TextXMLDecodePolicy` and make the default policy be NoEncode/NoDecode (the Base64 policy can remain for folks that want to pass binary data)

**Comment by johanste** [comment]
Interestingly enough, it looks like this bug was there in the previous version of `azure.storage.queues` as well.
