### ISSUE TITLE
[KeyVault] subject alternative names for certificate policy

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#8054]
I'm trying to do the following task: 
    # Create a new self signed certificate <yourname>-cert2, customize this certificate policy with subject alternative names "CN=*.contoso.com" and "CN=*.apps.contoso"

following the docs here: https://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.certificates.html#azure.keyvault.certificates.CertificatePolicy.san_upns

Here's my code: 
```
    cert_name = "lily-cert2" 
    cert_poller = certificate_client.create_certificate(cert_name)


    policy = CertificatePolicy(
        issuer_name="Self",
        subject_name=san_upns(["CN=*.contoso.com", "CN=*.apps.contoso"]),
    )
    updated = certificate_client.update_policy(
        certificate_name="lily-cert2", policy=policy
    )
```

I'm getting this error: 
  File "keyvault_keys_certificates_tasks.py", line 156, in task7
    subject_name=san_upns(["CN=*.contoso.com", "CN=*.apps.contoso"]),
NameError: name 'san_upns' is not defined

Is san_upns supposed to be something that I import? I don't see any specification on that in the docs above. Please help. Thanks!

**Comment by kaerm** [comment]
Thanks @lilyjma ! //cc: @iscai-msft

**Comment by lilyjma** [comment]
I think this works now: 
```
 policy = CertificatePolicy(
        issuer_name="Self",
        subject_name="CN=*.contoso.com", 
        san_unps = ["CN=*.contoso.com", "CN=*.apps.contoso"]
    )
```

**Comment by iscai-msft** [comment]
Hey @lilyjma assuming you are using v4.0.0.b4 of certificates, you should be using san_dns_names, it's [here](https://azure.github.io/azure-sdk-for-python/ref/azure.keyvault.certificates.html#azure.keyvault.certificates.models.CertificatePolicy) in the keyword arguments. I believe san_upns, san_dns, and san_emails were grouped together under san_upns during v4.0.0b2 but we have subsequently separated them

**Comment by iscai-msft** [comment]
closing this issue bc it has been resolved
