### ISSUE TITLE
The endpoint copied from the Azure portal for cognitive services gives errors

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-sdk-for-python#8065]
# To reproduce:

* Create a cognitive services resource in Azure (e.g. Face API)
* Copy the Endpoint from the overview page using the copy button
* Create a client using the copied endpoint and a key
* Access the cognitive service

## Expected

The call should work

## Actual

The calls fail with a "Resource not found" error. 

The 'correct' code involves removing the suffix from the Endpoint URL. For example an endpoint in the portal of `https://myfaceresource.cognitiveservices.azure.com/face/v1.0` needs to be stripped down to `https://myfaceresource.cognitiveservices.azure.com`.

# Discussion

Although there are docs that refer to this, it is not obvious and has caused a number of end users issues (for example at a student hackathon last weekend 3 sets of students came to the Microsoft booth to get help with this error). Therefore the docs are not sufficient. Users trying the code do not want to hit these errors as soon as they start using the code.

# Fix suggestion

The best fix would be to accept the full endpoint in the SDK, and manage this in the code.

**Comment by kaerm** [comment]
//cc: @ChrisHMSFT

**Comment by ChrisHMSFT** [comment]
Hi @jimbobbennett,

Thank you for the feedback. We are investigating a fix and will update here when we have made a change.

Thanks,
Chris

**Comment by jimbobbennett** [comment]
I notice that the Azure portal has now been updated to no longer show the `/face/v1.0` part in the Endpoint in the QuickStart or Overview pages, so this is not relevant any more.
