### ISSUE TITLE
[storage][readme]ContainerClient.from_connection_string requires "container_name" not "container"

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#8084]
We renamed the para "container" of ContainerClient.from_connection_string to "container_name" but did not update the readme.

**Comment by bsiegel** [comment]
@xiangyan99 I'm on it, fixing it in #8087

**Comment by mayurid** [comment]
This update should be merged once the changes which are in preview5 branch are in master.
I am proactively adding Blocking release to the PR to ensure it does not slip thru the cracks.
