### ISSUE TITLE
Constructing a BlockBlobService with a Management URL

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-python#811]
This is mostly an issue about (my) user error.  I am trying to understand the best way to construct a BlockBlobService with a management URL.

I construct a ServiceManagementService client like so.

```python
management_url = "https://management.core.windows.net"

sms = ServiceManagementService(subscription_id='--subscription-id--', cert_file='--cert-file--', host=management_url)
```

I want to construct a BlockBlobService, but based on the constructor arguments I cannot find a good way to just pass in the management_url.  There are parameters for custom domain and endpoint_suffix. Ideally, I just want to pass in the mangement_url.

Instead, I work around it by doing this, which seems wrong.

```python
client = BlockBlobService('--name--', '--primary-key--')
client.primary_endpoint = management_url
```

Is there a better way to implement this?

**Comment by lmazuel** [comment]
Hi @boumenot 

BlockBlobService is a feature of the azure-storage package, [see sample here](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py).

The ServiceManagementService will just allow you to create the storage account that will host this blob service. To that purpose, I suggest you to use `azure-mgmt-storage` more than `azure-servicemanagement-legacy`.

Also I made an example close to what you want in the front page of the documentation in readthedocs:
http://azure-sdk-for-python.readthedocs.io/en/latest/

I hope it helps, please tell me if you have further question.

**Comment by boumenot** [comment]
I am stuck using the old APIs because I am publishing extensions.  All of our auth is via a management certificate, and I do not believe there is a way to use the new APIs with a management certificate.  SPNs are the replacement, but straddling both worlds is difficult with just certs.

I find the samples to be very useful, thanks!

I know you make a distinction between the SDK, and Storage, but I often lump them together.

**Comment by yugangw-msft** [comment]
One option is to use service principal with certificate, check out the sample [here](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/certificate_credentials_sample.py). Yes, you do need to configure a service principal. With that you can acquire tokens through adal. Python SDK does take a bearer token, so things will be plumbed through.
For reference, below I mentioned the whole e2e flow using [xplat-cli](https://github.com/Azure/azure-xplat-cli/releases) to configure a cert associated service principal. You only need to do it once. Since you already have a certificate, only step 6,7,8 will be interesting, but i still list all to get things explained. 
```bash
1.	openssl version
OpenSSL 0.9.8e 23 Feb 2007
2.	azure -v
0.10.1
3.	openssl req -x509 -nodes -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365
(This gives you the private key and public key, and to be used at several places)
4.	cat key.pem cert.pem > final.pem
(This combines the private and public together and will be used to calculate the thumbprints)
5.	openssl x509 -in final.pem -noout -sha1 -fingerprint
SHA1 Fingerprint=BA:0E:9F:16:2C:F5:2A:57:79:1C:AE:BE:3E:06:F7:3F:01:9A:57:87
6.	azure ad app create -n 'yugangw-cert3' --home-page 'http://yugangw-cert3' -i "http://yugangw-cert3" --key-value "<base64 string from cert.pem>" --end-date "6/23/2017"
info:    Executing command ad app create
+ Creating application 'yugangw-cert3'
data:    AppId:                   579c9a29-4d8e-4ca3-944f-69d584966847
data:    ObjectId:                81f7e6cf-3066-4297-9798-01db70cd0980
data:    DisplayName:             'yugangw-cert3'
data:    IdentifierUris:          0=http://yugangw-cert3
data:    ReplyUrls:
data:    AvailableToOtherTenants:  False
info:    ad app create command OK
7.	azure ad sp create --applicationId 579c9a29-4d8e-4ca3-944f-69d584966847
info:    Executing command ad sp create
+ Creating service principal for application 579c9a29-4d8e-4ca3-944f-69d584966847
data:    Object Id:               c4b3e61f-f0d6-4f58-b8e1-dae6ea896a5c
data:    Display Name:            'yugangw-cert3'
data:    Service Principal Names:
data:                             579c9a29-4d8e-4ca3-944f-69d584966847
data:                             http://yugangw-cert3
info:    ad sp create command OK
8.	azure role assignment create --objectId "c4b3e61f-f0d6-4f58-b8e1-dae6ea896a5c" -o Contributor
info:    Executing command role assignment create
+ Finding role with specified name
|data:    RoleAssignmentId     : /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleAssignments/5da80e25-32e9-46e5-bb24-6582ffa998e4
data:    RoleDefinitionName   : Contributor
data:    RoleDefinitionId     : b24988ac-6180-42a0-ab88-20f7382dd24c
data:    Scope                : /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590
data:    Display Name         : 'yugangw-cert3'
data:    SignInName           :
data:    ObjectId             : c4b3e61f-f0d6-4f58-b8e1-dae6ea896a5c
data:    ObjectType           : ServicePrincipal
info:    role assignment create command OK
9.	azure login -u "http://yugangw-cert3" --service-principal --certificate-file C:\temp\sp-cert\final.pem  --thumbprint "BA0E9F162CF52A57791CAEBE3E06F73F019A5787" --tenant "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a"
info:    Executing command login
/info:    Added subscription AzureSDKADGraph2
+
info:    login command OK

```

**Comment by boumenot** [comment]
This is great!  Thank you @yugangw-msft!
