### ISSUE TITLE
[Feature Request] national cloud support

### ISSUE THREAD

**Issue by gitralf** [Azure/azure-sdk-for-python#814]
would be nice to have a way to get this running in national clouds like China or the new Microsoft Cloud Germany. There seem to be many hardcoded "windows.net" in the code where a cmdline switch (or Environment like in PowerShell) would really help...

**Comment by lmazuel** [comment]
Hi @gitralf 
Actually, it's not hardcoded at all (but I agree a tutorial could help to figure this out). You can change all the BaseUrl for all component. 

- Authentication: I suggest you to use [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-python) to get the token. 
- Service: You can change the "base_url" parameter when you create the client. For instance, the parameters section [here](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.compute.html#azure.mgmt.compute.ComputeManagementClient).

We plan to provide an "Azure environment" feature that will have all known clouds, to at least help you to connect easily without figure out yourself all the URLs. I'm not able to give you a date, but it's high on the backlog.
For reference:
https://github.com/Azure/autorest/issues/1082

Thanks,

**Comment by lmazuel** [comment]
Hi @gitralf 

Just wanted to add that for the ADAL part, there is now official simple support:
http://azure-sdk-for-python.readthedocs.io/en/latest/quickstart_authentication.html#using-adal

**Comment by lmazuel** [comment]
Hi @gitralf,

I just wrote a documentation about this case:
http://azure-sdk-for-python.readthedocs.io/en/latest/multicloud.html

I close this issue, since we have full support for multi-cloud and now a documentation. Please feel free to  comment on the issue if you think it's not enough, or to open a PR against [this file](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/multicloud.rst) with suggestion.

Thanks!

**Comment by gitralf** [comment]
thanks for this. I published a blog entry under azuregermany about this 
(in german :-) linking back to your dokumentation:

https://blogs.msdn.microsoft.com/azuregermany/2017/01/11/azure-sdk-fur-python-jetzt-auch-fur-azure-deutschland/

Ralf (ralfwi@microsoft.com)

Am 11.01.2017 um 02:37 schrieb Laurent Mazuel:
