### ISSUE TITLE
[EventHubs] Logs ERROR on `release_pump_on_timeout` when should be INFO or DEBUG.

### ISSUE THREAD

**Issue by mibrl12** [Azure/azure-sdk-for-python#8141]
Based on the release `azure-eventhub` `1.3.2`.

When there are no events  on pump release the `PartitionReceiver` considers it as an error. However this is a normal behaviour if there are no new messages.

In class `PartitionReceiver`:
```
    if self.eh_partition_pump.host.eph_options.release_pump_on_timeout:
        await self.process_error_async(TimeoutError("No events received"))
```
It seems to me that this should not be there.

**Comment by kaerm** [comment]
Thanks for letting us know @mibrl12! Someone from our team will look into this

**Comment by johanste** [comment]
I completely agree. Based on my experience troubleshooting event processor host, this is probably a reasonable INFO level message.

**Comment by annatisch** [comment]
Hi @mibrl12 - just hoping to clarify the expected behaviour here.

I cannot see the exact logged error message you're referring to - is this logged by the EventProcessorHost or EventHub SDK itself? Or do you mean that because we're calling into `process_error_async` here, the user-supplied error event handler is therefore logging this is an error?

**Comment by jongio** [comment]
@lmazuel @yunhaoling @YijunXieMS  - Can we work on getting this addressed soon?  It is 300 days old as of today.

**Comment by yunhaoling** [comment]
hey @mibrl12 , apologize for getting back to you late.

I would strongly recommend you to update to 5.1.0 (pip install --upgrade azure-eventhub) in which we addressed the issue you posted.
In the case you mentioned, in EH 5.1.0 we have `def receive_batch(self, on_event_batch, **kwargs):` which accepts `max_wait_time`, and if there is no messages received in the `max_wait_time` period, the callback would be called with empty list of events.

migration guide from v1 to v5 could be found here: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/migration_guide.md

for azure-eventhub 1.*, we might release a patch release for this in the future, but release time is not guaranteed.

**Comment by jongio** [comment]
@mibrl12 - Please re-open this if you still see the issue with v5.1.0.  Thanks, Jon
