### ISSUE TITLE
[Storage-file] Verify and correct files URL parsing and encoding

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#8147]
The URLs retrieved from the portal are not URL-encoded, however correct behaviour requires that they be encoded. Need to discuss with the storage team what the correct URLs need to be over the wire, and how we should handle URLs from the portal (if at all).

**Comment by xiafu-msft** [comment]
I think it doesn't matter if the url is encoded or not, storage sdk will unencode first then re-encode!
Probably we can close this issue?

**Comment by rakshith91** [comment]
Closing the issue now. Will reopen if an issue occurs.
