### ISSUE TITLE
Move samples to Samples/ folder

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#8152]
- [x] Blobs: #8171 
- [x] Files #8188
- [x] Queues #8185

**Copy Paste this in each of the PR**
- [ ] Got completely rid of test framework dependency
  - [ ] Remove assert Statements (if any)
  - [ ] Rename test_* to *
  - [ ] Get rid of setup and teardown
- [ ] All the samples are inside the samples/ folder and not anywhere else
- [ ] Update the literal includes
- [ ] Updated the links in the README
- [ ] Added samples to MANIFEST
- [ ] Verified Docs in sphinx are generated properly

**Comment by bsiegel** [comment]
Don't forget to also update each README with new links!
