### ISSUE TITLE
Service Buse Queues: More robust message receiving

### ISSUE THREAD

**Issue by eiliven** [Azure/azure-sdk-for-python#820]
It would be nice if message receiving was more robust. Specifically it would be nice if it was resilient to changes in the Service Bus implementation.

Currently _create_message() in _serialization.py is vulnerable to changes in the Service Bus, similar to what happened around 25.june 2016 when the 'strict-transport-security' header was added. This particular case was fixed with commits 97f97ce35dc92bdd5394d983a7b19ec84205898e and 073c97dfc5239dff9634432bb954397d832a7f7d, but the general weakness is still there: if any unexpected headers are received the Python SDK will fail to create a message. 

As a user of the SDK it is hard to remedy this without patching the SDK itself. It would be nice if messages could still be received in this situation, with the problem being logged instead of throwing an exception.

**Comment by lmazuel** [comment]
Hi @eiliven 

I agree that this part of the code is fragile and needs to be re-think.
Thanks for the feedback

**Comment by lmazuel** [comment]
Released https://pypi.python.org/pypi/azure-servicebus/0.21.0
Thank you for the feedback!
