### ISSUE TITLE
Azure azure.eventhub SDK, init EventData class with list parameter and raise exception 

### ISSUE THREAD

**Issue by yuhaii** [Azure/azure-sdk-for-python#8202]
We try to create EventData with list parameter event_list, but it got exception. I past part of code below:

        **event_list** = []
        for i in range(10):
            print("Before append")
            event_list.append(20)
            print("After append")
        sender.send(EventData(event_list))

        for i in range(100):
            print("Sending message: {}".format(i))
            message = "Message {}".format(i)
            sender.send(**EventData(message)**)

It raise exception "(<class 'AttributeError'>, AttributeError("'ValueBody' object has no attribute 'append'"), <traceback object at 0x0000011EB5AB8D88>)"

We checked the EventData source code in common.py file. Its comments say it can accept list object for initialization.

![image](https://user-images.githubusercontent.com/39817657/67542949-c43fae80-f721-11e9-9cbe-c40995c0ab1d.png)

This exception should throw from __init__ function or try_add function.
![image](https://user-images.githubusercontent.com/39817657/67543013-f4874d00-f721-11e9-90ad-9e03e6303d31.png)

![image](https://user-images.githubusercontent.com/39817657/67543044-1385df00-f722-11e9-90c3-cbcd3fc94841.png)

This is the python SDK I am using:
azure-common                       1.1.23
azure-eventhub                     5.0.0b1 

I try to update the SDK to latest version. But it still have this issue. 
![image](https://user-images.githubusercontent.com/39817657/67543084-3ca66f80-f722-11e9-86ec-09fd81f6cd51.png)

Please help us fixing this issue. Thanks!

**Comment by yuhaii** [comment]
This is the testing code we are using:
[test_python_code.zip](https://github.com/Azure/azure-sdk-for-python/files/3770359/test_python_code.zip)

The python version is  Python 3.6.8

**Comment by lmazuel** [comment]
@YijunXieMS ?

**Comment by YijunXieMS** [comment]
Will look into it

**Comment by yuhaii** [comment]
Hello @YijunXieMS , thanks for your reply. I confirmed with customer. Customer is ok to remove the list, customer has no more concerns. Thank you!
