### ISSUE TITLE
Preview 4 documentation in the package for Azure-Storage-blobs points to a broken link

### ISSUE THREAD

**Issue by loarabia** [Azure/azure-sdk-for-python#8230]
Look at the package description: https://pypi.org/project/azure-storage-blob/12.0.0b4/

The pointer to the "API Reference Documentation" points at a non-existent location. 

The link it points to is: https://azure.github.io/azure-sdk-for-python/ref/azure.storage.blob.html
The link I think it wants to point to is: https://azure.github.io/azure-sdk-for-python/ref/Storage.html#azure-storage-blob

Not sure if this is auto-generated. If it was manual, I'd submit a PR.

**Comment by scbedd** [comment]
This is a symptom of the new versioned github.io. 

There is only a single option that I'm aware of: release a new patch version of the package with the adjusted link to the new github.io.

**Comment by rakshith91** [comment]
Closing this issue. Verified the link is not broken in 12.0.0 GA version.
