### ISSUE TITLE
Using Advanced hub scenarios in SDK can not connect to IoT Edge device

### ISSUE THREAD

**Issue by secretsquirell** [Azure/azure-sdk-for-python#8238]
I'm using the register_x509.py sample in the advanced-hub-scenarios directory under the samples.  I'm attempting to register a leaf device under my Edge device (running as a transparent gateway).  I have had no issues using the certificates to register directly to IoT Hub.  

I have set my PROVISIONING_HOST to be the hostname of my edge device.  The SSL session appears to successfuly connect.  However I get the following when running the command 
`MQTTTransportStage: _on_mqtt_connection_failure called: Connection Refused: not authorised.
MQTTTransportStage(ConnectOperation): completing with error Connection Refused: not authorised.
SerializeConnectOpsStage(ConnectOperation): op failed.  Unblocking queue with error: Connection Refused: not authorised.
EnsureConnectionStage(MQTTSubscribeOperation): Connection failed.  Completing with failure because of connection failure: Connection Refused: not authorised.
EnsureConnectionStage(MQTTSubscribeOperation): completing with error Connection Refused: not authorised.
ProvisioningMQTTConverterStage(EnableFeatureOperation): completing with error Connection Refused: not authorised.
MQTTTransportStage: _on_mqtt_disconnect called: The connection was refused.
Unhandled exception in background thread
MQTTTransportStage: disconnection was unexpected`

**Comment by jlian** [comment]
Hello, I think (based on this https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/legacy-samples/register_x509.py) this is an IoT client SDK question. Would you mind posting this issue over at that repo https://github.com/Azure/azure-iot-sdk-python? You will get quicker help that way, thanks!

**Comment by secretsquirell** [comment]
that is not the exact sample it;s   azure-iot-sdk-python/azure-iot-device/samples/advanced-hub-scenarios/register_x509.py  I'll repost over at the azure-iot-sdk-python site

**Comment by jlian** [comment]
Thanks!
