### ISSUE TITLE
virtual_machine_extensions.create_or_update infinite polling

### ISSUE THREAD

**Issue by thommibens** [Azure/azure-sdk-for-python#8256]
I'm trying to create a Linux VM with the **OmsAgentForLinux**_  extension.
once the VM is created, the program starts creating the extension but each time ends up in an infinite polling.
Of course, I can set a timeout but this does not solve the problem, also because by controlling from the Azure Portal the extension always has the state "unavailable"

Code Snippet:
```python
def create_extension(self, rg_name, location, vm_name):
        name = '{}-OMS'.format(vm_name)
        client = self.compute_client.virtual_machine_extensions
        ext_type = 'OmsAgentForLinux'
        publisher = 'Microsoft.EnterpriseCloud.Monitoring' 
        ver = '1.7'
        params = VirtualMachineExtension(location = location, publisher = publisher, virtual_machine_extension_type = ext_type, type_handler_version = ver, auto_upgrade_minor_version = False)

        poller = client.create_or_update(rg_name, config.vm_name, name, params)

        poller.wait()
        return poller.result()
```

**Comment by BigCat20196** [comment]
Hi @thommibens , Compute has released the latest version 24.0.0. Please try it with the latest version. Thank you !

Fyi:
https://pypi.org/project/azure-mgmt-compute/24.0.0/
