### ISSUE TITLE
Per-request debug logging fails when request is repeated

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#8262]
`NetworkTraceLoggingPolicy` supports enabling debug-level logging for a single request. This is implemented with the `logging_enable` kwarg, e.g. using Key Vault:
```py
key_client.get_key("rsakey", logging_enable=True)
```
As implemented, `logging_enable` becomes an entry in the pipeline request's context.options dictionary. `NetworkTraceLoggingPolicy` pops this out. Should the request be sent again, e.g. by the retry policy, `logging_enable` won't be present in the options dictionary, and the repeated request won't be logged by `NetworkTraceLoggingPolicy`.

**Comment by xiangyan99** [comment]
Fixed
