### ISSUE TITLE
PythonSpec.html references are causing two redirects

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#8269]
**Issue:** 
PythonSpec.html is referenced in the following two places:

README.md
sdk/eventhub/azure-eventhubs/HISTORY.md

This causes two client redirects to: https://azure.github.io/azure-sdk/python_introduction.html

**Solution:**

Update the links to point directly to the python_introduction page.

**Comment by kaerm** [comment]
Thanks @jongio! //cc: @scbedd

**Comment by lmazuel** [comment]
Can't find none of the links anymore :(. Sorry @jongio it took so long to look at it, if you can still have this problem, could you create a new issue?
Thanks
