### ISSUE TITLE
ImportError: cannot import name 'Configuration' from 'azure.core' 

### ISSUE THREAD

**Issue by SiobhanBaynes** [Azure/azure-sdk-for-python#8289]
Since the [azure-core](https://pypi.org/project/azure-core/) package went to v1.0.0 on October 29th the following error message is appearing **'ImportError: cannot import name 'Configuration' from 'azure.core' (/databricks/python/lib/python3.7/site-packages/azure/core/__init__.py)'**

A workaround for now is to install the [1.0.0.0b4](https://pypi.org/project/azure-core/1.0.0b4/) package on your cluster.

**Comment by xiangyan99** [comment]
This is by design. Configuration is moved to azure.core.configuration.

**Comment by dsgouda** [comment]
@xiangyan99 I am trying to use azure-keyvault (version 1.1.0) which internally takes a dependency on
```
from azure.core import Configuration
```
Is there a workaround we could use?

**Comment by dsgouda** [comment]
Correcting myself, this error comes from the azure-keyvault-secrets library (which is in preview) and not azure-keyvault.
Also, the workaround for preview packages is pinning the version of azure core to an older one

**Comment by xiangyan99** [comment]
Solved offline. Close.
