### ISSUE TITLE
batch_read_file_in_stream doesn't work

### ISSUE THREAD

**Issue by lmcarreiro** [Azure/azure-sdk-for-python#8299]
When I call `batch_read_file_in_stream` I'm getting this error:

```
Error occurred in request., ConnectionError: ("bad handshake: SysCallError(-1, \'Unexpected EOF\')",)
```

It is not SSL related, because when I call `batch_read_file` that receives an image url instead of a local image, it works.

I'm calling it like this:

```python
with open(R"C:\...\teste.png", "rb") as imageStream:
    recognize_printed_results = computervision_client.batch_read_file_in_stream(imageStream,  raw=True)
```

It is something related to [this line](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py#L1716) (`body_content = self._client.stream_upload(image, callback)`), because when I change it to `body_content = image.read()` it works:

```diff
# Construct body
-body_content = self._client.stream_upload(image, callback) # <-- causes error in the `send` call below
+body_content = image.read()

# Construct and send request
request = self._client.post(url, query_parameters, header_parameters, body_content)
response = self._client.send(request, stream=False, **operation_config)
```

All examples about this API that I found on the internet, they use `batch_read_file`. I didn't find any using `batch_read_file_in_stream`.

**Comment by kaerm** [comment]
@lmcarreiro thanks for letting us know. I am tagging the right team to take a look at it

**Comment by lmazuel** [comment]
Hi @lmcarreiro 
That's a SSL connection error, which is happening way earlier in the process that any kind of streaming reading. So the code you changed shouldn't have any impact at all.

Could you confirm with 100% certainty (by replaying it several times), that in 100% of your failure the stream_upload is used, and in 100% of your success the direct read was used?

Thank you,
