### ISSUE TITLE
[Core] In stream upload, RetryPolicy should rewind the body position if possible, or throw

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#8307]
That's actually done in storage already, and should be part of the main Retry policy:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py#L496

**Comment by lmazuel** [comment]
Doing this like TDD, we need the following tests:
- We create a request and use "set_streamed_data_body" or we use "stream_content" kwarg (both are equivalent), we hack the transport to read part of this body, and we raise an exception, and we check when we come back we can read the whole body.
- We create a request and use "set_form_data" or we use "form_content" (both are equivalent), with content-type header 'multipart/form-data' (file upload). We hack the transport to read part of the file descriptor, and we raise an exception, and we check when we come back we can read the whole file. Create a tmp file with "tmpfile"

set_streamed_data_body:
https://github.com/Azure/azure-sdk-for-python/blob/3e878ffbaea57bae4537fd362aacf35cc43a934b/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L285-L290

stream_content kwarg:
https://github.com/Azure/azure-sdk-for-python/blob/3e878ffbaea57bae4537fd362aacf35cc43a934b/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L720

set_form_data:
https://github.com/Azure/azure-sdk-for-python/blob/3e878ffbaea57bae4537fd362aacf35cc43a934b/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L326-L331

form_content kwarg:
https://github.com/Azure/azure-sdk-for-python/blob/3e878ffbaea57bae4537fd362aacf35cc43a934b/sdk/core/azure-core/azure/core/pipeline/transport/_base.py#L719

Example of usage of both can be found here:
https://github.com/Azure/autorest.python/blob/azure-core/test/vanilla/Expected/AcceptanceTests/BodyFormData/bodyformdata/operations/_formdata_operations.py

In term of implementation, the storage one is fine for the first problem, but doesn't cover the second one. It's ok for storage, since they don't do multipart/form-data

**Comment by xiangyan99** [comment]
fixed
