### ISSUE TITLE
RecoveryServicesBackup API version change

### ISSUE THREAD

**Issue by WebSpider** [Azure/azure-sdk-for-python#8317]
As mentioned in https://azure.microsoft.com/en-us/updates/recovery-services-rest-api-version-deprecation-notice/ older API versions than 2019-05-13 are being deprecated. 

As a possible result, I have previously working code that is now reporting the error:

```
msrestazure.azure_exceptions.CloudError: Azure Error: BMSUserErrorInvalidAPIVersionMABProtectedItemsList
Message: Invalid API version for GetBackupProtectedItems.
Please user api version 2019-05-13 or higher.
```
Updating the instation of the RecoveryServicesBackupClient by using a specific API version as below does not seem to work. New client is instantiated as below:

```python
credentials = ServicePrincipalCredentials(client_id=str(rh.client_id), secret=str(rh.secret), tenant=rh.tenant_id)

    return RecoveryServicesBackupClient(credentials, sub_id, api_version="2019-05-13")
```
Is this possibly due to the API version being fixed, for example in https://github.com/Azure/azure-sdk-for-python/blob/466b0ba028fab8f14a4bbe2e7cc0cb639fd014d6/sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/operations/protected_items_operations.py#L36 ?

**Comment by pvrk** [comment]
@Webspider: Unfortunately, the python SDK is not routing to the latest API. We are in the process of publishing the latest python SDK which routes to this. May I know if you are protecting MAB items? If you are not retrieving MAB (Azure Backup agent - protecting files and folders), you can edit your code to include backupManagementType filter and it should work.

**Comment by WebSpider** [comment]
@pvrk at this point we're protecting Azure VMs (IaaSVM) only.

Please explain about backupManagementType filter, where should it be applied?

simplfied version of used code is:

```python
credentials = ServicePrincipalCredentials(client_id=str(rh.client_id), secret=str(rh.secret), tenant=rh.tenant_id)
backup_client =RecoveryServicesBackupClient(credentials, sub_id, api_version="2019-05-13")

pil = backup_client.backup_protected_items.list(vault_name=this_vault.arm__vault_name,
                                                            resource_group_name=this_vault.arm__rg_name)

for pi in pil:
  do_magic_stuff_for(pi)
```

**Comment by pvrk** [comment]
By passing as a filter "vm_filter = "backupManagementType eq 'AzureIaaSVM'"
Can you please try this?

**Comment by pvrk** [comment]
filter_string = _get_filter_string({
 'backupManagementType': 'AzureIaasVM'})

**Comment by WebSpider** [comment]
Hi!

Confirming that the following call fixes the issue for us:

```python
pil = bu_client.backup_protected_items.list(vault_name=this_vault_name,
                                                           resource_group_name=this_vault_rg,
                                                           filter="backupManagementType eq 'AzureIaaSVM'")
```

**Comment by pvrk** [comment]
We have released the latest python version which fixes this error. With this, you should be able to use this without the above filter.

https://pypi.org/project/azure-mgmt-recoveryservicesbackup/0.5.0/

**Comment by pvrk** [comment]
Closing this issue. Please feel free to re-open if this doesn't fix the problem.
