### ISSUE TITLE
Question: Azure Blob Storage Message Protocol

### ISSUE THREAD

**Issue by josiahlaivins** [Azure/azure-sdk-for-python#8321]
What Message Protocol does Azure Blob Storage use to transport large message packets? I have tried looking at the documentation and haven't found any information regarding this.

**Comment by mayurid** [comment]
@xiafu-msft and @zezha-msft to help

**Comment by xiafu-msft** [comment]
Hi @josiahlaivins 
Thanks for reaching out! Just to clarify your question, are you asking about message for Queue service(which means the you are using azure-storage-queue package)?

**Comment by josiahlaivins** [comment]
@xiafu-msft Yes, we are using the azure-storage-blob 2.1.0

**Comment by zezha-msft** [comment]
Hi @josiahlaivins, we are using HTTP/TCP, is there anything else that we can assist you with?

**Comment by josiahlaivins** [comment]
Perhaps Protocol was not the right word,  so we are asking about the _messaging protocol_. E.g. IotHub uses MQTT (used to support AMQP), and we are investigating message protocols that have larger messages sizes like ZeroMQ and DDP.

**Comment by zezha-msft** [comment]
Hi @josiahlaivins, I'm not sure I understand your question. We don't use message protocols.

**Comment by kartikshah9** [comment]
@josiahlaivins can you provide additional details. If your issue is resolved we can go ahead and close the issue.
