### ISSUE TITLE
Trouble deleting item from a container in cosmos

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#8327]
I'm following the readme and example.py in /samples to delete an item from a container, but kept coming across errors. 

When I do:

```
query = "SELECT * FROM test t where t.id='1'"

items = test_container.query_items(query=query, enable_cross_partition_query=True)
for i in items:
    print("to be deleted: " + json.dumps(i))
    test_container.delete_item(i, partition_key=PartitionKey(path="/id"))
```

I got: 

azure.cosmos.errors.CosmosHttpResponseError: Status code: 400
{"code":"BadRequest","message":"Partition key [{\"paths\": [\"/id\"], \"kind\": \"Hash\", \"version\": 2}] is invalid

Note that i'm able to get the item and print it. The partition key should also be correct because I created the container like this: 
```
container_name = "test"
try:
    container = db.create_container(
        id=container_name, partition_key=PartitionKey(path="/id")
    )
except exceptions.CosmosResourceExistsError:
    container = db.get_container_client(container_name)
```

I noticed that for the partition_key, you could also pass in a string, so I also tried: 
```
test_container.delete_item(i, partition_key="/id")
test_container.delete_item(i, partition_key="id")
```
both of which gave me this error:

azure.cosmos.errors.CosmosResourceNotFoundError: Status code: 404
{"code":"NotFound","message":"Entity with the specified id does not exist in the system.

In the docs here https://azuresdkdocs.blob.core.windows.net/$web/python/azure-cosmos/4.0.0b4/azure.cosmos.html#azure.cosmos.errors.CosmosHttpResponseError, it says that for the first param, you can pass in "The ID (name) or dict representing item to be deleted" so I tried passing in the ID of the item to be deleted:

`test_container.delete_item("1", partition_key=PartitionKey(path="/id"))`

The item looks like this on Data Explorer: 
```
{
    "id": "1",
    "msg": "happy halloween",
    "_rid": "RyhmAMRn73ABAAAAAAAAAA==",
    "_self": "dbs/RyhmAA==/colls/RyhmAMRn73A=/docs/RyhmAMRn73ABAAAAAAAAAA==/",
    "_etag": "\"1400d0f6-0000-0700-0000-5dbb35bc0000\"",
    "_attachments": "attachments/",
    "_ts": 1572550076
}
```

And I still got this: azure.cosmos.errors.CosmosHttpResponseError: Status code: 400
{"code":"BadRequest","message":"Partition key [{\"paths\": [\"/id\"], \"kind\": \"Hash\", \"version\": 2}] is invalid

I don't know if I passed in the wrong ID or not as the docs didn't specify. But the issue seems to lie in the partition key. There isn't much on the github.io page on the partition key either. Please help. Note that i'm using azure-core 1.0.0b4 and azure-cosmos 4.0.0b4. Thanks!

**Comment by annatisch** [comment]
Thanks @lilyjma - I will try to reproduce it :)

**Comment by annatisch** [comment]
Hi @lilyjma - I think the issue is that the specified `partition_key` needs to be the _value_ of the partition key in the item, not the path specified in the PartitionKey definition.

So the following should work:
```
test_container.delete_item("1", partition_key="1")
```
or 
```
test_container.delete_item(i, partition_key=i["id"])
```

**Comment by lilyjma** [comment]
I see; I tried it and it worked. But what if my partition is something like this: /address/zipcode? 

Thanks!

**Comment by annatisch** [comment]
Great - thanks @lilyjma 
No matter what your parition path, that needs to be a field in your item body, like so:
```
{
    "id": "1",
    "/address/zipcode": "00000"
    "msg": "happy halloween",
}
```
Then when you read or delete the item, use the value in the item body:
```
container.delete_item("1", partition_key="00000")
```

**Comment by lilyjma** [comment]
Follow up: 

The upsert_item() and create_item() methods of the SDK don't seem to check that the item being inserted actually has the address field in the right format. In fact, you could even insert an item that looks like this: 

{
    "id": "1",
    "msg": "this item has neither address nor zipcode field, but is still allowed to be inserted"
}

And now there seems to be no way we can identify the item. 

It's not only the SDK that allows this, Data Explorer on Portal also allows it.

**Comment by GuerreiroLeonardo** [comment]
Thank you [annatisch](https://github.com/annatisch), saved my life

**Comment by annatisch** [comment]
Thanks @GuerreiroLeonardo 
It sounds like you got stuck with the same behaviour - clearly we could document or sample this better...
Can I ask where the first place you searched for reference was?
Maybe we could add snippets to the API reference docs, or perhaps more details in the README for the package?

cc @simorenoh
