### ISSUE TITLE
ResourceHealth Mgmt SDK needed

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#8343]
Saw it in https://stackoverflow.com/questions/58653661/get-availability-status-of-azure-resources

Swagger exists:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resourcehealth/resource-manager

**Comment by dw511214992** [comment]
There is nothing about generating python sdk in readme file.

**Comment by changlong-liu** [comment]
Hi Service team, we plan to release a Python SDK for resourcehealth, and want to confirm whether the service side & swagger definition ready for a public release?

**Comment by xiangyan99** [comment]
It is released. https://pypi.org/project/azure-mgmt-resourcehealth/
