### ISSUE TITLE
Rendering of docstrings inside VSCode is incorrect

### ISSUE THREAD

**Issue by loarabia** [Azure/azure-sdk-for-python#8351]
Using VSCode: 1.39.2, and installing the GA versions of the Azure-storage-blob and azure-keyvault-key libraries, and then hovering over various items in the editor to get doc strings shows that there are missing snippets and some of the markup is still present.

class BlobServiceClient(account_url, credential=None, **kwargs, base_headers=None, **kwargs, **kwargs, initial_backoff=15, increment_base=3, retry_total=3, retry_to_secondary=False, random_jitter_range=3, **kwargs, logging_enable=False, **kwargs, proxies=None, **kwargs, **kwargs, **kwargs, **kwargs, **kwargs, **kwargs, **kwargs, logger=None, **kwargs)
A client to interact with the Blob Service at the account level.

This client provides operations to retrieve and configure the account properties as well as list, create and delete containers within the account. For operations relating to a specific container or blob, clients for those entities can also be retrieved using the get_client functions.

:param str account_url:

    The URL to the blob storage account. Any other entities included  
    in the URL path (e.g. container or blob) will be discarded. This URL can be optionally  
    authenticated with a SAS token.  
:param credential:

    The credentials with which to authenticate. This is optional if the  
    account URL already has a SAS token. The value can be a SAS token string, an account  
    shared access key, or an instance of a TokenCredentials class from azure.identity.  
    If the URL already has a SAS token, specifying an explicit credential will take priority.  
:keyword str secondary_hostname:

    The hostname of the secondary endpoint.  
:keyword int max_block_size: The maximum chunk size for uploading a block blob in chunks.

    Defaults to 4*1024*1024, or 4MB.  
:keyword int max_single_put_size: If the blob size is less than max_single_put_size, then the blob will be

    uploaded with only one http PUT request. If the blob size is larger than max_single_put_size,  
    the blob will be uploaded in chunks. Defaults to 64*1024*1024, or 64MB.  
:keyword int min_large_block_upload_threshold: The minimum chunk size required to use the memory efficient

    algorithm when uploading a block blob. Defaults to 4*1024*1024+1.  
:keyword bool use_byte_buffer: Use a byte buffer for block blob uploads. Defaults to False. :keyword int max_page_size: The maximum chunk size for uploading a page blob. Defaults to 4*1024*1024, or 4MB. :keyword int max_single_get_size: The maximum size for a blob to be downloaded in a single call,

    the exceeded part will be downloaded in chunks (could be parallel). Defaults to 32*1024*1024, or 32MB.  
:keyword int max_chunk_get_size: The maximum chunk size used for downloading a blob. Defaults to 4*1024*1024,

    or 4MB.  

        :start-after: [START create_blob_service_client]  
        :end-before: [END create_blob_service_client]  
        :language: python  
        :dedent: 8  
        :caption: Creating the BlobServiceClient with account url and credential.  

        :start-after: [START create_blob_service_client_oauth]  
        :end-before: [END create_blob_service_client_oauth]  
        :language: python  
        :dedent: 8  
        :caption: Creating the BlobServiceClient with Azure Identity credentials.

**Comment by lmazuel** [comment]
That's a VSCode Python behavior:
https://github.com/microsoft/vscode-python/issues/38

Especially @loarabia did you try PyCharm?

But maybe @brettcannon or @DonJayamanne have some recommendation for us?

**Comment by lmazuel** [comment]
Adding an actual screenshot
![image](https://user-images.githubusercontent.com/1050156/68805002-d1acd200-0617-11ea-8449-1f30f300985f.png)

**Comment by brettcannon** [comment]
You can all upvote https://github.com/microsoft/vscode-python/issues/38. 😄 Otherwise don't ask my opinion as it will be "keep your docstrings simple and ditch the `:param` stuff".

**Comment by lmazuel** [comment]
Coming back to this one year later, this is still the same thing:
![image](https://user-images.githubusercontent.com/1050156/96321409-28f6b780-0fca-11eb-9924-7059341fb593.png)

I'm closing this issue on favor of up-vote in the VSCode one, as Brett mentioned.
