### ISSUE TITLE
Type hint/docs for BlobClient.download_blob() is wrong

### ISSUE THREAD

**Issue by akx** [Azure/azure-sdk-for-python#8366]
The type hint for `download_blob` says it returns an iterable of bytes:
https://github.com/Azure/azure-sdk-for-python/blob/04b3a66eb89d8898fb1dd028dd37d1a15a52a398/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L528-L530
In reality, it returns a downloader object –
https://github.com/Azure/azure-sdk-for-python/blob/04b3a66eb89d8898fb1dd028dd37d1a15a52a398/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L599
– which in itself is not iterable-of-bytes either, but you're supposed to call its `.chunks()` method, like so:

```python
                bio = io.BytesIO()
                ssd: StorageStreamDownloader = bc.download_blob()
                for chunk in ssd.chunks():
                    bio.write(chunk)
```

For searchability, the likely error you'll get if you trip on this is

> TypeError: 'StorageStreamDownloader' object is not iterable

Library versions:
```
azure-core               1.0.0     
azure-storage-blob       12.0.0    
```

**Comment by kaerm** [comment]
@akx thanks for letting us know! Our team will look into that //cc @rakshith91

**Comment by rakshith91** [comment]
@akx Thanks for pointing it out. Addressing it along with some other mypy fixes.

**Comment by rakshith91** [comment]
@sebastiandziadzio 
Could you do `pip freeze` and let us know what version for azure-storage-blob you are using?
the `readinto()` has been added only in the latest version (12.0.0) and it doesn't exist in any of the previews(12.0.0.b*) . 

Let me know if you are using 12.0.0 and are still facing the same problem. Thanks :)

**Comment by sebastiandziadzio** [comment]
Works on 12.0.0, must have been on the preview. Thanks!

**Comment by secbug** [comment]
Sitting on this too. Trying to get an azure blob to be streamable through a flask response. Not easy then the object itself is not streamable.
