### ISSUE TITLE
Role_Assignments.Create breaks Azure Portal

### ISSUE THREAD

**Issue by 4c74356b41** [Azure/azure-sdk-for-python#837]
Also i seems that Create method doesn't accept a name and asks for a GUID, while it should, as there is a create_by_id method?

```
>>> a.role_assignments.create('/subscriptions/SUB_GUID', 'contributor', RoleAssignmentProperties('/subscriptions/SUB_GUID/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c', 'GROUP_GUID_WAS_HERE'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gleb_boushev\Envs\azure\lib\site-packages\azure\mgmt\authorization\operations\role_assignments_operations.py", line 316, in create
    raise exp
msrestazure.azure_exceptions.CloudError: The role assignment ID 'contributor' is not valid. The role assignment ID must be a GUID.
```

The working one (I created a random guid, is that how I am supposed to do that?)
'5f721e88-2cce-4cf4-a425-f19397d7277b' - my new random guid

```
>>> a.role_assignments.create('/subscriptions/SUB_GUID6', '5f721e88-2cce-4cf4-a425-f19397d7277b', RoleAssignmentProperties('/subscriptions/SUB_GUID/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c', 'GROUP_GUID_WAS_HERE'))
<azure.mgmt.authorization.models.role_assignment.RoleAssignment object at 0x0137C270>
```

so it works, but in the portal:
![_](https://cloud.githubusercontent.com/assets/16194643/19801959/ffa9b314-9d09-11e6-8c63-3fe4fd579706.png)

**Comment by lmazuel** [comment]
Hi @4c74356b41, thanks for the feedback.
@yugangw-msft did you try this scenario in the CLI? What do you think?

**Comment by 4c74356b41** [comment]
well, from powershell it works just fine, as from the cli.

**Comment by lmazuel** [comment]
@4c74356b41 there is two CLI:
- https://github.com/Azure/azure-cli based on this Python SDK
- https://github.com/Azure/azure-xplat-cli based on NodeJS

@yugangw-msft is working in the Python CLI, he might have see your scenario before, it's why I'm asking his expertise.

**Comment by 4c74356b41** [comment]
oh, i've never even knew that there's the python cli

**Comment by yugangw-msft** [comment]
>I created a random guid, is that how I am supposed to do that?

That is correct.
FYI, check out the cli's [code logics](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/custom.py#L157)
Also make sure you use the correct scopes, for a resource group if should be `/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/mygroup`

Hope this helps

**Comment by yugangw-msft** [comment]
then use `/subscriptions/11111111-2222-3333-4444-555555555555`

**Comment by 4c74356b41** [comment]
'/subscriptions/SUB_GUID' i used it?

**Comment by yugangw-msft** [comment]
correct

**Comment by 4c74356b41** [comment]
ok, but, the question is, is this a bug or did i do something wrong, and the guid\name question? why doesn't it accept name?

**Comment by yugangw-msft** [comment]
>a.role_assignments.create('/subscriptions/SUB_GUID6', '5f721e88-2cce-4cf4-a425-f19397d7277b', RoleAssignmentProperties('/subscriptions/SUB_GUID/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c', 'GROUP_GUID_WAS_HERE'))

If this is still the code you are using, based on the snapshot you later posted, your code is correct. I don't work on the portal, but I can guess other invalids assignments w/o user name might interfere. Can you remove all of them and retry the code snippet?

**Comment by 4c74356b41** [comment]
I'm sorry, but I don't entirely follow. I'm assigning this role to a single Azure AD Group that is present on the system. Can't you just try to reproduce this? It should take you like 1 minute...

**Comment by 4c74356b41** [comment]
well, turns out I cant reproduce it either :) I guess it was a temporary problem. Right now everything works great.

**Comment by 4c74356b41** [comment]
but the guid bug is there
