### ISSUE TITLE
Missing dependencies after installation

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-sdk-for-python#839]
`pip install --pre azure` does not pull all the dependencies. After installation it still asks for `msrest` and `msrestazure`

**Comment by lmazuel** [comment]
Hi @toddysm 
I close this one because it's a duplicate of this one:
https://github.com/Azure/azure-sdk-for-python/issues/644

There is a random issue with pip, sometimes it doesn't follow the 'extra_requires' as it should. Didn't found an easy workaround for now. :(
