### ISSUE TITLE
Missing documentation for eventhub

### ISSUE THREAD

**Issue by davidt99** [Azure/azure-sdk-for-python#8398]
The link to the API reference documentation on the github page leads to page that doesn't exist (https://azure.github.io/azure-sdk-for-python/ref/azure.eventhub).
The documentation that does exists (on https://azuresdkdocs.blob.core.windows.net/$web/python/azure-eventhub/5.0.0b4/index.html) is the one for the beta version (which I currently don't use), and the documentation for 1.3.2 is missing (which is the stable version).

**Comment by kaerm** [comment]
@davidt99 thanks for reporting that! We will definitely look into that //cc: @yunhaoling

**Comment by yunhaoling** [comment]
Hi @davidt99 ,

thanks for reporting the issue.
we've update the documentation link, you can find the latest beta documentation here:
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-eventhub/5.0.0b5/azure.eventhub.html.

The v 1.3.* documentation can be found here:
https://docs.microsoft.com/en-us/python/api/azure-eventhub/?view=azure-python-preview

**Comment by mayurid** [comment]
@davidt99 : Let us know if this fixes the issue.

**Comment by davidt99** [comment]
Yes, @mayurid Thanks! I would mention somewhere where the 1.3.* documentation can be found (maybe in the old repository).

**Comment by yunhaoling** [comment]
Hi @davidt99 ,

The docs for 1.3.* has been move to here: https://docs.microsoft.com/en-us/python/api/azure-eventhub/index?view=azure-python-previous.

We have released new azure-eventhub 5.0.0 and the documentations could be found here:
https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub?view=azure-python

**Comment by davidt99** [comment]
Thanks!
