### ISSUE TITLE
Remove exception message parsing from samples

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#8405]
We shouldn't attempt to catch exceptions that are raised during sample execution, like in [this example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/samples/list_operations.py#L88). Rather, we should let any exceptions get thrown normally as they do in [Administration package samples](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-administration/samples/access_control_operations.py).

**Comment by YalinLi0312** [comment]
Fixed.
