### ISSUE TITLE
ResourceNotFound

### ISSUE THREAD

**Issue by jpc2350** [Azure/azure-sdk-for-python#842]
Hi, I have a copy on my Mac of the Python-SDK (azure.mgmt.compute0.30RC6) I'm trying to create a script that queries the Instance_view.statuses.Displaystatus, however in doing this - I require the Resource_Group_Name.
When i run list_all i get the results expected (all the VM's, in the resource group named Testing), when I query the resource groups, I only see one - as expected (Testing) but when I query the following:

virtual_machines.get(GROUP_NAME, VM_NAME) 

I get a ResourceNotFound error - The resource (VM_NAME) under resource group 'Testing' was not found.

Any help greatly received.

**Comment by lmazuel** [comment]
Hi @jpc2350 , could you share some exact code sample? Listing VMs by resource groups is available and we don't know any problem. This is an example:
https://github.com/Azure-Samples/virtual-machines-python-manage/blob/master/example.py#L208

Thank you,

**Comment by jpc2350** [comment]
Hi @lmazuel , I think I have fixed the issue now, although I'm not sure how exactly. 
I was querying compute_client.virtual_machines.list(resource_group_name) and compute_client.virtual_machines.get(resource_group_name, VM_NAME) in the following code:

`for vm in compute_client.virtual_machines.list_all():
    VM_NAME = vm
    resource_group_name = testing
    compute_client.virtual_machines.get(resource_group_name, VM_NAME)
    status = compute_client.virtual_machines.get(resource_group_name, VM_NAME).instance_view.statuses[1].display_status
    print("\tVM: {}, Tags: {}, Location: {}, status: {}".format(vm.name, vm.tags, vm.location, status))`


I've managed to get this working by changing resource_group_name with GROUP_NAME
