### ISSUE TITLE
Validate SDist Contents

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#8420]
In `non-management` packages, we should verify that the SDIST contains the additional files we expect:

* `doc` (optional?)
* `tests`
* `samples`

However, we don't need to check this for _all_ packages. We only need to validate the presence of such folders when they are present within the package directory on disk.

**Comment by scbedd** [comment]
@lmazuel I'm not certain that we should always check for a `doc` folder, given that only two (`azure-core` and the new `azure-eventhub`) packages have a doc folder right now.

**Comment by lmazuel** [comment]
Yes, that was actually what I was thinkin, and for the three of them (if folder exists, must be in MANIFEST)

**Comment by scbedd** [comment]
Ok. Will do this for all 3 of the folders above.
