### ISSUE TITLE
InvalidGrantError when signing in

### ISSUE THREAD

**Issue by tstringer** [Azure/azure-sdk-for-python#843]
Using the `UserPassCredentials` class, I instantiate it with the correct username and password of a user in my AAD. Trying to use these credentials (or any credentials in my AAD), I get the following error:

> msrest.exceptions.AuthenticationError: , InvalidGrantError: (invalid_grant) ... To sign into this application the account must be added to the outlook.com directory

For what it's worth, all of the users I'm testing with are outlook.com email addresses/users.

Any thoughts on the cause and resolution of this?

**Comment by lmazuel** [comment]
Hi @tstringer 
@yugangw-msft Any ideas?

**Comment by tstringer** [comment]
@lmazuel @yugangw-msft Thanks for the quick response! Digging through the source, I then tried using the `BasicAuthentication` class. That got me further! But looks like another issue with the auth header in the request:

> msrestazure.azure_exceptions.CloudError: Azure Error: AuthenticationFailedInvalidHeader Message: Authentication failed. The 'Authorization' header is provided in an invalid format

**Comment by yugangw-msft** [comment]
The outlook account belong to MSA, so called Microsoft account , and regular username-password flow represented by `UserPassCredentials` will not work. You need to use [device flow](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/device_code_sample.py), or create an org-id in your tenant (make sure do not turn on multi-factor authentication)

**Comment by tstringer** [comment]
@yugangw-msft Thanks for the reply! Is this specific to *just* MSAs? So in other words, we would just use the `AADTokenCredentials` class just for MSA auth?

**Comment by yugangw-msft** [comment]
`AADTokenCredentials` is a wrapper around access tokens which were acquired for accounts through more advanced libraries such as adal-python. Under this context, there are 2 accounts you should consider, the MSA we talked about, or federated accounts which AAD sync from on-premise ADFS servers, including those '@microsoft.com' ones

**Comment by lmazuel** [comment]
Hi @tstringer ! Did the answer @yugangw-msft give to you enough or have you something else to confirm? Could we close this issue? :)
Thanks!

**Comment by tstringer** [comment]
Yep, let's go ahead and close this issue for now. I haven't had the chance to try out @yugangw-msft's recommendations (also a **super big thank you** to @yugangw-msft for the assistance!!! 😄 ), but if it doesn't resolve then I can reopen.

Thanks, all! 👍
