### ISSUE TITLE
Small error in example code in keyvault secrets

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#8436]
When setting permissions for operations for key vault secrets as shown in example code [here](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-secrets) using Cloud Shell, an error is thrown saying that 'create' is not a valid value for '--secret-permissions'. When checked on Portal (key vault -->Access policies -->Secret Permissions), 'create' is indeed not an option. Neither is 'update'. 

The command I'm referring to is this: 

`az keyvault set-policy --name my-key-vault --spn $AZURE_CLIENT_ID --secret-permissions backup delete get list create update decrypt encrypt`

**Comment by chlowell** [comment]
Thanks Lily! This was fixed by #8396.
