### ISSUE TITLE
Dots in DnsConfig's relative_name

### ISSUE THREAD

**Issue by bayotop** [Azure/azure-sdk-for-python#8446]
The Azure Portal UI allows you to create a Traffic Manager profile with a `FQDN` with n-level subdomains (e.g. custom.dev.custom.trafficmanager.net).

However, the Traffic Manager profile name can't include dots. The UI seems to handle this by replacing the dots with hyphens (but without the FQDN changing).

Is it possible to do this via the SDK? The `DnsConfig` class only has a `relative_name` parameter and the `Profile` class doesn't allow to specify a name separately. Am I missing something here?

**Comment by rohinkoul** [comment]
@bayotop traffic manager profile is an ARM resource and name of the ARM resource is the one that should have dashes and dnsConfig relative name can have dots. See https://docs.microsoft.com/en-us/rest/api/trafficmanager/profiles/createorupdate the request body has name property that should be the name with dashes and dnsConfig relative_name can contain the dotted name. What SDK are you using?

**Comment by bayotop** [comment]
I was missing something, indeed. Realised now that I can specify the profile name in the `client.profiles.create_or_update()` call. 

Thanks for looking into it!
