### ISSUE TITLE
Dependency problem between Identity, Cosmos, and Core

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#8454]
I'm trying to use cosmos and key-vault-secrets in a Flask app and came across problems with the different versions of the libraries depend on each other. For reference, I have these imports in my code: 

```
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from azure.cosmos import errors, CosmosClient
```

I noticed that when I did `pip install azure-keyvault-secrets azure-identity` as instructed in the directions in the README, if there's an existing azure-core version installed and it's not 1.0.0, it'll be uninstalled and the 1.0.0 version will be installed. I had core 1.0.0b4 installed because I was using  azure-cosmos 4.0.0b4. (I gathered from the engineering team there was a breaking change between azure-core 1.0.0 and 1.0.0b4 so in order for cosmos and core to work, the two library versions have to match.) I got the following since they didn't match:  

![image](https://user-images.githubusercontent.com/25314976/68322398-33999480-0078-11ea-9b99-500ae646c4e9.png)

For reference, library versions so far: 

azure-common                       1.1.23
azure-core                         1.0.0
azure-cosmos                       4.0.0b4
azure-identity                     1.0.1
azure-keyvault-secrets             4.0.0

So I reinstalled azure-core 1.0.0b4, but then the Identity library complained: 

![image](https://user-images.githubusercontent.com/25314976/68325015-79a52700-007d-11ea-853c-14e28bf6efe3.png)

I thought maybe azure-core 1.0.0b5 would work with the current Identity library, and there's also cosmos 4.0.0b5 so the two would match. But I couldn't pip install core 1.0.0b5 although it's listed as a published on the [github.io page](https://azure.github.io/azure-sdk-for-python/ref/Core.html). 

Nevertheless, I installed cosmos 4.0.0b5 just to experiment, and this showed up: 

![image](https://user-images.githubusercontent.com/25314976/68323387-2f6e7680-007a-11ea-948c-c8d0d168609c.png)

Versions so far: 

azure-common                       1.1.23
azure-core                         1.0.0b4
azure-cosmos                       4.0.0b5
azure-identity                     1.0.1     
azure-keyvault-secrets             4.0.0

And so I reinstalled core 1.0.0, but then of course Cosmos complains (but for a different reason than the b4 version mentioned at the very beginning):  

![image](https://user-images.githubusercontent.com/25314976/68323596-9be97580-007a-11ea-8b3f-0d765888f922.png)

Conclusion: Identity 1.0.1 seems to work only with core 1.0.0 and cosmos has to match core version to work properly. Now we have core 1.0.0 and 1.0.0b5, identity 1.0.0 and 1.0.0b5 (1.0.1 not shown for some reason), and cosmos 4.0.0b4 and 4.0.0b5 according to github.io links below. 

My expectation was that core 1.0.0b5 and cosmos 4.0.0b5 would work; there's also identity 1.0.0b5 if all of them have to match. But core 1.0.0b5 can't be installed as of now, so there doesn't seem to be a working combination for these three libraries.

https://azure.github.io/azure-sdk-for-python/ref/Cosmos.html
https://azure.github.io/azure-sdk-for-python/ref/Identity.html?highlight=identity
https://azure.github.io/azure-sdk-for-python/ref/Core.html?highlight=core

**Comment by annatisch** [comment]
Thanks @lilyjma - you're quite right that Cosmos b4 will not be compatible with these releases.
To use these library together you will need to use Cosmos 4.0.0b5, which will work with Core 1.0.0.
So your finally libraries will probably be something like:
Core 1.0.0
Identity 1.0.1
Cosmos 4.0.0b5
Keyvault-Secrets 4.0.0

**Comment by lilyjma** [comment]
Thanks for the quick response! @annatisch I tried those combinations--that was the last scenario I mentioned before the conclusion part.

**Comment by annatisch** [comment]
Ah - thanks @lilyjma - I didn't see that.
This seems like a separate issue specific to Comos rather than a compatibility issue.
Could you please show me a code snippet that causes the above error?

**Comment by lilyjma** [comment]
I recreated what I did in the app here:

```
from azure.cosmos import CosmosClient, PartitionKey, errors
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

KEY_VAULT_URI = "https://flaskreact.vault.azure.net/"

credential = DefaultAzureCredential()
client = SecretClient(vault_url=KEY_VAULT_URI, credential=credential)
key = client.get_secret("cosmosKey").id
url = client.get_secret("cosmosURI").id

client = CosmosClient(url, credential=key)
```

I get this error when running the code: 
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    client = CosmosClient(url, credential=key)
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cosmos\cosmos_client.py", line 172, in __init__
    url, auth=auth, consistency_level=consistency_level, connection_policy=connection_policy, **kwargs
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cosmos\_cosmos_client_connection.py", line 202, in __init__
    database_account = self._global_endpoint_manager._GetDatabaseAccount(**kwargs)
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cosmos\_global_endpoint_manager.py", line 121, in _GetDatabaseAccount
    database_account = self._GetDatabaseAccountStub(self.DefaultEndpoint, **kwargs)
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cosmos\_global_endpoint_manager.py", line 144, in _GetDatabaseAccountStub
    return self.Client.GetDatabaseAccount(endpoint, **kwargs)
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cosmos\_cosmos_client_connection.py", line 2303, in GetDatabaseAccount
    headers = base.GetHeaders(self, initial_headers, "get", "", "", "", {})  # path  # id  # type
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cosmos\_base.py", line 247, in GetHeaders
    cosmos_client_connection, verb, path, resource_id, IsNameBased(resource_id), resource_type, headers
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cosmos\auth.py", line 58, in GetAuthorizationHeader
    verb, resource_id_or_fullname, resource_type, headers, cosmos_client_connection.master_key
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cosmos\auth.py", line 84, in __GetAuthorizationTokenUsingMasterKey
    key = base64.b64decode(master_key)
  File "C:\Users\jiayma\AppData\Local\Continuum\anaconda3\Lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (81) cannot be 1 more than a multiple of 4

**Comment by annatisch** [comment]
Thanks @lilyjma - it looks like Cosmos is attempting to base 64 decode the Key value.
```
key = base64.b64decode(master_key)
```
Could you please check the value of the Key that is being passed in?
For example, whether is is bytes or string, or whether it's already base 64 encoded or not?

**Comment by lilyjma** [comment]
The key is this: 
https://flaskreact.vault.azure.net/secrets/cosmosKey/082432eccd42418e9a9a1a7da9e4743b

<class 'str'>

**Comment by mayurid** [comment]
//cc: @srinathnarayanan

**Comment by annatisch** [comment]
Thanks @lilyjma,
This doesn't look like a valid cosmos key, so I think  in this case maybe the wrong value has been stored in the key vault.

**Comment by annatisch** [comment]
Actually, looking at the keyvault docs - it looks like we need to get a different attribute on the secret (`value` rather than `id`):
```
credential = DefaultAzureCredential()
client = SecretClient(vault_url=KEY_VAULT_URI, credential=credential)
key = client.get_secret("cosmosKey").value
url = client.get_secret("cosmosURI").value

client = CosmosClient(url, credential=key)
```

**Comment by lilyjma** [comment]
yes, it works now! Thanks @annatisch! Sorry about that silly mistake... I'll try to be more careful next time.
