### ISSUE TITLE
[Blob][Queue][File]Test Cleanup

### ISSUE THREAD

**Issue by xiafu-msft** [Azure/azure-sdk-for-python#8489]
Go over the test and remove unused file
eg. https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/tests/blob_performance.py

**Comment by tasherif-msft** [comment]
@xiafu-msft is this file being used anywhere? I checked and it seems its currently not being used. Can we just go ahead and delete it?

**Comment by tasherif-msft** [comment]
Created pr. closing.
