### ISSUE TITLE
Azure.Identity documentation feedback

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-python#8498]
Feedback on: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.0.0/index.html

- **DefaultAzureCredential** - Clicking "DefaultAzureCredential" in the table does not go to that class. It is the only like that isn't an aka.ms link so that may have something to do with it.
<del>- **CertificateCredential** - `cert_path` says that the certificate must not be password protected. According to @johanste, this flow should work with a password-protected private key in the cert.</del> Already tracked by #5764.
- **Certificate Credential** - No information or links to how to actually associate the certificate with a service principal. I found this flow to be particularly confusing and there is precedent since Managed Identity and Device Code have links to external docs.
- **DeviceCodeCredential** - while it did link to documentation, that documentation was in-depth info on how the REST calls work. The would point of the SDK is that the user doesn't need to worry about that. What the documentation was lacking is all the work that needs to be done in the portal to correctly set this up to work. I ended up Googling and finding this, which was helpful: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow
- **ManagedIdentityCredential** - Here again, the linked documentation was dense and not helpful in me actually setting up the end-to-end  configuration. I ended up consulting many docs and finally using the following Azure Friday video to figure out how to set up and test this: https://binged.it/2PUj704

cc/ @mayurid

**Comment by johanste** [comment]
> According to @johanste, this flow should work with a password-protected private key in the cert.
Not high priority, but is there a reason to not support password protected private keys?

**Comment by chlowell** [comment]
> 
> Not high priority, but is there a reason to not support password protected private keys?

No. Supporting them is tracked by #5764.
