### ISSUE TITLE
[KV] azure.keyvault.certificates throwing "You can only set at most one of san_emails, san_dns_names, and san_upns" when downloading certificate

### ISSUE THREAD

**Issue by brianholley** [Azure/azure-sdk-for-python#8510]
Downloading valid self-signed certificates from a keyvault thows this error: "You can only set at most one of san_emails, san_dns_names, and san_upns"

Repro steps sing azure-keyvault-certificates v4.0.0b5:
1. Create a new self-signed certificate: `New-SelfSignedCertificate -CertStoreLocation cert:\currentuser\my -dnsname bad.com`
2. Export certificate and upload to keyvault
3. Download using `certificate_client.get_certificate(name="bad")`

Easy test certificates are attached here: [good_bad_certs.zip](https://github.com/Azure/azure-sdk-for-python/files/3821013/good_bad_certs.zip). You can just import these into a keyvault and try to download them with `certificate_client.get_certificate()`. Both of these certificates have Subject Alternative DNS Name set (but only DNS name, not emails or UPN)

However, a self-signed certificate created using azure.keyvault.certificate can be downloaded again with no problems. This code works fine, where downloading externally created certificates doesn't:
```python
from azure.keyvault.certificates import CertificateClient, CertificatePolicy
from azure.identity import InteractiveBrowserCredential

credential = InteractiveBrowserCredential()
certificate_client = CertificateClient(vault_url="https://test.vault.azure.net/", credential=credential)
policy = CertificatePolicy(issuer_name="Self", subject_name="CN=good.com", san_dns_names=["good.com"])
create_certificate_poller = certificate_client.begin_create_certificate(name="good", policy=policy)
cert = certificate_client.get_certificate(name="good")
print(cert.name)
```

**Comment by kaerm** [comment]
@brianholley thanks for reporting this, our team will look into it! //cc: @mayurid @chlowell

**Comment by chlowell** [comment]
Thanks again for reporting this! We'll fix it for the next release.
