### ISSUE TITLE
Support Additional CLI Publish at Release

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#8522]
As a post-step to a release of a full revision of the azureml sdk, a new CLI wheel is published. This new wheel takes a dependency on the new version of the azureml sdk that has just been published.

This cli wheel is then uploaded to a blob storage location.

The existing AML pipelines already have Powershell scripts for this, just need to migrate and integrate.

**Comment by kurtzeborn** [comment]
Pretty sure this isn't needed any more.  We'll Open a new issue if it is.
