### ISSUE TITLE
Update Package Versioning for each Migrated Package to Individually Version

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#8523]
As the azureml packages migrate into the repo, I believe we should swap them to have individual version.py files the same way the rest of the repository does.

Leverage versioning scripts in combination with the current AML release methodology to "stamp" the universally revved package version from the common version file onto the individual packages. This will allow both the two methodologies to exist, while also enabling the shipping of `SDISTs`.

Essentially.

1. Clone sdk-for-python
2. Get current version number
3. Run versioning script within cloned `sdk-for-python` to stamp the migrated packages with the correct version for the current release.
4. Run builds as normal.

**Comment by kurtzeborn** [comment]
Pretty sure this isn't needed any more.  We'll Open a new issue if it is.
