### ISSUE TITLE
Azure Function Event Hub Trigger - event.iothub_metadata returns empty dict

### ISSUE THREAD

**Issue by bran-ch** [Azure/azure-sdk-for-python#8533]
When streaming IoT Hub data into Event Hub, the fields in the EventHubEvent are not correctly populated.

```
import logging
import azure.functions as func

def main(event: func.EventHubEvent):
    body = event.get_body().decode('utf-8')
    logging.info('Body: ' + body) # Returns the body as expected
    logging.info('IoT Hub Metadata: ' + str(event.iothub_metadata)) # Returns an empty dict, not expected
```

I am using IoT Central and the same data stream to a blob storage provides a `Properties` and `SystemProperties` field. On further investigation, the SDK seems to use `EventHubTriggerConverter` (in `functions/eventhub.py`) to convert the incoming event and extracts the metadata like so:

``` eventhub.py
class EventHubTriggerConverter(EventHubConverter,
                               binding='eventHubTrigger', trigger=True):
...
    @classmethod
    def decode_single_event(cls, data,
                            trigger_metadata) -> _eventhub.EventHubEvent:
...
        iothub_metadata = {}
        for f in trigger_metadata:
            if f.startswith('iothub-'):
                v = cls._decode_trigger_metadata_field(
                    trigger_metadata, f, python_type=str)
                iothub_metadata[f[len('iothub-'):]] = v
```

but the `trigger_metadata` is a dict with `Properties` and `SystemProperties` included.

**Comment by kaerm** [comment]
@bran-ch thanks for reporting this, our team will look into this. //cc: @mayurid @yunhaoling

**Comment by etf5000** [comment]
Seeing the same issue. The metadata seems to be exposed correctly using the JavaScript and .net SDK.

**Comment by annatisch** [comment]
@kaerm  - This seems to be related to Azure Functions and/or IoT Hub - do you know the best person to direct it to?

**Comment by jlian** [comment]
@iluican can you assign someone to look at this?

**Comment by jlian** [comment]
@jebrando is this part of the python client SDK?

**Comment by jebrando** [comment]
@jlian I believe this is from the Eventhub SDK and not the IoTHub SDK.  You may have to ping someone in that area.

**Comment by jlian** [comment]
@kaerm can you help redirect?

**Comment by kaerm** [comment]
@yunhaoling can you take a look?

**Comment by yunhaoling** [comment]
Hi @kaerm , I don't think the code is part of our python EventHub SDK but it could be the `Azure Function Event Hub Trigger` that uses our sdk. Anyway I think we'd better reach out to the related Azure Function Team for more information.

**Comment by kaerm** [comment]
Thanks @yunhaoling //cc: @mayurid

**Comment by YijunXieMS** [comment]
Azure function team is looking

**Comment by Hazhzeng** [comment]
Hey @bran-ch,

After investigation, this is due to a schema change in function triggers metadata.
https://github.com/Azure/azure-functions-python-worker/issues/418

**Comment by Hazhzeng** [comment]
This issue should be fixed in the next release.

**Comment by ramya-rao-a** [comment]
Looks like the upstream issue https://github.com/Azure/azure-functions-python-worker/issues/418 is closed as fixed, but folks are still reporting problems.

If anyone here is still seeing this issue, please log a new GitHub issue at https://github.com/Azure/azure-functions-python-worker

Closing this issue as there are nothing that can be done from the Python Event Hubs SDK perspective.

**Comment by ramya-rao-a** [comment]
Also, based on https://github.com/Azure/azure-functions-python-worker/issues/639 and https://github.com/Azure/azure-functions-python-worker/issues/698, it looks like we are just waiting for the next deployment of the python worker
