### ISSUE TITLE
Huge "recordings" folders?

### ISSUE THREAD

**Issue by akx** [Azure/azure-sdk-for-python#8534]
Is having 

* 460 megabytes of YAML in `sdk/storage/azure-storage-blob/tests/recordings`
* 208 megabytes of YAML in `sdk/core/azure-servicemanagement-legacy/tests/recordings`

actually necessary? 

I suppose I should be lucky they're not shipped in the production wheels :)

**Comment by kaerm** [comment]
@akx thanks for letting us know! someone from our team will look into it //cc: @mayurid @rakshith91

**Comment by mayurid** [comment]
Thanks @akx for reporting this. We are looking into removing these and will keep you posted when that is done.

**Comment by akx** [comment]
Are these required at _all_ in the repository though, or could they be shipped in a compressed format?

Disk space is cheap, yes, but it's still irritating to have a gigabyte of YAML lying around on my laptop's disk when I need to dig in to the SDK's source.

Pulling down a clone of this repo as it is (a5b5510935f63c535a6f143952d51cf200760643 right now) takes **half a gig** of downloaded objects:
```
Receiving objects: 100% (165603/165603), 522.05 MiB | 3.58 MiB/s, done.
```

Indeed, throughout the _history_ of the repository, the largest blobs recorded are all these test recordings:
```
$ git rev-list --objects --all | git cat-file --batch-check='%(objectname) %(objecttype) %(objectsize) %(rest)' | grep '^[^ ]* blob' | gsort -n -r -k3 | head -n10
ddd9c21675273190e6e3e79e21588f0acb279244 blob 50358136 sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_copy_blob_async_private_blob_with_sas.yaml
a1ae1c9e0320b312e85856a97debe29c9715264e blob 49848228 sdk/core/azure-servicemanagement-legacy/tests/recordings/test_legacy_mgmt_misc.test_add_data_disk_from_url.yaml
9047ee7ef1aa61c947b41a0abfd97d566aceefa7 blob 49848228 azure-servicemanagement-legacy/tests/recordings/test_legacy_mgmt_misc.test_add_data_disk_from_url.yaml
ed816df7b388405995ad268b1054474c8e052b98 blob 49843265 azure-servicemanagement-legacy/tests/recordings/test_legacy_mgmt_misc.test_add_data_disk_from_disk_name.yaml
2d8f217b9af486eb8a755d3c393f9247c6d57b75 blob 49843265 sdk/core/azure-servicemanagement-legacy/tests/recordings/test_legacy_mgmt_misc.test_add_data_disk_from_disk_name.yaml
b1832e1d69a10504058f93286508774c926ed3ec blob 49080603 azure-servicemanagement-legacy/tests/recordings/test_legacy_mgmt_misc.test_add_update_delete_get_list_disk.yaml
180824289bf642b1ddf034be4d77fad73c19e4e0 blob 49080603 sdk/core/azure-servicemanagement-legacy/tests/recordings/test_legacy_mgmt_misc.test_add_update_delete_get_list_disk.yaml
6d10f78770294573bcc46d6577041b57c7eb0ca3 blob 46917799 sdk/storage/azure-storage-blob/tests/recordings/test_large_block_blob.test_put_block_stream_large_with_md5.yaml
0bc63f68ecac6941732a53df0cf63140cf2c7a33 blob 46917764 sdk/storage/azure-storage-blob/tests/recordings/test_large_block_blob.test_put_block_stream_large_with_md5.yaml
1a716603a5b649d654dcc44d96f1056f38fa09ab blob 46917514 sdk/storage/azure-storage-blob/tests/recordings/test_large_block_blob.test_put_block_stream_large.yaml
```

I know we can't get rid of the YAML in the repo without modifying history, but still, something to think about.

Compressing the Storage recordings with `gzip -9` brings them down to **5.4 megabytes**.

**Comment by xiafu-msft** [comment]
Hi @akx 
Sorry about the inconvenience again.

@xiangyan99 is there a reason we close this pr #8597

**Comment by rakshith91** [comment]
> is there a reason we close this pr #8597

@xiafu-msft The changes are merged.

@akx We have removed the yaml files from manifest. So sdist of the package will not have any recordings. Also, we are working on a long term solution to remove the recordings entirely from the repo. We will update you once the changes are made. Feel free to keep the issue open / feel free to close it - upto you :)
Thanks again for reporting and sorry for the inconvenience.

**Comment by xiangyan99** [comment]
#8625
