### ISSUE TITLE
Blob sample links are broken

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#8558]
Go here: https://github.com/Azure/azure-sdk-for-python/tree/348002b1b0472366104ca98004f824b9bdb07e76/sdk/storage/azure-storage-blob#more-sample-code

Click on any link with .py extension and you'll get a 404.

**Comment by kaerm** [comment]
thanks @jongio! //cc: @rakshith91

**Comment by rakshith91** [comment]
Thanks for reporting this @jongio . It seems like you are using an older commit from the tree and these links have been updated recently. I would suggest using the links from the master branch.

 https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob#more-sample-code

**Comment by jongio** [comment]
Thanks. I arrived at that location via docs or google, so I will see if I can re-trace my steps.  Will re-open if I can repro.
