### ISSUE TITLE
Difficult to extract a response from azure.storage.blob.BlobClient.stage_block()

### ISSUE THREAD

**Issue by timuralp** [Azure/azure-sdk-for-python#8565]
Reading through the `azure.storage.blob` code, I noticed that there is a way to pass a type or callable to retrieve a response from various operations, like `stage_block()` https://github.com/Azure/azure-sdk-for-python/blob/e8993089a8624e6e78f5e1d2fe02876d69cd2c3a/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_block_blob_operations.py#L215

This is great, as I'd like to be able to examine the response headers (specifically, the `x-ms-content-crc64` header). Unfortunately, `BlobClient` swallows this value https://github.com/Azure/azure-sdk-for-python/blob/e8993089a8624e6e78f5e1d2fe02876d69cd2c3a/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L1618

It's possible to work around this issue, as the callable still gets called, but it's a bit more awkward than being able to invoke:
```
resp = blob.stage_block('1', 'some body', cls=ResponseParser, logging_enable=True)
```

**Comment by kaerm** [comment]
@timuralp thanks for reporting this! //cc: @rakshith91 @mayurid

**Comment by rakshith91** [comment]
@timuralp  Just to make sure you know, you can also pass a raw_response_hook to get the headers.

```
def callback(response):
            return response.http_response.headers

props = blob.stage_block(1, "asdsjghjfha", raw_response_hook=callback)
print(props)
```

**Comment by timuralp** [comment]
@rakshith91 this does not work for me. I tried the following on master:
```
client = BlobServiceClient.from_connection_string(
 'AccountName=devstoreaccount1;'
 'AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;'
 'BlobEndpoint=http://localhost:10081/devstoreaccount1')
cont_client = client.get_container_client('test')
blob_client = cont_client.get_blob_client('foo')
print(blob_client.stage_block(1, 'foo', raw_response_hook=lambda *args: args))
print(blob_client.stage_block(1, 'foo', cls=lambda *args: args))
```

This prints:
> `None`
> `None`

If I apply the patch in the related PR, I can get the returned value of calling `cls` back:
>  `(<azure.core.pipeline.transport._requests_basic.RequestsTransportResponse object at 0x7f7dfaf8a950>, None, {'Content-MD5': None, 'x-ms-client-request-id': None, 'x-ms-request-id': 'ca94302e-319e-45f8-956c-7dda6a73f166', 'x-ms-version': '2018-03-28', 'Date': datetime.datetime(2019, 11, 15, 19, 16, 43, tzinfo=datetime.timezone.utc), 'x-ms-content-crc64': None, 'x-ms-request-server-encrypted': True, 'x-ms-encryption-key-sha256': None, 'x-ms-error-code': None})`

I'm unsure how your example works on master given these lines: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_block_blob_operations.py#L320-L332 and `BlobClient` calls this directly, as far as I can tell: `self._client.block_blob.stage_block(**options)`. It looks like the generated `BlockBlobOperations` will either return `None` or the result of calling `cls()`? What am I missing?

**Comment by rakshith91** [comment]
This works for me in the master branch. Could you try this? Also, I'd like to ask, is there a specific reason you need the `x-ms-content-crc64`? We'd ideally want to resolve it without  a breaking change.(adding return on stage_block is technically breaking :) )
```
headers = {}
blob.stage_block(1, "asdsjghjfha", raw_response_hook=lambda args: headers.update(args.http_response.headers))
print(headers)
```

**Comment by rakshith91** [comment]
To answer the second part of your question, raw_response_hook is passed to a [custom hook policy](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/_custom_hook.py#L32). So if you want to inspect the response ( even if it is not "returned" ) without actually modifying it, using the response_hook is the ideal.

**Comment by timuralp** [comment]
@rakshith91 The second example works. I find it quite awkward, however, especially when the returned value is plumbed almost all the way out. I don't know how common other folks will find themselves using this, but it's probably an indicator that the API is not as useful as it could be. I'd also compare this unfavorably with boto3, where all HTTP information is returned for every request.

> Also, I'd like to ask, is there a specific reason you need the x-ms-content-crc64?

For our customers we'd like to provide some assurance that the bytes written down by the storage service match what was submitted. With AWS S3, Google Cloud Storage, and OpenStack Swift, we can rely on the ETag. With Azure Blob, the best we can do is compare the x-ms-content-crc64 header value with the one we compute while streaming the upload (I'm glad the header was recently added!).

> We'd ideally want to resolve it without a breaking change.(adding return on stage_block is technically breaking :) )

I suspect there aren't many callers that rely on the return value being `None`. I'm also surprised about the hesitation given how much churn was introduced between versions 2.x and 12.x. Surely another small API change is not the end of the world? :P

> To answer the second part of your question, raw_response_hook is passed to a custom hook policy.

Thanks for the pointer! However, I was wondering how your example above produced the output it did. Can you explain how it worked? `props` is never assigned except as the return value, so I am lost how you produced the output you posted.
```
def callback(response):
            return response.http_response.headers

props = blob.stage_block(1, "asdsjghjfha", raw_response_hook=callback)
print(props)
```

**Comment by lmazuel** [comment]
Hi @timuralp !

I'm sorry to hear that you think this API is "is not as useful as it could be." :(. Let's try to see if we can make it better! :)

So let me reverse the question for you a bit, what would be in your ideal world the best API here? Giving you the headers is one possibility indeed, but that still put on you using that value to verify. Would it be better to just have a parameter "check_crc64=True" that does all magic for you? Something even better? Could you write a complete scenario code assuming you have full flexibility of the perfect usage of this API?

I think we didn't explain ourselves correctly here, we don't have any "hesitation", as you said we broke it at lot between 2.x and 12.x, we actually want to get further and understand what is the BEST fix, and not only the ok fix ;). So if we have hesitation here, it's to make something not as useful as it could be ;)

Feel free to share your feelings here (and dream big :)). You can also contact me directly by email I'll be glad to brainstorm something (my email is my <githublias>@microsoft.com).

Thank you!

**Comment by timuralp** [comment]
Hi @lmazuel, 
Thanks for jumping in! I'll tackle the smaller items first and then leave my thoughts on the broader topic.

> I'm sorry to hear that you think this API is "is not as useful as it could be."
Possibly a poor choice of words on my part, but I was trying to highlight that (at least to me) turning a call to upload a block into
```
headers = {}
blob_client.stage_block(<id>, <content>, raw_response_callback=lambda resp: headers.update(resp.http_response.headers))
```
feels quite inelegant. Having the callback seems helpful, but only for cases where one wants to pass a callback to mutate the response in some way before it is processed by the rest of the library. I've seen other libraries expose such mechanisms, but I have never seen that be the suggested way to obtain response details. 

> So let me reverse the question for you a bit, what would be in your ideal world the best API here?

I've found that there are different kind of users of the blobstore frameworks over the years. I'm sure many folks were/are looking to perform higher-level tasks, like "upload a file" or "upload a stream" and it looks like the current Azure Blob SDK works pretty well for that. It can chunk the uploads/downloads and take advantage of parallel requests. These callers probably could be satisfied with the library computing the CRC64 on a streaming upload and comparing it with the Azure Blob response. 

The other kinds of use cases that I'm interested in are described in detail [here](https://www.swiftstack.com/product/1space). Briefly, we're working on providing a way to "stitch" Azure Blob with OpenStack Swift and other blob stores, allowing our customers to transparently move data into Azure. While doing so, we want to be able to provide certain guarantees about the data integrity (hence the x-ms-content-crc64 value), as well as have lower level control to make specific individual requests to ensure we correctly translate objects between the different storage interfaces. I hope to find a way to satisfy both of these kind of approaches to using the SDK.

Happy to chat more about this and involve our PM if that would be useful. If that would be helpful, feel free to reach out timuralp@swiftstack.com. In the more immediate future, though, I don't know what the best path forward is. I suspect I will find other instances where I'd like to be able to examine the Azure Blob responses directly, but I'm not sure how it matches with the existing road map for this SDK.

**Comment by rakshith91** [comment]
Hi @timuralp 
We have been discussing this issue. We think [returning response headers by default](https://github.com/Azure/azure-sdk-for-python/pull/8589#discussion_r345929979) will be the best way to move forward. Will this be something you'd expect? 
If it's fine, would you mind making the change on your PR? Again, we want to make sure we have the "right" solution to this, so feel free to let us know if you have concerns with this approach. :) Thanks again!

cc: @lmazuel

**Comment by timuralp** [comment]
Hey @rakshith91,

Thanks for thinking through this issue! To make sure we're on the same page, are you suggesting both externalizing the response and setting a default value for the `cls` keyword argument? I'm happy to amend the request to do that.

Since this is something you're thinking about internally and know the framework better than I do, do you think this is something that will pop up in other places? Here are a couple of things I thought about:
1. `get_blob_properties()` doesn't return the raw header response, but wraps the response. I feel like there would be some inconsistency in the types returned now. I'm unsure that the wrapper over the dictionary response adds a lot of value, but I might be missing the expected use cases. It feels to me that it could (should?) return a similar type
2. What about other methods that currently don't return responses, like `delete_blob()` (the interesting header there might be `x-ms-delete-type-permanent`)?

**Comment by rakshith91** [comment]
@timuralp 


> are you suggesting both externalizing the response and setting a default value for the `cls` keyword argument

Yes. We'll return these headers by default.



> 1. `get_blob_properties()` doesn't return the raw header response, but wraps the response

I'm glad to inspect it further and see if there's something that's missing by not returning the headers directly.



> 2\. What about other methods that currently don't return responses, like `delete_blob()`

This is definitely an interesting case. It would be great if you can create a separate issue for it.

**Comment by rakshith91** [comment]
@timuralp Are you planning to work on your PR. Feel free to let us know if you want us to work on it. Totally your call :)

**Comment by timuralp** [comment]
I'm happy to address it, but have been busy at work lately. I hope to address your comments this weekend. For the time being, I've sidestepped this problem by using the internal generated code, which has lowered the priority of addressing this.
