### ISSUE TITLE
Possible to support credentials from azure cli in DefaultAzureCredential?

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-sdk-for-python#8566]
I noticed in [SharedTokenCacheCredentials](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/azure/identity/_credentials/user.py#L135-L147) it only works on windows. 

I used to use [get_azure_cli_credentials](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-common/azure/common/credentials.py#L31) and does the cli have a shared token cache across platforms? 

It'd be great for `DefaultAzureCredential` to work using the logged in azure cli account when developing locally and then no code changes needed when deploying to Azure with managed identity.

**Comment by lmazuel** [comment]
Hi @damienpontifex 
We definitely wants to address this scenario, we'll discuss with the team how to do it correctly :)

**Comment by damienpontifex** [comment]
Thanks @lmazuel I'd be happy to contribute a change if there's guidance on the best way to do this.

**Comment by lmazuel** [comment]
Thanks @damienpontifex , we are working on the design , I don't think this issue is the best one for contribution, but I will update this thread as soon as we have a candidate PR.

**Comment by jongio** [comment]
FYI - We are still discussing this internally and should have an update soon.

**Comment by carlosotgz** [comment]
@jongio Hi. Is there any update for this issue? :)

**Comment by jongio** [comment]
Thanks for checking in.  We are discussing when to do a preview of this.  Hopefully within the next couple of weeks, but we still have some remaining design to flesh out.  I'll earmark this to update when we have something ready.

@schaabs

**Comment by carlosotgz** [comment]
Hi :) Any luck with this issue? It would be really nice to be able to use play with the SDK without having to create additional service accounts :(

**Comment by chlowell** [comment]
The first preview of `DefaultAzureCredential` integrating the Azure CLI is available now in [azure-identity 1.4.0b1](https://pypi.org/project/azure-identity/1.4.0b1/). In this preview, `DefaultAzureCredential` will attempt to authenticate with the identity you've set up with `az login`, with no configuration required in your code. Please try it out and let us know what you think.

**Comment by damienpontifex** [comment]
Thanks @chlowell I did some initial testing with some KeyVault code I have and seems good so far :) 

Any idea when these credentials will also make their way to the python azure management libraries? e.g. DNS

**Comment by chlowell** [comment]
Adopting these credentials in management libraries is tracked by #9310. I don't know the timeline (@zikalino may have more details) but a [comment](https://github.com/Azure/azure-sdk-for-python/issues/9310#issuecomment-606893344) on that issue links to an adapter you can try in the meantime.

**Comment by jongio** [comment]
@damienpontifex - Just so you know the python version of AzureIdentityCredentialWrapper has been added to Azure Identity Extensions https://github.com/jongio/azidext#python 

We are still a ways from officially supporting Azure Identity in Mgmt plane libraries, but it is something we are actively working on.  For now, we must use adapters.

**Comment by chlowell** [comment]
Thanks for opening this issue. I'm closing it now because the current preview version of azure-identity has this support. Please open another issue if you encounter problems using it.
