### ISSUE TITLE
LUIS:  add_composite_entity method was dropped from _model_operations.py

### ISSUE THREAD

**Issue by ddu1** [Azure/azure-sdk-for-python#8576]
Hi, 

Notice that the method `add_composite_entity` does no longer exist in azure-cognitiveservices-language-luis:0.5.0 .   (it was available in 0.4.0)

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/operations/_model_operations.py

Was it intentional? 

Thanks!

**Comment by kayousef** [comment]
Hi @ddu1 

Yes, Composite Entities are not being retired and replaced with [ML Entities](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/reference-entity-machine-learned-entity?tabs=V3) that support all features of both Simple Entities and Composite Entities as well. 

For more details on how to migrate your existing model if needed, please refer to the documentation [here](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/migrate-from-composite-entity).
