### ISSUE TITLE
Onboard Nov previews onto docs.microsoft.com

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-python#8611]
Keeping in mind examples rendering
- [ ] https://pypi.org/project/azure-appconfiguration/1.0.0b5
- [ ] https://pypi.org/project/azure-cosmos/4.0.0b5
- [ ] https://pypi.org/project/azure-eventhub/5.0.0b5
- [ ] https://pypi.org/project/azure-eventhub-checkpointstoreblob/1.0.0b5
- [ ] https://pypi.org/project/azure-eventhub-checkpointstoreblob-aio/1.0.0b5
- [ ] https://pypi.org/project/azure-keyvault-certificates/4.0.0b5
- [ ] https://pypi.org/project/azure-storage-file-datalake/12.0.0b5
- [ ] https://pypi.org/project/azure-storage-file-share/12.0.0b5

**Comment by kaerm** [comment]
Also Adding Storage Datalake @scbedd 
Python Package: https://pypi.org/project/azure-storage-file-datalake/

**Comment by scbedd** [comment]
Progress on OPS CI Update:

Keeping in mind examples rendering
- [ ] https://pypi.org/project/azure-appconfiguration/1.0.0b5
- [ ] https://pypi.org/project/azure-cosmos/4.0.0b5
- [ ] https://pypi.org/project/azure-eventhub/5.0.0b5
- [ ] https://pypi.org/project/azure-eventhub-checkpointstoreblob/1.0.0b5
- [ ] https://pypi.org/project/azure-eventhub-checkpointstoreblob-aio/1.0.0b5
- [ ] https://pypi.org/project/azure-keyvault-certificates/4.0.0b5
- [ ] https://pypi.org/project/azure-storage-file-datalake/12.0.0b5
- [ ] https://pypi.org/project/azure-storage-file-share/12.0.0b5

**Comment by scbedd** [comment]
[PR for ToC Updated](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/579)

**Comment by scbedd** [comment]
Waiting on build. [Review Link.](https://review.docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python-preview&branch=smoke-test-preview)

**Comment by scbedd** [comment]
Review completed, looks good. [PR Here.](https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/646)

**Comment by scbedd** [comment]
Dealing with an issue where all content is being placed under an `Other` section. Investigating.

**Comment by scbedd** [comment]
There is madness with the ReferenceTOCUrl parameter in the openpublishing config. Building a fix.
