### ISSUE TITLE
RetryPolicy raises AttributeError while handling AzureError

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#8629]
When `RetryPolicy.send` handles an `AzureError`, it calls `RetryPolicy.increment`, passing the outgoing request as a response:
https://github.com/Azure/azure-sdk-for-python/blob/535f455abf9842ba9b5b0bc95b165fed91763fb6/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L359-L361

`RetryPolicy.increment` has an `else` block accessing `response.http_response`:
https://github.com/Azure/azure-sdk-for-python/blob/535f455abf9842ba9b5b0bc95b165fed91763fb6/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L313-L318

The request has no such attribute, so this code path raises `AttributeError`.

Repro:
```py
from azure.core.exceptions import AzureError
from azure.core.pipeline import Pipeline
from azure.core.pipeline.policies import HTTPPolicy, RetryPolicy
from azure.core.pipeline.transport import HttpRequest

class NaughtyPolicy(HTTPPolicy):
    def send(*args):
        raise AzureError('boo')

policies = [RetryPolicy(), NaughtyPolicy()]
pipeline = Pipeline(policies=policies, transport=None)
pipeline.run(HttpRequest('GET', url='https://foo.bar'))
```

**Comment by xiangyan99** [comment]
fixed
