### ISSUE TITLE
async operations with cosmos db

### ISSUE THREAD

**Issue by rajata07** [Azure/azure-sdk-for-python#8636]
As of now, the Python SDK doesn't support Async operations with the cosmos DB. From my perspective, this is a must-have feature.

**Comment by kaerm** [comment]
@rajata07 thanks for letting us know. Looping in my team //cc: @annatisch @mayurid

**Comment by yehoshuadimarsky** [comment]
I desperately would want this as well, kinda surprised it wasn't done yet considering the importance MSFT places on Cosmos. Anyway, count me in for this

**Comment by yehoshuadimarsky** [comment]
and why did @shurd remove the `Cosmos` label from this issue? Took me a while to find this, I was going to open a new one, would have been much easier if the `Cosmos` label was still on it

**Comment by shurd** [comment]
From my investigation, this is a change that the SDK team will make, not the Cosmos DB team. At the time, that label was making this appear in our backlog. I removed it from our backlog since we do not own that aspect.

**Comment by annatisch** [comment]
@shurd - please leave the service-name label in place and if you need to filter out service-team issues please use the `client` (SDK team) vs `Service Attention` (service team) labels.

On the other hand - doing a fully asynchronous query pipeline in the Cosmos SDK will need service-team input. :)

**Comment by bigdatamoore** [comment]
We also need this for our use case.

**Comment by scgbear** [comment]
<details>
<summary>Internal Tracking</summary>
CSEF370143
</details>

**Comment by ian-young-sydney** [comment]
I would expect this feature too.  Does the "Internal Tracking" number mean that this is being worked on?

**Comment by southpolesteve** [comment]
Internal tracking number does not mean it is being worked on

**Comment by bjoern-meier-by** [comment]
We are currently evaluating different databases/storage solutions including CosmosDB. The main usage would be from Python code which was explicitly written with async support. Sadly we do not have the work force to contribute async support here :( and adding sync calls for CosmosDB might then be a disqualification. Can you give an update if this will make it onto your roadmap?

**Comment by southpolesteve** [comment]
Unfortunately this work is still not scheduled. Since this is a feature request, user voice would be a better forum for this issue https://feedback.azure.com/forums/263030-azure-cosmos-db.

In the meantime, I you can always use the REST API directly: https://docs.microsoft.com/en-us/rest/api/cosmos-db/ Closing this issue for now.

**Comment by databasedav** [comment]
please vote here! https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/41539546-async-python-support

**Comment by Inrixia** [comment]
Any update on this?
