### ISSUE TITLE
Getting VM Sizes with Their Costs

### ISSUE THREAD

**Issue by aytekinar** [Azure/azure-sdk-for-python#8637]
I have the following environment:
```
~> pip list | grep azure
azure-cli-core         2.0.76   
azure-cli-nspkg        3.0.4    
azure-cli-telemetry    1.0.4    
azure-common           1.1.23   
azure-mgmt-compute     9.0.0    
azure-mgmt-monitor     0.7.0    
azure-mgmt-resource    4.0.0    
azure-nspkg            3.0.2    
msrestazure            0.6.2    
```
When I try to use `list` from `ComputeManagementClient.virtual_machine_sizes`, I see in the doctring that the method is deprecated and I should use "Resources Skus" instead, pointing to its [REST API](https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list).

When I change the command to `ComputeManagement.resource_skus.list`, I see that its signature is different (i.e., `virtual_machine_sizes.list` expects `location` as the first parameter whereas `resource_skus.list` expects `filter`). I have two problems:

1. How can I use the new API to fetch the sizes in a given `location`? The new API returns an iterable with objects having a `locations` field that expects/spits out a list of strings, but I could not get the new API to work using `filter`.
2. The new API's returned objects have their `costs` field set to `None`. Is there any way to get the costs (also related to Azure/azure-cli#7356)?

**Comment by Drewm3** [comment]
Hi @aytekinar, 

For #1, please use the following example for getting the SKUs list for a specific region using the filter mechanism: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-04-01/examples/ListAvailableResourceSkusForARegion.json 

For #2, the end-to-end cost support is not available yet. This section is reserved for future use, but we do not have an ETA for when it will be available. The mechanism to get pricing for the SKU is not consistent across the various channels in which Azure can be purchased, and that consistency needs to be in place before we can connect to this consistent pricing system via the SKUs API.

Please let me know if this answers your questions.

**Comment by Drewm3** [comment]
Closing this now due to no other questions.

**Comment by aktiver** [comment]
Has cost api's ever been implemented?

**Comment by Drewm3** [comment]
The cost API is available, but it is not directly integrated into the SKUs API. The primary issue is that there are multiple price points for each ARM VM SKU. Here is a summary of the retail pricing API: https://learn.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices.

An example of a query for D64s_v5 in West US excluding reservations would be:
```
https://prices.azure.com/api/retail/prices?$filter=serviceName eq 'Virtual Machines' and armRegionName eq 'westus2' and armSkuName eq 'Standard_D64s_v5' and unitOfMeasure eq '1 Hour'
```
