### ISSUE TITLE
Version manipulation tools update documentation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#8638]
incrementing should: 
* add an entry to the appropriate changelog file

set version should: 
* update the version entry in the changelog file (i.e. from "1.2.3b1" to "1.2.3" in preparation for release) 

We should also come up with a strategy for updating documentation. Current documentation PyPI links seem to follow this standard: 
* If the package has a previous GA version whose major version is behind the current version: link directly to the current preview version 
* If the package has not previously released GA: link to the package, the version number is not necessary

- [x]  Update version format to use double quote
- [x]  add an entry to the appropriate changelog file
- [x]  update the version entry in the changelog file (i.e. from "1.2.3b1" to "1.2.3" in preparation for release) 
- [ ] link documention on PyPI properly

**Comment by praveenkuttappan** [comment]
Version increment should use " instead of ' to mention version

**Comment by danieljurek** [comment]
For the PyPI documentation piece of this: 

Update the "Package (PyPi)" link in the README.md 

Example with previous GA [here](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhub)... note the link directly points to the `5.0.0b6` version because if we did not point directly to that version a consumer of the README docs would land on the `1.3.3` version. 

Example with no previous GA: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-keys ... Note the PyPI link does not point to a version. 


Also, we should probably ensure that the spelling of `Package (PyPI)` is consistent everywhere because it is different between event hubs and key vault.
