### ISSUE TITLE
pin install azure sdk tools not working on python alpine image

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-sdk-for-python#8654]
Hi
this is my docker file and works file if i comment out azure-mgmt-resource .In fact if add any of azure tools like azure-mgmt-resource ,azure-mgmt-datalake-store, azure-datalake-store, azure-keyvault

it fails either if i add direct to command or requirements.txt with below error in azure pipeline

############
FROM python:alpine3.7
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
RUN pip install azure-mgmt-resource
CMD python ./index.py

ERRORS

Collecting cryptography>=1.1.0
  Downloading https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz (504kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:

  ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9wtipuu5/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9wtipuu5/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vvyjvhg5/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-w3ulg_1k/overlay --compile Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-w3ulg_1k/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
The command '/bin/sh -c pip install azure-mgmt-resource' returned a non-zero code: 1
##[error]The command '/bin/sh -c pip install azure-mgmt-resource' returned a non-zero code: 1
##[error]/usr/bin/docker failed with return code: 1

**Comment by johanste** [comment]
In order to install the cryptography package on Alpine, please follow the instructions outlined [here](https://cryptography.io/en/latest/installation/#alpine).

**Comment by johanste** [comment]
And to add some background info to my comment above, the Azure SDKs depend on the [cryptography package](https://pypi.org/project/cryptography/), which includes a binary extension. See https://stackoverflow.com/questions/50619166/docker-installing-python-cryptography-on-alpine-linux-distribution/51494672 for  more info on python binary extensions and the Alpine distro.
