### ISSUE TITLE
python sdks unusable due to mass instability and constant breaking changes

### ISSUE THREAD

**Issue by kapilt** [Azure/azure-sdk-for-python#8662]
we have an application that heavily uses the azure apis via the python sdks for the last few years, we've noticed that the apis break constantly with backwards incompatible changes, sometimes multiple times a week across the full dependency graph, and that breakage seems to be accelerating rather than stabilizing.   

Its unclear what the rationale here is for a library / sdk to be so unstable, or what the goal / roadmap is wrt to stability. As a long time python user, I can't say I've ever seen an sdk or library with this degree of breakage/churn, it feels very user hostile. We would really like to understand the rationale for it, and the intended manner sdk consumers are supposed to handle this.

Background Issue with several examples from the last two weeks  (though this has been a problem for years), https://github.com/cloud-custodian/cloud-custodian/issues/5017

**Comment by kaerm** [comment]
@kapilt thanks for the feedback. Adding my team to take a look at it //cc: @mayurid

**Comment by RodgeFu** [comment]
assign to @changlong-liu who is working on an improvement to reduce the breaking change of python SDK. @kapilt, thanks for reporting the issue and sorry for the troubles. Could you help to provide the packages you are using so that we can look into them and talk with service team to see how we can mitigate the issue. thanks.

**Comment by kapilt** [comment]
we're using the following packages, we've had to pin everything to avoid the breakage, and with a future plan to ditching most of our usage of the azure sdk in favor of building a new client thats runtime generated using msrest and openapi specs. the existing static generated sdk approach is less then usable for us, as it results in lots of bloat (hundreds of mbs of downloads for an install w/ extraneous bloat for py2 & py3) and we've had to deal with instability in the generated packages for years due to changes in the generator. comparing to other provider sdk implementations, its quite a poor end user experience.

```
azure-cli-core==2.16.0; python_full_version >= "3.6.0"
azure-cli-telemetry==1.0.6; python_full_version >= "3.6.0"
azure-common==1.1.26; python_full_version >= "3.6.0"
azure-core==1.9.0; python_full_version >= "3.6.0"
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.5.0; python_version >= "3" and python_version < "4"
azure-graphrbac==0.61.1
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.1.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-authorization==0.60.0
azure-mgmt-batch==7.0.0
azure-mgmt-cdn==4.0.0
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==8.3.0
azure-mgmt-core==1.2.1; python_full_version >= "3.6.0"
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==3.0.0
azure-mgmt-eventgrid==2.2.0
azure-mgmt-eventhub==3.1.0
azure-mgmt-hdinsight==1.7.0
azure-mgmt-iothub==0.10.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-logic==3.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-monitor==0.7.0
azure-mgmt-network==9.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==6.0.0
azure-mgmt-resource==6.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-sql==0.16.0
azure-mgmt-storage==7.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-web==0.44.0
azure-nspkg==3.0.2
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-queue==2.1.0
msrestazure==0.6.4; python_full_version >= "3.6.0"
```

**Comment by BigCat20196** [comment]
Close this issue, please feel free to reopen it if you have any questions.
