### ISSUE TITLE
AppConfiguration sample does not have a description

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#8667]
This sample:

https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/azure-app-configuration-data-library-python-samples/

Doesn’t have content after the first H1

Shows this in card:
 
![image](https://user-images.githubusercontent.com/2163001/68969681-6d664b80-079a-11ea-886f-c1599be3f735.png)

I reported the issue to the docs team.

In the meantime, let's add a description to the sample.

**Comment by jongio** [comment]
Please assign to me.  Thanks, Jon

**Comment by xiangyan99** [comment]
@jongio I think it is already fixed. Please double check.

**Comment by jongio** [comment]
Yes, closing.
