### ISSUE TITLE
KeyVault Samples do not include azure-key-vault product front-matter.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#8669]
The following samples:
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/azure-key-vault-keys-client-library-python-samples/

https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/azure-key-vault-secrets-client-library-python-samples/

Do not have the azure-key-vault front matter, therefore are not showing up in the samples browser when someone filters by Azure Key Vault.

Add the following to the front-matter.
```
products:
  - azure
  - azure-key-vault
```

**Comment by jongio** [comment]
Please assign to me, Thanks, Jon

**Comment by kaerm** [comment]
I submitted a PR for this yesterday - waiting for someone to review :

**Comment by jongio** [comment]
Okay, thanks. I missed that.  If they merge yours first then, mine should still auto-merge.

**Comment by lmazuel** [comment]
@jongio closing, since the PR @kaerm mentionned has been merged.
