### ISSUE TITLE
[EventHubs] Provide an linear(fixed) backoff option for retry

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#8670]
### Feature Wanted:

We need to add support for Fixed(Linear) retry backoff in EventHubs. EventHub needs to implement its own retry as it's based on amqp protocol so we can't simply reuse the azure-core which is http-based. However, the design of retry is almost the same.

Currently EH only supports `exponential` back off mode, and it takes three retry related key-word arguments when constructing the EventHubProducerClient/EventHubConsumerClient -- `retry_backoff_factor`, `retry_backoff_max`, `retry_total`.

As per azure-core: https://github.com/Azure/azure-sdk-for-python/blob/1ba7a753b47c9fb54636c40a82af26133f47821a/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L56-L85

### Action items:
1. Need to define the enum type `RetryMode` under `azure.eventhub` namespace -- `azure.eventhub.RetryMode`
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L52-L54
```
class RetryMode(str, Enum):
    Exponential = 'exponential'
    Fixed = 'fixed'
```
2. EventHubProducerClient/EventHubConsumerClient (and async) `constructors` and the helper method `from_connection_string` should take "retry_mode" as a key-word argument and the default value shall be `Exponential` (non-breaking change), see [configuration](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/azure/eventhub/_configuration.py) and [how the configuration could be used internally](https://github.com/Azure/azure-sdk-for-python/blob/1ba7a753b47c9fb54636c40a82af26133f47821a/sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py#L166).

3. Update the [def _backoff](
https://github.com/Azure/azure-sdk-for-python/blob/1ba7a753b47c9fb54636c40a82af26133f47821a/sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py#L238-L259) and [the async version](https://github.com/Azure/azure-sdk-for-python/blob/1ba7a753b47c9fb54636c40a82af26133f47821a/sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py#L157) to backoff according to the given retry mode.
4. Test and docstring

**Comment by pastine** [comment]
Is this still an issue? I would like to work on it if possible.

**Comment by Hanse00** [comment]
Can we get some more detail on this? I understand the concept of a backoff option, but if you intend for this to be a good first issue, the contributor will need a bit of background.

**Comment by jmonty42** [comment]
I see that there is a fixed option and an exponential option for retries. Would a linear option simply be adding the back_off value each time?

**Comment by yunhaoling** [comment]
hey @jmonty42 , thanks for your help. Fixed retry is equal to liner retry.

sorry about not mentioning any background knowledge before, and I just added more description in the context. Hope it would be clear to you know and feel free to ping me if you need more input.

and apologize to @Hanse00 as well, I truthfully forget the issue here, I wish you were still interested in getting it resolved😊

**Comment by Hanse00** [comment]
@yunhaoling Not a problem, I'm happy to have been able to highlight an issue that needed some help. The first step to allowing people to help us in open source, is making sure we give them the tools and information they need to help 😄 

I might be interested in taking a stab at this myself if nobody else does, I'll need to get around to it when I'm a little less busy at work.

**Comment by jmonty42** [comment]
@yunhaoling, alright, thanks for the clarification, I will close my PR since it doesn't address the issue now. I'll take a closer look at the updated requirements to see if I could take a crack at that.
