### ISSUE TITLE
Version bump tool reads exclusions from a .toml file in the same folder as setup.py

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#8697]
Right now we use heuristics (e.g. no `azure` folder near `setup.py`, `nspkg` in folder structure, `mgmt` in folder structure) to determine whether to skip the package version updating process. We should use properties in the .toml file (e.g. https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-common/sdk_packaging.toml) to determine how to target packages for version bumping.

**Comment by scbedd** [comment]
@danieljurek I think the default exclusion works fine. I don't want to mandate that every new management packages needs to remember to exclude the version bump in their `pyproject.toml`.

What do you think?

**Comment by danieljurek** [comment]
I'm fine with closing this... If it isn't broken, don't fix it.
