### ISSUE TITLE
[azure.mgmt.alertsmanagement] Operations resource not found

### ISSUE THREAD

**Issue by michal-demecki-profil-software** [Azure/azure-sdk-for-python#8706]
https://github.com/Azure/azure-sdk-for-python/blob/5ec0b1df94aea41fae1a5628715b63d0993573b9/sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_operations.py#L38

package: azure.mgmt.alertsmanagement
version: 2019-05-05-preview
error:
```
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidResourceType
Message: The resource type 'operations' could not be found in the namespace 'Microsoft.AlertsManagement' for api version '2019-05-05-preview'. The supported api-versions are '2017-11-15-privatepreview,2018-05-05-preview,2018-05-05'.
```

**Comment by yairgil** [comment]
Thank you for your feedback. The item is passed to our backlog for priority investigation and correction.
