### ISSUE TITLE
EnvironmentCredential.get_token raises "The required field 'scope' is missing" exception

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#8710]
The following code:
```
import os
from dotenv import load_dotenv
from azure.keyvault.secrets import SecretClient
from azure.identity import EnvironmentCredential, SharedTokenCacheCredential, ManagedIdentityCredential

credentials = [EnvironmentCredential(), SharedTokenCacheCredential()]
for credential in credentials:
    print(credential)
    try:
        try:
            credential.get_token()
            print("No error while calling get_token")
        except Exception as te:
            print("Error while calling get_token")
            print(te)
        
        client = SecretClient(os.environ["KV_VAULT"], credential)
        secret_bundle = client.get_secret("MySecret", "467c6d9609344d3899dc71743e6ac9a9")
        print("Getting secret from KeyVault:")
        print(secret_bundle.value)
        
    except Exception as e:
        print (e)
```

Will produce this:
```
<azure.identity._credentials.environment.EnvironmentCredential object at 0x0000012704DF4148>
Error while calling get_token
Unexpected response '{'error': 'invalid_request', 'error_description': "AADSTS90014: The required field 'scope' is missing.\r\nTrace ID: 59136a38-f18e-42be-af8b-afed4e422b00\r\nCorrelation ID: 59a55cb2-9106-4972-93ab-e99d36aedc2e\r\nTimestamp: 2019-11-19 14:15:34Z", 'error_codes': [90014], 'timestamp': '2019-11-19 14:15:34Z', 'trace_id': '59136a38-f18e-42be-af8b-afed4e422b00', 'correlation_id': '59a55cb2-9106-4972-93ab-e99d36aedc2e', 'error_uri': 'https://login.microsoftonline.com/error?code=90014'}'
Getting secret from KeyVault:
MySecretValue

<azure.identity._credentials.user.SharedTokenCacheCredential object at 0x0000012704E41088>
No error while calling get_token
Getting secret from KeyVault:
MySecretValue
```

1. EnvironmentCredential.get_token will throw "AADSTS90014: The required field 'scope' is missing' when get_token is called, but it works when using with KeyVaultClient
2. SharedTokenCacheCredential will NOT throw an error when get_token is called, and it will work with KeyVaultClient

I have seen in docs that get_token should not be called by applications, but often times we want to get accessTokens for use in other places, not just in the SDK objects, i.e. calling REST APIs.  

1. I suggest we allow users to use get_tokens and allow them to specify the scope as an SDK object would.  EnvironmentCredential(scope='') - if that is why this doesn't work.
2. If we do not allow users to call get_tokens, then the error message should indicate/help them figure out what to do next.  If you google that error message, it does not help them realize that they shouldn't call get_token and should only be passing the credential object to an SDK class.
3. It is odd that the behavior is different for EnvironmentCredential and SharedTokenCacheCredential.  I understand why, because we already have the cached token and therefore don't need to generate it.  But still odd to end user that it is inconsistent.

**Comment by jongio** [comment]
I discovered that get_tokens accepts a scope and adding a scope resolved the issue.

`credential.get_token('https://vault.azure.net/.default')`

Docs:
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.0.0/azure.identity.html#azure.identity.EnvironmentCredential.get_token

**Comment by jongio** [comment]
One other related thing I would like to discuss:

Why does EnvironmentCredential require scopes when calling get_token, but SharedTokenCacheCredential does not?

It's an inconsistent experience that we should tell the users about if we can't avoid it.

**Comment by chlowell** [comment]
It's not a difference in the credentials per se. In keeping with our preference across the SDK for deferring client request validation to services, these credentials send whatever they're given to Azure AD. `EnvironmentCredential` in this case uses the client credentials grant, for which AAD requires a scope. `SharedTokenCacheCredential` uses the refresh token grant, for which AAD has a default scope.

**Comment by jongio** [comment]
Thanks.  Do you know off hand what the base uri is for their default scope?  I can dig it up if you don't

**Comment by chlowell** [comment]
For my token it's `https://graph.windows.net`.

**Comment by jongio** [comment]
Okay, Thanks.  I'll close this.
