### ISSUE TITLE
Service Bus: getting empty batch of messages regardless of the Service Bus Topic beeing full

### ISSUE THREAD

**Issue by Indy2222** [Azure/azure-sdk-for-python#8711]
We have a Service Bus Topic with one subscription. There is tens of thousands of messages in the subscription (see the screenshot from Azure Portal). We try to read messages from the subscription with the following code sample, what happens is that we get ~3 non-empty message batches and then all other batches are empty. The same thing happens after each restart to the program. We are using Service Bus of version `0.50.1` and uamqp of version `1.2.3` (installed as Service Bus dependency). 

![Untitled](https://user-images.githubusercontent.com/1902016/69155882-d4f60100-0ae2-11ea-99a7-b457239c4c49.png)

```python
from azure.servicebus.aio import SubscriptionClient
...
client = SubscriptionClient.from_connection_string(connection_string, subscription, loop=loop)
receiver = client.get_receiver(prefetch=0)

while True:
    # Here we get 3 non-empty batches and than start receiving only empty batches.
    batch = receiver.fetch_next(max_batch_size=1, timeout=10)
```

**Comment by kaerm** [comment]
@Indy2222 thanks for reporting this, routing it for the right team to take a look at this //cc: @annatisch

**Comment by Indy2222** [comment]
Is there any progress on the issue?

**Comment by KieranBrantnerMagee** [comment]
Hey Indy, thanks for your patience as we investigate this, and for the detail in your specification.

Given the version of UAMQP as well, I must admit this reminds me of [an issue we're currently mitigating](https://github.com/Azure/azure-sdk-for-python/issues/9017).

Is there any chance the message payloads you're sending are large? (50k+)

And a final "typical debugging question"  just in case, did this start from the get-go, or at a point in time/version upgrade?

**Comment by Indy2222** [comment]
> Given the version of UAMQP as well, I must admit this reminds me of an issue we're currently mitigating.
>
> Is there any chance the message payloads you're sending are large? (50k+)

I think that the messages were large so this looks like a possible explanation.

> And a final "typical debugging question" just in case, did this start from the get-go, or at a point in time/version upgrade?

We are using the library on several projects and having the issue only on one project. This could be caused both by version difference and by the fact that the other projects are not receiving as large messages.

**Comment by KieranBrantnerMagee** [comment]
Just wanted to follow up on this, a new SB release went out prior to the holidays, (0.50.2) that contains the aforementioned fixes.

Feel free to let us know if this addresses the issue at hand, don't hesitate to ping if any surprises/clarification/further questions, and thanks as always for your patience.  (I'll wait a bit to close this in case anything is needed)
