### ISSUE TITLE
Make README and CHANGELOG consistent across the repo

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-python#8738]
As an effort to make this repo self-consistent as well as consistent across our different languages we are going to update the README files to be README.md and any HISOTORY/CHANGELOG files to CHANGELOG.md. As part of this effort we may also need to move from `.rst` to `.md` file formatting if they are still using `.rst`.

The work breakdown looks something like:
- [ ] Update all data-plane libraries README files to README.md, including updates to setup.py
- [ ] Update all data-plane libraries HISTORY.md to CHANGELOG.md, including updates to setup.py
- [ ] Update all mgmt libraries README files to README.md, including updates to setup.py
- [ ] Update all mgmt libraries HISTORY.md to CHANGELOG.md, including updates to setup.py
- [ ] Update the PR bot to output MD files instead of RST files.

**Comment by danieljurek** [comment]
Libraries that are known to be generated from my conversation w/ @lmazuel: 

- Application Insights
- Cognitive Services
- Service Management Legacy should be excluded from EngSys work (don't have notes on whether it's generated or not) 
- Event Grid
- Graphrback 
- Log Analytics
 - Service Fabric

**Comment by lmazuel** [comment]
Checked @chidozieononiwu and it's closable
