### ISSUE TITLE
[event-hubs] checkpoint-blob-store should use all lowercase naming 

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-python#8745]
The checkpoint-blob-store, being a cross-language component, needs to use the same casing for the metadata properties all implementations. 

To eliminate ambiguity we've all gone lowercase (at this point). 

(original issue)
https://github.com/azure/azure-sdk-for-js/issues/6107

**Comment by annatisch** [comment]
Thanks - but we're tracking an issue here: #8535

**Comment by richardpark-msft** [comment]
Oof, sorry about that. Should have searched first.
