### ISSUE TITLE
Migrate Existing AzureML Release Pipelines to GitHub

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#8754]
Currently these exist as designer builds. We need to take advantage of the additional support outlined in #8561, #8520, #8521, #8522 and:

- Evaluate the existing design release pipeline for anything we missed in the above feature support
- Add the steps to unified pipelines
- Integration test the whole

**Comment by kurtzeborn** [comment]
Pretty sure this isn't needed any more.  We'll Open a new issue if it is.
