### ISSUE TITLE
Enable Customer provided storage Accounts for the tests.

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#8770]
If the user is using the Storage Emulator which has no subscription, resource group, etc. there is no way for them to run the test. 
Even if they have a subscription, only the owner could add role assignment for the service principal which subsequently creates resources, so it’s not very friendly for those who are not subscription owners.
In addition, the current behavior drastically slows down the development speed for developers in that running a single test takes nearly 30 seconds.
 
So it would be nice if there is a CONNECTION_STRING override in the “settings” file, so that if the CONNECTION_STRING value is not empty, ServicePrincipalCredential won’t be required and resource group won’t be created.
User defined account url could be parsed from the connection string(eg. BlobEndpoint=https://xyzw.blob.qw1.azure-test.net is the self-defined account url) if present
The SDK have support for parse_connection_str, so we can get a BlobServiceClient/ContainerClinet/BlobClinet by calling from_connection_str and get the client instance properties eg. account_url from there.

**Comment by xiafu-msft** [comment]
Is there any plan about modifying devtool for this issue?

**Comment by tasherif-msft** [comment]
There has been no updates to the devtools on this. I will proceed to close this issue.
