### ISSUE TITLE
API reference for SasPermission objects list incorrect operations.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#8784]
For example, the below is for BlobSasPermissions and lists "read, write, delete, list", but the correct permission options for BlobSasPermissions is "read, create, write, add, delete".

```
permission
str or BlobSasPermissions
The permissions associated with the shared access signature. The user is restricted to operations allowed by the permissions. Permissions must be ordered read, write, delete, list. Required unless an id is given referencing a stored access policy which contains this field. This field must be omitted if it has been specified in an associated stored access policy.

default value: None
```

Scrub all doc strings to ensure they list the correct permission options per SasPermission object.

**Comment by jongio** [comment]
Please assign to me.

**Comment by lmazuel** [comment]
Initial PR from @jongio here: https://github.com/Azure/azure-sdk-for-python/pull/8793
Closed since Storage team preferred to restart the fix from scratch, but could be used as inspiration for the fix (maybe even chrry-pick commits from it).

**Comment by jalauzon-msft** [comment]
This has been addressed in a recent PR to add missing SAS parameters. The doc string now just includes the permission letter for brevity but should include all possible options as well as proper order. Example:
https://github.com/Azure/azure-sdk-for-python/blob/b6217931d29f98abece37f9142470bbf2bb179e8/sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py#L530
