### ISSUE TITLE
[Storage]Add all Missing SAS Permissions

### ISSUE THREAD

**Issue by xiafu-msft** [Azure/azure-sdk-for-python#8799]
We have some missing sas permissions for container
check sas for blob, queue and file(fileshare and file datalake) to make sure all permissions are provided in sdk.
https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-directory-container-or-blob

**Comment by rakshith91** [comment]
IS this the same as #8784

**Comment by xiafu-msft** [comment]
Hi @rakshith91 

They are not the same. 8784 is (partially)updating the doc for generate_*_sas() operation.
This issue is to add missing permissions for *SasPermissions classes.
For example: [ContainerSasPermissions](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py#L902-L933) is missing **create** and **add** permission currently according to [rest doc](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-container). 

We should check all *SasPermissions classs for blob, file, queue, datalake and update all of them. 
Also we should update the doc for generate_*_sas() operation.

**Comment by jongio** [comment]
Is this a manual error or something we need to bubble up to autorest?  @johanste

**Comment by xiafu-msft** [comment]
hi @jongio 

Johan is OOF now.
It’s a manually error, not related to autorest I think.

**Comment by jalauzon-msft** [comment]
Re-opening this issue as the PR is not yet merged. Will use this to track adding all missing SAS parameters.
