### ISSUE TITLE
[EventHubs] Distributed tracing with OpenTelemtery: wrong diagnostics-id is added to the message

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#8810]
EventHubs trace_message:
-	It only [starts span, but does not make it current](https://github.com/Azure/azure-sdk-for-python/blob/de1013dd883cd2406ea02846124aafe3fa06224d/sdk/eventhub/azure-eventhubs/azure/eventhub/common.py#L123)
-	But when we generate diagnostic-id, it is actually created from [current span](https://github.com/open-telemetry/opentelemetry-python/blob/077a08e36f48f197b85df7c628f393fb8888bab5/opentelemetry-api/src/opentelemetry/propagators/__init__.py#L67), ignoring span instance

As a result, diagnostic-id carries parent (if any) context, rather than message span context.

**Comment by lmazuel** [comment]
I'll make this this is correct beofre merging https://github.com/Azure/azure-sdk-for-python/pull/7703, thanks!

**Comment by lmazuel** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-python/pull/7624/
