### ISSUE TITLE
AzureBlob: Unable to set blob metadata (x-ms-meta-* headers) when committing a block list

### ISSUE THREAD

**Issue by timuralp** [Azure/azure-sdk-for-python#8833]
It is currently impossible to set blob metadata when calling `commit_block_list()`. The `_commit_block_list_options()` method does not pass the `metadata` argument: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L1755-L1813. The metadata headers are inserted into the `headers` variable with a call to `add_metadata_headers`, but the `headers` variable is not used again in this method.

This is not contained to the above problem. There is a following issue in the generated code (`_generated.operations._block_blob_operations.BlockBlobOperations`): https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_block_blob_operations.py#L610-L611. The following lines produce a header like `'x-ms-meta': "{'foo': 'foo'}"`, whereas it should be producing: `'x-ms-meta-foo': 'foo'"`. The fixed up code should look something like:
```
         if metadata is not None:
             for k, v in metadata.items():
                 header_parameters['x-ms-meta-{}'.format(k)] =\
                    self._serialize.header("metadata", v, 'str')
```

This same issue exists in the `upload` method: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_block_blob_operations.py#L159-L160

While fixing this, it might be worthwhile to check other occurrences of handling the `x-ms-meta-` headers.

I used the following script to check the submitted headers against the Azurite emulator. I verified after fixing the issue in the generated code that the metadata headers are passed correctly and set on the objects as expected.
```
from azure.core.exceptions import ResourceNotFoundError
from azure.storage.blob import BlobServiceClient, BlobBlock, BlockState
from azure.storage.blob._generated.models import BlockLookupList
import base64
import logging


logger = logging.getLogger('azure.storage.blob')
logger.setLevel('DEBUG')
logger.addHandler(logging.StreamHandler())
metadata = {'foo': 'foo'}
container = 'test-meta'
blob = 'blob-with-meta'
connection_string = 'AccountName=devstoreaccount1;'\
'AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1'\
'OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KB'\
'HBeksoGMGw==;BlobEndpoint=http://localhost:10081/devstoreaccount1'

client = BlobServiceClient.from_connection_string(
    connection_string, logging_enable=True)
cont_client = client.get_container_client(container)
try:
    cont_client.get_container_properties()
except ResourceNotFoundError:
    cont_client.create_container()

blob_client = cont_client.get_blob_client(blob)
blob_client.stage_block(1, 'content')
blob_client.commit_block_list([BlobBlock(1, BlockState.Latest)],
                              metadata=metadata)
print(blob_client.get_blob_properties().metadata)

block_list = BlockLookupList(committed=[base64.b64encode(b'1').decode()])
blob_client._client.block_blob.commit_block_list(block_list, metadata=metadata)
print(blob_client.get_blob_properties().metadata)
```

**Comment by kaerm** [comment]
@timuralp thanks for reporting this, someone from our team will look into this //cc: @mayurid @rakshith91

**Comment by timuralp** [comment]
My workaround is to pass a `raw_request_hook` and set the appropriate headers that way. Looks like the existing unit tests don't actually verify that the expected headers are submitted in the request and with the canned response, this behavior is not caught.

**Comment by rakshith91** [comment]
@timuralp  Thanks for reporting. Looking into this now,

**Comment by timuralp** [comment]
@rakshith91 the same issue in the generated code exists for `set_blob_metadata()` (https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_blob_operations.py#L1229-L1230).

**Comment by xiafu-msft** [comment]
Hi @timuralp 

Thanks for helping investigate the problem!
Absolutely it's a bug, I will post a commit to fix it in a sec

**Comment by timuralp** [comment]
@xiafu-msft great -- thanks for looking into it! Makes sense -- I missed the transformation in `_set_blob_metadata_options`. This is a pretty confusing code base. When would these lines in the generated code ever make sense?
```
if metadata is not None:
        header_parameters['x-ms-meta'] = self._serialize.header("metadata", metadata, 'str')
```
It seems like that could be removed, as it will always be wrong?

**Comment by xiafu-msft** [comment]
Hi @timuralp 

That's a good question. We could modify the code base to serialize the metadata in _set_blob_metadata_options() and other *_options() places later, but I don't think we can delete metadata or modify it in _blob_operations.py because *_operations.py files are all generated by a swagger which is shared accross all sdks.

Sorry about the confusion!

**Comment by zezha-msft** [comment]
Looks like this has been fixed and released.
