### ISSUE TITLE
Wrong Validation in SelfDependencyTumblingWindowTriggerReference class offset attribute

### ISSUE THREAD

**Issue by daguito81** [Azure/azure-sdk-for-python#8846]
according to the python file the validation pattern is :
'pattern': r'((\d+)\.)?(\d\d):(60|([0-5][0-9])):(60|([0-5][0-9]))'
But according to the docs at https://docs.microsoft.com/en-us/azure/data-factory/tumbling-window-trigger-dependency
if using Self Dependency of Tumbling trigger, the offset needs to be negative. But the pattern does not allow for -0.01:00:00 as it doesnt have '-?' at the beginning. 
Testing the following JSON via Powershell worked so the offset can be a negative number in this case:
```
"dependsOn": [
                {
                    "type": "SelfDependencyTumblingWindowTriggerReference",
                    "offset": "-0.01:00:00"
                }
            ]
```

Whenever we try to use a non negative offset we get this error:
![image](https://user-images.githubusercontent.com/14969458/69580264-8362e000-0fd4-11ea-9750-9da7b4626541.png)

So would it make sense for the validation pattern to change and have the possibility of a negative before the offset.
Something like this maybe?
`r'-?((\d+)\.)?(\d\d):(60|([0-5][0-9])):(60|([0-5][0-9]))'`
I'm not that good at RegEx so maybe it can be improved

**Comment by spagarwa** [comment]
sent the PR for Fix

**Comment by spagarwa** [comment]
The work is complete
