### ISSUE TITLE
Onboard december releases on docs.microsoft.com

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-python#8853]
- [ ] Onboard the following packages on docs.microsoft.com
**Latest:**
azure-keyvault-secrets 4.0.0
azure-keyvault-keys 4.0.0
azure-storage-file-share 12.0.0
azure-storage-blob 12.0.0
azure-storage-queue 12.0.0
azure-core 1.1.0
azure-identity 1.1.0
**Preview:**
azure-keyvault-certificates 4.0.0b6
azure-storage-file-datalake 12.0.0b6
azure-eventhub-checkpointstoreblob 1.0.0b6
azure-eventhub 5.0.0b6
azure-cosmos 4.0.0b6
azure-appconfiguration 1.0.0b6
**Legacy:**
azure-storage-file 2.1.0

- [ ] Remove following packages from preview:
azure-storage-file-share 12.0.0b5
azure-storage-file 12.0.0b4

@mayurid to confirm version numbers

**Comment by scbedd** [comment]
Updated version numbers after checking pypi. Moving on to updating CI.

**Latest:**
- [ ] azure-keyvault-secrets==4.0.0
- [ ] azure-keyvault-keys==4.0.0
- [ ] azure-storage-file-share==12.0.0
- [ ] azure-storage-blob==12.1.0
- [ ] azure-storage-queue==12.1.0
- [ ] azure-core==1.1.1
- [ ] azure-identity==1.1.0

**Preview:**
- [ ] azure-keyvault-certificates==4.0.0b6
- [ ] azure-storage-file-datalake==12.0.0b6
- [ ] azure-eventhub-checkpointstoreblob==1.0.0b6
- [ ] azure-eventhub-checkpointstoreblob-aio==1.0.0b6
- [ ] azure-eventhub==5.0.0b6
- [ ] azure-cosmos==4.0.0b6
- [ ] azure-appconfiguration==1.0.0b6

**Legacy:**
- [ ] azure-storage-file==2.1.0

Remove following packages from preview:
- [ ] azure-storage-file-share==12.0.0b5


I did not remove `azure-storage-file==12.0.0b4` from the preview packages list, as it is still in preview and has not released a GA version.

@mayurid to confirm version numbers
