### ISSUE TITLE
should specify the compatible version of 'requests' package

### ISSUE THREAD

**Issue by gossion** [Azure/azure-sdk-for-python#889]
pip package of 'reqeusts' has latest verion [2.12.1](https://pypi.python.org/pypi/requests/2.12.1) released, which will be installed by `pip install azure`, but I got an error in my environment like this:
```
Traceback (most recent call last):
  File "setup_env.py", line 197, in <module>
    main()
  File "setup_env.py", line 188, in main
    prepare_storage(settings)
  File "setup_env.py", line 23, in prepare_storage
    blob_service.create_container('bosh')
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blob/baseblobservice.py", line 543, in create_container
    self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 137, in _perform_request
    raise AzureException('{}: {}'.format(ex.__class__.__name__, ex.args[0]))
azure.common.AzureException: AttributeError: 'X509' object has no attribute '_x509'  
```
By changing to 'reqeuests' v2.11.1, the error is gone. So my conclusion is that requests v2.12.1 is not compatible with azure sdk. 
From [requirements.txt](https://github.com/Azure/azure-sdk-for-python/blob/master/requirements.txt), it requires 'requests'  but it should also specified a compatible version of it there.

**Comment by lmazuel** [comment]
Hi @gossion 
Thanks for your feedback! You stacktrace is from the `azure-storage` package, which is managed by the Storage team directly (not the general Python team). Could you create your issue on the storage tracker here? https://github.com/Azure/azure-storage-python. Only them can fix their part. Please cite this issue as well.

I will check all the SDK hosted here, and keep your issue opened till I confirm (or not) that everything is working for the packages we manage.

**Comment by lmazuel** [comment]
Seems to be a requests problem: https://github.com/kennethreitz/requests/issues/3701

**Comment by gossion** [comment]
Hi @lmazuel 
Thanks for reply. Yes, the traceback is from `azure-storage`, but `requests` and `azure-storage` packages are installed by `pip install azure`. 

From this [requirements.txt](https://github.com/Azure/azure-sdk-for-python/blob/master/requirements.txt) file, I do see that `requests` does not have a compatible version defined. I am not sure if this `requirements.txt` is used for dependency check when installing azure sdk, or it it just a document file for user review? if it is used for dependency check, I think it is better to restrict a compatible version here, like:
```
futures
python-dateutil
requests>=VERSION1, <2.12.1
vcrpy
coverage
pyopenssl
msrest>=0.4.0,<0.5.0
msrestazure>=0.4.0,<0.5.0
```

**Comment by lmazuel** [comment]
Hi @gossion 
Actually, the requirements.txt at the root is using for general testing only. [We started to rename these files to dev_requirements.txt](https://github.com/Azure/msrest-for-python/blob/master/dev_requirements.txt). The `azure` meta-package itself does not requires external dependencies. In your situation, you use the [install_requires](https://github.com/Azure/azure-storage-python/blob/master/setup.py#L66) from storage. To be fair, the install_requires of the first real package installed by the `azure`, this will depends on the platform, python version and so on.
That being said, there is no compatibility issue with requests (we still use the same major version number). It's a bug introduced in requests that will be fixed soon for sure. You can freeze, in your application, `requests` in the meantime, [like the Azure CLI did](https://github.com/Azure/azure-cli#install-with-interactive-install-script).
Hope this helps,
Thanks,

**Comment by gossion** [comment]
Thans @lmazuel  for clarification. I already have a workaround in my application. 
Since there is no need to change for this SDK, I will close this issue.
