### ISSUE TITLE
Querying a Cosmos db with a CosmosClient created with a resource token.

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-python#8890]
I created a user for the db and gave it the ALL permission for items with partition key = 1 in a specific container. Then I created a CosmosClient with the token that's comes with the permission and tried to query the container by calling container.query_items(). But I kept getting a 403 error saying insufficient permissions provided in authorization header. 

I can, however, do read, upsert, create, and delete_item on items that have partition key =1. 

Here's my [code](https://github.com/lilyjma/azurethings/blob/master/getCosmosDataWithToken.py). 

Thanks!

**Comment by bryevdv** [comment]
cc @annatisch @rakshith91 I was not sure if this is a bug or a usage problem

@lilyjma contacted me about this, I can reproduce the 

> CosmosHttpResponseError: Status code: 403
{"code":"Forbidden","message":"Insufficient permissions provided in the authorization header for the corresponding request. Please retry with another authorization header.\r\nActivityId: 8460047d-0653-4a28-83c6-bf495e274ace, Microsoft.Azure.Documents.Common/2.7.0"}

result when this query is attempted:
```
for item in container.query_items(
    query='SELECT * FROM all_permission_collection c WHERE c.key="1"',
    enable_cross_partition_query=True,
):
    print(json.dumps(item, indent=True))
```

**Comment by bryevdv** [comment]
@srinathnarayanan just checking in, was there ever any determination made on the cause of this issue?

**Comment by lilyjma** [comment]
I talked to Jake Willey who works on this SDK but for .NET, and he suspects that: "permission validation is done before the query parsing. Since the partition key isn't in the header it doesn't have a way to ensure that it's only going to the partition it has permission to so it is failing the permission check." 

So if we pass in partition_key as a parameter into query_items(), it'll work: 

for item in container.query_items(
    query='SELECT * FROM all_permission_collection c WHERE c.key="1"',
    enable_cross_partition_query=False,
    partition_key="1",
):

(Note that setting enable_cross_partition_query=True will work too.)
