### ISSUE TITLE
Getting 400 error when trying to send a service bus message with broker properties

### ISSUE THREAD

**Issue by ncksol** [Azure/azure-sdk-for-python#890]
I am trying to send a message to my service bus and I need to populate Label property of that message.
Here is a snippet of my code:
```python
properties = {"Label":label}
msg = Message(bytes(messagebody, "utf-8"), bus_service, broker_properties=properties)
bus_service.send_queue_message("queue", msg)
```

What I  am getting is an Azure error:
The value '{'Label': 'testtest'}' of the HTTP header 'BrokerProperties' is invalid.

Am I missing something or is this a bug?

**Comment by lmazuel** [comment]
Hi @ncksol 
`broker_properties` is one HTTP header only and takes a string, not a dict. [See SB doc for reference.](https://msdn.microsoft.com/en-us/library/azure/hh780742.aspx#Anchor_0). It's not for personal data, but for advanced parameters.
Custom properties ([called Message Properties in the current doc](https://msdn.microsoft.com/en-us/library/azure/hh780742.aspx#Anchor_1)), take a dict. I think you want to use `custom_properties`. [Please see this unit test .](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/tests/test_servicebus_servicebus.py#L507)

**Comment by ncksol** [comment]
Hey @lmazuel 
Thanks for that link. I will try with a string. 
The reason I am populating broker properties is because I've noticed that it contains "Label" property and Microsoft Flow allows me to access "Label" of a message from Azure Service Bus. I've assumed that's the same "Label".

**Comment by lmazuel** [comment]
@ncksol I don't if this is the same Label, but seems a good guess :)
There is also a broker_properties unit test [here](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/tests/test_servicebus_servicebus.py#L366).

**Comment by ncksol** [comment]
@lmazuel cheers! If it's not the same label, than I'll go bug Microsoft Flow people =D
Thanks for your help.
