### ISSUE TITLE
EventHub Sender class : timeout wrong unit

### ISSUE THREAD

**Issue by TY48** [Azure/azure-sdk-for-python#8902]
EventHub Sender class 

https://github.com/Azure/azure-sdk-for-python/blob/ccdac0b1198a2273e63f9b55e81497478d573d5b/sdk/eventhub/azure-eventhubs/azure/eventhub/sender.py#L19

delegate the event handling, including timeout, to [uamqp SendClient class](https://github.com/Azure/azure-uamqp-python/blob/23b4d8e34a7aa631d6f5d60b0e0471a0f60340a2/uamqp/client.py#L412)

**Issue identified:**
SendClient class assumes timeout (‘msg_timeout’) in millisecond, but Eventhub Sender considers that this is in second.

**Consequence:**
The default value of Eventhub Sender is 60, which is 60millisecond, so it tends to raise timeout error easily.

**Possible solution:**
Change the unit of timeout in EventHub Sender class to millisecond, or convert second to millisecond in the EventHub Sender class initialization before passing the value to uamqp SendClient class

**Comment by annatisch** [comment]
Thanks @TY48 - we aware of this issue and are planning a fix for it :)

Adding @KieranBrantnerMagee

**Comment by yunhaoling** [comment]
Hello @TY48 ,

we've fixed this problem in azure-eventhub 1.3.3, can you try the v1.3.3?

**Comment by yunhaoling** [comment]
Hey @TY48 , I'm closing the issue for now as the latest release is supposed to fix the problem.. Let us know if the problem still exists.
