### ISSUE TITLE
KeyVault Certificate Client - [SSL: CERTIFICATE_VERIFY_FAILED] error

### ISSUE THREAD

**Issue by assafbari** [Azure/azure-sdk-for-python#8909]
Hi,

I'm trying to use the new Azure Key Vault Certificates client library for Python (azure-keyvault-certificates 4.0.0) behind a corporate proxy. when running the below sample code, the following error is raised:

`azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)`

I could not find a way to skip the SSL verification when using the certificate client, is there a way to do so?

Sample code:

```
from azure.keyvault.certificates import CertificateClient
from azure.common.credentials import ServicePrincipalCredentials

credentials = ServicePrincipalCredentials(
    client_id = '<SPN CLIENT ID>',
    secret = '<SPN SECRET>',
    tenant = '<SPN TENANT ID>'
)

certificate_client = CertificateClient(vault_url="https://<VAULT NAME>.vault.azure.net", credential=credentials)

certificate = certificate_client.get_certificate(name="<CERTIFICATE NAME>")

print(certificate.name)
print(certificate.properties.version)
print(certificate.policy.issuer_name)

```

**Comment by chlowell** [comment]
Yes, you can disable SSL verification with the keyword argument `connection_verify`. Also, azure-common's `ServicePrincipalCredentials` doesn't work with the new `CertificateClient`. You'll need a credential from [azure-identity](https://pypi.org/project/azure-identity/) (`ClientSecretCredential` is the equivalent). The credential has its own pipeline, so you'll need to disable SSL verification on it as well.

Fixing up your example:

```py
from azure.identity import ClientSecretCredential
from azure.keyvault.certificates import CertificateClient

credentials = ClientSecretCredential(
    tenant_id='<SPN TENANT ID>',
    client_id='<SPN CLIENT ID>',
    client_secret='<SPN SECRET>',
    connection_verify=False
)

certificate_client = CertificateClient(
    vault_url="https://<VAULT NAME>.vault.azure.net",
    credential=credentials,
    connection_verify=False
)
```

**Comment by assafbari** [comment]
Thank you, I tried to use the keyword argument `connection_verify=False` in the CertificateClient and in the ClientSecretCredentials and also utilizing the `azure-identity` library instead of `ServicePrincipalCredentials `.  it did solved the previous 'ServiceRequestError', now i got the below
certificate_bundle errors. is it possible to skip this verification as well or I'll have to import the CA certificate my organization is using for the web proxy? I guess this is a general python issue that is not necessarily related to the Azure SDK for Python.

```
C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\azure\core\tracing\decorator.py", line 62, in wrapper_use_tracer
    return func(*args, **kwargs) # type: ignore
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\azure\keyvault\certificates\client.py", line 154, in get_certificate
    return KeyVaultCertificate._from_certificate_bundle(certificate_bundle=bundle)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\azure\keyvault\certificates\models.py", line 306, in _from_certificate_bundle
    policy=CertificatePolicy._from_certificate_policy_bundle(certificate_bundle.policy),
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\azure\keyvault\certificates\models.py", line 776, in _from_certificate_policy_bundle
    return cls(
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\azure\keyvault\certificates\models.py", line 629, in __init__
    raise ValueError("You can only set at most one of san_emails, san_dns_names, and san_upns")
ValueError: You can only set at most one of san_emails, san_dns_names, and san_upns

```

**Comment by chlowell** [comment]
That `ValueError` came after the client deserialized a response from Key Vault, so I think you've sorted the proxy. In the latest preview library (4.0.0b6, released yesterday) we changed the behavior of the method that's raising that exception. Could you try again with 4.0.0b6?

**Comment by assafbari** [comment]
I can confirm that upgrading the azure-keyvault-certificates library to version 4.0.0b6 resolved the issue. I was able to get the KeyVault certificate properties with the same code, without the ValueError. Thank you!
