### ISSUE TITLE
When I tried to install using 'pip install azure' it failed due to permissions

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/azure-sdk-for-python#891]
This is the failing step:
/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x9/h92pwc1n7t5bcrtkykty1smm0000gq/T/pip-build-W2o1IO/azure/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x9/h92pwc1n7t5bcrtkykty1smm0000gq/T/pip-cJ8bvj-record/install-record.txt --single-version-externally-managed --compile

I eventually downloaded from git and ran "sudo python setup.py install" and it worked.

I'm a windows user who's doing new stuff on macOs, so I may just have a lame environment.

**Comment by lmazuel** [comment]
Hi @irwinwilliams 

When using `sudo`, you explicitly ask for root access. I guess then than `sudo pip install azure` would have work the same way than `sudo python setup.py install`.
I can't tell you why you local command does not work. However, common practice in Python is to use a [virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/) to install packages, to avoid this kind of questions.
Thanks,

**Comment by lmazuel** [comment]
Hi @irwinwilliams 
Could you confirm that your issue is solved?
Thank you,

**Comment by lmazuel** [comment]
I close this issue for inactivity. Please feel free to still comment on it if necessary.
Thank you,
