### ISSUE TITLE
[EventHubs]The current eventhub package 1.3.2 is not compatible with the latest azure blob storage v12.

### ISSUE THREAD

**Issue by imeya** [Azure/azure-sdk-for-python#8912]
The latest azure event hub package is [1.3.2](https://pypi.org/project/azure-eventhub/), which works well with the previous blob storage like 1.5.0 etc. The scenario is the that when we use EPH for event hub, we should use blob storage.

As of now, there is a new version of azure blob storage [v12](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python), if I installed the v12 version, it prompts an error: "ERROR: azure-eventhub 1.3.2 has requirement azure-storage-blob~=1.3, but you'll have azure-storage-blob 12.0.0 which is incompatible."

Please consider fixing this issue, thanks.

**Comment by annatisch** [comment]
Thanks @imeya - we will be releasing a new GA package early next year that will support the latest Storage library - although our hope is that we can remove the dependency entirely to prevent future conflicts.
Given that, it's unlikely that the eventhubs SDK v1.3.x will be updated to support the latest storage SDK.
If there a particular reason that you need the v12 Blobs SDK?

**Comment by imeya** [comment]
@annatisch , we tried to use the latest storage SDK since it's there, and found this issue. Yes, we can keep using old version storage SDK and wait for the fixing. Thanks.

**Comment by ibnipun10** [comment]
What is happening to this request. I would like to use ADLS gen2 and it is only in the latest storage SDK

**Comment by yunhaoling** [comment]
Hello @imeya , @ibnipun10 

We've recently release `azure-eventhub 5.0.0` and the `azure-eventhub-checkpointstoreblob/azure-eventhub-checkpointstoreblob-aio` library we provided is using the latest storage SDK.

Please try our latest SDK, any feedback is welcome :)

**Comment by Petermarcu** [comment]
Since the latest packages are all released and aligned can this be closed?

**Comment by yunhaoling** [comment]
thanks @Petermarcu for following upon the issue which I totally missed.

Hey @imeya @ibnipun10 , apologize for letting the issue fall off my track.
It has been a while since EventHub v5 was released, does it meet your requirements with Storage v12 properly?
Let me know if there's any help I can provide you with regards to usage of the latest EventHub SDK.

**Comment by ramya-rao-a** [comment]
@yunhaoling Given that we have tests that use Storage v12 for checkpointing when using Event Hubs v5, I would recommend we close this issue.

@imeya, if you still see any issues using the packages @yunhaoling has mentioned above, please log a new issue in this repo. We would be happy to hear any feedback you have using the new packages as well.
