### ISSUE TITLE
[Data Factory] [Dataset] AzureBlobStorageLocation : container field is not applied

### ISSUE THREAD

**Issue by maximemauro** [Azure/azure-sdk-for-python#8914]
Hello,

I'm using the SDK and trying to deploy the following dataset to Data Factory:

> {
>     "name": "BLOB_TEST_CI",
>     "type": "Microsoft.DataFactory/factories/datasets",
>         "linkedServiceName": {
>             "referenceName": "BLOB_DTP_TLS_INPUT",
>             "type": "LinkedServiceReference"
>         },
>         "annotations": [],
>         "type": "DelimitedText",
>         "typeProperties": {
>             "location": {
>                 "type": "AzureBlobStorageLocation",
>                 "folderPath": "dataset",
>                 "container": "test"
>             },
>             "columnDelimiter": ",",
>             "escapeChar": "\\",
>             "quoteChar": "\""
>         },
>         "schema": []
> }

And in the Data Factory UI, the "container" field is empty.
Every other fields are correctly filled.

Screenshots :
UI: https://cdn1.imggmi.com/uploads/2019/12/2/4cf62ab3df15a0cc877f60e7de73a253-full.png
Code block from UI: https://cdn1.imggmi.com/uploads/2019/12/2/22fd409664b0fbbff4ba34a47e1b39c9-full.png

Is this a bug ? Or did I miss something in the configuration ?

Thanks for your help,
Maxime

**Comment by zhangyd2015** [comment]
Adding @shawnxzq, the new ADF SDK owner.

**Comment by shawnxzq** [comment]
Please use the latest version of Az module, it should work.

**Comment by shawnxzq** [comment]
@zikalino Could you please help close it since I can't close it, thx!
