### ISSUE TITLE
Top-level Package "azure" has not been updated for v5 SDKs

### ISSUE THREAD

**Issue by lokitoth** [Azure/azure-sdk-for-python#8915]
Right now, if a user installs the "azure" 'metapackage', it will lock on version 4.0.0 (with associated 4.X versions of the individual packages). 

Unfortunately, when updating one of the child packages version, the system raises an error (likely spurious) an incompatibility error is raised (the package still seems to install successfully).

**Comment by lmazuel** [comment]
Hi @lokitoth 
Thanks for your report! We are actually well aware of this issue and we are discussing the best way moving forward to version the "azure" meta-package. 
The best approach right now if you want some more recent versions would be to install them individually.

**Comment by lmazuel** [comment]
`azure` meta-package has been officially deprecated. You can find the list of all available packages here:
https://aka.ms/azsdk/python/all
