### ISSUE TITLE
TypeError whilst creating virtual_network_peerings

### ISSUE THREAD

**Issue by thiezn** [Azure/azure-sdk-for-python#892]
When trying to establish a peering between two vnets using network_client.virtual_network_peerings, it fails during serialization of the virtual_network_peering_parameters.

```
  File "./network_example.py", line 474, in <module>
    create_vnet_peering(network_client, GROUP_NAME, 'VNET-Inet-Services', 'VNET-Three-Tier-App')
  File "./network_example.py", line 421, in create_vnet_peering
    'remote_virtual_network': vnet2.id
  File "/usr/local/lib/python3.5/site-packages/azure/mgmt/network/operations/virtual_network_peerings_operations.py", line 235, in create_or_update
    body_content = self._serialize.body(virtual_network_peering_parameters, 'VirtualNetworkPeering')
  File "/usr/local/lib/python3.5/site-packages/msrest/serialization.py", line 303, in body
    data = _convert_to_datatype(data, data_type, self.dependencies)
  File "/usr/local/lib/python3.5/site-packages/msrest/serialization.py", line 164, in _convert_to_datatype
    localtypes) for key in data
  File "/usr/local/lib/python3.5/site-packages/msrest/serialization.py", line 164, in <dictcomp>
    localtypes) for key in data
  File "/usr/local/lib/python3.5/site-packages/msrest/serialization.py", line 164, in _convert_to_datatype
    localtypes) for key in data
  File "/usr/local/lib/python3.5/site-packages/msrest/serialization.py", line 164, in <dictcomp>
    localtypes) for key in data
TypeError: string indices must be integers
```

I could not find any [tests](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_network.py) related to virtual_network_peerings so I'm not sure if this was working properly before. Tried to dig into the serialization class but having a hard time wrapping my head around it. This is the pseudo code I'm running:

```
    group_name = 'Resource-Group'
    vnet1_name = 'VNET1'
    vnet1_peering_name = 'LinkToVnet2'
    vnet2_name = 'VNET2'
    vnet2_peering_name = 'LinkToVnet1'

    vnet1 = network_client.virtual_networks.get(group_name, vnet1_name)
    vnet2 = network_client.virtual_networks.get(group_name, vnet2_name)

    async_creation = network_client.virtual_network_peerings.create_or_update(
        group_name,
        vnet1_name,
        vnet1_peering_name,
        {
            'remote_virtual_network': vnet2.id
        }
    )
```
Any help is much appreciated

cheers
Thiezn

**Comment by lmazuel** [comment]
Hi @thiezn 

You're right, I didn't find the time yet to do the VNet Peering samples. [Looking at the documentation](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.network.models.html#azure.mgmt.network.models.VirtualNetworkPeering), the right syntax is:
```python
async_creation = network_client.virtual_network_peerings.create_or_update(
        group_name,
        vnet1_name,
        vnet1_peering_name,
        {
            'remote_virtual_network': {
               'id': vnet2.id
            }
        }
    )
```
Could you test this and tell if this solve your serialization problem?

I'm pretty confident that the underlying code is working, because it is generating by the same meta-description that the [PowerShell Cmdlets](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-create-vnetpeering-arm-ps).

**Comment by thiezn** [comment]
Thanks for the swift reply @lmazuel. 
I tested it and works like a charm, my apologies for not reading the docs well enough.

**Comment by lmazuel** [comment]
@thiezn Glad to hear it's working :)
Don't apologize, documentation should be straight or exception should be clearer at least. Thanks for the feedback!
