### ISSUE TITLE
[textanalytics] Consider having language and country_hint as enums instead of passed as strings

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#8929]
Need to look at other cognitive services to see if there is a common language standard used.

- Text Analytics is using 2 letter ISO 639-1 for language and ISO 3166-1 alpha-2 for country hint.
- Computer Vision uses BCP-47 language code

**Comment by iscai-msft** [comment]
1. For language it was decided to leave as string in all cognitive Services (see more here
	Assaf Israel: Re - language codes. Apparently there's already a mandatory standard in… )
	
2. For countryHint we don't provide a list just to avoid political implications. The user can send whatever and the service is responsible to validate it.
