### ISSUE TITLE
Behaviour of NetworkManagementClient create / delete changed.

### ISSUE THREAD

**Issue by parimanur** [Azure/azure-sdk-for-python#8937]
I am currently using azure-mgmt-network==1.5.0 in my environment. 
In that version, the return for the function create_or_update was below depending on the **raw** flag.
>         :return:
>          :class:`AzureOperationPoller<msrestazure.azure_operation.AzureOperationPoller>`
>          instance that returns :class:`NetworkInterface
>          <azure.mgmt.network.v2017_03_01.models.NetworkInterface>` or
>          :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>` if
>          raw=true
But with the recent releases, eg: 8.0.0 there is no method which I can use to get the ClientRawResponse instance. 
An LROPoller instance is returned has the **_response** field which has only the response stored. 
`        self._response = initial_response.response if isinstance(initial_response, ClientRawResponse) else initial_response
`

Can you help here on changes for the code to be backwards compatible with the previous releases?
I am using the below snippet in the 1.5.0 version to get the Deserialized response NetworkInterface object. ( Not using the polling )

>         result =network_client.network_interfaces.create_or_update(
>                     resource_group, name, parameters, raw=True)
>         return result.output

**Comment by lmazuel** [comment]
Hi @parimanur 
There is a change a behavior documented in the ChangeLog of 2.0.0rc1
https://pypi.org/project/azure-mgmt-network/

> New Long Running Operation:
> - Return type changes from msrestazure.azure_operation.AzureOperationPoller to msrest.polling.LROPoller. External API is the same.
> - Return type is now always a msrest.polling.LROPoller, regardless of the optional parameters used.
> - The behavior has changed when using raw=True. Instead of returning the initial call result as ClientRawResponse, without polling, now this returns an LROPoller. After polling, the final resource will be returned as a ClientRawResponse.
> - New polling parameter. The default behavior is Polling=True which will poll using ARM algorithm. When Polling=False, the response of the initial call will be returned without polling.
> - polling parameter accepts instances of subclasses of msrest.polling.PollingMethod.
> - add_done_callback will no longer raise if called after polling is finished, but will instead execute the callback right away.

In your scenario, you want to pass `polling=False, raw=True` and do a `.result()` to get the `ClientRawResponse` instance.

**Comment by parimanur** [comment]
Thanks @lmazuel,  for the response. I will check with those params.

**Comment by lmazuel** [comment]
Sorry, but I insist, and just tested it right now:
![image](https://user-images.githubusercontent.com/1050156/70341953-eb9d9700-1808-11ea-91e4-210e2a59727c.png)

**Comment by parimanur** [comment]
My Bad @lmazuel, I was using False value for raw, Thanks for the clarification and help. Will close the issue now.
