### ISSUE TITLE
AppConfiguration select doesn't handle wildcards correctly

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-python#8940]
https://github.com/Azure/azure-sdk-for-python/blob/c9dd2c4303efb5fcd01ecca7662e9a77c4410654/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_utils.py#L26

This will not correctly handle a key named "\*", or "\***".

@xiangyan99

**Comment by xiangyan99** [comment]
Fixed
