### ISSUE TITLE
Expose a kwargs "add_to_user_agent"

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#8941]
Right now it's not possible to add anything to the user-agent unless you create your own policy UserAgentPolicy yourself, which means create your own pipeline.

**Comment by annatisch** [comment]
We do support this per request:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L209

But you're right - seem that we (probably I) forgot to add it on init..... :)

**Comment by xiangyan99** [comment]
Do you mean we want to expose "add_to_user_agent" for every pipeline run?

**Comment by lmazuel** [comment]
@annatisch yes, `user_agent` achieves this purpose, but we need one in init as you say :)
@xiangyan99 I don't understand your comment, as @annatisch says the idea is to have one in the init, so people can customize as a whole the user-agent, and not force them to do that per request

**Comment by jsntcy** [comment]
@xiangyan99  Previously we use something like "client.config.add_user_agent(UA_AGENT_1); client.config.add_user_agent(UA_AGENT_2)" to append our own user agents in Azure CLI code, after your PR #9355 , how can I use it to achieve the same goal?
cc @lmazuel

**Comment by lmazuel** [comment]
@jsntcy the kwargs will be called "user_agent"

**Comment by jsntcy** [comment]
@lmazuel , so I if I add to two use agents as I did before like "client.config.add_user_agent(UA_AGENT_1)
 client.config.add_user_agent(UA_AGENT_2)",

do I need use as follows?
policy = UserAgentPolicy(),
policy.add_user_agent(UA_AGENT_1),
policy.add_user_agent(UA_AGENT_2),
kwargs['user_agent'] = policy
client(**kwargs)

**Comment by lmazuel** [comment]
Nope, you would have to build the string and pass one kwarg:
```python
kwargs['user_agent'] = " ".join(UA_AGENT_1, UA_AGENT_2)
client(**kwargs)
```
You don't instantiate the UserAgentPolicy, that's internal

**Comment by xiangyan99** [comment]
Fixed
