### ISSUE TITLE
Web Search error/warning "Subtype value has no mapping..."

### ISSUE THREAD

**Issue by wiazur** [Azure/azure-sdk-for-python#8979]
I am running a [sample for Web Search ](https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/blob/master/samples/search/web_search_samples.py)(Cognitive Services) and the sample runs fine, but I get this warning type text in the printed results of my sample:
`Subtype value Organization has no mapping, use base class Thing.`

What does this mean?

Printed results:
```
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Searched for Query# " Xbox "
Webpage Results#9
First web page name: Xbox
First web page URL: https://www.xbox.com/
Image Results#20
First Image name: Defcon Skins™ Gives Gaming Enthusiasts the Ability to Unleash the Cool Factor and Make Consoles ...
First Image URL: None
News Results#5
First News name: 2019's Best Gaming Headsets and Gaming Headphones: PS4, Xbox One, And PC
First News URL: https://www.gamespot.com/articles/2019s-best-gaming-headsets-and-gaming-headphones-p/1100-6471725/
Videos Results#10
First Videos name: Xbox Elite Wireless Controller Series 2 - E3 2019 - Announce Trailer
First Videos URL: None

Searched for Query# " Best restaurants in Seattle "
Webpage Results#20
First web page name: 10 Best Restaurants in Seattle, WA - USA TODAY 10Best
First web page URL: https://www.10best.com/destinations/washington/seattle/restaurants/best-restaurants/

Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Searched for Query# " Microsoft " with response filters "News"
Webpage Results#5
First web page name: As more employees quit Microsoft-owned Github over its ICE contract, Microsoft shareholders are deciding whether to add an employee to the board
First web page URL: https://www.businessinsider.com/microsoft-github-employee-backlash-board-representation-2019-12

Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Subtype value Organization has no mapping, use base class Thing.
Searched for Query# " Lady Gaga"
Webpage Results#8
First web page name: Lady Gaga
First web page URL: https://www.ladygaga.com/

```

**Comment by lmazuel** [comment]
Hi @wiazur 
It means the runtime wasn't able to find a meta-description of the "Organization" type, and then the runtime decided to use the known base type type instead (Thing). This means you get an instance of "Thing", and some data might be in the "additionnal_properties" attribute because the runtime didn't know where else to put them.

The best fix would be to add "Organization" in the meta-description of this service:
https://github.com/Azure/azure-rest-api-specs/issues/2014

**Comment by lmazuel** [comment]
@wiazur if you don't care about the "organization" information, that was no impact on you at all, and you can just mute the "msrest" logger using logging API.

**Comment by wiazur** [comment]
Thanks @Imazuel, those are some good options. Do you know if the SDK will update in the next iteration on this issue? I could write the suppression into the code, but then if customers want to use the metadata that could be confusing.

**Comment by lmazuel** [comment]
Fixing the meta-description is out of my scope unfortunately, I encourage you to comment on that issue:
https://github.com/Azure/azure-rest-api-specs/issues/2014

Once it's noted fixed, we could release an update that will fix it.

**Comment by lmazuel** [comment]
Those SDKs are not supported anymore, and have been replaced by new ones. Bing is not a part of Azure nowadays, please address issues to https://github.com/microsoft/bing-search-sdk-for-python and consider using https://pypi.org/project/microsoft-bing-websearch/ instead. Thanks, and sorry for the late answer.
