### ISSUE TITLE
List virtual machines is missing newly created VM

### ISSUE THREAD

**Issue by gmistick** [Azure/azure-sdk-for-python#8985]
Hi,

I am using the virtual_machines.list() function to list all vms in my resource group. 
My script is calling this method multiple times to make sure VM was created successfully and get complete information (Public and private IP), but a lot of times, I'm getting results that don't include these newly created VM's.

Any idea if there is any caching going on or another control mechanism that I can control to prevent this caching and get the real vm machine list?

**Comment by Drewm3** [comment]
Is this being seen when listing all VMs in the subscription, when listing VMs in a resource group or both? Could you also share the frequency in which you are seeing this behavior?

**Comment by Drewm3** [comment]
Closing this due to no response.

**Comment by gmistick** [comment]
Hi , sorry for the no response, i missed previous email.
1. I used list in resource group.
2. the frequency was every few seconds/ minutes. 
But this scenario:
a. get all vms.
b. create multiple vms in multiple threads
c. in each thread after create vm, list vm in resource group to get the current new vm with config i needed.
there sometimes it was missing

**Comment by chester-leung** [comment]
@GM12Tick did you ever resolve this?
