### ISSUE TITLE
Implement Send Message batch for Service Bus

### ISSUE THREAD

**Issue by makhdumi** [Azure/azure-sdk-for-python#902]
Unlike Receive Message, there _is_ an API for [batch Send Message](https://msdn.microsoft.com/en-us/library/azure/dn798894.aspx).

Please consider implementing this, or allowing a pull request for it. While using AMQP was recommended in [#459](https://github.com/Azure/azure-sdk-for-python/issues/459) for high-performance because of HTTP limits, it's a massive pain to just install the AMQP Proton bindings because it needs to be built from the source. I actually save myself a lot of time by just switching to AWS Kinesis.

I don't need super high performance, it's just extremely inefficient to send hundreds of tiny 120-byte messages with the relatively huge HTTP header overhead.

**Comment by lmazuel** [comment]
Hi @makhdumi 

We totally allow PRs, you don't have to ask first :). Improving the HTTP SB package is unfortunately not a priority, but if you can provide a PR I will be happy to review and discuss, and release a package asap after that.
If I find time in near future to do so, I will try, but I cannot promise anything.
Thank you,

**Comment by lmazuel** [comment]
@makhdumi Released https://pypi.python.org/pypi/azure-servicebus/0.21.0
Thank you for the feedback!

**Comment by rajata07** [comment]
@lmazuel Where can i find example of batch send operation for service bus using AMQP?
