### ISSUE TITLE
Unable to import other python modules in called scripts

### ISSUE THREAD

**Issue by imsiddsingh** [Azure/azure-sdk-for-python#9049]
I have created a simple HTTP trigger-based azure function in python which is calling another python script to create a sample file in azure data lake gen 1. My solution structure is given below: -

FunctionApp
|_ HttpTrigger
         |_____ __init__.py
         |_____ Test.py
         |_____ function.json

Requirements.txt contains the following imports: -
- azure-functions
- azure-mgmt-resource
- azure-mgmt-datalake-store
- azure-datalake-store

**__init__.py** 
```
import logging, os, sys

import azure.functions as func
import json

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:         
            name = req_body.get('name')

    if name:
        full_path_to_script = os.path.join(os.path.dirname( __file__ ) + '/Test.py')
        logging.info(f"Path: - {full_path_to_script}")
        os.system(f"python {full_path_to_script}")
        return func.HttpResponse(f"Hello {name}!")
    else:
        return func.HttpResponse(
             "Please pass a name on the query string or in the request body",
             status_code=400
        )
```

**Test.py**

```
import json
from azure.datalake.store import core, lib, multithread

directoryId = ''
applicationKey = ''
applicationId = ''
adlsCredentials = lib.auth(tenant_id = directoryId, client_secret = applicationKey, client_id = applicationId)
adlsClient = core.AzureDLFileSystem(adlsCredentials, store_name = '')

with adlsClient.open('stage1/largeFiles/File_256_KB.json', 'rb') as input_file:
    data = json.load(input_file)
    with adlsClient.open('stage1/largeFiles/File_256_KB_Result.json', 'wb') as responseFile:
        responseFile.write(data)
```

Test.py is failing with an error that **no module found azure.datalake.store**
Why other required modules are not working for Test.py since it is inside the same directory?

![image](https://user-images.githubusercontent.com/27725324/70389542-12063280-19c1-11ea-817e-7d3a73f3b315.png)

**Comment by v-xuto** [comment]
What IDE are you using to deploy?when you upload the code to the function app, you can click on 'OUTPUT' to see if you have successfully installed the azure.datalake.store package. Before doing so, make sure your requirements.txt contains "azure-datalake-store".
```
Downloading https://files.pythonhosted.org/packages/27/9a/e7140775b3f8f011ef5d001c12a3519310094375671950105519e30bb12b/azure_datalake_store-0.0.48-py2.py3-none-any.whl
```

**Comment by imsiddsingh** [comment]
Yes, I am able to successfully install azure.datalake,.store.package. I am using visual studio code.

**Comment by v-xuto** [comment]
First, two points need to be distinguished: the packages in requirement.txt file will eventually be installed in Azure function's environment; but the azure.datalake package is not installed locally.

So, we can hit this problem when I run test.py locally in visual studio code.
ERROR:
```
ModuleNotFoundError: No module named 'azure.datalake'
```
If we want test.py to run successfully locally, we need to install "azure-datalake-store" package in terminal locally, such as:
```
(.venv) PS D:\code\CS> pip install azure-datalake-store
```

**Comment by v-xuto** [comment]
Hi @imsiddsingh，
Has your issue been resolved after installing the  'azure-datalake-store' package locally?
