### ISSUE TITLE
AppConfig tests should use test framework preparer

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#9062]
And then have a dev dependency on azure-mgmt-appconfiguration: create and delete it on the fly.

That will bring consistency with Storage and KeyVault

**Comment by lmazuel** [comment]
@seankane-msft is working on supporting the PS system from engsys, it would be more actionable to do that instead of a specific preparer:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/test-resources.json

**Comment by xiangyan99** [comment]
@seankane-msft Seems like it is already fixed, right?

**Comment by seankane-msft** [comment]
@xiangyan99 Yes, we are using the current test framework, closing this issue.
