### ISSUE TITLE
CogServices Internal Release Disappears After Build

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#9069]
The [build itself](https://dev.azure.com/azure-sdk/internal/_build?definitionId=976&_a=summary) looks fine:

![image](https://user-images.githubusercontent.com/45376673/70485926-20c61580-1aa5-11ea-9d5a-4f4f7934f3f1.png)

However when you _click_ on it. 

![image](https://user-images.githubusercontent.com/45376673/70485964-32a7b880-1aa5-11ea-983a-e1fca752e8df.png)

After refreshing:

![image](https://user-images.githubusercontent.com/45376673/70485981-39cec680-1aa5-11ea-9415-3b3f27534198.png)

Filed an ICM with the DevOps team: `162572499`

**Comment by kurtzeborn** [comment]
This might have just been a weird hiccup in DevOps.

CC: @mitchdenny

**Comment by scbedd** [comment]
@kurtzeborn already talked to Mitch. I'm filing an ICM for this item this AM. He thinks one of their js renderers is imploding.

**Comment by scbedd** [comment]
The DevOps team triaged, investigated, found the issue, and pushed a fix. You can now look at cogservices release pane without crashes!
