### ISSUE TITLE
Remove Storage Swagger Readme Transforms

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-python#9070]
During the push to GA track 2, several transforms were added to the readme which need to be migrated to the swagger in azure-rest-api-specs.  This should be coordinated across all of the langauge swaggers.  
- Apply any bugfixes (ie. batch return code)
- For client side renames, we should try to use `x-ms-client-name`

Once this is done, there should be no diffs in the generated code.

**Comment by tasherif-msft** [comment]
This is a long way ahead as there is a lot of intricacies between languages currently and the transforms each language applies.
