### ISSUE TITLE
[azure identity] Support for Creating TokenCredentials using OAuth Tokens

### ISSUE THREAD

**Issue by abhi2196** [Azure/azure-sdk-for-python#9075]
Does the azure.identity package supports creating TokenCredentials using OAuth Tokens ?

https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#successful-response-1
https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

Could not find any references here: https://pypi.org/project/azure-identity/

I have updated my client code to use the new azure-storage-blob 12.1.0 APIs which uses azure.identity for providing credential.

With the earlier BlockBlobService APIs, we can pass the token credential from the azure.storage.common TokenCredential Class (which used OAuth Tokens) 
for e.g
https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/oauth.py

**Comment by chlowell** [comment]
Azure-identity credentials provide tokens given authentication information. So instead of acquiring tokens yourself, you choose the identity you want to authenticate (e.g. a service principal), create a credential for it, and pass that credential to `BlobServiceClient`. You probably want [`DefaultAzureCredential`](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.1.0/azure.identity.html#azure.identity.DefaultAzureCredential) or [`ClientSecretCredential`](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.1.0/azure.identity.html#azure.identity.ClientSecretCredential):

```py
from azure.identity import DefaultAzureCredential, ClientSecretCredential
from azure.storage.blob import BlobServiceClient

# DefaultAzureCredential supports managed identity or environment configuration (see docs)
credential = DefaultAzureCredential()

# alternatively, one way to programmatically configure service principal authentication
credential = ClientSecretCredential(tenant_id, client_id, client_secret)

# in any case you pass the credential to BlobServiceClient, it gets tokens as needed
blob_client = BlobServiceClient(
    account_url="https://<my_account_name>.blob.core.windows.net",
    credential=credential
)
```

**Comment by abhi2196** [comment]
oh I see.
Actually my use-case is slightly different, as i have a custom service which returns me the Azure OAuth Tokens (in return for the User MSI details i provide to the service), and i need to validate those tokens by performing some client side storage operations (Create container, read, write) using BlobServiceClient APIs.

Is this possible currently with the available BlobServiceClient Python SDKs ?

**Comment by chlowell** [comment]
Yes, you can create your own credential class. All it must do is implement `get_token`:

```py
from azure.core.credentials import AccessToken
from azure.storage.blob import BlobServiceClient

class CustomTokenCredential(object):
    def get_token(*scopes, **kwargs):
       # ... your logic here ...
       return AccessToken(access_token, expires_on)

# BlobServiceClient will call get_token whenever it wants a token
credential = CustomTokenCredential()
blob_client = BlobServiceClient(
    account_url="https://<my_account_name>.blob.core.windows.net",
    credential=credential
)
```

**Comment by abhi2196** [comment]
Thanks @chlowell
