### ISSUE TITLE
Update sphinx-docfx-yaml to properly generate intermediate yaml for keyword arguments

### ISSUE THREAD

**Issue by cccs-cat001** [Azure/azure-sdk-for-python#9076]
I've noticed that with the old azure-storage-blob (v1.5.0), when you upload a blob it doesn't care whether the blob exists already or not, it'll overwrite it, but with the new version, v12.1.0, when you go to upload a blob it will not overwrite an already existing blob. Not sure if this is a new feature or what, but it'd be nice to have it consistent with the old one. Or maybe even have a parameter to the upload blob method(s) to specify whether you should overwrite or not.

**Comment by kaerm** [comment]
@cccs-cat001 thanks for the feedback! I am looping in someone from our team to take a look at this //cc: @mayurid @rakshith91

**Comment by rakshith91** [comment]
Hi @cccs-cat001  Thanks for reporting the issue. In version 12.0.0 and above, if you want upload to overwrite an existing blob, you will have to pass the `overwrite` parameter
Something like this:
`blob.upload_blob(data, overwrite=True)`

Note that the default value for overwrite is False.

**Comment by cccs-cat001** [comment]
Perfect that works! Can that be added to the [documentation](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#upload-blob-data--blob-type--blobtype-blockblob---blockblob----length-none--metadata-none----kwargs-)? Nowhere does it mention that you need to specify that.

**Comment by rakshith91** [comment]
That's a good catch. We'll definitely update it. Meanwhile, i'd encourage using[ this documentation](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.1.0/index.html) for now till we fix the issues with the other one.

**Comment by sworisbreathing** [comment]
@rakshith91 I just ran into this issue. Any ETA on when the documentation will be updated? It's been 3 months already.

**Comment by sworisbreathing** [comment]
also does this apply to the aio client? I've tried the `overwrite=True` kwarg and it's still failing

**Comment by MercyPrasanna** [comment]
I also ran into this issue, the documentation should be updated for this.

**Comment by fedler** [comment]
How can i specify overwrite = true and headers at the same time?

**Comment by howardjones** [comment]
I also just hit this issue. Still nothing in the docs! :-) (8 months)

**Comment by scbedd** [comment]
Removing @xiafu-msft , adding myself. Status: opened a PR and am pushing a resolution through the docs pipeline.

**Comment by xiafu-msft** [comment]
Hi @howardjones 

Please refer to this doc for now, https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.3.2/azure.storage.blob.html#azure.storage.blob.BlobClient.upload_blob it should have keyword arguments listed. Sorry about the inconvenience.

**Comment by scbedd** [comment]
Added `EngSys` label and updated title for better tracking of this issue.

**Comment by scbedd** [comment]
This was erroneously closed. Issue being resolved when [this PR](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/708) merges.

**Comment by scbedd** [comment]
Fixed. [keyword params render](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.datalakefileclient?view=azure-python#flush-data-offset--retain-uncommitted-data-false----kwargs-) 

Apologies to everyone for the wait.

I've filed another [follow-up](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.datalakefileclient?view=azure-python#flush-data-offset--retain-uncommitted-data-false----kwargs-) item for updating the parameter labeling.

**Comment by molakasanjay** [comment]
I have used upload method :- blob_client.upload_blob(data,overwrite=True)
but got the error:-

ResourceExistsError: The requested operation is not allowed in the current state of the entity.
RequestId:5d89f11a-201e-0009-2aff-9f08dd000000
Time:2021-09-02T13:37:31.2308862Z
ErrorCode:OperationNotAllowedInCurrentState
