### ISSUE TITLE
[azure-cosmos] Distributed tracing: wrong parent-child relationship between spans and duration issues

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#9079]
repro app below (combined basic cosmos query sample with basic opencensus sample)

## Expected
* query_items span becomes parent of http request span. 
* query_items span has duration >= http request span
* **[Update]** when query ends with exception (e.g. container does not exists), query_items should end with non-success status. **Bug in Azure Monitor exporter.**

E.g. how it looks for blobs
![image](https://user-images.githubusercontent.com/2347409/70568444-c3859f00-1b4c-11ea-93b2-ce8656875f21.png)

## Actual
* query_items span is sibling of http request span. 
* query_items span has 0 duration
* **[Update]** ~~when query ends with exception (e.g. container does not exists), span for query_items status is OK.~~ **Bug in Azure Monitor exporter.** 

![image](https://user-images.githubusercontent.com/2347409/70568392-a2bd4980-1b4c-11ea-8131-ae2148735d55.png)

```python
import json
import os
import time
from azure.cosmos import CosmosClient, PartitionKey, exceptions

from opencensus.ext.azure.trace_exporter import AzureExporter
from opencensus.trace.tracer import Tracer
from opencensus.trace.samplers import AlwaysOnSampler

# you could use zipkin
exporter = AzureExporter( 
    instrumentation_key="your ikey"
)

url = 'url'
key = 'key'
client = CosmosClient(url, credential=key)

database = client.get_database_client('ToDoList')
container = database.get_container_client('Items')

tracer = Tracer(exporter=exporter, sampler=AlwaysOnSampler())
with tracer.span(name="MyApplication") as span:
    for item in container.query_items(
            query='SELECT * FROM Items',
            enable_cross_partition_query=True):
        print(json.dumps(item, indent=True))
```

**Comment by sameergMS** [comment]
Routing to Cosmos DB Python SDK as this relates to tracing implementation in Cosmos DB

**Comment by annatisch** [comment]
This appears to be related to how spans are handled in azure-core pageables.
There is ongoing discussion on the best approach to this topic.
@southpolesteve - no changes will need to introduced into azure-cosmos SDK for this for the time being. It's likely that if a fix is needed, that it will go into azure-core.

**Comment by lmazuel** [comment]
Tagging feature-request, since this is the regular behaviour for listing operation:
- The method call will return an iterator object and close the method span
- Iterating over this iterator will create span that are not sub-span

Talking with @johanste we could imagine using link instead, this needs more precise discussion.
