### ISSUE TITLE
uthentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

### ISSUE THREAD

**Issue by skanthb** [Azure/azure-sdk-for-python#9080]
'''
in cmd set below environment variables
set AZURE_CLIENT_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxx"
set AZURE_CLIENT_SECRET="xxxxxxxxxxxxxxxxxxxxxxxxxxx"
set AZURE_TENANT_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxx"
'''

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

credential = DefaultAzureCredential()
secret_client = SecretClient(vault_url, credential=credential)
secret = secret_client.get_secret("AYXDDWDEV")

getting below error:
Authentication failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

also tried below approach and end up with same error:

from azure.identity import ClientSecretCredential
from azure.keyvault.keys import KeyClient
from azure.keyvault.secrets import SecretClient

credential = ClientSecretCredential(tenant_id, client_id, client_secret)
secret_client = SecretClient(vault_url, credential=credential)
secret = secret_client.get_secret("AYXDDWDEV")

Can someone please help?

Thanks,
Srikanth

**Comment by kaerm** [comment]
@skanthb thanks for the feedback! Someone from our team will take a look at this //cc: @chlowell @mayurid

**Comment by chlowell** [comment]
Looks like you're missing a root certificate. In this case you'd be using `requests` for transport, which uses certificates from `certifi` ([docs](https://2.python-requests.org//en/latest/user/advanced/#ca-certificates)). Which platform are you on, and which version of `requests` and `certifi` do you have installed?

**Comment by skanthb** [comment]
requests==2.22.0
requests-oauthlib==1.3.0
Im running the code on windows 10 laptop-Python 3.7.5 within work network and then accessing Azure key vault using Azure python SDK.

https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity#defaultazurecredential
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-secrets#retrieve-a-secret

Thanks,
Srikanth

**Comment by chlowell** [comment]
Does this network have a traffic inspecting proxy? If so, you'd see an error like this if `requests` doesn't trust that proxy's certificates.

I'd guess the failing request is to login.microsoftonline.com. You can try it without the Azure SDK:
```py
import requests
requests.get('https://login.microsoftonline.com/')
```

**Comment by skanthb** [comment]
Thanks @chlowell you are correct. Its proxy issue. I got a http proxy url and tried doing below and it worked.

from azure.storage.blob import BlobServiceClient
from azure.storage.blob._shared.base_client import create_configuration
http_proxy = 'http://xxxxxxxxxxx:yyyy'

# Create a storage Configuration object and update the proxy policy.
config = create_configuration(storage_sdk='blob')
config.proxy_policy.proxies = {
    'http': http_proxy
}

blob_service_client = BlobServiceClient.from_connection_string(connection_string, _configuration=config)

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/samples/blob_samples_proxy_configuration.py

Thanks,
Srikanth

**Comment by chlowell** [comment]
Great, I'm glad you got it working. However, all clients should accept the `proxies` keyword argument, and it would be safer to use that because underscored things are internal and may change in future releases. For `BlobServiceClient`, you'd want something like this:
```py
from azure.storage.blob import BlobServiceClient

proxies = {"http": "http://xxxxxxxxxxx:yyyy"}

blob_service_client = BlobServiceClient.from_connection_string(connection_string, proxies=proxies)
```
I opened #9311 to track updating the storage samples, and am closing this issue because the original problem is solved.
