### ISSUE TITLE
[FEATURE REQ] EventHub distributed tracing: stamp EventHubs info on processing spans

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#9085]
**Is your feature request related to a problem? Please describe.**
When EventHub processor receives messages, the only telemetry it generates is the processing span.  This span is not attributed with any event-hub specific info (endpoint, entity).

I.e. there is no way of knowing which EventHub certain app communicates with and processes messages from. Users may know it, but tools/visualizations don't. Also it requires an extra steps for users to look somewhere up this information or if app talks to mare than one hub/entity, it creates ambiguity.

**Describe the solution you'd like**
Similarly to send spans, stamp event hub properties on processing spans:
 - `message_bus.destination`: EventHub entity name
-  `peer.address`: Fully qualified EventHub service endpoint such as `sb://<name>.servicebus.windows.net/`

**Describe alternatives you've considered**
Instrumenting some calls (e.g. connection initiation or receive) from app to EventHubs. Connection initiation does not seem to be particularly useful.
Instrumenting 'receive' calls [brings low additional value](https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#receive-messages)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kaerm** [comment]
Thanks @lmolkova //cc: @mayurid

**Comment by lmazuel** [comment]
Actually done already:
https://github.com/Azure/azure-sdk-for-python/blob/25c0a046c3c486c83ec4fbc9fbbdf253e1091cf8/sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/_eventprocessor_mixin.py#L106-L107

https://github.com/Azure/azure-sdk-for-python/blob/25c0a046c3c486c83ec4fbc9fbbdf253e1091cf8/sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py#L247-L250
