### ISSUE TITLE
EventHubs distributed tracing: span kind changes

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#9099]
EventHub spans kinds were not correct in the previous guidance. They should be changed to
- Message: 'producer' kind for OpenTelemtery (was 'internal'). OpenCensus does not support 'producer' - 'internal' should still be used
- Send: 'client' kind (was 'producer')
- Processing: 'consumer' kind (was 'server'), OpenCensus should continue using 'server' 

This complies with [OpenTelemetry semantics](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#spankind) and helps backend tools understand they are dealing with async message processing and visualize it accordingly.

**Comment by kaerm** [comment]
thanks @lmolkova //cc: @mayurid

**Comment by lmazuel** [comment]
@lmolkova the way it's done in Python, EH doesn't know what plugin is running, so we can't really do "Consumer if OT, Server if OpenCensus"
What I can do is a hardcoded mapping for things that OpenCensus doesn't know. Right it's defined as:
```python
        kind = (
            OpenCensusSpanKind.CLIENT if value == SpanKind.CLIENT else
            OpenCensusSpanKind.CLIENT if value == SpanKind.PRODUCER else  # No producer in opencensus
            OpenCensusSpanKind.SERVER if value == SpanKind.SERVER else
            OpenCensusSpanKind.CLIENT if value == SpanKind.CONSUMER else  # No consumer in opencensus
            OpenCensusSpanKind.CLIENT if value == SpanKind.INTERNAL else  # No consumer in opencensus
            OpenCensusSpanKind.UNSPECIFIED if value == SpanKind.UNSPECIFIED else
            None
        )
```
Mostly, everything we don't know is mapped to OpenCensus CLIENT. What do you think?

**Comment by lmazuel** [comment]
See https://github.com/Azure/azure-sdk-for-python/pull/7624

**Comment by lmolkova** [comment]
@lmazuel 

thanks for the explanation.

I believe we should be using UNSPECIFIED for everything we don't know, but it's only relevant to INTERNAL. For producer/consumer, it;s fair to say they map pretty good to CLIENT/SERVER.

```python
kind = (
            OpenCensusSpanKind.CLIENT if value == SpanKind.CLIENT else
            OpenCensusSpanKind.CLIENT if value == SpanKind.PRODUCER else  # No producer in opencensus
            OpenCensusSpanKind.SERVER if value == SpanKind.SERVER else
            OpenCensusSpanKind.SERVER if value == SpanKind.CONSUMER else  # No consumer in opencensus
            OpenCensusSpanKind.UNSPECIFIED if value == SpanKind.INTERNAL else  # No internal in opencensus
            OpenCensusSpanKind.UNSPECIFIED if value == SpanKind.UNSPECIFIED else
            None
        )
```

**Comment by lmazuel** [comment]
@lmolkova thanks! I updated the mentionned PR in consequences.
