### ISSUE TITLE
Sample for Creating Virtual Network Gateway

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-sdk-for-python#910]
I am attempting to automate creating a Virtual Network Gateway using the Azure Python SDK.

I have run into an issue where I cannot figure out the correct way to format the Parameters to send over using the virtual_network_gateways.create_or_update:
```
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.network import NetworkManagementClient
nm_connection = NetworkManagementClient(credentials, subscription_id=’sub_id')

create_virtual_gw  = nm_connection.virtual_network_gateways.create_or_update(
    resource_group_name='RG', virtual_network_gateway_name=’vnet_gw', parameters=gw_params)
create_virtual_gw.wait()
```
The issue is the formatting of the parameters. I have tried many different ways and I am getting the following error:
“msrestazure.azure_exceptions.CloudError: Cannot parse the request.”

I tried looking through the documentation http://azure-sdk-for-python.readthedocs.io/ but it is not clear enough on the correct format for the virtual network gateway parameters. I also searched the Azure github, some other MS Azure Python resources, Internet searches, and have not be able to locate a detailed example of the correct way to format the parameters portion.

If you could please let me know the correct way to format the parameters that would be very helpful.

virtual_network_gateways.create_or_update function is at below link
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-network/azure/mgmt/network/operations/virtual_network_gateways_operations.py#L37

**Comment by lmazuel** [comment]
Hi @prashanthmadi 

I suggest you to follow the RTD tech doc [here](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.network.operations.html#azure.mgmt.network.operations.VirtualNetworkGatewaysOperations.create_or_update). You can click one type and see what is inside, what is required, etc.

For instance, I see that `parameters` should have at least `ip_configurations`, `gateway_type` and `vpn_type`; Since you didn't gave me your `gw_params`, I cannot try to guess what's wrong.

Anyway, you're right that there is no sample for VN Gateway. Please keep this issue opened till we have one. I add this in my backlog.

Thanks!

**Comment by prashanthmadi** [comment]
Hi @lmazuel 

Thanks for your help.. I forgot to include qw_params.. below is a sample..

```
gw_params = {
                 'location': 'eastus',
                'gateway_type': 'ExpressRoute',
    'sku': {'tier': 'Standard', 'capacity': 2, 'name': 'Standard'},
    'ip_configurations':[{'subnet': {'id': '/path/to/subnets/GatewaySubnet'}},
    {'public_ip_address': {'id': '/path/tp/Microsoft.Network/publicIPAddresses/pub_ip'}}
    ],
    'id': '/path/to/Microsoft.Network/virtualNetworkGateways/ vnet_gw',
}
````

**Comment by prashanthmadi** [comment]
Hi @lmazuel , did you got a chance to work on a sample for this

**Comment by lmazuel** [comment]
@prashanthmadi sorry for the late answer. your parameters are not correct:
- `ip_configurations` should have one element with two keys `subnet` and `public_ip_address`. This is not what currently the code is doing
- You miss `vpn_type`

Example:
```python
        gw_params = {
            'location': self.region,
            'gateway_type': 'ExpressRoute',
            'sku': {
                'tier': 'Standard',
                'capacity': 2,
                'name': 'Standard'},
            'ip_configurations':[{
                'subnet': {
                    'id': '/path/to/subnets/GatewaySubnet'
                },
                'public_ip_address': {
                    'id': '/path/tp/Microsoft.Network/publicIPAddresses/pub_ip'
                }
            }],
            'vpn_type': 'RouteBased'
        }
```

Please try to fix this first. Also, I used azure-mgmt-network 0.30.0 which is the recommended one currently.

**Comment by lmazuel** [comment]
FYI, working on your issue made me create this: https://github.com/Azure/azure-rest-api-specs/issues/818

**Comment by lmazuel** [comment]
I also discoverd that "name" is a required parameter (see issue referenced)

Example of parameters where I got an actual VN Gateway:
```python
        gw_params = {
            'location': self.region,
            'gateway_type': 'VPN',
            'vpn_type': 'RouteBased',
            'enable_bgp': False,
            'sku': {
                'tier': 'Standard',
                'capacity': 2,
                'name': 'Standard'},
            'ip_configurations':[{
                'name': 'default',
                'private_ip_allocation_method': 'Dynamic',
                'subnet': {
                    'id': gateway_subnet_info.id
                },
                'public_ip_address': {
                    'id': public_ip_address.id
                }
            }],
        }
```

**Comment by prashanthmadi** [comment]
Thanks @lmazuel

**Comment by lmazuel** [comment]
Hi @prashanthmadi 
I think we solved the issue, so I close it. Feel free to ask me to re-open it if I miss something important.

Thank you,
