### ISSUE TITLE
How to create ContainerInstanceManagementClient in Azure Function

### ISSUE THREAD

**Issue by briglx** [Azure/azure-sdk-for-python#9125]
I'd like to create a container from an Azure function using the python library. How can I create a ContainerInstanceManagementClient without uploading my credential file with my function?

**Comment by v-xuto** [comment]
This link is for your reference, there are some other methods here:
https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-cli

I tried method ”CLI-based authentication“ to create ContainerInstanceManagementClient.
I think "uploading my credential file" is probably the easiest way.

**Comment by v-xuto** [comment]
@jongio

**Comment by v-xuto** [comment]
Hi @briglx,
Follow [Authenticate with token credentials](https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-token):
Step 1, to create a service principal with the Azure CLI, use the following command:
```
az ad sp create-for-rbac --name ServicePrincipalName
```
Step 2, use following code to create ContainerInstanceManagementClient:
```
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.containerinstance import ContainerInstanceManagementClient

# Tenant ID for your Azure subscription
TENANT_ID = '<Your tenant ID>'
# Your service principal App ID
CLIENT = '<Your service principal ID>'
# Your service principal password
KEY = '<Your service principal password>'
credentials = ServicePrincipalCredentials(
    client_id = CLIENT,
    secret = KEY,
    tenant = TENANT_ID
)
subscription_id='<Your Subscription ID>'
client = ContainerInstanceManagementClient(credentials, subscription_id)
```

**Comment by v-xuto** [comment]
Hi @briglx,
How is this issue going? Feel free to let us know if further help is needed.

**Comment by tzhanl** [comment]
we are going to close this issue because we haven’t heard from you in a few days, but please re-open it if the issue still persists.
