### ISSUE TITLE
azure-devtools in pypi versus in this repo

### ISSUE THREAD

**Issue by omzevall** [Azure/azure-sdk-for-python#9127]
After a recent change (#9005), my team's pipelines starting failing with an import error complaining about NameInUseError (introduced in that change).

We figured out that the disconnect was that we were pip installing [azure-devtools==1.1.1](https://pypi.org/project/azure-devtools/), whose sources lives in the [azure-python-devtools](https://github.com/Azure/azure-python-devtools) repo.

But our tests also clone the [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python) repo and then "python install" azure-sdk-tools after copying over updated versions of mgmt_settings_real.py and testsettings_local.cfg. This led to a disconnect where KeyVaultPreparer was trying to import NameInUseError but was using the azure-devtools now in site-packages (which didn't have NameInUseError).

We fixed our issue by not pip installing azure-devtools and doing a "python install" from azure-sdk-for-python/tools/azure-devtools.

This raises a few questions:
1. Is azure-devtools in pypi going to be updated with the changes in this repo? The azure-python-devtools repo is inactive and it seems like forward development for azure-devtools is happening here instead.
2. Should the version number for tools/azure-devtools be updated to differentiate it from the pypi version? Both are reporting 1.1.1.

This is not urgent as our tests as passing again. But if anyone is still using pypi's azure-devtools, hopefully this helps.

Thank you.

**Comment by kaerm** [comment]
@omzevall thanks for reporting this, someone from our team will look into this //cc: @mayurid

**Comment by chlowell** [comment]
@lmazuel

**Comment by lmazuel** [comment]
Hi @omzevall 
To answer directly to your question
1. This repo now belongs to the Azure CLI team, our copy here is a "fork" in place
2. You're definitely right, even maybe rename the folder to be even more explicit. I assign this bug to me

**Comment by lmazuel** [comment]
We officially archived and deprecated "azure-devtools", and will merge soon the "azure-devtools" folder into internal tooling and make this name disapeared for good.
