### ISSUE TITLE
Onboard January releases on Docs

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-python#9151]
- [ ] Onboard the following packages on docs.microsoft.com
**Latest:**
azure-appconfiguration 1.0.0
azure-keyvault-certificates 4.0.0
azure-eventhub-checkpointstoreblob 1.0.0
azure-eventhub 5.0.0
azure-storage-file-datalake 12.0.0
**Preview:**
azure-ai-textanalytics 1.0.0b1
azure-cosmos 4.0.0
**Legacy:**
azure-eventhub 1.3.2

- [ ] Remove following packages from preview:
azure-cosmos 4.0.0b6
azure-appconfiguration 1.0.0b6
azure-storage-file-datalake 12.0.0b6
azure-keyvault-certificates 4.0.0b6
azure-eventhub-checkpointstoreblob 1.0.0b6
azure-eventhub 5.0.0b6

- [ ] Update GA versions if they are not pulling from latest for:
azure-keyvault-secrets 4.0.0
azure-keyvault-keys 4.0.0
azure-storage-file-share 12.0.0
azure-storage-blob 12.0.0
azure-storage-queue 12.0.0
azure-core 1.1.0
azure-identity 1.1.0

@mayurid to confirm version numbers

**Comment by scbedd** [comment]
All of these are completed, on validation, discovered that checkpointstore is still preview. Need to move to GA and off preview.
