### ISSUE TITLE
azure-storage-file-datalake - Authentication error getting access control.

### ISSUE THREAD

**Issue by KimShepherdVibrato** [Azure/azure-sdk-for-python#9159]
I have been getting the following error when attempting to read the access controls on a File System.

```
Traceback (most recent call last):
  File "/apps/agent/_work/3/source/venv/lib64/python3.6/site-packages/azure/storage/filedatalake/_path_client.py", line 364, in get_access_control
    return self._client.path.get_properties(**options)
  File "/apps/agent/_work/3/source/venv/lib64/python3.6/site-packages/azure/storage/filedatalake/_generated/operations/_path_operations.py", line 919, in get_properties
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.filedatalake._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/adls_gen2_acls.py", line 90, in <module>
    main()
  File "src/adls_gen2_acls.py", line 86, in main
    set_acls(account, spn_objectid)
  File "src/adls_gen2_acls.py", line 54, in set_acls
    current_permissions = directory_client.get_access_control()['acl']
  File "/apps/agent/_work/3/source/venv/lib64/python3.6/site-packages/azure/storage/filedatalake/_path_client.py", line 366, in get_access_control
    process_storage_error(error)
  File "/apps/agent/_work/3/source/venv/lib64/python3.6/site-packages/azure/storage/filedatalake/_deserialize.py", line 110, in process_storage_error
    raise error
azure.core.exceptions.ClientAuthenticationError: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
ErrorCode:AuthenticationFailed
```

I this worked fine on a DEV machine, but fails in the Pipeline.  We have narrowed it down to the version of the urllib3 library.

WORKING: urllib3==1.24.1
ERROR: urllib3==1.25.7

Code to replicate:
```
from azure.storage.filedatalake import DataLakeServiceClient

account_name = '<ACCOUNT NAME>'
account_key = '<ACCOUNT KEY>'

service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
        "https",
        account_name
    ), credential=account_key)

fs_paged = service_client.list_file_systems()
fs_list = list(fs_paged)
directory_client = service_client.get_directory_client(file_system=fs_list[0].name, directory=".")
current_permissions = directory_client.get_access_control()['acl']
print(current_permissions)
```

**Comment by kaerm** [comment]
Hi @KimShepherdVibrato thank you for reporting this, someone from our team will take a look at this //cc: @mayurid @rakshith91

**Comment by v-xuto** [comment]
Thanks for your report, I  reproduced the problem when urllib3 == 1.25.7
We can solve this problem by assigning a specific value to the parameter directory, such as：
```
directory_client = service_client.get_directory_client(file_system=fs_list[0].name, directory="testdir")
```
Because the type of the parameter directory is  'str'.

**Comment by xiafu-msft** [comment]
Hi @KimShepherdVibrato 
Thanks for reaching out! I was able to reproduce that. We will investigate that and get back to you, sorry about the inconvenience.

**Comment by antgonmir** [comment]
Any news on this? It has been three months since the issue was raised.
I am experiencing the same error running Python code from an Azure function and the latest stable (12.0.0) version of the azure-storage-file-datalake library.
I can mitigate the problem by pinning the urllib3 library version to 1.24.1, but this is definitely not ideal.

**Comment by xiafu-msft** [comment]
Hi @antgonmir 

Sorry about the inconvenience!
Would you like to use '/' to represent root directory as a workaround currently. I think that should work.

Feel free to let me know if that doesn't help!

**Comment by xiafu-msft** [comment]
So the conclusion for this issue is you should set directory="/" instead of directory="."

Feel free to reopen it if you have further questions!
