### ISSUE TITLE
Improve RequestIdPolicy with auto-generation

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#9163]
- Add “auto_request_id” to the policy `__init__` only. True by default. No support for this kwarg at the operation level
- Passing both auto_request_id and request_id to `__init__` raises a ValueError
- Auto-creation is done by `str(uuid.uuid1())`
- Passing “request_id=None” as operation kwargs means “don’t send this header, whatever auto-generation setting or fixed value at creation”. Empty string is acceptable way to say it as well.
- Passing “request_id=foo” as operation kwargs means “set header to foo, whatever auto-generation setting or fixed value at creation”

Tests should include the whole set of combination:
- `__init__` input could be request_id and/or auto_request_id (that's four combinations)
- on_request could take no request_id, or a "false" one (None or empty) or a value (three combinations).

**Comment by lmazuel** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/9170

**Comment by xiangyan99** [comment]
fixed
