### ISSUE TITLE
[EventHubs] Consumer should resume from last failed position when there is not checkpoint store

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#9166]
When there is no checkpoint store, in the eventhub processor, if a consumer fails and closed, a new consumer will be created, but it's still using the init position -- not the position where it failed.
This should be fixed.

**Comment by YijunXieMS** [comment]
The final decision is to resume from the checkpoint of an implicit in-memory checkpoint store if there is no checkpoint. Refer to issue #9226.
