### ISSUE TITLE
Create Additional "Debugging" Artifact on Builds

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#9168]
Right now, the debugging experience is limited to what you can see in stdout/stderr on the build agent window. 

We should additional attach:

- `tox` installation logs
- any additional caught exception information (if available)

Upload in an attached artifact of loose file artifacts.

**Comment by seankane-msft** [comment]
tox logs are in the `.tox/<env>/Logs` directory, grab them and upload as an artifact on failures
