### ISSUE TITLE
QueueClient documentation kwargs "encode_policy" should be "message_encode_policy"

### ISSUE THREAD

**Issue by KendallWeihe** [Azure/azure-sdk-for-python#9172]
Down a rabbit hole today because documentation was incorrect. [`QueueClient`](https://github.com/Azure/azure-sdk-for-python/blob/a0083a6baec418660180ed5cb838b269ce1f2d54/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L40) documentation defines the encoding/decoding policy kwarg keyword as [`encode_policy`](https://github.com/Azure/azure-sdk-for-python/blob/a0083a6baec418660180ed5cb838b269ce1f2d54/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L54) but is clearly [`message_encode_policy`](https://github.com/Azure/azure-sdk-for-python/blob/a0083a6baec418660180ed5cb838b269ce1f2d54/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L96). Same goes for the `decode_policy` in that same class `__init__`.

**Comment by kaerm** [comment]
@KendallWeihe thanks for the feedback, I am routing it for someone to take a look at this //cc: @mayurid @rakshith91

**Comment by xiafu-msft** [comment]
Hi @KendallWeihe 
Thanks so much for point that out, we will put this in our backlog and fix the doc in the next release

**Comment by annatisch** [comment]
Fix in PR #10031

**Comment by annatisch** [comment]
Fix merged :)
