### ISSUE TITLE
[EventHubs] The storage_blob_prefix in AzureStorageCheckpointLeaseManager does not take effect.

### ISSUE THREAD

**Issue by imeya** [Azure/azure-sdk-for-python#9180]
I'm using eph to receive event data as per this [link](https://github.com/Azure/azure-sdk-for-python/blob/eventhub_track1/sdk/eventhub/azure-eventhubs/examples/eph.py#L104). 

In the [AzureStorageCheckpointLeaseManager](https://github.com/Azure/azure-sdk-for-python/blob/eventhub_track1/sdk/eventhub/azure-eventhubs/examples/eph.py#L104), if I specify the parameter "storage_blob_prefix", it should create the checkpoint blob inside this specified "storage_blob_prefix". But actually, it will ignore the "storage_blob_prefix" I specified, and create the checkpoint blob directly inside the blob container.

This should be a bug, can you guys take a look at this? Thanks.

**Comment by kaerm** [comment]
@imeya thank you for reporting this, someone from our team will take a look at this //cc: @mayurid @yunhaoling

**Comment by yunhaoling** [comment]
Hello @imeya ,

We've noticed the issue and working on it right now: https://github.com/Azure/azure-sdk-for-python/pull/9086.
Will update you on this when the fix is out.

**Comment by KieranBrantnerMagee** [comment]
Hey folks, just chiming in:
Fix was merged per [this pr](https://github.com/Azure/azure-sdk-for-python/pull/9086)

As Adam aptly noted with the milestone tag, this will now be incorporated with our next track1 release.  @yunhaoling do you know offhand if this is fixed within T2?  If not I'll gladly take a look and follow up.

**Comment by KieranBrantnerMagee** [comment]
@YijunXieMS  kindly confirmed that now in T2 container is specifiable so this is implicitly solved.  Closing,  Thanks all!
