### ISSUE TITLE
NewConnectionError from face_client.face.detect_with_stream

### ISSUE THREAD

**Issue by kouta-kun** [Azure/azure-sdk-for-python#9191]
Ubuntu 18.04 / Python 3.6.9
I get the following exception
`urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f722c8d2ef0>: Failed to establish a new connection: [Errno -2] Name or service not known`

It happens once in a while, although not deterministically and I haven't been able to pin down conditions for it, other than it's always when calling `face_client.face.detect_with_stream(image=bio,
                                            return_face_id=True,
                                            recognition_model="recognition_02",
                                            return_face_attributes=['age', 'gender'])`

**Comment by SaurabhSharma-MSFT** [comment]
@kouta-kun Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by kouta-kun** [comment]
Hi! We're actually not using Azure anymore, and this was part of - although not the only reason - why.
