### ISSUE TITLE
Update docs to reflect that clients are tested with Python 3.8

### ISSUE THREAD

**Issue by estensen** [Azure/azure-sdk-for-python#9205]
According to the [pipeline](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/pipelines/templates/jobs/archetype-sdk-client.yml) the client is tested with Python 3.8, but this is not reflected in the [docs](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cosmos/azure-mgmt-cosmosdb) yet.

**Comment by lmazuel** [comment]
Hi @estensen 
Thanks for the report! I updated our templating system (see PR attached), so next release will declare 3.8 correctly (template are applied at release time, so it won't change until the next release, but that's matching what is actually on PyPI).
Thanks again!
