### ISSUE TITLE
Accessing environment variables when not debugging

### ISSUE THREAD

**Issue by pjjohnson** [Azure/azure-sdk-for-python#9207]
Python 3.8.0 (venv), VS Code 1.41.0, python-dotenv 0.10.3

Still learning Python…running my Python code without debugging, I did the following to set the expected environment variables required by DefaultAzureCredential():

import envvars
import os
os.environ['AZURE_TENANT_ID'] = envvars.AZURE_TENANT_ID
os.environ['AZURE_CLIENT_ID'] = envvars.AZURE_CLIENT_ID
os.environ['AZURE_CLIENT_SECRET'] = envvars.AZURE_CLIENT_SECRET
os.environ['AZURE_SUBSCRIPTION_ID'] = envvars.AZURE_SUBSCRIPTION_ID
os.environ['VAULT_URL'] = envvars.VAULT_URL

This code is a snippet for some Azure Key Vault work I am doing.  envvars.py contains my variable definitions (VAR_NAME='some value').  What is the best way to access environment variables when not debugging?

It was suggested I use ClientSecretCredential() instead; however, that doesn't resolve this pattern for environment variables.  

As for dotenv, I did create a .env file and I've installed python-dotenv, but it's unclear how I actually instantiate access to the .env file.  The examples show "from dotenv import load_dotenv", but the reference to "dotenv" is not resolved even though python-dotenv shows in "pip list".

**Comment by lmazuel** [comment]
Hi @pjjohnson 
Env variables is not a Python concept, you do not set env variables from inside your program, you set them on your system. I humbly think you you might need to read about this first, this is an example for Windows:
https://www.digitalcitizen.life/simple-questions-what-are-environment-variables

Once you have your env variables set at the system level, there is no code to write in Python, since the DefaultAzureCredential() will directly ask the system for the correct values for you.

If you don't want to use env variables finally, you can create directly an instance of authentication with code like this:
```python
credentials = ClientSecretCredential(
   tenant_id="my tenant id",
   client_id="my client id"
   client_secret="my client secret"
)
```

**Comment by lmazuel** [comment]
About dotenv, it could actually avoid having to set them in the system indeed, but that's a dotenv question, their front page give doc about that:
https://pypi.org/project/python-dotenv/

A simple example:
.env file:
```
AZURE_CLIENTSECRET="secret"
```
test.py
```python
import os

from dotenv import load_dotenv
load_dotenv()

print(os.getenv("AZURE_CLIENTSECRET"))
```

**Comment by pjjohnson** [comment]
I was able to get dotenv working, and I changed the code to the following:

load_dotenv()
credential = DefaultAzureCredential()
secret_client = SecretClient(vault_url=os.environ['VAULT_URL'], credential=credential)
key_client = KeyClient(vault_url=os.environ['VAULT_URL'], credential=credential)
mgmt_client = KeyVaultManagementClient(credential, os.environ['AZURE_SUBSCRIPTION_ID'])

I'll .gitignore the .env file to ensure my secrets/etc. aren't pushed to the repo.  How this reflects in running Python in an Azure AppService will be a new twist for me.

**Comment by lmazuel** [comment]
I'm glad I was helpful, I'm closing this issue since we answered the main question.

I would suggest you enable MSI on AppService, that DefaultAzureCredential will connect to automatically:
https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity
