### ISSUE TITLE
Disassociate NSG from a interface 

### ISSUE THREAD

**Issue by ajay15283** [Azure/azure-sdk-for-python#9217]
Hello All,

Is there a way to disassociate NSG from a interface using python SDK ?

**Comment by v-xuto** [comment]
Hi @ajay15283,
Here are the steps to disassociate NSG from a interface：
Step 1, create a Network Management Client Object.
Step 2, get public_ip_obj, nsg_obj and subnet_obj.
Step 3, configure network interface parameters. The most important thing, the value of the parameter network_security_group is None for disassociation.
Step 4, use method create_or_update to update network interface configuration.

The detailed code is shown below about disassociate NSG from an interface:
```
from azure.mgmt.network import NetworkManagementClient
from azure.common.credentials import ServicePrincipalCredentials

GROUP_NAME = 'ResourceGroupName'  
NSG_NAME = 'NetworkSecurityGroupName'  
INC_NAME = 'NetworkInterfaceName'  
subscription_id='<Your Subscription ID>'
credentials = ServicePrincipalCredentials(
   client_id='<Your service principal App ID>',
   secret='<Your service principal password>',
   tenant='<Your tenant ID>'
)
# Step 1, create a Network Management Client Object.
network_client = NetworkManagementClient(credentials, subscription_id)
# Step 2, get public_ip_obj,nsg_obj and subnet_obj.
public_ip_obj = network_client.public_ip_addresses.get(resource_group_name=GROUP_NAME,public_ip_address_name='PublicIpAddressName')
nsg_obj = network_client.network_security_groups.get(resource_group_name=GROUP_NAME,network_security_group_name=NSG_NAME)
subnet_obj = network_client.subnets.get(resource_group_name=GROUP_NAME, virtual_network_name='VirtualNetworkName',
                                    subnet_name='default')
# Step 3, configure network interface parameters.
params = {'location': 'EastUS',
            'ip_configurations': [
               {
                  'name': 'ip_configuration_name',
                  'subnet': {'id': subnet_obj.id},
                  'public_ip_address': {'id': public_ip_obj.id},
               }
            ],
            # None: Disassociate;  nsg_obj.id: Associate with the specified nsg object representative
            # 'network_security_group': {'id': nsg_obj.id}
            'network_security_group': None
            }
# Step 4, use method create_or_update to update network interface configuration.
network_client.network_interfaces.create_or_update(
   resource_group_name=GROUP_NAME,
   network_interface_name=INC_NAME,
   parameters=params)
```
@jongio

**Comment by allegradomel** [comment]
#please-close

**Comment by ajay15283** [comment]
> Hi @ajay15283,
> Here are the steps to disassociate NSG from a interface：
> Step 1, create a Network Management Client Object.
> Step 2, get public_ip_obj, nsg_obj and subnet_obj.
> Step 3, configure network interface parameters. The most important thing, the value of the parameter network_security_group is None for disassociation.
> Step 4, use method create_or_update to update network interface configuration.
> 
> The detailed code is shown below about disassociate NSG from an interface:
> 
> ```
> from azure.mgmt.network import NetworkManagementClient
> from azure.common.credentials import ServicePrincipalCredentials
> 
> GROUP_NAME = 'ResourceGroupName'  
> NSG_NAME = 'NetworkSecurityGroupName'  
> INC_NAME = 'NetworkInterfaceName'  
> subscription_id='<Your Subscription ID>'
> credentials = ServicePrincipalCredentials(
>    client_id='<Your service principal App ID>',
>    secret='<Your service principal password>',
>    tenant='<Your tenant ID>'
> )
> # Step 1, create a Network Management Client Object.
> network_client = NetworkManagementClient(credentials, subscription_id)
> # Step 2, get public_ip_obj,nsg_obj and subnet_obj.
> public_ip_obj = network_client.public_ip_addresses.get(resource_group_name=GROUP_NAME,public_ip_address_name='PublicIpAddressName')
> nsg_obj = network_client.network_security_groups.get(resource_group_name=GROUP_NAME,network_security_group_name=NSG_NAME)
> subnet_obj = network_client.subnets.get(resource_group_name=GROUP_NAME, virtual_network_name='VirtualNetworkName',
>                                     subnet_name='default')
> # Step 3, configure network interface parameters.
> params = {'location': 'Location',
>             'ip_configurations': [
>                {
>                   'name': 'ip_configuration_name',
>                   'subnet': {'id': subnet_obj.id},
>                   'public_ip_address': {'id': public_ip_obj.id},
>                }
>             ],
>             # None: Disassociate;  nsg_obj.id: Associate with the specified nsg object representative
>             # 'network_security_group': {'id': nsg_obj.id}
>             'network_security_group': None
>             }
> # Step 4, use method create_or_update to update network interface configuration.
> network_client.network_interfaces.create_or_update(
>    resource_group_name=GROUP_NAME,
>    network_interface_name=INC_NAME,
>    parameters=params)
> ```
> 
> @jongio

Thanks a lot for you help
