### ISSUE TITLE
[Event Hubs] Use IoT connection string to connect to event hub to consume events

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#9224]
Redirect the IoT connection string to the built-in endpoint and rebuild the connection to the built-in endpoint.
To be clarified with service team.

**Comment by ramya-rao-a** [comment]
There are no plans at the moment to provide the support from the Event Hubs package to take in an IotHub connection string. For any customers wanting this feature, please refer to the sample that shows how to [convert an IotHub connection string to an Event Hub compatible connection string](https://github.com/Azure-Samples/azure-iot-samples-python/tree/master/iot-hub/Quickstarts/read-d2c-messages) and then use it with the Event Hubs package
