### ISSUE TITLE
Outdate HISTORY.md for servicebus 

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-sdk-for-python#9227]
It seems that

azure-sdk-for-python/sdk/servicebus/azure-servicebus/HISTORY.rst

has not been updated with info about the latests 0.50.2 release.

**Comment by yunhaoling** [comment]
Hello @andreacassioli ,

Please take a look at the changelog here: https://github.com/Azure/azure-sdk-for-python/blob/release/servicebus-v1/sdk/servicebus/azure-servicebus/HISTORY.rst

**Comment by KieranBrantnerMagee** [comment]
This appears to be corrected in the current [CHANGELOG.md](https://github.com/Azure/azure-sdk-for-python/blob/servicebus_v0.50.2/sdk/servicebus/azure-servicebus/CHANGELOG.md) (HISTORY.rst was renamed to conform with repo standards), if I'm eliding some details that should have been present in the 0.50.2 entry don't hesitate to reopen this/give me a shout.

Thanks as always!
