### ISSUE TITLE
servicebus delivery count?

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-sdk-for-python#9228]
Hi,
I am upgrading to the new servicebus client `0.50.2`. In the old message object I could do

```
    # retrieve delivery-count from message
    delivery_count = message.broker_properties['DeliveryCount']
    logging.info(f'Message delivery count: {delivery_count}/{MAX_DELIVERY_COUNT}')
```

In the new version I cannot find any mention on "delivery count". Is that available somehow?

**Comment by kaerm** [comment]
Hi @andreacassioli thanks for reaching out to us. Someone from our team will take a look at this //cc: @mayurid

**Comment by v-xuto** [comment]
There are two differernt Message classes in servicebus client 0.50.2:
1. from azure.servicebus.control_client import Message
     This message in path: servicebus\control_client\models.py
     In this message class, it has propertie: message.broker_properties['DeliveryCount']
2. from azure.servicebus import Message
     This message in path: servicebus\common\message.py
     In this message class, it don't have propertie: message.broker_properties['DeliveryCount']

Which message class are you using?

**Comment by v-xuto** [comment]
@jongio

**Comment by andreacassioli** [comment]
Hi @v-xuto,
I am looking at the `Message` class in the `common` module. My old implementation uses the `control_client` version.

**Comment by v-xuto** [comment]
Why don't you continue to use control_client version?

**Comment by andreacassioli** [comment]
A number of reasons:

- use autolock renew
- hopefully experience better performance and less connection reset issues
- move to async 

Anyway, is the lack of delivery count a design choice?

**Comment by andreacassioli** [comment]
Any more feed back?

**Comment by yunhaoling** [comment]
Hello @andreacassioli , sorry for the delay.

The ServiceBus `Message` has a member called `header`: https://github.com/Azure/azure-sdk-for-python/blob/3f32d00a5f9abe7d9d84d9696cf8d8d7c9e59c2f/sdk/servicebus/azure-servicebus/azure/servicebus/common/message.py#L58

which is a `MessageHeader` object defined in the uamqp library, and contains `delivery_count` info:
https://github.com/Azure/azure-uamqp-python/blob/master/uamqp/message.py#L1031-L1080

I think what's you're looking for. This means to access the `delivery_count` inside the message, the code would be `message.header.delivery_count`.

Please take a try and let me know if this solves your problem or not.

**Comment by andreacassioli** [comment]
@yunhaoling Thanks works!

Just one note: the counter seems to be set to `None` instead of zero, so it goes `None, 1, 2, 3...`. Is it by design?

Is there a documentation for the header? I could not find any.

**Comment by annatisch** [comment]
Hi @andreacassioli - I believe the reason for this is that the message header doesn't include this field until its value is 1 or higher - so the deserilzation logic interprets this as None rather than 0.

We should give this value a sensible default - thanks for bringing it to our attention! :)

**Comment by andreacassioli** [comment]
@annatisch shall I create a separate issue for counter?

**Comment by KieranBrantnerMagee** [comment]
Hey @andreacassioli go ahead and create a separate issue with counter, as Anna asserted above this is something we'll have to triage in the REST deserialization.

We can move on this issue as improving Documentation to clarify the header behavior.

Echoing Anna's thanks for your time and effort.

**Comment by KieranBrantnerMagee** [comment]
Thanks for creating the other issue Andrea, (and for your time/patience as we looked into this!)

We'll be closing this out and will pick up work on that topic in that chain to keep the work encapsulated.
