### ISSUE TITLE
azure core needs to honor "retry-after-ms"

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#9240]

**Comment by lmazuel** [comment]
Could you precise your issue? Is this RetryPolicy, etc.
Usually variables like that are called "retry-after" and designed as float, so ms are possible.

**Comment by xiangyan99** [comment]
In our retry policy, we only parse "Retry-After" in the response header.

AppConfig uses "retry-after-ms" for the retry-after setting in their response and we want to honor this as well.

https://github.com/Azure/AppConfiguration/blob/master/docs/REST/throttling.md

**Comment by xiangyan99** [comment]
fixed
