### ISSUE TITLE
404 for link from Bing Image Search

### ISSUE THREAD

**Issue by wiazur** [Azure/azure-sdk-for-python#9261]
This link doesn't work:
https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-search-imagesearch/%5Bhttps://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference?view=azure-python#market-codes%5D(https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#market-codes)

It's from the Market Codes link, as described in the `search()` API call. Located under an optional parameter called `market`:
https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-search-imagesearch/azure.cognitiveservices.search.imagesearch.operations.imagesoperations?view=azure-python#search-query--accept-language-none--user-agent-none--client-id-none--client-ip-none--location-none--aspect-none--color-none--country-code-none--count-none--freshness-none--height-none--id-none--image-content-none--image-type-none--license-none--market-none--max-file-size-none--max-height-none--max-width-none--min-file-size-none--min-height-none--min-width-none--offset-none--safe-search-none--size-none--set-lang-none--width-none--custom-headers-none--raw-false----operation-config-

Here is the correct link:
https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-images-api-v7-reference#market-codes

**Comment by lmazuel** [comment]
Den @docs-product thee Python code contains correct MD link, but I guess the system is processing them as RST and creates the trouble? Thoughts?

**Comment by lmazuel** [comment]
This was unfortunately not addressed in time before the links went to 404 :(. Closing the issue.
