### ISSUE TITLE
Support for request batching via /batch endpoint?

### ISSUE THREAD

**Issue by nitzmahone** [Azure/azure-sdk-for-python#9271]
After seeing how the portal batch-fetches VM `instanceView`s for PowerState so quickly via the `/batch` endpoint, I hacked together a batched version of `instance_view()` on `ComputeManagementClient`. I couldn't find any docs about the batch endpoint though (complicated by the prevalence of docs for the Batch service)..

Is `/batch` actually supported, and if so, any chance for "official" support for batched operations via msrestazure and/or the Python SDK? The bulk VM instanceView fetch is the only thing I can think of right now that I'd need it for, but there are probably plenty of other things out there too...

cc @lmazuel

**Comment by xiangyan99** [comment]
@ifeoluwaokunoren any update on this issue?
