### ISSUE TITLE
Failure to upload to devops feed is not cleaning up stale file

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#9286]
Upload to devops feed failed due to service not available error but a stale file was already created in devops feed. When upload was reattempted, it found a file with same name in devops feed and failed.

Ideally we should cleanup any existing file with same name if it is present before reattempting to upload.

-----------------------------------------------------------------------------------------------------------------
Error logs
-----------------------------------------------------------------------------------------------------------------
Uploading azure-mgmt-sql-0.16.0.zip

  0%|          | 0.00/407k [00:00<?, ?B/s]
100%|██████████| 407k/407k [00:04<00:00, 91.0kB/s]
Received "503: Service Unavailable" Package upload appears to have failed.  Retry 1 of 5
Uploading azure-mgmt-sql-0.16.0.zip

  0%|          | 0.00/407k [00:00<?, ?B/s]
100%|██████████| 407k/407k [00:00<00:00, 1.66MB/s]
NOTE: Try --verbose to see response content.
HTTPError: 409 Client Error: Conflict - The feed 'azure-sdk-221745' already contains file 'azure-mgmt-sql-0.16.0.zip' in package 'azure-mgmt-sql 0.16.0'.

**Comment by weshaggard** [comment]
@praveenkuttappan DevOps feeds are immutable after you upload a package to them so we cannot delete them. I think in the failure case we may not have any choice but to abandon that package upload. What case is this failure is it for a dev build? I don't see a dev version in your example.

**Comment by praveenkuttappan** [comment]
Discussed this issue with Wes. This reported failure is during upload to boiler plate feed and bigger  question now is whether we need to upload to this feed during scheduled CI

**Comment by weshaggard** [comment]
@praveenkuttappan the DevOps feed publishing issue may be related to https://github.com/Azure/azure-sdk/issues/1048.

**Comment by praveenkuttappan** [comment]
Closing this issue. Fix has been done in Azure/azure-sdk#1048 to handle burner feed availability.
