### ISSUE TITLE
Network failure on BlobClientService | ContainerService causes hanging

### ISSUE THREAD

**Issue by KraGiE** [Azure/azure-sdk-for-python#9291]
I'm running an app that opens every single file in a container to check it's contents, and it runs well for the most part.  However, it will hang indefinitely when there's a network error. 

Entry point:
```python
service_client = BlobServiceClient.from_connection_string(self.connection_string)
self.client = service_client.get_container_client(container_name)
self.client.download_blob(source).content_as_text()
```

Taken from the samples so source is the filename of the blob being downloaded.

```python
  File "/myapp/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/myapp/lib/python3.6/site-packages/azure/storage/blob/_shared/policies.py", line 517, in send
    response = self.next.send(request)
  File "/myapp/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/myapp/lib/python3.6/site-packages/azure/storage/blob/_shared/policies.py", line 318, in send
    response = self.next.send(request)
  File "/myapp/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/myapp/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/myapp/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 112, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/myapp/lib/python3.6/site-packages/azure/storage/blob/_shared/base_client.py", line 295, in send
    return self._transport.send(request, **kwargs)
  File "/myapp/lib/python3.6/site-packages/azure/storage/blob/_shared/base_client.py", line 295, in send
    return self._transport.send(request, **kwargs)
  File "/myapp/lib/python3.6/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 248, in send
    **kwargs)
  File "/myapp/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/myapp/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/myapp/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/myapp/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/myapp/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/myapp/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
```

![Screenshot at Dec 31 23-05-21](https://user-images.githubusercontent.com/5402972/71638946-0dc8e000-2c22-11ea-8599-c07c7c0e4f6c.png)

I've ran this a few times, and it will hang every couple hours.  I understand network issues happen (doesn't happen this much with AWS, but that's a different subject).  The app should raise an exception rather than hang indefinitely.

**Comment by cbcoutinho** [comment]
I have this same error, and it seems that the 'timeout' and 'connection_timeout' kwargs are not respected when downloading/uploading blobs to a storage account.

I have azure-storage-blob v12.3.0

I would expect the following snippet to timeout (based on my reading of (the source)[https://github.com/Azure/azure-sdk-for-python/blob/8f4553893913217673156e7c78a9c42a539ff684/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py#L267-L293]):

```python
connection_string = ...
blob_client = BlobServiceClient.from_connection_string(connection_string)
blob_client.get_service_properties(timeout=1)
```

But it just hangs indefinitely if there is a network issue

**Comment by cbcoutinho** [comment]
After further digging, it seems like timeout parameter is not used when making a request, although the option is available

In the `requests` documentation they even state that:
- it's possible to set timeouts [link](https://2.python-requests.org/en/master/user/quickstart/#timeouts_
- You can specify both a connection timeout and a read timeout [link](https://2.python-requests.org/en/master/user/advanced/#timeouts)

And it appears that the `RequestsTransport` gets these connection/read timeout values from a configuration [link to source](https://github.com/Azure/azure-sdk-for-python/blob/497cff4f0019d1e9188479f493c02f8d3d43d5bf/sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py#L231-L285), but I'm not able to set them when initiating a `BlobServiceClient`, or when I'm using any of the class methods like `get_service_properties`.

How do I set these timeout values?

**Comment by davidt99** [comment]
Not sure who's responsible for prioritizing this issue but we had to revert to the old drive, this is a blocker for us.

**Comment by xiafu-msft** [comment]
Hi @cbcoutinho and @davidt99 

Sorry for the late response...
you can specify read_timeout and connection_timeout parameters when initiating ServiceClient, BlobClient or ContainerClient and the value would be respected. You can also try to set retry_read=0 or retry_connect=0 https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/README.md#retry-policy-configuration so that your program will not hang there.

Let me know if that doesn't work!

**Comment by davidt99** [comment]
Will add these definitions and report back with the results.

**Comment by bakshienator77** [comment]
This didn't work for me. Honestly I am appalled that a mature cloud provider like azure doesn't have a proper requester-side timeout facility in it's SDK. In any case for anyone who is still stuck with this problem like I was I recommend [timeout_decorator](https://pypi.org/project/timeout-decorator/). Use it to wrap the function that tries to make the download from the blobclientservice. Remember to set an exception in the in the decorator and a try catch with your desired number of retries around your actual function call.

Cheers.

**Comment by xiafu-msft** [comment]
Hi @bakshienator77 
Do you mean this doesn't work for you?

> Hi @cbcoutinho and @davidt99
> 
> Sorry for the late response...
> you can specify read_timeout and connection_timeout parameters when initiating ServiceClient, BlobClient or ContainerClient and the value would be respected. You can also try to set retry_read=0 or retry_connect=0 https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/README.md#retry-policy-configuration so that your program will not hang there.
> 
> Let me know if that doesn't work!

**Comment by xiafu-msft** [comment]
we will close this issue currently since this issue wasn't updated. feel free to reopen or comment on this is you need.

**Comment by OleksandrSurkov** [comment]
retry_connect=0 solved it for me. Had similar issue when instantiating BlobServiceClient with purposefully wrong account url. It would freeze by default, tried timeout which didn't work, setting "retry_connect=0" worked fine and threw an error ("azure.core.exceptions.ServiceRequestError: <...>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed") when trying to connect with bad storage account. Thanks!
