### ISSUE TITLE
Figure out how best to deal with handshake timeout as seen in live tests

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#9298]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=222481&view=results

Could be catching and throwing a better message, could be adding a new exception to azure core exceptions

**Comment by chlowell** [comment]
Closing this because it's hard to investigate now that build has been deleted. It may have been addressed by #9716, which ensures HTTP errors in azure-keyvault-* always raise azure-core exception types.
