### ISSUE TITLE
[EventHubs] Receive mechanism should be consistent between sync & async

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#9303]
Currently the async consumer adds events to an internal queue then processes these post-connection work, whereas the sync consumer processes the events as they arrive.

The async implementation has the advantage that any errors that occur will be raised if for example, the received message bytes are corrupted. Whereas in the sync version those errors would be swallowed.

I think we should add the internal queue structure to the sync version as well.
This also seems to have performance benefits - running the Python callbacks from within the C context seems to slow things down.

**Comment by YijunXieMS** [comment]
This can be done together with supporting on_events (list of events)

**Comment by yunhaoling** [comment]
This is related to the issue: https://github.com/Azure/azure-sdk-for-python/issues/9184
