### ISSUE TITLE
[uamqp] async management call may return status 4xx and empty data

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#9306]
For the following code in EventHubs, sometimes (not very often) it doesn't raise an error but response.get_data() returns an empty dict (not None). When it happens, the status code is 4xx. We haven't seen this with the same call of sync.

```python
response = await mgmt_client.mgmt_request_async(
                    mgmt_msg,
                    constants.READ_OPERATION,
                    op_type=op_type,
                    status_code_field=b"status-code",
                    description_fields=b"status-description",
                )
```

Try with wrong credential

**Comment by yunhaoling** [comment]
Related issue: https://github.com/Azure/azure-sdk-for-python/issues/9303

**Comment by yunhaoling** [comment]
Investigation: There is almost no difference in sync and async mgmt request implementation in uamqp. From the code I would even conclude that what happens to the async one would happen to the sync one as well.

So probably the most efficient way to handle corner case I'm thinking of is to add checking in EH/SB library unless we can stably reproduce the issue.

------ ref

mgmt request sync impl:
https://github.com/Azure/azure-uamqp-python/blob/21e1a63108254251da2ece398c49d7b4ad9cff43/uamqp/mgmt_operation.py#L113-L132

mgmt request async impl:
https://github.com/Azure/azure-uamqp-python/blob/21e1a63108254251da2ece398c49d7b4ad9cff43/uamqp/async_ops/mgmt_operation_async.py#L88-L107

@YijunXieMS I'm closing it right now, we can reopen this one in the future if we reproduce the problem or we could create new work item for EH/SB to check mgmt request response.
