### ISSUE TITLE
[uamqp] Remove loop as a param

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#9307]
Python 3.10 asyncio will remove loop as a param in some functions. For instance, asyncio.sleep(), shield(), wait_for(), etc. Uamqp should remove them.
Python 3.8 asyncio has deprecated param loop in these functions.

**Comment by yunhaoling** [comment]
quick notes:

- if loop is positional, raise TypeError for 3.10
- we should find all the SB/EH public leaking places
  - positional argument
  - keyword argument
    - we have more flexibility if it's kwargs we could do docstring/logging stuff

**Comment by swathipil** [comment]
https://github.com/Azure/azure-uamqp-python/pull/261
