### ISSUE TITLE
Update storage configuration samples

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#9311]
Samples currently show configuring clients with internal APIs. For example, this one imports `create_configuration` from `_shared` and uses an underscored keyword argument:
https://github.com/Azure/azure-sdk-for-python/blob/39c3c4076dbe0ba68540df9969b1a08f83256d35/sdk/storage/azure-storage-blob/samples/blob_samples_proxy_configuration.py#L47-L55

**Comment by xiangyan99** [comment]
#21762

**Comment by tasherif-msft** [comment]
Resolved
