### ISSUE TITLE
App Service Plans Missing Number of Workers

### ISSUE THREAD

**Issue by steveharrington1** [Azure/azure-sdk-for-python#9312]
This issue was originally opened in the rest-api-specs repo [here](https://github.com/Azure/azure-rest-api-specs/issues/7990). Opening this here at the request of Azure Support - Request ID 120010224003515

The current model for app service plans is missing the number of workers. When I go to https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/list and try it, in the properties sent back, I have number of workers available. But this value is not in the sample response nor the definition of a Service Plan https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/list#appserviceplan. As such this has not made it over to the Python SDK.

Here is an example of one of the service plans I get back from the API above with some info redacted. Note that the "numberOfWorkers" field accurately displays the number of workers as 2. This is not the case when called from the Python SDK.

{
    "id": "<resource_id>",
    "name": "<name>",
    "type": "Microsoft.Web/serverfarms",
    "kind": "linux",
    "location": "Central US",
    "properties": {
        "serverFarmId": <server_farm_id>,
        "name": "<name>",
        "workerSize": "D1",
        "workerSizeId": 3,
        "workerTierName": null,
        "numberOfWorkers": 2,
        "currentWorkerSize": null,
        "currentWorkerSizeId": null,
        "currentNumberOfWorkers": null,
        "status": "Ready",
        "webSpace": "<web_space>",
        "subscription": null,
        "adminSiteName": null,
        "hostingEnvironment": null,
        "hostingEnvironmentProfile": null,
        "maximumNumberOfWorkers": 30,
        "planName": "<plan_name>",
        "adminRuntimeSiteName": null,
        "computeMode": "Shared",
        "siteMode": null,
        "geoRegion": "Central US",
        "perSiteScaling": null,
        "maximumElasticWorkerCount": null,
        "numberOfSites": 0,
        "hostingEnvironmentId": null,
        "isSpot": null,
        "spotExpirationTime": null,
        "freeOfferExpirationTime": null,
        "tags": null,
        "kind": "linux",
        "resourceGroup": "<resource_group>",
        "reserved": null,
        "isXenon": null,
        "hyperV": null,
        "mdmId": null,
        "targetWorkerCount": null,
        "targetWorkerSizeId": null,
        "provisioningState": null,
        "webSiteId": null,
        "existingServerFarmIds": null
    },
    "sku": {
        "name": "P1v2",
        "tier": "PremiumV2",
        "size": "P1v2",
        "family": "Pv2",
        "capacity": 2
    }
}

**Comment by nickzhums** [comment]
@steveharrington1 thanks for opening this issue. Looks like this issue needs help from the service team. We'll route to the appropriate person

**Comment by nickzhums** [comment]
@steveharrington1 Per investigation from service team, this is on their radar with high priority and we are working on resolving this issue. In the mean-time, if reverting to an older version of SDK is an option for you, you could try **0.43.1**

Let us know if you have other questions

**Comment by steveharrington1** [comment]
We have since implemented a workaround solution, but we'll reach out if we have see any issues once we get a chance to test it. Thanks!
