### ISSUE TITLE
Make the core testbase off-line ready

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#9324]
There is several tests that call httbin or bing, and they can't pass if there is no network. Need to find a way todo an actual HTTP request, with the less possible mock so we're confident it's working as expected.

I think I remember httpbin can be install locally, maybe that?

To investigate.

**Comment by bryevdv** [comment]
Maybe https://github.com/kevin1024/pytest-httpbin (which AFAICT is not the *actual* httpbin)?

**Comment by kristapratico** [comment]
Tests that need to be made offline:


**test_streaming.py**
- [ ] test_decompress_plain_no_header
- [ ] test_decompress_compressed_no_header
- [ ] test_compress_plain_header
- [ ] test_compress_compressed_header

**test_streaming_async.py**
- [ ] test_decompress_plain_no_header
- [ ] test_compress_plain_no_header
- [ ] test_decompress_compressed_no_header
- [ ] test_compress_compressed_no_header
- [ ] test_decompress_plain_header
- [ ] test_compress_plain_header
- [ ] test_decompress_compressed_header
- [ ] test_compress_compressed_header

**Comment by HimanshuBarak** [comment]
@kristapratico I would love to take these up one by one(or all together depending on the requirement). I have already started and raised this PR : https://github.com/Azure/azure-sdk-for-python/pull/33800 . I just need the reviewers feedback to make sure I am on the right track. If there is any feedback, I would be happy  to incorporate it in my next revisions.

**Comment by HimanshuBarak** [comment]
Hey @lmazuel  @kristapratico @iscai-msft  @xiangyan99 .hope it is going well.  I have updated https://github.com/Azure/azure-sdk-for-python/pull/33800 to add all the test cases needed to be made offline. Currently all my changes are in a single PR. If you want me to break into multiple PR's for each test I can do that as well. If the code is not par or some case is missing. I would be happy to fix it. I would really really appreciate any response/feedback  from your side. I really want to contribute to the azure sdk. and your feedback would really help me.

**Comment by HimanshuBarak** [comment]
Hey everyone any feedback on the PR #33800 ??

**Comment by kristapratico** [comment]
@HimanshuBarak thanks for your patience. Review feedback was left on the PR.

**Comment by kristapratico** [comment]
Completed in https://github.com/Azure/azure-sdk-for-python/pull/33800 and https://github.com/Azure/azure-sdk-for-python/pull/34247
