### ISSUE TITLE
Update IP address on existing NIC return IpConfigDeleteNotSupported Error

### ISSUE THREAD

**Issue by wjia7** [Azure/azure-sdk-for-python#9332]
Hi There,

I am currently trying to update an existing IP address on an existing network interface of a VM using python SDK. This can be easily done through the Azure interface.  However, I am having trouble with it at the moment through python SDK.

`        nic_params = {
            'location': LOCATION,
            'ip_configurations':[{
                'name': ip_address_object.name,
                'public_ip_address':ip_address_object,
                'subnet': {
                    'id': subnet_info.id
                }
            }]
        }`

`update_nic_result = network_client.network_interfaces.create_or_update(GROUP_NAME, nic.name, nic_params)`

I want to be clear that I only want to update the public_ip_address to a different ip_address_object that I have created. However, at the moment I am getting the following error.

`msrestazure.azure_exceptions.CloudError: Azure Error: IpConfigDeleteNotSupported
Message: IP Configuration ipconfig1 cannot be deleted. Deletion and renaming of the primary IP Configuration is not supported`

I have tried to remove the 'name' section from my nic_params. However, I am getting a different error on `InvalidRequestFormat`

What is the correct way to update only the public IP address for an existing network interface?

**Comment by v-xuto** [comment]
Hi @wjia7,
In nic_params, please udpate **"ip_address_object.name"** to **"ip_configuration_name"**  about the name of ip_configurations.

nic_params = { 'location': LOCATION, 'ip_configurations':[{ 'name': **ip_configuration_name**, 'public_ip_address':ip_address_object, 'subnet': { 'id': subnet_info.id } }] }

 Ip_address_object.name refers to the name of public_ip_address.

The picture below will help you distinguish between the two：
![NIC](https://user-images.githubusercontent.com/57166602/72057319-2b283900-3309-11ea-8787-fc5fad264163.png)
@jongio

**Comment by wjia7** [comment]
Thanks for the update. This problem is now resolved for me
