### ISSUE TITLE
Add support for FabricClient.HealthManager

### ISSUE THREAD

**Issue by tomkregenbild** [Azure/azure-sdk-for-python#938]
I want to run my application on Azure fabric and use a python script in order to monitor the health state of the cluster and nodes as described in this [document](https://github.com/Microsoft/azure-docs/blob/master/articles/service-fabric/service-fabric-view-entities-aggregated-health.md)

From what I see, this is not currently supported by the python sdk, can you add support to it? 
If it is already supported and I missed it can you link me to the documentation page?

**Comment by lmazuel** [comment]
Hi @tomkregenbild 

Not available yet indeed, however now Python SDKs are auto-generated from a RestAPI meta-description (Swagger) and Fabric is now available. It was not a priority currently, but if you're ok, I can generate a preview package so you can test it (this week). And I move this up in my backlog to provide sample/unittests asap.

What do you think?

**Comment by tomkregenbild** [comment]
It shounds great

**Comment by tomkregenbild** [comment]
@lmazuel 

I have tried installing the package on my windows machine but it is constantly failing with the following error:

`Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Python27\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Python27\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Python27\lib\site-packages\pip\wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "C:\Python27\lib\site-packages\pip\locations.py", line 142, in distutils_scheme
    i = d.get_command_obj('install', create=True)
  File "C:\Python27\lib\distutils\dist.py", line 856, in get_command_obj
    self._set_command_options(cmd_obj, options)
  File "C:\Python27\lib\distutils\dist.py", line 899, in _set_command_options
    % (source, command_name, option))
DistutilsOptionError: error in setup.cfg: command 'install' has no such option 'single_version_externally_managed'`

I tried reinstalling pip, python 2.7 and setup tools with latest versions but it seems to be consistent. 

I removed the "single_version_externally_managed" parameter in the setup.cfg and I was able to install it but I am not sure what are the implications.

After that I have tested the code snippet you provided and it worked perfectly on my test cluster that is not using authentication

**Comment by lmazuel** [comment]
Usually this error comes from old pip/setuptools, but you say that you installed the latest one, so I don't know right now. Anyway, it's no big deal, I might consider remove it myself, I think it was necessary at some point, but not anymore.

Good to hear it works! I keep this issue open until I publish something in PyPI. Hopefully next week.

**Comment by lmazuel** [comment]
Just for information if someone is trying this client while this issue is opened, I just removed the "credentials" parameters completely. So the sample is now:

```python
from azure.fabric import ServiceFabricClient 
client = azure.fabric.ServiceFabricClient(
    api_version='2.0',
    base_url='http://mycluster.westus.cloudapp.azure.com:19080',
)
cluster_health = client.cluster_healths.get()
assert cluster_health.aggregated_health_state == '1'
```

**Comment by lmazuel** [comment]
Hi @tomkregenbild 

The SF team released an official package:
https://pypi.python.org/pypi/azure-servicefabric

I didn't have a chance to look at. If you have the opportunity to check your scenario is covered, would be great. Otherwise, please do feedback hare that I can forward.
Thanks!

**Comment by lmazuel** [comment]
I close this issue due to inactivity, I have no reason to believe that the package made by the service team directly does not cover this scenario.
Thanks!
