### ISSUE TITLE
azure-identity requires aiohttp

### ISSUE THREAD

**Issue by Korijn** [Azure/azure-sdk-for-python#9397]
- **Package Name**: azure-identity
- **Package Version**: 1.1.0
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.6.8

**Describe the bug**
azure-identity appears to require aiohttp. if this is a required dependency, it is missing from install_requires in setup.py, because it isn't installed automatically by pip

**To Reproduce**
Create a virtualenv with the following packages:

```
azure-identity==1.1.0
azure-storage-blob==12.1.0
fastapi==0.46.0
uvicorn==0.11.1
```

Save the following code as `app.py` and run `uvicorn app:app` in the virtualenv. The error already occurs before the environment variables are consumed so no need to set them.

```
import os

from fastapi import FastAPI, HTTPException

app = FastAPI()


def get_blob_service_client(tenant_id, client_id, client_secret, storage_account_name):
    # ERROR:
    from azure.identity.aio import ClientSecretCredential

    token_credential = ClientSecretCredential(tenant_id, client_id, client_secret)

    oauth_url = "https://{}.blob.core.windows.net".format(storage_account_name)
    from azure.storage.blob.aio import BlobServiceClient

    return BlobServiceClient(account_url=oauth_url, credential=token_credential)


blob_service = get_blob_service_client(
    os.environ["TENANT_ID"],
    os.environ["CLIENT_ID"],
    os.environ["CLIENT_SECRET"],
    os.environ["ACCOUNT_NAME"],
)


@app.get("/")
async def read_root():
    return {"Hello": "World"}
```

Error:

```
Traceback (most recent call last):
  File "./app.py", line 10, in get_blob_service_client
    from azure.identity.aio import ClientSecretCredential
  File "/home/korijn/.local/share/virtualenvs/aiotest--vQHOsY--/home/korijn/.pyenv/shims/python/lib/python3.6/site-packages/azure/identity/aio/__init__.py", line 7, in <module>
    from ._credentials import (
  File "/home/korijn/.local/share/virtualenvs/aiotest--vQHOsY--/home/korijn/.pyenv/shims/python/lib/python3.6/site-packages/azure/identity/aio/_credentials/__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "/home/korijn/.local/share/virtualenvs/aiotest--vQHOsY--/home/korijn/.pyenv/shims/python/lib/python3.6/site-packages/azure/identity/aio/_credentials/authorization_code.py", line 9, in <module>
    from .._internal import AadClient
  File "/home/korijn/.local/share/virtualenvs/aiotest--vQHOsY--/home/korijn/.pyenv/shims/python/lib/python3.6/site-packages/azure/identity/aio/_internal/__init__.py", line 5, in <module>
    from .aad_client import AadClient
  File "/home/korijn/.local/share/virtualenvs/aiotest--vQHOsY--/home/korijn/.pyenv/shims/python/lib/python3.6/site-packages/azure/identity/aio/_internal/aad_client.py", line 12, in <module>
    from .msal_transport_adapter import MsalTransportAdapter
  File "/home/korijn/.local/share/virtualenvs/aiotest--vQHOsY--/home/korijn/.pyenv/shims/python/lib/python3.6/site-packages/azure/identity/aio/_internal/msal_transport_adapter.py", line 19, in <module>
    from azure.core.pipeline.transport import AioHttpTransport, HttpRequest
ImportError: cannot import name 'AioHttpTransport'
```

**Expected behavior**
Not to get an error or to have aiohttp installed automatically.

**Screenshots**
N/A

**Additional context**
Workaround is to install `aiohttp` manually.

**Comment by chlowell** [comment]
Thanks for opening this issue. The tacit aiohttp dependency is intentional across the SDK. We don't explicitly require it because the choice of async transport is optional, as is the entire async API--it's designed to be opt-in. The need to separately install an async transport is documented in readmes but the error message here isn't helpful; we can make it more so.

This is broader than azure-identity, so I've opened #9399 to track the work.

**Comment by Korijn** [comment]
Transport means HTTP client in this context, correct?

**Comment by Korijn** [comment]
I can't find this in the (root) readme, also. Are there other readme's?

**Comment by chlowell** [comment]
> Transport means HTTP client in this context, correct?

Yes, which in this case also includes the async implementation (e.g. Trio or asyncio).

> I can't find this in the (root) readme, also. Are there other readme's?

azure-identity documents it [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/README.md#async-credentials). Thanks for asking, I see the link there to azure-core docs is defunct (#9400). I also see it isn't documented for azure-storage-blob (#9401).

**Comment by Korijn** [comment]
Thanks for this!

> Yes, which in this case also includes the async implementation (e.g. Trio or asyncio).
 
For future readers: aiohttp requires asyncio, that's what is meant here, and also it is the right choice for fastapi since it uses asyncio as well.
