### ISSUE TITLE
Descriptive, actionable error message when async API is unavailable

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#9399]
When the async API is unavailable due to unsupported Python version, or lack of async transport, we should raise an error with a message describing the async API's requirements and linking to documentation. Currently it's just a `ImportError: cannot import name 'AioHttpTransport'`.

**Comment by xiangyan99** [comment]
#15878

**Comment by xiangyan99** [comment]
Fixed in #15878
