### ISSUE TITLE
[Event Hubs] OwnershipManager doesn't claim ownership if used with a single partition

### ISSUE THREAD

**Issue by omermizr** [Azure/azure-sdk-for-python#9415]
When using `EventHubConsumerClient` with a single partition id, ownership for that partition is not claimed. This logic is problematic since one can use multiple consumer clients, but still want to balance the ownerships (consider 2 containers running the same code).

**Comment by YijunXieMS** [comment]
@omermizr Thank you for trying the eventhub sdk and the suggestion. We'll look into this improvement.

**Comment by yunhaoling** [comment]
Hello @omermizr , thanks for raising the problem.

Let's get the scenario more concrete:

Suppose we have two `EventHubConsumerClient` instances and both of them have specified the partition_id `0', both of them will receive events from partition 0 independently.

So when you're saying **"but still want to balance the ownerships (consider 2 containers running the same code)"**, do you mean in this case only one of the `EventHubConsumerClient` should receive events from partition 0 -- and in your understanding, is `the ownership for a partition` equal to receiving exclusively?

Let me know whether my statements are correct and I'm open to this topic.

**Comment by omermizr** [comment]
Hey @yunhaoling,
Yes, basically (disregarding timeouts). I'll try to clarify:
Let's look at two scenarios:
1. Two`EventHubConsumerClient` instances, bot reading from all partitions simultaneously. One will start consuming events on partition '0', while the other will not (because he first one claimed ownership).
2. Two `EventHubConsumerClient` instances, bot reading from partition '0' simultaneously. Both will start consuming events on partition '0'.

My issue is that this behavior (as I understood it) is inconsistent.
Thank you for looking into this!

**Comment by yunhaoling** [comment]
Hi @omermizr ,thanks for sharing your understanding.

The concept of `ownership` comes into effect when `checkpoint_store` is provided.
With that saying, there are 4 kinds of situation:

1. Multiple `EventHubConsumerClient` instances/checkpoint_store/receive from all partitions
Clients would do load-balancing and try to claim equal amount of partitions.
e.g The eventhub has 8 partitions, there're 4 `EventHubConsumerClient` instances. Each client finally will pick up 2 partitions.

2. Multiple `EventHubConsumerClient` instances/checkpoint_store/receive from single same partition.
Only one client would pick up the partition. Others would fail to receive.

3. Multiple `EventHubConsumerClient` instances/receive from all partitions
Each client would claim all the partitions.

4. Multiple `EventHubConsumerClient` instances/receive from single partition
Each client would claim the partition.

Let me know your thoughts on this.

**Comment by omermizr** [comment]
Hi @yunhaoling, thank you for answering.
I'm interested in cases 1 & 2 (but yeah, I'd expect 3 & 4 to behave like you described).
Scenario 1 is indeed what I saw and expected.
In scenario 2, what guarantees the seconds consumer fails to receive? From the code it seems like all instances would receive...

**Comment by yunhaoling** [comment]
Hi @omermizr ,

When `checkpoint_store` is provided, we're creating exclusive connection to the target partition id. This is a feature support by the service side.

------ Some deeper about this is:

When `checkpoint_store` is provided, the sdk would set `owner_level` to an integer value (>=0) if it's not provided in the `receive` method.
When creating a connection to a specific partition, the service would check if the request contains `owner_level` info.

If the `owner_level` is not None and there is no existing connection to the  target connection, then service side creates an exclusive connection to the client.
If the `owner_level` is not None and there is already an existing exclusive connection, bigger `owner_level` dominates the connection, smaller/equal-value `owner_level` connection requests get rejected.

**Comment by omermizr** [comment]
@yunhaoling thank you so much!
I just looked at the code in `master` and I see the code that does this.
I'm currently running in production with versions `5.0.0b4` and `5.0.0b5`, and I guess that functionality wasn't implemented yet in those versions.
Seeing as this is exactly what I want, I'm closing this issue and will upgrade my package.
Thanks again!
