### ISSUE TITLE
Document how to download blob with asynchronous generator

### ISSUE THREAD

**Issue by Korijn** [Azure/azure-sdk-for-python#9419]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.1.0
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.6.8

**Describe the bug**
It's unclear how to download blob contents with an asynchronous generator. I want to use "streaming responses" in web frameworks such as starlette and they require an object that passes `inspect.isasyncgen`.

The `chunks()` method on `BlobClient` returns an asynchronous iterator that I've been able to convert as follows:

```
@app.get("/stream_test/{filename}")
async def stream_test(filename: str):
    blob_client = blob_service.get_blob_client(container="stream_test", blob=filename)
    blob = await blob_client.download_blob()

    async def chunks_generator():  # convert to async generator
        async for i in blob.chunks():
            yield i

    return StreamingResponse(chunks_generator())
```

But I get the feeling the azure-storage package probably has something built in for this scenario, I'm just having a lot of trouble identifying it in the documentation. Can you point me in the right direction?

**To Reproduce**
See above

**Expected behavior**
I would expect there to be a method that returns an asynchronous generator in the package, or documentation on how to acquire one.

**Comment by xiafu-msft** [comment]
Hi @Korijn 
Thanks for reaching out!
chunks() returns an async iterator instead of a generator, so the chunks_generator() need to be defined on your own if you need a generator.

Let me know if you have any concern or need any help.

**Comment by Korijn** [comment]
Well that makes sense but I feel like documenting that or providing a convenience function would be an improvement for your library. If you disagree feel free to close the issue.

**Comment by lmazuel** [comment]
Just looked a the doc of this operation, `chunks` has no doc, and no return type:
![image](https://user-images.githubusercontent.com/1050156/96321648-15981c00-0fcb-11eb-9b1f-e2dc2f0a1db4.png)

We should add a docstring in order to close this issue. thanks @Korijn for the feedback :)

**Comment by xiafu-msft** [comment]
the problem will be addressed by this pr

**Comment by xiafu-msft** [comment]
Close this issue for now, this fix will be available in the next release.
Let me know if you have any concern! Thanks again for your feedback!
