### ISSUE TITLE
Create SAS token without user delegation key

### ISSUE THREAD

**Issue by Korijn** [Azure/azure-sdk-for-python#9421]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.1.0
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.6.8

**Describe the bug**
To generate a blob SAS token I need to get a user delegation key since I'm authenticating to the storage service with client id/secret. User delegation keys expire, and this means I have to keep requesting new ones, adding overhead to my application. Is it possible to sign SAS tokens directly with client id/secret credentials?

**Comment by lmazuel** [comment]
@rakshith91 to the rescue

**Comment by xiafu-msft** [comment]
Hi @Korijn 
Thanks for reaching out!
I don't think you can use the application id/secret to sign the user delegation SAS.

Here is some info about user delegation SAS
`Every SAS is signed with a key. To create a user delegation SAS, you must first request a user delegation key, which is then used to sign the SAS. The user delegation key is analogous to the account key used to sign a service SAS or an account SAS, except that it relies on your Azure AD credentials. To request the user delegation key, call the Get User Delegation Key operation. You can then use the user delegation key to create the SAS.`

Here is the link of user delegation SAS doc https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas

Let me know if you need any help!

**Comment by Korijn** [comment]
OK, thanks for the info. I will learn to live with it! :)

**Comment by ericthomas1** [comment]
You can generate a SAS token using the Storage Account Key. 
- Put the Storage Account Key in Key Vault as a secret
- Then use the python sdk to create a KeyVault Client
- Get the secret
- Create a BlobService client with the key
- Generate SAS token from key + BlobServiceClient
