### ISSUE TITLE
Enable update management for a VM using python sdk

### ISSUE THREAD

**Issue by ajay15283** [Azure/azure-sdk-for-python#9424]
Requesting for python sdk module to enable update management for a VM using a existing log analytics and automation account 

I couldn't find any particular documentation related to this specific operation .Please let me know if we have options to enable update management using python sdk

**Comment by yossi-y** [comment]
Adding @msvijayn

**Comment by msvijayn** [comment]
Almost, there is complete support for the required steps from Azure Automation & Update Management as well as Log Analytics. But it seems dependent service like OperationsManagement  solutions, can be used only available in ARM and not in Python SDK. 

I am listing (summarising) below the usual steps for using Update Management via ARM template/API and its equivalent in Python SDK. 

**1. Creating Log Analytics Workspace**

- ARM: https://docs.microsoft.com/azure/templates/microsoft.operationalinsights/2015-11-01-preview/workspaces

- Python:  https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/loganalytics/azure-mgmt-loganalytics/azure/mgmt/loganalytics/operations/workspaces_operations.py

**2.  Creating Automation Account**
- ARM: https://docs.microsoft.com/azure/templates/microsoft.automation/2015-10-31/automationaccounts
- Python: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/automation_account_operations.py

**3. Linking Automation account & Log Analytics workspace**
- ARM: https://docs.microsoft.com/azure/templates/microsoft.operationalinsights/2015-11-01-preview/workspaces/linkedservices
- Python: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/loganalytics/azure-mgmt-loganalytics/azure/mgmt/loganalytics/operations/linked_services_operations.py

**4. Setup OMS/LA Solution like Update Management**
- ARM: https://docs.microsoft.com/azure/templates/microsoft.operationsmanagement/2015-11-01-preview/solutions
- Python: Not Available (to my knowledge)

**5. Onboard machine to a solution using VM extensions**
- ARM: https://docs.microsoft.com/azure/templates/microsoft.compute/2019-07-01/virtualmachines/extensions
- Python: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_virtual_machine_extensions_operations.py

**Comment by ajay15283** [comment]
Thanks for the details
