### ISSUE TITLE
Enable EventHub Parallel Unit Tests

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#9429]
[This PR](https://github.com/Azure/azure-sdk-for-python/pull/9428) makes the eventhubs CI build run the tox environments in serial. This is because when running in parallel mode, the vast majority of builds will hang running tests against `livetests/test_eventprocessor_async.py` 

We should be understanding why and come up with a resolution.

**Comment by YijunXieMS** [comment]
Re-enabled parallel run after fixing a problem in test_eventprocessor_async.py. The parallel works now.
