### ISSUE TITLE
Documentation Improvement  - Broker Properties ServiceBus

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-sdk-for-python#946]
What are the python types for the headers/Broker Properties?

I am referencing the types found at https://docs.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties

In particular what is the expected TimeSpan equivalent?

**Comment by lmazuel** [comment]
Hi @bearrito 
As the documentation you point says:

> One HTTP header named BrokerProperties contains all the BrokeredMessage headers. The properties are JSON-formatted. 

> For REST/HTTP, [...] TimeSpan types are converted to “total seconds.” 

I agree that there is no explicit documentation at http://azure-sdk-for-python.readthedocs.io/en/latest/servicebus.html, but the unit tests [here ](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/tests/test_servicebus_servicebus.py#L364)might help you at short term.

I keep this issue opened til I added a broker properties section to the documentation.

Thank you,

**Comment by lmazuel** [comment]
Updated: http://azure-sdk-for-python.readthedocs.io/en/latest/servicebus.html
Thank you for the feedback!
