### ISSUE TITLE
[AutoRest] Modernize Existing Pipelines - Build and Release

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#9481]
They're currently defined in the devdiv org. 

1. Not yml
2. Not under our org to make them visible

[Link to Existing Definition](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=8943)

**Comment by kurtzeborn** [comment]
Not sure who on AutoRest should follow up on this.  Since it's in the python repo, starting with you @lmazuel.  This may make more sense for Garrett or David to do.

**Comment by lmazuel** [comment]
I would assume @daviwil is interested too :)
