### ISSUE TITLE
[Event Hubs] Add perf test

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#9494]
**Is your feature request related to a problem? Please describe.**
Event Hubs service team built a stress test infrastructure years ago for .Net and Java. The SDK feature crew and engineering team will develop a new one for all four languages JS, Python, .Net and Java.

We have some command line scripts to do stress test in Python. It was used to do stress test and long running test for Event Hubs 5.0.0 release. They could be re-used.

Not much detailed information for now. To be elaborated.

**Comment by yunhaoling** [comment]
ping anna and mike for more context on the stress/perf framework being developed.
