### ISSUE TITLE
Cannot make a python connection to ADLS Gen2 storage with DeviceCodeCredential method

### ISSUE THREAD

**Issue by raxitsoni** [Azure/azure-sdk-for-python#9498]
Hi I am trying to connect to ADLS Gen2 storage account using one of DSVM with devicecodecredential method, below is the code running on Jupyter Notebook.

I have registed the app and authentication works fine, i get a access token however when i call to 
DataLakeServiceClient passign the credentials i get Unsupported Credentials error, I understand that python api are in public preview for adls gen2.  Can you let me know if whether Devecodecredntial works or not in adls gen2 and point me to sample code.

!pip install azure-storage-blob --pre --upgrade --user
!pip install azure-storage-file-datalake --pre --upgrade --user
!pip install azure-identity --pre --upgrade --user

import os, uuid, sys, adal, pandas
from azure.storage.filedatalake import DataLakeServiceClient

from azure.identity import DeviceCodeCredential
browsect = DeviceCodeCredential(appId, tenant_id = tenant)
creds = browsect.get_token()

try:  
    global service_client
        
    service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
        "https", "storage_account_name"), credential=creds)
    
except Exception as e:
    print(e)

I get below errror -
Unsupported credential: AccessToken(token='eyJ0eXAiOiJKV1QiLCJub25jZSI6Ik5CeUdUMlV3SkxGbWpvZlFZSnJvQjktZ3c1ZVVPcEtSLWd4dlRjT2UzRG8iLCJhbGciOiJSUzI1NiIsIng1dCI6InBpVmxsb1FEU01LeGgxbTJ5Z3FHU1ZkZ0ZwQSIsImtpZCI6InBpVmxsb1FEU01LeGgxbTJ5Z3FHU1ZkZ0ZwQSJ9

**Comment by chlowell** [comment]
I'm not familiar with ADLS in particular, but the pattern for clients accepting azure-identity credentials is to take instances of them as parameters. So, you give the client a credential, then it calls `get_token` as required. Adapting your example, it would look like this:
```py
from azure.storage.filedatalake import DataLakeServiceClient
from azure.identity import DeviceCodeCredential

browsect = DeviceCodeCredential(appId, tenant_id=tenant)
service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
    "https", "storage_account_name"), credential=browsect)
```
@xiafu-msft do we have a sample or documentation for this scenario?

**Comment by raxitsoni** [comment]
@chlowell  Thanks for the response, let me give a try.

**Comment by xiafu-msft** [comment]
@chlowell Thanks for your comment on this issue! I think that is the correct way to use DeviceCodeCredential, get_token is called internally in storage pipeline.
Currently we haven't added sample code. While we have test which could be used as a reference.
```
    def generate_oauth_token(self):
        from azure.identity import ClientSecretCredential

        return ClientSecretCredential(
            self.settings.ACTIVE_DIRECTORY_TENANT_ID,
            self.settings.ACTIVE_DIRECTORY_APPLICATION_ID,
            self.settings.ACTIVE_DIRECTORY_APPLICATION_SECRET,
        )
    def test_create_file_using_oauth_token_credential(self):
        # Arrange
        file_name = self._get_file_reference()
        token_credential = self.generate_oauth_token()

        # Create a directory to put the file under that
        file_client = DataLakeFileClient(self.dsc.url, self.file_system_name, file_name,
                                         credential=token_credential)

        response = file_client.create_file()

        # Assert
        self.assertIsNotNone(response)
```

**Comment by xiafu-msft** [comment]
It looks like you've got the answer, so we plan to close this issue for now, feel free to reopen it if you are still stuck or you have any other questions! ^_^
