### ISSUE TITLE
SyntaxWarning due to comparison of literals over using is

### ISSUE THREAD

**Issue by tirkarthi** [Azure/azure-sdk-for-python#9525]
- **Package Version**: master branch
- **Operating System**: Linux
- **Python Version**: 3.8

**Describe the bug**

`SyntaxWarning` over comparison of literals using `is`.

**To Reproduce**

Below is emitted while compiling all Python 3 files.

```
./sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py:115: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert len(scopes) is 1
./sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py:68: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert len(scopes) is 1
```

**Comment by chlowell** [comment]
Thanks for opening this issue. I opened a PR to replace these instances of 'is' with ==.

**Comment by tirkarthi** [comment]
Just in case I ran `find . -iname '*.py' | xargs -I{} python3.8 -Wall -m py_compile {}` to find this since it's a compile time warning.
