### ISSUE TITLE
Upload of sparse page blobs should make use of SEEK_HOLE/SEEK_DATA on Linux

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-sdk-for-python#9538]
**Is your feature request related to a problem? Please describe.**
A sparse disk image file of 1000GB that is empty will take a very long time to upload as the SDK is scanning the whole file for zeros.

**Describe the solution you'd like**
The SDK should be more clever and, if available on the OS, use [SEEK_HOLE/SEEK_DATA](https://lwn.net/Articles/440255/) as well to jump over unallocated blocks in the file. Since version 3.3, Python has [`os.SEEK_HOLE`/`os.SEEK_DATA`](https://docs.python.org/3/library/os.html#os.SEEK_END) (though note that Anaconda currently incorrectly doesn't define those attributes: https://github.com/ContinuumIO/anaconda-issues/issues/11679). 

**Describe alternatives you've considered**
None.

Page blob upload code: https://github.com/Azure/azure-sdk-for-python/blob/6350dcba7f10a81855d4e33a61aaf3873838293d/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py#L278

**Comment by kaerm** [comment]
Hi @letmaik thanks for the suggestion! Looping in some of my teammates to take a look at this //cc: @mayurid @rakshith91

**Comment by xiafu-msft** [comment]
Hi @letmaik 
Thanks for providing the thought to optimize our upload function, we will create an item in backlog to look into that

**Comment by letmaik** [comment]
@xiafu-msft Great, thanks. Do you have a rough estimate on when this improvement would land?

**Comment by tasherif-msft** [comment]
Hi @letmaik, I have picked up your ask from our backlog and will be looking into adding it to our SDK.
We're sorry this was left in our backlog for a while. I will update you once any changes are added to the SDK
