### ISSUE TITLE
Passing request_id=None as operation level should remove the header from the request

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#9545]

**Comment by xiangyan99** [comment]
Here is the logic
1. if there is a operation level input, use it (None means ignore req_id_policy)
2.if user sets the request_id in the policy (either in init or call set_req_id), use it (None means ignore. And as long as user sets it, we ignore auto_req_id)
3.if user never sets request_id and auto_req_id is True(True is default value), we generate auto_id
4.if user never sets request_id and set auto_req_id = False, no request id will be sent.

**Comment by xiangyan99** [comment]
Fixed in #9547 9547

**Comment by iscai-msft** [comment]
Released in 1.2.2
