### ISSUE TITLE
Keyword argument definitions are not rendering on docs.ms.com

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#9562]
- **Package Name**: azure-eventhub
- **Package Version**: 5.0.0
- **Operating System**: N/A
- **Python Version**: N/A

**Describe the bug**
See the following link. from_connection_string( ) doesn't list any params while they do have some.
https://review.docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub.aio.eventhubproducerclient?view=azure-python&branch=smoke-test#from-connection-string

This method is a class method. Not sure if this is the reason but could be a clue.
...aio.EventHubConsumerClient has the same issue.
The sync version (azure.eventhub.EventHubProducerClient) has no such problem.

**Comment by scbedd** [comment]
[Issue Filed](https://ceapex.visualstudio.com/Engineering/_workitems/edit/168574)

**Comment by scbedd** [comment]
This is a general issue, not specific to eventhub.

**Comment by scbedd** [comment]
Update to `sphinx-docfx-yaml` published to pypi. Merging output to `live` ASAP.
