### ISSUE TITLE
Track 2 SDKs should support PEP561 to enable mypy for customers

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#9572]
I just discovered that if a package is shipped using typing in comments annotation, it's actually ignored by mypy when used on a client code:
```shell
> mypy .\code.py
code.py:1: error: No library stub file for module 'azure.core'
code.py:1: note: (Stub files are from https://github.com/python/typeshed)
Found 1 error in 1 file (checked 1 source file)
```

To enable that scenario, we need to put a "py.typed" empty file at the root of the namespace, and mypy will then scan for comments annotations. The previous run now becomes:
```shell
> mypy .\code.py
Success: no issues found in 1 source file
```

Reference:
- [Mypy details](https://github.com/python/mypy/blob/master/docs/source/installed_packages.rst)
- [PEP561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)

**Comment by lmazuel** [comment]
azure-core done in https://github.com/Azure/azure-sdk-for-python/pull/9577

**Comment by xiangyan99** [comment]
Fixed azure-core in #9577

**Comment by xiangyan99** [comment]
Fixed azure.core in #9577

**Comment by kristapratico** [comment]
Just checked - text analytics, form recognizer, metrics advisor, and document translation have py.typed files

**Comment by seankane-msft** [comment]
Tables has a py.typed. [Container Registry](https://github.com/Azure/azure-sdk-for-python/issues/18321) and [AppConfiguration](https://github.com/Azure/azure-sdk-for-python/issues/18322) do not.

**Comment by rakshith91** [comment]
Eventgrid and monitor don't have a py.typed
https://github.com/Azure/azure-sdk-for-python/issues/18324
https://github.com/Azure/azure-sdk-for-python/issues/18323

**Comment by chlowell** [comment]
Identity doesn't have one: #18325

**Comment by yunhaoling** [comment]
EventHubs, ServiceBus, SchemaRegistry don't have a py.typed

https://github.com/Azure/azure-sdk-for-python/issues/18344
https://github.com/Azure/azure-sdk-for-python/issues/18323
https://github.com/Azure/azure-sdk-for-python/issues/18346
