### ISSUE TITLE
Invalid documentation and insufficient examples

### ISSUE THREAD

**Issue by vairamsvsjdo** [Azure/azure-sdk-for-python#9574]
- **Package Name**: azure-mgmt-recoveryservicesbackup
- **Package Version**: latest
- **Operating System**: all OS (windows and linux)
- **Python Version**:  3.7/2.7

**Describe the bug**
Invalid documentation and insufficient examples
> https://pypi.org/project/azure-mgmt-recoveryservicesbackup/
"Usage
For code examples, see Recovery Services Backup Management on docs.microsoft.com."
docs.microsoft.com does not have any code examples.

https://docs.microsoft.com/en-us/python/api/overview/azure/recovery-services-backup?view=azure-python

**To Reproduce**
1. https://docs.microsoft.com/en-us/python/api/overview/azure/recovery-services-backup?view=azure-python

**Expected behavior**
Examples are provided

**Screenshots**

**Additional context**

**Comment by kaerm** [comment]
Hi @vairamsvsjdo thanks for reporting this, someone will take a look into this //cc: @nickzhums

**Comment by pvrk** [comment]
Currently, we don't have ready-made samples to be uploaded in docs. We have to prepare them and upload. This is the first ask and hence I would treat as a feature request. If the Python SDK is used for CLI, then we have the CLI doc updated.

**Comment by pvrk** [comment]
We are following up with SDK teams on the appropriate place for examples. Post that I can provide an update.

**Comment by vairamsvsjdo** [comment]
First, the text says to look here for examples and it doesn't have one.
Two,  how one should use that API, no examples.

**Comment by pvrk** [comment]
We recently prepared few python samples and we will update the SDK documentation soon.

**Comment by pvrk** [comment]
Sincere apologies for the delay.

**Comment by mepand** [comment]
We could not make much progress on this due to some high priority items. But we are targeting to publish few samples in the coming month.
