### ISSUE TITLE
Resolve Testability Assumptions for source distributions

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#9594]
@chlowell asked a question earlier today that prompted some further discussion. Specifically, he wants to share test code between various `azure-keyvault` packages. To do this, my initial recommendation was to:

> place it in a folder called `azure-keyvault-tests` under `sdk/keyvault`, omit it from CI builds, and add it as a dev_requirement for your `azure-keyvault-*` packages

The response there was 

> Ok, but how do people successfully test the shipped sdist? We don't want to ship this shared test package. 

I didn't have an answer! As it stands _right now_:

1.  We don't ship `dev_requirements.txt` in our sdist.
2. We don't ship the adjusted `azure-devtools` from our repo. It's a hard dependency for most of our track 2 package tests.

So people are _already_ blocked from immediately testing the SDIST. 

What should we be doing here for testability of sdists?

**Comment by kurtzeborn** [comment]
@chlowell, there's a question here for you.  After we sort out a plan, we can figure out who should do the work.

**Comment by chlowell** [comment]
I talked this over with @lmazuel. We decided it's okay for our sdists not to be directly testable, at least until someone presents a compelling argument for making them so. In that event we could e.g. add unpublished test dependencies to sdists. The status quo is acceptable today, so I'm closing this. We can reopen when we decide work is needed here.
