### ISSUE TITLE
[FEATURE REQ] EventHub distributed tracing: stamp EventHubs info on message spans

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-python#9597]
**Is your feature request related to a problem? Please describe.**
Currently message spans do not have any information about event hub they are being sent to.
It could be discovered by following to the linked 'send' span which has attributes describing EventHubs and entity. So it is not a problem for human beings debugging single trace, but creates a a problem for analysis and visualization tools (such as Azure Monitor).
It is inefficient and hard to build aggregated views such as application map and analyze things like number of messages per send call without information about EventHubs on message. 

**Describe the solution you'd like**
stamp event hub properties on message spans:
 - `message_bus.destination`: EventHubs entity name
-  `peer.address`: Fully qualified EventHubs name such as `<name>.servicebus.windows.net/`

**Describe alternatives you've considered**
Discover relationships between message and and send span on monitoring tool backend to build aggregated views and metrics. It appears to be expensive (from querying perspective) and  contributes to bad performance showing up such views.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kaerm** [comment]
@lmolkova thanks for the request, someone from our team will take a look at this.

**Comment by YijunXieMS** [comment]
I see "message_bus.destination" and "peer.address" already in Event Hubs code. So we can close this issue.

```python
    def _add_span_request_attributes(self, span):
        span.add_attribute("component", "eventhubs")
        span.add_attribute("az.namespace", "Microsoft.EventHub")
        span.add_attribute("message_bus.destination", self._address.path)
        span.add_attribute("peer.address", self._address.hostname)
```
