### ISSUE TITLE
RateCard (meter_region) needs matching with Locations

### ISSUE THREAD

**Issue by nandexsp** [Azure/azure-sdk-for-python#9602]
Its important to find a way to match the regions from Pricing with the Locations from Compute to calculate the total costs. I can't find the way to compare it. 
When I receive from the API the billing request....

Reference : https://docs.microsoft.com/en-us/python/api/azure-mgmt-commerce/azure.mgmt.commerce.operations.ratecardoperations?view=azure-python#get-filter--custom-headers-none--raw-false----operation-config-

API Call: ﻿

```
from azure.mgmt.commerce import UsageManagementClient

UsageManagementClient(CREDENTIALS, SUBSCRIPTION).rate_card.get(
            "OfferDurableId eq 'MS-AZR-0003P' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'")
```

Return: 

```
{
'additional_properties': {}, 
'meter_id': 'adc70dbe-f428-40a5-8877-14c34e701de4', 
'meter_name': 'Archive Other Operations', 
'meter_category': 'Storage', 
'meter_sub_category': 'General Block Blob v2 Hierarchical\xa0Namespace', 
'unit': '10K', 
'meter_tags': [], 
'meter_region': 'US Central', 
'meter_rates': {'0': 0.0026}, 
'effective_date': datetime.datetime(2019, 8, 1, 0, 0, tzinfo=<isodate.tzinfo.Utc object at 0x7f26bdb58898>), 
'included_quantity': 0.0
}
```

**'meter_region': 'US Central',** 

I want to check this value with the locations to operate into the compute side: 

For example if I use List Locations: 

Article: https://docs.microsoft.com/en-us/python/api/azure-mgmt-subscription/azure.mgmt.subscription.operations.subscriptionsoperations?view=azure-python#list-locations-subscription-id--custom-headers-none--raw-false----operation-config-

API Call: 
```

from azure.mgmt.resource import ResourceManagementClient, SubscriptionClient
SubscriptionClient(CREDENTIALS).subscriptions.list_locations(SUBSCRIPTION)

```
RETURN: 

```
{
'additional_properties': {}, 
'id': '/subscriptions/e587120e-a70e-49bd-9598-e22c805553e3/locations/centralus', 
'subscription_id': None,
'name': 'centralus', 
'display_name': 'Central US',
 'latitude': '41.5908', 'longitude': '-93.6208'
}
```
There is a REST API or call from python for that??

Thanks ;)

**Comment by kaerm** [comment]
@nandexsp thank you for reaching out! Someone from our team will take a look at this

**Comment by dw511214992** [comment]
It seems a new request and needs help from Commerce Team's help.

**Comment by lilyjma** [comment]
Hi @qiaozha, could you please take a look at this issue?

**Comment by qiaozha** [comment]
@ms-premp Hi, Do you know why the  'meter_region' value  in rate_card.get  doesn't match with any value from subscription.list_location

**Comment by xiangyan99** [comment]
@ms-premp @qiaozha any updates?

**Comment by msyyc** [comment]
Python SDK is generated by autorest with [swagger](https://github.com/Azure/azure-rest-api-specs). If you want to find which Python SDK operation to use, please tell us which Rest API you want to use.

**Comment by qiaozha** [comment]
@xiangyan99  I think this service you are using has probably been deprecated. their rest api specs hasn't been updated for 3 years https://github.com/Azure/azure-rest-api-specs/tree/main/specification/commerce/resource-manager/Microsoft.Commerce/preview/2015-06-01-preview

**Comment by xiangyan99** [comment]
@qiaozha Thanks for the information.

I see the latest one was released on 2021-1-3.  https://pypi.org/project/azure-mgmt-commerce/6.0.0/. And it is a GA release.

Any ideas?

**Comment by qiaozha** [comment]
@msyyc may have more context here.

**Comment by msyyc** [comment]
I think @`service team` of `Commerce` has more info about it.

**Comment by fernandosierrap** [comment]
thanks, is resolved now
