### ISSUE TITLE
Whl discovery step is ignoring platform type when running test

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#9613]
whl discovery step which identifies the whl in prebuilt directory for a given package name doesn't consider platform type. Currently whl is discovered using package name, package version and python version. We should add the support to identify whl using platform also if platform specific whl is built for azure sdk packages.

**Comment by scbedd** [comment]
Praveen is talking about [right here](https://github.com/Azure/azure-sdk-for-python/blob/63427b15ea3d5696db855724e93981fbe1ad6dc7/eng/tox/create_package_and_install.py#L185)

This usage of finding the correct wheel to install is a bit fraught. This is one of the first locations to need update after when we address #28211
