### ISSUE TITLE
from devtools_testutils import AzureMgmtTestCase

### ISSUE THREAD

**Issue by WilliamHoo** [Azure/azure-sdk-for-python#9616]
- **Package Name**: azure
- **Package Version**: latest
- **Operating System**: windows 10 enterprise
- **Python Version**:  3.7 

**Describe the bug**
even after installing the whole azure package, i am still not able to import from devtools_testutils.
I installed using 'pip install azure'.
i checked my pipvenv, it does not have a file called 'devtools_testutlis'. I notice your git repo has such a file under 
'https://github.com/Azure/azure-sdk-for-python/tree/c30629eb6cb0b4fa8367b2da740c2fb407066270/tools/azure-sdk-tools', but i have no idea how to install it.

**Comment by kaerm** [comment]
@WilliamHoo thanks for the feedback, looping in my team to help find some answers //cc: @lmazuel

**Comment by WilliamHoo** [comment]
update:

I tried to install your repo in ubuntu sub-system in windows-10, using command

'pip install git+https://github.com/Azure/azure-sdk-for-python.git', and I am getting error messages below:

**Comment by WilliamHoo** [comment]
we want to use the azure-python-sdk to run azure tests offline, but we can't import libraries. It seems that your latest version is not released to pip yet. is your azure-python-sdk ready for offline tests?

**Comment by kaerm** [comment]
@mayurid can you see if there is anyone who could take a look at this

**Comment by lmazuel** [comment]
Hi @WilliamHoo 
Our test framework is not shipped on PyPI and is designed to be used from source on Github. It's not considered a deliverable usable by non-Microsoft people. May I ask you to explain your scenario in a little more details?

If you still wish to pursue, you can install it this way:
```python
pip install git+https://github.com/Azure/azure-sdk-for-python#subdirectory=tools/azure-devtools&egg=azure-devtools
pip install git+https://github.com/Azure/azure-sdk-for-python#subdirectory=tools/azure-sdk-tools&egg=azure-sdk-tools
```

But beware since it's not published there is no guarantee on breaking changes, even if we try to avoid it.

**Comment by maggiepint** [comment]
Hi - given we haven't heard back, assuming that this can be closed. Feel free to open a new issue if you need further assistance.
