### ISSUE TITLE
Always upload "latest" version of documentation

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#9625]
Example, `azure-core_1.0.0` is present. We release `azure-core_1.3.0`. A `latest` URL in blob storage should be updated with the 1.3.0 docs.

Instead of docs linking out to the 1.3.0 version specifically, the devs would prefer to refer to that `latest` URL on github.io. 

This isn't a huge task during doc-upload. If the version that is being uploaded is newer, we expect that the `latest` should be supplanted. 

It is understood by the devs that doing such a thing will cause old blog posts and other media to now link to new versions of the documentation. They still would prefer that.

@weshaggard We've discussed this before. Looks like it's coming up again.
@xiangyan99 Where specifically will you be using the `latest` link? Just readmes? Where is request coming from?

**Comment by weshaggard** [comment]
While I don't mind having a latest link, I think for readme's we should point to a page with the list of versions so folks can pick a version instead of always getting the latest. I'd also be OK with what package managers generally do which is to have the latest be the default but having an easy way to select other versions.

**Comment by lmazuel** [comment]
@scbedd we have an additional scenario where we want to point to a policy documentation, but the version doesn't actually matter (dev documentation). So I'm more keen than ever to see that :)

**Comment by scbedd** [comment]
This is going in either Monday or Tuesday. I just need to adjust the `versioning` JS in each repo to handle when they're in the `latest` folder versus a valid version.

The code itself to copy the additional files is completed.
