### ISSUE TITLE
Azure Identity - Cannot be found with Azure Function

### ISSUE THREAD

**Issue by thedataproject** [Azure/azure-sdk-for-python#9633]
When using Azure Identity in a Python script in Azure Functions i receive the following error: 

> ModuleNotFoundError: No module named 'azure.identity' Stack: File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 242, in _handle__function_load_request func_request.metadata.entry_point) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/loader.py", line 66, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/*****/__init__.py", line 25, in <module> from azure.identity import DefaultAzureCredential_

Requirements.txt contains azure-identity==1.2.0

**Comment by chlowell** [comment]
Thanks for reaching out. I suspect there's a problem with your app's configuration. I'm not greatly familiar with the platform, but I am working on testing azure-identity in a Functions App, so I can offer you a working example: see [this commit](https://github.com/chlowell/azure-sdk-for-python/commit/9bad138fa5f6b3b21f50f79020451405122c4f23). I've been deploying it with `func azure functionapp publish ... --build remote`

**Comment by chlowell** [comment]
I hit the same problem. It appears remote build is intended to solve it, and will become the default. In the meantime you can use the `--build remote` flag with recent versions of Core Tools or configure VS Code, as described in Azure/azure-functions-python-worker#464.

**Comment by chlowell** [comment]
Closing this because we can't address it in the SDK. For future reference, #9689 added a minimal app using azure-identity in Azure Functions.

Thanks again for opening this. Please feel free to open another issue if you encounter other problems.
