### ISSUE TITLE
Missing source package on PyPi for azure-template

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-sdk-for-python#9634]
While packaging ```azure-template``` for openSUSE/SLE, I noticed that the source code for that package is missing on PyPi which makes packaging it for Linux distributions more difficult.

Could you add the source package for ```azure-template``` to PyPi?

**Comment by kaerm** [comment]
@glaubitz thanks for letting us know, @nickzhums can you take a look at this

**Comment by nickzhums** [comment]
@RodgeFu could you have a look at this issue and see if we can solve it on our side? thanks

**Comment by RodgeFu** [comment]
Assign to @zikalino to double check. Thanks.

**Comment by changlong-liu** [comment]
we checked that the latest release azure-template (May 2020) in PyPi has source code in it.  Since this is a data-plan package, +@lmazuel for double confirm.

**Comment by lmazuel** [comment]
This package should not have been released :(. @scbedd FYI

This is a starter package for dev on the repo, and is not intendend to be installed as-is, the presence on PyPI is un unfortunate mistake...

**Comment by lmazuel** [comment]
Closing this issue in favor of the removal one I just created, since we won't publish anything:
https://github.com/Azure/azure-sdk-for-python/issues/12223
