### ISSUE TITLE
Add common methods used by tox and CI script into dev tools

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#9638]
Currently we have few duplicate methods in tox helper and common tasks that needsto be added into azure dev tools to have the implementation in one place. for e.g. finding whl from prebuilt directory, git helper functions etc.

**Comment by scbedd** [comment]
Addressed by #28345 !

We are consistently moving content from `scripts/devops_tasks` into the `ci_tools` module of `azure-sdk-tools`. This is an ongoing project but we have made a ton of progress here.
