### ISSUE TITLE
Is there a way to dissociate public IP address from NIC through SDK?

### ISSUE THREAD

**Issue by wjia7** [Azure/azure-sdk-for-python#9649]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to dissociate public IP addresses from my nic that is associated with a VM that is part of a scale set. There is ways to do it through the Azure portal and CLI (https://docs.microsoft.com/en-us/azure/virtual-network/remove-public-ip-address-vm). My question is that is there a way to do it through SDK? 

**Describe the solution you'd like**
A solution would be clearly documented steps attached to the above-mentioned link that describes how to dissociate a Public IP from NIC.

**Describe alternatives you've considered**
Perhaps there is an existing solution as part of networkmgmtClient.PublicAddressOperation under create_or_update()? Is there an example anywhere to do this?

**Additional context**

**Comment by Drewm3** [comment]
Moving this to the Azure Networking team who owns this space.

**Comment by v-xuto** [comment]
Hi @wjia7 ,
Here are the steps to dissociate public IP address from NIC( You can click the [link](https://docs.microsoft.com/zh-cn/python/api/azure-mgmt-network/azure.mgmt.network.v2019_09_01.models.networkinterfaceipconfiguration?view=azure-python ) for your reference)：  
Step 1, create a Network Management Client Object.  
Step 2, get subnet_obj.  
Step 3, configure network interface parameters.  When the value of the parameter public_ip_address  is None for disassociation. When the value of the parameter public_ip_address is 'ip_address_object ', it is associated with the specified public IP object. 
Step 4, use method create_or_update to update network interface configuration.  
  
The detailed code is shown below about dissociate public IP address from NIC:  
```
from azure.mgmt.network import NetworkManagementClient  
from azure.common.credentials import ServicePrincipalCredentials  
GROUP_NAME = 'ResourceGroupName'    
NIC_NAME = 'NetworkInterfaceName'    
subscription_id='<Your Subscription ID>'  
credentials = ServicePrincipalCredentials(  
   client_id='<Your service principal App ID>',  
   secret='<Your service principal password>',  
   tenant='<Your tenant ID>'  
)  
# Step 1, create a Network Management Client Object.  
network_client = NetworkManagementClient(credentials, subscription_id)  
# Step 2, get subnet_obj.  
subnet_obj = network_client.subnets.get(resource_group_name=GROUP_NAME, virtual_network_name='VirtualNetworkName',  
                                    subnet_name='default')  
# Step 3, configure network interface parameters.  
params = {'location': Location,  
              'ip_configurations': [  
                 {  
                    'name': ip_configuration_name，  
                    'subnet': {'id': subnet_obj.id},  
                    # None: Disassociate;  
                    'public_ip_address': None,  
                 }  
              ]  
              }  
# Step 4, use method create_or_update to update network interface configuration.  
network_client.network_interfaces.create_or_update(  
   resource_group_name=GROUP_NAME,  
   network_interface_name=NIC_NAME,  
   parameters=params)  
```
@jongio

**Comment by v-xuto** [comment]
Hi @wjia7 ,
How is this issue going? Feel free to let us know if further help is needed.

**Comment by tzhanl** [comment]
We are going to close this issue because we haven’t heard from you in a few days, but please re-open it if the issue still persists.
