### ISSUE TITLE
Please add send_event_batch method in ServiceBusService

### ISSUE THREAD

**Issue by VaanPan** [Azure/azure-sdk-for-python#966]
According to MSDN document https://docs.microsoft.com/en-us/rest/api/eventhub/send-batch-events there is a special header needs to be added if we want to send eventhub message in batch mode.

Set the Content-Type header to "application/vnd.microsoft.servicebus.json".

But in current version, there is no such method for event hub.
This function is important to improve batch messages send performance.

Thanks a ton if you can take time to add it into this SDK.

**Comment by lmazuel** [comment]
Hi @VaanPan 

Will do my best to do it asap. Thanks for the report :)

**Comment by annatisch** [comment]
@VaanPan - this is a feature of the new in-preview Event Hub python SDK build on AMQP.
It would be great if you could try it out. Expect GA is end of June.
https://pypi.org/project/azure-eventhub/#description
https://github.com/Azure/azure-event-hubs-python/tree/develop

**Comment by annatisch** [comment]
Closing this issue now as the Event Hub SDK is now GA and supports this feature.
Please report any further issues with this operation (or the EH SDK) at:
https://github.com/Azure/azure-event-hubs-python

Thanks!
