### ISSUE TITLE
Event Hub - Exceptions are swallowed with no obvious hook

### ISSUE THREAD

**Issue by kdazzle** [Azure/azure-sdk-for-python#9660]
- **Package Name**:  azure.eventhub
- **Package Version**:  5.0.0
- **Operating System**: Windows
- **Python Version**:  3.6.5

**Describe the bug**
When receiving events, uncaught exceptions are being swallowed by the library, with no obvious way to handle them myself.

**To Reproduce**

```
from azure.eventhub import EventHubConsumerClient


class Receiver():
    def receive():
        consumer = EventHubConsumerClient.from_connection_string(
            connection_str, consumer_group=consumer_group, retry_total=0)

        with consumer:
            consumer.receive(
                on_event=self.event_receive_callback,
                on_error=self.event_error_callback,
                starting_position=-1
            )

    def event_receive_callback(self, partition_context: PartitionContext, event: EventData):
        raise Exception('ruh roh')

    def event_error_callback(self, partition_context, error):
        print('we never get here!')

if __name__ == '__main__':
    EventReceiver().receive()
```

Results in a stream of messages printed to the console like:

```
Error processing message no 160: Exception('ruh roh',)
Error processing message no 162: Exception('ruh roh',)
Error processing message no 163: Exception('ruh roh',)
```

**Expected behavior**
I expect to be able to handle the exception in some way without having to wrap the whole receive method in a try/except. The library shouldn't swallow it.

I see a couple of different options...

- If you look at the way you can stream messages in Databricks, there are a couple of different options for handling errors - you can ignore them, fail, or write bad messages somewhere else. Something like that would be nice.
- There is also the on_error callback, and since it doesn't actually get called on an error, I'm not sure exactly what it's for. I see that it's called after max_retries, but it's never been called for me, even with `retry_total=0`. Maybe an `on_message_error` callback would be a nice way to do it.

**Comment by kaerm** [comment]
@kdazzle thank you for letting us know, someone from our team will take a look at this //cc: @yunhaoling @YijunXieMS

**Comment by YijunXieMS** [comment]
I'm investigating

**Comment by YijunXieMS** [comment]
@kdazzle dazzle This is a bug of the sync version (azure.eventhub.EventHubConsumerClient).
The async version (azure.eventhub.aio.EventHubConsumerClient) doesn't have this bug.

I've pushed the fix into the github repository. The next release will include this fix. Will update this issue once it's released. You may download the dev build [azure-eventhub-5.0.0.zip](https://github.com/Azure/azure-sdk-for-python/files/4150068/azure-eventhub-5.0.0.zip) and use pip to install it if you want to try it before the release.

**Comment by kdazzle** [comment]
Amazing - thanks @YijunXieMS !

**Comment by kdazzle** [comment]
@YijunXieMS - quick question about the version of that. The zip file says azure-eventhub-5.0.0 - does that mean that the version with the fix will also be 5.0.0?

**Comment by YijunXieMS** [comment]
@kdazzle, I increment the version number to 5.0.1 for a new dev build. [azure-eventhub-5.0.1.zip](https://github.com/Azure/azure-sdk-for-python/files/4221661/azure-eventhub-5.0.1.zip)

**Comment by YijunXieMS** [comment]
@kdazzle azure-eventhub 5.0.1 is released. It has the fix for this issue.

**Comment by kdazzle** [comment]
That's awesome - thanks a lot!

**Comment by YijunXieMS** [comment]
@kdazzle can I close this issue?

**Comment by YijunXieMS** [comment]
@kdazzle I'm closing it now. Let me know if it happens again.

**Comment by kdazzle** [comment]
Oops, sorry. Perfect - thanks again!
