### ISSUE TITLE
Design and implement service APIs

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#9666]
This tracks the work to design the APIs for the document Service APIs endpoint.

This includes:
- Service APIs -- GetStatistics

**Comment by bryevdv** [comment]
> Here are a couple of quick links to help with that first SearchServiceClient.GetStatistics method to get the client hierarchy in place:
Source: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search/src/SearchServiceClient.cs#L201
Single Test ported from Track 1: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search/tests/SearchServiceClientTests.cs#L133
