### ISSUE TITLE
consumption

### ISSUE THREAD

**Issue by vsnarkhede13** [Azure/azure-sdk-for-python#9687]
I want to extract all the resources, resource type(storage/vm/any else) and its consumed price using python. I've tried to get it through billing but didn't get results as expected.

Code:
import datetime
import azure.mgmt.consumption
import azure.mgmt.consumption.models
from azure.mgmt.consumption.models import UsageDetailPaged
from azure.mgmt.consumption.consumption_management_client import ConsumptionManagementClientConfiguration,ConsumptionManagementClient
from msrest.paging import Paged
#All credentials are added appropriately for security reasons those are not added in this query.
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.billing import BillingManagementClient
try1 = ConsumptionManagementClient(credentials,subscription_id)
billing_client  = BillingManagementClient(credentials, subscription_id)
print(billing_client.invoices.list())

**Comment by kaerm** [comment]
@vsnarkhede13 thanks for the feedback, looping the right team to take a look at it 
//cc: @nickzhums

**Comment by dw511214992** [comment]
If there is a sample of results, it will be better. Thank you

**Comment by vsnarkhede13** [comment]
> If there is a sample of results, it will be better. Thank you

{
  "accountName": null,
  "additionalProperties": null,
  "billableQuantity": "None",
  "billingPeriodId": "**************************",
  "consumedService": "Microsoft.Storage",
  "costCenter": null,
  "currency": "INR",
  "departmentName": null,
  "id": "**************************",
  "instanceId": "*****************************",
  "instanceLocation": "IN West",
  "instanceName": "(instance name)",
  "invoiceId": null,
  "isEstimated": true,
  "meterDetails": null,
  "meterId": "*********************",
  "name": "********************",
  "pretaxCost": "0.0034",
  "product": "",
  "subscriptionGuid": "**************",
  "subscriptionName": "(subscription type)",
  "tags": null,
  "type": "Microsoft.Consumption/usageDetails",
  "usageEnd": "(end details)",
  "usageQuantity": "0.144",
  "usageStart": "(Start details)"
}

**Comment by dw511214992** [comment]
The result is gotten from billing service and we need help from billing service team.

**Comment by v-xuto** [comment]
Hi @vsnarkhede13 ,
You can use service commerce to extract all the resources, resource type(storage/vm/any else) and its consumed price ,and please install package azure-mgmt-commerce. 
  
The detailed code  is shown below (here is the official [document](https://docs.microsoft.com/en-us/python/api/overview/azure/commerce?view=azure-python) for your reference):  
  ```
from azure.mgmt.commerce import UsageManagementClient 
from datetime import date, timedelta 
from azure.common.credentials import ServicePrincipalCredentials 
subscription_id='<Your Subscription ID>'   
credentials = ServicePrincipalCredentials(   
   client_id='<Your service principal App ID>',   
   secret='<Your service principal password>',   
   tenant='<Your tenant ID>'   
)   
commerce_client = UsageManagementClient(credentials, subscription_id) 
aggregate_data = commerce_client.usage_aggregates.list( 
    str(date.today() - timedelta(days=1))+'T00:00:00Z', 
    str(date.today())+'T00:00:00Z' 
) 
```
@jongio

**Comment by ms-premp** [comment]
please try this.

https://github.com/ms-premp/AzureConsumptionSamples/blob/master/Python_sdk/usage_details_list_python_sdk_example.py

**Comment by ramaganesan-rg** [comment]
Closing this issue based on the recommendations given by Prem. Please feel free to re-open this issue if needed, after reviewing the sample shared.
