### ISSUE TITLE
ServiceBus message delivery count not initialised

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-sdk-for-python#9708]
- **Package Name**:  azure-servicebus
- **Package Version**: 0.50.2
- **Operating System**: any
- **Python Version**: 3.7>=

**Describe the bug**
The `DeliveryCount` message property is not initialise properly but left to `None`.

**To Reproduce**
1. dump a message in a servicebus queue
2. read the message using sdk client
3. check the `message.broker_properties['DeliveryCount']` value
4. The value is set to `None`

**Expected behavior**
The value should be set to 0

**Similar issues**
#9228

**Comment by kaerm** [comment]
@andreacassioli thanks for letting us know, someone from our team will take a look at this

**Comment by KieranBrantnerMagee** [comment]
Hey andrea,
Wanted to loop back that we've addressed this via [this UAMQP change](https://github.com/Azure/azure-uamqp-python/pull/159).

Expect this to percolate out both in the final 0.50 release "coming soon", and in the 7.0.0 GA releases working their way through preview. (b3 coming EOM).

As always don't hesitate to reopen this/reach out if any issues or questions.
