### ISSUE TITLE
Error when trying to add secret after being deleted in Azure keyvault

### ISSUE THREAD

**Issue by rfernand2** [Azure/azure-sdk-for-python#9743]
- **Azure Portal**: 
- **Feb-05-2002**: 
- **Windows 10**:

Using the Azure portal UI, I deleted a secret and then tried to add it back; keep getting the error:

> There was a conflict while creating/updating your secret.

**Comment by chlowell** [comment]
I suspect your Key Vault has [soft-delete](https://docs.microsoft.com/en-us/azure/key-vault/key-vault-ovw-soft-delete) enabled. When you soft-delete a secret, it's marked as deleted and no longer appears in the Portal, but its name and history of values are retained. You'll see a conflict error if you try to reuse that name.

You can manually recover, or permanently delete, a soft-deleted secret. These operations are currently not available in the Azure Portal, where you may see this warning:

![image](https://user-images.githubusercontent.com/10964656/73956965-8b83a980-48ba-11ea-8829-52367eb4b024.png)

They're possible with the SDK, however: see the documentation on [recovering a deleted secret](https://aka.ms/azsdk-python-keyvault-secrets-ref#azure.keyvault.secrets.SecretClient.begin_recover_deleted_secret) and [purging a deleted secret](https://aka.ms/azsdk-python-keyvault-secrets-ref#azure.keyvault.secrets.SecretClient.purge_deleted_secret).

Also, for the benefit of future readers who may be just getting started with Key Vault, if one only wants to change a secret's value, it isn't necessary to recreate that secret--secrets are versioned, and their latest value can be updated, in the Portal or with the SDK's [set_secret](https://aka.ms/azsdk-python-keyvault-secrets-ref#azure.keyvault.secrets.SecretClient.set_secret) method.

**Comment by chlowell** [comment]
Closing this because it concerns the Azure Portal, not the SDK.

**Comment by turtletennis** [comment]
For anyone who gets here from a Google search (like me) you can now purge/restore deleted secrets by clicking on "Manage deleted secrets"

**Comment by MeaningOfLights** [comment]
In Azure KeyVault, click "Manage Deleted Secrets" and the trick is to click the 'Load more' link at the bottom!

**Comment by rodrigo3000rodrigo** [comment]
> In Azure KeyVault, click "Manage Deleted Secrets" and the trick is to click the 'Load more' link at the bottom!

you safe my life thanks
