### ISSUE TITLE
Unable to get Azure resource manager VM memory metrics using azure SDK for python

### ISSUE THREAD

**Issue by navya-goli** [Azure/azure-sdk-for-python#977]
Hi 

I researched and worked a lot to extract azure resource manager VM metrics using azure SDK for python but did not succeed.

I am able to get only Percentage CPU, Network In, Network Out, Disk read Bytes, Disk write bytes, Disk Read Operations/sec, Disk write operations/sec.

Please provide assistance inorder to get azure vm memory metrics using azure sdk for python.

**Comment by lmazuel** [comment]
Hi @navya-goli 
I forwarded your question to the Monitor team, they answered:

> Memory usage is only available within the guest VM, not from host OS so it won't be available via the metrics API.  Current guest agent story is around WAD/LAD.  There is no REST API today to retrieve the memory metric but customer can configure WAD/LAD to collect the data to their storage account. 

This might be a future feature, but I have no ETA to this.

**Comment by scolinas** [comment]
Hi @lmazuel,

This issue also affects me, is there any alternative way to get all the metrics?

**Comment by lmazuel** [comment]
Hi @scolinas 
As I said the only alternative for memory so far is to configure WAD/LAD on a storage account.

**Comment by madhut** [comment]
> Hi
> 
> I researched and worked a lot to extract azure resource manager VM metrics using azure SDK for python but did not succeed.
> 
> I am able to get only Percentage CPU, Network In, Network Out, Disk read Bytes, Disk write bytes, Disk Read Operations/sec, Disk write operations/sec.
> 
> Please provide assistance inorder to get azure vm memory metrics using azure sdk for python.

Hi Navya, I would like to know that you were able to get  only Percentage CPU, Network In, Network Out, Disk read Bytes, Disk write bytes, Disk Read Operations/sec, Disk write operations/sec. Did you get it through REST API?. If it is through API can you share the REST API if you don't mind ?

**Comment by navya-goli** [comment]
Hi,

Please refer to the below link:

https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring?view=azure-python


It will definetly help you.

Thanks
Navya Goli

**Comment by madhut** [comment]
> Please refer to the below link:

Thank you Navya for the response. Sure I will give it a try.
Thanks,
Venkata

**Comment by asheniam** [comment]
This is a feature ask on Azure Monitor, specifically on VM team.  Memory metric is not supported via the Metrics API today.
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported

**Comment by xiangyan99** [comment]
@msyyc could you help to take a look?
