### ISSUE TITLE
Support a default error type in map_error

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#9773]
`azure.core.exceptions.map_error` requires the given `error_map` to map status codes to error types explicitly. This makes it cumbersome to use to prevent generated clients from raising generated error types. Generated methods often raise on all but one status code, requiring an `error_map` to map every other status code to some type. That is to say, `error_map` must either be a dict-like with a key for every status code, or a custom dict-like with its own implementation of a default value.

**Comment by lmazuel** [comment]
I approve this message :)

**Comment by xiangyan99** [comment]
Fixed in #10456
