### ISSUE TITLE
Can BlockBlobService.copy_blob copy file url which is from a public website.

### ISSUE THREAD

**Issue by lx1054331851** [Azure/azure-sdk-for-python#9782]
Can BlockBlobService.copy_blob function copy file url which is from a public website, such as copy a image from this url(https://static.zara.cn/photos///2019/I/0/1/p/2387/778/712/6/w/1920/2387778712_1_1_1.jpg) that the url is public.

**Comment by xiafu-msft** [comment]
Hi @lx1054331851 

Thanks for reaching out. If it is a public file then you should be able to copy that.
Also I've tested and I'm pretty sure you will be able to copy https://static.zara.cn/photos///2019/I/0/1/p/2387/778/712/6/w/1920/2387778712_1_1_1.jpg

Let me know if you need anything else!
Best,
Emily

**Comment by v-xuto** [comment]
Hi @lx1054331851 ,
You can install the latest blob version 12.2.0 using the following command: 
```
pip install azure-storage-blob==12.2.0 
```
The detailed code using blob version 12.2.0 is shown below (You can click the [link](https://github.com/Azure/azure-sdk-for-python/blob/a59b39a1bc11fe8556c94df26a71aa7ebf7d9d8f/sdk/storage/azure-storage-blob/samples/blob_samples_copy_blob.py) for your reference): 
```
from azure.storage.blob import BlobServiceClient 
def main(): 
    conn_str="my_connection_string" 
    blob_service_client = BlobServiceClient.from_connection_string(conn_str) 
    public_file = "https://static.zara.cn/photos///2019/I/0/1/p/2387/778/712/6/w/1920/2387778712_1_1_1.jpg" 
    copied_blob = blob_service_client.get_blob_client(container="my_container", blob='2387778712_1_1_1.jpg') 
    # Copy started 
    copied_blob.start_copy_from_url(public_file) 
if __name__ == "__main__": 
    main() 
```
@jongio

**Comment by v-xuto** [comment]
Hi @lx1054331851 ,
How is this issue going? Feel free to let us know if further help is needed.

**Comment by lx1054331851** [comment]
@xiafu-msft @v-xuto  Thanks very much , I update to the latest blob version, the problem has been solved. I will close this issue.
