### ISSUE TITLE
SDK is unable to unable the correct exception when receiving a 400 response code when creating (or updating) a AKS cluste

### ISSUE THREAD

**Issue by InesNefoussi** [Azure/azure-sdk-for-python#9792]
- **Package Name**: azure-sdk-for-python/sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2020_01_01/operations/_managed_clusters_operations.py/
- **Package Version**: v2020_01_01
- **Operating System**:
- **Python Version**: 2.7

**Describe the bug**
When creating a new AKS cluster and after receiving a 400 response (quota exceeded on cores), instead of having this exact error message, we had a __UnicodeEncodeError: 'ascii' codec can't encode character__. After debugging, this comes from line 549 in the ___managed_clusters_operations.py class__; after testing on the response code, it tries to raise a CloudError exception, but obviously fails and raises the __UnicodeEncodeError__ instead. We did not test on other response codes, but might happen with any response code other than 200 and 201.

**To Reproduce**
1. Try to create an AKS cluster with total cores that exceed the pre-set quota using the SDK and the ManagedClustersOperations.

**Expected behavior**
Expected is to receive the correct error message: Cores quota exceeded.

**Screenshots**

**Additional context**

**Comment by lilyjma** [comment]
@Azure/aks-pm can you please take a look at this issue?
