### ISSUE TITLE
PipelineDraft.list() throws exception

### ISSUE THREAD

**Issue by federicosalvi** [Azure/azure-sdk-for-python#9833]
- **Package Name**: 
azureml.pipeline.core
- **Package Version**: 
1.0.85.1
- **Operating System**:
Windows 10
- **Python Version**: 
3.7.4

**Describe the bug**
When calling PipelineDraft.list() an AttributeError is thrown. It happens only when a pipelinedraft has been created from the Azure ML studio.

**To Reproduce**
1. Create a pipeline draft from the Azure ML studio
2. Import PipelineDraft from azureml.pipeline.core
3. Instantiate the workspace
4. Call PipelineDraft.list(workspace)

**Expected behavior**
I would expect to get a list of the pipeline drafts saved in the workspace

**Screenshots**
![image](https://user-images.githubusercontent.com/12402525/74354029-0c5f0b80-4dbb-11ea-98c3-db43927d7bde.png)

**Additional context**
It seems the issues is inside _workflow_provider which in the documentation is marked as "internal use only"

**Comment by federicosalvi** [comment]
An update:
it seems that the issue occurs only when at least one of the pipeline drafts has been created from the azure ml studio. I suspect that's because you don't need to specify an experiment when doing so, while you do have to when you create it from the sdk.

I'll update the steps to reproduce.

**Comment by shbijlan** [comment]
This bug for listing PipelineDrafts throw errors for pipeline created in Designer (studio) was fixed earlier this year. Please reopen this thread if you are still facing the issue.

**Comment by shbijlan** [comment]
#please-close
