### ISSUE TITLE
smoke tests break on dependency changes for scripts in eng folder

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-python#9837]
Is there a way to install requirements for a tool like `install_dev_build_dependency.py` without requiring updates to the smoke tests' installations? 

A recent [change to common_tasks.py](https://github.com/Azure/azure-sdk-for-python/blob/master/scripts/devops_tasks/common_tasks.py#L31) introduced a dependency on `pkginfo` ... The smoke tests broke when this dependency was introduced but not installed [explicitly](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/pipelines/smoke-test.yml#L43). 

Possible solutions include: 
* Installing dependencies in [`eng/ci_tools.txt`](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/ci_tools.txt) but that carries with it some risk that we'll install tools that would contribute to false positives or negatives in our testing results. A customer might not have those packages installed in their environment so we shouldn't assume that they'll be in place for the script to run. 
* Install dependencies in [`eng/ci_tools.txt`](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/ci_tools.txt), run the updating script, then uninstall entries in that file... This could create problems if one of the entries in `ci_tools` is required by a package that we want to test.

**Comment by danieljurek** [comment]
cc @scbedd, @praveenkuttappan

**Comment by scbedd** [comment]
We actually have a plan for this going forward. @danieljurek 

We intend to move all our tooling scripts (where it makes sense, like everythin under scripts/devops_tasks) under a namespace in `azure-devtools.`

This would mean that it would take a simple `pip install azure-devtools` to get access to what you need. Then, as you mentioned, we could uninstall it after it runs to leave the environment that you want.

**Comment by weshaggard** [comment]
@scbedd is someone actively working on the azure-devtools work? If not is there a tracking issue for it?

**Comment by praveenkuttappan** [comment]
@weshaggard We have a tracking issue for this change and I have started on it. I will resume this task once API review integration for python is completed.
https://github.com/Azure/azure-sdk-for-python/issues/9638

**Comment by kurtzeborn** [comment]
Obsolete.
