### ISSUE TITLE
Change log version check ignored unreleased tag when releasing package

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#9848]
Version check must ensure that "Unreleased" tag is not present in version title when releasing package. for an instance, change log was not updated to release date for azure-storage-file-datalake

Fore.g. Version title should not have tag like the one in below sample. 
## 1.2.3 (Unreleased)

**Comment by weshaggard** [comment]
Closing as a duplicate of https://github.com/Azure/azure-sdk-tools/issues/421. We should have a common script that will verify the changelog on release.
