### ISSUE TITLE
service bus .complete() 

### ISSUE THREAD

**Issue by keithdarragh** [Azure/azure-sdk-for-python#9856]
- **Package Name**: azure-servicebus
- **Package Version**: 0.50.2
- **Operating System**: linux
- **Python Version**: 3.6

**Describe the bug**
I'm following the docs on how to subscribe to data in a topic and send back an acknowledgement  after processing. However the complete method throws an error saying it is unavailable. 

**To Reproduce**
1. Run through the quickstart docs guide: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-topics-subscriptions

Code snippet: 
```
msg = bus_service.receive_subscription_message('mytopic', 'LowMessages', peek_lock=True)
if msg.body is not None:
    print(msg.body)
    msg.complete()
```

**Expected behavior**
I expect an acknowledgement to be sent back and the message deleted from the subscription

**Additional context**
It looks as though the docs page may be out of date. Do they need updated?

**Comment by kaerm** [comment]
@keithdarragh thanks for letting us know! Someone from our team will look into that

**Comment by keithdarragh** [comment]
Hi @kaerm, 

Issue appears to be resolved by following the example found here: https://github.com/Azure/azure-sdk-for-python/blob/8e8d5ab93c5c37e48adac04fc3825ddae88b9210/sdk/servicebus/azure-servicebus/examples/subscription_receive.py#L34

Have some old apis for this been deprecated or support dropped?

**Comment by kaerm** [comment]
Hey @keithdarragh I started a discussion on the docs and seems like they weren't able to reproduce https://github.com/MicrosoftDocs/azure-docs/issues/48056#issuecomment-588881382

**Comment by ramya-rao-a** [comment]
@KieranBrantnerMagee, at the very least lets update the quick start docs to not use http operations and use amqp instead

**Comment by KieranBrantnerMagee** [comment]
Synced with Sreedhar/provided our T1 samples to get the ball rolling on doc update.  May take some time to get published, however, but that process has been started.

Closing this issue under the assumption that the above will proceed smoothly, feel free to reopen otherwise if any further issues or if we want to track this more actively.

Thanks for everyone's patience/help in this.
