### ISSUE TITLE
keyvault client fails with (1783, 'CredWrite', 'The stub received bad data')

### ISSUE THREAD

**Issue by BarryBo** [Azure/azure-sdk-for-python#9857]
This is similar to https://github.com/Azure/azure-sdk-for-python/issues/4610, but repros using msrest 0.6.11.

This repros on Windows 10, with Python 3.8.1 64-bit.  It does not repro on Ubuntu Linux.

**Describe the bug**
azure.keyvault.key_vault_client.KeyVaultClient - call get_secret(), and it throws the above exception.

**To Reproduce**
1.  Use ADAL to authenticate... adal.AuthenticationContext.acquire_token_with_device_code()
2.  auth = KeyVaultAuthentication(adal)
3.  keyvault = KeyVaultClient(auth)

**Expected behavior**
Key vault secret retrieved OK

**Additional context**

**Comment by kaerm** [comment]
@BarryBo thanks for letting us know, someone from our team will take a look into this

**Comment by chlowell** [comment]
@lmazuel looks like a recurrence of #4610 in the latest msrest?

**Comment by lmazuel** [comment]
The keyring problem was actually not in msrest, but in msrestazure. @BarryBo if you update your msrestazure to at least 0.5.0.

Please confirm this solves your issue so we can close, thanks!

**Comment by BarryBo** [comment]
I have msrestazure 0.6.2 and the problem repros.

```
C:\Users\barrybo\source\repos\exp23-yocto\scripts>pip3 show msrestazure
Name: msrestazure
Version: 0.6.2
Summary: AutoRest swagger generator Python client runtime. Azure-specific module.
Home-page: https://github.com/Azure/msrestazure-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: c:\users\barrybo\appdata\local\programs\python\python38\lib\site-packages
Requires: adal, msrest
...

C:\Users\barrybo\source\repos\exp23-yocto\scripts>where pip3
C:\Users\barrybo\AppData\Local\Programs\Python\Python38\Scripts\pip3.exe

C:\Users\barrybo\source\repos\exp23-yocto\scripts>C:\Users\barrybo\AppData\Local\Programs\Python\Python38\python.exe .\query-telemetry.py -i 101
Found search telemetry index: 101 - name: NW_KERNEL_KernelOops
Please sign in with your @microsoft.com credentials:
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <removed> to authenticate.
(1783, 'CredWrite', 'The stub received bad data')

Make sure you are logged in with your @microsoft.com identity
```

I checked with Python in verbose mode, and it's loading msrestazure from C:\Users\barrybo\AppData\Local\Programs\Python\Python38\lib\site-packages\msrestazure\.

**Comment by lmazuel** [comment]
I tried to to install azure-keyvault 1.1.0 (which I think is what you use correct?) but "keyring" is not installed anymore and I can't reproduce it.

Could you list the entire set of packages you have? Could you try a fresh env?

Thank you

**Comment by BarryBo** [comment]
Here's my current environment:

Package                               Version   
------------------------------------- ----------
adal                                  1.2.2     
astroid                               2.3.3     
azure                                 4.0.0     
azure-applicationinsights             0.1.0     
azure-batch                           4.1.3     
azure-common                          1.1.24    
azure-cosmosdb-nspkg                  2.0.2     
azure-cosmosdb-table                  1.0.6     
azure-datalake-store                  0.0.48    
azure-eventgrid                       1.3.0     
azure-graphrbac                       0.40.0    
azure-keyvault                        1.1.0     
azure-loganalytics                    0.1.0     
azure-mgmt                            4.0.0     
azure-mgmt-advisor                    1.0.1     
azure-mgmt-applicationinsights        0.1.1     
azure-mgmt-authorization              0.50.0    
azure-mgmt-batch                      5.0.1     
azure-mgmt-batchai                    2.0.0     
azure-mgmt-billing                    0.2.0     
azure-mgmt-cdn                        3.1.0     
azure-mgmt-cognitiveservices          3.0.0     
azure-mgmt-commerce                   1.0.1     
azure-mgmt-compute                    4.6.2     
azure-mgmt-consumption                2.0.0     
azure-mgmt-containerinstance          1.5.0     
azure-mgmt-containerregistry          2.8.0     
azure-mgmt-containerservice           4.4.0     
azure-mgmt-cosmosdb                   0.4.1     
azure-mgmt-datafactory                0.6.0     
azure-mgmt-datalake-analytics         0.6.0     
azure-mgmt-datalake-nspkg             3.0.1     
azure-mgmt-datalake-store             0.5.0     
azure-mgmt-datamigration              1.0.0     
azure-mgmt-devspaces                  0.1.0     
azure-mgmt-devtestlabs                2.2.0     
azure-mgmt-dns                        2.1.0     
azure-mgmt-eventgrid                  1.0.0     
azure-mgmt-eventhub                   2.6.0     
azure-mgmt-hanaonazure                0.1.1     
azure-mgmt-iotcentral                 0.1.0     
azure-mgmt-iothub                     0.5.0     
azure-mgmt-iothubprovisioningservices 0.2.0     
azure-mgmt-keyvault                   1.1.0     
azure-mgmt-loganalytics               0.2.0     
azure-mgmt-logic                      3.0.0     
azure-mgmt-machinelearningcompute     0.4.1     
azure-mgmt-managementgroups           0.1.0     
azure-mgmt-managementpartner          0.1.1     
azure-mgmt-maps                       0.1.0     
azure-mgmt-marketplaceordering        0.1.0     
azure-mgmt-media                      1.0.0     
azure-mgmt-monitor                    0.5.2     
azure-mgmt-msi                        0.2.0     
azure-mgmt-network                    2.7.0     
azure-mgmt-notificationhubs           2.1.0     
azure-mgmt-nspkg                      3.0.2     
azure-mgmt-policyinsights             0.1.0     
azure-mgmt-powerbiembedded            2.0.0     
azure-mgmt-rdbms                      1.9.0     
azure-mgmt-recoveryservices           0.3.0     
azure-mgmt-recoveryservicesbackup     0.3.0     
azure-mgmt-redis                      5.0.0     
azure-mgmt-relay                      0.1.0     
azure-mgmt-reservations               0.2.1     
azure-mgmt-resource                   2.2.0     
azure-mgmt-scheduler                  2.0.0     
azure-mgmt-search                     2.1.0     
azure-mgmt-servicebus                 0.5.3     
azure-mgmt-servicefabric              0.2.0     
azure-mgmt-signalr                    0.1.1     
azure-mgmt-sql                        0.9.1     
azure-mgmt-storage                    2.0.0     
azure-mgmt-subscription               0.2.0     
azure-mgmt-trafficmanager             0.50.0    
azure-mgmt-web                        0.35.0    
azure-nspkg                           3.0.2     
azure-servicebus                      0.21.1    
azure-servicefabric                   6.3.0.0   
azure-servicemanagement-legacy        0.20.6    
azure-storage-blob                    1.5.0     
azure-storage-common                  1.4.2     
azure-storage-file                    1.4.0     
azure-storage-queue                   1.4.0     
bcrypt                                3.1.7     
certifi                               2019.11.28
cffi                                  1.14.0    
chardet                               3.0.4     
Click                                 7.0       
colorama                              0.4.3     
colorlog                              4.1.0     
cryptography                          2.8       
dnslib                                0.9.12    
fdt                                   0.2.0     
Flask                                 1.1.1     
idna                                  2.8       
isodate                               0.6.0     
isort                                 4.3.21    
itsdangerous                          1.1.0     
Jinja2                                2.10.3    
keyring                               21.1.0    
lazy-object-proxy                     1.4.3     
lxml                                  4.5.0     
MarkupSafe                            1.1.1     
mccabe                                0.6.1     
msrest                                0.6.11    
msrestazure                           0.6.2     
oauthlib                              3.1.0     
paramiko                              2.7.1     
pip                                   20.0.2    
proboscis                             1.2.6.0   
protobuf                              3.11.3    
pycparser                             2.19      
PyJWT                                 1.7.1     
pylint                                2.4.4     
PyNaCl                                1.3.0     
pyserial                              3.4       
python-dateutil                       2.8.1     
pywin32-ctypes                        0.2.0     
PyYAML                                5.3       
requests                              2.22.0    
requests-oauthlib                     1.3.0     
scp                                   0.13.2    
setuptools                            41.2.0    
six                                   1.14.0    
urllib3                               1.25.8    
Werkzeug                              1.0.0     
workerpool                            0.9.4     
wrapt                                 1.11.2    
xmodem                                0.4.5

**Comment by BarryBo** [comment]
I uninstalled as much as I could, down to just this:
C:\Users\barrybo>pip3 list
Package    Version
---------- -------
-ffi       1.14.0
pip        20.0.2
setuptools 41.2.0

I then installed my team's default set of packages using the attached requirements.txt.
[requirements.txt](https://github.com/Azure/azure-sdk-for-python/files/4313689/requirements.txt) then used pip3 to install azure-keyvault, keyring and adal.  

That causes my app to fail with: ImportError: cannot import name 'KeyVaultClient' from 'azure.keyvault' (unknown location).  It looks like [this thread](https://github.com/Azure/azure-sdk-for-python/issues/8591) documents the issue, and the need to switch to azure-keyvault==1.1.0.  When I do that, the 'The stub received bad data' error appears.

I can try rewriting my app to use the newer azure-keyvault.  But the same v1.1.0 works fine on Linux.

**Comment by lmazuel** [comment]
I wonder who brought "keyring" in your environment, we definitly don't. Could you just try to uninstall "keyring"?
Also, if your app requires only keyvault , try to just install "azure-keyvault==1.1.0" and not "azure"

**Comment by BarryBo** [comment]
OK, closing out the bug.  The failing keyring call was coming from code I wrote, inside the callback function invoked by KeyVaultAuthentication, to cache the results of the device authentication, since the auth itself is valid for 60 minutes.

keyring.set_password() fails on Windows with a 1281 character password, with the (1783, 'CredWrite', 'The stub received bad data') message, but succeeds with 1280 characters.
