### ISSUE TITLE
Unable to find a way to specify the OS disk size for scale sets

### ISSUE THREAD

**Issue by tmarballi** [Azure/azure-sdk-for-python#987]
I was looking for a way to specify a bigger disk size for the scale sets I am creating, similar to how we can do for regular virtual machines (https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/models/os_disk.py#L75). 

I believe with the latest managed disk support, we are able to specify a bigger disk size than the default (~30 GB), but I was not able to find a way to specify size for VMSS. I came across this template (https://github.com/chagarw/MDPP/blob/master/101-vmss-standard-image/azuredeploy.json#L176) which has the parameter I need under virtual machine profile, but the specific VirtualMachineScaleSetVMProfile does not have the disk_size parameter as mentioned in the template. Am I missing something here? Any help is appreciated!

**Comment by lmazuel** [comment]
Good point, seems you're right. I will check with the service team.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue is still a concern.
