### ISSUE TITLE
Importing PEM-encoded certificates may not work

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#9874]
While fixing azure/azure-sdk-for-net#9963, I found that we are base64-encoding PEM files but, despite the parameter name and description in swagger, the service expects PEM files as plain strings. On top of that, we don't know how the developer encoded the PEM file so we can't correctly decode it unless we ask or, instead, add a string overload and handle encoding/decoding internally ourselves.

**Comment by twsouthwick** [comment]
My 2 cents: It would be great if we could just provide the certificate, and any encoding is done internally. Dealing with byte arrays is fine, but a bit cumbersome. The previous SDK would accept certifcates directly.

**Comment by lmazuel** [comment]
Talked with @chlowell , closeable
