### ISSUE TITLE
Programmatically how to get  the CPU and RAM utilization for Azure VM.

### ISSUE THREAD

**Issue by Ravi-cell** [Azure/azure-sdk-for-python#9885]
Please let me know how to get the cpu and ram size of azure VM.we are trying to get the CPU and RAM utilization by using python sdk.

**Comment by kaerm** [comment]
@Ravi-cell thanks for reaching out tagging the right team to take a look at this //cc: @nickzhums

**Comment by v-xuto** [comment]
Hi @Ravi-cell ，
About how to get the RAM utilization for Azure VM by using python sdk , it's not support now. The related [issue](https://github.com/Azure/azure-sdk-for-python/issues/977) for you reference. 
  
But about how to get the CPU utilization for Azure VM by using python sdk, it's support. 
The detailed code is shown below for how to  get the CPU utilization (here is the officle [document](https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring?view=azure-python).) 
```  
import datetime 
from azure.mgmt.monitor import MonitorManagementClient 
  
resource_id = ( 
    "subscriptions/{}/" 
    "resourceGroups/{}/" 
    "providers/Microsoft.Compute/virtualMachines/{}" 
).format(subscription_id, resource_group_name, vm_name) 
  
# create client 
client = MonitorManagementClient( 
    credentials, 
    subscription_id 
) 
  
# You can get the available metrics of this specific resource 
for metric in client.metric_definitions.list(resource_id): 
    # azure.monitor.models.MetricDefinition 
    print("{}: id={}, unit={}".format( 
        metric.name.localized_value, 
        metric.name.value, 
        metric.unit 
    )) 
  
# Get CPU total of yesterday for this VM, by hour 
today = datetime.datetime.now().date() 
yesterday = today - datetime.timedelta(days=1) 
 
metrics_data = client.metrics.list( 
    resource_id, 
    timespan="{}/{}".format(yesterday, today), 
    interval='PT1H', 
    metricnames='Percentage CPU', 
    aggregation='Total' 
) 
  
for item in metrics_data.value: 
    # azure.mgmt.monitor.models.Metric 
    print("{} ({})".format(item.name.localized_value, item.unit.name)) 
    for timeserie in item.timeseries: 
        for data in timeserie.data: 
            # azure.mgmt.monitor.models.MetricData 
            print("{}: {}".format(data.time_stamp, data.total)) 
```
@jongio

**Comment by Drewm3** [comment]
@LianwMS, could you please assign this to the Azure Monitor folks. This information comes from Azure Monitor instead of Azure Compute.

**Comment by KevinBlasko** [comment]
You can get memory metrics using the Azure Monitor (preview) sink for the WAD agent (note that Linux is currently not supported).  The sink can either be enabled [programmatically](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/collect-custom-metrics-guestos-resource-manager-vm) or through the "Diagnostic Settings" UI in the Azure Portal.

Once you enable the Azure Monitor sink, you can access the metrics through the API by setting the namespace to "azure.vm.windows.guestmetrics".
