### ISSUE TITLE
Establish Scenario Testing Support for Python

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#9898]
Getting this epic filed for tracking purposes. First, some context.

The method by which `azure-identity` is currently scenario-tested across various configurations and platforms is the following:

1. A "script" markdown is shared. This is essentially a set of manual steps necessary to properly execute the scenario test.
    * A sample of one such step would be `az appserviceplan create <params>`
2. Each step of the markdown is followed manually by whoever is running through the test.
3. Status and relevant logs are shared back on conclusion of the manual run.

There is an additional wrinkle here. The test matrix is not limited purely to platform OS and python version. For the identity testing alone, we have the complication of ensuring that we can automate successful checks with specific auth methods...

* User Assigned Identity
* System Assigned Identity
* Managed Identity
* Certificate?

...As well as executing code against the following environments:
* webjob
* cloudshare
* Azure Container Instance
* Azure Kubernetes Service
* VM
* WebApp

I'm seeing the following buckets of work here.

* Establish a shared language for the markdown
    * This doesn't need to be a strict grammar or the like. We just need to agree upon the formatting.
* Automate _retrieval of results_ from each platform. 
    * This might be as simple as adjusting the `executable code` to output its results to appinsights (as recommended by Xiang)
* Harness Configuration - Direct Build YML?
   * Code Environment
   * Python Version
   * Platform
* Location. This feels very much like it belongs within the smoke-tests.
* Execution. Run and Report!

@praveenkuttappan @xiangyan99

**Comment by scbedd** [comment]
[Example "script" ](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/managed-identity-live/appservice.md)

**Comment by kurtzeborn** [comment]
@scbedd, is this different than the work needed to get samples integrated into the smoke test builds and runs?

**Comment by scbedd** [comment]
It would be reasonable to call the samples integration an implementation of this scenario, 100%.

**Comment by scbedd** [comment]
Closing. Very generic request and this scenario hasn't been asked about since this issue was created.
