### ISSUE TITLE
Why is `pre_warmed_instance_count` not part of AppServicePlan?

### ISSUE THREAD

**Issue by estensen** [Azure/azure-sdk-for-python#9904]
It seems logical to group it together with `maximum_elastic_worker_count`, `location` and `sku`.
I cannot from the documentation find a way to programmatically specify how many pre-warmed instances I want.

**Comment by kaerm** [comment]
@estensen thanks for reaching out to us, someone from our team is going to take a look at this //cc: @nickzhums

**Comment by nickzhums** [comment]
This seems to be a design question for the App Services Plan, will need their expertise :)
