### ISSUE TITLE
[Storage] Migrate DataLake tests to new framework

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#9909]
We need to migrate the DataLake tests to resolve some parallelization issues.

Adding @xiafu-msft  - you mentioned that you had some concerns about this?

**Comment by tasherif-msft** [comment]
Hi @annatisch, @xiafu-msft is working on this here https://github.com/Azure/azure-sdk-for-python/pull/17396
I will close this issue in the meantime. Let us know if you have any questions.
