### ISSUE TITLE
[ServiceBus] Docs Missing for v0.50.2

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#9916]
ServiceBus v0.50.2 is released from branch [release/servicebus-v1](https://github.com/Azure/azure-sdk-for-python/tree/release/servicebus-v1) which doesn't have the documentation generated.

Missing doc for:
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/0.50.2/index.html

**Comment by scbedd** [comment]
Merged master, rebuilt docs, manually uploaded after confirmation with @yunhaoling 

Version now showing up here: https://azure.github.io/azure-sdk-for-python/ref/Service-Bus.html
