### ISSUE TITLE
Refactor CI scripts to move them as module within azure-sdk-tools package ci_tools

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#9924]
Currently we have few duplicate scripts across the scripts used by tox tasks and ci specific scripts. We can move most of these scripts as utility modules/methods under ci tools to avoid duplicate code as well as to keep it simpler for the consumers of this script instead of rewriting them again.

**Comment by scbedd** [comment]
I'm thinking the local `azure_devtools` instead of `azure-sdk-tools`.

Reason being: any new test work is being implemented in azure_devtools as far as I know.

**Comment by praveenkuttappan** [comment]
@scbedd Absolutely right. I mentioned it as azure-sdk-tools by mistake. it should be azure-devtools since ci_tools module is in it currently.

**Comment by praveenkuttappan** [comment]
This is duplicate of issue https://github.com/Azure/azure-sdk-for-python/issues/9638
