### ISSUE TITLE
ServiceBus get_queue fails for dead letter queue

### ISSUE THREAD

**Issue by itaysk** [Azure/azure-sdk-for-python#993]
Title self explanatory.
Fails with HTTP error 400

**Comment by lmazuel** [comment]
Hi @itaysk 
Are you saying it fails anytime? With nothing inside and/or message?

**Comment by itaysk** [comment]
Yeah I couldn't get it to work.. I can get the regular queue, but not the dead letter for that queue.
Tried doing similar test with C# sdk and it worked (create a client reference of the dead letter queue)

**Comment by annatisch** [comment]
Hi @itaysk 

This is just a heads-up to let you know that we have just published a new AMQP-based preview SDK for Service Bus! The API has been newly designed, and you can find documentation here:
- [Overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python)
- [Reference documentation](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus?view=azure-python)

Specifically the documentation regarding receiving from a dead letter queue can be [found here](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.servicebus_client.receiveclientmixin?view=azure-python#get-deadletter-receiver-transfer-deadletter-false--prefetch-0--mode--receivesettlemode-peeklock---receiversettlemode-peeklock--1----idle-timeout-0----kwargs-).

It would be fantastic to get your feedback on this new client, and whether this resolves the issue you reported.

Thanks!

**Comment by itaysk** [comment]
I no longer use Azure or Python so I can't validate the solution. Hence I'm closing this issue.
