### ISSUE TITLE
Retrieve Service Bus Queue length

### ISSUE THREAD

**Issue by geeday** [Azure/azure-sdk-for-python#997]
When I run the following code on a Service Bus queue, an empty queue gives "c = 15". If I add 3 messages using the same SDK, I get "c=18". 

`a = ServiceBusService(blah)
b=a.get_queue(qName)
c=b.message_count`

**Comment by annatisch** [comment]
Hi @geeday - Is this a brand new queue?
It's possible that there are deferred messages in the queue, that cannot be received by standard receive operation - and therefore it appears that the queue is empty when it is not.
If you check the message count of a brand new queue, does it still show ~15 messages?

This is just a heads-up to let you know that we have just published a new AMQP-based preview SDK for Service Bus! The API has been newly designed, and you can find documentation here:
- [Overview](https://docs.microsoft.com/en-us/python/api/overview/azure/servicebus?view=azure-python)
- [Reference documentation](https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus?view=azure-python)

**Comment by jfggdl** [comment]
Closing this issue. Please reopen this issue if you still have problems.
