### ISSUE TITLE
load_workspace_from_config() is unable to load workspace when using LocalWebservice

### ISSUE THREAD

**Issue by gel11** [Azure/azure-sdk-for-python#9972]
- **Operating System**:
Ubuntu 18.04.3 LTS
- **Python Version**: 
Python 3.6.9

**Describe the bug**
load_workspace_from_config() is unable to load workspace when using LocalWebservice

**To Reproduce**
```
ws = Workspace.from_config()
model = Model(ws, 'model')

environment = Environment("LocalDeploy")
environment.python.conda_dependencies = CondaDependencies("env/conda_dependencies.yml")

inference_config = InferenceConfig(entry_script="score.py", environment=environment)
deployment_config = LocalWebservice.deploy_configuration(port=8890)
service = Model.deploy(
    ws, "test", [model], inference_config, deployment_config)
```
**Expected behavior**
Should be able to load without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/37292332/75120996-4e782f00-5690-11ea-9b38-2450a0e9e11b.png)

**Additional context**
Docker version 18.05.0-ce, build f150324
azureml-core version: 1.0.85.2

**Comment by rastala** [comment]
Looks like you're trying to use workspace.from_config() from within webservice deployment. To do this, you'd need to:

 1. Include config.json file as dependency to webservice deployment. The config.json can be produced using Webservice.save_config() command.
 2. Within webservice code, instantiate [authentication object](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.authentication?view=azure-ml-py). Reason for this step is that webservice is not authenticated to Workspace automatically.
 3. Then call workspace.from_config(path=location of config.json file., auth= authentication object)

**Comment by rastala** [comment]
Guidance provided, closing issue.
