### ISSUE TITLE
Python Azure Search Client: Document Operations Proposal

### ISSUE THREAD

**Issue by bryevdv** [Azure/azure-sdk-for-python#9982]
## Basics

* Library name: **Azure Cognitive Search client library for Python**

* Language for review: **Python**

* Contacts

  **Alex Ghiondea** (PM)
  **Bryan Van de Ven** (Dev Lead)

## Library Details

* Link to documentation describing the client library: 

  [**README.md**](https://github.com/Azure/azure-sdk-for-python/blob/67162af1c0b179bfdd7daadcbc62096b3b74a1f7/sdk/search/azure-search/README.md) (draft)

* Link to documentation describing the service:

  https://azure.microsoft.com/en-us/services/search/

* REST API docs

  https://docs.microsoft.com/en-us/rest/api/searchservice/

## Artifacts 

Top level document:

https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041

individual interfaces:

* [`SearchApiCredential` API](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#searchapikeycredential-api)

* [`IndexOperationBatch` API](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#indexoperationbatch-api)

* [`SearchIndexClient`](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#searchindexclient-api)

* [Query APIs](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#query-apis)

## Champion Scenarios (Query and Search)

Enable users to query Azure search indices, including filtering, ordering, or selecting specific fields of results. Enable users to obtain search suggestions and autocompletions. 

#### Get the number of documents in an Azure search index

* Target audience: basic developers with general needs (~90%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#1-get-the-number-of-documents-in-an-azure-search-index)

#### Get a specific document in an Azure search index

* Target audience: basic developers with general needs (~90%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#2-get-a-specific-document-in-an-azure-search-index)

#### Search for documents in an Azure search index with simple text

* Target audience: basic developers with general needs (~90%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#3-search-for-documents-in-an-azure-search-index-with-simple-text)

#### Filter search results from an Azure search index

* Target audience: basic developers with general needs (~90%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#3-filter-results-azure-search-index)

#### Get a list of search suggestions

* Target audience: experienced developers with general needs (~50%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#5-get-a-list-of-search-suggestions)

#### Get a list of search auto-completions

* Target audience: experienced developers with general needs (~50%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#6-get-a-list-of-search-auto-completions)

## Champion Scenarios (CRUD and Batch)

Enable users to add, delete, or modify documents in Azure search indices. Provide a Batch interface for performance-sensitive use cases. 

#### Upload documents to an Azure Search index

* Target audience: basic developers with general needs (~90%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#7-upload-documents-to-an-azure-search-index)

#### Delete documents to an Azure Search index

* Target audience: basic developers with general needs (~90%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#8-delete-documents-from-an-azure-search-index)

#### Merge new fields in an existing document

* Target audience: basic developers with general needs (~90%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#9-merge-new-fields-in-an-existing-document)

#### Merge or upload a document in an Azure Search index

* Target audience: basic developers with general needs (~90%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#10-merge-or-upload-a-document-in-an-azure-search-index)

#### Batch CRUD operations on documents

* Target audience: experienced developers with general needs (~50%)
* [Code sample](https://gist.github.com/bryevdv/48323738f27bedb0c5d0d31246e17041#11-batch-crud-operations-on-documents)

**Comment by bryevdv** [comment]
Will re-open on main sdk repo

**Comment by tg-msft** [comment]
(Reopening and just transferring it over so you don't have to re-create the whole thing.)

**Comment by tg-msft** [comment]
(And closing again because apparently Transfer Issue won't let me jump across to azure-sdk????  Sorry for the noise.)
