### ISSUE TITLE
Activity logs export to Eventhub got truncated when consumer client receive it

### ISSUE THREAD

**Issue by luann-trend** [Azure/azure-sdk-for-python#9990]
Package Name: azure-eventhub
Package Version: 5.0.0
Operating System: docker image python:3.7-alpine3.10
Python Version: 3.7

**Describe the bug**
When the activity log is too big (> 20KB) the message send from the eventhub got truncated. 
The consumer client is not able to parse it. 

**To Reproduce**
1. Configure to export the activity logs to the eventhub
2. Start the streaming client from the sample codes "Consume events asynchronously from an EventHub."
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhub#consume-events-from-an-event-hub
3. Generate one of the activity log that conflict with the policies, it will trigger the error activity log in which will include all the policies. Therefore the log size is big, eventhub truncates it and sends to the consumer client.  

**Expected behavior**
Message not be truncated.

*Found similar issue here
https://social.msdn.microsoft.com/Forums/azure/en-US/7800e86a-d76a-4e04-9097-6af17d86e051/activity-logs-events-are-truncated-when-exported-to-eventhub-amp-storage?forum=opinsights&stoAI=10&f=255&MSPPError=-2147181133

**Comment by kaerm** [comment]
@luann-trend thanks for letting us know about this, someone from our team will take a look at it //cc: @yunhaoling @YijunXieMS

**Comment by kaerm** [comment]
The issue does not seem to be related to the SDK but to the Activity Logs @Nkiest, @asheniam , @kamathashwin , @sameergMS

**Comment by luann-trend** [comment]
Any update ?

**Comment by nkiest** [comment]
If this is not an SDK bug, then you need to open a support ticket to address it. However, we (Activity Log) is a pipeline, not the generator of the logs. We don't truncate them ourselves, that is happening with the generating team, who you should contact to request they don't truncate, or create such long logs.
