### ISSUE TITLE
[Storage][Queue] Response from send/update is encoded

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#9995]
- **Package**: azure-storage-queue
- **Version**: latest
- **Operating System**: Any
- **Python Version**:  Any

**Describe the bug**
The response from `QueueClient.send_message` and `QueueClient.update_message` is the message itself, however if an encoding policy has been applied, the returned message is in its encoded form.

**To Reproduce**
```python
from azure.storage.queue import (
  QueueClient,
  TextBase64EncodePolicy,
  TextBase64DecodePolicy,
  QueueMessage,
)
 
qc = QueueClient.from_connection_string(
  conn_str="<your connection string here>", 
  queue_name="<your queue name here>", 
  message_encode_policy=TextBase64EncodePolicy(),
  message_decode_policy=TextBase64DecodePolicy(),
)
 
# Send a message to the queue, and store the resulting message in sent_msg
sent_msg = qc.send_message("Hello, Queues")
 
print(sent_msg["content"])
# note the base64 encoded content
# SGVsbG8sIFF1ZXVlcw==
 
# Read the message we just sent (assuming there weren’t others) and store in received_msg
received_msg = next(qc.receive_messages(messages_per_page=1))
 
print(received_msg["content"])
# note the base64 DECODED content:
# Hello, Queues
 
#Update the message we received before, and store the new updated message in updated_msg
updated_msg = qc.update_message(received_msg)
 
print(updated_msg["content"])
# note the base64 ENCODED content, even though the message that was being updated was decoded.
# SGVsbG8sIFF1ZXVlcw==
```

**Expected behavior**
Message returned by send/update operations should be in its original un-encoded form.

**Additional context**
A fix could be applied to this line here:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L474

Where instead of passing in the encoded content, we should pass in the original value.
(Same fix applies to update operation and async operations)

**Comment by amishra-dev** [comment]
Thanks for recording this Anna. Emily can you please follow up with other platforms and make sure we are all doing the same right thing. 
We will have to also consider if the fix is a breaking change.
